### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by Samrose-Ahmed** [microsoft/pylance-release#10]
Release mentioned docstring support. Couldn't find anything.

How do you use it?

**Comment by erictraut** [comment]
Docstrings for modules, classes, functions, methods and properties will appear in hover text (when you hover over a symbol), in signature help (the text that appears when you're typing a call expression to help you fill in the correct arguments), and in completion suggestions (as you scroll through the list of suggested completions that are provided when you type).

**Comment by heejaechang** [comment]
FYI, you can see docstrings shows up, completion, signature help, hover

![docstring](https://user-images.githubusercontent.com/1333179/86222647-63336a80-bb3b-11ea-8572-f58247b411f1.gif)

**Comment by Destaq** [comment]
@heejaechang This does not seem to be working for me - I tried writing the exact same code as you, but nothing showed up.


![oddity](https://user-images.githubusercontent.com/61620873/86373682-f2e43080-bc83-11ea-85a2-e5fe7ff9b2be.gif)

**Comment by heejaechang** [comment]
so, I see signature help shows doc string. since you didn't try hover, I am not sure about hover. so I guess you are talking about completion?

for completion tooltip, can you give a pause after typing T or meth so that vscode doesn't cancel tooltip out before it showing it?

**Comment by Destaq** [comment]
@heejaechang Yes I'm interested in the completion, that is the #1 feature for me. In your video that you posted, it seemed like it worked completely for you (see below):

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/61620873/86396221-ce974c80-bca1-11ea-9480-66593129a461.gif)

Hovering *does* work for me. However, what I am interested in is the second box to the side of the completion list that describes the docstring.

When I run it as so:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/61620873/86396398-25048b00-bca2-11ea-92c5-28e23340544f.gif)

I do **not get any completion**.

**Comment by jakebailey** [comment]
You have it hidden in VS Code.

Hit Ctrl+Space, or hover over the completion item and click the "(i)" icon on the right.

**Comment by Destaq** [comment]
Is there any way to have this open by default? It is less helpful if we have to hover and hit or press key combinations each time.

**Comment by Destaq** [comment]
Thank you! That did the trick - I must have had it off by default for VS Code, and I have never had access to that second box before. This works now.

**Comment by jakebailey** [comment]
It stays open if you open it once, until you repeat the step again to disable it. This is a VS Code behavior, you probably want to ask them to allow it to never be hidden.

I don't know what the key combo is on Mac, but the hover and click method will work to enable it.

**Comment by jakebailey** [comment]
Thanks for confirming!
