### ISSUE TITLE
Missing Pyside2 / Pyside6 library autocompletion feature

### ISSUE THREAD

**Issue by LeoCCR** [microsoft/pylance-release#1008]
Current version of Pylance doesn't support many autocompletion for Pyside or PyQt library, those are really good GUI design packages for python, hope this feature will be available in future version!

**Comment by jakebailey** [comment]
PyQt5 is stubbed; do you have any specific examples of things that do not work? Is your issue the same as #454?

pyside hasn't been updated in 5 years, and only targets the now-defunct Qt4; are you referring to pyside2?

Note that both of these packages are compiled, so we don't have any insight into their contents, and therefore need stubs to accurately describe that behavior. PyQt5 does this, so should work.

**Comment by LeoCCR** [comment]
Sorry for my inaccuracy in description. Yes, I'm referring  to Pyside2 and now the latest one should be Pyside6. Since I mostly use Pyside2, and both PyQt5 and Pyside2 share a command Qt library and their syntax almost the same, so I thought Pylance didn't support autocompletion for PyQt5. I've tried PyQt5 in VS code, autocompletion worked perfectly! Can't wait for Pylance to support Pyside2 and Pyside6.

(I've change the title to more accurate description.)

**Comment by tjohanssonn** [comment]
Is this feature on the roadmap to be implemented? It would be very helpful with auto-completion. [PySide6 is also recommended by Qt themselves](https://doc.qt.io/qtforpython/index.html).

**Comment by jakebailey** [comment]
This isn't a feature, it's a library that is compiled and ships without type information. PyQt5 is shipped with generated stubs that make it usable. pyside6 must not, otherwise it would probably be working already.

**Comment by JDavidson2019** [comment]
Hello, @jakebailey ; thank you for your help on this issue. I wanted to chime in as this has recently been becoming an issue for me as well. I am not terribly familiar with stubs, so do forgive me if any of the following is incorrect. Whereas I do not see proper Typing for the PySide6 library (trying to find a definition for PySide6 takes me to the __init__.py file), there are some classes that appear to have some stubs (whether they are properly formatted is a different issue, I presume). For instance, when I go to the definition of the QtWidgets class, it takes me to the QtWidgets.pyi file; however, only some of the classes in this file are found using autocomplete. For instance, the QAbstractButton class is found under the autocomplete menu (code attached below), but the QMainWindow class is not (also attached below). Is this discrepancy due to an issue with the stubs?
```
class QAbstractButton(PySide6.QtWidgets.QWidget):

    def __init__(self, parent:Optional[PySide6.QtWidgets.QWidget]=...) -> None: ...

    def animateClick(self) -> None: ...
    def autoExclusive(self) -> bool: ...
    def autoRepeat(self) -> bool: ...
    def autoRepeatDelay(self) -> int: ...
    def autoRepeatInterval(self) -> int: ...
    def changeEvent(self, e:PySide6.QtCore.QEvent) -> None: ...
    def checkStateSet(self) -> None: ...
    def click(self) -> None: ...
    def event(self, e:PySide6.QtCore.QEvent) -> bool: ...
    def focusInEvent(self, e:PySide6.QtGui.QFocusEvent) -> None: ...
    def focusOutEvent(self, e:PySide6.QtGui.QFocusEvent) -> None: ...
    def group(self) -> PySide6.QtWidgets.QButtonGroup: ...
    def hitButton(self, pos:PySide6.QtCore.QPoint) -> bool: ...
    def icon(self) -> PySide6.QtGui.QIcon: ...
    def iconSize(self) -> PySide6.QtCore.QSize: ...
    def isCheckable(self) -> bool: ...
    def isChecked(self) -> bool: ...
    def isDown(self) -> bool: ...
    def keyPressEvent(self, e:PySide6.QtGui.QKeyEvent) -> None: ...
    def keyReleaseEvent(self, e:PySide6.QtGui.QKeyEvent) -> None: ...
    def mouseMoveEvent(self, e:PySide6.QtGui.QMouseEvent) -> None: ...
    def mousePressEvent(self, e:PySide6.QtGui.QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, e:PySide6.QtGui.QMouseEvent) -> None: ...
    def nextCheckState(self) -> None: ...
    def paintEvent(self, e:PySide6.QtGui.QPaintEvent) -> None: ...
    def setAutoExclusive(self, arg__1:bool) -> None: ...
    def setAutoRepeat(self, arg__1:bool) -> None: ...
    def setAutoRepeatDelay(self, arg__1:int) -> None: ...
    def setAutoRepeatInterval(self, arg__1:int) -> None: ...
    def setCheckable(self, arg__1:bool) -> None: ...
    def setChecked(self, arg__1:bool) -> None: ...
    def setDown(self, arg__1:bool) -> None: ...
    def setIcon(self, icon:Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap]) -> None: ...
    def setIconSize(self, size:PySide6.QtCore.QSize) -> None: ...
    def setShortcut(self, key:Union[PySide6.QtGui.QKeySequence, PySide6.QtCore.QKeyCombination, PySide6.QtGui.QKeySequence.StandardKey, str, int]) -> None: ...
    def setText(self, text:str) -> None: ...
    def shortcut(self) -> PySide6.QtGui.QKeySequence: ...
    def text(self) -> str: ...
    def timerEvent(self, e:PySide6.QtCore.QTimerEvent) -> None: ...
    def toggle(self) -> None: ...
```

```
class QMainWindow(PySide6.QtWidgets.QWidget):
    AnimatedDocks            : QMainWindow.DockOption = ... # 0x1
    AllowNestedDocks         : QMainWindow.DockOption = ... # 0x2
    AllowTabbedDocks         : QMainWindow.DockOption = ... # 0x4
    ForceTabbedDocks         : QMainWindow.DockOption = ... # 0x8
    VerticalTabs             : QMainWindow.DockOption = ... # 0x10
    GroupedDragging          : QMainWindow.DockOption = ... # 0x20

    class DockOption(Shiboken.Enum):
        AnimatedDocks            : QMainWindow.DockOption = ... # 0x1
        AllowNestedDocks         : QMainWindow.DockOption = ... # 0x2
        AllowTabbedDocks         : QMainWindow.DockOption = ... # 0x4
        ForceTabbedDocks         : QMainWindow.DockOption = ... # 0x8
        VerticalTabs             : QMainWindow.DockOption = ... # 0x10
        GroupedDragging          : QMainWindow.DockOption = ... # 0x20


    class DockOptions(object):


    def __init__(self, parent:Optional[PySide6.QtWidgets.QWidget]=..., flags:PySide6.QtCore.Qt.WindowFlags=...) -> None: ...

    @typing.overload
    def addDockWidget(self, area:PySide6.QtCore.Qt.DockWidgetArea, dockwidget:PySide6.QtWidgets.QDockWidget) -> None: ...
    @typing.overload
    def addDockWidget(self, area:PySide6.QtCore.Qt.DockWidgetArea, dockwidget:PySide6.QtWidgets.QDockWidget, orientation:PySide6.QtCore.Qt.Orientation) -> None: ...
    @typing.overload
    def addToolBar(self, area:PySide6.QtCore.Qt.ToolBarArea, toolbar:PySide6.QtWidgets.QToolBar) -> None: ...
    @typing.overload
    def addToolBar(self, title:str) -> PySide6.QtWidgets.QToolBar: ...
    @typing.overload
    def addToolBar(self, toolbar:PySide6.QtWidgets.QToolBar) -> None: ...
    def addToolBarBreak(self, area:PySide6.QtCore.Qt.ToolBarArea=...) -> None: ...
    def centralWidget(self) -> PySide6.QtWidgets.QWidget: ...
    def contextMenuEvent(self, event:PySide6.QtGui.QContextMenuEvent) -> None: ...
    def corner(self, corner:PySide6.QtCore.Qt.Corner) -> PySide6.QtCore.Qt.DockWidgetArea: ...
    def createPopupMenu(self) -> PySide6.QtWidgets.QMenu: ...
    def dockOptions(self) -> PySide6.QtWidgets.QMainWindow.DockOptions: ...
    def dockWidgetArea(self, dockwidget:PySide6.QtWidgets.QDockWidget) -> PySide6.QtCore.Qt.DockWidgetArea: ...
    def documentMode(self) -> bool: ...
    def event(self, event:PySide6.QtCore.QEvent) -> bool: ...
    def iconSize(self) -> PySide6.QtCore.QSize: ...
    def insertToolBar(self, before:PySide6.QtWidgets.QToolBar, toolbar:PySide6.QtWidgets.QToolBar) -> None: ...
    def insertToolBarBreak(self, before:PySide6.QtWidgets.QToolBar) -> None: ...
    def isAnimated(self) -> bool: ...
    def isDockNestingEnabled(self) -> bool: ...
    def isSeparator(self, pos:PySide6.QtCore.QPoint) -> bool: ...
    def menuBar(self) -> PySide6.QtWidgets.QMenuBar: ...
    def menuWidget(self) -> PySide6.QtWidgets.QWidget: ...
    def removeDockWidget(self, dockwidget:PySide6.QtWidgets.QDockWidget) -> None: ...
    def removeToolBar(self, toolbar:PySide6.QtWidgets.QToolBar) -> None: ...
    def removeToolBarBreak(self, before:PySide6.QtWidgets.QToolBar) -> None: ...
    def resizeDocks(self, docks:Sequence[PySide6.QtWidgets.QDockWidget], sizes:Sequence[int], orientation:PySide6.QtCore.Qt.Orientation) -> None: ...
    def restoreDockWidget(self, dockwidget:PySide6.QtWidgets.QDockWidget) -> bool: ...
    def restoreState(self, state:Union[PySide6.QtCore.QByteArray, bytes], version:int=...) -> bool: ...
    def saveState(self, version:int=...) -> PySide6.QtCore.QByteArray: ...
    def setAnimated(self, enabled:bool) -> None: ...
    def setCentralWidget(self, widget:PySide6.QtWidgets.QWidget) -> None: ...
    def setCorner(self, corner:PySide6.QtCore.Qt.Corner, area:PySide6.QtCore.Qt.DockWidgetArea) -> None: ...
    def setDockNestingEnabled(self, enabled:bool) -> None: ...
    def setDockOptions(self, options:PySide6.QtWidgets.QMainWindow.DockOptions) -> None: ...
    def setDocumentMode(self, enabled:bool) -> None: ...
    def setIconSize(self, iconSize:PySide6.QtCore.QSize) -> None: ...
    def setMenuBar(self, menubar:PySide6.QtWidgets.QMenuBar) -> None: ...
    def setMenuWidget(self, menubar:PySide6.QtWidgets.QWidget) -> None: ...
    def setStatusBar(self, statusbar:PySide6.QtWidgets.QStatusBar) -> None: ...
    def setTabPosition(self, areas:PySide6.QtCore.Qt.DockWidgetAreas, tabPosition:PySide6.QtWidgets.QTabWidget.TabPosition) -> None: ...
    def setTabShape(self, tabShape:PySide6.QtWidgets.QTabWidget.TabShape) -> None: ...
    def setToolButtonStyle(self, toolButtonStyle:PySide6.QtCore.Qt.ToolButtonStyle) -> None: ...
    def setUnifiedTitleAndToolBarOnMac(self, set:bool) -> None: ...
    def splitDockWidget(self, after:PySide6.QtWidgets.QDockWidget, dockwidget:PySide6.QtWidgets.QDockWidget, orientation:PySide6.QtCore.Qt.Orientation) -> None: ...
    def statusBar(self) -> PySide6.QtWidgets.QStatusBar: ...
    def tabPosition(self, area:PySide6.QtCore.Qt.DockWidgetArea) -> PySide6.QtWidgets.QTabWidget.TabPosition: ...
    def tabShape(self) -> PySide6.QtWidgets.QTabWidget.TabShape: ...
    def tabifiedDockWidgets(self, dockwidget:PySide6.QtWidgets.QDockWidget) -> List[PySide6.QtWidgets.QDockWidget]: ...
    def tabifyDockWidget(self, first:PySide6.QtWidgets.QDockWidget, second:PySide6.QtWidgets.QDockWidget) -> None: ...
    def takeCentralWidget(self) -> PySide6.QtWidgets.QWidget: ...
    def toolBarArea(self, toolbar:PySide6.QtWidgets.QToolBar) -> PySide6.QtCore.Qt.ToolBarArea: ...
    def toolBarBreak(self, toolbar:PySide6.QtWidgets.QToolBar) -> bool: ...
    def toolButtonStyle(self) -> PySide6.QtCore.Qt.ToolButtonStyle: ...
    def unifiedTitleAndToolBarOnMac(self) -> bool: ...
```

**Comment by jakebailey** [comment]
If you're saying they have stubs and some things appear, then it may be a case that the `QMainWindow` isn't exported in the way you're using it. Those all look like reasonable stubs to me, and at a glance I don't see a reason why they wouldn't work.

**Comment by erictraut** [comment]
The Pyside6 `__init__.py` file defines `__all__` in a dynamic manner, so static type checkers will not work with it. If this library is important to you, please work with the library maintainer to define `__all__` in a way that conforms to [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface), which we established by working with other Python type checkers and language servers.

```python
__all__ = list("Qt" + body for body in "Core;Gui;Widgets;...".split(";"))
```

should be changed to

```python
__all__ = ["QtCore", "QtGui", "QtWidgets", ...]
```

**Comment by JDavidson2019** [comment]
Thank you both for your responses. Interestingly enough, there was an update to PySide6 released on July 1, 2021, and when I updated from 6.1.1 -> 6.1.2, vscode and/or Pylance was able to resolve and successfully "autocomplete" all statements. I am still intrigued as to why the update resolved the issues, but the [changelog](https://code.qt.io/cgit/pyside/pyside-setup.git/tree/dist/changes-6.1.2?h=6.1.2&id=d3170ad444d57aa12d713198ca42653805e015bc) states "...missing classes, enumeration and functions have been added", so I assume somewhere along the line, they modified the export that @jakebailey was referring to. It doesn't appear they have modified the `__all__` definition, however. Regardless, it seems to work fine now, so thank you again for the help.

**Comment by jakebailey** [comment]
As far as I can tell, the bad `__all__` is still there: https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/pyside6/PySide6/__init__.py.in?h=6.1.2#n6

Why they have chosen to place a `;` separated string here and then split at runtime when they are already using macros to produce the file is beyond me...

**Comment by tjohanssonn** [comment]
> Thank you both for your responses. Interestingly enough, there was an update to PySide6 released on July 1, 2021, and when I updated from 6.1.1 -> 6.1.2, vscode and/or Pylance was able to resolve and successfully "autocomplete" all statements. I am still intrigued as to why the update resolved the issues, but the [changelog](https://code.qt.io/cgit/pyside/pyside-setup.git/tree/dist/changes-6.1.2?h=6.1.2&id=d3170ad444d57aa12d713198ca42653805e015bc) states "...missing classes, enumeration and functions have been added", so I assume somewhere along the line, they modified the export that @jakebailey was referring to. It doesn't appear they have modified the `__all__` definition, however. Regardless, it seems to work fine now, so thank you again for the help.

Thank you for the tip. I tried to update as well, but I can't say for sure it's better than previously.

@jakebailey I misunderstood your first answer on this issue, about stubs. I thought you somehow had implemented stubs yourself for PyQt 😳 

Thank you for the help. I will try to contact the library maintainer about this issue with PySide6.

**Comment by jakebailey** [comment]
> I guess that a restart of the language server after upgrading triggered the resolving.

Yes, library installs are currently not tracked due to file watching issues (#923).

**Comment by jakebailey** [comment]
I think I'll close this; originally we weren't sure they had any, but they do, and any issues with the pyside stubs should be reported upstream.
