### ISSUE TITLE
How to use the extension?

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#101]
## Environment data
-   Language Server version: 2020.7.1 (This is the version from Cmd+Shift+X, I don't have the "Python Language Server" thing in the "Output" tab)
-   OS and version: macOS 10.14.6 (18G103)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.10, miniconda

## Description
I rejected the initial suggestion to "activate" Pylance just after installation, because I wanted to try it later. Now, I have no idea how to activate it or check if it is actually working (I see no difference when coding). Reinstalling doesn't help, the suggestion doesn't pop up anymore. I suppose this is a bug in a sense that such simple scenario should not be a source of confusion to a user (additional instructions in README would help I think).

**Comment by jongio** [comment]
I ran into this as well.

Try adding this to your settings.json

![image](https://user-images.githubusercontent.com/2163001/87317098-68999900-c4db-11ea-839d-e850cd68325f.png)

```json
{
"python.languageServer": "Pylance",
}
```

**Comment by Yura52** [comment]
@jongio thanks, it helped! I didn't try that exactly because of the fact that Pylance is not in the list of suggested options (which is "Jedi, Microsoft, None").

**Comment by jongio** [comment]
@jakebailey - Thoughts on where we could put this in the docs?  Maybe in the readme, under manual setup?

**Comment by savannahostrowski** [comment]
Hey @Yura52  and @jongio!

Thanks for the feedback! We will be adding `Pylance` as a supported `python.languageServer` value in the near future (meaning that you'll see the `Pylance` as a value when editing your settings.json and in the settings editor UI). In the meantime, we will be amending our troubleshooting documentation to add this note in to help out others running into this.

**Comment by jakebailey** [comment]
The readme here and in the published extension are now updated.

**Comment by jongio** [comment]
Nice,  Thanks @jakebailey
