### ISSUE TITLE
Syntax highlighting not working for type hint `Type[MyClass]`

### ISSUE THREAD

**Issue by gijswobben** [microsoft/pylance-release#1012]
## Environment data

-   Language Server version: v2021.3.0
-   OS and version: Windows 10 (WSL2 Ubuntu)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.1 (default, Jan 28 2021, 11:59:23)

## Expected behaviour

Minimal example:

```python
from typing import Type


class MyClass:
    ...


def test_function() -> Type[MyClass]:
    return MyClass


ChangedMyClass = test_function()

test = ChangedMyClass()
test_2 = MyClass()
```

I'm expecting `ChangedMyClass` to be highlighted like `MyClass`, since the type hint shows that the function returns the class (not an instance).

## Actual behaviour

The type hint is not used for syntax highlighting:

![image](https://user-images.githubusercontent.com/3183856/109926590-6af77000-7cc3-11eb-80b9-6f27bde79b54.png)

![image](https://user-images.githubusercontent.com/3183856/109926763-9c703b80-7cc3-11eb-94fd-18edd07b7a4a.png)

**Comment by erictraut** [comment]
The symbol `MyClass` is a class, whereas `ChangedMyClass` is a variable (that is of type `Type[MyClass]` and therefore contains a reference to `MyClass` or any subtype thereof). Classes are semantically different from variables, which is why you're seeing the difference in coloring here.

**Comment by gijswobben** [comment]
> The symbol `MyClass` is a class, whereas `ChangedMyClass` is a variable (that is of type `Type[MyClass]` and therefore contains a reference to `MyClass` or any subtype thereof). Classes are semantically different from variables, which is why you're seeing the difference in coloring here.

Why would it be a variable? I'm returning a reference to the class definition...

Anyway, still feels weird from a developer point of view:
![image](https://user-images.githubusercontent.com/3183856/109927952-35538680-7cc5-11eb-9de1-6eb7d0520172.png)
They look the same, but are not syntax highlighted the same.

**Comment by erictraut** [comment]
Anything of the form `x = <expression>` or `x: <type annotation>` is a variable declaration. Anything of the form `class y: ...` is a class declaration.

`x` is a variable. You happen to be assigning a class reference to it, but that doesn't change the fact that it's a variable.

Consider the following:
```python
x = int
x = int(3)
```

 `x` is a variable in this example. In the first line, it is assigned a class, and in the second line it is assigned an instance of that class. It remains a variable in both lines. Its semantic category doesn't change, and `x` will be colored the same in both lines.

**Comment by judej** [comment]
@gijswobben, there is related issue #857 that is marked as an enhancement request. Please upvote that to support that enhancement.

thanks
