### ISSUE TITLE
"Go to symbol in workspace..." action frequently hangs

### ISSUE THREAD

**Issue by zbs** [microsoft/pylance-release#1015]
Often times my "Go to symbol in workspace..." action hangs. I noticed that it tends to happen when there is binding/parsing/indexing output in the `Python Language Server` output pane. I'm not sure what is triggering these indexings but it seems to be needlessly indexing the entire workspace. For reference, I have `python.analysis.indexing: true` in my settings (although FWIW, VS Code considers it an unused setting).

My Pylance version is 2021.3.0 and my VS Code version is 1.53.2. I am also using VS Code with Remote SSH on Windows 10.

**Comment by jakebailey** [comment]
> needlessly indexing the entire workspace

The point of the indexing is precisely to index the whole workspace, such that features that want to search everything (auto-import, workspace symbols, etc) work without having to open files which transitively pull in their contents.

Do you have logs for this case? Are there specific files that you think we shouldn't be analyzing, or are too slow to analyze?

**Comment by zbs** [comment]
I understand that it needs to index the whole workspace, but not on file changes, right? Shouldn't it only need to index what's changed? I will find logs the next time it repros. Thanks!

**Comment by jakebailey** [comment]
No, on file changes it shouldn't index anything (maybe some things) unless we are somehow seeing these changes as library changes where we can't understand the range of effects. Some trace logs would be great.

**Comment by zbs** [comment]
I can't consistently repro now, so I'll reopen when I have a reliable repro + logs. Thanks for your input!
