### ISSUE TITLE
"tuple" is not defined

### ISSUE THREAD

**Issue by ilogue** [microsoft/pylance-release#1018]
I get a reportUndefinedVariable for the following code:

```
tuple([1, 2])
```

but `tuple` is a built-in class constructor.

## Environment data

- VS Code 1.52.2
- Ubuntu 20.04
- python 3.8.5
- pylance v2021.3.0

## Expected behaviour

for the tuple constructor to not be marked undefined

## Actual behaviour

the builtin tuple constructor is marked as undefined

## Code Snippet / Additional information

documentation on the Tuple constructor:
https://docs.python.org/3/library/stdtypes.html#tuple

**Comment by judej** [comment]
Could you please add the code example and the logs? Instructions can be found here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

thanks

**Comment by ilogue** [comment]
The code example is as above, i.e.:

```python
tuple([1, 2])
```

Here's the logs:

> [BG(1)] analyzing: /home/<snip path>/script.py ...
> [BG(1)]   checking: /home/<snip path>/script.py (6ms)
> [BG(1)] analyzing: /home/<snip path>/script.py (6ms)
> Background analysis message: resumeAnalysis
> Background analysis message: getDiagnosticsForRange
> Background analysis message: getDiagnosticsForRange

**Comment by jakebailey** [comment]
If those are the entire logs, then that implies something's very wrong with your Pylance installation. Do you have the entire log with the header? We normally print quite a bit more at the start.

These logs are implying we can't find the stubs we ship with, which are required for the builtins/stdlib.

**Comment by jakebailey** [comment]
Without the full logs, we can't really do anything here. I'm going to close this (as it's been a month without an update), but if you're seeing this in the current release and can provide the logs, we can reopen.
