### ISSUE TITLE
Unable to auto complete basic template

### ISSUE THREAD

**Issue by Jebearssica** [microsoft/pylance-release#1019]
In 2020, it can still auto complete the basic template, such as "While/For/Class/With/If...". When I print "if", it can automatically complete a code template for me. Is there any changes in later version that I need to set some configurations in settings?

There used to be a code template.

![TIM截图20210307182538](https://user-images.githubusercontent.com/29978190/110236752-9358c600-7f72-11eb-8dcd-82419ce95fc7.png)

## Env

```shell
vscode:1.54.1
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
Pylance: 2021.3.0
```

**Comment by jakebailey** [comment]
Pylance doesn't provide these snippets. The Python extension did, and recently removed them as they interfered with other editor features.

See https://github.com/microsoft/vscode-python/issues/15220#issuecomment-767840313 (and the linked workarounds).
