### ISSUE TITLE
Pylance reports no overloads for min()/max() functions when overloads are available

### ISSUE THREAD

**Issue by aconncep** [microsoft/pylance-release#1022]
## Environment data

-   Language Server version: 2021.3.0
-   OS and version: Windows 10 Build 21327 (Insider)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.2

## Expected behaviour

Pylance reports no issues.

## Actual behaviour

Pylance reports no overloads for the min() or max() functions, for example when passing the `key` attribute. This is supported by Python and the code compiles and runs perfectly fine despite the warning from Pylance.

## Logs

[Info  - 7:10:53 PM] Pylance language server 2021.3.0 (pyright eb716c0a) starting
[Info  - 7:10:53 PM] Server root directory: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist
[Error - 7:10:53 PM] stubPath c:\Users\austi\Desktop\Data Mining HW5\typings is not a valid directory.
[Info  - 7:11:11 PM] No configuration file found.
[Info  - 7:11:11 PM] Setting pythonPath for service "Data Mining HW5": "C:\Users\austi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe"
Search paths found for configured python interpreter:
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\DLLs
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib
  C:\Users\austi\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0
  C:\Users\austi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\site-packages
[Error - 7:11:11 PM] stubPath c:\Users\austi\Desktop\Data Mining HW5\typings is not a valid directory.
[Info  - 7:11:11 PM] Assuming Python version 3.9
[Info  - 7:11:11 PM] Assuming Python platform Windows
[Info  - 7:11:11 PM] Searching for source files
[Info  - 7:11:11 PM] Found 3 source files
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: getSemanticTokens
[BG(1)] parsing: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py (39ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 1ms] (72ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\builtins.pyi (23ms)
[BG(1)] binding: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py (2ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\sys.pyi [fs read 0ms] (9ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\sys.pyi (2ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\__init__.pyi [fs read 0ms] (7ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\__init__.pyi (1ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 0ms] (9ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (1ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\typing.pyi [fs read 0ms] (21ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\typing.pyi (8ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stubs\typing-extensions\typing_extensions.pyi [fs read 0ms] (3ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stubs\typing-extensions\typing_extensions.pyi (1ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\io\api.pyi [fs read 0ms] (101ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\io\api.pyi (0ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\io\parsers.pyi [fs read 0ms] (32ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\io\parsers.pyi (3ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\_typing.pyi [fs read 0ms] (58ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\_typing.pyi (1ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\os\__init__.pyi [fs read 0ms] (13ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\os\__init__.pyi (3ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\abc.pyi [fs read 1ms] (1ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\abc.pyi (0ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\datetime.pyi [fs read 0ms] (6ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\datetime.pyi (3ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\frame.pyi [fs read 1ms] (74ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\frame.pyi (12ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\generic.pyi [fs read 1ms] (38ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\generic.pyi (1ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\base.pyi [fs read 0ms] (13ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\base.pyi (0ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\accessor.pyi [fs read 0ms] (1ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\accessor.pyi (0ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\indexing.pyi [fs read 0ms] (7ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\indexing.pyi (0ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\io.pyi [fs read 0ms] (5ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\io.pyi (1ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\series.pyi [fs read 0ms] (29ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\series.pyi (6ms)
[BG(1)] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\indexes\base.pyi [fs read 0ms] (13ms)
[BG(1)] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\bundled\stubs\pandas\core\indexes\base.pyi (4ms)
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py ...
[BG(1)]   checking: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py (55ms)
[BG(1)] analyzing: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py (55ms)
Background analysis message: resumeAnalysis
[FG] parsing: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py (54ms)
[FG] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 3ms] (76ms)
[FG] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\builtins.pyi (29ms)
[FG] binding: c:\Users\austi\Desktop\Data Mining HW5\HW_05_Cepalia_Austin\HW05_Cepalia_Austin\HW05_Cepalia_Austin_Trainer.py (3ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: markFilesDirty
Background analysis message: analyze
Background analysis message: markFilesDirty
Background analysis message: analyze
Background analysis message: markFilesDirty
Background analysis message: analyze
[FG] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 0ms] (13ms)
[FG] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (1ms)
[FG] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\typing.pyi [fs read 1ms] (21ms)
[FG] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\typing.pyi (9ms)
[FG] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stubs\typing-extensions\typing_extensions.pyi [fs read 1ms] (2ms)
[FG] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stubs\typing-extensions\typing_extensions.pyi (3ms)
[FG] parsing: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\abc.pyi [fs read 0ms] (1ms)
[FG] binding: c:\Users\austi\.vscode\extensions\ms-python.vscode-pylance-2021.3.0\dist\typeshed-fallback\stdlib\abc.pyi (0ms)

```
XXX
```

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/8921807/110398827-a3d87180-8042-11eb-8240-6fc3f275018b.png)

```python
XXX
```

**Comment by erictraut** [comment]
This is now fixed.

**Comment by jakebailey** [comment]
It seems like based on your usage, the overload you're intending to target is: https://github.com/python/typeshed/blob/8115299ee2d3d29e11ce1b351658b8a3306ce47f/stdlib/builtins.pyi#L1053

```
def min(__iterable: Iterable[_T], *, key: Callable[[_T], SupportsLessThanT]) -> _T: ...
```

Making this a concrete example:


```python
from typing import Dict


d: Dict[str, int] = {}

min_value = min(d, key=d.get)
```

![image](https://user-images.githubusercontent.com/5341706/110400398-6a950700-802c-11eb-81cf-95e4f39da30f.png)

`get` itself is overloaded, and the form that is needed in this case is the first one. However, `get` says that it can return `None`, so does not fit the type required; anyone can call `get` with a key that doesn't exist in the dict. The type system has no knowledge that `min` will iterate over the keys of a dict. If I do the work myself to prove to the type system that it always returns a value, then I have no type errors.

```python
def get_from_d(key: str) -> int:
    v = d.get(key)
    assert v is not None
    return v

min_value2 = min(d, key=get_from_d)
```

**Comment by GraphtyLove** [comment]
If anyone has the same issue with dataclasses with Optional types, here is the workaround I found for my case:

```python
from dataclasses import dataclass

@dataclass
class Phone:
    phone: str
    score: int | None = None # Same as score: `Optional[int] = None`

test = [
    Phone(phone="1", score=1),
    Phone(phone="2", score=2),
    Phone(phone="3", score=None),
]

best = max(test, key=lambda x: x.score if x.score else 0)
```
