### ISSUE TITLE
Missing type error for Type[T] usage

### ISSUE THREAD

**Issue by thomaseding** [microsoft/pylance-release#1024]
## Environment data

-   Language Server version: Pylance v2021.3.0
-   OS and version: MacOS Catalina 10.15
-   Python version: Python 3.8.2 64-bit

## Expected behaviour

```
T = TypeVar("T")

def static_isinstance(_value: T, _type: Type[T]):
    pass

static_isinstance("", int) # Expected typing error!
```

## Actual behaviour

No typing error

## Notes

Analogous code correctly type checks in Typescript for what it's worth.

## Motivation Use Case

Suppose we have
```
Foo = Union[X, Y]

if isinstance(foo, X):
    do_something_with_X(foo)
else:
    do_something_with_Any(foo)
```

but later update `Foo` to
```
Foo = Union[X, Y, Z]
```

Now the missing case for handling `Z` is lost due to the generic handling in the `else` case. To future proof the code, it could have been written as
```
if isinstance(foo, X):
    do_something_with_X(foo)
else:
    static_isinstance(foo, Y)
    do_something_with_Any(foo)
```

**Comment by thomaseding** [comment]
Oh dang. Is what I wrote possible to do in some other fashion?

**Comment by erictraut** [comment]
I recently added a feature called "implied else narrowing" that might address your use case. For documentation, see [here](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#narrowing-for-implied-else).

Using your example above:
```python
class X: ...
class Y: ...
class Z: ...

Foo = Union[X, Y]

def func(foo: Foo) -> str:
    if isinstance(foo, X):
        return "X"
    elif isinstance(foo, Y):
        return "Y"
```

This type checks without error. But if you now add `Z` to the `Foo` type alias, you'll receive an error. Does that help?

**Comment by thomaseding** [comment]
It helps to an extent, but falls short in some cases.

Example:
```
Foo = Union[X, Y]

def func(foo: Foo) -> None:
    if isinstance(foo, X):
        print("X")
    elif isinstance(foo, Y):
        print("Y")
    else:
        # foo inferred as Never, but doesn't seem accessible in PEP 484
        pass
```

```
Foo = Union[X, Y, Z]
foo(Z()) # oops!
```

Looks like Pylance will infer `Never` types.

I'll try hacking around a bit for a more robust solution.

**Comment by erictraut** [comment]
Here's another potential solution. You can use the `NoReturn` type (which is semantically the same as `Never` and is defined in PEP 484) to your advantage:

```python
class X: ...
class Y: ...
class Z: ...

Foo = Union[X, Y]

def assert_never(val: NoReturn):
    raise Exception("Should never get here!")

def func(foo: Foo) -> str:
    if isinstance(foo, X):
        return "X"
    elif isinstance(foo, Y):
        return "Y"
    else:
        assert_never(foo)
```

Incidentally, there is [a recent discussion](https://mail.python.org/archives/list/typing-sig@python.org/thread/CVZKTJRSOQDMC7T4A7HN6ZPIV3LOSOY2/) in the Python typing-sig (the body that discusses and approves changes to the typing standards in Python) to add `Never` as an official alias for `NoReturn`.

**Comment by thomaseding** [comment]
Awesome! That works for me. Much thanks :)
