### ISSUE TITLE
reportMissingModuleSource errors repored for Django modules

### ISSUE THREAD

**Issue by OmidShojaee** [microsoft/pylance-release#1025]
I have "insider build" enabled, so I assume I have the latest version.

I have TONS of ```reportMissingModuleSource``` errors in my code, and all of them are related to Django's standard modules from ```django.contrib``` to ```django.urls```. These are BASIC Django modules !

Pylint is much more stable and useful !

**Comment by jakebailey** [comment]
This issue has been in the "waiting for info" state for over a month; I'm going to close this. If you can provide the requested info, we can reopen to take a look, but until then we don't have enough information to look into this.

**Comment by jimnarey** [comment]
Hi,

I have exactly the same issue as reported above.

Pylance version: 2021.4.1

Python version: 3.8.5

requirements.txt:

appdirs==1.4.4
apturl==0.5.2
asgiref==3.3.4
blinker==1.4
Brlapi==0.7.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
contextlib2==0.6.0.post1
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distlib==0.3.1
distro==1.4.0
distro-info===0.23ubuntu1
Django==3.2
dnspython==1.16.0
docopt==0.6.2
entrypoints==0.3
filelock==3.0.12
gpg===1.13.1-unknown
httplib2==0.14.0
idna==2.8
internetarchive==2.0.2
jsonpatch==1.32
jsonpointer==2.1
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
louis==3.12.0
macaroonbakery==1.3.1
Markdown==3.1.1
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
packaging==20.3
pbr==5.5.1
pexpect==4.6.0
Pillow==7.0.0
protobuf==3.6.1
pycairo==1.16.2
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.3.1
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyparsing==2.4.6
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.4
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
schema==0.7.4
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
simplejson==3.16.0
six==1.14.0
sqlparse==0.4.1
ssh-import-id==5.10
stevedore==3.3.0
systemd-python==234
tqdm==4.60.0
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
virtualenv==20.4.3
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
wadllib==1.3.3
xkit==0.0.0

I am using Pylance's remote development feature via SSH, running Xubuntu 20 on the development machine and Ubuntu 20 on the server. I have selected the correct interpreter on the server machine.

In urls.py (project and app) I am getting reportMissingModuleSource for django.contrib and django.urls in the import lines. 

The development server runs fine.

Thanks.
