### ISSUE TITLE
Auto-import code actions do not work in notebooks

### ISSUE THREAD

**Issue by nfx** [microsoft/pylance-release#1033]
In order to simplify development experience, i'd like to see so much used import hints in VSCode.
![image](https://user-images.githubusercontent.com/259697/110245724-bbd9c380-7f64-11eb-9c7a-8c4b9cc6fd7d.png)

**Comment by jakebailey** [comment]
Pylance supports quick fixes for undefined variables of this nature. If you enable Pylance you should be able to try it out.

**Comment by nfx** [comment]
@jakebailey what's the difference between pylance, mspython, etc etc?.. i'm confused.

**Comment by jakebailey** [comment]
The Python extension supports multiple "language servers", which provide functionality such as diagnostics, completions, tooltips, etc. By default, the Python extension bundles and uses jedi.

To run pylance instead, you can follow the quickstart guide in our README: https://github.com/microsoft/pylance-release#quick-start

**Comment by nfx** [comment]
@jakebailey okay, pylance is def better for normal editor, thanks for pointing to it, but it doesn't work for native Jupyter
![image](https://user-images.githubusercontent.com/259697/110865809-80245e00-82c4-11eb-81ab-937ab3c4cad7.png)
![image](https://user-images.githubusercontent.com/259697/110865877-98947880-82c4-11eb-9d5f-2e7d38160145.png)

**Comment by jakebailey** [comment]
Are you using the old-style notebooks, or "native notebooks"? I'm not sure that the the old-style notebooks support quick fixes, but the newer native notebooks may.

**Comment by nfx** [comment]
@jakebailey i use "native notebooks" when insiders build is **not broken 😝 ** (50% of the time)

**Comment by jakebailey** [comment]
I see. It's very possible that their custom LSP -> notebook logic doesn't yet support quick fixes like these. They have to do a bit of massaging to the messages to make them apply to notebooks (and the notebook API may not even support them quite yet either, I'm unsure).

But, we're sort of unable to change anything in this area ourselves. We give quick fixes when requested, and it's up to the client (in this case, the Jupyter extension) to request and display them.

@rchiodo Do you know if quick fix support has been hooked up?

**Comment by rchiodo** [comment]
I believe 'quick fixes' are code actions, right? These are not supported because they require the real file to exist. I believe this would require pylance to understand the notebook document. Otherwise it tries to apply the fix to our in memory file.

**Comment by jakebailey** [comment]
Yes, code actions. We don't actually make file changes ourselves, there's a command that returns text edits the client is supposed to be applying, which shouldn't be different than a completion's text edits, right?

**Comment by rchiodo** [comment]
If I remember correctly the code actions returned a command that then went back into the pylance extension. The pylance extension is of course confused at that point because the file doesn't really exist.

**Comment by jakebailey** [comment]
The code action response contains commands which VS Code (or the client in general) runs on acceptance, but the commands themselves do not apply the edits directly to any file from my reading of the code. Seems like a case the middleware needs to rewrite.

I'll also point out that in the above screenshots, I'm not seeing the fixes appear at all, so they wouldn't even get to the place where the command could be run, no? It could be that VSC's notebooks aren't even sending the "give me the code actions for this location" call at all.

@nfx If you hit `Ctrl+.` on the squiggled part of the code, do you see a quick fix menu appear? Or is there no way to access them?

**Comment by rchiodo** [comment]
Code actions are completely canceled in the notebook case. Because the commands when I had them there would just throw exceptions.

I don't think we can rewrite them too because we can't guess as to what to rewrite. A command has arbitrary parameters.

**Comment by jakebailey** [comment]
The command contains paths, but the command is generated by Pylance and returned to Pylance only (nobody else), which then generates the text updates and sends those back as it does other text edits for completions. I wasn't suggesting that all commands in totality have their paths rewritten, just that the text edits we return be rewritten similarly to other positions/ranges for other calls.

I think we should try and not hide the code actions, and see what happens.

**Comment by nfx** [comment]
@jakebailey didn't know about `Ctrl+.`, probably it's cmd+. on mac... is it like alt+enter on intellij?

**Comment by heejaechang** [comment]
code action and command should be disabled under notebook for now. and auto-import on completion should be disabled on notebook as well. we can only enable it once we can make those feature (code generation) notebook aware so that it doesn't generate code in invalid location

**Comment by nfx** [comment]
@heejaechang you can simplify this by generating code in always-top cell - it's already more-or-less convention. same cell will be ideal.

**Comment by heejaechang** [comment]
@nfx we are currently experimenting with multiple approaches to provide better notebook supports in vscode. once we have something concrete, we will let you know. thank you for using Pylance!

**Comment by debonte** [comment]
@nfx, auto-import works for me after opting into the notebooks experiment that we shipped in Pylance [2022.5.3](https://github.com/microsoft/pylance-release/releases/tag/2022.5.3).

Give it a try:

1. Install the latest builds of the Python, Pylance, and Jupyter extensions.
2. Set `"python.pylanceLspNotebooksEnabled": true`
3. Reload VS Code.

**Comment by debonte** [comment]
We're closing this issue since it is fixed when `python.pylanceLspNotebooksEnabled` is set to `true` and as of Python extension version 2022.14.0 that is now the default.

If you are setting `python.pylanceLspNotebooksEnabled` to `false`, we would like to understand why. Please file an issue.
