### ISSUE TITLE
chalice: Expected no arguments to "Blueprint" constructor

### ISSUE THREAD

**Issue by jonathanpascoe** [microsoft/pylance-release#1034]
## Environment data

-   Language Server version: Pylance language server 2021.3.1
-   OS and version: macOS Catalina v10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.7

## Expected behaviour
No `reportGeneralTypeIssues` error. See AWS Chalice [Blueprint](https://github.com/aws/chalice/blob/master/chalice/app.py#L1908-L1910)

## Actual behaviour

```
Expected no arguments to "Blueprint" constructor
```

## Code Snippet / Additional information

<img width="763" alt="Screen Shot 2021-03-11 at 5 10 00 PM" src="https://user-images.githubusercontent.com/53105645/110867608-a75f3900-828c-11eb-92e9-3717e4abef2b.png">

**Comment by jakebailey** [comment]
Can you hover over `Blueprint` to see what we are inferring its `__init__` signature as? If you go-to-declaration, does it take you to a stub file that may have defined this initializer differently?

**Comment by jonathanpascoe** [comment]
Does this help?

![UsvqUmfJur](https://user-images.githubusercontent.com/53105645/110872378-4ab44c00-8295-11eb-81d7-7655ded1b5b9.gif)

**Comment by erictraut** [comment]
It appears that the chalice package includes type stubs, and the [declaration for the `Blueprint` class](https://github.com/aws/chalice/blob/a30d30b7be3d7a0264c57b61f0bdcad6a66b44d9/chalice/app.pyi#L318) doesn't define a constructor.

Pylance is honoring the type stub information shipped with the `chalice` package. If you think the type information is incorrect (and it appears to be based on the implementation of `Blueprint`), I recommend filing a bug report or PR with the [chalice repo](https://github.com/aws/chalice).

**Comment by jakebailey** [comment]
I'm going to close this as there's nothing we can really do on our end here; we respect the stubs that come with the library (and we've previously closed these sorts of upstream issues).

You can feasibly suppress the error yourself for your usage, but it's best to let the library know that their types are incorrect. Those stubs look pretty bare.
