### ISSUE TITLE
Type inference doesn't resolve function after update

### ISSUE THREAD

**Issue by Prunoideae** [microsoft/pylance-release#1041]
## Environment data
- Language Server version : 2021.3.1
- OS and version: Windows 10 Pro Insider Preview Build 21313
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.1 64-bit

## Expected behaviour

given a function and a class:

```python
T = TypeVar("T")
def foo(inner:Type[T]) -> T:
    pass

class bar():
    baz: foo(str)
```

the `baz` field in class `bar` should be annotated as `str`, like pylance did in before.

## Actual behaviour

![image](https://user-images.githubusercontent.com/24620047/111016223-8b23df00-83e7-11eb-83e3-ee58fabd8eef.png)
![image](https://user-images.githubusercontent.com/24620047/111016228-91b25680-83e7-11eb-94c1-9ebc1856aad3.png)

The function is detected but analyzed as an unknown symbol, which makes all type inference become `Any`.

**Comment by erictraut** [comment]
The expression `foo(str)` is not a valid type annotation. You cannot use call expressions in type annotations. Previous versions of pyright failed to mark that as an error, but this was fixed recently.

Perhaps what you meant is the following, which is legal:

```python
class bar:
    baz = foo(str)
```

**Comment by Prunoideae** [comment]
oh thanks, looks like I'll change my code structure now
