### ISSUE TITLE
Type annotation not supported for this type of expression

### ISSUE THREAD

**Issue by jerryc05** [microsoft/pylance-release#1042]
## Environment data

-   Language Server version: `Pylance 2021.3.1`
-   OS and version: `Win10`
-   Python version (& distribution if applicable, e.g. Anaconda): `Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32`

## Expected behaviour

```python
from typing import *
x, y, z = [], [], []  # type: List[int], List[int], List[str]
m, n, o = [], [], []  # type: (List[int], List[int], List[str])
a, b, *c = range(5)   # type: float, float, List[float]
```
This code reports no error, as shown in [PEP 484 #Type Comments](https://www.python.org/dev/peps/pep-0484/#type-comments).

## Actual behaviour

![image](https://user-images.githubusercontent.com/8305074/111020574-f42e3700-8394-11eb-99e2-40bcb0dcd620.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
from typing import *
x, y, z = [], [], []  # type: List[int], List[int], List[str]
m, n, o = [], [], []  # type: (List[int], List[int], List[str])
a, b, *c = range(5)   # type: float, float, List[float]
```

**Comment by erictraut** [comment]
Newer versions of Python have defined syntax for specifying type annotations, and you are encouraged to use that syntax instead.

Type comments are now obsolete and are supported only in a minimal manner within pylance, mainly as a bridge to the new syntax. We don't have plans to invest in further support for type comments.

**Comment by jerryc05** [comment]
Okay. I am requesting this feature because I encountered a strange error when using the type annotation syntax on `MacOS`'s `python 3.7` & `python 3.8`. 

I will attach details about this later.

**Comment by jerryc05** [comment]
Also, I think that type comments could enable us to use the new syntax from Python 3.10 [PEP 604 -- Allow writing union types as X | Y](https://www.python.org/dev/peps/pep-0604/) on earlier Python versions without throwing an error. Am I right?

**Comment by erictraut** [comment]
Let us know more details about the error you encountered, and we'll see if we can help you out there.

You can use PEP 604 annotations in versions prior to Python 3.10 if you enclose the annotation expression in quotes or use `from __future__ import annotations` at the top of the file. Both of those approaches will prevent the interpreter from evaluating the annotation expression.

```python
x: "str | int" = 0
```

or 

```python
from __future__ import annotations

x: str | int = 0
```

**Comment by jerryc05** [comment]
>x: "str | int" = 0

This is really helpful! Thanks for letting me know that!

---
Here is the minimal buggy code:
```python
def f():
    global GLOBAL
    print(GLOBAL)

GLOBAL: int = 1
```
This code works fine on Python 3.9+ but fails to run on Python 3.6, 3.7, or probably 3.8: `SyntaxError: annotated name 'GLOBAL' can't be global`

This error can be solved by removing the type annotation, e.g. `GLOBAL = 1 # type: int` will work.

My assumption is that earlier versions of python eagerly evaluate `global GLOBAL`, thus causing the error.

**Comment by erictraut** [comment]
I found [this discussion](https://bugs.python.org/issue34939) on this topic.

It looks to be a bug (er, a "design feature") of Python 3.6 and 3.7.

If you're able to move the global declaration above the `global` within the file, you can avoid the bug.

```python
GLOBAL: int = 1

def f():
    global GLOBAL
    print(GLOBAL)
```

If that's not feasible, then you can use a `# type` comment, but only simple forms of type comments will be supported by pylance. We don't have plans to add support for multi-variable forms (e.g. for tuple destructuring).

**Comment by jerryc05** [comment]
Thanks a lot!

**Comment by jerryc05** [comment]
BTW, what is the recommended way to annotate this:
```python
x, y, z = [], [], []  # type: List[int], List[int], List[str]
```

**Comment by erictraut** [comment]
```python
x: List[int]
y: List[int]
z: List[str]
x, y, z = [], [], []

```

or
```python
x: List[int] = []
y: List[int] = []
z: List[str] = []
```
