### ISSUE TITLE
Line breaks not showing in docstring

### ISSUE THREAD

**Issue by vishwa-raj** [microsoft/pylance-release#1048]
<h3> Environment data </h3>

-   Language Server version: 2021.3.1
-   OS and version: win32 x64
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Actual behavior </h3>

![image](https://user-images.githubusercontent.com/22815753/111077884-d7227100-8518-11eb-894e-89569634a709.png)

**Comment by Prunoideae** [comment]
The docstring follows a markdown style, you need to add an extra break between lines to make them separated.

like
```
First line of docstring.

Second line of docstring.
```

**Comment by vishwa-raj** [comment]
@Prunoideae But that'll unnecessary expand the actual docstring text.

**Comment by Prunoideae** [comment]
This is how markdown works, and it's for breaking long line of text into more readable shorter lines, especially when there's a 80 char limit. For example: 

![image](https://user-images.githubusercontent.com/24620047/111134446-95e09e80-85b6-11eb-9ebc-d48c4b4d1159.png)


And this is the markdown's standard, writing in Github also requires you to break twice to get a new line, it's not a standard only introduced by pylance.

**Comment by vishwa-raj** [comment]
You're right that it's the markdown standard but it's not a Python or PEP standard.
And if one doesn't wish to use the Markdown format, then they shouldn't be required to do so.

So there needs to be an option to disable it so that one can see the docstring exactly how it's typed in the code

**Comment by judej** [comment]
Thanks for the report. The blank line is the convention we are following for a new paragraph. I'd recommend you use that as a work around.
thanks!
