### ISSUE TITLE
Completion unavailable for abstract properties

### ISSUE THREAD

**Issue by BlueskyFR** [microsoft/pylance-release#1054]
<h3> Environment data </h3>

-   Language Server version: 2021.3.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Problem </h3>

No completion seems to be provided for abstract properties (new issue as asked in #1050):
![image](https://user-images.githubusercontent.com/25421460/111280334-fbc33980-863b-11eb-90f1-933108b2494c.png)

If you need additional information, please feel free to ask!

**Comment by judej** [comment]
Thanks for the report. This looks like a bug and will investigate

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202132-17-march-2021
