### ISSUE TITLE
Auto-imports only work for code from currently open files when indexing is enabled

### ISSUE THREAD

**Issue by klbostee** [microsoft/pylance-release#1055]
## Environment data

-   Language Server version: 2021.3.1

## Expected behaviour

I would expect pylance to be able to auto-import any symbol from my codebase, not only from currently open files. 

## Actual behaviour

As mentioned in the changelog for 2021.3.1, auto-imports now only work for code from currently open files when indexing is enabled. The release notes also said "please file an issue if you have enabled indexing and this affects your workflow", which is what I'm doing right now :)

## Additional information

This does indeed affect our workflow quite a bit. Could it at least be made configurable maybe?

**Comment by jakebailey** [comment]
Thanks for this; it's hard to find people who are actually using our insiders features...

Before we disabled it (sorry!), did you experience any sort of performance troubles with indexing? Or was it not a problem and the feature was worth the extra CPU time spent working? I'm very curious about your codebase and how it helped/hurt.

**Comment by klbostee** [comment]
So we're looking into moving our Python dev team over to VS Code with Pylance (one of the main reasons being that dev containers are really appealing to us, for what it's worth). This team relies heavily on auto-imports, symbol search and reference search, and enabling indexing seems to be the only way to make those (mostly) work for our large codebase.

We do see performance problems with indexing, as already discussed in #997 also. More specifically, completions and auto-imports can definitely be slow at times. The performance issues are enough of a turn-off to keep the team from switching over permanently at this point in fact, but not having the full functionality makes things even worse for us I'm afraid.

I guess I was hoping that VS Code with Pylance could still be an option for us further down the road, as indexing performance improves over time. This change is more of a step backwards that makes that all less feasible however. We'd be happy to test things out and/or provide info/feedback if that can help to keep the dream alive though :)

**Comment by heejaechang** [comment]
@klbostee how about providing the ability through code action? (the light bulb), we are trying to reduce things that affect typing such as completion but fine some feature taking more time on user explicit command such as code action.

**Comment by klbostee** [comment]
Providing it (only) through a code action sounds like a good potential solution to me @heejaechang. I'd have to ask the others in the team, but for me it was typically already very similar to this in practice anyway. The red curly line would appear because the symbol isn't defined, and then I'd trigger an auto-complete by hitting ctrl+space and pick the auto-import. So the only difference would be having to trigger code actions instead of auto-complete.

Some of our devs are pretty religious about being able to access everything via the keyboard, but I just checked and there seems to be a keyboard shortcut for code actions too (cmd+.) so that shouldn't be an issue.

**Comment by jakebailey** [comment]
The next release (later today) will re-eanble it for code actions (quick fixes), but not for completions. We'll see how far that get us, and use this thread for further feedback.

**Comment by b99andla** [comment]
I have experienced the auto imports getting worst during the last few updates to Pylance. I am unsure as what I need to do now to get this working again. 

I have installed the latest version of Pylance, I have added "python.analysis.indexing": true as well but it is still not working to use the 

A recent example:
I am working in a project where I would like to send mail. We have the function send_mail in three different places in this project, all of them outside my current workspace.

IntelliJ shows these imports as:
![Screenshot 2021-03-25 at 10 40 42](https://user-images.githubusercontent.com/8145201/112452558-0a55d300-8d57-11eb-94d6-a54b97fa8501.png)

While the latest pylance (2021.3.3) shows no valid imports at all:
 ![Screenshot 2021-03-25 at 10 42 17](https://user-images.githubusercontent.com/8145201/112452568-0e81f080-8d57-11eb-9fbb-be7f3af5143f.png)

What do we need to do to get code action imports working in this case?

**Comment by erictraut** [comment]
We should fully index all files within the project though. I'm guessing that `common.utils.mail` is within the workspace, Whereas `django.core.mail` and `wagtail.admin.mail` are imported from outside the workspace?

**Comment by b99andla** [comment]
I am sorry, I was under the impression that this has been working. But I may have just made this up... I am actually unsure now. 

Is there any way to make this work with the current release of pylance?

**Comment by jakebailey** [comment]
Right now, we have some hardcoded limits in the indexer as we work on ways to improve its performance. Most packages are limited to the top level, but django is restricted to two levels, but `django.core.mail` is three and is outside those limits.

We've recently identified some more perf improvements, so we'll see what we can do, but at the moment there isn't a way for you to tweak this externally.

**Comment by jakebailey** [comment]
Today's release (2021.5.3) includes stricter filtering on auto-imports which should mitigate some of the performance problems we have with offering far too many symbols. If this goes well, it's likely we can look into re-enabling auto-imports that make use of the user code index, but we'll see (I don't want to jinx it).

**Comment by ThiefMaster** [comment]
Do you have any details on how the logic changed and are there any settings to tune the behavior?

**Comment by jakebailey** [comment]
The change is that auto-import completions at least need to start with the same character as what has already been typed. This is something that is currently being put into TypeScript's auto-import system, as they have similar issues to us with offering so many completions that performance is greatly affected. Quick fixes remain unchanged.

There are no settings to tune this behavior. Is there a reason you're looking for a way to change it? Happy to take feedback as to how this may break; the intent is to filter out the bulk of the completions nobody is accepting.

**Comment by ThiefMaster** [comment]
I also noticed that for a multi-root workspace I often don't get proper suggestions from the code in another root. This is quite annoying when you have a [core project](https://github.com/indico/indico/) and a [plugin repo](https://github.com/indico/indico-plugins), and usually import stuff from the core in plugin code.

The repos are linked above so if you want to investigate this further feel free to try with them (I have one root for the core project and one for the folder containing all the plugins). Especially the `Event` import is interesting because it's a HUGELY common name, so getting matches from my own code first would be really helpful there. It looks like it ONLY searches within that particular root, and not in other ones at all:

![image](https://user-images.githubusercontent.com/179599/118940284-d828b200-b950-11eb-8687-c463e97a5f6e.png)

In terms of sorting, it's also a mix between thirdparty (site-packages) and custom code. Having imports from own code come first would be nice...

**Comment by ThiefMaster** [comment]
I tried setting `"python.analysis.extraPaths": ["/home/adrian/dev/indico/py3/src"],` but it didn't help. FWIW, the package is installed with `pip install -e` in the virtualenv, so from what I understood in another issue it should not be needed to explicitly set it as an extraPath?

Anyway, in the language server output I see this, so the src dir is clearly in the path - I do not get completions for imports coming from there though.

```
Search paths for /home/adrian/dev/indico/py3/plugins/public
  /home/adrian/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.5.4-pre.1/dist/typeshed-fallback/stdlib
  /home/adrian/dev/indico/py3/plugins/public
  /home/adrian/dev/indico/py3/plugins/public/typings
  /home/adrian/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.5.4-pre.1/dist/typeshed-fallback/stubs/...
  /home/adrian/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.5.4-pre.1/dist/bundled/stubs
  /home/adrian/.pyenv/versions/3.9.5/lib/python3.9
  /home/adrian/.pyenv/versions/3.9.5/lib/python3.9/lib-dynload
  /home/adrian/dev/indico/py3/env/lib/python3.9/site-packages
  /home/adrian/dev/indico/py3/plugins/public/livesync
  /home/adrian/dev/indico/py3/plugins/public/livesync_debug
  /home/adrian/dev/indico/py3/plugins/public/payment_manual
  /home/adrian/dev/indico/py3/plugins/public/payment_paypal
  /home/adrian/dev/indico/py3/plugins/public/piwik
  /home/adrian/dev/indico/py3/plugins/public/previewer_code
  /home/adrian/dev/indico/py3/plugins/public/previewer_jupyter
  /home/adrian/dev/indico/py3/plugins/public/storage_s3
  /home/adrian/dev/indico/py3/plugins/public/ursh
  /home/adrian/dev/indico/py3/plugins/public/vc_dummy
  /home/adrian/dev/indico/py3/plugins/public/vc_zoom
  /home/adrian/dev/indico/py3/plugins/cern/audiovisual
  /home/adrian/dev/indico/py3/plugins/cern/burotel
  /home/adrian/dev/indico/py3/plugins/cern/cern_access
  /home/adrian/dev/indico/py3/plugins/cern/conversion
  /home/adrian/dev/indico/py3/plugins/cern/cronjobs_cern
  /home/adrian/dev/indico/py3/plugins/cern/foundationsync
  /home/adrian/dev/indico/py3/plugins/cern/outlook
  /home/adrian/dev/indico/py3/plugins/cern/payment_cern
  /home/adrian/dev/indico/py3/plugins/cern/ravem
  /home/adrian/dev/indico/py3/plugins/cern/room_assistance
  /home/adrian/dev/indico/py3/plugins/cern/themes_cern
  /home/adrian/dev/indico/py3/plugins/cern/themes_lcagenda
  /home/adrian/dev/indico/py3/plugins/cern/vc_assistance
  /home/adrian/dev/indico/py3/plugins/cern-dev
  /home/adrian/dev/indico/py3/plugins/psi
  /home/adrian/dev/indico/py3/plugins/public/citadel
  /home/adrian/dev/indico/py3/plugins/public/themes_legacy
  /home/adrian/dev/indico/py3/src
```

If I use CTRL+T I do find those symbols though, so they are clearly being indexed.

**Comment by heejaechang** [comment]
we have added an option to include more symbols from third party libs if user wants, see this https://github.com/microsoft/pylance-release/issues/2312#issuecomment-1065637710

I also opened this issue to track UX on multi root workspace - https://github.com/microsoft/pylance-release/issues/2601

**Comment by jli** [comment]
I feel like auto-import and finding references has gotten worse quite recently, maybe in the past 1-2 weeks. When I "Find all references", it seems like Pylance is missing references more and more. This is all for code within my workspace, not external libraries.

VSCode: `Version: 1.71.0 (Universal)`
Pylance: `v2022.9.20`

Sorry this isn't a more useful report :/

**Comment by debonte** [comment]
@jli, @adamalpi, can you see if setting [`"python.analysis.indexing":true`](https://github.com/microsoft/pylance-release/issues/3324#issuecomment-1245808555) helps? If not, please file a new issue rather than commenting on this old issue.

**Comment by solarw** [comment]
@debonte
similar issue for me `"python.analysis.indexing": true,`  set

updated ubuntu and all the software
and autocomplete works only if py file is opened.
works well for custom modules installed, not for my own code
