### ISSUE TITLE
Cannot see function completion for private method

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/pylance-release#1057]
## Environment data

-   **Language Server version**: Pylance language server v2021.3.2-pre.1
-   **OS and version**: Windows_NT x64 10.0.19043
-   **Python version**: Python 3.8.6

## Expected behaviour

As shown in the figure below, we can see the function complement prompt of  method `__printinfo`
![显示私有方法](https://user-images.githubusercontent.com/65096819/111435487-cf8ee200-873b-11eb-9582-b83ed28db9a5.png)

## Actual behaviour

We can’t see the function complement prompt of private method `__printInfo` 

![无法显示私有方法](https://user-images.githubusercontent.com/65096819/111435496-d3baff80-873b-11eb-8e48-f21563d0b01a.png)

## Code Snippet

```python
class Dog:
    def __init__(self, age):
        self.age = age
        self.__pr

    def __printInfo(self):
        print(self.age)
```

**Comment by erictraut** [comment]
Thanks for the bug report. I'm able to repro the problem with pylance, but it works correctly with pyright. That should give us a good clue about the source of the bug.

**Comment by zhiyiYo** [comment]
> Thanks for the bug report. I'm able to repro the problem with pylance, but it works correctly with pyright. That should give us a good clue about the source of the bug.

Thank you for your reply. I just downloaded the new pylance model, and now the problem has been solved
