### ISSUE TITLE
Type checks inside function calls not detected

### ISSUE THREAD

**Issue by frreiss** [microsoft/pylance-release#1068]
## Environment data

-   Language Server version: v2021.3.2
-   OS and version: MacOS 11.2.3 (Big Sur)
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.8.8. 64-bit

## Expected behaviour

The code snippet below should not produce any errors.

## Actual behaviour

With Pylance type checking set to "strict", the code snippet below produces this error at line 8:
```
Expression of type "int | float" cannot be assigned to return type "int"
  Type "int | float" cannot be assigned to type "int"
    "float" is incompatible with "int"PylancereportGeneralTypeIssues)
```

It appears that static analysis does not detect the `isinstance()` check inside the function `is_int()`.

## Code Snippet / Additional information

```python
from typing import Union

def is_int(i) -> bool:
    return isinstance(i, int)

def to_int(value: Union[int, float]) -> int:
    if is_int(value):
        return value
    else:
        return int(value)
```

**Comment by erictraut** [comment]
The type checker doesn't know that the `bool` result of the `is_int` means "I've verified that this type is a subtype of int". Type checkers can't make assumptions like that.

You have a few options:

1. Move the check for int inline, like this:
```python
def to_int(value: Union[int, float]) -> int:
    if isinstance(value, int):
        return value
    else:
        return int(value)
```

2. Use a "verify" pattern, like this:
```python
def verify_is_int(i) -> Optional[int]:
    return i if isinstance(i, int) else None

def to_int(value: Union[int, float]) -> int:
    int_value = verify_is_int(value)
    if int_value:
        return int_value
    else:
        return int(value)
```

The approach you're taking is not uncommon, so we've proposed a new type checking feature to accommodate it. It's called "user-defined type guards", and it's covered in [PEP 647](https://www.python.org/dev/peps/pep-0647/). Support for this PEP is already included in Pylance, and we're trying to get it ratified for Python 3.10. You can use it today if you use quoted type annotations. Here's how that would look:

```python
from typing import Union, TYPE_CHECKING

if TYPE_CHECKING:
    from typing import TypeGuard

def is_int(i) -> "TypeGuard[int]":
    return isinstance(i, int)

def to_int(value: Union[int, float]) -> int:
    if is_int(value):
        return value
    else:
        return int(value)
```

Once the PEP is ratified and incorporated into the language (and support added to typing_extensions), you will be able to remove the ugly `if TYPE_CHECKING` conditional.

**Comment by erictraut** [comment]
For more information on type narrowing and type guards, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-narrowing).

**Comment by jakebailey** [comment]
I don't think there's anything left to do here; TypeGuard is the right way to do this (and it's been accepted for 3.10).
