### ISSUE TITLE
F12, Goto definition has to press twice.

### ISSUE THREAD

**Issue by Haibao425** [microsoft/pylance-release#1073]
Refer to below issue.
https://github.com/microsoft/vscode-python/issues/15727

**Comment by Haibao425** [comment]
> Go to definition on an object
> Get the message "Definition of xx" could not be found
> Go to definition again and it works
> 
> This seems to occur at the start of opening a workspace/folder and occurs a short time after.
> 
> Using the previous python-vscode version of 2021.2.636928669 makes the issue go away.
> 
> ## Environment data
> * VS Code version: 1.54.3
> * Extension version (available under the Extensions sidebar): 2021.3.658691958
> * Python version (& distribution if applicable, e.g. Anaconda): 2 & 3
> * Value of the `python.languageServer` setting: Pylance/Jedi/Microsoft
> 
> Appears to be only be dependent on python-vscode being on version 2021.3.658691958
> 
> ## Steps to reproduce:
> ![vscode-python-bug](https://user-images.githubusercontent.com/65086844/111825836-dce4d180-88df-11eb-88ac-1bef9f2511f9.gif)

Copy and paste here.

**Comment by doraemoncyx** [comment]
same happens on windows

**Comment by jakebailey** [comment]
Thanks. This is a bug in the core extension that was introduced a little bit ago; we'll fix it.

**Comment by jakebailey** [comment]
This is now fixed in the core extension (v2021.3.680753044).
