### ISSUE TITLE
Failure on `# type: ignore[code]' comments

### ISSUE THREAD

**Issue by algorythmic** [microsoft/pylance-release#108]
## Environment data

-   Language Server version: 2020.7.1
-   OS and version: macOS 10.15
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7 from Homebrew

## Expected behaviour

`# type: ignore[code]` treated same as `# type: ignore` (or, at least, does not generate its own error)

## Actual behaviour

A line with e.g. `# type: ignore[attr-defined]` produces a number of errors:

![image](https://user-images.githubusercontent.com/1232097/87450511-96123f80-c5cc-11ea-80ae-ace26907d016.png)
![image](https://user-images.githubusercontent.com/1232097/87453747-fd31f300-c5d0-11ea-97e8-eb0852039625.png)

Note that `Type annotation not supported for this type of expression` is reported even if `python.analysis.typeCheckingMode` is `off`.

## Code Snippet / Additional information

Mypy uses this syntax since 0.730 (https://github.com/python/mypy/issues/7239). See e.g. https://github.com/PyCQA/pyflakes/pull/455 and https://github.com/google/pytype/issues/485 for other tools' changes to adapt to this syntax.

**Comment by erictraut** [comment]
Thanks for the suggestion. The use of "[code, ...]" after a "# type: ignore" comment is not part of the official spec, but it appears it's a variant supported by mypy. The error codes will not have any meaning outside of mypy, but we could treat it as a general "# type: ignore" (i.e. suppress all errors on the line) as specified in PEP 484.

**Comment by erictraut** [comment]
This change will be included in the next version of Pylance/Pyright. Thanks again for the suggestion.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202072-15-july-2020

**Comment by rpatterson** [comment]
I'm unable to get this to work, there's no squigly underline error indication when I add the following to a Python file opened in VSCode:

    XXX = YYY  # type: ignore[ZZZ]

But the indication is displayed with the right error code when I remove the entire comment, so the code included in the brackets is having no effect.  FWIW, this is also true when using Pyright seperately from Pylance.

###  Environment data

-   Language Server version: 2021.6.3
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

**Comment by erictraut** [comment]
As mentioned above, the bracket after the `# type: ignore` is a non-standard proprietary extension used by mypy. The PEP 484 standard specifies only `# type: ignore`, and that's what pylance supports. If there is a bracket after the `# type: ignore`, it is ignored. Based on your description, it is working as expected.
