### ISSUE TITLE
Invalid types for pyDes

### ISSUE THREAD

**Issue by zhanghua000** [microsoft/pylance-release#1080]
<h3> Environment data </h3>

-   Language Server version: 2021.3.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.2
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Extension sets correct highlighting and marks code error correctly

<h3> Actual behaviour </h3>

In Python 3, it marks the type of the result of `pyDes.des().encrypt()`  as `str | bytes` , which will lead syntax error  'str is incompatible with bytes', however, when I check the source code of pyDes, its actual type in Python 3 is bytes.

<h3> Logs </h3>

Python Language Server Log
```

```
It is too large so I pasted it on Ubuntu Pastebin, the address is [this](https://pastebin.ubuntu.com/p/NxBfCxNSt3/)

<h3> Code Snippet / Additional information </h3>

```python
    def DESEncrypt(self,s):
        iv=base64.b64decode(self.apis["iv"])
        k=des(self.apis["encryptKey"], CBC, iv, pad=None, padmode=PAD_PKCS5)
        encrypted_data=k.encrypt(s)
        return base64.b64encode(encrypted_data).decode()
```
Pylance reports that the type of `encrypted_data` is `str | bytes` and it will be incompatible with the param of `base64.b64encode()`. The actual situation is that it is str in Python 2 and bytes in Python 3.

**Comment by erictraut** [comment]
The `pyDes` package contains no type information (no annotations and no stubs), so Pylance is forced to infer type information from the source code. The pyDes code is dynamically checking for the python version in a way that is too dynamic for a static type checker to understand. 

If you want to use the static type checker with this package, you'll need to provide more accurate types in the form of type stubs.

**Comment by judej** [comment]
Closing this in this repo since the work is not here in Pylance.
