### ISSUE TITLE
Pylance cannot detect Django App files on Django Project Files (Missing Import)

### ISSUE THREAD

**Issue by sekti92** [microsoft/pylance-release#1081]
## Environment data

-   OS and version: Windows 10 Pro 64bit
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.1 - 64bit

## Expected behaviour

Should not gives the warning to import files 

## Actual behaviour
Import "accounts.views" could not be resolved Pylance(reportMissingImports)
Django Project Files:  `urls.py - inside crm directory`
Django App Files: `views.py - inside accounts directory`

VSCode Screenshot:
![image](https://user-images.githubusercontent.com/14885417/112249180-e7a9b880-8c89-11eb-84e5-e78d6839144b.png)

**Comment by savannahostrowski** [comment]
Can you follow the guidance in our [TROUBLESHOOTING](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings) doc to configure extraPaths to include crm?

**Comment by sekti92** [comment]
Already create `settings.json` inside `.vscode`. It's working now

**Comment by msimkins** [comment]
I would expect the current 'python' lib paths to be automatically included in this path list, but that does not appear to be the case
