### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by gillug** [microsoft/pylance-release#1084]
- Issue Type: `Bug`
- Extension Name: `vscode-pylance`
- Extension Version: `2021.3.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakebailey** [comment]
Can you paste the info that was generated for this issue, please? Otherwise, we have no info that can help us. What issues are you seeing?

**Comment by savannahostrowski** [comment]
I'm going to close this issue for the time being. If you are able to provide us with the info specified in our bug template or additional information about the issue you are experiencing, feel free to tag me and I can reopen!
