### ISSUE TITLE
How do I type variables?

### ISSUE THREAD

**Issue by bholland** [microsoft/pylance-release#1089]
Hello all,

I searched for an answer but it was very hard to figure this out. I know how to get function headers to have types. I don't know how to define variables. For example:

def foo(InputVar: int) -> bool:

will define InputVar as an int. Now I want to do something like this:

def main():
    x = 10
    b = foo(x)

This will result in an error like (variable) x: Unknown and Type of "x" is unknown Pylance(reportUnknownVariableType)

What is the syntax to define x as an int? I would hope something like x: int = 10. Obviously 10 will result in an int but you get the idea. x could be assigned to a variable, some function, etc or even None. Is there a way to specify the variable as an integer to avoid getting this warning? BTW, I am using the latest version of pylance and vscode.

**Comment by erictraut** [comment]
The syntax for annotating variable types was introduced in Python 3.6 and is described in [PEP 526](https://www.python.org/dev/peps/pep-0526/). In short, it looks the same as when annotating a parameter:

```python
x: int = 10
```

In the vast majority of cases, Pylance can infer the type of a variable based on its assigned value, so explicit variable type annotations shouldn't be required.

If the statement `x = <some expression>` is resulting in `x` having an unknown type, then annotating the type of `x` isn't the first approach I'd take. Rather, I'd look at `<some expression>` to determine why it is evaluating to an unknown type. For example, if it's making a call to an unannotated function, then it's best to annotate that function. Once you do that, type inference will work, and an annotation for `x` will be unnecessary. Plus, by annotating the function, you eliminate the source of the "unknown" type, and the type checker can do a better job at finding and reporting bugs that take the form of type consistency violations.

**Comment by bholland** [comment]
True. In an ideal case, this would easily work. I seem to run into the
problem in a few wierd and specific cases, likely due to some parsing or
syntaxes error. I assumed this was the syntax but for some reason it didn't
seem to work. I will try again and give it more time.

Thank you for the reply. This was a remarkably difficult question to ask
google.
