### ISSUE TITLE
Call Hierarchy

### ISSUE THREAD

**Issue by GuSuku** [microsoft/pylance-release#109]
This popular feature request is best described within the [documentation](https://code.visualstudio.com/updates/v1_33#_call-hierarchy) of LSP, but here is a summary:

> A Call Hierarchy shows all calls from or to a function and allows you to drill into callers of callers and calls of calls.

This is currently available for JS/TS and Java language extension. 

The only issue (https://github.com/microsoft/vscode-python/issues/5127) tracking this in python language extension has been closed citing an existing upstream feature.

But the reason sounds a little inconsistent (see my comment at cited upstream issue https://github.com/microsoft/python-language-server/issues/888)

**Comment by jakebailey** [comment]
Pylance has call hierarchy support already. I'll close this as done, but we're happy to take feedback on this feature.

**Comment by jahan01** [comment]
@jakebailey actually i am never able to get call hierarchy for any python code. Is there an additional setting required ?

**Comment by jakebailey** [comment]
I'll open this until we can go verify that this is/isn't working as expected.

**Comment by jahan01** [comment]
Call hierarchy works since last update (not sure whether it was after vscode update or pylance update)

**Comment by huguesv** [comment]
@jahan01 you're right, it looks like it was fixed in the python extension 2020.7.94776

**Comment by GuSuku** [comment]
Works now. Both incoming calls and outgoing calls are showing up. Thanks!
