### ISSUE TITLE
Wrongly saying "Expected class as second argument to XXX"

### ISSUE THREAD

**Issue by benoitscherrer** [microsoft/pylance-release#1093]
## Environment data

-   Language Server version: 2021.3.3
-   OS and version: Windows 10 / WSL2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2

## Expected behaviour

No error for:
```
from typing import NewType, Awaitable, Callable
RunErrorCallback = NewType("RunErrorCallback", Callable[[Exception], Awaitable[None]])
```

## Actual behaviour

Showing the error
```
Expected class as second argument to NewType
```

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment]
I think the current behavior is correct. The second parameter must be a subclassable type, but `Callable` is not.

Mypy issues the same error for this code.
