### ISSUE TITLE
Always enable ``Expected no type arguments`` error

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1095]
It would be useful if the error `Expected no type arguments` would be enabled by default, even if `typeCheckingMode: off`. At least if postponed evaluation is not enabled, this will be a `TypeError` in Python.

I wouldn't mind enabling it with postponed evaluation as well, since this is almost always a user error.

```py
class Custom:
    pass

var: Custom[int]
```

**With `typeCheckingMode: basic`**

![Screen Shot 2021-03-27 at 01 19 17](https://user-images.githubusercontent.com/30130371/112704319-7725b600-8e9a-11eb-9e39-f8d324b5a819.png)

**Comment by jakebailey** [comment]
This will probably need some discussion as to 1) splitting this out from general type issues, and 2) where this can have false positives.

The default "off" mode is intended to be as quiet as possible except for things that can easily be determined to be "obvious" problems or affect analysis, e.g. syntax errors, import resolution warnings, and undefined variables. There's a high bar for anything we choose to add to this mode.

**Comment by erictraut** [comment]
This particular error message falls within the domain of type checking, so I don't think it would be appropriate to enable this error when typeCheckingMode is "off". As Jake said, there's a very high bar for errors that are emitted when type checking is off — only the most basic of problems with little or no possibility of false positives (like syntax errors).

You can configure "reportGeneralTypeIssues" to emit an error or warning independently from other checks if you'd like.
