### ISSUE TITLE
Protocol `Mapping[str, Any]` of `BaseRowProxy` from `SQLAlchemy` stubs does not always apply

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1108]
## Environment data

-   Language Server version: 2021.3.4
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 Anaconda

## Expected behavior

`BaseRowProxy` does NOT always implement `Mapping[str, Any]` (in fact, it may, but not always), and calling `iter` with an instance of `BaseRowProxy` should result in either `Iterable[Any]` or `Iterable[Unknown]`.

## Actual behaviour

`BaseRowProxy` always implements `Mapping[str, Any]`, and calling `iter` with an instance of `BaseRowProxy` will result in `Iterable[str]`.

## Code snippet

```python
from sqlalchemy import create_engine

def foo():
    engine = create_engine(...)
    sql = "SELECT `id`, `name` from `persons`"

    result = engine.execute(sql).fetchone()
    if result is None:
        return
    # Type of `result` is `RowProxy` which directly inherits `BaseRowProxy`.

    it = iter(result)
    _ = it
    # Type of `it` is `Iterable[str]` but should be `Iterable[Any]`.

    tp = tuple(result)
    _ = tp
    # Type of `tp` is `tuple[str]` but should be `tuple[Any, ...]`.
    # Missing ellipsis during tuple casting is not concerned here.

    # Base on the content of `sql`,
    # the real type of `tp` here would probably be `tuple[int, str]`,
    # but the language server is not expected to know this.
```

**Comment by erictraut** [comment]
I think pylance is doing the right thing based on the stubs. The type of `it` in your example above should be `Iterable[str]`, and the type of `tp` should be `tuple[str, ...]`. Those are the types that pylance reports. Mypy reports `Iterable[str]` and `tuple[str]`, respectively, although the latter should be `tuple[str, ...]`.

If you think that the sqlalchemy stubs are incorrect, please file a bug or a PR in that repo: https://github.com/dropbox/sqlalchemy-stubs.

**Comment by Azureblade3808** [comment]
I just did some research, and found something interesting.

A `BaseRowProxy` instance do implement all APIs of `Mapping`, and type of its keys is indeed `str`, but it also supports calling `__getitem__` with keys of other types such as `int`. Meanwhile, unlike a normal `Mapping` instance, calling `__iter__` on it iterates over its values instead of its keys, which is the main cause of this issue.

I tried modifying the stubs replacing
```python
class BaseRowProxy(Mapping[str, Any]):
    ...
```
with
```python
class BaseRowProxy(Iterable[Any], Mapping[str, Any]):
    ...
```
and it worked.

Please confirm whether such change is suitable.

**Comment by erictraut** [comment]
As I said above, I recommend working with the maintainers of the sqlalchemy stubs. They have the expertise in this library and will be able to tell you whether this is an acceptable change. Pylance will honor whatever type information is present in the stubs.

**Comment by Azureblade3808** [comment]
Thank you. I'll have a try.
