### ISSUE TITLE
How to keep local changes of bundled stubs after Pylance upgrade?

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1110]
If I make changes in the dist folder, they will be lost after Pylance upgrade as a newly downloaded dist folder will be in effect.

Most of these changes are for individual purposes only and I don't think they would make some passing PRs, so I just want to keep them local.

Is it suitable to copy a whole folder of type stubs into the library folder then make some changes there (which is my current work-around)? Or are there some other suggested ways?

**Comment by jakebailey** [comment]
Out of curiosity, what changes have you made to the bundled stubs? The bulk of our stubs are mirrored on https://github.com/microsoft/python-type-stubs, if you want to submit changes. (Some haven't been mirrored out quite yet.)

It'd be best to copy the stubs you need into a `typings` folder for your workspace; we use that ahead of our bundled stubs. You could also set the typings path to another folder if you're wanting to share it between projects.

**Comment by Azureblade3808** [comment]
Most of the changes I made are toward Pandas, where I found many common usages are not supported due to incompatible argument types.

For example, according to the bundled Pandas stubs, 
```python
class _LocIndexerSeries(_LocIndexer, Generic[S1]):
    @overload
    def __getitem__(self, idx: Union[MaskType, Sequence[str]],) -> Series[S1]: ...
    @overload
    def __getitem__(self, idx: Union[int, str],) -> S1: ...
    @overload
    def __setitem__(self, idx: MaskType, value: Union[S1, np.ndarray, Series[S1]], ) -> None: ...
    @overload
    def __setitem__(self, idx: str, value: S1, ) -> None: ...
    @overload
    def __setitem__(self, idx: List[str], value: Union[S1, np.ndarray, Series[S1]], ) -> None: ...
```
`_LocIndexerSeries` only supports keys of `str`.

But in reality, I often use `datetime.date` as key type and I think most comparable types also meet the requirement. So I rewrote this part as
```python
class _LocIndexerSeries(_LocIndexer, Generic[S1]):
    def __getitem__(self, idx: Any) -> Any: ...
    def __setitem__(self, idx: Any, value: Any) -> None: ...
```
to dismiss the numerous warnings in my project.

I think the generics are just wrong in the bundled stubs, from the very beginning. But fixing all of them would be a huge effect. And since I'm not familiar with Pandas enough, I can be just wrong with my judgement. So I'm only making bandage changes and keeping them local, at least for now.

**Comment by Azureblade3808** [comment]
> It'd be best to copy the stubs you need into a typings folder for your workspace; we use that ahead of our bundled stubs. You could also set the typings path to another folder if you're wanting to share it between projects.

Do you mean that I should form a folder structure like
```
[workspace]\
    typings\
        pandas\
            [pandas stubs]
        numpy\
            [numpy stubs]
        [other modules]
    [other project fiels]
```
?

**Comment by jakebailey** [comment]
Yes, precisely.

@gramster What's your opinion on adding the above overloads?
