### ISSUE TITLE
Pylance unable to detect type from pandas extension

### ISSUE THREAD

**Issue by seanboothm** [microsoft/pylance-release#1112]
Not sure if this would be possible, especially for a more generic solution beyond pandas, but pylance is unable to detect typing information from a DataFrame accessor extension. 

When calling the class/method manually typing works properly.
When using the DataFrame accessor, pylance reports the return type is 'Unknown'

## Environment data

-   Language Server version: 2021.3.4 (pyright ba71f257)
-   OS and version: Windows 10 Version 20H2 (OS Build 19042.867)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.1

## Expected behavior

Pylance should type `df.ext.plus_one()` as a `DataFrame`

## Actual behaviour

Pylance types `untyped_df` as `Unknown`

## Code Snippet / Additional information

```python
import pandas as pd
import numpy as np


@pd.api.extensions.register_dataframe_accessor("ext")
class CustomPandasExtension:
    def __init__(self, pandas_obj: pd.DataFrame):
        self._obj = pandas_obj

    def plus_one(self) -> pd.DataFrame:
        return self._obj + 1


if __name__ == "__main__":
    df = pd.DataFrame(np.random.rand(10, 10))
    untyped_df = df.ext.plus_one()
    typed_df = CustomPandasExtension(df).plus_one()
```

**Comment by gramster** [comment]
Unless/until we have some form of extensibility mechanism to handle these types of dynamic extensions on a per-library basis, we won't be able to handle this, at least not statically.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
