### ISSUE TITLE
The Sphinx docstring hover may be more pretty

### ISSUE THREAD

**Issue by fessua** [microsoft/pylance-release#1113]
## Environment data

-   Language Server version: v2021.3.4
-   OS: Ubuntu 18.04
-   Python 3.7, pipenv 2020.11.15
## Expected behaviour

Here is example of Jedi's hover

![IMG_20210401_232659](https://user-images.githubusercontent.com/3171606/113352075-7aaab880-9344-11eb-8253-b72a1654051a.jpg)

## Actual behaviour

![IMG_20210401_232528](https://user-images.githubusercontent.com/3171606/113352026-6666bb80-9344-11eb-8d36-bc83c7ae9145.jpg)

## Code Snippet / Additional information
code snippet from
[https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#an-example-class-with-docstrings](url)

```
class SimpleBleDevice(object):
    """This is a conceptual class representation of a simple BLE device
    (GATT Server). It is essentially an extended combination of the
    :class:`bluepy.btle.Peripheral` and :class:`bluepy.btle.ScanEntry` classes

    :param client: A handle to the :class:`simpleble.SimpleBleClient` client
        object that detected the device
    :type client: class:`simpleble.SimpleBleClient`
    :param addr: Device MAC address, defaults to None
    :type addr: str, optional
    :param addrType: Device address type - one of ADDR_TYPE_PUBLIC or
        ADDR_TYPE_RANDOM, defaults to ADDR_TYPE_PUBLIC
    :type addrType: str, optional
    :param iface: Bluetooth interface number (0 = /dev/hci0) used for the
        connection, defaults to 0
    :type iface: int, optional
    :param data: A list of tuples (adtype, description, value) containing the
        AD type code, human-readable description and value for all available
        advertising data items, defaults to None
    :type data: list, optional
    :param rssi: Received Signal Strength Indication for the last received
        broadcast from the device. This is an integer value measured in dB,
        where 0 dB is the maximum (theoretical) signal strength, and more
        negative numbers indicate a weaker signal, defaults to 0
    :type rssi: int, optional
    :param connectable: `True` if the device supports connections, and `False`
        otherwise (typically used for advertising ‘beacons’).,
        defaults to `False`
    :type connectable: bool, optional
    :param updateCount: Integer count of the number of advertising packets
        received from the device so far, defaults to 0
    :type updateCount: int, optional
    """
```

**Comment by jakebailey** [comment]
Is the suggestion to look like jedi's?

Note that jedi's output here (as converted to markdown in VS Code, at least) is incorrect as it's treating random indented blocks as code. We recently fixed that in Pylance to try and preserve the indention in the docstring, so those lines are properly treated as regular text in our tooltip (which is the expectation).

**Comment by fessua** [comment]
Thank you for your reply!

Yes, I suggest it to look like Jedi's.

Well, it's hard to explain in specific words.
I would like the text to look less dense.

On the other side, it supposed to be a docstring's responsibility.

**Comment by thehappycheese** [comment]
Baffled by VS Code docstring support. Is it markdown? is it sphinx? is it google style? Is it some undocumented mess combining elements of all flavours? I am confused and frustrated with it.

**Comment by viettappcard** [comment]
Hi, at this point it's close to 2 years since @jeremyvital4 's excellent summary of what's desired. Should another ticket be opened cause this one is closed and probably forgotten?

**Comment by rchiodo** [comment]
I created a new issue from @jeremyvital4's comment: https://github.com/microsoft/pylance-release/issues/4414
