### ISSUE TITLE
Can't recognize a dict from csv.DictReader (dict assignment)

### ISSUE THREAD

**Issue by zhj0924** [microsoft/pylance-release#1117]
<h3> Environment data </h3>

-   Language Server version: 2021.3.4
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

dict assignment should be perfectly OK

<h3> Actual behaviour </h3>

Argument of type "int" cannot be assigned to parameter "v" of type "str" in function "__setitem__"
  "int" is incompatible with "str"

<h3> Logs </h3>

Python Language Server Log
```
[Info  - 9:15:39 PM] Pylance language server 2021.3.4 (pyright ba71f257) starting
[Info  - 9:15:39 PM] Server root directory: /home/zhj0924/.vscode-server/extensions/ms-python.vscode-pylance-2021.3.4/dist
[Info  - 9:15:39 PM] Background analysis(1) root directory: /home/zhj0924/.vscode-server/extensions/ms-python.vscode-pylance-2021.3.4/dist
[Info  - 9:15:39 PM] Background analysis(1) started
```

<h3> Code Snippet / Additional information </h3>

```python
    teams = []
    # DONE: Read teams into memory from file
    filename = sys.argv[-1]
    with open(filename) as f:
        reader = csv.DictReader(f)
        for team in reader:
            rating = int(team["rating"])
            team["rating"] = rating
            teams.append(team)
```

**Comment by zhj0924** [comment]
On this line `team["rating"] = rating`, Pylance thinks team["rating"] is an int

**Comment by erictraut** [comment]
The type definitions for the stdlib `csv` module come from the typeshed repo. You can see [here](https://github.com/python/typeshed/blob/87bcb37d3f226f2047018fd9638af108acfbdd82/stdlib/csv.pyi#L71) that it defines the iterator type as a `_DRMapping` which is a type alias for `Dict[str, str]`. That means `team` has the type `Dict[str, str]`, which means it's a type violation to insert a value with type `int` into it.

I think this is correct, but if you think the type definition for `DictReader` is incorrect, please file a bug in the typeshed repo. Pylance picks up new type stubs from typeshed on a regular basis.

**Comment by PASUNX** [comment]
@zhj0924 Try using this instead
```python
from typing import TypedDict
import sys
import csv

class Team(TypedDict):

    rating: int

teams: list[Team] = list[Team]()

with open(sys.argv[1]) as fp:
    reader = csv.DictReader(fp)
    for team in reader:
        teams.append(Team(**{**team, **{
            "rating": int(team["rating"])
        }}))

first = teams[0]["rating"] # (variable) first: int
```

**Comment by zhj0924** [comment]
maybe you should mark it as a warning instead of an error because the code
runs perfectly

**Comment by judej** [comment]
Thanks for the report. This is error is correctly calling out a type error - Since the type stub is specific. If you think typeshed is wrong, you could file a bug against typeshed. Or you could `# type: ignore` on the line

**Comment by zhj0924** [comment]
> @zhj0924 Try using this instead
> 
> ```python
> from typing import TypedDict
> import sys
> import csv
> 
> class Team(TypedDict):
> 
>     rating: int
> 
> teams: list[Team] = list[Team]()
> 
> with open(sys.argv[1]) as fp:
>     reader = csv.DictReader(fp)
>     for team in reader:
>         teams.append(Team(**{**team, **{
>             "rating": int(team["rating"])
>         }}))
> 
> first = teams[0]["rating"] # (variable) first: int
> ```

This gives another error on `teams: list[Team] = list[Team]()`
Subscript for class "list" will generate runtime exception; enclose type annotation in quotes

**Comment by jakebailey** [comment]
Subscripting `list` only works in 3.10+, you could achieve the same thing with `typing.List`.

**Comment by erictraut** [comment]
Yes, you have a few options to avoid this error:

1. Use typing.List (as Jake suggested above):
```python
from typing import List
teams: List[Team] = list() # No need to specify type argument in constructor
```
or
```python
from typing import List
teams: List[Team] = []
```

2. Use deferred annotation evaluation:
```python
from __future__ import annotations
teams: list[Team] = []
```

3. Use a quoted form of the annotation:
```python
teams: "list[Team]" = []
```
