### ISSUE TITLE
No commit characters for auto import suggestion

### ISSUE THREAD

**Issue by mattbierner** [microsoft/pylance-release#1119]
Issue Type: <b>Bug</b>

**Repro**
1. In a python file, type `path`
2. See suggestions for auto import for `path`
3.  Now type `.`

**Expected**
An import is added

**Actual**
No import is added 

It looks like there are no commit characters for the suggestion:

<img width="1087" alt="Screen Shot 2021-04-03 at 6 51 43 PM" src="https://user-images.githubusercontent.com/212305/113496346-a301f680-94ad-11eb-9995-9630a7cea3c0.png">

It would be nice if commit characters worked here so that Python better aligns with the behavior in other languages (users can always disable commit characters if they wish)

Extension version: 2021.3.4
VS Code version: Code - Insiders 1.55.0-insider (05ce54df77c242b1b8ea5fd93d720c62fdb183e6, 2021-03-25T05:12:59.457Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|40.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id cefe23df-690f-4b1b-9ce9-e004d3be2745|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by judej** [comment]
Thanks for this request. It has been open for a while. Closing because of lack of upvotes.
