### ISSUE TITLE
Pasting Twice

### ISSUE THREAD

**Issue by akshitgupta29** [microsoft/pylance-release#112]
Issue Type: <b>Bug</b>

Hi Team,

If I copy any of the variables in the jupyter notebook, it is getting pasted twice. For example:
I copied df_new, I got "df_new", It is pasting:
"df_newdf_new"

Extension version: 2020.7.1
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
If you didn't see, I transferred this issue to: microsoft/vscode-python#12954, which moved your original issue.

**Comment by akshitgupta29** [comment]
Thanks @jakebailey, I missed it, and was thinking where the issue went. Thanks for the help.
