### ISSUE TITLE
Pylance complains when it shouldn't

### ISSUE THREAD

**Issue by eldarkurtic** [microsoft/pylance-release#1123]
<h3> Environment data </h3>

-   Language Server version: 2021.3.4
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

I guess the best explanation is the screenshot below:
<img width="667" alt="Screenshot 2021-04-04 at 16 25 22" src="https://user-images.githubusercontent.com/8884008/113511879-5cba9f00-9562-11eb-8203-0dae62f6c7d7.png">

And this is why I think it's a bug:
<img width="792" alt="Screenshot 2021-04-04 at 16 26 30" src="https://user-images.githubusercontent.com/8884008/113511919-870c5c80-9562-11eb-88ad-76c9f0adc12c.png">

(This is a screenshot from PEP 484 -- Type Hints: https://www.python.org/dev/peps/pep-0484/#type-comments)

**Comment by erictraut** [comment]
This is intended behavior. The older (now obsolete) behavior described in PEP 484 allows for uncaught type errors. You'll note that the authors of PEP 484 provided this exemption only for Python code (not stubs) and only for Python 3.5 and older. Pyright (the type checker that underlies Pylance) always enforces the new, type-safe behavior. If you want to assign `None` to a variable, you must declare its type to allow this. You can then use runtime checks (in the form of `if` or `assert`) to verify whether it has been initialized with a non-None variable.
