### ISSUE TITLE
Parameters placeholders in pylance

### ISSUE THREAD

**Issue by kuator** [microsoft/pylance-release#1126]
One of the features I miss from using Jedi is placeholders when completing functions
Jedi behaviour: ![Peek 2021-04-05 10-54](https://user-images.githubusercontent.com/25168308/113538626-87a60100-95fd-11eb-8a35-eadd43646563.gif)
Pylance behaviour: ![Peek 2021-04-05 10-55](https://user-images.githubusercontent.com/25168308/113538654-9b516780-95fd-11eb-8f5b-fd20a17fbe1b.gif)

**Comment by kuator** [comment]
I love Microsoft!

**Comment by jakebailey** [comment]
Duplicate of #221.
