### ISSUE TITLE
The semantic coloring of local variables becomes gray

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/pylance-release#1127]
## Environment data

-   **Language Server version**: Pylance language server v2021.3.5pre.1
-   **OS and version**: Windows_NT x64 10.0.19043
-   **Python version**: Python 3.8.6

## Expected behaviour

The semantic coloring of local variables should be red.

## Actual behaviour
The semantic coloring of local variables is gray.
![很奇怪](https://user-images.githubusercontent.com/65096819/113565791-2a7e6f80-963e-11eb-8ddc-de33a3f9b62a.png)

**Comment by Jay206-Programmer** [comment]
I can confirm this, It's happening with me as well. 

It is happening with the **One Dark Pro** theme. The theme's semantic highlighting was working properly till yesterday, but it's all messed up right now.

![2021-04-05 16_43_52-preprocessing py - end-to-end-p1 - Visual Studio Code](https://user-images.githubusercontent.com/62549240/113568467-3eba7080-962e-11eb-8d72-aa181d6adfbc.png)

All these _variables_ used to be in the **_red_** color previously. 

Also, the semantic highlighting seems to be working perfectly for other languages,

![2021-04-05 16_49_09-Register js - Feasta_React_Django-master - Visual Studio Code](https://user-images.githubusercontent.com/62549240/113568809-ea63c080-962e-11eb-8231-c11f84bf4547.png)

is it some configuration bug?

**Comment by zhiyiYo** [comment]
> I can confirm this, It's happening with me as well.
> 
> It is happening with the **One Dark Pro** theme. The theme's semantic highlighting was working properly till yesterday, but it's all messed up right now.
> 
> ![2021-04-05 16_43_52-preprocessing py - end-to-end-p1 - Visual Studio Code](https://user-images.githubusercontent.com/62549240/113568467-3eba7080-962e-11eb-8d72-aa181d6adfbc.png)
> 
> All these _variables_ used to be in the **_red_** color previously.
> 
> Also, the semantic highlighting seems to be working perfectly for other languages,
> 
> ![2021-04-05 16_49_09-Register js - Feasta_React_Django-master - Visual Studio Code](https://user-images.githubusercontent.com/62549240/113568809-ea63c080-962e-11eb-8231-c11f84bf4547.png)
> 
> is it some configuration bug?

I quite agree with you. I updated the `one dark pro` today, and that's what happened.

**Comment by zhiyiYo** [comment]
@Jay206-Programmer I quite agree with you. I updated the one dark pro this morning, and that's what happened.

**Comment by ITProKyle** [comment]
I can confirm that this was caused by the changes in [One Dark Pro theme >= 3.10.8](https://github.com/Binaryify/OneDark-Pro/blob/master/CHANGELOG.md#3109--20210404).

Installing version 3.10.7 of the theme resolves the issue. [How to install another version of an extension](https://stackoverflow.com/a/66134500/11003325).

- **Language Server version:** Pylance language server v2021.3.4
- **OS and version:** macOS 11.2.3
- **Python version:** Python 3.8.5

**Comment by zhiyiYo** [comment]
@ITProKyle 
![image](https://user-images.githubusercontent.com/65096819/113594660-92e34600-966a-11eb-95b6-7ecf81b89cc7.png)
Unfortunately, the `install another version` menu option has been disabled

**Comment by ITProKyle** [comment]
@zhiyiYo - that's odd because I just used it on Visual Studio Code version 1.55.0 which is the latest version. There may be a CLI equivalent you can run but would have to check the docs.

**Comment by jakebailey** [comment]
This appears to have been a deliberate decision by the One Dark Pro theme: https://github.com/Binaryify/OneDark-Pro/compare/3.10.7...3.10.9

![image](https://user-images.githubusercontent.com/5341706/113601302-fed79700-95f5-11eb-86d5-0baa8c8ea1b5.png)

Note that we are still sending the semantic info to VS Code.

I'm not sure why they chose the colors they did; it's inconsistent with other languages, as you've seen.

There's not really anything we can do about this. If you think this was a mistake I can only suggest filing an issue or commenting on the theme's repo.

**Comment by jakebailey** [comment]
It seems like the change was to "fix" the theme to make it look more like default VS Code, which only looked the way it did because it didn't have any tokenization and didn't apply any colors to variables by default (arguably an oversight).

If this bugs you, you can revert in the UI here (as opposed to using the CLI):

![image](https://user-images.githubusercontent.com/5341706/113603715-1f552080-95f9-11eb-8168-6d864bf57600.png)

**Comment by zhiyiYo** [comment]
@jakebailey @ITProKyle Thank you for your suggestions. I've moved one dark Pro back to version 3.10.7

**Comment by Binaryify** [comment]
v3.10.10 had already fix this problem, please confirm if this fixed 
@zhiyiYo

**Comment by zhiyiYo** [comment]
@Binaryify 感谢!
