### ISSUE TITLE
Pylance not following pyrightconfig.json

### ISSUE THREAD

**Issue by jordanisaacs** [microsoft/pylance-release#1129]
## Environment data

-   Language Server version: v2021.3.4
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1

## Expected behaviour

Pylance should follow the pyrightconfig.json file in my workspace root directory. I have an exclude option set.

## Actual behaviour

__init__.py are still be excluded. The type checker still runs on all __init__.py. I tried changing the path to "**\\__init__.py" and using absolute paths but I can only guess its something on pylance's end.

## Logs

```
Starting Pylance language server.
Python interpreter path: ~\AppData\Local\pypoetry\Cache\virtualenvs\fastapi-sessions-6iFG9FXP-py3.9\Scripts\python.exe
> conda --version
> ~\AppData\Local\pypoetry\Cache\virtualenvs\fastapi-sessions-6iFG9FXP-py3.9\Scripts\python.exe c:\Users\jdisa\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py flake8 --config=.flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\#####\fastapi-sessions\fastapi_sessions\authentication\__init__.py
cwd: c:\#####\fastapi-sessions
> ~\AppData\Local\pypoetry\Cache\virtualenvs\fastapi-sessions-6iFG9FXP-py3.9\Scripts\python.exe c:\Users\jdisa\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py flake8 --config=.flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s c:\#####\fastapi-sessions\fastapi_sessions\authentication\__init__.py
cwd: c:\#####\fastapi-sessions
```

## Code Snippet / Additional information

pyrightconfig.json
```json
{
    "exclude": [
        "**/__init__.py"
    ]
}
```

![image](https://user-images.githubusercontent.com/19742638/113714795-c9df4900-96b6-11eb-8bec-34a520114677.png)

Getting unused import errors from pylance. Based on what I read from pyright it should disabled.
Errors:
```
"SessionDataWrapper" is not accessedPylance
Import "SessionDataWrapper" is not accessedPylancereportUnusedImport
```

**Comment by erictraut** [comment]
The "exclude" option doesn't prevent Pylance from analyzing a file and reporting errors if the file is opened in your editor. It simply means "treat this file (or directory) as though it's not part of my project".

If you want to ignore all errors in this file even when it is open in the editor, you should use the "ignore" option in pyrightconfig.json. Alternatively, you can use a `# type: ignore` comment at the top of the file to suppress all errors in it.
