### ISSUE TITLE
PyLance freezes VS Code

### ISSUE THREAD

**Issue by casassg** [microsoft/pylance-release#113]
## Environment data

-   Language Server version: 2020.7.1
-   OS and version: MacOS Catalina - 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6, CPython

## Expected behaviour

Working nicely

## Actual behaviour

VS Code completly freezes after loading the Python extension making it unusable. 

## Logs
Can't copy them as window freezes. Pasting screen capture

<img width="2700" alt="Screen Shot 2020-07-14 at 1 13 10 PM" src="https://user-images.githubusercontent.com/6912589/87466615-d1fcd300-c5d3-11ea-8302-730804a4a20f.png">

**Comment by bschnurr** [comment]
Have you tried the latest 2020.8.1 build? Is it still happening?

**Comment by casassg** [comment]
Works now! Thanks!
