### ISSUE TITLE
Pylance incorrectly reports that SQLAlchemy 1.4.5 Session object cannot be used in With statement because it has no __exit__ method

### ISSUE THREAD

**Issue by TurboCooler** [microsoft/pylance-release#1131]
## Environment data

-   Language Server version: 2021.3.4
-   OS and version: Microsoft Windows 10 Enterprise Version 10.0.18363 Build 18363
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.7 

## Expected behaviour

Pylance should have found the __exit__ dunder method and not have flagged this as a problem.   I am using "python.analysis.typeCheckingMode" :"Basic".  I inspected the SQLAlchemy code and __exit__ does exist.  

## Actual behaviour

Pylance incorrectly reports that SQLAlchemy 1.4.5 Session object cannot be used in With statement because it has no __exit__ method

## Logs

```
XXX
```

## Code Snippet / Additional information

```PYTHON
        with Session(self.sqlengine, future=True) as session:
            statement = select(Carrier)
            #return session.execute(statement).all()
            return session.execute(statement).scalars().all()
```

**Comment by jakebailey** [comment]
Pylance includes stubs from https://github.com/dropbox/sqlalchemy-stubs, and those would be the types that are being used here, not the real code. The newer WIP stubs at https://github.com/sqlalchemy/sqlalchemy2-stubs also are missing `__exit__`, as far as I can tell.

Can you give a larger code snippet? Which `Session` class is this?

To fix this, a fix would need to be applied upstream, I'd think.

**Comment by erictraut** [comment]
Do you have the `sqlalchemy-stubs` package installed in your environment?

The `Session` class definition in `sqlalchemy-stubs` does not include an `__exit__` method. Here is a [link](https://github.com/dropbox/sqlalchemy-stubs/blob/7c93cd31ef386b421b7aa9c595bb42580e47f61e/sqlalchemy-stubs/orm/session.pyi#L32) to the code in the `sqlalchemy-stubs` repo. Looking at the sqlalchemy source code, it does appear that `Session` should be usable as a context manager, but I suspect that was a relatively recent addition. That probably means the stubs are out of date with the source code. I encourage you to file a bug report or a PR with the `sqlalchemy-stubs` project.

**Comment by erictraut** [comment]
Here's a minimal repro:
```python
from sqlalchemy.orm import Session

with Session() as session:
    ...
```

**Comment by randallpittman** [comment]
Workaround for any fellow Googlers:

sqlalchemy2-stubs seems to have made quite a bit of progress recently. Running `pip install sqlalchemy2-stubs` made Pylance work much more nicely with SQLAlchemy 1.4.26.

**Comment by jakebailey** [comment]
Thanks for that feedback; if these stubs are far enough along, we may consider shipping them rather than the older stubs. I think we had been waiting because their readme says that the status is "alpha" and they aren't more mature than the Dropbox ones. Maybe that's not true anymore.

**Comment by randallpittman** [comment]
> I think we had been waiting because their readme says that the status is "alpha" and they aren't more mature than the Dropbox ones. Maybe that's not true anymore.

I can't speak to that. I'm a lightweight user and haven't delved into that project's Issues. So I'm going to assume for now that it's a temporary workaround to *hopefully* make Pylance work better but not yet 100% trustworthy for mypy etc.
