### ISSUE TITLE
"Go to definition" for object in method

### ISSUE THREAD

**Issue by yunmingyang** [microsoft/pylance-release#1135]
If a method accept a object, and call a method of the object, "go to definition" for this method will not take effect. Such as
```python
class Test:
    def __init__(self, obj) -> None:
        self.test1()
        obj.test2()

    def test1(self):
        print("test1")


class TestMethod:
    def test2(self):
        print("test2")
```
Clicking "go to definition" of "obj.test2()" get "No definition found for 'test2'".
Is it possible that adding a list for choosing when clicking "go to definition" of the method like "obj.test2()" ?

**Comment by erictraut** [comment]
The type of `obj` is not known in this example, so there's no way for Pylance to determine which method it should "go to". If you provide a type annotation for `obj`, it will be able to determine which method the code is referring to:

```python
    def __init__(self, obj: TestMethod) -> None:
        ...
```

**Comment by yunmingyang** [comment]
Thanks, it work for me.
