### ISSUE TITLE
Give keywords the same sort order as local variables in completions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pylance-release#1136]
**Describe the bug**

When explicitly requesting completions in an argument list with no initial variable name, only only parameter names are provided as completion items.

On the other hand, if you do provide a single letter, you will start to get completions for names other than named parameters, which I would say is slightly more expected.

**To Reproduce**

Request completions at each `/**/`, then compare:

```python
def foo(hello: str, world: str):
    pass

foo(/**/)
```

```python
def foo(hello: str, world: str):
    pass

foo(h/**/)
```

```python
def foo(hello: str, world: str):
    pass

foo(hello="hello", /**/)
```

**Expected behavior**

I would expect all parameter names to be provided alongside all reachable variable names. I would also expect the parameter names to be sorted higher.

**Screenshots or Code**

![image](https://user-images.githubusercontent.com/972891/114072119-bec31f00-9856-11eb-8b76-e564fe2baa37.png)

![image](https://user-images.githubusercontent.com/972891/114072132-c256a600-9856-11eb-8c78-2ec7a45c510b.png)

**VS Code extension or command-line**

Extension

**Comment by jakebailey** [comment]
I guess I'm a little confused; what local are you expecting to see in your first example? I don't see any variable in scope of that call that has the letter `h` in it.

Are you expecting to see `foo` itself as a variable?

There is an issue with our current completion where we offer keywords in contexts where some keywords may not be expected, so that's why you're seeing them there (and we should tweak that), but I'm not sure which locals you're missing.

**Comment by erictraut** [comment]
I'm not clear on what you mean. Let's look at the case where you have not specified any arguments yet — e.g. the insertion point is between the parens in the expression `foo()`. I agree with you that completion suggestions should include all keyword parameter names and all other variables (and other symbols) that are currently in scope. That's consistent with what I'm seeing — both in your screen shot above and when I repro the situation locally. The keyword parameters in this sample include `hello=` and `world=`. There are no local variables at this scope, but we can easily add one — e.g. add the line `my_var = 3` above the call expression `foo()`. Once I do that, then I see both keyword parameters and the local variable `my_var` suggested.

And as you suggested, the keyword parameter names are sorted higher than the in-scope symbol names. Here's a screen shot of what I see in this case.

![Screen Shot 2021-04-08 at 10 56 53 AM](https://user-images.githubusercontent.com/7040122/114074380-28442d00-9859-11eb-8730-6ebf8b77806d.png)

What am I missing?

**Comment by DanielRosenwasser** [comment]
I see my confusion now - keyword completions are sorted close to the very top of the list, and when I saw that many gray icons for completions that weren't relevant, I assumed there was nothing else below them - so I didn't keep scrolling down the completion list. 😅

Maybe my issue is really that keywords should be given the same sort order as locals.

**Comment by heejaechang** [comment]
closing it as dup - https://github.com/microsoft/pylance-release/issues/1557
