### ISSUE TITLE
'yield' keyword appears twice in completion lists

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pylance-release#1137]
![image](https://user-images.githubusercontent.com/972891/114076241-4ca10900-985b-11eb-9dcd-c8a221701edd.png)

https://github.com/microsoft/pyright/blob/2918da1d0281ef0d8a1336512ccc81c4232960d6/packages/pyright-internal/src/languageService/completionProvider.ts#L116

https://github.com/microsoft/pyright/blob/2918da1d0281ef0d8a1336512ccc81c4232960d6/packages/pyright-internal/src/languageService/completionProvider.ts#L142

**Comment by jakebailey** [comment]
Thanks for the report, I'll get a fix in for this.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.4.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202141-14-april-2021
