### ISSUE TITLE
Intellisense is slow for pandas

### ISSUE THREAD

**Issue by dlefcoe** [microsoft/pylance-release#1144]
## Environment data

-   Language Server version: v2021.4.0

-   OS and version: windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0

## Expected behaviour

intellisense to show up immediately < 1 second.

## Actual behaviour

when pandas module is imported with: `import pandas as pd` the intelisense becomes slow.
if the user types "pd." they would expect the intellisense to be < 1 second for the menu, but it takes several seconds. 

## Logs

```
i dont see the logs with the given instruction.

```

## Code Snippet / Additional information

example of the slowing once pandas is imported.
![pandas slows intellisense](https://user-images.githubusercontent.com/17166744/114245078-9e46b200-9987-11eb-8077-e3029c130ef4.gif)

```python

python 3.9.0 64bit

```

**Comment by jakebailey** [comment]
We will need those logs. They should be located in the output panel if you select "Python Language Server", like:

![image](https://user-images.githubusercontent.com/5341706/114249020-33c55000-994e-11eb-9aca-80177efe447f.png)

**Comment by jakebailey** [comment]
Is it slow once pandas has been completed on once? Some slowness at the first completion is to be expected (as we analyze pandas once it's used), but after the analysis should be cached.

**Comment by dlefcoe** [comment]
It is continuously slow.

Some times, its faster when i revisit the same code.

**Comment by dlefcoe** [comment]
python langauge server does not appear to be one of the drop down options.

![image](https://user-images.githubusercontent.com/17166744/114262795-e262a280-99d9-11eb-93a2-8bb9313e61fd.png)

**Comment by erictraut** [comment]
It looks like you're not running Pylance. I suspect you're running the Jedi language server instead. If you select the Output tab and display the output for "Python", do you see the text "Starting Jedi Python language engine" in the log?

Please make sure to install the Pylance extension and set `"python.languageServer"` to `"Pylance"`.

I was able to repro the slow behavior you're seeing in Jedi. With Pylance installed, it's significantly faster the first time you try to complete a symbol from pandas, and it's almost instantaneous after the first.

**Comment by dlefcoe** [comment]
This is everything in the log:


`User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonSendEntireLineToREPL'
User belongs to experiment group 'pythonNotDisplayLinterPrompt'
User belongs to experiment group 'pythonDiscoveryModulecf'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'DeprecatePythonPath - experiment'
> conda --version
> pyenv root
> python3.7 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2021-04-11 18:11:10: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\Owner\Dropbox\programming\python\general\tests\.vscode\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\Owner\Dropbox\programming\python\general\tests\.vscode\settings.json')
	at _handleError (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:154942)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async y.readText (c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:9:328725)
	at async p.doesFileNeedToBeFixed (c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:578263)
	at async c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:577390
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:577336)
	at async p.updateTestSettings (c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\out\client\extension.js:61:576963)] {
  code: 'FileNotFound'
}
> ~\Anaconda3\Scripts\conda.exe info --json
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
Starting Jedi Python language engine.
> ~\Anaconda3\Scripts\conda.exe info --json
> pyenv root
> pyenv root
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: c:\Users\Owner\Dropbox\programming\python\general\tests
> ~\Anaconda3\Scripts\conda.exe env list
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py
Error 2021-04-11 18:11:14: stderr jediProxy Error (stderr) c:\Users\Owner\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

> ~\Anaconda3\Scripts\conda.exe env list
`



I have now updated the settings to:
`"python.languageServer":"Pylance"`

and this runs the language server:
`Starting Pylance language server.
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
> ~\Anaconda3\Scripts\conda.exe info --json
> ~\Anaconda3\Scripts\conda.exe env list
> ~\Anaconda3\Scripts\conda.exe info --json
> ~\Anaconda3\Scripts\conda.exe env list`

So will see what happens in the next day or so.

**Comment by gramster** [comment]
This was definitely jedi (which is slower), so not a pylance issue. If you have issues with pylance please come back and create a new issue.
