### ISSUE TITLE
Control autosuggestions on quote

### ISSUE THREAD

**Issue by ausiddiqui** [microsoft/pylance-release#1146]
This is on a macOS using Code - Insiders with Pylance. Opening a quote (single/double/triple) triggers the file selection menu. Firstly, is there a way to stop this -- would be great for the file selection pop-up to appear if there is a "/". 

Secondly, is there a way to ignore certain file types in this suggestion. It doesn't seem to honor the Files: Exclude settings option. Right now every time I open a triple-double quote to enter SQL text and press enter it auto-inserts """.DS_Store""" -- (the first suggestion from any macOS folder). So have to type-quote and ESC to ignore this suggestion.

![auto-suggestions](https://user-images.githubusercontent.com/9053345/114259785-4e66eb80-9985-11eb-9b10-142fdc66775b.jpg)

**Comment by jakebailey** [comment]
Pylance doesn't provide path competitions. Do you have another extension installed that is providing them?

**Comment by jakebailey** [comment]
It's been a month since I asked the above; closing. I'm pretty sure that this is another extension (or maybe the Jupyter kernel).
