### ISSUE TITLE
Intellisense doesn't recognize concatenated methods

### ISSUE THREAD

**Issue by dsgon** [microsoft/pylance-release#1147]
Hi!

I'm working in a automation framework and I created different methods that could be called using the same instance, because I am returning 'self' after every method.

Something like this:

![image](https://user-images.githubusercontent.com/37479902/114283573-c7ffe780-9a20-11eb-948c-308c001c1633.png)

So, in my current script I can call the methods without any problem

![image](https://user-images.githubusercontent.com/37479902/114283586-d77f3080-9a20-11eb-8668-4ad772700332.png)

But, the intellisense doesn't recognize the method as an instance of menu class, so this method doesn't have any suggestion to show.
![Visual Studio Code](https://user-images.githubusercontent.com/37479902/114283518-87a06980-9a20-11eb-8faf-221399cb6d91.png)

How can I configure VS or Pylance to fix this issue?

Thanks.

**Comment by erictraut** [comment]
I'm confused by your code. The expression `menu().verifySwitchToOption()` seems to imply that the `menu` class has an instance method called `verifySwitchToOption`. Is that the case? I can't see the declaration for your `menu` class, so I can't verify. I can see a function definition for `verifySwitchToOption`, but that function has nothing to do with the `menu` class, so it wouldn't be invoked by the expression `menu().verifySwitchToOption()`.

Does the code in your screen shots actually run, or is it a work in progress that has not yet been executed?

**Comment by erictraut** [comment]
If you are trying to write a generic method that accepts any object and returns the same object, this is the proper way to annotate it. Pylance will use these type annotations to provide the completion suggestions.

```python
from typing import TypeVar

_T = TypeVar("_T")

def foo(self: _T) -> _T:
    return self
```

**Comment by dsgon** [comment]
Hi @erictraut 

`verifySwitchToOption()` is a method from `MenuSteps`

![image](https://user-images.githubusercontent.com/37479902/114285443-b244ef00-9a2d-11eb-89f5-e6aaed0343a5.png)

As you can see. `MenuSteps` class applies inheritance from `BaseSteps` that contains a method called `takeScreenshot()`
![image](https://user-images.githubusercontent.com/37479902/114285884-ef5eb080-9a30-11eb-9756-f8f890929068.png)

So, if I call a instance of MenuSteps I should access to `verifySwitchToOption()` and `takeScreenshot()` methods concatenated because `verifySwtchToOption()` return `self` (MenuSteps).

So, the code is completely functional, it's work fine, but Pylance doesn't recognize it

![image](https://user-images.githubusercontent.com/37479902/114286404-c2ac9800-9a34-11eb-88d8-d08083dd05e0.png)

**Comment by erictraut** [comment]
Thanks for the additional details. I guess that the previous screen shots were cutting off the left side, so it wasn't clear that those were methods within a class.

It would be useful if you could create a minimal, self-contained repro of the problem. I've attempted to do that based on the screen shots above, but it all seems to be working fine for me. Here's a short video of what I'm seeing. Is this different from what you're seeing?

![Apr-10-2021 17-26-54](https://user-images.githubusercontent.com/7040122/114288212-4a3cdb80-9a22-11eb-8f0d-6ed42e46b5be.gif)

One thought is that the `@allure.step` decorator may be obscuring the signatures of your methods, thus preventing Pylance from understanding the return types. Which version of allure-pytest are you using? I installed the latest version, which appears to be 2.8.40. This package does not have proper type information, so Pylance will need to attempt to infer type information from it. Pylance will normally do this by default, but let's just confirm that you haven't disabled the "python.analysis.useLibraryCodeForTypes" setting.

**Comment by dsgon** [comment]
Thanks for the answer @erictraut 

I was using `allure-pytest 2.8.13` and I update to the latest version and this fix the issue. Obviously it's a incompatibility of versions with allure-pytest

![image](https://user-images.githubusercontent.com/37479902/114290654-8c344480-9a57-11eb-80c3-5636d9d33c27.png)

For me the question could be closed.
