### ISSUE TITLE
Higher-kinded type variables are not resolved within the function argument

### ISSUE THREAD

**Issue by wvolkov** [microsoft/pylance-release#1148]
## Environment data

-   Language Server version: Pylance language server 2021.4.0
-   OS and version: Windows 10 x64, Build: 19042.867
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.9
-   WSL: Ubuntu 20.04
-   VS Code: 1.54.3

## Expected behavior

1. define function, returning generic typed result
2. declare new function with argument of type with function from p. 1
3. argument type should be resolved according to provided generic type

## Actual behavior
3. No suggestions by intellisence

## Example Code

```python
from dataclasses import dataclass
from typing import TypeVar, Optional

T = TypeVar("T")


def dataclass_wrap(cls: T ) -> T:
    pass

@dataclass
class TestData:
    t_id: int
    t_desc: Optional[str] = None


def func(x: dataclass_wrap(TestData)):
    x.  # <-- no type hint

def func2():
   x = dataclass_wrap(TestData)
   x.t_  # <-- type hint works

```

## Screens
![image](https://user-images.githubusercontent.com/49549154/114299283-12d23b80-9ac3-11eb-8c69-c4b88e83cb46.png)

![image](https://user-images.githubusercontent.com/49549154/114299275-0c43c400-9ac3-11eb-8541-9ddff62aee6e.png)

**Comment by erictraut** [comment]
Function call expressions such as `dataclass_wrap(TestData)` cannot be used within a type annotation. If you enable the type checker functionality in Pylance (`"python.analysis.typeCheckingMode": "basic"), you will see that Pylance complains about this usage. 

Pylance is treating this errant type annotation as `Any`, which is why you are seeing no type hint in this situation.

**Comment by wvolkov** [comment]
Thanks for the info, is it a PyLance limitation?
What confuses me is the fact that such statements are working well at PyCharm:
![image](https://user-images.githubusercontent.com/49549154/114311930-68293f80-9af9-11eb-8b17-c8987ecaf2aa.png)

**Comment by erictraut** [comment]
PEP 484 is somewhat ambiguous about which expression forms are allowed for type annotations, but there are good reasons for function call expressions to be rejected. For details, refer to [this discussion](https://github.com/python/mypy/issues/10277). 

Mypy (another popular Python type checker) and pyright (the type checker that underlies Pylance) both reject call expressions in type annotations. I recommend using a type alias instead.

**Comment by wvolkov** [comment]
How should I handle situations were we can't use type alias because type may vary depending on exact implementation? I am contributing to a object-oriented rest framework based on starlette that allows easily build REST API, operating with schemas and dataclasses and there are infinity possible combinations of REST methods request/response bodies. 

The idea of its usage is rather simple: define a schema and pass it into an exec method that allows you to automatically validate and use it at further code, in that case all you have to care about is to define an appropriate annotation function depending on request/response mime-type:

```python
#... lines skipped
app = Starlette(debug=True)

@app.route('/post/dataclass', methods=['POST'])
@endpoint
class PostDataclass(Method):
    async def execute(self, item: json_schema(JsonPayloadDataclass, Payload)):
        return {'a': item.a * 3, 's': item.s}
```

<details>
   <summary> Full Code </summary>

   ```python
from marshmallow import Schema, fields, ValidationError, post_load
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from dataclasses import dataclass
from star_resty import Method, endpoint, json_schema
from typing import Optional


# Json Payload (by dataclass)
@dataclass
class Payload:
    a: int
    s: Optional[str] = None

class JsonPayloadDataclass(Schema):
    a=fields.Int(required=True)
    s=fields.Str()

    @post_load
    def create_payload(self, data, **kwargs):
        return Payload(**data)


app = Starlette(debug=True)

@app.route('/post/dataclass', methods=['POST'])
@endpoint
class PostDataclass(Method):
    async def execute(self, item: json_schema(JsonPayloadDataclass, Payload)):
        return {'a': item.a * 3, 's': item.s}

@app.exception_handler(ValidationError)
def register_error(request, e: ValidationError):
    return JSONResponse(e.normalized_messages(), status_code=400)


if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, port=8080)
   ```

</details>

**Comment by erictraut** [comment]
I think you may be confused about the way static type checkers work. They don't execute the code like an interpreter would. Instead, they apply static rules based on type annotations, and they verify type consistency based on the resulting types.

A function's implementation is generally ignored by a static type checker when evaluating the return type of a call expression that references that function. (I say "generally ignored" because the function implementation can be used to infer the return type of the function if an annotation is missing, but that's not the case in your example above because `json_schema` has an annotated return type.)

The type returned by the function `json_schema` is always `P`, and it depends only on the type of the argument passed for parameter `cls`. That means that the (illegal) type annotation `json_schema(JsonPayloadDataclass, Payload)` is equivalent to the (legal) type annotation `Payload`. But I don't think that's what you intend here.

I have to admit that I don't fully understand what you are trying to do, so I'm unable to suggest the right way to model it so it works with static type checking.

Perhaps you can explain in more detail what `Payload` and `JsonPayloadDataclass` are meant to represent. These are two distinct classes. I presume that the `item` parameter is an instance of one of these two classes, but I'm not sure which. It can't be an instance of both. The annotation for the `item` parameter should reflect the type that it is expected to contain when `execute` is called.

**Comment by wvolkov** [comment]
Sorry for such an unclear response, let me try to shed some light onto it.

The idea of that `exec` method is just to provide into its argument an appropriate function (`json_schema` in example) that will do the following actions over raw data:
1. accepting the basic `marshmallow` library `Schema` (in example above `JsonPayloadDataclass`)
2. verifying, whether the provided payload/queryparams to a method (in example above `POST /post/dataclass`) are valid or not according to that schema. If not it will raise standard `ValidationError` which is handled separately
3. In case of success validation - returning an instance of a dataclass (above - `Payload`) according to provided schema for more convenient usage in 'exec' body (like `item.a`, `item.s`) 

So it contains two-in-one logic: validation and parsing into a data, thus item result type is considered to be a 'Payload' in my example. This is an example for json payload body, the same approach for query parameters, multipart/form data payload, etc. Based on that it is possible to build a new `xml` parser that will accept 'text/xml' mime type and many other variations of REST payloads.

That `exec` method is able to accept multiple parsers, for instance if you want your API to accept both query params and payload with validation, you can easily draw a validation schema to each of it and implement it in a next few lines:

```python 
#... json payload schema  is the same as at example above

class QuerySchema(Schema):
   id = fields.Int(required=True)
   meta = fields.Str()

@app.route('/get/the/data', methods=['GET'])
@endpoint
class PostDataclass(Method):
    async def execute(self, json_payload: json_schema(JsonPayloadDataclass, Payload), query_params: query(QuerySchema):
        return {'a': json_payload.a * 3, 's': json_payload.s, 'query_params': query_params}
```

Hope that could help.

**Comment by erictraut** [comment]
Are you expecting the `json_schema` function to be invoked at runtime? The Python interpreter generally doesn't evaluate type annotations. In fact, as of Python 3.10 (or earlier if you include `from __future__ import annotation` at the top of the file), the Python interpreter will do nothing with type annotations other than verify that they are syntactically correct. 

It is possible (though not typical) for annotations to be accessed at runtime and evaluated. Are you relying on this behavior? For example, are you assuming that the `@app.route` decorator introspects the `execute` method and evaluates its type annotation expressions at runtime?

While it's illegal to use call expressions within type annotations, you can use call expressions outside of a type annotation and use the result in a type annotation. See below. Does this accomplish your goal?

```python
@app.route("/post/dataclass", methods=["POST"])
@endpoint
class PostDataclass(Method):
    PayloadWithParser = json_schema(JsonPayloadDataclass, Payload)
    async def execute(self, item: PayloadWithParser):
        return {"a": item.a * 3, "s": item.s}
```

**Comment by wvolkov** [comment]
> It is possible (though not typical) for annotations to be accessed at runtime and evaluated. Are you relying on this behavior? For example, are you assuming that the @app.route decorator introspects the execute method and evaluates its type annotation expressions at runtime?

No I aren't. 

I tried your approach and it worked brilliantly - each data class property is accessed via dot notation all you need to do is to prepare that type before passing hint into method argument.

```python
from dataclasses import dataclass
from typing import TypeVar, Optional

T = TypeVar("T")

def dataclass_wrap(cls: T ) -> T:
    pass

@dataclass
class TestData:
    t_id: int
    t_desc: Optional[str] = None

TestDataWrap = dataclass_wrap(TestData)

def func(x: TestDataWrap):
    x.  # <-- intellisence works well fields t_id and t_desc are accessible via dot notation
```

Thank you!
