### ISSUE TITLE
Most pyglet functions marked as NoReturn

### ISSUE THREAD

**Issue by runapp** [microsoft/pylance-release#1151]
Pylance 2021.4.0

e.g. `glEnable` is marked as `(variable) glEnable: Any | _FuncPointer | (*args, **kwargs) -> NoReturn` , causing all following code recognized as unreachable.

## Code Snippet / Additional information

```python
import pyglet
from pyglet.gl import *

glEnable(GL_DEPTH_TEST)
print('hello,world')   # This line (and all code after) is grayed out
```

**Comment by erictraut** [comment]
Pyglet appears to be an untyped library — that is, it doesn't provide any type information as per PEP 561. Without type information, pylance will do its best to infer type information from the source code. Alas, the library is using techniques that are not possible for pylance to statically analyze.

If this library is important to you, please contact the library maintainers and encourage them to provide type information. Here is some [documentation](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md) that provides guidance to library authors.

If you're ambitious, you could attempt to create [type stubs](https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md) for this library. Pylance can give you a head start by creating a "first draft" of these type stubs, but you'll need to do significant work to fill in the missing type annotations.

**Comment by runapp** [comment]
Thank you for the information. I didn't know that `.pyi` files was created by hand.
It seems that analyzing such dynamic code is out of pylance's scope? So I'll close the issue.
