### ISSUE TITLE
Undefined Variable error when importing modules/functions in a function and defining them global

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/pylance-release#1154]
## Environment data

-   VS Code version: 1.55.1
-   Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS and version: Windows 10 20H2
-   Python version : 3.7.6
-   Type of virtual environment used : N/A
-   Relevant/affected Python packages and their versions: -
-   Relevant/affected Python-related VS Code extensions and their versions: -
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour
Pylance not saying there is an Undefined-variable error

## Actual behaviour
Well I get almost 100 errors about mentionning an *apparently* not defined function

## Steps to reproduce:
Here is a sample code that triggers this bug
```python
def importFunc() :
    global math
    try :
        import math
    except ImportError : print("There was a fatal import error"); exit()
if __name__ == '__main__' :
    importFunc()
    math.sqrt(4)
#   Here pylance should underline in red saying math is undefined variable
```
Note : same would happen if instead I did `global sqrt; from math import sqrt`
## Picture
![image](https://user-images.githubusercontent.com/64481347/114623764-02cb7f00-9cb0-11eb-80df-a65269a0c51c.png)

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\cleme\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text "c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python\test.py"
cwd: c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\cleme\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text "c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python\test.py"
cwd: c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python
##########Linting Output - pylint##########

------------------------------------

Your code has been rated at 10.00/10



> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\cleme\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text "c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python\test.py"
cwd: c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python
> ~\AppData\Local\Programs\Python\Python37\python.exe c:\Users\cleme\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text "c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python\test.py"
cwd: c:\Users\cleme\OneDrive\Sauvegarde PC-STDO\Desktop\Documents\Python
##########Linting Output - pylint##########
************* Module test
8,4,error,undefined-variable:Undefined variable 'math'

-------------------------------------------------------------------

Your code has been rated at 5.00/10 (previous run: 10.00/10, -5.00)
```

</p>
</details>

**Comment by erictraut** [comment]
I'm a bit confused by this bug report. Are you saying that you think pylance should generate an error here but it doesn't (a false negative)? Or are you saying that it is generating an error but shouldn't (a false positive)?

I don't think that a linter or type checker should report an error in this case. Pylance does not report an error, so I think it's doing the correct thing here.

The screen shot above shows an "undefined-variable" error reported from pylint. If you think this is a false positive error (and I agree that it is), then I recommend that you file a bug report in the pylint repo.

**Comment by jakebailey** [comment]
Yeah, I'm pretty sure that this is all pylint. pylint should be getting disabled when a language server is used; have you force enabled pylint? You may want to disable it.

**Comment by cl-ement05** [comment]
> I'm a bit confused by this bug report. Are you saying that you think pylance should generate an error here but it doesn't (a false negative)? Or are you saying that it is generating an error but shouldn't (a false positive)?
Yes this is a false positive

**Comment by cl-ement05** [comment]
> pylint should be getting disabled when a language server is used; have you force enabled pylint? You may want to disable it.

Well when I installed the Pylance and Python extentions in vs code, a notification popped up saying pylint is not installed and I should install it. So I thought pylint was somehow a dependency of Pylance.

Now I am a bit confused. What is pylint job here, and what is Pylance used for if pylint does all the linting stuff ?
How can I disable pylint ?

**Comment by jakebailey** [comment]
That's a good point; @luabud would likely know better about when these prompts appear. It's likely we'll want to tweak this for the future.

pylint is a "linter" and can do many things, including providing diagnostics about unresolved imports, syntax errors, etc, on save. When running Pylance, it's not needed unless you want some of its other style-related things to run. For a more historical explanation, see: https://github.com/microsoft/pylance-release/issues/509#issuecomment-736088183

You should be able to disable pylint by setting:

```
"python.linting.pylintEnabled": false
```

In your `settings.json`, but I would argue that you shouldn't need to do this and there's some problem with the Python extension when Pylance is enabled.

**Comment by cl-ement05** [comment]
> In your `settings.json`, but I would argue that you shouldn't need to do this and there's some problem with the Python extension when Pylance is enabled.
Well I opened an issue in the pylint repo.


> You should be able to disable pylint by setting:
> 
> ```
> "python.linting.pylintEnabled": false
> ```
Well when I do this; nothing happens, even after reloading vs code, pylint is still enabled.
So I uninstalled it using the pip3 command. But now, when VS code starts-up, I get again this notification saying pylint is not installed and I should either install it either select another linter (and Pylance does not appear in this list).

So is Pylance a linter ?

Since I removed pylint, I won't get any diagnostics any more (unless I reinstall it) ?

**Comment by jakebailey** [comment]
Is it possible you have that setting in multiple places? This seems like a Python extension bug if the pylint setting is ignored.

I'd read my linked comment about the difference between Pylance and a linter; we do some of the same things as linters were previously used for (syntax checks and import checks), but much much more. For the most part, you don't need a linter when you use Pylance (or any other language server for that matter), unless you want specific rules from a specific linter to do with style.

**Comment by cl-ement05** [comment]
> Is it possible you have that setting in multiple places? This seems like a Python extension bug if the pylint setting is ignored.
No I checked my whole settings.json file. So yeah it may be a bug

Thank you for your explanation about linting and Pylance
