### ISSUE TITLE
Operator "+" not supported for URLPattern

### ISSUE THREAD

**Issue by OmidShojaee** [microsoft/pylance-release#1157]
## Environment data

-   Language Server version: 2021.4.1-pre.1
-   OS and version: Windows 10 Build 19042.867 (version 20H2)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.2

## Expected behaviour

It is completely valid to use "+" operator with URLPattern.
[https://docs.djangoproject.com/en/3.2/howto/static-files/#serving-static-files-during-development](url)

## Actual behaviour

Pylance shows error in the following piece of Django code:
```
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
```
The error message is:
```
Operator "+" not supported for types "list[URLResolver]" and "List[URLPattern]"
```
According to Django's official document, "+" is fully supported.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
FWIW, the error message above isn't complaining about `URLPattern`, it's complaining that that these are two lists being added together that contain different types.

Unfortunately the stubs for `list` don't really capture the behavior that `List[X] + List[Y] = List[Union[X, Y]]`:

https://github.com/python/typeshed/blob/901b8cb92d7dff50705c39d43522e7c3ee40fd70/stdlib/builtins.pyi#L744

mypy complains about this too: https://mypy-play.net/?mypy=latest&python=3.9&gist=2e97af622ba78cb942bc032a7ebee66e

**Comment by OmidShojaee** [comment]
I installed Pylance to help me catch real errors not to confuse me with false alarms and waste my time trying to figure out what is the problem with my code — where there's no problem.

I uninstalled it until you release a useful version.
