### ISSUE TITLE
Problematic result type for calling overloaded function with `Any` or `Unknown` as argument(s)

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1164]
## Environment data

-   Language Server version: 2021.4.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 Anaconda

## Sample code

```python
from __future__ import annotations

from typing import Any, overload

@overload
def f(x: int, /) -> int:
    ...

@overload
def f(x: str, /) -> str:
    ...

def f(x: int | str, /) -> int | str:
    ...

def make_any() -> Any:
    ...

any = make_any()  # Type of `any` is `Any`.
result_0 = f(any)

from builtins import unknown  # Type of `unknown` is `Unknown`.
result_1 = f(unknown)
```

## Expected behavior

Both types of results are `int | str` if possible, or `Unknown`.

## Actual behavior

Both types of results are `int`.

## Personal Thought

To make things easy, the result type can be determined by the function implementation, whenever an overloaded function is called with at least one argument of `Any` or `Unknown`.

Under this rule, the result type may be inexact, but can almost never be wrong.

**Comment by erictraut** [comment]
The current behavior is as intended. Pyright's overload behavior will pick the first matching overload, not all of the overloads that match.

**Comment by Azureblade3808** [comment]
Thank you for the info.

Good to know there has already been a rule for such cases, which I can fully imagine the reasoning behind.
