### ISSUE TITLE
Auto-completion/type hints for pymongo/motor

### ISSUE THREAD

**Issue by paulcmmrclly** [microsoft/pylance-release#1170]
## Environment data

-   Language Server version: `Pylance=v2021.4.1 (pyright 6410a8a2), Python=v2021.5.756443519-dev`
-   OS and version: macOS Big Sur / Darwin arm64 20.3.0
-   Python version: 3.8

## Expected behaviour

Auto-completion and type inference should work.

## Actual behaviour

No auto-completion and type hints are shown. 

## Code Snippet / Additional information

Install motor with `pip install motor`.

```python
from motor.motor_asyncio import AsyncIOMotorClient

CONN_URI = "mongodb://root:123456@localhost:27017"

client = AsyncIOMotorClient(CONN_URI, tz_aware=True)
db = client.get_database("dbber")
sc_sessions = db.get_collection("sc_sessions")
```

**Comment by bschnurr** [comment]
Can you please specify which completions are missing? Please include a screenshot. Thank you

**Comment by paulcmmrclly** [comment]
![image](https://user-images.githubusercontent.com/78375179/115407339-3a768180-a1f0-11eb-990e-e8645d589ed9.png)
![image](https://user-images.githubusercontent.com/78375179/115407410-48c49d80-a1f0-11eb-9c0d-f3be2789f67d.png)

**Comment by jakebailey** [comment]
This library appears to be doing something very funky (this "metaprogramming" thing that dynamically builds classes):

```python
from . import core, motor_gridfs
from .frameworks import asyncio as asyncio_framework
from .metaprogramming import create_class_with_framework

__all__ = ['AsyncIOMotorClient','AsyncIOMotorClientEncryption']


def create_asyncio_class(cls):
    return create_class_with_framework(cls, asyncio_framework,
                                       'motor.motor_asyncio')


AsyncIOMotorClient = create_asyncio_class(core.AgnosticClient)
```

It's likely that they'd benefit from some type annotations or stubs to describe this behavior, as it's a bit too dynamic for us to handle.

**Comment by paulcmmrclly** [comment]
@jakebailey That looks very "funky" indeed. I guess this issue belongs upstream then. Thank You!
