### ISSUE TITLE
Enable running pylance on code-server

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#1172]
Hi pylance

Thanks for providing this great tool. 

**Could you please add support for running pylance on code-server such that it can be used more broadly?** See https://github.com/cdr/code-server/issues/1938#issuecomment-822623573

My use cases are

**Use Case - Open Source on Binder**

I am a contributor to [HoloViz Panel](https://panel.holoviz.org) which builds on Bokeh and is a framework for creating powerful analytics apps in Python. Those apps can be developed in VS Code either as `.py` or `.ipynb` files. They can also run inside the notebook/ datascience experience of VS Code with full interactivity.

I am trying showcase how powerful a combination Panel and VS Code is by deploying it to binder.

https://mybinder.org/v2/gh/holoviz/panel/binder?urlpath=lab/tree/examples

But I cannot get it installed by running something similar to the below but with `ms-python.vscode-pylance` added.

```bash
conda install -c conda-forge code-server
code-server --install-extension ms-python.python
SERVICE_URL=https://open-vsx.org/vscode/gallery ITEM_URL=https://open-vsx.org/vscode/item code-server --install-extension wesbos.theme-cobalt2
SERVICE_URL=https://open-vsx.org/vscode/gallery ITEM_URL=https://open-vsx.org/vscode/item code-server --install-extension RandomFractalsInc.vscode-data-preview
```

![image](https://user-images.githubusercontent.com/42288570/115338993-3cb2ee80-a1a4-11eb-9235-7a3a2c6bec2f.png)

**Use Case - Jupyter Hub in Enterprise**

I'm the product owner in an Enterprise for a Jupyter Hub. The Jupyter Hub should lower the friction of working with Python and Data Science. I would like to support power users to continue to use VS Code in their workflow. But now running as `code-server` on the Jupyter Hub. 

Unfortunately running `code-server` is the only (secure) option for using the full VS Code experience with Jupyter Hub I have been able to find. Running VS Code locally on users laptop and using the Jupyter Hub via SSH is not allowed by our IT.

**Comment by judej** [comment]
@MarcSkovMadsen, Pylance is licensed for use in Microsoft products and services only. A substantial portion of Pylance is available via [Pyright](https://github.com/microsoft/pyright) which is open source and can be incorporated into other products - examples VIM, Sublime and Emacs.

thanks
