### ISSUE TITLE
PyLance showing return types but not showing return variables names

### ISSUE THREAD

**Issue by DeusAres** [microsoft/pylance-release#1173]
How do you set pylance to show variable names of returns when calling a function instead of types?

**Comment by bschnurr** [comment]
Can you provide a code example of what you are trying to achieve? I'm not quite sure what you mean by variable names. Thank you.

**Comment by DeusAres** [comment]
![image](https://user-images.githubusercontent.com/60852205/115453860-63166f80-a220-11eb-8ab8-fa41382320a1.png)

As you can see, the hovering box shows the function return as `->(Any | Literal[0])`, which I refer as return types
While instead I was expecting to see the names of the variables that the function returns 
Example: `-> foo, bar, zzz`
(Return index in the image is showed because of docstring, a patch to solve the problem)

**Comment by jakebailey** [comment]
The variable names inside of a function are an implementation detail and not a part of any API contract. They're not the same as parameter names (which do matter). If I change the variable name inside a function, it doesn't affect its behavior. Only the type matters for the return.

What's the reasoning for wanting to see the variable names? Is there some other analysis or editor that does this?

**Comment by DeusAres** [comment]
Maybe for inexperience the organizations of my functions are made in order to return multiple variables, that could be the same of the same type. When unpacking, I don't remember the order of returns, that's the main reason.
Possibly wrong, I'm not an experienced programmer

**Comment by jakebailey** [comment]
I'm not sure we're going to do this, I'm afraid. The names of variables that are returned from functions aren't a part of its API (and don't have an analogue in Python's type system), and it's certainly possible to return things from functions without using variables at all.

I would suggest using a docstring to document things like this instead; that's how most libraries choose to describe their returns when they are returning a tuple.

A `namedtuple` may do something similar to what you're describing, as it allows you to name the items in a tuple. I'll also say that there is something similar in TypeScript:

```ts
function foo(): [xyz: number, abc: string] {
    return [1234, "Hello, World!"];
}
```

But, this sort of syntax doesn't exist in Python; I know that there are improvements in progress for callables, so maybe something similar could be proposed for tuples to aid in making documenting the intent of returned tuples.
