### ISSUE TITLE
Type alias not always correctly recognised as such

### ISSUE THREAD

**Issue by smeznaric** [microsoft/pylance-release#1181]
## Environment data

-   Language Server version: 2021.4.2
-   OS and version: CentOS Linux release 7.5.1804
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.3

## Code Snippet / Additional information

```python
import pandas as pd
from typing import Union
import datetime

DateTime = Union[datetime.date, datetime.datetime, pd.Timestamp]

def some_function(d: DateTime) -> int:
    return 3

def some_function_2(d: Union[datetime.date, datetime.datetime, pd.Timestamp]) -> int:
    return 4
```

To see the behaviour you may need to place your cursor at the end of `import datetime` line and press ENTER twice then backspace twice. Seems odd. 

## Expected behaviour

No errors.

## Actual behaviour

The `DateTime` type alias is underlined in line `def some_function(d: DateTime) -> int:`  saying "Illegal type annotation: variable not allowed unless it is a type alias"

**Comment by erictraut** [comment]
Thanks for the bug report. This bug looks similar to (and could possibly be the same underlying bug) as this one: https://github.com/microsoft/pylance-release/issues/1180. I'll look into it in more detail.

**Comment by erictraut** [comment]
I'm pretty sure I've fixed this bug in the pyright source base. 

@jakebailey, we should double check that the problem no longer appears in pylance when you pull the code over and integrate next time.

**Comment by jakebailey** [comment]
This one does appear to be fixed. I've copied the above and did the "enter enter backspace backspace" (and other changes) and couldn't make it appear.

**Comment by jaraqueffdc** [comment]
I just wanted to add my use case in case it helps as well. I noticed that some times type aliases are not recognized based on the surrounding code. For example, this code marks the data parameter in the method as wrongly typed

```
Storable = Union[ExtractChunk, ReplicationJob, MetadataObject, Snapshot]
StorableIdentifier = Union[
    ChunkIdentifier,
    JobIdentifier,
    MetadataObjectIdentifier,
    SnapshotIdentifier,
]
ChunkLike = Union[str, Dict[str, Any], pd.DataFrame]


def _preprocess_json_chunk(data: ChunkLike) -> str:
  ...
```
It says that `ChunkLike` is not a valid with the message `Variable not allowed unless it is a type annotation`.

However, when I leave a blank line before it there is no complain

```
Storable = Union[ExtractChunk, ReplicationJob, MetadataObject, Snapshot]
StorableIdentifier = Union[
    ChunkIdentifier,
    JobIdentifier,
    MetadataObjectIdentifier,
    SnapshotIdentifier,
]

ChunkLike = Union[str, Dict[str, Any], pd.DataFrame]


def _preprocess_json_chunk(data: ChunkLike) -> str:
  ...
```

I have played with the previous type aliases seeing if different format, alignment or multilines have any impact but it seems that the only thing that makes a difference is whether we use the blank line or not.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.4.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202143-29-april-2021

**Comment by vineetrajasekhar** [comment]
This is a fairly clean workaround for using Pydantic's `con*` types - as [suggested](https://github.com/pydantic/pydantic/issues/5006#issuecomment-1416863679) by Pydantic's maintainer Samuel Colvin. 

This attracts a Pylance error...
```python
import pydantic

class MyClass(pydantic.BaseModel):
    myvar: pydantic.confloat(gt=0, lt=1)

x = MyClass(myvar=0.1)
``` 
... while this does not:

```python
from typing import Annotated

import pydantic

class MyClass(pydantic.BaseModel):
    myvar: Annotated[float, pydantic.confloat(gt=0, lt=1)]

x = MyClass(myvar=0.1)
```

**Comment by valery-iwanofu** [comment]
What can i do if my variale already an `Annotated`?
```python
from functools import cached_property
from typing import Annotated, Generic, TypeVar


C = TypeVar('C')


class MyField(Generic[C]):
    def __init__(self, type_: type[C]):
        self.type_ = type_

    @cached_property
    def field(self):
        type_ = self.type_ # workaround for "TypeVar "Self@MyField[C@MyField]" has no member "type_"
        return Annotated[type_, 'field']

    @cached_property
    def path(self):
        type_ = self.type_
        return Annotated[type_, 'path']


name_field = MyField(str)


class MyModel:
    name: name_field.field # Illegal type annotation: variable not allowed unless it is a type alias


def my_route(name: name_field.path): # Illegal type annotation: variable not allowed unless it is a type alias
    ...
```

**Comment by debonte** [comment]
@valery-iwanofu, it's not clear to me what you are trying to accomplish. You may want to create a [discussion](https://github.com/microsoft/pylance-release/discussions/categories/general) post about this, but there are a couple things that stand out to me:

1. The following line is not creating a type alias, but rather an instance of `MyField`.
```python
name_field = MyField(str)
```

 I'm assuming you meant to do the following:

```python
name_field = MyField[str]
```

And if that's the case, the `type_` parameter in your `__init__` method is unnecessary since within `MyField` you could use `C` in place of `self.type_`.

2. Type annotations need to be static. Using the return value of a function as a type annotation isn't going to work.

> For now i just moved of `name_field` definition in separate file and it works as i excepted, but maybe there is a more comfortable solution

This shouldn't have made a difference. You may have been hitting the bug described [here](https://github.com/microsoft/pyright/issues/4646#issuecomment-1434087168).
