### ISSUE TITLE
Syntax Highlighting not for working for some scopes

### ISSUE THREAD

**Issue by alimdi** [microsoft/pylance-release#1183]
**Environment data**

Language Server version: v2021.4.2
OS and vscode version: Windows 1.55.2
Python version (& distribution if applicable, e.g. Anaconda): 3.9.4

**Expected behaviour**

Colorization of the whole i-then-else block
Colorization of quoted string

**Actual behaviour**

Line 97 'StartFormatBodyTime' and 'datetime' not colorized
Line 99 'if' and 'boundary' not colorized
Line 106 __name__ not colorized

![image](https://user-images.githubusercontent.com/42753067/115845028-be16b500-a420-11eb-8f19-e6e29f3d6d5f.png)

**Comment by jakebailey** [comment]
To confirm, are you using semantic highlighting? If you reload the window, does the highlighting work as expected?

Can you provide a full code sample that isn't in a screenshot? We can't copy and paste out of an image, and with semantic highlighting, the actual code being used can matter (though string literals not being highlighted is suspect).

**Comment by alimdi** [comment]
Hi,

I guess semantic highlighting is enabled (any way to check that out?). Reloading the window doesn't change a thing.
Below the the incriminated code :

```
def FormatBody(CType: str, BytesBody: bytes) -> list:
    Attachments = {}
    DictBody = {}

    DictBody['StartFormatBodyTime'] = GenTimeStamp()['datetime']
    ContentType, pdict = cgi.parse_header(CType)
    if 'boundary' in pdict.keys():
        pdict['boundary'] = bytes(pdict['boundary'], "utf-8")
    if ContentType == 'multipart/form-data':
        EncDictBody = cgi.parse_multipart(BytesIO(BytesBody), pdict)
        for key in EncDictBody:
            if re.search(r"^attachment\d+$", key):
                Attachments[key] = EncDictBody[key][0]
                DictBody[key] = type(Attachments[key]).__name__
            elif re.search(r"^attachment\-info$", key):
                DictBody[key] = json.loads(EncDictBody[key][0])
            elif re.search(r"^headers$", key):
                my_header = {}
                for x in (EncDictBody[key][0]).strip().split("\n"):
                    x = x.split(":", 1)
                    my_header[x[0].strip()] = x[1].strip()
                DictBody[key] = my_header
            else:
                DictBody[key] = EncDictBody[key][0]
    DictBody['EndFormatBodyTime'] = GenTimeStamp()['datetime']
    DictBody['FormatBodyTime'] = str(DictBody['EndFormatBodyTime'] - DictBody['StartFormatBodyTime'])
    return [DictBody, Attachments]
```

By the way, scope inspector shows that the whole line isn't parsed correctly.

![image](https://user-images.githubusercontent.com/42753067/116047319-3d4ff700-a674-11eb-9c81-dc4995f78dc4.png)

**Comment by jakebailey** [comment]
Can you show that same tooltip but on a symbol that is working as intended, like `bytes` or `list`?

That piece of code isn't entirely complete (some symbols don't resolve), but I don't see this behavior when I paste into a fresh file.

**Comment by alimdi** [comment]
Sure, find it below. Pasting that piece of code in a fresh windows produces the same behavior. I really can't get it.

![image](https://user-images.githubusercontent.com/42753067/116197695-55d41600-a735-11eb-85fa-f4b4f94f2260.png)

**Comment by jakebailey** [comment]
That's very strange. Is it possible that those spaces aren't regular ASCII spaces but are another character that looks like a space? The code runs, correct?

If you copy and paste your code snippet above back into the file over top, does it work?

**Comment by jakebailey** [comment]
It's been a month since I asked the above without a response, so I'm going to close this.

If you're still experiencing this and can answer some more questions, we can reopen this. I'd also be interested in verifying that you don't have any stray extra Python extensions installed (as they may also override language settings and cause oddities like that textmake token mismatch).
