### ISSUE TITLE
Pylance not recognizing isinstance specification with TypeVar with Union bounds.

### ISSUE THREAD

**Issue by lossyrob** [microsoft/pylance-release#1189]
## Environment data

-   Language Server version: 2021.4.2 (21 April 2021)
-   OS and version: wsl 2 on Windows 10, Ubuntu 20
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 w/ venv

## Expected behaviour

In this snippet:

```python
from typing import Generic, Union, TypeVar

class Foo:
    pass

class Bar:
    pass

T = TypeVar('T', contravariant=True, bound=Union[Foo, Bar])

class Extension(Generic[T]):
    pass

class FooExtension(Extension[Foo]):
    def __init__(self, foo: Foo) -> None:
        pass

class BarExtension(Extension[Bar]):
    def __init__(self, bar: Bar) -> None:
        pass

def baz(foobar: T) -> Extension[T]:
    if isinstance(foobar, Foo):
        return FooExtension(foobar)
    elif isinstance(foobar, Bar):
        return BarExtension(foobar)
    else:
        raise Exception()
```

Pylance is currently reporting an error on `return FooExtension(foobar)` as

```
Argument of type "T@baz" cannot be assigned to parameter "foo" of type "Foo" in function "__init__"
  Type "Foo | Bar" cannot be assigned to type "Foo"
    "Bar" is incompatible with "Foo"
```

with a similar error underlining foobar in `return BarExtension(foobar)`.

I would expect the `isinstance` check to scope the type of `foobar` to either `Foo` or `Bar` depending on the check. If I remove the `bounds` of the TypeVar this seems to work. 

If I move the parameter to use the Union directly, this also reports no error:

```python
def baz2(foobar: Union[Foo, Bar]) -> Extension[T]:
    if isinstance(foobar, Foo):
        return FooExtension(foobar)
    elif isinstance(foobar, Bar):
        return BarExtension(foobar)
    else:
        raise Exception()
```

## Actual behaviour

The information from the `isinstance` check doesn't seem to be used when the TypeVar has a bounds.

**Comment by Azureblade3808** [comment]
I don't think a `Union` can be used as a `bound` value.

Quoted from PEP484 (https://www.python.org/dev/peps/pep-0484/#type-variables-with-an-upper-bound):
> A type variable may specify an upper bound using bound=<type> (note: <type> itself cannot be parameterized by type variables).

To my understanding, it means the value of `bound` needs to be a real type. In other words, calling `isinstance(x, bound)` needs to be valid. So it needs to be either a class or a runtime-checkable protocol.

In your example, I would rewrite the definition of `T` into
```python
T = TypeVar("T", Foo, Bar, contravariant=True)
```
And then everything works.

**Comment by erictraut** [comment]
@Azureblad3808 is correct. You should use a constrained type variable (one that constrains the type variable to a specified list of types) rather than a bound type variable that uses a union type.

**Comment by lossyrob** [comment]
Got it, thank you!
