### ISSUE TITLE
Type error not caught: returning container with wrong type

### ISSUE THREAD

**Issue by jli** [microsoft/pylance-release#1195]
<h3> Environment data </h3>

-   Language Server version: 2021.4.2
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.2
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Pylance should infer the type of generic containers and warn when that type doesn't match a function's return type.

<h3> Actual behaviour </h3>

Pylance doesn't warn unless I add an explicit type hint.

<h3> Code Snippet / Additional information </h3>

```python
from typing import Dict, List

# Pylance correctly finds the error.
def return_wrong_list_type__with_hint() -> List[int]:
    int_list: List[int] = []
    # Argument of type "Literal['string']" cannot be assigned to parameter "__object" of type "int" in function "append"
    int_list.append('string')
    return int_list

# Pylance misses the type error (same function as above, just without hint)
def return_wrong_list_type__no_hint() -> List[int]:
    int_list = []
    int_list.append('string')
    return int_list

# Pylance misses the type error (with dict instead of list)
def return_wrong_dict_type__no_hint() -> Dict[int, int]:
    int_dict = {}
    int_dict['string'] = 'another string'
    return int_dict
```

 mypy correctly finds all 3 errors:

```shell
$ mypy --version
mypy 0.812

$ mypy pylance_false_positive.py
pylance_false_positive.py:7: error: Argument 1 to "append" of "list" has incompatible type "str"; expected "int"
pylance_false_positive.py:14: error: Incompatible return value type (got "List[str]", expected "List[int]")
pylance_false_positive.py:20: error: Incompatible return value type (got "Dict[str, str]", expected "Dict[int, int]")
Found 3 errors in 1 file (checked 1 source file)
```

**Comment by erictraut** [comment]
In your second example above, you haven't provided a type annotation for `int_list`, so pyright (the type checker that powers pylance) needs to infer its type. For details about how pyright infers the types of list and dictionary expressions, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#list-expressions). In this particular case, it infers the type to be `List[Unknown]`. "Unknown" is a special form of `Any` that pyright uses internally to track types that could not be inferred.

If you are interested in stricter type checking to catch problems like this, you can enable additional type checking rules that are off by default. To enable all such rules, change `typeCheckingMode` to `strict`. These additional rules may result in some false positive errors, so we leave them disabled in `basic` type checking mode. 

To see the effects of `strict` mode in your sample above, you can enable this mode for only this file by pasting the following line at the top:
```python
# pyright: strict
```

Once you do this, pyright reports all of the issues you would like it to find.

**Comment by jli** [comment]
Gotcha, thanks!
