### ISSUE TITLE
Unable to navigate to some definitions in python.

### ISSUE THREAD

**Issue by tej1996nitrr** [microsoft/pylance-release#1196]
Pylance Language Server version: v2021.4.2
OS and version: MacOs Catalina 10.15.7
Python version: 3.8.3 Anaconda

## Expected behaviour
Should navigate to the definition.

## Actual behaviour
Code navigation doesn't work sometimes when I try to go to the definition. `Right click+ Go to Definition`  says  `No definition found` , `Ctrl+click`  displays `Any`.
Tried in both vs code and vs code insiders version 1.56.0-insider

## Code Snippets
Line 22: on `Right click + Go to Definition` on `set`:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/27068830/116314420-b82c2580-a7cc-11eb-87dc-b6ed15b5ec37.png">

Line 22: on `ctrl+click` on `set` :

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/27068830/116314457-c24e2400-a7cc-11eb-90be-76e9d1b2c79d.png">

**Comment by judej** [comment]
Thanks for the report. Could you please hover over `settings` and see what type is reported? Also, could you please send the code as opposed to a screenshot so that we can debug quicker?

thanks

**Comment by tej1996nitrr** [comment]
Hovering on `SETTINGS` give type: `(constant) SETTINGS: dict[str, dict[str, Any]]`. And hers's the code:

```
class Threshold(object):
    def __init__(self, value):
        self.value = value

    def set(self, value):
        if value > 20:
            return True
        return False


class Something(object):
    SETTINGS = {
        'metrics': {
            'threshold': Threshold(10),
            'status': 'red'
        }
    }

    @classmethod
    def set_threshold(cls, value):
        # return cls.SETTINGS['metrics']['threshold'].set(value)
        return cls.SETTINGS.get('metrics').get('threshold').set(value)

s = Something()
s.set_threshold(30)
```

**Comment by jakebailey** [comment]
Yeah, the problem is that the `dict` type can't represent what the type of each of its members are by key (at least not in Python's type system), so we need to determine a common type for all keys, and in this case are picking `Any` as the type of that nested dictionary. My guess is that it would "work" if you removed "status".

Feasibly, you could try and use a `TypedDict` if you needed to use dictionaries here, but what is the reasoning for using a dictionary for this as opposed to plain class members (which can be typed)? Is this a cut down version of some real code?

**Comment by tej1996nitrr** [comment]
Thanks Jake for the info. Yes, it works when I remove `status: red`. However, this snippet is just a simplified version of a larger code. I noticed one more thing, when I switch  Language Server to Jedi, it is able to navigate to `set` with or without `status: red`. Although Jedi seems to be a bit slower for me in my original code repo.

**Comment by erictraut** [comment]
If you are interested in how pyright (the type checker that underlies pylance) infers the types of dictionary expressions, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#dictionary-expressions).

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
