### ISSUE TITLE
Repo title is confusing

### ISSUE THREAD

**Issue by leebrian** [microsoft/pylance-release#12]
The title, **Pylance-Release** seems confusing to me as it is just release notes and there is no software here. 

Please rename to **pylance-release-notes** or something to be consistent with documentation projects. 

Or even better, release the software and source and keep the name!

**Comment by gramster** [comment]
This repo is to capture bug reports, etc, not just for release notes.

**Comment by leebrian** [comment]
Thanks, that makes sense, but still unusual. Maybe call it tracker or feedback or something? Not the end of the world, but typically projects are named this for dev of project and extra projects have something to designate how it is different.

**Comment by savannahostrowski** [comment]
Thanks for the feedback. We’ve updated the readme to clarify that this is for issues and documentation with the pylance release.
