### ISSUE TITLE
No error reported when pyrightconfig.json can't be parsed

### ISSUE THREAD

**Issue by russelldavis** [microsoft/pylance-release#120]
To reproduce, just add a trailing comma to the last item in the file (an easy mistake many will make).

## Expected behaviour
An error should show up in the vscode Problems panel. Also, the error should show up in the logs at logLevel "error".

## Actual behaviour
No errors are reported. An error only shows up in the logs if you change the value of python.analysis.logLevel to "Info" or greater severity.

## Environment data
-   Language Server version: Pylance 2020.7.1
-   OS and version: macOS 10.15.5
-   Python version: 3.8

**Comment by erictraut** [comment]
Thanks for the suggestion.

I agree that this should be logged as an error, not at the "info" level.

It will already appear in the Problems panel if you open the file. The JSON language server will report it as a problem. I don't think that Pylance should report a diagnostic separately. That would be inconsistent with every other language server that I'm aware of. For example, the TypeScript LS doesn't report a diagnostic if the tsconfig.json file has parse issues.

**Comment by russelldavis** [comment]
Ah, that's reasonable. I didn't catch it because I edited the json file in a different editor. I wish there was a way to tell vscode to run diagnostics on all files in the project, including json, even if they aren't open. But that's an issue for vscode, not pylance.

**Comment by erictraut** [comment]
I've reviewed all logging done by the Pyright server and updated the log levels for numerous log messages, including the "can't parse config file" message. This will be included in the next version of Pylance/Pyright.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202073-21-july-2020
