### ISSUE TITLE
The Intellisense becomes slow when coding within parenthesis

### ISSUE THREAD

**Issue by alanyoungCN** [microsoft/pylance-release#1204]
<h3> Environment data </h3>

-   Language Server version: 2021.4.3-pre.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): Anaconda Python 3.8.8
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Intellisense quickly when I code within parenthesis, as fast as when I code outside a function's parameter list.

<h3> Actual behaviour </h3>

The Intellisense becomes very slow when I am typing in a parenthesis inside a function's parameter list. But when I code outside the parenthesis, the Intellisense becomes OK. It's strange.

<h3> Code Snippet / Additional information </h3>

![Untitled](https://user-images.githubusercontent.com/32586930/116536475-8b385980-a917-11eb-9323-38d914810d87.gif)

**Comment by alanyoungCN** [comment]
So is it possible that the pylance need to find the outer function's parameter infomation and need to intellisense my input words at the same time, which makes pylance slow? Or just because my Mac is short of memory?

**Comment by erictraut** [comment]
What you're referring to as "IntelliSense" is actually several different types of feedback provided by a language server like pylance. One form of feedback is referred to as "completion suggestions". That's what you see popping up when you start typing an identifier or when you type "." after an identifier. Another form of feedback is referred to as "signature help", which displays function docstrings and information about parameters in a call expression. That's what you see when you start typing within parentheses. The amount of analysis required to present completion suggestions vs. signature help can differ. That probably explains what's happening here, but more investigation is needed to confirm.

**Comment by alanyoungCN** [comment]
Thanks for explaining. I found that when I rebooted my Mac, it went a little well. But slowness is still here.

**Comment by heejaechang** [comment]
we have made many perf improvement since this. is this still repo?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
