### ISSUE TITLE
Pylance report issue only works on python files (not notebooks).

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#1207]

**Comment by bschnurr** [comment]
any ideas why vscode's `editorLangId` isn't set when using notebooks?

**Comment by rchiodo** [comment]
Probably because there are multiples. A notebook doesn't have to be a single language

**Comment by rchiodo** [comment]
I assume you're talking about in a 'when' clause?

**Comment by bschnurr** [comment]
yes.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202150-5-may-2021
