### ISSUE TITLE
staticmethod builtin wrapper hides function signatures

### ISSUE THREAD

**Issue by bschnurr** [microsoft/pylance-release#1210]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour
correct function signature
to_wei(number: Union[int, float, str, decimal.Decimal], unit: str) -> int:

## Actual behaviour

![image](https://user-images.githubusercontent.com/1946977/116620858-41d81200-a8f7-11eb-82e0-57bce9143587.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
from web3 import Web3

Web3.toWei(1, 'ether')
```

**Comment by bschnurr** [comment]
this could be more related to the way they are using staticmethod.. i haven't seen it used like this in any other examples.  the usage i've see is staticmethod(classname.methodname)  or as a fixture.

**Comment by savannahostrowski** [comment]
Fixed upstream ethereum/web3.py#1979
