### ISSUE TITLE
Support for Pydantic's constructor parameters

### ISSUE THREAD

**Issue by jaraqueffdc** [microsoft/pylance-release#1214]
Hi!

I see this question has not been asked before (or I cannot find it) and given how Pydantic works I imagine there is not much you as pylance devs can do but I wanted to ask if you know about any effort of developing at least an extension that would support intellisense with Pydantic's parameters in the class constructor. In Pycharm I know there is a plugin that shows the parameters in the constructor when using a BaseModel from Pydantic but I cannot find something similar in VSCode.

Are you aware of any ongoing work in this front? 

Thanks!

**Comment by erictraut** [comment]
Please check out [this discussion in the pyright repo](https://github.com/microsoft/pyright/issues/637). Pyright is the open-source type checker that powers pylance.

**Comment by jaraqueffdc** [comment]
Thanks a lot @erictraut ! Looks that there is ongoing work there. As I see you are working on a way of allowing third party packages to support this code completion with pyright so I imagine that it will ultimately depend on a) when this is part of pyright (I understand this is still being tested) and b) when will the third party packages (pydantic in this case) use this as part of their code base. I am right assuming this?

I will try to stay posted and I will probably give it a try in my local copy although we cannot use this as a team setup until it is fully functional.

Thanks a lot!

**Comment by erictraut** [comment]
That's correct. We have been working with the maintainers of libraries like pydantic and attrs. 

If you would like to give this a try, you can apply the necessary changes to your local copy of pydantic by following [these instructions](https://github.com/microsoft/pyright/blob/master/specs/dataclass_transforms.md#applying-to-pydantic).

And if you have feedback on the proposed solution, please post it in [this discussion](https://github.com/microsoft/pyright/discussions/1782).

**Comment by jaraqueffdc** [comment]
I will certainly give it a try and if I have any comments I will let you know. Thanks a lot!
