### ISSUE TITLE
Syntax highlighting for ``match`` and ``case``

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1215]
It would be nice if syntax highlighting for `match` and `case` could be added.

![Screen Shot 2021-04-30 at 17 04 04](https://user-images.githubusercontent.com/30130371/116714575-34de2000-a9d6-11eb-90ed-4005f4ece357.png)

```py
def http_error(status: int):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
```

**Comment by jakebailey** [comment]
Thanks for the report; at the moment we rely on the TextMate profile built into VS Code to display these kinds of keywords. I'm surprised they haven't been added there, but I do think we should be emitting keywords as tokens in the semantic highlighter as well.

**Comment by cdce8p** [comment]
After searching a bit more, I found these two existing issues:
https://github.com/microsoft/vscode/issues/120734
https://github.com/MagicStack/MagicPython/issues/235

I've also opened a PR https://github.com/MagicStack/MagicPython/pull/237 to recognize `match` and `case` as keywords, at least in a `match` statement.

**Comment by jakebailey** [comment]
In the meantime while we wait for VS Code and such to pull in those changes, I've modified our semantic tokenizer to output `match` and `case` as keyword tokens:

![matchcase](https://user-images.githubusercontent.com/5341706/117192305-65d3a180-ad96-11eb-9789-bb436f303568.gif)

**Comment by cdce8p** [comment]
@jakebailey That's great! Thanks 🚀

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202150-5-may-2021

**Comment by Jaakkonen** [comment]
For people using `pyright` extension for development of it I think there's no other workaround than using a `MagicPython` extension built from the PR branch (rebased or not).

**Comment by scarf005** [comment]
default themes and github themes support `match` `case` syntax, however majority of other themes does not support them out of the box.

running `Inspect editor tokens and scopes` shows result like this:
![_01](https://user-images.githubusercontent.com/54838975/185725987-57b1d9c1-2b65-4636-848e-9c9057d2a59f.png "alma dimmed sakura")

![_02](https://user-images.githubusercontent.com/54838975/185725993-79ef5387-1fba-4137-89f8-df72f28edde5.png "github dark")

could there be any way to overwrite custom themes to support `match` `case`?

**Comment by debonte** [comment]
@scarf005, this issue has been closed for a long time. Please open a new issue for your suggestion.

**Comment by scarf005** [comment]
> @scarf005, this issue has been closed for a long time. Please open a new issue for your suggestion.

alright, referenced in new issue.
