### ISSUE TITLE
How to exclude paths for pylance?

### ISSUE THREAD

**Issue by haotian-liu** [microsoft/pylance-release#1220]
In my project, there is a folder (symbolic link) that contains a large dataset that my PyTorch module will train on. And Pylance seems spending a lot of the time loading it, and before it is fully loaded, I cannot use the intellisense feature (e.g. go to definition, auto completion, etc.)

I have tried a few things to exclude the path using `files.exclude`, `files.watcher_exclude`, and `search.exclude`. But it does not solve this slow loading issue.

One thing I did find to work (which also helped me confirm that the large dataset folder is the cause) is that when I remove the symbolic link for the dataset in the project, the intellisense can be used almost immediately after the project is opened.

Not sure if what I am doing is correct, and any suggestions / docs are appreciated. Thank you!

**Comment by erictraut** [comment]
Pylance is built on top of an open-source type checker called pyright. Pyright offers some configuration options that are not currently exposed in VS Code settings. You can create a pyrightconfig.json configuration file and specify the set of subdirectories that you want to exclude using the "exclude" setting. For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md). Here's an [example pyrightconfig.json](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#sample-config-file).

**Comment by haotian-liu** [comment]
Thank you, this is really helpful. I tried to add the directory to the `pyrightconfig.json` and it works. One additional concern is that what is the extension rule of the default json config?

For example, if I create a config like this, will it:

1. lose default values for other entries (e.g. `include`, `ignore`, etc.) used for Pylance;
2. for list entries like `exclude: [dir1, dir2]`, will the default exclude directories be still in the final exclusion list? E.g. in the following case, will `**/.git` still be excluded?

```json
{
  "exclude": [
    "**/data"
  ]
}
```

Thank you!

**Comment by yanyongyu** [comment]
Really helpful for me! I tried `python.linting.ignorePatterns` but not works.

It works for me to add `exclude` in `[tool.pyright]` section in `pyproject.toml`:

```toml
# pyproject.toml

[tool.pyright]
exclude = [".vscode/*.py", "**/site-packages/**/*.py"]
```
