### ISSUE TITLE
Type narrowing with ``isinstance`` and ``issubclass`` in match statement

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1221]
<h3> Environment data </h3>

-   Language Server version: 2021.4.4-pre.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.0a7
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

An `isinstance` or `issubclass` call in a match statement should narrow the type just like the same call in an `if` statement.

<h3> Actual behaviour </h3>

![Screen Shot 2021-05-02 at 20 56 35](https://user-images.githubusercontent.com/30130371/116824142-e4f38a80-ab88-11eb-8a46-5a1a18a24496.png)

<h3> Logs </h3>
--

<h3> Code Snippet / Additional information </h3>

```python
class Custom:
    pass

class Derived(Custom):
    pass

def func(cls: Custom) -> Derived:
    var: Derived
    match isinstance(cls, Derived):
        case True:
            var = cls
        case _:
            var = Derived()

    return var
```

**Comment by erictraut** [comment]
This looks like an incredibly contorted use of pattern matching when this would be much more straightforward, faster to run, and easier to read:

```python
if isinstance(cls, Derived):
    var = cls
else:
    var = Derived()
```

I suppose one could take any simple conditional code flow statement with a boolean test and contort it into a pattern matching statement that matches on True or False, but why?

```python
match value == 1:
    case True:
        print("value is 1!)
    case _:
       print("value is not 1!")
```

This is quite different from type narrowing used for other conditional statements because it requires an understanding of of subject type narrowing and pattern matching. It's theoretically possible to implement this, but it would be a lot of work, and I'm far from convinced this will be generally useful. I would need to have a lot of additional evidence from many more users before I could justify that additional development and code complexity.

**Comment by cdce8p** [comment]
True, for just one boolean check I wouldn't use pattern matching. That was only the example here. Originally it looked more like this:
```py
def func(obj: type[Custom], var: bool, arg: int) -> Derived:
    default_bar: Derived
    list_bar: list[Derived] = []
    default_foo: Custom
    list_foo: list[Custom] = []

    match issubclass(obj, Derived), var:
        case True, True:
            default_bar = obj(arg)
        case True, False:
            list_bar.append(obj(arg))
        case False, True:
            default_foo = obj(arg)
        case False, False:
            list_foo.append(obj(arg))
```
Of course, even that could be expressed by an `if` statement, but this was just a first test for what pattern matching can do.

**Comment by erictraut** [comment]
This case would be even more complicated for type narrowing because it involves multiple subexpressions within a tuple. Pyright doesn't perform type narrowing in complex cases like this, nor does any other Python type checker, to my knowledge.

```python
if (issubclass(obj, Derived), var) == (True, True):
    ...
```

**Comment by cdce8p** [comment]
I might be missing something, but isn't that the same as:
```py
def func3(obj: type[Custom], var: bool):
    default_bar: Derived
    list_bar: list[Derived] = []
    default_foo: Custom
    list_foo: list[Custom] = []

    if issubclass(obj, Derived) and var:
        default_bar = obj()
    elif issubclass(obj, Derived) and not var:
        list_bar.append(obj())
    elif not issubclass(obj, Derived) and var:
        default_foo = obj()
    elif not issubclass(obj, Derived) and not var:
        list_foo.append(obj())
```
That does work with Pyright.

**Comment by erictraut** [comment]
That's not the same. The match statement in your sample above is equivalent to:

```python
def func(obj: type[Custom], var: bool, arg: int) -> Derived:
    default_bar: Derived
    list_bar: list[Derived] = []
    default_foo: Custom
    list_foo: list[Custom] = []

    if (issubclass(obj, Derived), var) == (True, True):
        default_bar = obj(arg)
    elif (issubclass(obj, Derived), var) == (True, False):
        list_bar.append(obj(arg))
    elif (issubclass(obj, Derived), var) == (False, True):
        default_foo = obj(arg)
    elif (issubclass(obj, Derived), var) == (False, False):
        list_foo.append(obj(arg))
```

**Comment by bschnurr** [comment]
Closing issue, if you have any further questions let us know.
