### ISSUE TITLE
False-positive possibly unbound variable with explicit True / False check

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1222]
## Environment data

-   Language Server version: 2021.4.4-pre.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.0a7
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

## Expected behaviour

An explicit `False` check should be handled like `else`. Especially with pattern matching, it's not always possible to default to `else`.

## Actual behaviour

![Screen Shot 2021-05-02 at 22 20 47](https://user-images.githubusercontent.com/30130371/116826523-aa8fea80-ab94-11eb-8a41-2a464656cd40.png)

## Logs
--

## Code Snippet / Additional information

_simplified example_

```python
from typing import Any

class Custom:
    pass

class Derived(Custom):
    pass


def func(cls: Custom) -> Derived:
    var: Any
    if isinstance(cls, Derived):
        var = cls
    elif not isinstance(cls, Derived):
        var = Derived()
    return var  # possibly unbound


def func2(cls: Custom) -> Derived:
    var: Any
    match isinstance(cls, Derived):
        case True:
            var = cls
        case False:
            var = Derived()
    return var  # possibly unbound
```

**Comment by erictraut** [comment]
These are very difficult and costly determinations for a static type checker to make, so we're unlikely to implement them unless we receive strong signal from many users that they are generally desired.

As an easy workaround, you can initialize your variable outside of the conditional/match statement or ensure that you always have a code path that executes (e.g. use an `else` or a wildcard pattern):

```python

def func(cls: Custom) -> Derived:
    var: Any
    if isinstance(cls, Derived):
        var = cls
    else:
        var = Derived()
    return var

def func2(cls: Custom) -> Derived:
    var: Any
    match isinstance(cls, Derived):
        case True:
            var = cls
        case _:
            var = Derived()
    return var
```
