### ISSUE TITLE
lambda properties should identify the `self` parameter as an instance of their containing class

### ISSUE THREAD

**Issue by benblo** [microsoft/pylance-release#1231]
## Environment data

-   Language Server version: 2021.4.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

## Expected behaviour

In a member property initialized with `property(lambda self: "foo")`, the `self` parameter should be identified as an instance of the containing class.
Same goes for lambda-initialized methods.

## Actual behaviour

The `self` parameter is untyped (`Any`).

## Code Snippet / Additional information

Consider the following code:
```python
class Test(object):
	property_from_lambda = property(lambda self: self)
	method_from_lambda = lambda self: self
	def classic_method(self): return self

test = Test()
print(test.property_from_lambda)
print(test.method_from_lambda())
print(test.classic_method())
```

Both `property_from_lambda` and `method_from_lambda` are legal instance-bound members, as the test prints prove.
However, in both cases the `self` parameter is not recognized as an instance of Test:
![image](https://user-images.githubusercontent.com/574187/117113449-c4931e00-ad8a-11eb-86ed-1f86dc78861c.png)
![image](https://user-images.githubusercontent.com/574187/117113552-e8eefa80-ad8a-11eb-9edb-1e2f05ce902b.png)

By comparison, in a "normal" method the `self` parameter is correctly identified as an instance of `Test`:
![image](https://user-images.githubusercontent.com/574187/117114424-22743580-ad8c-11eb-82de-ddc126c89492.png)

---
In the tooltip/autocomplete menu, `method_from_lambda` is identified as a variable; this is more debatable, but IMO it would be more relevant to identify it as a method (tooltip, icon, syntax highlighting etc):
![image](https://user-images.githubusercontent.com/574187/117114721-7e3ebe80-ad8c-11eb-8af6-57aaab2b8282.png)

By comparison, this is `classic_method`:
![image](https://user-images.githubusercontent.com/574187/117115074-e55c7300-ad8c-11eb-9741-49f1ec38b4f5.png)

**Comment by erictraut** [comment]
Please refer to my response in #1230.
