### ISSUE TITLE
Can't jump to definition due to lager size of project

### ISSUE THREAD

**Issue by zheyuanWang** [microsoft/pylance-release#1237]
## Environment data

-   Language Server version: 2021.5.0
-   OS and version: Ubuntu 18.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9 , 64 bit

## Expected behaviour

jump to def with ctrl and left click

## Actual behaviour

didn't jump

## Logs

```
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Pylance language server.
Python interpreter path: /usr/bin/python3
> conda --version
```
Hi, 

as my project grows bigger, I can't use ctrl + left click(or F12) to *jump to definition* in Vscode.

I have tested with a new workspace and a single python file:
```python
def pp():
    print('test')



pp()
```
The jump to definition feature works well. 
Also, I have tested it by logging into a remote server with larger memory, the feature works well, too.

On my local machine, I have 15.6 GB memory in total. With the [bigger project]() opened, there is still 9 GB memory free. 

Maybe it's not directly related to memory but the experiments shows that *jump to definition*:
```
small project @ local machine:                ok
big   project @ local machine:                failed
big   project @ remote server(larger memory): ok
```
ps. the project could run well on both machine, so I don't think there is problem in the python environment. 

---
I'm using pylance, which is set in setting.json:
```
    "python.languageServer": "Pylance",
    "python.jediEnabled": false,
```
I have excluded all the uncessary folder in setting.json to reduce the project size:
```
"files.watcherExclude": {
    "**/build/**": true,
    "**/data/**": true,
    "**/output/**": true,
    "**/pcdet.egg-info/**": true,
    },
```
But still, when I click with ctrl, vscode is loading forever.

How can I get the *jump to definition* feature work?

ps. the extension "Error Lens" doesn't work in the mean time, I guess there is a fundamental error for both of them

**Comment by judej** [comment]
Thanks for the report. Is the bigger project that you reference in your report available for us to use to test and repro?

**Comment by bschnurr** [comment]
Closing for now. If you have any addition logs or repo info please let us know.
