### ISSUE TITLE
Unstable behavior with circular imports

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1239]
## Environment data

-   Language Server version: 2021.5.0
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample code

```python
# File: a.py

from __future__ import annotations

from .b import *

class A:
    def b(self) -> B:
        from .b import B
        return B()
```

```python
# File: b.py

from __future__ import annotations

from .a import *

class B:
    def a(self) -> A:
        from .a import A
        return A()
```

These two files are placed in the same folder. As far as I can tell, the code runs without a problem, though I'm not sure whether the usage of circular imports is solid.

## Expected behavior

Either there are no errors/warnings, or the errors/warnings are stable. The former behavior is preferred.

## Actual behavior

There are unstable errors/warnings in the result types.

Either `A` or `B` may be unable to resolve after some edit to the files. The errors/warnings will be gone if the files are closed and then reopened.

**Comment by erictraut** [comment]
You're creating a circular dependency. You should refactor or redesign your code to eliminate this.

Mypy also generates a "symbol is not defined" error in this code due to the circular dependency.

**Comment by Azureblade3808** [comment]
Is it true that circular dependencies are not supported, and the occasional successes in code analysis are not intended but are accidents?

If so, I'd like to know if there is a decent way to break classes, which reference each others only in type annotations, into separate files. It could be an easy task without type annotations. But as the types must be imported before being used, it became hard to accomplish.

**Comment by Azureblade3808** [comment]
I've learnt a TYPE_CHECKING trick from SO. Is it supposed to be supported?

```python
# File: a.py

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .b import B

class A:
    def b(self) -> B:
        from .b import B
        return B()
```

```python
# File: b.py

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .a import A

class B:
    def a(self) -> A:
        from .a import A
        return A()
```

**Comment by erictraut** [comment]
`TYPE_CHECKING` is supported, but that doesn't help in this situation. You still have a circular dependency that cannot be resolved by a type checker. You need to find a way to eliminate it. 

The fact that you had to resort to import statements within the function body of `a` and `b` is a good clue that something is problematic with your code structure. My recommendation is to look for a way to restructure or redesign the code so it doesn't involve cycles between two classes. If you cannot find a way to disentangle them, then consider moving them to the same source file.

**Comment by Azureblade3808** [comment]
Thank you for your advice.

The circular dependency is there because of the functionality of these classes, so it is not easily resolvable.

Combining the code into a same file is just what I wanted to avoid, as it would make very large files with complicated classes. I'll keep it as the last resort.

I admit the code has some smell, but I think that is negligible comparing to the difficulty in maintaining huge code files. As Pylance isn't complaining about my modified code using conditional imports with TYPE_CHECKING, and the code itself runs well, I'm going to stick to this way until it stops working.
