### ISSUE TITLE
Tagged unions not narrowed down correctly for TypedDicts

### ISSUE THREAD

**Issue by klbostee** [microsoft/pylance-release#1240]
## Environment data

-   Language Server version: 2021.5.0
-   OS and version: macOS 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 2.7

## Expected behaviour

The ability to discriminate between two TypedDicts using a Literal type, as explained in detail here: https://mypy.readthedocs.io/en/stable/literal_types.html#tagged-unions

## Actual behaviour

The Union type doesn't get narrowed by a check on the Literal:
 
![image](https://user-images.githubusercontent.com/13755/117287750-f8de0b80-ae6a-11eb-8107-e73e7a0eaeea.png)

**Comment by erictraut** [comment]
Thanks for the feature request.

Pylance already supports type narrowing for tagged unions of classes that have literal-typed fields. It doesn't currently support type narrowing for tagged unions of typed dicts with literal-typed values. Since mypy already supports this case, I think pyright should as well. I'll add it to the backlog.

**Comment by erictraut** [comment]
I've added support for type narrowing of tagged unions of typed dicts for conditional expressions of the form `x[K] == V` and `x[K] != V`. This support will be in the next release.

Thanks again for the feature request.

**Comment by klbostee** [comment]
For what it's worth: the specific use case I had in mind would also benefit from the ability to narrow with a conditional expression of the form `x[K] in (V, W)`, but I'm already very happy that we'll have `==` and `!=` soon of course! 🙂

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.4, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202154-26-may-2021
