### ISSUE TITLE
Missing stdlib docstrings in virtualenvs

### ISSUE THREAD

**Issue by iamkroot** [microsoft/pylance-release#1244]
**Describe the bug**
I'm seeing differing behaviour when running pyright inside a virtualenv, versus when using the default python interpreter. Specifically, the docstrings for objects from the standard library are not shown on hover when running inside a venv. 

Running "Go to definition" on a builtin while using the default interpreter brings up the actual python file, which includes the docstrings. Consequently, running "hover" on it shows the docs _and_ the signature correctly annotated with types from typeshed (I assume, since the types aren't present in the source py file).
However, when inside a virtualenv, "Go to definition" directly jumps to the typeshed stub, and "hover" only shows the annotated signature without the docs. 

**To Reproduce**
First, disable any other LSP extensions (like the default Python package in VSCode, because it uses jedi to fill in the docs inside venvs).
Do the following twice, once using default python interpreter, and once with pyright configured to use a venv:
1. Import any standard library module written in python, like `os` or `threading`
2. Type out any of the user-facing functions, eg: `os.walk` or `threading.active_count`
3. Call "Hover"/"Show documentation" capability of pyright

**Expected behavior**
The docstrings for builtins should be available in both the modes - with and without virtualenvs.

**Screenshots or Code**
```python
import threading
threading.active_count
```
Default Python Interpreter:
![Default Python Interpreter](https://user-images.githubusercontent.com/29517049/117403523-f096d680-af25-11eb-823a-41a5d4d76ffc.png)

Virtualenv enabled:
![Virtualenv enabled](https://user-images.githubusercontent.com/29517049/117403528-f2f93080-af25-11eb-8a3d-1d9deac6ea25.png)

**VS Code extension or command-line**
Using the VSCode extension, v1.1.138

**Comment by jakebailey** [comment]
Can you please provide trace logs? What version of python is in your venv?

**Comment by iamkroot** [comment]
I'm using Python 3.9.4, and the venv is created by Poetry.
Attached the logs, with and without the venv.
[pyright_logs_default.txt](https://github.com/microsoft/pylance-release/files/6456775/pyright_logs_default.txt)
[pyright_logs_venv.txt](https://github.com/microsoft/pylance-release/files/6456777/pyright_logs_venv.txt)

Looking at the first few lines, it seems pretty evident where the source of the bug is - the search paths for pyright when venv is activated include the site-packages of the venv, but not the site-packages folder of the system python. 
Considering that venvs do not duplicate the stdlib into their own folders, pyright thus fails to ever check `/usr/lib/python` folders when looking for docstrings in this case.

**Comment by jakebailey** [comment]
That isn't quite how it works; Pylance/pyright call the interpreter and retrieve `sys.path` directly, so we should be getting the same paths that the interpreter uses when running the code. The fact that the global folders aren't appearing in `sys.path` implies there's something wrong with the interpreter (or at least the way we run it, which is directly).

I'm not entirely certain how poetry works, but it would surprise me if it needed some extra step to get paths configured properly.

The logs have been redacted, so I'm not sure if the interpreter path is listed anywhere, but can you check and see if running something like `/path/to/venv/python -c 'import sys; print(sys.path)'` outputs the correct paths?

**Comment by iamkroot** [comment]
I was indeed doing exactly what you stated, thanks. I went throught the pyright source and just got to the point where it looks for the search paths.
This is the relevant file: https://github.com/microsoft/pyright/blob/7bb059ecbab5c0c446d4dcf5376fc5ce8bd8cd26/packages/pyright-internal/src/analyzer/pythonPathUtils.ts

In the non-venv case, what you described is true. However, please correct me if I'm mistaken, in the case of venv, it doesn't ever call the python interpreter, and only does a manual search of all the possible sites.

https://github.com/microsoft/pyright/blob/7bb059ecbab5c0c446d4dcf5376fc5ce8bd8cd26/packages/pyright-internal/src/analyzer/pythonPathUtils.ts#L80-L109

Maybe, the `return foundPaths;` shouldn't be present? That would allow it to use the interpreter method you described.

**Comment by iamkroot** [comment]
And yes, running the `/path/to/venv/python -c 'import sys; print(sys.path)'` does give include the default python stdlib paths. Which seems to support my case that in the case of venvs, pyright doesn't execute that command.

**Comment by erictraut** [comment]
If you do not specify a pythonPath or a venv, pyright will execute `python3` from the shell and retrieve the import resolution paths from the python interpreter that you have configured in the shell.

**Comment by jakebailey** [comment]
Yeah, sorry, I didn't realize you were literally using the "venv" config and assumed you were using pythonPath or an activated environment. The "venv" config is a very targeted feature for a specific usecase.
