### ISSUE TITLE
Why does a Pandas DataFrame become an NDFrame?

### ISSUE THREAD

**Issue by tcrapts** [microsoft/pylance-release#1246]
Hello,

consider the following code:

```python
import pandas as pd

df = pd.DataFrame(data={"test": "b", "test2": "c", "test3": "d"})
df_selection = df[["test", "test2"]]
df_merge = df.merge(right=df_selection, on="test")
```
According to Pylance, df_selection is of type 'NDFrame'. This causes problems when you want to use `df_selection` where a DataFrame is expected, for instance the keyword 'right' in df.merge().

Can someone perhaps explain this behavior?

![image](https://user-images.githubusercontent.com/51760013/117420172-972aa980-af1d-11eb-9fa1-326029ce9056.png)

**Comment by jakebailey** [comment]
@gramster

This recently changed to try and make the stubs more permissive, but this may be a regression.

**Comment by judej** [comment]
Looks like this is no longer an issue with the latest stubs. Please reopen if you are still experiencing it.

**Comment by Oliversinn** [comment]
I am having an issue with this. Here is my example:

```python
import pandas as pd
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
percent = round(df["col1"] / (df["col2"]) * 100,2)
df.insert(
            loc=1,
            column= "percent",
            value=percent
        )
```

This throws the following output in mypy:

```bash
error: Argument "value" to "insert" of "DataFrame" has incompatible type "DataFrame"; expected "str | bytes | date | datetime | timedelta | datetime64 | timedelta64 | bool | int | float | Timestamp | Timedelta | complex | Sequence[Any] | ndarray[Any, Any] | Series[Any] | Index[Any] | None"  [arg-type]
```

**Comment by debonte** [comment]
@Oliversinn, if you're looking for general help with writing code that uses `pandas`, I believe https://stackoverflow.com/questions/tagged/pandas is the recommended place to ask questions.

If you believe there's a problem with the `pandas` type stubs that are shipped with Pylance, please file an issue at https://github.com/pandas-dev/pandas-stubs.

If you believe that this is an issue with Pylance, please open a new issue. This one is very old.
