### ISSUE TITLE
IntelliSense does not suggest class attributes (@attr)

### ISSUE THREAD

**Issue by tomrunia** [microsoft/pylance-release#1251]
## Environment data

-   VS Code version: **1.56.0**
-   Extension version (available under the Extensions sidebar): **2021.4.765268190**
-   OS and version: **MacOS 11.3**
-   Python version (& distribution if applicable, e.g. Anaconda): **Python 3.9**
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): **conda**
-   Relevant/affected Python packages and their versions: **n/a**
-   Relevant/affected Python-related VS Code extensions and their versions: **n/a**
-   Value of the `python.languageServer` setting: PyLance **2021.5.1**

## Expected behaviour

IntelliSense should provide suggestions for class attributes.

## Actual behaviour

IntelliSense suggestions do not work for class attributes. 

For example, parameter suggestions do _not_ appear for this `@attr` class:

![Screenshot 2021-05-07 at 15 58 36](https://user-images.githubusercontent.com/5536129/117461317-b3463f00-af4d-11eb-9813-5fda020ab42e.png)

But do appear for this class with an `__init__` function:

![Screenshot 2021-05-07 at 15 59 17](https://user-images.githubusercontent.com/5536129/117461403-cb1dc300-af4d-11eb-89b7-9a9d4bf9baa7.png)

And also work when the class is decorated with an `@dataclass`:

![Screenshot 2021-05-07 at 16 06 34](https://user-images.githubusercontent.com/5536129/117461837-4f704600-af4e-11eb-98c2-c4ad83d15659.png)

I would hope and expect to see the latter behavior also for `attr` and undecorated dataclasses.

**Comment by jakebailey** [comment]
This works in the latest version of attrs, if you use `define`:

![image](https://user-images.githubusercontent.com/5341706/117511617-e2a37e80-af42-11eb-871f-d0f8e0b17975.png)

Additionally, I don't think those tooltips are from Pylance; those look like some other LS (maybe jedi?).

I'll close this in favor of #226, which is the issue tracking attrs support.
