### ISSUE TITLE
Analysis slow when .asv is present

### ISSUE THREAD

**Issue by max-sixty** [microsoft/pylance-release#1254]
> Would you mind making a new issue with the set of steps? I think your case is sufficiently different than the original post and I'd like to split the two apart.

_Originally posted by @jakebailey in https://github.com/microsoft/pylance-release/issues/702#issuecomment-825228790_

While I couldn't originally repro, I'm now getting this issue. (Maybe I needed to restart VSCode or similar?)

To reproduce:

```sh
git clone https://github.com/pydata/xarray
cd xarray

# Create an asv environment, takes a while
asv profile unstacking.Unstacking.time_unstack_pandas_slow master
```

...now hit cmd-t. With trace logging, I get https://gist.github.com/max-sixty/dc5765d45f949cd25a24ee346bfe81a7. Everything is expected AFAIK until https://gist.github.com/max-sixty/dc5765d45f949cd25a24ee346bfe81a7#file-gistfile1-txt-L1191, where it starts scanning the ASV environments. Those environments are accessible by python, so I would think shouldn't be scanned.

From then on, trying to find a method (e.g. `clip`) from cmd-t doesn't complete in 15 seconds, unfortunately it's not that helpful. And no logs or warnings without turning on trace logging.

After removing the `asv_bench/.asv` path, the completions are back to millis!

Thanks!

**Comment by jakebailey** [comment]
Sorry to be looking at this so late.

Can you try creating a pyrightconfig.json file and add `.asv` to the excludes to see if that fixes the issue? https://github.com/microsoft/pyright/blob/main/docs/configuration.md#main-pyright-config-options

But, I don't exactly know why we would be scanning those files, if they are unreferenced from opened files.

**Comment by heejaechang** [comment]
we now auto-exclude any folder starts with ".". please re-open the issue if it still repro with latest pylance.
