### ISSUE TITLE
Pylance license and copyright violation

### ISSUE THREAD

**Issue by rushfan0** [microsoft/pylance-release#1256]
Currently, pylance is a closed source component. Microsoft does not allow users to use it outside of microsoft products. 

It is not fair that certain users can implement pylance it their own editors, like in the repo: https://github.com/kuator/totally-not-hacked-pylance.nvim

These kind of copyright violations by the community should be actively pursued by microsoft, because it is well known that microsoft, especially the place team,  is not interested in open source.

**Comment by savannahostrowski** [comment]
We've done our best to address this on our [FAQ](https://github.com/microsoft/pylance-release/blob/main/FAQ.md#are-there-any-plans-to-open-source-pylance-in-the-future).
