### ISSUE TITLE
Don't change VS code colors

### ISSUE THREAD

**Issue by barbax7** [microsoft/pylance-release#1257]
Firstly, I decided not to use Pylance because it changes my default color theme.

I prefer that i can keep my color theme.

**Comment by savannahostrowski** [comment]
Hey there, you're probably noticing Pylance's enhanced syntax highlighting called semantic colourization.

If you'd like to disable this functionality, you can set:

```
 "editor.semanticTokenColorCustomizations": {
            "[One Dark Pro]": {
                // Apply to this theme only
                "enabled": false
            }
        }

```

You should replace "One Dark Pro" with the name of your theme.

**Comment by barbax7** [comment]
Thank you, that is my theme! Ahahah

Actually now I feel more confident with the semantic colourization, but thanks a lot for your held and for your time.
