### ISSUE TITLE
Support egg/zip files

### ISSUE THREAD

**Issue by Syndorik** [microsoft/pylance-release#1260]
## Environment data

-   Language Server version: 2021.5.2-pre.1
-   OS and version: Windows
-   Python version (& distribution if applicable, e.g. Anaconda): Conda
## Expected behaviour

When I do

```
conda install -c huggingface transformers
```
It installs to my environement an eggfile. Autocompletion doesn't work with them, while it works for usual installations

**Comment by jakebailey** [comment]
Hm, you say egg-link files; those should work already. Can you please include trace logs our template asks for? This would indicate that python isn't giving us the list of paths correctly.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
(Basically, `.egg` and `.zip` aren't yet supported, but `.egg-link` is something that Python will stick into `sys.path` which we do use.)

**Comment by Syndorik** [comment]
Oh sorry, I'm fairly new to this, so I might have misunderstood egg-link and egg files. I have two files in my site-package:
transformers-4.5.1-py3.8.egg
transformers.pth

Are these supported?

**Comment by jakebailey** [comment]
Retitled to match for better tracking.

**Comment by Syndorik** [comment]
Ok thanks for your answer!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.6.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202160-2-june-2021
