### ISSUE TITLE
Allow Pylance to be run when explicitly enabled but interpreter is Python 2

### ISSUE THREAD

**Issue by TrmorySpindrift** [microsoft/pylance-release#1263]
Today I updated my vscode and python extension, and found semantic highlighting missing when I select the python interpreter to py2.7.
Will Pylance consider supportting python 2.7, I wonder? 
Is it possible to enable Pylance language server(Includde semantic highlighting) ignoring the interpreter selection?

**Comment by jakebailey** [comment]
Pylance doesn't support Python 2, and we have no plans to do so. When selecting a Python 2 interpreter, the Python extension is falls back on an year-ish old version of jedi, which is why you're seeing semantic tokens disabled.

You might be seeing a difference now because the latest Python extension now more strongly enforces the use of a compatible language server when a Python 2 interpreter is selected. Before, explicitly configuring "Pylance" would enable Pylance regardless of the Python interpreter in use, but the newer version loads jedi rather than trying to use Pylance (which isn't guaranteed to work; our parser and code assumes 3+).

**Comment by jakebailey** [comment]
If you downgrade your Python version, you may get this functionality back, but it wasn't guaranteed to work before and probably wasn't behaving correctly (and it's likely Python 2 support will go away in the Python extension in the future).

**Comment by jakebailey** [comment]
If #1264 is the same, we may want to consider patching the core extension so that explicitly setting a language server guarantees it is used, skipping the Python 2 checks.

@kimadeline @luabud @karthiknadig

**Comment by TrmorySpindrift** [comment]
Thanks!
I think it more flexible for what you said, "if an LS is explicitly set, use it regardless of the interpreter", 
cause code compeltation, semantic highlighting, etc really helpful for me when py2 coding.

**Comment by benblo** [comment]
Huge downgrade for me too 👎 ! Pylance is far superior to Jedi, even with 2.7, and the gain far outweighs the few potential discrepancies. 
I too vote for a way to bypass the checks (either explicitly selecting Pylance rather than Default, or an extra option).

**Comment by jakebailey** [comment]
I've sent https://github.com/microsoft/vscode-python/pull/16210 for review which will allow Pylance to run if explicitly enabled.

**Comment by jakebailey** [comment]
The latest Python extension (2021.5.842923320) should have fixed this. By default, Pylance won't activate if Python 2 is selected (to avoid causing problems), but if you explicitly enable Pylance via `python.languageServer`, then the Python extension will respect that choice.

**Comment by anttin2020** [comment]
> The latest Python extension (2021.5.842923320) should have fixed this. By default, Pylance won't activate if Python 2 is selected (to avoid causing problems), but if you explicitly enable Pylance via `python.languageServer`, then the Python extension will respect that choice.

Yes it does but then nothing works for Python2 anymore. 
I know Python2 is not actively developed anymore but it is still used in many places like software scripting and so it cannot be just dropped without clear warning.
Before ...320 it worked fine for 2.7.17 but that broke Python2 totally in VSCode.

I made a bug report.

**Comment by jakebailey** [comment]
If you set `"python.languageServer": "Pylance"`, then it will work, even if you are using Python 2.

Originally, Pylance was entirely opt in while in preview. Then, we made it the default, with the intent that it became active for all users we knew it'd work for. Pylance does not officially support Python 2, so we chose to run Jedi instead. But, some users were actually using it with Python 2 before the default change, so we changed it so that those who had explicitly set Pylance before could still do so, while still not breaking other users. In the course of that fix, I made an error and flipped a condition, which made Pylance run more often than intended, and maybe that's what you're seeing, but at the moment, you can still set in your user config to use Pylance and that should work.

**Comment by anttin2020** [comment]
That is exactly how I had it before that update and after the update I checked and it was still set to 'pylance' but the result was unusable. Just going back to previous Python extension update made it o work again like just before the update so there was something serious that changed in the Python extension, Pylance version is the same.

I had and have this:
"python.languageServer": "Pylance",

Can you please tell me all the related settings I should have, then I can check them out and try again.

Thank you!

**Comment by jakebailey** [comment]
The only thing I can think of is that you have the setting set in multiple places, and one is taking over, e.g. "default" in a workspace but "pylance" globally. It'd be helpful to know which version numbers you're referring to, as there have been three Python extension versions in the past week or so.

**Comment by anttin2020** [comment]
I did tell that above:
"Before ...320 it worked fine for 2.7.17 but that broke Python2 totally in VSCode.
I made a bug report and went back to ...3038 which works but linting is done with Pylint."
So the two latest updates.

And no, I have Pylance selected in both 'user' and 'workspace' (and nothing in 'folder'.

Further ideas? :)

**Comment by jakebailey** [comment]
- 558 - Introduction of "Default", Python 2 meant Jedi for backwards compatibility.
- 038 - An error in the code I wrote meant that Python 2 allowed Pylance if "Default", but not when "Pylance".
- 320 - The "corrected" state where Python 2 allows Pylance if "Pylance", not when "Default".

So, your case should work. You may want to just file a bug with the requisite logs on https://github.com/microsoft/vscode-python, as that's where the code lies.

**Comment by anttin2020** [comment]
Yes there is something strange with 320, I have 'Pylance' and it did not work. 038 works with 'Default' AND 'Pylance' which it shouldn't do based to above :o
I have made bug report even before writing here as I told in my first comment :)

But the Problems list uses pylint even if I disable it (as long as I have use linting enabled), is that correct? This happens to both Python2 and Python3.
There is no option to select Pylance as linter so it uses pylint?
If those are correct, then using Pylance with Python2 does not actually give benefits of Pylance but it uses some other (Jedi?) in the background?
So what are the best VSCode settings (language server,linter etc.) for Python2 to get as much info as possible? :)
Thanks!

**Comment by jakebailey** [comment]
> I have made bug report even before writing here as I told in my first comment :)

Do you mean https://github.com/microsoft/vscode-python/issues/16253?

> But the Problems list uses pylint even if I disable it (EVEN IF I DISABLE LINTING in settings), is that correct? This happens to both Python2 and Python3.
> There is no option to select Pylance as linter so it uses pylint?

That sounds like https://github.com/microsoft/vscode-python/issues/16150.

> So what are the best VSCode settings (language server,linter etc.) for Python2 to get as much info as possible? :)


Pylance doesn't handle Python 2, so if you want to use it, you have to use the subset of Python 2 that is compatible with Python 3. The only LSs that explicitly support Python 2 are Jedi (the old one) and MPLS ("Microsoft"), neither of which are maintained given 1) Python 2 was EOL more than a year ago and most projects have dropped it, and 2) we have focused efforts on pylance/pyright and Jedi over LSP.
