### ISSUE TITLE
Pylance unusable with most recent release

### ISSUE THREAD

**Issue by zbs** [microsoft/pylance-release#1264]
2021.5 breaks Pylance for me. No intellisense features are working and the Python Language Server tab is missing from the output pane. 

I've had similar issues in the past (#1070), not sure if they're related to my setup.

**Comment by jakebailey** [comment]
You didn't fill out the template, but based on your linked issue, this sounds like #1263. The Python extension is now more strongly enforcing that those using Python 2 are using a language server that is guaranteed to work. Pylance is not compatible with Python 2 and the info it gives when run with a Python 2 interpreter selected will likely be incorrect.
