### ISSUE TITLE
Why can’t I access the member of a proto message？

### ISSUE THREAD

**Issue by phhcer** [microsoft/pylance-release#1266]
```proto
# file_name: test.proto
message base
{
    optional uint32 n = 1;
}
message Test
{
    optional base test = 1;
}
```
```python
import test_pb2
def demo(req: test_pb2.Test) -> str:
    print(req.test.n)  # unknown and cannot access the member
```

how can I deal with the lint?

**Comment by erictraut** [comment]
We make extensive use of proto files on my team. Unfortunately, the generated "pb2" files don't work well with static type checkers, but there's a protoc plugin called [mypy_protobuf](https://github.com/dropbox/mypy-protobuf) that generates ".pyi" files that work great with pylance. Just install mypy_protobuf, and when you compile your proto files, add the following:

```
protoc -I. --python_out=. --mypy_out=. <name.proto>
```

**Comment by jakebailey** [comment]
I'm going to close this; this has been labeled as waiting for a response for about a month and this behavior is expected for protobuf's generated code.
