### ISSUE TITLE
Undefined variable 'goto' when using goto labels with python

### ISSUE THREAD

**Issue by JoshiAyush** [microsoft/pylance-release#1269]
-   VS Code Version: 1.55.2
-   Extension: Pylance
-   Extension version: v2021.5.1
-   OS: Linux x64 5.8.0-50-generic
-   Python version: v3.8.5
-   Relevant/affected Python packages and their versions: python-gotov1.2.0
-   Value of the `python.languageServer` setting: pylance

## Expected behaviour

No error squiggles as it was before installing `Pylance` 

## Actual behaviour

![Screenshot from 2021-05-11 11-56-21](https://user-images.githubusercontent.com/70365318/117768527-1f77ba00-b250-11eb-89fa-e8316b887efa.png)

Error squiggles on labels `goto` and `label`

## Steps to reproduce:

1. Install `Pylance` extension
2. Install `goto-statement`, either install it by using `pip install goto-statement` and then later use it like,
   
    ```python
    from goto import with_goto

    @with_goto
    def function():
        label .begin
        print("goto ...")
        goto .begin
    ```
    or if the installation doesn't work then you can just download the code from here it's just around 250 lines big [python-goto](https://github.com/JoshiAyush/linkedin-bot/blob/master/src/python_goto/goto.py) and then later use it like,
   
    ```python
    from goto import with_goto

    @with_goto
    def function():
        label .begin
        print("goto ...")
        goto .begin
    ```

**Comment by erictraut** [comment]
The `goto-statement` library appears to be modifying the underlying Python byte stream, effectively extending the Python language in a non-standard manner. Tools like pylance assume you're using the standard Python language. In this case, it's telling you (correctly) that the `goto` symbol is not defined anywhere in your function's context.

You can disable the `reportUndefinedVariable` warning if you like.

**Comment by sylveon** [comment]
![image](https://user-images.githubusercontent.com/6440374/117909360-14e90f00-b2a8-11eb-8e11-ab597de53fea.png)

**Comment by JoshiAyush** [comment]
@sylveon I'm not using the 'April Fool's joke' one instead I'm using the one made by a user on GitHub Sebastian Noack and believe me that version of Sebastian Noack works just fine.

**Comment by JoshiAyush** [comment]
@erictraut  Yes you are right, it's just the warning that I'm annoyed by. Can't these extensions be modified so that they know what's going on under the hood, like in my code if there would be some feature so that the extension know already by doing some internal processing what this `with_goto` decorator is doing and then later mark these `goto` and `label` labels as a part of the `with_goto` decorator.

**Comment by jakebailey** [comment]
This sort of thing far surpasses the kind of operation a static checker is expected to understand; this library  abuses dot accesses to trick the parser into accepting the code, then literally modifies the bytecode of functions to make them support a new keyword.

If python itself adds this keyword or some PEP defines a way to do this more generally, then I can of course see accepting it, but this is super hacky and I do not expect to support it when it's a third party library.

If you are adamant to use this library, then you can silence the messages with a `# type: ignore` comment on the line, override the [diagnostic settings](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md) to disable it globally, or maybe declare fake variables at the top of the file (like `goto: Any = ...`).

But, this is only a workaround. This library allows arbitrary jumping in the code, which our code flow (or any other analysis tool) is not going to be able to handle. You may be silently hiding potential errors that wouldn't be present if the code were structured in a normal way.

**Comment by JoshiAyush** [comment]
> This sort of thing far surpasses the kind of operation a static checker is expected to understand; this library abuses dot accesses to trick the parser into accepting the code, then literally modifies the bytecode of functions to make them support a new keyword.
> 
> If python itself adds this keyword or some PEP defines a way to do this more generally, then I can of course see accepting it, but this is super hacky and I do not expect to support it when it's a third party library.
> 
> If you are adamant to use this library, then you can silence the messages with a `# type: ignore` comment on the line, override the [diagnostic settings](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md) to disable it globally, or maybe declare fake variables at the top of the file (like `goto: Any = ...`).
> 
> But, this is only a workaround. This library allows arbitrary jumping in the code, which our code flow (or any other analysis tool) is not going to be able to handle. You may be silently hiding potential errors that wouldn't be present if the code were structured in a normal way.

Thanks for your response. It was not a actual problem as you said it's a dynamic behaviour and I agree with that I know that the library effectively change the byte codes to support a new keyword and it's a dynamic behaviour I was just annoyed by those `yellow squiggles` which i just got rid of by applying one of your mentioned method,

```python3
from typing import Any

goto: Any = ...
label: Any = ...
```

I didn't know that making a fake variable won't effect the `with_goto` functionality.
