### ISSUE TITLE
Automatically update import paths when you move or rename a python file

### ISSUE THREAD

**Issue by ychechik** [microsoft/pylance-release#127]
Like PyCharm does- on change of dir or file name- update all imports in project which uses this path/module/package.

**Comment by savannahostrowski** [comment]
Hey @ychechik 

Thanks for the suggestion. We are currently investigating this request and will update with details soon.

**Comment by janLuke** [comment]
I periodically evaluate VS Code and the lack of refactoring features like these keeps me away from it. I'm sure there's a large number of developers that do the same but don't bother coming here to upvote issues. They just reopen PyCharm without any doubt that it's the right choice.

**Comment by jakebailey** [comment]
With the recent fix to folder deletion detection, this becomes more reasonable, but to obtain a UI similar to that of TypeScript (which already has this in VS Code), we'll have to wait until we can move the LS client into our extension (to be able to access the VS Code UI) before we can start figuring this one out.

**Comment by heejaechang** [comment]
we are working on this.

**Comment by savannahostrowski** [comment]
We are currently rolling this out slowly. If you don't have it available today, keep an eye out over the next couple weeks as we make it available to everyone.

**Comment by bsaunders23** [comment]
Great to hear @savannahostrowski ! I'm using the latest insiders build w/ latest Pylance, but not seeing the prompt to refactor when renaming files/paths. Maybe missed in release notes, if so could you confirm this released? Thanks!

**Comment by luabud** [comment]
Closing as this has been released early December: https://devblogs.microsoft.com/python/python-in-visual-studio-code-december-2021-release/#module-rename-with-change-preview

@bsaunders23 let me know if it still doesn't work for you and we can investigate what is going on 😊

**Comment by kasir-barati** [comment]
@luabud, I do not see the prompt either in ubuntu 24.4 with Pylance extension installed. Any comment?
