### ISSUE TITLE
Unable  to import scipy

### ISSUE THREAD

**Issue by VanshSh** [microsoft/pylance-release#1271]
Issue Type: <b>Bug</b>

Import "scipy" could not be resolved Pylance.
plz help

Extension version: 2021.5.1
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (1.22GB free)|
|Process Argv|--crash-reporter-id b35c49ce-6a91-4a83-8438-477cd6a04aea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
bridgeflight:30299254

```

</details>

**Comment by VanshSh** [comment]
I followed the step but nothing worked.
Pylance version:2021.5.1
Python  extension version:2021.5.829140558
![Screenshot (513)](https://user-images.githubusercontent.com/81517284/117871307-dad53880-b2ba-11eb-893c-016346991f68.png)
![Screenshot (514)](https://user-images.githubusercontent.com/81517284/117871399-f80a0700-b2ba-11eb-932e-7fca872a036a.png)

**Comment by jakebailey** [comment]
Please, include the logs as text in your replies; the screenshots are pretty difficult to work with.

In your terminal, can you open python and run these lines and see what it outputs?

```
import scipy
import sys
print(sys.path)
```

**Comment by VanshSh** [comment]
Logs as text>>

[Info  - 11:57:07 PM] Pylance language server 2021.5.1 (pyright df8b6b3c) starting
[Info  - 11:57:07 PM] Server root directory: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist
[Info  - 12:35:48 AM] No configuration file found.
[Info  - 12:35:48 AM] No pyproject.toml file found.
[Info  - 12:35:48 AM] Setting pythonPath for service "w3python": "C:\Users\DELL\AppData\Local\Programs\Python\Python39\python.exe"
[Warn  - 12:35:48 AM] stubPath d:\Dell2\Documents\ECA\CODING\Python\w3python\typings is not a valid directory.
[Info  - 12:35:48 AM] Assuming Python version 3.9
[Info  - 12:35:48 AM] Assuming Python platform Windows
Search paths for d:\Dell2\Documents\ECA\CODING\Python\w3python
  c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib
  d:\Dell2\Documents\ECA\CODING\Python\w3python
  d:\Dell2\Documents\ECA\CODING\Python\w3python\typings
  c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stubs\...
  c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\bundled\stubs
  C:\Users\DELL\AppData\Local\Programs\Python\Python39\DLLs
  C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib
  C:\Users\DELL\AppData\Local\Programs\Python\Python39
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\win32
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\win32\lib
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\Pythonwin
  C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages
[Info  - 12:35:48 AM] Searching for source files
[Info  - 12:35:48 AM] Found 3 source files
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1620759817057 at d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py ...
[BG(1)]   parsing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (218ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 3ms] (57ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi (26ms)
[BG(1)]   binding: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (0ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing.pyi [fs read 1ms] (22ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing.pyi (9ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 1ms] (9ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (1ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 0ms] (5ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing_extensions.pyi (3ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\bundled\stubs\matplotlib\pyplot.pyi [fs read 1ms] (171ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\bundled\stubs\matplotlib\pyplot.pyi (20ms)
[BG(1)]   parsing: C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.pyi [fs read 1ms] (116ms)
[BG(1)]   binding: C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.pyi (29ms)
[BG(1)] getSemanticTokens delta previousResultId:1620759817057 at d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (709ms)
Background analysis message: analyze
[BG(1)] analyzing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py ...
[BG(1)]   checking: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (1ms)
[BG(1)] analyzing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
[FG] parsing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (72ms)
[FG] parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 1ms] (103ms)
[FG] binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi (64ms)
[FG] binding: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (7ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Received updated settings
[Info  - 12:39:11 AM] No configuration file found.
[Info  - 12:39:11 AM] No pyproject.toml file found.
[Info  - 12:39:11 AM] Setting pythonPath for service "w3python": "C:\Users\DELL\AppData\Local\Programs\Python\Python39\python.exe"
[Warn  - 12:39:11 AM] stubPath d:\Dell2\Documents\ECA\CODING\Python\w3python\typings is not a valid directory.
[Info  - 12:39:11 AM] Assuming Python version 3.9
[Info  - 12:39:11 AM] Assuming Python platform Windows
Search paths for d:\Dell2\Documents\ECA\CODING\Python\w3python
  c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib
  d:\Dell2\Documents\ECA\CODING\Python\w3python
  d:\Dell2\Documents\ECA\CODING\Python\w3python\typings
  c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stubs\...
  c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\bundled\stubs
  C:\Users\DELL\AppData\Local\Programs\Python\Python39\DLLs
  C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib
  C:\Users\DELL\AppData\Local\Programs\Python\Python39
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\win32
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\win32\lib
  C:\Users\DELL\AppData\Roaming\Python\Python39\site-packages\Pythonwin
  C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages
[Info  - 12:39:12 AM] Searching for source files
[Info  - 12:39:12 AM] Found 3 source files
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: getSemanticTokens delta
[FG] parsing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (86ms)
[FG] parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 1ms] (137ms)
[FG] binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi (44ms)
[FG] binding: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (0ms)
[BG(1)] getSemanticTokens delta previousResultId:1620759949265 at d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py ...
[BG(1)]   parsing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (360ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 1ms] (304ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\builtins.pyi (53ms)
[BG(1)]   binding: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (0ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing.pyi [fs read 0ms] (108ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing.pyi (14ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 1ms] (23ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (6ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 0ms] (9ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\typeshed-fallback\stdlib\typing_extensions.pyi (9ms)
[BG(1)]   parsing: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\bundled\stubs\matplotlib\pyplot.pyi [fs read 1ms] (141ms)
[BG(1)]   binding: c:\Users\DELL\.vscode\extensions\ms-python.vscode-pylance-2021.5.1\dist\bundled\stubs\matplotlib\pyplot.pyi (10ms)
[BG(1)]   parsing: C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.pyi [fs read 0ms] (151ms)
[BG(1)]   binding: C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\__init__.pyi (16ms)
[BG(1)] getSemanticTokens delta previousResultId:1620759949265 at d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (1233ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: analyze
[BG(1)] analyzing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py ...
[BG(1)]   checking: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (1ms)
[BG(1)] analyzing: d:\Dell2\Documents\ECA\CODING\Python\w3python\test.py (1ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Received updated settings

**Comment by VanshSh** [comment]
This is what I got as output after you told me to run the lines.>>>
 It was not possible to copy them so I took a screenshot
![Screenshot
 (523)](https://user-images.githubusercontent.com/81517284/117878415-5cc95f80-b2c3-11eb-8885-6a6ed224e010.png)

**Comment by jakebailey** [comment]
Thanks, those paths line up, so it's confusing why we aren't finding scipy.

One more thing, can you show what `scipy.__file__` is in the interpreter?

**Comment by VanshSh** [comment]
Thank you
I don't know how but know there is no error and it's working fine.
If I encountered the issue again I will inform you again.
