### ISSUE TITLE
Pylance intellisense error when DataFrame.rename columns paramater is a dict variable

### ISSUE THREAD

**Issue by GusAlmeida93** [microsoft/pylance-release#1274]
## Environment data

-   Language Server version: 2021.5.1
-   OS and version: Ubuntu 20.04 LTS running on Windows 10 20H2 WSL 2
-   Python version: Python 3.8.5, Pandas 1.2.4

## Actual behaviour

No overloads for "rename" match the provided arguments
  Argument types: (dict[str, str])PylancereportGeneralTypeIssues)

## Code Snippet / Additional information

```python
import pandas as pd

df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})

columns = {"A": "a", "B": "c"}

df.rename(columns=columns)
```

**Comment by judej** [comment]
Are you still seeing this issue? I am not able to reproduce it on the latest build (> 20222.5.0)

![image](https://user-images.githubusercontent.com/547753/170487634-917c347d-9f97-482d-b8d2-aa439ca0b1d7.png)


Please reopen if you are still experiencing it.

**Comment by ShivnarenSrinivasan** [comment]
> Are you still seeing this issue? I am not able to reproduce it on the latest build (> 20222.5.0)
> 
> ![image](https://user-images.githubusercontent.com/547753/170487634-917c347d-9f97-482d-b8d2-aa439ca0b1d7.png)
> 
> Please reopen if you are still experiencing it.

No, this is fixed—thanks!
