### ISSUE TITLE
Pylance reportMissingImports

### ISSUE THREAD

**Issue by bs2019** [microsoft/pylance-release#1280]
Hi,

I installed a new package and when I run my code this was the problem report
Import "PyEMD" could not be resolved Pylance(reportMissingImports)
And, as I used data = np.genfromtxt('SENSOR1.txt') but I got

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 531, in open
    raise IOError("%s not found." % path)
OSError: SENSOR1.txt not found.

I would appreciate your help with these two errors.
Best of all, 

Sandy

**Comment by jakebailey** [comment]
Thanks for the issue.

For the first message, it's saying that we can't find a module that you imported. Do you have this library installed in the interpreter that you've selected at the bottom left? Do you have code that reproduces this?

The second message is a runtime error when you run your code; that wouldn't be caused by Pylance.

**Comment by bs2019** [comment]
Hi,

Yes, I have installed that library in the interpreter.

Thanks for your help.

**Comment by jakebailey** [comment]
Our issue template asks for logs, but you didn't seem to include them. The instructions are copied here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

Can you provide logs and some example code?

**Comment by bs2019** [comment]
Thanks for your help.

Finallly, I have solved my second problem. Then my code can run, even when this message continues

![imagen](https://user-images.githubusercontent.com/47706078/118214033-aeddc280-b434-11eb-8872-433433c03d57.png)

I am using the PyEMD package for signal processing.

<img width="393" alt="imagen" src="https://user-images.githubusercontent.com/47706078/118214383-3aefea00-b435-11eb-9253-5eba2e178ecd.png">

Best regards
