### ISSUE TITLE
Make default language server

### ISSUE THREAD

**Issue by OmnipotentCoder** [microsoft/pylance-release#129]
every time extension pylance ask for make default language server
and I clicked on yes and reload I do it this thing at least ten time
but still same notification pop up it just wasting time nothing more than that  
## Environment data
-   Language Server version: 1.1.53
-   OS and version: Window 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.1

## Expected behaviour

it should start working as I click on yes and reload

## Actual behaviour

but it's not working

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
@OmnipotentCoder, the problem is likely due to the language preference being specified in the user settings and workspace settings. You can verify this by checking the user settings - (Ctrl-Shift P) and selecting "Preferences: Open Settings (JSON))" and the workspace setting found in the settings.json file in the .vscode folder in the project root. Look for the setting `"python.languageServer" `

Work around:
Delete the `"python.languageServer"` setting in the settings.json file in the .vscode folder

Hope this works for you, please let us know. Additionally we will add this issue to our backlog. Thanks for the report

**Comment by OmnipotentCoder** [comment]
Well I also went in settings.json file and change the "python.languageServer" from "Microsoft" to "Pylance" but after that same notification of Pylance still pop up to make default language server.

**Comment by MikhailArkhipov** [comment]
The check looks into global settings. Do you happen to have multiple settings files or multi-root workspace with settings per workspace?

**Comment by OmnipotentCoder** [comment]
> The check looks into global settings. Do you happen to have multiple settings files or multi-root workspace with settings per workspace?

Nope i am just using python and C language in VS code

**Comment by MikhailArkhipov** [comment]
Can you post content of your `settings.json` (and also search your workspace for other possible `settings.json` in subfolders). Thanks.

**Comment by OmnipotentCoder** [comment]
![image](https://user-images.githubusercontent.com/64587338/88256253-67851a80-ccd8-11ea-8179-b2cbe38c915e.png)
when I download **Pylance** I changed language server from **"Microsoft"** to **"Pylance"** but still after that same notification pop up 
to make default language server even I restart visual studio code 
3-4 times.

**Comment by MikhailArkhipov** [comment]
When you click 'Yes' does `python.languageServer` change to `Pylance`?

**Comment by jakebailey** [comment]
That's also the workspace config. What about your user settings JSON? (You can find it by searching for JSON in the command pallete)

**Comment by OmnipotentCoder** [comment]
Nope when i click on notification to make pylance
default language server it doesn't work after restart it's still ask for to make default language server so then i just go to settings.json and change language server and then still it doesn't work even after restart same notification again pop up to make pylance default language server

**Comment by jakebailey** [comment]
If you delete the languageServer option and move it to your user settings, does that fix things? Can you post logs from the Python output window?

**Comment by OmnipotentCoder** [comment]
> If you delete the languageServer option and move it to your user settings, does that fix things? Can you post logs from the Python output window?

Well i don't try to delete the language server option untill now but i will try this thing and i will send screenshot of this here but i can't able to send things right now and but in settings i can language server to none in both workspace and user also but it still doesn't work so now i just delete language server option then i will post the results here

**Comment by OmnipotentCoder** [comment]
My problem get solved after updating python extension today 
![image](https://user-images.githubusercontent.com/64587338/88360524-a330ea80-cd93-11ea-97b3-6a9893570238.png)
thank you for your all support and advise

**Comment by MikhailArkhipov** [comment]
We should still look into what happens with multiple setting files though.

**Comment by OmnipotentCoder** [comment]
yes, you are right about this sir but still, thanks for helping me
