### ISSUE TITLE
"already in use by an outer class" when subclassing Generic class within Generic class

### ISSUE THREAD

**Issue by Fatsie** [microsoft/pylance-release#1290]
## Environment data

-   Language Server version: 2021.5.1 (pyright df8b6b3c)
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.9 64-bit (conda)

## Expected behaviour

Allowing subclassing of generic inside a class with a class generic without a problem report.

## Actual behaviour

For the minimal example given below I get the following problem report:

```{
	"resource": "/home/verhaegs/eda/test/generic_in_generic.py",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "reportGeneralTypeIssues",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 8,
	"message": "TypeVar \"T2\" is already in use by an outer scope",
	"source": "Pylance",
	"startLineNumber": 9,
	"startColumn": 23,
	"endLineNumber": 9,
	"endColumn": 25
}
```

## Code Snippet / Additional information

```python
from typing import TypeVar, Generic

T = TypeVar("T")
class Elem(Generic[T]):
    pass

T2 = TypeVar("T2")
class Collection(Generic[T2]):
    class MyElem(Elem[T2]):
        pass
```

**Comment by Fatsie** [comment]
I am using pylance basic typechecking.

**Comment by erictraut** [comment]
A type variable used in an outer class cannot be used again in a nested class. This is explicitly disallowed in PEP 484, which says: "A generic class nested in another generic class cannot use same type variables. The scope of the type variables of the outer class doesn't cover the inner one". It gives the following example:

```python
from typing import Generic, Iterable, TypeVar

T = TypeVar('T')
S = TypeVar('S')

class Outer(Generic[T]):
    class Bad(Iterable[T]):       # Error
        ...
```

This is almost identical to your example above.

I noticed that mypy (another type checker) does not flag this as an error, which seems like a bug in mypy. I've filed [a bug report](https://github.com/python/mypy/issues/10479) on this issue.

**Comment by Fatsie** [comment]
Don't understand why PEP authors did not allow this. To me in their example in `Outer[int], `Bad` would be a subclass of `Iterable[int]` and not be a subclass of `Generic`.
Will try a work around.

**Comment by jakebailey** [comment]
Given this is explicitly disallowed in PEP 484, I'm going to close this. Any changes would need to be to the typing spec itself.

**Comment by luochen1990** [comment]
To provide more info, here is the related content in [PEP 484](https://peps.python.org/pep-0484/#scoping-rules-for-type-variables):

<img width="583" alt="image" src="https://user-images.githubusercontent.com/2309868/169445925-eb92165e-436d-40ae-beca-c48bcc8ae869.png">

And I think it is the critical part that `attr : Inner[T] = None` is allowed, and I think that is **the expected usage**.
