### ISSUE TITLE
Some pip packages are not properly detected during import and their attributes instances also 

### ISSUE THREAD

**Issue by akashdiphazra** [microsoft/pylance-release#1291]
OS: Windows 10 Home
VsCode Stable Version: 1.56.2
Pylance Version : 2021.5.2
vscode Python extension Version : 2021.5.842923320
Python Version : 3.9.1

![image](https://user-images.githubusercontent.com/61003681/118363300-508a1e80-b5b1-11eb-9d42-1abb6891d423.png)

![image](https://user-images.githubusercontent.com/61003681/118363744-816b5300-b5b3-11eb-83b3-4b7716f7cdbb.png)

**Comment by jakebailey** [comment]
The first message is intended, it's saying that you aren't using pandas in the code below, so it's grayed out.

What version of numpy are you using? The latest version of numpy should have better type info.

**Comment by akashdiphazra** [comment]
It's version number 1.20.3

**Comment by jakebailey** [comment]
Thanks. This is likely covered by #150, then; the next version of numpy enriches its type information to not mark these as "Any" anymore, so we're waiting a bit for upstream there. Closing in favor of that tracking issue.
