### ISSUE TITLE
Pylance import not resolved error

### ISSUE THREAD

**Issue by sahiljhawar** [microsoft/pylance-release#1292]
## Environment data

-   Language Server version: XXX
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9

## Expected behaviour

I installed prettyprinter and pywhatkit using `pip install prettyprinter` and `pip install pywhatkit`

As per expected behaviour VS Code should not show me import not resolved error. Although it should show me the functions, methods and function signatures for the module.

## Actual behaviour
It's shows me import not resolved error for several libraries such as requests, pywhatkit, prettyprinter, etc. I'm not able to get suggestions and code completions for such libraries. A wavy line is there under the library name. Previous to Pylance, everything was working smooth. But now it's not.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
Can you please provide the logs and code snippets our template requests? We can't really help without that info.

The instructions are mirrored here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
