### ISSUE TITLE
pylance issue

### ISSUE THREAD

**Issue by Aabdelmoumen** [microsoft/pylance-release#1293]
<h3> Environment data </h3>

-   Language Server version: 2021.5.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
You submitted the issue template without filling anything out. If you can describe the issue you're seeing and provide the requested info, then we can reopen this, but until then we can't do anything with this.
