### ISSUE TITLE
pylance not showing the info of the methods in random class in numpy module

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1296]
## Environment data

-   python extension version: v2021.6.842802838-dev
-   Language Server version: v2021.5.3-pre.1
-   OS and version: ubuntu 21.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.4 64-bit

## Expected behaviour

intellisense showing the info about the methods available in random class of the numpy module

## Actual behaviour

no info being showed by the intellisense

## Code Snippet / Additional information

numpy.random.

**Comment by bschnurr** [comment]
what version of numpy?

```
import numpy
print(numpy.__version__)
```

**Comment by arian47** [comment]
`python3.9 -m pip list | grep numpy`
1.20.3

**Comment by arian47** [comment]
it doesn't also show the numpy.ndarray object methods info too
I will keep adding the problems i do encounter for this module or if you want me to create another issue please tell me.

**Comment by bschnurr** [comment]
hmm. seems to be working for me.

![image](https://user-images.githubusercontent.com/1946977/118526448-1b86e480-b6f5-11eb-9d4b-e34fb0c15a50.png)

Are you sure your have the correct interpreter selected that has your installed numpy?
can you provide the logs from your "Python Language Server" window, under "Output" tab

**Comment by bschnurr** [comment]
I know numpy is still working on their stubs, some missing entries will be updated in their next release.
https://github.com/microsoft/pylance-release/issues/150#issuecomment-842312255

Please log any new missing stub issue with them.

**Comment by bschnurr** [comment]
you could try bringing that new pyi version over locally

**Comment by jakebailey** [comment]
This works here: 

![image](https://user-images.githubusercontent.com/5341706/118534123-bc799d80-b6fd-11eb-8f69-988bb79985f7.png)

As does: 

![image](https://user-images.githubusercontent.com/5341706/118534160-c69b9c00-b6fd-11eb-8a32-a6677b862c01.png)

But this issue appears to be about the contents themselves being missing items ("not showing info of the methods"), which I believe to be covered by #150 and likely resolved in the next numpy release. I'll close this in favor of #150.
