### ISSUE TITLE
Unresolved import

### ISSUE THREAD

**Issue by Anvit182007** [microsoft/pylance-release#1297]
This has been happening for a long time after the update of Pylance. I am trying to import a module that I just downloaded and it is showing that it can not be resolved. Please reply fast with a solution

**Comment by jakebailey** [comment]
You haven't filled out our issue template, which makes it difficult to understand what you're reporting. See our instructions mirrored here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

Are you saying that when you install a package, it doesn't immediately resolve? That may be #923.

Or does it never work, even after a reload of the editor / Pylance?
