### ISSUE TITLE
Pylance analysis breaks on Zope packages

### ISSUE THREAD

**Issue by jaroel** [microsoft/pylance-release#130]
Hi,

The Pylance analysis (and therefore IntelliSense, aka command-click) seems to break on Zope related packages.

## Environment data

-   Language Server version: v2020.7.2
-   OS and version: OSX 10.15.5 
-   Python version: CPython 3.6.6 in a venv via pyenv
-  Microsoft Python Language Server version 0.5.51.0

## Expected behaviour

I should be able to command-click from one file to another.

## Actual behaviour

I see a tooltip "Code analysis is in progress.." , and cannot command-click into files.
I noticed I can command-click into some files, but they are probably indexed *before* the analysis crashes.

## Logs

I see no data in the PLS output panel after "[Info  - 3:39:38 PM] Initializing for /Users/roel/Develop/pylance_zope/bin/python
".
"python.analysis.logLevel" is set to "Trace", but I see no tracing data in the Python output panel.

## Code Snippet / Additional information
This is what I did:

`pyenv local 3.6.6`
`python3.6 -m venv .`
`bin/pip install Zope\[wsgi\] -c https://zopefoundation.github.io/Zope/releases/5.0a2/requirements-full.txt`

Then start vscode with pylance
`code .`

Make sure you select the venv Python interpreter `./bin/python`.

Open a Python file, say `AccessControl.class_init`, and try to command-click to `AccessControl.Permission`.

**Comment by erictraut** [comment]
Thanks for the bug report.

I've followed your repro steps with the latest version of Pylance (v2020.7.2), and it is working fine for me. What behavior do you get when you command-click on `Permission`? For me, hovering over `Permission` with the command key down displays a docstring, and command-clicking takes me to the declaration.

**Comment by jaroel** [comment]
![Screenshot 2020-07-18 at 12 29 46](https://user-images.githubusercontent.com/70700/87850685-6c218b80-c8f2-11ea-82e4-0a072f192215.png)

This is what I see, and command-clicking doesn't do anything for me.

**Comment by jaroel** [comment]
![Screenshot 2020-07-18 at 12 31 05](https://user-images.githubusercontent.com/70700/87850719-96734900-c8f2-11ea-9282-79f906ca0e7a.png)

This is the PLS output

**Comment by jaroel** [comment]
It seems to work with the homebrew python3.7, but not with my pyenv 3.6.6 install.

**Comment by jaroel** [comment]
Okay, it didn't work because somehow Pylance wasn't able to change my settings.json, so it said `"python.languageServer": "Microsoft"` instead of `"python.languageServer": "Pylance"`.

Pylance works as expected, false alarm.
