### ISSUE TITLE
Generic Function Factory Fails Static Type Check

### ISSUE THREAD

**Issue by cSDes1gn** [microsoft/pylance-release#1304]
Hi guys,

I'm writing a generic function for getting objects of different types from a module. For example if a module has internal objects `A`, `B` and `C`, instead of writing a getter for each object type:
```py
def get_a() -> A: ...
def get_b() -> B: ...
def get_c() -> C: ...
```
I would like to build a generic getter that takes an object type as a parameter and returns the instance that matches that type:
```py
_T = TypeVar('_T', bound=Union[A,B,C])
def get(ref_type:Type[_T]) -> _T: ...
```
So the resulting external module accessors would look like this:
```py
a:A = get(A)
```
The motivation is to avoid duplicate code across each object getter. I have written a short demo of what I am trying to achieve below. The code runs as expected printing object `__repr__` of Type `A` when I pass `A` into the getter and so on. Pylance underlines the `a` and `b` variables as seen in the snippet reporting a general typing issue.
```py
from typing import Type, TypeVar, Union

class A:
    def __init__(self) -> None: ...

class B:
    def __init__(self) -> None: ...

_T = TypeVar('_T', bound=Union[A,B])
         
def getter(something:Type[_T]) -> _T:
    a = A()
    b = B()
    if something is A: return a
    else: return b

print(getter(A))
```
I have used other typing examples of factory functions from the typing docs as benchmarks to validate my environment. I am open to alternate suggestions for tackling this problem.

## Environment data
-   Language Server version: Pylance language server 2021.5.2 (pyright df8b6b3c)
-   OS and version: MacOS BigSur 11.2.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

`return a` and `return b` should not fail pylance general typing issues

## Actual behaviour
The snippet is correctly interpreted by my python interpreter and runs as expected but fails `Pylance(reportGeneralTypeIssues)` static type checking.

## Logs
The logs appear nominal to me:
```
[FG] parsing: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (1ms)
[FG] binding: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py ...
[BG(1)]   parsing: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (3ms)
[BG(1)]   binding: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (0ms)
[BG(1)] getSemanticTokens full at /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (6ms)
Background analysis message: analyze
[BG(1)] analyzing: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py ...
[BG(1)]   checking: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (2ms)
[BG(1)] analyzing: /Users/christiansargusingh/Incuvers/Sandbox/pytypes/test.py (2ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

## Code Snippet / Additional information
![Screen Shot 2021-05-18 at 12 34 28 PM](https://user-images.githubusercontent.com/26971036/118689809-65df9280-b7d5-11eb-9656-7ac1e9a2eca0.png)

**Comment by erictraut** [comment]
The parameter `something` is annotated as `Type[_T]`, and `_T` is a bound type variable. That means the caller must pass an argument that is `A`, `B`, or some subclass of these, and the return result must be an instance that matches the type of the input parameter.

For example:
```python
class ASub(A): ...

getter(ASub) # According to the signature of `getter`, this must return an instance of `ASub`
```

It's not clear to me why your getter's implementation is specifically checking whether `function` is `A`. Is it feasible for you to write your getter like this instead?
```python
def getter(something: Type[_T]) -> _T:
    return something()
```

**Comment by cSDes1gn** [comment]
I think I see what you are getting at. Im trying to create a generic function but then am attempting to scope it with conditionals to be less generic. Your solution at least solves the pylance typing issue so I will think about my implementation some more. Cheers!

**Comment by cSDes1gn** [comment]
Here is a practical example of what I am looking to do with this for reference (since I realize the example I provided in the issue is vague.

```py
    def checkout_device(self) -> Device:
        """
        Generate a deepcopy of device runtime object

        :return: deepcopy of device runtime object
        :rtype: Device
        """
        return copy.deepcopy(self._device)

    def checkout_imaging_profile(self) -> ImagingProfile:
        """
        Generate a deepcopy of imaging profile runtime object

        :return: deepcopy of device runtime object
        :rtype: ImagingProfile
        """
        return copy.deepcopy(self._imaging_profile)
 
    def checkout_protocol(self) -> Protocol:
        """
        Generate a deepcopy of protocol runtime object

        :return: deepcopy of protocol runtime object
        :rtype: Protocol
        """
        return copy.deepcopy(self._protocol)
    
    def checkout_experiment(self) -> Experiment:
        """
        Generate a deepcopy of protocol runtime object 

        :return: deepcopy of experiment runtime object
        :rtype: Experiment
        """
        return copy.deepcopy(self._experiment)

    def checkout_icb(self) -> ICB:
        """
        Generate a deepcopy of icb runtime object

        :return: deepcopy of icb runtime object
        :rtype: ICB
        """
        return copy.deepcopy(self._icb)
```
As opposed to a factory:
```py
RuntimeModel = Union[ICB, Experiment, Device, Protocol, ImagingProfile]
T = TypeVar('T', bound=RuntimeModel)
def checkout(self, ref_type:Type[T]) -> T:
   if ref_type is ImagingProfile: return copy.deepcopy(self._imaging_profile)
   elif type(ref_type) is Device: return copy.deepcopy(self._device)
   ...
```
Maybe this is not "best practice" as it relates to programming paradigms but I would want to know why that is the case.

**Comment by erictraut** [comment]
I think your current code is much better than the combined generic method. I understand the desire to reduce code duplication, but you're not really saving any code. You're simply jamming together the functionality of multiple functions that arguably should be separate. Plus, it's an abuse of generics because your function isn't really operating in a generic manner here.

It's analogous to replacing this:

```python
def add(a: float, b: float):
    return a + b

def subtract(a: float, b: float):
    return a - b
```

with this:

```python
def do_stuff(func_name: str, *args, **kwargs):
    if func_name == 'add':
      return args[0] + arg[1]
    elif func_name == 'subtract':
      return args[0] - arg[1]
```

**Comment by cSDes1gn** [comment]
The more I think about it the more it makes sense to me. Functions should be less generalized. Thanks!
