### ISSUE TITLE
Support numbered lists in Python docs

### ISSUE THREAD

**Issue by JulianOrteil** [microsoft/pylance-release#1305]
## Environment data

-   VS Code version: 1.56.2
-   Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS and version: Win10, x64
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8; anaconda env
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: all
-   Relevant/affected Python-related VS Code extensions and their versions: python
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

The recent improvements to this extension's ability (if it is this extension) to process Python docs is quite commendable. Thank you for your hard work in bringing it up to speed. But, as expected I'm sure, there are still areas for improvement. My issue highlights one such area.

I am attempting to create a numbered list inside of the doc string for readability. However, when hovering over the documented object (like a class or function), the below is what I get. It clearly defeats my use of the list inside the doc.

I expect the doc to look similar to how I wrote it: nicely tabbed list contents.

## Actual behaviour

![image](https://user-images.githubusercontent.com/23083317/118526369-c7383080-b705-11eb-8dd3-749a0ebc7401.png)

As you can see, the sub list items are clearly tabbed correctly; but the entry-level list items are not (the `1.`, `2.`, and `3.` items).
Also, when adding sub lists to, for example, item `1.` here, it gets even more confusing.

![image](https://user-images.githubusercontent.com/23083317/118527262-bcca6680-b706-11eb-9282-90834a3d0ea6.png)

## Steps to reproduce:

1. Just paste the below code into a file for Python and hover over it with the mouse.

```python
class GenericClass(object):
    """Here is a python doc string.

    Below I will create a list:
        1. This is item one
        2. This is item two; but because I want to include more
        information, this item will be multiline.
        3. This is item number three.
            a. Here is even more information on item three.
                i. Is this sort of tabbed-doc comprehension possible?
    """
```

**Comment by bschnurr** [comment]
thanks for the issue. Currently its related to indented lists
as a workaround you could decrease the indent for now.

![image](https://user-images.githubusercontent.com/1946977/118868222-cb488780-b898-11eb-8179-0d570e77e689.png)


```
class GenericClass(object):
    """Here is a python doc string.

    Below I will create a list:
    1. This is item one
    2. This is item two; but because I want to include more
    information, this item will be multiline.
    3. This is item number three.
        a. Here is even more information on item three.
            i. Is this sort of tabbed-doc comprehension possible?
    """
```

**Comment by JulianOrteil** [comment]
Forgot to respond and close this. If I remember correctly, the above solution worked. Thanks.
