### ISSUE TITLE
requests module is not able to import on VSCode 

### ISSUE THREAD

**Issue by bharadwajr567** [microsoft/pylance-release#1309]
<h3> Environment data </h3>

-   Language Server version: 2021.5.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

import requests should handle the HTTP requests 
XXX

<h3> Actual behaviour </h3>
**Import "requests" could not be resolved from sourcePylancereportMissingModuleSource**

XXX

<h3> Logs </h3>
Traceback (most recent call last):
  File "/Users/xxx/Desktop/test/test.py", line 36, in <module>
    import requests  
ModuleNotFoundError: No module named 'requests'  
Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>
import csv 
import requests  

csv_url = "http://samplecsvs.s3.amazonaws.com/Sacramentorealestatetransactions.csv"

with requests.Session() as s :
    download = s.get(csv_url)
    
    decode_content = download.content.decode('utf-8')
    
    cr = csv.reader(decode_content.splitlines(), delimiter= ',')
    my_list = list(cr)
    for row in my_list:
        print(row)

Additional information - 

**requests module binary  is already installed/satisfied by pip3** 
log - Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from requests) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests) (2020.12.5)                                                            ```python
XXX
```

**Comment by jakebailey** [comment]
Both Pylance and the runtime interpreter report that the module cannot be found. Are you certain that the interpreter you've selected at the bottom left of your VS Code window is the interpreter where you have installed `requests`?

**Comment by bharadwajr567** [comment]
Yes, the requests module is already been installed. let me send you some more info.
```pip3 install requests
Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/site-packages (from requests) (4.0.0)  ```

**Comment by jakebailey** [comment]
Yes, I can see that in the logs, but I am mainly asking about the actual selected interpreter. Our trace logs (which our issue template asks for) will also print that info, but you haven't included it.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by bharadwajr567** [comment]
Gotcha.. I will include the trace logs.

**Comment by jessefogarty** [comment]
I have been having the same odd issue. Some modules its fine importing others it doesn't like seemingly without reason.

To answer the two common replies 1) extrapaths 2) select the right interpreter. Both tried both having fixed it.

**Comment by jakebailey** [comment]
It's been over a month since we asked for the logs; I'm going to close this. If you can provide some logs, we can reopen and take a look.
