### ISSUE TITLE
Setting 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/pylance-release#1310]
## Environment data

-   Language Server version: v2021.5.2
-   OS and version: Windows_NT x64 10.0.19043
-   Python version (& distribution if applicable, e.g. Anaconda): v2021.6.854437722-dev

## Expected behaviour

Editor highlights in a notebook cell should reflect only instances in the current cell. 

## Actual behaviour

1. Set "python.languageServer": "Pylance"
1. Create a notebook with >=2 cells with text in them, e.g. 
```python
import pandas as pd 
df = pd.read_csv('foobar')
```
and
```python
pd.read_clipboard()
```

1. Highlight `pd` in the first cell. A highlight corresponding to the column start and end of `pd` in the __second__ cell is also applied to the first cell editor:
![recording (1)](https://user-images.githubusercontent.com/30305945/118850043-325c4100-b885-11eb-83dc-e9ac4db25405.gif)

1. Set "python.languageServer": "Jedi"
1. Ghost highlights go away

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
I'm pretty sure this is expected; we answer the document highlight call with the other uses of that variable. I'd honestly be surprised if we didn't highlight the same variable in multiple cells; what's the rationale for not doing so?

**Comment by joyceerhl** [comment]
Oops, sorry, not sure how this got created (dupe of #1311)
