### ISSUE TITLE
No intellisense when one argument is type hinted

### ISSUE THREAD

**Issue by tombohub** [microsoft/pylance-release#1313]
## Issue

If one argument of the __init__ is type hinted it doesn't offer autocomplete

## Environment data

pylance - v2021.5.2

Language Server version: v2021.5.2
OS and version: Win10, WSL1
Python version (& distribution if applicable, e.g. Anaconda): 3.8 Miniconda, using .venv

## Expected behaviour

To offer autocomplete of object attributes

## Actual behaviour

Not offering autocomplete of object attributes

## Logs

No logs

## Code Snippet / Additional information

```python

@dataclass
class D:
    ko: str = 'koko'
    lo: str = 'lolo'

class A:
    def __init__(self, name, columns) -> None:
        self.name = name
        self.columns = columns

class B:
    def __init__(self, name: str, columns) -> None:
        self.name = name
        self.columns = columns
        
a = A('name', D())
b = B('name', D())
```

Offering autocomplete:
![1](https://user-images.githubusercontent.com/3029412/118880607-0ad69a00-b8c0-11eb-99cb-db61ee8a4d65.png)

No autocomplete:

![2](https://user-images.githubusercontent.com/3029412/118880635-13c76b80-b8c0-11eb-8dec-93b067e3d402.png)

**Comment by jakebailey** [comment]
This is currently intended behavior; for unannotated functions, we will evaluate the function at each call site with the specific types for that call. But, the moment you add a type hint to the function, we assume you're going to fully type the function and no longer perform this analysis.

Is there a reason to only annotate one of the parameters?

**Comment by tombohub** [comment]
> This is currently intended behavior; for unannotated functions, we will evaluate the function at each call site with the specific types for that call. But, the moment you add a type hint to the function, we assume you're going to fully type the function and no longer perform this analysis.
> 
> Is there a reason to only annotate one of the parameters?

Ok, thanks.

Yes because that `self.columns` I am trying to create is actually a dataclass with database and dataframe columns inside. 
Like the `class D` in code I provided. My goal is to have intellisense for columns, 

```python
f"SELECT {prices.columns.close} FROM {prices}" -> SELECT `prices`.close FROM `prices`
```
but I can't annotate the `columns` parameter because I won't to use different dataclasses each time to create columns.

**Comment by jakebailey** [comment]
I'm not sure if this is what you want, but this seems like a good place for a generic container:

```python
from typing import Generic, TypeVar

_T = TypeVar('_T')

class A(Generic[_T]):
    def __init__(self, name: str, columns: _T) -> None:
        self.name = name
        self.columns = columns

b = A('name', D())
reveal_type(b.columns)  # D
```

**Comment by tombohub** [comment]
That works!

for some reason I thought I would need to do
```python
a = A[D]('name', D())
```

but I was wrong, thank you Sir!

**Comment by jakebailey** [comment]
No, that's what inferencing is for. 🙂

**Comment by tombohub** [comment]
> No, that's what inferencing is for. 🙂

Is that because of pylance or that's how python usually works?

**Comment by jakebailey** [comment]
Pylance; we know that when you pass `D()` that `_T` will be `D` for that instance of `A`, so you don't need to explicitly say what kind of `A` you're making. The context is enough.

At runtime, none of these type annotations actually do anything.

**Comment by tombohub** [comment]
That's great, thank you for your hard work!
