### ISSUE TITLE
Type hint of the constructor of an indeterminate type should remain `(*args: Any, **kwargs: Any) -> Any`

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1316]
## Environment data

-   Language Server version: 2021.5.3
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample

Copied from my reply in #1303:

```python
from typing import Type

class Base:
    def __init__(self, i: int):
        ...

class Derived(Base):
    def __init__(self, s: str):
        ...

def get_cls() -> Type[Base]:
    return Derived

cls = get_cls()  # Implied type: Type[Base].
_ = cls(i=0)  # No warning from pylance, but met ValueError in runtime.
_ = cls(s="a")  # Runnable, but got a warning from pylance.
```

## Expected behavior

The signature of `cls(...)` should remain `(*args: Any, **kwargs: Any) -> Any` and there should be no warnings in the last two lines.

## Actual behavior

Like in the comments.

## Explanation

A type conforming to `Type[X]` is not necessarily the type `X` itself. It can also be any subclass of `X`.

The constructor is not necessarily inherited, so there is no guarantee that the constructor of a child class is compatible to the constructor of its parent.

Therefore, assuming there is `XLike` conforming to `Type[X]`, it's not safe to call `XLike(...)` using the same signature of `X(...)`.

While it should be discouraged to call a constructor on an indeterminate type, there is still practical value in such usage. So I think it's OK for the language server to loosen the checks and leave the potential errors to the runtime.

## Alternative

Assuming there is `XLike` conforming to `Type[X]`, the signature of `XLike`'s constructor can be `(*args: Any, **kwargs: Any) -> X` because type of the result is always a subclass of `X` ( `X` itself included ). It can help to restrict further type casts.

**Comment by Azureblade3808** [comment]
As #1303 has been closed as fixed, I'm making this a new issue.

**Comment by erictraut** [comment]
I think the current behavior is preferable (provides more value) than the change you are suggesting. The current behavior is also consistent with the way mypy handles this case.

**Comment by Azureblade3808** [comment]
I checked again, and found that current behavior is a bit different from what I thought.

The constructor on the indeterminate type always accepts pure dynamic inputs like `*args, **kwargs`, so pure dynamic calls would not trigger warnings. As for calling the constructor with a different signature from a subclass, the usage itself should be discouraged so it doesn't really matter.

Therefore, I agree that current behavior is good.
