### ISSUE TITLE
The third argument in `numpy.ndarray.__pow__()` should be optional

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1317]
## Environment data

-   Language Server version: 2021.5.3
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample

```python
import numpy as np

a: np.ndarray = np.array([])
b = a ** 2  # Operator ** not supported for types "ndarray" and "Literal[2]".
```

## Expected behavior

No warning.

## Actual behavior

See comment in sample.

## Suggestion

File: ".../dist/bundled/native-stubs/numpy/core/_multiarray_umath.pyi"
Line: 1258

Replace
```python
def __pow__(self, value, mod) -> ndarray:
```
with
```python
def __pow__(self, value, mod=...) -> ndarray:
```

**Comment by jakebailey** [comment]
What version of numpy are you using? These stubs are generated from the compiled modules and are not intended to be used in type checking, only to provide extra completions and docstrings. If you are using the most recent version of numpy, their types should take precedence.

**Comment by Azureblade3808** [comment]
I'm using numpy v1.19.2. I'll try an update.

**Comment by jakebailey** [comment]
Yeah, you definitely do not want to be type checking with numpy before 1.20. 1.21 should have many many more typing improvements.

**Comment by Azureblade3808** [comment]
Thank you for the info. With the new version of 1.20.1, the typing is far better now.
