### ISSUE TITLE
Built-in member is considered undefined if there is a variable of the same name in the global scope

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1320]
## Environment data

-   Language Server version: 2021.5.3
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample

```python
max_ = max
max = lambda a, b: a if a > b else b
```

## Expected behavior

The usage is valid.

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/118955379-3b3a3900-b991-11eb-84d5-f3df9c56e62a.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This bug was introduced recently as part of another bug fix, and it slipped past our regression tests. I've fixed the problem and added more tests so it doesn't regress in the future. A fix will be included in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.4, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202154-26-may-2021
