### ISSUE TITLE
Function with potentially multiple return types not inferred properly

### ISSUE THREAD

**Issue by k0aaa** [microsoft/pylance-release#1322]
## Environment data

-   Language Server version: v2021.5.3
-   OS and version: Windows 10 Pro 20H2
-   Python version: 3.8.4

## Expected behaviour

scipy.linalg.lu returns either the decomposition in form `(P, L, U)` or `(PL, U)` depending on an input parameter.

The return type is hence either 2-tuple or 3-tuple (of ndarray).

## Actual behaviour

Pylance, despite being able to type the return value as `(tuple[Unknown, Unknown] | tuple[Unknown, Unknown, Unknown])`, still recognizes solely the 2-tuple as return type, and gives the following error:

`Tuple size mismatch: expected 3 but received 2 Pylance reportGeneralTypeIssues`

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
import numpy as np
import scipy.linalg as linalg

dimN = 6

matA = np.random.rand(dimN, dimN)

(matP3, matL3, matU3) = linalg.lu(matA1) # pylance reports error
```

**Comment by jakebailey** [comment]
Unless `scipy.linalg` is type annotated, I don't think you're going to have a good experience type checking with it.

Note that `tuple[Unknown, Unknown] | tuple[Unknown, Unknown, Unknown]` is a union of two types; we are saying that one of them can't be assigned to a three-tuple, which is true. If the function returns a two-tuple, then it will fail at runtime.

**Comment by jakebailey** [comment]
A function's signature is defined by the function body itself, not how it's used. Unpacking it into a tuple of a specific size doesn't then propagate that information down to the function; how you use a function doesn't change its definition. The function needs to define its API so that type checking can use that info.

For this behavior to be possible and reasonable when type checking is enabled, the function really needs to be annotated with overloads that indicate that when `coef` is false, you get a 2-tuple of some sort, or a 3-tuple when true.

**Comment by erictraut** [comment]
Pyright (the type checker that underlies pylance) will do its best to infer the return type of an unannotated function. The result is typically good enough for completion suggestions, but often falls short for type checking. If you want to enable type checking for your code, you need high-quality type annotations for the libraries that your code imports. 

In this particular example, the function appears to be polymorphic — i.e. its return type varies depending on the input parameter types and values. Polymorphism can be expressed using overload annotations, as Jake mentioned. But it is beyond the capabilities of pyright (or any type checker in any language that I'm aware of) to infer polymorphic overloads.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
