### ISSUE TITLE
Add descriptions to python.analysis.typeCheckingMode setting

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#1324]
Hey folks!

Very simple feature request here 😂

We're trying to add a descriptions to our settings who have enums, and we bumped into this feature request as we were talking about it. I think it'd be nice if we could add descriptions to each of the possible values of the python.analysis.typeCheckingMode setting, like we do for the language server ones now 😊

**Comment by savannahostrowski** [comment]
We forgot to close this. Descriptions for the type checking modes enums were added and are in the latest version of Pylance!

![image](https://user-images.githubusercontent.com/8949415/122603103-bb070200-d028-11eb-9215-1fa56f2c75dd.png)
