### ISSUE TITLE
Expected class type but received "type" | make_dataclass

### ISSUE THREAD

**Issue by danstewart** [microsoft/pylance-release#1327]
## Environment data

-   Language Server version: v2021.5.4-pre.1
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

When using `make_dataclass` I would expect the variable could be used for type hints.

## Actual behaviour

These errors are displayed:
* 'Expected class type but received "type"' is displayed
* 'Illegal type annotation: variable not allowed unless it is a type alias'

## Code Snippet / Additional information

```python
from dataclasses import make_dataclass, dataclass

MyDataClass = make_dataclass('MyDataClass', ['field1', 'field2', 'field3'])

@dataclass
class MyOtherDataClass:
    field1: int
    field2: int
    field3: int

def some_func() -> MyDataClass:
    return MyDataClass(1,2,3)

def some_other_func() -> MyOtherDataClass:
    return MyOtherDataClass(1,2,3)

```

![image](https://user-images.githubusercontent.com/10670565/119154947-308bac80-ba42-11eb-9e77-0a932061982d.png)

**Comment by erictraut** [comment]
Pylance does not support `make_dataclass`. If you're interested in using static type checking, you should use the class form:

```python
@dataclass
class MyDataClass:
    field1: int
    field2: int
    field3: int
```

The only reason to use `make_dataclass` is if the parameters are dynamic, and in that case a static type checker wouldn't be able to reason about them anyway.

Mypy (another popular Python type checker) also does not support `make_dataclass` for the same reason, and it reports the same error that you're seeing with pylance.

**Comment by danstewart** [comment]
Ok, thanks for the info :+1:
