### ISSUE TITLE
Pylance reportMissingImports

### ISSUE THREAD

**Issue by CrisVl** [microsoft/pylance-release#1331]
Same code works in Ubuntu or Windows.

When I code in wsl pylance does not recognizes path

a -> package

 -b -> module inside b

c module -> same level as a where I need to import b

from a import b
```
{
  c code
}
```
I did this in settings.json
```
{
    "python.pythonPath": "/usr/bin/python3",
    "python.analysis.extraPaths": ["a"]
}
```

a is underlined with reportMissingImports

Any advice to fix this in wsl?

**Comment by sanskarbtw** [comment]
- Python Version: 3.9.5
- Pylance Version: 2021.5.3

This unfortunately doesn't work for me on Windows.
Importing a file into another while in the same directory underlines the filename being imported with:
```
Import "somefile" could not be resolved Pylance (reportMissingImports)
```
Despite this, the code compiles and runs perfectly.

**Comment by judej** [comment]
Thanks for the report, would you please provide logs so that we can see what your project is.

Here is the [troubleshooting info](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md). Please review the section on unresolved import. Also, the link has instructions for creating logs

**Comment by henshalb** [comment]
For me too. Need to fix this soon. Not working in WSL 2. But the code runs perfectly.

**Comment by jakebailey** [comment]
Logs and a folder layout are critical to us being able to identify the problem. Without that, we don't have any info as to why extraPaths isn't working.

**Comment by CrisVl** [comment]
Could you define logs?

When I hover over the import `from a import b` VS simply gives me a warning that the path is not found.
It is also underlined.

I think it is simple enough to test it yourself?

Would you like me to give you a screen shot?

**Comment by jakebailey** [comment]
No, I have not; you haven't provided enough info about your layout and which folder you're opening, nor the logs.

The logs we are looking for are the "Python Language Server" logs, e.g. the output of:

![image](https://user-images.githubusercontent.com/5341706/119701564-52ea4500-be09-11eb-9031-dc5e101a707f.png)

When trace mode is enabled: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
Note that we have a section in our troubleshooting doc about unresolved imports; have you tried extraPaths as is suggested? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings

**Comment by jakebailey** [comment]
Forgive me, you have tried extraPaths.

You don't want to add `"a"` as an extraPath if `a` is what you want to import. extraPath marks import roots, so the folder to add is the _parent_ folder of `a`.

A screenshot of your folder layout in the file explorer would probably help, yeah.

**Comment by StevenLi-DS** [comment]
Is there any way to disable this `reportMissingImports`?

**Comment by jakebailey** [comment]
Sure, you can use a diagnostic severity override or a `# type: ignore` comment, but I wouldn't recommend that; we'd much rather get the info to take a look into why extraPaths or the heuristic are not working.

**Comment by Sarwar242** [comment]
![Screenshot 2021-06-03 094802](https://user-images.githubusercontent.com/33449635/120583911-df6fb580-c450-11eb-829f-cf5bbb312563.png)
Why this warning? This is a very common case of importing from another app in Django. If this shows warnings then what is the use of the plugin?

**Comment by jakebailey** [comment]
@Sarwar242 See https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings, or try out our WIP solution here: https://github.com/microsoft/pylance-release/issues/68#issuecomment-811618343

**Comment by CrisVl** [comment]
thank you all for your comments. 

a joke: when stuff like this happens one could ignore it, buy a Mac or just create another meme on Microsoft :dagger: 

or get a job that comes with a Mac and don't give it away for a bit more money.

**Comment by jakebailey** [comment]
Without more info (logs, a reproduction that doesn't work when the heuristic is on, etc), we cant really do more here.
