### ISSUE TITLE
Cannot fine valid import

### ISSUE THREAD

**Issue by abrarlabib-code** [microsoft/pylance-release#1332]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.2

## Expected behaviour

Pylance should not show error in valid code.

## Actual behaviour

Pylance cannot find folder in the same directory. For Eg in the same directory, I have mysite(folder) and register(folder) in the same directory mysite (currently I am working with Django). My code is:
`from register import views as v`   
but Pylance can not access and showing error.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
There is a duplicate issue for this. Please review [comment in issue 68](https://github.com/microsoft/pylance-release/issues/68#issuecomment-811618343)
