### ISSUE TITLE
About Pylance restricting a type annotation from Any to Unknown

### ISSUE THREAD

**Issue by Questionsdenombres** [microsoft/pylance-release#1333]
## Environment data

python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) - distribution from https://www.python.org/downloads/
Windows-10-10.0.18363-SP0
Visual Code Studio: 1.56.2
extension python: v2021.5.842923320
extension pylance v2021.5.3
type checking mode: strict

## Actual and expected behaviour
See code examples below.

**test1**: As expected pylance restricts `x` from `Any` to `Sequence`.
The puzzling point is that the new type is `Sequence[Unknown]` not `Sequence[Any]`.

Sometimes typing doesn't fit with the python dynamic behavior I want to use.
So a volunteer Any is a way to obscure the type of the variable to pylance.
Therefore it is a bit annoying when pylance restricts from `Any` to `Unknown`. 
And this, since especially, after I read that pylance will not implement the `@no_type_check` decorator.
https://docs.python.org/3/library/typing.html#typing.no_type_check

Question: Is it a deliberate choice to reinsert `Unknown` where the programmer explicitly requests for `Any` ?

Following test2 and test3 are solutions to remove pylance reports in such a situation.

**test2**: (bug)
This looks a good and very readable solution.
pylance seems to work perfectly, `x` is restricted to `Sequence[Any]`, and no issue is reported. Yeah!
Unfortunately I think that this is a bug!
The reason is that this code fails at execution with `TypeError: isinstance() argument 2 cannot be a parameterized generic`.
I would expect that the static checker reports the problem before execution. Isn't that his role? 

Note: I fully agree with PEP 585 that clearly explains why parametrized generic is not allowed with `isinstance()`.
https://www.python.org/dev/peps/pep-0585/#making-isinstance-obj-list-str-perform-a-check-ignoring-generics

**test3**: (strange?)
This is the solution I use.
I add an harmless code line `x = x` to cast again the variable and expel the `Unknown`.
I prefer this to adding a `# type: ignore`, for the later can just heal single lines.
However, you may actually note that (in test3) `x` is not exactly cast as expected to `Sequence[Any]`, but `x` is cast (back?) to `Any`. Surprising, maybe a side effect or a bug?

**test4**: (working as expected)
Everything is correct when introducing a new variable.
But is it more complex and less readable.

I'm looking forward to reading from you.
Patrick Bourdon.

## Code Snippet
```python
from typing import Any
from collections.abc import Sequence

def test1(x: Any) -> None:
    if isinstance(x, Sequence):
        y = next(iter(x), None) # report: y is partially unknown
        print(str(y)) # report: y is partially unknown
    return

def test2(x: Any) -> None:
    if isinstance(x, Sequence[Any]): # no error reported but execution fails!
        y = next(iter(x), None) # x is Sequence[Any], y is Any
        print(str(y))
    return

def test3(x: Any) -> None:
    if isinstance(x, Sequence):
        x = cast(Sequence[Any], x) # first x is Any, not Sequence[Any] 
        y = next(iter(x), None)
        print(str(y))
    return

def test4(x: Any) -> None:
    if isinstance(x, Sequence):
        z = cast(Sequence[Any], x) # z is correctly Sequence[Any]
        y = next(iter(z), None)
        print(str(y))
    return

X = (1,2)
test1(X)
test3(X)
test4(X)
test2(X) # -> raise TypeError exception```

**Comment by erictraut** [comment]
`Unknown` is a special variant of `Any` and in most cases acts just like an `Any`. So `Sequence[Any]` is largely equivalent to `Sequence[Unknown]`. The difference is that `Unknown` is implicitly generated (for example, when an annotation for a generic class omits a type argument), whereas `Any` comes from an explicit annotation. This allows the type checker to track type information that is unintentionally omitted.

By tracking the difference between `Any` and `Unknown`, the type checker can emit errors if you use an `Unknown`. It does this only when the strictest type checking rules are enabled. If you don't want to use these strict type checking rules, you can leave them disabled. They are off by default. If you're seeing "partially unknown" errors, then you must have enabled these diagnostic checks.

You asked whether it was a deliberate choice to narrow `Any` to some other type. In general, the `Any` type is always left as `Any` and is not narrowed. There is one exception to this rule, and that's specifically with the `isinstance` and `issubclass` conditional check. In this circumstance, type narrowing is applied even if the unnarrowed type is `Any`. We decided that the benefits of type narrowing in this circumstance outweighed the downsides. Mypy (another popular Python type checker) does the same. So does the type checker built into the TypeScript compiler. So this is a common choice among type checkers.

Your code is using `Any` annotations, so I presume that you're not that interested in strict type checking. After all, `Any` effectively "blinds" the type checker from performing any useful type consistency rules. So my recommendation for you is to not use the strict type checking mode. If you stick with "basic" type checking mode, you will not encounter any of these issues.

If you decide to invest heavily in static type checking and want to enable strict type checking modes, then you should look for ways to modify your code to avoid dynamic behaviors that prevent proper static type annotation. My team has made this investment in our large production Python code base, and I'm happy with that decision. But if you value certain dynamic behaviors over static type checking, then you'll probably find that enabling all of the strictest type checking rules isn't feasible. You may want to enable strict mode for only parts of your code base, leaving some type checking rules disabled for the more dynamic parts.

I'll offer one additional workaround that may interest you. It makes use of a type feature documented in [PEP 647](https://www.python.org/dev/peps/pep-0647/) called "user-defined type guards". It was recently ratified and will be included in Python 3.10. It's also available in the `typing_extensions` library and can be used in older versions of Python. It allows you to define custom type narrowing rules based on "type guard functions". Here's how that would look:

```python
from typing_extensions import TypeGuard

def is_sequence(val: Any) -> TypeGuard[Sequence[Any]]:
    return isinstance(val, Sequence)

def test5(x: Any) -> None:
    if is_sequence(x):
        y = next(iter(x), None)
        print(str(y))
    return
```

**Comment by Questionsdenombres** [comment]
I had the strong feeling that this restriction behavior was an intentional choice.
Considering the benefit of strict typing, switching back to the basic mode isn't an option.
I already had read the TypeGuard PEP 646, but at the time it didn't lighten immediate use cases in my context.
Your example is cristal clear. I tested it. 
Thank you.

**Comment by erictraut** [comment]
I just thought of another approach that you could use. I'm providing it here for completeness.

```python
def test6(x: Union[Sequence[Any], Any]) -> None:
    if isinstance(x, Sequence):
        y = next(iter(x), None)
        print(str(y))
    return
```

**Comment by Questionsdenombres** [comment]
Indeed. A bit funny to make a union between two thinks where one includes the other.
