### ISSUE TITLE
reportUndefinedVariable

### ISSUE THREAD

**Issue by sanskarbtw** [microsoft/pylance-release#1334]
## Environment data

-   Language Server version: 2021.5.3
-   OS and version: Windows 10, 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

No errors should be shown as **str** is used for type conversion.

## Actual behaviour
Underlines the keyword **str** with:
```
"str" is not defined Pylance (reportUndefinedVariable)
```

## Code Snippet / Additional information

```py
arith = (str(input("Some input: "))).split()
```

**Comment by Questionsdenombres** [comment]
I wrote your code line as a single line in a test.py script and pylance reports no error.
Note that you can omit `str` in this particular case, since the result type of the `input` function is always `str`
Probably your line is included in something bigger that provokes the error.

**Comment by sanskarbtw** [comment]
Yes indeed, it looks like this error doesn't always arise. Thank You!
