### ISSUE TITLE
Pylance not showing suggestions for OpenCV module

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1335]
## Environment data

-   Python extension version: v2021.6.8646431
-   Pylance version: v2021.5.4-pre.1
-   Language Server version: 
-   OS and version: ubuntu 21.04
-   Python version : 3.9.4 64-bit

## Expected behaviour

showing suggestions like classes, functions, etc.

## Actual behaviour

not showing anything

## Logs

Search paths for /home/arian/Desktop/codes
  /home/arian/.vscode/extensions/ms-python.vscode-pylance-2021.5.4-pre.1/dist/typeshed-fallback/stdlib
  /home/arian/Desktop/codes
  /home/arian/Desktop/codes/typings
  /home/arian/.vscode/extensions/ms-python.vscode-pylance-2021.5.4-pre.1/dist/typeshed-fallback/stubs/...
  /home/arian/.vscode/extensions/ms-python.vscode-pylance-2021.5.4-pre.1/dist/bundled/stubs
  /usr/lib/python3.9
  /usr/lib/python3.9/lib-dynload
  /home/arian/.local/lib/python3.9/site-packages
  /usr/local/lib/python3.9/dist-packages
  /usr/lib/python3/dist-packages
  /usr/lib/python3.9/dist-packages
[Error - 1:22:37 PM] Exception received when installing recursive file system watcher
[Info  - 1:22:37 PM] Searching for source files
[Info  - 1:22:37 PM] Auto-excluding /home/arian/Desktop/codes/Image_Processing
[Info  - 1:22:37 PM] Found 21 source files
[BG(1)] getSemanticTokens delta previousResultId:1621846280326 at /home/arian/Desktop/codes/Image_processing1.py (37ms)
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1621846281362 at /home/arian/Desktop/codes/numpy2.py (3ms)
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze

**Comment by jakebailey** [comment]
Can you provide a code example of something that doesn't work but should? Or a screenshot showing where you're expecting info but are seeing none? As of a few releases ago, we should be shipping a basic stub for cv2.

**Comment by arian47** [comment]
after importing the library and using it, as the snippet below pylance does not show anything about the functions, classes or etc.
`import cv2`
`cv2.`
![Screenshot from 2021-05-25 12-40-38](https://user-images.githubusercontent.com/26442126/119464600-22969e00-bd58-11eb-9eb9-2f88342692f0.png)

**Comment by Python-37** [comment]
Same as numpy, when I want to input `np.asarray`, which is commonly used in my projects, there is not any suggestion; but when I use opencv functions, suggestions will be shown in my computer.

**Comment by bschnurr** [comment]
is this still happening with the latest pylance?
have you tried updating your numpy or opencv packages?

**Comment by arian47** [comment]
packages version were: opencv-contrib-python==4.5.2.52, opencv-python==4.5.2.52, numpy==1.20.3
I updated them to : opencv_python-4.5.2.54, opencv_contrib_python-4.5.2.54, numpy-1.21.0 
the issue seems to be fixed.
the big issue is that on the opencv side the documentation is horrible, it is sad you know a great package with bad documentation!

**Comment by Python-37** [comment]
> packages version were: opencv-contrib-python==4.5.2.52, opencv-python==4.5.2.52, numpy==1.20.3
> I updated them to : opencv_python-4.5.2.54, opencv_contrib_python-4.5.2.54, numpy-1.21.0
> the issue seems to be fixed.
> the big issue is that on the opencv side the documentation is horrible, it is sad you know a great package with bad documentation!

Aye, and so does the trackback information.🤣

**Comment by bschnurr** [comment]
The next release will have a partial stub fix for opencv. this should help with cases where opencv is installed in `dist-packages`
