### ISSUE TITLE
Intellisense not working with OpenCV after update

### ISSUE THREAD

**Issue by Gensight** [microsoft/pylance-release#1339]
When trying to see Visual Studio Code intellisense autocomplete for OpenCV ex: import cv2 I get the word 'Any' after any functions 

Example: Hovering over cv2.rectangle yields rectangle:Any in intellisense window.

Tried changing settings.json to include python.analysis.extraPaths but it did not work. Original setting was python.autoComplete.extraPaths but neither works.
This was working prior to v2021.5.842923320
When I disable Pylance extension in VS Code I do not get any intellisense window at all.
I really need Intellisense for my business coding so any help would be appreciated.

**Comment by judej** [comment]
Possibly similar issue [912](https://github.com/microsoft/pylance-release/issues/912)

**Comment by bschnurr** [comment]
can enable tracing and upload "Python Language Server" logs from the "Output" window. more info here  https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

you shouldn't have to set paths.

after installing opencv you probably have to restart though.

**Comment by heejaechang** [comment]
it should be fixed in 2021.8.2 released today (2021.8.19)
