### ISSUE TITLE
"python.languageSever" or "python.languageServer" ?

### ISSUE THREAD

**Issue by KagamigawaMeguri** [microsoft/pylance-release#134]
That's "Sever" in Quick Start, but i according to that @erictraut said "When you install Pylance, it should pop up a dialog asking you if you'd like to make it the default language server for Python. Click "Yes", and it will update your settings accordingly."  there shows   
"Server", and many issues also said "Server".

**Comment by ly-pa** [comment]
python.languageServer is correct.

I was confused because they made a typo on the Marketplace store page at https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance and called it "sever". I had to change this to get settings.json to reconise it.

**Comment by savannahostrowski** [comment]
The typo was fixed in the README. It will be updated in the marketplace in the next release.
