### ISSUE TITLE
`/` or `*` should not be allowed after `*args` in function signature

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1341]
## Environment data

-   Language Server version: 2021.5.3 / 2021.5.4-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 Anaconda

## Sample

```python
def f(*args, /, x, *, y):
    ...
```

## Expected behavior

Both `/` and `*` get marked as error.

## Actual behavior

No errors/warnings.

**Comment by erictraut** [comment]
Thanks for the feature request. I've added additional checks and corresponding error messages for these cases.

This will be in the next release.

**Comment by Azureblade3808** [comment]
Wow, your speed surprised me.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.4, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202154-26-may-2021
