### ISSUE TITLE
pylance import

### ISSUE THREAD

**Issue by craigmelville** [microsoft/pylance-release#1342]
<h3> Environment data </h3>

-   Language Server version: 2021.5.3
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
You haven't filled out the template, so I'm going to close this. If you can provide the info requested in our template, I can reopen this to take a look, but as it is now, there's nothing actionable.
