### ISSUE TITLE
Autocomplete does not place cursor in the parenthesis

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/pylance-release#1346]
## Environment data

Version: 1.56.0-insider (user setup)
Commit: 5080d21c0b538b996c83fb7b14a746f656eaef15
Date: 2021-04-26T17:23:39.588Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.17134
![image](https://user-images.githubusercontent.com/39871640/116197284-21794d80-a767-11eb-8039-0b590f2e2faf.png)

## Steps to reproduce:
1. Set "python.autocomplete.addBrackets" = true in workspace settings
2. Add "import os" to python file

## Expected behaviour
1. Write "os.getc", you'll see autocomplete for os.getcwd, selecting it, ensure:
	a. Auto-complete adds os.getcwd() to the source code and place the cursor inside the parentheses
2. If this setting is false, only os.getcwd is added to the file

## Actual behaviour
**actual1 setting:**
![image](https://user-images.githubusercontent.com/39871640/116197953-f3483d80-a767-11eb-8e68-db2352bdc063.png)
1. Write "os.getc", Auto-complete adds os.getcwd() to the source code, but the cursor does not place inside the parentheses, the cursor place after the parentheses.
![image](https://user-images.githubusercontent.com/39871640/116198242-4d490300-a768-11eb-85f0-5cd1dc0301c3.png)

**actual2 setting:**
![image](https://user-images.githubusercontent.com/39871640/116198730-e8da7380-a768-11eb-929b-aee788e7fb1e.png)
2. When setting "python.autocomplete.addBrackets" = false, os.getcwd() is added to the file not os.getcwd.

**Comment by jakebailey** [comment]
`python.autocomplete.addBracket` is an old setting that Pylance doesn't respect; we should have automatically migrated your setting to `python.analysis.completeFunctionParens`; can you check using that setting instead?

**Comment by zhouwangyang** [comment]
@jakebailey thanks, it works now.
