### ISSUE TITLE
Missing docstings for stdlib decimal module

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1350]
## Environment data

-   Language Server version: 2021.5.4-pre.1
-   OS and version: ubuntu 21.04
-   Python version: 3.9.4 64-bit

## Expected behaviour

pylance showing the docstring of the builtin decimal module's functions

## Actual behaviour

not showing docstrings which are available in the pythons website in the documentation section about the library

## Code Snippet / Additional information

`from decimal import Decimal`
`Decimal(3.14).min()`
![Screenshot from 2021-05-26 22-59-45](https://user-images.githubusercontent.com/26442126/119712702-1dc80c00-be76-11eb-93e9-c3e652d0ec1e.png)
![Screenshot from 2021-05-26 22-58-01](https://user-images.githubusercontent.com/26442126/119712714-215b9300-be76-11eb-992e-43a392a43fe7.png)

**Comment by jakebailey** [comment]
This is a unique case, as `decimal` is stubbed in typeshed differently than exists in the real code. The real code forwards to the `_decimal` or `_pydecimal` modules, but there's no stub for that. We try and extract info from `decimal.py` but find nothing.

**Comment by jakebailey** [comment]
The next version of Pylance should support decimal's docstrings.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202190-1-september-2021
