### ISSUE TITLE
Series.unique() has some kind of typing issue

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#1353]
Pyright 2021.5.3
```python
import pandas as pd

df = pd.DataFrame([[10, 1, "x"], [20, 0, "z"], [30, 1, "x"]], columns=["a", "b", "xz"])

f = df["xz"]

reveal_type(f)

xzl = f.unique()

reveal_type(xzl)
```

- The type of `f` is reported as `Type of "f" is "Series[Dtype@__getitem__]"`
- The type of `xzl` is reported as `Unknown`

Looking at the type stubs, I can't figure out why `xzl` comes out as `Unknown`, so this might be a pyright issue, not a type stub issue.  I can't find an obvious fix in the type stubs.  The type stubs for `Series` has:
```python
def unique(self) -> np.ndarray: ...
```
so I don't understand why the type of `xzl` is `Unknown`

**Comment by Dr-Irv** [comment]
Well, the issue is that we want to use pandas, and I can't upgrade to numpy 1.20 because pandas doesn't support it yet!

**Comment by Dr-Irv** [comment]
@jakebailey Here is another test that I did on the original example.  I created a brand new environment, just with numpy and pandas.

```
conda create --name barebones python=3.8 
conda activate barebones
conda install numpy=1.20.2
conda install pandas=1.2.4
```
Then tested my example using `pyright` from the command line.
```
(barebones) C:\Code\Misc\pytypes>pyright --version
pyright 1.1.144

(barebones) C:\Code\Misc\pytypes>pyright getitemreset.py
No configuration file found.
No pyproject.toml file found.
stubPath C:\Code\Misc\pytypes\typings is not a valid directory.
Assuming Python platform Windows
Searching for source files
Found 1 source file
C:\Code\Misc\pytypes\getitemreset.py
  C:\Code\Misc\pytypes\getitemreset.py:8:13 - info: Type of "f" is "Unknown"
  C:\Code\Misc\pytypes\getitemreset.py:12:13 - info: Type of "xzl" is "Unknown"
0 errors, 0 warnings, 2 infos
Completed in 0.604sec

(barebones) C:\Code\Misc\pytypes>pyright --lib getitemreset.py
No configuration file found.
No pyproject.toml file found.
stubPath C:\Code\Misc\pytypes\typings is not a valid directory.
Assuming Python platform Windows
Searching for source files
Found 1 source file
C:\Code\Misc\pytypes\getitemreset.py
  C:\Code\Misc\pytypes\getitemreset.py:8:13 - info: Type of "f" is "Series | Any | Unknown | DataFrame | None"
  C:\Code\Misc\pytypes\getitemreset.py:12:13 - info: Type of "xzl" is "ndarray | Unknown | Any"
0 errors, 0 warnings, 2 infos
Completed in 1.888sec
```

So you see that the presence of `--lib` gets the right results, but without `--lib`, the results are incorrect.

As previously mentioned, we would like this to work (and it generally does work fine for pandas) without `--lib` because of other 3rd party libraries that have no type stubs.  I would expect that without `--lib`, `pyright` would still use the `numpy` stubs that are installed and the `pandas` stubbed shipped inside of `pylance` .

Finally, for the next thing that is confusing, consider this simple example:
```python
import pandas as pd

s = pd.Series([1,2,3], name="foo")

reveal_type(s.name)
```

Inside VSC, the `reveal_type(s.name)` shows `Type of "s.name" is "Hashable | None"`

But the command lines (with `--lib`) shows:
```
(barebones) C:\Code\Misc\pytypes>pyright --lib sname.py
No configuration file found.
No pyproject.toml file found.
stubPath C:\Code\Misc\pytypes\typings is not a valid directory.
Assuming Python platform Windows
Searching for source files
Found 1 source file
C:\Code\Misc\pytypes\sname.py
  C:\Code\Misc\pytypes\sname.py:5:13 - info: Type of "s.name" is "Label"
0 errors, 0 warnings, 1 info
Completed in 1.246sec
```

Where is the command line version of pyright coming up with `Label` ?  It's as if it picked up some different set of stubs for pandas.

**Comment by jakebailey** [comment]
Without `--lib`, pyright will not use third party projects at all unless they are stubbed or py.typed. Pandas is neither of those, so requires `--lib` to run to get any types.

Pylance ships pandas stubs, those from python-type-stubs. To make use of those in pyright, they would need to be copied into `typings` so that pyright uses those before pandas own builtins (or get anything without `--lib`).

Pylance includes an extra mechanism that Pyright does not: "native stubs", which apply only when we are analyzing a library and the module is detected to be compiled. The stub content is then used as though it were the source code for the compiled module. This helps support getting some basic type info in numpy <1.20, but just docs in 1.20+ as types are provided in their stubs. You can technically achieve some of this with partial stubs, but because numpy 1.20+ is `py.typed`, partial stubs don't work in that instance.

**Comment by Dr-Irv** [comment]
So is the meaning of "Use library implementations to extract type information when type stub is not present" in the VSC/pylance context (which uses pyright under the hood) different because in VSC/pylance, the pandas stubs from `python-type-stubs` will get used, versus the command line `--lib` argument will cause nothing to be inferred about `pandas`  (unless you put something in the `typings` directory)?

If that's the case, then why does command line `pyright` show that `s.name` is `Label` in the example above?  I would have expected it to say `Unknown`.   It has to be doing some kind of type inference from somewhere.

**Comment by jakebailey** [comment]
Almost; with `--lib`, pyright will try and analyze pandas itself, even though it isn't py.typed. They have some partial type information, so you're seeing that. That info may differ from our stubs, as the stubs haven't been upstreamed in any way (not sure what happened to that effort on their side).

**Comment by Dr-Irv** [comment]
> That info may differ from our stubs, as the stubs haven't been upstreamed in any way (not sure what happened to that effort on their side).

I'm on the core team.  We're slowly working on introducing types into the pandas source.  Then we can eventually have `pyi` files shipped with pandas, but that might take some time.

**Comment by jakebailey** [comment]
Well, inlining them is the best method, of course. But, somewhere is better than nowhere. 🙂

**Comment by jakebailey** [comment]
The behavior in https://github.com/microsoft/pylance-release/issues/1353#issuecomment-848370763 needs to be looked at, though.

**Comment by rchiodo** [comment]
I believe this is all working now if you have the latest of pylance, numpy, and pandas.
