### ISSUE TITLE
Clearing fingerprint cache

### ISSUE THREAD

**Issue by Fatsie** [microsoft/pylance-release#1357]
Question
========
Is there a way to clear Pylance fingerprint cache after a python module is updated with pip install ?

Background
=========
Pylance seems to cache fingerprints of class methods and function of python modules. After I upgrade a local module with `pip install .` the cache is not updated, e.g. there is a mismatch with what Pylance thinks is the fingerprint of an updated method and the actual on disk fingerprint.
When I press F12 the installed python file is opened and the method is shown. Hovering over the header gives the right fingerprint of the method. Going back to the code where it is called, still the wrong fingerprint is shown when hovering over the method.
 I don't have the folder with source code of the module added to the workspace and I prefer not to do it as I am using quite some modules.
I am using latest released Pylance version (6.278.279); mostly default Pylance configuration with typeCheckingMode set to basic.

**Comment by Fatsie** [comment]
Doh, copied the number of installations, Pylance version is 2021.5.4

**Comment by jakebailey** [comment]
What is a "fingerprint"? I'm not familiar with that terminology.

Even so, it sounds like you're describing #923, if these dependencies are outside the workspace.

**Comment by Fatsie** [comment]
Sorry, I think signature is the right terminology and not fingerprint.
The problem seen #923 can indeed be causing the same problem as I see. I do see it on Ubuntu 20.04 though. Will document that in that issue and close this one.
