### ISSUE TITLE
Can python.analysis.extraPaths accept absolute file paths?

### ISSUE THREAD

**Issue by predragnikolic** [microsoft/pylance-release#136]
Hello,

Can I use absolute file paths for defining ` python.analysis.extraPaths`?
```json
        "python.analysis.extraPaths": [
            "/home/predrag/.local/lib/python3.7/site-packages",
            "/home/predrag/.config/sublime-text/Packages",
            "/home/predrag/.config/sublime-text/Packages/lsp_utils/st3"
        ],
```

Every issue that I have read here uses relative file paths when declaring ` python.analysis.extraPaths `.

Although I have added the extraPaths(I used absolute file paths). the import statements cannot be resolved for modules defined in those paths.

**Comment by wesleybl** [comment]
@predragnikolic the absolute paths worked for me. I am using the latest version of `Pylance` (2020.7.2). What didn't work was importing packages that are symlinks:

https://github.com/microsoft/pylance-release/issues/131

**Comment by predragnikolic** [comment]
@wesleybl thanks for point it out the version. 
I was using version 2020.7.1. Upgrading to 2020.7.2 fixes it :)
