### ISSUE TITLE
'Unknown' type generated for __getitem__ method return in some cases despite fully defined types

### ISSUE THREAD

**Issue by smithed180** [microsoft/pylance-release#1361]
<h3> Environment data </h3>

-   Language Server version: 2021.5.5-pre.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda):  3.9.5 x64
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

assert isinstance(x, y) should narrow the type for x to y

<h3> Actual behaviour </h3>

This does not appear to work anymore. 
I'm confused because this is pretty core, so I even went through and uninstalled/reinstalled pylance, and hit the prompt to reactivate it just to be sure.

<h3> Code Snippet / Additional information </h3>

```python
pin1 = J1['1']
assert isinstance(pin1, ConnectorPin)
print(pin1)

if isinstance(pin1, ConnectorPin):
    print(pin1)
```
What I get when I hover over all three instances of pin1 is always this, and it freely hints and colorizes properties which do not apply (for example a property that only exists on ItemBase shows up even though a ConnectorPin is not part of the same hierarchy as ItemBase).
![image](https://user-images.githubusercontent.com/53264791/119901737-43a3ee00-bf14-11eb-96a3-cedde700c637.png)

Again, I realize this seems absurd but I did reinstall and I know its worked in the past, so pretty confused.
Thanks

**Comment by smithed180** [comment]
I don't have a minimal example, but thanks for your questions -- it looks like the Unknown may have been a key factor. I now have it identifying the type right, so its definitely *not* the isinstance directly, but instead appears to be something to do with overriding `__getitem__` and the unknown.

The change I did was replace the source for the pin variable with the actual method. in other words from this:
`pin1 = J1['1']`
to this:
`pin1 = J1.getPin('1')`

In this case the code of `__getitem__` is:
```
    def __getitem__(self, value: str) -> Optional[ConnectorPin]:
        return self.getPin(value)
```
In the first case (`__getitem__`), the pin1 variable is marked as: `ConnectorPin | Unknown | None`
In the second case (`getPin`) the pin1 variable is marked as `ConnectorPin | None`

So it looks like two things are happening:

- Overriding `__getitem__` does not have the same type implications as the underlying method, and an `Unknown` option is added to a method which claims to return a specific Optional class.
- Asserting an item marked with `Unknown` type is in fact a specific type does not seem to force the type

Does this seem reasonable? I don't understand why these things would interact but I'm assuming there is something about the [ ] syntax that I'm missing?

**Comment by erictraut** [comment]
Overriding `__getitem__` should work without generating an `Unknown`. There must be additional circumstances at play here. If you're able to produce a minimal, self-contained repro, I can look into it further.

The type narrowing logic for `isinstance` does not narrow the type of an expression if the unnarrowed type is a union that contains an `Any` or `Unknown` but also includes known types. It will narrow the type if it is an `Any` or `Unknown` by itself (not part of a union). This behavior is the result of feedback and bug reports we received in the past. We could consider changing it, but such changes will likely make other pyright users unhappy.

**Comment by smithed180** [comment]
Ok, makes sense. I will work towards trying to get a more representative sample. Thank you for your assistance.

**Comment by smithed180** [comment]
I can't get this to reproduce anymore, with the same code, so I'm going to go ahead and close this. Thanks for the explanation :)
