### ISSUE TITLE
Pylance while loop bug ?

### ISSUE THREAD

**Issue by ghost** [microsoft/pylance-release#1364]
<h3> Environment data </h3>

-   Language Server version: 2021.5.4
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet / Additional information </h3>

```python
def A() -> str: # fine
    while True:
        return "A"

def B() -> str: # error
    while 1:
        return "B"
```
![image](https://user-images.githubusercontent.com/84806432/120047434-752ac100-bfc9-11eb-8522-08cc65e64907.png)

**Comment by erictraut** [comment]
This is intended behavior. There are certain special expression forms where pylance statically evaluates the value when building the code flow graph. This includes `True`, `False`, `TYPE_CHECKING`, `sys.version_info >= (3, 8)`, and `sys.platform == "win32"`. These special-case expression forms are required for proper evaluation of stdlib type stubs and are defined in PEP 484.

Pylance does not "execute" arbitrary expressions to evaluate their runtime values.

In your sample above, function `A` is using one of these statically-evaluated values (`True`), so the code flow graph takes into account the fact that the `while` loop never executes.

Function `B` doesn't use one of these special forms. From the perspective of the type checker, `B` is equivalent to:
```python
def B() -> str:
    while <some_expression_evaluated_at_runtime>:
        return "B"
```

If your intent is to indicate that it's a while loop that never executes, you can change it to `while True:`, and you'll get the desired behavior from the perspective of the type checker.

Another workaround is to add an explicit `raise` after the while loop.

```python
def B() -> str: # error
    while <expression that you expect will never be falsy at runtime>:
        return "B"
    
    # Should never get here
    raise RuntimeError
```
