### ISSUE TITLE
Reporting an error on bare "raise" outside of "except" is overly restrictive

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#1365]
## Environment data

-   Language Server version: 2021.5.3 (pyright 1f57ad5c)
-   OS and version: macOS 10.15.7
-   Python version: 3.8.6

## Expected behaviour

Pylance should not report an error when a bare raise statement is encountered outside `except`. This is a valid use case, e.g. in error handling functions.

## Actual behaviour

Pylance reports the following error:
`"raise" requires one or more parameters when used outside of except clause`

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/5028956/120074020-76c8b780-c0a3-11eb-849c-2fe965ef3bab.png)

**Comment by matangover** [comment]
P.S. bare `raise` is also valid inside `finally` but Pylance disallows it.

**Comment by erictraut** [comment]
Huh, I thought I read somewhere that a bare `raise` statement can be used only within an `except` clause, but it appears that it can be used anywhere. I've removed this check to eliminate the false positive error.

Thanks for reporting the bug. It will be fixed in the next release.

**Comment by matangover** [comment]
Wow, that was very fast, thanks! Bare `raise` will raise a `RuntimeError` when there is no active exception, and indeed it could be considered invalid in that case. However it is probably difficult to check whether there is an active exception at the time `raise` is executed so I support the removal of this check.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.6.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202160-2-june-2021
