### ISSUE TITLE
getting errors from Pylance while defining function

### ISSUE THREAD

**Issue by geetanshpancholi** [microsoft/pylance-release#1366]
I was defining a function within the definition of another function and I seem to have run into this issue.

![image](https://user-images.githubusercontent.com/78640436/120076657-4d6c5380-c0c4-11eb-871e-9b223943f453.png)

PS - I tried the same thing on replit.com and it does not give any errors.

**Comment by jakebailey** [comment]
This code definitely crashes at runtime. https://glot.io/snippets/fz246s4iu9

**Comment by erictraut** [comment]
Have you tried running that code within the Python interpreter? It results in a runtime error:

```
NameError: name 'efgh' is not defined
```

That's consistent with the error pylance is reporting.

The symbol `efgh` is local to the scope of function `abcd`, and it's not defined outside of that scope.

**Comment by geetanshpancholi** [comment]
right. i'm sorry
