### ISSUE TITLE
Request for type-stubs for pywhatkit and winshell

### ISSUE THREAD

**Issue by CoderLogy** [microsoft/pylance-release#1367]
pls add winshell to py-lance pls and make pylance work like kite , kite does more help on python than pylance pls add more things to pylance
I haveing windows 10 pc pls doit

**Comment by CoderLogy** [comment]
pls also add this pywhatkit

**Comment by judej** [comment]
These modules are not actively maintained. It is unclear what is actually broken in your experience. If you want us to investigate this, could you please use the troubleshooting directions and submit an issue. https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md

Also, Kite is closer to Intellicode. Would you please submit your request there.
