### ISSUE TITLE
Non-existent field doesn't show up in auto-complete but no error/warning is produced

### ISSUE THREAD

**Issue by syagev** [microsoft/pylance-release#137]
## Environment data

-   Language Server version: 2020.7.2
-   OS and version: Win10 (18363)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6

## Expected behaviour

Pylance should flag a non-existent field as error, especially when it seems to be able to correctly parse the variable's type.

## Actual behaviour

According to autocomplete suggestions, Pylance seems to infer the type well. However, even though a non-existent field is specified in code no error/warning is produced.

## Code Snippet / Additional information

![pylance_no_error](https://user-images.githubusercontent.com/5247438/87874725-cc88f980-c9d4-11ea-94ad-ff91460a402b.gif)

I wasn't able to make a minimal reproduction. Can share the code privately if required.

**Comment by erictraut** [comment]
If you want Pyright to report diagnostics for the use of non-existent fields, switch the "python.analysis.typeCheckingMode" from "off" (default) to "basic".
