### ISSUE TITLE
BeeGFS: Exception received when installing recursive file system watcher

### ISSUE THREAD

**Issue by ray8828** [microsoft/pylance-release#1370]
## Environment data

[Info  - 1:37:50 AM] Pylance language server 2021.5.4 (pyright fd334302) starting
[Info  - 1:37:50 AM] Server root directory: /mnt/beegfs/scratch/ray/.vscode-server/extensions/ms-python.vscode-pylance-2021.5.4/dist
[Error - 1:37:52 AM] Exception received when installing recursive file system watcher
[Error - 2:56:27 AM] Exception received when installing recursive file system watcher

## Expected behaviour

The pylance can't start on our slurm cluster

**Comment by erictraut** [comment]
That exception is not fatal. It simply means that we are not able to install a file system watcher, so modifications made to source files in your workspace outside of VS Code will not trigger a reanalysis. 

You mentioned that pylance can't start. What symptoms are you seeing?

**Comment by ray8828** [comment]
The symptoms are: there is no autocompletion or suggestion while required extensions are all installed, can't find the reference etc

**Comment by jakebailey** [comment]
Do you have trace logs? The default log level won't provide much information, hence our template asking for that info (and other sections you've deleted before submitting).

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by ray8828** [comment]
[Info  - 11:01:23 PM] Pylance language server 2021.5.4 (pyright fd334302) starting
[Info  - 11:01:23 PM] Server root directory: /mnt/beegfs/scratch/ray/.vscode-server/extensions/ms-python.vscode-pylance-2021.5.4/dist
[Info  - 11:01:23 PM] No configuration file found.
[Info  - 11:01:23 PM] No pyproject.toml file found.
[Info  - 11:01:23 PM] Setting pythonPath for service "research_1": "/mnt/beegfs/scratch/ray/env/anaconda3/envs/proj1/bin/python"
[Warn  - 11:01:23 PM] stubPath /home/leijh/projects/research_1/typings is not a valid directory.
[Info  - 11:01:24 PM] Assuming Python version 3.6
[Info  - 11:01:24 PM] Assuming Python platform Linux
Search paths for /home/leijh/projects/research_1
  /mnt/beegfs/scratch/ray/.vscode-server/extensions/ms-python.vscode-pylance-2021.5.4/dist/typeshed-fallback/stdlib
  /home/leijh/projects/research_1
  /home/leijh/projects/research_1/typings
  /mnt/beegfs/scratch/ray/.vscode-server/extensions/ms-python.vscode-pylance-2021.5.4/dist/typeshed-fallback/stubs/...
  /mnt/beegfs/scratch/ray/.vscode-server/extensions/ms-python.vscode-pylance-2021.5.4/dist/bundled/stubs
  /mnt/beegfs/scratch/ray/env/anaconda3/envs/proj1/lib/python3.6
  /mnt/beegfs/scratch/ray/env/anaconda3/envs/proj1/lib/python3.6/lib-dynload
  /mnt/beegfs/scratch/ray/env/anaconda3/envs/proj1/lib/python3.6/site-packages
[Error - 11:01:25 PM] Exception received when installing recursive file system watcher
[Info  - 11:01:25 PM] Searching for source files


---

I stuck in the last step: searching for source files

**Comment by ray8828** [comment]
Problem resolved. The reason is my workspace has an extremely huge dataset that stores on a network storage disk, just excluding the dataset will enable pylance to start running.
