### ISSUE TITLE
`reportUnboundVariable` warning in simple if conditions

### ISSUE THREAD

**Issue by sadjadanzabizadeh** [microsoft/pylance-release#1371]
In a code like the one below, pylance fails to realize that the variable cannot be unbound, and produces `reportUnboundVariable` error:

    def test(index, some_list):
        if index > 1:
            some_variable = some_list[-1]

        # some other code

        if index > 1:
            print(some_variable)

Note that the second condition, where the variable is being used, might not necessarily be the same condition, but rather a more strict condition than the first (`index>3` for example)

**Comment by erictraut** [comment]
Yes, this is expected. Static type checkers do not execute the code like an interpreter does. Instead, they track the types of symbols and expressions. 

You can easily work around this limitation by initializing the variable prior to the first conditional.

```python
    some_variable = None
    if index > 1:
        some_variable = some_list[-1]
```

Or if you can disable the `reportUnboundVariable` diagnostic check entirely if you find that it doesn't provide sufficient value for you.
