### ISSUE TITLE
Code snippets are not being auto suggested.

### ISSUE THREAD

**Issue by TomaraPetty** [microsoft/pylance-release#1372]
<h3> Environment data </h3>

-   Language Server version: 2021.5.4
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by Silun** [comment]
I am having the same issue (well, as far as I can tell from the name).

![image](https://user-images.githubusercontent.com/17919060/120186447-cfb75d80-c213-11eb-8e89-662ac5cf9368.png)

VSCode will not suggest code blocks any more, for things like `if` or `try/except`, when it did before.

**Comment by jakebailey** [comment]
These snippets were generated by the Python extension and were removed a number of months ago, see: https://github.com/microsoft/vscode-python/issues/14781, https://github.com/microsoft/vscode-python/issues/15220#issuecomment-767840313

**Comment by Silun** [comment]
Alright, thank you for the info.

**Comment by TomaraPetty** [comment]
That explains it.. Thank you!
