### ISSUE TITLE
Does Not Always Activate

### ISSUE THREAD

**Issue by jbhoffman613** [microsoft/pylance-release#1373]
Issue Type: <b>Bug</b>

Inconsistently, when I open up VSCode, pylance does not automatically turn on. When I close the IDE and then reopen it, it will then be activated. When I go to the extensions to try and manually enable it, it is greyed out, and I cannot activate the extension. 

Extension version: 2021.5.5-pre.1
VS Code version: Code - Insiders 1.57.0-insider (541a5d4fa70ab3095f23b28b88914e1f6a8f65c4, 2021-05-28T10:00:38.762Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 11, 8|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|here1/ --crash-reporter-id 88cd5646-8e9f-4eb2-a69e-216ccc12317b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805cf:30301675
vscextlangct:30310089

```

</details>

**Comment by bschnurr** [comment]
I believe pylance gets triggered when you open a python related file.  Are you opening a python file as well?

**Comment by jbhoffman613** [comment]
Yes. Specifically opening files with a `.py` extension. Also, I always open vscode from the command line using `$ code-insiders <DIR NAME>`

**Comment by judej** [comment]
Do you know if the Python extension is loading? Could you please add the logs to help us get to the root of the problem? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue.

thanks

**Comment by jakebailey** [comment]
It's been about a month since we asked for logs; if you can provide them (or, the Python extension logs or developer tools logs if no "Python Language Server" logs appear), then we can reopen this, but as presented we can't really do anything here.
