### ISSUE TITLE
False positive for reportUnsupportedDunderAll when using tuple

### ISSUE THREAD

**Issue by CarstenLeue** [microsoft/pylance-release#1378]
Pylance all of a sudden reports `reportUnsupportedDunderAll ` if my `__all__` exports are using a tuple instead of a list.

![image](https://user-images.githubusercontent.com/7644517/120343722-3cf0ee80-c2f9-11eb-82c5-37e3a7e4db19.png)

conflicting code:

```python
__all__: Sequence[str] = (
    'create_containers_start_stop_backend'
)
```

code without warning:

```python
__all__: Sequence[str] = [
    'create_containers_start_stop_backend'
]
```

Why would a tuple not be acceptable?

**Comment by erictraut** [comment]
That is not a tuple. It's a single string in parentheses. You need to add a comma to make it a tuple. If you add that, the warning will go away.

**Comment by CarstenLeue** [comment]
you are correct, I am sorry
