### ISSUE TITLE
Extract Method/Extract Variable in the Context Menu are not mapped to Pylance refactorings

### ISSUE THREAD

**Issue by savannahostrowski** [microsoft/pylance-release#1379]
## Environment data

-   Language Server version: 2021.5.4
-   OS and version: Windows
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Expected behaviour

When I open the context menu after highlighting a block of code, the Extract Method/Extract Variable items should be mapped to the Pylance refactorings.

## Actual behaviour

They are not. Upon selection, I see this prompt...which is for Jedi.
![image](https://user-images.githubusercontent.com/8949415/120359133-2ed0ad00-c2bc-11eb-8d8a-0bb04b4281dd.png)
![image](https://user-images.githubusercontent.com/8949415/120359398-76efcf80-c2bc-11eb-8313-d46d309dc1f5.png)

## Logs

Not really applicable

**Comment by savannahostrowski** [comment]
"Refactor..." seems to work as intended (with Pylance refactorings).

**Comment by judej** [comment]
This has been resolved.., Thanks SO :)
