### ISSUE TITLE
pylance not showing docstrings or arguments list of some of the numpy's functions

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1381]
## Environment data

-   Language Server version: 2021.5.5-pre.1
-   OS and version: ubuntu 21.04
-   Python version: 3.9.5 64-bit

## Expected behaviour

pylance to show the docstrings and arguments list of the some of the functions like subtract, also the lintings should not mark this as an object rather its a function (or maybe I'm wrong) 

## Actual behaviour

not showing docsrings nor the function arguments

## Code Snippet / Additional information

`numpy.subtract()`
![Screenshot from 2021-06-02 14-50-35](https://user-images.githubusercontent.com/26442126/120464276-fdd2a400-c3b1-11eb-9918-cec58c89722a.png)
![Screenshot from 2021-06-02 14-46-25](https://user-images.githubusercontent.com/26442126/120464209-ebf10100-c3b1-11eb-8b38-a9a2fb8c2f83.png)

**Comment by judej** [comment]
This will be fixed in the next version of Numpy (v1.22)

**Comment by jakebailey** [comment]
This is already fixed in the version that's released, actually.

![image](https://user-images.githubusercontent.com/5341706/131750449-35f04973-f1d4-4e3b-8d4d-2819d96aed27.png)
