### ISSUE TITLE
Why the Visual Studio Code recognizes `numpy.concatenate` as a variable?!

### ISSUE THREAD

**Issue by SMRHG** [microsoft/pylance-release#1382]
Both `numpy.array` and `numpy.concatenate` are functions in NumPy library, but the Visual Studio Code recognizes `numpy.concatenate` as a variable?!

![9BLIU](https://user-images.githubusercontent.com/59525413/120506702-6bdf9100-c3db-11eb-9c41-348717344081.png)

-   Language Server version: Pylance v2021.5.4
-   OS and version: Windows 10 Pro, version 21H1
-   Python version: Anaconda inside WSL, Python 3.9.1

**Comment by erictraut** [comment]
If you right-click on `concatenate` and choose "Go To Declaration", you will see the reason for this. The numpy library ships with a type stub file (`__init__.pyi`) that provides a type annotation for this symbol, and it is annotated as a variable not a function.

The numpy maintainers are continuing to invest in improved type annotations, so I expect this will improve with upcoming releases of the library.

**Comment by SMRHG** [comment]
> If you right-click on `concatenate` and choose "Go To Declaration", you will see the reason for this. The numpy library ships with a type stub file (`__init__.pyi`) that provides a type annotation for this symbol, and it is annotated as a variable not a function.
> 
> The numpy maintainers are continuing to invest in improved type annotations, so I expect this will improve with upcoming releases of the library.

Thank you for your help
