### ISSUE TITLE
Some completions do not work well on VS 2022.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#1385]
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119935778-9fc14d80-bfba-11eb-9b90-648ebed752de.png)

**Actual result**
1. When I input "ctxt", do not find "Content"
![image](https://user-images.githubusercontent.com/59192491/119936764-43f7c400-bfbc-11eb-874e-960ae978c227.png)
2. Member completions do not appear automatically
![image](https://user-images.githubusercontent.com/59192491/119937418-4dcdf700-bfbd-11eb-9a6d-6a7849fe0fc8.png)

**Comment by ttSpace** [comment]
I also encountered a similar problem. When I selected **Module2**, the previous **print** was replaced.

![something](https://user-images.githubusercontent.com/82852072/132297223-1572f0fd-ab0d-44d2-8a30-cd240c44891c.gif)

**Comment by bschnurr** [comment]
decimal.Context exists, decimal.ctx will bring it up. please file separate issue if they still occur
