### ISSUE TITLE
Pylance doesn't recognize the `__all__` member of the `__future__` module

### ISSUE THREAD

**Issue by MapleCCC** [microsoft/pylance-release#1389]
<h3> Environment data </h3>

-   Language Server version: 2021.6.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): CPython 3.9.0
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Pylance should be able to recognize the `__all__` attribute of the `__future__` module.

<h3> Actual behaviour </h3>

Pylance mistakenly claims that `__all__` is not a known member of the `__future__` module.

<h3> Code Snippet / Additional information </h3>

```python
import __future__

print("What the __future__ module gives us:", __future__.__all__)
```

![image](https://user-images.githubusercontent.com/25131775/120641570-54b9a580-c4a6-11eb-9bd7-deda21ef417f.png)

![image](https://user-images.githubusercontent.com/25131775/120641602-600cd100-c4a6-11eb-8128-f80f0aa4a671.png)

**Comment by erictraut** [comment]
The typeshed stub for `__future__` does not specify an `__all__` attribute. If you think this is in error, please file a bug or create a PR in the [typeshed](https://github.com/python/typeshed) repo. Pylance uses type stubs from this repo for type information in stdlib modules such as `__future__`.

**Comment by MapleCCC** [comment]
@erictraut Thanks for the information. I will open an issue in the upstream typshed repo. I will close this issue here in Pylance.
