### ISSUE TITLE
Unable to infer type of union of sets

### ISSUE THREAD

**Issue by lijunkang12** [microsoft/pylance-release#1391]
## Environment data
-   Language Server version: 2021.6.0
-   OS and version: macOS 11.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

Infer the type of the union of a list of sets of the same type

## Actual behaviour

Type information lost after union

## Logs
```
Type of "union" is partially unknown
  Type of "union" is "(self: set[Unknown], *s: Iterable[Unknown]) -> Set[Unknown]"
```

## Code Snippet / Additional information
```python
bar: list[set[int]] = [{1, 2}, {3, 4}]
foo = set.union(*bar)
```
`foo` should have type `set[int]`.

**Comment by erictraut** [comment]
Pyright (the type checker that underlies pylance) does not currently support the unpacked arguments that map to multiple parameters in the target function. In this case, you're doing something very unusual. You're calling `set.union` as though it were a static method but then using the unpack operator to provide one instance of `set` to the `self` parameter and expecting the remainder to map to the `s` parameter.

Adding support for this very unusual case would add significant complexity to an already very complex and performance-critical part of the type checker. Unless we see evidence that this is a common pattern, I think adding support for this case has more downsides than upsides.

It should be straightforward to work around this limitation.

**Comment by lijunkang12** [comment]
I see. Thanks for your answer! The main problem is that `set.union`, which is not a static method, is the only function that takes an iterable of sets as input and output their unions. Totally agree that support for this case should not be added.

Personally, I use the following workaround which is more symmetric with respect to the inputs:
```Python
foo: set[int] = set()
foo.union(*bar)
```
Thank you again!

**Comment by erictraut** [comment]
I like your solution better than mine. Much easier to read. :)
