### ISSUE TITLE
django-code

### ISSUE THREAD

**Issue by solid-learning** [microsoft/pylance-release#1393]
<h3> Environment data </h3>

-   Language Server version: 2021.6.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
You haven't filled out the template, so there isn't enough information to help you. If you can fill out the template, we can reopen this, but without info we can't really look into anything.
