### ISSUE TITLE
Bundled Django stub does not support custom model managers

### ISSUE THREAD

**Issue by federicobond** [microsoft/pylance-release#14]
## Environment data

- Language Server version: 2020.6.1   
- OS and version: 10.15.5
- Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Expected behaviour

Expected custom Django model manager methods to be recognized.

## Actual behaviour

Pylance types all managers as `Manager[Any] instead of their custom subtype, so it reports:

> Cannot access member "foo" for type "BaseManager[Any]"
  Member "foo" is unknown

## Code Snippet / Additional information

```python
from django.db import models

class MyModelManager(models.Manager):
    def foo(self):
        ...

class MyModel(models.Model):
    ...

    objects = MyModelManager()
```

When using `MyModel.objects.foo()` it reports the error described above.

If this Django stub was sourced from another project, please direct me to it so I can open an issue directly there.

**Comment by yellowjello** [comment]
Why is issue closed? It seems like it's still an issue.

**Comment by federicobond** [comment]
I closed it because it belongs more to the official django-stubs project from which the pylance stubs are taken and there is already ongoing discussion there as to the right approach to address this.

**Comment by yellowjello** [comment]
Wait I think this actually is a Pylance issue. Your example works fine in mypy.

**Comment by psam44** [comment]
IIH, I solved this error with this pattern:
```python
    objects: MyModelManager = MyModelManager()
```

**Comment by arnaldur** [comment]
This is still an issue when chaining manager calls, the first call resolves correctly, but the second call tries to resolve the method on a Queryset object that the manager returns from the methods.

**Comment by joeriddles** [comment]
This is still an issue for me. Here is a small sample that reproduces the issue I am seeing:

```python
from django.db import models


class PostQuerySet(models.QuerySet):

    def cool(self):
        return self.filter(title__ilike="cool")


class Post(models.Model):
    title = models.CharField()
    objects = PostQuerySet.as_manager()


cool_posts = Post.objects.cool()
```

Pylance shows the warning:

> cool: Unknown
Cannot access member "cool" for type "BaseManager[Any]"
  Member "cool" is unknownPylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

![image](https://user-images.githubusercontent.com/19392916/159808916-8c64863b-34d4-423e-8389-873fe799d5ac.png)
![image](https://user-images.githubusercontent.com/19392916/159808952-0c69710b-f32b-4c4b-93fa-e1e20cdae6e6.png)

**Comment by TomsOverBaghdad** [comment]
I'm seeing this issue as well @joeriddles, did you find a solution? I'd prefer to use the QuerySet but might resort to just making the manager

**Comment by joeriddles** [comment]
> I'm seeing this issue as well @joeriddles, did you find a solution? I'd prefer to use the QuerySet but might resort to just making the manager

@TomsOverBaghdad In my original code sample, I was using `.as_manager()` from a custom QuerySet. The solution I use these days is to create a custom Manager that forwards its custom function calls to the custom QuerySet. See below. It's a bit clunky, but it works.

```python
from django.db import models


class PostQuerySet(models.QuerySet):
    def cool(self):
        return self.filter(title__ilike="cool")


class PostManager(models.Manager):
    def get_queryset(self) -> PostQuerySet:
        return PostQuerySet(self.model)

    def cool(self):
        return self.get_queryset().cool()


class Post(models.Model):
    title = models.CharField()
    objects = PostManager()


cool_posts = Post.objects.cool()
```

![image](https://user-images.githubusercontent.com/19392916/224846402-8b9cae1e-a7f2-4cbf-ba5c-2898c60b2ede.png)

**Comment by karolyi** [comment]
This is only a partial solution. As long as you only use your implemented methods this way and don't use any method that of `QuerySet` (that will return a `QuerySet` type), pyright/pylance won't complain.

The moment you try something like `Post.objects.filter(pk__in=[1,2]).cool()`, pyright/pylance will start complaining.

It is not really pyright's issue since it's just following what's defined in django-stubs, but mypy seems to have a kind of a workaround for this problem. I can't tell because I don't use it.

**Comment by rchiodo** [comment]
Mypy works around this problem with a custom extension in django-stubs specifically for mypy. Pyright unfortunately doesn't support such extensions and needs type stubs to work.

**Comment by karolyi** [comment]
Was my comment about an ugly but working solution deleted here ?

**Comment by rchiodo** [comment]
> Was my comment about an ugly but working solution deleted here ?

There was no deletion that I'm aware of. If it was, it might have been by mistake. What was your solution?

**Comment by karolyi** [comment]
You need to override the `objects` variable type with the type that of the queryset, something like:
```python
@final
class _AdvertcontactQueryset(QuerySet['AdvertContact']):
    pass

_AdvertcontactManager = BaseManager['AdvertContact'].from_queryset(
    queryset_class=_AdvertcontactQueryset)

@final
class AdvertContact(Model):
    objects: (  # pyright: ignore[reportIncompatibleVariableOverride]
        _AdvertcontactQueryset
    ) = _AdvertcontactManager()  # pyright: ignore[reportAssignmentType]

```

Looks ugly, is ugly, but it works, the type is that of the queryset anyways:
```python
In [5]: AdvertContact.objects
Out[5]: <django.db.models.manager.BaseManagerFrom_AdvertcontactQueryset at 0x7fc62af4e610>
```

<img width="749" height="353" alt="Image" src="https://github.com/user-attachments/assets/54f711ff-d578-4cf8-b7b2-cd37403b55ad" />
