### ISSUE TITLE
Wrong reportUndefinedVariable for "print(_(..."

### ISSUE THREAD

**Issue by Alpengreis** [microsoft/pylance-release#140]
## Environment data

-   Language Server version: 2020.7.2
-   OS and version: Microsoft Windows 10 Pro x64 [19041.388] [2004] [de-CH]
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.4 x64 (CPython)

## Expected behaviour

The use of "print(_(..." for translatable texts should not produce a warning. The "old" MS Python language server from Python extension 2020.7.94776 does NOT procude a warning.

## Actual behaviour

The use of "print(_(..." for translatable texts produces a warning

![python_trl](https://user-images.githubusercontent.com/11355601/87889715-5667af80-ca33-11ea-9796-d5089cc2ca26.png)
![pylance_error1](https://user-images.githubusercontent.com/11355601/87889706-4fd93800-ca33-11ea-9455-e3eb9d5bebd9.png)
![pylance_error2](https://user-images.githubusercontent.com/11355601/87889714-54055580-ca33-11ea-83de-95d312218991.png)

**Comment by erictraut** [comment]
I'm not familiar with this pattern. Where is the symbol "_" defined? Based on your screen shot, I presume that `_` is a function of some sort. Where is it defined, and how is it imported into the module's namespace?

**Comment by Alpengreis** [comment]
First, thanks for fast reaction!

Ahh, I forgot the import, so this is from the module gettext from the standard bibliotheque:

import gettext

The import is enough, nothing else is required (no need to define the pseudo variable), for infos about please see this links:

https://docs.python.org/3/library/gettext.html?highlight=translation#changing-languages-on-the-fly

and here:

https://docs.python.org/2/library/gettext.html#gettext.NullTranslations.install

the relevant part is this:

![python_doc](https://user-images.githubusercontent.com/11355601/87890379-93817100-ca36-11ea-99bd-1bd4643006a4.png)

PS: I am a newbie in Python (and programming), please forgive, I am somehow wrong! However: I have no problem to use that code with the "old" MS Python Extension, just with Pylance ... the following screenshot is from MS Python language server:
![mspython_noerror](https://user-images.githubusercontent.com/11355601/87890596-81540280-ca37-11ea-8c88-1f236196e4ed.png)

**Comment by erictraut** [comment]
This is a dynamic behavior of a third-party package. Pyright is a static type checker, and it cannot anticipate, nor should it have knowledge of non-standard dynamic behaviors like this. If you are interested in using static type checking, you should avoid libraries that rely on such dynamic behaviors.

Pyright is behaving as designed in this case.

If you wish to continue using this package, you can elect to suppress this particular diagnostic in Pyright.

**Comment by Alpengreis** [comment]
I understand, thanks for help! Then I close now the case ...

**Comment by Alpengreis** [comment]
Two things are still unclear for me, so I reopen this again:

1) The Microsoft Extension for Python is also a static language server, or not? Why there I have no warnings?

2) This use of the dummy/pseudo variable is the normal way for internationalisation (for different/many languages) in Python (in 3.8 and above at least). I know know how I can make excludes but nevertheless: this could be really a problem for MANY developers with program translations (not for modules, there is the technique another). Is there really no way to integrate this common pattern?

**Comment by jakebailey** [comment]
> The Microsoft Extension for Python is also a static language server, or not? Why there I have no warnings?

Do you mean the Python extension: https://github.com/microsoft/vscode-python

This is a general-use extension that offers many things, including environment selection, notebooks, formatting, etc. They manage the language server's lifetime, so they "have an LS" (but it's Pylance). If you mean the old language server, it was a static analyzer, but not a full type checker and had warnings for some some things. By default it runs jedi, which is another static analyzer with its own behaviors.


In django I've seen:

```python
from django.utils.translation import gettext as _
```

Where it's more obvious that this character is a bound variable. `gettext` using magic to dynamically declare `_` without explicitly stating is existence is a shame.

If you write the code in this order, does it work in both cases?

```python
def _(message): return message

import gettext
```

My thought would be that we would statically see `_` as a function, then `gettext` would override the function at import time and be happy.

**Comment by Alpengreis** [comment]
> Do you mean the Python extension: https://github.com/microsoft/vscode-python
 Yes, exactly.

> This is a general-use extension that offers many things, including environment selection, notebooks, formatting, etc. They manage the language server's lifetime, so they "have an LS" (but it's Pylance). If you mean the old language server, it was a static analyzer, but not a full type checker and had warnings for some some things. By default it runs jedi, which is another static analyzer with its own behaviors.
Ok. 

> In django I've seen:
> 
> ```python
> from django.utils.translation import gettext as _
> ```
Unfortunately I can't make an import in similar way in CPython (tried, does not work).

> Where it's more obvious that this character is a bound variable. `gettext` using magic to dynamically declare `_` without explicitly stating its existence is a shame.

Ok, but that seems the usual way for gettext in CPython for program translations (with many different languages) as I described above. Even the CPython DOC itself recommend this style.

> If you write the code in this order, does it work in both cases?
> 
> ```python
> def _(message): return message
> 
> import gettext
> ```
Then I receive some critical errors and warnings from pylint, can't use this.

> My thought would be that we would statically see `_` as a function, then `gettext` would override the function at import time and be happy.

Seems not possible for CPython. Also "my" methode is a global methode for a whole program (needs to be placed only in ONE (the main) py file and it's okay for the rest of program files too.

**Comment by jakebailey** [comment]
The Django library and `gettext` are two separate things. I was describing another internationalization library that uses `_` to show that there are other places where this happens.

The fact that it's CPython isn't the important bit, it's that the `gettext` module patches the builtins to include `_` as a function, which is a magic side effect. Python's type system is not built for this sort of thing.

If that `def` doesn't work (I'd be interested in pylint's messages), how about "declaring" that the variable exists, like:

```python
from typing import Callable

_: Callable[[str], str]

import gettext

print(_("Something"))
```

I will also point out that the documentation's first example has `_` explicitly defined, not produced magically:

```python
import gettext
gettext.bindtextdomain('myapplication', '/path/to/my/language/directory')
gettext.textdomain('myapplication')
_ = gettext.gettext
# ...
print(_('This is a translatable string.'))
```

Which you may want to try. (This is where we may end up with oddity as to our handling of `_` as a "real" variable rather than an explicit discard.)

**Comment by Alpengreis** [comment]
> The Django library and `gettext` are two separate things. I was describing another internationalization library that uses `_` to show that there are other places where this happens.

Yes, I knew. I tried with similar way. Not with the Django one.
 
> The fact that it's CPython isn't the important bit, it's that the `gettext` module patches the builtins to include `_` as a function, which is a magic side effect. Python's type system is not built for this sort of thing.

Ok!

> If that `def` doesn't work (I'd be interested in pylint's messages), how about "declaring" that the variable exists, like:
> 
> ```python
> from typing import Callable
> 
> _: Callable[[str], str]
> 
> import gettext
> 
> print(_("Something"))
> ```
> 
> I will also point out that the documentation's first example has `_` explicitly defined, not produced magically:
> 
> ```python
> import gettext
> gettext.bindtextdomain('myapplication', '/path/to/my/language/directory')
> gettext.textdomain('myapplication')
> _ = gettext.gettext
> # ...
> print(_('This is a translatable string.'))
> ```
> 
> Which you may want to try. (This is where we may end up with oddity as to our handling of `_` as a "real" variable rather than an explicit discard.)

And it's not so easy then to switch the languages, especially for the whole program, because it's not global, right? I think, the last example is more for a module, not for a whole program with let me say, 10 different py files ...

However, I will try your suggestions out yet and will write the results soon.

So - for the moment - a BIG thank you anyway!

**Comment by jakebailey** [comment]
> And it's not so easy then to switch the languages, especially for the whole program, because it's not global, right? I think, the last example is more for a module, not for a whole program with let me say, 10 different py files ...

Presumably there is a single function that represents gettext's `_` function, `gettext.gettext`. Yes, I agree that this sort of workaround means you'd have to do this `_ = ...` in each file that uses `_` (to make the type checker happy), but it should still be the same function for every module, so if you set a global language to something else it's going to affect everything.

--

This is personal opinion, but I'd personally be wary of using something that relies on this sort of magic and implicitness... I'd much rather explicitly import a function and use it by name than to play with the `_` or have the library start patching the builtins. I can see how these sorts of things are appealing as they make the code look short, but writing it explicitly is going to help out type checkers, make it obvious the cost of the translation, make it simpler to identify strings which aren't yet translated, etc.

**Comment by Alpengreis** [comment]
Okay, here the results:

> If that `def` doesn't work (I'd be interested in pylint's messages), how about "declaring" that the variable exists, like:
> 
> ```python
> from typing import Callable
> 
> _: Callable[[str], str]
> 
> import gettext
> 
> print(_("Something"))
> ```

THIS WORKS! I had not (yet) the experience to find that out. I thank you VERY much for this solution! And this solution is the perfect one for me!
 
> I will also point out that the documentation's first example has `_` explicitly defined, not produced magically:
> 
> ```python
> import gettext
> gettext.bindtextdomain('myapplication', '/path/to/my/language/directory')
> gettext.textdomain('myapplication')
> _ = gettext.gettext
> # ...
> print(_('This is a translatable string.'))
> ```
And this worked too! 

> Which you may want to try. (This is where we may end up with oddity as to our handling of `_` as a "real" variable rather than an explicit discard.)
Yes, I understand.

I apprieciate your personal opinion, really! I changed my mind now too, it's a much better solution now!

Okay, once again thank you for your nice help!
