### ISSUE TITLE
Pylance 2021.6 code assist does not work

### ISSUE THREAD

**Issue by norbertnogacki-tomtom** [microsoft/pylance-release#1405]
After upgrading pylance from 2021.5.4  to 2021.6 code assist stopped working

## Environment data

-   Language Server version: 2021.6
-   OS and version: CentOS Linux release 7.7.1908
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.8

EDIT:
forgot to mention I'm using Remote-SSH from Windows 10 19042 (not sure if important)

## Expected behaviour

Code assist should work

## Actual behaviour

Code Assist does not work

## Logs

Python language server logs:

```
[Info  - 12:39:12 PM] Pylance language server 2021.6.0 (pyright 209c8040) starting
[Info  - 12:39:12 PM] Server root directory: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.0/dist
[Info  - 12:39:12 PM] No configuration file found.
[Info  - 12:39:12 PM] No pyproject.toml file found.
[Info  - 12:39:12 PM] Setting pythonPath for service "web": "/home/local/nogacki/projects/ndsweb3/web/venv/bin/python3.6"
[Warn  - 12:39:12 PM] stubPath /home/local/nogacki/projects/ndsweb3/web/typings is not a valid directory.
[Info  - 12:39:12 PM] Assuming Python version 3.6
[Info  - 12:39:12 PM] Assuming Python platform Linux
Search paths for /home/local/nogacki/projects/ndsweb3/web
  /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stdlib
  /home/local/nogacki/projects/ndsweb3/web
  /home/local/nogacki/projects/ndsweb3/web/typings
  /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.0/dist/typeshed-fallback/stubs/...
  /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.0/dist/bundled/stubs
  /usr/lib64/python36.zip
  /usr/lib64/python3.6
  /usr/lib64/python3.6/lib-dynload
  /home/local/nogacki/projects/ndsweb3/web/venv/lib64/python3.6/site-packages
  /home/local/nogacki/projects/ndsweb3/web/venv/lib/python3.6/site-packages
[Error - 12:39:13 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Error - 12:39:13 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 12:39:13 PM] Searching for source files
[Info  - 12:39:13 PM] Background analysis(1) root directory: /home/local/nogacki/.vscode-server/extensions/ms-python.vscode-pylance-2021.6.0/dist
[Info  - 12:39:13 PM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages

```

## Code Snippet / Additional information

```python
myarray = [12, 34]

print(my) # place caret here and try using code assist
```

requirements.txt file
```
amqp==1.4.9
aniso8601==1.1.0
anyjson==0.3.3
astroid==1.3.6
autopep8==1.5.5
azure-core==1.7.0
azure-identity==1.3.1
azure-nspkg==3.0.2
azure-storage-blob==12.3.2
azure-storage-nspkg==3.1.0
Babel==2.3.4
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.7
beautifulsoup4==4.6.0
billiard==3.3.0.23
bleach==2.1.2
blinker==1.4
boto==2.34.0
boto3==1.9.251
botocore==1.12.251
celery==3.1.24
certifi==2017.4.17
cffi==1.13.2
chardet==3.0.4
colorama==0.4.1
coverage==4.0.3
crypto==1.4.1
cryptography==2.8
dataclasses==0.8
debugpy==1.3.0
defusedxml==0.5.0
django-htmlmin==0.10.0
docutils==0.12
docxtpl==0.3.9
ecdsa==0.11
enum34==1.1.6
et-xmlfile==1.0.1
extras==1.0.0
fixtures==3.0.0
flake8==3.8.4
flake8-polyfill==1.0.2
Flask==0.10.1
Flask-Mail==0.9.1
Flask-Markdown==0.3
Flask-RESTful==0.3.3
flask-restplus==0.9.0
Flask-Script==2.0.5
Flask-WTF==0.10.2
flower==0.9.1
funcsigs==0.4
future==0.18.2
futures==3.0.5
ghdiff==0.4
gitdb==0.6.4
GitPython==1.0.1
gunicorn==19.9.0
html5lib==1.0.1
humanize==0.5.1
idna==2.5
importlib-metadata==3.7.0
influxdb==4.0.0
iniherit==0.3.9
ipaddress==1.0.17
isodate==0.6.0
itsdangerous==0.24
jdcal==1.4
Jinja2==2.8
jira==1.0.10
jmespath==0.9.0
jsonschema==2.5.1
kombu==3.0.37
linecache2==1.0.0
logilab-common==1.0.1
lxml==3.8.0
lxml-stubs==0.1.1
mando==0.6.4
Markdown==2.6.5
MarkupSafe==0.23
mccabe==0.6.1
meld3==1.0.2
mock==1.3.0
mox3==0.20.0
msal==1.4.3
msal-extensions==0.1.3
msrest==0.6.18
multi-key-dict==2.0.3
mypy==0.812
mypy-extensions==0.4.3
Naked==0.1.31
numpy==1.16.5
oauthlib==2.0.2
onedrivesdk==1.1.8
openpyxl==2.5.2
ordereddict==1.1
paramiko==1.15.1
pbr==1.8.1
pep8==1.7.0
pipdeptree==2.0.0
portalocker==1.7.1
psycopg2==2.7.3.2
pyasn1==0.4.6
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.10
pycrypto==2.6.1
pyfakefs==3.1
pyflakes==2.2.0
pyinstrument==3.3.0
pyinstrument-cext==0.2.4
PyJWT==1.7.1
PyPDF2==1.26.0
pyral==1.3.1
python-dateutil==2.5.3
python-docx==0.8.6
python-jenkins==1.4.0
python-ldap==3.3.1
python-memcached==1.54
python-mimeparse==1.6.0
python-simplexml==0.1.5
pytz==2017.3
PyYAML==3.12
radon==3.0.3
redis==2.10.5
requests==2.18.4
requests-oauthlib==0.8.0
requests-toolbelt==0.8.0
s3transfer==0.2.1
shellescape==3.4.1
six==1.10.0
smmap==0.9.0
suds-py3==1.4.1.0
testtools==2.2.0
text-unidecode==1.3
toml==0.10.2
tornado==4.2
traceback2==1.4.0
typed-ast==1.4.3
typing==3.7.4.3
typing-extensions==3.7.4.3
unittest2==1.1.0
unittest-xml-reporting==3.0.4
urllib3==1.21.1
webencodings==0.5.1
Werkzeug==0.11.4
WTForms==2.0.1
XlsxWriter==0.9.3
yoyo-migrations==6.1.0
zipp==3.4.1
zipstream==1.1.0

```

**Comment by EnzoMolion** [comment]
I faced the same issue with v2021.6.0
Only workaround I was able to find was to downgrade to v2021.5.4
I had no issue printed in logs.

**Comment by nzig** [comment]
Possible duplicate: #1386

**Comment by jakebailey** [comment]
What is "code assist"? Are you referring to completions? Signature help? Hover?

Completions appear to work: 

![image](https://user-images.githubusercontent.com/5341706/121062093-8ae27800-c779-11eb-8838-a7e6b00f4cac.png)


As does signature help:

![image](https://user-images.githubusercontent.com/5341706/121062118-90d85900-c779-11eb-829a-a408e67de100.png)

Using the completion then hovering:

![image](https://user-images.githubusercontent.com/5341706/121062159-9afa5780-c779-11eb-8360-76d98d1becf5.png)

**Comment by nihirv** [comment]
Thanks @EnzoMolion! downgrading PyLance to `v2021.5.4` fixed it for me too. Weird - the extension worked in some codebases but not in others

**Comment by lnxg33k** [comment]
I am facing the same issue with `2021.6.0`, had to downgrade to `2021.5.4` for the extension to work again.

**Comment by pwo311** [comment]
I am facing the same issues under Windows 10 Ent Python 3.9. I downgraded PyLance to 2021.4.3 and ms-python to 2021.4.765268190 and it resolved the issue with intellisense and the lack of any linting.

**Comment by banuni** [comment]
same here, only on some repos.
macOs 11.4
VSCode 1.56.2

**Comment by norbertnogacki-tomtom** [comment]
> What is "code assist"? Are you referring to completions? Signature help? Hover?
> 
> Completions appear to work:
> 
> ![image](https://user-images.githubusercontent.com/5341706/121062093-8ae27800-c779-11eb-8838-a7e6b00f4cac.png)
> 
> As does signature help:
> 
> ![image](https://user-images.githubusercontent.com/5341706/121062118-90d85900-c779-11eb-829a-a408e67de100.png)
> 
> Using the completion then hovering:
> 
> ![image](https://user-images.githubusercontent.com/5341706/121062159-9afa5780-c779-11eb-8360-76d98d1becf5.png)

I meant code completion but over and signatures don't work either

**Comment by pwo311** [comment]
For me there is no intellisense or linting. When I hover above something that should be flagged by pylance I get a "Loading" popup. I have seen this in prior versions but it goes away after a minute. I believe it just never completes the load in the current version.

**Comment by pwo311** [comment]
Verified that everything works up through and including 21.5.4 pylance. 21.6.0 does not intellisense or linting other than the "Loading" when hovering over something that should be flagged by pylance.

**Comment by craigds** [comment]
'Go to Symbol in Workspace' also doesn't work for me with pylance 2021.6. Downgrading to 2021.5.4 fixes the issue for me.

**Comment by jakebailey** [comment]
We've just released 2021.6.1; can you retry and see if your issue is fixed?

**Comment by craigds** [comment]
Yes 2021.6.1 fixes 'Go to Symbol in Workspace' for me 👍 🎉

**Comment by banuni** [comment]
Fixed the crashing on my machine 👯‍♂️

**Comment by norbertnogacki-tomtom** [comment]
updating to 2021.6.1 fixes the issues for me 👍 thanks
