### ISSUE TITLE
pylance does not show some of docstring of the functions located in os.path module

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1408]
## Environment data

-   Language Server version: 2021.6.1-pre.1
-   OS and version: ubuntu 21.04
-   Python version: 3.9.5 64-bit

## Expected behaviour

pylance showing the docstring of the some of the functions like splitext, etc. in the os.path module

## Actual behaviour

not showing the docstrings of the some of the functions

## Code Snippet / Additional information
`import os`
`os.path.splitext()`
![Screenshot from 2021-06-08 10-38-48](https://user-images.githubusercontent.com/26442126/121135237-89808080-c849-11eb-8a3e-3d9f9b860060.png)
![Screenshot from 2021-06-08 10-34-09](https://user-images.githubusercontent.com/26442126/121135255-8d140780-c849-11eb-9236-4a012177ee3d.png)

**Comment by jakebailey** [comment]
`splitext` appears to break due to this unfortunate dynamic behavior in the standard library: https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/ntpath.py#L209

@arian47 Are there other functions that you are seeing missing docs for, or is it just this one?

**Comment by jakebailey** [comment]
This will be fixed in the next release:

![image](https://user-images.githubusercontent.com/5341706/132776932-40f1646d-5e3d-453e-941b-0209616bcbbf.png)

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202192-16-september-2021
