### ISSUE TITLE
feature unavilable on this platform error

### ISSUE THREAD

**Issue by arian47** [microsoft/pylance-release#1409]
## Environment data

-   Language Server version: 2021.6.1-pre.1
-   OS and version: ubuntu 21.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5 64-bit

## Actual behaviour

there is an error with the following description in the output:

## Logs
[Info  - 10:13:04 AM] Pylance language server 2021.6.1-pre.1 (pyright 209c8040) starting
[Info  - 10:13:04 AM] Server root directory: /home/arian/.vscode/extensions/ms-python.vscode-pylance-2021.6.1-pre.1/dist
[Error - 10:13:10 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js

**Comment by fredrikaverpil** [comment]
Possible duplicate: https://github.com/microsoft/pylance-release/issues/1386
