### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by Samtsirhc** [microsoft/pylance-release#1414]
## Environment data

-   Language Server version: 2021.5.3
-   OS and version: win32 x64
-   Python version (& distribution if applicable, e.g. Anaconda): python3.7.9

## Expected behaviour

package import correctly

## Actual behaviour

I import a package in current dir, it will fail but when I run the .py, there is no problem. I was ok and I never change any setting
![1](https://user-images.githubusercontent.com/48616037/121292018-d6cd2280-c91b-11eb-970e-50ee80ffbc2a.jpg)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by Samtsirhc** [comment]
![Uploading 2.jpg…]()

**Comment by judej** [comment]
Thanks for the report. Have you opened this in the workspace that the aaa.py is in? In other words, did you "open  folder" in VS code in to get to this file?

**Comment by Samtsirhc** [comment]
Of course not，I know what you point. When I “open folder”, it works. But when I open another .py in another folder, it will have some problems. I mean that the pylance can't recognize current folder unless I "open folder" manually now. But it absolutely could do that.

**Comment by Samtsirhc** [comment]
And today I find that the problem is gone. Thank you for your fixing.
Language Server version: 2021.6.1
![1](https://user-images.githubusercontent.com/48616037/122372175-0bcc1b80-cf93-11eb-9bf6-9139eed4c0e7.jpg)

**Comment by jakebailey** [comment]
The semantic highlighting is gone, so I don't think that your issue is fixed, just that Pylance isn't loading at all anymore. Can you check your Python Language Server output window for our output?

In any case, if you are opening the files alone and not via Open Folder or Open Workspace, then I think this is a dupe of #1114.

**Comment by Samtsirhc** [comment]
Yes，thank you~ It is #1114
