### ISSUE TITLE
Context manager leads to unbound variables if `__exit__` explicitly returns `Literal[False]`

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1415]
## Environment data

-   Language Server version: 2021.6.1-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10 Anaconda

## Sample

```python
from typing import Literal

class C0:
    def __enter__(self) -> None:
        pass
    def __exit__(self, *args, **kwargs):  # (method) __exit__: (self: C0) -> Literal[False]
        return False

class C1:
    def __enter__(self) -> None:
        pass
    def __exit__(self, *args, **kwargs) -> Literal[False]:  # (method) __exit__: (self: C1) -> Literal[False]
        return False

with C0():
    a = 0
print(a)

with C1():
    b = 0
print(b)
```

`C0` and `C1` are similar except for that the return type of `C1.__exit__` is declared explicitly.

## Expected behavior

Both `a` and `b` are bound before being printed.

## Actual behavior

`b`is possibly unbound.

**Comment by erictraut** [comment]
This is the convention adopted by type checkers and by typeshed. If `__exit__` has an annotated return type that is bool, it is assumed to handle exceptions. If it is unannotated or explicitly annotated to return `None`, it is assumed to not handle exceptions. If you want to indicate that your context manager doesn't handle exceptions, you should annotated it to return `None`.

**Comment by Azureblade3808** [comment]
Got it.
