### ISSUE TITLE
Intellisense does not reckognize OpenCV object members/methods

### ISSUE THREAD

**Issue by AAnthon1985** [microsoft/pylance-release#1416]
## Environment data

-   VS Code version: 1.56.2
-   Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS and version: Win10m 64bit
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.5 (and reproduced on Python 3.8.8)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: OpenCV
-   Relevant/affected Python-related VS Code extensions and their versions: Python
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Intellisense suggests members/methods (e.g. .shape or .item()) of an "img" object.

## Actual behaviour

Intellisense does not suggest members/methods (e.g. .shape or .item()) of an "img" object.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

![Intellisense](https://user-images.githubusercontent.com/68788787/121396010-3db9fe00-c953-11eb-8e86-96182bad16c7.png)

**Comment by judej** [comment]
Thanks for the report. How are you installing OpenCV?

Also, could you please add the logs - [Instructions](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md)

thanks

**Comment by AAnthon1985** [comment]
I installed OpenCV using pip using the following command from within vscode:

`pip install opencv-contrib-python`

I am not really sure how I can get some output in my console, but this is what I got:

> Error 2021-06-09 20:09:08: stderr jediProxy Error (stderr) c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py:590: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py:590: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
> Error 2021-06-09 20:09:08: stderr jediProxy Error (stderr) c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py:590: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
>   script = jedi.Script(
> c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py:624: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
>   script.goto_definitions(), request["id"]


And here is another output shown in my console:

> User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
Error 2021-06-09 21:25:29: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'c:\Users\Alexander\Documents\GitHub\2020_Python\.vscode\settings.json' (Error: Unable to resolve non-existing file 'c:\Users\Alexander\Documents\GitHub\2020_Python\.vscode\settings.json')
	at _handleError (c:\Users\Alexander\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:581560)
	at async c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:580633)
	at async p.updateTestSettings (c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\out\client\extension.js:59:580260)] {
  code: 'FileNotFound'
}
Starting Jedi Python language engine.
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\completion.py
> conda --version
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py pylint --generated-members=cv2.* --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Alexander\Documents\GitHub\2020_Python\Part_06_opencv\16_opencv_02.py
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Alexander\.vscode\extensions\ms-python.python-2021.5.842923320\pythonFiles\pyvsc-run-isolated.py pylint --generated-members=cv2.* --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text c:\Users\Alexander\Documents\GitHub\2020_Python\Part_06_opencv\16_opencv_02.py
cwd: c:\Users\Alexander\Documents\GitHub\2020_Python
##########Linting Output - pylint##########
************* Module 16_opencv_02
6,0,convention,missing-final-newline:Final newline missing
1,0,convention,invalid-name:Module name "16_opencv_02" doesn't conform to snake_case naming style
1,0,convention,missing-module-docstring:Missing module docstring

------------------------------------------------------------------

Your code has been rated at 2.50/10 (previous run: 2.50/10, +0.00)

**Comment by jakebailey** [comment]
These logs imply that you're using Jedi, not Pylance.

Are you trying to use Python 2, by chance? Have you explicitly chosen Pylance as your language server in your settings but it's not loading?

**Comment by AAnthon1985** [comment]
Thank you, it was indeed set to Jedi, not sure how that one got in, because I used to have Pylance. I did change it back to Pylance, and reloaded the window. I'm now using Pylance again, so far so good. Amusingly enough, though, now I get 0 suggestions.

I am not trying to use Python 2, but Python 3.9.5.

![Intellisense](https://user-images.githubusercontent.com/68788787/121418188-fe97a700-c96a-11eb-826f-0af697b54525.png)

My settings.json file:
`{
    "C_Cpp.updateChannel": "Insiders",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "python.languageServer": "Pylance",
    "python.linting.pylintArgs": ["--generated-members=cv2.*"],
    "python.analysis.logLevel": "Trace"
}`

**Comment by jakebailey** [comment]
I was asking about Python 2 as by default Jedi will be used if that's your interepter. No worries.

Do you see that `cv2.` gets completions, and it's just completions on things after that that fail?

**Comment by bschnurr** [comment]
`cv2.imread`'s return is `Any` so we dont know the type.

**Comment by AAnthon1985** [comment]
> Do you see that `cv2.` gets completions, and it's just completions on things after that that fail?

Sorry, I was away for a couple of days, but would like to come back to this issue if possible.
`cv2.` gets completions as they should, everything works well there.



> our generated stub for `cv2.imread`'s return is `Any` so we dont know the type.

I'm sorry, but I do not quite understand. Could you elaborate please?

Thank you all.

Cheers,

**Comment by bschnurr** [comment]
try right click, go to declaration on `imread`. You will see the cv2 pyi type stub. the return type of the function is `Any`

**Comment by AAnthon1985** [comment]
> try right click, go to declaration on `imread`. You will see the cv2 pyi type stub. the return type of the function is `Any` and therefore we don't know any member/methods of `Any`

Okay, I think I'm understanding a bit more of what you're saying, thank you for your patience. I'd like to add one more question, though. I tried the jupyter notebook extension in VSCode, and there the intellisense does show the member/method.

Any idea what jupyter notebook extension is doing differently compared to the regular python extension? 

![Intellisense](https://user-images.githubusercontent.com/68788787/121797096-5873c780-cc1e-11eb-9d2e-e4a516784328.png)

**Comment by jakebailey** [comment]
Jupyter actually executes the code, so has live data pulled directly from the kernel/interpreter. It then merges that info with the static analysis that Pylance does.

**Comment by AAnthon1985** [comment]
> Jupyter actually executes the code, so has live data pulled directly from the kernel/interpreter. It then merges that info with the static analysis that Pylance does.

Okay, thank you for the explanation. Is there any possibility / option / solution to have the live data pulled directly from the kernel/interpreter just like in Jupyter or any other workaround to get the members of the OpenCV object?

**Comment by jakebailey** [comment]
For regular files, doing so would be quite dangerous; we don't want to go run your code (or libraries) automatically. With jupyter, you're in control of which code runs and does not.

**Comment by AAnthon1985** [comment]
> For regular files, doing so would be quite dangerous; we don't want to go run your code (or libraries) automatically. With jupyter, you're in control of which code runs and does not.

Hi Jake
thank you for the answer. I am more and more willing to accept that there was a misconception from my side. One last question, just for my understanding:
You mentioned that in jupyter, I am in control of which code runs and which does not. I assume you're referring to the fact that in jupyter, one can runs cells individually. That's what you mean with control over what code runs and what not. Am I correct?

Thank you,

**Comment by jakebailey** [comment]
Yes, so you run the code because you know (or assume) it's safe to run. We don't want to auto-run code to get info from it; maybe you wrote a script or imported a library that deletes all of your files, for example.

**Comment by AAnthon1985** [comment]
excellent, then I think that there's nothing left to say from my side apart from a big thank you for helping me understand the nature of the issue much better.

I appreciate the responsiveness and the clarification given from your side.

Best regards,
