### ISSUE TITLE
Make sure "rename" doesn't show as an option on elements that can't be renamed

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#1418]
The issue was originally filed at https://github.com/microsoft/vscode-python/issues/10443 for Jedi. I just opened this here as well to make sure that it doesn't also happen with Pylance 😊

cc @savannahostrowski 

## Steps to reproduce:
1. In a python file, place cursor on `None` and try to rename it using F2
1. See input box
1. Enter a new name and press enter
## Bug
See notification that says `No result`!

Here's what our builtin js/ts extension shows for this case (we show this before the input appears):

<img width="539" alt="Screen Shot 2020-03-04 at 10 26 29 PM" src="https://user-images.githubusercontent.com/12821956/75953959-648fa780-5e67-11ea-8bdb-14fd237dfa16.png">

This is implemented using `prepareRename`: https://github.com/microsoft/vscode/blob/c0c9e0043ce6133042268f22847021ad9a1ce410/extensions/typescript-language-features/src/features/rename.ts#L34

**Comment by heejaechang** [comment]
this is a dup - https://github.com/microsoft/pylance-release/issues/1360
