### ISSUE TITLE
pylance does not activate on python 2.7 virtual enviroment

### ISSUE THREAD

**Issue by mdsadique220076** [microsoft/pylance-release#1425]
## Environment data

-   Language Server version: v2021.6.1
-   OS and version: ubuntu 20.4 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 2.7.13 Anaconda

## Expected behaviour

pylance should automatically start which the vscode launched staying on python file and on the virtual environment of anaconda python2.7.13

## Actual behaviour

pylance doesn't start automatically the user has to change the virtual environment or change the python interpreter to version 3.8 or 3.9 and then the pylance starts and after that user changes the environment to python2.7.13 and continue on programing 

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
By default, Pylance will not run if the interpreter is Python 2.7. If you'd like to use Pylance with Python 2.7 you can explicitly set `"python.languageServer": "Pylance",`. Note, that Pylance does not officially support Python 2.7.
