### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by JulianOrteil** [microsoft/pylance-release#1426]
<h3> Environment data </h3>

-   Language Server version: 2021.6.0 (also fails on 2021.6.1)
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.8; with Anaconda
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

No crashes

<h3> Actual behaviour </h3>

The server crashes with the error `FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory`.
Logs are attached below.

<h3> Logs </h3>

[Python Language Server Log](https://github.com/microsoft/pylance-release/files/6633382/log.txt)

<h3> Code Snippet / Additional information </h3>

Because my project is so large (over 11k line written by me and just under 5 million autogenerated by Qt) and is proprietary, I can't provide code that would help. So instead, I will try to give you a description of the project:

- The project's primary dependencies include: PyQt5, opencv, numpy, pillow, loguru, and a couple other smaller ones.
- The project is well over 11k lines with nearly 5 million extra being auto-generated by PyQt's `pyrcc5` utility (images, gifs, etc). That file is basically bytecode, but is a python file. It is required that I load it in at the launch of the application, but I seldom open it in VS Code. This file I expect to be the culprit. I can upload if it is asked for.
- The language server only fails with this project. I have other, smaller projects that do not encounter this issue.

**Comment by erictraut** [comment]
The type checker maintains an internal type cache that it can discard if memory usage becomes too high. It checks the high-water mark after analyzing each file. From what you're saying it sounds like the type checker consumes the full available heap size (2GB!) of memory with just this single file. If that assumption is correct, that's well outside of the bounds of what we designed for, and I wouldn't expect to be able to analyze a 5-million-line file.

Perhaps we should simply refuse to analyze a text file above a certain size. How large is this file on disk?

**Comment by jakebailey** [comment]
Can you try using a `pyrightconfig.json` to exclude the file that you think is problematic, perhaps?

https://github.com/microsoft/pyright/blob/main/docs/configuration.md

**Comment by erictraut** [comment]
Excluding the file won't prevent type checking once the file is open in the editor. Once a ".py" or ".pyi" file is opened, pylance will analyze it.

**Comment by JulianOrteil** [comment]
> Perhaps we should simply refuse to analyze a text file above a certain size. How large is this file on disk?

The file is currently 321KB on disk.

> Once a ".py" or ".pyi" file is opened, pylance will analyze it.

Does this mean **any** ".py" or ".pyi" file, or just the ones importing this large one? If I open a ".py" file that does not import this large file, then the server doesn't crash. Even opening files that import other files that import this large file (i.e. "ui.py" imports this large file, but I import "ui.py" into "control.py" and can open "control.py" without the server crashing).

> Can you try using a `pyrightconfig.json` to exclude the file that you think is problematic, perhaps?

No change. Likely because of this: `Note that files in the exclude paths may still be included in the analysis if they are referenced (imported) by source files that are not excluded.` This is the case for me, I need to be able to edit "ui.py" (in this case) which imports the large file.

**Comment by jakebailey** [comment]
> Excluding the file won't prevent type checking once the file is open in the editor. Once a ".py" or ".pyi" file is opened, pylance will analyze it.

Yes, of course; I was hoping this was some unreferenced file, but that's clearly not the case.

**Comment by erictraut** [comment]
If another file imports this large file, the the large file will be opened, parsed, and "bound" (i.e. lexical scopes are identified and symbol tables are populated), but the large file will not be fully analyzed. Full analysis will be done only when the file is opened in the editor. The full analysis is where the vast majority of work takes place (and where most memory is consumed). Theoretically, a file could get so large that even parsing and binding would consume all available memory, but I wouldn't expect that to happen until the file reaches tens of Megabytes in size.

Partial type analysis will be done for a file that hasn't been opened, but this is done only for symbols whose types are needed by the importer. It's theoretically possible analysis of a single symbol's type could be problematic — for example if a large file defined a single variable without a type annotation and assigned to it a tuple expression that contains 100,000 items.

Is this large file checked in to a public github repo? If not, is there a place where you could upload it so we can look at it? I could do some additional exploration and analysis of the problem.

**Comment by JulianOrteil** [comment]
Here is a link for download. It does have a PyQt5 dependency: https://drive.google.com/file/d/1711ErbTlayYCh7ArybRn8mSh5rTY1N2q/view?usp=sharing

**Comment by JulianOrteil** [comment]
> This file is 335.6MB in size and has 4.9M lines.

My bad! I meant MB not KB lol

But excellent. Thanks for putting in the PR. I wonder if there should be some sort of notification from VS Code noting that the file size limit was exceeded? That would be preferable to nothing at all. I can open an issue there for that if you think it would be worth the time?

Thanks again

**Comment by JulianOrteil** [comment]
This file is 335.6MB in size and has 4.9M lines.

My bad! I meant MB not KB lol

But excellent. Thanks for putting in the PR.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.6.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202162-16-june-2021

**Comment by JulianOrteil** [comment]
Can confirm this has been fixed; thanks a ton for doing so. Pylance is so much more polished that Jedi.
