### ISSUE TITLE
Follow VS Code's system of overruling for configuration

### ISSUE THREAD

**Issue by jamilraichouni** [microsoft/pylance-release#143]
**Note:**

This issue has originally been posted in the Pyright repo: microsoft/pyright#836.
@erictraut recommended to report that issue here.

## Environment data

-   Language Server version: 2020.7.2
-   OS and version: macOS Catalina 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda 3 with multiple environments (mostly py3.7.7)

## Expected behaviour

Pylance configuration settings `"python.analysis.(...)"` respect the overruling concept of
VS Code even if a local `pyrightconfig.json` is present in a project folder.

### Effective value for a setting

Reading the [documentation for the WorkspaceConfiguration interface of VSCode](https://github.com/microsoft/vscode/blob/aa930e56196a1af56cae6d70b0e424fa0e99b824/src/vs/vscode.d.ts#L4674):

The *effective* value (returned by [`get`](#WorkspaceConfiguration.get) and excluding language settings) is computed by overriding or merging the values in the following order.

1. `defaultValue`
1. `globalValue` (if defined)
1. `workspaceValue` (if defined)
1. `workspaceFolderValue` (if defined)

**Note:** Only `object` value types are merged and all other value types are overridden.

## Actual behaviour

When a `pyrightconfig.json` file is present in a project folder and is not containing any
setting for severity overrides, the severity override settings in the global user config file
`Code/User/settings.json` have no effect.

### Global severity overrides

Define severities (`"python.analysis.diagnosticSeverityOverrides"`) in a way following the hierarchy listed above.

**Example:**

Set `diagnosticSeverityOverrides` in global settings (`Code/User/settings.json`) since a user may always want to apply the same severity overrides for all projects.

### Fine-tuned `include`/ `exclude` settings for best speed of type analysis

Set `"include"` and/ or `"exclude"` per workspace or folder (not only in `pyrightconfig.json` but also in VSCode's config system) since project directory names differ from project to project.

**Example:**

There might be a

* project A with a sub directory `${workspaceFolder}/pkg`,
* project B with a sub directory `${workspaceFolder}/lib`,
* project X, Y, and Z each with a sub directory `${workspaceFolder}/backend`.

As described at the top of this message:

For all projects the user may want to have identical severity overrides that
have been defined **globally** in `Code/User/settings.json` but:

The user may also want to fine-tune include/ exclude settings (see below):

1. For the projects A and B the include/ exclude settings may be defined as
   **folder settings**.
1. For the other (backend) projects X, Y, and Z that are organised in one `.code-workspace`
   the user may want to define include/ exclude **workspace** settings.

### Folder settings for `include` and `exclude`

**Project A:**

`${workspaceFolder}/.vscode/settings.json` with something like
```json
{
    "pyright.include": ["pkg"]
}
```

**Project B:**

`${workspaceFolder}/.vscode/settings.json` with something like
```json
{
    "pyright.include": ["lib"]
}
```

### Workspace settings for `include` and `exclude`

**Projects X, Y, and Z:**

`web_applications.code-workspace` with something like
```json
{
    "folders": [
        {
            "path": "/path/to/X"
        },
        {
            "path": "/path/to/Y"
        },
        {
            "path": "/path/to/Z"
        },
    ],
    "settings": {
        "pyright.include": ["backend"]
    }
}
```

## Summary

All configuration options shall follow VS Code's configuration system since it is
extremely useful and covers every(?) imaginable setup.

Fine-tuning `include` / `exclude` settings to try to ensure the best achievable analysis speed as described above is just one example use case.

## Benefits

Following the standards of VS Code's great configuration system with its sophisticated
overruling strategy (hierarchy) makes it possible to distribute settings with global,
workspace, and folder scope to get the flexibilty often needed by us developers.

Here and with most other VS Code settings:

1. Be able to configure global settings in `Code/User/settings.json`
1. Be able to configure workspace settings at one location for multiple projects organised
   in one `.code-workspace`.
1. Capability to fine-tune settings per project folder (`.vscode/settings.json`)
   without the need to maintain an extra `pyrightconfig.json` file.
   
   This is of interest for users who solely use Pylance as VS Code extension and
   do not run pyright via its CLI (e. g. CI pipelines).

**Comment by judej** [comment]
The exclude setting request is covered by https://github.com/microsoft/pylance-release/discussions/2581
