### ISSUE TITLE
Semantic Highlighting Won't work

### ISSUE THREAD

**Issue by awesomelewis2007** [microsoft/pylance-release#1430]
## Environment data

v2021.5.842923320

-   Language Server version: v2021.5.842923320
-   OS and version: Windows 10 H21H1
-   Python version : 3.9.4

## Expected behaviour

semantic Highlighting to work
![image](https://user-images.githubusercontent.com/60709927/121597558-c52d6d00-ca38-11eb-9f50-b4b861a02c1a.png)

## Actual behaviour

semantic Highlighting does not load after updating vscode
![image](https://user-images.githubusercontent.com/60709927/121597389-91eade00-ca38-11eb-9ad4-61d690d35c5f.png)

**Comment by jakebailey** [comment]
Duplicate of #1428. See a workaround here: https://github.com/microsoft/pylance-release/issues/1428#issuecomment-858916868
