### ISSUE TITLE
Intellisense fires within comments

### ISSUE THREAD

**Issue by normanlorrain** [microsoft/pylance-release#1431]
Inside a comment, I finish a sentence with a "." and the intellisense popup appears with "append", etc:

![intellisense](https://user-images.githubusercontent.com/7077277/121597955-824ea380-c9fe-11eb-8ebc-96abe6653b1d.png)

I can imagine some use for intellisense in comments, but in this case it shouldn't have appeared at all.  

If there's some agreement, I'll create an issue.

**Comment by erictraut** [comment]
I agree this should never occur. There is code in place to prevent this, but you must have hit a condition that our checks don't cover. If you're able to find a minimal, self-contained code sample, that would be really useful.

**Comment by erictraut** [comment]
Hmm, I'm not able to repro the problem following those steps. Are you sure that these completion suggestions are coming from pylance? Do you have other extensions installed that might be generating these completion suggestions? The icons next to these items in your screen shot don't look familiar.

**Comment by normanlorrain** [comment]
Ahhh, it was a different extension (frhtylcn.pythonsnippets).  I went through the ones I had installed, and toggling that one triggers this issue.

Sorry for the confusion, thanks for the help!
