### ISSUE TITLE
Parameter hints does not update when using functools.partial

### ISSUE THREAD

**Issue by Strauman** [microsoft/pylance-release#1434]
## Environment data

-   Language Server version: 2021.6.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off
- Running WSL 2: Windows 10 with Ubuntu 18.04.4 LTS

## Expected behaviour
When `functools.partial` is used, parameter hints should update, and show the parameters of the original function.

## Actual behaviour
Parameter hints show `(*args: Any, **kwargs: Any) -> None` instead.

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/1666236/121654092-a7deba00-ca9d-11eb-974d-ca4485614c64.png)

```python
from functools import partial

def generic_func(name: str, number: int):
  print(name, number)

specific_func = partial(generic_func, name="static_name")

specific_func()
```
Likely related to #442

**Comment by erictraut** [comment]
This is related to https://github.com/microsoft/pyright/issues/220.

We've talked about implementing special-case knowledge of functools.partial function's behavior within the type checker. In general, we don't include special-case knowledge of specific functions because it's not a scalable approach. However, we could consider making an exception in cases where 1) the function is part of the standard library, and 2) there's sufficient interest expressed by the community about a particular function.

If you're interested in better functools.partial handling, please indicate as such by upvoting this issue.

**Comment by Strauman** [comment]
@erictraut The linked issue is closed, though?

**Comment by erictraut** [comment]
There hasn't been any change to address this issue. It can be fixed only by adding special-case knowledge of this particular function — something we generally don't do in the type checker. We might change our minds if there's sufficient signal from users. So if you're interested in this, please upvote this issue.

**Comment by kthy** [comment]
Since there is no way that I know of to "upvote this issue" on Github, I took the liberty of instead thumbing every comment.

**Comment by johanrosenkilde** [comment]
Up-voting this: I'm in a situation where this would be great 🎉

**Comment by erictraut** [comment]
Thanks for the upvotes on this issue. I've implemented support for functools.partial. It will be included in the next release of pylance.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.0, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202210-5-january-2022)

**Comment by ekreate** [comment]
Hi, I'm getting the same issues as OP, was this recently broken?

**Comment by erictraut** [comment]
@ekreate, this is working fine for me. If you are seeing an issue, please open a new bug report and provide a minimal, self-contained code sample with repro instructions.

**Comment by ekreate** [comment]
I think I found what's wrong, in my case I'm doing a partial of a dataclass
in that case I just get the following:
![image](https://user-images.githubusercontent.com/30499201/235363609-3b246373-71c4-4327-b702-6e5f5fbaaa72.png)
![image](https://user-images.githubusercontent.com/30499201/235363736-d07cdbe1-9e0c-41e3-bad9-716ba91acef7.png)

I found a workaround:
![image](https://user-images.githubusercontent.com/30499201/235364011-abeb7eb3-959b-4250-955b-22f39979d1d0.png)
 but its working a bit odd with a `Type[InputPort]` attached:
 
![image](https://user-images.githubusercontent.com/30499201/235364081-809e1dfa-059a-47ae-aef2-19993cb14950.png)

![image](https://user-images.githubusercontent.com/30499201/235364061-65aa2982-bca8-46cb-bae7-02f324371c50.png)
