### ISSUE TITLE
Use hasattr-function to add member of a class variable in the indentation block

### ISSUE THREAD

**Issue by TobisMa** [microsoft/pylance-release#1440]
## Environment data

-   Language Server version: 2021.6.1
-   OS and version: Windows 10 x64
-   Python version (& distribution if applicable, e.g. Anaconda): python3.9.5
-   Pylance setting `reportGeneralTypeIssues`: `basic`

## Expected behaviour

```python
class MyClass: pass
my_class = MyClass()

if hasattr(my_class, "attr"):
    print(my_class.attr)            # reference as line 5
```
Pylance should not throw the error `Cannot access member "attr" for type "MyClass" [...] (reportGeneralTypeIssues)` in line 5 in the `PROBLEMS`-window of VS Code because the `if`-statement already checks whether the attribute exist or not.
It should not know the type of `my_class.attr`, so, `Unknown` is right.

## Actual behaviour
throwing error `Cannot access member "attr" for type "MyClass" [...] (reportGeneralTypeIssues)` in line 5 

## Logs
None, I have seen were relevant in my opinion. Let me know if there are relevant logs and I will send them.

## Code Snippet / Additional information
if you define `my_class.attr = "A message"` after creating a instance of `MyClass` it shows `reportGeneralTypeIssues`s in the line you define it and in the if-block. 

Here the code snippet with `my_class.attr = "A message"`:
```python
class MyClass: pass
my_class = MyClass()

my_class.attr = "A message"

if hasattr(my_class, "attr"):
    print(my_class.attr)
```
---
All of the snippets above a valid python code you can run without getting any errrs from the python interpreter (I tried it myself using Pylance version 2021.6.1).

**Comment by erictraut** [comment]
One of the main jobs of a type checker is to tell you when you are accessing an attribute that isn't declared within a class. In your example, the `MyClass` class doesn't declare an attribute `attr`, so any attempt to access this attribute outside of the class itself should report an error. This is consistent with what other type checkers (like mypy) do.

If you want to be able to access attribute `attr` in a manner that works with type checking, you have a few options.

1. Declare and initialize `attr` within your class. You can make it optional and assign it `None` if you would like.

```python
class MyClass:
    attr: Optional[str] = None
```

2. Implement `__getattr__` and `__setattr__` methods for your class:

```python
class MyClass:
    def __getattr__(self, name: str) -> Any:
        # Implementation omitted
        ...

    def __setattr__(self, name: str, value: Any) -> None:
        # Implementation omitted
        ...
```

**Comment by TobisMa** [comment]
Sure you are right that Pylance should throw an error if I try to access the attribute `attr` or could assign them to a class, but using an `if`-statement with `hasattr` is checking whether the attribute is accessable. That is why there is no need to throw an error. Either the interpreter executes the line and the attribute `attr` exist or the interpreter never executes the line. Also it is valid python code. Please correct me if I am wrong.

### Hopefully a more clearer example to point out what I meant
Creating a class with flexible attributes
```python
class MyClass:
    def __init__(self, **kwargs):
          for key, value in kwargs.items():
               setattr(self, key, value)
```

Then I am trying to check whether the class has the attribute using the `hasattr`-function:
```python
...
my_class = MyClass(attr="The print-string")

if hasattr(my_class, "attr"):
    print(my_class.attr)  # just doing something with it
...

```

Because of the `if`-statement `my_class` must have the attribute `attr`, but pylance tells me it does not exist
![grafik](https://user-images.githubusercontent.com/62471232/121786264-06e82000-cbbf-11eb-8be1-5b8d538bc6a0.png)
![grafik](https://user-images.githubusercontent.com/62471232/121786286-326b0a80-cbbf-11eb-8b33-ad086abcf6c2.png)

The python compiler can run the code and access the attribute `attr` and also prints it.

So Pylance should not throw any `access member`-error inside a `if`-code block if the `if`-statement uses the function `hasattr` to check, whether the attribute exists on the class instance or not. I do **not** want to tell that Pylance does something wrong by telling me that I can't access `attr` in the following example:

```python
class MyClass: pass
my_class = MyClass()
print(my_class.attr)   # Pylance shall throw an error on this line on the attribute "attr"
```

**Comment by erictraut** [comment]
The class has no declared attribute of that name. Checking it in a conditional statement doesn't change that fact.

Just because code happens to run without generating a runtime exception doesn't mean that it should pass type checking.

Pylance is consistent with other Python type checkers in this regard. If you run this code in mypy, it will give you the same error.

If you don't want a type checker to emit an error in this case, you can choose to suppress the error with a `# type: ignore` comment at the end of the line.

**Comment by TobisMa** [comment]
Ok. I apologize for the misunderstanding from me and disturbing you from other important work if that should be the case. Yet I would like it if Pylance would detect something like this and doesn't throws an error. Then I will use the `# type: ignore` comments to turn errors like that off.
Also I will have closed the issue by posting this issue.
