### ISSUE TITLE
Incorrect return type with overload and type Unknown

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#1444]
<h3> Environment data </h3>

-   Language Server version: 2021.6.1
-   OS and version: darwin x64
-   Python version: 3.10.0b2
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```py
from typing import overload

@overload
def func(arg: int) -> str:
    ...

@overload
def func(arg: None) -> None:
    ...

def func(arg: int | None) -> str | None:
    if arg is None:
        return None
    return "Hello World"

res = func(var)
reveal_type(res)  # should be: str | None
```

<h3> Expected behaviour </h3>

When calling a function with a variable that is inferred as `Unknown`, the return type shouldn't be the one of the first overload, i.e. `str`. I would have expected `str | None` as is the case when removing the `overload` declarations.

<h3> Actual behaviour </h3>

`res` is inferred as type `str`.

<h3> Logs </h3>

--

**Comment by jakebailey** [comment]
See also #1377, but I do feel like picking the first overload is a little unintuitive.

**Comment by cdce8p** [comment]
> See also #1377

Sorry about that. Should have checked before hand. Will close this one.
