### ISSUE TITLE
Pylance report Missing Imports

### ISSUE THREAD

**Issue by TrafalgarWaterDLaw** [microsoft/pylance-release#1445]
## Environment data

-   Language Server version: v2021.6.1
-   OS and version: 64-bit OS
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

from freegames import square, vector

## Actual behaviour

Import "freegames" could not be resolved Pylance report Missing Imports

## Logs

```
I am unable to enable trace logging
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by bschnurr** [comment]
Try using the "Pylance: Report Issue" command. it automatically copies the logs to your clipboard so that you can pase them. but you still need to turn tracing on in your settings.json `ctrl+,`

**Comment by TrafalgarWaterDLaw** [comment]
I'd you could walk me through the process, I would appreciate that

**Comment by jakebailey** [comment]
You would want to set:

![image](https://user-images.githubusercontent.com/5341706/121941540-43716400-cd04-11eb-9e39-52a439478473.png)

Then find the logs in the output window here:

![image](https://user-images.githubusercontent.com/5341706/121941569-4bc99f00-cd04-11eb-9f96-ceba3dac3c14.png)

**Comment by TrafalgarWaterDLaw** [comment]
I have managed to select Trace, although I am unable to find the language server

[Uploading v8{230a58c} (3408bcc8-c8a8-4f57-b878-7f8dbad544b4 id=0x7f0a03c0) …]()

**Comment by jakebailey** [comment]
For reference, you can find a link to the output here:

![image](https://user-images.githubusercontent.com/5341706/122115044-d67bce00-cdd8-11eb-807a-acd8629c3e70.png)

Then, you will see the dropdown on the right of the panel that appears.

**Comment by TrafalgarWaterDLaw** [comment]
Hello Sir
As instructed, I have open the output window and I am in the Python Language Server.![20210619_090628.jpg](https://user-images.githubusercontent.com/77013205/122634304-b6505580-d0dd-11eb-80c3-075862eef650.jpg)

**Comment by jakebailey** [comment]
Screenshots aren't really going to give us the info we need; can you copy and paste that entire output?

**Comment by TrafalgarWaterDLaw** [comment]
Okay I will send it tomorrow thank you Sire

**Comment by TrafalgarWaterDLaw** [comment]
Good morning and or Evening Sir, attached you will find a pdf with the output log that you requested. Hopefully it helps resolve the issue with the extension.

[Info.pdf](https://github.com/microsoft/pylance-release/files/6714403/Info.pdf)

**Comment by jakebailey** [comment]
Thanks.

Where do you have `freegames` installed? Your logs indicate that your selected interpreter is:

```
C:\Users\Mr Cephas\AppData\Local\Programs\Python\Python38\python.exe
```

Did you install `freegames` globally to this interpreter, or to some other interpreter?

**Comment by TrafalgarWaterDLaw** [comment]
Morning/Evening and or Afternoon

I have not installed _**freegames**_ anywhere, I am trying to import it and this is the first time I have tried to import a module and I am unable to import it. Should i install freegames on my computer?

**Comment by acbetter** [comment]
I use this to solve the issue. Mod your `settings.json` . Hope it works.

```json
{
    "python.languageServer": "Pylance",
    "python.defaultInterpreterPath": "python3"
}
```

**Comment by TrafalgarWaterDLaw** [comment]
Thanks let me try it

**Comment by TrafalgarWaterDLaw** [comment]
It is all okay now. Thanks guys.
