### ISSUE TITLE
Missing imports -> discord.py; python-dotenv

### ISSUE THREAD

**Issue by prithvi2k2** [microsoft/pylance-release#1448]
#### Module: discord.py
```
import discord
```
Response: `Import "discord" could not be resolved`

<hr/>

#### Module: python-dotenv
```
from dotenv import load_dotenv
```
Response: `Import "dotenv" could not be resolved`

**Comment by jakebailey** [comment]
You didn't fill out our bug template; can you please provide the info listed here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

I would verify that your selected interpreter has these installed.

**Comment by prithvi2k2** [comment]
I am closing this issue. On restarting VScode, PyLance asked me something related to a new environment, I think I should've mentioned that before that I am using a venv.
Now, everything seems to work fine after the restart.
Thnx for your patience @jakebailey

**Comment by jakebailey** [comment]
Yes, that sounds like #923.
