### ISSUE TITLE
completions inside dictionary key context was not perfect

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/pylance-release#1460]
## Environment data

-   Language Server version: 2021.6.2
-   OS and version: Windows 7 x64
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8

## Expected behaviour

Show all keys

## Actual behaviour

Just show some of keys
(Not showing those with symbols: +-*[....)
[![2v19mV.png](https://z3.ax1x.com/2021/06/17/2v19mV.png)](https://imgtu.com/i/2v19mV)

**Comment by javad94** [comment]
Also doesn't show integer keys.

**Comment by heejaechang** [comment]
@javad94 can you open a new issue with some examples? the main issue should be fixed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.6.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202163-23-june-2021

**Comment by javad94** [comment]
@heejaechang Yes, of course.
