### ISSUE TITLE
False positive for use before assignment

### ISSUE THREAD

**Issue by hauntsaninja** [microsoft/pylance-release#1461]
<h3> Environment data </h3>

-   Language Server version: 2021.6.1
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

The following is valid Python, and Pylance shouldn't complain:
```
def f():
    class X(A): ...
    print(x)

class A: ...
x = 5
```

<h3> Actual behaviour </h3>

Pylance complains about "using variable 'A' before assignment"

<h3> Code Snippet / Additional information </h3>

<img width="612" alt="screenshot" src="https://user-images.githubusercontent.com/12621235/122357746-daa70900-cf08-11eb-9d14-faf66251d8c2.png">

**Comment by erictraut** [comment]
That error message is not coming from Pylance. Please look for other extensions that you have installed that might be performing linting or similar code analysis.

**Comment by hauntsaninja** [comment]
You're absolutely right, this is what I get for filing issues late at night. So sorry about the noise. Was working in a different VSCode workspace than I usually do, and this one had Pylint enabled.
