### ISSUE TITLE
False positive "is not iterable" type check report

### ISSUE THREAD

**Issue by fedyakov** [microsoft/pylance-release#1463]
<h3> Environment data </h3>

-   Language Server version: 2021.6.1
-   OS and version: darwin x64
-   Python version: 3.9.5
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
a = 0
b = [lambda: a]
for a in b:
    pass
```

<h3> Actual behaviour </h3>

There is a type check report on line 3 when typeCheckingMode=basic:
> "b" is not iterable Pylance(reportGeneralTypeIssues)
> (variable) b: list[() -> (int | Unknown)]

I do not expect such a report cause "b" is a list and it's obviously iterable.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.6.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202163-23-june-2021
