### ISSUE TITLE
Pylance is not allowing to import everything( * ) from a module.

### ISSUE THREAD

**Issue by Abhinav-A-17** [microsoft/pylance-release#1466]
Guys whenever I try to import everything( * ) from a module. It gives me the error.

Like I was developing a browser:
![Issue#1](https://user-images.githubusercontent.com/76961241/122525102-84d07f00-d036-11eb-8f8f-0b3668f7e98f.PNG)

And my error was like this:
![Issue#1 1](https://user-images.githubusercontent.com/76961241/122525168-974ab880-d036-11eb-9743-c66608d9019e.PNG)

This error is showing me whenever I import it.
This is my first issue so it would be in a proper manner.

**Comment by erictraut** [comment]
This isn't an error, it's a warning. This diagnostic check is off by default in pylance, but when you enable type checking, it is enabled as a warning.

Using wildcard imports from a library is a dangerous and fragile practice that should be avoided in Python. See PEP 8 for details.

You can choose to silence this diagnostic check if you like.

**Comment by CodeCrazy-ywt** [comment]
That's to say, wildcard import is allowed but not recommended? If so, then the warning should be changed into "wildcard import from a library not **recommended**"

**Comment by CodeCrazy-ywt** [comment]
So the warning prompt should be changed into "Wildcard import from a library not **recommended**", and should be allowed to be switched off in the settings.

**Comment by jakebailey** [comment]
The wording is fine; the rule is there to allow you to enforce that they are disallowed.

This setting is already customizable with the diagnostic severity overrides; you can change the severity of any rule.

**Comment by Ramin350** [comment]
how can disable this ?

**Comment by PabloLION** [comment]
> how can disable this ?

add a `# type: ignore` in the line you need

**Comment by Diogo-Rossi** [comment]
> how can disable this ?

A "one action way" would be adding thins on settings:

```
"python.analysis.diagnosticSeverityOverrides": {
    "reportWildcardImportFromLibrary": "none"
}
```
