### ISSUE TITLE
Go to Definition not working for package pyeit

### ISSUE THREAD

**Issue by DavidMetzIMT** [microsoft/pylance-release#1467]
## Environment data

-   Language Server version: v2021.6.2
-   OS and version: Windows 10 Pro x86, Version: 20H2, build:19042.1052, Experience Pack: 120.2212.2020.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8 64-bit ('py38_app': conda)

## Introduction
Hy,
I'm new here, so I apology in advances if i forget something to mention!!!

I installed the package pyeit (https://github.com/liubenyuan/pyEIT) in my conda env (py38_app).
My code work fine, but since a while (since v2021.5.3) I can not access the source code of that package, the "go to definition F12" function and by clicking on the package + Ctrl  results both in "no definition found for 'select_lib'" (see gifs)

## Expected behaviour

with the v2021.5.2 the "go to definition " function work fine!
![bug_pyeit_pylance2021-5-2](https://user-images.githubusercontent.com/11027663/122540899-5e581700-d029-11eb-85df-9a442edc1494.gif)

## Actual behaviour
with the v2021.5.3 up to v2021.6.2 the "go to definition " function do not find the defnition
![bug_pyeit_pylance](https://user-images.githubusercontent.com/11027663/122540895-5dbf8080-d029-11eb-922e-249d3ee75061.gif)

## Code Snippet / Additional information

-->

**Comment by bschnurr** [comment]
can you please try the latest build? I believe this was fixed in `2021.8.3`
"A bug that prevented navigation to directory-based eggs has been fixed. (pylance-release#1685))"

**Comment by DavidMetzIMT** [comment]
I tried with v2021.9.0 and it works! many thanks!
