### ISSUE TITLE
Intelisense Support SQLAlchemy ORM Class

### ISSUE THREAD

**Issue by lowercase00** [microsoft/pylance-release#1476]
Couldn't find a way to get suggestions on SQLAlchemy ORM.
With the table defined, when creating a new instance it does not show the columns suggestions, and doesn't recognize inexistent attributes:

![Screen Shot 2021-06-21 at 09 09 56](https://user-images.githubusercontent.com/21188280/122759631-8d13fe80-d270-11eb-9aca-61e07205b005.png)

![Screen Shot 2021-06-21 at 09 10 59](https://user-images.githubusercontent.com/21188280/122759686-99985700-d270-11eb-90c2-554343a056a4.png)

When CTRL+Space it would be nice to know which columns are available.

**Comment by debonte** [comment]
@lowercase00, FYI, SQLAlchemy is working on improving their type checking experience. See https://github.com/sqlalchemy/sqlalchemy/issues/7642. The `dataclass_transform` feature they mention is currently in a [draft PEP](https://peps.python.org/pep-0681/) that we hope to get into Python 3.11.
