### ISSUE TITLE
Support parenthesized parameters for `del`

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1480]
## Environment data

-   Language Server version: 2021.6.3-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.10 Anaconda

## Sample

```python
a = 1
b = 2
del (a, b)
```

## Expected behavior

No errors/warnings.

## Actual behavior

Got "Expression cannot be deleted | Pylance(reportGeneralTypeIssues)".

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by Azureblade3808** [comment]
I had a `del` statement which deletes many variables at once, and the code line was wrapped using parenthesis by code formatter 'black', then it was reported by Pylance. The warning could be prevented by breaking the `del` statement into multiple ones which would not get wrapped. But I think it would be more convenient if Pylance could handle this usage.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.6.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202163-23-june-2021
