### ISSUE TITLE
auto-complete bug, when import from 3-rd lib and module not accessed in __init__.py

### ISSUE THREAD

**Issue by wangyuxinwhy** [microsoft/pylance-release#1482]
## Environment data

-   Language Server version: 2021.6.2
-   OS and version: MacOS 11.1
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.9

## Expected behaviour

have suggestions. 

```
from allennlp import modules

modules.
```

## Actual behaviour

No suggestions.

![ILpwRv](https://yuxin-wang.oss-cn-beijing.aliyuncs.com/uPic/ILpwRv.png)

![X92RXU](https://yuxin-wang.oss-cn-beijing.aliyuncs.com/uPic/X92RXU.png)

but in PyCharm, it's OK.

![3ll5Hl](https://yuxin-wang.oss-cn-beijing.aliyuncs.com/uPic/3ll5Hl.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
This library marks itself as `py.typed`, but doesn't follow the guidance provided here: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface

Specifically, it doesn't re-export things in a way that we currently recognize: https://github.com/allenai/allennlp/blob/main/allennlp/modules/__init__.py

These symbols won't be treated as visible to importers of the module.

**Comment by erictraut** [comment]
Please file a bug (or even better, submit a PR) to the allenlp repo so the type information is fixed.

**Comment by wangyuxinwhy** [comment]
OK，i will submit a PR to allennlp to fix this bug. Thank you for your reply.
