### ISSUE TITLE
Argument completion for literal values

### ISSUE THREAD

**Issue by vberlier** [microsoft/pylance-release#1497]
Pylance doesn't suggest literal values when you input the opening parenthesis of a function call:

![image](https://user-images.githubusercontent.com/24430071/123304816-aee6dd00-d51f-11eb-9676-7212f2b56dc3.png)

With TypeScript this is what it looks like:

![image](https://user-images.githubusercontent.com/24430071/123304705-8e1e8780-d51f-11eb-8792-9939ca9ca6de.png)

If you start inserting double quotes Pylance doesn't suggest the remaining characters:

![image](https://user-images.githubusercontent.com/24430071/123304850-ba3a0880-d51f-11eb-8b01-64de5d6476cc.png)

With TypeScript this works:

![image](https://user-images.githubusercontent.com/24430071/123304647-78a95d80-d51f-11eb-9e57-204997140aca.png)

If you omit the quotes and start writing the content of the string Pylance doesn't show the suggestions first:

![image](https://user-images.githubusercontent.com/24430071/123304943-d473e680-d51f-11eb-8357-f71e351454d9.png)

TypeScript handles this a bit better:

![image](https://user-images.githubusercontent.com/24430071/123304746-98d91c80-d51f-11eb-8a28-b3901eb261ab.png)

Also there's a problem with this use-case, when you select one of the suggested completions the string is inserted after the cursor instead of replacing the initial prompt:

![image](https://user-images.githubusercontent.com/24430071/123304982-df2e7b80-d51f-11eb-969a-12037d17f681.png)

With TypeScript the suggestion is inserted properly and replaces the initial prompt:

![image](https://user-images.githubusercontent.com/24430071/123306225-50226300-d521-11eb-86db-ac60a5a4bb07.png)

**Comment by jakebailey** [comment]
The next release (today) will include support for all of the things mentioned in this issue.

**Comment by heejaechang** [comment]
fixed in 2021.8.1 release.
