### ISSUE TITLE
No highlighting when selecting a word.

### ISSUE THREAD

**Issue by HongtaoYang** [microsoft/pylance-release#1500]
Issue Type: <b>Bug</b>

Missing variable highlights when selecting a word. This happens with instance variables from my testing. See the following three screen shots. Only the`var` in the `__init__` was highlighted when the cursor was on that variable. More strangely, it doesn't even highlight the variable in the same method.

![Screen Shot 2021-06-25 at 18 00 17](https://user-images.githubusercontent.com/16588434/123391595-88887680-d5df-11eb-90e1-36629329ceb0.png)

![Screen Shot 2021-06-25 at 18 00 27](https://user-images.githubusercontent.com/16588434/123391787-b40b6100-d5df-11eb-97fd-50f80f809a40.png)

![Screen Shot 2021-06-25 at 18 01 05](https://user-images.githubusercontent.com/16588434/123391799-b7065180-d5df-11eb-8125-d0f6d30d4fb9.png)

Extension version: 2021.6.3
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|. --crash-reporter-id 94428f45-d8ae-489d-ad47-c989c48031bb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
I can reproduce this, thanks.

![image](https://user-images.githubusercontent.com/5341706/123473872-09c71580-d5ae-11eb-9186-8563ccf8f01f.png)

**Comment by lapraas** [comment]
Yep, I've got the same issue.

![image](https://user-images.githubusercontent.com/63134341/123879414-e209e180-d90e-11eb-8d21-1a96bce863a4.png)

**Comment by jakebailey** [comment]
This appears to be a regression introduced in 2021.6.1 as a part of a refactoring done to enable dictionary key completion; they both use the same code to track variable read/writes.

**Comment by picrots** [comment]
+1 from me to hopefully move this to higher priority for fix. TQ

**Comment by jakebailey** [comment]
@picrots I have a fix prepared for review which should make it for next week's release, so no worries there.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.7.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202173-14-july-2021
