### ISSUE TITLE
Allow Pylance auto-import to insert imports at the end of imports 

### ISSUE THREAD

**Issue by submagr** [microsoft/pylance-release#1501]
Pylance auto-import insert the imports at the beginning of the imports. Sometimes it's undesirable (for example, I setup pythonpath on top of script which helps find the imported package)

Please provide a setting to allow imports to be inserted at the end of the imports.

**Comment by erictraut** [comment]
The current algorithm attempts to insert the import in an order consistent with PEP 8 recommendations where imports are grouped by class (stdlib, third-party, local, relative), and within each group, it inserts it alphabetically. If it's a symbol import (using the `from a import x, y, z` syntax), the symbol is also inserted alphabetically. Are you observing a different behavior than what I've described here?

**Comment by submagr** [comment]
Hi Eric,
Thanks for the follow-up. No, I am not observing different behavior. It works perfectly as described.

However, What I am requesting is will help me in the following use case:

```
import sys
from pathlib import Path
root_path = Path(__file__).parent.parent.absolute()
print("Adding to python path: ", root_path)
sys.path = [str(root_path)] + sys.path
```

I have this functionality on top of my file, which sets `PYTHONPATH` appropriately. Now when I use auto-import functionality, the imports are inserted at the top of the file like this:
```
from evaluate.evaluate_model import evaluate_sc_model
import sys
from pathlib import Path
root_path = Path(__file__).parent.parent.absolute()
print("Adding to python path: ", root_path)
sys.path = [str(root_path)] + sys.path

def main():
    evaluate_sc_model
```

In this case, it will give an error as the `PYTHONPATH` is not set appropriately. I am not 100% sure if this is the correct way to handle `PYTHONPATH` but if it is, it would be nice to have auto-import somehow be inserted after the `PYTHONPATH` setup.

**Comment by erictraut** [comment]
Tools like pylance will generally not work well if you dynamically manipulate the import resolution paths like this. While the Python interpreter allows this, it's generally not recommended and is pretty uncommon. There are typically ways to statically configured paths instead. If you are able to switch, it will make your life easier.

**Comment by submagr** [comment]
Got it. Thanks for the explanation.
