### ISSUE TITLE
__iter__ method not defined error

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [microsoft/pylance-release#1502]
## Environment data

-   Pylance language Server version: 2021.6.3 (pyright e66600b2)
-   OS and version: ArchLinux
-   Python version: 3.7.3

## Expected behaviour

No error

## Actual behaviour

GeneralTypeIssues error on subplot of pyplot, when in reality it works fine:

![screenshot_2021-06-25_15-00-05-edit](https://user-images.githubusercontent.com/7454137/123428487-28390b00-d5c6-11eb-9925-38e4b84e847c.png)

And obviously does not give error without it:

![image](https://user-images.githubusercontent.com/7454137/123428781-78b06880-d5c6-11eb-8d00-3bd32e9324bf.png)

And an horrible solution to it can be:

![image](https://user-images.githubusercontent.com/7454137/123430911-fe351800-d5c8-11eb-9f37-0eb4f4bb4062.png)

**Comment by jakebailey** [comment]
The stubs we ship for matplotlib largely aren't for type checking (but for editor features like completion/hover), so may have a few holes like this.

I can see from the docs that subplots can return a single Axes or more than one Axes. I'll have to come up with an overload that can describe that behavior.

**Comment by judej** [comment]
This has been fixed with an update to the matplotlib stubs. If you are still seeing the problem, please reopen. Thanks!
