### ISSUE TITLE
Working autocomplete with error squiggles

### ISSUE THREAD

**Issue by schperplata** [microsoft/pylance-release#1506]
Issue Type: <b>Bug</b>

With version `v2021.6.944021595` VSC shows error squiggles:
![image](https://user-images.githubusercontent.com/8736111/123761790-73069b80-d8c2-11eb-81ab-991c60d95103.png)
... showing two contradictory reports:
![image](https://user-images.githubusercontent.com/8736111/123761929-93365a80-d8c2-11eb-80b9-8d3c7d822a0e.png)

**Broken by the latest update,** since version `v2021.6.2` works as expected:
![image](https://user-images.githubusercontent.com/8736111/123762263-ec9e8980-d8c2-11eb-9a88-2d2dd3104f25.png)

Extension version: 2021.6.3
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.39GB free)|
|Process Argv|--crash-reporter-id 919e0ed9-46f3-4ad4-9e28-f35755bf8266|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30323308
vscorehov:30309549
vscod805:30301674
pythonvspyt200cf:30329804
binariesv615:30325510

```

</details>

**Comment by jakebailey** [comment]
The last version of pylance included a change in pyright to the diagnostics reported by the "basic" mode; it now reports the misuse of potentially `None` values. This was an intentional change; see https://github.com/microsoft/pyright/discussions/1969.

You can change your diagnostic severity overrides if you wish to return to the old behavior.
