### ISSUE TITLE
Globally-accessible variables provided by a library being flagged as undefined

### ISSUE THREAD

**Issue by ejenk0** [microsoft/pylance-release#1513]
```
from direct.showbase.ShowBase import ShowBase
from panda3d.core import WindowProperties

class Game(ShowBase):
    def __init__(self):
        ShowBase.__init__(self)

        properties = WindowProperties()
        properties.setSize(1000, 750)
        self.win.requestProperties(properties)
        self.disableMouse()
        self.environment = loader.loadModel("Models/Environment/environment")
        self.environment.reparentTo(render)


game = Game()
game.run()
```
Using the Panda3D library I am following a tutorial for it. Both `loader` and `render` are flagged as being undefined where in reality they function exactly as they should and are provided by the library.
![image](https://user-images.githubusercontent.com/74844913/124066277-bbb58480-da7b-11eb-99f0-c8032547008c.png)

![image](https://user-images.githubusercontent.com/74844913/124066209-9b85c580-da7b-11eb-99e1-2dc391d2ca71.png)

Tutorial page:
https://arsthaumaturgis.github.io/Panda3DTutorial.io/tutorial/tut_lesson02.html

How can I make pylance ignore this type of thing or figure out that they are valid?

**Comment by erictraut** [comment]
By "globally-accessible", I presume that you mean that the library is injecting symbols into your module's namespace? If so, that is covered in this issue: https://github.com/microsoft/pylance-release/issues/1203.

**Comment by ejenk0** [comment]
Thank you, that issue answers my question. I did search around because I hate being the guy to clog the forums with duplicates but I didn't have a proper understanding of the issue to search the right keywords. Thank you!
