### ISSUE TITLE
Strange warning on app.py of Flask, on Windows

### ISSUE THREAD

**Issue by JMGrenhas** [microsoft/pylance-release#1516]
## Environment data
Visual Studio Code, Version: 1.57.1 (user setup)
OS: Windows_NT x64 10.0.19043
Pylance v2021.6.3
ms-python.python v2021.6.9440

## Expected behaviour
No error should be signaled, I think.

## Actual behaviour
On a file app.py, written for Flask, pylance signals an error on code like 
@app.route("/analyse", methods=['POST'])
or
@app.route('/uploader', methods=['GET', 'POST'])

Error message:
Argument of type "() -> Text | None" cannot be assigned to parameter of type "_VT@route"
  Type "() -> Text | None" is incompatible with bound type "_ViewFunc" for type variable "_VT@route"
    Type "() -> Text | None" cannot be assigned to type "_ViewFunc"
      Type "() -> Text | None" cannot be assigned to type "(*args: Any, **kwargs: Any) -> NoReturn"
      Type "() -> Text | None" cannot be assigned to type "(*args: Any, **kwargs: Any) -> _ViewFuncReturnType"
        Function return type "Text | None" is incompatible with type "NoReturn"
          Type "Text | None" cannot be assigned to type "NoReturn"
        Function return type "Text | None" is incompatible with type "_ViewFuncReturnType"
          Type "Text | None" cannot be assigned to type "_ViewFuncReturnType"

**Comment by erictraut** [comment]
Could you provide a minimal self-contained piece of code that exhibits the error? Thanks!

**Comment by JMGrenhas** [comment]
Hope it helps:
`from flask import Flask, render_template, request
app = Flask(__name__)
#---
@app.route("/analyse", methods=['POST'])
def analyse():
  return analyse_router(request)

# (This would be defined in another .py:)
def analyse_router(request):
  if request.method == 'POST':
    # Obter valor do campo rawtext do formulário.
    rawtext = request.form['rawtext']
    #etc...

    return render_template('dsl.html', received_text=rawtext)
#---
nPort = 5002
if __name__ == '__main__':
  app.run(host="localhost", port=nPort, debug=True)`

**Comment by erictraut** [comment]
According to the flask type stubs, this decorator cannot be applied to a function that returns `None`, but `analyse_router` might return `None`. The error message is a bit contorted, but that's because the types involved in this example are very complex.

This change makes the error go away:
```python
def analyse():
  return analyse_router(request) or ""
```

Alternative, you could add the following line to the end of `analyze_router`:
```python
    raise Exception("Should never get here")
```

Or, if you're certain that `analyse_router` will never be called for a method other than `POST`, you can remove the `if` statement and replace it with `assert request.method == "POST"`.

**Comment by JMGrenhas** [comment]
OK, it helped! May be the error message could be more clear.
Thanks for the good work!
