### ISSUE TITLE
No definition found with PyLance

### ISSUE THREAD

**Issue by EzR1d3r** [microsoft/pylance-release#1518]
So i have the following folder structure (peek example from project), VS Code IDE.

`project/service/ui/screen/base/main_screen.py`
```
class MainScreen():
    pass
```

`project/service/ui/screen/base/__init__.py`
```
import service.ui.screen.base.main_screen
```

`project/service/ui/ui.py`
```
import service.ui.screen.base as base_screens


class UiService:
    def __init__(self):
        self.cell_not_opened_screen = base_screens.main_screen.MainScreen()
```

When PyLance is on I cant go to MainScreen definition from ui.py with F12, when is off - it works.

**Comment by erictraut** [comment]
Your code is relying on a dynamic side effect of the Python import resolution process that happens to work at runtime but is a fragile assumption to make.

The code within `__init__.py` should be changed to one of the following:
```python
from . import main_screen
```

Or if you have some aversion to relative imports within a module:
```python
import service.ui.screen.base.main_screen as main_screen
```

If you make this change, Pylance will work as expected and your code will no longer rely on this fragile import resolution side effect.

**Comment by EzR1d3r** [comment]
> Your code is relying on a dynamic side effect of the Python import resolution process that happens to work at runtime but is a fragile assumption to make.
> 
> The code within `__init__.py` should be changed to one of the following:
> 
> ```python
> from . import main_screen
> ```
> 
> Or if you have some aversion to relative imports within a module:
> 
> ```python
> import service.ui.screen.base.main_screen as main_screen
> ```
> 
> If you make this change, Pylance will work as expected and your code will no longer rely on this fragile import resolution side effect.

Thank you, I assumed it. I prefer the second way. However, I checked - that definition resolution works in PyCharm.

**Comment by bschnurr** [comment]
Marking this as closed for now.
