### ISSUE TITLE
Unexpected 'Object of type "None" cannot be called (reportOptionalCall)' messages

### ISSUE THREAD

**Issue by eddyg** [microsoft/pylance-release#1519]
## Environment data

-   Language Server version: 2021.6.3
-   OS and version: macOS 10.15.7
-   Python version: 3.8.7

## Expected behaviour

Pylance should not put a warning on lines like this:

```
    self.ref.register_event("test")(self._test_event_handler)
```

For reference, `self.ref.register_event` is typed to return `Optional[Callable[..., Awaitable[Optional[str]]]]`
 
## Actual behaviour

When opening a file that previously had _no_ warnings, I now see warnings like this from Pylance:
```
Object of type "None" cannot be called   Pylance(reportOptionalCall)
```

## Logs

Nothing of note was found in the trace logs.

## Code Snippet / Additional information

Unfortunately I have been **unable** to reproduce this issue in a small, standalone sample. 😞 I'm hoping there's enough info here to give you something to go on.

But to give you some idea, the code in question is architected _kinda_ like this, but with the classes split across multiple modules. (Unfortunately, this code does _**not**_ give the _Object of type "None" cannot be called_ warning that I'm seeing in my other workspace.)

One thing I did notice that may be worth pointing out: if I right-click on `_register` in the `__call__` method of `register_event` (again, in the code where I'm seeing the issue, _not_ the code below) and choose "Go to Definition", VS Code says "**No definition found for _register**" even though the method is there (just further down in the class).
 
```python
class App:
    # Register an event handler (NOTE: can be used as a decorator or as a method)
    def register_event(self, event: str) -> Optional[Callable[..., Awaitable[Optional[str]]]]:
        def __call__(*args, **kwargs):
            functions = list(kwargs) if kwargs else list(args)
            return self._register(list(functions))

        return __call__

    def _register(
        self,
        functions: Sequence[Callable[..., Awaitable[Optional[str]]]]
    ) -> Optional[Callable[..., Awaitable[Optional[str]]]]:
        ...

class Dispatcher:
    def __init__(self, thing) -> None:
        self.app = self.thing.app

    def initialize(self) -> None:
        self.app.register_event("test")(self._test_event_handler)

    async def _test_event_handler() -> None:
        ...
```

**Comment by erictraut** [comment]
This is intended behavior. We recently enabled the `reportOptionalCall` diagnostic check by default in basic type checking mode. This change was based on feedback from users. If you don't want this check on, you can disable it in the settings.

If a value is `None`, you cannot call it. So if a value is a union between `None` and some other callable type, you need to first validate that it's not `None` before you can safely call it. That's what this error is telling you. You can validate it through an if statement (`if x is not None`) or with an assert (`assert x is not None`).

**Comment by eddyg** [comment]
OK, this is really odd. I restarted VS Code (I hit **Cmd-Q** accidentally, thinking I was focused on another app) and now the 7 lines that were just giving me the `reportOptionalCall` warning _no longer_ have any warnings, and I didn't change anything...

I thought maybe something updated, but the Python Language Server item in the Output tab still says **Pylance language server 2021.6.3**.

**Comment by erictraut** [comment]
Do you have typeCheckingMode set to 'basic'? This diagnostic check is off if typeCheckingMode is set to 'off'.

Are other language server features working? For example, do you see text if you hover over a symbol, or does it just say "Loading..."?

**Comment by eddyg** [comment]
Just checked, and I did have typeCheckingMode set to `off`.

I set it to `basic`, and then restarted VS Code for good measure, but the `reportOptionalCall` warnings didn't come back for the file in question. _However_, having typeCheckingMode set to `basic` **does** cause a `reportOptionalCall` warning to show up in the sample code in my original comment.

Other language server features are working fine. For example, I can hover and get this:
<img width="306" alt="ScreenShot 2021-07-02-14 31 55@2x" src="https://user-images.githubusercontent.com/3235109/124315722-5bd5e100-db42-11eb-8849-56ec1adca362.png">
but when I hover over `self._register` the pop-up just says `_register: Unknown`.

But if I go down to where the `_register` method is defined in the class, and hover over `_register` there, it shows the method args in the pop-up.

(Also, I _can_ jump to `_register` from the Breadcrumbs navigation bar, for whatever that's worth.)

**Comment by jakebailey** [comment]
Note that the change to the optional setting default wasn't in the last Pylance release, but will be in the next one, so maybe some of the discrepancies in what squiggles you're seeing are just that.

**Comment by eddyg** [comment]
The issue I mentioned in [https://github.com/microsoft/pylance-release/issues/1519#issuecomment-873191429](this comment) (about `self._register` being listed as "Unknown") are no longer an issue in Pylance language server 2021.7.2 (pyright adb49aaa).

Since the `reportOptionalCall` behavior is intended, and the issue mentioned above has resolved itself, I'm closing this issue.
