### ISSUE TITLE
Incorrect `reportGeneralTypeIssues` when method named same as builtin

### ISSUE THREAD

**Issue by MattiasOlla** [microsoft/pylance-release#1528]
I have an issue where Pylance is wrongly reporting a type error on type hints on a class when there is a method named the same as that type. This might belong on the [Pyright](https://github.com/microsoft/pyright) page, but since I'm getting the error through Pylance, I'm reporting it here.

<h3> Environment data </h3>

-   Language Server version: 2021.6.4-pre.1 (also tested on stable version 1.57.1)
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.6
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

I have a class with a method called `dict`:

```python
class A:
    x: dict[str, int] = {}
    y: list[int] = []

    def dict(self) -> dict[str, int]:
        return self.x
```

This is valid code and runs perfectly (if you're wondering why a method would be named the same as a builtin, what I'm actually doing is subclassing [Pydantic](https://github.com/samuelcolvin/pydantic)s `BaseModel` to override its `dict` method).

<h3> Actual behaviour </h3>

Pylance underlines both `dict` type hints with the message
```
Expected class type but received "(self: A) -> Unknown" Pylance (reportGeneralTypeIssues)
Object of type "(self: A) -> Unknown" is not subscriptable Pylance (reportGeneralTypeIssues)
(method) dict: (self: A) -> Unknown
```

If I rename the method to e.g. `dict1`, it works perfectly. If I rename the method to `list`, the same error moves to the `y: list[int] = []` line.

I'm not seeing anything in the logs.

**Comment by erictraut** [comment]
I'm not able to repro the problem as specified. My guess is that you are using `from __future__ import annotations`. This would explain why you're seeing this, and it's expected behavior. When you enable this feature, all type annotations are effectively treated as though they are forward-declared. That means they are not resolved in code flow order but are instead looked up by scope. In your code example, the scope is the the class, and there is a symbol called `dict` declared within that scope.

There are a couple of ways to work around this issue:

```python
from __future__ import annotations

# Define a type alias
dict_original = dict

class A:
    x: dict_original[str, int] = {}
    y: list[int] = []

    def dict(self) -> dict_original[str, int]:
        return self.x
```

```python
from __future__ import annotations

import builtins

class A:
    # Use fully-qualified builtins.dict to avoid namespace collision
    x: builtins.dict[str, int] = {}
    y: list[int] = []

    def dict(self) -> builtins.dict[str, int]:
        return self.x
```

```python
from __future__ import annotations

# Use "Dict" from typing
from typing import Dict

class A:
    x: Dict[str, int] = {}
    y: list[int] = []

    def dict(self) -> Dict[str, int]:
        return self.x
```

**Comment by MattiasOlla** [comment]
You are right @erictraut, I was using `from future import annotations`. In my case, it wasn't necessary (must be left from an earlier version), so I just removed it, but I will keep your excellent examples in mind in the future. Thanks for the help!
