### ISSUE TITLE
Type detection completely ignores decorator

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1532]
## Environment data

-   Language Server version: 2021.6.3
-   OS and version: Windows 10 1909
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6 64-bit

## Expected behaviour

The type detector should detect the parameter type and the return type of the function **applied the decorator to**.

## Actual behaviour

The type detctor just ignores the decorator and shows the parameter type and the return type of the original function. Here's an example. The text in the red circle is `int` instead of `str`.
![屏幕截图 2021-07-07 093356](https://user-images.githubusercontent.com/62426149/124687623-d79ba900-df07-11eb-8be9-9ec2b47b76a3.png)

## Logs

```
None
```

## Code Snippet / Additional information

```python
def to_string(func):
    return lambda: str(func())


@to_string
def func():
    return 10


func
```

**Comment by jakebailey** [comment]
This is currently working as expected; we currently treat decorators without type annotations as not changing the signature of the function they decorate.

In your case, that's obviously not the case, but we've found that the vast majority of decorators in library code don't change the signature, but are too difficult to use type inference on (and we hit issues with the wrong types being displayed, docstrings being obscured, etc).

The current behavior was chosen to cause the least problems for users using libraries without type annotations but heavy use of decorators (e.g. tensorflow, sklearn, numpy, etc).

**Comment by erictraut** [comment]
Here's how you would need to annotate your decorator if you want its types to be honored:

```python
from typing import Any, Callable
from typing_extensions import ParamSpec

P = ParamSpec("P")

def to_string(func: Callable[P, Any]) -> Callable[P, str]:
    return lambda: str(func())
```
