### ISSUE TITLE
Allow "home" tilde symbol (~) to be used with extraPaths setting

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/pylance-release#1535]
I finally figured out how to fix the issue of all the unresolved imports from the same workspace in my Python code. The README explains how to set `python.analysis.extraPaths` to point to any additional "root" folders that should be checked for imports, and I realized that the parent directory was the one to include:
```
python.analysis.extraPaths: [".."]
```
Out of a personal preference, I figured I'd rather specify the path relative to my home directory instead because I wanted to avoid the parent-referencing `..`. Easy enough.
```
python.analysis.extraPaths: ["~/python-project"]
```
Only one problem: it doesn't work. I suspect it's because this setting currently does not support the ~ token to represent the home directory.

**Comment by erictraut** [comment]
The tilde is a platform-specific (and shell-specific) convention whereas VS Code settings are mean to be platform-agnostic. 

The `extraPaths` setting was intended to reference subdirectories within your workspace. It sounds like you're using it to point to directories outside of your workspace, so you're using absolute paths. I'm curious to understand your use case better.

**Comment by jakebailey** [comment]
It's a shell specific thing, though I do think that the core extension may convert that to the home directory for all OSs in some of its settings already.

I too am interested in your setup; is this a subset of a project such that a multi-root workspace would fare better?

**Comment by JordanLongstaff** [comment]
@erictraut @jakebailey First of all, to your point about different platforms, I'm on Mac Big Sur.

My VS Code workspace file is located in my home directory and includes three folders, all of which are located in the same subdirectory of the home directory. One folder contains a server codebase, which is the only one written in Python. Another folder contains client code for a set of apps running on different platforms that interact with the server. The other folder has some other files that are mainly there for testing purposes. For some reason, Pylance seems to treat the server folder as the workspace root, and it means that all imports of the following form are considered to be unresolved by Pylance:
```
from server.blahblahblah.etc import something_or_other
```
This was fixed by my aforementioned setting of `python.analysis.extraPaths`.

**Comment by jakebailey** [comment]
We assume that the workspace root is the import root, yes, and we'd probably recommend that you open that parent folder as the workspace, not the subdir, as that's where imports are rooted based on your absolute module names.

Conceptually, the code inside that subdir depends on its own name to function; if you move it, the code is identical but fails to run. For example, most repos assume the workspace/repo root are the import root (e.g. you just open https://github.com/pytest-dev/pytest as the workspace, and the module `pytest` is rooted there). If you think about it from the analysis point of view, opening the subdir eliminates that information, as we only see what's inside the workspace; the path to the workspace is not important.

**Comment by JordanLongstaff** [comment]
> we'd probably recommend that you open that parent folder as the workspace, not the subdir, as that's where imports are rooted based on your absolute module names.

I would have done that, but the parent folder has a ton of other files and folders that, by choice, do not get modified in VS Code, and it would be a lot of work to exclude all of them by name. That's why I went with a multi-root workspace, because I knew that I'd only want to look at a few of the folders in the entire parent directory.

**Comment by JordanLongstaff** [comment]
All right, looks like I've found a way to make it work. I'll close this.
