### ISSUE TITLE
can't go to definition in jupyter

### ISSUE THREAD

**Issue by beijie001** [microsoft/pylance-release#1540]
## Environment data
VS Code version:
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z (1 day ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Jupyter version:
v2021.8.1013163132

Pylance version:
v2021.7.2

Python version：
conda python 3.9.5 64-bit

os version:
Mac OS 11.4

## Expected behaviour

I click Ctrl + function, to go to the definition of the function. 

## Actual behaviour

 it can't work.

## Logs

I enable trace logging by adding "python.analysis.logLevel": "Trace" to your settings.json configuration file. But There isn't  message.

![vscode](https://user-images.githubusercontent.com/11880508/125064855-abd51a80-e0e3-11eb-8e1a-6ac3c555fe28.gif)

**Comment by jakebailey** [comment]
You appear to be using the old Jupyter notebooks, which don't support many advanced features. Can you try with the new notebooks UI instead, which should support navigation?

I believe you can set:

```
    "jupyter.experiments.optInto": [
        "__NativeNotebookEditor__"
    ],
```

To get it in VS Code stable, or install VS Code insiders.

**Comment by beijie001** [comment]
> You appear to be using the old Jupyter notebooks, which don't support many advanced features. Can you try with the new notebooks UI instead, which should support navigation?
> 
> I believe you can set:
> 
> ```
>     "jupyter.experiments.optInto": [
>         "__NativeNotebookEditor__"
>     ],
> ```
> 
> To get it in VS Code stable, or install VS Code insiders.




How do i update the jupyter notebook?
I have two mac book, the one is ok ,the other one is not ok .  they have same vscode version and jupyter version.
i try all the method i can do . It confuse me .

the two mac pro has the same version as flow:
vscode:
Version: 1.58.0 (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

➜  ~ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : not installed
qtconsole        : not installed
ipython          : 7.22.0
ipykernel        : 5.3.4
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : not installed
ipywidgets       : not installed
nbformat         : not installed
traitlets        : 5.0.5

**Comment by jakebailey** [comment]
Try checking the wiki here: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

And if you can't find a working solution, I would file an issue on their tracker.
