### ISSUE TITLE
Type checking in Jupyter notebook

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#1541]
It would be really cool if pylance could do type checking in notebook cells.   Hover and docs are nice, but I'd like it to point out when I've made a mistake in arguments to methods/functions.

**Comment by jakebailey** [comment]
Hm, we should already support this (mostly) if you have type checking enabled; notebooks are given to us as faked files in memory so act like any other file. Are you seeing the diagnostics filtered out in the UI?

**Comment by Dr-Irv** [comment]
Not sure what you mean, but here is what I see.  Note that I have basic type checking on, `math.sqrt("abc")` is picked up in regular python, but not the notebook:
![image](https://user-images.githubusercontent.com/15113894/125138727-2d757a00-e0dd-11eb-9ed1-bdd965e96a7e.png)

**Comment by jakebailey** [comment]
That's exactly what I was looking for, yeah. Curious.

**Comment by jakebailey** [comment]
Hm, maybe this is just an issue with old notebooks, as I can get type errors in cells:

![image](https://user-images.githubusercontent.com/5341706/125139304-25114500-e0c5-11eb-9987-5db413248178.png)

![image](https://user-images.githubusercontent.com/5341706/125139329-2fcbda00-e0c5-11eb-93dd-dfe40abca587.png)

Can you try the insiders version of VS Code, or the stable version with this set?

```
    "jupyter.experiments.optInto": [
        "__NativeNotebookEditor__"
    ],
```

**Comment by Dr-Irv** [comment]
Now it works.  I restarted VS Code, which loaded a new version, and it talked about a "new notebook experience", so maybe that was the issue.

The setting you gave was reported as not a valid setting.

**Comment by jakebailey** [comment]
Yes, it's an undocumented experiment. Thanks for confirming that the new notebooks work for these diagnostics!
