### ISSUE TITLE
When the quantity of the argument(s) given doesn't conform to that of the paramter(s) defined, pylance won't show any error

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1543]
## Environment data

-   Language Server version: 2021.7.2
-   OS and version: windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6

## Expected behaviour

Pylance should detect and show errors in the screenshot below

## Actual behaviour

Pylance doesn't show any error, which is unbeneficial to complicated develoment.

## Logs

```
none
```

## Code Snippet / Additional information

Code:
```python
# 2 parameters
def func1(a, b):
    pass

func1(1)  # Only 1 arguments -- Not enough
func1(1, 2, 3)  # 3 arguments -- Too many


# 1 compulsory parameters and 2 optional parameters
def func2(a, b=0, c=0):
    pass

func2(1, 2, 3, 4)  # 4 arguments -- Too many
```
Screenshot:
![屏幕截图 2021-07-10 152217](https://user-images.githubusercontent.com/62426149/125155640-cd8dda80-e193-11eb-8905-aa04b82a7144.png)

**Comment by erictraut** [comment]
If you enable type checking, pylance will emit errors in this case. Simply set `python.analysis.typeCheckingMode` to "basic". By default, type checking is "off" in pylance.

**Comment by erictraut** [comment]
<img width="552" alt="Screen Shot 2021-07-10 at 7 39 46 AM" src="https://user-images.githubusercontent.com/7040122/125164934-0311d400-e152-11eb-993a-a36bac13ba2c.png">

**Comment by CodeCrazy-ywt** [comment]
Solved my problem. Thanks. But I think it's better if 'basic' is by default.

**Comment by erictraut** [comment]
We leave type checking off by default because the vast majority of pylance users do not want type checking, they want only completion suggestions.
