### ISSUE TITLE
[Python] Autocompletion for existing methods and functions definition 

### ISSUE THREAD

**Issue by Razique** [microsoft/pylance-release#1544]
Hi,
I used to work with Jedi, and one neat feature was the fact that the intelisense feature would track my existing function, methods, and class names in the current file, which would then allow me to quickly resuse an existing name:

<img width="725" alt="Screenshot 2021-07-11 at 14 55 02" src="https://user-images.githubusercontent.com/1027278/125211000-aa962000-e292-11eb-89fe-e4da96b18efd.png">

I looked around and couldn't find any similar issue, perhaps my wording wasn't the right one. Is there an existing option for that or would that be a new feature?
Thanks!

Edit: this may not be a Pylance issue but a VSCode issue. I disabled an older Python intelisense extension in a different system and completion still works:

<img width="765" alt="Screenshot 2021-07-11 at 22 03 46" src="https://user-images.githubusercontent.com/1027278/125233651-8fe19c80-e2ce-11eb-8254-b53150785ad7.png">

Edit 2: After deactivating the extension (`v2021.6.944021595`), autocomplete works fine, so for some reason, enabling the extension prevents autocompletion from working:

<img width="620" alt="Screenshot 2021-07-11 at 22 06 02" src="https://user-images.githubusercontent.com/1027278/125233809-e0f19080-e2ce-11eb-8a79-e5cde1592a28.png">

**Comment by jakebailey** [comment]
Pylance by default disables word based suggestions, per #604 https://github.com/microsoft/pylance-release/issues/629#issuecomment-730588797. You can manually enable this rule to get them back.

Additionally, we don't suggest names for new functions/classes/etc by design, per #163. If you re-enable word based suggestions, then VS Code will provide those.

**Comment by Razique** [comment]
Ah indeed, that was the issue.
Thanks for addressing my issue.
