### ISSUE TITLE
"Remove unused imports" removes all imports

### ISSUE THREAD

**Issue by ttSpace** [microsoft/pylance-release#1547]
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/124250612-a150d900-db57-11eb-9579-570bd964ad4c.png)

**Steps to Reproduce**

1. Type a few imports, like import array; import glob; import math
2. Type print(math.cos(10))
3. In the line of import you can see a pattern, then select the "Remove unused imports"
![image](https://user-images.githubusercontent.com/82852072/124252714-d3633a80-db59-11eb-8aef-22312b7041c0.png)

**Actual behavior**

It removes all imports.
![image](https://user-images.githubusercontent.com/82852072/124252894-0b6a7d80-db5a-11eb-9a78-fbb2920114f0.png)

**Comment by rchiodo** [comment]
Yeah repros in VS code.

**Comment by CodeCrazy-ywt** [comment]
@ttSpace please try writing imports in seperate lines, like this:
```python
import array
import glob
import math
math.cos(0)
```
and try using remove unused imports and see whether all imports are removed.

**Comment by ttSpace** [comment]
@CodeCrazy-ywt  You can see it, like this:

![remove_unuesd_import](https://user-images.githubusercontent.com/82852072/125412790-cf54d980-e3f1-11eb-909a-efb9fcf114c6.gif)

**Comment by CodeCrazy-ywt** [comment]
As you can see, it doesn't remove all imports. Is that okay?

**Comment by jakebailey** [comment]
The code action doesn't remove all imports, only the one the quick fix is attached to (per diagnostic), so that's working as expected.

It deleting the full line sounds like a bug, but I don't know if that's because our change is wrong, or if the editor is applying all of the fixes with the same name on the same line at once.

**Comment by CodeCrazy-ywt** [comment]
Actually we seldom write many imports in a single line, so there's no need to worry about that.

**Comment by heejaechang** [comment]
it should be fixed in 2021.8.2 released today (2021.8.19)

**Comment by ttSpace** [comment]
I use it in today's build, is that supposed to happen like the following? I have to click a few times to remove unused import.
Build of Visual Studio:  17.0.0 Preview 4.0 [31702.283.main] 
Build of Python Package: 17.0.21243.2 

![remove_unuesd_import](https://user-images.githubusercontent.com/82852072/131961834-55f3e76f-e502-427c-97dd-37c885489792.gif)

<details>
<p>

```
Info: Info: Pylance language server 2021.8.3 (pyright fa4194fd) startingServer root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist

Info: Info: Info: Warning: Info: No pyproject.toml file found.Setting pythonPath for service "PythonApplication15": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"stubPath C:\Users\vting\source\repos\PythonApplication15\PythonApplication15\typings is not a valid directory.Info: Assuming Python version 3.9


Assuming Python platform Windows

Info: Searching for source filesInfo: Found 1 source file
Info: Info: Background analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(1) started

No configuration file found.
```
</p>
</details>

**Comment by jakebailey** [comment]
Quick fixes are offered per-diagnostic. In VS Code, you can hover over each diagnostic and get a lightbulb per, and that's how the LSP works.

I'm not sure how VS does this, but it looks like it offers a lightbulb per line.

We're doing what we expect (one quick fix per diagnostic), but it seems like this UI only offers up one of them per line, or something. #1722 covers a quick fix that would remove all, but overall I think that this would be something to report on PTVS for investigation, as Pylance isn't behaving incorrectly according to the protocol.
