### ISSUE TITLE
#1993 but for opencv built from source

### ISSUE THREAD

**Issue by ShivamMukherjee** [microsoft/pylance-release#155]
Exactly as the title suggests, refers to https://github.com/microsoft/vscode-python/issues/1993.

OpenCV built with NVIDIA CUDA and cuDNN on.
VS Code: 1.47.2
OS: Windows 10 Home 1909 18363.959

Refer: https://github.com/microsoft/python-language-server/issues/1926

**Comment by jakebailey** [comment]
Dupe of #138; this code is compiled and currently requires a stub.
