### ISSUE TITLE
Auto-completion not working with Open3D library

### ISSUE THREAD

**Issue by chrismeunier** [microsoft/pylance-release#1550]
I have a problem specific to a library: [Open3D](http://www.open3d.org/docs/release/index.html). The code hints appear only for the 1st level of the library... the screenshots below should be pretty self-explanatory.

## Environment data

-   Language Server version: v2021.7.2
-   OS and version: Windows 10 20H2
-   Python version: 3.8.6 64-bit

### Example with Jedi as the language server:
Past the 1st level of the library (p.ex. `o3d.geometry`) all possible suggestions appear:
![Capture d’écran (5)](https://user-images.githubusercontent.com/28230243/125641588-42b95f46-be6d-465f-b0a0-f455744a09c8.png)
And then for a class method:
![Capture d’écran (6)](https://user-images.githubusercontent.com/28230243/125642047-41ed06a1-5703-4a6d-b409-0703bf49ed23.png)

### Now with Pylance as the language server:
Up to here it works:
![1st_level](https://user-images.githubusercontent.com/28230243/125638391-9ae99648-adb9-4265-b100-66346483b68e.png)
Then nothing:
![2nd_level](https://user-images.githubusercontent.com/28230243/125638425-ccd0d145-50a6-44fc-9221-e0c8c33ded76.png)
For a class method:
![method](https://user-images.githubusercontent.com/28230243/125638441-4229fa17-2b58-4161-8048-697f71fa757a.png)

## Logs

```
XXX
```

**Comment by chrismeunier** [comment]
Edit: after checking more of my code I realized that the same problem occurs with **OpenCV** extra modules (with `opencv-contrib-python` package installed), the core functions are completed but the contrib modules are not (like `cv2.aruco`, `cv2.bgsegm`, `cv2.rgbd`...).

And weirdly I found that specific **NumPy** array manipulation routines are also missing, for instance `np.asarray`, `np.asanyarray` ...

**Comment by boris-gu** [comment]
Also caught this problem.
I used `pip install opencv-contrib-python`
![gif](https://media4.giphy.com/media/QW4rF0UTEXxHxZgS2q/giphy.gif)

**Comment by judej** [comment]
Will need to get open3d to create stubs for the libraries for this to work.
