### ISSUE TITLE
Confusion with Modules of the Same Name

### ISSUE THREAD

**Issue by choandrew** [microsoft/pylance-release#1551]
## Environment data

-   Language Server version: Any (2021.7.2)
-   OS and version: Windows 10
-   Python version: Miniconda

## Expected behaviour

Let there be projects `A` and `B` in your conda environment, via eggs, both with the same module name of `module_name`
Thus package files are in
`~/conda/envs/env_name/lib/python3.8/site-packages/A/module_name`
`~/conda/envs/env_name/lib/python3.8/site-packages/B/module_name`

Let the `module_name` of project `A` have submodule `A` and `module_name` of project `B` have submodule `B`

In other words, we have
`~/conda/envs/env_name/lib/python3.8/site-packages/A/module_name/A`
`~/conda/envs/env_name/lib/python3.8/site-packages/B/module_name/B`
as the relevant python modules

I would expect
```python
import module_name.B
```
to work, but it does not, likely because it is looking in the wrong folder (e.g. `site-packages/A/module_name` instead of `site-packages/B/module_name`

## Actual behaviour

Pylance gives a `PylancereportMissingImports` error and cannot do shortcuts like "Go to definition".
This only happens if two modules have the same name.

**Comment by erictraut** [comment]
Why do you have two modules with the same name installed? Is this a legitimate use case? It sounds suspect to me.

Are these namespace modules? If so, then Pylance will apply the sort of logic you're implying — where all namespaces are searched for the full module path. If they're not namespace modules (i.e. there's an `__init__.py` present), then Pylance will apply the traditional import logic where a partial import match will result in a failure. This makes sense given the way that modules are initialized and cached by the Python runtime.

**Comment by choandrew** [comment]
Hey Eric,
Thanks for the reply.

I have two (internal) modules with the same name installed because the module creators didn't take the collision into account years ago.

There are `__init__.py` in both of the modules, so not namespace modules.

The simplest technical solution would naturally be to not have name collisions, but I cannot control the names unfortunately.

**Comment by erictraut** [comment]
You said these are both in egg (zip) files, right? I presume that the Python runtime is able to import either of these by name? If so, then I presume that the Python zip loader has different (undocumented) import resolution logic than the non-zip loader. That's unfortunate, but I guess I shouldn't be surprised given how unnecessarily complicated and inconsistent the rest of the Python import system is.

**Comment by choandrew** [comment]
Yes, these are both in eggs. 
Yes, the Python runtime can import both of them, so `import module_name.A` and `import module_name.B` will both work when _running_ the script.
However, VSCode/PyLance will throw the error when editing it.


So, when both package `A` and `B` are installed, `import module_name.B` creates the error in PyLance, but if only one of them is installed, everything works normally.

**Comment by heejaechang** [comment]
@choandrew is this still repro? I didn't use eggs but I used extraPath to mimic similar situation, but I don't see the issue

basically, I created 2 import roots using "python.analysis.extraPath"

/A and /B

and put lib/A.py and lib/B.py and both of them have ```__init__.py```

and tried to import 2 modules using import lib.A and lib.B and both of them are discovered in the latest release.
