### ISSUE TITLE
Pylance breaks with specific packages

### ISSUE THREAD

**Issue by parasurama** [microsoft/pylance-release#1553]
Issue Type: <b>Bug</b>

Pylance breaks after loading certain packages (for example sentence_transformers https://github.com/UKPLab/sentence-transformers)

```
from sentence_transformers import SentenceTransformer, util
```

Syntax highlighting, error highlighting, autocomplete stops working/becomes very slow if I have the above import line in my file

Extension version: 2021.7.2
VS Code version: Code 1.58.1 (Universal) (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:22:33.013Z)
OS version: Darwin arm64 20.3.0
Restricted Mode: No
Remote OS version: Linux x64 5.3.0-1017-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id ff063a8f-916a-4966-bb68-317ca9914445|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: revel|
|OS|Linux x64 5.3.0-1017-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (32 x 3103)|
|Memory (System)|123.06GB (9.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by jakebailey** [comment]
This library is an extension of `transformers`, which is tracked in #1258.
