### ISSUE TITLE
brackets doesn't delete after cursor moved. 

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#1556]
## Environment data

-   Language Server version: 2021.7.3
-   OS and version: Windows 10.0.19042 64bit
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.1 32bit

## Expected behaviour
`|` supposed as cursor:
```python
print("|")
```
after press right then left, then press `back` button it shoud be this:
```python
print
```
## Actual behaviour

but it shows this:
```python
print')
```

## Code Snippet / Additional information

https://user-images.githubusercontent.com/26390254/125720645-a0b99f3e-f6bb-40d4-9db4-566e46709baa.mp4

**Comment by jakebailey** [comment]
This is implemented by VS Code's cursor; Pylance has no control over this behavior.

If you disagree with this choice, you should file an issue on the VS Code tracker, though I believe that this behavior is intended (as otherwise you have no way to remove just those characters).

**Comment by byehack** [comment]
i found `editor.autoClosingDelete`. this should set to `always`.

Thanks.
