### ISSUE TITLE
VS Code Pylance Issue

### ISSUE THREAD

**Issue by OsamaRF19** [microsoft/pylance-release#1558]
I am a new user to VS code and learning python. I was practicing my code when all of sudden Pylance stopped showing me the variable colors, the function suggestion and other features. Considering this a simple issue, i reinstalled Python, Pylance and still nothing changed. Still the problem wasn't fixed so i reinstalled VS code 3 times after downloading it again from Microsoft website and still it's not working Correctly. Searched on google about this issue but couldn't get the solution. 

This is the error it shows when i use 'python' in output of code:

User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
Python interpreter path: /usr/bin/python3
Error 2021-07-15 09:47:55: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/osama/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/osama/.vscode/settings.json')
	at _handleError (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:167834)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> conda --version

**Comment by OsamaRF19** [comment]
@erictraut Thanks!

**Comment by jakebailey** [comment]
Can you show the output of the "Python Language Server" instead of the plain Python output? That is where we log.

**Comment by OsamaRF19** [comment]
> Can you show the output of the "Python Language Server" instead of the plain Python output? That is where we log.

![Screenshot from 2021-07-15 10-27-16](https://user-images.githubusercontent.com/87461790/125734044-3b46d524-2ce4-40b2-94a1-c067010f0d2b.jpg)

**Comment by jakebailey** [comment]
Hm, curious. Can you bring up the Developer Tools to see if any errors are being reported there? It's available in the command palette ("Toggle Developer Tools") or in the help menu.

**Comment by OsamaRF19** [comment]
> Hm, curious. Can you bring up the Developer Tools to see if any errors are being reported there? It's available in the command palette ("Toggle Developer Tools") or in the help menu.

I would do that as soon as i reinstall VS code, because i uninstalled it and installed VSCode Insider which is apparently working completely fine. I will follow your instructions and get back to you with a feedback asap!

**Comment by OsamaRF19** [comment]
@jakebailey Here are the Screenshots of "Python Language Server" and "Developer Tools" for Console respectively.

![Screenshot from 2021-07-16 09-09-02](https://user-images.githubusercontent.com/87461790/125891878-05267eb5-730f-42e1-a994-eb90bfbd0149.jpg)
![Uploading Screenshot from 2021-07-16 09-06-26.jpg…]()

**Comment by jakebailey** [comment]
The above screenshot implies that Pylance is running; what is the issue you are seeing? Are you sure it wasn't fixed by the reinstall and maybe it was a download corruption?

**Comment by OsamaRF19** [comment]
> The above screenshot implies that Pylance is running; what is the issue you are seeing? Are you sure it wasn't fixed by the reinstall and maybe it was a download corruption?

I have uninstalled and installed VS Code 3 times and it wasn't fixed. My assumption is that the issue is with Python because i have compared the outputs of Python on VS Code and VS Code Insider. 
![Screenshot from 2021-07-17 06-00-40](https://user-images.githubusercontent.com/87461790/126020888-63109e8b-7b58-4b33-8025-1ad8ed572306.jpg)
![Screenshot from 2021-07-17 06-02-07](https://user-images.githubusercontent.com/87461790/126020889-9b0b0390-4418-4fa9-a267-02d46619c2cc.jpg)

**Comment by jakebailey** [comment]
That message isn't produced by Pylance, it's produced by the Python extension, and is harmless.

Is this what you are reporting, or does something else not work? Are you still not seeing completions, hover, etc?

**Comment by OsamaRF19** [comment]
> That message isn't produced by Pylance, it's produced by the Python extension, and is harmless.
> 
> Is this what you are reporting, or does something else not work? Are you still not seeing completions, hover, etc?

This is it apparently, because i can't see the variables color turning blue on getting assigned, same with when i use a function, it doesn't show any auto fill suggestion for functions I'm about to use.

**Comment by jakebailey** [comment]
The error message has nothing to do with Pylance or any of those features.

Can you please enable trace logging and provide the Python Language Server logs? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

Copy and paste it, please, no screenshots.

**Comment by OsamaRF19** [comment]
The output after enabling Tracing:
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
Python interpreter path: /usr/bin/python3
Error 2021-07-20 17:41:38: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/osama/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/osama/.vscode/settings.json')
	at _handleError (/snap/code/70/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:167834)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:9:343940)
	at async p.doesFileNeedToBeFixed (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:581700)
	at async /home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580827
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580773)
	at async p.updateTestSettings (/home/osama/.vscode/extensions/ms-python.python-2021.6.944021595/out/client/extension.js:59:580400)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> conda --version

**Comment by jakebailey** [comment]
That's the Python output, you'd need the Python Language Server output (which you had pulled up in a previous screenshot).

**Comment by OsamaRF19** [comment]
Sorry about that, i confused one for other, here is the python language server, it's very long so here's the text file. It's like 39k lines something!

[Python Language Server.txt](https://github.com/microsoft/pylance-release/files/6852886/Python.Language.Server.txt)

**Comment by jakebailey** [comment]
You're opening your entire home folder as a workspace, so we're getting stuck trying to list out the source files as there are a significant number (plus some symlinks from wine that are causing issues). Can you open just the project you are working on, or not write your code directly in your home?

**Comment by OsamaRF19** [comment]
I tried to remove my workspace from VS code, but i couldn't find how to remove. 
So, i opened new window of VS code, opened an existing code in that window and checked if there is any workspace folder opened, there was none. 
It worked successfully. I can see the colored syntax and the code suggestions, everything is working now. This is the python language server output:

[Info  - 8:58:54 AM] Pylance language server 2021.7.4 (pyright 209f9621) starting
[Info  - 8:58:54 AM] Server root directory: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist
[Info  - 8:58:55 AM] Background analysis(1) root directory: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist
[Info  - 8:58:55 AM] Background analysis(1) started
[Info  - 8:58:55 AM] No pyproject.toml file found.
[Info  - 8:58:55 AM] Setting pythonPath for service "<default>": "/bin/python3"
[Warn  - 8:58:55 AM] stubPath typings is not a valid directory.
[Info  - 8:58:55 AM] Assuming Python version 3.8
[Info  - 8:58:55 AM] Assuming Python platform Linux
Search paths for 
  /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib
  
  src
  modules
  typings
  /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stubs/...
  /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/bundled/stubs
  /usr/lib/python3.8
  /usr/lib/python3.8/lib-dynload
  /home/osama/.local/lib/python3.8/site-packages
  /usr/local/lib/python3.8/dist-packages
  /usr/lib/python3/dist-packages
[Warn  - 8:58:56 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:58:56 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:58:56 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:58:56 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:58:56 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:58:56 AM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 8:58:56 AM] Searching for source files
[Info  - 8:58:56 AM] No source files found.
[FG] parsing: /home/osama/Desktop/Coding/test-4.py (58ms)
[FG] parsing: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 6ms] (197ms)
[FG] binding: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/builtins.pyi (64ms)
[FG] binding: /home/osama/Desktop/Coding/test-4.py (5ms)
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at /home/osama/Desktop/Coding/test-4.py ...
[BG(1)]   parsing: /home/osama/Desktop/Coding/test-4.py (81ms)
[BG(1)]   parsing: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 6ms] (193ms)
[BG(1)]   binding: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/builtins.pyi (88ms)
[BG(1)]   binding: /home/osama/Desktop/Coding/test-4.py (3ms)
[BG(1)]   parsing: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/typing.pyi [fs read 2ms] (61ms)
[BG(1)]   binding: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/typing.pyi (30ms)
[BG(1)]   parsing: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (33ms)
[BG(1)]   binding: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (2ms)
[BG(1)]   parsing: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 1ms] (4ms)
[BG(1)]   binding: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/typing_extensions.pyi (2ms)
[BG(1)]   parsing: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (3ms)
[BG(1)]   binding: /home/osama/.vscode/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib/abc.pyi (1ms)
[BG(1)] getSemanticTokens full at /home/osama/Desktop/Coding/test-4.py (689ms)
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 44:19 at /home/osama/Desktop/Coding/test-4.py (14ms)
Background analysis message: analyze
[BG(1)] analyzing: /home/osama/Desktop/Coding/test-4.py ...
[BG(1)]   checking: /home/osama/Desktop/Coding/test-4.py (43ms)
[BG(1)] analyzing: /home/osama/Desktop/Coding/test-4.py (44ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: resumeAnalysis

**Comment by jakebailey** [comment]
Thanks, this confirms that it's that you're opening the home directory and we're getting stuck.

**Comment by OsamaRF19** [comment]
Yeah, thanks for your time!
I can't help it but ask is that meant to stop working for a ton of files depending on computer hardware or it should still work?

**Comment by jakebailey** [comment]
It's something we have to look into (we have other issues similar to this one), but in general, not opening your specific project causes other issues (e.g imports won't work as you expect), and the code we've written is not written in such a way as to scan literally every file in your home directory.

**Comment by OsamaRF19** [comment]
That is correct. Actually this problem was the reason that i made github account (I'm a Newbie to Python) and it was my first query. 
Again, Big thanks for your time, and I hope you have a great day!
