### ISSUE TITLE
'discord' is not Accessed Pylance (Pylance is grey)

### ISSUE THREAD

**Issue by Pappu2009** [microsoft/pylance-release#1566]
![image](https://user-images.githubusercontent.com/75248542/126034519-215a3d1c-7fbd-4ca7-934e-a0aca0e50ae4.png)

**Comment by Pappu2009** [comment]
Can someone tell me what's wrong in it?

**Comment by Pappu2009** [comment]
I've installed discord with this code "pip install discord.py" I did re install but did not work

**Comment by CodeCrazy-ywt** [comment]
"xxx is not accessed" means that this module is not **used** in your code, it **doesn't** mean this module cannot be imported.

**Comment by jakebailey** [comment]
That's correct; if you don't use the import, well grey it out.

**Comment by Pappu2009** [comment]
but, the code "from discord import commands" from the discord API but still not working

**Comment by Pappu2009** [comment]
and so is "client.run('token')"

**Comment by CodeCrazy-ywt** [comment]
Then you don't need to `import discord`, you can directly `from discord import commands`.
