### ISSUE TITLE
Python language features not working when VS Code is attached to a kubernetes container

### ISSUE THREAD

**Issue by jmusiel** [microsoft/pylance-release#1568]
## Environment data

-   Language Server version: 2021.7.4
-   OS and version: Local OS is Windows 10, remote is Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.13 conda

## Expected behaviour

Intellisense (code completion) and linting working properly always

## Actual behaviour

Whenever I am connected to a kubernetes pod (on a remote cluster) the language server seems to start (at least I can see it say "Pylance language server 2021.7.4 (pyright 209f9621) starting" in the output window) but none of its features (intellisense, linting, etc.) seem to work.

This occurs across multiple kubernetes pods that I have tried opening (all running Ubuntu 20.04), and across multiple local machines I have tried connecting from (all running windows and using the same User VS Code settings).

However, pylance does work when I use VS Code locally on all of these machines, just not when I remote into my kubernetes pods.

## Logs

Hopefully these are the logs you are looking for? I took them from the Python Language Server tab under 'OUTPUT'

```
[Info  - 3:28:35 PM] Pylance language server 2021.7.4 (pyright 209f9621) starting
[Info  - 3:28:35 PM] Server root directory: /home/jovyan/.vscode-server/extensions/ms-python.vscode-pylance-2021.7.4/dist
[Info  - 3:28:35 PM] No configuration file found.
[Info  - 3:28:35 PM] No pyproject.toml file found.
[Info  - 3:28:35 PM] Setting pythonPath for service "jovyan": "/opt/conda/bin/python"
[Warn  - 3:28:35 PM] stubPath /home/jovyan/typings is not a valid directory.
[Info  - 3:28:35 PM] Assuming Python version 3.6
[Info  - 3:28:35 PM] Assuming Python platform Linux
Search paths for /home/jovyan
  /home/jovyan/.vscode-server/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stdlib
  /home/jovyan
  /home/jovyan/typings
  /home/jovyan/.vscode-server/extensions/ms-python.vscode-pylance-2021.7.4/dist/typeshed-fallback/stubs/...
  /home/jovyan/.vscode-server/extensions/ms-python.vscode-pylance-2021.7.4/dist/bundled/stubs
  /opt/conda/lib/python3.6
  /opt/conda/lib/python3.6/lib-dynload
  /opt/conda/lib/python3.6/site-packages
  /home/jovyan/working/ocp-modeling-dev
  /home/jovyan/working/al_mlp
  /home/jovyan/working/amptorch
  /home/jovyan/working/vasp-interactive
  /home/jovyan/working/launch
[Warn  - 3:28:36 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 3:28:36 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 3:28:36 PM] Exception received when installing recursive file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 3:28:36 PM] Searching for source files
[Info  - 3:28:36 PM] Auto-excluding /home/jovyan/.cache/pre-commit/repobvbjtx62/py_env-python3.6
[Info  - 3:28:36 PM] Auto-excluding /home/jovyan/.cache/pre-commit/repodo0y__ft/py_env-python3.6
[Info  - 3:28:36 PM] Auto-excluding /home/jovyan/.cache/pre-commit/repok6rpm4am/py_env-python3.6
```

## Code Snippet / Additional information

```python

```

**Comment by jakebailey** [comment]
Based on your logs, it looks like you're opening the entire home folder as the workspace; we're likely stuck trying to produce the list of user files because home is so huge.

Can you try only opening your project instead, and not the container's entire home?

**Comment by jmusiel** [comment]
Ah yes, that seems to have fixed the issue, thank you!

Is there a hard limit to the number of files I can have in my workspace? Do you know can I exclude certain directories from my workspace while still being able to navigate to them?

It would be a little frustrating to have to open a new vscode window for each of my individual projects since many of them interact with each other.

**Comment by jakebailey** [comment]
There's no hard limit, it's just that we have to perform a scan once at startup and the more complicated the folder stucture, the longer it can take, which is especially true on an entire $HOME. Additionally, the workspace root is where we root imports, so even if we loaded, things would likely not work.

There's a way to explicitly include/exclude files using a `pyrightconfig.json`, but in your case, I think you'd be better served to try out VS Code's multi-root workspaces, which lets you open more than one folder at once.

**Comment by jmusiel** [comment]
I have tried the multiroot workspaces in the past, while it does work it also causes some problems for my workflow. Could it be sufficient to add large directories to the watcher exclude list in VS Code? What about the file exclude list? Or do these have no impact on this pylance issue?

**Comment by jakebailey** [comment]
The watcher exclude list is for VS Code's own file watching, and is unrelated to our internal scan of the workspaces for user files.

You could stick a `pyrightconfig.json` into your home with an exclude block, but I don't know if it will do what you are expecting. https://github.com/microsoft/pyright/blob/main/docs/configuration.md
