### ISSUE TITLE
Code is marked as unreachable, when typing.NoReturn is used.

### ISSUE THREAD

**Issue by arunvkumr** [microsoft/pylance-release#1572]
## Environment data

-   Language Server version: Pylance language server v2021.7.4
-   OS and version: Windows 10 Version 20H2(OS Build 19042.1083)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.6 64-bit

## Expected behaviour

Code should not be marked as unreachable

## Actual behaviour

Code is marked as unreachable code

## Logs

If you try the below mentioned code snippet, the print statement, with context after passmethod, is maked as unreachable by pylance.

## Code Snippet / Additional information

```python
from typing import NoReturn

def passmethod() -> NoReturn:
    pass

def main():
    print('before passmethod')
    passmethod()
    print('after passmethod')
```

**Comment by erictraut** [comment]
This is the correct behavior. `NoReturn` means that the method in question never returns — i.e. it always raises an exception or goes into an infinite loop. By definition, the print statement after the call to `passmethod` is unreachable.

For more details about the intended use of the `NoReturn` type, refer to [PEP 484](https://www.python.org/dev/peps/pep-0484/#id32).

**Comment by bschnurr** [comment]
I think `None` would be better in this case
```
def passmethod() -> None:
    pass
```
