### ISSUE TITLE
Not smart on suggestion.

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#1578]
## Environment data

-   Language Server version: v2021.7.4
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Expected behaviour

For example, in the following code:

```
import pandas as pd
import numpy as np
import pyspark

df_pd = pd.DataFrame()

spark = pyspark.sql.SparkSession.builder.getOrCreate()
df_spark = spark.createDataFrame([
    [1, ]
], ["A"])

a = np.arange(10)
```

I expected I could have suggestions list when I type `spark` and `df_spark` even `a` like in the PyCharm.

## Actual behaviour

It does not work at all.

I even could not get the full Autocomplete and IntelliSense when I type `pyspark`.

For example, it will not give me the suggest of `sql` when I type `pyspark`. But it works well when I switch to `JediLSP` Language Server.

And all of the above behavior works much better in the PyCharm.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by bschnurr** [comment]
Looks like `SparkSession` is not exported from `pyspark/__init__.py`

you'll need to import it directly
`from pyspark.sql import SparkSession`

![image](https://user-images.githubusercontent.com/1946977/126520582-27b1fa5d-d7e3-4e71-acf9-02ee8d7505e8.png)


I am seeing a possible issue with auto-completions not triggering.

you can manually bring up the completions with `ctrl+space`

**Comment by bschnurr** [comment]
Do you have the "Github Copilot" extension install?
I think there might be an issue with it eating our auto-completion after "." trigger

**Comment by gonghenghai** [comment]
Thanks for your response.

I haven't installed the `Github Copilot`. And I tried to disable all extensions and then only open the python related include the Pylance. Nothing has changed.

Follow your steps, `spark` works well, but `df_spark` still does not work, even I type `Ctrl+Space`.

I know of `from pyspark.sql import SparkSession` can work. But it's really not well enough. As it works well when I change to `JediLSP` Language Server, And I need not change to `from pyspark.sql import SparkSession`. And especially when I use the PyCharm, everything is perfect. Of course, I can't compare it with the PyCharm. But I think it's a little weird it really can be smarter, and I think the `JediLSP` was a prototype to learn.

Thanks for your reply again. have a great day : ).

**Comment by gonghenghai** [comment]
And from the comment of the questioner on the SO. We found an interesting thing, As the `Autocomplete and IntelliSense` works perfectly in the `interactive`.

**Comment by erictraut** [comment]
Pylance is doing the right thing here based on the type information provided by the `pyspark` library. It indicates that `SparkSession` is not exported directly from `pyspark`. You must therefore import it from the `pyspark.sql` submodule. You can do this one of two ways:

1. Import the submodule by adding this line to your code:
```python
import pyspark.sql
```

2. Import the symbol directly from the submodule by adding this line to your code:
```python
from pyspark.sql import SparkSession
```

If you think this is an error and that `SparkSession` should be (re)exported directly from the top-level module, then you can file a bug (or even better, submit a PR) to the pyspark repo.

Here is some [documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) for how library authors can provide type information to work with pylance and similar tools.

**Comment by gonghenghai** [comment]
Thanks for your response, got it.

**Comment by gonghenghai** [comment]
Yeah, I agree with that, that's logical. But the interactive is really smart. 

They designed follows the different logic, one of them is as possible as they can, another one: just do the things we need to do. Thanks for your timely response.
