### ISSUE TITLE
"Expected expression" incorrectly reported for valid magic functions

### ISSUE THREAD

**Issue by juandevprojects** [microsoft/pylance-release#1579]
## Environment data

-   Language Server version: Pylance language server 2021.7.4
-   OS and version: Ubuntu 20.04.2 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9

## Expected behaviour

No problems reported.

## Actual behaviour

Pylance reports  "Expected expression" problems in valid magic functions code.

![pylance_magic_functions_report](https://user-images.githubusercontent.com/48599196/126466939-02198d9d-ab9a-4246-8570-261a1c8559b1.png)

## Code Snippet / Additional information

```python
# %%
from IPython.display import display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('mode.chained_assignment','raise')
%load_ext autoreload
%autoreload 2
%matplotlib inline
```

**Comment by jakebailey** [comment]
This is only valid in notebooks; closing in favor of https://github.com/microsoft/vscode-jupyter/issues/6635.
