### ISSUE TITLE
Highlight variables in current for loop, other for loop not

### ISSUE THREAD

**Issue by Yang09701194** [microsoft/pylance-release#1581]
## Environment data

-   Language Server version: 2021.7
-   OS and version: Win10
-   Python version: 3.7

## Expected behaviour

1. Hightlight variable name in for loop only in current loop, in other for loop not highlight same name variable
2. F2 rename variable only in current for loop

## Actual behaviour

In other different for loop, same name variables are hightlight, and when rename all different for loop same name variable are renamed:

<img src="https://i.imgur.com/j6C0Xum.gif"  width="400"/>

**Comment by erictraut** [comment]
In Python (unlike most other languages), for loops don't create a new scope. So the variable in all of these for loops is the same variable. It will retain its value beyond the for loop. Therefore, it would be incorrect for the language server to treat it as though it was scoped to a for loop. 

Consider the following:

```python
for key in d:
    print(key)
print(key)
```

**Comment by Yang09701194** [comment]
thank you for your guidance.

**Comment by CodeCrazy-ywt** [comment]
@eritcraut However, in another for loop, the variable's value is *not* the variable's value in the previous for loop, even if their name are the same. See this code:
```python
for key in d:
    print(key)
for key in d.keys():  # Note that the key's value here is NO LONGER the key's value in the previous for loop.
    print(key)
```
Therefore, to avoid confusion, if a user tries to use the 'Rename Symbol' command to change the name of the variable, only the variable in this for loop (not the whole code) should be changed.

**Comment by erictraut** [comment]
No, it's still the same variable even if it's assigned different values at different locations within the scope.

If you renamed `key` in the following sequence, would you expect it to rename both instances of `key`? I think you would because it's the same variable even though it's assigned different values in the two different lines.

```python
key = 1
key = 2
```
