### ISSUE TITLE
Fields without default values cannot appear after fields with default values

### ISSUE THREAD

**Issue by aressler38** [microsoft/pylance-release#1589]
## Environment data

-   Language Server version: v2021.7.1053846006
-   OS and version: `Linux 28b804342d62 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9

## Expected behaviour

Pylance should not error when we use the attr decorator that sets a default value for an attribute.

## Actual behaviour

Pylance thinks that an attr class using `attr.ib()` and a default function has no default value.

Pylance error: **Fields without default values cannot appear after fields with default values**

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/2053500/126674297-7c54fbe9-8d71-43e0-bf1d-847e6facc000.png)

```
import attr


@attr.s(auto_attribs=True)
class Foo:
    a: int = 1
    b: str = "foo"
    c: bool = attr.ib()

    @c.default
    def _foo_default(self):
        return self.a == 1


f = Foo()

print(f.a)
print(f.b)
print(f.c)

```

**Comment by erictraut** [comment]
This is the intended behavior. You would need to provide a default value using the `default` parameter.

```python
c: bool = attr.ib(default=True)
```

The `attr` library uses non-standard semantics. We've proposed [this extension](https://github.com/microsoft/pyright/blob/main/specs/dataclass_transforms.md) to the Python type system that supports the most common aspects of `attr`, but it doesn't support all behaviors. The use of a `default` decorator is not supported. The workaround is to use some other mechanism.

**Comment by aressler38** [comment]
Okay thanks for the information.
