### ISSUE TITLE
A question about import torch

### ISSUE THREAD

**Issue by StevenTang1998** [microsoft/pylance-release#1594]
<h3> Environment data </h3>

-   Language Server version: 2021.7.5
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Miniconda Python 3.8.10
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off
-   pytorch version: 1.9.0

<h3> Behaviour </h3>

When I type `import torch`, a warning appears - `Import "torch" could not be resolvedPylancereportMissingImports`.

**Comment by jakebailey** [comment]
Do you have the environment where torch is installed selected at the bottom left as your active interpreter? Pylance respects the interpreter chosen by the Python extension.

**Comment by StevenTang1998** [comment]
Thanks for your help, the warning disappears after selecting the environment at the bottom left.
