### ISSUE TITLE
same method name appears twice and redundant object name in code completion

### ISSUE THREAD

**Issue by hanmala123** [microsoft/pylance-release#1595]
## Environment data

-   VS Code version: 1.59.0-insider (system setup)
-   Extension version (available under the Extensions sidebar): v2021.8.1054534874-dev
-   OS and version: Windows 10 19043.1110
-   Python version (& distribution if applicable, e.g. Anaconda): miniconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

no redundant method name and object name

## Actual behaviour

![](https://user-images.githubusercontent.com/35035210/126764708-866ed43a-1d12-4802-b18c-a607b7567fe1.png)
same method name appears twice（tobitmap and im.tobitmap is same method)

![](https://user-images.githubusercontent.com/35035210/126764822-de0d03b9-793f-4c1a-ab17-9b002644969e.png)
when press tab or enter, it will add redundant object name in editor

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

this problem happens in any python code completion

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by jakebailey** [comment]
This is already reported as #1593.
