### ISSUE TITLE
led.value don't working?

### ISSUE THREAD

**Issue by nerawn** [microsoft/pylance-release#1600]
While trying the codes in the pico documentation, I realized that this code does not work. Is it my fault or is it a bug? 

![image](https://user-images.githubusercontent.com/67653782/126912052-4326d3b7-3bf1-4325-bd42-47259b4153d4.png)

**Comment by erictraut** [comment]
Which Python library did you install?

From the screen shot, I don't see how this would work in standard Python. The symbol `led` is being assigned a two-element tuple object, but the `tuple` class doesn't define a `value` method in the Python 3.x standard library.

**Comment by nerawn** [comment]
I use in 3.9.6 version.Which version can I see this method?

**Comment by jakebailey** [comment]
Judging by the code, I think you're using MicroPython. I'm pretty sure you need to be writing:

```python
led = Pin(25, Pin.OUT)
```

Not a tuple.

https://learn.adafruit.com/micropython-basics-blink-a-led/blink-led

**Comment by nerawn** [comment]
That's working. Thanks!

**Comment by erictraut** [comment]
If you copied that code from a sample, you might want to report the bug so others don't hit the same issue.
