### ISSUE TITLE
Hitting return after a period in a comment autocompletes instead of new-lining

### ISSUE THREAD

**Issue by jtlapp** [microsoft/pylance-release#1604]
## Environment data

-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   OS and version: Mac OS 10.15.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: default

## Expected behaviour

When I type a sentence in a comment, end it with a period, and hit return, the editor should insert a return and put me on a new line, at least by default.

## Actual behaviour

When I type a period after a word in a comment, an auto-completion box pops up. If I hit return, intending to start the next line of the comment, I instead get the highlighted completion recommendation. I do this often. This just isn't how comments should work.

![Screen Shot 2021-07-26 at 09 53 22](https://user-images.githubusercontent.com/138133/127025016-6b12d2d1-a1e4-4912-8054-1b7245aeee00.png)

The behavior [has been discussed before](https://github.com/microsoft/vscode-python/issues/1123), but I don't understand its resolution, and that discussion is closed. In any case, if there is a way to disable this behavior, it should be disabled by default, which is not the case with this distribution.

## Steps to reproduce:

Self-evident. Disabling the Microsoft Python extension disables this behavior, which is why I'm this repo.

**Comment by erictraut** [comment]
I'm not able to repro this. Pylance specifically checks for when you're within a comment and does not offer completion suggestions in that context (unless you specifically invoke completions by pressing control-space)

Please verify that you don't have another language server configured. We've received reports previously that the other language servers have this problem.

If you still think this is a pylance issue, please provide specific repro steps.

**Comment by jtlapp** [comment]
Ugh. I'm sorry, I posted to the wrong repo. I was just in the ms-python extension repo, not sure how I landed here.

I have pylance disabled so I can use the latest pyright, with your switch for requiring that member variables be declared in `__init__`.

**Comment by jakebailey** [comment]
You didn't post in the wrong place, no worries, the issue was transferred because you said your LS was set to "default", which is typically Pylance.

**Comment by jtlapp** [comment]
Oh. It does say "default", though:

![Screen Shot 2021-07-26 at 13 05 50](https://user-images.githubusercontent.com/138133/127037175-c99a1581-bfdf-412f-8ce8-7c8a5e3754b2.png)

So do I reopen or repost?

**Comment by jakebailey** [comment]
To clarify, what do you mean by "disabled Pylance"? If you just disable the extension, the Python extension will load Jedi, which may be where you're getting the bad completions. You can check the Python logs or the Python Language Server logs to see what is running.

If you want to not use anything so you can use pyright, you'll have to set your language server setting to "None" to let pyright fully take over.

**Comment by jtlapp** [comment]
I found logs called "2-Python.log" and "9-Python language Server.log" but I can't make sense enough of what I'm seeing to identify a language server.

I set language server to "None" and the problem went away. Thank you soooo much!

Well, I'm glad I landed in Pylance after all. You guys are the best!

**Comment by jakebailey** [comment]
It sounds like you were starting up Jedi, then, yes.

For the record, you can find logs in the Output panel in VS Code; there's a dropdown at the right for various logs. They aren't files.

**Comment by jtlapp** [comment]
I see it. Yes, it's Jedi. I'm looking forward to getting back to Pylance, but they just released a new version and it only brings it up to pyright 1.1.51. :-(

**Comment by jakebailey** [comment]
The current version of Pylance contains that feature: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202175-22-july-2021

**Comment by jtlapp** [comment]
Woo! Thank you! I'm back to using Pylance proper. I somehow ended up in the middle of the change log, which shows change logs for prior versions of Pylance too. Dang, you really got me fixed up.
