### ISSUE TITLE
Python: Function body type hint without assignment is ignored

### ISSUE THREAD

**Issue by ntjess** [microsoft/pylance-release#1612]
Issue Type: <b>Bug</b>

The following code should produce intellisense recommendations for `list` attributes/methods. However, it is still treated as a generic variable.

```python
def test_method(a):
  a: list
  a.<ctrl+space>
```

Compare this to:

```python
def test_method(a):
  a: list = a
  a.<ctrl+space>
```

Which produces the expected result.

Extension version: 2021.7.1060902895
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:30:16.440Z)
OS version: Linux x64 5.8.0-50-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3399)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 1|
|Memory (System)|15.43GB (5.10GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id decd6d22-e356-4931-9723-127dca212b72|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin|
|XDG_CURRENT_DESKTOP|zorin:GNOME|
|XDG_SESSION_DESKTOP|zorin|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30341831
bridge0708:30335490

```

</details>

**Comment by jakebailey** [comment]
I'm not sure that this is valid code; that `a: list` is not an introduction of a variable.

Why are you putting the type annotation in the body of the function as a statement rather than applying it to the parameter itself?

**Comment by ntjess** [comment]
It is certainly valid code (type it in your interactive terminal, it will work without a problem).

As for why anyone would do this: consider the following scenario

```python
no_return_info = lambda: [], 'hi'
a, b = no_return_info()
# How do I know what 'a' is? Type hints
a: list
a.append(5)
# ...
```

In that case, it is a syntax error to provide type hints on initialization. Hopefully that answers your question.

**Comment by erictraut** [comment]
In your original example, the type annotation should be specified on the input parameter. 

```python
def test_method(a: list):
    a.<ctrl+space>
```

The code you posted in your first sample will run in the Python interpreter without generating a runtime exception, but it is not properly using type annotations, so pyright (the type checker that underlies pylance) will see it as an error. So does mypy.

Your second example above involves a local variable rather than an input parameter, so it works as you expect within pylance. Completion suggestions are provided without a problem in this case. However, I'll point out that this is still considered an illegal use of a type annotation by some type checkers. Mypy will not allow this because it requires type annotations to be specified on the first use of a variable. If you move the `a: list` before the assignment to `a`, it will work in mypy as well. Pyright is a bit more flexible in allowing you to annotate a local variable or an instance variable anywhere rather than prior to its first appearance within a file.

**Comment by jakebailey** [comment]
I would think you'd type the above as:

```python
no_return_info: Callable[[], Tuple[List[Any], str]] = lambda: ([], 'hi')
```

But in this case, I would think that type inference gets this correct.

![image](https://user-images.githubusercontent.com/5341706/127371748-98d09acf-1185-4136-84ee-fff88e73b7a6.png)


![image](https://user-images.githubusercontent.com/5341706/127371733-386e57f4-d2a4-43a3-94fe-1e32548c60e6.png)

**Comment by ntjess** [comment]
@jakebailey Right, I was quickly typing an example but in reality I don't have control over `no_return_info` (i.e. it comes from an external definition). Sometimes, those functions can be defined in C or dynamically returning things in which case the default intellisense wouldn't work that way.

@erictraut thank you for your detailed explanation, I wasn't aware of those rules (and have never used mypy before). I encountered the same pylance problem with local variables and my MWE used a function argument since I didn't realize they were treated differently.

Pardon the contrived example, but what about something like this?

```python
import random

class first:
    def whoami(self):
        print('first')
        return 'first'

    def afirstmethod(self):
        print('first method')

class second:
    def whoami(self):
        print('second')
        return 'second'

    def asecondmethod(self):
        print('second method')

def random_class():
    """
    Either returns `first` or `second` 50% of the time.
    """
    if random.random() < 0.5:
        return first()
    return second()

def main():
    x = random_class()
    if x.whoami() == 'first':
        x: first
        # Do things with a `first` object
        x.afirstmethod()
    else:
        x: second
        # Do things with a `second` object
        x.asecondmethod()

if __name__ == '__main__':
    main()
```

mypy didn't complain about any issues for me, but pylance still provides no type suggestions. Is this considered supported?
![image](https://user-images.githubusercontent.com/23620506/127374445-2e17be96-74b6-457f-bdfc-e0b9d36eff2f.png)
![image](https://user-images.githubusercontent.com/23620506/127374341-be145121-07ac-432a-8e80-fd4542fd5d36.png)

**Comment by jakebailey** [comment]
I don't think mypy checks functions that don't have type annotations themselves, so you may not be seeing errors due to that.

**Comment by ntjess** [comment]
You are correct, changing it to `main() -> None` raised mypy errors. Is there any valid way of typing in this kind of scenario?

**Comment by erictraut** [comment]
Yes, Jake is correct. By default, mypy completely ignores the body of a function if its type signature is not annotated, and it always assumes such functions return an `Any` type. Pyright always analyzes code, and it uses type inference for return types wherever possible.

The standard way to distinguish between objects of different types in Python is to use the `isinstance` call. If you do this, pyright will use "type narrowing" to distinguish between the different types. Note that the type of `x` in this case is inferred to be `first | second` (i.e. it's a union type) until it is narrowed to either `first` or `second` based on the test. For more details about type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing).

```python
def main():
    x = random_class()
    if isinstance(x, first):
        x.afirstmethod()
    else:
        x.asecondmethod()
```

**Comment by erictraut** [comment]
Pyright supports another type narrowing pattern that may be of interest here if you don't want to use `isinstance`. You can discriminate types based on a field that is explicitly annotated as a literal type.

```python
from typing import Literal

class first:
    id: Literal["first"] = "first"
    ...

class second:
    id: Literal["second"] = "second"
    ...

...

def main():
    x = random_class()

    if x.id == "first":
        x.afirstmethod()
    else:
        x.asecondmethod()
```

**Comment by ntjess** [comment]
@erictraut In my code base, `first` and `second` are protocol-like, so it's difficult to test for `x`'s type with `isinstance`. However, I do see your point.

The main reason I submitted a bug report instead of accepting the behavior is due to PyCharm providing intellisense inside the branches, but now I realize that is probably custom logic on their side, not something generically supported by Python's typing standards. I'm OK closing this as a result.
