### ISSUE TITLE
Implement smart selection

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#1614]
An ask we have over on PVSC is https://github.com/microsoft/vscode-python/issues/6669 to implement smart selection. I think Pylance could implement this via https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_selectionRange. Probably going to have to be opinionated in terms of what users would expect a selection expansion to look like since I bet everyone has their own view on this. 😁

**Comment by jakebailey** [comment]
This is #266.
