### ISSUE TITLE
Implement folding

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#1616]
https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_foldingRange

This has come up on PVSC a couple of times:
1. https://github.com/microsoft/vscode-python/issues/1847
2. https://github.com/microsoft/vscode-python/issues/15218
3. https://github.com/microsoft/vscode-python/issues/2069
4. https://github.com/microsoft/vscode-python/issues/16579

Couple of special things that Pylance can offer this.

One is folding import statements. Now I don't know if people want _all_ import statement folded or just an import _grouping_.

Two, docstrings. People seem to want to be able to hide them when they are really long. We have https://github.com/microsoft/vscode-python/blob/main/src/client/providers/docStringFoldingProvider.ts for this, but I suspect Pylance could be more robust.

Three, we flat-out don't do it right in some cases. E.g.
```Python
def spam():
   print("hi")
# This becomes it's own fold, dividing the function in half.
   return 42
```

**Comment by jakebailey** [comment]
This is #372.
