### ISSUE TITLE
Intellisense not working at all, even when I press ctrl+space

### ISSUE THREAD

**Issue by cmbrodie** [microsoft/pylance-release#1621]
## Environment data

-   Language Server version: v2021.7.1060902895
-   OS and version: WSL2 running ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Expected behaviour

Intellisense making recommendations
## Actual behaviour

Does nothin
## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
This isn't enough info to help us; our template asks for logs and code samples so we can help, but you haven't provided any. Can you please provide them?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
It's been a month since I asked for the above; I'm going to close this. If you can provide more information about your issue, we can reopen, but this isn't enough to go off of.
