### ISSUE TITLE
Definition not found for string module imports

### ISSUE THREAD

**Issue by wizardion** [microsoft/pylance-release#1623]
## Environment data

-   Version: 1.59.0-insider
-  Date: 2021-07-28T05:13:02.250Z
-  Electron: 13.1.7
-  Chrome: 91.0.4472.124
-  Node.js: 14.16.0
-  V8: 9.1.269.36-electron.0
-  OS: Linux x64 5.11.0-25-generic snap
-   Extension version (available under the Extensions sidebar): 2021.7.1060902895
-   OS and version: Ubuntu
-   Python version: 3.7.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

## Expected behavior

To have the ability "Go To Definition" for  module imports, like it is done in the Pycharm, see screen from the Pycharm.
![2021-07-28_17-16](https://user-images.githubusercontent.com/2981194/127483974-1f1b180d-f763-47dc-b630-affce0b409c2.png)

## Actual behavior

When I click on the "Go To Definition" property from the context menu for string module imports (see screen below), it says definition not found. 
Is there anythingI/we can do with it? Some configurations/settings? Maybe there is an extension that can allow to have this ability? Or it is not supported yet?

![2021-07-28_17-13](https://user-images.githubusercontent.com/2981194/127398272-7480c7d7-8813-4461-9992-c75015932a73.png)

**Comment by jakebailey** [comment]
We have no special cases for django; we treat this as effectively any other string, not some special module name that can be navigated to. This would be a django-specific enhancement.

**Comment by wizardion** [comment]
So I assume that I need to install some Django extension for this, or this case is not possible for vscode until the vscode implements such instructions?

**Comment by jakebailey** [comment]
I'm not aware of any special extension that would do this, no. Pylance is included with the Python extension by default (and is an extension itself), and there aren't any extensions to Pylance to add this, but we are certainly interested in django-related improvements.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
