### ISSUE TITLE
Get no hints when using tensorflow

### ISSUE THREAD

**Issue by wujcan** [microsoft/pylance-release#1625]
I have set
`
    "python.languageServer": "Pylance",
    "python.autoComplete.extraPaths": [
        "D:/Program Files/Anaconda3/envs/tf-gpu/Lib/site-packages",
    ],
`
but get no hints when I use tensorflow. Any solution?
![bug](https://user-images.githubusercontent.com/45536153/127637926-c1960c6f-e77a-4fdc-8d08-725404bcfffb.png)

**Comment by bschnurr** [comment]
you shouldn't have to set extra paths if tensorflow is installed under your selected interpreter

You could try pip installing the latest TF (non conda version)

We might be able help more with logs from the "Python Language Server" output window. see 
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by wujcan** [comment]
> you shouldn't have to set extra paths if tensorflow is installed under your selected interpreter
> 
> You could try pip installing the latest TF (non conda version)
> 
> We might be able help more with logs from the "Python Language Server" output window. see
> https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

I have commented out the settings to set extra paths, but it doesn't work still.
![bug](https://user-images.githubusercontent.com/45536153/127952425-3d9303f4-9837-4682-b2e0-7fad1bd70f86.png)

Here is the log file: [8-Python 语言服务器.log](https://github.com/microsoft/pylance-release/files/6920818/8-Python.log)

But it works well on other packages like numpy.

**Comment by bschnurr** [comment]
my guess is the tensorflow library in conda is old. try to manually pip install the latest tensorflow

**Comment by jakebailey** [comment]
It's been a month since we asked for more info here; if you can test it out with the latest tensorflow, we can reopen this.
