### ISSUE TITLE
Mutable objects(e.g. list) cannot be dictionary keys

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1631]
## Environment data

-   Language Server version: 2021.7.7
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.6

## Expected behaviour

Pylance should report errors

## Actual behaviour

Pylance doesn't report errors

## Logs

```
XXX
```

## Code Snippet / Additional information

Code:
```python
foo_dict = {
    [1, 2]: 4
}
```
Screenshot:
![批注 2021-08-01 163850](https://user-images.githubusercontent.com/62426149/127764983-15dcc0e8-2c66-440f-8f74-76feddce91b5.png)
[Reasons why keys cannot be mutable](https://docs.python.org/3/faq/design.html#why-must-dictionary-keys-be-immutable)

**Comment by erictraut** [comment]
Technically, it's not mutability that makes a key illegal. Rather, a key must be hashable (i.e. it must support the `Hashable` protocol).

There's nothing in the current typeshed type definitions that indicate this requirement. It would be possible for pylance to hard-code this knowledge specifically for dictionary expressions, but it would be an expensive check. Given how frequently dictionary expressions appear in most code, it would slow down analysis.

Mypy does not report an error in this case either.

For these reasons, I'm reluctant to add this check.

**Comment by CodeCrazy-ywt** [comment]
ok, I understand.

**Comment by jakebailey** [comment]
I'm going to close this one, based on the above.
