### ISSUE TITLE
Syntax check is not correct.

### ISSUE THREAD

**Issue by kgflying** [microsoft/pylance-release#1632]
## Environment data

-   Language Server version: Pylance language server 2021.7.7
-   OS and version: Windows 10, update to date
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.6

## Expected behaviour

The code is commented out. So pylance should not prompt the error.

## Actual behaviour
This code

```
#
class Test:
    def Test():
#

'''
class Test:
    def Test():
'''
```

I notice this:

![image](https://user-images.githubusercontent.com/12282281/127766475-8ac30f8a-d0b1-4a3a-9bd6-257c9ea1e3d1.png)

Thanks.

**Comment by CodeCrazy-ywt** [comment]
No, your code is incorrect.
The # comment in line 4 doesn't make any difference.
The docstring beginning from line 6 should be considered part of the function body of Test() and should be indented.

**Comment by erictraut** [comment]
If I run that code in the python interpreter, I receive the following runtime exception:

```
  File "test.py", line 6
    '''
IndentationError: expected an indented block
```

That matches the error provided by pylance. So I think it's doing the right thing here.

**Comment by kgflying** [comment]
Thanks for pointing out. Closed.
