### ISSUE TITLE
False error about a Python module (python-jose)

### ISSUE THREAD

**Issue by Yassineelkasmy** [microsoft/pylance-release#1633]
### The api is running fine , but VSCODE indicates that there is an error (jose module could not be resolved)

Im working on Fastapi app and i noticed a false error for the python module jose _(python-jose[cryptography])_ , i checked that the virtual env is activated and selected in vscode , also all the packages are installed (including python-jose) +  FastApi app is running fine.

**Code**:
from jose import JWTError, jwt

**FastApi**:
INFO:     Started server process [21207]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

**VSCODE error image:**
![1](https://user-images.githubusercontent.com/18315060/127783350-468121cf-e204-4edd-9d68-24ebd03bbfda.png)

**FastApi console log:**
![33](https://user-images.githubusercontent.com/18315060/127783378-015e1534-5f76-4983-858f-2e28707dc027.png)

**Python version :** 
Python 3.8.10 

**pip freeze (requirrements.txt):**

aiofiles==0.7.0
asgiref==3.4.1
bcrypt==3.2.0
cffi==1.14.5
click==8.0.1
cryptography==3.4.7
dnspython==2.1.0
ecdsa==0.17.0
email-validator==1.1.3
fastapi==0.66.0
h11==0.12.0
idna==3.2
motor==2.4.0
passlib==1.7.4
pyasn1==0.4.8
pycparser==2.20
pydantic==1.8.2
PyJWT==2.1.0
pymongo==3.11.4
python-decouple==3.4
python-jose==3.3.0
python-multipart==0.0.5
rsa==4.7.2
six==1.16.0
starlette==0.14.2
typing-extensions==3.10.0.0
uvicorn==0.14.0

**Comment by judej** [comment]
Thanks for the report. Would you please send us the logs when you are seeing this diagnostic? Please see [Troubleshooting](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md) for instructions.

**Comment by jakebailey** [comment]
It's been about a month since this was opened; I'm going to close this. If you can provide the info we've requested, we can reopen this.
