### ISSUE TITLE
Support refactoring in non-.py and untitled files with language mode python

### ISSUE THREAD

**Issue by maple3142** [microsoft/pylance-release#1636]
Issue Type: <b>Bug</b>

1. Create a file called `test.py` and `test.sage` with some content:

```python
def f(x):
    return x + 1
```

2. Make sure that language mode is set to Python in both file.
3. In `test.py`, select `x` and press F2 to rename it to y. It works.
4. In `test.sage`, select `x` and press F2 to rename it to y. It only shows `No results`.

Extension version: 2021.7.7
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.21390
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3593)|
|Memory (System)|7.74GB (0.23GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by maple3142** [comment]
Example video: https://streamable.com/jjqbhs

**Comment by judej** [comment]
Thanks for the report. The code actions for Pylance only work on Python files. 

What kind of file is a .sage file?

**Comment by maple3142** [comment]
> Thanks for the report. The code actions for Pylance only work on Python files.
> 
> What kind of file is a .sage file?

.sage is a file format used by [SageMath](https://www.sagemath.org/), it is basically python files with some syntax addition. I think pylance should work as long as the language mode is selected to `Python` instead of checking file extension.

**Comment by heejaechang** [comment]
it looks like sage syntax is not 100% subset of python syntax, so not sure whether we can support anything above text based features (ex. keyword highlighting you see) and even if it is, we might be able to support some syntactic based features, but we won't be able to support any semantic based features (ex, rename).

have you searched to see whether there is a language server for sageMath for vscode?

**Comment by maple3142** [comment]
> it looks like sage syntax is not 100% subset of python syntax, so not sure whether we can support anything above text based features (ex. keyword highlighting you see) and even if it is, we might be able to support some syntactic based features, but we won't be able to support any semantic based features (ex, rename).

It is not 100% subset of python syntax, but it is possible to write code for SageMath in 100% pure python, so I think pylance could be able to function correctly when it is all pure python as if it is actually a python script.

> have you searched to see whether there is a language server for sageMath for vscode?

Unfortunatedly, there aren't any as for now.

**Comment by jakebailey** [comment]
I would think that this would work, as we already try and handle files without `.py`/`.pyi` extensions (e.g. scripts, untitled files, etc). Maybe things are broken in those types too.

**Comment by corneliusroemer** [comment]
I think the title should be changed to: `Support refactoring in Language Mode: Python even if file not ending in .py`

**Comment by macintacos** [comment]
Just noting here that for convenience when I'm creating Python scripts I leave off the file extension and just use the shebang at the top (`#!/usr/bin/env python`) and set the language of the file in VSCode to Python. I spent probably too much time trying to figure out why these refactoring commands weren't working, until I thought that maybe I just need to add `.py` to the name and then voilà, everything worked.

It feels a bit silly that Pylance doesn't even try refactoring when the filename doesn't match but you've told VSCode that you're dealing with a Python file. If it's too complicated to implement currently, the extension at least give a better error message in the meantime?

**Comment by awf** [comment]
Also fails in notebooks -- is that just because it's named `.ipynb`?

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/issues/2273 https://github.com/microsoft/pylance-release/issues/1360 https://github.com/microsoft/pylance-release/issues/2468

**Comment by heejaechang** [comment]
closing in favor of duped issues.
