### ISSUE TITLE
Check file open mode

### ISSUE THREAD

**Issue by yzhang-gh** [microsoft/pylance-release#164]
It would be great if Pylance can help check whether a file is opened with an appropriate (writable) mode. For example,

```python
with open("hello.txt") as w:
    w.write("hello!")  # <-- Oops, it should have been opened with a writable file mode, e.g. "w".
```

**Comment by erictraut** [comment]
Thanks for the suggestion.

The file open mode is an internal detail of the return object, and it's unfortunately not reflected in the type. The same type is returned regardless of the open mode, so a type checker like Pylance doesn't (nor should) have the knowledge to emit a diagnostic in this case.

**Comment by yzhang-gh** [comment]
Uh, I see. Thanks for the quick response.
