### ISSUE TITLE
import numpy import calculator 

### ISSUE THREAD

**Issue by VinitPoddar** [microsoft/pylance-release#1642]
Not available in built in

**Comment by VinitPoddar** [comment]
Not available in built in

**Comment by judej** [comment]
Would you please some details on the issue? Please look at the troubleshooting guide on how to submit an issue.

thanks

**Comment by CodeCrazy-ywt** [comment]
@VinitPoddar Sorry I don't know what "not available in built in" means. Screenshot, please.

**Comment by jakebailey** [comment]
It's been a over a month since this was opened without a reply, closing. We can reopen if you can explain what you're seeing.
