### ISSUE TITLE
Allow marking source file as not to be auto-imported from

### ISSUE THREAD

**Issue by whardier** [microsoft/pylance-release#1646]
Not able to find any auto-import related requests like this.

I'd like to add in a mark (as a comment) that flags a file in order to skip it from any selection criteria when resolving auto-imports.

Many library maintainers would prefer to use module inheritance in order to persist functional contracts.  They use `__init__.py` and `__all__` lists to help develop a standard interface.

Auto-import behavior in many IDEs often chooses the longest path for an object.  Without going so far as to alter how auto-import works functionally - it would be nice to develop a standard to exclude files from the selection criteria.

**Comment by erictraut** [comment]
> Auto-import behavior in many IDEs often chooses the longest path for an object

In my experience, it's just the opposite. The shortest path for an object is usually preferred. That's the heuristic we use in pylance.

> Many library maintainers would prefer to use module inheritance in order to persist functional contracts.

If library authors can follow [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md), they have complete control over which symbols are exported (and re-exported) from which submodules in their library. Pylance honors the rules specified in this document.

**Comment by whardier** [comment]
> > Auto-import behavior in many IDEs often chooses the longest path for an object
> 
> In my experience, it's just the opposite. The shortest path for an object is usually preferred. That's the heuristic we use in pylance.
> 

Hah.  Sorry that was easy to misread.   I was trying to word this feature request in such a way that didn't prefer shortest or longest path for an import.  I was just pointing out the default IDE behavior seems to go for the longest despite what I want (shortest)

> > Many library maintainers would prefer to use module inheritance in order to persist functional contracts.
> 
> If library authors follow [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md), they have complete control over which symbols are exported (and re-exported) from which submodules in their library. Pylance honors the rules specified in this document.

Understood.

**Comment by jakebailey** [comment]
For libraries, this is actually affected by the indexing setting, as we don't analyze library modules that aren't referenced. If indexing is enabled (`"python.analysis.indexing": true`), then we do a scan over library code and can typically suggest auto-imports from the "best" module.

Can you see if when you enable this setting that you get the auto-imports you're expecting?

**Comment by whardier** [comment]
> For libraries, this is actually affected by the indexing setting, as we don't analyze library modules that aren't referenced. If indexing is enabled (`"python.analysis.indexing": true`), then we do a scan over library code and can typically suggest auto-imports from the "best" module.
> 
> Can you see if when you enable this setting that you get the auto-imports you're expecting?
> 
> (For user files, see #1055.)

Thanks Jake.  I don't have that option (greyed out JSON in system, remove, and workspace settings).  I've seen a few other references on the web about it as well but I'm not sure if it still applies or if I'm somehow behind. ;)

**Comment by jakebailey** [comment]
It's a undocumented experimental option we've been working on for some time and is enabled for insiders (and maybe an experiment in the future). If we document it, we give up the ability to control the default, hence it not being there until we're confident in it. If you set it, it will work.

**Comment by whardier** [comment]
The extra indexing worked really well.  When resolving dependencies using code actions the dropdown helps a lot and the auto-import for fairly distinct names is using the shortest path.. some more common names require simply using code actions to fulfill the import addition.  Thanks!
