### ISSUE TITLE
`"type" is not iterable "__iter__" method not defined`

### ISSUE THREAD

**Issue by JosephTLyons** [microsoft/pylance-release#1647]
<h3> Environment data </h3>

-   Language Server version: 2021.8.0
-   OS and version: darwin x64
-   Python version 3.10.0b3: 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

For error to not show

<h3> Actual behaviour </h3>

The error is displayed

Python Language Server Log
```
[Info  - 11:45:01 PM] Pylance language server 2021.8.0 (pyright dfb796d8) starting
[Info  - 11:45:01 PM] Server root directory: /Users/josephlyons/.vscode/extensions/ms-python.vscode-pylance-2021.8.0/dist
[Info  - 11:45:01 PM] Background analysis(1) root directory: /Users/josephlyons/.vscode/extensions/ms-python.vscode-pylance-2021.8.0/dist
[Info  - 11:45:01 PM] Background analysis(1) started
```

<h3> Code Snippet / Additional information </h3>

```python
try:
    return func(*args, **kwargs)
except exceptions as exception:
    # stuff
```

Where `exceptions` is a `tuple[type]`... a list of exceptions

The error is emitted on the `except` line

<img width="780" alt="CleanShot 2021-08-07 at 01 20 31@2x" src="https://user-images.githubusercontent.com/19867440/128589048-0b0aaa16-8245-4299-a247-a6441017bc44.png">

**Comment by JosephTLyons** [comment]
Seems similar to https://github.com/microsoft/pylance-release/issues/1463

**Comment by erictraut** [comment]
I can't tell from your code snippet what the problem is. Could you provide a complete, self-contained piece of code that exhibits the problem?

**Comment by erictraut** [comment]
The other bug (#1463) turned out to be specific to a lambda within a list expression, so this one is unlikely to be related.

**Comment by JosephTLyons** [comment]
Here's the most minimal form I can make to reproduce the error:

```python
def retry(exceptions: tuple[type]):
    try:
        print("Hello")
    except exceptions as exception:  # Error occurs here
        pass
```

What's odd is if I remove the input parameter and make it a local variable, the error goes away:

```python
def retry():
    exceptions: tuple[type] = (FileExistsError,)

    try:
        print("Hello")
    except exceptions as exception:  # No error here
        pass
```

**Comment by erictraut** [comment]
Your type annotation is incorrect here. It should be `Tuple[Type[BaseException], ...]`. The `except` statement requires one or more classes that derive from `BaseException`. These can be nested within a tuple. In other words, you can have a tuple that contains a tuple that contains multiple classes that derive from `BaseException`. In this case, the type checker is finding `type`, which is neither derives from `BaseException` nor is it iterable.

Also, note that you omitted the `...`, which indicates that the tuple may have multiple entries.

The reason it works with the local variable is that the type of `exceptions` is narrowed upon assignment to a type that is valid.

**Comment by JosephTLyons** [comment]
Ahh I see.  Sorry for misinterpreting that.  I'm newer to using type annotations, I guess I have a bit more learning to do.  Thanks for the help.
