### ISSUE TITLE
Why some operators is marked as none declared?

### ISSUE THREAD

**Issue by sergeos** [microsoft/pylance-release#1649]
Why a some of operators in the code are marked as not declared, but although they work?
![изображение](https://user-images.githubusercontent.com/7515761/128630082-184e6aef-5451-4f2b-b75e-b03b1f82a5f4.png)
I'm work under venv, maybe i need to install more dependencies into my virtual environment?

**Comment by jakebailey** [comment]
`list` is a builtin and we should be able to find it. `isinstance` is also breaking for you, which makes it seem like your Pylance install is broken somehow and the `builtins.pyi` file is broken or not being found.

Did you happen to set `typeshedPaths` or something in your config? Can you try navigating to your `.vscode` folder to manually delete Pylance to get VS Code to download?

**Comment by sergeos** [comment]
Nothing happens. When extension is enabled, operators is marking. 
Folder with ms-python.vscode-pylance-yyyy-x-y i'm delete, then install again from vscode extensions.

https://user-images.githubusercontent.com/7515761/128923508-30561f08-c261-4286-b3ca-22abfd72f261.mp4

**Comment by jakebailey** [comment]
Can you provide trace logs? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

Our issue template asks for them, but you seemed to have not used the template.

I'm wondering if this is due to non-ascii characters in paths, or something.

**Comment by sergeos** [comment]
Is this trace nedeed?
<details> 
[Info  - 23:04:04] Pylance language server 2021.8.0 (pyright dfb796d8) starting

[Info  - 23:04:04] Server root directory: c:\Users\compuser\.vscode\extensions\ms-python.vscode-pylance-2021.8.0\dist

[Info  - 23:04:04] No configuration file found.

[Info  - 23:04:04] No pyproject.toml file found.
[Info  - 23:04:04] Setting pythonPath for service "MiniParser3": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe"
[Warn  - 23:04:04] stubPath c:\Projects\MiniParser3\typings is not a valid directory.
[Info  - 23:04:04] Assuming Python version 3.7
[Info  - 23:04:04] Assuming Python platform Windows
Search paths for c:\Projects\MiniParser3
  c:\Projects\MiniParser3
  c:\Projects\MiniParser3\typings
  c:\Users\compuser\.vscode\extensions\ms-python.vscode-pylance-2021.8.0\dist\bundled\stubs
  c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\DLLs
  c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib
  c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64
  c:\Users\compuser\AppData\Roaming\Python\Python37\site-packages
  c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\site-packages
[Info  - 23:04:04] Searching for source files
[Info  - 23:04:04] Auto-excluding c:\Projects\MiniParser3\myEnv
[Info  - 23:04:04] Found 5 source files
[FG] parsing: c:\Projects\MiniParser3\parse_helper.py (90ms)
[FG] binding: c:\Projects\MiniParser3\parse_helper.py (11ms)
[Info  - 23:04:05] Background analysis(1) root directory: c:\Users\compuser\.vscode\extensions\ms-python.vscode-pylance-2021.8.0\dist
[Info  - 23:04:05] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens full
[BG(1)] getSemanticTokens full at c:\Projects\MiniParser3\parse_helper.py ...
[BG(1)]   parsing: c:\Projects\MiniParser3\parse_helper.py (88ms)
[BG(1)]   binding: c:\Projects\MiniParser3\parse_helper.py (14ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\typing.py [fs read 4ms] (151ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\typing.py (36ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\collections\__init__.py [fs read 4ms] (96ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\collections\__init__.py (27ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\collections\abc.py [fs read 1ms] (4ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\collections\abc.py ...
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\_collections_abc.py [fs read 2ms] (59ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\_collections_abc.py (22ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\collections\abc.py (83ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\abc.py [fs read 1ms] (9ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\abc.py (3ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\__init__.py [fs read 2ms] (6ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\__init__.py ...
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\base_events.py [fs read 2ms] (107ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\base_events.py (45ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\coroutines.py [fs read 3ms] (29ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\coroutines.py (6ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\events.py [fs read 1ms] (49ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\events.py (17ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\futures.py [fs read 2ms] (22ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\futures.py (6ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\locks.py [fs read 1ms] (21ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\locks.py (10ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\protocols.py [fs read 2ms] (5ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\protocols.py (2ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\runners.py [fs read 1ms] (7ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\runners.py (1ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\queues.py [fs read 1ms] (7ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\queues.py (5ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\streams.py [fs read 2ms] (20ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\streams.py (16ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\subprocess.py [fs read 1ms] (8ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\subprocess.py (8ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\tasks.py [fs read 2ms] (22ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\tasks.py (13ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\transports.py [fs read 2ms] (6ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\transports.py (3ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\windows_events.py [fs read 1ms] (40ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\windows_events.py (24ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\__init__.py (513ms)
[BG(1)]   parsing: c:\Projects\MiniParser3\helpers.py [fs read 1ms] (16ms)
[BG(1)]   binding: c:\Projects\MiniParser3\helpers.py (3ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\functools.py [fs read 2ms] (31ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\functools.py (14ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\keyword.py [fs read 1ms] (4ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\keyword.py (1ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\operator.py [fs read 1ms] (11ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\operator.py (9ms)
Loading ONNX runtime...
Loaded ONNX runtime. Creating IntelliCode session...
Created IntelliCode session.
[BG(1)]   parsing: c:\Projects\MiniParser3\progress_print.py [fs read 1ms] (3ms)
[BG(1)]   binding: c:\Projects\MiniParser3\progress_print.py (1ms)
[BG(1)]   parsing: c:\Projects\MiniParser3\models.py [fs read 1ms] (3ms)
[BG(1)]   binding: c:\Projects\MiniParser3\models.py (1ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\os.py [fs read 2ms] (77ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\os.py (30ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\threading.py [fs read 2ms] (28ms)
[FG] parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\typing.py [fs read 6ms] (231ms)
[FG] binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\typing.py (61ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\threading.py (23ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\_threading_local.py [fs read 2ms] (5ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\_threading_local.py (4ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\concurrent\futures\__init__.py [fs read 2ms] (5ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\concurrent\futures\__init__.py (1ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\concurrent\futures\_base.py [fs read 1ms] (14ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\concurrent\futures\_base.py (18ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\inspect.py [fs read 2ms] (118ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\inspect.py (108ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\types.py [fs read 2ms] (11ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\types.py (6ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\base_futures.py [fs read 2ms] (5ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\base_futures.py (1ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\format_helpers.py [fs read 3ms] (6ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\asyncio\format_helpers.py (1ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\traceback.py [fs read 1ms] (34ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\traceback.py (5ms)
[BG(1)]   parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\linecache.py [fs read 1ms] (6ms)
[BG(1)]   binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\linecache.py (2ms)
[BG(1)] getSemanticTokens full at c:\Projects\MiniParser3\parse_helper.py (1976ms)
Background analysis message: analyze
[BG(1)] analyzing: c:\Projects\MiniParser3\parse_helper.py ...
[BG(1)]   checking: c:\Projects\MiniParser3\parse_helper.py (24ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\parse_helper.py (25ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens range
[BG(1)] getSemanticTokens range 0:0 - 40:50 at c:\Projects\MiniParser3\parse_helper.py (14ms)
Background analysis message: resumeAnalysis
[BG(1)] analyzing: c:\Projects\MiniParser3\__main__.py ...
[BG(1)]   parsing: c:\Projects\MiniParser3\__main__.py [fs read 0ms] (2ms)
[BG(1)]   binding: c:\Projects\MiniParser3\__main__.py (1ms)
[BG(1)]   checking: c:\Projects\MiniParser3\__main__.py ...
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\datetime.py [fs read 2ms] (68ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\datetime.py (38ms)
[BG(1)]   checking: c:\Projects\MiniParser3\__main__.py (110ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\__main__.py (113ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\helpers.py ...
[BG(1)]   checking: c:\Projects\MiniParser3\helpers.py (14ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\helpers.py (14ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\models.py ...
[BG(1)]   checking: c:\Projects\MiniParser3\models.py ...
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\ntpath.py [fs read 1ms] (17ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\ntpath.py ...
[BG(1)]       parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\genericpath.py [fs read 1ms] (4ms)
[BG(1)]       binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\genericpath.py (2ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\ntpath.py (19ms)
[BG(1)]     parsing: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\stat.py [fs read 6ms] (13ms)
[BG(1)]     binding: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Lib\stat.py (2ms)
[BG(1)]   checking: c:\Projects\MiniParser3\models.py (66ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\models.py (67ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\progress_print.py ...
[BG(1)]   checking: c:\Projects\MiniParser3\progress_print.py (2ms)
[BG(1)] analyzing: c:\Projects\MiniParser3\progress_print.py (3ms)
Background analysis message: getDiagnosticsForRange
</details>

**Comment by jakebailey** [comment]
Thanks, the logs confirm that we still aren't finding our own typeshed folder, so things are breaking.

I'm not sure what's going wrong; all signs are pointing to a corrupted extension. Can you check to see that our extension folder contains `typeshed-fallback`?

**Comment by sergeos** [comment]
![изображение](https://user-images.githubusercontent.com/7515761/128929724-a08595f9-3c56-4516-a886-bee2e96d9058.png)

**Comment by jakebailey** [comment]
The folder that we list in the logs is:

```
c:\Users\compuser.vscode\extensions\ms-python.vscode-pylance-2021.8.0\dist
```

But the folder above is:

**Comment by sergeos** [comment]
this is my mistake when copying, sorry, that's no confuse.
And when i'm disable Microsoft Python errors marks are disappeared

![изображение](https://user-images.githubusercontent.com/7515761/128930592-f31b92da-c993-43fd-a13f-5a02c7732288.png)

**Comment by sergeos** [comment]
Maybe this two extensions are conflicting?

**Comment by jakebailey** [comment]
If you disable the Python extension, then that disables Pylance too, so that is expected. There's no conflict there.

Are you sure that was a copy paste error and the path does actually contain a slash after your username? I'm looking for a potential reason why we aren't finding our stubs.

Have you set `python.analysis.typeshedPaths` at all?

**Comment by sergeos** [comment]
> Have you set `python.analysis.typeshedPaths` at all?

I can't answer on this question. How can i check this?

P.S. If slash was broken we are can't see errors from Pylance when mouse over operators.

**Comment by jakebailey** [comment]
You can search for it in the UI:

![image](https://user-images.githubusercontent.com/5341706/128931957-461afbde-a35d-48e5-ab47-bc7534e842e8.png)

Then check the tabs to see if it's been set to something.

I'm not sure what your last sentence means, sorry. I'm saying that if the path there is `c:\Users\compuser.vscode\` and not `c:\Users\compuser\.vscode\`, then that is the problem, but if you have hand-edited it and it does have `.vscode` as a path, then it's something else.

**Comment by sergeos** [comment]
typeshedPath is absent. I can't find it in VSCode.

**Comment by CodeCrazy-ywt** [comment]
You mean you can't find it in the settings? If so, then it seems that Python and/or Pylance extension was corrupt.

**Comment by jakebailey** [comment]
If you still have the extension disabled, then it won't show up either. Also consider opening your settings as JSON (it's in the command palette), which may give you better insight into what settings you have set.

**Comment by jakebailey** [comment]
It's been over a month; if you're still experiencing this and can provide settings, we can reopen. Another option might be to reload with `"python.trace.server": "verbose"` set, then provide the trace so we can see what settings we're getting over the wire.
