### ISSUE TITLE
Pylance enabled but always showing problem and unsupported

### ISSUE THREAD

**Issue by acverma** [microsoft/pylance-release#1652]
<h3> Environment data </h3>

-   Language Server version: 2021.8.1-pre.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
What problem are you having? What is saying something is unsupported?

You haven't filled out our template with any info, so we can't really help.
