### ISSUE TITLE
Is to possible to configure pylance with additional custom builtins type definitions for a DSL

### ISSUE THREAD

**Issue by govinda-attal** [microsoft/pylance-release#1653]
Idea is to have use python as base for domain specific language. So certain type stubs which are specific to this DSL can be write code straight in vs code editor without explicit import statements.

appreciate that by default we could have `typings` folder in code workspace to allow usage of custom type stubs.

but when writing actual code we still need to use `import` statement .

`
from custom_types import * 
`

If we could somehow avoid this import statement in vs code editor, given that certain types (to be treated as builtins for this DSL) exist in `typings` directory in a certain file in code workspace.

**Comment by erictraut** [comment]
Pylance doesn't hard-code the list of builtin symbols. These come from the `builtins.pyi` file, and you're free to override it if you'd like to add new builtins symbols. To do so, you can clone the [typeshed github repo](https://github.com/python/typeshed), make local edits, and use the [python.analysis.typeshedPaths](https://code.visualstudio.com/docs/python/settings-reference) setting to point to your modified version. By default, pylance uses a bundle copy of these typeshed stubs.

Another option is to place your additional symbols in a `custom_types.pyi` file and import them under a `TYPE_CHECKING` conditional:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from custom_types import *
```

**Comment by govinda-attal** [comment]
The first option suits our needs better :)
