### ISSUE TITLE
Pylance type detection could be smarter if the return type of a function depends on the argument type.

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1654]
See this code:
```python
from typing import Union
# The return type depends on x's type.
def multiply_by_2(x: Union[int, list[int]]):
    if isinstance(x, int):
        return x * 2
    elif isinstance(x, list):
        return [i * 2 for i in x]
    else:
        raise TypeError
```
**Actual behavior:**
Pylance just lists all the possible return types.
![屏幕截图 2021-08-09 151402](https://user-images.githubusercontent.com/62426149/128671967-61dc5e86-455b-468a-836d-2d5f419e04b0.png)
When I do type hints to narrow the type of `foo`, pylance reports an error.
![屏幕截图 2021-08-09 151443](https://user-images.githubusercontent.com/62426149/128672012-2e1c1a2e-8094-4de9-97a7-e797ecda85f3.png)
And an ugly solution is to use an assert statement every time `multiply_by_2` appears. Why do I call it ugly? What if there are many function calls in my code? There will be a lot of redundant assert statements.
![屏幕截图 2021-08-09 154603](https://user-images.githubusercontent.com/62426149/128674172-ee6d48f9-ff21-4021-9437-f730952f7288.png)

**Expected behavior:**
Pylance can detect the return type according to the parameter type(that may be a little difficult)
Or don't report errors when I do type hints.

**Comment by erictraut** [comment]
Pylance's behavior in this case is prescribed by the typing standard defined in PEP 484. Accordingly, other type checkers like mypy act the same.

Thankfully, PEP 484 considered this case, and it provides a way to annotate a function or method whose return type depends on the argument type(s). This mechanism makes use of a decorator called `@overload`. You would use it like this:

```python
from typing import overload

@overload
def multiply_by_2(x: int) -> int:
    ...

@overload
def multiply_by_2(x: list[int]) -> list[int]:
    ...

def multiply_by_2(x: Union[int, list[int]]):
    if isinstance(x, int):
        return x * 2
    elif isinstance(x, list):
        return [i * 2 for i in x]
    else:
        raise TypeError
```

**Comment by jakebailey** [comment]
Given the above, I'm going to close this.
