### ISSUE TITLE
problem with syntax highlighter when using type annotations

### ISSUE THREAD

**Issue by Badr-MOUFAD** [microsoft/pylance-release#1655]
## Environment data

-   VS Code version: 1.59.0
-   Extension version (available under the Extensions sidebar): v 2021.8.1105858891
-   OS and version: Windows 10 Home 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): v 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: XXX

## Expected behavior

When I write python code I expect to get syntax highlighting, particularly when I write functions with type annotation.

## Actual behavior
However, when I add type annotations, namely the returned type of the function (for instance `-> str`), I lose all syntax highlighting that is below the function.

## Steps to reproduce:

To reproduce this behavior, copy paste this code in the editor

```python
def func_with_type_annotation_1(
    arg1: str, 
    arg2: int
    ) -> str:

    # some code to be excuted
    # another code to be excecuted

    return "a buggy function"

def func_with_type_annotation_2(
    arg1: str, 
    arg2: int
    ) -> int:

    # some code to be executed
    # another code to be executed

    return 0
```

In my case, I get the following:

![bug_vscode](https://user-images.githubusercontent.com/65614794/128644849-5fb419cd-3efa-4351-9f7e-7a3ea8db0c12.png)

**Comment by jakebailey** [comment]
This doesn't break for me when pasting things in.

![image](https://user-images.githubusercontent.com/5341706/128754893-d0858644-608e-4a1e-8286-f479958caf79.png)

If you reload the editor, does it go away? Or does it only happen when you are editing the code?

**Comment by Badr-MOUFAD** [comment]
Unfortunately **no**, 
even if I reload the editor the problem persists.

**Comment by jakebailey** [comment]
Do you have semantic highlighting disabled? Can you provide logs from the `Python Language Server` output window?

**Comment by Badr-MOUFAD** [comment]
1. The editor Semantic highlighting is enabled. 

2. These are the logs of errors:
![logs errors](https://user-images.githubusercontent.com/65614794/128773121-d69fe4cf-099a-45c2-b0cc-a20c69cd2b32.png)

2. These are logs of information:
![logs informations](https://user-images.githubusercontent.com/65614794/128773118-96c44654-78b4-490d-8efe-bf4f951fc3de.png)

3. I get no warning logs

**Comment by jakebailey** [comment]
Thanks. Can you set the log level to trace and post the output?

**Comment by Badr-MOUFAD** [comment]
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (0ms)
[FG] binding: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (0ms)
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1628620305006 at c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py ...
[BG(1)]   parsing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (5ms)
[BG(1)]   binding: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (0ms)
[BG(1)] getSemanticTokens delta previousResultId:1628620305006 at c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (11ms)
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py ...
[BG(1)]   checking: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (1ms)
[BG(1)] analyzing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py ...
[BG(1)]   parsing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (4ms)
[BG(1)]   binding: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (0ms)
[BG(1)]   checking: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (4ms)
[BG(1)] analyzing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (8ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1628620309846 at c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (1ms)
[FG] parsing: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (0ms)
[FG] binding: c:\Users\HP\Desktop\MSDA-skills-extractor\MSDA-jobs-graph\test_py.py (0ms)

**Comment by Badr-MOUFAD** [comment]
The problem was solved with the new update of `Pylance` and `Python` extensions.

![problem solved](https://user-images.githubusercontent.com/65614794/130162737-1c84fb45-83d7-44bf-8036-96d6c89d4029.png)

Thank you for your availability and support!
