### ISSUE TITLE
Pylance reports that the import "matplotlib.pyplot" could not be resolved from source

### ISSUE THREAD

**Issue by fabiograssiotto** [microsoft/pylance-release#1656]
Matplotlib is installed in the virtual env, python environment seems to be correct.

## Environment data
-   Language Server version: Pylance language server 2021.8.1-pre.1
-   OS and version:  Windows 10.0.19042 N/A Build 19042
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6, virtual env.

## Expected behaviour

Import is not flagged as non-resolved

## Actual behaviour

Import is flagged as non-resolved

## Logs

[logs.txt](https://github.com/microsoft/pylance-release/files/6956866/logs.txt)

![image](https://user-images.githubusercontent.com/6299041/128760892-b82ddafa-d462-4361-8d6f-427d92fcfcbc.png)

```

**Comment by jakebailey** [comment]
Did you install `matplotlib` into the environment while VS Code was running? If you reload, does this message go away?

**Comment by fabiograssiotto** [comment]
> Did you install `matplotlib` into the environment while VS Code was running? If you reload, does this message go away?

It was installed before opening the folder in VS Code. After reloading it does not go away.
Thanks,

**Comment by fabiograssiotto** [comment]
> can you show us where the lib is actually installed (full path)? is it under where rnn.py is? or somewhere else?
It is installed in virtual env ""tf" below

$ pwd
/c/Development/ml/Udemy/DL_AZ/tf/Lib/site-packages
 $ ls *mat*
matplotlib_inline:
__init__.py  __pycache__/  backend_inline.py  config.py

matplotlib_inline-0.1.2.dist-info:
INSTALLER  LICENSE  METADATA  RECORD  top_level.txt  WHEEL

tensorflow_estimator:
__init__.py  __pycache__/  _api/  python/

tensorflow_estimator-2.5.0.dist-info:
INSTALLER  METADATA  RECORD  top_level.txt  WHEEL
 $

**Comment by jakebailey** [comment]
I don't see `matplotlib` in that site-packages folder, just another library that isn't matplotlib.

In that terminal where you've shown that `matplotlib` is installed, can you run:

```
$ python -c 'import sys, pprint; pprint.pprint(sys.path)'
```

To look at the search paths that this interpreter is claiming?

**Comment by fabiograssiotto** [comment]
> I don't see `matplotlib` in that site-packages folder, just another library that isn't matplotlib.
> 
> In that terminal where you've shown that `matplotlib` is installed, can you run:
> 
> ```
> $ python -c 'import sys, pprint; pprint.pprint(sys.path)'
> ```
> 
> To look at the search paths that this interpreter is claiming?

Sure -

$ source tf/Scripts/activate
(venv:tf) $ python -c 'import sys, pprint; pprint.pprint(sys.path)'
['',
 'C:\\Python\\Python39\\python39.zip',
 'C:\\Python\\Python39\\DLLs',
 'C:\\Python\\Python39\\lib',
 'C:\\Python\\Python39',
 'C:\\Users\\fabio.grassiotto\\AppData\\Roaming\\Python\\Python39\\site-packages',
 'C:\\Python\\Python39\\lib\\site-packages',
 'C:\\Python\\Python39\\lib\\site-packages\\win32',
 'C:\\Python\\Python39\\lib\\site-packages\\win32\\lib',
 'C:\\Python\\Python39\\lib\\site-packages\\Pythonwin']
(venv:tf) $ pip install matplotlib
Requirement already satisfied: matplotlib in c:\python\python39\lib\site-packages (3.4.2)
Requirement already satisfied: numpy>=1.16 in c:\python\python39\lib\site-packages (from matplotlib) (1.21.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\python\python39\lib\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python\python39\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\python\python39\lib\site-packages (from matplotlib) (8.3.1)
Requirement already satisfied: cycler>=0.10 in c:\python\python39\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\python\python39\lib\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: six in c:\users\fabio.grassiotto\appdata\roaming\python\python39\site-packages (from cycler>=0.10->matplotlib) (1.16.0)
(venv:tf) $

**Comment by jakebailey** [comment]
The environment that you have in your terminal is the global interpreter, not the `tf` virtual environment, even though your terminal appears to be indicating so. If you change your selected interpreter in VS Code at the bottom left to the one matching the output above, then your import should resolve.

But, I think your intent was to use that virtual environment, in which case you need to ensure that it's activated in that terminal; right now it appears to not be actually activated, and the packages aren't installed to the right place.

**Comment by fabiograssiotto** [comment]
Correct - the intent was to use the venv in VS Code. 

I think you are right, matplotlib is not in the virtual env -

(venv:tf) $ tf/Scripts/python -i
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'
>>>

Thank you for your time.

**Comment by donaldKelly17** [comment]
> Did you install `matplotlib` into the environment while VS Code was running? If you reload, does this message go away?

That worked for me  Thank you

**Comment by CyberNord** [comment]
> Correct - the intent was to use the venv in VS Code.
> 
> I think you are right, matplotlib is not in the virtual env -
> 
> (venv:tf) $ tf/Scripts/python -i Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32 Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import matplotlib.pyplot as plt
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ModuleNotFoundError: No module named 'matplotlib'
> 
> Thank you for your time.

I am not sure what you did to resolve the problem. I have got the same issue as you had
