### ISSUE TITLE
Document which paths are searched by autoSearchPaths and make that list configurable

### ISSUE THREAD

**Issue by koenlek** [microsoft/pylance-release#1659]
Currently, the documentation of `python.analysis.autoSearchPaths` says:

```md
Used to automatically add search paths based on some predefined names (like src).
```

With pylance being closed source, it seems impossible to know what list of predefined names it checks... Could we make documentation explicit on the list of paths it automatically checks?

Additionally, can we make that list configurable? Perhaps it's already configurable by means of `python.analysis.extraPaths`, but the documentation on that is unclear on whether it allows wildcards (e.g. `"**/python"`). If wildcards are allowed for that, please make that clear in the docs too.

Also, the relationship to pyright and the possibility to configure pyright directly could probably also be better documented.

Thanks!

**Comment by jakebailey** [comment]
This code is here: https://github.com/microsoft/pyright/blob/295db6af56c36cb11b41f35d2032050a7e85fcf2/packages/pyright-internal/src/common/configOptions.ts#L1457

It's only `src` at the moment, but its intent is that we could add more.

Wildcards are not allowed for extraPaths. #973

Configuration for pyright is hosted in the pyright repo: https://github.com/microsoft/pyright/blob/main/docs/configuration.md

And the relationship is documented in our FAQ: https://github.com/microsoft/pylance-release/blob/main/FAQ.md

**Comment by koenlek** [comment]
Thanks for the fast reply + pointing out the docs! Just adding "py" and "python" to this list would make a huge difference for the large repos I'm working with. Would it be ok if I open a PR for that?

It seems like extraPaths with wildcards (https://github.com/microsoft/pylance-release/issues/973) is going to be the perfect solution for our use case though. Fingers crossed for that to land!

**Comment by jakebailey** [comment]
I'm not sure we'd want to do that; we settled on the current form based on a survey of popular projects, and we're currently working on other improvements to better handle imports in other ways (#68, for example).

What is the structure of your project? Is extraPaths not a good fit for you?

**Comment by koenlek** [comment]
Ok, I'll just put my hopes on https://github.com/microsoft/pylance-release/issues/973 then.

**Comment by jakebailey** [comment]
Sure, though I would still appreciate some info about your usecase; `autoSearchPaths` is a solution, but I'm moreso trying to understand what it is that you're facing.

**Comment by koenlek** [comment]
For example, when working with a large monorepo, python code can be scattered over multiple places. This way, the extraPaths list can end up consisting of hundreds of items, whereas wildcards could probably capture >90% of those already. 

Note that an alternative solution to providing a long list of extraPaths is to link everything together in a venv, but then vscode can end up opening multiple copies of files: at the symlinked path in the venv and at the original path (I've opened a vscode feature request with a proposed solution for that here: https://github.com/microsoft/vscode/issues/130082)...

**Comment by koenlek** [comment]
The latter

**Comment by jakebailey** [comment]
Okay, thanks. I think that #973 is going to be the thing, then.
