### ISSUE TITLE
How do I tell pylance about variables that will be defined in the calling environment?

### ISSUE THREAD

**Issue by cinderblock** [microsoft/pylance-release#1660]
I'm writing some "`extra_scripts`" for a PlatformIO project. These "scripts" are Python files.

They use ["Construction Environments"](https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#construction-environments) to "`Import`" a couple global variables.

I'm new to Python and not sure if these terms mean something more that they imply, but I'm not seeing how I can let pylance know that `Import`, `env`, and `projenv` and not "undefined variables". I'm currently getting a `reportUndefinedVariable` when I start a Hello World script that otherwise works fine:

```py
Import("env")
import configparser

config = configparser.ConfigParser()
config.read(env["PROJECT_CONFIG"])

port = config["env:" + env["PIOENV"]]["monitor_port"]


def before_upload(source, target, env):
    print("Hello, world")
    print(port)


env.AddPreAction("upload", before_upload)
```

I'm not looking to turn off the `reportUndefinedVariable` warning in general, just tell pylance that there are some globals it should know about.

I looked through the extension options but didn't see anything that clearly did what I wanted. Maybe the `./typings` directory?

Thanks for the look.

**Comment by erictraut** [comment]
The symbol `Import` (with a capital `I`) is not built in to Python. I'm guessing that this script is loaded by another script that's dynamically injecting this symbol into the module's namespace. The call to `Import("env")` apparently injects another symbol called `env` into the global namespace. This is highly unusual and an antipattern, but it is possible to do this form of manipulation in Python, which is a very dynamic language. Tools like pylance have no knowledge of these behind-the-scenes manipulation of the global namespace. That explains the errors you're seeing.

Your options are:
1. Simply ignore the errors when you're using scripts for this environment
2. Disable `reportUndefinedVariable` errors for your workspace using pylance's "python.analysis.diagnosticSeverityOverrides" setting
3. Use `# type: ignore` comments at the end of each line to suppress errors on that line
4. Add the following at the top of your script. This tells pylance about the symbols that are being dynamically injected into your script's global namespace.

```python
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    Import: Any = None
    env: Any = {}
```

**Comment by cinderblock** [comment]
@erictraut Thank you. The extra code worked well.

I agree that this felt like an anti-pattern and I was assuming I'd have to do some hack to get it to work.

While it is an anti-pattern, is this something that pylance should support? Or maybe there is a way for PlatformIO to configure pylance and tell it about these extra symbols? Is there a way for me to put that `typing` in `./typings`?

**Comment by jakebailey** [comment]
The only way to achieve this at the moment is to copy all of typeshed, modify `builtins.pyi` to your needs, then configure Pylance to use that copy of typeshed. Not exactly the most maintainable compared to the above, unfortunately.
