### ISSUE TITLE
Something went wrong activating IntelliCode support for Python

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/pylance-release#1664]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.59.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Open VS Code
2. it show the dialog
![image](https://user-images.githubusercontent.com/17985592/128959341-daf58a81-0340-4f32-aa40-1f0f4b67a672.png)

3. VS IntelliCode log:
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at g._tryExecuteCommand (vscode-file://vscode-app/d:/programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1525:3364)
    at vscode-file://vscode-app/d:/programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1525:3245
Error while activating Python: {}

**Comment by jakebailey** [comment]
Does this happen every time, or sporadically?

**Comment by jakebailey** [comment]
Also, can you check your Python Language Server output window to see if Pylance has loaded?

**Comment by jeffreyyjp** [comment]
@rzhao271 My Python Extension is the latest version, and the extensions viewletn doesn't show anything that needed "reload required"

**Comment by jeffreyyjp** [comment]
@jakebailey How can I check my Python Language Server output, could you provide some commands?

**Comment by jakebailey** [comment]
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue contains some instructions on how to get there.

**Comment by jakebailey** [comment]
My current theory (for any message that talks about `loadLanguageServerExtension`) is that the Python extension changed to activate more quickly than it used to; I believe historically the Python extension waited to finish activating until Pylance was loaded, then IntelliCode could wait for that to send this command. I've noticed that the Python extension activation is very fast these days, which to me implies they're no longer waiting for the LS to start to finish activating, which is good, but may break the IntelliCode extension's assumptions.

**Comment by judej** [comment]
Closing stale bug. Please reopen if you are still seeing this issue
