### ISSUE TITLE
False Positive for "Unbound" with a boolean that controls the flow

### ISSUE THREAD

**Issue by thethiny** [microsoft/pylance-release#1668]
## Environment data

-   Language Server version: Pylance language server 2021.8.0 (pyright dfb796d8)
-   OS and version: Windows 10 21H1 19043.1165
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 @580fbb0

## Expected behaviour

No error

## Actual behaviour

> "data" is possibly unboundPylancereportUnboundVariable

## Code Snippet / Additional information

```python
prepared = False
if os.path.isfile(old_file_path):
    data = get_typeddict_items_file(MK11EquipmentType, old_file_path)
    if data.get("version", "") == self.VERSION["equipment"]:
        prepared = True
        print(f"Equipment {location} is already prepared at {old_file_path}")
if not prepared:
    loc = self.extract_database(location, file_hash)
    items = self.parse_database(loc)
    data = get_typeddict_items(MK11EquipmentType, items = items)
    set_typeddict_items_file(MK11EquipmentType, self.equipment_items_file_prepared, data)

return data
```

`prepared` above is initialized to False, so if the `if statement` fails, then it's guaranteed to pass through the 2nd `if`. Using pyright ignore unbound removes the squiggly lines, however the variable `data` remains unbound on return which causes other issues elswhere.

**Comment by erictraut** [comment]
Pyright evaluates and tracks the types of individual variables within the code flow graph, but it doesn't track type relationships between different variables. For example, it doesn't track conditions like "if `prepared` is `Literal[False]`, then the type of `data` is x, but if `prepared` is `Literal[True]`, then the type of `data` is y". Tracking relationships like this would be _really_ difficult — and computationally infeasible. I don't know of any type checkers in any language that do this. 

Without tracking the relationship between `prepared` and `data`, there's no way for pyright to determine that `data` is bound to a value along all paths.

There are cases where you will need to make accommodations to your code to accommodate limitations of type checkers. This is one of those cases. The good news is that such changes typically improve the robustness and readability of your code. (I'll admit that I had to read your code snippet three times to understand what it was doing and convince myself that it was indeed correct.)

Here's one possible solution:
```python
result = None
if os.path.isfile(old_file_path):
    data = get_typeddict_items_file(MK11EquipmentType, old_file_path)
    if data.get("version", "") == self.VERSION["equipment"]:
        result = data
        print(f"Equipment {location} is already prepared at {old_file_path}")
if result is None:
    loc = self.extract_database(location, file_hash)
    items = self.parse_database(loc)
    result = get_typeddict_items(MK11EquipmentType, items = items)
    set_typeddict_items_file(MK11EquipmentType, self.equipment_items_file_prepared, result)

return result
```

**Comment by thethiny** [comment]
Thanks for this comment. I believe that I wasn't clear with my post and I wanted to clarify that I wanted an option to remove the "unbound" type from check, similar to `# type: ignore` and the others just so the return value is correct. For now I've created a function that returns "Any" and defaulting my "data" to it. Though what you've suggested makes more sense than my approach.

**Comment by erictraut** [comment]
Ah, sorry for the misunderstanding.

I'm guessing that you do not have a return type annotation for your function. (I can't tell for sure because you didn't provide the function signature in your sample.) If you include a return type annotation, then pyright won't attempt to infer the return type from the function implementation.

**Comment by thethiny** [comment]
No need to apologize, it was unclear from my part. Thank you this suggestion has worked (kind of) and does what I need it to do.
