### ISSUE TITLE
Go to Symbol in Workspace does not work when set Language Server to Pylance

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#1669]
## Environment data
Build of Visual Studio Code - Insiders: 1.60.0 -insider (user setup)  
Build of python-insider: 2021.9.1125171759-dev 
Build of jupyter-insider: 2021.8.2025984474
Build of Pylance: 2021.8.1

## Steps to reproduce:
1. Set Language Server to Pylance
2. Open new folder in VSC
3. Create test1.py and typing code
```
from math import cos, radians
	
# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
    rad = radians(x)                             # cos works with radians
    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
    return st
	
def main():
    for i in range(0, 1800, 12):
        s = make_dot_string(i)
	print(s)
	
main()
```
4. Create test2.py and typing code:
```
import logging
Log=logging.getLogger(__name__)
	
class Test(logging.Handler):
    pass
def main():
    Log.info("Running main")
```
5. Press Ctrl+Shift+P, select Go to Symbol in Workspace…
6. Verify the symbols in test1.py and test2.py all listed out and any choice of symbols can be positioned successfully

## Actual behaviour
Go to Symbol in Workspace does not work 
![image](https://user-images.githubusercontent.com/59192491/129296735-a8e25d5a-92b6-46b8-b948-0f776eea50d5.png)

**Comment by CodeCrazy-ywt** [comment]
You should input symbols in the input box.
![屏幕截图 2021-08-13 180529](https://user-images.githubusercontent.com/62426149/129341455-85dade0e-5a85-40f8-b104-e77c6a43756e.png)

**Comment by jakebailey** [comment]
This is expected behavior; if I do the same thing with a TypeScript codebase in VS Code and don't put a search query, I also get no symbols. There isn't a way to get a listing of every single symbol in the workspace without providing a query.

![image](https://user-images.githubusercontent.com/5341706/129608569-dc6a770c-28a1-4a4e-bea6-d4f1dcf93c20.png)
