### ISSUE TITLE
Checks should be applied to % format strings 

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1672]
## Environment data

-   Language Server version: v2021.8.1
-   OS and version: Win10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6

## Expected behaviour

1. When %-things is not as many as items at the right-hand side of the % operator, pylance should quiggle out.
2. When the type of an item is not the required type of the corresponding type of the %-thing, pylance should also squiggle out.

## Actual behaviour

Pylance doesn't squiggle out in the above 2 scenarios.

## Logs

```
I don't think it's important here.
```

## Code Snippet / Additional information

```python
string = '%s%d' % 'only one string'
string = '%s%d' % ('only one string', 'a string wrongly put where a number should be', 'redundant')
```

**Comment by erictraut** [comment]
Thanks for the suggestion.

One thought... Old-style format strings are quite fragile in general, so you might want to switch to f-strings if that's feasible. They were introduced in Python 3.6, and they're much safer and easier to work with than the older formatting mechanism. We've replaced most of these old format strings with f-strings in my team's Python code base.

**Comment by CodeCrazy-ywt** [comment]
Emm...that's ok. I just realized that what I'm requesting for may be a little difficult. 😅

**Comment by jakebailey** [comment]
I think I'm going to close this one; this would be pretty hefty for a syntax that has since been replaced by `.format()` and then again by f-strings. Lots to parse the format strings, then checking all of the different conversions (and figuring out which types are valid), etc...
