### ISSUE TITLE
The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted

### ISSUE THREAD

**Issue by Derry-Jay** [microsoft/pylance-release#1673]
The Python Server Crashes Unexpectedly. Am able to run in debug mode but the Linting is not working.

**Comment by Derry-Jay** [comment]
![Uploading geneAPI.py - backend - Visual Studio Code 14-08-2021 17_17_47 (2).png…]()

**Comment by CodeCrazy-ywt** [comment]
log, please

**Comment by Derry-Jay** [comment]
> log, please

Am sorry that it is fixed. And, IMHO, the modification in the settings.json file solved the problem for me.

Anyways, thanks.
