### ISSUE TITLE
autoImportCompletion does not work

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#1678]
## Environment data

-   VS Code version: 1.59.0
-   Pylance Extension version: v2021.8.1
-   Python Extension version: v2021.8.1105858891
-   OS and version: Ubuntu 18.04.5 LTS
-   Python version: 3.8.8 (conda)
-   Type of virtual environment used: conda
-   Value of the `python.languageServer` setting: "Default"

## Expected behaviour

The setting `autoImportCompletion` is available and works as described in two official documentation pages:
- https://code.visualstudio.com/docs/python/editing#_quick-fixes
- https://code.visualstudio.com/docs/python/settings-reference#_python-language-server-settings

## Actual behaviour

The setting "python.analysis.autoImportCompletion" is coloured in grey in my "settings.json" file, which means that there is no such setting, if I understand correctly.

When I type `path.` in an empty file as shown [here](https://code.visualstudio.com/docs/python/editing#_quick-fixes), nothings happens and if I trigger Quick fixes it says "no code actions available".

**Comment by jakebailey** [comment]
Thanks for the note about the docs; we'll get those fixed.

What `path` are you expecting to show up?

Can you set `"python.analysis.indexing": true` or switch to our insiders build and see if that fixes your issue?

**Comment by Yura52** [comment]
> What `path` are you expecting to show up?

I was simply trying to reproduce the official toy example: https://code.visualstudio.com/docs/python/editing#_quick-fixes

> Can you set `"python.analysis.indexing": true` or switch to our insiders build and see if that fixes your issue?

1. `mkdir test` && `code test`, then I created "a.py", then typed `Path` trying to trigger the auto-import `from pathlib import Path`. It didn't work:

<img width="1440" alt="Screenshot 2021-08-16 at 22 03 27" src="https://user-images.githubusercontent.com/8861742/129616496-07e781a5-7669-4656-89bf-ffa469ae737e.png">

2. Then I set the option as you recommended. However, it was not recognized by VSCode:

<img width="1440" alt="Screenshot 2021-08-16 at 22 04 46" src="https://user-images.githubusercontent.com/8861742/129616768-7ea82c4d-7e92-4f3e-9df5-79963f928d5b.png">

3. The unknown-and-undocumented (Ctrl+F "indexing" finds nothing [here](https://code.visualstudio.com/docs/python/settings-reference)) option helped!

<img width="1440" alt="Screenshot 2021-08-16 at 22 05 02" src="https://user-images.githubusercontent.com/8861742/129616869-7aac8446-c08f-46b0-a66b-5b7657c4c5a6.png">

**Comment by jakebailey** [comment]
It not being recognized is expected; this is a feature we're currently working on. Thanks for checking; the behavior you're seeing at the moment is expected.

We'll get the docs updated to fix the typo.

**Comment by jakebailey** [comment]
Sent https://github.com/microsoft/vscode-docs/pull/4760.

**Comment by Yura52** [comment]
> the behavior you're seeing at the moment is expected.

This is a bit confusing, because my impression after reading the docs is that auto-import is a default feature working out-of-the-box.

Is it safe then to use the "indexing" option? Are there any limitations that I should be aware of?

**Comment by jakebailey** [comment]
It's safe, but depending on the workspace, may use more CPU than we'd like. We're currently tweaking it, and it's only enabled in insiders or via an experiment (or by manually enabling it).

Without indexing, we will still offer auto-import completions and quick fixes, but they will only be able to offer imports from code that is referenced somewhere within the open files and those files' dependencies. E.g. if you open an existing project that has a lot of imports already, then it's likely we'll offer something. If you start with a single file with nothing in it, we won't offer much of anything. The indexer is what scans unopened files and libraries to find more things to offer.

**Comment by jakebailey** [comment]
Closing, as the docs are now fixed. Indexing is intended to be enabled for everyone in the future, and we'll include something in the changelogs when that's the case.
