### ISSUE TITLE
Autocomplete stops auto-completing functions when chained

### ISSUE THREAD

**Issue by jtheyer** [microsoft/pylance-release#1695]
## Environment data

-   VS Code version:  1.59.0
-   Extension version (available under the Extensions sidebar):  2021.8.1
-   OS and version:  Windows_NT x64 10.0.19043
-   Python version (& distribution if applicable, e.g. Anaconda):  3.9.0 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions:  Selenium 3.141.0
-   Relevant/affected Python-related VS Code extensions and their versions:  Pylance
-   Value of the `python.languageServer` setting:  Pylance

## Expected behaviour

Autocomplete/suggestions should continue to show available class methods after the first one (when chaining methods).
![image](https://user-images.githubusercontent.com/23281810/130103911-be9b44c7-952d-4f26-8223-ba14b5a96fe6.png)
...Here  ^ I expect to see click(), send_keys(), etc. There's many class methods that should come up, not just the special "__" functions.

## Actual behaviour

Autocomplete works as expected for the first method, then only special/dunder functions are available to choose from in the suggestion box. 
*Note* Usually, but not always, special functions only show up in suggestion box when calling a method that is defined earlier in the source file and has not yet been called with proper highlighting. I.e., perform() is first function defined in ActionChains.py; If perform() is called such that it is yellow (or successfully auto-completed), then placing a "." after perform() will not bring up suggested __()__ functions. 
-- For the most part, trying to do anything after the first successful function/method call is broken.
      Everything explained thus far was working as intended before I updated vscode this morning (2021AUG08). 
This picture may help explain the suggestion box not showing up when trying to chain:
![image](https://user-images.githubusercontent.com/23281810/130109561-78f9889d-4db5-4182-a292-7ac6043d9932.png)

## Steps to reproduce:

1. Install Python extension
2. Set Pylance as language server
3. Create venv 
4. Install Selenium package (pip install selenium) 
5. Import ActionChains (from selenium.webdriver.common.action_chains import ActionChains)
6. Try to chain methods

*Notice only special/dunder methods will show in suggestion box. 

## Alternate Steps to reproduce:
1. Try to chain methods from any class. Selenium is just used here as an example.

## Logs

N/A

**Comment by jakebailey** [comment]
I don't think this is true for any class (selenium is #345).

Can you provide an example with code that you've written? This depends heavily type analysis, so the code matters. Selenium is untyped and likely has some shortcomings.

**Comment by erictraut** [comment]
The [selenium type stubs in typeshed](https://github.com/python/typeshed/blob/master/stubs/selenium/selenium/webdriver/common/action_chains.pyi) appear to be very incomplete (and possibly inaccurate). 

For example, the `reset_action` method is declared to return `None`. It sounds like your expectation is that it returns an `ActionChain`, allowing you to chain together multiple calls.

If you're so inclined, you're welcome to contribute improvements to these type stubs in the typeshed repo. Pylance picks up new type stubs from typeshed on a regular basis, and any improvements to them will help the broader community.

**Comment by jakebailey** [comment]
Bah, I forgot that they added stubgen generated stubs for selenium to typeshed.

**Comment by jtheyer** [comment]
@jakebailey and @erictraut , Thank you both so much for the help! 
  Jake, the link to issue #345 is very helpful and, in combination with Eric's comment, I believe I can help resolve these issues. I still don't understand why they were working until this most recent update, nevertheless, it sounds like adding to the typeshed will _possibly_ help resolve these issues once and for all. 
  I'm relatively new to all this so I'll have to spend time [here](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) learning, as linked by @erictraut in issue #345. 
  This probably solves it, will close the issue as #345 seems to be the proper forum.

**Comment by erictraut** [comment]
The selenium type stubs were recently added to typeshed. That explains why this was previously working for you. Previous to this, there was no type information, so pylance attempted to infer type information directly from the selenium source code. Type inference is often inaccurate, so pylance always prefers type stubs over inferred types. But in this particular case, it appears that the selenium type stubs that someone added to typeshed are inaccurate — even more inaccurate than the type information that pylance was able to infer from the source code.

The best solution to this problem is to fix the selenium type stubs so the type information is accurate and complete. That will require help from someone with an understanding of the selenium library and its interface. If you have some expertise in this area, you could contribute type stub improvements yourself. Or if you don't feel comfortable doing that, it would still be helpful if you filed a bug report in the typeshed repo with details about the issues you're seeing.

@jakebailey, we might want to consider removing the selenium stubs from pyright and pylance until these stubs receive some additional improvements. It sounds like they might be doing more harm than good at the moment.

**Comment by jakebailey** [comment]
Maybe, if they really are that bad. Should probably report this to typeshed, just so it's not lost.

@jtheyer If you downgrade to 2021.7.7, do things improve? 2021.8.0 seems to be the first release we included these stubs.

**Comment by jakebailey** [comment]
(Or, just delete the seleneium stubs from your extension folder to see.)

**Comment by jtheyer** [comment]
@erictraut , Thank you for the detailed explanation; Which I can confirm describes the case accurately. Also, I do have some expertise with this library and would love to help with type completeness.
@jakebailey , I have not downgraded at time of writing this  (was not apparent how after a quick look over the extension, I don't know how) but after removing the Selenium stubs from pylance's /typeshed-fallback things did improve. Everything has returned to what I would expect.

**Comment by jtheyer** [comment]
@jakebailey , I added to the typeshed while it was deleted from pylance extension , moved the folder back into the extension, then restarted vscode and things seem to be working a little better with those additions. 
-- Anomaly: I'm not sure why the same behaviour is present in other files I had opened but did not have any tracked changes to. E.g., file 'x' was opened in the editor with no changes, file 'y' was opened and actively being worked on. Now file 'y' can chain anything. File 'x' can not chain the same methods correctly as file 'y' can. 
     I restarted the language to server but that did not seem to change anything.
     
Here is what I added to the files... Hoping you have a sec to glance at this and be able to tell if I'm way off or this is the right direction please:
-- ActionChains.pyi
![image](https://user-images.githubusercontent.com/23281810/130277487-6c3ebef1-132c-4efa-8d5e-cc6e2e2f130f.png)
-- action_builder.pyi
![image](https://user-images.githubusercontent.com/23281810/130277583-0da5dde8-0e4d-4b00-8283-58a840ea8242.png)

I've also reached out to one of the head maintainers at Selenium to try and collaborate. However, no response yet...

**Comment by erictraut** [comment]
Great! Looks like a good start. A couple of pointers...
1. It looks like you're including instance variables in some of the type annotations. For example, `ActionBuilder.pointer_action` refers to an instance variable, not a type. Types are generally the names of classes.
2. Within a ".pyi" file, you can use the new, easier-to-read Python 3.10 syntax for union types. The new syntax makes use of the "|" operator. For example, `int | str | None` is equivalent to `Optional[Union[int, str]]`.
3. Many of the methods in `ActionChains` appear to accept parameters with default values. This is indicated by following the parameter type by `= ...`. For example, `def click(self, on_element: WebElement | None = ...)`.
4. (Minor) By convention, it's typical for a space to be placed after the colon in a type annotation. If you install an auto-formatter like "black", it will handle these formatting details for you.

**Comment by jtheyer** [comment]
@erictraut , the pointers are highly appreciated. I'll make the changes and continue adding now that I have more confidence that this is going in the right direction. Thank you!
