### ISSUE TITLE
False positive when using an overload that restricts the returned type to NoReturn 

### ISSUE THREAD

**Issue by Questionsdenombres** [microsoft/pylance-release#1702]
## Environment data

python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Windows-10-10.0.19043-SP0
Visual Code Studio: 1.59.1
extension python: v2021.8.1147840270 
extension pylance: v2021.8.2
type checking mode: strict

## Actual and expected behaviour
See code example below.
Pylance reports an error, which I think is a False positive.

## Code Snippet
```python
import enum
from typing import overload, Union, NoReturn, Literal

@enum.unique
class Options(enum.Enum):
    A = enum.auto()
    B = enum.auto()

@overload
def test(options: Literal[Options.A]) -> NoReturn: ...
@overload
def test(options: Literal[Options.A, Options.B]) -> Union[None, NoReturn]: ...
def test(options: Literal[Options.A, Options.B]) -> Union[None, NoReturn]:
    if options == Options.A:
        raise NotImplementedError
    return

def my_func() -> NoReturn:
    test(Options.A) 
    # pylance reports: Function with declared type of "NoReturn" cannot return "None"
```

**Comment by erictraut** [comment]
This is related to https://github.com/microsoft/pyright/issues/2206

**Comment by heejaechang** [comment]
closing as dup
