### ISSUE TITLE
'Argument to class must be a base class' if using a specific version check while importing `Protocol` from either `typing` or `typing_extensions`

### ISSUE THREAD

**Issue by hojo0590** [microsoft/pylance-release#1703]
**Describe the bug**
If importing python modules using a version check (I'll be using python 3.8.11 throughout these examples) there is at least one case in which I don't know why pylance does not behave/resolve that conditional import as expected.  
Let's say we want our import to behave differently depending on the python version we are using, I'd use something like this:
```python
import sys
if sys.version_info > (3, 7):
    from typing import List
```
To be precise I came from [this pyright issue](https://github.com/microsoft/pyright/issues/2066) which is most likely unrelated, but somehow the source (cite-worthy) on which I based my minimal examples.  
The next code leads to `Argument to class must be a base class` on `Protocol` and `Type variable "T" has no meaning in this context` on `T` pylance errors.
```python
import sys
from typing import TypeVar

if sys.version_info[0:2] > (3, 7):
    from typing import Protocol
else:
    from typing_extensions import Protocol

T = TypeVar("T")


class P(Protocol[T]):
    v: T
```
![grafik](https://user-images.githubusercontent.com/39441485/130248101-c2e461ef-c73f-44ad-b326-6245dbb2eeed.png)

These errors can easily be fixed when using `if sys.version_info > (3, 7):` instead of `if sys.version_info[0:2] > (3, 7):`
```python
import sys
from typing import TypeVar

if sys.version_info > (3, 7):
    from typing import Protocol
else:
    from typing_extensions import Protocol

T = TypeVar("T")


class P(Protocol[T]):
    v: T
```
![grafik](https://user-images.githubusercontent.com/39441485/130248034-51ccd96d-2996-4aca-a6ff-34f49b2a466d.png)

**To Reproduce**
See above.

**Expected behavior**
I'd expect the import conditions `if sys.version_info > (3, 7):` and `if sys.version_info[0:2] > (3, 7):` to lead to equivalent behaviour.

**VS Code extension or command-line**
Pylance VS Code Extension v2021.8.2 on VS Code 1.59.1

**Comment by hojo0590** [comment]
I hope I have not overseen anything - if you need any additional information please let me know!

**Comment by erictraut** [comment]
Type checkers like pyright allow certain expression forms for system version checks as defined in [PEP 484](https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking). The form `if sys.version_info[0:2] > (3, 7)` is too complex and outside the bounds of what type checkers will understand. The form `sys.version_info > (3, 7)` is part of the agreed-upon set of expression forms that is supported. If you stick to that, this will work fine.

If there's some reason why that form doesn't work for you, you can include `TYPE_CHECKING` in the check, like this:
```python
if sys.version_info[0:2] > (3, 7) or TYPE_CHECKING:
    from typing import Protocol
else:
    from typing_extensions import Protocol
```

**Comment by hojo0590** [comment]
Thank you for taking the time and answering that extensively @erictraut. I guess this can be closed then.
