### ISSUE TITLE
How to make pylance not show autocomplete for objects not defined in the imported file?

### ISSUE THREAD

**Issue by tombohub** [microsoft/pylance-release#1706]
If we have a entitities.py file with code: 

![2021-08-21 09_06_09-entities py - stock-analytics - Visual Studio Code](https://user-images.githubusercontent.com/3029412/130322784-39eb3051-af86-493a-a231-47e75ba101a0.png)

```python
from dataclasses import dataclass
import datetime as dt

from core.enums import PriceInterval

@ dataclass
class Price:
    """
    OHLC price data for single time interval
    """

    symbol: str 
    """
    security symbol on market, ex.: SPY
    """
```

now when we try to import `Price` we get suggestions for everything that's in `entities.py`:
 
![2021-08-21 09_07_58-● m py - stock-analytics - Visual Studio Code](https://user-images.githubusercontent.com/3029412/130322818-b400991e-b3e5-43dc-880a-8f1f2996963b.png)

How can we make pylance to show only `Price` since that's the only object defined in `entities.py` ?

**Comment by jakebailey** [comment]
If you repeat this and write `import core.entities`, then do `core.entities.` on another line (completing after `entities` but not in an import statement), do you see those same unwanted items listed?

My impression was that we were hiding some of these "implicitly exported" module attributes, but perhaps not in some condition. If the behavior matches outside of the `import` line, then I was mistaken.

**Comment by tombohub** [comment]
@jakebailey hello, yes I see the same all items:

![2021-08-23 17_36_26-● m py - stock-analytics - Visual Studio Code](https://user-images.githubusercontent.com/3029412/130522786-8088bc9f-76f7-4004-9ad4-038a4d89c677.png)

**Comment by jakebailey** [comment]
Alright, I was mistaken, and the two do behave identically.

Technically, all of those attributes are accessible, so we show them. It's hard to know in a typical Python codebase whether or not a specific imported value is intended to be usable in other modules, as most Python codebases do not follow the stricter rules outlined here: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md

I'm not sure that it's a good idea to change this (i.e. remove them entirely), but it would be worth seeing if (for modules not in a `py.typed` library) we can deprioritize members that are exported. But, given the wide range of non-`py.typed` libraries out in the wild, it may cause more regression than benefit.

**Comment by tombohub** [comment]
@jakebailey ok, thanks for the explanation
