### ISSUE TITLE
Support inserting argument placeholders when completing function name

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#171]
When completing a function, it would be nice to add argument placeholders. This is already supported by several language servers, like TypeScript, Dart, and Go, using a preference. See https://github.com/Microsoft/vscode/issues/34641.

**Comment by jakebailey** [comment]
I'm going to close this in favor of two issues targeting the specific parts of this, #37, which covers adding `()` to callables, and #221, which covers placeholder arguments specifically. The latter will take some specifying and consideration as to it being the default.
