### ISSUE TITLE
Could it possible to get Intesllisense from the pyd file.

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#1711]
![AHszI](https://user-images.githubusercontent.com/21306413/130408439-b7fd4890-1de7-4b9b-b2f5-38b68afd3f3e.gif)

![Capture](https://user-images.githubusercontent.com/21306413/130408685-b089c004-d247-4a6a-99e5-af883a003671.PNG)

Could it be possible like the PyCharm does?

**Comment by jakebailey** [comment]
See #166.

It's unlikely we'll do this, as you need to execute the library to get info from it, which is generally unsafe.

**Comment by gonghenghai** [comment]
thanks.

**Comment by ImadYIdrissi** [comment]
Hello,

Could you provide further explanation why the `C` binaries (of the library) need to be executed for the IDE to be able parse the source code?
