### ISSUE TITLE
Issue Resolving Stig_parser

### ISSUE THREAD

**Issue by SMoseley44** [microsoft/pylance-release#1713]
Hello, I am currently experiencing an issue resolving a pip-installed module for stig_parser. See the message below:

" Import "stig_parser" could not be resolved"

**Comment by CodeCrazy-ywt** [comment]
Screenshot, please

**Comment by jakebailey** [comment]
You haven't filled out our bug template, so you haven't provided enough information for us to help you.

You should first try to ensure that you have selected the interpreter where `stig_parser` is installed at the bottom left in the interpreter selector; Pylance uses the interpreter selected by the Python extension.

If you have it selected, please provide the logs as instructed in a copy of our bug template here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
It's been about a month since we asked for more info; I'm going to close this. If you can check the above or provide more info, we can reopen this.
