### ISSUE TITLE
About the IntelliSence on the methods of a `numpy.ndarray` object

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/pylance-release#1714]
## Environment data

-   Language Server version: 2021.8.2
-   OS and version: Windows 10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6

## Expected behaviour

Take `reshape` as an example, Intellisence should be applied in this piece of code:
```python
import numpy as np
a1: np.ndarray = np.arange(10).reshape(2, 5)
```

## Actual behaviour

Intellisence doesn't work on `reshape`. For the specific situation, see the screenshot below.

## Logs

```
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\Admin\ywt\2.py ...
[BG(1)]   parsing: c:\Users\Admin\ywt\2.py (1ms)
[BG(1)]   binding: c:\Users\Admin\ywt\2.py (0ms)
[BG(1)]   checking: c:\Users\Admin\ywt\2.py ...
[BG(1)]     parsing: c:\Users\Admin\ywt\sorting\Lib\site-packages\numpy\__init__.pyi [fs read 0ms] (27ms)
[BG(1)]     binding: c:\Users\Admin\ywt\sorting\Lib\site-packages\numpy\__init__.pyi (18ms)
[BG(1)]     parsing: c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.2\dist\typeshed-fallback\stdlib\abc.pyi [fs read 0ms] (2ms)
[BG(1)]     binding: c:\Users\Admin\.vscode\extensions\ms-python.vscode-pylance-2021.8.2\dist\typeshed-fallback\stdlib\abc.pyi (0ms)
[BG(1)]     parsing: c:\Users\Admin\ywt\sorting\Lib\site-packages\numpy\typing\__init__.py [fs read 1ms] (12ms)
[BG(1)]     binding: c:\Users\Admin\ywt\sorting\Lib\site-packages\numpy\typing\__init__.py (1ms)
[BG(1)]     parsing: c:\Users\Admin\ywt\sorting\Lib\site-packages\numpy\typing\_shape.py [fs read 0ms] (0ms)
[BG(1)]     binding: c:\Users\Admin\ywt\sorting\Lib\site-packages\numpy\typing\_shape.py (0ms)
[BG(1)]   checking: c:\Users\Admin\ywt\2.py (67ms)
[BG(1)] analyzing: c:\Users\Admin\ywt\2.py (68ms)
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1629729755384 at c:\Users\Admin\ywt\2.py (1ms)
Background analysis message: resumeAnalysis
[FG] parsing: c:\Users\Admin\ywt\2.py (1ms)
[FG] binding: c:\Users\Admin\ywt\2.py (0ms)
Background analysis message: markFilesDirty
Background analysis message: analyze

```

## Code Snippet / Additional information

```python
import numpy as np

a1: np.ndarray = np.arange(10).reshape(2, 5)
# No IntelliSence is applied at all.
# No suggestions. No semantic highlighting. No tooltips.
# When I hover on `reshape`, a tooltip shows that says "reshape: Unknown"

a2: np.ndarray = np.arange(10)
b = a2.reshape(2, 5)
# IntelliSence works here.
```
![屏幕截图 2021-08-23 224545](https://user-images.githubusercontent.com/62426149/130468052-f2a8c4fa-fba3-4ad8-acda-c80002067407.png)

**Comment by jakebailey** [comment]
If you write `reveal_type(np.arange(10))`, what do you see? The only difference in this example is when the `np.ndarray` type assignment is happening; in the first case, it's after `reshape`, but in the second, it's before.

I think `ndarray` is generic, so may be causing some oddities here, but not in the way I expected.

**Comment by bschnurr** [comment]
the return type for `np.arange` is `Any` when you got to declaration (the type stub)

**Comment by jakebailey** [comment]
Yeah, older versions of numpy had these functions return `Any`. I think that newer ones will have better types: https://github.com/numpy/numpy/blob/c0d8696e7dd14ef209d5deb4c2b952c51a62a132/numpy/core/multiarray.pyi#L709

The second one works because you're explicitly changing the `Any` to `np.ndarray`.

**Comment by bschnurr** [comment]
Looks fixed in new numpy pre-release https://github.com/numpy/numpy/releases/tag/v1.22.0rc1

![image](https://user-images.githubusercontent.com/1946977/143134270-55120131-9ad9-4bbb-8f80-eb77d9b65af5.png)
