### ISSUE TITLE
Non-imported modules not indexed even with "indexing" enabled, when no workspace folder is opened

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#1715]
## Environment data

-   Language Server version: 2021.8.2 (pyright f462f5bb)
-   OS and version: macOS 10.15.7
-   Python version: 3.9

## Expected behaviour

When indexing is enabled (`"python.analysis.indexing": true`), auto-import should suggest to import a module even if it had not previously been manually imported in the project. This works correctly when a workspace folder is opened - but doesn't work when a single file is opened (without any workspace folder).

## Actual behaviour

To reproduce:
* Create new empty VS Code window
* Change the empty file's language mode to Python
* Type `sys`
* Expect to have an auto-import suggestion to "Add import sys", but actually get no suggestion
* Only after you manually add (and then remove) "import sys", the suggestion to "Add import sys" will correctly show up.
* This happens whether or not `"python.analysis.indexing": true` is in your settings

**Comment by jakebailey** [comment]
At the moment, we don't do this for the "default" workspace, which is what encompasses any file that isn't a part of an open folder.

We could consider changing this behavior to do indexing for these files (maybe just the standard library?).

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
