### ISSUE TITLE
Iterable item with non-digit index can't remember implicit typing info within condition block

### ISSUE THREAD

**Issue by abelcheung** [microsoft/pylance-release#1718]
## Environment data

- Pylance version: v2021.8.3pre1
- VSCode version: 1.60.0-insider
- Python version (& distribution if applicable, e.g. Anaconda): 3.8.8

## Problem Description

(See further down below for code sample and screenshot)

In code sample, a few list items are placed within `if` blocks and `while` blocks to further limit their possible typing. However it seems that it works only for items with digit-only list index, like `data[0]` or `data[1]`. No luck for negative numbers, arithmetics or variables. So far only `if` and `while` blocks are tested, I'm not quite sure how wide the scope of problem is.

Besides, iterables with fixed size behave a bit differently. For example, if the annotation of `data` variable is changed to `Tuple[Optional[str], ...]`, then most warnings disappear. `data[0+0]` still yields the same warning though.

## Code Sample

Problem is illustrated with following code sample:

```python
from typing import List, Optional

def func(arg: str):
    pass

data: List[Optional[str]] = ['', '', None, 'foo', 'bar']

if data[0]:
    func(data[0])    # OK
    func(data[0+0])  # Bad

if data[-1]:
    func(data[-1])  # Bad

x = data[-1]
if x:
    func(x)  # OK

a = 0
if data[a]:
    func(data[a])  # Bad

while data[0]:
    func(data[0])  # OK

while data[a]:
    func(data[a])  # Bad
```

## Screenshot

![圖片](https://user-images.githubusercontent.com/83110/130557899-1509164b-2203-4fe9-b6c9-66a41c0e2b6c.png)

**Comment by erictraut** [comment]
This is intended behavior. Type narrowing applies only to specific expressions that are static and provably do not change from one access to another. Subscript expressions that use non-negative integer literals as an index are supported, but other forms of subscripts are not. This same limitation exists in other type checkers like mypy.

If you want type narrowing to apply in situations like this, one option is to use a walrus operator to assign the value to a variable. This also results in slightly faster code.

```python
if (x := data[a]):
    func(x)
```

**Comment by erictraut** [comment]
Refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-narrowing) for full details about type narrowing within pyright, the static type checker that underlies pylance.

**Comment by abelcheung** [comment]
Ah yes, I was losing my head completely about evaluation of list index as static expression, not as python code. Closing the issue now ^_^
