### ISSUE TITLE
Try Except block creates a new scope

### ISSUE THREAD

**Issue by Niflhem** [microsoft/pylance-release#1719]
<h3> Environment data </h3>

-   Language Server version: 2021.8.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.5 64 bit from MS Store
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Try except doesn't create a new scope. The `foo` variable is accessible.

<h3> Actual behaviour </h3>

`"foo" is not defined` and the code works.

<h3> Logs </h3>

Python Language Server Log
Username redacted
```
[FG]   parsing: c:\Users\{user}\Desktop\Untitled.py (3ms)
[FG]   binding: c:\Users\{user}\Desktop\Untitled.py (1ms)
[FG] completion at c:\Users\{user}\Desktop\Untitled.py:4:13 [found 5 items] (14ms)
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: c:\Users\{user}\Desktop\Untitled.py ...
[BG(1)]   parsing: c:\Users\{user}\Desktop\Untitled.py (0ms)
[BG(1)]   binding: c:\Users\{user}\Desktop\Untitled.py (0ms)
[BG(1)]   checking: c:\Users\{user}\Desktop\Untitled.py (2ms)
[BG(1)] analyzing: c:\Users\{user}\Desktop\Untitled.py (2ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1629797561006 at c:\Users\{user}\Desktop\Untitled.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

<h3> Code Snippet / Additional information </h3>

```python
try:
    foo = 0
    raise
except:
    print(foo)
```
`"foo" is not defined` and 0 is printed.

**Comment by CodeCrazy-ywt** [comment]
Emm...that's a bit unsafe. What if an error occurs **before** the variable assignment? e.g. if you run this piece of code:
```python
try:
    foo = 1 / 0
    raise
except:
    print(foo)
```
you will see this output:
```
Traceback (most recent call last):
  File "some\path\to\the\python\file.py", line 3, in <module>
    foo = 1 / 0
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "some\path\to\the\python\file.py", line 6, in <module>
    print(foo)
NameError: name 'foo' is not defined
```

**Comment by erictraut** [comment]
This behavior is intended and expected.

The type checker needs to assume that any statement — or even any subexpression — within a try block might generate an exception. If you rely on the value of a symbol within the except clause, you should always initialize it prior to the try block to be safe.
