### ISSUE TITLE
Type Issue: No overloads for "read_excel" with BytesIO

### ISSUE THREAD

**Issue by kigawas** [microsoft/pylance-release#1721]
-   Language Server version: 2021.8.2
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.9.5, Homebrew
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

No error

<h3> Actual behaviour </h3>

 ```
No overloads for "read_excel" match the provided arguments
  Argument types: (BytesIO)
``` 
![image](https://user-images.githubusercontent.com/4182346/130735982-18fcebff-f611-4e5d-81ee-41293a4d274c.png)

<h3> Logs </h3>

Not Applied

<h3> Code Snippet / Additional information </h3>

 
```python
import pandas as pd

with open("sample.xlsx", "rb") as f:
    data = f.read()

pd.read_excel(io.BytesIO(data))
```

The argument "filepath: str" is not accurate, which should be `io: str, file-like, ...`, details are in the documentation.

Pandas read_excel documentation: https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html

**Comment by rchiodo** [comment]
This seems to have been addressed.
