### ISSUE TITLE
Type annotation not supported for PEP-526

### ISSUE THREAD

**Issue by WuZhuoran** [microsoft/pylance-release#173]
## Environment data

-   Language Server version: v2020.7.3
-   OS and version: Ubuntu 16.04.5 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.10

## Expected behaviour

No error message. According to PEP 526 https://www.python.org/dev/peps/pep-0526/#global-and-local-variable-annotations
It should be OK to initialize a List with a type and initial value.

## Actual behaviour

Error message with: `Type annotation not supported for this type of expression`

## Logs

```
Type annotation not supported for this type of expression
```

## Code Snippet / Additional information

```python
my_varibale: List[MyClass] = []
```

**Comment by erictraut** [comment]
This should work fine. Are you sure you're importing `List` from `typing`? Is it perhaps redeclared or reassigned within your source file?

**Comment by WuZhuoran** [comment]
Problem solved.
I used this annotation with a value in a dict, something like:

```
myDict[mykey]: List[myclass] = []
```

that is not working. thank you for you help.

**Comment by erictraut** [comment]
Ah yes, you cannot use an annotation on an expression like `myDict[mykey]`. That expression already has a type that is defined by the `myDict` symbol.

For example, you could do the following:
```
myDict: Dict[str, List[MyClass]] = {}
myDict[mykey] = []
```
