### ISSUE TITLE
Generic object attribute with contraints wrongly seen as `TypeVar` or `Generic` type in `isinstance`

### ISSUE THREAD

**Issue by hojo0590** [microsoft/pylance-release#1730]
## Environment data

-   Language Server version: 2021.8.3 (pyright fa4194fd)
-   OS and version: Win10 19043.1165
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.11 (Anaconda)

## Code Snippet

```python
from typing import Any, Generic, TypeVar

T = TypeVar("T", int, str)


class B(Generic[T]):
    att: T

    def check_type(self, var: Any) -> bool:
        return isinstance(var, type(self.att))
```

## Expected behaviour

I'd expect pylance to not throw an `Second argument to "isinstance" must be a class or tuple of classes` `TypeVar or generic type with type arguments not allowed` error on the second argument passed to `isisntance()`.

## Actual behaviour

Error is thrown.

## Additional information

Possibly related/in addition to #1294 and  
using a `TypeVar` without constraints works well.

```python
from typing import Any, Generic, TypeVar

T = TypeVar("T")


class B(Generic[T]):
    att: T

    def check_type(self, var: Any) -> bool:
        return isinstance(var, type(self.att))
```
(removing the constraints `TypeVar("T", int, str)` -> `TypeVar("T")` does not lead to an error)

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202190-1-september-2021
