### ISSUE TITLE
Unexpected warnings on final class derived from ABC

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1732]
## Environment data

-   Language Server version: 2021.8.4-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.11 (Anaconda)

## Sample code

```python
from abc import ABC
from typing import final

class Base(ABC):
    pass

@final
class Derived(Base):
    pass

_ = Derived()
```

## Expected behavior

No error.

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/131067339-1df77f9b-9150-403b-8350-cb7869cc5ab4.png)

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202190-1-september-2021
