### ISSUE TITLE
Jax numpy autocomplete not working

### ISSUE THREAD

**Issue by machineko** [microsoft/pylance-release#1737]
## Environment data

-   Language Server version: v2021.8.4-pre.1
-   OS and version: windows 11 pro
-   Python version (& distribution if applicable, e.g. Anaconda): conda python 3.9.6

## Expected behaviour
when importing jax i would expect it to allow me to autocomplete just like in version using Jedi as language server.
![jediauto](https://user-images.githubusercontent.com/42299606/131223667-6fdd36ac-e516-47da-9582-9018f88c1489.png)

## Actual behaviour
![jaxautocompl](https://user-images.githubusercontent.com/42299606/131223662-3ce951c3-9b59-41d9-b617-6f3a010bedfe.png)

Jax.numpy autocomplete is not working

**Comment by jakebailey** [comment]
The way this library exports things really defeats static analysis: https://github.com/google/jax/blob/bbfd8f7cfc540d7a93b9c8e7b4460fef4af9f560/jax/numpy/__init__.py#L82

Jedi must be doing some trickery to figure this out, but overall, a stub would really be better.

**Comment by machineko** [comment]
How can we fix this? (I'll make PR for Jax repo if u point me in some meaningful direction so i can fix it 📦 )

**Comment by erictraut** [comment]
Jax is a "py.typed" library, so it is treated according to the rules spelled out in [this document](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md). In particular, imported symbols are not assumed to be re-exported unless they appear in `__all__` or use a redundant form of `import`. Jedi's logic predates the py.typed rules, which explains why it's showing symbols in this case.

The correct fix is for jax to be updated to conform to these rules and guidelines. Let us know if you have any questions after reading the above document.

**Comment by jakebailey** [comment]
Ah, I didn't even notice that it was `py.typed`; that explains everything.

**Comment by machineko** [comment]
Thank u guys, its already working by just adding __all__ to init.py and folks from google are working on it so I close this issue for now 😸
