### ISSUE TITLE
Report redundant parentheses

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [microsoft/pylance-release#174]
Similar to pycharm, I'd like to be warned where there are parentheses that don't do anything to change the order of operations.

**Comment by savannahostrowski** [comment]
Hey @A-UNDERSCORE-D 

Thanks for the enhancement request. We're looking into this suggestion and have added it to our backlog. In the meantime, we'll leave this issue open so that others can upvote!

**Comment by erictraut** [comment]
This is a matter of code style or coding convention, not a code correctness or type issue. That means it's properly the domain of a linter (like pylint) or a reformatter (like black). It's not something a type checker or language server would normally handle.

**Comment by savannahostrowski** [comment]
Thanks for the feature request. After some consideration, we've decided to not tackle stylistic linting at this time.
