### ISSUE TITLE
Missing docstring for np.sqrt

### ISSUE THREAD

**Issue by EternalLines** [microsoft/pylance-release#1740]
Hi,

This is the docstring given when Pylance is chosen as the language server:
![Pylance_docstrings](https://user-images.githubusercontent.com/69616195/131333141-6872731a-5581-4747-8ae9-07fae7d782c1.png)

This is the docstring given when JediLSP is chosen as the language server:
![Jedi_docstrings](https://user-images.githubusercontent.com/69616195/131333180-4ac22ec4-df50-4160-9cc1-ab4db082aca9.png)

They are different and the docstring given by Pylance is not useful (and it is perhaps retrieving docstring of some base class?). Is there a way to resolve this?

Thanks!

**Comment by CodeCrazy-ywt** [comment]
I also met the same problem

**Comment by jakebailey** [comment]
Jedi executes compiled code to get its docstrings, Pylance does not, instead shipping a pre-scraped version for docs. It looks like our current handling could be improved here; the intent is that this works.

**Comment by judej** [comment]
What version of NumPy are you using?

**Comment by EternalLines** [comment]
I am using version 1.21.2.

**Comment by jakebailey** [comment]
This was actually fixed in 2021.9.1; it was the same as #1047.
