### ISSUE TITLE
circular dependency between 'ms-python.vscode-pylance' and 'ms-python.python'

### ISSUE THREAD

**Issue by pgit** [microsoft/pylance-release#1742]
## Description

For developing Python in VSCode, the extension pack "ms-python.python" is suggested. It includes "ms-python.vscode-pylance" and "ms-toolsai.jupyter". Installing them in an online Installation of Visual Studio Code works.

When doing the same in an offline installation using the "code --install-extension" command line, it doesn't. There is a dependency from *pylance* back to the extension pack, which seems to be resolved by the online installer. When installing offline like this, I can't install neither pylance nor the extension pack, see below. Fixing the pylance VSIX to NOT depend on ms-vscode.python resolves this.

So please remove the dependency on the extension pack from vscode-pylance. 

## Environment data

* Visual Studio Code V1.59.1
* ms-python.python-2021.8.1159798656.vsix
* ms-python.vscode-pylance-2021.8.3.vsix
* ms-toolsai.jupyter-2021.8.1195043623.vsix

## Expected behaviour

```
# code --install-extension ms-toolsai.jupyter-2021.8.1195043623.vsix
Extension 'ms-toolsai.jupyter-2021.8.1195043623.vsix' was successfully installed.
# code --install-extension ms-python.vscode-pylance-2021.8.3.vsix
Extension 'ms-python.vscode-pylance-2021.8.3.vsix' was successfully installed.
# code --install-extension ms-python.python-2021.8.1159798656.vsix
Extension 'ms-toolsai.jupyter-2021.8.1195043623.vsix'' was successfully installed.
````
## Actual behaviour

```
# code --install-extension ms-toolsai.jupyter-2021.8.1195043623.vsix
Extension 'ms-toolsai.jupyter-2021.8.1195043623.vsix' was successfully installed.
# code --install-extension ms-python.vscode-pylance-2021.8.3.vsix
getaddrinfo ENOTFOUND marketplace.visualstudio.com
Failed Installating Extensions: file://.../ms-python.vscode-pylance-2021.8.3.vsix
...
# code --install-extension ms-python.python-2021.8.1159798656.vsix
getaddrinfo ENOTFOUND marketplace.visualstudio.com
Failed Installating Extensions: file://.../ms-python.python-2021.8.1159798656.vsix
...
````

**Comment by pgit** [comment]
Actually, it says in the [pylance extension](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) that pylance is an _optional_ dependency. So it might be the other way around. Anyway, the circle needs breaking :)

**Comment by jakebailey** [comment]
The dependency exists because the Pylance extension itself doesn't actually start anything; the Python extension is required for anything to work. If we remove the hard dep, anyone installing Pylance will not see anything work, which would appear to be a bug to most everybody.

I believe if you install the python extension first, you shouldn't hit this. Is that not the case? VS Code should be smart enough to skip pack dependencies that are unavailable.

**Comment by pgit** [comment]
Hi, I can confirm this works with insiders. Extensions can be installed from the command line while being offline, ignoring their dependencies. I was able to install python/pylance without installing jupyter first.
