### ISSUE TITLE
Wrong `typings.Literal` type detection

### ISSUE THREAD

**Issue by Masynchin** [microsoft/pylance-release#1749]
Issue Type: <b>Bug</b>

Actual code:
```python
from typing import List, Literal, Union


X = 1
O = 2

Row = List[Union[Literal[0], Literal[X], Literal[O]]]
```

Warning: `Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value`

Extension version: 2021.8.3
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:07.791Z)
OS version: Windows_NT ia32 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Turion(tm) II Dual-Core Mobile M520 (2 x 2294)|
|GPU Status|2d_canvas: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.12GB (0.26GB free)|
|Process Argv|--crash-reporter-id 6f544008-845b-4f8c-81f4-28fa832f4a01|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
vsdyn321cf:30356811
vscus224:30358039

```

</details>

**Comment by erictraut** [comment]
You cannot use variables within `Literal` type statements. Please refer to [PEP 586](https://www.python.org/dev/peps/pep-0586/) for details.

You would need to use the following. (Note that `Union` isn't required since you can provide multiple literal type arguments in a single `Literal` annotation.)
```python
Row = List[Literal[0, 1, 2]]
```

You can also use type aliases:
```python
X = Literal[1]
O = Literal[2]
Row = List[Union[Literal[0], X, O]]
```

**Comment by jakebailey** [comment]
Closing, as this is disallowed by PEP 586 and I don't think we're going to change this behavior.

**Comment by Masynchin** [comment]
> You cannot use variables within `Literal` type expressions. Please refer to [PEP 586](https://www.python.org/dev/peps/pep-0586/) for details.
> 
> You would need to use the following. (Note that `Union` isn't required since you can provide multiple literal type arguments in a single `Literal` annotation.)
> 
> ```python
> Row = List[Literal[0, 1, 2]]
> ```
> 
> You can also use type aliases:
> 
> ```python
> X = Literal[1]
> O = Literal[2]
> Row = List[Union[Literal[0], X, O]]
> ```

Thanks for detailed answer (and very thanks for `Literal[0, 1, 2]`)!
