### ISSUE TITLE
Wrong docstring shown for nn.LayerNorm.__init__

### ISSUE THREAD

**Issue by jingw222** [microsoft/pylance-release#1753]
What we have:
<img width="1207" alt="Screen Shot 2021-09-02 at 12 36 05 AM" src="https://user-images.githubusercontent.com/5494367/131863317-0f286073-fe1b-4387-9017-871cd07618b4.png">
which only shows a very terse signature. How do we get the **full** docstrings:
<img width="857" alt="Screen Shot 2021-09-02 at 12 40 38 AM" src="https://user-images.githubusercontent.com/5494367/131863446-22f5847e-9eca-4518-be36-a67ee9921fb3.png">
as in Jupyter:

https://user-images.githubusercontent.com/5494367/131863498-9290fb35-e156-4fda-a621-b6b6cce8fffd.mov

**Comment by jakebailey** [comment]
What project is this, pytorch?

That doc is likely `Module`'s docs; we have a bug at the moment where we return the parent class' `__init__` doc before we offer up the class's docs itself. You can confirm this by hovering over `LayerNorm` without calling it, or hovering over the class name at its declaration.

**Comment by jakebailey** [comment]
I'm going to close this in favor of #1047, which is the same issue (and I've retitled it to better represent the problem).

**Comment by jingw222** [comment]
This issue has been announced as fixed in the Pylance v2021.9.1 release as you said in the linked issue. But The hover box still shows me what it was before. What gives?

**Comment by jakebailey** [comment]
Later in that issue, we decided that this particular behavior wasn't a necessarily a bug; it's unclear whether or not the parent class's init doc is the more useful one if the class doc also exists. Other editors appear to behave similarly to us, except that we show the init doc when invoking a class (which calls init).

The other issue was in fact actually fixed (as it involved a doc from object), but this particular issue is entirely between non-builtin classes.
