### ISSUE TITLE
"await" outside of async function in jupyter notebook indicates problem

### ISSUE THREAD

**Issue by CalebEverett** [microsoft/pylance-release#1754]
<h3> Environment data </h3>

-   Language Server version: 2021.9.1-pre.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Should not indicate a problem if await called directly in jupyter notebook.

<h3> Actual behaviour </h3>

Indicates problem if await called directly in a jupyter notebook but code runs fine.

**Comment by jakebailey** [comment]
Top-level await is disallowed in regular Python files, but it looks like the IPython kernel allows this: https://ipython.readthedocs.io/en/stable/interactive/autoawait.html

Notebooks are closer to a REPL than a script, so that makes some sense, but that doesn't mesh well with our current way of handling notebooks, which is to concatenate the cells and then treat that as a single file.

**Comment by CalebEverett** [comment]
Got it  - is there a way to disable the warning for that file or workspace? I didn't see anything with await or async on this list here
https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md

**Comment by jakebailey** [comment]
This is something that we would typically be treating as a parser error (though, technically is checked later, as the `await` rules are a little trickier than the parser can understand), so there's no rule for it.

The only way you can affect this would be to disable all diagnostics for the file (put `# type: ignore` at the top), or to put `# type: ignore` at the end of each line containing an await.

We would like to fix this, though.

**Comment by heejaechang** [comment]
we should discuss this as part of discussion linked above.

**Comment by heejaechang** [comment]
support for this is added in https://github.com/microsoft/pyrx/pull/2149

**Comment by rchiodo** [comment]
If you add support for this, we need to remove the special parsing for this from the concat layer.

**Comment by heejaechang** [comment]
this is handled with https://github.com/microsoft/pyrx/pull/2269 but only if user is using pylance as notebook handler.

**Comment by Apollo3zehn** [comment]
What do we need to do to use pylance as notebook handler?

I still have problems with `async with` and `xxx = await` statements:

![image](https://user-images.githubusercontent.com/20972129/162918495-6d032f92-7014-49d0-9a27-3d53eb3373a3.png)

**Comment by varunsurapaneni** [comment]
> What do we need to do to use pylance as notebook handler?
> 
> I still have problems with `async with` and `xxx = await` statements:

Here is the setting in the Settings Editor (just search for `jupyter.pylanceHandlesNotebooks`)
![vs_code_jupyter_pylance_setting](https://user-images.githubusercontent.com/67070327/166621171-ce43b2f2-1290-4e3b-87bf-ec978e519393.png)

Or just add the following to your `settings.json` file:
> "jupyter.pylanceHandlesNotebooks": true

**Comment by Apollo3zehn** [comment]
Thank you, the situation has improved a little bit now:

![image](https://user-images.githubusercontent.com/20972129/166648508-22c94ecc-9374-4efa-968c-b2cc4ea58d12.png)

**Comment by pinkfrog9** [comment]
Using interactive cell (note ipynb file) still has the issue:
<img width="348" alt="image" src="https://github.com/microsoft/pylance-release/assets/107285219/551e1464-77ef-4813-bdc3-e6f0feba9ae7">
<img width="523" alt="image" src="https://github.com/microsoft/pylance-release/assets/107285219/f147cf49-78f9-41ec-b1ab-cbd95f13172f">

@heejaechang

**Comment by superlevure** [comment]
This is still an issue as of today, is there a way to disable this error message beside disabling Pylance?

**Comment by superlevure** [comment]
@debonte actually I realized I'm in @pinkfrog9's situation and using `# %%` to declare cell blocks within a `.py` file so that explains it. Thank you for the quick answer

**Comment by debonte** [comment]
@superlevure, @pinkfrog9, there is now a discussion tracking this enhancement request. Please consider up-voting it. https://github.com/microsoft/pylance-release/discussions/5322
