### ISSUE TITLE
Function return type arrow token screws up editor formatting

### ISSUE THREAD

**Issue by JordanLongstaff** [microsoft/pylance-release#1757]
## Environment data

-   VS Code version: 1.60.0
-   Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS and version: MacOS Big Sur 11.5.2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: mypy 0.790
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Default

## Expected behaviour

VS Code editor's formatting of Python code (particularly font colours) is always consistent.

## Actual behaviour

Nearly all code following a function return type annotation using the arrow token (`->`) is formatted (coloured) incorrectly, as evidenced in this screen recording.

https://user-images.githubusercontent.com/7563922/131924515-1845ca4f-25a0-4bb2-8969-07d54071b7ff.mov

## Steps to reproduce:

1. Create a new Python code file.
2. Define a function in the file, using any name and body.
3. Now give the function a return type annotation using the arrow token. Watch as nearly all of the contents after the arrow suddenly change colours.

**Comment by heejaechang** [comment]
Hi @JordanLongstaff 

I tried it with the latest pylance, but can't repro. if it still repro, can you re-open the issue with a file that we can use to repro?
