### ISSUE TITLE
Do not check `self` compatibility when pattern `Class.method` is used

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1758]
## Environment data

-   Language Server version: 2021.9.1-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.11 Anaconda

## Sample code

```python
from __future__ import annotations

from abc import ABC
from typing import Any, overload

class Base(ABC):
    @overload
    def f(self: A) -> A:
        ...

    @overload
    def f(self: B) -> B:
        ...

    def f(self: Any) -> Any:
        return self

class A(Base):
    pass

class B(Base):
    pass

_ = Base.f(A())
```

## Expected behavior

No warnings.

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/131941779-f2ec3d44-eb42-4931-aecc-d1f1b7a0221c.png)

## Explanation

In practice, the class `Base` could be a base class, or a mix-in used in limited concrete classes, and the method `f` could be a method with different signatures in different concrete classes but uses a same implementation. Static access of `Base.f` alone should always be valid. `Base().f`, aside from the `ABC` restriction, should be considered invalid because of `self` compatibility.

**Comment by erictraut** [comment]
A type checker can't ignore type annotations in some cases. If a parameter is annotated, type consistency needs to be validated.

If I correctly understand your use case, it should be handled using a bound type variable, like this:

```python
from typing import TypeVar

_T = TypeVar("_T", bound="Base")

class Base(ABC):
    def f(self: _T) -> _T:
        return self
```

**Comment by Azureblade3808** [comment]
There are cases in my project that the return type does not match the type of `self`, so the method signature cannot simply be written with type variables.

While I could try some work-around, I'd like to know why you decided to check the type of `self` on static access of a method, when the method might not even get called.

**Comment by erictraut** [comment]
The `self` needs to be type checked because a member access results in a "binding" operation where the `self` parameter passed an argument implicitly. Any time an argument is passed to a parameter, a type checker validates type consistency.

**Comment by Azureblade3808** [comment]
Thank you for explaining. While this behavior breaks some of my tricks, I see what it accomplishes and I'll adapt.
