### ISSUE TITLE
In Windows 10 , Pylance serve the Python built-in functions as "not defined"

### ISSUE THREAD

**Issue by wyqmanutd** [microsoft/pylance-release#1759]
## Environment data

-   Language Server version: v2021.9.0
-   OS and version: Win10 20H2
-   Python version Anaconda3 Python 3.8.5 64-bit

## Expected behaviour

The Pylance language server in VSCode run under Win10 20H2 , should not report with the Python Build-In Functions like:
- "print" is not defined Pylance(reportUndefinedVariable)
- "print" is not defined Pylance(reportUndefinedVariable)
- "print" is not defined Pylance(reportUndefinedVariable)

## Actual behaviour

The Pylance language server in VSCode run under Win10 20H2 , should not report with the Python Build-In Functions like:
- "print" is not defined Pylance(reportUndefinedVariable)
- "print" is not defined Pylance(reportUndefinedVariable)
- "print" is not defined Pylance(reportUndefinedVariable)
![image](https://user-images.githubusercontent.com/69949997/131968513-5aa36b60-6f5c-4119-8db3-241513005007.png)

## Logs
- "print" is not defined Pylance(reportUndefinedVariable)
- "print" is not defined Pylance(reportUndefinedVariable)
- "print" is not defined Pylance(reportUndefinedVariable)

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
This seems to me like your Pylance extension is corrupted. Can you try removing pylance, then opening the extension folder, delete pylance, then restart VS Code and install Pylance again?

The easiest way to find the extension folder is to use the command palette:

![image](https://user-images.githubusercontent.com/5341706/132054583-51e6f381-1605-4ed0-a5ac-4393774b543b.png)

**Comment by wyqmanutd** [comment]
1. We have several correctly installed + configurated VSCode + Pylance with Win10 20H2 , and faced a common situation is that Pylance can analyze well with the external package rather than built-ins. But it did not affected the compiling as well as the running of py file.
2. The tutorials in last response did not help.
3. Meanwhile , this phenomenon did not happen when Pylance is working under Linux such as CentOS
4. We hope that you can do the thorough investigation of focus on the analyzing of Python build-ins running under Win20 20H2

**Comment by jakebailey** [comment]
Can you please provide logs? Our template asked for them, but they were not included. The instructions are mirrored here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

We test on all platforms, and I doubt it this is specific to 20H2 (which I had last year when that was the latest).

**Comment by Taynor** [comment]
Uninstalling pylance and reload visual studio code resolved the issue. Thanks @jakebailey
