### ISSUE TITLE
pylance works on local, but fails on remote ssh

### ISSUE THREAD

**Issue by bearhunt110** [microsoft/pylance-release#1760]
The pylance extensions do not work on remote,  any logs or something I need to provide to debug?

My "python.languageServer" settings sets to "Default" both on local and remote, and when I disable Pylance, the autocompletion starts working.

**Comment by jakebailey** [comment]
Our issue template includes instructions on where to find logs, but the instructions are mirrored here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by jakebailey** [comment]
It's been about a month since this was opened; if this still reproduces and you can produce the logs via the instructions I linked to, I can reopen this.
