### ISSUE TITLE
some functions are not defined

### ISSUE THREAD

**Issue by NOELMANUELPY** [microsoft/pylance-release#1761]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
You haven't filled out the template, so we don't have anything to go off of here. If you can fill out our template, or submit a new issue, we can take a look, but we can't handle a blank issue.
