### ISSUE TITLE
Setting diagnosticSeverityOverrides doesn't work as expected

### ISSUE THREAD

**Issue by zhenya-mamenko** [microsoft/pylance-release#1762]
<h3> Environment data </h3>

-   Language Server version: 2021.9.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.5
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

When in settings.json set **reportGeneralTypeIssues** option to **none**
```json
    "python.analysis.diagnosticSeverityOverrides": {
        "reportGeneralTypeIssues": "none"
    },
```
no errors expected

<h3> Actual behaviour </h3>

![image](https://user-images.githubusercontent.com/38508413/132020587-f068f5bb-3496-4b9a-ba0c-70c34c4d0a7c.png)
![image](https://user-images.githubusercontent.com/38508413/132021501-639ec3d0-e4d1-41c4-be91-51d1018c72a0.png)

<h3> Logs </h3>

<h3> Code Snippet / Additional information </h3>

**Comment by jakebailey** [comment]
Do you have a `pyrightconfig.json` in your workspace root, by chance?

**Comment by zhenya-mamenko** [comment]
yes, it contains
```json
{
    "reportInvalidStringEscapeSequence": false
}
```
but I never used this file🤔
I delete it and all work fine.
Thank you!

**Comment by jakebailey** [comment]
For reference, `pyrightconfig.json` currently takes precedence for rules like these.
