### ISSUE TITLE
Module cannot be resolved from source but can actually be imported [Remote SSH]

### ISSUE THREAD

**Issue by jingw222** [microsoft/pylance-release#1763]
## Environment data

-   Language Server version: v2021.9.0
-   OS and version:
```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

No warnings on import statements

## Actual behaviour

<img width="1508" alt="Screen Shot 2021-09-03 at 11 50 37 PM" src="https://user-images.githubusercontent.com/5494367/132033292-e3567d96-f525-44a1-8d95-0a30611e2dce.png">

However these modules **can** be imported without an error. That being said, when I log onto the remote Linux desktop and run VSCode locally on that machine, the warnings do not exist.

**Comment by jakebailey** [comment]
The notebook kernel isn't the interpreter that Pylance uses; can you try opening up a regular Python file, then ensuring that the interpreter that's selected at the bottom left is the same one that is selected for the notebook?

**Comment by jingw222** [comment]
Yes that solved the issue. Pylance not using the notebook kernel by default does not make sense to me. Why do I have to change it from another regular python script?
