### ISSUE TITLE
Cannot select & copy text on hover boxes

### ISSUE THREAD

**Issue by jingw222** [microsoft/pylance-release#1764]
## Environment data

-   Language Server version: v2021.9.0
-   OS and version: XXX
```
Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:54:53.442Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

## Expected behaviour

When the hovering box shows up, I want to select and copy text inside the box.

## Actual behaviour

Cannot select and copy text on hover boxes, instead, it copies all the code in the cell.

https://user-images.githubusercontent.com/5494367/132036020-66252a33-65e7-43b1-8926-328ce0d0ce67.mov

**Comment by jakebailey** [comment]
This appears to be a VS Code UI bug; Pylance only provides the info, VS Code renders it. I can't transfer the issue to them, but I would report this on the VS Code issue tracker, as it would affect any language (not just Python).
