### ISSUE TITLE
Quick fix for undefined variable does not suggest built-in modules 

### ISSUE THREAD

**Issue by chrisjsewell** [microsoft/pylance-release#1765]
## Environment data

-   Language Server version:2021.9.0 (pyright 21562654)
-   OS and version: OSX 10.15.7 (19H1323)
-   Python version (& distribution if applicable, e.g. Anaconda): Conda 4.10.3, Python 3.7.3.final.0

## Expected behaviour

typing `sys` pylance would suggest adding `import sys`

## Actual behaviour

![image](https://user-images.githubusercontent.com/2997570/132068715-75ef340a-c629-4e3e-a1ca-60b80e73c0e5.png)

## Logs

```
[Info  - 11:57:51 PM] Pylance language server 2021.9.0 (pyright 21562654) starting
[Info  - 11:57:51 PM] Server root directory: /Users/chrisjsewell/.vscode/extensions/ms-python.vscode-pylance-2021.9.0/dist
[Error - 11:57:51 PM] Pyproject file "/Users/chrisjsewell/Documents/GitHub/aiida-task-controller/pyproject.toml" is missing "[tool.pyright] section.
```

**Comment by heejaechang** [comment]
can you enable indexing by adding "python.analysis.indexing: true" in settings.json and see whether this still repro?

**Comment by heejaechang** [comment]
fixed as a part of this - https://github.com/microsoft/pylance-release/issues/297
