### ISSUE TITLE
Some modules in openpyxl  cannot be Auto completed

### ISSUE THREAD

**Issue by 387712522** [microsoft/pylance-release#1766]
When I use the Openpyxl module, some classes cannot be completed automatically，like this：
![image](https://user-images.githubusercontent.com/31927448/132088912-c496a0c8-8b46-4053-9fa5-b40ae1fedb52.png)
Is there any solution？

**Comment by jakebailey** [comment]
The stubs we used are sourced here: https://github.com/MartinThoma/openpyxl-stubs

This library is compiled, so we can't actually infer any of the information from it, and must rely on stubs.

If you believe that these should exist, you may want to report an issue there or submit the code.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
