### ISSUE TITLE
pycryptodome is not loadable at all thought it is without problems in PyCharm

### ISSUE THREAD

**Issue by tomay3000** [microsoft/pylance-release#1769]
`pip install pycryptodome`

```Py
from Crypto.Cipher import AES
from Crypto.Hash import MD5
```

`Exception has occurred: ModuleNotFoundError
No module named 'Crypto' File "...", line #, in <module> from Crypto.Cipher import AES`

-   Language Server version: **2021.9.0 (pyright 21562654)**
-   OS and version: **Win7 x64**
-   Python version (& distribution if applicable, e.g. Anaconda): **3.8.9 x64**

**Comment by erictraut** [comment]
Please provide the log information requested in the issue template. Here are the [instructions](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue). Without logs, we won't be able to diagnose the problem. Thanks!

**Comment by tomay3000** [comment]
It was picking another python installation (from MinGW-W64) by default.
