### ISSUE TITLE
Error-Message for "<>"=operator with Python 2.7

### ISSUE THREAD

**Issue by dpalmetzvbg** [microsoft/pylance-release#177]
## Environment data
VS Code version: 1.47.2
Extension version (available under the Extensions sidebar): Python, Version v2020.7.94776
OS and version: Windows 10
Python version (& distribution if applicable, e.g. Anaconda): 2.7.14
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
Relevant/affected Python packages and their versions: None
Relevant/affected Python-related VS Code extensions and their versions: None
Value of the python.languageServer setting: "python.languageServer": "Pylance"

## Expected behaviour

I am trying to switch to VSCode as my Editor for a OSGEO4W-Project, which is written for Python 2.7.14. Due to a problem with the outline-windows I was told to switch to pylance (https://github.com/microsoft/vscode-python/issues/13091). But pylance seems to have a problem with some python 2.7.14 syntax. Due to some server-restrictions I am not able to switch to python 3 at the moment.

## Actual behaviour

All "<>" operators ar marked as error.
Also all uninoce-calls  (`unicode("just a string")`) are marked as warning.

**Comment by erictraut** [comment]
Pylance works only with Python 3. It doesn't support Python 2.

If you still need to support Python 2.7, the Jedi language server is available.

**Comment by dpalmetzvbg** [comment]
Thanks for your response. But then the problem with the outline-window arises (see my other bug). Seems that I have to switch to python 3 soon. Thanks for your help.
Maybe you should mention that somewhere on the project-page (or did I miss it?).

Von: Eric Traut <notifications@github.com>
Gesendet: Montag, 27. Juli 2020 08:42
An: microsoft/pylance-release <pylance-release@noreply.github.com>
Cc: Palmetzhofer Dietmar <Dietmar.Palmetzhofer@vorarlberg.at>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/pylance-release] Error-Message for "<>"=operator with Python 2.7 (#177)


Pylance works only with Python 3. It doesn't support Python 2.

If you still need to support Python 2.7, the Jedi language server is available

**Comment by jakebailey** [comment]
Yes, it's mentioned in the readme and the marketplace page. (See also #7, #156.)
