### ISSUE TITLE
Type hinting for multiprocessing.Event

### ISSUE THREAD

**Issue by ratara** [microsoft/pylance-release#1770]
I wonder why this is marked as failure. Any suggestions?
![grafik](https://user-images.githubusercontent.com/46249856/132216718-f9e7b6d1-d2fe-42ba-be97-bda14a6af45f.png)

**Comment by CodeCrazy-ywt** [comment]
No, `Event` is a function, which cannot be used in type annotations. If you want to use the class, please add a line `from multiprocessing.synchronize import Event`.

**Comment by ratara** [comment]
@CodeCrazy-ywt : Thanks alot! You saved my day.
But who invents such crazy standard interfaces? I guess i would have seen this by time but it contracdicts the concept of least surprise.
