### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Retr00ooo** [microsoft/pylance-release#1773]
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.9.1191016588`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakebailey** [comment]
I think to troubleshoot this one, we really need a profile that shows the activation. I'm pretty sure VS Code does so, but maybe not. Was one included?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
