### ISSUE TITLE
pylance cannot recognize instance variables in the Pyqt5 module, No smart completion

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#1780]
## Environment data
版本: 1.60.0 (user setup)
提交: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
日期: 2021-09-01T10:43:34.699Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT ia32 10.0.18363
Python:3.8.4
Pylance:v2021.9.1-pre.1

## Expected behaviour
This is use Jedi, It can correctly identify the variable type.

![image](https://user-images.githubusercontent.com/33288114/132484367-694c2475-bc32-4810-a52b-a55f4af3aab4.png)

## Actual behaviour

Almost all instance variables are recognized as Any in Pylance
![image](https://user-images.githubusercontent.com/33288114/132484114-18978cf7-9285-47d6-b60f-7429b395cb45.png)

## other info
![image](https://user-images.githubusercontent.com/33288114/132484837-17d72fd6-5f9f-459d-9d33-20a196d55af1.png)

The setupUi method inherits from Ui_ui.Ui_Mainwindow, after executing this method, it will bind tablewidget and other properties
Jedi can correctly infer the various attributes bound to the instance object after the setupUi method is executed, but Pylance cannot correctly infer it.
This is Ui_ui.Ui_Mainwindow code, It is generated by qtdesigner
![image](https://user-images.githubusercontent.com/33288114/132485386-c9a7c82a-dd73-4dc8-9d37-7bcbe161a054.png)

**Comment by judej** [comment]
@CatNoFishing Thanks for the report. Will investigate this. thanks

**Comment by CatNofishing** [comment]
After i update pylance to version v2021.9.2-pre.1,This problem disappeared
