### ISSUE TITLE
not a known member of "None" - Pylance(reportOptionalMemberAccess) 

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#1785]
Hello! I keep having this **typing issue** with a context class:
![image](https://user-images.githubusercontent.com/218956/132583061-025b7244-1de3-4d75-ad8a-b89332047bd6.png)

- I declare an instance var as `typing.Optional[P4.P4]`
- on `__enter__` I fill it with a P4 instance
- on another method it keeps complaining about accessing `None`
- 🤷‍♀️

How do I annotate this correctly?! I thought that was exactly what the `typing.Optional` is for! :( 
halp!

<details>
<summary><b>some example context class code</b></summary>

```python

import typing
import P4

def connect(workspace):
    p4 = P4.P4()
    p4.client = workspace
    return p4

class Connection(object):
    def __init__(self, workspace=None):
        self.workspace = workspace
        self.p4: typing.Optional[P4.P4] = None

    def __enter__(self):
        self.p4 = connect(workspace=self.workspace)
        return self.p4

    def __exit__(self, *args):
        self.p4.disconnect()
```
</details>

Eventually I'd like to have this in a **stub** file and have the `.py` one Python2 AND 3 compatible ...
How would I write this there?

<details>
<summary><b>some example stub code</b></summary>

```py
import typing
import P4

def connect(workspace: str) -> P4.P4: ...

class Connection:
    p4: typing.Optional[P4.P4] = ...
    workspace: str = ...
    def __init__(self, workspace: str = ...) -> None: ...
    def __enter__(self) -> P4.P4: ...
    def __exit__(self, *args: typing.Any) -> None: ...
```
</details>

**Comment by erictraut** [comment]
Static type checkers are able to understand changes to specific variables within a single function's code flow graph, but they typically do not understand changes across functions. In most cases, the order of invocation of functions cannot be determined statically. Even in cases where it could be, tracking changes to variables across such invocations would be very computationally expensive.

In your example, you happen to know that the order in which you are invoking these functions is "safe" from a type perspective, but a static type checker can't make that same assumption. For a somewhat contrived example, `__exit__` could be invoked manually, not in conjunction with a call to `__enter__`.

The way I recommend handling this is to document your assumptions in the form of assert statements. This serves not only human-readable "comments", it also tells the type checker what assumptions you're making, and it provides runtime validation of those assumptions.

In your specific example, this would involve adding the following line to the start of the `__exit__` method:
```python
assert self.p4 is not None
```

**Comment by jakebailey** [comment]
I'm going to close this, since this is behaving as expected.

One thing to keep in mind is that `Optional[T]` is just shorthand for `Union[T, None]` (or just `T | None` in more recent versions of Python and our tooltips). It's not treated specially in any way.

As a suggestion to the API given in the stub in the issue, I'd consider hiding `p4` away as `_p4` and not making it a part of the API, if the intent is that the connection is used as a context manager, but that's up to you.

**Comment by ewerybody** [comment]
Ah ok! Thanks SO much @erictraut 🙏 that `assert self.p4 is not None` seems like a fair thing at that point.

@jakebailey: Yeah I also read that in the docs somewhere. [Ah here: docs.python.org/3/library/typing.html#typing.Optional](https://docs.python.org/3/library/typing.html#typing.Optional)
regarding the API: user is expected to have access to the p4 instance when IN the context like so:
```
with Connection() as p4:
    p4.run_sync('somefile.py')
```
This way one has no access to the instance of the context but ... `True` I should hide these variables nonetheless 👍

The stub is not yet working tho. But I'll put it in another issue then.
