### ISSUE TITLE
No syntax error in invalid `for` statement

### ISSUE THREAD

**Issue by Molkree** [microsoft/pylance-release#1805]
## Environment data

-   Language Server version: v2021.9.1
-   OS and version: Win10 19043.1165
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Expected behaviour

Some error diagnostics as it is invalid syntax.

## Actual behaviour

No errors at all.

## Code Snippet / Additional information

```python
for in range(3):
    print(5)
```

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202192-16-september-2021
