### ISSUE TITLE
mark no member for tree member of git commit in git package

### ISSUE THREAD

**Issue by assafmendelson** [microsoft/pylance-release#1810]
-   Language Server version: v2021.9.1
-   OS and version: local windows 10, remote: centos8
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6

## Expected behaviour

I have a virtual environment, in it I installed GitPython==3.1.11
I then have the following code:
```python
import git

repo = git.Repo(".", search_parent_directories=True)
a = repo.commit(repo.active_branch)
b = a.tree
```

while autocomplete manage to suggest a.tree correctly, I get a squickly red line from pylance with error:
 Cannot access member "tree" for type "SymbolicReference"
  Member "tree" is unknownPylancereportGeneralTypeIssues

I set python.analysis.typeCheckingMode to basic

I also tried to setup the type directly, i.e.:

```python
b: git.objects.commit.Commit = a.tree
```

however I get the error message "objects" is not a known member of modulePylancereportGeneralTypeIssues

That said:
```python
a: git.SymbolicReference.commit = self.repo.commit(repo.active_branch)
```
works correctly.

Needless to say, this code runs properly when running directly with python
## Logs

```
User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayedcf'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayedcf'
User belongs to experiment group 'pythonRememberDebugConfigcf'
Starting Pylance language server.
Python interpreter path: ./venv/bin/python
Error 2021-09-13 10:26:00: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+dpsim00/home/cyc/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+dpsim00/home/cyc/.config/Code/User/settings.json')
	at _handleError (/home/cyc/.vscode-server/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/out/vs/server/remoteExtensionHostProcess.js:94:160087)
	at async y.readText (/home/cyc/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:9:314351)
	at async p.doesFileNeedToBeFixed (/home/cyc/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:823854)
	at async /home/cyc/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:822981
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/cyc/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:822927)
	at async p.updateTestSettings (/home/cyc/.vscode-server/extensions/ms-python.python-2021.9.1218897484/out/client/extension.js:59:822554)] {
  code: 'FileNotFound'
}
> conda --version

**Comment by judej** [comment]
Looking at the repo, it seems they are planning on typing the module. But they have not done that yet. I'd recommend you ask the authors to add the type info. That way, the completion experience will be better.

**Comment by jakebailey** [comment]
`commit` returns a union of a bunch of types:

![image](https://user-images.githubusercontent.com/5341706/133133245-ff814a34-9e80-4f54-8475-2d8171f7a3ff.png)

Which then makes it not possible to do `.tree` without explicitly casing the type:

![image](https://user-images.githubusercontent.com/5341706/133133334-19b6986e-44c9-4293-889f-92dfb4a422ee.png)

The rest appears to be re-exporting issues; the library does claim to be `py.typed` (but then forgets to ship the file in the library), but then uses dynamic expressions that a static type checker may not support.
