### ISSUE TITLE
Missing autocomplete and intellisense about matplotlib.lines.Line2D

### ISSUE THREAD

**Issue by molly-w** [microsoft/pylance-release#1811]
## Environment data

-   VS Code version: 1.60.0
-   Extension version (available under the Extensions sidebar): v2021.10.1219758147-dev
-   OS and version: Win10 Version2004(OS Build 19041.1165)
-   Python version (& distribution if applicable, e.g. Anaconda):Python3.9.5 64bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: matplotlib
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance v2021.9.2-pre.1
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Code
```
import matplotlib.pyplot as plt
line, =plt.plot([2,3],[4,5],'-')
line.set_linewidth(5)
plt.show()

```
## Expected behaviour

when it comes to line3, type `line.`, I want all the properties and methods displayed from the [Line2D](https://matplotlib.org/stable/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) class

## Actual behaviour

No properties or methods about Line2D displayed:
![image](https://user-images.githubusercontent.com/63043224/133051776-70a30fee-f1a1-40cd-bf6d-b04584508cc1.png)

**Comment by judej** [comment]
Thanks for the report. It looks like an incomplete stub. Will look at this

**Comment by judej** [comment]
This has been fixed with a couple of recent updates. Please reopen if this is an issue.
