### ISSUE TITLE
Python continually re-analysing all files when unrelated files change (diagnosticMode=workspace)

### ISSUE THREAD

**Issue by richardjharris** [microsoft/pylance-release#1814]
## Environment data

-   VS Code version: 1.58.2
-   Extension version (available under the Extensions sidebar): v2021.8.1159798656
-   OS and version: Manjaro Linux 21.1.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.6 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

When running a command to generate a large data file in the Python project directory, VS Code should do nothing.

## Actual behaviour

Instead the bottom status bar continually shows '40 files to analyze'. Shortly after finishing analysis, it triggers again (roughly every 5 seconds) even though no Python files have been changed. In addition, if the Explorer is used to create a new file or rename a file, and the edit box for the filename is open, the edit box will be forcibly closed (and the file created or renamed with whatever had been typed in the box), as if the user had pressed Enter.

## Steps to reproduce:

1. Open a non-trivial Python project with VS Code, and type checking enabled via Pylance
2. In another shell, perform a command like `yes > foo` to create a file that continually updates
3. Observe "X files to analyse" appear in the status bar repeatedly
4. Try to create a new file with the Explorer. Leave the filename edit box open. Observe that the file is created (if the box contains text) or file creation is cancelled (if box is empty) automatically after a few seconds
5. Try to rename a file via the Explorer. Leave the filename edit box open. Observe that the rename command is automatically committed after a few seconds.

## Config

The following JSON config is specified. Setting `python.analysis.indexing` to false did not alleviate the issue. but changing `diagnosticMode` to `openFilesOnly` does.

```
    "python.analysis": {
        "indexing": true,
        "typeCheckingMode": "basic",
        "diagnosticMode": "workspace"
    },
```

I guess if any file changes then the entire workspace is reanalysed, but this does not work well if there are large files being generated in the project root directory. If this is an unsupported case that's fine, although I'd very much appreciate a workaround as the files have .json and .sqlite extensions (i.e. they're not Python)

Thanks!

**Comment by jakebailey** [comment]
This sounds like a file watching problem; would you mind creating a `pyrightconfig.json` and add `"verboseOutput": true` to it, then post the trace logs or take a look to see what FS events are coming in when the analysis is restarted?

**Comment by richardjharris** [comment]
```
[Info  - 22:59:37] SourceFile: Received fs event 'add' for path '/home/rjh/yomikun/database/tmp/parAT6d2.par'
[Info  - 22:59:37] SourceFile: Received fs event 'add' for path '/home/rjh/yomikun/database/tmp/parIRdt1.par'
[Info  - 22:59:37] SourceFile: Received fs event 'change' for path '/home/rjh/yomikun/database/w.jsonl'
[Info  - 22:59:37] SourceFile: Received fs event 'change' for path '/home/rjh/yomikun/database/tmp/parAT6d2.par'
[Info  - 22:59:37] SourceFile: Received fs event 'change' for path '/home/rjh/yomikun/database/tmp/parIRdt1.par'
Background analysis message: invalidateAndForceReanalysis
[Info  - 22:59:37] Searching for source files
[Info  - 22:59:37] Found 43 source files
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze
```

The 'change' event is actually a deletion of the file. For example I can touch and then delete a file manually:

```

[Info  - 23:08:05] SourceFile: Received fs event 'add' for path '/home/rjh/yomikun/database/tmp/a'
[Info  - 23:08:07] SourceFile: Received fs event 'change' for path '/home/rjh/yomikun/database/tmp/a'
Background analysis message: invalidateAndForceReanalysis
(as above)
```

So the problem is not the JSON file being built, but rather a file being deleted triggering a full re-analysis - my script happens to create and delete temporary files in `tmp/` repeatedly, triggering a re-analysis each time. (i.e. my initial post was incorrect, `yes > file` is not enough to cause this) Curiously, this happens whether or not the `tmp` path is added to the `ignore` or `exclude` parameter.

**Comment by jakebailey** [comment]
The ignore/exclude configuration options are about diagnostics; if a file imports another file that is in include/exclude, we still need to analyze it, it's just that we won't show diagnostics in it. If we were to use these to ignore certain FS events, we'd end up with an inconsistent state.

It seems like this database being within the workspace is causing problems; we reload the analysis on many FS events as it's possible that a good bulk of them will affect an analyzed file (e.g. make an import resolve that didn't before). I'm working on trying to clean this up; it may be the case that we can ignore more events, but the problem is that we get a pretty limited set of information from the watcher (as you noted, "change" was actually a deletion, so we can't even trust the event type). Deletions of folders are especially hard, because we can't check to see what it was beforehand to know if it mattered.

Can you try setting `files.watcherExclude` in your VS Code settings to exclude that database file? This FS watching is powered by VS Code itself, so it may work out to exclude them there.

**Comment by richardjharris** [comment]
Thanks, adding `"**/tmp/**"` to `files.watcherExclude` has resolved the issue for me!

I expect repeatedly deleting files inside the workspace is a rather niche case, and I also could have worked around the issue by putting `tmp` somewhere else, but it's good to know there's a more general solution.

**Comment by jakebailey** [comment]
I'm glad that worked; previously I asked someone to do this and it didn't help, so it was truthfully a shot in the dark.

Adding that should make VS Code in general perform better, as it's no longer processing every change that your program is making to those files.

I do think there is work to be done here to try and not reanalyze when not needed, and I'm hoping to be able to address that.

**Comment by heejaechang** [comment]
linking PR fixing same root cause

**Comment by alexlatif** [comment]
@jakebailey @bschnurr  I am dealing with this same issue on mac M1, using 

Pylance v2023.5.30 
VScode Version: 1.78.2
Python 3.11

[pylance_log.txt](https://github.com/microsoft/pylance-release/files/11524744/pylance_log.txt)

using "files.exclude", "files.watcherExclude" and "search.exclude" with all these files

            "**/webpack-stats.json": true,
            "**/webpack-bundle-debug-stats.json": true,
            "**/venv/**": true,
            "**/venv_old": true,
            "**/staticfiles": true,
            "**/package-lock*": true,
            "**/dist": true,
            "**/dev_media": true,
            "**/local_junk": true,
            "**/coverage": true,
            "**/htmlcov": true,
            "**/__pycache__": true,
            "**/rust/**/target/**": true,
            "**/.vscode/**": true,
            "**/.mypy_cache/**": true,
            "**/.git/**": true,
            
it seems it is still trying to analyze them. every change especially deletion causes over 20 files to be analyzed and my CPU just gets eaten, code freezes and I am stuck but to remove Pylance altogether. I have no other extensions running.

**Comment by heejaechang** [comment]
@alexatif this issue is already closed. please open new issue.

**Comment by LeonardoAlchieri** [comment]
I'm currently having the same issue on multiple M1 Macs. Has the issue been opened somewhere?

**Comment by cemoke** [comment]
> 

I am having the same issue on M1 Mac as well

**Comment by lrahal** [comment]
same!

**Comment by debonte** [comment]
@LeonardoAlchieri, @cemoke, @lrahal, one of you should open a new issue.

**Comment by spookyuser** [comment]
same
