### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by Nani-7989** [microsoft/pylance-release#1821]
selenium Keys are not imported

**Comment by CodeCrazy-ywt** [comment]
Screenshot? Error log?

**Comment by jakebailey** [comment]
You haven't filled out the template, so there isn't enough information to help you.

Consider looking at our troubleshooting page, which covers many ways you can diagnose unresolved imports. If the page doesn't help, instructions to file an issue are at the bottom.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md

**Comment by Nani-7989** [comment]
Closed issue : 

webdriver.exe X64 needs to be in the path in order to import Keys
