### ISSUE TITLE
support typehints for classes that may or may not exist

### ISSUE THREAD

**Issue by iscai-msft** [microsoft/pylance-release#1829]
Pylance currently is not able to provide typehints for a class that may or may not exist. In my code, I'm adding extension points in a separate file, so other users can patch my code. Since users may or may not add these extension points, I write my code to import the extension classes in a try except block. Here's what my code looks like

```python
try:
    from ._patch import ExtensionsMixin
except ImportError:
    ExtensionsMixin = object

class MyClass(ExtensionsMixin):
   ...
```

Users can add methods etc through the `ExtensionsMixin` extension in `_patch.py`, like this:
```python
class ExtensionsMixin:
    def added_method(self):
        ...
```
However right now pylance is not showing typehints for anything users added in these extension classes because the import of these extensions is in a try except block. The typehints I get for `MyClass` **will not** included `added_method`. However, if I move the import of the mixin class out of the try except, I **will** get typehints for `added_method`, but I can't structure my code like that, because I can't rely on there being an `ExtensionsMixin` in `_patch.py`. I'm asking if pylance can add typehints in this situation, i.e., if they can dynamically determine whether a class in a try except block exists, and if so, add typehints for that class. Thank you!

**Comment by erictraut** [comment]
Pyright (the type checker that underlies pylance) is a static type analyzer. As such, it needs to statically determine the hierarchy of a class to perform its analysis. In your example, the class hierarchy is dynamically determined at runtime, so it cannot be analyzed by a static type analyzer.

As a workaround, you can use a `TYPE_CHECKING` conditional as described in PEP 484.

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ._patch import ExtensionsMixin
else:
    try:
        from ._patch import ExtensionsMixin
    except ImportError:
        ExtensionsMixin = object
```

or

```python
try:
    from ._patch import ExtensionsMixin
except ImportError:
    if not TYPE_CHECKING:
        ExtensionsMixin = object
```

**Comment by iscai-msft** [comment]
ok perfect this works out! thank you so much @erictraut for your quick response! Closing!
