### ISSUE TITLE
Direct access of d-under members outside the containing class should be forbidden

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1831]
..., and access using their mangled names should be allowed.

## Environment data

-   Language Server version: 2021.9.3-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.11 Anaconda

## Sample code

```python
class C:
    __var: object = None

c = C()

_ = c.__var  # Line A
c.__var = 0  # Line B

_ = c._C__var  # Line C
c._C__var = 0  # Line D
```

## Expected behavior

Line A & line B are invalid, while line C and line D are valid.

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/133869010-5cb5ec7d-0e09-4cf9-9601-c44ef8ed42ac.png)
![image](https://user-images.githubusercontent.com/15389744/133869031-150abb26-b520-4d8a-844d-9a87e44ac718.png)
![image](https://user-images.githubusercontent.com/15389744/133869020-b386d17e-70bf-44cc-9b48-429e5729b05e.png)

**Comment by erictraut** [comment]
Pylance is emitting errors for Line C & D (as it should), but it's not reporting errors on A & B. So I agree this is a false negative because A & B will result in runtime exceptions.

For what it's worth, the current behavior is consistent with mypy. That doesn't mean it's correct.

**Comment by erictraut** [comment]
Actually, pylance does correctly emit errors on A & B if you enable the `reportPrivateUsage` diagnostic rule. This rule is disabled by default in basic type checking mode. So I think the behavior is correct.

**Comment by Azureblade3808** [comment]
Ah, I've forgot that I disabled `reportPrivateUsage` because I needed to access s-under members across different classes. Closing.
