### ISSUE TITLE
Hover Docs repeating thrice in python pandas functions

### ISSUE THREAD

**Issue by Trid-collab** [microsoft/pylance-release#1833]
vs code ver 1.60.1 and latest insiders 
pylance - v2021.9.2
win 10

When I am enabling the hover enabled for python ,  the pandas function shows the details thrice instead of once like as shown in the screenshot below: Is there something wrong in my config

![image](https://user-images.githubusercontent.com/61322708/133885124-96d40904-7c54-48ff-aeaa-64fdb50be7b6.png)

**Comment by jakebailey** [comment]
This is currently intended behavior; those are there different overloads for the same function, which is why they are shown as different.

(I don't think TS shows all overloads in their completion/hover, though, as a comparison.)

**Comment by Trid-collab** [comment]
Thank you for the clarification.
