### ISSUE TITLE
JavaScript code marked as error

### ISSUE THREAD

**Issue by SirGarnet** [microsoft/pylance-release#1836]
## Environment data

-   Language Server version: 2021.9.2
-   OS and version: Windows_NT x64 10.0.19043
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Expected behaviour

Accepting the syntax to be correct

## Actual behaviour

![image](https://user-images.githubusercontent.com/3258297/133935803-79241025-fe68-413f-b853-9c09c2c34f87.png)

## Logs

```
no logs
```

## Code Snippet / Additional information

HTML - base.html
```HTML
<script>
    function translate(sourceElem, destElem, sourceLang, destLang) {
        $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
        $.post('/translate', {
            text: $(sourceElem).text(),
            source_language: sourceLang,
            dest_language: destLang
        }).done(function(response) {
            $(destElem).text(response['text'])
        }).fail(function() {
            $(destElem).text("{{ _('Error: Could not contact server.') }}");
        });
    }
</script>
```

```python
no code
```

**Comment by jakebailey** [comment]
This is the issue tracker for Pylance, the language server for Python. It doesn't handle HTML or JS. I would suggest filing an issue on the main VS Code issue tracker. https://github.com/microsoft/vscode/issues

**Comment by CodeCrazy-ywt** [comment]
> 
> 
> ## Environment data
> 
> 
> 
> -   Language Server version: 2021.9.2
> -   OS and version: Windows_NT x64 10.0.19043
> -   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
> 
> ## Expected behaviour
> 
> Accepting the syntax to be correct
> 
> ## Actual behaviour
> 
> ![image](https://user-images.githubusercontent.com/3258297/133935803-79241025-fe68-413f-b853-9c09c2c34f87.png)
> 
> ## Logs
> 
> 
> 
> ```
> no logs
> ```
> 
> ## Code Snippet / Additional information
> 
> HTML - base.html
> ```HTML
> <script>
>     function translate(sourceElem, destElem, sourceLang, destLang) {
>         $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
>         $.post('/translate', {
>             text: $(sourceElem).text(),
>             source_language: sourceLang,
>             dest_language: destLang
>         }).done(function(response) {
>             $(destElem).text(response['text'])
>         }).fail(function() {
>             $(destElem).text("{{ _('Error: Could not contact server.') }}");
>         });
>     }
> </script>
> ```
> 
> ```python
> no code
> ```
> 

You need an escape character inside a single-quoted string.
