### ISSUE TITLE
PyLance 2021.9.2

### ISSUE THREAD

**Issue by robmac29** [microsoft/pylance-release#1837]
With some of my programs the newest release causes electron_node bundle.js to have "high" cpu usage. It bumps the cpu speed to 4.4 ghz and persists. Changing back to the last version 2021.9.1 gets rid of this problem.

**Comment by judej** [comment]
Thanks for the report. Could you please attach the logs emitted when you are seeing this problem?

**Comment by pohmelie** [comment]
I think I have the same problem. 100% cpu of 1 core by pylance, but bringing 2021.9.1 back did nothing, same behavior. Pylance log consist of two info lines with version and path. Like this:
```
[Info  - 11:29:50 AM] Pylance language server 2021.9.1 (pyright e804f324) starting
[Info  - 11:29:50 AM] Server root directory: /home/poh/.vscode/extensions/ms-python.vscode-pylance-2021.9.1/dist
```
My usecase is like this:
- Type some line of python code
- It is all in white color without syntax highlight
- Pylance 100% cpu 1 core
- After 20-30 seconds pylance calms down
- Syntax highlight appears

**Comment by jakebailey** [comment]
If going back to 2021.9.1 didn't change anything, then your issue is likely not the same as the original issue.

Can you please file a new issue with a reproduction, e.g. what it is you typed?

**Comment by benelgiac** [comment]
Well, I know it doesn't help much but after the lastest upgrade to 2021.10.1 I get the same problem as well, with pylance, as soon as I switch to my virtual env python interpreter. Htop shows 50% more CPU on 

`/usr/share/code/code /home/giacomo/.vscode/extensions/ms-python.vscode-pylance-2021.10.1/dist/server.bundle.js --cancellationReceive=file:93621ae8b7dea8fa85157875361ce625874b52229c --node-ipc --clientProcessId=36819`

where 36819 is 

`/usr/share/code/code --inspect-port=0 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost --skipWorkspaceStorageLock`

With the default log settings, pylance doesn't show any logs at all.

**Comment by judej** [comment]
Thanks for the update
