### ISSUE TITLE
Return type Union[List,None] causes Object of type "None" is not subscriptable error

### ISSUE THREAD

**Issue by abceleung** [microsoft/pylance-release#1839]
<h3> Environment data </h3>

-   Language Server version: 2021.9.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.7.9 (64bit)
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

I defined a class method that returns Union[ List[Dict[str,str]] ,None]. 
![image](https://user-images.githubusercontent.com/82202780/133967870-52ce4c13-664e-451e-82ac-82b6bc180c7e.png)
When I call the method and try to use the returned List, an unexpected warning *"Object of type "None" is not subscriptable"* pops up.
Is this intended? How do I fix this error (or less preferably suppress it)?

<h3> Actual behaviour </h3>

Error shows up here
![image](https://user-images.githubusercontent.com/82202780/133967781-05ab046a-2b4a-4ce4-8071-0a4a01464aa2.png)

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by erictraut** [comment]
This is probably a bug in your type annotations or your code. There's not enough information in the screen shots above to diagnose the problem. Please provide a self-contained minimal code sample that exhibits the error so we can provide additional assistance.
