### ISSUE TITLE
I'm getting "group" is not a known member of "None" error on some code that I got off of StackOverflow a few years back that works correctly

### ISSUE THREAD

**Issue by sean-galloway** [microsoft/pylance-release#1841]
<h3> Environment data </h3>

-   Language Server version: 2021.9.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): Anaconda 3.8.3
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Report no Error

<h3> Actual behaviour </h3>

Reporting: "group" is not a known member of "None"

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>
import re

class REMatcher(object):
    ''' This is a utility function to help out with matching regex's and
        grabbing the matches out in a way that is similar to how perl
        does it.
    '''
    def __init__(self, matchstring):
        self.matchstring = matchstring

    def match(self, regexp):
        self.rematch = re.match(regexp, self.matchstring,
                                re.IGNORECASE | re.MULTILINE | re.DOTALL)
        return bool(self.rematch)

    def group(self, i):
        return self.rematch.group(i) #####<-------------------- This is the line that PyLance flags with an error

```python
XXX
```

**Comment by CodeCrazy-ywt** [comment]
That's because `self.rematch` returns a may-be-None object. You should first use a `if self.rematch is None` check first.

**Comment by sean-galloway** [comment]
That fixed the problem. Thank you so much for helping to clean up my code.
