### ISSUE TITLE
Code completion not working for collections when the key is taken from a variable.

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/pylance-release#1843]
## Environment data

-   VS Code version: 
![image](https://user-images.githubusercontent.com/20190653/133888603-05ed8199-fcbb-403f-9176-e8f14b7d819e.png)

-   Extension version (available under the Extensions sidebar): 
![image](https://user-images.githubusercontent.com/20190653/133888605-c6d03215-b9c2-4d61-a8f4-e068a63041fd.png)

-   OS and version: Win10
-   Value of the `python.languageServer` setting: "python.languageServer": "Pylance",

## The issue

Something like:
![image](https://user-images.githubusercontent.com/20190653/133888730-a1c97505-5d92-4601-a37c-c2744a9ce006.png)
gives code completion, whilst:
![image](https://user-images.githubusercontent.com/20190653/133888707-8a9faf13-96a6-495c-9aa9-e04bec70bc89.png)
does not.

## Expected behaviour
It should not matter whether the key I feed in is a literal or taken from else where.

**Comment by jakebailey** [comment]
`dict[str]` is invalid; are you meaning to have `dict[str, str]` or something? You need to give it both the key and the value type, so it's likely that this is behaving incorrectly because the result is `Any`.
