### ISSUE TITLE
Renaming x in "for x in myCollection" renames x even outside the for loop scope.

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/pylance-release#1844]
-   VS Code version: 
![image](https://user-images.githubusercontent.com/20190653/133887605-c1286acc-ec9d-4931-a5e8-50223d6fd617.png)

-   Extension version (available under the Extensions sidebar): XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda):
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Relevant/affected Python packages and their versions: v2021.9.1230869389
- 
![image](https://user-images.githubusercontent.com/20190653/133887624-154114e5-2e73-4534-bd50-b5cf48255140.png)

-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: XXX

## Expected behaviour

Only the relevant scope should be affected - which is the scope that the for loop creates

## Actual behaviour

https://user-images.githubusercontent.com/20190653/133887630-487e7cbf-a7e6-41e9-93b5-4464f7e296e1.mp4

**Comment by erictraut** [comment]
In Python, `for` and `while` loops don't introduce their own scope. They are part of the scope of their containing scope, as are variables that are used within them.

**Comment by jakebailey** [comment]
Yeah, I believe we've overall determined this to be as designed.

Try running:

```python
for x in [1, 2, 3]: pass

print(x)
```

It'll print 3.

**Comment by ItsCubeTime** [comment]
Aha, well this feels quite wrong coming from other languages 🤔

Doesnt this easily introduce naming conflicts? Feels very error prone... Personally I love being able to just write out several hundred lines of code in a single function without having to worry about organizing it too much - having to define functions all over just for the sake of creating scopes takes time of its own
