### ISSUE TITLE
Existing module member gets reported as not known

### ISSUE THREAD

**Issue by meollab** [microsoft/pylance-release#1846]
### Environment data
* Language Server version: 2021.9.2
* OS and version: Linux x64
* Python version (and distribution if applicable, e.g. Anaconda): Python 3.7.5 (64bit)
* python.analysis.indexing: undefined
* python.analysis.typeCheckingMode: basic

### Expected behaviour
```python
import bs4

def blah(a: bs4.Tag):
    pass
```
Should not yield any warning.

### Actual behaviour
Pylance marks an error in the `def blah...` line:

`"Tag" is not a known member of module Pylance(reportGeneralTypeIssues) [3, 17]`

### Code Snippet / Additional information

* This error wasn't reported by 2021.9.1 . None of the changes mentioned in the changelog looks related to this behaviour to me.
* The following line does not cause an error in the python interpreter
```python
from bs4 import Tag
```

**Comment by erictraut** [comment]
The symbol `Tag` is not exported from the top-level module of `bs4`. It is exported from `bs4.element`. The stub file `beautifulsoup4/bs4/__init__.pyi` does not re-export `Tag`. To indicate that this symbol is re-exported from the top-level module, it would need to use a redundant form of import as specified in PEP 484. That would look like `from .element import Tag as Tag`.

If you think that this is an error, please file a bug (or a PR) in the [typeshed repo](https://github.com/python/typeshed/blob/master/stubs/beautifulsoup4/bs4/__init__.pyi).

Alternatively, import `Tag` from the `bs4.elements` submodule, like this:
```python
from bs4.element import Tag

def blah(a: Tag):
    pass
```

**Comment by meollab** [comment]
Oh, I see. I suspected something like that, but seeing that the symbol was correctly imported by Python and that nothing in the changelog looked related I thought that this could be some kind of regression. With your response and reading again the changelog I guess that this change is due to the 1.1.168 "Behavior Change: Enforce PEP 484 rule (...) ", sorry for not catching that.

Anyway, thanks for your prompt response!
