### ISSUE TITLE
Improved docstring display support

### ISSUE THREAD

**Issue by abgivant** [microsoft/pylance-release#1848]
## Environment data
VS Code version:  1.18
Python Extension version:  0.8.0
Python Version:   3.4
OS and version:   Windows 10

![image](https://user-images.githubusercontent.com/3431954/32667855-8b6ebb94-c601-11e7-832f-f08bbdeef923.png)

There is currently very little support for python docstrings, at least using the reST format that we use in our project. Existing docstrings are displayed in the intellisense dialog, but the parameters aren't interpreted as parameters, meaning that there is no type inference being done off of the documentation.

The two main things that would be helpful are:

1. Recognize existing docstrings and defined parameters/types
1. Include the ability to auto-generate docstrings, inferring types from the function signature when possible

Thanks!

**Comment by jakebailey** [comment]
Since this was transferred, I'm going to close this; my update above was some 9 months ago and Pylance's docstring handling has been much improved. Any specific issue should be opened as a new issue.
