### ISSUE TITLE
Outline says No Symbols Found for the current doc. start type and symbols appear

### ISSUE THREAD

**Issue by atomlin** [microsoft/pylance-release#1852]
Originally opened as microsoft/vscode-python#2434 , which was closed as duplicate of microsoft/vscode-python#2334 

I updated to 1.27.1 this am to get the fix for microsoft/vscode-python#2334

I opened existing file that had problem before. Same problem as 2334. Hit space and symbols appear.

Cut and paste all code from that file to new file, saved and closed new file. On open of new file, symbols appear. On Open of old file with identical code no symbols until hit space.

## Environment data
VS Code version: 1.27.1
Extension version (available under the Extensions sidebar): 2018.8.0
OS and version: Ubuntu 16.04.3
Python version (& distribution if applicable, e.g. Anaconda): 3.5.2
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
Relevant/affected Python packages and their versions: N/A
## Actual behavior
Outline view does not display any symbols after file open. Outline view shows 'No symbols found in document xxx'. On editing the file symbols appear in couple of seconds

## Expected behavior
Symbols appear in outline window after opening file

## Steps to reproduce:
Open file
## Logs
None

Original file
![image](https://user-images.githubusercontent.com/7913505/45242785-2df2c400-b2a6-11e8-979c-64b67626f3da.png)

New file with same code
![image](https://user-images.githubusercontent.com/7913505/45242735-fe43bc00-b2a5-11e8-83ec-910e1be56b29.png)

**Comment by jakebailey** [comment]
@brettcannon Our side is #1823 (so I guess I could this as a dupe), but as far as I'm concerned, issues with the outline only appearing after typing are squarely in the client or VS Code's domain and need to be fixed there. We don't even get the request for the outline when this happens.

We're only at the stage where we need to reproduce this and then debug it in the Python extension to see.

**Comment by Corallus-Caninus** [comment]
Same issue as of now for rust-analyzer language server.

**Comment by jovyllebermudez** [comment]
Tw, hoq ro ciew it.

**Comment by dbabits** [comment]
I am on version 1.87 (February 2024) and experience the same problem.
In outline, it always shows "no symbols found for file.py"
All consoles (problems, output, terminal ) are empty.
I am on RHEL8, projecting UI using X. (no code server etc)

**Comment by debonte** [comment]
@dbabits, this issue has been closed for a long time. Please open a new one. If you're really not seeing anything in the output pane, not just under Python Language Server, but in any of the logs, I'd guess that this is a VS Code issue rather than a Pylance issue, so I'd suggest opening it here: https://github.com/microsoft/vscode/issues
