### ISSUE TITLE
Fail fast on invalid rename, i.e do not show the input box asking for new symbol name

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#1853]
## Environment data

- VS Code version: 1.43
- Extension version (available under the Extensions sidebar): 2020.2.64397
- Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): tested with both. Doesn't seem to effect this

## Steps to reproduce:
1. In a python file, place cursor on `None` and try to rename it using F2
1. See input box
1. Enter a new name and press enter

## Bug
See notification that says `No result`!

Here's what our builtin js/ts extension shows for this case (we show this before the input appears):

<img width="539" alt="Screen Shot 2020-03-04 at 10 26 29 PM" src="https://user-images.githubusercontent.com/12821956/75953959-648fa780-5e67-11ea-8bdb-14fd237dfa16.png">

This is implemented using `prepareRename`: https://github.com/microsoft/vscode/blob/c0c9e0043ce6133042268f22847021ad9a1ce410/extensions/typescript-language-features/src/features/rename.ts#L34

**Comment by jakebailey** [comment]
This is #1418.
