### ISSUE TITLE
Implement "Go To Implementation"

### ISSUE THREAD

**Issue by wesleybowman** [microsoft/pylance-release#1855]
## Environment data

- VS Code version: 1.27.2
- Extension version (available under the Extensions sidebar): 2018.8.0
- OS and version: Ubuntu 18.04
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.5
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Relevant/affected Python packages and their versions: N/A

## Actual behavior

I can "Go To Definition" (either with `F12` or "Ctrl + left click"), but cannot "Go To Implementation" at all

## Expected  behavior

I expect that when we are at a definition, that when you use "Ctrl + F12" (or, ideally, "Ctrl+left click" again) that you go to the implementation (or show all places where it is implemented)

## Steps to reproduce:
Create a new python file and use the following code:
```python
class TestClass:

    def run_this(self):
        self.try_and_click_through()

    def try_and_click_through(self):
        print('Does this work?')


def test_functions():
    does_this_work()


def does_this_work():
    print('How about this?')
```

If I try "Go To Definition" on either `self.try_and_click_through()` or `does_this_work()`, it takes me to the definition. However, once I am at the definition, I cannot "Go To Implementation". I have tried both using the "Ctrl + F12" as well as manually trying to do it. I know you can use "Find All References" to do something similar, but it's not the same. 

I think ideally this would work with a "Ctrl + right click", like "Go To Definition" but in reverse, if you are already at the definition.

## Logs
- Output for `Python` in the `Output` panel (`View`→`Output`, change the drop-down the upper-right of the `Output` panel to `Python`)

Nothing other than my linting & type checking   

- Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

Also nothing that I can see from just trying to do the "Go To Implementation"

---
Originally created in the VS Code repo. Xref: https://github.com/Microsoft/vscode/issues/59434

**Comment by jakebailey** [comment]
This is #611.

**Comment by jakebailey** [comment]
Err, sorry, #1200.
