### ISSUE TITLE
Can I configure whether to block certain files when set "python.analysis.diagnosticMode" to workspace 

### ISSUE THREAD

**Issue by taicaile** [microsoft/pylance-release#186]
Can I configure whether to not check certain files when set ```python.analysis.diagnosticMode``` to ```workspace```?

Thanks.

**Comment by erictraut** [comment]
You can create a "pyrightconfig.json" file at the workspace level and specify which folders or files you want Pylance/Pyright to analyze by specifying them in the "include" and "exclude" arrays. See [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md) for more details and an example config file.

**Comment by taicaile** [comment]
Thanks, I got it.
