### ISSUE TITLE
Custom syntax highlighting

### ISSUE THREAD

**Issue by SilverSCode** [microsoft/pylance-release#1865]
How do I customize syntax highlighting?
For example, I wanted Pylance to highlight a particular variable

**Comment by CodeCrazy-ywt** [comment]
For example?

**Comment by SilverSCode** [comment]
> 具体例子？

Suppose I add an alias for a token in the Python interpreter
![tmp01](https://user-images.githubusercontent.com/46935947/134544143-d7f99491-b3bc-4ee0-9b18-b2325bd9c292.png)

I wanted Pylance to syntactically highlight it like this
![tmp02](https://user-images.githubusercontent.com/46935947/134544520-45fc2733-a5f2-4dca-96f1-4d40dfbf3dcb.png)

**Comment by SilverSCode** [comment]
> 具体例子？

The effect in the second image was achieved by configuring the Jedi
But I don't know how to implement similar modifications in Pylance

**Comment by jakebailey** [comment]
What is an "alias for a token"?

**Comment by SilverSCode** [comment]
> What is an "alias for a token"?

I just wanted to use Pylance to provide syntax highlighting for my custom Python syntax

**Comment by jakebailey** [comment]
I see. I don't think we're going to add support for modified versions of Python like this, sorry.
