### ISSUE TITLE
Cannot access member ... when using Flask-SQLAlchemy

### ISSUE THREAD

**Issue by JakubBlaha** [microsoft/pylance-release#187]
## Environment data

-   Language Server version: 2020.7.4
-   OS and version: Windows 10, version 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8, python.org, pipenv

## Expected behaviour

Pylance correctly determines the type and does not throw an error when on the following code.

```python
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class ExampleModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
```

## Actual behaviour

Pylance throws the following kind of error on multiple `db` attributes.
```python
Cannot access member "Column" for type "SQLAlchemy"
  Member "Column" is unknownPylance (reportGeneralTypeIssues)
```
![image](https://user-images.githubusercontent.com/28687156/88921269-84889300-d26e-11ea-905f-683d15fdd82f.png)

## Logs

```
[Info  - 2:16:19 PM] Pylance language server 2020.7.4 (pyright a65343ef) starting
[Info  - 2:16:19 PM] Server root directory: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server
[Info  - 2:16:19 PM] No configuration file found.
[Info  - 2:16:19 PM] Setting pythonPath for service "Options-Pannel": "C:\Users\jakub\.virtualenvs\Options-Pannel-6T8U9D47\Scripts\python.exe"
[Error - 2:16:19 PM] stubPath d:\Options-Pannel\typings is not a valid directory.
[Info  - 2:16:19 PM] Assuming Python version 3.8
[Info  - 2:16:19 PM] Assuming Python platform Windows
[Info  - 2:16:19 PM] Searching for source files
[Info  - 2:16:19 PM] Found 8 source files
[Info  - 2:16:19 PM] Background analysis root directory: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server
[Info  - 2:16:19 PM] Background analysis started
[BG] analyzing: d:\Options-Pannel\options_pannel\test.py ...
[BG]   parsing: d:\Options-Pannel\options_pannel\test.py (106ms)
[BG]   parsing: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server\typeshed-fallback\stdlib\2and3\builtins.pyi (125ms)
[BG]   binding: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server\typeshed-fallback\stdlib\2and3\builtins.pyi (54ms)
[BG]   binding: d:\Options-Pannel\options_pannel\test.py (0ms)
[BG]   checking: d:\Options-Pannel\options_pannel\test.py ...
[BG]     parsing: C:\Users\jakub\.virtualenvs\Options-Pannel-6T8U9D47\lib\site-packages\flask_sqlalchemy-stubs\__init__.pyi (23ms)
[BG]     binding: C:\Users\jakub\.virtualenvs\Options-Pannel-6T8U9D47\lib\site-packages\flask_sqlalchemy-stubs\__init__.pyi (4ms)
[BG]     parsing: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server\typeshed-fallback\stdlib\3\typing.pyi (36ms)
[BG]     binding: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server\typeshed-fallback\stdlib\3\typing.pyi (14ms)
[BG]   checking: d:\Options-Pannel\options_pannel\test.py (95ms)
[BG] analyzing: d:\Options-Pannel\options_pannel\test.py (381ms)
[FG] parsing: d:\Options-Pannel\options_pannel\test.py (20ms)
[FG] parsing: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server\typeshed-fallback\stdlib\2and3\builtins.pyi (126ms)
[FG] binding: c:\Users\jakub\.vscode\extensions\ms-python.vscode-pylance-2020.7.4\server\typeshed-fallback\stdlib\2and3\builtins.pyi (53ms)
[FG] binding: d:\Options-Pannel\options_pannel\test.py (1ms)

```

`Pipfile`
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"
timeloop = "*"
validators = "*"
bs4 = "*"
requests = "*"
safe-cast = "*"
apscheduler = "*"
pandas = "*"
flask-cors = "*"
flask-sqlalchemy = "*"

[requires]
python_version = "3.8"
```

**Comment by jakebailey** [comment]
This library is doing something very dynamic: https://github.com/pallets/flask-sqlalchemy/blob/a91b33852efec04aacf2db48213dc83bd0415632/src/flask_sqlalchemy/__init__.py#L66

It's build its `SQLAlchemy` class by defining a new class, then manually copying attributes from the "real" SQLAlchemy over. I'm not sure that we could statically analyze this. I would wonder why they aren't using a parent class to add more behavior.

As-is, I think this is going to need a stub to define that the `SQLAlchemy` class has those extra members.

You're seeing these messages because you have a type checking mode above `off`. You could `# type: ignore` to ignore the messages, but it'd be best for this library to be properly typed.

**Comment by JakubBlaha** [comment]
I have found this library.
https://github.com/ryanwang520/flask_sqlalchemy-stubs
Is there a way to include this in Pylance manually while there is no official support yet?

I know about `# type: ignore`, but I feel like writing that on each line when having about five models in my database isn't that effective. It would be useful if we could apply `# type: ignore` to a whole module.

**Comment by jakebailey** [comment]
That project is unlicensed, so I doubt we could include them. If you want to make use of them yourself, you can make a folder `typings` in your project and place them there to see if that helps. Pylance/pyright will look in this folder by default to find extra type stubs you have written or added.

**Comment by Sebschock** [comment]
@JakubBlaha did you find a solution?

**Comment by JakubBlaha** [comment]
@Sebschock I ended up creating my won typing stubs and later I moved on to MongoDB.

**Comment by WilsonPhooYK** [comment]
Hi,

Just sharing my approach in dealing with this. It will only assist intellisense on the missing methods available but not the declarations.

```
from typing import Any
from flask_sqlalchemy import SQLAlchemy as SQLAlchemyBase, Model as ModelBase

class QueryModel:
    add_column: Any = ...
    add_columns: Any = ...
    add_entity: Any = ...
    all: Any = ...
    apply_labels: Any = ...
    as_scalar: Any = ...
    autoflush: Any = ...
    correlate: Any = ...
    count: Any = ...
    ...

class SQLAlchemy(SQLAlchemyBase):
    class Model(ModelBase):
        query: QueryModel
        
    Column: Any = ...
    ForeignKey: Any = ...
    relationship: Any = ...
    backref: Any = ...
    
    BigInteger: Any = ...
    Boolean: Any = ...
    Date: Any = ...
    DateTime: Any = ...
    Enum: Any = ...
    ...
```

I created a definition class in `typings/sql_alchemy` with all the dynamic typings of the methods that are created only when the SQLAlchemy object is created and inherited everything that it already has by default.

After which I use it like this in db.py:
```
from typing import cast
from flask_sqlalchemy import SQLAlchemy
from typings.sql_alchemy import SQLAlchemy as SQLAlchemyStub

db:SQLAlchemyStub = cast(SQLAlchemyStub, SQLAlchemy())
```

Inheriting the Model class:
```
Model = db.Model

class SomeModel(Model):
    __tablename__ = 'tablename'

    # Now these no longer show linting errors
    id: int = db.Column(db.Integer, primary_key=True)
    name: str = db.Column(db.String(80))
    ...
```

**Comment by obrua** [comment]
> Hi,
> 
> Just sharing my approach in dealing with this. It will only assist intellisense on the missing methods available but not the declarations.
> 
> ```
> from typing import Any
> from flask_sqlalchemy import SQLAlchemy as SQLAlchemyBase, Model as ModelBase
> 
> class QueryModel:
>     add_column: Any = ...
>     add_columns: Any = ...
>     add_entity: Any = ...
>     all: Any = ...
>     apply_labels: Any = ...
>     as_scalar: Any = ...
>     autoflush: Any = ...
>     correlate: Any = ...
>     count: Any = ...
>     ...
> 
> class SQLAlchemy(SQLAlchemyBase):
>     class Model(ModelBase):
>         query: QueryModel
>         
>     Column: Any = ...
>     ForeignKey: Any = ...
>     relationship: Any = ...
>     backref: Any = ...
>     
>     BigInteger: Any = ...
>     Boolean: Any = ...
>     Date: Any = ...
>     DateTime: Any = ...
>     Enum: Any = ...
>     ...
> ```
> 
> I created a definition class in `typings/sql_alchemy` with all the dynamic typings of the methods that are created only when the SQLAlchemy object is created and inherited everything that it already has by default.
> 
> After which I use it like this in db.py:
> 
> ```
> from typing import cast
> from flask_sqlalchemy import SQLAlchemy
> from typings.sql_alchemy import SQLAlchemy as SQLAlchemyStub
> 
> db:SQLAlchemyStub = cast(SQLAlchemyStub, SQLAlchemy())
> ```
> 
> Inheriting the Model class:
> 
> ```
> Model = db.Model
> 
> class SomeModel(Model):
>     __tablename__ = 'tablename'
> 
>     # Now these no longer show linting errors
>     id: int = db.Column(db.Integer, primary_key=True)
>     name: str = db.Column(db.String(80))
>     ...
> ```

Too great, I need this urgently!
Can I build a project to open source this part?

**Comment by WilsonPhooYK** [comment]
> > Hi,
> > Just sharing my approach in dealing with this. It will only assist intellisense on the missing methods available but not the declarations.
> > ```
> > from typing import Any
> > from flask_sqlalchemy import SQLAlchemy as SQLAlchemyBase, Model as ModelBase
> > 
> > class QueryModel:
> >     add_column: Any = ...
> >     add_columns: Any = ...
> >     add_entity: Any = ...
> >     all: Any = ...
> >     apply_labels: Any = ...
> >     as_scalar: Any = ...
> >     autoflush: Any = ...
> >     correlate: Any = ...
> >     count: Any = ...
> >     ...
> > 
> > class SQLAlchemy(SQLAlchemyBase):
> >     class Model(ModelBase):
> >         query: QueryModel
> >         
> >     Column: Any = ...
> >     ForeignKey: Any = ...
> >     relationship: Any = ...
> >     backref: Any = ...
> >     
> >     BigInteger: Any = ...
> >     Boolean: Any = ...
> >     Date: Any = ...
> >     DateTime: Any = ...
> >     Enum: Any = ...
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I created a definition class in `typings/sql_alchemy` with all the dynamic typings of the methods that are created only when the SQLAlchemy object is created and inherited everything that it already has by default.
> > After which I use it like this in db.py:
> > ```
> > from typing import cast
> > from flask_sqlalchemy import SQLAlchemy
> > from typings.sql_alchemy import SQLAlchemy as SQLAlchemyStub
> > 
> > db:SQLAlchemyStub = cast(SQLAlchemyStub, SQLAlchemy())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Inheriting the Model class:
> > ```
> > Model = db.Model
> > 
> > class SomeModel(Model):
> >     __tablename__ = 'tablename'
> > 
> >     # Now these no longer show linting errors
> >     id: int = db.Column(db.Integer, primary_key=True)
> >     name: str = db.Column(db.String(80))
> >     ...
> > ```
> 
> Too great, I need this urgently!
> Can I build a project to open source this part?

Go ahead! You can grab the latest version here instead. Its more extensive.
[Type hints for SQLAlchemy and psycopg2](https://github.com/WilsonPhooYK/udemy-automated-software-testing-python/tree/main/section6_7/typings)

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
