### ISSUE TITLE
Unable to determine variable type on `yield` line in a loop

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#1871]
## Environment data

-   Language Server version: v2021.9.4-pre.1
-   OS and version: Windows 7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.11 Anaconda

## Sample code

```python
def f():
    a = b = 0 + 1
    while True:
        a += 1
        yield a, b
        _ = a
```

## Expected behavior

`a` always gets inferred as `int`.

## Actual behavior

`a` gets inferred as `Unknown` on the yield line but `int` elsewhere, while `b` always gets inferred as `int`.

![image](https://user-images.githubusercontent.com/15389744/134665322-11455535-49c1-4ae4-a6b6-e0ca767c8a9b.png)
![image](https://user-images.githubusercontent.com/15389744/134665294-1cbe2e11-9da8-448f-95e4-f761a0a0405a.png)
![image](https://user-images.githubusercontent.com/15389744/134665354-de8a6b6f-a652-4877-ac43-8447eafe9f7e.png)
![image](https://user-images.githubusercontent.com/15389744/134665408-27016c59-083d-4778-af90-6f16aa4b0100.png)

**Comment by erictraut** [comment]
Thanks for the bug report. I'm able to repro it, and I'll take a look.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by Azureblade3808** [comment]
@erictraut This issue is missing a "fixed" label and needs to be closed.

**Comment by erictraut** [comment]
Thanks for catching that.
