### ISSUE TITLE
Error type report for `inspect.Parameter.empty`

### ISSUE THREAD

**Issue by yanyongyu** [microsoft/pylance-release#1872]
<h3> Environment data </h3>

-   Language Server version: 2021.9.3
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

No issue should be reported

<h3> Actual behaviour </h3>

`inspect.Parameter.empty` is reported as type `_empty` instead of `Type[_empty]`

<h3> Code Snippet / Additional information </h3>

```python
inspect.Parameter.empty
inspect._empty
```

![image](https://user-images.githubusercontent.com/42488585/134665813-f6a70806-82d6-44ab-bc6a-16698ab79a5e.png)

![image](https://user-images.githubusercontent.com/42488585/134665832-65f5bf1c-a098-49f2-8af9-ca0388abc392.png)

![image](https://user-images.githubusercontent.com/42488585/134666015-61b7a6b0-721e-4ef1-8388-71453f0c0cce.png)

![image](https://user-images.githubusercontent.com/42488585/134666057-785363de-8c3f-4a14-acb9-a62430b77d55.png)

![image](https://user-images.githubusercontent.com/42488585/134665905-877143b7-d64c-43d5-ada7-bc8f2382cb88.png)

**Comment by yanyongyu** [comment]
this seems to be the `typeshed` problem. changed in https://github.com/python/typeshed/pull/6020

**Comment by erictraut** [comment]
It looks like this was fixed in typeshed 6 days ago. It will be fixed in pylance the next time we merge the latest typeshed changes.

**Comment by yanyongyu** [comment]
Thanks for answering.

This problem is caused by that pull request merged 6 days ago and i have just opened an issue in typeshed repo.

I hope this can be solved and merge into pylance!

**Comment by erictraut** [comment]
Great! I just pulled the latest version of the typeshed stubs into the pyright repo, so this will appear in the next release of pyright & pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.4, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202194-29-september-2021
