### ISSUE TITLE
"bool" is not defined

### ISSUE THREAD

**Issue by fristhon** [microsoft/pylance-release#1876]
## Environment data

-   Language Server version: Pylance language server 2021.9.3 (pyright d2771b18)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7

## Expected behaviour

bool is a built-in function !

## Actual behaviour

"bool" is not defined PylancereportUndefinedVariable

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/30555691/134881541-36d2d6ea-9526-44fc-9a29-c435845ba8c6.png)

**Comment by jakebailey** [comment]
It seems like your extension is corrupted somehow; we should be finding `bool`. Can you try uninstalling Pylance, then deleting it from your extension folder, then reinstall it? Quick access to the folder can be found in the command palette:

![image](https://user-images.githubusercontent.com/5341706/134958440-4d6afb4f-c00e-4dd8-b807-aee5bdae57cb.png)

**Comment by fristhon** [comment]
This problem appeared suddenly after the last update. I thought this is a bug.
Uninstalling the extension and reinstalling it solved the problem.(also extension folder)
Thank you
