### ISSUE TITLE
Could you stop obfuscating your JavaScript code during deployment? 

### ISSUE THREAD

**Issue by Neo23x0** [microsoft/pylance-release#1882]
The JavaScript code that I find in my extensions folder (e.g. `/.vscode/extensions/ms-python.vscode-pylance-2021.9.1/dist/extension.bundle.js`) is obfuscated. 
Could you explain how and why this happens? 

![Screenshot 2021-09-28 at 12 03 31](https://user-images.githubusercontent.com/2851492/135066996-c1f38193-e24a-4491-bb5a-244c01e1d11c.png)

This causes problems since Antivirus engines and my detection rules report this obfuscated JavaScript code as suspicious and flag the files, which is an undesired behaviour.

**Comment by judej** [comment]
Thanks for the report, which AV are you using?

**Comment by judej** [comment]
closing stale issue
