### ISSUE TITLE
Question: Why some annotations in stubs are different from the inline type annotations of the original packages?

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#1885]
Some annotations in [python type stubs](https://github.com/microsoft/python-type-stubs#python-type-stubs) used by VSCode are a little different from the inline type annotations of the original packages.

### Example:
___
The original `matplotlib.pyplot.plot` function has the following inline type annotation in its signature:
```
def plot(*args, scalex=True, scaley=True, data=None, **kwargs):
```
___
But the stub file `pyplot.pyi` (used by Pylance) has the following signature, with type annotations, for the same function.
```
def plot(*args: Any, scalex: bool = ..., scaley: bool = ..., data: Optional[Any] = ..., **kwargs: Any) -> List[Line2D]: ...
```
___
The last expression above is used by VS Code in autocompletions.

Some noted differences improves the usability, like the returned type `List[Line2D]`, not present in the original.

But some of then seems not be right, like the default values of `scalex` and `scaley` which are `True` in the original, and not defined in the stub. I would like to know why is that.

Also, I would like to take this opportunity to ask: what means the `Ellipsis` `...` in default values of python functions?
The original [PEP documentation](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values) does not made it clear.

I apologize if this is not the right place to ask these questions. I couldn't find a more suitable.

**Comment by erictraut** [comment]
The matplotlib sources don't contain any type annotations. Consider the function `def plot(*args, scalex=True, scaley=True, data=None, **kwargs):`. None of the parameters have declared types, and there is no return type annotation specified. The type stub provides types for each of the parameters and supplies a return type.

In stubs, the ellipsis is intended to indicate "some value". From the perspective of a type checker, the actual value of the default value isn't important.

To quote PEP 484:

>In stubs it may be useful to declare an argument as having a default without specifying the actual default value. For example:
```python
def foo(x: AnyStr, y: AnyStr = ...) -> AnyStr: ...
```
>What should the default value look like? Any of the options "", b"" or None fails to satisfy the type constraint. In such cases the default value may be specified as a literal ellipsis, i.e. the above example is literally what you would write.

Most type stubs follow the convention spelled out in PEP 484. From the perspective of a type checker, this makes sense. However, type stubs are now used in ways that were not contemplated by the original authors of PEP 484. Namely, they're used for completion suggestions and tooltips during editing. From this perspective, it's useful to retain the default argument value in the signature. We've been advocating that providers of type stubs include these default argument values.

[This documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) provides guidance to library authors. It says:

>In many existing type stubs (such as those found in typeshed), default parameter values are replaced with with “...” and all docstrings are removed. We recommend that default values and docstrings remain within the type stub file so language servers can display this information to developers.

Most existing type stubs don't follow this guidance today. It will take time.

**Comment by Diogo-Rossi** [comment]
Thankyou very much for the quick reply @erictraut.

Sorry, I've understand it wrong: there are really no type annotation in that original example.

I was concerned about the function signature with default values, not followed entirely in the stub, which you explained perfectly.

Thankyou.

**Comment by jakebailey** [comment]
Unless I'm mistaken, this is a question issue that's been answered; this is just how stubs are.
