### ISSUE TITLE
list comprehension variable not defined

### ISSUE THREAD

**Issue by skyslide22** [microsoft/pylance-release#189]
## Environment data

-   Language Server version: v2020.7.4
-   OS and version: Win10Home
-   Python version 3.8.1

## Expected behaviour

"obj" is not definedPylance (reportUndefinedVariable)
the obj in obj.users_collection is undefined but it is defined at the end...
_works fine with microsoft language server, but that loops randomly on (analyzing 7 items in background) and kills it._

## Code Snippet / Additional information

```python
def getCollectionNamesFromVisibleObjs() -> list:
    """returns list of collection names of all visible objects in the scene"""
    objs = bpy.context.scene.objects
    return [col.name for col in obj.users_collection for obj in objs]

```

**Comment by erictraut** [comment]
I think Pylance is doing the right thing here. 

Here's a simplified version of the code above:
```
a = [[1], [2]]
print([c for c in b for b in a])
```

If I run this, the Python interpreter generates an exception "NameError: name 'b' is not defined". This is consistent with the error Pylance is reporting.

I suspect that the behavior you're looking for requires parentheses, as follows:
```
print([c for c in (b for b in a)])
```
When I run this, no exception is raised, and it prints "[[1], [2]]". Pylance reports no error in this case.

**Comment by judej** [comment]
As Eric mentioned, this is expected behaviour
