### ISSUE TITLE
Import Missing autoslug 

### ISSUE THREAD

**Issue by ahmedsharifkhan** [microsoft/pylance-release#1891]
# I have installed  Auto SlugField library(version: django-autoslug 1.9.8)  in my app but when I tryto Import in my models.py file it is show me an error like Import "autoslug" could not be resolved
## What to do ?
![Screenshot 2021-10-01 014852](https://user-images.githubusercontent.com/65096534/135520947-679f288f-eb4e-4a88-a1e6-daedb68af67e.png)

**Comment by jakebailey** [comment]
Pylance uses the interpreter selected at the bottom left. Can you confirm that your selected interpreter is the one you installed the package into?

**Comment by jakebailey** [comment]
@akseart Your issue is unrelated, and is https://github.com/microsoft/vscode-jupyter/issues/6333 which is currently being fixed. You may want to try the insiders builds of Jupyter and Python.

**Comment by judej** [comment]
closing stale issue

**Comment by Sajeyks** [comment]
Facing same issue
