### ISSUE TITLE
Pylance doesn't recognize properties of a Generic class with a ParamSpec as one of the generic types

### ISSUE THREAD

**Issue by StockerMC** [microsoft/pylance-release#1892]
Pyright correctly recognizes the property, while pylance doesn't. This is not the case for attributes or methods.

## Environment data

-   Language Server version: v2021.9.4
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Code Snippet
```python
from __future__ import annotations

from typing import Generic, TypeVar

from typing_extensions import ParamSpec

T = TypeVar('T')
T_ = TypeVar('T_')
P = ParamSpec('P')

class Command(Generic[P, T]):
    @property
    def qualified_name(self) -> str: ...

def foo(command: Command):
    reveal_type(command.qualified_name) # Cannot access member "qualified_name" for type "Command[Unknown, Unknown]"

class Command2(Generic[T, T_]):
    @property
    def qualified_name(self) -> str: ...

def bar(command: Command2):
    reveal_type(command.qualified_name) # str
```

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release.

The type checker wasn't properly handling the case where an "Any" type argument was assigned the a ParamSpec. Because it rejected this case, the operation failed when attempting to bind the `__get__` method on the property object.
