### ISSUE TITLE
Method Obscured Issue for user-defined-`property`-like decorator

### ISSUE THREAD

**Issue by junkmd** [microsoft/pylance-release#1893]
## Environment data

-   Language Server version: 2021.9.4 (pyright 5b7bce0e)
-   OS and version: Windows 10 Home
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.4

## Expected behaviour

no complaint

## Actual behaviour

complains: `Method declaration "METHODNAME" is obscured by a declaration of the same name`

## Code Snippet / Additional information

```python
class MyProperty:
    def __init__(self, fget=None, fset=None):
        self.fget = fget
        self.fset = fset

    def __get__(self, obj, objtype=None):
        if obj is None:
            return self
        if self.fget is None:
            raise AttributeError("unreadable attribute")
        return self.fget(obj)

    def __set__(self, obj, value):
        if self.fset is None:
            raise AttributeError("can't set attribute")
        self.fset(obj, value)

    def setter(self, fset):
        return type(self)(self.fget, fset)

    @classmethod
    def another_init(cls, fget):
        return cls(fget)

    def do_special_thing(self):
        ...


class Foo:
    @MyProperty
    def foo(self) -> str:  # <- HERE!
        return self._foo

    @foo.setter
    def foo(self, a: str) -> None:
        self._foo = a

    @MyProperty.another_init
    def bar(self) -> int:  # <- HERE!
        return self._bar

    @bar.setter
    def bar(self, a: int) -> None:
        self._bar = a
```
It disappears when changing the name of `@setter` decorated method.
But I want to use this decorator same as builtin `property`.
Or is it correct behavior?

## similars to
#1683: case of builtin `property` and `ABC`.

**Comment by erictraut** [comment]
Pylance special-cases the builtin `property` class (and subclasses thereof) to avoid this diagnostic, but it doesn't know about other custom property-like descriptor classes.

Mypy (another popular type checker) emits the same error on this condition.

Is it feasible for you to use the builtin `property` or have `MyProperty` subclass from `property`?

If that's not feasible, then you can manually suppress this diagnostic by adding `# type: ignore` comments.

**Comment by junkmd** [comment]
@erictraut 

Thank you for your response.

Following your advices,

1. In my project, subclassing from builtin `property` to implement property-like decorator.

2. Making type stub for third party package, 
adding `# type: ignore` comment.
