### ISSUE TITLE
Third party libraries Symbol in Workspaces

### ISSUE THREAD

**Issue by tamutamu** [microsoft/pylance-release#1894]
## Environment
  - Language Server version: 2021.9.4
## Expected
  - `Go to Symbol in workspace`(Ctrl + T) command suggest a symbol containing a third party libraries(ex: site-packages).
## Actual
  - `Go to Symbol in workspace`(Ctrl + T) command suggest a symbol without a third party libraries.

Is there way to suggest a symbol that contains a third party libraries.

**Comment by jakebailey** [comment]
Duplicate of #35.
