### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Ajesh0** [microsoft/pylance-release#1896]
i have a error shown
\\from catalog.forms import RenewBookForm
ModuleNotFoundError: No module named 'catalog.forms''\\
here i want to import RenewBookForm from forms.py file that is stored in the the catalog folder i'm getting this error why?

**Comment by Nusab19** [comment]
I got a missing module error.

I tried to import matplotlib.pyplot in my code. But it showed me this error -

Traceback (most recent call last):
  File "c:\Users\osama\OneDrive\Documents\Projects\Auto Email Sending Bot\more.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'


So, I'll be glad if you guys fix this.
![image](https://user-images.githubusercontent.com/85403795/135724307-48fcef38-ac7d-4ad3-ac4e-01c8425ed7e6.png)

**Comment by CodeCrazy-ywt** [comment]
Screenshot?

**Comment by erictraut** [comment]
This sounds like a runtime error coming from the Python interpreter, not an error being reported by pylance.

If you think this is a bug in pylance, please fill out the issue template with the requested information.

**Comment by jakebailey** [comment]
Closing, as this is a runtime error. I would recommend using a forum like StackOverflow or similar to get help on solving runtime errors.
