### ISSUE TITLE
pylance can not recognize some Qt Types with PyQt5.

### ISSUE THREAD

**Issue by jibintao** [microsoft/pylance-release#1897]
## Environment data

-   Language Server version: PyLance v2021.9.4
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5 

## Expected behaviour

There are many types can not be recognized by PyLance, such as Qt.Checked, QEvent.WindowStateChange, Qt.WindowMaximized, Qt.WindowNoState

## Actual behaviour

when these type are called , there will be show error. QEvent.WindowStateChange, Qt.WindowMaximized, Qt.WindowNoState

## Logs

```
XXX
```

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/6461952/135761705-7e8ecc34-8934-490f-9e48-338d6e53c5a1.png)

![image](https://user-images.githubusercontent.com/6461952/135761730-1332a11d-1d87-4f65-ac53-32bd7ff3fa35.png)

```python

Michael Ji (michael.ji@wcs-sh.com)
```

**Comment by heejaechang** [comment]
most of Qt modules are compiled modules and PyQt5 ships with pyi file to provide type info but ones the user is looking for is missing in the pyi files. it must be fixed by PyQt5 package owner.

**Comment by heejaechang** [comment]
@jibintao you need to contact PyQt5 for those missing symbols and ask them to add them to pyi files that ships with the package.
