### ISSUE TITLE
Import "wikipedia" could not be resolvedPylancereportMissingImports

### ISSUE THREAD

**Issue by Rajesh01B** [microsoft/pylance-release#1899]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
I'm going to close this as the template is completely empty; there's not much we can do without any info.

You should check out our troubleshooting page for unresolved imports here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings

It sounds like you haven't selected the right interpreter.

If you can complete the template, we can reopen this.
