### ISSUE TITLE
Issues when `str` is defined as a class variable

### ISSUE THREAD

**Issue by max-sixty** [microsoft/pylance-release#19]
## Environment data

- Language Server version: 2020.6.1 
- OS and version: MacOS
- Python version (& distribution if applicable, e.g. Anaconda): Python3.7

@jakebailey asked me to open a new issue here. As discussed in https://github.com/microsoft/pylance-release/issues/15#issuecomment-652608230, and https://github.com/microsoft/python-language-server/issues/1732, this causes > 50 errors in https://github.com/pydata/xarray/blob/v0.15.1/xarray/core/dataarray.py.

The reproduction is there, but copying the essentials here:

It's on this line: https://github.com/pydata/xarray/blob/v0.15.1/xarray/core/dataarray.py#L242
And I suspect caused by this definition of `str`: https://github.com/pydata/xarray/blob/v0.15.1/xarray/core/dataarray.py#L3435 

Please let me know if it would be helpful to produce logs.

Thank you!

**Comment by jakebailey** [comment]
@erictraut 

Maybe I'm misunderstanding the scoping rule, but given `str` is being declared as a class variable, is it not only accessible by say `ClassName.str`?

**Comment by jakebailey** [comment]
I would also suggest trying to do the method described in https://github.com/microsoft/python-language-server/issues/1732#issuecomment-652620364, though, as it would certainly prevent that aliasing.

**Comment by erictraut** [comment]
@jakebaily, if you're within the class, you don't need to use the class name to refer to the class variable. For example, this runs fine and prints "3".
```
class Foo:
    str = 3
    str2 = str
    print(str2)
```

**Comment by jakebailey** [comment]
Ah, that explains a lot. Unfortunate.

**Comment by max-sixty** [comment]
This is fixed with the suggestion in (2): https://github.com/pydata/xarray/commit/5c09276472cc05cc0967a5064f206ddb8247e1ec

It's not super convenient, as a new contributor is going to slip up at some point given mypy currently allows it, so let me reflect on which path we take. And I recognize it's on us for picking `str` as a class variable (I think we were following pandas convention, which was probably from a decade ago...)

Thanks for the engagement and guidance

**Comment by jakebailey** [comment]
Out of curiosity, why update the docstrings to contain the "fake" type? Or are you somehow generating those docs from the type annotations?

**Comment by max-sixty** [comment]
Sorry, that was a regex replace, I won't keep those
