### ISSUE TITLE
Bad Function Annotation String Error Highlighting

### ISSUE THREAD

**Issue by syminical** [microsoft/pylance-release#1900]
## Environment data

-   VS Code version: ***1.60.2***
-   Extension version (available under the Extensions sidebar): ***Python: v2021.9.1246542782, Pylance: v2021.9.4***
-   OS and version: ***Windows 10***
-   Python version (& distribution if applicable, e.g. Anaconda): ***3.9.6***
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): ***N/A***
-   Relevant/affected Python packages and their versions: ***N/A***
-   Relevant/affected Python-related VS Code extensions and their versions: ***Not sure. It's either the Pylance or Python extension.***
-   Value of the `python.languageServer` setting: ***Default***

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

***No error highlighting on closed string function annotations.***

## Actual behaviour

***Incorrect error highlighting present on function annotations (strings). It seems like it's not treating them as strings.***
***The code works, but the highlighting doesn't like it.***
# :thinking:

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

***1. Create a function with string annotations. The weirder the better.***
`def f(i: 'index') -> '("c", [(...),...])':`
***2. Try to ignore the orange / red under-squiggles.***

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
N/A
```

</p>
</details>

**Comment by erictraut** [comment]
I'm not sure what you mean by "string annotations". Do you simply mean "type annotations that are enclosed within a string literal"? Type annotations that are string literals are interpreted as forward-declared types, as explained in PEP 484. As such, a static type checker will parse the contents of the string and report syntax and semantic errors as appropriate.

These are not valid type annotations, so a static type analyzer will reject them, and all bets are off when it comes to semantic highlighting.

If your intent is to provide non-type annotations, you can use the `Annotated` annotation introduced in [PEP 593](https://www.python.org/dev/peps/pep-0593/).

**Comment by jakebailey** [comment]
Yeah, these are not valid type annotations. Type annotations are not for random text, but for PEP 484-specified strings. Yours could be something like `tuple[Literal["c"], list[tuple[Any]]` or something (if I have read it right).

**Comment by syminical** [comment]
Thank you @erictraut, @jakebailey !

This goes deeper than I thought. I found [PEP 3107](https://www.python.org/dev/peps/pep-3107) when I was looking into annotations, but it seems they have evolved since then. The functionality I wanted seems to have been replaced with forward-declared types.

I hate the direction they took, but this is just a personal problem now. 🙂
