### ISSUE TITLE
Pylance reports missing arguments for urllib.request examples

### ISSUE THREAD

**Issue by acdha** [microsoft/pylance-release#1901]
## Environment data

-   Language Server version: 2021.9.4
-   OS and version: macOS 11.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Expected behaviour

The examples shown in the Python documentation would work without error

## Actual behaviour

Pylance reports:

Arguments missing for parameters "_p0", "_p1", "_p2", 

This is likely due to the way the stdlib classes are defined with position arguments (https://github.com/python/cpython/blob/f4a7ce70f9e61b8594f0979ae0e5f39868d4ceb2/Lib/urllib/request.py#L837) while keyword arguments are used in the examples:

https://github.com/python/cpython/blob/f4a7ce70f9e61b8594f0979ae0e5f39868d4ceb2/Lib/urllib/request.py#L53

## Code Snippet / Additional information

```python
authinfo = urllib.request.HTTPBasicAuthHandler()
authinfo.add_password(
        realm="Service-now",
        uri=SERVICENOW_BASE_URL,
        user=SERVICENOW_USERNAME,
        passwd=SERVICENOW_PASSWORD,
    )
# Arguments missing for parameters "_p0", "_p1", "_p2", "_p3" Pylance reportGeneralTypeIssues
```

**Comment by erictraut** [comment]
The `add_password` field in `authinfo` is annotated in the typeshed stub as follows:
```python
    add_password: Callable[[str, str | Sequence[str], str, str], None]
```

That means it doesn't accept keyword arguments. You would need to pass the arguments by position instead.

If you think this is a bug in the type stub, please consider opening an issue (or creating a PR) with the [typeshed repo](https://github.com/python/typeshed/blob/47e9788246d2b84c3fc5362e822f25671ac352b0/stdlib/urllib/request.pyi#L146). Pylance (and other Python type checkers) use the type information from typeshed, so any fixes that make their way into that repo will be reflected in pylance in short order.
