### ISSUE TITLE
Both csv and _csv suggested as modules 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#1904]
Issue Type: <b>Bug</b>

**Repro**
1. In a python file, write: `import csv`

**Bug**
I see two suggestions: `csv` and `_csv`:

![Screen Shot 2021-10-05 at 5 09 24 PM](https://user-images.githubusercontent.com/12821956/136120670-3badc6aa-b69b-4586-8221-1f1eaf0fd1e9.png)

I probably want `csv`, but there is not any documentation in the IntelliSense that tells me what the difference is.

It it helpful to show `_csv` in this case? I'm not really sure what it's for?

Extension version: 2021.9.5-pre.1
VS Code version: Code - Insiders 1.61.0-insider (Universal) (71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32, 2021-10-05T01:23:40.704Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.00GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30377800
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
pydsgst2:30361790
vsqsis300:30374797
vsaa593cf:30376535

```

</details>

**Comment by jakebailey** [comment]
Reasonably, we could deprioritize `_` prefixed modules (as they are usually private), but when there are only two options, that wouldn't appear differently.

I don't know that we show docs for unimported modules; that would potentially help in general, though both `csv` and `_csv` have module docs.

**Comment by mjbvz** [comment]
Can the intellisense document these? Just showing `csv` and `_csv` without any additional context is not a good experience

**Comment by judej** [comment]
Closing old issue
