### ISSUE TITLE
searching for symbols is excruciatingly slow 

### ISSUE THREAD

**Issue by Zacharias030** [microsoft/pylance-release#1906]
Hi guys,
I am trying to avoid switching to software such as pycharm professional, but searching for symbols is really very slow in vscode and often unreliable as if the parsed skeletons are often "lost".

I suppose this depends on the python language server `pylance` and not on vscode itself (full text search via the sidebar's search functionality is blazingly fast).

I'm using the current vscode with pylance and a conda-installed python 3.8 on macos BigSur on a recent macbook pro and have a medium sized repository of a couple of MB of code open.
My impression is that this issue is very general and was always so no matter which of the just mentioned environment details were changed.

**Comment by jakebailey** [comment]
Can you try setting `"python.analysis.indexing": true` to see if this improves your search speed?

**Comment by jakebailey** [comment]
It's a hidden setting; you can ignore VS Code's comment on whether or not it exists.

Those two settings are for our old, deprecated language server and won't have any effect on Pylance.

**Comment by judej** [comment]
@Zacharias030, presume the fix resolved the issue. If not, please reopen this issue
