### ISSUE TITLE
`asyncio.gather` bad type information (pyright)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/pylance-release#1913]
Issue Type: <b>Bug</b>

`asyncio.gather` is seen as returning `Tuple[]`, but in reality returns `List[]`. This results in errors on type-checking.

**To Reproduce**

Open the script below in Visual Studio Code, with Pylance extension installed, and with setting `    "python.analysis.typeCheckingMode": "basic"` (or more aggressive).

**Expected**

Pylance (pyright) does flag errors on `main1()`.
Pylance (pyright) does not flag any errors on `main2()`.

**Actual**

Pylance (pyright) does not flag errors on `main1()`.
Pylance (pyright) does flag errors on `main2()`.

Basically, the type-checker sees `asyncio.gather()` return `Tuple[]` where-as, in fact, it returns `List[]`. The code further down demonstrates that `asyncio.gather()` indeed returns `List[]`

Compare the results obtained also against `mypy`, which works correctly:

![image](https://user-images.githubusercontent.com/3868036/136424706-57757490-5c24-4a99-9cbb-4a431a45ce6d.png)

Alas, I cannot tell at which level things are wrong; my understanding is that pyright/pylance and mypy share the same type information, so I am surprised to see this behaviour.

This is with a virtual environment on Windows, Python 3.9.7 from the Windows Store.

```python
import asyncio
import sys

async def doit(id) -> bool:
    return True

async def main0():
    ret = await asyncio.gather(*[ doit(id) for id in range(1) ])
    return ret

async def main1() -> tuple[bool]:
    ret: tuple[bool] = await asyncio.gather(*[ doit(id) for id in range(1) ])
    return ret

async def main2() -> list[bool]:
    ret: list[bool] = await asyncio.gather(*[ doit(id) for id in range(1) ])
    return ret

x0 = asyncio.run(main0())
x1: tuple[bool] = asyncio.run(main1())
x2: list[bool] = asyncio.run(main2())

if "list" == type(x0).__name__ == type(x1).__name__ == type(x2).__name__:
    print("all lists - good")
    sys.exit(0)
else:
    print("ehh?")
    sys.exit(1)
```

Extension version: 2021.10.0
VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.66GB (45.31GB free)|
|Process Argv|--crash-reporter-id 5ddcd13a-5853-4d88-9c59-31e3be66729a|
|Screen Reader|no|
|VM|44%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by srittau** [comment]
This is a tradeoff chosen by the typeshed project that pyright uses for type information. The [source code of the type hints](https://github.com/python/typeshed/blob/3c58736d01b4befa4499e481e87bd7e8458dac20/stdlib/asyncio/tasks.pyi#L44-L47) has this comment:

```python
# `gather()` actually returns a list with length equal to the number
# of tasks passed; however, Tuple is used similar to the annotation for
# zip() because typing does not support variadic type variables.  See
# typing PR #1550 for discussion.
```

The type system is currently not expressive enough to say: "This returns a list with three elements of the following types: ..." As a workaround, `gather()` is annotated to return a tuple so that the following works:

```python
foo, bar = gather([do_foo(), do_bar()])  # do_foo() returns int, do_bar() returns str
```

See python/typeshed#1550 and python/typing#193 for discussion.

**Comment by jakebailey** [comment]
Given the return type says `Tuple[bool]`, this is probably the thing where when we have no matching overload we arbitrarily pick the first one (which has always felt wrong to me, as it's the most specific overload, versus say the last one or some unioning behavior).

**Comment by erictraut** [comment]
I'll investigate the issue later today. I'm busy at the moment.
