### ISSUE TITLE
pyright faulty diagnostics for `AnyStr = TypeVar('AnyStr', bytes, str)` on generic class (Python os)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/pylance-release#1917]
Issue Type: <b>Bug</b>

Some parts of the Python Standard Library implement functionality in terms of `AnyStr = TypeVar('AnyStr', bytes, str)`. pyright does not seem to correctly attempt to trace into the concrete types specified (e.g. `str`). This results in type errors on simple code.

**To Reproduce**
```python
import os

with os.scandir('anything') as it:
    for file in it:
        if file.is_file() and file.name.endswith('.xml'): ...

reveal_locals()
```

**Expected behavior**

No diagnostics.

**Actual behavior**

Type check error resulting in `Cannot access member "endswith" for type "TypeVar" - Member "endswith" is unknown`, because `TypeVar` does not have such a member.

Root cause: 
```
Type of "os" is "Module("os")"
Type of "it" is "_ScandirIterator[TypeVar]"
Type of "file" is "DirEntry[TypeVar]"
```

From the reveals information, it seems as if, first of all, pyright drops the type constraints (`byte`, `str`); I'd expect those type constraints to be rendered as part of the reveals information.

The difficult part now is in getting the specific type(s) to stick, and offering consistency. 

Given https://docs.python.org/3/library/typing.html#typing.TypeVar, `def scandir(path: AnyStr | PathLike[AnyStr]) -> _ScandirIterator[AnyStr]: ...`, and `os.scandir('anything')` I'd except that the type checker instantiates a concrete type instance of `str` and pushes this down such that the iterator is specialized into `_ScandirIterator[str]` and the entry as `DirEntry[str]`. And this then makes the call `[str].endswith`, which clearly will work fine.

FWIW, mypy does not show any diagnostics in the above source code, but will show an error on

```python
import os
from typing import AnyStr

def thing(value: AnyStr):
    with os.scandir(value) as it:
        for file in it:
            if file.name.endswith('.xml'): ...
```
as it apparently resolves `name` to `[bytes]`.

 

Extension version: 2021.10.0
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.66GB (40.41GB free)|
|Process Argv|--crash-reporter-id 5ddcd13a-5853-4d88-9c59-31e3be66729a|
|Screen Reader|no|
|VM|44%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30358481
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
pydsgst2:30361792
vsqsis200:30374795
vsaa593cf:30376535

```

</details>

**Comment by heejaechang** [comment]
this should be already fixed.
