### ISSUE TITLE
TypedDict completions after first don't appear without quotes

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pylance-release#1920]
@jakebailey Unfortunately, it only works for the first key. After that pylance reports an error (missing key) and no suggestions are offered.

```py
from typing import TypedDict

class PointTD(TypedDict):
    x: int
    y: int

p1: PointTD = {'x': 1, }
```

<img width="438" alt="Screen Shot 2021-10-08 at 21 12 07" src="https://user-images.githubusercontent.com/30130371/136613179-9ab941d3-7b2b-4752-860e-32084a952df1.png">

_Originally posted by @cdce8p in https://github.com/microsoft/pylance-release/issues/654#issuecomment-939060611_

**Comment by erictraut** [comment]
The logic wasn't properly handling the case where there was no quote but there was already at least one dictionary entry. Handling this properly required the parser to provide a bit more information (in particular, the presence of a hanging comma token). I've updated the logic to handle this case.
