### ISSUE TITLE
[Parser] Statements must be separated by newlines or semicolons

### ISSUE THREAD

**Issue by Speak2Erase** [microsoft/pylance-release#1922]
## Environment data
![image](https://user-images.githubusercontent.com/54482069/136639725-f3e79324-2eda-4543-9dfe-977d53b4b709.png)

-   Language Server version: v2021.10.0
-   OS and version: Windows 10 Pro
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9 with a Virtual environment

## Expected behaviour
The "Statements must be separated by newlines or semicolons" error does not show.

## Actual behaviour

The "Statements must be separated by newlines or semicolons" shows.
![image](https://user-images.githubusercontent.com/54482069/136639771-2ae4fddc-aba2-4203-b1ad-174680e77960.png)

## Logs

I get no additional output when putting `"python.analysis.logLevel": "Trace"` in my settings.json. If I had to guess, kivy, the GUI library I am using, is interfering with the output.

## Code Snippet / Additional information

```python
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.uix.dropdown import DropDown
from kivy.uix.spinner import Spinner
from kivy.uix.splitter import Splitter

class RightLayout(Splitter):
    def __init__(self, root, **kwargs):
        super(RightLayout, self).__init__(**kwargs)

        self.root = root

        self.sizable_from = 'left'
        self.min_size = 15
        self.max_size = 270

        self.layout = BoxLayout(orientation = 'vertical')
        self.add_widget(self.layout)
```
Pylance complains that the last line would throw an error regardless of what I do. Adding a semicolon temporarily fixes it, however the error comes back whenever I add a new line. Python does **not** report a syntax error or **any** error whatsoever.

**Comment by erictraut** [comment]
I'm not able to repro the problem with the above code sample.

I wonder if there's a non-printable character (perhaps a result of file corruption) that is present in the file? That's the only hypothesis that I have currently. 

Here's what I suggest. Make a copy of the file to preserve the original contents so we can do further investigation if necessary. Then open the original file and try deleting and retyping the characters after and prior to the `)`. Does the error disappear?

**Comment by Speak2Erase** [comment]
> Here's what I suggest. Make a copy of the file to preserve the original contents so we can do further investigation if necessary. Then open the original file and try deleting and retyping the characters after and prior to the ). Does the error disappear?

Alright, I've made a copy. Retyping everything hasn't fixed anything, the error still persists?

**Comment by erictraut** [comment]
Let's try this. Create a new ".py" file, then copy the sample code above and paste it into the new file. Do you see the problem then?

What is the character encoding of the original file? Is it "UTF-8"? You can find the encoding by looking in the bottom right part of the VS Code window.

![Screen Shot 2021-10-08 at 8 03 38 PM](https://user-images.githubusercontent.com/7040122/136641930-31b97b59-02db-4640-88b9-de845fdda695.png)

**Comment by Speak2Erase** [comment]
> Here's what I suggest. Make a copy of the file to preserve the original contents so we can do further investigation if necessary. Then open the original file and try deleting and retyping the characters after and prior to the ). Does the error disappear?

I don't get the error anymore pasting it in, which is pretty odd?
I double checked and the encoding is UTF-8.
![image](https://user-images.githubusercontent.com/54482069/136642011-42add373-7b89-41ae-8515-a7307c1b6cd4.png)

**Comment by judej** [comment]
If you can provide us a file that repros the problem, we can investigate. Looks like you are unblocked for now. If this is still an issue please reopen this issue.

**Comment by Devourian** [comment]
I have the same error now:
![image](https://github.com/microsoft/pylance-release/assets/96141879/7b2eb432-9778-4f5c-aa92-1e04cfba875d)

**Comment by debonte** [comment]
@Devourian, thanks for reporting this. We had trouble reproducing this issue last time. If you have a file that still shows this issue, could you try replying here and attaching the file (drag the file into your new comment). I'm hoping that that approach (rather than just providing the text of the file in a comment) will allow us to reproduce the issue on our computers.
