### ISSUE TITLE
Does pylance provide the command line tool like mypy?

### ISSUE THREAD

**Issue by evilbrave** [microsoft/pylance-release#193]
Hi all,

 As far as I know, pylance is a new language protocol server. But does it provide the command-line tool like mypy to check type annotation?

Thanks in advance.

**Comment by erictraut** [comment]
Pylance is built on top of [Pyright](https://github.com/microsoft/pyright), an open-source Python type checker. Pyright offers a command-line version, which supports the same configuration options and diagnostics as Pylance. You can use Pylance in your editor and integrate the command-line version of [Pyright into your CI pipeline](https://github.com/microsoft/pyright/blob/master/docs/ci-integration.md).

**Comment by QuintinWillison** [comment]
Noise. Even [Microsoft's own documentation](https://code.visualstudio.com/docs/python/linting#_choose-a-linter) suggests only Pylint, flake8 or mypy. So I can only see Pylance as a distraction. Pyright's "built on Node.js" nature doesn't immediately fill me with any confidence that it's at all Pythonic at heart either. I assume I "accidentally" installed Pylance into VS Code when I grabbed Microsoft's Python extension (I'm very new to Python development, was it parallel installed by the Python extension automatically perhaps?), so will be removing the Pylance extension and probably going with flake8 as I hope it'll give us VS Code integration _and_ sensible CI options (we use GitHub workflows heavily).
