### ISSUE TITLE
No intellisense when from django.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#1931]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/136897714-79c02936-af93-472b-979e-6b97aea7d275.png)
Using TypeScript 4.3 for IntelliSense.

## Repro steps
1. Create Blank Django Web Project 
2. Create virtual environment
3. Right-click BasicProject in SE, select Add > New item > Django 1.9 App, specify the app name "HelloDjango" in the Name field and select OK
4. In the HelloDjango folder, modify views.py to match the code below
![image](https://user-images.githubusercontent.com/59192491/136898389-e1bfdf26-6318-4a95-ae03-0fdab8a8ab6c.png)

## Expected behaviour
From django should be intellisense.

## Actual behaviour
No intellisense when from django.
![image](https://user-images.githubusercontent.com/59192491/136898567-934ee368-e68a-4c3a-b401-81698ffd301f.png)

**Comment by ttSpace** [comment]
In today's build ```17.1.0 Preview 2.0 [32001.270.main]```, The ```HelloDjango``` has no intellisense.

![image](https://user-images.githubusercontent.com/82852072/144367414-4e0ae8bf-fda9-4996-a15f-c7852e9bd644.png)

**Comment by judej** [comment]
Closing stale issue from the preview. Please reopen if this is still a problem
