### ISSUE TITLE
Code after with statement which always returns is always considered unreachable.

### ISSUE THREAD

**Issue by overactor** [microsoft/pylance-release#1945]
## Environment data

-   Language Server version: v2021.10.0
-   OS and version: Ubuntu 20.04.3 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

Since `Foo` suppresses all exceptions when used as a context manager and an exception is raised before the return statement is reached, the print statement after the with statement actually gets executed. It should not be marked as dead code.

## Actual behaviour

The print statement gets marked as unreachable.

## Code Snippet / Additional information

```python
class Foo:
    def __enter__(self):
        pass
    
    def __exit__(self, exc_type, exc_value, stack trace) -> bool:
        return True

def bar():
    with Foo():
        print(1 / 0)
        return
    print('This actually gets printed')

bar()
```

In general, code after a with block should only be marked unreachable because of a statement within the with block if it is known that no exception can be raised before that statement is raised which the context manager might suppress.

Pragmatically, the code after the with block should probably always be considered reachable unless it can be proven no exception can be raised or the dynamic type of the context manager is known and it is known that that type's `__exit__` function never returns `True`. Otherwise, only the remaining code within the with block should be marked unreachable.

**Comment by erictraut** [comment]
Your sample contains a syntax error in the signature for `__exit__`. The third parameter is missing an underscore between `stack` and `trace`. If I add the underscore, it works as expected — the print statement is seen as reachable.

**Comment by overactor** [comment]
> Your sample contains a syntax error in the signature for `__exit__`. The third parameter is missing an underscore between `stack` and `trace`. If I add the underscore, it works as expected — the print statement is seen as reachable.

Sorry about the typo, I did test this without the typo before posting it here and saw this issue. I've updated to v2021.10.1 and I'm still seeing the same issue.

![unreachable code](https://user-images.githubusercontent.com/8274203/137550533-5b4088e4-fadf-417d-ab6f-e375f07ea1d6.png)
![intellisense](https://user-images.githubusercontent.com/8274203/137550541-4ed5448d-167a-4f85-8ca8-c1aebbd04ebc.png)

**Comment by erictraut** [comment]
In your screen shot above, you have not included a return type annotation for the `__exit__` method. By default, type checkers assume that context managers do not catch exceptions. You can override that default assumption by including a `-> bool` return type annotation for `__exit__`, like you did in your original code sample at the top of this thread.

**Comment by overactor** [comment]
That makes a lot of sense, thanks for the explanation. Will your fix also cover the following patterns as well?

```python
def foo() -> Foo:
    return Foo()

with foo():
    pass
```

```python
foo: Foo = Foo()
with foo():
    pass
```

What I'm actually doing in my project is something like

```python
from __future__ import annotations

class Foo:
    def __enter__(self) -> None:
        pass

    def __exit__(self, exc_type, exc_value, traceback) -> bool:
        return True


    def bar(self) -> Foo:
        return self


def baz():
    with Foo().bar():
        print(1 / 0)
        return
    print('This actually gets printed.')


baz()
```
I assume that would be covered by the patterns above, or are these usage patterns more rigid than I'm imagining them?

**Comment by erictraut** [comment]
No, this change won't work with the first usage pattern above. (The second one is invalid because it attempts to call an object). The logic is very rigid because it can't use the general type evaluator; it needs to work directly on the parse tree.

Now that you understand the details, you can change your code to accommodate the known limitations.
