### ISSUE TITLE
Pylance not autocompleting metaclass/init_subclass keyword arguments

### ISSUE THREAD

**Issue by StockerMC** [microsoft/pylance-release#1946]
## Environment data
-   Language Server version: v2021.10.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7

## Expected behaviour
For the keyword arguments defined in `__init_subclass__` and `__new__` to be autocompleted. Due to https://github.com/microsoft/pyright/issues/2436, the metaclass keyword arguments not being suggested may not be a bug.
Instead of the keyword arguments of `__init_subclass__`/`__new__` being suggested, the attributes of the class are suggested.

## Actual behaviour
![image](https://user-images.githubusercontent.com/44980366/137502339-41525e46-834b-4d62-9e10-7e51dd994b8c.png)
![image](https://user-images.githubusercontent.com/44980366/137502358-96dd3546-c211-4cd5-bcb1-a2f098976e43.png)

## Code Snippet / Additional information
```python
from typing import TypeVar, Tuple, Dict, Any, Type, TYPE_CHECKING

CMT = TypeVar('CMT', bound='CommandMeta')

class BaseCommand:
    if TYPE_CHECKING:
        __foo__: int
        __bar__: str

    def __init_subclass__(cls, *, foo: int, bar: str) -> None: ...

class CommandMeta(type):
    if TYPE_CHECKING:
        __foo__: int
        __bar__: str

    def __new__(
        cls: Type[CMT],
        cls_name: str,
        bases: Tuple[type, ...],
        attrs: Dict[str, Any],
        *,
        foo: int,
        bar: str,
    ) -> CMT: ...
```

**Comment by StockerMC** [comment]
Thanks.

**Comment by judej** [comment]
Moving this issue to discussion as an enhancement request for comments and upvotes.
