### ISSUE TITLE
Allow to define per project aliases for Python import paths

### ISSUE THREAD

**Issue by charles-dexter-ward** [microsoft/pylance-release#1948]
We have various project hosted on gitlab.
These applications are deployed inside a common container application with the following structure:

```
base path/www/app1/....
base path/www/app2/...
```
so, each application can import other ones with 

`from www.app2 import app2_module`

But when developing, each application from gitlab is a single project

So in the development folder we have:

```
base devel path/www/app1/src/....
base devel path/www/app2/src/...
```

Now, I have  found no way to instruct the python extension to resolve absolute imports like `from www.app2 import app2_module ` because each project has a src folder which causes the folders structure to differ from the one deployed.

Is there a way to define a per project 'alias', in a way to redefine the 'www' folder with  custom path?

Ie:

for app1 ---> www = base devel path/www/app1/src (or relative, www = ./src)
for app2 ---> www = base devel path/www/app2/src (or relative, www = ./src)

and letting the extension to take into account these aliases when resolving the import paths?

**Comment by jakebailey** [comment]
That's a very unfortunate code layout, as it means that the code that you write is not at all similar to the code that is executed, and there's no configuration knob that could emulate that. I would expect effectively all other tooling (other editors, linters, etc) to fail similarly.

A layout like this is more commonly handled by using [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/), where if you need to split an import namespace into separate projects by module, you have something like:

```
repo1/www/app1/app1_module.py
repo2/www/app2/app2_module.py
```

Or:

```
repo1/src/www/app1/app1_module.py
repo2/src/www/app2/app2_module.py
```

Where both repos are packages that are installed together on the end-user's machine or server and occupy the same tree, in this case, `www`. This is the approach taken by the Azure SDK and some of Google's libraries (protobuf, storage, etc).

**Comment by judej** [comment]
closing old issue.
