### ISSUE TITLE
panda3d has no auto-filled future

### ISSUE THREAD

**Issue by abcdesteve** [microsoft/pylance-release#1951]
## Environment data

-   Language Server version: XXX
-   OS and version: win10,21h1
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.9.6/panda3d 1.10.10

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
![image](https://user-images.githubusercontent.com/72078508/137609010-01399eb5-3423-4f5a-8d4d-c870c84f6077.png)

```

**Comment by CodeCrazy-ywt** [comment]
Logs?

**Comment by judej** [comment]
closing stale issue
