### ISSUE TITLE
PyLance has totally weird/aribtrary color highlighting n Visual Studio (on notebooks)

### ISSUE THREAD

**Issue by fschiffers** [microsoft/pylance-release#1957]
## Environment data

-   Language Server version: PyLance v2021.10.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.8

## Actual Behaviour

![image](https://user-images.githubusercontent.com/13521689/137773005-a1c6f172-33e2-4e57-af59-fdd611dab78f.png)
![image](https://user-images.githubusercontent.com/13521689/137773049-c457dff8-dff9-4037-9b83-83ac632d7908.png)
![image](https://user-images.githubusercontent.com/13521689/137773077-92687387-fb09-4122-821f-11259e826fec.png)

## Expected Behavior (this is without PyLance)
![image](https://user-images.githubusercontent.com/13521689/137773199-9ee8cff2-3fe1-48d8-868c-62e53dc6060c.png)
![image](https://user-images.githubusercontent.com/13521689/137773247-33132d32-75b4-493d-80d6-18c85a6b3a44.png)

## Description
Hi, my colors in the my text editor are totally messed up when turning on PyLance. I never observed this before and I can't remember what I've changed. I see this behavior mostly in Jupyter Notebooks, but it make reading my files almost impossible :(

Does anyone have an idea what could have gone wrong? I'm happy to provide more context, but I have no idea what information I could provide you to resolve this issue.

**Comment by jakebailey** [comment]
This is #1932; there are ongoing issues with notebooks in the browser as they are not handled the same way as Python notebooks are in the desktop.
