### ISSUE TITLE
Auto-import "quick fix" fails unless "Go to Symbol" is used

### ISSUE THREAD

**Issue by andreyfedoseev** [microsoft/pylance-release#1969]
Many time when I enter a non-imported class name I want to auto-import it. To do that I invoke the "Quick Fix..." action but I don't get any suggestions to auto-import that class.

If, however, I use "Go to Symbol" action to search for this class name, and invoke the "Quick Fix..." action immediately after that, I get the auto-import suggestion as expected.

This behavior is inconsistent, sometimes I can do auto-import without any issues, other times I have to do "Go To Sybmol..." first.

It looks like the auto-import feature maintains an index of available modules/symbols in the workspace, and that index has limited capacity so the information gets removed from it over time. And using the "Go To Symbol" action re-populates that index with new info.

## Environment data

-   VS Code version: 1.61.1
-   Extension version (available under the Extensions sidebar): v2021.10.1336267007
-   OS and version: KDE Neon
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Being able to use the "Quick Fix..." action to auto-import things.

## Actual behaviour

The "Quick Fix..." for a non-imported classes shows "No code actions available" message.

## Steps to reproduce:

1. Enter a class name for a non-imported class defined in another module
2. Invoke the "Quick Fix..." action
3. "No code actions available" message is displayed
4. Use the "Go to Symbol in Workspace" action for search the class name (the symbol is found)
5. Invoke the "Quick Fix..." action again
6. The auto-import suggestions are displayed

**Comment by andreyfedoseev** [comment]
> do you have "python.analysis.indexing": true?

@jakebailey No, I don't have this setting.

The only python analysis settings I have configured are:

```
    "python.analysis.diagnosticSeverityOverrides": {
        "reportUnusedImport": "error",
        "reportUnusedVariable": "error",
        "reportMissingImports": "error",
        "reportDuplicateImport": "error",
    },
    "python.analysis.symbolsHierarchyDepthLimit": 20,
```

**Comment by jakebailey** [comment]
Would you please enable it, and see how this changes your test?

FWIW, `"python.analysis.symbolsHierarchyDepthLimit": 20,` is an old setting for the old, deprecated language server, so wouldn't have any effect.

**Comment by edraft** [comment]
Enabling `"python.analysis.indexing": true` helps me too.
