### ISSUE TITLE
Goto definition goes to stub files 

### ISSUE THREAD

**Issue by cloud-yu** [microsoft/pylance-release#1970]
## Enivronment data
- Language Server Version: v2021.10.2
- OS and version: win10 21h1(19043.1288)
- Python version: 3.9.5-64bit

## Expected behaviour
goto definition goes to the actual source file (.py)
 
## Actual behaviour
hover show annotation from source file(.py)
but goto definition still goes to stub file(.pyi)

![11](https://user-images.githubusercontent.com/8436078/138282767-92da349d-424f-4b3e-9dd7-450e1b6f21bc.gif)

_Originally posted by @cloud-yu in https://github.com/microsoft/pylance-release/issues/949#issuecomment-948594018_

**Comment by Roymprog** [comment]
Same here on MacOS:
Pylance: v2021.10.3
VSCode: 1.61.2
Python: 3.7.9

**Comment by heejaechang** [comment]
it doesn't repro with the latest release. it looks like it is fixed. please reopen if it still repro
