### ISSUE TITLE
Nothing is importing, please help.

### ISSUE THREAD

**Issue by ElbryanWyndon** [microsoft/pylance-release#1971]
When I try to import most things, it simply says "Import "=the thing i wanna use" could not be resolvedPylance (reportMissingImports)", it does that for EVERYTHING, EXCEPT FOR datetime, webbrowser, os, and smtplib. I wanna make a jarvis and I am so confused, it would mean alot if you could help, (for reference, this is my first time using imports, and the ones not working are speech  recognition, pyttsx3, and wikipedia)

**Comment by wovano** [comment]
I got this message too (for "numpy"), but restarting VSCode solved it in my case. Of course, it should not be necessary to restart an IDE just because a Python package was installed...

**Comment by CodeCrazy-ywt** [comment]
Is it **after you pip-install the package** that you import this package and get this error?

**Comment by judej** [comment]
If correcting the environment did not work, please reopen this issue
