### ISSUE TITLE
"p" is not defined in print!

### ISSUE THREAD

**Issue by 411A** [microsoft/pylance-release#1975]
Before using Pylance I was using PyRight & never had any problem...
Now It's been more than 6 months since I'm using Pylance, which makes me mad and frustrated! It can't even recognize packages installed (no! the directory and the interpreter is correct, actually code runs without problem, but pylance can't recognize it)...
& now, it's a legend! **"p" is not defined in print** ! it's more than 10 minutes that pylance shows me this error! not even writing another line helps.
just please fix these issues, or maybe I should go to install another linter.

![image](https://user-images.githubusercontent.com/13054619/138595945-14ecd46e-8fe6-4d60-a50d-1534cdd20a32.png)

-   Language Server version: v2021.10.2
-   OS and version: Windows 10 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1

**Comment by bschnurr** [comment]
Is this still happening on the latest?  2022.1.5 build?

Was your python version installed from the windows store?
I'm not seeing us auto exclude it in the logs. ie `Auto-excluding  xxx`


also is your `Diagnostic Mode` set to openFilesOnly?
