### ISSUE TITLE
Give priority to enum member values in code completion

### ISSUE THREAD

**Issue by talldeveloper** [microsoft/pylance-release#1977]
Code completion for Enum classes will show the enum member values intermixed with the member functions of the enum.

![enum_code_completion](https://user-images.githubusercontent.com/11422620/138696815-3a955e89-1dbe-40c4-b4ec-1d1470e80de8.png)

In this case, the enum has three member values: TEXT, NUMBER and DATETIME. It would make sense if those are at the top of the code completion list, since you are interested in them 99% of the time. Instead, they are intermixed with other members, like mro, name and register (and I even had a production example where some of the values were all the way at the bottom of the list).

Can the enum member values be given a highter priority than the other members?

**Comment by binh-vu** [comment]
An up vote for this features. Moving from Pycharm, I definitely miss this a lot.

**Comment by erictraut** [comment]
Thanks for the suggestion. I've implemented the proposed solution. It will be included in the next release of pylance.

**Comment by heejaechang** [comment]
fixed in 2021.11.0
