### ISSUE TITLE
Feature Request: Docstring popup for `__getitem__` when using `[]` syntax.

### ISSUE THREAD

**Issue by jmrgibson** [microsoft/pylance-release#1980]
I have a .pyi file with docstrings and type hints for a native module that works great in VSCode for showing pop-up/autocomplete inline documentation when editing code. However, many of the native objects have custom `__getitem__` functionality that I would like to show documentation for. The docstring shows up for the function `obj.__getitem__(item)` but naturally most of our users are using the `obj[item]` syntax, which doesn't display any documentation. It would be a huge boon to our users if the `[]` syntax could show the documentation we write for `__getitem__()`.

Since it is difficult to know when half way though a line of code whether it is going to be a `setitem` or `getitem`, I would be OK with VSCode defaulting to the `getitem` docstring. 

I would expect the pop-up to work something as follows:

```python
foo = Foo()
foo["bar"]
#   ^__getitem__ documentation popup is created on open of bracket
#        ^__getitem__ documentation closed when bracket is closed
```

(side note: I have the "show advanced members" option enabled in my settings, this doesn't seem to affect the behaviour of `[]`).

Thanks!

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
