### ISSUE TITLE
Popup from documentation does not respect indentation in code blocks

### ISSUE THREAD

**Issue by jaraqueffdc** [microsoft/pylance-release#1985]
## Environment data

-   VS Code version: 1.61.2
-   Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS and version: MacOS 11.5
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

When defining a docstring in a method with a markdown code block inside the code block not only does syntax highlighting, which is working perfectly, but also respect the indentation.

## Actual behaviour

Indentation in the code block is not respected and all lines of the code are left aligned.

## Steps to reproduce:

1. Create a method with a docstring that includes a markdown code block
2. Use the method and check the popup that appears where the docstring is rendered

## Example
This is a docstring with a code block that won't respect indentation

```python
def function():
    """This is the summary of the method

    ```python
    class A:
        def __init__(self, val):
            self.val = val

        def method(self):
        pass
    ```
    """
```

And this is what the pop up shows.

![Screenshot 2021-10-26 at 11 31 19](https://user-images.githubusercontent.com/75382180/138851379-ce9ec3f7-b505-43b4-a7c6-d1de27649ad5.png)

## Notes
I see that this issue was raised in the past in microsoft/vscode-python#787 but was closed because it was supposed to be fixed but I have never seen it working properly.

**Comment by debonte** [comment]
Closing as this appears to be fixed in our latest builds.

Signature help:
![image](https://github.com/microsoft/pylance-release/assets/12820898/290339fb-5ff6-4393-a54f-5a83edf13d6a)

Hover:
![image](https://github.com/microsoft/pylance-release/assets/12820898/f95d0f93-a251-4a0f-99c7-df6c1f8b7573)
