### ISSUE TITLE
Intellisense does not recognize new Pandas dataframe variable as such when it is assigned with Pandas concat function

### ISSUE THREAD

**Issue by Orionsg** [microsoft/pylance-release#199]
-   VS Code version: VS Code 1.47.3
-   Extension version (available under the Extensions sidebar): Python v2020.7.96456
-   OS and version: Windows 10, x64, 10.0.18363
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8 (Windows store installation)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: Pandas v1.0.4 
-   Relevant/affected Python-related VS Code extensions and their versions: Python (Microsoft) v2020.7.96456
-   Value of the `python.languageServer` setting: 
When I search settings for "python language server", I only get "Python: Lanuage Server" with the value "Microsoft"
There is no setting `python.languageServer`. Could it be that the language server is now included in the general Microsoft Python extension since intellisense does work except for the specific problem reported below.
I installed the PyLance language server but kept getting this issue: 
https://github.com/microsoft/pylance-release/issues/192.

Thus, I have removed the PyLance extension and the problem reported here exists with the "Microsoft" python language server. I suggest that you release your new language server in the same place as the existing one and let it be exclusively setting based, which one to choose.

## Steps to reproduce:
Code which demonstrates the problem of the issue reported here:
```
import pandas as pd 

df_1 = pd.DataFrame()
df_2 = pd.DataFrame()
df_3 = pd.concat([df_1,  df_2])

df_3.rein
```

## Expected behaviour

When typing the last line, intellisense should suggest the reindex function of the DataFrame class.

## Actual behaviour

No functions are suggested. Forcing Intellisense lookup with Ctrl+Space gives the message: "No suggestions."

**Comment by jakebailey** [comment]
This doesn't reproduce in Pylance 2020.8.0.

![image](https://user-images.githubusercontent.com/5341706/89830402-f4213c80-db10-11ea-8d45-ea1ea1bb36a5.png)

Note that `languageServer` not accepting Pylance is #16, and will be fixed in the next Python extension release.
