### ISSUE TITLE
*args type checking

### ISSUE THREAD

**Issue by max-sixty** [microsoft/pylance-release#20]
## Environment data

- Language Server version: 2020.6.1 
- OS and version: MacOS
- Python version (& distribution if applicable, e.g. Anaconda): Python3.7

## Expected behaviour

@jakebailey suggested I open a new issue based on https://github.com/microsoft/pylance-release/issues/15#issuecomment-652612447

From that issue:
> The `dims` issue is a third thing (separate again), as it's saying that you can't unpack `Hashable` into a `*args` parameter, which is true from a type checking point of view. If you believe that message to be wrong, I'd file a separate issue for that one as well, especially if you have the type checking mode set to "off".

I'm not sure this is correct. mypy & the pep seems fairly explicit that `*args: Hashable` should expect each of the args to `Hashable`, not `args` itself to be `Hashable`:
https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values

Copying the requested screenshot from the attached issue for convenience
![image](https://user-images.githubusercontent.com/5635139/86285757-0915c200-bb9a-11ea-98e4-f413890299e1.png)

Let me know if logs etc would be helpful.

Thank you!

**Comment by jakebailey** [comment]
Yes, `dims` should have type `Tuple[Hashable]` (or similar, I can't recall the exact one used for variadic args as I'm typing this).

I'll likely clone this to check for myself, as this codebase seems to be very annotated (yay!), but if you remove that `if` block entirely, does the issue go away?

**Comment by max-sixty** [comment]
I'm not sure that's the case, though. Here's a screenshot of the link above:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/5635139/86288810-6b24f600-bb9f-11ea-81b1-b115dee99dad.png">

Removing the if block does fix it. Why is that? Presumably entering the `if` block means that `dims` must be a tuple, which is iterable?

**Comment by erictraut** [comment]
This is definitely a bug in pyright/pylance. I'm debugging it now. In some code path (not yet determined) it's not treating the type of `args` as a Tuple. In other code paths it does. Stay tuned for a fix. And thanks for reporting the problem.

**Comment by jakebailey** [comment]
When I said "should have type `Tuple[Hashable]`", I meant the actual type of the `dims` variable within the function scope, not that you should annotate it as such. `*dims: Hashable` is a valid declaration.

**Comment by max-sixty** [comment]
> When I said "should have type `Tuple[Hashable]`", I meant the actual type of the `dims` variable within the function scope, not that you should annotate it as such. `*dims: Hashable` is a valid annotation.

Great, I see, thanks

**Comment by erictraut** [comment]
I found and fixed the bug and added some additional unit tests. It will be fixed in the next release. Thanks again for the bug report.

**Comment by max-sixty** [comment]
Thank you! Feel free to close!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202070-9-july-2020
