### ISSUE TITLE
GeneralTypeIssues: Please ignore "Cannot access member" when there ARE matches on dict items

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#2011]
Imagine some class like:
```py
class Bam:
    def __init__(self) -> None:
        self.nfo = {} # type: dict[str, bool | str | list | int | float | dict]
        self.some_magic()

    def some_magic(self):
        self.nfo['bucket'] = []
        self.nfo['report'] = {'count': 123}

    def doings(self):
        # all good:
        self.nfo['count'] = 1337
        self.nfo['count2'] = 42
        self.nfo['count'] += self.nfo['count2']
        self.nfo['is_good'] = True

        # complaint department:
        self.nfo['bucket'].append('asd')
        self.nfo['report']['count'] += 3
```
So `self.nfo` is a dictionary with some annotated values.
Now the type checker allows to put anything in there that's properly typed.
But when fetching something that's not explicitly put there in the very scope it complains.

And it does so with listing ALL the not fitting types silently ignoring that there was actually a fit!
![image](https://user-images.githubusercontent.com/218956/139437109-f176e4a3-15d8-4283-8234-44a7ef47f11a.png)
Although the dictionary IS literally equipped with the said key and value already...

I feel like this inspection rather something "**strict**" and my feature request would be to have these `Cannot access member` errors ignored IF there was at least one fitting type! in "**basic**" type checking mode.

<details "version info">
I'm on:<br>
• Pylance: <b>v2021.10.3</b><br>
• VS Code version: 1.61.2 (user setup)<br>
• Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643<br>
• Date: 2021-10-19T14:57:20.575Z (1 wk ago)<br>
• Electron: 13.5.1<br>
• Chrome: 91.0.4472.164<br>
• Node.js: 14.16.0<br>
• V8: 9.1.269.39-electron.0<br>
• OS: Windows_NT x64 10.0.19043<br>
</details>

Btw: Its **incredible** that Pylance already provides **key auto-completion** for dictionaries like these!! 😊👍

**Comment by ewerybody** [comment]
> FWIW the fact that we offer completions here is not indicative of some special casing when it comes to type evaluation; our completion provider does some additional heuristics on past uses of dictionaries to suggest potential keys for convenience, but that doesn't mean that the code will type check any differently than if we didn't have that feature.

I'm sorry when I made the impression I was implying that. I just wanted to express something nice 🙇‍♀️

**Comment by jakebailey** [comment]
No worries, I just wanted to explain the limitations!

**Comment by ewerybody** [comment]
> 
> 
> The current behavior is dictated by PEP 484 and the way unions are meant to be interpreted within a type checker.
> 
> There are various ways to provide type annotations to avoid these errors, but if you want to simply suppress them, you could add a `# type: ignore` to suppress all of the errors on a single line.

@erictraut can you show me where in [PEP 484](https://python.org/dev/peps/pep-0484) this is given? The document is rather long and I don't want to read it all. So if you have a hint. That'd be great! :)

**Comment by jakebailey** [comment]
It's something that sort of falls out of the type system itself; in short, you can condense the dict type down to something like this (I am oversimplifying and ignoring variance):

```python
K = TypeVar('K')
V = TypeVar('V')

class dict(Generic[K, V]):
    def __getitem__(self, k: K) -> V: ...
```
```

If you declare `dict[int, str | int]`, then it follows that any access to the dict produces `str | int`; the type system doesn't encode any information about what keys map to which types in that union. If you want to explicitly have a dict that has set key-value types, you can use `TypedDict`:

```python
class Movie(TypedDict):
    name: str
    year: int
```
