### ISSUE TITLE
"Union requires two or more type arguments" reported for non-type annotation usage of `Union` (e.g. introspection)

### ISSUE THREAD

**Issue by tonyzbf** [microsoft/pylance-release#2014]
## Environment data

-   Language Server version: v2021.10.3
-   OS and version: macOS 11.6
-   Python version: 3.9.6

## Expected behaviour

`typing.Union` with no subscript is valid when it is used in certain situations other than type annotation, such as for runtime introspection, for example, using [`typing.get_origin`](https://docs.python.org/3/library/typing.html#typing.get_origin):

```py
from typing import Union, get_origin

union_type = Union[int, float, bool]
assert get_origin(union_type) is Union  # is a union type
# get_origin will return the `Union` object itself
```

In such use cases, Pylance should not report issues.

## Actual behaviour

Pylance reports "Union requires two or more type arguments."

This seems to be introduced in the latest 2021.10.3 (October 27) version, in this feature:

> Enhancement: Added check for Union when only one type argument is provided and it is not an unpacked variadic type variable.

**Comment by tonyzbf** [comment]
The same issue appears with `typing.Generic` as well.

**Comment by erictraut** [comment]
The issue with `Union` has already been fixed in pyright. (See https://github.com/microsoft/pyright/issues/2499). I'll file a separate issue for `Generic`.

**Comment by heejaechang** [comment]
fixed in 2021.11.0

**Comment by coady** [comment]
This is still reported when `Union[...]` is used with a non-literal tuple, which is valid.
```python
tup = int, float
Union[tup]  # Union requires two or more type arguments
Union[int]  # same
```

**Comment by erictraut** [comment]
> which is valid

This isn't valid. It doesn't crash at runtime, but `Union` is a special form that's part of the type system, and type checkers like pyright and mypy apply additional rules about what is is valid and what is not for these special forms. Tuples and tuple expressions are also not allowed here. Mypy generates the same error if you try to use a tuple here

I'll also note that the use of `Union` is no longer recommended. The modern way to express a union type within a type annotation is `int | float`.

**Comment by erictraut** [comment]
> and what is a valid way to create union out of tuple of arguments?

There isn't a valid way to do this in the Python type system. Could you describe your use case in more detail? You can use a type alias that refers to a union to define another union, if that helps.

**Comment by hellozyemlya** [comment]
> > and what is a valid way to create union out of tuple of arguments?
> 
> There isn't a valid way to do this in the Python type system. Could you describe your use case in more detail? You can use a type alias that refers to a union to define another union, if that helps.

As mentioned above - runtime introspection. My primary goal is "un-Optional" type. I check if type is Union\UnionType, and ensure that there is one last NoneType in get_args(my_type).

I worked-around that by following code:

```
    result = None
    for t in get_args(optional_type)[:-1]:
        if result is None:
            result = t
        else:
            result = result | t
```

seems to be working fine, and mypy & pyright are happy about that.
