### ISSUE TITLE
How to declare a forward type alias in Python 3.8 with recent `Union` change?

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#2019]
I have been working on Windows 7, which doesn't support Python over 3.8. 

I used to write code like
```python
from typing import Union

Alias = Union["Origin"]

def do_something_with_alias(x: Alias):
    ...

class Origin:
    ...
```
while using `Union` as a work-around for lack of `TypeAlias`.

But with the recent change of `Union` (probably since https://github.com/microsoft/pyright/issues/2479), such usage would cause an error of "Union requires of two or more type arguments".

So, is there another way to accomplish a forward type alias in Python 3.8? Or is it possible to mute this error?

**Comment by erictraut** [comment]
A few suggestions:
1. Don't use a type alias. Just use `"Origin"` directly.
2. Use `Alias: TypeAlias = "Origin"` and import `TypeAlias` from `typing_extension`.
3. Use a `# type: ignore` statement on the line where you declare the alias using the single-argument Union.

**Comment by Azureblade3808** [comment]
Thank you for the suggestions. Good to know these ways, and the `typing_extension` one best suits my need.

**Comment by jwannebo** [comment]
Unfortunately, support for PEP 613 and `TypeAlias` still isn't present in the latest mypy release (Though a PR has gone through to master  python/mypy/pull/11305 ), and until it is, `foo_alias = Union[foo]` is still the idiomatic way to add type aliases as members of a class in mypy:  https://github.com/python/mypy/issues/7866#issuecomment-549454370

Until either this change is toggleable in Pylance, or mypy issues a new release, the only way to have mypy and Pylance agree on the status of the following example is to `# type: ignore` which isn't ideal by any means.

```python
class Foo():
    my_alias = Union[int] # Pylance: "Union requires two or more type arguments"
    my_alias: TypeAlias = int # MyPy 0.910:  'Variable "typing_extensions.TypeAlias" is not valid as a type'
    
    def bar() -> my_alias:
        return 0
```

**Comment by erictraut** [comment]
@jwannebo, I think that PEP 613 support is in the next release of mypy, which will be coming out very soon.

In the meantime, you can either use `# type: ignore` or supply the type twice in the `Union`, like this: `my_alias = Union[int, int]`. Both are somewhat ugly, but a better solution will arrive shortly.
