### ISSUE TITLE
Error warning for typehint

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/pylance-release#2022]
## Environment data

-   Language Server version: v2021.10.3
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

I set the typehint for my function parameter. But the Pylance give me a warning.
## Actual behaviour
![image](https://user-images.githubusercontent.com/82581024/139859627-be654db5-919e-41d0-89d4-8a9ca6d83eac.png)

## Code Snippet / Additional information

```python
class Point:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y

    @classmethod
    def distance(cls,A:Point,B:Point):
        return math.sqrt((A.x-B.x)**2+(A.y-B.y)**2)
    
    def __repr__(self) -> str:
        return f"({self.x},{self.y})"

```

**Comment by CodeCrazy-ywt** [comment]
No, you cannot use `Point` in the type hint of methods inside class `Point`. If you run the code, you will probably get a `NameError`. (To be honest, I'm also deeply troubled by this problem 😭)

**Comment by Vincent0706** [comment]
So, how can I set the typehint for A and B ? I want the input parameter is Point.

**Comment by jakebailey** [comment]
Either use `Point` in quotes to make it a forward reference (e.g. `A: 'Point'`), or place `from __future__ import annotations` at the top of the file.

**Comment by judej** [comment]
Please reopen if the suggestion above does not address the issue. Thanks
