### ISSUE TITLE
Wrong behavior in type-narrowing with Callable

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#2026]
## Environment data

-   Language Server version: 2021.11.0
-   OS and version: Window 7 x64
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.12 Anaconda

## Sample code
```python
from __future__ import annotations

from typing import Any, Callable, Protocol

if True:  # 0
    P = Callable[[], None]
else:
    class P(Protocol):
        def __call__(self) -> None: ...

class C1:
    def __call__(self) -> None: ...
class C2:
    def __call__(self) -> None: ...

def return_any() -> Any: ...

x: P = return_any()  # 1

if isinstance(x, C1):
    x  # 2
else:
    x  # 3
x  # 4

if isinstance(x, C2):
    x  # 5
else:
    x  # 6
x  # 7
```

## Expected behavior

It doesn't matter whether the flag is set to `True` or `False` in line 0.
- Type of `x` is inferred as `P` in line 1.
- Type of `x` is inferred as `C1` in line 2.
- Type of `x` is inferred as `P` in line 3.
- Type of `x` is inferred as `P` in line 4.
- Type of `x` is inferred as `C2` in line 5.
- Type of `x` is inferred as `P` in line 6.
- Type of `x` is inferred as `P` in line 7.

## Actual behavior

When the flag is set to `True` in line 0:
- Type of `x` is inferred as `P` in line 1.
- Type of `x` is inferred as `C1` in line 2.
- ❗ Type of `x` is inferred as `Never` in line 3.
- ❗ Type of `x` is inferred as `C1` in line 4.
- ❗ Type of `x` is inferred as `<subclass of C1 and C2>` in line 5.
- ❗ Type of `x` is inferred as `C1` in line 6.
- ❗ Type of `x` is inferred as `<subclass of C1 and C2> | C1` in line 7.

When the flag is set to `False` in line 0:
- Type of `x` is inferred as `P` in line 1.
- Type of `x` is inferred as `C1` in line 2.
- Type of `x` is inferred as `P` in line 3.
- ❗ Type of `x` is inferred as `C1 | P` in line 4.
- Type of `x` is inferred as `C2` in line 5.
- ❗ Type of `x` is inferred as `C1 | P` in line 6.
- ❗ Type of `x` is inferred as `C2 | C1 | P` in line 7.

**Comment by Azureblade3808** [comment]
If we focus on the title, while ignoring the inconsistency between `Callable` and callable protocol, here is a simplified example:

```python
from typing import Any

def return_any() -> Any: ...
x: object = return_any()  # Inferred: `object`

if isinstance(x, int):
    x  # Inferred: `int`
x  # Inferred: `int | object` instead of `object`

if isinstance(x, str):
    x  # Inferred: `str`
x  # Inferred: `str | int | object` instead of object
```

**Comment by Azureblade3808** [comment]
Sorry to have modified both the title and the content. I believe they can better illustrate this issue now.

**Comment by Azureblade3808** [comment]
When a callable protocol is used as the original type, the unexpected narrowed types are a bit ugly but still acceptable, and the behavior seems consistent with normal classes.

As for `Callable`, the problem could probably be that Pylance thought `Callable[[], None]` is equal to `C1`, which would explain the behavior in line 3.

**Comment by erictraut** [comment]
Can you share what you're trying to do with this code pattern?

`isinstance` is not appropriate to use for callable types or protocols that don't support runtime checks. It's meant to be used for instances of classes that are part of class hierarchies.

The behaviors you're seeing are consistent with what I would expect given the somewhat nonsensical inputs. Mypy provides similar type narrowing behavior for this code, although there are minor differences that can be explained with known behavior differences between the two type checkers.

**Comment by Azureblade3808** [comment]
```python
from __future__ import annotations

from math import inf, nan
from typing import Callable


Operator = Callable[..., float]

class Negate:
    def __call__(self, a: float, /) -> float:
        return -a

class Multiply:
    def __call__(self, a: float, b: float, /) -> float:
        return a + b

class Divide:
    __allows_zero_division: bool

    def __init__(self, allows_zero_division: bool = False) -> None:
        self.__allows_zero_division = allows_zero_division

    def __call__(self, a: float, b: float, /) -> float:
        try:
            return a / b
        except ZeroDivisionError:
            if self.__allows_zero_division:
                if a > 0:
                    return inf
                elif a < 0:
                    return -inf
                else:
                    return nan
            else:
                raise


class Calculation:
    operator: Operator  # Could be any operator declared here, or just a plain callable.
    operands: tuple[float | Calculation, ...]

    def __init__(self, operator: Operator, *operands: float | Calculation) -> None:
        self.operator = operator
        self.operands = operands

def standardize_calculation(origin: Calculation) -> Calculation:
    """
    Rebuild the calculation in a standard form, if possible.
    """

    operator = origin.operator
    operands = origin.operands

    if isinstance(operator, Multiply):
        return origin  # FIXME

    # Type of `operator` is inferred as `Never`.
    if isinstance(operator, Divide):
        (a, b) = operands
        (absolved, negative) = standardize_division(operator, a, b)
        if negative:
            return Calculation(Negate(), absolved)
        else:
            return absolved

    ...  # TODO

    return origin

def standardize_division(divide: Divide, a: float | Calculation, b: float | Calculation) -> tuple[Calculation, bool]:
    """
    Returns a standard division.

    Parameters
    ----------
    divide : Divide
        The Divide operator.

    a : float
    b : float
        The operands of this division.

    Returns
    -------
    calculation:
        A calculation with the identical Divide operator, and absolved operands.

    negative: bool
        Whether the result calculation needs to be negated.
    """

    ...
```

This roughly shows what I was doing. Though there is no warnings in the code, you can see that the inferred type becomes wrong after first isinstance check.

**Comment by erictraut** [comment]
I don't think this approach will work because `isinstance` will always return False if you pass a function (a "plain callable") as the first argument. There's not enough implemented here for me to test it. Does it run?

Is your intent that `Operator` must be an instance of one of the defined operator classes? If so, then you should simply define `Operator` as a union of these classes.

```python
Operator = Negate | Multiply | Divide
```

Then I think this will work, both at runtime and at type checking time.

**Comment by Azureblade3808** [comment]
I expect the `operator` in `Calculation` be either an instance of a known operator class or some arbitary function as long as it take some arguments and return a float. The `standardize_calculation` function will just return the input calculation if type of `operator` is not a known operator class.

To be clear, the point bugs me is that `isinstance` behave differently between a Callable and a callable protocol when they are mostly equal. If this behavior is intended, I will work around it.

**Comment by erictraut** [comment]
Yes, the behavior is intended.

A callback protocol is similar to a `Callable`, but there are important differences between the two. A class can derive from a callback protocol, but it cannot derive from `Callable`.

This is valid:
```python
class P(Protocol):
    def __call__(self) -> None: ...
class MyOperator(C1, P): ...
```

But this doesn't work:
```python
P = Callable[[], None]
class MyOperator(C1, P): ...
```

Some protocol classes also implement runtime code that dynamically implements the `isinstance` logic to introspect an object and determine whether it implements the protocol. A `Callable` cannot do this.

**Comment by Azureblade3808** [comment]
I see. Thank you.
