### ISSUE TITLE
how to ignore warning

### ISSUE THREAD

**Issue by www516717402** [microsoft/pylance-release#2027]
``` python
from XXX import KKK
# it will display Import "KKK" `could not be resolved` warning
```
How to use code ignore this warning like flake8, as follows:
``` python
from XXX import KKK  # noqa: E402
```

**Comment by jakebailey** [comment]
You can use `# type: ignore` to suppress any diagnostics that Pylance produces.

**Comment by judej** [comment]
Please reopen if this does not adequately satisfy the issue

**Comment by www516717402** [comment]
> You can use `# type: ignore` to suppress any diagnostics that Pylance produces.

Great help. Thanks.
