### ISSUE TITLE
Intellisense not working for class objects in a list.

### ISSUE THREAD

**Issue by DominikLindorfer** [microsoft/pylance-release#2028]
## Environment data

-   Language Server version: 2021.10.3
-   OS and version: Windows_NT x64 10.0.14393
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Actual behaviour

Intellisense shows "No suggestion." for class variables when append is used to append objects to a list.

![Intellisense](https://user-images.githubusercontent.com/21077042/140058339-49d1fe13-f009-420c-af95-177b5d0eaafb.PNG)

## Expected behaviour

Should preview the class variables as in the screenshot below, where the classes are initiated within the list.

![Intellisense_2](https://user-images.githubusercontent.com/21077042/140058365-fc4d8047-3c40-4ec1-b98b-bebd384c48a7.PNG)

## Logs

```
No Logs.
```

## Code Snippet / Additional information

```python
# Test Class
class Testclass:

    def __init__(self, x, y) -> None:
        self.x = x
        self.y = y


xylist = []
xylist.append(Testclass(1,2))
xylist.append(Testclass(3,4))

xylist[0].x

xylist2 = [Testclass(1,2), Testclass(3,4)]
xylist2[0].x
```

**Comment by erictraut** [comment]
The type of `xylist` is inferred to be a list, but its contents are not constrained to any particular type. If you provide a type annotation for it, its contents will be constrained, and intellisense will work as you are expecting.

```python
xylist: list[Testclass] = []
```

**Comment by DominikLindorfer** [comment]
Thank you very much for your quick reply! I see where the problem is now and intellisense is working as expected. I've just tested this for lists where I union two classes in my list and intellisense then suggests every variable possibility. This is fine for me but i guess it would be nice if intellisense would propose only those variables that are in the actual object (assuming one would use more than two different types / variables). Is there a way to do this?

![Intellisense_3](https://user-images.githubusercontent.com/21077042/140273046-d01030a7-df30-43ef-b5ee-2beab54f9776.PNG)

**Comment by erictraut** [comment]
No, there's no way to do this with lists. Lists are dynamic mutable data structures, so in general a static type checker has no way of knowing what type of object is associated with each index within a list at any given point in the code. 

If you are able to use a tuple rather than a list, a static type checker can then understand the type of each entry. That's possible because a tuple is an immutable data structure and the Python static type system allows for each entry within a tuple to be typed independently of the others.

Here's how that would look.

```python
xytuple = (Testclass(1, 2), Testclass2(3, 4))
xytuple[0]. <completion suggestions limited to Testclass>
xytuple[1]. <completion suggestions limited to Testclass2>
```

**Comment by DominikLindorfer** [comment]
Thank you very much, that's fine for me!
