### ISSUE TITLE
Cannot register the properties "python.analysis.logLevel" and "python.analysis.typeshedPaths", which are already registered.

### ISSUE THREAD

**Issue by hsinyinfu** [microsoft/pylance-release#2032]
## Environment data

-   Language Server version: v2021.11.0
-   OS and version: Windows 10 20H2 (19042.1083)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7
-   VSCode: 1.61.2

## Actual behaviour

Steps to reproduce:
1. Open the VS Code extensions panel. Locate Pylance from the list of installed extensions.
2. Install the Pylance extension.
3. Reload the VSCode.
4. Click "Runtime Status" in the Pylance View.

There are two messages shown in the Runtime Status (no matter if Pylance was activated or not):
* Cannot register 'python.analysis.logLevel'. This property is already registered.
* Cannot register 'python.analysis.typeshedPaths'. This property is already registered.

I also tried to install only "Python" extension and its dependency extensions (Pylance and Jupyter) in a clean "Portable VSCode" environment (where no other extensions are installed), but the two messages were still shown in the "Runtime Status" in Pylance.

**Comment by jakebailey** [comment]
The next version of the python extension will have fixed this; our old language server is being deprecated and some settings are moving around. You should be able to ignore it or switch to the insiders builds.

**Comment by jakebailey** [comment]
The Python extension was just released, so this should no longer be a problem.

**Comment by shp7724** [comment]
I just reinstalled the latest python extension, and I have the same issue. Pylance doesn't seem to be working for me.

- Python: v2021.10.1365161279
- Pylance: v2021.11.1
- VS Code: v1.60.0
