### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by moore911** [microsoft/pylance-release#2035]
- Issue Type: `Bug`
- Extension Name: `vscode-pylance`
- Extension Version: `2021.11.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by CodeCrazy-ywt** [comment]
It means that you need to paste things.

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
