### ISSUE TITLE
Unable to read IntelliCode metadata.

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/pylance-release#2036]
When I open vscode, the python LSP report such information:
![image](https://user-images.githubusercontent.com/82581024/140320133-ec12f3c7-90df-43e9-a2ec-8cbd0f7e537d.png)
~~~
[Info  - 下午9:15:15] Pylance language server 2021.11.0 (pyright fb86eac6) starting
[Info  - 下午9:15:15] Server root directory: c:\Users\thinkpad\.vscode\extensions\ms-python.vscode-pylance-2021.11.0\dist
[Error - 下午9:15:16] Unable to read IntelliCode metadata. Exception Error: ENOENT: no such file or directory, open 'd:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19', Error code: ENOENT
[Error - 下午9:15:16] Unable to close model zip. Exception Error: ENOENT: no such file or directory, open 'd:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19', Error code: ENOENT
~~~
And the path "d:\Visual Studio code\extensions\visualstudioexptteam.vscodeintellicode-1.2.14\cache" is the old vscode extension path.

**Comment by judej** [comment]
This is an Intellicode issue. Would you please file it using the instructions below:

Reporting a Problem
-------------------
To report a problem with IntelliCode for Visual Studio Code, please go to https://github.com/MicrosoftDocs/intellicode and copy and paste any details that are visible in the Output window logs for VS-IntelliCode and the language you're using.
