### ISSUE TITLE
Pyright do not autocomplete scipy.stats.norm module

### ISSUE THREAD

**Issue by troflog** [microsoft/pylance-release#2038]
**Describe the bug**
Trying to import the norm module from `scipy.stats` (using VSCode) in the following way:
`from scipy.stats import norm`
but Pyright is not able to find the norm module. The python code with the `from scipy.stats import norm` runs find, so there is no issue with my python installation. Ipython autocomplete do find this module.

**To Reproduce**
Make a conda environement which contains scipy, make a .py file, set python interpreter to this environment in VsCode and try to import the norm module.

**Expected behavior**
The norm module should be found by the VsCode's autocomplete engine (Pyright/pylance).

**Screenshots or Code**
![missing_scipy_stats_module](https://user-images.githubusercontent.com/21247912/140300262-31bb488c-2963-4c49-9518-20a04a2a3037.png)

**VS Code extension or command-line**
Running VS Code with Pylance v2021.11.0 

**Additional context**
It works find to import norm in this way:
`from scipy.stats._continuous_distns import norm`
Doing it like this, VsCode autocompletes the norm module.

**Comment by ldorigo** [comment]
Had the same issue today. This is because of how scipy.stats defines `__all__`:

```python
__all__ = [s for s in dir() if not s.startswith("_")]  # Remove dunders.
```
When I open the file, Pylance actually highlights the line and says that it does not support modifications to `__all__` and that it might result in incorrect exported names. Is there anything that could be done on pylance's side, or should I file an issue at scipy? If the latter, do you have some suggestions for the easiest way they could make this work without major refactoring of the library? 

The line in question for reference: https://github.com/scipy/scipy/blob/50e8aeacfa1e1b843100c7bdca7dfc338a8d43c4/scipy/stats/__init__.py#L473

@jakebailey , mentioning you because you replied to similar issues I had about this in the past.

**Comment by jakebailey** [comment]
I don't personally know why that line is even required. If `__all__` is not set, Python will automatically omit `_` prefixed variables when doing `import *`. `__all__` should only be set if a different behavior is required. Perhaps this is some old cargo culting copy pasting.

**Comment by ilayn** [comment]
The reason for that is *lazy-loading* our modules. That's the reason `norm` does not exist in the namespace there. To be able to get norm from stats is to import it first. 

```python
import scipy.stats as stat
stat.no   #  Typing this will auto-complete
```

On version 1.9.0, there will be some improvements about this (see https://github.com/scipy/scipy/pull/15230)

> Perhaps this is some old cargo culting copy pasting.

No. I wish it was that simple.

**Comment by ldorigo** [comment]
After bringing up this issue on Scipy, I actually tried this again on a more recent version of Pylance (tried it at work yesterday and it did not work, but it's an older release...), and now it seems that it actually finds something:

![image](https://user-images.githubusercontent.com/8631181/158985949-11c0c4ec-88ab-484b-9fe9-7375a5d0b8fa.png)

So, I'm not entirely sure what changed, but this might be solved?

**Comment by tupui** [comment]
@ldorigo note that as Ilhan said, you should import `stats` before. This has the added benefit that you keep a namespace and make it cleaner in your code about where a function is coming from. Things like `norm` are very common names.

**Comment by judej** [comment]
@ldorigo, if the `import scipy.stats as stats` does not result in completions. Please reopen is issue. I've tried it and it worked. 

thanks!
