### ISSUE TITLE
Talk to Jupyter kernel/VSCode Notebook kernel to support dynamically created function.

### ISSUE THREAD

**Issue by thy09** [microsoft/pylance-release#204]
According to the discussion in issue #117 , we know that currently pylance can only get the static information from the code.
 Thus we need to get the variable status from Jupyter kernel directly in vscode-python, see the PR: https://github.com/microsoft/vscode-python/pull/13259#issuecomment-669286725
 
 In long term, I believe it would be better to let Pylance talk to Jupyter kernel or VSCode notebook kernel,
 thus pylance could provide better information from both static analysis and dynamic information, especially for the case that a function is dynamically created.

**Comment by judej** [comment]
Closing stale bug. Jupyter rework is in progress.
