### ISSUE TITLE
Can't give the intellisense of "with"

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/pylance-release#2042]
The intellisense didn't give the tips of the key word "key"
![image](https://user-images.githubusercontent.com/82581024/140463536-1f0e0d76-13ed-43a7-b336-ba7c8f1214da.png)

**Comment by CodeCrazy-ywt** [comment]
Check your settings. Have you enabled suggestions for keywords?

**Comment by erictraut** [comment]
Thanks for the bug report. I've confirmed that the completion provider was missing support for the `with` keyword. This will be fixed in the next release.

**Comment by heejaechang** [comment]
fixed in 2021.11.1 release
