### ISSUE TITLE
Wrong return type of psutil.Process.status

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/pylance-release#2043]
## Environment data

-   Language Server version: v2021.11.0
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

## Expected behaviour

Return type of `psutil.Process.status` should be `str`.

## Actual behaviour

Return type of `psutil.Process.status` is annotated as `int` by Pylance and in
`/home/xhtang/.vscode-server/extensions/ms-python.vscode-pylance-2021.11.0/dist/typeshed-fallback/stubs/psutil/psutil/__init__.pyi`

## Code Snippet / Additional information

```python
import psutil
status: str = psutil.Process().status()
```

**Comment by erictraut** [comment]
This type evaluation is based on the type definition of the `Process` class, which is defined in the typeshed stub `psutil/__init__.pyi/Process`. 

```python
class Process:
    ...
    def status(self) -> int: ...
    ...
```

If you think this is an error, please file a bug or a PR with the typeshed repo. Pylance will pick up any changes from that repo.

**Comment by srittau** [comment]
There is an open pull request on typeshed that addresses this: python/typeshed#6245.
