### ISSUE TITLE
redis zpopmin wrong type

### ISSUE THREAD

**Issue by louisabraham** [microsoft/pylance-release#2046]
from redis/client.pyi

    def zpopmin(self, name: _Key, count: int | None = ...) -> list[_StrType]: ...

Actually it returns a list of tuples (bytes, scores). I think scores is always float.

**Comment by jakebailey** [comment]
FWIW this repo isn't exactly the right place to report issues with typeshed; https://github.com/python/typeshed/issues is likely to get a better response and we regularly update our copy.

**Comment by louisabraham** [comment]
My bad, I was actually confused about the source of that annotation.
