### ISSUE TITLE
Problem messages not showing in the popover when hovering with the mouse

### ISSUE THREAD

**Issue by floatingpurr** [microsoft/pylance-release#2047]
## Environment data

-   Language Server version: v2021.11.0 (VS Code Version: 1.62.0)
-   OS and version: macOS BigSur 11.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10

## Expected behaviour

I should see all the error messages in the tooltip when hovering over the code with the mouse

## Actual behaviour

When I hover with the mouse on a problem, I can't see all the available error messages (e.g., flake8 messages are available just in the problem bar at the bottom, but not in the popover). I used to see all of them also in the popover before the latest VSCode update. Here is a pic of the problem in action:

<img width="524" alt="a" src="https://user-images.githubusercontent.com/14820600/140764410-95e8f18f-bc4a-4d26-9084-727ad0d11baf.png">

## Logs

```
Starting Pylance language server.
> conda --version
> ~/myPath/.venv/bin/flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/myPath/myProject/main.py
cwd: ~/myPath
##########Linting Output - flake8##########
10,7,F,F821:undefined name 'e'

```

## Code Snippet / Additional information

```python
def hello():
    print("hello world")
print(e)
```

Settings

```json
{
    "python.pythonPath": ".venv/bin/python",
    "python.formatting.provider": "black",
    "editor.formatOnSave": true,
    "python.linting.flake8Enabled": true,
    "python.linting.enabled": true,
}
```

**Comment by jakebailey** [comment]
I don't think this has anything to do with Pylance; all we do is report the diagnostics and it's up to VS Code to display them. We don't have any way in which we could silence someone else's diagnostics. I think VS Code was the right place to report this.

**Comment by floatingpurr** [comment]
thanx for the suggestion
