### ISSUE TITLE
Tensorflow.data module not recognized after vscode update

### ISSUE THREAD

**Issue by BlueskyFR** [microsoft/pylance-release#2050]
## Environment data

-   VS Code version: Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-03T15:18:44.904Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.70-1-MANJARO snap
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001414422
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Manjaro Linux
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Problem

I updated my vscode a couple of minutes ago and this feature was working: the problem I am going to describe is cause by the update:
The autocompletion is not working for the following module:

![image](https://user-images.githubusercontent.com/25421460/140789518-d1b56095-22f4-4bd4-a13c-2deab58e9566.png)

## Logs

```
[FG] completion at XXX/test.py:0:18 ...
[FG]   parsing: XXX/test.py (1ms)
[FG]   binding: XXX/test.py (0ms)
[FG] completion at XXX/test.py:0:18 [found 0 items] (1ms)
```

**Comment by bschnurr** [comment]
in the examples i see its

```python
import tensorflow as tf
tf.data.AUTOTUNE
```

**Comment by bschnurr** [comment]
which version of tensorflow r you using?

**Comment by BlueskyFR** [comment]
> which version of tensorflow r you using?

The statement I used in my screenshot is a valid one and is executed normally, the problem comes from Pylance.
I am using TensorFlow 2.7.0.

Thanks for looking into this!

**Comment by vigneshgarrapally** [comment]
Pylance is able to recognize when import is done [https://github.com/microsoft/pylance-release/issues/2050#issuecomment-963426222](this) way but when import is made using `from tensorflow.data import AUTOTUNE` pylance isn't able to recognize for me as well. But I assume this issue is there even before the latest vs code update and I also think  this is the same in other editors like PyCharm as well.

**Comment by BlueskyFR** [comment]
@vigneshgarrapally I am now \*also\* having a problem with autocompletion using Nvidia Dali:
![image](https://user-images.githubusercontent.com/25421460/146519608-8ab02e64-adba-4cbd-affc-65f15cf8d041.png)
![image](https://user-images.githubusercontent.com/25421460/146519667-f2113df3-ea23-41ca-978e-f92a4d8ef849.png)

This problem seems to hit a wide variety of libraries, I have other examples if you want

**Comment by BlueskyFR** [comment]
@vigneshgarrapally @bschnurr I am now \*also\* having a problem with autocompletion using Nvidia Dali:
![image](https://user-images.githubusercontent.com/25421460/146519608-8ab02e64-adba-4cbd-affc-65f15cf8d041.png)
![image](https://user-images.githubusercontent.com/25421460/146519667-f2113df3-ea23-41ca-978e-f92a4d8ef849.png)

This problem seems to hit a wide variety of libraries, I have other examples if you want

**Comment by bschnurr** [comment]
You can file a bug with tensorflow, but I dont think you are supposed to use it that way. 

this also works
```
from tensorflow._api.v2.data import AUTOTUNE
```
