### ISSUE TITLE
how to annotate tuple[tuple[? - `Tuple entry is incorrect type` ...

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#2051]
Hello! I'd like to use `types.FunctionType` to annotate a a function with incoming nested tuples like

```py
def set_tuple(my_tuple):
    # type: (tuple[tuple[str, types.FunctionType], ...]) -> None
    print('my_tuple: %s' % str(my_tuple))
```
Now when I want to use it like expected Pylance keeps complaining:
```py
def a_function():
    pass


def main():
    my_tuple = (('name', a_function), ('bla', a_function))
    set_tuple(my_tuple)
```
Saying:
```
Argument of type "tuple[tuple[Literal['name'], () -> None], tuple[Literal['bla'], () -> None]]" cannot be assigned to parameter "my_tuple" of type "tuple[tuple[str, FunctionType], ...]" in function "set_tuple"
  Tuple entry 1 is incorrect type
    Tuple entry 2 is incorrect type
      "object" is incompatible with "FunctionType"
```

I don't understand. 😐
`type(a_function)` is EXACTLY the right type as `types.FunctionType` like literally:
```py
>>>type(a_function) is types.FunctionType
True
```

Unfortunately I cannot import `typing` and use `typing.Callable` here.
What am I doing wrong? (again)

**Comment by erictraut** [comment]
`FunctionType` isn't the correct type to use here. It's a class that's used internally to the Python runtime. It does have legitimate uses within source code for mypy, pylance or other tools that are interacting with the internals of Python, but for most code, you should never use types defined in the `types` module within your annotations. From the perspective of a type checker, it doesn't have any special properties, and you cannot assign callables to a `FunctionType`.

The correct thing to do here is to use `typing.Callable` which is part of the type system and is designed for this case.

```python
def set_tuple(my_tuple: tuple[tuple[str, Callable[..., Any]], ...]) -> None: ...
```

You mentioned that you cannot import `typing`. Why not?

**Comment by ewerybody** [comment]
> ... It's a class that's used internally to the Python runtime. ...

One can literally do `import types` and there it is! If this is supposed to work internally only then its not very well hidden. I don't read any such warnings in the file itself. And I've seen a couple runtime type checks with is already. 🤷‍♀️ 

> You mentioned that you cannot import `typing`. Why not?

code needs to work in both Python 2 and 3.

**Comment by erictraut** [comment]
`typing` is available in Python 2. Without it, you can't do much in the way of type annotations, even if you're using comment-based annotations.

**Comment by ewerybody** [comment]
```
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named typing
>>>
```
this is the latest Python 2.7 version

You mean like https://pypi.org/project/typing ?

Well, So far I'm doing VERY well with comment-based annotations. This would really be the FIRST thing I come across that wouldn't work. I'd rather stick to keeping the `typing` module out. Its 2.5k lines that are not needed at runtime ... HEEEEELP!

**Comment by jakebailey** [comment]
Yes, though that package is effectively unmaintained at this point, as all new additions go into `typing_extensions`, and all versions of Python that required the `typing` backport package are long since unsupported: https://github.com/python/typing/issues/877

If you don't want to install this for 2.7, you can feasibly just write something like:


```python
if sys.version_info > (3,):
    import typing
```

Pyright/Pylance do not support Python 2, so this should be a no-op and `typing.Callable` should be available for use in type comments.

**Comment by ewerybody** [comment]
Well, this also works:
```py
def a_function():
    pass

MyType = type(a_function)

def set_tuple(my_tuple):
    # type: (tuple[tuple[str, MyType], ...]) -> None
    print('my_tuple: %s' % str(my_tuple))
```

So that's exactly the same as the `types` module does. And the type is like **bitwise** identical.
Is the `types` module somehow "blocked"?

**Comment by erictraut** [comment]
The classes defined in the `types`  module correspond to internal types used within the Python runtime. They are not the appropriate types to use for type checking annotations. You should use the special-form types defined in the `typing` module for type annotations. For example, to describe the type of a function, you would use the `typing.Callable` type. For more details, refer to PEP 484.

If you want to annotate a parameter that is a `tuple` that contains a `str` and a callable that accepts zero parameters and returns a `None` result, the following is the correct annotation:

```python
from typing import Callable

def set_tuple(my_tuple: tuple[str, Callable[[], None]]):
    ...
```

**Comment by jakebailey** [comment]
> So that's exactly the same as the types module does. And the type is like bitwise identical.
> Is the types module somehow "blocked"?

Type analysis is defined by the typing PEPs and stub files; the PEPs define certain semantics for `type` and `Callable` (and so on), but they don't define special behavior for the `types` module, which is instead [stubbed here](https://github.com/python/typeshed/blob/master/stdlib/types.pyi), and we treat this stub like any other module's stub.
