### ISSUE TITLE
Support math in docstrings as per Sphinx notation / dollar sign notation

### ISSUE THREAD

**Issue by LunarLanding** [microsoft/pylance-release#2058]
For instance, in numpy.fft:
```
There are many ways to define the DFT, varying in the sign of the
exponent, normalization, etc.  In this implementation, the DFT is defined
as

.. math::
   A_k =  \\sum_{m=0}^{n-1} a_m \\exp\\left\\{-2\\pi i{mk \\over n}\\right\\}
   \\qquad k = 0,\\ldots,n-1.
```

Sphinx notation is in https://www.sphinx-doc.org/en/1.0/ext/math.html . 
These could be rendered with MathJax. vscode's notebook markdown renderer uses it : https://code.visualstudio.com/updates/v1_55#_continued-improvements-to-extensible-markdown-renderers-in-notebooks

Personally I would find the `$\tau$` and `$$\tau$$` more practical.

Someone asked somewhere else about this : https://stackoverflow.com/questions/61751393/view-latex-translation-of-documentation-when-hovering-on-function-definition

This would make sense given the current way of using latex in numpy docs. 
However, it seems the python docstring format is very fragmented.

**Comment by jakebailey** [comment]
FWIW until VS Code allows tooltips in something more powerful than markdown (like raw HTML), we can't actually render LaTeX or anything like it.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
