### ISSUE TITLE
Auto complete for attributes form CBV in Django not working

### ISSUE THREAD

**Issue by xaitec** [microsoft/pylance-release#2059]
## Environment data

-   Language Server version: 2021.10.1 and greater
-   OS and version: Kubuntu 21.10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Expected behaviour

In version 2021.10.0 we get the attributes autocompleted for CBV in Django
![image](https://user-images.githubusercontent.com/678838/141024634-1f126375-36e2-49e1-9174-8cecb9cc5b93.png)

## Actual behaviour

However for 2021.11.1 and above that functionality has gone
![image](https://user-images.githubusercontent.com/678838/141024445-53c57d50-bb6a-4ff8-8953-c25ef2fe08ea.png)

## Code Snippet / Additional information

```python

```

**Comment by jakebailey** [comment]
Thanks for the issue; we'll take a look.

Are the versions you've listed correct? Those versions you've listed are about a month old (so testing with the current 2021.11.0 would be helpful).

**Comment by xaitec** [comment]
My mistake, the actual behavior image is based on 2021.11.1. I made the edit

**Comment by debonte** [comment]
@xaitec, the fix is available in the latest Pylance insiders build ([2022.5.0-pre.1](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202250-pre1-4-may-2022)). We're not shipping a stable build this week. If you're not using Pylance insiders, you'll see the fix in next week's stable build.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.5.1, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202251-11-May-2022)

**Comment by xaitec** [comment]
Awesome, I appreciate it very much.
