### ISSUE TITLE
Intellisense not working at all on VS Code when using Python

### ISSUE THREAD

**Issue by andreapesare** [microsoft/pylance-release#2062]
Hi,
I installed VS Code 1.62.1 on macOS Monterey (12.0.1). I also installed the Python Extension (including the Pylance Extension).

When I write code in Python, the Intellisense feature is not working at all, nothing happens. I tried on a JavaScript file and Intellisense is working on it.

Could you help me? Thank you

**Comment by jakebailey** [comment]
Would you mind following the steps outlined here to provide us with more info? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

(Our issue template typically asks for that, but you may have used the "question" type instead.)

**Comment by judej** [comment]
Closing stale issue
