### ISSUE TITLE
Pylance cannot detect renamed module

### ISSUE THREAD

**Issue by zuhataslan** [microsoft/pylance-release#2067]
## Environment data

Pylance: 
v2021.11.1

VSCode: 
![image](https://user-images.githubusercontent.com/60361090/141257841-d54c9bce-3eb7-4987-83df-fedac2ab8846.png)

Python Language Server Output:
[Info  - 8:30:26 AM] Pylance language server 2021.11.1 (pyright 446a9bdb) starting
[Info  - 8:30:26 AM] Server root directory: /home/xxx/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.11.1/dist
[Info  - 8:30:27 AM] No configuration file found.
[Info  - 8:30:27 AM] No pyproject.toml file found.
[Info  - 8:30:27 AM] Setting pythonPath for service "xxx": "/bin/python"
[Warn  - 8:30:27 AM] stubPath /mnt/c/Users/xxx/Downloads/xxx/typings is not a valid directory.
[Info  - 8:30:27 AM] Assuming Python version 3.9
[Info  - 8:30:27 AM] Assuming Python platform Linux
[Warn  - 8:30:27 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:30:27 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:30:27 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:30:27 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 8:30:27 AM] Searching for source files
[Info  - 8:30:27 AM] Found 21 source files
[Info  - 8:30:27 AM] Background analysis(1) root directory: /home/xxx/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.11.1/dist
[Info  - 8:30:27 AM] Background analysis(1) started
[Info  - 8:41:17 AM] Pylance language server 2021.11.1 (pyright 446a9bdb) starting
[Info  - 8:41:17 AM] Server root directory: /home/xxx/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.11.1/dist
[Info  - 8:41:17 AM] No configuration file found.
[Info  - 8:41:17 AM] No pyproject.toml file found.
[Info  - 8:41:17 AM] Setting pythonPath for service "xxx": "/bin/python"
[Warn  - 8:41:17 AM] stubPath /mnt/c/Users/xxx/Downloads/xxx/typings is not a valid directory.
[Info  - 8:41:18 AM] Assuming Python version 3.9
[Info  - 8:41:18 AM] Assuming Python platform Linux
[Warn  - 8:41:18 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:41:18 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:41:18 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 8:41:18 AM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 8:41:18 AM] Searching for source files
[Info  - 8:41:18 AM] Found 21 source files
[Info  - 8:41:18 AM] Background analysis(1) root directory: /home/xxx/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.11.1/dist
[Info  - 8:41:18 AM] Background analysis(1) started
Read the guidelines for filing an issue first.

## Expected behaviour

When renaming a already imported module file name, changing the import line should find the module with new name

## Actual behaviour

When renaming an already imported module file name inside vscode, renaming the import line reports that '"new filename" is not accessed'

## Notes
I don't know why I have Warns like: [Warn  - 8:41:17 AM] stubPath /mnt/c/Users/xxx/Downloads/xxx/typings is not a valid directory.

I Installed python and pylance extensions inside vscode as usual. This and the second TypeError regarding file system watcher could be the issue

**Comment by heejaechang** [comment]
@zuhataslan can you provide some repro steps for us to take a look?

**Comment by heejaechang** [comment]
I will close this issue since we didn't get any response from users.
