### ISSUE TITLE
Pylance auto-suggest python packages for import. 

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#2069]
And I need a favor to avoid spending another 3 hours for searching the net.
Is there any settings that would help Pylance/Python extension to realize python packages in order to auto-suggest for import. 
Actually I spent some time to find out, `"python.analysis.diagnosticMode": "workspace",` , `"python.analysis.extraPaths"` and `"python.autoComplete.extraPaths"` are required, but these are not enough and the is some shortage/deficiency.

_Originally posted by @mh-firouzjaah in https://github.com/microsoft/vscode-python/issues/18006#issuecomment-966988574_

**Comment by jakebailey** [comment]
I think what is being asked for here is `"python.analysis.indexing": true`, a work in progress feature that should give auto imports for libraries (and quick fixes for things in the workspace).

**Comment by judej** [comment]
The indexing setting is complete.
