### ISSUE TITLE
Static member should be highlighted as such

### ISSUE THREAD

**Issue by TFCx** [microsoft/pylance-release#2084]
![image](https://user-images.githubusercontent.com/9135500/142221256-a3f4aa4a-1a7b-457b-a7d5-0b83a0667490.png)

Static python members should be detected by the LSP and displayed with the correct style. As of now, static members and members of instances of a class are both detected as properties. (Note that semantic highlighting of VSCode does work on static functions).

Thanks for all the hard work on Pylance :)

**Comment by erictraut** [comment]
By "static member", are you referring to class variables?

In your example, it's clear that `static_member` is used only as a class variable, at least within `SomeClass` (although that assumption could break in a hypothetical subclass of `SomeClass`). The challenge is that in Python it's common to use the same symbol name to refer to a class variable and an instance variable. For example, you can overwrite `static_member` with an instance-specific value by assigning a value to `self.static_member` within a method. If it is overwritten in some methods but not in others, then any method that accesses it might be accessing the class variable or the instance variable, depending on the order of execution. So a static analyzer can't generally determine whether a class-level variable is also an instance variable. Unlike most languages, Python doesn't provide a way to specify that a variable must be "static" (i.e. used only as a class variable).

**Comment by TFCx** [comment]
Thanks for the answer @erictraut.

From what I understand (i'm not a Python guru), the _class variable_ is shared. All instances have some kind of "reference" to this class variable by default. If I'm modifying the class variable, all the references will get the new value (if I access them). However, if I modify the value through one reference of a specific instance, then it will "detach" and thus become an instance variable.

A static analyzer might detect that there's no assignment going through instances variables? Would it be possible to then consider that all those variables really reference to the class variable? If it's not possible, at least a `SomeClass.class_variable` should be highlighted as static, right? (it **cannot** be an instance variable?).

Anyway, it's a complicated problem, you're right :) at least, I learned something today !

**Comment by erictraut** [comment]
@judej, I don't think there's anything more to do here. Python doesn't have a notion of a "static member". It has the notion of class variables, but these can be (and often are) overwritten by instance variables with the same name and type.

**Comment by judej** [comment]
Thanks Eric
