### ISSUE TITLE
intellisense cannot resolve third party modules

### ISSUE THREAD

**Issue by amunger** [microsoft/pylance-release#2085]
Issue Type: <b>Bug</b>

My python 3.10 environment in VS Code shows a warning squiggle for any imported 3rd party module when they are installed for that environment and are available to use in the runtime.
Some modules have intellisense after importing, others do not.

Does not repro for my other Python environment (3.8.8)

![image](https://user-images.githubusercontent.com/2019016/142294883-424aff8d-d853-4227-94fe-7a2eccefae6a.png)

Works fine at runtime:
> & C:/Python310/python.exe c:/repros/test.py
C:\Python310\python.exe

Extension version: 2021.11.2-pre.1
VS Code version: Code - Insiders 1.63.0-insider (d450b04c783dfa6f83dc439017767acccd4e9fac, 2021-11-17T05:21:29.351Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.48GB free)|
|Process Argv|--crash-reporter-id ee1e8284-1ce1-46ae-b666-4982391b0a39|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593cf:30376535
vsc1dst:30396469
vscexrecpromptc:30397557

```

</details>

**Comment by bschnurr** [comment]
Do you have the correct python interpreter selected in VSCode?
R you using Open folder? or Open File ?

**Comment by amunger** [comment]
Running the file in VSCode worked fine, so I assume the interpreter was selected correctly.
I was using Open File, or New File. 
After using open folder with the same file, intellisense works fine and I can no longer get this to repro.
