### ISSUE TITLE
Import "arepl_dump" could not be resolved

### ISSUE THREAD

**Issue by Ratbagdoo** [microsoft/pylance-release#2086]
I literally just got the extension and I'm already confused on what's the issue is and how to fix it.
All I'm getting is: Import "arepl_dump" could not be resolved

**Comment by heejaechang** [comment]
we will need a bit more info to help you. can you provide us a way to repro? or share your project folder structure?

**Comment by Ratbagdoo** [comment]
> we will need a bit more info to help you. can you provide us a way to repro? or share your project folder structure?

here is the file that you requeste
![Screenshot 2021-11-18 125115](https://user-images.githubusercontent.com/58292410/142336728-f842f725-4f2a-44ab-be28-b5d6fcfde63f.png)
d

**Comment by erictraut** [comment]
Please provide the information requested in the issue tracker template.

**Comment by Ratbagdoo** [comment]
No module named 'arepl_dump'
  File "C:\Users\Lenevo\Desktop\python test\test.py", line 1, in <module>
    from arepl_dump import dump

**Comment by erictraut** [comment]
For reference, here's an issue with the information that we're looking for: https://github.com/microsoft/pylance-release/issues/2083

**Comment by Ratbagdoo** [comment]
solved this issue I just didn't require the code in question
