### ISSUE TITLE
SQLAlchemy Session __enter__ and __exit__ methods not being noticed.

### ISSUE THREAD

**Issue by howbazaar** [microsoft/pylance-release#2088]
<h3> Environment data </h3>

-   Language Server version: 2021.11.1
-   OS and version: linux x64
-   Python version: cpython 3.8 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

We have a session builder being used, and a method new_session:
```python
from sqlalchemy.orm import Session
#...
    @staticmethod
    def new_session() -> Session:
        dbm = DBManagerBuilder()
        Session = dbm().get_session()
        return Session()
```
All places in the code where we call this method should be error free:
```python
    with rdb.new_session() as session:
```

<h3> Actual behaviour </h3>

All places in the code where we call this method
```python
    with rdb.new_session() as session:
```
gets red squiggly lines under the `rdb.new_session()` 
```
Object of type "Session" cannot be used with "with" because it does not implement __enter__PylancereportGeneralTypeIssues
Object of type "Session" cannot be used with "with" because it does not implement __exit__PylancereportGeneralTypeIssues
(method) new_session: () -> Session
```
Following the Session definition through, the `__enter__` and `__exit__` methods are clearly there.

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
typeshed-fallback/stdlib/logging/__init__.pyi [fs read 0ms] (28ms)
[FG] binding: /home/tim/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/typeshed-fallback/stdlib/logging/__init__.pyi (6ms)
[FG] parsing: /home/tim/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/bundled/stubs/sqlalchemy/orm/__init__.pyi [fs read 0ms] (2ms)
[FG] binding: /home/tim/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/bundled/stubs/sqlalchemy/orm/__init__.pyi (1ms)
[FG] parsing: /home/tim/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/bundled/stubs/sqlalchemy/orm/session.pyi [fs read 1ms] (13ms)
[FG] binding: /home/tim/.vscode/extensions/ms-python.vscode-pylance-2021.11.1/dist/bundled/stubs/sqlalchemy/orm/session.pyi (3ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange

```

I'm guessing that the stubs being bundled don't specify the enter and exit methods.

**Comment by erictraut** [comment]
Yes, your diagnosis is correct. The bundled stubs don't include `__enter__` or `__exit__` methods in the `Session` class. If you click on `Session` and choose "Go to declaration", you can see the type information that is used here.

**Comment by erictraut** [comment]
I'll also note that the latest published version of [sqlalchemy-stubs](https://github.com/dropbox/sqlalchemy-stubs/blob/81e44ae30f6d13d29be4abbcb76a9d03880bc165/sqlalchemy-stubs/orm/session.pyi#L32) also doesn't include these methods. Perhaps it was a recent addition to the library?

**Comment by erictraut** [comment]
Maintaining compatibility between a library and the corresponding stubs presents a challenge for the Python ecosystem. Our preference and recommendation is that library maintainers include type information (in the form of inlined types or type stubs) as part of their library package. This is the best way to prevent incompatibilities like this. Thankfully, we're seeing that many libraries are now directly incorporating type information!

It helps if consumers of a library express their desire for type information to be included. If this is something you'd like to see for sqlalchemy, perhaps you'd be willing to file an enhancement request in the sqlalchemy repo?

**Comment by howbazaar** [comment]
https://github.com/sqlalchemy/sqlalchemy/blame/958f902b1fc528fed0be550bc573545de47ed854/lib/sqlalchemy/orm/session.py#L1131 says it was added 17 months ago.

**Comment by erictraut** [comment]
I think pylance currently bundles the stubs from `sqlalchemy-stubs`. @judej, could you confirm? If so, then the best way to address this in the short term is to submit a PR to the [sqlalchemy-stubs](https://github.com/dropbox/sqlalchemy-stubs) repo and them incorporate the updated stubs in the next release of pylance.

Longer term, the best answer is for sqlalchemy to ship type information as part of their package.

**Comment by howbazaar** [comment]
Have opened https://github.com/dropbox/sqlalchemy-stubs/pull/231

**Comment by debonte** [comment]
Triage: I think we should close this:
1. I don't see any SQLAlchemy stubs bundled in Pylance.
2. The PR to fix sqlalchemy-stubs has been open and unmerged for 17 months.
3. SQLAlchemy 2.x has better typing support.
