### ISSUE TITLE
[cv2-stubs] cv2.norm function is missing a parameter

### ISSUE THREAD

**Issue by Avasam** [microsoft/pylance-release#2089]
## Environment data

-   Language Server version: v2021.11.1
-   OS and version: 10.0.19043
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Expected behaviour

cv2.norm to have 4 parameters, 2 of which are sources: https://shimat.github.io/opencvsharp_docs/html/aee06fc2-ed07-251e-f8f4-ddcaa239ebfd.htm
`def norm(src1, src2, normType: int, mask=...) -> float:`

## Actual behaviour

cv2.norm is missing a parameter.
It is defined as `def norm(src1, normType=..., mask=...) -> typing.Any:`

## Logs

```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonRunFailedTestsButtonDisplayed' is active
Experiment 'pythonRefreshTestsButtonDisplayed' is active
Experiment 'pythonRememberDebugConfig' is active
> conda info --json
> "C:\Program Files\Python39\python.exe" ~\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\interpreterInfo.py
Python interpreter path: C:\Program Files\Python39\python.exe
Starting Pylance language server.
> conda --version

```

## Code Snippet / Additional information

If applicable, add screenshots or the text of the code (surrounded by triple back ticks) to help explain your problem.
```python
from __future__ import annotations
from typing import Any, TYPE_CHECKING
import cv2
import numpy
if TYPE_CHECKING:
    Image = numpy.ndarray[int, numpy.dtype[Any]]

source1: Image = numpy.array([])
source2: Image = numpy.array([])
mask: Image = numpy.array([])

cv2.norm(source1, source2, cv2.NORM_L2, mask)
```
![image](https://user-images.githubusercontent.com/1350584/142380377-002013ed-958a-40b7-9a75-b8bf0a384ebd.png)

**Comment by judej** [comment]
Thanks for the report. This looks like a typestub issue.

**Comment by Avasam** [comment]
I [made a PR](https://github.com/microsoft/python-type-stubs/pull/112) in microsoft/python-type-stubs. But there's been no acknowledgment in a month.
