### ISSUE TITLE
[Feature Request] Add '=' to args and kwargs when calling a callable object.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#209]
because of [this issue](https://github.com/microsoft/vscode-python/issues/12503) we can only use pylance language server.

but it seems pylance doesn't show '=' for kwargs in calling a function.

![image](https://user-images.githubusercontent.com/26390254/89640787-8e8d4000-d8c5-11ea-9ef0-6d514215750e.png)

in this, we should have 'sep=' suggestion instead of 'sep' suggestion for 'print' function. like jedi and microsoft language server.

![image](https://user-images.githubusercontent.com/26390254/89641116-386ccc80-d8c6-11ea-9721-9bced40fb76a.png)

in this, we have 2 same 'sep' suggestion. one is for defined 'sep' value at line 1. another one is for 'print' kwarg.

**Comment by erictraut** [comment]
Thanks for the suggestion. This will be addressed in the next version of Pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202081-13-august-2020
