### ISSUE TITLE
missing import pdfplumber

### ISSUE THREAD

**Issue by hcharp** [microsoft/pylance-release#2090]
Hi,
I did not find where to report a missing import: pdfplumber seems to be missing.
Thank you
Regards

**Comment by bschnurr** [comment]
I believe this is a error related to your local code base or setup.

If you have the required library installed and have selected the correct python interpreter "Python: Select Interpreter", and still see an issue. please add the output window logs from "Python Language Server".  https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
