### ISSUE TITLE
Site-packages are prefered over the ones in the workspace

### ISSUE THREAD

**Issue by thesadru** [microsoft/pylance-release#2099]
## Environment data

- Language Server version: 2021.11.2
- OS and version: Windows 10
- Python version: 3.9.6

## Expected behaviour

The packages in the current working directory should be preferred over the installed packages. 

## Actual behaviour

If a package is installed in site-packages then that package will be preferred.

## Additional information

Preferring the one in the current workspace is absolutely required for the development of a library as it's pretty normal to have a `tests` directory which should use the package in the cwd instead of the library version you have installed in site-packages.

**Comment by bschnurr** [comment]
Can you provide some more context as to when are are preferring site-packages over local?  ie. are you talking about import quick fixes or completions?

Any simple code examples would help too.

thank you

**Comment by thesadru** [comment]
Say I am developing a library called `requests` and want to add a new function

I have a file `./requests.py` or a module called `./requests/`.
```py
# ./requests.py
def some_function():
    print("Should be visible")
```

I create some tests for this module in the `./test.py` 
```py
# ./test.py
import requests

requests.some_function()
```

Here `requests` is not recognized as my module but as the installed package even though when the module is actually ran everything works as expected.

**Comment by heejaechang** [comment]
it looks like it is fixed in the latest release.

**Comment by thesadru** [comment]
appreciate it
