### ISSUE TITLE
[Feature Request] Add the ability to specify import syntax for different imports

### ISSUE THREAD

**Issue by Jay-Madden** [microsoft/pylance-release#210]
Currently say if you want to type hint a dict or a list etc, and you don't have that import currently pylance will import it for you, however it imports as ```from typing import List```which can get long and tedious. When really I want the autoimport to be 

```import typing as t```

then the autocomplete would be 

```foo: t.List[some_type] = []```

I propose a way to configure different imports to behave in different manners on auto import. This is somewhat similar to #8 however, I am proposing to make it user defined and extensible.

**Comment by savannahostrowski** [comment]
This issue has been open for nearly a year and has not received enough upvotes to prioritize this work. I'm going to close this for now but I'm happy to revisit if we see this becoming a theme in opened issues.
