### ISSUE TITLE
"Extract Variable" do not replace all similar occurrences.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#2101]
## Environment data
Build of Visual Studio Code - Insiders: 1.63.0-insider (user setup)  
Build of python-insider: v2021.12.1482249642-dev
Build of jupyter-insider: v2021.11.1001489384
Build of pylance-insider: v2021.11.2
Build of jupyter Keymap-insider: v1.0.0
Build of jupyter Notebook Renderers-insider: v1.0.3

## Reproduced steps
1. Create a test file and type
```
import math
import extractVar
class Solver:
    def roots(self):
        a = 3
	b = 25
	c = 46
	root1 = (-b + math.sqrt(b ** 2 - 4 * a * c)) / (2 * a)
	root2 = (-b - math.sqrt(b ** 2 - 4 * a * c)) / (2 * a)
        return root1, root2
Solver().demo()
```
2. Select the code "math.sqrt(b ** 2 - 4 * a * c)", right click and select "Extract Variable"
![image](https://user-images.githubusercontent.com/59192491/142963236-13396d98-339b-42d6-85fe-3ed9a8e2908c.png)
3. Re-named the variable as below
![image](https://user-images.githubusercontent.com/59192491/142964327-3e63ea12-6d8a-4422-a2c6-fa760b4a89ab.png)

## Expected behaviour
Check all similar occurrences are replaced

## Actual behaviour
"Extract Variable" do not replace all similar occurrences.
![image](https://user-images.githubusercontent.com/59192491/142964398-d5a5765e-002f-41f5-9ac6-1dee66316334.png)

**Comment by CodeCrazy-ywt** [comment]
But what if this expression changes? For example:
```python
root1 = (-b + math.sqrt(b ** 2 - 4 * a * c)) / (2 * a)
b += 1 # Of course it's impossible in this use case, here's just a sample.
root2 = (-b - math.sqrt(b ** 2 - 4 * a * c)) / (2 * a) # The value of -b - math.sqrt(b ** 2 - 4 * a * c) changes.
```
When both of the occurrences of `-b - math.sqrt(b ** 2 - 4 * a * c)` changes to `delta`, the code will turn into:
```python
delta = -b - math.sqrt(b ** 2 - 4 * a * c)
root1 = (delta) / (2 * a)
b += 1
root2 = (delta) / (2 * a) # Here delta doesn't change.
```

**Comment by bschnurr** [comment]
Thanks for the issue and the corner case

**Comment by rchiodo** [comment]
Moving back to triage, I don't think we'd want to replace all occurrences? Maybe we would.

**Comment by bschnurr** [comment]
for extract variable its safer to not replace all.

closing
