### ISSUE TITLE
Add a `builtins` parameter

### ISSUE THREAD

**Issue by Neyri** [microsoft/pylance-release#2103]
Hello,
I am working on databricks notebooks and I use VScode to edit the content of the notebooks.
I make extensive use of builtin databricks functions such as `dbutils` or `spark`. However I find Pylance raises an *UndefinedVariable* on those functions as they are not locally declared.
I would like to be able to specify some builtins functions that pylance won't raise an undefined error on. I imagine this would be similar to flake8's approach on the subject, see [here](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-builtins)

Even better : I would like to be able to specify a databricks profile where all databricks' builtin functions will be already defined (and autocompletion compatible). But not sure that fits in the philosophy of the package.

**Comment by erictraut** [comment]
Pylance doesn't hard-code the definition of "builtins". Rather, it uses the type information from the `builtins.pyi` stub file from typeshed. You can download your own copy of the typeshed stdlib stubs and use the `python.analysis.typeshedPaths` setting to point to their path. You can then modify your local copy of `builtins.pyi` file and add additional symbols.

**Comment by erictraut** [comment]
We've received this request from a number of users, so I've implemented a less-cumbersome way to extend the builtins namespace. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/builtins.md). This new capability will be included in next week's release of pylance.

**Comment by debonte** [comment]
This issue has been fixed in version 2022.2.1, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202221-9-February-2022)

**Comment by bjtho08** [comment]
So, I have a question about using the builtins.pyi file. In the example from databricks, the builtins are not functions, but actually entire modules with submodules, classes and functions. How would I go about 'mocking' that structure with the builtins.pyi file?

**Comment by erictraut** [comment]
You should be able to import those other modules in `__builtins__.pyi`. To make these modules appear as "re-exported", you'll need to use a redundant form of import.

```python
import foo as foo
```

**Comment by bjtho08** [comment]
> You should be able to import those other modules in __builtins__.pyi.

So if the modules are not actually available outside of the databricks runtime, I would need to write a mock up module with the necessary submodules and classes and then import them into the `__builtins__.pyi`, is that correct?
