### ISSUE TITLE
The Extract Method and Extract Variable keyboard shortcut does not work after setting.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#2104]
### VS Code version

1.63.0-insider (user setup)  

### Extension version

Build of python-insider: v2021.12.1482249642-dev

### OS type

Windows

### OS version

Win10 

### Python distribution

python.org

### Python version

3.9.9

### Language server

Default

### Expected behaviour

The keyboard shortcut working.

### Actual behaviour

The Extract Method and Extract Variable keyboard shortcut does not work. 

### Steps to reproduce

1.  Go to File -> Preferences -> Keyboard Shortcuts [Ctrl+K Ctrl+S]
2.  Assign a keyboard shortcut to the python.refactorExtractVariable command
![image](https://user-images.githubusercontent.com/59192491/142977163-2cafff18-e2ac-40e4-940b-f8504121c50a.png)
![image](https://user-images.githubusercontent.com/59192491/142977181-17451e5f-1378-4981-ba59-4495cc7a6695.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bschnurr** [comment]
the keybinds way doesn't provide any arguments.

```
[Trace - 11:16:58 AM] Sending request 'workspace/executeCommand - (77)'.
Params: {
    "command": "pylance.extractVariable",
    "arguments": []
}
```

maybe need to add shortcut to python refactor

**Comment by bschnurr** [comment]
the shortcut to use is the code action trigger on a selection when its a valid extraction. "ctrl+."

**Comment by bschnurr** [comment]
On further thought.. the is no need for shortcut, because a code action is available on a valid extraction

**Comment by 0xorial** [comment]
I find it a bit lacking to not be able to have a direct shortcut for that since I use it very often. also feels a bit inconsistent to not have a possibility to assign a shortcut.
