### ISSUE TITLE
reportMissingImports 

### ISSUE THREAD

**Issue by MdIbrahimSk** [microsoft/pylance-release#2106]
## Environment data

-   Language Server version: XXX
-   OS and version: windows 11 insiderpreview
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5 (64bit)
- microfoft vscode

## Expected behaviour

<html>
<body>

Diagnostics for imports that have no corresponding imported python file or type stub file.
-- | --

</body>
</html>

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by forinda** [comment]
### Pylance missing imports
One of the reasons why this happens is that
- For instance, if you have ever worked with pycharm it does ask you to select the interpreter and create virtual environment with the selected interpreter. For the same, if you start a project in `visual studio code` It takes the global interpreter as the default interpreter even if you create a virtual environment See this on the bottom left section for the selected interpreter

![pylance1](https://user-images.githubusercontent.com/55891685/143175590-cc0dc7c4-d5eb-42f3-8826-2808911fb087.png)

- So how do you ensure Pylance reads modules installed in the virtual environment created? You need to check for the selected interpreter at the bottom left and if not activated on the virtual environment click on the selected interpreter and vs-code will prompt you to select a default interpreter for the project. Select your current virtual environment and visual studio pylance will read the modules in the current environment. Hope this works for anyone who's struggling with the same

![pylance2](https://user-images.githubusercontent.com/55891685/143175885-f87a8563-9ebf-4b05-a7d0-a2933d9528fe.png)

**Comment by judej** [comment]
Thanks @forinda for the suggestion. @MdIbrahimSk, could you please let us know if this fixes the problem?

**Comment by forinda** [comment]
> Thanks @forinda for the suggestion. @MdIbrahimSk, could you please let us know if this fixes the problem?

This solves the problem
