### ISSUE TITLE
Allow Pylance to detect docker volumes path by default

### ISSUE THREAD

**Issue by MahdiZerara** [microsoft/pylance-release#2108]
Currently, in order for Pylance to detect the python packages installed in a docker volume, one needs to go to Pylance settings and manually add the path that points to docker volumes installed on windows. in my case it is: 

**\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\backend_python_packages\_data**

Is it possible to make Pylance support this by default?  

![image](https://user-images.githubusercontent.com/88960606/143261881-9a03b08d-c57e-49d6-8788-35ad0bab62c3.png)

**Comment by judej** [comment]
Thanks for the report, would you please elaborate on the environment you have set up?
Are you editing a project that is in the docker image? or is it on your local machine and you are trying to include a path that is mapped to a running container? 

Where is the interpreter running?

More details will help triage the issue.
thanks

**Comment by judej** [comment]
closing stale issue
