### ISSUE TITLE
Being able to correctly parse files that are in symlinked folders

### ISSUE THREAD

**Issue by SeeringPhil** [microsoft/pylance-release#211]
## Environment data
-   Language Server version: v2020.8.0
-   OS and version: Windows 10, 2004 -> Ubuntu 20.04 through WSL 2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2 64 bit

## Expected behaviour

When my work folder (here "my_project") contains a symbolic link pointing to another folder, for instance : 

```
-root

--my_project
---tools -> ../my_package/tools

--my_package
---tools
---- ...

```

1. I expect that the extension would not show warnings saying it cannot find the imports
2. I expect to be able to ctrl + click to navigate to the definitions

## Actual behaviour

1. Warnings are shown, see Logs below. 
2. I am unable to ctrl + click to navigate to definitions 

## Logs

```
Import "tools.my_package.config" could not be resolvedPylance (reportMissingImports)
```

After writing the above, I'm not quite sure this is even possible right now for Pylance as I noticed I can correctly open the files using vs code's file explorer, but not with the file-picker (ctrl-p).

**Comment by wesleybl** [comment]
Same problem as https://github.com/microsoft/pylance-release/issues/131

**Comment by jakebailey** [comment]
I'm going to close this in favor of #131 for generic symlink support.
