### ISSUE TITLE
Urgently! Import relevant Issue and Createsuperuserrelevantissue

### ISSUE THREAD

**Issue by abdullahkhanPWD** [microsoft/pylance-release#2115]
Import "django.apps" , "django.contrib" and may be others imports could not be resolved from source [Pylance.](url)
python manage.py createsuperuser this command is also not working.

## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
``
![this2](https://user-images.githubusercontent.com/95150228/143723127-21691f38-bb1f-415c-a60b-08961bbf4356.JPG)
![this3](https://user-images.githubusercontent.com/95150228/143723129-bd27f527-cac2-41a3-8d7b-f7901a5aa607.JPG)
![this4](https://user-images.githubusercontent.com/95150228/143723130-96919f6f-3619-4ecc-b420-d75e54725346.JPG)
![this](https://user-images.githubusercontent.com/95150228/143723131-b3521657-afbf-4d3c-9964-1dc12920a053.JPG)
`

## Code Snippet / Additional information

<!--
Note: If you think a GIF of what is happening would be helpful, consider tools like https://www.cockos.com/licecap/, https://github.com/phw/peek or https://www.screentogif.com/ .
-->

```python
XXX
```

**Comment by judej** [comment]
Thanks for the report. Could you please verify that you are using the right Python virtual environment that has django installed?

**Comment by judej** [comment]
closing stale issue
