### ISSUE TITLE
dropbox installed but showing cannot resolve

### ISSUE THREAD

**Issue by KaranAggarwal2008** [microsoft/pylance-release#2116]
Python version 3.10.0
Installed dropbox but facing issue with imports

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by judej** [comment]
closing stale issue
