### ISSUE TITLE
Associate errors with the start line instead of the end line (Better Syntax Errors as in Python 3.10)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/pylance-release#2118]
## Current behaviour

Write the following code:
```python
print(
1234
```

Error message should be assocated with the line containing `print(`, not error in line `xyz`.
Python 3.10 does a great job here (that's one of the most popular features announced in 3.10, at least from what I've seen when users publish articles about 3.10).

![image](https://user-images.githubusercontent.com/1948812/143941800-b5818053-22d1-4a37-813a-93006c0f53cd.png)

This is crucial for Notebooks as the errors are now associated with the first line of the next cell.
See below

![image](https://user-images.githubusercontent.com/1948812/143942048-b525db3d-4ce3-46c5-bd31-61354c2bb035.png)

Things get even worse if you have markdown cells (see below), as user has no clue what's wrong now.

![image](https://user-images.githubusercontent.com/1948812/143942271-33b06259-d921-4fef-90b0-6f3e9dc71356.png)

## Expected behaviour

Notebook users should not have to look for errors in the preceeding cell and figure out what's wrong (developer tools like LS should hel;p users figure it out). With notebooks users have to go to previous cell and look for errors there.

Syntax Errors should be handled as done in Python 3.10
![image](https://user-images.githubusercontent.com/1948812/143942612-b7f510cf-547e-4ddc-8414-64a89b19886a.png)

Originally reported here https://github.com/microsoft/vscode-jupyter/issues/6556

**Comment by erictraut** [comment]
Thanks for the suggestion. I agree that parse errors involving missing parenthesis are clearer when they're associated with the starting parenthesis.

I've updated all of the parse errors related to parentheses, square brackets and braces (curly brackets) to follow this pattern and use an error message that more closely matches that of the Python 3.10 interpreter.

This change will be included in the next release of pylance.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2021.12.0, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2021120-2-december-2021)
