### ISSUE TITLE
Goto definition goes to dummpy files instead of actual definitions

### ISSUE THREAD

**Issue by iseesaw** [microsoft/pylance-release#2119]
## Environment data

-   Language Server version: 2021.11.2
-   OS and version: Linux hpc-server
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.6

## Expected behaviour
I want to goto definition of `M2M100Tokenizer`, which should be `transformers.models.m2m_100.modeling_m2m_100.py`.
It is alright when I use Jedi.
![2](https://user-images.githubusercontent.com/31267864/144011658-a86997bc-b68a-4f6a-ae46-b156f9ada2ac.jpg)

## Actual behaviour
But it goes to dummpy file (`transformers.utils.dummpy_pt_objects.py`) when I use Pylance.
![1](https://user-images.githubusercontent.com/31267864/144011712-91032da6-feef-4a5e-8b75-e48bef21c84b.jpg)

## Code Snippet / Additional information

The lib is [huggingface/transformers](https://github.com/huggingface/transformers).

**Comment by judej** [comment]
Thanks for the report. Will look into this.

**Comment by bschnurr** [comment]
as a work around this seems to work
```python
from transformers.models.m2m_100 import M2M100Tokenizer
```

**Comment by bschnurr** [comment]
Looks like there is a change in the current dev version of `transformers\__init__.py`  line 2277


Your version dummy_sentencepiece_objects's M2M100Tokenizer is being exported
```
    else:
        from .utils.dummy_sentencepiece_objects import *
```

newer version
```
  else:
        from .utils import dummy_sentencepiece_objects

        _import_structure["utils.dummy_sentencepiece_objects"] = [
            name for name in dir(dummy_sentencepiece_objects) if not name.startswith("_")
        ]
```

**Comment by iseesaw** [comment]
Thanks for your reply.

**Comment by iseesaw** [comment]
Thanks for your reply.

Well, the `__init__.py` file looks like this:
```python
    if is_sentencepiece_available():
        # ...
        from .models.m2m_100 import M2M100Tokenizer
        # ....
    else:
        from .utils.dummy_sentencepiece_objects import *
```

 While `is_sentencepiece_available()` returns `True` in my environment, it should mean that `M2M100Tokenizer` is being exported from `.models.m2m_100` rather than  `dummy_sentencepiece_objects`.

But after I click `Go to definition`, it goes to `utils.dummy_sentencepiece_objects.M2M100Tokenizer` rather than `models.m2m_100.M2M100Tokenizer`?

I'm so confused and Jedi always works well.

**Comment by bschnurr** [comment]
i dont believe pylance knows is_sentencepiece_available() returns true and Jedi does. that is the difference.

**Comment by bschnurr** [comment]
replace the else statement with the newer version and it should work

**Comment by judej** [comment]
closing stale issue
