### ISSUE TITLE
Django model field

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/pylance-release#212]
Hi, I am using django and I here is a bug I encountered, the method `django.contrib.auth.authenticate` returns and instance of `django.contrib.auth.models.AbstarctBaseUser`.

If I check for `user.is_active` pylance claims **Cannot access member "is_active" for type "AbstractBaseUser"** even though it is a defined field on the `AbstractBaseUser` class as shown in the screenshot.

![Screenshot from 2020-08-07 14-34-08](https://user-images.githubusercontent.com/41123800/89677330-40733f00-d8bb-11ea-8a2b-ba1b252d0934.png)

-   Language Server version: pylance (v2020.8.0)
-   OS and version: Ubuntu 20.04 64bit
-   Python version: python 3.8.2 (pyenv, venv)

**Comment by jakebailey** [comment]
You seem to be running Pylance at a type checking level above off. Once type checking is enabled, the stubs are important. In this case, the django stub we include (https://github.com/TypedDjango/django-stubs) does not say AbstractBaseUser has an `is_active` member, and we use the stubs for type checking (not the given code).

**Comment by yankyhoffman** [comment]
I have opened a [Pull request](https://github.com/typeddjango/django-stubs/pull/517) in the [Django Stubs Repo](https://github.com/TypedDjango/django-stubs) with a fix for this issue, and it was merged.

This issue can be closed when the Pylance extension will reflect these commits.

**Comment by jakebailey** [comment]
Thanks for that; I'll get your fix pulled in for tomorrow's release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020110-4-november-2020

**Comment by yankyhoffman** [comment]
Thanks again! I'm happy I was able to help out with this!
