### ISSUE TITLE
Wrong Type from TypeVar and SQLAlchemy

### ISSUE THREAD

**Issue by alexschoeberl** [microsoft/pylance-release#2121]
I am using Pylance 2021.11.2 (pyright b27108d5) with Python 3.8 and SQLAlchemy 1.4 (sqlalchemy[mypy]==1.4.22).

I noticed an issue with type hints:

    from typing import Type, TypeVar
    from sqlalchemy.orm import declarative_base

    Base = declarative_base()

    class X(Base):
        pass

    class Y(Base):
        pass

    MyT = TypeVar("MyT", X, Y)

    def f(foo: Type[MyT]) -> MyT:
        return foo()

    def t():
        a = f(X)

Pylance will always say that a is of the "last" type specified in TypeVar, in this case Y.
How can I work around this issue? Is this a problem with Pylance, SQLAlchemy or my code?

**Comment by erictraut** [comment]
The problem here is that `declarative_base()` returns a class type that is dynamically generated. That means a static type checker cannot reason about it or any type that is derived from it. It's effectively treated like an `Any` type.

The best workaround I can offer is to use a `TYPE_CHECKING` conditional to define a base class that will work for static analysis.

```python
from typing import TYPE_CHECKING, Type, TypeVar
from sqlalchemy.orm import declarative_base

if TYPE_CHECKING:
    class Base: ...
else:
    Base = declarative_base()
```

**Comment by alexschoeberl** [comment]
Thank you for the workaround!

What seems irritating is that the type checker just selects one of X or Y. Even when I manually set `a: X = f(X)`, it still says a is of type Y.

**Comment by debonte** [comment]
> What seems irritating is that the type checker just selects one of X or Y. Even when I manually set `a: X = f(X)`, it still says a is of type Y.

As Eric explained above, dynamic type creation can lead to some confusing/surprising Pyright behaviors. However, this is more graceful than mypy which simply flags the X and Y classes with errors -- "error: Variable "__main__.Base" is not valid as a type"

For what it's worth, it sounds like SQLAlchemy might be moving to a more type checker-friendly approach in the future. See the discussion here -- https://github.com/python/typing/discussions/1020#discussioncomment-1958865
