### ISSUE TITLE
Code is unreachable, although it works just fine - Pylance

### ISSUE THREAD

**Issue by ravilnicki** [microsoft/pylance-release#2126]
### Discussed in https://github.com/microsoft/pylance-release/discussions/2125

<div type='discussions-op-text'>

<sup>Originally posted by **ravilnicki** November 30, 2021</sup>
Hello there, I've noticed something that bothers me.

I have here a simple recursion with memoization calculating fibonacci sequence. Pylance shows a message that one specific line is unreachable but the code works just fine. I don't see any errors in this code, so may it be a bug?

![image](https://user-images.githubusercontent.com/59303785/144128782-d5617f43-c081-4685-89d8-bceeabada288.png)

 </div>

**Comment by erictraut** [comment]
Thanks for the bug report. This is a known issue that we've already fixed. You will see the bug fix appear in the next pylance release, which will probably be tomorrow.

**Comment by ravilnicki** [comment]
Thanks for the info, cheers!
