### ISSUE TITLE
False positive when setting a __tablename__ value in a sqlalchemy model

### ISSUE THREAD

**Issue by deterok** [microsoft/pylance-release#2129]
<h3> Environment data </h3>

-   Language Server version: 2021.11.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

```py
class Test(Base):
    __tablename__ = 'test' # << This code has no any problems
```

<h3> Actual behaviour </h3>

```py
class Test(Base):
    __tablename__ = 'test' # << Expression of type "Literal['test']" cannot be assigned to declared type "declared_attr" "Literal['test']" is incompatible with "declared_attr"
```

<h3> Logs </h3>

Python Language Server Log
```log
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /workspace/myproject/core/test/models.py ...
[BG(1)]   parsing: /workspace/myproject/core/test/models.py (5ms)
[BG(1)]   binding: /workspace/myproject/core/test/models.py (0ms)
[BG(1)]   checking: /workspace/myproject/core/test/models.py (74ms)
[BG(1)] analyzing: /workspace/myproject/core/test/models.py (80ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1638430169428 at /workspace/myproject/core/test/models.py (9ms)
Background analysis message: resumeAnalysis
[BG(1)] indexing: /workspace/myproject/core/test/models.py [found 8] (0ms)
Indexing Done: /workspace/myproject/core/test/models.py
Background analysis message: getDiagnosticsForRange
[FG] parsing: /workspace/myproject/core/test/models.py (1ms)
[FG] binding: /workspace/myproject/core/test/models.py (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

**Comment by erictraut** [comment]
Could you please provide a complete, stand-alone sample? Where does the symbol `Base` come from? I don't see such a symbol exported from the `sqlalchemy` module.

**Comment by deterok** [comment]
Thanks for the waiting, I've a custom Base
```py
from sqlalchemy.ext.declarative import declarative_base, declared_attr


class Base(object):
    @declared_attr
    def __tablename__(cls):
        return cls.__name__.lower()


Base = declarative_base(cls=Base)
```

**Comment by dtiesling** [comment]
Having the same issue. @deterok have you found a workaround?

**Comment by erictraut** [comment]
By default, type checking is disabled in pylance. I presume that you have enabled type checking. 

This isn't a false positive, at least from the perspective of the type checker. The base class declares the class variable `__tablename__` as having the type `declared_attr`, but you're attempting to assign a `str` to it within the subclass. Pylance is correct in pointing out the type violation.

This is analogous to:
```python
class Parent:
    foo: int

class Child(Parent):
    foo = "not an int" # Type violation error
```

I don't know enough about sqlalchemy to offer a suggested workaround. You might want to ask the maintainers of sqlalchemy how this is intended to be used.

**Comment by judej** [comment]
Closing inactive issue
