### ISSUE TITLE
Intellisense, typehints, and subclasses

### ISSUE THREAD

**Issue by shaperilio** [microsoft/pylance-release#2130]
Consider the following code:

```python
class Base:
    def base_method(self):
        pass


class Sub(Base):
    def sub_method(self):
        pass
```

If I declare an instance of `Sub`, Intellisense will properly pick up that it has a `base_method`:
![image](https://user-images.githubusercontent.com/26465923/144481325-559355e6-45f6-40d6-ad14-6c85b212a72d.png)

Now consider we write some function that should accept `Base` or any subclass thereof. My understanding is that `some_function` has the correct typehint:

```python
def some_function(p: Base) -> Base:
    return p
```

Calling `some_function` with a `Sub` instance results in Intellisense not seeing that its return value should have a method called `sub_method`:
![image](https://user-images.githubusercontent.com/26465923/144481384-749e4eca-32e4-4787-9a9d-1f2cb2522e7f.png)

MyPy is not giving me an error so I believe the typehint is correct. Forgive my crude description of what's actually happening, but it seems to me that PyLance sees the typehint and just stops inspecting what the actual parameter `p` is. Thus my typehint actually breaks intellisense because it will never see any of the members of the subclasses.

Let's also write the same function, but without typehints:

```python
def untyped_function(p):
    return p
```

![image](https://user-images.githubusercontent.com/26465923/144481434-1d28ccfe-cfa7-4ef6-9e68-a8cb7add4885.png)

PyLance is now forced to figure out types on its own, so the Intellisense is correct.

This can get hairy as the typehints "trickle down":

```python
class PartiallyTypedContainer:
    def __init__(self, p: Base):
        self._p = p

    @property
    def p(self):
        return self._p
```

![image](https://user-images.githubusercontent.com/26465923/144481470-52efc61b-120d-4bfa-b6de-d5b4b5aae35e.png)

I have this exact situation (in much more complicated code) - I tried to remove typehints so that the Intellisense was correct, but I failed to follow the whole trail. This is, of course, just a work-around and not a proper solution.

If I'm correct that PyLance is "feeding" this information to Intellisense, then I believe the behavior is wrong. Typehints should be ignored by Intellisense as far as showing members while typing is concerned.

Version info:
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
Pylance: v2021.11.2
Python: 3.8.10

**Comment by erictraut** [comment]
The problem here is with your type annotations for `some_function`. The annotations you have provided indicate that the function always returns a value of type `Base`. The type checker therefore cannot assume that it's the same type as the input parameter. For example, this is a legal implementation for that same function:

```python
def some_function(p: Base) -> Base:
    return Base()
```

If your intent is for `some_function` to return a value that is the same type as the input parameter, the correct way to annotate it is as follows:

```python
_T = TypeVar("_T", bound=Base)
def some_function(p: _T) -> _T:
    return p
```

For more details about generic functions and type variables, refer to PEP 484.

When type annotations are provided, pylance honors them according to the typing specs. When annotations are not provided, pylance does its best to infer the intent. That's why you're seeing the desired behavior with the untyped function.

**Comment by shaperilio** [comment]
It seems to get this to work with classes, it's one step more complicated:

```python
class FullyTypedContainer(Generic[_T]):
    def __init__(self, p: _T):
        self._p = p

    @property
    def p(self) -> _T:
        return self._p
```

This is the only way I've found to get the Intellisense to show properly when doing:

```python
c = FullyTypedContainer(Sub())
# c.d. <-- Intellisense shows the `sub_method` as desired
```

This seems like a whole lot of work to just say "this or a subclass thereof". Is this correct?

**Comment by erictraut** [comment]
Yes, you got it! Generic type support was added to the language specifically to handle cases like this.

**Comment by shaperilio** [comment]
Thanks @erictraut for the help!
