### ISSUE TITLE
why pylance is not picking a path if I am adding a path explicitly using sys module in my script

### ISSUE THREAD

**Issue by Agent-Hellboy** [microsoft/pylance-release#2132]
We are adding path to our script explicity using 
```sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), "../..")))```
common_util is present in this directory but pylance is showing this as a problem 
![image](https://user-images.githubusercontent.com/31388347/144559911-3009e2c9-94cd-4aae-8457-59020068b469.png)

**Comment by bschnurr** [comment]
Pylance does not support dynamic at-runtime modifications to sys.path like this; you can emulate it by providing "python.analysis.extraPaths": ["add path here"].

**Comment by Agent-Hellboy** [comment]
why can't we do it automatically?

**Comment by erictraut** [comment]
Pylance is a static analyzer. It doesn't execute the code dynamically. Executing code loaded in your code editor would be unsafe in general. When your code dynamically manipulates import search paths, static analysis tools like pylance do not know about these manipulations. If you can avoid dynamic import search path modifications, that's generally recommended. If that's not feasible and you need to do runtime manipulation of search paths, pylance provides the `python.analysis.extraPaths` setting so you can tell it about these additional paths.

**Comment by Agent-Hellboy** [comment]
got it, thanks.
