### ISSUE TITLE
Release 2021.12.0 not published?

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#2134]
I saw that a release for [2021.12.0](https://github.com/microsoft/pylance-release/releases/tag/2021.12.0) was added yesterday. Is it possible that it wasn't uploaded to the VSCode marketplace? So far I've been unable to download it. The version history doesn't mention it either.

https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

**Comment by bschnurr** [comment]
You are correct. the pipeline failed. thank you.

**Comment by bschnurr** [comment]
Updated thanks again!
