### ISSUE TITLE
Ignoring *.ipynb files does not work

### ISSUE THREAD

**Issue by taldcroft** [microsoft/pylance-release#2135]
**Describe the bug**
Here is my `pyrightconfig.json` file:
```
{
  "ignore": [
    "**/commands_archive.py",
    "**/*.ipynb"
  ]
}
```

I confirmed that the `commands_archive.py` is ignored (as expected) by introducing an error in that file and noting that the error is not reported. However, the Jupyter notebooks in my project are not ignored and generate a large number of errors:

<img src="https://user-images.githubusercontent.com/348089/144598140-504f0507-5176-46a6-85ca-ec39dfb35b8f.png" width=400>

**To Reproduce**
Using VS code, create a Jupyter notebook and include that `pyrightconfig.json` in the project.

**Expected behavior**
No Pylance / pyright errors should be reported for any file named `*.ipynb`.

**VS Code extension or command-line**
Running as a VS Code extension Pyright version v1.1.192.

**Comment by taldcroft** [comment]
@erictraut - ah ok, that makes sense. Thanks for clarifying this and I'll be hoping for a fix in pylance.

**Comment by heejaechang** [comment]
@judej we should discuss whether we should consider ipynb (opened in vscode) as something affected by pyrightconfig or mspythonconfig.json

**Comment by debonte** [comment]
Still doesn't work with LSP notebooks because each cell is treated as its own file and those "fake" cell paths have additional data after the `.ipynb` extension.

While waiting for a fix you could work around this issue by ignoring ` "**/*.ipynb*"` instead.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.8.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022851-31-august-2022-prerelease)

**Comment by sliedes** [comment]
Don't you think there's still a bug in needing that `*`in `*.ipynb*`? This seems incredibly hard to discover and I don't know if it's documented anywhere besides issue comments.

**Comment by rchiodo** [comment]
We could special case any ignores with *.ipynb and change them internally. I'm guessing that's a common pattern and people expect it to work. 

I'll enter an enhancement request.
