### ISSUE TITLE
Spaces around assignment equals sign

### ISSUE THREAD

**Issue by jdwk** [microsoft/pylance-release#2136]
I am somewhat new to Python and VS Code but I read through PEP8 and it suggests using a single space around the equals sign in an assignment.  e.g.  variable = 'some string'
However when pylance suggests assignment arguments to a method, for instance, when typing
parser = argparse.ArgumentParser(description='some description')
It puts no spaces around the equals sign.

Is it possible to configure pylance to automatically create spaces around the assignment operator?

**Comment by erictraut** [comment]
PEP 8 says that spaces shouldn't be used when assigning a keyword argument, as in `description='some description'` in your example above. Here's the exact quote:

> Don't use spaces around the = sign when used to indicate a keyword argument

So pylance is following the standard conventions in Python here.

**Comment by jdwk** [comment]
Thanks, missed that.
