### ISSUE TITLE
Error message for `__all__` operations

### ISSUE THREAD

**Issue by r-priyam** [microsoft/pylance-release#2137]
## Environment data

-   Language Server version: v2021.12.1-pre.1
-   OS and version: Windows 11 Home Single Language 22000.348
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.9

## Expected behaviour

Shouldn't error with the `__all__` operations.

## Code Snippet / Additional information

`test.py`
```py
class AllBug:
    ...
```
`__init__.py`
```py
from test import *

__all__ = (AllBug) # errors here
```
Error message - Operation on "__all__" is not supported, so exported symbol list may be incorrect

**Comment by r-priyam** [comment]
It appears that this was fixed previously in [this release of pyright](https://github.com/microsoft/pyright/releases/tag/1.1.129) #4

**Comment by erictraut** [comment]
This is an incorrect usage of `__all__`. You need to assign a tuple or list of symbol names, not actual symbols. You can fix this bug by changing your code above to one of the following:

```python
__all__ = ("AllBug",)
```

or

```python
__all__ = ["AllBug"]
```

**Comment by r-priyam** [comment]
Sorry and thanks eric

**Comment by mangelozzi** [comment]
> This is an incorrect usage of `__all__`. You need to assign a tuple or list of symbol names, not actual symbols. You can fix this bug by changing your code above to one of the following:
> 
> ```python
> __all__ = ("AllBug",)
> ```
> 
> or
> 
> ```python
> __all__ = ["AllBug"]
> ```

I get the same error even though it is a tuple (also tried a list same error):
![image](https://user-images.githubusercontent.com/19764314/156920285-06899dd3-0c3e-4394-978c-32508eca2804.png)

**Comment by erictraut** [comment]
You need to include a list of strings in the tuple, as in `__all__ = ("DevHw", )`. Your code is including a list of symbol references, not strings.

**Comment by mangelozzi** [comment]
> You need to include a list of strings in the tuple, as in `__all__ = ("DevHw", )`. Your code is including a list of symbol references, not strings.

Oh my goodness sorry about that, I kept checking and couldnt see the difference, thank you.

**Comment by xeroc** [comment]
Funny how this works:
```python
import abc


class AbstractTradingStrategy(abc.ABC):
    pass


__all__ = ["AbstractTradingStrategy"]

```

but this fails:

```python
import abc


class AbstractTradingStrategy(abc.ABC):
    pass


__all__ = [AbstractTradingStrategy.__name__]    ## WARNING HERE!
```

**Comment by erictraut** [comment]
@xeroc, that's correct. The first example is supported by type checkers and the second is not. Refer to [this documentation](https://microsoft.github.io/pyright/#/typed-libraries?id=library-interface) for a full list of supported expression forms supported for `__all__`.

**Comment by xeroc** [comment]
> @xeroc, that's correct. The first example is supported by type checkers and the second is not. Refer to [this documentation](https://microsoft.github.io/pyright/#/typed-libraries?id=library-interface) for a full list of supported expression forms supported for `__all__`.

Thanks for the explanation and the link.
Do you have a proposal how I should do do this when using autoflake? It remives unused imports. So either i use .__name__, then the import is used, or i have to eun an assert on all imports. I prefer .__name__, as its cleaner code.

**Comment by xeroc** [comment]
Thanks for pointing me to the right direction. Turns out autoflake has a parameter for that already:
https://github.com/PyCQA/autoflake/issues/35

Sorry for bothering you for nothing.

**Comment by fcole90** [comment]
I think this might need to be re-opened, or perhaps discussed at least, I got this issue on stubs generated by pyright itself 😬 

This is the stub:

```pyi
"""
This type stub file was generated by pyright.
"""

from . import _ffmpeg, _filters, _probe, _run, _view, nodes
from .nodes import *
from ._ffmpeg import *
from ._filters import *
from ._probe import *
from ._run import *
from ._view import *

__all__ = (nodes.__all__ + _ffmpeg.__all__ + _probe.__all__ + _run.__all__ + _view.__all__ + _filters.__all__)
```

```
Operation on "__all__" is not supported, so exported symbol list may be incorrectPylance[reportUnsupportedDunderAll](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportUnsupportedDunderAll.md)
(module) _filters
This type stub file was generated by pyright.
```

Each of the `__all__` is defined as `__all__: list[str]`, so, I'm not sure what's complaining about here 🤔 

![Image](https://github.com/user-attachments/assets/d5987866-67df-4bd3-9a35-04dc87c77b56)
![Image](https://github.com/user-attachments/assets/9ef47a7c-bb37-454d-b69b-adf91f88c3ba)
![Image](https://github.com/user-attachments/assets/109f292a-723d-45ac-9369-a69b675da1d4)

**Comment by erictraut** [comment]
@fcole90, a stub generated by pyright should be considered a "first draft". Generated stubs often require manual edits before they can be used. See [this documentation](https://microsoft.github.io/pyright/#/type-stubs?id=generating-type-stubs) for details.

In this case, the `__all__` definition provided by the library is not compatible with the list of forms supported by static analysis tools. For details, refer to [this section of the Python typing spec](https://typing.python.org/en/latest/spec/distributing.html#library-interface-public-and-private-symbols). This is an example of something you'll need to clean up manually to make the stub usable.

**Comment by fcole90** [comment]
> a stub generated by pyright should be considered a "first draft". Generated stubs often require manual edits before they can be used. See [this documentation](https://microsoft.github.io/pyright/#/type-stubs?id=generating-type-stubs) for details.

Ok, I had indeed the assumption that even being a first draft, such things were going to be ready, thanks for the clarification 😊 

> In this case, the `__all__` definition provided by the library is not compatible with the list of forms supported by static analysis tools. For details, refer to [this section of the Python typing spec](https://typing.python.org/en/latest/spec/distributing.html#library-interface-public-and-private-symbols). This is an example of something you'll need to clean up manually to make the stub usable.

Mmh, so in this case I should not "compute" the list, merging the lists, but instead write it myself, correct?

As, the error happens whenever I have anything more complex than just a liter list of strings 🤔 

```
__all__ = []  # Works!

```

```
__all__ = [] + []  # Operation on "__all__" is not supported, so exported symbol list may be incorrectPylance[reportUnsupportedDunderAll](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportUnsupportedDunderAll.md)
^^^^^^^^^^^^^^^^^
```

So, rather than not being compatible with the library, it seems the only thing one can do is assign a list of strings, that must also be present in the module 🤔 Am I reading this correctly? 😊 

So, copy the content of `(nodes.__all__ + _ffmpeg.__all__ + _probe.__all__ + _run.__all__ + _view.__all__ + _filters.__all__)` and manually merge it myself, right? 😊 

```
__all__ = ["input", "output"]  # OK
```

```
__all__ = ["input"] + ["output"]  # Operation on "__all__" is not supported, so exported symbol list may be incorrectPylance[reportUnsupportedDunderAll](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportUnsupportedDunderAll.md)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by fcole90** [comment]
Ah no sorry, I missed the `extend` and other such options 😊 Thanks again 😊

**Comment by fcole90** [comment]
In case it's useful to anyone, this is how I fixed it 😊 

```
"""
This type stub file was generated by pyright.
"""pyi
from . import _ffmpeg, _filters, _probe, _run, _view, nodes
from .nodes import *
from ._ffmpeg import *
from ._filters import *
from ._probe import *
from ._run import *
from ._view import *

__all__: list[str] = []
__all__ += nodes.__all__
__all__ += _ffmpeg.__all__
__all__ += _probe.__all__
__all__ += _run.__all__
__all__ += _view.__all__
__all__ += nodes.__all__
__all__ += _filters.__all__

```
