### ISSUE TITLE
[Bug] Pylance doesn't show suggestions for functions and some types like NoneType.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#214]
## Environment data

-   Language Server version: 2020.8.0
-   OS and version: Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7

## Actualbehaviour

```python
def x(): pass
x.
```
after i entered `.` the suggestion panel should open for `x` function. but it seems not working on pylance.
i tested with jedi and it worked.

**Comment by erictraut** [comment]
What suggestions would you expect to see in your example above? `x` is a function, so what members would you expect it to have? Likewise, if `x` was `None`, what would you expect for suggestions?

**Comment by byehack** [comment]
look at jedi:

![image](https://user-images.githubusercontent.com/26390254/89708633-0757cf00-d98e-11ea-952f-f96b51526d47.png)

**Comment by erictraut** [comment]
And you find this useful?

**Comment by byehack** [comment]
yes. like when we wanna use __doc__ of a function.

> And you find this useful?

**Comment by erictraut** [comment]
This will be addressed in the next version of Pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202081-13-august-2020
