### ISSUE TITLE
All Pallets Projects stubs have been removed from typeshed and pyright

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#2141]
A couple days ago, type stubs for several popular packages were removed from typeshed. These include Flask, Werkzeug, Jinja, Click, ItsDangerous, and MarkupSafe. The maintainer of these libraries apparently requested that they be removed from typeshed because they are now shipping their own since May 2021. 
 
Here's the commit if you're interested in the details: https://github.com/python/typeshed/commit/8542b3518a36313af57b13227996168e592fe868
 
Eric [updated the typeshed stubs in pyright](https://github.com/microsoft/pyright/commit/47c6a4e3299a20f1988b7fd5352bf6a0199667c1), which means that this change will be reflected in pyright. This could be an issue for pylance. We may want to consider shipping these stubs with pylance. Either that, or we'll need to tell pylance users that they should download the latest versions of these packages that contain type information.
 
Also, it appears that these libraries are now "py.typed", but their types are incomplete. For example, "jinja2" has a type completeness score of only 69.5% and flask is 53.9%. We may need to work with the maintainers of these libraries to improve the type information.

**Comment by judej** [comment]
At this point. I expect users will use the latest and hopefully, the Pallets folks will continue to improve their stubs. I'd prefer that we don't ship the stubs ourselves. Please reopen if you think we should ship them.
