### ISSUE TITLE
Inheritance and override

### ISSUE THREAD

**Issue by SarahLightBourne** [microsoft/pylance-release#2144]
When I create an inherited class, I can't see methods and fields of its parent. Also, when I override some methods, it shows nothing.

  Please, add a more comfortable way to work with inheritance🙏🏻

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by CodeCrazy-ywt** [comment]
> When I create an inherited class, I can't see methods and fields of its parent. Also, when I override some methods, it shows nothing.
> 
>   Please, add a more comfortable way to work with inheritance🙏🏻

for example?

**Comment by heejaechang** [comment]
@SarahLightBourne I just tried it and it works as expected. can you reopen the issue if you have repro steps we can follow to see the issue?
