### ISSUE TITLE
Pylance intellisense not working properly with Python submodules

### ISSUE THREAD

**Issue by mradmila** [microsoft/pylance-release#2145]
-   VSCode: 1.62.3
-   Pylance extension: v2021.12.0
-   Language Server version: Pylance language server 2021.12.0 (pyright acfc919d
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.9 (plain Python)

## Expected behaviour

Python submodules (subfolders with __init__.py) should participate in Intellisense completions (show up after typing . in the containing folder/module).

## Actual behaviour

Completions show while typing import statement (import foo.*), but not when typing afterwards.

## Logs

Since this is a trivial repro, I will elide collection of logs. Here's the directory structure:
```
./foo
./foo/bar
./foo/bar/baz
./foo/bar/baz/__init__.py
./foo/bar/__init__.py
./foo/__init__.py
./test.py
```

## Code Snippet / Additional information

Notice how bar and baz are showing as completions while doing the first (import) statement. Notice how they don't show when typing the second statement. This used to work properly in VSCode, and works properly today in PyCharm.
```python
import foo.bar.baz as bz
import foo

foo.
```

Completion only shows FooClass, which is in __init__.py, but not bar, which is a submodule.

**Comment by erictraut** [comment]
The current behavior is intended. If you want to access `foo.bar` you should import it directly, not rely on side effects of other imports. You can do so by using the statement `import foo.bar` or `import foo.bar.baz`.
