### ISSUE TITLE
Please revert the change of symbol resolution

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#2147]
I'm talking about this one:
> Behavior Change: Modified symbol resolution involving a quoted (forward-declared) type annotation that references a symbol in  the global (module) or builtins namespaces. The previous implementation didn't match the runtime behavior of typing.get_type_hints.

I don't think `typing.get_type_hints` is doing right, because it raises with inner classes using quoted annotations, and the behavior doesn't match that using unquoted annotations:
```python
from __future__ import annotations

from typing import get_type_hints

class Outer:
    class Inner: pass
    def work(self) -> Inner: pass

get_type_hints(Outer.work)  # Raises
```

Without the import of `annotations`, the code works:
```python
from typing import get_type_hints

class Outer:
    class Inner: pass
    def work(self) -> Inner: pass

get_type_hints(Outer.work)  # Returns
```

Of course, we can make it work with fully qualified types:
```python
from __future__ import annotations

from typing import get_type_hints

class Outer:
    class Inner: pass
    def work(self) -> Outer.Inner: pass

get_type_hints(Outer.work)  # Returns
```

After all, I'd like to say that fully qualified types should be mandatory for a full match with the behavior of `get_type_hints`, but I don't think we have to go this far.

**Comment by erictraut** [comment]
Can you provide an example of where this change is causing a problem for you? From the perspective of a type checker, the behavior of all three samples above work today, as they did prior to the recent change. The change was intended to more closely match the behavior of `get_type_hints`. The new behavior also appears to be consistent with mypy's behavior. So we'd need a compelling reason to revert.

**Comment by Azureblade3808** [comment]
I was trying to write a Python version of [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift), and was stucked at the very beginning. Below is what I got so far.

<details>
<summary>/reactive/__init__.py</summary>

```python
from ._reactive import *
from ._reactive_extensions_provider import *
```

</details>

<details>
<summary>/reactive/_reactive.py</summary>

```python
from __future__ import annotations

from typing import Final, Generic, TypeVar


__all__: Final = ["Reactive"]


_Base_co = TypeVar("_Base_co", covariant=True)


class Reactive(Generic[_Base_co]):
    """
    A proxy which hosts reactive extensions of `Base`.
    """

    base: Final[_Base_co]
    """
    The `Base` instance the extensions would be invoked with.
    """

    def __init__(self, base: _Base_co) -> None:
        """
        Construct a proxy.

        Parameters
        ----------
        base
            The object to be proxied.
        """

        self.base = base
```

</details>

<details>
<summary>/reactive/_reactive_extensions_provider.py</summary>

```python
from __future__ import annotations

from typing import Final, TypeVar

from typing_extensions import TypeAlias

from ._reactive import Reactive


__all__: Final = ["ReactiveExtensionsProvider"]


_Reactive: TypeAlias = Reactive


_Self_t = TypeVar("_Self_t", bound="ReactiveExtensionsProvider")


class ReactiveExtensionsProvider:
    Reactive: TypeAlias = _Reactive
    """
    A proxy which hosts static reactive extensions for the type of `self`.
    """

    @property
    def reactive(self: _Self_t) -> Reactive[_Self_t]:
        """
        A proxy which hosts reactive extensions for `self`.
        """

        return self.Reactive(self)
```

</details>

And a sample file for manually validating the static types.

<details>
<summary>/reactive/_usage_sample.py</summary>

```python
from __future__ import annotations

from typing import Final, TypeVar

from . import *


__all__: Final = []


_Base_co = TypeVar("_Base_co", bound="Something", covariant=True)

_Self_t = TypeVar("_Self_t", bound="Something")


class Something(ReactiveExtensionsProvider):
    class Reactive(ReactiveExtensionsProvider.Reactive[_Base_co]):
        static_value: int = 0

        @property
        def value(self) -> str:
            ...

    @property
    def reactive(self: _Self_t) -> Reactive[_Self_t]:
        return self.Reactive(self)


static_value = Something.Reactive.static_value  # type should be `int`
something = Something()  # type should be `Something`
reactive = something.reactive  # type should be `Something.Reactive`
value = reactive.value  # type should be `str`
```

</details>

First, let me make some explanation:

- `Reactive` serves as a base class of all reactive proxies, whereas `something.reactive.somevalue` is supposed to be a reactive signal of `something.somevalue` (which is not implemented yet in my code).
- A subclass of `ReactiveExtensionsProvider` provides `reactive` to be the reactive proxy of its instance, and the result type is normally a true subclass of the basic `Reactive`.

Now, let's see what the problems are:

1. On the declaration line of  `ReactiveExtensionsProvider.reactive`, the result type `Reactive` is not `ReactiveExtensionsProvider.Reactive` but the `reactive.Reactive` (see the difference in hovering message). And there is no way to make it `ReactiveExtensionsProvider.Reactive` as long as there is an import of `reactive.Reactive` unaliased.
2. In the sample file, accessing `something.reactive.value` gets a warning, because type of `something.reactive` is not `Something.Reactive` but `reactive.Reactive`, for there is a wildcard import from `reactive`.

Technically, the two problems are just of one root cause. There may be ways to get around (for example, using a aliased import), but the code will become unintuitive in my opinion.

**Comment by Azureblade3808** [comment]
And I don't think it's correct to call `get_type_hints` without a `localns` argument.

If we call `get_type_hints(SomeClass.some_method, localns=SomeClass.__dict__)`, the result should be the same no matter whether the class is written with quoted or unquoted annotations, and it should match the previous behavior of Pylance's type resolution.

**Comment by erictraut** [comment]
Pyright's new behavior is not only more consistent with `get_type_hints`, it's also now consistent with mypy's behavior in this case. The old behavior wasn't. So I don't think it makes sense to revert this change. You'll need to update your code to avoid the namespace collision and accommodate the new behavior.

**Comment by Azureblade3808** [comment]
https://mypy-play.net/?mypy=master&python=3.10&gist=00ab8574876312dd2f7cf5504e44ac4c

Interestingly, I didn't see mypy do this, with both the latest stable version (0.910) or the master version.

**Comment by Azureblade3808** [comment]
I've finished reading PEP-563 and I have to agree that my sample code violates some rules written in it.

Closing.
