### ISSUE TITLE
F2 refactoring is adding unexpected new lines everywhere

### ISSUE THREAD

**Issue by volksvagen** [microsoft/pylance-release#2148]
### VS Code version

Version: 1.62.3 (system setup) Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247 Date: 2021-11-17T08:11:14.551Z Electron: 13.5.2 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Extension version

v2021.11.1422169775

### OS type

Windows

### OS version

Windows 10

### Python distribution

python.org

### Python version

3.10.0

### Language server

Default

### Expected behaviour

F2 refactoring should only replace involving strings, leaving nothing else untouched.

### Actual behaviour

F2 refactoring is ok, but the refactoring action is adding unexpected new lines everywhere.

### Steps to reproduce

1. write a python function
2. call the function somewhere else
3. click the function name in the definition position, press F2, rename the functiion by entering a new function name
4. press enter to carry out the refactoring
5. check the whole python file, there is a new line added after each single line in the file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by debonte** [comment]
Thanks for the report. This isn't reproing for us, can you provide a more concrete repro? For example, are you using Jedi, Pylance, Pyright?

**Comment by erictraut** [comment]
I was able to repro the problem by creating a new "Untitled" file and manually changing it to "Python" without saving it. I then followed the above instructions. @volksvagen, does that match the steps you took when you initially observed the problem? I'm not able to repro the problem when the source file is on disk (stored as a ".py" or ".pyi" file).

**Comment by volksvagen** [comment]
Hi @debonte 

I am not using Jedi, Pylance, Pyright, and have tried disabling all installed extensions except for python extension, the problem persists, under both saved and unsaved circumstances.

B.T.W, my python interpreter is a local one, version is latest python 3.10.0, autopep8 1.6.0

**Comment by volksvagen** [comment]
Good day @erictraut 

I have tried disabling all installed extensions except for python extension, the problem persists, under both saved and unsaved circumstances.

B.T.W, my python interpreter is a local one, version is latest python 3.10.0, autopep8 1.6.0

**Comment by volksvagen** [comment]
Sorry guys, I just checked that this IS not the right place to report this issue, it is a problem about the Python extension. My bad.

You may close the issue now.
