### ISSUE TITLE
Pylance infers types of zip objects wrongly / needlessly unspecific

### ISSUE THREAD

**Issue by from-nowhere** [microsoft/pylance-release#2153]
<h3> Environment data </h3>

-   Language Server version: 2021.12.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] on win32
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

I have a number of pairs (tuples) all of the same known type -- say `tuple[int, str]` -- that I pass as arguments to the `zip` function. Since this function merges elements from all tuples together, the type of the output is precisely known -- it should be `tuple[tuple[int, ...], tuple[str, ...]]`:

```python
ints_and_strs = tuple((i, str(i)) for i in range(5))

zipped = tuple(zip(*ints_and_strs))

ints, strs = zip(*ints_and_strs)
```
Here, `zipped` has type `tuple[tuple[int, ...], tuple[str, ...]]`, `ints` has type `tuple[int, ...]` and `strs` has type `tuple[str, ...]`.

<h3> Actual behaviour </h3>

The inferred type of the zip is `tuple[tuple[int | str], ...]` (i.e. a tuple of union types), which is less specific than expected. By the [type inference rules for tuples](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#tuple-expressions), the inferred type of a tuple's element should be as specific as possible.

```python
ints_and_strs = tuple((i, str(i)) for i in range(5))

# Expected types are tuple[int, ...] and tuple[str, ...]
# Inferred types are both tuple[int | str]
ints, strs = zip(*ints_and_strs)
```
If the zip object is unpacked, the inferred types are not imprecise but actually wrong: the inferred types of `ints` and `strs` in the code example above are both `tuple[int | str]` (tuples of length `1`) when the actual tuples are clearly of length `5`.

This seems to be an issue only in the case that the arguments to `zip` each have elements of several different types -- it works if the arguments to `zip` are homogeneous tuples:

```python
tuple_of_ints = tuple(range(5))  # inferred type: tuple[int, ...]
tuple_of_strs = tuple(str(i) for i in range(5))  # inferred type: tuple[str, ...]

y = tuple(zip(tuple_of_ints, tuple_of_strs))  # inferred type is tuple[tuple[int, str], ...] -- correct
```

<h3> Code Snippet / Additional information </h3>

```python
ints_and_strs = tuple((i, str(i)) for i in range(5))  # inferred type is tuple[tuple[int, str], ...] -- correct

# Expected type of `zipped`: tuple[tuple[int, ...], tuple[str, ...]]
zipped = tuple(zip(*ints_and_strs))  # inferred type is tuple[tuple[int | str], ...] -- incorrect

# Expected types should be tuple[int, ...] and tuple[str, ...]
# Inferred types are both tuple[int | str], which is wrong
ints, strs = zip(*ints_and_strs)

# It's unrelated to the * operator: the following does not work either
t0 = ints_and_strs[0]  # inferred type is tuple[int, str] -- correct
t1 = ints_and_strs[1]  # inferred type is tuple[int, str] -- correct

fixed_zipped = tuple(zip(t0, t1))  # inferred type is again tuple[tuple[int|str, int|str], ...]
```

**Comment by erictraut** [comment]
The "type inference rules for tuples" apply only to tuple statements such as `(1, )` or `(x, y, z)`. Your sample doesn't contain any tuple statements, so these inference rules don't apply here. Your sample uses function calls (to the `tuple` constructor, the `zip` call, etc.), so Pylance is applying the normal type rules for functions. These rules are dictated by PEP 484.

If you select `zip` and choose `Go To Definition`, you will see how it is defined in `builtins.pyi`. It uses `Iterable` parameter types. The type `tuple[int, str]` is a subtype of `Iterable[int | str]`. That's why you're seeing these results. The positional nature tuple elements is lost because of the `Iterable`.

Unfortunately, I don't see much that can be done here. Perhaps the `zip` type definitions in the typeshed stub could be expanded to include overloads specifically for tuples, but that's something you'd need to discuss with the maintainers of typeshed.

**Comment by from-nowhere** [comment]
I see your point, thank you for the detailed explanation.

To me at least it is far from obvious how a `zip` overload for generic tuples would be expressed in the current typing syntax (and adding different overloads for several tuple types and numbers of arguments to `zip` seems very wasteful). This feels like it would be better solved by an extension to the type inference logic itself.

For posterity: explicitly typecasting e.g. `ints = typing.cast(tuple[int, ...], ints)` makes both pylance and me happy:)
