### ISSUE TITLE
Can't resolve absolute import of module stubs

### ISSUE THREAD

**Issue by itsadok** [microsoft/pylance-release#2158]
**Describe the bug**
Absolute imports of a module that is only available as a stub gets reported as "could not be resolved", whereas a relative import succeeds.
This is especially critical when the stubbed module is a top-level module, which cannot be relatively imported.

**To Reproduce**

```bash
$ mkdir /tmp/project
$ cd /tmp/project
$ mkdir pkg
$ touch pkg/module.pyi
$ echo "import pkg.module" > test.py
$ pyright test.py
...
  /tmp/project/test.py:1:8 - warning: Import "pkg.module" could not be resolved from source (reportMissingModuleSource)
0 errors, 1 warning, 0 infos
Completed in 0.837sec
$ echo "from pkg import module" > test.py
$ pyright test.py
...
0 errors, 0 warnings, 0 infos
Completed in 0.75sec
$ python --version
Python 3.9.5
$ pyright --version
pyright 1.1.194
```

**Expected behavior**
At the very least, the behavior should be consistent between the different ways to import the same module.

If I rename `module.pyi` to `module.py`, this warning goes away. 

I'm using venv and running on ubuntu 21.04, if that makes any difference.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.3.3, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202233-23-March-2022)
