### ISSUE TITLE
Import Suggestion Not Working As Expected

### ISSUE THREAD

**Issue by ac50934** [microsoft/pylance-release#2159]
Issue Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual Behaviour

When typing a Python class that is somewhere in my `extraPaths`, it does not suggest an automatic import as I would expect.

Import suggestions work fine for modules that are already imported. Ex: If I have already import `from payments.models import PaymentMethod`, it will suggest import `payments.models.PaymentIntent` if I type `PaymentIntent`. But a model from a completely different module, say `users.models`, will not be suggested if I start typing `User`.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: false
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2021.12.1
VS Code version: Code 1.63.0 (Universal) (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 70c8b375-d874-4c3a-b4db-84d518c23a12|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
vsena315cf:30406436
pythonvs932:30410667
vscop804:30404766
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t1:30407762

```

</details>

**Comment by shanewazabbas** [comment]
I am also having issues with import suggestions. Not sure what changes have been made recently but it's not able to look at the installed packages and suggest those modules. However, once I open up that module then it's able to suggest that module for import. So clearly it's doing some sort of lazy loaded analysis. Really would like it if this can be fixed soon because it's a huge productivity loss.

**Comment by judej** [comment]
Could you try turning on indexing and seeing if that fixes it?  You can turn on indexing by adding the following in the settings file

` "python.analysis.indexing":true,`

**Comment by ac50934** [comment]
Thanks for your response @judej - I tried adding that into my `settings.json` but in fact it made it worse :( It wouldn't even suggest imports for other classes in already-imported files

**Comment by ac50934** [comment]
To add some more detail:

It seems like the indexing is not file-specific, but rather session-specific. For example, if I import `from payments.models` in one file, then I start to get auto-suggestions for classes from `payments.models` all over my workspace. But, if I reload the window, then its like all the indices are "cleared" (I get no auto-suggestions until I explicitly import that module/file again).

**Comment by shanewazabbas** [comment]
Is it always the case, that import suggestions wont work, until you open that file up at least once. Because when I try settings like these: `python.analysis.extraPaths` and `python.autoComplete.extraPaths`, they seem to have no impact.

**Comment by heejaechang** [comment]
@shanewazabbas can I see your settings? it sounds like "python.analysis.indexing" didn't have any impact.

**Comment by nmoya** [comment]
> Could you try turning on indexing and seeing if that fixes it? You can turn on indexing by adding the following in the settings file
> 
> ` "python.analysis.indexing":true,`

Enabling indexing worked for me! The indexing configuration line looks deprecated (light color), but auto imports started to work again.

**Comment by nagromLobo** [comment]
It looks like a single user (not the user that reported the bug) has reported that enabling this (undocumented?) option has fixed it for them. This is still broken for me, and I can't find a way to fix this. Did something change on how pylance resolves imports recently? I'm not sure I see the reasoning on why this issue was closed?

**Comment by thethiny** [comment]
This broke for me on multiple PCs during the past couple of months. It was working perfectly before, unsure what changed. Is this still a thing?

**Comment by rchiodo** [comment]
@thethiny can you be more specific about what's not behaving how you want it?

Some things have changed since this bug was logged.

To start with, auto imports are disabled by default. Auto imports is overly aggressive and orders things poorly, so we disabled it by default. You can turn it back on like so:

```json
  "python.analysis.autoImportCompletions": true,
```

Then on top of that there are settings to control how many modules we will search through. This is called indexing and we do this when opening a workspace.

The settings are described here:

https://github.com/microsoft/pylance-release#settings-and-customization

The ones needed to be set are:

```json
  "python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 2,
      "includeAllSymbols": true
    },
  ],
```
That will index all 3rd party modules to 2 levels up the directory hierarchy. You could also set the depth to 1 if you want it to be faster and you don't need second level modules.

**Comment by thethiny** [comment]
@rchiodo I took what you said into consideration and have opened a new issue

**Comment by nagromLobo** [comment]
I'm glad we have a suggested solution for this now! This appears to be working for us!

**Comment by thethiny** [comment]
Yes I agree that this should be part of the Documentation since I didn't see it in any `What's New` recently.
