### ISSUE TITLE
Add option to disable reportUndefinedVariable on a per variable-basis

### ISSUE THREAD

**Issue by janosh** [microsoft/pylance-release#216]
Pylance correctly warns that `y` in `print(y)` is possibly unbound in this minimal example.

```py
for x in maybe_empty_iter:
    y = x

print(y)
```

It's a little annoying though if you're sure enough the iterator is not empty. Could Pylance offer a per-variable off switch for such rules? Similar to [`# noqa` in `flake8`](https://flake8.pycqa.org/en/latest/user/violations.html#in-line-ignoring-errors) maybe:

```py
for x in maybe_empty:
    y = x  # nounbound: y

print(y)
```

**Comment by erictraut** [comment]
My recommendation is to always initialize your variable before the for loop if you intend to use it after the for loop.
```
y = None
```
That's more proper and less noisy than a comment to suppress the error.

Pylance does support `# type: ignore` comments as per the PEP 484 spec, but you need to place them on the line where the error is reported.

**Comment by janosh** [comment]
Thanks for the quick reply!

> My recommendation is to always initialize your variable before the for loop if you intend to use it after the for loop. That's more proper and less noisy than a comment to suppress the error.

I find that a little noisy too but I take your point.

> Pylance does support `# type: ignore` comments as per the PEP 484 spec, but you need to place them on the line where the error is reported.

Cool, didn't know about that.
