### ISSUE TITLE
Problema com tkinter import *

### ISSUE THREAD

**Issue by VladimirPereira** [microsoft/pylance-release#2162]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```
Ao chamar from tkinter import *, o asterisco fica com uma espécie de ~ embaixo dele e colocando o mouse em cima aparece essa mensagem e a janela não abre...
Wildcard import from a library not allowedPylance (reportWildcardImportFromLibrary)
Nenhuma correção rápida disponível

obrigado pela atenção

**Comment by VladimirPereira** [comment]
estou usando o a versão 3.10 do python

**Comment by erictraut** [comment]
Importing from a library using a wildcard import is not recommended. For details, refer to [PEP 8](https://www.python.org/dev/peps/pep-0008/).

> Wildcard imports (from <module> import *) should be avoided...

If you want to disregard this warning, you can use `# type: ignore` or disable the `reportWildcardImportFromLibrary` diagnostic check in the pylance settings.
