### ISSUE TITLE
from django.db import models

### ISSUE THREAD

**Issue by evgen66rus** [microsoft/pylance-release#2166]
Default Django, just started to use.
<img width="643" alt="image" src="https://user-images.githubusercontent.com/18571021/145719628-6f2aedb1-516e-4610-96a2-b498b2a3c7a4.png">

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by ncermesoni** [comment]
@evgen66rus is your python interpreter pointing to the right env?

**Comment by judej** [comment]
closing stale issue
