### ISSUE TITLE
Inline hints

### ISSUE THREAD

**Issue by aliev** [microsoft/pylance-release#2170]
It would be cool to have inline hints like in rust-analyzer:

<img width="834" alt="Screen Shot 2021-12-11 at 00 06 09" src="https://user-images.githubusercontent.com/407134/145652200-b6421dfb-0398-4fd3-b42b-d79dd9c1da23.png">

Since vscode already supports inline hits (it seems that this already works in TypeScript as well).

**Comment by judej** [comment]
Thanks for the suggestion. Will add this to the backlog.

**Comment by judej** [comment]
Covered in discussion: https://github.com/microsoft/pylance-release/discussions/2643
