### ISSUE TITLE
How should an optional dependency be typehinted?

### ISSUE THREAD

**Issue by FeryET** [microsoft/pylance-release#2175]
Imagine I have package A that has an optional dependency B. Usually there is no need for the portion of A that is dependent on B to be used, but some advanced users might end up doing so.

In order to indicate that the package is optional, most packages wrap the import in a try/except  or if/else error, to make sure the optional import doesn't break things, and log/print errors of not importing to the user.

In this case, pylance cannot follow exactly what has been imported. You can see the issue in action here:

https://github.com/PyTorchLightning/pytorch-lightning/issues/10974#event-5767801690

Any idea how is this addressable?

**Comment by erictraut** [comment]
Typically this is handled with a `if TYPE_CHECKING` conditional, which allows you to specify which assumptions you want a static type checker to use when performing type analysis. If you want it to assume that the optional dependency is present, then you'd do something like this:

```python
if TYPE_CHECKING:
    import B
else:
    try:
        import B
    except:
        pass
```

Or if you want the static type checker to assume that the optional import is not present:

```python
if not TYPE_CHECKING:
    try:
        import B
    except:
        pass
```

**Comment by FeryET** [comment]
why not doing this?
```
try:
    import B
except Exception as e:
   if TYPE_CHECKING:
      raise e
```
This way you are only doing imports in one line, instead of copying all of your imports?

**Comment by erictraut** [comment]
That won't work because it's ambiguous for the type checker. If the import causes an exception, B will be unbound.

**Comment by judej** [comment]
@FeryET, looks like the fix for this should in the PyTorchLightning lib, and you have a conversation in progress there. Please let us know if we can help.
