### ISSUE TITLE
[Bug] keywords are showen on top of suggestion list.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#218]
see sorted list of jedi:
![image](https://user-images.githubusercontent.com/26390254/89709428-4be66900-d994-11ea-9add-469762a41ed1.png)

and here is Pylance sorted list:
![image](https://user-images.githubusercontent.com/26390254/89709953-746e6300-d994-11ea-883a-546dd119de0d.png)

**Comment by erictraut** [comment]
Can you explain what you mean by "keywords"? That term typically refers to words that are reserved within the language grammer like "class" and "continue". Those keywords are appearing in the list, but they aren't at the "top of the list", so I want to make sure I understand what you mean.

Pylance uses a sophisticated set of heuristics to determine which items to include in the suggestion list and which order to present them in. The goal is to always make it as likely as possible that the desired completion is at or near the top of the list.

Could you provide more information about what it is about Pylance's sort order that you find suboptimal? Are you saying that you always want the list to be in simple alphabetical order even if the most likely completion is alphabetically far down the list? I don't think that matches the expectations of most users.

**Comment by byehack** [comment]
> Could you provide more information about what it is about Pylance's sort order that you find suboptimal? Are you saying that you always want the list to be in simple alphabetical order even if the most likely completion is alphabetically far down the list?

i think you are sorting the list seprated: (variables & classes & functions) and (keywords: like def, pass)
then show sorted keywords list at top and sorted variables list after. 


> I don't think that matches the expectations of most users.

when keywords are at top we should press more down Key

**Comment by jakebailey** [comment]
> i think you are sorting the list seprated: (variables & classes & functions) and (keywords: like def, pass)
then show sorted keywords list at top and sorted variables list after.

But this isn't true; the screenshot you provided for Pylance shows variables, then keywords, then some more variables.

All that's happening in the Jedi case is pure alphabetical sorting, without any ranking applied to distinguish things.

Can you clarify what you are expecting to see instead?
