### ISSUE TITLE
Support for Pandas display() in VSC

### ISSUE THREAD

**Issue by eightbit** [microsoft/pylance-release#2181]
display() is underlined in VSC

**Message**
"display" is not defined Pylance(reportUndefinedVariable)

Link from VSC brought me here.

I'll leave it to you to consider.
Thanks for this great tool!

**Comment by CodeCrazy-ywt** [comment]
Screenshot? Log?

**Comment by eightbit** [comment]
Pandas: 1.2.0

Unless there is a fix that is not installed in my env, here's a quick way to check it out for yourself:

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

d = {'num_legs': [4, 4, 2, 2],
     'char': ['impersonal','bff','coolest','best view'],
     'class': ['mammal', 'mammal', 'mammal', 'bird'],
     'animal': ['cat', 'dog', 'bat', 'penguin'],
     'locomotion': ['walks', 'walks', 'flies', 'walks']}
df = pd.DataFrame(data=d)
df
display(df)
```


![image](https://user-images.githubusercontent.com/5913748/146979694-be846708-a1a6-4555-863f-cf056580cec7.png)

**Comment by judej** [comment]
thanks for the report. Is this from a notebook? and do you have IPython installed?

**Comment by heejaechang** [comment]
jupyter extension page will have more detail but main thing is this

https://github.com/microsoft/vscode-jupyter/wiki/Setting-Up-Run-by-Line-and-Debugging-for-Notebooks

**Comment by heejaechang** [comment]
might be related to this https://github.com/microsoft/pylance-release/issues/1598

**Comment by judej** [comment]
closing stale issue
