### ISSUE TITLE
Make it possible to apply a function whose return value is ``NoReturn`` to the abstract method.

### ISSUE THREAD

**Issue by SaidBySolo** [microsoft/pylance-release#2183]
<h3> Environment data </h3>

-   Language Server version: 2021.12.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): CPython 3.9.1
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

Even if you apply the NoReturn type hint as the return value, it shouldn't complain.

<h3> Actual behaviour </h3>

![image](https://user-images.githubusercontent.com/33891531/146634702-27b07538-eba2-4700-aae4-1e54da91495f.png)

<h3> Logs </h3>

Python Language Server Log
```
[Info  - 5:23:53 PM] Pylance language server 2021.12.2 (pyright 211ebe44) starting
[Info  - 5:23:53 PM] Server root directory: c:\Users\saidb\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist
[Info  - 5:23:53 PM] No configuration file found.
[Info  - 5:23:53 PM] No pyproject.toml file found.
[Info  - 5:23:53 PM] Setting pythonPath for service "heliotrope": "c:\Users\saidb\Documents\GitHub\heliotrope\.venv\Scripts\python.exe"
[Warn  - 5:23:53 PM] stubPath c:\Users\saidb\Documents\GitHub\heliotrope\typings is not a valid directory.
[Info  - 5:23:54 PM] Assuming Python version 3.9
[Info  - 5:23:54 PM] Assuming Python platform Windows
[Info  - 5:23:54 PM] Searching for source files
[Info  - 5:23:54 PM] Auto-excluding c:\Users\saidb\Documents\GitHub\heliotrope\.venv
[Info  - 5:23:54 PM] Found 50 source files
[Info  - 5:23:54 PM] Background analysis(1) root directory: c:\Users\saidb\.vscode\extensions\ms-python.vscode-pylance-2021.12.2\dist
[Info  - 5:23:54 PM] Background analysis(1) started
```

<h3> Code Snippet / Additional information </h3>

```python
from asyncio import sleep
from typing import NoReturn

from abc import ABC, abstractmethod


class AbstractTask(ABC):
    @abstractmethod
    async def start(self, delay: float) -> NoReturn: # Function with declared type of "NoReturn" cannot return "None"
        """
        Start the task.
        """

class Task(AbstractTask):
    async def start(self, delay: float) -> NoReturn:
        while True:
            await sleep(delay)
```

This is not a problem even when strictly applying mypy

**Comment by erictraut** [comment]
A typical way to implement an abstract method is to include the statement `raise NotImplemented()` in the function body. This will satisfy the `NoReturn` return type. You can also include the statement `...` at the end. I think those are better solutions than special-casing the NoReturn check specifically for abstract methods.

**Comment by Azureblade3808** [comment]
I think there may be something wrong.

If we were to write similar code without async/await, it could be:
```python
from time import sleep
from typing import NoReturn

from abc import ABC, abstractmethod

class AbstractTask(ABC):
    @abstractmethod
    def start(self, delay: float) -> NoReturn:
        ...

class Task(AbstractTask):
    def start(self, delay: float) -> NoReturn:
        while True:
            sleep(delay)
```
In such case, Pylance doesn't complain about the return type.

**Comment by Azureblade3808** [comment]
Sorry, I misread the OP. The problem is all about a missing ellipsis(...) in the method implementation, just as one solution that Eric gave in his reply.
