### ISSUE TITLE
Two argument lambda can't infer type

### ISSUE THREAD

**Issue by Molkree** [microsoft/pylance-release#2184]
## Environment data

-   Language Server version: v2021.12.2
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.1

## Expected behaviour

type is being inferred as `list[int]`.

## Actual behaviour

![image](https://user-images.githubusercontent.com/12860284/146836844-a8f53663-2750-4e55-9c6b-ef795d10d20c.png)

## Code Snippet / Additional information

```python
from itertools import accumulate


cashflows = [1000, -90, -90, -90, -90]
lst = list(accumulate(cashflows, lambda bal, pmt: bal * 2 + pmt))
```

Weirdly `pmt` is being inferred as an `int` while `bal` stays `Uknown`. Pylance 2021.1.1 seems to be the last version that could infer `list[int]` type.

**Comment by erictraut** [comment]
There's not enough type information here for pyright to infer the type. The parameter `bal` has no type annotation, and the `accumulate` constructor doesn't provide any details that would allow pyright to determine the type.

Here's the relevant overload for the `accumulate` constructor:
```python
def __init__(self, iterable: Iterable[_S], func: Callable[[_T, _S], _T], *, initial: _T | None = ...) -> None: ...
```

I would normally suggest that you provide an explicit specialization inline for the `accumulate` class, but it appears that it's not a real generic class, so this causes a runtime exception.

```python
lst = list(accumulate[int](cashflows, lambda bal, pmt: bal * 2 + pmt)) # Runtime error
```

To work around this, I recommend doing something like this:
```python
acc: "accumulate[int]" = accumulate(cashflows, lambda bal, pmt: bal * 2 + pmt)
lst = list(acc)
```

Another workaround is to supply an `initial` argument, which allows pyright to understand the type of `_T` in the constructor.

```python
lst = list(accumulate(cashflows, lambda bal, pmt: bal * 2 + pmt, initial=0))
```

**Comment by Molkree** [comment]
@erictraut, thank you for the detailed explanation!

1.
```py
acc: "accumulate[int]" = accumulate(cashflows, lambda bal, pmt: bal * 2 + pmt)
```
This is great, I didn't know enough about quoted type hints to come up with this, I usually just used `from __future__ import annotations` which also works in this case (when we extract to the separate `acc` variable).

2. The last workaround doesn't actually work for me, I still get errors, just one less than in the initial example:

![image](https://user-images.githubusercontent.com/12860284/146846173-86a15c14-dd7e-49ca-bf0b-0dc327e96677.png)

3. Could you explain a bit more why old Pylance 2021.1.1 was able to infer the type?

![image](https://user-images.githubusercontent.com/12860284/146846501-b045349b-6286-44ba-91d6-24e7a5224a96.png)

![image](https://user-images.githubusercontent.com/12860284/146847575-f03a3ff8-374b-4ef7-bffa-7df51dce1be2.png)

~~Am I correct in understanding that it was able only because old bundled typeshed had different signature? I guess this is the [commit](https://github.com/python/typeshed/commit/c893857f4671e454d558c3fcaf1a502548669873) that changed it?~~ Okay, I went ahead and edited `itertools.pyi` to the old version and it did "fix" this particular inference problem but I assume it's somehow wrong for other cases and this is beyond me at this point. Thank you again for your help.

**Comment by erictraut** [comment]
I don't think anything changed in the type checking logic that would explain this difference, but it's possible that the typeshed for `itertools.pyi` has changed.

**Comment by Molkree** [comment]
I think my point 2 about the workaround not working is a [different bug](https://github.com/microsoft/pylance-release/issues/2192) so I'm going to close this issue.
