### ISSUE TITLE
Variable with asterisk when unpacking lists has wrong type

### ISSUE THREAD

**Issue by WEGFan** [microsoft/pylance-release#2187]
## Environment data

- Language Server version: 2021.12.2 (pyright 211ebe44)
- OS and version: Windows 10 20H2 (19042.1151)
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Expected behaviour

```python
[a, *b, c] = [1, 2, 3, 4]
for i in b:
    print(i)
```

`b` should be inferred as a `List[int]` instead of `int`

## Actual behaviour

![](https://user-images.githubusercontent.com/7558201/146923204-588ad355-067c-4531-8bc1-a87dbfd15470.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.0, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202210-5-january-2022)

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.0, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202210-5-january-2022)
