### ISSUE TITLE
Merging project & user extraPaths settings

### ISSUE THREAD

**Issue by propertone** [microsoft/pylance-release#2195]
We have a use case where we need to configure extraPaths at the project AND user level. The project level extraPaths point to the relative location of python modules within the project, and user-level setting would optionally be set to override the default location of some of the external modules to the absolute path in the user's personal checkout.

However it seems like Pylance will ignore the extraPaths in the user's vscode setting if it's specified in the project settings (either pyproject.toml or pyrightconfig.json or .vscode/settings.json). Is this an intentional decision? Is there a way to specify extraPaths both at the project AND user level?

**Comment by erictraut** [comment]
There's currently no way to do this using "extraPaths".

You could use the `PYTHONPATH` environment variable (e.g. through a ".env" file)  on each user's system to add extra import resolution paths to the selected Python environment. This would then be merged with the "extraPaths" provided in the project settings.

**Comment by propertone** [comment]
Ok, that works for our use case.

**Comment by propertone** [comment]
Actually, this is not quite working. The PYTHONPATH set in the `.env` file is only being respected if the `python.analysis.extraPaths` is specified in the user/workspace VSCode settings. But if you specify `extraPaths` in the pyproject.toml or pyrightconfig.json file, then the env file is being ignored altogether.
