### ISSUE TITLE
Semantic Highlighting

### ISSUE THREAD

**Issue by mkschulze** [microsoft/pylance-release#220]
Hello,

it would be great to have semantic highlighting available for Color Theming.

The scope inspector doesn't show semantic scopes but just the textmate fallbacks.

![Bildschirmfoto 2020-08-09 um 13 07 05](https://user-images.githubusercontent.com/3390820/89730723-b2759080-da41-11ea-87a3-4e924a952363.png)

**Comment by jakebailey** [comment]
This is being worked on, yes. Note that semantic highlighting isn't finalized in the LSP spec and changes somewhat often, so requires a bit of coordination between the client / server to make sure they are agreeing on the API.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
