### ISSUE TITLE
Import "airflow.models" could not be resolved

### ISSUE THREAD

**Issue by DachuanZhao** [microsoft/pylance-release#2201]
<h3> Environment data </h3>

-   Language Server version: 2021.12.2
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda):  anaconda 3.7.11
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>
<h3> Actual behaviour </h3>

I have install the module : 
```Bash
pip install apache-airflow
```

But when I import the module , 
```Python
from airflow.models import DAG
```
it raise error :
```Python
Import "airflow.models" could not be resolved Pylance reportMissingImports
```
<h3> Logs </h3>

Python Language Server Log
```
[Info  - 9:37:54 AM] Pylance language server 2021.12.2 (pyright 211ebe44) starting
[Info  - 9:37:54 AM] Server root directory: /Users/zhaodachuan/.vscode/extensions/ms-python.vscode-pylance-2021.12.2/dist
[Info  - 9:37:54 AM] No configuration file found.
[Info  - 9:37:54 AM] No pyproject.toml file found.
```

<h3> Code Snippet / Additional information </h3>

**Comment by erictraut** [comment]
Can you confirm that you have the latest version of "apache-airflow" installed? I just installed the latest, and I'm not able to repro the error you're seeing. I installed version "2.2.3" which appears to be the latest published.

**Comment by DachuanZhao** [comment]
> Can you confirm that you have the latest version of "apache-airflow" installed? I just installed the latest, and I'm not able to repro the error you're seeing. I installed version "2.2.3" which appears to be the latest published.

I reinstall it and it works . Thanks !
