### ISSUE TITLE
PIL being underlined in yellow on Import even though pillow installed

### ISSUE THREAD

**Issue by J-onasJones** [microsoft/pylance-release#2207]
## Environment data
Pylance version 2021.12.2

-   Language Server version: XXX
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

Pylance should detect the PIL library after installed using command: 'pip install pillow'. Pylance should not underline the PIL library in the import statement of the python script.

## Actual behaviour

Pylance underlines the PIL library when importing it usning 'Import PIL' in the schipt in yellow. Pylance does not detect that the library has already been installed (possibly because of the different name: "pillow" when installing and "PIL" when importing)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

A code snippet would be useful.

**Comment by judej** [comment]
closing stale issue
