### ISSUE TITLE
Not type related features comparison

### ISSUE THREAD

**Issue by zbirenbaum** [microsoft/pylance-release#2209]
What non-type related features does pylance offer over pyright? Everything in changelog seems related to the custom stubs maintained, but I was wondering if there is anything else.

**Comment by judej** [comment]
Thanks for the query. Type related features is where a significant part of our investment is. However, we have several other features that are not type related that improve the coding experience - such as:

	semantic colorization
	trusted workspace
	module rename
	intellicode
	extract methods and variables 
	removed unused imports
	add import
	auto parens for function call

To name some. Hope this information is useful.
thanks

**Comment by zbirenbaum** [comment]
Hi! Thanks for the reply. I am a little confused regarding semantic colorization and intellicode though. I was under the impression that both of those were controlled by the editor, and not the server itself. I know from the VSCode source that a lot of effort has been put into comparators but I'm unsure of how pylance has any input there.

Since semantic colorization is similarly handled under editor options rather than analysis, do you mean that pylance provides additional information by some method to the editor for an improved token highlighting scheme?

I use neovim and am trying to figure out what features I would gain by using pylance in vscode that aren't things handled by vscode itself that could be written into a neovim plugin.

**Comment by erictraut** [comment]
Basic (grammar-based) colorization is handled by VS Code, but _semantic colorization_ (also know as [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide)) requires input from the language server.

Other features in pylance include (adding to Jude's list):
* Background indexing of sources to improve performance of "find all references".
* Extracting and displaying docstrings from parallel source tree when stubs are present.
* Including preprocessed docstrings from stdlib modules.

**Comment by zbirenbaum** [comment]
Thank you for the very descriptive answers, I understand where I was confused regarding the highlights now. 

I appreciate both of you taking the time to answer my question!
