### ISSUE TITLE
Add placeholders to callable completions

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#221]
I'm moving this feature request from pyright to pylance. It was originally submitted by @leungbk here https://github.com/microsoft/pyright/issues/924.

It would be nice if [snippets](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#snippet_syntax) were given in completions. For example, with the insertion point at `[-]` in

``` python3
def factorial(n: int) -> int:
    return 1 if n == 0 else n * fa[-]
```

one of the completions could be, using snippet syntax,

`factorial${1:(${2:n: int})}`

Type-inferencing could be useful here to let us automatically drop the outer pair of braces depending on context.

**Comment by jakebailey** [comment]
This is technically #37 + placeholders for parameters. We've committed to the former, but the latter has a pretty poor UX in VS Code, IMO.

**Comment by savannahostrowski** [comment]
This issue has been open for nearly a year and has not received enough upvotes to prioritize the work. Will reopen if we see this becoming a theme in user issues.
