### ISSUE TITLE
Are generic types handled correctly when re-used in function signature?

### ISSUE THREAD

**Issue by jellis18** [microsoft/pylance-release#2211]
I'm not sure if this is a bug or not but this doesn't seem to be the right behavior based on what I've come to expect from generics in other languages

This is expected since the type of the variables is `float` then the return is `List[float]`
![image](https://user-images.githubusercontent.com/3458354/147989641-46dab1f5-d308-4f79-a9c2-cba0d29d6968.png)

This is not expected and would raise an error in a more realistic case 
![image](https://user-images.githubusercontent.com/3458354/147989705-3a28afe3-713d-4ddd-a892-f43b62b7b2d6.png)

The above seems wrong to me, the type should be inferred based on its first use so the type of `T` should be string and I would expect an error to be raised here.

For example this is what would happen in Rust (no union types) 
![image](https://user-images.githubusercontent.com/3458354/147990402-8fd5e652-1b08-4f64-bde1-489aa664d1c3.png)

and TypeScript (union types)
![image](https://user-images.githubusercontent.com/3458354/147990341-82463dd0-b25f-4707-8893-ba389e155028.png)

**Comment by erictraut** [comment]
Yes, this is the correct behavior as prescribed by PEP 484.
