### ISSUE TITLE
False Unreachable Code

### ISSUE THREAD

**Issue by mmzeynalli** [microsoft/pylance-release#2223]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
class TransactionDataGetSetTestCase(StarexTestCase):
    def setUp(self):
        super().setUp()

        self.transaction1: Transaction = pf.TransactionFactory(data=None)
        self.transaction2: Transaction = pf.TransactionFactory(data=dict())
        self.transaction3: Transaction = pf.TransactionFactory(data={"data_key": None})
        self.transaction4: Transaction = pf.TransactionFactory(
            data={"data_key": "data_value"}
        )
        self.transaction5: Transaction = pf.TransactionFactory(data=None)
```

**Comment by erictraut** [comment]
Thanks for the bug report, but we'll need more context. Could you please provide a minimal, self-contained sample (including any required import statements and the versions of the libraries you have installed) and describe what behavior you're seeing?
