### ISSUE TITLE
Hope add the special-method automatic completion

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/pylance-release#2228]
I found some special-mathod didn't give the automatic completion, such as `__enter__` , `__exit__` , etc.

![image](https://user-images.githubusercontent.com/82581024/148641404-1c2f55bb-7a13-445f-a77c-54462770a2da.png)

I always rely on the automati completion to ensure correctness, so I hope pylance can provide the function.
The information for special-mathod is at https://docs.python.org/3/reference/datamodel.html#special-method-names

**Comment by erictraut** [comment]
Those methods are not included in the auto-complete list because they are not found anywhere in the `Foo` object hierarchy, whereas the others are (since they are methods provided by the base class `object`).

**Comment by Vincent0706** [comment]
But it's important for uers to build the individuation class.

**Comment by hrmorley34** [comment]
You can get this completion by inheriting from the appropriate ABCs:

![image](https://user-images.githubusercontent.com/10192165/148664151-6ca7649c-1766-48dc-af8f-df4708af86af.png)

```python
from typing import ContextManager
# or
# from contextlib import AbstractContextManager


class Foo(ContextManager[int]):
    def __enter__(self) -> int:
        return super().__enter__()
```

**Comment by judej** [comment]
Thanks @hrmorley34  for the input.
