### ISSUE TITLE
print(f"Month: {month:14} Training: {trainning}")

### ISSUE THREAD

**Issue by Ilseneugenia** [microsoft/pylance-release#2229]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
Thanks for the report. Would you please help us understand the bug or issue you are facing?
Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by judej** [comment]
Closing stale issue
