### ISSUE TITLE
Showing reportundefinedVariable

### ISSUE THREAD

**Issue by jballipalli** [microsoft/pylance-release#223]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment]
We'll need more information. Can you provide a code snippet that demonstrates the problem you're seeing?
