### ISSUE TITLE
markdown rendering issues

### ISSUE THREAD

**Issue by jdtsmith** [microsoft/pylance-release#2231]
**Describe the bug**

The auto-markdown conversion for signatureHelp and hover is useful, but appears to have some issues.  For example, consider the numpy function `np.unique`.  This is the Parameters block from its docstring:

```
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
        axis, if provided) that can be used to reconstruct `ar`.
    return_counts : bool, optional
        If True, also return the number of times each unique item appears
        in `ar`.

        .. versionadded:: 1.9.0

    axis : int or None, optional
        The axis to operate on. If None, `ar` will be flattened. If an integer,
        the subarrays indexed by the given axis will be flattened and treated
        as the elements of a 1-D array with the dimension of the given axis,
        see the notes for more details.  Object arrays or structured arrays
        that contain objects are not supported if the `axis` kwarg is used. The
        default is None.

        .. versionadded:: 1.13.0
```

---

And here is how pyright renders it into markdown:

Parameters
----------
ar : array\\_like\\
&nbsp;&nbsp;&nbsp;&nbsp;Input array. Unless `axis` is specified, this will be flattened if it
is not already 1-D.\\
return\\_index : bool, optional\\
&nbsp;&nbsp;&nbsp;&nbsp;If True, also return the indices of `ar` (along the specified axis,
if provided, or in the flattened array) that result in the unique array.\\
return\\_inverse : bool, optional\\
&nbsp;&nbsp;&nbsp;&nbsp;If True, also return the indices of the unique array (for the specified
axis, if provided) that can be used to reconstruct `ar`.\\
return\\_counts : bool, optional\\
&nbsp;&nbsp;&nbsp;&nbsp;If True, also return the number of times each unique item appears
in `ar`.

axis : int or None, optional\\
&nbsp;&nbsp;&nbsp;&nbsp;The axis to operate on. If None, `ar` will be flattened. If an integer,
the subarrays indexed by the given axis will be flattened and treated
as the elements of a 1-D array with the dimension of the given axis,
see the notes for more details.  Object arrays or structured arrays
that contain objects are not supported if the `axis` kwarg is used. The
default is None.

---

The main issues are (sometimes, but not always) doubling or tripling backslashes (e.g. `\\\n`), and losing the reverse indentation layout which delineates individual parameters.  The `..versionadded` info is also stripped.

**Comment by heejaechang** [comment]
this is what i am seeing

![image](https://user-images.githubusercontent.com/1333179/164576652-5d018217-ba42-44a0-9d65-8d990593c68c.png)

I don't see any issue on doc string rendering.

please re-open the issue with more specifics if you think we need to improve doc string rendering.

**Comment by heejaechang** [comment]
actually, I think we are

**Comment by heejaechang** [comment]
I re-opened the issue and set it as enhancement. we probably want to improve line wrapping.

**Comment by jdtsmith** [comment]
Thanks for your thoughts on this.  The issue is with parsing the doc info in another tool (Emacs).  While it may be rendered well enough in some tools, the markdown has errors, as you can see above by Github's rendering of the exact content delivered by pyright.  Here's how it renders for me:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/93749/164588643-d642ebbf-0f61-4f0b-aa05-05b9fc5512d0.png">

It would be great if pyright could stick to simple markdown, renderable anywhere.  Even GitHub has trouble rendering the markdown pyright generates (see example above).  Is there perhaps a plaintext option which returns the docs without processing?

**Comment by heejaechang** [comment]
@jdtsmith not all markdown renderer supports all different variations of markdowns. our markdown targets one that vscode LSP client uses. it looks like the markdown renderer you used are not supporting some of markdown vscode renderer supports. (we also have bugs the other way that says vscode LSP markdown renderer not supporting one that other renderers support such as LaTex markdown)

we will take a look but we will probably still target best experience over vscode's markdown renderer.

**Comment by bschnurr** [comment]
look into replacing `\` with `<br>`
https://www.markdownguide.org/basic-syntax/#line-break-best-practices

**Comment by heejaechang** [comment]
@bschnurr it looks like ```&nbsp;``` is shown as it is according to the image @jdtsmith shared. so, I am not sure the markdown renderer @jdtsmith is using even supports HTML tags. it might be better to use the "two spaces - trailing whitespace" trick the doc is mentioning?

**Comment by heejaechang** [comment]
but the renderer user uses doesn't even support char escaping we put for ```_```.  (https://www.markdownguide.org/basic-syntax/#characters-you-can-escape)

so, it might be better to just ask users to use better markdown renderer.

**Comment by jdtsmith** [comment]
Plain text sounds workable.  What is the config setting enabling that?  Thanks.

**Comment by heejaechang** [comment]
@jdtsmith its up to client (Emacs), they need to request plain text hover, not markdown hover.

**Comment by rchiodo** [comment]
Not sure there is work to do here? What would the enhancement be?

**Comment by jdtsmith** [comment]
Unless the markdown can be simplified so as not to include special HTML entities but only pure markdown, I think just reverting to plain text is the right solution.  I've put in [a request](https://github.com/joaotavora/eglot/discussions/1039) (no traction yet).  

Just came across this particularly bad example today (from python's `re` module):

![image](https://user-images.githubusercontent.com/93749/195960742-5d897bd1-cf2f-42a7-a9c5-980b5bab4c66.png)

I'll close this as the client's problem.
