### ISSUE TITLE
Pylance not providing Code Snippets / Autocompletion Suggestions

### ISSUE THREAD

**Issue by TheKnax-dev** [microsoft/pylance-release#2232]
Hi there,

been trying to get into Python Programming. Installed Python / Pylance in VSCode but I am not getting any suggestions for code completion / Code Snippets.
I tried it both with and without a virtual envirement (used command:  python -m venv venv). Neither worked.

I can run / debug my python programs just fine.

I am probably missing something obvious but I can't get it working

Thank you for any help on this!

<h3> Environment data </h3>

-   IDE: VSCode
-   installed Extensions:
   - Python v2021.12.1559732655
   - Pylance v2022.1.0
-   Language Server version: 2022.1.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): python3.10.1 64-bit
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Expecting Pylance to suggest Code Snippets / Auto Completion in Editor.

<h3> Actual behaviour </h3>

No Code Snippet / Auto Completion Suggestions.

![image](https://user-images.githubusercontent.com/79710648/148705395-738a3ea4-35db-4ead-b496-be9012e7c1ae.png)

<h3> Logs </h3>

Python Language Server Log

[Info  - 00:14:46] No configuration file found.
[Info  - 00:14:46] No pyproject.toml file found.
[Info  - 00:14:46] Setting pythonPath for service "Neat": "e:\Coding\VSCode\Projects\Python\Neat\venv\Scripts\python.exe"
[Warn  - 00:14:46] stubPath e:\Coding\VSCode\Projects\Python\Neat\typings is not a valid directory.
[Info  - 00:14:46] Assuming Python version 3.10
[Info  - 00:14:46] Assuming Python platform Windows
Search paths for e:\Coding\VSCode\Projects\Python\Neat
  c:\Users\jonas\.vscode\extensions\ms-python.vscode-pylance-2022.1.0\dist\typeshed-fallback\stdlib
  e:\Coding\VSCode\Projects\Python\Neat
  e:\Coding\VSCode\Projects\Python\Neat\typings
  c:\Users\jonas\.vscode\extensions\ms-python.vscode-pylance-2022.1.0\dist\typeshed-fallback\stubs\...
  c:\Users\jonas\.vscode\extensions\ms-python.vscode-pylance-2022.1.0\dist\bundled\stubs
  e:\Python\DLLs
  e:\Python\Lib
  e:\Python
  e:\Coding\VSCode\Projects\Python\Neat\venv
  e:\Coding\VSCode\Projects\Python\Neat\venv\Lib\site-packages
[Info  - 00:14:46] Searching for source files
[Info  - 00:14:46] Auto-excluding e:\Coding\VSCode\Projects\Python\Neat\venv
[Info  - 00:14:46] Found 1 source file
Background analysis message: setConfigOptions
Background analysis message: setImportResolver
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: getSemanticTokens delta
[BG(1)] getSemanticTokens delta previousResultId:1641769643202 at e:\Coding\VSCode\Projects\Python\Neat\main.py ...
[BG(1)]   parsing: e:\Coding\VSCode\Projects\Python\Neat\main.py (89ms)
[BG(1)]   parsing: c:\Users\jonas\.vscode\extensions\ms-python.vscode-pylance-2022.1.0\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 1ms] (43ms)
[BG(1)]   binding: c:\Users\jonas\.vscode\extensions\ms-python.vscode-pylance-2022.1.0\dist\typeshed-fallback\stdlib\builtins.pyi (27ms)
[BG(1)]   binding: e:\Coding\VSCode\Projects\Python\Neat\main.py (0ms)
[BG(1)] getSemanticTokens delta previousResultId:1641769643202 at e:\Coding\VSCode\Projects\Python\Neat\main.py (159ms)
Background analysis message: analyze
[BG(1)] analyzing: e:\Coding\VSCode\Projects\Python\Neat\main.py ...
[BG(1)]   checking: e:\Coding\VSCode\Projects\Python\Neat\main.py (0ms)
[BG(1)] analyzing: e:\Coding\VSCode\Projects\Python\Neat\main.py (0ms)
Background analysis message: resumeAnalysis

<h3> Code Snippet / Additional information </h3>

**Comment by heejaechang** [comment]
what kind of suggestion are we referring? can you give us some examples? for example, if you write "import o", does it show completion?

**Comment by TheKnax-dev** [comment]
> what kind of suggestion are we referring? can you give us some examples? for example, if you write "import o", does it show completion?

I get the following autocompletions for "output o".
![image](https://user-images.githubusercontent.com/79710648/149023271-0776797f-29d3-4433-81c9-9c065986c9c0.png)

What I am missing are code snippets for e.g. if-statements or for-loops.
If I write "if" I would expect a snippet that gives me something like:

if condition:
    pass
else:
    pass

![image](https://user-images.githubusercontent.com/79710648/149023710-73af0962-79f8-4579-9c43-0402c4569e1f.png)

**Comment by judej** [comment]
We removed the code snippets a while ago. Please see the explanation here: https://github.com/microsoft/vscode-python/issues/15279#issuecomment-771306907
