### ISSUE TITLE
reportMissingimports flasksqlalchemy

### ISSUE THREAD

**Issue by ayushshaw90** [microsoft/pylance-release#2234]
## Environment data

-   Language Server version: v2022.1.0
-   OS and version: Ubuntu 20.04 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by bschnurr** [comment]
make your you have the proper environment select.  see https://code.visualstudio.com/docs/python/environments

**Comment by ayushshaw90** [comment]
Thanks.
