### ISSUE TITLE
Could we provide a method like `Use debug() to automatically open a debugger at the start of a function call.` in RStudio?

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#2238]
In the RStudio, we can simply use the command: debug(my_function), then run the code, and automatically the script debugs at my_function.

Like the introduction in the [official docs](https://rstats.wtf/debugging-r-code.html):

> Use debug() to automatically open a debugger at the start of a function call.

**Comment by debonte** [comment]
FYI, there's more detail on the debug function further down on that page -- https://rstats.wtf/debugging-r-code.html#debug

**Comment by heejaechang** [comment]
@gonghenghai can you provide us some more detail on UX you are thinking?

**Comment by gramster** [comment]
In Python, this would be https://docs.python.org/3/library/functions.html#breakpoint

But it depends what environment you're talking about as to what effect this would have.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
