### ISSUE TITLE
Code colors are inconsistent for the same Python code in .ipynb and .py

### ISSUE THREAD

**Issue by arencambre** [microsoft/pylance-release#2239]
### VS Code version

1.63.2

### Extension version

2021.12.1559732655

### OS type

Windows

### OS version

11

### Python distribution

Anaconda

### Python version

3.8.12 64-bit

### Language server

Default

### Expected behaviour

Python code should have the same color in VSCode regardless of whether you're seeing it in a .py file or in a code cell in an .ipynb file.

### Actual behaviour

This is just one example. There are more.

Here's code in a .py file:
![image](https://user-images.githubusercontent.com/411495/148992167-2b4083fb-06c4-42b4-b98b-e9b4cb6c7d23.png)

Identical code in an .ipynb file:
![image](https://user-images.githubusercontent.com/411495/148992243-07809fe1-4901-42d4-8118-b08a36d1a71f.png)

### Steps to reproduce

Put the same code in a .py file and in a .ipynb file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by heejaechang** [comment]
let me take a look. thank you for the reporting!

**Comment by heejaechang** [comment]
I can't repro this. is kernel set properly that points to the venv you have those package installed for the notebook?

![image](https://user-images.githubusercontent.com/1333179/150038767-96995b6a-49c2-4c0e-a78e-2ac9fd15583e.png)

this is different than normal python file env

![image](https://user-images.githubusercontent.com/1333179/150038918-1d448e15-c88b-4347-8b31-1f0d7966c0db.png)

**Comment by arencambre** [comment]
Here's what I see:
![2022-01-18_18-22-42](https://user-images.githubusercontent.com/411495/150040269-68e49539-ea5b-49d7-829e-9c6945db7e65.gif)

**Comment by heejaechang** [comment]
@arencambre First, click the ... to select kernel. see this on how to use notebook in vscode - https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_create-or-open-a-jupyter-notebook

and it looks like vscode is in the restricted mode. in that mode, only limited functionality will be available. one of limitation could be getting location of third party packages installed. 

colorization on the regular python file might be still working since all packages used in the example is in the bundled typeshed (even though it couldn't access real packages).

**Comment by arencambre** [comment]
@heejaechang thanks for your response. I've reproduced on a pretty vanilla Windows 11 VM, too, so it's not an issue with my main workstation configuration.

I can see three ...s, and none have anything relevant to selecting a kernel:
![image](https://user-images.githubusercontent.com/411495/150157426-a96363d2-4aa9-4d59-a767-8acec9433395.png)

![image](https://user-images.githubusercontent.com/411495/150157487-09012e86-64da-483f-9346-57c8218c46ec.png)
![image](https://user-images.githubusercontent.com/411495/150157534-f44a6f6e-3c56-4cb5-aa99-573ecccdfdd4.png)

![image](https://user-images.githubusercontent.com/411495/150157732-eaa5fb19-2665-46b3-83aa-a3edf8552e29.png)

Even if I take VSCode out of restricted mode, the color difference does not resolve:
![image](https://user-images.githubusercontent.com/411495/150157985-b89166e4-cbc3-45c1-af0b-6240b34cc3d3.png)

![image](https://user-images.githubusercontent.com/411495/150158050-07ce8e19-ed38-4347-bae6-dddee0e0eb99.png)

**Comment by heejaechang** [comment]
Selecting kernel is pretty much standard thing on jupyter notebook regardless of vscode (https://docs.jupyter.org/en/latest/projects/kernels.html) but each client might have different UI for it. it provides execution environment where the notebook will be executed. without it, tool has no idea how to interpret text inside of the cells.

anyway, glad that the issue got resolved.

and, again, here are link (https://code.visualstudio.com/docs/datascience/jupyter-notebooks) on how to use jupyter notebook on vscode.

thank you.
