### ISSUE TITLE
Whole blocks marked as unreachable

### ISSUE THREAD

**Issue by vincentleeuwen** [microsoft/pylance-release#2241]
Issue Type: <b>Bug</b>

Whole blocks of code are marked as unreachable even tough they are not. I don't even remember updating pylance or vscode or anything? Very frustrating.

Extension version: 2022.1.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 3d2976ab-329e-4457-bcd5-1f1f5634912d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804cf:30404767
vs360cf:30404996
vsrem710cf:30416617
py55gd98cf:30419166

```

</details>

<img width="800" alt="Screenshot 2022-01-12 at 10 20 01" src="https://user-images.githubusercontent.com/431685/149122028-ebee34b4-f5da-4572-93b5-e43fb86b7cb2.png">

**Comment by jshaefferbfly** [comment]
https://github.com/microsoft/pylance-release/issues/2224#issuecomment-1007599177

**Comment by heejaechang** [comment]
it is a dup of https://github.com/microsoft/pylance-release/issues/2224
