### ISSUE TITLE
The help of numpy.random.choice is not complete

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/pylance-release#2243]
I found the help information of numpy.random.choice is not complete. It only have the function declaration. 

![image](https://user-images.githubusercontent.com/82581024/149270361-cdec53c6-58f0-49bd-a51d-0f0c6c00f25d.png)

**Comment by erictraut** [comment]
I presume that you're looking for a docstring or other documentation?

The type information and docstrings come from numpy itself. If you right-click on `choice` and select "Go To Declaration", you'll see which file this information comes from. In the latest release of numpy, `choice` is declared in a type stub file `numpy/random/mtrand.pyi`. Unfortunately, it doesn't include any docstrings, so pylance has nothing to display. You may want to file a bug (or better yet, a PR) in the numpy github repo.

**Comment by Vincent0706** [comment]
Thank you, I have asked for numpy

**Comment by bashtage** [comment]
Putting type information only in pyi files is standard.  docstrings are not incorporated in these files generally.  Other IDEs, e.g., PyCharm, can seamlessly incorporate pyi information with standard docstrings. I don't expect NumPy, or many other projects that have compiled code and use pti for typing, will move their docstrings away from the code into type stub files.

Related to numpy/numpy#20809

**Comment by Vincent0706** [comment]
https://github.com/numpy/numpy/issues/20809#issuecomment-1012013047
According to this, it seems to be pylance's or python-extention's problem.

**Comment by BvB93** [comment]
> numpy/numpy#20809 (comment)
> According to this, it seems to be pylance's or python-extention's problem.

Following up on this comment: the issue seems to be limited to functions that are purely C- or Cython-based, lacking any wrapper of some sort written in pure-python.

**Comment by bashtage** [comment]
@BvB93 Do the examples of functions with python wrappers have docstrings and typing information together. or is the docstring in the .py file and the typing in a .pyi?

**Comment by Vincent0706** [comment]
I don't know what is python wrappers. But in numpy  1.20.3 version, I right-click on choice and select "Go To Declaration". I can't found any docstrings or typing information.

![image](https://user-images.githubusercontent.com/82581024/149318014-9f995c28-1a1c-4c14-becf-5d784d856563.png)

**Comment by BvB93** [comment]
> @BvB93 Do the examples of functions with python wrappers have docstrings and typing information together. or is the docstring in the .py file and the typing in a .pyi?

The docstrings and annotations are *always* split between .py/.pyx and .pyi files.
Just to give a few more examples from my previous point:

Shows docstrings
------------------
* [`np.atleast_2d`](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/core/shape_base.py#L81-L118): Pure python function
* [`np.bincount`](https://github.com/numpy/numpy/blob/5cc7ef066fca7a821a2160b095578384c301ae3c/numpy/core/src/multiarray/compiled_base.c#L98-L112): C-based function with some form of [python wrapper](https://github.com/numpy/numpy/blob/813a0c11186ded0b5caeb853fd2b22fb9addd511/numpy/core/multiarray.py#L883-L956)

Does not show docstrings
--------------------------
* [`np.random.choice`](https://github.com/numpy/numpy/blob/813a0c11186ded0b5caeb853fd2b22fb9addd511/numpy/random/mtrand.pyx#L806-L898): Cython function
* [`np.array`](https://github.com/numpy/numpy/blob/229c1757609efbbeea96b90746bcbe5ba41e0397/numpy/core/src/multiarray/multiarraymodule.c#L1685-L1687): C-based function without a python wrapper

**Comment by bashtage** [comment]
I see. `bincount`'s python wrapper is

https://github.com/numpy/numpy/blob/8dbd507fb6c854b362c26a0dd056cd04c9c10f25/numpy/core/multiarray.py#L884

while it's type information is here

https://github.com/numpy/numpy/blob/e2d35064df262efa6eb7dfe5bfc43160c73cf685/numpy/core/multiarray.pyi#L417

**Comment by erictraut** [comment]
Pylance will find and display docstrings for functions and classed declared in ".pyi" files if it can find the same symbol in a corresponding ".py" file. In the case of `np.random.choice`, there is no corresponding ".py" file though. When functions are implemented in a language other than Python, there is no static way to access the docstring if it's not in the ".pyi" file. As such, it is recommended that the ".pyi" include the docstring. Refer to [this guidance](https://github.com/python/typing/blob/master/docs/source/libraries.rst#inlined-type-annotations-and-type-stubs) for more details.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.3, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202213-21-january-2022)
