### ISSUE TITLE
#region folding stopped working

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#2244]
Regression introduced with new LSP-based folding code which appears to have disabled the #region folding configuration in the Python language-configuration.json:

`"folding":{"offSide":true,"markers":{"start":"^\\s*#\\s*region\\b","end":"^\\s*#\\s*endregion\\b"}}`

## Environment data
-   Language Server version: 2022.1.1
-   OS and version: Windows 11 rs_prerelease 220107-2122
-   Python version: 3.10

## Expected behavior

^ folding icon should be displayed in gutter for #region/#endregion pairs

![image](https://user-images.githubusercontent.com/12820898/149402465-a9992663-49be-4a68-981b-a97ac511b131.png)

## Actual behavior

No folding icon.

![image](https://user-images.githubusercontent.com/12820898/149402701-8b729f7c-79b5-4436-8856-3c159a70994b.png)

## Code Snippet / Additional information

```python
#region foo1
    def foo1(self): pass
#region foo2
    def foo2(self): pass
#region foo3
    def foo3(self): pass
#endregion
#endregion
    def foo4(self): pass
#endregion
```

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.3, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202213-21-january-2022)
