### ISSUE TITLE
Pylance doesn't recognize the type of a variable pointing to a method.

### ISSUE THREAD

**Issue by geeshta** [microsoft/pylance-release#2247]
## Environment data

-   Pylance language server 2022.1.1 (pyright 4f61d443) 
-   Ubuntu 21.10
-   Python 3.10.1
-   Venv. Requirements.txt:
- `black==21.12b0
click==8.0.3
elementpath==2.4.0
mypy-extensions==0.4.3
pathspec==0.9.0
platformdirs==2.4.1
tomli==1.2.3
typing_extensions==4.0.1
xmlschema==1.9.2
`

## Expected behaviour

The xmlschema python package contains a type alias XMLSchema, which point to a class called XMLSchema10 which inherits from XMLSchemaBase.  
XMLSchemaBase has a method called `decode` which and a pointer to this method called `to_dict`  
`xmlschema/validators/schema.py:3014 to_dict=decode`

If I create an instance of the  XMLSchema class, Pylance should recognize both `decode` and the pointer `to_dict` and provide completion and type inference.

## Actual behaviour

If I create an instance of XMLSchema, Pylance recognizes only the `decode` method which is defined, but not the `to_dict` which is a pointer to `decode`. I says the type of `to_dict` is unknown. However, if I go to the source file nad hover over the definition on `xmlschema/validators/schema.py:3014 to_dict=decode` over `to_dict` it shows the correct types passed from the original definition.

## Logs

```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
> conda info --json
> ~/Documents/xml/venv/bin/python ~/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
Python interpreter path: ./venv/bin/python
> conda --version
> ". /home/sfoldesi/Documents/xml/venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/sfoldesi/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/printEnvVariables.py"
> /bin/python3 ~/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /bin/python3.10 ~/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/bin/python3.10 ~/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/local/bin/python3.10 ~/.vscode/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
Starting Pylance language server.
> ~/Documents/xml/venv/bin/python -m black --diff --quiet ~/Documents/xml/validate.py.8a5f414d9b3ea7fe18f7a1b86ecb374b.tmp
cwd: ~/Documents/xml
> ~/Documents/xml/venv/bin/python -m black --diff --quiet ~/Documents/xml/testmethodptr/methodptr.py.fde25e1ac2fb323e8ed35bcf9a9249c5.tmp
cwd: ~/Documents/xml
> ~/Documents/xml/venv/bin/python -m black --diff --quiet ~/Documents/xml/testmethodptr/__init__.py.a8931f348e45b6cd758e584f7758fa88.tmp
cwd: ~/Documents/xml
> ~/Documents/xml/venv/bin/python -m black --diff --quiet ~/Documents/xml/test.py.77983e59dadde56ace29afc5e01cda14.tmp
cwd: ~/Documents/xml
> ~/Documents/xml/venv/bin/python -m black --diff --quiet ~/Documents/xml/validate.py.8a5f414d9b3ea7fe18f7a1b86ecb374b.tmp
cwd: ~/Documents/xml
> ~/Documents/xml/venv/bin/python -m black --diff --quiet ~/Documents/xml/validate.py.8a5f414d9b3ea7fe18f7a1b86ecb374b.tmp
cwd: ~/Documents/xml
```

## Code Snippet / Additional information
Here you can see me F12 through definitions. In my file, the type of `to_dict` is Unknown. However if I go to the definition, the type information is shown correctly.
https://imgur.com/a/o03LLvH

```python
import xmlschema as xsd

xml_schema = xsd.XMLSchema("xml_schema.xsd")
xsdict = xml_schema.to_dict("xml_doc.xml")

print(xsdict)
```

I try to replicate it by crating a new package and following the same structure - the method definition and its pointer are in the base class, a child class inherits from the base class and a variable points to the child class. However in that case Pylance recognized the types correctly. I don't know why this doesn't happen with xmlschema.

**Comment by erictraut** [comment]
The `xmlschema` library is a "py.typed" library, so it should follow the type annotation rules set forth in [this documentation](https://github.com/python/typing/blob/master/docs/source/libraries.rst). When a library claims to be typed, any unannotated symbols a library are treated as "unknown". In other words, pylance doesn't attempt to infer the types of unannotated symbols if the package claims to be typed.

Pyright (the type checker upon which pylance is built) has a command-line mode called "--verifytypes" that determines the "type completeness" of a py.typed library. When I run this on the xmlschema package, it outputs the following summary:

```
Symbols exported by "xmlschema": 1956
  With known type: 1506
  With partially unknown type: 450

Type completeness score: 77%
```

So, while `xmlschema` is claiming to be fully typed, only 77% of its public symbols are fully typed.

The `to_dict` variable has no annotation, so it falls into the category of an "untyped symbol". The reason you are able to see the type information for this symbol when you open the file directly is that pyright will infer its type locally, but it will not infer its type when it's exported from a "py.typed" library.

If this library is important to you, please contact the maintainers and point them to the above guidance and encourage them to work toward 100% type completeness.

As a workaround in the meantime, it looks like the `decode` method is an alias for `to_dict`, and the former is fully annotated. So you could use that instead.

**Comment by geeshta** [comment]
Thank you fir the quick and comprehensive answer! Love the work Microsoft does on Vscode and Pylance!
