### ISSUE TITLE
TypedDict incompatible with `RequestData = dict` type in httpx 

### ISSUE THREAD

**Issue by kimadeline** [microsoft/pylance-release#2250]
## Environment data

-   Language Server version: 2022.1.0 (pyright 5829dcbb)
-   OS and version: macOS Big Sur 11.6.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8 venv

## Expected behaviour

No error when a typed dictionary as data to the `httpx.post` parameter accepting an object of type `RequestData`, with `RequestData = dict`.

## Actual behaviour

Argument of type "MyDictionary" cannot be assigned to parameter "data" of type "RequestData | None" in function "post"
  Type "MyDictionary" cannot be assigned to type "RequestData | None"
    "MyDictionary" is incompatible with "RequestData"
    Type cannot be assigned to type "None" (Pylance reportGeneralTypeIssues)

## Code Snippet / Additional information

httpx==0.21.3

```python
class MyDictionary(TypedDict):
    foo: str
    bar: int
    baz: Literal["banana", "orange"]

data_dict: MyDictionary = {"foo": "something", "bar": 3, "baz": "banana"}

httpx.post("http://localhost:4545", data=data_dict) # Pylance reports an error here

other_dict = {"foo": "something", "bar": 3, "baz": "banana"}

httpx.post("http://localhost:4545", data=other_dict) # This is fine
```

![image](https://user-images.githubusercontent.com/51720070/149601304-da726ffe-3aa2-4a5d-aae2-7ac70909d022.png)

**Comment by erictraut** [comment]
This behavior is correct. It is an error to assign a `TypedDict` to a `dict`. This is explicitly prohibited by [PEP 
589](https://www.python.org/dev/peps/pep-0589/), which introduced `TypedDict`.

If it were allowed to assign a `TypedDict` to a `dict`, the following type violation would be possible:
```python
class MyDictionary(TypedDict):
    foo: str
    bar: int
    baz: Literal["banana", "orange"]

data_dict: MyDictionary = {"foo": "something", "bar": 3, "baz": "banana"}

def mutate_my_dict(d: dict):
    del d["foo"]
    d["bar"] = "not an int"
    d["aaa"] = "a new key!"

mutate_my_dict(data_dict)
# At this point, `data_dict` is no longer a `MyDictionary` because it has been mutated.
```

It is possible to assign a `TypedDict` to a `Mapping` (which is an immutable dict type).
