### ISSUE TITLE
TypedDict can not be assign by the "dict" function

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#2257]
<h3> Environment data </h3>

-   Language Server version: 2022.1.1
-   OS and version: win32 x64 - Windows 10.0.17763.1935
-   Python version:  Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Following [this example of PEP 589](https://www.python.org/dev/peps/pep-0589/#supported-and-unsupported-operations) the `TypedDict` should allow to be defined by the `dict` constructor.

<h3> Actual behaviour </h3>

There is an error of `GeneralTypeIssues`
____
<h3> Code Snippet / Additional information </h3>

These examples comes from [PEP 589](https://www.python.org/dev/peps/pep-0589/)

```python
from typing import TypedDict

class Movie(TypedDict):
    name: str
    year: int

# this is OK
movie: Movie = {'name': 'Blade Runner', 'year': 1982}

# this is OK
m: Movie = Movie(name='Alien',year=1979)

# this shows an error
m: Movie = dict(name='Alien',year=1979)
```

Error message:
```
Expression of type "dict[str, str | int]" cannot be assigned to declared type "Movie"
  "dict[str, str | int]" is incompatible with "Movie" Pylance(reportGeneralTypeIssues)
```

Maybe related to #1645

____
<h3> Screen capture </h3>

![image](https://user-images.githubusercontent.com/57204023/149807678-39e2651d-54dd-4c0b-91b0-d86da7c30ada.png)

**Comment by erictraut** [comment]
This is intended. The behavior of the `dict` constructor is dictated by the type stubs in `builtins.pyi`. The form in your example is covered by the following overload:
```python
@overload
def __init__(self: dict[str, _VT], **kwargs: _VT) -> None: ...
```

The resulting `dict` has the type `dict[str, str | int]`, which isn't compatible with the `TypedDict`.

Addressing this would require special-case logic that overrides the type information in the builtins.pyi stub, which is something we generally don't do.

The recommended approach is to use one of the other two mechanisms in your example — either call the TypedDict constructor directly or use the Python dict expression syntax.

**Comment by Diogo-Rossi** [comment]
@erictraut Thanks for clarify. I will close this issue.
