### ISSUE TITLE
Pylance doesn't trigger if file created by command code

### ISSUE THREAD

**Issue by nguyendviet** [microsoft/pylance-release#2260]
Issue Type: <b>Bug</b>

If I create a new file using command `code`, Pylance doesn't start checking for issues. I have to restart VSCode window to make it work.
If I create a new file using command `touch` then open it with `code`, Pylance works as expected.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv|. --crash-reporter-id 329fcf0c-6e96-4f0d-92c4-e2d1ecd72ce4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.30.0
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2021.12.2
jupyter|ms-|2021.11.1001550889

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30414010
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vscexrecpromp3t3:30407764

```

</details>

**Comment by heejaechang** [comment]
@nguyendviet I am not sure what you meant by

> If I create a new file using command code, Pylance doesn't start checking for issues. I have to restart VSCode window to make it work.

can you actually give us command you use that we can follow?

> If I create a new file using command touch then open it with code, Pylance works as expected.

same for this one as well. please give us exact steps we can follow to reproduce the issue.

..

also, which type checking mode and diagnostic mode ("python.analysis.diagnosticMode" and "python.analysis.typeCheckingMode") are you using? openFileOnly or Workspace? are  you using "strict" mode?

is the file you mentioned opened in editor in vscocde? or is it closed file?

thank you.

**Comment by heejaechang** [comment]
and please, don't forget to include logs as described in the bug template.

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by erictraut** [comment]
@heejaechang, I think he's talking about commands executed from a terminal on Linux or MacOS. The "touch" command creates a new text file, and the "code" command launches VS Code.

**Comment by nguyendviet** [comment]
Hi @heejaechang and @erictraut .
Please see more details below.
```
code test.py
```
After I save, `pylance` doesn't check for errors.
<img width="397" alt="Screenshot 2022-04-21 at 15 19 39" src="https://user-images.githubusercontent.com/30057363/164537030-2402ac9e-e70c-4830-bfdc-38e1bd7877c4.png">

```
touch test2.py && code test2.py
```
Same content but `pylance` checks for undefined vars. 
<img width="682" alt="Screenshot 2022-04-21 at 15 19 47" src="https://user-images.githubusercontent.com/30057363/164537097-49511d28-c231-4a22-9d51-859614d0fbad.png">

My [Pylance Language Server log](https://gist.github.com/nguyendviet/21e03c1ac71ebdaf83653f918462fbc1).

I hope this helps.

**Comment by heejaechang** [comment]
@nguyendviet I couldn't repro this. can you provide us log to make sure pylance is running?

see here for how to get the log - [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by nguyendviet** [comment]
Hi @heejaechang , I provided the log in my previous comment: https://gist.github.com/nguyendviet/21e03c1ac71ebdaf83653f918462fbc1

Please let me know if you need more info.

**Comment by heejaechang** [comment]
@nguyendviet I still can't repro. if I see your logs (assuming the log captures what you said [here](https://github.com/microsoft/pylance-release/issues/2260#issuecomment-1105664079) and test.py and test2.py are the files that having issues.)

the log shows this

```
(99576) [BG(1)] analyzing: /Users/viet/github/algorithms/test.py ...
(99576) [BG(1)]   parsing: /Users/viet/github/algorithms/test.py (0ms)
(99576) [BG(1)]   binding: /Users/viet/github/algorithms/test.py (0ms)
(99576) [BG(1)]   checking: /Users/viet/github/algorithms/test.py (6ms)
(99576) [BG(1)] analyzing: /Users/viet/github/algorithms/test.py (6ms)

(99576) [BG(1)] analyzing: /Users/viet/github/algorithms/test/test2.py ...
(99576) [BG(1)]   checking: /Users/viet/github/algorithms/test/test2.py (1ms)
(99576) [BG(1)] analyzing: /Users/viet/github/algorithms/test/test2.py (1ms)

```

so, error checking should ran for both. 

we will need more detail repro steps. otherwise, there are not much we can do.

**Comment by nguyendviet** [comment]
@heejaechang Thank you for your reply. I'm currently using VS code version
```
Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z (1 wk ago)
```
and I cannot reproduce the error today. I assume it's been fixed since I last encountered it. I'll mark this issue as Closed.

Thank you for your help!
