### ISSUE TITLE
Enum member already declared in if/else in init

### ISSUE THREAD

**Issue by legra-ms** [microsoft/pylance-release#2266]
## Environment data

-   Language Server version: v2022.1.1
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2

## Expected behaviour

Given the following code, there should be no errors.
```python
from enum import Enum

class ElmoEnum(str, Enum):
    BALSAMIC = "balsamic"
    VINEGAR = "vineguh"
    ROCCO = "rocco"

    def __init__(self, word: str):
        if word == "rocco":
            self.isBigWordForElmo = False
        else:
            self.isBigWordForElmo = True
```

## Actual behaviour

Pylance believes that the assignment in `else` is invalid since it has already been declared in the `if` section. Pylance should not declare this assigment as invalid.

![image](https://user-images.githubusercontent.com/56611012/150410886-3f5cb8e0-df90-4cbe-886c-5445aa7e5893.png)

## Code Snippet / Additional information

The following code works and does not throw an error.
```python
class ElmoEnum(str, Enum):
    BALSAMIC = "balsamic"
    VINEGAR = "vineguh"
    ROCCO = "rocco"

    def __init__(self, word: str):
        if word == "rocco":
            isBigWordForElmo = False
        else:
            isBigWordForElmo = True

        self.isBigWordForElmo = isBigWordForElmo
```

**Comment by erictraut** [comment]
Thanks for the bug report. This will be addressed in the next release.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.3, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202213-21-january-2022)

**Comment by erictraut** [comment]
I can confirm that this is fixed in the latest version of pyright. I think the change was made after last week's release of pylance. It should be included in this week's release.

**Comment by legra-ms** [comment]
@erictraut Thanks!
