### ISSUE TITLE
Pylance is attempting to parse interactive window output and showing errors in Problems window

### ISSUE THREAD

**Issue by amunger** [microsoft/pylance-release#2268]
Issue Type: <b>Bug</b>

I did a fresh reload, opened a .py script and ran a cell in the IW.
result: the cell ran and the problems window is showing issues with the connection information output from the IW

Extension version: 2022.1.1001696915
VS Code version: Code - Insiders 1.64.0-insider (753319a08f8e74700b1dba3a29bf0a6af7c2953f, 2022-01-12T05:16:42.486Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (12.87GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30421239
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstartedc:30421358
vscop804:30404766
vs360cf:30404996
vsclayoutctrc:30405799
azactmsalcf:30409288
vsccppwtstudy:30421978

```

</details>

**Comment by greazer** [comment]
We believe this is due to Pylance not skipping non-python cells.

**Comment by debonte** [comment]
I was unable to repro this. @amunger confirmed: "I don't see it anymore, even on last week's version."
