### ISSUE TITLE
vegas_datasets not supported for intellisense/hover/goto definition

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#227]
This code here should allow you to see an altair dataset (run it in the interactive window after pip installing altair and vega_datasets)

```
# %% Altair (vega)
import altair as alt
from vega_datasets import data

iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```

However autocomplete/goto definition etc does not work for 'vega_datasets'

**Comment by rchiodo** [comment]
Altair doesn't seem to work correctly either. Go to def sometimes jumps to the right spot, but sometimes goes nowhere.
![goto def](https://user-images.githubusercontent.com/19672699/89835931-909c0c80-db1a-11ea-885a-00cb9a74fa13.gif)

**Comment by judej** [comment]
Tried this on the latest release and was able to go to definition. The completions are missing because of the lack of type stubs for the `vega_datasets` module.
![227](https://user-images.githubusercontent.com/547753/104506719-9f3f9180-559a-11eb-8021-984561723adc.gif)

Please reply if the go to definition is still not working.
Thanks

**Comment by jakebailey** [comment]
I've tested this out; it doesn't work on the first call, but on the second call it does work. It doesn't matter how long you wait until you make the first request. There must be a bug here where we do some work and then suddenly we do have the analysis, which doesn't seem right.

You can always go-to-def on `data`, however, and if you do that, then go-to-def on `vega_datasets` does work after as though you had made a request previously. Seems like an instance where there's some state that's only produced once something has been walked, so the side effect of walking the AST to get something brings it in for future calls (but not the current one?).

**Comment by jakebailey** [comment]
The remaining issue is https://github.com/microsoft/vscode-python/issues/15727.

**Comment by jakebailey** [comment]
The above is fixed in the core extension, so I think this should all be working. The source mapper was fixed to handle these go-to-defs a while ago, so all that was left was the core extension bug.
