### ISSUE TITLE
F2 rename variable doesn't work

### ISSUE THREAD

**Issue by johanrex** [microsoft/pylance-release#2273]
## Environment data

 -   vscode version: 1.63.2 (user setup)
 -   Jupyter Extension version: v2021.11.1001550889
 -   python extension version: v2021.12.1559732655
 -   OS: Windows 10
 -   python version: 3.10.0
 -   conda version: 4.10.3
 -   Jupyter server running: I assume local. Don't know what this is. 

## Expected behaviour

F2 keyboard shortcut can rename a variable in the current file. 

## Actual behaviour

F2 on a variable does bring up the change variable window, but does not change the variable name and this error message is displayed:

    No result. No result.

## Steps to reproduce:

Create a new .ipynb file in vscode.

Add some code with a variable, e.g.:

    some_variable = 'hello'
    some_variable += some_variable

Place cursor on the variable and press F2. Give the variable a new name and press Enter. 

Instead of changing the variable name an error message is displayed.

**Comment by FOMX** [comment]
> This looks to be an issue in pylance. Pylance is returning 'no result' when the file is untitled.

I have the same issue on a saved file. It happens in a jupyter notebook (. ipynb) but not in a .py file. 
The "show preview" shortcut  (Shift+enter) also doesn't work. It executes the cell as you can see in the attached gif.

My environment data is basically the same as OP, 
I included my pylance language server version below. 

## Environment Data
- VS Code version: 1.63.2
- Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
- Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
- OS (Windows | Mac | Linux distro) and version: Windows 10 Pro
- Python and/or Anaconda version: Python 3.10.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
- Jupyter server running: Local

- Pylance extension + language server version: v2022.1.3


## Logs
I enabled Trace logging, but no additional logs were produced while recording the attached gif. 

![ezgif-3-672c23b63e](https://user-images.githubusercontent.com/20251588/150671314-dde1880a-1677-4d8a-8c07-b6ee79ddfefe.gif)

**Comment by heejaechang** [comment]
it looks like it works as expected in our internal version. but it will take a few release until current internal version is enabled by default.

**Comment by Caerno** [comment]
https://user-images.githubusercontent.com/5860476/154812388-1449db3d-0471-44ae-abad-75e12b99f0a1.mp4

![Code_pJkHChWx1o](https://user-images.githubusercontent.com/5860476/154812391-157f5d53-e6f4-470e-8481-b4e8f0416731.png)
![Code_xmDj95OvLp](https://user-images.githubusercontent.com/5860476/154812392-4eb3a56a-442f-4c85-b601-9722e8c78eaa.png)

**Comment by johanrex** [comment]
@heejaechang  Yes, `"jupyter.pylanceHandlesNotebooks": true,` solves the issue. But it introduces some odd syntax highlighting bugs I haven't seen before. 

Notice the first quote character is colored different that the others and the aaa variable in the first cell is colored differently than in the second. 
![bild](https://user-images.githubusercontent.com/6969298/158263621-62d392ae-00ec-40fc-a0e5-3fdbe84563ee.png)

**Comment by heejaechang** [comment]
that option is testing internal bits, and probably only works correctly with insider versions of all extensions (vscode, python, pylance). I wasn't trying to suggest using it but want to confirm that rename is enabled with internal bits.

**Comment by johanrex** [comment]
@heejaechang that makes sense. So now we know there is a fix at least in the internal testing code. Looking forward to it reaching out to us mere mortals in the release version of the plugin. :)

**Comment by heejaechang** [comment]
we are trying to consolidate multiple notebook experiement to one.

rename issue should be fixed in next release with this option on in user settings.json

"python.pylanceLspNotebooksEnabled": true,

**Comment by heejaechang** [comment]
closing as a dup - https://github.com/microsoft/pylance-release/issues/3061
