### ISSUE TITLE
Syntax highlighting and completions for `__all__`

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#2290]
Somewhat related to #2289

Pylance does already have (limited) support for syntax highlighting and completions in string annotations. It would be awesome if something similar could be implemented for `__all__`.

<img width="366" alt="Screen Shot 2022-01-26 at 16 46 46" src="https://user-images.githubusercontent.com/30130371/151196667-8411ca6f-6ca8-47ce-a272-7baeff7dded4.png">

<details>
<summary>Example code</summary>

```py
from .const import CustomConstant

__all__ = [
    "CustomConstant",
    "func",
    "SomeClass",
]

def func(): ...

class SomeClass: ...
```
</details>

**Comment by judej** [comment]
Thanks for the request. This is not something that is currently supported but will reevaluate based on upvotes or community feedback.

**Comment by judej** [comment]
Captured in discussion #2289
