### ISSUE TITLE
Recognize private methods outside the class

### ISSUE THREAD

**Issue by jadeidev** [microsoft/pylance-release#2297]
Recognize calls of private methods outside the class through name mangling. Currently, this is the issue:
![image](https://user-images.githubusercontent.com/32917209/151454786-631616f8-79d7-499e-a4fd-b464fa33791f.png)

**Comment by erictraut** [comment]
This is intentionally flagged as an error. 

Code shouldn't rely on the name mangling algorithm to access private variables. The details of name mangling are an implementation detail of the Python interpreter, and the mangling is done to prevent accesses like this.

If you want to allow access to an attribute or method outside of the class, you should either make it non-private or add a public property or accessor method.

You could also use `obj.__getattribute__('_A__fun')()`, but that once again relies on the mangled name, which is not recommended.

**Comment by jadeidev** [comment]
thanks
