### ISSUE TITLE
Django. Typing for get_user_model()

### ISSUE THREAD

**Issue by Bazulenkov** [microsoft/pylance-release#2301]
## Environment data

-   Language Server version: v2022.1.5
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.10

## Expected behaviour

This would be an improvement:

`def get_user_model() -> Type[AbstractUser]: ...`

Better yet, could pylance introspect settings and determine the real type that is returned?

## Actual behaviour

Right now, typing for get_user_model() is implemented like:

`def get_user_model() -> Type[Model]: ...`

This is pretty useless for many cases, and inevitably results in a cast or a # type: ignore.

## Code Snippet / Additional information

Look at https://github.com/Bazulenkov/yatube/blob/77dcf4cb88bd0357fc473a94038860807bca4249/posts/tests.py#L14

https://user-images.githubusercontent.com/38315253/151393798-e8ec58b1-bb86-489e-a6a6-68c988899c64.png

**Comment by judej** [comment]
Thanks for the report. This is due to the dynamic behavior of Django. We don't do that currently.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
