### ISSUE TITLE
Big powers cause `int` to become `Any`

### ISSUE THREAD

**Issue by Molkree** [microsoft/pylance-release#2311]
## Environment data

-   Language Server version: v2022.1.5
-   OS and version: Win10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.2

## Expected behaviour

Type inferred as `int`.

## Actual behaviour

Type inferred as `Any`.

## Code Snippet / Additional information

```python
big_int = 2**25  # you can multiply by 100 and it will still be `int`
bigger_int = 2**26  # Any
reveal_type(big_int)
reveal_type(bigger_int)
```

`big_int` is correctly inferred as `int` but `bigger_int` becomes `Any`. Is it some limitation of pyright? mypy seems to infer the correct type with arbitrarily large powers:
![image](https://user-images.githubusercontent.com/12860284/151870395-8ae46798-3d5f-42e5-8b30-2869e717fa9c.png)

**Comment by erictraut** [comment]
This is a limitation of the Python type system. The `__pow__` method provided by the `int` class can return a `complex`, `float` or `int` depending on the value of the right-hand operand. The typeshed stub `builtins.pyi` [declares several overloads](https://github.com/python/typeshed/blob/f86f096e1ce6d414d726b75560368807b5759260/stdlib/builtins.pyi#L233) that handle common (small) integer exponents, but there's a limit to this approach.

Mypy apparently special-cases this particular case in the type checker and overrides the types in the type stub. That's something we generally don't do.

**Comment by Molkree** [comment]
> The typeshed stub `builtins.pyi` [declares several overloads](https://github.com/python/typeshed/blob/f86f096e1ce6d414d726b75560368807b5759260/stdlib/builtins.pyi#L233) that handle common (small) integer exponents, but there's a limit to this approach.

Hm, alright, I see it:
```py
_PositiveInteger = Literal[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
```

I wonder how this cutoff was chosen and why there's no 0 anywhere because `2**0` also produces `Any`... But I guess this is not a Pylance issue.
