### ISSUE TITLE
Do you have same performances problems ?

### ISSUE THREAD

**Issue by rousseldenis** [microsoft/pylance-release#2313]
System: Ubuntu 20.04
Vscode: 1.63.2
Pylance: 2022.1.5

For few weeks, I have great performances problems with Pylance.

If I display htop :

![image](https://user-images.githubusercontent.com/19529533/151951161-16b5d3be-4665-4a82-9f27-b54ae1690df7.png)

My laptop is going crazy when developing as CPU is suffering(fan is making noise permanently). 

I'm wondering if there are fine tuning settings ?

Do people have same issues ?

**Comment by ewjoachim** [comment]
Came here to say the same, so yeah. though I don't seem to have threads, it seems the main pylance process is taking 100% of a CPU
<img width="1440" alt="Capture d’écran 2022-02-01 à 11 38 36" src="https://user-images.githubusercontent.com/1457576/151953733-627b778a-c8ca-40d0-bb9d-7a552281587a.png">
.

**Comment by ewjoachim** [comment]
Hm, this could be a duplicate from https://github.com/microsoft/pylance-release/issues/1368
(or maybe it isn't)

**Comment by ewjoachim** [comment]
I'm not sure it's the same problem, actually. I'll open an issue with my details, worst case scenario, if we confirm it's the same issue, we'll close.

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by bhy** [comment]
I also have high CPU load problem on MacOS and reverting Pylance to v2022.1.3 seems completely resolve it.

**Comment by bschnurr** [comment]
Can you post your logs before and after?

Enable trace logging by adding "python.analysis.logLevel": "Trace" to your settings.json configuration file.
Adding this will cause a large amount of info to be printed to the Python output panel. This should not be left long term, as the performance impact of the logging is significant.

**Comment by EldhosePoulose** [comment]
i also have CPU load problem i am using windows, i used the pylance v2022.2.0 

it took 6 minutes to load a jupyter notebook

**Comment by heejaechang** [comment]
we need logs to find out what is happening. without the log, not much we can do. (https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)

**Comment by EldhosePoulose** [comment]
https://github.com/microsoft/pylance-release/issues/2313#issuecomment-1030591676

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
