### ISSUE TITLE
Top level await in notebook recognized incorrectly in assignment statements

### ISSUE THREAD

**Issue by richbon75** [microsoft/pylance-release#2320]
## Environment data

-   VS Code version:  1.63.2
-   Jupyter Extension version (available under the Extensions sidebar):  Tested both current release: v2021.11.1001550889 and pre-release: v2022.1.1001760686
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: macOS Catalina Version 10.15.7
-   Python and/or Anaconda version: Python 3.9.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

I think this is closely related to the issue raised in [Issue 1510 - Top level await in notebook recognized incorrectly](https://github.com/microsoft/vscode-jupyter/issues/1510)

While the `await` keyword is no longer flagged if it is the first token in a statement, like:
`await hello()`
it is still flagged if it is used in an assignment statement, like in the context:
`greeting = await hello()`

Use of the `await` keyword in top-level notebook code should not be flagged with Pylance error `"await" allowed only within async function` since effectively the notebook environment _is_ an async function.

## Actual behaviour

When `await` is not the first element in the line (or even if there is a comment at the end of the line!) it is flagged as an error, even though actually executing the code works fine and produces the expected result.

## Steps to reproduce:

1. Create a new notebook file, `async_test.ipynb`
2. In the first cell, enter this code and execute it.  No errors.
```
async def hello(name="World"):
    return f'Hello {name}!'
```
3. In the second cell, enter this code and execute it. Notice that it does _not_ result in a Pylance message, and it produces the expected output.
```
await hello('Bob')
```
4. In the third cell, enter this code and execute it.  Notice that although it runs successfully and produces the expected output, it DOES result in a Pylance message.
```
greeting = await hello('Alice')
print(greeting)
```

![image](https://user-images.githubusercontent.com/8406130/151680649-ee75361c-823c-49d9-a7bc-80ef0ab2b08e.png)

**Comment by heejaechang** [comment]
this is a dup of https://github.com/microsoft/pylance-release/issues/1754
