### ISSUE TITLE
Function is not a known member of module

### ISSUE THREAD

**Issue by berkdemir** [microsoft/pylance-release#2328]
Hi,
There are couple of questions regarding this, but those are referring to torch or numpy, this is my own module. Similar issues: #1860 or #1447  

I have created a package and sub-modules that I import. To be able to import like `import my_package as pck` and reach submodules, I have also written the following code in the __init__.py file.

```python
import pkgutil

__all__ = []
for loader, module_name, is_pkg in pkgutil.walk_packages(__path__):
    __all__.append(module_name)
    _module = loader.find_module(module_name).load_module(module_name)
    globals()[module_name] = _module
```

But, when I call the submodules and functions inside them like `pck.module1.function1`, VSCode writes `function1 is not a known member of module`. 

I have seen that problem is related to type stub of other big modules that are compiled, but for me, this is my own simple package, I cannot understand why this happens. Is there something I should change in init file of package or submodules?

**Comment by bschnurr** [comment]
is my_package a known relative path?

ie something like 'from xxxx import my_package as pck`   where 'xxx' is a relative path

**Comment by erictraut** [comment]
The problem is that you're manipulating the global namespace programmatically. Tools like pylance use static analysis. It doesn't execute the code in your files, so it doesn't know about the dynamic namespace modifications you're making at runtime. 

If you want your module to work with pylance or any other static analysis or type checking tools, you would need to use normal import statements and a static definition of `__all__`.

**Comment by berkdemir** [comment]
Hi again,

Package is not in relative path.

And if I define __all__ manually, that should solve the problem. I will try and report.

**Comment by erictraut** [comment]
```python
from . import my_submodule1, my_submodule2, my_submodule3
```

**Comment by berkdemir** [comment]
That's exactly what I am trying not to do. I want to use the numpy like structure where all calls will be made to np.

**Comment by erictraut** [comment]
I'm not sure what you mean by "numpy like structure where all calls will be made to np". Can you elaborate?

I thought you wanted to re-export your submodules from the top-level (__init__) module.

**Comment by berkdemir** [comment]
Sorry, I wasn't clear.

`import my_package as pck
pck.module1.func1()
pck.module2.anotherfunc()
`
My aim is using this structure, I don't want to import all modules, modules are already stored in pck. To do that, I needed `__all__` but if I need manual definition instead of the function that I shared in the first post, that's OK. But I would like to keep the structure I showed above.

**Comment by erictraut** [comment]
Yes, then you'll need to do what I suggested above.

You need to change your `__init__.py` to the following:
```python
from . import module1, module2
__all__ = ["module1", "module2"]
```

This re-exports `module1` and `module2` from the namespace of the top-level module, but it does so in a static manner without dynamically manipulating the top-level module's namespace.

You can then use the following pattern in code that imports from this package:
```python
import my_package as pck
pck.module1.func1()
pck.module2.anotherfunc()
```

**Comment by judej** [comment]
Closing inactive issue, please reopen if this is still an issue
