### ISSUE TITLE
Missing releases for last two versions

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#2331]
Would it be possible to continue doing a release just for the notable changes and a link to the changelog? I found it always to be quite helpful. For reference #625

**Comment by debonte** [comment]
Good to know that people still find these useful. I added the releases this morning. Sorry for the omission. We are planning to continue creating these for future releases.

https://github.com/microsoft/pylance-release/releases/tag/2022.1.5
https://github.com/microsoft/pylance-release/releases/tag/2022.2.0

**Comment by cdce8p** [comment]
Thanks, much appreciated!
