### ISSUE TITLE
Folding issues on v1.4

### ISSUE THREAD

**Issue by sayyid5416** [microsoft/pylance-release#2333]
Issue Type: <b>Bug</b>

Foldings were working fine on earlier versions, but from v1.4 of VS Code, since new better foldings were introduced, some foldings are not working correctly.

Look at the screenshot to understand the issue.

Extension version: 2022.0.1786462952
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.22543
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.66GB free)|
|Process Argv|--crash-reporter-id b3d6d8a6-e711-4a16-8e55-6bdc2a1f7eda|
|Screen Reader|no|
|VM|0%|
</details>

Reference Link: https://code.visualstudio.com/updates/v1_64#_python

**Comment by debonte** [comment]
Maybe related to #1768? Trailing paren isn't included in parse node text range.

**Comment by sayyid5416** [comment]
@debonte Any update regarding this?

**Comment by debonte** [comment]
We believe it is a parser issue related to parens, but haven't had time to dig into it yet.

**Comment by erictraut** [comment]
@debonte, is your theory that the parser is generating a range that includes the opening paren but not the closed paren? I could dig into that to confirm. If that's the case, it should be easy to fix.

**Comment by debonte** [comment]
@bschnurr knows more about this.

**Comment by bschnurr** [comment]
I think I need to revert a fix that was excluding the parens from an expression. but then I'll need to fix issues with multiline semantic tokens too a different way.

**Comment by sayyid5416** [comment]
I believe, It's been fixed in #3085. Confirmed in 
![image](https://user-images.githubusercontent.com/78584556/187035764-ba823bf3-346d-4e3b-b270-6ce55359754d.png)

**Comment by debonte** [comment]
This is still broken. A fix is in progress though.

**Comment by debonte** [comment]
This issue was fixed in prerelease version 2022.9.21 and is now also available in release version 2022.9.30.
