### ISSUE TITLE
Stop false reportUndefinedVariable warnings by supporting a  custom list of strings to describe 'magic' variables Pylance is unaware of

### ISSUE THREAD

**Issue by JamesParrott** [microsoft/pylance-release#2334]
Hi everyone,

Thanks for the awesome work.  Pylance has been super helpful so far.

I was getting the same set of _Unresolved Import_ warnings, which I was delighted to discover I could turn off by adding the following to _settings.json_:

```
"python.analysis.diagnosticSeverityOverrides" :{
        "reportMissingImports" : "none"}

```
So cheers.  However I do find _"misspelled_variable" is not defined_ warnings to be invaluable and don't want to turn all of them off. So while I can also set the warning level, I would really like to allow valid warnings through only if they are not due to the same set of context-specific 'magic variables' I am working with.  I suggest using a filter, that the user can define as an array of strings (still valid JSON), e.g. :

```
"python.analysis.diagnosticSeverityOverrides" :{
        "reportUndefinedVariable": "warning",
        "ignoreUndefinedVariables": ["magic_variable_1", "magic_variable_2", "magic variable_3"]

}

I appreciate it's possible to add `# type : ignore` on the usual suspect lines, or `import TYPING` (see below).  But Pylance would be even better, if every single one of its users with this same problem didn't have to alter their source code.  It's a bit much to ask from everyone, just to accommodate a simple missing feature.  Personally I'm more likely to use an alternative that supports such a filter.
https://github.com/microsoft/pylance-release/issues/929
```

**Comment by erictraut** [comment]
Can you say more about the "magic variables" you're using? Are they global variables (e.g. injected into the builtins global namespace or injected into every module namespace)? Or are they class variables? Local variables?

**Comment by JamesParrott** [comment]
Thanks - much appreciated.  Of course I can.  The magic variables are globals. After testing, indeed they aren't accessible by every imported module in its own namespace (thanks for asking - your question helped me understand what's going on under the hood a bit more).  

If there's way more to this than I've realised then fair enough.  But personally I'd be happy to own errors resulting from a filter I myeslf put in there.  I'm not just relying on Pylance at the end of the day, I'm carrying out a test or two too.

**Comment by erictraut** [comment]
OK, thanks for the additional information. 

We've received several requests recently for similar functionality, so I added a new mechanism to address this use case. It allows you to specify a local `__builtins__.pyi` stub file that defines additional symbols that are "injected" into the global namespace for your project. You simply create this file in your project root directory or alternatively in a project subdirectory referenced by the "python.analysis.stubPath" setting (which defaults to the directory name "typings").

You can then fill in type definitions for the symbols you would like to "inject". Note that this isn't limited to variables. It works for functions, constants, type aliases, etc.

```python
# __builtins__.pyi

magic_variable_1: int
magic_variable_2: str

def magic_function(a: int, b: str) -> str: ...

MEANING_OF_LIFE: Final = 42
```

This functionality didn't make it into this week's version of Pylance, but it will be included in next week's release.

For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/builtins.md).

**Comment by JamesParrott** [comment]
Brilliant!  I look forward to trying it out.  Thanks ever so much :)

**Comment by Yashrajjjjjjj** [comment]
wow

**Comment by ennajari** [comment]
Great solution with `___builtins__.pyi!_`  Just wanted to add a few alternative approaches for anyone landing here:
1. Using `__builtins__.pyi` (recommended — as described above)
Create a `__builtins__.pyi` file in your project root or typings/ directory:

```
# __builtins__.pyi
magic_variable_1: int
magic_variable_2: str
```

2. Inline `# type: ignore `comment
For one-off cases, suppress the warning on a specific line:

`result = magic_variable_1 + 1  # type: ignore[name-defined]`

` [name-defined]` is more precise than a bare `# type: ignore.`

3. Using `pyrightconfig.json`
If you prefer a project-level config over `settings.json`, you can set `reportUndefinedVariable `in `pyrightconfig.json` (Pylance uses Pyright under the hood):
```
json{
  "reportUndefinedVariable": "warning"
}
```
4. Declaring variables with `TYPE_CHECKING`
If you want type-checker-only declarations without a stub file:
f```
rom typing import TYPE_CHECKING
if TYPE_CHECKING:
    magic_variable_1: int
```
This block is ignored at runtime but visible to Pylance.

**Comment by emanuelpereirarodrigues326-ctrl** [comment]
miluty
