### ISSUE TITLE
Recognizing a monkey-patched method

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#2335]
We are working with a third party library that monkey patches in methods into a class.  The way they do it, pylance (or maybe pyright) isn't picking up that the monkey patched method is valid.   I've created a simple example that illustrates what happens:
```python
class Foo():

    def __init__(self, x:int):
        self._x = x
        self.set_target()

    def set_target(self):
        self.get_x = get_x    

def get_x(y:int) -> int :
    return y


class Foo2(): 
    
    def __init__(self, x:int):
        self._x = x
        set_target(self)

def set_target(trgt):
    trgt.get_x = get_x



def main(): 

    f = Foo2(10)
    print(f.get_x(2))
    g = Foo(10)
    print(g.get_x(1))

main()
```
The third party library uses the pattern shown in the class `Foo2`, where a global function is used to patch in methods to the class.  If you load the above code into VSCode, then the call to `f.get_x(2)` is marked as invalid, because it doesn't know about the method `get_x()`.  But for the call `g.get_x(1)`, it has no issue in determining that `get_x` was patched in, because the patching is done within the class.

Now the vendor (IBM in this case) should use the pattern in `Foo` above, but their code isn't on GitHub, so that means I need to convince them to do that.  

The other option is that pylance/pyright recognizes this pattern and sees that monkey-patching via the method used in `Foo2` is valid.

**Comment by erictraut** [comment]
This is a really dangerous and fragile practice. What if the class in question happens to have a `get_x` attribute already? While Python does allow this type of dynamic modification at runtime, it completely goes against the rules of static typing. This is a type violation, and pyright is correct to flag it as such.

Here are a few potential workarounds:
1. Use a cast (`cast(Any, f).get_x(2)`). You could also create a protocol class with the `get_x` method defined if you don't want to cast to `Any`.
2. Use a `# type: ignore`.

The best answer is to get the third party to avoid this pattern in their code.

**Comment by Dr-Irv** [comment]
> 
> While Python does allow this type of dynamic modification at runtime, it completely goes against the rules of static typing. This is a type violation, and pyright is correct to flag it as such.

I agree with you - just wanted to see if there was some way to deal with it, because they are monkey patching about 30 methods, and we don't want to change each of the calls throughout our code (or put `#type: ignore` comments) just because they did something stupid.

> The best answer is to get the third party to avoid this pattern in their code.

Well, the third party is IBM, and as a former IBM employee, I can tell you getting them to do anything is a huge chore!  Having said that, I have reached out to them about this.

**Comment by judej** [comment]
Closing since there is no action for Pylance
