### ISSUE TITLE
Pylance shows errors when using typing.ParamSpec or typing.Concatenate as the first argument of typing.Callable.

### ISSUE THREAD

**Issue by jorge4larcon** [microsoft/pylance-release#2337]
## Environment data

-   Language Server version: v2022.2.0
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7, Ubuntu 21.10 (GNU/Linux 5.13.0-28-generic x86_64)

## Expected behaviour

Python type annotations [`typing.Callable`](https://docs.python.org/3/library/typing.html#typing.Callable) and [`collections.abc.Callable`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Callable) must always be used with exactly two values: the argument list and the return type. The argument list must be a list of types or an ellipsis; the return type must be a single type. Look at the following example:
```python
from collections.abc import Callable


def foo(n: int) -> str:
    return str(n)


def call_foo(f: Callable[[int], str]):
    f()
```
The first argument of `typing.Callable` can also be [`typing.Concatenate`](https://docs.python.org/3/library/typing.html#typing.Concatenate) and [`typing.ParamSpec`](https://docs.python.org/3/library/typing.html#typing.ParamSpec) according to the official Python documentation:

![image](https://user-images.githubusercontent.com/54189123/152652900-dfe7f723-728d-48be-a8d0-826d8220ed89.png)
![image](https://user-images.githubusercontent.com/54189123/152652939-520f268a-517a-4bf2-a137-9115da09fccb.png)

## Actual behaviour

Pylance only supports the list of types and the ellipsis as the first argument of `typing.Callable`:

![image](https://user-images.githubusercontent.com/54189123/152653166-a963683c-c733-4edd-807d-5b7e798866e8.png)

And does not support using `typing.Concatenate` or `typing.ParamSpec`.

## Logs

```
XXX
```

## Code Snippet / Additional information

You can use this snippet to test that Pylance shows errors when using `typing.Concatenate` or `typing.ParamSpec` as the first argument of `typing.Callable`.
```python
from collections.abc import Callable
from threading import Lock
from typing import Concatenate, ParamSpec, TypeVar

P = ParamSpec('P')
R = TypeVar('R')

# Use this lock to ensure that only one thread is executing a function
# at any time.
my_lock = Lock()

def with_lock(f: Callable[Concatenate[Lock, P], R]) -> Callable[P, R]:
    '''A type-safe decorator which provides a lock.'''
    global my_lock
    def inner(*args: P.args, **kwargs: P.kwargs) -> R:
        # Provide the lock as the first argument.
        return f(my_lock, *args, **kwargs)
    return inner

@with_lock
def sum_threadsafe(lock: Lock, numbers: list[float]) -> float:
    '''Add a list of numbers together in a thread-safe manner.'''
    with lock:
        return sum(numbers)

# We don't need to pass in the lock ourselves thanks to the decorator.
sum_threadsafe([1.1, 2.2, 3.3])
```
This example was taken from the [Python documentation](https://docs.python.org/3/library/typing.html#typing.Concatenate),

**Comment by erictraut** [comment]
`ParamSpec` and `Concatenate` were added in Python 3.10, but it looks like you're using Python 3.9. You therefore need to download and install a recent version of the `typing_extensions` package, which provides backward compatibility. You can then import `ParamSpec` and `Concatenate` from `typing_extensions`. Alternatively, you can install Python 3.10.

I also recommend that you enable basic type checking, which provides additional errors that would have made it easier for you to figure out the underlying problem. To enable type checking in pylance, set "python.analysis.typeCheckingMode" to "basic".

**Comment by jorge4larcon** [comment]
Thank you so much for your kind support.
