### ISSUE TITLE
pandas  module Not found

### ISSUE THREAD

**Issue by ssain2021** [microsoft/pylance-release#2342]
I was working with pandas library for long. Since 02-Feb-2022, or, 03-Feb-2022,  I am receiving 'Module Not Found Error'.
 Though pandas is currently installed.

## Environment data

-   Language Server version:  Pylance  v2022.2.0  (Microsoft VS Code)
-   OS and version: Windows 11 Home Single Language /  Version  21H2 /  Build  22000.434
-   Python 3.10.0

## Expected behaviour
    My python code should compile with 'import pandas as pd'   

## Actual behaviour
 It is throwing following error :
  ModuleNotFoundError: No module named 'pandas'

## Logs
File "c:\Sukhendu\Upwork-PARTS Engine\SCRAPING-Python\My-WORK\DV8-Offroad-SELENIUM-Auto.py", line 16, in <module>
    import pandas as pds
ModuleNotFoundError: No module named 'pandas'

## Code Snippet / Additional information

from ast import Break
from distutils.filelist import findall
from queue import Empty
from sre_constants import CATEGORY, LITERAL_IGNORE
import time, requests
from xmlrpc.client import boolean
from tkinter import Image
from bs4 import BeautifulSoup
from requests.api import options
import json
import time
import requests
import re
import csv
import os
import pandas as pds
from collections import defaultdict

..  Please help with correct library for pandas. 
Thanks,
Sukhendu

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please respond and let us know if that worked.

**Comment by venturi123** [comment]
Hi, judej

I have the same problem and am sure the right conda environment with Python 3.9.5 has been chosen. 

Besides, I found that I could run my script without error, but the Pylance still warned me `Import "pandas" could not be resolved from sourcePylance.`

![image](https://user-images.githubusercontent.com/19996167/153343908-785323eb-b12f-48e6-92dc-902b90c83988.png)

**Comment by zbir84** [comment]
I'm having the same problem and it's doing my head in!! Correct conda env. is selected, with the installed libraries and if I run the script through VS Code it runs fine, but Pylance is reporting missing libraries and non of the autocomplete functions work!

**Comment by lukepighetti** [comment]
I have the right interpreter selected in Jupyter notebook and in VSCode command pallet `Python: Select Interpreter` and yet none of my packages can be found

<img width="406" alt="Screen Shot 2022-04-07 at 7 37 04 AM" src="https://user-images.githubusercontent.com/666539/162190226-bb533bb9-7872-47ec-a63f-41f9c706f29f.png">

**Comment by bschnurr** [comment]
checkout your output pane under your environment name. 
![image](https://user-images.githubusercontent.com/1946977/163272393-27d074ca-ad73-4219-9350-f4ea467dd159.png)

**Comment by bschnurr** [comment]
are you using 'Open Folder' mode?

**Comment by lukepighetti** [comment]
I resolved the issue but I cannot remember how, sorry!

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

without it, there is not much actionable data for us.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
