### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by EldhosePoulose** [microsoft/pylance-release#2347]
Issue Type: <b>Performance Issue</b>

I am facing poor performance from VS code while running my jupyternotebook. Strange that it even cannot run a single cell with only one line of code.

Very poor experience. 
Any help will be appreciated.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.55GB (8.47GB free)|
|Process Argv|--crash-reporter-id 0a2c520f-733f-4c67-a648-75f12c4ca82b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	 14224	code main
    0	   136	  1096	   extensionHost
    0	   212	 14392	     "C:\Users\Eldhose\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Eldhose\.vscode\extensions\ms-python.vscode-pylance-2022.1.5\dist\server.bundle.js --cancellationReceive=file:fcbee996a7614204cd260c9101de29c576f1948c2c --node-ipc --clientProcessId=1096
    0	   222	 14408	     "C:\Users\Eldhose\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Eldhose\.vscode\extensions\ms-python.vscode-pylance-2022.1.5\dist\server.bundle.js --cancellationReceive=file:2eff5581a9bd31799308b53bf97e247558b591ccf7 --node-ipc --clientProcessId=1096
    0	    16	 14996	     C:\Users\Eldhose\anaconda3\envs\adsml\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
    0	   110	  5344	       electron_node hl.js 
    0	    10	 14956	       console-window-host (Windows internal process)
    0	   259	 15124	     "C:\Users\Eldhose\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Eldhose\.vscode\extensions\ms-python.vscode-pylance-2022.1.5\dist\server.bundle.js --cancellationReceive=file:a01677a8ce9bd41e0ca684557db96e6304c7064e69 --node-ipc --clientProcessId=1096
    1	    85	  6968	   issue-reporter
    0	    36	  8564	   utility-network-service
    0	   184	 10984	   gpu-process
    0	    96	 13384	   shared-process
    0	    72	  1348	     watcherServiceParcelSharedProcess
    0	    78	 13600	     ptyHost
    0	     6	  5532	       console-window-host (Windows internal process)
    0	    65	 10712	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   175	 13616	   window (Settings - project-adsml-ibex-c1-s1-4946-3104 - Visual Studio Code)
    0	    87	 13780	   window (undefined)
    0	    24	 14300	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - project-adsml-ibex-c1-s1-4946-3104 - Visual Studio Code)
|    Folder (project-adsml-ibex-c1-s1-4946-3104): 59 files
|      File types: csv(34) ipynb(7) json(4) txt(2) yml(1) PNG(1) py(1) pyc(1)
|                  md(1) xls(1)
|      Conf files: onedrive(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.12.1559732655
vscode-pylance|ms-|2022.1.5
jupyter|ms-|2021.11.1001550889
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30428979
pythonvs932:30410667
vscop341:30404997
vsrem710cf:30416617

```

</details>

**Comment by heejaechang** [comment]
@EldhosePoulose can you provide us some repro? such as ipynb file that shows the issue?

**Comment by heejaechang** [comment]
also, if possible, can you provide us log as described here - https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

for notebook, there will be multiple logs from pylance server in output window, can you provide us logs from all those output window? any log related to pylance should have python or pylance in the output window name.

**Comment by EldhosePoulose** [comment]
(pyright 90161194) starting
[Info  - 4:53:36 PM] (12613) Server root directory: /Users/pouloeld/.vscode/extensions/ms-python.vscode-pylance-2022.4.2/dist
[Info  - 4:53:37 PM] (12613) No configuration file found.
[Info  - 4:53:37 PM] (12613) No pyproject.toml file found.
[Info  - 4:53:37 PM] (12613) Setting pythonPath for service "Desktop": "/usr/local/bin/python3"
[Warn  - 4:53:37 PM] (12613) stubPath /Users/pouloeld/Desktop/typings is not a valid directory.
[Info  - 4:53:38 PM] (12613) Assuming Python version 3.9
[Info  - 4:53:38 PM] (12613) Assuming Python platform Darwin
[Info  - 4:53:40 PM] (12613) Searching for source files
[Error - 4:53:50 PM] (12613) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
[Info  - 4:54:05 PM] (12613) Found 438 source files
[Info  - 4:54:05 PM] (12613) Background analysis(1) root directory: /Users/pouloeld/.vscode/extensions/ms-python.vscode-pylance-2022.4.2/dist
[Info  - 4:54:05 PM] (12613) Background analysis(1) started
[Info  - 4:54:09 PM] (12613) [BG(1)] Long operation: checking: /Users/pouloeld/Desktop/_NotebookConcat_84aa233e9b4c.py (2180ms)
[Info  - 4:54:09 PM] (12613) [BG(1)] Long operation: analyzing: /Users/pouloeld/Desktop/_NotebookConcat_84aa233e9b4c.py (3003ms)

**Comment by EldhosePoulose** [comment]
<img width="745" alt="Screenshot 2022-04-21 at 17 23 11" src="https://user-images.githubusercontent.com/28917220/164491909-a7372520-e7b1-4630-a767-762be56fd90d.png">

**Comment by judej** [comment]
After executing the first cell, does it still take a long time? Could it be taking a long time to load the kernel?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
