### ISSUE TITLE
reportOverlappingOverload wrong for overloads with a type and derived type

### ISSUE THREAD

**Issue by EldarSehayekZenity** [microsoft/pylance-release#2350]
<h3> Environment data </h3>

-   Language Server version: 2022.2.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.9, standard Windows installation
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

Consider the following definitions:

```
class MyStr(str):
    pass


TScalarValue = TypeVar("TScalarValue", MyStr, str)


@overload
def print_str(field_type: Type[str]) -> str:
    ...


@overload
def print_str(field_type: Type[TScalarValue]) -> MyStr:
    ...


def print_str(field_type: Union[Type[str], Type[TScalarValue]]) -> Union[str, TScalarValue]:
    print(field_type)

    if field_type == str:
        return "abc"
    return "def"


my_str = print_str(MyStr)

print(my_str)
```

When running the code with Python it's revealed that indeed the `field_type` was `MyStr` based on what's printed and what's returned from the function. Pylance and VS Code Intellisense should treat it the same.

<h3> Actual behaviour </h3>

Pylance errors with reportOverlappingOverload for above, and Intellisense thinks the call `print_str(MyStr)` returns a `str` instead of returning a `MyStr`.

<h3> Logs </h3>

Python Language Server Log
```
I tried but I didn't get any logs...
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by erictraut** [comment]
You have overlapping overload functions that return different return types. That's what the `reportOverlappingOverload` error is telling you.

`MyStr` is a subclass of `str`, so it matches the first overload, and the resulting type is `str`. That's consistent with the hover text.

So I think everything is working as expected here.
