### ISSUE TITLE
Add TensorFlow 2.7 support

### ISSUE THREAD

**Issue by BlueskyFR** [microsoft/pylance-release#2351]
## Environment data

- Language Server version: 2021.11.2 (pyright b27108d5)
- OS and version: Manjaro Linux, latest
- Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Expected behaviour

Autocompletion for TensorFlow should work.

## Actual behaviour

It is not the case:
![image](https://user-images.githubusercontent.com/25421460/144221960-d20ae7f0-743b-4925-96f7-d245d5625a0a.png)

## Logs

No relevant logs, just zero item found by the LS.

## Code Snippet / Additional lnformation

```python
import tensorflow as tf
tf.keras.lay
```

**Comment by bschnurr** [comment]
https://github.com/microsoft/pylance-release/issues/1941#issuecomment-1022430663
