### ISSUE TITLE
Incorrect Problem Report for imported modules

### ISSUE THREAD

**Issue by TianranZhang21** [microsoft/pylance-release#2352]
## Environment data

-   Language Server version: 2022.2.0
-   OS and version: macOS version 12.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Expected behaviour

I copied the example code from numpy documentation, and was able to compile and run the file, but pylance keeps generating error reports

## Actual behaviour

![image](https://user-images.githubusercontent.com/78061467/153114839-6a8b9d42-1eb8-4d6f-af05-2f6ab4faf3bd.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by bschnurr** [comment]
looks like a numpy issue. please log a bug with them https://github.com/numpy/numpy/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

as a workaround this seems to work
`a = np.array([[1,2],[3,4]], np.int32)`
