### ISSUE TITLE
flask import not  found

### ISSUE THREAD

**Issue by tush-viky** [microsoft/pylance-release#2356]

**Comment by luabud** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please respond and let us know if that worked.

**Comment by judej** [comment]
Closing inactive issue, please reopen if this is still an issue
