### ISSUE TITLE
reportMissingModuleSource Import "py.xml" could not be resolved from sourcePylance

### ISSUE THREAD

**Issue by zeusweb-1** [microsoft/pylance-release#2357]
Environment

Windows 10
Pylance v2022.2.0
Python v2022.0.1814523869
Pytest BDD v0.3.17

Python 3.10.2 with venv

The following code reports a problem in VSCode
from py.xml import html

In 'normal' python the following appears to work correctly
from py.xml import html
print ( html.th('Ticket'))

Which prints the following
<th>Ticket</th>

The version of py listed by pip is
py       1.11.0

**Comment by debonte** [comment]
Dynamic behavior?

**Comment by browneye1826** [comment]
Same issue here. In Conda env, but Pylance is not seeing the modules.
