### ISSUE TITLE
Rename symbol (F2) failed in files that are not part of the current project

### ISSUE THREAD

**Issue by yansnow78** [microsoft/pylance-release#2358]
-   Language Server version: Pylance language server 2022.2.0
-   OS and version: Windows 10
-   Python version : Any version

## Expected behaviour

Rename symbol (F2) should also work when you rename symbol that is defined in one the following location:
- site-packages python files 
- files present in one of the path present in PYTHONPATH or in a folder other than 

## Actual behaviour

i get "no result" whenever i try to rename a symbol (f2) that is defined in site-packages python files or in files present in one of the path present in PYTHONPATH .
it happens both if i try to rename the symbol in one of my project file or in the package file itself

## Logs

no extra log lines when rename doesn't work

**Comment by debonte** [comment]
We currently only support rename within the project root. We'll consider adding support for this if this issue gets upvoted.

**Comment by yansnow78** [comment]
at least, when you try to rename outside the project root, the resulting message should be more clear than "no result"

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/issues/1360

now, we will behave same as typescript

![image](https://user-images.githubusercontent.com/1333179/159544208-5dcfd220-48c2-4c1c-9e98-7bc41a2c09e5.png)
