### ISSUE TITLE
pandas.read_csv returns wrong type hint

### ISSUE THREAD

**Issue by hokkwan** [microsoft/pylance-release#2364]
## Environment data
-   Language Server version: >= 2022.1.5
-   OS and version: Windows 10 Enterprise, version 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4

## Expected behaviour
pandas.read_csv returns type hint DataFrame

## Actual behaviour
pandas.read_csv returns type hint TextFileReader

## Code Snippet / Additional information
```python
import pandas
df = pandas.read_csv("data.csv")
```
![image](https://user-images.githubusercontent.com/42298590/153375412-ef1c609b-ad2f-4234-902f-5fb7ed6d24d5.png)

**Comment by Dr-Irv** [comment]
There is work in progress to fix the pandas stubs.  This issue is fixed in https://github.com/microsoft/python-type-stubs/pull/149/files .  pandas stubs issues should be reported at https://github.com/microsoft/python-type-stubs/issues

**Comment by luabud** [comment]
Closing as fixed :)
