### ISSUE TITLE
Rename symbol (F2) to rename one variable name fully mess your whole script

### ISSUE THREAD

**Issue by neuf-de-pixel** [microsoft/pylance-release#2367]
# Behaviour
## Expected vs. Actual

Expected : using F2 does allow to JUST rename variable names 
Actual : using F2 to rename variable names and ADD blank lines to your script (or mess it up completely if you do it twice)

## Steps to reproduce:

1. declare a variable in a script
2. click on the variable name
3. use 'F2' key to rename
4. rename the variable
5. press enter
6. your script is now messy

Python extension v2022.0.1814523869
Python version installed 3.10.0
VS Code 1.64.1

Example : 
Before renaming anything:
![python 1](https://user-images.githubusercontent.com/5772258/153448236-b3c0d47a-51b2-4fcc-9977-05ed61dd871b.PNG)
After renaming the "white" variable to "wwhite":
![python2](https://user-images.githubusercontent.com/5772258/153448414-c1b9955a-f9d2-413d-88c7-6fb8cb0c0443.PNG)
Then after renaming again a variable name (here "blue" to "bllue"):
![python 3](https://user-images.githubusercontent.com/5772258/153448520-bbb3dbe7-acaa-404a-95fa-43cb49eb2f46.PNG)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

**Comment by heejaechang** [comment]
@neuf-de-pixel I can't repro the issue. can you provide a log for us to take a look? here are instructions on how to get logs - https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

also, it would be nice if you can share the file that showing the issue (especially if it is line ending or char code issue)

**Comment by heejaechang** [comment]
@neuf-de-pixel I kind of repro this today, for me, it was due to multiple extensions (Pylance and other python tool) trying to do rename that messed up the file.

once I disable/uninstall those conflicting extensions and leave only Pylance in vscode, it worked as expected. have you checked if you uninstall/disable all other extensions and leave pylance only, this still repro?

**Comment by heejaechang** [comment]
I will close this issue. please re-open if it repro with latest pylance.

**Comment by AsmisAlan** [comment]
Hi, If someone is looking for a solution please check this other issue: https://github.com/microsoft/vscode-python/issues/17123

1. Install Pylance extension. 
2. change your vscode setting to use pylance` "python.languageServer": "Pylance"`
