### ISSUE TITLE
Unexpected pop-up window while importing module 'kivy.graphics.any_module'

### ISSUE THREAD

**Issue by Necrophanto** [microsoft/pylance-release#2368]
# Behaviour
## Expected vs. Actual

I expected to just import the kivy.graphics.whatever_module specific module that i want,  instead of that, after puch the dot after 'kivy.graphics' (it doesn't matter which module i write after that, the behavior launches right after typing the dot), a window is launched and that window kep showing nothing, crashes and ask to wait or force exiting

## Steps to reproduce:

1. Create a project with 2 files: main.py and myappname.kv
2.  In the main.py file create a class that inherits from Widget class (i.e. import the following: 'from kivy.uix.widget import Widget'), like:
class WidgetExample(Widget):
3. Use a canvas component inside that class, and try to draw a line:
class WidgetExample(Widget):
    . . .
    with self.canvas:
        Line(points=[100,100,400,500],width=2)
4. In order to use the Line component you need to import from kivy module, so import the component like this:
'from kivy.graphics.vertex_instructions import Line'
5. When you're typing: 'from kivy.graphics' at the right moment you type the dot following 'graphics' a window will pop-up, just like if you were running the app, but instead it is unresponsive and crashes after a while, asking you to force exiting or waiting
6. It happens everytime you write: 'from kivy.graphics...'

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnv
-   Value of the `python.languageServer` setting: Jedi

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Jedi"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

**Comment by erictraut** [comment]
That's a reasonable hypothesis given the description. However, Pylance doesn't execute any Python library code, so I can't explain how the `kivy.graphics` package would get executed in response to the completions request.

I tried to repro from the description above (thanks for the repro steps!), but I didn't see the described behaviors. Instead, I saw the expected completion popup.

![Screen Shot 2022-02-10 at 1 42 17 PM](https://user-images.githubusercontent.com/7040122/153502098-211f8365-6309-4706-8b1c-1f78ad5ce5cb.png)

Am I correct in understanding that this happens for you regardless of which language server is configured? In other words, you see this crash if Pylance _or_ Jedi are configured, but the crash goes away if _no_ language server is configured?

**Comment by Necrophanto** [comment]
> That's a reasonable hypothesis given the description. However, Pylance doesn't execute any Python library code, so I can't explain how the `kivy.graphics` package would get executed in response to the completions request.
> 
> I tried to repro from the description above (thanks for the repro steps!), but I didn't see the described behaviors. Instead, I saw the expected completion popup.
> 
> ![Screen Shot 2022-02-10 at 1 42 17 PM](https://user-images.githubusercontent.com/7040122/153502098-211f8365-6309-4706-8b1c-1f78ad5ce5cb.png)
> 
> Am I correct in understanding that this happens for you regardless of which language server is configured? In other words, you see this crash if Pylance _or_ Jedi are configured, but the crash goes away if _no_ language server is configured?

I'm not quite sure, since the only server that it is installed for python language comes from the Python extension, but i realized that the behavior goes away when the Pylance extension is disabled

Could it be that the auto-completion triggers something with the "kivy.graphics." input?

**Comment by bschnurr** [comment]
can't repro as well.

when the bug report was created `Jedi` was on.
`Value of the python.languageServer setting: Jedi`
