### ISSUE TITLE
Allow configuration of inactivity delay for diagnostics

### ISSUE THREAD

**Issue by ilyasotkov** [microsoft/pylance-release#237]
I'd like to have the option to disable linting while typing.

For example, when I type

```py
if 
```

in a Python file then in a split second my screen turns red showing "Expected expression" problem from Pylance. You eventually get used to this but I consider this unnecessarily distracting. 

For reference, microsoft/vscode-eslint allows the user to choose whether linting happens onType or onSave: https://github.com/microsoft/vscode-eslint/search?l=TypeScript&q=onType

**Comment by jakebailey** [comment]
I should point out that in most other languages, syntax checking is not linting. In TypeScript, syntax errors appear immediately as they are checked by the TypeScript compiler/server, just as we are doing for Python. Without a language server (Pylance or MPLS), the Python extension has no other choice to get syntax errors than to run a linter. The point of running LSs at all are to remove that restriction and offer live syntax checking consistent with other languages.

**Comment by ilyasotkov** [comment]
@jakebailey I see how language servers are different from linters in a fundamental way, but users might consider this an implementation detail since they just see it as VSCode reporting a *problem*.
 
Perhaps then the feature request is for an option like

```json
{
  "python.analysis.delaySyntaxCheckingUntilSave": true
}
```

So that if you open a file (regardless of whether it already has syntax problems) and make a change to the file, it will clear all problems for that file until you save it.

**Comment by jakebailey** [comment]
Another option (which we supported previously in the old LS) is to allow configuration of the delay between inactivity and the diagnostics being refreshed. We have it set low (after the feedback was that people wanted things to show up _faster_), but if given this option could let you delay diagnostics for a few seconds as well. This was mentioned on another issue, though I'm having trouble finding it at this time. A save would bypass the inactivity checks and immediately render the diagnostics.

**Comment by ilyasotkov** [comment]
> Another option (which we supported previously in the old LS) is to allow configuration of the delay between inactivity and the diagnostics being refreshed.

That would be perfect, this way users could tweak it to their preference and if they don't want any errors showing while typing, they could just set it to something like 9999 seconds.

**Comment by jakebailey** [comment]
Retitled to match, as I think this is the better option (versus the boolean). Will need a decision and planning, of course.

**Comment by ewellinger** [comment]
+1 on this request. All things considered I've been loving pylance, but I find the speed at which things I'm actively typing to be marked as wrong pretty distracting.
Y'all are killing it 🥳

**Comment by savannahostrowski** [comment]
This has been open for nearly a year and hasn't received enough upvotes for us to prioritize this work. If we see this becoming more of a theme, I'm happy to revisit this ask.

**Comment by Alexandar1983** [comment]
An upvote from me.
    It's extremely distracting to see the immediate syntax checking, when you've programmed for 10+ years with syntax check on save. Not to mention the very common lag of the checking, that I receive. Scenarios like:
1. Begin typing some code
2. Syntax check does it's real-time magic with some delay (~1-2s)
3. Finish the code without errors
4. See it's still with red squigglies all over
5. 1-2s period in which you have to wonder "is it you, or is it Pylance lagging again"
, are my usual practice. I've been postponing the Pylance migration for almost 2 years, one of the reasons being exactly for the lack of the "syntax checking on save" feature. The awesomeness of the other features finally won my upvote, but the implementation of at least some delay before the syntax checking, will bring much relief for colleagues like me.
    The education courses are also a good mention - it's very hard for first-time programmers to develop some muscle memory and understand Python errors, when each of their keystroke leads to a red squigglie, misleading them into thinking, what they've already written is wrong. Why do we have to completely turn off the language server and miss all of its great features, when it can only be a single feature?

**Comment by mjohnson324-ingenovis** [comment]
An upvote from me as well.

The intellisense and auto-completion are really useful, but I prefer linting with other programs like flake8.

**Comment by whatbee** [comment]
+1. pylance is distracting to the point of unusability in its current state.
imo this is an accessibility issue, and should be treated as such.
