### ISSUE TITLE
Can't get the function information for matplotlib.figure.Figure.add_subplot

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/pylance-release#2372]
I find the function help for matplotlib is not well. It can't find some function.
Like this:
![image](https://user-images.githubusercontent.com/82581024/153591894-9eaa9d3e-1711-45e2-bc3e-dbdb4d6de9d7.png)

![image](https://user-images.githubusercontent.com/82581024/153591919-5e1dac30-ee64-4a0f-81cc-abf7f38e6a7e.png)

**Comment by judej** [comment]
Thanks for the report. Will investigate this.

**Comment by heejaechang** [comment]
it is due to missing info on matplotlib stub

**Comment by judej** [comment]
We have made some fixes to the Matplotlib stubs. This should be working now. Please reopen if you're still seeing issues.
