### ISSUE TITLE
Semantic Tokens Full Delta Method

### ISSUE THREAD

**Issue by tiagovla** [microsoft/pylance-release#2376]
I noticed pylance's implementation of `textDocument/semanticTokens/full/delta` method is the same of the `textDocument/semanticTokens/full` sending all tokens for the whole document. Would it be possible to implement it like in https://microsoft.github.io/language-server-protocol/ specs so it would be faster?

**Comment by erictraut** [comment]
I'd be surprised if this change would make a measurable different in performance. Most of the work involved with calculating semantic tokens has nothing to do with the communication costs of sending the list of tokens.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
