### ISSUE TITLE
Recursive type with List incorrectly thinks there is a type mismatch

### ISSUE THREAD

**Issue by wch** [microsoft/pylance-release#2377]
<h3> Environment data </h3>

-   Language Server version: 2022.2.0
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

In the example below, VS Code and Pylance flag a problem when there isn't one:

```py
from typing import Iterable, List, Union

RecursiveType = Union[
    int,
    List["RecursiveType"],
]

def foo(x: RecursiveType) -> None:
    pass

z = [1, 2]
foo(z)   # <- z is underlined, but should not be
```

It says:

```
Argument of type "list[int]" cannot be assigned to parameter "x" of type "RecursiveType" in function "foo"
  Type "list[int]" cannot be assigned to type "RecursiveType"
    "list[int]" is incompatible with "int"
    TypeVar "_T@list" is invariant
      Type "int" cannot be assigned to type "RecursiveType"
        "int" is incompatible with "List[RecursiveType]"Pylance[reportGeneralTypeIssues]
```

If I explicitly specify the type for `z`, however, Pylance thinks it's OK:

```py
z: RecursiveType = [1, 2]
foo(z)   # OK
```

If I use `Iterable` instead of `List`, Pylance also thinks it's OK:

```py
RecursiveType2 = Union[
    int,
    Iterable["RecursiveType2"],
]

def bar(x: RecursiveType2) -> None:
    pass

z = [1, 2]
bar(z)  # OK
```

**Comment by erictraut** [comment]
Pyright is correct to report an error in this case. The type parameter for `List` is invariant, so `List[int]` is not compatible with `List[RecursiveType]`.

You can fix this in a couple of ways:

Switch to a `Sequence`, where the type parameter is covariant.

```python
RecursiveType = Union[int, Sequence["RecursiveType"]]
```

Provide a type annotation for `z` to specify that `[1, 2]` should be inferred as `RecursiveType` rather than `List[int]`.

```python
z: RecursiveType = [1, 2]
```

**Comment by wch** [comment]
Ah, after reading up on covariant types, it does make sense to me now.

`Sequence` isn't exactly right for my use case, since lists, tuples, and ranges (and a few others) count as `Sequence`s, but I only want my functions to accept lists or tuples. But I suppose `Sequence` is close enough for practical purposes.
