### ISSUE TITLE
Autocompletion for __init_subclass__ (PEP 487)

### ISSUE THREAD

**Issue by timrid** [microsoft/pylance-release#2378]
I have seen in microsoft/pyright#1020 that PEP487 is supported. This also works for me, so that the types are recognized correctly and also if parameters are missing this is recognized. But what I still miss is that missing parameters are not suggested by the autocompletion. Is it possible to add this function?

With the following example, I would expect that the autocompletion suggests `bar=`:
```python
class Foo:
    def __init_subclass__(cls, *, bar: str) -> None:
        super().__init_subclass__()
        # Do something with bar

class Bar(Foo, b<---Hit Ctrl+Space here
```

**Comment by erictraut** [comment]
@judej, you may want to move this to a discussion topic to see if there is interest from other pylance users. I don't think it needs any investigation.

**Comment by judej** [comment]
Moving this issue to discussion as an enhancement request for comments and upvotes.
