### ISSUE TITLE
Infer Popen.stdout to be non-None when PIPE is given

### ISSUE THREAD

**Issue by heavywatal** [microsoft/pylance-release#2385]
The following is an example code from <https://docs.python.org/3/library/subprocess.html>

```py
# pyright: strict
from subprocess import Popen, PIPE

p1 = Popen(["dmesg"], stdout=PIPE)
p2 = Popen(["grep", "hda"], stdin=p1.stdout, stdout=PIPE)
p1.stdout.close()  # Allow p1 to receive a SIGPIPE if p2 exits.
output = p2.communicate()[0]
```

A hint, `"close" is not a known member of "None" Pylance (reportOptionalMemberAccess)`, is shown at `p1.stdout.close()`, which can be silenced by adding `if p1.stdout:` or `assert p1.stdout` before the line. But it would be nice if Pylance could infer `Popen.stdout` as non-`None` when it is generated from `Popen(..., stdout=PIPE, ...)` so that assertion/check can be omitted. The same applies to stderr and stdin.

**Comment by erictraut** [comment]
The type information for `Popen` comes from the typeshed stubs [here](https://github.com/python/typeshed/blob/1317fa7af9ad0b1ad24333c082eda9e431906bdf/stdlib/subprocess.pyi#L710). If you think the type stub is in error, please file a bug in the typeshed issue tracker — or better yet, submit a PR to change it. Pylance picks up updated stubs from this repo every week or two, so any changes or bug fixes in typeshed will be reflected in Pylance.

**Comment by heavywatal** [comment]
Understood. I have found a related issue https://github.com/python/typeshed/issues/3831 , which have been sitting there for nearly 2 years.

Thank you for your quick response, @erictraut.

**Comment by erictraut** [comment]
To work around the issue, you can insert the following line in your code:

```python
assert p1.stdout is not None
```

This will tell Pylance that you are assuming the value isn't `None`, and it also serves as a runtime check to validate your assumption.

**Comment by heavywatal** [comment]
Yeah, that's what I'm currently doing, and getting rid of it is the motivation of filing this issue.
