### ISSUE TITLE
Syntax highlighting is slow

### ISSUE THREAD

**Issue by CmpCtrl** [microsoft/pylance-release#2387]
Issue Type: <b>Performance Issue</b>

Starting 2/14 i noticed extrememly slow syntax highlighting while editing python scripts. Typically >10s. I think that 2/14 was the first time i restarted allowing vscode to update with the 2/9 release.

I've tried to do some performance profiling and it seems like most of the time is spent idle. 

Extension version: 2022.0.1814523869
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (19.72GB free)|
|Process Argv|--inspect-extensions=9993 --crash-reporter-id e55d3703-d7b2-409d-9ef3-d55e0fc5446e|
|Screen Reader|no|
|VM|0%|
</details>

[CPU-20220215T165402.716Z.cpuprofile.txt](https://github.com/microsoft/vscode-python/files/8073192/CPU-20220215T165402.716Z.cpuprofile.txt)

**Comment by erictraut** [comment]
There was a regression that affected performance in the v2022.2.1 release. This will be addressed in this week's Pylance release (v2022.2.3). Typically we publish a new version each Wednesday or Thursday, so you will see the fix shortly.

**Comment by debonte** [comment]
This issue has been fixed in version 2022.2.3, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202223-16-February-2022)
