### ISSUE TITLE
The keyword 'match` is not immediately determined

### ISSUE THREAD

**Issue by DaSh-More** [microsoft/pylance-release#2389]
If I use `if` or other keywords, they are detected immediately:
> ![image](https://user-images.githubusercontent.com/52647986/154214800-5d0655b3-49aa-4604-813e-e29ac4df93e2.png)
---
But this does not happen if you use 'match`:
> ![image](https://user-images.githubusercontent.com/52647986/154214931-c71c571d-cea3-4037-abb2-d10006b28c99.png)

However, it is worth putting `:` and everything works fine:
> ![image](https://user-images.githubusercontent.com/52647986/154215029-3dcc9a91-cf30-4f27-bc23-d10678b5cef6.png)

**Comment by erictraut** [comment]
Yes, this is the intended behavior. When `match` was added to the language in Python 3.10, it was added as a "soft keyword". This preserves compatibility with existing Python code that might use the word `match` as a variable name. For example, the following is legal:

```python
match = 123
```

Contrast that with other "hard keywords" like `def` or `class`. The following is considered a syntax error:
```python
def = 123
```

This means that tools need to treat `match` contextually.  Pylance can't determine whether `match` should be treated as an identifier or a keyword until you have supplied it with enough context — namely, a subject expression followed by a `:` character. Once it sees that, it knows that it's intended to be a keyword.

**Comment by DaSh-More** [comment]
Understood, thanks for the explanation!
