### ISSUE TITLE
F12 `go to definition` but locate to a strange place 

### ISSUE THREAD

**Issue by floatshadow** [microsoft/pylance-release#2392]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

As a framework `Megatron-LM` changes it API much.  I download an older and a later version comparing what were changed and make further modification.  I have opened both two folders in two in-dependent vscode window.

I viewed `olderversion-folder/pretrain_gpt.py` at first and happend to drag  (not copy, just put it into editing and previewing space in vscode) the `laterversion-folder/pretrain_gpt.py` manually (exclude other modules in later version) to the older folder workspace. I found that the vscode locate  function definition
`mpu.get_data_parallel_group` in `laterversion-folder/pretrain_gpt.py`  to the older version folder! 

Is this an appropriate feature ? I guess it should either report can't find definition or locate the definition to the new version of megatron.

## Steps to reproduce:

![image](https://user-images.githubusercontent.com/50550436/154294880-dfe8361d-a61e-4867-b93e-e19ba756af59.png)

This window is the workspace for older version one, and I drag the .py file from the preview of another vscode workspace window.

![image](https://user-images.githubusercontent.com/50550436/154295208-613cf757-b273-4ec2-898a-02a57ad21764.png)

F12 jump to definition gives it location to older version folder

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): WindowsStore
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

insidersChannel: "off"

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.0.1814523869
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.52GB free)|
|Process Argv|D:\\Project\\Megatron-LM --crash-reporter-id 79f44645-ea50-42cb-b2c9-ae831f0e47c3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
vsbas813:30436447
vscscmwlcmt:30438805
helixcf:30438807

```

</details>

**Comment by judej** [comment]
Would you please add the Pylance logs please?

**Comment by floatshadow** [comment]
I opened Yuan-1.0/ and DeepSpeedExample/ folder and drag the pretrain_gpt2.py in latter folder into the Yuan-1.0/ editing space as I described above.
`[Info 9:48]` ones for opening Yuan-1.0/ folder, and `[Info 9:49]` seems for dragging operation and make a F12 jump.
The log is quite long... hope it helps
https://github.com/floatshadow/logs/blob/main/Pylance%20log

And I tried another simple case like:
new/
   |-----main.py (from .module import function and use new_function )
   |-----module/
           |----function.py (def new_function)
old/
   |-----main.py (from .module import function, and use old_function)
   |-----module/
           |----function.py (def  old_function)


In this case, if drag the main.py opened in old/ workspace to the editing area of opened new/ workspace, it can analysis correctly and jump to old/module/function.py

**Comment by heejaechang** [comment]
@floatshadow I am not sure whether I understand what you are saying fully, but as far as I can understand, what you are describing shouldn't matter (unless actual file is copied). vscode and us use file path to find out workspace it belongs to not the editors location. so regardless whether you put code editor in one panel or the other shouldn't matter as long as file is not actually copied (path is changed)

I tried to repro what you described, but can't make it happen unless I actually copy file over to the other workspace.

I am going to close this issue as not repro. if you disagree please reopen the issue with self contained example and repro steps to reproduce the issue.

thank you.
