### ISSUE TITLE
Pylance doesnt recognize variables made using globals() function

### ISSUE THREAD

**Issue by Stanley444** [microsoft/pylance-release#2394]
## Environment data
-   Language Server version: v2022.2.1
-   OS and version: Windows 10 Version 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2

## Expected behaviour

When creating variable using globals() function it should get recognized and have changed color instead of geting underlined

## Actual behaviour

Pylance says variable is not defined

## Code Snippet / Additional information
example code to reproduce

a = "Hello"
globals()[f"{a}"] = "Hi"
print(Hello)

```python
XXX
```
![image](https://user-images.githubusercontent.com/92398082/154371183-183428bd-3276-4e4e-abc4-603611ce0ffd.png)

**Comment by erictraut** [comment]
This sort of dynamic behavior won't work with a static analysis tool like Pylance.

If you want to use module-level (global) variables, you can use normal variable assignments like `Hello = "Hi"`. If you need to declare global variables from within an inner scope, you can use the `global` keyword, like this:

```python
def func():
    global Hello
    Hello = "Hi"
```
