### ISSUE TITLE
Default `float` argument with integral value is displayed as an integer

### ISSUE THREAD

**Issue by decorator-factory** [microsoft/pylance-release#2397]
## Problem

If a default argument is a float with an integral value (such as `3.0`), it is displayed as if it was an `int` object

![image](https://user-images.githubusercontent.com/42166884/154456273-4d87b3b8-b1de-40b5-86c7-1b20a0c4f356.png)

I don't think it's a big issue since `int` is "promotable" to `float` anyway, but I found this a bit confusing.

## Environment data

- Pylance version: v2022.2.4-pre.1
- OS: Manjaro Linux
- Python version: 3.10.1

## Expected behaviour

The default value is displayed as `3.0` on hover

## Actual behaviour

The default value is displayed as `3` on hover

## Code Snippet / Additional information

```python
def f(x: float = 3.0) -> None:
    pass


f
```

**Comment by judej** [comment]
Since 3 is a valid way of representing a float, the formatting is not a big issue.
