### ISSUE TITLE
rom discord_build_info_py import * ModuleNotFoundError: No module named 'discord_build_info_py'

### ISSUE THREAD

**Issue by Johnybhiduri** [microsoft/pylance-release#2399]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by bschnurr** [comment]
code sample?

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please respond and let us know if that worked.

**Comment by judej** [comment]
Please reopen this issue if the virtual environment suggestion above does not work. thanks.
