### ISSUE TITLE
Import couldn't be resolved

### ISSUE THREAD

**Issue by HorselessName** [microsoft/pylance-release#2400]
## Environment data
* Python Version: v3
* OS and version: Windows 10

## Expected behaviour
No Warnings.

## Actual behaviour
For some reason Pylance can't resolve imports (PyCharm does'nt have such issue. ) - Tho i have no idea this might be happening...
 
## Code Snippet / Additional information
Packages are called "Cloudscraper" and "Scrapy" - Both installed using PIP.

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please respond and let us know if that worked.

**Comment by Anok611** [comment]
Yeah, @judej, it worked for me... just switch to another virtual environment. I changed from 
Python 3.10.8('.venv':venv).\.venv\Scripts\python.exe to Python 3.10.8 64-bit C:\Program Files\Python310\python.exe  which is noted as Global at the far end of the selection tab
