### ISSUE TITLE
False-positive error 'reportUnboundVariable' when raising from class method

### ISSUE THREAD

**Issue by aka-raccoon** [microsoft/pylance-release#2401]
## Environment data

-   Language Server version: **v2022.2.3**
-   OS and version: **macOS Monterey 12.1**
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.12, 3.9.10

## Expected behaviour

Do not report variable as possibly unbound after try/except statement if exception is raised from method called in except clause.  

## Actual behaviour

Pylance reports problem `"variable" is possibly unbound'.

## Code Snippet / Additional information

Following snippet causes Pylance to report `"this_could_fail" is possibly unbound`.
```python
import random


def who_knows_if_i_fail():
    if random.randrange(1, 10) == 5:
        return "Cool"
    raise Exception()


class Dump:
    def raise_it(self):
        raise Exception()


def run_module():

    dump = Dump()

    try:
        this_could_fail = who_knows_if_i_fail()
    except FileNotFoundError:
        dump.raise_it()

    print(this_could_fail) # "this_could_fail" is possibly unbound


def main():
    run_module()


if __name__ == "__main__":
    main()
```

As workaround, I can use type hint for variable `dump: Dump`.
This works fine and Pylance does not report any issue:

```python
import random


def who_knows_if_i_fail():
    if random.randrange(1, 10) == 5:
        return "Cool"
    raise Exception()


class Dump:
    def raise_it(self):
        raise Exception()


def run_module():

    dump: Dump = Dump() # add type hint

    try:
        this_could_fail = who_knows_if_i_fail()
    except FileNotFoundError:
        dump.raise_it()

    print(this_could_fail) # no error reported


def main():
    run_module()


if __name__ == "__main__":
    main()
```

**Comment by erictraut** [comment]
Yes, this is a limitation of pyright's ability to handle NoReturn calls when the call expression involves symbols with inferred types. If you annotate `dump`, inference is not needed in this case.

This is the same underlying problem as this: https://github.com/microsoft/pyright/issues/3001.

**Comment by judej** [comment]
Closing this issue in Pylance since it is tracked in Pyright
