### ISSUE TITLE
Show description for annotations

### ISSUE THREAD

**Issue by KTibow** [microsoft/pylance-release#2407]
Right now, if you [have an annotation on a variable](https://stackoverflow.com/a/8820636/12243248), eg:
```python3
from typing import Annotated
MY_VARIABLE: Annotated[str, "Description goes here"]
```
You only see the typing, not the description.
![Example of the description not showing](https://user-images.githubusercontent.com/10727862/154817493-18b81b6e-cd2b-4dc7-a989-0195ba6e2cd6.png)
I couldn't find any already existing feature requests in a quick search.

**Comment by erictraut** [comment]
`Annotated` is not meant to be used for adding "descriptions" to a type declaration. It is intended for other domain-specific metadata. For details, refer to [PEP 593](https://www.python.org/dev/peps/pep-0593/).

There's nothing that prevents you from adding a string to an `Annotated` annotation, but this string will not (nor should it) be interpreted by general tools as a "description".

If your intent is to provide a docstring for a variable, you can do that with a variable docstring — a quoted string that appears one line below the variable.

**Comment by KTibow** [comment]
Okay, I'll use that instead. Thanks for letting me know.
