### ISSUE TITLE
Unreported unsupported operand type(s) for |: 'function' and 'types.GenericAlias'

### ISSUE THREAD

**Issue by PatrickBourdon** [microsoft/pylance-release#2408]
## Environment data
- Pylance: v2022.2.3
- VScode 1.64.2
- Platform: Windows-10-10.0.19042-SP0
- python.org: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)])

## Actual behaviour
The following incorrectly typed code isn't detected by the type checker and raises at run the exception:
`TypeError: unsupported operand type(s) for |: 'function' and 'types.GenericAlias'`

```python
from typing import TypedDict, Any
def my_func(**kwargs: TypedDict|dict[str, Any]) -> None:
    return
my_func()
```

**Comment by erictraut** [comment]
Yeah, that's not a legal usage of `TypedDict`. There are many illegal and nonsensical usages of special forms that pylance doesn't detect or report. It does check for the most common cases. We could add support for this if there is sufficient interest from users.

**Comment by PatrickBourdon** [comment]
I agree. There is nothing deep in here, no real issue, and it is easy to correct. 
It's up to you, you can close the issue. 
Thank you.
