### ISSUE TITLE
beautifulsoup suggestions not working

### ISSUE THREAD

**Issue by Manju2012** [microsoft/pylance-release#241]
even though python extension is installed, when object/variable created further suggestions related to that object are not showing up as shown in screenshot

![Screenshot (6)](https://user-images.githubusercontent.com/56887373/88765511-399a4d00-d194-11ea-8647-b1fd3ff1e5f5.png)

in the above example **option.get_attribute** will be the method for the object/variable **option**. This suggestions will show automatically in other editors. but in VS code it is not showing(refer screenshot)

**Comment by savannahostrowski** [comment]
Would you mind hover over `stat_info` and tell us what is shown, if anything?

**Comment by Manju2012** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/56887373/90306712-67e68f00-deed-11ea-9ea9-2877064cccdd.png)

**Comment by jakebailey** [comment]
That's `stat`. What is `stat_info`? Additionally, can you check `findAll` to see if its return type is known?

I'm pretty sure beautifulsoup isn't typed.

**Comment by Manju2012** [comment]
stat_finder is result set of beautifulsoup 
![Screenshot (14)](https://user-images.githubusercontent.com/56887373/90307002-5d79c480-def0-11ea-98ff-d7911459eb39.png)

**Comment by jakebailey** [comment]
Thanks. Given beautifulsoup isn't stubbed, I'm guessing we're not figuring out the type you get when iterating over `ResultSet` via inference only. Since BS4 operates over HTML, I'm guessing it's pretty complicated to get right. I'm going to mark this as needing a stub for now.

**Comment by Manju2012** [comment]
Any updates please?

**Comment by jakebailey** [comment]
No updates; beautifulsoup needs to have a stub as typical inference doesn't seem to be able to deduce the type of what it iterates over (leading it to be "any").

**Comment by jakebailey** [comment]
beautifulsoup stubs were added to typeshed a few months ago; the types are now more complete, but `ResultSet` is still parameterized by `Any` when doing `findAll`, so no completions show.

https://github.com/python/typeshed/tree/master/stubs/beautifulsoup4

**Comment by judej** [comment]
Closing this in Pylance, Beautiful soup will need to add type stubs for this to work correctly.
