### ISSUE TITLE
How to turn off automatic module rename refactoring?

### ISSUE THREAD

**Issue by bland328** [microsoft/pylance-release#2410]
One of my macOS systems is acting as if I chose `Don't ask again` in the `Extension 'Python' wants to make refactoring changes with this file move` dialog. I doubt I did, but anything is possible, I suppose.

At any rate, I need the auto-rename behavior to stop, but can't find any way to turn it off.

I've even peeked in the SQLite DB at `~/Library/Application Support/Code/User/globalStorage/state.vscdb`, but failed to find anything that looked applicable.

Is there anything I can do, short of reinstalling VS Code?

**Comment by judej** [comment]
Are you trying to turn it back on? Or are you trying to turn it off?

**Comment by bland328** [comment]
That depends on your definition of "it," I suppose :)

I'm trying to turn automatic _(that is, proceeds without confirmation)_ module rename refactoring off.

To accomplish that, I'm operating under the assumption I need to bring back (or "turn on") the confirmation dialog with the `Don't ask again` option.

That said, if there's another way _(short of no longer using the extension)_ to get the Python extension to stop auto-refactoring when I rename modules, I'm all ears.

**Comment by bland328** [comment]
Hoping I'm not rudely "bumping" this issue, but does anyone have any insight on how to turn off automatic refactoring triggered by the renaming of a module? Hopefully short of reinstalling VS Code, but I'm nearing the point of trying that.

**Comment by debonte** [comment]
Related -- https://github.com/Microsoft/vscode/issues/24815

**Comment by bland328** [comment]
Thanks very much for that.

In the meanwhile, @judej, is there any way I can dig into the Pylance extension settings and get the pre-refactoring confirmation dialog to reappear? I'm willing to dive into sqlite database files, and don't need my hand held, but a hint at the naming of the setting/property/field I should be searching for would be greatly appreciated.

**Comment by bland328** [comment]
I combed the VS Code source a bit, latched onto what was going on in `mainThreadFileSystemEventService.ts`, and worked out that the `"file.particpants.additionalEdits"` _(yes, spelled "particpants")_ record in `~/Library/Application Support/Code/User/globalStorage/state.vscdb` database needed to be removed.

After closing VS Code and making that change, the `Extension 'Python' wants to make refactoring changes with this file move` dialog returned, and I'm now able to control refactoring decisions again.

(I should note that I also removed `"file.particpants.additionalEdits"` from within the value of the neighboring `__$__targetStorageMarker` record, but I _suspect_ that was temporary data storage and not really necessary.)

In the end, @debonte was exactly right in the sharing of the link above--this issue is on the VS Code side of the fence, rather than the Pylance side.

I'd surely appreciate it if the Pylance team would pressure the VS Code team to make this user experience better!

_(Editorial: On one hand, who can complain about free software as great as VS Code? On the other hand, how can a piece of software as fantastic and polished as VS Code have "one-shot" settings that can't be undone without tracing source code and editing sqlite databases?)_

**Comment by StefanKarlsson987** [comment]
unfathomable that this is still an issue today. I cant rename my files or folders, without vscode freezing up... and i have to wait for the dialog box to pop open and then if I am lucky, I can cancel the action in time. Searching online, I see other frustrating comments, but no attention. This is a serious bug, as it can be destructive.

**Comment by Philipflyg** [comment]
> unfathomable that this is still an issue today. I cant rename my files or folders, without vscode freezing up... and i have to wait for the dialog box to pop open and then if I am lucky, I can cancel the action in time. Searching online, I see other frustrating comments, but no attention. This is a serious bug, as it can be destructive.

unfathomable that this is still an issue today.

**Comment by umarbutler** [comment]
@debonte Why was this closed? Looks like myself, @Philipflyg, @StefanKarlsson987 are all having this same problem.

**Comment by giuliano-97** [comment]
@debonte do you happen to know if this has been fixed in recent releases? I also observe the same behavior and on a large codebase it's extremely annoying, is there now a way to turn automatic refactoring on file rename back off?

**Comment by giuliano-97** [comment]
after digging through the settings, I noticed this option:

![Image](https://github.com/user-attachments/assets/9e9fa5a1-be67-4af8-90dc-eae3f34e8736)

by default this is set to 60000 ms or 60 s, so setting it to 0 solved the problem for now  
not sure if this will create more problems down the line, but if other people come here looking for a solution, this might be a workaround

**Comment by debonte** [comment]
> [@debonte](https://github.com/debonte) do you happen to know if this has been fixed in recent releases? I also observe the same behavior and on a large codebase it's extremely annoying, is there now a way to turn automatic refactoring on file rename back off?

It looks like the vscode issue hasn't gotten any traction. If you're willing to dive into the SQLite database and muck with the setting as  @bland328 described [above](https://github.com/microsoft/pylance-release/issues/2410#issuecomment-1062406383), that's the only other workaround I'm aware of. I realize that that's awful though. There is some discussion in the vscode issue about how to do this on different platforms.

**Comment by RDjarbeng** [comment]
Came here to find out how to turn it off, haven't found a solution yet

**Comment by RDjarbeng** [comment]
<img width="495" height="192" alt="Image" src="https://github.com/user-attachments/assets/02e3d319-4155-4081-bdfe-282b296ddae2" />

Unchecking this worked for me
