### ISSUE TITLE
No error message to prompt  even though the package is not installed.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#2411]
## Environment data
Build of Visual Studio Code - Insiders: 1.65.0-insider (user setup)  
Build of python-insider: v2022.1.1869134244-dev
Build of Pylance-insider: v2022.2.3
Build of Jupyter-insider: v2022.1.1301854968
Build of Jupyter Keymap-insider:v1.0.0
Build of Jupyter Notebook Renderers-insider:v1.0.6

## Reproduced steps:
1. Create a folder "newapp"
2. Create a python file "stackoverflow.py"
3. Type scripts "import requests"

## Expected behaviour
There should be an error message like this 
![image](https://user-images.githubusercontent.com/59192491/155080771-ef6b1c84-8be1-44eb-8ff0-8baa3cbcf460.png)

## Actual behaviour
No error message
![image](https://user-images.githubusercontent.com/59192491/155080635-7b81f2ef-3f4f-4570-82d9-19d3c4920373.png)

When launch the python file, it prompt no "requests" module
![image](https://user-images.githubusercontent.com/59192491/155080588-89325bd2-f7dd-4968-ac1f-f6b19ef566f8.png)

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported. Here's what I see when importing `requests` when it's not available in my selected Python environment.

<img width="742" alt="Screen Shot 2022-02-22 at 12 17 49 AM" src="https://user-images.githubusercontent.com/7040122/155081805-a460a991-85e4-40b9-ad5b-26941d943be4.png">

Here are a few things for you to check:
1. Do you have the correct Python environment selected?
2. Have you disabled the `reportMissingModuleSource` diagnostic check in your user settings?

**Comment by linette-zyy** [comment]
@erictraut 
I create a new virtual environment for this workspace and selected it.
![image](https://user-images.githubusercontent.com/59192491/155084500-c6f94db8-4ccc-450d-8ebc-9ae61a65a9da.png)
And I do not to disable the reportMissingModuleSource diagnostic
Another package also not installed, but it can prompt.
![image](https://user-images.githubusercontent.com/59192491/155084791-66b9aa99-dd1d-48d1-8faa-c8c559c07963.png)

**Comment by erictraut** [comment]
The diagnostic you're seeing for numpy is from a different diagnostic rule `reportMissingModuleSource`. This rule looks for type information for the module, whether it comes from bundled type stubs or installed stub packages. The `reportMissingModuleSource` rule looks for missing sources. These are separate because it's possible to write code and validate its correctness without having the library installed. In the case of `requests`, there is a type stub bundled with pylance, so I would not expect to see a `reportMissingImports` diagnostic for it. But you should see a `reportMissingModuleSource` diagnostic if the `requests` library is not installed in your selected Python environment.

**Comment by linette-zyy** [comment]
I import another module , I see the `reportMissingModuleSource` diagnostic
![image](https://user-images.githubusercontent.com/59192491/155255018-cde0d2e1-f9b3-45db-a89c-71b3a8df7cf1.png)
But the requests is still not prompt.
I also try on another the same environment. this issue is not reproduce.
![image](https://user-images.githubusercontent.com/59192491/155256047-dbb00e82-c3b1-4a5b-8119-400920ff23ad.png)

**Comment by erictraut** [comment]
Do you happen to have a local file called `requests.py` in your workspace? Perhaps the import is being resolved to that file instead.

If you right-click on the `requests` identifier in the statement `import requests` and select "Go To Definition", where does it take you? This will tell you which source Pylance is finding when it resolves the import.

**Comment by linette-zyy** [comment]
I prepare a new environment, but this issue is not reproduce. If I meet this issue again, I will update.
