### ISSUE TITLE
Pylance Extension High CPU

### ISSUE THREAD

**Issue by capcarr** [microsoft/pylance-release#2414]
Issue Type: <b>Bug</b>

Python extension with Pylance causes high CPU load on file save or while typing.

Extension version: 2022.0.1814523869
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.35GB free)|
|Process Argv|--crash-reporter-id 64378ed8-46c0-4ad8-8616-508dc7098918|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by judej** [comment]
Thanks for the report. Could you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by capcarr** [comment]
@judej Here goes the requested information.

The Pylance log was captured with a conda environment, based on Python 3.7, but I also see this behavior with other environments.

In the log, there are some "analyzing" and "checking" tasks that take over 1600 ms to complete.
That is when the CPU load spikes, corresponding to an edit to the file.
[pylance_log.txt](https://github.com/microsoft/pylance-release/files/8131890/pylance_log.txt)
[environment.txt](https://github.com/microsoft/pylance-release/files/8131896/environment.txt)

PS: GitHub does not allow upload of .yml files, so I changed the extension to .txt for the environment file.

**Comment by bschnurr** [comment]
@capcarr is that a public repo?

**Comment by capcarr** [comment]
Yes, it is:
https://github.com/PIA-Group/BioSPPy

**Comment by bschnurr** [comment]
thanks. my guess is could be do to using conda which uses older versions of the numpy etc.

i'd try to pip install a venv.

I'll try the conda environment yml you posted though.

**Comment by bschnurr** [comment]
ah i miss read the time you were seeing. I'll take a closer look but 1600ms is expected when using un py typed libraries

**Comment by capcarr** [comment]
@bschnurr 

I did have extra paths added in the settings.
But removing them made no difference.

However, changing the interpreter to plain Python did reduce CPU usage.
So, something to do with conda or how I have it set up?

**Comment by bschnurr** [comment]
could be newer versions of numpy etc have more type annotions, so pylance will do less inference work.

**Comment by judej** [comment]
@capcarr, there have been a couple of fixes for issues that were causing high CPU usage in the past couple of weeks. Is this still reproducible?

**Comment by capcarr** [comment]
@judej What version should I look for, to make sure I have it?

**Comment by judej** [comment]
The latest will have all the changes 2022.3.2

**Comment by bschnurr** [comment]
Do you have a source file to share? or a public github repo?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
