### ISSUE TITLE
Still provide autocomplete for unreachable code

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pylance-release#2416]
I'd like to still get autocompletion for code that is marked unreachable as there can be false positives for this diagnostic.

```py
import pytest
from typing import NoReturn

def cleanup() -> NoReturn:
    ...

def test_foo() -> None:
    with pytest.raises(SystemExit) as exc:
        cleanup()

    # autocomplete here

```

I know this particular bug is fixed (https://github.com/microsoft/pyright/issues/3080) but there could be other false positives in the future and it would be nice to still get completion suggestions, thanks!

**Comment by erictraut** [comment]
That's not really possible. Completion suggestions are based on type analysis, and type analysis is intrinsically linked with reachability analysis. If a piece of code is determined to be unreachable, then any variables used within that code effectively have the type "never", so no completion suggestions will appear.

**Comment by RobertCraigie** [comment]
Yeah that makes sense, pylance / pyright doesn't seem to respect a `# type: ignore` comment in this case though, would supporting that be possible?

```py
with pytest.raises(SystemExit) as exc:
    cleanup()  # type: ignore
```

**Comment by erictraut** [comment]
A `# type: ignore` comment suppresses any diagnostic (error, warning, or information) for that line. It is already honored here.

**Comment by RobertCraigie** [comment]
Sorry I should've clarified what I meant, Pylance still marks the code below it as unreachable and infers types to be `Never`
![image](https://user-images.githubusercontent.com/23125036/155443566-eabebe28-7886-4743-acbf-a3e82d63f9d6.png)

Would it be possible to not mark the code below as unreachable if a `# type: ignore` comment is present on the offending expression that causes the unreachable diagnostic?

**Comment by erictraut** [comment]
No, the mechanism for suppressing diagnostics using a `# type: ignore` is completely divorced from the mechanism that does reachability analysis. The two logically have nothing to do with each other. They're done in completely different stages of analysis and don't know anything about each other.
