### ISSUE TITLE
Pylance does not offer "from numpy.fft import fft" import.

### ISSUE THREAD

**Issue by kbauer** [microsoft/pylance-release#2417]
## Environment data

```
VS Code
  Version: 1.64.2
  Commit: f80445acd5a3dadef24aa209168452a3d97cc326
  Date: 2022-02-09T22:02:29.527Z
  Electron: 13.5.2
  Chromium: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Linux x64 5.3.18-lp152.106-default

Pylance
  Pylance language server 2022.2.4 (pyright 101e717a) starting

Python Interpreter
  Python 3.6.12 from /usr/bin/python3, and
  Python 3.9.7 from ~/anaconda3/bin/python
```

## Expected behaviour

Typing `fft` or `ifft` should offer the imports

    from numpy.fft import fft
    from numpy.fft import ifft

## Actual behaviour

Using the default python interpreter from `/usr/bin/python3`, no import is offered.

After switching the python interpreter to `~/anaconda3/bin/python`, imports from `scipy` are offered, including sub-packages, but still not from `numpy.fft`.

## Logs

Over 2000 lines, hence as attachment.
[logfile.txt](https://github.com/microsoft/pylance-release/files/8133183/logfile.txt)

### Differences between `scipy.fft` and `numpy.fft`

In `.../site-packages/numpy/fft/__init__.py`, symbols are not declared directly, but through a `*` import, and there is no `__all__`.

    from ._pocketfft import *

In `.../site-packages/scipy/fft/__init__.py`, declarations of the public interface are more explicit:

```
from ._basic import (
    fft, ifft, fft2, ifft2, fftn, ifftn,
    rfft, irfft, rfft2, irfft2, rfftn, irfftn,
    hfft, ihfft, hfft2, ihfft2, hfftn, ihfftn)
# [...]
__all__ = [
    'fft', 'ifft', 'fft2','ifft2', 'fftn', 'ifftn',
    # [...]
    'get_workers', 'set_workers']
```

### Video Demo

https://user-images.githubusercontent.com/7498468/155543414-c0f882ca-0e8f-40f0-80e8-0d39b41c2eae.mp4

**Comment by bschnurr** [comment]
to override the default indexing add this to your settings.json

```
    "python.analysis.packageIndexDepths":[
        ["", 1],
        ["sklearn", 2],
        ["matplotlib", 2],
        ["scipy", 2],
        ["django", 2],
        ["numpy",2]
    ],
```
