### ISSUE TITLE
pylance changelog doesn't appear in extension in VS Code

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#2418]
pylance 2022.2.4

In VSCode, the Changelog doesn't appear:
![image](https://user-images.githubusercontent.com/15113894/155582488-dbac819c-c9a6-4855-9d21-1885df94f9da.png)

**Comment by bschnurr** [comment]
looks like a vscode issue. fixed in insiders 
https://github.com/microsoft/vscode/issues/143057

**Comment by debonte** [comment]
Insiders 1.65.0 or later apparently.

**Comment by luabud** [comment]
Closing as fixed upstream 😊
