### ISSUE TITLE
Does not autocomplite list_per_page in admin.ModelAdmin class of Django project

### ISSUE THREAD

**Issue by inkoff** [microsoft/pylance-release#2422]
i type "li" in :
![image](https://user-images.githubusercontent.com/18501137/155887014-ffc1c908-c4a6-41de-b227-88d1ff855100.png)

and autocomplite does not work.

why is this?
what settings is not correctly?

**Comment by erictraut** [comment]
We would need more information from you to diagnose this. A partial screen shot isn't sufficient. For example, I can't tell where the symbols `admin` or `models` come from. Could you provide a minimal, complete code sample that demonstrates the problem you're seeing? If the code imports from any third-party packages, it would be helpful to understand what versions of those packages you have installed.

**Comment by inkoff** [comment]
![image](https://user-images.githubusercontent.com/18501137/155888710-942cfcd2-a199-4bc8-8404-fb2427c23ce8.png)

**Comment by inkoff** [comment]
![image](https://user-images.githubusercontent.com/18501137/155888749-58452ec0-cbff-42ec-974f-cac97ee00536.png)

**Comment by inkoff** [comment]
![image](https://user-images.githubusercontent.com/18501137/155888778-fd8f7522-709e-402c-b200-64d68a13a479.png)

**Comment by inkoff** [comment]
![image](https://user-images.githubusercontent.com/18501137/155888833-ac051e2b-6195-415a-b080-9ef4b1c7cb0d.png)

**Comment by inkoff** [comment]
![image](https://user-images.githubusercontent.com/18501137/155888876-a3032fa7-823d-462c-adf3-be95b75eddf4.png)

**Comment by inkoff** [comment]
venv in workspace folder. if it matter.

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please respond and let us know if that worked.

**Comment by inkoff** [comment]
![image](https://user-images.githubusercontent.com/18501137/156048087-105866f6-ba18-45a9-9a71-2d49bf215ebf.png)
venv is chose correctly.
its work.
autocomplite does not work.

**Comment by inkoff** [comment]
test on python 9.6.3 - awesome truble. and pylint was 2021.11.

**Comment by inkoff** [comment]
my OS is Windows 11

**Comment by inkoff** [comment]
this is log from pylance.
may be it is have some error of config?


[Info  - 22:32:32] (11252) Pylance language server 2022.2.4 (pyright 101e717a) starting
[Info  - 22:32:32] (11252) Server root directory: c:\Users\kob87\.vscode\extensions\ms-python.vscode-pylance-2022.2.4\dist
[Info  - 22:32:32] (11252) No configuration file found.
[Info  - 22:32:32] (11252) No pyproject.toml file found.
[Info  - 22:32:32] (11252) Setting pythonPath for service "storefront": "c:\Users\kob87\storefront\.venv\Scripts\python.exe"
[Error - 22:32:32] (11252) venvPath c:\Users\kob87\storefront\.venv\Script\ is not a valid directory.
[Warn  - 22:32:32] (11252) stubPath c:\Users\kob87\storefront\typings is not a valid directory.
[Info  - 22:32:33] (11252) Assuming Python version 3.10
[Info  - 22:32:33] (11252) Assuming Python platform Windows
[Info  - 22:32:34] (11252) Searching for source files
[Info  - 22:32:35] (11252) Found 45 source files
[Info  - 22:32:35] (11252) Background analysis(1) root directory: c:\Users\kob87\.vscode\extensions\ms-python.vscode-pylance-2022.2.4\dist
[Info  - 22:32:35] (11252) Background analysis(1) started
[Info  - 22:32:36] (11252) Indexer background runner(2) root directory: c:\Users\kob87\.vscode\extensions\ms-python.vscode-pylance-2022.2.4\dist (index)
[Info  - 22:32:36] (11252) Indexing(2) started
[Info  - 22:32:38] (11252) [BG(1)] Long operation: analyzing: c:\Users\kob87\storefront\store\admin.py (2358ms)
[Info  - 22:32:39] (11252) [IDX(2)] Long operation: index execution environment c:\Users\kob87\storefront (2026ms)
[Info  - 22:32:39] (11252) [IDX(2)] Long operation: index libraries c:\Users\kob87\storefront (3768ms)
[Info  - 22:32:39] (11252) Indexer done(2). indexed 449 files
[Info  - 22:32:41] (11252) Searching for source files
[Info  - 22:32:41] (11252) Found 45 source files

**Comment by inkoff** [comment]
just deactivate pylance, and autocoplite is work.

**Comment by RamiSJ12** [comment]
[django-intellisense - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=shamanu4.django-intellisense) need to add or update this.

**Comment by inkoff** [comment]
> [django-intellisense - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=shamanu4.django-intellisense) need to add or update this.

i had try this extension, no result have been

**Comment by RamiSJ12** [comment]
Try to uninstall the extension itself and close your IDE then open again and reinstall, should be installed completely. And let me know

**Comment by inkoff** [comment]
> Try to uninstall the extension itself and close your IDE then open again and reinstall, should be installed completely. And let me know

i try this. i just uninstall pylance and "autocomplite" is worked

**Comment by judej** [comment]
@inkoff, if this is still a problem, could you please reopen this issue and add the following info?
1. A code sample so that we can reproduce the problem
2. Make sure you have your virtual environment set correctly
3. add logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
thanks
