### ISSUE TITLE
Auto import third party modules

### ISSUE THREAD

**Issue by sisoe24** [microsoft/pylance-release#2426]
I've seen a couple of questions about the auto import features but I think mine is not a duplicate.

A couple of version ago, I was able auto import a module from a suggestion that was based on imports I have already made:

```py
from PySide2.QtWidgets import (
   QPushButton
)

label = Q
```
Just by writing `Q`, I was given a list of auto import modules suggestions that were part of the `PySide2.QtWidgets`.
Once confirmed the suggestion, it was automatically imported in the import statement.

Now I am on the same project, same interpreter, same settings, but I am no longer offered those suggestions from the PySide2.QtWidgets but only from built-in modules and modules in current workspace, that just have "similar" names containing some of the letters of what I am writing.

![w9kCY](https://user-images.githubusercontent.com/28490646/156211550-3b88f44b-820b-45e7-8419-f774bcb70b3a.jpg)

What I tried:
* Changed the setting `python.analysis.indexing` to `true` with no success.
* Downloaded older version of VS Code (1.59/60), but was not able to reproduce the imports suggestion.
* Use VS Code Insiders with no success.

So at this point I wonder if this was Pylance doing at all?

**Comment by judej** [comment]
Thanks for the report. Will investigate this.

**Comment by heejaechang** [comment]
It is probably due to tweaks we have been making to reduce number of items in the completion. I think it is a dup of this https://github.com/microsoft/pylance-release/issues/2312

can you try suggested hidden options once fix is released in next version? I will let you know once it is released

**Comment by heejaechang** [comment]
try this with next pylance release

in settings.json

add this

```
"python.analysis.packageIndexDepths": [["PySide2", 3, true]],
```
