### ISSUE TITLE
Code actions of import can be more smart

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/pylance-release#2432]
![Animation2](https://user-images.githubusercontent.com/21306413/156529641-8f453c25-04b1-4ba9-98eb-53f719d08896.gif)

They are apparently in alphabetical order. Is it possible to configure this? To prioritize the typing import over others? 

Such as when I always do that, then the language server can be known of my habit? Or can we reorder it depending on the usage frequency?

**Comment by debonte** [comment]
This isn't limited to auto-import. If you try to use the code fix to add an import for an existing usage of `Dict` you'll have the same issue.

**Comment by judej** [comment]
Since Pylance does not keep track of usage, it won't be able to suggest the appropriate lib based on usage frequency. Might be a feature that Intellicode/CoPilot might be able to implement since those make suggestions based on usage and AI models.
