### ISSUE TITLE
speech_recognition import

### ISSUE THREAD

**Issue by Bhairav777** [microsoft/pylance-release#2437]
<h3> Environment data </h3>

-   Language Server version: 2022.3.0
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by judej** [comment]
Thanks for the report. Unfortunately, we do not have enough info to debug the problem. If this is still an issue, would you please reopen this and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
