### ISSUE TITLE
Function parameter with type `list[A | B]` does not accept variable arguments with type `list[A]` or `list[B]`

### ISSUE THREAD

**Issue by qiemem** [microsoft/pylance-release#2439]
<h3> Environment data </h3>

-   Language Server version: 2022.3.0
-   OS and version: linux x64 (Fedora 35)
-   Python version (and distribution if applicable, e.g. Anaconda): Reproduced with both:
    - System installation of 3.10.2
    - Conda 4.11.0 venv of 3.9.7
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

This code should pass type checking:

Python 3.10
```python
def foo(arg: list[int | str]):
    return arg

foo([1])
foo(["str"])

bar = ["str"]
foo(bar)
```

Python 3.9
```python
from typing import List, Union

def foo(arg: List[Union[int, str]]):
    return arg

foo([1])
foo(["str"])

bar = ["str"]
foo(bar)
```

<h3>Actual behaviour</h3>

The final line, `foo(bar)` gives the type error:

```
Argument of type "list[str]" cannot be assigned to parameter "arg" of type "list[int | str]" in function "foo"
  TypeVar "_T@list" is invariant
    Type "str" cannot be assigned to type "int | str"
      "str" is incompatible with "int" Pylance(reportGeneralTypeIssues)
```

The other lines correctly pass type checking.

<h3> Logs </h3>

https://gist.github.com/qiemem/bf77d4f435b38912e540b03f65e927d1

Happy to edit to paste logs here if preferred.

**Comment by erictraut** [comment]
Yes, this is correct behavior. The type variable for `list` is invariant, so `list[A]` cannot be assigned to `list[A | B]`. For an explanation of variance and why mutable containers use invariant type variables, you might want to read PEP 483 & 484 or refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#generic-types).

**Comment by qiemem** [comment]
Ah of course! :facepalm: I hadn't been considering mutability, so was thinking that passing the literals demonstrated inconsistency. Sorry about that!

**Comment by erictraut** [comment]
The reason that `foo(["str"])` works but `foo(bar)` does not is that the former can employ [bidirectional type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#bidirectional-type-inference-expected-types) to infer that the type of the expression `["str"]` is `list[str | int]` rather than `list[str]`. In the latter case, the type of `bar` has already been inferred as `list[str]` from a previous statement.
