### ISSUE TITLE
Import "httpx" could not be resolved Pylance(reportMissingImports)

### ISSUE THREAD

**Issue by phoenixor** [microsoft/pylance-release#2441]
i use vscode 1.65.0 with httpx，pylance report an error, but the code runs correctly
https://github.com/encode/httpx/issues/2109#issue-1160219702

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please reopen if this does not work.

**Comment by edouard-lopez** [comment]
Sound obvious, but when working with devcontainers, you need to select the python from your `.venv/` directory
![image](https://user-images.githubusercontent.com/1212392/209683229-648dd805-bfad-4b6a-9119-9529e4655551.png)
.
