### ISSUE TITLE
Conflicting Error msg, for working code 

### ISSUE THREAD

**Issue by mrpbennett** [microsoft/pylance-release#2442]
Since the latest update of Pylance I am getting the following error on my code.

<img width="737" alt="Screenshot 2022-03-05 at 14 12 10" src="https://user-images.githubusercontent.com/1844080/156887026-709805b9-b85b-44b7-84fa-d0d8f22a42c8.png">

This is pretty confusing because the application works fine and the code does what it needs to do.

This is the end point

```python
@app.patch(
    "/update-contact/{contact_id}",
    response_model=Contact,
    status_code=status.HTTP_200_OK,
)
def update_contact(contact_id: int, contact: Contact, db: Session = Depends(get_db)):
    """UPDATE: Update a contact"""
    contact_to_update = (
        db.query(models.Contact).filter(models.Contact.id == contact_id).first()
    )

    contact_to_update.first_name = contact.first_name
    contact_to_update.last_name = contact.last_name
    contact_to_update.company = contact.company
    contact_to_update.telephone = contact.telephone
    contact_to_update.email = contact.email
    contact_to_update.address = contact.address
    contact_to_update.notes = contact.notes

    db.commit()

    return contact_to_update
```

It's model is this

```python
class Contact(Base):
    """Contact model"""

    __tablename__ = "contacts"
    id = Column(Integer, primary_key=True, index=True)
    first_name = Column(String(255), nullable=False)
    last_name = Column(String(255), nullable=False)
    company = Column(String(255), nullable=True, default="NULL")
    telephone = Column(String(255), nullable=True, default="NULL")
    email = Column(String(255), nullable=True, default="NULL")
    address = Column(Text, nullable=True, default="NULL")
    notes = Column(Text, nullable=True, default="NULL")
```

It's schema is this

```python
class Contact(BaseModel):
    """Contact model"""

    id: Optional[int] = None
    first_name: str
    last_name: str
    company: Optional[str] = None
    telephone: Optional[str] = None
    email: Optional[str] = None
    address: Optional[str] = None
    notes: Optional[str] = None

    class Config:
        """Pydantic config"""

        orm_mode = True
```

With the errors being highlighted the run still runs without any issues, could someone advise how to get rid of the error warnings?

**Comment by erictraut** [comment]
You have enabled type checking features, so pylance is highlighting static type inconsistencies in your code. The fact that your code runs without an exception is not evidence that it doesn't have a bug. 

If you provide a minimal self-contained code sample that exhibits the problem, I can help you diagnose the cause. If your code relies on any third-party libraries, make sure to include the import statements and list the versions of those libraries that you're using.

**Comment by mrpbennett** [comment]
Hey @erictraut not sure how I could provide a self-contained code sample. The backend of my application is here:

https://github.com/mrpbennett/signal_journey_py/tree/work_3/backend

The API endpoints are in `main.py` the schemas are in `schema.py` and well the models are in `models.py` The app relies on a local postgres db. Because of the db side not sure how to give you a code sample. Sorry

**Comment by erictraut** [comment]
The change you're seeing is due to [a recent PR in typeshed for the sqlalchemy stubs](https://github.com/python/typeshed/commit/44bcf5eed0f882c20d5d09d510f191aef9e918a6). The `Query.first` method was modified to reflect the fact that it can return a `None` return result. Your code is not checking for this case.

For the record, here is a minimal self-contained code sample that exhibits the problem.

```python
from sqlalchemy.orm import Session

def func(db: Session):
    foo = db.query().first()
    foo.enabled = True
```

**Comment by mrpbennett** [comment]
Oh right. How can I tweak it to remove the error? Thanks for the explanation too, much appreciated 🤙🏼

**Comment by erictraut** [comment]
To remove the error, you need to fix the bug in your code so it properly deals with the possibility that `first()` returns None.

**Comment by mrpbennett** [comment]
Ok great thanks. I’ll take a look.

**Comment by mrpbennett** [comment]
I have fixed the None error. But still not sure how to resolve the other one?

```
Cannot assign member "enabled" for type "SignalJourneyAudiences"
  Expression of type "bool" cannot be assigned to member "enabled" of class "SignalJourneyAudiences"
    "bool" is incompatible with "Column[bool]"PylancereportGeneralTypeIssues
```

Any guidance here?
