### ISSUE TITLE
Import "environ" could not be resolved

### ISSUE THREAD

**Issue by Deadlooks** [microsoft/pylance-release#2446]
### It is just a miner issue! 

as shown in the image it cannot resolve but the server run fine!

i am not using any virtual environment

python version, Python 3.9.10

I have installed it by,  pip3 install django-environ

![Screenshot_2022-03-07_02_45_11](https://user-images.githubusercontent.com/91751103/156943079-19af0d30-f6bf-4b04-bdd5-26d49b42519e.png)

**Comment by judej** [comment]
Thanks for the report. Would you please try using a virtual environment?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Please reopen this issue if this does not solve the problem.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

**Comment by vokilasxela** [comment]
Thanks judej! Worked for me!

**Comment by gemarkalmacen** [comment]
I just need to create environments via vscode.

thanks @judej! It works.
