### ISSUE TITLE
No funciona la extensión en los archivos .py

### ISSUE THREAD

**Issue by CarlosVallejo47** [microsoft/pylance-release#2447]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
