### ISSUE TITLE
Pylance freezes after sklearn PCA.fit() call

### ISSUE THREAD

**Issue by martinwoo7** [microsoft/pylance-release#2448]
## Environment data 
-   Language Server version: 2022.3.0 (pyright 1ed262f6)
-   OS and version: Windows 11 (but still occured in 10)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.10 w/ miniconda3 

## Actual behaviour

This is similar to #2296, where suggestions are frozen after the call to sklearn's PCA function, except this time it happens with .fit()
Commenting out the line doesn't fix the problem, only restarting VSCode does.
Even just loading the file with the line uncommented results in this behaviour.

## Logs

[Info  - 11:58:17 p.m.] (11520) Pylance language server 2022.3.0 (pyright 1ed262f6) starting
[Info  - 11:58:17 p.m.] (11520) Server root directory: c:\Users\marti\.vscode\extensions\ms-python.vscode-pylance-2022.3.0\dist
[Info  - 11:58:17 p.m.] (11520) No pyproject.toml file found.
[Info  - 11:58:17 p.m.] (11520) Setting pythonPath for service "<default>": "C:\Users\marti\miniconda3\envs\test\python.exe"
[Warn  - 11:58:17 p.m.] (11520) stubPath typings is not a valid directory.
[Info  - 11:58:17 p.m.] (11520) Assuming Python version 3.9
[Info  - 11:58:17 p.m.] (11520) Assuming Python platform Windows
[Info  - 11:58:17 p.m.] (11520) Searching for source files
[Info  - 11:58:17 p.m.] (11520) No source files found.
[Info  - 11:58:18 p.m.] (11520) Background analysis(1) root directory: c:\Users\marti\.vscode\extensions\ms-python.vscode-pylance-2022.3.0\dist
[Info  - 11:58:18 p.m.] (11520) Background analysis(1) started
[Info  - 11:58:43 p.m.] (11520) [BG(1)] Long operation: checking: c:\Users\marti\OneDrive\Desktop\test2.py (21241ms)
[Info  - 11:58:43 p.m.] (11520) [BG(1)] Long operation: analyzing: c:\Users\marti\OneDrive\Desktop\test2.py (21247ms)

## Code Snippet / Additional information

sklearn version: 1.0.2 from conda-forge

I created a new conda environment with just Python 3.9.10 and sklearn.
Note that this problem doesn't happen when using fit_transform, only fit

```python
from sklearn.decomposition import PCA

kmeans = KMeans(init="k-means++", n_clusters=16, random_state=42, n_init=4)
bench_k_means(kmeans=kmeans, name="k-means++", data=training_data, labels=training_labels)

pca = PCA(n_components=16).fit(training_data) 
kmeans = KMeans(init=pca.components_, n_clusters=16, n_init=1)
bench_k_means(kmeans=kmeans, name="PCA-based", data=training_data, labels=training_labels)
```

**Comment by erictraut** [comment]
Thanks for the bug report. I'm able to repro the problem as reported. I've created a tracking bug in the pyright project since this issue is related to the core type checker functionality.
