### ISSUE TITLE
Support `PDM` python package manager

### ISSUE THREAD

**Issue by li1234yun** [microsoft/pylance-release#2453]
PDM is a modern Python package manager with [PEP 582](https://www.python.org/dev/peps/pep-0582/) support. It installs and manages packages in a similar way to npm that doesn't need to create a virtualenv at all!

Can you consider to support it?

[PDM](https://pdm.fming.dev/)

**Comment by erictraut** [comment]
Correct me if I'm wrong, but I think PEP 582 was proposed during Python 3.8 development but has never been accepted as a standard.

**Comment by li1234yun** [comment]
Hi, @erictraut. you are right!

I will close the issue.

[PEP 582](https://www.python.org/dev/peps/pep-0582/)
