### ISSUE TITLE
A way for library authors to describe a canonical way to import symbols

### ISSUE THREAD

**Issue by Ran4** [microsoft/pylance-release#2456]
**Is your feature request related to a problem? Please describe.**
Concrete example of a problem: I, like many other pyright users, use the Pydantic library.

I might type out a sample module by writing this:

```python
class Book(BaseModel):
    title: str
```

I then move my cursor to `BaseModel` and choose to import it, using Pyright's auto-import feature. However, by default, the auto importer will add `from pydantic.main import BaseModel`, which is wrong - I really want to do `from pydantic import BaseModel`, as that's the intended way (and importing from some submodule may or may not be part of the public api). The same thing of course applies to all sorts of libraries, and also code used within the same package.

**Describe the solution you'd like**
Not sure, but there should be some way for library authors to be able to describe the preferred way to import some symbol (i.e.  through the public api), such that Pyright will respect it (and use it if possible).

Perhaps through `__all__` somehow? Given that `__all__` already has some convention as being used to describe the public api of a module.

For example:
* if theres a symbol `Foo` that exists in both `foo` and `foo.implementation`...
* then prefer to import `Foo` from `foo`, if `hasattr(foo, "__all__") and "Foo" in foo.__all__`

**Comment by bschnurr** [comment]
hmm. pylance seems to be doing the right thing here.
![image](https://user-images.githubusercontent.com/1946977/157307940-b29c656e-08f6-458b-b739-55a3b27a5731.png)

**Comment by Ran4** [comment]
Oh, so it's not Pyright that does the import? I'm using coc-pyright (latest version, 1.1.223), but it seems like it's using pyright for its import functionality.

**Comment by bschnurr** [comment]
you could try turning on 'indexing' in your pyrightconfig.json

{
"indexing": true
}

Looks like we need to update the pyright docs
https://github.com/microsoft/pyright/blob/main/docs/configuration.md

**Comment by Ran4** [comment]
> you could try turning on 'indexing' in your pyrightconfig.json
> 
> { "indexing": true }
> 
> Looks like we need to update the pyright docs https://github.com/microsoft/pyright/blob/main/docs/configuration.md

No idea what it does (and it seems undocumented, as you mention), but no difference (I created a file `pyrightconfig.json` in the root folder, same as where my editor's CWD is and where my example file is, and added `{"indexing": true}` to it)

**Comment by erictraut** [comment]
Yeah, you're right, this might be due to the fact that we don't have all of the libraries indexed.

For the record, pyright doesn't support indexing. That's a more advanced feature that only Pylance supports. And we have no plans at this time to back-port it to pyright.
