### ISSUE TITLE
Python › Auto Complete: Add Brackets

### ISSUE THREAD

**Issue by AbdelrahmanHamdy1996** [microsoft/pylance-release#246]
Issue Type: <b>Feature Request</b>

Auto Complete for brackets not working with pylance 

Extension version: 2020.8.1
VS Code version: Code 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6, 2020-08-13T07:40:55.768Z)
OS version: Linux x64 5.4.0-42-generic

**Comment by erictraut** [comment]
Can you provide more details about what you mean by "add brackets"? Are you referring to automatically adding parentheses when completing a symbol that is callable? If so, I think this is a duplicate of #37.

**Comment by AbdelrahmanHamdy1996** [comment]
Yeah 
python.autoComplete.addBrackets​"​: ​true 
automatic complete by adding brackets to python function and methods not working

**Comment by erictraut** [comment]
OK, thanks. Marking this as duplicate since we're already tracking this in #37.
