### ISSUE TITLE
Import Error Message: "Import 'nose.tools' could not be resolved Pylance(reportingMissingImports) 

### ISSUE THREAD

**Issue by evanxuw** [microsoft/pylance-release#2460]
Hi,
I am using VSCode for a python project. When I try "from nose.tools import assert_equal" to test my codes, the error message (above) populates. 

After I install "pip install nose"  from cmd, I can get the correct output. However, the error message still persists.  Any insights? 

Thank you.

Evan

**Comment by sutr19** [comment]
Hi,
Have you set the interpreter path
i assume this would help
https://www.youtube.com/watch?v=x-BtaZDbQeo

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
