### ISSUE TITLE
typing.ByteString and compatibility with Sequence[int]

### ISSUE THREAD

**Issue by tapetersen** [microsoft/pylance-release#2465]
## Environment data

-   Language Server version: Pylance language server 2022.3.1 (pyright bd47ac0b) starting
-   OS and version: Ubuntu 20.04.4 LTS
-   Python version: 3.8

## Expected behaviour

typing.ByteString should work as a type for variables that should hold some kind of bytes-like object such as `bytes`, `bytearray` or `memoryview` and only require read-only access

If not this type then I would expect some reasonable way of typing such objects while working with them without forcing a specific type.

Normal operations on the variables such as concatenation and slicing should preserve this without requiring casts.

## Actual behaviour
Can't add any of the listed types to a `typing.ByteString`

```python
foo = typing.cast(typing.ByteString, b'foo')
foo + b'bar'

"""
Operator "+" not supported for types "ByteString" and "Literal[b'bar']"
  Operator "+" not supported for types "ByteString" and "Literal[b'bar']"
"""
```

Slicing a `ByteString` returns `typing.Sequence[int]` which is not compatible with `ByteString`

```python
bar = typing.cast(typing.ByteString, b'bar')[:]

"""
Expression of type "Sequence[int]" cannot be assigned to declared type "ByteString"
  "Sequence[int]" is incompatible with "ByteString"
"""
```

This makes it very unergonomic to work with bytebuffers while keeping correct typing as any operation must explicitly cast the type back to `ByteString` to stay type-compatible.

**Comment by tapetersen** [comment]
I do understand there is some problem in that there really isn't any way in python to represent a sequence of ints limited to 0-255
but since this case is very common when working with any binary protocol having a type that's specialized for it feels motivated and is what I would have expected `ByteString` to be.

If nothing else I file this to have the problems documented since I was surprised I couldn't find any existing bugs or discussion of it.

**Comment by tapetersen** [comment]
Ok checking some in the mypy issues where it also has come up it seems like typing.ByteString is not really complete as it should and the general recommendation is to just use bytes for annotations as allowed by https://docs.python.org/3/library/typing.html#typing.ByteString

I see that pylance generally accepts this between `bytes` and `bytearray` but `memoryview` objects are still marked as incompatible.

I personaly find it clearer and would prefer an Interface type such as `ByteString` to document that variants are allowed but if memoryviews would be accepted as a `bytes` subclass that would at least allow a consistent typing.

**Comment by erictraut** [comment]
The type definition for `ByteString` comes from the `typing.pyi` stub in the typeshed project. Pyright (the type checker that underlies Pylance) bundles the typeshed stubs for stdlib type information. If you right click on `ByteStream` and choose "Show Declaration", Pylance will take you to the relevant declaration in the stub file.

All of the major Python type checkers, including pyright and mypy, use the same typeshed type stubs. If you think that there is an error in these stubs, please file a bug or a PR in the [typeshed project](https://github.com/python/typeshed). Pyright (and Pylance) regularly pick up changes to this repo.
