### ISSUE TITLE
pylance causes high CPU load

### ISSUE THREAD

**Issue by Urkallinger** [microsoft/pylance-release#2466]
## Environment data
-   Language Server version: Pylance language server 2022.3.1 (pyright bd47ac0b)
-   OS and version: Microsoft Windows 21H2 (OS Build 19044.1526)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7 with poetry

For some time now I have the problem that when I open a Python file the CPU load of VS Code increases extremely. A look in the task manager shows that it is the pylance process that causes the CPU load.

![pylance_cpu_load](https://user-images.githubusercontent.com/20026149/157638353-67f2af73-ebdb-4935-b953-fd7295eec89f.png)

The CPU load only increases when a Python file is opened. Notably, the CPU load does not decrease when the Python file is closed again. I have to restart VS code to get the CPU load to drop again.

## Expected behaviour

CPU load increases briefly when Python file is opened in VS code and decreases again when the file is analyzed.

## Actual behaviour

CPU load remains permanently high

**Comment by kalsky** [comment]
Happens to me as well, I'll try to add the details as described in the troubleshooting guide
