### ISSUE TITLE
pytest missing from list of imports - reportMissingImports

### ISSUE THREAD

**Issue by JohnSprunger** [microsoft/pylance-release#2470]
![image](https://user-images.githubusercontent.com/6321764/158021478-cca92cff-ab2b-4e6a-abc1-7e61ab1df08d.png)

**Comment by Azureblade3808** [comment]
From my experience, it could be caused by the workspace being not trusted. You may first check if there is a "Restricted Mode" sign at the bottom-left of VSC window.

**Comment by judej** [comment]
Thanks for the report. Is your workspace trusted? Could you please try changing trust and seeing if this fixes the issue?

**Comment by judej** [comment]
Another issue to check is the virtual environment.  Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
