### ISSUE TITLE
[bug] Hovering symbol doesnt show any description when the associated docstring __doc__  is set manually.

### ISSUE THREAD

**Issue by ItsCubeTime** [microsoft/pylance-release#2471]
To demonstrate: https://i.imgur.com/Exar2LE.png
![image](https://user-images.githubusercontent.com/20190653/158064346-1519dfb7-fffd-44db-bed2-c1dd8740f40f.png)

VS using a string literal:

https://i.imgur.com/g5UImFK.png
![image](https://user-images.githubusercontent.com/20190653/158064344-c2051d6a-2766-4d16-a433-f5d3ca357acd.png)

**Comment by erictraut** [comment]
Dynamically setting the docstring won't work for a static analysis tool like pylance. Is there a reason you don't simply use a normal docstring within the function?

**Comment by ItsCubeTime** [comment]
> Dynamically setting the docstring won't work for a static analysis tool like pylance. Is there a reason you don't simply use a normal docstring within the function?

Hi Eric, I needed to have access to that very string in a dependency of the class I was documenting (which was just another class right above (you dont see that class in the screenshots)).

As its just an intellisense issue I wont bother to reorganize my code just to declare the string as a string literal right under the class In docummenting, but it would be a nice if Pylance could pick up on it <3

The variable that Im setting in the docstring to I would expect to have to be static however, which it is

**Comment by erictraut** [comment]
The Python interpreter will automatically set the value of the `__doc__` variable if you use a normal docstring. You can then access the variable from other classes if necessary. So I don't understand why you are setting this value manually within the class. Why is it not sufficient to allow the Python interpreter set it for you?

```python
class FastTrimUnwrap:
    """
    This is my class description
    """

print(FastTrimUnwrap.__doc__)

# Output: "This is my class description"
```

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
