### ISSUE TITLE
Consider reducing delay for indexing of libraries

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/pylance-release#2473]
This is especially important for my library (https://github.com/RobertCraigie/prisma-client-py) as it is auto-generated it will be modified a lot.

Currently whenever a change is made to the schema and the package is re-generated, any new type errors are not reported and new autocomplete suggestions are not shown either for 10 minutes or until the language server is restarted. This makes it difficult to rapidly prototype schema changes.

I tried going through the Pylance settings and didn't find anything that worked for me. I could've missed the setting but even if there is a setting I can change to get the desired behaviour ideally this would be possible by default as it can be confusing for users as they don't know that they will have to either wait 10 minutes or restart the language server for their schema changes to propagate.

I understand that delaying the indexing of libraries is for performance reasons. Is there any way indexing could be optimised for my use case?

**Comment by judej** [comment]
Thanks for the report @RobertCraigie, One way you could trigger is to the Language  Server restart from the command palette with `Python: Restart Language Server`. That would be faster than the restarting the process. Please reopen the issue if that approach is not satisfactory. Thanks

**Comment by RobertCraigie** [comment]
Hi @judej, sorry I wasn't clear enough in the original comment. I was making use of the command palette `Python: Restart Language Server` which works well but it can still be confusing if a user forgets that they have to run it or doesn't know that they have to run it in the first place.

I would like to provide the best possible experience for users of my library and having the editor automatically recheck their code and update suggestions as soon as they make any schema changes without them having to think about it would be an amazing QOL feature. Ideally this would be possible with default settings but I understand that this brings performance concerns.

**Comment by erictraut** [comment]
@RobertCraigie, are you saying that _users_ of your library will experience frequent regeneration of code? Or is this just an issue for you as you develop the library? I had previously assumed that it was the latter, but based on your most recent comment, I'm wondering if I misunderstood. If _users_ of your library will see frequent code regeneration, can you explain more about the intended workflow for your library?

**Comment by RobertCraigie** [comment]
@erictraut Yes users will experience frequent code regeneration in certain workflows.

> can you explain more about the intended workflow for your library?

Of course. The library deviates from other ORMs as the data models are defined outside of a python file, instead they are defined in a [Prisma Schema](https://www.prisma.io/docs/concepts/components/prisma-schema) file, the way this works isn't important but it does mean that the library code has to be regenerated *every time* a change is made to the schema.

So when users are prototyping features in their app they'll likely be making lots of changes to their schema which results in a lot of code regeneration. However, any workflow that does not require changes to the schema will not result in code regeneration.

It also should be noted that code generation is a hard requirement for the library as it is fundamental to its ability to provide type safe queries and is an underlying requirement by Prisma as well.

Sample Prisma Schema in case that helps clear things up:

```prisma
datasource db {
  url      = env("DATABASE_URL")
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-py"
}

model User {
  id         Int      @id @default(autoincrement())
  created_at DateTime @default(now())
  email      String   @unique
  name       String?
  role       Role     @default(USER)
}

enum Role {
  USER
  ADMIN
}
```

**Comment by erictraut** [comment]
Thanks for the details. Am I correct in assuming that the generated code files are located within the user's project file, as opposed to in the installed library location (in site-packages)? If these generated files are project-local code files, then regenerating them should be no different than any other edit, and "library indexing" concerns shouldn't apply.

**Comment by RobertCraigie** [comment]
Yeah that is a good point. I was under the impression that the vast majority (if not all) modern python projects use some form of environment isolation whether that's `venv`, `poetry`, `virtualenv` etc. Although I do not know what the actual usage stats are for these environment managers.

Generating to a local directory also comes with the disadvantage of having to deal with Python's potentially confusing import system for relative modules. For example it would then be difficult to run scripts in other directories:

```
prisma/
├─ <generated library code>
foo/
├─ script.py
schema.prisma
```
```py
# script.py
from prisma import Prisma
```

Running the script with `python foo/script.py` will result in an `ImportError` as the local package cannot be resolved properly. As far as I'm aware the fix for this is `sys.path` manipulation which the user would then need to include in every script they want to run.

For what it's worth it is very clear to the user where the code is being generated to:

```
$ prisma generate
Prisma schema loaded from schema.prisma

✔ Generated Prisma Client Python to ./.venv/lib/python3.9/site-packages/prisma in 265ms
```

**Comment by erictraut** [comment]
It may be clear, but if I found that a library was dynamically generating new code files into my Python environment (virtual or otherwise), I'd be pretty surprised and a bit miffed.

**Comment by RobertCraigie** [comment]
I see, I think most people come into the library with the knowledge that it does this but I acknowledge that it might be surprising.

I do think I want to keep the current behaviour due to the difficulties with importing local modules and I haven't received complaints from users that the default behaviour is not what they want.

If you do want to use local modules then it's a one line change:

```prisma
generator client {
  provider = "prisma-client-py"
  output = "prisma"
}
```

**Comment by erictraut** [comment]
For users of your library who want to use Pylance, I would recommend the approach of generating local modules. Perhaps you could document that as an alternate workflow?

**Comment by RobertCraigie** [comment]
> For users of your library who want to use Pylance, I would recommend the approach of generating local modules. Perhaps you could document that as an alternate workflow?

Yes that is a good suggestion, I'll document that as an alternative workflow.

However I still want to be able to provide a good experience for users who want to generate to `site-packages`, would it be possible to add an option to disable or reduce the 10 minute delay?

**Comment by erictraut** [comment]
We generally don't add new configuration knobs unless/until we have signal that there is a broad need. This use case still strikes me as atypical and rather esoteric. We could reconsider in the future if we get sufficient signal from our user base.

**Comment by DeveloperHarris** [comment]
> Yeah that is a good point. I was under the impression that the vast majority (if not all) modern python projects use some form of environment isolation whether that's `venv`, `poetry`, `virtualenv` etc. Although I do not know what the actual usage stats are for these environment managers.
> 
> Generating to a local directory also comes with the disadvantage of having to deal with Python's potentially confusing import system for relative modules. For example it would then be difficult to run scripts in other directories:
> 
> ```
> prisma/
> ├─ <generated library code>
> foo/
> ├─ script.py
> schema.prisma
> ```
> 
> ```python
> # script.py
> from prisma import Prisma
> ```
> 
> Running the script with `python foo/script.py` will result in an `ImportError` as the local package cannot be resolved properly. As far as I'm aware the fix for this is `sys.path` manipulation which the user would then need to include in every script they want to run.
> 
> For what it's worth it is very clear to the user where the code is being generated to:
> 
> ```
> $ prisma generate
> Prisma schema loaded from schema.prisma
> 
> ✔ Generated Prisma Client Python to ./.venv/lib/python3.9/site-packages/prisma in 265ms
> ```

This is also the behavior from the Javascript/Typescript implementation of Prisma, so it'd make sense for the implementations to be functionally identical. I came across this refresh issue myself and had no idea why I could import everything properly in runtime but vscode presented errors. I had no idea to restart the language server. I think having this setting be user-adjustable, wouldn't hurt.

**Comment by ntindle** [comment]
+1 on the above behavior being expected from a module side. If it did it otherwise, it would be pretty unexpected.
