### ISSUE TITLE
import pyttsx3

### ISSUE THREAD

**Issue by Liima1** [microsoft/pylance-release#2474]
<h3> Environment data </h3>

-   Language Server version: 2022.3.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
