### ISSUE TITLE
Issue with lagging on python project startup

### ISSUE THREAD

**Issue by Newcool1230** [microsoft/pylance-release#2481]
## Environment data

-   Language Server version: 2022.3.1 (pyright bd47ac0b)
-   OS and version: Windows_NT x64 10.0.17763
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9

## Expected behaviour

Vscode run smoothly on startup

## Actual behaviour

Freeze whole computer on startup and have 70% CPU and 100% GPU spike

## Logs

Its over 2500 lines so here is the .txt
[vscode_lag.txt](https://github.com/microsoft/pylance-release/files/8260934/vscode_lag.txt)

## Code Snippet / Additional information

Issue occurs on all python startup in any project folder the current project that was opened in the trace log was an empty test folder with one .py file and 3 lines of import code.

```python
import random
import traceback
import praw
```

**Comment by heejaechang** [comment]
can you put in settings.json, "python.analysis.indexing=false" ? according to log, that is only thing that takes more than 2 seconds. 

indexing is something that improve auto-import/add-import/search symbol perf and experiences.

**Comment by Newcool1230** [comment]
24 hour update after setting indexing to false...

Thank you for the help, everything is not freezing anymore, so all good in that department. Still having some weird GPU spikes tho, is there anything I can do about that?

![image](https://user-images.githubusercontent.com/10657253/158887246-061b77cf-0fb1-4792-860f-26010edf6631.png)

**Comment by heejaechang** [comment]
@Newcool1230 what machine are you using? according to the log, there is nothing pylance does. if you machine can't even handle vscode opening a file, not sure what we can do.

**Comment by Newcool1230** [comment]
> @Newcool1230 what machine are you using? according to the log, there is nothing pylance does. if your machine can't even handle vscode opening a file, not sure what we can do.

@heejaechang I'm running i7-8700k, GTX 1070 Ti, 32GB RAM and 1T SSD

Runs pycharm just fine, only having issues with vscode. Further testing shows that it happens when all extensions were disabled so I have made an issue on vscode repo and will be closing this one since it seems to be an issue with vscode and not the pylance extension.

Thank you for your help!
