### ISSUE TITLE
Add quickfixes for reportMissingImports

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/pylance-release#2483]
I think it's highly relevant here that I consider myself a novice with Python. Every time I get this warning, I'd like to fix it. Since I don't use Python every day, I have to remember what I googled before when I fixed this last time, and hope I find it and that it works for this new situation.

Isn't there some type of quickfix that could be provided? For example, opening up the settings directly to the editable property/properties pylance uses to find its source files? Opening up a file browser to choose a root directory, or a requirements.txt file to use as its source of truth? etc.

I suspect the solution to this problem is nuanced. If there's no general solution, I'd like to request that the warnings somehow direct me to documentation that explains my options and then how to set those options in pylance.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
