### ISSUE TITLE
Type check does not update when `.discard` is used with singleton.

### ISSUE THREAD

**Issue by jrom99** [microsoft/pylance-release#2488]
<h3> Environment data </h3>

-   Language Server version: 2022.3.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] on linux
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

After typing the following:

```python
my_set: set[str | None] = {"hello", "another string", None}
my_set.discard(None)
```
I expect `my_set` type to be `set[str]` since `None` is a singleton.

<h3> Actual behaviour </h3>

`my_set` type is still `set[str | None]`

<h3> Logs </h3>

Python Language Server Log:

[pylance_logs.txt](https://github.com/microsoft/pylance-release/files/8289287/pylance_logs.txt) (Github reported that issue body was too long if I kept them as pure text)

<h3> Code Snippet / Additional information </h3>

```python
my_set: set[str | None] = {"hello", "another string", None}
my_set.discard(None)
```

**Comment by erictraut** [comment]
That's not how static types work. The type of `my_set` remains `set[str | None]`. This allows you to add `None` to it again.

For more details about how static typing — including generic types like `set` — please refer to PEP 483 and 484.

**Comment by erictraut** [comment]
You might also find this documentation useful: https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md.

To use the lingo of static type checking... The type parameter for `set` is invariant, so `set[str]` is not a subtype of `set[str | None]`. That means that `set[str | None]` cannot be narrowed to `set[str]`.

**Comment by jrom99** [comment]
I understand now, thanks for the information!
