### ISSUE TITLE
Indexing bytes with slice returns int

### ISSUE THREAD

**Issue by twiggler** [microsoft/pylance-release#2489]
<h3> Environment data </h3>

-   Language Server version: 2022.3.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

```
x = bytes(4)
z = x[1:3]
```

type of `x` is `bytes` (class)

<h3> Actual behaviour </h3>

type of `x` is `int`

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported.

```python
x = bytes(4)
reveal_type(x) # bytes
z = x[1:3]
reveal_type(z) # bytes
```

If you index a bytes with an integer rather than a slice, you will get an integer:
```python
a = x[1]
reveal_type(a) # int
```

**Comment by twiggler** [comment]
I discovered the problem.

I had installed grpc-stub files using `pip install grpc-stubs`

For some reason, pylance did nothing with them, so I added `C:\Python310\Lib\site-packages` to Python: stub path in my config:
![image](https://user-images.githubusercontent.com/12800443/159046470-d3122d7b-d604-475f-8fdb-6dff572c20ca.png)
 
This caused the stubs to work, but it broke typings of bytes, because if I remove the path, the typings of bytes work again.

**Comment by erictraut** [comment]
Yeah, setting the stub path to point to your site-packages will likely cause lots of problems. Stub packages that are installed in the site-packages directory should be picked up automatically by type checkers. However, some versions of the google stub packages (including the grpc-stubs) use overlapping namespaces and do not properly mark the stubs as "partial", so the presence of multiple google stub packages can cause problems. Make sure you have the latest versions of any google stub packages installed in your environment, and that will hopefully clear up the problem you've hit with `grpc-stubs`.

**Comment by twiggler** [comment]
Ok, thanks you for your prompt responses @erictraut
