### ISSUE TITLE
Bug in bundled django stubs

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#249]
The django stubs contain several bugs in the `db/models/fields/__init.pyi` file. Subclasses of the generic `Field` class should generally specify concrete types for type arguments rather than being generic themselves.

For example:
```
class IntegerField(Field[_ST, _GT]):
```

should be defined as:

```
class IntegerField(Field[Union[float, int, str, Combinable], int]):
```

With the current stubs, the following code generates incorrect type-checking errors.
```
from django.db import models

class Order(models.Model):
    status = models.IntegerField()

    def get_status(self) -> int:
        return self.status

    def set_status(self, new_status: int) -> None:
        self.status = new_status
```

(Note: there was a bug in pyright that also contributed to the incorrect error reporting. This bug has been fixed as of 16-Aug, but the bugs in the type stub files also need to be fixed for this code to pass type checks.)

**Comment by last-partizan** [comment]
Does pylance uses https://github.com/typeddjango/django-stubs, or it maintains separate version of it?

I was not using pylance, and my original issue was with pyright + typeddjango/django-stubs, so, maybe this should be reported there?

**Comment by last-partizan** [comment]
And, looking at detailed definition in typeddjango/django-stubs:

```
class IntegerField(Field[_ST, _GT]):
    _pyi_private_set_type: Union[float, int, str, Combinable]
    _pyi_private_get_type: int
    _pyi_lookup_exact_type: Union[str, int]
```

If _ST stands for _pyi_private_set_type and _GT for _pyi_private_get_type, this is already the same as you want?

**Comment by erictraut** [comment]
I'm guessing that "_pyi_private_set_type", etc. are symbols used by the custom mypy plugin for django. They will have no effect on type checking when used by type checkers like Pylance/Pyright that limit themselves to the Python type standards.

**Comment by last-partizan** [comment]
@erictraut no, it actually already works. I just installed pyright from git with your fix, and it works as expected.

**Comment by erictraut** [comment]
The error will go away now in "basic" type checking mode, but if you use "strict" mode, a different error will appear because of the bug in the type stub.

![Screen Shot 2020-08-16 at 4 20 46 PM](https://user-images.githubusercontent.com/7040122/90346279-72cc1d00-dfdc-11ea-933c-964663b1845f.png)

**Comment by judej** [comment]
Need to verify the behaviour in the next version

**Comment by psam44** [comment]
I confirm the diagnosis of @erictraut. In "strict" mode, I have:
```python
class Message(models.Model):
    subject = models.CharField()
````
```
Type of "subject" is partially unknown
  Type of "subject" is "CharField[Unknown, Unknown]"Pylance (reportUnknownVariableType)
```

typeddjango/django-stubs is written with mypy in mind and with a mypy_django_plugin. The code in this plugin has a hook to "reparametrize_instance()" with types for set and get ops, read from the `_pyi_private_...` custom attributes.

My current workaround is:
```python
class Message(models.Model):
    subject: models.CharField[Union[str, int, Combinable], str] = ...
```
or, to factorize writings with an alias in case of many fields of the same kind:
```python
_CharField = models.CharField[Union[str, int, Combinable], str]

class Message(models.Model):
    subject: _CharField = ...
```

**Comment by simensol** [comment]
My workaround is to replace `_ST` and `_GT` with the type hints from `_pyi_private_set_type` and `_pyi_private_get_type` using a regex:

Find:

```regex
([A-Za-z]*)\[_ST, _GT\][): .\n]*_pyi_private_set_type: ([^\n]*)[\n ]*_pyi_private_get_type: ([^\n]*)
```

Replace:

```regex
$1[$2, $3]):
    _pyi_private_set_type: $2
    _pyi_private_get_type: $3
```

Then

```python
class CharField(Field[_ST, _GT]):
    _pyi_private_set_type: Union[str, int, Combinable]
    _pyi_private_get_type: str
    ...
```

becomes

```python
class CharField(Field[Union[str, int, Combinable], str]):
    _pyi_private_set_type: Union[str, int, Combinable]
    _pyi_private_get_type: str
    ...
```

I did this with all stub files from the `django-stubs` repro.

**Comment by simensol** [comment]
Even better, there is already [a package](https://github.com/sbdchd/django-types) with Django stubs optimized for Pyright. These stubs should be bundled with Pylance instead of the unmodified `django-stubs` (`django-types` is a fork of `django-stubs`).

**Comment by judej** [comment]
review shipping [stubs](https://github.com/sbdchd/django-types)

**Comment by rafrafek** [comment]
> or, to factorize writings with an alias in case of many fields of the same kind:
> 
> ```python
> _CharField = models.CharField[Union[str, int, Combinable], str]
> 
> class Message(models.Model):
>     subject: _CharField = ...
> ```

It's giving me an error:

```
models.py", line 6, in <module>
    _CharField = models.CharField[Union[str, int, Combinable], str]
TypeError: 'type' object is not subscriptable
```

I'm using Python 3.9.12 and Django 4.0.4.

Should I import Combinable like this?:
```python
from django.db.models.expressions import Combinable
```

**Comment by lexicalunit** [comment]
Where do these bundled stubs come from anyway? It doesn't seem like they're from `django-stubs` or `django-types`. I'd like to be able to run `pyright` on the command line and get the same results as I do in my editor.

**Comment by simensol** [comment]
I'm quite sure the stub files are from `django-stubs`, as there are identical comments in the code, e.g., [this comment](https://github.com/typeddjango/django-stubs/blob/e221f0e0533c98417ed726cba764b5f6282442f8/django-stubs/db/__init__.pyi#L23) which also appears in the stubs shipped with Pylance:

<img width="465" alt="__init___pyi_—_backend__Dev_Container__backend_" src="https://user-images.githubusercontent.com/4491653/169251073-d06b9e2a-4774-4a8e-bf5a-52c0bc76054e.png">

**Comment by rchiodo** [comment]
I believe this is fixed. We followed @simensol's advice AFAICT and shipped the stubs from https://github.com/sbdchd/django-types

**Comment by simensol** [comment]
I can confirm that linting Django projects now works as expected with the stubs shipped with Pylance.

**Comment by andresespinosapc** [comment]
I have the same problem in Pylance 2024.8.1 and can't find the command that it runs to debug it in the command line.

**Comment by rchiodo** [comment]
@andresespinosapc I'd recommend upgrading Pylance to the latest. Whatever stubs you have maybe different by now.
