### ISSUE TITLE
Pylance does not show import suggestions for classes and functions inside file starting with underscore

### ISSUE THREAD

**Issue by khaitruong922** [microsoft/pylance-release#2490]
## Environment data

-   Language Server version: 2022.3.2
-   OS and version: Windows 10
-   Python version: 3.9

## Expected behaviour

Classes and functions inside a file starting with underscore should show up in the suggestion list.

## Actual behaviour

Classes and functions inside a file starting with underscore does not show up in the suggestion list.

## Code Snippet / Additional information

my_module/_MyClass.py and my_module/MyClass.py
```python
class _MyClass:
    pass
def my_function():
    pass
```

main.py
![image](https://user-images.githubusercontent.com/56820749/158941626-6b518c7f-018e-43ed-b456-8e4a710044b0.png)
![image](https://user-images.githubusercontent.com/56820749/158941651-d3d26cb3-940b-4465-a56c-2922eeb519f7.png)

Only the function and class inside MyClass.py show up.

**Comment by erictraut** [comment]
This is intended behavior.

A file that begins with an underscore is a private (internal) module, and its symbols are not meant to be visible outside of the library unless they are re-exported explicitly from a public module.

**Comment by khaitruong922** [comment]
@erictraut Is there any settings that I can modify to change this behavior?

**Comment by judej** [comment]
Sorry, there is unfortunately, no setting to change the behavior. If there are more upvotes for this, we can reconsider.

thanks

**Comment by iyz91** [comment]
I'll second this, suggestions for importing privates is useful when needing to modify and monkeypatch stuff. My 2 cents is probably a comment flag for the line allowing private import suggestions.

**Comment by lendle** [comment]
Same, I'm trying to subclass a class which uses underscore prefixes for internal methods which I need to call.

**Comment by ColinStroud** [comment]
I'm with OP, I feel like importing of private classes,funcs,etc. should be left up to the end developer.
