### ISSUE TITLE
Is there some setting to set the **key word** filter ?

### ISSUE THREAD

**Issue by Booooooger** [microsoft/pylance-release#2493]
hey guys , i'm newer to pylance , i need your helps

here, i have one module package named `server.async` 

and in my code , when i import the module , like below:

```
import server.async 
```

pylance told me like below:
![image](https://user-images.githubusercontent.com/40785594/159209430-05014130-a048-4254-a9cf-e5fe546c96c4.png)

i want to know ,is there some setting to set the **key word** filter ? Or other solution for this problem ?

thanx

**Comment by erictraut** [comment]
These are basic syntax errors and may indicate that you have non-printing (non-whitespace) characters in your file. Are you able to run this code file in the Python interpreter without errors?

**Comment by Booooooger** [comment]
> These are basic syntax errors and may indicate that you have non-printing (non-whitespace) characters in your file. Are you able to run this code file in the Python interpreter without errors?

yes. this code is able to run . and i guess that is one keyword misstake

![image](https://user-images.githubusercontent.com/40785594/159210570-55385fe2-4505-454c-9cb6-612f9898f149.png)

although the keyword **aysnc** is error , but it can work when i run the code 

and just can't work when i'm wirting code, i can not go to souce code

**Comment by erictraut** [comment]
Yes, `async` is a keyword, so you cannot use it in the context of a module name. This produces a `SyntaxError: invalid syntax` when running the code in the standard Python interpreter. This isn't valid Python code.

You said that you were able to run this without runtime errors. Are you sure? If so, are you using a nonstandard Python interpreter? Or perhaps a really old version prior to the introduction of the `async` keyword (< Python 3.5)?

**Comment by Booooooger** [comment]
Ok , thanks for your reply and suggests . I aslo think this isn‘t valid Python code 

I wanna share to you ,  is real to run without any runtime errors ,🤣 and the Python version i using is 3.6.5 。

anyway ,thanks again 😁, i'll close the question later
