### ISSUE TITLE
Pylance displays irrelevant errors

### ISSUE THREAD

**Issue by sfaroy** [microsoft/pylance-release#2498]
Hi,

I have worked lately with mypy as type checking as integrated in the vs-code and it works great until now. When I opened the vs-code now, I get many errors that are not relevant - although when executing mypy manually - I recieve no errors. 

I don't know the source of the displayed error , what changed that they appear now and how to disable them.

I work using remote ssh.

For example, the following log of the pylance seems OK:
```
Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonInterpreterInfoUnpinned' is active
> conda info --json
> /miniconda/envs/tf/bin/python ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
Python interpreter path: /miniconda/envs/tf/bin/python
> /miniconda/bin/python ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/interpreterInfo.py
> ". /miniconda/bin/activate && conda activate tf && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/roee/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/printEnvVariables.py"
Starting Pylance language server.
> /miniconda/envs/tf/bin/python -m mypy --follow-imports=silent --ignore-missing-imports --show-column-numbers --no-pretty ~/GIT/tmqi_estimator/train_tmqi.py
cwd: ~/GIT/tmqi_estimator
##########Linting Output - mypy##########
Success: no issues found in 1 source file
```

But I get weird non-relevant errors in the pylance, and I can't track their source:
![image](https://user-images.githubusercontent.com/3100892/159452575-685de15e-1390-4abd-8137-4a23711d9766.png)

Any ideas on how to debug this? I went over the configuration and checked that only mypy is active as a linter (can be seen from the output log)

Workspace setting:
```
{
    "files.autoSave": "afterDelay",
    "python.linting.enabled": true,
    "python.linting.mypyEnabled": true,
    "python.analysis.typeCheckingMode": "basic",
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.pytestEnabled": true,
    "python.analysis.logLevel": "Trace"
}
```

**Comment by judej** [comment]
Is the question - how to disable/uninstall Pylance? If so, you can do that from the Extensions tab - right click on Pylance and uninstall or disable. 

Since the setting ` "python.analysis.typeCheckingMode": "basic",`, you will get those error. You could set it to ` "python.analysis.typeCheckingMode": "off",` to disable typchecking.

Please reopen this issue if this does not resolve the issue.
