### ISSUE TITLE
Support typing for NamedTuple unpacked variables

### ISSUE THREAD

**Issue by oidualc** [microsoft/pylance-release#251]
Currently when a variable is unpacked from a typed `NamedTuple`, it's type is `Any`.
It would be nice if the type could be detected as it happens using the dot notation.
Example:

```python
from typing import NamedTuple

class Employee(NamedTuple):
    name: str
    id: int

employee = Employee("Guido", 1)

employee.name  # (variable) name: str
employee.id  # (variable) id: int

(name, id) = employee  # (variable) name: Any, (variable) id: Any
```

**Comment by erictraut** [comment]
Thanks for the suggestion. It turns out that I implemented this support last week, and it will be included in the next version of Pylance. See https://github.com/microsoft/pyright/issues/907 for more details.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202082-20-august-2020

**Comment by Kein** [comment]
Is it possible to implement type check for short syntax?
```python
Entry = NamedTuple("Entry", size=int, offset=int, numSubs=int, subs=int, hasValue=bool)
```
This will report `Entry.size` as `type: Any`

**Comment by erictraut** [comment]
Pylance supports this [documented form](https://docs.python.org/3/library/typing.html):

```python
Entry = NamedTuple(
    "Entry",
    {
        ("size", int),
        ("offset", int),
        ("numSubs", int),
        ("subs", int),
        ("hasValue", bool),
    },
)
```

Or the variant documented in [PEP 526](https://www.python.org/dev/peps/pep-0526/):

```python
class Entry(NamedTuple):
    size: int
    offset: int
    numSubs: int
    subs: int
    hasValue: bool
```

**Comment by Kein** [comment]
> Pylance supports this [documented form](https://docs.python.org/3/library/typing.html):
> 
> ```python
> Entry = NamedTuple(
>     "Entry",
>     {
>         ("size", int),
>         ("offset", int),
>         ("numSubs", int),
>         ("subs", int),
>         ("hasValue", bool),
>     },
> )
> ```

This does not work, it still reports `size` as any.

The class approach works but it is too verbose and OOP for 3 lines of code.

**Comment by erictraut** [comment]
Apologies. It's supposed to be a list, not a dictionary.

```python
Entry = NamedTuple(
    "Entry",
    [
        ("size", int),
        ("offset", int),
        ("numSubs", int),
        ("subs", int),
        ("hasValue", bool),
    ],
)
```

And you need to instantiate it:

```python
a = Entry(3, 4, 5, 6, True)
a.size
```

**Comment by Kein** [comment]
> And you need to instantiate it:

Ah, I see, so that's why it failed, I was populating it a bit differently. A warning for that when type checking enabled would be nice but I believe it is out of scope for Pylance. Thanks.

**Comment by Kein** [comment]
Is there any particular reason type annotations for anonymous tuples are not supported?
I would rather prefer:
```python
(var, var2, var) = struct.unpack('<3I', data) # type: (int, int int)
```
then
```python
var1 = 0 # type: int
var2 = 0 # type: int
var3 = 0 # type: int
(var, var2, var3) = struct.unpack('<3I', data)
```

**Comment by erictraut** [comment]
Old-style type annotations in comments were never documented in any PEP or the Python specification. They grew up organically and were eventually replaced by language syntax in Python 3.3 and 3.6. Pylance does support a few simple forms of these old-time comment forms, but we don't plan to add any more at this point. You should use the official language syntax for type annotations.

**Comment by gvanrossum** [comment]
> Old-style type annotations in comments were never documented in any PEP or the Python specification. They grew up organically and were eventually replaced by language syntax in Python 3.3 and 3.6. Pylance does support a few simple forms of these old-time comment forms, but we don't plan to add any more at this point. You should use the official language syntax for type annotations.

Well, there's this: https://www.python.org/dev/peps/pep-0484/#id41

But I agree that we should encourage annotations for everything except `# type: ignore`.

**Comment by Kein** [comment]
> Old-style type annotations in comments were never documented in any PEP or the Python specification. They grew up organically and were eventually replaced by language syntax in Python 3.3 and 3.6. Pylance does support a few simple forms of these old-time comment forms, but we don't plan to add any more at this point. You should use the official language syntax for type annotations.

So what about Python 2.x and very early 3.x that only basically support `#type: T->T` hints? I understand you dont want  to actively support these, but is there any reason to completely abandon backwards compatibility with 2.x?

**Comment by erictraut** [comment]
Pylance doesn't support Python 2.x. If you need to maintain Python 2.x compatibility in your source base, the JEDI language server is available for your use.

**Comment by gvanrossum** [comment]
Another approach would be to specify mypy as the linter.
