### ISSUE TITLE
Type: ignore for a block of code?

### ISSUE THREAD

**Issue by tddschn** [microsoft/pylance-release#2512]
I have a block of code that I don't want to type check, how do I surpress type warnings for it?

I don't want to append `# type: ignore` to every line in that block, is it possible to add a feature that disables type checking between a `# type: ignore start` and a `type: ignore end`?

**Comment by erictraut** [comment]
There's currently no way to disable type checking for just a single block of code in a module. You can disable all type-related checks for a module by adding a `pyrightconfig.json` file and specifying the entire module in the `ignore` section.

Can you explain why you don't want to type check a block of code?

**Comment by tddschn** [comment]
@erictraut Thank you for your reply!
The reasone why I want to do this is because I'm viewing codes written by other people, and I often got dozens of `... is not a member of "None"` warning in a file. I don't want these warnings to show up and don't want to add type narrowing code / assertions in those files manually. I want to just disable type checking for a large block of code in those files.

**Comment by erictraut** [comment]
If you're viewing code projects written by others, you can disable type checking for the entire project by simply setting `typeCheckingMode` to "off" for that project. As I said, you can also specify which files within a project that you would like type checking diagnostics to be suppressed by using the "ignore" section of a pyrightconfig.json file.

We currently have no plans to add a way to disable type checking messages for blocks within a file.

**Comment by SuperMB** [comment]
Just wanted to add another comment on a desire for a similar feature. It would be great if you could put a #type:ignore at the start of a block, like a for block or while block, and have it ignore any code within that block. We deal with some custom python code / format, but only for certain parts of a file. Would love to ignore these warnings for only certain code blocks!

**Comment by higorc-mck** [comment]
+1 on SuperMB. Would be super-useful for code such as nested dataclasses with `__post_init__`s:

```python
@dataclass
class LocalConfig:
    input: InputConfig
    output: OutputConfig

    # type: ignore
    def __post_init__(self):
        self.input = InputConfig(**self.input)  # Argument expression after ** must be a mapping with a "str" key type
        self.output = OutputConfig(**self.output)  # Argument expression after ** must be a mapping with a "str" key type
```

**Comment by khanfarhan10** [comment]
Is there any update for this?

```python
class ABCConfig(BaseModel, extra="forbid"):
    numberKeys : Optional[Dict[Literal[VALID_VALUES['numberKeys']], NumericKeyConfig]] = None

# NOTE The VSCode Linter (PyLance) shows following bug for the above, but this runs perfectly in code , this is a known dynamic linting issue.
# Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value
```

**Comment by nickezekias** [comment]
Hey guys here is another use case with sqlalchemy ORM objects
I have a mapper object that maps let's say ProductORM to Product domain model. 
I get pylint errors because `ProductORM.name` is of type `Column[str]` while `Product.name` is `str`. Now sqlalchemy ORM implicitly knows how to return the correct value in str, but I get pylance errors for this. No I don't want to # type: ignore all those lines and no I dont want to do type casting (str(orm.name)) for something that just works implicitly, and works fine for that matter.

**Comment by nickezekias** [comment]
Hey guys here is another use case with sqlalchemy ORM objects
I have a mapper object that maps let's say ProductORM to Product domain model. 
I get pylint errors because `ProductORM.name` is of type `Column[str]` while `Product.name` is `str`. Now sqlalchemy ORM implicitly knows how to return the correct value in str, but I get pylance errors for this. No I don't want to # type: ignore all those lines and no I dont want to do type casting (str(orm.name)) for something that just works implicitly, and works fine for that matter.

**Comment by ssteinerx** [comment]
While this is possibly (also) a parsing error, you can't ignore this as shown without bringing the entire `d.baked_time = ...` statement onto a single line:

```python
    # Cannot assign member "baked_time" for type "Donut"
    # "datetime" is incompatible with "time | Combinable | None"
    d.baked_time = datetime.datetime(
        year=2007, month=4, day=20, hour=16, minute=19, second=59)   # type: ignore
```
Ironically, the `#type: ignore` is ignored.  A block ignore would cure the symptom.

**Comment by tigerhawkvok** [comment]
+1 on this. 

@erictraut asked at https://github.com/microsoft/pylance-release/issues/2512#issuecomment-1079934867

> Can you explain why you don't want to type check a block of code?

A valid answer would be that "Pylance/Pyright is wrong". Consider this:

```python
class Constants(Enum):
    USE_SRID:int = 3857 # https://epsg.io/3857
    MAX_PEER_DISTANCE_SRID_UNITS:float = 100 * 1000 # 100 km, EPSG:3857 is in meters
    MAX_PEER_COUNT:int = 100
    LIMIT_TO_COUNTRY:Optional[str] = None
    ZOOM_OUT_RESOLUTION:int = 8
    TARGET_PEERING_H3_RESOLUTION:int = 6
    TIMESTAMP_ID:str = str(dt.datetime.now().timestamp()).replace(".", "")
    H3_MAX_RESOLUTION:int = 15
    H3_MIN_RESOLUTION:int = 0
```

Every single line is squiggled, with a variant of `Expression of type "Literal[6]" cannot be assigned to declared type "Literal[Constants.TARGET_PEERING_H3_RESOLUTION]"` (in this _particular_ case, it usually correctly goes away when the file is clean, but usually surfaces again as soon as the file is dirty). It's actively unhelpful to have that keep flashing up as bad.

**Comment by erictraut** [comment]
@tigerhawkvok, it sounds like you're hitting a bug. Please consider filing a bug report with repro steps.

**Comment by sorrentinoandrea** [comment]
> If you're viewing code projects written by others, you can disable type checking for the entire project by simply setting `typeCheckingMode` to "off" for that project. As I said, you can also specify which files within a project that you would like type checking diagnostics to be suppressed by using the "ignore" section of a pyrightconfig.json file.
> 
> We currently have no plans to add a way to disable type checking messages for blocks within a file.

We use the enaml python language extension (https://github.com/nucleic/enaml) and it's useful to associate .enaml files with python for syntax highlighting and code completion. However pylance warning makes it horrific to watch the sections of a file that contain enamdefs. Surely this is a legitimate case for disabling warnings for a block of code?

**Comment by belliriccardo** [comment]
+1 to this! Any news about this development? I've pinged the twin issue at Mypy as well ( [https://github.com/python/mypy/issues/6948](https://github.com/python/mypy/issues/6948) ); this so that a common ground can be reached on how to define the type checking start/end. (so that the two different type checkers don't end up requiring different syntax).
