### ISSUE TITLE
reportMissingImports warning

### ISSUE THREAD

**Issue by ChuliangXiao** [microsoft/pylance-release#2515]
## Environment data

-   Language Server version: Pylance
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda, Python 3.8.3

![image](https://user-images.githubusercontent.com/6011789/160460944-4e8a0d09-3e38-4d90-842b-1769b51bd1d7.png)

## Code Snippet / Additional information

```python
# No warning
from apiclient import discovery
discovery.build


# reportMissingImports warning
from apiclient.discovery import build
```

**Comment by erictraut** [comment]
What is the name and version of the library that provides the import `apiclient`?

**Comment by ChuliangXiao** [comment]
> What is the name and version of the library that provides the import `apiclient`?

`apiclient.__version__` is NOT available.
```python
import apiclient
apiclient.__version__
```
Here is the `apiclient/__init__.py` in `site-packges`.

```python
"""Retain apiclient as an alias for googleapiclient."""

import googleapiclient

from googleapiclient import channel
from googleapiclient import discovery
from googleapiclient import errors
from googleapiclient import http
from googleapiclient import mimeparse
from googleapiclient import model

try:
    from googleapiclient import sample_tools
except ImportError:
    # Silently ignore, because the vast majority of consumers won't use it and
    # it has deep dependence on oauth2client, an optional dependency.
    sample_tools = None
from googleapiclient import schema

_SUBMODULES = {
    "channel": channel,
    "discovery": discovery,
    "errors": errors,
    "http": http,
    "mimeparse": mimeparse,
    "model": model,
    "sample_tools": sample_tools,
    "schema": schema,
}

import sys

for module_name, module in _SUBMODULES.items():
    sys.modules["apiclient.%s" % module_name] = module

```

**Comment by erictraut** [comment]
I understand that `apiclient` is the name of the import module, but what is the name of the library? In other words, what is the command you used to install this library? Is it `pip install apiclient`? Or `pip install googleapiclient`? Or something else?

**Comment by ChuliangXiao** [comment]
> I understand that `apiclient` is the name of the import module, but what is the name of the library? In other words, what is the command you used to install this library? Is it `pip install apiclient`? Or `pip install googleapiclient`? Or something else?

Was following instruction from https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py
```bash
pip install --upgrade google-api-python-client 
pip install --upgrade oauth2client
```
The package name is `google-api-python-client` 
> google-api-core                    2.7.1
google-api-python-client           2.42.0
googleapis-common-protos           1.56.0

**Comment by erictraut** [comment]
This library is doing something that I've never seen before — and didn't realize was even supported by Python. I'm not sure if it is officially supported or just happens to work as a side effect of the complex import mechanism in the Python runtime.

The module `apiclient/__init__.py` is importing another module using the statement `from googleapiclient import discovery`, and you're trying to import symbols from the `discovery.py` module using the statement `from apiclient.discovery import XXX`. The `discovery.py` module doesn't exist in the file system under the `apiclient` directory; that relationship exists only in memory once the `from googleapiclient import discovery` statement is executed at runtime. 

I think we can handle this case statically, but I'll need to think more about how much complexity this would add to pyright / pylance. As I said, this is the first time I've ever seen this situation, so it's far from the norm.

In the meantime, you can use the following variants if you want to avoid the `reportMissingImports` warning.

```python
from apiclient import discovery
discovery.build
```

or
```python
from googleapiclient.discovery import build
```

**Comment by uktamka** [comment]
### Environment data
- Language Server version: Pylance
- IDE Visual Studio Code version: 1.66.1
- OS and version: Windows 11
- Python 3.10.4

I used to install this library "pip install python-decouple"

```python
# reportMissingImports warning
from decouple import config
```

![image](https://user-images.githubusercontent.com/39945349/162606826-049d455c-4c52-43d6-b4ed-bcbd086b9f8a.png)

**Comment by KazemDolatabadi** [comment]
I had a similar problem, finally, I uninstalled and reinstalled Pylance Extension and it resolved.

**Comment by abdudds** [comment]
> ### Environment data
> * Language Server version: Pylance
> * IDE Visual Studio Code version: 1.66.1
> * OS and version: Windows 11
> * Python 3.10.4
> 
> I used to install this library "pip install python-decouple"
> 
> ```python
> # reportMissingImports warning
> from decouple import config
> ```
> 
> ![image](https://user-images.githubusercontent.com/39945349/162606826-049d455c-4c52-43d6-b4ed-bcbd086b9f8a.png)

done everything suggested by chatgpt, reinstalled pylance still issue not solved

**Comment by debonte** [comment]
@abdudds, my guess is that `decouple` is not installed in your environment, or the environment that you have selected in VS Code is not the environment that you planned to use. See https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters.

If this doesn't help, please open a new issue.
