### ISSUE TITLE
Import "X" could not be resolved - Correct interpreter, lib installed, searchPath is there

### ISSUE THREAD

**Issue by MVPat** [microsoft/pylance-release#2516]
## Environment data

-   Language Server version: v2022.3.3
-   OS and version: Win 10 Pro 21H1 19043.1586
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda3 Python 3.9.7

## Expected behaviour

virtual conda environment is used, correct interpreter is selected. "requests" is installed in this environment. 
"pip show requests"  gives "Location: C:\Users\Sebastian.Schleicher\Anaconda3\envs\zoho\lib\site-packages"
Output of python -c 'import sys, pprint; pprint.pprint(sys.path)' is given below.
pylance should be able to resolve the import.

## Actual behaviour

pylance cannot resolve imports. Running the code works fine however. 

**Important info: Adding the following line to settings.json solves the issue:**
"python.analysis.extraPaths": [ "C:\\Users\\Sebastian.Schleicher\\Anaconda3\\envs\\zoho\\Lib\\site-packages" ],

output of "python -c 'import sys, pprint; pprint.pprint(sys.path)'" does not change however.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
python -c 'import sys, pprint; pprint.pprint(sys.path)'
['',
 'C:\\Users\\Sebastian.Schleicher\\Anaconda3\\envs\\zoho\\python310.zip',
 'C:\\Users\\Sebastian.Schleicher\\Anaconda3\\envs\\zoho\\DLLs',
 'C:\\Users\\Sebastian.Schleicher\\Anaconda3\\envs\\zoho\\lib',
 'C:\\Users\\Sebastian.Schleicher\\Anaconda3\\envs\\zoho',
 'C:\\Users\\Sebastian.Schleicher\\Anaconda3\\envs\\zoho\\lib\\site-packages'] 

```

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
