### ISSUE TITLE
pathvalidate: No suggestions

### ISSUE THREAD

**Issue by chr7** [microsoft/pylance-release#2518]
<h3> Environment data </h3>

-   Language Server version: 2022.3.3
-   OS and version: Windows_NT x64 10.0.18363
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.3
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Getting suggestions, e.g. `sanitize_filename`

<h3> Actual behaviour </h3>

![image](https://user-images.githubusercontent.com/7242780/160888621-4edbba09-a867-4192-b0c4-82dc283db533.png)

<h3> Logs </h3>

Python Language Server Log
```
[Info  - 18:51:13] (16756) SourceFile: Received fs event 'change' for path 'c:\Users\...\pylance-problem.py'
(16756) Background analysis message: markFilesDirty
(16756) Background analysis message: analyze
(16756) Background analysis message: getDiagnosticsForRange
(16756) Background analysis message: getDiagnosticsForRange
[Info  - 18:51:15] (16756) SourceFile: Received fs event 'change' for path 'c:\Users\...\pylance-problem.py'
(16756) Background analysis message: markFilesDirty
(16756) Background analysis message: analyze
```

<h3> Code Snippet / Additional information </h3>

Content of file `pylance-problem.py`:
```python
import pathvalidate

a = pathvalidate.san
```

**Comment by judej** [comment]
The pathvalidate library needs to update the way it does the imports. See this link:
https://github.com/python/typing/blob/master/docs/source/libraries.rst#library-interface

This needs to be fixed by the library author.
