### ISSUE TITLE
Linux - The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by RichardGladman** [microsoft/pylance-release#2522]
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic

## Expected behaviour

Able to use python language server

## Actual behaviour

Python language server crashes

## Logs

Too big for the comment - available at https://thefifthcontinent.com/files/vscode.log

**Comment by debonte** [comment]
`FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory`

**Comment by erictraut** [comment]
I think this issue has been addressed. I found and fixed some issues in the pyright logic that determines when to dump its type cache. This should prevent the javascript heap from running out of space.

**Comment by heejaechang** [comment]
@RichardGladman can you retry and see whether it still repro?

**Comment by RichardGladman** [comment]
Have tried starting vscode after updating and re-enabling pylance and the error seems to be gone :)

**Comment by Boon-in-Oz** [comment]
Sorry if this is poor form. Can/should I reopen this bug, or make a new one?

I am seeing this same error every hour or two using VS Code 1.69.2 on Windows, PyLance 2022.8.10 which I believe uses Pyright 1.1.264, which I think should contain the fix above(?)

I'm in a large workspace (contains most of the Python scripts we use at our location) and see this warning ~10 times at startup:
`[Warn  - 1:50:39 pm] (97096) Workspace indexing has hit its upper limit: 2000 files`

Then some time later I see errors like this and PyLance stops working:
```
<--- Last few GCs --->

[97096:00000DF8002E0000]  7354222 ms: Scavenge 524.4 (553.5) -> 520.7 (553.7) MB, 2.5 / 0.0 ms  (average mu = 0.998, current mu = 0.945) task; 
[97096:00000DF8002E0000]  7354510 ms: Scavenge 525.4 (553.7) -> 522.3 (555.7) MB, 1.6 / 0.0 ms  (average mu = 0.998, current mu = 0.945) task; 
[97096:00000DF8002E0000]  7355980 ms: Scavenge 527.2 (555.7) -> 524.1 (557.0) MB, 4.0 / 0.0 ms  (average mu = 0.998, current mu = 0.945) task; 


<--- JS stacktrace --->

FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory
 1: 00007FF7A0AD86D6 node::Buffer::New+50438
 2: 00007FF7A0AD88DF node::OnFatalError+463
 3: 00007FF7A35D07EA v8::ScriptOrigin::HostDefinedOptions+858
 4: 00007FF7A35D073C v8::ScriptOrigin::HostDefinedOptions+684
 5: 00007FF7A3677A43 v8::CppHeap::CollectGarbageInYoungGenerationForTesting+53827
 6: 00007FF79FFD29E5 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+156373
 7: 00007FF79FFCF5E4 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+143060
 8: 00007FF79FFBFB87 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+78967
 9: 00007FF79FFBE4F1 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+73185
10: 00007FF79FFBBC79 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+62825
11: 00007FF7A206F972 v8::CppHeap::GetHeapHandle+75666
12: 00007FF7A205F942 v8::CppHeap::GetHeapHandle+10082
13: 00007FF7A00A3F4F v8::internal::OSROptimizedCodeCache::GetBytecodeOffsetsFromSFI+179727
14: 00007FF727ECD67C 
[Error - 2:06:29 pm] Client Pylance: connection to server is erroring. Shutting down server.
[Error - 2:06:29 pm] Client Pylance: connection to server is erroring. Shutting down server.
[Error - 2:06:29 pm] Connection to server got closed. Server will not be restarted.
[Error - 2:06:29 pm] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:06:29 pm] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:06:29 pm] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by debonte** [comment]
@Boon-in-Oz, since this issue has been closed for several months, opening a new issue would be preferred. Thanks!
