### ISSUE TITLE
Rename Symbol Unexpected Behavior

### ISSUE THREAD

**Issue by AlteriusOmega** [microsoft/pylance-release#2525]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Setup:
Put cursor on a variable, hit F2, type new name and hit enter

Expected:
All instances of that variable are renamed to the new name

Actual:
Other variables are renamed to a seemingly random combination of their names and new names. Letters are also randomly capitalized.

## Steps to reproduce:

In a python program, select a variable and use Rename Symbol or hit F2. Do this a few times in a row on different variables. Usually on the third try, it will do unexpected things

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (40.30GB free)|
|Process Argv|--crash-reporter-id f59b737e-b5ef-4e72-8dfd-53ab67676639|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmc:30438804
vscgsvidc:30447482
vscaat:30438848
pynewfile477:30463512

```

</details>

https://user-images.githubusercontent.com/44767171/161144969-34c93a0f-5c01-4260-b2e0-21959de5b452.mp4

**Comment by heejaechang** [comment]
@AlteriusOmega can you provide some repro steps that we can try? I did very simple repro I created and it doesn't repro.

also, while you prepare repro, can you make sure that you don't have any other extensions enabled/installed except python/pylance extension? asking since I saw some others reporting similar issue and it was due to them having multiple extensions installed that handles rename. and they basically messed up each others rename edits.

**Comment by AlteriusOmega** [comment]
> 

I'm sorry, I can no longer reproduce this particular issue. I only had the Python and associated Jupyter extensions installed, nothing else. I fixed this particular issue by uninstalling all my extensions and, importantly, deleted all of the extension folders from the VSCode program folders, then reinstalled. I'm no longer having the very strange behavior seen here but I am having another issue where VSCode will not rename certain variables, giving "Request textDocument/prepareRename failed with message: Maximum call stack size exceeded" but I will submit that as another ticket.
