### ISSUE TITLE
Can't turn off autcomplete addBrackets setting

### ISSUE THREAD

**Issue by VaustXIII** [microsoft/pylance-release#2526]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
When typing function and choosing an autocomplete option, the extension automatically adds brackets. I have searched the settings to turn off that feature, but to no avail.
I tried searching extension settings for keywords: "brackets", "autocomplete", "parentheses", etc.
I tried googling but found only deprecated(?) options like `python.autocomplete.addBrackets` and `python.analysis.completeFunctionParens`

Expected:
Can turn off the setting
```python
ran
# pressing tab for autocomplete
range
```

Actual:
Can't turn off the setting, stuck with default behavior
```python
ran
# pressing tab for autocomplete
range(stop)
```

## Steps to reproduce:

Just start typing a function and choose an autocomplete option

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Jedi"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Jedi"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.17GB free)|
|Process Argv|--crash-reporter-id 088f1885-c167-44fe-9526-30aa212774ff|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by heejaechang** [comment]
@VaustXIII range is a class, not function, so our option "python.analysis.completeFunctionParens" won't affect it. can you uninstall or disable all extensions you installed on vscode and only enable python/pylance and try again to see whether it reproes?

**Comment by VaustXIII** [comment]
> @VaustXIII range is a class, not function, so our option "python.analysis.completeFunctionParens" won't affect it. can you uninstall or disable all extensions you installed on vscode and only enable python/pylance and try again to see whether it reproes?

The behavior is the same with functions too
```python
def some_func(p, q, r):
    pass

# I type
some_

# I press 'Tab' and get
some_func(p, q, r)
# the cursor is selecting 'q', I can type smth else instead of it, then press Tab again to go to 'q' and so on

# What I would like to get after pressing 'Tab'
some_func
```

By the way I could not find "python.analysis.completeFunctionParens" in settings. I tried adding it to settings.json manually, but it gets greyed out and "Unknown configuration setting" box pops up on hover.

I have tried disabling all extensions except for python, unfortunately it didn't help. Looks like this parentheses completion logic does come from the python extension, but I just can't find the setting controlling it

**Comment by VaustXIII** [comment]
@heejaechang is there a way to remove "waiting for user response" label?

**Comment by heejaechang** [comment]
@VaustXIII you are using pylance right? not pyright?

**Comment by VaustXIII** [comment]
@heejaechang 
Yep, the one that comes with the Python extension
![image](https://user-images.githubusercontent.com/21273876/171717221-5de58e07-a292-4b65-821f-2475bc39cdd1.png)

**Comment by heejaechang** [comment]
@VaustXIII if you are intentionally using Jedi, you should open the issue on Jedi repo.
