### ISSUE TITLE
Make optional the Intellisense offer of super()-calls when overwriting inherited methods

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#2531]
The feature of intellisense offering `super()`-calls when overwriting inherited methods is very useful (requested in #668).

But can it remain as optional? (activated in settings)

Because sometimes we may don't want to add the `super` call.
Like when implementing interfaces/abstract classes, for instance, as in [this example](https://github.com/microsoft/pylance-release/issues/2514#issuecomment-1080901254).

**Comment by erictraut** [comment]
This doesn't seem like a good candidate for a setting. It's not really a personal preference, but rather something that is contextual. The same user might want it in some cases but not in others. Switching a setting between these cases would be cumbersome.

In cases where you don't want to call through to the base class method, why not simply overwrite the code when you add the actual implementation?

**Comment by Diogo-Rossi** [comment]
It may be tedious to always remove the `super` call when implementing a lot of abstract classes.

But it is really just one line that we have to always remove in the methods. So, maybe you're right and it is not worth it.
If you judge this so, you can close the issue.

BTW, switching a specific setting so often is not so cumbersome when we install [this extension](https://marketplace.visualstudio.com/items?itemName=rebornix.toggle).

**Comment by erictraut** [comment]
What code would you want pylance to emit when the base method is abstract? The method requires at least one statement in its implementation to avoid a syntax error. Would you prefer that it emit `pass`? Or `""" You must provide an implementation here """`? In any case, it must emit some statement that you will need to replace. The statement `return super().<method>(<args>)` seems like it's as good as the other options, no?

**Comment by Diogo-Rossi** [comment]
You're right. I was thinking about "no emission at all", as we always have to implement something in abstract methods,
and that would force us to do it to avoid syntax error.

But the `return super().` statement is fine.
It is useful most of time, and can easily be erased when it is needed (<kbd>shift</kbd> + <kbd>home</kbd>, <kbd>del</kbd> do the job)

Sorry to bother you with that.
