### ISSUE TITLE
Can install Pylance normally in Gitpod ( a version of VS Code in the cloud )

### ISSUE THREAD

**Issue by jefer94** [microsoft/pylance-release#2532]
## Environment data

```
Gitpod Code
Version: 1.66.0
Commit: 82f23cb00067c9dab97976f9635a18bf3ef47ebd
Date: 2022-03-31T09:30:01.298Z (3 days ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
```

## Expected behaviour

Can install Pylance in Gitpod

## Actual behaviour

Is very much harder install that extension in Gitpod ( a version of VS Code in the cloud ), this behavior occur also with VS Code stable

## Logs

In Gitpod

![image](https://user-images.githubusercontent.com/3018142/161474935-3f4aaea0-bf09-491a-be46-ea9680507c8a.png)

In VS Code Insider

![image](https://user-images.githubusercontent.com/3018142/161475015-daf79b80-1e9c-4caf-bb19-b553c6103407.png)

## Code Snippet / Additional information

@loujaybee @gitpod-io https://github.com/gitpod-io/gitpod/issues/8945

**Comment by judej** [comment]
@jefer94, Pylance is licensed for use with Microsoft editors and IDEs. In the browser, today, you can run Pylance in [Github.dev in Preview](https://github.dev) and [vscode.dev in Preview](https://vscode.dev).

Unfortunately, at the moment there no plans to make it available to run on non-Microsoft editors.

**Comment by jefer94** [comment]
I don't understand you saying, I we apply the paradox of Ship of Theseus, the part Gitpod remove from VS Code is none and the part of VS Code Gitpod add is relatively is small, Gitpod is in essence VS Code, that really sound like DR-DOS vs MS-DOS again, monopoly practices, Gitpod is perfectly compatible with Pylance

Also vscode.dev not have a console 🤷‍♂️

Microsoft can take any decision about it, but I go to proceed through of way of ethical

**Comment by jrdzha** [comment]
Was looking for this as well. Figured out that if you open your Gitpod in VSCode Desktop, you'll be able to use Pylance.

https://www.gitpod.io/docs/ides-and-editors/vscode
