### ISSUE TITLE
Remove auto-import when typing the letter d to avoid being serenaded with The Zen of Python

### ISSUE THREAD

**Issue by hgibling** [microsoft/pylance-release#2535]
Hello,

After a lot of head scratching as to why my python script was suddenly reciting The Zen of Python this afternoon, I learned it was because my code had `from this import d` added to the top. I did not type that though.

After more head scratching I learned it was because I had typed a single letter `d` and accidentally hit enter before finishing my variable. Capital `D` triggers this as well.

I see how the auto-import functions are useful, but since this particular case adds a module that outputs a lengthy poem, perhaps this can be disabled, or more text can be required, or there can be a two-step confirmation process? It has bungled up at least [one other person](https://www.reddit.com/r/learnpython/comments/sjcd6l/disable_zen_of_python/).

**Comment by bschnurr** [comment]
should we also suggest adding '_' to the front of those variables in https://github.com/python/cpython/blob/main/Lib/this.py

**Comment by hgibling** [comment]
> This is both hysterical and very annoying. :)

Had this occurred 3 days prior I would have assumed it was an April Fool's joke!

**Comment by casellimarco** [comment]
Would it be possible to add the option to "whitelist" some packages in `python.analysis.autoImportCompletions`? For instance, when I use `pdb.set_trace()` I don't want it to go on the top of the file if I have forgotten to import it before

**Comment by debonte** [comment]
For this issue and #4229, we should exclude Easter egg stdlib modules from auto-import. Are there more than `this` and `antigravity`?

**Comment by heejaechang** [comment]
user can use `python.analysis.packageIndexDepths` to disable those if they want by giving the packate search depth 0

ex)
```
"name": "this",
"depth": 0
```

that said, I think it is good idea to filter them out from our indices at the first place.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.5.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023511-3-May-2023-PreRelease)
