### ISSUE TITLE
Error with serialport module Pymakr

### ISSUE THREAD

**Issue by tsipushnaya** [microsoft/pylance-release#2536]
There was an error with your serialport module, Pymakr will likely not work properly. Please try to install again or report an issue on our github (see developer console for details)
Source: Pymakr (Extension) 

No one of Pymakr commands doesn't work. (Example: Command 'Pymakr > Global settings' resulted in an error (command 'pymakr.globalSettings' not found)

Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.4.0

Pymakr: v1.1.17

This problem started on Thursday(3/31/2022) evening.

**Comment by bschnurr** [comment]
This is the Pylance repo. I think you are looking for the  Pymakr repo https://github.com/pycom/pymakr-vsc
