### ISSUE TITLE
Autocomplete of keyword ``self`` when writing classes methods

### ISSUE THREAD

**Issue by Badr-MOUFAD** [microsoft/pylance-release#2538]
It would be helpful to get autocomplete of ``self`` whenever writing a method within a class since it is a mandatory argument to be included in every class method in python.

Indeed, sometimes (often) I forget to write it which results in errors and bugs later.

**Comment by debonte** [comment]
> it is a mandatory argument to be included in every class method in python.

`self` is only required for instance methods, and not for methods decorated with `@classmethod` (which takes a class instead) or `@staticmethod`.

If we automatically add `self` for **all** methods, someone who is writing a `classmethod`/`staticmethod` and hasn't added the decorator yet would need to delete the auto-added `self` parameter. So automatically adding self doesn't feel like a clear win to me.

If you set `python.analysis.typeCheckingMode` to `basic` or `strict` (not `off`) and you forget to add the `self` parameter on an instance method, Pylance will give you the following error:

`Instance methods should take a "self" parameter Pylance[reportSelfClsParameterName]`

Have you tried this? Maybe this feedback would be sufficient to help you avoid the errors/bugs you mentioned?

**Comment by erictraut** [comment]
You can also enable `reportSelfClsParameterName` by itself without enabling other type checking diagnostics.

**Comment by Badr-MOUFAD** [comment]
Thanks for your responsivity!

I see what you mean @debonte. Yet, your solution is a bit overwhelming (got a lot of type checking errors).
I will stick with the one suggested by @erictraut. Works fine and serves my purpose.
