### ISSUE TITLE
Unexpected "Unknown" Type reported in generic method

### ISSUE THREAD

**Issue by Spenhouet** [microsoft/pylance-release#2539]
## Environment data

-   Language Server version: v2022.3.4
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.12

## Expected behaviour

I need a method which reduces a variable to a single value if it is a list. Since the type is generic, I did write the following method:

```python
from typing import List, TypeVar, Union

T = TypeVar('T')

def reduce_distinct(values: Union[List[T], T]) -> T:
    if isinstance(values, List):
        if len(values) == 0:
            raise ValueError('List is empty. No value to return.')
        
        return values[0]
        
    return values
```

To me the typing looks good and I would expect this to be fine.

## Actual behaviour

For `values[0]`, VS code shows this type hint:

```
(parameter) values: List[T@reduce_distinct] | List[Unknown]*
```

and pylance reports the following type error:

```
Expression of type "T@reduce_distinct | Unknown" cannot be assigned to return type "T@reduce_distinct"
  Type "T@reduce_distinct | Unknown" cannot be assigned to type "T@reduce_distinct"
```

**Comment by erictraut** [comment]
The `isinstance` check narrows the type of `values` to `list[T] | list[Unknown]`. Mypy evaluates the same type in this case.

This may be counterintuitive, but it makes sense if you consider that in type theory, type narrowing is distributive. The narrowed type of a union is the union of the narrowed types of the individual subtypes within the union. `N(A | B) = N(A) | N(B)`. 

```python
def fooA(value: list[T]):
    if isinstance(value, list):
        reveal_type(value) # list[T]

def fooB(value: T):
    if isinstance(value, list):
        reveal_type(value) # list[Unknown]

def fooAB(value: list[T] | T):
    if isinstance(value, list):
        reveal_type(value) # list[T] | list[Unknown]
```

You may need to resort to a `cast` in this case.

```python
        return cast(T, values[0])
```

**Comment by Spenhouet** [comment]
@erictraut Thanks for the good explanation of what is going on. It makes sense now but as you said, it is counterintuitive. One would expect that in a `list[T] | T` case, if we check if it is a list, the "just T" case is assumed to be "not the case" (if that makes sense).

If I put the cast there, it does no longer complain but this feels rather unnecessary.
I'm unsure if I should just rather put a `# type: ignore` comment there to not make this typing issue part of the code.

Isn't there anyway how this could be improved?
Sadly I can not check `isinstance(values, T)` which could theoretically also solve this.
Or is there any other way to express that `T` is not a list and that a check for `isinstance(values, list)` on the `T` case can not result in `list[Unknown]`?

**Comment by erictraut** [comment]
A `cast` is the best suggestion I could come up with in this case. I use `cast` only as a last resort and I never use `# type: ignore` (it's disallowed in my team's code base by virtue of enableTypeIgnoreComments=false).

The only other thought is to use a user-defined type guard (see [PEP 647](https://peps.python.org/pep-0647/)), but this doesn't narrow in the negative case, so it doesn't meet your needs here.

We have proposed a more limited form of `TypeGuard` called `StrictTypeGuard` that would work for your use case because it does narrow in the negative case. It is prototyped in pyright/pylance, but it hasn't been standardized and has no support in the runtime currently. Here's how it would work:

```python
from typing import List, TypeVar, Union
from typing_extensions import StrictTypeGuard

T = TypeVar("T")

def is_list(values: list[T] | T) -> StrictTypeGuard[list[T]]:
    return isinstance(values, list)

def reduce_distinct(values: Union[List[T], T]) -> T:
    if is_list(values):
        return values[0]

    return values
```

**Comment by Spenhouet** [comment]
> I use cast only as a last resort and I never use # type: ignore (it's disallowed in my team's code base by virtue of enableTypeIgnoreComments=false).

That's really cool but we are sadly far away from that. We are using packages which generate their code dynamically so there are no type and not type stubs and we don't want to patch a whole dependency to get type stubs. :(
So `# type: ignore` is quite common in our code base.

I like the `StrictTypeGuard`! At first it requires a bit getting used to when reading it but I get the idea and think this would be useful. I hope it will get official support.

Thanks for your help and explanations. I will go with the type cast for now.
