### ISSUE TITLE
Large performance penalty when analyzing "while True" loop

### ISSUE THREAD

**Issue by ClementPhan** [microsoft/pylance-release#2540]
<h3> Environment data </h3>

-   Language Server version: 2022.3.4
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.2
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

Near-realtime analysis.

<h3> Actual behaviour </h3>

Very long analysis time, more than 20 minutes in actual code.

I do not believe this was an issue in early march.

Removing the ```while True``` loop in the example files shortens the analysis from 8000ms to 3ms.

Is this expected behavior ?

<h3> Logs </h3>

~Python Language Server Log: [log.txt](https://github.com/microsoft/pylance-release/files/8425412/log.txt) (also in linked repo)~
edit : see linked repo

<h3> Code Snippet / Additional information </h3>

All example code is located in [ClementPhan/cphan-pylance-performance-issue](https://github.com/ClementPhan/cphan-pylance-performance-issue)

**Comment by ClementPhan** [comment]
Upon further testing I found:
- No issues in Pylance v2022.3.1
- Small performance penalty in v2022.3.2
- No change from 3.2 in v2022.3.3
- Large penalty un v2022.3.4

The different logs are updated in the referenced repo

**Comment by erictraut** [comment]
Thanks for the repro. 

I've made some significant changes to the code flow engine over the past month. These changes fixed several long-standing type evaluation bugs and also improved analysis performance significantly in some cases, but it is quite possible that it slowed analysis in other cases.

I'll investigate further.

**Comment by erictraut** [comment]
Thanks again for the repro. That made it much easier to diagnose the issue. This will be addressed in the next release.

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.4.1, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202241-13-April-2022)
