### ISSUE TITLE
Support for `**kwargs` autocompletion when using Unpack[T]

### ISSUE THREAD

**Issue by dgellow** [microsoft/pylance-release#2541]
Environment: Pylance version v2022.3.4, from vscode.

I'm not sure if it is a bug or would be considered a new feature. I understood from https://github.com/microsoft/pyright/issues/3002 that typed `**kwargs` are now supported by pylance/pyright. Thank you for this!

Now when I try the example mentioned at https://github.com/microsoft/pyright/issues/3002#issuecomment-1046100462 I see that while type checking seem to work correctly, the autocompletion doesn't seem to work as I would expect.

Let's say I have this code in vscode, with Pylance enabled:

```python
from typing_extensions import Unpack, TypedDict, Literal

class MyKwargs(TypedDict):
    foo: Literal["hello", "nopnop"]
    bar: int

def baz(**kwargs: Unpack[MyKwargs]) -> None:
    pass

baz(foo="hello", bar=3)
baz(|) # 👈 My caret is here
```

I would expect that when I trigger the autocompletion via `ctrl+space` I would get suggested `foo=` and `bar=`, but instead the only relevant suggestion is `kwargs=`.

![image](https://user-images.githubusercontent.com/2451004/161977172-ec0dd6ce-d195-4523-ae59-662c5fe455dd.png)

When I trigger the autocompletion for `MyKwargs()` arguments I get something correct, the issue seem to only be when using `Unpack[T]`:
![image](https://user-images.githubusercontent.com/2451004/161977459-10bf7631-9a6d-4f1e-bff7-b72b7e57273a.png)

It would be nice to have the list of keys of the unpacked typed dict :)

**Comment by bschnurr** [comment]
We would prefer to wait for it to become standard.  If that happens, please reopen if you would still like it.
Thank you.

**Comment by nitedani** [comment]
In my opinion, this is a must have feature for the future of python. Typescript had this for 10 years and it's an essential part of the language.

**Comment by erictraut** [comment]
The good news is that this proposal is one step closer to becoming standardized in Python. It is now a [draft PEP](https://peps.python.org/pep-0692/#:~:text=PEP%20692%20%E2%80%93%20Using%20TypedDict%20for,typing%20%7C%20peps.python.org), and if it's accepted, it will become part of Python 3.12.

**Comment by madkinsz** [comment]
@bschnurr it looks like this PEP has now been accepted and is on track to be a standard in Python 3.12. See https://peps.python.org/pep-0692/

Would you be willing to open this issue again?

**Comment by rchiodo** [comment]
We actually implemented this. It should be working in our latest prerelease. 

![image](https://user-images.githubusercontent.com/19672699/221929871-383f5ac4-c8aa-48b3-9b00-48b351c6ca6d.png)

**Comment by alon-ba** [comment]
It works really nice, thank you!
But - It produces 2 issues for me:

1. In the case that my TypedDict is complex - meaning having another TypedDict nested inside my main TypedDict - it wouldn't auto-complete the fields of the inner TypedDict, if not all fields of OuterDict are given:
![Image](https://github.com/user-attachments/assets/f442da44-861b-4412-8fb2-ce667940a0d4)
![Image](https://github.com/user-attachments/assets/46347dd5-c51e-44a6-9e24-a04562f5e3cc)

2. Probably MyPy's fault, not yours: With MyPy, if I don't invoke my method with all the required args I get a constant error `Missing named argument "xyz" for "some_method" Mypy(call-arg) - as if it expects to receive all the fields of my TypedDict, even if I marked them as optional. 
![Image](https://github.com/user-attachments/assets/5cd39209-119b-494d-9bab-342723c15145)

**Comment by erictraut** [comment]
Mypy is correct to generate an error here. You'll see the same error if you enable type errors in pylance. If you want the fields in your TypedDict to not be required, they need to be marked as "NotRequired". Alternatively, you can specify `total=False` which will implicitly mark all of the fields as `NotRequired`. In your sample, `field_1` is required and must be of type `int | None`.

```python
class MyDict(TypedDict, total=False):
    field_1: int | None
```

or

```python
class MyDict(TypedDict):
    field_1: NotRequired[int | None]
```

For future bug reports, please include your code in text form rather than (or in addition to) screen shots and open new issues rather than adding to issues that have been closed for a long time.

**Comment by alon-ba** [comment]
@erictraut 
Thank you very much! I'll try that tomorrow.
