### ISSUE TITLE
Wrong code block folding when parenthesis is at the end of the function

### ISSUE THREAD

**Issue by chebbyChefNEQ** [microsoft/pylance-release#2542]
Issue Type: <b>Bug</b>
minor bug in code folding

# Behaviour
## Expected vs. Actual

```python
def func() -> None:
    return (
        1 + 1
    )
```

After folding the cod looks like 
```python
def func() -> None:
    )
```

Expected after folding the cod looks like 
```python
def func() -> None:
```
<img width="237" alt="Screen Shot 2022-04-05 at 11 53 46 AM" src="https://user-images.githubusercontent.com/12615154/161829570-1c570eab-b383-4a56-87be-e07a7f78f17b.png">
<img width="249" alt="Screen Shot 2022-04-05 at 11 53 43 AM" src="https://user-images.githubusercontent.com/12615154/161829572-56a5e0e5-da31-4b9a-ac63-6fd5fcd133d9.png">

Extension version: 2022.4.0
VS Code version: Code 1.65.1 (Universal) (8908a9ca0f221f36507231afb39d2d8d1e182702, 2022-03-08T02:20:11.670Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

**Comment by bschnurr** [comment]
dup of #2333
