### ISSUE TITLE
False error presented on comment-based type annotation

### ISSUE THREAD

**Issue by c-schembri** [microsoft/pylance-release#2546]
## Environment data
Pylance version: 2022.4.0
OS version: 10.0.18363 Build 18363 (Windows 10)
Python version: 3.10.1 64-bit

## Expected behaviour
- Static analysis does not show an error for comment-based type annotation
- Static analysis should not throw errors on succeeding text after the comment-based type annotation

## Actual behaviour
- Static analysis does show an error for comment-based type annotation
- Static analysis should not throw errors on succeeding text after the comment-based type annotation

## Code Snippet / Additional information

```python
def get_tuple() -> tuple[str, str]:
    return 'a', 'b'


a, b = get_tuple()  # type: tuple[str, str] ... the errors occur here
```

![pylance_err](https://user-images.githubusercontent.com/47208537/162345872-1bfedbab-6b04-4a7a-bf50-6cdcb0b2db24.PNG)

**Comment by erictraut** [comment]
This is intended behavior. Type annotation comments have been deprecated for a long time. They were designed for backward compatibility with Python 2.x and early versions of Python 3.x. Type comments are supported in pylance only in places where you can place modern type annotations. Tuple expressions don't allow this. The correct way to do this today is as follows:

```python
a: str
b: str
a, b = get_tuple()
```

**Comment by c-schembri** [comment]
When were they deprecated/what is the source for that? As far as I know they weren't introduced solely for backwards compatibility but also for complex expressions. PEP 484 and PEP 526 make this clear: 

> [PEP 484](https://peps.python.org/pep-0484) explicitly states that type comments are intended to help with type inference in complex cases, and this PEP [526] does not change this intention.

As an aside, PyCharm sees this typing system as valid and does not return an error.

**Comment by erictraut** [comment]
The Python type system has evolved significantly since PEP 484. [PEP 526](https://peps.python.org/pep-0526/) effectively eliminated the need for type comments. We have no plans to add further support for type comments. If you want your code to work with pylance, you'll need to make this change.
