### ISSUE TITLE
pandas: Argument of type "(x: Unknown) -> list[Unknown]" cannot be assigned to parameter "arg" of type "() -> Any" in function "aggregate"

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#2547]
## Environment data

-   Language Server version: Pylance language server 2022.4.0 (pyright 67ee16be) starting
-   OS and version: macOS

## Expected behaviour

No error

## Actual behaviour

The `lambda x: list(x)` section is highlighted red with the error:

```
Argument of type "(x: Unknown) -> list[Unknown]" cannot be assigned to parameter "arg" of type "() -> Any" in function "aggregate"
  Type "(x: Unknown) -> list[Unknown]" cannot be assigned to type "() -> Any"
    Keyword parameter "x" is missing in destination
```

## Code Snippet / Additional information

```python
from typing import List
import pandas as pd

def group_tx(tx_df: pd.DataFrame, grouping_fields: List[str]) -> pd.DataFrame:
    grouped = tx_df.groupby(grouping_fields)[['date', 'amount']].aggregate(lambda x: list(x))
    return grouped
```

**Comment by debonte** [comment]
Currently the relevant overload is this:
```python
@overload 
def aggregate(self, func: Callable[[], Any], *args, **kwargs) -> DataFrame: ...
```
The [documentation for DataFrameGroupBy.aggregate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html#pandas.core.groupby.DataFrameGroupBy.aggregate) says that if `func` is a `Callable` it "must either work when passed a `DataFrame` or when passed to `DataFrame.apply`."

The [documentation for DataFrame.apply](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html?highlight=dataframe%20apply#pandas.DataFrame.apply) says, "objects passed to the function are `Series` objects." However, it later says that when the `raw` parameter of `apply` is `True`, the "function will receive `ndarray` objects instead."

So my interpretation of all this is that the first parameter of the function can be either a `DataFrame`, a `Series`, or an `ndarray`. Clearly `Callable[[], Any]` is not correct.

I believe the correct approach to typing `func` is to use `ParamSpec`, which would also allow proper typing of the optional `args` and `kwargs` parameters which are passed to the function in addition to the `DataFrame` / `Series` / `ndarray` mentioned above.

Something like this:

```python
P = ParamSpec("P")
@overload
def aggregate(self, func: Callable[[Concatenate[Union[DataFrame, Series, ndarray], P]], Any], *args: P.args, **kwargs: P.kwargs) -> DataFrame: ...
```

I noticed several other issues with the `aggregate` stubs that could be fixed at the same time:
- The `agg` and `aggregate` overloads are out of sync.
- We're missing an overload that takes a list of functions -- `List[Union[Callable, str]]`
- The `Dict` overload could be more specific than just `Dict` -- `Dict[str, Union[Callable, str, List[Union[Callable, str]]]]`
- The docstring has a good set of examples that should all pass type checking for both `agg` and `aggregate` but currently do not.

**Comment by debonte** [comment]
@tekumara, this no longer repros with the latest Pylance build which includes the latest [pandas-stubs](https://github.com/pandas-dev/pandas-stubs), so presumably this issue was fixed in the stubs.
