### ISSUE TITLE
python extesnion linting appears to be not working after pylance is installed

### ISSUE THREAD

**Issue by abhijit-sawant** [microsoft/pylance-release#255]
Is it expected that pylint warnings to be suppressed after pylance is installed? I have following in my settings.json for workspace  

```
    "python.linting.pylintArgs": [
        "--disable=invalid-name",
        "--init-hook",
        "import sys; sys.path.append(<some_path>); sys.path.append(<some_path_2>)"
    ]
```
Before I installed pylnace it used to work alright. But now I don't see it working.

**Comment by jakebailey** [comment]
Closing in favor of microsoft/vscode-python#13315. We don't have control over this extension behavior; the Python extension would need to have an option to still run pylint when an LS is active (and it disables it as it's assumed it's only needed for syntax checks).
