### ISSUE TITLE
Pylance not working in WSL2 (Ubuntu)

### ISSUE THREAD

**Issue by tundragon** [microsoft/pylance-release#2555]
Hello,

I am using WSL2 ( 
Ubuntu 
$ uname -a
Linux COMPUTERNAME 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
)
with Python 3.8.10. 
And the extension "Remote WSL" to connect to WSL2

The host is:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation

I am using VSCode
Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

**I have installed Pylance on WSL and it was working.
Since few weeks ago, Pylance stopped working when installed in WSL2.
It shows "Loading"
Pressing CTRL + Space: https://prnt.sc/4AzJK0FLSy9q
Mouse Hover: https://prnt.sc/wc_JrpQYLGyB**

________________________
I have tried like in this issue: https://github.com/microsoft/pylance-release/issues/1428
But still does not work.

This is the list of my VSCode extensions ( enabled and disabeld )
https://pastebin.com/QuR4iYm8

This is the Pylance Log level trace
It says "No configuration file found.", but i do not remember creating a config file for pylance...

[Info  - 12:45:58 AM] (957) Pylance language server 2022.4.0 (pyright 67ee16be) starting
[Info  - 12:45:58 AM] (957) Server root directory: /home/usern/.vscode-server/extensions/ms-python.vscode-pylance-2022.4.0/dist
[Info  - 12:45:58 AM] (957) No configuration file found.
[Info  - 12:45:58 AM] (957) No pyproject.toml file found.
[Info  - 12:45:58 AM] (957) Setting pythonPath for service "wsl+ubuntu": "/bin/python3"
[Warn  - 12:45:58 AM] (957) stubPath /typings is not a valid directory.
[Info  - 12:45:58 AM] (957) Assuming Python version 3.8
[Info  - 12:45:58 AM] (957) Assuming Python platform Linux
[Info  - 12:45:58 AM] (957) Searching for source files
[Warn  - 12:45:58 AM] (957) Skipping recursive symlink "/bin/X11" -> "/usr/bin"
[Error - 12:46:08 AM] (957) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.

[Info  - 12:45:58 AM] (957) Pylance language server 2022.4.0 (pyright 67ee16be) starting
[Info  - 12:45:58 AM] (957) Server root directory: /home/usern/.vscode-server/extensions/ms-python.vscode-pylance-2022.4.0/dist
[Info  - 12:45:58 AM] (957) No configuration file found.
[Info  - 12:45:58 AM] (957) No pyproject.toml file found.
[Info  - 12:45:58 AM] (957) Setting pythonPath for service "wsl+ubuntu": "/bin/python3"
[Warn  - 12:45:58 AM] (957) stubPath /typings is not a valid directory.
[Info  - 12:45:58 AM] (957) Assuming Python version 3.8
[Info  - 12:45:58 AM] (957) Assuming Python platform Linux
[Info  - 12:45:58 AM] (957) Searching for source files
[Warn  - 12:45:58 AM] (957) Skipping recursive symlink "/bin/X11" -> "/usr/bin"
[Error - 12:46:08 AM] (957) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.

I have tried disabling all other extensions and enabling only pylance, but it still showing "Loading"

**Comment by judej** [comment]
Thanks for the report. It seems like the folder you are opening has a lot of files/folders. Is the folder you are opening the correct project folder? The error message might be worth investigating:
 - You have opened your home directory or entire hard drive as a workspace
 - Your workspace contains a very large number of directories and files
 - Your workspace contains a symlink to a directory with many files.
 
 If after investigating that, you are still unable to resolve it, please reopen this issue. It would be useful if we can look at the project.

**Comment by tundragon** [comment]
Yes, i have opened now only the folder with my project.

I see that Pylance is working.

I usually open / in WSL2 with Vscode, or my the folder with all of my scripts.



Why is Pylance behaves like this ( showing the Loading tooltip ), if i open a folder with a lot of files?
Shouldn't Pylance work regardless?
Why other similar extensions work and Pylance does not?

**Comment by erictraut** [comment]
Some operations in Pylance (such as "find all references" and "rename symbol") require Pylance to understand which Python source files comprise your current project. As such, it needs to do a file system scan under your project's root directory to determine which Python files are located within your project root. If you open `/` in your editor, it needs to scan all of the directories and subdirectories on that drive to find Python files.

You can avoid this by opening the directory of the project that you are interested in working on.

**Comment by HeliumOctahelide** [comment]
I had basically the same problem, except I was running Pylance in a directory under `/mnt/` instead of `/`. 
This problem is rarely seen when you're using Windows, but is greatly amplified by WSL2's horribly poor performance when reading Windows files. When I open the workspace under WSL2, it takes a dozen minutes for Pylance to work properly, while under Windows it only takes a few seconds.
