### ISSUE TITLE
Inherited class variable modification

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#2558]
In fact：
![image](https://user-images.githubusercontent.com/100815370/162672709-acd53934-87a8-499f-9431-0ae12e11c8f5.png)

Expect：
![image](https://user-images.githubusercontent.com/100815370/162672746-8418f225-6114-4596-bb48-17f20158468e.png)

**Comment by heejaechang** [comment]
we currently only show methods so it can be overriden, but not fields.

**Comment by judej** [comment]
Dupe of #2059
