### ISSUE TITLE
"Type" is inconsistent and cannot be allocated

### ISSUE THREAD

**Issue by A-kirami** [microsoft/pylance-release#2560]
## Environment data

-   Language Server version: v2022.4.0
-   OS and version: Windows11 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0

## Expected behavior

No error.

## Actual behavior

```
Cannot assign member "checker" for type "Type[ServiceCheckerChain]"
  Expression of type "CheckerChainNode" cannot be assigned to member "checker" of class "ServiceCheckerChain"
    Type "CheckerChainNode" cannot be assigned to type "Type[CheckerChainNode] | None"
      Type "CheckerChainNode" cannot be assigned to type "Type[CheckerChainNode]"
      Type cannot be assigned to type "None"
```

## Code Snippet / Additional information

```python
from abc import ABC
from typing import ClassVar, Type

class ServiceCheckerChain(object):
    checker: ClassVar[Type["CheckerChainNode"] | None] = None

    @classmethod
    def register(cls, checker: Type["CheckerChainNode"]) -> Type["CheckerChainNode"]:
        cls.checker = checker(cls.checker)
        return checker


class CheckerChainNode(ABC):
    def __init__(self, next_checker: Type["CheckerChainNode"] | None = None):
        self.next_checker = next_checker
```

![image](https://user-images.githubusercontent.com/66513481/162970607-7739a100-ea53-4723-ab1e-cb13569eb0e2.png)

**Comment by erictraut** [comment]
Pylance is correct to emit an error here. The type of the class variable `checker` is declared to be `Type[CheckerChainNode]`, but you are trying to assign an instance of `CheckerChainNode` to it.

Is this what you intended instead?
```python
cls.checker = checker
```

Or is your intent to assign an instance of `CheckerChainNode`? If so, you need to change the type annotation for the `checker` class variable:

```python
checker: ClassVar["CheckerChainNode" | None] = None
```

**Comment by A-kirami** [comment]
Yes, I want to assign an instance of CheckerChainNode. 

I try to change type annotation to what you say, but to my confuse, I found error occured in other place.

```
Argument of type "CheckerChainNode | None" cannot be assigned to parameter "next_checker" of type "Type[CheckerChainNode] | None" in function "__init__"
  Type "CheckerChainNode | None" cannot be assigned to type "Type[CheckerChainNode] | None"
    Type "CheckerChainNode" cannot be assigned to type "Type[CheckerChainNode] | None"
      Type "CheckerChainNode" cannot be assigned to type "Type[CheckerChainNode]"
      Type cannot be assigned to type "None"
```

![image](https://user-images.githubusercontent.com/66513481/163012888-81dce0df-1e98-44df-b8d2-9d338b71e416.png)

**Comment by erictraut** [comment]
The new error is because you have the wrong annotation on the constructor for `CheckerChainNode`. It too should accept an instance, not a type of an instance.
