### ISSUE TITLE
IntelliSense is not working in pylance.

### ISSUE THREAD

**Issue by big100** [microsoft/pylance-release#2563]
If the language server is pylance, it will not work in the following cases.

IntelliSense is not working in pylance.
![image](https://user-images.githubusercontent.com/37491415/163140377-25454fdc-b686-4a91-9f26-8ec4ccf886de.png)

It works in Judi.
![image](https://user-images.githubusercontent.com/37491415/163140397-cd8a1ef4-d97b-4768-b223-ef6cb93528a9.png)

It works in PyCharm.
![image](https://user-images.githubusercontent.com/37491415/163140920-37b54910-0e32-4f72-bc93-f76a5b8121d6.png)

The code has the following path.

class Main(QMainWindow, Ui_MainWindow):

     def __init__(self, tQ):

         super().__init__()
         self.setupUi(self)
         self.setui = SetUI(self, tQ)
         self.setui.SetupUI()

class SetUI:

     def __init__(self, ui_class, tQ):
         super().__init__()
         self.ui = ui_class
        
     def SetupUI(self):
         self.ui.file_down.clicked.connect(self.file_down)
         self.ui.file_clear.clicked.connect(self.file_clear)
         self.ui.file

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
