### ISSUE TITLE
pathvalidate: Jedi provides suggestions, pylance not

### ISSUE THREAD

**Issue by chr7** [microsoft/pylance-release#2564]
## Environment data

-   Language Server version: v2022.4.0
-   OS and version: Windows_NT x64 10.0.18363
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.3
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

## Expected behavior

Selecting Jedi as language server:

![image](https://user-images.githubusercontent.com/7242780/163146446-9c09b767-7ae4-4c54-8e65-d9d6347a3e89.png)

## Actual behavior

Pylance:

![image](https://user-images.githubusercontent.com/7242780/163146400-9daf749a-1fc7-4f96-b1c3-71d912629452.png)

**Comment by bschnurr** [comment]
https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface
Imported symbols are considered private by default. If they use the “import A as A” 

![image](https://user-images.githubusercontent.com/1946977/163242260-1bd192fe-9b37-4c47-840e-b3528fae6f3d.png)

**Comment by bschnurr** [comment]
please file an issue with pathvalidate
