### ISSUE TITLE
Add [correct|full] code [completion|suggestion], please!

### ISSUE THREAD

**Issue by weranda** [microsoft/pylance-release#2568]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
I use python with a "Python extension for Visual Studio Code" from Microsoft and it doesn't work properly.

## Steps to reproduce:
I use this code:

```
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String


engine = create_engine("sqlite:///foo.db")
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))


usr1 = User(
    name = "Iona"
)

sel = session.
```
After the last dot I suppose to see any suggestion, but it doesn't happen. I think it is a bug.
![1](https://user-images.githubusercontent.com/9132570/163314993-0159b95b-d4a5-444f-b708-b43b59c065d8.png)
![2](https://user-images.githubusercontent.com/9132570/163315007-b86dcfda-6ceb-4f14-84c7-9b9327f6dfaf.png)

Take a look how it works in a PyChart — it works correctly.
![3](https://user-images.githubusercontent.com/9132570/163315030-c19a9ac7-d85c-46d8-9713-f7156036cb5f.png)
![4](https://user-images.githubusercontent.com/9132570/163315039-123e04ed-7ae6-4fa4-a8e7-a4a877383cb7.png)

# Diagnostic data

-   Python version: 3.8.8
-   Type of virtual environment used: Venv
-   Value of the `python.languageServer` setting: Pylance

<details>
<summary>User Settings</summary>
<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: true
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.1
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|64.00GB (22.14GB free)|
|Process Argv|--crash-reporter-id 5ac13ee3-fc6e-4561-9583-5e8ddeb33a1c|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by erictraut** [comment]
You don't receive any completion suggestions for `session` because its type is unknown. That's because the type declaration for the `sessionmaker` class is incomplete in the typeshed SqlAlchemy type stubs. 

Here's the specific line of interest: https://github.com/python/typeshed/blob/40985b4f0258e6ee6af3b9f79675fc85bd8e66d8/stubs/SQLAlchemy/sqlalchemy/orm/session.pyi#L217. Note that the `__call__` method has no return type annotation.

Pylance (and other type checkers and language servers) rely on typeshed stubs for type information. If those stubs are incomplete or incorrect, you will see incomplete or incorrect type completion information. Typeshed is open source, so you're welcome to contribute improvements to those stubs. Pylance regularly picks up new versions of typeshed stubs.

**Comment by lowercase00** [comment]
I guess PyCharm probably uses `sqlalchemy-stubs` automatically? Given this is one of the most used ORMs, would you guys consider leveraging the stubs for Pylance to understand SQLAlchemy better?

To avoid opening a new issue, and considering this is related, even with `sqlalchemy-stubs` we notice errors when using Pylance (MyPy can pick those normally).

---

Creating a SQLAlchemy model:

![Screen Shot 2022-05-03 at 14 42 08](https://user-images.githubusercontent.com/21188280/166508964-f691f3b1-640d-4f7d-8add-23374a502853.png)

---

Changing a SQLAlchemy model attribute:

![Screen Shot 2022-05-03 at 14 42 27](https://user-images.githubusercontent.com/21188280/166509030-632aa8fc-a3ea-4e20-bdf4-9869b2fa7a32.png)

**Comment by erictraut** [comment]
There are multiple type stubs available for sqlalchemy, and they all have their own deficiencies and limitations. As I mentioned above, Pylance includes the version of the stubs from typeshed. If you encounter incomplete or inaccurate types, please consider filing a bug (or even a PR) in the typeshed repo. The entire Python community will benefit from such improvements.

**Comment by lowercase00** [comment]
@erictraut got it, I hadn't understand that the stubs should be a part of the typeshed, thanks for the clarification.
As I understand SQLAlchemy is moving towards native typing starting with +1.4 and then 2.0, so not sure this is the best timing, but I'll open an issue to see if those can be merged somehow. without this being fixed unfortunately we can't use Pylance. Thanks

**Comment by erictraut** [comment]
@lowercase00, if you prefer to use other stubs for sqlalchemy such as `sqlalchemy-stubs`, you can install those into your Python environment, and Pylance will use those instead of ones from typeshed. The bundled typeshed stubs are resolved last, so any other installed versions will take precedence.

**Comment by lowercase00** [comment]
Hmm, we do have those installed, so maybe there's something wrong on our end that makes Pylance not pickup the installed stubs, we've been turning it off completely because of that. I'll make some tests on a fresh repo to if I can reproduce and let you guys know if I find anything.
