### ISSUE TITLE
Can not find the include file's fuction define in vscode jupyter

### ISSUE THREAD

**Issue by hzs268** [microsoft/pylance-release#2569]
The fuction can run,but report "XXX" is not define
![2022_04_15_12_03_58](https://user-images.githubusercontent.com/58660484/163517012-90f13533-e1fa-437a-bf65-beb251745930.png)
d

**Comment by judej** [comment]
Thanks for the report. The `main.ipynb` is in the project root. In order to import `func`, you will need to treat inc as a module. So you would you please try `from inc.func import *`

Please reopen this issue if this continues to be a problem.

thanks
