### ISSUE TITLE
Intellisense does not work on modules

### ISSUE THREAD

**Issue by crowbardispensingcore** [microsoft/pylance-release#2570]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

For built-in types intellisense works normally
![image](https://user-images.githubusercontent.com/22359365/163537262-0cf27ae1-bbbc-40ad-96ee-3a8ca611257a.png)

For any pip installed packages, suggestion or autocomplete only works partially or does not work at all.
Example:
![image](https://user-images.githubusercontent.com/22359365/163537536-e462046d-d7d0-48c4-8f54-0e9c3b35b6db.png)
![image](https://user-images.githubusercontent.com/22359365/163537501-7414d6dd-fccf-48a7-9ea7-9f65696fb19e.png)
![image](https://user-images.githubusercontent.com/22359365/163537579-24f7fbab-b318-4834-90c0-082d6b742818.png)
Also does not work on any local variables
![image](https://user-images.githubusercontent.com/22359365/163543993-0e8703f9-413e-411c-9e13-4cc70642fdea.png)
![image](https://user-images.githubusercontent.com/22359365/163537630-5e191991-d21e-4a14-b2f3-6491ff0b42c1.png)

I've tested it in both virtual environment and global environment; neither works.
I've done clean installation of vscode, python, and pylance extensions. I have tried to reset all settings. 

If I switch to Jedi, intellisense seems to work but I lose all syntax highlights
![image](https://user-images.githubusercontent.com/22359365/163538671-bae1247a-99aa-484b-9930-f001488e9e02.png)

## Steps to reproduce:

Clean installation of vscode, python, and extensions

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: true
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.2-pre.1
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22598
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.87GB free)|
|Process Argv|--crash-reporter-id 1b0fe587-bf67-4fc1-a53d-e130ee8d7382|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by heejaechang** [comment]
@crowbardispensingcore can you give us a repro? or at least give us some info such as what package are installed, what platform/os you are using and etc?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
