### ISSUE TITLE
Pylance result differs for variable and 

### ISSUE THREAD

**Issue by neighthan** [microsoft/pylance-release#259]
## Environment data

-   Language Server version: 2020.8.1
-   OS and version: Ubuntu 16.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7 (Anaconda)

## Expected behavior

I would expect pylance to give the same typing results (e.g. report the same issues) when a function is called with an object literal as input or with a variable. However, in the below example, this isn't the case:

```python
from typing import Tuple, Union, Dict

def f(x: Dict[str, Union[Tuple[int], Tuple[int, int]]]):
    pass

o = {"": (1, 2)}
f(o)
f({"": (1, 2)})
```

I would also expect `o` to match the input type for `f`, though that doesn't seem to be the main issue here.

## Actual behavior

pylance underlines `f(o)` and says

```
(variable) o: dict[str, Tuple[Literal[1], Literal[2]]]
Argument of type "dict[str, Tuple[Literal[1], Literal[2]]]" cannot be assigned to parameter "x" of type "Dict[str, Tuple[int] | Tuple[int, int]]" in function "f"
  TypeVar "_VT" is invariant
    Type "Tuple[Literal[1], Literal[2]]" cannot be assigned to type "Tuple[int] | Tuple[int, int]" Pylance (reportGeneralTypeIssues)
```

However, for `f({"": (1, 2)}`, pylance doesn't report any issues. Why is pylance treating these two function calls differently?

**Comment by erictraut** [comment]
Type inference for dictionaries leverages contextual clues when available. When you assign a dictionary expression to a variable with no type annotation, there are no contextual clues, so inference falls back on default rules/heuristics. When you use a dictionary expression in a call expression, the "expected type" of the corresponding parameter provides additional context for inference.

For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#dictionary-expressions).

When I encounter this situation, I typically solve it by adding a type annotation to the variable.
```
a: Dict[str, Union[Tuple[int], Tuple[int, int]]] = {"": (1, 2)}
f(o)
```
Or you might want to use a type alias to avoid repeating the long type:
```
MyDict = Dict[str, Union[Tuple[int], Tuple[int, int]]]
def f(x: MyDict):
    pass

o: MyDict = {"": (1, 2)}
f(o)
```

**Comment by neighthan** [comment]
Ah, thanks for the reference to the docs. In addition to the dictionary section, the [bi-directional inference section](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md#bidirectional-type-inference-expected-types) describes the behavior you mentioned, which I wasn't aware of. I wouldn't mind seeing a suggestion in the pylance readme to look at that docs page first if one has questions (I learned about `Literal` types there too; I'm still on Python 3.7, so I hadn't seen those before), but I'll close this issue since there's no real problem.
