### ISSUE TITLE
Resizable Docstring

### ISSUE THREAD

**Issue by timrid** [microsoft/pylance-release#26]
I'm wondering if there is a way to resize the docstring, that is printend while autocompletion. If there is a very long docstring, there are many linebreaks which make it harder to read, like in the image below.

![image](https://user-images.githubusercontent.com/6593626/86322772-d91efb00-bc3b-11ea-9283-d5d4f4fe1343.png)

**Comment by jakebailey** [comment]
Unfortunately, the docstring window's dimensions are determined by the editor; a language server can only respond with markdown and it's up to VS Code to display it. We don't get any sort of feedback as to how wide a window the text is going to be rendered in.

For example, you can stretch VS Code across 3 monitors, and it will expand the tooltips just as wide.

This is an ongoing display thing we'd like to try and work out, but it may require LSP changes.

**Comment by huguesv** [comment]
Please upvote/comment on this issue on the vscode repo for a more configurable tooltip sizing:
https://github.com/microsoft/vscode/issues/14165

thanks!
