### ISSUE TITLE
Improve scraper to handle collections.defaultdict doc string format

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#2600]
our current scrapper can't extract doc string for collections.defaultdict and deque properly. causing us to unable to show doc string for those 2 symbols.

**Comment by heejaechang** [comment]
it is enhancement since our scrapper is full of heuristics and we don't handle every possible doc string formats users use.

**Comment by debonte** [comment]
Do all of the modules in `sys.builtin_module_names` have the same issue or is `_collections` special?

**Comment by heejaechang** [comment]
I only looked _collections and _io. _io worked fine but didn't work for _collections

**Comment by heejaechang** [comment]
@debonte I didn't make the logic to blindly scrap all builtin modules, but manually listed one that are tested or reported.

**Comment by heejaechang** [comment]
I am going to just put enhancement tag back since it is not a bug.

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.6.30, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022630-22-June-2022)
