### ISSUE TITLE
Show module path of symbols about to be auto-imported

### ISSUE THREAD

**Issue by underyx** [microsoft/pylance-release#2604]
There is no way to tell which of these two options is the one I actually want to import. The first one imports `boto3.auth`, the second one imports `semgrep.auth` (which is my first party module).

<img width="495" alt="CleanShot 2022-04-19 at 11 22 50@2x" src="https://user-images.githubusercontent.com/1060436/164070347-f80db6ad-aa18-4ebe-8025-c9839b713b2b.png">

**Comment by heejaechang** [comment]
@underyx it already has that info if you expand completion item by clicking > at the end of the item.

![image](https://user-images.githubusercontent.com/1333179/164289458-d7cfa010-898d-47f4-8a5c-e2eb6fda4de0.png)

see here for more detail about quick info on completion item - https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features

**Comment by underyx** [comment]
It would still be nice to not need to click all those small buttons and instead be able to decide at a glance which auto-completion I should pick :/

Should this be a feature request for vscode then?

**Comment by erictraut** [comment]
If you toggle the additional information, it will continue to appear every time you do an autocompletion — at least until you toggle it off again. I typically just leave it toggled on at all times.

**Comment by underyx** [comment]
I see, thank you! I guess this is a vscode UX issue then. I'll try to remember to create it later.
