### ISSUE TITLE
Prefer auto-importing from first party packages instead of third party

### ISSUE THREAD

**Issue by underyx** [microsoft/pylance-release#2605]
This is along the lines of https://github.com/microsoft/pylance-release/issues/2604. As mentioned in that issue, the first option here imports `boto3.auth`, the second one imports `semgrep.auth` (which is my first party module).

<img width="495" alt="CleanShot 2022-04-19 at 11 22 50@2x" src="https://user-images.githubusercontent.com/1060436/164070347-f80db6ad-aa18-4ebe-8025-c9839b713b2b.png">

I think the first party suggestions should be shown first.

**Comment by heejaechang** [comment]
@underyx unfortunately, ordering in this case is not determined by us but vscode and even if we can, python doesn't provide information on which packages are supposed to be first party or not.
