### ISSUE TITLE
Pylance import suggestion doesn't recommend variable I'm trying to import

### ISSUE THREAD

**Issue by underyx** [microsoft/pylance-release#2606]
<h3> Environment data </h3>

-   Language Server version: 2022.4.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): python 3.10
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

`Cmd-.` should suggest the correct import path for a variable called `app_session` here:

#### `semgrep/publish.py`

```py
    if not app_session.token:
        # ...
```

where `app_session` is defined as:

#### `semgrep/app/__init__.py`

```py
from .session import AppSession

app_session = AppSession()
```

<h3> Actual behaviour </h3>

### When `semgrep/app/__init__.py` is not open in a tab

<img width="918" alt="CleanShot 2022-04-19 at 11 40 07@2x" src="https://user-images.githubusercontent.com/1060436/164073192-a00b7bca-0f59-42fa-9970-873fa4432445.png">

This suggestion comes up which is very far off.

### When `semgrep/app/__init__.py` is open in a tab

<img width="917" alt="CleanShot 2022-04-19 at 11 42 27@2x" src="https://user-images.githubusercontent.com/1060436/164073538-ab11ec4e-8a2e-46c3-b830-b15651939bcd.png">

This suggestion comes up, which is defined as:

#### `semgrep/app/session.py`

```py
class AppSession(requests.Session):
    ...
```

<h3> Logs </h3>

https://gist.github.com/underyx/c308790296457d25360c3145e43d78d6

**Comment by heejaechang** [comment]
Pylance only include symbols exported from top level package module (ex, ```semgrep/__init__.py```) to prevent completion list become too long.

but we do provide hidden knob on how much we include in completion (with performance cost, of course)

see this for more detail - https://github.com/microsoft/pylance-release/issues/2533#issuecomment-1089268739

**Comment by heejaechang** [comment]
@underyx I think you have indexing off, so we fallback to the behavior where we only get data from files that are already consumed through opened files, either directly or indirectly.

also, by default, we don't import most of variables since python has nothing to indicate which variable is supposed to be used outside or it is supposed to be used only locally.
