### ISSUE TITLE
Document how to exclude files from analysis

### ISSUE THREAD

**Issue by underyx** [microsoft/pylance-release#2607]
I have a workspace with Python 8000 files, only 200 of which are part of the project. Pylance has been misbehaving in all sorts of ways until I found out that it's not respecting my vscode settings for ignoring paths. Please document that you need to add a file like

#### `pyrightconfig.json`

```json
{
  "exclude": [
    "**/site-packages/**",
    ".vscode/*.py",
    "**/.venv/**",
    "**/.tox/**",
    "**/build/**",
    "perf/bench/**",
    "semgrep/tests/e2e/targets/**",
    "semgrep/tests/e2e/snapshots/**",
    "semgrep/tests/e2e/rules/syntax/**",
    "semgrep/semgrep/external/**",
    "semgrep-core/**/tests/**"
  ]
}
```

in the repository root for files to actually get ignored.

**Comment by heejaechang** [comment]
we have discussion on this - https://github.com/microsoft/pylance-release/discussions/2581 - please, upvote there.
