### ISSUE TITLE
Add support for VS Code's smart select API

### ISSUE THREAD

**Issue by mattbierner** [microsoft/pylance-release#266]
## Feature Request
It'd be great to have support for VS Code's smart select API (`SelectionRangeProvider` which is exposed to users by the expand/shrink selection commands)

The default implementation is designed for bracket based languages and therefore it isn't too useful in python files

**Comment by yellowtailfan** [comment]
Yes this would be great. For example, at the moment using pylance:
1. I put the cursor inside a single-quoted string which in turn is inside `()`
2. I press Shift-Alt-RightArrow and the word is highlighted
3. I press Shift-Alt-RightArrow again and everything inside the `()` is highlighted
What I expect and hope to happen instead at step (3) is that everything inside the single-quotes is highlighted.

The same thing happens with double-quoted strings too.

**Comment by Vikdemen** [comment]
This is a major pain point for switching between VSCode and Pycharm.
After doing "expand selection" with a selected line, I'm selecting all lines in a file.
This is not very useful, and I'd prefer finer grained control.

1. It selects the lines indented under current line.
It is useful both for selecting a "header" with its content - function definition, loop condition, ect. and for selecting multi-line statements (usually continuation is indented)

2. It selects all lines with the same or higher level of indentation, unless separated by 2+ whitespace.
It is useful when you want to select, say, a function body.

3. It selects all lines with the same or higher level of indentation regardless of whitespace.
It is useful when you want to select all methods of a class, for example.
If used when indentation = 0, equivalent to "select all"

4. It selects one line with lower indentation level than 
It is useful when you want to include the "header" - definitions, if statements, loops, ect. from within their scope.
Also, it puts you in the same state as 1. if you had the header line selected first.

**Comment by debonte** [comment]
Smart selection support was added in [2021.12.1](https://github.com/microsoft/pylance-release/releases/tag/2021.12.1).
