### ISSUE TITLE
Pylance cannot read type informations from .pyi file at the same level of directory

### ISSUE THREAD

**Issue by nukemiko** [microsoft/pylance-release#2665]
## Environment data

-   Language Server version: 2022.4.1
-   OS and version: Arch Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4 at /usr/bin/python3.10, without virtual environment
-   Project hierarchy:
    ```text
    test
    └── src
        └── testpkg
            ├── __init__.py
            ├── __init__.pyi
            ├── util.py
            └── util.pyi

    2 directories, 4 files
    ```

## Expected behavior

- The type of function's parameters and return will normally display (screenshot from `util.pyi`):

![Screenshot_20220420_202556](https://user-images.githubusercontent.com/53572814/164230584-74f029f8-0dcd-43fc-978a-b0eaca2de04a.png)
![Screenshot_20220420_202613](https://user-images.githubusercontent.com/53572814/164230593-e2c4e9b8-8320-4eb5-8ec5-c689123b8c1d.png)
![Screenshot_20220420_204348](https://user-images.githubusercontent.com/53572814/164233224-0d22bf03-4c74-4602-9bdb-741ddd828165.png)

## Actual behavior

- The type of function's parameters and return  displayed `Unknown`, unless the Pylance deduced them type from the code, like this (screenshot from `util.py`):

![Screenshot_20220420_202639](https://user-images.githubusercontent.com/53572814/164230340-86939a81-f714-4ab8-8bab-4161fce6291e.png)
![Screenshot_20220420_202701](https://user-images.githubusercontent.com/53572814/164230359-fde7a4ed-9649-4ea8-b170-afe94a4de0d2.png)
![Screenshot_20220420_204414](https://user-images.githubusercontent.com/53572814/164233342-747ef198-3acb-45a1-8365-3c9d3af1fa28.png)

## Logs

I put it in the pastebin: https://pst.klgrth.io/paste/hogqcwwcfej7jjdg3yhr5bbf

## Code Snippet / Additional information

`utils.py`:
```python
def bytesxor(term1, term2):
    segment1 = bytes(term1)
    segment2 = bytes(term2)

    if len(segment1) != len(segment2):
        raise ValueError('only byte strings of equal length can be xored')

    def xor():
        for b1, b2 in zip(segment1, segment2):
            yield b1 ^ b2

    return bytes(xor())


def normally_return(obj):
    return obj


def string_modify(s):
    if not isinstance(s, str):
        raise TypeError(f"'{s}' must be str, not {type(s).__name__}")

    return s + '.modified'


def verify_fileobj(obj):
    if isinstance(obj, (str, bytes)) or hasattr(obj, '__fspath__'):
        raise ValueError(f"{repr(obj)} is not a file object")


def verify_readable(fileobj, is_binary=True):
    verify_fileobj(fileobj)
    target_type = str
    if is_binary:
        target_type = bytes

    fileobj_readable = getattr(fileobj, 'readable', None)
    if callable(fileobj_readable):
        if not fileobj_readable():
            raise ValueError(f"file {repr(fileobj)} is not readable")
    elif isinstance(fileobj, bool):
        if not fileobj_readable:
            raise ValueError(f"file {repr(fileobj)} is not readable")
    else:
        result = fileobj.read(0)
        if not isinstance(result, target_type):
            raise ValueError(
                f"incorrect type from file {repr(fileobj)} "
                f"(should be {target_type.__name__}, got {type(fileobj).__name__})"
            )


def verify_writable(fileobj, is_binary=True):
    verify_fileobj(fileobj)
    target_type = str
    if is_binary:
        target_type = bytes

    fileobj_writable = getattr(fileobj, 'writable', None)
    if callable(fileobj_writable):
        if not fileobj_writable():
            raise ValueError(f"file {repr(fileobj)} is not writable")
    elif isinstance(fileobj, bool):
        if not fileobj_writable:
            raise ValueError(f"file {repr(fileobj)} is not writable")
    else:
        fileobj.write(target_type())


def verify_seekable(fileobj):
    verify_fileobj(fileobj)

    fileobj_seekable = getattr(fileobj, 'seekable', None)
    if callable(fileobj_seekable):
        if not fileobj_seekable():
            raise ValueError(f"file {repr(fileobj)} is not seekable")
    elif isinstance(fileobj, bool):
        if not fileobj_seekable:
            raise ValueError(f"file {repr(fileobj)} is not seekable")
    else:
        fileobj.seek(0, 1)
```

`utils.pyi`:
```python
from typing import IO, Iterable, SupportsBytes, SupportsIndex


def bytesxor(
        term1: SupportsBytes | Iterable[SupportsIndex],
        term2: SupportsBytes | Iterable[SupportsIndex]
) -> bytes:
    ...


def normally_return(obj: object) -> object:
    ...


def string_modify(s: str) -> str:
    ...


def verify_fileobj(obj: object) -> None:
    ...


def verify_readable(fileobj: IO, is_binaryio: bool = True) -> None:
    ...


def verify_writable(fileobj: IO, is_binaryio: bool = True) -> None:
    ...


def verify_seekable(fileobj: IO) -> None:
    ...
```
And the project files: [test-project.zip](https://github.com/microsoft/pylance-release/files/8521510/test-project.zip)

**Comment by heejaechang** [comment]
@nukemiko you get Unknown in verify_readable because you put IO which is generic type without type argument. 
ex) ```def verify_readable(fileobj: IO[str], is_binaryio: bool = ...) -> None:```

also, the reason you get unknown from utils.py is because it doesn't have type annotation. we don't merge type info even if you have pyi file for associated py file. 
ex) utils.pyi type info won't be merged to utils.py.

the type info in utils.pyi will be used when symbols in utils are used in other file.
ex) foo.py using utils by "import utils"

if you want the effect of merging, best way is just inlining type annotation in utils.py rather than having separate pyi file.

thank you
