### ISSUE TITLE
Remove unused imports on Organize Imports

### ISSUE THREAD

**Issue by hmoravec** [microsoft/pylance-release#268]
When running Organize Imports, I would expect that the imports will be not only sorted but also all unused imports will be removed.
[Organize Imports](https://code.visualstudio.com/Docs/languages/javascript#_organize-imports) for JavaScript in VS Code does the same. [Optimize Imports](https://www.jetbrains.com/help/pycharm/creating-and-optimizing-imports.html#optimize-imports-in-project) in PyCharm is also doing the same.

**Comment by zillionare** [comment]
Any progress on this? It's very convenient if organizeImports can remove unused imports, otherwise, a lot of warngins will be reported by lint tools.

**Comment by hmoravec** [comment]
I solved it by adding `autoflake` and `isort` as pre-commit hooks. `autoflake` can remove unused imports in-place using options `--in-place --remove-all-unused-imports`. I use also option `--ignore-init-module-imports` so unused imports in init modules are not removed.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
