### ISSUE TITLE
Got false error about object is not callable.

### ISSUE THREAD

**Issue by cebor** [microsoft/pylance-release#269]
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: macOS 10.15
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8 (venv)

## Expected behaviour

No error is been shown.

## Actual behaviour

Shows following false error: "PostProcessor(t)" has type "PostProcessor" and is not callable

Code to reproduce issue:
```python
from testa.tooling.post_processing import PostProcessor

class Main(testa.StdMain):
    def run(self):
        with PostProcessor(t) as p:
            p.run()
```

post_processing/\_\_init\_\_.py
```python
from .PostProcessor_Special import * # maybe this '*' import causes the issue, direct import works

PostProcessor=PostProcessor_Special
```

post_processing/PostProcessor_Special.py
```python
class PostProcessor_Special:
    def __init__(self, t, issue=None):
        self.org_t = t
        self.issue = issue
```

With language server set to jedi, all works fine.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202083-28-august-2020
