### ISSUE TITLE
Pylance does not work properly

### ISSUE THREAD

**Issue by EduardoBaroni** [microsoft/pylance-release#2723]
Issue Type: <b>Bug</b>

Some Pylance features are not working when I am coding: 
- As-you-type reporting of code errors and warnings
- Type checking mode

For instance, the variables that have to be in blue color (vs code default dark+ theme)
are just in white color, and the libraries that i've been importing are in white color as well.

Sometimes this features come back to life, and it works fine, but after a while they just stop again.

![image](https://user-images.githubusercontent.com/51293624/164541564-f69d3eb9-9dc0-45b9-ac5e-b7a74c10d52e.png)
The image above show an example that pylance just stop to work properly, when I add pandas to imports.

Extension version: 2022.4.1
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

I found a issue that is very similar:
https://github.com/microsoft/pylance-release/issues/1428

Log from Pylance language server:
[Info  - 8:11:37 AM] (2728) Pylance language server 2022.4.1 (pyright af32b7d8) starting
[Info  - 8:11:37 AM] (2728) Server root directory: c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist
[Info  - 8:11:37 AM] (2728) No configuration file found.
[Info  - 8:11:37 AM] (2728) No pyproject.toml file found.
[Info  - 8:11:37 AM] (2728) Setting pythonPath for service "aida": "c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\Scripts\python.exe"
[Warn  - 8:11:37 AM] (2728) stubPath c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\typings is not a valid directory.
[Info  - 8:11:37 AM] (2728) Assuming Python version 3.9
[Info  - 8:11:37 AM] (2728) Assuming Python platform Windows
[Info  - 8:11:38 AM] (2728) Searching for source files
[Info  - 8:11:38 AM] (2728) Found 288 source files
[Info  - 8:11:38 AM] (2728) Background analysis(1) root directory: c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist
[Info  - 8:11:38 AM] (2728) Background analysis(1) started
[Info  - 8:11:39 AM] (2728) Indexer background runner(2) root directory: c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist (index)
[Info  - 8:11:39 AM] (2728) Indexing(2) started
[Info  - 8:11:44 AM] (2728) [IDX(2)] Long operation: index execution environment c:\Users\baron\OneDrive\Documentos\AI Solutions\aida (3700ms)
[Info  - 8:11:44 AM] (2728) [IDX(2)] Long operation: index libraries c:\Users\baron\OneDrive\Documentos\AI Solutions\aida (5084ms)
[Info  - 8:11:44 AM] (2728) Indexer done(2). indexed 470 files
[Info  - 8:12:17 AM] (2728) Searching for source files
[Info  - 8:12:17 AM] (2728) Found 288 source files
[Info  - 8:21:06 AM] (2728) Searching for source files
[Info  - 8:21:06 AM] (2728) Found 288 source files
[Info  - 9:17:25 AM] (2728) No configuration file found.
[Info  - 9:17:25 AM] (2728) No pyproject.toml file found.
[Info  - 9:17:25 AM] (2728) Setting pythonPath for service "aida": "c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\Scripts\python.exe"
[Warn  - 9:17:25 AM] (2728) stubPath c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\typings is not a valid directory.
[Info  - 9:17:25 AM] (2728) Assuming Python version 3.9
[Info  - 9:17:25 AM] (2728) Assuming Python platform Windows
[Info  - 9:17:25 AM] (2728) Search paths for c:\Users\baron\OneDrive\Documentos\AI Solutions\aida
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist\typeshed-fallback\stdlib
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\typings
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist\typeshed-fallback\stubs\...
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist\bundled\stubs
[Info  - 9:17:26 AM] (2728)   c:\Python39\DLLs
[Info  - 9:17:26 AM] (2728)   c:\Python39\Lib
[Info  - 9:17:26 AM] (2728)   c:\Python39
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv
[Info  - 9:17:26 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\Lib\site-packages
[Info  - 9:17:26 AM] (2728) Adding fs watcher for library directories:
 C:\Python39\DLLs
C:\Python39\lib
C:\Python39
c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv
c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\lib\site-packages
[Info  - 9:17:26 AM] (2728) Adding fs watcher for directories:
 c:\Users\baron\OneDrive\Documentos\AI Solutions\aida
[Info  - 9:17:26 AM] (2728) Searching for source files
[Info  - 9:17:26 AM] (2728) Found 288 source files
[Info  - 9:17:26 AM] (2728) SourceFile: Received fs event 'change' for path 'c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.vscode\settings.json'
[Info  - 9:17:26 AM] (2728) SourceFile: Received fs event 'change' for path 'c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.vscode\settings.json'
[Info  - 9:17:26 AM] (2728) SourceFile: Received fs event 'change' for path 'c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.vscode\settings.json'
(2728) Received updated settings
[Info  - 9:17:33 AM] (2728) No configuration file found.
[Info  - 9:17:33 AM] (2728) No pyproject.toml file found.
[Info  - 9:17:33 AM] (2728) Setting pythonPath for service "aida": "c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\Scripts\python.exe"
[Warn  - 9:17:33 AM] (2728) stubPath c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\typings is not a valid directory.
[Info  - 9:17:33 AM] (2728) Assuming Python version 3.9
[Info  - 9:17:33 AM] (2728) Assuming Python platform Windows
[Info  - 9:17:33 AM] (2728) Search paths for c:\Users\baron\OneDrive\Documentos\AI Solutions\aida
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist\typeshed-fallback\stdlib
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\typings
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist\typeshed-fallback\stubs\...
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\.vscode\extensions\ms-python.vscode-pylance-2022.4.1\dist\bundled\stubs
[Info  - 9:17:33 AM] (2728)   c:\Python39\DLLs
[Info  - 9:17:33 AM] (2728)   c:\Python39\Lib
[Info  - 9:17:33 AM] (2728)   c:\Python39
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv
[Info  - 9:17:33 AM] (2728)   c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\Lib\site-packages
[Info  - 9:17:33 AM] (2728) Adding fs watcher for library directories:
 C:\Python39\DLLs
C:\Python39\lib
C:\Python39
c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv
c:\Users\baron\OneDrive\Documentos\AI Solutions\aida\.venv\lib\site-packages
[Info  - 9:17:33 AM] (2728) Adding fs watcher for directories:
 c:\Users\baron\OneDrive\Documentos\AI Solutions\aida
[Info  - 9:17:33 AM] (2728) Searching for source files
[Info  - 9:17:33 AM] (2728) Found 288 source files

I am using a virtual environment, with the requirements.txt below:
[requirements.txt](https://github.com/microsoft/pylance-release/files/8555008/requirements.txt)

Code example:
![image](https://user-images.githubusercontent.com/51293624/165101225-67f8bb5b-7449-464c-9106-dff6298a4d41.png)

The image above show that we have no checking for erros and no type checking mode, this features just dont work. when I add a purposeful error, such as the absence of a ':' in line 32, no erros are detected.
![image](https://user-images.githubusercontent.com/51293624/165102082-b00ee517-2875-4d9e-bc87-6ea8525f4354.png)

I realize that sometimes all pylance features are working fine, but when I open other file to edit, pylance just stop.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.86GB (13.90GB free)|
|Process Argv|--crash-reporter-id 72b97042-4f75-4f7a-a252-afa8ca1119f8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by judej** [comment]
@EduardoBaroni, thanks for the report. I would like to get the bottom of this. Unfortunately, this is not enough data for us to debug. 

Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by bschnurr** [comment]
is there a public repo to view the code? or small example that reproduces the problem?

**Comment by thekaveman** [comment]
I'm having basically the exact same problem outlined by @EduardoBaroni, running a Django app in a VS Code devcontainer environment. I left some comments on #2529 because I also experience that issue and they seem to be, tangentially related?

As of recently (the last few weeks at least), I almost never get Pylance highlighting, type checking, etc.

Links:

* Public repo: https://github.com/cal-itp/benefits
* [devcontainer.json](https://github.com/cal-itp/benefits/blob/dev/.devcontainer/devcontainer.json#L37)
* [settings.json](https://github.com/cal-itp/benefits/blob/dev/.vscode/settings.json#L27)

VS Code / runtime info: 

```
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
Language Server version: v2022.5.2 (experienced with v2022.4.1 as well)
Python version (& distribution if applicable, e.g. Anaconda): python:3.9-slim (Debian GNU/Linux 11) installed via Docker
```

Recent Language Server output:

```console
[Info  - 12:55:52 AM] (56529) Pylance language server 2022.5.2 (pyright 0577bc22) starting
[Info  - 12:55:52 AM] (56529) Server root directory: /home/calitp/.vscode-server/extensions/ms-python.vscode-pylance-2022.5.2/dist
[Info  - 12:55:52 AM] (56529) No configuration file found.
[Info  - 12:55:52 AM] (56529) pyproject.toml file found at /home/calitp/app.
[Info  - 12:55:52 AM] (56529) Setting pythonPath for service "app": "/usr/local/bin/python"
[Info  - 12:55:52 AM] (56529) Loading pyproject.toml file at /home/calitp/app/pyproject.toml
[Error - 12:55:52 AM] (56529) Pyproject file "/home/calitp/app/pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 12:55:52 AM] (56529) stubPath /home/calitp/app/typings is not a valid directory.
[Info  - 12:55:52 AM] (56529) Assuming Python version 3.9
[Info  - 12:55:52 AM] (56529) Assuming Python platform Linux
[Info  - 12:55:53 AM] (56529) Searching for source files
[Info  - 12:55:53 AM] (56529) Found 47 source files
[Info  - 12:55:53 AM] (56529) Background analysis(1) root directory: /home/calitp/.vscode-server/extensions/ms-python.vscode-pylance-2022.5.2/dist
[Info  - 12:55:53 AM] (56529) Background analysis(1) started
[Info  - 12:56:06 AM] (56529) Indexer background runner(2) root directory: /home/calitp/.vscode-server/extensions/ms-python.vscode-pylance-2022.5.2/dist (index)
[Info  - 12:56:06 AM] (56529) Indexing(2) started
[Info  - 12:56:09 AM] (56529) [IDX(2)] Long operation: index libraries /home/calitp/app (2404ms)
[Info  - 12:56:09 AM] (56529) Indexer done(2). indexed 475 files
```

Example in VS Code devcontainer:

* *Loading...* instead of `os` docstrings - this never "loads"
* Lack of highlighting on `os` module/functions

![image](https://user-images.githubusercontent.com/1783439/170155826-9fa0b459-bc21-4402-b3f8-eab1f851bfcc.png)
