### ISSUE TITLE
reopened issue

### ISSUE THREAD

**Issue by Ak22735** [microsoft/pylance-release#2727]
![image](https://user-images.githubusercontent.com/89251923/164601989-bdad4c14-7a2e-4c2a-a24f-882a21754f21.png)
help!!

**Comment by heejaechang** [comment]
@Ak22735 can you provide repro steps we can follow to reproduce the issue? also, fill in information described here - https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

that being said, did you select right environment where the package is installed?
![image](https://user-images.githubusercontent.com/1333179/164769217-7e6ed79a-0a04-4130-b15e-c5cacc8a6410.png)

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
