### ISSUE TITLE
Auto imports causing excessive CPU and bad perf

### ISSUE THREAD

**Issue by gramster** [microsoft/pylance-release#2730]
Reported by user on Twitter; see https://twitter.com/alexdreptu/status/1517573258685657092

## Environment data

To find your version, you can either:

- Open the VS Code extensions panel. Locate Pylance from the list of installed extensions. The version appears next to the name.

- Select "View: Toggle Output" from the command palette (Ctrl+Shift+P on Windows/Linux, Command+Shift+P on macOS), then select "Python Language Server" in the dropdown on the right. Look for the line Pylance Language Server version X in the console.

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Logs

Enable trace logging by adding "python.analysis.logLevel": "Trace" to your settings.json configuration file.

Adding this will cause a large amount of info to be printed to the Python output panel. This should not be left long term, as the performance impact of the logging is significant.

**Comment by heejaechang** [comment]
if user is not interested in using auto import, user might want to disable indexing as well to get even more perf

"python.analysis.indexing": false.

this will degrade "add import" code actions, and workspace symbol search perf as well, but if machine is having problem with auto import, those other features will probably have similar issue.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
