### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by mxcai08** [microsoft/pylance-release#2734]
## Environment data

-   Language Server version: 
-   OS and version: WSL2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.1 

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```
![屏幕截图 2022-04-23 215938](https://user-images.githubusercontent.com/35069239/164909151-d32c3762-e9e4-4a70-a301-b831427f5533.png)

**Comment by debonte** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to docs on virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.

**Comment by mxcai08** [comment]
> Thanks for the report. Would you please check if the right virtual environment is being used?
> 
> The way to do that would be to:
> 
> * If you have not selected a virtual environment, the status bar will show the global python interpreter.
> * Click on version number and choose the right environment from the command palette
> * If there is no environment offered, you will need to create an environment and then select that as the default environment
> * When you select the right virtual environment Pylance find the modules installed in that environment.
> 
> Here is a link to docs on virtual environments: https://code.visualstudio.com/docs/python/environments
> 
> Please reopen this issue if this does not solve the problem.

Thanks for your reply, I created a virtual environment using conda, I can import tensorflow modules correctly and this statement works correctly, I don't have similar problems when using pycharm in the same virtual environment

**Comment by bschnurr** [comment]
couldn't repo with non condo environment.

could be you are using an older version of tensorflow in your condo env.

what is the version of your tensorflow?

**Comment by rxy1212** [comment]
This problem is indeed exist. When I use tensorflow, pylance give me a same error, but my code works well.
![image](https://user-images.githubusercontent.com/14829556/168240297-027b50b2-d00b-4470-94e2-bc2d6f2e698b.png)

**Comment by rxy1212** [comment]
> * looks like a problem with the latest tensorflow version
> * tensorflow - 2.7.0
> 
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/3067668/168314687-2951a1d7-0aae-4740-a227-a6be918887d7.png">
> 
> * tensorflow - 2.8.0
> 
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/3067668/168314898-f6916f6f-377d-4c39-9ad0-f7b8d282eb81.png">

I think so, my code above is also with tf2.8

**Comment by petrenkonikita112263** [comment]
I have same issue in VS Version 17.2.2. I used Conda distro as Python, the enviroment base (is created by default) in Conda. 
Anaconda3 2022.05 Python 3.9.12.

![image](https://user-images.githubusercontent.com/56109799/170221975-e64c22da-3156-4549-894c-5e3b75b0f1b2.png)

**Comment by petrenkonikita112263** [comment]
Here is my local settings for VS

`
{
  "python.pythonPath": "C:\\Users\\Nikita\\anaconda3\\python.exe",
  "python.autoComplete.extraPaths": [ "C:\\Users\\Nikita\\anaconda3\\pkgs\\python-3.9.12-h6244533_0" ],
  "TestFramework": "Pytest",
  "Interpreter": "Global|ContinuumAnalytics|Anaconda39-64",
  "UnitTestRootDirectory": "tests",
  "UnitTestPattern": "test_*.py"
}
`

**Comment by rafattushar** [comment]
So, there is still no fix instead of downgrading to tensorflow=2.7.

**Comment by bschnurr** [comment]
works with  tensorflow-2.9.1

**Comment by bschnurr** [comment]
@rxy1212 

try
```python
from keras import applications
from keras.applications import resnet
```

**Comment by petrenkonikita112263** [comment]
@bschnurr 
what's your local(workshop) settings for Python?

**Comment by bschnurr** [comment]
i create a local virtual environment inside my workspace 

python -m venv .venv
.venv/scripts/activate
pip install tensorflow

i get a popup to set my .venv as my python interpreter 

no custom settings

**Comment by petrenkonikita112263** [comment]
with Anaconda the base env has already installed and activate, don't know why in PyCharm pytest import works, but same thing in VS didn't

**Comment by bschnurr** [comment]
what version of conda? what OS?

**Comment by bschnurr** [comment]
@petrenkonikita112263 
I think you're conda environment might not have pytest installed.

when creating a new venv make sure to add pytest 
![image](https://user-images.githubusercontent.com/1946977/170553979-b03541bf-8ce9-4a80-9543-63182f2359b1.png)

**Comment by petrenkonikita112263** [comment]
@bschnurr 

here's my [issue](https://github.com/microsoft/PTVS/issues/7018) on github

**Comment by samehraban** [comment]
> @rxy1212
> 
> try
> 
> ```python
> from keras import applications
> from keras.applications import resnet
> from keras import layers
> ```

This is discouraged in official docs. One should import keras from tensorflow.

**Comment by bschnurr** [comment]
Closing this issue. for Keras see https://github.com/microsoft/pylance-release/issues/1941#issuecomment-1022430663
