### ISSUE TITLE
Activating Pylance leading "Runing file renaming  participants forever" and a slowly speed on editing file names.

### ISSUE THREAD

**Issue by XinzeZhang** [microsoft/pylance-release#2737]
Issue Type: <b>Bug</b>

1. Activate the Pylance extension.
2. Moving or Renaming a file in the current workspace, then, the vscode shows: "Moving files" with a notification of "Runing file renaming participants".
3. After a long time, the process of moving file is done.

Extension version: 2022.4.2
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-7614-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv|--crash-reporter-id c1ed7ca7-8843-4737-b9d1-402801ab9633|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xinze.201|
|OS|Linux x64 5.11.0-7614-generic|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3800)|
|Memory (System)|62.79GB (37.92GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. Be aware, that rename a file can be an expensive process. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
