### ISSUE TITLE
error when class member name is same as type

### ISSUE THREAD

**Issue by beauxq** [microsoft/pylance-release#2738]
Pylance gets confused if the type of a class member is the same as the name of the class member.

```python3
from collections import deque


class D:
    deque: deque

    def __init__(self) -> None:
        self.deque = deque()
```

## Expected behavior

The type of the class member `deque` can be understood.

## Actual behavior

Pylance gets confused if the type of a class member is the same as the name of the class member.

It says:
` Type of "deque" could not be determined because it refers to itself`
and
`"deque" is unbound`
but it does not refer to itself, and is not unbound.

This is not specific to deque.
Another example:

```python3
class Xyz:
    def __repr__(self) -> str:
        return "Xyz instance"


class C:
    Xyz: Xyz

    def __init__(self) -> None:
        self.Xyz = Xyz()


c = C()
print(c.Xyz)
```

## Environment data

-   Language Server version: Pylance language server 2022.4.2 (pyright 90161194)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.5

**Comment by erictraut** [comment]
This behavior is correct and intended. Type declarations use the scope in which they are referenced. In this case, the scope declares the symbol `deque`, and the type annotation refers to that symbol.

The proper workaround in this case is to use an alias:

```python
from collections import deque as _deque

class D:
    deque: _deque

    def __init__(self) -> None:
        self.deque = _deque()
```

Alternatively, avoid naming a class variable the same as a type.

```python
from collections import deque

class D:
    items: deque

    def __init__(self) -> None:
        self.items = deque()
```

**Comment by beauxq** [comment]
The type is not referenced in that scope. In order to reference something in that scope, it would have to be `D.deque`.

Consider this example:
```python3
class E:
    ab: int
    cd: int = ab
```
The second `ab` is not referencing anything declared in the same scope as the first `ab`.

The type is not in the same scope as the class member declaration.

**Comment by beauxq** [comment]
Note that in this program:
```python3
ab = 1


class E:
    ab: int
    cd: int = ab


e = E()
print(e.cd)
```
Pylance incorrectly says `ab` is unbound, when it clearly isn't, and this program prints `1` with no error.

`ab` references something from a different scope.

**Comment by judej** [comment]
The behavior is by design.
