### ISSUE TITLE
Auto Import Bug

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#274]
![image](https://user-images.githubusercontent.com/26390254/90960455-e24b7c00-e4b6-11ea-84b0-834347d8059c.png)

there is not `Add import time` in list.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
