### ISSUE TITLE
Are you planning to integrate this extension into Python?

### ISSUE THREAD

**Issue by ZhuangQu** [microsoft/pylance-release#2746]
In the vs code extension marketplace, there are two extensions, `pylance` and `python`, both officially released by `Microsoft`. After installing `python`, vs code recommends installing `pylance` next. The official description says that these two extensions should be used together. If so, why not merge them into one extension?

**Comment by judej** [comment]
It is now installed together. You can uninstall it if you want.

If you are having an issue with it, please reopen this issue.
