### ISSUE TITLE
Corrupt ZIP: end of central directory record signature not found

### ISSUE THREAD

**Issue by mursalatul** [microsoft/pylance-release#2747]
## Environment data

-   Language Server version: XXX
-   OS and version: Windows 10Pro 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.4

## Expected behavior

It should be installed as usual.

## Actual behavior

But **it is not installing. Its just waiting and after a long time its saying to install manually. When i am trying to install it with cmd its saying  "Corrupt ZIP: end of central directory record signature not found".**

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
Are you trying to install Pylance separately from the Python extension? 

Could you please try uninstalling the Python extension and reinstalling?
