### ISSUE TITLE
type hinting fails on r:Optional[requests.Response]=None

### ISSUE THREAD

**Issue by fenchu** [microsoft/pylance-release#2751]
## Environment data

-   Language Server version: v2022.4.3
-   OS and version: windows11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4

## Expected behavior
```
r:Optional[requests.Response] = None
if r.status_code not in [201,409,401,403,406,409]:

no error because Optional support None or requests.Response types
```

## Actual behavior

"status_code" is not a known member of "None"Pylance[reportOptionalMemberAccess](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

if I write
```
r:requests.Response = None
```
it says:
Expression of type "None" cannot be assigned to declared type "Response"
  Type "None" cannot be assigned to type "Response"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

it is the same with:
```
r:Union[requests.Request,None] = None
if r.status_code not in [201,409,401,403,406,409]:

"status_code" is not a known member of "None"Pylance[reportOptionalMemberAccess](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

**Comment by erictraut** [comment]
Your code sample is incomplete, but I presume you meant something like this:
```python
from typing import Optional
import requests

r: Optional[requests.Response] = None
if r.status_code not in [201, 409, 401, 403, 406, 409]:
    pass
```

If you run that code in the Python interpreter, it produces the runtime exception `AttributeError: 'NoneType' object has no attribute 'status_code'`. Pylance is indicating that you have a bug in your code that needs to be fixed to avoid this runtime exception.

If you are not interested in seeing these type checking errors, set the "typeCheckingMode" setting back to its default value of "off". I presume that you have set "typeCheckingMode" to "basic", which enables checks like this one.

**Comment by erictraut** [comment]
If you would like to understand more about static type checking in Python, you may find [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md) useful.

**Comment by fenchu** [comment]
Sorry, I've probed more and it seems to be a problem with scooping, it was not a fully example:

This fails:
```
#!/usr/bin/env python3
import requests
from typing import Optional

s:Optional[requests.Session] = None
s = requests.session()
r:Optional[requests.Response] = None
try:
    r = s.get("https://www.nrk.no/serum/api/time/")
except Exception:
    pass
if r.status_code not in [201,409,401,403,406,409]:
    print(r.status_code)
    print(r.text)
```
the status_code and text are underlined and give the error:
"status_code" is not a known member of "None"Pylance[reportOptionalMemberAccess](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

this is all fine:
```
#!/usr/bin/env python3
import requests
from typing import Optional

s:Optional[requests.Session] = None
s = requests.session()
r:Optional[requests.Response] = None
r = s.get("https://www.nrk.no/serum/api/time/")
if r.status_code not in [201,409,401,403,406,409]:
    print(r.status_code)
    print(r.text)
```

**Comment by erictraut** [comment]
Yes, pylance is pointing out that you have a bug in this code. If the call to `s.get` generates an exception, then `r` will contain `None`, and your program will crash when it attempts to access `r.status_code`.

**Comment by fenchu** [comment]
Thanks Eric for pointing out, now I get it, it looks at the entire program-flow not only the variables.
Really powerful. 

Sorry for wasting your time.


Now it was easy to find workarounds:
```
#!/usr/bin/env python3
import requests, sys
from typing import Optional

s:Optional[requests.Session] = None
s = requests.session()
r:Optional[requests.Response] = None
try:
    r = s.get("https://www.nrk.no/serum/api/time/")
except Exception:
    sys.exit(1)
if r.status_code not in [201,409,401,403,406,409]:
    print(r.status_code)
    print(r.text)
```
or 
```
#!/usr/bin/env python3
import requests
from typing import Optional

s:Optional[requests.Session] = None
s = requests.session()
r:Optional[requests.Response] = None
try:
    r = s.get("https://www.nrk.no/serum/api/time/")
except Exception:
    pass
if r and r.status_code not in [201,409,401,403,406,409]:
    print(r.status_code)
    print(r.text)
```
