### ISSUE TITLE
goto definition actually open pyi file instead of the actual py file

### ISSUE THREAD

**Issue by copdips** [microsoft/pylance-release#2754]
## Environment data

-   Language Server version: 2022.4.3
-   OS and version: Ubuntu 20.04.3 LTS inside of Windows WSL
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Expected behavior

I've already seen many similar closed issues, but the bug persists still.

it should open the py file where the member (for instance `startswith` of `str`) is actually defined, when use goto definition. Only open pyi file when use goto declaration

## Actual behavior

when the package contain stub files (*.pyi), the goto definition open the pyi file instead of the actual py file.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
# F12 over startswith opens the .pyi file only, there's even no second choice for the .py file
# whether go to definition or go to declaration, both goes to the .pyi file.
s = "abc"
s.startswith("a")
```

**Comment by bschnurr** [comment]
I believe `startswith` if from a compiled module. there is .py file defining it so as a fallback we go to .pyi in this case.
