### ISSUE TITLE
Unreachable code for common django exception

### ISSUE THREAD

**Issue by Tobeyforce** [microsoft/pylance-release#2770]
Python 3.8, Ubuntu 20.04, VScode 1.63.2

I'm getting unreachable code for the second block in this piece of code:

```
        try:
            content_type = ContentType.objects.get(app_label=app_label, model=model)
            page_preview = PagePreview.objects.get(content_type=content_type, token=self.request.GET["token"] + "shdhsa")
        
        except ContentType.DoesNotExist:
            raise ValidationError({"content_type": "Invalid value"})

        except PagePreview.DoesNotExist:
            # THIS BLOCK IS UNREACHABLE ACCORDING TO PYLANCE
            raise ValidationError({"preview": "Preview does not exist for this token and content_type combination"})
```

These two are exceptions from Django, as documented here:
https://docs.djangoproject.com/en/4.0/ref/exceptions/
The ObjectDoesNotExist one

Any idea how to fix this? I'm thinking it has something to do with both exceptions inheriting from the same base?

**Comment by Archivec** [comment]
I'm facing the same issue. I would think that the purpose of `Model.DoesNotExist` over `ObjectDoesNotExist` is for situation like this with multiple exception block. If this is the intended usage then it may just be Pylance identifying those two exceptions as the same.

**Comment by erictraut** [comment]
@Archivec, if you're seeing a similar issue, perhaps you could post a self-contained minimal code sample? I'd like to investigate this, but I need a repro. The above code sample doesn't contain sufficient context.

**Comment by Tobeyforce** [comment]
I'm swamped at work but here's a guide on how you would reproduce it:

1. Create a vanilla django project, e.g 4.0.4 (pip install django==4.0.4)
2. Define two separate models, it doesn't matter what they do.
`
from django.db imports models

# First model:
models.py:
```
class Car(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)

class Motorcycle(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)

```
test.py:
3. Create a simple function with a try catch block. I don't think you need to run the server or make any migrations for the models.
```
from .models import Car, Motorcycle

def test_func():
        try:
            car_instance = Car.objects.get(name="toyota")
            motorcycle_instance = Motorcycle.objects.get(name="suzuki")
        
        except Car.DoesNotExist:
            raise ValidationError({"car": "Invalid value"})

        except PagePreview.DoesNotExist:
            # THIS BLOCK IS UNREACHABLE ACCORDING TO PYLANCE
            raise ValidationError({"motorcycle": "Invalid value"})
     return
```
Function above should trigger the warning from pylance in vscode.
Hope that is enough, if you need more info do let me know.

**Comment by erictraut** [comment]
Thanks, I'm able to repro with that sample.

I think pylance is correct in flagging that block as unreachable, no? The `DoesNotExist` class is the same in both cases, so the second except clause will never be executed.

If you enable basic type checking mode (set "python.analysis.typeCheckingMode" to "basic"), pylance will also emit an error explaining why this is a problem:
```
Except clause is unreachable because exception is already handled
  "DoesNotExist" is a subclass of "DoesNotExist"
```

**Comment by erictraut** [comment]
If I change the `Motorcycle` class to declare its own private version of the `DoesNotExist` class, then the error is eliminated. 

```python
class Motorcycle(models.Model):
    class DoesNotExist(ObjectDoesNotExist): ... # Create a private exception class
    name = models.CharField(max_length=255, null=True, blank=True)
```

But if both `Car` and `Motorcycle` share the same `DoesNotExist` class, then the second `except` clause will never be executed.

**Comment by Tobeyforce** [comment]
> Thanks, I'm able to repro with that sample.
> 
> I think pylance is correct in flagging that block as unreachable, no? The `DoesNotExist` class is the same in both cases, so the second except clause will never be executed.
> 
> If you enable basic type checking mode (set "python.analysis.typeCheckingMode" to "basic"), pylance will also emit an error explaining why this is a problem:
> 
> ```
> Except clause is unreachable because exception is already handled
>   "DoesNotExist" is a subclass of "DoesNotExist"
> ```

I'm fairly sure that I tried it multiple times and it did indeed reach the second block multiple times when the first one passed. Have you had time to run the code yet? Please test it and see if you can confirm this. I do distinctly remember seeing the greyed out block being executed. I'll give your solution a try as well, but generally we tend to not touch the built in exceptions to django.

**Comment by erictraut** [comment]
I've tried to run the code, but the sample isn't complete enough to run in isolation, and I don't know enough about django to initialize the library properly.

The type information for django comes from a type stub file. It's possible that the type stub is incorrectly modeling the actual behavior of the library. According to the type stub, there's a class called `DoesNotExist` in the `Model` class. This class is common to all `Model` subclasses. If each `Model` subclass is intended to have a separate private `DoesNotExist`, then the type stub would need to be modified to reflect this.

Based on the type information provided to pyright (the static type evaluator that underlies pylance), it is correct to assume that the second `except` clause is unreachable.

Let us know what you find when you try running the code. Depending on the results, we may need to contact the maintainers of the django stubs and report a bug.

**Comment by Tobeyforce** [comment]
> I've tried to run the code, but the sample isn't complete enough to run in isolation, and I don't know enough about django to initialize the library properly.
> 
> The type information for django comes from a type stub file. It's possible that the type stub is incorrectly modeling the actual behavior of the library. According to the type stub, there's a class called `DoesNotExist` in the `Model` class. This class is common to all `Model` subclasses. If each `Model` subclass is intended to have a separate private `DoesNotExist`, then the type stub would need to be modified to reflect this.
> 
> Based on the type information provided to pyright (the static type evaluator that underlies pylance), it is correct to assume that the second `except` clause is unreachable.
> 
> Let us know what you find when you try running the code. Depending on the results, we may need to contact the maintainers of the django stubs and report a bug.

Thanks for the thorough explanation, that's really interesting. Hopefully I can come back to this, because this is probably the most common exception used within Django, so I do think it deserves being looked into :)

**Comment by benspaulding** [comment]
I stumbled on this and looked into a bit. It must be the stub that is incorrect. I have also used the pattern and seen the behavior that @Tobeyforce has. [Every model has its own `DoesNotExist` exception that is a subclass of `ObjectDoesNotExist`](https://github.com/django/django/blob/3.2.13/django/db/models/base.py#L123-L132).

```py
class ModelBase(type):
    """Metaclass for all models."""
    def __new__(cls, name, bases, attrs, **kwargs):

        ...

        if not abstract:
            new_class.add_to_class(
                'DoesNotExist',
                subclass_exception(
                    'DoesNotExist',
                    tuple(
                        x.DoesNotExist for x in parents if hasattr(x, '_meta') and not x._meta.abstract
                    ) or (ObjectDoesNotExist,),
                    module,
                    attached_to=new_class))

        ...
```

**Comment by erictraut** [comment]
Yeah, that means it's a bug in the stub file `base.pyi`.

```python
class Model(metaclass=ModelBase):
    class DoesNotExist(ObjectDoesNotExist): ...
    class MultipleObjectsReturned(BaseMultipleObjectsReturned): ...
```

should be changed to

```python
class Model(metaclass=ModelBase):
    DoesNotExist: Type[ObjectDoesNotExist]
    MultipleObjectsReturned: Type[BaseMultipleObjectsReturned]
```

or if the members are not meant to be overridable:

```python
class Model(metaclass=ModelBase):
    DoesNotExist: Final[Type[ObjectDoesNotExist]]
    MultipleObjectsReturned: Final[Type[BaseMultipleObjectsReturned]]
```
