### ISSUE TITLE
Show Call Hierarchy doesn't handle overridden methods correctly

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#2774]
## Environment data
-   Language Server version: 2022.5.0-pre.1
-   OS and version: Windows 11
-   Python version: 3.11.0a7

## Repro steps

1. Paste the code below in a .py file
2. Right-click on `Derived.method` and select `Show Call Hierarchy`
3. Examine the generated call hierarchy
4. Right-click on `Base.method` and select `Show Call Hierarchy`
5. Examine the generated call hierarchy

## Expected behavior

Since "Find All References" considers the `method` calls in both `BaseConsumer` and `DerivedConsumer` to be references of both `Base.method` and `Derived.method`, I would expect both calls to appear in both call hierarchies.

## Actual behavior

Both call hierarchies contain a single call -- the call from `BaseConsumer`.

Additionally, in the call hierarchy for `Derived.method`, when I click on the root of the hierarchy, it takes me to `Base.method`, so perhaps that's a clue to what's going wrong.

## Code Snippet / Additional information

```python
import abc

class Base(abc.ABC):
    @abc.abstractmethod
    def method(self):
        pass


class Derived(Base):
    def method(self):
        pass


class BaseConsumer:
    def consumer(self, base: Base):
        base.method()


class DerivedConsumer:
    def consumer(self, derived: Derived):
        derived.method()
```

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.7.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023731-19-July-2023-PreRelease)
