### ISSUE TITLE
Dead code detection broken

### ISSUE THREAD

**Issue by cclamb** [microsoft/pylance-release#2777]
<h3> Environment data </h3>

-   Language Server version: 2022.4.3
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

    def __init__(self):

        gr.basic_block.__init__(
            self,
            name="data_association",
            in_sig=None,
            out_sig=None
        )

        self._msg_port_state_in = pmt.intern('state in')
        self.message_port_register_in(self._msg_port_state_in)
        self.set_msg_handler(self._msg_port_state_in, self.state_in)

The three lines after the superclass constructor are not marked as dead code.

<h3> Actual behaviour </h3>

    def __init__(self):

        gr.basic_block.__init__(
            self,
            name="data_association",
            in_sig=None,
            out_sig=None
        )

        self._msg_port_state_in = pmt.intern('state in')
        self.message_port_register_in(self._msg_port_state_in)
        self.set_msg_handler(self._msg_port_state_in, self.state_in)

The three lines after the superclass constructor *are* marked as dead code.

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by erictraut** [comment]
Could you provide a complete example? There's not enough here for us to repro the problem. For example, the symbols `gr` and `pmt` are not defined.

**Comment by cclamb** [comment]
Seems to be related to type hints. If I have a constructor with no type hint, code after the ctor seems to be indicated as unreachable. If I use a '-> None' hint, seems okay.

I'll see if I can get a better example up tonight.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
