### ISSUE TITLE
Multiline tuples don't fold

### ISSUE THREAD

**Issue by MJKirk** [microsoft/pylance-release#2779]
<h3> Environment data </h3>

-   Language Server version: 2022.4.3
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.10
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Multiline tuples will be fold-able, just like multiline lists.

<h3> Actual behaviour </h3>

They are not

<h3> Code Snippet / Additional information </h3>

```python
long_list = [
    1,
    2,
    3,
    4,
    5,
]

long_tuple = (
    1,
    2,
    3,
    4,
    5,
)
```
should be foldable to
```python
long_list = [...

long_tuple = (...
```
but only the list can be folded.

**Comment by debonte** [comment]
This issue has been fixed in version 2022.5.3, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202253-25-May-2022)
