### ISSUE TITLE
Go to Definition disabled when useLibraryCodeForTypes = false

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#278]
When `"useLibraryCodeForTypes": false` is set in *pyrightconfig.json* then "Go to Definition" is disabled for symbols without stubs. I was expecting this setting would only affect type checking, and "Go to Definition" would still work.

Language Server version: Pylance language server 2020.8.2 (pyright fbe2eb4d)

**Comment by jakebailey** [comment]
Do you mean within libraries? If that option is disabled, it's likely we're never touching the library files (and would need some extra mode to know to start analyzing them, maybe).

**Comment by tekumara** [comment]
Yes libraries in site-packages (as opposed my application's code).

**Comment by jakebailey** [comment]
Alright. I believe this is "intended" at the moment (the default is `true` in Pylance), and we'd have to figure out how this could be managed.

**Comment by tekumara** [comment]
Some context: I'm setting `"useLibraryCodeForTypes": false` so that I get the same type errors reported in pylance, as I do when pyright runs in CI/CD. With `"useLibraryCodeForTypes": true`, pylance reports a different set of type errors from pyright based on the additional inference it is doing. Would be great to have both autocompletion/definitions in pylance, and consistent type checking between pylance and pyright.

**Comment by erictraut** [comment]
I can't think of a feasible way to do this short of doing all type analysis twice — once for completion suggestions and a second time for type checking and error reporting. That would mean twice the computation, twice the memory, etc. And the hover text would no longer match that of the type checker. I don't think this would work.

**Comment by erictraut** [comment]
You could run the CLI version of pyright in a terminal window in "watch" mode so it's continuously watching for changes to the sources. This way, you would get the nice language service features in the editor, and you'd get error reporting consistent with your CI in the terminal window.

**Comment by judej** [comment]
closing old issue. Please reopen if necessary
