### ISSUE TITLE
"regression" is not defined Pylance

### ISSUE THREAD

**Issue by ml3z** [microsoft/pylance-release#2782]
Following line of code shows "regression" is not defined Pylance
plt.plot(X, regression.predict(X), color='red', linewidth=3)
Any workaround?

**Comment by erictraut** [comment]
We'll need more context to answer your question. Could you provide a complete code sample and explain which libraries (and versions) you're importing?

The symbol `regression` is not a builtin symbol in Python, so I presume you're importing it from somewhere?
