### ISSUE TITLE
Custom decorator creates classmethod, pylance reports first argument cls missing

### ISSUE THREAD

**Issue by MatteoRagni** [microsoft/pylance-release#2787]
<h3> Environment data </h3>

-   Language Server version: 2022.4.2
-   OS and version: linux x64 (Ubuntu 20.04 LTS)
-   Python version (and distribution if applicable, e.g. Anaconda): cpython 3.8
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

Writing a decorator that calls `classmethod` does not raises a `reportGeneralTypeIssue` for the missing argument `cls`.

<h3> Actual behaviour </h3>

Writing this kind of decorator (here you have a MRE example):
```py
from functools import wraps

def decorator(function):
    return classmethod(wraps(function)(function))

class Example:
    @decorator
    def class_method(cls):
        return cls

if __name__ == "__main__":
    assert Example.class_method() == Example # Pylance reports error: reportGeneralTypeIssue, missing one positional argument, cls
```
makes pylance raising the aforementioned error. I must use `# type: ignore` to disable it.

To be completely honest I'm not 100% sure if this shall raise the report or not... I'm not exactly an expert in decorator.
Anyway, the decorated class method does not fail the assert.

<h3> Logs </h3>

Python Language Server Log
```
(793593) Background analysis message: setFileClosed
(793593) Background analysis message: analyze
(793593) Background analysis message: setFileOpened
(793593) Background analysis message: getDiagnosticsForRange
(793593) Background analysis message: getDiagnosticsForRange
(793593) [FG] parsing: /tmp/minimal.py (0ms)
(793593) [FG] binding: /tmp/minimal.py (0ms)
(793593) Background analysis message: getSemanticTokens full
(793593) [BG(1)] getSemanticTokens full at /tmp/minimal.py ...
(793593) [BG(1)]   parsing: /tmp/minimal.py (1ms)
(793593) [BG(1)]   binding: /tmp/minimal.py (0ms)
(793593) [BG(1)] getSemanticTokens full at /tmp/minimal.py (2ms)
(793593) Background analysis message: getDiagnosticsForRange
(793593) Background analysis message: getDiagnosticsForRange
(793593) Background analysis message: analyze
(793593) [BG(1)] analyzing: /tmp/minimal.py ...
(793593) [BG(1)]   checking: /tmp/minimal.py (2ms)
[Info  - 3:04:07 PM] (793593) Heap stats: total_heap_size=71MB, used_heap_size=53MB, total_physical_size=68MB, total_available_size=4041MB, heap_size_limit=4096MB
(793593) [BG(1)] analyzing: /tmp/minimal.py (2ms)
(793593) Background analysis message: resumeAnalysis
(793593) Background analysis message: getDiagnosticsForRange
(793593) Background analysis message: getDiagnosticsForRange
```

<h3> Code Snippet / Additional information </h3>

Squiggles in editor:
![image](https://user-images.githubusercontent.com/4260219/167417259-0c57ef8f-666c-4b11-a021-e1ed2e93350c.png)

Report box
![image](https://user-images.githubusercontent.com/4260219/167417164-f68ef99c-dda0-4874-af6d-91d9469fb944.png)

**Comment by erictraut** [comment]
Type checkers need to do special processing for `classmethod`, so the `classmethod` decorator must be applied within the class itself, not as part of another method. 

If you would like this to work with type checkers, here's how to do it:
```python
def decorator(function):
    return wraps(function)(function)

class Example:
    @classmethod
    @decorator
    def class_method(cls):
        return cls
```
