### ISSUE TITLE
Auto-import should sort suggestions better

### ISSUE THREAD

**Issue by nip3o** [microsoft/pylance-release#279]
This is an example of an auto import suggestion from a Django project with a model called `WorkPeriod`. In this case we have an exact match (the correct import in this case), but it ends up really far down in the list. Naturally there are quite a few other things in the project that contains the name of that model, and it's probably reasonable to include all or most of them in the import suggestions, but the sorting should be improved.

Maybe there is also a difference between what import suggestions are relevant while typing, and what imports are relevant when "correcting squiggles". In this particular case I would find the non-exact-matches useful while typing/intellisense, but not while showing quick fixes.

![image](https://user-images.githubusercontent.com/1380307/91183141-65551800-e6eb-11ea-8720-ec0fdc7f12a0.png)

**Comment by jakebailey** [comment]
We're currently reworking this, but showing exact matches at the top sounds reasonable.

**Comment by heejaechang** [comment]
this is a dup of https://github.com/microsoft/pylance-release/issues/297

tracking issue on the other issue.
