### ISSUE TITLE
Extra modules appended in sys.path are not recogonised by pylint, but work in python.

### ISSUE THREAD

**Issue by maasir554** [microsoft/pylance-release#2790]
## Environment data

-   Language Server version: Python 3.10.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.1

## Expected behavior

the modules present in append paths of sys should be recognized, and colored as other modules

## Actual behavior
The module remains unrecognized and linted by yellow color

## Example Code

```
import sys
import os
MyCustomModuleDirectory = os.path.abspath("../python_project/custom__modules/")
sys.path.append(MyCustomModuleDirectory)

import customModule1 
```
(customModule1 is present in the custom_modules folder)

this module will recognized by python but not vscode / pylance

![image](https://user-images.githubusercontent.com/96122569/167519815-1d2d63d3-1910-4d84-9053-d77ba2bbcba7.png)

**Comment by maasir554** [comment]
module import in exception handling not recognized by pylint , but working fine in python, as well as when imported withour exception handling.
![image](https://user-images.githubusercontent.com/96122569/167644787-4ee3241c-ea56-4103-9571-6c61cc48c586.png)

![image](https://user-images.githubusercontent.com/96122569/167645181-ff39a67d-fad9-4cea-9519-91e37e02ec8a.png)

I don't know if its issue of pylance or vscode but yes, its a small issue.

**Comment by judej** [comment]
Thanks for the report. In order for Pylance to recognize the additional path that you have dynamically added to `sys.path`, you will need to add it to `python.analysis.extrapaths` in the settings.json

**Comment by martin-blostein-innovasea** [comment]
Just a note: the setting is `python.analysis.extraPaths`, not `python.analysis.extrapaths` (capital P)
