### ISSUE TITLE
vscode.dev - 'Pylance: Report Issue...' command shows error

### ISSUE THREAD

**Issue by egamma** [microsoft/pylance-release#2791]
I ran into an issue (#19107) with the python extension using vscode.dev and tried to report the issue following the instructions https://github.com/microsoft/vscode-python/wiki/Reporting-a-bug.

@brettcannon the page mentions to use `Python: Report Issue...` which is not available in vscode.dev. Therefore I've tried `Pylance: Report Issue...` . 

To reproduce
- install the Python extension in vscode.dev
- navigate to vscode.dev, e.g. https://vscode.dev/github/python/cpython/pull/92556
- 'Pylance: Report Issue'

The following error shows up:
![image](https://user-images.githubusercontent.com/172399/167564222-3199f3de-f5ae-4b6e-8e57-92ee61c55e6b.png)

**Comment by egamma** [comment]
@karthiknadig 

>@egamma For the web we provide a link see here: https://github.com/microsoft/vscode-python/wiki/Reporting-a-bug#web

sry I've overlooked that. I suggest to include this link inline in the little program on top of the reporting a bug wiki page
![image](https://user-images.githubusercontent.com/172399/167851527-5da0aca4-1b4d-46ae-9108-82d38d826b4c.png)

Obviously the command `Pylance: Report Issue...` should still not fail in vscode.dev/github.dev 😄 .

**Comment by debonte** [comment]
@luabud it turns out that this isn't a browser-specific issue. It works fine in both browser and desktop if the vscode-pylance extension has activated, but fails in both if it has not.

**Comment by debonte** [comment]
I think I found the answer on https://code.visualstudio.com/api/extension-guides/command#creating-a-user-facing-command:

> We still need to call registerCommand to actually tie the command ID to the handler. This means that if the user selects the myExtension.sayHello command from the Command Palette but our extension has not been activated yet, nothing will happen. To prevent this, extensions must register an onCommand activationEvent for all user facing commands:

> {
  "activationEvents": ["onCommand:myExtension.sayHello"]
}

> Now when a user first invokes the myExtension.sayHello command from the Command Palette or through a keybinding, the extension will be activated and registerCommand will bind myExtension.sayHello to the proper handler.

**Comment by debonte** [comment]
This issue has been fixed in version 2022.5.3, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202253-25-May-2022)
