### ISSUE TITLE
vscode.dev - Error connecting to language server when viewing a python file

### ISSUE THREAD

**Issue by egamma** [microsoft/pylance-release#2792]
When viewing a Python file from a PR an error shows up that the server connection is erroring.

To reproduce:
- navigate to https://vscode.dev/github/python/cpython/pull/92556
- an error notification shows up 
![image](https://user-images.githubusercontent.com/172399/167565984-7ec151bd-9ea1-4f28-b12a-efd60dbfd785.png)
- the output channel shows
```
[Error - 08:50:49] Client Python Language Server: connection to server is erroring. Shutting down server.
[Error - 08:50:49] Client Python Language Server: connection to server is erroring. Shutting down server.
```

**Comment by karthiknadig** [comment]
@heejaechang Is this the same one that is addressed by the race condition fix (https://github.com/microsoft/vscode-python/pull/19076)?

/cc @luabud

**Comment by karthiknadig** [comment]
@kieferrm We don't trigger on markdown files, do you happen to have one of these potential trigger files:
https://github.com/microsoft/vscode-python/blob/52c100bd28a1668aaf7194678f0430bebde32843/package.json#L63-L98
