### ISSUE TITLE
language server crash on azure-mgmt-network install

### ISSUE THREAD

**Issue by prawalgangwar** [microsoft/pylance-release#2798]
## Environment data

-   Language Server version: v2022.4.3
-   OS and version: 
```
Version: 1.67.1 (system setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4

## Expected behavior

language server and intellisense should continue to run 

## Actual behavior

intellisense stopped working and upon investigation in the language server logs it seemed to have crashed

## Logs

These are the new logs I see just after the `pip3 install azure-mgmt-network`
```
[Info  - 12:24:33 PM] (4436) Found 102 source files
[Info  - 12:24:51 PM] (4436) [BG(1)] Long operation: parsing: XXX/dev_env/lib/python3.10/site-packages/azure/mgmt/network/v2019_12_01/operations/_operations.py (2541ms)
[Info  - 12:24:56 PM] (4436) [BG(1)] Long operation: parsing: XXX/dev_env/lib/python3.10/site-packages/azure/mgmt/network/v2020_04_01/operations/_operations.py (4044ms)
[Info  - 12:25:04 PM] (4436) [BG(1)] Long operation: parsing: XXX/dev_env/lib/python3.10/site-packages/azure/mgmt/network/v2020_05_01/operations/_operations.py (7680ms)
[Error - 12:25:21 PM] (4436) Error occurred on background thread: {"code":"ERR_WORKER_OUT_OF_MEMORY"}
```

## Code Snippet / Additional information
Working on a venv hosted on WSL2 Ubuntu20.04

```sh
pip3 install azure-mgmt-network
```

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
