### ISSUE TITLE
Auto-import doesn't work

### ISSUE THREAD

**Issue by imankulov** [microsoft/pylance-release#28]
## Environment data

-   Language Server version: 2020.6.1
-   OS and version: macOS Mojave 10.14.6
-   Python version: 3.8.2, installed via pyenv.

## Expected behaviour

As demonstrated in the in [Pylance announcement](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/), I want to be able to automatically import packages as I type.

- I type "gc" and make a short pause
- VSCode shows the tooltip, inviting me to import gc
- I choose the library from the popup window
- VSCode adds an import to the top of the file

## Actual behaviour

- I type "gc" and make a pause
- Nothing happens

## Logs

<details><summary>Logs output</summary>

```
[Info  - 11:15:42 AM] Pylance language server 2020.6.1 starting
[Info  - 11:15:42 AM] Server root directory: /Users/roman/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 11:15:42 AM] No configuration file found.
[Info  - 11:15:42 AM] Setting pythonPath for service "vscode-playground": "/Users/roman/workspace/vscode-playground/env/bin/python3"
[Info  - 11:15:42 AM] stubPath /Users/roman/workspace/vscode-playground/typings is not a valid directory.
[Info  - 11:15:42 AM] Assuming Python version 3.8
[Info  - 11:15:42 AM] Assuming Python platform Darwin
[Info  - 11:15:42 AM] Searching for source files
[Info  - 11:15:42 AM] Auto-excluding /Users/roman/workspace/vscode-playground/env
[Info  - 11:15:42 AM] Found 1 source file
[FG] parsing: /Users/roman/workspace/vscode-playground/foo.py (7ms)
[FG] parsing: /Users/roman/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (245ms)
[FG] binding: /Users/roman/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (95ms)
[FG] binding: /Users/roman/workspace/vscode-playground/foo.py (0ms)
[Info  - 11:15:42 AM] Background analysis root directory: /Users/roman/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 11:15:42 AM] Background analysis started
[BG] analyzing: /Users/roman/workspace/vscode-playground/foo.py ...
[BG]   parsing: /Users/roman/workspace/vscode-playground/foo.py (41ms)
[BG]   parsing: /Users/roman/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (246ms)
[BG]   binding: /Users/roman/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (106ms)
[BG]   binding: /Users/roman/workspace/vscode-playground/foo.py (0ms)
[BG]   checking: /Users/roman/workspace/vscode-playground/foo.py (2ms)
[BG] analyzing: /Users/roman/workspace/vscode-playground/foo.py (396ms)
[FG] parsing: /Users/roman/workspace/vscode-playground/foo.py (3ms)
[FG] binding: /Users/roman/workspace/vscode-playground/foo.py (3ms)
[BG] analyzing: /Users/roman/workspace/vscode-playground/foo.py ...
[BG]   parsing: /Users/roman/workspace/vscode-playground/foo.py (2ms)
[BG]   binding: /Users/roman/workspace/vscode-playground/foo.py (0ms)
[BG]   checking: /Users/roman/workspace/vscode-playground/foo.py (0ms)
[BG] analyzing: /Users/roman/workspace/vscode-playground/foo.py (3ms)
[FG] parsing: /Users/roman/workspace/vscode-playground/foo.py (1ms)
[FG] binding: /Users/roman/workspace/vscode-playground/foo.py (0ms)
[BG] analyzing: /Users/roman/workspace/vscode-playground/foo.py ...
[BG]   parsing: /Users/roman/workspace/vscode-playground/foo.py (1ms)
[BG]   binding: /Users/roman/workspace/vscode-playground/foo.py (0ms)
[BG]   checking: /Users/roman/workspace/vscode-playground/foo.py (2ms)
[BG] analyzing: /Users/roman/workspace/vscode-playground/foo.py (3ms)
```
</details>

## Code Snippet / Additional information

![vscode](https://user-images.githubusercontent.com/75075/86347383-20b28080-bc56-11ea-978b-7765597c884b.gif)

**Comment by gramster** [comment]
Try this:

- Type `gc.`
- You should get a squiggle under `gc`
- If you hover on `gc` you should get a floating error popup saying it is not defined
- If you click on `gc` you should get a 'quick fix' lightbulb. and if you click on that you should get the option to add the import

**Comment by huguesv** [comment]
Also note that if you're trying to activate it with the keyboard, you'll only get a suggestion if the caret is within the identifier (in this case, after  `g` and  before `c`). If the caret is before or after the identifier, the lightbulb will not appear.

**Comment by Destaq** [comment]
> Try this:
> 
> * Type `gc.`
> * You should get a squiggle under `gc`
> * If you hover on `gc` you should get a floating error popup saying it is not defined
> * If you click on `gc` you should get a 'quick fix' lightbulb. and if you click on that you should get the option to add the import

This works, but I thought that it is auto-imported? Having to hover, click, and click every time sort of takes away the purpose and automation of auto-imports.

**Comment by huguesv** [comment]
Oh, sorry, I also confused light bulb with auto import. It's not auto importing for `gc` as shown in the animated gif from the blog post.

@heejaechang can you help?

**Comment by heejaechang** [comment]
unlike code action, since auto import shows up in completion list, we try not to include all possible identifiers in the completion. we only show ones already have used. we could tweak this behavior. but that is our current behavior.

that being said, we can improve code action to show it at the identifier edges.

**Comment by Destaq** [comment]
So is there support for the libraries being automatically imported when you type in e.g. `gc.disable()`? Because that doesn't seem to be happening, contrary to the introduction video.

**Comment by heejaechang** [comment]
it depends, for example, if you have 2 files open, and one of the files have gc used, then completion will have "gc" in the other file. if you have "import statement" in a current file that implicitly imports "gc", then "gc" will show up in completion.

otherwise, completion could have too many entries from all library files accessible from the current file. currently, code action can be used for this situation, and then related libraries will start to show up in auto import.

but that being said, we can improve auto-import behavior based on feedbacks.

**Comment by imankulov** [comment]
Thanks for clarifying, @heejaechang. Now it makes more sense, and I understand that it works as intended.

With this saying, I should admit that the auto-import behavior is quite confusing because it works in a limited set of scenarios. For example, to import `gc`, you need to have a different file where you imported the module before. The file should be open in your session, and you should interact with this file in a special way (the editor should auto-complete the contents of `gc.` for you at least once.) Then you can close the file, but if you close the session and re-start it again, you lose the auto-import for the module again.

I recorded a second video, and it's available here: https://ibb.co/B6MJDBM (the file was too large to upload on GitHub.)

Since it's not a bug, I don't mind if you close this issue.

**Comment by Destaq** [comment]
Yes, maybe I'm missing some resource, but I don't see any detailed information about PyLance other than the introductory README.md and blog post. If you haven't set it up, I believe that it would be useful for potential users to have a page/file they can go to in order to see all of the features of PyLance.

For example, the auto-import information should be included there, as well as docstrings, detail on each of the features, etc.; many features are listed but only a few are demonstrated with video.

**Comment by erictraut** [comment]
Thanks for the input. I agree that the auto-import behavior is confusing, and there are opportunities to improve it further.

It tends to work better if you set the diagnostic mode to tell pylance to analyze all of the files in your workspace rather than just the open files.
```
"python.analysis.diagnosticMode": "workspace"
```

I also like the idea of providing additional documentation for Pylance. In the meantime, the [Pyright](https://github.com/microsoft/pyright) site may provide you with some of the information you're looking for. Pylance is built on Pyright, so most of the functionality is the same.

**Comment by imankulov** [comment]
@erictraut, thanks for the hint. Meanwhile, setting `"python.analysis.diagnosticMode": "workspace"` hasn't changed the behavior of the auto-imported. I can see from the console that the extension analyzed closed files as well, but it didn't make the auto-complete work.

**Comment by imankulov** [comment]
I allow myself to close down the issue. It's not a bug, and I think there's no immediate actionable to change the behavior. Thanks a lot for explaining how the feature works.

**Comment by JosephTLyons** [comment]
Even after hearing the explanation, I'm still confused as to why I can't get automatic imports to work the same as the gif shows.  It seems a bit misleading.

**Comment by erictraut** [comment]
I'm going to reopen this because I think it's worth investigating further. At the very least, we need to document the current behavior better. And we should look for ways to improve the behavior.

**Comment by JosephTLyons** [comment]
From what I read, the reason why gc doesn't just magically show up as an auto-import (unless another file has recently imported it) is because there would be too many suggestions for in the autocomplete/auto-import menu if it had to show them for every character types... I think a good middleground would be to show normal code completions as you type (like normal), then only show possible auto-imports after the `.` is typed on a bit of code.

So if you had a variable called "date" and you typed in "da..." somewhere, the autocomplete list would show "date" as a possible autocomplete... but if you typed "datetime.", then the import for `datetime` would show up.  It would not populate the autocomplete list until the `.` was inserted.

Just a suggestion.

**Comment by taldcroft** [comment]
Somewhat related, I finally understood why this was not working for me at all.  I was doing something like this:
```
template = jinja2.
```
It seems that the auto-import functionality is only triggered when the package name is at the beginning of the statement, but of course this is most commonly not the case. Am I getting that right and can this behavior be improved?

**Comment by VolkerH** [comment]
yes, please  document this prominently as it is prominently featured in the blog post. I saw the blog, thought "great", tried with a numpy import (didn't work),  tried to replicate the behaviour from the blog post with `.gc.`, uninstalled/reinstalled pylance, tried again until I decided to look in the issues.

**Comment by ebsaral** [comment]
![Screen Recording 2020-07-09 at 05 29 36 PM](https://user-images.githubusercontent.com/2864828/87052881-f9d1ec80-c209-11ea-9ef4-dccb857c6e99.gif)

I am working in a Django project. 

As seen in this GIF, auto-import should import as `from django.core.paginator import Paginator` but case insensitivity causes a problem, I guess? I couldn't make this work right. Leaving it as an example.

**Comment by BrennanAyers** [comment]
Hi all, coming to VSCode from PyCharm to be able to use LiveShare in these full remote times. Glad to see I'm not the only one confused by this implementation/lack of functionality around auto imports.
Just wondering why the solution isn't something along the lines of what JetBrains has already done with their IDEs: https://www.jetbrains.com/help/pycharm/creating-and-optimizing-imports.html
With the specific hotkey you don't flood Intellisense with extraneous information, and you also don't have to search for the import every time you type something, only when triggered. Coming into a new codebase, this feature is a lifesaver and it would be great to see it in Pylance.
Thanks!

**Comment by heejaechang** [comment]
we will work on improving this feature based on feedbacks in future releases! we are already looking into it! hopefully, we have something to show soon!

**Comment by oesah** [comment]
To sum my opinion up: Great improvement overall, but this auto-import is still not a good solution. I am wondering, why does it Work so well with Type-/Java-Script? Javascript usually has much more libraries, but it still works super fast and accurate.

**Comment by heejaechang** [comment]
we just didn't implement some of the things that require more CPU and memory to work. eventually, hopefully we can add functionalities that people want based on feedback!

**Comment by bkcsfi** [comment]
Is there a way to disable auto-import suggestions/function?

I cannot find a setting to control it.

I'm finding my modules are randomly failing to load because weird imports have been pasted in at the top, these are invalid imports (i.e. importing something that doesn't exist)

Sometimes the UI is janky as I type, I suspect the UI sometimes thinks I'm trying to pick an auto-import. I would like to turn off this feature.

For myself, I don't like auto-imports because I want to explicit about what gets imported. I can see others might find it handy.

**Comment by jakebailey** [comment]
@bkcsfi No, but you can upvote #64.

**Comment by bkcsfi** [comment]
Ooops, sorry I missed that. Upvoted. Please close this ticket

**Comment by heejaechang** [comment]
should be fixed in the 

![autoimportfix](https://user-images.githubusercontent.com/1333179/92031439-77ebd480-ed1d-11ea-86c7-bb0f8ea9c8b6.gif)
next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020

**Comment by hmoravec** [comment]
I have still issues with auto-imports, e.g. auto-import of Path from pathlib doesn't work:
![image](https://user-images.githubusercontent.com/43935406/99283790-c5181680-2835-11eb-802a-3009588ebebe.png)

Only when I manually added `from pathlib import Path` and then deleted it again, the auto-import suggested to Add import Path from pathlib:
![image](https://user-images.githubusercontent.com/43935406/99284247-4cfe2080-2836-11eb-9eb7-791246f45736.png)

**Comment by jakebailey** [comment]
The code that fixed this issue was disabled for performance reasons while we could optimize it. Can you set `"python.analysis.indexing": true` and see if your issue is resolved and don't have too much extra performance degredation?

**Comment by hmoravec** [comment]
Seems to be working now, even though VS Code shows warning "Unknown Configuration Setting" for this option in `settings.json`.

**Comment by jakebailey** [comment]
Yes, it's a hidden toggle for testing. We're hoping to get that enabled for everyone soon, so thanks for confirming that it's working out.

**Comment by hmoravec** [comment]
The auto-import still is not working in some cases. I have defined variable (type alias) `ImagePil = PIL.Image.Image` in one module. When I type `ImagePil` as a type annotation in a function in other module, VS Code does not offer any actions (even when I added the import manually at first and then deleted it). When I try to invoke Quick fix command, it only shows `No code action available` and the language server logs `Background analysis message: getDiagnosticsForRange` and nothing happens.

**Comment by erictraut** [comment]
Type aliases are not currently included in the index, but this support was just added. The challenge with type aliases is that they are syntactically identical to variable assignments in Python, so without a full type analysis, it's not possible to tell them apart in a definitive manner. And full type analysis is way too expensive to do for every library file during indexing. The solution we've converged upon is to use simple naming heuristics to do a "good enough" job of distinguishing variables from type aliases, since the latter are typically named using capitalized camel-casing. You'll see this change in the next release of pylance.

**Comment by hmoravec** [comment]
I bumped into another problem: I have package `pdf2image` in my virtual environment in Docker container. I can see in the language server logs:
```
[BG(1)]     parsing: /opt/venv/lib/python3.8/site-packages/pdf2image/pdf2image.py [fs read 0ms] (33ms)
[BG(1)]     binding: /opt/venv/lib/python3.8/site-packages/pdf2image/pdf2image.py (4ms)
[BG(1)]     parsing: /opt/venv/lib/python3.8/site-packages/pdf2image/generators.py [fs read 0ms] (1ms)
[BG(1)]     binding: /opt/venv/lib/python3.8/site-packages/pdf2image/generators.py (0ms)
```
But when I type `pdf2image`, VS Code does not offer to import this package.

**Comment by AndrewTrapani** [comment]
The auto import functionality and suggestions wasn't working as I expected today with:
VS Code 1.51.1
PyLance 2020.12.0
Python 2020.11.37...

Fixed some issues I was having today by adding this hidden setting to "settings.json"
`"python.analysis.indexing": true`
Press ctrl+shift+p to bring up the "Command Palette" (View menu -> Command Palette) and I found "Preferences: Open Settings (JSON)" by starting to type "settings.json"
NOTE: There was also workspace settings, if you wanted to set it for just one workspace.

This hidden "feature" fixed an issue where when I typed `os.` it wouldn't suggest an import in any of the ways I'd have expected:
Type `os.` and a menu doesn't pop up with an Auto Import option.
Type `os.` and mouse over `os`, and Quick Fix ... doesn't appear.
Type `os` and no light bulb appears. Mouse over and still no light bulb.

When I enabled the above setting
Type `os` and a menu pops up with an Auto Import option.
Type `os` or `os.` and mouse over `os`, and Quick Fix ... appears and works. Clicking on it opens a menu to suggest one of many options (if any) as "Add import os".

Similarly, works with `gc` and guessing if the user meant something else:
Type `gc` and press "Ctrl" + "." to bring up a menu "Add import gc" and "Add import gcd from math"

NOTE: `gc` was not imported AFAIK into any other files in the workspace.

**Comment by anthonyalayo** [comment]
> The code that fixed this issue was disabled for performance reasons while we could optimize it. Can you set `"python.analysis.indexing": true` and see if your issue is resolved and don't have too much extra performance degredation?

Hey there, new to the thread. I just got up to speed with Pylance in VS Code and without this setting on, I was enable to get any autocompletion for imports. Now it is working.

**Comment by hipertracker** [comment]
I can't find `python.analysis.indexing`. There is no such option in the latest Pylance.

**Comment by jakebailey** [comment]
It is a hidden option, and must be set directly in your settings.JSON.

**Comment by liudonghua123** [comment]
> It is a hidden option, and must be set directly in your settings.JSON.

Thanks!

**Comment by tonisives** [comment]
Would it make sense to enable `python.analysis.indexing` by default?

I write `pytest` and it recommends ByteString without the setting.

<img width="456" alt="Screenshot 2021-12-16 at 16 18 38" src="https://user-images.githubusercontent.com/1083534/146343290-5a9d9371-b431-413e-8588-0e6d727a1183.png">

**Comment by davidonlaptop** [comment]
YMMV but it seems that the default indexing isn't deep enough for auto-import to work when the function or class you import is not at the root level, so here's what I had to put in my settings.json for it to work properly:

```json
{
  "python.analysis.autoImportCompletions": true,
  "python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 3
    },
    
    ]
}
```
