### ISSUE TITLE
Certain chromeOptions cause code to be unreachable for all following statements. 

### ISSUE THREAD

**Issue by GlacierDan** [microsoft/pylance-release#2807]
Like others here, I am having the code unreachable problem.  Mine is directly related to using "add_experimental_option" for Chrome Options.  I have tried it this evening with a few different options, and all are leading to the grayed lines.

I am guessing something on my machine updated, because it was fine this morning, and then not fine this afternoon.  Actually, in some of my Python files, it is still not an issue, and in others, the exact same setup and approach has grayed out lines.  The file runs fine, and opens the browser and outputs as expected, but the grayed text is terribly annoying. Please help!  

To simplify, below is a code snippet showing an example.  If I comment out the line that lets Chrome run detached so it does not close when the script is done, then everything becomes normal and reachable.  But with that "add_experimental_option" line in there, the rest goes gray. 

<img width="531" alt="Screen Shot 2022-05-12 at 7 04 46 PM" src="https://user-images.githubusercontent.com/49542835/168181785-170d2237-7abf-44fc-82a5-d2c1a8883442.png">

**Comment by erictraut** [comment]
Thanks for filing the issue. 

For future bug reports, it would be helpful if you pasted the code sample as text so we don't need to retype it from a screen shot. For reference, here's the relevant part of the sample:

```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options as ChromeOptions

chromeOpts = ChromeOptions()
chromeOpts.add_experimental_option("detach", True)
driver = webdriver.Chrome(options=chromeOpts)
```

I'm not able to repro the problem as reported. Could you confirm that you're running the latest version of pylance (v2022.5.1)?

![Screen Shot 2022-05-12 at 4 19 37 PM](https://user-images.githubusercontent.com/7040122/168182697-abe945e9-89a4-440f-95f7-b7a612e14156.png)

The symptom you're seeing indicates that the `add_experimental_option` method raises an exception or otherwise does not return. If you right click on `add_experimental_option` and choose "Go To Declaration", where does it take you? For me, it takes me to the file "ms-python.vscode-pylance-2022.5.1/dist/typeshed-fallback/stubs/selenium/selenium/webdriver/chrome/options.pyi".

Which version of the selenium library do you have installed in your Python environment? I have version 4.1.5 installed.

**Comment by GlacierDan** [comment]
Sorry about the screenshot.   
I am using VSCode 1.67.1
I am running Pylance v2022.5.1
I am running Selenium 4.1.3

"Go To Declaration" took me to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py
I see that function is defined with -> NoReturn, so I guess that's the issue. Do I just change that to None and save it?

**Comment by GlacierDan** [comment]
@erictraut 
I am sorry about the screenshot - I am new to this.  Thank you for your help.   
I am using VSCode 1.67.1
I am running Pylance v2022.5.1
I am running Selenium 4.1.3

"Go To Declaration" took me to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py
I see that function is defined with -> NoReturn, so I guess that's the issue. Do I just change that to None and save it?

**Comment by erictraut** [comment]
Ah, then it's a bug in that version of selenium. It looks like they've fixed it in newer versions. So if you are able to upgrade to 4.1.5, that's probably best. If you're stuck using 4.1.3 for some reason, then you could edit the code to replace `NoReturn` with `None.

**Comment by GlacierDan** [comment]
How do I update selenium for this?

**Comment by erictraut** [comment]
`pip install selenium --upgrade` should do it.

**Comment by GlacierDan** [comment]
I upgraded it, but still see the gray lines of code

**Comment by erictraut** [comment]
You will need to restart the language server. You can either close the project window and reopen it or use the "Python: Restart Language Server" command from the Commands menu in VS Code.

**Comment by GlacierDan** [comment]
I did both of those options, and still see unreachable gray code

**Comment by erictraut** [comment]
If you choose "Go To Declaration", where does it take you now? If you have 4.1.5 installed, it should look like this:

![Screen Shot 2022-05-12 at 5 02 15 PM](https://user-images.githubusercontent.com/7040122/168186118-e2e24589-a740-448a-89b1-e3d866a7f041.png)

Are you sure you installed the new version of selenium in the same python environment that you have selected in VS Code?

**Comment by GlacierDan** [comment]
When I open a terminal window in VSCode from the project, and in that same directory I run
python3 -c "import selenium; print(selenium.__version__)"
It returns: 4.1.5

"Go To Declaration" brings me to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py
The function looks like this:
```
    def add_experimental_option(self, name: str, value: Union[str, int, dict, List[str]]) -> NoReturn:
        """
        Adds an experimental option which is passed to chromium.

        :Args:
          name: The experimental option name.
          value: The option value.
        """
        if name.lower() == "w3c" and (value == "false" or value is False):
            warnings.warn(UserWarning("Manipulating `w3c` setting can have unintended consequences."))
        self._experimental_options[name] = value

```

**Comment by erictraut** [comment]
I've confirmed that the code you're seeing is from selenium 4.1.3. You have some versioning issue that you'll need to figure out. If you install selenium 4.1.5, the problem will go away.

In any event, Pylance is doing the right thing here.

**Comment by GlacierDan** [comment]
So VSCode is showing code that is 4.1.3, yet in the VSCode terminal it says it is running 4.1.5.  I have no idea how to fix this, but I understand it is not in your scope.  Thank you for all your help.  Have a great rest of your day.

**Comment by visar63** [comment]
Thank you @GlacierDan for bringing up this issue, since I had same issue as well. And thanks @erictraut for suggestions, it worked for me after upgrading selenium.

**Comment by MBezerril** [comment]
Worked for me too!
