### ISSUE TITLE
Default search paths not found and ${workspaceFolder} doesn't work with `python.analysis.extraPaths`

### ISSUE THREAD

**Issue by meichthys** [microsoft/pylance-release#281]
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.8

## Expected behaviour

Pylance should automatically be able to locate local modules and provide autocomplete like:
![image](https://user-images.githubusercontent.com/10717998/91212205-e4435400-e6dd-11ea-88cb-d3af0212051a.png)
![image](https://user-images.githubusercontent.com/10717998/91212325-0ccb4e00-e6de-11ea-93c7-91ca78fa8f28.png)

Inside `src`:
![image](https://user-images.githubusercontent.com/10717998/91212871-cfb38b80-e6de-11ea-828e-e779aef6005b.png)

## Actual behaviour

Pylance does not find the modules in the root of `src` so it is necessary to add `src` to `python.analysis.extraPaths`. Adding `src` to `python.analysis.extraPaths` works but adding `${workspaceFolder}\\src` does not work:
![image](https://user-images.githubusercontent.com/10717998/91212645-8105f180-e6de-11ea-894f-98906943b5cf.png)

![image](https://user-images.githubusercontent.com/10717998/91212667-87946900-e6de-11ea-9d32-11b4446cafef.png)

**Comment by meichthys** [comment]
@jakebailey From pull request #280

**Comment by jakebailey** [comment]
For what it's worth, `"./src"` will do exactly what you're intending; paths are resolved relative to the workspace root.

I'm actually surprised that you need to set `src` at all; we should be auto-detecting `src` and adding it automatically. Does your `src` folder contain an `__init__.py`, making it importable?

**Comment by meichthys** [comment]
Right. According to the docs `src` is supposed to be detected automatically but is is not. As seen in the screenshot above `src` does contain an `__init__.py`. 
One thing we've noticed is that if we use an old version of the Python extension (like 2020.5.80290) it works.

**Comment by jakebailey** [comment]
The python extension version doesn't really matter per se, the LS being used does. A really old version of the extension is likely falling back to jedi or MPLS. 2020.5 is definitely before the release of Pylance.

It's very strange to have `__init__.py` in a `src` folder, as it implies that it's legal to write `import src.foo.bar`, when most people are intending `import foo.bar`. The hueristic we use notes that, and tries not to generate a false negative in the case that a user really did want to write `import src.foo.bar`.

In any case, you should be able to set `"./src"` and it work. This example in particular is documented in our troubleshooting docs: https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

**Comment by meichthys** [comment]
Your first paragraph would make sense since jedi works as expected.

Thanks for the explanation. I was able to verify that removing the `__init__.py` from the `src` directory works.
