### ISSUE TITLE
Since upgrading to VSCode 1.67, Pylance Intellisense does not work for 3rd party libraries. Downgrading to 2022.2.4 fixed the issue

### ISSUE THREAD

**Issue by CraigPersonal100** [microsoft/pylance-release#2810]
The example I discovered this problem with is `asyncua`. It cannot find the import for `sync.Server`:

```
from asyncua.sync import Server
```

It was installed with:

`pip install asyncua`

And my workspace `settings.json` are:

```
{
    "python.autoComplete.extraPaths": [
        "C:\\Python38\\Lib\\site-packages"
    ],
    "python.analysis.extraPaths": [
        "C:\\Python38\\Lib\\site-packages"
    ]
}
```

I have the default user `settings.json`

I have seen [discussions online](https://www.reddit.com/r/vscode/comments/uk2fl9/pylance_doesnt_show_object_methods_information/) that others have had this problem.

Downgrading to 2022.2.4 fixed the issue.

**Comment by bschnurr** [comment]
looks like they re-export server at the root level.

`from asyncua import Server`

though both ways are working for me. you shouldn't have to set extraPaths, just make sure you have selected the correct environment.

i tested with ` Downloading asyncua-0.9.92-py3-none-any.whl (619 kB)` on windows with python 3.10

**Comment by erictraut** [comment]
I'm not able to repro this problem either. Is it possible that you have an old version of asyncua installed? Like @bschnurr, I installed the latest version which is 0.9.92.

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
