### ISSUE TITLE
indent problem bill

### ISSUE THREAD

**Issue by PatrickCuentas** [microsoft/pylance-release#2812]
<h3> Environment data </h3>

-   Language Server version: 2022.5.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by debonte** [comment]
@PatrickCuentas, there's not enough info here for us to investigate. Please open a new issue with a complete description of the problem you are seeing. See our [troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) for guidance.
