### ISSUE TITLE
Numpy NDArray with built-in float raise an error

### ISSUE THREAD

**Issue by longcw** [microsoft/pylance-release#2817]
## Environment data

-   Language Server version: 2022.5.1
-   OS and version: Manjaro Linux
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.10

## Code Snippet

```python
import numpy as np
from numpy.typing import NDArray

TypeA = NDArray[float]  # not work
TypeB = NDArray[np.float64]  # works
```

## Repro Steps

1. Use code snippet above

## Expected behavior

`TypeA` and `TypeB` should be both correct.

## Actual behavior

`TypeA` raise a problem:
```
Could not specialize type "NDArray[ScalarType@NDArray]"
  Type "float" cannot be assigned to type "generic"
    "float" is incompatible with "generic"Pylance
```

**Comment by erictraut** [comment]
The symbol `NDArray` is a generic type alias that is defined by the numpy library as `np.ndarray[Any, np.dtype[ScalarType]]`. `ScalarType` is a type variable bound to `np.generic`. That means the type argument provided for `NDArray` must be compatible with the type `np.generic`. The builtin `float` is not type compatible with `np.generic`, so pylance is correct in flagging this as an error given the type information provided within the numpy library.

If you think that `float` should be allowed here, you should file a bug with [numpy](https://github.com/numpy/numpy/issues).
