### ISSUE TITLE
Refactor: Move Function or Class

### ISSUE THREAD

**Issue by dciborow** [microsoft/pylance-release#2821]
I would like to be able to easily move a function or class from one file to another. When moving the class, all the imports in my project should be properly updated with the new location. If other functions or classes depend on the object being moved, I should be prompted to include them in the move. 

#### File1.py
```python
def func1(): 
  pass


def func2(): # We will select this function to move to File2.py
  func1()


def func3():
  func2()
```

When selecting to _Refactor: Move_ `funct2`, to File2.py, it should be noted that `func1()` must also be moved, to prevent creating a circular dependency.

#### File1.py
```python
from File2 import func2  # This line was inserted for me after func2() was moved

def func3():
  func2()
```

#### File2.py
```python
def func1():  # Dependent functions where also moved 
  pass


def func2():  # This function was selected for refactoring
  func1()
```

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/discussions/2617
