### ISSUE TITLE
Issue not fixed yet... #2505

### ISSUE THREAD

**Issue by Zaeem20** [microsoft/pylance-release#2827]
## Environment data

-   Language Server version: 2022.5.1
-   OS and version: Windows 10 pro 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.10 

## Actual behavior

@heejaechang @bgianfo **that issue is not fixed yet**

![image](https://user-images.githubusercontent.com/60778335/168834840-9fdf7afa-5242-4259-a3a1-7381fe036436.png)

**Comment by Zaeem20** [comment]
it creating delay in my work 

i have to restart it again , then it got fixed...

**Comment by heejaechang** [comment]
@Zaeem20 can you provide some detail repro steps. I am not sure what you are asking.

**Comment by Zaeem20** [comment]
hey i think i fixed it python.autoComplete.ExtraPaths...

yeah it working fine now....

**Comment by Zaeem20** [comment]
> also whenever i install new packages in workspace(no venv) using pip, it not recognizing it
> 
> ![image](https://user-images.githubusercontent.com/60778335/169105526-ef7d1c74-507c-4033-a05a-77e773c19c13.png)
> 
> but strange thing, it instantly detects any new package in virtual env @heejaechang

this issue is fixed now by adding autoComplete.extraPaths

**Comment by Zaeem20** [comment]
But still getting **"Select Python Interpreter"** error

_See this Logs_:

```Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'pythonSurveyNotification' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonInterpreterInfoPinned' is active
> conda info --json
> "~\AppData\Local\Programs\Python\Python39\python.exe" "~\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\get_output_via_markers.py" "~\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\interpreterInfo.py"
[ERROR 2022-4-20 20:2:58.147]: [Error: Command failed: "C:\Users\Zaeem Durani\AppData\Local\Programs\Python\Python39\python.exe" "c:\Users\Zaeem Durani\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\get_output_via_markers.py" "c:\Users\Zaeem Durani\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\interpreterInfo.py"

	at ChildProcess.exithandler (node:child_process:406:12)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)] {
  killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '"C:\\Users\\Zaeem Durani\\AppData\\Local\\Programs\\Python\\Python39\\python.exe" "c:\\Users\\Zaeem Durani\\.vscode\\extensions\\ms-python.python-2022.6.2\\pythonFiles\\get_output_via_markers.py" "c:\\Users\\Zaeem Durani\\.vscode\\extensions\\ms-python.python-2022.6.2\\pythonFiles\\interpreterInfo.py"'
}
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
Starting Pylance language server.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
```


@heejaechang @mattetti

**Comment by Zaeem20** [comment]
how do i fix it

**Comment by Zaeem20** [comment]
no reply yet @heejaechang

**Comment by Zaeem20** [comment]
looking for reply, anyone???

**Comment by debonte** [comment]
> But still getting **"Select Python Interpreter"** error

@Zaeem20, this appears to be an issue with the Python extension rather than Pylance. Looks like the same issue as https://github.com/microsoft/vscode-python/issues/19104. Please comment on that issue.

Btw, it's very confusing when you report multiple different problems in the same GitHub issue. It would be best to open a separate issue for each problem that you are seeing. It's easier for us to manage, easier for other users who are experiencing the same problem to find, etc.

> this issue is fixed now by adding autoComplete.extraPaths

Thanks, closing this issue.
