### ISSUE TITLE
Pylance experiment doesn't provide semantic colorization without scrolling

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#2837]
<h3> Environment data </h3>

-   Language Server version: 2022.5.3-pre.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off
-   python.pylanceLspNotebooksEnabled: true

<h3> Expected behaviour </h3>

Semantic colorization happens without having to scroll.

<h3> Actual behaviour </h3>

This cell works for hover, but colors are off:

![image](https://user-images.githubusercontent.com/19672699/169404424-6a7fe4ba-5c05-47cb-ba26-18393805cc0c.png)

If I scroll colors fix themselves:

![image](https://user-images.githubusercontent.com/19672699/169404614-9c7ef17f-47c1-48ee-b760-3f2f4d38de41.png)

<h3> Logs </h3>

Python Language Server Log

[pylance.txt](https://github.com/microsoft/pylance-release/files/8734233/pylance.txt)

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by rchiodo** [comment]
Here's the smaller log
[pylance2.txt](https://github.com/microsoft/pylance-release/files/8742078/pylance2.txt)
:

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.8.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022851-31-august-2022-prerelease)
