### ISSUE TITLE
Can Pylance warn unused parameters like Java

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#2840]
As the title says, 

Expecte like Java:

![image](https://user-images.githubusercontent.com/100815370/169431372-4fbb2157-e8df-4287-ac20-3b2dbd7dfa47.png)
![image](https://user-images.githubusercontent.com/100815370/169431431-b61c1ae4-3ca7-4449-a928-2b54b6d308ae.png)

We can see the underline reminder, which also exists in the problem

Fact in Python:
![image](https://user-images.githubusercontent.com/100815370/169431513-5ee4ac4c-e5a6-4e6d-81ff-b45937f839f1.png)

Only the color reminder, which is really not obvious.

**Comment by erictraut** [comment]
Pylance supports the following diagnostic rules:
`reportUnusedImport` - reports imports that are unreferenced
`reportUnusedVariable` - reports local variables that are unreferenced
`reportUnusedClass` - reports class that is unreferenced within the module (applies only to private classes whose names start with an underscore)
`reportUnusedFunction` - reports function that is unreferenced within the module (applies only to private functions whose names start with an underscore)

You can enable these diagnostic rules by updating your project settings.
```
{
  "python.analysis.diagnosticSeverityOverrides": {
    "reportUnusedImport": "error",
    "reportUnusedClass": "warning"
  }
}```

**Comment by ydmykr** [comment]
@erictraut 
I don't know why. Recently, even though I added these two lines of reminders, I still didn't get any reminders from pylance. Is there any update from pylance? How can I get the prompt again.
