### ISSUE TITLE
colorama

### ISSUE THREAD

**Issue by adelar129** [microsoft/pylance-release#2843]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by debonte** [comment]
@adelar129, there's not enough info here for us to investigate. Please open a new issue with a complete description of the problem you are seeing. See our [troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) for guidance.
