### ISSUE TITLE
How to change the default folder for typings

### ISSUE THREAD

**Issue by AllanDaemon** [microsoft/pylance-release#285]
When I ask to generate a stub from a library, it creates a folder `typings/libname` in the root directory.  I wanna change it, in the workspace, to create this folder in another place (eg. `.vscode/typings`) instead of the root directory, as this breaks the folder structure of the project. I tried to find it in the settings but there isn't anything like that.

Where do I change it?

**Comment by savannahostrowski** [comment]
Hey there! You can change the path by setting `python.analysis.stubPath` in your settings.json.

**Comment by AllanDaemon** [comment]
Oh. I had understood that `python.analysis.stubPath` is like the extra paths config, but for stubs. Now it seems dumb, but maybe a little more clarification in the `python.analysis.stubPath` description could help a few ones that might not get it like me.

**Comment by jakebailey** [comment]
What would you suggest? We show the default value as "./typings" already. Are you looking for it to mention that that's where generated stubs are placed?

**Comment by AllanDaemon** [comment]
well, showing that the default is `./typings` would be enough. But I think the problem is that it doesn't show the default in VSCode settings.

![image](https://user-images.githubusercontent.com/607994/91350409-07910080-e7bd-11ea-8b01-9428d0a891fe.png)

**Comment by jakebailey** [comment]
Ah, interesting. It should be there, but empty/undefined is equivalent to default, so it probably wasn't caught.

**Comment by AllanDaemon** [comment]
Maybe this is more a VS Code issue, that seems to never show the defaults for some kind of fields.

**Comment by jakebailey** [comment]
No, it's up to the extension to declare its defaults, so we just have to add it in.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
