### ISSUE TITLE
No attribute suggestions after indexing operator.

### ISSUE THREAD

**Issue by Steamvoker** [microsoft/pylance-release#2852]
## Environment data

-   Language Server version: v2022.5.3
-   OS and version: Windows 10 Pro 21H2
-   Python version: Python 3.10.4

## Code Snippet

```python
dc = {}

dc.setdefault('foo', {})
dc['foo'].
```

## Expected behavior

![example](https://user-images.githubusercontent.com/23413050/170447024-459b8ddb-a99b-4b52-b6af-f8cd76afd43d.png)

## Actual behavior

![example2](https://user-images.githubusercontent.com/23413050/170447339-40cfc6ae-c348-42da-aa81-65531ddc5c5f.png)

**Comment by erictraut** [comment]
The type of `dc` is inferred to be `dict[Any, Any]` in this case, so any index operation will have a type of `Any`, which explains why there are no completion suggestions in this case.

If you assign a value to a dictionary key locally using an assignment operator and a static key (either an integer or string literal value), the type of that expression will be narrowed to the assigned type, and you will then see completions if you read back that value.

```python
dc = {}
dc['foo'] = 'hi'
dc['foo'].<completions for str object>
```

So the current behavior is as I would expect given the type information pylance has at its disposal.
