### ISSUE TITLE
Suggestions only appear if I open the file I want to import from

### ISSUE THREAD

**Issue by PedroKrohling** [microsoft/pylance-release#2856]
<h3> Environment data </h3>

-   Language Server version: 2022.5.4-pre.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.12 (venv)
- "python.languageServer": "Pylance"
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

I expected that the indexing done by Pylance to appear in the suggestions (Ctrl + Space) without the need to open the file which I want to import from. Like what happens using Quick Fix.

<h3> Actual behaviour </h3>

Whenever I open VSCode from the first time (or Reload Window) the suggestions from the modules in my workspace doesn't show. I need to open the file for be able to see in auto-import suggestions.

<h3> Logs </h3>

Python Language Server Log
[log.txt](https://github.com/microsoft/pylance-release/files/8780777/log.txt)

<h3> Code Snippet / Additional information </h3>

Project Files
- workspaceFolder
-- event.py
-- sub_event.py

![Animação](https://user-images.githubusercontent.com/70545122/170539276-739d35ee-8ccf-4f00-84dd-0a665c775c5d.gif)

**Comment by bschnurr** [comment]
Unfortunately this is as designed, due to the long list of suggestions in large projects.

the work around is to trigger the code action provided 'ctrl + .' next to your 'Event' usage,  which will have the auto import you want
