### ISSUE TITLE
No keys hints for TypedDict when it is in union

### ISSUE THREAD

**Issue by pukhov** [microsoft/pylance-release#2860]
## Environment data

-   Language Server version: Pylance language server 2022.5.3 (pyright 73c82fab)
-   OS and version: Windows 10 / tested on Linux, too.
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4 (anaconda)

## Code Snippet

```python
from __future__ import annotations
from typing import TypedDict

class MyDict(TypedDict):
    a: str

def foo() -> MyDict | int:
    ...

x = foo()
# x. # OK: shows hints for int, e.g. bit_length and for dict, e.g. keys
# x[] # BUG: does not show 'a' here
# x[''] # and even here

# but this works, though, so it understands it is TypedDict, only hints do not work.
#y = x['a'] # inferred type of y is str | Any
```

## Expected behavior

Show keys hints, 'a' in this case

## Actual behavior

Does not show key hints.

**Comment by bschnurr** [comment]
I think you need to check that the type is `MyDict` first 

```python
if isinstance(x, MyDict):
    x['a'] = 'hi'
else:
    x = 1
```

**Comment by erictraut** [comment]
For type correctness, you'd need to add that check. For completions, we should offer suggestions for all subtypes in the union. We do this for unions in other cases, like in this example.

![Screen Shot 2022-05-26 at 2 41 20 PM](https://user-images.githubusercontent.com/7040122/170584742-d503a4dd-8abd-46f8-bd44-7adfa77feb29.png)
 
The completion logic for TypedDict is special-cased, and it doesn't currently handle unions properly.

**Comment by pukhov** [comment]
> I think you need to check that the type is `MyDict` first
> 
> ```python
> if isinstance(x, MyDict):
>     x['a'] = 'hi'
> else:
>     x = 1
> ```

I don't think one should check with isinstance to get autocomplete hints, finally, it's just a nice feature, the inference of types works correctly (I said so in the issue, that `y = x['a']` has correct type -- `str | Any`).

**Comment by pukhov** [comment]
@erictraut 

So it is currently not supported but maybe it will be fixed later?

**Comment by erictraut** [comment]
It's a trivial fix. Working on it now.

**Comment by erictraut** [comment]
This will be addressed in the next release.

The change also support unions that include multiple TypedDict types.

![Screen Shot 2022-05-26 at 2 54 11 PM](https://user-images.githubusercontent.com/7040122/170586282-7e69270f-c813-4579-b12e-55d0f111494a.png)

**Comment by pukhov** [comment]
Thanks!

In fact, what I want to achieve with this is to say that some class has these and these keys. Are there any other ways to tell this to pylance?

As I understand, now only TypedDict has supported hints. There are 2 "pythonic" solutions, both are prohibited by TypedDict pep though :)
1) class should inherit from TypedDict
2) add methods to TypedDict 

So what I am doing is a hack, I say "this is both class and it has these keys" by passing the union of my class and created TypedDict.

Motivation / common use-case: pandas.DataFrame / numpy.ndarray (with fields).

 I might create a separate issue for this, though not sure, if it's pylance or current Python typing state. (I think the latter)

**Comment by pukhov** [comment]
Ok, thanks!

**Comment by erictraut** [comment]
We'll leave this open until next week's release.

**Comment by pukhov** [comment]
@erictraut 

BTW, is the problem below also fixed by your change or should I open another issue? 

Normal classes have hints in notebooks, but TypedDicts don't. 

foo.py
```
from typing import TypedDict

class A:
    a: int

class B(TypedDict):
    a: int

def get_A() -> A:
    ...

def get_B() -> B:
    ...
```

in notebook:
(on double brackets see  #2384 )
```
import foo

a = foo.get_A()
b = foo.get_B()

a. # gives hints
b[] # no hints
b[[]] # and even this
```

**Comment by erictraut** [comment]
That should have worked prior to my change because `b` doesn't involve a union.

Here are the completions I receive with the latest code. I think this is what one would expect.

![Screen Shot 2022-05-29 at 10 07 36 AM](https://user-images.githubusercontent.com/7040122/170882727-fea35fbf-5ba3-4a66-b06d-a3d1d77aefcd.png)

![Screen Shot 2022-05-29 at 10 07 48 AM](https://user-images.githubusercontent.com/7040122/170882732-4d67ec41-9933-43d7-900b-de58d7ebf2dc.png)

**Comment by pukhov** [comment]
Yes, it works perfectly in normal py files, however for notebooks:
- if dict is already created and has keys then there is a known issue, when double brackets work and single brackets do not.
- if it is not created (but of a known type TypedDict), then neither single nor double brackets work, so I thought it's a different issue.

We can wait for that issue to be resolved first and if it still does not work, I ll open a new issue.
