### ISSUE TITLE
On ssh-remote the pylance does not work

### ISSUE THREAD

**Issue by muyidasheng** [microsoft/pylance-release#2862]
I tried ssh remote uninstall vscode server & reintall python & pylance extension & restart language server, the python intellisense always stuck at loading & CPU usage is very high. 

I use conda  python 3.8.12 as the interpreter. 

The OS is Linux x64 4.14.81.bm.15-amd64.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, would you please reopen the issue and add the repro steps? thanks
