### ISSUE TITLE
help im getting pylance client couldn't create conncet to server

### ISSUE THREAD

**Issue by Alrezi** [microsoft/pylance-release#2863]
<h3> Environment data </h3>

-   Language Server version: 2022.5.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```
![image](https://user-images.githubusercontent.com/105689446/170640450-b5f8e8c7-217b-414b-ba5e-62f25cd90c52.png)

**Comment by debonte** [comment]
Can you provide your logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by joootdooot** [comment]
The problem seems to go away after switching to another environment and switching back

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
