### ISSUE TITLE
Autocomplete not working properly for inherited classes - Ubuntu

### ISSUE THREAD

**Issue by 0xab3d** [microsoft/pylance-release#2868]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

While working on a Django project, autocompleting doesn't seem to be working properly for inhereted classes.

from django.contrib.auth.models import User, auth
user = User.objects.create_user(username=user_name, password=password1, email=email, first_name=first_name, last_name=last_name)

if I try to type user. nothing is being suggested.
![Image 0](https://i.imgur.com/ivteW2W.png)

Also, when I instated the object, when I type in User.objects create_user is not showing.

![Image 1](https://i.stack.imgur.com/aGXbM.png)
## Steps to reproduce:

from django.contrib.auth.models import User, auth
user = User.objects.create_user(username=user_name, password=password1, email=email, first_name=first_name, last_name=last_name)

Also, I don't get syntax error when I type in incorrect method name

![Image 2](https://i.stack.imgur.com/m761z.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

venvPath: "<placeholder>"

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.6.2
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.15.0-33-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|3.80GB (0.24GB free)|
|Process Argv|--crash-reporter-id 9c803422-b6ae-465a-a25d-e15097affe9e|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by erictraut** [comment]
Please provide a self-contained minimal code sample that demonstrates the problem. It's difficult to diagnose problems from partial screen shots. Also, please provide the versions of any libraries that you are importing in your code sample.

**Comment by 0xab3d** [comment]
Thanks @erictraut, I think anyone with VSCode and Python can replicate this:

Steps to replicate:
1. `cd /tmp` (example)
2. `mkdir temp_project`
3. `python -m venv .venv`
4. `source .venv/bin/activate`
5. `pip install django`
6. `django-admin startproject temp_project`
7. `cd temp_project`
8. Launch VSCode and navigate to * /tmp/temp_project/temp_project * and open any of the py files or create a new one.
9. Type in the following:
` from django.contrib.auth.models import User`
10. Start typing `User.objects.crea` and you will notice inherited functions are not listed.

**Comment by 0xab3d** [comment]
Thank you so much for this. So, do I have to make any changes my end? or the issue should be fixed in future releases?

**Comment by erictraut** [comment]
> do I have to make any changes my end?

No, you don't need to make any changes. The problem is with one of the ".pyi" files bundled with pylance.

> Also, could you please explain how can I manually amend the pyi file? 

You can right-click on "User" and choose "Go To Declaration". This will open the file `django/contrib/auth/models.pyi`. Within the `AbstractUser` class definition, add the line `objects: UserManager = ...`. Then save the file.

**Comment by 0xab3d** [comment]
Thank you so much, much appreciated 🙏🏻🙏🏻

**Comment by 0xab3d** [comment]
Thanks a lot :) btw any recommended resources that easily explains the pyi jargon?

**Comment by erictraut** [comment]
There's a bunch of documentation on the pyright project site. Pyright is the type checker that Pylance is built upon. Here's a good [starting place](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

**Comment by 0xab3d** [comment]
Thanks Eric for all your help :) shall I close the issue or it needs to remain opened until the issue is fixed on Pylance?

**Comment by erictraut** [comment]
Let's leave it open for now.

**Comment by rchiodo** [comment]
Looks like this has been fixed.

**Comment by kyoduke** [comment]
This solution also works if you are using a custom user model.

`objects = CustomUserManager()` shows **no autocomplete** for create_user.


`objects: CustomUserManager()` **shows autocomplete correctly.**
