### ISSUE TITLE
python.analysis.completeFunctionParens: don't add parentheses when other '(' already exists in next.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#287]
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: 
Version: 1.48.1 (user setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7 32-bit

## Expected behaviour

```python
dicts = {'key': 'value'}
dicts.pop('key')
```
when we go on `pop` and use 'ctrl+tab' then select `popitem` it should be like this:
```python
dicts = {'key': 'value'}
dicts.popitem('key')
```

## Actual behaviour

but currently it will:
```python
dicts = {'key': 'value'}
dicts.popitem()('key')
```

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
This request has been open for a while. Closing old issue because of lack of upvotes.

**Comment by wouter-palmsens** [comment]
> This request has been open for a while. Closing old issue because of lack of upvotes.

Upvoted. (Sorry, didn't know bugs had to be "upvoted" in order to be fixed.)

**Comment by ms77grz** [comment]
up
