### ISSUE TITLE
pylance not resolving site-package imports

### ISSUE THREAD

**Issue by ianbd** [microsoft/pylance-release#2872]
v 2022.5.3 appears not to be resolving packages that have been installed in site-packages.

For example 
"from lxml import etree"
gives the message 
Import "lxml" could not be resolved
The same is true for every other package I try to import from site-packages

Running the script is unaffected 
VS Code Version: 1.67.2

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
