### ISSUE TITLE
Pylance randomly using unindexed source

### ISSUE THREAD

**Issue by christopherdwelton** [microsoft/pylance-release#2878]
## Environment data

-   Language Server version: v2022.5.3
-   OS and version: Windows 10 Enterprise 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.8

## Code Snippet

```python
import sys
print(sys.path)
```

## Repro Steps

1. We have a source code repository (Perforce) that contains python source code which has not been installed on any computer yet.
2. This folder is not in any PATH or PYTHONPATH env variable, and is not printed out from print(sys.path)
3. Python itself is correctly loading the module code from the place it is installed on the local computer. Python has no idea the Perforce directory exists, because it is not in any path whatsoever.
4.  Pylance has somehow noticed that this directory exists and will always resolve module code to this directory as long as said directory is connected.
5. There are no "Extra Paths" components called out for pylance in the settings. It is not set.
6. "Python › Analysis: Auto Search Paths" is turned off
7. Switching back to Jedi instantly fixes the problem

## Expected behavior

Pylance should not be finding source code in random places and deciding it might be authoritative, especially when the settings are telling it not to look for any, explicitly

## Actual behavior

Pylance is finding code paths that are not indexed in any path variable and considering them to be authoritative

## Logs

```

The trace does show the folder in question is being considered an "Extra Path" by Pylance, despite not being set as an extra path, not being in the system path, and not being in the python sys path.

[Info  - 10:15:55 PM] (14360)   Looking in extraPath 'C:\repo\bin\Python'

(That folder should not even be known about by Pylance. As I said, it is not in extra paths, system path, python path, or sys.path inside python.)
```

**Comment by erictraut** [comment]
When you say "resolve module code to this directory", are you saying that there is an import statement in your code, and pylance is resolving the import to a module, but your expectation is that it should not be resolved in this case? In other words, you expect pylance to emit an error or warning associated with that import statement indicating that the import could not be resolved?

If my understanding is correct, let's confirm which source file pylance thinks the import is resolved to. To do this, open the file with the import statement, right click on the module name in the import statement and choose "Go To Declaration". Which file does it open? Is it a file within the Perforce directory?

You mentioned that the target module lives in a directory on another computer. Are you mounting this as a separate drive? By any chance, is there a symbolic link to this directory anywhere within your workspace directory? I'm wondering if pylance is perhaps following a symbolic link and treating it as though it's a subdirectory within your workspace.

You mentioned in step 1 that the source code hasn't been installed on any computer yet. But in step 3 you implied that the code has been installed on the local computer. Are you sure it isn't installed in the Python environment that you are using with pylance?
