### ISSUE TITLE
After creating a new notebook, language server error notifications appear 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/pylance-release#2888]
Testing microsoft/vscode-jupyter#10183

1. Create a notebook in insiders.vscode.dev
2. :bug: see these error messages:
![image](https://user-images.githubusercontent.com/30305945/171688724-275c46ff-37a1-4bf2-b0dd-b628e2f4df88.png)

I have the pre-releases of Python and Jupyter, and v2022.6.0 of Pylance

**Comment by debonte** [comment]
@joyceerhl can you provide the contents of the Python Language Server log?

Also, do you always see the same errors? I tried this twice and both times saw "Request textDocument/semanticTokens/full failed." which is different from the errors in your screenshot.

**Comment by joyceerhl** [comment]
Now I see "Request textDocument/semanticTokens/full failed" as well.

Logs:

```
[Info  - 1:47:58 PM] Pylance language server 2022.6.0 (pyright c6e1d8dd) starting
[Info  - 1:47:58 PM] Server root directory: /
Notebook support: Legacy
[Error - 1:47:58 PM] Request textDocument/semanticTokens/full failed.
  Message: Request textDocument/semanticTokens/full failed with message: Cannot read properties of undefined (reading 'startOffset')
  Code: -32603 
[Info  - 1:47:58 PM] No configuration file found.
[Info  - 1:47:58 PM] No pyproject.toml file found.

```

This only seems to occur in vscode.dev now, I can't repro in insiders.vscode.dev

**Comment by debonte** [comment]
I'm unable to repro this. Please reopen if you start seeing this again.
