### ISSUE TITLE
Autocomplete only works after re-selecting python interpreter

### ISSUE THREAD

**Issue by cgebbe** [microsoft/pylance-release#2889]
## Environment data

-   Language Server version: v2022.6.0
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): virtual environment, python 3.8.10

## Code Snippet

```python
import boto3
s3_client = boto3.client("s3")
response = s3_client.list_objects_v2(Bucket="my-bucket")
```

## Repro Steps

```bash
python -m venv venv
source ven/bin/activate
pip install boto3

# open vscode

pip install boto3-stubs
```

## Expected behavior

After installing boto3-stubs, autocomplete works (after a few seconds)

## Actual behavior

After installing boto3-stubs, autocomplete does NOT work. One workaround that works is re-selecting the python interpreter via "Python: Select Interpreter".

## Note

I use boto3 and boto3-stubs as an example here, but have experienced the same behavior with any other library (e.g. numpy, tqdm, ...)

**Comment by judej** [comment]
Thanks for the report. In your scenario, are you opening VSCode after the environment is created with `code .` from the project directory? If not, could you please try that?
