### ISSUE TITLE
List comprehension in __all__ definition hides module members

### ISSUE THREAD

**Issue by Achillx** [microsoft/pylance-release#289]
## Environment data

-   Language Server version: 2020.8.2
-   OS and version: macOS Mojave 10.14.6
-   Python version: Python 3.7.6 | packaged by conda-forge

## Expected behaviour

Importing a function from a sub-package using `from package import foo` Pylance is able to find the definition.

## Actual behaviour

Importing a function from a sub-package using `from package import foo`  and hovering on the function, Pylance displays
`(import) foo: Any`.

![Screenshot 2020-08-27 at 13 27 12](https://user-images.githubusercontent.com/38357732/91436798-1b923c00-e869-11ea-8c8e-5db32a01e137.png)

and when right-clicking and "Go to Definition" displays "No definition found for foo"

![Screenshot 2020-08-27 at 13 28 42](https://user-images.githubusercontent.com/38357732/91436876-3f558200-e869-11ea-81f6-cabca7414287.png)

If the function is imported using `from package.sub_package import foo` it finds it

![Screenshot 2020-08-27 at 13 27 22](https://user-images.githubusercontent.com/38357732/91436831-2d73df00-e869-11ea-85d8-579b64af20d5.png)

## Code Snippet / Additional information
The folder structure is:
```
main.py
package
└─ __init__.py
└─ package_file.py
└─ sub_package
   └─ __init__.py
   └─ sub_package_file.py
````

Files content for those who don't want to download the zip file
[pylance_test.zip](https://github.com/microsoft/pylance-release/files/5136032/pylance_test.zip)

#### main.py
```
from package import dog
from package.sub_package import cat
from package import cow

print(dog(4))
print(cat(2))
print(cow(8))
```

#### package init
```
from .sub_package import *
from .package_file import *

__all__ = [name for name in dir() if not name.startswith('_')]
```

#### sub_package init
```
from .sub_package_file import *

__all__ = [name for name in dir() if not name.startswith('_')]
```

#### sub_package_file.py
```
__all__ = [
	'cat',
	'dog'
]

def cat(t):
	""" 
	Make the cat meow

	Parameters
	----------
	t : int
		How many times to meow

	Returns
	-------
	string
	"""

	return "Cat says:" + " meow" * t

def dog(t):
	""" 
	Make the dog bark

	Parameters
	----------
	t : int
		How many times to bark

	Returns
	-------
	string
	"""

	return "Dog says:" + " woof" * t + "!!"

if __name__ == "__main__":
	print(cat(1))
	print(dog(3))
```

#### package_file.py
```
__all__ = [
	'cow'
]

def cow(t):
	""" 
	Make the cow moo

	Parameters
	----------
	t : int
		How many times to moo

	Returns
	-------
	string
	"""

	return "Cow says: m" + "oo" * t + "!!"

if __name__ == "__main__":
	print(cow(8))
```

**Comment by erictraut** [comment]
The problem is that you are using wildcard imports with a value of `__all__` that is defined with a complex dynamic expression. Pylance is based on Pyright, which is a static type analyzer. It is able to evaluate expressions like `__all__ = ['cow']`, but it cannot evaluate something as dynamic as `__all__ = [name for name in dir() if not name.startswith('_')]`.

If you comment out two dynamic `__all__` expressions within your example above, Pyright is able to see the imported symbol `dog`.

If you want your package to work correctly with static type checkers, you should either avoid using wildcard imports or replace dynamic `__all__` expressions with static expressions like `__all__ = ['cat', 'dog']`.

**Comment by Achillx** [comment]
Thanks for the info!
Since I'm not the main developer of the package in question _(not the one with the cat and dog!)_ , I'll point them to your suggestion.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by debonte** [comment]
Here are the forms of __all__ that type checkers have agreed to support: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface
