### ISSUE TITLE
pylance does not infer a type correctly a variable is set via 'global'

### ISSUE THREAD

**Issue by SteveBenz** [microsoft/pylance-release#2895]
## Environment data

-   Language Server version: v2022.6.0
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0

## Code Snippet

```python
from typing import Optional

s: Optional[str] = None

def gf() -> None:
    global s
    s = "hello"

gf()
l: int = s.index('o')
print(f'o is at index {l}')
```

## Expected behavior

It understands that `o` is of type `str`.

## Actual behavior

Pylance has no idea what type type of `s` is and complains about "s.index"

**Comment by erictraut** [comment]
This is expected behavior. Static type checkers perform "type narrowing" within execution contexts but not across such context. In your example, the function `gf` is a separate execution context from the global (module-level) execution context. In general, analyzing this wouldn't be possible because dynamic execution paths cannot be predicted statically.

You have a few options here:
1. Add an assert statement after calling `gf`
```python
gf()
assert s is not None
l: int = s.index("o")
```

2. Rewrite `gf` so it returns the new value of `s`.
```python
def update_s() -> str:
    global s
    s = "hello"
    return s

new_s = update_s()
l: int = new_s.index("o")
print(f"o is at index {l}")
```

**Comment by SteveBenz** [comment]
Ugh, I think my effort at simplifying it were bad.  How about this case.  Even though s must be an instance of my class, because of the assertion, it still doesn't believe s.method() is a thing.

```python
from typing import Optional

class C:
    def method(self) -> str:
        return "hello"

s: Optional[C] = None

# def gf() -> None:
#     global s
#     s = C()

# gf()
if s is not None:
    print(s.method().index("o"))

```

**Comment by erictraut** [comment]
In this case, `s` has a declared type of `C | None`, but its type is narrowed to `None` because of the assignment. The type analyzer knows that the `if` condition will never evaluate to True in this case because all code paths that lead to the `if` have assigned a value of `None` to `s`.

**Comment by SteveBenz** [comment]
...and if you uncomment the code, why doesn't it change it's mind?

**Comment by SteveBenz** [comment]
I mean, at the least it should say that the intervening code block *could* have changed `s`, and it should assume that any change to it was within the type constraints, so it should figure if `s` is not `None`, then it must be `C`.

**Comment by erictraut** [comment]
When you say "intervening code block", I presume you're talking about the "def" statement? The "def" statement assigns a local variable `gf` to a function. That's all that happens when the `def` statement is executed. The line `gf()` then makes a call, but the code that runs in response to that call is part of a different execution scope. As I mentioned above, static analyzers do not perform analysis across execution scopes because, in general, that's not possible to do statically. And even in the rare case where it is theoretically possible, it's computationally prohibitive.

**Comment by SteveBenz** [comment]
So, the analyzer is saying "I don't know what the `gf` does, so it does nothing".

But wouldn't it be more correct to say "gf could have done anything to the variables in the global scope"?

Why would it be "computationally prohibitive" to assume that whatever "anything" was, that the variables will still conform to their type hint?  That is, it should say "Well, I don't know how `s` could be anything other than None, but if it is something other than None, it must be a `C` because of the type hint."

**Comment by erictraut** [comment]
The analyzer is saying "I'm going to assume that a function operates on the state passed to it and doesn't have far-ranging side effects". That's a good assumption in almost all cases, and it's a considered a core tenet of well-written software. It's certainly possible to violate that tenet. In Python, almost anything is possible given its truly dynamic nature. That doesn't mean it's a good idea, nor is it something that a static analyzer can or should handle.

A type analyzer certainly could make much more conservative assumptions about type narrowing — effectively assuming that any call (explicit or implied) could change the state of any variable in any scope at any time. But this would be extremely inconvenient for most code. Consider the following:

```python
s: int | None = 1

some_random_call()

# Should we assume that the following line is unsafe because some_random_call
# (or some other function that it happens to call) may have updated the state of `s` and
# assigned it a value of None?
s++

# The "+" operator implicitly calls `__add__`. Should we assume that the implementation
# of `__add__` (or some other function that it happens to call) might reach in and update
# the state of `s`, perhaps assigning a value of None?
a = s + 1
```

**Comment by SteveBenz** [comment]
It's certainly reasonable for a parser to assume no global side effects, and "# type: ignore" is there for times when things go wrong.  However, in this case, it seems to me that it's comparable to this:

```
class D:
    v: Optional[str] = None
 
    def getter(self) -> int:
        if self.v is None:
            return 0
        else:
            return self.v.index("o")
```

The analyzer has no problem with that code - it has no idea what 'v' could be other than what it learns from the type declaration, and yet it's happy to assume that `v` is a `str` if it's not `None`.

Here:

```
s: Optional[C] = None
gf()
if s is not None:
    print(s.method().index("o"))
```

If the analyzer issued a "unreachable code detected" error, then maybe it'd be a consistent story.  But as it is, it's insisting that `s` is something completely outside of it's ken when the type constraint should guide it, as it does with the public-setter.

Although 'global' is poisonous in my opinion too, it's a part of the language specification.  Do you think you could win a fight with the language committee to have it removed?  I think your chances are slim.  It's there, and people are going to (ab)use it, and pylance should deal with it as best it can.  I'm gonna guess that you hold a dim view of public setters.  I know I do.  But nevertheless, it's a part of the language, and both that and global variables are probably driving causes of the success of the language, whether we like it or not.

**Comment by erictraut** [comment]
Your original example is more akin to a property with a getter that modifies internal state and therefore returns a different value if it is called a second time.

Pylance is working as designed here. This isn't a bug. It's making the same assumptions that other Python static type analyzers — and other type analyzers in other languages — make. For example, run mypy on the following code, and it will produces the same results as pylance.

```python
from typing import Optional
s: Optional[str]
s = None

def gf() -> None:
    global s
    s = "hello"

reveal_type(s) # None
gf()
reveal_type(s) # None
```

I could show you the equivalent code in TypeScript, and it would also produce the equivalent result.

You can certainly subvert static analysis if you try hard enough. If you want to benefit from these tools, you should work with them not against them.

**Comment by SteveBenz** [comment]
```python
PS E:\repos\ballsort> type repro3.py
from typing import Optional, final
from typing_extensions import reveal_type

class C:
    @final
    def method(self) -> str:
        return "hello"

s: Optional[C] = None

def gf() -> None:
    global s
    s = C()

reveal_type(s)
if s is not None:
    reveal_type(s)
    print(s.method().index("o"))
PS E:\repos\ballsort> mypy .\repro3.py
repro3.py:15: note: Revealed type is "Union[repro3.C, None]"
repro3.py:17: note: Revealed type is "repro3.C"
Success: no issues found in 1 source file
PS E:\repos\ballsort> 
```

**Comment by erictraut** [comment]
Yes, this is because mypy treats `s: Optional[C] = None` inconsistent with `s: Optional[C]` followed by `s = None`. Pylance and other Python type checkers treat these as the same. But that's unrelated to the issue we're discussing here.

**Comment by debonte** [comment]
@erictraut, I'm curious about one of @SteveBenz's examples from [above](https://github.com/microsoft/pylance-release/issues/2895#issuecomment-1149349812):

Why isn't the last line considered unreachable?

```python
from typing import Optional

class C:
    def method(self) -> str:
        return "hello"

s: Optional[C] = None

if s is not None:                # Pyright says s is None here...
    print(s.method().index("o")) # ...so why isn't this line unreachable?
```

**Comment by erictraut** [comment]
Reachability analysis is generally not informed by type narrowing (although the opposite is true — type narrowing is informed by reachability). The code block in this example is still considered "reachable" from the standpoint of the code flow engine, but the type of `s` is narrowed to `Never` within the block. You'll see this if you hover over `s` or add a `reveal_type(s)` in the line preceding the `print` statement.

**Comment by SteveBenz** [comment]
I'd suggest you give a little more thought to the reachability question.  The version of mypy that I'm using at least doesn't seem to evaluate the "if" block at all if it doesn't think the type condition will be satisfied.  (E.g. blatant type violations unrelated to the condition don't trigger any errors, reveal_type commands do nothing).  So it seems like it's possible to know that the condition will never be satisfied.  In any case other languages (e.g. C#) are capable of reporting conditions like this.

Another thing you should consider is to make your static analyzers validate your assumption - e.g. issue warnings any time you see a global variable modified.  That way you could give a better error message.  I think you'd have to admit that the static analyzer claiming `s` is Never in a context like the following is going to cause confusion:

```python
if s is C:
  s.method_from_c()
```

If there already was a warning about my use of the global, it'd be a whole lot easier to make sense of the problem.  I'll grant that there's a chance I won't see the warnings, but it's better than no chance at all.

You guys work on static analyzers and I'm sure you're big fans.  I've worked on teams on both ends of the spectrum, and you should understand, some of the sloppiest code I've worked on was also the most profitable for its authors.  You never do know.  I try and sell static analyzers everywhere I go.  The biggest pieces of pushback I face is "Too many false-positives!" and "I spend so much time trying to figure out what it's complaining about, and, when I finally do, I discover it's not really a bug!"

If you could make the error message a bit more clear about what's going on here, you'd definitely be making the product easier to sell.
