### ISSUE TITLE
Not getting intellisense in notebooks

### ISSUE THREAD

**Issue by greazer** [microsoft/pylance-release#2896]
Version: 1.68.0-insider (user setup)
Commit: b7faf235467dd56e4a62e52e7f1cacf875b67261
Date: 2022-06-07T18:33:43.014Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.25131

Jupyter: v2022.6.1001601017 (prerelease)
Pylance: v2022.6.0

1. Create a new notebook
2. Create a cell
3. Enter 
```python 
import numpy as np
np.r
```
On pressing "r" I expect to see autocompletions that includes "random". I do not.

Stable works fine.

**Comment by rchiodo** [comment]
How long did you wait? The screenshot looks like pylance hasn't loaded yet. There's no colorization.

It works for me if I wait for the colorization to appear:

![image](https://user-images.githubusercontent.com/19672699/172667717-9fdaf811-3d44-4f73-a2ef-7bfbf0b5b3be.png)

**Comment by rchiodo** [comment]
This is what it looks like before pylance starts up:

![image](https://user-images.githubusercontent.com/19672699/172667985-8e304253-2c9f-4f2b-8cc6-4710c8b5edbe.png)

**Comment by debonte** [comment]
> They're going to want logs for the language server. Additionally did you end up in the experiment for the "python.pylanceLspNotebooksEnabled" setting.

@rchiodo thanks for requesting logs. The Pylance log will show the experiment state fwiw.

**Comment by debonte** [comment]
@greazer, are you still seeing this? Does it resolve on its  own if you wait for Pylance to finish initializing, as Rich suggested above? If not, please provide logs.

**Comment by debonte** [comment]
@greazer, ping?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
