### ISSUE TITLE
Add support to Pytest "skipif" fixture in order to avoid false positive reports

### ISSUE THREAD

**Issue by Delgan** [microsoft/pylance-release#2902]
Hi.

I don't know how feasible it is, but I would like to report some false positive while combining `if` condition with Pytest `skip()` functions.

I'm testing a library with conditional dependency, and the test cases look like that:

```python
import os

import pytest


def test_a():
    if os.name == "nt":
        import windows_only_lib
        windows_only_lib.do_something()


def test_b():
    if os.name != "nt":
        pytest.skip(reason="Windows only test")

    import windows_only_lib
    windows_only_lib.do_something()


@pytest.mark.skipif(os.name != "nt", reason="Windows only test")
def test_c():
    import windows_only_lib
    windows_only_lib.do_something()
```

On Linux, it's displayed like this in VSCode using Pylance v2022.1.3:

![2022-06-09-152358_1920x1080_scrot](https://user-images.githubusercontent.com/4193924/172857893-443cb6cf-913a-4f76-9246-7f53b3bd1bde.jpg)

The main problem is that it reports the following warnings inside `test_b()` and `test_c()`:

```
Import "windows_only_lib" could not be resolved
Pylance (reportMissingImports)
```

That would be very nice if the warnings could be ignored as for `test_a()` due to the conditional `skip`. Is it even possible?

**Comment by erictraut** [comment]
The static type analyzer doesn't know about the internal semantics or behaviors of the pytest `skipif` function, so skipping this warning automatically isn't possible.

If you want to suppress the warning, you can do one of the following:
1. Add a `# pyright: reportMissingImports=false` comment to the top of the file. This will suppress all diagnostics of that type for the entire file.
2. Add a `# type: ignore` or `# pyright: ignore[reportMissingImports]` comment to the end of that line to suppress a single diagnostic.
