### ISSUE TITLE
Failed to complete the word when type a few letters of the word.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#2905]
## Environment data
![image](https://user-images.githubusercontent.com/59192491/173011745-eea6b913-1f1e-44ed-8fbd-c5c65dd2aec0.png)

## Repro Steps
![image](https://user-images.githubusercontent.com/59192491/173012446-89f67aba-f503-43c7-847a-5d4893aa2738.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/59192491/173012061-9edc6bb7-2bf0-44df-9706-1df6538f8845.png)
When type "ctxt", failed to find "Context"
![image](https://user-images.githubusercontent.com/59192491/173012203-de835ea8-44f6-4646-8563-24a701e5189a.png)

**Comment by debonte** [comment]
Is this a regression or a feature request?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
