### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zemogsirhc** [microsoft/pylance-release#2907]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2022.6.10`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/CHRIST~1/AppData/Local/Temp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
