### ISSUE TITLE
Import "zoautil_py" could not be resolvedPylancereportMissingImports

### ISSUE THREAD

**Issue by fupyCo** [microsoft/pylance-release#2908]
Not sure why This error is popping why trying to execute

Import "zoautil_py" could not be resolvedPylance[reportMissingImports]

any advice?

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
