### ISSUE TITLE
Suggest more sources for auto imports

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#291]
Hi! The feature that allows to import things automatically while typing is super cool! However, in my opinion, there is one case where it can be improved even further.

I experienced the issue when using the feature when using my library (as a third-party module): https://github.com/Yura52/zero
The library contains the `zero/all.py` module that is designed specifically for importing things without producing many lines. However, the auto-import feature suggests imports only from submodules (such as `zero.io`), where entities are actually implemented. Instead, I would prefer importing them from `zero.all`.

**Comment by heejaechang** [comment]
currently, in the next release, "from m import *" form is not considered, but "from m import t as t" is considered when choosing what to show in completion for auto import.

but let me play with it and see how much it affects our auto-import experiences.

**Comment by jakebailey** [comment]
Note that the new heuristic wouldn't help for this case, as `zero.all` is not shorter (in length or module dots) than `zero.io`. Usually re-exports are things like "np.array is actually np.core.some._long_compiled_module", for example.

**Comment by heejaechang** [comment]
we should both actual definition and best 1 import alias, so zero.all will at least show up.

**Comment by ain-soph** [comment]
I agree with this issue. I think we should certainly improve it. Hope this issue priority could be more urgent.

**Comment by heejaechang** [comment]
now, "python.analysis.indexing" became a real option. Set "python.analysis.indexing": true to enable indexing which will improve auto-import experience.

Also, new hidden option "python.analysis.packageIndexDepths" is added which can be used as below to control how much get indexed.

> "python.analysis.packageIndexDepths": [['sklearn', 2],['matplotlib', 2]],

by default, only 1 level module of third party libraries will be indexed, but now, you can use ["package name", module levels to be scanned] to control that.

if you put "" to package name, then that will affect all packages.

for your example, ["zero", 2] will make all.py to be picked up.

thank you

**Comment by bschnurr** [comment]
This issue has been fixed in version 2022.1.3, which we've just released. You can find the changelog here:  [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202213-21-january-2022)

**Comment by abraaoz** [comment]
Even with the update, which introduces `python.analysis.indexing` with `true` as default, you MUST add `"python.analysis.includeAliasesFromUserFiles": true` to your settings.json. Otherwise, the import suggestions will not show the import from __init__.py (__all__), as per https://code.visualstudio.com/docs/python/settings-reference#:~:text=includeAliasesFromUserFiles
