### ISSUE TITLE
Auto completion doesn't work by importing  3rd  part library 

### ISSUE THREAD

**Issue by Seant1125** [microsoft/pylance-release#2912]
Issue Type: <b>Bug</b>

I created a virtual environment and imported requests library, and found auto completion could not  work. I also edited setting json as  belows:
{
    "diffEditor.renderSideBySide": false,
    "explorer.confirmDelete": false,
    "editor.fontSize": 14,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "python.languageServer": "Pylance",
    "python.autoComplete.extraPaths": [
            "/home/sean/prawlerenv/lib/python3.10/site-packages"
    ],
    "python.analysis.extraPaths": [
        "/home/sean/prawlerenv/lib/python3.10/site-packages"
    ],
    "python.analysis.completeFunctionParens": true
}

Extension version: 2022.8.0
VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:49:57.055Z)
OS version: Linux x64 5.17.13-300.fc36.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2563)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.58GB (0.75GB free)|
|Process Argv|--unity-launch --crash-reporter-id 279aa6f7-e15b-477f-870c-be50e4ea0cde|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by heejaechang** [comment]
@Seant1125 can you provide us sample code or repro steps? I just tried 

```
import requests

requests. <=  here
```

and it works as expected.

**Comment by Seant1125** [comment]
import requests
my_cookies = ''
jar = requests.cookies.RequestsCookieJar()
for cookie in my_cookies.split(';'):
    key, value = cookie.split('=', 1)
    jar.set(key, value)
print(jar, '\n\n')



-----Original Message-----
From: Heejae Chang ***@***.***>
Reply-To: microsoft/pylance-release
***@***.***>
To: microsoft/pylance-release ***@***.***>
Cc: Seant1125 ***@***.***>, Mention
***@***.***>
Subject: Re: [microsoft/pylance-release] Auto completion doesn't work by
importing 3rd part library (Issue #2912)
Date: Mon, 13 Jun 2022 10:48:39 -0700


@Seant1125 can you provide us sample code or repro steps? I just tried
import requests

requests. <=  here
and it works as expected.
―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by debonte** [comment]
Not sure if this is what @Seant1125 was referring to, but Pylance reports an error in his sample code:

```python
import requests

my_cookies = ''
jar = requests.cookies.RequestsCookieJar() # "cookies is not a known member of module"
```

This works though:

```python
from requests import cookies

my_cookies = ''
jar = cookies.RequestsCookieJar()
```

Is this by design?

**Comment by judej** [comment]
Yes, this is by design. If `requests` had imported `cookies` like below, it would have worked

`import cookies as cookies`

**Comment by bschnurr** [comment]
see https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface
