### ISSUE TITLE
support suggestion when debugging.

### ISSUE THREAD

**Issue by byehack** [microsoft/pylance-release#292]
```python
a = []
a.append('string')
b = a[0]
```

in debugging when hover on `b` we can see `'string'`. but when write `b.` it doesn't show StringClass methods and attributes.

**Comment by erictraut** [comment]
@byehack, I presume that your sample is meant to say `b = a[0]`. 

You haven't included any type annotations in this code, so Pylance attempts to use type inference to determine the type of `a` and `b`. Its inference for `a` is based on the assignment `a = []`, which does not provide any information about the type contained within the list, so Pylance infers the type of `a` to be `List[Any]`. Its inference for `b` is based on the assignment `b = a[0]`, and `b` is inferred to have type `Any`.

This is a situation where you will need to provide a type annotation to get the behavior you're looking for. You can provide one for either `a` or `b` (or both).

```
a: List[str] = []
a.append('string')
b = x[0]
```
or
```
a = []
a.append('string')
b: str = x[0]
```

**Comment by jakebailey** [comment]
Note that debugging means VS Code is going to ask the debugger for the values, and can offer a different experience. This is similar to (and more powerful than) using notebooks with IPython.

**Comment by byehack** [comment]
@erictraut thanks for reply

i mean can't you add option to suggest on type from real value in debugging?

**Comment by jakebailey** [comment]
The language server has no knowledge of anything but the files themselves, and has no idea what debugging is or how it would access it.

Additionally, you can't write code during a debugging session without the debugger going out of sync, so the LS will think one thing and the debugger will think another, and the types that a type checker reads statically do not have to match the actual types in a running program (e.g., the source may say it's a Protocol, but protocols don't "exist", they just describe a value that has certain methods/properties).

There's some discussion on how to reconcile something like a notebook kernel and a static type checker (where you are naturally in an environment where you can edit and run at the same time), but I can't think of any solution that would make this feasible for a debugging session...

**Comment by byehack** [comment]
> but I can't think of any solution that would make this feasible for a debugging session...

it would be great if debugpy could connect to LSP for povide suggestion.
but if you sure this can't be happening you can close this issue.
i will leave this issue open for doing on later time.

**Comment by jakebailey** [comment]
I'm going to close this; I don't think we're going to be calling out into the debugger to gain extra type information.
