### ISSUE TITLE
Where does function signature IntelliSense come from if there are no type annotations?

### ISSUE THREAD

**Issue by AaronBeaudoin** [microsoft/pylance-release#2928]
If I import the `requests` Python library (for example) and hover over `requests.get` I see this:

![image](https://user-images.githubusercontent.com/26592486/173636559-f67645c7-ddc6-40b9-8020-ed4555ee594a.png)

The function signature arguments and types are described completely.

Now, if I <kbd>Ctrl</kbd>+<kbd>Click</kbd> on the `get` method, I am taken to my local `<python-dir>/site-packages/requests/api.py` file where the function is defined and exported from. If I hover over the `get` function **there** I see the following **much less descriptive** function signature:

![image](https://user-images.githubusercontent.com/26592486/173636529-d77b118a-e9f6-4066-b225-b824da1cd45f.png)

It still has the docstring, but all the function signature argument and type information is gone.

I don't see any type annotations in the source there either, so the question is, **where is all that other type information** for the function signature coming from when I hover over it in my own script (in the first screenshot), and how do I add similar information for my own code?

**Comment by debonte** [comment]
The extra info is coming from the requests type stubs. If you right-click on `get` and select `Go to Declaration` it will take you to `api.pyi` in the requests stubs that we get from [typeshed](https://github.com/python/typeshed/blob/master/stubs/requests/requests/api.pyi).

**Comment by debonte** [comment]
@AaronBeaudoin, there's more info on type stubs here: https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md
