### ISSUE TITLE
Pylance 2022.6.10 no longer allows Enum with another mixed-in type

### ISSUE THREAD

**Issue by mikeyk** [microsoft/pylance-release#2930]
<h3> Environment data </h3>

-   Language Server version: 2022.6.10
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda):  Python 3.10 virtual env
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from enum import Enum

class StrEnum(str, Enum):
  HELLO = "hello"
  OK = "ok"
```

Note that this is the order suggested by the [Python docs](https://docs.python.org/3/library/enum.html).

<h3> Expected behavior </h3>

No pylance warning given for snippet above.

<h3> Actual behavior </h3>

As of the 2022.6.10 release, this now reports:
```
The metaclass of a derived class must be a subclass of the metaclasses of all its base classes
```

2022.6.11 pre-release exhibits the same issue. This previously worked in 2022.6.0.

**Comment by erictraut** [comment]
I'm not able to repro the problem, and I can't think of any reason why this behavior would have changed recently.


Is it possible that you have a custom `enum` module or stub installed? If you right click on `Enum` and choose "Go to Declaration", where does it take you?

**Comment by mikeyk** [comment]
Ah, that was exactly it @erictraut; our local version of typeshed had worked until the latest Pylance update and then the combination started showing that metaclass error; updating typeshed definitions fixes the issue on latest Pylance. Thank you!
