### ISSUE TITLE
 Operator "<=" not supported for types "Timestamp" and "Series[Timestamp]"

### ISSUE THREAD

**Issue by timovp** [microsoft/pylance-release#2933]
<h3> Environment data </h3>

-   Language Server version: 2022.6.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8.8 / 3.8.10
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import pandas as pd

df =  pd.DataFrame(['2020-01-01','2019-01-01'],columns='date')
dates = pd.to_datetime(df['date'], format = '%Y-%m-%d')
date_to_compare = pd.to_datetime('2019-02-01', format = '%Y-%m-%d')
date_mask = date_to_compare <= dates # Operator "<=" not supported for types "Timestamp" and "Series[Timestamp]"
```

<h3> Expected behavior </h3>

userstand that this expression results in a boolean series, which is used to do boolean indexing for pandas dataframes. 
i.e. `df.loc[date_mask,:]`

<h3> Actual behavior </h3>
hovering over the variable shows : 

`(variable) date_mask: Unknown`

and "problems" tab tells: ```[{
	"resource": "/home/nlpraag2/projects/bktool/hello_world.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportGeneralTypeIssues",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 8,
	"message": "Operator \"<=\" not supported for types \"Timestamp\" and \"Series[Timestamp]\"\n  Operator \"<=\" not supported for types \"Timestamp\" and \"Series[Timestamp]\"",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 13,
	"endLineNumber": 8,
	"endColumn": 37
}]```
<h3> Logs </h3>

```
what logs could be helpfull (paste all results in overflow of maximum characters ? 
```
Hope this helps

**Comment by gramster** [comment]
There will be a new release of Pylance today which will have pandas stubs from https://github.com/pandas-dev/pandas-stubs; if this is still an issue after you have that release, please open an issue there.
