### ISSUE TITLE
Pylance stops working on tensorflow

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/pylance-release#2935]
VS Code version: Version: 1.68.0
Jupyter Extension version: v2022.5.1001601848
Python Extension version: v2022.8.0
OS: Mac and version: Monterey 12.4
Python: 3.9.13
Jupyter server running: Local

Auto-completion was working just fine a few moments ago, then suddenly stopped working in a python  script file. 

I specifically changed codes from the example online to 

```
dataset = keras.utils.get_file("aclImdb_v1.tar.gz", url, untar=True, 
                               cache_dir='.', cache_subdir='')
```
because autocompletion does not work for `tf.keras.` but `import tensorflow.keras as keras` works. 

<img width="650" alt="image" src="https://user-images.githubusercontent.com/4111978/173872888-121f2444-4db3-476c-a7b0-0b08770f930e.png">

However, the autocompletion still worked in the jupyter notebook, but the same warning message appeared too. 

<img width="881" alt="image" src="https://user-images.githubusercontent.com/4111978/173875866-5ac0d9f9-4b9a-4728-9b14-6cad8c8b4c3e.png">

**Comment by Fred-Wu** [comment]
I experimented a little bit.  
After I changed to another folder and retried it, it worked again. 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/4111978/173991758-8a5f2c11-970a-437a-b82a-65ab28b42302.png">

However, the issue is still there if I am working in the folder I have run tensorfow.

**Comment by ynorz** [comment]
I have the exact same problem. Any fix?

**Comment by bschnurr** [comment]
see https://github.com/microsoft/pylance-release/issues/1941#issuecomment-1022430663 for keras workarounds
