### ISSUE TITLE
Period and open paren should insert currently selected IntelliSense completion

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#2946]
From C# in Visual Studio and TypeScript in VS Code, I'm used to being able to use `.` and `(` to insert IntelliSense completions, but this doesn't work in Pylance. 

The workaround is to use tab or enter instead, but I find this much less natural given my past experience in other languages.

### Period scenario
1. Create a Python file
2. Add
```python
from datetime import datetime
```
3. Type `da`
4. See that the IntelliSense completion for `datetime` is selected
5. Press `.` with the intention to follow that with `now()`

**Expected:** `datetime.` is inserted and the caret is after the period. We continue typing `now()` to complete our intended call to `datetime.now()`.

**Actual:** IntelliSense is dismissed and we're left with `da.` with the caret after the period throwing off our typing flow.

### Open paren scenario
1. Create a Python file
2. Type `pri`
4. See that the IntelliSense completion for `print` is selected
5. Press `(` with the intention of following that with `"hello"`

**Expected:** `print()` is inserted and the caret is between the parens. We continue typing `"hello")` to complete the intended print call.

**Actual:** IntelliSense is dismissed and we're left with `pri()` with the caret between the parens throwing off our typing flow.

I believe period and open paren are the most common characters used this way, but there are others that may also make sense. For example, '[' also works this way in C# for convenience when indexing into collections.

**Comment by heejaechang** [comment]
we need to support commit chars - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionOptions

either common to all items or per completion list or per completion item. since we have auto parent functionality, we need to update that figure not to mess up with ( or [ if we accept those as commit char.

see LSP spec for more detail.

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.7.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022731-13-july-2022)

**Comment by byehack** [comment]
doesn't work when "python.analysis.completeFunctionParens" enabled.

**Comment by wanzhiyu** [comment]
> doesn't work when "python.analysis.completeFunctionParens" enabled.

doesn't work no matter "python.analysis.completeFunctionParens" enabled or disabled.

**Comment by heejaechang** [comment]
currently, this only works with prerelease bit. and unfortunately, due to some limitation, we can't enable it when completeFunctionParens is enabled.

**Comment by byehack** [comment]
> currently, this only works with prerelease bit. and unfortunately, due to some limitation, we can't enable it when completeFunctionParens is enabled.

@heejaechang 
isn't stable yet?
