### ISSUE TITLE
"Parameter" is not exported from module "torch.nn"

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#2953]
## Environment data

- macOS: 11.6
- VSCode: 1.68.1
- Pylance: v2022.6.20

I am working on [this](https://github.com/Yura52/rtdl) repository. So, my environment can be reproduced as follows:

```
# you can use conda instead of micromamba, the result is the same
micromamba create -n rtdl python=3.7
micromamba activate rtdl
pip install numpy=1.18.5 torch=1.7.1 scikit-learn=1.0.2
pip install -r requirements_dev.txt
```

## Code Snippet

Create a file `rtdl/a.py` with the following content:
```python
import torch.nn as nn

nn.Parameter
```

## Expected behavior

I expect no warnings and no red underlines regarding `nn.Parameter`. mypy agrees with me and does not complain about this file.

## Actual behavior

The `nn.Parameter` is underlined in red. Interestingly, when I hover over it, I see the correctly inferred docstring, but in the end at also contains the following error message: `"Parameter" is not exported from module "torch.nn" Pylance (reportPrivateImportUsage)"`

## Logs

The logs are going beyond the GitHub limits :( If they are needed, what are the relevant parts that I should provide?

**Comment by Yura52** [comment]
I have just checked that the issue can be reproduced with the latest torch 1.11.0 as well (1.11.0).

**Comment by bschnurr** [comment]
torch==1.11.0 worked for me on windows.
i'll try linux

**Comment by Yura52** [comment]
Just in case, here is the illustration:

<img width="661" alt="Screenshot 2022-06-19 at 16 57 29" src="https://user-images.githubusercontent.com/8861742/174656974-5aa8d15d-0228-405b-b67b-37f8e16aa9a4.png">

**Comment by linminhtoo** [comment]
I get the same error as well. 

I'm on `nixos`
```
Python 3.9.12 (main, Mar 23 2022, 21:36:19) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.11.0+cu113'
```

**Comment by Yura52** [comment]
> couldn't repro on linux. any luck on your side?

nope, and in fact I have been experiencing this issue for a long time

**Comment by erictraut** [comment]
Torch is a "py.typed" library which means it contains inlined type information.

When a library is marked "py.typed", pyright (the type checker that underlies pylance) applies certain rules to determine whether specific symbols are intended to be visible from a module. These rules are documented [here](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface).

The module `torch/nn/__init__.py` imports the `Parameter` symbol, but it does not indicate that this symbol should be re-exported — and therefore made visible externally. To do so, it would need to use a redundant form of import: `from .parameter import Parameter as Parameter`. If you manually make that change in the `torch/nn/__init__.py` file, you'll see that `nn.Parameter` no longer generates an error.

If you believe that `Parameter` is meant to be visible from the `torch.nn` module, then this is a bug in the torch library, and you should report it to the torch maintainers.

As a workaround, you can access the `Parameter` symbol through the module that defines it: `nn.parameter.Parameter`.

You can also configure pylance to disable the `reportPrivateImportUsage` diagnostic rule, effectively silencing this error.

**Comment by Yura52** [comment]
Thank you for the detailed answer! I created [the issue](https://github.com/pytorch/pytorch/issues/80433) in the PyTorch repository.

P.S. Is the approach `from .parameter import Parameter as Parameter` expected to declare public interface  by convention in Python or is it just a Pylance-specific workaround? To me it looks like the "portable" solution would be to explicitly create the `__all__` variable.

**Comment by erictraut** [comment]
This approach was standardized in PEP 484 for type stubs. It hasn't been officially adopted in a PEP for "py.typed" libraries, but there is general consensus among type checker authors that it makes sense to use the pattern established by PEP 484. This guidance has been posted on the [python/typing site](https://github.com/python/typing/blob/master/docs/source/libraries.rst).

The `__all__` variable designates "symbols that should be imported by a wildcard import", so it often overlaps with the notion of "symbols that are meant to be publicly visible from a module", but there are cases where the former is a subset of the latter.

**Comment by erictraut** [comment]
> Is this that still the convention anymore?

This has now been formalized and added to the Python typing spec. See [here](https://typing.readthedocs.io/en/latest/spec/distributing.html#library-interface-public-and-private-symbols).
