### ISSUE TITLE
Pylance plug-in caused incomplete auto-completion

### ISSUE THREAD

**Issue by stfujnkk** [microsoft/pylance-release#2955]
There was **no prompt** for ContentHandler when I imported the xml.sax package. It worked after I **disabled Pylance**

## Environment data

Pylance `v2022.6.20`

Python: `3.9.12`

VsCode: `1.68.1 (user setup)` 

Language Server version: `2022.6.20 (pyright 979d9c9e)` 

OS :`Windows_NT x64 10.0.19043`

## Expected behavior

![2](https://user-images.githubusercontent.com/52458236/174515503-92410b3d-9048-4e9b-903e-f717b7c86a77.png)

## Actual behavior

![1](https://user-images.githubusercontent.com/52458236/174515454-29a870a7-d04f-4dd3-ab51-41f627faf175.png)

## Logs
The log when I enter a period
```log
(16724) [FG] completion at c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py:3:8 ...
(16724) [FG]   parsing: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (0ms)
(16724) [FG]   binding: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (0ms)
(16724) [FG] completion at c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py:3:8 [found 23 items] (3ms)
(16724) Background analysis message: setFileOpened
(16724) Background analysis message: markFilesDirty
(16724) Background analysis message: analyze
(16724) [BG(3)] analyzing: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py ...
(16724) [BG(3)]   parsing: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (0ms)
(16724) [BG(3)]   binding: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (0ms)
(16724) [BG(3)]   checking: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (3ms)
(16724) [BG(3)] analyzing: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (3ms)
(16724) Background analysis message: resumeAnalysis
(16724) [BG(3)] indexing: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py [found 0] (0ms)
(16724) Indexing Done: c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py
(16724) Background analysis message: getDiagnosticsForRange
(16724) Background analysis message: getDiagnosticsForRange
(16724) Background analysis message: getSemanticTokens delta
(16724) [BG(3)] getSemanticTokens delta previousResultId:1655692870684 at c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py (1ms)
(16724) Background analysis message: getDiagnosticsForRange
(16724) Background analysis message: getDiagnosticsForRange
[Info  - 10:41:18] (16724) SourceFile: Received fs event 'change' for path 'c:\Users\stfujnkk\Desktop\work_space\python\autoTest\main.py'
(16724) Background analysis message: markFilesDirty
(16724) Background analysis message: analyze
```

**Comment by erictraut** [comment]
The type information that pylance uses for `xml.sax` comes from the [typeshed project](https://github.com/python/typeshed/blob/master/stdlib/xml/sax/__init__.pyi). It indicates that `ContentHandler` is not exported directly from `xml.sax` but is instead available only through the submodule `xml.sax.handler`. If you think this is an error, please consider opening a bug report in the typeshed project. Pylance and other static type checkers within the Python community all consume these typeshed stubs.

**Comment by stfujnkk** [comment]
The most important thing is that after I disabled the Pylance plug-in, it worked normally.
What I mean is that this plugin **interferes** with the [ms-python.python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) plugin working properly.

**Comment by erictraut** [comment]
The Typeshed stub indicates that the symbol `ContentHandler` is not re-exported from the `xml.sax` module. If it is intended to be re-exported from that module, the type stub would need to use a redundant import form to indicate this.

```python
from xml.sax.handler import ContentHandler as ContentHandler
```

Without that redundant form, `ContentHandler` is considered a private import, and pylance will not recommend it for completion. The behavior of type stubs is specified in PEP 484, and pylance is following the specification here.

If you think that `xml.sax` is intended to re-export the symbol `ContentHandler`, then you can file a bug or a PR with the typeshed project.
