### ISSUE TITLE
Pylance/pyright is not running in IPythonMode

### ISSUE THREAD

**Issue by fungiboletus** [microsoft/pylance-release#2963]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I wrote a notebook that uses a top level await, which is allowed in ipython jupyter notebooks.

However, pylance warns me about an error that is not relevant:

```
"await" allowed only within async function Pylance
```

But if I read the source code of pyright, [I can see that pyright has an `IPythonMode` boolean to not wrongly trigger this error](https://github.com/microsoft/pyright/blob/794d151050bae95e34a04edae85338a6420ded36/packages/pyright-internal/src/analyzer/binder.ts#L1421-L1423).

I'm not an expert at all in python or jupyter, but it seems that the `IPythonMode` is not set to `true` when running in `vscode-jupyter`.

### VS Code Version

Version: 1.68.0 Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f Date: 2022-06-08T11:43:24.900Z (1 wk ago) Electron: 17.4.7 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Darwin arm64 21.5.0

### Jupyter Extension Version

v2022.5.1001601848

### Jupyter logs

```shell
/
```

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by heejaechang** [comment]
with https://github.com/microsoft/pyrx/pull/2570, regardless which experiment group you are in, it should work as expected in next release.

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.7.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022721-6-July-2022)

**Comment by fungiboletus** [comment]
Thanks 😊
