### ISSUE TITLE
Type str is incompatible with Literal from string

### ISSUE THREAD

**Issue by Werni2A** [microsoft/pylance-release#2964]
## Environment data

-   Language Server version: v2022.6.30
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Code Snippet

```python
from typing import Literal

ArgT = Literal["foo", "bar"]

class Parent:
    def test(self, arg: str) -> None:
        pass


class Child(Parent):
    def test(self, arg: ArgT) -> None:
        pass


if __name__ == "__main__":
    child = Child()
    child.test("foo")
```

## Repro Steps

1. Copy code example to VsCode with Pylance installed

## Expected behavior

IMO `str` and `Literal["foo", "bar"]` should be exchangeable (though not sure what the Python standard thinks), therefore do not report an error.
 
Other linters like prospector do not report this issue.

## Actual behavior

Pylance reports

```text
Method "test" overrides class "Parent" in an incompatible manner
  Parameter 2 type mismatch: base parameter is type "str", override parameter is type "ArgT"
    Type "str" cannot be assigned to type "ArgT"
      "str" cannot be assigned to type "Literal['foo']"
      "str" cannot be assigned to type "Literal['bar']"
```

**Comment by erictraut** [comment]
You have apparently enabled the strict-mode check `reportIncompatibleMethodOverride`. This check is correctly pointing out that you are overriding the method `test` in an incompatible manner. This is dangerous and can lead to bugs.

```python
from typing import Literal
ArgT = Literal["foo", "bar"]

class Parent:
    def test(self, arg: str) -> None:
        pass

class Child(Parent):
    def test(self, arg: ArgT) -> None:
        assert arg == "foo" or arg == "bar"

def func(v: Parent):
    v.test("not foo!")

if __name__ == "__main__":
    func(Child())
```

So the check is working as intended. If you don't want to use this strict-mode check, you can disable it.

**Comment by Werni2A** [comment]
Thank you for the counter example and the fast feedback.

This makes sense.
