### ISSUE TITLE
Feature: code operations for inlay hints

### ISSUE THREAD

**Issue by yanyongyu** [microsoft/pylance-release#2970]
Inlay hints is a good feature for showing function and variable types. If it canbe just place in code with code operations like which `vscode rust support` provided (code operation `insert explicit type`), it will be great!

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.7.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022741-20-July-2022)
