### ISSUE TITLE
Investigate if we need to watch everything in `sys.path`

### ISSUE THREAD

**Issue by karrtikr** [microsoft/pylance-release#2975]
Follow up from https://github.com/microsoft/pylance-release/issues/2914#issuecomment-1166390438, opened this issue to review what is being watched and see if we could be smarter about it. For eg. if the intention is to watch for installed modules, see if we can watch where it's generally installed instead; if we can restrict the pattern we watch for etc.

cc/ @judej

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/issues/2974

**Comment by karrtikr** [comment]
Doesn't look to me like a dup, as this focuses on what should be watched.
