### ISSUE TITLE
Import "tensorflow" could not be resolvedPylancereportMissingImports

### ISSUE THREAD

**Issue by Nactydbug** [microsoft/pylance-release#2980]
I have tried uninstalling all extensions and imports but still gets this error

**Comment by bschnurr** [comment]
see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue for how to grab the logs.

are you using open folder?
selected your python interpreter with tensorflow installed?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
