### ISSUE TITLE
Generic type parameters don't work with Union types

### ISSUE THREAD

**Issue by ElijahSink** [microsoft/pylance-release#2984]
## Environment data

-   Language Server version: v2022.6.30
-   OS and version: Windows 11: 10.0.22000 Build 22000
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.5

## Code Snippet

```python
from typing import Type, TypeVar, Union, cast

T = TypeVar("T")

Foo = Union[int, str]

"""
(type alias) Foo: Type[int] | Type[str]
Expression of type "Foo" cannot be assigned to parameter of type "Foo | Type[T@bar]"
  Type "object" cannot be assigned to type "Foo | Type[T@bar]"
    Type "object" cannot be assigned to type "Type[T@bar]"
    Type "object" cannot be assigned to type "Type[int]"
    Type "object" cannot be assigned to type "Type[str]"Pylance(reportGeneralTypeIssues)
                               vvv"""
def bar(return_type: Type[T] = Foo) -> T:
    return cast(T, "")

spam = bar(str)  # (variable) spam: Unknown
```

## Expected behavior

No type error should be raised, and `spam` s type should be recognized as `str`, not `Unknown`.

## Actual behavior

Error is raised, and `spam`'s type is not inferred.

## Logs

```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'pythonSurveyNotification' is active
Experiment 'PythonPyTorchProfiler' is active
LSP Notebooks experiment is disabled -- not in treatment group
> conda info --json
Python interpreter path: /usr/bin/python
> ~/.pyenv/versions/3.9.13/bin/python ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/interpreterInfo.py
> /bin/python ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/interpreterInfo.py
> /sbin/python ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/interpreterInfo.py
> /usr/sbin/python ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2022.8.1/pythonFiles/interpreterInfo.py
Starting Pylance language server.
```

**Comment by erictraut** [comment]
There are a couple of problems with your code here.

First, `Foo` is a type alias. At runtime, it is a `typing.Union` object. Normally unions are used only in type annotations because it is a special form that has no meaning in value expressions. But you are attempting to use this `typing.Union` object as a default argument value for parameter `return_type`. I presume that's not what you intend to do here. Perhaps you meant to use `int` as the default argument?

```python
def bar(return_type: Type[T] = int) -> T: ...
```

Or perhaps your intent was to constrain `T` to be either `int` or `str` but then default to one of them?
```python
T = TypeVar("T", int, str)
def bar(return_type: Type[T] = int) -> T: ...
```

Second, assigning default arguments for a parameter defined with a TypeVar is problematic from a type safety standpoint. Other type checkers like mypy don't allow this at all. Pyright (the type checker that pylance is built upon) allows it, but it is very restrictive in what it allows. The recommended approach here is to use an overload.

```python
T = TypeVar("T", int, str)

@overload
def bar(return_type: type[T]) -> T: ...
@overload
def bar() -> int: ...
def bar(return_type: type = ...) -> object:
    return return_type
```

**Comment by ElijahSink** [comment]
I think I understand your point. My intent is to create a function which functions something like a type guard. You pass in some value, you pass in a type, and you get assurance that the return value from the function is the type you wanted. 
```py
def ensure_type(val: Any, _type: Type[T]) -> T:
    ... # do type checks at runtime
    return val
```
But with this particular function, I don't want the user to have to specify `_type` every time when there is a particular one that is used nearly every time. It's a custom `Union` type.

I'm surprised that a custom `Union` type alias isn't treated as a first-class type here.

I do think the overloading workaround is suitable for my case:
```py
@overload
def ensure_type(val: Any, _type: Type[T]) -> T: ...
@overload
def ensure_type(val: Any) -> CustomUnion: ...
def ensure_type(val: Any, _type: Type = CustomUnion) -> object: # is object significant here vs omitting the return type?
    # runtime typechecks
    return val
    

```
