### ISSUE TITLE
Imports consumed in later cells flagged as unused with LSP notebooks

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#2986]
This was reported via a [Marketplace review](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance&ssr=false#review-details):
>When I use Jupyter notebook and put the imported modules in a separate cell, Pylance always shows "module not used/module not accessed" despite the fact that they are used in the cells below. The bug needs to be fixed. (Then I installed old version v2022.5.1, there is no such problem)

This repros when the LSP notebooks experiment is enabled (but not with concat docs) because we aren't checking to see if symbols imported in a cell are used in later cells.

**Comment by debonte** [comment]
These features will be disabled for LSP notebooks in the next release. We don't see any good ways to support these features when LSP notebooks are in use.

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.7.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022721-6-July-2022)
