### ISSUE TITLE
Method overriding template is auto inserted before opening parentheses

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#2987]
## Environment data

-   Language Server version: v2022.6.31 Pre-Release
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13

## Code Snippet

```python
class Base:
    def f(self): ...
class Derived(Base):
    def 
```

## Repro Steps

1. Create a python file, and paste the sample snippet into it.
2. Continue to input "f(" after "def " in the last line.

## Expected behavior

![image](https://user-images.githubusercontent.com/15389744/176815342-924b0cd2-94e7-47b3-ae8d-70ba865ddb11.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/176815307-458e8c7b-c63f-4261-950c-43c1c4b8c30a.png)

**Comment by debonte** [comment]
@Azureblade3808, thanks for the issue! We have released a hotfix to address this.

This issue has been fixed in version 2022.7.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022711-1-July-2022)
