### ISSUE TITLE
Wrong method icon for @property method

### ISSUE THREAD

**Issue by dzpt** [microsoft/pylance-release#299]
While declaring a method as a property with `@property` keyword, it's supposed to have the property icon.
But pylance displays it with method icon, which is wrong.

I've been using `pyright` old version and it works fine without this error.
try the simple code and see the intellisense from screenshot below

## Environment data

-   Language Server version: 2020.8.0
-   OS and version: macOS 10.15.2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.1

## Expected behaviour

Property icon

## Actual behaviour

Method icon

# Screenshot

<img width="459" alt="Screen Shot 2020-08-30 at 11 02 35" src="https://user-images.githubusercontent.com/5781080/91650948-808ba300-eab0-11ea-88a3-cd48fc5dcb6b.png">
<img width="492" alt="Screen Shot 2020-08-30 at 11 02 28" src="https://user-images.githubusercontent.com/5781080/91650949-841f2a00-eab0-11ea-8b0c-9c3e59013084.png">
<img width="402" alt="Screen Shot 2020-08-30 at 11 04 46" src="https://user-images.githubusercontent.com/5781080/91650964-a153f880-eab0-11ea-8981-b3930ead54af.png">

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next version of Pyright and Pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
