### ISSUE TITLE
Pylance can not auto import python modules

### ISSUE THREAD

**Issue by rustam-ashurov-mcx** [microsoft/pylance-release#2991]
## Environment data

-   Language Server version: v2022.6.30
-   OS and version: Windows 10 Pro
-   Python version: Python 3.10.4

- I created a small library (my_library) with an empty __init__.py file in the main module and all sub-modules as well
- py.typed file is added and exists in the package distribution
- my library is used as a dependency in another python project
- we are using VS Code as an IDE with Pylance extension
- all dependencies (including my library) are installed there via python virtual environment
- venv is created via Poetry tool
- venv is chosen for python interpreter in VS Code for type hints, auto-completion, auto imports

## Expected behavior

- I have a MyClass type definition in my library that is located in my_library/my_module_folder/my_class.py
- I put MyClass somewhere in my project code, and click ctrl+.
- VS Code suggests adding auto-import: `from my_library/my_module_folder/my_class.py import MyClass `

## Actual behavior
- VS Code has no suggestions on how to import my class. I can type imports manually and there will be even step-by-step auto-completion, but nothing like it gives for FastAPI for example.

**Comment by heejaechang** [comment]
@rustam-ashurov-mcx can you provide step by step repro steps that we can follow? otherwise, it is hard for us to find out problem you are seeing.

that being said, we do not show every symbols defined in modules in "add imports", that will make the list gigantic. we only show symbols we think public symbols.

one way to do that is putting them in __all__ = [ 'symbol' ]

see [this](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface) for more detail on what is considered as public symbols.

**Comment by rustam-ashurov-mcx** [comment]
So am I right saying, that in case I have a library with a module with an empty __init__.py - there will be no import suggestions given?
Should I put manually public members in the __init__.py files for every module? Or could it be configured that I would like to define all my types public?
The confusing part is, that my VS code gives suggestions when I type manually "from my_lib.some_module import SomeClass", but at the same time if I would like to add usage of SomeClass type in projects code - VS Code doesn't suggest what import could be suitable.

**Comment by heejaechang** [comment]
@rustam-ashurov-mcx by the way, if your intension is making your lib to have good pylance experience for your lib users, yes, all public APIs of your lib should be re-exported from init.py at the root of your library.

**Comment by rustam-ashurov-mcx** [comment]
Many thanks for all the insights @heejaechang. As you suggested, we need to make our library API more meaningful via init files with the declaration of our public members.

**Comment by rustam-ashurov-mcx** [comment]
Btw, @heejaechang do you maybe know is "python.analysis.packageIndexDepths":[["",20, true]] config is compatible with the latest VS Code?
I see that VS Code says in a popup "Unknown Configuration Setting" whenever I add this config to settings.json file, also this config doesn't fix the issue with imports.

**Comment by rustam-ashurov-mcx** [comment]
@heejaechang Many thanks once again, I'm closing the issue 👍

**Comment by nguyenit67** [comment]
I want to add to include this line as well
```json
"python.analysis.autoImportCompletions": true 
```
(its default is false)

**Comment by mperon** [comment]
> Btw, @heejaechang do you maybe know is "python.analysis.packageIndexDepths":[["",20, true]] config is compatible with the latest VS Code?
> I see that VS Code says in a popup "Unknown Configuration Setting" whenever I add this config to settings.json file, also this config doesn't fix the issue with imports.

To me, these settings do the job an fix the problem.

```json
    "python.analysis.autoImportCompletions": true,
    "python.autoComplete.extraPaths": ["${workspaceFolder}/src"],
    "python.analysis.extraPaths": ["${workspaceFolder}/src"],
    "python.analysis.indexing": true,
    "python.analysis.packageIndexDepths": [
        { "name": "", "depth": 20, "includeAllSymbols": true }
    ]
```

**Comment by igorbaryshev** [comment]
> ```json
> "python.analysis.indexing": true,
> ```

Setting this to false actually fixed it for me, very strange behavior.

**Comment by heejaechang** [comment]
@igorbaryshev that's probably because one of your opened files imported the one you want to auto import already transitively.

when `indexing` is off, that is our fallback behavior.

**Comment by BigCat3997** [comment]
> > Btw, @heejaechang do you maybe know is "python.analysis.packageIndexDepths":[["",20, true]] config is compatible with the latest VS Code?
> > I see that VS Code says in a popup "Unknown Configuration Setting" whenever I add this config to settings.json file, also this config doesn't fix the issue with imports.
> 
> To me, these settings do the job an fix the problem.
> 
> ```json
>     "python.analysis.autoImportCompletions": true,
>     "python.autoComplete.extraPaths": ["${workspaceFolder}/src"],
>     "python.analysis.extraPaths": ["${workspaceFolder}/src"],
>     "python.analysis.indexing": true,
>     "python.analysis.packageIndexDepths": [
>         { "name": "", "depth": 20, "includeAllSymbols": true }
>     ]
> ```

Thank you, It ran smoothly.

**Comment by nullbio** [comment]
> > > Btw, @heejaechang do you maybe know is "python.analysis.packageIndexDepths":[["",20, true]] config is compatible with the latest VS Code?
> > > I see that VS Code says in a popup "Unknown Configuration Setting" whenever I add this config to settings.json file, also this config doesn't fix the issue with imports.
> > 
> > 
> > To me, these settings do the job an fix the problem.
> > ```json
> >     "python.analysis.autoImportCompletions": true,
> >     "python.autoComplete.extraPaths": ["${workspaceFolder}/src"],
> >     "python.analysis.extraPaths": ["${workspaceFolder}/src"],
> >     "python.analysis.indexing": true,
> >     "python.analysis.packageIndexDepths": [
> >         { "name": "", "depth": 20, "includeAllSymbols": true }
> >     ]
> > ```
> 
> Thank you, It ran smoothly.

Did not work for me. Is there a way to debug/diagnose the underlying issue here? I'm wondering if it's a conflict with something else, like black formatter, flake8 or isort.

**Comment by debonte** [comment]
@nullbio, this issue has been closed for a long time. Please open a new issue and provide details on what you are seeing and what you expected, ideally with code/packages/config settings that reproduce the behavior. Thanks!

**Comment by nullbio** [comment]
> @nullbio, this issue has been closed for a long time. Please open a new issue and provide details on what you are seeing and what you expected, ideally with code/packages/config settings that reproduce the behavior. Thanks!

No problem, here it is: https://github.com/microsoft/pylance-release/issues/5996
