### ISSUE TITLE
False Positive of "Code is unreachable" Detection

### ISSUE THREAD

**Issue by AAArthurLiu** [microsoft/pylance-release#2992]
## Environment data

-   Language Server version: v2022.8.1
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Code Snippet

```python
def flag(
    name: str,
    value_type: type,
):
    if value_type not in (str, int, float, bool):
        raise Exception('invalid type.')

    return (
        name,
        value_type
    )


a = flag("key", int)


def func():
    print(a)

```

## Expected behavior

All codes reachable

## Actual behavior
![image](https://user-images.githubusercontent.com/19529060/177030516-af454562-255d-424e-a8cb-04dc731e1d82.png)

**Comment by erictraut** [comment]
Thanks for the bug report.

Yes, this is a bug in the type narrowing logic for `in` and `not in` expressions. It requires some special casing for the case where the LHS is `type`. This will be fixed in the next release.

In the meantime, you can work around it by doing one of the following:
1. Change the annotation for `value_type` to `type[Any]`.
2. Add a return type annotation for `flag`: `-> tuple[str, type]`

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.7.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022721-6-July-2022)

**Comment by Elmsroth** [comment]
Hi @heejaechang 
I seems I am facing the same issue.
Pylance says the raise is unreachable but in fact ...no it is reachable if the date_debut_affaire is from another type

```
        # Handle date_debut_affaire
        if isinstance(date_debut_affaire, str):
            if not is_iso_date(date_debut_affaire):
                raise BusinessError(Messages.AFFAIRE_DATE_DEBUT_DOES_NOT_HAVE_EXPECTED_FORMAT)
            date_debut_affaire = date_debut_affaire + "T00:00:00"
        elif isinstance(date_debut_affaire, date):
            date_fin_affaire = format_datetime(date_debut_affaire, date_format_name="iso_date_with_time", date_time_separator="T")
        else:
            raise BusinessError(Messages.API_JSON_PROPERTY_IS_NOT_VALID_TYPE.format(
                property_name ="date_debut_affaire",
                expected_type="date or str"
            ))
```

Do you think it is related ?

**Comment by rchiodo** [comment]
@Elmsroth you should enter a new issue. We'd need the entire source (or at least a sample we can use to reproduce). Your code may have specified the types for `date_debug_affaire` in the function so Pylance will think it can't be anything but a str or a date.
