### ISSUE TITLE
VSCode option to turn off syntax reporting of future Python versions

### ISSUE THREAD

**Issue by laralex** [microsoft/pylance-release#2994]
Hello, I have the following workflow. I remotely connect to a cluster access machine (via VSCode over SSH), where I make changes to my repository. The access machine runs Python 3.4, thus I assume Pylance operates with it to analyze my repo. The issue is that the code that I develop runs on cluster nodes with Python 3.8, and my code extensively uses some of newer Python features like f-strings and type annotations. 

Pylance annoingly complains about "Format string literals (f-strings) require Python 3.6 or newer" at hundreds and hundreads of places of my repository. I haven't found any VSCode option to turn these errors off. It would be great if there was an option like 
```
"python.analysis.diagnosticSeverityOverrides": {
      "reportFuturePythonSyntax": "none",
},
```

**Comment by BerylXavier** [comment]
hellow,  sorry for the errors... well one way to solve the problem is to
install a new version of python this can somehow help and the good thing
about this is that you can install multiple python versions so you can
choose which version you need to run your code

**Comment by laralex** [comment]
@BerylXavier Hi, as I said, I work on a cluster, and managing its software is beyond my control

**Comment by erictraut** [comment]
By default, pyright (the type checker upon which pylance is built) assumes that you are running a version of python that matches the selected python interpreter. You can override this by creating a `pyrightconfig.json` file in the root directory of your project and including { "pythonVersion": "3.8" }. For additional configuration options, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

**Comment by laralex** [comment]
Works like a charm! Though having unrelated files in the project root annoys a bit

**Comment by erictraut** [comment]
If you would prefer to use a `pyproject.toml` file, pyright also supports that.
