### ISSUE TITLE
Turn off `pyright` Linting

### ISSUE THREAD

**Issue by adam-grant-hendry** [microsoft/pylance-release#2995]
I would like to turn off `pyright` linting and use `mypy` exclusively. I like the other features of the `pylance` language server (code formatting, debugging, testing, jupyter notebooks, environments, refactoring, etc.), but I prefer not to use `pyright`.

How can I turn this off?

**Comment by erictraut** [comment]
By default, pylance does not emit any type-related diagnostics. If you have enabled these, you can disable them by setting "python.analysis.typeCheckingMode" to "off".

**Comment by adam-grant-hendry** [comment]
> By default, pylance does not emit any type-related diagnostics.

Isn't the default mode `basic` though?

**Comment by erictraut** [comment]
In pyright the default mode is `basic`, but in pylance the default mode is `off`.

**Comment by akonitx** [comment]
> By default, pylance does not emit any type-related diagnostics. If you have enabled these, you can disable them by setting "python.analysis.typeCheckingMode" to "off".

In my case that does not works, I have set `"python.analysis.typeCheckingMode": "off"` in `settings.json` but still get Pylance linter logs in problem window in VS Code

#### Example: 
```python 
COMMENTS: list[dict[str, str | int]] = [
    {"text": "Great post!", "username": "akonitx"},
    {"text": "I agree!", "username": "kindaway"},
    {"text": "Nice work", "username": "dolfinus"},
# ...
 # Here is missed square bracket (']')
```
##### Problems:
1. "[" was not closed [Pylance]
2. '[' was never closed  [syntax] [Mypy]
3. Expected expression [Pylance]

So how to off `pyright` analysis?

**Comment by rchiodo** [comment]
Pylance/Pyright still needs syntactically correct code for most of the other features to work, so it still checks that. There's no way to turn off syntax errors.

Other errors can be mostly turned off with `typeCheckMode`, but some can still come through, especially if they prevent say completions from working. 

Those other errors can be turned off with individual error settings, like so:

```json
	"python.analysis.diagnosticSeverityOverrides": {
		"reportMissingImports": "none" <-- Set whatever errors you don't want to see to none
	},

```

**Comment by im-n1** [comment]
> There's no way to turn off syntax errors.

Thats quite bad because it prevents usage pyright with other tools like Ruff or so. Since Pyright is very slow it forces users to use it as a whole (and sacrifice speed) or get rid of it and use other (faster) tools.

**Comment by JulianKu** [comment]
@im-n1, I found this workaround [here](https://stackoverflow.com/a/75071893) for the exact same problem of using Ruff VSCode extension and still getting Pylance/Pyright warnings and errors:
```
"python.analysis.ignore": [
        "*"
    ]
```

**Comment by dchandan** [comment]
@JulianKu one issue I've found with this is that it turns off some useful catches like `reportMissingImports` which can help indicate when an imported module is not found. As far as I know I can't catch this error in Ruff (correct me if I am wrong). 

Is there a way to keep `reportMissingImports` (and maybe some others) while turning off all other pyright listing in favour of Ruff?

**Comment by rchiodo** [comment]
> Is there a way to keep reportMissingImports (and maybe some others) while turning off all other pyright listing in favour of Ruff?

As described [here](https://microsoft.github.io/pyright/#/configuration?id=type-check-rule-overrides), you can control individual errors:

```
	"python.analysis.diagnosticSeverityOverrides": {
		"reportMissingImports": "error" 
	},
```

`python.analysis.ignore` ignores everything so if you want to ignore syntax errors but still show other errors, there's no way to do that.

**Comment by dchandan** [comment]
Thank you @rchiodo
