### ISSUE TITLE
Allow ignoring reportMissingImports warning when catching/supressing ModuleNotFoundError

### ISSUE THREAD

**Issue by ivanlonel** [microsoft/pylance-release#2996]
`reportMissingImports` will flag missing imports even if they are not strictly required. It would be useful being able to turn this off when the code hints that the module being imported is optional.

For example, the following code shows two different ways of trying to import `uvloop` without raising an error if it isn't available in the current environment:

```python
import asyncio
import contextlib
import sys

try:
    import uvloop
except ModuleNotFoundError:
    if sys.platform.startswith("win"):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
else:
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

with contextlib.suppress(ModuleNotFoundError):
    import uvloop
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

The fact that `uvloop` can't be resolved is nothing to worry about. It's not even available on Windows. But the imports still get flagged:

![image](https://user-images.githubusercontent.com/15915901/177222874-10838377-3733-4298-bec4-424c94586f9c.png)

**Comment by erictraut** [comment]
There are still good reasons to highlight a missing import in this case. Suppressing the error automatically is probably not the right answer.

If you prefer to suppress these warnings in this case, you can add a `# type: ignore` or `# pyright: ignore[reportMissingImport]` comment on that line.

**Comment by ivanlonel** [comment]
That makes sense. I didn't know about these magic comments. They do solve my problem in a way that seem safer.

Thanks for your quick reply!

Just a heads up, in case someone ends up here for reference in the future, I had to include the `s` at the end of `# pyright: ignore[reportMissingImports]` for it to work. The first comment worked out of the box, tho.

**Comment by cedenoaugusto** [comment]
In my case I have to use # pyright: reportMissingImports=false

**Comment by jace** [comment]
I've found there are four ways to address this within a file:

1. `# pyright: reportMissingImports=false` near the top of the file disables it for the entire file.
2. `# type: ignore` on the line works, but as a general ignore it can mask other problems.
3. `# pyright: ignore` on the line specifically targets Pyright, and may be better if your CI uses Mypy but your editor uses Pyright.
4. `# pyright: ignore[reportMissingImports]` on the line narrows it to ignore the specific error.

**Comment by bhuvnayukesh-sudo** [comment]
for me the problem is there is no module named 

<img width="1950" height="1646" alt="Image" src="https://github.com/user-attachments/assets/2814d213-1558-4fbd-84f3-027325a2a001" />

 pyQt6.Qtcore
