### ISSUE TITLE
Auto-imports should add the import before the code that generated the issue

### ISSUE THREAD

**Issue by gramster** [microsoft/pylance-release#30]
## Environment data

-   Language Server version: 2020.6.1
-   OS and version: MacOS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Expected behaviour

If I enter this code:

```python
gc.

import pandas
```

then go to the `gc.` to do a quick fix for the import, I would expect the import to come before the `gc.` code.

## Actual behaviour

The import is added just before `import pandas`, so I end up with:

```python
gc.


import gc
import pandas
```

If the existing imports are below the location where the new reference occurs, the new import should be added higher up. I guess we add next to the first existing imports but should then special-case this and add the new import at the top of the file.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by heejaechang** [comment]
until we improve the memory/CPU issue with auto-indexing, you need "python.analysis.indexing": true in .vscode/settings.json for add import/auto import feature to be enabled.
