### ISSUE TITLE
Request textDocument/semanticTokens/full failed (vscode.dev)

### ISSUE THREAD

**Issue by softcode589** [microsoft/pylance-release#3000]
The error output looks like this:
![1](https://user-images.githubusercontent.com/108250871/177240349-ce5fb560-3538-4bdd-a7e1-d7b216edbbb6.png)
**vscode.dev issue.**

**Comment by bschnurr** [comment]
is there a public code repo?

**Comment by erictraut** [comment]
The `reading 'startOffset'` in the screen shot is a good clue. The only code path in pylance that appears to access a field with that name is in the signature help provider, not in the semantic token provider. So I don't have any working theory. Maybe `startOffset` is used within the vscode language server library on the semantic token code path?

**Comment by bschnurr** [comment]
ya thats my guess. it might be a property on a parameter of the semantic token lsp call.

**Comment by softorangetech11** [comment]
> is there a public code repo?

No I just installed it, and I got this error.

**Comment by bschnurr** [comment]
still seeing this?

just open vscode.dev no typing? 

it happens on startup?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
