### ISSUE TITLE
Erroneous warnings "constant not defined" issued by Pylance

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/pylance-release#3012]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Erroneous-warnings-constant-not-defined/10043878)._

---
[regression] [worked-in:VS 2022 17.1.x]
Opening the repo mentioned here https://github.com/microsoft/pylance-release/issues/2427 with VS 17.2.0 not only yields the well known problems of VS continuously starting pylance and pylance not analyzing files in acceptable time but 

Info: (2404) [BG(1)] Long operation: checking: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (494719ms)
Info: (2404) [BG(1)] Long operation: analyzing: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (495780ms)
Info: (2404) [BG(1)] Long operation: getSemanticTokens full at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (70756ms)
Info: (2404) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1652737442062 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (70484ms)
Info: (2404) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1652737513253 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (75193ms)
Info: (2404) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1652737584122 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (68038ms)
Info: (2404) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1652737659771 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (73477ms)
Info: (2404) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1652737728122 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (72514ms)
etc. etc.

in addition _583: warnings almost all of the type "constant X not defined" are issued with the code segments getting highlighted. These warnings are all incorrect as the constants are defined in a separate file and due to the associated code highlighting are rather annoying.

---
#### Feedback Bot on 5/16/2022, 07:35 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by excubo-jg** [comment]
Update report below now using Pylance language server 2022.6.0 and Version 17.3.0 Preview 3.0

Retracing the steps from above, observed peak runtime per step now 6448636ms (+40%) and the first code analysis does not report the warning in line 5704 any more...

Info: (17884) Pylance language server 2022.6.30 (pyright 212d1465) starting
Info: (17884) Background analysis(1) started
Info: (17884) [BG(1)] Long operation: getSemanticTokens range 1925:0 - 2026:0 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (11968ms)
Info: (17884) [BG(1)] Long operation: checking: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (11580ms)
Info: (17884) [BG(1)] Long operation: analyzing: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (11580ms)
Info: (17884) [BG(1)] Long operation: getSemanticTokens full at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (35018ms)

0 errors/warnings - CPU-Load goes down without issue in 5704 being found

Change "action" to "cation" in line 1972:

Info: (17884) [FG] Long operation: completion at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py:1971:41 (242242ms)
Info: (17884) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1657689398137 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (55758ms)
Info: (17884) [FG] Long operation: completion at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py:1971:43 (4209004ms)

still no errors/warnings

Info: (17884) [BG(1)] Long operation: checking: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (6448131ms)
Info: (17884) [BG(1)] Long operation: analyzing: C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (6448636ms)
Info: (17884) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1657691847358 at C:\Users\Admin\Documents\Visual Studio 2019\Projects\pylancedemo\ai\quick_dominion.py (29058ms)

1 warning line 1972

Makes no sense to fix the undetected issue in 5704 so stopping here

**Comment by bschnurr** [comment]
Here's the next thing you can try. Add the following to the `settings.json` file for your project:
```
  "python.analysis.logLevel": "Trace",
  "python.analysis.logTypeEvaluationTime": true,
```
you should now see much more verbose output.

it might help track down where the time is being spent.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
