### ISSUE TITLE
Pylance fails to find certain properties in the Stripe SDK

### ISSUE THREAD

**Issue by xavdid** [microsoft/pylance-release#3014]
<h3> Environment data </h3>

-   Language Server version: 2022.5.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): `Python 3.9.11`
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Expected behaviour </h3>

No type error

<h3> Actual behaviour </h3>

```
Cannot access member "search" for type "Type[Customer]"
  Member "search" is unknown Pylance(reportGeneralTypeIssues)
```

<h3> Logs </h3>

Python Language Server Log
log is here (ran over the character limit for issue): https://gist.github.com/xavdid/47ade8a3ac9bc105834fb2cc3dfcc16b

<h3> Code Snippet / Additional information </h3>

```python
import stripe

stripe.Customer.search() # Cannot access member "search" for type "Type[Customer]"
```

I'm not sure of the nature of this issue, just that pylance was giving stripe errors when it shouldn't have. In a clean virtual env using the prod stripe (`pip install stripe`; v `3.5.0` at time of writing), the above snippet threw a pylance error (while the code worked as expected). 

The `search` method is definitely present on the `Customer` class. Here's the call path:
 
1. [stripe/stripe-python | __init__.py#L34](https://github.com/stripe/stripe-python/blob/5ce6b671d1e476c171e5c3f8caf748ce5fa63fc0/stripe/__init__.py#L34)
2. [stripe/stripe-python | __init__.py#L42](https://github.com/stripe/stripe-python/blob/5ce6b671d1e476c171e5c3f8caf748ce5fa63fc0/stripe/api_resources/__init__.py#L42)
3. [stripe/stripe-python | customer.py#L110](https://github.com/stripe/stripe-python/blob/5ce6b671d1e476c171e5c3f8caf748ce5fa63fc0/stripe/api_resources/customer.py#L110)

Other methods on `Customer` are hinted correctly, `.search` is a weird outlier here.

Oddly, in [the import block at the top](https://github.com/stripe/stripe-python/blob/5ce6b671d1e476c171e5c3f8caf748ce5fa63fc0/stripe/api_resources/customer.py#L4-L14) of `Customer.py`, a subset of the resources aren't resolved by pylance (each has a `"X" is unknown import symbol`):

<img width="536" alt="Screen Shot 2022-07-07 at 2 35 11 PM" src="https://user-images.githubusercontent.com/1231935/177875498-6b63bba2-2ccb-41a3-9e48-61d0892c7b22.png">

Those are all defined in [`abstract/__init__.py`](https://github.com/stripe/stripe-python/blob/5ce6b671d1e476c171e5c3f8caf748ce5fa63fc0/stripe/api_resources/abstract/__init__.py#L5), and pylance shows no errors when looking at the file locally:

<img width="573" alt="Screen Shot 2022-07-07 at 2 37 32 PM" src="https://user-images.githubusercontent.com/1231935/177875767-32ea7298-637c-4dd6-9457-c0de893fbb57.png">

Apologies in advance if this belongs in another repo!

**Comment by heejaechang** [comment]
It looks like type stubs in the typeshed (https://github.com/python/typeshed/tree/master/stubs/stripe/stripe) is out dated.

can you open a bug on https://github.com/python/typeshed so that they fix the issue on strip type stubs? once they fix it, we will pull those in and bundle them with us.

**Comment by piotrsynowiec** [comment]
I have a similar problem with:

`line_items = stripe.checkout.Session.list_line_items(session.id)`

even though the code is correct, the Stripe library is latest etc:

"Cannot access member "list_line_items" for type "Type[Session]"
  Member "list_line_items" is unknownPylance"

when creating StripeWebhookView.

How can I fix it?

**Comment by rchiodo** [comment]
> I have a similar problem with:
> 
> `line_items = stripe.checkout.Session.list_line_items(session.id)`
> 
> even though the code is correct, the Stripe library is latest etc:
> 
> "Cannot access member "list_line_items" for type "Type[Session]" Member "list_line_items" is unknownPylance"
> 
> when creating StripeWebhookView.
> 
> How can I fix it?

This is likely a type stub error as well. Those type stubs for stripe look rather incomplete. You could add the appropriate data to them or log an issue.
