### ISSUE TITLE
Documentation/full Docstring for basic numpy/pandas absent in VSC Jupyter notebook. 

### ISSUE THREAD

**Issue by deem-lab** [microsoft/pylance-release#3016]
The standard Jupyter Notebook browser interface provides detailed information when hovering (see image below), but in VSCode the straightforward documentation is absent. In my attempts to find a solution, I see that this has been a recurrent issue and might be related to Pylance?? If I need to edit my .json settings, which looks like it might be a solution for some people, I could use some basic instructions on how to do so. 

## Environment data
Pylance: v2022.7.20
Pylance language server 2022.7.20 (pyright 7cadfb74)
OS and version: Monterey v12.4
Python version: 3.9.12 
I use multiple IDEs depending on the project, some with v2.7.18 or v3.7.13, but the issue is consistent. 

## Expected behavior (pulled from another issue) 
<img width="807" alt="Screen Shot 2022-07-07 at 4 06 17 PM" src="https://user-images.githubusercontent.com/56778172/177885869-6c909b2d-ecb6-42d6-a182-e7f46e936f87.png">

## Actual behavior
<img width="187" alt="Screen Shot 2022-07-07 at 4 01 35 PM" src="https://user-images.githubusercontent.com/56778172/177885400-9c420b2c-6410-4c15-90f9-5114032e012d.png">
<img width="304" alt="Screen Shot 2022-07-07 at 4 11 05 PM" src="https://user-images.githubusercontent.com/56778172/177886303-08ffc270-729f-42f7-b429-4be322434248.png">

**Comment by debonte** [comment]
@deem-lab, we'll need more complete sample code to be able to repro this. With imports and versions of imported libraries.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
