### ISSUE TITLE
pandas: Cannot access member "astype" for type "float"

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#302]
## Environment data

-   Language Server version: Pylance language server 2020.8.3 (pyright 8c5415fd)
-   OS and version: macOS
-   Python version (& distribution if applicable, e.g. Anaconda): pandas==1.0.5

## Expected behaviour

No type error

## Actual behaviour

Cannot access member "astype" for type "float"
  Member "astype" is unknown

## Code Snippet / Additional information

```python
import pandas as pd
from datetime import date


df = pd.DataFrame({
    'date': [
        date.fromisoformat('2020-02-14'),
        date.fromisoformat('2020-02-14'),
        date.fromisoformat('2020-03-14'),
    ],
    'amount': [50.0, 50.0, 12.0]
})

(df.groupby(["date"])["amount"]
 .sum()
 .astype(float)
 .to_frame(name="daily_total")
 .reset_index())

```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.5, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202095-16-september-2020
