### ISSUE TITLE
Stub file not found for "hvac"

### ISSUE THREAD

**Issue by Hickory420** [microsoft/pylance-release#3020]
The line `import hvac` produces `Stub file not found for "hvac"`
I installed `hvac` via `pip3 install hvac`
hvac is python client for Hashicorp Vault
https://pypi.org/project/hvac/

If you need any more information, please let me know!
<img width="628" alt="image" src="https://user-images.githubusercontent.com/18060387/178096535-11dd0042-48b9-4f3e-a9fe-103423927a32.png">
edit: Added Screenshot

**Comment by erictraut** [comment]
The `reportMissingTypeStubs` diagnostic check is not enabled by default in pylance, so I presume that you've enabled it, perhaps by setting `typeCheckingMode` to "strict"?

This diagnostic means that the import target is not marked as "py.typed" and you have no type stub that describes the types in this module. Strict type checking requires accurate and complete type information, and that needs to come from some source — either from the library itself or a separate type stub.

For more details about type stubs, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md).
