### ISSUE TITLE
issues finding stubs for native library with submodules

### ISSUE THREAD

**Issue by pthom** [microsoft/pylance-release#3021]
I'm having issues with Visual Studio Code python language server, which cannot find the stubs for a python binding library I am developing (https://github.com/pthom/lg_hello_imgui). I think the issue might be linked to the fact that my library expose several submodules.

I made a minimum reproducible example here: https://github.com/pthom/pylance_test

When using PyCharm or CLion, I can easily navigate to the stubs I defined for my library, and also in its submodules stubs.

However, when using Visual Studio Code, it is less reliable: 
* when using the `Jedi` language server I can navigate to the functions definition, although it might fail after a few minutes of usage.
* when using the `Pylance` language server, it always fails

I'm using a Mac M1. I've had this failure inside OSX, as well as inside windows ARM, with Parallels. Is it linked to my setup?

Here is the installed package structure:
````
.venv/lib/python3.9/site-packages/lg_hello_imgui/
├── __init__.py
├── _lg_hello_imgui.cpython-39-darwin.so*
├── hello_imgui.pyi
├── imgui.pyi
├── implot.pyi
└── py.typed
````

`_lg_hello_imgui` is a native library that include three submodules, defined like this via pybind11:
````cpp
PYBIND11_MODULE(_lg_hello_imgui, m)
{
    auto module_imgui =  m.def_submodule("imgui");
    py_init_module_imgui(module_imgui);

    auto module_himgui =  m.def_submodule("hello_imgui");
    py_init_module_hello_imgui(module_himgui);

    auto module_implot =  m.def_submodule("implot");
    py_init_module_implot(module_implot);
}
````

and `lg_hello_imgui/__init__.py` states:

````python
from lg_hello_imgui._lg_hello_imgui import imgui
from lg_hello_imgui._lg_hello_imgui import hello_imgui
from lg_hello_imgui._lg_hello_imgui import implot
````

Repo for issue reproduction:
https://github.com/pthom/pylance_test
(Note: the lg_hello_imgui linked library does not exist as wheel yet, so it may require 1 minute or 2 to build)

**Comment by erictraut** [comment]
We'll need to examine your stub files to diagnose the issue. I don't see any stubs in your [main project](https://github.com/pthom/lg_imgui_bundle) or the [repro test project](https://github.com/pthom/pylance_test). Where are the stubs and the "py.typed" file coming from? I tried to install library, but I received various errors (on MacOS) when attempting to build it.

**Comment by pthom** [comment]
Thanks for your help, and sorry if I was not clear enough.

> I don't see any stubs in your [main project](https://github.com/pthom/lg_imgui_bundle) or the [repro test project](https://github.com/pthom/pylance_test)

The stubs are here: https://github.com/pthom/lg_imgui_bundle/tree/main/bindings/lg_imgui_bundle


> I tried to install library, but I received various errors (on MacOS) when attempting to build it.

Sorry for that!  It is still largely a work i progress (although I also work on a mac M1).  I did setup some CI on linux. It seems like I will need to do the same on MacOS.

-----

In  order to help you, I made an archive with the content of the `site-packages/lg_imgui_bundle` folder: 

https://traineq.org/lg_imgui_bundle.tgz (it also includes a wheel for Mac M1, python 3.9)

**Comment by erictraut** [comment]
The problem is that your `__init__.pyi` stub is importing the symbols `_hello_imgui`, `imgui`, and `implot`, but it is not re-exporting them. By default, all symbols imported by a stub are considered private to that module, not exported outside of it. To indicate that your intent is to re-export these symbols, you need to use a redundant form of the import statement (e.g. `from x import y as y`). For details, refer to [this section of PEP 484](https://peps.python.org/pep-0484/#stub-files) that specifies how stub files work.

**Comment by pthom** [comment]
`from . import hello_imgui as hello_imgui` worked like a charm!

Thanks a lot and sorry for if this was not a pylance related issue.

I'm closing the issue, as it is resolved for me. Thanks again.
