### ISSUE TITLE
How to update missing definitions from imported libraries?

### ISSUE THREAD

**Issue by Newcool1230** [microsoft/pylance-release#3026]
In pycharm you are able to directly jump to the function you called in different libraries

<details>
<summary>pycharm</summary>

![pycharm64_UTW7t16Ums](https://user-images.githubusercontent.com/10657253/178157993-38d84b0b-3b44-47cc-8f90-61e85152216f.gif)
</details>

but in vscode pylance it shows that there is "No definition found".
<details>
<summary>vscode</summary>

![Code_xaIjvwAS4a](https://user-images.githubusercontent.com/10657253/178158056-f505fa4d-03d9-4a74-b405-4051acfc1014.gif)
</details>

is there a similar or same setting I can enable in vscode to allow for the full indexing of the imported library? This issue also fails to autocomplete most functions.

<details>
<summary>pylance enabled</summary>

![image](https://user-images.githubusercontent.com/10657253/178158330-8421350f-773a-4152-b170-affb858ecf8d.png)
</details>

Version: 1.69.0 (user setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by bschnurr** [comment]
My guess is 'submission' or 'mod' type is unknown.

might need to do something like this

```
m:XXX = submission.mod
```
where XXX is the type of mod

**Comment by bschnurr** [comment]
could also try generating type stubs. see https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md#generating-type-stubs

**Comment by Newcool1230** [comment]
> could also try generating type stubs. see https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md#generating-type-stubs

Generating Type Stubs doesn't seem to make it better, rather it seems to make it worse as I'm unable to even jump to the `r.submission()` function like before.

<details>
<summary>vscode Type Stubs</summary>

![Code_fYo3GcwZZk](https://user-images.githubusercontent.com/10657253/178417432-777dab0f-af43-45e3-b7fb-f3cbc3b364be.gif)
</details>

<details>
<summary>pycharm jumping to `.mod` function</summary>

![pycharm64_xu7MegsvM4](https://user-images.githubusercontent.com/10657253/178417585-cd0aecbe-073b-4ad7-92a2-15d373c32930.gif)
</details>

Adding a type also didn't work.
