### ISSUE TITLE
After set the return value of the function, wrong color display in the code of function.

### ISSUE THREAD

**Issue by ARCJ137442** [microsoft/pylance-release#3028]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

After setting the return value of a function, comments and reserved keywords are displayed in white instead of the color before setting the return value.

## Steps to reproduce:

1. Input code:
```
def f(x:int):
    # comment
    if True:
        return x+1
```
3. Then insert " -> int" between "(x:int)" and ":", like this:
```
def f(x:int) -> int:
    # comment
    if True:
        return x+1
```
4. Now you can see the color change of the code (the current function and the rest of whole .py file).

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.11.11891004
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (17.16GB free)|
|Process Argv|H:\\A137442\\Develop\\Python\\语言学小工具 --crash-reporter-id 69e7bd2a-8a9e-4927-8a68-bc6f9add4ad1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by judej** [comment]
@ARCJ137442, I have tried this on  the latest stable release - v2022.10.20. And I am unable to reproduce it. If you are still seeing this, please reopen this issue.
