### ISSUE TITLE
pandas: set_index with a single value errors

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#303]
## Environment data

-   Language Server version: Pylance language server 2020.8.3 (pyright 8c5415fd)
-   OS and version: macOS
-   Python version (& distribution if applicable, e.g. Anaconda): pandas==1.0.5

## Expected behaviour

No type error, as this is correct behaviour according to the [pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.set_index.html) 

## Actual behaviour

No overloads for "pd.DataFrame({ "name": "alice","count": [0] }).set_index("name")" match parameters
  Argument types: (Literal['name'])

## Code Snippet / Additional information

```python
import pandas as pd

pd.DataFrame({"name": "alice", "count": [0.0]}).set_index(
        "name"
    )
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.5, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202095-16-september-2020
