### ISSUE TITLE
Type of "bpy" is unknown

### ISSUE THREAD

**Issue by VimHax** [microsoft/pylance-release#3030]
## Environment data

-   Language Server version: 2022.7.20
-   OS and version: Fedora Linux 36
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.5

## Code Snippet

```python
import bpy

for area in bpy.context.screen.areas:
    print(area)
```

## Repro Steps

1. Follow [this guide](https://wiki.blender.org/wiki/Building_Blender/Other/BlenderAsPyModule) to build Blender as a Python module
2. Install it globally
3. Import `bpy` in a project

## Expected behavior

Able to pick up at least some type information from the module. The module should be installed correctly as it can be imported from the interactive console.
![image](https://user-images.githubusercontent.com/45242122/178462983-ddf4557d-2fd7-440a-99aa-ee1a904576d9.png)

## Actual behavior

The type of the whole module is marked as unknown.
![image](https://user-images.githubusercontent.com/45242122/178461850-ca73f919-be45-4d82-a29d-153277ecbf85.png)

## Logs

[Logs](https://gist.github.com/VimHax/0f6d07ef8a3480a2813fb9f3a2fef6b3)

**Comment by bschnurr** [comment]
I would try to launch the code to make sure your python environment sees it.

also recommend not installing things globally and to use a virtual environment.

**Comment by heejaechang** [comment]
did we set correct python interpreter? 

this one?
![image](https://user-images.githubusercontent.com/1333179/178559308-fea626b2-6c85-4ea0-a611-d4d179a82d95.png)

**Comment by VimHax** [comment]
I have set the interpreter properly I believe.
![image](https://user-images.githubusercontent.com/45242122/178571833-ba65669c-9f74-47e8-9146-18a319499697.png)
![image](https://user-images.githubusercontent.com/45242122/178571928-f036f3fd-ed4c-4f4e-8be1-a4fc4935a9cf.png)
And yes the code does run fine when I execute it.
![image](https://user-images.githubusercontent.com/45242122/178572063-1ea148b3-a66e-4580-9880-8a4cf9b317ed.png)

**Comment by VimHax** [comment]
FYI, BPY is a native Python module. When installing the module it added `bpy.so` and a folder named `3.2` to the `site-packages` folder located at `/usr/lib/python3.10/site-packages/`.

**Comment by bschnurr** [comment]
if bpy is a native module, it will need stubs ie. a .pyi file

**Comment by judej** [comment]
Closing old issue. As bschnurr mentions, this will need stubs from the python blender authors.
