### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by Meet-Bhalodia** [microsoft/pylance-release#3031]
i have install python library pyautogui successfully but whenever i open or create my file and use pyautogui library but it always show's me missing library "reportMissingImports".
i have latest version of python and pip.
So please guide me i have faced this problem always in python.
![report](https://user-images.githubusercontent.com/109055372/178477982-24851e94-5c95-4bd2-853a-c1c6d54b43e5.png)
contact email :- meetbhalodia3@gmail.com

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
