### ISSUE TITLE
pylance resolves zmq.async symbol to wrong object

### ISSUE THREAD

**Issue by orodbhen** [microsoft/pylance-release#3034]
## Environment data

-   Language Server version: v2022.7.21
-   OS and version: Linux Mint 20
-   Python version: 3.9.10 (anaconda)
-   PyZMQ version: 22.3.0

## Code Snippet

```python
import zmq
import zmq.asyncio
import asyncio

ctx = zmq.asyncio.Context()
sock = ctx.socket(zmq.SUB)
sock.setsockopt_string(zmq.SUBSCRIBE, "")
sock.setsockopt(zmq.LINGER, 0)
sock.bind("tcp://*:8888")

async def recv():
    while True:
        msg = await sock.recv_multipart()
        print(f"topic: {msg[0]}, data: {msg[1]}")

if __name__ == '__main__':
    asyncio.run(recv())
```

## Repro Steps

1. XXX

## Expected behavior

`sock.recv_multipart` should resolve to `zmq._future._AsyncSocket.recv_multipart`, which is what happens when pylance is disabled:

```
def recv_multipart(flags=0, copy=True, track=False)
Receive a complete multipart zmq message.

Returns a Future whose result will be a multipart message.
Full name: zmq._future._AsyncSocket.recv_multipart
```

## Actual behavior

With pylance enabled it resolves to the non-async version of the function, resulting in a "not awaitable` error:

```
"list[Frame | ByteString]" is not awaitable Pylance(reportGeneralTypeIssues)
```

## Logs

```

```

**Comment by orodbhen** [comment]
I've updated the original post to include the `pyzmq` version and import statement. `asyncio` is part of Python. `ctx` is just a variable.

The problem, essentially, is that pymzq objects, such as `socket`, should resolve to the `pyzmq.asyncio` variant, because they're instantiated using `zmq.asyncio.Context`. This is what happens when pylance is disabled. However, with pylance enabled, it resolves to the standard variant of the object. As a result, I get a lot of warnings that the methods of `socket` aren't awaitable.

**Comment by erictraut** [comment]
Are you sure you have version 22.3.0 of the `pyzmq` library installed and the correct Python environment selected in VS Code? I was able to repro your issue as reported with older versions of the library, which didn't return awaitable objects from the `recv_multipart` method. Once I upgraded to 22.3.0, the error went away because the latest version does provide an awaitable return value. Please confirm that you have the correct Python environment selected and try `pip install pyzmq --upgrade` to ensure that you're using the latest version of the library.

**Comment by orodbhen** [comment]
Yes, I'm certain of the version:

```
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
>>> zmq.__version__
'22.3.0'
```
However, the Python version is actually 3.9.7, not 3.9.10, as previously noted. I used the latter number, as that was what was being reported by VSCode. But when I ran `python --version` on what VSCode said was the interpreter path, it output 3.9.7. I've attached a screenshot. Note how it gives different versions for `python3` and `python`, even though the two are just links to the same binary.

Output of `ls -l ./venv/bin/python*`:

```
lrwxrwxrwx 1 user user        9 Jun 21 11:43 ./venv/bin/python -> python3.9
lrwxrwxrwx 1 user user        9 Jun 21 11:43 ./venv/bin/python3 -> python3.9
-rwxrwxr-x 1 user user 15733456 Jun 21 11:43 ./venv/bin/python3.9
```

![Screenshot from 2022-07-19 09-39-26](https://user-images.githubusercontent.com/4573865/179765058-259e9c68-6af2-4f2d-af5e-6bb9970550e1.png)

**Comment by rchiodo** [comment]
It's strange that `./venv/bin/python` is coming out as Python 3.9.7. Seems like a bug in the python extension.

However even with 3.9.7 and the latest ZMQ this should work. 

This is what I get:



![Image](https://user-images.githubusercontent.com/19672699/192031758-f9c2ffbd-f7fb-4e5c-ac35-d9c78ac30023.png)

Can you set this setting:

```
    "python.analysis.logLevel": "Trace",
```

And then copy the contents of the Python Language Server output window:



![Image](https://user-images.githubusercontent.com/19672699/192032168-f9f71617-d564-44d0-9eae-cf345b7ce8a8.png)

It should show some parsing of ZMQ. That will indicate where we get the ZMQ types from. Example, this is what mine shows for a 3.9.7 python:

```
[Info  - 11:18:27 AM] (25828)   Attempting to resolve using root path 'c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar'
(25828) [IDX(2)]       binding: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\__init__.pyi ...
(25828) [IDX(2)]         parsing: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\context.py [fs read 1ms] (10ms)
(25828) [IDX(2)]         binding: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\context.py (1ms)
(25828) [IDX(2)]         parsing: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\frame.py [fs read 0ms] (4ms)
(25828) [IDX(2)]         binding: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\frame.py (0ms)
(25828) [IDX(2)]         parsing: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\poll.py [fs read 1ms] (2ms)
(25828) [IDX(2)]         binding: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\poll.py (0ms)
(25828) [IDX(2)]         parsing: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\socket.py [fs read 1ms] (12ms)
(25828) [IDX(2)]         binding: c:\Users\aku91\miniconda3\envs\RunPythonTest\Lib\site-packages\zmq\sugar\socket.py (1ms)

```

**Comment by rchiodo** [comment]
Closing pending more information. This should be working if you have the latest version of ZMQ
