### ISSUE TITLE
Cannot find 'decimal.Context' when typing 'decimal.ctxt'.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/pylance-release#3037]
## Environment data

![image](https://user-images.githubusercontent.com/82852072/178705779-806a9fd6-e6b7-48b6-a1b8-3b20c3861921.png)

## Repro Steps

![image](https://user-images.githubusercontent.com/82852072/178708769-ac1dc413-05d1-4a7d-aef4-220b70d26cca.png)

## Expected behavior

decimal.ctxt will bring ```decimal.Context``` up.

## Actual behavior

Cannot find 'Context' when typing 'ctxt'. 

![image](https://user-images.githubusercontent.com/82852072/178707036-cf6de74c-0789-4896-bcd6-69dbdbeedc08.png)

**Comment by judej** [comment]
This is not reproducible in VS Code. Looks like a VS specific issue

**Comment by judej** [comment]
This seems to be working on VS too.

![image](https://user-images.githubusercontent.com/547753/195689551-84320260-b93f-4cbd-b328-eda96523a1a6.png)


@ttSpace, if this is still reproducible, please reopen.
