### ISSUE TITLE
my vscode still cannot jump to definitions and references

### ISSUE THREAD

**Issue by Luh1124** [microsoft/pylance-release#3041]
-   Language Server version: v2022.7.30
-   OS and version: ubuntu18.04
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda
- 

After installation, my vscode still cannot jump to definitions and references, which cannot be solved. Python language has been set to pylance .

**Comment by Luh1124** [comment]
![image](https://user-images.githubusercontent.com/45451989/178920890-1b96b82a-301d-45d8-a887-d694f9bbc5f5.png)

**Comment by Fadelis98** [comment]
ctrl + shift + p  and use 'python:select language interpreter; manually to select one interpreter may be useful

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
