### ISSUE TITLE
Intellisense not work for sub modules

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/pylance-release#3044]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

It cannot understand `gym.spaces.Discrete` is a class. Not parameters suggestions.

![image](https://user-images.githubusercontent.com/4510984/178973937-25c1c9a2-3ce7-415e-9a4c-1737c7f60cae.png)

![image](https://user-images.githubusercontent.com/4510984/178974133-387dbbbb-ad0c-4f49-a970-0b5bb29017c4.png)

### VS Code Version

1.69.1

### Jupyter Extension Version

v2022.6.1101950301

### Coding Language and Runtime Version

Python 3.9.13 by MiniConda

### Language Extension Version (if applicable)

v2022.10.0

### Anaconda Version (if applicable)

MiniConda 4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by bschnurr** [comment]
try `from gym.spaces import Discrete`

you could ask gym to export 'spaces' in their '__init__.py' '__all__' definition
