### ISSUE TITLE
Feature request: Implement GitHub Action to set up and run `pyright` exactly as Pylance would do in VSCode

### ISSUE THREAD

**Issue by blakeNaccarato** [microsoft/pylance-release#3045]
[This comment](https://github.com/microsoft/pylance-release/issues/2989) helps a user who is having trouble getting the `pyright` CLI and the Problems tab of VSCode to behave the same. In summary, there are a few settings that Pylance does differently by default than `pyright`, Pylance doesn't always have the very latest `pyright`, and Pylance leverages additional type stubs than `pyright`. This issue also occurs when trying to get a GitHub Actions workflow to check a project in _exactly the same way_ that the local VSCode Pylance extension is doing.

Would it be possible to supply an "official" GitHub Action to the Marketplace that sets up and runs `pyright` exactly as Pylance would do in VSCode? Such an action would properly handle the caveats in the comment above, especially pinning the `pyright` version, pulling Microsoft type stubs and putting them in `typings`, and reading from, e.g. the `pyrightconfig.json` in the repo. Such an Action would follow the release cadence of Pylance and automatically update its pinned `pyright` version in step with the latest release of Pylance.

I would understand if this feature is considered out of scope for this project, but facilitating `pyright` to run the same as Pylance in workflows would reduce the need to manually keep `mypy` roughly synced with Pylance just for workflow type-checking.

**Comment by erictraut** [comment]
I don't think we need to be all that concerned about version syncing between pyright and pylance. Pylance releases once a week (typically on Wednesday), and I release pyright once or twice a week (typically on Friday or Saturday and then again on Tuesday). So pylance is never more than a few commits out of date from pyright. It's rare that these minor deltas result in visible behavior differences between the two.

There are two other differences between pylance and pyright that will result in different behaviors:
1. As you point out, pylance ships with additional stubs.
2. By default, pylance sets `typeCheckingMode` to "off" and `useLibraryCodeForTypes` to "true". The defaults for pyright are "basic" and "false", respectively.

To address 2, you need to manually modify the defaults for pylance. I recommend doing that in a pyrightconfig.json (or pyproject.tolm) file that is checked in to your repo. That way, all contributors to your project will get the same settings regardless of which editor they are using.

That leaves 1 above. To handle this, I recommend identifying which additional stubs your project relies on and checking them in to your repo in a `typings` subdirectory. This will override any of the stubs that pylance ships with, and it will supply these same stubs for the CLI version of pyright. This approach puts you in full control of the versioning of these stubs. The added stubs that pylance ships with can be found [in this repo](https://github.com/microsoft/python-type-stubs).

You can use [this github action](https://github.com/jakebailey/pyright-action) to set up and run pyright as part of your CI.

**Comment by jakebailey** [comment]
The python-type-stubs repo contains some stubs we wrote by hand, but I believe Pylance still ships with more stubs than just those that have been pulled from other repos like django-stubs. I'm not so sure my action could reliably grab a specific set of versions of all of those stubs to match a specific Pylance version (and have it behave the same as Pylance does, where those are low priority imports).

IMO the best way to do this is to not rely on those Pylance stubs if you're trying to run things in CI, instead depend on the types packages directly by installing them. I'm curious which stubs you're using that aren't actually available on PyPI as packages or similar. Most of the major ones have been upstreamed to typeshed, pandas, etc, directly (probably not matplotlib?). I'm not sure how you'd be using mypy at the same time for this, either, since mypy wouldn't be pulling from Pylance stubs.

**Comment by blakeNaccarato** [comment]
Thanks to both of you for the help. That there is a fairly feature-rich existing Pyright GitHub Action, and knowing that a `typings` directory with explicit stubs does in fact override Pylance's stubs, will likely resolve most of my headaches. I think there's a way forward here with the existing tools, given your pointers. I realize I probably should've started out over in [Discussions](https://github.com/microsoft/pylance-release/discussions). I'll go there first next time I'm asking about blue-sky enhancements like this.

My specific issue has been with various differences between CI and local runs, sometimes an "unnecessary type ignore", and the occasional Pandas-related `pyright` error triggering on CI but not local. Despite installing the same version of `pandas-stubs` on local and CI, I think that not having anything explicitly in the `typings` directory must be causing local Pylance to source some of its own stubs implicitly.

I mentioned `mypy` in that it's often easier to type check with Pylance locally, but not actually "enforce" it at all in CI, opting to type check in CI with `mypy` instead. Of course then you have to maintain `mypy` and `pyright` configs alongside one another and keep them somewhat in agreement, which is a headache, too. Perhaps the mismatch between Pylance and CI could be helped by having workspace-specific extension version pinning in VSCode, but that's definitely out of scope here.

I'll close this request, since it seems adequately handled by existing tools, and that getting a GitHub Action to type-check exactly like any given version of Pylance is not really one-size-fits-all, with all the variables involved. Thanks again.

**Comment by PierreSnell** [comment]
Hi, sorry to bump a closed issue. 

@blakeNaccarato Seems you managed to solve the problem with your own typeStubs.
However, I still have a difference in behaviour with pyright cli and pylance...

@erictraut or @jakebailey do you know where I could find the stubs used by pylance to replicate this in my CI ? (Or if there is any way to make the CI close enough to the pylance extension. Now I have hundred of errors, mostly pandas)

The easiest option for the team here is to develop in VsCode and that they can trust the "problems" tab (no problem means the CI passes)

System :
```
python3.10
pyright: 1.1.279
typeShed: python/typeshed.git (latest master)
typeStubs: :microsoft/python-type-stubs.git (latest master)
```
My only option to run it in CI for now is to just not run it...

Thanks
Have a great day

**Comment by erictraut** [comment]
The custom stubs that are packaged with pylance are checked in to [this repo](https://github.com/microsoft/python-type-stubs). Or you can find where pylance is installed on your machine and grab the stubs directly from that location.

**Comment by PierreSnell** [comment]
Hi @eri
