### ISSUE TITLE
Find References should handle dunder methods

### ISSUE THREAD

**Issue by indigoviolet** [microsoft/pylance-release#3047]
**Is your feature request related to a problem? Please describe.**
Find References seems to only find actual uses of the symbol, and doesn't handle cases like `in` for `__contains__`, iteration for `__iter__`. 

**Describe the solution you'd like**
Find References (or Call Hierarchy) should link to all usages of dunder methods. 

**Additional context**
AFAICT, the spec (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_references) doesn't specify what it means precisely by references to a symbol. I can see how the literal interpretation would be looking for an actual call to (for eg) `__contains__()`, but I think that the above behavior will be more useful.

**Comment by judej** [comment]
Dupe of https://github.com/microsoft/pylance-release/discussions/2597. Please feel free to upvote the discussion.
