### ISSUE TITLE
Pylance doesn't work on my vscode！

### ISSUE THREAD

**Issue by Luh1124** [microsoft/pylance-release#3049]
Issue Type: <b>Bug</b>

The operating system ubuntu18.04, pylance version is v2022.7.30. After I installed the Python and pylance plug-ins, I set the PythonLanguage to Pylance“”, but I still can't enable functions such as jump definition and reference!

Extension version: 2022.7.30
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:28:29.328Z)
OS version: Linux x64 4.15.0-167-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|62.83GB (2.96GB free)|
|Process Argv|--unity-launch --crash-reporter-id a071169c-1339-46b5-966e-3ec6c9000993|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

![image](https://user-images.githubusercontent.com/45451989/179144274-726253ac-34dd-4b11-bc1d-fb7d056e0f44.png)

**Comment by ddejohn** [comment]
I'm having this issue as of this morning as well. I've tried restarting vscode, explicitly setting Pylance as the language server in `settings.json`, restarting the language server, restarting my computer....

**Comment by bschnurr** [comment]
does onHover information appear?

please include logs in a separate file.
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by Luh1124** [comment]
Hello, I found that pylance can be enabled normally when the workspace I opened does not contain large files or soft connections to large files; For example, my workspace is set under \home\user, which cannot be enabled normally, but when I create a subfolder workspace separately under the \home\user folder, and then touch py file, I can enable pylance; Can this situation be solved?

**Comment by Luh1124** [comment]
> .
i have try it,but not work for me; But I found new problems like https://github.com/microsoft/pylance-release/issues/3049#issuecomment-1186060656

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

How many files/folders are there in \home\user?  It could be that we are taking too long to can the whole folder structure.
If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by Luh1124** [comment]
Thanks， because I added the folder where the dataset is stored to the $HOME PATH using a symlink, it took a long time to enable pylance. Currently I have modified my usage to only add the required folders to the workspace.
