### ISSUE TITLE
I am working with the OAK-D  and trying to import this one "from depthai_helpers.version_check import check_depthai_version" and facing the Error No Module found. Can anyone guide what should I do resolve this issue

### ISSUE THREAD

**Issue by ZeeshanHaydar** [microsoft/pylance-release#3052]

**Comment by bschnurr** [comment]
check you have the correct interpreter selected with the library installed.

https://code.visualstudio.com/docs/python/environments#_work-with-python-interpreters

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
