### ISSUE TITLE
Switch to finalized notebookEditor API

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#3054]
From https://github.com/microsoft/vscode/issues/151661

VS Code has finalized the notebookEditor in 1.68. It seems dotnet is currently using the proposal, so we need you to switch to the finalized version

See https://github.com/microsoft/vscode/issues/151661 for details on the migration (it should be very simply) and let me know if you have any questions

**Comment by debonte** [comment]
@mjbvz, I don't believe we're using the notebookEditor proposal. Can you explain how you identified vscode-pylance as a consumer? I'm wondering if it might be because of our dependency on vscode-jupyter-lsp-middleware.

**Comment by mjbvz** [comment]
pylance is listed as an API user in our internal API proposal allow list. I don't know the history of why pylance was added but if you aren't using this API proposal, I will remove pylance from the list

**Comment by debonte** [comment]
Pylance doesn't currently have any API proposals in our package.jsons. However, [vscode-jupyter-lsp-middleware](https://github.com/microsoft/vscode-jupyter-lsp-middleware/blob/main/package.json#L27) does have `notebookEditor` enabled. I think that may be accidental/unused though.

@rchiodo might know more.

**Comment by rchiodo** [comment]
Pylance shouldn't be dependent upon vscode-jupyter-lsp-middleware. That's only used in the jupyter extension and the python extension.

**Comment by mjbvz** [comment]
Thanks @rchiodo! I'll go ahead and remove pylance from the list of consumers then. Please let me know right away if you notice any issues with the next insiders build
