### ISSUE TITLE
VSCode: Auto import/import suggestions for Python dependencies from external libraries

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3055]
I'm using VSCode for Python programming. One project heavily relies on an external library and often needs to load modules/classes/etc from that library.

When I type a class that is not yet imported and click on "quick fix" (cmd + . on Mac), VSCode automatically suggests what to import. Unfortunately, these suggestions only involve modules from the currently open project - not from any external dependency.

This means, I always have to figure out how to import the missing class from the external library (which package) and manually add the import myself. This is quite tedious when required frequently.

Is there any way to have VSCode auto suggest and import missing debendencies/classes/etc from external libraries similar to what it does with imports from the open project?

I found the setting `python.autoComplete.extraPaths` and set it to

```
"python.autoComplete.extraPaths": [  
   "/opt/homebrew/Caskroom/miniforge/base/envs/myenv/lib/python3.8/site-packages/mylib"
]
```

but I couldn't notice any change and the auto import still does not work.

**Comment by judej** [comment]
This could be resolved with an enhancement to configure the indexing options as discussed in this discussion. Please upvote the discussion. https://github.com/microsoft/pylance-release/discussions/2608

**Comment by heejaechang** [comment]
by the way, we have this hidden option for now - https://github.com/microsoft/pylance-release/issues/2533#issuecomment-1089268739

you can use this hidden option to make indexer to index more stuff as long as you are okay to pay perf cost.
