### ISSUE TITLE
Variable defined in context created by contextmanager is possibly unbound

### ISSUE THREAD

**Issue by zhaoruiyang98** [microsoft/pylance-release#3056]
## Environment data

-   Language Server version: v2022.7.30
-   OS and version: Ubuntu 20.04LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13 ([GCC 7.5.0] Anaconda)
-   python.analysis.typeCheckingMode: basic

## Code Snippet

```python
from contextlib import contextmanager

@contextmanager
def context():
    yield

with context():
    x = "hello world!"
lst = x.split()
```

## Expected behavior

Using `x` outside the context should be legal .

## Actual behavior

Pylance reports: "x" is possibly unbound
![Snipaste_2022-07-16_16-26-26](https://user-images.githubusercontent.com/43402887/179347104-e232ce4a-d44f-47d3-941a-902e108f70b5.jpg)

**Comment by erictraut** [comment]
This is a known issue with pylance 2022.7.30. It will be addressed in the next release. It's available today in the insiders release 2022.7.31, or you can wait for the next full release.
