### ISSUE TITLE
Pytorch Backends Module Cannot Be Detected

### ISSUE THREAD

**Issue by fang-d** [microsoft/pylance-release#3058]
In the code below, I can successfully import the `torch` package, but when I use `torch.backends`, Pylance gives me an error that the `backends` module cannot be found. However, the strange thing is that my code can run correctly, and I can directly import `torch.backends`, where Pylance does not give me an error. I wonder how to solve this problem.

```python3
# -*- coding: utf-8 -*-
import torch
from torch.backends import cudnn

if __name__ == '__main__':
    torch.backends.cudnn.benchmark = torch.backends.cudnn.is_available()
    cudnn.benchmark = cudnn.is_available()
```

![VSCode](https://user-images.githubusercontent.com/39642933/179384750-ee6bf655-023b-430e-bef1-aea23b0953a9.png)

## Environment
Windows 10 Pro 21H2
Python 3.10.4
Visual Studio Code 1.19.1 (System Setup)
Python Extension v2022.10.1
Pylance Extension v2022.7.30

## Python Virtual Environment Packages

```
Package                 Version       |  Package                 Version
----------------------- ------------  |  ----------------------- ------------
absl-py                 1.1.0         |  tqdm                    4.64.0
asttokens               2.0.5         |  traitlets               5.1.1
autopep8                1.6.0         |  typing_extensions       4.3.0
backcall                0.2.0         |  urllib3                 1.26.10
cachetools              5.2.0         |  visdom                  0.1.8.9
certifi                 2022.6.15     |  pyasn1-modules          0.2.8
charset-normalizer      2.1.0         |  pycodestyle             2.8.0
colorama                0.4.5         |  pydocstyle              6.1.1
cycler                  0.11.0        |  pyflakes                2.4.0
debugpy                 1.5.1         |  Pygments                2.11.2
decorator               5.1.1         |  pyasn1                  0.4.8
entrypoints             0.4           |  pyasn1-modules          0.2.8
executing               0.8.3         |  pycodestyle             2.8.0
fonttools               4.34.4        |  pydocstyle              6.1.1
google-auth             2.9.1         |  pyflakes                2.4.0
google-auth-oauthlib    0.4.6         |  Pygments                2.11.2
grpcio                  1.47.0        |  pylama                  8.3.8
idna                    3.3           |  pyparsing               3.0.9
IProgress               0.4           |  python-dateutil         2.8.2
ipykernel               6.9.1         |  pytz                    2022.1
ipython                 8.3.0         |  pywin32                 302
jedi                    0.18.1        |  pyzmq                   22.3.0
jsonpatch               1.32          |  requests                2.28.1
jsonpointer             2.3           |  requests-oauthlib       1.3.1
jupyter-client          7.2.2         |  rsa                     4.8
jupyter-core            4.10.0        |  scipy                   1.8.1
kiwisolver              1.4.3         |  seaborn                 0.11.2
Markdown                3.3.7         |  setuptools              61.2.0
matplotlib              3.5.2         |  six                     1.16.0
matplotlib-inline       0.1.2         |  snowballstemmer         2.2.0
mccabe                  0.7.0         |  stack-data              0.2.0
nest-asyncio            1.5.5         |  tensorboard             2.9.1
numpy                   1.23.0        |  tensorboard-data-server 0.6.1
oauthlib                3.2.0         |  tensorboard-plugin-wit  1.8.1
packaging               21.3          |  tensorboardX            2.5.1
pandas                  1.4.3         |  toml                    0.10.2
parso                   0.8.3         |  torch                   1.12.0+cu116
pickleshare             0.7.5         |  torch-tb-profiler       0.4.0
Pillow                  9.2.0         |  torchaudio              0.12.0+cu116
pip                     21.2.4        |  torchfile               0.1.0
prompt-toolkit          3.0.20        |  torchvision             0.13.0+cu116
protobuf                3.19.4        |  tornado                 6.1
pure-eval               0.2.2         |  wcwidth                 0.2.5
pyasn1                  0.4.8         |  websocket-client        1.3.3
pyasn1-modules          0.2.8         |  Werkzeug                2.1.2
pycodestyle             2.8.0         |  wheel                   0.37.1
pyasn1                  0.4.8         |  wincertstore            0.2

```

**Comment by erictraut** [comment]
Your code is relying on fragile side effects of the Python import mechanism.

You're first importing `torch`, which does not import the submodule `backends`. If you were to access `torch.backends` after the first import, your code would likely crash. You're then importing the submodule `torch.backends.cudnn` and assigning the module to the local symbol `cudnn`. Later, your code is relying on the side effect that the `backends` attribute of the `torch` module was populated as a side effect of the second import statement.

Pylance intentionally does not model such side effects. In general, they cannot be modeled statically. Code should not rely on such side effects, so it is intentionally flagged as an error.

If your code is going to depend on accessing `torch.backends.cdnn`, it should include the statement `import torch.backends.cdnn`. Or if you would prefer to stick with the statement `from torch.backends import cdnn`, then you should use the local symbol `cdnn` to access the `cdnn` submodule.

**Comment by fang-d** [comment]
Thank you for your reply. It is very helpful to me.

You mentioned in your reply that

>If you were to access `torch.backends` after the first import, your code would likely crash.

But It seems that there are no similar statements in the official documents of PyTorch. In the doucuments, `torch.backends` seems to be used directly such as [GPU specific optimizations](https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#gpu-specific-optimizations) and [TensorFloat-32(TF32) on Ampere devices](https://pytorch.org/docs/stable/notes/cuda.html#tensorfloat-32-tf32-on-ampere-devices).

Besides, I wrote the following testing code, and no crash occurred:
```python
# -*- coding: utf-8 -*-

import torch

if __name__ == '__main__':
    print(torch.backends.cuda.is_built())
    print(torch.backends.cudnn.is_available())
    print(torch.backends.cudnn.version())
    print(torch.backends.cudnn.enabled)
    print(torch.backends.cudnn.allow_tf32)
    print(torch.backends.mps.is_available())
    print(torch.backends.mps.is_built())
    print(torch.backends.openmp.is_available())
    print(torch.backends.mkldnn.is_available())
```
![image](https://user-images.githubusercontent.com/39642933/179387094-8f5c58a1-4074-4521-96e2-a9edefaa8924.png)
Could you please explain more on this to me so that there will be less potential problems in my code. Thank you so much!

**Comment by erictraut** [comment]
Pytorch is a "py.typed" library, which means that it includes a "py.typed" file within its root directory. When such a file is present, a library indicates that it has type information. It also means that the library must follow certain conventions that indicate which symbols are meant to be part of the public interface contract and which are meant to be private implementation details. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md).

In the case of Pytorch, the `torch/__init__.py` file indicates that the `backends` submodule is not re-exported from the top-level module. Therefore, you need to import it with an explicit `import torch.backends` statement within your code. If the `backends` submodule is intended to be re-exported from the top-level module, the `torch/__init__.py` file will need to be updated to indicate this. You could file a bug report in the [Pytorch github project](https://github.com/pytorch/pytorch/issues).

**Comment by fang-d** [comment]
Got it! Thank you very much for your reply.

**Comment by yzhang-gh** [comment]
Hi @erictraut, thanks for your explanation. However, I'm still kind of confused how I should deal with this kind of "error" messages.

The very begining

```python
import torch

torch.backends.cuda.matmul.allow_tf32 = False
      ^^^^^^^^
torch.backends.cudnn.allow_tf32 = False
      ^^^^^^^^
```

If I `import torch.backends`, then

```python
import torch.backends

torch.backends.cuda.matmul.allow_tf32 = False
               ^^^^
torch.backends.cudnn.allow_tf32 = False
               ^^^^^
```

and then

```python
import torch.backends.cuda
import torch.backends.cudnn

torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False
                     ^^^^^^^^^^
```

**Comment by erictraut** [comment]
The last of those code blocks is correct. It works for me without any type errors. If you're seeing an error here, I suspect it's because you have an older version of torch that has a bug. If you upgrade to torch 1.12.1, it should work fine.

**Comment by yzhang-gh** [comment]
Thank you. You are right, I'm using torch 1.11.0.
