### ISSUE TITLE
IntelliSense not works for submodules

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/pylance-release#3062]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In JupyterLab, I simply import the module, it can show me the parameters of the class which inside submodule.

![image](https://user-images.githubusercontent.com/4510984/179402875-ab2cb092-647f-4d51-8151-3d0bbb667df5.png)

In VSCode, not work.

![image](https://user-images.githubusercontent.com/4510984/179402927-ff5a1346-14c2-4cba-984b-cd8c00902d80.png)

### VS Code Version

1.69.1

### Jupyter Extension Version

v2022.6.1201981810

### Coding Language and Runtime Version

Python 3.9.13 by MiniConda

### Language Extension Version (if applicable)

v2022.10.1

### Anaconda Version (if applicable)

MiniConda 4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by bschnurr** [comment]
try 
```python
from tianshou.utils.net import common


common.Recurrent()
```

.net is missing from the public types listed in utils\__init__.py
![image](https://user-images.githubusercontent.com/1946977/183516221-3801efac-f87b-4dfe-8468-ff6d5d4152ed.png)

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
