### ISSUE TITLE
No module named 'requests'   File "C:\Users\Owner\AppData\Local\Temp\Temp1_pin-cracker-main.zip\pin-cracker-main\cracker.py", line 1, in <module>     import requests

### ISSUE THREAD

**Issue by nommmmmg** [microsoft/pylance-release#3065]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
