### ISSUE TITLE
Standard library collection/generics-supported-type from an alias-defined-module does not works as type-hinting

### ISSUE THREAD

**Issue by junkmd** [microsoft/pylance-release#3066]
## Environment data
-   Language Server version: `v2022.7.30`
-   OS and version: Windows 10 Home
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0

## Code Snippet
I am developing a version-compatible library.

Since Python 3.9, some features in `typing` have been deprecated because the collection types in the standard library support generics.

So I created a conditional branch by `sys.version_info` to import them aliased from `bulitlins` or import them from `typing`.

However, these boilerplates are written in each module, so I created a module dedicated to type hints that includes these conditional branches and import from there.

However, when the branch is imported from `builtins`, the type hints are not displayed properly, unlike when imported from `typing`, and `Any` is displayed.

When an alias is defined in the same module, type hints such as `tuple` work as expected.

I am using only standard libraries in the environment.
I am looking for the way does not use `typing_extensions`.

Is it possible to make such type hints work?

```
├─library
│  ├─ __init__.py
│  ├─ hints.py
│  └─ impl.py
```

```py
# hints.py
import sys

if sys.version_info < (3, 9):
    from typing import Callable as Callable
    from typing import Dict as Dict
    from typing import List as List
    from typing import Tuple as Tuple
    from typing import Type as Type
else:
    from collections.abc import Callable as Callable
    from builtins import dict as Dict
    from builtins import list as List
    from builtins import tuple as Tuple
    from builtins import type as Type
```

In `impl.py`,
![image](https://user-images.githubusercontent.com/45822440/179627678-eaa3df17-a894-4f63-9744-63392244197a.png)

![image](https://user-images.githubusercontent.com/45822440/179627758-1c09dd86-9b49-404e-8833-242bd55bff2c.png)

![image](https://user-images.githubusercontent.com/45822440/179628196-1b468e4a-f7db-4094-b950-aa1130a5cc5c.png)

## Expected behavior

`hints.Tuple` works like `builtins.tuple`.

## Actual behavior

`hints.Tuple` displays `Any`

**Comment by junkmd** [comment]
Is there some kind of investigation underway on this?

Or is this something that the type checker does not cover?

**Comment by erictraut** [comment]
I'm not able to repro the problem as reported.

<img width="437" alt="Screen Shot 2022-08-01 at 3 45 56 PM" src="https://user-images.githubusercontent.com/7040122/182258022-793ec81d-b9a2-4078-baf2-efe162c76b6b.png">

Have you enabled type checking diagnostics (i.e. set "python.analysis.typeCheckingMode" to "basic") to see if there are any type-related errors reported?

**Comment by junkmd** [comment]
@erictraut

> Have you enabled type checking diagnostics (i.e. set "python.analysis.typeCheckingMode" to "basic") to see if there are any type-related errors reported?

Thank you for your response.

Indeed, I changed `setting.json` from `"python.analysis.typeCheckingMode": "off"` to `"basic"` and now the type hint appears!

![image](https://user-images.githubusercontent.com/45822440/182260815-5153dff5-4779-4235-ab53-ecbae6e07888.png)

The strange thing is that when I change it to `"off"` again, the hint does not revert to `Any`, but is still displayed.

Sometimes, the type checker is not pylance (pyright) for project reasons, but the VSCode launguage server is set to pylance and I want to use the wonderful feature that the hints are displayed when the mouse is hovered over.
What should I do in such a case?
Do I need to make a momentary switch, as I did above?

**Comment by erictraut** [comment]
The hover text should not depend on the `typeCheckingMode` setting, so if you're seeing different hover text before and after enabling type checking diagnostics, then there's a bug.

Are there any other steps needed to repro the problem? Are you sure that you can repro it with the minimal instructions above? I'm still not able to repro it despite my best attempts.

Here are the files I've created based on your original post and screen shots.

```python
# hints.py
import sys

if sys.version_info < (3, 9):
    from typing import Callable as Callable
    from typing import Dict as Dict
    from typing import List as List
    from typing import Tuple as Tuple
    from typing import Type as Type
else:
    from collections.abc import Callable as Callable
    from builtins import dict as Dict
    from builtins import list as List
    from builtins import tuple as Tuple
    from builtins import type as Type
```

```python
# test.py
import hints

def foo(bar: str) -> hints.Tuple[str, int]:
    ...
```

When you see the problem, are you using a version of Python >= 3.9 or <3.9?

Have you tried updating to the latest prerelease (insiders) build of Pylance? The current production version of Pylance hasn't been updated for a couple of weeks, and there are several pyright bugs that have been fixed since then that could theoretically explain what you're seeing.

**Comment by junkmd** [comment]
@erictraut 

I'm using Python 3.10.

I created these py files with `setting.json` set to `"python.analysis.typeCheckingMode": "off"`, so they may be related.

I did not force the project to use VS Code, so I did not track the `setting.json` in git. So I have no history of that status. My apologies.

I have not tried the pre-release version.

At the present time, I had to write boilerplate in each module.

I will try the code-without-boilerplate at hand when the new production version is released.

**Comment by erictraut** [comment]
Out of curiosity, why are you trying to abstract the `typing` symbols? It's unlikely that they will ever go away. There's way too much Python code that uses them, and their removal would be way too disruptive. There's no need to avoid their use and abstract them away with either boilerplate or compatibility modules.

**Comment by junkmd** [comment]
> ... typing symbols ... will ever go away.

Really?

`typing` documentation said that
> Deprecated since version 3.9: builtins.type now supports []. See PEP 585 and Generic Alias Type.

And PEP585 said that
> The deprecated functionality will be removed from the typing module in the first Python version released 5 years after the release of Python 3.9.0.

Does this mean YAGNI at this point?

**Comment by erictraut** [comment]
> Really?

Yeah, "deprecated" in this context means that there is a new recommended approach that you can use for code that doesn't have backward compatibility requirements. It doesn't mean that these symbols will be removed. It would be _way_ too disruptive to delete these symbols from `typing`.

**Comment by junkmd** [comment]
@erictraut 

I respect your knowledge of Python.

> delete these symbols from `typing`.

That is exactly the mistake I made.

I will use `typing` without hesitation.

I am fine with this issue as resolved.

Thank you.

**Comment by junkmd** [comment]
from https://github.com/python/typing/issues/1230,

> There are currently no plans to remove the aliases from `typing`.

Therefore, I use `typing` in version-compatible-project without further hesitation.
