### ISSUE TITLE
Value returned from inside a with-statement context in a function results in a missing return value error

### ISSUE THREAD

**Issue by rexor12** [microsoft/pylance-release#3068]
## Environment data

-   Language Server version:
    - Stable: 2022.7.30 (pyright f3e85ee2)
    - Pre-release: 2022.7.31 (pyright bd00e0d1)
-   OS and version: Microsoft Windows 11 Pro (21H2, build 22000.795)
-   Python version: Python 3.10.0 64-bit
-   Explicit configuration: python.analysis.typeCheckingMode: "basic"
-   IDE: Visual Studio Code version 1.69.1 (system setup)

## Code Snippet

```python
import contextlib

def foo() -> str:
    with contextlib.suppress(Exception):
        return "hello"

print(foo())
```

## Expected behavior

No error should be reported as a value is returned after leaving the context.

## Actual behavior

An error is reported stating the following:
> Function with declared type of "str" must return value
>  Type "None" cannot be assigned to type "str" Pylance(reportGeneralTypeIssues)

![error-message](https://user-images.githubusercontent.com/15330052/179732054-14c085eb-446a-4d19-be85-6af1b43a72e8.png)

Executing the script (`py .\test.py` on Windows) produces the correct behavior, printing "hello" to the terminal.

## Logs

[python-language-server-output.txt](https://github.com/microsoft/pylance-release/files/9140251/python-language-server-output.txt)
[python-language-server-output-prerelease.txt](https://github.com/microsoft/pylance-release/files/9140371/python-language-server-output-prerelease.txt)

The root cause may be related to #3056, however, I was able to reproduce this using the pre-release version.

**Comment by erictraut** [comment]
The behavior you are seeing is correct. The context manager in this case may suppress (swallow) an exception that is raised through the execution of a statement within the `with` block. If this happens, execution will continue after the `with` block, and the function will implicitly return `None`, which violates the explicit return type `str`.

**Comment by rexor12** [comment]
You're absolutely correct, in the case of `contextlib.suppress(...)` this is indeed the case. I tried to simplify my real issue and ended up with something this silly.

The following example, however, also produces the same Pylance error, in which case exceptions aren't caught and ignored by the asynchronous context manager:
```py
from asyncio.locks import Lock
import asyncio

async def get_text(lock: Lock) -> str:
    async with lock:
        # an exception raised here wouldn't be caught by the context manager
        return "done"

async def main():
    lock = Lock()
    print(await get_text(lock))

asyncio.run(main())
```

In my project, I have a similar piece of code for an asynchronous cache implementation where the getter uses the above construct with the lock.

Is it the expected behavior in this case, too?

**Comment by erictraut** [comment]
This behavior is related to a bug that was fixed about two weeks ago in pyright (the type checker that underlies pylance), but the fix hasn't made it to the production release of pylance yet. The fix is included in the prerelease ("insiders") version of pylance if you want to try it out.
