### ISSUE TITLE
Relative Path Support for python.analysis.extraPaths

### ISSUE THREAD

**Issue by Miladiouss** [microsoft/pylance-release#3078]
`"python.analysis.extraPaths"` in `settings.json` should handle relative paths, regex patterns, and VS Code variables reference such as `$workspaceFolder`. These future are not supported as of `v2022.7.40` on Linux systems.

**Comment by erictraut** [comment]
Relative paths are supported in `extraPaths`. Paths are relative to the workspace folder.

**Comment by Miladiouss** [comment]
I'm not sure how to document it but only the first one can resolve paths successfully. In the following example, `$workspaceFolder = "/home/username/projects/A/"` (i.e. where VS Code has been opened).

1. `"python.analysis.extraPaths": ["/home/username/projects/A/B/C",]`
2. `"python.analysis.extraPaths": ["B/C",]`
3. `"python.analysis.extraPaths": ["${$workspaceFolder}/B/C",]`
4. `"python.analysis.extraPaths": ["./B/C",]`

**Comment by erictraut** [comment]
Option 3 won't work, but the other three (including 2 and 4) should work fine. They will be interpreted as relative paths (relative to the workspace root). Are you opening a folder, or are you opening individual files? You need to open the folder.

To get additional logging to help you diagnose the problem, create a file called `pyrightconfig.json` in your workspace root, and add the following to that file: `{ "verboseOutput": true }`. Then look at the output tab in VS Code for pylance ("Python Language Server"). It will provide additional details for any imports that go unresolved.

**Comment by Miladiouss** [comment]
Noticed that the problem only exist for Jupyter Notebooks open via VS Code and Python files behave as expected. 
I did check to ensure that the Notebook File Root is set to `${fileDirname}`. `Path().resolve()` points to the directory containing the notebook.
Unfortunately, I'm not seeing any difference in the output tab with or without `pyrightconfig.json`.
