### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Edorta23** [microsoft/pylance-release#3079]
- Issue Type: `Bug`
- Extension Name: `vscode-pylance`
- Extension Version: `2022.7.40`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bschnurr** [comment]
Please update with a description and output logs 

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

closing for now
