### ISSUE TITLE
Code is unreachable false positive

### ISSUE THREAD

**Issue by pinguin999** [microsoft/pylance-release#3080]
## Environment data

-   Pylance v2022.7.41
-   Language Server version: 2022.7.41 (pyright 31ee1479) 
-   OS and version: Mac OSX 12.4 M1
-   Python version: CPython 3.9.13

## Code Snippet

```python
    def bla(self) -> bool:
        try:
            foo()
            return True
        except (ValueError, PermissionDenied):
            return False
        return False <- Pylance: Code is unreachable
```

## Expected behavior

The last line will be hit if the except block does not catch the exception.

## Actual behavior

Do not gray out the last line

**Comment by erictraut** [comment]
I think pylance is doing the right thing here. Under what circumstances will the last line be executed? If there is no exception raised in the try block, the first `return` statement will be executed. If there is an exception of type `ValueError` or `PermissionDenied`, the second return will be executed. If a different type of exception is raised, it will not be handled by the try/except, so the final `return` statement won't be executed.

**Comment by pinguin999** [comment]
Yes, you and pylance are right. If an other exception is thrown the function will exit with the exception and not continue execution. 
Thanks
