### ISSUE TITLE
Pyright no longer resolves modules in the directory containing notebooks

### ISSUE THREAD

**Issue by thomasaarholt** [microsoft/pylance-release#3088]
**Describe the bug**
In VSCode notebooks, I have been able to keep functions in a `process_data.py` file placed in the same directory as a notebook I am working with. That way I can move functionality out of the notebook and into the .py module to keep the notebook clean.

As of the latest pre-release version, pylance does not resolve the import, and so does not know anything about the functions I am importing. It does work in a regular `other.py` file. 

# fails in notebook
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/2721423/180410349-cba4dbd1-ada8-4464-947b-11e179a10cc2.png">

# works in regular .py files
<img width="910" alt="image" src="https://user-images.githubusercontent.com/2721423/180410699-c92ac48b-6580-4d25-894a-10a31e4ab8c0.png">

I've awkwardly bypassed this using the following try-except. pylance recognises imports via the `.process_data` relative import, but this raises an importerror when called on its own in the notebook :(

```python
try:
    from process_data import numeric_categorical_columns
    from .process_data import numeric_categorical_columns
except SyntaxError:
    print("uh oh, check imports")
except ImportError:
    pass
```

**VS Code extension or command-line**
Running Python extension pre-release version v2022.11.12021011

**Comment by heejaechang** [comment]
dupe - https://github.com/microsoft/pylance-release/issues/3017
