### ISSUE TITLE
Docstring tooltip not shown for nested imports

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#3093]
## Environment data

-   Language Server version: 2022.1.3 (pyright 98868f26)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): PSF Python v3.9

## Code Snippet

```python
import pandas.compat
```

## Repro Steps

1. Hover over the word `compat`

## Expected behavior

I would expect to see the `pandas.compat` module docstring in the tooltip.

## Actual behavior

I don't see it

![import-pandas-compat](https://user-images.githubusercontent.com/42288570/180641555-e1f73545-1f77-4867-8a25-29304f0529ed.gif)

If I change to `from pandas import compat` I see the docstring tooltip on the `compat` part but not the `pandas` part. It would be valuable also to have it on the `pandas` part.

![from-pandas-import-compat](https://user-images.githubusercontent.com/42288570/180641638-8badb3f5-5193-44ba-b722-267a6bdf2618.gif)

## Context

I'm trying to improve the user experience of the HoloViz ecosystem in VS Code. For example for [hvPlot](https://hvplot.holoviz.org/) like requested in https://github.com/holoviz/hvplot/issues/789.

hvPlot works by patching a data source like `pandas` when running `import hvplot.pandas` and I would like the users to be able to get relevant tooltips when hovering over the `hvplot` or `pandas` parts of the import.

The nested import `from hvplot.pandas` has been used by the community for a long time now and might be hard to change to `from hvplot import pandas`. This is what I can get currently on [PR](https://github.com/holoviz/hvplot/pull/793) where I've added docstrings to the modules.

![from-hvplot-import-pandas](https://user-images.githubusercontent.com/42288570/180640997-acc539e1-76ee-4507-8f8b-baba95b9edf5.gif)

Nested imports should be valid according to PEP8 https://peps.python.org/pep-0008/#imports, so I believe it would make sense to provide useful tooltips for these in VS Code.

## Logs

<details>
<summary>Logs</summary>
[Info  - 11.19.37] Pylance language server 2022.1.3 (pyright 98868f26) starting
[Info  - 11.19.37] Server root directory: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist
[Info  - 11.19.37] No configuration file found.
[Info  - 11.19.37] pyproject.toml file found at c:\repos\private\hvplot.
[Info  - 11.19.37] Setting pythonPath for service "hvplot": "c:\repos\private\hvplot\.venv\Scripts\python.exe"
[Info  - 11.19.37] Loading pyproject.toml file at c:\repos\private\hvplot\pyproject.toml
[Error - 11.19.37] Pyproject file "c:\repos\private\hvplot\pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 11.19.37] stubPath c:\repos\private\hvplot\typings is not a valid directory.
[Info  - 11.19.38] Assuming Python version 3.9
[Info  - 11.19.38] Assuming Python platform Windows
Search paths for c:\repos\private\hvplot
  c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib
  c:\repos\private\hvplot
  c:\repos\private\hvplot\typings
  c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stubs\...
  c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\bundled\stubs
  c:\Program Files\Python39\DLLs
  c:\Program Files\Python39\Lib
  c:\Program Files\Python39
  c:\repos\private\hvplot\.venv
  c:\repos\private\hvplot\.venv\Lib\site-packages
  c:\repos\private\hvplot
  c:\repos\private\hvplot\.venv\Lib\site-packages\win32
  c:\repos\private\hvplot\.venv\Lib\site-packages\win32\lib
  c:\repos\private\hvplot\.venv\Lib\site-packages\pythonwin
[Info  - 11.19.39] Searching for source files
[Info  - 11.19.39] Auto-excluding c:\repos\private\hvplot\.venv
[Info  - 11.19.39] Found 46 source files
[Info  - 11.19.39] Background analysis(1) root directory: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist
[Info  - 11.19.39] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setImportResolver
Background analysis message: ensurePartialStubPackages
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
IntelliCode model c:\Users\masma\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.2.11\cache\E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19
Background analysis message: getSemanticTokens full
[FG] parsing: c:\repos\private\hvplot\script.py (46ms)
[FG] parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 6ms] (243ms)
[FG] binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\builtins.pyi (73ms)
[FG] binding: c:\repos\private\hvplot\script.py (0ms)
[BG(1)] getSemanticTokens full at c:\repos\private\hvplot\script.py ...
[BG(1)]   parsing: c:\repos\private\hvplot\script.py (51ms)
[BG(1)]   parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 5ms] (239ms)
[BG(1)]   binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\builtins.pyi (74ms)
[BG(1)]   binding: c:\repos\private\hvplot\script.py (0ms)
[BG(1)]   parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 2ms] (17ms)
[BG(1)]   binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\typing_extensions.pyi (2ms)
[BG(1)]   parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\typing.pyi [fs read 0ms] (35ms)
[BG(1)]   binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\typing.pyi (23ms)
[BG(1)]   parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 1ms] (14ms)
[BG(1)]   binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (1ms)
[BG(1)]   parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\abc.pyi [fs read 1ms] (1ms)
[BG(1)]   binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\abc.pyi (1ms)
[BG(1)]   parsing: c:\repos\private\hvplot\.venv\Lib\site-packages\xarray\__init__.py [fs read 1ms] (19ms)
[BG(1)]   binding: c:\repos\private\hvplot\.venv\Lib\site-packages\xarray\__init__.py (1ms)
[BG(1)]   parsing: c:\repos\private\hvplot\hvplot\xarray.py [fs read 1ms] (14ms)
[BG(1)]   binding: c:\repos\private\hvplot\hvplot\xarray.py (2ms)
[BG(1)]   parsing: c:\repos\private\hvplot\.venv\Lib\site-packages\xarray\tutorial.py [fs read 1ms] (50ms)
[BG(1)]   binding: c:\repos\private\hvplot\.venv\Lib\site-packages\xarray\tutorial.py (4ms)
[Info  - 11.19.39] Indexer background runner(2) root directory: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-.
....
.....
.....
[FG] binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\typing.pyi (9ms)
[FG] parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 2ms] (12ms)
[FG] binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (3ms)
[FG] parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\abc.pyi [fs read 1ms] (2ms)
[FG] binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\typeshed-fallback\stdlib\abc.pyi (0ms)
[FG] parsing: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\bundled\stubs\pandas\testing.pyi [fs read 0ms] (7ms)
[FG] binding: c:\Users\masma\.vscode\extensions\ms-python.vscode-pylance-2022.1.3\dist\bundled\stubs\pandas\testing.pyi (0ms)
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
</details>

**Comment by debonte** [comment]
This was fixed in 2022.12.21. See #3636.
