### ISSUE TITLE
Goto definition doesn't work

### ISSUE THREAD

**Issue by artemijan** [microsoft/pylance-release#3096]
Hello, I've been searching for a while how to resolve this issue but I didn't find any solution. The issue, probably, is in the pylance but I'm not sure. I'm trying to override django's Serializer class
<img width="578" alt="image" src="https://user-images.githubusercontent.com/7948990/180668607-904fc0b6-4c5b-4487-8426-e2553b62cd19.png">
On the image you can see an error "_value_from_field: Unknown". I cannot go to definition of this method it just doesn't see down the inheritance in PythonSerialiser 
<img width="534" alt="image" src="https://user-images.githubusercontent.com/7948990/180668724-ed1f4b0f-ec32-4627-a1a8-162fe4570f2a.png">
I'm importing Serialiser class as following

```

from django.core.serializers.json import Serializer as JSONSerializer

class Serializer(JSONSerializer):

    def handle_field(self, obj, field):

        value = self._value_from_field(obj, field)

        return value

```

Could it be resolved by configuring pylance?
PS: django version 3.2.5

**Comment by bschnurr** [comment]
`django/core/serializers/base.pyi` stub for 'Serializer doesn't expose that private function

https://github.com/typeddjango/django-stubs/blob/56f9300d0d73787546b3dbcc4a589c98f3164993/django-stubs/core/serializers/base.pyi#L31

**Comment by artemijan** [comment]
Thank you, seems like I have 2 options, generate pyi files on my own for each module or use pycharm😅. Thank you, you saved my time!!!
