### ISSUE TITLE
Missing import from specified "python.analysis.extraPaths" in Notebook

### ISSUE THREAD

**Issue by 0nyr** [microsoft/pylance-release#3097]
I have a Missing Import Error while importing a custom package inside a Notebook, despite specifying the path inside python.analysis.extraPaths.

![Screenshot_from_2022-07-25_13-04-51](https://user-images.githubusercontent.com/47721040/180768373-d78e29b3-7a37-44aa-ae98-7f54531dab58.png)

## Environment data
 - Pylance v2022.7.40, 
 - Pylance language server 2022.7.40 (pyright bd00e0d1)
- Ubuntu 20.04.4 LTS
- Python 3.10.5 using Conda

 - Conda 4.13.0

## Code Snippet
Inside a Notebook:

```python
import sys
sys.path.append("/home/onyr/missing_import_custom_package/src")

from src.test_package import TestObject
obj_1 = TestObject("HelloWorld")
obj_1.print_name()
```

## Repro Steps
1. Just download this repo where I have setup a custom example : [0nyr/pylance_issue_illustration_missing_import](https://github.com/0nyr/pylance_issue_illustration_missing_import)
2. Create a conda venv.
3. Load the notebook in VSCode and select the conda venv.
4. You should see the MissingImport error.

## Expected behavior
No import error. And type hinting.

## Actual behavior
Missing Import error and no type hinting.

## Logs

See https://github.com/0nyr/pylance_issue_illustration_missing_import/blob/main/python.log

**Comment by heejaechang** [comment]
we don't support dynamic behavior like below.
```python
import sys
sys.path.append("/home/onyr/missing_import_custom_package/src")
```

but, we should provide a way to add extraPath in notebook.

**Comment by debonte** [comment]
This doesn't repro for me anymore. My guess is that you were hitting https://github.com/microsoft/pylance-release/issues/3208.

`extraPaths` also appears to be working fine in notebooks, but is unnecessary in your sample.

@0nyr, can you upgrade to the latest Pylance and see if this is also fixed for you?

**Comment by 0nyr** [comment]
Ok, I did new tests. I have no more problems.

![capture no more error](https://github.com/0nyr/pylance_issue_illustration_missing_import/blob/main/img/screenshot_no_more_error_2022_10_19.png)

Thank you, you can close the issue.
