### ISSUE TITLE
Pylance does not detect any problems using typing.Protocol

### ISSUE THREAD

**Issue by mr-bjerre** [microsoft/pylance-release#310]
The following snippet does not suggest any issues in pylance

```python
from typing import Protocol


class MyProtocol(Protocol):
    def my_method(arg: str) -> dict:
        ...


class MyClass(MyProtocol):
    pass
```

I'd expect that `MyClass` had to implement `my_method`?

**Comment by erictraut** [comment]
This is not how `Protocol` works. A protocol class is any class that derives directly from `typing.Protocol`. In your example, `MyProtocol` is a protocol class, but `MyClass` is not. It doesn't make sense for a non-protocol class to derive from a protocol class, as your example shows.

A protocol class defines the methods, class variables, and instance variables that must be implemented for other classes to match that protocol.

This example shows the correct use of a protocol class.

```python
from typing import Protocol

class MyProtocol(Protocol):
    def my_method(arg: str) -> dict:
        ...

class MyClass1:
    pass

class MyClass2:
    def my_method(arg: str) -> dict:
        return {}

# Pylance generates an error because here because MyClass1
# does not match the protocol defined by MyProtocol.
m1: MyProtocol = MyClass1()

# No error is generated here.
m2: MyProtocol = MyClass2()
```

For more details on protocol classes, refer to [PEP 544](https://www.python.org/dev/peps/pep-0544/).

**Comment by mr-bjerre** [comment]
Sorry my mistake - thanks for clarifying.
