### ISSUE TITLE
Cannot install from vsix

### ISSUE THREAD

**Issue by ButchGis** [microsoft/pylance-release#311]
## Environment data

-   Language Server version: XXX
-   OS and version: win 10 1809 17763.1397
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.6 and up; Anaconda 2019.03 

## Expected behaviour

I am in an isolated newtwork situation. I have access to python / conda resources and I have the pylance.vsix. I cannot get vs code version 1.47.3 to install the pylance extension from the vsix.

## Actual behaviour

get toast message - extension/package.json not found inside zip.

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by judej** [comment]
@ButchGis, we updated the required version of VS Code to be 1.48.0 or above. Would you please update and try again? Thanks!

**Comment by ButchGis** [comment]
I will need to wait until the 1.48 vs code update is available at my closed network location.
Thank you for your quick response.

________________________________

**Comment by ButchGis** [comment]
I have tried today with version code version 1.48.2 on linux, with vsix _2020.9.4.vsix.
I recieved the same error message as before: extension/package.json not found inside zip.

**Comment by jakebailey** [comment]
Very confusing, the VSIX is the zip and definitely contains extension/package.json. How are you trying to sideload the VSIX? Are you using the "install VSIX" option in the command palette or the extension menu?

**Comment by ButchGis** [comment]
I used the extension menu.
________________________________

**Comment by ButchGis** [comment]
I just retried with command palette. same error.
________________________________

**Comment by jakebailey** [comment]
At this point I'm at a loss. Any chance you could take an md5 or sha-1 hash of the VSIX just to verify it hasn't been corrupted in some manner?

**Comment by ButchGis** [comment]
md5 = 6e96fdd7be0a742114070705287d8d5
________________________________

**Comment by jakebailey** [comment]
The hash I get when I download it from the marketplace is 07FA45B70B22691BB17FCA02954BF96A, so I'm wondering whether or not the VSIX you grabbed is correct or not. Redownloading a day later gets the same file. https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

**Comment by ButchGis** [comment]
I see. My internal version of the vsiz was corrupt. It did not, in fact, have the package.json file. Who knows what else.  I obtained a new copy of the vsix and it did install properly.

Thank you for the support.

________________________________

**Comment by jakebailey** [comment]
Thanks for confirming!
