### ISSUE TITLE
Not detecting some optional fields in pydantic models

### ISSUE THREAD

**Issue by eseglem** [microsoft/pylance-release#3115]
## Environment data

-   Language Server version: v2022.7.40
-   OS and version: WSL2 Ubuntu 20.04.4 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Code Snippet

```python
from typing import Optional
from pydantic import BaseModel, Field  # pydantic==1.9.1

class Foo(BaseModel):
    a: str = Field("a")
    b: int
    c: Optional[int]
    d: Optional[int] = None

f = Foo(b=2)   # No error, and f is Foo(a='a', b=2, c=None, d=None)
```

## Expected behavior

Nothing reported by pylance.

## Actual behavior

Pylance reports `Arguments missing for parameters "a", "c"`

## Additional Explanation

The `Field("a")` in pydantic sets the default value to `"a"` so it is not required. This is an overly simple example, and `Field` would normally be used with additional validation parameters, but those do not affect this issue.
And `c` is optional so pydantic also sets it to `None`. 

Additionally mypy, with the pydantic.mypy plugin, recognizes that `Foo(b=2)` is valid without complaint. 

I know there are other ways to define `Foo` such that it does not complain here, but I came across this when calling a third party library so it is not as simple to make those changes.

**Comment by erictraut** [comment]
The behaviors that you are citing above are specific to pydantic, and pyright (the type checker that underlies pylance) has no specific knowledge of pydantic. It does have support for general dataclass-like behaviors. If you stick with those more general behaviors, pyright will work fine with pydantic.

In your example, you would need to make the following modifications to the class definition:

```python
class Foo(BaseModel):
    a: str = Field(default="a")
    b: int
    c: Optional[int] = None
    d: Optional[int] = None
```

**Comment by eseglem** [comment]
I had forgotten that it was pyright under the hood. A reminder about that would be nice in the issue that Pylance is reporting. 

I did manage to find more explanation as to why and what is happening now that I remember that part. In fact there is a whole page in the docs I missed in my hurry.  https://pydantic-docs.helpmanual.io/visual_studio_code/#strict-errors 

I guess the best thing to do is submit a PR to update the other library. I just wanted to understand more about what was going on.

**Comment by vincentsarago** [comment]
sorry @eseglem I think we can move forward with this (maybe @geospatial-jeff can also double check). 

Could you please update the changelog 🙏
