### ISSUE TITLE
Debug Failure

### ISSUE THREAD

**Issue by peacefulstreamdev** [microsoft/pylance-release#3117]
## Environment data

-   Language Server version: v2022.7.40
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.12, Anaconda

## Code Snippet

```from django import forms```

## Expected behavior

No error should occur.

## Actual behavior

[{
	"resource": "/c:/Users/Jake/VS Code Projects/peaceful-stream-webdev/profiles/forms.py",
	"owner": "_generated_diagnostic_collection_name_#5",
	"severity": 8,
	"message": "An internal error occurred while binding file \"c:\\Users\\Jake\\VS Code Projects\\peaceful-stream-webdev\\profiles\\forms.py\": Error: Debug Failure. createKeyForReference received unexpected index type\n    at createKeyForReference (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\codeFlowTypes.ts:237:13)\n    at createKeyForReference (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\codeFlowTypes.ts:218:25)\n    at createKeyForReference (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\codeFlowTypes.ts:218:25)\n    at C.visitAssignment (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:849:50)\n    at C.visitNode (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:132:29)\n    at C.walk (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at forEach (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:107:22)\n    at Array.forEach (<anonymous>)\n    at C.walkMultiple (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:105:15)\n    at C.walk (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:100:18)\n    at C._walkStatementsAndReportUnreachable (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:2583:22)\n    at C.visitSuite (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:345:14)\n    at C.visitNode (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:330:29)\n    at C.walk (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at callback (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:1148:18)\n    at C._trackCodeFlowExpressions (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:3236:9)\n    at C._bindLoopStatement (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:3258:49)\n    at C.visitFor (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:1147:14)\n    at C.visitNode (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:205:29)\n    at C.walk (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at C._walkStatementsAndReportUnreachable (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:2583:22)\n    at C.visitSuite (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:345:14)\n    at C.visitNode (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:330:29)\n    at C.walk (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\parseTreeWalker.ts:98:37)\n    at Object.callback (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:545:22)\n    at C._bindDeferred (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:4140:22)\n    at C.bindModule (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\binder.ts:298:14)\n    at callback (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\sourceFile.ts:1197:28)\n    at s.timeOperation (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\common\\timing.ts:40:20)\n    at callback (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\sourceFile.ts:1184:38)\n    at t.LogTracker.log (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\common\\logTracker.ts:43:20)\n    at t.SourceFile.bind (c:\\Users\\Jake\\.vscode\\extensions\\ms-python.vscode-pylance-2022.7.40\\dist\\pyright-internal\\src\\analyzer\\sourceFile.ts:1181:33)",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by heejaechang** [comment]
looks like an assert from pyright code flow analyzer

**Comment by erictraut** [comment]
This is a bug that was fixed in pyright over two weeks ago but has not yet been incorporated into a production version of pylance. The latest version of pyright is 1.1.264; this bug was fixed in 1.1.261. The latest production version of pylance was based on pyright 1.1.260.

To work around the issue, you can install the latest prerelease (insiders) version of pylance. Or you can wait for the next production version to be released.
