### ISSUE TITLE
 missing new line from dict() help mouse hover

### ISSUE THREAD

**Issue by Devid-Ba** [microsoft/pylance-release#3118]
<h3> Environment data </h3>

-   Language Server version: 2022.7.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. hover over `dict()` 

<h3> Expected behavior </h3>

newline after `d = {}`.

<h3> Actual behavior </h3>

![Screenshot from 2022-07-31 17-32-36](https://user-images.githubusercontent.com/97880699/182052668-a911e935-96c3-4ea0-931a-611675c1ca38.png)

screen shot from `help(dict)`
![Screenshot from 2022-07-31 17-33-37](https://user-images.githubusercontent.com/97880699/182052810-5feb9381-7f00-40fe-8909-4d6484fb2292.png)

<h3> Logs </h3>

```
XXX
```

**Comment by heejaechang** [comment]
doc string formatter issue.

**Comment by rchiodo** [comment]
Builtins may then have to be formatted literally. Or at least special cased to add literal indents.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246100-13-June-2024-PreRelease)

**Comment by rchiodo** [comment]
The fix for this issue is behind an experimental feature flag:

```json
"python.analysis.supportRestructuredText": true
```

If you want to try out our new restructuredText support, enable this flag. It's behind a flag at the moment until we can make sure it handles all the possible Sphinx/GoogleDoc/Epytext scenarios that customers need. Please log additional issues if this setting isn't working out for you.

Thanks :)
