### ISSUE TITLE
Pylance reports an error for Pydantic constrained types

### ISSUE THREAD

**Issue by lonelyteapot** [microsoft/pylance-release#3119]
### Environment data

-   Language Server version: 2022.7.40
-   Python version: 3.10.2
-   pydantic version: 1.9.1
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

### Code Snippet

```python
from pydantic import BaseModel

class Model(BaseModel):
    name: constr(strip_whitespace=True, to_lower=True)

```

### Expected behavior

No error is reported

### Actual behavior

An error is reported on the `constr(...)` type annotation:  
`Illegal type annotation: call expression not allowed`

The same happens for other [constrained types](https://pydantic-docs.helpmanual.io/usage/types/#constrained-types).

**Comment by erictraut** [comment]
Pyright is correct in issuing this error. The Python type system doesn't allow the use of function calls within type annotations, so the code above will not work.

I'm not familiar with constrained types in pydantic, so I don't know the proper way to specify constrained types such that they don't violate the basic rules of static typing. I recommend posting a question in the pydantic discussion forum.
