### ISSUE TITLE
reportMissingModuleSource

### ISSUE THREAD

**Issue by M-Mohtashami** [microsoft/pylance-release#3121]
<h3> Environment data </h3>

-   Language Server version: 2022.7.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by heejaechang** [comment]
please, add more info and re-activate the issue.
