### ISSUE TITLE
"parameter is not accessed" for `abstractclassmethod`/`abstractstaticmethod`

### ISSUE THREAD

**Issue by dasturge** [microsoft/pylance-release#3123]
## Environment data

-   Language Server version: 2022.7.40
-   OS and version: Ubuntu 18.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9 conda

## Code Snippet

```python
class MyAbstractClass(ABC):

    @abstractclassmethod
    def myclassmethod(cls, input_1):  # input_1 not accessed warning
        ...

    @abstractstaticmethod
    def mystaticmethod(input_1):  # input_1 not accessed warning
        ...

    @abstractmethod
    def from_json(self, input_1):  # expected behavior, pylance ignores this
        ...
```

## Expected behavior

No warning should pop up, just like for abstract methods

**Comment by erictraut** [comment]
You are using `@abstractclassmethod` here, which has been deprecated since Python 3.3. You should use `@classmethod` in conjunction with `@abstractmethod` instead. The same is true for `@abstractstaticmethod`.
