### ISSUE TITLE
Accessibility: HTML entities are not escaped when pressing control+shift+space

### ISSUE THREAD

**Issue by TheQuinbox** [microsoft/pylance-release#3125]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Windows 10 21H2 (x64) build 19044.1766

Steps to Reproduce:

1. Open a Python file.
2. Type "dict()" without the quotes.
3. Start Narrator, NVDA, or another Windows screen reader.
4. press control+shift+space while inside the ().
5. I hear:
```
__map: SupportsKeysAndGetItem[_KT@dict, _VT@dict], dict() -&gt; new empty dictionary dict(mapping) -&gt; new dictionary initialized from a mapping object's\ &nbsp;&nbsp;&nbsp;&nbsp;(key, value) pairs\ dict(iterable) -&gt; new dictionary initialized as if via:\ &nbsp;&nbsp;&nbsp;&nbsp;d = {} for k, v in iterable:\ &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d\[k\] = v\ dict(\*\*kwargs) -&gt; new dictionary initialized with the name=value pairs\ &nbsp;&nbsp;&nbsp;&nbsp;in the keyword argument list. For example: dict(one=1, two=2), hint 
```

This is extremely hard to read to say the least, with all the HTML entities being spoken. It would be great if these could be escaped, and turned into standard symbols.

**Comment by bschnurr** [comment]
I'm not escaping anything in the hint, but the hint should just be the type.  Maybe its reading the onHover text?

**Comment by bschnurr** [comment]
hmm. NVDA seems to handle it fine.

**Comment by TheQuinbox** [comment]
Just tested again, and it doesn't on my side. Would an audio recording possibly help?

**Comment by bschnurr** [comment]
```python
dict(|)
```

cursor at `|` correct?

**Comment by bschnurr** [comment]
video would help

**Comment by luabud** [comment]
I wasn't able to reproduce it either, unfortunately. I'm wondering if there may be an extension other than Pylance that is providing these parameter hints. Perhaps it may help if all extensions but the Pylance and Python ones are disabled, and seeing if the problem still occurs?

**Comment by TheQuinbox** [comment]
Disabling all extensions that aren't Python fixed it. Weird, and going to be a pain to trace, but not related to Pylance, so closing it.
