### ISSUE TITLE
No attribute docstring in hover information for parameter input of type Callable

### ISSUE THREAD

**Issue by Fate6174** [microsoft/pylance-release#3135]
<h3> Environment data </h3>

-   VS Code version: 1.69.2
-   Language Server version: 2022.8.10
-   OS and version: linux x64 (Manjaro)
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.5

<h3> Code Snippet </h3>

```python
from collections.abc import Callable

class MyClass():
    def __init__(
            self,
            number : float,
            func : Callable[[float], float]
        ) -> None:
        self.number = number
        """A given number"""
        self.func = func
        """A given function"""
```

<h3> Expected behavior </h3>

The hover information should contain the variable docstring as is happening for `number` (type `float`).
![image](https://user-images.githubusercontent.com/53304999/182842492-a72b5e59-007b-44d6-a4b2-ca6cd3285aa0.png)

<h3> Actual behavior </h3>

The hover information does not contain the variable docstring for `func` (type `Callable[[float], float]`).
![image](https://user-images.githubusercontent.com/53304999/182842706-38920d87-8aee-4306-aee5-0ea34810137f.png)

**Comment by heejaechang** [comment]
This issue has been fixed in version 2022.8.12, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022812-8-August-2022)
