### ISSUE TITLE
Pylance 2022.08.10 crashes with Jupytext

### ISSUE THREAD

**Issue by tratigan-drw** [microsoft/pylance-release#3136]
## Environment data

-   Language Server version: 2022.08.10
-   OS and version: Ubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 miniconda environment

## Code Snippet

This can be replicated on an empty Python file

## Repro Steps

1. Install [jupytext for notebooks](https://marketplace.visualstudio.com/items?itemName=congyiwu.vscode-jupytext)
2. Create an empty python file `foo.py`
3. Click "Open as a Jupyter Notebook"

## Expected behavior

Pylance does not crash (Pylance does not crash on any version before 2022.08.10)

## Actual behavior

Pylance crashes

## Logs

```
Error: Debug Failure. verifyCellChainIsLinear should only be called on notebooks
    at _0x3244cf (/home/tratigan/.vscode/extensions/ms-python.vscode-pylance-2022.8.10/dist/server.bundle.js:1:396859)
    at _0x270681._onDidOpenNotebookDocument (/home/tratigan/.vscode/extensions/ms-python.vscode-pylance-2022.8.10/dist/server.bundle.js:1:369871)
[Error - 12:00:07 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

```

Full logs:
[pylance_logs.txt](https://github.com/microsoft/pylance-release/files/9261821/pylance_logs.txt)

**Comment by heejaechang** [comment]
I tried but I got this

![image](https://user-images.githubusercontent.com/1333179/183240641-08c23286-ea4c-4516-8ebc-a6ba38c7fb25.png)

and I am not sure where the log is?

**Comment by hfmamh** [comment]
I'm dealing with the error, but I haven't installed jupytext. Whenever I open a jupyter notebook, pylance server crashes.

**Comment by hwancheol-jeong** [comment]
Suffering with the same error :(

**Comment by vsethi13** [comment]
I too. As soon as I open a jupyter notebook, the pylance server crashes. None of the suggestions in [this previously resolved issue](https://github.com/microsoft/vscode-python/issues/13679) helped me.

**Comment by heejaechang** [comment]
there is a bug with untitled.ipynb. we will releasing a fix in pylance prerelease soon.

**Comment by heejaechang** [comment]
related to https://github.com/microsoft/pylance-release/issues/3126

**Comment by vsethi13** [comment]
Switching to v2022.08.12 fixes this! Thanks @heejaechang :)
