### ISSUE TITLE
python core extension calls us multiple times when new notebook (untitled) is opened.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#3137]
it looks like the bug is on python core extension as long as I can see. but we probably need to dig in a bit more before giving the bug to python core ext.

**Comment by debonte** [comment]
@heejaechang, can you provide logs that show the problem? I just tried creating a new notebook both with LSP notebooks and concat doc ("python.pylanceHandlesNotebooks": true). I didn't see any redundant messages from Python in the LSP scenario. In the concat doc case I saw what looked like duplicate inlayHint requests, but that was it.

**Comment by heejaechang** [comment]
thank you Erik for taking a look! let me close the issue.
