### ISSUE TITLE
Go to Definition erratic behavior

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#314]
> Thanks for your feedback! We have recently released a new and more performant language server called Pylance which likely solves these issues you are reporting.  You can download [Pylance](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/) from the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and install it alongside the core Python extension. Because our team's development efforts have shifted to support the new language server, we'd encourage you to try it out. If you try out Pylance and this issue persists, you can open an issue on the [pylance-release repo](https://github.com/microsoft/pylance-release).

Thanks for the reply !

I already did the test with Pylance and actually I got worse results.
When I select pylance as language server and try the same example above what happens is
ctrl + click doesn't do anything
f12 -> no definition found for "MediaSerializer"

_Originally posted by @weberxw in https://github.com/microsoft/vscode-python/issues/13751#issuecomment-685946886_

**Comment by weberxw** [comment]
Hi @jakebailey have you seen the original Issue (https://github.com/microsoft/vscode-python/issues/13751#issuecomment-685946886), I had posted some of the code there. You need more? I'm not having any import problems.

**Comment by jakebailey** [comment]
If possible, could you hover over the symbol you're trying to go-to-def on and see if it's resolved properly?

**Comment by jakebailey** [comment]
I would see this: https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

But I don't think you've provided the codebase in that previous thread to be able to look at the general code structure, in fact you've censored it out, so it's hard to say.

The main thing to look for is if all of your code is import rooted from a folder that isn't the workspace root, like src, or maybe that `apideduca` folder I'm seeing in your breadcrumbs.

**Comment by weberxw** [comment]
@jakebailey pylance + this **python.analysis.extraPaths** tip solved my problem !!! Thanks a lot :)
