### ISSUE TITLE
Import "numpy" could not be resolved Pylance(reportMissingImports)

### ISSUE THREAD

**Issue by khteh** [microsoft/pylance-release#3141]
## Environment data

v2022.8.10
-   Language Server version: Pylance language server 2022.8.10 (pyright 6fa755c0)
-   OS and version: Ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4

## Code Snippet

```python
import numpy as np
def square(x):
    return x * x
```

## Repro Steps

`Import "numpy" could not be resolved Pylance(reportMissingImports)` Error!
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/src/jupyter-notebooks/notebook1.ipynb Cell 3 in <cell line: 1>()
----> [1](vscode-notebook-cell:/usr/src/jupyter-notebooks/notebook1.ipynb#W2sZmlsZQ%3D%3D?line=0) import numpy as np
      [2](vscode-notebook-cell:/usr/src/jupyter-notebooks/notebook1.ipynb#W2sZmlsZQ%3D%3D?line=1) def square(x):
      [3](vscode-notebook-cell:/usr/src/jupyter-notebooks/notebook1.ipynb#W2sZmlsZQ%3D%3D?line=2)     return x * x

ModuleNotFoundError: No module named 'numpy'
```
XXX

## Logs

```
XXX
```

**Comment by khteh** [comment]
https://stackoverflow.com/questions/73257370/python-3-10-4-import-numpy-could-not-be-resolved-pylancereportmissingimports/73257576#73257576

**Comment by lybPigff** [comment]
Maybe you can try the conda interpreter

**Comment by harisalimughal** [comment]
check numpy version by "pip show numpy" on cd

**Comment by harisalimughal** [comment]
check numpy version by "pip show numpy" on cmd

**Comment by oncealong** [comment]
I found a situation and a solution.
My `which python3` is not the `python3` in the conda environment, and `pyright --verbose .` shows that it is looking for `python3`. 
So I set the PATH path and then it can be executed successful.

```
> which python3
/opt/homebrew/bin/python3
> export PATH=/opt/homebrew/Caskroom/miniforge/base/envs/pyright/bin:$PATH
> pyright --verbose .
```
