### ISSUE TITLE
How do I implement a "bothmethod" decorator with correct type annotations and docstring?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#3142]
## Context

I am a user of [holoviz/param](https://github.com/holoviz/param). I would like it to VS Code to be able to provide useful tooltips for this library. One issue is described in https://github.com/holoviz/param/issues/646#issuecomment-1206720384.

Basically one of its classes [ParameterizedFunction](https://github.com/holoviz/param/blob/2958f6327ad3a5222eb773801e3e46f6130d9f65/param/parameterized.py#L3613) has a method `instance` that can be used both as a class and and instance method. Its defined using a custom `@bothmethod` decorator. For examples of using this function check out this [link](https://param.holoviz.org/user_guide/ParameterizedFunctions.html).

The `ParameterizedFunction` class and the `instance` method is used in various places across the HoloViz ecosystem and unfortunately VS Code cannot provide useful tooltips for this method. This makes it hard to use HoloViz and VS code together.

Below I've tried to provide a minimum, reproducible example of what I would like working.

I've tried to google search and experiment to find a solution without luck.

## Code

```python
from functools import wraps, partial

class bothmethod(object): # pylint: disable-msg=R0903
    """
    'optional @classmethod'

    A decorator that allows a method to receive either the class
    object (if called on the class) or the instance object
    (if called on the instance) as its first argument.

    Code (but not documentation) copied from:
    http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/523033.
    """
    # pylint: disable-msg=R0903

    def __init__(self, func):
        self.func = func

    # i.e. this is also a non-data descriptor
    def __get__(self, obj, type_=None):
        if obj is None:
            return wraps(self.func)(partial(self.func, type_))
        else:
            return wraps(self.func)(partial(self.func, obj))

class MyClass():
    a=0

    @bothmethod
    def instance(self_or_cls)->'MyClass':
        """Instance docstring"""
        if isinstance(self_or_cls,type):
            cls = self_or_cls
            obj = cls()
            obj.a = 1
        else:
            cls = self_or_cls.__class__
            obj = cls()
            obj.a = 2
        
        return obj
    
obj = MyClass.instance()
assert obj.a==1
obj = obj.instance()
assert obj.a==2
print("done")
```

```bash
$ python script.py
done
```

## Incomplete Intellisense

I would like the docstring and correct types to be understood by pyright/ pylance/ vs code such that tab completion and tooltips work.

![image](https://user-images.githubusercontent.com/42288570/183237918-23b855b4-6ea1-4d9c-98ce-fdc4008d2a69.png)

![image](https://user-images.githubusercontent.com/42288570/183237957-3ebf3955-a647-470f-9244-55e6af5c8c24.png)

![image](https://user-images.githubusercontent.com/42288570/183237981-c93098bd-417e-46ab-a55c-ceaaa870fc57.png)

![image](https://user-images.githubusercontent.com/42288570/183238008-be48e348-1438-4487-8c37-7119cad0e94c.png)

It would also be *nice* to be able to avoid reported issues like the one below.

![image](https://user-images.githubusercontent.com/42288570/183238078-6aac1cec-b6b9-419d-8308-d4cfb53cef12.png)

## Question

**How do I solve this problem?**

If I can solve the problem I would contribute the solution to Param.

**Comment by erictraut** [comment]
What you're trying to do here is highly unusual, and the Python static type system doesn't have a great answer for hybrid class/instance methods.

The best solution I can offer is the following, which I think gets you most of what you want. It preserves the parameter signature, return type, and docstring of the decorated method.

```python
_P = ParamSpec("_P")
_R = TypeVar("_R")


class bothmethod(Generic[_P, _R]):
    def __init__(self, func: Callable[Concatenate[Any, _P], _R]) -> None:
        self.func = func

    def __get__(
        self, obj: object | None, type_: type | None = None
    ) -> Callable[_P, _R]:
        if obj is None:
            return wraps(self.func)(partial(self.func, type_))
        else:
            return wraps(self.func)(partial(self.func, obj))
```

**Comment by MarcSkovMadsen** [comment]
Thanks.

I've tried to use with Python 3.9 and `typing_extensions=4.3.0` but neither will let me import it.

![image](https://user-images.githubusercontent.com/42288570/183238841-2c07a795-9335-4597-97d8-f8eab13dbf70.png)

Is this only available in Python 3.10? (Param currently supports 3.7+).

**Comment by MarcSkovMadsen** [comment]
A specific solution instead of a general one would also be helpful because the next version of Param only uses the `@bothmethod` decorator in this one place.

**Comment by erictraut** [comment]
`ParamSpec` and `Concatenate` were added to `typing` in Python 3.10. To use them in Python 3.7, you need to use `typing_extensions`. Version 4.3.0 should work fine, so I'm not sure why you're having trouble with the imports. Make sure you have the correct Python interpreter selected and that you installed `typing_extensions` into that environment.
