### ISSUE TITLE
Nested types cannot reference their own type annotations

### ISSUE THREAD

**Issue by stfujnkk** [microsoft/pylance-release#3143]
## Environment data

-   Language Server version: 2022.8.10 (pyright 6fa755c0)
-   OS and version: Windows10
-   Python version: 3.9.12 conda

## Code Snippet

![image](https://user-images.githubusercontent.com/52458236/183320251-5167f5b3-0870-4d99-b742-e6325c11a924.png)
```python
class Node:
    __slots__ = ['val', 'node']
    def push(node:Node):
        pass
    pass
```

**Comment by erictraut** [comment]
This is a limitation of the Python runtime, not pylance. If you attempt to run the above code, you'll see a runtime exception.

There are two ways to work around this:
1. Add `from __future__ import annotations` to the top of your source file. Refer to [PEP 563](https://peps.python.org/pep-0563/) for details.
2. Enclose the annotation in quotes (`"Node"`). Refer to [PEP 484](https://peps.python.org/pep-0484/#forward-references) for details.
