### ISSUE TITLE
⚡ Feature Request for auto-import libraries from outside current working folder (e.g. from python poetry environment)

### ISSUE THREAD

**Issue by fcabrita** [microsoft/pylance-release#3152]
When developing with python, I am using several different repositories inside my workspace, which are all part of a bigger project. I am using poetry to manage the dependencies between repositories.
When I try to use the auto-import feature (Ctrl+.) VSCode is unable to find imports from outside the current repository.

I would like to request support for imports which are part of the current working environment even if they are located outside the current working repository, something like pycharm does.

**Comment by heejaechang** [comment]
this looks like a dup of https://github.com/microsoft/pylance-release/discussions/2614

it sounds like you are working with multiple repos that has dependency each other. people usually use multi workspace set up for it and each repo become a root of the workspaces.

if it is the same case, please upvote the discussion. if not, please, reopen this issue.
