### ISSUE TITLE
Docstrings missing in django, but go-to-def goes to a place with docstrings

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pylance-release#316]
Copied from @cpbotha in https://github.com/microsoft/pylance-release/issues/170#issuecomment-686438379.

I am running into this issue with Django as well.

PyLance is showing the docstring-less function signature from django-stubs (which it comes bundled with) instead of the docstring in the actual Django source code.

What I gather from https://github.com/microsoft/pylance-release/issues/170#issuecomment-663719941 above is that PyLance *should* use type stubs for type info and source code for docstrings. However, with Django (for example) this is clearly not the case.

For `django.db.models.ForeignKey`, as one example, PyLance in VSCode shows only the signature on hover:

![image](https://user-images.githubusercontent.com/937871/92112119-99b48c80-eded-11ea-90e8-4838e1988cab.png)

Although the source clearly has a docstring, and VSCode even offers to take me there with `Go to definition`:

![image](https://user-images.githubusercontent.com/937871/92112220-c1a3f000-eded-11ea-80ab-fa4f041dfa09.png)

Ideally hover would show the type information but also any docstring.

**Comment by jakebailey** [comment]
Tracked this one down, it depends on how you use it.

When you just have the type itself, you get a hover:

![image](https://user-images.githubusercontent.com/5341706/93951451-3a1a1480-fcfb-11ea-9e59-abebf637f3a7.png)

Completing it also works:

![image](https://user-images.githubusercontent.com/5341706/93951463-41412280-fcfb-11ea-9425-143b2a0fbb8d.png)

However, once it's in a call expression, the docstring goes away:

![image](https://user-images.githubusercontent.com/5341706/93951486-528a2f00-fcfb-11ea-92c1-758f248dd89b.png)

This makes some sense, as we'd typically try and show the docstring for the constructor here, but this class doesn't have one. It's likely that we should fall back to showing the class's docstring if the constructor is missing one.

**Comment by cpbotha** [comment]
> This makes some sense, as we'd typically try and show the docstring for the constructor here, but this class doesn't have one. It's likely that we should fall back to showing the class's docstring if the constructor is missing one.

Of course you're right, I just confirmed. :)

Showing the class's docstring when constructor has none would indeed be convenient, but I see now that in this case the Django source does not offer much in terms of constructor parameter documentation in any case.

Thanks again for looking into this!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.6, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202096-23-september-2020
