### ISSUE TITLE
Not all pylance problems listed in the "Problems" section are annotated/decorated with large amounts of problems

### ISSUE THREAD

**Issue by SimonSchick** [microsoft/pylance-release#3160]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

All problems are correctly annotated OR a warning is shown that not ALL problems are shown in the view (not problems tab).

vs.

Some errors hidden

See:
<img width="731" alt="image" src="https://user-images.githubusercontent.com/3259089/183515753-2afa5b95-8cb9-4a7a-b549-f5c29c76c12e.png">

The IDE is aware of the error (via `Problems` tab), but doesn't show the squiggly line to highlight it, it *does* show the fix suggestion though.

## Steps to reproduce:

Have a file with lots of problems, see above, been unable to repro this exact issue outside of prod code.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Telemetry level is off
Experiments are disabled, only manually opted experiments are active.
LSP Notebooks experiment is disabled -- Jupyter disabled or not installed
LSP Notebooks interactive window support is disabled -- not in LSP Notebooks experiment
Python interpreter path: ./.env/bin/python
Starting Pylance language server.
> ./.env/bin/python ~/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/linter.py -m pylint --init-hook "import sys; sys.path.append(".")" ./common/integrations/slack.py
cwd: .
##########Linting Output - pylint##########

[]

> ./.env/bin/python ~/.vscode/extensions/ms-python.python-2022.12.0/pythonFiles/linter.py -m pylint --init-hook "import sys; sys.path.append(".")" ./common/integrations/slack.py
cwd: .
##########Linting Output - pylint##########

[]

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

envFile: "<placeholder>"

languageServer: "Pylance"

linting
• pylintArgs: "<placeholder>"

formatting
• provider: "black"
• blackPath: "<placeholder>"

```

</p>
</details>

Extension version: 2022.12.0
VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.21GB free)|
|Process Argv|--crash-reporter-id 0731fb54-df68-48c8-9bc7-cb94d92db4d8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by erictraut** [comment]
I'm guessing that you have updated your theme colors such that the squiggly lines are the same color as the background, so they're no longer visible. Could you review your settings and see if that might explain what you're seeing?

**Comment by SimonSchick** [comment]
This is not the case, other errors are correctly annotated.
I should also note that not only is the squiggly lines not showing, but intellisense isn't showing the popup either. The only thing that does show up is the 💡 icon, the gutter isn't showing any issues either.

Other errors in the same file are displayed as expected

**Comment by bschnurr** [comment]
Are you using open folder or open file mode?  after editing the file does it fix itself?

**Comment by SimonSchick** [comment]
- openFile
- no

**Comment by bschnurr** [comment]
same behaviour in open folder?

**Comment by SimonSchick** [comment]
To be clear, are you refering to `python.analysis.diagnosticMode`?

**Comment by bschnurr** [comment]
Sorry, I mean VSCode->File->Open Folder

**Comment by SimonSchick** [comment]
- I have that set to `openFilesOnly`.
- Opening the file individually vs. as part of a folder makes no difference in the erro reporting

Also it seems that *pylint* output is also truncated eg. not shown as part of this issue so this is likely an issue with the annotation platform, not analysis itself, I will attach the logs shortly.

**Comment by SimonSchick** [comment]
[logs.txt.zip](https://github.com/microsoft/pylance-release/files/9293737/logs.txt.zip)

Please note that these logs have been redacted.

**Comment by SimonSchick** [comment]
I found the culprit.

In our `.vscode/settings.json` file we had this bit:

```
  "terminal.integrated.env.linux": {
    "PYTHONPATH": "."
  },
  "terminal.integrated.env.osx": {
    "PYTHONPATH": "."
  },
```

This apparently really messes with mypy, removing it resolved the issue, I do consider this issue closed.
