### ISSUE TITLE
Andrew

### ISSUE THREAD

**Issue by Andrew-m264** [microsoft/pylance-release#3161]
On my project I typed pywhatkit it shown be error, so what can I do!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
-->

**Comment by debonte** [comment]
@Andrew-m264, there's not enough info here for us to investigate. Please open a new issue with a complete description of the problem you are seeing. See our [troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) for guidance.
