### ISSUE TITLE
Union Types not resolved correctly (VSCode)

### ISSUE THREAD

**Issue by jacksbox** [microsoft/pylance-release#3162]
I ran into following issue:

```
def create(args) -> Union[Foo, Tuple[Foo, Bar]]
  # do something and return either an instance of Foo or a tuple of instances Foo and Bar based on the args

foo = create(...) # called with args to trigger the return of a foo instance 

foo.method_call() # complains as foo could be Foo or a Tuple
```

PyCharm correctly deduces, that in this example `foo` is of type `Foo`, but in VSCode it is not.

PS: Probably it would generally make more sense for me to write two create functions, one for `Foo` and one for the `Tuple`, but imo pylance should still deduce the type "correctly" (in the obvious way?)

**Comment by erictraut** [comment]
Pyright is the static type checker upon which pylance is built. 

Your sample above is incomplete, but I think I understand what you're trying to do. Am I correct in assuming that `Foo` and `Bar` are both classes, and `Foo` has a method named `method_call`, like this?

```python
class Foo:
    def method_call(self):
        ...

class Bar:
    ...

def create(*args) -> Foo | tuple[Foo, Bar]:
    ...

foo = create()

foo.method_call()
```

In this case, Pylance is correct in pointing out that `method_call` will generate a runtime exception if `foo` is a `tuple`. To fix this bug, you would need to validate that it's an instance of `Foo` before calling `method_call`.

```python
if isinstance(foo, Foo):
    foo.method_call()
```

If `create` is a polymorphic function that returns either a `Foo` instance or a tuple based on the types of its input arguments, you can use an `@overload` to indicate the conditions under which each return type applies. 

```python
from typing import overload

class Foo:
    def method_call(self):
        ...

class Bar:
    ...

@overload
def create(v: None = None) -> Foo: ...
@overload
def create(v: str) -> tuple[Foo, Bar]: ...
def create(v: str | None = None) -> Foo | tuple[Foo, Bar]:
    ...

foo = create()

foo.method_call()
```

For more details about `@overload`, refer to [PEP 484](https://peps.python.org/pep-0484/#function-method-overloading).

**Comment by jacksbox** [comment]
@erictraut 

> Your sample above is incomplete, but I think I understand what you're trying to do. Am I correct in assuming that Foo and Bar are both classes, and Foo has a method named method_call, like this?

yes, correct. Sorry for not writing the example more descriptive (tried to represent that both are classes via the first uppercase letter, but I see that that is not obvious enough)

Thank you for your extensive answer, the `@overload` solves my issue and also makes the code better structured.
