### ISSUE TITLE
Allow intellisense to recognize files with custom extensions

### ISSUE THREAD

**Issue by wnakhleh** [microsoft/pylance-release#3163]
Currently, pylance fails to parse imported files that end with a custom prefix, this means that we can't have features such as code completion and code navigation on these imported files

# Example

## Code Snippet

main.py
```python
import somefile
```

somefile.bla:
```Python
def hello():
     pass
```

## Repro Steps

1. Build two files main.py and somefile as stated above
2. Put curser on import somefile

## Expected behavior

Being able to click on somefile and have all the intellisense features (auto completion for example), maybe by adding the ability
to specify custom extensions (other than `.py`) in the settings.json

for example:

```Python
"python.analysis.customExtensions" = ["bla, "foo"]
```

Providing such argument will allow pylance to parse files that end with `.bla` and `.foo`

## Actual behavior

Import "somefile" could not be resolvedPylance[reportMissingImports]

## Logs

```
[Info  - 13:52:10] (26748) Could not import 'somefile' in file '<full_path>/main.py'
```
I can also see that pylance is indeed checking the correct directory (the file sits next to main.py)
```
[Info  - 13:52:10] (26748)   Attempting to resolve using root path '<full_path>'
```

I'm not an expert of Pylance/Pyright, but I believe that this feature can be done by appending user specified custom suffixes to supportedFileExtensions list in pyright `importResolver.ts`

Related issues: #739, #639, microsoft/pyright#3398
 
The issues were closed but pylance still fails on files without .py, other users have also expressed that they have faced a similar issue

**Comment by erictraut** [comment]
Can you explain your use case in more detail? Why are you using non-standard file extensions?

How are you able to import a file with a custom extension at runtime? Are you writing a custom import loader that knows about non-standard file extensions?

**Comment by wnakhleh** [comment]
> Can you explain your use case in more detail? Why are you using non-standard file extensions?

Our project takes Python files as input, make some adjustments and changes to the python files and then executes them, we identify the files based on our custom extension.

> How are you able to import a file with a custom extension at runtime? Are you writing a custom import loader that knows about non-standard file extensions?

Yes, exactly that, you can write a new custom import loader using Python's built-in `importlib`

**Comment by mariiash-intel** [comment]
Hi, I see there is still a label "[waiting for user response](https://github.com/microsoft/pylance-release/labels/waiting%20for%20user%20response)" although @wnakhleh replied.
I will add a bit more info: we are develiping a python-based domain specific language, so we have to use a custom file extentions to be able to differentiate between regular python files and our domain specific language files. Our language extends python – all python capabilities are available for our language, so this enhacement is very important to us.

**Comment by erictraut** [comment]
This use case is pretty far outside the norm — definitely not a targeted use case that was considered when we were writing pyright (the type checker that underlies pylance) or pylance itself.

**Comment by judej** [comment]
Thanks for the request. We discussed this with the team and it is not a case that we are able to support. 

An option for you would be to use another language server as the base to build the customizations for the DSL.

**Comment by MH-ABE** [comment]
Using pyinstaller, one can use .spec files to configure the .exe generation. Spec files have proper python syntax, just with a different file extension. It would be quite useful to be able to have intellisense running on .spec files when editing them, and this use is more "inside the norm" than the custom files discussed earlier. 
Manually adding the file extensions you want to your config is reasonable, so as not to analyze binary files and such.
