### ISSUE TITLE
pylance 2022.7.40 is reported as malware by clamav

### ISSUE THREAD

**Issue by jasonzio** [microsoft/pylance-release#3164]
## Environment data

-   Language Server version: 2022.7.40
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9
-   clamav engine version 0.103.6
-   daily signature date 2022-07-28 sigver 26615

## Actual behavior

clamav detected malware type Tetris-9958738-0

## Logs

```json
{"updateResults":[
    {"sigType":"main","updateResult":"NO_CHANGE","sigDate":"2021-07-15T02:39:00Z","sigVer":"61","sigMD5":": 10dad18d5a254d821a841985d3043bf8"},
    {"sigType":"daily","updateResult":"NO_CHANGE","sigDate":"2022-07-28T07:58:00Z","sigVer":"26615","sigMD5":": 697672604318964bf73f2fb3e20d101b"},
    {"sigType":"bytecode","updateResult":"NO_CHANGE","sigDate":"2021-03-08T15:21:00Z","sigVer":"333","sigMD5":": d82da5df59cd2fc80f01f7895a5a88fd"}
    ],
"enginVersion":"0.103.6"
}
```

**Comment by judej** [comment]
Could you please report this to clamav as a false positive? Our code is obfuscated and looks like there our obfuscated code matches some segment of the malware.
