### ISSUE TITLE
TypedDict type inference failing since v2022.8.10

### ISSUE THREAD

**Issue by multimeric** [microsoft/pylance-release#3166]
## Environment data

-   Language Server version: v2022.8.10
-   OS and version: Ubuntu 21.10
-   Python version: 3.9.5

## Code Snippet

```python
from typing import Iterable, Union
from typing_extensions import NotRequired, TypeAlias, TypedDict

class QueryDict(TypedDict):
    and_: NotRequired[Iterable["Query"]]
    field: NotRequired[str]


Query: TypeAlias = Union[QueryDict, str]


x: Query = {"and_": ["", {"field": "foo"}]}
y: Query = {"and_": [{"field": "bar"}, {"field": "foo"}]}
```

## Expected behavior

This should not be an error. Each entry in the list is a dictionary with a valid key.

## Actual behavior

For both `x` and `y`, pylance marks this as:
```
Expression of type "dict[str, list[str | dict[str, str]]]" cannot be assigned to declared type "Query"
  Type "dict[str, list[str | dict[str, str]]]" cannot be assigned to type "Query"
    "dict[str, list[str | dict[str, str]]]" is incompatible with "QueryDict"
    "dict[str, list[str | dict[str, str]]]" is incompatible with "str"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

Notably I believe this is a regression since the previous release, where this wasn't an issue. Also this may relate to https://github.com/microsoft/pyright/issues/3796, where we had issues with a similar scenario from the type checking perspective.

**Comment by erictraut** [comment]
The changes in pylance 1.1.266 are not yet included in the latest production release of pylance (2022.8.10). If you switch to the prerelease (insiders) build of pylance, you should see that it's fixed there.

**Comment by multimeric** [comment]
Hmm, then I'm confused because it says they are: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022812-8-august-2022

**Comment by multimeric** [comment]
Oh, I see, 2022.8.12 is a prerelease version. I'll check if this is present in that version.

**Comment by erictraut** [comment]
That is the 2022.8.12 release, which is an insiders build.

**Comment by multimeric** [comment]
Apologies, you are right, this works correctly in 2022.8.20 and I was just confused about the release numbers.
