### ISSUE TITLE
Expected class type but received "SQLAlchemy"

### ISSUE THREAD

**Issue by SewerynPiorkowski** [microsoft/pylance-release#317]
Do you have any tips how to solve these errors?
![image](https://user-images.githubusercontent.com/50875213/92147608-aa7bf700-ee1b-11ea-9598-f258f3f9b966.png)
![image](https://user-images.githubusercontent.com/50875213/92147644-b5368c00-ee1b-11ea-9e44-07efadc491de.png)

**Comment by jakebailey** [comment]
If you don't want to see type checking errors, you can set your type checking mode to "off" or suppress the errors.

What is `db`? Based on the import, it looks like a variable in your codebase. Is it from Flask-SQLAlchemy? (#187)

**Comment by jakebailey** [comment]
It's been over a month since this issue was opened and we asked for feedback. I'm going to close this; if this is still an issue and you can provide the requested info, we can reopen it.
