### ISSUE TITLE
missing imports

### ISSUE THREAD

**Issue by DarkBramwel** [microsoft/pylance-release#3171]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by DarkBramwel** [comment]
Missing the imports 'PyRoxy' in lines 40 and 41 and 'impacket.ImpactPacket' in line 46

**Comment by bschnurr** [comment]
have you installed the correct package and selected your environment? https://code.visualstudio.com/docs/python/environments#_work-with-python-interpreters

**Comment by DarkBramwel** [comment]
![image](https://user-images.githubusercontent.com/103999090/184193068-18733246-e66d-4c2e-a4b0-14f555a236a5.png)

**Comment by bschnurr** [comment]
are you using File->Open Folder on your code?

**Comment by DarkBramwel** [comment]
Every time i try to install impackets it gives me an OSError

**Comment by bschnurr** [comment]
`pip install impacket` gives you an error?

**Comment by DarkBramwel** [comment]
Yes!!

**Comment by bschnurr** [comment]
whats the error. maybe you have to update pip

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
