### ISSUE TITLE
Import generation from CTRL+Space menu suddenly adds relative imports

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/pylance-release#3179]
### Environment data

-   Language Server version: 2022.8.20
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

---

Since the last update (I'm on insiders), generating an import from the CTRL+Space menu creates a relative import instead of an absolute one.

Setting `"python.analysis.importFormat": "absolute",` does not help.

This is very annoying because my project does not use relative imports and isort etc. cannot automatically fix those...

Using the Ctrl+Period menu still does the correct thing (but it shows a TON of barely related matches, but that's probably something for a separate issue)

**Comment by heejaechang** [comment]
fix should be in prerelease released yesterday.
