### ISSUE TITLE
Semantic Highlighting Question

### ISSUE THREAD

**Issue by JosephTLyons** [microsoft/pylance-release#319]
First, I wanted to say that the newest release (v2020.9.0) is fantastic.  The import feature has improved so much that I think Python dev in VS Code is quickly catching up to the IDEs that have been built specifically for Python development.  Thank you for all the tremendous work!  I'm extremely excited for the future, to see how Pylance evolves.

I did have a question related to the semantic highlighting.  I may be missing something, but I'm not sure how to get it work.  I upgraded to the newest Pylance (v2020.9.0) and the newest Python VS Code package (v2020.8.106424) and then switched my theme from the GitHub Dark theme to One Dark Pro (after installing it) and I'm not seeing any noticeable difference.  Maybe my idea of what is supposed to happen here is incorrect, but I assumed the variables would be colored different colors, however, everything seems to have the same color.

Any help is greatly appreciated.  Thanks.

**Comment by jakebailey** [comment]
![semantic_1](https://user-images.githubusercontent.com/5341706/92183633-d7bcab00-ee03-11ea-9531-4ec3d32bc8fe.gif)

This is what you should be seeing with One Dark Pro; in this gif I've gone and disabled/reenabled semantic highlighting.

I believe there might be two "One Dark Pros" out there. Which one are you using?

Here's what it looks like for Dark+ and Monokai, which are included with VS Code.

![semantic_3](https://user-images.githubusercontent.com/5341706/92183707-03d82c00-ee04-11ea-9d06-06b100630c8f.gif)

![semantic_2](https://user-images.githubusercontent.com/5341706/92183703-02a6ff00-ee04-11ea-92b1-7eb15bbee5a8.gif)

Do either of those work?

**Comment by jakebailey** [comment]
For reference, this is the One Dark Pro we are referring to: https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme

**Comment by huguesv** [comment]
Are you using the latest version of VS Code (1.48.2) ?

**Comment by JosephTLyons** [comment]
How are 

> ![semantic_1](https://user-images.githubusercontent.com/5341706/92183633-d7bcab00-ee03-11ea-9531-4ec3d32bc8fe.gif)
> 
> This is what you should be seeing with One Dark Pro; in this gif I've gone and disabled/reenabled semantic highlighting.
> 
> I believe there might be two "One Dark Pros" out there. Which one are you using?
> 
> Here's what it looks like for Dark+ and Monokai, which are included with VS Code.
> 
> ![semantic_3](https://user-images.githubusercontent.com/5341706/92183707-03d82c00-ee04-11ea-9d06-06b100630c8f.gif)
> 
> ![semantic_2](https://user-images.githubusercontent.com/5341706/92183703-02a6ff00-ee04-11ea-92b1-7eb15bbee5a8.gif)
> 
> Do either of those work?

Which setting are you using to turn on and off the semantic highlighting?  Maybe it is working for me, it is just not the thing I expected.  When I heard semantic highlighting, I sort of expected individual variable to have their own colors, like how semantic highlighting works in PyCharm:

<img width="571" alt="Screen Shot 2020-09-03 at 9 06 26 PM" src="https://user-images.githubusercontent.com/19867440/92188048-76a7ce00-ee29-11ea-94e8-8c6634f4ea5c.png">

This is what VS Code is showing with the One Dark Pro theme, VS Code 1.48.2, and the newest Pylance and Python extensions:

<img width="434" alt="Screen Shot 2020-09-03 at 9 06 48 PM" src="https://user-images.githubusercontent.com/19867440/92188076-8d4e2500-ee29-11ea-95a4-7db1a73c237a.png">

Is this correct?

**Comment by jakebailey** [comment]
Semantic highlighting means that each token is highlighted based on its semantic meaning. For example, all variables would be one way, maybe parameters are italicized, enums are colored a specific way, and so on. I'm not sure what that PyCharm behavior is, but that's definitely not semantic highlighting "per se". That's something else, assigning each individual token a different color (which VS Code doesn't do).

Your One Dark Pro looks consistent with the behavior I expect from that theme. All parameters are italicized, for example. You might find another theme that looks how you'd like it, if you're unhappy with One Dark Pro (it's just one of the earliest themes with semantic coloring, so we used it in our testing).

**Comment by JosephTLyons** [comment]
Interesting.  PyCharm's semantic highlighting feature was the first time I heard of the time I heard of term, so my entire definition of what it was was based off of that.

Maybe one day VS Code will support variables with their own colors, but that is another issue I suppose.  Going to go ahead and close this.  Thanks for the information.
