### ISSUE TITLE
Pylance doesn't detect new packages

### ISSUE THREAD

**Issue by PitchBlackNights** [microsoft/pylance-release#3191]
## Environment data

-   Language Server version: 2022.8.20
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0

## Code Snippet

```python
import discord
from discord.ext import commands
```

## Repro Steps

1. Just install a package with pip, while a python file is open *This SOMTIMES works as expected, idk what to do to get this 100% of the time*

## Expected behavior

Pylance actually works and detects new packages

## Actual behavior

It does not detect new packages, even though the program runs as intended

## Logs

[https://pastebin.com/P6uJTk4M](https://pastebin.com/P6uJTk4M)
Don't worry about the username in the paths, I redacted it

## Pictures

![Picture of Pylance Error](https://i.imgur.com/nT66OYK.png)
![Picture of installed pip packages](https://i.imgur.com/xZqEtyH.png)

Before anyone asks, Yes, I am using a virtual environment.

**Comment by bschnurr** [comment]
I dont see `discord` in your package list

**Comment by PitchBlackNights** [comment]
Oh, my mistake. Sorry!
