### ISSUE TITLE
matplotlib intellisense issues / upgrade python-type-stubs

### ISSUE THREAD

**Issue by Trass3r** [microsoft/pylance-release#3192]
<h3> Environment data </h3>

-   Language Server version: 2022.8.21
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.12 Miniconda
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

Following https://code.visualstudio.com/docs/datascience/data-science-tutorial#_prepare-the-data:

```py
import seaborn as sns
import matplotlib.pyplot as plt

fig, axs = plt.subplots(ncols=5, figsize=(30,5))
sns.violinplot(x="survived", y="age", hue="sex", data=data, ax=axs[0])
```

You get false positive error squiggles:
```py
(variable) axs: Axes
"__getitem__" method not defined on type "Axes"
```

Also reported by someone here: https://discourse.matplotlib.org/t/getitem-method-not-defined-on-axes/22651

The type stubs for this got improved 4 months ago in https://github.com/microsoft/python-type-stubs/commit/3e00ef77e0e8727d8512d34a7a489062ea3c5329.
I checked `~/.vscode-server/extensions/ms-python.vscode-pylance-2022.8.21/dist/bundled/stubs/matplotlib/pyplot.pyi` to confirm it's the old version.

_So those should definitely be updated._

### Manual upgrade test

```sh
cd ~/.vscode-server/extensions/ms-python.vscode-pylance-2022.8.21/dist/bundled/stubs/
wget https://github.com/microsoft/python-type-stubs/archive/refs/heads/main.tar.gz -O - | tar xvz --strip-components=1
```

It does pick up the new definitions but there are new problems:
```py
(variable) axs: Axes | ndarray[Unknown, Unknown]
"__getitem__" method not defined on type "Axes" [reportGeneralTypeIssues]

(variable) axs: Axes | ndarray[Unknown, Unknown]
Type of "axs" is partially unknown
  Type of "axs" is "Axes | ndarray[Unknown, Unknown]" [reportUnknownVariableType]

Type of "subplots" is partially unknown
  Type of "subplots" is "Overload[(nrows: Literal[1] = ..., ncols: Literal[1] = ..., *, sharex: bool | Literal['none', 'all', 'row', 'col'] = ..., sharey: bool | Literal['none', 'all', 'row', 'col'] = ..., squeeze: Literal[True] = ..., subplot_kw: Dict[Any, Any] | None = ..., gridspec_kw: Dict[Any, Any] | None = ..., **fig_kw: Any) -> Tuple[Figure, Axes], (nrows: int = ..., ncols: int = ..., *, sharex: bool | Literal['none', 'all', 'row', 'col'] = ..., sharey: bool | Literal['none', 'all', 'row', 'col'] = ..., squeeze: Literal[False], subplot_kw: Dict[Any, Any] | None = ..., gridspec_kw: Dict[Any, Any] | None = ..., **fig_kw: Any) -> Tuple[Figure, ndarray[Unknown, Unknown]], (nrows: int = ..., ncols: int = ..., *, sharex: bool | Literal['none', 'all', 'row', 'col'] = ..., sharey: bool | Literal['none', 'all', 'row', 'col'] = ..., squeeze: bool = ..., subplot_kw: Dict[Any, Any] | None = ..., gridspec_kw: Dict[Any, Any] | None = ..., **fig_kw: Any) -> Tuple[Figure, Axes | ndarray[Unknown, Unknown]]]" [reportUnknownMemberType]
```

Because `pyplot.pyi` now contains:
```py
def subplots(........) -> Tuple[Figure, Union[Axes, ndarray]]: ...
Expected type arguments for generic class "ndarray" [reportMissingTypeArgument]
```
```py
class ndarray(_ArrayOrScalarCommon, Generic[_ShapeType, _DType_co]):
```

So it looks like the stubs need further fixes.
But maybe also pylance/pyright to handle cases like `Axes | ndarray[Unknown, Unknown]` better?

**Comment by Trass3r** [comment]
It also seems to pick up numpy type definitions from my 3.10 system installation rather than the conda environment active in my Jupyter notebook. I hope that's not interfering here.
```
Long operation: analyzing: /usr/lib/python3/dist-packages/numpy/__init__.pyi (4745ms)
```

**Comment by bschnurr** [comment]
adding a narrowing check seems to fix the `__getitem__ ` issue

```python
from matplotlib.axes import Axes
import seaborn as sns
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
data = pd.read_csv('titanic3.csv')

fig, axs = plt.subplots(ncols=5, figsize=(30,5))
if isinstance(axs, np.ndarray):
    sns.violinplot(x="survived", y="age", hue="sex", data=data, ax=axs[0])
```

**Comment by bschnurr** [comment]
hmm. maybe the stub for Axes needs updating too so that it has `__getitem__`.. i see its base class has it 
https://github.com/matplotlib/matplotlib/blob/1efc391434812f0f24392ca4a45c5cd846f46862/lib/matplotlib/axes/_base.py#L1378

**Comment by bschnurr** [comment]
adding `__getitem__` here
`/bundled/stubs/matplotlib/axes/_base.pyi`

```python
class _AxesBase:
    def __getattr__(self, name: str) -> Any: ...  # incomplete
    def __getitem__(self, key): ... # incomplete
```

**Comment by Trass3r** [comment]
> hmm. maybe the stub for Axes needs updating too so that it has `__getitem__`.. i see its base class has it https://github.com/matplotlib/matplotlib/blob/1efc391434812f0f24392ca4a45c5cd846f46862/lib/matplotlib/axes/_base.py#L1378

That's a method of class ArtistList, not AxesBase!

I think the subplots return type is wrong. If there's only 1 subplot and squeeze is True, `Axes` is correct. In all other cases it should be `ndarray[Axes]`, not `Union[Axes, ndarray]`.

**Comment by danieltomasz** [comment]
This issue still seems to be persistent  in the Matplotlib 3.9.1

**Comment by debonte** [comment]
> This issue still seems to be persistent in the Matplotlib 3.9.1

@danieltomasz, please file a new issue describing what you're seeing. This issue is almost two years old and therefore unlikely to be related to what you're seeing today.

Note that starting with version 3.8, matplotlib is now py.typed and therefore our bundled matplotlib stubs should be ignored and have no impact on your experience. The issue you're seeing may therefore be a matplotlib issue.

**Comment by danieltomasz** [comment]
@debonte  I am really sorry, I was trying comment on matplotlib issue thread, I don't know why I  Ianded here :(
