### ISSUE TITLE
Code marked as unreachable, when it is reachable.

### ISSUE THREAD

**Issue by TheRainManV2** [microsoft/pylance-release#3196]
## Environment data

-   Language Server version: 2022.8.20 (pyright
-   OS and version: Windows 10 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.10

## Code Snippet

selenium version 4.1.3
```python
from selenium.webdriver.chrome.options import Options
ch_options = Options()
ch_options.headless = True
ch_options.add_experimental_option("excludeSwitches", ["enable-logging"])
ch_options.add_argument("no-sandbox")
ch_options.add_argument('--disable-blink-features=AutomationControlled')
ch_options.add_experimental_option('useAutomationExtension', False)
ch_options.add_argument('disable-cache')
ch_options.add_argument('--log-level=1')
ch_options.add_argument("start-maximized")

print("everything under first add_experimental_option will be marked as unreachable")
```

## Expected behavior

Code shouldn't be marked as unreachable.

## Actual behavior

Code is marked as unreachable.

## Additional information
as you can see in the screenshot below, everything under ch_options.add_experimental_option("excludeSwitches", ["enable-logging"]) will be grayed out (unreachable): 
![image](https://user-images.githubusercontent.com/90480148/184544758-a7eb79f5-8d13-49fb-88fd-0d256ef5f6ad.png)

but if I comment it out:
![image](https://user-images.githubusercontent.com/90480148/184544790-f7cd37c6-fd03-4855-b846-e0153f942398.png)

the lines below become reachable until it reaches the next call to .add_experimental_option

**Comment by erictraut** [comment]
This is a known bug in older versions of the selenium library. If you upgrade to the latest version, the problem will go away (`pip install selenium --upgrade`).

**Comment by TheRainManV2** [comment]
> This is a known bug in older versions of the selenium library. If you upgrade to the latest version, the problem will go away (`pip install selenium --upgrade`).

It did fix it, thank you.
