### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KimoNada** [microsoft/pylance-release#3198]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2022.8.20`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/karee/AppData/Local/Temp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bschnurr** [comment]
do you have public code to reproduce this?

you can try disabling indexing.
also are you using local workspace or remote?

info on how to grab logs. https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
