### ISSUE TITLE
Automatic Parentheses Beta Feature Adds Parentheses to Function Imports

### ISSUE THREAD

**Issue by JosephTLyons** [microsoft/pylance-release#320]
-   Language Server version: v2020.9.0
-   OS and version: macOS 10.15.6
-   Python version: Python 3.8.5
## Expected behaviour

I expect Pylance to not add parentheses to function imports

## Actual behaviour

With `Complete Function Parens` enabled, parentheses are added to function imports.  If I typed `from math import sqr` then chose `sqrt` from the autocomplete list, the result is `from math import sqrt()`

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020110-4-november-2020
