### ISSUE TITLE
pylance cannot recognize instance variables in the Pyqt5 module, No smart completion

### ISSUE THREAD

**Issue by Byxs20** [microsoft/pylance-release#3200]
## Environment data:
OS: windows 10
Python:3.8.8
pylance version: 2022.8.21

## Expected behaviour
This is use Jedi, It can correctly identify the variable type.
![Snipaste_2022-08-16_22-13-50](https://user-images.githubusercontent.com/64669718/184901685-b661df0c-f1ad-422d-9adb-3add91ae4796.png)

## Actual behaviour
Almost all instance variables are recognized as Any in Pylance
![Snipaste_2022-08-16_22-14-48](https://user-images.githubusercontent.com/64669718/184901904-2c5b8e5d-cee8-4fc0-a74b-d30366eb0fe6.png)

## other info
![Snipaste_2022-08-16_22-17-03](https://user-images.githubusercontent.com/64669718/184902400-f4db2a67-abcd-442f-8e55-20de7ff003d2.png)
The setupUi method inherits from Ui_ui.Ui_Mainwindow, after executing this method, it will bind tablewidget and other properties
Jedi can correctly infer the various attributes bound to the instance object after the setupUi method is executed, but Pylance cannot correctly infer it.
This is Ui_ui.Ui_Mainwindow code, It is generated by qtdesigner
![Snipaste_2022-08-16_22-18-29](https://user-images.githubusercontent.com/64669718/184902740-05d02546-0859-4743-a633-330e2cacad3d.png)

**Comment by erictraut** [comment]
Could you provide a minimal self-contained code sample that exhibits the problem? It's difficult to repro from partial screen shots. Also, could you specify which version of PyQt5 you have installed? Is it the latest published version (5.15.7)? It looks like you're also importing from a module called `Ui`. Which package does that come from, and which version do you have installed? You mentioned it was generated code. What are the steps needed to install and/or generate it?

**Comment by Byxs20** [comment]
Hello, very thank you can find the time to reply me, the code of the picture I put in my warehouse, link: https://github.com/Byxs20/FrequencyCount

## Version
PyQt5 5.15.4
Pyqt5 - plugins 5.15.4.2.2
PyQt5 - Qt5 5.15.2
PyQt5 - sip 12.11.0
Pyqt5 - tools 5.15.4.3.2

**Comment by erictraut** [comment]
This appears to be a problem with older versions of PyQt5. If you upgrade to the latest version (`pip install PyQt5 --upgrade`), the problem goes away.

**Comment by Byxs20** [comment]
Hello, thank you very much for your help. It can be solved after the updated version.
