### ISSUE TITLE
Valid "unreachable" code using deepdish

### ISSUE THREAD

**Issue by amoscao** [microsoft/pylance-release#3202]
<h3> Environment data </h3>

-   Language Server version: 2022.8.20
-   OS and version: Ubuntu 20.04
-   Python version (and distribution if applicable, e.g. Anaconda): 3.7, Poetry 1.1.14
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off
-   deepdish = "0.3.6"

<h3> Code Snippet </h3>

```
import deepdish
foo = deepdish.io.load("mypath.txt")
print("this code is now unreachable")
```
![image](https://user-images.githubusercontent.com/10836807/184980071-064d3dcb-7e5b-49d0-940e-bd3b923556f1.png)

Removing the deepdish package results results in the code being reachable, and the import correctly unresolved:
![image](https://user-images.githubusercontent.com/10836807/184981257-41fec3d6-0c9b-419f-9c35-1db9befeba4d.png)

<h3> Repro Steps </h3>

N/A

<h3> Logs </h3>

```
Starting Pylance language server.
> ~/.cache/pypoetry/virtualenvs/pyhfs-hIM3JKKH-py3.7/bin/python ~/.vscode-server/extensions/ms-python.python-2022.12.0/pythonFiles/linter.py -m flake8 --config=./etc/flake8.ini ./bugreport.py
cwd: .
##########Linting Output - flake8##########

1,1,D,D100:Missing docstring in public module
3,38,W,W292:no newline at end of file
1     D100 Missing docstring in public module
1     W292 no newline at end of file

```

**Comment by bschnurr** [comment]
add a pyrightconfig.json

"""json
{
    "defineConstant": {
        "_pytables_ok": true
      },
}
"""
