### ISSUE TITLE
Pylance has issue evaluating the function when input is a class

### ISSUE THREAD

**Issue by noppGithub** [microsoft/pylance-release#3203]
Language Server version: v2022.8.20
OS and version: Windows 10X64
Python version: Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16)

## Code Snippet

```python
from typing import Optional


class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right


class Solution:
    def evaluateTree(self, root: Optional[TreeNode]) -> bool:
        # represent the leaf node
        if root.val == 0:
            return False
        # represent the leaf node
        elif root.val == 1:
            return True

        # represent non-leaf node
        elif root.val == 2:
            return self.evaluateTree(root.left) or self.evaluateTree(root.right)
        elif root.val == 3:
            return self.evaluateTree(root.left) and self.evaluateTree(
                root.right
            )


if __name__ == "__main__":
    s = Solution()
    # test case 1
    print(
        s.evaluateTree(
            TreeNode(2, TreeNode(1), TreeNode(3, TreeNode(0), TreeNode(1)))
        )
    )
    # test case 2
    print(s.evaluateTree(TreeNode(0)))
    # test case 3, changed 213 to 203
    print(
        s.evaluateTree(
            TreeNode(2, TreeNode(0), TreeNode(3, TreeNode(0), TreeNode(1)))
        )
    )

```

## Repro Steps
- Copy the code above to VSCODE with Pylance enabled.

## Expected behavior
- the `root.val` and ` -> bool` in the method `evaluateTree` should not get error mark

## Actual behavior
- the `root.val` and ` -> bool` in the method `evaluateTree` both of them get error mark
![alt text](https://i.imgur.com/FsvtkQK.png "image Title")

## Logs
```log
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
Python interpreter path: ~\AppData\Local\Programs\Python\Python38\python.exe
Starting Pylance language server.
> conda info --json
> ~\AppData\Local\Programs\Python\Python38\python.exe ~\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\interpreterInfo.py
```

**Comment by erictraut** [comment]
Pylance is correct to flag these as errors. The code indicates that parameter `root` has the type `Optional[TreeNode]` which means that it is either `None` or an instance of `TreeNode`. If it is none, then the expression `root.val` will result in a runtime exception. Pylance is highlighting the type violation and potential bug. If the intent is that `root` never contains `None`, its type annotation should be `TreeNode`. If it is possible for `root` to be `None`, then an additional check can be added to the code to check for that condition and avoid the runtime exception.

```python
    def evaluateTree(self, root: Optional[TreeNode]) -> bool:
        if root is None:
            return False
```

The function is declared to return a value of type `bool`, but there is a code path where the function might return `None`. Pylance is pointing out this type violation and potential bug. If `root.val` contains a value other than 1, 2, or 3, the function will fall through to the bottom and implicitly return `None`. If the intent is to allow a `None` return result, then you can change the return type annotation to `Optional[bool]`.

**Comment by noppGithub** [comment]
@erictraut Thank you so much, sorry for not carefully testing before submitting an issue.
