### ISSUE TITLE
fr-string support 

### ISSUE THREAD

**Issue by petsuter** [microsoft/pylance-release#3209]
f-strings support syntax highlighting e.g. in f"{a+b}".

fr-string (raw format strings) should have the same syntax highlighting for example: fr"{a+b}\b" should look similar to the example above.

https://github.com/microsoft/vscode-python/issues/19694

**Comment by erictraut** [comment]
This fix requires upstream changes to the TextMate grammar included in VS Code.

**Comment by petsuter** [comment]
I guess this was fixed at some point in VSCode.
