### ISSUE TITLE
Quick suggestions don't work in comments and strings

### ISSUE THREAD

**Issue by ymyke** [microsoft/pylance-release#3213]
Type: <b>Bug</b>

I get the usual quick suggestions in the code, but not in comments or strings. There, I just get "No suggestions" when I trigger suggestions with ctrl+space.

I did the extension bisect process and the pylance extension was left as the culprit.

When I disable the pylance extension and restart vscode, suggestions work also in strings and comments.

(When I re-enable the pylance extension, suggestions no longer work in strings and comments.)

My user settings contain the following:

```
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
```

Any ideas what could be the problem here and what else I can check or try?

Extension version: 2022.8.30
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.33GB free)|
|Process Argv|. --crash-reporter-id 0d55e927-a53b-41b8-93d2-a1b33aa4e103|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ymyke** [comment]
Any ideas anybody?

**Comment by bschnurr** [comment]
can you provide a simple example?

**Comment by bschnurr** [comment]
I don't believe we support suggestions in comments.
but we do support suggestions in f-strings.
![image](https://user-images.githubusercontent.com/1946977/187551655-37e8241f-e6b8-4069-ab22-439a27fe4633.png)

**Comment by debonte** [comment]
If you disable Pylance and enable the `comments` and `strings` settings under `editor.quickSuggestions`, someone (VS Code? Python?) provides suggestions in comments and strings:

![image](https://user-images.githubusercontent.com/12820898/187552133-d3054477-f28f-4d14-91c5-1e23c041bf20.png)

![image](https://user-images.githubusercontent.com/12820898/187552229-aad2d09c-448e-4342-8e68-7c3e7eb4e373.png)

But with Pylance enabled, this functionality goes away.

It's not clear to me how useful these suggestions are. They seem to only include words that appear elsewhere in the current document. I guess that could be useful for completing function names, parameter names, and the like in doc strings.

**Comment by heejaechang** [comment]
we disable word based suggestion in python code with pylance. if you want that, we need to explicitly turn it on in settings.json

put this in settings.json

```
"[python]": {
                "editor.wordBasedSuggestions": true
            }
```

**Comment by ymyke** [comment]
Thanks, @heejaechang !

@debonte Re "It's not clear to me how useful these suggestions are. They seem to only include words that appear elsewhere in the current document. I guess that could be useful for completing function names, parameter names, and the like in doc strings." – Indeed I find this very useful in docstrings and comments when I'd like to mention a function name or other symbol; especially when that symbol is not on the current viewport. It would be even more useful (esp. when writing longer documentation) if symbols in general could be suggested.
