### ISSUE TITLE
Visual Studio does not recognize the correct python environment for the intellisense help (VScode works fine)

### ISSUE THREAD

**Issue by axelande** [microsoft/pylance-release#3215]
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.1
Python with Pylance   17.0.22179.3
Visual Studio IntelliCode   2.2
-   OS and version: Windows 10
-   Python version 3.7

## Code Snippet
Import anything from the venv then I got missing import warning (But works to run

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. Also, if this is related to Visual Studio and not Visual studio code, please report it at http://github.com/microsoft/ptvs. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
