### ISSUE TITLE
Referencing own class in class signature leads to error

### ISSUE THREAD

**Issue by kasium** [microsoft/pylance-release#3217]
## Environment data
-   Language Server version: 2022.8.31
-   OS and version: SLES 12 SP3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.1

## Code Snippet
```python
from __future__ import annotations

from typing import Generic, TypeVar
from typing_extensions import reveal_type


T = TypeVar("T", bound="Base")

class Base(Generic[T]):
    def get_self(self: T) -> T:
        return self

class UpperBase(Generic[T], Base[T]):
    pass

class Concrete(UpperBase[Concrete]):
    pass

self_ = Concrete().get_self()
reveal_type(self_)  # Concrete
```

## Repro Steps
1. Put the code into vscode
2. If checking with the latest version of mypy, no error occurs

## Expected behavior
No error

## Actual behavior
Error:  `"Concrete" is not definedPylance[reportUndefinedVariable]`

**Comment by erictraut** [comment]
This error is correct. If you try to run the above code in the Python interpreter, you will receive a runtime exception "NameError: name 'Concrete' is not defined".

You can work around the issue by "stringifying" the type argument.

```python
class Concrete(UpperBase["Concrete"]):
    pass
```

**Comment by kasium** [comment]
Thanks. I missed running the code first
