### ISSUE TITLE
Unable to install extension 'ms-python.vscode-pylance' as it is not compatible with VS Code '1.57.1'.

### ISSUE THREAD

**Issue by RessCris2** [microsoft/pylance-release#3221]
hello, due to company policy, I can't update the vscode version on the server, can't install extensions online neither.
so  I tried to install this extension from vsix.
but as you can see, it caught this error. 
where can I find the right version of pylance vsix to download?

**Comment by judej** [comment]
The latest version of Pylance will not work with the older version of VSCode. You will need to go back this version of Pylance: https://github.com/microsoft/pylance-release/releases/tag/2022.1.3.

Please reopen this issue if this continues to be a problem

**Comment by bschnurr** [comment]
here is a link to the 2022.1.3 build which should work with the older VSCode version `1.57.1`
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/vscode-pylance/2022.1.3/vspackage
