### ISSUE TITLE
Cannot resolve imports for mongoengine project

### ISSUE THREAD

**Issue by njgrisafi** [microsoft/pylance-release#3222]
## Environment data

-   Language Server version: v2022.8.31
-   OS and version: WSL: Ubuntu-22.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.9

## Code Snippet
Cannot resolve names within the `mongoengine` project itself.

![image](https://user-images.githubusercontent.com/7305581/185763005-e2a930c5-f8c3-429f-adb7-f309a11a0866.png)

## Repro Steps

1. Create a python project with local virtualenv
2. Install latest monoengine in virtualenv (`pip install mongoengine`)
3. Open the `connection.py` mongoengine project from virtualenv site-package
4. Confirm `Import "mongoengine.pymongo_support" could not be resolved`

## Actual behavior

I would expect the import would be resolved as the file does exist. At run time, everything imports fine.

Disabling the Pylance extension results in imports and autocomplete to work as expected.

**Comment by rchiodo** [comment]
@njgrisafi  is this still reproing for you? 

I can't repro myself. 



![Image](https://user-images.githubusercontent.com/19672699/201788296-865795a0-6eee-41e7-a849-029c7815f193.png)

If it does repro, can you add the output logs as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
