### ISSUE TITLE
custom themes lack `match` and `case` syntax highlighting

### ISSUE THREAD

**Issue by scarf005** [microsoft/pylance-release#3223]
default themes and github themes support `match` `case` syntax, however majority of other themes does not support them out of the box.

running `Inspect editor tokens and scopes` shows result like this:
![_01](https://user-images.githubusercontent.com/54838975/185725987-57b1d9c1-2b65-4636-848e-9c9057d2a59f.png "alma dimmed sakura")

![_02](https://user-images.githubusercontent.com/54838975/185725993-79ef5387-1fba-4137-89f8-df72f28edde5.png "github dark")

could there be any way to overwrite custom themes to support `match` `case`?
(using `editor.tokenColorCustomizations` for every single themes would too much work)

_Originally posted by @scarf005 in https://github.com/microsoft/pylance-release/issues/1215#issuecomment-1221215157_

**Comment by rchiodo** [comment]
I'm not sure what the ask is here? Themes can provide their own colors for `keyword`.

Here's an example:

```json
  "editor.semanticTokenColorCustomizations": {
    "[Default Light+]": {
      "rules": {
        // Make keywords green
        "keyword": "#00ff26"
      }
    }
  },
```

Which produces:



![Image](https://user-images.githubusercontent.com/19672699/202008221-059325ff-426e-4932-8a49-892c3731bd23.png)

Are you asking for a different token specific to 'match' and 'case'?

**Comment by scarf005** [comment]
then why are `match`/`case` not identified as keywords?

**Comment by rchiodo** [comment]
Do you have a specific case where that happens? I can't repro your first screen shot.

**Comment by rchiodo** [comment]
Pylance (and the tmlanguage grammar that ships with VS code) knows nothing of the theme being used. My guess is that the theme is not defining a color for the token, or is overriding it somehow.

**Comment by MicBotta** [comment]
Hi,
I had the same problem with Dracula Theme and solved by enabling the Semantic Highlighting. You have to add this entries in the settings.json file:

"editor.semanticTokenColorCustomizations": {
        "[Darcula Theme]": {
            "enabled": true
        },
    },
