### ISSUE TITLE
Go to definition goes to stub files instead of actual definitions

### ISSUE THREAD

**Issue by skarasov** [microsoft/pylance-release#3227]
Type: <b>Bug</b>

    from operator import itemgetter

On `operator` 'Go to Definition' works fine,
but not on `itemgetter`, it goes to stub (go to and peek )

Extension version: 2022.8.30
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by rchiodo** [comment]
Repros for me too. Very weird that it goes to the stub for itemgetter, but not operator.

**Comment by debonte** [comment]
@IanMatthewHuff, might be related to the issue you were seeing?

**Comment by rchiodo** [comment]
Oh it seems in main, it shows both:



![Image](https://user-images.githubusercontent.com/19672699/192067679-1285b2d2-7e9b-4472-8b79-488b19b679e9.png)


That's on VS code stable and building from source. 

Should we just skip showing the PYI version if there's a .PY one?

**Comment by rchiodo** [comment]
Nevermind, that was my bad. When building from source, I end up with a Jedi LS and Pylance. Jedi must be finding the .py definition.

**Comment by debonte** [comment]
Go-to-definition in Pylance should only show a stub file if no non-stub file locations were found. Go-to-declaration does the opposite.

**Comment by skarasov** [comment]
No, it's not complited!

    from operator import add

'Go to definition' on 'operator' - gose to operator.py = fine.
But 'go to definition' on 'add' - goes to _operator.pyi - NOT fine!

    from operator import __add__

This works fine! ??

**Comment by skarasov** [comment]
_operator.pyi and operator.pyi - Pylance confused.

**Comment by rchiodo** [comment]
When the bug is closed it means the code has been submitted to main. It does not mean it's shipped. This should work when the next prerelease is shipped.

Here's what the prerelease version should show:

![gotoadd](https://user-images.githubusercontent.com/19672699/195395649-e92208c7-7a1c-4f89-904d-cd0c4995bb1c.gif)

**Comment by rchiodo** [comment]
The commit was to pylance (private repository) so unfortunately it doesn't show in the issue. 

It's being ported to pyright at the moment. Should release today or tomorrow.

**Comment by debonte** [comment]
@rchiodo, actually we leave Pylance issues open until the fix ships. The dev handling the release will close all "fixed in next version" issues once the release is published.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2022.10.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221021-12-October-2022-PreRelease)
