### ISSUE TITLE
Parse `rtype` as the return type

### ISSUE THREAD

**Issue by asherlporetz** [microsoft/pylance-release#3247]
Parse `rtype` as the return type. Example for the python kubernetes client:

```python
    def metadata(self):
        """Gets the metadata of this V1Namespace.  # noqa: E501

        :return: The metadata of this V1Namespace.  # noqa: E501
        :rtype: V1ObjectMeta
        """
        return self._metadata
```

**Comment by bschnurr** [comment]
is this a docstring issue?

**Comment by asherlporetz** [comment]
If you type `ns.metadata.` hoping to have vscode autosuggest the fields of `metadata` it will only suggest the generic python object fields.

**Comment by erictraut** [comment]
You will need to add a return type annotation for the `metadata` method or a variable type annotation for the `metadata` instance variable.

**Comment by asherlporetz** [comment]
According to [python kubernetes](https://github.com/kubernetes-client/python/blob/master/kubernetes/client/models/v1_namespace.py) it's auto generated by OpenAPI Generator.

**Comment by bschnurr** [comment]
I suggest log an issue with them, asking for a return type annotation

**Comment by bschnurr** [comment]
you could try generating  your own type stubs for the kubernetes package locally as well.

see https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md#generating-type-stubs

`# pyright: reportMissingTypeStubs=true`
