### ISSUE TITLE
Duplicated suggestions in .py when .ipynb is open

### ISSUE THREAD

**Issue by k-papadakis** [microsoft/pylance-release#3250]

**Comment by Unknown-Chinese-User** [comment]
I come across this bug, too.
why did you close the issue?
![image](https://user-images.githubusercontent.com/56683174/200099887-249d6145-fe11-4f35-af97-cbb21bbe5e30.png)

**Comment by rchiodo** [comment]
@Unknown-Chinese-User can you include the information in the troubleshooting guide for filing an issue:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
