### ISSUE TITLE
Why `map` is class instead of function 

### ISSUE THREAD

**Issue by brxxlstxrs** [microsoft/pylance-release#3252]
I use Neovim with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) (setup for pyright) and [cmp](https://github.com/hrsh7th/nvim-cmp) (completion plugin) ([my config](https://github.com/brxxlstxrs/nvim))
And I see `map` as class instead of function in completion hints:
![IMG_20220827_120705](https://user-images.githubusercontent.com/92815065/187023805-f67a86ef-b3d0-4066-96a1-f60e08c52a97.jpg)

**Comment by qexat** [comment]
Because `map()` is a class, not a function

![image](https://user-images.githubusercontent.com/43090614/187048853-e548c835-8cc9-4552-82e8-7d033ea462a2.png)

**Comment by debonte** [comment]
@brxxlstxrs, which `map` function are you expecting to see? Is it possible that you are missing an import?

**Comment by bschnurr** [comment]
closing since map is a class
