### ISSUE TITLE
Mutually exclusive not-None values not taken in account

### ISSUE THREAD

**Issue by qexat** [microsoft/pylance-release#3253]
## Environment data

-   Language Server version: v2022.8.40
-   OS and version: EndeavourOS
- Operating System: EndeavourOS 5.19.3-arch1-1 (64-bit)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6-final-0

## Code Snippet

```python
def panic(*args: object, code: str | None = None, from_exception: type[Exception] | None = None):
    if code is None and from_exception is None:
        raise TypeError(
            f"panic() missing 1 required keyword-only argument: 'code'")

    errcode = code_from_exception(from_exception) if code is None else code
```

## Expected behavior

No error should be reported.

## Actual behavior

An error is reported at `code_from_exception(from_exception)`:
```
Argument of type "Type[Exception] | None" cannot be assigned to parameter "exception" of type "Type[Exception]" in function "code_from_exception"
  Type "Type[Exception] | None" cannot be assigned to type "Type[Exception]"
    Type "None" cannot be assigned to type "Type[Exception]"
```

It should not happen, because we checked right before that either `code` or `from_exception` can be None but not together, which means that if `code` is None, `from_exception` MUST be of type `type[Exception]`

## Logs

I added the line to my `settings.json` but nothing showed up in the output.

```

```

**Comment by erictraut** [comment]
This is expected behavior. Type narrowing is applied to individual expressions, not to combinations of expressions. In this case, neither `code` nor `from_exception` can be narrowed in the negative ("else") case because of the use of the `and` operator. 

For more details about static type analysis and type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md). 

You can make a small change to your code to eliminate the error:
```python
def panic(*args: object, code: str | None = None, from_exception: type[Exception] | None = None):
    if from_exception is None:
        if code is None:
            raise TypeError(
                f"panic() missing 1 required keyword-only argument: 'code'")
        errcode = None
    else:
        errcode = code_from_exception(from_exception)
```

**Comment by qexat** [comment]
> This is expected behavior. Type narrowing is applied to individual expressions, not to combinations of expressions. In this case, neither `code` nor `from_exception` can be narrowed in the negative ("else") case because of the use of the `and` operator.
> 
> For more details about static type analysis and type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).
> 
> You can make a small change to your code to eliminate the error:
> 
> ```python
> def panic(*args: object, code: str | None = None, from_exception: type[Exception] | None = None):
>     if from_exception is None:
>         if code is None:
>             raise TypeError(
>                 f"panic() missing 1 required keyword-only argument: 'code'")
>         errcode = None
>     else:
>         errcode = code_from_exception(from_exception)
> ```

I'm not really a fan of this refactoring but I guess I'll have to stick with that.
I should point out that the code reported as an error by Pylance works absolutely fine with mypy, though.
![image](https://user-images.githubusercontent.com/43090614/187074033-f6b2bc31-fedf-4e20-a632-cc6f9e0f8427.png)

**Comment by erictraut** [comment]
Mypy does not perform type narrowing on combinations of expressions either. Nor does any other static type checker (in any language to my knowledge). So I would be surprised if your original code above type checked in mypy.

I don't know how the `code_from_exception` function is defined, but I presume it looks something like this:

```python
from typing import Type

def code_from_exception(exception: Type[Exception]) -> int:
    ...

def panic(
    *args: object,
    code: str | None = None,
    from_exception: type[Exception] | None = None,
):
    if code is None and from_exception is None:
        raise TypeError(f"panic() missing 1 required keyword-only argument: 'code'")

    errcode = code_from_exception(from_exception) if code is None else code
```

When I run mypy on the above code, it emits the same error as pylance:
```
error: Argument 1 to "code_from_exception" has incompatible type "Optional[Type[Exception]]"; expected "Type[Exception]"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by qexat** [comment]
Yeah, you're right, my code passed mypy checks because my file has a stub equivalent and it seems that mypy privilegies this latter rather than the `.py` file

**Comment by qexat** [comment]
Anyway, I'm closing this issue as not planned I guess then
