### ISSUE TITLE
reportMissingImports: channels

### ISSUE THREAD

**Issue by SureshbabuAkash1999** [microsoft/pylance-release#3255]
missing import django channels.
![deletenow](https://user-images.githubusercontent.com/64519161/187132386-69ba253c-01cb-4341-b5f3-e2dc8025e162.jpg)

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
