### ISSUE TITLE
default typing folder no longer respected

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#326]
-   Language Server version: Pylance language server 2020.9.0 (pyright 60eb2cca) 
-   OS and version: Windows 10
-   Python version 3.8.5

## Expected behaviour

If I create a stub in the ./typings (default) folder, it Pylance should discover it.

## Actual behaviour

The type stubs I add are not found. 

However, if in the setting UI, it set the 
"Python > Analysis: Stub Path" to blank, it works

**Comment by jakebailey** [comment]
Broken by the fix to #285, the default value is somehow being treated differently even though under the hood is "if not provided, say 'typing'".

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.6, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202096-23-september-2020
