### ISSUE TITLE
Please add typing.Literal result type for key in TypedDict class

### ISSUE THREAD

**Issue by spacether** [microsoft/pylance-release#3260]
### search existing issues to avoid creating duplicates
None found

### Requested Feature
I would like vscode-python to be able to see that
- a key, required or optional exists in the TypedDict class
Here is an example:

```
import typing
import decimal
DictAnnotation = typing.TypedDict('Annotations', {'some_str': str, 'some_int': int}, total=False)


class SomeDict(dict):
    annotation = DictAnnotation

    @overload
    def get_item(self, name: typing.Literal['some_str'], in_annotation: typing.Literal[True]) -> str: ...

    @overload
    def get_item(self, name: typing.Literal['some_int'], in_annotation: typing.Literal[True]) -> int: ...

    @overload
    def get_item(self, name: str, in_annotation: typing.Literal[False]) -> decimal.Decimal: ...

    def get_item(self, name: str, property_property: bool):
        # if an attribute does not exist
        return self[name]

some_dict = SomeDict(SomeDict.annotation({'some_str': 'a', 'some_int': 1}))
my_bool = 'some_str' in SomeDict.annotation # key definition exists in TypedDict class, seen as bool but should also be typing.Literal[True]
# I want the type hint to work on some_str
some_str = some_dict.get_item('some_str', my_bool)

my_bool = 'str_of_any_type' in SomeDict.annotation
str_of_any_type = some_dict.get_item('str_of_any_type', my_bool)
# I want the type hint to work on str_of_any_type
```
This is generally applicable to classes that inherit from dict, and have properties defined with a TypedDict.
This extra in_annotation argument is needed to ensure that the type hint for some_str does not include the type hint for `get_item(self, name: str, in_annotation: typing.Literal[False]) -> decimal.Decimal: ...`
I understand that using a TypeDict for SomeDict can accomplish this, but I am not able to use TypeDict because I need SomeDict to be able to be mixed in to other classes.

**Comment by erictraut** [comment]
You're using `TypedDict` incorrectly here. Please refer to [PEP 589](https://peps.python.org/pep-0589/) for details about how `TypedDict` is intended to be used.

When pyright (the type checker upon which pylance is built) sees a `TypedDict` declaration, it synthesizes overloaded `get` methods with literals. 

```python
class SomeDict(TypedDict):
    some_str: str
    some_int: int

some_dict = SomeDict(some_str = 'a', some_int = 1)
x = some_dict.get('some_str') # Type is 'x' is 'str'
```

**Comment by spacether** [comment]
As I said, TypedDict won't work in my use case. Thank you for pointing out that vscode can correctly see types using the get method on an instance of TypedDict.
My ultimate goal here is to store a dict where some type hints are know for certain keys and for all unspecified keys, there is a different type.
That'w why I showed the decimal.Decimal type as the default type.
This may be accomplishable with the PEP 675. I will open a separate ticket on that.

**Comment by erictraut** [comment]
> My ultimate goal here is to store a dict where some type hints are know for certain keys and for all unspecified keys, there is a different type.

There has been [a recent discussion](https://github.com/python/typing/discussions/1165) in the Python typing community about extending `TypedDict` to support this notion. (TypeScript supports a similar capability.) Nothing concrete has happened yet on this front, but you are not alone in wanting this functionality.

**Comment by spacether** [comment]
No need for another ticket.
Wow, actually vscode supports this today:
```
    @typing.overload
    def __getitem__(self, name: typing.Literal["some_str"]) -> str: ...

    @typing.overload
    def __getitem__(self, name: typing.Literal["some_bool"]) -> bool: ...

    @typing.overload
    def __getitem__(self, name: str) -> int: ...

...
# results in
some_val = aa["some_str"]  # str
some_val = aa["some_bool"]  # bool
some_val = aa["hi there"]  # int
```
