### ISSUE TITLE
Pylance do not recognize editable installed package by setuptools

### ISSUE THREAD

**Issue by PaleNeutron** [microsoft/pylance-release#3262]
## Environment data

-   Language Server version: 2022.8.40 (pyright f444ffa5)
-   OS and version: macOS 12.5
-   Python version (& distribution if applicable, e.g. Anaconda): python3.10  brew

## Code Snippet

Newest editable installed python packages won't be recognize by pylance.

<img width="299" alt="image" src="https://user-images.githubusercontent.com/8296331/187617254-57bd9449-a6e6-49c2-984c-83aa7b56518c.png">

These packages do not contains a `xxx.egg-link` file in `site-packages`.

macos:
```
$ grep amdb
-rw-r--r--    1 johnlyu  admin    87B Aug 31 15:16 __editable__.amdb-0.1.dev66.pth
-rw-r--r--    1 johnlyu  admin   2.4K Aug 31 15:16 __editable___amdb_0_1_dev66_finder.py
drwxr-xr-x   10 johnlyu  admin   320B Aug 31 15:16 amdb-0.1.dev66.dist-info
```

linux:
```
ll /home/john/.local/lib/python3.10/site-packages | grep amdb
-rw-r--r--  1 john john  103 Aug 31 15:31 __editable__.amdb-0.2.dev1+g30968f1.pth
-rw-r--r--  1 john john 2.4K Aug 31 15:31 __editable___amdb_0_2_dev1_g30968f1_finder.py
drwxr-xr-x  2 john john 4.0K Aug 31 15:31 amdb-0.2.dev1+g30968f1.dist-info
```

successful import
```
Python 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import amdb
>>> 
```

show package content
```
pip uninstall amdb
Found existing installation: amdb 0.1.dev66
Uninstalling amdb-0.1.dev66:
  Would remove:
    /opt/homebrew/lib/python3.10/site-packages/__editable__.amdb-0.1.dev66.pth
    /opt/homebrew/lib/python3.10/site-packages/__editable___amdb_0_1_dev66_finder.py
    /opt/homebrew/lib/python3.10/site-packages/amdb-0.1.dev66.dist-info/*
Proceed (Y/n)?
```

## Repro Steps

1. install setuptools>=65
2. create a package only contains `pyproject.toml` and use `setuptools` as build backend
3. pip install -e .

## Logs
[pylance.log](https://github.com/microsoft/pylance-release/files/9459492/pylance.log)

**Comment by qianyizhang** [comment]
i am facing the same issue. 
packages installed with develop mode are reported missing in pylance
i have to manully link them via `python.analysis.extraPaths`

**Comment by gramster** [comment]
You could try setting the environment variable SETUPTOOLS_ENABLE_FEATURES="legacy-editable" before running pip.

**Comment by debonte** [comment]
> -rw-r--r--    1 johnlyu  admin    87B Aug 31 15:16 __editable__.amdb-0.1.dev66.pth
-rw-r--r--    1 johnlyu  admin   2.4K Aug 31 15:16 __editable___amdb_0_1_dev66_finder.py

Your editable install is using an import hook. Pylance is unable to resolve imports via import hooks. There are more details including workarounds [here](https://github.com/microsoft/pyright/blob/main/docs/import-resolution.md#editable-installs).
