### ISSUE TITLE
Pylance doesn't work properly when subclassing UI files generated with Qt designer (Pyside2).

### ISSUE THREAD

**Issue by mark-77** [microsoft/pylance-release#3267]
Good evening to everyone!

I encountered this particular problem after updating VSCode to the latest version to date (1.70.2). Originally I thought it was a problem with Pyside2 so I filed a bug report here 

https://bugreports.qt.io/browse/PYSIDE-2043

that was partially addressed. They confirmed the problem is not by their side and that it doesn't depend on the VSCode versions but just on the Pylance extension version. Particularly all the version equal or below 2022.7.40 don't exhibit the problem while all the versions equal and above 2022.8.10 show it.

The issue arises when working with a GUI file created with Qt designer (as .ui file) and then converted to .py using Pyside2-uic.exe and the details are the following:

When you create let's say a window, by subclassing "QtWidgets.QMainWindow" and the gui class you created with Qt designer, then intellisense stops working for every component that is present in the window. I attach hereby two files just to help you understand better. "main_gui.py" is a python file representing a window that has been designed in Qtdesigner and then converted to .py using Pyside2-uic.exe. It's just a stupid example with 3 radio buttons, a push button and a label. When you press the push button the label tells you which radio button is currently selected. 
"mainFile.py" on the other hand is the main code. If you load these files inside VScode with a version of Pylance = 2022.8.10 + in a virtual environment with Pyside2 and shiboken2 of course (I attach a requirement.txt for my particular virtual env), you will notice that for example the methods isChecked() or setText() or clear() that are applied to Qlabel, Qradiobuttons, Qpushbuttons etc. are not highlighted. Furthermore if you type something like self.label. no suggestions appear after the trailing dot, while in previous version of 
Pylance = 2022.7.40 or below, those very same methods were highlighted and suggestions were showing up for every gui element (buttons, labels etc etc). Pressing ctrl + space to invoke intellisense doesn't work either...

<h3> Environment data </h3>
[requirements_py39.txt](https://github.com/microsoft/pylance-release/files/9463961/requirements_py39.txt)

-   Language Server version: 2022.8.10
-   OS and version: win32 x64
-   Python version 3.9.13 (but it doesn't depend on the python version, tested with 3.6 + and the problem persists): 
-   VSCode version: 1.70.2
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet  </h3>
main_gui:

```
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_gui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(309, 218)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")

        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)

        self.radioButton_2 = QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(u"radioButton_2")

        self.gridLayout.addWidget(self.radioButton_2, 2, 0, 1, 1)

        self.radioButton = QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setChecked(True)

        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)

        self.radioButton_3 = QRadioButton(self.centralwidget)
        self.radioButton_3.setObjectName(u"radioButton_3")

        self.gridLayout.addWidget(self.radioButton_3, 3, 0, 1, 1)

        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")

        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 309, 18))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"RadioButton2", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"RadioButton1", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"RadioButton3", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Click me", None))
    # retranslateUi
```

mainFile:
```import sys

from PySide2.QtWidgets import QApplication, QDialog, QPushButton, QRadioButton, QMainWindow
from main_gui import Ui_MainWindow

class mainWindow(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(mainWindow,self).__init__()
        self.setupUi(self)
        self.pushButton.clicked.connect(self.buttonPressed)
        self.radioButtons = [self.radioButton, self.radioButton_2, self.radioButton_3]
        self.radioButton.toggled.connect(self.radiobuttonToggled)
        self.radioButton_2.toggled.connect(self.radiobuttonToggled)
        self.radioButton_3.toggled.connect(self.radiobuttonToggled)

    def buttonPressed(self):
        for i in range(3):
            if self.radioButtons[i].isChecked():
                index = i
                break
        self.label.setText(f'you have selected radio Button {index + 1}')

    def radiobuttonToggled(self):
        self.label.clear()


if __name__ == "__main__":
    app = QApplication()
    window = mainWindow()
    window.show()
    sys.exit(app.exec_())

```
<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

![expected behaviour](https://user-images.githubusercontent.com/61950137/187751875-ae3c0635-c477-49de-b03b-a29ca2e66ec1.png)

<h3> Actual behavior </h3>

![actual behaviour](https://user-images.githubusercontent.com/61950137/187752329-4fe76b2a-fc08-4358-a331-3278a17063b3.png)

**Comment by erictraut** [comment]
The problem is caused by a bug in the PySide2 type stubs that ship with the PySide2 library. I suspect (but haven't confirmed) that the bug was introduced relatively recently because I don't remember seeing this problem with earlier versions of PySide2.

The problem is found in multiple stub files including `QtWidgets.pyi`. This file includes the following statements:
```python
import shiboken2 as Shiboken
Shiboken.Object = Object
```
The same stub file then goes on to use `Shiboken.Object` as a base class for multiple files.

This won't work, as type stub files are not executed and are meant to include only type declarations. This statement is not a type declaration, it's an assignment expression. The expression `Shiboken.Object` therefore has no declared type, which means any class that derives from `Shiboken.Object` (such as `QMainWindow`) has an unknown class hierarchy. Any class that, in turn, derives from one of these classes therefore has an unknown set of attributes.

To address this, the maintainers of PySide2 will need to fix the bug in their stub files. I recommend changing `Shiboken.Object = Object` to `Shiboken_Object = Object`. In this form, it is a legal type alias declaration that can then be used as a base class for other classes.

I've confirmed that if I make those changes in the PySide2 stubs, Pylance works as expected.

**Comment by mark-77** [comment]
Thanks very much for your clear and effective reply Eric, 

I ve tried myself the modifications you suggested, and after that, Pylance works as expected

We can close the issue here.

I will forward this answer to the Pyside support team.

Have a nice day.

**Comment by adrianghc** [comment]
Hi @erictraut, I'm a developer on the Qt for Python team who is trying to solve this issue. Unfortunately, I can't confirm that your suggested fix works. Is there anything else you did besides replacing `Shiboken.Object = Object` with `Shiboken_Object = Object` in the pyi files? Did you do this in all pyi files? How have you verified that your fix works? Many thanks in advance.

**Comment by erictraut** [comment]
@addrianghc, thanks for reaching out. Yes, I verified that it worked. `Shiboken.Object = Object` is not a valid statement in a ".pyi" file, so it shouldn't appear in any stubs. To fix this, I replaced `Shiboken.Object = Object` with `Shiboken_Object = Object` and replaced all references to `Shiboken.Object` with `Shiboken_Object` in all ".pyi" files. Once I did this, the code sample provided by the OP worked as expected within pylance.

**Comment by mark-77** [comment]
Good evening!

I can confirm that replicating the exact same procedure suggested by eric traut, everything works as expected.

**Comment by adrianghc** [comment]
Hi Eric and Mark, thanks for getting back to me. I can now confirm that your suggested fix works if I apply it on the stubs from the wheels from pip, but it doesn't on the stubs generated by our latest codebase, which I was operating on. So there must be something that must be fixed in these stubs in addition to what you suggested, which I'm trying to figure out. Thank you for your help!

**Comment by shihlun1208** [comment]
Hi, I'm having the same problem as this with PyQt5 and Python 3.8.7. I posted a question on stackoverflow earlier.
[autocomplete-not-working](https://stackoverflow.com/questions/76394523/vscode-python-intellisense-does-not-autocomplete-in-pyqt-when-using-inheritance)
I've tried with Pyside6, and seems pylance works fine with PySide6. Any suggestions?
