### ISSUE TITLE
Pylance does not detect imports with projects on UNC network locations

### ISSUE THREAD

**Issue by austinwitherspoon** [microsoft/pylance-release#3269]
## Environment data

-   Language Server version: 2022.8.50
-   OS and version: Windows 10 21H2
-   Python version: 3.8

## Code Snippet

```python
import my_module # Import "my_module" could not be resolved (PylancereportMissingImports)
from . import sibling_module # Import ".my_module" could not be resolved (PylancereportMissingImports)
```

## Repro Steps

1. Setup workspace on a UNC path.
2. Create a subfolder and add it to "python.analysis.extraPaths" in vscode's settings.json
3. Create a python script in the root directory and attempt to import a script in your subfolder

Same thing happens with relative imports. Creating a python module, and relatively importing a sibling python file from inside with `from . import sibling_a`

## Expected behavior
Pylance detects relative imports from inside a module, and detects absolute imports from paths in `python.analysis.extraPaths`

## Actual behavior

On UNC network locations (like `\\network_location\code\my_project`,) pylance shows `Import XXX could not be resolved.`
The same code on a local folder works fine with pylance.

## Logs

I have attached the full log output as a .txt file, but the interesting part is this-
for context, the workspace root is: `\\isilon\Production\pipeline\dev\auswit\main\`
```
[Info  - 7:01:37 PM] (19472) No pyproject.toml file found. # this DOES exist at root of workspace
[Info  - 7:01:37 PM] (19472) Setting pythonPath for service "main": "\\isilon\Production\pipeline\dev\auswit\main\.venv\Scripts\python.exe"
[Warn  - 7:01:37 PM] (19472) stubPath \Production\pipeline\dev\auswit\main\typings is not a valid directory.
[Info  - 7:01:37 PM] (19472) Assuming Python version 3.8
[Info  - 7:01:37 PM] (19472) Assuming Python platform Windows
[Info  - 7:01:38 PM] (19472) Search paths for \Production\pipeline\dev\auswit\main
[Info  - 7:01:38 PM] (19472)   c:\Users\auswit\.vscode\extensions\ms-python.vscode-pylance-2022.8.50\dist\typeshed-fallback\stdlib
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\.venv\Lib\site-packages
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\modules
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\python2_lib
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\python3_lib
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\resolve\Modules
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\stubs
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main\servers\lambda_functions\shared
[Info  - 7:01:38 PM] (19472)   \Production\pipeline\dev\auswit\main
...
[Info  - 7:01:39 PM] (19472) Adding fs watcher for directories:
 \Production\pipeline\dev\auswit\main
[Info  - 7:01:39 PM] (19472) Searching for source files
[Error - 7:01:39 PM] (19472) File or directory "\Production\pipeline\dev\auswit\main" does not exist.
```

It appears that somewhere something in pylance is converting `\\isilon\Production` into `\Production`, which is breaking all import and configuration paths.

**Comment by rchiodo** [comment]
I believe this issue has been fixed in prerelease version 2022.11.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221121-9-November-2022-PreRelease)

We should support UNC paths now.

**Comment by klaerik** [comment]
Confirmed that this is fixed in the latest version. Thank you.

**Comment by austinwitherspoon** [comment]
This also appears to have fixed the issue for us! Thanks!

**Comment by elibroftw** [comment]
Yes, I will open a new bug, but the variables not being defined is correlated to the relative import not being recognized.
