### ISSUE TITLE
Pylance giving incorrect error messages with decorators

### ISSUE THREAD

**Issue by CircuitSacul** [microsoft/pylance-release#327]
##  Environment data
-   Language Server version: 2020.9.0
-   OS and version: MacOS Catalina 10.15.6
-   Python version: Python 3.8.3

## Expected behavior
This problem doesn't occur when I use pylint, but as soon as I switch to pylance, it gives me a `not defined` error for every keyword argument inside the decorators. I don't get these errors from python when I run the code, so it's not actually an error.

I expect it to not give me error messages

## Actual behavior

Gives me no defined errors for every single key word argument in the decorator

## Code Snippet / Additional information

```python
@any_decorator(keyword=value)
```
"keyword" is underlined in yellow and gives me `"keyword" is not defined Pylance (reportUndefinedVariable)`

![Screen Shot 2020-09-05 at 9 12 51 AM](https://user-images.githubusercontent.com/55721663/92305874-4a8b6a80-ef59-11ea-90af-467cc9f0f09f.png)

**Comment by erictraut** [comment]
This is the same regression that is reported in #322.

**Comment by jakebailey** [comment]
#322 is closed as fix; closing this one.
