### ISSUE TITLE
Pylance thinks code after reportlab method is unreachable, but the code is running

### ISSUE THREAD

**Issue by natajacks** [microsoft/pylance-release#3270]
## Environment data

-   Language Server version: 2022.8.50
-   OS and version: Windows 10 Enterprise, Version 21H
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
-   reportlab version: 3.6.5 (pip install reportlab)

## Code Snippet

from reportlab.graphics import renderPDF
...
renderPDF.draw(
    my_reportlab_graphics_object,
    my_canvas,
   70,  # x pixels from left on pdf page (reportlab Canvas)
   30  # y pixels from bottom on pdf page (reportlab Canvas)
)

code_after_renderPDFdraw_marked_unreachable_but_it_runs()

**Comment by bschnurr** [comment]
thanks for the issue.


seems there are two class 
parent `Renderer`
child `_PDFRenderer`


child's instance calls the parents `draw`, which calls `applyStateChanges` and the parent's version always throws an exception.

**Comment by bschnurr** [comment]
ah..

in renderbase.py

add `@abstractmethod` to 

```python
 @abstractmethod
    def drawNode(self, node):

 @abstractmethod
def applyStateChanges(self, delta, newState):
```

and any funciton that calls `self.undefined("drawString")`

**Comment by bschnurr** [comment]
please file an issue with the library maintainer

**Comment by natajacks** [comment]
@bschnurr  thanks! I've contacted reportlab with this info.

**Comment by natajacks** [comment]
@bschnurr I received this reply from reportlab (text copied below). 

I haven't dived into the code of reportlab itself to investigate what's going on (I don't know if there's something wrong with my instance of reportlab, as the respondent suggests, but I haven't made any changes to it from my recent original install).

In case any of this information is helpful:


-------------------------

thanks for the report, but as you note the conclusion drawn by Pylance is clearly wrong; perhaps there's something wrong
with the instance of reportlab that you are running so that Pylance concludes there's always an exception thrown.


1) reportlab.graphics.renderbase.Renderer class implements undefined methods eg drawString

2) The function reportlab.graphics.renderPDF.draw is

     def draw(drawing, canvas, x, y, showBoundary=rl_config._unset_):
         """As it says"""
         R = _PDFRenderer()
         R.draw(renderScaledDrawing(drawing), canvas, x, y, showBoundary=showBoundary)

so it is using class reportlab.graphics.renderPDF._PDFRenderer.

3) class _PDFRenderer(Renderer):
        .......
inherits from reportlab.graphics.renderbase.Renderer, but as is expected this class does override all the needed methods
including eg
        def drawString(self, stringObj):
                textRenderMode = getattr(stringObj,'textRenderMode',0)
                needFill = textRenderMode in (0,2,4,6)
                needStroke = textRenderMode in (1,2,5,6)
                .......

so as you find yourself there's no forced exception in renderbase.Renderer

It seems clear that the analysis of bschnurr is wrong. No decorator is needed on _PDFRenderer, standard python
inheritance is sufficient.

--------------------------

Thanks again for looking into this issue. For now I've just put a flag in my code that it's running, and to ignore this error.

**Comment by bschnurr** [comment]
I can't remember what kind of exception they throw, but if they throw 'UnimplementedError' in the base `applyStateChanges` instead then we should also not treat it as no return.

**Comment by bschnurr** [comment]
info here. https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#noreturn-return-type
