### ISSUE TITLE
Request: option to restrict errors and warning to the active file window

### ISSUE THREAD

**Issue by Kcwidman** [microsoft/pylance-release#3271]
I came across this "python.analysis.diagnosticMode": setting in settings.json used to control the scope of error checking through. I was hoping there would be an option like "activeFile" that would restrict errors and warnings to the active file in VsCode. However, this option does not exist. Currently, this setting only has two valid options: "openFilesOnly" and "workspace".

The use case for an "activeFile" option would be a common one I would think. I interact with many python repos that have existed through various standards at my company. In the past, we didn't include type hinting, but in current code we do. So, I definitely want type hint checks on, as they aid in code development, but when I have other files open for reference that don't adhere as strictly to type hinting rules, I find it to be a visual nuisance to see the title of the file as red in the directory sidebar, at the top of the file, red underlines throughout the files, and red ticks throughout the scroll bar. If this is a simple change, it would be much appreciated. Thanks!

**Comment by erictraut** [comment]
When you say "active file", are you referring to any front-most tabs that are currently visible? To my knowledge, VS Code doesn't have the notion of "active files", so there's no way for a language server to differentiate between active and inactive views. A language server is only told which files are open.

**Comment by bschnurr** [comment]
you could try gradual typechecking per file as well.

"On a file-by-file basis, enable all type checking options by adding the comment # pyright: strict somewhere in the file."
https://github.com/microsoft/pyright/blob/main/docs/getting-started.md#getting-started-with-type-checking

can't remember if its supports basic as well.

**Comment by Kcwidman** [comment]
Not all front most tabs, but specifically the file tab that the cursor is active in. I just left my workstation for the day, but I know that, at least in key mappings in vscode, there is a way to isolate the “active tab”. If you think it’s a potential options, I can send more specifics on this selector tomorrow morning. 

 However it very well might be that this is still unavailable from pylances perspective. I don’t have a great understanding of what’s going on behind the scenes there. Regardless, thanks for the response!

**Comment by bschnurr** [comment]
reading that link I added above there is also a folder level typechecking setting in pyrightconfig.json

closing because the language server api doesn't support the notion of active tab
