### ISSUE TITLE
Changeable font style in popup-window

### ISSUE THREAD

**Issue by Eureka-0** [microsoft/pylance-release#3278]
The popup-window for a function or module is useful, but sometimes it can be hard to read when using Pylance due to the font style and incorrect format of docstring. While I noticed it to use the same font as my editor when using jedi.

Original docstring.
<img width="627" alt="iShot_2022-09-03_10 11 22" src="https://user-images.githubusercontent.com/56858288/188251891-2a3c9df7-f26f-4418-8094-28afb7feab43.png">

Pylance, not monospaced, fontsize a little small, and the newlines are incorrect, hard to read.
<img width="673" alt="iShot_2022-09-02_10 00 52" src="https://user-images.githubusercontent.com/56858288/188251809-97980116-4e37-426c-8019-9cdd945fc24a.png">

Jedi, closest to the original dcostring, using the same font style as my editor, format is correct, easy to read.
<img width="548" alt="iShot_2022-09-02_10 01 38" src="https://user-images.githubusercontent.com/56858288/188251974-af046144-fd98-47e9-bf1e-3b59917b050b.png">

Sorry if I haven't made myself clear, I'm not a native English speaker.

**Comment by bschnurr** [comment]
to force a code block in markdown you could wrap it in ```



![Image](https://user-images.githubusercontent.com/1946977/195463637-30acbd21-7e5c-4049-b639-82038e07beec.png)
