### ISSUE TITLE
add import line quickfix should add options of popular library aliases

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/pylance-release#3285]
Adding alias of popular libraries is absolutely a bonus. 
As shown blow, it would be nice if the top 1 suggesstion is `import pandas as pd`. 

![image](https://user-images.githubusercontent.com/3153534/188411082-b59f5e68-f0e1-4896-9cd5-02f33939e8f3.png)

**Comment by judej** [comment]
Thanks for the report. Could you please make sure pandas is installed in the selected environment?

**Comment by heejaechang** [comment]
also make sure you have "python.analysis.indexing": true

**Comment by yuuuxt** [comment]
pandas installation: yes it's installed.

I added `"python.analysis.indexing": true` then more options appear, including pandas. 

Maybe this setting could be turned on by default?

![图片](https://user-images.githubusercontent.com/3153534/188765310-1b09c85e-7448-47e2-8e33-5895dbf006f4.png)

**Comment by luabud** [comment]
The indexing setting should be defaulted to true, but something unexpected is going on. We're doing a controlled rollout to enable it and doing more verifications to ensure everything is working as expected, and if everything looks good we can make this officially set to true by default when the Python extension releases next month. 
Closing in favour of https://github.com/microsoft/pylance-release/issues/3329.
