### ISSUE TITLE
Show empty module name from third party packages in auto completion.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#3293]
currently, auto complete doesnt show package/module name in auto completion if top level package doesn't have ```__init__.py``` or ```__init__.py``` is empty

ex) 
myPackage/__init__.py with empty content

completion won't show ```myPackage``` in completion. that is because there is nothing we can show when user do ```myPackage. <= dot```

but, it might still have value on showing them.

**Comment by heejaechang** [comment]
we will still only include those empty module if it is forced. 

ex) "python.analysis.packageIndexDepths":[["pyngrok", 3, true]]

"true" in the "python.analysis.packageIndexDepths" indicates pyngrok package is force indexed.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2022.9.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022911-7-September-2022-PreRelease)
