### ISSUE TITLE
How can I set pylance to use virtual python environment

### ISSUE THREAD

**Issue by jameslahm** [microsoft/pylance-release#330]
I wonder how can I set pylance to use a virtual python environment, for example, the python interpreter and libs in venv folder. I try to change the python interpreter in vscode, but it seems pylance will not change. And it leads to the problem of missing packages. Thanks!

**Comment by erictraut** [comment]
Pylance should pick up the selected Python environment from the Python extension in VS Code. It should also handle updates to the selected Python environment dynamically, so if you change the setting, Pylance should immediately switch to the new environment. You shouldn't need to do any special configuration.

**Comment by jameslahm** [comment]
Thanks, it's the third party package problem, which has no type support. Thanks again!

**Comment by hazho** [comment]
I faced the issue that pylance is not updates the selected Python environment dynamically, when I use ctrl+click on the imported module, it takes to the Python extension in VS Code :
`/.vscode-server/extensions/ms-python.vscode-pylance-2021.2.2/dist/bundled/stubs/XMODULE_PACK`
this is the path of python packages (XMODULE_PACK means any package in the pip site_packages such as django )

instead of this behavior, I want it to open the exact imported module, is this possible?

**Comment by jakebailey** [comment]
@hazho That's not related to this issue; please file a new one. We use stubs for the main information for many libraries (including django) but attempt to map the stubs back to the real code so we can navigate to them. This sounds like a case where we are not mapping and therefore only show the stub.

**Comment by treecoder** [comment]
If you use Pyenv to switch between python versions, then the general advice is to set your python path like this:

```
"python.pythonPath": "/home/myname/.pyenv/versions/3.9.5/bin/python",
```

However, if your virtual environment is not managed by [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv), or your virtualenv manager does not put the environment within the same location as pyenv-virtualenv, then the python path like above would NOT allow pylance to be able to find modules properly.

The reason for this is that pylance needs to know the location of `site-packages`. The above location of python path does not tell the correct site-packages' location.

For example, if you use Poetry and put your virtualenv locally within the project directory, then the above python path will fail in getting pylance to find the site packages. Hence you need to set the python path in the following way:

```
"python.pythonPath": "/my/project/path/.venv/bin/python",
```

With this, we are still pointing to the Pyenv managed python interpreter, but now from within the virtualenv. This will immediately make the site-package visible to pylance.

**Comment by mjohnson324-ingenovis** [comment]
What if my virtual environments are stored elsewhere? On mac they're placed at **~/Library/Caches/pypoetry/virtualenvs**. If I understand the above I need to set:

`"python.pythonPath": "~/Library/Caches/pypoetry/virtualenvs/<venv>/bin/python",`

**Comment by rfbatista** [comment]
I had the same problem but after i reload the window: (`ctrl + shift + p` then `Developer: Reload window`) the warning had stopped

**Comment by S-Yuan137** [comment]
If you use VScode, `ctrl + shift + p` then `Python: Select Interpreter` to your environment. Or find the name of the environment at the right lower corner of the VScode window, and click it to choose the environment.

**Comment by GuiTaek** [comment]
Coming from windows what helped for me:
Type in `CTRL+SHIFT+P` and then `Python: Create Environment` and then choosing the venv to create the environment from scratch.

**Comment by mjohnson324-ingenovis** [comment]
It's been a while since I posted this but I solved this problem a long time ago. I've been successful at applying different virtual envs through vscode. This has been working for me:

```json
"python.venvPath": "~path-to-directory-with-all-poetry-envs",
```

**Comment by hong539** [comment]
Or if somebody else like me
setting up pyenv and pipenv in terminal but vscode extension pylance not loading your Interpreter correctly...
You guys can try this way

```shell
#Enter your virtual environment
pipenv shell
```

And in your vscode
In VS Code, press Ctrl+Shift+P (Windows/Linux) or Command+Shift+P (Mac) to open the command palette.
In the command palette, type "Python: Select Interpreter" and select that option. This will open a list of Python interpreters to choose from.
In the list, you should see your virtual environment listed, similar to pipenv 3.8.16. Choose that virtual environment.
Here, pipenv 3.8.16. just an example.
Then reload your vscode, I think it should be work. !

**Comment by alilefta** [comment]
On **Windows**, just put the path to the _site-packages_ of _venv_:

`
"python.analysis.extraPaths": [
		"YOUR_PROJECT_PATH\\venv\\Lib\\site-packages"
	],
`

**Comment by 731315163** [comment]
> Simply adding a custom local path to pylance worked for me. In `.vscode/settings.json` (workspace):
> 
> {
>     "python.analysis.extraPaths": [
>         "venv"
>     ]
> }

Settings.json overridden by Pyrightconfig.json or Pyproject.toml
