### ISSUE TITLE
Pylance creates dozens of errors with Huggingface Transformers 

### ISSUE THREAD

**Issue by MikeyBeez** [microsoft/pylance-release#3306]
I'm using VScode's Jupyter notebook feature, and although my code runs fine, there are dozens of Pylance errors.  I'm going over the Huggingface Transformers Course on their website.  For example from transformers import AutoModelForSequenceClassification generates an error to import from transformers.models.auto.tokenization_auto instead, and this fails to run.

**Comment by bschnurr** [comment]
can you link example

**Comment by MikeyBeez** [comment]
This is the course.  If you paste these text fragments into a Jupyter notebook in VSCode, you'll get about 34 errors, but the notebook will run fine.  [https://huggingface.co/course/chapter3/2?fw=pt]

**Comment by debonte** [comment]
@MikeyBeez, with `"python.analysis.typeCheckingMode"` set to `"basic"` I'm not seeing any errors with the code sample from the ["Processing the data" section](https://huggingface.co/course/chapter3/2?fw=pt#processing-the-data) on the page you linked to above.

Can you please provide more details? Is this the code that you were referring to? Did you `pip install` both `torch` and `transformers[sentencepiece]`? What errors are you seeing?

```python
import torch
from transformers import AdamW, AutoTokenizer, AutoModelForSequenceClassification

# Same as before
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = [
    "I've been waiting for a HuggingFace course my whole life.",
    "This course is amazing!",
]
batch = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")

# This is new
batch["labels"] = torch.tensor([1, 1])

optimizer = AdamW(model.parameters())
loss = model(**batch).loss
loss.backward()
optimizer.step()
```

![image](https://user-images.githubusercontent.com/12820898/194449602-9cf15ad5-c190-41bd-9b64-67e83e9f9de3.png)

**Comment by MikeyBeez** [comment]
I’m afraid I’ve moved on.  I’m not working on this any more.
