### ISSUE TITLE
Pylance Crash in a big project

### ISSUE THREAD

**Issue by Fenggewudi** [microsoft/pylance-release#3307]
how can I increase Pylance's memory use, not only 4g . I try to use NODE_OPTIONS=--max_old_space_size=8172 , but it seems doesn't work.
```
<--- Last few GCs --->

[24648:0000205C002E4000] 4061 ms: Scavenge 40.0 (51.2) -> 37.3 (53.2) MB, 1.5 / 0.0 ms (average mu = 0.998, current mu = 0.998) task;
[24648:0000205C002E4000] 4473 ms: Scavenge 41.5 (53.2) -> 38.0 (55.2) MB, 1.6 / 0.0 ms (average mu = 0.998, current mu = 0.998) task;
[24648:0000205C002E4000] 5250 ms: Scavenge 43.6 (55.2) -> 39.2 (55.9) MB, 1.1 / 0.0 ms (average mu = 0.998, current mu = 0.998) task;

<--- JS stacktrace --->

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```

**Comment by bschnurr** [comment]
public code base?

can you add the logs? see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by Fenggewudi** [comment]
It is a privy project and I can't provide code.
it show all file is long operation and  it have about 50000+ files.
please break the memory limited

**Comment by Fenggewudi** [comment]
vscode version 1.70.2
pylance 2022.8.31
python 2022.13.12281011

**Comment by erictraut** [comment]
Please create a `pyrightconfig.json` file in your project's root directory and add the following to this file:

```json
{
    "verboseOutput": true
}
```

Then reload your project and reproduce the out-of-memory condition. The output should now include more details. Look for lines in the output logs that start with "Heap stats: ". Please provide the last few of these heap stat outputs prior to the crash.

Do you have `diagnosticMode` set to "workspace", or is it "openFilesOnly"? By default, it is the latter.

**Comment by Fenggewudi** [comment]
I set diagnosticMode to "openfilesOnly", it work out. I try to create prightconfig.json, and set  diagnosticMode to "workspace" , it like this
```
[3436:0000623A01350000]
[3436:0000623A01350000]
[3436:0000623A01350000]
62548 ms: Scavenge 3080.7 (3205.6) -> 3073.9 (3206.6) MB, 2.6 / 0.0 ms
(average mu = 0.911, current mu = 0.843) allocation failure;
62566 ms: Scavenge 3082.2 (3207.1) -> 3075.4 (3208.1) MB, 2.1 / 0.0 ms
(average mu = 0.911, current mu = 0.843) allocation failure;
62585 ms: Scavenge 3083.6 (3208.6) -> 3076.9 (3209.1) MB, 2.6 / 0.0 ms
(average mu = 0.911, current mu = 0.843) allocation failure;
•JS stacktrace
FATAL ERROR: NewSpace:: Rebalance Allocation failed - JavaScript heap out of memory
1: 00007FF6DED50126 node: :Buffer: :New+50054
2: 00007FF6DED5032F node: :OnFatalError+463
3: 00007FF6E198932A v8::Data:: IsFixedArray+1002
4: 00007FF6E1989246 V8: : Data: : IsFixedArray+774
5: 00007FF6E1A37103 v8: :CppHeap::CollectGarbageInYoungGenerationForTesting+55251
6: 00007FF6DE25399D V8: : CppHeap::GetAllocationHandle+176397
7: 00007FF6DE24F894 v8:: CppHeap::GetAllocationHandle+159748
8: 00007FF6DE23F9E3 V8:: CppHeap::GetAllocationHandle+94547
9:
00007FF6DE23D6EC v8:: CppHeap::GetAllocationHandle+85596
10: 00007FF6DE23A9E6 v8:: CppHeap::GetAllocationHandle+74070
11: 00007FF6E035F20C v8: : CppHeap::GetHeapHandle+69292
12: 00007FF6E0350E7C V8:: CppHeap::GetHeapHandle+11036
13: 00007FF6DE32876B-v8::internal::OSROptimizedCodeCache::TryGet+187675
14: 00007FF667ECC93C
```

**Comment by Fenggewudi** [comment]
I think it probably 50000+ python files analysis that 4g memory is not enough , give me a set to increase the pylance maximum memory use will be better.

**Comment by erictraut** [comment]
I'd appreciate it if you'd follow the instructions I provided above and enable verbose output in the configuration file, then post the "Heap stats" output logs. 

There is currently no way to adjust the max heap size for the node instance that hosts pylance.

Some workarounds:
1. Use "openFilesOnly" for the diagnostic mode. If you use "workspace", pylance will type check all of the files in your entire workspace.
2. If you want to type check a subset of the files in your project, use the pyrightconfig.json file to specify directories to "include" or "exclude". See [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) for details.

**Comment by Fenggewudi** [comment]
Thank you for your answer. Next Time I will only use “openFilesOnly” mode to work.
I can ‘t to provide the more details, because it's a privacy project。
