### ISSUE TITLE
pylance randomly creating large Zip file and models.json file

### ISSUE THREAD

**Issue by highpost** [microsoft/pylance-release#331]
## Environment data

-   Language Server version: v2020.9.0
-   OS and version: both Ubuntu 20.04 and macOS 10.15.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

Not generating these files.

## Actual behaviour

I believe that PyLance has been randomly generating a pair of files for a few weeks now. They show up together in different directories. I've attached samples of each to this bug report in a single Zip file container. I suspect that it's related to PyLance because the models.json file contains the following text:

[{"analyzerName":"intellisense-members-lstm-pylance","languageName":"python","identity":{"modelId":"E61945A9A512ED5E1A3EE3F1A2365B88F8FE","outputId":"E4E9EADA96734F01970E616FAB2FAC19","modifiedTimeUtc":"2020-08-11T14:06:50.811Z"},"filePath":"E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19","lastAccessTimeUtc":"2020-09-03T00:47:30.529Z"}]

The big Zip file contains the following:
-rw-rw-r-- 1 dan dan      362 Jul  8 12:03 metadata.json
-rw-rw-r-- 1 dan dan 35756058 Jun  8 17:01 model.onnx
-rw-rw-r-- 1 dan dan  5891183 Jun  8 17:01 tokens.json

And metadata.json also mentions IntelliCode.

**Comment by judej** [comment]
@highpost, thanks for the report. This is a file created by IntelliCode and it is part of the training model. This is expected.

thanks

**Comment by highpost** [comment]
Okay, but maybe it would be better to have the file created in a well-known location. It's showing up in different places...

**Comment by jakebailey** [comment]
What do you mean by "different places"? It should only be appearing in the Pylance extension folder.

**Comment by highpost** [comment]
These files have shown up in both my project directory and home directory and perhaps others.

**Comment by jakebailey** [comment]
Hm, that's definitely not supposed to happen. It's probably picking the working directory in some cases when it shouldn't be.

**Comment by highpost** [comment]
Let me add that I start VSC in different ways:

- code views.py
- code .
- GNOME favorites

So it may get different indications of what the current directory is.

If you need logs it may take me some time to catch the thing in the wild. A few hours probably.

**Comment by jakebailey** [comment]
I'm afraid there probably won't be any logs to help in this case; we have to double check the paths we're using for this process.

**Comment by jakebailey** [comment]
We think this might actually be a bug in the IntelliCode model downloader (before we ever get access to the file). In which folders does it appear? Can you provide some examples, e.g. if you open `code .` do they get placed in the workspace? If you open via GNOME, is it in `~`?

**Comment by highpost** [comment]
I'm so sorry for the delay.

It has mostly shown up in my project directories and (I seem to recall) in my home directory. I'll make a list.

--Dan

**Comment by jakebailey** [comment]
If possible, the exact files that you see created would be most helpful, as we'd need to figure out if it's the IntelliCode extension (the unextracted files) or our code (the extracted models).

**Comment by highpost** [comment]
I can repeat this in any directory by opening the file with its filename, e.g. "code yy.py".

The zip file below contains a simple Python source file I used as well as the generated models.json file. The other file is too big for GitHub, but here's a link to my Google Drive: https://drive.google.com/file/d/14NYrzua79nZhKKpYzj_DgxACuqbfLkBm/view?usp=sharing

[bug.zip](https://github.com/microsoft/pylance-release/files/5303716/bug.zip)

Please let me know if you get this.

**Comment by jakebailey** [comment]
To confirm, you see appear in your directory `model.json` and this long file name "E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19"?

**Comment by highpost** [comment]
Yes. The example I showed last night was on an Ubuntu 20.04.1 PC, but I just repeated the process on a macOS laptop with the same results:

In this case "code yy.py" generated two files:

E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19
models.json

**Comment by jakebailey** [comment]
Okay, that definitely appears to be the pre-extracted IC model files (what they give to us), so the bug has to be in IntelliCode.

**Comment by jakebailey** [comment]
Opened MicrosoftDocs/intellicode#231 as I can't transfer to their repo.

**Comment by jakebailey** [comment]
A workaround for now would be to disable the IntelliCode extension. I'm surprised that this isn't being reported more widely if you're experiencing it consistently, so that's weird.

**Comment by highpost** [comment]
If I had to guess, perhaps it's something about my environment. I don't have many extensions and they're mostly popular ones. But I do build my own executable Python from source.

**Comment by jakebailey** [comment]
Can you disable the IntelliCode extension and confirm that files don't get created?

**Comment by highpost** [comment]
I disabled IntelliCode and VS Code did not create the two files.

**Comment by jakebailey** [comment]
Thanks for confirming.

**Comment by jakebailey** [comment]
Closing in favor of discussing on MicrosoftDocs/intellicode#231.
