### ISSUE TITLE
`overload` implementation problem in signature

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#3314]
I'm not sure if it is a expected warning, but I found a "Overloaded implementation problem", using the [exact same example of the oficial documentation](https://docs.python.org/3/library/typing.html#typing.overload).

## Environment data

-   Language Server version: 2022.9.10
-   OS and version: Microsoft Windows 10.0.19044.1889
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12 (Anaconda)

## Code Snippet

[The same as the example of the oficial documentation](https://docs.python.org/3/library/typing.html#typing.overload).

```python
from typing import overload

@overload
def process(response: None) -> None:
    ...
@overload
def process(response: int) -> tuple[int, str]:
    ...
@overload
def process(response: bytes) -> str:
    ...
def process(response):
    ...
```

## Expected behavior

No warnings.

## Actual behavior

Got the following message error

```
Overloaded implementation is not consistent with signature of overload 2
  Function return type "tuple[int, str]" is incompatible with type "None"
    Type cannot be assigned to type "None"

Overloaded implementation is not consistent with signature of overload 3
  Function return type "str" is incompatible with type "None"
    Type cannot be assigned to type "None"

Overload signature is defined here
```

## Print

![image](https://user-images.githubusercontent.com/57204023/189400271-0a6cd1c1-487a-418a-9d2c-562c4dc6b441.png)

**Comment by bschnurr** [comment]
I think we are expecting `Any` for the last definition

```python
from typing import Any, overload

@overload
def process(response: None) -> None:
    ...
@overload
def process(response: int) -> tuple[int, str]:
    ...
@overload
def process(response: bytes) -> str:
    ...
def process(response: Any) -> Any:
    ...
```

**Comment by erictraut** [comment]
The error is pointing out that the signature of the implementation is inconsistent with the signature of your overloads.

You haven't provided type annotations for the implementation, so pyright (the type checker that underlies pylance) infers the return type. In your example, the inferred return type is `None` since the implementation is `...`. 

You could use `Any` as @bschnurr suggested, but it would be better to include the union possible return types.

```python
def process(response: int | bytes | None) -> str | tuple[int, str] | None:
    ...
```

If/when you supply a real implementation, the type checker will then verify that it conforms to the return type annotation.

**Comment by debonte** [comment]
@erictraut, do you think that the [Python docs](https://docs.python.org/3/library/typing.html#typing.overload) that @Diogo-Rossi pulled this code from should be updated?

**Comment by bschnurr** [comment]
I did feel bad suggesting `Any`

**Comment by debonte** [comment]
Haha. `Any` is the Voldemort of types. "The type that must not be used" :)

**Comment by Diogo-Rossi** [comment]
> If/when you supply a real implementation, the type checker will then verify that it conforms to the return type annotation.

Thanks! That really makes sense.

> You could use `Any` as @bschnurr suggested, but it would be better to include the union possible return types.
> 
> ```python
> def process(response: int | bytes | None) -> str | tuple[int, str] | None:
>     ...
> ```

I think the point of using `@overload` is to avoid that, I am right?

**Comment by Diogo-Rossi** [comment]
Actually, I think this signature
> ```python
> def process(response: int | bytes | None) -> str | tuple[int, str] | None:
>     ...
> ```

does not meet the point of `@overload`'s supports for multiple different combinations of types in arguments and returns.

I think the original overloads stands for:
"if the `response` is `None`, the return will be `None`", "if the `response` is of type `bytes`, the return will be of type `str`", etc . . .
what is not the message of this signature. That is what I understood.

**Comment by bschnurr** [comment]
Closing for now, since there was no implementation.

assuming you used `...` as the place holder for the implementation, and not actually in the code.
