### ISSUE TITLE
pylance doesn't understand classes created with built-in function type()

### ISSUE THREAD

**Issue by greyltc** [microsoft/pylance-release#3317]
## Environment data

-   Language Server version: 2022.9.11 (pyright 95c059fa)
-   OS and version: Arch Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.7

## Code Snippet

```python
response = type("OC", (object,), {"error": 4})()
response.error = 5
```
Should be the same as
```python
class OC(object):
    error = 4
response = OC()
response.error = 5
```
but pylance fails type checking the first one's error attribute while working fine on the second

## Actual behavior

pylance gets upset with my assignment to the `error` attribute:
```
Cannot assign member "error" for type "OC"
  Member "error" is unknown
```

![image](https://user-images.githubusercontent.com/16778174/189647014-66e9b94e-15d7-441a-a236-2ca1c7d9758b.png)
![image](https://user-images.githubusercontent.com/16778174/189647343-4e630db2-e4c2-40d1-b24a-1c7e9aa4b086.png)

**Comment by erictraut** [comment]
This is intended behavior. If you want your code to work with pyright (the type checker that underlies pylance), you will need to use the normal `class` syntax to declare your classes.

Out of curiosity, why do you want to use the syntax `type("OC", (object,), {"error": 4})()`? It is much more cumbersome and hard to read than the equivalent declaration that uses the syntax built into Python for declaring classes.

```python
class OC:
    error = 4
```

The only time I've seen the other approach used is for dynamic class creation, which will not work with a static type checker.

**Comment by greyltc** [comment]
```python
response = type("OC", (object,), {"error": 4})()
```
and
```python
class OC(object):
    error = 4
response = OC()
```
are both valid ways to define and instantiate a class. I don't really see a fundamental reason why a static type checker should work with one and not the other. Can I re-file this as a feature request instead of a bug report?

The first is for sure harder to read and I don't actually do this. I just wrote it here like that as a minimal example of the failure for the report.

**Comment by erictraut** [comment]
A static type checker like pyright (the static type checker that underlies pylance) is a tool that allows you to write more robust, maintainable, and bug-free Python code. There will always be ways in Python to subvert or work around a static analysis tool if you try hard enough.

The only place I have ever seen `type("OC", (object,), {"error": 4})()` used is in cases where one or more of the arguments is dynamic — i.e. not possible to determine through static analysis. In such cases, a static analysis tool won't be able to understand the intent anyway. 

You can file a feature request if you'd like, but adding support for this would be a significant amount of work, so we would need a strong signal from pyright users that it's a common pattern before we would commit to adding such support. As I said, I haven't ever seen this used except in cases dynamic use cases where a static analysis tool won't work anyway. And even those cases have been exceedingly rare.

If you're interested in writing robust and maintainable Python code and are interested in using static type analysis to help you achieve that goal, I encourage you to use the standard `class` syntax provided by the language to declare your classes.

**Comment by greyltc** [comment]
I must just be naïvely missing why the dynamicness associated with making classes using `type()` is much different than any other dynamicness that the checker already supports. Today the checker handles this as I'd expect it to:
```
import random

r = random.random()

if r < 0.5:
    x = "X"
else:
    x = 1

y = x.lower() # <-- warning because the checker knows x might be an int which doesn't have .lower() even though the actual class of x is determined at runtime
```
so why should the following dynamic class creation with `type()` be anything very new compared to what's already working above?
```
import random

r = random.random()

if r < 0.5:
    base = str
    attrib = (21, 2.1)
else:
    base = int
    attrib = ["gold", "silver"]

OC = type("OC", (base,), {"error": attrib})
```

**Comment by debonte** [comment]
Thanks for your feedback. As Eric mentioned above, we would only add this support if we got a strong indication from our user community that this was needed. So, if lots of people up-vote this issue or [the related Pyright discussion topic](https://github.com/microsoft/pyright/discussions/3438), we would consider it. But our current belief is that this is a niche feature that is not a priority for us.
