### ISSUE TITLE
Pylance is not aware of imported child modules when parent is aliased

### ISSUE THREAD

**Issue by benfiola** [microsoft/pylance-release#3320]
Apologies if this is a issue that's been filed before - I've found _similar_ issues but those issues usually either facilitate import side-effects or dynamic import behavior - things that naturally trip up static type checking.  If one exists that's relevant to this issue, please point me in the right direction!

In my case, I'm importing parent and child packages, but am giving the parent an alias.  Pylance recognizes the alias, but fails to recognize the (imported) children modules - returning `<child> is not a known member of module`.

<h3> Environment data </h3>

-   Language Server version: 2022.9.10
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): python 3.9.13
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

Assume the following folder structure:

```text
a_pkg/
    __init__.py
    a_mod.py
    b_mod.py
main.py
```

and the following file contents:

```python
# a_pkg/__init__.py
```

```python
# a_pkg/a_mod.py

def a_func() -> bool:
    return True
```

```python
# a_pkg/b_mod.py

def b_func() -> str:
    return "string"
```

```python
# main.py

import a_pkg as pkg
import a_pkg.a_mod
import a_pkg.b_mod

def main():
    pkg.a_mod.a_func()
    pkg.b_mod.b_func()
```

<h3> Expected behavior </h3>

No type warnings.

<h3> Actual behavior </h3>

```
"a_mod" is not a known member of module
"b_mod" is not a known member of module
```

<h3> Workaround </h3>

At the moment, I can work around this by doing:

```
# main.py

import a_pkg
import a_pkg.a_mod
import a_pkg.b_mod
pkg = a_pkg


def main():
    pkg.a_mod.a_func()
    pkg.b_mod.b_func()
```

While this works, the workaround can potentially raise linting errors depending on where the variable assignment occurs (some linters, like the default inspection settings in Pycharm, want imports to happen before non-import code).  Consequently, moving this assignment after a block of imports would yield less readable code as the import aliasing happens in a different section of the file.

Aliasing imports in this fashion is a strategy to shorten otherwise lengthy import path prefixes - particularly in large projects with deeper folder structures (for example, what if `a_pkg` was instead `pkg_1.pkg_2.pkg_3.pkg_4`, etc.).

Is this behavior intended in the type checker?  If so, is there a more elegant workaround for the problem?

**Comment by erictraut** [comment]
This pattern is intentionally not supported. Pyright, the static type checker that underlies pylance, does not model side effects of the import loader. For additional details, refer to [this discussion](https://github.com/microsoft/pylance-release/issues/3263).

What you are effectively doing here is creating two local variables: `pkg` and `a_pkg`. You are using different import statements to populate each of these local variables, and you're relying on incidental side effects performed by the Python import loader — namely, that it is caching an imported submodule as a global variable within its parent module's namespace. Such assumptions are fragile and in the general case cannot be modeled by a static type checker. There are certain forms of this side effect that could be modeled by a static type checker, but we've established a principle that we will not model any such side effects. We may reconsider this stance in the future and make an exception in specific cases if there is sufficient signal from users and the usage is provably safe, but for now we have no plans to change this.

The workaround that you've suggested does not rely on implicit loader side effects, so it is a better solution from my perspective.

I'm curious why you are using an alias for the top-level package name. Is it for brevity, to avoid a local namespace conflict, or some other reason?

**Comment by benfiola** [comment]
Brevity: one of our projects is a namespace package with a deep-folder structure and sub-packages with empty `__init__.py` files.  As a result, the full path to an imported member can be long (and repetitive) - these aliases produce terser code.  

Regardless, I appreciate the explanation and agree with the justification!
