### ISSUE TITLE
Pylance intelligence can only take effect after qucik fix is used

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3324]
Here is an example:

![image](https://user-images.githubusercontent.com/100815370/189815077-013b2afa-49a5-4175-948d-893e0f753fc6.png)

When I click quick fix, delete the content and re-enter it, I can get a prompt, otherwise it doesn't exist.

![image](https://user-images.githubusercontent.com/100815370/189814341-5f9410f7-4a3b-494d-b96a-0addb62f074a.png)

Is there any way I can get a prompt directly?

I tried to add the following in settings.json:

```
    "python.autoComplete.extraPaths": [
        "C:\\newPython\\helloFloder\\helloFloder2\\hello.py"
    ],
    "python.analysis.extraPaths": [
        "C:\\newPython\\helloFloder\\helloFloder2\\hello.py"
    ]
```

I also add the __init__.py in the folder. But they didn't work.

**Comment by luabud** [comment]
Hey @ydmykr, would you mind trying setting `"python.analysis.indexing":true` in your settings.json file? (View > Command Palette... and run "Open User Settings (JSON)").  What you're reporting seems to be the behaviour of when this setting is set to "false", and it looks like there's a bug where we're not setting it to "true" by default.

**Comment by heejaechang** [comment]
this is currently by design. currently, we do not add user types in auto import unless it is already used. code action on the other hand, adds all user types. this was a decision to make sure we do not add hundreds of user types in completion list.
