### ISSUE TITLE
Cell magics not properly handled in VS.Code Jupyter

### ISSUE THREAD

**Issue by timoklimmer** [microsoft/pylance-release#3327]
## Environment data

-   Language Server version: v2022.9.10
-   OS and version: Windows 11, Ubuntu 20.04
-   Python version: Python 3.10.5, conda 4.14.0

## Repro Steps

1. Create a Jupyter notebook in VS.Code
2. Start a cell with a cells magic, for example %%cmd.
3. Add some arbitrary code to the next lines.

## Expected behavior

Whenever a cell's content starts with a cells magic (%%...), the code in the cell is not validated as Python code, and no wrong and disturbing squiggles are shown.

Ignoring all cell content when the cell starts with a `%%` seems like a good first step.

## Actual behavior

Wrong and disturbing squiggles, making a convenient use of cell magics in VS.Code Jupyter impossible.

![image](https://user-images.githubusercontent.com/25802428/189965746-159cabca-ff83-4de2-a6b7-89edbf58fe81.png)

@debonte fyi
See also #2582

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2022.9.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022931-21-September-2022-PreRelease)
