### ISSUE TITLE
How to specify python interpreter for type checking?

### ISSUE THREAD

**Issue by timeinsaber** [microsoft/pylance-release#3334]
**What I See**
In VSCode, I will see a variable be typed by pylance like this:
![image](https://user-images.githubusercontent.com/59987408/190097191-62f5f773-d4cd-4b90-bbde-fa43a0a256d7.png)
I Guess this is done by python ast parser.

Then I change Python Interpreter to Python2.7:
![image](https://user-images.githubusercontent.com/59987408/190097390-26749224-eef1-4889-a8aa-1adb848601d6.png)

type annotation can still work.
![image](https://user-images.githubusercontent.com/59987408/190097702-1f9d801f-f580-4cc9-a8a0-6daca4ea3e33.png)

**Why I ask this question And what I want**
I am trying to compile py3.11 by myself(with python parser modified), which I want to use for pylance. But when I changed python interpreter to my compiled python, it seems not working.

So I wonder how to change the python interpreter that pylance is using for type checking. Thank You:)

**Comment by judej** [comment]
Pylance does not run the Python kernel to get information about types. So, changing the kernel will not result in different info. The type information is derived from the static analysis.

**Comment by timeinsaber** [comment]
> Pylance does not run the Python kernel to get information about types. So, changing the kernel will not result in different info. The type information is derived from our own parser, not the Python parser.

Well I got it. Thanks for answer:)
