### ISSUE TITLE
Autocompletion and error checking very slow

### ISSUE THREAD

**Issue by warui-slime** [microsoft/pylance-release#3344]
Type: <b>Performance Issue</b>

The autocompletion is extremely slow and sometimes don't even work. The error checking is also very slow, sometimes i even have to save the file for error checking.
I have been using vs code for a year and this had never happened in the past, please help me.

Extension version: 2022.9.20
VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.19GB free)|
|Process Argv|--crash-reporter-id e32075ee-99ca-481f-a879-7387c74a8212|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    98	 18416	code main
    0	    40	  2252	   utility-network-service
    0	    91	  4132	   issue-reporter
    0	    26	  7756	   crashpad-handler
    0	   180	  8320	   window (bot.py - Discord_Bot - Visual Studio Code)
    0	   117	 12724	   extensionHost
    0	    69	  4276	     "C:\Users\rohan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\rohan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=12724
    0	   368	 15384	     "C:\Users\rohan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\rohan\.vscode\extensions\ms-python.vscode-pylance-2022.9.10\dist\server.bundle.js --cancellationReceive=file:0e9dab6971f0eea06e0eaeeda90d7b30417aee4fa3 --node-ipc --clientProcessId=12724
    0	   100	 14356	   shared-process
    0	    72	 23704	     fileWatcher
    0	    69	 23848	     ptyHost
    0	   135	 24292	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (bot.py - Discord_Bot - Visual Studio Code)
|    Folder (Discord_Bot): 6 files
|      File types: py(3) env(1) pyc(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
fc301958:30567733

```

</details>

**Comment by bschnurr** [comment]
Can you add the "Python Language Server" logs. see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by rchiodo** [comment]
Closing issue with no response. If you can respond with the asked for information, please reopen this issue.

Thanks.
