### ISSUE TITLE
Type hint inlays inaccurate for big integer literals

### ISSUE THREAD

**Issue by diceroll123** [microsoft/pylance-release#3355]
<h3> Environment data </h3>

-   Language Server version: 2022.9.11
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
x = 123670029844611072
y = 228576013746044928
z = 603377803525750794
```

<h3> Expected behavior </h3>

Type inlays have the exact value as the integers

<h3> Actual behavior </h3>

Type inlays _sometimes_ have the exact value as the integers

---

It also occurs when mousing-over the variable. I figure it's some Javascript limitation with rounding. Here's a quick visual.

![image](https://user-images.githubusercontent.com/1243957/190839204-60e5664f-ce1a-4a33-9c97-c2f363fd1306.png)

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2022.9.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022931-21-September-2022-PreRelease)
