### ISSUE TITLE
pyattck could not be resolved

### ISSUE THREAD

**Issue by StoopidGit** [microsoft/pylance-release#3360]
Language Server version: python 3.9.6
OS and version: Windows 10
Python version (& distribution if applicable, e.g. Anaconda): 3.9.6
Code Snippet
```
from pyattck import Attck
attack = Attck()
```
Repro Steps
![Capture](https://user-images.githubusercontent.com/108001432/191026818-47c95757-ba72-4ef8-a2e9-d69f57706c02.JPG)

**Comment by bschnurr** [comment]
have you selected the correct python environment, with pyattact installed?
https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

**Comment by rchiodo** [comment]
Closing issue with no response. If you can respond with the asked for information, please reopen this issue.

Thanks.
