### ISSUE TITLE
TypeVar('T', None, str) doesn't work correctly

### ISSUE THREAD

**Issue by conao3** [microsoft/pylance-release#3364]
## Disclaimer

I'm new at Python toolchain, so anyone please tell me if there is good place to report this.

## Environment data

-   Language Server version (pylance): v2022.9.20
-   OS and version: OSX 12.6 Montery
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

![image](https://user-images.githubusercontent.com/4703128/191160402-b6ad531f-e4b0-4433-a3be-0cd763ffd4e7.png)

```python
from typing import TypeVar


T = TypeVar('T', None, str)


def fn1(s: T) -> T:
    if s is None:
        return s
    return s


def fn2(s: T) -> T:
    if s is None:
        return
    return s
```

## Repro Steps

1. Install `python` extension at VSCode
2. Setup python 3.10 environment
3. Paste above snippet
4. Reproduce the screenshot

## Expected behavior

Don't Error at `fn2`.

## Actual behavior

Error at `fn2`.

```
Expression of type "None" cannot be assigned to return type "T@fn2"
  Type "None" cannot be assigned to type "T@fn2"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

## Logs

None

**Comment by bschnurr** [comment]
adding 'return None' also has the same error, basically saving that None is not the same type as T
```
from typing import TypeVar


T = TypeVar('T', None, str)


def fn1(s: T) -> T:
    if s is None:
        return s
    return s


def fn2(s: T) -> T :
    if s is None:
        return None
    return s

```

**Comment by debonte** [comment]
https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards:

> In addition to assignment-based type narrowing, Pyright supports the following type guards.
> * `x is None` and `x is not None`

**Comment by heejaechang** [comment]
it is a dup of this - https://github.com/microsoft/pyright/issues/2010

**Comment by conao3** [comment]
So... this behavior is intended?

**Comment by debonte** [comment]
> So... this behavior is intended?

Not really "intended", but it's a known limitation of the way that constrained TypeVars are handled in Pyright, the type checker that Pylance is based on. There's a good explanation in [this comment](https://github.com/microsoft/pyright/issues/2010#issuecomment-864339917).
