### ISSUE TITLE
pandas: Argument missing for parameter "by"

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#337]
## Environment data

-   Language Server version: Pylance language server 2020.9.0 (pyright 60eb2cca)
-   OS and version: macOS
-   Python version (& distribution if applicable, e.g. Anaconda): pandas==1.1.1

## Expected behaviour

No type error, as this is correct behaviour according to the [pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html) 

## Actual behaviour

Argument missing for parameter "by" [10,1]

## Code Snippet / Additional information

```python
import pandas as pd

arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
          ['Captive', 'Wild', 'Captive', 'Wild']]
index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]},
                  index=index)
df

df.groupby(level=0).mean()

```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.5, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202095-16-september-2020
