### ISSUE TITLE
False positive unreachable

### ISSUE THREAD

**Issue by janosh** [microsoft/pylance-release#3373]
## Environment data

-   Language Server version: Pylance language server 2022.9.20 (pyright 95c059fa)
-   OS and version: macOS 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

```py
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

np.cross(X, Y)
print(X)  # pylance says unreachable
```

## Expected behavior

Code should be marked reachable.

## Actual behavior

![Screen Shot 2022-09-20 at 17 16 56](https://user-images.githubusercontent.com/30958850/191386934-d6e1ba6c-1360-4e1a-8a5d-489bcdd7d663.png)

**Comment by erictraut** [comment]
This is a duplicate of https://github.com/microsoft/pylance-release/issues/3277.

**Comment by janosh** [comment]
Ah, good to know someone already raised an issue with https://github.com/numpy/numpy/issues/22146.
