### ISSUE TITLE
Find All References does not work on latest version v2022.9.30 and v2022.9.20

### ISSUE THREAD

**Issue by angel-langdon** [microsoft/pylance-release#3378]
## Environment data

-   Language Server version: v2022.9.30 and v2022.9.20
-   OS and version: Mac OS Version 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6

**Comment by angel-langdon** [comment]
Solved the problem downgrading `PyLance` to `v2022.9.10`

<img width="797" alt="image" src="https://user-images.githubusercontent.com/53478143/191699169-b9df6c23-e525-40ea-93ad-2a6e1ffba22f.png">

**Comment by n4choo** [comment]
I'm currently experimenting the same issue in both versions. I also have MacOS Version 12.6 and Python 3.10.6

**Comment by debonte** [comment]
Do you have a `pyproject.toml` file? If so, can you try switching to prerelease and see if 2022.9.31 fixes this issue?

**Comment by debonte** [comment]
Duplicate of https://github.com/microsoft/pylance-release/issues/3348
