### ISSUE TITLE
Type checker does not completely recognise Dict type constructor in typing library

### ISSUE THREAD

**Issue by SaadiSave** [microsoft/pylance-release#338]
## Environment data

-   Language Server version: 2020.9.0
-   OS and version: Ubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2

## Expected behaviour
When hovering over pdict
```python3
def __init__(self, syst: str, pdict: Dict[str, float]) -> None:
```
pylance should display
```
(parameter) pdict: Dict[str, float]
```
## Actual behaviour

Instead, it displays
```
(parameter) pdict: Dict
```
![Screenshot from 2020-09-08 12-14-17](https://user-images.githubusercontent.com/53120037/92442991-719ea200-f1ce-11ea-97a4-e49e3e81875f.png)

## Logs

```
None
```

## Code Snippet / Additional information

```python3
class aqi:
    def __init__(self, syst: str, pdict: Dict[str, float]) -> None:
    ...
```

**Comment by erictraut** [comment]
Thanks for the bug report.

This issue has already been addressed, and the fix will appear in the next release of Pylance.

![Screen Shot 2020-09-08 at 12 32 29 AM](https://user-images.githubusercontent.com/7040122/92446566-db856000-f16a-11ea-95a3-157979d47e36.png)

**Comment by erictraut** [comment]
It is a duplicate of #315

**Comment by SaadiSave** [comment]
Okay. Thank you.
