### ISSUE TITLE
Python Import suggestion doesn't even work

### ISSUE THREAD

**Issue by shanewazabbas** [microsoft/pylance-release#3384]
Please fix this. I have no idea, what settings to turn on for it to even make it work now. It used to normally work just fine before. 

I create a dataclass and save it one file. I type the name of the dataclass in another file and I get this:

![image](https://user-images.githubusercontent.com/86968952/192024828-a0e58184-a3a5-4d4b-a136-066d3ce43a29.png)

I just want to understand what exactly is being done to figure out import suggestions. I want to know if I can see some logs or something to understand why it doesn't pick up newly added classes.

I also thought this setting would work but it doesn't do what I would think it does. I have no clue what its for.
`"python.analysis.indexing": true,`

**Comment by debonte** [comment]
Do you have a `pyproject.toml` file? If so, can you try switching to prerelease and see if 2022.9.31 fixes this issue?

**Comment by shanewazabbas** [comment]
Yeah, I have pyproject.toml. Is prerelease referring to the python extension version

**Comment by shanewazabbas** [comment]
yeah I switch pylance to prelease and it appears to be working again

**Comment by debonte** [comment]
Nope, the Pre-Release version of Pylance. Here's how to do that:

1. Open the Extensions pane
2. Find and click on Pylance
![image](https://user-images.githubusercontent.com/12820898/192027186-b67eacde-77dd-4527-9793-ba7816409b4b.png)
3. Click the "Switch to Pre-Release Version" button
![image](https://user-images.githubusercontent.com/12820898/192027336-cd2f439b-6a38-4786-93a2-2d77baff2df0.png)
4. Wait for the Pre-Release build to install. You may be notified that you need to reload VS Code. If you see the "Reload Required" button, make sure your work is saved, and then press that button.
![image](https://user-images.githubusercontent.com/12820898/192028040-003da719-1a1e-4b4d-a43b-bb04d4839bd9.png)

When things are running smoothly, when we ship each Wednesday we ship two builds:
- New Pre-Release build which is our latest changes and therefore may be unstable.
- New Release build which matches last week's Pre-Release build assuming we didn't find any big problems with it.

So you can choose to either be on the bleeding edge (Pre-Release) or safer more stable build (Release).

When you're using Pre-Release, the "Switch to Pre-Release Version" button is replaced by a "Switch to Release Version" button that will put you back on the more stable Release build if that's what you want:
![image](https://user-images.githubusercontent.com/12820898/192027813-164bc1a9-ace6-43b8-9d31-bc7cea782bd6.png)

**Comment by shanewazabbas** [comment]
Looks like prerelease has a fix for this:
https://github.com/microsoft/pylance-release/issues/3348

**Comment by debonte** [comment]
Duplicate of #3348
