### ISSUE TITLE
Missing Imports

### ISSUE THREAD

**Issue by amanin1** [microsoft/pylance-release#3389]
path: usr/lib/python3
name of file: __init.py__

1.      import _frozen_importlib as _bootstrap

2.     import _frozen_importlib_external as _bootstrap_external

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
