### ISSUE TITLE
Syntax Highlighting changed by Pylance

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#339]
## Environment data

- Python Extension `v2020.9.106814-dev`
-   Language Server version: `v2020.9.0`
-   OS and version: `Win 10.0.19041.423`
-   Python version `2.7.18 64`

## Expected behaviour

Syntax highlighting is left to the theme and unaffected by the language server plugin.

## Actual behaviour

After the python extension finishes loading the colors change from this 👍
![one_dark_shl](https://user-images.githubusercontent.com/218956/92475690-1aa0c900-f1de-11ea-9372-88a40c4bc1f4.png)
to this ☹
![pylance_shl](https://user-images.githubusercontent.com/218956/92475705-2096aa00-f1de-11ea-9143-8b725fbb6c72.png)

There is nothing in the logs or anywhere to find. Since I'm on the Insider build and on the Pylance preview I suppose thats something new? Since I have never seen it before?
Is there a setting for this?

**Comment by ewerybody** [comment]
I'm using the [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) theme but the default one is also affected!

**Comment by bschnurr** [comment]
This is related to new support for semantic highlighting

```
{
    "[python]": {
        "editor.semanticHighlighting.enabled": false
    }
}
```

see https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting
for more info

or issue #323

**Comment by ewerybody** [comment]
Ooh Dang! Thanks! I saw this one and immediately though: No that's not my issue 🙈

**Comment by judej** [comment]
@ewerybody, please respond back to this is the disabling does not work

**Comment by ewerybody** [comment]
what?

ehm. The disabling works. I'm sorry. The "_Thanks_" was supposed to state that.

**Comment by ddejohn** [comment]
This issue has come back for me, even after adding

```
{
    "[python]": {
        "editor.semanticHighlighting.enabled": false
    }
}
```

To my settings.

**Comment by jakebailey** [comment]
Pylance just serves the data to VS Code; that setting is VS Code's toggle. They might have a bug or something. Maybe it's to do with trying to set it in the `[python]` block?
