### ISSUE TITLE
`Use List[T] to indicate ...` error message does not provide the correct fix

### ISSUE THREAD

**Issue by jparisu** [microsoft/pylance-release#3392]
## Environment data

-   Language Server version: v2022.9.30 
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.10

## Code Snippet

```python
# List expression not allowed in type annotation
# Use List[T] to indicate a list type or Union[T1, T2] to indicate a union type  (Pylance)
def function_with_str_list_param_1(
        command: [str]):  # Error
    pass

# "List" is not definedPylancereportUndefinedVariable  (Pylance)
def function_with_str_list_param_2(
        command: List[str]):  # Error
    pass

# Subscript for class "list" will generate runtime exception; enclose type annotation in quotes  (Pylance)
def function_with_str_list_param_3(
        command: list[str]):  # Error
    pass

# Correct
def function_with_str_list_param_correct(
        command: 'list[str]'):  # OK
    pass
```

## Expected behavior

The error shown helps you to correct the issue

## Actual behavior

The help snippet given is not correct.

**Comment by erictraut** [comment]
What do you think is wrong or misleading about the error message? A list expression like `[str]` is not a legal type annotation. If your intent is to declare the parameter as a list, you should use `List[str]` in this case. You need to import `List` from the `typing` module.

**Comment by jparisu** [comment]
> You need to import `List` from the `typing` module.

This is what I missed. I just tried to use `List[str]` and it shows a different error. And I wrongly supposed `'list[error]'` is what you meant with List[T].
My fault
(however, I may suggest to mention somehow that this import is needed in error message).

**Comment by jparisu** [comment]
Thank you for the quick response BTW.

**Comment by thestampr** [comment]
You need to import `annotation` from `__future__` to use `list[str]`

**Comment by debonte** [comment]
> You need to import `annotation` from `__future__` to use `list[str]`

Or use Python 3.9+. https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
