### ISSUE TITLE
Ensure `str` is a `Literal`

### ISSUE THREAD

**Issue by CaedenPH** [microsoft/pylance-release#3394]
## Environment data

-   Language Server version: `2022.9.30`
-   OS and version: `Windows 11 Pro 10.0.22000` 
-   Python version (& distribution if applicable, e.g. Anaconda): `3.10.7`

## Code Snippet

```py
from typing import Literal, get_args


modes = Literal["r", "rb", "r+", "rb+", "w", "wb", "w+", "wb+", "a", "ab", "a+", "ab+", "x", "xb", "x+", "xb+"]

def main(c: str):
    if c not in get_args(modes):
        raise ValueError("Invalid mode")


    type(c)

with open("test.txt", "w") as f:
    f.write("r")

main(open("test.txt").read())
```

## Repro Steps

1. View type of `c`

## Expected behavior

The type of `c` should be `modes`

## Actual behavior

`c` remains str
![image](https://user-images.githubusercontent.com/23421705/192363825-e3c83724-61f7-4a1f-8916-9883c5f1ba78.png)

## Info 

My thought process, correct me if I'm wrong;
     `a: Literal["a", "b", "c"]` means that `a` must be of type `a`, `b`, or `c`.
     Therefore, when ensuring the `c` is in `"r", "rb", etc`, `c` is now a literal of `"r", "rb", etc`
For example;
![image](https://user-images.githubusercontent.com/23421705/192364664-ccb8d10b-9362-4935-af8e-f1ae36f39f18.png)

When asserting that `a == "a"`, `a` is transformed *into* `Literal["a"]`, so why does the same not apply to `c`, when checking for `get_args`.

My conclusion is that `get_args` does not correctly typehint it's return type, as shown below. I believe that there should be some indication that the return type is in direct correlation to the input, some dynamic overloading as such. I don't know the exact solution, but I think that this is the problem.

![image](https://user-images.githubusercontent.com/23421705/192364874-51dff687-ef02-41b4-831c-05b3ecdfb172.png)

**Comment by erictraut** [comment]
Pylance is working correctly in terms of static type checking. The function `get_args` is declared as follows in the `typing.pyi` type stub.

```python
def get_args(tp: Any) -> tuple[Any, ...]: ...
```

This indicates that the function accepts a single argument which can be of any type, and it returns a value that is a tuple of unknown length with `Any` values.

You are using `get_args` in a way that is not intended. It is intended for runtime introspection of types that have been specialized, not for static typing. Also, `Literal` is a special form, not a generic type.

**Comment by CaedenPH** [comment]
> Pylance is working correctly in terms of static type checking. The function `get_args` is declared as follows in the `typing.pyi` type stub.
> 
> 
> 
> ```python
> 
> def get_args(tp: Any) -> tuple[Any, ...]: ...
> 
> ```
> 
> 
> 
> This indicates that the function accepts a single argument which can be of any type, and it returns a value that is a tuple of unknown length with `Any` values.
> 
> 
> 
> You are using `get_args` in a way that is not intended. It is intended for runtime introspection of types that have been specialized, not for static typing. Also, `Literal` is a special form, not a generic type. 

Okay, but how do I cast `c: modes`?
