### ISSUE TITLE
auto import works well with "pandas" but not work with "ipynbname"

### ISSUE THREAD

**Issue by WystanW** [microsoft/pylance-release#3398]
## Environment data

-   Language Server version: v2022.9.40
-   OS and version: Ubuntu 20.04 in Dev Container
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7

## Code Snippet

```python
import ipynbname
ipynbname.name()
```

## Repro Steps

I'm using the Dev Containers plugin(Visual Studio Code Remote - Containers) to develop in a Ubuntu 20.04 container

![image](https://user-images.githubusercontent.com/18168353/192456550-e1d7b076-48e4-4a8c-baad-a244a18befff.png)

1. My settings.json in User/Dev Container(vscode plugin)/Workspace:

```json
{
    "jupyter.debugJustMyCode": false,
    "python.formatting.blackArgs": [
        "--skip-string-normalization",
        "--line-length",
        "88"
    ],
    "editor.formatOnSave": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
        "--max-line-length=88"
    ],
    "python.linting.flake8Path": "/opt/miniconda3/envs/mlflow-dev-env/bin/flake8",
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.languageServer": "Pylance",
    "python.analysis.autoImportCompletions": true,
    "python.analysis.indexing": true,
    "python.analysis.stubPath": "",
    "python.analysis.logLevel": "Trace",
    "editor.fontSize": 20,
    "autoimport.showNotifications": true,
    "autoimport.filesToScan": "**/*.{ts,tsx,py}",
    "python.analysis.importFormat": "absolute",
    "python.analysis.extraPaths": [
        "/opt/miniconda3/envs/mlflow-dev-env/lib/python3.7/site-packages/ipynbname"
    ],
    "python.autoComplete.extraPaths": [
        "/opt/miniconda3/envs/mlflow-dev-env/lib/python3.7/site-packages/ipynbname"
    ],
}
```

These 3 files are same. As you see "python.analysis.autoImportCompletions" is true, "python.analysis.indexing" is true, "python.analysis.stubPath" is ""

## Expected behavior

When I enter "pandas", the auto import works well

![image](https://user-images.githubusercontent.com/18168353/192455555-710828b1-4a36-4a3e-8da8-27791c081b5d.png)

## Actual behavior

But when I enter "ipynbname", the auto import didn't work until I import the package manually

![image](https://user-images.githubusercontent.com/18168353/192456119-7de19702-ecc6-44e0-b414-63eb5312826b.png)

![image](https://user-images.githubusercontent.com/18168353/192456262-5f430cb5-a351-42fe-b0d9-554bf416a5f8.png)

How can the auto import feature works when I enter "ipynb..." to get a tooktip? (The quick fix also not work)

XXX

## Logs

Output from the Python language server is as follows in the txt file

**Comment by WystanW** [comment]
[log.txt](https://github.com/microsoft/pylance-release/files/9652762/log.txt)

**Comment by heejaechang** [comment]
This is happening because ipynbname doesn't have ```__all__``` that expose any symbol in top level ```__init__``` file.

you can use this hidden option to tell us to pick it up
"python.analysis.packageIndexDepths":[["ipynbname",1, true]]

see this comment for more detail - https://github.com/microsoft/pylance-release/issues/2543#issuecomment-1092055466

by the way, we will soon have proper doc and make the option official, but for now, it is a hidden option.
