### ISSUE TITLE
Bug on Pylance 2022.9.40 (released Sept 28, 2022)

### ISSUE THREAD

**Issue by fismoilov20** [microsoft/pylance-release#3401]
## Environment data

-   Language Server version: 2022.9.40
-   OS and version: Windows 10 21H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.

Screenshot with 2022.9.40 version:
![Bug_2022 9 40](https://user-images.githubusercontent.com/101515354/192743230-0234a190-7375-438a-92fd-7992ca3394cb.png)

Screenshot with 2022.9.30 version:
![NoBug_2022 9 30](https://user-images.githubusercontent.com/101515354/192743622-c3ee21da-0a5e-4cf8-9141-74828b425f5f.png)

## Description
Today on Sept 28, 2022 I encountered this little but not for me problem, IntelliSense, which was working perfectly a day before, doesn't suggest from Django packages as shown in [Bug_2022 9 40] picture. 

Then I turned to my laptop with Linux and IntelliSense worked fine as usual, but at that moment I noticed the icon that some extension was being upgraded and that was Pylance. After it completed its upgrade I encountered the same bug. Afterwards I reinstalled the previous version 2022.9.30 & it worked fine again and I realized that the error is in Pylance 2022.9.40.

I hope you definitely fix this issue. If you viewed my submit please reply to me by mkvazowski@gmail.com or fismoilov20@gmail.com

## Expected behavior

2022.9.30 behavior

## Actual behavior

2022.9.40 behavior

**Comment by bschnurr** [comment]
Old stubs override `__init__`

https://github.com/typeddjango/django-stubs/blob/1f2e406972f25aef559d7447bb2856a259aa10cb/django-stubs/db/models/fields/__init__.pyi#L290

new stubs override `__new__`
https://github.com/sbdchd/django-types/blob/21986083b5625c9eb0e6ee1709bd608f6945cbea/django-stubs/db/models/fields/__init__.pyi#L687

**Comment by CatPeare** [comment]
2022.10.10 has the same bug.

**Comment by tombohub** [comment]
> Old stubs override `__init__`
> 
> https://github.com/typeddjango/django-stubs/blob/1f2e406972f25aef559d7447bb2856a259aa10cb/django-stubs/db/models/fields/__init__.pyi#L290
> 
> new stubs override `__new__` https://github.com/sbdchd/django-types/blob/21986083b5625c9eb0e6ee1709bd608f6945cbea/django-stubs/db/models/fields/__init__.pyi#L687

@bschnurr Hi, why are there 'new' and 'old' stubs? 

When I go to .venv/Lib/django-stubs it uses `__init__`: 
![image](https://user-images.githubusercontent.com/3029412/200172330-da9f2fd1-0b51-4b24-8f58-252021de37f0.png)

why pylance is not using those?

thanks

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221141-30-November-2022-PreRelease)

**Comment by ifirdavs** [comment]
Finally updated from stable version:
2022.12.20 -> 2026.3.1
