### ISSUE TITLE
False positive args check when both __new__ and __init__ are presented

### ISSUE THREAD

**Issue by qsz13** [microsoft/pylance-release#3404]
<h3> Environment data </h3>

-   Language Server version: 2022.9.40
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class Base():
    def __init__(self):
        print("init without args")

class Child(Base):
    def __new__(cls, *args, **kwargs):
        print("it works, args:", *args)
        return args[0] 

Child(123)
```

<h3> Repro Steps </h3>

1. `"python.analysis.typeCheckingMode": "basic",`
2. put the code in a .py file

<h3> Expected behavior</h3>

No error, the code runs fine in the interpreter.

![no error](https://user-images.githubusercontent.com/4075761/192898322-a761e2bd-8f61-4c76-ad5d-f1e757cab8fc.png)

<h3> Actual behavior </h3>

error on the last line 
```
Expected 0 positional arguments
```
![error](https://user-images.githubusercontent.com/4075761/192898253-973a1ee5-6c7e-4dcb-8041-ac517c8f1cac.png)

**Comment by erictraut** [comment]
This is intended behavior. Arguments passed to a constructor call are validated against both `__init__` and `__new__` methods, and they must work with both if you want to avoid an error.

In your example, you are using `__new__` in a very non-standard manner to return one of the arguments to the constructor rather than constructing an instance of the class.

A static type checker needs to make certain assumptions. There will always be ways in Python to break these assumptions if you try hard enough. In this case, you'll need to either avoid this behavior in your code or use a `# type: ignore` or `# pyright: ignore` comment to suppress the error.

**Comment by qsz13** [comment]
For our use case, the Child class wasn't meant for initialization, it was meant for doing some validation, and then returning an object of a different type.

Making __init__ the same arguments as __new__ does solve the problem, but I just think giving errors when the code runs perfectly fine in runtime is a bug for the static type checker.

Maybe we can validate between __new__ and the actual return type of __new__?

**Comment by erictraut** [comment]
There are many pieces of code that will "run perfectly fine" (i.e. will not crash) but will not pass static type checking. The goal of a static type checker is to give you a tool for writing code that is robust, bug-free, and maintainable. You can always subvert a static type checker if you try hard enough.

Validating the behavior of a constructor call in Python is complex. A type checker needs to handle both `__new__` and `__init__` (each of which potentially comes from a different class in a class hierarchy and is possibly overloaded). It also needs to handle generic classes where the parameters of `__init__` and/or `__new__` dictate the type arguments for the resulting class instance, `__init__` methods that have an annotated `self` parameter, [bidirectional type inference](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#bidirectional-type-inference-expected-types), and many other complexities.

The algorithm used in pyright (the type checker that underlies pylance) has been tuned over several years to handle a wide variety of cases. It is based on some basic assumptions about the way constructors typically work in Python and incorporates some heuristics. It's possible to violate these assumptions or for these heuristics to fail. Changes that we make to the current algorithm might fix an edge case like the one in your code, but will likely result in false positives in more common cases. This is true for the change you're suggesting, so it wouldn't be a good tradeoff to make such a change.

What you're doing here violates a pretty basic assumption about constructors in Python. I would recommend against this coding pattern. If you decide not to change your code, you can suppress the error using `# type: ignore`. Another option is to include a bogus `__init__` method within the `Child` class — one that accepts `*args` and `**kwargs`.

**Comment by qsz13** [comment]
Fair enough. I'm new to the project I'm working on so I don't have the context why it was written this way. Closing the issue now, thanks!
