### ISSUE TITLE
User documentation on import hook-based editable installs (PEP 660)

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3407]
Add user documentation somewhere explaining:

- Why import hooks are a problem for static analysis tools
- The downside of opting out of import hooks -- your editable install may not match your real install as closely as it could.
- How to out-out of import hooks in common build backends. Graham started that [here](https://github.com/microsoft/pylance-release/wiki/FAQ#packages-are-not-found-when-using-editable-installs). We might need to move it for discoverability.
    - setuptools: [legacy behavior](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#legacy-behavior) / [strict mode](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#strict-editable-installs)
    - [hatchling](https://hatch.pypa.io/latest/config/build/#dev-mode)
    - [pdm](https://pdm.fming.dev/latest/pyproject/build/#editable-build-backend)

For https://github.com/microsoft/pyrx/issues/2715

**Comment by ofek** [comment]
Hatchling does the `.pth` file way by default

**Comment by debonte** [comment]
> Hatchling does the `.pth` file way by default

Thanks @ofek. For hatchling I think we would just explain that `dev-mode-exact = true` enables import hooks and could cause issues with Pylance.
