### ISSUE TITLE
Import "matplotlib.pyplot" could not be resolved from sourcePylancereportMissingModuleSource

### ISSUE THREAD

**Issue by wnsgr** [microsoft/pylance-release#3409]
Hi.
Missing module

[5](vscode-notebook-cell:/c%3A/Users/......?line=4) import sys
      [6](vscode-notebook-cell:/c%....?line=5) import numpy as np 
----> [8](vscode-notebook-cell:/c%.....?line=7) import matplotlib.pyplot as plt
      [9](vscode-notebook-cell:/c%....?line=8) get_ipython().run_line_magic('matplotlib', 'inline')
     [11](vscode-notebook-cell:/c%.....?line=10) def Plotvec1(u, z, v):

ModuleNotFoundError: No module named 'matplotlib'

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.

**Comment by maruf-pfc** [comment]
Use this version `matplotlib>=3.3.0`
