### ISSUE TITLE
operators emulating numeric types are (wrongly) guessed as not supported when operands are generic types

### ISSUE THREAD

**Issue by Questionsdenombres** [microsoft/pylance-release#3410]
## Environment data
- Pylance v2022.9.40
- Python version(3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36)
- Visual studio: 1.71.2
- Windows-10-10.0.19042-SP0

## Code Snippet
```python
from collections import Counter
from collections.abc import Iterable
from datetime import timedelta
from typing import TypeVar

_T = TypeVar('_T')
def my_func(a: _T, b: _T) -> _T:
    """ my_func """
    c: _T
    c = -a # reported as not supported
    c = 2 * a # idem
    c = a + b # idem
    c = a - b # idem
    c = a | b # idem
    c = a / b # idem
    c = a // b # idem
    c = a & b # idem
    c = a % b # idem
    c = a * b # idem
    return c

# Use cases: emulating 'sum' on non basic numeric types:
def summation(iterable: Iterable[_T], start: _T) -> _T:
    """ summation """
    _sum: _T = start
    for item in iterable:
        _sum += item
        # Report:
        #    Operator "+=" not supported for types "_T@summation" and "_T@summation"
        #    Operator "+" not supported for types "object*" and "object*"
    return _sum

counters: list[Counter[str]] = [
    Counter(a=1, b=2),
    Counter(a=10, c=4),
    Counter(b=5, d=3),
]
zero_counter: Counter[str] = Counter()
print(summation(counters, start=zero_counter))

elapsed: list[timedelta] = [
    timedelta(seconds=17),
    timedelta(seconds=37),
    timedelta(seconds=59),
]
print(summation(elapsed, start=timedelta()))
```

## Expected behavior
- I wonder whether it is a bug or a feature.
- I understand the situation is not easy:  when analyzing the function, the generic type `_T` is unknown  and the type checker doesn't know neither if the operation is defined nor the type it returns.
- However the guess that the operations are not supported seems a bit bold and it can be wrong as shown by the use cases.
- Hence I would have expected no report.
- The only possible current workaround I see is `type: ignore`.

Again thank you for your great tool!
Patrick Bourdon - PARIS

**Comment by erictraut** [comment]
Pyright (the type checker that underlies pylance) is working correctly here. When you use a type variable like `_T` in your example, it can be substituted for any `object`. Some objects don't support numeric operators, so the type checker is telling you that your program will crash if you pass objects of arbitrary type to `my_func`.

What you can do here is specify that `_T` has an "upper bound" type that constrains which types can be bound to `_T`. You can use a protocol class as a bound. For example, if you want to indicate that `_T` can be any type that supports addition, you could do the following:

```python
_T = TypeVar("_T")

class SupportsAdd(Protocol):
    def __add__(self: _T, obj: _T, /) -> _T:
        ...

_TAdd = TypeVar("_TAdd", bound=SupportsAdd)

def my_func(a: _TAdd, b: _TAdd) -> _TAdd:
    c: _TAdd = a + b
    return c
```

**Comment by Questionsdenombres** [comment]
Thank you very much for the direction.
I read many times about "protocol" (and some from you), but I never really dive in to understand the abstraction.
I have to ... "PEP 544 – Protocols: Structural subtyping (static duck typing)"
