### ISSUE TITLE
No type errors shown in interactive windows and unsaved notebooks

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3412]
## Environment data
-   Language Server version: 2022.9.41
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0a7

## Repro Steps

1. Run "Jupyter: Create Interactive Window" or "Create: New Jupyter Notebook" from command palette
2. Create cell with:
```python
def foo(x: int):
    return x

foo("str")
```

## Expected behavior
Error on "str":
>Argument of type "Literal['str']" cannot be assigned to parameter "x" of type "int" in function "foo"
  "Literal['str']" is incompatible with "int"Pylance[reportGeneralTypeIssues]

![image](https://user-images.githubusercontent.com/12820898/193196550-90870b73-1376-4464-809f-d002570b3808.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/12820898/193191966-73188145-a577-4788-8117-ff02016f7124.png)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2022.10.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221031-19-October-2022-PreRelease)
