### ISSUE TITLE
Go to Type Definition on TypeAlias should include location of TypeAlias in results

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3413]
## Code Snippet

```python
from os import PathLike
from typing import TypeAlias

StrPath: TypeAlias = str | PathLike[str]

var: StrPath
```

## Repro Steps
1. Right-click on `var` and select "Go to Type Definition"

## Expected behavior
List of results includes StrPath alias.

## Actual behavior
List of results only includes `str` and `PathLike`, the members of the union.

![image](https://user-images.githubusercontent.com/12820898/193199275-855f4c3f-59eb-4d6a-b3ef-8bb5e541e7dc.png)

**Comment by erictraut** [comment]
I don't think the type alias should be included in the list here. A type alias is just a convenient name for a particular type (often a union of other types); it's not a type itself.

The pyright type evaluator doesn't currently retain enough information about a type alias associated with a type to determine the original declaration location. It's theoretically possible to add this, but it would increase the amount of information tracked for every internal type object and the amount of work performed when transforming these types.

For comparison, TypeScript also does not include type aliases in in the "Go To Type Definition" list — presumably for the same reasons I mentioned above.

**Comment by debonte** [comment]
That's fine. For what it's worth my thought process as a user was something like:

1. Hover over var to see what type it is.
2. "Oh, it's a `StrPath`, let's see what that is.
3. Go to Type Definition
4. Confused about why I'm not seeing info about StrPath.

In my case `StrPath` was not defined locally and I didn't have convenient access to a `StrPath` token in my code that I could Go to Definition on.
