### ISSUE TITLE
Methods are Inferred as Variables

### ISSUE THREAD

**Issue by Alecton4** [microsoft/pylance-release#3416]
## Environment data

-   Language Server version: 2022.9.40
-   OS and version: Windows_NT x64 10.0.19044
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.13 (using venv)

## Code Snippet

```python
import numpy as np
# numpy version is 1.23.3

arr = np.random.random((3,3,3))
```

## Repro Steps

1. Create a `test.py` file;
2. Write the above codes;
3. Issue occurs. (Indeed methods in Python are also objects, so I'm not sure whether this is an issue or a feature to be improved)

## Expected behavior

`random` should be inferred as a "method". 

Because when ctrl-clicking `random`, which goes to the definition, the following is shown. And clearly `random` should also be a "method" as `_rand.random`.

![image](https://user-images.githubusercontent.com/43232804/193253638-d808162f-ce72-49cc-b263-42f3ad20f9e5.png)

## Actual behavior

`random` is inferred as a "variable" as shown below.

![image](https://user-images.githubusercontent.com/43232804/193252467-efaa5dbd-6671-4dd8-9b45-de8895147472.png)

## Logs

<details>
<summary>log</summary>
<pre><code>
[Info  - 6:36:06 PM] (26472) Pylance language server 2022.9.40 (pyright 9fd1b94c) starting
[Info  - 6:36:06 PM] (26472) Server root directory: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist
[Info  - 6:36:06 PM] (26472) Starting service instance "course"
[Info  - 6:36:06 PM] (26472) Starting service instance "Coursera1"
[Info  - 6:36:06 PM] (26472) Starting service instance "numpy-100"
[Info  - 6:36:06 PM] (26472) Notebook support: LSP
[Info  - 6:36:06 PM] (26472) Interactive window support: LSP
[Info  - 6:36:06 PM] (26472) No configuration file found.
[Info  - 6:36:06 PM] (26472) No pyproject.toml file found.
[Info  - 6:36:06 PM] (26472) Setting pythonPath for service "course": "d:\workspace\COMP4211\course\.venv\Scripts\python.exe"
[Warn  - 6:36:06 PM] (26472) stubPath d:\workspace\COMP4211\course\typings is not a valid directory.
[Info  - 6:36:06 PM] (26472) Assuming Python version 3.9
[Info  - 6:36:06 PM] (26472) Assuming Python platform Windows
[Info  - 6:36:07 PM] (26472) Search paths for d:\workspace\COMP4211\course
[Info  - 6:36:07 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course\typings
[Info  - 6:36:07 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stubs\...
[Info  - 6:36:07 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\bundled\stubs
[Info  - 6:36:07 PM] (26472)   c:\Program_Files\Python39\DLLs
[Info  - 6:36:07 PM] (26472)   c:\Program_Files\Python39\Lib
[Info  - 6:36:07 PM] (26472)   c:\Program_Files\Python39
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course\.venv
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course\.venv\Lib\site-packages
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course\.venv\Lib\site-packages\win32
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course\.venv\Lib\site-packages\win32\lib
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\course\.venv\Lib\site-packages\pythonwin
[Info  - 6:36:07 PM] (26472) Adding fs watcher for library directories:
 C:\Program_Files\Python39\DLLs
C:\Program_Files\Python39\lib
C:\Program_Files\Python39
d:\workspace\COMP4211\course\.venv
d:\workspace\COMP4211\course\.venv\lib\site-packages
d:\workspace\COMP4211\course\.venv\lib\site-packages\win32
d:\workspace\COMP4211\course\.venv\lib\site-packages\win32\lib
d:\workspace\COMP4211\course\.venv\lib\site-packages\Pythonwin
[Info  - 6:36:07 PM] (26472) Adding fs watcher for directories:
 d:\workspace\COMP4211\course
[Info  - 6:36:07 PM] (26472) Searching for source files
[Info  - 6:36:07 PM] (26472) Found 1 source file
[Info  - 6:36:07 PM] (26472) Background analysis(3) root directory: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist
[Info  - 6:36:07 PM] (26472) Background analysis(3) started
[Info  - 6:36:07 PM] (26472) Background analysis(1) root directory: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist
[Info  - 6:36:07 PM] (26472) Background analysis(1) started
(26472) Background analysis message: setConfigOptions
(26472) Background analysis message: setImportResolver
(26472) Background analysis message: ensurePartialStubPackages
[Info  - 6:36:07 PM] (26472) Background analysis(2) root directory: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist
[Info  - 6:36:07 PM] (26472) Background analysis(2) started
[Info  - 6:36:07 PM] (26472) No configuration file found.
[Info  - 6:36:07 PM] (26472) No pyproject.toml file found.
[Info  - 6:36:07 PM] (26472) Setting pythonPath for service "Coursera1": "d:\workspace\COMP4211\Coursera1\.venv\Scripts\python.exe"
[Warn  - 6:36:07 PM] (26472) stubPath d:\workspace\COMP4211\Coursera1\typings is not a valid directory.
[Info  - 6:36:07 PM] (26472) Assuming Python version 3.9
[Info  - 6:36:07 PM] (26472) Assuming Python platform Windows
[Info  - 6:36:07 PM] (26472) Search paths for d:\workspace\COMP4211\Coursera1
[Info  - 6:36:07 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1\typings
[Info  - 6:36:07 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stubs\...
[Info  - 6:36:07 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\bundled\stubs
[Info  - 6:36:07 PM] (26472)   c:\Program_Files\Python39\DLLs
[Info  - 6:36:07 PM] (26472)   c:\Program_Files\Python39\Lib
[Info  - 6:36:07 PM] (26472)   c:\Program_Files\Python39
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1\.venv
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1\.venv\Lib\site-packages
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1\.venv\Lib\site-packages\win32
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1\.venv\Lib\site-packages\win32\lib
[Info  - 6:36:07 PM] (26472)   d:\workspace\COMP4211\Coursera1\.venv\Lib\site-packages\pythonwin
[Info  - 6:36:08 PM] (26472) Adding fs watcher for library directories:
 C:\Program_Files\Python39\DLLs
C:\Program_Files\Python39\lib
C:\Program_Files\Python39
d:\workspace\COMP4211\Coursera1\.venv
d:\workspace\COMP4211\Coursera1\.venv\lib\site-packages
d:\workspace\COMP4211\Coursera1\.venv\lib\site-packages\win32
d:\workspace\COMP4211\Coursera1\.venv\lib\site-packages\win32\lib
d:\workspace\COMP4211\Coursera1\.venv\lib\site-packages\Pythonwin
[Info  - 6:36:08 PM] (26472) Adding fs watcher for directories:
 d:\workspace\COMP4211\Coursera1
[Info  - 6:36:08 PM] (26472) Searching for source files
[Info  - 6:36:08 PM] (26472) Found 60 source files
[Info  - 6:36:08 PM] (26472) No configuration file found.
[Info  - 6:36:08 PM] (26472) No pyproject.toml file found.
[Info  - 6:36:08 PM] (26472) Setting pythonPath for service "numpy-100": "d:\workspace\COMP4211\numpy-100\.venv\Scripts\python.exe"
[Warn  - 6:36:08 PM] (26472) stubPath d:\workspace\COMP4211\numpy-100\typings is not a valid directory.
[Info  - 6:36:08 PM] (26472) Assuming Python version 3.9
[Info  - 6:36:08 PM] (26472) Assuming Python platform Windows
[Info  - 6:36:08 PM] (26472) Search paths for d:\workspace\COMP4211\numpy-100
[Info  - 6:36:08 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100\typings
[Info  - 6:36:08 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stubs\...
[Info  - 6:36:08 PM] (26472)   d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\bundled\stubs
[Info  - 6:36:08 PM] (26472)   c:\Program_Files\Python39\DLLs
[Info  - 6:36:08 PM] (26472)   c:\Program_Files\Python39\Lib
[Info  - 6:36:08 PM] (26472)   c:\Program_Files\Python39
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100\.venv
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\win32
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\win32\lib
[Info  - 6:36:08 PM] (26472)   d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\pythonwin
[Info  - 6:36:08 PM] (26472) Adding fs watcher for library directories:
 C:\Program_Files\Python39\DLLs
C:\Program_Files\Python39\lib
C:\Program_Files\Python39
d:\workspace\COMP4211\numpy-100\.venv
d:\workspace\COMP4211\numpy-100\.venv\lib\site-packages
d:\workspace\COMP4211\numpy-100\.venv\lib\site-packages\win32
d:\workspace\COMP4211\numpy-100\.venv\lib\site-packages\win32\lib
d:\workspace\COMP4211\numpy-100\.venv\lib\site-packages\Pythonwin
[Info  - 6:36:08 PM] (26472) Adding fs watcher for directories:
 d:\workspace\COMP4211\numpy-100
[Info  - 6:36:08 PM] (26472) Searching for source files
[Info  - 6:36:08 PM] (26472) Found 3 source files
(26472) [IDX(FG)] index libraries d:\workspace\COMP4211\numpy-100 (index) ...
(26472) [IDX(FG)]   read stdlib indices (33ms)
(26472) [IDX(FG)] index libraries d:\workspace\COMP4211\numpy-100 (index) [succeed] (34ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\test.py (27ms)
(26472) [FG] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 4ms] (114ms)
(26472) [FG] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\builtins.pyi (50ms)
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\test.py (0ms)
(26472) Background analysis message: setTrackedFiles
(26472) Background analysis message: markAllFilesDirty
(26472) Background analysis message: analyze
(26472) Background analysis message: setConfigOptions
(26472) Background analysis message: setImportResolver
(26472) Background analysis message: ensurePartialStubPackages
(26472) Background analysis message: setTrackedFiles
(26472) Background analysis message: markAllFilesDirty
(26472) Background analysis message: analyze
(26472) Background analysis message: setConfigOptions
(26472) Background analysis message: setImportResolver
(26472) Background analysis message: ensurePartialStubPackages
(26472) Background analysis message: setTrackedFiles
(26472) Background analysis message: markAllFilesDirty
(26472) Background analysis message: setFileOpened
(26472) Background inlayHint message
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\test.py (35ms)
[Info  - 6:36:08 PM] (26472) SourceFile: Received fs event 'change' for path 'd:\workspace\COMP4211\course\.git\FETCH_HEAD'
(26472) [BG(3)] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\builtins.pyi [fs read 3ms] (141ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\builtins.pyi (49ms)
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\test.py (0ms)
(26472) [BG(3)] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing.pyi [fs read 2ms] (38ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing.pyi (9ms)
(26472) [BG(3)] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 0ms] (5ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing_extensions.pyi (3ms)
(26472) [BG(3)] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 1ms] (21ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (3ms)
(26472) [BG(3)] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\abc.pyi [fs read 1ms] (2ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\abc.pyi (1ms)
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\__init__.pyi [fs read 2ms] (268ms)
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\__init__.pyi (57ms)
[Info  - 6:36:09 PM] (26472) SourceFile: Received fs event 'change' for path 'd:\workspace\COMP4211\Coursera1\.git\FETCH_HEAD'
[Info  - 6:36:09 PM] (26472) SourceFile: Received fs event 'change' for path 'd:\workspace\COMP4211\numpy-100\.git\FETCH_HEAD'
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\__init__.pyi [fs read 1ms] (36ms)
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\__init__.pyi (1ms)
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\mtrand.pyi [fs read 1ms] (9ms)
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\mtrand.pyi (6ms)
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\__init__.py [fs read 1ms] (13ms)
[Info  - 6:36:09 PM] (26472) Could not resolve source for '._ufunc' in file 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\__init__.py'
[Info  - 6:36:09 PM] (26472)   Attempting to resolve relative import
[Info  - 6:36:09 PM] (26472)   Attempting to resolve using root path 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing'
[Info  - 6:36:09 PM] (26472)   Resolved import with file 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\_ufunc.pyi'
[Info  - 6:36:09 PM] (26472)   Attempting to resolve using root path 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing'
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\__init__.py (1ms)
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\_shape.py [fs read 0ms] (2ms)
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\_shape.py (0ms)
(26472) [BG(3)] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\core\overrides.py [fs read 1ms] (17ms)
(26472) [BG(3)] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\core\overrides.py (2ms)
(26472) [BG(3)] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\collections\abc.pyi [fs read 0ms] (0ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\collections\abc.pyi ...
(26472) [BG(3)]   parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\_collections_abc.pyi [fs read 0ms] (2ms)
(26472) [BG(3)]   binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\_collections_abc.pyi (1ms)
(26472) [BG(3)] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\collections\abc.pyi (4ms)
(26472) Background analysis message: getSemanticTokens full
(26472) [BG(3)] getSemanticTokens full at d:\workspace\COMP4211\numpy-100\test.py (4ms)
(26472) Background analysis message: analyze
(26472) [BG(3)] analyzing: d:\workspace\COMP4211\numpy-100\test.py ...
(26472) [BG(3)]   checking: d:\workspace\COMP4211\numpy-100\test.py (5ms)
(26472) [BG(3)] analyzing: d:\workspace\COMP4211\numpy-100\test.py (6ms)
(26472) Background analysis message: getSemanticTokens range
(26472) [BG(3)] getSemanticTokens range 0:0 - 3:0 at d:\workspace\COMP4211\numpy-100\test.py (1ms)
(26472) Background analysis message: resumeAnalysis
(26472) Loading ONNX runtime...
(26472) Loaded ONNX runtime. Creating IntelliCode session...
(26472) Created IntelliCode session.
(26472) Initialize deeplearning succeeded
(26472) Created IntelliCode session.
(26472) Initialize deeplearning succeeded
(26472) [FG] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing.pyi [fs read 2ms] (46ms)
(26472) [FG] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing.pyi (8ms)
(26472) [FG] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 1ms] (4ms)
(26472) [FG] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\typing_extensions.pyi (3ms)
(26472) [FG] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 1ms] (9ms)
(26472) [FG] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (3ms)
(26472) [FG] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\abc.pyi [fs read 0ms] (1ms)
(26472) [FG] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\typeshed-fallback\stdlib\abc.pyi (1ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\__init__.pyi [fs read 1ms] (219ms)
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\__init__.pyi (37ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\__init__.pyi [fs read 0ms] (33ms)
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\__init__.pyi (1ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\mtrand.pyi [fs read 1ms] (10ms)
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\random\mtrand.pyi (11ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\__init__.py [fs read 1ms] (10ms)
[Info  - 6:36:13 PM] (26472) Could not resolve source for '._ufunc' in file 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\__init__.py'
[Info  - 6:36:13 PM] (26472)   Attempting to resolve relative import
[Info  - 6:36:13 PM] (26472)   Attempting to resolve using root path 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing'
[Info  - 6:36:13 PM] (26472)   Resolved import with file 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\_ufunc.pyi'
[Info  - 6:36:13 PM] (26472)   Attempting to resolve using root path 'd:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing'
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\__init__.py (0ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\_shape.py [fs read 0ms] (0ms)
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\_typing\_shape.py (0ms)
(26472) [FG] parsing: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\core\overrides.py [fs read 0ms] (15ms)
(26472) [FG] binding: d:\workspace\COMP4211\numpy-100\.venv\Lib\site-packages\numpy\core\overrides.py (1ms)
(26472) [FG] parsing: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\bundled\native-stubs\numpy\random\mtrand.pyi [fs read 1ms] (42ms)
(26472) [FG] binding: d:\yzhao\.vscode\extensions\ms-python.vscode-pylance-2022.9.40\dist\bundled\native-stubs\numpy\random\mtrand.pyi (1ms)
(26472) Background inlayHint message
</code></pre>
</details>

**Comment by erictraut** [comment]
In the hover text, the initial text in parentheses indicates the declaration type of the symbol in question, and the evaluated type of that symbol is displayed next. 

In your example, the symbol `random` is declared as a variable, not a method. So pylance is correct to display `(variable)` here. Variable declarations take the form `x = <expression>`. Function declarations take the form `def x(<param list) ...`. Method declarations are function declarations nested within a class declaration.

The variable `random` happens to be assigned a value that is a method, so the inferred type of `random` is a function (in this case an overloaded function that has multiple signatures). That's why you see the type `random(size: None = ...) -> float ...` displayed within the hover text.

**Comment by erictraut** [comment]
> But is it possible to make some optimization for variables that are actually methods?

The symbol `random` is not a method. It's a variable. It happens to receive a value through an assignment statement, and the expression assigned to it happens to evaluate to a method type. But that doesn't change the fact that `random` is a variable. So it would be inappropriate and inconsistent to display it as a method.

Even if this weren't a consistency issue, there's a major implementation hurdle that would prevent pylance from indicating that `random` is a method within the completion suggestion list. The full list of completion suggestions is built prior to any type evaluation. The symbol category for each completion suggestion (which dictates which icon you see to the left of the item in the pop-up menu) is based entirely on the symbol's declaration, not on its type. The declaration form is cheap to determine, whereas the type can be very expensive to evaluate. For that reason, the type is resolved only once you select that item from the menu. If we were to evaluate the types of every symbol before displaying the completion suggestion list, you'd often need to wait for multiple seconds for the popup to appear. That would destroy the user experience.

**Comment by Alecton4** [comment]
@erictraut Thanks for the elaboration! I agree with you :)
