### ISSUE TITLE
Pylance failed to connect

### ISSUE THREAD

**Issue by TaqiHaider-el** [microsoft/pylance-release#3420]
## Environment data

-   Language Server version: Pylance
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet
![Capture](https://user-images.githubusercontent.com/96980772/193423411-c087b4a8-41fd-41d2-b82d-7921006b9329.JPG)

```python
3.10
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

Pylance client: couldn't create connection to server.

## Logs

```
XXX
```

**Comment by debonte** [comment]
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by debonte** [comment]
@TaqiHaider-el, did you figure out what was going on?

**Comment by TaqiHaider-el** [comment]
Yes. I just reinstalled the vs code and it's working fine. Thank you for your help
