### ISSUE TITLE
Pylance unable to detect venv modules

### ISSUE THREAD

**Issue by SE-Nitro** [microsoft/pylance-release#3421]
The "Python" extension could detect the venv, but Pylance produces a `reportMissingImports` error, even though numpy is installed in the venv.
If I remember correctly, this issue was said to be solved some years ago, but apparently, it still exists.
<h3> Environment data </h3>

-   Language Server version: 2022.9.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.2
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
 import numpy as np
```

<h3> Expected behavior </h3>

Import the module

<h3> Error </h3>

`Import "numpy" could not be resolved Pylance`([`reportMissingImports`](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules))

<h3> Image </h3>
<img title="Error" src="https://i.imgur.com/cPElUoc.png" alt="reportMissingImports"/>
<img title="Program" src="https://i.imgur.com/V7BBHwV.png" alt="prints numpy version"/>

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.

**Comment by ElR4T0n** [comment]
> I just ran across this today, and this worked for me too. Here are the detailed steps for anyone else arriving here:
> 
> * Click on the VSCode status bar on the bottom-right where it says `{ } Python` and a version number.
> * At the top of VSCode, click on "Enter interpreter path..."
> * Browse to your project's .venv folder and select `\Your\Project\Dir\.venv\Scripts\python.exe`.
> 
> Now my status bar says `{ } Python 3.10.11 ('.venv': venv)` and the squiggles are gone.

Im on the same spot, but that didnt resolve my issue :(

**Comment by agudallago** [comment]
+1 hitting the same issue with flatbuffers

**Comment by DePasqualeOrg** [comment]
This is still a problem for me, and it seems for others as well. Can we reopen this?

**Comment by rchiodo** [comment]
@DePasqualeOrg please open a new issue instead of commenting on older ones. We'd need information specific to your situation and adding onto someone else's issue makes the root cause more confusing.

**Comment by Vanny-Chuck** [comment]
I would heavily recommend setting the interpeter to python3 as opposed to just python in .venv/bin

**Comment by ugoi** [comment]
I did pip3 install <package> instead of pip install <package> and it worked.
