### ISSUE TITLE
Pylance does not pick up on PySide6 dependency

### ISSUE THREAD

**Issue by StayBlueee** [microsoft/pylance-release#3423]
## Environment data
-   Language Server version: v2022.9.4
-   OS and version: macOS Monterey 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): v3.10.7

## Code Snippet
![image](https://user-images.githubusercontent.com/23127866/193482854-0d75ac67-8d6d-47eb-8227-695d4b89cc18.png)

## Repro Steps
1. Install PySide6 via Homebrew
2. Create a virtual environment in the project directory using python3 -m venv --system-site-packages .venv
3. Attempt to import anything from PySide6

## Expected behavior
Working imports and Intellisense for PySide6

## Actual behavior
Error saying it's undefined, even though the code itself compiles fine when I press Play in the top right.
![image](https://user-images.githubusercontent.com/23127866/193482864-164c3b8c-6106-44b5-983d-6cf254a8a4ea.png)

## Logs
I could not find where these logs were located, apologies.

## Additional Notes
I understand that similar issues like this have been reported before, but this issue is very persistent.
I have a virtual environment set up, with Pylance set as my Language Server in the settings. I also tried adding PySide in /opt/homebrew/opt to the extraPaths and analysis in the settings.json file as suggested in the troubleshooting, but it doesn't seem to work.

For some reason, Pylance does recognize PySide6 at first, but it doesn't seem to recognize it after you fill in the autocompletion settings (maybe these are just AI suggestions? I have no idea how Pylance works):
![image](https://user-images.githubusercontent.com/23127866/193483000-380ad502-5eab-49cf-a6fd-691432a22c87.png)

I would be happy to provide any additional information.

**Comment by rchiodo** [comment]
What is your python interpreter in the bottom right set to? This doesn't repro for me but perhaps your interpreter is set to a python that doesn't have PySide6 installed.

![image](https://user-images.githubusercontent.com/19672699/197646693-8097ed01-40c8-4dc6-b0db-dd97c7a4721a.png)

Also what version of PySide6. The one I'm using is `6.4.0`. It seems to have python type stubs. And older version might not.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by RyanHope** [comment]
Still an issue!!!
