### ISSUE TITLE
Missing suggestions for nested neighbor modules.

### ISSUE THREAD

**Issue by krzysztof3-wisniewski** [microsoft/pylance-release#3428]
## Environment data

-   Language Server version: 2022.9.40
-   OS and version: Windows 10 Version	10.0.19044 Build 19044 | Ubuntu 22.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9 | 3.10

## Repro Steps

Assume following project structure (open in Visual Studio Code).
Project must be correctly configured python package, installed into virtual environment.

```
source/
    project1/
        nest1/
            sub1/
                mod1.py
                __init__.py
            sub2/
                mod2.py
                __init__.py
        sub3/
            mod3.py
            __init__.py
```
All files are empty.

Now let's populate `mod1.py` with:

```python
class SomeSymbol:
    pass
```

Then lets open `mod2.py` and start typing:

```python
SomeSym
```

Do same thing for `mod3.py`

## Expected behavior

`class SomeSymbol` should be suggested everywhere, both in `mod2.py` and `mod3.py`.

## Actual behavior

`class SomeSymbol` is suggested in `mod3.py` but its not in `mod2.py`

## Additional information

When suggestions work correctly for "flatter" projects, ie.

```
source/
    project1/
        sub1/
            mod1.py
            __init__.py
        sub2/
            mod2.py
            __init__.py
        sub3/
            mod3.py
            __init__.py
```

Suggestions are available everywhere.
I can not provide logs as issue was found in non public environment. I'll provide them later if necessary.

**Comment by debonte** [comment]
> Project must be correctly configured python package, installed into virtual environment.

Are you saying that there's an editable install involved here? If so, can you provide more explicit instructions on how that should be configured in your sample?

**Comment by krzysztof3-wisniewski** [comment]
Yes, but I'm not 100% sure. It is possible that some of environemnts, I have used, were based on editable builds while others were constantly reinstalling packaged build. I'm considering example similar to [this package](https://github.com/Argmaster/async-py-octocat). I have recently moved to use poetry with simpler setup, but problem still occurs and I haven't fully set up any public project latter way. If you are willing to use async_py_octocat, you will have to follow [this instructions](https://argmaster.github.io/async-py-octocat/howto/tox_devenv/). Otherwise it should be possible to reproduce this issue with minimal poetry project (easiest to acquire) with `poetry init` followed by `poetry shell` and `poetry install` or dev branch of [this repository](https://github.com/Argmaster/eldritch/tree/feature/plugins) (last one is what i used). 
I am willing to help more with reproduction but I have to know which method, out of listed, is prefrerred.

**Comment by debonte** [comment]
> I am willing to help more with reproduction but I have to know which method, out of listed, is prefrerred.

Whichever you prefer is fine with me. If an editable install is involved, I'm wondering if you may be hitting the issues described [here](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#editable-install-modules-not-found).

**Comment by debonte** [comment]
Closing since there's been no response in more than a month. We can reopen if you are able to provide more info.
