### ISSUE TITLE
Crash report logs pile up in root directory

### ISSUE THREAD

**Issue by lucaluca** [microsoft/pylance-release#343]
## Environment data

-   Language Server version: 2020.9.0
-   OS and version: Windows 10 v1909
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4

## Behaviour

Since the update to 2020.9.0, Pylance has been working very well on my workspace. However, it appears that it frequently runs out of memory, which doesn't seem to impact performance except that it's saving a crash log to my root directory every few minutes. I can't find any setting to change where crash logs are stored. 

My workspace has various large folders and files, all of which are ignored by the appropriate VS Code settings (search, file watcher, etc). 

It's not the crashes I want to report here, since I figure that's related to https://github.com/microsoft/pylance-release/issues/321 and will get fixed. It's that I want to put the logs somewhere other than my root directory, like in my `.vscode` folder. 

## Logs
[report.20200908.155430.10105.0.001.txt](https://github.com/microsoft/pylance-release/files/5191038/report.20200908.155430.10105.0.001.txt)

## Code Snippet / Additional information
As far as the crashes themselves, I don't know what large files are causing it. I have a medium-sized workspace (30k lines of Python) but my git, `site-packages`, and other folders are all in the parent folder to the workspace so they shouldn't be searched for symbols.

**Comment by huguesv** [comment]
This looks like it is created by Node.js, and it's creating it in the cwd. We are unsure if it can be customized.

The issue that causes the crash https://github.com/microsoft/pylance-release/issues/321 will be fixed in the next version.
