### ISSUE TITLE
Abnormal memory consumption when used in a root workspace of VS Code

### ISSUE THREAD

**Issue by outremont** [microsoft/pylance-release#3430]
## Environment data

-   Language Server version: 2022.9.40
-   OS and version: Ubuntu 20.04 5.4.0-81-generic
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Repro Steps

1. Open parent folder containing several repositories — also known as the root workspace in VS Code.
2. Monitor memory consumption

## Expected behavior

Manageable memory consumption when used inside the root workspace of VS Code.

## Actual behavior

Whenever I am using Pylance inside the root workspace of VS Code that contains a couple repositories, my memory consumption goes through the roof. As far as I understand, this is happening due to caching of all child folders and their files, but I wanted to see if there is a way to reduce memory consumption.

**Comment by judej** [comment]
Thanks for the report. We made a fix on our latest release that should address this. Could you please get the latest pre-release version (2022.10.11) and see if it still reproduces? 

Please reopen if you are still seeing the issue.

**Comment by outremont** [comment]
Thank you very much, Judej! Will confirm on Monday
