### ISSUE TITLE
Pylance is eagerly and aggressively removing unused imports when saving a module

### ISSUE THREAD

**Issue by jason-s** [microsoft/pylance-release#3436]
## Environment data

-   Language Server version: v2022.9.40
-   OS and version: Windows 10 Pro 19044.1889
-   Python version (& distribution if applicable, e.g. Anaconda): n/a

## Code Snippet

```python
import os

if __name__ == '__main__':
    print("Yo dude!")
```

## Repro Steps

- Enter in code snippet above
- Save as a python module
- Watch as Pylance fixes your code by removing the unused import.

## Expected behavior

Fixing imports should be an action caused by the user. When I am making targeted changes to a file for other reasons aside from the imports, I want my changeset to contain exactly the changes I want to make, not those changes plus other helpful ones.

## Actual behavior

The line `import os` gets deleted.

## Logs

N/A, not using Python output

**Comment by debonte** [comment]
I assume you have `source.fixAll` enabled in `editor.codeActionsOnSave`?

```json
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
```

Removing unused imports is currently a "fixAll" action. See the complete list [here](https://github.com/microsoft/pylance-release#source-code-actions).

You can disable this behavior by adding `"source.fixAll.unusedImports": false` to your `codeActionsOnSave` config:

```json
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.fixAll.unusedImports": false
  },
```

@heejaechang, were we considering removing `unusedImports` from `fixAll`?

**Comment by jason-s** [comment]
> I assume you have source.fixAll enabled in editor.codeActionsOnSave?
>  ```
>  "editor.codeActionsOnSave": {
>   "source.fixAll": true
>  }

No, I don't; that is the weird thing. I looked around for any "On Save" or "OnSave" settings and I couldn't find any that were enabled.

**Comment by debonte** [comment]
> the UI settings in VSCode did not show any indication that it was selected

FYI, the settings UI should have the indicator shown below. If you click on the Workspace link, it will take you to the workspace `settings.json`. If it's set in both your user and workspace settings, it will say, "Also modified in Workspace".

![image](https://user-images.githubusercontent.com/12820898/194374719-449cde78-3ed0-4c09-9251-c2dd24873cf5.png)

**Comment by jason-s** [comment]
Anyway it sounds like the feature itself is working exactly as designed; the usability problems are in the settings and the documentation.

**Comment by debonte** [comment]
Yeah, `codeActionsOnSave` is a feature provided by the editor for use by all languages.
