### ISSUE TITLE
reportMissingimport

### ISSUE THREAD

**Issue by Sanjay-bud** [microsoft/pylance-release#3438]
"message": "Import \"cpngfilters\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 144,
	"startColumn": 12,
	"endLineNumber": 144,
	"endColumn": 23

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
