### ISSUE TITLE
How to disable Auto-excluding venv workspace

### ISSUE THREAD

**Issue by roxizhauk** [microsoft/pylance-release#3441]
## Environment data

-   Language Server version: v2022.10.10
-   OS and version: macOS 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2, venv

## Repro Steps

1. go to WORKSPACE and activate the virtual env.
2. open Vscode.

## Expected behavior

Include all source files under "WORKSPACE" directory.

## Actual behavior

Excluded all source files. I assume it's because Pylance automatically excludes any virtual environment directories.

## Logs

```
[Info  - 10:41:27 AM] (76774) No configuration file found.
[Info  - 10:41:27 AM] (76774) No pyproject.toml file found.
[Info  - 10:41:27 AM] (76774) Setting pythonPath for service "WORKSPACE": "/Users/USERNAME/.dev/python/WORKSPACE/bin/python"
[Warn  - 10:41:27 AM] (76774) stubPath /Users/USERNAME/.dev/python/WORKSPACE/typings is not a valid directory.
[Info  - 10:41:27 AM] (76774) Assuming Python version 3.10
[Info  - 10:41:27 AM] (76774) Assuming Python platform Darwin
[Info  - 10:41:27 AM] (76774) Searching for source files
[Info  - 10:41:27 AM] (76774) Auto-excluding /Users/USERNAME/.dev/python/WORKSPACE
[Info  - 10:41:27 AM] (76774) No source files found.
```

**Comment by heejaechang** [comment]
there is no exposed option. but you can workaround by creating ```pyrightconfig.json``` file (https://github.com/microsoft/pyright/blob/main/docs/configuration.md) and then put dummy ```exclude``` option to hit this - https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/common/configOptions.ts#L671

**Comment by roxizhauk** [comment]
Ok, I understand. Sorry for the late response and thanks for the suggestion!
