### ISSUE TITLE
Couldn't jump to definition or jump to incorrect file in python dotted module names

### ISSUE THREAD

**Issue by yola-0316** [microsoft/pylance-release#3442]
## Environment data

-   Language Server version: v2022.10.11
-   OS and version: macOS Monterey 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6

## Code Snippet

<img width="1985" alt="image" src="https://user-images.githubusercontent.com/4338052/194473352-e3420d43-5ea6-4a61-bba0-cb7b95970660.png">

Example Repo: https://github.com/yola-0316/pylance-issues

## Repro Steps

Write code in `src/app.py` like below:
```py
import web.foo.bar.baz


print(web.MODULE_ID)
print(web.foo.MODULE_ID)
print(web.foo.bar.MODULE_ID)
print(web.foo.bar.baz.MODULE_ID)
```

Interact with "Go to Definition" in editor.

## Expected behavior

module and variable could jump correctly.

## Actual behavior

- Only MODULE_ID in `web.foo.bar.baz.MODULE_ID` could jump.
- `web` module jump to `baz/__init__.py` file.
[Video Record](https://www.screencast.com/t/Wzyf7sH4Tt)

## Logs

None

**Comment by heejaechang** [comment]
this is by design. we do not import parent module automatically when you import submodule using import statement. see the dupped issue.
