### ISSUE TITLE
Syntax highlighting broken by method return type hint

### ISSUE THREAD

**Issue by alecglen** [microsoft/pylance-release#3443]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Using the Dark+ (default dark) theme, I expect Python keywords (`for`, `with`, `return`, `def`, etc.) to display as a magenta color. This is true throughout my IDE.
![image](https://user-images.githubusercontent.com/28493454/194436344-3e058a16-9995-4ae7-afd1-1d7d1127407f.png)

Except when I add a type hint to the method, I lose that portion of the highlighting through the function to the next method start.
![image](https://user-images.githubusercontent.com/28493454/194436431-8c058890-31e8-4545-99d3-5235d1806a23.png)

Details:
 - Other than `def`, it appears scoped to the function context (the generator inside `sorted` is unaffected).
 - It doesn't matter what the type hint is; a simple `int` still breaks it.
 - For some reason, wrapping the hint in parens avoids the issue.
   ![image](https://user-images.githubusercontent.com/28493454/194436515-3e70585a-296e-4bb6-b860-52ebd2099620.png)

## Steps to reproduce:

OS: Ubuntu 20.04.5 LTS

Open a class and add a type hint.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: ~/anaconda3/envs/betsy-nfl/bin/python
> /bin/python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
> /bin/python3 ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
> ~/anaconda3/bin/python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
> conda run -n betsy-nfl --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/printEnvVariables.py
> conda run -n betsy-nfl --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/printEnvVariables.py
> conda run -n betsy-nfl --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/printEnvVariables.py
> conda run -n betsy-nfl --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/printEnvVariables.py
> ~/anaconda3/envs/betsy-nfl/bin/python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
> ~/anaconda3/envs/betsy2/bin/python ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/interpreterInfo.py
Starting Pylance language server.
Jupyter provided interpreter path override: /home/alec/anaconda3/envs/betsy-nfl/bin/python
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.16.0
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:47.539Z)
OS version: Linux x64 5.15.0-43-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|31.09GB (22.38GB free)|
|Process Argv|--unity-launch --crash-reporter-id cfe16397-b991-4479-bd53-4bc43848e2f1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by EmpireJones** [comment]
I'm experiencing the same issue. This issue causes comments to be colored incorrectly too, which makes things a bit more difficult to read.
<img width="210" alt="image" src="https://user-images.githubusercontent.com/15959998/195715634-76d2a22f-2afd-4d2e-8a11-f01e3603b1d5.png">

**Comment by debonte** [comment]
@alecglen, @EmpireJones, can you provide sample files that repro this issue consistently? I retyped the code from both of your examples and didn't see any coloring issues.

**Comment by EmpireJones** [comment]
I tracked this down to having some old/deprecated "Python for VSCode" extension installed. Thanks!

**Comment by alecglen** [comment]
Hey hey, removing the old extension fixed it for me as well! Good catch @EmpireJones!

**Comment by debonte** [comment]
Oh, yes, your confusion is understandable. [Python for VSCode](https://marketplace.visualstudio.com/items?itemName=tht13.python) was not created by Microsoft and doesn't seem to be in active development anymore (last release was in 2016). Microsoft's python extension is just called [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python).

**Comment by h12sw06** [comment]
I'm using a temporary solution.

It's a way to create a meaningless def _(): pass.

def function() -> str:
   def _():
     pass

   return 'Hello World!'

or

def function() -> str:
   # def _():

   return 'Hello World!'

or 

def function() -> str:
   # ():

   return 'Hello World!'
