### ISSUE TITLE
pandas Series typing is confusing and raises a TypeError exception

### ISSUE THREAD

**Issue by Questionsdenombres** [microsoft/pylance-release#3445]
## Environment data
- Pylance: v2022.10.10
- pylint: 2.15.0
- pandas: 1.4.4
- Python: version(3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36)
- Visual studio: 1.72.00
- Windows-10-10.0.19042-SP0

## Code Snippet
```python
from pandas import DataFrame, Series

df: DataFrame = DataFrame({'A': [1,2,3], 'B': [3,4,5]})

row_a = df.loc[0]
print(f'row_a =\n{row_a}')

row_b: Series = df.loc[0]
print(f'row_b =\n{row_b}')

try:
    row_c: Series[int] = df.loc[0]
    print(f'row_c =\n{row_c}')
except Exception as exc:
    print(f'Exception({type(exc).__name__}): {exc}')

def my_func(_df: DataFrame) -> None:
    """ my_func """
    row_d: Series[int] = _df.loc[0]
    print(f'row_d =\n{row_d}')
    return

my_func(df)
```
## Actual behavior
1. On the one hand Pylance expects `Series` with an argument `Series[S1]` and reports that the type is partially unknown otherwise.
2. On the other hand pylint reports that the argument as unexpected: `Value Series is unsubscriptable`.
3. Line: `row_c: Series[int] = df.loc[0]` raises a run time exception: `TypeError: 'type' object is not subscriptable`.
    However the very same code line within the `my_func` function works correctly: `row_d: Series[int] = _df.loc[0]`

![Capture](https://user-images.githubusercontent.com/47284986/194651898-2ccc76f2-e619-4a34-a460-03570c0cb7a8.JPG)

## Expected behavior
- It is sensible that `'Series` has an argument.
- I used to trust Pylance and hide pylint messages (assumed false positive) 
  with `pylint: disable=unsubscriptable-object` until I got the `TypeError` exception.

- My investigation gives confusing results:

  - Pylance uses its own dedicated stubs located at
    `C:\Users\...\.vscode\extensions\ms-python.vscode-pylance-2022.10.10\dist\bundled\stubs\pandas\core\frame.pyi`
    where `Series`is defined as a Generic type with one argument.
    `class Series(IndexOpsMixin, NDFrame, Generic[S1]): ...`

  - pandas defines the class `Series` in file `...\Python310\Lib\site-packages\pandas\core\series.py`
    as `class Series(base.IndexOpsMixin, NDFrame): ...` with no argument.
    Note that this `series.py` module is typed: few lines later read:
```python
    @property
    def _constructor(self) -> Callable[..., Series]:
        return Series
```

  - class `Series` in pandas_stubs-1.5.0.221003 (last version from pypi)
    is consistent with pylance stubs: `class Series(IndexOpsMixin, NDFrame, Generic[S1]): ...`

Something's wrong, but I don't not what?
Tell me if I don't report the issue at the correct place.

Thank you for the pyright/pylance tool.
Patrick Bourdon - Paris

**Comment by debonte** [comment]
> Pylance uses its own dedicated stubs...

The pandas stubs included in Pylance are from https://github.com/pandas-dev/pandas-stubs. We generally update them weekly. You can see the version that we're currently bundling in `C:\Users\...\.vscode\extensions\ms-python.vscode-pylance-<ver>\dist\bundled\stubs\pandas\_version.pyi`.

> Something's wrong, but I don't not what?

The pandas-stubs authors have chosen to represent `Series` as generic [internally](https://github.com/pandas-dev/pandas-stubs/issues/269#issuecomment-1237297651), but as you've seen, `Series` is not really a generic class and treating it as such in your code will result in runtime errors.

The issue with `reportUnknownVariableType` and `Series` was discussed [here](https://github.com/microsoft/pyright/issues/3066).

Pylance is acting correctly here. You could report this as an issue in the pandas-stubs repo. Perhaps they hadn't considered the impact of making `Series` generic on Pyright/Pylance users with `typeCheckingMode` set to `strict`.

cc: @Dr-Irv

**Comment by Dr-Irv** [comment]
> You could report this as an issue in the pandas-stubs repo. Perhaps they hadn't considered the impact of making `Series` generic on Pyright/Pylance users with `typeCheckingMode` set to `strict`.

We are gradually making changes to the stubs to allow `strict` to work.

The generic declarations for `Series` are only used for type checking, so that we can return things like `Series[bool]`, which the type checker can then use when pandas expects a boolean `Series`.  But the runtime doesn't support the generic declarations.

Also, given a `DataFrame`, we can't track the underlying types of the various `Series` corresponding to each column of the `DataFrame`, so you will get the "partially unknown" messages.

You can do  `row_c = cast("Series[int]", df.loc[0])` so that the type checker knows the generic version of the type of `df.loc[0]`.  That will also work in runtime.

**Comment by aleksandar-adevinta** [comment]
Any news on this issue?

**Comment by debonte** [comment]
@aleksandar-adevinta, did you see the responses from me and Dr-Irv above? I didn't think there's anything left for the Pylance team to address here.
