### ISSUE TITLE
Ignored modules do not appear in quick fix

### ISSUE THREAD

**Issue by mehdigmira** [microsoft/pylance-release#3449]
## Environment data

-   Language Server version: Pylance language server 2022.10.10 (pyright 59bdc42e)
-   OS and version: MacOS 12.6 M1 Pro
-   Python version: Python 3.10

## Repro Steps

Setting a directory as ignored in pyright configuration, has the effect of disabling any auto-import (quickfix) to that directory

pyproject.toml

```
[tool.pyright]
pythonVersion = "3.10"
ignore = [
    "common/models"
]
```

models/model.py

```python
class Main:
    ...
```

test.py

```
Main # quick fix will not suggest auto-importing Main from models

```

## Expected behavior

Quick fix works as usual. Pyright documentation states
``` Paths of directories or files whose diagnostic output (errors and warnings) should be suppressed even if they are an included file or within the transitive closure of an included file```
I expect the directories to still be analyzed and used by qui-fix. I suppose that why pyright makes a difference between the exclude and ignore parameters.

This particularly important for me, since i use SQLAlchemy which today produces a large amount of errors when basic type checking is enabled. So I want to silence these errors, but still benefit from quickfix.

## Actual behavior

quickfix not working

## Logs

```
(895) Background analysis message: getDiagnosticsForRange
```

**Comment by yanjintao** [comment]
[国际化2022-10-05(1).docx](https://github.com/microsoft/pylance-release/files/9740815/2022-10-05.1.docx)
23232

**Comment by judej** [comment]
This is by design, when the folder is excluded, and we will not have the diagnostic and therefore the quickfix will not work.

**Comment by debonte** [comment]
@mehdigmira, this was a typo. @judej meant ignored not excluded. Fixes are for diagnostics. Since ignored files don't show diagnostics, there's nothing to fix and therefore the quick fix is not available.

**Comment by mehdigmira** [comment]
I see, I wan't aware this was the way fixes worked. But it makes sense. Thanks for the swift replies.
