### ISSUE TITLE
Use a custom directory <> module mapping for Python modules?

### ISSUE THREAD

**Issue by rzats** [microsoft/pylance-release#3454]
I have a project where Python files from multiple repositories are combined into a single Docker image and then restructured into a single Python package. Is there a way to make Visual Studio Code aware of this nonstandard structure to get code completion, analysis etc.? In other words, given an import like

```import A.B.module as module```
the IDE should look for `module` in path `X/Y` using some set `A.B` -> `X/Y` mapping.

Alternatively, it could internally treat `import A.B.module as module` like `import module as module` (ignoring the `A.B.`), which could be used in combination with [python.autoComplete.extraPaths](https://code.visualstudio.com/docs/python/editing#_enable-intellisense-for-custom-package-locations) to pick up on the missing imports.

https://github.com/microsoft/pylance-release/issues/1948 is a similar issue, but doesn't look like it has gone anywhere.

**Comment by erictraut** [comment]
Pylance is built on top of Microsoft's open-source type checker called pyright. Pyright supports a way to configure multiple "execution environments" within your project. For full details refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md). Within each execution environment, you can specify a different root directory, Python version, Python platform, and additional import resolution paths (extraPaths). I think this may address your needs.

**Comment by rzats** [comment]
Looks like that tool lets you define multiple import resolution paths, which is very helpful, but it doesn't quite help with the import resolution issue I'm facing.

For reference (this is essentially the same issue as https://github.com/microsoft/pylance-release/issues/1948), I'm working with several GitHub repos structured like so
```
repo1
  src
    file1.py
    file2.py
    ...
repo2
  src
    file3.py
    ...
```
which are merged into a single Docker container / Python package at runtime:
```
package
  repo1
    file1.py
    file2.py
    ...
  repo2
    file3.py
    ...
```
All first-party imports are absolute - `import package.repo1.file1`. This works at runtime, but isn't recognized by the IDE, since it doesn't match the compile-time code structure.

By adding several root directories using Pylance's `extraPaths`, multiple execution environments etc., I can get relative imports like `import file1` working, but still not absolute ones like `import package.repo1.file1`.

It's also possible to clone multiple repos into a single directory and mimic the structure of the package like so:
```
[VSCode root directory]
  package
    repo1
      src
        file1.py
        file2.py
        ...
    repo2
      src
        file3.py
        ...
```
But this only enables imports like `import package.repo1.src.file1`- almost, but _not quite_ `import package.repo1.file1`. My question is whether it's possible to get this kind of import working via IDE config without reworking the code layout.

**Comment by erictraut** [comment]
You're correct — execution environments won't work for you unless you change the layout of your repo.

Your needs are similar to those of a library author who is working on code that is intended to be installed in `site-packages` and executed from that context. The standard way to handle that is through the use of an "editable install". You would need to create a setup.py that describes how your final package is laid out. Then members of your development team would simply do a one-time `pip install -e <local package name>`. This would create a `<package>` directory in your site-packages folder. Within that `<package>` directory will be ".pth" files that are symbolic links that point back to your project source. This effectively creates the final on-disk structure and allows static analysis tools like pylance, mypy, pylint, etc. to resolve imports as they will be resolved at the time the code is executed.
