### ISSUE TITLE
Lines in docstrings starting with # displayed as headings in hover popup

### ISSUE THREAD

**Issue by pgorczak** [microsoft/pylance-release#3457]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: lines starting with # in docstrings e.g. for including comments in code examples render as regular lines of text

Actual: lines starting with # are rendered as headings

## Steps to reproduce:

1. write this example function

```python
def spam():
    """Lorem ipsum dolor sit amet
    
    consectetur adipiscing elit
    
    # sed do eiusmod tempor incididunt
    
    Example:

        ut labore et dolore magna aliqua
        # Ut enim ad minim veniam
        quis nostrud exercitation ullamco

    laboris nisi ut aliquip ex ea commodo consequat
    """
    return None
```

2. hover on the function name

<img width="458" alt="Screen Shot 2022-10-10 at 12 27 48" src="https://user-images.githubusercontent.com/1765698/194846359-212d6168-b05f-49fe-89cd-1ecf2b3e3890.png">

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): PipEnv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

(no output)

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.14.0
VS Code version: Code 1.72.0 (Universal) (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

**Comment by rchiodo** [comment]
This is actually on purpose. Doc comments are formatted as markdown in VS code.

You can work around this by explicitly indicating something is code:

```python
def spam():
    """Lorem ipsum dolor sit amet
    
    consectetur adipiscing elit
    
    # sed do eiusmod tempor incididunt
    
    Example:
        ut labore et dolore magna aliqua

    ```python
    	# Ut enim ad minim veniam
    	def func
    ```
        
        quis nostrud exercitation ullamco

    laboris nisi ut aliquip ex ea commodo consequat
    """
    return None
```

That should generate the following output:

![image](https://user-images.githubusercontent.com/19672699/197642375-e730592d-8634-45ce-9afa-df1e71b5773f.png)

The '```python' has to be at the same indentation as the rest of the docstring though for it to work.

This won't work:

```python
def spam():
    """Lorem ipsum dolor sit amet
    
    consectetur adipiscing elit
    
    # sed do eiusmod tempor incididunt
    
    Example:
        ut labore et dolore magna aliqua

        ```python
    	# Ut enim ad minim veniam
    	def func
        ```
        
        quis nostrud exercitation ullamco

    laboris nisi ut aliquip ex ea commodo consequat
    """
    return None
```
