### ISSUE TITLE
Support for doccer-style docstring expansion

### ISSUE THREAD

**Issue by hoechenberger** [microsoft/pylance-release#346]
Hello! I've come across some situations where I don't get the expected docstrings in packages that, it seems, are using SciPy's [doccer](https://github.com/scipy/scipy/blob/master/scipy/_lib/doccer.py) (or derived / similar tools) to reduce docstring redundancy. Essentially, doccer allows re-using of (parts of) existing docstrings, so one doesn't have to copy & paste recurring sections to different functions, and can keep a single "source of truth".

For example, the docstring of [`mne. compute_proj_raw`](https://mne.tools/stable/generated/mne.compute_proj_raw.html) looks something like this (omissions by me are indicated by an ellipsis):

```python
@verbose
def compute_proj_raw(raw, start=0, stop=None, duration=1, n_grad=2, n_mag=2,
                     n_eeg=0, reject=None, flat=None, n_jobs=1, meg='separate',
                     verbose=None):
    """Compute SSP (spatial space projection) vectors on Raw.

    Parameters
    ----------
    raw : instance of Raw
        A raw object to use the data from.
    ...
    %(n_jobs)s
        Number of jobs to use to compute covariance.
    ...
    %(verbose)s

    Returns
    -------
    projs: list
        List of projection vectors.

    See Also
    --------
    compute_proj_epochs, compute_proj_evoked
    """
```

[`n_jobs`](https://github.com/mne-tools/mne-python/blob/039e712156066d5a4d2a10b5d8797f7b72614dce/mne/utils/docs.py#L549-L553
) and [`verbose`](https://github.com/mne-tools/mne-python/blob/039e712156066d5a4d2a10b5d8797f7b72614dce/mne/utils/docs.py#L25-L29
) are defined in a central "documentation dictionary". When Sphinx builds the documentation, these placeholders are expanded.

To my surprise, the Python as well as the IPython REPL seem to be aware of this, and display the **expanded** docstrings when calling `help(mne.compute_proj_raw)`:

<img width="1157" alt="Screenshot 2020-09-09 at 10 28 06" src="https://user-images.githubusercontent.com/2046265/92576745-2944ba00-f28a-11ea-9d2a-5227ad504700.png">

In VS Code with Pylance, I receive the non-expanded docstrings, which are not really helpful:
<img width="1136" alt="Screenshot 2020-09-09 at 10 29 26" src="https://user-images.githubusercontent.com/2046265/92576885-52654a80-f28a-11ea-80ca-5736514188cf.png">

Now I did a little bit of research, but couldn't really figure out just **how** Python and IPython generate the correct docstrings on the fly; but obviously it **is** possible somehow.

This is a feature I would very, very much like to see in Pylance as well. The current limitation extends beyond the [MNE package ](https://mne.tools/stable/index.html) I used in my example, and is likely to affect other scientific software packages as well, including SciPy.

**Comment by hoechenberger** [comment]
Here, for completeness, is an example straight from a central SciPy function, namely [`ndimage.filters.correlate1d`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.correlate1d.html)

Function signature & docstring:
```
@_ni_docstrings.docfiller
def correlate1d(input, weights, axis=-1, output=None, mode="reflect",
                cval=0.0, origin=0):
    """Calculate a 1-D correlation along the given axis.
    The lines of the array along the given axis are correlated with the
    given weights.
    Parameters
    ----------
    %(input)s
    weights : array
        1-D sequence of numbers.
    %(axis)s
    %(output)s
    %(mode)s
    %(cval)s
    %(origin)s
    Examples
    --------
    >>> from scipy.ndimage import correlate1d
    >>> correlate1d([2, 8, 0, 4, 1, 9, 9, 0], weights=[1, 3])
    array([ 8, 26,  8, 12,  7, 28, 36,  9])
    """
```

### (truncated) output of `help(scipy.ndimage.filters.correlate1d)` on the Python 3.8 REPL
<img width="947" alt="Screenshot 2020-09-09 at 22 56 12" src="https://user-images.githubusercontent.com/2046265/92654147-b4a46680-f2ef-11ea-9cb9-e448c3c795ff.png">

### Pylance in VS Code
<img width="943" alt="Screenshot 2020-09-09 at 22 50 18" src="https://user-images.githubusercontent.com/2046265/92653990-71e28e80-f2ef-11ea-8ed3-a41062c47663.png">

**Comment by nkukard** [comment]
Even without expansion this displays incorrectly....
```
    def add(self, item: SectionConfigItem, order: int = 10, deferred: bool = False, debug: bool = False) -> None:
        """
        Add configuration to the output we're going to generate.

        Parameters
        ----------
        item : SectionConfigItem
            Configuration to add, either a string, list of strings or another section.

        order : int
            Ordering of the item to add. Defaults to `10`.

        deferred : bool
            If the config item is a SectionBase, then rendering can be deferred until after configuration.
            This is needed for instance for the constants section, which other protocols may add to.

        debug : bool
            The configuration provided should only be output when we are in debug mode.

        """
```

**Pylance in VS Code...**

![Screenshot_20200911_123621](https://user-images.githubusercontent.com/2354782/92926454-8e83e100-f42b-11ea-913f-d2b6d1d3f99d.png)

**Comment by hoechenberger** [comment]
@nkukard
> Even without expansion this displays incorrectly....

Could be nicer, but I think it's a different issue – one of general docstring rendering :)

**Comment by bschnurr** [comment]
Newest improvements to docstrings about to be released.

![image](https://user-images.githubusercontent.com/1946977/106811744-a1d65980-6623-11eb-8bea-cc8fafc20c39.png)

**Comment by jakebailey** [comment]
For reference, though, we didn't add this "expansion" that would normally happen at runtime. Not sure that we ever will given the non-static nature of these types of docstrings, but we can at least not print these indented regions poorly.

**Comment by hoechenberger** [comment]
@jakebailey Thank you! Docstrings render much nicer now, great job!

I totally understand your argument regarding Pylance being a **static** type checker.

However, since these doccer expansions are used in a few important scientific packages (like SciPy), I'm afraid quite a bunch of users are affected by this. Maybe it's worth considering special-casing these types of docstrings? All that would need to be executed is the Python file defining the "doc dict", containing the strings to insert into the docstrings. This only needs to be read once, and the respective docstrings can be compiled either immediately or on-demand (at runtime), as string replacements should be super fast. 🙂

**Comment by cbrnr** [comment]
I'm not sure this is the same issue, but at least for MNE-Python I get very strange docstrings when hovering over a method (in the example, I'm using `mne.time_frequency.tfr_multitaper` [source](https://github.com/mne-tools/mne-python/blob/main/mne/time_frequency/tfr.py#L813)).

Here's the output when using Pylance:
<img width="611" alt="pylance" src="https://user-images.githubusercontent.com/4377312/107647761-ce215400-6c7b-11eb-992e-52845a94665e.png">

And here's the (correct) output when using Jedi:
<img width="1001" alt="jedi" src="https://user-images.githubusercontent.com/4377312/107647797-d7122580-6c7b-11eb-8137-6c80e2d2cbb5.png">

**Comment by hoechenberger** [comment]
@cbrnr This is something else, related to the `@verbose` decorator used in MNE-Python. Care to open a separate issue for this one?

**Comment by cbrnr** [comment]
Are we sure it's not our fault? The `verbose` function doesn't use the `functools.wraps` decorator, although it seems like we're using `decorator.FunctionMaker` instead, which should do the same thing. I currently don't have time, I'll just switch back to Jedi and/or PyCharm. I just commented in case this was the same issue. But feel free to create a new issue if you can reproduce this and if it's not our fault.

**Comment by bschnurr** [comment]
see point 3 in https://github.com/microsoft/pyright/blob/master/docs/type-stubs.md#cleaning-up-generated-type-stubs for tips on how to add types to decorators.

**Comment by hoechenberger** [comment]
Thank you, @bschnurr, I will try this

**Comment by hoechenberger** [comment]
Hello again, and sorry for bumping this once more. But I'd like to once again bring to your attention that the lack of this feature is a real usability issue for numerous scientific / data science developers and users:

@hoechenberger
> However, since these doccer expansions are used in a few important scientific packages (like SciPy), I'm afraid quite a bunch of users are affected by this. Maybe it's worth considering special-casing these types of docstrings? All that would need to be executed is the Python file defining the "doc dict", containing the strings to insert into the docstrings. This only needs to be read once, and the respective docstrings can be compiled either immediately or on-demand (at runtime), as string replacements should be super fast. 🙂

If this is not possible, do you have any recommendations as to what could be done on the side of the affected software projects to provide a better experience for Pylance users? While I know, for example, that type stubs can be a solution for libraries that do not yet use type annotations, could we provide something like "documentation stubs" that contain the expanded docstrings? The affected projects could do the expansion themselves and Pycharm would just need to gather these strings. WDYT?

**Comment by jakebailey** [comment]
I'm not sure about "documentation stubs" (that requires greater thought, especially as the python ecosystem moves to inlining types as a single source of truth), but I do know that if regular type stubs are present and contain docs, we will use them and not try and analyze the real code.

**Comment by hoechenberger** [comment]
> , but I do know that if regular type stubs are present and contain docs, we will use them and not try and analyze the real code.

Perfect, this could be something I could use, then. I will look into this.

**Comment by jakebailey** [comment]
Just note that type stubs effectively replace the source files in the eyes of the analysis, so if you add stubs, they should have all of the types filled out (as we're not going to go analyze the real code for anything).

**Comment by hoechenberger** [comment]
Hello @judej,

This is still topical and nothing has changed about this. Could you please reopen? This is still a big problem for those who use SciPy and certain other scientific tools. Thank you!

**Comment by hoechenberger** [comment]
Thanks @judej!

**Comment by bschnurr** [comment]
one way to fix this would be to fixup stubs here https://github.com/microsoft/python-type-stubs/tree/main/scipy-stubs

**Comment by hoechenberger** [comment]
Yes, I'd be thinking about this too 🤔

**Comment by bschnurr** [comment]
Closing for now... maybe there is something we can do with sphinx html generated docstrings
