### ISSUE TITLE
Pylance causes Renaming to Format file

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/pylance-release#3461]
Enabling Pylance causes the following error:
I try to rename a variable with F2 (or by submenu), Pylance causes to reformat the file, by inserting a new empty line after each original line.

No idea what's the relation.
I tried to empty my user json config file, but didn't help.
When I disable Pylance it instantly solves the issue.

![2022-10-10_211208_27](https://user-images.githubusercontent.com/4163396/194944869-85e262df-b243-48c8-83b2-706ad5fa134c.jpg)

## Environment data

-   Language Server version: Pylance v2022.10.10
-   OS and version: win7/ also win10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.8
- ## Code Snippet

```python
XXX
```

## Repro Steps

1. Try to rename a variable

## Expected behavior
Varible should be renamed

## Actual behavior
Variable renamed, but .py file gets formated (see above)

## Logs
nothing shows up in output. (I don't try to run my script)

**Comment by bschnurr** [comment]
can't repo.
after hitting f2 there is a why to preview the change.. `shift+enter`


![Image](https://user-images.githubusercontent.com/1946977/195458878-9b7267d0-bcb3-496d-bea0-64403d17ecc2.png)


if your preview includes additional lines then it would be pylance

**Comment by heejaechang** [comment]
could you provide us some repro steps we can follow or sample project we can use to live repro the issue? otherwise, it would be hard for us to figure out what went wrong.

**Comment by bschnurr** [comment]
> Although after saving the formatting it doesn't replace line endings, so no idea why is it touching them.
> 
> ![2022-10-14 09_36_57-speed py C__sandboxes_speed_mapping - Notepad2-mod (Administrator)](https://user-images.githubusercontent.com/4163396/195802279-e41c008c-f1fa-4444-bf7d-765342ae1858.jpg)
> 
> ![22022-10-14 09_37_13-speed py C__sandboxes_speed_mapping - Notepad2-mod (Administrator)](https://user-images.githubusercontent.com/4163396/195802337-d6e43518-fd7f-45de-902b-e416e3158c44.jpg)

how did you get VSCode to display the carriage return and line feed?

**Comment by bschnurr** [comment]
can you upload your formatted file?

**Comment by bschnurr** [comment]
I still can't seem to repo this. My only suggestion is to disable/uninstall all other extensions except python and pylance and try again to see if its still happening.
