### ISSUE TITLE
When I try to clone or replicate the project I can't run with existing modules

### ISSUE THREAD

**Issue by Nethajioslo** [microsoft/pylance-release#3462]
Try to add the modules which are required for smooth functioning of the project it's very important to have all the modules . So then only execution becomes easier and Smooth.

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
