### ISSUE TITLE
option to exclude some auto-import options

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/pylance-release#3466]
Can we have the option to exclude some auto-import options?
- some auto-import options will possibly never make sense to me, e.g.  (an arbitrary example) `adm` -> `from msilib.schema import AdminExecuteSequence`
- Hope there is an ignore list setting, e.g. adding `msilib` to that list will eliminate all auto-import options from `msilib`.

ref
- similar request on reddit: https://www.reddit.com/r/vscode/comments/tlcuwg/remove_auto_import/

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023111-4-January-2023-PreRelease)
