### ISSUE TITLE
Allow ignoring words in import quick fixes

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#347]
Pylance now features adding imports. But for instance when working on a Python 2.7 project it highlights `unicode` and offers A WHOLE PAGE of imports from who knows where.
I'd like a Quick Fix like "Ignore 'unicode'" or "Add 'unicode' to keywords" ...
How would sth like that be implemented? Where would I start?

**Comment by erictraut** [comment]
Pylance is specifically written for Python 3. We have no plans to add support for Python 2.x, nor would we accept code contributions to that effect. If you want to work with Python 2.x, the Jedi language server is a good option.

**Comment by savannahostrowski** [comment]
This issue has been open for a long while and we haven't received enough upvotes to prioritize this work. Additionally, we will not be adding 2.7 support.
