### ISSUE TITLE
Managing autocompletion of cython generated modules (JSBSim)

### ISSUE THREAD

**Issue by Dobid** [microsoft/pylance-release#3471]
Hello, question from a newbie there. 
I'm working with a simulation module called [JSBSim](https://github.com/JSBSim-Team/jsbsim) and Pylance autocompletion does not work. After reading some of the issues around here, I found that Pylance does not manage cython generated modules (which JSBSim is, that's what I understood). In fact there's only a *.so file in the site-package/ directory. 
What do I have to do to make vscode/pylance work with this module ? Should I expect a new feature from Pylance to manage this kind of modules (like Pycharm does) ? Or should I ask for JSBSim maintainers to generate .pyi stubs (I think that's what Pylance needs to make autocompletion work for cython compiled modules), or maybe I could generate them myself ?
Thanks in advance !

**Comment by bschnurr** [comment]
Yes JSBSim will require stubs

**Comment by Dobid** [comment]
Alright, so... is this something to do for pylance ? JSBSim team ? Me ? Who would be more suited to fix this problem ?

**Comment by erictraut** [comment]
Type information should be provided by the maintainer of the library. If they unwilling to include type information but are willing to accept a contribution (in the form of a PR), you could create type stubs and contribute them back for the benefit of other users of the library. For more information about distributing type information with a library, refer to [PEP 561](https://peps.python.org/pep-0561/).

If they're unwilling to accept a contribution, you could consider adding type stubs to the [typeshed](https://github.com/python/typeshed) project. This would take the form of a separate "stub package" that needs to be installed separately from the main library.

**Comment by Dobid** [comment]
Ok, seems clear to me, thank you !
