### ISSUE TITLE
Incorrect typing warning when subtracting numpy arrays

### ISSUE THREAD

**Issue by ortk95** [microsoft/pylance-release#3475]
## Environment data

-   Language Server version: v2022.10.20
-   OS and version: Mac OS 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:43:32) [Clang 12.0.1 ]

## Code Snippet

```python
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

a = x - y # Operator "-" not supported for types "ndarray[Unknown, Unknown]" and "ndarray[Unknown, Unknown]"

# These are fine:
b = x + y
c = x * y
d = x / y
```

## Expected behavior

Subtracting numpy arrays is allowed, so there should not be a typing error.

## Actual behavior

Get typing error when trying to subtract numpy arrays.

## Relevant issues
See also https://github.com/numpy/numpy/issues/22437

**Comment by erictraut** [comment]
This is a known issue with recent versions of numpy. It's due to an overload for `__sub__` in the `ndarray` class:
```python
    @overload
    def __sub__(self: NDArray[bool_], other: _ArrayLikeBool_co) -> NoReturn: ...
```

It has already been addressed in the main branch of numpy, and the fix will appear in the next published release of that library.
