### ISSUE TITLE
Help forcing pylance to recognize import paths?

### ISSUE THREAD

**Issue by DocIsenberg** [microsoft/pylance-release#3477]
Hi! I'm using a external dependency (airflow) with a non-standard `__init__.py` that's throwing the static checker for a loop. I'd appreciate advice on getting pylance to actually recognize these modules.

Problem (my team's code): 
<img width="443" alt="Screen Shot 2022-10-14 at 5 27 12 PM" src="https://user-images.githubusercontent.com/2624762/195960614-fe8263e1-db57-46c3-b87f-03b71b348795.png">

`airflow.models` works just fine, but `airflow.operators.dummy_operator` etc. are hit with "Could not be resolved." And yet, in the same venv: 

<img width="1277" alt="Screen Shot 2022-10-14 at 5 55 25 PM" src="https://user-images.githubusercontent.com/2624762/195961799-f40ac85d-4eed-4607-bf56-3827812a2714.png">

Let's take a look at airflow's source:
```
# airflow/operators/__init__.py
# License truncated

from __future__ import annotations

from airflow.utils.deprecation_tools import add_deprecated_classes

__deprecated_classes = {
    'bash_operator': {
        'BashOperator': 'airflow.operators.bash.BashOperator',
    },

    ...

    'dummy_operator': {
        'EmptyOperator': 'airflow.operators.empty.EmptyOperator',
        'DummyOperator': 'airflow.operators.empty.EmptyOperator',
    },

    ...

    'python_operator': {
        'BranchPythonOperator': 'airflow.operators.python.BranchPythonOperator',
        'PythonOperator': 'airflow.operators.python.PythonOperator',
        'PythonVirtualenvOperator': 'airflow.operators.python.PythonVirtualenvOperator',
        'ShortCircuitOperator': 'airflow.operators.python.ShortCircuitOperator',
    },

    ...
}

```

```
# airflow/utils/deprecation_tools.py
# License truncated


from __future__ import annotations

import functools
import importlib
import sys
import warnings
from types import ModuleType


def getattr_with_deprecation(imports: dict[str, str], module: str, name: str):
    target_class_full_name = imports.get(name)
    if not target_class_full_name:
        raise AttributeError(f"The module `{module!r}` has no attribute `{name!r}`")
    warnings.warn(
        f"The `{module}.{name}` class is deprecated. Please use `{target_class_full_name!r}`.",
        DeprecationWarning,
        stacklevel=2,
    )
    new_module, new_class_name = target_class_full_name.rsplit('.', 1)
    return getattr(importlib.import_module(new_module), new_class_name)


def add_deprecated_classes(module_imports: dict[str, dict[str, str]], package: str):
    for module_name, imports in module_imports.items():
        full_module_name = f"{package}.{module_name}"
        module_type = ModuleType(full_module_name)
        # Mypy is not able to derive the right function signature https://github.com/python/mypy/issues/2427
        module_type.__getattr__ = functools.partial(  # type: ignore[assignment]
            getattr_with_deprecation, imports, full_module_name
        )
        sys.modules.setdefault(full_module_name, module_type)
```

I don't know much about static analysis, but I doubt this fits the bill. **Do y'all have any recommendations on getting/forcing pylance to map these import paths to modules/classes?**

I'm looking to just resolve this issue locally for the sake of editing, and I'm happy to make unpleasant local changes to `airflow` itself such as modifying or adding to the __init__.py in question. Specifying extra paths to pylance probably won't help here- the problem as I see it is the import paths aren't equivalent to file/module names, e.g. `airflow.operators.dummy_operator.DummyOperator` -> `airflow.operators.empty.EmptyOperator`. Changing imports in my own source is out of the question at the moment- I don't think my team would prioritize that.

Python v 3.8.12
`apache-airflow==2.4.1`

**Comment by erictraut** [comment]
If you can avoid using deprecated symbols, that's preferable.

If you can't avoid it, your options are limited if you want to use these classes with static analysis tools. You could create your own type stub files that describe the symbols you're using in your program. Or you can use a `# type: ignore` comment to suppress the individual warnings, but you won't get any completion suggestions in that case.

If you're willing to locally hack your copy of airflow code files, you can manually add import statements to `airflow/operators/__init__.py`. For example:

```python
from airflow.operators.bash import BashOperator as BashOperator

from airflow.operators.empty import EmptyOperator
DummyOperator = EmptyOperator
```

In the first example, I used a redundant form of import (`BashOperator as BashOperator`) because this is a py.typed library, and the redundant form is required to indicate that the symbols is intended to be re-exported.

In the second example, I used a simple assignment to re-export a symbol (`EmptyOperator`) under a different name `DummyOperator`).

**Comment by DocIsenberg** [comment]
For anyone coming across this issue in the future, for Airflow or other creative `__init__.py` examples, there's apparently a `TYPE_CHECKING` variable in the base Python libs helps immensely. I resolved this by creating a `python_operator.py` module that looked like the following:

```python3
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from airflow.operators.python import BranchPythonOperator as BranchPythonOperator
    from airflow.operators.python import PythonOperator as PythonOperator
```
