### ISSUE TITLE
Incorrect 'No overloads for "apply" match the provided arguments' on the pandas apply function

### ISSUE THREAD

**Issue by jonmooser** [microsoft/pylance-release#3491]
Incorrect `No overloads for "apply" match the provided arguments` on the pandas apply function

The problem seems caused by the "args" argument. But only in some cases. See the two nearly identical lines in the snippit below. 

This may be similar to #2547, but sees different enough to warrant a new issue 

## Environment data

-   Language Server version: v2022.10.20
-   OS and version: mac os Monterey 12.3.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   pandas==1.5.0
-   numpy==1.23.2

## Code Snippet
```python
import pandas as pd

def gethead(s, y):
    return s.head(y)

df = pd.DataFrame({"A": [1, 2, 3, 4, 5, 6], "B": [11, 12, 13, 14, 15, 16]})

df2 = df.apply(gethead,  args=tuple([4]))
df3 = df.apply(gethead, axis=0, args=tuple([4]))

print(df2)
print(df3)
```

## Repro Steps

1. Open the code above in VS Code
2. Run it to confirm that the code works

## Expected behavior 

There should be no warnings / errors

## Actual behavior

Error: 
No overloads for "apply" match the provided arguments
  Argument types: ((s: Unknown, y: Unknown) -> Unknown, list[int])Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)

This happens on the first call to df.apply *but not the second*
The only difference is that one of the optional parameters to df.apply is explicitly included in the second case. 

Note that when you run the code, both lines produce identical output as expected. 
## Logs

Log output attached

[pylance_output.txt](https://github.com/microsoft/pylance-release/files/9804956/pylance_output.txt)

**Comment by bschnurr** [comment]
there are 2 overloads on `apply`, try right click Got declaration to see them.
 
see https://github.com/microsoft/pylance-release/issues/3029#issuecomment-1182029725

**Comment by bschnurr** [comment]
if you think your code example is correct please create an issue in the pandas stub repo. https://github.com/pandas-dev/pandas-stubs/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by debonte** [comment]
Specifically I think the problem is that the second `overload` of `apply` doesn't have a default value for the `axis` parameter:

```python
    @overload
    def apply(self, f: Callable) -> Series: ...
    @overload
    def apply(
        self,
        f: Callable,
        axis: AxisType,
        raw: _bool = ...,
        result_type: _str | None = ...,
        args=...,
        **kwargs,
    ) -> DataFrame: ...
```

but the implementation does:

```python
    def apply(
        self,
        func: AggFuncType,
        axis: Axis = 0,
        raw: bool = False,
        result_type=None,
        args=(),
        **kwargs,
    ):
```

So that `overload` should be:

```python
    @overload
    def apply(
        self,
        f: Callable,
        axis: AxisType = ...,
        raw: _bool = ...,
        result_type: _str | None = ...,
        args=...,
        **kwargs,
    ) -> DataFrame: ...
```

The error goes away after I make that change (add ` = ...`) in frame.pyi.

**Comment by debonte** [comment]
Pyright complains about the fix I proposed: `Overload 1 for "apply" overlaps overload 2 and returns an incompatible type`. Basically once `axis` has a default value, there's no way to tell which overload should be used and therefore which return type should be inferred.

So I opened a bug here and tagged you @jonmooser: https://github.com/pandas-dev/pandas-stubs/issues/393
