### ISSUE TITLE
There is no code completion for the gmpy2 library

### ISSUE THREAD

**Issue by Byxs20** [microsoft/pylance-release#3495]
Hello,
I have a question:
Version gmpy2 This library has no code completion

System: windows11
python version: 3.8.8
gmpy2 version: 2.1.2

As shown in figure:
![9-08-04](https://user-images.githubusercontent.com/64669718/196414113-389dd86d-2e10-47cf-a75f-713ab23e4317.png)

**Comment by debonte** [comment]
`gmpy2` is implemented using cython and therefore would need to provide [type stubs](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#inlined-type-annotations-and-type-stubs) for Pylance to understand what types, functions, etc it exposes.

Type information should be provided by the maintainer of the library. If they unwilling to include type information but are willing to accept a contribution (in the form of a PR), you could create type stubs and contribute them back for the benefit of other users of the library. For more information about distributing type information with a library, refer to [PEP 561](https://peps.python.org/pep-0561/).

If they're unwilling to accept a contribution, you could consider adding type stubs to the [typeshed](https://github.com/python/typeshed) project. This would take the form of a separate "stub package" that needs to be installed separately from the main library.
