### ISSUE TITLE
Disallow disabling "remove unused imports" on a folder/path basis

### ISSUE THREAD

**Issue by ramarivera** [microsoft/pylance-release#3496]
Basically, I would love to configure VS code so that imports within `__ini__.py` files are not removed.

**Comment by luabud** [comment]
Thanks for the suggestion, we're thinking we should probably disable removing all unused imports of the form `import foo as foo`.

**Comment by rchiodo** [comment]
import point:

- This applies to `import x as x` but not `import x as y`. `import x as x` is probably an export.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2022.10.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221041-26-October-2022-PreRelease)

**Comment by heejaechang** [comment]
wrongly closed. this fix will be included in next release, not today release.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2022.10.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221041-26-October-2022-PreRelease)

**Comment by heejaechang** [comment]
closed again. it is fixed in this release. sorry for the confusion.

**Comment by ramarivera** [comment]
Hi!
Could you please point out which point of the changelog corresponds to this issue?

**Comment by rchiodo** [comment]
It's not listed in the changelog as it wasn't really a bug. But if you have `import x as x` anywhere in a file now, it won't be marked as unresolved.

**Comment by ramarivera** [comment]
> It's not listed in the changelog as it wasn't really a bug. But if you have `import x as x` anywhere in a file now, it won't be marked as unresolved.

oh, okay. I missed that.
Then, in order to use the auto remove setting with `__init__.py` files, I should do imports in the form `import x as x` instead of `from x import x` ? Would that work also if I want to just import a subset of all the symbols in the current module?
Maybe I am writing my init files wrong, so any help is welcomed :)

**Comment by rchiodo** [comment]
I wouldn't say there's a wrong way to write your init files, but the pattern we're ignoring is something like so:

```
from .foo import bar as bar
```

Or anything that is specified in the `__all__` list: 
https://peps.python.org/pep-0008/#public-and-internal-interfaces

```
from .foo import bar 
__all__=['bar']
```

**Comment by ramarivera** [comment]
> I wouldn't say there's a wrong way to write your init files, but the pattern we're ignoring is something like so:
> 
> ```
> from .foo import bar as bar
> ```
> 
> Or anything that is specified in the `__all__` list: https://peps.python.org/pep-0008/#public-and-internal-interfaces
> 
> ```
> from .foo import bar 
> __all__=['bar']
> ```

Oh that's useful indeed. Thank you!
