### ISSUE TITLE
Bug template url gives 404 message

### ISSUE THREAD

**Issue by Boon-in-Oz** [microsoft/pylance-release#3497]
Using Windows 10 and Chrome, in the template for creating a new bug, the link to the guidelines

> https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md%23filing-an-issue

Takes me to a 404 error with the message

> The 'microsoft/pylance-release' repository doesn't contain the 'TROUBLESHOOTING.md#filing-an-issue' path in 'main'.

**Comment by debonte** [comment]
Thanks. Are you getting to the bug template via the "Pylance: Report Issue..." command in VS Code? I was able to repro the issue that way, but just wanted to confirm that's the scenario you're talking about.

**Comment by Boon-in-Oz** [comment]
Yes I get it that way . I also get it when I click "New Issue" on (eg) this page, and then "Get Started" next to "Bug Report".

**Comment by debonte** [comment]
> I also get it when I click "New Issue" on (eg) this page, and then "Get Started" next to "Bug Report".

Really? You don't see `https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#filing-an-issue` with `#` instead of `%23` in that case?

**Comment by Boon-in-Oz** [comment]
> > I also get it when I click "New Issue" on (eg) this page, and then "Get Started" next to "Bug Report".
> 
> Really? You don't see `https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#filing-an-issue` with `#` instead of `%23` in that case?
No. I see
https://github.com/microsoft/pylance-release/issues/new?assignees=&labels=&template=bug-report.md&title=
![image](https://user-images.githubusercontent.com/50002053/197062925-0b1a4fb5-1d81-4b71-87ae-a661b696bd87.png)

**Comment by debonte** [comment]
Sorry, I meant the URL in the bug report template:

![image](https://user-images.githubusercontent.com/12820898/197070241-b90c6583-12c1-47ca-b5f1-f29d4a3b7a92.png)

**Comment by Boon-in-Oz** [comment]
Ah I understand. Sorry, yes, you're correct. When I click on "Bug Report" in the web page, the text has the hash symbol.

I'm confused by that, because the first time this happened to me, I definitely used the web page as I wasn't aware of the "Report an issue" command in VS Code. I'll keep looking for a repro using the web page, but I guess this still serves as a bug report for the "Report Issue" version.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221141-30-November-2022-PreRelease)
