### ISSUE TITLE
Collapse code arrow disappears after file is loaded

### ISSUE THREAD

**Issue by FaresFilms** [microsoft/pylance-release#3505]
Writing any new code, that will require a collapse arrow (like an if statement), doesn't show the arrow. Even after reloading the file and VSCode. Opening the file after closing VSCode shows the arrows temporarily, until the file fully loads, then the arrows disappear. I've tried to uninstall the extension, which after reloading had the issue fixed. Keep in mind it was fixed when the extension wasn't enabled. After enabling it, the issues came back

**Comment by debonte** [comment]
Are you using Pylance as your Python language server? What is `python.languageServer` set to?

**Comment by debonte** [comment]
Related to https://github.com/microsoft/pylance-release/issues/3487?

**Comment by FaresFilms** [comment]
> Are you using Pylance as your Python language server? What is `python.languageServer` set to?

How do I check that?

**Comment by FaresFilms** [comment]
> Are you using Pylance as your Python language server? What is `python.languageServer` set to?

How would I check that?

**Comment by debonte** [comment]
1. Press "Ctrl+Comma" to bring up the settings UI in a new tab.
2. Type `python.languageServer` in the search box at the top of the Settings UI.
3. You should see something like this. And I'm wondering if it's set to Pylance or something else.

![image](https://user-images.githubusercontent.com/12820898/196777001-b6e9680c-005d-4c74-94a8-682dc3f3deec.png)

**Comment by FaresFilms** [comment]
![image](https://user-images.githubusercontent.com/69481149/196779009-dd0c9bc7-e64c-4f4b-bbcf-031b89ce00df.png)
It says "default"

**Comment by FaresFilms** [comment]
Switching to Pylance did seem to fix the issue and a multitude of other issues I didn't even know I had

**Comment by debonte** [comment]
> Switching to Pylance did seem to fix the issue

Did you need to install the Pylance extension? If it was already installed, setting `python.languageServer` to `Default` should be equivalent to `Pylance`.
