### ISSUE TITLE
Signature help highlights / and * as if they were actual parameters

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3507]
## Environment data
-   Language Server version: 2022.10.21
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

# `/` Scenario

```python
def foo(x: int, /, y: int, *, z: int):
    pass
```

## Repro Steps

1. Paste in code above
2. Below the pasted code, type `foo(1,`

## Expected behavior

Not sure given that the `y` and `z` arguments could be passed in either order, so highlighting `y` seems wrong, but highlighting the `/` is definitely wrong.

## Actual behavior

`/` is highlighted
![image](https://user-images.githubusercontent.com/12820898/196814189-5508b131-ed24-4db0-a14e-9ccadd42e9e4.png)

# `*` Scenario

```python
def bar(*, x: int, y: int):
    pass
```

1. Paste in code above
2. Below the pasted code, type `bar(x=`

## Actual behavior

`*` is highlighted
![image](https://user-images.githubusercontent.com/12820898/196813772-91350562-e157-4087-8c9e-5e69673ddb39.png)

3. Continue so you have `bar(x=1, y=`

## Actual behavior

`x: int` is highlighted
![image](https://user-images.githubusercontent.com/12820898/196814017-6330972f-2896-4058-9ca4-6a74458ed77c.png)

**Comment by bschnurr** [comment]
fixed in latest pre-release 2022.11.32
