### ISSUE TITLE
Pylance type checking rejects gRPC protobuf generated types

### ISSUE THREAD

**Issue by adriangay** [microsoft/pylance-release#351]
## Environment data

-   Language Server version: Python 2020.8.106424 (2 September 2020); Pylance 2020.9.0 (3 September 2020)
-   OS and version: OSX 10.14.6 (18G84)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5 64-bit

## Expected behaviour

Pylance type checking should accept gRPC tools generated protobuf types in type hints

## Actual behaviour

Pylance reports ```Expected class type but received "GeneratedProtocolMessageType"```

## Code Snippet / Additional information

Here is the gRPC tools generated type definition in a _pb2.py file:
```python

Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'proto.tagging_service_pb2'
  # @@protoc_insertion_point(class_scope:com.example.map.Content)
  })
_sym_db.RegisterMessage(Content)

MLTags = _reflection.GeneratedProtocolMessageType('MLTags', (_message.Message,), {
  'DESCRIPTOR' : _MLTAGS,
  '__module__' : 'proto.tagging_service_pb2'
  # @@protoc_insertion_point(class_scope:com.example.map.MLTags)
  })
_sym_db.RegisterMessage(MLTags)
```
Here is a reference in a method signature:

```python
from proto.tagging_service_pb2 import MLTags, Content

        def EnrichContentWithTags(self, request: Content, context: ServicerContext) -> MLTags:
```
Here is the Pylance type-checking message:

<img width="1164" alt="Screenshot 2020-09-09 at 21 19 46" src="https://user-images.githubusercontent.com/14236327/92649013-4907cc80-f2e2-11ea-8271-496ac64e2725.png">

**Comment by erictraut** [comment]
The protoc tool generates Python that is not friendly to type checkers. For that reason, there's a protoc plugin that generates high-quality type stubs for proto files. It's called mypy-protobuf, and you can install it via pip.

Despite the fact that "mypy-protobuf" contains "mypy" in its name, it's not specific to mypy. It outputs standard type definition files that are understandable by all standards-compliant type checkers including Pyright, which is the type checker at the heart of Pylance.

When you generate the "_pb2.py" file, you should also generate the corresponding "_pb2.pyi" file as follows:
```
protoc -I. --python_out=. --grpc_python_out=. __mypy_out=. <filename.proto>
```

**Comment by adriangay** [comment]
thanks... this fixed my issue
