### ISSUE TITLE
Pylance handling PyQt6 stub incorrectly

### ISSUE THREAD

**Issue by jasperswallen** [microsoft/pylance-release#3516]
## Environment data

-   Language Server version: 2022.10.30 (pyright 50e12b4b)
-   OS and version: macOS Monterey 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.7, from Homebrew

## Code Snippet

```python
from PyQt6.QtWidgets import QStatusBar

status_bar = QStatusBar()
status_bar.showMessage("Message")  # Argument missing for parameter "message"
status_bar.showMessage(message="Message")  # Argument missing for parameter "self"
```

For reference, the .pyi file installed alongside PyQt6 (I believe with PyQt6-sip) that this function is pulled from is correct:

```python
class QStatusBar(QWidget):
    # lots of functions here

    def showMessage(self, message: str, msecs: int = ...) -> None: ...
```

## Expected behavior

This is valid code, so Pylance should not say this is an error

Pylance seems to be missing the implicit `self` argument by operating on an object here, although I cannot reproduce this for any other classes.

**Comment by bschnurr** [comment]
can't seem to reproduce.

when you right click and `go to declaration` or `got to definition` on `showMessage` it takes you to `PyQt6\QtWidigets.pyi` ?

**Comment by jasperswallen** [comment]
Just figured it out: I had used an equals sign instead of a colon for type annotations (`status_bar = QtWidgets.QStatusBar` instead of `status_bar: QtWidgets.QStatusBar`), so Pylance (correctly) thought that `status_bar` was a type definition, not an instance.
