### ISSUE TITLE
Pylance is using 100% CPU for 1 minute after every change in a Python File

### ISSUE THREAD

**Issue by bashir-abdelwahed** [microsoft/pylance-release#3520]

**Comment by bschnurr** [comment]
r you using "openFilesOnly" ?
![image](https://user-images.githubusercontent.com/1946977/197579516-0b9f4634-77cd-4cda-a6dc-f3a62233649d.png)

**Comment by bashir-abdelwahed** [comment]
Yes I am using it now thank you

**Comment by bschnurr** [comment]
that helped?

**Comment by bschnurr** [comment]
nice
