### ISSUE TITLE
Pylance is using 100% CPU for 1 minute after every change in a Python File

### ISSUE THREAD

**Issue by bashirmindee** [microsoft/pylance-release#3521]
## Environment data

[Info  - 9:47:57 PM] (2957252) SourceFile: Received fs event 'change' for path '/home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py'
(2957252) [BG(1)] analyzing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py ...
(2957252) [BG(1)]   parsing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (7ms)
(2957252) [BG(1)]   binding: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (1ms)
(2957252) [BG(1)]   checking: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (0ms)
(2957252) [BG(1)] analyzing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (8ms)
(2957252) [BG(1)] indexing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (0ms)
(2957252) Background analysis message: markFilesDirty
(2957252) Background analysis message: analyze
(2957252) [BG(1)] analyzing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py ...
(2957252) [BG(1)]   checking: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (68ms)
[Info  - 9:47:57 PM] (2957252) Heap stats: total_heap_size=686MB, used_heap_size=565MB, total_physical_size=611MB, total_available_size=3509MB, heap_size_limit=4096MB
(2957252) [BG(1)] analyzing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (68ms)
(2957252) Background analysis message: resumeAnalysis
[Info  - 9:47:59 PM] (2957252) SourceFile: Received fs event 'add' for path '/home/bashir/mindee/mindee-products/.mypy_cache/3.8/@plugins_snapshot.json'
[Info  - 9:48:00 PM] (2957252) SourceFile: Received fs event 'change' for path '/home/bashir/mindee/mindee-products/.pytest_cache/v'
[Info  - 9:48:06 PM] (2957252) SourceFile: Received fs event 'add' for path '/home/bashir/mindee/mindee-products/.pytest_cache/v'
(2957252) Background analysis message: invalidateAndForceReanalysis
[Info  - 9:48:06 PM] (2957252) Searching for source files
[Info  - 9:48:06 PM] (2957252) Auto-excluding /home/bashir/mindee/mindee-products/venv
[Info  - 9:48:06 PM] (2957252) Found 855 source files
(2957252) Background analysis message: setTrackedFiles
(2957252) Background analysis message: markAllFilesDirty
(2957252) Background analysis message: analyze
(2957252) [BG(1)] analyzing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py ...
(2957252) [BG(1)]   parsing: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (111ms)
(2957252) [BG(1)]   parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 1ms] (50ms)
(2957252) [BG(1)]   binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/builtins.pyi (9ms)
(2957252) [BG(1)]   binding: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py (1ms)
(2957252) [BG(1)]   checking: /home/bashir/mindee/mindee-products/products/financial_document/v1_0/main.py ...
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/typing.pyi [fs read 1ms] (11ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/typing.pyi (4ms)
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/typing_extensions.pyi [fs read 0ms] (4ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/typing_extensions.pyi (11ms)
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi [fs read 0ms] (9ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/_typeshed/__init__.pyi (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/abc.pyi [fs read 0ms] (1ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/abc.pyi (0ms)
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/__future__.pyi [fs read 0ms] (0ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/__future__.pyi (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/bundled/stubs/cv2-stubs/__init__.pyi [fs read 2ms] (89ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/bundled/stubs/cv2-stubs/__init__.pyi (20ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/__init__.py [fs read 1ms] (3ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/__init__.py ...
(2957252) [BG(1)]       parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/constants.py [fs read 0ms] (1ms)
(2957252) [BG(1)]       binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/constants.py (0ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/__init__.py (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/__init__.pyi [fs read 1ms] (62ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/__init__.pyi (10ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/common/helpers/iterable.py [fs read 1ms] (4ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/common/helpers/iterable.py (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/inference/execution.py [fs read 0ms] (18ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/inference/execution.py (4ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/inference/parsing.py [fs read 0ms] (7ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/inference/parsing.py (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/utils/decorators.py [fs read 0ms] (1ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/utils/decorators.py (0ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/utils/helpers.py [fs read 0ms] (7ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/inferfwk/utils/helpers.py (2ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.pyi [fs read 0ms] (1ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/core/fromnumeric.pyi (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/__init__.py [fs read 0ms] (1ms)
[Info  - 9:48:09 PM] (2957252) Could not resolve source for '._ufunc' in file '/home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/__init__.py'
[Info  - 9:48:09 PM] (2957252)   Attempting to resolve relative import
[Info  - 9:48:09 PM] (2957252)   Attempting to resolve using root path '/home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing'
[Info  - 9:48:09 PM] (2957252)   Resolved import with file '/home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_ufunc.pyi'
[Info  - 9:48:09 PM] (2957252)   Attempting to resolve using root path '/home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing'
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/__init__.py (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_array_like.py [fs read 0ms] (3ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_array_like.py (0ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_shape.py [fs read 0ms] (0ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_shape.py (0ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_dtype_like.py [fs read 0ms] (0ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/numpy/typing/_dtype_like.py (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/collections/abc.pyi [fs read 0ms] (0ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/collections/abc.pyi ...
(2957252) [BG(1)]       parsing: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/_collections_abc.pyi [fs read 0ms] (1ms)
(2957252) [BG(1)]       binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/_collections_abc.pyi (0ms)
(2957252) [BG(1)]     binding: /home/bashir/.vscode/extensions/ms-python.vscode-pylance-2022.10.30/dist/typeshed-fallback/stdlib/collections/abc.pyi (1ms)
(2957252) [BG(1)]     parsing: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/common/python/decorators.py [fs read 0ms] (1ms)
(2957252) [BG(1)]     binding: /home/bashir/mindee/mindee-products/venv/lib/python3.8/site-packages/common/python/decorators.py (0ms)
...

-   Language Server version: v2022.10.30
-   OS and version: ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python3.8

## Repro Steps

1. I 

## Expected behavior

Pylance only reparses the file that got changed

## Actual behavior

Pylance parses all the Python files in the working directory including the whole venv

**Comment by bschnurr** [comment]
`[Info - 9:48:06 PM] (2957252) SourceFile: Received fs event 'add' for path '/home/bashir/mindee/mindee-products/.pytest_cache/v'
(2957252) Background analysis message: invalidateAndForceReanalysis`

maybe an issue with pytest.. are you running some pytest extension in the background?

**Comment by bashirmindee** [comment]
I solved the problem after a whole day of head-banging. 
The problem was the setting: 
`Python>Analysis: Diagnostic Mode`. It was set to workspace instead of Only Open Files.
It was running all the verifications on every save apparently!

**Comment by erictraut** [comment]
If you set diagnosticMode to "workspace" and modify one file, pylance will reanalyze the modified file and any files that depend on it. If it's a "leaf node" in the dependency tree, it will require analysis of just one file. If it's a source file that many other files depend upon — i.e. it's further up in the dependency tree or you have cyclical dependencies within your project — then all dependent files require reanalysis.
