### ISSUE TITLE
Possibly unbound variable in with statements

### ISSUE THREAD

**Issue by franklsf95** [microsoft/pylance-release#3523]
<h3> Environment data </h3>

-   Language Server version: 2022.10.30
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.13, anaconda
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
def foo() -> int:
    with open("a"):
        return 1
```

<h3> Repro Steps </h3>

Enter the code above.

<h3> Expected behavior </h3>

No type error.

<h3> Actual behavior </h3>

```
Function with declared type of "int" must return value
  Type "None" cannot be assigned to type "int"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

<h3> Logs </h3>

```
XXX
```

It seems to me since the function always enter the `with` path, it will always return an int. Can I somehow show Pylance this?

**Comment by erictraut** [comment]
I'm not able to repro any error with the code snippet above. The title of your bug report seems to indicate that you are seeing an error related to an unbound variable. The error you reported in the bug report has nothing to do with an unbound variable but instead is related to a return type mismatch.

Can you double check that you are seeing an error with the supplied code snippet?

There are some context managers that swallow exceptions, which means that execution will "fall through" after the `with` statement if an exception is raised. The context manager returned by the `open` function is a class called `TextIOWrapper`. It does not swallow exceptions, so execution should not fall through and continue after the `with` statement in this case.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
