### ISSUE TITLE
Type checking mode shown on status bar is incorrect

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#3527]
Type checking mode is set to `strict`. However, the status bar says it is `basic`

![image](https://user-images.githubusercontent.com/547753/197597665-2af7f03c-6e69-4f4b-b1d7-e4855eee0b45.png)

**Comment by bschnurr** [comment]
hmm. ya. how did you repo? global to strict but workspace basic?

**Comment by judej** [comment]
Work space strict. Global is set to basic

**Comment by bschnurr** [comment]
did save after editing workspace mode strict?

**Comment by judej** [comment]
I had my global set to strict. And once I updated the workspace, it all showed up correctly.
