### ISSUE TITLE
Simple comparison returns "Unknown type"

### ISSUE THREAD

**Issue by Rudxain** [microsoft/pylance-release#3531]
## Environment data

-   Language Server version: v2022.10.30
-   OS and version: Linux Mint 21
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6

## Code Snippet

```python
def starts_ends(container: str | list, x):
    """Check if it starts and ends with the same value."""
    return container[0] == x and container[-1] == x
```

## Expected behavior

Type-inference should work and the return-type should be detected as `bool`

## Actual behavior

"Type unknown" unless it explicitly uses `bool`s, like this:
```py
def starts_ends(container: str | list, x):
    return True if container[0] == x and container[-1] == x else False
```
Or if `x` is annotated
```py
def starts_ends(container: str, x: str): #bool
    return container[0] == x and container[-1] == x

def starts_ends(container: list, x: str): # Unknown
    return container[0] == x and container[-1] == x

def starts_ends(container: str | list, x: str): #Unknown | bool
    return container[0] == x and container[-1] == x

def starts_ends(container: str | list[str], x: str): #bool
    return container[0] == x and container[-1] == x

def starts_ends(container: str, x: int): # `bool`... shouldn't it be `Literal[False]`?
    return container[0] == x and container[-1] == x
```

## Logs

```
XXX
```

**Comment by erictraut** [comment]
All of these examples are working as intended. A type checker uses the type information it is provided when evaluating expression types.

The type returned by the `==` operator depends on the `__eq__` method of the LHS (left-hand side) operand. If the type of the LHS operand is unknown, then there's no way for a type checker to know what type the `__eq__` method returns, and the resulting type is likewise `Unknown`.

In your first code sample, the type of `container` is `str | list[Unknown]`, so the type of `container[0]` is `str | Unknown`. If `x` is unannotated, then its type is also `Unknown`.

In your last example, `container[0]` is type `str`, so `container[0] == x` depends on the return type of `str.__eq__` which is declared to be `bool`.

**Comment by Rudxain** [comment]
> All of these examples are working as intended. A type checker uses the type information it is provided when evaluating expression types.

I guess that's why it's "static analysis". Makes sense to me

> `==` operator depends on the `__eq__`

That explains a lot. IIRC, some operators can be overloaded, is that one of the reasons why static-analysis "tends to Unknown"?

> not `Literal[False]`

I forgot that `Literal` is only valid for literal values, not constants. Thanks for reminding me.

I'll close this issue for now
