### ISSUE TITLE
Auto-importing in current package stopped working when we changed our directory structure with python code in a folder.

### ISSUE THREAD

**Issue by nsthorat** [microsoft/pylance-release#3539]
## Environment data
-   Language Server version: v2022.10.30
-   OS and version: Mac OS 12.6 (21G115) running on M1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.13

## Code Snippet

Auto-importing broke for relative imports (completely fine for dependent packages).

Our directory structure was originally just
```
src/
  __init__.py
```

Now we changed it to:
```
pipeline/
  src/
     __init__.py
```

The relevant settings file I tried adding all combinations of this:
```
  "python.analysis.extraPaths": ["pipeline", "pipeline/src"],
  "python.autoComplete.extraPaths": ["pipeline", "pipeline/src"]
```

For example, two files:
constants.py
```
DATA_DIR = os.path.abspath('data')
```

source.py
```
print(DATA_DIR) # Here I try to control + space but it cannot resolve the import.
```

But unfortunately nothing seems to get it to work. I get "No suggestions" when importing symbols from the current package. If I manually import, the import works fine at runtime.

**Comment by luabud** [comment]
Hi there! Can you try setting your folder into the `include` setting? 
```
"python.analysis.include": [
        "pipeline/src"
    ],
```

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

that way we can see more detail.

**Comment by nsthorat** [comment]
Apologies for the back and forth! This combination ultimately worked (and no subset of it)

```
  "python.analysis.extraPaths": ["pipeline", "pipeline/src"],
  "python.autoComplete.extraPaths": ["pipeline", "pipeline/src"],
  "python.analysis.include": ["pipeline/src"]
```

**Comment by heejaechang** [comment]
"python.autoComplete.extraPaths" shouldn't be needed. it is old setting for "python.analysis.extraPaths"

**Comment by heejaechang** [comment]
@nsthorat by the way, symbols from user files are not automatically included in auto import. it will be in "add import" (the lightbulb) but not auto import unless it is already used by another open files transitively.

**Comment by nsthorat** [comment]
That’s great to know, thank you for all the help!

**Comment by heejaechang** [comment]
by the way, even without "python.analysis.include", add import should just work. we recommended "python.analysis.include" assuming you only want files inside of that to be considered as user files. but regardless of that, add import should work even without it.

thank you.
