### ISSUE TITLE
Pylance latest v 2022.10.30 disables collapsable code

### ISSUE THREAD

**Issue by 0xAskar** [microsoft/pylance-release#3543]
## Environment data

Python 3.9.15
Pylance v 2022.10.30
## Code Snippet
no code

## Repro Steps

download the latest version, open any project, and try to collaspe code

## Expected behavior
should be able to collaspe any group of code

## Actual behavior

no down arrow to collaspe code

**Comment by rchiodo** [comment]
Can you share a screenshot? It is working for me:

![image](https://user-images.githubusercontent.com/19672699/198112277-5009e57e-b332-4a97-9fee-1e84e0ce032b.png)

You do need to hover in the margin for the collapse arrow to show up.

Or change this setting to have it always show up:

![image](https://user-images.githubusercontent.com/19672699/198112445-a060bfe1-75f5-4136-ba66-b5a5df031592.png)

**Comment by 0xAskar** [comment]
it wasn't working, but now it is. I would say that vscode is trying to frame me!
