### ISSUE TITLE
`Add "# type: ignore" to suppress warning` places comment in wrong place

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3544]
-   Language Server version: 2022.10.31
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Repro Steps

1. In a `.py` file or notebook, type: `x: str = 1`
2. Click on the lightbulb
3. Click on `Add "# type: ignore" to suppress warning`

## Expected behavior

```python
x: str = 1 # type: ignore
```

## Actual behavior

```python
x: str =   # type: ignore1
```

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221141-30-November-2022-PreRelease)
