### ISSUE TITLE
Keeps reporting errors not recognizing __init__ as a function name

### ISSUE THREAD

**Issue by hayesgr** [microsoft/pylance-release#3547]
-   vscode 1.72.2
-   Windows 10
-   Python 3.11

## Code Snippet
class world:
     def __init__(self):
         return

Repro steps just type it in.

Actual behavior
Highlights in red error message listed:
Expected function name after "def" Pylance
2 to 5 minutes later it will clear. 

There is nothing else in the file, and it does it every time.

## Logs

If you are going to request something like this maybe you should include better instructions. Such as were those files are.

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
