### ISSUE TITLE
Pylance stuck, need to restart language server

### ISSUE THREAD

**Issue by mehdigmira** [microsoft/pylance-release#3548]
## Environment data

-   Language Server version: v2022.10.40
-   OS and version: Working in a devcontainer with debian bullseye. Machine is a macbook pro with m1 chip ans macOS 12.6.
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.10.8

## Issue

Pylance seems to be randomly stuck when working with some files. These files have nothing specific except that they make _advanced(ish)_ use of Python's typing (protocols and generics). Maybe worth to note, we define TypeAliases in a file and import them in other files. That's all that's really specific about this code.
If i restart the language server, it works well, but eventually will get stuck again. I've also experienced it getting stuck for a while and then working well again. When it's in this "stuck" state, quickfix, autoimports,
 and errors no longer show up (see GIF below).

I've attached the pylance trace, and added a "stuck" annotation when pylance gets stuck.
Sorry I cannot provide a code reproduction, it happens randomly on a private codebase.

![pylance_stuck](https://user-images.githubusercontent.com/13655536/198232262-b84d6a2d-e615-4c6d-acd0-f0ceaba7511d.gif)

[pylance_crash.txt](https://github.com/microsoft/pylance-release/files/9877407/pylance_crash.txt)

**EDIT:**

When I restart the language server, I see `[Error - 3:16:34 PM] Stopping server timed out` in the output

**Additional information**

- indexing is enabled
- inlayHints also

**Comment by odiseo0** [comment]
It does happen as well if you go idle for a while, the extension get stucks. It has been happening to me since VSCode installed `isort`.

My versions are 3.8 & 3.10 but in my case 3.10 has been working fine.

**Comment by mehdigmira** [comment]
I see `index execution environment /code [found 45045 in 4662 files] (63578ms)` in the trace, this seems huge. Do the 4662 files include library code as well ?

**Comment by odiseo0** [comment]
I think it only works in the files you have open

**Comment by judej** [comment]
Thanks for the report. Could you please try this on the latest build - 2022.10.40? 

Also, could you please send us the settings and the logs?

**Comment by mehdigmira** [comment]
I'm already on 2022.10.40 as stated in the report. Logs are also attached to the original report as well.
I've came across https://github.com/microsoft/pylance-release/issues/3513 and found it looked a lot like what i'm experiencing. Switched to pre-release, and now performance seems a bit better. Will confirm in the next couple of days, if it completely disappears.

**Comment by mehdigmira** [comment]
Seems to be much better with prerelease
