### ISSUE TITLE
RPyC Python module description looks strange

### ISSUE THREAD

**Issue by rafrafek** [microsoft/pylance-release#3549]
- VS Code Version: 1.72.2
- OS Version: MacOS 12.6.1 

Steps to Reproduce:

1. Install `rpyc` via pip
2. Import it in your Python project
3. Hover over `rpyc` import

How it looks in VS Code:

![](https://user-images.githubusercontent.com/23004737/198028981-e25aefbe-7279-430b-b478-9dc51e7bf0a7.png)

Module source:

![](https://user-images.githubusercontent.com/23004737/198030514-a143151b-1adb-457b-a4c3-bf28597642dd.png)

**Comment by comrumino** [comment]
@judej It is most likely a result of VS Code not respecting reStructuredText (RST). There is some ASCII art that should be interpreted as a literal block and VS Code does not seem to be rendering it correctly. I'm following up from [an RPyC issue](https://github.com/tomerfiliba-org/rpyc/issues/512).

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221141-30-November-2022-PreRelease)
