### ISSUE TITLE
Warn about shadowing stdlib modules

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#3550]
### Discussed in https://github.com/microsoft/pylance-release/discussions/2619

<div type='discussions-op-text'>

<sup>Originally posted by **brettcannon** April  5, 2022</sup>
Beginners often make the mistake of shadowing a module in the stdlib with their own code (e.g. creating a module named `queue.py` will break debugpy).

Since Pylance has the knowledge of what's in the stdlib as well as the names of the modules the user has, it could provide a diagnostic at either/both the import line that is getting shadowed or in the module causing the shadowing.</div>

**Comment by rchiodo** [comment]
This is what it looks like:



![Image](https://user-images.githubusercontent.com/19672699/199347316-855a1dee-7c52-4b29-9d5b-1734dab5ad9e.png)



To do:
- Add rename code action
- Default reportShadowedImports to 'warning' in pylance
- Write tests

**Comment by rchiodo** [comment]
Hmm, renaming a file using 'workbench.action.files.saveAs' creates a copy. Need a 'rename' command somewhere or have to write one.

**Comment by rchiodo** [comment]
Rename should probably be pushed to pylance. Seems weird for pyright to do it. I'll start there though.

**Comment by rchiodo** [comment]
To do:
- Make rename only work in VS code
- Test in web version (rename may fail there too)

**Comment by rchiodo** [comment]
Still need to override this in pylance to show a warning

**Comment by rchiodo** [comment]
This issue was fixed in prerelease version 2022.11.21. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221121-9-November-2022-PreRelease)
