### ISSUE TITLE
intellisense stuck or hang with specific module

### ISSUE THREAD

**Issue by joonhyuk** [microsoft/pylance-release#3552]
## Environment data

-   Language Server version: v2022.10.30+
-   OS and version: Linux 6.0.2-arch1-1 (Arch Linux)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.8

## Code Snippet

```python
from collections import deque

d = deque()
```

## Repro Steps

- My python project imports many modules and custom libraries
- After 10.30(now 10.40), intellisense and F12(go to definition) for collections.deque not working("Loading...") and vscode seizes one cpu core 100% until killed manually.
- Vscode itself still works without intellisense and F12
- **10.20 and earlier versions work well**
- With clean(empty) codebase, works well

## Expected behavior

- Intellisense and Go to definition work well

## Actual behavior

- Intellisense not working(with "Loading..." message)
- Go to definition not working(keep loading progress bar animating)
- code process seizes one cpu core to 100% (hang)

## Logs

No specific log for this problem.
(Output panel appears to be frozen after the problem occurs)

**Comment by mehdigmira** [comment]
Looks like this https://github.com/microsoft/pylance-release/issues/3548
You may want to check if installing the prerelease version fixes the issue

**Comment by Object905** [comment]
Had same issue until upgraded to pre-release version. Every time I've used defaultdict language server hanged until manually killed.

**Comment by mehdigmira** [comment]
Seems to be much better with prerelease

**Comment by rchiodo** [comment]
@Object905 which prerelease version did you try? 10.40.1?

There was a hang with large projects that should be fixed in 10.40.1. https://github.com/microsoft/pylance-release/issues/3513

If the prerelease you were using is 10.40.1, can you give more details on your setup?

**Comment by joonhyuk** [comment]
As far as my problem is concerned, it seems to have been solved.
(v2022.11.10)
