### ISSUE TITLE
Missing imports edge case with implicit namespace packages

### ISSUE THREAD

**Issue by vors** [microsoft/pylance-release#3553]
👋 

We are probably doing something wrong here, but this is a real case from my company where we spent countless engineering hours wasted (people were not being able to use go-to-definition in some very particular cases) because of this bug in our monorepo.

## Environment data

-   Language Server version: 2022.10.40 (pyright 24992a73)
-   OS and version: MacOS 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.15

## Code Snippet

Create the following folders structure

<img width="215" alt="image" src="https://user-images.githubusercontent.com/816680/198855426-4f372b01-b646-4e8f-8a4e-c7428b932315.png">

Files:
1. `a/b/c.py`
```python
def x():
    pass
```
2. `a/b/d.py`
```python
from a.b.c import x
```
3. `a/__init__.py` and `search_root/a/__init__.py` empty
4. `pyproject.toml`
```toml
[tool.pyright]
extraPaths = [
  "search_root",
]
```

## Repro Steps

Open `a/b/d.py` and try to use go-to-definition on the `import x` expression.

## Expected behavior

The go-to-definition works.

## Actual behavior

<img width="216" alt="image" src="https://user-images.githubusercontent.com/816680/198855505-720a9331-af5f-4ae7-9737-77916d7f1fd6.png">

The import cannot be resolved.

## Logs

https://gist.github.com/vors/86df16071fc7ff151b4c5fd446fb78a7

**Comment by erictraut** [comment]
Traditional modules (those with `__init__.py` files) take precedent over implicit namespace packages. In your example, there are two `a` modules in the search space. The submodule `a.b` is an implicit namespace because it doesn't contain an `__init__.py`. The module `search_root/a` contains an `__init__.py`, so it is a traditional package and therefore takes precedence. There is no `b` symbol within this module, so the symbol `a.b.c` cannot be resolved.

The import will be resolved if you add the missing `__init__.py` under `a/b`.

**Comment by vors** [comment]
Hi @erictraut!

Thank you for the analysis! I agree that this is probably by design and it's our usage of python in a monorepo that triggers this behavior. VSCode works surprisingly well with large monorepos that use bazel, buck, pants etc.

However, these build tools are very flexible (maybe not pants 2, this one is rather opinionated about python files layout) and allow people to have very elaborated packaging solutions.
In our case, we have a mix of "implicit namespace packages" and "traditional packages". And we have a mix of things being "absolute paths from root" and packages with "stripped prefix". From my conversation with people from Meta I think this is not unheard of in large monorepos.

When you account for all this zoo of packaging, it may be profitable not to pay too much attention to the presence or absence of the "__init__.py" files altogether. Perhaps, we can have a settings flag to relax that?

**Comment by erictraut** [comment]
Pyright (the static type checker that pylance is built upon) tries to model the import behaviors of the actual runtime. If and when we deviate from this behavior, then false positives results. The are many complex behaviors in the import resolution mechanism. Parameterizing all of them and exposing knobs for each one isn't practical. It's best for us to stick with the actual behaviors of the runtime. You'll need to find a way to make your configuration work accordingly.

**Comment by vors** [comment]
Ok, that makes sense. Thank you for the consideration!
