### ISSUE TITLE
Wrong code color syntax highlighting due to docstring

### ISSUE THREAD

**Issue by yasirroni** [microsoft/pylance-release#3556]
## Environment data

Reposting from https://github.com/microsoft/vscode/issues/165030

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

Python 3.7,4 - PyPI

## Code Snippet

Write this piece of code in .py or ipynb file,

```python
def foo(x):
    """foo
    """
    return (
        x
        * 42  # why wrong colour? treated as comment by syntax higlight
    )

def bar():
    """bar
    """
    return 42
```

## Repro Steps

1. Write and see

## Expected behavior

Not highlighted as comment

## Actual behavior

Highlighted as comment

**Comment by yasirroni** [comment]
Screenshoot here:

https://github.com/microsoft/vscode/issues/165030#issuecomment-1296495718

**Comment by rchiodo** [comment]
@yasirroni this seems to work just fine for me

![image](https://user-images.githubusercontent.com/19672699/199066213-9a3634b6-ee05-4119-8970-28a371a38cda.png)

What does it look like for you? I'm not reproing your screenshot. THis is with the Monokai Dark theme.

This is what it looks like with default dark:

![image](https://user-images.githubusercontent.com/19672699/199066399-aa938e92-94da-48a5-bedf-ba74368c0f1f.png)

What's your pylance extension version? These screen shots were taken with 2022.10.40

**Comment by yasirroni** [comment]
I'm sorry for not closing this issue. It is based on better comment. See: https://github.com/microsoft/vscode/issues/165030#issuecomment-1304847665
