### ISSUE TITLE
Intellisense not recognizing the Self typing withing staticmethod

### ISSUE THREAD

**Issue by BeetMacol** [microsoft/pylance-release#3557]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

The Code's Intellisence does not recognize the `Self` typing within methods decorated with `staticmethod`. The variables are noted as `Any`. The behavior in methods decorated with `classmethod` is correct though.

This is the case in both Python 3.10 (with `Self` from `typing_extensions`) and in Python 3.11.

## Example

The following code prints `Test` two times, as expected.
```py
from typing import Self


class Test:
    @classmethod
    def foo(cls, test: Self) -> None:
        print(type(test).__name__)

    @staticmethod
    def bar(test: Self) -> None:
        print(type(test).__name__)


Test.foo(Test())
Test.bar(Test())
```
In case of the `classmethod`, the type is detected correctly and Intellisense works fine:
![image](https://user-images.githubusercontent.com/53908689/198881782-c91f87b1-f548-4bed-88ed-660e122506bd.png)
The `staticmethod` though, does not detect the type:
![image](https://user-images.githubusercontent.com/53908689/198881954-08a152a6-cb6e-4349-a409-218e2d06db3f.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• flake8Args: "<placeholder>"
• flake8Enabled: true

```

</p>
</details>

Extension version: 2022.17.13020517
VS Code version: Code - OSS 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-13T20:17:28.261Z)
OS version: Linux x64 6.0.1-arch1-1
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (8.66GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>

**Comment by erictraut** [comment]
The `Self` type is not allowed in a static method. It is explicitly disallowed by PEP 673, which introduced `Self` and describes how it is meant to work. Here is the relevant section:

> Note that we reject Self in staticmethods. Self does not add much value since there is no self or cls to return. The only possible use cases would be to return a parameter itself or some element from a container passed in as a parameter. These don’t seem worth the additional complexity.

**Comment by BeetMacol** [comment]
Thanks for letting me know, sorry for this report.
