### ISSUE TITLE
Use new environment variables API

### ISSUE THREAD

**Issue by karrtikr** [microsoft/pylance-release#3558]
Instead of using the temporary hack to get environment variables, use https://github.com/microsoft/vscode-python/issues/20056.

cc/ @heejaechang

**Comment by rchiodo** [comment]
Is this related to the client move?

**Comment by karrtikr** [comment]
Yes

**Comment by debonte** [comment]
@heejaechang, I see this issue was moved to "Done". Can it be closed?

**Comment by heejaechang** [comment]
there is one more place we can use it (server using the API through custom LSP to resolve env variables) or we resolve things like `$workspaceroot` in the middleware. but that work is separate work I guess.

**Comment by heejaechang** [comment]
this specific issue is done. this one is about `pythonPath`
