### ISSUE TITLE
pylance can not recognize pytest fixture scope argument

### ISSUE THREAD

**Issue by kevinwang89** [microsoft/pylance-release#356]
## Environment data

-   Language Server version: v2020.9.0
-   OS and version: win10
-   Python version (& distribution if applicable, e.g. Anaconda): conda python3.8

## Expected behaviour

pytest fixture support scope argument to define the life span of the fixture.

## Actual behaviour

"scope" is not defined pylance reportundefinedvariable

## Logs

```
XXX
```

## Code Snippet / Additional information

@pytest.fixture(scope='module')
def test():
    return 1

```python
XXX
```

**Comment by huguesv** [comment]
Please see https://github.com/microsoft/pylance-release/issues/322
