### ISSUE TITLE
Auto import not working

### ISSUE THREAD

**Issue by scarf005** [microsoft/pylance-release#3561]
Type: <b>Bug</b>

for example, after typing `Path` and  `Trigger Suggest(ctrl + space)`, there is no `import pathlib` suggestion but  only `__path__` . using python `3.11.0`, pre-release python  and pylance.

Extension version: 2022.10.41
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-52-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 0|
|Memory (System)|30.72GB (20.23GB free)|
|Process Argv|--unity-launch --crash-reporter-id b0fe70dc-73b5-44f5-a8cc-3807703c7d9c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by debonte** [comment]
Auto-import is [turned off by default](https://github.com/microsoft/pylance-release/issues/3467) starting in [2022.10.41](https://github.com/microsoft/pylance-release/releases/tag/2022.10.41). Set `"python.analysis.autoImportCompletions": true` to enable it.

**Comment by scarf005** [comment]
well that's weird but alright.

**Comment by laundmo** [comment]
> Auto-import is [turned off by default](https://github.com/microsoft/pylance-release/issues/3467) starting in [2022.10.41](https://github.com/microsoft/pylance-release/releases/tag/2022.10.41). Set `"python.analysis.autoImportCompletions": true` to enable it.

thats a descision which makes sense from a "want it to be correct" POV, but has absolutely awful UX. Most users would expect auto imports to just work when installing the python extension - and likely not consider they're a off-by-default setting.

I know that it took me a surprising amount of googling to even find the change and issue - since the extension auto updated in the background and suddenly my auto imports were gone.
