### ISSUE TITLE
attrs attribute with decorator based default not recognized as field with default value

### ISSUE THREAD

**Issue by mmorys** [microsoft/pylance-release#3562]
<h3> Environment data </h3>

-   Language Server version: 2022.10.41
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Miniconda + Python 3.9.13
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

Using attrs v22.1.0 (https://www.attrs.org/en/stable/)

```python
from attrs import define, field


@define
class MyClass:
    arg1: int
    kwarg1: int = 0
    kwarg2: int = field()
    kwarg3: int = 0

    @kwarg2.default
    def _kwarg2_default_factory(self):
        return 0
```

<h3> Expected behavior </h3>

Pylance should recognize that the `kwarg2` variable is a keyword argument and has a default value specified using the [attrs decorator syntax](https://www.attrs.org/en/stable/init.html#defaults). This should not raise any syntax errors.

<h3> Actual behavior </h3>

Pylance underlines `kwarg2` with a red squiggly line and specifies the error:
```console
Fields without default values cannot appear after fields with default values
```

**Comment by Redoubts** [comment]
How do you disable this lint check? It's not obvious to me from the error message where this would be in https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings (if that's right at all).

**Comment by mmorys** [comment]
> How do you disable this lint check? It's not obvious to me from the error message where this would be in https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings (if that's right at all).

You should be able to simply add `#noqa` at the end of the affected line. i.e.
```
...
kwarg2: int = field()  #noqa
...
```

**Comment by erictraut** [comment]
Pylance isn't a linter, it's a static type checker. (Linters tend to focus on code style issues, whereas type checkers validate type consistency and bugs that can result from type violations.) In a type checker, the way to suppress a diagnostic message on a particular line is to use a `# type: ignore` comment.

**Comment by Redoubts** [comment]
So there's no configuration setting to disable this globally?

**Comment by erictraut** [comment]
Most diagnostics have an associated diagnostic rule that can be disabled independently. The specific diagnostic in this case (`Fields without default values cannot appear after fields with default values`) is currently not associated with a diagnostic rule, so it is always enabled. I think it's reasonable to move this to the `reportGeneralTypeIssues` diagnostic rule. That way, if you disable all type checking (i.e. set `typeCheckingMode` to "off"), it will be disabled globally. If that sounds like a good solution to you, please open a separate enhancement request so we can track that change.
