### ISSUE TITLE
Improve "Definition Preview Hover" rendering and layout (similiar to JetBrains IDEs)

### ISSUE THREAD

**Issue by fredrickdave** [microsoft/pylance-release#3566]
Type: <b>Bug</b>

I'm almost done with migration from PyCharm to VSCode, but a few things are holding me back! One of them being the layout and the rendering for "Definition Preview Hover" or the equivalent for "Quick Documentation Popup" on JetBrains' IDEs.

Rather than trying to explain it in words, I would rather attach a screenshot from both VSCode and PyCharm displaying the documentation for sort_values() method:

- PyCharm

![173692750-ffa5a23a-f9f7-453a-80c5-2d547ccc20d0](https://user-images.githubusercontent.com/45444823/199504718-dc0411b0-05aa-42db-8aa7-4f9956e66a8c.png)

- VSCode

![173692685-afa511bc-4928-4479-beb4-3e0d2a4ea1a2](https://user-images.githubusercontent.com/45444823/199504964-36228540-7048-4934-84b8-a635d1dddd58.png)

As you can see in the images above, PyCharm's definition doc preview is displaying very nicely, properly formatted and easy to read while VSCode started with all of the overload examples of the method and even when you scroll down past the overloads you see this hard to read and poorly formatted text:
![173693606-eba46dc3-f390-4a70-bc3e-38ba3ded2ac9](https://user-images.githubusercontent.com/45444823/199505187-19e0a54a-53d1-4415-a722-5fe40cbb3354.png)

Extension version: 2022.16.1
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.25GB free)|
|Process Argv|--crash-reporter-id 33b6b272-4665-4589-adcc-d21022a5c38a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by debonte** [comment]
This experience has been improved since you opened this issue. Here's what I see today on Pylance 2024.2.105. Please take a look.

![image](https://github.com/microsoft/pylance-release/assets/12820898/10b6c9fd-4ae5-4cd5-b5d6-57640f6924f2)

If you'd like to see additional improvements, please open a new issue with a **text** code sample and list of packages (and versions) required.

Here's my attempt at reproducing your code in this issue from your images:
```python
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

def plot_corr_heatmap(df: pd.DataFrame, title: str):
    corr_mat = df.corr()
    top_corr_features = corr_mat.index
    plt.figure(figsize=(20, 20))
    # plot heat map
    heatmap = sns.heatmap(df[top_corr_features], annot=True, cmap='coolwarm', fmt='.2f')
    
    heatmap.set_title("Correlation Heatmap")
    plt.show()
    plt.close()
    plt.figure(figsize=(20, 20))
    heatmap = sns.heatmap(
        df.corr()[[target_feature]].sort_values(by=target_feature, ascending=False),
        vmin=-1,
        vmax=1,
        annot=True,
        cmap="BrBG"
    )
```
