### ISSUE TITLE
Just keeps more and more buggy with each release

### ISSUE THREAD

**Issue by shanewazabbas** [microsoft/pylance-release#3571]
One issue is code helper process taking up 100% cpu usage. That seems to happens randomly. But the more recent issue is that type hints stop working. 

![image](https://user-images.githubusercontent.com/86968952/199746623-eeaf0ce9-1345-4ee0-b8aa-f4c4a749eded.png)

Reload the window, and now the intellisense window pops up...

![image](https://user-images.githubusercontent.com/86968952/199747306-e617be56-51d0-451c-be84-0987c377e108.png)

Obviously the issue comes back at some point, so reloading isn't a solution.

What is going on. There's no logs to help here. 

A better process is needed for release cause it seems like release version can just be labelled "beta" because it's getting less and less stable.

**Comment by rchiodo** [comment]
Thanks for the bug. The logs are found here 

![image](https://user-images.githubusercontent.com/19672699/199775713-2d1fada9-7844-4e8e-89cd-2765564862b0.png)

The log should at least give us some clue as to what's going on.

**Comment by rchiodo** [comment]
Yeah sorry there's a setting that spews more info. 

![image](https://user-images.githubusercontent.com/19672699/199790735-adc46226-e3c2-4303-ab15-2d6a48218310.png)

But it would really only be useful if you're reproing a problem. There'd be nothing in the log that would indicate a problem might occur.

**Comment by shanewazabbas** [comment]
I see, I didn't know about that setting. I'm going to close this issue, and reopen it, when I have the logs and the issue popping up again.
