### ISSUE TITLE
an operation to sort methods

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3575]
Can we provide an operation to sort methods more quickly?

When there are too many methods in a class, and I want to sort according to some rules (for example, the first letter of method names). I think it will be a more practical function.

**Comment by AdamYoblick** [comment]
Hello,

VSCode has a built-in `outline` menu that doesn't sort the file, but it does provide a list of methods and variables, and you can sort the results alphabetically. See the image below:

![image](https://user-images.githubusercontent.com/29436557/200393262-82ccac32-c93c-4ac4-bbbb-289b330e87f1.png)

Does this solve your issue?
