### ISSUE TITLE
How to handle an iterable that can return "None"?

### ISSUE THREAD

**Issue by eddyg** [microsoft/pylance-release#3578]
<h3> Environment data </h3>

-   Language Server version: 2022.11.10
-   OS and version: darwin x64
-   Python version: 3.10.6 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

_(Apologies in advance if this is the wrong place to ask about this.)_

<h3> Code Snippet </h3>

```python
from typing import Any, Iterable, Sequence, TypeVar

_T = TypeVar("_T", Any, None)


def first_n(seq: Sequence[_T], n: int = 1) -> _T | Iterable[_T]:
    def _first_n(seq: Sequence[_T], n: int) -> Iterable[_T]:
        it = iter(seq)
        for _ in range(n):
            yield next(it, None)

    if n == 1:
        try:
            return seq[0]
        except IndexError:
            return None
    else:
        return _first_n(seq, n)


data = "one two".split()
cmd, arg1, arg2 = first_n(data, 3)
print(f"{cmd=} {arg1=} {arg2=}")
```

<h3> Repro Steps </h3>

The code works as expected:

```
❯ python3.10 test.py
cmd='one' arg1='two' arg2=None
```

but pylance doesn't like the `yield` line, _or_ the `return None`.

(I will note that `mypy` doesn't complain.)

<h3> Expected behavior </h3>

Ideally no warnings from pylance, without have to resort to `# type: ignore`. 🙂

<h3> Actual behavior </h3>

On line 10 (`yield next(it, None)`):

```
Type "_T@first_n | None" cannot be assigned to type "_T@first_n"
```

On line 16 (`return None`):

```
Type "None" cannot be assigned to type "_T@first_n"; "__iter__" is not present
```

**Comment by erictraut** [comment]
There are a couple of issues in this code.

First, it includes a TypeVar that is constrained against `Any`. You should never include an `Any` as a constraint or a bound for a TypeVar! The results will be indeterminate. I suspect mypy is very confused by this, which would explain why it's reporting no errors for your code.

Let's start by fixing that issue. Remove the constraints from the TypeVar and use `_T = TypeVar("_T")`. With this fix, mypy now reports the same errors as pyright (the type checker that underlies pylance).

Let's look at the return type annotation for the outer function `first_n`. It indicates that the return value must be compatible with type `_T | Iterable[_T]`, but one of the code paths is returning `None`, which isn't compatible with that type. If your intent is to allow `None` to be returned by `first_n`, then `None` should be included in the return type union.

Next, let's look at the return type for the inner function `_first_n`. It indicates that the return type is `Iterable[_T]`, but the yield statement is returning values of type `_T | None`, so there's a type violation there. If your intent is that it should be allowed to return either `_T` or `None`, then the return type annotation for the inner function should be `Iterable[_T | None]`.

In any case, I think pyright is working correctly here. It's properly identifying and reporting type violations in your code. And it matches the behavior of mypy once you fix the issue with the `Any` constraint.

**Comment by eddyg** [comment]
Thanks for the reply! I'm _far_ from any kind of python typing expert, but am learning, so appreciate your time.

If you look at the edits to my issue, you'll see the snippet actually started off closer to what you're describing. 🙂 The latest edit was from me "experimenting" to see if I could improve things. _Mea culpa!_

With your suggested changes (and where I was when I originally opened the issue) was the final `return` statement (line 18) giving:

```
Expression of type "Iterable[_T@first_n | None]" cannot be assigned to return type "_T@first_n | Iterable[_T@first_n] | None"
```

along with any instance of calling `first_n()` giving the warning:

```
"None" is not iterable
```

(and `mypy` only complains about "None" not being iterable on any call to `first_n`).

**Comment by erictraut** [comment]
Based on the code within `first_n`, the correct type annotations for `first_n` and `_first_n` would be:

```python
def first_n(seq: Sequence[_T], n: int = 1) -> _T | Iterable[_T | None] | None:
    def _first_n(seq: Sequence[_T], n: int) -> Iterable[_T | None]:
        ...
```

This eliminates all type violations within the implementation of `first_n`, but it results in a type violation on line 22 (`cmd, arg1, arg2 = first_n(data, 3)`) because the call can produce a value of `None`, which will cause a runtime exception if you attempt to unpack it.

If your intent is that `first_n` never returns `None`, you could modify line 16 to be `return [None] * 3` and remove the `| None` from the `first_n` return type. That eliminates all type violations in the code.

**Comment by eddyg** [comment]
> If your intent is that `first_n` never returns None

Hmm… but that’s literally the  purpose of this helper function — to allow users to unpack a (potentially shorter) sequence, and have the values _not_ explicitly defined evaluate to `None` **instead** of throwing a _“not enough values to unpack”_ exception, and at the same time, allow unpacking a single-item sequence _without_ having to use a “dangling comma” (`item, = …`) on the left-hand side…

**Comment by eddyg** [comment]
@erictraut First, thanks much for taking the time to engage with me on this question. I was on holiday last week so my ability to follow-up was limited.

Your [suggested change](https://github.com/microsoft/pylance-release/issues/3578#issuecomment-1304334398) does fix the type errors for `first_n`. 🙂

When asking for only a single value, this are no warnings:

```
cmd = first_n(data, 1)
```

but for any other value, you get the `"None" is not iterable` error.

Since `next()` can be told to return `None` (instead of raising `StopIteration`), is there any way to cleanly avoid this warning, or does the use in this situation require a `#type: ignore` comment anywhere `first_n()` is called?

**Comment by eddyg** [comment]
Terrific! I appreciate your insight.

Thanks again for your time.
