### ISSUE TITLE
Revert #3467

### ISSUE THREAD

**Issue by dakotahorstman** [microsoft/pylance-release#3579]
#3467 should be reversed. It takes the wrong approach to a problem not every user faces (i.e. myself, for example) and creates a problem every user will face. For example, I no longer get code suggestions for stdlib modules (such as `typing`), let alone any of my pip installed. This severely castrates Pylance's appeal and usability by requiring a setting change to bring it to its full potential.

Plus, it would appear no outreach to the community was performed to see if the issue #3467 addresses is actually an issue, nor is there any indication an attempt to incrementally address it was performed (i.e. only suggest the user's most used packages, disable non-stdlib suggestions, more intelligently suggest packages, etc).

**Comment by dakotahorstman** [comment]
Additionally, #3467 doesn't address the underlying issue, just the symptoms. When users inevitably enable this setting, they'll be confronted by the issue again if it pops up for them.

**Comment by judej** [comment]
@dakotahorstman, thanks for the report. The reason we changed the default setting of `python.analysis.autoImportCompletions` to false was that we got feedback that the feature was causing confusions especially with newer users. Specifically, the auto import would add an import to an incorrect module without the user noticing it. 

So, for example, when I type `path` it auto imports `from importlib.resources import path` That is unexpedcted and incorrect for me. There are times when a more obscure lib would be imported. We needed to address that problem and therefore turned it off by default.

With regard to your suggestion of being smarter with the suggestions, is something we are looking at. We have a work item on it and expect the suggestions to be smarter in an upcoming release.

thanks

**Comment by dakotahorstman** [comment]
@judej Thanks for the reply, but your (and the team's) reasoning is still severely flawed here. This isn't a bandaid or a bridge. It's a wrecking ball. It does not help those who encounter the issue because they're just going to re-enable it and re-encounter the same issue (or uninstall Pylance). Those who don't encounter the issue are now going to be left frustrated because Pylance no longer works as it used to and they have to spend more of their time trying to figure out why.

If newer users are getting confused by the suggestions, then putting a note on the VSCode Marketplace page for Pylance about it would be far better considering *everyone* sees that page when they install the extension.

**Comment by jay-snyder** [comment]
The extension details seem to still suggest that the default value for `python.analysis.autoImportCompletions` is `true` which could lead to a big headache for users who are trying to figure out why all of the sudden their import suggestions disappeared.

I am admittedly that user.

**Comment by debonte** [comment]
> The extension details seem to still suggest that the default value for python.analysis.autoImportCompletions is true

@jay-snyder, thanks for pointing that out! We'll get that fixed in the next release.

**Comment by fenilgandhi** [comment]
It would help a lot if we could configure what folders it considers for auto import Completions. In most cases, i am looking for only functions which i have defined in my workspace. If i can limit it somehow to functions, import already used in my workspace, that would be very useful

**Comment by jbmusso** [comment]
Just sharing some user experience here, for an overall great extension.

> Those who don't encounter the issue are now going to be left frustrated because Pylance no longer works as it used to and they have to spend more of their time trying to figure out why.

I can confirm that I've been one of these users :). Auto completion used to work, and stopped overnight after restarting my computer.

I thought that my setup was responsible for this and had become broken overnight and/or that Pylance was broken. Trying to understand if virtual env, python path, etc. are properly configured is not fun : hard or next to impossible for juniors, probably time consuming even for experienced.

Although being comfortable with GitHub and Google, it took me several months to find this solution of using `"python.analysis.autoImportCompletions": true` to revert back to the default behavior that I was expected from such an extension, and ok with in my day-to-day code.

During that time, I had switched to using `Cmd + Shift + ;` and open up the autofix window from which I would manually select the right import.

**Comment by dakotahorstman** [comment]
@judej @debonte 

The upvotes to revert this change now exceed the combined upvotes of #3467 and #2344 which appears to be the original requester. I would also appreciate if this issue would be reopened and reconsidered since it was prematurely closed IMO. This issue still affects users, and giving a quick test to see if there has been any improvement as promised by @judej, this has not been resolved after nearly a year.

**Comment by rchiodo** [comment]
I believe we disabled this because auto imports aren't reliable. Our number one error is 'import unresolved'. 

I'm wondering if maybe we can auto import only those things that would not cause an import error? That might make auto imports more reliable.

**Comment by erictraut** [comment]
> I believe we disabled this because auto imports aren't reliable.

I don't think that was the reason. Auto-import is very reliable. It was disabled because some users were surprised and dismayed when import statements were added to their files. They weren't expecting that behavior.

I sympathize with those users, but I also sympathize with those who think that it was a mistake to disable auto-import by default. Language servers in other languages like TypeScript enable auto-import by default. Users either get used to it (i.e. they get over their initial surprise and accept the behavior) or they disable the feature.

**Comment by rchiodo** [comment]
> I don't think that was the reason. Auto-import is very reliable.

The two issues referenced here seem to say that. I believe our telemetry said that with auto import on, completions were not being completed as much.

**Comment by dakotahorstman** [comment]
Disabling this setting disables all import suggestions including first-party, 3rd-party, stdlib, etc. In #3467, @judej explained his reasoning for this change to be the auto-import, through the intellisense suggestion I presume, may be incorrect if users don't pay attention closely.

For example, if I want to use `Dict` from the `typing` module, intellisense suggests, in order:

- `from ast import Dict`
- `from typing import Dict`
- `from traitlets import Dict`
- ...

I hardly ever use `ast`, have never used `traitlets`, but use `typing` all the time. I'd much rather deal with "poor" import suggestions and potentially choosing the wrong one (which I occasionally do!) than try to remember every import path for every common component I use. Take this with a grain of salt, but extrapolating the upvotes here as representing the user base as a whole, I believe the majority would agree.

Plus, if the wrong import is chosen, more often than not:
- Pylance will catch the issue (through the user trying to use an attribute that exists in their desired import, but not the actual)
- The user will catch the issue (some sort of review)
- Their tests will catch the issue
- Python will catch the issue (some sort of error)

As you stated @erictraut, those select users struggling with this will either get used to this and keep an eye out (see myself for example) or will disable the feature. To restate what I said before as well, not every user experiences this issue--but every user relying on auto-import will experience frustration and headache because a very useful feature (to them at least) is no longer working or just appears to be missing. Especially since other language servers have this feature enabled by default.

**Comment by erictraut** [comment]
Maybe I misunderstood what you meant by "unreliable". Do you mean:
1. The feature is inserting import statements that then result in an import resolution error? 
2. It's inserting an import statement that imports a symbol from a different library than the one the user expects?
3. Something else?

I'm not aware of 1 being a problem. Item 2 has been a reported issue, but that's arguably user error because they selected the wrong completion. You could also say that it's a UX problem if users are regularly selecting the wrong completion without realizing it.

**Comment by rchiodo** [comment]
Thinking more about 1, 1 seems impossible. How would we even suggest it if it's not a valid import. 

Number 2 is the likely case. At least the bugs referenced show that. If I recall our brainstorming sessions, the idea was to try and pick the 'more' right one first. Figure out a way to better sort the auto import suggestions. That was the usability suggestion we were trying to figure out.

**Comment by rchiodo** [comment]
The new user thing is a different caveat to this. New users don't know which import is the 'right' one. They don't know what imports they might want to accomplish what they're doing. 

New users are also less likely to find github and this specific repository in github to log an issue. Our telemetry showed an impact on completions. A statistically significant impact. The guess was that new users were liking Pylance less because of auto import. Perhaps this was the wrong assumption to make but it's hard to tell.

'Advanced' users want auto import on.  They can find the setting (and/or this issue). 

The worry was about people that can't find a setting and can't figure out what package to import. 

Perhaps there's some way to identify what the 'right' import is, but we haven't gotten there yet.

**Comment by rchiodo** [comment]
@tsdaemon, you should be getting this:

![image](https://github.com/microsoft/pylance-release/assets/19672699/ea0a3a0b-518e-4fb3-9522-df0497c8022e)

Can you log a new issue?
