### ISSUE TITLE
Code folding hides entire function/class names in Visual Studio

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#3580]
Code folding behaves differently in VS and VSCode. In VS, the entire function name disappears after collapsing the function.
![image](https://user-images.githubusercontent.com/100439259/200087019-f7465aa4-f2eb-4b21-9cf8-22c4f90e3d2f.png)

What's causing the difference is that in VS Code, the [`lineFoldingOnly`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#:~:text=in%20a%20FoldingRange.%0A%09%20*/-,lineFoldingOnly,-%3F%3A%20boolean%3B) client capability is set to `true` such that the client signals that it only supports folding complete lines, and will ignore specified `startCharacter` and `endCharacter` properties in a FoldingRange. 

In Visual Studio, however, the `lineFoldingOnly` is not set so it will fold in the middle of line, and this becomes a problem when `textDocument/foldingRange` always returns 4(which is the end of `def  `) as the `startCharacter` rather than the end of line of the first line.

Below are LSP messages monitored from VS Telemetry Monitor.
![image](https://user-images.githubusercontent.com/100439259/200088094-0e04d848-a3a1-4f3a-9c5d-377d2cfd28df.png)

Related issue in PTVS: https://github.com/microsoft/PTVS/issues/7032

**Comment by debonte** [comment]
@StellaHuang95, here's the function that adds folding nodes for functions -- https://github.com/microsoft/pyrx/blob/a9cbf1ee68939e4c8e5d844508c9d84dde071ec7/packages/pylance-internal/src/languageService/foldingRangeProvider.ts#L136

```python
override visitFunction(node: FunctionNode) {
    this._addTwoNodeRange(node.name, node.suite);
    return true;
}
```

The range for functions currently starts at the beginning of the function's name. We could fix that, but it might be better to modify `_addTwoNodeRange` to change the resulting range to start at char 0 of the first line and end at the very end of the last line. I think this would ensure that our folding ranges are treated the same way regardless of what `lineFoldingOnly` is set to in FoldingRangeClientCapabilities.

We could decide later to take advantage of intra-line folding, but the `FoldingRangeProvider` was not implemented with that feature in mind.

**Comment by StellaHuang95** [comment]
@debonte, I made a change [here](https://github.com/microsoft/pyrx/blob/a9cbf1ee68939e4c8e5d844508c9d84dde071ec7/packages/pylance-internal/src/languageService/foldingRangeProvider.ts#L227) to pass `endNode.start + 1` rather than `startNode.start` to `convertOffsetToPosition()`, hoping it would return the last character of the first line, but it doesn't seem to fix all the cases especially with the functions that have multiple lines of arguments/docstring/match-case:

For example,
```python
def my_func(
    a,
    b,
    c
):
    """Docstring
    """
    return a + b + c
```

when collapsing the function, it becomes 
```python
def my_func(
    a,
    b,
    c
):...
```
when collapsing the docstring, it becomes
```python
def my_func(
    a,
    b,
    c
):
    "...
    return a + b + c
```
which doesn't match vscode's behavior of only leaving the entire first line visible.

Do you happen to know if there's any other way to get the position of the last character of the first line? I also tried `startNode.start + startNode.length` but I don't think `startNode.length` include the length of the function arguments.

**Comment by debonte** [comment]
Some context: `startNode` and `endNode` are nodes within the parse tree representing the beginning and end of the foldable range. In some cases they are the same node (any `visitFoo` function that calls `_addNodeRange`) and in others they are different (any `visitFoo` that calls `_addTwoNodeRange`). In either scenario, the beginning of `startNode` and the end of `endNode` might be on the same line, but if that's true we [don't bother returning](https://github.com/microsoft/pyrx/blob/a9cbf1ee68939e4c8e5d844508c9d84dde071ec7/packages/pylance-internal/src/languageService/foldingRangeProvider.ts#L231) a folding range for them, since we only support line folding and a single line can't be folded.

> Do you happen to know if there's any other way to get the position of the last character of the first line?

`this._parseResults.tokenizerOutput.lines` contains all of the lines in the file. Something like this should work I think:

```typescript
const startLine = this._parseResults.tokenizerOutput.lines.getItemAtPosition(startNode.start);
const startPos = TextRange.getEnd(startLine)
```

**Comment by debonte** [comment]
FYI, we leave Pylance issues open until the fix is released.

**Comment by StellaHuang95** [comment]
Thanks @rchiodo!! Do you know when will the users be able to see the fix in VS? Is it after this change is in stable?

**Comment by rchiodo** [comment]
Not sure. Where and when does PTVS update its pylance bits? When you pull in version 2022.11.31, that should be when it becomes a part of PTVS.

**Comment by StellaHuang95** [comment]
Looks like we need to make a VS PR to update pylance, I will see if I can kick off that by starting a new main build.
