### ISSUE TITLE
Import "PyQt5" could not be resolved

### ISSUE THREAD

**Issue by Raekpruk** [microsoft/pylance-release#3582]
![Screenshot (41)](https://user-images.githubusercontent.com/117500774/200102247-4654ef59-1c93-4036-86e0-754751d9550d.png)

How come Visual Studio can't locate it?
However, PyScripter may be imported without issue.

**Comment by rchiodo** [comment]
Can you include the information from our 'filing an issue' in our troubleshooting guide?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

This may be expected if the python interpreter you have selected does not have PyQt5 installed.

**Comment by FIRDOUS-BHAT** [comment]
I'm facing with the same issue even though the PyQt5 is installed!

**Comment by judej** [comment]
@FIRDOUS-BHAT or @Raekpruk , thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
