### ISSUE TITLE
Matplotlib 3D Syntax Incorrectly Highlighted

### ISSUE THREAD

**Issue by chinmaykh** [microsoft/pylance-release#3583]
## Environment data

-   Language Server version: v2022.11.10 (pyright 4e50162d)
-   OS and version: MacOS Ventura 13.0 & Ubuntu 20.04.5 LTS
-   Python version: Python 3.8.10 & conda's Python 3.8.12 (It's a global bug)

## Code Snippet

```python
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(5, 5), dpi=200)
axs = fig.add_subplot(projection='3d')

max_val = 10

axs.set_xlim(0, max_val)
axs.set_ylim(max_val, 0)
axs.set_zlim(0, max_val)

# Draw a point at the origin
axs.scatter(0, 0, 0, s=5, c='b')
```

## Repro Steps

1. Edit this with Pylance in any Python3.

## Expected behavior

No errors should be present as this is a 3D axis and not a 2D one.

## Actual behavior

`.set_zlim` and `s=5` get highlighted as errors. Pylance doesn't  know these are 3D plots, hence it doesn't know the `set_zlim` method. Similarly, it doesn't know that in the 3d plot, the third argument for scatter is the `z` value and not the `s` value.

## Logs

Couldn't find any logs in the python panel after performing the instructions in this documentation. But you don't need it because the problem is pretty straightforward?
```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue. I can repro. 

My guess is that the matplotib stubs don't support this. In fact, it looks like the axes [documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_ylim.html) doesn't list it, so the return value in the stub of add_subplot is probably incorrect. It should likely be something like so:

```python
    def add_subplot(self, *args, **kwargs) -> Axes | Axes3D ...
```

We get the matplotlib stubs from here:
https://github.com/Microsoft/python-type-stubs

**Comment by judej** [comment]
@gramster, looks like a typestub issue.

**Comment by bschnurr** [comment]
workaround stub

```python
from mpl_toolkits.mplot3d import Axes3D

@overload
    def add_subplot(self, projection: Literal['3d'], *args, **kwargs) -> Axes3D: ...
```

**Comment by bschnurr** [comment]
PR. https://github.com/microsoft/python-type-stubs/pull/237

**Comment by chinmaykh** [comment]
Thanks for all the replies and corrective actions. Where does this go from here?

**Comment by judej** [comment]
This has been fixed in the typestub repo. This will be picked in an upcoming release. In the mean time, if you need it fixed now, you can replace your existing matplotlib/figure.pyi stub with the file in the the typestub repo: https://github.com/microsoft/python-type-stubs/blob/main/matplotlib/figure.pyi.
