### ISSUE TITLE
"Unexpected token at end of expression" in f-string

### ISSUE THREAD

**Issue by yangtzech** [microsoft/pylance-release#3585]
<h3> Environment data </h3>

-   Language Server version: 2022.11.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

input:
```python
x = np.array([2])
print(f"{x.shape=}")
```
output:
```python
x.shape=(1,)
```

<h3> Repro Steps </h3>

1. Executing the code snippet will get the right output, and no error occurs.
2. But a red line under the code.

<h3> Expected behavior </h3>

No error hint

<h3> Actual behavior </h3>

![image](https://user-images.githubusercontent.com/41911522/200122257-fb0669a0-e249-48a8-b1da-689e612325e0.png)

<h3> Logs </h3>

```
XXX
```

**Comment by erictraut** [comment]
I'm not able to repro this problem. Can you confirm that you're able to repro by creating a new ".py" file and pasting the following minimal code sample into that file?

```python
import numpy as np

x = np.array([2])
print(f"{x.shape=}")
```

Here is what it looks like for me:

![Screenshot 2022-11-05 at 7 28 13 AM](https://user-images.githubusercontent.com/7040122/200124706-8c40e259-9bbb-46b7-816c-4eacf82ae997.png)

**Comment by yangtzech** [comment]
Yes, the problem still occurs.

![image](https://user-images.githubusercontent.com/41911522/200124899-5428299f-4cf3-418c-be57-e2d97f254012.png)

**Comment by yangtzech** [comment]
Sorry, I think it's my problem. After my VSCode just crushed and reloaded, the problem solved. Thanks!
