### ISSUE TITLE
Autocomplete suggestions for import don't work without entry in __init__.py

### ISSUE THREAD

**Issue by vishwa-raj** [microsoft/pylance-release#359]
## Environment data

-   Language Server version: 2020.9.4
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7, Anaconda

## Expected behaviour

Autocomplete suggestion for import should be shown during typing even without entry in `__init__.py`.
This is the behaviour when using Jedi.

![jedi](https://user-images.githubusercontent.com/22815753/92877028-6181ff00-f428-11ea-8d1a-cc047d400d21.gif)

## Actual behaviour

Without entry in `__init__.py`, autocomplete suggestion is showed with Ctrl+Space but not while typing.

![pylance](https://user-images.githubusercontent.com/22815753/92877014-5dee7800-f428-11ea-8ccf-0dc931a08a81.gif)

**Comment by vishwa-raj** [comment]
Any update on this issue ?

**Comment by erictraut** [comment]
Could you provide more information or perhaps a self-contained example of the problem? I can't tell from your description or the animated gifs what you mean by "without entry in __init__.py".

**Comment by vishwa-raj** [comment]
@erictraut I've attached example code for the problem.

Simply put, the difference between Jedi and Pylance, when trying to import the file `child_1.py` in `parent.py`,
is that the name of the file `child_1` automatically shows up in suggestion while typing with Jedi but not with Pylance.

Expected behaviour:
![jedi](https://user-images.githubusercontent.com/22815753/96031353-dc509680-0e7a-11eb-874f-19f4ea3d488d.gif)

Actual behavious
![pylance](https://user-images.githubusercontent.com/22815753/96031335-d8247900-0e7a-11eb-9c10-6adf5d9f0b79.gif)


[autocomplete_check.zip](https://github.com/microsoft/pylance-release/files/5380233/autocomplete_check.zip)

**Comment by erictraut** [comment]
Thanks for the example — very helpful. I've diagnosed and fixed the problem. The bug fix will be included in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020102-21-october-2020

**Comment by vishwa-raj** [comment]
Thanks @erictraut @jakebailey
