### ISSUE TITLE
Try to check exec type command for variable defined detection ('reportUndefinedVariable')

### ISSUE THREAD

**Issue by AnirbanKopty** [microsoft/pylance-release#3590]
I have attached a screenshot showing a code that successfully works, and yes, I wasn't expecting Pylance to detect that the variable was defined.
But, I think it would be great if this can be looked at.

Description of the image:
I wanted to define variable names iteratively, I came across a way to do that by using the command `exec` and combining it with the f-string method. It successfully works.
```Python
for i in range(1,5):
    exec(f'Psi{i-1} = data[:,i]')
```
This piece of code returned
```Python
Psi0 = data[:,1]
Psi1 = data[:,2]
Psi2 = data[:,3]
Psi4 = data[:,4]
```

But, while using the variables later, Pylance couldn't detect that those were defined (actually not yet defined, but will be defined - which is why the problem arises).

So. I was thinking to inform this 'issue', and it might suggest some way to fix this.

![Screenshot](https://user-images.githubusercontent.com/83864185/200412443-5acd2311-a7e0-4364-aab8-c360752b5968.png)

**Comment by judej** [comment]
@AnirbanKopty, thanks for the report. Pylance has a static checker and will not be able to analyze the return type from dynamic calls. If you could declare and type annotate `Psi` you would get rid of the warnings. Hope that helps.
