### ISSUE TITLE
Wrong sum() return type derivation for unknown start value

### ISSUE THREAD

**Issue by FatsieFS** [microsoft/pylance-release#3591]
## Environment data

-   Language Server version: 2022.11.10
-   OS and version: Ubuntu 20.04.5 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13

## Code Snippet

```python
from typing import Iterable, Any

def f(l: Iterable[Any], s):
    return sum(l, s)
```

This code derives `int` as return type for `f()` although it should be `Unknown`.

Problem is that this can lead to type errors that should not be type errors

```python
from typing import Iterable, Any

def f(l: Iterable[Any], s):
    return sum(l, s).width
```

## Expected behavior

`f()` having `Unknown` as return type for first snippet and not having type error for second snippet.

## Actual behavior

Pylance has derived `int` as return type for `f()` in first snippet.
Second snippet gives type error:
```
Cannot access member "width" for type "int"
  Member "width" is unknown
```

**Comment by erictraut** [comment]
The `sum` function is declared in the typeshed `builtins.pyi` stub file, and it's an overloaded function with three overloads:

```python
@overload
def sum(__iterable: Iterable[bool | _LiteralInteger], start: int = ...) -> int: ...

@overload
def sum(__iterable: Iterable[_SupportsSumNoDefaultT]) -> _SupportsSumNoDefaultT | Literal[0]: ...

@overload
def sum(__iterable: Iterable[_AddableT1], start: _AddableT2) -> _AddableT1 | _AddableT2: ...
```

Pyright (the static type checker that underlies pylance) performs overload matching by picking the first overload that matches the supplied argument list. In your example above, the first overload matches, so the return result is `int`. That means the inferred return type of `f` is `int`.

If you want pyright to choose a different overload, you will need to supply more precise type declarations for the parameters `l` and `s`.

**Comment by FatsieFS** [comment]
@erictraut
mypy seems to be able to do the right derivation of sum returning Unknown is start type is Unknown; likely time to switch over.
Reason I stumbled on this is that I am using sum on types from a an external library (pya from klayout) that does not have type annotation.

**Comment by FatsieFS** [comment]
And thinking a little further I disagree that `Unknown` as type for start should match the first overload of `sum` because the start value can be something else than an `int`. So IMO mypy is doing the right thing.

**Comment by erictraut** [comment]
@FatsieFS, overload resolution rules are not specified in Python. The details are left up to each type checker. Mypy's overload resolution rules are defensible (i.e. there is a good argument for their behavior), but so are the overload rules used by pyright. They both have advantages and disadvantages and fail and succeed in different circumstances. Pyright's overload resolution rules match that of other Python type checkers like pyre and other languages like TypeScript.

**Comment by FatsieFS** [comment]
@erictraut 
Understood.
I tend to favor mypy resolution rules then as I find it better matching with being more compatible with non type annotated code.

**Comment by YodaEmbedding** [comment]
Note that `bool | _LiteralInteger ≤ Any`, where ≤ denotes subtype.

So why does an input of type `Iterable[Any]` match the overload type `Iterable[bool | _LiteralInteger]`?

Firstly, allowing the opposite (an input `Iterable[bool | _LiteralInteger]` to match an overload `Iterable[Any]`) would be bad, as indicated by the following example from [PEP 483](https://peps.python.org/pep-0483/#subtype-relationships):

> Let us also consider a tricky example: If `List[int]` denotes the type formed by all lists containing only integer numbers, then it is not a subtype of `List[float]`, formed by all lists that contain only real numbers. The first condition of subtyping holds, but appending a real number only works with `List[float]` so that the second condition fails:
> 
> ```python
> def append_pi(lst: List[float]) -> None:
>     lst += [3.14]
> 
> my_list = [1, 3, 5]  # type: List[int]
> 
> append_pi(my_list)   # Naively, this should be safe...
> 
> my_list[-1] << 5     # ... but this fails
> ```

Evidently, `int ≤ float` (well, sort of), and yet `List[int] ≮ List[float]`.

Similarly, `List[float] ≮ List[int]`, since:
```python
def assert_int(lst: List[int]) -> None:
    assert all(isinstance(x, int) for x in lst)

my_list = [1.1, 3.3, 5.5]  # type: List[float]

assert_int(my_list)  # throws AssertionError
```

This is due to [covariance/contravariance/invariance](https://peps.python.org/pep-0483/#covariance-and-contravariance), which is defined as follows:

> A generic type constructor `G` is called
> 
> - Covariant, if `G[S] ≤ G[T]`
> - Contravariant, if `G[T] ≤ G[S]`
>
> for all types `S, T` such that `S ≤ T`, and
>
> - Invariant, if `G` is not covariant nor contravariant (i.e., `G[S] ≠ G[T]` for some `S ≤ T`).

Apparently, `List[T]` is defined to be invariant.
Thus, `List[Any] ≠ List[bool | _LiteralInteger]`.

**However,** `Iterable[T]` is defined to be covariant.
Thus, `Iterable[Any] ≤ Iterable[bool | _LiteralInteger]`.

And that's what causes the issue.

**Comment by YodaEmbedding** [comment]
I wonder if there's a more restrictive set of overloads that could be defined instead. For example:

```python
def sum(iterable: List[bool], /, start: int = 0) -> int:
def sum(iterable: List[_LiteralInteger], /, start: int = 0) -> int:
def sum(iterable: Iterable[_SupportsSumNoDefaultT], /) -> _SupportsSumNoDefaultT | Literal[0]:
def sum(iterable: Iterable[_AddableT1], /, start: _AddableT2) -> _AddableT1 | _AddableT2:
```

...Or maybe something more fancy that can support `Iterable[bool]`, but only invariantly rather than covariantly.
