### ISSUE TITLE
While making an website using django framework I encountered a sistuation to call the child model object the code is running fine but the

### ISSUE THREAD

**Issue by ArManiyar** [microsoft/pylance-release#3593]
While making an website using django framework I encountered a situation were to  call the child model object  by the parent.
The code is running fine but the warning comes up and it is so annoying.

![Screenshot 2022-11-08 213540](https://user-images.githubusercontent.com/86867746/200616329-deb48fa9-9595-434e-932b-b6a81fa5cfab.jpg)
![Screenshot 2022-11-08 213647](https://user-images.githubusercontent.com/86867746/200616309-b99e8f89-a774-4ab4-819a-b1efc31fa932.jpg)

**Comment by rchiodo** [comment]
Thanks for the bug.

Could you paste the code to repro or possibly the data from this here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by bschnurr** [comment]
where is `message_set` supposed to come from?

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
