### ISSUE TITLE
PROBLEMA

### ISSUE THREAD

**Issue by xela4060** [microsoft/pylance-release#3594]
quanado vado a scrivere nel terminale pip install pynput dice che non è corretto e non riesco a risolvere il problema<!--

![2022-11-08 (1)](https://user-images.githubusercontent.com/93289221/200638994-5974e09b-b7ff-4868-bb8e-25d749f44984.png)

**Comment by rchiodo** [comment]
Thanks for the bug. It looks like you don't have pip installed on your machine. 

Pylance doesn't install pip or provide support for it, but I'd recommend looking here:

https://pip.pypa.io/en/stable/installation/
