### ISSUE TITLE
star operator in zip function leads to incorrect type assumptions

### ISSUE THREAD

**Issue by hoelzeli** [microsoft/pylance-release#3598]
Pylance does not approve the following code:

```python
test_list: list[tuple[int, str]] = [(1, 'testa'), (2, 'testb')]

a: tuple[int]
b: tuple[str]

a, b = zip(*test_list)
```

the warning for the zip function is:
```
Expression of type "tuple[int | str]" cannot be assigned to declared type "tuple[int]"
  "tuple[int | str]" is incompatible with "tuple[int]"
    Tuple entry 1 is incorrect type
      Type "int | str" cannot be assigned to type "int"
        "str" is incompatible with "int" (PylancereportGeneralTypeIssues)
Expression of type "tuple[int | str]" cannot be assigned to declared type "tuple[str]"
  "tuple[int | str]" is incompatible with "tuple[str]"
    Tuple entry 1 is incorrect type
      Type "int | str" cannot be assigned to type "str"
        "int" is incompatible with "str" (PylancereportGeneralTypeIssues)
```

a and b are only ints and strs:
```python
print(a)
# Output: (1, 2)
print(b)
# Output: ('testa', 'testb')
```

Expected behavior:
The warning seems inappropriate. As long as all elements in the list are of the specified type (tuples with two entries, the first being an int and the second a str), a should always have only int entries and b should always have only str entries.

**Comment by erictraut** [comment]
This is a result of the way `zip` is declared in the typeshed `builtins.pyi` stub file. The constructor for the `zip` class is overloaded, but here's the overload signature that applies in this case:

```python
        @overload
        def __new__(cls, __iter1: Iterable[_T1], *, strict: bool = ...) -> zip[tuple[_T1]]: ...
```

You're passing a `tuple[int, str]` argument to parameter `_iter1` (as a result of the unpack of the list). The type `tuple[int, str]` is type compatible with `Iterable[int | str]`, so the type checker determines that the value of type variable `_T1` is `int | str`. The result of the call is a new object of type `zip[tuple[int | str]]`. Unpacking this into `a` and `b` invokes the `__iter__` method on the `zip` object, and that results in unpacked items of type `tuple[int | str]`. These are type incompatible with `tuple[int]` and `tuple[str]`, hence the type violations.

So pylance is doing the correct thing here from a type analysis standpoint.

It is difficult to provide a proper type declaration for the `zip` constructor in the current Python type system. You could file a bug in the typeshed project, but I don't see a good way for the typeshed maintainers to fix this.

You'll probably need to find a workaround for this limitation in your code. A `typing.cast` call may be needed.
