### ISSUE TITLE
How to prevent autocomplete of type hints

### ISSUE THREAD

**Issue by GBrachetta** [microsoft/pylance-release#3599]
I would like to deactivate the autocompletion of type hints, such as described in the video below.

https://user-images.githubusercontent.com/57924268/200871266-a3d07c39-3d55-4761-86e0-bae207114263.mov

How can I get rid of those type hints in the autocomplete?

**Comment by bschnurr** [comment]
isn't that copilot?

**Comment by judej** [comment]
Could you also let us know what the version of VSCode and Pylance you are using?

Also are you using another extension for inline errors?

**Comment by GBrachetta** [comment]
I'm using VSCode 1.73.0 and Pylance v2022.11.10.

The behaviour (the autocompletion of the type hints) disappears when I disable Pylance, but of course that's not what I'd want to do.

Autocomplete of just `list_display` is what I'd want, but not all the type hints I'm deleting in the video.

**Comment by bschnurr** [comment]
Could be intellicode. you could try disabling that extension

**Comment by GBrachetta** [comment]
I'm afraid it's not intellicode. Same behaviour uninstalling it.

Maybe my issue is pretty easy to replicate if you're interested to debug it.

**Comment by bschnurr** [comment]
Ah.. I see it now.. yes we are including the annotation type from the django stubs.

this could be an enhancement to control annotation printing.

**Comment by heejaechang** [comment]
so the behavior is because of this - https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/languageService/completionProvider.ts#L985

currently there is no option to control the behavior.

**Comment by GBrachetta** [comment]
Thanks for spotting the cause. Yes, it would be great to be able to toggle this behaviour on/off because it wastes a lot of time for people not using annotation types.

**Comment by heejaechang** [comment]
we are discussing a way to mitigate the issue. either providing option to toggle, or use type checking mode, or provide separate completion that has the type annotation when user type `:` after the member variable or etc.

**Comment by GBrachetta** [comment]
Thanks, that's great, as soon as it still lets autocomplete the variable **alone** if we don't type the colon (`:`).

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221141-30-November-2022-PreRelease)
