### ISSUE TITLE
Pylance allows redefining a variable with a type hint

### ISSUE THREAD

**Issue by mgoldenbe** [microsoft/pylance-release#3602]
I would expect that the following program should result in a warning (using the strict mode):

```python
a: int = 1
a = True
```

In fact, I think it should result in a warning even without a type hint, but it does not.

Using Pylance v2022.11.20 under VS Code 1.72 under Windows 10 Pro.

**Comment by mgoldenbe** [comment]
I realized the Boolean can be converted to int in Python.

**Comment by erictraut** [comment]
Yes, the `bool` type is a subtype of `int`, so it is allowed to assign a `bool` to a variable that has been declared as an `int`.
