### ISSUE TITLE
Type inference not working?

### ISSUE THREAD

**Issue by mgoldenbe** [microsoft/pylance-release#3603]
The following gives a warning as expected:
```python
my_num: int = 1
my_num = 'aa'
```

But the following does not:
```python
my_num = 1
my_num = 'aa'
```

It looks like the integer type was not inferred.

**Comment by erictraut** [comment]
This is working as expected. You're confusing the concept of type inference with the concept of a type declaration. For details, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).

In the first example, you have declared that `my_num` is of type `int`, so the type checker will generate an error if you attempt to assign a value that is not an `int` (or a subtype thereof). In the second example, you have not declared any type for `my_int`.
