### ISSUE TITLE
"be accessed" check issue

### ISSUE THREAD

**Issue by 841020** [microsoft/pylance-release#3623]
Type: <b>Bug</b>

pylance says "attrgetter not accessed"

but the terminal doesn't show it
The attrgetter function is actually used on line 321

![pic1](https://user-images.githubusercontent.com/33141341/201581987-07126eff-d1f2-44af-9ba8-b38345222347.png)
![pic2](https://user-images.githubusercontent.com/33141341/201582001-d9f629a8-6b01-4a85-aa7d-e90dbedf4817.png)
![pic3](https://user-images.githubusercontent.com/33141341/201582008-6e75cae7-66ef-4ef1-a9ea-39a83702fab8.png)

Extension version: 2022.11.20
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.34GB free)|
|Process Argv|--crash-reporter-id 64746321-2964-41d9-806d-b1f3e775e20d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30605430
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by erictraut** [comment]
This occurs when the static analyzer (which is what determines whether symbols are accessed) encounters code that is too complex to analyze. This is indicated by the error that states "Code is too complex to analyze; reduce complexity by refactoring...". Code complexity is measured as a combination of [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) and the number of nodes in the code flow graph. As indicated by the error message, you can avoid this situation by refactoring it into subroutines.

**Comment by 841020** [comment]
you got the point , thanks 

![pic4](https://user-images.githubusercontent.com/33141341/201588304-9a215523-11fb-45b0-993c-0ba274280aea.png)
