### ISSUE TITLE
type hint with "Union" operator doesn't work properly

### ISSUE THREAD

**Issue by djccnt15** [microsoft/pylance-release#3624]
## Environment data

-   Language Server version: 2022.11.20 (pyright 470188d0)
-   OS and version: windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10, 3.11

## Code Snippet

I made simple function which returns identity matrix like below

```python
vector = list[float | int]
matrix = list[vector]

def mat_identity(n: int) -> matrix:
    """
    returns n by n sized identity matrix
    """

    I = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    return I
```

## Repro Steps

just type the code

## Expected behavior

obviously the function shouldn't have any problem, as code below returns no error at all

```python
vector = list[float | int]
matrix = list[vector]

m: matrix = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
```

## Actual behavior

pylance warn error like below

```
Expression of type "list[list[int]]" cannot be assigned to return type "matrix"
  "list[list[int]]" is incompatible with "matrix"
    TypeVar "_T@list" is invariant
      "list[int]" is incompatible with "vector"
        TypeVar "_T@list" is invariant
          Type "int" cannot be assigned to type "float | int"
```

**Comment by erictraut** [comment]
Yes, this behavior is correct. To understand why, please review [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md) about static type concepts.
