### ISSUE TITLE
Option to choose severity level of type checking

### ISSUE THREAD

**Issue by MetRonnie** [microsoft/pylance-release#3625]
There is currently `python.analysis.typeCheckingMode` but no way to choose what severity the identified problems should have. (I would like to set them to INFO level rather than ERROR)

**Comment by bschnurr** [comment]
I think you are looking for `python.analysis.diagnosticSeverityOverrides`

see https://github.com/microsoft/pylance-release/blob/main/README.md#settings-and-customization

```json
{
    "python.analysis.diagnosticSeverityOverrides": {
        "reportUnboundVariable": "information",
        "reportImplicitStringConcatenation": "warning"
    }
}
```

**Comment by MetRonnie** [comment]
That does help, thanks, but it means having to add every type-check category as I come across them rather than do it for all of them

**Comment by erictraut** [comment]
You have a couple of choices. You can either start with `typeCheckingMode` set to "basic" and then override all of the rules that emit a warning or error by default. Or you can start with `typeCheckingMode` set to "off", which sets the severity to most diagnostic rules to "none", and enable only the ones you care about by setting them to "information". Here's a [full table](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults) of the diagnostic rules.
