### ISSUE TITLE
Pylance extension details displayed in VS Code are out of date

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3626]
## Environment data
-   Language Server version: 2022.11.21

## Repro Steps
1. Open extensions pane in VS Code
2. Find and select Pylance
3. In the Details tab of the newly opened "Extension: Pylance" window, look for the `python.analysis.autoImportCompletions` config setting

## Expected behavior
The info states that the default value of `python.analysis.autoImportCompletions` is `false`.

## Actual behavior
The info states that the default value of `python.analysis.autoImportCompletions` is `true`.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221131-16-November-2022-PreRelease)
