### ISSUE TITLE
Operator "+" not supported for types "Scalar" and "Literal

### ISSUE THREAD

**Issue by bicofevo** [microsoft/pylance-release#3629]
<h3> Environment data </h3>

-   Language Server version: 2022.11.20
-   OS and version: win32 x64
-   Python version: 3.10.8 (Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import pandas as pd

df = pd.DataFrame({"A": [1,2,3], "B": [1,2,2]})
c = df.groupby(by="B")["A"].transform(sum) == 5

f = df.loc[c, "A"] + 100
```

<h3> Expected behavior </h3>

No problems appeared in the last line

<h3> Actual behavior </h3>

Operator "+" not supported for types "Scalar" and "Literal[100]"
  Operator "+" not supported for types "str" and "Literal[100]"
  Operator "+" not supported for types "bytes" and "Literal[100]"
  Operator "+" not supported for types "date" and "Literal[100]"
  Operator "+" not supported for types "datetime" and "Literal[100]"
  Operator "+" not supported for types "timedelta" and "Literal[100]"
  Operator "+" not supported for types "Timestamp" and "Literal[100]"
  Operator "+" not supported for types "Timedelta" and "Literal[100]"

**Comment by rchiodo** [comment]
Here's a minimal repro:

```
Scalar: TypeAlias = Union[
    str,
    bytes,
    bool,
    int,
    float,
    complex,
]

def foo() -> Scalar:
	return 4

x = foo() + 100
```

**Comment by erictraut** [comment]
A type error is reported for the minimal repro results. That's correct because this is a type violation. Adding `100` to a `str` or `bytes` will result in a runtime error. For example, if you replace `return 4` with `return ""` and then run the code, you will see an exception.

**Comment by rchiodo** [comment]
This is an even simpler repro

```python
def foo() -> str | int:
   return 4

x = foo() + 100
```

Meaning you can't add 100 to something that isn't definitely an int. You first have to do something like so:

```python
import pandas as pd

df = pd.DataFrame({"A": [1,2,3], "B": [1,2,2]})
c = df.groupby(by="B")["A"].transform(sum) == 5
e = df.loc[c, "A"] <- This returns a Scalar, which is a union of str, int, bytes, bool, float, and complex

if isinstance(e, float):
   f = e + 100 
```

**Comment by bicofevo** [comment]
Seems I didn't make it clear. The question is not about why `Scalar` and `int` can't be summed. The question is why in this case `df.loc[c, "A"]` is considered as a `Scalar`, while in the next example it is not:
```python
import pandas as pd

df = pd.DataFrame({"A": [1,2,3], "B": [1,2,2]})
c = df["A"] == 3

f = df.loc[c, "A"] + 100
```

That code is just small change of the line where the mask is defined. It is not generating any type violation error, in contrast to:
```python
import pandas as pd

df = pd.DataFrame({"A": [1,2,3], "B": [1,2,2]})
c = df.groupby(by="B")["A"].transform(sum) == 5

f = df.loc[c, "A"] + 100
```

So, why in the first case pylance is able to understand the type of `df["A"]` is definitely an `int` and doesn't throw type violation error, while in the second case it is not?

**Comment by rchiodo** [comment]
The difference is what pylance thinks the type of 'c' is.

In the second example it's unknown:

![image](https://user-images.githubusercontent.com/19672699/201983936-dd7bbf30-247b-43d3-98fe-199d7a91431f.png)

In the first example, it's a `Series[bool]` so the `df.loc` call is well typed.

![image](https://user-images.githubusercontent.com/19672699/201984113-b91579ad-a647-4051-ae1a-bc87ce7cf0ae.png)

**Comment by rchiodo** [comment]
It looks like the `groupby` is not finding the `__getitem__` call on the result.

**Comment by rchiodo** [comment]
It looks like the latest update to the pandas stubs fixed this:



![Image](https://user-images.githubusercontent.com/19672699/205129231-08b53215-9a0e-48a2-9281-5d8a9201d0f2.png)


That's with the 2022.11.41 prerelease version.
