### ISSUE TITLE
TypeGuard from PEP 647 not working?

### ISSUE THREAD

**Issue by beauxq** [microsoft/pylance-release#3633]
It seems the `TypeGuard` on `callable` isn't working.

## Environment data

Ubuntu 20.04
VSCode 1.73.1
Python 3.10.8
Pylance v2022.11.20

## Code Snippet

```python
from typing import Any, Callable, cast


class A:
    def foo(self) -> None:
        pass


super_class = A
function_name = "foo"

super_func = getattr(super_class, function_name)
assert callable(super_func)       # mouseover callable says it returns TypeGuard[(...) -> object]
super_code = super_func.__code__  # mouseover all these symbols gives "Any"
super_func = cast(Callable[..., Any], super_func)
super_code = super_func.__code__  # mouseover all these symbols gives what I want
```

## Expected behavior

Shouldn't `assert callable(super_func)` narrow the type like `super_func = cast(Callable[..., Any], super_func)`?

## Actual behavior

(in code snippet comments)

**Comment by erictraut** [comment]
Could you provide a complete, self-contained code sample? The sample above refers to symbols like `super_class` and `function_name` that are not defined, so we won't be able to repro the problem you're seeing.

I suspect what is happening is that `super_func` is type `Any`. In general, `Any` is never narrowed. There are a few specific exceptions to this rule that the major Python type checkers have all agreed to — namely, `isinstance`, `issubclass`, and `match`/`case` type narrowing patterns. For all other type guards, an `Any` remains an `Any`. Does that explain the behavior you're seeing?

**Comment by erictraut** [comment]
As requested previously, please provide complete, self-contained code samples. I can only guess at what you mean when you use symbols that are not declared (like `super_func`).

**Comment by beauxq** [comment]
It was complete and self-contained before your last message.

**Comment by erictraut** [comment]
User-defined type guards (as spec'ed in PEP 647) are also exempt from the "`Any` is never narrowed" rule. That explains why `isfunction` acts as is does.

Pyright (the type checker upon which pylance is built) has [built-in type type guard logic](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards) for `callable` that predates the introduction of `TypeGuard`. It is more sophisticated than what can be provided for user-defined type guards. It supports both positive ("if") and negative ("else") narrowing, and it supports intersection types. Its behavior is therefore different from the user-defined type guard behavior seen for `isfunction`. It is not exempt from the "`Any` is never narrowed" rule.

This explains the difference you're seeing between `callable` and `isfunction`. This behavior is expected, and we don't currently have any plans to change it. Doing so will introduce false positive errors in code that currently type checks without errors. You'll need to adjust your code accordingly.

**Comment by beauxq** [comment]
> Doing so will introduce false positive errors in code that currently type checks without errors.

Can you give an example of this?

**Comment by erictraut** [comment]
```python
from typing import Callable

def func(x: Callable[[int], int] | int, param: int = 0) -> int:
    if not callable(x):
        return x
    
    return x(param)
```

This will fail because `x` won't be narrowed to `Callable[[int], int]` in the negative case if we were to apply `TypeGuard` narrowing.

**Comment by erictraut** [comment]
Here's another example that uses an intersection type:
```python
def func2(x: A) -> A | None:
    if callable(x):
        x()
        return x
```

We have test cases in pyright for these cases because existing code relies on these behaviors.

**Comment by beauxq** [comment]
I see.

We have a false positive from this:
```python
from typing import Callable, TypeGuard


def my_callable(o: Callable[[int], int] | int) -> TypeGuard[Callable[[int], int]]:
    return callable(o)


def func(x: Callable[[int], int] | int, param: int = 0) -> int:
    if not my_callable(x):
        return x

    return x(param)
```

**Comment by rchiodo** [comment]
I believe this is expected. See Eric's comment: 

> This will fail because x won't be narrowed to Callable[[int], int] in the negative case if we were to apply TypeGuard narrowing.

I believe this discussion: https://github.com/python/typing/discussions/1013 outlines what would be necessary to support the negative case.
