### ISSUE TITLE
Property of class not determined inside match statement

### ISSUE THREAD

**Issue by lukjoh** [microsoft/pylance-release#3634]
## Environment data

-   Language Server version:  v2022.11.21
-   OS and version:   Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda):   Python 3.11.0

## Expected behavior
If a value can be one of two classes then,
after passing the value through a match statement, 
Pylance should be able to infer whether or not a property exists on the result.

## Actual behavior
Pylance error says the property can be "Unknown"

## Code Snippet

![problem](https://user-images.githubusercontent.com/59101551/202133345-03b83234-916b-48b8-abb9-29ef5c19262f.png)

Here is the same code as text so you can copy and paste:

```python
from random import randint
from typing import Literal, NewType, TypeAlias, Union

class Heads:
    state: Literal['heads'] = 'heads'

class Tails:
    state: Literal['tails'] = 'tails'
    message: str = 'You win'

Coin = Union[
    Heads,
    Tails
]

def toss() -> Coin:
    if randint(0, 1) == 0:
        return Heads()
    else:
        return Tails()

def run():
    coin = toss()
    match coin.state:
        case 'heads':
            pass
        case 'tails':
            print(coin.message)
```

**Comment by erictraut** [comment]
The behavior is "as designed". Type narrowing is supported for the target expression of a `match` statement, but it isn't supported for other subexpressions in the target expression. In your example above, the target expression is `coin.state`. The type of this expression is narrowed, but the subexpression `coin` is not.

Not surprisingly, mypy also has this same limitation for type narrowing in `match` statements.

This narrowing pattern is supported for `if`/`elif` ladders, so if you want to use this sort of "discriminator" approach in your code and would like it to work with type checkers, you can switch to something like this:

```python
def run() -> None:
    coin = toss()
    if coin.state == 'heads':
        pass
    elif coin.state == 'tails':
        print(coin.message)
```
