### ISSUE TITLE
Support hint for inline if statement

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/pylance-release#3635]
Consider typing the following code in VSCode
```python
foo = True
bar = 1 if foo else 0
```
There will be no hint available when typing foo
![image](https://user-images.githubusercontent.com/14952735/202146738-0adbf239-8d06-4fbc-adae-0680bf34044a.png)

Also, the typed foo will not be recognized as variable until the statement after else is written
![image](https://user-images.githubusercontent.com/14952735/202147229-02615582-113b-4624-a01c-a2c50716cd27.png)

**Comment by erictraut** [comment]
I've improved the parser's error recovery in this case so it creates a TernaryNode (with error subnodes) when it is discovers a partial ternary expression. This provides the completion provider with sufficient parse information to supply completion suggestions in this circumstance.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221131-16-November-2022-PreRelease)
