### ISSUE TITLE
Will pylance implement LineCompletion.

### ISSUE THREAD

**Issue by dileepyavan** [microsoft/pylance-release#3640]
Is there a plan to support LineCompletion in pylance?

**Comment by rchiodo** [comment]
What's LineCompletion? Do you have an example?

**Comment by dileepyavan** [comment]
Whole line of code prediction based on current context. For more details, please refer to this intellicodeCompletion extension in VSCode: https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode-completions

**Comment by rchiodo** [comment]
Like github copilot?
https://github.com/features/copilot

**Comment by dileepyavan** [comment]
Yes, you are correct.

**Comment by judej** [comment]
Closing issue since this is what copilot does.
