### ISSUE TITLE
Pylance suggests wrong parameter name

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/pylance-release#3642]
## Environment data

-   Language Server version: 2022.11.32
-   OS and version: Windows_NT x64 10.0.17763
-   Python version: 3.10.4, with pandas 1.4.3
## Code Snippet

```python
import pandas as pd

df = pd.DataFrame()
df.to_csv(lineterminator='\n')
```

## Expected behavior
Mark `lineterminator` as error.

## Actual behavior
No error message is shown, Pylance even suggests me to use `lineterminator`
![image](https://user-images.githubusercontent.com/14952735/202344963-9f6df8aa-a4d3-4714-9348-27964db437a1.png)
Also it's weird that the docstring does not match the signature
![image](https://user-images.githubusercontent.com/14952735/202345301-2bf18b43-64c9-4ca8-b5fc-0680cbdc2540.png)

Pandas 1.5 changes `line_terminator` in `to_csv` to `lineterminator`, but I am using pandas 1.4.3.
I configured the python interpreter correctly, and when ctrl+click on `to_csv` it leads me to the expected method definition (which uses `line_terminator` as parameter), so I have no idea where Pylance found this method with `lineterminator`

**Comment by bschnurr** [comment]
![image](https://user-images.githubusercontent.com/1946977/202539247-f58c768c-9a85-47b2-85f0-66d9ff03331f.png)

You can install a different version of pandas stabs

pip install pandas-stubs==1.4.3.220829

then copy them under the `typings` folder

right clicking on a function and choosing 'Got to Declaration' should now go to your stub.
