### ISSUE TITLE
Exclude platform specific bits from extension bundle

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#3646]
ms-python.vscode-pylance-2022.11.30

Hi, the pylance extension is currently 95MB on disk. I noticed that 66MB of this appears to be platform specific code under: `dist/native/onnxruntime/napi-v3`

Can you use VS Code's [platform specific extension logic](https://github.com/microsoft/vscode-platform-specific-sample) to avoid shipping platform specific bits to other platforms? Doing so should cut the extension's on disk size in half on linux and windows (and a little under half on macOS)

**Comment by rchiodo** [comment]
These files are from intellicode. We use them to read the model in the server. 

One thought was to switch to this: https://www.npmjs.com/package/onnxruntime-web

Need to talk to somebody on intellicode team to see if that would work or not too.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023131-18-January-2023-PreRelease)
