### ISSUE TITLE
When inspecting a stdlib method, VSCode consumes high percentage of CPU and becomes unresponsive or very laggy, possibly due to weird Windows Defender interaction

### ISSUE THREAD

**Issue by rdbisme** [microsoft/pylance-release#3650]
## Environment data

-   Language Server version: 2022.11.30
-   OS and version: Windows 10, Build 18363
-   Python version: 3.10, installed using scoop

## Code Snippet

```python
from zipfile import ZipFile
```

## Repro Steps

Randomly inspecting some stlib methods or classes (e.g. `ZipFile` in the snippet), triggers some sort of scan or indexing from pylance that brings the CPU to ~60-70% for long time and VScode becomes unresponsive. Not sure if it's Windows Defender badly interacting with PyLance and VSCode, but...

https://user-images.githubusercontent.com/8077364/202765071-7a3c2139-f48a-4bbe-9011-40719c44985a.mp4

## Logs

```
XXX
```

**Comment by rdbisme** [comment]
Hello @erictraut, unfortunately this is triggered randomly when clicking on some stdlib object to inspect it. E.g. it can be triggered from the following snippet: 

```
from zipfile import ZipFile
```

than clicking with the right mouse button on `ZipFile` > Go to Definition.

Or also hovering the mouse on some methods of `ZipFile`

The problem is, if I close VScode and open it again. It won't trigger again (I guess because the typesheds for the specific module / class have been already processed). But then it will trigger again on some other stdlib object. It seems something related to populating cache or indexes.

**Comment by rdbisme** [comment]
This is very relatable: https://github.com/microsoft/pylance-release/issues/3632

**Comment by rdbisme** [comment]
I managed to turn Trace on while it's happening: 
[9-Python Language Server.zip](https://github.com/microsoft/pylance-release/files/10043757/9-Python.Language.Server.zip)

**Comment by rdbisme** [comment]
It seems to be rescanning the entire universe in all the virtualenvs of my workspace.

**Comment by rdbisme** [comment]
Another way of triggering it: create a new virtualenv. Switch a Jupyter Kernel to it. That will trigger the scan of all the others virtualenvs (that can be huge)

**Comment by ooliver1** [comment]
May be related to #3554

**Comment by rdbisme** [comment]
Hello, still experiencing this problem. VScode becomes unresponsive and it's basically unusable. Anything I can do to help more?

**Comment by bschnurr** [comment]
can you upload a file with the trace logs? see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by rdbisme** [comment]
@bschnurr Like this: https://github.com/microsoft/pylance-release/issues/3650#issuecomment-1320354310 or something different?

**Comment by rdbisme** [comment]
@judej I don't understand the "waiting for user response" tag. I replied to @bschnurr  and I provided a file with trace logs in https://github.com/microsoft/pylance-release/issues/3650#issuecomment-1320354310. What am I missing?

**Comment by rdbisme** [comment]
[pylance.log.gz](https://github.com/microsoft/pylance-release/files/10066093/pylance.log.gz)

Here's another one while it's happening. Basically PyLance is scanning the entire universe for some reason. And Vscode is unusable.

Any chance we could prioritize this? I can't work...

**Comment by rdbisme** [comment]
[pylance2.log.gz](https://github.com/microsoft/pylance-release/files/10066369/pylance2.log.gz)

**Comment by rdbisme** [comment]
Just as a note, I left the scanning process going all night long and at the morning some apps (e.g. another VScode window) crashed for OOM.

**Comment by rchiodo** [comment]
For me, I only get those messages when I open a file.

**Comment by rchiodo** [comment]
Can you try installing the [insiders](https://code.visualstudio.com/insiders/) build of VS code and just install the python and pylance extensions into it? My guess is one of your other extensions is doing something that's closing and opening files.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by rdbisme** [comment]
Just for reference, I recreated a new workspace from scratch, on the same vscode (not insiders), and the problem vanished.
