### ISSUE TITLE
Import suggestions should be case sensitive

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/pylance-release#366]
![image](https://user-images.githubusercontent.com/179599/93078914-95a92a00-f68b-11ea-86cc-d6d6e73a1df9.png)

Python itself is case sensitive, so I would like import suggestions to be case sensitive as well. Maybe with a setting in case people prefer the current behavior.

**Comment by ThiefMaster** [comment]
Or does this only happen if there is no exact match? If yes, feel free to close this!

**Comment by judej** [comment]
@ThiefMaster, this is expected behavior, import suggestions are case sensitive, but since there was no exact match found in this case (for "unicode"), the fuzzy search results returned what you are seeing.

**Comment by jakebailey** [comment]
I'll also point out that `unicode` is Python 2, and if it's not being resolved (by say importing from `six` or some other compatibility later), we're not going to be able to do anything with it.

**Comment by ThiefMaster** [comment]
Sure, I know that Python 2 is not fully supported - it was just the import where I noticed it. Anyway, if fuzzy and case-insensitive is just a fallback everything is fine :)
