### ISSUE TITLE
No suggestions on last line of cell in notebook

### ISSUE THREAD

**Issue by bschnurr** [microsoft/pylance-release#3660]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by debonte** [comment]
@bschnurr, I can't repro this. Can you? Any particular repro steps required?
