### ISSUE TITLE
Unexpected type warning when passing a TypedDict to args of pydantic.create_model_from_typeddict

### ISSUE THREAD

**Issue by baojd42** [microsoft/pylance-release#3662]
<h3> Environment data </h3>

-   Language Server version: 2022.11.30
-   OS and version: Debian 11.5
-   Python version (and distribution if applicable, e.g. Anaconda): python 3.10.7
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from typing import TypedDict
from pydantic import create_model_from_typeddict

class MyType(TypedDict):
    a: str

_MyType = create_model_from_typeddict(MyType)
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

No errors.

<h3> Actual behavior </h3>

```
Argument of type "Type[MyType]" cannot be assigned to parameter "typeddict_cls" of type "Type[TypedDict]" in function "create_model_from_typeddict"
  "Type[MyType]" is incompatible with "Type[TypedDict]"
  Type "Type[MyType]" cannot be assigned to type "Type[TypedDict]"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

<h3> Logs </h3>

```
XXX
```

**Comment by erictraut** [comment]
This is an apparent bug in pydantic. It is using `TypedDict` in a parameter type declaration. `TypedDict` is a special form and cannot be used in this manner. See PEP 589 for details.

I'll note that the pydantic source contains the following comment that claims that it is a bug in mypy.
```python
def create_model_from_typeddict(
    # Mypy bug: `Type[TypedDict]` is resolved as `Any` https://github.com/python/mypy/issues/11030
    typeddict_cls: Type['TypedDict'],  # type: ignore[valid-type]
    **kwargs: Any,
) -> Type['BaseModel']:
```
Mypy was the reference implementation for PEP 589, so it's safe to say that this usage was not intended by the authors of PEP 589. I don't consider this a bug in mypy or in pyright (the type checker upon which pylance is built). I recommend reporting the issue to the maintainers of pydantic.
