### ISSUE TITLE
duplicate hit or suggest when i installed pylance

### ISSUE THREAD

**Issue by SunYong0821** [microsoft/pylance-release#3663]
i installed only one extension python，then i got pylance etc，but hint or suggest occurce duplicate。
![企业微信截图_20221122142241](https://user-images.githubusercontent.com/7601063/203240164-3ff5d370-c282-4aff-b486-ee45b2e42bcc.png)
When I disable the extension, there is no problem...... how fix it？

**Comment by rchiodo** [comment]
This should be a dupe of #3530 

If you upgrade the Jupyter extension to the latest prerelease, the problem should go away.
