### ISSUE TITLE
Different variable with same name mistakenly highlighted

### ISSUE THREAD

**Issue by herjiict** [microsoft/pylance-release#3664]
## Environment data

-   Language Server version: 2022.11.30 (pyright 04a10583)
-   OS and version: Windows 11 22000.1281 WSL Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6 (pyenv)

## Code Snippet

```python
import argparse


class Report(object):
    report = "foo"

    def write(self, report):
        print(report)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("report")
    args = parser.parse_args()
    # report
    report = Report()
    report.write(args.report)
    print(report.report)

```

## Repro Steps

1. Click the variable `report` in `report = MyReport()` and see only references of that variable get highlighted
2. Click the property `report` in `args.report` and see all tokens with name `report` get hightlighted

## Expected behavior

When the property `report` in `args.report` is clicked, only that token gets highlighted

## Actual behavior

![screenshot](https://user-images.githubusercontent.com/108729710/203268380-7c8b2758-f8bb-4585-926f-627f4024903e.png)

**Comment by rchiodo** [comment]
This is because `args.report` is dynamic. We can't determine if it's a symbol, so it does a text search instead. 

You can verify this by hovering over `args.report`. If it says unbound, or any, this is the designed behavior. Anything that we don't know what the type is, we do a text search instead.
