### ISSUE TITLE
Allow user to custom memory & process limits of Pylance

### ISSUE THREAD

**Issue by Riki-Du** [microsoft/pylance-release#3665]
Hi,
I'm trying the "Auto Import" feature of Pylance and I edited "python.analysis.packageIndexDepths" so that I can auto import every symbol in my project.
![image](https://user-images.githubusercontent.com/53928797/203269114-33a53d9b-905b-4d88-9259-d0eaa024e64c.png)
But I found that when I open the vscode client, it takes so much time to do code analysis and only consumes near 300% CPU.
My vscode server (I'm using remote-SSH in client) runs on a powerful server which has 80 CPUs and 500G memory. So does pylance run faster if I allow it to comsume much more CPUs and memory? If it does, Can you provide an optional in preference to change the resource limitation?

**Comment by rchiodo** [comment]
The option you're adjusting is actually for [3rd party libraries](https://code.visualstudio.com/docs/python/settings-reference#_python-language-server-settings) so it doesn't affect how we search for symbols in your project. 

However, that option does cause us to search much deeper in 3rd party libraries. This will cause a lot of indexing to happen. This indexing is limited by node at the moment though. Node is limited in the amount of memory it can consume and VS code actually controls how this process is started. Pylance wouldn't be able to make this value any higher, so your super fast machine doesn't really have any effect on it.

Sorry
