### ISSUE TITLE
Make import suggestion dropdown more readable

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/pylance-release#367]
![image](https://user-images.githubusercontent.com/179599/93078914-95a92a00-f68b-11ea-86cc-d6d6e73a1df9.png)

- The word "Add" in front of the line actually reduces readability.
- If that dropdown somehow used the editor font (likely a monospace one), and ideally even syntax highlighting, it would be much easier to see what name is being imported from where.

Take an editor line like this for example - it's super clear what you are importing from where:

![image](https://user-images.githubusercontent.com/179599/93079155-f9cbee00-f68b-11ea-9cf9-142844db2728.png)

**Comment by savannahostrowski** [comment]
We've improved consistency between auto-imports and the text in the add import code action suggestions and added quotations to make it a little more clear. 

Unfortunately, VS Code does not support monospaced font or syntax highlighting so we can't do much beyond that at this time. If you'd like to file an issue to their repo, I'm sure they'd welcome the suggestion.
