### ISSUE TITLE
Feature Request: Auto import should suggest all symbols in your project

### ISSUE THREAD

**Issue by youssefm** [microsoft/pylance-release#3670]
At the moment, auto import only seems to suggest symbols for files in your project that happen to be open in VSCode.

I feel like that's a huge limitation. Most developers, including myself, would like to be able to start typing the name of symbols they know exist in their project and be able to auto import those symbols.

This feels like a super basic scenario for Pylance that would get it closer to the amazing experience we have with the Typescript experience in VSCode and with Python in competing IDEs.

@heejaechang  and I had a good discussion about this here: https://github.com/microsoft/pylance-release/issues/3648#issuecomment-1322814937

I would love if this was just the default behavior when you opt in to auto-import, but at the very least there should be a way for users to enable this somehow even if it's not the default behavior.

**Comment by urbpeti** [comment]
I've faced the same issue before and I've just found out that this can be changed in the config. On the extensions, tab click the gear icon and select extension settings. You will find a lot of good options there including a change of this behavior. (I struggeled with auto import before and I've just found that setting there as well).

**Comment by youssefm** [comment]
> I've faced the same issue before and I've just found out that this can be changed in the config. On the extensions, tab click the gear icon and select extension settings. You will find a lot of good options there including a change of this behavior. (I struggeled with auto import before and I've just found that setting there as well).

@urbpeti Can you please elaborate? As far as I know, there is no single configuration that will let you auto import symbols in your project without first opening the files that you want to import from. This is what my configuration looks like:

```
  "python.analysis.autoImportCompletions": true,
  "python.analysis.diagnosticMode": "workspace",
  "python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "depth": 100,
      "includeAllSymbols": true,
      "name": ""
    },
  ],
```

**Comment by heejaechang** [comment]
new option is added `python.analysis.autoImportUserSymbols`.

if set `true`, we will include user symbols in the auto import completion.

**Comment by youssefm** [comment]
Amazing! Thank you @heejaechang, this is going to make a huge difference

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221141-30-November-2022-PreRelease)

**Comment by youssefm** [comment]
@heejaechang @rchiodo @judej 

Thank you all so much for getting this feature in. I've written a blog post about it here if you're interested in promoting it somehow:

https://www.youssefm.com/posts/writing-python-in-vscode

Cheers

**Comment by kevcmk** [comment]
I'm curious, when was this removed?

It is not in Version: 1.86.2 (Universal)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda

**Comment by debonte** [comment]
@kevcmk, can you check `python.analysis.autoImportCompletions`? It is off by default. If you're still having problems, please file a new issue.
