### ISSUE TITLE
PyLance reports syntax error when an integer is next to the else keyword

### ISSUE THREAD

**Issue by ChezCoder** [microsoft/pylance-release#3671]
## Environment data

-   Language Server version: v2022.11.30
-   OS and version: macOS Monterey v12.5.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.7

## Code Snippet

```python
print("Yay")if 1==1else print("Nay")
```

## Repro Steps

1. Paste the code and let PyLance do the work

## Expected behavior

There should be no syntax errors, as this is valid Python.

## Actual behavior

<img width="518" alt="Screen Shot 2022-11-23 at 19 58 51" src="https://user-images.githubusercontent.com/62308406/203671181-7cdb4fa7-9451-43d8-965b-0cff6d489d06.png">

## Logs
No logs

**Comment by erictraut** [comment]
If you run this code in the Python 3.10 or 3.11 interpreter, you will receive a warning indicating: `SyntaxWarning: invalid decimal literal`. So, while this may not result in an exception in the current version of Python, it is [deprecated](https://docs.python.org/3.10/whatsnew/3.10.html#deprecated) and will result in an exception in the future. As such, it makes sense for pylance to emit an error here. You can obviously avoid the error by inserting a space.

**Comment by ChezCoder** [comment]
Oh ok makes sense then, thanks for clarifying.
