### ISSUE TITLE
Pylance reads a lot of data on disk

### ISSUE THREAD

**Issue by lripoche** [microsoft/pylance-release#3673]
## Environment data

-   Language Server version: 2022.11.30
-   OS and version: Ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.15

## Repro Steps

1. Install pylance
2. Restart vscode
3. Run iotop then filter DISK_READ by active (ascending)

## Expected behavior

No disk_read since I don't have any python file open.

## Actual behavior

Pylance reads disk at unusal rate (30-40 mbps) during long periods (few minutes). 

## Logs

Responsible process 
```
 /snap/code/113/usr/share/code/code --ms-enable-electron-run-as-node /home/user/.vscode/extensions/ms-python.vscode-pylance-2022.11.30/dist/server.bundle.js --cancellationReceive=file:40667f7f308cfc23dcb35f691711023703c08b4b0a --node-ipc --clientProcessId=25110
```

**Comment by rchiodo** [comment]
This is by design. When pylance activates it 'indexes' your virtual environment. To do so it needs to read all of the python files in your site-packages folder. 

You can control this by forcing this value to false:

```json
  "python.analysis.indexing": false,
```
