### ISSUE TITLE
Auto import feature breaks after adding another directory to workspace

### ISSUE THREAD

**Issue by diego351** [microsoft/pylance-release#3677]
## Environment data

MacOS 13.0
VSCode Version: 1.73.1
Pylance v2022.11.30
Pylance language server 2022.11.30

settings.json:

```
 "python.analysis.autoImportCompletions": true,
  "python.analysis.indexing": true,
  "python.analysis.packageIndexDepths": [
    {
      "name": "rest_framework",
      "depth": 10,
      "includeAllSymbols": true
    }
  ],
```

## Repro Steps

1. Auto import works
2. File -> Add folder to workspace -> show other directory path (in my case it was 'site-packages')
3. CTRL + SHIFT + P -> Developer Reload Window
4. Now auto import doesn't work
5. Right click on site packages -> Remove folder from workspace
6. CTRL + SHIFT + P -> Developer Reload Window
7. Auto import works back again

## Desired behaviour

I can have many folders added to workspace and have option to mark one directory 'as source root'

**Comment by rchiodo** [comment]
I believe this is by design. Folders in your workspace aren't considered for auto import. We should document that behavior though. I don't see it anywhere in our documentation.

**Comment by diego351** [comment]
@richodo What do you mean it's by design? I don't mean to have auto import hints from my workspace. It's that when I add another folder to the workspace the general auto import feature stops working as in provided repro steps. Am not sure if that helps ;)

**Comment by rchiodo** [comment]
Yes the secondary folder (site-packages) in this case is considered user code. So they're not part of auto import because we only auto import non user code at the moment.

@heejaechang is working on adding a setting to allow user code to be part of auto import though. See this issue:
https://github.com/microsoft/pylance-release/issues/3670

**Comment by diego351** [comment]
I checked and this also happens when I add empty directory as secondary directory to workspace. I don't expect to get auto import from secondary directory. Always from primary, secondary is just for exploring directory tree purpose, no auto import

**Comment by diego351** [comment]
After recent pre release update I can add extra directories without breaking the auto import feature. Great!

**Comment by diego351** [comment]
https://github.com/microsoft/pylance-release/issues/3652 duplicate
