### ISSUE TITLE
Option to set python.analysis.packageIndexDepths  depth globally.

### ISSUE THREAD

**Issue by diego351** [microsoft/pylance-release#3678]
MacOS 13.0
VSCode Version: 1.73.1
Pylance v2022.11.30
Pylance language server 2022.11.30

For now if you want to fully index (deeper than 2 directories deep) installed libraries to get auto import working you have to do something like this in your settings.json for each library:

```
 ],
  "python.analysis.packageIndexDepths": [
    {
      "name": "rest_framework",
      "depth": 10,
      "includeAllSymbols": true
    },
    {
      "name": "django",
      "depth": 10,
      "includeAllSymbols": true
    },
    {
      "name": "factory",
      "depth": 10,
      "includeAllSymbols": true
    }
  ]
```

I would like to have an option to index everything globally, taking the performance hit

# Repro:

1. No setting set or one below:
```
"python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 10,
      "includeAllSymbols": true
    }
  ]
```
1. pip install django-rest-framework
2. Type ListAPIView, no completition
3. Change setting to one below

```
 "python.analysis.packageIndexDepths": [
    {
      "name": "rest_framework",
      "depth": 10,
      "includeAllSymbols": true
    }
]

```
4. Type ListAPIView -> Correct quick fix available
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1809191/204519172-e2c33e10-8263-4ea2-98d1-d248432b0198.png">

# Desired behaviour:

I don't want to have to define each library in settings.json to have auto import feature from them. My dream is to have 'index everything' option. Thank you!

**Comment by bschnurr** [comment]
to change the default set name to ""

**Comment by diego351** [comment]
@bschnurr If I do 
```
"python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 10,
      "includeAllSymbols": true
    }
  ]
```

my library competitions doesn't work at all

**Comment by diego351** [comment]
Repro:

1. No setting set or one below:
```
"python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 10,
      "includeAllSymbols": true
    }
  ]
```
1. pip install django-rest-framework
2. Type ListAPIView, no completition
3.Change setting to one below

```
 "python.analysis.packageIndexDepths": [
    {
      "name": "rest_framework",
      "depth": 10,
      "includeAllSymbols": true
    }

```
4.Type ListAPIView -> 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1809191/204519172-e2c33e10-8263-4ea2-98d1-d248432b0198.png">

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.11.42, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20221211-1-December-2022-PreRelease)

**Comment by diego351** [comment]
I can confirm, that now

```
"python.analysis.packageIndexDepths": [
    {
      "name": "",
      "depth": 10,
      "includeAllSymbols": true
    }
  ]
```

works correctly, thanks a lot!

**Comment by heejaechang** [comment]
@diego351 I just checked, and it worked as expected. since you are searching for depth 10 for every module installed, it will take long time to index, make sure you wait for it to finish.

once indexing is finished, you will be able to see `Indexing finished` in `Python Language Server` in output tab. 

For me, with only a few packages installed, enabling depth 10 for all modules took almost 1 min on my dev machine.
