### ISSUE TITLE
Any way to get the behavior of python.linting.ignorePatterns?

### ISSUE THREAD

**Issue by marknelson** [microsoft/pylance-release#368]
I have a submodule of code that I have no control over, and it generates thousands of problems. I can't figure out how to exclude it from Pylance linting.

Setting python.analysis.diagnosticMode to openFilesOnly is as close as I can get to a reasonable workaround, but it is less than completely satisfying for various reasons.

This is submitted as a question, not an issue, because I have to believe that my ignorance is the problem - it seems like this is something so obvious that it is being dealt with properly somewhere, somehow, by more intelligent people than me.

**Comment by erictraut** [comment]
Pylance is based on the Pyright type checker, which supports some additional configuration options that are not (currently) exposed via VS Code settings. You can create a "pyrightconfig.json" file at the top level of your workspace and include an "ignore" section that lists the subdirectories you'd like Pyright/Pylance to ignored. All diagnostics in those files will be suppressed. For more details about the "pyrightconfig.json" file, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

**Comment by marknelson** [comment]
@erictraut thanks, trying this with a pyrightconfig.json that has nothing in it except an ignore specification. I'm hoping that all the other settings in use by vs code are unchanged by the presence of the file.
