### ISSUE TITLE
Pylance doesn't prevent this (my_var = 5 + "hello")

### ISSUE THREAD

**Issue by MotasemZiad** [microsoft/pylance-release#3680]
<h3> Environment data </h3>

-   Language Server version: 2022.11.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
my_var = 5 + "hello" 
print(my_var)
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by erictraut** [comment]
If you set "python.analysis.typeCheckingMode" to "basic", pylance will flag this as a type error.

![Screenshot 2022-11-27 at 6 20 29 AM](https://user-images.githubusercontent.com/7040122/204140150-a754c487-673c-4577-b4b6-a8dfb138739c.png)

**Comment by MotasemZiad** [comment]
@erictraut Thanks a lot, What about other hints? Could you send me a reference for setting up an excellent python environment linting technique?
