### ISSUE TITLE
Feature: Support LSP request command

### ISSUE THREAD

**Issue by NWYLZW** [microsoft/pylance-release#3681]
**Is your feature request related to a problem? Please describe.**
I am developing an [extension](https://github.com/NWYLZW/vscode-comment-queries) based on the `LSP` of the `VSCode`. This extension will read the `quickInfo` information provided by the `LSP` in the corresponding row and column, and display it in the code in the way of `inlayHints`.

I already support `TypeScript`, and now I support `Python`, But I found that I could not request `LSP` to get `quickInfo` information through `Pylance` or `Pyright`.

An instruction is provided in [`vscode/typescape-language-feature`](https://github.com/microsoft/vscode/blob/d65e6e6b2f2525910648e295425754c83e1fcee2/extensions/typescript-language-features/package.json#L65) to obtain the corresponding data from `LSP`.

**Describe the solution you'd like**

The instruction request `LSP` is supported in `Pyright` and `Pylance`.

**Additional context**

The command cannot be executed through the `runCommands` exported by `Pylance` (in fact, I don't know what the API should look like).
<img width="952" alt="image" src="https://user-images.githubusercontent.com/51358815/204126093-3513e24d-0df3-4a86-bd29-ce7ebc128a56.png">

support TypeScript
<img width="640" alt="image" src="https://user-images.githubusercontent.com/51358815/204125783-a14c98c5-8185-4910-b6b4-63398df374cb.png">

unable support Python
<img width="624" alt="image" src="https://user-images.githubusercontent.com/51358815/204125810-3e258b26-ca73-4942-a9d4-aae1c9a22e57.png">

**Comment by rchiodo** [comment]
@NWYLZW are you trying to execute a command on the server?

That would be this message here:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_executeCommand

And you'd have to know what commands the pylance server supports. It's not publicly exposed.

Your original question sounded like you wanted inlay hint information. That would be this message:

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint

My guess is that Typescript has a 'quickInfo' command that is custom to the typescript server. Pylance only supports the messages from the LSP.
