### ISSUE TITLE
Two instances of Python extension running

### ISSUE THREAD

**Issue by cmditch** [microsoft/pylance-release#3683]
Type: <b>Bug</b>

It almost seems as if the Python extension is running two daemons. 

I get duplicate intellisense code completion suggestions (e.g. same function(s) will always appear twice); two function type inlay suggestions (e.g., "def thing() -> None -> None"); when renaming a file it says something along the lines of "2 extensions want to apply changes if you rename this file...". If I restart the editor the error can sometimes go away briefly, but it very often comes back.

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1094-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|. --crash-reporter-id 508b0cbf-2a4d-4409-a2bd-ffb8926b9fea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1094-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (2 x 2793)|
|Memory (System)|3.84GB (2.26GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

<img width="491" alt="image" src="https://user-images.githubusercontent.com/15849320/204186027-ccecfa87-427a-4913-8940-701cf382871a.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/15849320/204186150-21798aa2-d3ce-4f90-bba4-6123a194ec2f.png">

**Comment by rchiodo** [comment]
@cmditch are you opening any jupyter notebooks? This sounds like this bug here:
https://github.com/microsoft/pylance-release/issues/3027#issuecomment-1312148181

**Comment by rchiodo** [comment]
Did you try updating the jupyter extension to the prerelease version to see if the problem goes away?

**Comment by cmditch** [comment]
I just tried the pre-release of the Jupyter extension `v2022.11.1003301027`. 
![image](https://user-images.githubusercontent.com/15849320/204355304-bc18d798-8603-4c0b-839a-927697283a12.png)

Getting this error in the console `[Extension Host] extension activation failed TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function`

Fwiw, setting `"python.pylanceLspNotebooksEnabled": true` has fixed the issue for me for the time being.

**Comment by rchiodo** [comment]
Oh that probably means the jupyter extension requires a newer VS code to run.

**Comment by rchiodo** [comment]
But the setting being true means it's the same issue. Thanks.
