### ISSUE TITLE
Member "iter_rows" unknown for openpyxl worksheet

### ISSUE THREAD

**Issue by gmckeown** [microsoft/pylance-release#3689]
Seems similar to issue [#947 ](https://github.com/microsoft/pylance-release/issues/947) though installing openpyxl-stubs doesn't resolve the problem in this case.

## Environment data

-   Language Server version: 2022.11.30 (pyright 04a10583)
-   VSCode version: 1.73.1
-   OS and version: Windows 10 (19044.2251)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2 (python.org)

## Code Snippet

```python
from openpyxl import load_workbook

wb = load_workbook("test.xlsx")
# ws = wb.worksheets[0]
ws = wb["Sheet2"]

for row in ws.iter_rows(min_row=2):
    group_name = row[8].value
```

## Repro Steps

If using `wb.worksheet[0]` there's no problem, but using `wb["Sheet2"]` results in:

```Cannot access member "iter_rows" for type "Chartsheet"
Member "iter_rows" is unknown 
Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

## Expected behavior

Code works just fine in both cases, so wouldn't expect the red underline.

## Actual behavior

Red underline and above error when using `wb["Sheet2"]`

## Logs

[pylance_log.txt](https://github.com/microsoft/pylance-release/files/10112768/pylance_log.txt)

**Comment by Questionsdenombres** [comment]
Using typing with openpyxl may be tricky and pyright/pylance helps a lot:

![image](https://user-images.githubusercontent.com/47284986/205896973-78b09cf2-2f9f-482d-a119-d7a2e15c68c4.png)
![image](https://user-images.githubusercontent.com/47284986/205897282-4a655abf-5b00-4e10-a96a-c944a79e48c5.png)

Using the `worksheets` property of a `Workbook` instance `ws = wb.worksheets[0]` returns an instance of `Worksheet | ReadOnlyWorksheet`. Both have the `iter_rows` attribute.

However a `Workbook` can also contain a `Chartsheet` that doesn't have the `iter_rows` attribute.
`wb["Sheet2"]` returns an instance of `Chartsheet | Worksheet | ReadOnlyWorksheet`.

Conclusion: 
- pylance/pyright is correct.
- Possible:  use `Any` (workaround 1) or `cast` (workaround 2) to restrict the variable to types having the `iter_rows` attribute (see below).

I understand that typing is a feature that was added to openpyxl, which is not designed and developed from start with strong typing.

```python
from typing import cast, Any
from openpyxl.worksheet._read_only import ReadOnlyWorksheet  # https://openpyxl.readthedocs.io/en/latest/optimized.html#read-only-mode
from openpyxl.worksheet._write_only import WriteOnlyWorksheet  # https://openpyxl.readthedocs.io/en/latest/optimized.html#write-only-mode
from openpyxl.worksheet.worksheet import Worksheet  # https://openpyxl.readthedocs.io/en/stable/api/openpyxl.worksheet.worksheet.html
from openpyxl.chartsheet.chartsheet import Chartsheet  # https://openpyxl.readthedocs.io/en/latest/_modules/openpyxl/chartsheet/chartsheet.html#Chartsheet

ws: Any = wb["Sheet2"] # Workaround 1
ws = cast(Worksheet|ReadOnlyWorksheet, wb["Sheet2"]) #  # Workaround 2
```

**Comment by Questionsdenombres** [comment]
In other words: some openpyxl methods return mixed typed instances which some have little or very specific usage and methods. Hence, they are nightmares for python strict typing developers, which I am. I hope in some future releases such types could be ousted from the commonly used methods, either by refactoring some code or by using appropriate overload typing stubs. This is probably not an easy job with strong regression risk.

Probably you are a user only interested with raw data in workbook. You never hear and don't really care about [Charsheet](https://openpyxl.readthedocs.io/en/latest/charts/chartsheet.html). But this Charsheet class makes you code fail here.

Pandas also has many strict typing issues, with stubs indicating that some classes are generic while they are not defined as such - see #3445.

**Comment by gmckeown** [comment]
Merci beaucoup @Questionsdenombres! Great analysis and a very helpful response :)

I have now used cast to successfully work around the issue.

**Comment by bschnurr** [comment]
also see typeguards
https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards

```python
from openpyxl import load_workbook
from openpyxl.chartsheet import Chartsheet

wb = load_workbook("test.xlsx")
# ws = wb.worksheets[0]
ws = wb["Sheet2"]

assert not isinstance(ws, Chartsheet)

for row in ws.iter_rows(min_row=2):
    group_name = row[8].value
```
