### ISSUE TITLE
IntelliSense doesn't autocomplete modules in workspace subfolders in unsaved Jupyter notebooks

### ISSUE THREAD

**Issue by torext** [microsoft/pylance-release#3692]
<h3> Environment data </h3>

-   Language Server version: 2022.11.30
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.8, Miniconda
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: off

<h3> Repro Steps </h3>

1. Create a new workspace folder `myworkspace` with the following structure:
```
myworkspace/
    subfolder/
        myclasses.py
```
2. Put the following inside `myclasses.py`:
```
class myclass:
    pass
```
4. Open a new blank Jupyter notebook using **Create: New Jupyter Notebook** from the command palette and _do not save it_.
5. Start typing `from subfolder.myclas`

<h3> Expected behavior </h3>

I should get an autocompletion suggestion for `from subfolder.myclasses`.

<h3> Actual behavior </h3>

No suggestions are given, even after pressing `Ctrl + Space` to force suggestions. Finishing typing the command

`from subfolder.myclasses import myclass`

doesn't give autocomplete suggestions at any point, but executes fine when the cell is run. Once the notebook is saved however autocomplete suggestions work as expected.

This is a duplicate of https://github.com/microsoft/pylance-release/issues/3177 which however seems to have gone under in relation with past similar issues regarding _saved_ notebooks.

**Comment by bschnurr** [comment]
Thank for bringing this up again, but closing this duplicate

**Comment by bschnurr** [comment]
appears to be working in Pylance v2023.3.30
