### ISSUE TITLE
Highlighting issue on python code

### ISSUE THREAD

**Issue by davfsa** [microsoft/pylance-release#370]
## Environment data

-   VS Code version: 1.49
-   Extension version (available under the Extensions sidebar): 2020.8.108011 (can reproduce with any version after 2020.8.105369)
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Relevant/affected Python packages and their versions: None
-   Relevant/affected Python-related VS Code extensions and their versions: None
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

![image](https://user-images.githubusercontent.com/29100934/93127035-7e8b2c00-f6cd-11ea-88ff-d3714a374845.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/29100934/93126872-3b30bd80-f6cd-11ea-8ce5-e4b79731a75c.png)

## Steps to reproduce:
Any code should do, but this just helps see most of what it affects
```py
class Test:
    def test(a : str, b : str):
        print(a + b)

test = Test()

test.test("Hello World")
```

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - control'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
> conda --version
> conda info --json
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/coding/hikari/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Pylance language server.
Python interpreter path: ./.venv/bin/python
> ~/coding/hikari/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/coding/hikari/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> pyenv root
> pyenv root
> pyenv root
> ~/coding/hikari/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/coding/hikari/hikari/utilities/ux.py
cwd: ~/coding/hikari
> ~/coding/hikari/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/pyvsc-run-isolated.py flake8 --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s ~/coding/hikari/hikari/utilities/ux.py
cwd: ~/coding/hikari
##########Linting Output - flake8##########
0
> conda --version
> ~/coding/hikari/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.8.105369/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir ~/coding/hikari -s --cache-clear -c pytest.ini tests
cwd: ~/coding/hikari
> pyenv root
> pyenv root
> pyenv root
```

</p>
</details>

**Comment by jakebailey** [comment]
See #323. This is currently intended behavior; tokens are highlighted based on their semantic meaning and your theme provides semantic highlighting support, coloring these characters as you see. We have no control over the colors themselves. Previously this was done via a TextMate profile which had a different scheme. It's possible we can can improve this to emulate some of that old behavior, but that is covered in #323.

If you don't like this semantic highlighting, you can disable it wholesale for python by setting:

```json
{
    "[python]": {
        "editor.semanticHighlighting.enabled": false
    }
}
```

**Comment by jaymegordo** [comment]
Is there a way to disable _specific_ highlight scopes, eg disable "class", and let it fall back to the textmate scopes?

**Comment by jakebailey** [comment]
The only difference that specific option would make would be to not show uses of classes as "class", which doesn't seem like it'd be very useful. Why would you be interested in disabling specific scopes? Is there some scope that doesn't look "right" compared to the old TextMate profile? If so, we'd appreciate a new issue describing the difference so we can take a look.

Note that we already analyze files for diagnostics in the same thread; we get this info for free. It's unlikely to improve performance, if that's what you were looking to help.

**Comment by jaymegordo** [comment]
@jakebailey well I think the real issue I'm getting at is that the semantic options aren't as comprehensive as the textmate rules.

In the `class` example: with textmate things like `dict` can be broken out with `support.type.python`, but

 with the semantic options EVERY instance of any class (dict, list MyClass, etc) has to be colored the same.

Assuming the semantic options don't plan to be as comprehensive as textmate, it would be useful to disable a specific rule to let the highlighting fall back to textmate, if that makes sense?

I can definitely open a separate issue if that sounds appropriate.

<img width="548" alt="Screen Shot 2020-10-06 at 16 06 51" src="https://user-images.githubusercontent.com/29611875/95269439-3ce23280-07ee-11eb-9b03-bd14d0cb86f3.png">

**Comment by jakebailey** [comment]
Yes, I'd make a new issue for that.
