### ISSUE TITLE
Go to definition by python module path in string

### ISSUE THREAD

**Issue by diego351** [microsoft/pylance-release#3700]
MacOS 13.0
VSCode Version: 1.73.1
Pylance v2022.11.30
Pylance language server 2022.11.30

Django heavily uses python module paths in strings for configuration.

settings.py
```
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
```
Another example:
```
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
]
```
urls.py
```
 url(r"^transmissions", include("transmissions.urls")),
```

I would like to have option to go to the definition by these strings

**Comment by rchiodo** [comment]
Can you give an example on where you'd go to definition? Do you mean where you're using say `INSTALLED_APPS[3]`?

**Comment by diego351** [comment]
I agree that while classes paths are fairly obvious in terms of behaviour, for non project directories (majority of cases) it's more complicated. Ideal world scenario would be showing the library directory somehow in the file explorer, perhaps as separate folder in workspace?

**Comment by rchiodo** [comment]
@djego351 I'm sorry but I don't think I understand what it is you're asking for. Goto definition on what exactly?

**Comment by diego351** [comment]
@rchiodo Sorry, when I go to definition of `django.middleware.security.SecurityMiddleware` I want to go to definition of SecurityMiddleware sitting in  `site-packages/django/middleware/security.py`

**Comment by rchiodo** [comment]
Ah okay, so you want special functionality for strings in general or is there some other way for us to identify these are actually package names?

**Comment by diego351** [comment]
I'm thinking about it now. Not really much more than optionally dot separated words. Eh, that might be dirty.

**Comment by rchiodo** [comment]
Are these strings always in a settings.py file? Maybe we could use that to filter it down?

Strings in settings.py that contain '.' in them and no spaces or other punctuation

**Comment by diego351** [comment]
@rchiodo Not always in settings.py unfortunately, but MVP for settings.py would be 90% effect I think

**Comment by diego351** [comment]
Works beautifully! Thanks you!
