### ISSUE TITLE
`Fix All` command no longer removes unused imports

### ISSUE THREAD

**Issue by torext** [microsoft/pylance-release#3703]
<h3> Environment data </h3>

-   Language Server version: 2022.11.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.8, Anaconda
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: off

<h3> Repro Steps </h3>

1. Create a new `.py` file and import some packages. Possibly add some random code that doesn't use these packages.
2. Issue the `Fix All` command from the command palette.

<h3> Expected behavior </h3>

All the unused imports should be removed. This is used to be the case with Pylance 2022.11.30.

<h3> Actual behavior </h3>

No imports get removed and, assuming no other issues in the code, the `No fix all action` bubble appears at the cursor.

**Comment by debonte** [comment]
@torext, we changed the behavior of our `fixall` actions from opt-out to opt-in in [2022.11.31](https://github.com/microsoft/pylance-release/releases/tag/2022.11.31). Enabling all of them when `source.fixAll` was enabled/executed caused too much confusion. Here are a couple of examples, but there were others: https://github.com/microsoft/pylance-release/issues/3144, https://github.com/microsoft/pylance-release/issues/3436

Pylance's `fixall` actions can now be enabled via the `python.analysis.fixAll` setting. For example:

```json
"python.analysis.fixAll": ["source.unusedImports"]
```

**Comment by judej** [comment]
@torext, assuming this restores the functionality you were looking for. If not, please reopen this issue.
thanks
