### ISSUE TITLE
Pylance forgets some variables are TypeVars

### ISSUE THREAD

**Issue by Anonymous-Stranger** [microsoft/pylance-release#3705]
## Environment data

-   Language Server version: v2022.11.40
-   OS and version: Ubuntu 22.04.1 LTS running via WSL 1.0.0.0 in Windows 11 version 22H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0

## Code Snippet

```python
from dataclasses import dataclass
from typing import Generic, TypeVar, Union


NatExpr = Union['Add[NatExpr]', 'Sub[NatExpr]', 'Mul[NatExpr]']
IntExpr = Union['Add[IntExpr]', 'Sub[IntExpr]', 'Mul[IntExpr]']
RealExpr = Union['Add[RealExpr]', 'Sub[RealExpr]', 'Mul[RealExpr]']

ExprT = TypeVar('ExprT', NatExpr, IntExpr, RealExpr)


# Expression base classes

@dataclass
class UnaryExpr(Generic[ExprT]):
    x: ExprT


@dataclass
class BinaryExpr(Generic[ExprT]):  
#                        ^^^^^ Type argument for "Generic" must be a type variable -- Pylance
    x: ExprT
    y: ExprT


# -- Numeric expressions

@dataclass
class Add(Generic[ExprT], BinaryExpr[ExprT]): pass


@dataclass
class Sub(Generic[ExprT], BinaryExpr[ExprT]): pass


@dataclass
class Mul(Generic[ExprT], BinaryExpr[ExprT]): pass
#                 ^^^^^ Type argument for "Generic" must be a type variable -- Pylance
```

## Expected behavior

No type errors.

## Actual behavior

Errors marked in comments above -- but sometimes they move to other classes. It's as if Pylance is repeatedly remembering and forgetting that ExprT is a TypeVar.

If you remove all of the constraints in the TypeVar declaration, `ExprT = TypeVar('ExprT')`, the errors go away.

If you remove one of the constraints in the TypeVar declaration, e.g, `ExprT = TypeVar('ExprT', NatExpr, RealExpr)`, sometimes you see errors, sometimes you don't.

## Logs

Log file was too large to include in issue below are the first few lines:
```
[Info  - 4:47:45 PM] (27011) Pylance language server 2022.11.40 (pyright 45344736) starting
[Info  - 4:47:45 PM] (27011) Server root directory: /home/akash/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.40/dist
[Info  - 4:47:45 PM] (27011) Starting service instance "_Test"
[Info  - 4:47:45 PM] (27011) Notebook support: LSP
[Info  - 4:47:45 PM] (27011) Interactive window support: LSP
[Info  - 4:47:45 PM] (27011) No configuration file found.
[Info  - 4:47:45 PM] (27011) No pyproject.toml file found.
[Info  - 4:47:45 PM] (27011) Setting pythonPath for service "_Test": "/bin/python3.11"
[Warn  - 4:47:45 PM] (27011) stubPath /home/akash/programming/python/_Test/typings is not a valid directory.
[Info  - 4:47:45 PM] (27011) Assuming Python version 3.11
[Info  - 4:47:45 PM] (27011) Assuming Python platform Linux
[Info  - 4:47:45 PM] (27011) Search paths for /home/akash/programming/python/_Test
[Info  - 4:47:45 PM] (27011)   /home/akash/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.40/dist/typeshed-fallback/stdlib
[Info  - 4:47:45 PM] (27011)   /home/akash/programming/python/_Test
[Info  - 4:47:45 PM] (27011)   /home/akash/programming/python/_Test/typings
[Info  - 4:47:45 PM] (27011)   /home/akash/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.40/dist/typeshed-fallback/stubs/...
[Info  - 4:47:45 PM] (27011)   /home/akash/.vscode-server/extensions/ms-python.vscode-pylance-2022.11.40/dist/bundled/stubs
[Info  - 4:47:45 PM] (27011)   /usr/lib/python3.11
```
[pylance_log.txt](https://github.com/microsoft/pylance-release/files/10144631/pylance_log.txt)

**Comment by erictraut** [comment]
You have created a cyclical dependency. You've defined type variables in terms of classes that use those same type variables. You'll need to eliminate the cycle if you want this to work with pyright (the type checker that underlies pylance).

**Comment by Anonymous-Stranger** [comment]
So if I've understood you correctly: inductive type definitions, including my snippet, violate pyright's type semantics?

Do they also violate Python's type-hint semantics?
I've noticed mypy does not report an error, so maybe I should post a bug report there?

**Comment by erictraut** [comment]
Different type checker architectures will handle circular definitions in different manners. Mypy is a multi-pass type checker and is able to deal with some circular dependencies that pyright does not. Pyright uses a just-in-time (lazy) approach for type checking, which is much more efficient and appropriate for powering language servers like pylance.

**Comment by Anonymous-Stranger** [comment]
Ah that makes sense -- thanks so much for answering all my questions!
