### ISSUE TITLE
always make a yellow line after I import any modules even if the module is in my imported packages , I want to know the solution of this problem

### ISSUE THREAD

**Issue by atef7534** [microsoft/pylance-release#3707]
<h3> Environment data </h3>

-   Language Server version: 2022.11.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by judej** [comment]
@atef7534, I am guessing that you are talking about the diagnostic squiggly lines that appear under the `import x from y` statement. 

Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.
