### ISSUE TITLE
Type of stdlib types.coroutine is incorrect

### ISSUE THREAD

**Issue by gaohuazuo** [microsoft/pylance-release#3716]
## Environment data

-   Language Server version: v2022.11.40
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

```python
import types

class A: pass
class B:
    b = None

@types.coroutine
def f():
    x: B = yield A()
    return x

async def g():
    b = await f()
    b.b # Cannot access member "b" for type "A"
```

Looks like the problem comes from `types.coroutine` having a wrong type. Pylance think it is

```
coroutine(func: (**_P@coroutine) -> Generator[R@coroutine, Any, Any]) -> ((**_P@coroutine) -> Awaitable[R@coroutine])
```

but actually it should be

```
coroutine(func: (**_P) -> Generator[Y, S, R]) -> ((**_P) -> Awaitable[R])
```

Note that `R` is the 3rd type parameter of `Generator`, not the 1st one.

For reference, here is the [definition](https://docs.python.org/3/library/typing.html#typing.Generator) of `Generator`

**Comment by erictraut** [comment]
The `types.coroutine` type definition comes from the typeshed project, so if you think that there's a bug in `types.pyi`, you can report the problem [here](https://github.com/python/typeshed/issues). Pylance (and other Python static type analysis tools like mypy) consume the stubs from typeshed, so any fix would need to be done there.

Here's the type definition of `coroutine` in `types.pyi` currently:
```python
def coroutine(func: Callable[_P, Generator[_R, Any, Any]]) -> Callable[_P, Awaitable[_R]]: ...
```

I think pylance is correctly applying this type definition.

**Comment by gaohuazuo** [comment]
Thanks for the redirection. Indeed, changing the relevant line in `types.pyi` fixes the problem.

(`types.pyi` is located at `~/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2022.11.40/dist/typeshed-fallback/stdlib/types.pyi`, In case someone might find it helpful)
