### ISSUE TITLE
Double rename (F2) cause source code mess up in a python file

### ISSUE THREAD

**Issue by 101viktor101** [microsoft/pylance-release#3718]
The editor mess up python code, in case of you do double rename without save between them.

## The VSC version what I use
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

Python version: v2022.19.13251009 Pre-Release 
(The Release version also reproduce this behaviour)

## Steps to reproduce

1. Create .py file with the following content.
```
class MyClass:
    my_class_variableNew = 1234

    def writeoutName(name):
        print('Name: ' + name)

print(MyClass.my_class_variableNew)
MyClass.my_class_variableNew = 4321
```

2. Stand cursor to **MyClass** in the first row.
3. Press F2
4. Type new name **MyClassNew** and press enter.

The result:
```
class MyClassNew:

    my_class_variableNew = 1234



    def writeoutName(name):

        print('Name: ' + name)



print(MyClassNew.my_class_variableNew)

MyClassNew.my_class_variableNew = 4321

```
5. Stand the cursor to **my_class_variableNew** in the third row.
6. Press F2
7. Type **my_class_variable** as new name and press enter.
The result:
```
class MyClassNewN

ew:




    my_class_variableNew = 1234








    def writeNewoutName(name):


New


        print('Name: ' + name)



print(MyClassNew.my_class_variableNew)

MyClassNew.my_class_variableNew = 4321


```

**Comment by rchiodo** [comment]
Thanks for the issue.  I can't seem to reproduce it though:


![Image](https://user-images.githubusercontent.com/19672699/211083622-2759a990-a965-470e-963d-470b624275b9.gif)



Can you make sure you have the latest pylance release? As of me typing this, that should be 2023.1.10



![Image](https://user-images.githubusercontent.com/19672699/211083328-d5f38f59-96e7-4c41-9eed-75fef4e3729c.png)
