### ISSUE TITLE
Investigate `dataclass_transform` use for Django models

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3720]
- What can `dataclass_transform` do, as is?
- Could we extend `dataclass_transform` to help in Django scenarios without requiring drastic API changes?
- Could whatever we do here be applied to other ORMs such as SQLAlchemy?

**Comment by rchiodo** [comment]
Would django maybe be able to do like pydantic did and have the 'id' field for the metaclass? (https://github.com/pydantic/pydantic/pull/2721/files)

Maybe that doesn't work because the 'id' field can be overwritten by the user.

**Comment by debonte** [comment]
I don't see a way for `dataclass_transform` to help with the issues in #3701 or with the issues (extra code required) called out in https://www.youtube.com/watch?v=Lz4I7rFmFdY.

Perhaps it could be used to help validate the kwargs provided to `__init__` on model classes? That's not something we'd need to be involved with though.
