### ISSUE TITLE
Support "Move to new file" action

### ISSUE THREAD

**Issue by pokey** [microsoft/pylance-release#3724]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
In Typescript, there is an action called "move to a new file", which

- moves a function / class / type to a new file,
- carries any imports with it,
- removes imports from the original file which are no longer used
- adds an import to the original file to get the moved declaration

It would be great if this action were available in Python

**Additional context**
N/A

**Comment by heejaechang** [comment]
this is done now.
