### ISSUE TITLE
return type "Never" cause "Code not reachable". but work well

### ISSUE THREAD

**Issue by wbfw109** [microsoft/pylance-release#3728]
## Environment data

-   Language Server version: v2022.11.40 or v2022.12.11 (pre-release)
-   OS and version: Windows 11, Version 21H2 (OS Build 22000.1219)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0, poetry

## Code Snippet

```python
from typing import Never
class Foo:
    def main(self) -> Never:
        print("Foo")        

Foo().main()
print("Bar")
```

## Repro Steps

1. Pylance shows from line 'print("Bar")' including lower lines: Code is unreachable
2. I ignore this, and run code.  
3. when I change return type of main() as "None" rather than "Never", Pylance not shows that message.
4. run code.

## Expected behavior (output)
Foo
Bar
Foo
Bar
## Actual behavior (output)
Foo
Bar
Foo
Bar

## Logs

```
None
```

**Comment by debonte** [comment]
Pylance's behavior here is correct. When explicit type annotations are provided, Pylance honors them. A return type of `Never` indicates that the function never returns. For example, perhaps it loops forever or always raises an exception. So it is correct that code after a call to such a function would be unreachable.

**Comment by debonte** [comment]
Btw, if you set Pylance's `python.analysis.typeCheckingMode` setting to `basic` or `strict`, it will warn you that there's a problem with `main`. It marks the `Never` return type with a `reportGeneralTypeIssues` diagnostic with the following message: 
```text
Function with declared type of "NoReturn" cannot return "None"
```
