### ISSUE TITLE
False positive '"yield" not allowed outside of a function' when using yield in lambda in top-level code

### ISSUE THREAD

**Issue by monotony113** [microsoft/pylance-release#373]
## Environment data

-   Language Server version: v2020.9.4
-   OS and version: macOS 10.15.6
-   Python version: Python 3.8.1

## Expected behaviour

Writing a lambda function containing yield expressions in top-level code should be considered valid syntax.

## Actual behaviour

Pylance reports `"yield" not allowed outside of a function` for the yield expression.

## Code Snippet / Additional information

Can be reproduced simply with

```python
lambda: (yield)
```

**Comment by erictraut** [comment]
Thanks for the bug report. I didn't realize that yield statements could be used within lambdas. I've updated the code to not emit an error in this case. This fix will be in the next release of pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.5, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202095-16-september-2020
