### ISSUE TITLE
when user has a module that has the same name as stdlib module, doc string shows one from stdlib

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#3733]
let's say user has `random.py` at the root of workspace.

and has

```python
from .random import *
```

the `.random` is supposed to refer `random.py` at the root rather than one in the stdlib. 

so, when user hovers the `.random`, it shouldn't show doc string for `stdlib`

But currently, it shows one from the stdlib
![image](https://user-images.githubusercontent.com/1333179/206284758-5800d25a-5015-490c-a12b-2d8b359e1be6.png)

instead, it shouldn't show any docstring.

by the way, if user `random.py` has its own doc string, then pylance shows user's docstring correctly. this bug is only when user doesn't have its own module level doc string.

**Comment by heejaechang** [comment]
related to https://github.com/microsoft/pylance-release/issues/3725

**Comment by judej** [comment]
looks fixed now


![Image](https://github.com/microsoft/pylance-release/assets/547753/0e825356-ae28-429a-bc2a-801c36cea3b7)
