### ISSUE TITLE
Exclude files from finding references

### ISSUE THREAD

**Issue by spreiter** [microsoft/pylance-release#3735]
I am reporting this issue here, because I was told this is supposed to be handled by the language server.

https://github.com/microsoft/vscode/issues/136441

## Environment data

-   Language Server version: v2022.12.20
-   OS and version: Rocky Linux 8.5 and VS Code 1.74.0
-   Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.18 and 3.6.8 locally and anaconda 33.16.5.6 with Python 3.6.15 environment

## Repro Steps

File structure:
```
lib/
    base.py
lib/
    calibrations -> ../calibrations
calibrations/
    a/
        measure.py
```

Module `base` has a class named _BaseClass_ and module `calibrations.a.measure` has a sub class called _SubAClass_

1. Added `**/lib/calibrations` to the `files.exclude` settings (user or workspace makes no difference)
2. Calling _Find all References_ on _SubAClass_ still finds the files in lib, even though they are the same files and should be ignored.
3. Even adding `**/calibrations` to `files.exclude` settings still shows me all files.

## Expected behavior

The settings `files.exclude`/`search.exclude` should have influence on finding references.

## Actual behavior

The settings `files.exclude` is ignored on finding references.

## Logs

no logs available when calling _Find All References_

**Comment by erictraut** [comment]
This has been discussed in the past, and we previously concluded that `files.exclude` is a VS Code setting that controls which files are displayed in the VS Code's file explorer, and that it doesn't apply to language servers. We should (re)confirm that other language servers (like TypeScript, for example) make the same assumption.

If you want to exclude files from pylance, you can create a [pyrightconfig.json](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) file and add an `"exclude"` section to it. Pyright is the static type checker upon which pylance is built.

**Comment by heejaechang** [comment]
@spreiter 
> If you want to exclude files from pylance, you can create a [pyrightconfig.json](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) file and add an "exclude" section to it. Pyright is the static type checker upon which pylance is built.

you can also get the same effect by using `python.analysis.exclude` in `settings.json`

...

one question. 

`calibrations -> ../calibrations` is this symlink? and you want it to be included in `analysis` (ex, you can import through `lib.calibrations..`) , but not in `find all references`? is that the ask? or are you saying we should dedup so we only show 1 if multiple files are pointed to the same physical file by symlink?

**Comment by spreiter** [comment]
Thanks @erictraut and @heejaechang !
Yes, `python.analysis.exclude` was the option I was looking for. I just assumed that if I exclude a file from everything else in VS Code, all extension should follow such rule. But if this is only applied for the explorer itself, this makes sense.

> one question.
>
> `calibrations -> ../calibrations` is this symlink? and you want it to be included in `analysis` (ex, you can import through `lib.calibrations..`) , but not in `find all references`? is that the ask? or are you saying we should dedup so we only show 1 if multiple files are pointed to the same physical file by symlink?

Yes, it's a symlink. And with the `lib` folder set as PYTHONPATH one can import `base` and `calibrations.a.measure`. I just want that those files in `lib/calibrations` are not found as references, because they actually come from another location. checking the real path may be an option, but I am already running fine with your proposed option :)
