### ISSUE TITLE
Pylance can't detect django rest framework when using Environment

### ISSUE THREAD

**Issue by neoMtrix** [microsoft/pylance-release#3736]
Type: <b>Bug</b>

Though, django rest framework is working fine. Pylance can't detect import and modules django rest framework when running in Environment. 

![bug](https://user-images.githubusercontent.com/106992001/206440980-fdcf79d4-a12f-4fee-ab5e-409280f1d083.png)

Extension version: 2022.12.20
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.14GB free)|
|Process Argv|--crash-reporter-id eba9fc9e-6549-4f90-88ba-6a3243884967|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723
ejf25101:30620729

```

</details>

**Comment by rchiodo** [comment]
Are you running the app with the same python environment that's selected in the bottom right? 

![image](https://user-images.githubusercontent.com/19672699/206520017-e407c1b2-b995-4457-92ab-798c4344d517.png)

'djangorestframework' is not a dependency of django, so I need to actually install it in my environment for this code to run. When I do that pylance detects it.

![image](https://user-images.githubusercontent.com/19672699/206520445-e15edbb8-765d-4b78-9615-59b676d9428c.png)

**Comment by neoMtrix** [comment]
![image](https://user-images.githubusercontent.com/106992001/206523088-da1e5fe8-5c86-4031-8534-dabb1f55da69.png)
Yes, I did install djangorestframework while in the environment. I also tried changing the interpreter path.

**Comment by rchiodo** [comment]
Can you follow the steps for capturing your log found here?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

Additionally, can you include your settings.json?
