### ISSUE TITLE
warning (maybe codeAction) on usage of deprecated objects

### ISSUE THREAD

**Issue by copdips** [microsoft/pylance-release#3738]
Hi,

I would like to see an useful feature from Pycharm, which is about to the usage of deprecated object.
Hereunder is a screenshot from Pycharm.

You can see that the word `coroutine` in the line 4 is strikethroughed.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/13083856/206408875-8b5bc670-3ce1-4d5d-bc89-81678bc21485.png">

And the source code of the `asyncio.coroutine` has a warnings.warn()

<img width="590" alt="image" src="https://user-images.githubusercontent.com/13083856/206409019-61c3c78c-ce5f-43f3-8d6d-13a8d3196184.png">

**Comment by judej** [comment]
Thanks for the suggestion, we are currently debating the best way to handle deprecations

**Comment by judej** [comment]
@erictraut, are there plans to support this before the [PEP ](https://peps.python.org/pep-0702/) is approved?

**Comment by erictraut** [comment]
@judej, I implemented this functionality in pyright 1.1.289 (published on Jan 13). I wouldn't expect any support for it in typeshed until after the PEP is approved (which I anticipate it will be) and the other type checkers also add the requisite support.

**Comment by judej** [comment]
@copdips we are waiting for the [PEP-702 ](https://peps.python.org/pep-0702/) to be approved at which point we will support the `@deprecated` decorator

**Comment by erictraut** [comment]
To be clear, pylance already supports the `@deprecated` decorator as specified in the latest draft of PEP 702. However, this PEP is still in draft form and could change. It's also possible that it will not be accepted by the Python steering council. If you would like to try out the current functionality, you're welcome to do so. But keep in mind that it could change or be removed in the future.
