### ISSUE TITLE
Autocomplete suggestion for a word.

### ISSUE THREAD

**Issue by inkoff** [microsoft/pylance-release#3739]
I am using pylance. Completion for words does not appear in suggestion. Where can this be configured? As I read on git: autocompletion works based on whichever language server matches the file extension.
I also use pycharm. It has a hotkey to search for words in the nearest context. Or is it to go to vscode? )))
That would be a cool feature

**Comment by judej** [comment]
Thanks for the report. This feature is disabled by default. To enable it, make the following change in your settings:
`"[python]": {
                "editor.wordBasedSuggestions": true
            } `
