### ISSUE TITLE
slice bytes type data got int type

### ISSUE THREAD

**Issue by MrScallion** [microsoft/pylance-release#3740]
## Environment data

-   Language Server version: 2022.12.20 (pyright 621d886b)
-   OS and version: windows 11
-   Python version (& distribution if applicable, e.g. Anaconda):  Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)] on win32

## Repro Steps

![image](https://user-images.githubusercontent.com/43311996/206643301-718121f7-5fd5-49a3-90cc-04ad6f9b98cf.png)

**Comment by erictraut** [comment]
Can you please provide a minimal, self-contained code sample (in text form) that exhibits the problem you're reporting? It's difficult to diagnose issues from partial screen shots.

**Comment by MrScallion** [comment]
@erictraut 
```python
data = bytes.fromhex("0060000001ffff")
bytes_sn = data[:5]  # slice data should be bytes, but pylance infer variable bytes_sn  type is int
bytes_sn.hex() # pylance will report "Cannot access member "hex" for type "int" Member "hex" is unknown"
```

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing.

![Screenshot 2022-12-08 at 11 52 17 PM](https://user-images.githubusercontent.com/7040122/206652294-27787f53-1ffd-4994-96b2-c448e542ca9c.png)

You mentioned that you're specifying a value for the `python.analysis.stubPath` setting. What value are you providing? And are you setting any other pylance settings?

**Comment by MrScallion** [comment]
> I'm not able to repro the problem you're seeing.
> 
> ![Screenshot 2022-12-08 at 11 52 17 PM](https://user-images.githubusercontent.com/7040122/206652294-27787f53-1ffd-4994-96b2-c448e542ca9c.png)
> 
> You mentioned that you're specifying a value for the `python.analysis.stubPath` setting. What value are you providing? And are you setting any other pylance settings?
my workspace settings:
```json
{
	"folders": [
		{
			"path": "remote_sim_dmis"
		},
		{
			"path": "tcp_services\\cardapi"
		},
		{
			"path": "tcp_services\\algorithm"
		},
		{
			"path": "tcp_services\\simcard_server"
		},
		{
			"path": "tcp_services\\card_pool_server"
		},
		{
			"path": "tcp_services\\PoolClientGo"
		},
		{
			"path": "tcp_services\\scpsim"
		},
		{
			"path": "tcp_services\\synway_sim_pool_server"
		},
		{
			"path": "tcp_services\\aleka_sim_pool_server"
		}
	],
	"settings": {
		"python.analysis.stubPath": "D:\\ProgramData\\Anaconda3\\envs\\voice-gateway\\Lib\\site-packages"
	}
}
```
my workspace structure
![image](https://user-images.githubusercontent.com/43311996/206653616-8bbb5717-21ff-4a65-8cdd-7c706595ecdf.png)
my test scripts
![image](https://user-images.githubusercontent.com/43311996/206653804-0d2ab663-c04f-4169-b330-dfaab4dc17c1.png)

**Comment by erictraut** [comment]
Why are you setting your `stubPath` to your `site-packages` directory? The `stubPath` is meant to point to a project-local directory that contains stubs that you have downloaded or created specifically for your project. Stubs that are installed your selected Python environment will be used automatically. Please try removing the `stubPath` setting, and see if that fixes the issue you're seeing.
