### ISSUE TITLE
TROUBLESHOOTING.md

### ISSUE THREAD

**Issue by Sittp** [microsoft/pylance-release#3744]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by rchiodo** [comment]
Was this created by mistake? Doesn't seem to have any information in it.
