### ISSUE TITLE
Pylance misses errors when instantiating Pydantic BaseModels that use a custom metaclass

### ISSUE THREAD

**Issue by ggydush** [microsoft/pylance-release#3745]
<h3> Environment data </h3>

-   Language Server version: 2022.12.20
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from pydantic import BaseModel
from pydantic.main import ModelMetaclass

class CorrectlyShowsError(BaseModel, metaclass=ModelMetaclass):
    """Test docstring."""
    a: int


class TestMeta(ModelMetaclass):
    ...


class DoesNotShowError(BaseModel, metaclass=TestMeta):
    """Test docstring."""
    a: int


CorrectlyShowsError() # Pylance finds an error, as argument for `a` is not specified
DoesNotShowError() # Pylance does not find an error, but it should
```

<h3> Repro Steps </h3>

1. Install latest pydantic
2. Copy snippet into editor with Pylance turned on

<h3> Expected behavior </h3>

Pylance should find an error (Argument missing for parameter "a") when trying to instantiate both classes. Also, when hovering over the classes, the docstring should show "Test docstring."

<h3> Actual behavior </h3>

When a BaseModel's object uses a metaclass that inherits from `ModelMetaClass`, Pylance misses errors when instantiating the objects and shows docstrings that are less relevant (shows BaseModel's docstring).

<h3> Logs </h3>

```
XXX
```

**Comment by erictraut** [comment]
If you intend for `TestMeta` to act like a dataclass decorator, you would need to add the `dataclass_transform` to it for type checkers to treat it as such. This is specified in [PEP 681](https://peps.python.org/pep-0681/).
