### ISSUE TITLE
Field of sqlalchemy model is not recognized for refactoring

### ISSUE THREAD

**Issue by introom** [microsoft/pylance-release#3747]
I am using VSCode and Sqlalchemy. Given the following orm table,
```
class Model(Base):
    __tablename__ = "model"
    __table_args__ = ()

    created_at = Column(DateTime)

m = Model(created_at = datetime.now())
```
When I perform a refactoring with "F2 Rename Symbol" on the "created_at" field and change it to some name like "foobar", the line
```
m = Model(created_at = datetime.now())
```
won't get changed.

**Comment by rchiodo** [comment]
Need to see if SQLAlchemy is using dataclass transform or not? If it isn't, then this wouldn't work because we don't know how the constructor is synthesized.

**Comment by gramster** [comment]
This might work when SQLAlchemy2 is released, if they make use of dataclass transform (discussion at https://github.com/microsoft/pyright/discussions/2958). We have no knowledge of how the constructor is synthesized in SQLAlchemy 1.x.
