### ISSUE TITLE
reportShadowedImports x.py is overriding the stdlib module x whils x.py IS stdlib!

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#3751]
Type: <b>Bug</b>

I have my Python interpreter pointed to a custom location and now (just updated) get Pylance reporting about modules from that location "shadowing" `stdlib` modules.
Thing is: This IS the location of the very stdlib module! For instance:

> ```
> "c:\...\python\python39\Lib\traceback.py" is overriding the stdlib module "traceback"
> ```
> Pylance([reportShadowedImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportShadowedImports))

Interpreter is pointed to
```
c:\...\python\python39\python.exe
```

Extension version: 2022.12.21
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.97GB (3.55GB free)|
|Process Argv|--crash-reporter-id 52bfd6ed-a49c-4227-9403-bca1ab1a5ea5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Can you include the output as described here?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

My suspicion is that Pylance doesn't see your private python install as the environment in use for some reason.

**Comment by gandhis1** [comment]
I still get this issue, as I previously [alluded to here](https://github.com/microsoft/pyright/pull/4132). I will post my trace logging output soon.

**Comment by ewerybody** [comment]
I'm sorry I was too packed recently to provide the requested info.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks

**Comment by kivikakk** [comment]
I just encountered this issue, but after some tinkering found the issue occurred when my workspace included a folder which contained both the source file of interest _and_ the stdlib files; i.e.:

* C:/root/
  * python3/
  * my-code/

If my workspace started at `C:/root/`, I'd get the failure. If I instead started it at `C:/root/my-code/`, I wouldn't. I could even add `C:/root/python3/` to the workspace as well, and it'd be fine -- they just need to come from different "workspace folders". Even having overlapping definitions is fine (i.e. `C:/root/` and `C:/root/my-code/`), it seems, as VS Code appears to use the more specific folder definition and thus groups them separately in.. whatever process is going on here.

**Comment by CA4GitHub** [comment]
> I'm sorry I was too packed recently to provide the requested info.

Were you able to resolve your issue?

**Comment by Preston-Landers** [comment]
> I just encountered this issue, but after some tinkering found the issue occurred when my workspace included a folder which contained both the source file of interest _and_ the stdlib files; i.e.:
> 
> * C:/root/
>   
>   * python3/
>   * my-code/
> 
> If my workspace started at `C:/root/`, I'd get the failure. If I instead started it at `C:/root/my-code/`, I wouldn't. I could even add `C:/root/python3/` to the workspace as well, and it'd be fine -- they just need to come from different "workspace folders". Even having overlapping definitions is fine (i.e. `C:/root/` and `C:/root/my-code/`), it seems, as VS Code appears to use the more specific folder definition and thus groups them separately in.. whatever process is going on here.

I'm having this exact problem. My folders need to be structured this way for ... historic reasons.  I've got Python vendored inside my project folder. 

```text
c:\code\my-project\
c:\code\my-project\my-lib-1
c:\code\my-project\my-lib-2
c:\code\my-project\dist\python\python.exe
c:\code\my-project\dist\python\Lib\...
```

Unless I have `reportShadowedImports: none` it complains about every line where I import a standard library. I want to tell Pylance that `c:\code\my-project\dist\python` *is* the standard library as far as it's concerned, even though it's in my project folder.  I've also put the `dist/python` folder in `files.exclude` to no avail.

I'd still like to have reportShadowedImports enabled, because we still don't want to define modules that shadow a builtin.  Thanks!

**Comment by rchiodo** [comment]
Sounds like we need to check if the reported path has a python.exe in it or not (or the equivalent for mac/linux).

**Comment by rchiodo** [comment]
In the cases where it isn't working, is your python environment in VS code set to the embedded python folder?

**Comment by erictraut** [comment]
@rchiodo, searching for a "python.exe" doesn't strike me as the right solution here. This case isn't any different from a "venv" directory within the project, except that pylance will auto-exclude venvs. If the `dist/python` directory is explicitly excluded, it should work fine. I recommend figuring out why that's not working.

**Comment by Preston-Landers** [comment]
Huh, ok. I thought I had tried `python.analysis.exclude` and it wasn't helping, or maybe I just messed it up. But I tried that again and it seems to work for me now, I'm no longer getting the warning on my standard imports. And I'm still getting the desired warnings about when I _do_ override a stdlib file name.

```
//  settings.json
{
  "python.analysis.exclude": ["dist/python"],
}
```

**Comment by rchiodo** [comment]
@erictraut, I was thinking this would be the same thing as our current auto exclusion for venvs:

https://github.com/microsoft/pyright/blob/c400d889a46752c7b500df5fd7a0bcfd2e8e1101/packages/pyright-internal/src/analyzer/service.ts#L1201

We'd add something else to the envMarkers to find these cases.

**Comment by erictraut** [comment]
Auto-excluding the directory won't help if explicit exclusion doesn't work. 

I don't think this case is common (or legitimate) enough to add additional logic to the venv detection logic. Explicit exclusion is a fine answer for odd cases like this, but that assumes that explicit exclusion solves the problem.

**Comment by rchiodo** [comment]
Thanks, makes sense to me. Since @Preston-Landers reported that the exclusion works, closing.

**Comment by jmontalvo94** [comment]
In case someone else is experiencing this, I had the same issue as previous users. My python distribution lives inside a `venv/` folder created by a conda environment in the workspace folder, so it lives right next to the `src/` folder. I added `venv` to exclude it and it doesn't complain anymore.

```
# settings.json
{
  "python.analysis.exclude": ["venv"],
}
```

**Comment by gandhis1** [comment]
Another solution, which I ended up using, is turning off the report shadowed message error by setting the severity to None. I still think there is an issue - specifically Pylance thinking an environment is source code - but I don't have the time to investigate.

**Comment by swfc** [comment]
I had same problem with vscode 1.81.1 and had to include the above to exclude my venv directory. I don't remember seeing this problem before now. Did something change as I've been using conda venv dirs for a long time and only just started to need this explicit exclude?

**Comment by VashJuan** [comment]
I'm no expert, but this check was a fairly recent change. My solution was to **rename code.py to main.py**, avoiding the conflict altogether, in case this works in your situation...

**Comment by fredludlow** [comment]
I have a similar conda setup to that described by @jmontalvo94, I create a conda environment at the top level of the checked out code (sibling to src, setup.cfg etc). Their suggestion works for me:

``# settings.json
{
  "python.analysis.exclude": ["venv"], // Or whatever directory your env is in
}```

@erictraut - As specific exclusion does work in this case, and conda is a very common environment manager, would it be reasonable to have something included in `envMarkers` that is specific to a conda env? Conda envs tend to have a `conda-meta` directory at their top level. There isn't usually an activate script AFAICS because activation is handled externally to the environment.

**Comment by jtencer** [comment]
Same issue with a conda environment.  Adding the explicit exclusion worked.
