### ISSUE TITLE
Pylance(reportShadowedImports) links to anchor that does not exist on docs

### ISSUE THREAD

**Issue by ewerybody** [microsoft/pylance-release#3752]
Type: <b>Bug</b>

I was just reporting #3751 and noticed that there is an anchor specified in the link under **reportShadowedImports**:
![image](https://user-images.githubusercontent.com/218956/207025099-21dbbfaa-67be-46ee-a887-2aad4bbc017b.png)

`https://github.com/microsoft/pyright/blob/main/docs/configuration.md`**`#reportShadowedImports`**

Seems this anchor goes nowhere on the docs page https://github.com/microsoft/pyright/blob/main/docs/configuration.md
Well, I'd think this is super minor but that's for you to decide :)
Cheers:
ëRiC

Extension version: 2022.12.21
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.97GB (3.55GB free)|
|Process Argv|--crash-reporter-id 52bfd6ed-a49c-4227-9403-bca1ab1a5ea5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by rchiodo** [comment]
Thanks for noticing. Updated the configuration.md file to have that link
