### ISSUE TITLE
Import "tensorflow.keras" could not be resolved

### ISSUE THREAD

**Issue by otavio-silva** [microsoft/pylance-release#3753]
<h3> Environment data </h3>

-   Language Server version: 2022.12.20
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import tensorflow as tf
from tensorflow.keras import activations, initializers, layers, losses, metrics, models, optimizers, regularizers
```

<h3> Repro Steps </h3>

1. Open VSCode
2. Create somename.py
3. Type code snippet

<h3> Expected behavior </h3>

Imports should  be resolved

<h3> Actual behavior </h3>

`Import "tensorflow.keras" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)`

<h3> Logs </h3>

[pylance.log](https://github.com/microsoft/pylance-release/files/10210259/pylance.log)

**Comment by rchiodo** [comment]
I think `tensorflow.keras` is a special case. Its location is determined dynamically as far as I can tell, so pylance cannot figure out where it is.

The `tensorflow.keras` module is found here for me:

```
.venv/lib/python3.10/site-packages/keras/
```

whereas pylance would look for it here:

```
.venv/lib/python3.10/site-packages/tensorflow/keras
```

@bschnurr has advice on how to get pylance to see where it is:

/home/rich/test/test_1/.venv/lib/python3.10/site-packages/keras/

**Comment by bschnurr** [comment]
whats your version of tensorflow? try the latest

**Comment by otavio-silva** [comment]
I installed version 2.10 using mambaforge on WSL2 Ubuntu, it works now.
And it seems that TensorFlow is going for Linux-only, this is the way then.

**Comment by AnuraagaNath** [comment]
Try keras only without using tensorflow before it

**Comment by mnothman** [comment]
With keras3 there is a new way to import, the documentation has examples for layers, models, optimizers, applications
https://keras.io/api/

Just do below with no other imports:

    import tensorflow as tf
    from tensorflow import keras

For Dense you would do

    keras.layers.Dense

Example:

    x = keras.layers.Dense(128, activation='relu')(x)
