### ISSUE TITLE
way to convert string to f-string

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#3757]
### Discussed in https://github.com/microsoft/vscode-python/discussions/15549

<div type='discussions-op-text'>

<sup>Originally posted by **zcutlip** March  3, 2021</sup>
I waste so many keystrokes by starting a string, realizing I want to format an object in the middle of it, skipping back to the beginning to prepend `f`, then returning to my typing position.

It'd be awesome if there was a keyboard shortcut for this, or, even better, if the need for an f-string could be automatically detected (e.g., the presence of curly braces and an in-scope object is referenced).</div>

---
<div type='discussions-op-text'>
<sup>rgov on 3 Mar</sup>

I like the idea of just typing a curly bracket inside a string to convert it to an f-string, as long as this is pushed to the undo stack and I can <kbd>Cmd-Z</kbd> quickly to undo it. I type literal curly brackets in my strings infrequently enough it wouldn't bug me much (no more than other kinds of quote/bracket auto-complete).

I think the best way to do this would be to trigger on `}` and apply a few rules:

1. Scan backwards for a matching `{` in the same string. If none is found, do not convert to an f-string. This avoids a number of false positives like `print("int main() { return ", code, "}")`.

2. Scan forwards and backwards for another `}` in the same string. If one is found, this probably means the string is not meant to be an f-string, and it guarantees that conversion will be attempted at most once per string.

Plus two heuristics for avoiding conversion of strings that are formatted with `str.format()`:

3. Do not convert if the sequence `{}` appears, because this is an invalid f-string specified and may indicate the use of `str.format()`.

4. Try to detect if `str.format()` is being called on the string. This is imperfect because if the user is typing a new line of code, it may not have been written yet. For *existing* code the user is editing, one could just see if `.format(` comes directly after the closing quote -- by far the most common pattern.

    But note that, as long as you are targeting a version of Python with f-strings, the user probably won't be writing *new* code that uses `str.format()`.</div>

**Comment by rchiodo** [comment]
We actually already have an item for this: 
https://github.com/microsoft/pylance-release/discussions/2615
