### ISSUE TITLE
Provides go to def support for overloaded operators and special method names.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#3759]
Currently pylance only supports `go to definition` on named symbol such as `method name`, `variable name`, `type name` and etc. but it doesn't support `go to definition` on operator. 

In python, overloading operator such as `==`, `+`, `[]` is quite common. for example, pandas `Series` type overload `==` so it returns another `Series`, or `numpy` overrides `~` to return new `numpy` array. It would be nice if one can do `go to definition` on `==` which jump to `__eq__` or `[]` jump to `__getitem__`

If pylance can also color those overloaded operators differently than the default one, it would help coding as well.

**Comment by heejaechang** [comment]
It would be nice if pylance can support all special names (https://docs.python.org/3/reference/datamodel.html#special-method-names) but supporting at least all major ones would be good start and help people understanding/navigating third party libraries.

**Comment by bschnurr** [comment]
maybe also add a semantic token

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023611-7-June-2023-PreRelease)
