### ISSUE TITLE
Pyright parser causes tests failures

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#3761]
Latest pyright causes failures in pylance:
https://github.com/microsoft/pyrx/actions/runs/3595466571/jobs/6055042149

Need to adjust tests or figure out why parser changes are affecting format on save

**Comment by rchiodo** [comment]
Inlay hints don't work the same either.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023111-4-January-2023-PreRelease)
