### ISSUE TITLE
Ray's `.init()` not detected as valid

### ISSUE THREAD

**Issue by BlueskyFR** [microsoft/pylance-release#3764]
<h3> Environment data </h3>

-   Language Server version: 2022.12.20
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
import ray

ray.init()
```

![image](https://user-images.githubusercontent.com/25421460/207974494-64acbb66-2a5c-4f37-958e-00021d85d06c.png)

<h3> Logs </h3>

```
(114586) Background analysis message: setFileOpened
(114586) Background analysis message: getDiagnosticsForRange
(114586) Background analysis message: getDiagnosticsForRange
(114586) Background analysis message: analyze
```

**Comment by rchiodo** [comment]
Thanks for the issue. I'm trying to replicate the structure of the ray module and I can't seem to cause the same error.

The `init` method is exposed here I believe:

https://github.dev/ray-project/ray/blob/963174ca3b94daf709bdead8f6b78cc0e3e950cc/python/ray/__init__.py#L146

I'm not sure why pylance thinks this is not exported.

**Comment by bschnurr** [comment]
I've been able to repo in linux.

**Comment by watsy0007** [comment]
same log `"init" is not exported from module "ray"`

**Comment by bschnurr** [comment]
found the cause...  We aren't seeing 'init' being exported in the '__all__' list due to the fact they are adding subpackages in the same expression.  It needs to be a separate statement.

`ray/__init__.py`


```
__all__ = [
] + _subpackages
```
change to 
```
__all__ = [
]
__all__ += _subpackages
```

**Comment by bschnurr** [comment]
looks like they have already fixed it in their repo.
https://github.com/ray-project/ray/commit/1829be0a4ff58f726184295476f4ec0762b7c721
