### ISSUE TITLE
(parameter) request: Any "request" is not accessed Pylance

### ISSUE THREAD

**Issue by AhmadNazir7** [microsoft/pylance-release#3766]
![WhatsApp Image 2022-12-17 at 7 03 11 PM](https://user-images.githubusercontent.com/120793462/208245850-e886660d-8d8b-406f-b779-e1585c4dc071.jpeg)

**Comment by judej** [comment]
Thanks for the report. This diagnostic is expected since you do not use `request` in the `delete_emp` function.  You can use the `reportUnusedVariable` setting as documented in [settings](https://github.com/microsoft/pyright/blob/main/docs/configuration.md)

**Comment by erictraut** [comment]
This isn't a diagnostic, and it cannot be disabled. It's simply a hint that indicates that the parameter is not accessed in the body of the function. The `reportUnusedVariable` rule never emits diagnostics for parameters because there are legitimate reasons for parameters to be unused.
