### ISSUE TITLE
Inlay Hints infills illegal return type hints on methods

### ISSUE THREAD

**Issue by AlexBlandin** [microsoft/pylance-release#3767]
## Environment data

- Language Server version: Pylance language server 2022.12.20 (pyright 621d886b)
- OS and version: Windows 10 21H2 19044.2251
- Python version (& distribution if applicable, e.g. Anaconda): CPython 3.11.1 64-bit

## Code Snippet

```python
class Bar:
  def foo(self):
    return Bar()
```

## Repro Steps

1. Enter snippet
2. Ensure inlay type hints are enabled (`python.analysis.inlayHints.functionReturnTypes`)
3. Double click to infill return type (`def foo(self) -> Bar:`)
4. Observe Pylance inform you of its own erroreous infill (`Pylance(reportUndefinedVariable)`)

## Expected behavior

There are three acceptable behaviours in Python at current for type hints of a given class within its own methods (in order of reliability):

1. Stringified infills (`def foo(self) -> "Bar":`), safe, handled correctly by Pylance and other type checkers, considered awkward
2. Unchanged infill (`def foo(self) -> Bar:`), but with a code-action for `from __future__ import annotations` (for PEP 563 behaviour)
3. `Self` infill (`def foo(self) -> Self:`), which may be considered Pythonic, but only where available, requiring an import not in earlier versions of the standard `typing` module (but a code-action to import when the Python environment supports it may be viable), or via fallback upon the external `typing_extensions` module (a backport for Python 3.10 and prior, which may not be available in the given Python environment)

I suspect that 1 and 2 are likely the best solutions, given they are available for all Python from 3.7 onwards (CPython 3.6 being no longer supported), though if further support (Python 3.6) is required then 1 is the only option that can be reliably defaulted to for the infill. If code-actions are provided to help users fix this, then the availability of 2 and 3 is likely desired, though if `Self` is not already available via the `typing` or `typing_extensions` modules already available in the Python environment, then it should probably not be shown. However, while more likely to be available than `Self` in the immediate future, 2 makes annotation slow (due to stringification) and runtime evaluation even slower on many implementations (requiring `eval()` for stringified annotations and so forth), whereas 3 does not have this issue (but at the cost of an external module if not on Python 3.11 and above).

Given that resolving type hints like this into legal Python may be required if Pylance is not merely to rely on stringified infills (which users may find unsatisfying), then the ability to treat the double click as a code-action may be necessary in itself; to save double clicking and _then_ triggering a code-action. While a default strategy setting may work to avoid this, naturally any cases may eventually fallback upon stringified input to "at least" infill a syntactically correct annotation.

Alternatively, of course, no solution may be found and Python could simply be waited out on until a resolution to the PEP 563 and PEP 649 situation is resolved.

## Actual behavior

The type hint is infilled as a variable (`def foo(self) -> Bar:`) rather than a string literal (`def foo(self) -> "Bar":`, as the safe default) or any other chosen/preferred option above. Pylance then correctly reports this as an error, given that Python does not currently support the class (`Bar`) being referenced in any declaration or annotation within itself (but, of course, may be referenced in its method bodies proper). 

## Logs

Nothing relevant.

**Comment by bschnurr** [comment]
Thanks for the issue and suggestions.
We will look at fixing this.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.22, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023322-15-March-2023-PreRelease)

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.22, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023322-15-March-2023-PreRelease)

**Comment by AlexBlandin** [comment]
Can confirm that in the pre-release version it does stringify the infill as `-> "Bar"` now, per approach 1. That's probably the best approach, pending future PEPs that improve/resolve typing syntax.
