### ISSUE TITLE
No import suggestions

### ISSUE THREAD

**Issue by gregersn** [microsoft/pylance-release#3771]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When I write code, and use functions, etc not defined, I am expecting suggestions for imports in the pop-up dialog.

The popup list now only shows built-in or already defined/imported suggestions.

## Steps to reproduce:

1. Create new Python file.
2. Start writing code, `def test(a: Di)`

3. Observe that there is no suggestion to import `Dict` from `typing`

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Telemetry is disabled
Experiments are disabled, only manually opted experiments are active.
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: /usr/bin/python
> /usr/share/anaconda/bin/conda info --json
> /usr/share/conda/bin/conda info --json
> /bin/python ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/interpreterInfo.py
> /bin/python2 ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/interpreterInfo.py
> /usr/bin/python2 ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.21.13491005/pythonFiles/interpreterInfo.py
Starting Pylance language server.

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "yapf"

```

</p>
</details>

Extension version: 2022.21.13491005
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:47:18.476Z)
OS version: Linux x64 6.0.12-300.fc37.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2122)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.27GB (15.35GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by bschnurr** [comment]
Yes, the completion suggestions will only include symbols from the current scope.

However you can press 'ctrl+.' to request autoImport suggestions
![image](https://user-images.githubusercontent.com/1946977/209731666-b9d7e251-75c9-4229-ab56-17087b35bc0d.png)

**Comment by gregersn** [comment]
So this was changed in some previous version? Cause I remember correctly that the auto-import suggestions used to come up with the other suggestions automatically? Could this be set through some configuration? I might get used to pressing a key instead, but right now that feels very clunky.

**Comment by bschnurr** [comment]
@heejaechang might have further info

**Comment by heejaechang** [comment]
@gregersn did you enabled `python.analysis.autoImportCompletions`? it is changed to `off` by default in recent release.

see https://github.com/microsoft/pylance-release/blob/main/README.md#settings-and-customization for more details. especially settings for indexing, auto imports and etc.

**Comment by gregersn** [comment]
> @gregersn did you enabled `python.analysis.autoImportCompletions`? it is changed to `off` by default in recent release.

I did not, thank you for the link. 

Closing this issue.
