### ISSUE TITLE
multiline strings are collapsible and don't collapse with their parent

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pylance-release#3775]
### VS Code version

1.62.1

### Extension version

2021.11.1422169775

### OS type

Windows

### OS version

10

### Python distribution

python.org

### Python version

3.10

### Language server

Pylance

### Expected behaviour

![image](https://user-images.githubusercontent.com/57028336/141215070-919cab72-a4a8-4b45-b065-96683b32d7e4.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/57028336/141215094-640f805c-303d-4c03-a3a1-0fa9986c28b6.png)

### Steps to reproduce

1. create a `.py` file with the following
    ```py
    def foo() -> None:
        print(1)
        bar = """
    asdf"""
        print(2)
    ```
2. move your mouse to the side and observe the collapse button incorrectly appearing on line  4

    ![image](https://user-images.githubusercontent.com/57028336/141215266-8cc84d21-25e5-4f61-9d22-63a63ecbb261.png)
3. click the collapse button on line 1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by debonte** [comment]
Going through old issues. This is fixed. My guess is it has worked since https://github.com/microsoft/pylance-release/issues/3085 was fixed in 2022.8.41.
