### ISSUE TITLE
Protocols inside protocols incompatibilities

### ISSUE THREAD

**Issue by AiroPi** [microsoft/pylance-release#3776]
## Environment data

-   Language Server version: v2022.12.20
-   OS and version: MacOS 13.1 (22C65)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

```python
from typing import Protocol


class WeaponProtocol(Protocol):
    damages: int


class PlayerProtocol(Protocol):
    def attack(self, weapon: WeaponProtocol) -> None:
        ...


class Sword:
    damages = 2


class Player1:
    def attack(self, weapon: Sword) -> None:
        print(f"You inflicted {weapon.damages} damages.")


weapon: WeaponProtocol = Sword()  # here, no problem : Sword IS compatible with WeaponProtocol
player: PlayerProtocol = Player1()  # here, error: for any reason, Sword is NOT compatible with WeaponProtocol anymore.

player.attack(weapon)
```

## Expected behavior

No complain from PyLance since Sword IS compatible with WeaponProtocol.

## Actual behavior

```
Expression of type "Player1" cannot be assigned to declared type "PlayerProtocol"
  "Player1" is incompatible with protocol "PlayerProtocol"
    "attack" is an incompatible type
      Type "(weapon: Sword) -> None" cannot be assigned to type "(weapon: WeaponProtocol) -> None"
        Parameter 1: type "WeaponProtocol" cannot be assigned to type "Sword"
          "WeaponProtocol" is incompatible with "Sword"
```

**Comment by erictraut** [comment]
Pyright is correct here. Not surprisingly, mypy generates the same error here.

The protocol `PlayerProtocol` indicates that the method `attack` must accept a parameter `weapon` that is any type that satisfies the protocol `WeaponProtocol`, but the method `Player.attack` does not accept any `WeaponProcotol` instance; it accepts only a `Sword`.

**Comment by AiroPi** [comment]
Ok I see, it make sens. Then how can I type the attack method to accept any class that respect the WeaponProtocol ?
I know it is not the right place to ask this, so you don't need to answer my question 😅

**Comment by AiroPi** [comment]
Ok I only need to use a bounded TypeVar, sorry for the false issue !
