### ISSUE TITLE
pandas rename(columns={int: str}) is rejected

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#378]
## Environment data

-   Language Server version: 2020.9.4
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.5

## Expected behaviour

No error on code below

## Actual behaviour

```python
import pandas as pd

df = pd.DataFrame({0: [1,2,3]})
df = df.rename(columns={0: "hey"})

df = pd.DataFrame({"ok": [1,2,3]})
df = df.rename(columns={"ok": "hey"})
```

In the above, the first rename is valid, but the error message:
```
No overloads for "df.rename(columns={ 0: "hey" })" match parameters
  Argument types: (Dict[int, str])
```
appears.  This is valid pandas code.  Column names can be integers

## Logs

Leaving this out - it's just a stub issue

**Comment by Dr-Irv** [comment]
In addition, the following also fails:
```python
df = pd.DataFrame({0: [1, 2, 3]})
df = df.rename(columns=str)
```

Here are my fixes (but I think there may be other use cases that I'm not listing here - these are the ones that fixed my code):
```
diff frame.pyi.ORIG frame.pyi
633c633,634
<         columns: Optional[Dict[_str, _str]],
---
>       index: Optional[Union[Dict[Union[_str, int], _str], Callable]] = ...,
>       columns: Optional[Union[Dict[Union[_str, int], _str], Callable]] = ...,
```

Note that `index` was also missing from the `rename()` argument list.

**Comment by gramster** [comment]
It looks like this was fixed in the last release but we forgot to list it. Closing.

**Comment by Dr-Irv** [comment]
@gramster  The following also fails, and it is related.  Should I open up a new issue?

With 2020.9.6, the following code is failing:
```python
df = pd.DataFrame({0: [1, 2, 3]})
df = df.rename(index=lambda x: str(x))

df = pd.DataFrame({0: [1, 2, 3]})
df = df.rename(index=str)
```

Message for first one is:
```
No overloads for "df.rename(index=lambda x: str(x))" match parameters
  Argument types: ((x: Unknown) -> str)
```

Message for second one is:
```
No overloads for "df.rename(index=str)" match parameters
  Argument types: (Type[str])
```

This seems to fix it:
```
diff frame.pyi.ORIG frame.pyi
634c634
<         columns: Optional[Union[Callable, Dict[Union[int,_str], _str]]],
---
>         columns: Optional[Union[Callable, Dict[Union[int,_str], _str]]] = ...,
```

Note that this is making `index` and `columns` optional, but in reality, you should specify one or the other or both.  Not sure how to specify that in the `.pyi` file.  It might need 3 overloads:  one for `index` only, one for `columns` only, and one for both.

**Comment by gramster** [comment]
Thanks. We're already abusing the types quite a bit to do things like enforcing whether a parameter is present or not, and I don't want to get too carried away, especially as we want to eventually inline these in pandas, so I think its okay to just make both optional.

**Comment by Dr-Irv** [comment]
@gramster I know you closed this issue, but I want to make sure the issue shown in the comment  https://github.com/microsoft/pylance-release/issues/378#issuecomment-699141106 will still be addressed. 

If you want a new issue, let me know, or just reopen this one.

**Comment by jakebailey** [comment]
Yes, the patch in that comment was applied.
