### ISSUE TITLE
Intellisense issue with Flask-SQLAlchemy

### ISSUE THREAD

**Issue by robot1125** [microsoft/pylance-release#3780]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expecting components of Flask-SQLAlchemy to be syntax highlighted by Intellisense.

## Steps to reproduce:

1. Enter the code below and look for the lack of highlighting on objects such as db.Column and db.Integer:

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///mydatabase.sqlite3'

db = SQLAlchemy(app)

class students(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(100))
   
    def __init__(self, name):
        self.name = name
```
2. This appears to be the same issue as [#4027](https://github.com/microsoft/vscode-python/issues/4027) - "Intellisense not available for flask-sqlalchemy", however that was marked closed in 2019.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
{no output}
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.20.1
VS Code version: Code 1.74.1 (Universal) (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:33:40.793Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-56-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 31ca47c1-ab4f-4983-abcb-b86c76fd0df8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Linode|
|OS|Linux x64 5.15.0-56-generic|
|CPUs|AMD EPYC 7542 32-Core Processor (2 x 2899)|
|Memory (System)|3.83GB (2.53GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by bschnurr** [comment]
Try out adding some flask-sqlalchemy-stubs

I found this https://github.com/ssfdust/flask-sqlalchemy-stubs

Steps:

1. pip install git+https://github.com/ssfdust/flask-sqlalchemy-stubs.git
2. add `if TYPE_CHECKING:` block below

```python
from typing import TYPE_CHECKING
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///mydatabase.sqlite3"

db = SQLAlchemy(app)
if TYPE_CHECKING:
    from flask_sqlalchemy.model import Model

    BaseModel = db.make_declarative_base(Model)
else:
    BaseModel = db.Model


class students(BaseModel):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))

    def __init__(self, name):
        self.name = name

```

**Comment by PabloLION** [comment]
I had the same problem and tried @bschnurr's solution and it did what I wanted. I think it's a good spot to close the issue. What's your opinion @robot1125 ?

**Comment by judej** [comment]
Closing since this seems to address the issue. If this is still a problem, please reopen the issue.

**Comment by robot1125** [comment]
Sorry for not spending more time on this.  Thank you for reviewing it.
