### ISSUE TITLE
Auto-indent behavior as before / jumping to beginning of line

### ISSUE THREAD

**Issue by amueller** [microsoft/pylance-release#3781]
Filing as requrested in https://github.com/microsoft/vscode-python/issues/481

## Environment data

-   Language Server version: v2022.12.20
-  `[Info  - 5:13:28 PM] (8596) Pylance language server 2022.12.20 (pyright 621d886b) starting`
-   OS and version: Windows / WSL
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.13 via anaconda

![image](https://user-images.githubusercontent.com/449558/208962863-2f134b71-763a-4205-8d61-d95a1faf4953.png)

## Code Snippet
```python
def f(a,<newline>
```
jumps to the beginning of the next line, instead of to the opening parenthesis indentation.
Same in similar settings (calling a function, in an if clause, ...), and also if the parenthesis is closed.
 

I added the ``languageServer`` line and the `"editor.formatOnType": true,` but still see the linebreak behavior issues.
Is there a way to confirm I set it up correctly?

**Comment by rchiodo** [comment]
I believe this is on purpose. Until the function has a `:` on the end, it's not considered a function. Auto indentation only happens once it's known to be a function (or an if statement, etc).

This works:
```python
def f(a):<newline>
```
But this doesn't:
```python
def f(a)<newline>
```

**Comment by amueller** [comment]
please note that there is no closing parenthesis in my example, meaning the next token would be a second argument for the function, not the function body.

**Comment by rchiodo** [comment]
This does seem silly. Why would it not indent to the parens. PEP 8 seems to indicate a different default than jumping to the `(` though:

https://peps.python.org/pep-0008/#indentation

Maybe that's just an example though. 

If we were to implement this would it need settings?

**Comment by amueller** [comment]
![image](https://user-images.githubusercontent.com/449558/210650773-e2f9298a-573d-4822-b38c-608044099874.png)

My reading (and I think what flake8 and pep8 enforce?) is that if there is nothing after the opening parenthesis, we indent an extra level, if there is already something after the opening parenthesis, then indent to the parenthesis.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023121-11-January-2023-PreRelease)
