### ISSUE TITLE
feature request: auto-imports: exclude some modules from auto-import suggestion

### ISSUE THREAD

**Issue by sarisia** [microsoft/pylance-release#3786]
I have [`pyparsing` module](https://pypi.org/project/pyparsing/) as an indirect dependency, but since it has many classes whose names are as same as the ones in `typing` module (e.g. `Optional`, ), I experience wrong imports too many...

![image](https://user-images.githubusercontent.com/33576079/209445279-c4314e12-d413-453b-ab39-c7c53bfbdbde.png)

It would be helpful to have something like "module blocklist" to hide or make priority lower for suggestions from specific modules.

## Repro

1. enable indexing and auto import:

```
"python.analysis.autoImportCompletions": true,
"python.analysis.indexing": true
```

2. install `pyparsing`: `pip install pyparsing`
3. Type `Optional` and see suggestions

**Comment by bschnurr** [comment]
there is a way to exclude modules, see

https://github.com/microsoft/pylance-release/issues/3466#issuecomment-1341842382

**Comment by sarisia** [comment]
> https://github.com/microsoft/pylance-release/issues/3786#issuecomment-1386310432
> there is a way to exclude packages, see
> 
> [#3466 (comment)](https://github.com/microsoft/pylance-release/issues/3466#issuecomment-1341842382)

This worked perfectly, thanks!

**Comment by shayded-exe** [comment]
Is there a way to exclude all packages that aren't a direct dependency.
