### ISSUE TITLE
Disable type checking for a package but keep autcompletion

### ISSUE THREAD

**Issue by albireox** [microsoft/pylance-release#3792]
There are packages that are simply not ready to work with types at this point, and trying to externally coerce them to be typed produces code that's more confusing that just assume their values are `Any` and, where relevant, manually type them.

Right now I don't think there's an option to disable typing for a single package. The only option is to add a `typings` directory and for each submodule in the package add an `__init__.pyi` overriding `__getattr__()`. That wouldn't be too bad except for two reasons: it needs to be done independently for each submodule that's imported; and it disables symbol discovery and autocompletion, which is often useful even if the typing in the package is not.

Would it be possible to have a configuration option in `pyrightconfig.json` to disable typing for a package while keeping its autocompletion? Something like reverting `python.analysis.typeCheckingMode` to `off` but only for that package.

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) doesn't type check code within imported packages, so "disabling type checking for a package" wouldn't have any effect. The `python.analysis.typeCheckingMode` setting tells pyright whether it should type check _your code_. You can certainly disable this if you want, but that's probably not what you're looking for.

Pyright uses type information from imported packages (when it's available) to type check your code. This same type information is used for symbol discovery and completion suggestions. If you remove the type information for a package (i.e. treat all symbols as though they are type `Any`), you may eliminate some false positive type checking errors, but you will also lose all symbol discovery and completion suggestions for that package. Unfortunately, there's no way to tell pyright to "treat types as `Any` for some purposes but not for others". The same type information is used for everything. That's core to pyright's architecture. You can imagine how confusing it would be if the hover text, completion suggestions, and other language server features were operating on type information that's different from the type information used to generate type-related diagnostics. It would make it nearly impossible to diagnose type-related diagnostics.

So, your options are:
1. Disable type checking for your own code.
2. Disable the "python.analysis.useLibraryCodeForTypes". This tells pyright to use type information from an imported package _only if that package claims to provide type information_ (i.e. it contains a "py.typed" marker with inlined types or includes packaged type stubs). For all other packages, pyright will treat all imported symbols as `Any`, meaning that you won't see any false positive type checking errors, but you also won't see any completion suggestions.
3. If there is a specific problematic untyped packages that is causing you problems, see if there is a stub library published by someone. If so, install the stub library in your Python environment.
4. Selectively provide your own stubs for problematic packages. As you noted, you can create an `__init__.pyi` with an overridden `__getattr__` to start and fill in more as you see fit (e.g. add type details for specific functions or classes that you use frequently). Pylance also has a feature that will generate a "first draft" type stub for a package based on the limited type information provided by that package. This is a good way to get started. For more details about type stubs, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-stubs.md).

If there is an untyped library that you depend upon, you may want to reach out to the maintainers of that library to let them know that you would like to see them add type information. Most popular Python libraries have started to do this over the past couple of years.

**Comment by albireox** [comment]
Thanks a lot for the quick and detailed explanation. That helps me understand the relationship between symbol discovery and type checking.

Based on that, I think my best option when I'm dealing with some of those libraries is to set `useLibraryCodeForTypes` to false (by the way, it was on by default in my VSCode, which according to the docs shouldn't be the case). It would be useful to be able to defined what libraries one wants `useLibraryCodeForTypes` to be on/off for. In many cases pyright's type inference for external packages works quite well, and I'd prefer to keep it (especially since it would also keep access to the package symbols), but a combination of `useLibraryCodeForTypes` and custom type stubs is probably a good enough combination.

**Comment by erictraut** [comment]
Yes, `useLibraryCodeForTypes` is on by default in pylance but off by default if you are using pyright. That's because pyright is targeted at users who are focused on type checking, but pylance is targeted at users who are more interested in completion suggestions.

If you want to enable `useLibraryCodeForTypes` for most libraries but effectively disable it for a few, you can create an `__init__.pyi` with `__getattr__` for those few libraries. That will give you the combination you're looking for.
