### ISSUE TITLE
Automatic docstring word wrapping

### ISSUE THREAD

**Issue by VolkerSiep** [microsoft/pylance-release#3794]
My experience with VS Code and pylance so far is: _If I miss a feature, it's just because I didn't find it yet._ I assume the same to be the case here, that's why I'd like to ask carefully:

When writing docstrings (for using sphinx/autodoc), I would like the **text to wrap lines and indent automatically for connected pieces of text.** Ideally even, when editing the text, it should re-arrange the lines to avoid too long or unnecessarily short lines.

![image](https://user-images.githubusercontent.com/41128870/210071493-f0dfd5c3-dca7-482a-a504-a9a4cc08ed4b.png)
.. should be converted to ..
![image](https://user-images.githubusercontent.com/41128870/210071530-fb4c7dec-0a01-4875-a107-682ab6119589.png)

And, then, when I edit the comment:
![image](https://user-images.githubusercontent.com/41128870/210071616-a4aec177-3d87-4cdf-95da-e3ae9891a78f.png)
... it should ideally rearrange it as follows:
![image](https://user-images.githubusercontent.com/41128870/210071669-81149974-6386-4717-8a65-bf2089ba7dd2.png)

Does this functionality already exist :smile: ?

**Comment by rchiodo** [comment]
Is this what you're looking for?

![image](https://user-images.githubusercontent.com/19672699/210417145-953de4d7-149f-463c-a100-04f3539f4f15.png)

Setting that value to 'wordWrapColumn', it automatically wraps at the 80th column.

**Comment by rchiodo** [comment]
Granted that's not specific to doc strings. It applies to everything.

**Comment by VolkerSiep** [comment]
Hi, thanks for answering. But it's not really solving it, as this only wraps the **view** of the line, but the line is actually long, and pylint complains (and is imho right) about it.

![image](https://user-images.githubusercontent.com/41128870/210430616-554ee061-4ee8-47f7-9bc5-c9b88ad4d4e8.png)

So I was looking for something that splits and indents the line, so that the file content remains according to PEP standard - like other things get corrected with the "Format Selection" feature (which btw. leaves such long line comments in peace).

However, I must say, by writing the documentation with word-wrap enabled in connected paragraphs, it is then already much easier to just insert the line feeds when done.

**Comment by rchiodo** [comment]
No, sorry it's not something we have on our backlog. I recommend adding an enhancement request to the [discussions](https://github.com/microsoft/pylance-release/discussions/categories/enhancement) so people can up vote it.
