### ISSUE TITLE
Can the extension only download binary specific to my operating system and CPU architecture?

### ISSUE THREAD

**Issue by singularitti** [microsoft/pylance-release#3795]
Currently, it downloads all possible binaries, even on systems that I would never use:

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/25192197/210185305-f72dbe81-1461-45e3-bc24-a8bc9a35c9df.png">

**Comment by rchiodo** [comment]
Thanks for the issue.

Dupe of https://github.com/microsoft/pylance-release/issues/3646
