### ISSUE TITLE
Variable possibly unbound warning after enumerate?

### ISSUE THREAD

**Issue by TotallyNotChase** [microsoft/pylance-release#38]
Consider this code snippet-
```py
for i, val in enumerate(range(1, 11)):
    print(val)
print(i)
```
I get a `"i" possibly unbound: Pylance` on that last `print(i)`. But the variables in a `for....in` are accessible *after* that `for....in` too. As is the case here, this prints correctly. Should this be a valid warning?

More information [here](https://stackoverflow.com/questions/3611760/scoping-in-python-for-loops).

**Comment by erictraut** [comment]
Yes, this is a valid warning. In general a `for` loop can execute zero (or more) times depending on the iterator provided by the expression after the keyword `in`. If it executes zero times, the variable `i` will be unbound, and the program will crash. In this particular case, you know that the iterable `enumerate(range(1, 11))` will always cause the for loop to execute more than zero times, but a type checker doesn't have enough information to determine that from the type information it is provided. It must assume this is a possible bug.

If you want to use the target of a for loop (in your case, `i`) outside of the for loop, you should make sure it is initialized before the for loop. For example:
```
i = None
```

**Comment by ChrisLee63** [comment]
Hi, @erictraut, how to disable the kind of checking?

**Comment by erictraut** [comment]
This is a potential bug in your code, so the best thing to do is to change your code to eliminate the potential bug. 

If you really want to suppress the entire diagnostic rule, you can do so on a line-by-line basis with a "# type: ignore" comment, in a file-by-file basis using a "# pyright: reportUnboundVariables=false" comment, or across your entire project (or all projects) by setting the `python.analysis.diagnosticSeverityOverrides` setting for `reportUnboundVariables` to "none".

**Comment by ChrisLee63** [comment]
Thank you very much! It works!
