### ISSUE TITLE
Typing problem on indexing pandas DataFrame with a Callable

### ISSUE THREAD

**Issue by ischurov** [microsoft/pylance-release#3800]
## Environment data

-   Language Server version: 2022.12.20 (pyright 621d886b)
-   OS and version: Mac OS Ventrua 13.0.1 (22A400)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:55:37) 

## Code Snippet

```python
import pandas as pd # version 1.5.2

df = pd.DataFrame(dict(var=[1, 2, 3, 4]))
new_df = df[lambda x: x["var"] > 2]
```

## Expected behavior

No typing problems found. It is a usual way to filter elements of DataFrame using a Callable that returns pd.Series.

## Actual behavior

The expression `df[lambda x: x["var"] > 2]` gives the following problem:

```
Argument of type "(x: Unknown) -> Unknown" cannot be assigned to parameter "idx" of type "tuple[Unknown, ...] | Series[bool] | DataFrame | list[_str] | list[ScalarT@__getitem__] | Index | np_ndarray_str | np_ndarray_bool | Sequence[tuple[Scalar, ...]]" in function "__getitem__"
  Type "(x: Unknown) -> Unknown" cannot be assigned to type "tuple[Unknown, ...] | Series[bool] | DataFrame | list[_str] | list[ScalarT@__getitem__] | Index | np_ndarray_str | np_ndarray_bool | Sequence[tuple[Scalar, ...]]"
    "object" is incompatible with "tuple[Unknown, ...]"
    "object" is incompatible with "Series[bool]"
    "object" is incompatible with "DataFrame"
    "object" is incompatible with "list[_str]"
    "object" is incompatible with "list[ScalarT@__getitem__]"
    "object" is incompatible with "Index"
    "object" is incompatible with "np_ndarray_str"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

This problem was mentioned in #252 (see [comment](https://github.com/microsoft/pylance-release/issues/252#issuecomment-725372862_)), but does not seem to be solved there.

**Comment by ischurov** [comment]
Okay, I found the answer [here](https://github.com/pandas-dev/pandas-stubs/issues/256#issuecomment-1235774506): the problem is that lambda is typechecked as `(x: Unknown) -> Unknown`, and it's too broad.

**Comment by rchiodo** [comment]
Yeah this works for me:

```python
df2 = pd.DataFrame(dict(var=[1, 2, 3, 4]))

def varGt2(s: pd.DataFrame) -> pd.Series:
    return s["var"] > 2

new_df = df2[varGt2(df2)]
```

**Comment by ischurov** [comment]
@rchiodo Your example does not actually "fixes" my problem, as I pass Callable into `[]`, and in your example, it is `pd.Series` (as you already applied function to a dataframe). Nevertheless, I see that it does not seem to be pylance bug anyway: it's partially not a bug (it should fail, as `Unknown -> Unknown` is too broad) and partally upstream bug in pandas-stubs I referenced (it's still open as type-checking fails even on correctly specified Callables).

At the same time, it is quite unfortunate that syntax like `df[lambda x: x['var'] > 2]` cannot be correct from the typechecker's perspective unless we allow `Unknown -> Unknown` callables there, as there is no way to specify the signature of `lambda` function. I use this syntax as a default way to filter pandas DataFrames in the method chaining pattern, and there's basically no alternatives exists in pandas except of `.query` which I personally do not like at all. It seems that I need to add `# type: ignore` to any line where this syntax is used, and that's the only solution we have.
