### ISSUE TITLE
Show Definition Preview Hover doesn't pop up in some situation

### ISSUE THREAD

**Issue by loftusa** [microsoft/pylance-release#3801]
I use shift+tab all the time to look at documentation in jupyter lab. In VSCode, I have the keybinding set up for "Show Definition Preview Hover" (`editor.action.showDefinitionPreviewHover`) as shift+tab.

Unfortunately, in many situations, the full definition doesn't pop up. I think this generally is true when I'm calling a method rather than a function, e.g., see the picture below (which just says 'merge: Any' instead of the result of making a new Jupyter cell and typing `?pd.DataFrame.merge`, which is what I would like to see instead)
![image](https://user-images.githubusercontent.com/12386450/210038272-9c3979ef-b605-417b-8ff2-20e0edcb7f7e.png)

This has been my primary problem with vscode for a very long time and is essentially the only reason that I continue to use the browser-based jupyter notebook. I'd much prefer to work exclusively in vscode if I could. For instance, when I open up the same file in the browser and call shift+tab, this is the result:

![image](https://user-images.githubusercontent.com/12386450/210038876-fceb54f5-0a14-4473-9719-b1142fe63626.png)

Is there plans to extend the functionality of the Hover feature to make sure it always shows docstrings if they exist, even for method calls on an object in the middle of a line?

I've met many other people as well for whom this is the only reason they don't use VSCode for everything.

**Comment by rchiodo** [comment]
From your example I would guess that the 'merge' function isn't known to pylance and why it says "merge: Any". 

What version of pandas are you using? For me it shows this:

![image](https://user-images.githubusercontent.com/19672699/210620210-38ebf696-8d43-45e9-9126-b51d83fd9cbc.png)

It looks like the pandas definition for merge don't include a docstring, and it's why it doesn't show any documentation.

If I modify my pandas merge function with a docstring, I get something like so:

![image](https://user-images.githubusercontent.com/19672699/210620536-0ae751f6-04a1-4611-8c91-9fe9cb4d191d.png)

**Comment by rchiodo** [comment]
I'm using pandas 1.5.2. That and newer versions should be able to find the 'merge' function on the result for `ffill`.

**Comment by rchiodo** [comment]
The doc for the merge function would probably need to be added here:
https://github.com/pandas-dev/pandas-stubs/blob/86259cce61c5e77a0370de7cc316e2527cb4d4aa/pandas-stubs/core/frame.pyi#L1202
