### ISSUE TITLE
(Python) "Find All References" on any __init__ shows every constructor for every class

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/pylance-release#3802]
Python extension installed and nothing else.

I am evaluating VS Code as an alternative to Pycharm for a professional codebase because PyCharm is generally slow and I do not like the git support as much. We are not a software development shop, so we don't need a lot of fancy features, just usability in our ~500k line code base.

I have noticed several problems so far, but the biggest one is how VS Code finds references. Sometimes it shows fewer references than are actually in the code. Sometimes, many more, where it fails to distinguish between the same name function in different classes. See this extreme case below. Why is this happening?

Here is a toy workspace with main.py, class_a.py, and class_b.py to show the issue. I right click on __init__ of either ClassA or ClassB, and select "Find All References" and get 3 results in 3 files. PyCharm correctly shows that there's only one instance of __init__, and that's in main.py

![image](https://user-images.githubusercontent.com/108051416/210314920-f29f9e40-2ca0-4d7d-ad57-621bc2c472c8.png)

**Comment by rchiodo** [comment]
Thanks for the issue. 

It looks like we're not special casing `__init__` to match uses of the class name. Other functions wouldn't have this problem though.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023121-11-January-2023-PreRelease)

**Comment by tombohub** [comment]
I am having this problem with regular functions. Renaming function affects all functions with the same name.

**Comment by heejaechang** [comment]
@tombohub this issue is already closed. please open new issue with repro steps or logs so that we can take a look.

thank you.
