### ISSUE TITLE
Add more fine-grained code action kinds for `refactor.extract`

### ISSUE THREAD

**Issue by pokey** [microsoft/pylance-release#3803]
Currently, both the `Extract method` and `Extract variable` refactoring quick actions have the code action kind `refactor.extract`, which makes it impossible to target the one that you want directly.  It would be great for them each to have their own more specific code action kinds, similar to Typescript's `refactor.extract.constant` and `refactor.extract.function`

In addition, it would be great to have `preferred: true` on them

**Comment by heejaechang** [comment]
sure, we can make it. just curious. what are you trying to do with it?

**Comment by pokey** [comment]
In [Cursorless](https://www.cursorless.org/), we have an action that allows you to extract an expression to a variable using a voice command.  That action relies on this refactoring quick fix to perform that extraction.  The action works fine in Typescript, but in Python, we've had to introduce this very hacky workaround because there is no other way to directly get the right quick fix https://github.com/cursorless-dev/cursorless/pull/1207/files

**Comment by heejaechang** [comment]
I gave each refactoring a specific name (`refactor.extract.variable` and `refactor.extract.method`). I didn't give `preferred` since I wasn't sure which refactoring I should give `preferred` when both are available for the given span. especially since these are `refactoring`, not `quickfix`. 

anyway, if you give a specific refactoring kind, then only those will be available.

**Comment by pokey** [comment]
Amazing thank you!

I think I'd argue variable would be preferred. Also I guess you can't make it preferred just for its kind and not for the more generic extract kind?

Either way, no big deal at all to work around the preferred thing. The big thing is having specific kind like you've done

Thank you!

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023141-25-January-2023-PreRelease)
