### ISSUE TITLE
Guys, in VERY simple terms, not tech speak, how do I turn off the "reportOptionalMemberAccess" rule?

### ISSUE THREAD

**Issue by ZackPlauche** [microsoft/pylance-release#3809]
I'm using Python and Bueatiful Soup and trying to get text from a Tag.

It's saying ".text is not a member of None".

Trying to do this:
```python
title = soup.find('div', ...).text
```
But `.text` is underlined with that annoying error.

I'm on VSCode.

How do I turn that error off?

I'd say it's borderline a bug if there's no way to turn off a specific rule.

Please explain how to turn it off for simpletons.

**Comment by rchiodo** [comment]
Thanks for the issue.

Directions on different settings are described here:

https://github.com/microsoft/pylance-release/blob/main/README.md#settings-and-customization

The one you're looking for is diagnosticSeverityOverrides:

```json
"python.analysis.diagnosticSeverityOverrides": {
        "reportOptionalMemberAccess": "none",
    }
```
