### ISSUE TITLE
Unable to properly type hint Django models when adding a Meta class

### ISSUE THREAD

**Issue by sronveaux** [microsoft/pylance-release#3814]
Hello,

I'm not sure if this is the good place to ask for this, but I'm wondering how to properly type hint a [Meta class added inside a Django model](https://docs.djangoproject.com/en/4.1/ref/models/options/).

I'm using `VSCode 1.74.2` which includes `pylance 2022-12-20` which includes `django-stubs`. I'm opening my issue here as the reported error is coming from the `Pylance extension`.

My question is quite similar to what's discussed in issue #927. When a Meta class is defined inside a Model, errors like these start to occur:

> "Meta" overrides symbol of same name in class "Model"
>     "assessments.models.Species.Meta" is incompatible with "django.db.models.base.Model.Meta"
>     Type "Type[Meta]" cannot be assigned to type "Type[Meta]"

Here is how such a class is defined:

    from django.db import models
    class Species(models.Model):
        class Meta:
            verbose_name_plural = "species"

And here are the lines of `django-stubs` concerning this:
 
    class Model(metaclass=ModelBase):
        class DoesNotExist(ObjectDoesNotExist): ...
        class MultipleObjectsReturned(BaseMultipleObjectsReturned): ...
        class Meta: ...

So to continue the parallel with #927, I define a `Meta` class which is only mentioned to exist in the `stubs` file...

Are there other options than disabling the `reportIncompatibleVariableOverride` rule in this case ?

**Comment by heejaechang** [comment]
tagging @erictraut

**Comment by heejaechang** [comment]
@sronveaux by the way, you can ignore the error on that specific line using this `# pyright: ignore [reportIncompatibleVariableOverride]`

**Comment by erictraut** [comment]
The `reportIncompatibleVariableOverride` check is a strict-mode check. It's quite picky and opinionated, as many strict-mode checks are. 

I think your options are:
1. Disable `reportIncompatibleVariableOverride` for your project, for the specific files where you use this approach, or on a per-line basis.
2. Use a cast as follows:
```python
class Species(models.Model):
    class _Meta:
        verbose_name_plural = "species"

    Meta = cast(type[models.Model.Meta], _Meta)
```

**Comment by sronveaux** [comment]
Hi @heejaechang @erictraut 

Thanks for the fast reply and thanks for the list of options here!

I think I'll personally stick with disabling the rule where the problem occurs then...

Best regards!

**Comment by rayansostenes** [comment]
Another way of solving this problem, is changing the type of `Meta` on a `BaseModel` that every model on the project inherits from (I really common to have this on a Django project).

```python
# pyright: strict

from typing import Any, ClassVar

from django.db import models


class BaseModel(models.Model):
    Meta: ClassVar[type[Any]]  # pyright: ignore [reportIncompatibleVariableOverride]


class MyModel(BaseModel):
    my_field = models.CharField(max_length=10)
    my_other_field = models.CharField(max_length=10)

    class Meta:
        verbose_name = "My Model"
```

My initial ideia was to change the stub files to include something like a `DjangoMetaProtocol`:

```python
# typings/django/db/models/base.pyi
# ...
class DjangoMetaProtocol(Protocol):
    abstract: bool = ...
    verbose_name: str = ...
    verbose_name_plural: str = ...
    ...

class Model(metaclass=ModelBase):
    DoesNotExist: ClassVar[type[ObjectDoesNotExist]]
    MultipleObjectsReturned: ClassVar[type[BaseMultipleObjectsReturned]]

    Meta: ClassVar[type[DjangoMetaProtocol]]
    pk: Any = ...
    _state: ModelState
    _meta: Options[Any]
    ...
```
That was when I discovered that we cannot have [optional protocols members](https://peps.python.org/pep-0544/#support-optional-protocol-members) according to PEP-544.

This means what the `Meta` class would need to inherit from the protocol to lie to the type-checker, like:
```python
from django.db import models
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from django.db.models.base import DjangoMetaProtocol
else:
    DjangoMetaProtocol = object

class MyModel(BaseModel):
    my_field = models.CharField(max_length=10)
    my_other_field = models.CharField(max_length=10)

    class Meta(DjangoMetaProtocol):
        verbose_name = "My Model"
```
I didn't like the idea of having to add a base class to `Meta`.

**Comment by akvadrako** [comment]
According to https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults `reportIncompatibleVariableOverride` defaults to on, not just "strict".

**Comment by debonte** [comment]
> According to https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults `reportIncompatibleVariableOverride` defaults to on, not just "strict".

@akvadrako, this was a recent change in pyright with the introduction of the new `standard` type checking mode. `typeCheckingMode` now defaults to `standard` in Pyright, but still defaults to `off` in Pylance.

Are you seeing some sort of problem?

**Comment by goodeath** [comment]
Hey @sronveaux  , could:
```python
class Meta(models.base.Model.Meta):
    ...
```

solve it? I had the same problem and chosen this way

**Comment by tylerlaprade** [comment]
@rayansostenes, I love your solution! Do you not have `abstract = True` inside your base model's `Meta` class already, though? This precludes me from declaring a type for `Meta`.
<img width="1325" alt="image" src="https://github.com/microsoft/pylance-release/assets/5475199/16174015-bf55-4863-9d7a-dd30b70fc9c9">

**Comment by karolyi** [comment]
Wouldn't this just be solved with
```python
from django.forms.forms import BaseForm
from django.forms.models import ModelForm

from .models import Subscriber


class SubscriberForm(ModelForm):

    class Meta(BaseForm.Meta):
        model = Subscriber
        fields = ['email', 'message']
```

?

**Comment by karolyi** [comment]
On second thought (and testing), it wouldn't since in the runtime environment there is no `Model.Meta`.

This is why casting `Meta` (mentioned in https://github.com/microsoft/pylance-release/issues/3814#issuecomment-1376276168) will also yield a runtime error.

The simplest option is to disable `reportIncompatibleVariableOverride` for the meta lines.
