### ISSUE TITLE
Pylance no longer suggests auto imports and fails to suggest some obvious completions

### ISSUE THREAD

**Issue by thethiny** [microsoft/pylance-release#3816]
Similar to https://github.com/microsoft/pylance-release/issues/2159

## Environment data

-   Language Server version: v2023.1.10
-   OS and version: Windows 21H2 19044.2364 (Windows 10)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 (From Python website)
## Settings

```json
"[python]": {
        "editor.defaultFormatter": "ms-python.python"
    },
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.autoImportUserSymbols": true,
    "python.analysis.autoImportCompletions": true,
    "python.analysis.completeFunctionParens": true,
    "python.analysis.indexing": true,
    "python.analysis.packageIndexDepths": [
        {
            "name": "",
            "depth": 2,
            "includeAllSymbols": true,
        },
    ]
```

## Code Snippet

Code Snippet 1:
Pylance does not auto suggest methods from known libraries anymore.
Example:

```python
import datetime
os.maked # Suggestions show no suggestions
```
Pylance used to show a suggestion of import `os` and it will automatically import it since it knew `makedirs` is under `os`. Now it doesn't suggest importing `os` nor `makedirs` unless they're specified separately (no prefix/suffix).

Code Snippet 2:
Pylance does not auto suggest methods if they look similar to reserved keywords.

Example:

```python
import os
os.path # Works fine
os.path.i # suggests isdir and isfile
os.path.is # suggestions are 
os.path.isd # suggestions are off
os.path.isdi # suggests isdir
```

These 2 behaviors are very recent and becoming inconvenient.

## Expected behavior

Pylance to suggest the obvious method

## Actual behavior

Pylance uses too much CPU, VS Code Freezes, and then suggests nothing helpful.

**Comment by thethiny** [comment]
It is worth noting that comment https://github.com/microsoft/pylance-release/issues/2159#issuecomment-1376539942 suggested enabling some features, would still give the same problems above.

**Comment by thethiny** [comment]
I uninstalled all python extensions and reinstalled them all with the exception of Intelli-Sense, the issues above are no longer valid.

**Comment by dennisvd** [comment]
IntelliCode seems to conflict with Pylance at least for my VSCode it did. Thx or pointing it out.
