### ISSUE TITLE
reportGeneralTypeIssues

### ISSUE THREAD

**Issue by DomoticaVirginia** [microsoft/pylance-release#3818]
OS: Windows_NT x64 10.0.19045
Visual Studio Code 1.74.2
Language: Python
Extension: Pylance v2023.1.11

Code:
changed_s = dict((i, False) for i in range(5))
changed_s[1] = True

Regarding the last statement the error message is:
<<Argument of type "Literal[True]" cannot be assigned to parameter "__value" of type "Literal[False]" in function "__setitem__"
  "Literal[True]" cannot be assigned to type "Literal[False]"Pylance[rep]>>

Thank you

**Comment by erictraut** [comment]
You can fix this by providing a type annotation for the variable `changed_s`.

```python
changed_s: dict[int, bool] = dict((i, False) for i in range(5))
changed_s[1] = True
```

Or, if you're not interested in static type checking, you can disable these messages by setting `python.analysis.typeCheckingMode` to "off".

For more information about static types, type inference, etc., refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md).
