### ISSUE TITLE
Completion Tooltip Intermittently Disappearing

### ISSUE THREAD

**Issue by savannahostrowski** [microsoft/pylance-release#382]
## Environment data

-   Language Server version: 2020.9.5
-   OS and version: Windows, VSCode 1.49
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5

## Expected behaviour

I'd expect that the tooltip for the completion remains open as I'm typing the function name.

## Actual behaviour
Tooltip intermittently hides as I'm typing.
![bug_completion](https://user-images.githubusercontent.com/8949415/93522218-fcc21b00-f8e5-11ea-8d3f-2921a6e0c8f1.gif)

**Comment by jakebailey** [comment]
I'm thinking this might be fixed via: https://github.com/microsoft/pyright/commit/90c8cdd72c5a6e7480c9ae982b02f809ba2c2d49

But we'll have to check.

**Comment by erictraut** [comment]
Yes, I discovered this bug independently and fixed it. I'm confident it's the same issue.

**Comment by jakebailey** [comment]
We checked, and it's fixed.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.6, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202096-23-september-2020
