### ISSUE TITLE
Long analysis time when using package (scipy)

### ISSUE THREAD

**Issue by aukeschaap** [microsoft/pylance-release#3821]
When writing a small project I noticed that code analysis time was significantly longer than for large projects I have worked on (~2 seconds vs. ~100ms). This lead me to investigate. I have produced a minimum reproducible example, which can be found below. I've also included a code snippet and log trace for an example that works as expected, to indicate that this code snippet isolates the problem for me. It seems the issue is localized to using `scipy`.

This might be related to:
- #3470, as the issues experienced are similar in nature, and `scipy` is also in the user's environment.
- #2098, as the issues experienced are somewhat similar in nature.

<h2> Problem </h2>

<h3> Environment data </h3>

-   Language Server version: 2023.1.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11
-   python.analysis.indexing: false
-   python.analysis.typeCheckingMode: off
-   `venv`:
```
Package    Version
---------- -------
numpy      1.24.1
pip        22.3
scipy      1.10.0
setuptools 65.5.0
```

<h3> Code Snippet </h3>

```python

import scipy.sparse as sp

def A(N):
    sp.bmat([])
```

<h3> Repro Steps </h3>

1. Modify the code. E.g., add an enter at line 6.
2. Analysis is triggered (which takes ~1.7 seconds).

<h3> Expected behavior </h3>

Analysis of the file should not take this long.

<h3> Actual behavior </h3>

Analysis takes ~1.7 seconds.

<h3> Logs </h3>

```
(2892) Background analysis message: setFileOpened
(2892) Background analysis message: markFilesDirty
(2892) [FG] parsing: c:\Users\aukes\Documents\repos\local\temp\something.py (1ms)
(2892) [FG] binding: c:\Users\aukes\Documents\repos\local\temp\something.py (0ms)
(2892) Background analysis message: analyze
(2892) [BG(1)] analyzing: c:\Users\aukes\Documents\repos\local\temp\something.py ...
(2892) [BG(1)]   parsing: c:\Users\aukes\Documents\repos\local\temp\something.py (1ms)
(2892) [BG(1)]   binding: c:\Users\aukes\Documents\repos\local\temp\something.py (0ms)
[Info  - 14:27:25] (2892) SourceFile: Received fs event 'change' for path 'c:\Users\aukes\Documents\repos\local\temp\something.py'
(2892) [BG(1)]   checking: c:\Users\aukes\Documents\repos\local\temp\something.py (1070ms)
(2892) [BG(1)] analyzing: c:\Users\aukes\Documents\repos\local\temp\something.py (1071ms)
(2892) Background analysis message: getSemanticTokens delta
(2892) [BG(1)] getSemanticTokens delta previousResultId:1673443376119 at c:\Users\aukes\Documents\repos\local\temp\something.py (0ms)
(2892) Background analysis message: markFilesDirty
(2892) Background analysis message: analyze
(2892) [BG(1)] analyzing: c:\Users\aukes\Documents\repos\local\temp\something.py ...
(2892) [BG(1)]   checking: c:\Users\aukes\Documents\repos\local\temp\something.py (1750ms)
(2892) [BG(1)] analyzing: c:\Users\aukes\Documents\repos\local\temp\something.py (1750ms)
(2892) Background analysis message: resumeAnalysis
```

<details> 
<summary><h2> Additional example </h2></summary>
In this additional example the reproduction steps are the same, but the issue does not occur, as can be seen by the logs. The environment is the same.

<h3> Code Snippet </h3>

```python

import numpy as np

def A(N):
    np.array([])

```

<h3> Logs </h3>

```
(2892) Background analysis message: setFileOpened
(2892) Background analysis message: markFilesDirty
(2892) [FG] parsing: c:\Users\aukes\Documents\repos\local\temp\something.py (1ms)
(2892) [FG] binding: c:\Users\aukes\Documents\repos\local\temp\something.py (0ms)
(2892) Background analysis message: analyze
(2892) [BG(1)] analyzing: c:\Users\aukes\Documents\repos\local\temp\something.py ...
(2892) [BG(1)]   parsing: c:\Users\aukes\Documents\repos\local\temp\something.py (1ms)
(2892) [BG(1)]   binding: c:\Users\aukes\Documents\repos\local\temp\something.py (0ms)
(2892) [BG(1)]   checking: c:\Users\aukes\Documents\repos\local\temp\something.py (39ms)
[Info  - 14:54:52] (2892) Heap stats: total_heap_size=86MB, used_heap_size=78MB, total_physical_size=86MB, total_available_size=4015MB, heap_size_limit=4096MB
(2892) [BG(1)] analyzing: c:\Users\aukes\Documents\repos\local\temp\something.py (40ms)
(2892) Background analysis message: getSemanticTokens delta
(2892) [BG(1)] getSemanticTokens delta previousResultId:1673445288413 at c:\Users\aukes\Documents\repos\local\temp\something.py (0ms)
(2892) Background analysis message: resumeAnalysis
[Info  - 14:54:53] (2892) SourceFile: Received fs event 'change' for path 'c:\Users\aukes\Documents\repos\local\temp\something.py'
(2892) Background analysis message: markFilesDirty
(2892) Background analysis message: analyze
```

</details>

**Comment by rchiodo** [comment]
Scipy is notoriously slow for analysis because it isn't typed. The scipy stubs we have aren't complete either: https://github.com/microsoft/python-type-stubs/tree/main/scipy-stubs

Because the entire library isn't typed, inferring types from analyzing code needs to be done. This is a LOT slower. 

This analysis time should only be when first opening the file. It should be much faster on subsequent edits.

**Comment by rchiodo** [comment]
@gramster have you been trying anything with your automated stub generation for scipy?

**Comment by erictraut** [comment]
The best solution here is for scipy to include inline type annotations so type inference isn't required. Most major Python libraries have moved in this direction, but scipy is unfortunately a holdout.

If this is important to you, I recommend filing a feature request with the scipy maintainers. Absent feedback from scipy users, they are unlikely to invest the effort to add the necessary type information.

**Comment by aukeschaap** [comment]
Thanks, I know enough.
