### ISSUE TITLE
Inferred types after an any(...) check includes False-y types

### ISSUE THREAD

**Issue by lojack5** [microsoft/pylance-release#3826]
## Environment data

-   Language Server version: 2023.1.10
-   OS and version: Windows 11 21H2
-   Python version: CPython 3.11.0 64-bit is this reproducer, but the same experience on 3.9, 3.10, 3.12a2.  Not currently in a venv, but I observe the same behavior there as well.

## Code Snippet

```python
from typing import Any


def foo(a: Any) -> int | None:
    if isinstance(a, int):
        return a
    return None


lst1 = [1, 2, 3, None, 4]
lst2 = [1, 2, 3, 4]

t1 = tuple(map(foo, lst1))  # Correctly inferred as tuple[int | None, ...]
t2 = tuple(map(foo, lst2))  # Correctly inferred as tuple[int | None, ...]


if all(t1):
    sum = 0
    for x in t1:
        sum += x    # Incorrectly inferred as int | None
    print('1: All ints, sum:', sum)

if all(t2):
    sum = 0
    for x in t2:
        sum += x    # Incorrectly inferred as int | None
    print('2: All ints, sum:', sum)

```

## Repro Steps

1. Input the above code, see errors in the IDE

## Expected behavior

I don't know if this should be a feature request instead, but I expected pylance to see the `all` check and infer that none of the items in the iterable could be a Falsy value, and hence rule out the `| None` part of the type inferrence.  If this is expected behavior, fair.  I'm currently marking the instance of this in my actual code with a `# type: ignore`, but it would be nice to not have to.

Also just want to note, yes this simple of an example I wouldn't write this way, but it showcases the issue with the least amount of code.

## Actual behavior

Pylance still sees the items in the tuple as `int | None`.

## Logs

```
[Info  - 11:15:50 PM] (19836) Pylance language server 2023.1.10 (pyright bbf0ae78) starting
[Info  - 11:15:50 PM] (19836) Server root directory: c:\Users\Lojack\.vscode\extensions\ms-python.vscode-pylance-2023.1.10\dist
[Info  - 11:15:50 PM] (19836) Notebook support: LSP
[Info  - 11:15:50 PM] (19836) Interactive window support: LSP
[Info  - 11:15:50 PM] (19836) Starting service instance "<default>"
[Info  - 11:15:50 PM] (19836) No pyproject.toml file found.
[Info  - 11:15:50 PM] (19836) Setting pythonPath for service "<default>": "C:\Code\Python-3-11\python.exe"
[Warn  - 11:15:50 PM] (19836) stubPath typings is not a valid directory.
[Info  - 11:15:50 PM] (19836) Assuming Python version 3.11
[Info  - 11:15:50 PM] (19836) Assuming Python platform Windows
[Info  - 11:15:50 PM] (19836) Searching for source files
[Info  - 11:15:50 PM] (19836) No source files found.
[Info  - 11:15:50 PM] (19836) No pyproject.toml file found.
[Info  - 11:15:50 PM] (19836) Setting pythonPath for service "<default>": "C:\Code\Python-3-11\python.exe"
[Warn  - 11:15:50 PM] (19836) stubPath typings is not a valid directory.
[Info  - 11:15:50 PM] (19836) Assuming Python version 3.11
[Info  - 11:15:50 PM] (19836) Assuming Python platform Windows
[Info  - 11:15:50 PM] (19836) Searching for source files
[Info  - 11:15:50 PM] (19836) No source files found.
[Info  - 11:15:50 PM] (19836) Background analysis(1) root directory: c:\Users\Lojack\.vscode\extensions\ms-python.vscode-pylance-2023.1.10\dist
[Info  - 11:15:50 PM] (19836) Background analysis(1) started
```

**Comment by erictraut** [comment]
Type narrowing doesn't apply to `all` function calls. For supported type narrowing patterns, please refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-concepts.md#type-guards).

If you want this to work without a `# type: ignore`, you can define your own user-defined type guard, as defined in [PEP 647](https://peps.python.org/pep-0647/). It would look something like this:

```python
T = TypeVar("T")

def is_tuple_without_nones(x: tuple[T | None, ...]) -> TypeGuard[tuple[T, ...]]:
    return all(x)

if is_tuple_without_nones(t1):
    sum = 0
    for x in t1:
        sum += x
    print("1: All ints, sum:", sum)
```

**Comment by lojack5** [comment]
I hadn't dug into the PEP.  If it's not there, it's not there and I wouldn't expect pylance to support it.  Unfortunately my actual usage pattern doesn't really make it worthwhile to make a one off method for this, I'll just keep using `# type: ignore` in the few places it comes up.

Thanks for the response!
