### ISSUE TITLE
Incorrect type checking error using type alias

### ISSUE THREAD

**Issue by Shapedsundew9** [microsoft/pylance-release#3829]
## Issue
EDIT: Sorry not an actual type alias but a compatible type - could not change title after submission.
Pretty sure this should not be an error for the assignment to a.
![image](https://user-images.githubusercontent.com/16618209/212159129-1e4fae7c-265a-451a-8e25-513cd3c51e72.png)

## Environment data
Pylance language server 2023.1.10 (pyright bbf0ae78)

Ubuntu 22.04.1 LTS

VS Code
Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:57:40.428Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-57-generic
Sandboxed: No

Python 3.11.1

## Code Snippet
```python
from typing import NewType, Type
T = NewType('T', tuple[int, int])

a: T = (0, 1)
b: tuple[int, int] = (0, 1)
```

## Expected behavior
No error

## Actual behavior
Type checking says types are incompatible is invalid.

**Comment by rchiodo** [comment]
Thanks for the issue.

I believe 'NewType' is exactly for this case. It's supposed to error in this situation.

This should work:

```python
a: T = T((0, 1))
```

For example, this same case fails for a 'NewInt'

```python
NewInt = NewType('NewInt', int)

b: NewInt = 4
```

But this doesn't:


```python
b: NewInt = NewInt(4)
````

**Comment by Shapedsundew9** [comment]
I had not realized that. I think I understand the intent re-reading the python docs. Sorry for the distraction.
