### ISSUE TITLE
Completions for kwargs showing while in the middle of a string

### ISSUE THREAD

**Issue by savannahostrowski** [microsoft/pylance-release#383]
## Environment data

-   Language Server version: 2020.9.5
-   OS and version: Windows, VSCode version 1.49
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5

## Expected behaviour

I don't get completions while in the middle of typing out a string-type param.

## Actual behaviour

If I type "." while in a string-type param while invoking a function, I get a completion list of kwargs.
![bug_function_invocation](https://user-images.githubusercontent.com/8949415/93522491-63473900-f8e6-11ea-8647-f3eab4f91898.gif)

**Comment by jakebailey** [comment]
This is related to #163, though we don't want to eliminate completions in strings in the context of type annotations.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020111-11-november-2020
