### ISSUE TITLE
No brackets autocompletion with python.analysis.completeFunctionParens set to true when python.languageServer is set to Pylance

### ISSUE THREAD

**Issue by nerfi58** [microsoft/pylance-release#3831]
## Environment data

-   VS Code
Version: 1.74.3 (system setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
-   Language Server version: 2023.1.20
-   OS and version: Windows 11 Pro 22H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.1

I believe it has happened after VS Code or extension update, previously it worked fine.

## Code Snippet

![Jedi](https://user-images.githubusercontent.com/39164765/212195969-15d119df-c309-473c-804d-c2303ff876c3.gif)
![Pylance](https://user-images.githubusercontent.com/39164765/212195977-f48591db-397b-4af3-9a5d-3c13d471183f.gif)

## Expected behavior

Brackets are added when `python.languageServer` is set to `"Pylance"`.

## Actual behavior

Brackets are added only when `python.languageServer` is set to `"Jedi"`.

**Comment by rchiodo** [comment]
Thanks for the issue.

I can definitely repro. Not sure what's happening yet.

**Comment by rchiodo** [comment]
It was a mistake introduced in 2023.1.20. Should be easy to fix. Hope to have it in 2023.1.31 (next week)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023131-18-January-2023-PreRelease)
