### ISSUE TITLE
VScode is not completing my code.

### ISSUE THREAD

**Issue by Randhal1** [microsoft/pylance-release#3837]
<h3> Environment data </h3>

-   Language Server version: 2023.1.20
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
