### ISSUE TITLE
How to best deal with the inconsistencies between pyright, VS, and VSC?

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/pylance-release#3838]
I am working on a python project about which pyright reports 5 errors and no warnings, when opened in VSC "no problems have been detected" is reported and VS as usual hallucinates, in this case about 91 warnings.

My problem is that this is a joint project and the errors stem from somebody else who refuses to acknowledge them as he is using VSC. Actually there were hundreds of errors which I manually tracked and fixed based on the pyright reporting. This is really tedious and I am a bit lost why VS or VSC cannot simply show in the GUI what pyright is reporting.

What is the suggested best-practice to deal with these inconsistencies on joint projects?

**Comment by erictraut** [comment]
Here are the primary reasons why pylance may produce different results from pyright:
1. Pylance defaults `useLibraryCodeForTypes` to true, whereas pyright defaults to false. You can override the default in your settings or your pyrightconfig.json or pyproject.toml config file.
2. Pylance bundles additional stubs that pyright does not. These stubs are located in [this repo](https://github.com/microsoft/python-type-stubs), so you can clone the applicable stubs and check them in to your repo (in the "typings" subdirectory, typically).
3. Pylance and pyright are both released weekly, but pylance normally lags pyright by one week (unless you use the insiders build of pylance, in which case they are in sync). This means that there could be temporary behavior differences due to minor bug fixes, etc. This is rare though.

Getting consistent behavior with VS is more difficult because new versions of VS are released on a less regular basis, so pyright and pylance bug fixes and enhancements will lag in VS.

**Comment by judej** [comment]
Thanks for the report. Are you running Pylance as the language server in VSCode? What are some of the examples of errors that Pyright reports that VSCode doesn't?

**Comment by excubo-jg** [comment]
Many thanks for providing possible reasons for the deviations. pyright was reporting errors because for instance variable creations were done in modules which should have happened in __init__.py. The errors were not related to external libraries.

Pylance is the only Python-related extension installed in VS Code.

Both VS and VSC correctly report additional errors if one introduces any in the respective GUIs. So I am assuming that pyright is working. But both do not report the existing errors which pyright reports in the CLI when loading the project.

**Comment by erictraut** [comment]
As an experiment, you could temporarily uninstall pylance and install the pyright VS Code extension. To do this, manually uninstall the Pylance extension, then set `python.analysis.languageServer` to "None". (This tells the Python extension not to load any language server. The Pyright extension will load itself.) Then search for Pyright in the VS Code extensions panel and install it. See if that gives you the same behavior as the Pylance extension within VS Code. If it doesn't, please provide specifics of the different behaviors you're seeing, preferably with code samples.

Once you're done with this experiment, you can undo it by uninstalling the Pyright extension, setting `python.analysis.languageServer` back to "Pylance" and then re-installing the Pylance extension.

**Comment by excubo-jg** [comment]
Exactly the same behavior - also reinstalling Pylance did not change anything

**Comment by erictraut** [comment]
OK, just to confirm... you're seeing a different set of diagnostics reported between the Pyright VS Code extension and pyright when run from the command line? Can you provide an example?

**Comment by excubo-jg** [comment]
From earlier team communication pyright at the time reported close to 4000 errors, primarily "Type annotation not supported for this statement". The message in VSC-Problems read "No problems have been detected in the workspace."

**Comment by excubo-jg** [comment]
I double checked and Pylance in the lower right corner gives exactly the same information about conda env and python version as is the dedicated conda-powershell in which pyright is run. Also, VS is set to the same env for the project in the Solution Explorer. From all I see the environments should be the same.

**Comment by excubo-jg** [comment]
With VS the error count of 0 will get updated if one opens a file with errors. Which is still a problem as a it does not indicate how many errors there are in total until one opens all the relevant files. Also, VS will get lost rather soon (described here https://github.com/microsoft/PTVS/issues/7274) and then won't report any existing errors anymore but floods the zone with warnings. These are of the type import "'local.file' could not be resolved" and all constants declared in other files are "not defined". Pyright-CLI is unaware of these warnings.

**Comment by erictraut** [comment]
If you want consistency between pyright and your editor, I recommend using VSC rather than VS.

With VSC (and pylance), you can set "python.analysis.diagnosticMode" to "workspace" to show all of the diagnostics in the workspace. By default, this setting is "openFilesOnly".

**Comment by excubo-jg** [comment]
Interesting. Still I think that VS could provide much better support if the issues in the interface were fixed.

Thanks. I was not aware of that parameter. It would be more precise if the message in the Problems tab would only read "No problems have been detected in the _workspace_" if the diagnosticMode is actually set to "_workspace_". I was under the impression that a scan of the workspace had been executed.
Unfortunately, changing the setting to "workspace" causes only a delay of a couple of seconds as more files seem to get scanned, but no change to the "no problems have been detected" message - even after opening a file with CLI-reported errors. In VS this updates the error count (as long as VS keeps its ducks in a row)

**Comment by excubo-jg** [comment]
I built a tiny test repo - VSC correctly reported the error the unopened faulty file with the "workspace" setting.

In the repo discussed above, using the same setting VSC counts down from 39 to zero files and then reports "no problems have been detected" while Pyright detects 3 errors in 2 of the 39 files. VS this time immediately went into warnings-land so no errors.

**Comment by erictraut** [comment]
Are you able to share the test repo with us?

**Comment by excubo-jg** [comment]
I set-up a private github repo DemoProject and invited msfterictraut.

At my end pyright reports 6 errors in 2 files. VSC reports "no problems detected" when opening the directory.

**Comment by erictraut** [comment]
Thanks for making the github repo available. I downloaded the code and selected a Python 3.11 environment. I then ran the command-line version of pyright (1.1.291), and I received 6 errors and 1 warning. 

```
/DemoProject-main/main.py
  /DemoProject-main/main.py:10:6 - warning: Import "tqdm" could not be resolved from source (reportMissingModuleSource)
/DemoProject-main/dominion/kingdom_configuration.py
  /DemoProject-main/dominion/kingdom_configuration.py:35:57 - error: Type annotation not supported for this statement (reportGeneralTypeIssues)
  /DemoProject-main/dominion/kingdom_configuration.py:36:55 - error: Type annotation not supported for this statement (reportGeneralTypeIssues)
  /DemoProject-main/dominion/kingdom_configuration.py:37:53 - error: Type annotation not supported for this statement (reportGeneralTypeIssues)
  /DemoProject-main/dominion/kingdom_configuration.py:38:59 - error: Type annotation not supported for this statement (reportGeneralTypeIssues)
  /DemoProject-main/dominion/kingdom_configuration.py:29:70 - error: Expression of type "None" cannot be assigned to parameter of type "KingdomConfiguration"
    Type "None" cannot be assigned to type "KingdomConfiguration" (reportGeneralTypeIssues)
/DemoProject-main/dominion/game_flow/cards_setup.py
  /DemoProject-main/dominion/game_flow/cards_setup.py:112:154 - error: Cannot access member "blocked_cards" for type "KingdomConfiguration"
    Member "blocked_cards" is unknown (reportGeneralTypeIssues)
6 errors, 1 warning, 0 informations 
```

I then used the Pyright extension in VS Code (1.1.291) and set `python.analysis.diagnosticMode` to "workspace". It produced the same 6 errors and 1 warning. So I'm seeing exactly the same results, as expected.

I then installed the latest published version of Pylance and set `python.analysis.typeCheckingMode` to "basic". I once again received the same 6 errors and 1 warning.

This all appears to be working as expected.

**Comment by excubo-jg** [comment]
Reinstallung VSC and conda did not change the outcome, e.g. warning about tqdm displayed but none of the errors. We have the problem (no errors reported) on two independently managed machines. Any suggestions what to try next to get this resolved?

**Comment by erictraut** [comment]
I provided detailed steps above, including the settings changes I made. Please follow these steps closely, and it should work for you. I'm quite sure that you're simply misconfiguring something.

**Comment by excubo-jg** [comment]
Many thanks, the relevant line fell through the cracks on the first try. Now we have synchronicity between VSC and Pyright. 

Which is good, still the experience overall is suboptimal: If I get this correct then VS and Pyright report the same level of errors out of the box, but not VSC. None provides pyright's full report and it seems only in VSC a parameter can be set to match scope. VS rather sooner than later changes reporting from factual to unhelpful warnings. The latter problem still needs to be addressed and I'd appreciate if the default reporting were better aligned as one cannot assume that everyone on a project knows all setting idiosyncrasies of all programs.

**Comment by erictraut** [comment]
We make it possible to get the same results from pyright running in VS Code and the command-line version of pyright. If you want consistent results between your editor and your automation, I recommend you use VS Code, not VS.

> None provides pyright's full report

I'm not sure what you mean by this. If you properly configure pylance (in VSC) and pyright, you should receive the same diagnostic list as you do with pyright.

> I'd appreciate if the default reporting were better aligned

There are good reasons why we selected the respective default settings for pylance and pyright. The former is focused more on language server features, and the latter is focused on static type checking. The defaults for each are tuned for their respective use cases. Changing the defaults to accommodate your request would inconvenience the majority of pylance and pyright users, so it's unlikely we would make such a change.

**Comment by excubo-jg** [comment]
Don't know which information I should be adding here. There is no bug but I think the VS reporting needs to get changed as it keeps confusing people on the project:  
The message "no problems have been detected in the workspace" should only be displayed when pyright has actually checked all files in the workspace. As long as the default settings are not changed by the user, the message is misleading and gives the user a false impression about the state of the project if errors/warnings are present in unopened files.

**Comment by blakeNaccarato** [comment]
For further information on Pylance/Pyright discrepancies, see discussion https://github.com/microsoft/pylance-release/discussions/3638 and issue https://github.com/microsoft/pylance-release/issues/3045. Feel free to add to that discussion regarding general concerns about this.

For resolving discrepancies in the future, keep in mind the following:

- You have to keep type stubs up to date in the project repo which correspond to the additional stubs bundled with Pylance/VSCode
- Being careful about your `python.analysis...` settings in `settings.json`, and your configs in `pyrightconfig.json`. All of these have to be configured carefully to minimize cross-platform/IDE discrepancies.

See my helper repo, https://github.com/blakeNaccarato/pylance-stubs-unofficial, that (mostly) resolves these discrepancies by bundling most of the stubs bundled with Pylance each update. There is some fancy type stub layering/resolution going on in Pylance that my repo doesn't completely account for, but it does reduce noise.

**Comment by erictraut** [comment]
@judej, I think it would be good to publish some documentation on the topic of using pylance and pyright (CLI) together. This is increasingly popular, and there are a number of pitfalls that can be avoided with the proper guidance. I think it might be better to publish this documentation in the pylance-release project rather than pyright since pylance is built on top of pyright.

**Comment by erictraut** [comment]
@judej, here's [another question](https://github.com/microsoft/pyright/issues/4784) related to this. I'm spending quite a bit of time answering questions and providing guidance on this topic. Documentation is badly needed here. Please let me know how you'd like to proceed.

**Comment by gramster** [comment]
@judej, if documentation was created, can this issue be closed?

**Comment by davetapley** [comment]
@erictraut can you edit [your comment](https://github.com/microsoft/pylance-release/issues/3838#issuecomment-1387510630) ⬇️  to reflect [this no longer being the case](https://github.com/microsoft/pyright/commit/5d6eacd5e14e9087802c79bb41be299469732f26). It confused me for while there 🤪 🙏🏻

> Pylance defaults useLibraryCodeForTypes to true, whereas pyright defaults to false.
