### ISSUE TITLE
python.analysis.extraPaths should support "${workspaceFolder}"

### ISSUE THREAD

**Issue by johneast** [microsoft/pylance-release#384]
When setting the path to an environment variable file, the Python extension allows the following format
```
"python.envFile": "${workspaceFolder}/.env",
```

We have multiple python projects in one repo and it's advantageous to be able to open the IDE at the root of the repo, so being able to specify extra paths in the `settings.json` as relative to the workspace folder would be useful. However it seems that only absolute paths work. So to get Pylance to work with extra paths I would like to be able to do the following

```
{
        "python.analysis.extraPaths": [
                "${workspaceFolder}/proj1",
                "${workspaceFolder}/proj2",
                "${workspaceFolder}/proj3"
    ]
}
```

**Comment by jakebailey** [comment]
Relative paths should work. Does `./proj1` not work? Paths like this are in our troubleshooting (and would have worked previously with MPLS).

**Comment by jakebailey** [comment]
FWIW we don't support these replacements in any config (at least not consistently, I recall one place where we do but it's an exception); #275 would only end up working (after I have time to fix it) because .env file processing is handled by the core extension (not us).

**Comment by johneast** [comment]
You're right. Changing the path to "./proj1" works. Thanks for the suggestion.

**Comment by jakebailey** [comment]
Thanks for confirming. It might be the case that we try to implement these replacements in the future, but previously we've stuck with the relative paths as it's a bit less "magical". I know there are other replacements the Python extension does that may be of use.
