### ISSUE TITLE
Bad code insertion when typing Calalble params as ellipsis 

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pylance-release#3841]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When typing out a `Callable` type using the ellipsis for the params... "Callable" is automatically inserted after typing the first period of the ellipsis

## Steps to reproduce:

```python
from typing import Callable

f  # manually try to type this as Callable[..., None]
# I end up with this:
# f: Callable[Callable.]
```

https://user-images.githubusercontent.com/27844407/212563493-ea6d5417-24b4-4e43-a44f-7d4c50bcc8a9.mov

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

envFile: "<placeholder>"

languageServer: "Pylance"

linting
• mypyEnabled: true
• pylintArgs: "<placeholder>"

testing
• pytestArgs: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: true

```

</p>
</details>

Extension version: 2022.20.2
VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No
Connection to 'SSH: lambda' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 8106252b-2e2a-45d6-a119-685169d4080a|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: lambda' could not be established  Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.1.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023141-25-January-2023-PreRelease)
