### ISSUE TITLE
Get a list of methods for override in subclass

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/pylance-release#3842]
Type: <b>Feature Request</b>

PyCharm has a modal that allows me to view all non-overriden methods and select which ones to override. Can VSCode's Python extension offer a similar feature?

Extension version: 2022.20.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

**Comment by judej** [comment]
Thanks for the request. Will add this to the enhancement discussion for [Offer completions when overriding class methods](https://github.com/microsoft/pylance-release/discussions/2950#top)
#2950
