### ISSUE TITLE
Python does not know autocomplete information when submodule is imported

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/pylance-release#3845]
Type: <b>Bug</b>

If I have a module `my_mod/__init__.py` with content:

```py
def x(s: str) -> int:
    return int(s)
```

and a module `my_mod/y.py` with content:

```py
def y(i: int) -> str:
    return str(i)
````

and in a file `run.py` I have the following content: 

```py
import my_mod.y

x_val = my_mod.x("5")
```

VSCode will not know types for `x_val` unless I add an additional `import my_mod` .

Extension version: 2022.20.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:05:47.808Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 2b0708f4-d206-4f56-bb5c-21ca647cc418|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
fim-prod:30623723
a9j8j154:30646983

```

</details>

**Comment by erictraut** [comment]
This is by design. Your code is relying on side effects of the Python import loader. Such side effects cannot generally be modeled statically, and it's not a good idea to rely on them. If you want to import from `my_mod`, you should include an `import my_mod` in your code rather than relying on the fact that `my_mod` will be implicitly loaded and initialized as a side effect of importing `my_mod.y`.
