### ISSUE TITLE
Consume new overload apis added.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#3850]
see https://github.com/microsoft/pyright/pull/4492

Previously, we didn't use context (such as arguments to the call expression) to select the best matches among overloaded functions and ended up showing all overloads in various features. The new API will let us filter out inapplicable overloads and show only what matters to reduce noise.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.4.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023411-5-April-2023-PreRelease)
