### ISSUE TITLE
Show Python method's API documentation from a URL on hover in VSCode

### ISSUE THREAD

**Issue by austinleedavis** [microsoft/pylance-release#3852]
**Allow user to configure VSCode to point toward a URL containing a Python method's online documentation so the online documentation appears on hover.**

For example, [PyTorch API Docs](https://pytorch.org/docs/stable/index.html) are hosted online and the method hierarchy is simple to navigate. When I hover of a method from the PyTorch library, I'd like to see the API documentation from that URL, **not** just the various method signatures.

This feature is available to Java Developer using Eclipse: The user can configure Eclipse to pull API documentation from a URL (e.g., the [List API JavaDocs](https://docs.oracle.com/javase/8/docs/api/java/util/List.html)) on a project-by-project basis by configuring the JavaDocs in the project's build path. Here's an example of the popup that shows up in Eclipse for the `List.of()` method:

---
[![enter image description here][1]][1]

---

Notice that along with the method signature is a short description of the method ("returns an unmodifiable list...") along with additional helpful information (e.g., Type parameters, Parameters, and Returns)

To clarify: I'm not only looking for a popup showing the method signature(s), but also the associated documentation *hosted at an online url*. For example: VSCode only displays the method signatures for `torch.rand()`, but the PyTorch API documentation includes the [full description](https://pytorch.org/docs/stable/generated/torch.rand.html).

  [1]: https://i.stack.imgur.com/rOSny.png

**Comment by debonte** [comment]
The standard way for tools to obtain documentation for Python library types/methods/etc is via docstrings. PyTorch does include docstrings for some things. Here's an example:

![image](https://user-images.githubusercontent.com/12820898/213830503-0594e7e0-c155-4a39-a687-a6ea2248d1e6.png)

But they seem inconsistent with their docstrings. Looking at their [issue tracker](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+docstring+label%3A%22module%3A+docs%22+is%3Aopen), they have a fair number of bugs on missing docstrings. They also encourage users to submit PRs with docstring fixes. So you could help them there.

I also saw some cases ([example](https://github.com/pytorch/pytorch/blob/ae0c4c4c295b1b4d6ac94f3c665bc39c7db052cd/torch/functional.py#L390)) where the `TYPE_CHECKING` version of a function does not have a docstring whereas the non-`TYPE_CHECKING` version does. They apparently [do not realize](https://github.com/pytorch/pytorch/issues/53545#issuecomment-795446422) that `TYPE_CHECKING` is used by language servers in addition to command line type checkers.
