### ISSUE TITLE
Auto import not working for package "numpy"

### ISSUE THREAD

**Issue by nguyenanht** [microsoft/pylance-release#3853]
## Description
I am unable to auto import "numpy" using the quick fix feature in VSCode. The official documentation (https://code.visualstudio.com/docs/python/editing#_quick-fixes) shows an example of auto import for "numpy", but I am unable to reproduce this in my environment. When attempting to use the quick fix feature, no option to import "numpy" appears.  It suggests instead : ```from gettext import npgettext```

https://user-images.githubusercontent.com/19518282/213888840-ad03c7e4-fc62-4497-a893-a61a504a35f1.mp4

I have tried the following steps:

Installed "numpy" package using pip on my os system
Attempted to use the quick fix feature to import "numpy as np" in my code, but no option to import "numpy" appears.
The quick fix not showing also auto import for package like scikit-learn. For instance when I want to use accuracy_score. 
(Of course, I have python extension installed)

I would appreciate any assistance in resolving this issue.

## Environment 

-   Language Server version: Pylance language server 2023.1.30 (pyright bf8ec313) starting
-   OS and version: ManjaroLinux release 22
-   Python version: 3.10

Here is my settings.json
```json
{
    "autoDocstring.docstringFormat": "numpy",
    "editor.renameOnType": true,
    "editor.fontSize": 17,
    "workbench.list.openMode": "doubleClick",
    "files.autoSave": "afterDelay",
    "editor.rulers": [
        100
    ],
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "python.linting.flake8Enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.enabled": false,
    "python.formatting.provider": "black",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[python]": {
        "gitlens.codeLens.symbolScopes": [
            "!Module"
        ],
        "editor.wordBasedSuggestions": false
    },
    "vsicons.dontShowNewVersionMessage": true,
    "python.analysis.diagnosticSeverityOverrides": {
        "reportPrivateUsage": "error",
        "reportUnboundVariable": "information",
        "reportUnusedImport": "warning",
        "reportImportCycles": "warning"
    },
    "search.useIgnoreFiles": false,
    "search.exclude": {
        "**/.cache": true,
        "**/.ipython": true,
        "**/.jupyter": true,
        "**/.local": true,
        "**/.vscode": true,
        "**/.vscode-server": true
    },
    "files.watcherExclude": {
        "**/.cache/**": true,
        "**/.local/**": true,
        "**/.vscode-server/**": true,
        "**/.vscode/**": true
    },
    "editor.largeFileOptimizations": false,
    "python.analysis.autoImportCompletions": true,
    "python.analysis.packageIndexDepths": [
        {
            "name": "sklearn",
            "depth": 5
        },
        {
            "name": "matplotlib",
            "depth": 3
        },
        {
            "name": "scipy",
            "depth": 3
        },
        {
            "name": "numpy",
            "depth": 2
        },
        {
            "name": "django",
            "depth": 2
        }
    ],
    "security.workspace.trust.enabled": false,
    "python.analysis.autoImportUserSymbols": true,
    "python.languageServer": "Pylance"
}
```

**Comment by judej** [comment]
Thanks for the report. Would you please check if the right virtual environment is being used?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show the global python interpreter. 
   * Click on version number and choose the right environment from the command palette
   * If there is no environment offered, you will need to create an environment and then select that as the default environment
   * When you select the right virtual environment Pylance find the modules installed in that environment.

Here is a link to virtual environments: https://code.visualstudio.com/docs/python/environments

Please reopen this issue if this does not solve the problem.

**Comment by nguyenanht** [comment]
I had the same issue with poetry env inside a docker container. So that is why I used the global Python environment in my host machine.

But as suggested, I tested with a new virtualenv and I have exactly the same issue.

![Screenshot from 2023-01-22 09-48-58](https://user-images.githubusercontent.com/19518282/213907784-fe2f6694-dd93-4c91-8c19-19c870a58b70.png)
