### ISSUE TITLE
Improved error handling for undefined and missing function arguments in VSCode

### ISSUE THREAD

**Issue by nguyenanht** [microsoft/pylance-release#3854]
## Description:
I would like the editor to clearly indicate when an undefined argument or a missing argument has been provided to a function in my code. This would make it easier for me to identify and fix errors in my code without having to run the program.

Specifically, I would like to see the following improvements in VSCode:

- When an undefined argument is provided to a function, VSCode should display an error message indicating the name of the undefined argument and the function in which it was passed.

- When a missing argument is detected, VSCode should display an error message indicating the name of the missing argument and the function in which it should have been passed.

VSCode should provide suggestions for the missing or undefined arguments in the function
This would greatly improve the debugging process and make it easier for me to write accurate and error-free code.
I was a user of Pycharm but recently switch to vscode and this feature is essential for me.

You can find in the screenshot below that there is no error showing :
![Screenshot from 2023-01-21 21-31-17](https://user-images.githubusercontent.com/19518282/213889356-a2b46395-9151-4a09-bbbc-0d8b09dbb052.png)

**Comment by erictraut** [comment]
This functionality is available if you enable static type checking. You can do this by setting `python.analysis.typeCheckingMode` to "basic".

Here's what it looks like when you enable this functionality:

![Screenshot 2023-01-21 at 2 35 54 PM](https://user-images.githubusercontent.com/7040122/213889673-ef227cb1-4b70-45e1-94a4-ed11cb275fae.png)

**Comment by nguyenanht** [comment]
@erictraut, thank you for your help. It works as expected by setting to "basic" ! 

Shouldn't this be set by default in the next release ?
