### ISSUE TITLE
[Bug]Code completion feature Completion code completion is wrong

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/pylance-release#3856]
VS Code Version:
![image](https://user-images.githubusercontent.com/96709586/213916220-973d262e-738f-419c-b88f-385ec89b72f5.png)

VS Code Python Version:
![image](https://user-images.githubusercontent.com/96709586/213916293-6b8e34dc-afc8-4954-b7ed-09e99f54096b.png)

https://user-images.githubusercontent.com/96709586/213916392-4af6f3b6-7dc6-4d5a-9273-e78e68326d6e.mp4

The correct code should be:
```
class Animals:
    def __call__(self, *args: any, **kwds: any) -> any:
        pass
```

**Comment by erictraut** [comment]
The code completion here is correct. The symbol `Any` refers to `typing.Any` and is a valid type annotation. The symbol `any` refers to `builtins.any`, which is a function and is not a valid type annotation.

To use `Any`, you will need to import it from `typing` as follows: `from typing import Any`.

**Comment by debonte** [comment]
Should we automatically add the `Any` import in this case (if needed)?

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/discussions/2590
