### ISSUE TITLE
Why is go to definition useless at this point?

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/pylance-release#3860]
Type: <b>Bug</b>

The following directory structure exists. I open `src` in vscode as workspace.

    Directory tree view is like :
    src
     |-calculation
        |-base_class.py
        |-particular_class.py
     |-db_related_module
        |-db_class.py

and each module has:

base_class.py

    class BaseClass():
    
        def __init__(self, DbClass):
            self.db_cls = DbClass

particular_class.py

    from base_class import BaseClass
    from db_related_module.db_class import DbClass
    
    
    class ParticularCalClass(BaseClass):
    
        def __init__(self):
            super().__init__(
                DbClass
            )
    
        def some_calculation(self):
            do_db_stuff = self.db_cls
            ret = do_db_stuff.execute_sql()
            return ret
    
    
    def main():
        calc_cls = ParticularCalClass()
        print(calc_cls.some_calculation())
    
    main()

db_class.py

    class DbClass():
    
        def __init__(self):
            pass
    
        def execute_sql():
            return "execute some sql"

Here I would like to jump from particular_class.py

    ret = do_db_stuff.execute_sql()

to db_class.py

    def execute_sql():

as it is the definition. 

But unable to go to definition.

[![image.png](https://imgur.com/QJHwmgZ.png)](https://imgur.com/QJHwmgZ.png)

Both ``Ctrl+Click`` and ``F12`` have no effect

Extension version: 2022.20.1
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4310 CPU @ 2.10GHz (8 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|12.46GB (5.90GB free)|
|Process Argv|--crash-reporter-id 85d2ef9b-c1a0-4650-bde2-81115cb1e6e8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by bschnurr** [comment]
Need to add an annotation to base_class.py.. but i dont think you want to do that.
```python
from db_related_module.db_class import DbClass

class BaseClass():

    def __init__(self, DbClass: DbClass):
        self.db_cls = DbClass

```

**Comment by rchiodo** [comment]
This code repros it too:

```python
class MyClass:
    pass

class BaseClass:
    def __init__(self, other):
        self.other = other

    def get_other(self):
        return self.other
    
class SubClass(BaseClass):
    def __init__(self, other):
        super.__init__(other)

y = SubClass(MyClass)

x = y.get_other()
```

Type of x is unknown.

But this works:

```python
y = BaseClass(MyClass)
x = y.get_other()
```

Type of x is `Type[MyClass]`

**Comment by erictraut** [comment]
This is working as designed.

You need to provide a type annotation for the input parameter for the class constructor. Without this, the type of the instance variable `db_cls` cannot be inferred.

```python
class BaseClass:
    def __init__(self, db_cls: type[DbClass]):
        self.db_cls = db_cls
```

Alternatively, you could annotate the type of the instance variable `db_cls` directly, in which case it doesn't need to be inferred.

```python
class BaseClass:
    def __init__(self, db_cls):
        self.db_cls: type[DbClass] = db_cls
```

@rchiodo, it works when you directly invoke the `BaseClass` constructor (`y = BaseClass(MyClass)`) because of the "pseudo-generic" support in pyright. If a class has a constructor whose types are unannotated, pyright effectively treats it as though it's a generic class where each input parameter for the constructor is a type variable. In the example above, it effectively treats `BaseClass` as `BaseClass[T]`, and the type of the call `BaseClass(MyClass)` evaluates to `BaseClass[type[MyClass]]`. The inferred type of the instance variable is `T`, which is specialized to `type[MyClass]` in this case.

**Comment by rchiodo** [comment]
@erictraut how come the 'pseudo-generic' support isn't being applied to `SubClass`? Or maybe it is but that isn't passing through to `BaseClass`?

**Comment by erictraut** [comment]
Psuedo-generic support works only when you directly call the constructor. Keep in mind that a static analyzer doesn't actually "run" the code, so simulation of nested function calls isn't really feasible.
