### ISSUE TITLE
No automatic parens with class types

### ISSUE THREAD

**Issue by PYOSESEUNG** [microsoft/pylance-release#3870]
This issue has been fixed in prerelease version 2023.1.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023131-18-January-2023-PreRelease)

_Originally posted by @heejaechang in https://github.com/microsoft/pylance-release/issues/3831#issuecomment-1396205655_
            

I tested with prerelease version(2023.1.41), but it does not automatically make brackets with class type functions such as int(), str().. so on. I wonder whether it is bug or not. Was it intended?

P.S. With Jedi server, class type functions make brackets with them.

**Comment by rchiodo** [comment]
I don't believe this used to work either, but it does sound like bug.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.2.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023211-1-february-2023-prerelease)
