### ISSUE TITLE
StrEnum member is incompatible with annotation

### ISSUE THREAD

**Issue by AlexanderPodorov** [microsoft/pylance-release#3872]
<h3> Environment data </h3>

-   Language Server version: 2023.1.40
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda):  3.11.1
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
from enum import StrEnum

class Endpoint(StrEnum):
    CREATE_ADDRESS = 'create_address'
    FOO = 'foo'
    BAR = 'bar'

def test(e: Endpoint) -> Endpoint:
    return e


#  2023.1.30 -> no warnings
#  2023.1.40 -> false positive: Literal['create_address'] is incompatible with Endpoint
print(test(Endpoint.CREATE_ADDRESS))
```

<h3> Repro Steps </h3>

1. No warnings for 2023.1.30
2. False positive warning for 2023.1.40

<h3> Expected behavior </h3>

No warnings

<h3> Actual behavior </h3>

Warning: Literal['create_address'] is incompatible with Endpoint

<h3> Logs </h3>

```
-
```

**Comment by erictraut** [comment]
I think this is due to this bug: https://github.com/microsoft/pyright/issues/3997. It's already fixed in the latest pyright, and the fix is in the latest "insiders build" of pylance. It will be included in the production build of pylance next week.

**Comment by AlexanderPodorov** [comment]
Thank you! The issue you mentioned is relatively old, it looks like it was caused by some recent bugfix/feature.
