### ISSUE TITLE
"No symbols found in document ..." and python autocomplete no longer works after latest VSCode update

### ISSUE THREAD

**Issue by raj-trustlab** [microsoft/pylance-release#3878]
Hello,

I use VSCode to write python code. I SSH Into an Ec2 instance with VSCode to do this. Recently, I noticed that symbols / linking stopped working for me in VSCode, and autocomplete doesn't work either. Can someone help me here? Thanks! Happy to provide more info as needed.

## Environment data

-   Language Server version: v2023.1.40
-   OS and version: MacOS Monterrey 12.3.1 (But I SSH into an Ec2 Instance running Ubuntu 20.04.2 LTS)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.10

**Comment by bschnurr** [comment]
could be similar to this issue
https://github.com/microsoft/pylance-release/issues/3300#issuecomment-1406947296
