### ISSUE TITLE
The pylance process not existed with high cpu usage after vscode connections closed several days

### ISSUE THREAD

**Issue by sunnysnowhi** [microsoft/pylance-release#3879]
I have an ubuntu conda env and I use VS Code remote-ssh to connect it.  When I finish my work I closed all the VS Code windows. After several days, (I use another ssh tool(not VS Code) to connect the environment，I find the pylance process is still here ! And the cpu is very high

$ps -efww |grep node
my-user   1972     1 58 Jan17 ?        6-10:25:55 /home/my-user/work/.vscode-server/71e0e984-eca5-431f-b464-bd81d4af7c73/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/node /home/my-user/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.3/dist/server.bundle.js --cancellationReceive=file:8fbca14524ede8624336641b06482fe27d7d7d47d0 --node-ipc --clientProcessId=1530
my-user   5572     1 63 Jan09 ?        12-01:40:10 /home/my-user/work/.vscode-server/71e0e984-eca5-431f-b464-bd81d4af7c73/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/node /home/my-user/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.3/dist/server.bundle.js --cancellationReceive=file:fdb77fd28d2f6ba32ab7de93285b1917045d2b95a8 --node-ipc --clientProcessId=5102
my-user  10622     1 62 Jan11 ?        10-15:29:13 /home/my-user/work/.vscode-server/71e0e984-eca5-431f-b464-bd81d4af7c73/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/node /home/my-user/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.3/dist/server.bundle.js --cancellationReceive=file:1a21b010cb2a0651d4a3ae26951cbf2e2ad3a012e4 --node-ipc --clientProcessId=9625
my-user  15146     1 63 Jan13 ?        9-13:32:58 /home/my-user/work/.vscode-server/71e0e984-eca5-431f-b464-bd81d4af7c73/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/node /home/my-user/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.3/dist/server.bundle.js --cancellationReceive=file:fe823f149222b4a6c5c265abbd7d993461429811b4 --node-ipc --clientProcessId=14213
my-user  22965     1 57 Jan15 ?        7-12:31:30 /home/my-user/work/.vscode-server/71e0e984-eca5-431f-b464-bd81d4af7c73/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/node /home/my-user/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.3/dist/server.bundle.js --cancellationReceive=file:dfee8509a3d36fd002e85093e641de4f2e0b0b37b5 --node-ipc --clientProcessId=22656
my-user  25786 16790  0 11:08 pts/2    00:00:00 grep --color=auto node
my-user  26564     1 64 Jan13 ?        9-12:47:59 /home/my-user/work/.vscode-server/71e0e984-eca5-431f-b464-bd81d4af7c73/bin/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/node /home/my-user/.vscode-server/extensions/ms-python.vscode-pylance-2022.1.3/dist/server.bundle.js --cancellationReceive=file:d10f1a76c88fb100d69c65c64ff056667dfd67675b --node-ipc --clientProcessId=26125

The cpu usage is like this:
top - 10:12:07 up 171 days, 23:13,  0 users,  load average: 6.07, 5.60, 5.75
Tasks:  16 total,   5 running,  11 sleeping,   0 stopped,   0 zombie
%Cpu(s): 10.6 us, 44.4 sy,  0.0 ni, 45.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 65791716 total, 17015976 free, 12995788 used, 35779952 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 52133384 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                  
15146 my-user   20   0 1837176 1.167g   5544 R  66.0  1.9  13736:55 node                                                                                                     
22965 my-user   20   0 1731800 0.997g   8096 R  66.0  1.6  10795:24 node                                                                                                     
26564 my-user   20   0 1436264 722396   5576 R  65.8  1.1  13691:55 node                                                                                                     
 1972 my-user   20   0 1780184 1.051g  14612 D  65.5  1.7   9229:50 node                                                                                                     
 5572 my-user   20   0 1713716 1.038g   5208 D  65.0  1.7  17344:08 node                                                                                                     
10622 my-user   20   0 1731864 1.031g   5556 R  64.7  1.6  15293:11 node   

## Environment data

-   Language Server version: pylance-2022.1.3
-   OS and version: Ubuntu 18.04.6 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.10 conda 4.8.2

## Code Snippet

I am not sure what code will cause this

## Repro Steps

I am not sure how to reproduce because many people have used this environment for a long time, but this problem does not appear every time

## Expected behavior

1.  After I close the VS Code， no residual pylance processes
2.  The pylance process should not have so high cpu  usage when I am not using it.

## Actual behavior

The residual pylance processes existed with high cpu usage(>60%)

## Logs

Now i am not using VS Code to connect it,  so no log here......

I want to know if this is a known issue.  I see the issue lists [here](https://github.com/microsoft/pylance-release/issues?q=cpu+usage),  but all the questions is about 'when using pylance the cpu is high ',  it is not same as 'the residual pylance processes without using it'.

Thank you!

**Comment by bschnurr** [comment]
could be related to this issue
https://github.com/microsoft/pylance-release/issues/3300#issuecomment-1406947296
