### ISSUE TITLE
Don't show `__future__` options in auto-import quick action

### ISSUE THREAD

**Issue by brettcannon** [microsoft/pylance-release#3882]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
a
```

## Repro Steps

1. Type `a`
2. Look at the list of potential completions

https://github.com/microsoft/pylance-release/discussions/3873 has a screenshot.

## Expected behavior

Not to list any `__future__` imports as you can't access anything from such an import (they change the parser/language, they don't pull any names).

## Actual behavior

Various `__future__` imports gets listed.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.2.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023211-1-february-2023-prerelease)
