### ISSUE TITLE
Python-File not analyzed with 2 workspace-folders using remote-SSH

### ISSUE THREAD

**Issue by Dephrilibrium** [microsoft/pylance-release#3883]
Type: <b>Bug</b>

Open a SSH-Remote connection to a raspberry pi 4 (8GB) (home-folder) and add root (/) to the workspace-folders.
Afterwards the file is not "analyzed" anymore and you can't use autocompletion or "Go to defintion (F12)"

I also tried to reinstall both (local and remote) extensions. Everytime when I add the second folder the Python-file is not analyzed anymore.

Extension version: 2023.1.40
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux arm 5.10.103-v7l+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900 (24 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|127.70GB (117.74GB free)|
|Process Argv|--crash-reporter-id 3a9f857b-25aa-4613-9dc9-3779bab08260|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ccdkammer|
|OS|Linux arm 5.10.103-v7l+|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 1500)|
|Memory (System)|7.54GB (5.39GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12cf:30652349
a9j8j154:30646983
vscsbc:30628655

```

</details>

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

...

my gut feeling is you pointed pylance to the whole disk. so pylance is basically walking your whole drive taking long time to finish. Try point workspace root to more specific folder where py files are located.

**Comment by Dephrilibrium** [comment]
Hi heejaechang,

when i enable the pylance trace option I can't find lines with "Pylance language server XXX (pyright xxx) starting" in output.

Therefore i made a video which shows what I'm doing.
1.) I start with only one folder in the workspace. Then the file is analyzed and i can use autocompletion and i can see the function-parameters (ctrl+space)
2.) I add root (/) to the workspace. After that the file is not analyzed anymore. Then autocompletion and the popup to see the function parameters not working anymore.

https://user-images.githubusercontent.com/89015665/215720387-e462659d-d278-4c44-af6c-92b9e4c5f2be.mp4

I hope this helps too.


Kind regards,
Deph

**Comment by heejaechang** [comment]
so, don't give the root to the workspace folder. if you give the root, we will walk your entire disk which can take minutes to hours depending on how big your disk is.

also, to be 100% sure we need the log. without it, we can't find out what is going on internally.

**Comment by Dephrilibrium** [comment]
Ah no, I think you are right. I played around and noticed that it won't appear if I add "/media" instead of "/" to the workspace.
