### ISSUE TITLE
incorrect return type on if expression if condition is imported

### ISSUE THREAD

**Issue by scarf005** [microsoft/pylance-release#3885]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

```py
import os

class A:
    ...

class B:
    ...

def spam():
    return A if os.name == 'foo' else B
```

expected: return  type of spam is `Type[A] | Type[B]`

actual: return type of spam is `Type[B]` (the else clause)

## Steps to reproduce:

1. enter above code.
2. type is incorrectly guessed, which will also trigger `reportUnusedImport` if values of if expression is imported
3. return type will be correctly inferred if condition is imported using `import-from` syntax
```py
from os import name

def egg(): # -> `Type[A] | Type[B]`
    return A if name == 'foo' else B
```

![image](https://user-images.githubusercontent.com/54838975/215264542-602258b7-928f-4276-87dc-47828fd04b92.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• mypyArgs: "<placeholder>"
• mypyEnabled: true

formatting
• provider: "black"
• blackArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2022.20.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
OS version: Linux x64 5.19.0-29-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 3632)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.70GB (16.93GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by erictraut** [comment]
The subexpression `os.name == "foo"` is evaluated statically. This is required by PEP 484, which introduced the basic framework for static type checking in Python.

By default, pylance assumes that the `os.name` matches the OS you are developing on. If you would like to override this assumption, you can create a `pyrightconfig.json` or `pyproject.toml` file and configure the `pythonPlatform` configuration. If you specify an empty string for the pythonPlatform, pylance will assume that you want your code to run on all platforms, and your code sample will be evaluated as you expect.

**Comment by heejaechang** [comment]
this is by design as Eric explained above.
