### ISSUE TITLE
Grinds system to a halt

### ISSUE THREAD

**Issue by Timusan** [microsoft/pylance-release#3889]
Type: <b>Bug</b>

Do a vanilla VSCode install, enable the Python (with Pylance extension), open any Python project. Indexing takes a very long time, but even after that is finished the whole system is very very slow and VSCode (or the internal Python process to be more exact) is taking up to 200%~300% CPU the entire time.

VSCode has to be shut down before you can use the computer again.

I have already fully removed VScode and any configs from my system, worked with a very minimal install and the issue is there immediately after enabling the official Microsoft Python extension.

Extension version: 2023.1.40
VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 78, 79|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug.  We need to look at the log files. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
