### ISSUE TITLE
Add auto import setting as a language status item 

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#3894]
Since we changed the default value of `"python.analysis.autoImportCompletions"` to `false`, it would be nice if we could expose auto imports in the language status menu alongside type checking mode, to make it more discoverable. 

![image](https://user-images.githubusercontent.com/45497113/216146013-539fbffc-9e3a-435f-8dc7-a3e4bf8fd625.png)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231011-4-October-2023-PreRelease)
