### ISSUE TITLE
"Add type annotations for all fixture references in this file" code action is shown in non-test file

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#3895]
## Code Snippet

```python
import pytest

@pytest.fixture
def first_entry():
    return "a"

def foo(first_entry):
    pass
```

## Repro Steps

1. pip install pytest
2. Place the code above in a file that does not match pytest's file filter (ex. does not start with `test_` or end with `_test`).
3. Click somewhere in the file.

## Expected behavior

No pytest code actions.

## Actual behavior

"Add type annotations for all fixture references in this file" code action is suggested.
"Add type annotation to first_entry" is suggested if you click on the `first_entry` parameter of `foo`

## Rationale

Not a huge deal, but as a first time user of the pytest features (and pytest) I was confused about why Pylance was presenting these code actions yet none of the other new behaviors were lighting up. It was because my filename wasn't matching what pytest expected.

For consistency, I think `PytestExtensionImpl.addCodeActions` should be doing no work unless `_isTestFile` is true.

**Comment by rchiodo** [comment]
Any file with fixtures in it would benefit from the code actions too. I believe it's already checking that? Let me double check.

**Comment by debonte** [comment]
Yes, that's correct.

**Comment by rchiodo** [comment]
The inlay hints work in that file though, right? I'm wondering what other functionality didn't work in a fixture only file?

**Comment by debonte** [comment]
As far as I could tell nothing else worked because `_isTestFile` was returning false. My filename was "PytestExamples.py" and I didn't have a pytest config file telling it to search for test files in a non-default way.

**Comment by rchiodo** [comment]
Yeah it checks for 
- Test functions (have to match the function and file pattern)
- Fixture functions (should work anywhere)

The latter was what I was wondering wasn't working.

**Comment by rchiodo** [comment]
I believe this is working as designed.
