### ISSUE TITLE
Pylance said my code is unreachable although it's not.

### ISSUE THREAD

**Issue by KbyteTutu** [microsoft/pylance-release#3897]
## Environment data

-   Language Server version: Pylance v2023.2.11
-   OS and version: WSL2 ubuntu22.04
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.11

## Code Snippet

```python
from typing import List, Dict, Tuple, Any, NoReturn


class Foo:
    def a(self) -> NoReturn:
        print("a")

    def b(self) -> NoReturn:
        print("b")

    def main(self) -> NoReturn:
        try:
            self.a()
            self.b()  # marked as unreachable
        except:
            print(1)


if __name__ == "__main__":
    ins = Foo()
    ins.main()
```
The line below self.b() are marked as unreachable.

## Expected behavior

Code below that function should be mark as reachable.

## Actual behavior

Code is marked as unreachable

## Additional information
It's similar as [https://github.com/microsoft/pylance-release/issues/31](url) 
I'm not sure why this old bug pop up again but it's weird.

**Comment by erictraut** [comment]
Pylance is correct here. You've annotated the methods `a`, `b` and `main` with the return type `NoReturn`, which indicates that they never return control back to the caller. For details about `NoReturn`, refer to [this documentation](https://docs.python.org/3/library/typing.html#typing.NoReturn) or [PEP 484](https://peps.python.org/pep-0484/#the-noreturn-type).

These methods implicitly return `None`, so the proper return type annotation would be `None`. If you apply this fix to your code, pylance will no longer report the code as unreachable.

**Comment by KbyteTutu** [comment]
> Pylance is correct here. You've annotated the methods `a`, `b` and `main` with the return type `NoReturn`, which indicates that they never return control back to the caller. For details about `NoReturn`, refer to [this documentation](https://docs.python.org/3/library/typing.html#typing.NoReturn) or [PEP 484](https://peps.python.org/pep-0484/#the-noreturn-type).
> 
> These methods implicitly return `None`, so the proper return type annotation would be `None`. If you apply this fix to your code, pylance will no longer report the code as unreachable.

Oh, thank you very much. Seems like i'm not quite understand the meaning of NoReturn. So the NoReturn type should be use in the last function with out return, which normally happen in except catching, am i right here?

**Comment by erictraut** [comment]
`NoReturn` should be used for the return type if the function...
1. throws an exception along all code paths
2. executes an infinite loop
3. terminates the process
