### ISSUE TITLE
Pylance install hangs on Windows 10

### ISSUE THREAD

**Issue by SiggiSmara** [microsoft/pylance-release#3898]
This is also filed in https://github.com/microsoft/vscode/issues/173122 as I'm not sure where it belongs.

This is a copy of the same information in that ticket to save some clicking:

Type: <b>Bug</b>

1. Start VS Code
1. Make sure you are in Local mode and not Remote
1. Go to Extensions
1. Search for Pylance
1. Press Install button

What is expected:  Pylance extension is installed

What actually happens:  Install hangs and never finishes

**Edit**: Disabling all extensions has no effect on outcome

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (4.28GB free)|
|Process Argv|--crash-reporter-id 935dacf1-2f84-4f2c-b361-6d2163d7045f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2207)|
|Memory (System)|12.30GB (11.63GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.2.0
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.72.0
vetur|oct|0.36.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
89544117:30613380
pythonsymbol12cf:30652349
a9j8j154:30646983

```

</details>

</details><details>
<summary>Shared process Log, debug setting</summary>

```
2023-02-02 08:45:49.170 [info] Starting worker process with pid 14716 (type: fileWatcher, window: 1).
2023-02-02 08:45:49.675 [info] Deleted from disk redhat.vscode-xml c:\Users\myusername\.vscode\extensions\redhat.vscode-xml-0.24.0-win32-x64
2023-02-02 08:45:55.061 [info] Starting worker process with pid 25956 (type: fileWatcher, window: 3).
2023-02-02 08:46:16.709 [debug] User data changed
2023-02-02 08:46:18.482 [debug] User data changed
2023-02-02 08:46:31.805 [info] Getting Manifest... ms-python.vscode-pylance
2023-02-02 08:46:31.813 [info] Installing extension: ms-python.vscode-pylance
2023-02-02 08:46:34.032 [info] Getting Manifest... ms-python.python
2023-02-02 08:46:36.005 [debug] User data changed
2023-02-02 08:46:36.525 [info] Getting Manifest... ms-toolsai.jupyter
2023-02-02 08:46:37.113 [info] Getting Manifest... ms-python.isort
2023-02-02 08:46:37.373 [info] Installing extension: ms-python.python ms-python.vscode-pylance
2023-02-02 08:46:37.373 [info] Installing extension: ms-python.isort ms-python.vscode-pylance
2023-02-02 08:46:37.682 [debug] User data changed
2023-02-02 08:46:38.150 [debug] User data changed
2023-02-02 08:46:38.614 [debug] User data changed
2023-02-02 08:46:57.270 [debug] User data changed
2023-02-02 08:46:59.793 [debug] User data changed


```

</details>

**Comment by rchiodo** [comment]
Install wouldn't be handled by our extension. We just generate a zip file. 

Do other extensions install?

**Comment by bschnurr** [comment]
maybe try deleting the downloaded pylance extension from `c:\Users\XXXX\.vscode\extensions\`

**Comment by SiggiSmara** [comment]
Thanks for looking into this.  

@rchiodo other extensions install without problem. 

@bschnurr yep tried that already with no change. Even tried deleting the whole folder. Same result.

**Comment by SiggiSmara** [comment]
I guess the better fit for this would then be over on vscode side where I posted the original issue.

**Comment by bschnurr** [comment]
windows defender maybe? exclude vscode process and folder?

**Comment by SiggiSmara** [comment]
Not likely given that other extensions install without problem.

**Comment by bschnurr** [comment]
we sometimes get our extension flagged by windows defender
