### ISSUE TITLE
Support for Monorepo with multiple virtual environments

### ISSUE THREAD

**Issue by Hyperclaw79** [microsoft/pylance-release#3899]
I have a Monorepo where the parent application and the child application both have different set of requirements and hence use different virtual envs.

```
main
├── .venv
│   ├── main
│   │   └── lib
│   │       └── site-packages
│   └── child
│       └── lib
│           └── site-packages
├── child
│   └── requirements.txt
└── requirements.txt
```

When the Interpreter is set to the parent's virtual env, I get reportMissingImports errors for the modules in the child application and vice versa.
Requesting you to implement a feature where Pylance would grep for all site_packages throughout the workspace. This should resolve the missing imports. If that's not possible to do, at least a way to temporarily suppress the errors from the UI.

**Comment by erictraut** [comment]
I think that multi-root workspaces would address this use case, no? You could create a new workspace for each project in the monorepo. Each workspace can have its own settings.

**Comment by Hyperclaw79** [comment]
@rchiodo Thank you for clarifying it and the workaround. I'll try it out.

@erictraut Multi-root workspaces work well for independent projects. However, since this is a case of nested projects, the parent will always have the child modules and from its perspective, there will be import errors.
As of now, i haven't actually tested it but I'm theorizing it.
