### ISSUE TITLE
vs code - reportMissingModuleSource with venv

### ISSUE THREAD

**Issue by GarikFirst** [microsoft/pylance-release#3900]
I’m in vs code on Mac OS Ventura and 

I’m in venv and venv is activated and interpreter selected in vs code, but I got **Missing Import** **from pylance**

(.venv) MacBook-Pro14-ibulekov:PySocialCreditBot ibulekov$ pip3 list
...
python-telegram-bot   20.0b0
pytz                  2022.7.1
...
<img width="757" alt="Снимок экрана 2023-02-02 в 13 27 05" src="https://user-images.githubusercontent.com/47447219/216299900-d06607c4-d7e6-4ebb-b52d-693d46d1d06b.png">

But, when I add key "python.analysis.extraPaths":[".venv/lib/python3.10/site-packages»] in my .vscode/settings.json - all imports successfully resolved

**Comment by rchiodo** [comment]
Can you upload the log after following the directions here:

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

It might be that we don't get the `python3.10` when creating the site-packages directory internally. I believe the log will show that. 

For example it shows this for my own venv:

```
[Info  - 9:29:57 AM] (10128) Search paths for d:\Source\Testing\Test_Pytest
[Info  - 9:29:57 AM] (10128)   c:\Users\aku91\.vscode\extensions\ms-python.vscode-pylance-2023.2.11\dist\typeshed-fallback\stdlib
[Info  - 9:29:57 AM] (10128)   d:\Source\Testing\Test_Pytest
[Info  - 9:29:57 AM] (10128)   d:\Source\Testing\Test_Pytest\.venv\child\lib\site-packages
[Info  - 9:29:57 AM] (10128)   d:\Source\Testing\Test_Pytest\typings
[Info  - 9:29:57 AM] (10128)   c:\Users\aku91\.vscode\extensions\ms-python.vscode-pylance-2023.2.11\dist\typeshed-fallback\stubs\...
[Info  - 9:29:57 AM] (10128)   c:\Users\aku91\.vscode\extensions\ms-python.vscode-pylance-2023.2.11\dist\bundled\stubs
[Info  - 9:29:57 AM] (10128)   c:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\DLLs
[Info  - 9:29:57 AM] (10128)   c:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\Lib
[Info  - 9:29:57 AM] (10128)   c:\Users\aku91\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0
[Info  - 9:29:57 AM] (10128)   c:\Users\aku91\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages
[Info  - 9:29:57 AM] (10128)   c:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0
[Info  - 9:29:57 AM] (10128)   c:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\Lib\site-packages
```

**Comment by GarikFirst** [comment]
Yes please
`(43784) Background analysis message: analyze
(43784) [BG(1)] parsing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__init__.py [fs read 0ms] (3ms)
(43784) [BG(1)] parsing: /Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/typeshed-fallback/stdlib/builtins.pyi [fs read 0ms] (16ms)
(43784) [BG(1)] binding: /Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/typeshed-fallback/stdlib/builtins.pyi (6ms)
(43784) [BG(1)] binding: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__init__.py (0ms)
(43784) [BG(1)] indexing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__init__.py [found 0] (0ms)
(43784) Indexing Done: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__init__.py
(43784) [BG(1)] parsing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__main__.py [fs read 0ms] (2ms)
[Info  - 08:00:26] (43784) Could not resolve source for 'pytz' in file '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__main__.py'
[Info  - 08:00:26] (43784)   Looking in root directory of execution environment '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   No python interpreter search path
[Info  - 08:00:26] (43784) Could not import 'telegram.ext' in file '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__main__.py'
[Info  - 08:00:26] (43784)   Looking in stubPath '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/typings'
[Info  - 08:00:26] (43784)   Attempting to resolve stub package using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/typings'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/typings'
[Info  - 08:00:26] (43784)   Looking in root directory of execution environment '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   Attempting to resolve stub package using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   No python interpreter search path
[Info  - 08:00:26] (43784)   Looking in bundled stubs path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/bundled/stubs'
[Info  - 08:00:26] (43784)   Attempting to resolve stub package using root path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/bundled/stubs'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/bundled/stubs'
[Info  - 08:00:26] (43784)   Looking for typeshed stdlib path
[Info  - 08:00:26] (43784)   Looking for typeshed stdlib path
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/typeshed-fallback/stdlib'
[Info  - 08:00:26] (43784)   Typeshed path not found
[Info  - 08:00:26] (43784)   Looking for typeshed third-party path
[Info  - 08:00:26] (43784)   Looking for typeshed stubs path
[Info  - 08:00:26] (43784)   Typeshed path not found
(43784) [BG(1)] binding: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__main__.py (1ms)
(43784) [BG(1)] indexing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__main__.py [found 5] (0ms)
(43784) Indexing Done: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/__main__.py
(43784) [BG(1)] parsing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/config.py [fs read 0ms] (1ms)
(43784) [BG(1)] binding: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/config.py (0ms)
(43784) [BG(1)] indexing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/config.py [found 1] (0ms)
(43784) Indexing Done: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/config.py
(43784) [BG(1)] parsing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/__init__.py [fs read 0ms] (0ms)
(43784) [BG(1)] binding: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/__init__.py (0ms)
(43784) [BG(1)] indexing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/__init__.py [found 0] (0ms)
(43784) Indexing Done: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/__init__.py
(43784) [BG(1)] parsing: /Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/bot.py [fs read 0ms] (4ms)
[Info  - 08:00:26] (43784) Could not resolve source for 'pytz' in file '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/bot.py'
[Info  - 08:00:26] (43784)   Looking in root directory of execution environment '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   No python interpreter search path
[Info  - 08:00:26] (43784) Could not import 'telegram' in file '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/socialcreditbot/bot/bot.py'
[Info  - 08:00:26] (43784)   Looking in stubPath '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/typings'
[Info  - 08:00:26] (43784)   Attempting to resolve stub package using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/typings'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot/typings'
[Info  - 08:00:26] (43784)   Looking in root directory of execution environment '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   Attempting to resolve stub package using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/Library/Mobile Documents/com~apple~CloudDocs/Code Projects/PySocialCreditBot'
[Info  - 08:00:26] (43784)   No python interpreter search path
[Info  - 08:00:26] (43784)   Looking in bundled stubs path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/bundled/stubs'
[Info  - 08:00:26] (43784)   Attempting to resolve stub package using root path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/bundled/stubs'
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/bundled/stubs'
[Info  - 08:00:26] (43784)   Looking for typeshed stdlib path
[Info  - 08:00:26] (43784)   Looking for typeshed stdlib path
[Info  - 08:00:26] (43784)   Attempting to resolve using root path '/Users/ibulekov/.vscode/extensions/ms-python.vscode-pylance-2023.2.10/dist/typeshed-fallback/stdlib'
[Info  - 08:00:26] (43784)   Typeshed path not found
[Info  - 08:00:26] (43784)   Looking for typeshed third-party path
[Info  - 08:00:26] (43784)   Looking for typeshed stubs path
[Info  - 08:00:26] (43784)   Typeshed path not found`

**Comment by rchiodo** [comment]
I believe your problem is this one:
https://github.com/microsoft/pylance-release/issues/3881. 

The path you have your project in has a `~` in the middle of it. We had an issue with that which we just fixed in yesterday's prerelease bits.
