### ISSUE TITLE
VSCode Pylance checking and analyzing become very slow once import fire package 

### ISSUE THREAD

**Issue by cyxr001** [microsoft/pylance-release#3906]
## Environment data

-   Language Server version: Pylance v2023.1.10 and Python v2022.16.1
-   OS and version: macbook monterey 12.6
-   Python version (& distribution if applicable, e.g. Anaconda): interpreter 3.10.9

## Code Snippet

```python
import fire


class C:

    def __init__(self) -> None:
        return


if __name__ == '__main__':
    fire.Fire(C)
```

## Repro Steps

1. Pylance checking and analyzing become very slow once import fire package like Code Snippet. And it took 2000-4000ms
2. When I comment out the fire package , it will become normal. Code like following :
```
class C:

    def __init__(self) -> None:
        return


if __name__ == '__main__':
    c = C
    print(c)
```
## Expected behavior

I'm a beginner in python language, and don't know whether it meets expectation

## Actual behavior

XXX

## Logs

```
slow logs:
[Info  - 1:11:39 AM] (49617) [BG(1)] Long operation: checking: /Users/xxx/yy/script.py (3956ms)
[Info  - 1:11:39 AM] (49617) [BG(1)] Long operation: analyzing: /Users/xxx/yy/script.py (3956ms)
```

**Comment by erictraut** [comment]
The `fire` library is an untyped library (i.e. it contains no inlined type annotations or type stubs). That means pylance needs to analyze it to infer type information based on its code. Type inference can be expensive. We're always working to improve the performance, but there are limits to what we can do. If `fire` is a library that you rely on, I recommend contacting its maintainers and encouraging them to include type information. Many major Python type libraries have started to do so over the past two years. We've prepared [this guidance](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) for library maintainers.

On my machine, I'm seeing pylance take about 1300ms to complete the analysis for the code snippet you've provided. Assuming that my machine is faster than yours, that's roughly consistent with what you're seeing.

I've added a performance improvement in the pre-release version of pylance that appears to make a significant difference in this case. It drops the analysis time to 750ms on my machine. That means it would likely drop the analysis time on your machine to about 2280ms. That's still not great, but it's better than what you're seeing. Please give the pre-release version of pylance a try and let us know what you see.

**Comment by cyxr001** [comment]
Thanks for your kind response . 
Normally , in my machine this  analysis time is around 2500ms , and 4000ms is the situation that I reopen vcsode .  
After I install Pylance v2023.2.12, it drops to around 200ms, but sometimes it is around 1500ms.
```
(82942) [BG(1)]   checking: /Users/xxx/yy/cmd.py (172ms)
(82942) [BG(1)] analyzing: /Users/xxx/yy/cmd.py (173ms)

(82942) [BG(1)]   checking: /Users/xxx/yy/cmd.py (1568ms)
(82942) [BG(1)] analyzing: /Users/xxx/yycmd.py (1568ms)
```

**Comment by debonte** [comment]
@erictraut, can this issue be closed, or do you think we can improve this further?

**Comment by erictraut** [comment]
I don't see additional opportunities for improvement, so I recommend closing it.
