### ISSUE TITLE
Python 3.11 Self return type on static method appears as Any type in IDE

### ISSUE THREAD

**Issue by v1b1** [microsoft/pylance-release#3909]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

```python
class Foo:
  def bar(self) -> int:
    ...

  @staticmethod
  def load(*args) -> Self:
    return Foo(*args)

# This appears as `(method) load(...) -> Any` and intellisense does not provide bar method as an option nor highlights methods/fields on foo.
foo = Foo.load(...)
```

## Steps to reproduce:

1. Create a simple class as above.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Nothing appears in the output panel.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.2.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.80GB (53.41GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/vnb/Workspace/pebble/openapi-cli --crash-reporter-id 2515fdac-0fa7-47f5-9ea7-2538b0019a07|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by debonte** [comment]
As discussed [here](https://github.com/microsoft/pyright/issues/4540#issuecomment-1407212284), `Self` is not supported on static methods.

**Comment by debonte** [comment]
Btw, if you change `python.analysis.typeCheckingMode` from `off` to `basic` (or `strict`), Pylance will give you an error when you attempt to use `Self` in this way:

![image](https://user-images.githubusercontent.com/12820898/216706643-5e9a74e8-55ed-4521-bbb1-8fc98e159377.png)

**Comment by linjer** [comment]
@v1b1 I found this after running into the same issue. It turns out `Self` is supported for factory methods, which appears to be what you may be trying to do with `load(...)`. For it to work properly, you just have to change the method to being a `@classmethod`, i.e.,

```py
class Foo:
  def bar(self) -> int:
    ...

  @classmethod
  def load(cls, *args) -> Self:
    return cls(*args)

foo = Foo.load(...)
```

**Comment by andres-swax** [comment]
> [@v1b1](https://github.com/v1b1) I found this after running into the same issue. It turns out `Self` is supported for factory methods, which appears to be what you may be trying to do with `load(...)`. For it to work properly, you just have to change the method to being a `@classmethod`, i.e.,
> 
> class Foo:
>   def bar(self) -> int:
>     ...
> 
>   @classmethod
>   def load(cls, *args) -> Self:
>     return cls(*args)
> 
> foo = Foo.load(...)

🤦🏽‍♂️

Thank you.
