### ISSUE TITLE
Many user snippets overridden by suggestions and others do not operate as expected after updating to VS Code Version 1.75.0

### ISSUE THREAD

**Issue by GigglePocket** [microsoft/pylance-release#3910]
Type: <b>Bug</b>

1) In a global user snippets file (Python), create the following snippet that wraps selected text with a try & except statement:

```json
    "Try & Except": {
        "prefix": "try:",
        "body": [
            "try:",
            "\t$TM_SELECTED_TEXT",
            "   ",
            "except Exception as E:",
            "\t$0",
            "",
        ],
        "description": "Try & except statement with wrap.\nHighlight code to try to use."
    },
```

2) With Pylance enabled, attempt to use the snippet by selecting a block of code and typing the specified prefix
    - Result: The code is replaced by the prefix and cursor is tabbed

3) Repeat step 2 with the Pylance disabled
    - Result: The code is wrapped with the try & except statement with the correct indentation, and the cursor is auto-positioned correctly within the scope of the except statement.

Extension version: 2023.2.10
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.69GB free)|
|Process Argv|C:\\Programming\\EVERYTHING\\EVERYTHING.code-workspace --crash-reporter-id 5bf58387-f4a6-4b59-b3d3-da5638839151|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779cf:30657577
f6dab269:30613381
pythonsymbol12:30657548
a9j8j154:30646983

```

</details>

**Comment by debonte** [comment]
This is working fine for me in both 1.75.0 and 1.76.0-insider. Can you provide a video of what you're seeing?

**Comment by sahil-1012** [comment]
same happened with me also..
adding a link with proper photos..
https://stackoverflow.com/questions/75344463/why-are-the-user-defined-snippets-not-working

**Comment by debonte** [comment]
@sahil-1012, I get this message when I follow that stackoverflow link:
![image](https://user-images.githubusercontent.com/12820898/216784482-a34e03a8-c3f3-40f1-836a-b75c8d5e6ef2.png)

**Comment by GigglePocket** [comment]
> This is working fine for me in both 1.75.0 and 1.76.0-insider. Can you provide a video of what you're seeing?
> 
> I'd also be curious to see your `settings.json` in case there's something about your Python/Pylance settings that is impacting this.

Thank you verily for responding. My apologies, but I rolled back to the previous version of VS Code and Pylance which provided a temporary solution because, to my chagrin, I rely much more heavily on snippets for my workflow now than I had realized. As far as possible settings issues, upon experiencing the aforementioned issue, I looked for similar issues and checked/verified all settings containing the word "snip" as well as all Pylance and relevant Python settings, but it's possible I missed something. I'm including my settings file, which is probably a bit bloated, so my apologies.

Here is my [settings](https://github.com/microsoft/pylance-release/files/10609425/settings.txt) file which was renamed as a text file as GitHub doesn't support uploading JSON files here.

**Comment by debonte** [comment]
Thanks, I'm able to repro this now. Not sure why I wasn't before.

I think this is the same as https://github.com/microsoft/pylance-release/issues/3911. Can you check if what you're seeing matches that behavior?

**Comment by GigglePocket** [comment]
#3911 seems the same save for the fact that my user snippets didn't show with even just one letter typed.

**Comment by debonte** [comment]
@GigglePocket, #3911 is fixed in the latest VS Code Insiders build. Can you see if this issue is also fixed for you?

**Comment by GigglePocket** [comment]
Will do. I have to re-upgrade to the latest version of VS Code & Pylance and I will follow up and let you know afterward.

**Comment by GigglePocket** [comment]
This issue has been fixed. All user snippets now appear in suggestions and insert correctly upon tabbing. Additionally, an issue I believe to be unrelated to this where `TM_SELECTED_TEXT` failed to insert the selected text into a rendered snippet appears to be fixed as well.

I'm closing this issue as it has been resolved. Thank you verily for your help and efforts.
