### ISSUE TITLE
Steeply slow after upgraded from `2023.1.40` to `2023.1.41+` - Long operation: getSemanticTokens

### ISSUE THREAD

**Issue by Starry-OvO** [microsoft/pylance-release#3917]
## Log

`2023.1.40` is fast, highlighting will complete within 0.7s.

```log
[Info  - 21:29:25] (5744) Pylance language server 2023.1.40 (pyright e96b3ece) starting
[Info  - 21:29:25] (5744) Server root directory: c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.1.40\dist
[Info  - 21:29:25] (5744) Starting service instance "aiotieba"
[Info  - 21:29:25] (5744) Auto-indent enabled
[Info  - 21:29:25] (5744) No configuration file found.
[Info  - 21:29:25] (5744) pyproject.toml file found at d:\Code\Python\aiotieba\aiotieba.
[Info  - 21:29:25] (5744) Setting pythonPath for service "aiotieba": "C:\Program Files\Python\Python311\python.exe"
[Info  - 21:29:25] (5744) Loading pyproject.toml file at d:\Code\Python\aiotieba\aiotieba\pyproject.toml
[Error - 21:29:25] (5744) Pyproject file "d:\Code\Python\aiotieba\aiotieba\pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 21:29:25] (5744) stubPath d:\Code\Python\aiotieba\aiotieba\typings is not a valid directory.
[Info  - 21:29:25] (5744) Assuming Python version 3.11
[Info  - 21:29:25] (5744) Assuming Python platform Windows
[Info  - 21:29:25] (5744) Searching for source files
[Info  - 21:29:25] (5744) Found 271 source files
[Info  - 21:29:25] (5744) Background analysis(1) root directory: c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.1.40\dist
[Info  - 21:29:25] (5744) Background analysis(1) started
```

While `2023.1.41` is steeply slow, highlight and type hints will cost upto 3.0s to complete.

```log
[Info  - 21:32:05] (14092) Pylance language server 2023.1.41 (pyright 01758105) starting
[Info  - 21:32:05] (14092) Server root directory: c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.1.41\dist
[Info  - 21:32:05] (14092) Starting service instance "aiotieba"
[Info  - 21:32:05] (14092) Auto-indent enabled
[Info  - 21:32:05] (14092) No configuration file found.
[Info  - 21:32:05] (14092) pyproject.toml file found at d:\Code\Python\aiotieba\aiotieba.
[Info  - 21:32:05] (14092) Setting pythonPath for service "aiotieba": "C:\Program Files\Python\Python311\python.exe"
[Info  - 21:32:05] (14092) Loading pyproject.toml file at d:\Code\Python\aiotieba\aiotieba\pyproject.toml
[Error - 21:32:05] (14092) Pyproject file "d:\Code\Python\aiotieba\aiotieba\pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 21:32:05] (14092) stubPath d:\Code\Python\aiotieba\aiotieba\typings is not a valid directory.
[Info  - 21:32:06] (14092) Assuming Python version 3.11
[Info  - 21:32:06] (14092) Assuming Python platform Windows
[Info  - 21:32:06] (14092) Searching for source files
[Info  - 21:32:06] (14092) Found 271 source files
[Info  - 21:32:06] (14092) Background analysis(1) root directory: c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.1.41\dist
[Info  - 21:32:06] (14092) Background analysis(1) started
[Info  - 21:32:07] (14092) Indexer background runner(2) root directory: c:\Users\Administrator\.vscode\extensions\ms-python.vscode-pylance-2023.1.41\dist (index)
[Info  - 21:32:07] (14092) Indexing(2) started
[Info  - 21:32:07] (14092) scanned(2) 49 files over 1 exec env
[Info  - 21:32:08] (14092) indexed(2) 35 files over 1 exec env
[Info  - 21:32:08] (14092) Indexing finished(2).
[Info  - 21:32:09] (14092) [BG(1)] Long operation: getSemanticTokens full at d:\Code\Python\aiotieba\aiotieba\aiotieba\client\_client.py (2989ms)
```

## Sample

https://github.com/Starry-OvO/aiotieba/blob/master/aiotieba/client/_client.py

This file has 2,103 lines, imports 77 sub-packages, including 48 files generated by protobuf. All the files are really small (<1KB), and well typed except for the auto-gen protobuf codes.

## Environment

I've tested `_client.py` on several versions between `2023.1.40` and `2023.2.13`, `2023.1.41` is the version that this weird problem first appears, and still remain in `2023.2.13`.

It can be reproduced on both of my two PC:

- Windows 11 + CPython 3.11.1
- Windows 10 + CPython 3.10.9

## Other

I also checked the previous issues and ChangeLog of [`2023.1.41`](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023141-25-january-2023-prerelease) and pyright [1.1.291](https://github.com/microsoft/pyright/releases/tag/1.1.291) but found no clue.

**Comment by bschnurr** [comment]
the log `[Info  - 21:32:09] (14092) [BG(1)] Long operation: getSemanticTokens full at d:\Code\Python\aiotieba\aiotieba\aiotieba\client\_client.py (2989ms)` might be redharring, due to non deterministic behavior in the order of analysis and semantic token process ordering.

that you for the easy repo though.

i'll see if I can find any bottle necks in the code.

**Comment by Starry-OvO** [comment]
Just now I accidentally updated Pylance to `2023.2.21` and found that the problem is already disappeared.
I guess this is the by-product of my recent commits. So I test several cases as the table shows below.

| Commit | `2023.1.40` | `2023.1.41` | `2023.2.21` |
| :-----| :----: | :----: | :----: |
| [early commit](https://github.com/Starry-OvO/aiotieba/blob/170b54066f3d24954eea6878b2088aaf92bd6e36/aiotieba/client/_client.py) | fast | slow (3.236s) | slow (3.244s) |
| [latest commit](https://github.com/Starry-OvO/aiotieba/blob/d018ab9ce8e4d570e27c1831f490fd2486608e67/aiotieba/client/_client.py) | fast | fast | fast |

The main difference between these two versions is the removal of `import` inside of functions.

The early commit be like

```python
def foo():
    import sth
    ...
```

and the latest commit be like

```python
import sth

def foo():
    ...
```

Maybe the import inside of functions is just the culprit.

**Comment by erictraut** [comment]
If you can create a minimal, self-contained example and/or a set of repro steps, we'd be happy to take a look at it.

**Comment by Starry-OvO** [comment]
The bottleneck is just from `Resolve Imports`.

Stats of [latest commit](https://github.com/Starry-OvO/aiotieba/blob/d018ab9ce8e4d570e27c1831f490fd2486608e67/aiotieba/client/_client.py)

```log
Analysis stats
Total files parsed and bound: 453
Total files checked: 1

Timing stats
Find Source Files:    0sec
Read Source Files:    0.08sec
Tokenize:             0.11sec
Parse:                0.18sec
Resolve Imports:      0.34sec
Bind:                 0.22sec
Check:                0.38sec
Detect Cycles:        0sec
```

The source file looks like

```python
import numpy


class ImportAtTop:
    def numpy(self):
        return numpy.empty(0, numpy.uint8)
```

Stats of [early commit](https://github.com/Starry-OvO/aiotieba/blob/170b54066f3d24954eea6878b2088aaf92bd6e36/aiotieba/client/_client.py)

```log
Analysis stats
Total files parsed and bound: 463
Total files checked: 1

Timing stats
Find Source Files:    0sec
Read Source Files:    0.06sec
Tokenize:             0.12sec
Parse:                0.19sec
Resolve Imports:      1.96sec
Bind:                 0.22sec
Check:                0.36sec
Detect Cycles:        0sec
```

The source file looks like

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import numpy


class ImportAtTop:
    def numpy(self):  # this overload naming may lead to overload analysis
        import numpy

        return numpy.empty(0, numpy.uint8)
```

It seems that this weird problem is caused by my weird function naming since I set the name of functions identically with the name of related submodules.

Then the extra time cost may come from this change:

https://github.com/microsoft/pyright/compare/e96b3ece...01758105#diff-e8178cbc8c6f5764a3b368c69c7aad9132af94c62d25559c433c80d58e9cf51dR22601-R22624

**Comment by bschnurr** [comment]
Thank you for the additional info.

**Comment by bschnurr** [comment]
closing because on the newer builds its gone
