### ISSUE TITLE
Improve smart ordering of Intellisense suggestions based on common usage

### ISSUE THREAD

**Issue by adamerose** [microsoft/pylance-release#3925]
In some IDEs the autocomplete suggestions are sorted with the most commonly used options at the top, rather than purely alphabetically. Could something like this be done in PyLance?

Example in PyCharm ([description](https://www.jetbrains.com/help/pycharm/auto-completing-code.html#ml_completion)):
<img width="395" alt="image" src="https://user-images.githubusercontent.com/10884874/217371976-ff523745-4a5a-483f-960d-5237cfa67b11.png">

It does seem like maybe PyLance already tries to do this, but couldn't find any mention of it in the settings or docs and it seems buggy. Here is a [demo](https://imgur.com/a/ZdkC6AD) of me repeatedly typing or pressing Ctrl+Space on `df.` and it seems to randomly switch between 5 different behaviors (in order of appearance in the video).

1. `__xor__` at the top, with the rest alphabetical 
2. All alphabetical, but with `head` as the default selection (scrolled down to h)
3. `head` and `__xor__` at the top, with the rest alphabetical
4. `head` at the top, with the rest alphabetical 
5. Purely alphabetical

The inconsistency is a problem, and `__xor__` is not a common method to call on DataFrames, and I think there should be more than 2 preferred suggestions at the top. The PyCharm example is a much better representation of the methods I would expect to be commonly used in this context.

<details>
-   ms-python.vscode-pylance: v2023.2.13
-   ms-python.python: v2023.3.10381854
-   Python version: Python 3.9.6
-   Pandas version: 1.3.1

VS Code Info...
Version: 1.75.0 (system setup)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:23:45.584Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
</details>

**Comment by judej** [comment]
Thanks for the feature request. Have you looked at [Intellicode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)?  It uses AI-assisted IntelliSense to show recommended completion items. Hope this is what you are looking for.
