### ISSUE TITLE
report missing module source

### ISSUE THREAD

**Issue by jimmyausi** [microsoft/pylance-release#3927]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
