### ISSUE TITLE
Type is not hashable - Pylance 

### ISSUE THREAD

**Issue by AsgeirDoku** [microsoft/pylance-release#3936]
## Environment data

```
Python 3.9.2
pydantic 1.9.0

VS-Code 1.75.0
VS-Code python v2023.2.0
VS-Code pylance v2023.2.20
```
VS-Code pylance v2022.9.40 works

## Code Snippet

```python
from typing import Hashable
from pydantic import BaseModel, Field

class BaseId(BaseModel, Hashable):
    id: str

    def __hash__(self) -> int:
        return self.id.__hash__()


class Extend(BaseId):
    pass


highlights = {bi for bi in [Extend(id="first", Extend(id="second"))]}
# Set expansion gets highlighted with:
# Set entry must be hashable
#  Type "Extend" is not hashablePylance[reportGeneralTypeIssues]
```
![Screenshot_20230210_123948](https://user-images.githubusercontent.com/107412262/218083734-444071ad-f2e8-4a6c-b609-921e9a1192a5.png)

## Repro Steps

1. Paste code into VS-Code, 

## Expected behavior

pylance should agree with mypy, a constructed Extend class is hashable.

## Actual behavior

pylance diverges from truth

## Logs

N/A

**Comment by erictraut** [comment]
This appears to be a bug in pydantic. It uses PEP 681 (`dataclass_transform`) to describe the behavior of the `BaseModel` class. That means `BaseModel` adopts dataclass-like behaviors. For dataclasses, a `__hash__` method is synthesized in the following cases (according to [PEP 557](https://peps.python.org/pep-0557/#specification)):
* If `eq` and `frozen` are both true, a `__hash__` method is synthesized.
* If `eq` is true and `frozen` is false, `__hash__` will be set to `None`, marking it unhashable.
* If `eq` is false, `__hash__` will be left untouched meaning the `__hash__` method of the superclass will be used.

Pydantic is specifying that the `BaseModel` defaults to `eq` = true and `frozen` = false. That tells type checkers that they should assume that it will synthesize a `__hash__` method set to `None`, marking it unhashable.

I confirmed that if I modify pydantic's `main.py` file — in particular, by adding a `eq_default=False` argument to the `@dataclass_transform` class decorator on `ModelMetaclass`, then the error goes away. I'm not sure if this is the correct fix though. This means that type checkers will assume that no `__eq__` is synthesized, and I don't know if that is the actual runtime behavior of `ModelMetaclass`. 

I recommend that you report this to the maintainers of pydantic and see what they say.

**Comment by erictraut** [comment]
As a temporary workaround, you could add the following to your `Extend` class:
```python
class Extend(BaseId):
    if TYPE_CHECKING:
        def __hash__(self) -> int: ...
```

**Comment by debonte** [comment]
@erictraut, some thoughts on our `dataclass_transform` support. @AsgeirDoku, this probably isn't relevant to you.

I was also able to eliminate the error by setting `eq=False` on the `Extend` class:

```python
class Extend(BaseId, eq=False):
    pass
```

Given that `__hash__` is defined in `BaseId`, I think it would make more sense to set `eq=False` there, but that doesn't eliminate the error. Seems like a bug?

```python
class BaseId(BaseModel, Hashable, eq=False):
    id: str

    def __hash__(self) -> int:
        return self.id.__hash__()
```

However, both of these approaches result in a runtime error: `TypeError: BaseId.__init_subclass__() takes no keyword arguments`. Based on [this section of PEP 681](https://peps.python.org/pep-0681/#id3), Pyright seems correct to assume keyword args are supported, but I guess Pydantic doesn't support this which is unfortunate.

The equivalent decorator-based approach with attrs seems to work as expected though:

```python
import attr

@attr.s(eq=False)
class BaseId():
    id: str = attr.ib()

    # def __hash__(self) -> int:
    #     return self.id.__hash__()

class Extend(BaseId):
    pass

highlights = {bi for bi in [Extend(id="first"), Extend(id="second")]}
```

**Comment by erictraut** [comment]
The `dataclass_transform` implementation in pyright did not contemplate the use of metaclass or `__init_class__` keyword arguments in an intermediate class definition. Neither (apparently) did PEP 681. So I wouldn't consider this a bug as much as an implementation choice. If there's value in formalizing this behavior, I wouldn't object to changing the implementation. On the other hand, I don't know if this is worth the trouble given that pydantic apparently doesn't support this pattern at runtime.
