### ISSUE TITLE
Make "Fields without default values cannot appear after fields with default values" a toggle-able diagnostic rule

### ISSUE THREAD

**Issue by Redoubts** [microsoft/pylance-release#3939]
As came up in #3562, I have an interest in ignoring rules like the above, but globally and without `# type: ignore` additions to my codebase. Can we have this rule be disabled through a config setting some how?

**Comment by erictraut** [comment]
It's unlikely that we would create a separate diagnostic check specifically for this diagnostic. This is way too specific an error. I recommend using other workarounds.

**Comment by debonte** [comment]
@erictraut, this stemmed from [your comment](https://github.com/microsoft/pylance-release/issues/3562#issuecomment-1424475452) on #3562:

> I think it's reasonable to move this to the `reportGeneralTypeIssues` diagnostic rule. That way, if you disable all type checking (i.e. set `typeCheckingMode` to "off"), it will be disabled globally. If that sounds like a good solution to you, please open a separate enhancement request so we can track that change.

**Comment by erictraut** [comment]
Ah yes, thanks for making that connection for me.

Moving this to `reportGeneralTypeIssues` (which I think is a reasonable idea to consider) is different from having a completely separate rule (which I think would be difficult to justify). @debonte, are you in support of moving this to `reportGeneralTypeIssues`?

**Comment by debonte** [comment]
Sure, sounds good to me. I can make this change if you like.

**Comment by erictraut** [comment]
Great, please do.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.2.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023231-15-february-2023-prerelease)
