### ISSUE TITLE
Excessive CPU Utilization VSCode Pylance

### ISSUE THREAD

**Issue by tseanard** [microsoft/pylance-release#3944]
Type: <b>Bug</b>

Open Python project Folder in VSCode with Python and Pylance extensions enabled.  For each instance of VSCode, three distinct Python threads are created that utilize 8-10% of CPU for each thread.

Extension version: 2023.2.20
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (20.39GB free)|
|Process Argv|--folder-uri file:///c%3A/GIT/Python/basic_kafka_microservice_learning --crash-reporter-id 222d3003-a273-45dc-9c59-16483adfc253|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30660299
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by sergei3000** [comment]
I'm having the same issue but more severe. CPU usage by process Code Helper is around 100%, drains my battery really fast.
```
ps aux | grep 35428
username   35428 200.0  0.8 72010812 137084   ??  R     3:49PM  36:56.23 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/username/.vscode/extensions/ms-python.vscode-pylance-2023.2.20/dist/server.bundle.js --cancellationReceive=file:787703fe46c8fcfe746a022668193a1bdb8ca7d483 --node-ipc --clientProcessId=35305
```
MacOS 13.1
VS Code 1.75.1
Pylance v2023.2.20

**Comment by bschnurr** [comment]
please send us the logs.. see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by kuqquk** [comment]
I have the same issue _only_ I open VScode with a large workspace, like /home/username. Try a small workspace with fewer files. I don't figure out the reason for this and need more investigation.

**Comment by hylkevds** [comment]
I've noticed it happens when I have 1 workspace, that has 2 directories added to it that are both in the same virtual environment. Shortly after starting VSCode there will be one stuck Pylance thread that takes 100% of a CPU core. At some point this also breaks Pylance functionality (highlighting, hinting, etc)

Removing one (any) of the two directories and restarting VSCode fixes the issue.

**Comment by debonte** [comment]
@hylkevds, please open a new issue. Describing the workspace file/directory layout in more detail would be helpful. Also please include a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue).
