### ISSUE TITLE
Pylance cannot provide intellisense for xml.dom.parse()

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#3946]
Example:

```
from xml.dom import minidom
doc= minidom.parse("abc.xml")
doc.
```

We cannot get any intellisense. And it shows that the return of parse is any.

![image](https://user-images.githubusercontent.com/100815370/218354491-afc85597-a016-4bee-93b1-30281559fdfe.png)

![image](https://user-images.githubusercontent.com/100815370/218354523-ca148d26-56f7-486a-b6d5-9e977cfce6c5.png)

However it should be document instead of any.

**Comment by erictraut** [comment]
The type information for the `xml` library comes from typeshed. The `parse` function, in particular, can be found [here](https://github.com/python/typeshed/blob/965b3108fe3723e128a7d533ae5c86337cfe2d9b/stdlib/xml/dom/minidom.pyi#L8). Note that it is missing a return type annotation. In general, typeshed has very complete type information for most of the stdlib libraries, but `xml` is an exception. It is quite incomplete. If you are familiar with the `xml` library and want to contribute type information, you can submit PRs directly to typeshed. Pyright and pylance (and other Python type checkers and language servers) bundle the typeshed stubs, so any improvements here will help the entire Python community.
