### ISSUE TITLE
Pylance doesn't show correct list of an object methods after class change

### ISSUE THREAD

**Issue by ParingerGH** [microsoft/pylance-release#3949]
After changing "a" class to "B" it can call B's methods but, popup hints don't show them.

![instance_change_popup_hint](https://user-images.githubusercontent.com/61421117/218451710-4ee834f5-02b7-4af2-8d09-d115dc5ab220.png)

**Comment by heejaechang** [comment]
I am not sure python can even do what you showed above, but even if there is some magic to do so (changing type of an object which is already created in spot), we as a static analysis tool can't support such dynamic behavior. 

we won't be able to figure out calling `change_to_b` will change type of the variable `a` from Type `A` to type `B`

you need to tell type checker explicitly you changed type of the variable `a` by using something like type guard, isinstance or etc.

or change `change_to_b` to explictly return object whose type is `B`

ex)
```python
def change_to_b(self) -> B:
     # do your magic here.
     return ...

b = a.change_to_b()
```

then we will know `b` is type `B`

**Comment by ParingerGH** [comment]
Sadly, I exactly need my users to be able to see hints of such behavior, creating a new variable doesn't suit my purpose. Can u suggest any extensions which can handle it?

**Comment by rchiodo** [comment]
Running such code in a jupyter notebooks might be able to determine the dynamic behavior. Notebooks (when the kernel is active) use the live 'type' of an object when doing completions. 

If you ran a cell where you called `a.change_to_b()`, after that point, the completions for the 'b' type should theoretically come through.

**Comment by heejaechang** [comment]
I am not sure there would be any static analysis tool that can support such thing. only tools that actually run code will be able to support such behavior.

notebook would be one of those tools as @rchiodo suggested. but not statically, but once we ran the cell that has those code.

**Comment by ParingerGH** [comment]
Actually, I'm writing UI auto test project and my goal is to have contractions such as

```python

def test_t1(...):

     site = go_to(adress)
     
     ... some actions on a main page ...
     
     site.open_some_sub_page1() <-- there class is changed, but we are going to use same variable
     
     ... some actions on a sub page 1 ...
     
     site.open_some_sub_page2() <-- and again
     
     ...

```

In that case using notebook cell just for 1 line of code where we change page would be strange workaround (convention) for my users.

Also running test in CI/CD would require to copy-paste all the code from notebooks to actual .py files

**Is it possible to include such functionality (object.__class__ cnage) in some of upcoming patches?**

**This would be great for such a popular dynamically typed language.**

**Comment by judej** [comment]
For this dynamic behavior to work we will need to run the code. We have no plans to do that.
