### ISSUE TITLE
duplicate tooltips

### ISSUE THREAD

**Issue by jablka** [microsoft/pylance-release#3950]
hello, I have no idea what's going on.
I experience duplicate suggestions primarily in Jupyter (documented here https://github.com/microsoft/vscode-jupyter/issues/12029 ).

But this one relates to just Python in VSCode in general.
I have disabled Jupyter extensions, and isort extension, restarted VSCode. Opened a blank new .py file. And this one duplicate "tooltip" is showing.

I have multiple instances of Python installed (basic one, and then Anaconda distribution), but this should not be the problem, right?

My printscreen:
![p2r](https://user-images.githubusercontent.com/20874763/218081546-f36cd424-044b-4d4b-b2d1-3be27a42808e.jpg)

VSCode version: 1.75.1

Python Output:
```
Telemetry level is off
Experiments are disabled, only manually opted experiments are active.
LSP Notebooks experiment is disabled -- Jupyter disabled or not installed
LSP Notebooks interactive window support is disabled -- not in LSP Notebooks experiment
Python interpreter path: C:\Python\python.exe
Starting Pylance language server.
```
Python Language Server Output:
```
[Info  - 12:12:26 PM] (23716) Pylance language server 2023.2.20 (pyright cca7588f) starting
[Info  - 12:12:26 PM] (23716) Server root directory: c:\Users\uzo\.vscode\extensions\ms-python.vscode-pylance-2023.2.20\dist
[Info  - 12:12:26 PM] (23716) Starting service instance "<default>"
[Info  - 12:12:26 PM] (23716) No pyproject.toml file found.
[Info  - 12:12:26 PM] (23716) Setting pythonPath for service "<default>": "C:\Python\python.exe"
[Warn  - 12:12:26 PM] (23716) stubPath typings is not a valid directory.
[Info  - 12:12:26 PM] (23716) Assuming Python version 3.11
[Info  - 12:12:26 PM] (23716) Assuming Python platform Windows
[Info  - 12:12:26 PM] (23716) Searching for source files
[Info  - 12:12:26 PM] (23716) No source files found.
[Info  - 12:12:26 PM] (23716) Background analysis(1) root directory: c:\Users\uzo\.vscode\extensions\ms-python.vscode-pylance-2023.2.20\dist
[Info  - 12:12:26 PM] (23716) Background analysis(1) started
[Info  - 12:12:26 PM] (23716) No pyproject.toml file found.
[Info  - 12:12:26 PM] (23716) Setting pythonPath for service "<default>": "C:\Python\python.exe"
[Warn  - 12:12:26 PM] (23716) stubPath typings is not a valid directory.
[Info  - 12:12:26 PM] (23716) Assuming Python version 3.11
[Info  - 12:12:26 PM] (23716) Assuming Python platform Windows
[Info  - 12:12:26 PM] (23716) Searching for source files
[Info  - 12:12:26 PM] (23716) No source files found.
```

**Comment by bschnurr** [comment]
typeshed recently updated their type stubs for `print`. What you are seeing are overloads
![image](https://user-images.githubusercontent.com/1946977/218531627-e0dd2afb-8a6d-4ea6-b4f6-a1f6cf0eb0cc.png)

**Comment by erictraut** [comment]
Those are not duplicates. The `print` function is a polymorphic function that supports different sets of arguments. These are sometimes referred to as "overloads". Pylance is showing you the various overloads. If you right click on `print` and choose `Go To Declaration`, you will see the overload definitions.

**Comment by jablka** [comment]
interesting, thank you!
