### ISSUE TITLE
Intellisense want's me to rename the file to "code_1.py"

### ISSUE THREAD

**Issue by SunboX** [microsoft/pylance-release#3951]
Type: <b>Bug</b>

# Behaviour

All is underlined yellow, because Intellisense wants me to rename the file from "code.py" to "code_1.py".

<img width="708" alt="Bildschirm­foto 2023-02-13 um 17 48 32" src="https://user-images.githubusercontent.com/83344/218522010-7325d556-9586-45e8-b1e6-03942f406424.png">

## Expected vs. Actual

No suggestion. No yellow marking of the whole file.

## Steps to reproduce:

Open attached project in VS Code with Python extension installed.
[Archiv.zip](https://github.com/microsoft/vscode-python/files/10724427/Archiv.zip)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.8
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.2.0
VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 8efc867a-192d-4bc1-923c-cdab463da5e1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30660299
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
89544117:30613380
pythonsymbol12:30657548

```

</details>

**Comment by rchiodo** [comment]
If you want to keep your 'code.py' because you're are purpose changing the stdlib import, you can set this setting to disable the warning:

```json
  "python.analysis.diagnosticSeverityOverrides": {
    "reportShadowedImports": "none"
  },
````
