### ISSUE TITLE
Incomplete docstring for functions in some python libs

### ISSUE THREAD

**Issue by MatiasOB** [microsoft/pylance-release#3958]
Issue still persists after extensions disabled. (using pylance or jedi issue also still persists).
Using the same conda Venv in all pictures i will post below.

![image](https://user-images.githubusercontent.com/113733547/218919875-75d061a1-596b-4d30-b421-5a046d47198e.png)

- VS Code Version:  1.75.1
- OS Version: Windows 10

Steps to Reproduce:

Incomplete docstring for some libraries functions. (only shows signature, not docstring)

example of this issue using a function from the seaborn library:
![image](https://user-images.githubusercontent.com/113733547/218920548-edaf915d-914a-497d-9126-23ad20eb9479.png)

only way i can get a full docstring documentation in VScode is via the following way, but its far from ideal
![image](https://user-images.githubusercontent.com/113733547/218924001-1232bb49-29cb-4d96-8281-23c8795adacb.png)

issue doesn't replicate in a browser jupyter notebook (using same venv):
![image](https://user-images.githubusercontent.com/113733547/218923554-aaec27d6-72f0-44ea-88e1-23824e6cdde0.png)

Also some libraries don't have this issue like numpy or pandas:
example using a function from numpy library in Vscode (this shows docstring properly and has no issues compared to other libs like seaborn or plotly)
![image](https://user-images.githubusercontent.com/113733547/218921050-6855cb52-482a-42c8-908a-ca48b69e2520.png)

Posting my settings.json just in case.
![image](https://user-images.githubusercontent.com/113733547/218941227-fdb68d05-7a6f-4d70-98fb-b7895e5903ec.png)

**Comment by rchiodo** [comment]
This is happening because seaborn doesn't publish the docstrings. When you goto definition on `scatterplot` it looks like this:

![image](https://user-images.githubusercontent.com/19672699/219114820-e2938682-ef2f-4ff4-9d65-841516a6e8fc.png)

This can be fixed if somebody adds docstrings to the seaborn type stubs here:
https://github.com/microsoft/python-type-stubs/tree/main/seaborn-stubs

I believe the jupyter kernel can get the docstrings because they are injected into the functions at runtime. Something like so:

```
sns.scatterpot.__doc__ = "A doc string"
```

Pylance (and Pyright) cannot get docstrings this way because they don't run any python code.

**Comment by rchiodo** [comment]
Numpy and pandas do have docstrings either in their type stubs or in their relevant source. For example here's the definition of a dataframe in pandas:

![image](https://user-images.githubusercontent.com/19672699/219117538-1b1a811e-5146-4a69-a741-f33c159cdd98.png)

**Comment by rchiodo** [comment]
> Is there any possibility to make Pylance (and Pyright), indeed run code like the jupyter kernel. to make it an overall fix for any library?

Sorry but not anytime in the near future. Pylance is a static type analyzer very much on purpose. Running python code (and user's code) has all sort of unknown side effects that a language server wouldn't want to have happen. 

It might be possible to have Pylance understand the state of a Jupyter kernel though. That's code that the user has run for themselves. Pylance would then just inspect the kernel and not alter it in any way. 

That's the hard part with running code. Code can alter your machine and we really don't want to do that.

**Comment by erictraut** [comment]
There's already a way to determine the type of a symbol at runtime — by actually running the code. That's the job of an interpreter and a debugger. Those tools already exist, and you can make use of them if you want. Static type checkers, like those that are built into Pylance and PyCharm, play a different role. They determine types based on a static analysis of the code without running any of the code. This has some limitations, but it also has some major strengths that a runtime interpreter or debugger cannot replicate.

**Comment by GF-Huang** [comment]
It's still suck in 2024. https://stackoverflow.com/questions/78193572/why-so-many-python-built-in-functions-has-no-in-code-docs?noredirect=1#comment137852540_78193572

**Comment by debonte** [comment]
@GF-Huang, I filed a new issue to track that -- https://github.com/microsoft/pylance-release/issues/5831
