### ISSUE TITLE
Azure packages cause ERR_WORKER_OUT_OF_MEMORY error in Pylance

### ISSUE THREAD

**Issue by justinbowes** [microsoft/pylance-release#3960]
Type: <b>Bug</b>

There has been a significant regression in the Python language server recently. It consistently hangs working on a Python project with azure-mgmt-{compute,network,resource} and azure-identity installed. I'm forced to return to Jedi for this project. 

Setting verboseOutput: true in pyrightconfig.json shows OOM errors consistently:
```
[Info  - 10:57:26 AM] (20024)   Attempting to resolve using root path '<project-root>/venv/lib/python3.8/site-packages/azure/mgmt/compute'
[Error - 10:57:43 AM] (20024) Error occurred on background thread: {"code":"ERR_WORKER_OUT_OF_MEMORY"}
```

Extension version: 2023.2.20
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (7.02GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/<project-root>/api --remote=wsl+Ubuntu --crash-reporter-id 0e83ab72-3776-446b-ab59-607812f494fe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2495)|
|Memory (System)|15.49GB (11.72GB free)|
|VM|0%|

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30662992
89544117:30613380
pythonsymbol12cf:30657549
a9j8j154:30646983
6233i204:30664135
vsccsb:30662443

```

</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

Sorry but I'm not able to reproduce the issue though. I can use azure-mgmt-compute and azure-identity just fine:

![image](https://user-images.githubusercontent.com/19672699/219193436-e142d3a3-3365-404a-85c8-a6141cda4e65.png)

Do you have a sample repository that you're opening? Or maybe a minimal repro?

It might be something unrelated to azure-mgmt (maybe those are just pushing everything over the top).

**Comment by justinbowes** [comment]
You're right -- the Azure packages are likely pushing things over the top. This is a "mature" repo into which the Azure dependencies were recently introduced, so it's a challenge to provide a minimum repro.

Viewing this as an overall heap exhaustion problem, I've disabled all unnecessary plugins and this has helped. Will open a new issue if I can provide a cleaner repro.
