### ISSUE TITLE
Pylance incorrect typecheck on openpyxl worksheet ws["A1"]

### ISSUE THREAD

**Issue by ColorfulQuark** [microsoft/pylance-release#3967]
<h3> Environment data </h3>

-   Language Server version: 2023.2.30
-   OS and version: win32 x64
-   Python version 3.11.2: 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

`from openpyxl import load_workbook`
`wb = load_workbook("c:/temp/file.xlsx")`
`ws = wb["Sheet1"]`
`x = ws["A1"]`

Results in `"__getitem__" method not defined on type "Chartsheet"` for the last line.  However, this code is correct.  See https://openpyxl.readthedocs.io/en/latest/tutorial.html and `openpyxl.worksheet.py` which includes `def __getitem__(self, key)`.  Also, `mypy --strict` does not report an error.

**Comment by erictraut** [comment]
I'm not able to repro the problem you're reporting. The `openpyxl` library is an untyped library (i.e. it contains no "py.typed" marker and does not include inlined type annotations, but there are minimal (admittedly incomplete) type stubs for the library included in typeshed and therefore also bundled with pylance.

If you right click on `load_workbook` and choose "Go To Declaration", where does VS Code take you? In my case, it takes me to a stub file called `stubs/openpyxl/openpyxl/reader/excel.pyi`.

The stub defines `load_workbook` as follows:

```python
def load_workbook(filename, read_only: bool = ..., keep_vba=..., data_only: bool = ..., keep_links: bool = ...): ...
```

Note that the return type is missing, so pylance will use `Any` as the return type here.

**Comment by ColorfulQuark** [comment]
Right clicking on `load_workbook` and choosing `Go To Declaration` takes me to `Lib/site-packages/openpyxl/reader/stubs/excel.pyi` which defines `load_workbook` with a return type `Workbook`.  I uninstalled this file (`openpyxl-stubs`) and the Pylance error went away.  

I am now getting `mypy` errors, but I guess that's not Pylance's problem?

`Skipping analyzing "openpyxl": module is installed, but missing library stubs or py.typed marker`
`See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports`

Seems my choices are to satisfy Pylance or satisfy mypy.

**Comment by erictraut** [comment]
You should not need to install an external stub package in this case. As I mentioned above, the openpyxl stubs are included in typeshed, and pylance bundles the typeshed stubs with it.

It looks like you're using a version of `openpyxl` that includes some stubs. I suspect that's an older version of the library. Have you tried installing the latest version (`pip install openpyxl --upgrade`)?

If you're looking for static type checking capabilities, you don't need to use mypy. Pylance can provide that as well because it is built on [pyright](https://github.com/microsoft/pyright), Microsoft's open-source Python type checker. Simply set `typeCheckingMode` to "basic". If you want to run static type checking in your CI script, you can [do that as well](https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md).

**Comment by ColorfulQuark** [comment]
To clarify, I am using the latest version of `openpyxl`.  I used to use mypy before switching to Pylance.  I installed `openpyxl-stubs,` as it was necessary for running `mypy` without errors. I regularly update both files.

I've been getting the Pylance error message for some time, but finally got annoyed enough to post today.  I ran mypy as a check to see if it found any errors. It's now clear what is happening.

It would be nice if Pylance could do actual type checking on `openpyxl`, rather than using `Any`.  `Any` seems indistinguishable from no type checking. 😛 I hope this doesn't come across as argumentative.

**Comment by erictraut** [comment]
Pyright (the type checker that underlies pylance) is able to infer types from Python code, but it does this only in cases where type stubs are not present. Inferring types is costly and can be error prone. If pyright sees that there's a type stub present, it assumes that the stub is the unambiguous source of truth for type information for that module. You're encountering an unfortunate situation where a type stub is present, but the stub is woefully incomplete and is probably doing more harm than good.

Something for you to consider... you could consider contributing improvements to the [openpyxl type stub in typeshed](https://github.com/python/typeshed/tree/main/stubs/openpyxl/openpyxl). This would benefit the entire Python community regardless of which type checker or language server they're using.
