### ISSUE TITLE
Auto parens happens for except clauses

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#3969]
![image](https://user-images.githubusercontent.com/19672699/219802283-b073fff0-0460-4498-a6d3-53f8c137e5a4.png)

**Comment by rchiodo** [comment]
Want to discuss this item to see how people feel about the algorithm I'm changing it to.

The new algorithm is:

- Any assignment to a class will put the parens. So like `x = Foo()`. This means that if the user intended to set the assigment to a static field of the class, the parens might show up when they don't want them to.
- Any passing of a class as an argument if that class is a builtin, will also have parens. That means something like`foo(list())` will have a parens, but something like `foo(Foo)` will not.

**Comment by debonte** [comment]
It's not clear to me why these two scenarios would behave differently. But I'm also a relatively new Python user, so maybe I'm missing something here.

Do we have data to support this algorithm?

**Comment by erictraut** [comment]
Personally, I wouldn't want auto parentheses in either of these cases, especially the second.

On the second bullet, you mentioned "if that class is a builtin". Why does the fact that it's a builtin matter? Builtin classes are just like all other classes in Python, so I'm not sure why these should be singled out for different behavior. So, if you decide to keep that second bullet, I think it should be consistent for all classes.

**Comment by rchiodo** [comment]
The current implementation puts parens on all builtin class usages. Hence the parens for the usage of `OSError` in an except clause.

I believe the reason for just builtins before was because they have fewer static methods? Not entirely sure. 

This was an attempt to make it more useful.

**Comment by erictraut** [comment]
I think it's worth revisiting the decision to treat builtins specially. If anything, builtins are less likely to be instantiated explicitly through a constructor call because many of them have language syntax for instantiation. For example, you would rarely use `int(0)` or `list()` in favor of `0` or `[]`. The language syntax is simpler and more idiomatic. I suspect that most of the time someone types the name of a builtin symbol within an argument list, their intent is probably _not_ to call the constructor.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023341-29-March-2023-PreRelease)
