### ISSUE TITLE
Pytest fixtures that yield should show the yielded result

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#3973]
I have a test using a fixture like so:

![image](https://user-images.githubusercontent.com/19672699/219822792-ddeaa0ca-cdad-4c51-bff6-c3c69f9a0595.png)

The `app` parameter is from a fixture that yields a `Flask` object. That's what the test will get during the test running (assuming there's a single yield). 

If there was more than one yield, it would be a union of the possible types yielded.

Instead of showing `Generator[Flask...`, this should just show the `Flask` type.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.2.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023241-22-February-2023-PreRelease)
