### ISSUE TITLE
Classes for opencv-python are not detected and break intellisense autocomplete

### ISSUE THREAD

**Issue by elesbb** [microsoft/pylance-release#3976]
`videoReader: cv2.VideoCapture = cv2.VideoCapture(videoFileLocation)
fps = int(videoReader.`

After typing the "dot" after the "videoReader" variable, there is no autocompletion. After hovering over "cv2.VideoCapture", it shows "Any" as class type.

**Comment by erictraut** [comment]
This is a duplicate of https://github.com/microsoft/pylance-release/issues/138.

**Comment by elesbb** [comment]
> This is a duplicate of #138.

I don't think so.

I read this before posting an issue. The issue is NOT having "cv2." autocomplete, but any classes INSIDE cv2 do not have autocompletion nor class typing. All the "fixes" mentioned there don't fix the issue I am having.

**Comment by erictraut** [comment]
Which workarounds have you tried? Have you generated your own local type stubs for `cv2` using "stubgen" or similar tools? Without type information, pylance will not be able to provide any autocomplete suggestions. Most libraries ship with Python code, and pylance can analyze the code to infer type information. However, `cv2` is not written in Python, so pylance has no code to analyze. Most libraries that are not written in Python ship with additional type information in the form of "type stub" (.pyi) files. Unfortunately, cv2 does not. If this library is important to you, you may want to encourage the maintainers to include type stubs in a future version. In the meantime, you would need to create your own type stubs (or install a type stub package created by someone else) if you want pylance to provide completion suggestions for symbols in the cv2 library.

**Comment by elesbb** [comment]
> Which workarounds have you tried? Have you generated your own local type stubs for `cv2` using "stubgen" or similar tools? Without type information, pylance will not be able to provide any autocomplete suggestions. Most libraries ship with Python code, and pylance can analyze the code to infer type information. However, `cv2` is not written in Python, so pylance has no code to analyze. Most libraries that are not written in Python ship with additional type information in the form of "type stub" (.pyi) files. Unfortunately, cv2 does not. If this library is important to you, you may want to encourage the maintainers to include type stubs in a future version. In the meantime, you would need to create your own type stubs (or install a type stub package created by someone else) if you want pylance to provide completion suggestions for symbols in the cv2 library.
> 
> PyCharm will extract minimal type information out of a binary library like cv2. It does so by loading (and therefore executing) the library and then using reflection to extract classes, methods, etc. Pylance does not do this for security and performance reasons. You would need to do this manually using a tool like stubgen to extract the type information.

Here is what I have done:
`C:\Users\Seth>stubgen -m cv2 -o C:\Users\Seth\AppData\Local\Programs\Python\Python311\Lib\site-packages\cv2
Processed 1 modules
Generated C:\Users\Seth\AppData\Local\Programs\Python\Python311\Lib\site-packages\cv2\cv2/__init__.pyi`

And there is still no autocomplete for the classes inside cv2.

I also tried copying the file it generates into multiple different locations.

I even added the location for the pyi to the extrapaths in the python extension settings.

**Comment by erictraut** [comment]
Once you generate the type stubs via stubgen, you need to move them into a project-local directory called `typings/cv2/<stubs go here>`. If you don't do this, pylance will not be able to find them. You can opt to check these stubs in with the rest of your project if you want other collaborators to also access them.

**Comment by elesbb** [comment]
> Once you generate the type stubs via stubgen, you need to move them into a project-local directory called `typings/cv2/<stubs go here>`. If you don't do this, pylance will not be able to find them. You can opt to check these stubs in with the rest of your project if you want other collaborators to also access them.

Is there a solution that is not project dependent? Would be very annoying if I have to do this for every single project. I would like it to stay this way for the interpreter that Pylance is set to.

**Comment by erictraut** [comment]
The best solution is for the maintainers of opencv to include type stubs with their library.

The next best solution is for someone to publish a "cv2-stubs" stub package on pypi that includes type stubs for opencv. This could then be installed in your python environment and used for all of your projects. You could check with the maintainers of typeshed to see if they'd be interested in including stubs for cv2. Then you could contribute yours as a starting point.

**Comment by elesbb** [comment]
> The next best solution is for someone to publish a "cv2-stubs" stub package on pypi that includes type stubs for opencv. This could then be installed in your python environment and used for all of your projects. You could check with the maintainers of typeshed to see if they'd be interested in including stubs for cv2. Then you could contribute yours as a starting point.

How could I publish a cv2-stubs package myself? 

For example, how could I go about getting this working on my own local machine, then share it with others? Would I be able to use the __init__.pyi file to do this?

**Comment by erictraut** [comment]
[PEP 561](https://peps.python.org/pep-0561/) is a good place to start for information on this topic.

If you are able to incorporate the cv2 stubs into [typeshed](https://github.com/python/typeshed), the stub package will automatically be published because that project has a bunch of automation for creating and publishing stub packages.

**Comment by elesbb** [comment]
Thanks my friend! I shall look into this!
