### ISSUE TITLE
Pylance very slow on analyzing files

### ISSUE THREAD

**Issue by yanxke** [microsoft/pylance-release#3977]
## Environment data

-   Language Server version: 2023.2.30 (pyright dec6aa20) 
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6 64-bit from Windows Store

## Code Snippet

Seems to be related to my import of numpy because if I comment it out it seems okay.  FWIW, I'm using np.array in my type hints.

## Logs
[Info  - 9:30:10 AM] (28044) SourceFile: Received fs event 'change' for path 'myscript.py'
(28044) [BG(1)] parsing: myscript.py (53ms)
(28044) [BG(1)] binding: myscript.py (4ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (26ms)
(28044) [BG(1)] binding: myscript.py (6ms)
(28044) [BG(1)] indexing: myscript.py (1ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background inlayHint message
(28044) [FG] completion at myscript.py:471:61 ...
(28044) [FG]   parsing: myscript.py (35ms)
(28044) [FG]   binding: myscript.py (6ms)
(28044) [FG] completion at myscript.py:471:61 [found 11 items] (555ms)
(28044) [FG] completion at myscript.py:471:62 ...
(28044) [FG]   parsing: myscript.py (50ms)
(28044) [FG]   binding: myscript.py (6ms)
(28044) [FG] completion at myscript.py:471:62 [found 9 items] (567ms)
(28044) [FG] completion at myscript.py:471:63 ...
(28044) [FG]   parsing: myscript.py (24ms)
(28044) [FG]   binding: myscript.py (5ms)
(28044) [FG] completion at myscript.py:471:63 [found 7 items] (647ms)
(28044) [FG] parsing: myscript.py (48ms)
(28044) [FG] binding: myscript.py (16ms)
(28044) [FG] completion at myscript.py:471:74 ...
(28044) [FG]   parsing: myscript.py (51ms)
(28044) [FG]   binding: myscript.py (17ms)
(28044) [FG] completion at myscript.py:471:74 [found 97 items] (636ms)
(28044) [FG] parsing: myscript.py (52ms)
(28044) [FG] binding: myscript.py (5ms)
(28044) [FG] completion at myscript.py:471:79 [found 1 items] (4ms)
(28044) [FG] parsing: myscript.py (24ms)
(28044) [FG] binding: myscript.py (11ms)
[Info  - 9:30:16 AM] (28044) SourceFile: Received fs event 'change' for path 'myscript.py'
(28044) [FG] parsing: myscript.py (43ms)
(28044) [FG] binding: myscript.py (13ms)
[Info  - 9:30:18 AM] (28044) SourceFile: Received fs event 'change' for path 'myscript.py'
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   checking: myscript.py (23ms)
(28044) [BG(1)] analyzing: myscript.py (23ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (30ms)
(28044) [BG(1)] binding: myscript.py (6ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (27ms)
(28044) [BG(1)] binding: myscript.py (9ms)
(28044) [BG(1)] indexing: myscript.py (1ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background inlayHint message
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   checking: myscript.py (20ms)
(28044) [BG(1)] analyzing: myscript.py (20ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   parsing: myscript.py (36ms)
(28044) [BG(1)]   binding: myscript.py (13ms)
(28044) [BG(1)]   checking: myscript.py (0ms)
(28044) [BG(1)] analyzing: myscript.py (50ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background inlayHint message
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   checking: myscript.py (35ms)
(28044) [BG(1)] analyzing: myscript.py (35ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (36ms)
(28044) [BG(1)] binding: myscript.py (16ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (49ms)
(28044) [BG(1)] binding: myscript.py (16ms)
(28044) [BG(1)] indexing: myscript.py (1ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (51ms)
(28044) [BG(1)] binding: myscript.py (12ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (23ms)
(28044) [BG(1)] binding: myscript.py (7ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (53ms)
(28044) [BG(1)] binding: myscript.py (14ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (36ms)
(28044) [BG(1)] binding: myscript.py (4ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (20ms)
(28044) [BG(1)] binding: myscript.py (14ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background inlayHint message
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (36ms)
(28044) [BG(1)] binding: myscript.py (4ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (19ms)
(28044) [BG(1)] binding: myscript.py (8ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getSemanticTokens delta
(28044) [BG(1)] getSemanticTokens delta previousResultId:1676827809097 at myscript.py (8264ms)
[Info  - 9:30:47 AM] (28044) [BG(1)] Long operation: getSemanticTokens delta previousResultId:1676827809097 at myscript.py (8264ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   parsing: myscript.py (30ms)
(28044) [BG(1)]   binding: myscript.py (4ms)
(28044) [BG(1)]   checking: myscript.py (0ms)
(28044) [BG(1)] analyzing: myscript.py (37ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (36ms)
(28044) [BG(1)] binding: myscript.py (17ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (49ms)
(28044) [BG(1)] binding: myscript.py (15ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] parsing: myscript.py (35ms)
(28044) [BG(1)] binding: myscript.py (14ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: getDiagnosticsForRange
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   parsing: myscript.py (37ms)
(28044) [BG(1)]   binding: myscript.py (4ms)
(28044) [BG(1)]   checking: myscript.py (1ms)
(28044) [BG(1)] analyzing: myscript.py (43ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background inlayHint message
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) Background analysis message: setFileOpened
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   parsing: myscript.py (19ms)
(28044) [BG(1)]   binding: myscript.py (5ms)
(28044) [BG(1)]   checking: myscript.py (2ms)
(28044) [BG(1)] analyzing: myscript.py (26ms)
(28044) [BG(1)] indexing: myscript.py (0ms)
(28044) Background inlayHint message
(28044) Background analysis message: markFilesDirty
(28044) Background analysis message: analyze
(28044) [BG(1)] analyzing: myscript.py ...
(28044) [BG(1)]   checking: myscript.py (159ms)
(28044) [BG(1)] analyzing: myscript.py (159ms)
(28044) Background inlayHint message
(28044) Background analysis message: getSemanticTokens delta
(28044) [BG(1)] getSemanticTokens delta previousResultId:1676827839652 at myscript.py (237ms)
(28044) Background analysis message: resumeAnalysis```
```

**Comment by erictraut** [comment]
Thanks for the log. Unfortunately, that's not enough information for us to diagnose the problem. By any chance, is your code in a public github repo? Or is it in a private repo that you'd be willing to give me temporary access to? If not, we'd need you to do some diagnosis to help us narrow down the problem.

**Comment by judej** [comment]
What extensions are you using? Have you tried disabling the other extensions and see if the problem persists?
