### ISSUE TITLE
Pylance loses type information after applying sorted() on list of dataclass instances

### ISSUE THREAD

**Issue by somiandras** [microsoft/pylance-release#3979]
<h3> Environment data </h3>

-   Language Server version: 2023.2.30
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from dataclasses import dataclass
from typing import reveal_type


@dataclass
class MyDataClass:
    name: str


my_list = [MyDataClass(name=str(item)) for item in range(10)]
my_sorted_list = sorted(my_list, key=lambda x: x.name)


reveal_type(my_list) # list[MyDataClass]
reveal_type(my_sorted_list) # list[Unknown]
```

<h3> Repro Steps </h3>

1. Create a list of dataclass instances.
2. Apply `sorted()` on the list.

<h3> Expected behavior </h3>

Sorting should not obscure the type of list elements, sorted list should have the same type (`list[MyDataClass]`) as the original. I'm pretty sure that was the case a while ago, but couldn't find an earlier version where this actually worked.

<h3> Actual behavior </h3>

Pylance loses the type information and treats the sorted list of dataclass instances as a list of elements of unknown type.

<h3> Logs </h3>

```
[Info  - 14:38:21] (27083) Pylance language server 2023.2.30 (pyright dec6aa20) starting
[Info  - 14:38:21] (27083) Server root directory: /Users/somiandras/.vscode/extensions/ms-python.vscode-pylance-2023.2.30/dist
[Info  - 14:38:21] (27083) Starting service instance "collective"
[Info  - 14:38:21] (27083) Starting service instance "<default>"
```

**Comment by erictraut** [comment]
I'm not able to repro the behavior you're seeing. Can you please double check that when you paste the above code sample into a new editor window within a new project that you are able to repro the behavior described? 

Here's what I see:
![image](https://user-images.githubusercontent.com/7040122/220145570-cbf65190-024d-4202-97b7-bf4f038caeff.png)

**Comment by somiandras** [comment]
Actually, in my original code the sorting class variable of the dataclass is not of type `str`, but `Literal[...]`. If I change it to simple `str` the type hint works, but not with the `Literal[]`... 

I wasn't able to reproduce this with my example above, `Literal[]` key won't confuse the type checker in the simple script. 🤯🤯🤯

Anyway, I cannot seem to be able to narrow it down better now.

**Comment by heejaechang** [comment]
if there is no repro, there is not much we can do.
