### ISSUE TITLE
issue with semantic highlighting - dimming

### ISSUE THREAD

**Issue by rholland** [microsoft/pylance-release#398]
Does pylance dim code that it thinks is unreachable?  I have some code that modifies itself during runtime.  Pylance significantly dims all of the code after a function call that it may think ends the program, but really doesn't.  Is there a way to disable this behavior? 

Thanks.

**Comment by erictraut** [comment]
Can you provide more details about the code immediately before the dimmed section? I'm guessing that there is a call expression to a function or method that has no return type annotation and always raises an exception on all code paths. When there is no return type annotation, Pylance will analyze the code within the function's implementation to infer the return type. If there is no possible way for it to return, it infers a `NoReturn` type.

If you don't like this behavior, you can work around it by adding an explicit return type annotation to the function or method in question.

**Comment by jakebailey** [comment]
Note that this isn't tied to semantic highlighting; if code is marked as unreachable, it gets dimmed via a special diagnostic that VS Code chooses to render by dimming the code.

Feasibly, you could disable dimming in VS Code by setting something like:

```json
{
    "[python]": {
        "editor.showUnused": false
    }
}
```

But the code flow will still regard the code to be unreachable (which has significant impact for the overall analysis), hence Eric's questioning here.

**Comment by rholland** [comment]
The function has an os._exit(1) but it is only executed after the subsequent code is read by doing some modifications on the fly.  

Thanks very much for your helpful explanation and solution.  Your suggestion took care of it. I'll close this now.
