### ISSUE TITLE
VSCode 1.75.1 tensorflow intellisense no longer works

### ISSUE THREAD

**Issue by rivershah** [microsoft/pylance-release#3985]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

VSCode 1.75.1 tensorflow intellisense no longer works

## Steps to reproduce:

Steps to reproduce:

Create devcontainer with Dockerfile:

FROM tensorflow/tensorflow:2.11.0-gpu

"extensions": [
    "ms-python.python",
    "ms-python.vscode-pylance",
...
]
Open up a python file

import tensorflow as tf

tf.minimum # won't intellisense
tf.Tensor # intellisense will work

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• flake8Enabled: true

formatting
• provider: "black"
• blackArgs: "<placeholder>"

testing
• pytestArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2023.2.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.19.0-23-cloud-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 5|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id d7dc3061-a555-4929-a6f3-c6097ddec231|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Dockerfile @ ssh://34.67.74.176|
|OS|Linux x64 4.19.0-23-cloud-amd64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.20GHz (48 x 2200)|
|Memory (System)|334.59GB (329.57GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30660299
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779cf:30662993
89544117:30613380
pythonsymbol12cf:30657549
vsccsb:30662443
vscodedisable:30660115

```

</details>

**Comment by judej** [comment]
Thank for the report. Could you please see if this reproduces on the latest version of Pylance (2023.2.30)  We removed the Tensorflow typestubs and you should see more completion. 

Please reopen if you continue to see the problem.

**Comment by rivershah** [comment]
Problem still persists. Inside `devcontainer.json` I reverted python and pylance to the following version to get intellisense to work with tensorflow. Most recent version still does not work
```
"customizations": {
    "vscode": {
      "extensions": [
        "ms-python.python@2023.1.31",
        "ms-python.vscode-pylance@2023.1.31",
        "ms-python.flake",
...
```
