### ISSUE TITLE
IntelliSense fails to load packages from keras in .venv/lib/python 3.10/site-packages/keras/ also from tensorflow

### ISSUE THREAD

**Issue by Apisteftos** [microsoft/pylance-release#3987]
According to tensorflow we can load dynamically keras either from their API `.venv/lib/python 3.10/site-packages/tensorflow/keras`     or directly from `.venv/lib/python 3.10/site-packages/keras/ `  [keras-team](https://github.com/keras-team/) .  While I am trying to load the datasets e.g.  `datasets.cifar10.load_data()`   or   `tf.keras.datasets.cifar10.load_data()`  intelliSense doesn't work. In the first case  after hitting `dataset. ` shows me:

<pre>
__spec__
__annotations__
__cached__
__builtins__
.
.
.
etc

</pre>

but no `cifar10.load_data()`. In the second case after `tf.` fails to load keras. But the result in both cases is correct. 

keras version 2.10.0
tensorflow version 2.10.0 

Should I downgrade even more the tensorflow version?

**Comment by bschnurr** [comment]
please try the latest pre-release  pylance 2023.2.31

**Comment by Apisteftos** [comment]
Yes it works for tensorflow. Thanks!
