### ISSUE TITLE
False alarm: reportGeneralTypeIssues

### ISSUE THREAD

**Issue by huynd26** [microsoft/pylance-release#3990]
Seem it still raises the error after setting python.analysis.typeCheckingMode': 'off
I have some query set with the related fields, and everything is ok, but today, when working time, the error `reportGeneralTypeIssues` appears.
example:
![220575015-f98f5b09-381b-4cb2-8e26-b2d6720a1983](https://user-images.githubusercontent.com/109842259/220801976-7c6f84f2-12b5-4cae-ab23-30cf2eec2b8c.png)

OS and version: Ubuntu 20.04.5 LTS
Python version: 3.9.15+
Pylance: v2023.2.30

**Comment by rchiodo** [comment]
Thanks for the issue but I can't reproduce it. Do you have a complete sample that reproduces it?


For example typing this for me causes a squiggle:
```
x =[4]
x.bar
```

turning off type checking makes the squiggle go away

**Comment by huynd26** [comment]
Oh, it only appears error in my Django project, I try to open a new python file and type follow you, not any error happened.

**Comment by huynd26** [comment]
I realize I don't change TypeCheckingMode on Workspace too, just changed it on User, so this problem has been resolved. Thank you.
