### ISSUE TITLE
Wrong syntax highlighting

### ISSUE THREAD

**Issue by CanePlayz** [microsoft/pylance-release#3999]
## Environment data

-   Language Server version: v2023.2.41
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2

## Code Snippet

```python
import xlsxwriter as xl

workbook = xl.Workbook("Test.xlsx")
workbook.add_worksheet()
rock = wb.add_format({"font_color": "#b71f19"})
worksheet.conditional_format("A1:B2", {"type": "cell", "criteria": "==", "value": '"Rock"', "format": rock})
```

## Repro Steps

1. Use A1 notation for the range of a conditional format method.

## Expected behavior

No highlighting because this alternate "A1 notation" works (see documentation [here](https://xlsxwriter.readthedocs.io/worksheet.html?highlight=conditional#conditional_format))

## Actual behavior

This false syntax highlighting appears: 
![image](https://user-images.githubusercontent.com/81419612/221038819-eec16ef3-20e6-48b4-aed3-402ef51bacab.png)

## Logs

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue. 

This is by design unfortunately. The definition of `conditional_format` is like so:
```python
    @convert_range_args
    def conditional_format(self, first_row, first_col, last_row, last_col,
                           options=None):
```

There are no overloads defined and pylance can't run the code in the decorator,  so it will give this error.

You could try adding an overload to `conditional_format` (you'd have to submit to xlsxwriter) or you could do this:


```python
import xlsxwriter as xl

workbook = xl.Workbook("Test.xlsx")
worksheet = workbook.add_worksheet()
rock = workbook.add_format({"font_color": "#b71f19"})
worksheet.conditional_format("A1:B2", {"type": "cell", "criteria": "==", "value": '"Rock"', "format": rock}) # type: ignore
```

**Comment by CanePlayz** [comment]
Thanks! :)
