### ISSUE TITLE
Support pyrightconfig.json intellisense

### ISSUE THREAD

**Issue by tamuhey** [microsoft/pylance-release#40]
VSCode pyright extension supports [intellisense for pyrightconfig.json](https://github.com/microsoft/pyright/commit/3ebdb0b9b00da5fe0b4f26849f6fa9a1e0b67bed).

It'd be great if pylance also supports the intellisense.

**Comment by savannahostrowski** [comment]
Hey @tamuhey 

Thanks for the suggestion. We are currently investigating this request and will update with details soon.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
