### ISSUE TITLE
Can not work when  assigns a type to a function with a Any return type

### ISSUE THREAD

**Issue by VEADoc** [microsoft/pylance-release#400]
## Environment data

-   Language Server version: v2020.9.5
-   OS and version: macOS Catalina 10.15.5 (Beta) 19F62f
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.7

![图片](https://user-images.githubusercontent.com/22616515/93863460-1902f500-fcf6-11ea-9a10-2e8bce412116.png)

## Expected behaviour
![图片](https://user-images.githubusercontent.com/22616515/93863126-b3166d80-fcf5-11ea-9063-5ea6a49bd403.png)

## Actual behaviour
![图片](https://user-images.githubusercontent.com/22616515/93863190-cb868800-fcf5-11ea-92d5-a81cad47bd55.png)

Do you get what I mean? 👨🏻‍💻👨🏻‍💻👨🏻‍💻👨🏻‍💻

**Comment by erictraut** [comment]
I am not able to repro the problem you're reporting. There must be something about your specific code that I'm not able to understand from the screen shots above. Could you please provide a simple and self-contained code sample that exhibits the problem?

Here's my attempt, which works as expected:
```python
from typing import Any, Callable

def foo(a: Callable[[], Any]):
    b: int = a()
    reveal_type(b)
```

My best guess based on the symptoms you're seeing is that the type of `WXPayGetCertificatesResponse` is unknown to Pylance. If you hover over this symbol, it should tell you whether it's a class or "Unknown". If it's the latter, that would explain what you're seeing. And then we'd need to determine why it's an unknown type.

**Comment by VEADoc** [comment]
This happens occasionally. I'm not sure under what conditions this happened

<img width="796" alt="图片" src="https://user-images.githubusercontent.com/22616515/93955027-72fccc80-fd81-11ea-9e8b-aa7f4ef7e25a.png">

Working now.

**Comment by erictraut** [comment]
If you can find a pattern to the failure, let us know.
