### ISSUE TITLE
Issues when moving symbol to a different file 

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#4002]
## Environment data

-   Language Server version: v2023.2.41
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2, venv 

## Code Snippet

```python
import random


answer_word = random.choice(["a","b","c","d"])
guess_word = "c"

#this function doesn't do much
def myfunc(a, b):
    return a+b

```

## Repro Steps

There are two problems when I tried to move two different symbols in this sample:

1. Click on `answer_word` and select the "move symbol to a new file" code action
2. See that the symbol right below (`guess_word`) will also be moved, but without the `= "c"` bit:

The second problem:
1. Click on the `myfunc` function and select the "move symbol to a new file" code action 
2. The comment itself will move with it to the new file, but the `#` will be left behind 

![MoveFileBug](https://user-images.githubusercontent.com/45497113/221063410-6cd1001b-28db-45d6-9d33-3d99f018cdef.gif)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.2.43, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023243-24-February-2023-PreRelease)
