### ISSUE TITLE
Warning doesn't say which file

### ISSUE THREAD

**Issue by parched** [microsoft/pylance-release#4003]
I got a notification that said
> extension-output-ms-python.python-#3-Python Language Server: tokenization, wrapping and folding have been turned off for this large file in order to reduce memory usage and avoid freezing or crashing.

It would be helpful if it said which file it was, so I could investigate the problem as I don't believe any of the files I have open are particularly large.

I guess this might actually be a Pylance issue, but the message says this extension.

**Comment by debonte** [comment]
That output comes from [vscode](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/codeEditor/browser/largeFileOptimizations.ts#L47). It outputs this when a text file hits one of the following two [thresholds](https://github.com/microsoft/vscode/blob/02fa5bc9806b17d2e6a4994cae7c24e5161c9e9f/src/vs/editor/common/model/textModel.ts#L177):
```typescript
private static readonly LARGE_FILE_SIZE_THRESHOLD = 20 * 1024 * 1024; // 20 MB;
private static readonly LARGE_FILE_LINE_COUNT_THRESHOLD = 300 * 1000; // 300K lines
```

The text before the colon is the file name: `extension-output-ms-python.python-#3-Python Language Server`

I haven't personally noticed this before. But I suppose if you've using Pylance in this VS Code session for a long time, this would be expected. If you think there's something strange going on with Pylance, could you share the log?

**Comment by parched** [comment]
Ok that makes sense now. The notification popped up around when I open the Python Language Server output.

The reason it would have been so big is because I put `"versbose": true` in my `pyrightconfig.json` files to try and figure out why I'm Pylance is crashing sporadically due to running out of memory.

Feel free to close then @debonte.
