### ISSUE TITLE
"Match case" or "if" statements do not recognize Literal types

### ISSUE THREAD

**Issue by ksamarin90** [microsoft/pylance-release#4005]
There is no warning for using wrong literal type and no suggestion for autocomplete:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/60395970/221130001-3a70efe2-e5e6-41a6-9439-17b7d1dac4de.png">
<img width="449" alt="Screenshot 2023-02-24 at 12 19 03" src="https://user-images.githubusercontent.com/60395970/221127968-a6e6df18-e862-45ca-9569-2eb270b650f8.png">
<img width="640" alt="Screenshot 2023-02-24 at 12 20 04" src="https://user-images.githubusercontent.com/60395970/221128162-6e850fb8-5932-4f9b-bbfe-e6c8e48bad0c.png">

In Typescript, for instance, there is such functionality:
<img width="825" alt="Screenshot 2023-02-24 at 12 21 39" src="https://user-images.githubusercontent.com/60395970/221128483-b6dcf8a3-c573-4eb2-886a-2b8f903a414f.png">
<img width="581" alt="Screenshot 2023-02-24 at 12 21 50" src="https://user-images.githubusercontent.com/60395970/221128522-f4cde147-3ae6-40ea-bbc2-fa715e7ee918.png">
<img width="749" alt="Screenshot 2023-02-24 at 12 22 08" src="https://user-images.githubusercontent.com/60395970/221128597-188119a9-d37a-49e3-9ae6-e3c1a57f02d6.png">

Is it expected behaviour? Wouldn't it be better to provide such functionality if type is unequivocal?

**Comment by erictraut** [comment]
You're asking about several independent issues here. Let's enumerate these so they don't get lost.
1. `if` statements where the conditional is known to be always true or false
2. `match` statements where the `case` is known to never be matched
3. Completion suggestions for string literal values used in `==` and `!=` comparisons where one operand is an expression whose type is a union that includes only string literals
4. Completion suggestions for `case` string literal patterns where the narrowed subject type is a union that includes only string literals

Pylance is a language server that's built on top of pyright, a type checker. Pyright would be responsible for 1 and 2, whereas pylance would be responsible for 3 and 4.

Pyright already implements item 1 through an optional diagnostic check called `reportUnnecessaryComparison`. It's disabled by default, but you can enable it in your settings using `python.analysis.diagnosticSeverityOverrides`. For a full description of all diagnostic rules provided by pyright, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

Pyright does not currently implement 2, but I think it's a reasonable idea to do so. I've filed [this enhancement request](https://github.com/microsoft/pyright/issues/4689) in the pyright issue tracker. It does implement another check that would have caught the bug in your code above: `reportMatchNotExhaustive`.

Items 3 and 4 are enhancement requests for pylance's completion suggestion logic, and they'd need to be considered and prioritized by the pylance team.

**Comment by erictraut** [comment]
I've added support for item 2 in pyright. This functionality will be included in a future release of pylance.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023321-8-March-2023-PreRelease)
