### ISSUE TITLE
Pylance cannot detect attributes from implicitly imported modules

### ISSUE THREAD

**Issue by PythonCoderAS** [microsoft/pylance-release#4014]
Type: <b>Bug</b>

The open-source library `pywikibot` contains files with types such as this:

```python
NAMESPACE_OR_INT_TYPE = Union[int, 'pywikibot.site.Namespace']
```

There is an `import pywikibot` in the code, but no direct `import pywikibot.site` (`pywikibot.site` is a module). `pywikibot.site` is available at runtime in the module due to other modules that are part of pywikibot calling `import pywikibot.site` but for some reason Pylance cannot pick up on the types and reports the earlier types as `Type[int] | Any` without me adding an `import pywikibot.site` to the file and reporting `Type[int] | Type[Namespace]` once I do add the import. While this is understandble when editing the actual library, it's a much bigger issue in any other code that uses this library as an import, because in that case the type shows up as `Type[int] | Unknown` and causes all sorts of errors. I think either Pylance should be able to read types like these or at the very least fall back to `Any` instead of `Unknown`.

Extension version: 2023.2.40
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 2b0708f4-d206-4f56-bb5c-21ca647cc418|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30662444
pythonb192:30669360

```

</details>

**Comment by erictraut** [comment]
The Python module loader does not automatically load submodules. If you want to access submodules, you must either import them explicitly (as in `import pywikibot.site`) or the top-level module must explicitly import the submodule and re-export its name as part of its module namespace.

In the case of pywiki's `__init__.py` file, it is not explicitly importing and re-exporting the `site` submodule. If you are able to access it at runtime, then you're getting lucky. Perhaps some other submodule is implicitly referencing it, so it happens to get loaded and initialized. Your code should not rely on this behavior. Instead, you should explicitly import the submodule in your code.

**Comment by PythonCoderAS** [comment]
"Perhaps some other submodule is implicitly referencing it"

This is exactly what is going on. The structure of the library has led to many weird bugs if an exception is thrown during an import in a REPL and the library is re-imported.
