### ISSUE TITLE
Implement detection for local-object pickling 

### ISSUE THREAD

**Issue by AgFlore** [microsoft/pylance-release#4017]
## Environment data

-   Language Server version: 2023.2.40
-   OS and version: Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Code Snippet

```python
import pickle

def a():
    def b(c, d):
        return c * d

    with open('a.pkl', 'wb') as f:
        pickle.dump(b, f)

if __name__ == '__main__':
    a()
```
which returns an `AttributeError: Can't pickle local object 'a.<locals>.b'`, unwarned by pylance.

Further for built-in libraries like `multiprocessing` that uses `pickle`:
```python
import multiprocessing as mp

def a():
    def b(c, d):
        return c * d

    with mp.Pool() as pool:
        pool.starmap(b, [(1, 2), (3, 4)])

if __name__ == '__main__':
    a()
```
identifying such cases is also appreciated.

**Comment by erictraut** [comment]
Pylance is built on pyright, a static type checker. This isn't the sort of error that a static type checker would normally check for. You might want to look for other tools, like linters (perhaps pylint?) that have intimate knowledge of pickling rules and limitations.
