### ISSUE TITLE
incomplete movement expression while Refactor -> Move symbol to

### ISSUE THREAD

**Issue by evgenii-moriakhin** [microsoft/pylance-release#4018]
<h3> Environment data </h3>

-   Language Server version: (current Pre-release)
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda):  Python 3.8.13 in Pipenv env
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>
here is simple example (but it's critical for large expressions, which cannot be formatted on single line ):

```
sum1_2 = partial(sum, 
[1, 
2]
)
```

<h3> Repro Steps </h3>

right click to sum1_2 > Refactor > Move symbol to... > <some_file>.py

<h3> Expected behavior </h3>

whole expression moves to <some_file>.py

<h3> Actual behavior </h3>
moves only 

`sum1_2 = partial(sum,`

```
[1, 
2]
)
```
stays in the origin file

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.3.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023311-1-March-2023-PreRelease)
