### ISSUE TITLE
No error when to exist the variables not to be defined in class

### ISSUE THREAD

**Issue by tnakaicode** [microsoft/pylance-release#4023]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

In following code, the variable Child.v0 is not defined, so vscode should show warnning about the existing the variables not to be defined.
This issue will only become apparent at run time.

```
class Parent:

    def __init__(self, va=1, vb=2, vc=3):
        self.v0 = 0
        self.ChildA = Child(v1=va)
        self.ChildB = Child(v1=vb)
        self.ChildC = Child(v1=vc)

    def ParentMethod(self):
        self.ChildA.ChildMethod()
        self.ChildB.ChildMethod()
        self.ChildC.ChildMethod()
        print(self.ChildA.v1, self.ChildB.v1, self.ChildC.v1)


class Child:

    def __init__(self, v1=1):
        self.v1 = v1

    def ChildMethod(self):
        self.v1 += self.v0


if __name__ == '__main__':
    parent1 = Parent(va=1, vb=2, vc=3)
    parent1.ParentMethod()
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"


```

</p>
</details>

Extension version: 2023.2.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

</details>

**Comment by erictraut** [comment]
Pylance does emit an error for this condition if you enable type checking. To do so, set `python.analysis.typeCheckingMode` to "basic". I suspect that you currently have it set to "off", in which case such errors will be suppressed.

**Comment by tnakaicode** [comment]
I set "python.analysis.typeCheckingMode" to basic (and strict), but I cannot not solve this issue.
The variables that are not internal of Class are warned, but variables within Class are not warned.

**Comment by erictraut** [comment]
You should see a red squiggle under the `v0` in `ChildMethod`.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/7040122/222080397-303554c8-a7ac-4400-9466-940ad5d147ef.png">

Is this different from what you're seeing?

**Comment by tnakaicode** [comment]
I solved. Workspace' setting activated.
Thank you.
