### ISSUE TITLE
Migration path for open-source vscode users?

### ISSUE THREAD

**Issue by JacobHenner** [microsoft/pylance-release#403]
According to the [Pylance release announcement](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/#the-future-of-the-microsoft-python-language-server):

> Our long-term plan is to transition our Microsoft Python Language Server users over to Pylance and eventually deprecate and remove the old language server as a supported option.

While this seems reasonable at first, it leaves open-source VS Code users high and dry. Pylance is not open source, [it does not run in open source distributions of VS Code](https://github.com/microsoft/pylance-release/issues/50), and [it does not seem](https://github.com/microsoft/pylance-release/issues/4) like it's expected to be open-sourced any time soon. 

What are open-source VS Code users to do?

While I'd certainly like to see Pylance open sourced, I'd hope MSFT would at least support the Microsoft Python Language Server until a true alternative was available.

**Comment by savannahostrowski** [comment]
Hey @JacobHenner!

We have no plans to open-source Pylance at this time. You are still able to use the Microsoft Python Language Server or Jedi as open-source options as a language server in VSCode. Alternatively, you might also find that installing Pyright suits your needs. It's open-source and includes a large subset of Pylance functionality.
