### ISSUE TITLE
incorrect red squiggles from mypy on submodule look ups on alias modules 

### ISSUE THREAD

**Issue by jmhodges** [microsoft/pylance-release#4037]
## Environment data

-   Language Server version: 2023.3.10
-   OS and version: macOS 13.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2 and 3.8.16

## Code Snippet

```python
import libcst as cst
from libcst.codemod import VisitorBasedCodemodCommand

_ = VisitorBasedCodemodCommand
_ = cst.codemod.SkipFile
```

## Repro Steps

I strong suspect this is not specific to libcst, but I'm, unfortunately, hitting a timebox on reproducing this. Thanks for your patience with me.

1. `pip install libcst==0.4.9` into your virtualenv
2. Open a file with the above contents.
3. Turn on type checking

## Expected behavior

No red squiggles on the `cst.codemod.SkipFile` line.

## Actual behavior

The `codemod` in `cst.codemod.SkipFile` will have red squiggles and error saying:

```
"codemod" is not a known member of modulePylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

However, this code will execute just fine.

## Logs

```
Experiment 'pythonSurveyNotification' is active
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
VS Code was launched from an activated environment: '.venv', selecting it as the interpreter for workspace.
Python interpreter path: ./.venv/bin/python
Starting Pylance language server.
> conda info --json
> . ./.venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/printEnvVariables.py
> . ./.venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/printEnvVariables.py
> . ./.venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/printEnvVariables.py
> ./.venv/bin/python -I ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 -I ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/interpreterInfo.py
> /opt/homebrew/bin/python3 -I ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/interpreterInfo.py
> /opt/homebrew/bin/python3.10 -I ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2023.4.0/pythonFiles/interpreterInfo.py
```

(The Logs section says to only include the output from Python, but I'd be happy to include the Python Language Server output as well, if requested)

**Comment by rchiodo** [comment]
Thanks for the issue.

I believe this is expected because the `__init__.py` for `libcst` has an `__all__` export. The `__all__` export is defining the public interface to `libcst` and it doesn't include the codemod module. 

See this for more information:
https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface

I think an alternative would be to reference that module directly and not from the base:

```python
import libcst as cst
import libcst.codemod as codemod
from libcst.codemod import VisitorBasedCodemodCommand

_ = VisitorBasedCodemodCommand
_ = codemod.SkipFile
```

**Comment by erictraut** [comment]
Yes, @rchiodo is correct. The `libcst` top-level module does not import or re-export the symbol `codemod`. If you want to reference this submodule or symbols within it, you need to do so explicitly within your code.

```python
import libcst as cst
from libcst.codemod import VisitorBasedCodemodCommand, SkipFile

_ = VisitorBasedCodemodCommand
_ = SkipFile
```

or

```python
import libcst as cst
import libcst.codemod
from libcst.codemod import VisitorBasedCodemodCommand

_ = VisitorBasedCodemodCommand
_ = libcst.codemod.SkipFile```

**Comment by jmhodges** [comment]
Thank you for your help!
