### ISSUE TITLE
Type checking of decorator keyword arguments

### ISSUE THREAD

**Issue by malcolmsailor** [microsoft/pylance-release#4043]
## Environment data

-   Language Server version: PyLance v2023.3.11
-   OS and version: MacOs 12.5
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9

## Code Snippet

```python
from functools import wraps
from typing import Callable, TypeVar

from typing_extensions import Concatenate, ParamSpec

_P = ParamSpec("_P")
_T = TypeVar("_T")


def decorator(f: Callable[_P, _T]) -> Callable[Concatenate[str, _P], _T]:
    @wraps(f)
    def wrapper(foo: str = "foo", *args: _P.args, **kwargs: _P.kwargs):
        print(foo)
        return f(*args, **kwargs)

    return wrapper


@decorator
def f():
    pass


f()
f(foo="bar")
```

## Expected behavior

I am not 100% certain that my code is correct, but it runs as I would expect in Python, giving the following output:

```
foo
bar
```

Therefore I would expect VSCode to recognize that the decorated function `f` has no positional arguments and can be called either with no arguments or with the keyword argument "foo".

## Actual behavior

Pylance reports type errors for both invocations of `f`:

<img width="149" alt="Screen Shot 2023-03-04 at 9 43 00 AM" src="https://user-images.githubusercontent.com/28103673/222920808-b7db291a-8cfb-42bc-8173-def9832fdb6f.png">

In both cases, it says `expected 1 more positional argument`.

## Logs

```
[Info  - 9:36:15 AM] (73590) Pylance language server 2023.3.11 (pyright 93a4ef87) starting
[Info  - 9:36:15 AM] (73590) Server root directory: /Users/malcolm/.vscode/extensions/ms-python.vscode-pylance-2023.3.11/dist
[Info  - 9:36:16 AM] (73590) Starting service instance "tmp"
[Info  - 9:36:16 AM] (73590) Auto-indent enabled
[Info  - 9:36:16 AM] (73590) Starting service instance "<default>"
[Info  - 9:36:16 AM] (73590) No configuration file found.
[Info  - 9:36:16 AM] (73590) No pyproject.toml file found.
[Info  - 9:36:16 AM] (73590) Setting pythonPath for service "tmp": "/opt/homebrew/bin/python3"
[Error - 9:36:16 AM] (73590) venvPath /Volumes/Frescobaldi/venvs is not a valid directory.
[Warn  - 9:36:16 AM] (73590) stubPath /Users/malcolm/tmp/typings is not a valid directory.
[Info  - 9:36:16 AM] (73590) Assuming Python version 3.10
[Info  - 9:36:16 AM] (73590) Assuming Python platform Darwin
[Info  - 9:36:16 AM] (73590) Search paths for /Users/malcolm/tmp
[Info  - 9:36:16 AM] (73590)   /Users/malcolm/.vscode/extensions/ms-python.vscode-pylance-2023.3.11/dist/typeshed-fallback/stdlib
...
```

[I first included the complete logs here but got a "Comment is too long" error from Github.]

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is doing the correct thing here. You've annotated the `decorator` function to return the type `Callable[Concatenate[str, _P], _T]` which means that it requires one positional parameter of type `str` followed by zero or more positional/keyword arguments as captured by the ParamSpec. In your usage of `f()` and `f(foo="bar")`, you have not supplied the requisite `str` positional parameter.

The problem is that `Callable` isn't flexible enough to specify parameters with default values. To express this, you need to use a "callback protocol" as defined in [PEP 544](https://peps.python.org/pep-0544/#callback-protocols).

Here's what that might look like:

```python
from functools import wraps
from typing import Callable, Protocol, TypeVar, ParamSpec, cast

_P = ParamSpec("_P")
_T = TypeVar("_T", covariant=True)

class AddOptionalStr(Protocol[_P, _T]):
    def __call__(self, foo: str = "foo", *args: _P.args, **kwargs: _P.kwargs):
        ...

def decorator(f: Callable[_P, _T]) -> AddOptionalStr[_P, _T]:
    @wraps(f)
    def wrapper(foo: str = "foo", *args: _P.args, **kwargs: _P.kwargs):
        print(foo)
        return f(*args, **kwargs)

    return cast(AddOptionalStr[_P, _T], wrapper)

@decorator
def f():
    pass

f()
f(foo="bar")
```

**Comment by malcolmsailor** [comment]
Thank you for taking the time to explain that to me, and provide me with that example! Looks like I will have a little more reading to do to fully understand all this. Cheers!
