### ISSUE TITLE
`Concatenate` does not work with `TypeVarTuple`.

### ISSUE THREAD

**Issue by HolonProduction** [microsoft/pylance-release#4046]
## Environment data

-   Language Server version: 2023.3.10 (pyright 773a7cde)
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 11

## Code Snippet

This works:
```python
from typing import Callable, ParamSpec, TypeVar, Concatenate, TypeVarTuple, Unpack


P = ParamSpec("P")
R = TypeVar("R")

T = TypeVarTuple("T")
T1 = TypeVar("T1")

def bind_front(
    parameter: T1,
) -> Callable[[Callable[Concatenate[T1, P], R]], Callable[P, R]]:
    def decorator(func: Callable[Concatenate[T1, P], R]) -> Callable[P, R]:
        def inner(*args: P.args, **kwargs: P.kwargs) -> R:
            return func(parameter, *args, **kwargs)

        return inner

    return decorator


@bind_front(1)
def add(a: int, b: int) -> int:
    return a + b


if __name__ == "__main__":
    print(add(2))
```
This does not:
```python
from typing import Callable, ParamSpec, TypeVar, Concatenate, TypeVarTuple, Unpack


P = ParamSpec("P")
R = TypeVar("R")

T = TypeVarTuple("T")
T1 = TypeVar("T1")


def bind_front(
    *parameter: Unpack[T],
) -> Callable[[Callable[Concatenate[Unpack[T], P], R]], Callable[P, R]]:
    def decorator(func: Callable[Concatenate[Unpack[T], P], R]) -> Callable[P, R]:
        def inner(*args: P.args, **kwargs: P.kwargs) -> R:
            return func(*parameter, *args, **kwargs) # Expected 1 positional argument

        return inner

    return decorator


@bind_front(1)
# Argument of type "(a: int, b: int) -> int" cannot be assigned to parameter of type "(*tuple[int], **P@bind_front) -> R@bind_front"
#  Type "(a: int, b: int) -> int" cannot be assigned to type "(*tuple[int], **P@bind_front) -> R@bind_front"
#    Parameter 1: type "*tuple[int]" cannot be assigned to type "int"
#      "*tuple[int]" is incompatible with "int"
def add(a: int, b: int) -> int:
    return a + b


if __name__ == "__main__":
    print(add(2))
```

## Expected behavior

The second example should work without errors.

## Actual behavior

Pylance displays the errors shown in the comments.

**Comment by erictraut** [comment]
You cannot use `Concatenate` with `TypeVarTuple` as you are doing in this code sample. Both a `TypeVarTuple` and a `ParamSpec` capture an arbitrary number of parameters. If you use them together as you have done here, it wouldn't be possible for a type checker to determine which parameters should be captured by `TypeVarTuple` and which should be captured by `ParamSpec`. You can use `TypeVarTuple` or `ParamSpec`, but it doesn't make sense to combine the two with `Concatenate`.

**Comment by erictraut** [comment]
I've added a check and corresponding error message for this condition. This will be included in an upcoming version of pylance.

**Comment by HolonProduction** [comment]
> Both a `TypeVarTuple` and a `ParamSpec` capture an arbitrary number of parameters. If you use them together as you have done here, it wouldn't be possible for a type checker to determine which parameters should be captured by `TypeVarTuple` and which should be captured by `ParamSpec`.

As far as I understand it, this would only apply without the wrapping `bind_front` function. In my example the `TypeVarTuple` has already captured the parameters that were passed to `bind_front`, so when it is used inside of the `Concatenate` it does not capture anything. Instead it should insert what was already captured and behave more like a `Tuple`.

To check this assumption I replaced the `TypeVarTuple` with a constant tuple. And it does not work either. I guess, that `Concetanate` has a problem with `Unpack`.

```python
from typing import Callable, ParamSpec, TypeVar, Concatenate, Unpack, Tuple


P = ParamSpec("P")
R = TypeVar("R")


A = 1
B = 2

def decorator(func: Callable[Concatenate[Unpack[Tuple[int, int]], P], R]) -> Callable[P, R]:
    def inner(*args: P.args, **kwargs: P.kwargs) -> R:
         return func(A, B, *args, **kwargs) # Expected 1 positional argument

    return inner

#Argument of type "(a: int, b: int) -> int" cannot be assigned to parameter "func" of type "(*Tuple[int, int], **P@decorator) -> R@decorator" in function "decorator"
#  Type "(a: int, b: int) -> int" cannot be assigned to type "(*Tuple[int, int], **P@decorator) -> R@decorator"
#    Parameter 1: type "*Tuple[int, int]" cannot be assigned to type "int"
#      "*Tuple[int, int]" is incompatible with "int"
@decorator
def add(a: int, b: int) -> int:
    return a + b


if __name__ == "__main__":
    print(add()) # Argument missing for parameter "b"
```
