### ISSUE TITLE
Argument of type "tuple[Literal['foo'], bool]" cannot be assigned to parameter "__key" of type "tuple[Literal['foo'], Literal[False]] | tuple[Literal['foo'], Literal[True]]" in function "__getitem__"

### ISSUE THREAD

**Issue by FallenKhadgar** [microsoft/pylance-release#4047]
## Environment data

- Pylance language server 2023.3.11 (pyright 93a4ef87)
- VS Code 1.75.1
- Python 3.10.10
- Ubuntu 22.04.1 LTS

## Code Snippet

```python
def f(s:typing.Literal['foo'], b:bool):
    # b = True   # uncommenting this line fixes the issue
    return {
        ('foo', False): {},
        ('foo', True): {},
    }[(s, b)]
```

## Expected behavior

No warning.

## Actual behavior

```
Argument of type "tuple[Literal['foo'], bool]" cannot be assigned to parameter "__key" of type "tuple[Literal['foo'], Literal[False]] | tuple[Literal['foo'], Literal[True]]" in function "__getitem__"
  Type "tuple[Literal['foo'], bool]" cannot be assigned to type "tuple[Literal['foo'], Literal[False]] | tuple[Literal['foo'], Literal[True]]"
    "tuple[Literal['foo'], bool]" is incompatible with "tuple[Literal['foo'], Literal[False]]"
      Tuple entry 2 is incorrect type
        "bool" cannot be assigned to type "Literal[False]"
    "tuple[Literal['foo'], bool]" is incompatible with "tuple[Literal['foo'], Literal[True]]"
      Tuple entry 2 is incorrect type
        "bool" cannot be assigned to type "Literal[True]"  Pylance(reportGeneralTypeIssues)
```

## Works

```Python
def f2(s:str):
    return {
        ('foo'): {},
        ('bar'): {},
    }[(s)]

def f3(b:bool):
    return {
        (False): {},
        (True): {},
    }[(b)]
```

**Comment by erictraut** [comment]
This behavior is "as designed", not a bug. For more information about type inference for tuples, refer to [this documentation](https://github.com/microsoft/pyright/blob/main/docs/type-inference.md#tuple-expressions).

If you don't want to see type-related errors in your code, you can disable type checking using `python.analysis.typeCheckingMode` to "off".

If you wan to leave type checking enabled, you can use a type declaration to override the default type inference rules. Something like this...

```python
    x: dict[tuple[Literal["foo"], bool], dict] = {
        ("foo", False): {},
        ("foo", True): {},
    }

    return x[(s, b)]
```

**Comment by FallenKhadgar** [comment]
Thanks. Unfortunately the code has many different values, not just 'foo'.

**Comment by erictraut** [comment]
You can use `dict[tuple[str, bool], dict]` if you don't want to restrict the first tuple entry to a particular set of literals.

**Comment by heejaechang** [comment]
for `bool` case, since it has limited value set "True" and "False", we could be `dict` has all possible values in the key? might be too complex to track when expression becomes too complex, but single case, we might be able to? not sure whether it is worth it though.

**Comment by heejaechang** [comment]
or it could infer type to `tuple[Literal['foo'], bool] | tuple[Literal['foo'], bool]` since it sees all possible value of `bool` is used?
