### ISSUE TITLE
Autocomplete provides incorrect name for select_dtypes method of pandas

### ISSUE THREAD

**Issue by saurabh-c-rai** [microsoft/pylance-release#405]
Issue Type: <b>Bug</b>

1. Create a dataframe df.
2. using dot notation check the name of the option provided for select_dtypes method
Eg. df = pd.read_csv(....)
Try to find autocomplete for select_dtypes method
![image](https://user-images.githubusercontent.com/47693029/94050565-0ec72080-fdf4-11ea-991d-c2d2d2c6e44d.png)

Extension version: 2020.9.5
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.17GB free)|
|Process Argv|--crash-reporter-id c5cdd6d1-5f58-4ecc-a12e-42f7f1593127|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gramster** [comment]
Interesting; I believe selectDTypes came from the Pandas source so there may be some munging that pandas does. I'll fix this in the stubs though. Thanks for reporting!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.7, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202097-30-september-2020
