### ISSUE TITLE
PyQt5 not linked to my Visual Studio 

### ISSUE THREAD

**Issue by kharo019** [microsoft/pylance-release#4064]
## Environment data

-   Language Server version: Pylance v2023.3.20
-   OS and version:  MacOS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2

## Code Snippet
Traceback (most recent call last):
  File "/Users/kharo019/Documents/CS/CS448/test/main.py", line 3, in <module>
    from PyQt5 import *
    ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PyQt5'

```python
XXX
```

## Repro Steps

1. To build a website IDE using PyQt5 and Qscintilla

## Expected behavior

Failed to import the PyQt5 libraries 

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by kharo019** [comment]
[Info  - 4:54:13 PM] (41135) Pylance language server 2023.3.20 (pyright 93a4ef87) starting
[Info  - 4:54:13 PM] (41135) Server root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist
[Info  - 4:54:13 PM] (41135) Starting service instance "Documents"
[Info  - 4:54:13 PM] (41135) Auto-indent enabled
[Info  - 4:54:13 PM] (41135) Starting service instance "<default>"
[Info  - 4:54:13 PM] (41135) No pyproject.toml file found.
[Info  - 4:54:13 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 4:54:13 PM] (41135) stubPath typings is not a valid directory.
[Info  - 4:54:13 PM] (41135) Assuming Python version 3.11
[Info  - 4:54:13 PM] (41135) Assuming Python platform Darwin
[Info  - 4:54:13 PM] (41135) Searching for source files
[Info  - 4:54:13 PM] (41135) No source files found.
[Info  - 4:54:13 PM] (41135) No configuration file found.
[Info  - 4:54:13 PM] (41135) No pyproject.toml file found.
[Info  - 4:54:13 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 4:54:13 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 4:54:13 PM] (41135) Assuming Python version 3.11
[Info  - 4:54:13 PM] (41135) Assuming Python platform Darwin
[Info  - 4:54:13 PM] (41135) Searching for source files
[Info  - 4:54:13 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 4:54:13 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 4:54:13 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 4:54:13 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 4:54:13 PM] (41135) Found 33 source files
[Info  - 4:54:13 PM] (41135) Background analysis(1) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist
[Info  - 4:54:13 PM] (41135) Background analysis(1) started
[Info  - 4:54:13 PM] (41135) No pyproject.toml file found.
[Info  - 4:54:13 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 4:54:13 PM] (41135) stubPath typings is not a valid directory.
[Info  - 4:54:13 PM] (41135) Assuming Python version 3.11
[Info  - 4:54:13 PM] (41135) Assuming Python platform Darwin
[Info  - 4:54:13 PM] (41135) Searching for source files
[Info  - 4:54:13 PM] (41135) No source files found.
[Info  - 4:54:13 PM] (41135) Background analysis(2) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist
[Info  - 4:54:13 PM] (41135) Background analysis(2) started
[Info  - 4:54:13 PM] (41135) Indexer background runner(3) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 4:54:13 PM] (41135) Indexing(3) started
[Info  - 4:54:14 PM] (41135) scanned(3) 34 files over 1 exec env
[Info  - 4:54:14 PM] (41135) indexed(3) 17 files over 1 exec env
[Info  - 4:54:14 PM] (41135) Indexing finished(3).
[Info  - 4:54:55 PM] (41135) No configuration file found.
[Info  - 4:54:55 PM] (41135) No pyproject.toml file found.
[Info  - 4:54:55 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 4:54:55 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 4:54:55 PM] (41135) Assuming Python version 3.11
[Info  - 4:54:55 PM] (41135) Assuming Python platform Darwin
[Info  - 4:54:55 PM] (41135) Searching for source files
[Info  - 4:54:55 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 4:54:55 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 4:54:55 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 4:54:55 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 4:54:55 PM] (41135) Found 33 source files
[Info  - 4:54:55 PM] (41135) No pyproject.toml file found.
[Info  - 4:54:55 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 4:54:55 PM] (41135) stubPath typings is not a valid directory.
[Info  - 4:54:55 PM] (41135) Assuming Python version 3.11
[Info  - 4:54:55 PM] (41135) Assuming Python platform Darwin
[Info  - 4:54:55 PM] (41135) Searching for source files
[Info  - 4:54:55 PM] (41135) No source files found.
[Info  - 4:54:55 PM] (41135) Indexer background runner(4) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 4:54:55 PM] (41135) Indexing(4) started
[Info  - 4:54:55 PM] (41135) scanned(4) 16 files over 1 exec env
[Info  - 4:54:55 PM] (41135) indexed(4) 4 files over 1 exec env
[Info  - 4:54:55 PM] (41135) Indexing finished(4).
[Info  - 4:55:06 PM] (41135) No configuration file found.
[Info  - 4:55:06 PM] (41135) No pyproject.toml file found.
[Info  - 4:55:06 PM] (41135) Setting pythonPath for service "Documents": "/opt/homebrew/bin/python3"
[Warn  - 4:55:06 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 4:55:06 PM] (41135) Assuming Python version 3.11
[Info  - 4:55:06 PM] (41135) Assuming Python platform Darwin
[Info  - 4:55:06 PM] (41135) Searching for source files
[Info  - 4:55:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 4:55:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 4:55:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 4:55:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 4:55:06 PM] (41135) Found 33 source files
[Info  - 4:55:06 PM] (41135) No pyproject.toml file found.
[Info  - 4:55:06 PM] (41135) Setting pythonPath for service "<default>": "/opt/homebrew/bin/python3"
[Warn  - 4:55:06 PM] (41135) stubPath typings is not a valid directory.
[Info  - 4:55:06 PM] (41135) Assuming Python version 3.11
[Info  - 4:55:06 PM] (41135) Assuming Python platform Darwin
[Info  - 4:55:06 PM] (41135) Searching for source files
[Info  - 4:55:06 PM] (41135) No source files found.
[Info  - 4:55:06 PM] (41135) Indexer background runner(5) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 4:55:06 PM] (41135) Indexing(5) started
[Info  - 4:55:06 PM] (41135) scanned(5) 27 files over 1 exec env
[Info  - 4:55:06 PM] (41135) indexed(5) 9 files over 1 exec env
[Info  - 4:55:06 PM] (41135) Indexing finished(5).
[Info  - 5:47:52 PM] (41135) Indexer background runner(6) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (refresh)
[Info  - 5:47:52 PM] (41135) Indexing(6) started
[Info  - 5:47:52 PM] (41135) scanned(6) 27 files over 1 exec env
[Info  - 5:47:52 PM] (41135) indexed(6) 9 files over 1 exec env
[Info  - 5:47:52 PM] (41135) Indexing finished(6).
[Info  - 5:53:39 PM] (41135) No configuration file found.
[Info  - 5:53:39 PM] (41135) No pyproject.toml file found.
[Info  - 5:53:39 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 5:53:39 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:53:39 PM] (41135) Assuming Python version 3.11
[Info  - 5:53:39 PM] (41135) Assuming Python platform Darwin
[Info  - 5:53:39 PM] (41135) Searching for source files
[Info  - 5:53:39 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:53:39 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:53:39 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:53:39 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:53:39 PM] (41135) Found 33 source files
[Info  - 5:53:39 PM] (41135) No pyproject.toml file found.
[Info  - 5:53:39 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 5:53:39 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:53:39 PM] (41135) Assuming Python version 3.11
[Info  - 5:53:39 PM] (41135) Assuming Python platform Darwin
[Info  - 5:53:39 PM] (41135) Searching for source files
[Info  - 5:53:39 PM] (41135) No source files found.
[Info  - 5:53:39 PM] (41135) Indexer background runner(7) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:53:39 PM] (41135) Indexing(7) started
[Info  - 5:53:39 PM] (41135) scanned(7) 34 files over 1 exec env
[Info  - 5:53:40 PM] (41135) indexed(7) 17 files over 1 exec env
[Info  - 5:53:40 PM] (41135) Indexing finished(7).
[Info  - 5:53:53 PM] (41135) No configuration file found.
[Info  - 5:53:53 PM] (41135) No pyproject.toml file found.
[Info  - 5:53:53 PM] (41135) Setting pythonPath for service "Documents": "/opt/homebrew/bin/python3.9"
[Warn  - 5:53:53 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:53:53 PM] (41135) Assuming Python version 3.9
[Info  - 5:53:53 PM] (41135) Assuming Python platform Darwin
[Info  - 5:53:53 PM] (41135) Searching for source files
[Info  - 5:53:53 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:53:53 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:53:53 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:53:53 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:53:53 PM] (41135) Found 33 source files
[Info  - 5:53:53 PM] (41135) No pyproject.toml file found.
[Info  - 5:53:53 PM] (41135) Setting pythonPath for service "<default>": "/opt/homebrew/bin/python3.9"
[Warn  - 5:53:53 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:53:53 PM] (41135) Assuming Python version 3.9
[Info  - 5:53:53 PM] (41135) Assuming Python platform Darwin
[Info  - 5:53:53 PM] (41135) Searching for source files
[Info  - 5:53:53 PM] (41135) No source files found.
[Info  - 5:53:53 PM] (41135) Indexer background runner(8) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:53:53 PM] (41135) Indexing(8) started
[Info  - 5:53:53 PM] (41135) scanned(8) 16 files over 1 exec env
[Info  - 5:53:53 PM] (41135) indexed(8) 4 files over 1 exec env
[Info  - 5:53:53 PM] (41135) Indexing finished(8).
[Info  - 5:53:57 PM] (41135) No configuration file found.
[Info  - 5:53:57 PM] (41135) No pyproject.toml file found.
[Info  - 5:53:57 PM] (41135) Setting pythonPath for service "Documents": "/opt/homebrew/bin/python3"
[Warn  - 5:53:57 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:53:57 PM] (41135) Assuming Python version 3.11
[Info  - 5:53:57 PM] (41135) Assuming Python platform Darwin
[Info  - 5:53:57 PM] (41135) Searching for source files
[Info  - 5:53:57 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:53:57 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:53:57 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:53:57 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:53:57 PM] (41135) Found 33 source files
[Info  - 5:53:57 PM] (41135) No pyproject.toml file found.
[Info  - 5:53:57 PM] (41135) Setting pythonPath for service "<default>": "/opt/homebrew/bin/python3"
[Warn  - 5:53:57 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:53:57 PM] (41135) Assuming Python version 3.11
[Info  - 5:53:57 PM] (41135) Assuming Python platform Darwin
[Info  - 5:53:57 PM] (41135) Searching for source files
[Info  - 5:53:57 PM] (41135) No source files found.
[Info  - 5:53:57 PM] (41135) Indexer background runner(9) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:53:57 PM] (41135) Indexing(9) started
[Info  - 5:53:57 PM] (41135) scanned(9) 27 files over 1 exec env
[Info  - 5:53:57 PM] (41135) indexed(9) 9 files over 1 exec env
[Info  - 5:53:57 PM] (41135) Indexing finished(9).
[Info  - 5:54:06 PM] (41135) No configuration file found.
[Info  - 5:54:06 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:06 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.10.10/bin/python"
[Warn  - 5:54:06 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:54:06 PM] (41135) Assuming Python version 3.10
[Info  - 5:54:06 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:06 PM] (41135) Searching for source files
[Info  - 5:54:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:54:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:54:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:54:06 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:54:06 PM] (41135) Found 33 source files
[Info  - 5:54:06 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:06 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.10.10/bin/python"
[Warn  - 5:54:06 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:54:06 PM] (41135) Assuming Python version 3.10
[Info  - 5:54:06 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:06 PM] (41135) Searching for source files
[Info  - 5:54:06 PM] (41135) No source files found.
[Info  - 5:54:06 PM] (41135) Indexer background runner(10) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:54:06 PM] (41135) Indexing(10) started
[Info  - 5:54:06 PM] (41135) scanned(10) 14 files over 1 exec env
[Info  - 5:54:07 PM] (41135) indexed(10) 4 files over 1 exec env
[Info  - 5:54:07 PM] (41135) Indexing finished(10).
[Info  - 5:54:12 PM] (41135) No configuration file found.
[Info  - 5:54:12 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:12 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 5:54:12 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:54:12 PM] (41135) Assuming Python version 3.11
[Info  - 5:54:12 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:12 PM] (41135) Searching for source files
[Info  - 5:54:12 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:54:12 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:54:12 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:54:12 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:54:12 PM] (41135) Found 33 source files
[Info  - 5:54:12 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:12 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 5:54:12 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:54:12 PM] (41135) Assuming Python version 3.11
[Info  - 5:54:12 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:12 PM] (41135) Searching for source files
[Info  - 5:54:12 PM] (41135) No source files found.
[Info  - 5:54:12 PM] (41135) Indexer background runner(11) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:54:12 PM] (41135) Indexing(11) started
[Info  - 5:54:12 PM] (41135) scanned(11) 34 files over 1 exec env
[Info  - 5:54:12 PM] (41135) indexed(11) 17 files over 1 exec env
[Info  - 5:54:12 PM] (41135) Indexing finished(11).
[Info  - 5:54:16 PM] (41135) No configuration file found.
[Info  - 5:54:16 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:16 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 5:54:16 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:54:16 PM] (41135) Assuming Python version 3.11
[Info  - 5:54:16 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:16 PM] (41135) Searching for source files
[Info  - 5:54:16 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:54:16 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:54:16 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:54:16 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:54:16 PM] (41135) Found 33 source files
[Info  - 5:54:16 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:16 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 5:54:16 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:54:16 PM] (41135) Assuming Python version 3.11
[Info  - 5:54:16 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:16 PM] (41135) Searching for source files
[Info  - 5:54:16 PM] (41135) No source files found.
[Info  - 5:54:16 PM] (41135) Indexer background runner(12) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:54:16 PM] (41135) Indexing(12) started
[Info  - 5:54:16 PM] (41135) scanned(12) 16 files over 1 exec env
[Info  - 5:54:17 PM] (41135) indexed(12) 4 files over 1 exec env
[Info  - 5:54:17 PM] (41135) Indexing finished(12).
[Info  - 5:54:19 PM] (41135) No configuration file found.
[Info  - 5:54:19 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:19 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 5:54:19 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 5:54:19 PM] (41135) Assuming Python version 3.11
[Info  - 5:54:19 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:19 PM] (41135) Searching for source files
[Info  - 5:54:19 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 5:54:19 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 5:54:19 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 5:54:19 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 5:54:19 PM] (41135) Found 33 source files
[Info  - 5:54:19 PM] (41135) No pyproject.toml file found.
[Info  - 5:54:19 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 5:54:19 PM] (41135) stubPath typings is not a valid directory.
[Info  - 5:54:19 PM] (41135) Assuming Python version 3.11
[Info  - 5:54:19 PM] (41135) Assuming Python platform Darwin
[Info  - 5:54:19 PM] (41135) Searching for source files
[Info  - 5:54:19 PM] (41135) No source files found.
[Info  - 5:54:19 PM] (41135) Indexer background runner(13) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 5:54:19 PM] (41135) Indexing(13) started
[Info  - 5:54:20 PM] (41135) scanned(13) 34 files over 1 exec env
[Info  - 5:54:20 PM] (41135) indexed(13) 17 files over 1 exec env
[Info  - 5:54:20 PM] (41135) Indexing finished(13).
[Info  - 6:08:50 PM] (41135) No configuration file found.
[Info  - 6:08:50 PM] (41135) No pyproject.toml file found.
[Info  - 6:08:50 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 6:08:50 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 6:08:50 PM] (41135) Assuming Python version 3.11
[Info  - 6:08:50 PM] (41135) Assuming Python platform Darwin
[Info  - 6:08:50 PM] (41135) Searching for source files
[Info  - 6:08:50 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 6:08:50 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 6:08:50 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 6:08:50 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 6:08:50 PM] (41135) Found 33 source files
[Info  - 6:08:50 PM] (41135) No pyproject.toml file found.
[Info  - 6:08:50 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 6:08:50 PM] (41135) stubPath typings is not a valid directory.
[Info  - 6:08:50 PM] (41135) Assuming Python version 3.11
[Info  - 6:08:50 PM] (41135) Assuming Python platform Darwin
[Info  - 6:08:50 PM] (41135) Searching for source files
[Info  - 6:08:50 PM] (41135) No source files found.
[Info  - 6:08:50 PM] (41135) Indexer background runner(14) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 6:08:50 PM] (41135) Indexing(14) started
[Info  - 6:08:50 PM] (41135) scanned(14) 16 files over 1 exec env
[Info  - 6:08:51 PM] (41135) indexed(14) 4 files over 1 exec env
[Info  - 6:08:51 PM] (41135) Indexing finished(14).
[Info  - 6:08:53 PM] (41135) No configuration file found.
[Info  - 6:08:53 PM] (41135) No pyproject.toml file found.
[Info  - 6:08:53 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 6:08:53 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 6:08:53 PM] (41135) Assuming Python version 3.11
[Info  - 6:08:53 PM] (41135) Assuming Python platform Darwin
[Info  - 6:08:53 PM] (41135) Searching for source files
[Info  - 6:08:54 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 6:08:54 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 6:08:54 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 6:08:54 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 6:08:54 PM] (41135) Found 33 source files
[Info  - 6:08:54 PM] (41135) No pyproject.toml file found.
[Info  - 6:08:54 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 6:08:54 PM] (41135) stubPath typings is not a valid directory.
[Info  - 6:08:54 PM] (41135) Assuming Python version 3.11
[Info  - 6:08:54 PM] (41135) Assuming Python platform Darwin
[Info  - 6:08:54 PM] (41135) Searching for source files
[Info  - 6:08:54 PM] (41135) No source files found.
[Info  - 6:08:54 PM] (41135) Indexer background runner(15) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 6:08:54 PM] (41135) Indexing(15) started
[Info  - 6:08:54 PM] (41135) scanned(15) 34 files over 1 exec env
[Info  - 6:08:54 PM] (41135) indexed(15) 17 files over 1 exec env
[Info  - 6:08:54 PM] (41135) Indexing finished(15).
[Info  - 6:09:04 PM] (41135) No configuration file found.
[Info  - 6:09:04 PM] (41135) No pyproject.toml file found.
[Info  - 6:09:04 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 6:09:04 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 6:09:04 PM] (41135) Assuming Python version 3.11
[Info  - 6:09:04 PM] (41135) Assuming Python platform Darwin
[Info  - 6:09:04 PM] (41135) Searching for source files
[Info  - 6:09:04 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 6:09:04 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 6:09:04 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 6:09:04 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 6:09:04 PM] (41135) Found 33 source files
[Info  - 6:09:04 PM] (41135) No pyproject.toml file found.
[Info  - 6:09:04 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.local/share/virtualenvs/AC-rLLUnJzF/bin/python"
[Warn  - 6:09:04 PM] (41135) stubPath typings is not a valid directory.
[Info  - 6:09:04 PM] (41135) Assuming Python version 3.11
[Info  - 6:09:04 PM] (41135) Assuming Python platform Darwin
[Info  - 6:09:04 PM] (41135) Searching for source files
[Info  - 6:09:04 PM] (41135) No source files found.
[Info  - 6:09:04 PM] (41135) Indexer background runner(16) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 6:09:04 PM] (41135) Indexing(16) started
[Info  - 6:09:05 PM] (41135) scanned(16) 16 files over 1 exec env
[Info  - 6:09:05 PM] (41135) indexed(16) 4 files over 1 exec env
[Info  - 6:09:05 PM] (41135) Indexing finished(16).
[Info  - 6:09:08 PM] (41135) No configuration file found.
[Info  - 6:09:08 PM] (41135) No pyproject.toml file found.
[Info  - 6:09:08 PM] (41135) Setting pythonPath for service "Documents": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 6:09:08 PM] (41135) stubPath /Users/kharo019/Documents/typings is not a valid directory.
[Info  - 6:09:08 PM] (41135) Assuming Python version 3.11
[Info  - 6:09:08 PM] (41135) Assuming Python platform Darwin
[Info  - 6:09:08 PM] (41135) Searching for source files
[Info  - 6:09:08 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/CS448/venv
[Info  - 6:09:08 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/beta/WillitWork
[Info  - 6:09:08 PM] (41135) Auto-excluding /Users/kharo019/Documents/CS/test/beta
[Info  - 6:09:08 PM] (41135) Auto-excluding /Users/kharo019/Documents/Test/env
[Info  - 6:09:08 PM] (41135) Found 33 source files
[Info  - 6:09:08 PM] (41135) No pyproject.toml file found.
[Info  - 6:09:08 PM] (41135) Setting pythonPath for service "<default>": "/Users/kharo019/.pyenv/versions/3.11.2/bin/python"
[Warn  - 6:09:08 PM] (41135) stubPath typings is not a valid directory.
[Info  - 6:09:08 PM] (41135) Assuming Python version 3.11
[Info  - 6:09:08 PM] (41135) Assuming Python platform Darwin
[Info  - 6:09:08 PM] (41135) Searching for source files
[Info  - 6:09:08 PM] (41135) No source files found.
[Info  - 6:09:08 PM] (41135) Indexer background runner(17) root directory: /Users/kharo019/.vscode/extensions/ms-python.vscode-pylance-2023.3.20/dist (index)
[Info  - 6:09:08 PM] (41135) Indexing(17) started
[Info  - 6:09:08 PM] (41135) scanned(17) 34 files over 1 exec env
[Info  - 6:09:08 PM] (41135) indexed(17) 17 files over 1 exec env
[Info  - 6:09:08 PM] (41135) Indexing finished(17).

**Comment by heejaechang** [comment]
did you set logLevel to "Trace"? the log has no detail.

**Comment by gramster** [comment]
This is not a pylance error; it is happening at runtime. The user has not installed PyQT or has not set their virtual environment correctly in the Python extension. Closing.
