### ISSUE TITLE
Return type of filter + isinstance is not properly understood

### ISSUE THREAD

**Issue by Meehai** [microsoft/pylance-release#4069]
## Environment data

-   Language Server version: v2023.3.20
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.13

## Code Snippet

```python
from typing import List, Dict
my_list: List[str | Dict[str, str]] = ["a", {"b": "c"}, "d", {"e": "f"}]
my_filtered_list: List[Dict[str, str]] = filter(lambda x: isinstance(x, dict), my_list)
```

This raises the pylance error:
```
Expression of type "list[str | Dict[str, str]]" cannot be assigned to declared type "List[Dict[str, str]]"
  "list[str | Dict[str, str]]" is incompatible with "List[Dict[str, str]]"
    TypeVar "_T@list" is invariant
      Type "str | Dict[str, str]" cannot be assigned to type "Dict[str, str]"
        "str" is incompatible with "Dict[str, str]"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by erictraut** [comment]
Pylance is working as designed here. The definition for `filter` is provided by the community-maintained typeshed stubs. You can see the type declaration by right-clicking on `filter` and choosing "Go To Declaration". It looks like this:

```python
class filter(Iterator[_T]):
    @overload
    def __init__(self, __function: Callable[[_S], TypeGuard[_T]], __iterable: Iterable[_S]) -> None: ...
    @overload
    def __init__(self, __function: Callable[[_T], Any], __iterable: Iterable[_T]) -> None: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> _T: ...
```

If you want this to work without typing errors, you could modify your code as follows:
```python
from typing import Iterable, TypeGuard


def my_filter(val: str | dict[str, str]) -> TypeGuard[dict[str, str]]:
    return isinstance(val, dict)

my_list: list[str | dict[str, str]] = ["a", {"b": "c"}, "d", {"e": "f"}]
my_filtered_list: Iterable[dict[str, str]] = filter(my_filter, my_list)
```

**Comment by Meehai** [comment]
I understand why it is like this. Even though `filter` is part of the language syntax, it's still a function under the hood.

From a usability point of view it kind of defeats the functional-style programming in python where you can do various inline expressions with anonymous functions if I have to create a special function just to provide the return type.
 
Shouldn't `filter` alongside `map` have special rules (as opposed to say `reduce` which requires `functools`) ?

It's just weird that this code is okay with pylance:
```
from typing import Union
import random

x: Union[int, str] = 1 if random.random() < 0.5 else "1"
assert isinstance(x, int)
y: int = x


```

while this is not:
```
from typing import Union, List
import random

x: List[Union[int, str]] = [1] if random.random() < 0.5 else ["1"]
# both below raise errors
y: List[int] = filter(lambda _x: isinstance(_x, int), x)
z: List[int] = map(lambda _x: 5, x)

```

**Comment by erictraut** [comment]
`filter` is just a class that is subject to the same type rules as all other classes, functions, and methods. It's not part of the language syntax.

If you find that type checking rules like this do not provide sufficient value for you, you can disable these checks by setting `python.analysis.typeCheckingMode` to "off".

**Comment by erictraut** [comment]
Glad to hear that you find it useful.

You may find that you need to adjust your coding style slightly to get the benefits of static type checks. This is such an example.
