### ISSUE TITLE
Highlighting of parameters is incorrect when using `*` with docstring

### ISSUE THREAD

**Issue by yuxqiu** [microsoft/pylance-release#4070]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

Without any extensions, the code looks like this:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/45459572/225050345-242d2947-cb5e-482d-beca-9b9ee6df047b.png">

With only Python extension enabled, the highlighted code looks like this:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/45459572/225157708-a485b4e1-08cd-4bdd-97d0-15648300d14f.png">

The color of the parameter name and type is incorrect.

## Steps to reproduce:

Use the following code snippet.

```python
class F:
    """This one cannot be empty.
    """

def f(
    *, strange_color_here: int
):
    """This docstring can be empty."""
```

Note: If you add more parameters to `f`, they will not be highlighted correctly either.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Jedi"

linting
• prospectorEnabled: true

formatting
• provider: "black"

testing
• pytestEnabled: true

experiments
• enabled: false

```

</p>
</details>

Extension version: 2023.4.1
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

**Comment by yuxqiu** [comment]
Is this really Pylance's fault? I should have mentioned that this happens even if I have `Python` enabled and `Pylance` disabled.

**Comment by erictraut** [comment]
From your screen shot, it looks like there is an error reported for the symbol `strange_color_here`. What error is being reported here? That's probably a clue to why the semantic highlighting isn't working the way you're expecting.

**Comment by yuxqiu** [comment]
The error occurs because this variable is not used. It is reported by the prospector (linter).

**Comment by yuxqiu** [comment]
The problem has been found. This seems to be caused by another plugin `Better Comments`. Maybe I should go notify them. Thanks for your help!
