### ISSUE TITLE
Problem completion with pylance

### ISSUE THREAD

**Issue by goupil35000** [microsoft/pylance-release#4072]
## Environment data
-   Language Server version: Pylance v2023.3.20
-   OS and version: Ubuntu 22.04.2 and WSL2 Ubuntu 22.04.2 -- each in a docker container
-   Python: 3.8.10

## Code Snippet

#!/usr/bin/env python

import rospy
from nav_msgs.msg import Odometry
import cv2

class RobotControl():

    def __init__(self):
        rospy.init_node('robot_control_node', anonymous=True)
        self.odom_sub = rospy.Subscriber ('/odom', Odometry, self.odom_callback)

    def odom_callback(self, msg):
        msg.pose.pose

## Expected behavior

When typing the first letters for msg.pose.pose, completion appears when pylance is not installed.

## Actual behavior

With pylance installed, no completion.

**Comment by goupil35000** [comment]
I forgot to list the extensions in my container (all last versions).
C/C++ Microsoft
Doxygen Documentation Generator Christoph Schlosser
IntelliCode Microsoft
IntelliCode API Usage examples Microsoft
isort Microsoft
Jupyter Microsoft
Python Microsoft
ROS Microsoft
----------

**Comment by theunknowninfinite** [comment]
I face the same issue also now.

**Comment by bschnurr** [comment]
I think you are missing a type annotation on `msg`
try swapping in a type for `XXX`

```python
def odom_callback(self, msg):
    msg.pose.pose
```

to

```python
def odom_callback(self, msg: XXX):
    msg.pose.pose
```
