### ISSUE TITLE
Variable "is not accessed" when using pandas query / eval

### ISSUE THREAD

**Issue by akanz1** [microsoft/pylance-release#408]
I keep getting a "is not accessed" message for variables used in the Pandas or DataFrame "query" and "eval" methods using @variable inside the string.

I.e. given a list "labels" and a column "label" in a DataFrame (X_train):

`X_train.query("label in @labels")`

gives me "'labels' is not accessed".

Pylance: v2020.9.6
Python 3.8.3 64bit
Windows

**Comment by jakebailey** [comment]
If I'm understanding it correctly, pandas has something where you can pass in a string containing `@<variable name>`, and it will somehow reach back into the caller's scope to read the variable.

I don't know how we could could support something like this; it totally defeats any analysis method as it's passing in variables without actually passing them in.

I think that if you want to hide the message, you might be able to disable the diagnostic via an override (https://github.com/microsoft/pylance-release/blob/master/DIAGNOSTIC_SEVERITY_RULES.md). But note that the diagnostics here are only intended to dim the code; it shouldn't cause any squiggles or anything.

**Comment by akanz1** [comment]
Exactly, upon evaluation of the string, the @ allows to access variables from the environment.

Thank you for getting back to me, your reply sums it up very well and clarifies this issue!
