### ISSUE TITLE
Hover over symbols without docstrings isn't rendered correctly

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4082]
## Environment data
-   Language Server version: 2023.3.22
-   OS and version: Windows 11
-   Python version: 3.11.2

## Code Snippet
```python
x = 1

def func():
    pass

def func_with_docstring():
    """doc string"""
    pass
```

## Repro Steps
1. Hover over `x`, `func`, and `func_with_docstring`

## Expected behavior
`x` hover says `(variable) x: Literal[1]`. `func` and `func_with_docstring` look similar.

![expected](https://user-images.githubusercontent.com/12820898/225493092-b6963e0d-1ac4-415d-837f-7a55242e54f2.gif)

## Actual behavior
`x` hover says `python (variable) x: Literal[1]` and has an unexpected gray background.  `func` looks similar. But `func_with_docstring` is fine.

![actual](https://user-images.githubusercontent.com/12820898/225493104-3ffe6345-20d9-453f-b42e-353e9d8474eb.gif)

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2022.3.25, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022325-17-March-2023-PreRelease)
