### ISSUE TITLE
Unpacking in type hint should not occour error

### ISSUE THREAD

**Issue by Harry-Jing** [microsoft/pylance-release#4084]
## Environment data

-   Language Server version: v2023.3.20
-   OS and version: Windows 11 Pro 22621.1344
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.10 and 3.11.2

## Code Snippet

```python
Literal[*("a", "b", "c")]
```

## Repro Steps

```python
from typing import Literal
Literal[*("a", "b", "c")]
```

## Expected behavior

No error occour. It can perfect work with pydantic typing check

Example code below
```python
from typing import Literal
from pydantic import BaseModel

class Data(BaseModel):
    data: Literal[*("a", "b", "c")]

print(Data(data="a"))
print(Data(data="d"))
```
output
```
data='a'
Traceback (most recent call last):
  File "c:\Users\Harry\Data\programing\python\3.11-feature\test.py", line 8, in <module>
    print(Data(data='d'))
          ^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Data
data
  unexpected value; permitted: 'a', 'b', 'c' (type=value_error.const; given=d; permitted=('a', 'b', 'c'))
```

So it can pass pydantic type check

## Actual behavior

Below happend in `python3.10.10`
```
Unpack operator in subscript requires Python 3.11 or newer
Unpacked arguments cannot be used in type argument lists
```
Below happend in `python3.11.2`
```
Unpacked arguments cannot be used in type argument lists
```

## Logs

None

**Comment by erictraut** [comment]
Unpack operators are not legal within static type annotations. While it may work at runtime, static type checkers like pyright (upon which pylance is built), mypy, and others support only certain simple expressions within type annotations as dictated by PEP 484 and subsequent standards established by static type checker maintainers.

So pyright is correct to indicate that this is an illegal expression to use within a type annotation. Mypy generates the same error here.

The correct way to specify a union of literals in a static type annotation is:
```python
Literal["a", "b", "c"]
```

**Comment by Harry-Jing** [comment]
The reason I need this is that I need to generate a lot of legal literal word.
```python
DisplayContentTypes: TypeAlias = Literal[
    'text-answer',
    'text-reference',
    'text-suggested-question',
    'text-answer&reference',
    'text-answer&suggested-question',
    'text-reference&answer',
    'text-reference&suggested-question',
    'text-suggested-question&answer',
    'text-suggested-question&reference',
    'text-answer&reference&suggested-question',
    'text-answer&suggested-question&reference',
    'text-reference&answer&suggested-question',
    'text-reference&suggested-question&answer',
    'text-suggested-question&answer&reference',
    'text-suggested-question&reference&answer',
    'image-answer',
    'image-reference',
    'image-suggested-question',
    'image-answer&reference',
    'image-answer&suggested-question',
    'image-reference&answer',
    'image-reference&suggested-question',
    'image-suggested-question&answer',
    'image-suggested-question&reference',
    'image-answer&reference&suggested-question',
    'image-answer&suggested-question&reference',
    'image-reference&answer&suggested-question',
    'image-reference&suggested-question&answer',
    'image-suggested-question&answer&reference',
    'image-suggested-question&reference&answer',
]
```
And when there is more option it need more space ande adjust each time. So I wright a generator expression to generator  it.
```python
DisplayContentTypes: TypeAlias = Literal[
    *('text-'+'&'.join(i) for i in itertools.chain.from_iterable(itertools.permutations(options, r) for r in range(1, len(options) + 1)))
    *('image-'+'&'.join(i) for i in itertools.chain.from_iterable(itertools.permutations(options, r) for r in range(1, len(options) + 1)))
]
```
Is there a better option for this?

**Comment by erictraut** [comment]
No, dynamic expressions such as this are intentionally and expressly disallowed for static type annotations. Type annotations need to be evaluated by static type analyzers, which do not run the code like the Python interpreter does.

If you want your code to work with static type checkers, you'll need to use the more verbose version. If you don't want to use static type checking, you can disable these types of errors by setting `python.analysis.typeCheckingMode` to "off".

**Comment by sheldonldev** [comment]
> The reason I need this is that I need to generate a lot of legal literal word.
> 
> ```python
> from typing import Literal
> 
> DisplayContentTypes: TypeAlias = Literal[
>     'text-answer',
>     'text-reference',
>     'text-suggested-question',
>     'text-answer&reference',
>     'text-answer&suggested-question',
>     'text-reference&answer',
>     'text-reference&suggested-question',
>     'text-suggested-question&answer',
>     'text-suggested-question&reference',
>     'text-answer&reference&suggested-question',
>     'text-answer&suggested-question&reference',
>     'text-reference&answer&suggested-question',
>     'text-reference&suggested-question&answer',
>     'text-suggested-question&answer&reference',
>     'text-suggested-question&reference&answer',
>     'image-answer',
>     'image-reference',
>     'image-suggested-question',
>     'image-answer&reference',
>     'image-answer&suggested-question',
>     'image-reference&answer',
>     'image-reference&suggested-question',
>     'image-suggested-question&answer',
>     'image-suggested-question&reference',
>     'image-answer&reference&suggested-question',
>     'image-answer&suggested-question&reference',
>     'image-reference&answer&suggested-question',
>     'image-reference&suggested-question&answer',
>     'image-suggested-question&answer&reference',
>     'image-suggested-question&reference&answer',
> ]
> ```
> 
> And when there is more option it need more space ande adjust each time. So I wright a generator expression to generator it.
> 
> ```python
> import itertools
> from typing import Literal
> 
> options = ('answer', 'reference', 'suggested-question')
> 
> DisplayContentTypes: TypeAlias = Literal[
>     *('text-'+'&'.join(i) for i in itertools.chain.from_iterable(itertools.permutations(options, r) for r in range(1, len(options) + 1)))
>     *('image-'+'&'.join(i) for i in itertools.chain.from_iterable(itertools.permutations(options, r) for r in range(1, len(options) + 1)))
> ]
> ```
> 
> Is there a better option for this?

I'm facing the same problem, may this help:

```py
from typing import Literal, get_args
WordExt = Literal[
    "doc",
    "docx",
]
WORD_EXTS: List[WordExt] = [*get_args(WordExt)]
```
