### ISSUE TITLE
Create documentation on the topic of using pylance and pyright (CLI) together

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#4085]
Users are seeing inconsistencies in errors and warnings when using VSC, VS, Pyright. 

Related issues:
https://github.com/microsoft/pylance-release/issues/3045
https://github.com/microsoft/pylance-release/discussions/3638
https://github.com/microsoft/pylance-release/issues/3838
https://github.com/microsoft/pyright/issues/4780
https://github.com/microsoft/pyright/issues/4784

**Comment by blakeNaccarato** [comment]
Thanks for putting this on the roadmap! Documenting the details of Pylance's type stub resolution will go a long way to help users align the behavior of vanilla `pyright` with Pylance, for instance in CI like GitHub Actions. Currently, the audiences that might benefit from this documentation are in camps (1) and (2) below, with (3) and (4) being extensions of camp (2) requiring feature development either in Pylance or VSCode.

1. Use `mypy` for type-checking, locally and in CI, and only use Pylance for refactoring features and QoL in your IDE.
2. Use `pyright` for type-checking in CI. Locally, stay at latest Pylance, and be okay with troubleshooting minor discrepancies with CI. Check in some stubs to the repo to reduce the discrepancies.
3. Desired feature: The same as (2), but allow Pylance to be configured to not use bundled stubs at all, giving full control to the developer to supply their stubs in their repo's `typings` folder.
4. Ridiculously complex solution that should not be considered (but mentioned here for completeness): The same as (2), but VSCode enables workspace-specific extension versioning granularity. Then, Pylance can be manually synchronized with the hypothetically-perfect stubs in the repo's `typings`.

I suspect that most people are in camp (1), but sufficient documentation of this thorny issue would make camp (2) more viable, especially for bigger projects. I also hope that the documentation addresses some of Pylance's type stub resolution mysteries, such as:

-  Pylance bundles stubs at `~/.vscode/extensions/ms-python.vscode-pylance-<RELEASE>/dist`. Does `typeshed-fallback` factor into stub resolution at all, and give rise to any possible pyright/Pylance discrepancies?
- The subfolder `bundled` has `native-stubs` and `stubs` directories. There is some overlap in their contents. Which stubs take precedence, and when? Are they loaded in a certain order?
- Is it possible to map the stub-loading logic of Pylance to an equivalent singular `typings` folder containing a certain set of stubs? If so, how might that be composed from the above stubs?
- Or is Pylance doing some advanced logic when deciding which stubs to load from `dist`, such that it is impossible to replicate exactly in a simple `typings` folder and with vanilla `pyright`?

Sorry about the essay-length comment, I'm looking forward to documentation as to the suggested approach!

**Comment by mbyt** [comment]
👍 for I think (3): Having exactly the same error & warning behavior locally and on CI. I do not care what to run in CI, however, it shall produce the same output as the local pylance vs-code extension.

Why: As we use a really strict pyright setup, the following might occur: pylance is green locally and red in CI (_no fast feedback, hides some of the advantages of using pylance and thus discourages developers to use it_).
