### ISSUE TITLE
AutoComplete and Preload Modules failing to load 

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/pylance-release#4086]
Type: <b>Bug</b>

Hi, I'm attempting to get a API python module to load with auto complete. Unfortunatley that is not working as even with the path to the module for the setting; `python.autocomplete.extraPaths` as well as the name of the name space for the module in the setting `python.autoComplete.preloadModules` upon `CTRL+SPACE` none of the functions for the module load. 

"python.autoComplete.extraPaths": [
        "C:\\Program Files\\Side Effects Software\\Houdini 16.5.496\\houdini\\python2.7libs",
        "C:\\Program Files\\Mari4.8v4\\Bundle\\bin\\lib\\site-packages"
    ],

    ],
    "python.autoComplete.preloadModules": [
        "hou",
        "mari" 

In the example above these are two programs each should load a *.pyd file into visual studio code as so that autoComplete will work. Unfortunately that is not working when I type for example; mari.+[CTRL+SPACE] nothing appears for autoComplete ?

Extension version: 2023.4.1
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
pythonb192:30669360
funwalk2:30682974
pythonms35cf:30686773

```

</details>

**Comment by NicTanghe** [comment]
Hi did you get the hou module working somehow ?
I can`t seem to get it to work?

**Comment by wyhinton** [comment]
Would love to know if anyone found a answer to this

**Comment by rchiodo** [comment]
PYD files require type stubs. You'd have to [generate them](https://microsoft.github.io/pyright/#/type-stubs?id=generating-type-stubs) yourself or find them from somewhere else.
