### ISSUE TITLE
Incomplete signature for ParamSpec

### ISSUE THREAD

**Issue by kvdveer** [microsoft/pylance-release#4096]
## Environment data

* Ubuntu 22:10
* Python 3.10.7
* 

-   Language Server version: v2023.3.20
-   OS and version: Ubuntu 2022.10
-   Python version: 3.10.7 from OS, using a venv

## Code Snippet

```python
P = ParamSpec("P", bound=Sequence)
```

This produces the error: `"bound" is an unknown parameter to ParamSpec`. However, Paramspec has had an (undocumented) `bound` parameter since [cpython 3.10.1](https://github.com/python/cpython/blob/v3.10.1/Lib/typing.py#L910).

**Comment by erictraut** [comment]
`ParamSpec` is a special form that type checkers need to special case, which is why pyright (the static type checker that underlies pylance) is reporting an error here. 

Do you happen to know why a `bound` parameter was added to `ParamSpec`? An upper bound makes no sense for a `ParamSpec`.

**Comment by kvdveer** [comment]
I suppose it was added because the specification demands it:
https://peps.python.org/pep-0612/#declaration

> The runtime should accept bounds and covariant and contravariant arguments in the declaration just as typing.TypeVar does, but for now we will defer the standardization of the semantics of those options to a later PEP.

However, mypy currently doesn't implement anything either:

```
foo.py:3: error: Only the first argument to ParamSpec has defined semantics  [misc]
```

**Comment by ifplusor** [comment]
However, it's documented now.

https://docs.python.org/3.13/library/typing.html#typing.ParamSpec

> Parameter specification variables created with `covariant=True` or `contravariant=True` can be used to declare covariant or contravariant generic types. The `bound` argument is also accepted, similar to [TypeVar](https://docs.python.org/3.13/library/typing.html#typing.TypeVar). However the actual semantics of these keywords are yet to be decided.
> 
> Added in version 3.10.
