### ISSUE TITLE
Support Markdown Docstrings

### ISSUE THREAD

**Issue by Destaq** [microsoft/pylance-release#41]
Since VS Code can display Markdown in the autocompletion dropdown and help boxes, it would be helpful to have this be extended to docstrings. Currently, docstrings only display as raw text with the occasional syntax highlight, as seen below:

![image](https://user-images.githubusercontent.com/61620873/86453348-ea403880-bd1d-11ea-8b06-041ea2144b91.png)

However, it is clear that VS Code supports Markdown in these boxes (i.e. for module descriptions, below)
![image](https://user-images.githubusercontent.com/61620873/86453421-09d76100-bd1e-11ea-93aa-6cf4f737862c.png)

So, I believe that a good Pylance enhancement would be to support Markdown in the docstrings as well. What I'm imagining would be useful would be have something show up similar to the modules with italicized and bolt text, lists, etc.; so as an example the original docstring would look how it looks below.

Access top *x* extensions from **current platform**

Args:
- x (int): number of top extensions to grab

**Comment by memeplex** [comment]
If markdown is supported then please don't assume everything is markdown, in that case it's better to have *no formatting at all*, there are many docstrings that contain google/numpy/sphinx-style formatting and many docstrings that don't use any format at al. The situation is already bad with both Jedi and MLS backends.

**Comment by bradennapier** [comment]
The best I could personally come up with is pretty custom but it is actually pretty practical.  By mapping back ticks to `'` you could parse it as yaml.  Not sure what the token is that makes that all red text, haven't tried to customize that yet.

![image](https://user-images.githubusercontent.com/15365418/89723738-2bd09d00-d9c8-11ea-84e5-b9383a2e30ed.png)

**Comment by tristan957** [comment]
Would be nice to be able to set the string formatting on a per package basis. Docstrings for your package may be in Markdown, so in your workspace settings.json, you could set the setting there to parse docstrings as markdown for your specific package, while other packages maybe in Google or reST syntax.

**Comment by jakebailey** [comment]
I believe that the original issue here was mainly about the docstrings with indention being poorly formatted; they are markdown, but we have to do some conversion of other formats (such as those in the original report). Here are some of the snippets from @bradennapier with the next version:

![image](https://user-images.githubusercontent.com/5341706/106655663-80576e00-654e-11eb-96b1-bbf6c9519587.png)

![image](https://user-images.githubusercontent.com/5341706/106655996-f065f400-654e-11eb-87bf-8498916e12b3.png)

Some of the other escapes are going to be fixed as well, though the `*` and `**` things are harder without really knowing for sure that any given doc is markdown (as `*` and `**` are frequently used in Python docstrings when desribing `*args` and `**kwargs`.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.2.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202120-3-february-2021
