### ISSUE TITLE
[QUESTION]  Pylance does not correctly resolve inherited classes (subclasses) with typing.Type[ ])?

### ISSUE THREAD

**Issue by schperplata** [microsoft/pylance-release#410]
Issue Type: <b>Bug</b>

Example:
```python
from typing import Type

class BaseClass():
    myBaseClassAttr: str = "asd"

class SubclassOne(BaseClass):
    mySubClassAttr: str = "x"

class SubclassTwo(BaseClass):
    mySubClassAttr: str = "y"

def myFunc(c1: Type[BaseClass], c2: Type[BaseClass]) -> Type[BaseClass]:
    """This funciton will copy 'c2.myBaseClassAttr' value to 'c1.myBaseClassAttr', and return updated 'c1'. Just a made up example."""
    c1.myBaseClassAttr = c2.myBaseClassAttr

    return c1

if __name__ == "__main__":
    c1 = SubclassOne()
    c1.myBaseClassAttr = "one"

    c2 = SubclassTwo()
    c2.myBaseClassAttr = "two"

    c1 = myFunc(c1, c2)
```
Code execute as expected, but Pylance is complaining:
`Type "SubclassTwo" cannot be assigned to type "Type[BaseClass]"Pylance (reportGeneralTypeIssues)`
![image](https://user-images.githubusercontent.com/8736111/94115555-2f21ca00-fe4a-11ea-8954-b5a95c994f45.png)

Both, `c1` and `c2` are subclasses of `BaseClass`:
```
type(c1):  <class '__main__.SubclassOne'>
isinstance(c1, BaseClass): True

type(c2): <class '__main__.SubclassTwo'>
isinstance(c2, BaseClass): True
```

**What am I missing/don't understand?**

Extension version: 2020.9.5
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.87GB free)|
|Process Argv|W:\BlueBox\trunk\fitIDEA3\_fitIDEA3.code-workspace --crash-reporter-id 919e0ed9-46f3-4ad4-9e28-f35755bf8266|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
I don't think that function signature should be using `Type`. As you've written `myFunc`, it's accepting types as the arguments, meaning a valid call would look like:

```python
myFunc(SubclassOne, SubclassTwo)
```

Did you mean a signature like:

```python
def myFunc(c1: BaseClass, c2: BaseClass) -> BaseClass: ...

if __name__ == "__main__":
    c1 = SubclassOne()
    c1.myBaseClassAttr = "one"

    c2 = SubclassTwo()
    c2.myBaseClassAttr = "two"

    c1 = myFunc(c1, c2)
```

This should type check.

**Comment by schperplata** [comment]
Follow-up question: How should return type be defined? Is Pylance capable of resolving such scenarios?
```python
def myFunc(c1: BaseClass, c2: BaseClass) -> BaseClass:
    """This funciton will copy 'c2.myBaseClassAttr' value to 'c1.myBaseClassAttr', and return updated 'c1'. Just a made up example."""
    c1.myBaseClassAttr = c2.myBaseClassAttr

    return c1

if __name__ == "__main__":
    c1 = SubclassOne()
    c1.myBaseClassAttr = "one"

    c2 = SubclassTwo()
    c2.myBaseClassAttr = "two"

    c1 = myFunc(c1, c2)
    print(c1.mySubClassAttr)
```
Pylance is warning me that `c1.mySubClassAttr` does not exist, since function returns `BaseClass`. In fact, I only want to type hint function that it returns whatever comes in `c1` argument.
![image](https://user-images.githubusercontent.com/8736111/94235752-55a83980-ff0c-11ea-88fa-2454cdc3eb8e.png)

**Comment by erictraut** [comment]
If I correctly understand what you're trying to do, the proper way would be to use a bound type variable as follows:

```python
_T = TypeVar("_T", bound=BaseClass)

def myFunc(c1: _T, c2: BaseClass) -> _T:
    c1.myBaseClassAttr = c2.myBaseClassAttr
    return c1
```

**Comment by schperplata** [comment]
Yes. That is exactly what I need. Thanks.

**Comment by erictraut** [comment]
If you're using a non-bound, non-constrained TypeVar in only one place in your function signature, you're probably doing something wrong. Such a TypeVar serves no purpose. In my proposed solution above, the TypeVar is used multiple times and it is bound to a type.

If you need help with a problem that differs from the one above, please post a minimal code sample and an explanation of what you're trying to do.

**Comment by CsatiZoltan** [comment]
Sorry, it was my mistake. Actually, I want to pass a class object to `f`, not an instance (because `f` is a factory function). In your example, it would be
```python
f(BasisA)
```
which gives
```
Argument of type "Type[BasisA]" cannot be assigned to parameter "basis" of type "Basis" in function "f"
  "Type[type]" is incompatible with "Type[Basis]"
```

**Comment by erictraut** [comment]
If you want to pass a class (as opposed to a class instance), you need to use the type annotation `type[Basis]` in your function.

**Comment by CsatiZoltan** [comment]
Thank you, that solved my issue. Do you know where I should start reading about Python's type system to really understand `TypeVar`, `type`, etc? Maybe the [PEPs](https://docs.python.org/3/library/typing.html#relevant-peps)?
