### ISSUE TITLE
Stub a file for auto-complete ?

### ISSUE THREAD

**Issue by SheepDomination** [microsoft/pylance-release#4106]
Hi, I was hoping someone can help. I have a PYD for me to use this file with auto-complete I was informed that I must *stub* the file. Since this is new to me, I have created basically an empty `pylanceconfig.json` file which only includes the following for visual studio code. 

```
{
    "include" : [
        "src"
    ],

    "exclude":[
        
    ]
}
```

Although, what must I place in this pylance configuration file for auto-complete to work but also to load the name space of the module ? For example; when typing `black.` then a list of all the functions for that module would load; that is if `black` was a real name space for a module which I want to load with auto-complete although it's only an example.

**Comment by erictraut** [comment]
You need to create a type stub file that corresponds to the module name. For example, if the library is called `my_library.pyd`, then the top-level module name is `my_library`. Create a file `my_library/__init__.pyi` within your project under a subdirectory called `typings`

```python
# ./typings/my_library/__init__.pyi

# Define all of the symbols exported by `my_library` module. For example,
# if `black` is a function that takes no parameters and returns a str, you would
# add the following.
def black() -> str: ...
```

**Comment by SheepDomination** [comment]
Is it possible to do this for user settings, rather then a workspace setting ? In other words, create subdirectory called `typings` and within the user settings have this path found so that the module can be stubbed ?

Also I have to go though all the modules functions and stub the ones I use or want to use ?

**Comment by erictraut** [comment]
If you want other project collaborators to benefit from the stubs you generate, you should check in the `typings` folder that is local to your project and use workspace settings to access them.

If you are not checking in your code and simply want to use a common set of stubs across your projects, you can use the `python.analysis.stubPath` setting (which can be set as a user or workspace setting) to tell pylance where your type stubs live.

> Also I have to go though all the modules functions and stub the ones I use or want to use ?

Yes, if the library author doesn't provide type information and the library is written in a language other than Python. If this is a library that's important to you, you may want to post a request with the library author to include type stubs in the library distribution. This will improve the experience for all consumers of that library and eliminate the need for them to individually generate stub files.

**Comment by erictraut** [comment]
Do you have documentation for the library? That will typically provide a list of the public symbols (functions, classes, methods, constants, etc.) exposed by the library.

**Comment by SheepDomination** [comment]
I have access to the library including (functions, classes) so therefore the setting `python.analysis.stubPath` will stub all the functions, classes; or what command must I use to stub the functions ?

**Comment by erictraut** [comment]
You need to write the type stubs yourself based on the documentation or source code. You can then place these type stubs in the `typings` folder. If you want to place them in some other folder, you can use the `python.analysis.stubPath` setting to point to that other folder. This isn't a "command", it's a setting that refers to a directory.

**Comment by SheepDomination** [comment]
When stubbing a class, does it include all methods of that class ?  
I understand, although; how do you stub the class or method of a class if you need to stub method separately from classes ?

**Comment by judej** [comment]
There is documentation for creating Type stubs [here](https://microsoft.github.io/pyright/#/type-stubs?id=type-stub-files). As well as [here](https://typing.readthedocs.io/en/latest/source/libraries.html). 

Hopefully these will answer your question.

**Comment by erictraut** [comment]
Pylance can generate a "first draft" of stub files for libraries that are written in Python. It isn't able to produce type stubs from native libraries like ".pyd" files.

There are other tools available that will produce minimal stubs for native libraries. Check out [stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html.

The type information produced from a native library is going to be very minimal. It will be insufficient for type checking, but it may be good enough for basic auto-complete support. You'll need to do significant manual cleanup of these stubs if you want them to contain good type information. In my experience, you may be better of simply writing the stubs yourself from scratch rather than starting with the generated stubs.

If this is a library that's important to you, I recommend contacting the maintainers of the library and asking them to include stub files in future releases. Most popular Python libraries have started to include type information over the past few years.
