### ISSUE TITLE
Extension Hijacks whitespace preferences, inserts spaces regardless settings or editorconfig

### ISSUE THREAD

**Issue by GinoMan** [microsoft/pylance-release#4109]
Type: <b>Bug</b>

# Behaviour

I understand that Pep-8 is quite dictatorial about the use of spaces and yet the python interpreter and compiler doesn't care. It will happily allow you to use tabs for your indentation. And for me, tabs make more sense. I never use space-based indentation in my code. But I'm getting really sick of boxing with my editor to do that without it constantly changing my own code to use what everyone else seems to think is best. I'm my own programmer and I'm nonplussed that I've filed this before within the past week or so and that report isn't even "closed" it's just gone.

Inb4 you say "well, do you run a formatter? are you sure it's not another plugin? etc", I've traced it to this plugin. I've diabled all plugins and enabled them one by one reloading the editor each time and tested if it happens each time. I've even created a new blank profile with no plugins and installed only the python extension and whatever it depends on and the behavior returned. It's this plugin or one of its related plugins all of which are microsoft plugins and go with this one. It's this plugin. I've disabled all formatters and linters and still get the same result. Below is the information for the behaviors and my setup.

## Expected

Given the following config:

```json
"editor.insertSpaces": false,
"editor.renderWhitespace": "all",
```

1. Create a new Python file
2. Type in any element that expects the next line to be indented
3. Hit enter
4. File has the following contents:

```
def function():
\t|
```

## Actual Behavior

File instead has...

```
def function():
_ _ _ _ |
```

![VSCode Python Bug](https://user-images.githubusercontent.com/528834/226153507-37ab3c75-6105-43a2-ba46-8da2cef03b0b.gif)

## Steps to reproduce:

1. Set `"editor.insertSpaces"` to `false` in ANY configuration
1. (alternatively set .editorconfig appropriately to do the same)
2. Create a new python file
3. type in a function/class/etc's header (`def function():`)
4. hit the enter key to invoke the automatic indentation

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): PipEnv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

(Note, I cleared the output panel before hitting enter on a function name so as not to polute the panel with extraneous stuff, but it seems that everything in the panel just has to do with the fact that pytest hasn't been setup for this project yet.)

```
[INFO 2023-2-18 23:55:57.959]: [
  'getActivatedEnvironmentVariables, Class name = k, completed in 0ms, has a truthy return value, Arg 1: <Uri:c:\\Users\\OpenM\\source\\repos\\Edit-Env>, Arg 2: undefined, Arg 3: false'
]
> .\.venv\Scripts\python.exe ~\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\testing_tools\run_adapter.py discover pytest -- --rootdir . -s --cache-clear --cov=. --cov-report=xml:coverage.xml
cwd: .
[ERROR 2023-2-18 23:55:59.323]: Error discovering pytest tests:
 n [Error]: ERROR: usage: run_adapter.py [options] [file_or_dir] [file_or_dir] [...]
run_adapter.py: error: unrecognized arguments: --cov=c:\Users\OpenM\source\repos\Edit-Env --cov-report=xml:coverage.xml
  inifile: None
  rootdir: c:\Users\OpenM\source\repos\Edit-Env


Traceback (most recent call last):
  File "c:\Users\OpenM\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\testing_tools\run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "c:\Users\OpenM\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\testing_tools\adapter\__main__.py", line 99, in main
    parents, result = run(toolargs, **subargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\OpenM\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\testing_tools\adapter\pytest\_discovery.py", line 47, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 4)

    at ChildProcess.<anonymous> (c:\Users\OpenM\.vscode\extensions\ms-python.python-2023.4.1\out\client\extension.js:2:244860)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)


```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

pipenvPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: false
• flake8Args: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "none"
• blackPath: "<placeholder>"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```

</p>
</details>

Extension version: 2023.4.1
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.89GB (0.55GB free)|
|Process Argv|--crash-reporter-id cb928791-934b-4d70-ac94-10d42d342b49|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
f6dab269:30613381
vscrp:30673768
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
vsctsb:30677850
functionswalk:30687959
pythonms35cf:30686773

```

</details>

**Comment by rchiodo** [comment]
I believe you already entered this issue? https://github.com/microsoft/pylance-release/issues/4071

Not sure what the difference is?

**Comment by GinoMan** [comment]
The other one disappeared. I couldn't find it either in the list of opened issues nor in issues authored by me and so I assumed it got lost/deleted/I forgot to actually post it.

**Comment by rchiodo** [comment]
Okay thanks for replying.
