### ISSUE TITLE
Cannot assign `Sequence[T]` with constrained `T` to the union of {`Sequence[T]` for all T}

### ISSUE THREAD

**Issue by dfangs** [microsoft/pylance-release#4115]
## Environment data
-   Language Server version: v2023.3.20
-   OS and version: macOS Monterey 12.6
-   Python version: Python 3.11.2 64-bit

## Code Snippet
```python
from typing import TypeVar
from collections.abc import Sequence

T = TypeVar("T", str, float)
Aliased = Sequence[str] | Sequence[float]

def func(values: Sequence[T]) -> Sequence[T]:
    direct_inside: Sequence[str] | Sequence[float] = values  # type error here
    aliased_inside: Aliased = values  # type error here
    return values

direct_outside: Sequence[str] | Sequence[float] = func([1, 2, 3])
aliased_outside: Aliased = func([1, 2, 3])
```

## Expected behavior

No static error. mypy 1.1.1 also reported no issue with the code: [link to the playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=811c6e45506483cec483e1b2dc04c6c9).

## Actual behavior

Type error when assigning a generic `Sequence[T]` variable (with `T` constrained to a set of possible types) to a union of those sequences, but no error when the assignment is done outside of the function. Type aliases work just fine, though.
 
```
Expression of type "Sequence[T@func]" cannot be assigned to declared type "Sequence[str] | Sequence[float]"
  Type "Sequence[T@func]" cannot be assigned to type "Sequence[str] | Sequence[float]"
    "Sequence[T@func]" is incompatible with "Sequence[str]"
      TypeVar "_T_co@Sequence" is covariant
        Type "str* | float*" cannot be assigned to type "str"
          "float*" is incompatible with "str"
    "Sequence[T@func]" is incompatible with "Sequence[float]"
      TypeVar "_T_co@Sequence" is covariant
        Type "str* | float*" cannot be assigned to type "float"
  ...

Expression of type "Sequence[T@func]" cannot be assigned to declared type "Aliased"
  Type "Sequence[T@func]" cannot be assigned to type "Aliased"
    "Sequence[T@func]" is incompatible with "Sequence[str]"
      TypeVar "_T_co@Sequence" is covariant
        Type "str* | float*" cannot be assigned to type "str"
          "float*" is incompatible with "str"
    "Sequence[T@func]" is incompatible with "Sequence[float]"
      TypeVar "_T_co@Sequence" is covariant
        Type "str* | float*" cannot be assigned to type "float"
  ...
```

**Comment by erictraut** [comment]
This is by design. It's not a bug. You are using a constrained TypeVar in your code sample. A constrained TypeVar is an oddity of the Python type system, not found in any other language's type system. I recommend avoiding it if possible. It's underspecified in PEP 484. Refer to [this documentation](https://microsoft.github.io/pyright/#/mypy-comparison?id=constrained-type-variables) for more details. This happens to work with mypy's implementation of constrained TypeVars, but it will not work with pyright, the type checker that pylance is based on.

**Comment by dfangs** [comment]
I see. Thanks for the explanation!
