### ISSUE TITLE
Pylance inappropriately complains about an empty `TypedDict` instance

### ISSUE THREAD

**Issue by bland328** [microsoft/pylance-release#4116]
<h3> Environment data </h3>

-   Language Server version: 2023.3.20
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.2
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from typing import TypedDict
class Person(TypedDict):
    name: str
    age: int
people = Person()
```

Pylance reports `Arguments missing for parameters "name", "age"` regarding the empty `Person()` instantiation in the final line.

This complaint doesn't make sense to me for an _empty_ `TypedDict` instance--an empty instance is valid, functional, and the typed equivalent of ```people = {}```.

Furthermore, I can't imagine any way to satisfy Pylance in this case--how would one provide arguments for item parameters in an empty dictionary?

As an experiment, I tried annotating both `TypedDict` items as `NotRequired`...

```python
from typing import TypedDict, NotRequired
class Person(TypedDict):
    name: NotRequired[str]
    age: NotRequired[int]
people = Person()
```

...and found that this _does_ satisfy Pylance.

That's interesting, but it seems to me that changing the "contract" for creation of dictionary items should have no impact on the evaluation of a dictionary containing no items.

**Comment by erictraut** [comment]
Pyright's behavior is correct. Please refer to [PEP 589](https://peps.python.org/pep-0589/) for details about TypedDict. You've defined a TypedDict where all of the keys are required, so it is invalid to construct an instance of `Person` with these keys missing. If your intent is to specify a TypedDict where these keys are not required, you can do it in one of two ways.

```python
class Person(TypedDict, total=False):
    name: str
    age: int
```

or

```python
class Person(TypedDict):
    name: NotRequired[str]
    age: NotRequired[int]
```

**Comment by bland328** [comment]
Lest anyone else read my original post and become confused by my confusion...apparently I didn't get enough sleep last night, and managed to deeply misunderstand even the basics of properly using `TypedDict`.

So, please disregard. Nothing to see here :)
