### ISSUE TITLE
Rename on symbol in `from foo import foo` incorrectly updates module name

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4129]
## Environment data

-   Language Server version: 2023.3.31

### `declare.py`
```python
def declare():
    return "success"
```

### `consume.py`
```python
from declare import declare

declare()
```

## Repro Steps

1. Create files as above
2. Right-click on `declare()` call in `consume.py` and select `Rename Symbol`
3. Enter `func` as new name, press Enter.

## Expected behavior

Within `consume.py` only the imported symbol name and the function call are modified.
```
from declare import func

func()
```

## Actual behavior

Module name in import is also changed. Error on module name: "Import "func" could not be resolvedPylance (reportMissingImports)"

```
from func import func

func()
```

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.4.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023411-5-April-2023-PreRelease)
