### ISSUE TITLE
Incorrect type hint

### ISSUE THREAD

**Issue by XJTLUmedia** [microsoft/pylance-release#4130]
## Environment data

-   Language Server version: 1.77
-   OS and version: Win11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

```python
import pandas as pd
import numpy as np
df1=pd.DataFrame([[1,2,3],[4,5,6],[7,8,],[7,9,]],columns=['a','b','c'])
count=df1['c'].isna().sum()
```

## Expected behavior

count should be integer

## Actual behavior

```python
df1: DataFrame=pd.DataFrame([[1,2,3],[4,5,6],[7,8,],[7,9,]],columns=['a','b','c'])
count: bool=df1['c'].isna().sum()
```
count type hint is boolean

## Logs

![Uploading Screenshot 2023-03-23 101354.png…]()

**Comment by rchiodo** [comment]
Thanks for the issue. 

This looks like a bug in the pandas stubs:

https://github.com/pandas-dev/pandas-stubs/blob/f16ac9024fe1f8cdd5c09cedd0aa3512012585bc/pandas-stubs/core/series.pyi#L1814

Series.sum is annotated as returning the same type as the series instead of an int.

**Comment by rchiodo** [comment]
You can log a bug on panda-stubs if you wanted it to come out correctly in pylance. Or submit a PR to change sum to return an int.
