### ISSUE TITLE
"NotRequired" is not allowed in this context

### ISSUE THREAD

**Issue by raman325** [microsoft/pylance-release#4131]
While trying to implement https://peps.python.org/pep-0655/ I am running into the titled error. Here is the code that is generating the error (all four attributes generate the error):

Running in both Python 3.10 and 3.11 (in 3.10 I import `TypedDict` from `typing_extensions`)
```python
class CodeSlot(TypedDict):
    """Represent a code slot."""

    code_slot: int
    name: str
    in_use: bool | None
    usercode: NotRequired[str | None]
```

I feel like I am missing something obvious but I can't figure out what it is. My tests, including running `mypy` and `pylint` pass in both Python versions so what gives? Thanks in advance!

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing. I suspect that you may have some old library installed in your Python environment — perhaps an old typing_extensions-stub library? Please try to repro the problem with a freshly-created virtual environment.

**Comment by raman325** [comment]
It looks like it has to do with the fact that I am trying to support both python 3.10 and python 3.11. I have a constant called `TYPING_EXTENSION_REQUIRED` that is set to `sys.version_info < (3, 11)` and the imports are set up as follows:

```python
if TYPING_EXTENSION_REQUIRED:
    from typing_extensions import NotRequired, TypedDict
else:
    from typing import NotRequired, TypedDict
```

When I remove this condition and use the appropriate import for the version I am using, the error goes away

**Comment by erictraut** [comment]
Yes, you cannot define a constant in that manner if you want static type checkers to work correctly. PEP 484, which introduced type checking to Python, dictates that static type checkers must honor certain conditional expression forms statically when determining which portions of the code to analyze. This includes the form `sys.version_info < (3, 11)`. This must be evaluated early in the analysis, long before any types or constants can be evaluated. So, if you want this to work, you cannot use a constant. You need to use `sys.version_info < (3, 11)` directly in the conditional statement.

I recommend eliminating this entire block and importing only from `typing_extension`. This package is meant to handle backward compatibility. It already has these conditional statements built into it, so there's no need for your code to conditionally check for the Python version. Simply use `from typing_extensions import NotRequired, TypedDict`, and you'll be fine.

**Comment by raman325** [comment]
thanks @erictraut I appreciate the explanation and will do as you advise!
