### ISSUE TITLE
Pylance report do not find module sys？

### ISSUE THREAD

**Issue by gramce** [microsoft/pylance-release#4132]
<img width="730" alt="截屏2023-03-23 16 02 34" src="https://user-images.githubusercontent.com/17009832/227140666-c9f8d4f9-9102-488c-a57d-fc524b5ce70d.png">
<img width="719" alt="截屏2023-03-23 16 02 19" src="https://user-images.githubusercontent.com/17009832/227140699-e8c2cd8d-6984-4c3c-9ae2-28d6773e39ca.png">

When I add some dir into the workspace, Pylance don't work properly.

OS: macos 13.2.1 (22D68)
version: 1.76.2
comment: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
date: 2023-03-14T17:54:09.061Z 
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
docker: No
Pylance: try v2023.3.31 and v2023.3.30
Python: Language Server: Pylance
python interpreter: Try conda env and system default env

**Comment by gramce** [comment]
Thanks for your response.
Here is the log.
https://gist.github.com/gramce/3eb0a2afef7aacc6e7140d1a993c291d

**Comment by gramce** [comment]
After examine the user setting, I found there is a setting
python.analysis.typeshedPaths: "/Users/gramce/opt/anaconda3/pkgs".
When I remove this, the issue was fixed. But I have no idea that what is this and who add it.

```
{
  "[json]": {
    "editor.quickSuggestions": {
      "strings": true
    },
    "editor.suggest.insertMode": "replace"
  },
  "editor.accessibilitySupport": "off",
  "git.autofetch": true,
  "jupyter.jupyterServerType": "remote",
  "python.analysis.diagnosticMode": "workspace",
  "python.analysis.extraPaths": [
    "/Users/gramce/opt/anaconda3/pkgs"
  ],
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1"
  },
  "terminal.integrated.inheritEnv": false,
  "workbench.colorTheme": "Monokai",
  "workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
  },
  "[python]": {

    "editor.formatOnType": true
  },
  "jupyter.interactiveWindow.creationMode": "perFile",
  "tabnine.experimentalAutoImports": true,
  "python.analysis.autoImportCompletions": true,
  "python.analysis.completeFunctionParens": true,
  "python.analysis.diagnosticSeverityOverrides": {

  },
  "python.analysis.typeCheckingMode": "basic",
  "python.languageServer": "Pylance",
  "python.analysis.logLevel": "Trace",
}
```

**Comment by erictraut** [comment]
Yes, setting `typeshedPaths` to a directory that does not include the stdlib typeshed paths will cause many problems. In general, `typeshedPaths` should be set only for people who are actively updating typeshed stub files.
