### ISSUE TITLE
Enable autocomplete and reference resolution in VSCode with pylance from a c++ code wrapped with pybind11

### ISSUE THREAD

**Issue by Wondounet** [microsoft/pylance-release#4133]
Hello,

I have a function called "Add" which add two integers, I used pybind11 to bind this function. When I compile my solution on visual studio I obtain a .pyd dll which contain my function. 

```
int Add(int i, int j)
{
	return i + j;
}

PYBIND11_MODULE(MyModule, m)
{
	m.def("Add", &Add);
}
```

When I import this module in python, it works well and I can use my "Add" function.

```
from MyModule import *

print(Add(3, 5))
```
_The code in visual studio code._

My problem is that there is no autocomplete for this "Add" function. I supposed it is normal because the .pyd is a binary file but I search on internet some solution to this problem. So I tried to create a MyModule.pyi which describe my "Add" function as you can see below:
`def Add(a: int, b: int) -> int:...`

I was hoping (probably naively) that putting this .pyi file next to my .pyd file will enable Pylance to find the definition of the "Add" function and permits autocomplete but this is not the case.

I am doing the right thing to reach my objectiv ? Is it possible ? What did I do wrong ? Thanks !

PS: I also set Pylance a the "python.languageServer".

**Comment by DingXuefeng** [comment]
I have the same problem but it doesn't work with the method you mentioned.
