### ISSUE TITLE
How to inform `reportGeneralTypeIssues` of TypeAliases?

### ISSUE THREAD

**Issue by dsm-72** [microsoft/pylance-release#4135]
I have some type aliases which pylance gives me TypeIssues. How do I inform pylance of these types?

**Comment by dsm-72** [comment]
@erictraut thank you for responding. 
I have a file in a package I installed with `pip install -e .`

```python
# types.py
from typing import (
    TypeAlias, List, 
    Sequence, Literal,
    Tuple, NamedTuple, 
    Union, get_args
)


Series: TypeAlias = pd.Series

ndarray: TypeAlias = np.ndarray

SeriesLike: TypeAlias = Union[list, Series, ndarray, Tensor]
```

and then 

```python
# utils.py
from .types import ndarray
def is_np(arr_q:ndarray) -> bool:
    return isinstance(arr_q, ndarray)
```
which gives me the squiggle for `ndarray`.

This is the simplest I can make the example and get the warning.

**Comment by erictraut** [comment]
I presume that you also have import statements that define `np`, `pd`, and `Tensor`? Those are undefined in your self-contained sample above.

I'm not able to repro an error based on the same you provided above. Are you able to repro the problem with a fresh virtual environment and a clean project? I suspect that you have something stale installed in your environment, perhaps an old stub library, that is causing the problem.

Also, you mentioned that you're using an editable install. I'm not sure which package you're referring to here? Is it one of the packages in your minimal, self-contained sample? There are issues that you may want to be aware of with [editable installs](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#editable-install-modules-not-found).

**Comment by dsm-72** [comment]
hmmm my environment is 

```yml
name: my_env
channels:
  - conda-forge  
dependencies:  
  - python>=3.10  
  - numpy
  - pandas
```

I have an `__init__.py` and  `setup.py` file as well 

```
# my_project
__init__.py
setup.py
types.py
utils.py
env.yml
```

**Comment by erictraut** [comment]
You said "which gives me the squiggle for ndarray". Which "ndarray" is being flagged? (Your sample includes `ndarray` in three places — once in an import statement, once in a type annotation, and a third time as an argument for `isinstance`.) What is the diagnostic message?

**Comment by dsm-72** [comment]
@erictraut, ah sorry for not being clear.

```python
from .types import ndarray
def is_np(arr_q:ndarray) -> bool:             # <---- squiggle
    return isinstance(arr_q, ndarray)         # <---- squiggle
```

**Comment by erictraut** [comment]
And what is the diagnostic message you're receiving for each of these lines? You mentioned that they were associated with the `reportGeneralTypeIssues` diagnostic rule, but that's kind of a catch-all rule for many diagnostic messages.

**Comment by dsm-72** [comment]
That is the message for each of them.  Pylance just doesn't know what they are.

**Comment by debonte** [comment]
> That is the message for each of them. Pylance just doesn't know what they are.

@dsm-72, what is the associated diagnostic message? 

For example, for `x: int = "str"` I get the following diagnostic which is a `reportGeneralTypeIssues` diagnostic too, but `reportGeneralTypeIssues` diagnostics can have many other possible messages.

```text
Expression of type "Literal['str']" cannot be assigned to declared type "int"
  "Literal['str']" is incompatible with "int" (reportGeneralTypeIssues)
```

**Comment by debonte** [comment]
`reportGeneralTypeIssues` is a class of diagnostics, not a specific error. For example, below are two `reportGeneralTypeIssues` diagnostics. Note that the description of the actual problem in the two cases is very different. We need to know what that descriptive text is in the case(s) that you are hitting.

```text
Expression of type "Literal['str']" cannot be assigned to declared type "int"
  "Literal['str']" is incompatible with "int" (reportGeneralTypeIssues)
```

```text
Argument of type "Literal[10]" cannot be assigned to parameter "__value" of type "None" in function "send"
  Type cannot be assigned to type "None" (reportGeneralTypeIssues)
```

**Comment by rchiodo** [comment]
Closing issue with no response. If you can respond with the asked for information, please reopen this issue.

Thanks.
