### ISSUE TITLE
Docstring for an object which is decorated by a class

### ISSUE THREAD

**Issue by tjsmart** [microsoft/pylance-release#4139]
I have a feeling that I'm not the first person to ask this question but my research has failed to find an answer anywhere.

My use case is that I have a class `Foo` that is intended to be used as a decorator of a function `bar`.

```python
class Foo:
    def __init__(self, x):
        self._x = x
        self.__doc__ = x.__doc__


@Foo
def bar(abc):
    """
    Docstring for bar!
    """
    ...
```

The above code gives me the expected runtime behavior, e.g. it creates a `Foo` object named `bar` by passing the `bar` function in as an argument to `Foo`'s `__init__`.

***The problem:*** 
In the above example, I am unsure of how to correctly add a docstring to the object `bar`. What I have tried above will not show up in pylance's provided intellisense.

---

I also tried putting the docstring at the very end but it did not work either:
```python
@Foo
def bar(abc):
    ...
"""
Docstring for bar!
"""
```

---

One work around I've come up with is that I can break this up into two separate statements:

```python
def bar_wrapped(abc):
    ...

bar = Foo(bar_wrapped)
"""
Docstring for bar!
"""
```

And this seems to work more appropriately. While I'm willing to use this workaround, I'm hoping that there is some clever trick to get my original code to work 😄 . I'm also aware of `functools.wraps` but not sure that it applies to my use case.

**Comment by tjsmart** [comment]
Playing around with this a bit more It also seems that In the original snippet `bar` is being reported as a `function`:
![image](https://user-images.githubusercontent.com/40041862/227347757-28a08263-ebc9-4670-ab45-844cf27ec025.png)

I'd instead expect to see:
![image](https://user-images.githubusercontent.com/40041862/227348145-175f418b-38b0-4eda-9240-56d7d745387f.png)

**Comment by rchiodo** [comment]
Hovering over bar shows me this? 

![image](https://user-images.githubusercontent.com/19672699/227349035-ec88a372-a49b-42b9-ae20-11d01cd1707a.png)

Is that not what happens for you? If not, what version of Pylance are you using?

**Comment by rchiodo** [comment]
Or are you talking about where you use it?

![image](https://user-images.githubusercontent.com/19672699/227351641-456d7706-f664-4353-b181-ed74bd20d711.png)

In this case we don't track the `__doc__` assignment in the Foo class so the docstring wouldn't show up.

**Comment by erictraut** [comment]
Is your "wrapped" function meant to be callable? In other words, does your `Foo` class implement a `__call__` method, and you're looking for the docstring to appear when calling `bar`? Something like this?

```python
class Foo:
    def __init__(self, x):
        self._x = x
        self.__doc__ = x.__doc__

    def __call__(self):
        return self._x()

@Foo
def bar(abc):
    """
    Docstring for bar!
    """
    ...

bar() # <= you want the docstring to appear here in the "signature help" text?
```

**Comment by tjsmart** [comment]
Yeah I'm talking about when you go to use it.
![image](https://user-images.githubusercontent.com/40041862/227352240-66a1dcc1-e0fc-4ccd-a832-93816ac8eec0.png)

**Comment by erictraut** [comment]
If `Foo` is callable, then you can annotate it as follows such that it retains the docstring through the use of a `ParamSpec`.

```python
from typing import Callable, Generic, ParamSpec, TypeVar

P = ParamSpec("P")
R = TypeVar("R")

class Foo(Generic[P, R]):
    def __init__(self, x: Callable[P, R]):
        self._x = x
        self.__doc__ = x.__doc__

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R:
        return self._x(*args, **kwargs)

@Foo
def bar(abc):
    """
    Docstring for bar!
    """
    ...

bar()
```

Here's what it looks like when you attempt to call `bar`:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/7040122/227354214-de91ee01-4ce9-47d6-b27f-0c1497f11782.png">

**Comment by tjsmart** [comment]
The exact use case looks something more like this
```python
from typing import ParamSpec, Generic, Callable

P = ParamSpec("P")


class Topic(Generic[P]):
    def __init__(self, topic: Callable[P, None]):
        self.name = topic.__name__

    def send(self, *args: P.args, **kwargs: P.kwargs):
        send(self.name, *args, **kwargs)

    def subscribe(self, subscriber: Callable[P, None]):
        subscribe(subscriber, self.name)

@Topic
def bar(msg: str) -> None:
    """
    Docstring for the bar topic!
    """
    ...
```

Ideally `bar` would show the docstring in the above example.
![image](https://user-images.githubusercontent.com/40041862/227357329-aa31b8e4-3ebc-4e36-965f-66a0e2b60dd9.png)


It instead shows up on `send`, I suppose due to how `ParamSpec` is treated:

![image](https://user-images.githubusercontent.com/40041862/227357415-27b870e0-aa51-4031-97d6-80b9504f5bdf.png)

![image](https://user-images.githubusercontent.com/40041862/227357685-f4fe83d1-fa2d-46e2-8f8c-086321588ef9.png)

**Comment by tjsmart** [comment]
Here is an alternative approach which comes close:

```python
from typing import ParamSpec, Generic, Callable

P = ParamSpec("P")


class Topic(Generic[P]):
    def __init__(self, name: str):
        self.name = name

    def send(self, *args: P.args, **kwargs: P.kwargs):
        send(self.name, *args, **kwargs)

    def subscribe(self, subscriber: Callable[P, None]):
        subscribe(subscriber, self.name)

bar: Topic[[str]]: Topic("bar")
"""
Docstring for the bar topic!
"""
```

But as you can see the call signature is worse (doesn't include the argument information `msg`, nor whether it is keyword only:
![image](https://user-images.githubusercontent.com/40041862/227362206-ce425409-2ef1-4068-b410-fea5992cb187.png)

![image](https://user-images.githubusercontent.com/40041862/227362272-07552751-863d-46f3-a829-8648ee46280f.png)

---

Just dreaming, but I would love to be able to do something like below to more accurately specify the call information:
```python
bar: Topic[(msg: str -> None)]: Topic("bar")
"""
Docstring for the bar topic!
"""
```

**Comment by erictraut** [comment]
Yeah, that's not legal Python syntax, unfortunately. There was an attempt to standardize something [similar to this](https://peps.python.org/pep-0677/), but the Python Steering Council rejected it. :(

**Comment by tjsmart** [comment]
Wow, that would be neat but I suppose I can also understand the reasons for rejecting it. To me the more important thing is not trading `Callable[[str], None]` for `(str) -> None`. But rather being able to specify call signatures such as `(*, msg: str) -> None`, which the current syntax does not provide.

For now I've settled on doing this:
```python
from typing import ParamSpec, Generic, Callable

P = ParamSpec("P")


class Topic(Generic[P]):
    def __init__(self, signature: Callable[P, None], name: str) -> None:
        self.name = name

    def send(self, *args: P.args, **kwargs: P.kwargs):
        send(self.name, *args, **kwargs)

    def subscribe(self, subscriber: Callable[P, None]):
        subscribe(subscriber, self.name)

def _(*, msg: str) -> None:
    ...

bar = Topic(_, "bar")
"""
Docstring for the bar topic!
"""
```

Which isn't as slick as what I had originally but seems to give the most accurate information possible to the user.

Feel free to close and thanks both for the help! 😄
