### ISSUE TITLE
functools.wraps broken for complex class decorator for versions after 2023.02.40

### ISSUE THREAD

**Issue by shartzog** [microsoft/pylance-release#4140]
Type: <b>Bug</b>

Pylance was able to correctly return the docstring and type annotations of the original function for functions wrapped with class decorators similar to that shown below up until v2023.02.40.  Beginning with v2023.03.*, Pylance started return a generic docstring with no concrete type information (see screenshots below).
```python
import json
from collections.abc import Callable
from functools import wraps
from typing import Any

import stackprinter

# **************************************************
# Example class decorator definition
# **************************************************
class ToyLogExHandler:
    """
    toy example emulating LogExHandler
    """

    def __init__(
        self,
        continue_on_error: bool,
        *,
        is_generator=False,
        **kwargs,
    ):
        self.cont = continue_on_error
        self.is_gen = is_generator
        self.exit_code = kwargs.get("exit_code", -1)
        self.func: Callable[..., Any] | None = None

    def __call__(self, func: Callable[..., Any]):
        self.func = func

        @wraps(func)
        def log_exception_wrapper(*args, **kwargs):
            if self.is_gen:
                return self._gen_wrapper(*args, **kwargs)
            return self._wrapper(*args, **kwargs)
        return log_exception_wrapper

    def _gen_wrapper(self, *args, **kwargs):
        try:
            yield from self.func(*args, **kwargs)
        except Exception as ex:
            print(stackprinter.format())
            if not self.cont:
                raise SystemExit(self.exit_code) from ex

    def _wrapper(self, *args, **kwargs):
        try:
            return self.func(*args, **kwargs)
        except Exception as ex:
            print(stackprinter.format())
            if not self.cont:
                raise SystemExit(self.exit_code) from ex


# **************************************************
# Example wrapped function definition
# **************************************************
@ToyLogExHandler(True)
def fun_test(param1: dict[str, list[int]], param2: bool = True) -> str:
    """super fun!
    
    you're gonna love the str version of that param1 dict, lemme tell ya!
    
    set param2 = False to prevent it from printing..."""
    outpt = json.dumps(param1, indent=2)
    if param2:
        print(outpt)
    return outpt


# **************************************************
# Example of wrapped function usage
# **************************************************
TEST_DICT = {
    "testing": [1, 2, 3]
}
fun_test(TEST_DICT)

```

## LAST GOOD VERSION (works correctly):
Extension version: 2023.2.40
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

Screenshot of desired operation when using 2023.02.40:
![image](https://user-images.githubusercontent.com/47760929/227382867-6473e825-b64a-489d-90fc-ff274c741e47.png)

## BAD VERSION (MOST RECENT):
Extension version: 2023.3.30
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

Screenshot of undesired operation when using 2023.03.30:
![image](https://user-images.githubusercontent.com/47760929/227382391-490b8579-625d-44d3-b45b-9c50797dc4e9.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|27.86GB (13.47GB free)|
|Process Argv|--crash-reporter-id 2c6eb7af-a39a-4eb9-8df9-35a3d26cd51b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30677850
defaultazurewalk:30687958
pythonms35cf:30686773

```
</details><details>
<summary>Python 3.10.4 Environment</summary>

```
anyio==3.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
astroid==2.13.2
asttokens==2.2.1
attrs==22.2.0
backcall==0.2.0
beautifulsoup4==4.11.1
black==22.12.0
bleach==5.0.1
boto3==1.26.46
boto3-stubs[logs,s3,secretsmanager,ses]==1.26.46
botocore==1.29.46
botocore-stubs==1.29.46
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
comm==0.1.2
debugpy==1.6.5
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.6
entrypoints==0.4
et-xmlfile==1.1.0
executing==1.2.0
fastjsonschema==2.16.2
fqdn==1.5.1
future==0.18.2
idna==3.4
ipykernel==6.20.1
ipython==8.8.0
ipython-genutils==0.2.0
isoduration==20.11.0
isort==5.11.4
jedi==0.18.2
jinja2==3.1.2
jmespath==1.0.1
jsonpointer==2.3
jsonschema[format-nongpl]==4.17.3
jupyter-client==7.4.8
jupyter-core==5.1.3
jupyter-events==0.6.0
jupyter-server==2.0.6
jupyter-server-terminals==0.4.4
jupyterlab-pygments==0.2.2
lazy-object-proxy==1.9.0
markupsafe==2.1.1
matplotlib-inline==0.1.6
mccabe==0.7.0
mistune==2.0.4
mypy==0.991
mypy-boto3-logs==1.26.43
mypy-boto3-s3==1.26.0.post1
mypy-boto3-secretsmanager==1.26.40
mypy-boto3-ses==1.26.0.post1
mypy-extensions==0.4.3
nameparser==1.1.2
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.7
nbformat==5.7.1
nest-asyncio==1.5.6
notebook==6.5.2
notebook-shim==0.2.2
numpy==1.24.1
openpyxl==3.0.10
packaging==23.0
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.10.3
pdftotext==2.2.2
phonenumberslite==8.13.4
pickleshare==0.7.5
platformdirs==2.6.2
probableparsing==0.0.1
prometheus-client==0.15.0
prompt-toolkit==3.0.36
psutil==5.9.4
psycopg2-binary==2.9.5
pure-eval==0.2.2
pycparser==2.21
pygments==2.14.0
pylint==2.15.10
pypdf==3.5.0
pyrsistent==0.19.3
python-crfsuite==0.9.8
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.7
pywin32==305
pywinpty==2.0.10
pyyaml==6.0
pyzmq==24.0.1
requests==2.28.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
s3transfer==0.6.0
send2trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
stackprinter==0.2.10
tabulate==0.9.0
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tomlkit==0.11.6
tornado==6.2
tqdm==4.64.1
traitlets==5.8.1
types-awscrt==0.16.3
types-psycopg2==2.9.21.2
types-python-dateutil==2.8.19.5
types-pytz==2022.7.0.0
types-requests==2.28.11.7
types-s3transfer==0.6.0.post5
types-tabulate==0.9.0.0
types-urllib3==1.26.25.4
typing-extensions==4.4.0
uri-template==1.2.0
urllib3==1.26.13
usaddress==0.5.10
wcwidth==0.2.5
webcolors==1.12
webencodings==0.5.1
websocket-client==1.4.2
wrapt==1.14.1
```

</details>

**Comment by shartzog** [comment]
crap, I created this with the "issue report" feature in vscode and thought I'd be given an oppty to update it before it was actually created.  revising to include additional pertinent details.  hold pls... 😅

**Comment by shartzog** [comment]
Hopefully that's a little better lol

**Comment by erictraut** [comment]
Thanks for the bug report. It's difficult to diagnose the problem with such a complex sample. It references a bunch of symbols that are not defined. Do you think you could simplify it and produce a minimal, self-contained sample — along with code that shows how it's used?

There was a significant change recently to the way `functools.wraps` was defined in the typeshed stub `functools.pyi`. This is likely the underlying cause for the change in behavior. The change was made to improve type inference for `functools.wraps`, but it's possible that the change had a negative impact on certain use cases.

**Comment by shartzog** [comment]
Thanks, @erictraut.  Updated issue description with a toy example exhibiting the same behavior.

**Comment by erictraut** [comment]
Thanks for the simplified example. As I suspected, the change is due to the new definition of `wraps` in the `functools.pyi` type stub. This change generally improves type information for functions that use `wraps`. This was one of the [most upvoted pylance feature requests](https://github.com/microsoft/pylance-release/issues/442).

Previously, the type inference logic was unable to determine the proper type for `ToyLogExHandler.__call__` in your code, so it didn't attempt to apply the decorator and assumed that the decorator produced no effect on the decorated function `fun_test`. With the improved `functools.wraps` definition, the type inference logic was able to determine a valid return type for the `__call__` method, and this type was applied. However, the type is based on the signature of `log_exception_wrapper` which is unannotated. This is why you're seeing an effective signature of `(*args, **kwargs)`.

It's unlikely that we would back out the improved `functools.wraps` because it produces better type results in most cases. That means you'll need to work around this issue in your code if you'd like. Here's one way to do this.

```python
T = TypeVar("T", bound=Callable[..., Any])

class ToyLogExHandler:
     ...
    def __call__(self, func: T) -> T:
        ...
```

This tells the type checker that the `__call__` method preserves the signature of the function that is passed to it. Pylance will preserve not only the signature but also the docstring.

**Comment by shartzog** [comment]
Thanks so much for the detailed response @erictraut!  I definitely see the advantage to the enhancement and how my original implementation led to the deficiency.  Playing with your proposed solution now.  Let you know where I end up.

**Comment by shartzog** [comment]
Works like a charm.  Thanks so much, @erictraut!  Closing this one out.

**Comment by Harteg** [comment]
Could someone clarify how the problem was solved? Doc strings are not showing for me, even with explicit types. See screenshot. Thank you. 

![Image](https://github.com/user-attachments/assets/923917b8-0977-497e-a18e-8f05616d8c24)

**Comment by debonte** [comment]
@Harteg, the following approach worked for me. If this doesn't solve your problem, please open a new issue.

```python
from functools import wraps
from typing import Any

def my_decorator(f):
    @wraps(f)
    def func(*args: Any, **kwargs: Any) -> int:
        return f(*args, **kwargs)
    return func

@my_decorator
def foo(a: int) -> int:
    """ This is the docstring """
    return a + 1

foo(1)
```

![Image](https://github.com/user-attachments/assets/6d306cc8-f403-492f-b691-3c6ba676714d)

**Comment by Harteg** [comment]
Hi Erik @debonte , thanks for your input! What I was hoping for was an example showing how wraps helps a decorator preserve a wrapped function’s docstring and metadata when they’d otherwise be lost. So that a wrapper function can include the documentation of the wrapped function without having to retype it. I am not entirely sure what you're trying to show with the example, but `foo()` here is not wrapping any function and the docstrings comes directly from `foo()` itself.

**Comment by debonte** [comment]
@Harteg, please file a new issue.

**Comment by Harteg** [comment]
New issue created #6650
