### ISSUE TITLE
Infinite loop in the chaining of files

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4141]
Go here and look at some of the stacks:
https://microsoft.github.io/pyrx

It looks like we are stuck in a loop going through chained files

RangeError: Maximum call stack size exceeded</br>    at fileToParse <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L987'>pyright-internal/src/analyzer/program.ts:987:23</a></br>    at _parseFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1017'>pyright-internal/src/analyzer/program.ts:1017:13</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>    at _bindFile <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1024'>pyright-internal/src/analyzer/program.ts:1024:17</a></br>    at getScopeIfAvailable <a href='https://github.com/microsoft/pyrx/blob/main/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1045'>pyright-internal/src/analyzer/program.ts:1045:16</a></br>

**Comment by rchiodo** [comment]
Maybe we need to check recursion in this situation. It's not entirely clear it's chained files, but that is where we've made changes recently.

**Comment by erictraut** [comment]
I think this problem might be explained by a bug that I fixed last week: https://github.com/microsoft/pyright/commit/ae873e49dd0e613097dac26d6d0a0a2beb5309e1. If I'm correct, then this problem should disappear from the telemetry with this week's prerelease build.

**Comment by rchiodo** [comment]
I don't see this same stack in the prerelease from the week before but maybe we just didn't have anybody hitting it.

**Comment by erictraut** [comment]
The bug that I fixed was introduced via pylance on Jan 4: https://github.com/microsoft/pyright/commit/b78a9e4bd305f0378c230cf2139a462acd38d03b.
