### ISSUE TITLE
macOS `toggleSuggestionDetails` not working if Pylance is working

### ISSUE THREAD

**Issue by SimiPixel** [microsoft/pylance-release#4145]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:53:46.528Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes
- OS Version: macOS 13.2.1

Steps to Reproduce:

1. open up a jupyter-notebook in VSCode
2. then CTRL + Space only toggles suggestionDetails if Pylance somehow doesn't work yet..

I have made a video that showcases the problem
https://faubox.rrze.uni-erlangen.de/getlink/fiLiLpb8RVWrhQKwbCJg4q/Screen%20Recording%202023-03-23%20at%2013.53.49.mov

Edit: Sorry apparently you have to download the video in order to view it..

**Comment by debonte** [comment]
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by SimiPixel** [comment]
Language Server Log:
https://gist.github.com/SimiPixel/cede3315e6fe23ce9321487ea3147242

Jupyter Extension Log: (<- there is an error in this one, maybe connected? "re-starting notebook takes ~10s")
https://gist.github.com/SimiPixel/7cc131a901ab4838d63ba7e73ae79cf1

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023341-29-March-2023-PreRelease)
