### ISSUE TITLE
Dataclasses get flagged when used as types.

### ISSUE THREAD

**Issue by sldion-rubikloud** [microsoft/pylance-release#415]
When trying to get type inference using classes that have the dataclass decorator this error often gets flagged:
```
Expected class type but received "(p0: AnyType) -> DataclassType | DataclassType"
  "(p0: AnyType) -> DataclassType" is not a class
  "DataclassType" is not a class Pylance (reportGeneralTypeIssues)
```
I am not sure if this is the expected behaviour or not, and not sure how to resolve it.

**Comment by judej** [comment]
@sldion-rubikloud, thanks for the report, would you please add a code snippet that shows the code and error?
thanks

**Comment by sldion-rubikloud** [comment]
I think this is my mistake. It looks to be problem specifically with importing dataclass from the Pydantic python project https://pydantic-docs.helpmanual.io/usage/dataclasses/
I'll close the issue.
Thanks!
