### ISSUE TITLE
Crash within `getRegionCommentType`

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4157]
High-hitting crash in 2023.3.30.

Error: Debug Failure. False expression.    

- at itemIndex <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/positionUtils.ts#L27'>pyright-internal/src/common/positionUtils.ts:27:11</a>    
- at hashOffset <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/regions.ts#L49'>pyright-internal/src/analyzer/regions.ts:49:49</a>    
- at getRegionCommentType <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/regions.ts#L31'>pyright-internal/src/analyzer/regions.ts:31:42</a>   
- at nodeType <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pylance-internal/src/pytest/extension.ts#L510'>pylance-internal/src/pytest/extension.ts:510:33</a>    
- at _checkRegions <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/checker.ts#L299'>pyright-internal/src/analyzer/checker.ts:299:13</a>   
- at check <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/sourceFile.ts#L1401'>pyright-internal/src/analyzer/sourceFile.ts:1401:28</a>   
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a>    
- at timeOperation <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/sourceFile.ts#L1392'>pyright-internal/src/analyzer/sourceFile.ts:1392:44</a>    
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/sourceFile.ts#L1390'>pyright-internal/src/analyzer/sourceFile.ts:1390:32</a>    
- at check <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1228'>pyright-internal/src/analyzer/program.ts:1228:39</a>    
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>    
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>   
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>   
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>    
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>    
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>    
- at callback <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a>    
- at log <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1169'>pyright-internal/src/analyzer/program.ts:1169:32</a>    
- at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/f79f9a6f1d8360ede9eae01ccbe81b836e241b4c/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1215'>pyright-internal/src/analyzer/program.ts:1215:33</a>

**Comment by erictraut** [comment]
It looks like this stack trace can occur only in IPython mode.

The code in `_checkTypes` doesn't seem to deal with import cycles. There's no recursion check.

**Comment by heejaechang** [comment]
cycle is supposed to be checked when notebook is created/changed and verified so that we don't need to recheck it every time. no one else is supposed to change the chaining (imported by)

this call path can only happen for notebook cell, and notebook cell can't be explicitly imported by other files, so only the implicit chaining with cycle seems to be able to cause this. 

since we have this other issue - https://github.com/microsoft/pylance-release/issues/4141 - it feels like there is some bug around notebook create/change code and cycle detection code.

**Comment by heejaechang** [comment]
this seems another reason to start forcing our code on immutability for state that are not supposed to be changed.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.3.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023341-29-March-2023-PreRelease)
