### ISSUE TITLE
Folding is not working correctly for `#region` surrounded by imports

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#4159]
## Environment data

-   Language Server version: v2023.3.30 / v2023.3.31 Pre-Release
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.10

## Code Snippet

```python
# Blah, blah, blah...

import module_a
# region
import module_b
# endregion
```

## Repro Steps

See "Code snippet".

## Expected behavior

Line `import module_a` is not foldable (because it's one line). And if there were multiple lines, the folding should stop before `# region`.

Or maybe there could be an option to disable folding of imports.

## Actual behavior

![image](https://user-images.githubusercontent.com/15389744/228169188-10b92a85-7cec-4ddc-ba5b-676d5570de17.png)
![image](https://user-images.githubusercontent.com/15389744/228169239-e8101878-e23f-44d7-8cc6-5bf09e978cb2.png)

## Logs

I haven't seen anything interesting.

**Comment by Azureblade3808** [comment]
Folding is still working strangely on following sample --
```python
import module_a
# region
import module_b
a = 0
# endregion
```

![image](https://user-images.githubusercontent.com/15389744/231917312-725703c2-d9fe-4432-957f-3a066fefd39d.png)
![image](https://user-images.githubusercontent.com/15389744/231917333-5e221bab-4e89-490d-87e9-fea2e6535d7a.png)

**Comment by debonte** [comment]
Yes, you're hitting a limitation of VS Code's folding system. It doesn't support interleaved regions. There's more info on this [here](https://github.com/microsoft/pylance-release/issues/3290#issuecomment-1242654484). For what it's worth, Visual Studio does handle interleaved regions (it shows folding controls for both regions in this scenario), but VS Code does not.

Here's another example that exhibits the same behavior:

```python
def func1():
#region
    pass

a = 0
#endregion
```

We could special case this for imports by splitting the imports into two folding ranges (before and after the `#region`), but it's not clear to me that this is an important scenario to handle. I'd want to see a strong indication from users that this was valuable before investing time there.

**Comment by DarioDaF** [comment]
Just wanted to add for further people discovering this, it works until the imports get processed then the collapse button disappers, a bit annoying for having blocks of imports
