### ISSUE TITLE
Switching kernels in a notebook made pylance stop working

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4166]
Open a notebook
See that pylance works in the notebook
Switch kernels

Expected:
Pylance works

Actual:
Semantic tokenization goes away and pylance no longer returns anything.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.4.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023411-5-April-2023-PreRelease)

**Comment by Auxority** [comment]
Works for me :+1:
