### ISSUE TITLE
pillow has no code complements

### ISSUE THREAD

**Issue by Byxs20** [microsoft/pylance-release#4168]
你好，很抱歉打扰到您，我想要问一个问题。

我这边使用 `Image.open()` 或者 `Image.new` 打开图像都不能自动识别到类型，识别不到类型就没有对应的智能补全了。

code --version: 1.72.2 d045a5eda657f4d7b676dedbfa7aab8207f8a075 x64
Python version: 我从3.8.8换到3.8.10再换到3.9.13
Pillow version: 9.4.0
vscode-Python version: v2022.16.1
vscode-Pylance version: v2023.1.10

![image](https://user-images.githubusercontent.com/64669718/228824054-234b1b86-6c4c-45d3-a3f2-51f11846ee37.png)

**Comment by bschnurr** [comment]
Sorry I couldn't repo. please update to the latest Pylance v2023.3.40  and try again

**Comment by Byxs20** [comment]
![image](https://user-images.githubusercontent.com/64669718/228994486-17115687-c97f-467b-bec1-3ef3fcc732b1.png)

code version: 1.77.0
7f329fe6c66b0f86ae1574c2911b681ad5a45d63
x64

vscode-Python: v2023.6.0
vscode-Pylance: v2023.3.40
python version: 3.8.10

It's still the same as before. May I ask you what else I can do to find the core of the problem?

**Comment by rchiodo** [comment]
Sorry that it's still broken.

This is what I get:
![image](https://user-images.githubusercontent.com/19672699/229176646-7d5b288c-5a29-4670-9b01-6cf2349cd272.png)

The logs as described here would help us diagnose the problem:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by Byxs20** [comment]
This is what happened when I opened my previous project:
[Info  - 01:08:49] (16480) Pylance language server 2023.3.40 (pyright 04471971) starting
[Info  - 01:08:49] (16480) Server root directory: c:\Users\97766\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist
[Info  - 01:08:49] (16480) Starting service instance "5.贪吃蛇的秘密2.0"
[Info  - 01:08:49] (16480) Auto-indent enabled
[Info  - 01:08:49] (16480) No configuration file found.
[Info  - 01:08:49] (16480) No pyproject.toml file found.
[Info  - 01:08:49] (16480) Setting pythonPath for service "5.贪吃蛇的秘密2.0": "D:\Python\python.exe"
[Warn  - 01:08:49] (16480) stubPath f:\CTF题目\ctfshow_大牛杯\5.贪吃蛇的秘密2.0\typings is not a valid directory.
[Info  - 01:08:49] (16480) Assuming Python version 3.8
[Info  - 01:08:49] (16480) Assuming Python platform Windows
[Info  - 01:08:49] (16480) Searching for source files
[Info  - 01:08:49] (16480) Found 1 source file
[Info  - 01:08:49] (16480) Background analysis(1) root directory: c:\Users\97766\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist
[Info  - 01:08:49] (16480) Background analysis(1) started
[Info  - 01:08:49] (16480) Indexer background runner(2) root directory: c:\Users\97766\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist (index)
[Info  - 01:08:49] (16480) Indexing(2) started
[Info  - 01:08:50] (16480) scanned(2) 323 files over 1 exec env
[Info  - 01:08:52] (16480) [IDX(2)] Long operation: index execution environment f:\CTF题目\ctfshow_大牛杯\5.贪吃蛇的秘密2.0 (2670ms)
[Info  - 01:08:52] (16480) [IDX(2)] Long operation: index packages f:\CTF题目\ctfshow_大牛杯\5.贪吃蛇的秘密2.0 (2675ms)
[Info  - 01:08:52] (16480) indexed(2) 229 files over 1 exec env
[Info  - 01:08:52] (16480) Indexing finished(2).

But I just created a new demo folder on my desktop and then opened the folder with Vscode, and there was no problem

[Info  - 01:08:14] (10976) Pylance language server 2023.3.40 (pyright 04471971) starting
[Info  - 01:08:14] (10976) Server root directory: c:\Users\97766\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist
[Info  - 01:08:14] (10976) Starting service instance "demo"
[Info  - 01:08:14] (10976) Auto-indent enabled
[Info  - 01:08:14] (10976) No configuration file found.
[Info  - 01:08:14] (10976) No pyproject.toml file found.
[Info  - 01:08:14] (10976) Setting pythonPath for service "demo": "D:\Python\python.exe"
[Warn  - 01:08:14] (10976) stubPath c:\Users\97766\Desktop\demo\typings is not a valid directory.
[Info  - 01:08:14] (10976) Assuming Python version 3.8
[Info  - 01:08:14] (10976) Assuming Python platform Windows
[Info  - 01:08:14] (10976) Searching for source files
[Info  - 01:08:14] (10976) Found 1 source file
[Info  - 01:08:15] (10976) Background analysis(1) root directory: c:\Users\97766\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist
[Info  - 01:08:15] (10976) Background analysis(1) started
[Info  - 01:08:15] (10976) Indexer background runner(2) root directory: c:\Users\97766\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist (index)
[Info  - 01:08:15] (10976) Indexing(2) started
[Info  - 01:08:15] (10976) scanned(2) 323 files over 1 exec env
[Info  - 01:08:18] (10976) [IDX(2)] Long operation: index execution environment c:\Users\97766\Desktop\demo (2689ms)
[Info  - 01:08:18] (10976) [IDX(2)] Long operation: index packages c:\Users\97766\Desktop\demo (2694ms)
[Info  - 01:08:18] (10976) indexed(2) 229 files over 1 exec env
[Info  - 01:08:18] (10976) Indexing finished(2).

I'm not quite sure why a new project is fine, Can you tell me why this is happening? Thanks!

**Comment by rchiodo** [comment]
Might be the folder name. Your old folder name has none ascii characters in it. Let me try that myself.

**Comment by rchiodo** [comment]
No that works for me. 

What happens when you goto definition on `PIL` in the old project?

**Comment by Byxs20** [comment]
In the old project:
I held down ctrl + left mouse button to go to the following directory:
D:\Python\Lib\site-packages\PIL\Image.py

Pressing and holding PIL will go to
D:\Python\Lib\site-packages\PIL\__init__.py

But in my new project it also jumps to the same py file as in the old project

**Comment by rchiodo** [comment]
In the image.py file, what does the definition of `open` look like? You're using python 3.8, so maybe the problem is it doesn't match the bits here:

`<user root>\.vscode\extensions\ms-python.vscode-pylance-2023.3.40\dist\typeshed-fallback\stubs\Pillow\PIL\__init__.pyi`

**Comment by rchiodo** [comment]
Your `__init__.pyi` only has 3 lines in it?

**Comment by Byxs20** [comment]
Sometimes it works for me, sometimes it doesn't prompt intelligently, I can create a new project, but not my old project before, I'm not sure why

def open(
    fp: str | bytes | Path | SupportsRead[bytes], mode: Literal["r"] = ..., formats: list[str] | tuple[str, ...] | None = ...
) -> Image: ...

**Comment by rchiodo** [comment]
Can you set this setting to "trace" and try again? The log may show something else. It might be the old project has too many files and we're bailing out early:

```json
"python.analysis.logLevel": "Trace"
```

**Comment by Byxs20** [comment]
[info.txt](https://github.com/microsoft/pylance-release/files/11140725/info.txt)

**Comment by rchiodo** [comment]
And it's not working after that runs? Looks like it indexed a lot of stuff but should have finished after 2 seconds or so. It should be working after the 2 seconds are up.

**Comment by rchiodo** [comment]
I think we'd need to repro locally to figure out what the problem is at this point.

Is there anything else that you have different between the two projects besides the name of the folder?

**Comment by Byxs20** [comment]
I'll see if I can take some time to study it tomorrow. In fact, I don't know why sometimes I can and sometimes I can't. So I was thinking about changing an IDE tool some time ago, and I'm going to change to pycharm.

**Comment by Byxs20** [comment]
![image](https://user-images.githubusercontent.com/64669718/229678714-2eb8cd69-f8b0-4f35-a97d-2e34ca32ea29.png)
![image](https://user-images.githubusercontent.com/64669718/229678755-0c86dc62-5d68-4476-ba41-1bb023192307.png)
