### ISSUE TITLE
Auto-import is suggesting completions from local files rather than library

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#4179]
Something must have recently changed in the completion provider. I recently started to receive auto-import completion suggestions for stdlib symbols like `TypeVar` or `overload` that suggest importing these symbols from local files that happen to also import these symbols rather than the library that exports them.

To repro:
1. Disable indexing (or use the Pyright VS Code extension).
2. Create a new project and create a file called "test1.py". Within that file, type `from typing import TypeVar`.
3. Create a new file called "test2.py". Start typing `TypeVar`. Prior to completing the word, wait for a completion suggestion. Note that the top suggestion is `from test1 import TypeVar`. The completion provider should not be suggesting this.

![image](https://user-images.githubusercontent.com/7040122/229198697-e89a0596-94ca-40a4-b218-39b7c88cd852.png)

This regression appears to have been introduced into the pyright code base from pylance after the latest release of pyright (1.1.301). I've bisected it to [this commit](https://github.com/microsoft/pyright/commit/d7616109825416235ee6516165ce90600b1ae604).

This regression makes it very difficult to use the auto-import feature.

**Comment by bschnurr** [comment]
pylance commit https://github.com/microsoft/pyrx/commit/7172be36b5e6ceb222f8acf52cd1779718aaffd2

**Comment by erictraut** [comment]
Thanks for isolating the change, @bschnurr. Perhaps we should simply revert this change to fix the regression until @heejaechang has time to work on a fix?

**Comment by erictraut** [comment]
Looking at the [bug that prompted this change](https://github.com/microsoft/pyrx/pull/3316), I'm not convinced it was a bug to begin with. I don't think we should be including symbols aliased in user files as part of auto-import. The old logic seems correct to me.

**Comment by bschnurr** [comment]
ok. i'll revert for now

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.4.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023411-5-April-2023-PreRelease)
