### ISSUE TITLE
Time is not accessed by pylance

### ISSUE THREAD

**Issue by llwafflesll** [microsoft/pylance-release#4180]
so i have this code for my game but it says "time not accessed by pylance" when i hover over the time
![Screenshot from 2023-04-01 09-51-41](https://user-images.githubusercontent.com/102574383/229265386-cc46eaef-8e46-46e9-969e-9cf5b8af0a72.png)

**Comment by rchiodo** [comment]
That means Pylance thinks you're not using it in that file. From the screenshot, that looks to be true to me, but it could be used in code off the screen.

What's the entire contents of the file?

**Comment by llwafflesll** [comment]
Thank you, do you want me to send u the entire code

**Comment by rchiodo** [comment]
Yes, pylance is correct. You are not referencing the `time` module anywhere. You can remove it from the file and the game will still run.

Perhaps you thought this was a reference to time?

```python
clock = pygame.time.Clock
```

That's actually a reference to the pygame submodule, called `pygame.time`. If that's confusing, this might help: https://docs.python.org/3/tutorial/modules.html#packages

**Comment by llwafflesll** [comment]
Awesome, thanks!

**Comment by llwafflesll** [comment]
but its staying only for a mili second
not any longer it comes and vinishes
