### ISSUE TITLE
Autocomplete for CV2 and numpy stopped working after update to Vscode or Pylance 

### ISSUE THREAD

**Issue by theunknowninfinite** [microsoft/pylance-release#4186]
## Environment data

-   Language Server version: 2023.3.40
-   OS and version: Windows 10 22H2 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.8
-   Pylance version - 54,314,145 (2023.3.40)
-   OpenCV version - 4.7.0.72
-   Using python virtual environments and interpreter set to a virtul env. 

## Code Snippet

![image](https://user-images.githubusercontent.com/68436564/229510411-f75c3edb-a83d-4432-9e47-c431eee8ce47.png)
![image](https://user-images.githubusercontent.com/68436564/229510528-b5250b3c-95b5-44bd-8642-898298b1fdf9.png)

## Repro Steps

1. import cv and numpy as np. Typing cv2. and trying to do autocomplete does not show any available functions.

## Expected behavior

Show a list of Cv2 and numpy functions  available.

## Actual behavior

Says no functions found. 

This used to work before my vscode updated itself to the march release. 

## Troubleshooting 
Tried adding "python.autoComplete.extraPaths" to setting.json as suggested on stackoverflow 
Tried reinstalling OpenCV using terminal

Edit: Similar behaviour to this - https://github.com/microsoft/pylance-release/issues/4072

**Comment by judej** [comment]
Please reopen if this persists. Also, add the information that Heejae requested.
