### ISSUE TITLE
Can't recognize the replacement of module or class method.

### ISSUE THREAD

**Issue by kong13661** [microsoft/pylance-release#4187]
## Environment data

-   Language Server version: Pylance language server 2023.3.40
-   OS and version: ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9

## Code Snippet

```python
import pandas as pd
from pandas.core.api import DataFrame as DataFrame_

class DataFrame(DataFrame_):
    @property
    def field_names(self):
        return self.columns


pd.DataFrame: DataFrame
pd.DataFrame = DataFrame
df = pd.DataFrame()

print(df.field_names)
```

## Expected behavior

df has method field_names now, and pylance should include the method.

## Actual behavior

![image](https://user-images.githubusercontent.com/28509442/229515531-eac811ee-2fe7-45a0-bddb-d386f4a13e88.png)

In fact, if I replace line 17 with df = pd.DataFrame, it work properly.

![image](https://user-images.githubusercontent.com/28509442/229516039-2ddff13f-0c15-4f8b-8488-551a53db810d.png)

Besides, if a add a method directly to the class, pylance also ignore the change.

![image](https://user-images.githubusercontent.com/28509442/229516591-105dada8-79eb-42bf-b4ee-82529aac9ec5.png)

In this code, pylance should realize the method aaa.

**Comment by bschnurr** [comment]
I think you need to add an `__init__` or `__new__` function to your child `Dataframe` class.
see https://stackoverflow.com/questions/10788976/how-do-i-properly-inherit-from-a-superclass-that-has-a-new-method

```python

from pandas.core.api import DataFrame

class MyDataFrame(DataFrame):
    @property
    def field_names(self):
        return self.columns

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        

x = MyDataFrame()

print(x.field_names)
```

**Comment by kong13661** [comment]
> @bschnurr, this isn't related to an `__init__` method.
> 
> @kong13661, you are dynamically overwriting a symbol in a library module. Yikes!!! This form of patching is not recommended because it breaks encapsulation and leads to fragile code. Cross-scope patching is not supported by static type checkers. A dynamic language like Python permits this sort of patching, but your code will not type check, nor will you get type completion hints based on the patched symbols.
> 
> You can make normal use of the local symbol `DataFrame` which uses `pd.DataFrame` as a base class.

But, even I dosen't overwriting the symbol, it can't work properly.

Look at this code:

``` Python
import pandas as pd


class DataFrame(pd.DataFrame):
    @property
    def field_names(self):
        return self.columns


df = DataFrame()

print(df.field_names)
```

I create a subclass from pd.DataFrame and instantiates it, and pylance can't find the symbol belongs to subclass.

![image](https://user-images.githubusercontent.com/28509442/229693552-161b3a10-ba66-4e0e-925c-c8cc46019b5e.png)

It seems to be caused by the stub. I think pylance think the type of subclass is pd.DataFrame but not it's subclass, and it use stub of pd.DataFrame directly. But I think the symbol of the subclass should be recognized.

**Comment by kong13661** [comment]
> @bschnurr, this isn't related to an `__init__` method.
> 
> @kong13661, you are dynamically overwriting a symbol in a library module. Yikes!!! This form of patching is not recommended because it breaks encapsulation and leads to fragile code. Cross-scope patching is not supported by static type checkers. A dynamic language like Python permits this sort of patching, but your code will not type check, nor will you get type completion hints based on the patched symbols.
> 
> You can make normal use of the local symbol `DataFrame` which uses `pd.DataFrame` as a base class.

Thanks, it works. But it looks strange. 

Besides, dynamically adding method dosen't work properly. Look at code below:

``` Python
import pandas as pd


def add_column(self, column_name=None, column=None):
    if column is None:
        column = np.NaN
    if column_name is None:
        self[len(self.columns)] = column
    else:
        self[column_name] = column


pd.DataFrame.add_column = add_column
pd.DataFrame.add_column
```

![image](https://user-images.githubusercontent.com/28509442/229695480-64c94b74-a3fa-4813-8c76-bdfbd37b168e.png)

May dynamic analises be hard for python?

**Comment by heejaechang** [comment]
That kind of dynamic behavior won't be supported by language services that use static type information. If you want a tool that supports such dynamic behavior, you should consider using tools like notebooks, which will have access to the necessary information once the cells are executed.

**Comment by heejaechang** [comment]
this sounds like a bug - https://github.com/microsoft/pylance-release/issues/4187#issuecomment-1495359876

can you open a new issue? 

when there is no explicit `__init__`, we think type is the one that has `__init__, not the one explicitly used to create the object.

**Comment by heejaechang** [comment]
by the way, until we fix the issue, you can explicitly add `__init__` 

```python
import pandas as pd

class DataFrame(pd.DataFrame):
     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)

    @property
    def field_names(self):
        return self.columns

df = DataFrame()
print(df.field_names)
```

**Comment by erictraut** [comment]
This appears to be a bug in the pandas type stubs that ship with pylance. The return type of the `DataFrame.__new__` method should be annotated as `typing.Self`, but it's incorrectly annotated as `DataClass`. This results in incorrect type evaluation when the constructor for a subclass of `DataFrame` is invoked.
