### ISSUE TITLE
[Feature requests] Support for metaclass keyword

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/pylance-release#4189]
The code hint that when I specifies the metaclass

![image](https://user-images.githubusercontent.com/96709586/229287098-5532ac9f-7327-49e1-9b3c-c8571330c72e.png)

**Comment by bschnurr** [comment]
Can you give some more details?

are you expecting `metaclass=` to trigger a completion?

**Comment by CoolPlayLin** [comment]
I was already ignored😢
