### ISSUE TITLE
Using `display` in a notebook requires a kernel be selected that has IPython installed

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4193]
Have a cell like so:

```python
display('foo')
```

You'll get an error in VS code until you actually install IPykernel into the selected kernel:

![image](https://user-images.githubusercontent.com/19672699/229646607-42edeeea-c376-4396-95eb-8067d973e106.png)

From a notebook user's point of view this feels like a bug. You never have to import anything to use `display`.

I feel like `display` should be treated like a system library and not a 3rd party library that needs an environment for it to be recognized. 

For a notebook user, `display` is equivalent to `print` which doesn't require a kernel to be setup.

**Comment by debonte** [comment]
- There are other symbols exposed by IPykernel other than `display` (ex. `display_pretty`). Will we special case those also?
- Could there be issues where our special-case view of IPykernel is out-of-sync (different version, different symbols) with the version they will eventually install?

**Comment by rchiodo** [comment]
> There are other symbols exposed by IPykernel other than display (ex. display_pretty). Will we special case those also?

Yeah everything that's default included in a notebook. Essentially a notebook does `from IPython import *` at the top of every cell.

> Could there be issues where our special-case view of IPykernel is out-of-sync (different version, different symbols) with the version they will eventually install?

Not very likely in my opinion. This is like typesheds being out of date with the system libraries. IPython display hasn't changed in a long time. Maybe more overloads are added as time goes on.

**Comment by luabud** [comment]
I agree. If it doesn't lead to errors at runtime, I think ideally we wouldn't show it as an error. 
I understand reservations against special casing individual modules, but what would be the implications of special casing the entire package? This would be coming from the point of view that we want to provide 1st class Jupyter notebooks support and Jupyter has a strong dependency on `IPykernel`.

**Comment by rchiodo** [comment]
If we had a 'typeshed' module for IPython and we shipped it next to the other ones, the changes shouldn't be too bad? We have to treat IPython like builtins I think.

**Comment by erictraut** [comment]
Pyright already provides the ability for a user to extend `builtins.pyi`.  See [this documentation](https://microsoft.github.io/pyright/#/builtins) for details. This same mechanism could be used to inject IPython symbols into builtins.

**Comment by luabud** [comment]
We're planning to add type stubs for IPython, as it would be enough to take care of this problem given there's no explicit imports. We should also document all the typestubs we bundle in Pylance in a single place, to make it more easily accessible.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.5.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023551-31-May-2023-PreRelease)
