### ISSUE TITLE
Go to Definition does not work for Jupyter notebooks

### ISSUE THREAD

**Issue by deepettas** [microsoft/pylance-release#4195]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: "go to definition" command should work, both on hover as well as the actual function that transports you to the function/class definition

Actual: "No definition found for X" where X is a function outside of the notebook or class (pip installed packages)

Note: This functionality works in "main.py" python scripts on the current setup.

## Steps to reproduce:

1. Open jupyter notebook
2. Import any package
3. Try going to the function or class definition

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

condaPath: "<placeholder>"

languageServer: "Pylance"

formatting
• provider: "black"

```

</p>
</details>

Extension version: 2023.6.0
VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:55:48.214Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id e848645e-7248-435f-bc0e-1cc6858c3ee9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30677849
vscodedisable:30660115
pythonb192cf:30669361
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue.

My guess is you don't have a kernel selected (or one that points to an unknown environment). 

![image](https://user-images.githubusercontent.com/19672699/229874278-9595d81d-eec1-4a32-9e18-de48ad450aae.png)

We need a kernel so that we know what environment to do the goto definition in.

If you think the correct kernel is selected, but it still doesn't work, can you add the logging for the Pylance extension?

Directions are here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by tikendraw** [comment]
Using 

> Thanks for the issue.
> 
> My guess is you don't have a kernel selected (or one that points to an unknown environment).
> 
> ![image](https://user-images.githubusercontent.com/19672699/229874278-9595d81d-eec1-4a32-9e18-de48ad450aae.png)
> 
> We need a kernel so that we know what environment to do the goto definition in.
> 
> If you think the correct kernel is selected, but it still doesn't work, can you add the logging for the Pylance extension?
> 
> Directions are here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

I am currently running in that kernel and it says "definition not found in x", 
I have also tried starting jupyter server in llamaindex venv and adding jupyter server in notebook. still doesn't work. 
![tmp-1723643590647](https://github.com/user-attachments/assets/357ce082-a294-4fea-b430-517a4659baf9)

**Comment by tikendraw** [comment]
Found the solution. 

1. go to settings

2. search language sever

3. change the python language server from jedi to pylance,
