### ISSUE TITLE
Error when trying to turn on type checking - Failed to update setting 'python.analysis.typeCheckingMode'.  Error: Unable to write to Folder Settings because no resource is provided.

### ISSUE THREAD

**Issue by TeamDman** [microsoft/pylance-release#4199]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I click the "Type Checking: off" button, and it shows 
Failed to update setting 'python.analysis.typeCheckingMode'.  Error: Unable to write to Folder Settings because no resource is provided.
Source: Pylance (Extension)

## Steps to reproduce:
I have this file tree on disk

FolderA
- FolderB
- - diagrams.ipynb

I have the workspace opened with folderB as its own folder in the workspace
- FolderA
- FolderB

I have to open FolderB as its own thing in the workspace because vscode doesn't discover virtualenvs that aren't in the root of workspace folders.

Steps:

1. open diagrams.ipynb
2. Click "Type Checking: off" in the bottom of VSCode, might be "{}" button if it hasn't been pinned yet.

![image](https://user-images.githubusercontent.com/9356891/230123164-e01091ae-d101-4720-8a65-40a649bdaf24.png)

![image](https://user-images.githubusercontent.com/9356891/230123689-b9566f81-c4e7-4c5e-baed-d5f3c5706069.png)

Saving the workspace so it's no longer untitled doesn't resolve the error.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Telemetry level is off
Experiments are disabled, only manually opted experiments are active.
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: C:\Python39\python.exe
> ~/source/repos/SelfServicePortal-Infrastructure-as-Code/diagrams/venv/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/printEnvVariables.py
> ~/source/repos/SelfServicePortal-Infrastructure-as-Code/diagrams/venv/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/printEnvVariables.py
> ~/source/repos/SelfServicePortal-Infrastructure-as-Code/diagrams/venv/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/printEnvVariables.py
> ~/source/repos/SelfServicePortal-Infrastructure-as-Code/diagrams/venv/Scripts/activate.bat && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2023.4.1/pythonFiles/printEnvVariables.py
> C:\Python39\python.exe -I ~\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\interpreterInfo.py
> ~\source\repos\SelfServicePortal-Infrastructure-as-Code\diagrams\venv\Scripts\python.exe -I ~\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2023.4.1\pythonFiles\interpreterInfo.py
Starting Pylance language server.
Jupyter provided interpreter path override: c:\Users\PHILDOM\source\repos\SelfServicePortal-Infrastructure-as-Code\diagrams\venv\Scripts\python.exe

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.3.40
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bschnurr** [comment]
was your settings.json file open already in an unsaved state?

**Comment by TeamDman** [comment]
no, it was happening with just the notebook open

**Comment by rchiodo** [comment]
I can't seem to replicate this. Some other extension may have written to the settings at the same time?

**Comment by lightshadower** [comment]
I resolved the same error by changing the setting on Python>Analysis: **Type Checking Mode** from _off_ to _basic_.
I hope it helps.
