### ISSUE TITLE
matplotlib: Expected no arguments to "Line2D" constructor

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#420]
## Environment data

-   Language Server version: Pylance language server 2020.9.6 (pyright c52b78aa) 
-   OS and version: macOS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.8

## Expected behaviour

No `reportGeneralTypeIssues` error. See [Line2D docs](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.lines.Line2D.html?highlight=line2d)

## Actual behaviour

```
Expected no arguments to "Line2D" constructor
```

## Code Snippet / Additional information

```python
from matplotlib.lines import Line2D

line = Line2D([0], [0], lw=10)
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202130-3-march-2021
