### ISSUE TITLE
Don't put 2 lines between variables when moving symbol.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#4202]
Currently, when moving a symbol, regardless of the type of symbol, it put 2 lines before or after the symbol.

It should not do that if the symbol it is moving is `variable` and symbol before or after it is also `variable`

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.4.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023421-12-April-2023-PreRelease)
