### ISSUE TITLE
Finding all references to the __init__ function and the class name shows different results.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/pylance-release#4205]
## Environment data

- Build of Visual Studio Code - Insiders:1.78.0-insider  
- Build of python-insider: v2023.7.10951006 
- Build of pylance-insider: v2023.4.11 

## Code Snippet

**test.py**
```python
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

```
**file1.py**
```python
from test import Person
person1 = Person("John", 25)
```
**file2.py**
```python
from test import Person
person2 = Person("Alice", 30)
```
## Repro Steps

1. Open a new python file
2. Create a class in that python file with an __init__ method.
3. Open two other python files
4. Import the first file in each
5. Create a variable by constructing the class in the two other files
6. Go back to the first file
7. Find all references on the class
8. Verify it finds the two creations in the other files
9. Go back to the first file
10. Find all references on the __init__ function
11. Verify it finds the same references as searching for the class name

## Expected behavior

The results show the same.

## Actual behavior

Find all references on the class

![image](https://user-images.githubusercontent.com/82852072/230323882-fb761ac2-9c04-4e11-9f0c-e1d6874e5674.png)

Find all references on the __init__ function. It's not the same references as searching for the class name.

![image](https://user-images.githubusercontent.com/82852072/230324024-4a4dab9f-2301-49bf-ad9c-c1fc9b069566.png)

**Comment by rchiodo** [comment]
I believe our test plan may reference these exact steps. I'll update the test plan.
