### ISSUE TITLE
Unable to recognize element type in a tuple when the tuple is built from `zip`

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [microsoft/pylance-release#4206]
<h3> Environment data </h3>

-   Language Server version: 2023.4.10
-   OS and version: darwin arm64
-   Python version: 3.9.12 (miniconda py39_4.12.0)
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
def func(i: int):
    # return the integer, and whether it is an even number
    return i, (i % 2 == 0)

nums, evenQ = zip(*[
    func(i) for i in range(10)
])
```

<h3> Expected behavior </h3>

The type of `nums` and `evenQ` should be recognized as `tuple[int, ...]` and `tuple[bool, ...]`, respectively.

<h3> Actual behavior </h3>

But Pylance only label them as `tuple[int | bool]`.

**Comment by erictraut** [comment]
You can see the type definition for `zip` by right clicking on it and selecting `Go to declaration`. This will take you to the typeshed stub `builtins.pyi`. Note that `zip` is an overloaded function, so it has multiple signatures.

Unfortunately, the Python type system isn't able to fully express the behavior of `zip` in all cases. The type definition handles most cases, but there are situations when the star operator is used where it causes type checkers to produce the wrong results. This is a [known issue](https://github.com/python/typeshed/issues/9143), but it's not clear that there's any good solution short of making changes to the Python static type system.
