### ISSUE TITLE
"'module' is not accessed" occurs occasionally 

### ISSUE THREAD

**Issue by Rhizome-system** [microsoft/pylance-release#4210]
![bug](https://user-images.githubusercontent.com/106471316/230426726-b8c7cb38-9db0-449e-b69b-eb4138a95ddd.png)

I write two notebooks in the same fold and using the same Jupyter kernel, when I import the Dataset class, one is accessible and the other tells me "is not accessed. The former code runs well and later one crushed, how can I fix this problem

**Comment by rchiodo** [comment]
The second one is not accessing the Dataset class, it is creating a parameter named 'Dataset' for a function called `myda`

What you probably want is this:

```python
class myda(Dataset):
   ...
```
