### ISSUE TITLE
Type annotations of metaclass `__getitem__` are not considered

### ISSUE THREAD

**Issue by hanjinliu** [microsoft/pylance-release#4217]
## Environment data

-   Language Server version: 2023.4.10 (pyright d7616109) 
-   OS and version: Windows 11 Home
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.10.8 (anaconda)

## Code Snippet

```python
from typing import TypeVar

T = TypeVar("T")

class Meta(type):
    def __getitem__(self, key: type[T]) -> type[T]:
        return key

class A(metaclass=Meta):
    pass

def f(x: A[str]):
    return x  # <--- type of `x` is inferred as `A`, not `str`
```

![スクリーンショット (8)](https://user-images.githubusercontent.com/40591297/230753018-a9f588cb-dfa4-475f-b7e8-906d28093975.png)

It worked well before (I think a few months ago) but I don't remember the version of pylance at that time.

## Logs

The entire logs were too long. Here's the logs printed out when I hoverred the cursor over the `x`

<details><summary>log</summary><div>

```
(3032) [FG] parsing: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\typing.pyi [fs read 5ms] (34ms)
(3032) [FG] binding: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\typing.pyi (10ms)
(3032) [FG] parsing: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\typing_extensions.pyi [fs read 0ms] (4ms)
(3032) [FG] binding: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\typing_extensions.pyi (3ms)
(3032) [FG] parsing: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi [fs read 0ms] (17ms)
(3032) [FG] binding: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\_typeshed\__init__.pyi (2ms)
(3032) [FG] parsing: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\types.pyi [fs read 1ms] (10ms)
(3032) [FG] binding: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\types.pyi (5ms)
(3032) [FG] parsing: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\abc.pyi [fs read 1ms] (2ms)
(3032) [FG] binding: c:\Users\liuha\.vscode\extensions\ms-python.vscode-pylance-2023.4.10\dist\typeshed-fallback\stdlib\abc.pyi (1ms)

```

</div></details>

**Comment by erictraut** [comment]
`A[str]` is not a legal type annotation because `A` is not a generic class. Its metaclass supports `__getitem__`, so `A[str]` is a valid expression to use in as a runtime value, but type expressions (those that can be used within a type annotation) are more restrictive.

I don't think this would have ever worked in pyright, the type checker that underlies pylance.

If you want class `A` to be considered a generic class — one that accepts a type argument within a type annotation, it needs to subclass from `Generic`.

```python
class A(Generic[T], metaclass=Meta): ...
```
