### ISSUE TITLE
Feature request: Disallow implicit Any option

### ISSUE THREAD

**Issue by Pyrolistical** [microsoft/pylance-release#4223]
The standard library isn't fully type hinted and still returns `Any` in some cases. For example `sqlite3.Cursor.fetchall` is defined as:
```python
def fetchall(self) -> list[Any]
```

The `Any` then leaks into application code and sometimes goes undetected:
```python
def doThing(id: int, name: str):
  pass

for id, name in db.execute("SELECT * FROM users").fetchall():
  # id and name are any
  # but id is actually a str!
  doThing(id, name) # oops we passed a str to id instead of int
```

Feature request: Add option to error when a variable is implicitly has the type `Any`. Similar to TypeScript's [`noImplicitAny`](https://www.typescriptlang.org/tsconfig#noImplicitAny)

**Comment by heejaechang** [comment]
as far as I know, python doesn't have a way to explicitly type `id` or `name`?

I guess, they can do

```python
id: int
name: str
for id, name in db.execute. ...
```

**Comment by Pyrolistical** [comment]
> as far as I know, python doesn't have a way to explicitly type `id` or `name`?

You can also cast:
```python
from typing import cast

for id, name in cast(list[str, str], db.execute. ...):
```

**Comment by erictraut** [comment]
Pyright, the type checker upon which pylance is built, distinguishes between an "implied Any" and an "explicit Any". You can read about this [here](https://microsoft.github.io/pyright/#/mypy-comparison?id=unknown-type-and-strict-mode).

You can configure pyright / pylance to report uses of `Unknown` (implicit `Any`). Reporting errors for _explicit_ use of `Any` would be very noisy.

**Comment by Pyrolistical** [comment]
Hmm, so are you saying the problem is with the standard library exporting an explicit Any?

**Comment by erictraut** [comment]
By "standard library", I presume that you're referring to the typeshed stubs that describe the types for the standard library modules. These stubs are used by all major Python type checkers, including pyright.

If you would like to contribute improvements to typeshed (e.g. the [dbapi2.pyi](https://github.com/python/typeshed/blob/a035372a916e057f309409cd008e2dbe93e29ddc/stdlib/sqlite3/dbapi2.pyi#L383) stub that defines `fetchall`), you can create a feature request or a PR in that project. Pyright regularly pulls updates from typeshed stubs.

**Comment by Pyrolistical** [comment]
Oh thats where that is defined! I've been trying to figure out where the types were being defined. 

Thanks. I'll see if I can improve the type
