### ISSUE TITLE
`assert` statements for type checking don't persist across Jupyter Notebook cells

### ISSUE THREAD

**Issue by numbermaniac** [microsoft/pylance-release#4231]
If I have a function that returns more than one possible type, then I use an `assert` to specify the correct type, that assertion doesn't persist through later cells in a Jupyter Notebook, causing type-checking errors to appear all over the notebook.

Lately for example I have noticed this with `sklearn.datasets` where some of the functions to load a dataset return a union of types, and asserting which one it is isn't taking effect on later cells, causing just about every use of the dataset to show a type checking error. I have shown a simpler example here.

<h3> Environment data </h3>

-   Language Server version: 2023.4.10
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.2 from Homebrew
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>
Cell 1

```py
import random
def float_or_str():
	x = random.random()
	if x < 0.5:
		return x
	else:
		return str(x)

foo = float_or_str()

assert isinstance(foo, float)

foo += 1
```
Cell 2

```py
foo += 10
print(foo)
```

<h3> Expected behavior </h3>

The effect of the type assertion should persist through later cells.

<h3> Actual behavior </h3>

It doesn't - it only applies in that cell, which causes the code to show as an error in later cells. This means you'd have to repeat the assert statement in every single cell, which is extremely tedious.

<h3> Screenshot </h3>

<img width="1111" alt="Screenshot 2023-04-12 at 9 26 58 pm" src="https://user-images.githubusercontent.com/5206120/231443742-ebb689f3-d5e0-4f08-be86-43d9549a5bd7.png">

**Comment by rchiodo** [comment]
Thanks for the issue. I can repro.

I imagine this is an underlying problem of how we string cells together. They're not put into one giant file, but rather each one references the other as an import. 

I don't believe asserts are applied across imports because the timing of the import isn't known (or tracked).

Yes I can repro this by putting your cell1 into a cell1.py, and then in a cell2.py, putting your cell 2 and importing `*` from cell1.
