### ISSUE TITLE
Matplotlib Stubs: Axes.hlines / Axes.vlines accept a string as well as an ArrayLike for `colors`

### ISSUE THREAD

**Issue by ldorigo** [microsoft/pylance-release#4239]
Type: <b>Bug</b>

The official docstrings are also wrong, opened an issue there - but the `colors` parameter can be a single string. e.g.:

```python
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# some random data:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# date range for the same:
start = datetime(2018, 1, 1)
end = datetime(2018, 1, 10)
dates = [start + timedelta(days=i) for i in range(10)]

# plot the data:
fig, ax = plt.subplots()

ax.plot(dates, x)

# Add a hline at y=5:
ax.hlines(5, dates[0], dates[-1], colors='r', linestyles='dashed') # colors gives a type error
```

Extension version: 2023.4.10
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 6.2.9-zen1-1-zen
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-1035-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 3283)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.77GB (14.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: sudcal_vm|
|OS|Linux x64 5.15.0-1035-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|7.72GB (3.69GB free)|
|VM|0%|
</details>

**Comment by debonte** [comment]
> The official docstrings are also wrong, opened an issue there...

@ldorigo, thanks for the issue. As with #4238, please let us know when the docs are updated and we'll change our stubs to reflect that change.
