### ISSUE TITLE
[auto-import] Option to ignore importing from modules that already have a name in the current module

### ISSUE THREAD

**Issue by munael** [microsoft/pylance-release#425]
If I already have

```py
import numpy as np
```
and mistakenly start typing
```py
x = arr|
```
Then `arr` should either suggest to auto complete to `np.array` or not offer any options from `numpy`. Specifically, I'd like the option to make it never suggest to add `from numpy import array`.

**Comment by jakebailey** [comment]
This was actually fixed back in [2020.12.0](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2020120-2-december-2020). If any import already present is the source of an auto-import completion or quick fix, then we will instead edit the completion to use that import. With your example:

![numpyimport](https://user-images.githubusercontent.com/5341706/131583639-d6450b07-d421-4b2f-bf49-0f3c687835ad.gif)
