### ISSUE TITLE
Unable to identify OpenCv package in virtualenv

### ISSUE THREAD

**Issue by fahad-programmer** [microsoft/pylance-release#4250]
## Environment data

-   Language Server version: v2023.4.20
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.9

## Code Snippet

```python
import cv2 as cv
```
## Expected behavior

This should import the module and show no errors like yellow line below cv2.

## Actual behavior

Everything is working fine even the python file but the pylance is not able to identify the opencv module in venv and because of that it is showing yellow line and telling that this is not defined.

## Logs

```
[{
	"resource": "/F:/AI Projects/HandWritten Number Recongnizer/main.py",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"cv2\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 11
}]
```

**Comment by fahad-programmer** [comment]
Yes i have installed it and also run the file in the environment and it run
successfully without any problem.

**Comment by bschnurr** [comment]
we are looking for logs from the ""Python Language Server" window. 
See https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by fahad-programmer** [comment]
`[Info  - 10:43:08 PM] (1828) Pylance language server 2023.4.20 (pyright 64a33975) starting
[Info  - 10:43:08 PM] (1828) Server root directory: c:\Users\AC\.vscode\extensions\ms-python.vscode-pylance-2023.4.20\dist
[Info  - 10:43:08 PM] (1828) Starting service instance "HandWritten Number Recongnizer"
[Info  - 10:43:08 PM] (1828) Auto-indent enabled
[Info  - 10:43:08 PM] (1828) Setting pythonPath for service "HandWritten Number Recongnizer": "f:\AI Projects\HandWritten Number Recongnizer\Venv\Scripts\python.exe"
[Warn  - 10:43:08 PM] (1828) stubPath f:\AI Projects\HandWritten Number Recongnizer\typings is not a valid directory.
[Info  - 10:43:09 PM] (1828) Assuming Python version 3.10
[Info  - 10:43:10 PM] (1828) Auto-excluding f:\AI Projects\HandWritten Number Recongnizer\Venv
[Info  - 10:43:10 PM] (1828) Found 2 source files
[Info  - 10:43:10 PM] (1828) Background analysis(1) root directory: c:\Users\AC\.vscode\extensions\ms-python.vscode-pylance-2023.4.20\dist
[Info  - 10:43:10 PM] (1828) Background analysis(1) started
[Info  - 10:43:10 PM] (1828) Indexer background runner(2) root directory: c:\Users\AC\.vscode\extensions\ms-python.vscode-pylance-2023.4.20\dist (index)
[Info  - 10:43:10 PM] (1828) Indexing(2) started
[Info  - 10:43:12 PM] (1828) scanned(2) 170 files over 1 exec env
[Info  - 10:43:15 PM] (1828) [BG(1)] Long operation: checking: f:\AI Projects\HandWritten Number Recongnizer\model_algorithm.py (4214ms)
[Info  - 10:43:15 PM] (1828) [BG(1)] Long operation: analyzing: f:\AI Projects\HandWritten Number Recongnizer\model_algorithm.py (4605ms)
[Info  - 10:43:15 PM] (1828) [IDX(2)] Long operation: index execution environment f:\AI Projects\HandWritten Number Recongnizer (3733ms)
[Info  - 10:43:15 PM] (1828) [IDX(2)] Long operation: index packages f:\AI Projects\HandWritten Number Recongnizer (3744ms)
[Info  - 10:43:15 PM] (1828) indexed(2) 115 files over 1 exec env
[Info  - 10:43:15 PM] (1828) Indexing finished(2).
[Info  - 10:46:33 PM] (1828) Setting pythonPath for service "HandWritten Number Recongnizer": "f:\AI Projects\HandWritten Number Recongnizer\Venv\Scripts\python.exe"
[Warn  - 10:46:33 PM] (1828) stubPath f:\AI Projects\HandWritten Number Recongnizer\typings is not a valid directory.
[Info  - 10:46:33 PM] (1828) Assuming Python version 3.10
[Info  - 10:46:34 PM] (1828) Auto-excluding f:\AI Projects\HandWritten Number Recongnizer\Venv
[Info  - 10:46:34 PM] (1828) Found 2 source files
[Info  - 10:46:34 PM] (1828) Indexer background runner(3) root directory: c:\Users\AC\.vscode\extensions\ms-python.vscode-pylance-2023.4.20\dist (index)
[Info  - 10:46:34 PM] (1828) Indexing(3) started
[Info  - 10:46:34 PM] (1828) scanned(3) 170 files over 1 exec env
[Info  - 10:46:37 PM] (1828) [BG(1)] Long operation: checking: f:\AI Projects\HandWritten Number Recongnizer\model_algorithm.py (3404ms)
[Info  - 10:46:37 PM] (1828) [BG(1)] Long operation: analyzing: f:\AI Projects\HandWritten Number Recongnizer\model_algorithm.py (3633ms)
[Info  - 10:46:38 PM] (1828) [IDX(3)] Long operation: index execution environment f:\AI Projects\HandWritten Number Recongnizer (3540ms)
[Info  - 10:46:38 PM] (1828) [IDX(3)] Long operation: index packages f:\AI Projects\HandWritten Number Recongnizer (3550ms)
[Info  - 10:46:38 PM] (1828) indexed(3) 115 files over 1 exec env
[Info  - 10:46:38 PM] (1828) Indexing finished(3).`

**Comment by rchiodo** [comment]
Sorry that nobody got back to you on this one. 

In the log it looks like this is the interpreter that Pylance thinks is selected:

```
f:\AI Projects\HandWritten Number Recongnizer\Venv\Scripts\python.exe
```

Is that the interpreter where you installed opencv? Might that be a network drive? I know there's currently a problem with UNC paths https://github.com/microsoft/pylance-release/issues/4357

We should be seeing log entries like so if we're able to find the site-packages folder:

```
2023-07-13 17:04:36.602 [info] [Info  - 5:04:36 PM] (13816)   Received 5 paths from interpreter
2023-07-13 17:04:36.602 [info] [Info  - 5:04:36 PM] (13816)     C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\DLLs
2023-07-13 17:04:36.602 [info] [Info  - 5:04:36 PM] (13816)     C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib
2023-07-13 17:04:36.603 [info] [Info  - 5:04:36 PM] (13816)     C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0
2023-07-13 17:04:36.603 [info] [Info  - 5:04:36 PM] (13816)     c:\Users\rchiodo\source\testing\Testing_Pyright\.venv
2023-07-13 17:04:36.603 [info] [Info  - 5:04:36 PM] (13816)     c:\Users\rchiodo\source\testing\Testing_Pyright\.venv\Lib\site-packages
```

Although this log output only comes out if you set the log level to trace:

```json
	"python.analysis.logLevel": "Trace"
```
