### ISSUE TITLE
`networkx` bundled stub problem

### ISSUE THREAD

**Issue by goyalyashpal** [microsoft/pylance-release#4252]
Under "discussion" upstream at: https://github.com/networkx/networkx/discussions/6638
_Originally posted by @goyalyashpal in https://github.com/microsoft/pylance-release/issues/682#issuecomment-1512936361_
Created issue anew on @ debonte and @ rossbar suggestions

### Steps to Reproduce

1. Open VSCodium with `ms-python.python` extension enabled
2. Save this following code to a file with python valid file name & extension and 
open it with vscodium > ensure language mode is set to Python
3. This requires turning on the "Python Type Checking Mode" from status bar (default 
is off). This will show as Set to "basic".
    1. Open the Problems Panel `ctrl + shift + m` or
    2. Hover over or click on `draw` (line 9) and then do `ctrl + shift + p` Command 
    Palette > type `hover` > select "Show definition preview hover"
4. Click on `draw` (line 9) > press `f12` "Go to definition"
 

```python
import networkx
import matplotlib.pyplot as plt

edges = [(1,2),(2,3),(2,4)]

nxgraph = networkx.DiGraph()
nxgraph.add_edges_from(edges)

# networkx.draw_networkx(nxgraph)
networkx.draw(nxgraph)
plt.show()

```

### Current Behavior (for corresponding step )

3. "draw_networkx" is not a known member of module "networkx" Pylance [reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues) [Ln 9, Col 10]
(function) draw_networkx: Unknown
4. No definition found for `draw_networkx`

Oher similar issues shown:

* "spring_layout" is not a known member of module "networkx"
* "draw" is not a known member of module "networkx"
* "draw_networkx_labels" is not a known member of module "networkx"

### Environment

Python: 3.11.2 (via `python --version`)
NetworkX: 3.1 (via `pip list | grep networkx`)
OS: Windows 10 22H2 x64

VSCodium: 1.77.0
Pylance extension `ms-python.vscode-pylance` : v2023.3.41
Python extension `ms-python.python` : v2023.6.0

**Comment by MiguelIbrahimE** [comment]
I think this seems to be an issue with Pylance not recognizing certain members of the NetworkX module. One potential solution is to add type hints directly to the NetworkX module to help Pylance understand the types and members of the module. 
This can be done by creating a stub file with the same name as the module (e.g. networkx.pyi) and adding type hints to the module's functions and classes.

Another potential solution is to use a different type checker such as Pyright or Mypy, as they may have better support for type checking the NetworkX module.

**Comment by goyalyashpal** [comment]
umh, the typing issue is caused by lack of type annotations and can be fixed with stub files - got it; but what about the "defintion" not found itself??

> 4\. Click on `draw` (line 9) > press `f12` "Go to definition"
> 4\. No definition found for `draw_networkx`

**Comment by debonte** [comment]
> but what about the "defintion" not found itself??

I'm not sure, but I did find that adding the following to `__init__.pyi` makes "Go to Definition" work in addition to "Go to Declaration". I'm not sure why changing the stubs affects "Go to Definition". @heejaechang or @erictraut may be able to explain.

```python
from .drawing.nx_pylab import draw as draw
```

**Comment by goyalyashpal** [comment]
> adding the following to `__init__.pyi`

> ```python
> from .drawing.nx_pylab import draw as draw
> ```

This look very similar to the suggestion at the previous issue?

> The reason the completions are not showing is because networkx does not explicitly export the `readwrite` module or the `gpickle` module. if you look at the top level `__init.py__` you will notice that `readwrite` is not exported like they have done with `from networkx.testing.test import run as test` 
>
> Therefore, you will need to explicitly import the gpickle module like `import networkx.readwrite.gpickle as gp` and then `gp.` should give you completions.
> 
_Originally posted by @judej in https://github.com/microsoft/pylance-release/issues/682#issuecomment-738334645_

**Comment by goyalyashpal** [comment]
Seems these 2 are different issues - the completions one, and the type hinting/linting one;

both likely from nx's side, both fixable by using stubs (right?) and both due to separate reasons and hence requiring separate steps for resolution

**Comment by debonte** [comment]
Reactivating since we maintain our own stubs for `networkx` in https://github.com/microsoft/python-type-stubs/tree/main/stubs/networkx. Feel free to submit a PR there with a proposed fix.

**Comment by lkct** [comment]
@goyalyashpal please try to clone https://github.com/microsoft/python-type-stubs and add the following to your vscode setting
```json
    "python.analysis.stubPath": "/path/to/python-type-stubs/stubs",
```

If your problem is resolved by this, the next version of pylance with these stubs should work fine.

**Comment by lkct** [comment]
just a kind note: don't add a whitespace after @ which makes it useless. Actually I see your update because I commented, not because I was mentioned.

@goyalyashpal (<-- this should work)
@ goyalyashpal (<-- but this not)

**Comment by goyalyashpal** [comment]
hehe :smiley: i deliberately put space as some ppl don't like getting mentioned
