### ISSUE TITLE
Imports cannot be resolved

### ISSUE THREAD

**Issue by ullix** [microsoft/pylance-release#4256]
## Environment data

-   Language Server version:  v2023.4.20 
-   OS and version: Linux x64 5.10.0-21-amd64
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] on linux

## Code Snippet

```
#! /usr/bin/env python3
# -*- coding: UTF-8 -*-

import numpy
print("numpy.random.poisson(100): ", numpy.random.poisson(100))

```

## Repro Steps

1. open the code snippet in vscode

## Expected behavior

recognize all available imports

## Actual behavior

All imports of modules which were installed by pip are NOT being recognized, numpy, scipy, pyserial, PyQt5, matplotlib, ...

For a while now (many weeks) I am getting those wiggly red lines for all modules installed with pip, like e.g. the numpy module, supposedly indicating that an import of a module is not possible.

![image](https://user-images.githubusercontent.com/9335726/233028209-a7b0eae5-b192-4d4d-b386-3e160847f080.png)

However, this is not true, the module is installed, is accessible, and this Python two-liner program runs just fine:

    $ python bugtest.py
    numpy.random.poisson(100): 107

So vscode now indicates loads of errors, which don't exist, obscuring the errors that do exist. How can I get rid of these false indications?

About vscode :
Version: 1.77.3 Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 Date: 2023-04-12T09:16:52.732Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Linux x64 5.10.0-21-amd64 Sandboxed: No

NOTE: this had first been reported to this site, which referred me to the pylance site:
https://github.com/microsoft/vscode/issues/180209

**Comment by rchiodo** [comment]
Thanks for the issue. 

What is the interpreter you have selected for the python file? 

This works for me as long as I select the interpreter that has numpy installed, but perhaps your venv is so large we stop looking.

Could you include the logs as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

That should show us what paths we're looking in.

**Comment by ullix** [comment]
I am not quite sure what you are asking, so I'll do my best:

`$ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	LMDE 5 (elsie)
Release:	5
Codename:	elsie
`

I activated the trace:

![Screenshot from 2023-04-20 11-46-46](https://user-images.githubusercontent.com/9335726/233329653-bb9cc628-911c-4444-9e50-01f89168017f.png)

but when I open the file bugtest.py, this is all I get:

![Screenshot from 2023-04-20 11-47-11](https://user-images.githubusercontent.com/9335726/233330032-3d00b2c0-fe2e-4856-a662-91f742f32414.png)

Actually running bugtest.py in the vscode terminal:
`$ python bugtest.py 
numpy.random.poisson(100):  80`

 does not change the "Problems" output at all, and neither "Debug Console" nor "Output" have any output.

**Comment by ullix** [comment]
I forgot, you asked about "venv": I had used a venv some time ago, but not now. I am NOT using one, at least not intentionally. 

Unless there is one setting somewhere which makes me use a venv without telling me.

**Comment by rchiodo** [comment]
There's an output tab specifically for Pylance, called 'Python Language server'. That's the log we need:

![image](https://user-images.githubusercontent.com/19672699/233424317-df61f85a-114e-4aa4-9bf1-064e96c332bc.png)

It will tell us what python environment you have selected in VS code. It has to match the one you're running from the command line. If not you'd get this error.

The Python Environment can be picked at the bottom right:

![image](https://user-images.githubusercontent.com/19672699/233424603-9456fa1c-3a82-4965-96e7-424b54a73aad.png)

**Comment by ullix** [comment]
It is hard to use vscode! (and even harder, no to :-7)

I had run bugtest.py onece. I hope the attached is what you need. My screen bottom line says:
![Screenshot from 2023-04-20 18-22-46](https://user-images.githubusercontent.com/9335726/233428678-c4c8e485-c68f-48c8-8673-7044de62227f.png)

[bugtest.pylance.txt.](https://github.com/microsoft/pylance-release/files/11288409/bugtest.pylance.txt)

**Comment by rchiodo** [comment]
It seems to me like you have the wrong environment selected. According the log the 'Python' environment is this one:

```
/usr/local/bin/python3.11
```

The one you said you were running is a Python 3.9.2 environment. That would explain the error.

You have to select your Python 3.9.2 environment by clicking on that 'Python' in the bottom right of the window. Then Pylance (and other things in VS code) will use the same environment you're using in the terminal.

**Comment by rchiodo** [comment]
There's some online help about it here:
https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters for more info

**Comment by ullix** [comment]
Yeehaa! It works! 

Many thanks :-))
