### ISSUE TITLE
unable to import seaborn

### ISSUE THREAD

**Issue by taradepan** [microsoft/pylance-release#4267]
Type: <b>Bug</b>

while using Jupyter i am unable to use seaborn library. 
even after "pip install seaborn"

Extension version: 2023.6.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.65GB (0.94GB free)|
|Process Argv|--crash-reporter-id 74b2dd5c-4c79-45a6-a047-0a12dfb4e94e|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttextcf:30716743
pythonclientmvcf:30713944

```

</details>

**Comment by rchiodo** [comment]
Sorry it's not clear to me what the selected environment is? That terminal is just running the default python environment. Is that the same one that's selected in VS code?

It's shown in the bottom right of the VS code window:

![image](https://user-images.githubusercontent.com/19672699/233425509-e30de834-5ead-4c8e-9f6f-209843a29b1c.png)

Yours should say that specific anaconda environment. `(base)`

If that's true, then we'd need to see what paths we're looking for stuff in. They should be listed in the "Python Language Server" output.

Thanks.

**Comment by taradepan** [comment]
![1](https://user-images.githubusercontent.com/63502147/233428984-376b6465-851e-408a-b222-c2baeb89980e.png)

**Comment by rchiodo** [comment]
That doesn't seem like the same python environment to me at least. Hard to say for sure. What happens when you click on it? It should bring up a list showing the environments and it should include the path to the executable there:

For example, this is what I see:

![image](https://user-images.githubusercontent.com/19672699/233429654-094ccde9-152d-432f-81d2-d11b294463bd.png)

**Comment by bschnurr** [comment]
see https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters  for more info

**Comment by taradepan** [comment]
![1](https://user-images.githubusercontent.com/63502147/233431128-4f93114c-66d7-4852-85e6-e207936383f3.png)

**Comment by rchiodo** [comment]
If you want Pylance to use the same environment you're running, you'd pick the 'base' environment in that drop down.

**Comment by taradepan** [comment]
now it's working...
Thanks a lot.
