### ISSUE TITLE
Option to only show errors/warnings on save

### ISSUE THREAD

**Issue by westernwontons** [microsoft/pylance-release#4269]
I would like to have to ability to specify an option to only show errors and warnings when I save the file and not on every keystroke.

# Reason
It can be very distracting to have the red squiggles pop up every time I'm typing a letter.

**Comment by debonte** [comment]
@westernwontons, thanks for the suggestion! If we added this option it should be added centrally by VS Code and apply to all languages rather than being added by a particular language server like Pylance. Please open an issue at https://github.com/microsoft/vscode/issues.
