### ISSUE TITLE
pandas TimeStamp init arguments are wrong

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#427]
## Environment data

-   Language Server version: 2020.9.6
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.5

## Expected behaviour

No error

## Actual behaviour

```python
ts = pd.Timestamp("2020-09-26")
```
reports
```
Arguments missing for parameters "freq", "tz", "unit", "year", "month", "day"
```

Possible fix:
```
diff _libs/tslibs/__init__.pyi.ORIG _libs/tslibs/__init__.pyi
153,158c153,158
<         freq: Any,
<         tz: Any,
<         unit: str,
<         year: int,
<         month: int,
<         day: int,
---
>         freq: Any = ...,
>         tz: Any = ...,
>         unit: str = ...,
>         year: int = ...,
>         month: int = ...,
>         day: int = ...,
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020100-7-october-2020
