### ISSUE TITLE
Function signature prompt is wrong when `singledispatch` or `singledispatchmethod` is used

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/pylance-release#4277]
## Environment data

-   Language Server version: v2023.4.31
-   OS and version: Windows11 22624
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6 64-bit

## Code Snippet

```python
from functools import singledispatch


class Person:

    @singledispatchmethod
    def hello(self):
        print("Hello")

    @hello.register
    def _(self, name: str):
        print("Hello, "+name)

@singledispatch
def add():
    return 0

@add.register
def _(a: int, b: int):
    return a+b


add()
Person().hello()
```

## Repro Steps

Just copy the code snippet and see the signature prompt

## Expected behavior

Prompt window will show method overloading

## Actual behavior
I can't get the correct signature prompt
![image](https://user-images.githubusercontent.com/65096819/233815169-a1944971-95a6-4855-b77e-dc8e4766a3af.png)

**Comment by erictraut** [comment]
Yes, the `singledispatch` mechanism in Python uses dynamic (runtime) calls to register callbacks with the single dispatch. That makes it difficult for a static type analyzer to understand the signatures. If you want meaningful completion suggestions, I recommend avoiding the `singledispatch` design pattern.

**Comment by zhiyiYo** [comment]
Can we perform special processing on `singledispatch`?

**Comment by erictraut** [comment]
That's not possible given the architecture of pyright, the type checker that underlies pylance. The behavior is too dynamic to accommodate. 

The `singledispatch` mechanism is similar in some ways to `property` setter and deleter registration. However, `property.setter` and `property.deleter` create a new object and assign this object back to the original symbol. In contrast, `singledispatch` registration performs internal "magic" that is invisible to a static type checker. It doesn't assign the modified value back to the original symbol. That means there's no way to find such registrations without scanning all code that potentially contains such registrations. That's antithetical to the way that pyright works. Pyright is a lazy (just-in-time) type analyzer, and it always analyzes the minimum number of expressions needed to supply the type of a particular symbol. This is done for performance reasons — a key to pylance's ability to provide quick completion suggestions.

To make matters worse, `singledispatch` registrations can theoretically be performed in any module, even outside of the module in which the the original singledispatch is defined. So, worst case, pyright would need to analyze every file in your program to determine the type. That's not feasible.

As I mentioned above, if you want good completion suggestions, I recommend avoiding the `singledispatch` design pattern.

If you really want to make completions work with `singledispatch`, you could define the `@singledispatch` and its variants as an overload in a conditional block guarded by `TYPE_CHECKING`. Something like this:

```python
if not TYPE_CHECKING:
    @singledispatch
    def add():
        return 0

    @add.register
    def _(a: int, b: int):
        return a+b

    @add.register
    def _(a: str, b: str):
        return a+b
else:
    @overload
    def add(a: int, b: int): ...

    @overload
    def add(a: str, b: str): ...

    def add(*args, **kwargs): ...
```

**Comment by zhiyiYo** [comment]
Thank you for the useful answer
