### ISSUE TITLE
Unpacking tuples results in inferring impossible type combinations to members

### ISSUE THREAD

**Issue by toramanlis** [microsoft/pylance-release#4278]
<h3> Environment data </h3>

-   Language Server version: 2023.4.30
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.0
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
from typing import Tuple

StrPair = Tuple[str, str]
IntPair = Tuple[int, list[int]]
EitherPair = StrPair | IntPair


pair: EitherPair = ("", "")

needle, haystack = pair
needle in haystack

```

<h3> Repro Steps </h3>

1. Have multiple `Tuple` definitions with multiple subscripting
2. Make a Union of the two
3. Get the type inferred to a variable
4. Unpack the variable into multiple variables

<h3> Expected behavior </h3>

Pyright to remember the possible type combinations by the logical dependencies and recognize it's a valid `in` operation. Similar to the way it handles `TypeVar`s.

<h3> Actual behavior </h3>

```
Operator "in" not supported for types "str | int" and "str | list[int]"
```
Pyright distributes the types of the members over the `|` operator. Each unpacked variable is inferred every subscripted type with respect to their index. Completely disregards that it's impossible for the types to have mixed.

This can be overcome by using `TypeVar`s apparently, but I'm not completely sure this is intended. I failed to find any specification on this, it may have been left to the implementer. Either way, it is best you take a look decide what to make of it

<h3> Logs </h3>

**Comment by erictraut** [comment]
Pyright is working as designed here.

Static type checkers track the types of symbols individually. These types are not conditional on the types of other symbols. To do what you're suggesting would require pyright to track conditions like "the type of `needle` at this point is `str` if the type of `haystack` is also `str` but is `int` otherwise". This sort of "entanglement" between symbol types is not feasible. I'm not aware of any type checker in any language that does this.

Not surprisingly, mypy infers the same types as pyright in this case.

You'll need to restructure your code if you want to avoid a type violation error here. Or you can suppress the diagnostic using a `# type: ignore`. Or if you find type checking too noisy and are unwilling to make accommodations in your code, you can disable it entirely by setting `python.analysis.typeCheckingMode` to "off".

**Comment by toramanlis** [comment]
Can we just take a minute to appreciate how quickly this is addressed. i'll just add a quick workaround for future reference, in case anyone else has this issue and sees this page.

In my opinion, the simplest, most effective solution is to use `TypeVar`. Exactly what it's made for and exactly what we need. It was barely a second choice to begin with, just because a single `|` operator is even simpler. The working version of above snippet would be:

```python
from typing import Tuple, TypeVar

StrPair = Tuple[str, str]
IntPair = Tuple[int, list[int]]

EitherPair = TypeVar('EitherPair', StrPair, IntPair)


def test(pair: EitherPair):
    needle, haystack = pair

    if needle in haystack:
        pass


test(("", ""))

```

`TypeVar`, as the name suggests, works like a variable that holds types. When we make an assignment that has any `TypeVar` involved in its resolution, the actual type in the value is also assigned to the respective `TypeVar`. In this example, the parameter pair first, is hinted the `EitherPair` type that can either be one of `StrPair` or `IntPair`. When a value is introduced by a function call, type checker has to find the inferred type (the most specific type that fits the definition) and, in a way, assigns the type to the type variable `EitherPair`. Because the assigned type of a `TypeVar` has to be consistent through the function call, type checker, apparently has a different way of looking into possible scenarios. Seems like it separates the possible options of the `TypeVar` and validates everything for each option or combination of options if there's more than one `TypeVar`.

This doesn't seem to be how `Union` types work though. It doesn't have separate scenarios for each option. It validates the value at assignment which is not unpacked at that point. Then, when the unpacked variables are needed to be type checked, they're traced individually.

Still, I'd say it's problematic. Because the type hinting is sufficient to tell the operation is valid and although there's nothing specifically saying how this particular situation should be handled, I think it's implied that a `Union` definition like `Tuple[str, str] | Tuple[int, list[int]]` disallows the unpacked Tuples yield one of each. Then again, it's not exactly allowed to have one of each. It's just that the type checker doesn't know it already ruled out that possibility.


Btw, @erictraut let me just tell you how impressive it is that you attend countless of these reports most of which are not bugs in the first place. you do actually look into them and even if they're not bugs, you try to provide suggestions and relevant documentation. Even on a Sunday in mere hours. You, sir, are an absolute unit. Cheers
