### ISSUE TITLE
Auto Complete often "No code actions available"

### ISSUE THREAD

**Issue by loveyoufooyou** [microsoft/pylance-release#4282]
# Feature request
Auto complete more code in the current path of python lib .

# report
In the example, I use Django.
I click `ctrl+.` to Auto Complete.
```python
settings  # correct: from django.conf import settings
gloable_settings  # wrong: No code actions available
```
I think it should: `from django.conf import gloable_settings`.

# Environment
vscode 1.77.3
python3.9
windows10

**Comment by rchiodo** [comment]
Thanks for the issue. This is actually a result of our default indexing depth. We don't search deep enough to find 'global_settings'.

You can fix this by doing this:

```jsonc
# User settings.json
    "python.analysis.indexing": true,
    "python.analysis.packageIndexDepths": [

        {
            "name": "sklearn",
            "depth": 2
        },
        {
            "name": "matplotlib",
            "depth": 2
        },
        {
            "name": "scipy",
            "depth": 2
        },
        {
            "name": "django",
            "depth": 4 <--- This number has to be more than 2
        }
    ]
```
