### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mrswopschall** [microsoft/pylance-release#4284]
<h3> Environment data </h3>

-   Language Server version: 2023.4.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for logging an issue.

Unfortunately, we need more information to figure out what your problem is. 

Please enter the information as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
