### ISSUE TITLE
Rename does not rename module in test directory

### ISSUE THREAD

**Issue by dciborow** [microsoft/pylance-release#4286]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When I rename a directory in like 'src/my_package' -> 'src/new_package', I expect the imports in my 'tests/' be updated with the name name.
## Steps to reproduce:

1. XXX

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• flake8Path: "<placeholder>"
• mypyPath: "<placeholder>"
• pylintPath: "<placeholder>"

formatting
• autopep8Path: "<placeholder>"
• provider: "black"
• blackPath: "<placeholder>"

testing
• pytestEnabled: true

```

</p>
</details>

Extension version: 2023.7.11111009
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1105-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.79GB (10.08GB free)|
|Process Argv|--crash-reporter-id ddcce7ad-f6f4-4d7c-ab78-4d6e2c867f39|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1105-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|3.84GB (1.87GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by heejaechang** [comment]
@dciborow Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

my gut feeling is we are internally setting `src` as root or setting `test` as extraPath and it get filtered out from module renaming.

but without log, hard to know. and I assume the folder rename properly rename reference to the folder for files in `src`?

also, if possible, if you can provide us some simple repro project, that will help us as well to find out what is going on.

**Comment by dciborow** [comment]
This repo is a very simple project that you can try out in a codespace. 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/9027725/235818721-78b6cf1f-ca67-4cfd-a166-c1812a5a590b.png">

<img width="972" alt="image" src="https://user-images.githubusercontent.com/9027725/235818838-3ded6c2f-d94d-499e-adda-33d28af7f749.png">


```txt
(1491) Background analysis message: setFileOpened
(1491) Background analysis message: markFilesDirty
(1491) Background analysis message: analyze
(1491) [BG(1)] analyzing: /workspaces/python-package-template/src/python_package/hello_world.py ...
(1491) [BG(1)]   parsing: /workspaces/python-package-template/src/python_package/hello_world.py (1ms)
(1491) [BG(1)]   binding: /workspaces/python-package-template/src/python_package/hello_world.py (1ms)
(1491) [BG(1)]   checking: /workspaces/python-package-template/src/python_package/hello_world.py (45ms)
(1491) [BG(1)] analyzing: /workspaces/python-package-template/src/python_package/hello_world.py (47ms)
(1491) [BG(1)] analyzing: /workspaces/python-package-template/tests/test_methods.py ...
(1491) [BG(1)]   checking: /workspaces/python-package-template/tests/test_methods.py (4ms)
(1491) [BG(1)] analyzing: /workspaces/python-package-template/tests/test_methods.py (10ms)
(1491) Background analysis message: getDiagnosticsForRange
(1491) [FG] parsing: /workspaces/python-package-template/src/python_package/hello_world.py (1ms)
(1491) [FG] binding: /workspaces/python-package-template/src/python_package/hello_world.py (1ms)
(1491) Background analysis message: resumeAnalysis
(1491) [BG(1)] indexing: /workspaces/python-package-template/src/python_package/hello_world.py [found 3] (0ms)
(1491) Indexing Done: /workspaces/python-package-template/src/python_package/hello_world.py
(1491) Background analysis message: getDiagnosticsForRange
(1491) Background analysis message: getDiagnosticsForRange
(1491) Background analysis message: getDiagnosticsForRange
(1491) Background analysis message: getSemanticTokens delta
(1491) [BG(1)] getSemanticTokens delta previousResultId:1683078284394 at /workspaces/python-package-template/src/python_package/hello_world.py (1ms)
[Info  - 1:45:01 AM] (1491) SourceFile: Received fs event 'add' for path '/workspaces/python-package-template/src/python_package/hello_world.py.769d9ef47ddeffbd81e7fee5e8230954.tmp'
[Info  - 1:45:02 AM] (1491) SourceFile: Received fs event 'change' for path '/workspaces/python-package-template/src/python_package/hello_world.py.769d9ef47ddeffbd81e7fee5e8230954.tmp'
[Info  - 1:45:02 AM] (1491) SourceFile: Received fs event 'change' for path '/workspaces/python-package-template/src/python_package/hello_world.py'
(1491) Background analysis message: markFilesDirty
(1491) Background analysis message: analyze
[Info  - 1:45:03 AM] (1491) SourceFile: Received fs event 'add' for path '/workspaces/python-package-template/src/python_package/__pycache__/hello_world.cpython-311.pyc'
```

**Comment by dciborow** [comment]
Here is another example I posted in my duplciate.

<img width="1480" alt="image" src="https://user-images.githubusercontent.com/9027725/235768277-9f105b5d-d9c1-4126-9f83-919560fa9019.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/9027725/235768313-aa7b8f82-8978-4be1-b8aa-2be2b4f3ac5e.png">
After
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/9027725/235768375-5fbfa180-864f-4786-afd5-5766401993b2.png">

**Comment by dciborow** [comment]
> Thanks for the suggestion. This isn't currently a feature we support, but we'll make sure to put it on our backlog.

@rchiodo , I think it actually is already largely supported. I think I'm just causing some time of edge case with my file structure. Something about using the 'src' directory is throwing off the refactor.

**Comment by heejaechang** [comment]
@dciborow, your log is cut off, can you post full log rather than some parts of it? it doesn't have any info on how we recognized your workspace folder structure and etc. the actual information we need to diagnose your issue.

**Comment by heejaechang** [comment]
@dciborow so, I just looked the [repo](https://github.com/microsoft/python-package-template) shared in this issue, the reason `rename` didn't find the references in `test` was these settings in `toml` file

```
include = ["src"]
executionEnvironments = [
  { root = "src" }
]
```

the `include` points to only `src`, so files in `tests` are not recognized as `user files` that are allowed to be modified by us. and `executionEnvironments` explicitly include only `src` so, `test` will not be recognized as part of `workspace`

to fix the issue, those 2 need to be changed to

```
include = ["src", "tests"]
executionEnvironments = [
  { root = "src" },   { root = "tests" }
]
```

after that, references under `tests` will be recognized.

**Comment by heejaechang** [comment]
reopen the issue if it is still an issue.
