### ISSUE TITLE
support hover tooltip on string that mapped to module/symbol

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#4287]
now we have an infrastructure for string <=> module/symbol map from https://github.com/microsoft/pylance-release/issues/3700

one enhancement we can do is adding `hover support` as well, so that for those strings, we show the same `tooltip` user would get if user hovers over those names in `import statement`.

ex) from `module1`.`module2` import `symbol` => "`module1`.`module2`.`symbol`"

**Comment by rchiodo** [comment]
@heejaechang assigning to you for now. Please put back in triage if that's not okay.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231031-18-October-2023-PreRelease)
