### ISSUE TITLE
Improve pandas typestubs shipped with pylance so it can detect "The truth value of a DataFrame is ambiguous."

### ISSUE THREAD

**Issue by karolzlot** [microsoft/pylance-release#4289]
I described the problem here: https://github.com/microsoft/pyright/issues/5024

I know that pylance ships with additional pandas typestubs. Mirror of them is here: https://github.com/blakeNaccarato/pylance-stubs-unofficial

I request for improvement in those typestubs, so this bug can be detected by pylance.

**Comment by erictraut** [comment]
If it is possible to describe this particular constraint in type stubs, that's great, but I suspect it's not. There are many internal constraints or behaviors that cannot be described via static typing. Someone who is more familiar with pandas than me (perhaps @gramster) may be able to provide some insights here.

**Comment by bschnurr** [comment]
Panda stub issues should be sent here https://github.com/pandas-dev/pandas-stubs
