### ISSUE TITLE
Support for PEP 712

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4290]
Add support for PEP 712.

https://peps.python.org/pep-0712/
https://discuss.python.org/t/pep-712-adding-a-converter-parameter-to-dataclasses-field/26126

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.5.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023511-3-May-2023-PreRelease)
