### ISSUE TITLE
Function hint shows info about np.vectorize, not the vectorized function

### ISSUE THREAD

**Issue by Quacken8** [microsoft/pylance-release#4292]
## Environment data

-   Language Server version: v2023.4.40
-   OS and version: Ubuntu 22.04.2 LTS
-   Python version: 3.10.6

## Code Snippet

```python
import numpy as np

@np.vectorize
def foo(x):
    """I am a foo function"""
    return x**2

foo


print(foo.__doc__)
```
![Peek 2023-04-28 09-33](https://user-images.githubusercontent.com/78506690/235085067-e226efe7-87a8-4dab-a246-662edbf0e99a.gif)

## Repro Steps

1. define a function with a docstring
2. use np.vectorize (wrapper or not)

## Expected behavior

The intellisense hint shows the original docstring as np.vectorize passes it on by default

## Actual behavior

The intellisense hint shows hint for np.vecorize

**Comment by erictraut** [comment]
The numpy library is partly annotated, but some of its functions are missing type information. The `vector` decorator function is an example of a function that is unannotated.

Please consider filing a bug report in the [numpy project](https://github.com/numpy/numpy).
