### ISSUE TITLE
Library is overriding the stdlib module. 

### ISSUE THREAD

**Issue by mohsinzz** [microsoft/pylance-release#4293]
I am getting below warning and my program does not run.

"c:\Machine Learning Project\pyenv\Lib\datetime.py" is overriding the stdlib module "datetime"

The warning is being shown for many libraries and my program does not run.

How do I fix this issue.

**Comment by debonte** [comment]
@mohsinzz, my first thought is this sounds like a duplicate of #3751 where Pylance is not automatically excluding your virtual environment directory and you need to manually exclude it with:

```json
  "python.analysis.exclude": ["pyenv"],
```

If that doesn't work, please provide more detail on your project directory and virtual environment directory structure.

**Comment by genericHuman12** [comment]
Datetime is a module, so you need to change your file name.
