### ISSUE TITLE
Server Connection and initialisation Issue

### ISSUE THREAD

**Issue by traliotube** [microsoft/pylance-release#4294]
Type: <b>Bug</b>

Run VSCode. The prompt gives many error msgs saying:

node:internal/modules/cjs/loader:990
  throw err;
  ^

Error: Cannot find module 'c:\Users\prana\.vscode\extensions\ms-python.vscode-pylance-2023.4.40\dist\server.bundle.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 8:13:02 PM] Connection to server got closed. Server will restart.
[Error - 8:13:02 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:02 PM] Pylance client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:990
  throw err;
  ^

Error: Cannot find module 'c:\Users\prana\.vscode\extensions\ms-python.vscode-pylance-2023.4.40\dist\server.bundle.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 8:13:03 PM] Connection to server got closed. Server will restart.
[Error - 8:13:03 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:03 PM] Pylance client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:990
  throw err;
  ^

Error: Cannot find module 'c:\Users\prana\.vscode\extensions\ms-python.vscode-pylance-2023.4.40\dist\server.bundle.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 8:13:03 PM] Connection to server got closed. Server will restart.
[Error - 8:13:03 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:03 PM] Pylance client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:03 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:990
  throw err;
  ^

Error: Cannot find module 'c:\Users\prana\.vscode\extensions\ms-python.vscode-pylance-2023.4.40\dist\server.bundle.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 8:13:03 PM] Connection to server got closed. Server will restart.
[Error - 8:13:03 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:03 PM] Pylance client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:03 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:990
  throw err;
  ^

Error: Cannot find module 'c:\Users\prana\.vscode\extensions\ms-python.vscode-pylance-2023.4.40\dist\server.bundle.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at Module._load (node:internal/modules/cjs/loader:832:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 8:13:04 PM] The Pylance server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 8:13:04 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:04 PM] Pylance client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:13:04 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

Extension version: 2023.4.40
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.63GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 799b00d5-c0e7-4247-8d50-e7a69afb47af|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
6233i204:30672705
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by debonte** [comment]
Seems like Pylance may not have been installed/updated correctly. Can you try the steps [here](https://github.com/microsoft/vscode-python/issues/13721#issuecomment-685014688) and see if that resolves your issue?

**Comment by traliotube** [comment]
> Seems like Pylance may not have been installed/updated correctly. Can you try the steps [here](https://github.com/microsoft/vscode-python/issues/13721#issuecomment-685014688) and see if that resolves your issue?

i remove ms-python.vscode-pylance-* by mistake, its fine right?

**Comment by debonte** [comment]
> i remove ms-python.vscode-pylance-* by mistake, its fine right?

Yes, that's good actually. I didn't notice that the instructions only suggested removing the Python extension.

**Comment by traliotube** [comment]
It worked @debonte, Thanks a Lot!
