### ISSUE TITLE
"import could not be resolved" when using an editable install with pyproject.toml

### ISSUE THREAD

**Issue by tybug** [microsoft/pylance-release#4298]
<h3> Environment data </h3>

-   Language Server version: 2023.4.40
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.10
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
import ossapi
```

<h3> Repro Steps </h3>

I maintain a package, [ossapi](https://github.com/circleguard/ossapi), which I recently migrated from `setup.py` to `pyproject.toml` for building. I install the package locally (`pip install -e .`) as I actively develop it. When installing the version which uses `pyproject.toml`, pylance fails to find it. When using the `setupy.py` version, it works fine.

Repro steps (roughly):

1. `git clone https://github.com/circleguard/ossapi`
2. `cd ossapi`
3. `pip install -e .`
4. run above code snippet and observe pylance reports ossapi cannot be found
5. `git checkout v3.1.2` (last version on setup.py)
6. `pip install -e .`
7. run above code snippet and observe pylance reports ossapi can be found

<h3> Expected behavior </h3>

Pylance finds editable installs with pyproject.toml

<h3> Actual behavior </h3>

Pylance does not find editable installs with pyproject.toml, though it does with setup.py

<h3> Logs </h3>

This is from the "output" tab with the "python" dropdown selected, when opening and then saving a file with the above snippet in it.

```
Python interpreter path: /opt/homebrew/opt/python@3.10/bin/python3
Starting Pylance language server.
[ERROR 2023-3-29 16:40:2.11]: Active interpreter type is detected as Unknown {"id":"/opt/homebrew/opt/python@3.10/bin/python3","sysPrefix":"/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10","envType":"Unknown","envName":"","envPath":"","path":"/opt/homebrew/opt/python@3.10/bin/python3","architecture":3,"sysVersion":"3.10.10 (main, Feb  8 2023, 05:32:04) [Clang 14.0.0 (clang-1400.0.29.202)]","version":{"raw":"3.10.10","major":3,"minor":10,"patch":10,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.10.10 64-bit","detailedDisplayName":"Python 3.10.10 64-bit"}
Extension search path: /Users/tybug/.vscode/extensions
> /opt/homebrew/opt/python@3.10/bin/python3 ~/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/linter.py -m pylint --disable=protected-access,invalid-name,logging-not-lazy,broad-except,missing-function-docstring,import-outside-toplevel,missing-module-docstring,missing-class-docstring,fixme,relative-beyond-top-level,wildcard-import,line-too-long,anomalous-backslash-in-string,too-many-arguments,too-few-public-methods,useless-super-delegation,too-many-lines,unnecessary-pass,wrong-import-order,redefined-outer-name,expression-not-assigned,dangerous-default-value,arguments-differ,abstract-method,too-many-locals,too-many-statements,wrong-import-position,too-many-instance-attributes,too-many-public-methods,too-many-nested-blocks,logging-fstring-interpolation,too-many-return-statements,too-many-ancestors,too-many-branches,inconsistent-return-statements,subprocess-run-check,eval-used,global-statement,exec-used,unused-wildcard-import,disallowed-name,bare-except,using-constant-test,raise-missing-from,redefined-builtin,unspecified-encoding,undefined-loop-variable,use-implicit-booleaness-not-comparison,signature-differs,arguments-renamed ./_ossapi.py
cwd: .
##########Linting Output - pylint##########

[]

Extension search path: /Users/tybug/.vscode/extensions
> /opt/homebrew/opt/python@3.10/bin/python3 ~/.vscode/extensions/ms-python.python-2023.6.1/pythonFiles/linter.py -m pylint --disable=protected-access,invalid-name,logging-not-lazy,broad-except,missing-function-docstring,import-outside-toplevel,missing-module-docstring,missing-class-docstring,fixme,relative-beyond-top-level,wildcard-import,line-too-long,anomalous-backslash-in-string,too-many-arguments,too-few-public-methods,useless-super-delegation,too-many-lines,unnecessary-pass,wrong-import-order,redefined-outer-name,expression-not-assigned,dangerous-default-value,arguments-differ,abstract-method,too-many-locals,too-many-statements,wrong-import-position,too-many-instance-attributes,too-many-public-methods,too-many-nested-blocks,logging-fstring-interpolation,too-many-return-statements,too-many-ancestors,too-many-branches,inconsistent-return-statements,subprocess-run-check,eval-used,global-statement,exec-used,unused-wildcard-import,disallowed-name,bare-except,using-constant-test,raise-missing-from,redefined-builtin,unspecified-encoding,undefined-loop-variable,use-implicit-booleaness-not-comparison,signature-differs,arguments-renamed ./__random.py
cwd: .
##########Linting Output - pylint##########

[]
```

**Comment by erictraut** [comment]
Please refer to the [troubleshooting section about editable installs](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#editable-install-modules-not-found).

**Comment by tybug** [comment]
Hmm. I can't say I'm a fan of having static analysis broken by updating to a supposedly newer-and-better build system. Both of the setuptools workarounds seem strictly worse; either use compat mode which is explicitly deprecated, or strict mode which doesn't seem to allow importing new files without a re-install.

But I understand that your hands are tied here. Thanks for the response.
