### ISSUE TITLE
code action for imports should prefer pathlib (quick fix sort order for add import)

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/pylance-release#4299]
The current behaviour of when suggesting import actions is to prefer the shorter import line, even if that means that it will import from another random module which happens to be installed instead of stdlib.

1. The first suggestion in the list should be the most likely one, and when there is a stdlib import possible, the answer is clear.
2. User should be allowed to extend or override the prefered import modules list, which by default should just be a list of python stdlib modules. That would allow people that do import similarly named imports from non-stdlib to alter the behavior. This feature is an extension for the first bullet, so it might be implemented separately.

# Current behavior

Look at example below, while ignoring the ruff suggestions as they come from another extension. Still, the suggested imports for `Path`, one of the most common imports one would want, is not the 1st import, instead `click` is listed first just because it is installed.

Over the last couple of months I got tens of bad suggestions, even bugs when using auto-import as Path was imported from random places instead of `pathlib`. I seem similar behavior with imports from `typings`, where code prefered to import from a 3rd-party library instead of stdlib.

![](https://sbarnea.com/ss/Screen-Shot-2023-05-01-07-08-21.74.png)

## Actual behavior

If you type `Path`, `Sequence`, `Iterator` the 1st code action suggestion for an import should be one from python stdlib, not from 3rd party libraries.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2024.2.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20242100-13-February-2024-PreRelease)

**Comment by facundoq** [comment]
I can confirm this has been fixed for "Add Imports" but is still an issue when using the "Trigger Suggest" (ie, autocomplete/"ctrl+space").  

<img width="966" height="585" alt="Image" src="https://github.com/user-attachments/assets/d8006d03-4d14-4993-a59b-193628493756" />

Maybe a MRU scheme could be applied to solve this, so the solution works even for symbols that are not in stdlib but are anyhow preferable to the user (think of a large project that defines its own Path class)
