### ISSUE TITLE
"Arguments missing" for optional arguments

### ISSUE THREAD

**Issue by onnoeberhard** [microsoft/pylance-release#43]
I noticed that when I use a function with optional arguments I get an error message for "missing arguments". In this case, I was using the `subplots` function from the `matplotlib.pyplot` module. The actual error message was: `Arguments missing for parameters "nrows", "ncols"`.

The function signature (https://matplotlib.org/_modules/matplotlib/pyplot.html#subplots) defines default arguments for these parameters. However, it looks like the `pyplot.pyi` file contains only `def subplots(nrows: int, ncols: int, ...`.

## Environment data

-   Language Server version: 2020.6.1
-   OS and version: Windows (10.0.17763 Build 17763)
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.7

## Expected behaviour

(no error)

## Actual behaviour

(error)

**Comment by PrateekArya** [comment]
I got the same for using plt.hist() without "bins". Error message: Argument missing for parameter "bins"

**Comment by erictraut** [comment]
It sounds like your type stub file (`pyplot.pyi`) contains a bug. Where did you get that stub? I don't see it included in the matplotlib package, nor do I see it in typeshed. In any case, the correct fix here is to fix the bug in the type stub file.

**Comment by onnoeberhard** [comment]
The `pyplot.pyi` file is located here: `~/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/bundled-stubs/matplotlib/pyplot.pyi`. I don't know where it came from.

**Comment by PrateekArya** [comment]
I see the same issue with my type stub file.

![image](https://user-images.githubusercontent.com/1255663/86522402-5f665780-be5d-11ea-9edc-761e1b85930f.png)

![image](https://user-images.githubusercontent.com/1255663/86522405-6ab98300-be5d-11ea-9476-e56405ac6c82.png)

Should I just modify this here?

**Comment by jakebailey** [comment]
You can modify this in the bundle if you wish, but I expect to fix this.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202070-9-july-2020

**Comment by oembz123** [comment]
Same issue with ImageGrab.grab() from PIL
![image](https://user-images.githubusercontent.com/49533140/109087644-850ade80-7716-11eb-8471-da03a9c72b2b.png)

**Comment by jakebailey** [comment]
Can you file a new issue? That's not related to this old closed issue, and is a bug with a bundled stub we ship.
