### ISSUE TITLE
Incorrect typing error for Decimal operators

### ISSUE THREAD

**Issue by joshuamanns** [microsoft/pylance-release#430]
## Environment data

-   Language Server version: 2020.9.6
-   OS and version: MacOs 10.15.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.1

## Expected behaviour
```python
from decimal import Decimal
x = Decimal("2.5")
y = Decimal("3.2")
z = x + y
```
Standard mathematical operators between two "Decimal" objects should not produce typing errors.

## Actual behaviour
Using "basic" Type Checking Mode:

`Operator "+" not supported for types "Decimal" and "Decimal"Pylance (reportGeneralTypeIssues)`

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing. Perhaps you have some other "decimal" package installed that is overriding the stdlib version? If you click on `Decimal` and press F12 to "show definition", does it take you to the `decimal.pyi` stub file that ships with the Pylance extension?

**Comment by joshuamanns** [comment]
Looks like the problem is with the Datastax Cassandra driver Decimal column type. While it's treated like a regular Decimal under the hood, it is indeed different. I'll manage around it for now... thank you.
