### ISSUE TITLE
Python Intellisense Issues?

### ISSUE THREAD

**Issue by raffertyuy** [microsoft/pylance-release#4300]
## Environment data

-   Language Server version: v2023.4.40
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.3

## Code Snippet

Pylance is telling me I have errors when the code is working.
![image](https://user-images.githubusercontent.com/1037626/235437984-4886f421-7218-4ce5-9731-ce2e319370f5.png)

`client` here is an optional argument, but Pylance thinks it is required.
![image](https://user-images.githubusercontent.com/1037626/235438019-7320ffd8-f746-4297-825d-618e42987cf4.png)

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by cmaycumber** [comment]
I'm running into the same issue w/ `langchain` on mac OS

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
