### ISSUE TITLE
Const "is not accessed" when used in match case statement

### ISSUE THREAD

**Issue by veleek** [microsoft/pylance-release#4309]
## Environment data

-   Language Server version: PyLance: v2023.4.40 
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

```python
        # Errors occur if const exists in this file, or is imported from an external file.
        ZONE_CIRCLE = "circle"

        zone = None
        match type:
            case ZONE_CIRCLE:
                zone = CircleZone(config)
```

## Repro Steps

1. Write this case statement.

## Expected behavior

Match case statement should work properly

## Actual behavior

Two errors shown:

```
"ZONE_CIRCLE" is not accessedPylance

Irrefutable pattern is allowed only for the last case statementPylance

(constant) ZONE_CIRCLE: str  <- error hover info, just to verify the type.
```

replacing the constant `ZONE__CIRCLE` with the hard-coded string `"circle"`, causes both errors to go away.

**Comment by erictraut** [comment]
Pylance is correct here.

Your code doesn't do what you think it does.

When `ZONE_CIRCLE` is used within a `case`, it is considered a "[capture pattern](https://peps.python.org/pep-0634/#capture-patterns)". It is a local variable that receives the value of the subject expression. I'm guessing that you thought `ZONE_CIRCLE` would be interpreted as a [literal pattern](https://peps.python.org/pep-0634/#literal-patterns).

As evidence, run this code:

```python
ZONE_CIRCLE = "circle"

zone = None
match "square":
    case ZONE_CIRCLE:
        print(ZONE_CIRCLE)
```

It will print "square".

If the `match` statement is within an inner scope (such as a function), then `ZONE_CIRCLE` is a local variable that is distinct from the outer-scoped `ZONE_CIRCLE`.

```python
ZONE_CIRCLE = "circle"

def func():
    match "square":
        case ZONE_CIRCLE: # This is a local variable
            pass
```

**Comment by veleek** [comment]
Hmmm.... well that's especially confusing given that intellisense says that ZONE_CIRCLE is a constant string...

I read far too much of PEP634 and still wasn't able to figure it out, but I was able to coax ChatGPT into clarifying for me that the only way to accomplish this with a const is to ensure that the const uses a qualified name.

```
import types
consts = types.SimpleNamespace()
consts.A = 1
consts.B = 2
consts.C = 3

interface = 2

match interface:
    case consts.A:
        print("A")
    case consts.B:
        print("B")
    case consts.C:
        print("C")
```

This is oddly unintuitive, but thanks for helping me figure it out!
