### ISSUE TITLE
Error: Debug Failure. False expression: Check called before binding

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4310]
Found in telemetry for 2023.4.40, but has been occurring for at least several weeks.

Error: Debug Failure. False expression: Check called before binding</br>    at assert <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/sourceFile.ts#L1385'>pyright-internal/src/analyzer/sourceFile.ts:1385:8</a></br>    at check <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1317'>pyright-internal/src/analyzer/program.ts:1317:39</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>    at callback <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L48'>pyright-internal/src/common/logTracker.ts:48:19</a></br>    at log <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1258'>pyright-internal/src/analyzer/program.ts:1258:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/32cae6caa5aa38774b909cfa4e26c89ccba940c4/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1304'>pyright-internal/src/analyzer/program.ts:1304:33</a></br>

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023611-7-June-2023-PreRelease)
