### ISSUE TITLE
Report packages listed in requirements.txt that correspond to missing modules in the current environment  

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#4315]
This is an ask from the Python extension to help with https://github.com/microsoft/vscode-python/issues/20133 (https://github.com/microsoft/vscode-python/issues/21140)

The idea is that the Python extension would define a pip requirements language type, and mark *requirements*.txt files as a pip requirements language type. Pylance would then register its LS to access pip-requirements type either by language type or by using requirements path pattern, and then throw warnings for when packages listed there are not installed, and then send back a code action to trigger the create environment command.

**Comment by rchiodo** [comment]
I think we can do that if the user opens the requirements file, but what if they don't? (I don't imagine people commonly open that file when they're trying to resolve why they get an import error)

Wouldn't python still need these warnings to figure out what to install? I added a comment in the python extension issue about potentially implementing support for 'pulling' diagnostics for a file. I believe pylance currently only supports 'push'.

**Comment by luabud** [comment]
After talking about this offline, we decided to handle it on the Python extension side.
