### ISSUE TITLE
Google docstrings with type hints not displaying properly in hover window after version 2023.4.30

### ISSUE THREAD

**Issue by shiftysheep** [microsoft/pylance-release#4317]
## Environment data

-   Language Server version: 2023.4.40 and 2023.5.10
-   OS and version: Ubuntu
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.6

## Code Snippet
```python
def test(a: int, b: str) -> list:
    """Return a string of b for amount of a.

    Args:
        a (int): The amount of iterations.
        b (str): The string to multiply.
    Returns:
        A string of the outcome

    Examples:
        >>> test(3, "test")
        testtesttest
    """
    return b * a
```

## Repro Steps

1. Hover over references to function

## Expected behavior - <= 2023.4.30
Hover window should display each parameter/argument on an individual line. 

![working_docstring](https://user-images.githubusercontent.com/44270943/236139304-a725ad6f-2569-484a-9650-9b6a8a1130e5.jpeg)

## Actual behavior - 2023.4.40 and 2023.5.10
Hover window merges all arguments with `(type)` similar to markdown rendering. If type hints are removed from the docstring the hover window displays correctly.

![notworking_docstring](https://user-images.githubusercontent.com/44270943/236139308-1df040d0-6f7e-455c-94a3-471654537a45.jpeg)
Type hints removed:
![no_type_hints](https://user-images.githubusercontent.com/44270943/236141725-2c361d3c-2f24-4a12-a98e-910a70a46b2c.jpeg)

## Logs

No output

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.5.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023521-10-May-2023-PreRelease)

**Comment by zduvall** [comment]
Thanks for the updates and efforts on this!

Any possibility of extending this functionality to when there is more than one word inside the parenthesis? An example use case is when indicating that an argument is optional. Unfortunately, the lines collapse again into a single line in this case. I'm on version `v2023.5.30`.

Example:

<img width="753" alt="Screenshot 2023-05-18 at 11 55 57 PM" src="https://github.com/microsoft/pylance-release/assets/71565231/f8b0b5dc-edd7-4178-a7d4-ee630ae90709">

<img width="1107" alt="Screenshot 2023-05-18 at 11 56 09 PM" src="https://github.com/microsoft/pylance-release/assets/71565231/eb8c890a-5b9e-44d9-aa62-f484bddab9d9">

For further context, this follows the [google docstring format](https://github.com/NilsJPWerner/autoDocstring/blob/HEAD/docs/google.md) that [autoDocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) uses for optional kwargs.

Thoughts? Thanks!

**Comment by rchiodo** [comment]
> Any possibility of extending this functionality to when there is more than one word inside the parenthesis? 

I think that should be doable. Can you open a new issue?

**Comment by shiftysheep** [comment]
I also noticed if it's a complex type hint it doesn't format it still. 
![image](https://github.com/microsoft/pylance-release/assets/44270943/340997a1-afa1-4aa8-85d3-4ae02e004ced)
@zduvall did you open a new issue?

**Comment by zduvall** [comment]
Thanks! Just opened an issue [here](https://github.com/microsoft/pylance-release/issues/4395). Feel free to add a comment there as well if you'd like @shiftysheep.
