### ISSUE TITLE
Python type hinting TypeVarTuple example fails

### ISSUE THREAD

**Issue by Dylanb-dev** [microsoft/pylance-release#4323]
## Description

The example at https://docs.python.org/3/library/typing.html#typing.TypeVarTuple fails type checking with pylance in both basic and strict modes when it should pass.

## Environment data

-   Language Server version: pylance language server 2023.5.10 (pyright c400d889)
-   OS and version: ubuntu 22
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.3

## Code Snippet
```python
from typing import TypeVar, TypeVarTuple

T = TypeVar('T')
Ts = TypeVarTuple('Ts')

def move_first_element_to_last(tup: tuple[T, *Ts]) -> tuple[*Ts, T]:
    return (*tup[1:], tup[0])

# T is bound to int, Ts is bound to ()
# Return value is (1,), which has type tuple[int]
move_first_element_to_last(tup=(1,))
```
## Error
```json
[{
	"resource": ".../python-hints/type-hint.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportGeneralTypeIssues",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportGeneralTypeIssues"
		}
	},
	"severity": 8,
	"message": "Expression of type \"tuple[*tuple[T@move_first_element_to_last | Union[*Ts@move_first_element_to_last], ...], T@move_first_element_to_last | Union[*Ts@move_first_element_to_last]]\" cannot be assigned to return type \"tuple[*Ts@move_first_element_to_last, T@move_first_element_to_last]\"\n  Type \"T@move_first_element_to_last | Union[*Ts@move_first_element_to_last]\" cannot be assigned to type \"*Ts@move_first_element_to_last\"\n  Type \"T@move_first_element_to_last | Union[*Ts@move_first_element_to_last]\" cannot be assigned to type \"T@move_first_element_to_last\"",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 12,
	"endLineNumber": 7,
	"endColumn": 30
}]
```

**Comment by erictraut** [comment]
Pyright, the type checker upon which pylance is built, doesn't currently support slices that reference unpacked TypeVarTuples. To my knowledge, no other Python type checkers support this either. (Mypy emits a similar error.) So this was a bad example for the typing documentation to use.

PEP 646, which introduced `TypeVarTuple`, added significant complexity to Python type checking along with a bunch of very tricky and complex edge cases. Pyright supports all of the common uses cases and many less-common ones. Support for slices is not mandated by (or even discussed in) the PEP, and this is an edge case that is not supported. We could consider adding support for this in the future if there is demand.

To give you a sense for why this is tricky, a slice can reference any portion of a tuple, and tuple type definitions can contain both known-length and indeterminate-length entries. A TypeVarTuple is an example of an indeterminate-length entry. Slices can theoretically reference both known-length and indeterminate-length entries, and some of these slices can result in ambiguous types. For example, if the type of `tup` is `tuple[*tuple[str, ...], int]`, what is the type of `tup[:1]`? Is it `tuple[str]` or `tuple[int]`? It depends on the number of `str` entries, and that is statically unknowable.

This is the first time I've heard this feature requested. Do you see a need for this feature in code you're writing, or are you just curious why the sample didn't work?

**Comment by Dylanb-dev** [comment]
Thanks for the fast reply and context, I appreciate it.

> Do you see a need for this feature in code you're writing, or are you just curious why the sample didn't work?

I am learning the python type hinting system to try and reduce the amount of integration testing required for my programs.

Coming from more functional languages I like to use is the railroad/pipeline pattern to typecheck business logic.

The most ergonomic way to do this is with a `compose` or `pipe` function that takes a list of functions and type checks that each output matches the input of the next e.g.

```python
def numToString(x:int) -> str:
     return str(x)

def addOne(x:int):
     return x + 1

def stringToNum(x:int):
     return x + 1

# Currently have to do this
result = addOne(stringToNum(numToString(10)))

# If variadic generics were supported I could write this:
result = compose(addOne,  stringToNum, numToString) (10)
```
This would help reduce the potential for bugs in my software and require less integration tests need to be written as the type system is doing the integration checks for me.

**Comment by erictraut** [comment]
I don't think `TypeVarTuple` will help you with that coding pattern.

Something like this is probably what you're looking for:

```python
A = TypeVar("A")
B = TypeVar("B")
C = TypeVar("C")
D = TypeVar("D")
E = TypeVar("E")

@overload
def compose(cb1: Callable[[B], A], cb2: Callable[[C], B], /) -> Callable[[C], A]:
    ...

@overload
def compose(
    cb1: Callable[[B], A], cb2: Callable[[C], B], cb3: Callable[[D], C], /
) -> Callable[[D], A]:
    ...

@overload
def compose(
    cb1: Callable[[B], A],
    cb2: Callable[[C], B],
    cb3: Callable[[D], C],
    cb4: Callable[[E], D],
    /,
) -> Callable[[E], A]:
    ...

def compose(*args: Callable[[Any], Any]) -> Callable[[Any], Any]:
    ...
```

**Comment by Dylanb-dev** [comment]
Yeah that is standard and what is in most libraries, however the variadic generics of `TypeVarTuple` means we could have something like:

```python
import functools
from typing import TypeVar, TypeVarTuple

T = TypeVar('T')
Ts = TypeVarTuple('Ts')

def compose(*funcs: tuple[T, *Ts]):
    def reduceFuncs(value):
        firstFunc: T = funcs[0] 
        newValue = firstFunc(value)
        remainingFuncs: *Ts = funcs[1:]
        if(remainingFuncs):
            return compose(remainingFuncs)(newValue)
        else:
            return value
    return reduceFuncs
```

Perhaps I am just imagining that such a solution is possible.

**Comment by MiguelIbrahimE** [comment]
This error occurs because of the way the TypeVarTuple is defined. When using TypeVarTuple to define a tuple of type variables, you need to specify the minimum and maximum number of elements the tuple can have.

from typing import TypeVar, TypeVarTuple

T = TypeVar('T')
Ts = TypeVarTuple('Ts', int)

def move_first_element_to_last(tup: tuple[T, *Ts]) -> tuple[*Ts, T]:
    return (*tup[1:], tup[0])

move_first_element_to_last(tup=(1,))

**Comment by erictraut** [comment]
@Dylanb-dev, your `compose` function would work at runtime, but there's no way it would type check. Even if pyright evaluated the expression `funcs[1:]` as type `tuple[*Ts]`, it would not allow you to pass this to the recursive call `compose` because `tuple[*Ts]` is not type compatible with `tuple[T, *Ts]` (the input parameter type for `compose`). A static type checker has no way of knowing what types (or how many entries) `*Ts` represents. So, as I said, I don't think `TypeVarTuple` provides a solution to the problem you're trying to solve here.
