### ISSUE TITLE
Pylint client: couldn't create connection to server

### ISSUE THREAD

**Issue by pironem** [microsoft/pylance-release#4324]
Dear All,

I get the following issue with Pylint:

> 2023-05-05 16:17:09.363 [info] [Error - 4:17:09 PM] Server initialization failed.
> 2023-05-05 16:17:09.363 [info]   Message: Pending response rejected since connection got disposed
>   Code: -32097 
> 2023-05-05 16:17:09.363 [info] [Error - 4:17:09 PM] The Pylint server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
> 2023-05-05 16:17:09.364 [info] [Error - 4:17:09 PM] Pylint client: couldn't create connection to server.
> 2023-05-05 16:17:09.364 [info]   Message: Pending response rejected since connection got disposed
>   Code: -32097 
> 2023-05-05 16:17:09.364 [info] [Error - 4:17:09 PM] Restarting server failed
> 2023-05-05 16:17:09.364 [info]   Message: Pending response rejected since connection got disposed
>   Code: -32097 

 (see pylint.log for full details)

I have done the following trouble shooting in this order:
1. Switch to "python.languageServer": "Pylance",
2. Delete and re-install all the extensions and remove all the cache
3. Reset the entire VS by deleting:
    - .vscode
    -  Roaming/Code

Nothing worked

Please let me know if you need any further information

Thank you in advance for the help

Best Regards,
Matteo

## Environment data

Pylance: v2023.5.10 --> Pylance language server 2023.5.10 (pyright c400d889) starting
Pylint: v2023.4.0
Pyton: v2023.8.0
OS: Win10

## Logs

[PythonLanguageServe.log](https://github.com/microsoft/pylance-release/files/11407230/PythonLanguageServe.log)
[pylint.log](https://github.com/microsoft/pylance-release/files/11407231/pylint.log)

**Comment by rchiodo** [comment]
Pylint and pylance are actually separate extensions. Pylance doesn't actually have anything to do with pylint running. This would be a pylint bug:

https://github.com/microsoft/vscode-pylint/issues
