### ISSUE TITLE
pylance suggests a new unknown type for a variable.

### ISSUE THREAD

**Issue by ujjwalnur** [microsoft/pylance-release#4325]
<h3> Environment data </h3>

-   Language Server version: 2023.5.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda):  python 3.9.7  with Anaconda ( conda 23.3.1 )
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>
This code simply depends upon `pycocotools` package. More specifically it calls the file [coco.py](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py) for reading annotation files in JSON format.

Other than that, this code is self-contained to reproduce the issue.
```
import os
import argparse
import logging
from typing import Dict, List, Literal
from pycocotools.coco import COCO

parser = argparse.ArgumentParser(prog="Code to create TFRecords for MSCOCO dataset.")
parser.add_argument(
    "--coco_base_dir",
    required=True,
    type=str,
    help="Root folder holding the unzipped MSCOCO dataset.",
)

parser.add_argument(
    "--coco_year", required=True, type=str, help="Year of the COCO dataset."
)

parser.add_argument(
    "--coco_subset",
    required=True,
    choices=["train", "val", "test", "test-dev"],
    type=str,
    help='Subset for which to prepare TFRecords. One of "train", "test", "val" and "test-dev".',
)

parser.add_argument(
    "--save_dir", required=True, type=str, help="Path where to save TFRecords."
)

parser.add_argument(
    "--num_shards", required=True, type=int, help="Number of shards to create."
)


NUM_SHARDS: int = 0
SAVE_DIR: str = ""


COCO_BASE_DIR: str = ""
COCO_YEAR: str = ""
COCO_SUBSET: str = ""
COCO_IMAGE_FOLDER: str = ""
COCO_ANNOTATION: Dict = dict()
COCO_CATEGORY_TO_LOGITS_INDEX : Dict[int, int]= dict()


def validate_coco_args(
    coco_year: Literal["2014", "2015", "2017"],
    coco_subset: Literal["train", "test", "val", "test-dev"],
) -> None:
    """
    Validates the MSCOCO year and subset choice. It also sets the global variables
    COCO_YEAR, COCO_IMAGE_FOLDER and COCO_SUBSET which are used later on to create the
    TFRecords.


    For MSCOCO 2014 : allowed subsets ['train', 'val', 'test']
    For MSCOCO 2015 :  allowed subsets ['test', 'test-dev']
    For MSCOCO 2017 : allowed subsets ['train', 'val', 'test', 'test-dev']
    :param coco_year: Year of the MSCOCO dataset.
    :param coco_subset: Subset of the MSCOCO dataset.
    :raises: ValueError if the selected coco_year and coco_subset are not compatible with each other.
    """

    if coco_year not in ["2014", "2015", "2017"]:
        logging.error('coco_year must be one of "2014","2015" and "2017".')
        raise ValueError

    if coco_year == "2014":
        if coco_subset not in ["train", "val", "test"]:
            logging.error(
                'For MSCOCO 2014, the allowed subsets are "train", "val" and "test".'
            )
            raise ValueError

    if coco_year == "2017":
        if coco_subset not in ["train", "val", "test", "test-dev"]:
            logging.error(
                'For MSCOCO 2017, the allowed subsets are "train", "val", "test" and "test-dev".'
            )
            raise ValueError

    if coco_year == "2015":
        if coco_subset not in ["test", "test-dev"]:
            logging.error(
                'For MSCOCO 2015, the allowed subsets are "test" and "test-dev"'
            )
            raise ValueError

    global COCO_YEAR
    COCO_YEAR = coco_year
    global COCO_SUBSET
    COCO_SUBSET = coco_subset
    relevant_subset: Literal['train', 'test', 'val', 'test-dev'] = coco_subset
    if coco_subset == "test-dev":
        relevant_subset = "test"

    global COCO_IMAGE_FOLDER
    COCO_IMAGE_FOLDER = "{}{}".format(relevant_subset, coco_year)

    return None


def get_tfrecord_names(save_dir: str, num_shards: int) -> List[str]:
    """
    Returns the names of TFRecord files. These returned names are used to store the created TFRecord files.
    :param save_dir: Path to the folder where the TFRecords are saved.
    :param num_shards: Number of shards of TFRecord files.
    :return: A list of TFRecord file names.
    """
    file_names: list[str] = [
        "tfrecord-{}-of-{}.record".format(str(i).zfill(4), str(num_shards).zfill(4))
        for i in range(1, num_shards + 1)
    ]

    file_names = [os.path.join(save_dir, x) for x in file_names]
    return file_names


def get_coco_annotation_file() -> str:
    if not os.path.isdir(COCO_BASE_DIR):
        logging.error("The base path for the MSCOCO dataset was not found.")
        raise NotADirectoryError
    if COCO_SUBSET in ["test", "test-dev"]:
        filename: str = "image_info_{}{}.json".format(COCO_SUBSET, COCO_YEAR)
    else:
        filename = "instances_{}{}.json".format(COCO_SUBSET, COCO_YEAR)

    filename = os.path.join(COCO_BASE_DIR, "annotations", filename)
    return filename


def read_coco_data(coco_annotation_file: str) -> None:
    if not os.path.isfile(coco_annotation_file):
        logging.error(
            "The annotation file {} was not found.".format(coco_annotation_file)
        )
        raise FileNotFoundError

    global COCO_ANNOTATION
    global COCO_CATEGORY_TO_LOGITS_INDEX
    data = COCO(annotation_file=coco_annotation_file)
    cat_ids: list[int] = sorted(list(data.cats.keys()))
    for index, id in enumerate(cat_ids):
        COCO_CATEGORY_TO_LOGITS_INDEX[id] = index
    for image_id, image_info in data.imgs.items():
        COCO_ANNOTATION[image_id] = {
            "file_name": image_info["file_name"],
            "width": image_info["width"],
            "height": image_info["height"],
        }

        if COCO_SUBSET in ["train", "val"]:
            
            anns = data.imgToAnns[image_id]
            if not anns:
                logging.warning(
                    "The image {} with image_id {} does not have any annotations.".format(
                        image_info["file_name"], image_id
                    )
                )
            else:
                for index, annotation in enumerate(anns):
                    mask = data.annToMask(annotation)
                    anns[index][]
                    anns[index]["segmentation"] = mask
                    anns[index]["label_name"] = data.cats[anns[index]["category_id"]][
                        "name"
                    ]

                COCO_ANNOTATION[image_id] |= {"annotations": anns}

    return None
```

In this code, on line 156, pylance gives me the following type suggestion for `anns`

![issue](https://user-images.githubusercontent.com/130743548/236637013-58658a8b-ef7b-4f22-b178-0ce4c4a3a2ee.png)

**Comment:** I have no idea where does this `_Annotation` type come from. Essentially `anns` should be a `List[Dict]`. This is internally created by `pycocotools` and is guaranteed to be non-empty. There is no reference to `_Annotation` anywhere in my code or even in `pycocotools` after having checked the `coco.py` file in the `pycocotools` package. 

And a little later this corresponds to line 168 : 

![issue2](https://user-images.githubusercontent.com/130743548/236637065-dafbd5a8-cf80-46b1-8cc4-ee4f397dd886.png)

I understand the core of this issue. However, at no point of time I have declared anything like a `TypedDict`. I am simply working with `Dict` and `defaultdict`. So, what is the core of this behavior ? 

<h3> Expected behavior </h3>

pylance should not throw an error here.

<h3> Logs </h3>
[pylance_log.log](https://github.com/microsoft/pylance-release/files/11412957/pylance_log.log)

**Comment by erictraut** [comment]
Pylance is built on top of pyright, a static code analyzer. Pyright analyzes code based on the type information provided to it. You may find [this documentation](https://microsoft.github.io/pyright/#/type-concepts) for understanding the basics of static type annotations and type checking.

The type information for the `pycocotools` library comes from the [community-maintained typeshed project](https://github.com/python/typeshed/tree/main/stubs/pycocotools). Pylance bundles these typeshed "type stubs".

The `_Annotation` type comes from this type stub [here](https://github.com/python/typeshed/blob/a6ecf564b552b2d0cae7a747b7eab8cb4f90f21c/stubs/pycocotools/pycocotools/coco.pyi#L28). In particular, the `COCO` class has an instance variable `imgToAnns` that is annotated with the type `dict[int, list[_Annotation]]` [here](https://github.com/python/typeshed/blob/a6ecf564b552b2d0cae7a747b7eab8cb4f90f21c/stubs/pycocotools/pycocotools/coco.pyi#L63).

If you think that this type information is incorrectly represented in the typeshed stub, please file a bug in the [typeshed issue tracker](https://github.com/python/typeshed/issues) or consider submitting a PR to address the issue.

I suspect what happened here is that the authors of the type stub decided that it was useful to specific type information for the dict keys, which is possible only using a `TypedDict`. This means that a type checker will complain if you attempt to use a key that is not listed in the TypedDict definition. There's currently no way in the Python static type system to specify that a TypedDict should permit additional keys. Here's a recent discussion about this in the [typing-sig](https://mail.python.org/archives/list/typing-sig@python.org/thread/66RITIHDQHVTUMJHH2ORSNWZ6DOPM367/#AIBYTWKQHHVP2EYHZULI3MK4M5MB4VZA) (the forum for static type checking) if you're interested in the details.

If you find that static type checking errors are not useful, you can disable them in pylance by setting `python.analysis.typeCheckingMode` to "off".

Another option is to use a `# type: ignore` or `# pyright: ignore` comment to suppress this particular error.

**Comment by ujjwalnur** [comment]
@erictraut Is it possible to have some functionality where one could override a type annotation safely and PyLance accepts the override ? For instance, in line `156`, I could annotate `anns` as `List[Dict]` and then it should be fine. Currently, PyLance does not allow me to override this type annotation ( the reason is now clear to me !! ). 

Can something be done about it ?

**Comment by erictraut** [comment]
You cannot override a type annotation in another file, but you can override the evaluated type of an expression in your own code using the `typing.cast` function. For example, the expression `anns[index]` in your code sample evaluates to the type `_Annotation`, which is a TypedDict. If you want to override this with the type `dict[str, Any]`, you can do the following:
```python
cast(dict[str, Any], anns[index])["label_name"] = ...
```

**Comment by ujjwalnur** [comment]
Thanks a lot. It clarifies a lot of things for me. Indeed a better way to specify type restrictions. Helps in writing cleaner code.
