### ISSUE TITLE
Support go-to-implementation

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#4329]
### Discussed in https://github.com/microsoft/pylance-release/discussions/2642

<div type='discussions-op-text'>

<sup>Originally posted by **MalcolmMielle** April 29, 2021</sup>
Hi all,

The "find implementation" feature doesn't seem to work well. I have a method f in a class A that inherits from B and reimplements f, and I'd like to list all "f" implementation, but nothing gets listed.
Is the feature included in Pylance, and if yes, am I missing something?

Thanks,</div>

**Comment by fl0mb** [comment]
bump?

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.12.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202412100-16-December-2024-PreRelease)

**Comment by rchiodo** [comment]
Note that we're still discussing how this should behave. There's another issue here as a follow up:
https://github.com/microsoft/pylance-release/issues/6775

**Comment by disrupted** [comment]
will it also be possible to list all implementations?
