### ISSUE TITLE
After extracting class to a new file, pylance does not recognizes it.

### ISSUE THREAD

**Issue by diego-pm** [microsoft/pylance-release#4331]
## Environment data

-   Language Server version: v2023.5.10
-   OS and version: Windows 10 / WSL 2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8

## Repro Steps

1. Create a file `file1` with multiple classes, one of them called `A`.
2. In a file `file2`, import `A` from `file1`.
3. with the cursor focused on the name of the class in `file1`, ctrl+shift+r and select extract to new file.
4. Save the changes
5. Rename the new created file.

## Expected behavior

After renaming the automatically created file, the import statement in `file2` should also be updated to have the new name.

## Actual behavior

It is not renamed. This happens because pylance does not automatically recognize the extracted class.

If between steps 4 and 5 I restart the python language server, it all works as expected.

The ideal behaviour would be to not have to manually restart the language server in this situation.

Note: After renaming a file, I also need to manually restart the language server in order for pylance to recognize the changes.

**Comment by debonte** [comment]
I'm not able to repro this. Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

> This happens because pylance does not automatically recognize the extracted class.

What leads you to this conclusion? I'm not saying you're wrong, but it would be surprising.

Btw, after renaming the file, do you see the dialog shown in the screenshot below? Either when following the repro steps as written, or when you restart Pylance between steps 4 and 5?

![image](https://github.com/microsoft/pylance-release/assets/12820898/621ec263-5a37-46ac-9a7d-57b9213de883)
