### ISSUE TITLE
How to ignore `param is not accessed`

### ISSUE THREAD

**Issue by jugmac00** [microsoft/pylance-release#434]
The param is not used in this method, but the signature is there so one can override the method and then the param is necessary.

What kind of comment do I have to add to ignore this error?

Thank you!

![Screenshot from 2020-09-30 16-23-06](https://user-images.githubusercontent.com/9895620/94699289-73c1cf80-033a-11eb-994e-1011d95784a3.png)

**Comment by erictraut** [comment]
Pylance doesn't report an error for this condition. You will never see it reported in the "Problems" panel or see an underlined squiggle. Pylance is telling VS Code to display the text "grayed out" as a subtle way of informing you that the variable is not accessed in this particular context. There's no way to disable this functionality.

**Comment by jugmac00** [comment]
Thank you, once again @erictraut

**Comment by sglbl** [comment]
I think after 5 years, at least there should be a way to ignore this.
