### ISSUE TITLE
Improve error message when symbol fails to be moved to an existing file 

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#4345]
When we try to move a symbol to a file but there's already a symbol with the same name there, we seem to be failing silently. It'd be nice if we could show an error message saying something like "A symbol with the same name already exists in the destination file."

To reproduce this silent fail behaviour, just create two files that contain symbols with the same name: 

a.py:

```
x = 1
```
b.py

```
x = 2
```

And then try to move x from the a.py file to the b .py file.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.2.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20242103-22-February-2024-PreRelease)
