### ISSUE TITLE
Failed to update setting 'python.analysis.typeCheckingMode'. No permission to mkdir

### ISSUE THREAD

**Issue by lxrswdd** [microsoft/pylance-release#4346]
Failed to update setting 'python.analysis.typeCheckingMode'.  Error: Unable to write file 'vscode-remote://ssh-remote+ward-lambda01.xxx/.vscode/settings.json' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/.vscode')

Currently, I am running remote access to a server in my school I replaced the address with 'xxx' for security reasons. 
It appears that both Intellisense and Copilot do not work because of this issue. Pylance is trying to make a directory in a place where I do not have permission to do so. Do you know how I can solve this problem? 

Can I request to do it at "/home/guest" as it is where '.vscodeserver' locates?
It is weird that I can find the following directory
"/home/guest/.vscode-server/data/Machine/settings.json"

**Comment by heejaechang** [comment]
@lxrswdd is it just error message box you are talking about or is pylance actually crash?

**Comment by heejaechang** [comment]
@bschnurr why would it try to update machine setting.json instead of workspace setting.json? any idea?

**Comment by heejaechang** [comment]
> why would it try to update machine setting.json instead of workspace setting.json? any idea?

@bschnurr my bad, it is actually opposite. we, by default, try saving it to `workspace folder`, but for this user case, it had to be saved in `global`

@lxrswdd can you explicitly add `'python.analysis.typeCheckingMode` to your user setting? then we will use that instead of creating one in `workspace`

**Comment by lxrswdd** [comment]
@heejaechang 
Thank you for responding. So currently "/home/guest/.vscode-server/data/Machine/settings.json" contains following 
```
{
    "python.analysis.autoImportCompletions": true,
    "python.analysis.diagnosticSeverityOverrides": {


    },
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.completeFunctionParens": true,
    "python.analysis.addImport.exactMatchOnly": true
}
```
However, none of the autocomplete or suggestions pops up when I am writing codes.  It suggests that it is enabled for my SSH address and with an activation time of 156ms

**Comment by lxrswdd** [comment]
[pylance log.txt](https://github.com/microsoft/pylance-release/files/11455061/pylance.log.txt)
@heejaechang 
Here you go, please see the attached .txt file

**Comment by heejaechang** [comment]
this is happening because we think your project root is `\` of your remote server.

```
2023-05-11 10:52:12.122 [info] [Info  - 10:52:12 a.m.] (667788) Search paths for /
```

due to that we are walking whole hard drive of your remote server

you can see from the log, we output this

```
2023-05-11 10:52:22.123 [info] [Error - 10:52:22 a.m.] (667788) Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
```

either set `exclude` or `include` in `setting.json` or in `pyrightconfig.json` or better don't open entire hard drive of the remote server.

we are not responding probably because we are still scanning server's hard drive.

**Comment by lxrswdd** [comment]
@heejaechang 
Thank you for solving the problem!
