### ISSUE TITLE
Why did I lose semantic highlighting?

### ISSUE THREAD

**Issue by marcelo-xiatech** [microsoft/pylance-release#4348]
<h3> Environment data </h3>

-   Language Server version: 2023.5.21
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by bschnurr** [comment]
without any repro step or logs, there is not much we can do here.

Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by marcelo-xiatech** [comment]
Closed. It was after the theme changing.
