### ISSUE TITLE
使用Pylance后函数无法自动补全括号

### ISSUE THREAD

**Issue by isinvon** [microsoft/pylance-release#4353]
Type: <b>Bug</b>

使用pylance后输入函数无法补全括号, 例如输入input,print按回车之后无法自动补全括号, 我的python.languageServer已经设置为Pylance了但是依旧不起作用.

Translation: After using Pylance, the `input` function cannot complete the parentheses, for example, input `input`, `print` cannot automatically complete the parentheses after pressing enter, my `python.languageServer` has been set to `Pylance` but still does not work.

Extension version: 2023.5.20
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (6.34GB free)|
|Process Argv|--crash-reporter-id 2123c431-83b9-47c8-b7dc-2d65961922ff|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstrcf:30731970
fixhidewlkth:30730051
hidesbindicator:30730055

```

</details>

**Comment by bschnurr** [comment]
Please provide a simple code example

请提供一个简单的代码示例

**Comment by isinvon** [comment]
Uploading PylanceTest.mp4…

**Comment by isinvon** [comment]
https://github.com/microsoft/pylance-release/assets/123001648/8d838e0d-6cab-4083-8b64-22a6542af6b6

**Comment by debonte** [comment]
Do you have the `python.analysis.completeFunctionParens` config setting set to `true`?

**Comment by isinvon** [comment]
在视频中,我的setting.json文件中python.analysis.completeFunctionParens是已经设置为true的,
并且"python.languageServer"设置为"Pylance",

**Comment by isinvon** [comment]
但是当我卸载掉Pylance之后, 将"python.languageServer"设置为"Default"或者"Jedi"是可以触发自动补充函数括号的, 这个情况我经过多次试验证实.

**Comment by debonte** [comment]
Can you confirm (ex. via the settings UI) that you don't have `completionFunctionParens` set anywhere else (ex. workspace `settings.json`)?

![image](https://github.com/microsoft/pylance-release/assets/12820898/76956643-2911-4f69-aaf8-0ff503ca55e6)

**Comment by isinvon** [comment]
OMG! I see. The problem has been solved. Thank you very much!O(∩_∩)O
