### ISSUE TITLE
pandas TimeStamp.strftime() missing argument

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#436]
## Environment data

-   Language Server version: 2020.9.6
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.5

## Expected behaviour

No error

## Actual behaviour

```python
import pandas as pd

ts = pd.Timestamp("9/30/2020")
fmt = ts.strftime("%Y-%m-%d")
print(fmt)
```
reports on the `strftime` call
```
Expected 0 positional arguments
```

Note - there is an error in the pandas docs, and I created an issue for that:  https://github.com/pandas-dev/pandas/issues/36745

Possible fix:
```
diff __init__.pyi.ORIG __init__.pyi
243c243
<     def strftime(self) -> str: ...
---
>     def strftime(self, fmt:str) -> str: ...
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020100-7-october-2020
