### ISSUE TITLE
'reportOptionalMemberAccess' wrong report

### ISSUE THREAD

**Issue by yingshaoxo** [microsoft/pylance-release#4360]
Error
```
"name" is not a known member of "None"    Pylance[reportOptionalMemberAccess](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalMemberAccess)
(variable) name: str | None
```

___

Source Code
```python
from dataclasses import dataclass
from typing import Any

@dataclass()
class An_Object():
    id: str | None = None
    name: str | None = None
    description: str | None = None


@dataclass()
class Delete_Object_Request():
    an_object: An_Object | None = None

    _property_name_to_its_type_dict = {
        "an_object": An_Object,
    }

    @dataclass()
    class _key_string_dict:
        an_object: str = "an_object"

    def from_dict(self, dict: dict[str, Any]):
        # new_variable: Delete_Object_Request = super().from_dict(dict)
        # return new_variable
        return None

def main():
    item = Delete_Object_Request()
    if (item.an_object.name == None):
        print("ok")
```

![image](https://github.com/microsoft/pylance-release/assets/17190829/82113b50-fc7c-4362-8df7-a1153e736937)

**Comment by erictraut** [comment]
Can you provide a minimal, self-contained code sample that reproduces the behavior you're seeing? The code above references `YRPC_OBJECT_BASE_CLASS`, which is not defined. The screen shot also differs from the provided code, so it's not clear how `item` in the screen shot relates to the code above.

**Comment by yingshaoxo** [comment]
> Can you provide a minimal, self-contained code sample that reproduces the behavior you're seeing? The code above references `YRPC_OBJECT_BASE_CLASS`, which is not defined. The screen shot also differs from the provided code, so it's not clear how `item` in the screen shot relates to the code above.

Now I know where is the problem.

```python
    # wrong code
    if (item.an_object.name == None):
        print("no")

    # right code
    if (item.an_object != None and item.an_object.name == None):
        print("no")
```

___

I wonder why the python community still refuse to use this syntax:
```python
if (item?.an_object?.name == None):
    print("no")
```
___

Can you do me a favor to raise this issue again in the python repo?

https://github.com/python/cpython/issues/103128
