### ISSUE TITLE
Notification: analyze

### ISSUE THREAD

**Issue by Hugloss** [microsoft/pylance-release#4364]
Type: <b>Bug</b>

1. Start VS Code
2. View in Status bar for notification
3. It's analyze more files than I have in the open folder.
I have 6 files but it's analyze over 50 and the computer is than so slow that I can't use it
4. Wait for analyze to complete and than I can start working.

<img width="235" alt="vscode" src="https://github.com/microsoft/vscode-python/assets/17194107/86e8eded-1c0d-4c03-ba0d-55961b789f53">

Extension version: 2023.8.0
VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (11.88GB free)|
|Process Argv|--enable-proposed-api genuitecllc.codetogether --enable-proposed-api genuitecllc.codetogether-onpremises|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bschnurr** [comment]
Please provide a self contained code sample that reproduces the issue.
see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue


Also if you haven't already done so I suggest setting analysis diagnostic mode to open files only.
![image](https://github.com/microsoft/pylance-release/assets/1946977/44f34bc0-06a3-4a38-aaef-84690575f2ee)

**Comment by Hugloss** [comment]
> Please provide a self contained code sample that reproduces the issue. see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
> 
> Also if you haven't already done so I suggest setting analysis diagnostic mode to open files only. ![image](https://user-images.githubusercontent.com/1946977/238418536-44f34bc0-06a3-4a38-aaef-84690575f2ee.png)

Analysis diagnostic mode was "open files only"

Hard to reproduced.
Often happends when I just leave the computer for some time and do nothing.

**Comment by Hugloss** [comment]
The mode is still "open files only" but it search in "other files" also.

![image](https://github.com/microsoft/pylance-release/assets/17194107/940eca1a-d8f8-4fea-b83c-368e96d61f51)

Code is in this repo:
https://github.com/Hugloss/CryptoDetails

If I than later open a file,  "problems" is refreshed and most of them disapear. This picture is just after I have open and closed som files of the files.
![image](https://github.com/microsoft/pylance-release/assets/17194107/86e4bee1-8ce2-487b-a295-9a40b9396c4d)

**Comment by bschnurr** [comment]
RSA_02_crack isn't there anymore but RSA_01 doesn't seem to have this issue.

Is this fixed for you?

**Comment by Hugloss** [comment]
Switched a while ago and then it was still there, but I see that there is a new version now (v2023.8.20). 😊
It doesn’t go haywire right away, but it does so while coding. I’ve never been able to understand why/when it starts, but it always disappears when I just switch to Jedi. 
Switching to Pylance and start coding (testing).

**Comment by Hugloss** [comment]
cannot be reproduced any longer

**Comment by WGYi** [comment]
@Hugloss  I have the same problem, how did you solve it?
