### ISSUE TITLE
Cannot instantiate a sub class of abstract type

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#437]
## Environment data

-   Language Server version: 2020.9.6
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.5

## Expected behaviour

no error

## Actual behaviour

```python
from abc import ABC, abstractmethod
from typing import Type


class Base(ABC):
    @abstractmethod
    def foo(self, x: int) -> int:
        pass


class Sub(Base):
    def foo(self, x: int) -> int:
        return 2 * x


whichclass: Type[Base] = Sub

print(whichclass().foo(10))
```
reports
```
Cannot instantiate abstract class "Base"
  "Base.foo" is abstract
```

`mypy` is OK with the above code, and it certainly is valid python.  My understanding of the `Type[Base]` means that you have a class that is a subtype of `Base`, which you can instantiate.

**Comment by jakebailey** [comment]
On which line is that error reported? The `foo` call, or at the assignment?

Depending on the narrowing, `withclass` may be `Type[Base]` or `Type[Sub]`, and you can't just call `foo()` on `Base` because it's abstract.

**Comment by erictraut** [comment]
There are two issues here:
1. Type narrowing is not being applied correctly in this case. I'm working on a fix.
2. Even if type narrowing is not applicable, I think it's reasonable to expect that the abstract class instantiation rule should not generate an error when Type[X] is used. In other words, I think we need to differentiate between these two cases:

```python
def foo1(a: Type[Base]):
    return a()

def foo2():
    return Base()
```

**Comment by erictraut** [comment]
I've fixed problem 2 that I mentioned above. The type narrowing issue (1) is in progress.

**Comment by jakebailey** [comment]
@erictraut Did you ever come back to look at (1)?

**Comment by jakebailey** [comment]
Must have at some point:

![image](https://user-images.githubusercontent.com/5341706/106977671-9e200100-670f-11eb-9180-d8d34ed4d20d.png)

**Comment by erictraut** [comment]
Yes, this is fixed. I must have forgotten to update the issue.
