### ISSUE TITLE
Analysing raw string

### ISSUE THREAD

**Issue by ZhouJinXuan24** [microsoft/pylance-release#4373]
Type: <b>Feature Request</b>

This may be a minor case, but I want to report it anyway. 
Raw strings in Python have two uses: regular expressions and raw strings (which have no escape characters). But apparently Pylance only parses raw strings as regular expressions. 
Maybe it's good to do some actions to determine whether a string is being used as a raw string or a regular string, and for the former, it can stop showing the escape characters.

Extension version: 2023.5.21
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by rchiodo** [comment]
Thanks for the suggestion, but I'm not sure what you mean by Pylance only parses raw strings as regular expressions? Are you talking about colorization?

I don't believe we actually do any colorization of raw strings:

![image](https://github.com/microsoft/pylance-release/assets/19672699/97cf9120-182b-4876-92d2-54f7d7966c78)

The entire string is just one token type and it looks like this is controlled by the grammar shipped with VS code. (Textmate tokens are provided by VS code)

**Comment by rchiodo** [comment]
You should log your issue on VS code as it ships the textmate grammar. The issue reproduces without Pylance installed.

**Comment by rchiodo** [comment]
See this issue which seems very similar to yours. It sounds like this is on purpose:
https://github.com/microsoft/pylance-release/issues/1862
