### ISSUE TITLE
editor.formatOnType does not work

### ISSUE THREAD

**Issue by fireattack** [microsoft/pylance-release#4378]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I enabled editor.formatOnType. But it does not format on type.

For exmaple, I type `a = 1      + 1`, then nothing happens.

`editor.formatOnSave` works (if I save the above file, it formats to `a = 1 + 1`.

## Steps to reproduce:

1. Enable formatOnType by 
```
{
    "[python]": {
        "editor.formatOnType": true,
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "ms-python.python"
    }
}
```
2. Create a new py file, and type in `a = 1      + 1` then enter (newline).
3. It should format it to `a = 1 + 1`. But it does not.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.1
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Nothing.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.8.0
VS Code version: Code - Insiders 1.79.0-insider (9233de805c8fb05fad4d9d1c15f22fbca85430ad, 2023-05-16T10:44:42.423Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600K (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (15.25GB free)|
|Process Argv|--crash-reporter-id ec59ae88-55f6-4589-8133-a873b1b9d699|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
azdwalk:30721579
pythonms35:30671666
a2ce3375:30680469
57b77579:30687741
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by debonte** [comment]
@fireattack, Pylance's `formatOnType` implementation does not perform general document formatting (ex. [PEP 8](https://peps.python.org/pep-0008/)). It only supports two scenarios at the moment:
1. Auto-indent -- When you press `Enter`, automatically decides how the cursor should be indented on the new line.
2. Auto format strings -- Automatically adds an `f` prefix on a string if you type `{` within it. Enabled via `python.analysis.autoFormatStrings`.

These features are intended to streamline your typing process by automating syntactically important changes as you type. If your goal is to ensure formatting consistency across your files, then `formatOnSave` using a dedicated formatter (ex. black) is a better option.

**Comment by fireattack** [comment]
Thanks for the explanation.
