### ISSUE TITLE
python.analysis.exclude does not override python.analysis.include

### ISSUE THREAD

**Issue by BaconPancakes** [microsoft/pylance-release#4380]
<h3> Environment data </h3>

-   Language Server version: 2023.5.20
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```json
        "python.analysis.include": [
            "my_lib"
        ],
        "python.analysis.exclude": [
            "my_lib/.venv"
        ],
```

<h3> Expected behavior </h3>

.venv is not counted as a source file for analysis/indexing

<h3> Actual behavior </h3>

.venv is indexed (goes over the 2000 file limit, annoyingly)

<h3> Logs </h3>

Sorry, can't expose the paths that are printed in trace log.

**Comment by heejaechang** [comment]
it should be supported. if it is not working. can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

or even better is sample project that repoes it.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
