### ISSUE TITLE
pylance can't be terminated

### ISSUE THREAD

**Issue by song-zhang** [microsoft/pylance-release#4383]
Hi, I often have a problem, my pylance extension process can't be terminated, this lead to my container can't be terminated and released.
Is this a common problem, how can I workaround it? Thank you.

## Environment data

-   Language Server version: pylance v2022.7.30
-   OS and version: cenos7
-   Python version (& distribution if applicable, e.g. Anaconda): python3.8

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
