### ISSUE TITLE
restart server

### ISSUE THREAD

**Issue by hmouradova** [microsoft/pylance-release#4385]
<h3> Environment data </h3>

-   Language Server version: 2023.5.30
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue but this isn't enough information for us to fix the problem.

Could you attach the logs as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

And provide repo steps. Thanks.

**Comment by Avasam** [comment]
Open Command Palette (default is `CTRL+Shift+P`)
![image](https://github.com/microsoft/pylance-release/assets/1350584/a6af01c0-85a4-4c18-b22b-620837b96761)

Then `Python: Restart Language Server`
![image](https://github.com/microsoft/pylance-release/assets/1350584/f7e92b4f-0e3d-4583-9021-73b23ed3f05e)

**Comment by rchiodo** [comment]
Thanks but that doesn't tell us if there's a problem? That restart language server command works for me. Are you saying it does nothing for you? It's supposed to restart the pylance language server.

**Comment by Avasam** [comment]
I was answering OP, I have updated my comment to make that clearer. There's not much you can do with an issue this vague.

**Comment by rchiodo** [comment]
Thanks didn't realize you weren't the original poster.
