### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Nineteeen92** [microsoft/pylance-release#4397]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2023.5.30`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.78.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Dell/AppData/Local/Temp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rchiodo** [comment]
Thanks for the issue, but you need to attach the file asked for or there's nothing we can do.
