### ISSUE TITLE
Jupyter `2023.3.1201040234` extremely high memory usage causes disconnect with remote SSH workstation

### ISSUE THREAD

**Issue by mrburrito** [microsoft/pylance-release#4403]
I run VSCode on a Windows machine using the Remote SSH extension to work with code on a Linux server with 32GB of RAM. When I updated the Python extension this morning to 2023.6.0, I started seeing continual disconnects from my remote code every time I tried to save a file. I tried removing the remote server (`~/.vscode-server`) as that was a suggested fix. This appeared to work until I realized none of my extensions were installed. As soon as I installed extensions, the problem reappeared. Every time I would try to save a Python file, I'd see a popup saying "Saving File: Running Python formatter..." which would spin forever until the remote connection timed out and could not be re-established.

I started investigating on the remote server and, as soon as I hit save, memory usage shot up from 2GB to 31GB.

I downgraded the Python extensions to:
- Python: 2023.4.1
- Pylance: 2023.3.40
- Jupyter: 2023.3.1000892223

With that configuration, memory usage shoots up to 8GB then settles back down to 5GB and everything appears to function as it did before.

I'm going to investigate further to see if I can narrow down exactly which of those three extensions is causing the issue, but it appeared I needed to back all of them down to fix the problem.

**Comment by debonte** [comment]
@mrburrito, are you still seeing this issue? If so, and censoring the Pylance log is too much hassle, would you be willing to provide a log to me directly? I can provide my email address.
