### ISSUE TITLE
why not pylance show torch.sum 's docstring?

### ISSUE THREAD

**Issue by gigberg** [microsoft/pylance-release#4410]
![image](https://github.com/microsoft/pylance-release/assets/81040793/2e6e5367-9305-4ae4-ab36-0e10fd84e757)

pytorch write most of their code in cpp, with many add_docstr(func, "some text") calls in[ torch/_torch_docs.py](https://sourcegraph.com/github.com/pytorch/pytorch@main/-/blob/torch/_torch_docs.py?L7558:1) to supply enough docstring for their cpp function's usage, which could be print use help() function.

For example, as the picture show, I'd like to review torch.sum 's docstring, however pylance only show some stub hints, is there any method show the docstring in pylance?

**Comment by heejaechang** [comment]
that's because the `pyi` shipped with `torch` doesn't have `doc string` in them and we can't get those doc strings from `native modules`

**Comment by heejaechang** [comment]
since `torch` ship with its own `pyi` stubs, we can't do what we do for `pandas`. we either need to invent some new mechanism only for `doc string` or need to ask `torch` team to add doc string on their `pyi` stubs even if that is not the standard.

**Comment by gigberg** [comment]
> 

thanks for you explanation
