### ISSUE TITLE
Wrong hover type hint and missing warning on bad import

### ISSUE THREAD

**Issue by tweakimp** [microsoft/pylance-release#4411]
When trying to import `func2` in file `b.py`, an `ImportError` will be raised. However, Pylance's hover type hint shows that `func2` is of type `Any` (which suggests it exists) and does not warn that `func2` can not be imported.

![grafik](https://github.com/microsoft/pylance-release/assets/20489521/94536e69-8fb8-4b16-884b-1017d29ef225)

## Environment data

-   Language Server version: v2023.5.30
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.0

## Code Snippet

```python
# file a.py
def func1():
    return 1
```
```python
# file b.py
from a import func1, func2

func1()
func2()
```

## Repro Steps

1. Hover cursor over `func2`.

## Expected behavior

Pylance shows `Import func2 could not be resolved.` and hover does not show anything or also a warning.

## Actual behavior

No warning or error message about the bad import and hover implies imported object `func2` is of type `Any`.

## Logs

[Pastebin](https://pastebin.com/h1TSPMh6)
Python Language Server logs are too long and I cant put them in this issue.
`Comment is too long (maximum is 65536 characters)` 
`There was an error creating your Issue: body is too long (maximum is 65536 characters).`

**Comment by tweakimp** [comment]
I just noticed that with `"python.analysis.typeCheckingMode": "basic" or "strict"`, Pylance does warn me:
![grafik](https://github.com/microsoft/pylance-release/assets/20489521/a8ce33e6-8fe7-4ea7-8fc6-cc97fd4721bb)
But is it expected that the import check only works when type checking is on?

**Comment by StellaHuang95** [comment]
Hi @tweakimp, thanks for the issue. Yes, that behavior is expected. When the `typeCheckingMode`  is set to `off`, many diagnostic rules are disabled, which is why you're not seeing the errors. You can also refer to this documentation for more information on which diagnostic rules are enabled in different type checking modes. https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults.
