### ISSUE TITLE
Make the file count limit for indexing configurable

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#4417]
### Discussed in https://github.com/microsoft/pylance-release/discussions/3036

<div type='discussions-op-text'>

<sup>Originally posted by **LeBoucEtMistere** June 15, 2022</sup>

## Environment data

-   Language Server version: 2022.6.11, vscode over ssh
-   OS and version: Ubuntu 20.04.3 LTS 
-   Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.18 (Proprietary codebase, cannot give more details on packages and such)

Pylance config:
```
{
    "python.analysis.indexing": true,
    "python.languageServer": "Pylance",
    "python.formatting.provider": "black",
    "python.analysis.useLibraryCodeForTypes": false
}
```

## Problem statement

Running Pylance through the official extension, in a large proprietary Python Monorepo, in a python2 virtualenv. Symbol search (Cmd+T) takes more than a minute to find symbols. However Cmd+Clicking a symbol in the code is working instantaneously. From the logs I can read, the index size reaches its limit causing VSCode to drop index cache.

## Repro Steps

Repo I use is private and proprietary, cannot share any reproduction steps. At least 13k python files in the repo.

## Expected behavior

Symbol search being fast. In particular, PyCharm is able to handle this repo properly and its symbol search is working as expected while VSCode is not.

## Actual behavior

Symbol search unusably slow

## Logs

```
[Info  - 8:35:38 AM] (708066) Pylance language server 2022.6.11 (pyright bbc42826) starting
[Info  - 8:35:38 AM] (708066) Server root directory: /home/arthur.depasse/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.11/dist
Notebook support: Legacy
[Info  - 8:35:38 AM] (708066) No configuration file found.
[Info  - 8:35:38 AM] (708066) pyproject.toml file found at <redacted-repo>.
[Info  - 8:35:38 AM] (708066) Setting pythonPath for service "<redacted-repo>": "/home/arthur.depasse/<obfuscated-repo>/venv2/bin/python"
[Info  - 8:35:38 AM] (708066) Loading pyproject.toml file at /home/arthur.depasse/<redacted-repo>/pyproject.toml
[Error - 8:35:38 AM] (708066) Pyproject file "/home/arthur.depasse/<redacted-repo>/pyproject.toml" is missing "[tool.pyright]" section.
[Warn  - 8:35:38 AM] (708066) stubPath /home/arthur.depasse/<redacted-repo>/typings is not a valid directory.
[Info  - 8:35:38 AM] (708066) Python version 2.7 from interpreter is unsupported
[Info  - 8:35:38 AM] (708066) Assuming Python platform Linux
[Info  - 8:35:39 AM] (708066) Searching for source files
[Info  - 8:35:39 AM] (708066) Auto-excluding /home/arthur.depasse/<redacted-repo>/venv2
[Info  - 8:35:40 AM] (708066) Found 12970 source files
[Info  - 8:35:40 AM] (708066) Background analysis(1) root directory: /home/arthur.depasse/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.11/dist
[Info  - 8:35:40 AM] (708066) Background analysis(1) started
[Info  - 8:35:40 AM] (708066) Indexer background runner(2) root directory: /home/arthur.depasse/.vscode-server/extensions/ms-python.vscode-pylance-2022.6.11/dist (index)
[Info  - 8:35:40 AM] (708066) Indexing(2) started
[Info  - 8:35:44 AM] (708066) [BG(1)] Long operation: getSemanticTokens full at /home/arthur.depasse/<redacted-repo>/<redacted-file>.py (2773ms)
[Info  - 8:35:44 AM] (708066) [IDX(2)] Long operation: index execution environment /home/arthur.depasse/<redacted-repo> (3302ms)
[Info  - 8:35:44 AM] (708066) [IDX(2)] Long operation: index libraries /home/arthur.depasse/<redacted-repo> (4293ms)
[Info  - 8:35:44 AM] (708066) Indexer done(2). indexed 516 files
[Warn  - 8:36:55 AM] (708066) Workspace indexing has hit its upper limit: 2000 files
```
</div>

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.5.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023551-31-May-2023-PreRelease)

See the new setting:

```json
"python.analysis.userFileIndexingLimit": 2000
```

for changing the limit.
