### ISSUE TITLE
How to disable auto imports?

### ISSUE THREAD

**Issue by theoturner** [microsoft/pylance-release#443]
I appreciate the time and effort that has gone to develop this highly requested feature, however it has caused me several unwanted imports that I only discover at build time and I would like to disable it. How do I do so?

**Comment by theoturner** [comment]
"python.analysis.autoImportCompletions": false

**Comment by jakebailey** [comment]
While you can of course disable the feature, we'd always appreciate feedback as to how we can improve it.
