### ISSUE TITLE
Find All Refereences does not work across multi-root projects

### ISSUE THREAD

**Issue by adampauls** [microsoft/pylance-release#4431]
Type: <b>Bug</b>

Same issue as https://github.com/microsoft/vscode-cpptools/issues/4711 but for Python.

# Behaviour

I have a multiroot workspace for a Python mono repo. There is a `root` folder with `project1` and `project2` as subfolders. I have a multi-root workspace where all of `.`, `project1`, and `project2` are included. I understand this to be the recommended usage, though there are [complaints](https://github.com/microsoft/vscode-python/issues/21204). 
## Expected vs. Actual

If a method is defined in `project1` and used in `project2`, then `Go to Definition` works fine when inside `project2`, but `Go to References` in `project1` only finds references in `project1`. 

## Steps to reproduce:

My `.vscode/xxx.code-workspace` file looks like:

```
{
	"folders": [
		{
			"path": ".."
		},
		{
			"path": "../project1"
		},
		{
			"path": "../project2"
		}
	],
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Poetry
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

formatting
• provider: "black"

testing
• pytestEnabled: true

```

</p>
</details>

Extension version: 2023.8.0
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T15:00:40.428Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|96.00GB (23.69GB free)|
|Process Argv|--crash-reporter-id 62f96d30-d764-40b0-b095-bd6a36a1295e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

```

</details>

**Comment by heejaechang** [comment]
@adampauls this is currently not supported. that said, there is on-going requests - https://github.com/microsoft/pylance-release/discussions/2585

you should upvote that enhancement request, so the enhancement request is properly prioritized.
