### ISSUE TITLE
"object*" is not iterable on list[np.ndarray]

### ISSUE THREAD

**Issue by yanxke** [microsoft/pylance-release#4436]
```
import numpy as np

def foo(a: list[float], b: list[float]):
    for i, j in zip(a, b):
        print(i, j)


def bar(a: list[float], b: list[np.ndarray]):
    for i, j in zip(a, b):
        print(i, j)

```

![image](https://github.com/microsoft/pylance-release/assets/25883626/751a1973-46ea-48c4-80f1-3a16bc57a73c)

foo() seems okay, bar() gives an error.

## Environment data

Version: v2023.5.40
Windows 11
Python 3.10.6

**Comment by rchiodo** [comment]
Thanks for the issue. This was actually fixed in last week's pre-release: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/vscode-pylance/2023.5.41/vspackage
