### ISSUE TITLE
ctypes IntelliSense/Autocomplete

### ISSUE THREAD

**Issue by TheRealQuantam** [microsoft/pylance-release#4437]
**Describe the feature you are requesting**
Python has by far the best support for binary structured data of any scripting language I'm familiar with in ctypes - better even than many compiled languages. PTVS supports IS/AC for classes, named tuples, and probably others I'm not familiar with. However, it does not appear to support ctypes structures et al, instead only showing the members of the metaclass. This issue requests IS/AC support for ctypes structures/unions/etc. in at least Visual Studio 2022+.

**Comment by StellaHuang95** [comment]
Moving this issue to discussion as an enhancement request for comments and upvotes.
