### ISSUE TITLE
The cursor doesn't auto indent after newline 

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#4444]
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/538ce8e3-c381-48e7-a988-a57c14ae37e3)

**Steps to Reproduce**
1.Create a python project
2.Type some simple code in default file, such as define a class or define a function 

**Expected behavior**
The cursor should auto indent after typing 'Enter' 
![auto_suojin_normal](https://github.com/microsoft/PTVS/assets/59192491/32fb70a7-bd05-4d1c-9d45-b6e39139610a)

**Actual behavior**
The cursor doesn't auto indent after typing 'Enter' 
![auto_suojin](https://github.com/microsoft/PTVS/assets/59192491/e08b7de0-5d39-48e7-af70-5ce9310e3ea2)

**Note: I can repro this in most time , instead of all time**

**Comment by StellaHuang95** [comment]
This should be fixed once we pull in this change: https://github.com/microsoft/pyright/commit/c8e72e70f3865cce403c49b1ef0d05b91cdad8ac

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023621-14-June-2023-PreRelease)
