### ISSUE TITLE
Sphinx's code-block are not rendered

### ISSUE THREAD

**Issue by Predeactor** [microsoft/pylance-release#4445]
Hi! I'd like to know if it's possible to integrate Sphinx's code-block feature into VSC's documentation pop-up.

Given the following piece of code:

```py
class MyClass:
    type: typing.Any
    """
    Define what type the variable is.
    It'll attempt to convert the answer by initializing a new class. For example:

    .. code-block:: py

       question = {
           "id": "number",
           "help": "What number do you like the most?",
           "type": int
       }

       answer = "1"  # The answer will always be a string, unless a type is defined and we try to
                       # convert it.

       if kind := question["type"]:
           try:
               kind(answer)
           except ValueError:
               ...
    """
``` 

Hovering `type` will show this:

![image](https://github.com/microsoft/pylance-release/assets/61093863/c4942a1b-9424-494c-8190-c677150abf50)

The documentation is cut in half and remove the most important information here!

An alternative would be to use Markdown to allow the code to be rendered, but in projects that make uses of Sphinx, it feels impossible to mix both.

My feature request would be to **add support for Sphinx's `code-block` to show code in documentation pop-up.**

**Comment by StellaHuang95** [comment]
Hi @Predeactor, thank you for your suggestion! We currently have a [discussion item](https://github.com/microsoft/pylance-release/discussions/4416) for supporting Sphinx docstrings. Please upvote the idea if you'd like to see Sphinx docstrings being supported, thanks!
