### ISSUE TITLE
'Rename' command is sometimes broken in python notebooks

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/pylance-release#4447]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

'Rename' on a symbol doesn't do anything, only shows a notification 'No result. No result.'

https://github.com/microsoft/vscode-jupyter/assets/16353531/c74ede6c-3198-46e2-bb58-4ddf0f6ecd2f

I don't have repro steps unfortunately. Feel free to close if the notification message is not helpful to track where this error may be coming from

### VS Code Version

Version: 1.79.0-insider Commit: 784e72bc4486b7ea5ad3447c506e31d949848592 Date: 2023-05-30T05:23:26.066Z Electron: 22.5.4 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Darwin arm64 22.4.0

### Jupyter Extension Version

v2023.5.1001521100

### Coding Language and Runtime Version

Python 3.11.3

### Language Extension Version (if applicable)

Python v2023.9.11491011

### Running Jupyter locally or remotely?

Local

**Comment by judej** [comment]
@ulugbekna, unfortunately, I am not able to reproduce the problem. Are you still seeing the behavior?  If so, please reopen the issue. Thanks
