### ISSUE TITLE
Pylance not showing parameter hints from parent class

### ISSUE THREAD

**Issue by samkanje** [microsoft/pylance-release#4449]
## Environment data
Pylance language server 2023.5.51 (pyright 7784093a)
OS: MacOS 13.3.1 (a) (22E772610a)
Python3.11 venv

Also tested the release version of Pylance with same results

## Code Snippet

```python
class Parent:
    def __init__(self, a1: str, a2: int, **kwargs):
        pass


class Child(Parent):
    def __init__(self, a3: str, a4: int, **kwargs):
        pass

```

## Repro Steps

With the two classes above, parameter hinting for Child class does not show the parameters defined in the parent.

1. XXX

## Expected behaviour

![CleanShot 2023-06-02 at 12 34 35](https://github.com/microsoft/pylance-release/assets/8049629/079046ff-ccf3-4fa2-8342-e15b16b7e576)

## Actual behavior

![CleanShot 2023-06-02 at 12 38 06](https://github.com/microsoft/pylance-release/assets/8049629/223484d7-49f5-41ca-a0f7-d05f256d00ec)

**Comment by erictraut** [comment]
Yes, that's correct. You've overridden the method from the base class with a method of the same name but a different signature. The signature of the override takes precedence. If you want to expose keyword parameters from a base class method, you should include them explicitly in the override.
