### ISSUE TITLE
Cannot access member "objects" for Mongoengine models

### ISSUE THREAD

**Issue by ripperdoc** [microsoft/pylance-release#445]
## Environment data

Pylance: v2020.9.7
Pylance language server 2020.9.7 (pyright a0620921)
MacOS 10.14.5
Python 3.8.5

## Expected behaviour

I'm using `mongoengine` and `flask-mongoengine` to build my model classes based on the `mongoengine.Document`.  I'm expecting to use the common `Document.objects()` query method on my model classes without error.

E.g.
```python
from mongoengine import Document

class World(Document):
    ...

World.objects(title="test")
```

## Actual behaviour

I get loads of errors from Pylance about `Cannot access member "objects" for type "Type[World]". Member "objects" is unknown`. I can understand that this happens, as Mongoengine is very dynamically typed with a lot of trickery under the hood. But I also fail to figure out how to create my own stub file to alleviate the problem. As a test I created a stub file but didn't seem to do any difference.

```python
# ./typings/lore/api/world.pyi 
# matches the same path in my source

class World:
    def objects(**kwargs):
        """"""

```

**Comment by erictraut** [comment]
The stub isn't working because you haven't declared `objects` as a static method. As such, it's not available on the class itself, only on instances of that class. If you add a `@staticmethod` decorator, it should work as expected.

**Comment by ripperdoc** [comment]
Thanks, I should have realized that! Unfortunately, the staticmethod did not change the outcome. But more fortunately, when I ran stubgen for mongoengine, and then edited that file with the objects method, it seems to work. Thanks, this issue can be closed!

**Comment by sandboxcmd** [comment]
> Thanks, I should have realized that! Unfortunately, the staticmethod did not change the outcome. But more fortunately, when I ran stubgen for mongoengine, and then edited that file with the objects method, it seems to work. Thanks, this issue can be closed!

Hi, I'm new at Python and I have same problem, can you share how make it works technically?
l'm use black and flake8 for auto-format and linter, but Document member is grey out. Been googling everywhere, but always end up here.
Thanks in advance!

**Comment by bsladewski** [comment]
This is the top result when searching this particular issue but I initially missed the resolution. If you are using a Python virtual environment, the following commands should be run using your project's virtual environment.

1. Install `mypy` if you do not already have it installed; this will add the `stubgen` command:
```
pip install mypy
```
2. In the root directory of your project run the following command:
```
stubgen -o typings -p mongoengine
```
3. Navigate to `typings/mongoengine/document.pyi` and locate the `Document` class definition.
4. Add the following function definition to the `Document` class definition:
```
@staticmethod
def objects(**kwargs): ...
```

**Comment by tpougy** [comment]
@bsladewski I tried to set up as you explained, but i couldn't find the def objects where it should be. Also, in VS Code, what other configs should I be using to enable this mypy autocompletion? In my case I was using the default option which is the pylance to handle autocompletion, should I change to MyPy? Sorry if I'm missing somthing, I'm pretty new to python.

**Comment by shahanneda** [comment]
I also have the same problem, after setting up the stub, does anyone know how to get VS Code to actually use it for the types?

**Comment by mrbio** [comment]
> I also have the same problem, after setting up the stub, does anyone know how to get VS Code to actually use it for the types?

The following minor change did the trick:

```
@staticmethod
    def objects(**kwargs)->QuerySet: ...
```

This allows VSCode to do autocompletes. I use Pyright and it works fine this way
