### ISSUE TITLE
Installation is missing after every restart of VSCode

### ISSUE THREAD

**Issue by dk00001101** [microsoft/pylance-release#4451]
Type: <b>Bug</b>

Every Boot from VSCode dismisses somehow the Pylance installation. It is showed that Language Server was set to Pylance, but pylance is not installed. After trying to install pylance, the installation wont run successfully, because pylance is installed. I have to delete pylance from the extensions folder and install it then again after a reboot of VsCode. This is so annoying, that im honestly considering to install pycharm..... 

this was not always the situations, it started all a month ago, but I dont know why! 

Thank you alot.

BR 
KUDA 

Extension version: 2023.5.50
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (16.50GB free)|
|Process Argv|--crash-reporter-id 95c9fc43-5ab6-4076-9cfb-68e3e3735854|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705
pythonnosmt12:30757131

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue.

Can you provide the logs from both the 'Python' output tab and the 'Python Language Server' output tab?

![image](https://github.com/microsoft/pylance-release/assets/19672699/3bb3763e-5fb2-4ab2-84f4-3d6aeaa8fcc5)
