### ISSUE TITLE
I cannot use autocompletion on some method of libraires.

### ISSUE THREAD

**Issue by cometess** [microsoft/pylance-release#4453]
Hello.
when using openpyxl, pyautogui, some of features like pyautogui.click/move/moveTo ... can be auto complete. 

However, method like getActiveWindows, isActive, activate can not be auto filled on VScode.

similar problem happens on openpyxl too.

So, is there any solution?

**Comment by Avasam** [comment]
PyAutoGUI stubs live here: https://github.com/python/typeshed/tree/main/stubs/PyAutoGUI
openpyxl stubs live here: https://github.com/python/typeshed/tree/main/stubs/openpyxl
