### ISSUE TITLE
Source actions not found

### ISSUE THREAD

**Issue by e-vissch** [microsoft/pylance-release#4464]
## Environment data
- Pylance v2023.5.50
- macOS 12.5 (21G72)
- Python 3.10

## Code Snippet

```python
import sys
```

## Repro Steps
1. Command + shift + P -> Source Action -> UI comment, no available source actions
2. Use lightbulb -> Quick Fix -> Remove unused import 
3. Cmd Z 
4. Command + shift + P -> Source Action -> See available source action of removing import. 

https://github.com/microsoft/pylance-release/assets/66283272/80f02c44-b0bc-4321-a8ea-66996215ee7a

## Expected behavior

Expect step 4. above at step 1.

When I roll back my pylance version to v2023.5.20 the expected behaviour occurs.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023621-14-June-2023-PreRelease)
