### ISSUE TITLE
Stubs downloader log claims that `django` is not installed, but it is

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4469]
-   Language Server version: 2023.6.11

## Repro Steps

0. Clear stubs cache. I ended up uninstalling Pylance, removing the pylance install dir, and reinstalling. But deleting the `.cache` dir might be sufficient.
1. Create new folder
2. python -m venv .venv
3. .venv\Scripts\activate
4. pip install django
5. Open folder in VS Code
6. Create test.py
7. Search log for "download"
8. Note successful download -- "Downloading django stubs..." + " Finished django stub download (2463ms)"
9. Restart VS Code
10. Reopen same folder.
11. Search log for "download"

**Expected:** Not sure. Same output about succesful download, or better yet something like "Django stubs are already present"

**Actual:** "Skipping django stubs download because package is not installed." Note in screenshot that hover works, django is installed in .venv, and .venv is selected.

![image](https://github.com/microsoft/pylance-release/assets/12820898/36f44aaa-f980-4c0f-92a8-e77d0740a619)

**Comment by rchiodo** [comment]
Oh if it's already there it finds the stub first and thinks the package isn't installed. It needs to see if there's a non stub import too.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023621-14-June-2023-PreRelease)
