### ISSUE TITLE
How to get rid of "__start/" etc. ?

### ISSUE THREAD

**Issue by GBZH** [microsoft/pylance-release#4473]
Currently I am using (VS)code under Ubuntu 22.04 LTS with the Pylance extension, when I type the following code:

     for l in range(1, L_max+1): 

         rpow = (r0 / r) ** (l + 2)

         if abs(Clm[index]) > vsmall:

             Nlm = FuncNlm(l,0) / r0

             Bsph += rpow * Nlm * np.array([
                 Clm[index] * (l+1) * assoc_legendre(l, 0, costheta),
                 -Clm[index] * FuncDlm(l, 0, costheta),

in the code editor, the text is shown with several additions like '_start/', '__stop/' and many other variables names which are listed in the function arguments as can be seen on the attached screenshot. I did not find a way to tune Pylance settings in order to get rid of all these unwanted "decorations".  In fact I do not know if these things have a name, therefore I do not find how to fix this. 
Any help is more than welcome.
Thanks in adavance

![Screenshot from 2023-06-08 15-48-40](https://github.com/microsoft/pylance-release/assets/2182411/5d90c213-24c7-487e-a1ef-0fb60368d165)

**Comment by bschnurr** [comment]
turn this setting off
![image](https://github.com/microsoft/pylance-release/assets/1946977/214d6485-f29d-4753-9e57-21d9073feaff)
