### ISSUE TITLE
pipenv editable install not detected

### ISSUE THREAD

**Issue by jcampbell** [microsoft/pylance-release#4476]
I have an editable install of a python module in a virtual environment managed by pipenv. The package was installed directly from git.

The package is not recognized by pylance unless it is explicitly added to the `python.analysis.extraPaths` list, even though it is located in the `src` (vs the `lib/.../site-packages`) directory. It is included in site-packages.

<h3> Environment data </h3>

-   Language Server version: 2023.5.50
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.9.16
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

![2023-06-08 16 07 43](https://github.com/microsoft/pylance-release/assets/332575/7b3a78b0-fd17-41d6-96b0-437b8733b6bd)

```python
import great_expectations as gx # great_expectations has been installed directly from github using pipenv
```

<h3> Repro Steps </h3>

Install an editable module using pipenv:
`pipenv install -e git+https://github.com/great-expectations/great_expectations.git@develop#egg=great-expectations`

<h3> Expected behavior </h3>

Module is correctly analyzed.

<h3> Actual behavior </h3>

Module must be included in analysis.extraPaths

<h3> Logs </h3>

Here are what I think are the relevant logs...

```
2023-06-08 16:05:46.403 [info] [Info  - 4:05:46 PM] (88455)   Looking in extraPath '/Users/james/.local/share/virtualenvs/data-validation-3VeP54W-/src/great-expectations'
2023-06-08 16:05:46.403 [info] [Info  - 4:05:46 PM] (88455)   Attempting to resolve stub package using root path '/Users/james/.local/share/virtualenvs/data-validation-3VeP54W-/src/great-expectations'
2023-06-08 16:05:46.404 [info] [Info  - 4:05:46 PM] (88455)   Attempting to resolve using root path '/Users/james/.local/share/virtualenvs/data-validation-3VeP54W-/src/great-expectations'
```

Hard to know what are the right missing logs.

**Comment by debonte** [comment]
Please see our documentation on resolving imports from editable installs: https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs

**Comment by jcampbell** [comment]
Thanks for pointing me to the docs--I was able to get it to work as expected by using a `pip` install instead of `pipenv` install; if it's an issue at all, then, it would seem to be with having pipenv allow that flag. Thank you!
