### ISSUE TITLE
Type check not working for union of frozensets

### ISSUE THREAD

**Issue by spacether** [microsoft/pylance-release#4479]
Type: <b>Bug</b>

When defining this type hint:
```
tuple_items: typing.Union[
    frozenset[
        typing.Union[
            typing.Tuple[typing_extensions.Literal['1invalid'], int],
            typing.Tuple[typing_extensions.LiteralString, float]
        ]
    ],
    frozenset[
        typing.Tuple[typing_extensions.Literal['1invalid'], int],
    ],
] = frozenset({
    ('1invalid', 1),
    ('a', 1)
})
```
The editor does not show a warning or error. It should because the 'a': 1 key value pair has an integer value, and the type hint requires a float value

Extension version: 2023.6.10
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 11, 9|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id c48e9027-7f92-4e80-b41f-684aa4a6e195|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705
dh2dc718:30763024

```

</details>

**Comment by spacether** [comment]
Never mind, it looks like this is working. The above issue is because an int value can be assigned to a float type as a float value.

**Comment by erictraut** [comment]
Yes, that's correct. In the Python type system, an `int` is a subtype of `float`. Likewise, a `float` is a subtype of `complex`.
