### ISSUE TITLE
pandas to_dict has wrong return type for most `orient` arguments

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#448]
## Environment data

-   Language Server version: 2020.9.7
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.7.5

## Expected behaviour

No error

## Actual behaviour

```python
from typing import Dict, Any
import pandas as pd


df = pd.DataFrame({"x": [1, 2, 3]})

dic: Dict[str, Any] = df.to_dict(orient="split")
```
reports
```
Expression of type "List[Dict[_str, Any]]" cannot be assigned to declared type "Dict[str, Any]"
  "List[Dict[_str, Any]]" is incompatible with "Dict[str, Any]"
```

Issue here is that the return type of `to_dict` depends on the `orient` argument.

Possible solution:
```
diff frame.pyi.ORIG frame.pyi
202c202
<         self, orient: Union[_str, Literal["dict", "list", "series", "split", "records", "index"]] = ..., into: Hashable = ...,
---
>         self, orient: Literal["records"] = ..., into: Hashable = ...,
203a204,207
>     @overload
>     def to_dict(
>         self, orient: Union[_str, Literal["dict", "list", "series", "split", "index"]] = ..., into: Hashable = ...,
>     ) -> Dict[_str, Any]: ...
```

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020100-7-october-2020
