### ISSUE TITLE
Pylance having issue with suggestions in certain condition

### ISSUE THREAD

**Issue by tenacioustommy** [microsoft/pylance-release#4486]
## Environment data
Language Server version v2023.6.10
OS and version: windows10 
Python version: Python 3.9.13 via Anaconda.

## Expected behavior
it is expected to have suggestion after '.' ,but it has nothing and the highlight doesn't show either
as the picture suggests
![{1E3567B8-5C07-4455-8471-A32C643D542B}](https://github.com/microsoft/pylance-release/assets/99079604/0ee77ff3-1ff8-4840-9976-296608d3eea8)
![{63E86738-D370-4D6B-9E1F-2F6E178A0E2B}](https://github.com/microsoft/pylance-release/assets/99079604/27487713-b4d2-4589-aebb-32554a653b58)
## Actual behavior
in pycharm it works well, it should have highlight and suggestion

**Comment by debonte** [comment]
Sample above as text:

```python
from selenium.webdriver import Chrome
import time
web=Chrome()
web.get("https://google.com")

img=web.find_element_by_xpath('/html/body/div[3]/div/div[3]/div[1]/form/div/img')
```

**Comment by debonte** [comment]
@tenacioustommy, what version of `selenium` are you using? Do you also have `selenium` stubs installed? If so, which ones (`types-selenium`?) and which version?

**Comment by erictraut** [comment]
This is due to a bug in an old version of the selenium library. If you upgrade to the latest version, it should work fine.

**Comment by tenacioustommy** [comment]
thanks,after i update my selenium version, it works normally
