### ISSUE TITLE
Convert string to f-string when adding brackets around a text selection

### ISSUE THREAD

**Issue by rik** [microsoft/pylance-release#4489]
The `python.analysis.autoFormatStrings` feature is very nice!

One missing use-case for me is when I have a text selection in a string and type `{` to add brackets around that selection. See video below.

https://github.com/microsoft/pylance-release/assets/3653/43e30ea7-4644-459d-9fe9-8ea17bdf0637

**Comment by rchiodo** [comment]
Thanks for the issue.

Not sure why the format on type is not triggering in this case but it should be fixable.

**Comment by Zaffer** [comment]
same issue on my side, in fact, changing this setting in settings.json of vscode caused vscode to crash too. strange.

**Comment by StellaHuang95** [comment]
Filed a ticket with vscode: https://github.com/microsoft/vscode/issues/185611

**Comment by rik** [comment]
May I ask why was this ticket closed? The VSCode ticket is still open and the issue is still present in VSCode 1.94.0.

**Comment by heejaechang** [comment]
because it is a bug in vscode, not pylance. once they fix it, it should work without pylance doing anything.
