### ISSUE TITLE
Debug Failure. False expression: Check called unnecessarily

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4492]
Error: Debug Failure. False expression: Check called unnecessarily</br>at this <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/sourceFile.ts#L773'>pyright-internal/src/analyzer/sourceFile.ts:773:15</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/common/logTracker.ts#L57'>pyright-internal/src/common/logTracker.ts:57:19</a></br>at log <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1875'>pyright-internal/src/analyzer/program.ts:1875:32</a></br>    at _checkTypes <a href='https://github.com/microsoft/pyrx/blob/912066d7de2b584a2695894a755e9124df4d8296/packages/pyright/packages/pyright-internal/src/analyzer/program.ts#L1915'>pyright-internal/src/analyzer/program.ts:1915:33</a></br>

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.6.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023641-28-June-2023-PreRelease)
