### ISSUE TITLE
pylance cannot locate the definition of class instance method when nested in a function. 

### ISSUE THREAD

**Issue by flyforward2016** [microsoft/pylance-release#4493]
## Environment data

-   Language Server version: 2022.5.1 with vscode 1.63.2 ( Also tested 2023.6.10 with vscode-insider 1.80.0) 
-   OS and version: Mac Monterey 12.6.3  
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.8

## Code Snippet

```python

class ConfigName:
    def __init__(self,  resume=None ):
        self.resume = resume

    def get_logger(self, name ):
        print(f"the name is {name}")
        return logger

def process(config):  
    logger = config.get_logger('yes') # get_logger is not highlighted and "go to definition" does not work.
    

if __name__ == '__main__':
    resume = "yes"
    config = ConfigName(resume)
    logger = config.get_logger('yes') # get_logger is highlighted and "go to definition" works.
    process(config)
```

- The instance method "get_logger()" has correct syntax highlight and right click "go to definition" can point to the get_logger function in class ConfigName.

- However, when I call the instance method in the "process" function, "get_logger()" does not have any syntax highlighting and "go to definition" does not work - no definition found for "get_logger".  

- Is this expected behavior? If I were to call the instance method in process function, what should I do to make the syntax highlighting work and the "go to definition" option work.

Please see attachment for more details. 

Thank you in advance. 

 
<img width="465" alt="image" src="https://github.com/microsoft/pylance-release/assets/19171234/e1bdd5fb-4a28-4bf2-9e11-4b9605090a7e">

**Comment by debonte** [comment]
If you annotate the `config` parameter of `process` this will work the way you want it to:

```python
def process(config: ConfigName): 
```

**Comment by debonte** [comment]
FYI, this [comment](https://github.com/microsoft/pyright/issues/4057#issuecomment-1280412028) explains why we don't infer the type of the `config` parameter based on calls to `process`.
