### ISSUE TITLE
Use pyright-specific comment for `Quick Fix... > Add '# type: ignore' to suppress warning`

### ISSUE THREAD

**Issue by Avasam** [microsoft/pylance-release#4494]
It is not uncommon to run multiple type-checkers on the same code-base (ie mypy+pyright), especially in libraries and in typeshed.
To separate the different type errors, especially when the checkers disagree, it is possible to configure pyright to ignore `# type: ignore` comments.

I think it would be more productive and better serve the users of pylance, if the "Quick fix" for suppression instead used `# pyright: ignore[reportedError]`, or at least offered it as an option.

This:
![image](https://github.com/microsoft/pylance-release/assets/1350584/adea29a5-b582-4f7e-be34-c70f4ba5527e)

Simply results in:
![image](https://github.com/microsoft/pylance-release/assets/1350584/579685ea-ee14-4816-9401-24de1239e663)

**Comment by erictraut** [comment]
You can tell pyright to ignore `# type: ignore` (but still honor `# pyright: ignore`) by setting `enableTypeIgnoreComments` to false in your config file.

**Comment by Avasam** [comment]
> You can tell pyright to ignore `# type: ignore` (but still honor `# pyright: ignore`) by setting `enableTypeIgnoreComments` to false in your config file.

That's what I'm doing. And the reason I'd like Pylance to offer a different quick fix to suppress warning.

**Comment by heejaechang** [comment]
in next pre-release, if the option `enableTypeIgnoreComments` is `false`, we will show `# pyright: ignore` instead.

**Comment by erictraut** [comment]
@heejaechang, will you also include the specific diagnostic rule(s) for the line (e.g. `# pyright: ignore[reportGeneralTypeIssue]`)?

**Comment by heejaechang** [comment]
okay

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.41, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231041-19-October-2023-PreRelease)

**Comment by Avasam** [comment]
@heejaechang I just tried it on the latest pre-release, and it works, but not all the time:
![image](https://github.com/microsoft/pylance-release/assets/1350584/0563043c-f876-42b2-984b-8f10cc128ba6)
![image](https://github.com/microsoft/pylance-release/assets/1350584/21fe7d98-5c19-4f7d-bfe8-0000a14dc225)
