### ISSUE TITLE
Incorrect Type Hinting for redis.Redis Class with 'strict' Type Checking

### ISSUE THREAD

**Issue by blaze-Youssef** [microsoft/pylance-release#4500]
Type: <b>Bug</b>

When using the Pylance extension in VS Code for Python type hinting with 'strict' type checking, it is incorrectly expecting type arguments for the `redis.Redis` class from the `redis-py` package.

**Reproduce:**

1. Install the `redis-py` package via pip: `pip install redis`.
2. Write a Python function that accepts an argument with a `redis.Redis` type hint.
    ```python
    import redis

    def example_function(r: redis.Redis):
        pass
    ```
3. Open this Python file in VS Code with the Pylance extension enabled and 'strict' type checking enabled.
4. Observe the error message "`redis.Redis` is not a generic class".

**Expected behavior:**

Pylance should recognize `redis.Redis` as a valid type hint without requiring type arguments, as the `redis.Redis` class in the `redis-py` package is not a generic class, even when 'strict' type checking is enabled.

**Actual behavior:**

Pylance is incorrectly expecting type arguments for the `redis.Redis` class when 'strict' type checking is enabled, with the error message "Expected type arguments for generic class 'Redis'".

**What I have tried:**
When I hover my mouse on top of a variable set with this class, like:
`self.redis = redis.Redis(host=redis_host, port=redis_port)`
I get `(variable) redis: Redis[bytes]`. So, I tried setting the type hint to `redis: redis.Redis[bytes],` the error is gone and everything is fine, but when I run the code I get this error `<class 'redis.client.Redis'> is not a generic class`.

Extension version: 2023.6.11
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (3.26GB free)|
|Process Argv|C:\\Users\\youss\\Projects\\python\\openai-ratelimiter --crash-reporter-id dce33efd-89da-4252-9cac-2cada8866b0c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
57b77579:30736110
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by bschnurr** [comment]
Maybe the typeshed repo can help? something similar https://github.com/python/typeshed/issues/8242

**Comment by erictraut** [comment]
The `Redis` class is modeled as a [generic class in the typeshed stubs](https://github.com/python/typeshed/blob/5beddbe88363c93f2912320c18e31e55b2caaa49/stubs/redis/redis/client.pyi#L79), so pyright (the type checker upon which pylance is built) is doing the right thing by notifying you that you are not supplying type arguments to a generic class. There are cases where the runtime class doesn't derive from `Generic` but the typeshed maintainers choose to model the class as generic for a variety of reasons. I suspect that's what's happening here. If you have questions about this, you could file an issue in the [typeshed project](https://github.com/python/typeshed).
