### ISSUE TITLE
Pylance causes extensive CPU usage

### ISSUE THREAD

**Issue by TimHenry1995** [microsoft/pylance-release#4504]
Type: <b>Bug</b>

I was developing unit tests when I noticed my computer overheating with CPU spikes of above 200%. Thanks to the bisection tool for eliminating problematic extensions I was able to identify pylance as the reason. I had to disable it.

Extension version: 2023.6.20
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:29:00.206Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 56b4800f-250e-405f-9760-ba0570f96f1b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
ecj1e332:30736112
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
hideindicator:30766889
pythongtdpath:30739704
dh2dc718:30763024
pythonnosmt12:30765603

```

</details>

**Comment by StellaHuang95** [comment]
Thanks you for reporting the issue. To better understand the problem, it would be helpful if you could provide some additional information, like a public repository (or code sample) that causes the issue. Also, how long the process causes the CPU to spike?

Additionally, could you provide the information outlined here:

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by dbrakenhoff** [comment]
I seem to experiencing the same issue (again?, previous issue was #3762). In the previous issue, updating the Pylance extension had fixed the issue, but now on a clean install of Ubuntu 22.04 and VS Code + Pylance extension I'm running into high CPU usage again.  

When I open a workspace in VS Code and open a specific (long) Python file, the Pylance process starts using CPU, initially peaking and subsequently leveling off around 8-15%, it never drops below this though. I'm not seeing continuous logging as it hovers around 8% CPU, so I have no idea what its doing... It also occasionally seems to hang on "analyzing" a file, never seeming to complete the task. 

I cannot reproduce the behavior on all Python files. The one I'm experiencing issues with right now is unfortunately not public, but I'll check if I can find a public example to reproduce the issue. I've included the Python Language Server log for the file I'm experiencing trouble with. It is quite a large file (4000 lines) and contains quite a few imports.

Last time I got some advice to create type stubs for my custom packages, which I understand could improve performance. However, I do not expect Pylance to continuously cause a high cpu load despite some type stubs not being available.

Anyway, hope you guys can help me (and the original poster) to solve this issue.

<h3> Environment data </h3>

-   Language Server version: 2023.7.10
-   OS and version: Ubuntu 22.04 linux x64 (completely clean install)
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.9.7 (environment installed with mamba)
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<details>
<summary>environment.yml</summary>
<code>
name: benschop
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - ipython
  - geopandas
  - shapely
  - pyshp
  - descartes
  - rasterio
  - rasterstats
  - rioxarray
  - xarray
  - matplotlib
  - numpy
  - pandas
  - openpyxl
  - xlrd
  - scipy
  - numba
  - tqdm
  - owslib
  - cytoolz
  - netCDF4
  - scikit-image
  - requests
  - zeep
  - flopy
  - imod
  - pastas
  - bottleneck
  - pip: 
    - nlmod
    - hydropandas
    - pastastore
    - ttim
    - timml
</code>
</details>

<h3> Repro Steps </h3>

**Note**: _I will update this once I find a public file that shows same issue._

1. Open VSCode workspace,
2. Open a (large) *.py file.
3. Watch System Monitor as CPU usage peaks then levels off somewhere between 8-15%. 

<h3> Logs </h3>

[PythonLanguageServer.zip](https://github.com/microsoft/pylance-release/files/12017231/PythonLanguageServer.zip)

**Comment by w-bonelli** [comment]
just to corroborate @dbrakenhoff's experience, I often see the same issue on macOS 13.3.1 with pylance 2023.8.10 &mdash; the process sometimes persists even after quitting VSCode and needs to be killed manually. Output from `ps aux`:

```
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/<me>/.vscode/extensions/ms-python.vscode-pylance-2023.8.10/dist/server.bundle.js --cancellationReceive=file:7169f192ca32afac49bbf5829b0cd34d3df7933cc9 --node-ipc --clientProcessId=59278
```

This does not seem repository-specific, it occurs reliably when editing any non-trivial Python project.

**Comment by bschnurr** [comment]
@w-bonelli can you create a new issue and with the logs and file you are opening. see
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
