### ISSUE TITLE
Pylance doesn't work after updating to Python 3.11 in virtual environment with include-system-site-packages=true

### ISSUE THREAD

**Issue by Ancieg** [microsoft/pylance-release#4508]
## Environment data

-   Language Server version: v2023.6.20
-   OS and version: ALT Linux Sisyphus (updated 18.06.2023)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.4 (from repository)

## Code Snippet

```python
def foo(a: int, b: float) -> tuple[int, float]:
    return a*b, b**2
```

## Repro Steps

Type the code snippet above.

## Expected behavior

Language server works.

## Actual behavior

It doesn't even know about built-in types such `int`, `bool`, `float`, etc.

![image](https://github.com/microsoft/pylance-release/assets/29044775/118a8f7e-53f0-41a9-9d12-dc1d5610ba45)

## Logs

Unfortunately, output panel is empty after setting `"python.analysis.logLevel": "Trace"`.
But there is a message in PROBLEMS tab after editor restart:
```
Unable to load schema from 'vscode://schemas/settings/user': cannot open vscode://schemas/settings/user. Detail: Unable to resolve text model content for resource vscode://schemas/settings/user.
```

I can't find any similar issue. Please help!

**Comment by Ancieg** [comment]
Important note: if I keep `include-system-site-packages = false` in `venv/pyvenv.cfg`, Pylance works well.
But when I set `include-system-site-packages = true`, Pylance doesn't work.

**Comment by heejaechang** [comment]
@Ancieg I tried to repro but it doesn't so. we would need the log to see what is happening on your machine.

**Comment by Ancieg** [comment]
I'm sorry. I found log.
[vscode.log](https://github.com/microsoft/pylance-release/files/11805727/vscode.log)

**Comment by heejaechang** [comment]
```
2023-06-20 22:09:27.379 [info] [Info  - 10:09:27 PM] (13783) Search paths for /home/ancieg/tlrefresh
2023-06-20 22:09:27.379 [info] [Info  - 10:09:27 PM] (13783)   /usr/lib/python3/site-packages/typeshed/stdlib

2023-06-20 22:09:27.569 [info] [Info  - 10:09:27 PM] (13783) Could not import 'builtins' in file '/home/ancieg/tlrefresh/tlrefresh/base.py'
```

did you install our own `typeshed` in global `site-packages`? it looks like the `typeshed/stdlib` installed in global override `stdlib` we bundled but it doesn't have `builtins` so we can't resolve any of `builtin` types.

**Comment by Ancieg** [comment]
`typeshed` had been removed from the repository almost year ago: https://packages.altlinux.org/en/sisyphus/srpms/python3-module-typeshed/.

I'll try to return it to the repository.

**Comment by heejaechang** [comment]
@Ancieg I am not sure what you meant by
> I'll try to return it to the repository.

but anyway, unless needed, try `uninstalling` `/typeshed/stdlib` from `global site-packages`

I think that will fix the issue.

**Comment by Ancieg** [comment]
> but anyway, unless needed, try `uninstalling` `/typeshed/stdlib` from `global site-packages`
> 
> I think that will fix the issue.

I uninstalled `typeshed` from global site-packages and the problem disappeared.
Thank you!
