### ISSUE TITLE
py.typed library showing _hidden modules

### ISSUE THREAD

**Issue by laundmo** [microsoft/pylance-release#4510]
<h3> Environment data </h3>

-   Language Server version: 2023.6.21
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: tried both basic and strict

<h3> Code Snippet </h3>

```python
from mytypedlib.
```

<h3> Repro Steps </h3>

1. create a typed library called `mytypedlib`
2. make sure it includes a public module, and a private one denoted by the filename starting with `_`
3. ensure it contains and is packaged with a `py.typed`file
4. install it with `pip install .`
5. verify it still includes the `py.typed` file after install (checking in site-packages)
6. create a new python file
7. start importing from `mytypedlib` by starting to type `from mytypedlib.`
8. trigger completions

<h3> Expected behavior </h3>

The completions should not include modules prefixed with `_` should not show up, as per: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface they should be considered private.

<h3> Actual behavior </h3>

The autocompletion shows modules prefixed with `_`

<h3> Logs </h3>

i have not included trace logs as it would leak private information. I can provide them with some effort if others can't reproduce this.

**Comment by rchiodo** [comment]
If the `_privatetest.py` was included, it would have shown this:

![image](https://github.com/microsoft/pylance-release/assets/19672699/b66f5e58-841a-4f3f-a52e-c90776f8eaea)

That's controlled by what's exported from the `__init__.py` though. So maybe your `__init__.py` is reexporting the private modules.

**Comment by laundmo** [comment]
you're looking at the wrong autocomplete: the issue is specific to the 

`from mylib.|` autocomplete, where your cursor is directly after the dot, where i have written a pipe character.

**Comment by rchiodo** [comment]
Ah you mean this:

![image](https://github.com/microsoft/pylance-release/assets/19672699/0cefe46a-8a92-49c1-8451-059b38a0b9f6)

Seems like a bug. I'm guessing import module completions don't exclude privates on purpose though as they are valid to be imported.

Moving to triage to discuss.

**Comment by erictraut** [comment]
This might be related to [this bug](https://github.com/microsoft/pylance-release/issues/4059).

**Comment by debonte** [comment]
Moving this issue to discussion as an enhancement request for comments and upvotes.

Maybe we should add a setting to control this behavior -- should `_` prefixed symbols be shown in the completion list.
