### ISSUE TITLE
Pylance can't discriminate some functions or modules to highlight it .Especially some have connections with cpp.

### ISSUE THREAD

**Issue by ZhuYizhou2333** [microsoft/pylance-release#4511]
![image](https://github.com/microsoft/pylance-release/assets/131937763/d0dabc05-bc56-4d87-8b92-0c22a68cb608)

As you can see in the picture. When I use jedi as my language server, it can discriminate this function. But it can't highlight it.

So I load Pylance But It shows as the folowing picture.

![image](https://github.com/microsoft/pylance-release/assets/131937763/42d82aa7-48ef-4dbe-afae-51a55e2b584b)

Is this a real bug or just I didn't set the Pylance correctly?

I searched the internet and i found maybe same issue will happen when import Pytorch due to the rely on cpp.But i'm not sure.

**Comment by ZhuYizhou2333** [comment]
![image](https://github.com/microsoft/pylance-release/assets/131937763/a38dd0cc-c51d-40a1-9d31-d2157b24ecf2)

Maybe it is another example. The cell can run smoothly but Pylance says it is a mistake.

**Comment by ZhuYizhou2333** [comment]
In order to reproduce the problem, just code as following.

![image](https://github.com/microsoft/pylance-release/assets/131937763/2b27461b-a67f-4e1e-9991-2c48f864df82)

**Comment by bschnurr** [comment]
Thank you for the detailed issue. We will look into it

**Comment by debonte** [comment]
`matplotlib` started shipping their own stubs in 3.8.0. If you haven't upgraded already, I'd suggest doing that. With 3.8.3 and the following code:
```python
import matplotlib.pyplot as plt
import numpy as np
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
z = np.sqrt(xs ** 2 + ys ** 2)
plt.imshow(z, cmap=plt.cm.gray, extent=(-5, 5, -5, 5))
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
```

I see:
![image](https://github.com/microsoft/pylance-release/assets/12820898/bb5464df-a64b-4f8e-aabc-37f4812969d1)

The diagnostic on `gray` is `"gray" is not a known member of module "matplotlib.cm"`. The colors are installed in some dynamic way that static type checkers like Pylance don't understand.

If you'd like to see improvements to the `matplotlib` stubs to fix this or other issues, please file issues at https://github.com/matplotlib/matplotlib/issues.
