### ISSUE TITLE
Pylance mistakenly claims that `Type "int" cannot be assigned to type "int | float"`

### ISSUE THREAD

**Issue by janekb04** [microsoft/pylance-release#4516]
## Environment data

-   Pylance extension version: `v2023.6.20`
-   Language Server version: `2023.6.20 (pyright 73165c50)`
-   OS and version: `Windows 11, Version 22H2 (OS Build 22621.1702)`
-   Python version (& distribution if applicable, e.g. Anaconda): `3.10.6`

## Code Snippet

```python
i = [0]
f = [0.0]
fi: list[int | float]
fi = i
```

## Expected behavior

There are no typing errors - an `int` is an `int | float`.

## Actual behavior

```
Expression of type "list[int]" cannot be assigned to declared type "list[int | float]"
  "list[int]" is incompatible with "list[int | float]"
    TypeVar "_T@list" is invariant
      Type "int" cannot be assigned to type "int | float"
        "int" is incompatible with "float" Pylance(reportGeneralTypeIssues)
```
**`Type "int" cannot be assigned to type "int | float"`**

## Logs

I don't think they are necessary.

**Comment by erictraut** [comment]
This error is correct. The type `list[int | float] is not type compatible with `list[int]. This may seem counterintuitive, but it makes sense once you understand the underlying reason. For details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts?id=generic-types).

**Comment by janekb04** [comment]
Ok, I get it - reference semantics. We cannot assign a type to a "broader" type because we can modify the original through the new reference. Thanks.
