### ISSUE TITLE
Go to definition.  No Definition found for torch.utils.data.get_worker_info()

### ISSUE THREAD

**Issue by trotsky1997** [microsoft/pylance-release#4520]
<h3> Environment data </h3>

-   Language Server version: 2023.6.20
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
worker_info = torch.utils.data.get_worker_info()
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
Go to definition.  No Definition found for torch.utils.data.get_worker_info()

```
![image](https://github.com/microsoft/pylance-release/assets/30512160/e1f76e40-9174-4de8-be68-319e77d5ec85)

**Comment by heejaechang** [comment]
it doesn't repro for me. 

Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
