### ISSUE TITLE
`__` prefixed first argument of function gets `/` instead of `=` in inlay hint

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4525]
## Environment data
-   Language Server version: 2023.6.21

## Code Snippet

```python
def foo(__x: int, _y: int): ...
foo(1, 2)

def bar(_x: int, __y: int): ...
bar(1, 2)
```

## Repro Steps

1. Set `"python.analysis.inlayHints.callArgumentNames": true`
2. Paste code snippet above.

I had noticed this before, but was reminded by this issue: https://github.com/microsoft/pylance-release/issues/4524

## Expected behavior

Inlay hint for `__x` is `__x=`.

## Actual behavior

Inlay hint for `__x` is `__x/`. Note in the screenshot below that if the `__` prefixed param is not the first param, this behavior doesn't occur.

![image](https://github.com/microsoft/pylance-release/assets/12820898/2466bf36-25b8-4aad-b535-ada08c5c88fa)

**Comment by NoahELE** [comment]
Pylance seems to treat double underscore prefixed parameter as positional-only arguments. Try these code:

```python
def foo(__a: int, __b: int) -> int:
    return 0

print(foo(__a=1, __b=2))
```

This causes the error `Expected 2 more positional arguments` in pylance.
