### ISSUE TITLE
Don't show private modules for import completions on a py.typed package

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4528]
### Discussed in https://github.com/microsoft/pylance-release/discussions/4518

<div type='discussions-op-text'>

<sup>Originally posted by **laundmo** June 19, 2023</sup>
<h3> Environment data </h3>

-   Language Server version: 2023.6.21
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: tried both basic and strict

<h3> Code Snippet </h3>

```python
from mytypedlib.
```

<h3> Repro Steps </h3>

1. create a typed library called `mytypedlib`
2. make sure it includes a public module, and a private one denoted by the filename starting with `_`
3. ensure it contains and is packaged with a `py.typed`file
4. install it with `pip install .`
5. verify it still includes the `py.typed` file after install (checking in site-packages)
6. create a new python file
7. start importing from `mytypedlib` by starting to type `from mytypedlib.`
8. trigger completions

<h3> Expected behavior </h3>

The completions should not include modules prefixed with `_` should not show up, as per: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface they should be considered private.

<h3> Actual behavior </h3>

The autocompletion shows modules prefixed with `_`

<h3> Logs </h3>

i have not included trace logs as it would leak private information. I can provide them with some effort if others can't reproduce this.</div>

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.8.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023811-2-August-2023-PreRelease)
