### ISSUE TITLE
Allow to specify pyright version

### ISSUE THREAD

**Issue by vors** [microsoft/pylance-release#4532]
We have a large monorepo that has all sort of edge cases in it.
We currently run pyright version `1.1.291` in our CI. This is a little bit old, however the update is non-trivial to execute and we don't plan to do it for a few months.
Our developers use VSCode with Pylance and currently the pyright version mistmatch creates confusing discrepancy where one set of errors is reported in VSCode and another one in CI.

The proposal is to allow specify an explicit Pyright version in VSCode settings so we can get consistent experience between the environments that we care about.

**Comment by rchiodo** [comment]
Sorry but you're asking for isn't currently possible. See this duplicate issue:
#4435

This discussion item is a good spot to comment on your use case:
https://github.com/microsoft/pylance-release/discussions/4440

**Comment by debonte** [comment]
@vors, please also upvote https://github.com/microsoft/pylance-release/discussions/4440.
