### ISSUE TITLE
Autocomplete with function parameters not working

### ISSUE THREAD

**Issue by mathew35** [microsoft/pylance-release#4533]
Type: <b>Bug</b>

# Behaviour
### Expected
when using autocomplete on function, i expect the parameters to be prefilled as it was (v2023.8.0)
### Actual
fills just function name and nothing after that (v2023.10.1 maybe 10.0 as well, not tested)
## Steps to reproduce:

1. Version speaks for itself

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.17
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Jedi"

linting
• flake8Path: "<placeholder>"
• banditPath: "<placeholder>"
• mypyPath: "<placeholder>"
• pycodestylePath: "<placeholder>"
• prospectorPath: "<placeholder>"
• pydocstylePath: "<placeholder>"
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

formatting
• autopep8Path: "<placeholder>"
• provider: "none"
• blackPath: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• pytestPath: "<placeholder>"

```

</p>
</details>

Extension version: 2023.8.0
VS Code version: Code 1.79.0 (b380da4ef1ee00e224a15c1d4d9793e27c2b6302, 2023-06-07T14:28:44.251Z)
OS version: Linux x64 6.3.6-200.fc38.x86_64
Modes:
Remote OS version: Linux x64 4.18.0-477.10.1.el8_8.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 1199)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.09GB (21.39GB free)|
|Process Argv|--unity-launch --crash-reporter-id 67ce4ff3-9129-4985-aed2-82c3b991a9f4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: virt-510|
|OS|Linux x64 4.18.0-477.10.1.el8_8.x86_64|
|CPUs|AMD EPYC 7551 32-Core Processor (2 x 1996)|
|Memory (System)|3.87GB (3.04GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30773604
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
dh2dc718:30770000
pythonidxpt:30772539
pythondjangotscf:30772537
h7j2d465:30772216

```

</details>

**Comment by rchiodo** [comment]
If you're using 'jedi', that would explain why it suddenly stopped working. You should switch the language server back to 'Pylance' or 'Default'.
