### ISSUE TITLE
Pylance does not warn about missing transformers import

### ISSUE THREAD

**Issue by mkranzlein** [microsoft/pylance-release#4536]
## Environment data
-   Language Server version: pylance-2023.6.30
-   OS and version: Windows 11
-   Python version: 3.11.3 via Miniconda

## Code Snippet
```python
import transformers
import numpy
```

## Repro Steps
1. Create an empty conda environment.
2. Create a file and import `transformers` and `numpy`.
## Expected behavior
Pylance should warn about both imports being missing, since they have not been installed in the environment.

## Actual behavior
Pylance only warns about `numpy` being missing.

![image](https://github.com/microsoft/pylance-release/assets/8162250/93c3aa5b-b032-48ac-84f1-73606133d715)

I'm pretty sure Pylance ships with stubs for both of these libraries, so I'm not sure why Pylance correctly reports that `numpy` is not installed but says nothing about `transformers`.

**Comment by bschnurr** [comment]
thank you for the bug report.. I can repo it.

**Comment by mmlynarik** [comment]
I add that Pylance also does not highlight transformers imports (classes and and library name itself) the same way as other libraries. 
![image](https://github.com/microsoft/pylance-release/assets/44208384/8349331d-4299-40ac-b705-1e3e63e5fa65)

**Comment by bschnurr** [comment]
can no longer reproduce since pylance v2023.8.20
