### ISSUE TITLE
No code completion while in remote connection

### ISSUE THREAD

**Issue by james-berkheimer** [microsoft/pylance-release#4538]
## Environment data

-   Language Server version: 2023.6.30
-   OS and version: Windows 10 (19044.3086) & Linux Centos 7
-   Python version: 3.9.12

## Repro Steps

1. Log into either an SSH or Remote Tunnel session.
2. Open a python file and import any module.
3. Attempt to use code completion with ctrl+space" or '.'

## Expected behavior

Code completion options should appear

## Actual behavior

I get a "loading/no suggestions" notification, then a problem message:

```
[{
	"resource": "/home/ad.blur.com/berkheimer/Code/hab/hab/cli.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"severity": 8,
	"message": "Expected member name after \".\"",
	"source": "Pylance",
	"startLineNumber": 16,
	"startColumn": 3,
	"endLineNumber": 16,
	"endColumn": 4
}]
```

If I am working locally, I have no issues with code completion with the latest version.  Also, If I install any previous version, the extension works as intended while remotely connected.

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by james-berkheimer** [comment]
> 

Here ya go.  There's not much there.

```
2023-06-23 18:07:30.568 [info] [Info  - 6:07:30 PM] (30026) Pylance language server 4.17.21 (pyright ae795f5b) starting
2023-06-23 18:07:30.569 [info] [Info  - 6:07:30 PM] (30026) Server root directory: /home/ad.blur.com/berkheimer/.vscode-server/extensions/ms-python.vscode-pylance-2023.6.30/dist
2023-06-23 18:07:30.569 [info] [Info  - 6:07:30 PM] (30026) Starting service instance "hab"
2023-06-23 18:07:30.645 [info] [Info  - 6:07:30 PM] (30026) Loading pyproject.toml file at /home/ad.blur.com/berkheimer/Code/hab/pyproject.toml
2023-06-23 18:07:30.658 [info] [Info  - 6:07:30 PM] (30026) Pyproject file "/home/ad.blur.com/berkheimer/Code/hab/pyproject.toml" has no "[tool.pyright]" section.
2023-06-23 18:07:30.869 [info] [Info  - 6:07:30 PM] (30026) Found 33 source files
2023-06-23 18:09:38.933 [info] [Info  - 6:09:38 PM] (30026) [FG] Long operation: checking: /home/ad.blur.com/berkheimer/Code/hab/hab/cli.py (3253ms)
2023-06-23 18:09:38.934 [info] [Info  - 6:09:38 PM] (30026) [FG] Long operation: analyzing: /home/ad.blur.com/berkheimer/Code/hab/hab/cli.py (3255ms)
```

**Comment by james-berkheimer** [comment]
> can you make sure your log is set to "Trace" as the instructions?

Yes, I followed the exact steps.  I just reran them just to be sure and I got the same output.

**Comment by heejaechang** [comment]
the log you shared seems something one would get when "python.analysis.logLevel" is set to `Information` not `Trace` though. it doesn't have any detail. just summary.

**Comment by james-berkheimer** [comment]
Here's a screen grab of my session.

![image](https://github.com/microsoft/pylance-release/assets/5049386/c6b184de-9116-4c0f-8a61-da2c98debc93)

**Comment by heejaechang** [comment]
do you have `python.analysis.logLevel: "Trace"` in your `settings.json` ?

**Comment by james-berkheimer** [comment]
Yes.

**Comment by james-berkheimer** [comment]
This is the log I get when I have the previous version (2023.6.20) installed.  It's much more info.


[vsCode_log.txt](https://github.com/microsoft/pylance-release/files/11872418/vsCode_log.txt)

**Comment by heejaechang** [comment]
so, I tested with `WSL + remote SSH` and it doesn't repro. by the way, one part that seems strange is this part

...

2023-06-23 18:07:30.568 [info] [Info  - 6:07:30 PM] (30026) Pylance language server **4.17.21** (pyright ae795f5b) starting
2023-06-23 18:07:30.569 [info] [Info  - 6:07:30 PM] (30026) Server root directory: /home/ad.blur.com/berkheimer/.vscode-server/extensions/ms-python.vscode-pylance-**2023.6.30**/dist
...

that 2 should match like this

...
2023-06-26 15:37:02.597 [info] [Info  - 3:37:02 PM] (15348) Pylance language server **2023.6.30** (pyright ae795f5b) starting
2023-06-26 15:37:02.598 [info] [Info  - 3:37:02 PM] (15348) Server root directory: c:\Users\hechang\.vscode-insiders\extensions\ms-python.vscode-pylance-**2023.6.30**\dist
...

not sure why it says `4.17.21` for your case.

that version is supposed to be baked in when we create release bits, so not sure how you got `4.17.21` yet has correct `commit id`

where did you get the pylance vsix?

**Comment by james-berkheimer** [comment]
I got it from the Extensions library within VS Code.  I will note that I am using different profiles other than the default.  I have one for work and one for home.  Not sure if that will be relevant information though.

**Comment by heejaechang** [comment]
your log does say it is from `remote ssh` right?

**Comment by heejaechang** [comment]
does this happen with non SSH workspace case as well? or happen with different SSH remote machine? also, where did you put `"python.analysis.logLevel": "Trace"`? did you add it to `workspace setting.json` or `remote-ssh setting.json`? make sure you don't put it in the `user/machine setting.json`

so far, it doesn't repro on my machine and there is no actionable data, so I am trying to find anything we can use to start digging in.

**Comment by james-berkheimer** [comment]
Locally I have no issues with the current version of Pylance.  I'm only having issues while either using an SSH remote session or a Tunnel remote session.

As for where I put the json setting.  I opened the "Current Profile Settings" json.

![image](https://github.com/microsoft/pylance-release/assets/5049386/09fcf0d9-e801-438c-a236-e3905f82bde0)

Let me know if there is another settings.json I should be setting.

**Comment by heejaechang** [comment]
ya, I think you are putting it in the wrong `settings.json`. use one that says `workspace or remote`

![image](https://github.com/microsoft/pylance-release/assets/1333179/2ba8147c-ab8d-4660-bf88-bd686b3fab1c)

**Comment by james-berkheimer** [comment]
OK so I started a Tunnel on my remote Windows machine.  Then I connected to it from my local Windows machine, updated the Pylance extension, then added that line to the Remote Settings JSON.  I got the same result.

![fl0sfU8o5O](https://github.com/microsoft/pylance-release/assets/5049386/45f933a1-85f7-4771-8353-7ed71aeae8fc)

This is how it looks when I have the previous version of Pylance installed:

![Code_wkEGDVVxM8](https://github.com/microsoft/pylance-release/assets/5049386/6a336725-fe0d-451e-98c5-b0c86c7d88e0)

**Comment by heejaechang** [comment]
can I see `log` from your `local` windows vscode? I want to see whether you still get `4.17.21` version when you run locally.

**Comment by james-berkheimer** [comment]
Here you go.  This was run locally with my "home" profile selected.  I attached a log file at the bottom.

![7KdfbPFgoi](https://github.com/microsoft/pylance-release/assets/5049386/3eced38d-d34d-4869-936d-6158ff6259c1)

[vsCode_log_2.txt](https://github.com/microsoft/pylance-release/files/11887309/vsCode_log_2.txt)

**Comment by heejaechang** [comment]
sorry, the log doesn't have this line `Pylance language server xxxx (pyright ae795f5b) starting` only full log (from vscode launch) will have that line.

that said, can you go to your pylance extension folder (`/home/ad.blur.com/berkheimer/.vscode-server/extensions/ms-python.vscode-pylance-2023.6.30/` from `Server root directory: /home/ad.blur.com/berkheimer/.vscode-server/extensions/ms-python.vscode-pylance-2023.6.30/dist`) and zip that folder and share with me?

just to make sure that your vsix is not busted somehow.

**Comment by heejaechang** [comment]
also, just to make sure that this is not due to some issue in `profile`, can you create `setting.json` with the `logLevel` on `workspace` (Workspace (JSON))? so, the workspace folder you are working on has `.vscode` folder with `settings.json` in it?

**Comment by james-berkheimer** [comment]
Sorry, but I need to return to my work.  If I get a chance later I can try setting up a fresh workspace.

[ms-python.vscode-pylance-2023.6.20.zip](https://github.com/microsoft/pylance-release/files/11887418/ms-python.vscode-pylance-2023.6.20.zip)
[ms-python.vscode-pylance-2023.6.30.zip](https://github.com/microsoft/pylance-release/files/11887421/ms-python.vscode-pylance-2023.6.30.zip)

**Comment by heejaechang** [comment]
just to make sure that you didn't enable our internal flag by accident or it got enabled by a bug, can you check whether you have this option enabled somewhere `"python.analysis.enableSyncServer": true`

if you can't find one, can you explicitly disable it by adding `"python.analysis.enableSyncServer": false` in one of the `settings` such as profile settings and etc, just to make sure. and see whether it still repro.

**Comment by james-berkheimer** [comment]
OK well that was a good lead because I DID have that set to true.  Not sure how that ever got set, but I have been playing around with my settings a lot.  Once I set `"python.analysis.enableSyncServer"` to false the latest version of the extension started working again.
