### ISSUE TITLE
Import "PyQt5.QtCore" could not be resolved from source

### ISSUE THREAD

**Issue by CareF** [microsoft/pylance-release#454]
There have been some discussion about not being able to resolve some package, but I don't think it applies here. 

For all `PyQt5` imports are reporting this error, but `cmd+click` jump to the correct local file at `/usr/local/lib/python3.8/site-packages/PyQt5`, so it seems that those files are accessible. 

I feel like this is either a misguiding warning message, or there's some bug about it.

**Comment by jakebailey** [comment]
That message only appears in a higher type checking mode when the module has a stub but no source/compiled module, i.e. we have completion and such for it but will believe the code will fail at runtime.

What file does it jump to? A `pyi` file? If so, what files are next to that stub?

**Comment by CareF** [comment]
Thank you for reply! 
Yes it jump to a `pyi` file, and next to it is a `.so` file. I think it's typical for PyQt.  @jakebailey

**Comment by jakebailey** [comment]
Thanks. We should be marking this import as resolved if we can resolve the compiled code; there might be a bug in the import resolver.

**Comment by Bowenf3** [comment]
Having same issue here with PyQt5.QtWidgets

**Comment by bschnurr** [comment]
closing for now. feel free to reopen if its still happening.

**Comment by Ak22735** [comment]
![image](https://user-images.githubusercontent.com/89251923/164600831-5336e836-e1b4-4446-9924-f131428fbda8.png)

**Comment by Ak22735** [comment]
@bschnurr 
![image](https://user-images.githubusercontent.com/89251923/164601283-969e76bc-ec5a-49d9-8291-31fcbfb18eab.png)
what about this

**Comment by bschnurr** [comment]
you have the correct interpreter selected?
logs from the "python language server" output pane

**Comment by SaleemMalik632** [comment]
![pip](https://user-images.githubusercontent.com/115183904/226095434-2ea7a6af-99db-4e32-9bfd-8cdb591f5766.png)
I install pyqt 5 but still geting error Import "PyQt5" could not be resolved

**Comment by debonte** [comment]
@SaleemMalik632, please file a new issue.

**Comment by ThatBegginerCoderDommi** [comment]
If anyone is still having this problem its C:\Users\johna\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
