### ISSUE TITLE
Moving symbol refactoring: docstrings have the blank line removed

### ISSUE THREAD

**Issue by wgmo** [microsoft/pylance-release#4540]
## Environment data

-   Language Server version: 2023.6.31
-   OS and version: Debian GNU/Linux 12 (bookworm) (running in WSL2 on Windows 11 Pro 22H2 22621.1848 Windows Feature Experience Pack 1000.22642.1000.0)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12

### The original content of the file _a.py_:

```python
class A:
    def __init__(self, x):
        """Make an A from an x.

        This is more complicated than you might expect. That's why it needs a more
        detailed description down here, separated from the summary by a blank line.
        """
```

### After refactoring by moving the symbol into the file _b.py_:

```python
class A:
    def __init__(self, x):
        """Make an A from an x.
        This is more complicated than you might expect. That's why it needs a more
        detailed description down here, separated from the summary by a blank line.
        """
```

... note that the necessary blank line has disappeared from the docstring.

## Repro Steps

1. Enable the "move symbol" refactoring feature (`"python.analysis.refactoring.allowMovingSymbols": true,` in _settings.json_).
1. Move a symbol which includes a docstring with a detailed description, separated from the summary by a blank line, to another file.

Note that it seems this problem affects all docstrings in the affected symbol (e.g. the docstrings for all methods in a class which is moved).

## Expected behavior

The docstrings are preserved _verbatim_ when the symbol has been refactored from file a.py to file b.py

## Actual behavior

The docstrings are preserved in their textual content, _but the required blank line between the summary and the detailed description is removed_.

## Logs

I can provide logs if necessary, but they're big so I'll only add them here if there's a specific need, the problem should be trivial to reproduce!

Great to see this refactoring feature approaching production, looking forward to seeing it make it into a release from prerelease!

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.7.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023721-12-July-2023-PreRelease)
