### ISSUE TITLE
Not perfectly work with django after update

### ISSUE THREAD

**Issue by thecyberarpan** [microsoft/pylance-release#4541]
Type: <b>Performance Issue</b>

When I develop my django application some code snippets not working. As an example: 
In "views.py" file I write this code:

```python
from django.shortcuts import render

# Create your views here.
def new(request):
    return render(request, 'index.html')   #write it mannualy
```

before update the python extension it  return render(request, 'index.html')  this command appers autometically. but after update not working. And also many issue like this. Mainly code auto complete error.

Extension version: 2023.10.1
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.11GB free)|
|Process Argv|C:\\Users\\arpan\\OneDrive\\Desktop\\Full Blog\\blogs --crash-reporter-id b5d734a5-6c3d-42f7-8644-ddab0612715a|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   396	 12924	code main
    0	    47	  2900	   utility-network-service
    2	    92	  3940	window [2] (Issue Reporter)
    0	    81	  3988	ptyHost
    0	     7	  5684	     console-window-host (Windows internal process)
    0	    68	 12360	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     7	 14984	       "C:\Windows\py.exe" .\manage.py runserver
    0	    36	 11840	         "C:\Python 3.7\python.exe" .\manage.py runserver
    3	    43	  3276	           "C:\Python 3.7\python.exe" .\manage.py runserver
    1	   163	  4344	   gpu-process
    0	    26	  4944	   crashpad-handler
    0	   157	  5016	extensionHost [1]
    0	   114	  4088	     electron-nodejs ("C:\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\arpan\.vscode\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js --node-ipc --clientProcessId=5016)
    0	    66	 15276	     "C:\Python 3.7\python.exe" c:\Users\arpan\.vscode\extensions\ms-python.python-2023.10.1\pythonFiles\run-jedi-language-server.py
    0	    23	   380	       "C:\Python 3.7\python.exe" c:\Users\arpan\.vscode\extensions\ms-python.python-2023.10.1\pythonFiles\lib\jedilsp\jedi\inference\compiled\subprocess\__main__.py c:\Users\arpan\.vscode\extensions\ms-python.python-2023.10.1\pythonFiles\lib\jedilsp 3.10.1
    0	    11	  6848	         console-window-host (Windows internal process)
    0	    11	  1584	       console-window-host (Windows internal process)
    0	    91	  5960	fileWatcher [1]
    0	   100	  6540	shared-process
    0	   187	 11188	window [1] (views.py - blogs - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (views.py - blogs - Visual Studio Code)
|    Folder (blogs): 22 files
|      File types: py(13) pyc(4) sqlite3(1)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrp:30673768
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
pythongtdpath:30769146
i26e3531:30769768
gsof1:30774496
dh2dc718:30770000
pythonidxpt:30772539
pythondjangots:30772535

```

</details>

**Comment by luabud** [comment]
Hi @thecyberarpan! Apologies for the delay in our response.
Would you mind sharing your logs as described here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue, so we can investigate this issue?
Thanks!

**Comment by bschnurr** [comment]
Can you send us which version it was working on?
