### ISSUE TITLE
Code analysis and completion don't work in devcontainers

### ISSUE THREAD

**Issue by julianofp** [microsoft/pylance-release#4547]
## Environment data

-   Language Server version: 2023.6.30
-   OS and version: Windows 10 docker(19045.2965)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12

## Code Snippet

devcontainer.json:
```json
{
  "name": "Test - Pylance",
  "build": {
    "dockerfile": "Dockerfile",
    "context": ".."
  },
  "customizations": {
    "vscode": {
      "settings": {
        "files.exclude": {
          "**/__pycache__": true,
          "**/.pytest_cache": true
        },
        "files.autoSave": "onFocusChange",
        "git.autorefresh": true,
        "extensions.ignoreRecommendations": true,        
        "isort.args": [
          "--profile",
          "black"
        ],        
        "python.analysis.diagnosticMode": "workspace",
        "python.analysis.typeCheckingMode": "strict",
        "python.analysis.logLevel": "Trace",
        "python.analysis.disableSemanticOnNoPython": false,
        "python.analysis.enableSyncServer": true,
        "python.analysis.userFileIndexingLimit": -1,
        "python.formatting.provider": "none",
        "python.languageServer": "Pylance",
        "python.linting.enabled": false,
        "python.linting.lintOnSave": false,
        "python.testing.autoTestDiscoverOnSaveEnabled": false,
        "python.testing.pytestArgs": [
          "tests"
        ],
        "python.testing.pytestEnabled": true,
        "python.testing.unittestEnabled": false,
        "[python]": {
          "editor.defaultFormatter": "ms-python.black-formatter",
          "editor.formatOnSave": true,
          "editor.formatOnPaste": false,
          "editor.formatOnSaveMode": "file",
          "editor.codeActionsOnSave": {
            "source.organizeImports": true
          }
        }
      },      
      "extensions": [
        "eamodio.gitlens",
        "ms-python.black-formatter",
        "ms-python.isort",
        "ms-python.python",
        "ms-python.vscode-pylance",
        "ms-vscode.makefile-tools"
      ]
    }
  },
  // "forwardPorts": [],
  "postCreateCommand": "pip3 install --disable-pip-version-check --no-cache-dir -r requirements.txt ",
  "postAttachCommand": "git config --global --add safe.directory ${containerWorkspaceFolder}",
  "remoteUser": "vscode"
}
```

## Repro Steps

1. Create project using the specified devcontainer.json
2. Install Dev Containers (ms-vscode-remote.remote-containers) extension
3. Open folder in Container
4. Attempt to use code completion with ctrl+space" or '.'

## Expected behavior

Code completion options should appear.

## Actual behavior

"No suggestions." message is displayed.
Logs don't contain traces, even with "python.analysis.logLevel": "Trace".
I have no issues when working locally with the latest version. Previous versions work as expected.

## Logs

```
2023-06-27 11:34:20.952 [info] [Info  - 11:34:20 AM] (784) Pylance language server 4.17.21 (pyright ae795f5b) starting
2023-06-27 11:34:20.952 [info] [Info  - 11:34:20 AM] (784) Server root directory: /home/vscode/.vscode-server/extensions/ms-python.vscode-pylance-2023.6.30/dist
2023-06-27 11:34:20.952 [info] [Info  - 11:34:20 AM] (784) Starting service instance "inventory"
2023-06-27 11:34:21.323 [info] [Info  - 11:34:21 AM] (784) Found 42 source files
```

**Comment by rchiodo** [comment]
Thanks for the issue.

The root cause of the problem is this setting here:

```json
        "python.analysis.enableSyncServer": true,
```

Did you set that yourself? That's an experimental way to run Pylance that isn't ready to be used yet. In 2023.6.30 it would cause completions to not work.

**Comment by julianofp** [comment]
I set it myself because I was having trouble with a previous version inside the devcontainer and this setting fixed it. I will try to disable it to see if it works for the latest one. Thanks!

**Comment by julianofp** [comment]
The problem is still there without the setting. Could you please reopen the issue @rchiodo?

**Comment by julianofp** [comment]
I could actually make it work by closing and reopening VSCode after build the devcontainer, so maybe the language server is not being started on postAttach.

**Comment by rchiodo** [comment]
If you look in the log and this line says the same thing:

```
2023-06-27 11:34:20.952 [info] [Info  - 11:34:20 AM] (784) Pylance language server 4.17.21 (pyright ae795f5b) starting
```

With the important part being the 4.17.21, then the setting is still there.

**Comment by rchiodo** [comment]
I believe you have to restart VS code for the devcontainer changes to take effect.

I get this is change that setting in the Devcontainer.json:

![image](https://github.com/microsoft/pylance-release/assets/19672699/afb1c95d-25b1-4372-a500-2881e156a034)
