### ISSUE TITLE
Using standalone Pylance as language server

### ISSUE THREAD

**Issue by goto1134** [microsoft/pylance-release#455]
I would like to use Pylance in my web-based IDE with monaco editor.
Is it possible to use Pylance as a standalone language server without VS Code? 

Since microsoft has plans to deprecate [microsoft/python-language-server](https://github.com/microsoft/python-language-server) it is a burning question.

**Comment by savannahostrowski** [comment]
Right now, Pylance is only available to use in the official build of Visual Studio Code. We have no plans to open-source Pylance at this time. You can use the Microsoft Python Language Server or Jedi as open-source language server options in VSCode. Alternatively, you might also find that installing [Pyright](https://github.com/microsoft/pyright) suits your needs. It's open-source and includes a large subset of Pylance functionality.
