### ISSUE TITLE
Rules overrides are not recognised

### ISSUE THREAD

**Issue by Andy-Dihong-Luo** [microsoft/pylance-release#4551]
I use Pylance in the "basic" diagnostic mode and want to enable the `strictListInference` rule. I have the code below in my settings. 

```json
"python.analysis.typeCheckingMode": "basic",
"python.analysis.diagnosticSeverityOverrides": {
    "strictListInference": true
}
```

However, when I type `[0, 'a']` e.g., Pylance still hints the list to be `List[Unknown]`. Expected to `List[int | str]`. Did I make something wrong?

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by heejaechang** [comment]
by the way, you can't set `strictListInference` in `setting.json`. you need to use either `pyrightconfig.json` or `pyproject.toml` to set it. see https://github.com/microsoft/pyright/blob/main/docs/configuration.md for more detail.

...

I just set `json` at the root of workspace folder and can see it works as expected.

```json
{
    "strictListInference": true
}
```

![image](https://github.com/microsoft/pylance-release/assets/1333179/91af6607-d9fc-4edb-9fc2-61f63f92eea1)
