### ISSUE TITLE
Huge memory leak after installing python package via integrated terminal

### ISSUE THREAD

**Issue by vishalovercome** [microsoft/pylance-release#4553]
This problem happens all the time on MacOS. No matter what python package gets installed (via pip) the memory usage of pylance keeps climbing forcing a restart. What I did notice was that this problem only happens when packages are installed from within the integrated terminal. Along with pylance extension, a Code Helper (Renderer) also ends up with a lot of memory. My python settings are:

```
"[python]": {
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
		"source.organizeImports": true
	},
	"editor.defaultFormatter": "ms-python.black-formatter",
	"editor.formatOnSave": true,
	"gitlens.codeLens.symbolScopes": [
		"!Module"
	]
},
"python.analysis.autoFormatStrings": true,
"python.analysis.autoImportCompletions": true,
"python.analysis.diagnosticMode": "workspace",
"python.analysis.fixAll": [
	"source.unusedImports"
],
"python.analysis.gotoDefinitionInStringLiteral": true,
"python.analysis.inlayHints.callArgumentNames": false,
"python.analysis.inlayHints.functionReturnTypes": true,
"python.analysis.inlayHints.pytestParameters": true,
"python.analysis.inlayHints.variableTypes": true,
"python.analysis.packageIndexDepths": [
	{
		"depth": 3,
		"includeAllSymbols": true,
		"name": ""
	}
],
"python.analysis.typeCheckingMode": "strict",
"python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python",
"python.envFile": "${workspaceFolder}/staging.env",
"python.formatting.provider": "black",
"python.languageServer": "Pylance",
"python.linting.banditArgs": [
	"--ignore=8108"
],
"python.linting.banditEnabled": true,
"python.linting.lintOnSave": true,
"python.linting.prospectorArgs": [
	"-s",
	"veryhigh"
],
"python.linting.prospectorEnabled": false,
"python.terminal.activateEnvInCurrentTerminal": true,
"python.testing.pytestArgs": [
	"."
],
"python.testing.pytestEnabled": true,
"python.testing.unittestEnabled": true,
```

**Comment by rchiodo** [comment]
Thanks for the issue.

I'm afraid the settings aren't enough to cause a problem for me locally. Do you have an example project that causes the problem? My guess is something in your specific set of installed packages is causing an issue. You might also try setting your package index depth lower. Depending upon what you have installed a depth of 3 may cause us to load a LOT of files into memory. That could be the root cause of the problem. 

Including the logs would also help us diagnose the issue:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by vishalovercome** [comment]
I've changed global depth to 2 and it didn't help. There has got to be some regression in some of the recent releases. VSCode memory spikes while simply typing out some code. Reloading the window is how I'm getting around things. I'll enable logging but it says that it produces a lot of logs and I hope that doesn't slow things down

**Comment by rchiodo** [comment]
Without a project or a repro, we can't really help here. Generally, these sort of things are caused by specific python files causing really long analysis chains in our type evaluation code. So a repro is really the only way to figure out what the problem is.

**Comment by rchiodo** [comment]
Additionally, the logs should pinpoint any files that are taking up a lot of memory when being analyzed as we print out anything that takes a long time or is consuming significant memory.

The log shouldn't have any impact on pylance's memory consumption though. It just slows things down a bit.
