### ISSUE TITLE
from scipy.spatial import KDTree error

### ISSUE THREAD

**Issue by yanxke** [microsoft/pylance-release#4556]
"KDTree" is unknown import symbol

## Environment data

-   Language Server version: v2023.6.40
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.6

## Code Snippet

from scipy.spatial import KDTree

**Comment by debonte** [comment]
This is a duplicate of https://github.com/microsoft/pylance-release/issues/4531 which is fixed in our latest pre-release build, 2023.6.41.
