### ISSUE TITLE
Server settings should be printed when in 'trace' mode.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4559]
We frequently have issues where we don't know the settings from the user. We could just print them out in the trace logs as soon as we get them in the server.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.7.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023731-19-July-2023-PreRelease)
