### ISSUE TITLE
Pylance can not realize auto-complete function

### ISSUE THREAD

**Issue by Glutaredoxin** [microsoft/pylance-release#4561]
hello :>
When the mouse hovers over the code, it always shows "LOADING", and there is no auto-complete function.
i make sure that me settings are correct.
Is there any possibility of causing such a problem?

**Comment by Glutaredoxin** [comment]
![image](https://github.com/microsoft/pylance-release/assets/55617926/8f51aba6-dcdb-4fc9-b5f1-0d7d5d3b97ff)

**Comment by luabud** [comment]
Hi @Glutaredoxin! Apologies for the delay in our response. 
Would you mind sharing your logs as described here: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue, so we can investigate this issue?
Thanks!

**Comment by jasonreed7780-commits** [comment]
Ok
