### ISSUE TITLE
Pylance is removing imports used by type annotations

### ISSUE THREAD

**Issue by Mapiarz** [microsoft/pylance-release#4563]
## Environment data

-   Language Server version: v2023.6.40
-   OS and version: Ubuntu 22 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11

## Code Snippet

I need to annotate a Django's ForeignKey like in the example below. `Foo` cannot be imported 'normally' due to circular import. When Pylance removes the `Foo` import then my type annotations for `DjangoModel.foo` no longer work (quite obviously).

```python
from typing import TYPE_CHECKING
from django.db import models

if TYPE_CHECKING:
    from my_module.models import Foo

class DjangoModel:
    foo = models.ForeignKey["Foo"]("Foo", on_delete=models.CASCADE)
```

## Expected behavior

Pylance not to remove the type checking import of `Foo`

## Actual behavior

Pylance removes import of `Foo`

**Comment by heejaechang** [comment]
no longer repro
