### ISSUE TITLE
Pylance fails to recognize import in Jupyter notebook from transformers package (Symbol is unknown import symbolPylance), but successfully finds import in a pure Python file.

### ISSUE THREAD

**Issue by montyevans** [microsoft/pylance-release#4572]
This has been raised as an issue on the [transformers repo](https://github.com/huggingface/transformers/issues/24548), but it seems to be a Pylance / VSCode issue, rather than a transformers issue, because Pylance correctly finds the input in pure Python files.

A first look suggests that this stems from the use of transformers using Lazy Modules in its importing, but I can't say this for sure.

## Environment data

-   Language Server version: v2023.6.40
-   OS and version: macOS Ventura 13.4.1
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.10.11

## Code Snippet

If you paste the code into a pure Python file, Pylance recognizes the import fine. In a VSCode Jupyter notebook cell it fails with the error:

> "AutoConfig" is unknown import symbolPylance [[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)]

<img width="683" alt="image" src="https://github.com/microsoft/pylance-release/assets/32969601/f63b3197-868a-442f-b87b-2a8b5bca344e">

```python
from transformers import AutoConfig
hf_config = AutoConfig.from_pretrained("gpt2")
```

## Logs
I tried to produce logs using the recommended method, but they were too long to fit inside a github issue. Can provide any logs that would be helpful if you give me a way to narrow them down.

**Comment by debonte** [comment]
I'm unable to repro this. Do you have the correct environment/kernel selected in the notebook?

![image](https://github.com/microsoft/pylance-release/assets/12820898/b214de24-6cec-4fb7-a0e2-54969061d887)

> I tried to produce logs using the recommended method, but they were too long to fit inside a github issue. Can provide any logs that would be helpful if you give me a way to narrow them down.

You can drag the log file into the comment box as an attachment rather than copying the contents as text.

**Comment by montyevans** [comment]
Hmmn, weird. I just tried with a fresh venv, installing just `transformers` and `torch`. Same result (and I double checked that I have the right kernel selected - see example screenshot). 

<img width="1284" alt="image" src="https://github.com/microsoft/pylance-release/assets/32969601/610196f8-60f8-4fed-94a9-a40584919b39">

Logfile attached - thanks for the tip!

[debug_log.txt](https://github.com/microsoft/pylance-release/files/11950888/debug_log.txt)

**Comment by debonte** [comment]
That's not the full log. Can you reopen this test project and file and then provide the full log?

**Comment by montyevans** [comment]
Ah, sorry! Just closed & reopened the project.

I see that starting line, but weirdly now a much smaller log, so unsure if this is truncated or no?

[debug_log_2.txt](https://github.com/microsoft/pylance-release/files/11951107/debug_log_2.txt)

**Comment by debonte** [comment]
Can you set `"python.analysis.logLevel": "Trace"` and then restart? Sorry, for some reason I thought you had that set already.

**Comment by montyevans** [comment]
Yep, it's set already - I just quit and restarted VSCode to make sure it got picked up. The logs look the same as before (pretty sure I've had that option toggled for the whole debugging process), but I've attached the new ones just in case. If there's a command I can run to verify that `logLevel: Trace` is being picked up, lmk and I'll run it.

<img width="438" alt="image" src="https://github.com/microsoft/pylance-release/assets/32969601/cf85298a-0e49-45d4-b95b-cae40ad9b3f8">

[debug_log_3.txt](https://github.com/microsoft/pylance-release/files/11951242/debug_log_3.txt)

**Comment by hidaris** [comment]
I also encountered a similar problem in Langchain. Sometimes, after starting VSCode, it prompts that the instance variable is unknown, but sometimes it is normal

**Comment by debonte** [comment]
@montyevans, I was just trying to repro this again. I couldn't get it to happen in the latest Pylance build, but when I rolled back to 2023.6.40 I hit something similar in a regular .py file:

![image](https://github.com/microsoft/pylance-release/assets/12820898/74c8b1f0-5e79-4186-afe0-b9ba87c67764)

This is https://github.com/microsoft/pylance-release/issues/4531. Notice how it complains that `"AutoConfig" is unknown import symbol`, but the hover window also displays the doc string for `AutoConfig`. That's the signature of issue 4531 -- analysis is broken, but requests handled by our foreground thread (ex. hover) work. Was that what you were seeing also?

I'm curious to know if you can still reproduce this issue on the latest pre-release build of Pylance -- 2023.7.31

**Comment by montyevans** [comment]
No, it doesn't repro in 2023.7.30 (the version that my laptop's VSCode at some point auto-updated to).

Guess the #4531 fix was exactly it - thanks!
