### ISSUE TITLE
incorrect warnings for "unused variables" that are actually used

### ISSUE THREAD

**Issue by yasuoiwakura** [microsoft/pylance-release#4582]
## Environment data

-   Language Server version: 2023.7.10 (pyright 74d8f3c4)
-   OS and version: Win10 Pro 22H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet
    ...
    b_step1_getalltenants = args.new_tenant_list
    ...
    sf_tenants_3_settings_sorted= f"{DIR_TEMP}/{s_run_date}_{s_master_tenant}_2_settings[{s_taskid}]_sorted"
    ...
    ...
    try:
        if not b_step1_getalltenants:
            print(123)
            ld_tenants_todo_flat = json_read(sf_foobar)
    except FileNotFoundError:
        print(123)
        try:
            ld_tenants_todo_flat = csv_read(foobar)
        except FileNotFoundError:
            print(123)
            b_step1_getalltenants = True
    ###########################  FOOBAR ###############################
    if b_step1_getalltenants:
    ...
    ...
    json_save(ld_tenants_done_flat, sf_tenants_3_settings_sorted)

## Repro Steps

1. assign var and use it later

## Expected behavior

no pylance warning

## Actual behavior

some pylance warnings that should not be there (but only for 10% of the vars)
warning: "b_step1_getalltenants is unused"
warning: "sf_assets is unused"

## Logs

I could not reproduce the error in a sample script, 

```
the whole script may contains sensitive information, is a logging needed?```

**Comment by erictraut** [comment]
Could you provide a minimal, self-contained code sample that demonstrates the problem? Your code above references a bunch of symbols that are not defined (e.g.  `args` and `DIR_TEMP`), which makes it difficult to repro the problem you're seeing.

**Comment by yasuoiwakura** [comment]
> Could you provide a minimal, self-contained code sample that demonstrates the problem? Your code above references a bunch of symbols that are not defined (e.g. `args` and `DIR_TEMP`), which makes it difficult to repro the problem you're seeing.

hey there,
currently i'm unable to reproduce the behavior in a minimalistic sample.

The Code combinations seems to run pylance unfunctional, the effect disappears when removing parts of the code and cannot be traced down to a certain part of the code.

I understand it's hard to qualify this issues with the example,
I'll come back after checking if I can supply the example or not

**Comment by judej** [comment]
Closing awaiting repro.

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
