### ISSUE TITLE
unable to import 'django.db' in pylance 

### ISSUE THREAD

**Issue by dhanubalde** [microsoft/pylance-release#4585]
<h3> Environment data </h3>

-   Language Server version: 2023.7.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue.

Do you have an example? This works for me:

![image](https://github.com/microsoft/pylance-release/assets/19672699/554bf852-247a-4d35-a126-cb1af7ab386c)


If you're seeing something like so:
![image](https://github.com/microsoft/pylance-release/assets/19672699/20d8bd51-5a8d-48ab-8657-e1f4099a2351)

You might need to select the correct interpreter in VS code for us to find Django. (I got that warning to show up by picking an interpreter that didn't have Django installed).

Can you include a log as described here?
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
