### ISSUE TITLE
Pylance shows unresolved imports for installed packages after opening notebook files in WSL

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#4596]
## Environment data

-   Language Server version: 2023.7.11
-   OS and version: Windows 11 using WSL 2 (Ubuntu)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11, .venv

## Repro Steps

1. Install and set up the [WSL extension](https://code.visualstudio.com/docs/remote/wsl#_getting-started) 
1. Connect to the WSL extension and clone a repo. Any repo should work, the important thing is for it to use packages that need to be installed (e.g. https://code.visualstudio.com/docs/python/tutorial-django)
2. Run the "Python: Create Environment" command to create a virtual environment and install the dependencies listed in requirements.txt 
3. Open a file that imports a package and verify Pylance is not showing any unresolved imports
4. Now create a notebook file (File > New file.. Jupyter notebook)
5. Save the notebook
6. Open the same file from step 3
7. See the unresolved imports

![unresolvedimportsbugwsl](https://github.com/microsoft/pylance-release/assets/45497113/f0b5c989-418e-439e-8c73-41dc11d002ef)

## Logs

[logs.txt](https://github.com/microsoft/pylance-release/files/12021726/logs.txt)

**Comment by dbalabka** [comment]
I'm experiencing the same issue. 
VSCode:
```
Version: 1.81.0-insider (user setup)
Commit: 4390ebc406732e5b4eed22a1d7aa4fc0ef4a9460
Date: 2023-07-18T05:36:41.526Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23466
```

PyLance version: `v2023.7.20`

**Comment by debonte** [comment]
Dupe of https://github.com/microsoft/pylance-release/issues/4606?

**Comment by rchiodo** [comment]
Yeah, looks like the exact same circumstances. 

You can verify by editing the file with the import errors and see if the errors suddenly go away.

**Comment by luabud** [comment]
Cool, thanks! closing as dupe of https://github.com/microsoft/pylance-release/issues/4606
