### ISSUE TITLE
Does Pylance use `django-stubs` or `django-types` for its Django type hints?

### ISSUE THREAD

**Issue by joeriddles** [microsoft/pylance-release#4597]
There is conflicting information on whether the Pylance extension bundles [django-stubs](https://github.com/typeddjango/django-stubs) or [django-types](https://github.com/sbdchd/django-types). Can someone help me understand which Pylance currently uses?

### django-types
Most documentation in the last two years points to django-types, such as:
- https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2022931-21-september-2022-prerelease
![image](https://github.com/microsoft/pylance-release/assets/19392916/43847a3a-970b-49cf-ab4d-6c219c4bce0c)
- https://github.com/microsoft/pylance-release/issues/3918#issuecomment-1472117429
  > I mistakenly fixed this in https://github.com/microsoft/python-type-stubs instead of https://github.com/sbdchd/django-types.

### django-stubs
If I use "Go to Definition" (F12) of some imported Django type hints, it shows django-stubs:

```python
import typing

if typing.TYPE_CHECKING:
    from django.db.models.manager import RelatedManager  # <-- use "Go to Definition" in VS Code
```

![image](https://github.com/microsoft/pylance-release/assets/19392916/8e74e83b-43fb-485b-821b-0cd18e62984f)

**Comment by debonte** [comment]
We ship `django-types` which is a fork of `django-stubs` and is installed to a directory of the same name. For an explanation of why, see https://github.com/microsoft/pylance-release/issues/4562#issuecomment-1615049922.

**Comment by joeriddles** [comment]
> We ship `django-types` which is a fork of `django-stubs` and is installed to a directory of the same name. For an explanation of why, see [#4562 (comment)](https://github.com/microsoft/pylance-release/issues/4562#issuecomment-1615049922).

Thanks for the explanation and link @debonte!
