### ISSUE TITLE
Walrus operator not recognised 

### ISSUE THREAD

**Issue by ciaranjudge** [microsoft/pylance-release#46]
## Thank you!!!

Thank you so much for producing Pylance - it's amazingly fast and I really love the grayed out unused imports! :+1: :1st_place_medal: 

## Environment data

-   Language Server version: v2020.6.1
-   OS and version: Windows 7 :(
-   Python version : 3.8.3

## Expected behaviour

Pylance recognises walrus operator and correctly parses code containing it

## Actual behaviour

Pylance doesn't recognise walrus operator and throws up errors/warnings

## Code Snippet / Additional information

This is a little helper class that's useful for getting the right version of metadata that change over time. 

It's got a couple of walrus operators in it but it works without issues in Python 3.8.

```python
class NearestKeyDict(collections.UserDict):
    """Dictionary for looking up nearest key to a given key.
    Useful for 'nearest date' lookups but can work for any keys implementing <= >=

    Based on https://stackoverflow.com/a/3387975/13088500
    """

    def __init__(self, data={}, how="max_before"):
        self.data = data
        self.how = how

    def __getitem__(self, key):
        return self.data[self._keytransform(key)]

    def __setitem__(self, key, value):
        self.data[self._keytransform(key)] = value

    def __delitem__(self, key):
        del self.data[self._keytransform(key)]

    def _keytransform(self, key):
        if self.how != "min_after":
            if len(candidate_keys := [k for k in sorted(self.data) if k <= key]):
                return max(candidate_keys)
            else:
                raise KeyError(f"No data key found before {key}")
        else:
            if len(candidate_keys := [k for k in sorted(self.data) if k >= key]):
                return min(candidate_keys)
            else:
                raise KeyError(f"No data key found after {key}")
```
![walrus_pylance_issue_1](https://user-images.githubusercontent.com/45339268/86464515-8e7aad00-bd27-11ea-8640-d5fc9fc025bd.png)

**Comment by erictraut** [comment]
Thanks for the bug report. I've fixed the bug, and the fix will be in an upcoming version of Pylance.

**Comment by ciaranjudge** [comment]
Thank you so much - that was amazingly fast!!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.7.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202070-9-july-2020

**Comment by jamesohortle** [comment]
Unsure if there has been further discussion on this topic, but this appears to still not be fixed for me:

```python
import os
from typing import Optional

AUTHORITY: Optional[str] = auth_str.format(tenant_id=TENANT_ID) if (os.environ.get("AUTHORITY") := auth_str) is not None else None
```
Produces a red squiggle under `:=` and a hover tile `Expected ")" Pylance`.

Pylance version: 2021.1.13
Python version: 3.8.7
VS Code version: 1.52 (November 2020)

**Comment by NaokiSato102** [comment]
![image](https://user-images.githubusercontent.com/27545766/153744744-aa87ffa8-0584-47a1-b50c-817772c75d72.png)
![image](https://user-images.githubusercontent.com/27545766/153744757-1c247f46-f848-41ff-a445-79b41f94aecf.png)
I don't know why, but I'm having a relapse. I'm in trouble.

**Comment by erictraut** [comment]
@NaokiSato102, does this code run in the interpreter without crashing? I wonder if there's a corrupt (non-visible) character present. If you can't figure it out, please file a new issue with the information requested in the issue template.

**Comment by NaokiSato102** [comment]
[cannot use assignment expressions with attribute] has occurred.
It seems to match [this example](https://realpython.com/python-walrus-operator/). I didn't know...

I apologize for the inconvenience. However, if possible, it would be kind to goofballs like me if you could make it clear that this is the cause of the symptom.

**Comment by erictraut** [comment]
Ah, I didn't notice that you were using an attribute on the left-hand side of the assignment expression. That's not allowed in the Python grammar, so your code produces a syntax error. The error message provided by pylance could be clearer here.

For more details about assignment expressions, refer to [this documentation](https://docs.python.org/3/reference/expressions.html#assignment-expressions). Note that the expression on the left-hand side must be a simple identifier (like `x`), not an attribute access expression (like `self.x`).
