### ISSUE TITLE
deprecated warnings are not displayed when another decorator is under `@deprecated`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/pylance-release#4600]
## Environment data

-   Language Server version: 2023.6.40 (pyright 3f84540e)
-   OS and version: windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

```python
from typing import TypeVar

from typing_extensions import deprecated

T = TypeVar("T")


def deco(fn: T) -> T:
    return fn


@deprecated("asdf")
def foo():
    ...


foo()


@deprecated("asdf")
@deco
def bar():
    ...


bar()
```

## Expected behavior

deprecated warning on both `foo` and `bar` function calls

## Actual behavior

only the `foo` function call has the deprecation warning
![image](https://github.com/microsoft/pylance-release/assets/57028336/a2cf0a84-f36b-4755-8d43-46b7bdb648f5)

**Comment by erictraut** [comment]
This is intended behavior. If you apply the deprecated decorator directly to the (undecorated) function or method, the function will be flagged as deprecated.

**Comment by DetachHead** [comment]
why not make it work in both cases?

**Comment by KotlinIsland** [comment]
> This is intended behavior. If you apply the deprecated decorator directly to the (undecorated) function or method, the function will be flagged as deprecated.

Why? The pep doesn't mention that. 

Additionally, given the runtime functionality:

```py
from typing_extensions import deprecated

def wrap(fn):
    def wrapper():
        return fn()
    return wrapper

@deprecated("asdf")
def foo(): ...

@deprecated("asdf")
@wrap
def bar(): ...

foo()  # DeprecationWarning: asdf
print(foo.__deprecated__)  # asdf
bar()  # DeprecationWarning: asdf
print(bar.__deprecated__)  # asdf
```
