### ISSUE TITLE
Unable to find references of a class instance attribute

### ISSUE THREAD

**Issue by Econ808** [microsoft/pylance-release#4604]
## Environment data

-   Language Server version: v2023.7.21
-   OS and version: Windows 10 Enterprise
-   Python version: 3.8.10 ('venv': venv)

## Issue

Pylance cannot find references of a class instance attribute when a class is passed to another class which then uses the instance attribute.

## Expected behavior

I expect vscode/Pylance to find the uses of the instance attribute `ray_settings`. Here is an example of how PyCharm is able to find multiple references of said instance attribute:

![image](https://github.com/microsoft/pylance-release/assets/36441764/78be26fd-4453-4fa3-a3d2-8927772491ca)

## Actual behavior

When using shift+alt+F12 to find references, only the creation of the instance attribute is found:

![image](https://github.com/microsoft/pylance-release/assets/36441764/d1e5e94c-4ad5-463a-9c2e-8cca3c116643)

**Comment by heejaechang** [comment]
@Econ808 can you provide us actual code examples to make sure we are on the same page?
