### ISSUE TITLE
String containing hash `#` breaks IntelliSense suggestions

### ISSUE THREAD

**Issue by hassanselim0** [microsoft/pylance-release#461]
## Environment data

- Language Server version: 2020.9.8
- OS and version: Windows 10 v2004
- Python version: Python 3.8.2

## Expected behaviour

Given this code sample:
```python
msg = 'hello'
print('upper: ' + msg.upper())
print('#upper: ' + msg.upper())
```
After typing `msg.` in both cases, I should get the IntelliSense suggestions for the str type.

## Actual behaviour

In case of the second print line, I don't get suggestions, and manually executing the "Trigger Suggest" command shows "No Suggestions" or generic text suggestions.
![image](https://user-images.githubusercontent.com/1431770/95125895-e5908380-0755-11eb-85d6-4ef54abc585e.png)

## Logs

Couldn't find any relevant logs

## Code Snippet / Additional information

My guess is that the `#` makes it assume I'm inside a comment even though the `#` is inside a string.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020110-4-november-2020
