### ISSUE TITLE
 Cannot access member "coastlines" for type "Axes"   Member "coastlines" is unknown

### ISSUE THREAD

**Issue by mgorfer** [microsoft/pylance-release#4610]
## Environment data

-   Language Server version: Pylance language server 2023.7.21 (pyright 74d8f3c4)
-   OS and version: Manjaro
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16

## Code Snippet

```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

# Create a figure and a GeoAxes object with a PlateCarree projection
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())

# Call the coastlines method on the GeoAxes object
ax.coastlines(resolution="110m")
```

## Repro Steps

1. Add the code snipped in VSCode.

## Expected behavior

No error is shown, as `ax` is an `GeoAxes` Object.

## Actual behavior

The error `Cannot access member "coastlines" for type "Axes" Member "coastlines" is Unknown Pylance[reportGeneralTypeIssues]` is shown for `ax.coastlines(resolution="110m")`.

Pylance does not recognize that `ax` is actually a `GeoAxes` object.

Does this need to be fixed from cartopy itself?

**Comment by StellaHuang95** [comment]
Hi there, it appears that the return type of `add_subplot` changes depending on the value passed to the `projection` parameter. In other words, the return type varies based on the value not the type, so it's not something that the static analysis tool can generally supports. If there're ways to figure out return type based on types on signature, we could consider adding overloads. Otherwise, you will need to either cast or use the `isInstance` check to narrow the type.

**Comment by erictraut** [comment]
@StellaHuang95, `add_subplot` is defined using an overload in the stubs that pylance bundles. Here's the relevant part (in `stubs/matplotlib/figure.pyi`:

```python
    def add_subplot(self, *args, projection: Literal['3d'], **kwargs) -> Axes3D: ...
    @overload
    def add_subplot(self, *args, **kwargs) -> Axes: ...
```

It may be feasible to add more overloads based on literal types. It looks like `projection` accepts a limited number of literal values, as per [this documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.subplot.html).

**Comment by StellaHuang95** [comment]
Thanks! It may not address the problem in this issue, but might be beneficial for other cases. I can definitely look into adding more overloads based on literal types.
