### ISSUE TITLE
TypeVar yields an error when used with reduce

### ISSUE THREAD

**Issue by egeres** [microsoft/pylance-release#4614]
**👉🏻 Describe the bug**
When analyzing the code from below, I get:
```
Expression of type "list[int]" cannot be assigned to return type "T@foo"
  Type "list[int]" cannot be assigned to type "T@foo"Pylance[reportGeneralTypeIssues](...
```
This seems to happen because, the output of `reduce` is correctly parsed as a `list[int]`, but then that type would be different from `list[T]`, even if `T` is bound to `list[int]`

**👉🏻 To Reproduce**
Put the code below in VSCode + pylance version `v2023.7.20`

**👉🏻 Expected behavior**
If a `TypeVar` is bound to a type (even if it's a composition using `Union` etc...), Pylance should consider another type valid if it matches with the bound of such `TypeVar`

**👉🏻 Code**
```python
from functools import reduce
from typing import TypeVar

T = TypeVar("T", bound=list[int])

def foo(x: list[T]) -> T:
    return reduce(lambda a, b: a + b, x)
```

**👉🏻 VS Code extension or command-line**
Running pylance in VSCode as an extension!

**Comment by erictraut** [comment]
Pyright is correct to emit an error here. You're using a TypeVar that is bound to `list[int]`. Here's the applicable overload for `reduce`:
```python
def reduce(function: Callable[[_T, _T], _T], sequence: Iterable[_T]) -> _T:
    ...
```

That means the two inputs to the callable must be the same type as the output. In your case, the inputs are type `T`, but the output is type `list[int]`. The expression `a + b` in the lambda maps to the method `__add__` in the `list` class. This is defined to always return another `list`, not a `Self`. That means if `T` happens to be a subclass of `list`, the `a + b` operation will not produce the same subtype. 

Not surprisingly, mypy generates the same error for this code.

Here's how to adjust your code so it type checks without error:

```python
T = TypeVar("T")

def foo(x: Iterable[list[T]]) -> list[T]:
    return reduce(lambda a, b: a + b, x)
```

**Comment by egeres** [comment]
I'm sorry I didn't see this and reported a false positive!! 🙇🏻‍♂️
