### ISSUE TITLE
pylance shows prompts in Russian, while the vscode interface is in English.

### ISSUE THREAD

**Issue by Hudrolax** [microsoft/pylance-release#4616]
<img width="782" alt="image" src="https://github.com/microsoft/pylance-release/assets/58570622/f3cbea4f-6708-4a4e-8cc0-0a6ef04f855d">

**Comment by bschnurr** [comment]
have you tried setting locale? see https://code.visualstudio.com/docs/getstarted/locales

**Comment by bschnurr** [comment]
see this. https://github.com/microsoft/pylance-release/issues/4579#issuecomment-1640733279
