### ISSUE TITLE
Bug Import "dotenv" could not be resolved - Pylance

### ISSUE THREAD

**Issue by Cwei0** [microsoft/pylance-release#4619]
I installed the python-dotenv and the python-decouple packages to help load my env files. But Pylance can seem to resolve them at all

**Comment by judej** [comment]
Thanks for the report, unfortunately, this is not enough data for us to debug. 

If this continues to be a problem, would you please reopen the issue and add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
