### ISSUE TITLE
matplotlib: missing types

### ISSUE THREAD

**Issue by mvolkmann** [microsoft/pylance-release#462]
Do I understand correctly that Pylance bundles type stub files for popular libraries like matplotlib?
I get type errors for some things and I wonder if they are just missing from the bundled stub files.
For example, it doesn't recognize that `Axes` objects have a `clear` method and this import gives an error:

```python
import matplotlib.animation as animation
```

Can I add my own versions of these stub files in the `typings` subdirectory of my project to override them?
If so, what file names do they need to have?

**Comment by jakebailey** [comment]
Yes, it does, and the matplotlib stubs aren't fully complete yet.

You can override them by adding `typings/matplotlib`, and the folder structure in there, or install a package that overrides them. The bundled stubs are read last overall (typings, installed stubs, original code).

**Comment by mvolkmann** [comment]
Oops! @jakebailey I guess you didn't want to close this yet. I reopened it.

**Comment by jakebailey** [comment]
Yes, I need to find some time to fix the matplotlib stubs.

**Comment by CatNofishing** [comment]
@jakebailey   can you response  my issue #301, i think this issue is a big problem.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202130-3-march-2021
