### ISSUE TITLE
Pylance does not show docstring in hover window

### ISSUE THREAD

**Issue by Lustrewilkin** [microsoft/pylance-release#4622]
## Environment data

-   Language Server version: v2023.7.21
-   OS and version:  win11, VScode 1.80.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12

## Description

I am using Pylance as the language server for Python in VScode. I have written a docstring for a function using reStructuredText format, and I have set the python.analysis.typeCheckingMode to basic and the python.analysis.autoSearchPaths to true in the Pylance settings. However, when I hover over the function name, the hover window does not show the docstring, only the function signature. I have tried to restart VScodeand reinstall Pylance, but the problem persists. My code is the same as the Pytorch Conv2d function doc, and also has the same problem. Here is my code and a screenshot of the hover window:

## Code Snippet

```python
import torch as th
print(th.nn.Conv2d.__doc__)

class Conv2d(_ConvNd):
    __doc__ = r"""Applies a 2D convolution over an input signal composed of several input
    planes.

    In the simplest case, the output value of the layer with input size
    :math:`(N, C_{\text{in}}, H, W)` and output :math:`(N, C_{\text{out}}, H_{\text{out}}, W_{\text{out}})`
    can be precisely described as:

    .. math::
        \text{out}(N_i, C_{\text{out}_j}) = \text{bias}(C_{\text{out}_j}) +
        \sum_{k = 0}^{C_{\text{in}} - 1} \text{weight}(C_{\text{out}_j}, k) \star \text{input}(N_i, k)


    where :math:`\star` is the valid 2D `cross-correlation`_ operator,
    :math:`N` is a batch size, :math:`C` denotes a number of channels,
    :math:`H` is a height of input planes in pixels, and :math:`W` is
    width in pixels.
    """
......
```

## Screenshot
![image](https://github.com/microsoft/pylance-release/assets/63487490/67cc8b95-39ee-4798-8c3f-a3c7a9b22dfe)

## Repro Steps

1. XXX

## Expected behavior

The hover window should show the docstring of the function, including the math formula and the cross-correlation link.

## Actual behavior

The hover window only shows the function signature, without any docstring.

## Logs

```
XXX
```

😢Please let me know if you need any more information or if you have any suggestions on how to fix this issue. Thank you for your help.

**Comment by Lustrewilkin** [comment]
add additional message
the normal docstring rather than `__doc__ = r"""xxx"""` work normally except for displaying Formula using `.. math:: `.

**Comment by erictraut** [comment]
Why are you dynamically assigning the value to the underlying `__doc__` attribute rather than simply placing the docstring string literal as the first statement within the class body? This is very non-standard, and most static analysis tools (including pyright / pylance) will not work with this. If you delete the `__doc__ = ` from the beginning of the statement, it will work fine.

**Comment by Lustrewilkin** [comment]
thanks for ur comment. 

## Replay
(I didn't see the replay button)
But the Pytorch use this format docstring in their functions, and that will allow us to make more complex presentation, like this
```python
def my_func(*pram):
    __doc__ = r"""
        content
    """ + f""" 
        content 
    """ + """
        content
   """
   function content
```
if I use this presentation without `__doc__`, it wont run right as second pic
![image](https://github.com/microsoft/pylance-release/assets/63487490/e4fe71bc-d9e6-4b6f-af58-4bd5905bc265)
![image](https://github.com/microsoft/pylance-release/assets/63487490/e3f88ab1-b46c-4968-b2b9-e9f205c4095b)

## Math not appear
On the other hand, deleting the `__doc__ = `seems not completely resolve it. in the flowing pic, the `.. math:: ` still don't work.

![image](https://github.com/microsoft/pylance-release/assets/63487490/58faeebf-4362-4286-aa15-80d9403636b8)

In the end, I used to use it without any problems until I switched to a new computer, and the configuration and plugins of vscode were the same. This is a strange problem 😢😢😢

**Comment by erictraut** [comment]
If your code is dynamically building docstrings and assigning them to `__doc__`, a static analyzer will not understand this. Pylance doesn't run your Python code; it's analyzing the code statically. If you want your docstrings to appear in hover text when using pylance, you'll need to define them using a string literal, not a complex (dynamic) expression.

**Comment by Lustrewilkin** [comment]
> if your code is dynamically building docstrings and assigning them to `__doc__`, a static analyzer will not understand this. Pylance doesn't run your Python code; it's analyzing the code statically. If you want your docstrings to appear in hover text when using pylance, you'll need to define them using a string literal, not a complex (dynamic) expression.

ok, I get it. Thank you for your answer
