### ISSUE TITLE
 Incorrect Hints

### ISSUE THREAD

**Issue by LeieXoyo** [microsoft/pylance-release#4642]
I want to know why when "import tornado", tornado.xxx[yyyy]<tornado.web.RequestHandler> doesn't give me the right hint, it just indicates that it's a function, whereas when I import yyy, zzz from xxx, I get the right hint! when I import yyy, zzz from xxx, I get the correct
![屏幕截图 2023-07-23 191735](https://github.com/microsoft/pylance-release/assets/17492992/46fa9ef2-8d29-4fec-892c-9956d9bcfcf4)
![屏幕截图 2023-07-23 191713](https://github.com/microsoft/pylance-release/assets/17492992/ec91e8de-03fc-4770-8dc9-ce14b48c8754)
![屏幕截图 2023-07-23 191810](https://github.com/microsoft/pylance-release/assets/17492992/8e213f56-9e6a-4e35-8d76-3caa73abf068)

**Comment by debonte** [comment]
If you change your `import tornado` to `import tornado.web` you'll get the behavior that you want. You can read more about how Pylance models the behavior of `import` statements [here](https://github.com/microsoft/pyright/blob/main/docs/import-statements.md).

It appears that the `__getattr__` in `tornado/__init__.py` is intended to support your current approach at runtime, but static analysis tools like Pylance will not be aware of this dynamic behavior.

Ideally `tornado` would expose its interface in a way that is supported by static analysis tools. If this is important to you, you could point the authors of `tornado` at [this documentation](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md) about library interfaces.

**Comment by LeieXoyo** [comment]
Thank you very much for your answer, when I use "import tornado.web", I get the expected result.
