### ISSUE TITLE
PYLANCE issue

### ISSUE THREAD

**Issue by namanj975** [microsoft/pylance-release#4643]
<h3> Environment data </h3>

-   Language Server version: 2022.1.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: null
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
Match statements require Python 3.10 or newerPylance
```

<h3> Code Snippet / Additional information </h3>

```python
match value:
        case "one":
            result = 1
        case "two":
            result = 2
        case "three" | "four":
            result = (3, 4)
        case _:
            result = -1

```

**Comment by judej** [comment]
thanks for the report. The version of Pylance shown is Language Server version: 2022.1.3. That is old. Could you please update Pylance and see if this repros? If it does please reopen this issue
