### ISSUE TITLE
'PROBLEMS Window' doesn't report any errors or warnings when imported file is empty

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#4654]
## Environment data
**Build of Visual Studio Code - Insiders: 1.81.0-insider 
Build of python-insider: v2023.13.12071009 
Build of pylance-insider: v2023.7.41** 

## Repro Steps

1. Open a folder and create two python files
2. Open **test.py** and define a method in it
3. Open **file1.py** and import the method from **test.py**
4. Go back to **test.py** and clear the method
5. Save all files

## Expected behavior
PROBLEMS Window should report errors or warnings

## Actual behavior
PROBLEMS Window doesn't report any errors or warnings
![vsc_import](https://github.com/microsoft/pylance-release/assets/59192491/4bb474e9-6443-493e-8d65-1fef8bf308bf)

**Comment by debonte** [comment]
It appears that you have `python.analysis.typeCheckingMode` set to `off`. The error that you are expecting to see is disabled by default when `typeCheckingMode` is `off`. You'll get the behavior that you expect if you set it to either `basic` or `strict`.

Clicking on the curly braces in the VS Code status bar when a Python file is open is a quick way to toggle `typeCheckingMode` between `off` and `basic`:

![image](https://github.com/microsoft/pylance-release/assets/12820898/e36bce24-46aa-4ad9-a918-1b0eb755136a)
