### ISSUE TITLE
Annotated for docstring purpose

### ISSUE THREAD

**Issue by D-X-Y** [microsoft/pylance-release#4657]
Many people attach docstring as a metadata in Annotated:
```
from typing import Annotated

class Foo:
    f: Annotated[str, 'xxxxxx'] = "asdf"
```
If we hover the pointer on Foo, VS Code shows nothing. However, if we write codes like this:
```
class Foo:
    f: str = "asdf"
    """xxxxxx"""
```
and then VS Code can understand its docstring is """xxxxxx""".

Could pylance support the same feature for `Annotated` when the second arg is just a string?

**Comment by erictraut** [comment]
> Many people attach docstring as a metadata in Annotated

Can you provide some documentation or examples that back up that assertion? 

To my knowledge, there is no standard that says that a literal string passed as a type argument to `Annotated` should be assumed to be a docstring. `Annotated` can be used anywhere that type annotations are allowed, and docstrings don't make sense in many of those locations.

There have been some attempts to standardize a `docs` class that wraps a literal string, but a "naked" literal string could have many meanings inside of an `Annotated` annotation. I don't think it would be appropriate to assume that it is intended as a docstring.

[PEP 593](https://peps.python.org/pep-0593/), which introduced `Annotated`, defines a meaning to the first type argument but explicitly says that static analysis tools (including type checkers) should not ascribe any specific meaning to subsequent type arguments.

Pylance does support attribute docstrings of this form:

```python
class Foo:
    f: str = "asdf"
    """A description of the field f goes here"""
```

**Comment by D-X-Y** [comment]
The authors' reply resolved my problem.
