### ISSUE TITLE
Wrong color for decorator parameters when chaining calls

### ISSUE THREAD

**Issue by uf-fipper** [microsoft/pylance-release#4666]
## Environment data

-   Language Server version: pylance 2023.7.31 (19 July 2023) PreRelease
-   OS and version: win11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7

## Code Snippet

```python
class A:
    def f(self, *args, **kwargs):
        return self

    def __getitem__(self, *args, **kwargs):
        return self

    def __call__(self, f):
        return f


@A().f(2, b=4)["123", "456"].f(1, a=3)
def func():
    print("call func")


func()

```

## Expected behavior

![image](https://github.com/microsoft/pylance-release/assets/55644019/06964eba-ec62-4548-b6ee-87b7ca3e59e9)

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/55644019/aeda8a03-df0b-4f8e-9de2-2e0cff81a151)

**Comment by heejaechang** [comment]
this is a bug in textmate. not pylance language server.

**Comment by heejaechang** [comment]
it seems there is not much we can do here.

**Comment by heejaechang** [comment]
closing it but made it sub item of bigger work (shipping textmate grammar ourselves - https://github.com/microsoft/pyrx/issues/4026)
