### ISSUE TITLE
IntelliSense has a half-second delay

### ISSUE THREAD

**Issue by isinvon** [microsoft/pylance-release#4669]
Type: <b>Bug</b>

Using Pylance Extended IntelliSense has a half-second delay, which affects the experience.

Extension version: 2023.7.40
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (3.49GB free)|
|Process Argv|--crash-reporter-id 2123c431-83b9-47c8-b7dc-2d65961922ff|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by bschnurr** [comment]
can you provide a code example?

**Comment by isinvon** [comment]
When I use Jedi, the prompt panel will be displayed immediately after typing the first letter, and then the prompt panel will appear to follow up with zero delay when I continue typing. But when using Pylance, it feels half a beat slower

https://github.com/microsoft/pylance-release/assets/123001648/70fb66b2-943b-4725-91a6-c24c51596ab6

**Comment by debonte** [comment]
@isinvon, to investigate this we would need to be able to reproduce the behavior. Can you provide access to source code in a repo that reproduces this issue?
