### ISSUE TITLE
conint (false?) flagged as a problem in PROBLEMS tab

### ISSUE THREAD

**Issue by thomasheadrapson** [microsoft/pylance-release#4675]
<h3> Environment data </h3>

-   Language Server version: 2023.7.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): Anaconda
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

class Rating(BaseModel):
    """
    new_rating by userid from a movieid

    """
    ratingid: Optional[int] = None
    userid: int
    movieid: int
    rating: conint(ge=0,le=5)

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

conint recognised and correctly assessed

XXX

<h3> Actual behavior </h3>

Flagged as problem in PROBLEMS tab with message
"
Call expression not allowed in type expression Pylance(reportGeneralTypeIssues)
"
and "conint(ge=0,le=5)" as shown in code snippet is underlined in red.

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by erictraut** [comment]
You're using a call expression (`conint(ge=0, le=5)`) within a type annotation, which isn't permitted in the Python static type system.

If you provide more context about what you're attempting to do, we may be able to give you some additional tips.

**Comment by thomasheadrapson** [comment]
Hi, and thanks for the quick reply.

Constar, in the same code snippet, doesn't have this problem, but uses a
similar syntax.

I'm trying to restrict an integer attribute in a class definition.

All the example I've seen online use the syntax I have, as far as I can
tell

Cheers

Tom


Thomas Head-Rapson

+33 (0)6 52 78 73 12

**Comment by thomasheadrapson** [comment]
Correction, in the same file, not code snippet, but for a different class

Tom


Thomas Head-Rapson

+33 (0)6 52 78 73 12

**Comment by erictraut** [comment]
That example is invalid. Call expression forms are not allowed in type expressions (annotations).

**Comment by erictraut** [comment]
The purpose of static type checking is to help you find bugs ahead of time and to write robust code that will not break over time as you update libraries, refactor your code, etc. If you find that static type checking is not sufficiently beneficial, you have the option of disabling it (by setting `python.analysis.typeCheckingMode` to "off"). It's entirely optional in Python. If you find that static type checking is useful, then you need to use the static type system properly. That means, among other things, that type annotations must conform to expression types that are allowed by static type checkers. It's completely up to you.

**Comment by sebastianvitterso** [comment]
I realize that, but I believe the point of functions as types (such as `conint`, `constr`, `confloat` in Pydantic) is to simplify the combination of static type checking (to statically check that you're passing an int) and constraint validation (to dynamically check that the int is `ge=0` and `le=5`). 

Although these validation operations are wildly different in operation, they conceptually check similar things, and therefore  it makes sense (and is quite ergonomic) to a developer to have them in the same place.

---

And as a slight "FYI", the [definition of the `conint`](https://github.com/pydantic/pydantic/blob/main/pydantic/types.py#L137-L164) function is as follows: 

```python

def conint(
    *,
    strict: bool | None = None,
    gt: int | None = None,
    ge: int | None = None,
    lt: int | None = None,
    le: int | None = None,
    multiple_of: int | None = None,
) -> type[int]:
    """A wrapper around `int` that allows for additional constraints.

    Args:
        strict: Whether to validate the integer in strict mode. Defaults to `None`.
        gt: The value must be greater than this.
        ge: The value must be greater than or equal to this.
        lt: The value must be less than this.
        le: The value must be less than or equal to this.
        multiple_of: The value must be a multiple of this.

    Returns:
        The wrapped integer type.
    """
    return Annotated[  # type: ignore[return-value]
        int,
        Strict(strict) if strict is not None else None,
        annotated_types.Interval(gt=gt, ge=ge, lt=lt, le=le),
        annotated_types.MultipleOf(multiple_of) if multiple_of is not None else None,
    ]
```

My argument with this is that it returns a simple type expression, so why can't a call to a function that returns a type expression be used as a type expression?

I realize that I might have to raise this question on the Pyright repository instead, but I feel like the restriction of just saying "you can't have function calls there" seems a bit arbitrary.

**Comment by erictraut** [comment]
I'm the primary author of pyright, so there's no need to raise the question in the pyright repo. You'll get the same answer there. The restriction on call expressions isn't specific to pyright. It's something that none of the Python type checkers (including mypy, pyre, and pytype) allow. Type expressions need to be fast to evaluate and non-ambiguous. Call expressions are slow to evaluate and can evaluate differently based on subtle differences between type checkers. PEP 484, which introduced the fundamental aspects of static typing to Python, indicates that "Annotations should be kept simple or static analysis tools may not be able to interpret the values." This statement is somewhat ambiguous, but the specifics were later clarified and agreed upon by all of the type checker maintainers. Call expressions are not allowed in type expressions. Like I said, if you don't want to use static type checking, you can disable it. If you want to use static type checking, you need to abide by its rules.
