### ISSUE TITLE
reportUnboundVariable when using assignment expression and logical short circuiting 

### ISSUE THREAD

**Issue by BeatButton** [microsoft/pylance-release#468]
## Environment data

-   Language Server version: v2020.9.8
-   OS and version: Arch Linux
-   Python version: 3.9.0

## Expected behaviour

A name hould not be reported as unbound when using the assignment expression in conjunction with logical short circuiting.
This is similar to #381 

## Actual behaviour

The name is reported as possibly unbound.

## Code Snippet / Additional information

```python
if x := 0 or 1:
    print(x)
```

![image](https://user-images.githubusercontent.com/10457847/95369491-baf91480-0894-11eb-9dd6-0eb5f8ebaa25.png)
![image](https://user-images.githubusercontent.com/10457847/95369507-c0565f00-0894-11eb-8d33-24ee1096a5e3.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release of Pylance.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020101-14-october-2020
