### ISSUE TITLE
Rename of type alias defined with PEP 695 fails

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#4696]
PEP 695 (introduced in Python 3.12) introduces a new `type` statement to define type aliases. If you use the language server "rename" feature to attempt to rename the type alias, it fails with an error message:

![Screenshot 2023-08-07 at 2 57 27 PM](https://github.com/microsoft/pylance-release/assets/7040122/6ce29292-ed49-4b4b-bc62-2ea63b2fbb57)

To repro:
1. Install the latest Python 3.12 rc1. Alternatively, set the pylance/pyright "pythonVersion" to "3.12".
2. Create a new file with the following contents.

```python
type TA1 = int

x: TA1 = 1
```

3. Position the mouse cursor over either instance of `TA1` and run the "Rename Symbol" command.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.9.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023911-6-September-2023-PreRelease)
