### ISSUE TITLE
Use of cmp builtin function results in "is not defined" warning

### ISSUE THREAD

**Issue by rtkapiper** [microsoft/pylance-release#47]
Using the `cmp` builtin function results in a "not defined" warning:

## Environment data
-   Language Server version: Pylance language server 2020.6.1
-   OS and version: Mac OS Catalina 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): 2.7.18 and 3.8.2

Python is running in a virtualenv, but no extra modules are imported or used

## Expected behaviour

No warning is generated

## Actual behaviour

The following warning is shown

`"cmp" is not defined Pylance (reportUndefinedVariable)`

## Logs

```
Info  - 8:42:51 AM] Pylance language server 2020.6.1 starting
[Info  - 8:42:51 AM] Server root directory: /Users/andy.piper/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 8:42:51 AM] Background analysis root directory: /Users/andy.piper/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 8:42:51 AM] Background analysis started
[Info  - 8:42:51 AM] No configuration file found.
[Info  - 8:42:51 AM] Setting pythonPath for service "apiper": "/opt/local/bin/python3.8"
[Info  - 8:42:51 AM] stubPath /Users/andy.piper/awn/users/apiper/typings is not a valid directory.
[Info  - 8:42:51 AM] Assuming Python version 3.8
[Info  - 8:42:51 AM] Assuming Python platform Darwin
[Info  - 8:42:51 AM] Searching for source files
[Info  - 8:42:51 AM] Found 3 source files
[FG] parsing: /Users/andy.piper/Downloads/foo.py (18ms)
[FG] parsing: /Users/andy.piper/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (300ms)
[FG] binding: /Users/andy.piper/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (119ms)
[FG] binding: /Users/andy.piper/Downloads/foo.py (0ms)
[BG] analyzing: /Users/andy.piper/Downloads/foo.py ...
[BG]   parsing: /Users/andy.piper/Downloads/foo.py (91ms)
[BG]   parsing: /Users/andy.piper/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (291ms)
[BG]   binding: /Users/andy.piper/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server/typeshed-fallback/stdlib/2and3/builtins.pyi (117ms)
[BG]   binding: /Users/andy.piper/Downloads/foo.py (1ms)
[BG]   checking: /Users/andy.piper/Downloads/foo.py (8ms)
[BG] analyzing: /Users/andy.piper/Downloads/foo.py (509ms)
```

## Code Snippet / Additional information

Can be reproduced with a 1-line file:

```python
z = cmp(1, 2)
```

**Comment by erictraut** [comment]
The `cmp` function exists only in Python 2. It was deprecated in Python 3. 

Pylance works only with Python 3. If you want language support for Python 2, you can use the JEDI language server.

**Comment by rtkapiper** [comment]
Thanks for the prompt reply!

This makes sense considering that Python 2 has reached EOL, but I didn't come across anything that stated Python 2 wasn't supported by Pylance. Maybe adding this to the docs and/or the description in the VS Code marketplace would prevent others from filing similar bugs in the future?

**Comment by erictraut** [comment]
Yes, that's a good suggestion. [Someone else also suggested that](https://github.com/microsoft/pylance-release/issues/7), and the README has since been updated to mention that Python 2 is not supported.
