### ISSUE TITLE
Pylance import resolve messages should be pushed to Pyright

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4701]
To make Pyright and Pylance be more consistent, we should make the import resolve errors that we're remapping to change the message for Pyright too.

The 'environment name' could default to the Python path for pyright, but for pylance, when it has the information, can get it from the Python core extension.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.8.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023851-30-August-2023-PreRelease)
