### ISSUE TITLE
pylance say `fits` is a variable

### ISSUE THREAD

**Issue by Firestar-Reimu** [microsoft/pylance-release#4710]
![image](https://github.com/microsoft/pylance-release/assets/65082432/1bd59a8c-523d-4428-bdce-f8fcc0c52d53)

The truth is:

```
from astropy.io import fits
```

and the code run with no error (and should be no warning) which means I imported `fits` and it used `fits`

**Comment by debonte** [comment]
Can you provide a complete code sample that reproduces this issue? I tried the following with `astropy` 5.3.1 and don't see any diagnostics:

```python
from astropy.io import fits

x = fits.open("")
```

**Comment by Firestar-Reimu** [comment]
I run it in a jupyter notebook https://paste.c-net.org/RegalScent which `fits` warning happen at the last code block.

**Comment by debonte** [comment]
Thanks for the notebook. I'm not seeing an error on the `fits.open` call though. What version of Pylance are you using?

![image](https://github.com/microsoft/pylance-release/assets/12820898/354a9ea2-ca0c-4277-b565-8a55a80a0680)

**Comment by Firestar-Reimu** [comment]
v2023.8.20

**Comment by debonte** [comment]
Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
