### ISSUE TITLE
How to set the language of the warning displayed by pylance

### ISSUE THREAD

**Issue by MikuAndRabbit** [microsoft/pylance-release#4715]
# Environment 

* OS: MacOS 13.4.1 
* VS Code: 1.81.1
* Pylance: v2023.8.20

# Question

&emsp;&emsp;Recently, when I was programming with vscode, I found that Pylance's warnings and the like have changed to Chinese, but the display language of my vscode is English, and I have not made any other settings.
&emsp;&emsp;I would like to know how to set the language of the warnings displayed by pylance?

**Comment by Hudrolax** [comment]
You should switch language for VSCode in MacOS. In the system language setting you can choose a specific language for the specified application. It helps me to solve the same problem.

**Comment by MikuAndRabbit** [comment]
> You should switch language for VSCode in MacOS. In the system language setting you can choose a specific language for the specified application. It helps me to solve the same problem.

Thanks a lot, this solved my problem.
