### ISSUE TITLE
Unable to code

### ISSUE THREAD

**Issue by thunderfan9** [microsoft/pylance-release#4717]
Type: <b>Bug</b>

Pylance is causing problems with the code and leading to an unknown command: shellen to pop up every time a new terminal is opened.

Extension version: 2023.8.20
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 1a800591-b926-48b8-98f6-6d2babf99626|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by debonte** [comment]
Can you elaborate on what you mean by "causing problems with the code"?

Also, can you provide a screenshot of the popup message that you're seeing?

**Comment by thunderfan9** [comment]
<img width="395" alt="Screenshot 2023-08-14 at 12 59 36 PM" src="https://github.com/microsoft/pylance-release/assets/134335704/fd1ad5c7-379b-4aae-a007-42b16785fa5a">

**Comment by bschnurr** [comment]
if you change your language server to jedi does it still happen?

**Comment by thunderfan9** [comment]
How do I do that?

**Comment by bschnurr** [comment]
Settings > Extensions > Python, head down to Language Server and change Default to Jedi

**Comment by thunderfan9** [comment]
It does not give me that option where is the language server?

**Comment by bschnurr** [comment]
![image](https://github.com/microsoft/pylance-release/assets/1946977/fde9a4b0-db41-46af-a201-1773279f5317)

**Comment by thunderfan9** [comment]
<img width="990" alt="Screenshot 2023-08-14 at 1 22 44 PM" src="https://github.com/microsoft/pylance-release/assets/134335704/0f96a95e-75fa-4a5e-a7f1-6e902a9e25f3">

**Comment by thunderfan9** [comment]
I am not sure where you saw that on your app.

**Comment by bschnurr** [comment]
bottom left corner. 
![image](https://github.com/microsoft/pylance-release/assets/1946977/1bf187b4-dbc5-4ac9-ba91-6246fa344f8b)

**Comment by thunderfan9** [comment]
It still gives me the error.

**Comment by thunderfan9** [comment]
whenever I open a new terminal

**Comment by bschnurr** [comment]
then. its most likely a different extension. it could be the 'python' extension. i'd try disabling them one by one

**Comment by thunderfan9** [comment]
It did not fix it the extension disabling but the default language is still on Jedi not sure if that would affect it

**Comment by debonte** [comment]
Can you share the contents of your user `settings.json`? You can get there via the `Preferences: Open User Settings (JSON)` command in the command palette (Cmd+Shift+P on Mac). I'm curious to see if there are any Terminal-related settings in there.

If not, given that the issue still happens with the Python and Pylance extensions disabled, I think we'll want to transfer this issue to the vscode repo so the devs that work on the Terminal can help you.

**Comment by debonte** [comment]
Closing because this issue needs more information and has not had recent activity. If the issue still persists, please reopen with the information requested. Thanks.
