### ISSUE TITLE
VS Code fails to highlight syntax properly if type of return value provided

### ISSUE THREAD

**Issue by cx0222** [microsoft/pylance-release#4718]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.81.0 (Universal)
- OS Version: macOS 13.4.1 (c), BuildVersion: 22F770820d

Steps to Reproduce: 
1. Select the color scheme "Github Dark";
2. Create a Python file and write a function with a type hint which indicates the type of the return value; e.g. 
```python
# Xuan Chen - Aug 4, 2023

def get_list(some_val: int, other_val: int) -> list[int]:
    return [some_val, other_val]

if __name__ == "__main__":
    # The color of "if" is black, which should be red in this color scheme
    # The color of "__main__" is also black, which should be dark blue in this color scheme
    print(get_list(2023, 8))
```
3. I found that some of the lines under the function appear in improper colors.
Note: This problem occurs no matter which color scheme I select.
![pic1](https://github.com/microsoft/vscode/assets/77929197/63612cb6-2dac-4137-ad50-9d02728509b5)
![pic2](https://github.com/microsoft/vscode/assets/77929197/eaf67fa1-1523-4666-a0c0-955eb51a8ad0)
![pic3](https://github.com/microsoft/vscode/assets/77929197/bc669b73-c158-44e3-a358-f0a94f217394)

**Comment by Aegis1863** [comment]
Just a supplementary question, whether pylance also fails and keeps showing loading? i got such problem.

**Comment by debonte** [comment]
I'm not seeing this on our latest prerelease build (2024.2.105). I'm closing this under the assumption that it is fixed. If you are still seeing this behavior, please reopen -- we'll need additional details on how to repro this.

![image](https://github.com/microsoft/pylance-release/assets/12820898/ce73be4b-1c1f-4306-a06f-e3aff6698765)
