### ISSUE TITLE
Action and option to declutter type hints

### ISSUE THREAD

**Issue by rik** [microsoft/pylance-release#4721]
As useful as type hints can be, they can sometimes be visually overwhelming. Just like imports, it would be nice to hide them sometimes.

- Action to show/hide type hints.
- Option to decide if they should be shown/hidden when first opening a file.

[PyCharm shipped a similar feature in 2023.2](https://www.jetbrains.com/pycharm/whatsnew/#:~:text=Option%20to%20collapse%20Python%20type%20annotations).

**Comment by debonte** [comment]
Moving this issue to discussion as an enhancement request for comments and upvotes.
