### ISSUE TITLE
Programmatic Access to Extract Type Information

### ISSUE THREAD

**Issue by nashid** [microsoft/pylance-release#4726]
I'm working on a project where I need to programmatically analyze a Python codebase and extract type information for specific variables. I've been using Pylance in VS Code and I'm interested in leveraging Pylance (or the underlying Pyright) for this task.

**Objective:**
I would like to programmatically use Pylance or Pyright to analyze Python code and retrieve type information for specific variables.

**Approaches Considered:**
**Language Server Protocol (LSP):** I understand that Pylance operates as a language server using the LSP. I've considered setting up an LSP client, starting the Pylance language server, and then sending LSP requests to get type information. However, I'm unsure about the specifics and feasibility of this approach.

**Using Pyright Directly:** Since Pyright is the core type-checker behind Pylance, I am wondering if there is a way to use it directly as a library to analyze Python code and extract type information.

**Questions:**

- Is there a recommended way to achieve programmatic type extraction using Pylance/Pyright?
- Are there any internal APIs or tools within Pyright that could be leveraged for this purpose?

Thank you for your time and for the fantastic work on Pylance and Pyright!

**Comment by rchiodo** [comment]
What type information are you interested in? Pyright and Pylance both use LSP. That's the current limit to their extensibility. They don't have any other API to query type information. 

However, LSP does give a lot of information about what's under the cursor. I guess it depends upon what information you're looking for.

**Comment by rchiodo** [comment]
Ah I see Eric responded to the same request in Pyright:
https://github.com/microsoft/pyright/issues/5734
