### ISSUE TITLE
Import suggestion should suggest collections.abc instead of typing for container types

### ISSUE THREAD

**Issue by Kuba314** [microsoft/pylance-release#4738]
Container types (e.g. `Iterable`, `Collection`, ...) in the `typing` module are deprecated since python 3.9 (see [PEP 585](https://peps.python.org/pep-0585/)). These symbols should be getting imported from `collections.abc` instead, but the python extension keeps suggesting importing them from the `typing` module.

**Comment by rchiodo** [comment]
Thanks for the suggestion. I suppose the downside is that these container types may eventually be removed from typing.

**Comment by erictraut** [comment]
It's unlikely these container types will ever be removed from typing. There's no significant upside to removing them (since they're just re-exports), and the downside would be huge because it would impact so much existing code.

**Comment by Kuba314** [comment]
Let me know if I could help you in any way. But I assume this issue happens to everyone, because I don't think I use any non-standard configuration other than being switched to a venv created by poetry.

**Comment by flying-sheep** [comment]
> It's unlikely these container types will ever be removed from typing. There's no significant upside to removing them (since they're just re-exports), and the downside would be huge because it would impact so much existing code.

Where do you take this from? Core development guidelines or personal feelings about it? Because I don’t think everyone feels that way, so if there’s nothing confirming this, I doubt it’s the case.

**Comment by Tinche** [comment]
I was just about to report this issue. I'm using Ruff in almost all of my projects, and Ruff has a [rule to flag importing deprecated symbols from typing](https://docs.astral.sh/ruff/rules/deprecated-import/).

So now using the import quick fix is a two step operation, have VS Code generate the import, and then have Ruff fix it. ;)

**Comment by Kuba314** [comment]
I'm on `2023.12.1` and I'm now getting both `typing` and `collections.abc` imports. I'm fine with there being both, so from my point of view this issue is now resolved.
![screenshot_20231215_205354](https://github.com/microsoft/pylance-release/assets/35199722/1587fc8f-18cb-4c5f-b321-f2249c1eda29)
