### ISSUE TITLE
Failed to find some existing functions

### ISSUE THREAD

**Issue by Kidsunbo** [microsoft/pylance-release#4739]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Expected VSCode could navigate to the function definition. But actually it failed to do that and it doesn't report anything either. Just render function references to white.

## Steps to reproduce:

1. I find this bug when I read the code of `Django`. So git clone `django` to some folder.
2. Open it using VSCode with Python and Pylance extension installed.
3. The wierd thing is that some functions in the same module could be found but some are not. 
![image](https://github.com/microsoft/vscode-python/assets/12459780/f24e231c-981c-4068-8adb-5d328a4e75f9)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.14.0
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin x64 22.5.0
Modes:
Remote OS version: Linux x64 5.15.49-linuxkit-pr
Remote OS version: Linux x64 5.15.49-linuxkit-pr

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 8, 6|
|Memory (System)|32.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 42793901-d4a5-495c-b8ba-f5d48a2bbefc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container ubuntu (kie) @ desktop-linux|
|OS|Linux x64 5.15.49-linuxkit-pr|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (8 x 2600)|
|Memory (System)|15.64GB (12.11GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container ubuntu (kie) @ desktop-linux|
|OS|Linux x64 5.15.49-linuxkit-pr|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (8 x 2600)|
|Memory (System)|15.64GB (12.11GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30815622
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by bschnurr** [comment]
My guess is that the django stubs we ship with are missing those classes.. i'll take a look.

**Comment by bschnurr** [comment]
remove the stub folder or rename it should disable them. ie 'C:\Users\(username)\.vscode\extensions\ms-python.vscode-pylance-2023.8.31\dist\bundled\stubs\django-stubs'

**Comment by bschnurr** [comment]
please log an issue on https://github.com/sbdchd/django-types
