### ISSUE TITLE
Pylance is not working properly with some pip packages

### ISSUE THREAD

**Issue by Eric-Arz** [microsoft/pylance-release#474]
I recently tried to transition over to pylance from the Microsoft Python Language Server. Sadly lots of packages i use regularly don't seem to fully work with pylance. 

Pylance usually only works on the import and top level stuff. But when it comes to submodules it stops working.

One example would be the pyglet library:

```
import pyglet

pyglet.window.
```

Result with pylance:

![pylance](https://user-images.githubusercontent.com/42436462/95679073-c8820780-0bd0-11eb-85e8-9eab54f0210d.png)

Result with microsoft python language server:

![server](https://user-images.githubusercontent.com/42436462/95679119-febf8700-0bd0-11eb-8a5e-92fbc1bafcbd.png)

From what i understand pylance is supposed to be the successor to the language server and people should move over to it. But as it is now it does a strictly worse job at providing code completion. 

I am getting the same results on different computers with different python versions (tested 3.7, 3.8, 3.9) and operating systems (tested Windows 10 + Linux)

**Comment by erictraut** [comment]
Thanks for reporting the issue, and please file issues for other libraries that are not working as well with Pylance.

In the case of pyglet, I'm not sure how the latest version would work with any static analysis tool. If you look in the implementation of pyglet, you'll see that it is dynamically and lazily loading all of its submodules in a way that obscures their content from any attempt to statically analyze their contents. There's one simple change that would allow pyglet to work with pylance (and other tools). I recommend that you submit a PR or file a bug to the pyglet maintainers.

Here's the current code in `pyglet/__init__.py`:

```python
if True:
    app = _ModuleProxy("app")
    ...

if False:
    from . import app
    ...
```

If you change this to the following, it will retain its lazy loading but also work fine with Pylance:

```python
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
    app = _ModuleProxy("app")
    ...

if TYPE_CHECKING:
    from . import app
    ...
```

**Comment by erictraut** [comment]
With that change, here's the Pylance completion behavior.

![Screen Shot 2020-10-11 at 8 15 50 AM](https://user-images.githubusercontent.com/7040122/95682421-fbf56f80-0b99-11eb-9fb8-7fa67d656ab1.png)

**Comment by Eric-Arz** [comment]
I suggested the change to the pyglet maintainers. Since this issue seems to be on their end im closing this.
