### ISSUE TITLE
"Import 'environs' could not be resolved"

### ISSUE THREAD

**Issue by StephanieAG** [microsoft/pylance-release#4744]
<h3> Environment data </h3>

-   Language Server version: 2023.8.30
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

I used the Pylance: Report Issue command to get the above. I'm a new coder, so I'm really not sure about this, but I feel like the below info might be what should've been included(?)
-   OS and version: macOS Big Sur V 11.7.7
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.4 (I'm not sure what distribution is so I'm assuming I don't have it)

<h3> Code Snippet / etc. </h3>
Please see this forum post from April 2023 onward for details: 
https://forum.djangoproject.com/t/environ-import-is-not-recognized/8119/6

**Comment by StellaHuang95** [comment]
Thanks for the issue. Can you include a log as described here?
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
