### ISSUE TITLE
Crash related to `JinjaParser` -- setIncompleteSubtype can be called only on a valid incomplete cache entry

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4745]
Error: Debug Failure. setIncompleteSubtype can be called only on a valid incomplete cache entry: prev cache entry?: false index=0 isPending=falseevaluationCount=1</br>at None <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L275'>pyright-internal/src/analyzer/codeFlowEngine.ts:275:28</a></br>    at _isParsingTypeAnnotation <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pylance-internal/src/jinja/jinjaParser.ts#L2747'>pylance-internal/src/jinja/jinjaParser.ts:2747:21</a></br>at func (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L876'>pyright-internal/src/analyzer/codeFlowEngine.ts:876:41</a></br>at getTypeFromLoopFlowNode <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L592'>pyright-internal/src/analyzer/codeFlowEngine.ts:592:31</a></br>at getTypeFromFlowNode <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1086'>pyright-internal/src/analyzer/codeFlowEngine.ts:1086:19</a></br>at getTypeFromCodeFlow <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18749'>pyright-internal/src/analyzer/typeEvaluator.ts:18749:24</a></br>    at node <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L977'>pyright-internal/src/analyzer/typeEvaluator.ts:977:43</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L982'>pyright-internal/src/analyzer/typeEvaluator.ts:982:51</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1455'>pyright-internal/src/analyzer/codeFlowEngine.ts:1455:45</a></br>at isCallNoReturn <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L434'>pyright-internal/src/analyzer/codeFlowEngine.ts:434:66</a></br>at getTypeFromFlowNode <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1086'>pyright-internal/src/analyzer/codeFlowEngine.ts:1086:19</a></br>at getTypeFromCodeFlow <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L18749'>pyright-internal/src/analyzer/typeEvaluator.ts:18749:24</a></br>    at node <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L977'>pyright-internal/src/analyzer/typeEvaluator.ts:977:43</a></br>    at node <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L982'>pyright-internal/src/analyzer/typeEvaluator.ts:982:51</a></br>    at node <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L987'>pyright-internal/src/analyzer/typeEvaluator.ts:987:44</a></br>at node <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/typeEvaluator.ts#L982'>pyright-internal/src/analyzer/typeEvaluator.ts:982:51</a></br>at callback <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/common/timing.ts#L40'>pyright-internal/src/common/timing.ts:40:19</a></br>at getTypeOfExpression <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1455'>pyright-internal/src/analyzer/codeFlowEngine.ts:1455:45</a></br>at isCallNoReturn <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L434'>pyright-internal/src/analyzer/codeFlowEngine.ts:434:66</a></br>    at _parseTestListAsExpression <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pylance-internal/src/jinja/jinjaParser.ts#L2735'>pylance-internal/src/jinja/jinjaParser.ts:2735:40</a></br>at func (<anonymous>)</br>at forEach <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L876'>pyright-internal/src/analyzer/codeFlowEngine.ts:876:41</a></br>at getTypeFromLoopFlowNode <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L592'>pyright-internal/src/analyzer/codeFlowEngine.ts:592:31</a></br>at getTypeFromFlowNode <a href='https://github.com/microsoft/pyrx/blob/b193146576028b2a8dfafd487ba23d6af00df6f1/packages/pyright/packages/pyright-internal/src/analyzer/codeFlowEngine.ts#L1086'>pyright-internal/src/analyzer/codeFlowEngine.ts:1086:19</a></br>

**Comment by erictraut** [comment]
This looks like the bug that I fixed in pyright 1.1.323, so it should be fixed in last week's pre-release version of pylance.

**Comment by debonte** [comment]
Thanks, you're right.
