### ISSUE TITLE
Third-party libraries cannot use docstring

### ISSUE THREAD

**Issue by zaaronbin** [microsoft/pylance-release#4748]
pycharm can use 'ctrl+q' to display the docstrings, but the vscode with pylance just display the function name

![image](https://github.com/microsoft/pylance-release/assets/52147833/940c4cf0-1daf-4ba0-8c6b-e4d821b5e50b)

![image](https://github.com/microsoft/pylance-release/assets/52147833/06a7ce02-66ea-44de-96da-1ab2822755de)

**Comment by heejaechang** [comment]
this is because `PyQt5.QtWidgets` is compiled module and `QtWidgets.pyi` shipped along side with `QtWidgets.pyd` doesn't contain `doc string`

**Comment by zaaronbin** [comment]
Thanks for your answer
