### ISSUE TITLE
Python keywords, type names, etc should not be localized

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4749]
In a [recent loc update](https://github.com/microsoft/pyrx/pull/4017), the Spanish translation translated the word `Concatenate` which is the name of a special form. Just like `ParamSpec`, `Concatenate` should never be translated.

English: "concatenateParamSpecMissing": "Last type argument for \"Concatenate\" must be a ParamSpec or \"...\"",
Spanish: "concatenateParamSpecMissing": "El último argumento de tipo para \"Concatenatar\" debe ser un ParamSpec o \"...\"",

**Comment by debonte** [comment]
@bschnurr, I see that you added the "waiting for upstream" label back in September. Was a bug filed against the loc team about this? The latest `pyright-internal/src/localization/package.nls.es.json` [still has this issue](https://github.com/microsoft/pyrx/blob/release/2024.3/packages/pyright/packages/pyright-internal/src/localization/package.nls.es.json#L88-L90).

**Comment by cwebster-99** [comment]
@debonte Is this related to the work you have been doing recently?

**Comment by debonte** [comment]
Closing as a duplicate of https://github.com/microsoft/pylance-release/issues/6035. I have a pending PR to resolve this.
