### ISSUE TITLE
 Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by MuhammmadS** [microsoft/pylance-release#4755]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by debonte** [comment]
Duplicate of #4756
