### ISSUE TITLE
cannot ceate a consistent method resolution

### ISSUE THREAD

**Issue by MuhammmadS** [microsoft/pylance-release#4756]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
class Employee:
    company = "visa"

class Freelancer(Employee):
    company = "Fiverr"

class Programmer(Employee , Freelancer):
    name = "rohit"
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
```

**Comment by erictraut** [comment]
Pylance is telling you that your code contains a bug. Try running the code in the sample above, and you'll receive an error from the Python interpreter. 

```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Employee, Freelancer
```

You can read more about this condition [here](https://stackoverflow.com/questions/29214888/typeerror-cannot-create-a-consistent-method-resolution-order-mro).
