### ISSUE TITLE
vscode extension Pylance did not detect installed lib 'label_studio_sdk'

### ISSUE THREAD

**Issue by stevezkw1998** [microsoft/pylance-release#4761]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

![image](https://github.com/microsoft/pylance-release/assets/53121066/124914ac-9277-4100-bdcd-f2f524b40721)
![image](https://github.com/microsoft/pylance-release/assets/53121066/ab506d18-ab0a-4233-9b10-652cbc0a7a95)
![image](https://github.com/microsoft/pylance-release/assets/53121066/15dc0f83-c6b7-4dac-9e44-cbeaf811aeb2)

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by debonte** [comment]
Thanks for the report. Would you please check if the correct virtual environment has been selected?

The way to do that would be to:
   * If you have not selected a virtual environment, the status bar will show your global python interpreter version. 
   * Click on version number and choose the correct environment from the command palette.
   * If there is no environment offered, you will need to create an environment and then select that as the default environment.

You can find more details on Python environments in VS Code [here](https://code.visualstudio.com/docs/python/environments).

**Comment by stevezkw1998** [comment]
Hi @debonte thank you for your suggestions, I adopted it, selecting a venv works for me
![image](https://github.com/microsoft/pylance-release/assets/53121066/8ee133f1-e7b1-4c5c-812f-6f4a573be279)
