### ISSUE TITLE
Auto indentation fails after comment lines

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#4763]
This issue has been reported in PTVS several times recently.
## Related PTVS issues:

- https://github.com/microsoft/PTVS/issues/7703
- https://github.com/microsoft/PTVS/issues/7649
## Environment data

-   Language Server version: 2023.8.40

## Code Snippet

```python
def func():
    # This is a comment
    print("hello")

```

## Repro Steps
In Visual Studio
1. Create a python file with code snippet above
2. Hit enter after `# This is a comment` and observe the auto-indent behavior

In VSCode
1. Create a python file with code snippet above
2. Set `editor.formatOnType` to `true`, and set `editor.autoIndent` to `none`
3. Hit enter after `# This is a comment` and observe the auto-indent behavior

## Expected behavior

Automatic indentation reaches the appropriate position.

## Actual behavior
![247748019-6a87c8cb-b9b8-49e9-8af2-851a235af8b0](https://github.com/microsoft/pylance-release/assets/100439259/efc71e5c-ee02-490e-8085-99039f36c366)

**Comment by StellaHuang95** [comment]
Separate this issue out from https://github.com/microsoft/pylance-release/issues/4456#issuecomment-1601631547

**Comment by debonte** [comment]
We'll leave this open until the fix ships.
