### ISSUE TITLE
Support `goto def` on https://github.com/microsoft/pylance-release/issues/4660 as well

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#4764]
this https://github.com/microsoft/pyrx/pull/4033 enables https://github.com/microsoft/pylance-release/issues/4660 

but it only works for completion. `go to def` doesn't work for now. we should support it since that is only one missing among editor features such as hover, checker, completion, signature help.

**Comment by heejaechang** [comment]
once we have `service provider` for `workspace/service/program` and once we move `extension.tryGetDefinition` to some kind of `definition provider service`

we can add `literal` in `__getattr__` as one of those `definition provider`, so things like `find all referece`, `highlight reference`, `rename` and `go to def` just work.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.9.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023911-6-September-2023-PreRelease)
