### ISSUE TITLE
Why does my codespace not let me write code

### ISSUE THREAD

**Issue by Clarasia** [microsoft/pylance-release#4766]
Whenever I try to write code it does not give an answer for example if I type "<<< Help = 'Help me' " it does not type Help me it just went to the next line.

**Comment by bschnurr** [comment]
Are you experiencing a delay on startup?

i'm not quite sure if this is a pylance issue.

can you provide the logs.  see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by bschnurr** [comment]
closing for now.. please reopen if you have a code example or image.
