### ISSUE TITLE
Bytes and bytearray stubs missing ctypes constructor overloads

### ISSUE THREAD

**Issue by ELFoglalt** [microsoft/pylance-release#477]
## Environment data

-   Language Server version: v2020.10.0
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.0

## Expected behaviour

`ctypes` objects can be used to instantiate `bytes` and `bytearray` objects via copying their buffer. The following code should not produce any static analysis errors:

```py
from ctypes import Structure, c_uint8, c_uint16

class A(Structure):
    _pack_ = 1
    _fields_ = [("foo", c_uint8), ("bar", c_uint16)]

print(bytearray(c_uint8(65)))  # bytearray(b'A')
print(bytes(A(65, 17218)))  # b'ABC'
```

## Actual behaviour

The code above runs just fine, but produces the following errors in the editor:
```py
print(bytearray(c_uint8(65)))
#     ~~~~~~~~~~~~~~~~~~~~~~
#     ^ No overloads for "bytearray(c_uint8(65))" match parameters
#       Argument types: (c_uint8)

print(bytes(A(65, 17218)))
#     ~~~~~~~~~~~~~~~~~~~~
#     ^ No overloads for "bytes(A(65, 17218))" match parameters
#       Argument types: (A)
```

## Code Snippet / Additional information

Possibly related: [python/typing issue](https://github.com/python/typing/issues/593) and [python bug report](https://bugs.python.org/issue27501). I don't fully expect this to be resolvable in a general sense, until the issues mentioned are resolved, but it would sure be nice to have constructor overloads in buffer-like objects for ctypes objects.

**Comment by jakebailey** [comment]
Like other type checkers, Pylance uses the stubs from typeshed, which it appears that those linked threads are covering changes to (or some other related typing change). There's not much we can do when they these types are defined to have a specific signature for their constructors.

For the specific lines if you know the invocations to be correct, you should be able to add `# type: ignore` to tell the type checker to suppress any messages, though.

**Comment by ELFoglalt** [comment]
My bad, this is clearly to be solved in the dependency then. I wrongfully attributed the .pyi definitions in question to be pylance related. I'll just use the ignore hint to get rid of the errors
