### ISSUE TITLE
Sementic Highlighting, linting in Jyptyer Notebook breaks on file saving

### ISSUE THREAD

**Issue by philosofool** [microsoft/pylance-release#4776]
## Environment data

-   Language Server version: v2023.08.40
-   OS and version: Ubuntu 20.04.6 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.10

## Code Snippet

The following can be added to the first cell of a notebook to complete steps below:
```python
def my_func():
    return 'yellow'
my_func()  # should be semantically highlighted to theme color for functions
undefined_name  # should display linting error (undefined name.)
```

## Repro Steps

1. In VSCode: File > New File > Jupyter Notebook File
2. Add a function, `my_func` which takes no arguments and returns an arbitrary value. (So far as I can tell, _any_ code should work at this step, as long as it can be used to verify semantic highlights.)
3. add a line that calls the function and verify that semantic highlighting is working as-expected.
4. add a line `undefined_name`, which should trigger linting highlights, since the name is not assigned to anything.
5. Ctrl + S to save the notebook. Add a name, I used "semantic_highlights.ipynb". I imagine the default "Untitle-1.ipynb" will work too.
6. Failure: semantic highlight is no longer working, linting errors (likely other language model features) are missing.

Alternative replication: (some attempts to generate the failure with this have not caused the issue.)
1. Open a notebook from any directory.
2. Verify that semantic highlighting and linting are correct in the notebook
3. From terminal `touch <path to notebook>` 
4. Same as 6 above.

## Expected behavior

Touching files from OS, Save as, etc. do not stop any Pylance features (semantic highlighting, linting, etc.) from running. Or, if necessary, Pylance restarts on the open notebook to implement features.

## Actual behavior

After `touch`ing a file, including OS processes that touch the file, semantic highlighting and linting (likely other Pylance language features) no longer work in open notebooks and the notebook must be closed and opened to start it again. 

For me, this is a pretty big issue since my team builds `.py` files from notebooks and the process touches the notebooks when this happens.

**Comment by rchiodo** [comment]
The log is from it reproducing? Cause it looks like the last thing it does is ask for the semantic token information (colors) for the untitled file.

Can you turn on trace logging and reproduce again?

```json
"python.analysis.logLevel": "Trace"
```

That should show more information. I still can't reproduce myself so something strange is going on.

**Comment by rchiodo** [comment]
Oh no wait, you already had trace logging enabled.

**Comment by rchiodo** [comment]
This might have been fixed recently. I can't seem to reproduce this with the 2023.8.41 version. Can you try with the prerelease version to see if you can still reproduce?

**Comment by philosofool** [comment]
> This might have been fixed recently. I can't seem to reproduce this with the 2023.8.41 version. Can you try with the prerelease version to see if you can still reproduce?

Yes! The issue does not appear in 2023.08.41. I also ran my team's notebook export process (which can touch dozens of files each run) and the language server seems to be stable after that. If I encounter any future issues, I will dig and try to find more specific conditions that replicate the issue. I think you can safely close this.

**Comment by rchiodo** [comment]
Thanks for verifying!
