### ISSUE TITLE
Make "add type annotation for pyTest arguments" to add `import` automatically as well.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#4779]
currently `add type annotation for pytest` doesn't insert `import` automatically

![image](https://github.com/microsoft/pylance-release/assets/1333179/d58bf51f-c48c-44f1-b0fd-7766fea7e13e)

make them to insert them as well.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.9.12, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023912-8-September-2023-PreRelease)
