### ISSUE TITLE
Diagnostics can suddenly disappear in a notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#4780]
Repro steps:
1. Open new notebook
2. Save file
3. Add an error to a cell
4. Add a bunch more cells
5. Delete cells until errors suddenly disappear

Editing a cell again will cause the errors to reappear.

Also note that hover and colorization still works, but that diagnostics seem to disappear. Meaning the server is still running it just seems the diagnostics have been removed.

**Comment by rchiodo** [comment]
My suspicion is that removing a cell has changed the workspace that we think the diagnostics belong to.

**Comment by rchiodo** [comment]
No this seems to have existed for a while. Went back to 8.31 and still repro'd.

Root cause is that the checker is running on all cells in the notebook when deleting and the checker's type evaluator is using a cached version of the cell and so doesn't emit another error.

The checker either doesn't need to run for cells above the deleted cell or we need to clear the type cache for all cells in the notebook.

**Comment by heejaechang** [comment]
we might need to set files dirty, not `importedBy` but `imports` as well? if change in a file can affect not just files that depends on it but it is depending?

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.9.11, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023911-6-September-2023-PreRelease)
