### ISSUE TITLE
Spurious undefined variable error in type alias

### ISSUE THREAD

**Issue by sliedes** [microsoft/pylance-release#4782]
<h3> Environment data </h3>

-   Language Server version: 2023.8.40
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10.7
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
from __future__ import annotations

import asyncio
from typing import TypeVar, Generic, TypeAlias

RequestT = TypeVar("RequestT")
ResponseT = TypeVar("ResponseT")


class WorkItem(Generic[RequestT, ResponseT]):
    AsyncFut = asyncio.Future[TypeAlias[WorkItem[RequestT, ResponseT]]]
```

<h3> Description </h3>

The above snippet causes pylance to emit undefined variable errors for WorkItem. This is something that mypy (at least version 1.5.1) accepts, and which, as far as I can tell, is correct. The exact error is `"WorkItem" is not defined`.

**Comment by sliedes** [comment]
Actually, I'm not sure this is valid after all. I somehow apparently managed to get it imported once (or at least I very much imagine so), but now I see errors when running it... So this may instead be a case of mypy underreporting things than pylance overreporting.

**Comment by erictraut** [comment]
If you run the above code, you'll see that the Python interpreter generates an exception "NameError: name 'WorkItem' is not defined". Pylance is telling you about this error, so it's not spurious.

I'll also point out that you're using `TypeAlias` incorrectly in your code. Refer to [PEP 613](https://peps.python.org/pep-0613/) for details on how to use `typing.TypeAlias`.

**Comment by erictraut** [comment]
I suspect that what you probably meant was the following:
```python
from __future__ import annotations

import asyncio
from typing import TypeVar, Generic, TypeAlias

RequestT = TypeVar("RequestT")
ResponseT = TypeVar("ResponseT")

AsyncFut: TypeAlias = "asyncio.Future[WorkItem[RequestT, ResponseT]]"

class WorkItem(Generic[RequestT, ResponseT]):
    ...
```

Note that `from __future__ import annotations` enables deferred evaluation of _type annotations only_. It doesn't defer evaluations of value expressions.

**Comment by sliedes** [comment]
Yes, you are correct (with the addition that I believe type aliases that refer to bound generic type variables are simply not supported by current type checkers). Thanks and sorry!
