### ISSUE TITLE
Type narrowing error while function return type is not marked as `NoReturn`

### ISSUE THREAD

**Issue by uf-fipper** [microsoft/pylance-release#4788]
## Environment data

-   Language Server version: 2023.8.41 (23 August 2023) PreRelease
-   OS and version: win11
-   Python version (& distribution if applicable, e.g. Anaconda): python3.9

## Code Snippet

```python
from typing import NoReturn, Optional

def raise_exc():
    raise Exception()

def get() -> Optional[int]:
    ...

def main():
    x = get()  # int | None
    if x is None:
        raise_exc()
    x.as_integer_ratio()  # pylance: "as_integer_ratio" is not a known member of "None"

main()
```

`raise_exc` is inferred as `NoReturn`, so according to type narrowing `x` in `x.as_integer_ratio()` should be inferred as `int`. But pylance consider it to be `int | None`.

But if I add return type obviously, pylance will provide the correct inference:

```python
from typing import NoReturn, Optional

def raise_exc() -> NoReturn:  # <---------------
    raise Exception()

def get() -> Optional[int]:
    ...

def main():
    x = get()  # int | None
    if x is None:
        raise_exc()
    x.as_integer_ratio()  # pylance work right

main()
```

**Comment by erictraut** [comment]
This is expected behavior. You need to include an explicit `NoReturn` return type annotation if you want pyright to assume a `NoReturn` behavior for purposes of code flow analysis. Return type inference will not be used in this case.

**Comment by uf-fipper** [comment]
thanks for your reply!
