### ISSUE TITLE
Always include file's dir in pylance search path.

### ISSUE THREAD

**Issue by T-256** [microsoft/pylance-release#4789]
1. Open empty folder in vscode
2. create folder `scripts`
3. create `scripts/a.py` with content of `x = 0`.
4. create `scripts/b.py` with below content:
```py
from a import x

# pylance autocomplete not working, try uncomment below and `ctrl+tab`
# a.
```

Here pylance cannot recognize type of `x` in `b.py`, but `python scripts/b.py` runs with no problem!

I have lot of workspaces similar to this situation, so it's hard to set `python.analysis.extraPaths` per workspace.
It's useful when `launch` configuration set `"cwd": "${fileDirname}"`.

What I need here is an option to auto include directory of these files in analyze search path:
`python.analysis.fileDirAnalyze`
Value can be boolean or list of glob patterns.

**Comment by T-256** [comment]
Current ugly solution to force pylance to analyze file is adding `.` to import statement.
Example:

`from .a import x`
do your work then remove `.`, if you forgot to remove it, python raises:
```
ImportError: attempted relative import with no known parent package
```

**Comment by rchiodo** [comment]
What's your version of Pylance? This works for me no matter what the subfolders are called:

![image](https://github.com/microsoft/pylance-release/assets/19672699/851a0d42-732a-4865-a5c5-d4878861374d)

But assuming it didn't work, the alternative here is to just put this in your global settings.json:

```
   "python.analysis.extraPaths": ['scripts']
```

That lets me reference any file from the 'scripts' folder in any project.

**Comment by T-256** [comment]
> What's your version of Pylance? This works for me no matter what the subfolders are called:

Correct, I was not up to date.
I can confirm it works as expected in version 2023.8.51, Thanks!
