### ISSUE TITLE
type.Annotated (3.9.0) error - Unexpected token at end of expression

### ISSUE THREAD

**Issue by EdLipson5117** [microsoft/pylance-release#479]
Just started to play with python 3.9.0, and the attr package. I'm not sure if I have the correct syntax as I get the error messages. Program works.

`import pathlib as PP
from typing import Annotated as Ann

import attr

@attr.s
class GpxDist():
    """
     get the distances in the gpx files
    """
    gpxfilelist: Ann[list, "list of pathLib files, including paths",
                     [Ann[PP.Path, "PathLib file name with path"]]]
    gpxfilename: Ann[PP.Path, "PathLib file name with path"]
    stoppedsec: Ann[int, "number of seconds between points to be considered not moving"]\
        = attr.ib(default=90)

`
Is there a valid syntax?

**Comment by erictraut** [comment]
Thanks for reporting.

Normally, string literals within a type would be interpreted as forward references, but `Annotated` needs to be handled specially. I've addressed the problem, and the fix will be in the next version.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020101-14-october-2020
