### ISSUE TITLE
Hint typing break my code

### ISSUE THREAD

**Issue by Kiryonn** [microsoft/pylance-release#4790]
Here is relevant parts of my code.
If i declare `App` first, then hint typing `Cell` in `App` would break my code.
If i declare `Cell` first, then hint typing `App` in `Cell` would break my code.
```py
class App(tk.Tk):
	def __init__(self) -> None:
		...

	def highlight(self, widget: Cell) -> None:
		...

class Cell(tk.Frame):
	def __init__(self, master: App) -> None:
		super(Cell, self).__init__(master)
		self.parent: App = master
		...

	def on_click(self, event) -> None:
		self.parent.highlight(self)
```

**Comment by debonte** [comment]
Currently when you want to use a type name in an annotation before the type is declared you have two options:
1. In the annotation, wrap the type name in quotes:
```python
class App(tk.Tk):
    def highlight(self, widget: "Cell") -> None:   # Note quotes around Cell
        ...

class Cell(tk.Frame):
```

2. Add the following import: `from __future__ import annotations`. This approach can cause problems for libraries that want annotations to be types (ex. runtime type checkers, Pydantic). So if you care about those scenarios, use option 1.

[PEP 649](https://peps.python.org/pep-0649/) will fix the issues with option 2, but will only be supported starting in Python 3.13.
