### ISSUE TITLE
How to have only Python code in completion code 

### ISSUE THREAD

**Issue by Jacques2101** [microsoft/pylance-release#4796]
Hi I an a data science an I  would like to have only Python completion code and not the others code completion that is not useful from my point of view (cf pictures). 
How can I do that ? 

<img width="1680" alt="Capture d’écran 2023-09-05 à 14 44 02" src="https://github.com/microsoft/pylance-release/assets/49912455/f2b2303b-848f-4233-9792-4559819b8b12">
<img width="1680" alt="Capture d’écran 2023-09-05 à 14 45 10" src="https://github.com/microsoft/pylance-release/assets/49912455/9e84bc02-4c0e-4e06-a40f-2649a4f669a1">

Thx.

**Comment by debonte** [comment]
These completions are from the [auto-import feature](https://devblogs.microsoft.com/python/pylance-has-reached-stable/#auto-import-completions). They are possible matches that Pylance found within your environment whose modules are not yet imported in the current file. If you selected one of those completions it would insert both the identifier and the required import.

You can disable the auto-import feature by setting `python.analysis.autoImportCompletions` to `false`.
