### ISSUE TITLE
doesn't recognize unpack type

### ISSUE THREAD

**Issue by asukaminato0721** [microsoft/pylance-release#4797]
## Environment data

-   Language Server version: v2023.8.50
-   OS and version: linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5

## Code Snippet

```python
pow(*[int(x) for x in input().split()], 1000000007)
```

## Repro Steps

1. put the code in editor

## Expected behavior

it recognize the type int, int,...

## Actual behavior

```
No overloads for "pow" match the provided arguments
  Argument types: (list[int], Literal[1000000007])
```

## Logs

**Comment by heejaechang** [comment]
closing the issue. if you don't agree please reopen with more data.
