### ISSUE TITLE
Unexplained inconsistency between pylance and pyright

### ISSUE THREAD

**Issue by erictraut** [microsoft/pylance-release#4799]
[Issue 5889](https://github.com/microsoft/pyright/issues/5889) in pyright's issue tracker talks about a behavior that differs between pylance and pyright. The behavior (an error) seen in pyright is correct. I can't explain why pylance doesn't display the same error in this case. It does display the error if I enable strict mode, but this diagnostic rule should be enabled in basic type checking mode.

I've debugged this as far as I can with the pyright sources. I'll need someone from the pylance team to investigate further. 

Note that I just pulled an updated copy of the typeshed stubs into pyright. These stubs mask the problem, so you may need to roll back the stubs to make the inconsistency reappear.

**Comment by rchiodo** [comment]
I believe this is because the default for pylance is now 'off'. If I switch to 'basic' it shows the same error that Pyright does.

**Comment by rchiodo** [comment]
![image](https://github.com/microsoft/pylance-release/assets/19672699/f136fd6a-1a6d-4204-8c11-500132c4d0ac)

**Comment by erictraut** [comment]
Yep, that was it. I thought I had typeCheckingMode set to "basic" in my user settings, but I must have removed it at some point. Never mind.
