### ISSUE TITLE
Automatic collection of types while in the debugger (suggestion)

### ISSUE THREAD

**Issue by WillAvudim** [microsoft/pylance-release#480]
There are two major problems with Pylance's definition of types I've run into:
1. Missing types (numpy.uint32, numpy.uint16, etc)
2. Incomplete or misconfigured types (e.g. when XGBoost.save_raw() returns the model as "bytearray", Pylance reports that it is not compatible with the "bytes" type expected by base64.b64encode), while in practice it works perfectly fine.

Correcting and populating all these types require a lot of human efforts and does not scale.

Given that all type information is available during debugging session, would it be possible to somehow capture the types of all observed functions/members and run a diff against the known static types? The revealed differences could then be reviewed and incorporated into the known static map of types.

For the second type of problems, if an application passes a mismatched type and it works normally (no exception), or passes an accepted type and there is a type exception, it could serve as a signal to update the type definition.

Such type diffs/fixes could then be reviewed and submitted to you. If you get enough reports for a specific type/member, that might serve as a reliable signal that the update is probably a good idea.

I realize that this idea is very involved and might require more than you're probably committed to, so feel free to reject it outright.

**Comment by jakebailey** [comment]
> Given that all type information is available during debugging session, would it be possible to somehow capture the types of all observed functions/members and run a diff against the known static types? The revealed differences could then be reviewed and incorporated into the known static map of types.

I think you might be interested in the [MonkeyType](https://github.com/instagram/MonkeyType) project.

> Such type diffs/fixes could then be reviewed and submitted to you. If you get enough reports for a specific type/member, that might serve as a reliable signal that the update is probably a good idea.

In general, we don't provide the types, the libraries, typeshed, or the users do. We have a few bundled types that we did write ourselves (which we plan to get into a public place soon), but the bulk are not produced by us.

**Comment by WillAvudim** [comment]
Nice! I'm looking forward to the time when definitions can be edited by the general public. And, hopefully, MonkeyType will be up for the job, otherwise it's a lot of routine and many libraries evolve pretty fast.
