### ISSUE TITLE
Pylance says Mapping[str, Any] is incompatible with TypedDict when used with Callable

### ISSUE THREAD

**Issue by AGiantSquid** [microsoft/pylance-release#4803]
## Environment data

pylance v2023.8.50
wsl debian
python 3.9

## Code Snippet

```python
from typing import Callable, Mapping, Any

from typing_extensions import TypedDict


class TD(TypedDict):
    key: str


def specific(td: TD):
    """Function that expects a TypedDict."""
    return td


def generic(c: Callable[[Mapping[str, Any]], Any]):
    """First argument is function that expects a Mapping."""
    return c


generic(specific)
```

The `generic()` function accepts as an argument a function, and this function expects its first argument to be a generic mapping.
The snippet feeds the `specific` function that expects a TypedDict instead of the generic Mapping.

## Expected behavior

Since Mapping is the supertype of a TypedDict, I would expect this to work fine.

## Actual behavior

When the generic function is called and provided with a function that expects a specific TypedDict, Pylance complains that Mapping[str, Any] is incompatible with the TypedDict. 

Error:
```
Argument of type "(td: TD) -> TD" cannot be assigned to parameter "c" of type "(Mapping[str, Any]) -> Any" in function "generic"
  Type "(td: TD) -> TD" cannot be assigned to type "(Mapping[str, Any]) -> Any"
    Parameter 1: type "Mapping[str, Any]" cannot be assigned to type "TD"
      "Mapping[str, Any]" is incompatible with "TD"
```

**Comment by erictraut** [comment]
This behavior is correct. Not surprisingly, mypy generates the same error in this case.

The function `generic` is expecting to receive a callable that accepts any `Mapping[str, Any]` as the first argument, but the function `specific` will not accept any `Mapping[str, Any]`. It accepts only `TD` for its first parameter.

When determining type compatibility of callables, the types of the parameters are contravariant — that is, the type of the parameter in `specific` must be a supertype of the parameter in `generic`. The types in your code sample are reversed; the type `TD` is a subtype of `Mapping[str, Any]`, not a supertype.

**Comment by AGiantSquid** [comment]
I appreciate your quick response!

I'm still trying to wrap my head around this. Let's say I have a use case of creating a wrapper for different functions that have different TypedDict arguments:

```
from typing import Callable, Mapping, Any

from typing_extensions import TypedDict


class TD_1(TypedDict):
    key_1: str

class TD_2(TypedDict):
    key_2: str


def specific_1(td: TD_1):
    """Function that expects a TypedDict."""
    return td


def specific_2(td: TD_2):
    """Function that expects a different TypedDict."""
    return td


def wrapper(c: Callable[[Mapping[str, Any]], Any]):
    """First argument is function that expects a Mapping."""
    return c


wrapped_1 = wrapper(specific_1)
wrapped_2 = wrapper(specific_2)

```

So, `wrapper` should have a signature that allows it to accept any function that expects a TypedDict as an argument. I feel like the wrapper's signature should have the more generic supertypes, right?

**Comment by erictraut** [comment]
No, you have it backward still. I'll add a minimal implementation for `specific_1` and `wrapper` to demonstrate the problem.

```python
def specific_1(td: TD_1):
    print(td["key_1"])
    return td

def wrapper(c: Callable[[Mapping[str, Any]], Any]):
    c({"hi": 1})
    return c

wrapped_1 = wrapper(specific_1)
wrapped_1({"key_1": ""})
```

If you run this code, it will crash. That's because `wrapper` has called the callback `c` with a `Mapping[str, Any]` that is not a `TD_1`.

Here's how you can fix this in a way that doesn't violate any types.

```python
from typing import Callable, Mapping, Any, TypeVar, TypedDict

T = TypeVar("T", bound=Mapping[str, Any])

class TD(TypedDict):
    key: str

def specific(td: TD):
    return td

def generic(c: Callable[[T], Any]) -> Callable[[T], Any]:
    return c

generic(specific)
```

**Comment by AGiantSquid** [comment]
Ah, so its because you _could_ call the function with generic data in the body of the wrapper. Thank you for that example, that helps to clear it up!
