### ISSUE TITLE
Lintint not working

### ISSUE THREAD

**Issue by sinankefeli** [microsoft/pylance-release#4821]
Type: <b>Bug</b>

Highlighting and ctrl + left click doesn't work on python files

Extension version: 2023.9.10
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux x64 6.2.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (3.88GB free)|
|Process Argv|--crash-reporter-id 508193cf-6ccb-4d05-b238-5b0d1eb4d934|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: infer|
|OS|Linux x64 6.2.0-32-generic|
|CPUs|AMD Ryzen 9 7950X 16-Core Processor (32 x 2991)|
|Memory (System)|124.91GB (121.24GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. I'm not familiar with the steps you're taking. 

What are you CTRL+CLICKing on? A definition? Like this:
![ctrlclick](https://github.com/microsoft/pylance-release/assets/19672699/29fcacb7-ee15-472f-8be5-3260a7de16c5)

Can you describe what you're trying to do or perhaps provide a GIF?
