### ISSUE TITLE
high memory usage(100%) when using vscode remote

### ISSUE THREAD

**Issue by 25252www** [microsoft/pylance-release#4822]
## Environment data

-   OS and version: alicloud ECS ubuntu 16.04
-   Python version (& distribution if applicable, e.g. Anaconda):  anaconda python 3.7

## Code Snippet

I do nothing but contain ssh connection, after approximately 2-4 hours, my server suddenly reach 100% memory usage

<img width="1181" alt="截屏2023-09-09 17 44 41" src="https://github.com/microsoft/pylance-release/assets/45707511/dca464fb-737a-4dfe-8955-f36ae503ddc1">

**Comment by bschnurr** [comment]
what version of pylance are you running? latest?
https://github.com/microsoft/pylance-release/releases/tag/2023.9.12

can you provide the trace logs.. see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by JulianCBC** [comment]
I'm seeing similar issues using WSL, PyLance's Node process is using _by far_ the most memory of any of the Node processes running in WSL immediately after startup with 6x relatively small python files open.

OS and version: Ubuntu 20.04.06 installed via the Microsoft Store
Python version: 3.8.10 (shipped with Ubuntu)
Pylance version: v2023.10.30

```
> wsl.exe --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2428
```

![image](https://github.com/microsoft/pylance-release/assets/52724016/f0d9255d-cc3e-4b76-9b3b-66c369fe5d6d)

**Comment by JulianCBC** [comment]
Here's a redacted log file:

[pylance.log](https://github.com/microsoft/pylance-release/files/13048317/pylance.log)

Some brief statistics on my environment: I'm using a workspace with 26 folders open and it appears to have only indexed about 24 files. This project is a mix of PHP, Javascript, Typescript, Terraform and other stuff and I have extensions installed and active for _all_ the languages I use. Pylance is the only one which is using significant memory with Terraform's language server and VSCode's remote process coming in as a distant second and third, using a third and seventh the memory of Pylance respectively.
