### ISSUE TITLE
Type is not inferred with pyi file in pyqtgraph(PyQt6)

### ISSUE THREAD

**Issue by m666m** [microsoft/pylance-release#4823]
## Environment data

-   Language Server version: pylance 2023.9.10
-   OS and version: Fedora 38 workstation
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda lastest, python 3.10

## Code Snippet

```python
import sys
from pyqtgraph.Qt import QtGui, QtCore, QtWidgets


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.btn = QtWidgets.QPushButton('hello')

        self.setCentralWidget(self.btn)


if __name__ == '__main__':
    app = QtWidgets.QApplication([])

    main = MainWindow()
    main.show()

    sys.exit(app.exec())

```

## Repro Steps

1. Let pyqtgraph use PyQt6's pyi file

Copy "QtCore.pyi/QtGui.pyi/QtWidgets.pyi" from
    ~/anaconda3/envs/p310/lib/python3.10/site-packages/PyQt6
to
    ~/anaconda3/envs/p310/lib/python3.10/site-packages/pyqtgraph/Qt

2. VSCode set "python.languageServer": "Jedi"

Move the mouse, point to "QPushButton":

    YES: I can see the declearation of class/function/...

    YES: code autocomplete works good

    YES: running the .py file works good
![jedi ok](https://github.com/microsoft/pylance-release/assets/31643783/fdc8d759-5e35-4e36-b775-038d1753d16d)

3. VSCode set "python.languageServer": "Pylance"

Move the mouse, point to "QPushButton"

## Expected behavior

    step 2  Jedi does

## Actual behavior

    NO: code not inferred, all "funcion ... any"

    NO: code autocomplete not works

    YES: running the py file works good
![pylance no](https://github.com/microsoft/pylance-release/assets/31643783/41116d6e-f12b-44ef-8fa5-31f075eabbc4)

But if I remove the empty dirs "QtCore/QtGui/QtWidgets" in ~/anaconda3/envs/p310/lib/python3.10/site-packages/pyqtgraph/Qt/, then reopen my .py file:

    YES: I can see the declearation of class/function/...

    YES: code autocomplete works good
![pylance yes](https://github.com/microsoft/pylance-release/assets/31643783/2cfcf4a7-8c57-45af-94fd-a51dc9fb84b1)

    NO: running the py file [failed]:

        ImportError: cannot import name 'QtCore' from partially initialized module 'pyqtgraph.Qt' (most likely due to a circular import) (.../site-packages/pyqtgraph/Qt/__init__.py)

How can I configure the pylance works with the sip files like step 2 Jedi does?

## Logs

see attached zip file: 
[ms-python.python.Python language server.zip](https://github.com/microsoft/pylance-release/files/12569906/ms-python.python.Python.language.server.zip)

**Comment by debonte** [comment]
Instead of copying the `pyi` files into the `pyqtgraph` implementation directory, copy them to `<your workspace root>/typings/pyqtgraph/Qt`. Then you won't impact the runtime behavior, but Pylance will know to find the stubs there for type checking. `typings` is the default location, but you can change this by setting `python.analysis.stubPath`.

FYI, there's some discussion about providing official stubs for `pyqtgraph` [here](https://github.com/pyqtgraph/pyqtgraph/issues/2409). You might want to comment on that issue about your scenarios.

**Comment by m666m** [comment]
Thanks for replay, this works for me .

But I found if  write the code `import pyqtgraph as pg`, not inferred again:

```python

import sys

# from pyqtgraph.Qt import QtGui, QtCore, QtWidgets
import pyqtgraph as pg

class MainWindow(pg.Qt.QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.btn = pg.Qt.QtWidgets.QPushButton('hello')

        self.setCentralWidget(self.btn)


if __name__ == '__main__':
    app = pg.Qt.QtWidgets.QApplication([])

    main = MainWindow()
    main.show()

    sys.exit(app.exec())

```

**Comment by debonte** [comment]
Looks like to make aliasing work you need to add the following:

`typings\pyqtgraph\__init__.pyi`:
```python
import Qt as Qt
```

`typings\pyqtgraph\Qt\__init__.pyi`:
```python
import QtWidgets as QtWidgets
```

**Comment by debonte** [comment]
We're a little more flexible when resolving imports within the workspace. Once you move the files outside you're workspace, you'll need to change the import syntax slightly. The code below will work in both locations (default `typings` dir or anywhere outside your workspace):

`typings\pyqtgraph\__init__.pyi`:
```python
from . import Qt as Qt
```

`typings\pyqtgraph\Qt\__init__.pyi`:
```python
from . import QtWidgets as QtWidgets
```

**Comment by m666m** [comment]
That's great，thank you !

**Comment by m666m** [comment]
Setting 'python.analysis.stubPath' can't inferred  after pylance upgrade to  2023.9.20. 
'typings' dir in work space sitll works.

**Comment by debonte** [comment]
@m666m, can you please open a new issue? We recently changed how we handle paths within Pylance. You may be hitting a bug in that new behavior.
