### ISSUE TITLE
ConfigurationItem.scopeUri in workspace/configuration request is not a DocumentUri

### ISSUE THREAD

**Issue by jwortmann** [microsoft/pylance-release#4826]
*This issue is about the Pyright language server, but I open it in this repository because AFAICT the Pyright repo is only about core type checking bugs.*

## Environment data

-   Language Server version: Pyright language server 1.1.326
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Repro Steps

I'm thinking about how to implement support/special handling for the optional [`scopeUri`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#configurationItem) field of the `workspace/configuration` request in a client. I noticed that the `scopeUri` used by Pyright is not a [`DocumentUri`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#documentUri), but instead it uses the URI of the workspace folder given in the `initialize` request of the client. So I think that Pyright is not compliant with the LSP specs here.

For example, with an opened project stored at `D:\MyProject`, the params of one of the `workspace/configuration` requests are
```json
{
    "items": [
        {
            "scopeUri": "file:///D:/MyProject",
            "section": "python"
        }
    ]
}
```

You can see in the specs that the type of [`WorkspaceFolder.uri`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceFolder) (from `initialize`) is `URI`, while `scopeUri` should be a `DocumentUri`, so I tend to think that this is a bug in Pyright. If you disagree, I could open an issue in the LSP repo, and ask for clarification or to fix the types in the specs.

**Comment by rchiodo** [comment]
Thanks for the issue but I believe we are doing the correct thing here. If I'm understanding your request, the scopeURI should be for a specific document, not a folder?

I don't believe that's the intent of the scope URI. It can be for any URI that's valid in the currently list of open files and folders in the client. 

If you disagree, maybe it would be better to get clarification from the LSP authors.

**Comment by jwortmann** [comment]
> If I'm understanding your request, the scopeURI should be for a specific document, not a folder?

Yes, I've checked a few other language servers and while many don't use `scopeUri` at all, a few servers (vscode-css-languageserver and vscode-html-languageserver) indeed use the full URI of an opened document, and they resend the request with a new `scopeUri` whenever another document is opened in the editor. But note that the servers for those languages don't really rely on a project structure, in contrary to Pyright.

I agree that it makes more sense to allow a folder URI, instead of restricting it to `DocumentUri`s for this request.

I will create an issue in the LSP repo and ask for clarification.
