### ISSUE TITLE
No action on "Remove all unused imports"

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/pylance-release#4830]
## Environment data

-   Language Server version: 2023.9.10 (pyright c70adefc)
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.11

## Code Snippet

Using a pretty minimal repro here, but just this:

```python
from typing import Any, Awaitable, Callable#$
```

## Repro Steps

1. Request code actions at the cursor notated as `#$`
2. Select "Remove all unused imports"

## Expected behavior

All imports are removed.

## Actual behavior

File is unchanged.

Nothing interesting appears in the logs.

**Comment by StellaHuang95** [comment]
I can only repro this in vscode insiders, it works fine in vscode stable.

**Comment by StellaHuang95** [comment]
Verified that this repros with `python.analysis.enableSyncServer` set to `true`, no matter the vscode version. 

This is where different `enableSyncServer` values start to diverge. https://github.com/microsoft/pyrx/blob/200801f2e0555b0a4ad85820a1c96b3f5e414358/packages/pylance-internal/src/server/syncServer.ts#L2419

@rchiodo Any ideas what's going wrong here? I can also debug more tomorrow.

**Comment by rchiodo** [comment]
Sorry it's likely just something that wasn't tested well in the sync server. My only guess is that it's not sending the edits for some reason.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.9.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023931-27-September-2023-PreRelease)
