### ISSUE TITLE
slots broken again

### ISSUE THREAD

**Issue by rlippmann** [microsoft/pylance-release#4832]
## Environment data

-   Language Server version: v2023.9.10
-   OS and version: Ubuntu 22.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Code Snippet

If you use dataclass(slots=True) you get a warning:
No parameter named slots

## Repro Steps

1. XXX

## Expected behavior

@dataclass(slots=True) is supported from python 3.10 on

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by bschnurr** [comment]
Thank you for logging the issue. Unfortunately I can't repo with 3.11 python, i'll try anaconda 3.10

**Comment by luabud** [comment]
Unfortunately we are unable to reproduce this issue. If you are still experiencing this problem, please consider providing more information about your code, environment and logs: https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by raylu** [comment]
I had a similar issue. a `pyproject.toml` in a parent directory had
```toml
[tool.pyright]
pythonVersion = "3.9"
```
so even though it was using a 3.11 interpreter and it loaded the fallback typeshed with 3.11 types, it still evaluated the typeshed as 3.9

I don't think trace-level logs showed this happening, so it was pretty tricky to debug

**Comment by heejaechang** [comment]
@raylu this issue is already closed. can you open new issue with repro steps and etc?

I think you want to use different version than the python interpreter version you selected in vscode?
