### ISSUE TITLE
Fix all command no longer removes unused imports

### ISSUE THREAD

**Issue by rbhanot4739** [microsoft/pylance-release#4835]
The `Fix All` no longer seems to remove the unused imports. I have the following settings defined in my `settings.json`

```
"[python]": {
    "editor.codeActionsOnSave": {
      "source.fixAll": true,
      "source.organizeImports": true
    }
},
"python.analysis.fixAll": [
    "source.unusedImports"
  ],
```

**OS**:  MacOS(13.5.2 (22G91))
**VsCode version**: 1.82.0
**Python extension version**: v2023.16.0
**Pylance extension version**: v2023.9.10

It was working up until few days ago and today I noticed that it no longer works. I have tested this on insiders version as well along with pre-release versions of both `pylance` and `python` extensions. 

So not sure where the bug is.

**Comment by rbhanot4739** [comment]
Any update on this ?

**Comment by heejaechang** [comment]
looks like it is broken.

**Comment by rchiodo** [comment]
Is this a dupe of #4830 ?

Try doing this:

```
"python.analysis.enableSyncServer": false
```

**Comment by heejaechang** [comment]
ya, it works with that.

closing as a dup.

**Comment by rbhanot4739** [comment]
@rchiodo thanks for the tip, is there a downside of changing the default value of `True` to `False` ?
