### ISSUE TITLE
IntelliSense disappears after saving with the default name until reopen the Jupyter Notebook.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#4837]
## Environment data
Build of Visual Studio Code - Insiders: 1.83.0-insider
Build of python-insider: v2023.17.12561009
Build of pylance-insider: v2023.9.12

## Repro Steps
1. Open a folder
2. Ctrl + shift + P to open command palette and choose "Create: New Juyter NoteBook"
![image](https://github.com/microsoft/pylance-release/assets/59192491/4553318c-6600-48da-a275-8dbf74aee619)
3. Type sys and verify you get completions
4. And hover over sys and make sure it shows something
5. Save this Juyter NoteBook with the deafult name

## Expected behavior
Hover over sys and make sure it shows something.

## Actual behavior
IntelliSense disappears.
![Imports_from_files](https://github.com/microsoft/pylance-release/assets/59192491/72fd930e-e308-462a-822d-407cbecfc8c7)
After restart the Juyter NoteBook, IntelliSense works well. This issue is not reproduced when we save with other name.
## Logs
![image](https://github.com/microsoft/pylance-release/assets/59192491/c9a936b4-3cf6-4d48-9fbe-8aff213a3603)

**Comment by StellaHuang95** [comment]
Does it still repro if you add `"python.analysis.enableSyncServer": false` to your `settings.json`?

**Comment by linette-zyy** [comment]
I can not repro this issue after adding  ```"python.analysis.enableSyncServer": false``` to my settings.json
![jupyter_intelliSense](https://github.com/microsoft/pylance-release/assets/59192491/2687fce4-ae23-4894-985d-96fa96ff3465)

**Comment by StellaHuang95** [comment]
@linette-zyy Does this still repro for the sync server case?

**Comment by ttSpace** [comment]
I can't repro it without adding any settings.
## Build info

<details>
<p>

```
Build of Visual Studio Code - Insiders: 1.85.0-insider 
Build of python-insider: v2023.21.13201007
Build of pylance-insider: v2023.11.13 

```

</p>
</details>

![image](https://github.com/microsoft/pylance-release/assets/82852072/c7183b67-cec5-45d7-98ac-6ff5bd4e3c29)

**Comment by StellaHuang95** [comment]
@ttSpace Does it repro when you enable sync server?

**Comment by ttSpace** [comment]
@StellaHuang95 I can not repro it when sync server is enabled.

![image](https://github.com/microsoft/pylance-release/assets/82852072/eab34139-2498-416e-a4f3-80a981cc6dee)

## Build info

<details>
<p>

```
Build of Visual Studio Code - Insiders: 1.86.0-insider 
Build of python-insider: v2023.23.13481009
Build of pylance-insider: v2023.12.100

```

</p>
</details>

![image](https://github.com/microsoft/pylance-release/assets/82852072/9b5ea1a8-b881-42cb-addf-56841a3adbc2)
