### ISSUE TITLE
Symbol highlighting disappears when switching editors across VS Code multiroot workspace

### ISSUE THREAD

**Issue by ijessen-mitll** [microsoft/pylance-release#4846]
<h3> Environment data </h3>

-   Language Server version: 2023.9.10
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.10
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Repro Steps </h3>

Note: this only happens with Pylance Language Server version: 2023.9.10.  This behavior does *not* happen with Pylance Language Server version: 2023.8.50

- Open Python file from first folder of multi-root workspace
- Note that semantic highlighting is applied after Pylance completes indexing
- Open other Python file from second folder of multi-root workspace
- Note again that semantic highlighting is applied after Pylance completes indexing
- Switch back to editor tab of first open file - note that most semantic highlighting *disappears* after a few milliseconds

This behavior persists across files within the different workspace root folders.  As soon as highlighting disappears from one file from one workspace root, all files in that same root will lack highlighting.  All files in the unaffected root will maintain their highlighting.

<h3> Logs </h3>

The following log snippet is captured after toggling back to the first file (paths have been sanitized).  The disappearance of highlighting coincides with `getSemanticTokens` log entry printed at 16:52:01.045.

```
2023-09-18 16:52:00.619 [info] (22626) [FG] parsing: /path/to/code/file.py [fs read 1ms] (16ms)
2023-09-18 16:52:00.621 [info] (22626) [FG] binding: /path/to/code/file.py (2ms)
2023-09-18 16:52:01.045 [info] (22626) [BG(7)] getSemanticTokens delta previousResultId:1695070297043 at /path/to/code/file.py (0ms)

```

**Comment by rchiodo** [comment]
Can you try setting this and see if it works again?

```
"python.analysis.enableSyncServer": false
```

**Comment by ijessen-mitll** [comment]
> Can you try setting this and see if it works again?
> 
> ```
> "python.analysis.enableSyncServer": false
> ```

Nope - no joy.

**Comment by djbarker** [comment]
I also see this issue. Using Pylance 2023.8.50 does stop the python files in one root from losing highlighting, but it also seems to break (or not support?) imports of editable modules in an `.ipynb` notebook. Which "breaks" the highlighting in notebook as it cannot recognise any of the functions imported. (As it happens the code for the editable module lives in the other workspace root).

**Comment by rchiodo** [comment]
Does anybody have a test workspace that reproduces the problem? I have a setup like so and colorization works fine:

![image](https://github.com/microsoft/pylance-release/assets/19672699/88975d2e-c6a8-4b4f-a5b9-f9981cb7b8e9)

**Comment by djbarker** [comment]
I don't have a minimal example I can share but it definitely seems to happen in workspaces where I have notebooks open.
