### ISSUE TITLE
python package alias is not recognized by pylance

### ISSUE THREAD

**Issue by forrestjgq** [microsoft/pylance-release#4849]
## Environment data

-   Language Server version: v2023.9.10
-   OS and version: macos
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11

## Code Snippet

refer to https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/core/__init__.py#L9

```python
import megatron.core.parallel_state
import megatron.core.tensor_parallel
import megatron.core.utils

from .inference_params import InferenceParams
from .model_parallel_config import ModelParallelConfig

# Alias parallel_state as mpu, its legacy name
# ----> mpu will not be recognized
mpu = parallel_state

__all__ = ["parallel_state", "tensor_parallel", "utils", "InferenceParams", "ModelParallelConfig"]
```

## Repro Steps

just clone and open https://github.com/NVIDIA/Megatron-LM

## Expected behavior

alias of package should be recognized correctly

## Actual behavior

[{
	"resource": "/workspace/MegatronLM/megatron/core/__init__.py",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": {
		"value": "reportUndefinedVariable",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportUndefinedVariable"
		}
	},
	"severity": 4,
	"message": "\"parallel_state\" is not defined",
	"source": "Pylance",
	"startLineNumber": 9,
	"startColumn": 7,
	"endLineNumber": 9,
	"endColumn": 21
}]

## Logs

<!--

**Comment by erictraut** [comment]
This code is relying on a tenuous side effect of the python import loader. Pyright (the type checker upon which pylance is built) intentionally does not model such side effects. In general, they are not possible to model by a static analysis tool, and even when they can be modeled, such code is fragile and leads to maintenance problems. You can read more about this [in the pyright documentation](https://microsoft.github.io/pyright/#/import-statements).

If you want this to work with static analysis tools like pyright and pylance, the code would need to be changed to `mpu = megatron.core.parallel_state`. If you're not a maintainer of the megatron library, please consider filing an issue in that project's issue tracker to bring this to the maintainers' attention.
