### ISSUE TITLE
False Positive for `list[x]` not assignable to `list[x | y]` 

### ISSUE THREAD

**Issue by jshannon-tml** [microsoft/pylance-release#4856]
<h3> Environment data </h3>

-   Language Server version: 2023.9.10
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
def return_subset() -> list[int]:
  return [1]

def return_set() -> list[int | float]:
  return return_subset()

```

<h3> Repro Steps </h3>

1. Run pylance on the above

<h3> Expected behavior </h3>

No error. 

`return_set()` returns a list of *either* `int`s *and/or* `float`s (`list[int | float]`). (the union type being [either/or](https://docs.python.org/3/library/typing.html#typing.Union)). In my mind, that should be equivalent to declaring: `list[int] | list[float] | list[int | float]`. 

`list[int | float]` does not mean that the list must contain >= 1 `int`s and >= 1 `float`s.

Thus, an expression of `list[int]` should be assignable to a return type of `list[int | float]`. 

<h3> Actual behavior </h3>

Error on line 5 (`return_subset()`):

```
Expression of type "list[int]" cannot be assigned to return type "list[int | float]"
  "list[int]" is incompatible with "list[int | float]"
    Type parameter "_T@list" is invariant, but "int" is not the same as "int | float"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
(function) def return_subset() -> list[int]
```

**Comment by erictraut** [comment]
This isn't a false positive. The type `list[int]` is not type compatible with `list[int | float]`. While it may not be immediately obvious, you can read more about why this limitation is required for type safety [here](https://microsoft.github.io/pyright/#/type-concepts?id=generic-types).
