### ISSUE TITLE
Auto-dedent on `else:` in tabbed file removes too many characters

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4858]
## Environment data

-   Language Server version: 2023.9.21
-   OS and version: Windows 11
-   Python version: 3.11.5

## Code Snippet

```python
def func():
	if True:
		x = 1
		else
```

## Repro Steps

1. Set the following settings:
```json
    "editor.insertSpaces": false,
    "editor.tabSize": 4,
    "editor.renderWhitespace": "all"
```
2. Place code above in a Python file
3. Place cursor after `else` and press `:`

## Expected behavior

`else:` is dedented by one tab.

## Actual behavior

Both leading tabs and the `el` of `else` are removed.
![jUExcnoTdU](http://g.recordit.co/jUExcnoTdU.gif)

http://g.recordit.co/jUExcnoTdU.gif

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.9.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#2023931-27-September-2023-PreRelease)
