### ISSUE TITLE
The code 'np.sqrt(1)' runs correctly but the error 'Module is not callable'  is raised by Pylance

### ISSUE THREAD

**Issue by Youngerkind** [microsoft/pylance-release#4868]
## Environment data

-   Language Server version: 2023.9.20 (pyright 35eaeca4)
-   OS and version: ubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10

## Code Snippet

```python
import numpy as np

a = np.sqrt(1)
```

## Actual behavior

The codes just run normally. But Why there is a warning?
![image](https://github.com/microsoft/pylance-release/assets/96768846/92677c0f-1c1b-4818-b8d4-dc858b1e7dad)

It is the same for `np.square(1)` as well.

**Comment by erictraut** [comment]
I'm not able to repro the problem. Which version of numpy do you have installed? I suspect that you have an old version that contained some typing errors. You can upgrade to the latest using `pip install numpy --upgrade`.

**Comment by Youngerkind** [comment]
Thank you for your help, Eric Traut!

The problem was gone after the package `numpy` was upgraded from `1.16.6` to `1.24.4`, using the command you provided.
I am working on a server, and the system manager has not upgraded any packages since the operation system `ubuntu 20.04 lts` was installed.

Thanks again for your wisdom and kindness!
