### ISSUE TITLE
Annotations of an attribute of an attribute

### ISSUE THREAD

**Issue by AwePhD** [microsoft/pylance-release#4870]
Hello,

I'd like to annotate the type of an attribute's attribute within one of my classes. Here's an example:

```python
# In the __init__ method of my class.
self.attribute.attribute_of_attribute: MyType
# pylance message:
# Type annotation not supported for this statementPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

In my class scopre, I know what are the types of both self.attribute and self.attribute_of_attribute. However, these attributes are instantiated in a parent meta class, which uses a builder to construct these objects at runtime from configuration files. So when those attributes are instanced, they do not have type annotations. I cannot modify the builder or the meta class.

How can I type self.attribute.attribute_of_attribute in the __init__ method of my class? I'm not looking for solutions like reimplementing the __init__ method from the meta class or monkey-patching the meta class. I simply want self.attribute.attribute_of_attribute to be statically typed as MyType. Is this feasible?

Edit: I guess it's something that I do not get about annotations hints in Python. So it's not a pylance question per-say. I apologize if my question does not belong to the right place. I thought pylance - since the type checking feature - issue would be a good place to question this.

Thank you for your time,
Mathias.

**Comment by AwePhD** [comment]
Reproduction with a simple minimal example. Here there is no meta class, runtime building.
How can I change self.b_from_c.a_from_b type from the C init?

```
class A:

    def __init__(self) -> None:
        self.a = ''


class B:

    def __init__(self) -> None:
        self.a_from_b = A()


class C:

    def __init__(self) -> None:
        self.b_from_c = B()
        self.b_from_c: B
        self.b_from_c.a_from_b: A
```

**Comment by AwePhD** [comment]
In [PEP 526](https://peps.python.org/pep-0526/#global-and-local-variable-annotations), there is no mention about nesting annotations like I want to do. Since the annotations syntax in Python is only for clarity (type checkers and human readability), I guess the current scenario is off-topic ; it's too complicated. 

> Explicit is better than implicit.
> Simple is better than complex.
> Complex is better than complicated.
> Flat is better than nested.

Although, in my case, I actually want to type hint something that is complex and complicated, so to bring "explicit" hints.  But I guess the type hints are meant to be in the local scope. Since attribute of self is in the local scope, if I add the scope of self.b_from_c in addition, it would be very complicated. Notably, if you have to extend the scope for annotations for every attributes. So I guess the design of type hint are kept local in purpose to remain simple.

I find a workaround and pylance can infer the type of my nested attribute. I add this line instead of the classic type hint:

```python
assert isinstance(self.b_from_c.a_from_b, A)
``` 

Pylance does not issue any warning and I have the type for the completion and for the knowledge of the reader. 

I let this issue open, I would like to have the opinion of a pylance dev since this type hint philosophy of Python is a bit complicated to me. I am not sure to understand correctly. Plus, the nested type hint in my scenario seems pythonic to me so I am a bit surprised that it does not work.  Eventually, the use of `isinstance` looks like goose-typing but A is not an ABC class or a meta class in my real situation.

**Comment by erictraut** [comment]
A type for an attribute must be declared by the class that owns the attribute, not a class that accesses the attribute. In your example above, the attribute `a_from_b` is owned by class `B`, so class `B` is responsible for defining which type is valid for this attribute. It wouldn't make sense (from a type checking perspective) to allow another class (`C`) to specify or modify the inner workings of class `B`.

I don't fully understand the problem you're trying to solve, but perhaps generic classes are the answer? A generic class allows a class like `B` to have a type "placeholder" in the form of a "type variable" that can be specified at instantiation time. For example, if you want class `B` to support different types for attribute `a_from_b`, you can specify this with a generic.

```python
from typing import Generic, TypeVar

T = TypeVar("T")

class A:
    def __init__(self) -> None:
        self.a = ""

class B(Generic[T]):
    def __init__(self, a_from_b: T) -> None:
        self.a_from_b: T = a_from_b

class C:
    def __init__(self) -> None:
        self.b_from_c = B(A())
        reveal_type(self.b_from_c.a_from_b)  # A
```

**Comment by AwePhD** [comment]
I appreciate your detailed explanation regarding the issues related to nested annotations. Your response was both prompt and informative, and I thank you for that.

Regarding the core concern, it seems that the class itself should ideally be responsible for annotating its attributes, from a type checking perspective. I understand this design and I agree.

To elucidate my question further, I attempted to create a minimal example in pure Python, consisting of just 40 lines. However, despite my efforts, this example still proves to be quite intricate in demonstrating the purpose of such a class design. I would like to emphasize that the intention here is to address the topic of annotations rather than engage in a debate about the design of the minimal example or the framework.

---

You have a base class called BuilderBaseClass that has the ability to construct certain classes from a dictionary. In the provided example, only two classes are showcased, but in reality, these classes are modules within the framework, and there are numerous such modules(*). I've also included your solution, even though it doesn't align with my specific scenario, as I cannot modify these classes within my codebase. Consequently, I cannot add the generic type in the constructor of BuilderBaseClass. Plus, it does not give the type hints.

```python
class BuiltClassOne:
    def __init__(self, foo: int) -> None:
        self.foo = foo
        print(f"{foo = }")


class BuiltClassTwo:
    def __init__(self, bar: str) -> None:
        self.bar = bar
        print(f"{bar = }")


# This class belongs to the framework: it cannot be edited
class BuilderBaseClass(Generic[T], metaclass=ABCMeta):
    # Add other methods / attributes
    def __init__(self, cfg: dict):
        cls = globals()[cfg.pop('type')]
        self.x: T = cls(**cfg)
``` 

This builder class needs a config  `dict` variable to instantiate its `x` attribute, It is what I meant by: 

> However, these attributes are instantiated in a parent meta class, which uses a builder to construct these objects at runtime from configuration files. 

Here an example of such a config dictionary:

```python
config_for_class_one = dict(
    type='BuiltClassOne',
    foo=0,
)
```

Specifically, this `BuilderBaseClass is instanciated within a class called `IntermediateClass`:

```python
# This class belongs to the framework: it cannot be edited
class IntermediateClass(BuilderBaseClass):
    # Add other methods / attributes
    def __init__(self, cfg: dict):
        super().__init__(cfg)
```

Lastly, there is my `MyClass` that I can edit. I have an attribute `y` which is `IntermediateClass`. This attribute `y` has an attribute `x` which classes depends of what is the value of the `type` key in my config `cfg` dictionary.

```python
class MyClass:
    # The editable class
    def __init__(self, cfg):
        self.y = IntermediateClass(cfg)
```

--- 

The primary purpose of the BuilderBaseClass is to construct a class from a configuration stored as a dictionary. This class encompasses all the logic required for managing scope, although for the purpose of illustration, I've used the global scope. It's crucial to note that the framework employs the same base class to instantiate a variety of modules, each with its unique interface. Consequently, annotating anything directly within BuilderBaseClass is unfeasible. For illustration, we can see that the `BuiltClassOne` and `BuiltClassTwo` have different attributes. 

(*): In addition, I'd like to clarify the role of IntermediateClass. While it could theoretically provide an annotation for the x attribute, as it restricts the types of configurations that can be used with the x object, it doesn't provide such annotations in the context of the framework. Furthermore, in the context of MyClass, inheriting from IntermediateClass is not a viable solution, making it impossible to annotate the x attribute directly from its class.

So without introducing breaking changes or modifying the framework code, how can I introduce a type hint for `self.y.x`. Lately, I thought of implementing a [protocol](https://peps.python.org/pep-0544/) that performs static duck typing for `IntermediateClass`. So it would be a solution to not modify the framework code while providing additional information. I forgot to mention that the `x` attribute is a method. From my understanding protocol is for static duck typing methods.

**Comment by erictraut** [comment]
> So without introducing breaking changes or modifying the framework code, how can I introduce a type hint for self.y.x.

You can't provide a direct type annotation for `self.y.x` for the reasons I mentioned above. If the classes you're using are not properly typed as generic classes, then your options are rather limited. Can you eliminate the dependency on these classes, since they don't meet your needs?

One other thought is to add code to your class that provides an accessor method and includes a `cast` operation to cast the untyped or mistyped object. You can use the `typing.cast()` call to do this.

**Comment by AwePhD** [comment]
Thanks for your quick answer.

I cannot eliminate the dependency. More, the design that I tried to illustrate is the design of almost any class in the framework.

For the cast function. I think the use of this function is cleaner compared to `isinstance`. Plus it does not do anything at runtime while the `assert` solution introduces an `assert`, which I do not like. 

So if I follow your idea, I implement `get_x(self) -> BuiltClassOne: return typing.cast(BuiltClassOne, self.y.x)`. So when I want to use the nested attribute from `MyClass`, I can use the getter to have pylance type checking / hint. If I may I, I have 2 questions:

- Why do I need typing.cast when I can just use the annotation of the getter `-> BuiltClassOne`. Is it because the cast type is more flexible than annotation?
- While the use of `typing.cast` with the getter works, I would like to know if the use of Protocol is following the type checking logic, please. I put an example below. So my `y` attribute is now correctly typed. It's statically typed that it has a `x` attribute. Then it gives information that we need `y` to have a class with an `x` attribute of class `BuiltClassOne`. The protocol seems, from my understanding, to be a layer of typing that I add on top of `IntermediateClass` to type hints. So it's not like I choose in `MyClass` which are the attribute of my attribute. It's much more like "I choose what kind of `y` attribute I want to have". Is the use of Protocol matching the type checking sense?

```python
class OnlyClassOne(typing.Protocol):
    x: BuiltClassOne

# in __init__ of MyClass
self.y: IntermediateProtocol = IntermediateClass(config)
```

Thanks for you patience.

**Comment by erictraut** [comment]
The `cast` call effectively tells the type checker to ignore its own type evaluation for an expression and substitute the type that you specify. I recommend avoiding it if possible, but there are cases where it is the best option available. This is sometimes because the behavior of the code is too dynamic for a static type analyzer to understand or because you're consuming classes that are typed incorrectly or incompletely. Your case falls into the latter category.

I don't understand enough about your problem to say whether a protocol would work. You'll need to determine whether it's a an appropriate tool for your use case. Pyright fully supports protocols as they are specified in [PEP 544](https://peps.python.org/pep-0544/).

If you have more general questions about how to use the Python type system (independent of whether you're using pyright, mypy, or other standards-based type checkers), the [python/typing discussion forum](https://github.com/python/typing/discussions) is a good place to get help from the broader Python typing community.
