### ISSUE TITLE
"OutOfMemoryError" is not a valid exception class

### ISSUE THREAD

**Issue by Avishka-Perera** [microsoft/pylance-release#4874]
Pylance shows the above error during scripting in VS Code when catching `torch.cuda.OutofMemoryError` but when I run the script, everything works fine.

### Minimum reproducible code
```
import torch
from torch.nn import Linear

try:
    model = Linear(64, 64)
except torch.cuda.OutOfMemoryError:
    print("Out of memory")

```

**Comment by erictraut** [comment]
Pylance is working correctly here.

This is a bug in the type stub that ships with pytorch. The `torch.cuda.OutOfMemoryError` is a type alias to the type `torch._OutOfMemoryError`, which is defined as follows:

```python
class _OutOfMemoryError:
    pass
```

The Python runtime requires that all objects used with a `raise` statement must be instances of a class that derives from `BaseException`. That means `_OutOfMemory` should be declared as a subclass of `BaseException` or `Exception`.

```python
class _OutOfMemoryError(Exception):
    pass
```

Please report this bug to the maintainers of the pytorch library.
