### ISSUE TITLE
Ability to support other type checkers, like mypy.

### ISSUE THREAD

**Issue by scruel** [microsoft/pylance-release#4875]
I wonder if I can choose to other type checkers in VS Code via this plugin?
pyright is good enough, however in some cases, I do prefer to use mypy to check mycode, because it can give me some notes about how to correction the error.

For example, for the following code:

```python
class T:
  def p(self):
    print(1)

class T2(T):
  pass

class X:
  def __init__(self, t: list[T]):
    pass

class X2(X):
  def __init__(self, t: list[T2]):
    super().__init__(t)
```

pyright will give me the following outputs:
```
  C:\Users\scruel\Desktop\x.py:14:22 - error: Argument of type "list[T2]" cannot be assigned to parameter "t" of type "list[T]" in function "__init__"
    "list[T2]" is incompatible with "list[T]"
      Type parameter "_T@list" is invariant, but "T2" is not the same as "T" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
```

mypy will give me the same error, but with notes:
```
C:\Users\scruel\Desktop\x.py:14: error: Argument 1 to "__init__" of "X" has incompatible type "list[T2]"; expected "list[T]"  [arg-type]
C:\Users\scruel\Desktop\x.py:14: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
C:\Users\scruel\Desktop\x.py:14: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
```

Acorrding to the notes which provided by mypy, I now can know how to fix the error: change List to Sequence, it is quite user-friendly to provide such extra info.

**Comment by erictraut** [comment]
I've updated pyright's error messages to include suggestions similar to mypy's for `list` and `dict`. Thanks for the suggestion.

**Comment by scruel** [comment]
> @scruel, is this the only (or primary) reason you want to use mypy over pyright?
> 
> We're always looking for ways to make error messages more understandable in pyright. Adding similar notes to the error messages in pyright is a reasonable enhancement request.

Currently, yes, it is the only reason I find, though it will be really nice, if Pylance can have this feature request supported. However, even I am not familiar with the repo, I still think it will require some huge changes which will cost you a lot, so you can close this issue as not planned for now, and open it if you want to do this in the feature.

> I've updated pyright's error messages to include suggestions similar to mypy's for list and dict. Thanks for the suggestion.

Oh, thank you, you already got this improved this so quickly!
I realize that for the description of this issue, I should fire related issues in the pyright repo also, and you did that for me, you're really nice!
