### ISSUE TITLE
VSCode shortcut for inferring Python variable types

### ISSUE THREAD

**Issue by mht2953658596** [microsoft/pylance-release#4887]
https://github.com/microsoft/vscode/issues/193874#issue-1909821310
I am using VSCode to write Python code, and I have a question. How can I add a type to a variable, and does VSCode have a shortcut to deduce the type of a variable through assignment statements?

such as:
```python
_dict={"john":1,"peter":2,"mike":3,"nike":4} 
_sort=sorted(_dict.items(),key=lambda x:x[1],reverse=True)
```

Is it possible to have a shortcut key that, when the cursor is placed on a variable and the shortcut is pressed, automatically deduces the type of that variable?

then，the code will be that：

```python
from typing import Dict, List, Tuple
_dict: Dict[str, int] = {"john": 1, "peter": 2, "mike": 3, "nike": 4}
_sort: List[Tuple[str, int]] = sorted(_dict.items(), key=lambda x: x[1], reverse=True)
```

Additionally, it can automatically import the 'typing' module for these types

**Comment by StellaHuang95** [comment]
Hi @mht2953658596, you can add type annotations to variables and functions using Pylance's inlay type hints feature. To achieve what you're looking for, you can enable variable type inlay hints by setting `"python.analysis.inlayHints.variableTypes": true`.

You can also learn more about inlay type hints in our [devblogs](https://devblogs.microsoft.com/python/python-in-visual-studio-code-july-2022-release/).
