### ISSUE TITLE
Pylance complains when parsing Literal type with variable

### ISSUE THREAD

**Issue by rb901909** [microsoft/pylance-release#4894]
I seem to encounter a Pylance complaint with the following code:

```python
from typing import Literal
an_integer = 1
a_type = Literal[an_integer]
```

The complaint says `Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value`. As expected, the complaint goes away when setting directly `a_type = Literal[1]`.

However, the above way of defining a Literal type is valid Python, i.e. look at [these examples on the official docs for Literal types](https://peps.python.org/pep-0586/#legal-and-illegal-parameterizations).

Let me know if someone can look into this and see if it might be a potential bug with Pylance's parser. Thanks!

## Environment data

-   Language Server version: `v2023.9.20` on VSCode `Version: 1.81.1 (Universal)`
-   OS and version: MacOS Monterrey
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.17

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is correct in flagging that as incorrect. You are not allowed to use a variable within a `Literal` type expression. The value within a `Literal` must be a literal expression (string, bytes, integer), `None`, an enum value, or a literal type alias. In your code sample above, you're attempting to use a variable `an_integer`, which isn't allowed.

```python
Literal[1] # Allowed
LiteralOne: TypeAlias = Literal[1]
Literal[None, 2, Literal[3], LiteralOne] # Allowed
x = 1
Literal[x] # Not allowed
```

**Comment by rb901909** [comment]
Ah I see, that makes sense, it seems that the only variables allowed in `Literal` are `TypeAlias`. Thanks for the help!
