### ISSUE TITLE
Extension crashes related to WASM

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4899]
Presumably IntelliCode related. We're seeing similar issues in 2023.9.21 and 2023.9.20, so I don't believe this is related to the [recent `onnxruntime-web` upgrade](https://github.com/microsoft/pyrx/pull/4103).

- Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '<REDACTED: user-file-path>'). Build with -sASSERTIONS for more info., [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.</br>    at <REDACTED: user-file-path>:2:46756</br>at func (<REDACTED: user-file-path>:2:46414)</br>at func (server.bundle.js:1:371558)</br>at func (server.bundle.js:1:399034)</br>at func (server.bundle.js:1:396806)</br>
- Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '<REDACTED: user-file-path> (Perso)<REDACTED: user-file-path>'). Build with -sASSERTIONS for more info., [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.</br>    at func (Perso)<REDACTED: user-file-path>:2:46756</br>    at func (<REDACTED: user-file-path> (Perso)<REDACTED: user-file-path>:2:46414)</br>    at func (<REDACTED: user-file-path> (Perso)<REDACTED: user-file-path>:1:375897)</br>    at func (<REDACTED: user-file-path> (Perso)<REDACTED: user-file-path>:1:403130)</br>    at func (<REDACTED: user-file-path> (Perso)<REDACTED: user-file-path>:1:400881)</br>
- Error: Bad archive</br>    at func (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:28156)</br>    at func (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:37642)</br>    at func (node:fs:684:5)</br>

**Comment by rchiodo** [comment]
First step is to just add more logging. Not sure which wasm file can't load.

**Comment by rchiodo** [comment]
Logging showed out of memory errors with wasm, I don't believe we're seeing the no such file errors anymore. 

We do see this weird one though:

Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): section was shorter than expected size (8957861 bytes expected, 2199997 decoded) @+2243173). Build with -sASSERTIONS for more info., [cpu] Error: previous call to 'initializeWebAssembly()' failed., [webnn] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.</br>    at func (<REDACTED: user-file-path>:2:2700711)</br>at func (<REDACTED: user-file-path>:2:2705307)</br>at None <a href='https://github.com/microsoft/pyrx/blob/85f8159198f89040a165470943348e66ed9f6772/packages/pylance-internal/src/server/asyncServer.ts#L336'>pylance-internal/src/server/asyncServer.ts:336:12</a></br>at getWorkspaceForFile <a href='https://github.com/microsoft/pyrx/blob/85f8159198f89040a165470943348e66ed9f6772/packages/pylance-internal/src/server/asyncServer.ts#L1846'>pylance-internal/src/server/asyncServer.ts:1846:37</a></br>at None <a href='https://github.com/microsoft/pyrx/blob/85f8159198f89040a165470943348e66ed9f6772/packages/pylance-internal/src/server/asyncServer.ts#L1716'>pylance-internal/src/server/asyncServer.ts:1716:51</a></br>

I can only guess that our install is failing in some scenarios?
