### ISSUE TITLE
Python highlighting `in` and `not in` incorrect in specific case

### ISSUE THREAD

**Issue by tdegeus** [microsoft/pylance-release#4909]
Type: <b>Bug</b>

Following https://github.com/microsoft/vscode/issues/194484 , identified using the bisection algorithm 

In the following snippet `not` and `in` are incorrectly highlighted, see screenshot.

```python
import h5py

def Run():
    with h5py.File("foo", "a") as file:
        if "a" not in file:
            assert not any(m in file for m in ["b"]), "Wrong file type"
        else:
            pass
```
![screenshot](https://github.com/microsoft/vscode/assets/7030445/07606a85-19ec-4ef5-9d18-3f78ca26458c)

Instead, this correct highlighting is given if I (incorrectly) remove the import:
```python
def Run():
    with h5py.File("foo", "a") as file:
        if "a" not in file:
            assert not any(m in file for m in ["b"]), "Wrong file type"
        else:
            pass
```
![screenshort2](https://github.com/microsoft/vscode/assets/7030445/2db22146-93d0-4136-8b2a-07335c07072e)

Extension version: 2023.9.30
VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id 3d97051d-96cb-46f2-aa74-cf444e361b1f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
pythonmpsinfo:30842941
dsvsc015:30845448

```

</details>

**Comment by heejaechang** [comment]
it is `by design`, it represents that `h5py.File` is implementing/overriding `__contains__` and have its own logic. any `keyword` or `operator` where a `type` implements/override them through `magic method`, you will see that color.

**Comment by heejaechang** [comment]
you also should be able to see `hover tooltip` and `go to def` for those keyword/operators.

**Comment by tdegeus** [comment]
Thanks @heejaechang ! That is in fact a useful feature. Yet, what triggered my attention that is that `not` is yellow in this scheme (blue for default objects) whereas I would have expected `in` to be highlighted differently as in the second occurrence (or both `not in` differently). So I would still consider this a bug...
