### ISSUE TITLE
Pylance can't recognize this type, but it's standard in Python 3

### ISSUE THREAD

**Issue by jefer94** [microsoft/pylance-release#4910]
![image](https://github.com/microsoft/pylance-release/assets/3018142/425d36ab-8c59-4389-a642-d637b021f48b)

```py
from django.test.client import Client


def a(client: 'django.test.client.Client'):
    client.get('/')
    return 1


def b(client: 'Client'):
    client.get('/')
    return 1


def c(client: Client):
    client.get('/')
    return 1
```

In the function `a` it must recognize the type of `client`, it's useful with Pytest

It's using:
- Python 3.11.5
- Linux LAPTOP-IKLDLJHK 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux (Archlinux)

```
Version: 1.83.0-insider (user setup)
Commit: 4268e464763087044d0c1b5bdd37ebbe683cadfa
Date: 2023-09-29T20:42:50.630Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by erictraut** [comment]
Pylance is correct in flagging this as an error. There is no symbol `django` in the global namespace of your source file. If you want to use the symbol `django` in your code, you need to add an import statement `import django.test.client`.

You have imported a value for the symbol `Client`, so you can use that in a type annotation (as you have done in function `b` and `c`).
