### ISSUE TITLE
Object-aware autocomplete doesn't work in interactive windows

### ISSUE THREAD

**Issue by grst** [microsoft/pylance-release#4915]
## Environment data

-   VS Code version: 2.82.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002162226
-   Python Extension version (available under the Extensions sidebar): v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: Local: Windows 10 / Remote: Scientific linux kernel 3.10.0-1160.11.1.el7.x86_64
-   Python and/or Anaconda version: Python 3.10.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: "Python environment" kernel started by vscode, running via remote ssh extension

## Expected behaviour

In an interactive Python window with active jupyter kernel, I'd expect the autocomplete to be aware of the objects in memory, for instance to suggest dictionary keys. This is how this works for the notebook interface: 

![image](https://github.com/microsoft/vscode-jupyter/assets/7051479/b0d0bd86-e9f2-4759-9733-ed5974d94d37)

## Actual behaviour

However, in an interactive window (for instance, associated with a python "percent script"), this doesn't work
![image](https://github.com/microsoft/vscode-jupyter/assets/7051479/0493f03c-80a6-499a-9ddc-ec4f55ebc046)

## Steps to reproduce:

1. Create a dictionary
```python
mydict = {"aaaa": 42, "bbbb": 35, "cccc": 22}
```
2. Type `mydict["` and wait for autocomplete 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
10:52:46.519 [info] Restart requested /Interactive-2.interactive
10:52:46.621 [error] Failed to get activated conda env vars for ~/apps/jupyter/bin/python
                 in 100ms
10:52:46.622 [error] Unable to determine site packages path for python ~/apps/jupyter/bin/python (Conda)
10:52:46.658 [info] Process Execution: ~/apps/jupyter/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:52:46.699 [info] Process Execution: ~/apps/jupyter/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9036 --control=9034 --hb=9033 --Session.signature_scheme="hmac-sha256" --Session.key=b"bbdde280-619d-436a-a3d8-7d631a78fcae" --shell=9035 --transport="tcp" --iopub=9037 --f=~/.local/share/jupyter/runtime/kernel-v2-48298fdHvH8cQDnYV.json
    > cwd: ~/transient/quarto-test
10:52:47.316 [info] ipykernel version & path 6.24.0, ~/apps/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py for ~/apps/jupyter/bin/python
10:52:59.247 [warn] StdErr from Kernel Process ~/apps/jupyter/lib/python3.10/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
10:52:59.247 [warn] StdErr from Kernel Process ~/apps/jupyter/lib/python3.10/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'bbdde280-619d-436a-a3d8-7d631a78fcae' instead of 'b"bbdde280-619d-436a-a3d8-7d631a78fcae"'.
  warn(
10:52:59.374 [info] Started Kernel jupyter (Python 3.10.12) (pid: 110237)
10:52:59.374 [info] Started new session 47062b55-4b7a-4265-afcc-189a923d64e6
10:52:59.376 [info] Shutdown old session 297192d9-cd1c-44ba-9201-7cfa8ad70b06
10:52:59.377 [info] Dispose Kernel process 106726.
10:53:13.339 [info] Generated code for 1 = <ipython-input-1-3f004a30bb3a> with 2 lines
10:53:13.366 [info] Kernel acknowledged execution of cell 2 @ 1693471993362
10:53:13.367 [info] End cell 2 execution @ 1693471993365, started @ 1693471993362, elapsed time = 0.003s
```

</p>
</details>

**Comment by debonte** [comment]
Is the actual behavior, in the input box, is `mydict` shown in the completion suggestions but then flagged as unknown. If so, that's the same symptom as https://github.com/microsoft/vscode-jupyter/issues/13018#issuecomment-1458873666, so maybe whatever is broken is in the same area as that issue was.
