### ISSUE TITLE
Don't show `stubPath xxx is not a valid directory` warning when using config default

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#4917]
## Repro Steps

1. Ensure `python.analysis.stubPath` is not set in VS Code settings.
2. Open a folder that does not contain a `typings` subdir

## Expected behavior

Pylance (or Pyright) log does not contain the following warning. The warning should only be shown if the user explicitly provided a `stubPath` and that directory is not found.
```text
[Warn  - 1:35:44 PM] (33924) stubPath c:\myproject\typings is not a valid directory.
```

## Actual behavior

The warning is present.

This was discussed in the comments of https://github.com/microsoft/pyright/issues/777. Suggested fix is to modify the `workspace/configuration` logic in the Pylance/Pyright client to return empty string for `python.analysis.stubPath` if it is not set, rather than returning the default value.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.21, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231021-11-October-2023-PreRelease)
