### ISSUE TITLE
Pylance fails to recognise and highlight import of local module with the same name as a folder in the parent directory

### ISSUE THREAD

**Issue by umarbutler** [microsoft/pylance-release#4921]
## Environment data
-   Language Server version: v2023.10.10
-   OS and version: Windows 11 Version 22H2 (OS Build 22621.2283)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4

## Code Snippet

![](https://i.imgur.com/Ce06you.png)

## Repro Steps

1. Create a new workspace in an empty folder.
2. Create two folders (eg, `data` and `scripts`).
3. Within one folder, create two Python scripts, one of which shares a name with the other folder you created (eg, create `data.py` and `app.py`).
4. Within the Python script named after a folder, create a random variable (eg, `foo = 1`).
5. Within the Python script not named after a folder, attempt to the variable you created from the other script (eg, `from data import foo`).
6. Observe that Pylance fails to highlight the imported module.

## Expected behavior

Pylance should be able to highlight the imported module.

## Actual behavior

Pylance fails to highlight the imported module.

**Comment by StellaHuang95** [comment]
Can you provide your `settings.json` and also some more information outlined here?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
