### ISSUE TITLE
Cannot Go To Definition for methods of classes used as class variables. It cannot detect of which class a class variable can be instance of

### ISSUE THREAD

**Issue by Ema0** [microsoft/pylance-release#4923]
Sorry if the title is a bit confusing. It's easier to see it with an example (see below).

When I pass a class `Test2` as a parameter to another class `Test1`, and then invoke one of `Test2` methods (`method2`) from another method of `Test1`, PyLance cannot detect where `method2` has been defined because it doesn't seem to understand that that class variable is a instance of `Test2`, hence I cannot use the GoTo Definition function.
This case is handled fine with another language server (Jedi) on VSCode, and on PyCharm, so I'm not sure if I'm just not enabling some option in PyLance, if I'm doing something wrong, or if there is something wrong.

This is with PyLance (see the invocation of `method2` from `method1`):
<img width="311" alt="Pylance" src="https://github.com/microsoft/pylance-release/assets/5725131/edfd57c3-59b8-483e-b443-d5d2305b4598">

This is with Jedi:
<img width="351" alt="Jedi" src="https://github.com/microsoft/pylance-release/assets/5725131/a115043b-4bc2-4ead-880a-f6bb402c971e">

I know I can add type hints such as:
```python
class Test1:
    def __init__(self, parameter: Test2):

...
```
and that would actually work, but I can't just strong-type everywhere on some existing Python code on which I've just recently started working, and I cannot force other devs to start doing it just to make GoTo Definition work on VS Code.

<h3> Environment data 

</h3>

-   Language Server version: 2023.10.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.10, 3.11. Tried with and without a venv
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class Test1:
    def __init__(self, parameter):
        print('init Test1')
        self.parameter = parameter

    def method1(self):
        if self.parameter:
            self.parameter.method2(True)  #PyLance won't recognize this method2. It doesn't understand that self.parameter is instance of Test2


class Test2:
    def __init__(self):
        print('init Test2')

    def method2(self, flag):
        if flag:
            print("method2 called from method1 in Test1")


if __name__ == '__main__':
    t2 = Test2()
    t1 = Test1(parameter=t2)
    t1.method1()
```

<h3> Repro Steps </h3>

1. Pass a class as a parameter when creating an instance of another class and assign it as a class variable. Then invoke one of its methods.
2. Use the GoTo Definition (CTRL+Click) on the invoked method.

(see example above and code snippets for clarity)

<h3> Expected behavior </h3>

The GoTo Definition (ctrl+click) option on the method should bring me to when that method is defined in the second class.

<h3> Actual behavior </h3>

PyLance cannot detect where the method has been defined and shows a popup with "methodName: Unknown"
It cannot understand of which class the class parameter can be an instance of.

<h3> Logs </h3>

[PyLance.log](https://github.com/microsoft/pylance-release/files/12819252/PyLance.log)

**Comment by Ema0** [comment]
If Test2 was in another file nothing would change: I put everything together just to have a simple snippet to show the problem here, but when I originally noticed the issue the second class (Test2 in this example) was in another file.

But even in that case other language servers managed to work it out correctly.

**Comment by Ema0** [comment]
I've tested this on Linux as well. Same results with the only difference that instead of `function (method2): Unknown` PyLance reports `function (method2) Any`.

I suppose it is an improvement but still off compared to other language servers.

Here an example with 2  implementations of method2 in two different classes:
this is PyLance (`any` is shown even with just one implementation of method2, the one in `Test2`)
![pylance](https://github.com/microsoft/pylance-release/assets/5725131/95193486-8cf1-4b5a-874a-59f64020ad19)

This is Jedi:
![jedi](https://github.com/microsoft/pylance-release/assets/5725131/61f0ec22-e060-403b-9d85-b2794c2e4b9e)

**Comment by erictraut** [comment]
This is expected behavior. The `Go To Definition` functionality (like most functionality in Pylance) is based on type analysis. The type of the class variable `Test1.parameter` is `Any` because you have provided no type annotation. The type of expression `self.parameter.method2` is therefore also `Any`. From a type analysis perspective, there's no way for Pylance to know what `method2` refers to.

If you want to constrain `parameter` to contain only an instance of `Test2`, then you can specify this with a simple type annotation for `parameter`. Note that I've used quotes here because `Test2` is a forward reference.

```python
class Test1:
    def __init__(self, parameter: "Test2"):
        ...
```

With this small addition, Pylance now knows the type of `Test1.parameter`, and it can now determine that `self.parameter.method2` refers to `Test1.method2`.

**Comment by Ema0** [comment]
Understood thank you. So it doesn't do any type on inference based on the code (which in this case it would be: we are creating an instance of `Test1` by passing an instance of `Test2` as parameter so `self.parameter.method2() `is invoking method2 in `Test2`) other than type annotations?

So I guess for now I'll keep using Jedi then, as I cannot add type annotations everywhere in an existing codebase just to make PyLance `Go To Definition` functionality work...

**Comment by heejaechang** [comment]
we do but what you are describing is not the type inferring we do. 

we could make it work for the simple examples like you posted above, but in any real world code, it is not simple unless we track every instance of objects created in workspace. and that is what notebook or jedi do by actually running python code.

`pylance` is static analysis tool so we don't run any python code so it is not something we can provide.

For example, if you have `Test1`, `Test2`, `Test3` and `TestN` defined in multiple files, and each file created Test1 with itself (Test2, Test3, ... TestN)

```
def method1(self):
        if self.parameter:
            self.parameter.method2(True)  <= you don't know which TestN type this parameter is. 
```
