### ISSUE TITLE
Provide Pylance GitHub action similar to pyright-action

### ISSUE THREAD

**Issue by mjperrone** [microsoft/pylance-release#4927]
I am using Pylance for python type checking in VSCode. I am using pyright in my github action runs to make sure anything committed passes type checking.

I want to make sure that the version of pyright that VSCode is using is the same as the github action so they can be more likely to agree on what's wrong with the code they're both looking at.

EDIT: The proposed solution to my problem is for pylance to publish a github action using the pylance fork of pyright to type check files in a way that will be consistent with the behavior in the VSCode extension. EDIT 

-----

I'd like to do that by providing a pyright version number to Pylance in a configuration file that I can check into a repo. Perhaps in `vscode/settings.json`.

Another option is to expose config for the path to the `pyright` executable that pylance will use, so I make sure it's the same executable.

Related issues:

https://github.com/microsoft/pyright/discussions/5916
https://github.com/microsoft/pylance-release/discussions/3638

**Comment by rchiodo** [comment]
Thanks for the suggestion but there is no way to have a different Pyright than Pylance. Pylance doesn't run pyright, it injests the code from it. It's more like a fork of Pyright.

Your best bet is to follow Eric's advice on this issue here:
https://github.com/microsoft/pyright/issues/2035

Additionally, we've been discussing creating a Pylance github action to run against the released version of Pylance.

**Comment by mjperrone** [comment]
> Pylance doesn't run pyright, it injests the code from it.

Strange design choice from my perspective, but thank you for sharing this information.


My goal is definitely just to get a consistent development experience in VSCode and in the cli and in CI/CD, which _could_ be accomplished with a pylance github action.  Is there a ticket to track the pylance github action feature? I would love to be notified when that happens. 

> Your best bet is to follow Eric's advice on this issue here: https://github.com/microsoft/pyright/issues/2035

Every time I come back to this and try to search for the relevant issues, I find ~5 different issues/discussions/pull requests/readmes where there is conversation around this incompatibility and ideas for fixing it, but none are conclusive. While I appreciate the link, at this point I don't really have an appetite for reading through dense threads to pull out the relevant steps I need to take to correct this, since my last few attempts have taken a lot of time and lead me to failure.

Instead I'm just resigning myself to a bad developer experience (relying only on the CLI `pyright`) until a clear solution is available.

**Comment by rchiodo** [comment]
To summarize, Eric's advice was to either:

- Use the pyright extension instead of Pylance as it ships at the same time as Pyright CLI does. Although the Pyright extension is missing a bunch of stuff in Pylance.

or 

- Pin your CI system to a specific version and update it manually on some cadence.

Generally, Pylance and Pyright are pretty close (usually a week apart). It's only occasionally that Eric adds some new error check that they diverge, and then only for a week or so. 

Unfortunately, there's no visible ticket at the moment for a github action for Pylance, but it's good to know somebody would use it. @debonte, perhaps we should make the internal ticket public to see how many up votes it gets?

**Comment by erictraut** [comment]
I'll also note that there's [documentation](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md) that provides this information in a form that doesn't require you to read through a bunch of threads. Let us know if you think there are ways this documentation could be improved.

**Comment by rchiodo** [comment]
Actually, we can just make this item the item to publicly up vote.

**Comment by rchiodo** [comment]
Another idea here is to create a github action that runs the pyright CLI, but it runs the pyright that matches the current Pylance stable or prerelease version.

**Comment by rchiodo** [comment]
So using the action might look something like so:

```yml
jobs:
  pyright:
    runs-on: ubuntu-latest
    name: Pyright validate

    steps:
      - uses: actions/checkout@v3

      - uses: rchiodo/pyright-pylance-action@v3
        with:
          pylance-version: 'stable' <--- This can be 'stable' or 'prerelease'
          
```

**Comment by tylerlaprade** [comment]
Many developers, including myself, would greatly benefit from such an action. The original complaint is not about the Pyright version that Pylance uses, rather, it's the fact that the generally-accepted community Pyright action updates to a newer version about a week earlier than Pylance does, so there's a week of unexpected CI failure. The two workarounds, pinning the Pyright version in CI and switching to pre-release, both have potential concerns (a pin has to be manually updated every release, while pre-release exposes developers to potential bugs that would be caught by the time of release).

**Comment by debonte** [comment]
> Another idea here is to create a github action that runs the pyright CLI, but it runs the pyright that matches the current Pylance stable or prerelease version.

[pyright-action](https://github.com/jakebailey/pyright-action) and [pyright-python](https://github.com/RobertCraigie/pyright-python) now support this. You can tell them to use the Pyright version that matches the latest Pylance stable version, latest Pylance prerelease version, or a specific Pylance version. See [our docs](https://github.com/microsoft/pylance-release/blob/main/USING_WITH_PYRIGHT.md#pyright-version-and-pylances-underlying-pyright-version-are-different) as a starting point.

If there are other similar tools that you'd also like to support this behavior, please either let me know or ask the authors to contact me. I'd be happy to help them and/or document the underlying mechanism if needed.

**Comment by debonte** [comment]
@mjperrone, given that you gave this alternative approach a thumbs-up when Rich suggested it, I'm going to assume that this satisfies your needs and close this issue. Please let us know if you have any feedback on this approach.
