### ISSUE TITLE
The Highlighting doesn't work properly when the method has so too lines of code 

### ISSUE THREAD

**Issue by rescandonvov** [microsoft/pylance-release#4929]
## Environment data

-   Language Server version: v2023.10.10
-   OS and version: Mac Big Sur V 11.3.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.2

## Repro Steps

1. create a Python file
2. create any method
3. declare some variables within the method
4. create random blocks of code until it reaches approximately +1k lines of code. Inside these blocks of code, you should assign those variables previously declared
5. You should start to look at the issue that some declared variable isn't being accessed

## Expected behavior

Highlighting should work anyway 

## Actual behavior

Highlighting starts to fail 

## Logs

I turned on it but I didn't any relevant issue

**Comment by debonte** [comment]
I'm unable to repro this. Can you provide a source file that reproduces this issue? It will probably be too large to include in the comment text, but you should be able to drag it into a comment and provide it as an attachment.

A screenshot or video of the behavior that you're seeing would also be helpful.
