### ISSUE TITLE
How can I use this for abstract classes and decorators

### ISSUE THREAD

**Issue by bholland** [microsoft/pylance-release#493]
Hello all,

I love pylance. It has already fixed a few bugs. I have a question about implementing a few things with pylance. 
1. How do I use this within decorators (e.g., what is the type for a function and a class)?
2. How can I state that I am returning an instance that is determined by an abstract class?

For 2, this is quite paramount. I am trying to build out an interface that will define database access classes. Oracle and Postgres both have connection objects. How do I define that I am returning a connection object  in the interface or that an interface should return, say, a psycopg2 connection object? 

This also hits the __subclasshook__(cls, subclass). What do I define the subclass as?

**Comment by erictraut** [comment]
If you are using decorators that are defined by an existing library or the Python stdlib, these decorators will probably already have the appropriate type annotations. If you are defining your own decorators, here's [some document](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md#annotating-decorators) that will help you provide the proper type annotations.

If you are using abstract classes, simply use the abstract class in the type annotation. Here's an example:

```python
from abc import ABC, abstractmethod

class AbstractBase(ABC):
    @abstractmethod
    def bar(self) -> int:
        raise NotImplementedError

class Subclass1(AbstractBase):
    def bar(self) -> int:
        return 3

class Subclass2(AbstractBase):
    def bar(self) -> int:
        return 4

def func(val: int) -> AbstractBase:
    if val < 0:
        return Subclass1()
    else:
        return Subclass2()
```

Let me know if I've misinterpreted your questions.

**Comment by bholland** [comment]
I think there was a bit of a mixup. I have a decorator like this:

`def test_name(name: str) -> FunctionType:
def wrapper(f: str) -> FunctionType:
        f.__name__ = name
        return f
    return wrapper`

The decorator takes any function pointer and returns a function pointer. What is the type I should use for a function pointer?

Likewise, I have an interface like this:
`class DatabaseInterface(abc.ABCMeta):
    @classmethod
    def __subclasshook__(cls, subclass):
        return True

    @abc.abstractmethod
    def create_db_connection(self):
        return connection`

What is the type for the subclass? I haven't instantiated it yet so I can't know the type but I know that it is going to be a child of this class. It is the same problem with the connection. I want to state that the connection is the connection for the subclass. If my child class is, say, sqlite then I would want the sqlite connection class as the return type. If this were a postgres connection, then I would want to say it was a psycopg2 connection class object. Basically, for abstract classes, I can demand that a class implements the interface but can have specific and unique return classes depending on the implementation. I am almost looking for a template I guess like I would want a return of something like ConnectionObject[T] where T can be sqlite, postgres, oracle, etc. but I don't know what T is. 

BTW, is there a list anywhere of all of the possible types that pylance defines? This includes things like functions, classes, functions that don't return anything, functions that return multiple types depending on input, and the builtin types like arbitrary dictionaries, arrays, tuples, and more? A list of everything that you define would be hugely helpful.

**Comment by erictraut** [comment]
Decorators that accept any function and return that same function are an example of a "generic function", and they should be declared as such. Generic functions are declared using type variables ("TypeVar"). Please look at the documentation link in my answer above for detailed examples of how to annotate a decorator.

When you specify a class type in a type annotation, you are indicating that the type must be "assignable" to that type. Child classes are generally considered "assignable" to their base classes. If you look in my example above, `func` indicates that it returns an instance of `AbstractBase`, but it's actually returning either a `Subclass1` or `Subclass2`. This is allowed because these subclasses are both assignable to `AbstractBase`. Callers of `func` are guaranteed that they're receiving an instance that is compatible with `AbstractBase`.

Pylance doesn't define any types. Python defines a set of built-in types like `int`, `float`, `dict`, `tuple`, `list`, etc. These types and their attributes are defined in a set of "stub files" that are maintained in the `typeshed` repo. Pylance includes a copy of these stub (".pyi") files. If you click on a built-in type like `int` and press F12, the corresponding stub file will open in the editor, and you can see the definition.

**Comment by bholland** [comment]
I get what you did with the child classes. What I don't understand is how to define this in the abstract class. In your bar method, you return an int. I want to return a class-specific object. For example, I want the method bar to return a SqlLite.connection object for subclass 1 and a Postgresql.connection object for subclass 2. I want to define bar in the base class to return a connection object but I don't know how to specify that. 

In addition, how can I put func as a method for the AbstractBase in your code above? In my example, `def __subclasshook__(cls, subclass):` has cls as Type[DatabaseInterface]. What do I define subclass to be?

**Comment by erictraut** [comment]
It sounds like you want a generic class.

```python
_T = TypeVar("_T")
class DatabaseInterface(ABC, Generic[_T]):
    def connect(self) -> _T:
        raise NotImplementedError
```

If your connections have a common base class, you can bind the TypeVar to that base class.
```python
_T = TypeVar("_T", bound=ConnectionBase)
```

When you define your subclass, you would do so as follows:
```python
class SqliteConnection(DatabaseInterface[SqliteConnection]):
    ...

class PostgresInterface(DatabaseInterface[PostgressConnection]):
    ...
```

I don't recommend using `__subclasshook__`. It won't work for static type checking. You should simply declare your subclasses using a class declaration. Is there a reason you think you need to use `__subclasshook__`?

**Comment by bholland** [comment]
The reason for `__subclasshook__` is that I am worried about forcing subclasses to implement at least all methods in the base class. I read a bit about how abc works and many of them mention to implement it but I am okay dropping it. It was just interesting to think about what the class type would be if I needed it.

**Comment by savannahostrowski** [comment]
This issue has been open for 30 days and it seems that the above answer from our team was helpful so I'm going to close this. Feel free to let us know if this needs to be reopened.
