### ISSUE TITLE
Unable to autosuggest members with typing.Literal types when used in Generic classes

### ISSUE THREAD

**Issue by girip11** [microsoft/pylance-release#4938]
## Environment
Language Server version: v2023.10.11 (pre-release version)
OS and version: macOS 13.2.1 Ventura
Python version: 3.11.5

## Issue

Consider the below snippet.

```python
from typing import Any, Generic, Literal, TypeAlias, TypeVar

T = TypeVar("T", bound=str)

DS1FieldNames = Literal["col1", "col2", "col3"]


class GenericType(Generic[T]):
    def calculate(self, value: T) -> None:
        pass

    def __getattr__(self, value: T) -> Any:
        pass


ConcreteType: TypeAlias = GenericType[DS1FieldNames]

c = ConcreteType()
```
 In the above example, when I invoke the method `c.calculate()`, I get the field suggestion as in the image below.

<img width="760" alt="image" src="https://github.com/microsoft/pylance-release/assets/5471162/cf63b307-be8c-4fe9-a09e-9e5ced8468cd">

But when I type `c.`, I expected that the literal values should be populated in the list of attributes for the object c. But this wasn't the case.

If I change the signature of the `__getattr__`, it works as expected, as you could see in the image below.
<img width="818" alt="image" src="https://github.com/microsoft/pylance-release/assets/5471162/61f148fe-7b9d-4b65-aaaa-92986669de32">

**NOTE** - If I invoke the magic methods explicitly, the auto suggestion works. 
<img width="641" alt="image" src="https://github.com/microsoft/pylance-release/assets/5471162/dbcad7f4-8814-447b-80b7-8106b2919bc6">

This applies to the `__getitem__` method too. I assume this is the case for all the dunder methods overridden in the class.

I ran pyright against this code and it didn't complain, so I assume it passed the type checking rules. When I used the `reveal_type` for all these magic methods, pyright gave me the correct types.
<img width="985" alt="image" src="https://github.com/microsoft/pylance-release/assets/5471162/315f32ed-63aa-4347-a3e6-c9f5f56e050c">

Am I doing something incorrect here? Or currently such autosuggestions are not supported on magic dunder methods implemented using generic types? 

I am not sure if this would qualify for a feature request? Getting these members through auto suggestion helps greatly minimizing the member spelling lookups. Currently to make it work, I would need to duplicate the class implementation if I need to get the auto suggestions for different `typing.Literal` values.

**Comment by rchiodo** [comment]
Thanks for the issue. This looks like a bug to me. We have support for `__getattr__` but I don't believe we save the type argument for the TypeAlias as you've shown here.

**Comment by girip11** [comment]
Thanks so much for acknowledging. 

I will use this issue to document other related ones on the same snippet I have posted above. I have found similar issues with other magic methods like `__getitem__`, `__setitem__` too.

My expectation is that, the way Intellisense works for `calculate()` method, it should also work the same way for the magic methods.

**Comment by girip11** [comment]
Intellisense **DOES NOT** work for the `__getitem__`

```python
class GenericType(Generic[T]):
    def calculate(self, value:  T) -> None:
        pass

    # Intellisense DOES NOT work
    def __getitem__(self, value: T) -> Any:
        pass
```
Intellisense **WORKS** for the below signature of `__getitem__`

```python
class GenericType(Generic[T]):
    def calculate(self, value:  T) -> None:
        pass

    # Intellisense WORKS
    def __getitem__(self, value: DS1FieldNames) -> Any:
        pass
```

**Comment by girip11** [comment]
Intellisense **DOES NOT** work for the `__getitem__`

```python
class GenericType(Generic[T]):
    # intellisense works very nicely for this method
    # It autosuggests for both single value or when I pass a list of values
    def calculate(self, value:  T | list[T]) -> None:
        pass

    # Intellisense suggests only for DS1FieldNames but when I try to pass a list
    # it doesnt suggest anything.
    def __getitem__(self, value: DS1FieldNames | list[DS1FieldNames]) -> Any:
        pass
```

I will capture the screenshot so that its easier to understand. As you can see in the below image, intellisense works WELL for the `calculate` method
![image](https://github.com/microsoft/pylance-release/assets/5471162/0015278e-3090-4013-b8df-de803deb3d78)

Intellisense doesn't work for `__getitem__` when passing a `list`

![image](https://github.com/microsoft/pylance-release/assets/5471162/17acad8c-100e-4a18-a04e-2dbe4048dd20)

**Comment by erictraut** [comment]
There is currently no support for `__getattr__` in the completion provider logic. That's not a bug. It's just functionality that doesn't exist. A `__getattr__` method that limits its input to literal types is unusual, so the pylance team may want to wait for additional user feedback from users before deciding how to prioritize this request. Handling all of the edge cases for such a feature will be tricky because it would need to handle generics, overloads, and metaclasses. It will also need to distinguish between `__getattr__`, `__setattr__` and `__delattr__` depending on how the expression is used in the code.

The completion provider _does_ have support for a `__getitem__` method that limits its inputs to a literal type, but the current code doesn't currently handle generics or overloads. I've addressed both of these limitations. This will be included in the next release of pyright and pylance.

Here's how it looks with the new logic in place:

![image](https://github.com/microsoft/pylance-release/assets/7040122/f1034a95-aadf-4866-904e-b29c48a19941)

**Comment by girip11** [comment]
Thanks Eric. Regarding the `__getitem__` fix, could you confirm if it works for the signature `def __getitem__(self, value: T| list[T]):` and when I try to pass `c.[[""]]`. Previously it wasn't showing up in the auto suggestions.

On the `__getattr__` support, currently if I explicitly provide the parameter type, I do get the right value suggestions when I type `c.` . So I assumed its supported but only the support for generic type parameters was missing.

When it comes to `__getitem__`, we do have `__setitem__`  and `__delitem__`, so I thought if it autosuggests for `__getitem__`, then on the similar lines, `__getattr__` can also be supported.

**Comment by erictraut** [comment]
The logic works only with a `__getitem__` that accepts a literal type or a generic that is specialized to a literal type. It doesn't work for more complex types like `T | list[T]`. If you want that to work, please file a separate feature request, and the pylance team can prioritize it based on user feedback.

**Comment by girip11** [comment]
Thanks Eric. I will raise a new feature request and I will close this issue.
