### ISSUE TITLE
Stub folder should not be analyzed

### ISSUE THREAD

**Issue by apmadsen** [microsoft/pylance-release#495]
## Environment data

-   Language Server version: v2020.10.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.6 on VS Code 1.49.2
## Expected behaviour

I would expect Pylance, not to analyze files in the _typings_ folder, since these are merely stubs generated from 3rd-party code. I'm running Pylance with following settings:
```
# settings.json
{
    "python.analysis.typeCheckingMode": "strict",
    "python.analysis.diagnosticSeverityOverrides": {
        "reportImportCycles": "none",
        "reportPrivateUsage": "none",
        "reportUnusedVariable": "warning",
        "reportUnusedFunction": "warning",
        "reportUnusedImport": "warning"
    },
    "python.analysis.autoSearchPaths": true,
    "python.analysis.diagnosticMode": "workspace"
}
```
I've tried combinations of _python.analysis.autoSearchPaths_ and _python.analysis.extraPaths_ to try to force Pylance not to analyze the stubs folder, without any luck.

## Workaround

I've discovered, that using the good old _pyrightconfig.json_ file in conjunction with Pylance settings, gives you the ability to control which folders are analyzed, but you do lose the ability to do severity overrides, as these settings are then overridden
```
# pyrightconfig.json
{
  "include": [
    "src",
    "tests"
  ]
}
```

**Comment by erictraut** [comment]
You can use the `exclude` section of the pyrightconfig.json file.

Diagnostic severity settings are also supported in pyrightconfig.json, so you shouldn't lose any configurability.

**Comment by apmadsen** [comment]
I did already manage a workaround as I described (by using the pyrightconfig.json file), but that interferes with pylance severity overrides, which are no longer working. Furthermore, imo, it's counterintuitive to have the settings two places.

I think a good solution, on your side, might be to implement the include and exclude part from pyright.

**Comment by jakebailey** [comment]
I guess I'm confused; does putting the overrides into your config file not work? You should be able to set the overrides there. E.g. just put `"reportImportCycles": "none"` into the config, and it's used. Moving them leaves them still in one place.

See: https://github.com/microsoft/pyright/blob/master/docs/configuration.md#sample-config-file

**Comment by apmadsen** [comment]
I agree, and just tested that it does work, but I understood that Pylance was supposed to replace Pyright entirely, including the old pyrightconfig file, which is why I tried to move all config into the workspace settings of Pylance.

I'd still prefer to have everything in one place, but for now, of course, I can do with the workaround.

**Comment by jakebailey** [comment]
Nope, the config file is supported and necessary for some features.

**Comment by apmadsen** [comment]
Duly noted
