### ISSUE TITLE
The result of finding all references to the __init__ function is not correct

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/pylance-release#4954]
## Environment data
Build of Visual Studio Code - Insiders: 1.84.0-insider 
Build of python-insider: v2023.19.12841010 
Build of pylance-insider: v2023.10.21 

## Code Snippet

**test.py**
```
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

```
**file1.py**
```
from test import Person
person1 = Person("John", 25)
```
**file2.py**
```
from test import Person
person2 = Person("Alice", 30)
```
## Repro Steps
1.Open a new python file
2.Create a class in that python file with an init method.
3.Open two other python files
4.Import the first file in each
5.Create a variable by constructing the class in the two other files
6.Go back to the first file
7.Find all references on the init function
8.Verify it finds the same references as searching for the class name

## Expected behavior
![image](https://github.com/microsoft/pylance-release/assets/59192491/b11e93da-b563-4f0f-b9f5-fd6959c26440)

## Actual behavior
![image](https://github.com/microsoft/pylance-release/assets/59192491/90d74aed-c7d6-427c-97ab-a5eae5c55f59)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231031-18-October-2023-PreRelease)
