### ISSUE TITLE
"(" was not closedPylance

### ISSUE THREAD

**Issue by TyOpC** [microsoft/pylance-release#4956]
Having this problem, first time coding.
Already tried to Select Interpreter, but still the issue remains.
![Screenshot 2023-10-12 203102](https://github.com/microsoft/vscode-jupyter/assets/147756780/1270a278-e1a6-4a7a-800f-d6ef07307724)
![Screenshot 2023-10-12 203044](https://github.com/microsoft/vscode-jupyter/assets/147756780/afd1bc01-59c2-4105-ae1b-73097172fc46)

**Comment by rchiodo** [comment]
Yeah, that's invalid syntax. @erictraut do you think we could fix the error in this case to indicate they should add a ',' instead? The error is kind of misleading.

**Comment by erictraut** [comment]
It's tough to produce a better error message here because the intention isn't clear. Is it a missing `,`? A missing `:`? An extra space? The Python interpreter simply says "invalid syntax", which is arguably even less helpful than pyright's current error message.
