### ISSUE TITLE
Question: How can I get type hints from the stub file when I'm writing the corresponding code file?

### ISSUE THREAD

**Issue by Fau818** [microsoft/pylance-release#4962]
For example, I have a folder named `demo_project`.

I created two files, `demo.pyi` and `demo.py`, in the `demo_project` folder separately.

In `demo_project/demo.pyi`, there is the following code:

```python
def calc(a: int, b: int) -> int: ...
```

In `demo_project/demo.py`, there is the following code:

```python

def calc(a, b):
     return a + b

calc(|)  # | is the cursor
```

Pylance does not provide me the type hints which is written in the `demo.pyi` file.

<img width="259" alt="image" src="https://github.com/microsoft/pylance-release/assets/75115028/da9a81f7-fa8e-446a-8015-e9b4cb22b6b4">

---

Question: Is it possible to get type hints from `demo.pyi` when writing code in the `demo.py` file?

**Comment by erictraut** [comment]
This isn't how type stubs work. A type stub is a stand-in for a code file — typically used when the code is written in another language or when the maintainer of a library has not added type annotations to a file. If you are the author of a Python source file and want to use type annotations, you should add them directly to your code file.

**Comment by Fau818** [comment]
> This isn't how type stubs work. A type stub is a stand-in for a code file — typically used when the code is written in another language or when the maintainer of a library has not added type annotations to a file. If you are the author of a Python source file and want to use type annotations, you should add them directly to your code file.

I understand now. Thank you for your response.
