### ISSUE TITLE
There is no preview after renaming module

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#4964]
https://code.visualstudio.com/docs/python/editing#_rename-module

According to the document, there should be a pop up window every time I rename a file.

However, I didn't receive it. Is there any help?

My VSCode version is 1.83.1 and Pylance is v2023.10.20.

**Comment by ydmykr** [comment]
Related on Stack Overfolw: https://stackoverflow.com/questions/77295348/rename-python-file-but-pylance-not-finding-instances-and-refactoring

**Comment by rockallite** [comment]
It works in VSCode 1.83.1 with Pylance v2023.10.20 on macOS Sonoma 14.0. However it does not on Windows 10 22H2.

The latest Pylance version that works on Windows is v2023.10.10, including pre-releases.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.31, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231031-18-October-2023-PreRelease)

**Comment by wvenialbo** [comment]
I found this issue again in Pylance 2023.11.10. Rolling back to 2023.10.50 solve it.
