### ISSUE TITLE
extension.bundle.js detects as Trojan

### ISSUE THREAD

**Issue by intervisionlord** [microsoft/pylance-release#4967]
Related to https://github.com/microsoft/pylance-release/issues/2045 (new question because those issue was closed with suggestions to create a new one)

```
file: .vscode\extensions\ms-python.vscode-pylance-2023.10.20\dist\extension.bundle.js
sig: Trojan.Script.QBot.kblikv; Riskware.Script.Obfuscated.kcdfgx

file: .vscode\extensions\.5535db6a-7490-40c1-9942-044aa4c537ed\dist\sync.bundle.js
sig: Trojan.Script.QBot.kblikv; Riskware.Script.Obfuscated.kcdfgx

file: .vscode\extensions\ms-python.vscode-pylance-2023.10.10\dist\server.bundle.js
sig: Trojan.Script.QBot.kblikv; Riskware.Script.Obfuscated.kcdfgx

file: .vscode\extensions\ms-python.vscode-pylance-2023.10.10\dist\extension.bundle.js
sig: Trojan.Script.QBot.kblikv; Riskware.Script.Obfuscated.kcdfgx
```

**Comment by intervisionlord** [comment]
A new alerts today after removing previous files by AV:

```
.vscode\extensions\.bed44996-5aa2-4754-9049-f4f8f231b4ba\dist\sync.bundle.js
Riskware.Script.Obfuscated.kcdfgx

.vscode\extensions\.bed44996-5aa2-4754-9049-f4f8f231b4ba\dist\server.bundle.js
Riskware.Script.Obfuscated.kcdfgx

.vscode\extensions\.bed44996-5aa2-4754-9049-f4f8f231b4ba\dist\extension.bundle.js
Riskware.Script.Obfuscated.kcdfgx
```

**Comment by judej** [comment]
One option to fix this is to 
- run a gh action to check for malware: https://learn.microsoft.com/en-us/azure/defender-for-cloud/github-action, https://learn.microsoft.com/en-us/azure/defender-for-cloud/quickstart-onboard-github  
- based on if malware is found in the bundled files, then rerun the obfuscation with a new seed

**Comment by intervisionlord** [comment]
It’s not entirely clear how running the action on the GitHub platform will help fix the problem that when you try to update an extension, the antivirus complains about the downloaded files of this extension

**Comment by rchiodo** [comment]
Jude was talking about how we're going to fix the problem. The bytes in our obfuscated output are matching the signature used to identify the trojan. Obfuscation generates random hex values for the names of functions and occasionally we end up matching some series of bytes for a virus. One solution would be for us to check for this scenario and if it happens, redo the obfuscation.

**Comment by intervisionlord** [comment]
Thanks a lot for the explanation

**Comment by rocka0** [comment]
I just wanted to add on about my experience. I recently performed a full scan on my system and it seems pylance was somehow involved in what got flagged as a trojan:

<img width="758" alt="image" src="https://github.com/microsoft/pylance-release/assets/13283801/d35d7c08-e2ea-4170-a78c-745f2ad78194">

Should I be worried or this just a false positive?

**Comment by rchiodo** [comment]
It should be a false positive. We believe the obfuscated code is generating a byte pattern that matches some trojan. You can double check that you have the released version by installing it directly from the [marketplace ](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance).

**Comment by intervisionlord** [comment]
I tried to completely remove the extension from vscode and install the latest version from the store, and upon installation the antivirus complaint occurs again

**Comment by debonte** [comment]
This was fixed by https://github.com/microsoft/pyrx/pull/5467/files#r1676259192. Our build will now fail (and need to be re-run) if Windows Defender finds a threat in our VSIX.

**Comment by ruppde** [comment]
@debonte  Why do you obfuscate the files at all?

**Comment by debonte** [comment]
@ruppde, because Pylance is closed source.
