### ISSUE TITLE
Add support for "Show super type Hierarchy" command

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#4978]
### Discussed in https://github.com/microsoft/pylance-release/discussions/2848

<div type='discussions-op-text'>

<sup>Originally posted by **debonte** May 24, 2022</sup>
Support for type hierarchy is new in [LSP 3.17](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/).

https://github.com/microsoft/vscode/issues/126666 shows what the UX looks like in Java.

![image](https://user-images.githubusercontent.com/45906942/122543697-a2b1da00-d05e-11eb-9359-e2bbc0761edf.gif)</div>

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.11.13, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231113-15-November-2023-PreRelease)

**Comment by nnop** [comment]
Does this feature support all languages?

**Comment by debonte** [comment]
Pylance supports all the [languages that VS Code supports](https://code.visualstudio.com/docs/getstarted/locales#_available-locales) except for Hungarian.
