### ISSUE TITLE
Handle `sys.path.append` for more convenience

### ISSUE THREAD

**Issue by p-avital** [microsoft/pylance-release#498]
Hello there,

A rather common pattern in my teams is the use of `sys.path.append(os.path.dirname(__file__))` in the entry point to ensure the libs are accessible for imports.

This is a rather easy pattern to find, do you think this could be used to add some folders to the PYTHON_PATH Pylance considers ? This would be useful when the entry point is not located at the workspace's root :)

It is a bit hacky though, so I'd understand if you don't want to do it

**Comment by vegetable09** [comment]
@p-avital  That's really useful! 

And for me,  `from dirA.util import xxx` is also a common pattern

my_project
|--dirA
|     |__util.py
|--dirB
|__main.py

**Comment by erictraut** [comment]
@p-avital, a static type checker cannot handle dynamic changes to system paths. If you are interested in using the functionality provided by a static type checker, you should avoid using this technique.

@vegetable09, this should already work find. If you see a specific problem, please file a separate issue. Thanks!

**Comment by jakebailey** [comment]
Yeah, this would be a hack; this is a bit more evaluation that I think we're comfortable with.

Also see #253, since it seems like you're talking about scripts (which natively have this "add the script's folder to `sys.path` behavior).
