### ISSUE TITLE
Unable to use methods from sqlalchemy

### ISSUE THREAD

**Issue by abhinay181** [microsoft/pylance-release#4981]
@jakebailey @debonte 
I am unable to access methods from sqlalchemy package. I have installed the package successfully you can see it in the below screenshot I have run the pip list command to show that sqlalchemy is installed

![new 2](https://github.com/microsoft/pylance-release/assets/85485413/035a6bad-63da-400b-aff2-fed2d437ede3)
![new 3](https://github.com/microsoft/pylance-release/assets/85485413/b4877aaa-a16e-4082-8acd-af88832656d8)
![new 4](https://github.com/microsoft/pylance-release/assets/85485413/c82d5b4a-5382-44a8-881f-32da364da21c)

**Comment by abhinay181** [comment]
@bschnurr 

Can you help me with this issue? I am no able to figure out

**Comment by debonte** [comment]
@abhinay181, as I said in response to your comment on #757, this is a runtime issue. Please ask your question over at the sqlalchemy repo -- https://github.com/sqlalchemy/sqlalchemy/discussions. We are not experts on SQLAlchemy.
