### ISSUE TITLE
No code completion or renaming for SimpleNamespace objects

### ISSUE THREAD

**Issue by DervishD** [microsoft/pylance-release#4984]
**I could not report this bug using the `Issue Reporter` because I kept receiving a 401 error and I cannot determine why, sorry.**
On the code below:
```
from types import SimpleNamespace
from enum import IntEnum

testNS = SimpleNamespace()
testNS.MEMBER = 1

class testIE(IntEnum):
    MEMBER = 1

print(testNS.MEMBER)  # No completion was offered after the dot, and MEMBER cannot be renamed.
print(testIE.MEMBER)
```
## Expected vs. Actual

I expected completion to be offered after `print(testNS.`, just as it is offered after `print(testIE.`.

I expected to be able to rename `MEMBER` in  the line `testNS.MEMBER = 1`, just as I can rename `MEMBER` in line `MEMBER = 1`

None of that happens, looks like refactoring and completion do not work for SimpleNamespace. I can understand why completion does not work, as the attributes are created on the fly at runtime, but renaming (refactoring) should.

## Steps to reproduce:

1. Put the cursor after `print(testNS.` and wait.
2. Try to rename `MEMBER` in line `testNS.MEMBER = 1` using F2 or right-click->Rename

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2023-10-19 13:05:20.605 [info] Experiment 'pythonPromptNewFormatterExt' is active
2023-10-19 13:05:20.605 [info] Experiment 'pythonPromptNewToolsExt' is active
2023-10-19 13:05:20.605 [info] Experiment 'pythonSurveyNotification' is active
2023-10-19 13:05:20.605 [info] Experiment 'pythonTestAdaptercf' is active
2023-10-19 13:05:20.605 [info] Test server listening.
2023-10-19 13:05:20.605 [info] Python interpreter path: C:\Program Files\Python311\python.exe
2023-10-19 13:05:20.673 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-19 13:05:20.673 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-19 13:05:20.673 [warning] Retry failed, storage update failed for key PYTHON_WORKSPACE_STORAGE_KEYS
2023-10-19 13:05:21.483 [info] > conda info --json
2023-10-19 13:05:23.255 [info] Starting Pylance language server.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

testing
• pytestEnabled: true

```

</p>
</details>

**Comment by DervishD** [comment]
Thanks a lot for the advice @erictraut 😄  In fact in the real code that I was writing when I discovered this I was using a `StrEnum`. I started using a SimpleNamespace because it looked better suited for the task. I will probably go back to a StrEnum.

I agree completely with you regarding completion, as I mentioned in the bug report. I assume it is something that a static analyzer just cannot do. But my main cause of concern, though, is not being able to rename the members, because I thought that was well into the capabilities of a static code analyzer.

**Comment by StellaHuang95** [comment]
We might be able to support code completion by implementing similar logic as we do for dictionary key completion support. We handle it by finding the assignment that declares local variable with `SimpleNamespace` and then collecting the attributes.

**Comment by DervishD** [comment]
Good idea, @StellaHuang95 thanks a lot! Anyway, my main source of concern is renaming/refactoring. Code completion is great but I use it only when first writing the code, and refactoring (renaming variables, etc.) it is used during all the time a project is maintained.

**Comment by StellaHuang95** [comment]
Thank you for bringing up this issue. Currently, Pylance does not support the mentioned refactoring. There's a related discussion about auto completion suggestions as an enhancement request. Please upvote https://github.com/microsoft/pylance-release/discussions/2630 if you'd like to see it being supported. Thank you for your understanding!
