### ISSUE TITLE
Persistent "Pylance as default Python language server" message on VSCode Start

### ISSUE THREAD

**Issue by angelhdz** [microsoft/pylance-release#499]
## Environment data

-   Language Server version: v2020.10.1
-   OS and version: Windows 10 Pro 10.0.19041 Build 19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0

## Expected behaviour

Pressing the button to set Pylance as default language server should mark Pylance as default language server and never show the message again.

## Actual behaviour

The message shows up every time I open VSCode.
![image](https://user-images.githubusercontent.com/10191085/96375060-be1dbb80-1144-11eb-929f-7717938bdcca.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by savannahostrowski** [comment]
Hey @angelhdz! Can you tell me if you have `python.languageServer:"Pylance"` set at the workspace or user level? Could you also check/provide a screenshot of the settings UI for `python.languageServer`?

**Comment by jakebailey** [comment]
I believe this should be fixed; this prompt now will stay hidden if "no" is clicked.
