### ISSUE TITLE
Pylance auto-completes and imports when typing function definition

### ISSUE THREAD

**Issue by JosuaKrause** [microsoft/pylance-release#4994]
## Environment data

-   Language Server version: v2023.10.41
-   OS and version: MacOS Sonoma 14.0
-   Python version (& distribution if applicable, e.g. Anaconda): miniconda 3.11.6

## Code Snippet / Repro Steps

When defining a method/function it auto-completes and imports automatically from the suggestions upon entering `(`

Typing the name:
```python
class A:
    def h
```
Typing more of the name:
```python
class A:
    def hdel
```
Pressing `(`:
```python
from torchaudio.models import hdemucs_low

class A:
    def hdemucs_low(
```

(requires torchaudio to be installed to get the exact same response. but it could be any library function really that matches)

## Expected behavior

I don't expect pylance to autocomplete any function/method definition. Especially not with an unrelated import that would be shadowed by the definition anyway.

The most I would expect would be if it autocompleted method names from the class hierarchy which it doesn't do at all (when subclassing the method names of the parent class don't appear anywhere).

Also, I would expect autocomplete to trigger on `Enter` not on `(`.

## Actual behavior

It autocompletes and imports whatever function is at the top of the suggestion list at the time when pressing `(`.

## Logs

logs are too long for github...

**Comment by heejaechang** [comment]
`auto import complete` is off by default. I think you enabled it. if you disable it back, that won't happen.

![image](https://github.com/microsoft/pylance-release/assets/1333179/0b562049-af55-46b7-b2f4-b5ba5eaf2c55)

**Comment by JosuaKrause** [comment]
I do want auto complete. But I'm this firm it doesn't make any sense. Why would it auto complete when *writing a function definition*?

**Comment by rchiodo** [comment]
It does seem weird that we'd trigger on '('? I don't see that explicitly in our code, so maybe VS code is auto triggering on '('?

**Comment by JosuaKrause** [comment]
Hmm, pylance is producing logs on the key press. I didn't post them here because they are too long for a comment/pr description but maybe I can upload them elsewhere. I'll have a look though and check what event is triggering the autocomplete.

That said, I still don't understand why auto completing anything in a function name definition is desired behavior? It will import a symbol that is in 100% of cases immediately shadowed by the newly defined function (except for methods).
