### ISSUE TITLE
Errors don't disappear from deleted files.

### ISSUE THREAD

**Issue by SplatTab** [microsoft/pylance-release#4999]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: Errors should not show from deleted files
Actual: Errors remain even after a file is deleted

## Steps to reproduce:

1. Create a new file any name doesn't even have to be a .py file if VSCode recgonizes it as python it will happen
2.  Put in code that will trigger an error ex:
```
def main():
    ERROR
  print();
```
3. Delete the file
4. View problems panel notice the code does not disappear

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): MicrosoftStore
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.18.0
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700G with Radeon Graphics          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.38GB (1.98GB free)|
|Process Argv|--crash-reporter-id f15cdb97-9057-4567-aaa3-453e30a4bbe7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pyreplss1:30865275
h48ei257:30869481
pythontbext0:30864172

```

</details>

**Comment by rchiodo** [comment]
Hmm, it doesn't reproduce for me. 

Oh, it only reproduces on stable. It seems this is fixed in our latest prerelease - 2023.10.41

**Comment by sjhsbhqf** [comment]
I encountered this issue when using the cursor. However, by disabling and then restarting the extension, i can refresh and clear out the error messages.

Cursor
Version: 0.44.11
VSCode Version: 1.93.1

Pylance
Id: ms-python.vscode-pylance
Description: A performant, feature-rich language server for Python in VS Code
Version: 2024.8.1
Publisher: ms-python
VS Marketplace Link: https://marketplace.cursorapi.com/items?itemName=ms-python.vscode-pylance

**Comment by rchiodo** [comment]
@sjhsbhqf cursor is not a supported IDE. Your version of pylance is the one with this issue.
