### ISSUE TITLE
"variable" is not accessed when it is used by `locals()`

### ISSUE THREAD

**Issue by qria** [microsoft/pylance-release#500]
## Environment data

-   Language Server version: v2020.10.1
-   OS and version: Microsoft Windows 10 Pro 10.0.19041 Build 19041
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.6

## Expected behaviour

Pylance should pick up that variables are accessed when `locals()` use them.

## Actual behaviour

Pylance does not evaluate local variables as accessed.

## Logs

There were no relevent logs out of the trace.

## Code Snippet / Additional information

```python
from typing import Any, Dict

def foo() -> Dict[str, Any]:
    a = 1  # "a" is not accessed Pylance
    return locals()
```

**Comment by erictraut** [comment]
This behavior is intended. There is no explicit reference to `a`.

By default, Pylance doesn't emit any error for unaccessed variables. If you are using strict type checking mode or have explicitly configured it to emit an error for the `reportUnusedVariable` diagnostic rule, you can use a `# type: ignore` comment on that line or a `# pyright: reportUnusedVariable = false` comment at the top of the file to suppress the error in this particular case.

**Comment by qria** [comment]
Thanks for the explanation. I will close the issue.
