### ISSUE TITLE
Pytest add fixture type annotation code action shows up for non test files

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#5003]
## Code Snippet

```python
# test_1.py
def test_foo(myFixture, capfd, cache):

# file_1.py
def test_foo(myFixture, capfd, cache):
```

## Expected behavior

The `pytestAddFixtureTypeAnnotation` code action (the light bulb) only appears in `test_1.py`

## Actual behavior

The `pytestAddFixtureTypeAnnotation` code action (the light bulb) appears in both `test_1.py` and `file_1.py`.

The code action in `file_1.py` also fails to add type annotations.

![pytest](https://github.com/microsoft/pylance-release/assets/100439259/d0240c70-2f54-45b7-9cb3-49c99068465f)

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.10.51, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231051-26-October-2023-PreRelease)
