### ISSUE TITLE
Pylance report problems with softlink path that cause Error lens dont shows error msg.

### ISSUE THREAD

**Issue by birdhackor** [microsoft/pylance-release#5010]
## Environment data

-   Language Server version: 2023.10.41 (pyright cfe56bfb)
-   OS and version: Windows 10 local + Debian 11 (bullseye) remote
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Repro Steps

Create new python file at home folder, open folder in vscode, choose python file and type some code that should have warning. Ex:

``` python
s: str = 1
```

## Expected behavior

With pylance and error lens, problem msg should should show next to code like this

![](https://raw.githubusercontent.com/usernamehw/vscode-error-lens/master/img/demo.png)

## Actual behavior

Pylance report problem with absolute path like example below, and VSCode tab shows file path for opened file is `~/project/web/backend/main/monitor/routers.py` . Error lens doesn't think that problem msg is for the tab so it does not show problem msg next to code.

I have to click the problem msg to open same file in absolute path mode to get Error lens show problem msg next to code.

```
[{
	"resource": "/home/birdhackor/project/web/backend/main/monitor/routers.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportGeneralTypeIssues",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportGeneralTypeIssues"
		}
	},
	"severity": 8,
	"message": "Expression of type \"Literal[1]\" cannot be assigned to declared type \"str\"\n  \"Literal[1]\" is incompatible with \"str\"",
	"source": "Pylance",
	"startLineNumber": 147,
	"startColumn": 15,
	"endLineNumber": 147,
	"endColumn": 16
}]
```

**Comment by birdhackor** [comment]
## Key issue in pre-release version

I fount out that key problem is softlink path.

Here is my test:

<img width="782" alt="CleanShot 2023-10-27 at 02 34 11@2x" src="https://github.com/microsoft/pylance-release/assets/1615229/15be3f1b-e669-4005-91b1-35c989304235">

test.py is fine:
![CleanShot 2023-10-27 at 02 38 10@2x](https://github.com/microsoft/pylance-release/assets/1615229/02fb6781-f1b1-4a4e-9e64-0b1ee24cff17)

But test2.py is not OK:
![CleanShot 2023-10-27 at 02 41 04@2x](https://github.com/microsoft/pylance-release/assets/1615229/e92d87f3-96d2-44cf-9f83-72466a16f757)

And test3.py also not OK:
![CleanShot 2023-10-27 at 02 42 27@2x](https://github.com/microsoft/pylance-release/assets/1615229/95a257f9-7897-4628-94e1-a7313a4279fc)

If I click the problem msg to open same file in original path, Error lens will work properly.
![CleanShot 2023-10-27 at 02 43 45@2x](https://github.com/microsoft/pylance-release/assets/1615229/429f8d34-7802-4fbd-a43e-9d9bdaf3636d)

## Current release version (v2023.10.40) is fine!!

![CleanShot 2023-10-27 at 02 50 10@2x](https://github.com/microsoft/pylance-release/assets/1615229/51930043-d055-474b-9fd5-81006c497729)

**Comment by rchiodo** [comment]
This sounds more like a symbolic link issue to me? We real path everything and then turn it back into a URI. I think that's what's messing this case up.

**Comment by heejaechang** [comment]
This is a dup of other issues where we didn't use original uri but generated new uri that are different than the original uri that points to the same file

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/issues/5030
