### ISSUE TITLE
Python code navigation in PyCharm vs VSCode

### ISSUE THREAD

**Issue by afsay** [microsoft/pylance-release#5022]
I use VSCode with Python and Pylance extensions. Basic navigation works fine, however when code involves references from function parameters code navigation doesn't work.

For example following scenario works in PyCharm but doesn't work in VSCode. In the code below when I Ctrl+click parent_b_func1 on ins_B.parent_b_func1(A()) it is able to locate the function definition. However when I do Ctrl+click parent_a_func1 on param_a.parent_a_func1() it cannot locate the definition.
```python
class ParentA(object):
    def parent_a_func1(self):
        print("Hi!")


class A(ParentA):
    def a_func1(self):
        pass


class ParentB(object):
    def parent_b_func1(self, param_a):
        param_a.parent_a_func1()
        pass


class B(ParentB):
    def b_func1(self, ):        
        pass


ins_B = B()

ins_B.parent_b_func1(A())
```
- Windows 10 Enterprise, 21H2, 19044.3570
- VSCode version 1.83.1
- Python extension version v2023.18.0
- Pylance extension version v2023.10.50
- Python 3.9.13
[pylance_trace_output.txt](https://github.com/microsoft/pylance-release/files/13187944/pylance_trace_output.txt)

**Comment by afsay** [comment]
if I do

```python
class ParentB(object):
    def parent_b_func1(self, param_a : A):
        param_a.parent_a_func1()
        pass
```
it works, but I am curious if Pylance have a way of doing it automatically like PyCharm do.

**Comment by COOLIRON2311** [comment]
Pylance performs static type analysis, and yet what you have here is a kind of type-deduction-by-usage dirty hack that JetBrains decided to implement for some reason.

Also, since Python 3 you don't have to inherit from object for all your custom classes.

**Comment by afsay** [comment]
Thanks for clarification!
