### ISSUE TITLE
the function of highlighting

### ISSUE THREAD

**Issue by husterWL** [microsoft/pylance-release#5023]
## Environment data

-   Language Server version: pylance 10.50
-   OS and version: win11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12

## Code Snippet

```python
import torch
import XXXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

it can't highlight my code splits, it looks a little awkward.

## Logs

```
XXX
```

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
