### ISSUE TITLE
Type analysis of Django seems to be configured somehow differently

### ISSUE THREAD

**Issue by lexicalunit** [microsoft/pylance-release#5027]
## Environment data
-   Language Server version: v2023.18.0
-   OS and version: macOS 13.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.17
-  Pylance Version: v2023.10.50

## Code Snippet
```python
from django.db import models

class MyModel(models.Model):
    nullable = models.IntegerField(null=True)

def foo():
    m = MyModel.objects.get()

    def accepts_only_int(x: int):
        pass

    accepts_only_int(m.nullable)
```

In VSCode via pylance I get the error:

```
Argument of type "int | None" cannot be assigned to parameter "x" of type "int" in function "accepts_only_int"
  Type "int | None" cannot be assigned to type "int"
    Type "None" cannot be assigned to type "int"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
(variable) nullable: int | None
```

But if I run `pyright` against this source code I get no errors:
```log
➜ PYRIGHT_PYTHON_FORCE_VERSION=latest pyright monolith/models.py
0 errors, 0 warnings, 0 informations
```

I have `django-stubs==4.2.6` installed.

So `pylance` is doing something weird with Django... there must be something else installed or something else configured that allows it to know that `nullable` is a nullable column and thus could be `None`.

I'd like to know what that something is. 🙏🏻

**Comment by rchiodo** [comment]
Thanks for the issue. This is happening because Pylance ships different stubs than django-stubs. Django-stubs aren't actually compatible with Pylance as they use mypy extensions to provide type information. We actually use the stubs here:
https://github.com/sbdchd/django-types. 

You should probably use the django-types stubs if you're going to be running Pyright.

**Comment by erictraut** [comment]
Is pylance allowing its bundled stubs to take precedence over stubs installed in the Python environment? If so, that seems to me like a bug. It violates the resolution order specified in [PEP 561](https://peps.python.org/pep-0561/). It says that stub libraries installed in the Python environment should take precedent over any bundled stubs (like typeshed).

**Comment by lexicalunit** [comment]
@erictraut Maybe it's because `pyright` doesn't even recognize that `django-stubs` is a thing, so it doesn't see that there are "stubs installed in the Python environment" in the first place? And in that case it falls back to its own stubs, which are the `django-types` ones.

**Comment by erictraut** [comment]
> Maybe it's because pyright doesn't even recognize that django-stubs is a thing

I can confirm that pyright uses the stubs in `django-stubs` if that stub package is installed in the environment.

**Comment by lexicalunit** [comment]
Interesting... I assumed that @rchiodo's comment meant that pyright didn't use `django-stubs`:

> Django-stubs aren't actually compatible with Pylance as they use mypy extensions to provide type information.

Maybe some of the stubs work but not all of them? Regardless, if pyright is using _any_ of `django-stubs` then yes it does seem like `pylance`'s bundled stubs are overriding it.

**Comment by rchiodo** [comment]
Yeah it does seem like we use the bundled stubs over the installed ones. That seems like a bug.
