### ISSUE TITLE
Pylance 2023.10.50 (pyright cfe56bfb) crashes on displaying symbols in debug console (in jupyter)

### ISSUE THREAD

**Issue by MichaelXt** [microsoft/pylance-release#5036]
<h3> Environment data </h3>

-   Language Server version: 2023.10.50
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): python 3.12 conda
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Repro Steps </h3>
gif for repro with the sample min code:

![pylance](https://github.com/microsoft/pylance-release/assets/8294558/e520318e-91e1-410f-8fe6-fe7aea37e636)

run cell under debugger. type in variable name in the debug console, press enter.

Expected: the variable value is printed.

Actual: the debugger crashes.

Note: the previous version of pylance works correctly without a crash

**Comment by debonte** [comment]
@MichaelXt, it's not clear to me how this is related to Pylance. Did you mean to file this issue against debugpy?

If Pylance is crashing, can you please provide the contents of the "Python Language Server" log?

**Comment by MichaelXt** [comment]
@debonte, The issue appeared when pylance extension was updated to 2023.10.50 version. Reverting it back solved the issue. If the issue is related to debugpy, corresponding reasoning is needed, and the issue can be transferred.

**Comment by debonte** [comment]
I'm unable to reproduce this.

@int19h, any idea how this could be related to Pylance? Or how the user can collect more information for us? I tried enabling debugpy logging via the `DEBUGPY_LOG_DIR` environment variable, but didn't see any logs generated.

**Comment by debonte** [comment]
I talked with Pavel offline and he said:

> I don't see how Pylance could possibly be related here. It's more likely that user has also updated Jupyter and now there's some kind of conflict there.
> 
> For logs, the problem usually is that the env var is set in the wrong context - it needs to be visible to all processes from which you want to collect logs. For best results I set it for both VSCode (and thus everything it spawns, including the debug adapter) and also the debuggee. But I'm not sure how exactly that works in case of Jupyter when running from VSCode; i.e. if the env vars are propagated there when spinning it up.
> 
> If that is the case, it should also be possible to do import debugpy; debugpy.log_to("...") from the notebook itself to the same effect.

**Comment by debonte** [comment]
@MichaelXt, can you please enable debugpy logging as described [here](https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs#logging-using-environment-variables), reproduce the crash, and then provide the resulting log files?

I did this on my Ubuntu machine by adding the following to my `/env/environment` file and then logging out and back in again. Not sure if this is the best way to do it, but it worked :)

```text
DEBUGPY_LOG_DIR="/home/erikd/temp/debugpylogs"
```

**Comment by MichaelXt** [comment]
Just got back to that issue. Updated to latest pylance and other extensions - no issue anymore. Probably was some mismatch in extensions. Now everything works as expected.
