### ISSUE TITLE
Understand type based on __class__

### ISSUE THREAD

**Issue by emj1991** [microsoft/pylance-release#505]
Pylance understands types in if statements based on `isinstance()` but doesn't apply the same logic when comparing `__class__` of two objects.

## Environment data

-   Language Server version: v2020.10.1
-   OS and version: OSX 10.15.4
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6

## Expected behaviour

In this simple example, Pylance correctly detects that everything is ok based on the type check from `isinstance()`
![image](https://user-images.githubusercontent.com/3459761/96511681-3dc68b80-1214-11eb-8b89-5b01163e32d1.png)

I would expect the same from this statement:
![image](https://user-images.githubusercontent.com/3459761/96511770-5cc51d80-1214-11eb-880d-fc2a9b01bd6f.png)

## Actual behaviour

Pylance does not understand that the object "other" must be of the same class and therefor have the same functions/properties.

**Comment by erictraut** [comment]
I don't think this pattern is sufficiently common to justify special-case type narrowing. It's also not clear how it would generalize to union types, etc. I recommend using either an `assert` or a `cast` as a workaround.

**Comment by emj1991** [comment]
To be fair, this is the __eq__ pattern generated by the dataclass under the hood.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
