### ISSUE TITLE
Regular expression not highlighted correctly unless with `rf` prefix

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/pylance-release#5050]
Type: <b>Bug</b>

# Behaviour
write the following in a python file, I expect all strings with `r` as prefix to be rendered as regular expressions (red with blue highlight), and all with `R` as raw strings (orange with no highlight). the actual behavior is that only `rf` is rendered as regular expression
```python
"D:\nexus"
Rf"D:\nexus"
rf"D:\nexus"
R"D:\nexus"
r"D:\nexus"
```
![image](https://github.com/microsoft/vscode-python/assets/14952735/6ff6607b-c686-44d8-9bcd-d2b39cacf851)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

formatting
• provider: "black"

```

</p>
</details>

Extension version: 2023.18.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.15.0-208-generic
Remote OS version: Linux x64 4.15.0-208-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (13.14GB free)|
|Process Argv|--crash-reporter-id 5256b527-2907-4999-af58-0cda0ec119d8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.214.241.16|
|OS|Linux x64 4.15.0-208-generic|
|CPUs|Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (72 x 1045)|
|Memory (System)|251.42GB (205.17GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.214.241.16|
|OS|Linux x64 4.15.0-208-generic|
|CPUs|Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (72 x 1045)|
|Memory (System)|251.42GB (205.29GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30866041
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythontestfixtcf:30866406
pyreplss1:30865275
h48ei257:30866288
pythontbext0:30864172

```

</details>

**Comment by StellaHuang95** [comment]
The coloring is handled by the tmlanguage file that VS code ships for Python so could be a bug in textmate. https://github.com/microsoft/vscode/blob/main/extensions/python/syntaxes/MagicPython.tmLanguage.json

**Comment by sparr** [comment]
This is fixed in MagicPython but hasn't made it into the VSCode Python extension yet.
https://github.com/MagicStack/MagicPython/commit/5b5f388fc46e45dff7e48edc90242c7f578d8705

**Comment by StellaHuang95** [comment]
Hi there, thanks for the issue. I am going to close this specific issue but categorizing it as a sub-item of a larger effort - (shipping textmate grammar ourselves - https://github.com/microsoft/pyrx/issues/4026)

Please note that we are currently resolving TextMate issues as external bugs. However, we're also considering maintaining and shipping our own grammar and fix any issues ourselves. The work has not started yet and it's probably better owned by vscode-python rather than Pylance. Once the work is assigned to a team, we will create an issue either in vscode-python or pylance-release for public tracking. Thank you for your understanding!
