### ISSUE TITLE
Can't not use code highlight/reference suddenly

### ISSUE THREAD

**Issue by RickyYXY** [microsoft/pylance-release#5051]
By the way your issue submission module in vscode is not working...

I just suddenly find out that
All the code became in white, the lib is not shown in different color.
When I refer to a variable, it just stuck, can't get any result.
I try to set the Language sever to Pylance and restart vscode, but it didn't work.

Please check out for this, thks.

**Comment by RickyYXY** [comment]
And it works well when I use vscode linking to remote ssh server, which is strange.

**Comment by RickyYXY** [comment]
The versions of python, pylance, and black-formatter extensions are all 2023.18.0, 2023.10.50, and 2023.4.1. I think they are all the newest. The versions on my remote ssh server are the same.

**Comment by dc8866** [comment]
I have the same issue. Downgrading the pylance extension to v2023.10.40 is a temporary fix I am using,

**Comment by RickyYXY** [comment]
> I have the same issue. Downgrading the pylance extension to v2023.10.40 is a temporary fix I am using,

Thks so much, I solved the problem by doing the same. Pylance needs to be fix.

**Comment by rchiodo** [comment]
This is likely this issue here: https://github.com/microsoft/pylance-release/issues/5037. Please try upgrading to 2023.10.53

**Comment by radove** [comment]
upgrading to pre-release 2023.10.53 fixed this issue for me
