### ISSUE TITLE
Improperly reported 'GeneralTypeIssue' regarding Python string comparisons

### ISSUE THREAD

**Issue by ElijahSink** [microsoft/pylance-release#506]
## Environment data

-   Language Server version: v2020.10.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6

## Expected behaviour

No lint error raised.

## Actual behaviour

`Operator "in" not supported for types "bool" and "Literal['1']"Pylance (reportGeneralTypeIssues)`
## Logs

```
N/A
```

## Code Snippet / Additional information

```python
"1" == "1" in "1"    // error
"1" == "1" in ["1"]  // no error
```
It's clearly valid syntactically and semantically, as demonstrated here:
```
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "1" == "1" in "1"
True
```
and in the [docs](https://docs.python.org/3/reference/expressions.html#comparisons).

**Comment by erictraut** [comment]
Thanks for the bug report. You uncovered a rare bug in the parser. It was not honoring the order of precedence for chained logical comparisons. (The "in" and "not in" operators are considered the same as logical comparisons in terms of precedence.) The parser was interpreting the first line as `("1" == "1") in "1"` when it should have been interpreting it as `"1" == ("1" in "1")`. 

If you're curious about the fix, here's [the commit](https://github.com/microsoft/pyright/commit/abea3f1c531098128edb9215730dce5adc7fbd2f).

The fix will be included in the next release of Pylance.

**Comment by ElijahSink** [comment]
Excellent, thanks!

I'm curious what you mean when you say there was a mistake in the application of precedence rules, since my understanding from the docs was that "all comparison operations in Python have the same priority." 

Could you elaborate on that?

**Comment by erictraut** [comment]
You're correct that all comparison operators in Python have the same priority, but comparison operators have a different priority than other classes of binary operators, and the parser needs to honor those precedence rules.

For full details, refer to the official [Python grammar](https://docs.python.org/3/reference/grammar.html). Search for "in_bitwise_or". At first reading, the grammar would seems to indicate that parser should expect a `bitwise_or` on the right-hand side of a comparison operator, which is how I initially coded it. That results in left associativity. I should have looked at "compare_op_bitwise_or_pair", which clearly indicates that a comparison operator has right associativity.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.10.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020102-21-october-2020

**Comment by paulober** [comment]
I still got this error with the newest version of the extension: `Operator "==" not supported for types "str" and "Literal['__main__']"
  Operator "==" not supported for types "str" and "Literal['__main__']"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)`

**Comment by erictraut** [comment]
@paulober, this bug has been closed for almost two years. If you are seeing a similar issue, it's unlikely the same as this one. Please open a new issue and provide a self-contained minimal code sample that demonstrates the behavior you're seeing.
