### ISSUE TITLE
unittest assertIn doesn't recognize __contains__

### ISSUE THREAD

**Issue by davetapley** [microsoft/pylance-release#5061]
<h3> Environment data </h3>

-   Language Server version: 2023.10.50
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
class a(object):

    d = 'ddd'

    def __contains__(self, m):
        if self.d: 
            return True

b = a()

print('d' in b)
import unittest

class TestA(unittest.TestCase):
    def test_in(self):
        self.assertTrue('d' in b)
        self.assertIn('d', b)

```

<h3> Repro Steps </h3>

1. Paste above snippet in VS Code

<h3> Expected behavior </h3>

It type checks okay

<h3> Actual behavior </h3>

```
Argument of type "a" cannot be assigned to parameter "container" of type "Iterable[Any] | Container[Any]" in function "assertNotIn"
  Type "a" cannot be assigned to type "Iterable[Any] | Container[Any]"
    "a" is incompatible with protocol "Iterable[Any]"
      "__iter__" is not present
    "a" is incompatible with protocol "Container[Any]"
      "__contains__" is an incompatible type
        Type "(m: Any) -> (Literal[True] | None)" cannot be assigned to type "(__x: object, /) -> bool"
          Function return type "Literal[True] | None" is incompatible with type "bool"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```
<h3> Logs </h3>

N/A

**Comment by davetapley** [comment]
This should probably to go https://github.com/microsoft/pyright/

because:
https://github.com/microsoft/pyright/blob/4c49f518a37bae49f511f853ad4ded07d266debc/packages/pyright-internal/typeshed-fallback/stdlib/unittest/case.pyi#L112-L113C13

**Comment by erictraut** [comment]
Pyright is working correctly here. The protocol definition for `Container` indicates that the `__contains__` method must return a `bool` value, but `a.__contains__` returns `Literal[True] | None`. That means class `a` doesn't match the `Container` protocol.

If you change your implementation of `a.__contains__` to the following, it will type check without error:
```python
    def __contains__(self, m):
        return bool(self.d)
```

**Comment by davetapley** [comment]
Good catch! Thanks 🙏🏻
