### ISSUE TITLE
Two questions about pylance usage

### ISSUE THREAD

**Issue by Lantern-r** [microsoft/pylance-release#5073]
1. How do I get pylance to parse pyi correctly

```
ls /home/lantern/anaconda3/envs/angr/lib/python3.11/site-packages/ghidra-stubs                                  
app           closedpatternmining  docking    generic                      GhidraJarApplicationLayout.pyi  GhidraRun.pyi                    JarRun.pyi  MiscellaneousPluginPackage.pyi  plugins                 rmi       SoftwareModelingInitializer.pyi  util
async         comm                 feature    GhidraApplicationLayout.pyi  GhidraLaunchable.pyi            GhidraTestApplicationLayout.pyi  javaclass   net                             program                 security  SwingExceptionHandler.pyi        xml
base          dalvik               file       ghidra_builtins.pyi          GhidraLauncher.pyi              GhidraThreadGroup.pyi            language    pcode                           project                 server    taint
bitpatterns   dbg                  formats    GhidraClassLoader.pyi        GhidraOptions.pyi               graph                            lifecycle   pcodeCPort                      ProjectInitializer.pyi  service   test
bytepatterns  debug                framework  GhidraException.pyi          Ghidra.pyi                      __init__.pyi                     macosx      plugin                          python                  sleigh    trace
```

```
Import "ghidra.ghidra_builtins" could not be resolved from source
```

2. How should I use Pylance properly to avoid the following situation：

```python
try:
    from ghidra.ghidra_builtins import *
except:
    pass
```

the situation is:
```
"getCurrentProgram" is unboundPylance[reportUnboundVariable](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnboundVariable)
(function) getCurrentProgram: Unbound
```

But in fact it is contained in ghidra.ghidra_builtins

```python
def getCurrentProgram() -> ghidra.program.model.listing.Program:
    """
    Gets the current program.
    @return the program
    """
    ...
```

**Comment by debonte** [comment]
> ```text
> Import "ghidra.ghidra_builtins" could not be resolved from source
> ```
[reportMissingModuleSource](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource) indicates that Pylance found the stubs for the specified module, but did not find the implementation. If you have `ghidra-strubs` installed, but not `ghidra` then this is expected.

It's not clear to me how [Ghidra](https://github.com/NationalSecurityAgency/ghidra) gets installed or if there even is a `ghidra` Python module. If you will never have a `ghidra` Python module present in your environment, then you could choose to suppress this error by putting `# type: ignore` at the end of the `import` line.

> How should I use Pylance properly to avoid the following situation：
> ```python
> try:
>     from ghidra.ghidra_builtins import *
> except:
>     pass
> ```

A type checker cannot determine statically whether the `try` or `except` will be executed at runtime. If you want to use the "try import" pattern, you can use `TYPE_CHECKING` to tell the type checker what imports it should assume will be present:

```python
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from ghidra.ghidra_builtins import * # type: ignore
else:
    try:
        from ghidra.ghidra_builtins import * # type: ignore
    except:
        pass


getCurrentProgram()
```
