### ISSUE TITLE
Rename Symbol renames variables of the same name in different scopes of an if statement

### ISSUE THREAD

**Issue by SmartLamScott** [microsoft/pylance-release#5075]
<h3> Environment data </h3>

-   Language Server version: 2023.10.20
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.5 64-bit
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
flag = True
if flag:
    for index in range(10):
        print(index)
elif flag:
    for index in range(10):
        print(index)
```

<h3> Repro Steps </h3>

1. Create an if statement with multiple branches. Each branch should use a variable of the same name, but the variable should not be declared outside of any branch of the if statement.
![image](https://github.com/microsoft/pylance-release/assets/134100828/83d3db5d-f67d-4f37-9a3f-f462fc600cd3)
2. Select the variable and rename it.
![image](https://github.com/microsoft/pylance-release/assets/134100828/ec95712d-7378-48f6-8ca7-74ce923d3ff0)
3. This results in all the variables sharing this name to be renamed.
![image](https://github.com/microsoft/pylance-release/assets/134100828/80306cbb-6fd6-44c0-8137-b2b2aa193dd7)

<h3> Expected behavior </h3>

The selected variable should be renamed, but only in its scope. Variables of the same name in other scopes should remain untouched. This is supported by the fact that variables that share the same name residing in different functions are left unaltered when using Rename Symbol on them.

<h3> Actual behavior </h3>

All variables sharing the same name within all branches of the if statement are renamed, not just in the proper scope.

**Comment by erictraut** [comment]
In Python, `if` statements don't introduce a new scope. In your example, all identifiers `foo` refer to the same variable, so it's correct for all of them to be renamed.

There are other languages where `if` statements introduce new scopes, but that's not true of Python.

**Comment by SmartLamScott** [comment]
That makes sense. Thanks for the swift response and sorry I added to your issues needlessly.
