### ISSUE TITLE
After briefly being available in the Jupyter Notebook editor, Go To Definition (Ctrl + right click / F12) has become unavailable.

### ISSUE THREAD

**Issue by CoderChen01** [microsoft/pylance-release#5076]
> @CoderChen01 your issue is a dupe of #5037 that was fixed in 2023.10.53. You can fix your problem by upgrading to the prerelease version.

Thank you for your answer, but I switched to 2023.10.53 and the problem still exists. Here is my screen recording.

https://github.com/microsoft/pylance-release/assets/61137732/b25f7334-7d8a-4d4d-8999-5c19467a56e2

_Originally posted by @CoderChen01 in https://github.com/microsoft/pylance-release/issues/5066#issuecomment-1791706271_

**Comment by rchiodo** [comment]
Thanks, can you include the output from the `Python Language Server` pane?

**Comment by CoderChen01** [comment]
> Thanks, can you include the output from the `Python Language Server` pane?
> 
> The video looks like the Pylance language server stopped responding or crashed.

In this video, I initially tested on version 2023.10.40 and there were no issues. Then I switched back to 2023.10.53, the problem could still be reproduced, and the output seemed quite normal.


https://github.com/microsoft/pylance-release/assets/61137732/380f2483-a7c2-492c-a861-751d194bc722

**Comment by rchiodo** [comment]
It looks like the server is busy and never finishing. If you hover over print, does it show anything after it stops working?

**Comment by rchiodo** [comment]
Can you share your source so I can try to repro?

**Comment by CoderChen01** [comment]
> It looks like the server is busy and never finishing. If you hover over print, does it show anything after it stops working?

It can't show anything, and the code block also cannot run anymore.

**Comment by rchiodo** [comment]
Okay this might be the same problem as this [one](https://github.com/microsoft/vscode/issues/196740). We're about to release, so maybe you can try again with the new prerelease (should be out by tomorrow)

If jupyter execution is getting messed up, the consistent repro seems to be the wrong URI being returned from Pylance requests.

**Comment by CoderChen01** [comment]
> Can you share your source so I can try to repro?

Of course, it's possible, but there will always be problems in the notebook editor.

This is my current vscode profile: https://vscode.dev/profile/github/e110678985ac8e4d6a31cc0dc36b8b3c

Here is my code file: https://drive.google.com/file/d/1-Tj4lQy64sQlp07vaFJxcf_P8dThEcqe/view?usp=sharing

**Comment by rchiodo** [comment]
Thanks. I can repro something similar with 2023.10.53 if I goto definition on things in the notebook. (not if I only goto def on externals, like the definition of AutoTokenizer).

Our new release fixes the problem for me, so it will likely do the same for you.
