### ISSUE TITLE
Argument of type "Literal[0]" cannot be assigned to parameter

### ISSUE THREAD

**Issue by wheeheee** [microsoft/pylance-release#5083]
## Environment data

-   Language Server version: v2023.11.11
-   OS and version: Windows 11 22H2, (OS Build 22621)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   VSCode version: 1.84.0

## Code Snippet

```python
from keras.models import Sequential
from keras.layers import Input, Dense

m = Sequential()
m.add(Input(1))
m.add(Dense(1))
m.compile(loss="mse")
m.fit([1,2,3], [4,5,6], verbose=0)
```

## Repro Steps

1. Enter code snippet into empty file, open in VSCode.
2. Change keyword argument to verbose to desired int/bool.

## Expected behavior

Keyword arguments of verbose are not underlined in red squigglies, since there are no type annotations in the method called.

## Actual behavior

Unless argument is a string like the default, they are underlined with red squigglies.

## Logs

```
[{
	"resource": "/blah/blah.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportGeneralTypeIssues",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportGeneralTypeIssues"
		}
	},
	"severity": 8,
	"message": "Argument of type \"Literal[0]\" cannot be assigned to parameter \"verbose\" of type \"str\" in function \"fit\"\n  \"Literal[0]\" is incompatible with \"str\"",
	"source": "Pylance",
	"startLineNumber": 119,
	"startColumn": 69,
	"endLineNumber": 119,
	"endColumn": 70
}]
```

**Comment by erictraut** [comment]
This is working as designed, so I don't consider it a bug.

Keras is an untyped library. Without type information, pyright (the type checker upon which pylance is built) needs to infer type information. When a function's parameter has a default argument, pyright uses the type of that parameter for type inference. Most of this time, this is beneficial. In rare cases like this one, it can lead to an incorrect assumption. For details, refer to [this documentation](https://microsoft.github.io/pyright/#/type-inference?id=parameter-type-inference).

Type inference can lead to false positives, and no approach will be correct all of the time. If you want to benefit from type checking within your code, it's best to use libraries with inlined type information or type stubs.

As a workaround, you can add a `# type: ignore` or `# pyright: ignore` comment to the end of the line. Or if you're seeing many type checking errors with keras, you can disable type checking in your project by setting `python.analysis.typeCheckingMode` to "off".
