### ISSUE TITLE
Pylance not able to infer nested inline TypedDicts

### ISSUE THREAD

**Issue by iann838** [microsoft/pylance-release#5087]
## Environment data

-   Language Server version: 2023.10.50 (pyright cfe56bfb)
-   OS and version: Win 11
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.12.0

## Code Snippet

```python

A = TypedDict("A", {
    "metadata": TypedDict("AMetadata", {
        "dataVersion": str,
    }),
})


def return_a() -> A:
    return {
        "metadata": {
            "dataVersion": "1.0"
        }
    }


a = return_a()


metadata = a["metadata"]
```

## Expected behavior

`metadata` is typed as `AMetadata`.
`metadata[]` hints at a list of keys.

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/58193352/54f278a1-f5c0-44a7-a8f1-bc63b85bf50e)

`metadata` is typed as `Any`.

**Comment by erictraut** [comment]
This behavior is correct. Call expressions are not allowed within type annotations, and TypedDict's cannot be anonymous.

```python
AMetadata = TypedDict(
    "AMetadata",
    {
        "dataVersion": str,
    },
)
A = TypedDict(
    "A",
    {
        "metadata": AMetadata,
    },
)
```

There has been some discussion of expanding the type system to support inlined TypedDict definitions, but they haven't yet progressed to the PEP stage.

**Comment by iann838** [comment]
@erictraut Thanks, I shall wait for future PEP progress (if any).
