### ISSUE TITLE
Pylance ignores the Linting rule

### ISSUE THREAD

**Issue by jeff-hykin** [microsoft/pylance-release#509]
## Environment data

-   VS Code version: 1.50.1
-   Extension version (available under the Extensions sidebar): 2020.10.1
-   OS and version: MacOS Sierra
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Value of the `python.languageServer` setting: "Pylance"

## Expected behaviour

No linting

## Actual behaviour

My settings:
```
"python.languageServer":"Pylance",
"python.linting.enabled": false,
"python.linting.mypyEnabled": false,
"python.linting.pylintEnabled": false,
"python.linting.maxNumberOfProblems": 0,
"python.workspaceSymbols.enabled": false,
```
After reloading the window:
![Screen Shot 2020-10-20 at 3 41 53 PM](https://user-images.githubusercontent.com/17692058/96642172-61103a00-12eb-11eb-9ba4-2e6ab43d97e6.png)

## Steps to reproduce:
- Install pylance
- set those settings
- reload window
- create new python file (save it)
- try to use an undefined variable (`a = alkjalksdfja`)

**Comment by jakebailey** [comment]
Pylance will warn about undefined/unbound variables by default (MPLS did too).

If you don't like this behavior, you can override the severity level for `reportUndefinedVariable` and `reportUnboundVariable`: https://github.com/microsoft/pylance-release/blob/master/DIAGNOSTIC_SEVERITY_RULES.md

**Comment by jakebailey** [comment]
However, if the variable _is_ actually defined, then that could indicate a bug and we'd appreciate a more complete example, but your repro steps are what we currently expect.

**Comment by jeff-hykin** [comment]
> Pylance will warn about undefined/unbound variables by default (MPLS did too).
> 
> If you don't like this behavior, you can override the severity level for `reportUndefinedVariable` and `reportUnboundVariable`: https://github.com/microsoft/pylance-release/blob/master/DIAGNOSTIC_SEVERITY_RULES.md

How can I do this but for everything?

**Comment by jakebailey** [comment]
The top of the file I linked gives the setting to set this in VS Code. See also: https://github.com/microsoft/pylance-release#settings-and-customization

The setting UI will also provide a dropdown of the different diagnostics you can override.

**Comment by jeff-hykin** [comment]
I see, but there is no way to disable all linting? (I have to manually disable every individual rule, and disable new rules every time they are added?)

I have `"python.analysis.typeCheckingMode" : "off"`

**Comment by jakebailey** [comment]
The default is already "off", in this mode, the only things reported are:

- reportMissingImports
- reportMissingModuleSource
- reportUnboundVariable
- reportUndefinedVariable

And syntax errors. I don't expect us to expand this any further. These are just the same things that MPLS would have reported by default (and similar-ish to the core extension's pylint config).

**Comment by erictraut** [comment]
Most diagnostic rules are disabled by default in pylance. The small subset that are enabled by default have very low false positives and almost always indicate a bug in your code. If you are truly uninterested in being informed of such bugs, then you can disable the small number of diagnostic rules as Jake mentioned above.

**Comment by jeff-hykin** [comment]
Thanks for the information, I'll do that. However, I still think it is an issue that pylance is the only language server (AFAIK) that ignores the user's general linting rule. It undermines the goal of creating a common interface for settings that are shared across python language servers.

If a user disables generic linting it should stay disabled when switching to pylance.

I'm not worried about the false positive rate because I already know the code is wrong;  I frequently need to write pseudocode. Even outside of pseudocode however, I don't want an ugly line showing up in 0.1 sec telling me the line I haven't finished editing it going to throw an error.

**Comment by stolenzc** [comment]
@jakebailey 
excuse me, My django program also alert this and I don't know why, May I ask how to ignore this warning?
![image](https://user-images.githubusercontent.com/42373706/96952672-07458500-1522-11eb-9724-08e65f4eba6d.png)

**Comment by jakebailey** [comment]
@stolenzc That's unrelated to this issue. That appears to be a false positive in the support for the 3.10 Union syntax, and we'd appreciate a separate issue (as that's certainly something to look into).

**Comment by jakebailey** [comment]
"Linting" has a long history in Python for VSC that is rooted in the fact that until a couple of years ago, there was no way to provide live information about issues in Python code. All diagnostics were provided by external linters, e.g. running pylint on save with some preset config to get syntax errors.

These days, that is no longer necessary, and the core extension already elides running linters by default when an LS enabled; you have to explicitly force enable things like pylint.

That toggle already doesn't quite have the meaning it used to in the presence of a language server. With MPLS, we were loose and tried to respect the setting, but even then we weren't perfectly consistent and still allowed some messages through that we believed to be so problematic that it was worse to not show them than to show them, i.e., syntax, imports, unbound values, where each directly impacts the quality of the analysis.

I don't see us adding any new diagnostics to the default set for Pylance any time soon; if you find its default set to be undesirable I would override them to disable them (those listed in https://github.com/microsoft/pylance-release/issues/509#issuecomment-713767197) and it should work as expected.

Perhaps we'll revisit this in the future, but I don't see us wanting to add this complexity when we are so unlikely to add more diagnostics to the defaults everyone gets.

**Comment by anneadb** [comment]
Hi there,

I have the same issue of wanting to switch off all the linting in Pylance.

1. In out team, not everyone uses VSCode and we agreed on common flake8 settings.
2. I find the "live" linting rather distracting.

I've removed the 4 settings mentioned above but this still shows up:

<img width="384" alt="Screenshot 2021-04-07 at 08 53 20" src="https://user-images.githubusercontent.com/46241952/113823265-b992a100-977e-11eb-90e4-3612ffa8ca84.png">

Can you tell me how to switch this off?

**Comment by jakebailey** [comment]
I think what you're looking for is #237.

**Comment by anneadb** [comment]
Hi @jakebailey,
thanks for your answer.
Yes, this addresses the second reason why I would like to switch off the error reporting in Pylance but my goal is still to _switch off any error reporting by Pylance and keep using flake8_.
I only installed Pylance because I had issues importing modules after the last VSCode update. Pylance fixed that but I wasn't expecting this extra "feature".

**Comment by erictraut** [comment]
By default, pylance will report only the most basic of errors — e.g. syntax errors that will result in runtime errors as soon as the Python interpreter attempts to run the code. 

Can you provide more details about the code that is resulting in the error `Expected expression to the right of "="`? Pylance is detecting a basic syntax error here, so I'd like to understand whether it's a bug in pylance or an actual syntax error in your code.

**Comment by jeff-hykin** [comment]
> "Linting" has a long history in Python for VSC that is rooted in the fact that until a couple of years ago, there was no way to provide live information about issues in Python code. All diagnostics were provided by external linters, e.g. running pylint on save with some preset config to get syntax errors.
> 
> These days, that is no longer necessary, and the core extension already elides running linters by default when an LS enabled; you have to explicitly force enable things like pylint.
> 
> That toggle already doesn't quite have the meaning it used to in the presence of a language server. With MPLS, we were loose and tried to respect the setting, but even then we weren't perfectly consistent and still allowed some messages through that we believed to be so problematic that it was worse to not show them than to show them, i.e., syntax, imports, unbound values, where each directly impacts the quality of the analysis.
> 
> I don't see us adding any new diagnostics to the default set for Pylance any time soon; if you find its default set to be undesirable I would override them to disable them (those listed in https://github.com/microsoft/pylance-release/issues/509#issuecomment-713767197) and it should work as expected.
> 
> Perhaps we'll revisit this in the future, but I don't see us wanting to add this complexity when we are so unlikely to add more diagnostics to the defaults everyone gets.

I'm glad this was bumped as, I meant to say this back when you posted this @jakebailey, but sincerely thank you for taking the time to write up the reasoning before closing. It changed this from "it's proprietary, and I see they don't really care" to a "we respectfully disagree, but the reasoning was thought out and provided". 👍
