### ISSUE TITLE
Error: Debug Failure. False expression: Check called before binding

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5097]
pyright 1.1.334
Error: Debug Failure. False expression: Check called before binding
at assert pyright-internal/src/analyzer/sourceFile.ts:781:8
at callback pyright-internal/src/common/logTracker.ts:57:19
at log pyright-internal/src/analyzer/program.ts:1874:32
at callback pyright-internal/src/analyzer/typeEvaluator.ts:590:19
at callback pyright-internal/src/common/timing.ts:44:27
at runWithCancellationToken pyright-internal/src/analyzer/program.ts:1045:40
at _runEvaluatorWithCancellationToken pyright-internal/src/analyzer/program.ts:638:20
at analyze pyright-internal/src/analyzer/analysis.ts:52:32
at this pyright-internal/src/backgroundAnalysisBase.ts:484:12
at handleResumeAnalysis pyright-internal/src/backgroundAnalysisBase.ts:336:21
at None pylance-internal/src/commands/commandController.ts:83:32
at onMessage pyright-internal/src/backgroundAnalysisBase.ts:630:24
at func (node::735:20)
at func (node::23:28)

**Comment by rchiodo** [comment]
Should be in the next version of Pyright. Our next prerelease we should be able to check for the crash again.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2023.11.13, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231113-15-November-2023-PreRelease)
