### ISSUE TITLE
How to disable "Missing Argument" and "Code is unreachable" warnings?

### ISSUE THREAD

**Issue by HMaker** [microsoft/pylance-release#51]
Pylance is giving "Missing Argument" warning in the following decorator usage:
```python
class DecoratorClass:

    def decorator(cls, func):
        def wrapper():
            print('Hello from decorator')
            func()
        return wrapper
    decorator = classmethod(decorator)

@DecoratorClass.decorator
def foo():
    print('Hello from foo')

foo()
``` 

and "Code is unreachable" warning at the print line in `Superclass.say_hello` method:
```python
class Superclass:

    def hello(self):
        raise NotImplementedError

    def say_hello(self):
        self.hello()
        print('I am reachable from Subclass')

class Subclass(Superclass):

    def hello(self):
        print('Hello')

Subclass().say_hello()
```
How can I disable those warnings? I don't think it's a bug.

**Comment by erictraut** [comment]
You can eliminate the first warning by adding appropriate type annotations to your decorator.

```
from typing import TypeVar

_T = TypeVar("_T")

class DecoratorClass:
    @classmethod
    def decorator(cls, func: _T) -> _T:
        def wrapper():
            print("Hello from decorator")
            func()

        return wrapper
```

For the second one, there are two ways you can improve your code an eliminate the warning.

The first way is to declare `Superclass` as an abstract base class (ABC) and the `hello` as an abstract method.

```
from abc import ABC, abstractmethod

class Superclass(ABC):
    @abstractmethod
    def hello(self):
        raise NotImplementedError
```

The second way is provide an explicit return type annotation for `hello` so Pylance doesn't need to infer the return type from the code.

```
class Superclass:
    def hello(self) -> None:
        raise NotImplementedError
```

**Comment by HMaker** [comment]
For the second case, its better to typehint the return type. In the decorator case, I can't employ the decorator annotation by using @classmethod since that decorator is in a third party library, but I can suppress the warning with `# type: ignore`. Thanks for the answer.

**Comment by erictraut** [comment]
If it's in a third-party library, the recommended way to handle it is through a type stub that defines the interface to that library. If a type stub isn't available, you have the option of creating one yourself. Or you can wait for someone else (perhaps the library's author) to publish a type stub. You can suppress the error in the meantime using a `# type: ignore` comment, as you pointed out.
