### ISSUE TITLE
pandas has its own typing since 2.0

### ISSUE THREAD

**Issue by davetapley** [microsoft/pylance-release#5102]
## Environment data

-   Language Server version: v2023.11.10
-   OS and version: Codespace `mcr.microsoft.com/devcontainers/universal:2`
-   Python version (& distribution if applicable, e.g. Anaconda): `ghcr.io/devcontainers/features/python:1` on 3.11

## Code Snippet

```python
from datetime import datetime
from pandas import Timestamp

Timestamp(datetime.now().isoformat()).as_unit('us')
```

## Repro Steps

1. `pip install pandas==2.1.0`
2. paste above snippet

## Expected behavior

Type check ok because [`as_unit`](https://github.com/pandas-dev/pandas/blob/851fea0ea38985cd7d5e0a3b7a7a7539b5883307/pandas/_libs/tslibs/timestamps.pyi#L243)

## Actual behavior

```
Cannot access member "as_unit" for type "Timestamp"
  Member "as_unit" is unknownPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

because `as_unit` not in the [`pandas-stubs`](https://github.com/pandas-dev/pandas-stubs/blob/94df87594489d5043fab87810730ebcdf9931c77/pandas-stubs/_libs/tslibs/timestamps.pyi).

because:
- https://github.com/pandas-dev/pandas-stubs/issues/797

But this raises the question: Do we need to use `pandas-stubs` now 2.0 has its own types?

**Comment by davetapley** [comment]
Related issue I found in my research:
- https://github.com/microsoft/pylance-release/issues/1197
- https://github.com/microsoft/pylance-release/issues/3084
- https://github.com/microsoft/python-type-stubs/issues/191

**Comment by debonte** [comment]
This seems like a question for the folks at https://github.com/pandas-dev/pandas-stubs. If `pandas` has sufficient inline types to eliminate the need for stubs, then they should ship with a `py.typed` file. The presence of that file would cause type checkers to favor the inline types over any available stubs.

**Comment by davetapley** [comment]
@debonte oh, I naively assumed it was `py.typed`, but apparently not 😑 

It looks like as of Feb they were recommending `pandas-stubs`, I'll ask there...
- https://github.com/pandas-dev/pandas/issues/28142#issuecomment-1438701091
