### ISSUE TITLE
Explicitly setting a type doesn't give proper type-hinting 

### ISSUE THREAD

**Issue by burcam** [microsoft/pylance-release#5103]
## Environment data

-   Language Server version: v2023.11.10
-   OS and version: Ubuntu 20.04
-   Python version: 3.10.13

## Code Snippet

```python
class UncontrolledClass:
    def __init__(self, input: int) -> None:
        self.num = input
    num: int

    def new(self, input: int):
        if input == 1:
            return UncontrolledClass(input)
        return None

class ControlledClass:
    num: int

from_func: ControlledClass = UncontrolledClass.new(1)
from_func.num

from_num: ControlledClass = 1
from_num.num
```

## Repro Steps

1. Mouse over from_func and from_func.num.
2. Mouse over from_num and from_num.num.

## Expected behavior

"from_func" should cast to type "ControlledClass". "from_func.num" should have type "int".
"from_num" should cast to type "ControlledClass". "from_num.num" should have type "int".
## Actual behavior

"from_func" has type "Any | ControlledClass", "from_func.num" has type "Any | int"
"from_num" has type "ControlledClass", "from_num.num" has type "int" (Correct)

**Comment by erictraut** [comment]
Pylance is working correctly here. This isn't a bug.

Type annotations are not cast operators. They are type declarations that specify the type that should be enforced when assigning values to that variable. When you assign a value to the variable, you are allowed to assign a "narrower" type — one that is compatible with the declared type but more precise. Pyright (the type checker that underlies pylance) tracks these narrowed types throughout the code flow graph in your function. If you enable type checking mode (i.e. set `python.analysis.typeCheckingMode` to "basic") you will see errors reported if you attempt to violate the typing constraints, as you do in the code above.

For more information about static typing, type declarations, etc., you may find [this documentation](https://microsoft.github.io/pyright/#/type-concepts) useful.

**Comment by burcam** [comment]
Sorry, I used the wrong vocabulary here. In the above code I declare both from_func and from_num as ControlledClass. As expected, when typeCheckingMode is on basic, both of these assignments are considered invalid.
However, my actual use case (not just the toy example above) looks closer to `from_func: TypeA = func("TypeA")`. I'm not in control of the implementation of func, but it creates an object with a type based on the string passed into it, but it's declared return type isn't well-defined. As a developer, I'd like to be able to specify "I know that this object has this type". In most cases I can do this, but not here.
I would also expect this declaration to work as ControlledClass is narrower than Any | ControlledClass.

**Comment by erictraut** [comment]
It sounds like you're looking for a cast operator to cast the type of the expression to a different type, thus overriding the type checker's inferred type. You can do this using `typing.cast`.

```python
from typing import cast
x: int = cast(int, "not an int")
```

I recommend using `cast` sparingly because it can mask errors that a type checker would otherwise be able to catch.

**Comment by burcam** [comment]
Thanks, that's exactly what I was looking for.
