### ISSUE TITLE
How to make pylance use installed modules in existing jupyter Server

### ISSUE THREAD

**Issue by willi-z** [microsoft/pylance-release#5107]
Hi everyone,

first of all I wanted to mention, that I am very grateful for pylance, as it gave me a wonderful experience so far.
Therefore it is really sad, when I started to work with the JupyterNotebooks on an existing Jupyter Server.
The Server has python modules, that I can not install locally and it seems that this results in most modules being marked, as not able to resolve and classes and functions are allegedly not defined, even so the code runs with out issues.
As I found by researching the problem I found that pylance might not be able to find the modules on my system, even so it should look at the external server.
Is there an option to do this?
I would be very happy to use the features I fell in love with in my Jupyter-Projects therefore would appreciate every help.
Thanks!

**Comment by rchiodo** [comment]
One way this might be possible would be to share your drive for your remote server and then add that as [extraPaths](https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options)

```jsonc
   "python.analysis.extraPaths": ["//shared-drive/usr/lib/dist-packages"]
```

It needs to point to the location where the remote jupyter kernel has installed all of its python packages. Basically the remote `sys.path`
