### ISSUE TITLE
Long string literals are cut off when using autocomplete

### ISSUE THREAD

**Issue by monkeyman192** [microsoft/pylance-release#5116]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When using autocomplete on an argument which has a string literal as a type hint, the value which you end up with is truncated.
Actual: `"An even longer argument!! Wow! It's so long it wil…"`
Expected: `"An even longer argument!! Wow! It's so long it will just keep going... Will it ever stop?... Yes"`

## Steps to reproduce:

```python
from typing import Literal

class MyClass():
    def __init__(
        self, 
        some_arg: Literal[
            "This is a really long argument... I'm going to stop typing now...",
            "An even longer argument!! Wow! It's so long it will just keep going... Will it ever stop?... Yes"
        ]
    ):
        self.some_arg = some_arg
```

If you now enter `c = MyClass("`, the autocomplete will pop up with the two options. Pressing tab on one (say, the second) will result in the line
```python
c = MyClass("An even longer argument!! Wow! It's so long it wil…")
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2023-11-14 09:21:19.487 [info] Experiment 'pythonPromptNewFormatterExt' is active
2023-11-14 09:21:19.487 [info] Experiment 'pythonPromptNewToolsExt' is active
2023-11-14 09:21:19.487 [info] Experiment 'pythonRecommendTensorboardExt' is active
2023-11-14 09:21:19.488 [info] Experiment 'pythonREPLSmartSend' is active
2023-11-14 09:21:19.488 [info] Experiment 'pythonSurveyNotificationcf' is active
2023-11-14 09:21:19.488 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2023-11-14 09:21:19.488 [info] Experiment 'pythonTestAdapter' is active
2023-11-14 09:21:19.564 [info] Default formatter is set to null for workspace c:\Users\monkeyman192\Documents\GitHub\NMS data
2023-11-14 09:21:19.583 [info] Test server listening.
2023-11-14 09:21:19.584 [info] Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
2023-11-14 09:21:22.132 [info] Starting Pylance language server.
2023-11-14 09:24:26.399 [info] Discover tests for workspace name: NMS data - uri: c:\Users\monkeyman192\Documents\GitHub\NMS data\test.py
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.21.13141007
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (0.93GB free)|
|Process Argv|--crash-reporter-id 5e74cbc0-92bf-4dd1-949d-032a9996ea40|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30880073
ch094911:30880123
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30887143
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017:30886112
dsvsc018:30886114
aa_t_chat:30882232

```

</details>

**Comment by erictraut** [comment]
The current behavior is intentional. There must be some limit placed on literal string lengths. This cutoff is somewhat arbitrary, but it is quite long and accommodates the vast majority of use cases.

**Comment by monkeyman192** [comment]
Is there a way to configure it? I get not wanting to show the whole thing in the popup, but it doesn't seem right that when you'd auto-complete the value of the string it would not insert the full string...

**Comment by erictraut** [comment]
No, there's no way to configure it. Adding configuration knobs for something so esoteric is probably not the right answer.

**Comment by monkeyman192** [comment]
Yeah, that is fair enough. I still don't really understand why the value inserted into the code isn't the complete value. I can't see a use case for it being truncated when anyone wanting to use the auto-complete functionality would surely want the whole string irrespective of it's length?

**Comment by erictraut** [comment]
These same strings are used for hover text, type checker error messages, etc. We've seen cases where string literals are tens of thousands of characters in length. It wouldn't make sense to present the full string in these cases, so we need to cut it off at some length.

**Comment by monkeyman192** [comment]
Yeah, I understand for popups and messages and such, it definitely makes sense to have them truncated. However if you need the actual value in your code, I can't understand why the value that gets inserted isn't the full value. For every other case I agree, it should get truncated, just not this one.

**Comment by bschnurr** [comment]
How about we dont suggest the autocomplete then when the string is too long?

**Comment by monkeyman192** [comment]
I don't see how that really helps? The point is that I want the autocomplete.. Just not truncated...

**Comment by StellaHuang95** [comment]
Thank you for bringing up this issue. As mentioned earlier, the current behavior is by design, and at the moment, we don't have plans to alter it in the near future. For more insights into how we organize and prioritize issues, please refer to this [link](https://github.com/microsoft/pylance-release/wiki/Issue-Management). Thanks for your understanding!

**Comment by Minibrams** [comment]
@StellaHuang95  Any chance this could be revisited?

I understand that adding knobs for controlling max literal length seems like a strange thing to add, but there are scenarios where it makes some sense. I don't think these are particularly esoteric.

I am currently using a library that auto-generates API clients from OpenAPI specs, and it uses string literals to ensure type-safety when calling endpoints. Some of these endpoints are long, but not unreasonably so:

```python
# Actual endpoint is:            "/api/v1/git/merge_request/{config_type}/{site}/{name}"
AsyncIACConfigClient().get_route("/api/v1/git/merge_request/{config_type}/{site}/{na…")
```

Another scenario could be i18n where string literals are used for translation keys:
```python
raise NotFoundError(i18n.get("customer.customer_db_config_page.config_not_fou…"))
```

I don't know if these count as esoteric, but it does make it really hard to use string literals for stuff like this. I have to jump into the source code each time to get the full string literal every time it's too long for autocompletion.
