### ISSUE TITLE
Autocomplete suggests keyword argument for positional-only parameter

### ISSUE THREAD

**Issue by maurosilber** [microsoft/pylance-release#5117]
## Environment data

-   Language Server version: v2023.11.10
-   OS and version: MacOS Sonoma 14.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12 (from conda-forge).

## Code Snippet

```python
def func(parameter, /):
    pass

func(p...)
```

![image](https://github.com/microsoft/pylance-release/assets/9124827/19b336dc-f2ec-4999-856e-de41ed924475)

## Expected behavior

No suggestion for the positional-only parameter name.

## Actual behavior

Parameter name appears between the suggestions, but would result in an error if accepted.

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in an upcoming release.

**Comment by rchiodo** [comment]
This should be fixed in the 2023.11.13 version of Pylance.
