### ISSUE TITLE
Ctrl/⌘+click support for Unpacked **kwargs (go to definition)

### ISSUE THREAD

**Issue by lucas-labs** [microsoft/pylance-release#5118]
We already have support for unpacked kwargs completion, but if you <kbd>Ctrl</kbd> **+ click** (or <kbd>⌘</kbd> **+ click** on one of the unpacked args, it doen't take us to its definition as one would assume.

```python
class MyKwrgs(TypedDict):
    foo: str
    bar: str

def qux(**kwargs: Unpack[MyKwrgs]) -> None:
    pass
```

```python
qux(foo='foo', bar='bar')
#    ^ ctrl/cmd + click on foo should take us to foo definition
```

**Comment by erictraut** [comment]
This was recently fixed. If you switch to the pre-rerelease version of pylance, you'll see that it works as you'd expect.

**Comment by KacieKK** [comment]
yeah, this is fixed, thanks Eric
closing issue
