### ISSUE TITLE
Any advice for Django ForeignKey fields defined using string references?

### ISSUE THREAD

**Issue by jereze** [microsoft/pylance-release#5124]
In a Django project using VS Code with the Pylance extension, I am facing challenges with type hinting for ForeignKey fields. Specifically, the autocomplete feature does not provide accurate type information for ForeignKey relations when defined using a string reference to the related model.

<h3> Environment data </h3>

-   Language Server version: 2023.11.10
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.6
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off
-   Django version: 4.2.7

<h3> Repro Steps </h3>

This works as expected.

```python
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)


def test_pylance() -> str:
    c = Comment._default_manager.get(id=1)
    title = c.article.title
    return title
```
<img width="368" alt="CleanShot 2023-11-16 at 11 58 13@2x" src="https://github.com/microsoft/pylance-release/assets/4386500/1834d3e8-c71f-4cd6-9235-727e13d8e7d6">

But when using a string reference, it no longer works.

```python
class Comment(models.Model):
    article = models.ForeignKey("Article", on_delete=models.CASCADE)
    # other fields...

```

<img width="355" alt="CleanShot 2023-11-16 at 11 59 50@2x" src="https://github.com/microsoft/pylance-release/assets/4386500/4938db39-879e-4dac-9d7b-827ef19cace2">

<h3>Work Around</h3>

I discovered that explicitly typing the ForeignKey field as follows resolves the issue:

```python
class Comment(models.Model):
    article: models.ForeignKey[Article] = models.ForeignKey(
        "Article", on_delete=models.CASCADE
    )
    # other fields...
```

While the above workaround is effective, I am interested in understanding if there are any other recommended practices or solutions for this issue. Specifically:

* Are there any settings or configurations in Pylance or Django that can improve type hinting for ForeignKey fields defined with string references?
* Or, any package that could help here? I have tried using django-stubs, but it does not seem to resolve this particular issue.

Thanks

**Comment by rchiodo** [comment]
Without debugging what's going wrong my only guess is that the type stubs for `ForeignKey` are generic. That means when you pass a string for the T it treats it as a string, not as a type annotation.

Yeah the stubs (which we currently get from [django-types](https://github.com/sbdchd/django-types) instead of django-stubs - django stubs are mypy specific) are marking ForeignKey as generic:

```python
# related.pyi
class ForeignKey(Generic[_M], ForeignObject[_M]):
```

Which means if you pass in a string for the Generic, it can't tell what the type is.

This kinda stinks because it enforces ordering of the classes. However, you can workaround this with a type alias. Like so:

```python
MyAlias: TypeAlias = "Article"

class Comment(models.Model):
    article = models.ForeignKey(MyAlias, on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    
def test_pylance() -> str:
    c = Comment._default_manager.get(id=1)
    title = c.article.title
    return title

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
```

**Comment by jereze** [comment]
Thank you very much, @rchiodo, for your insightful suggestion. I appreciate your help.
