### ISSUE TITLE
Wrong autocomplete hints if a decorator is used

### ISSUE THREAD

**Issue by MalteBecker** [microsoft/pylance-release#5126]
Type: <b>Bug</b>

# Behaviour
When i use the autocomplete feature of a function that have a decorator i only get the wrapper parameters:

![fail](https://github.com/microsoft/vscode-python/assets/80974339/e727a5d2-e3e7-4ef1-95c5-426bcfef015f)

If I remove the `: FunctionType` in the `args_as_ints` definition. Everything works fine.

![work](https://github.com/microsoft/vscode-python/assets/80974339/bbfaedc6-d0c9-49ec-8355-6ca70a2efe17)

## Steps to reproduce:

1. Create a file with the following content.
```python
import functools
from types import FunctionType

def args_as_ints(func: FunctionType):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args = [int(x) for x in args]
        kwargs = dict((k, int(v)) for k, v in kwargs.items())
        return func(*args, **kwargs)

    return wrapper

@args_as_ints
def funny_function(x, y, z=3):
    """Computes x*y + 2*z"""
    return x * y + 2 * z

funny_function()
```
2. Use the autocomplete function for the funny_function.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.18
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Poetry
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.20.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by erictraut** [comment]
You have annotated your decorator incorrectly. If you find yourself using a symbol from the `types` module in an annotation, you're probably doing something wrong. (There are rare cases where this doesn't apply, but it's a good rule of thumb.) You should generally use symbols from `typing` instead of `types`.

Here's one way you can annotate your decorator:

```python
from typing import Any, Callable, TypeVar

T = TypeVar("T", bound=Callable[..., Any])

def args_as_ints(func: T) -> T:
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args = [int(x) for x in args]
        kwargs = dict((k, int(v)) for k, v in kwargs.items())
        return func(*args, **kwargs)

    return wrapper
```

Or if you're using Python 3.12, you can use the new PEP 695 syntax:

```python
from typing import Any, Callable

def args_as_ints[T: Callable[..., Any]](func: T) -> T:
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        args = [int(x) for x in args]
        kwargs = dict((k, int(v)) for k, v in kwargs.items())
        return func(*args, **kwargs)

    return wrapper
```

**Comment by MalteBecker** [comment]
@bschnurr oh okay. Thank you for your help.
