### ISSUE TITLE
Elipsis is required in Protocol class, if only using docstring raises GeneralTypeIssue

### ISSUE THREAD

**Issue by prokie** [microsoft/pylance-release#5127]
## Environment data

-   Language Server version: 2023.11.10
-   OS and version:  win32 x64
-   Python version: python 3.12.0
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic
## Code Snippet

```python
from typing import Protocol

class SingleEndedChannel(Protocol):

    @property
    def frequency(self) -> float:
        """Frequency of the output signal."""
        ...
```

## Repro Steps

Remove the ellipsis (...) and the GeneralTypeIssue will be raised.

## Expected behavior

I expect that I should not need to add ...

## Actual behavior

I get a reportGeneralTypeIssue

## Logs

```
XXX
```

**Comment by erictraut** [comment]
This is intended behavior. Protocol classes are allowed to provide implementations for methods, and subclasses of those protocols inherit those implementations. A `...` indicates to a type checker that the method's implementation isn't intended to be treated as such — and that the method should instead be treated as a "template" for structural type checks. If you omit the ellipsis, pyright (the type checker that underlies pylance) will assume that it should type check the method as though it has a real implementation.

**Comment by erictraut** [comment]
I'm guessing that you filed this issue because ruff's code formatting is removing the `...` from your protocol definition. I've replied to a [thread in the ruff issue tracker](https://github.com/astral-sh/ruff/issues/8756#issuecomment-1817567945) to clarify that ruff's formatter shouldn't remove the `...`.

**Comment by prokie** [comment]
Yes, it was removing it! Thanks for filing an issue with Ruff and thanks for the explanation.
