### ISSUE TITLE
Infer types for lambdas in Deal contracts

### ISSUE THREAD

**Issue by EternityForest** [microsoft/pylance-release#5132]
Right now, using Deal contract decorators produces lots of errors when using strict mode, due to not knowing the Lambda return types(Also due to the type of the decorator itself being unknown, but that might be an issue with Deal itself?).

Would it be possible to special-case these, or is there some way it could be fixed on Deal's end, so that the checker can infer the types of the lambda validators passed to the contract decorators?

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) has no specific knowledge of any third-party libraries. It uses type information provided by those libraries or separate type stubs to evaluate types.

Which library are you referring to here? Which version? Could you provide a self-contained minimal repro in code form?
