### ISSUE TITLE
Error when using TypeVar in type annotation for @property

### ISSUE THREAD

**Issue by BojieSheng** [microsoft/pylance-release#5133]
```python
from typing import TypeVar, Generic
from pyspark.sql import DataFrame
import pandas as pd
AnyDataFrame = TypeVar('AnyDataFrame', pd.DataFrame, DataFrame)

class OutputA(Generic[AnyDataFrame]):

    @property
    def original_data(self) -> AnyDataFrame:
        return self._original_data

    @original_data.setter
    def original_data(self, value: AnyDataFrame) -> None:
        self._original_data = value
```

I get mypy error: Need type annotation for "_original_data"  [var-annotated]

I have to add the annotation as below to solve the error, why?
```python
    @original_data.setter
    def original_data(self, value: AnyDataFrame) -> None:
        self._original_data: AnyDataFrame = value
```

**Comment by erictraut** [comment]
Is your question related to pylance? You mentioned that you're using mypy.

The code you've provided is incomplete. It refers to symbols `pd` and `DataFrame` that are undefined. I presume that `pd` is can be defined through a `import pandas as pd` statement, but I don't know what `DataFrame` refers to. Could you update your example so it's complete?

If you have a question or bug report about mypy, you can post to the [mypy issue tracker](https://github.com/python/mypy/issues).

If you have a general question about static typing in python, the [python/typing discussion forum](https://github.com/python/typing/discussions) is a good place to post.

**Comment by debonte** [comment]
I was able to repro the error in https://mypy-play.net using the following code. Pylance doesn't show any diagnostics for this code even in strict mode.

```python
from typing import TypeVar, Generic


class pdDataFrame: ...

class DataFrame: ...

AnyDataFrame = TypeVar('AnyDataFrame', pdDataFrame, DataFrame)
class OutputA(Generic[AnyDataFrame]):

    @property
    def original_data(self) -> AnyDataFrame:
        return self._original_data

    @original_data.setter
    def original_data(self, value: AnyDataFrame) -> None:
        self._original_data = value
```

**Comment by BojieSheng** [comment]
> Is your question related to pylance? You mentioned that you're using mypy.
> 
> The code you've provided is incomplete. It refers to symbols `pd` and `DataFrame` that are undefined. I presume that `pd` is can be defined through a `import pandas as pd` statement, but I don't know what `DataFrame` refers to. Could you update your example so it's complete?
> 
> If you have a question or bug report about mypy, you can post to the [mypy issue tracker](https://github.com/python/mypy/issues).
> 
> If you have a general question about static typing in python, the [python/typing discussion forum](https://github.com/python/typing/discussions) is a good place to post.

Thanks for your reply, the code has been updated.

**Comment by BojieSheng** [comment]
> I was able to repro the error in https://mypy-play.net using the following code. Pylance doesn't show any diagnostics for this code even in strict mode.
> 
> ```python
> from typing import TypeVar, Generic
> 
> 
> class pdDataFrame: ...
> 
> class DataFrame: ...
> 
> AnyDataFrame = TypeVar('AnyDataFrame', pdDataFrame, DataFrame)
> class OutputA(Generic[AnyDataFrame]):
> 
>     @property
>     def original_data(self) -> AnyDataFrame:
>         return self._original_data
> 
>     @original_data.setter
>     def original_data(self, value: AnyDataFrame) -> None:
>         self._original_data = value
> ```

Thanks, Debonte. Do you know the reason of the error?

**Comment by debonte** [comment]
@BojieSheng, I'm not sure what is causing the error. But since your question is about the behavior of mypy rather than Pyright or Pylance, please file an issue at https://github.com/python/mypy/issues instead.
