### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by swapnilwagh2204** [microsoft/pylance-release#514]
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2020.9.114305`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.50.1`
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1635,
		"activateCallTime": 4,
		"activateResolvedTime": 15849,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-python.vscode-pylance",
				"_lower": "ms-python.vscode-pylance"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```
:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jakebailey** [comment]
What is the issue? There's no much in this report to indicate that something is wrong. All the above says is that the Pylance extension loaded the Python extension.

**Comment by swapnilwagh2204** [comment]
Hey jack,thanks for responding.The issue is vscode is running so slowly.and extensions also loading up very slowly.is there any way to optimize the performance??

**Comment by jakebailey** [comment]
VS Code offers a dev tool to analyze how long each extension is taking to load (an option called "Startup Performance"), but this may simply be your machine's performance.

**Comment by swapnilwagh2204** [comment]
Thanks jake

**Comment by jakebailey** [comment]
It's been a month without update/more info; I'm going to close this.
