### ISSUE TITLE
Missing autocomplete for type `Literal[...] | str`

### ISSUE THREAD

**Issue by ianhco** [microsoft/pylance-release#5146]
## Environment data

-   Language Server version: 2023.11.10 (pyright 088ebaa5)
-   OS and version: Win 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.0

## Code Snippet

```python

from typing import Literal, Any, LiteralString, AnyStr

OptionStr = Literal["a", "b", "c"] | str
OptionAny = Literal["a", "b", "c"] | Any
OptionLit = Literal["a", "b", "c"] | LiteralString
OptionAnyStr = Literal["a", "b", "c"] | AnyStr

def func(*, o1: OptionStr, o2: OptionAny, o3: OptionLit, o4: OptionAnyStr):
    ...

func(o1="")
func(o2="")
func(o3="")
func(o4="")

```

## Expected behavior

All `o1`, `o2`, `o3`, and `o4` should have type hints for the `Literal["a", "b", "c"]` 
![image](https://github.com/microsoft/pylance-release/assets/58193352/5032289e-cf44-4cfa-a0ea-109b3956bd62)

## Actual behavior

`o2`, `o3` and `o4` prompt autocomplete as expected.
`o1` (`Literal["a", "b", "c"] | str`) does not prompt autocomplete.
![image](https://github.com/microsoft/pylance-release/assets/58193352/a6b901c3-bf6c-4d32-8e9f-d4cb900ea0fc)
![image](https://github.com/microsoft/pylance-release/assets/58193352/3e8865a2-5581-4d01-9431-73c2abbf9970)
![image](https://github.com/microsoft/pylance-release/assets/58193352/118b32d6-f286-4395-a825-d67262f9e2dd)

**Comment by iann838** [comment]
@erictraut Thanks for the response, your guess is correct. While I agree that it is atypical, it is still a valid type and therefore the server should still provide the completion suggestions regardless. I can name a few use cases for this:
- A parameter accepts "latest", "development", "staging", "production", and any arbitrary version number.
- A parameter accepts a list of frequent options, the list of options may grow over time, this would prevent a sudden type check error until the new option is added.

**Comment by erictraut** [comment]
> it is still a valid type

I agree it's a valid type, but you're relying on the tenuous assumption that the type evaluator won't immediately simplify the type. This would be justified given that the simplified version of the type is the same as the more complex type. The type evaluator doesn't currently perform this simplification in this case, but it does in other cases. This could change in the future. Even if the language server were to add support for this, it could easily break in the future as the underlying type evaluator evolves.

A more robust approach is to use an overload:
```python
@overload
def func(*, o1: Literal["a", "b", "c"]) -> None:
    ...

@overload
def func(*, o1: str) -> None:
    ...

def func(*, o1: str) -> None:
    pass
```

This also has the added benefit of working with the current completion provider logic.

**Comment by iann838** [comment]
@erictraut Understandable, using `@overload` is indeed the more robust approach, my issue is that I have more than 50 functions relying on such argument typing, doing 50+ overloads is not going to look great. I have found out that `Literal[] | AnyStr` works, and based on your reply, it's not simplifying this type since `AnyStr` includes byte strings, so I will be coping with that instead in the meantime.

**Comment by erictraut** [comment]
I don't think you want to use `AnyStr`. This is a type variable, which means that `OptionAnyStr = Literal["a", "b", "c"] | AnyStr` defines a generic type alias. When this type alias is used, it requires you to supply a type. If you omit the type argument (`OptionAnyStr`), a type checker will assume you mean `OptionAnyStr[Any]`, which is probably not your intent. If you really do intend for your function to be generic and it accepts `bytes` arguments, you could specify `OptionaAnyStr[AnyStr]`, but I'm guessing that's inconsistent with your implementation. An `@overload` is the proper tool for this job. I agree it's somewhat verbose, but if you're looking for a correct and robust solution, that's what I recommend.

**Comment by iann838** [comment]
Thanks, I'll consider it
