### ISSUE TITLE
When I try to rename a function definition I run into a bug

### ISSUE THREAD

**Issue by ujazishere** [microsoft/pylance-release#5148]
Type: <b>Bug</b>

its  not possible to rename a function definition unless you press F2 once done It creates a new line in the file after every line. when used undo it undoes the fault and remanes it back to the previous function definition name. I use vim new line keyboard shortcuts a lot that used the key 'o' and 'O' when in vim mode, nevertheless I tried it with extension bisect with vim supposedly off and the issue persists.

Extension version: 2023.20.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (9.88GB free)|
|Process Argv|--crash-reporter-id 0144a85e-98ad-4ddf-b1e2-0976ac25a5cb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by heejaechang** [comment]
@ujazishere are you using vscode? or other editor? if you are using other editor, how are you using `pylance`? does it repro with `vscode + pylance` as well?

**Comment by ujazishere** [comment]
I am using vs code.

**Comment by ujazishere** [comment]
Also, if it helps, I figured out one of the issues that I was facing with the vim plugin in VS Code. Every once in a while, I would see my code's upper case chars turn into lowercase ones. This is incredibly frustrating, especially when it is subtle and your code breaks after many commits. Apparently this is due to the `u` key for undo in vim. When you are in visual mode (selection mode), you cannot undo using `u`. Instead, when you hit `u` for undo during visual mode, it will turn all the uppercase characters within that selection to lowercase ones.

**Comment by heejaechang** [comment]
can you provide some repro sample? I can't repro this with vscode + pylance. without repro, it is hard to find out what went wrong.
