### ISSUE TITLE
Refactor should handle primitive / object difference

### ISSUE THREAD

**Issue by rentruewang** [microsoft/pylance-release#5149]
See microsoft/vscode#198600

Steps to Reproduce:

1. Use the following code snippet
```python
a = 0

for i in range(10):
    a += 1
```
2. Use extract method from refactoring tools on the for loop.
3. Get the following code
```python
a = 0

def new_func(a):
    for i in range(10):
        a += 1

new_func(a)
```

This has no effect on primitive types.

**Comment by debonte** [comment]
> This has no effect on primitive types.

To be clear, your point is that at the end of the original snippet `a` is 10, but at the end of the second snipet `a` is 0?

Is this what you were hoping to see?

```python
a = 0

def new_func(a):
    for i in range(10):
        a += 1
    return a

a = new_func(a)
```

**Comment by rentruewang** [comment]
Hi, thanks for the response.

Answer to your question is yes. Since primitive types are copied by values, refactor should take care of that I think.

**Comment by StellaHuang95** [comment]
Hi @rentruewang, we've tagged the issue with the `bug` label, which means it's now in our backlog for fixing. The order in which we address backlog items depends on their priority and our current bandwidth. We will provide an update below this ticket once it's fixed. We appreciate your patience!

**Comment by rentruewang** [comment]
@StellaHuang95 Makes sense. Thanks.

**Comment by debonte** [comment]
Reopening as this has not been fixed yet. It still repros for me in 2024.5 103.
