### ISSUE TITLE
typed dict key hover shows incorrect header

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5150]
for 2 kinds of typed dict key hover, I get different header

![image](https://github.com/microsoft/pylance-release/assets/1333179/2bcbea61-6c7e-4263-b53e-d19f4c988549)

Both hover seems should show `(key)` rather than `(function)` for one of the case. or at least `(parameter)` instead of `(function)`

**Comment by rchiodo** [comment]
Won't fixing.
