### ISSUE TITLE
Setting auto import completions to true defaults exact match to true without showing it in the settings

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5153]
Set auto imports to true:

![image](https://github.com/microsoft/pylance-release/assets/19672699/73e50816-e851-4ef2-a324-14223c556002)

Then go into a python file and type something like 'Path'.

Imports will show up, but don't pick them, just leave 'Path' in the file.

Then pick the 'Add imports' action. It will show only exact matches:

![image](https://github.com/microsoft/pylance-release/assets/19672699/6608ca21-dbed-4c4d-95fe-49d2bf0abb2e)

Go back to settings and find the 'exact' option:

![image](https://github.com/microsoft/pylance-release/assets/19672699/6b9ac056-b07d-4385-8079-c8967beb9f74)

It seems to me this should show 'true' as that's the behavior I'm seeing.

**Comment by heejaechang** [comment]
the option is now removed.
