### ISSUE TITLE
Enabling Black formatter removes syntax highlighting

### ISSUE THREAD

**Issue by nicfv** [microsoft/pylance-release#5154]
Hi, whenever I enable Black formatter (v2023.6.0), my Python syntax highlighting gets removed. The only other extensions I have enabled are Python v2023.20.0 and Pylance v2023.11.10. See video for demonstration.

https://github.com/microsoft/vscode-black-formatter/assets/24358775/56ccbb41-627e-4d51-98aa-f11ec0b2ad9a

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.18.3-051803-generic snap
```

**Comment by heejaechang** [comment]
I can't repro this with latest vscode, pylance, python, black extension.

Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by jpcastberg** [comment]
I was experiencing the same thing, syntax highlighting came back after reloading the window.

**Comment by heejaechang** [comment]
can you provide us some logging or repro samples?
