### ISSUE TITLE
No autocomplete for cv2 module installed by conda

### ISSUE THREAD

**Issue by Unturned3** [microsoft/pylance-release#5163]
Type: <b>Bug</b>

- VS Code Version: 1.84.2
- OS Version: MacOS Monterey 12.7.1

For some reason, VSCode does not provide Python autocompletions for the `cv2` module installed through `conda`.

Steps to Reproduce:
1. Make sure `opencv` is installed by conda. (e.g. by running `conda install -c conda-forge opencv=4.8.1`.
2. Create a new `.py` file in VSCode and write `import cv2`.
3. Select the appropriate Python interpreter provided by conda
4. Write `cv2.`

This should trigger autocompletion, but the menu does not show up. This issue does not occur for other Python modules, such as `numpy` or `matplotlib`.

Extension version: 2023.20.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 7575e86b-e434-484d-8645-89363df807c7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2cf:30871583
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by Unturned3** [comment]
Hello! Any updates on this issue?

**Comment by StellaHuang95** [comment]
Thank you for the issue. I was able to reproduce it, and it seems like a bug where type stubs are not included in the conda install. A similar issue is being tracked at https://github.com/conda-forge/opencv-feedstock/issues/374.

**Comment by jomai1** [comment]
Hi was there any update on this issue?

**Comment by debonte** [comment]
@jomai1, I see that you also commented on the conda-forge issue mentioned above. That's the right place to ask. Pylance is behaving correctly here.
