### ISSUE TITLE
pyright command except generate stub is not connected to pylance

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5164]
it looks like at some point, we stopped calling pyright's command controller.

so pyright's code action such as `add missing optional params` or `order imports` no longer work.

basically, no one is handling these `PyrightCommand` anymore.
https://github.com/microsoft/pyrx/blob/main/packages/pylance-internal/src/commands/commandController.ts#L100

pylance should call pyright's command controller if commands are not one that pylance handle.

**Comment by heejaechang** [comment]
related issue - https://github.com/microsoft/pyright/issues/6571

**Comment by rchiodo** [comment]
This is probably my fault, sync/async server redesign.
