### ISSUE TITLE
Incorrect autocomplete suggestion for object.attribute.property if object.attribute's type is changed in Child class and attribute.property is returned from Parent's method

### ISSUE THREAD

**Issue by vishwa-raj** [microsoft/pylance-release#517]
## Environment data

-   Language Server version: 2010.10.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7, Anaconda

## Expected behaviour
In the following example:
object = Child()
attribute = data
property = keys()

As in Jedi:
![jedi](https://user-images.githubusercontent.com/22815753/97068012-51417000-15e1-11eb-8b66-99d0b40c594c.gif)

## Actual behaviour
As in Pylance:
![pylance](https://user-images.githubusercontent.com/22815753/97068013-530b3380-15e1-11eb-8f28-35145acdb254.gif)

## Code Snippet / Additional information
```
class Parent:
    def __init__(self):
        self.data = None

    def get_keys(self):
        return self.data.keys()


class Child(Parent):
    def __init__(self):
        super().__init__()
        
        self.data = dict()


c = Child()
keys = c.get_keys()

keys.

```

**Comment by erictraut** [comment]
You are calling the `get_keys` method, which has no type information provided. Pylance is therefore inferring its return type based on the information is has available in the `Parent` class. The only type information it has available is the assignment in the `__init__` method, where `self.data` is assigned a `None` value.

You can easily fix this by adding a type annotation in one of two places:
1. The accessor method:

```python
    def get_keys(self) -> dict:
        return self.data.keys()
```

2. The instance variable:

```python
        self.data: Optional[dict] = None
``

**Comment by vishwa-raj** [comment]
@erictraut I also realised that even if I simply return `self.data` in `get_keys()`, then the type information of output isn't updated according to the definition of `self.data` in `Child.__init__()`.
```
class Parent:
    def __init__(self):
        self.data = None

    def get_data(self):
        return self.data.keys()


class Child(Parent):
    def __init__(self):
        super().__init__()
        
        self.data = dict()


c = Child()
data = c.get_data()

keys.
```
But shouldn't it be able to update the type information of `self.data` from `__init__` method of Child class, as that's the object from where it's being invoked ?
And this feature works fine with Jedi.

**Comment by erictraut** [comment]
Jedi isn't a full type checker, so it works differently from Pyright/Pylance.

The type of an instance variable is established by the class where it is introduced, not by subclasses.

**Comment by vishwa-raj** [comment]
But this means that if `self.data` in `Parent` class is of `Base_Data` type and `self.data` in `Child` class if of `Derived_Data` type with some `new_method`,
then Pylance will never be able (currently isn't) to provide `new_method` as suggestion if we invoke `get_data()` from `Child` object,
which doesn't sound right.

```
class Base_Data:
    def __init__(self):
        pass


class Derived_Data(Base_Data):
    def __init__(self):
        super().__init__()
    
    def new_method(self):
        return


class Parent:
    def __init__(self):
        self.data = Base_Data

    def get_data(self):
        return self.data


class Child(Parent):
    def __init__(self):
        super().__init__()
        
        self.data = Derived_Data()


c = Child()
data = c.get_data()

data.
```

**Comment by erictraut** [comment]
This isn't a design pattern that I would generally recommend, but if you want to stick with this design pattern, the proper way to annotate it is to declare the base class as generic.

```python
from typing import Generic, TypeVar

class Base_Data:
    def __init__(self):
        pass

class Derived_Data(Base_Data):
    def __init__(self):
        super().__init__()

    def new_method(self):
        return

_T = TypeVar("_T", bound=Base_Data)

class Parent(Generic[_T]):
    def __init__(self):
        self.data: _T = Base_Data()

    def get_data(self) -> _T:
        return self.data

class Child(Parent[Derived_Data]):
    def __init__(self):
        super().__init__()

        self.data = Derived_Data()

c = Child()
data = c.get_data()
```

There are many benefits to building a language server on a type checker engine, but if you prefer the behavior provided by Jedi, it's still available as an option.

**Comment by jakebailey** [comment]
It's been over a month since we added the "waiting for info" tag without hearing back; I'm going to close this, but we can reopen it we believe there is still work to do here.
