### ISSUE TITLE
No docstrings for TypedDict on hover

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#5171]
## Code Snippet

```python
from typing import TypedDict
```

## Repro Steps

1. Hover `TypedDict`

## Expected behavior

hover tooltip shows docstring

## Actual behavior

hover tooltip doesn't show docstring

![image](https://github.com/microsoft/pylance-release/assets/100439259/aa94bb20-83d3-4e42-a82e-fad7bdccdcf9)

**Comment by debonte** [comment]
When I "go to def" on `TypedDict` it takes me to the definition of the `TypedDict` function in `typing.py`. I guess it's the docstring on that function that you are referring to? 

`TypedDict` isn't a type, it's a special form. So I think if we were going to do this it would be a special case in the hover provider.

**Comment by bschnurr** [comment]
the docstring appears to be in typing_extensions.py source

**Comment by debonte** [comment]
> the docstring appears to be in typing_extensions.py source

You're also referring to the docstring on the `TypedDict` function though, right?

**Comment by bschnurr** [comment]
yes

**Comment by luabud** [comment]
@heejaechang is this fixed by any chance?

**Comment by bschnurr** [comment]
I think this is fixed. 
![image](https://github.com/microsoft/pylance-release/assets/1946977/996b8aae-6482-4d49-a381-17f4755a63db)
