### ISSUE TITLE
"unknown import symbol" for symbol in unsaved file in symlinked directory

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5181]
## Environment data

-   Language Server version: 2023.11.100
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.0

## Repro Steps

1. `md repro`
2. `md reproSubdirTarget`
3. `cd repro`
4. `mklink /d subdir ..\reproSubdirTarget`       (requires admin permissions)
5. `code-insiders .`
6. `Create: New Jupyter Notebook`
7. Save in root of workspace.
8. In `subdir`, create `test1.py`
9. Add `def foo1(): return 1` to `test1.py`, but do not save the file.
10. Switch back to notebook and add `from subdir.test1 import foo1` in the cell.

## Expected behavior

No errors

## Actual behavior

"foo1" is unknown import symbol
![image](https://github.com/microsoft/pylance-release/assets/12820898/44ef6ef5-e6f0-4b14-b15f-3a396af9d616)

Closing and reopening the notebook has no effect. Error goes away if you save `test1.py` and then close/reopen the notebook.

If I replace step 4 with `md subdir` (i.e. replace the symlinked dir with a normal dir) the issue does not repro.

## Non-notebook is worse?
Follow the same repro steps but create a `.py` file in the root rather than a notebook.

In this case, you can save and close files all you like. It doesn't help. `Developer: Reload Window` fixes it though.

**Comment by judej** [comment]
need to check if this is a regression

**Comment by debonte** [comment]
Not a recent regression. This also repros in 2023.10.21.

**Comment by rchiodo** [comment]
This should be fixed with the URI change.

**Comment by debonte** [comment]
This was actually fixed in 2023.11.102 by https://github.com/microsoft/pyrx/pull/4375

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2023.12.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202312104-22-January-2024-PreRelease)
