### ISSUE TITLE
"Missing import" for modules in the same folder.

### ISSUE THREAD

**Issue by markshannon** [microsoft/pylance-release#5184]
Situation:
Two files.  `/path/to/foo.py` and `path/to/bar.py`

`foo.py` contains `import bar`.
This works fine when running `python foo.py` in `path/to` as the current working directory is added to the path.

Unfortunately pylance reports `Import "bar" could not be resolved".

This is a false positive.

I'm using the default version of pylance that comes bundled with VScode. Latest release on 2023-11-30

**Comment by CommanderPho** [comment]
I'm experiencing the same issue (along with many others) in my multi-folder workspace
