### ISSUE TITLE
don't show internal virtual cell file path in UI in type hierarchy

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5192]
currently pylance leak internal cell's virtual file name to UI.

![image](https://github.com/microsoft/pylance-release/assets/1333179/23738b8f-f615-45f4-be97-b5c70d0eb99a)

it should always use `real filepath` in UI. not the internal file name.

**Comment by debonte** [comment]
Show call hierarchy has the same issue -- https://github.com/microsoft/pylance-release/issues/3611

**Comment by debonte** [comment]
While investigating #5815, I realized that this issue is already fixed -- we show the notebook filename without the fragment. Looks like it happened during the URI work.
