### ISSUE TITLE
semantic token not refreshing on file watcher notification

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5193]
`pylance` is not sending `refresh` requests on `file change notification` from `file watcher`

see this (https://github.com/microsoft/pyrx/blob/8abca756d37995387d88853c21913a1f09cb6695/packages/pylance-internal/src/server/asyncServer.ts#L705C9-L711C10)
```ts
            this.connection.sendRequest(SemanticTokensRefreshRequest.method).ignoreErrors();
            this.connection.sendRequest(InlayHintRefreshRequest.method).ignoreErrors();
```
one can repro it using
https://github.com/microsoft/pylance-release/blob/0945dea30d3276dcf945543aa4f5f75c84aa4136/testing/single/src/fileWatcher.py#L4C1-L6C24

**Comment by bschnurr** [comment]
https://github.com/microsoft/pyrx/pull/4471
