### ISSUE TITLE
pylance crash when notebook is opened and change vscode to `restricted mode`

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5194]
1. open notebook in a workspace
2. create a few python cells
3. open `Workspaces: Manage Workspace Trust` using `command palette`
4. change the workspace to `in restricted mode`

expected: notebook moves to restricted mode
actual: pylance crash with some assert.

use this test - https://github.com/microsoft/pylance-release/blob/main/testing/single/src/notebook.ipynb and follow instructions on this cell
`# test basic trusted workspace in notebook context`

**Comment by rchiodo** [comment]
I'm guessing this is a dupe of #5152

**Comment by rchiodo** [comment]
Although this repro seems easier.

**Comment by debonte** [comment]
Pylance is shutdown and restarted when the workspace changes to untrusted. On restart, we receive `textDocument/didOpen` messages for each of the cells before we receive the `notebookDocument/didOpen`. Pylance crashes in `getNotebookCellPath` on receiving the first `textDocument/didOpen` because the `_uriToPath` map is empty. Normally when a notebook is opened we don't receive any `textDocument/didOpen` messages for the cells.

@rebornix, would this be a vscode bug?

```text
UriMapper.getNotebookCellPath (c:\src\pyrx2\packages\pylance-internal\src\common\uriMapper.ts:150)
PylanceUriParser.decodeTextDocumentUri (c:\src\pyrx2\packages\pylance-internal\src\common\pylanceUriParser.ts:23)
PylanceAsyncServer.onDidOpenTextDocument (c:\src\pyrx2\packages\pylance-internal\src\server\asyncServer.ts:1013)
<anonymous> (c:\src\pyrx2\packages\pyright\packages\pyright-internal\src\languageServerBase.ts:674)
handleNotification (c:\src\pyrx2\packages\pyright\packages\pyright-internal\node_modules\vscode-jsonrpc\lib\common\connection.js:640)
handleMessage (c:\src\pyrx2\packages\pyright\packages\pyright-internal\node_modules\vscode-jsonrpc\lib\common\connection.js:342)
processMessageQueue (c:\src\pyrx2\packages\pyright\packages\pyright-internal\node_modules\vscode-jsonrpc\lib\common\connection.js:362)
```

**Comment by debonte** [comment]
@rchiodo, any thoughts on [this](https://github.com/microsoft/pylance-release/issues/5194#issuecomment-1863617530)?

**Comment by rchiodo** [comment]
We need the notebook open before we get the text document open. I think this would be a VS code issue then.

**Comment by rchiodo** [comment]
althought maybe VS code is not the one sending these messages? It might be the [vscode language client npm module](https://github.com/microsoft/vscode-languageserver-node).

**Comment by debonte** [comment]
Removing `vscode-notebook-cell` documents from our documentSelector caused hover, semantic highlighting, etc to break for notebooks. Need to find another way to address the crash.

**Comment by debonte** [comment]
This is caused by a bug in vscode-languageclient. I filed an issue: https://github.com/microsoft/vscode-languageserver-node/issues/1394

**Comment by debonte** [comment]
Dirk determined that this is actually caused by a bug in vscode, and he can't work around it in vscode-languageclient -- https://github.com/microsoft/vscode/issues/202232

**Comment by debonte** [comment]
This was fixed in VS Code insiders this morning. https://github.com/microsoft/vscode/issues/202232
