### ISSUE TITLE
show non-basic/partial type errors as warnings

### ISSUE THREAD

**Issue by goyalyashpal** [microsoft/pylance-release#5200]
* allow for the vscode setting of `python.analysis.typeCheckingMode` 
* to be able to customise the severity level i.e. error, warn, info, etc. on the basis of checking modes "basic" | "strict" etc.

---- 
Same requirement mentioned in the wild:
* @ gramster [suggestion][gm-gh-wf] for the gh-workflow
* SO question: [68832821] show-all-non-critical-typing-errors-as-warnings

[68832821]: https://stackoverflow.com/q/68832821/ "show-all-non-critical-typing-errors-as-warnings"
[gm-gh-wf]: https://github.com/microsoft/pyright/issues/3066#issuecomment-1043612153

### Versions

* `ms-python.vscode-pylance`: 2023.6.11

----
duplicate search 🔍 : [partial type errors as warnings] | [non-basic as warn] | [strict as warn]

[non-basic as warn]: https://github.com/microsoft/pylance-release/issues?q=is%3Aissue+non-basic+as+warn
[strict as warn]: https://github.com/microsoft/pylance-release/issues?page=2&q=is%3Aissue+strict+as+warn
[partial type errors as warnings]: https://github.com/microsoft/pyright/issues?q=is%3Aissue+partial+type+errors+as+warnings

**Comment by debonte** [comment]
@goyalyashpal, does the `diagnosticSeverityOverrides` setting do what you want? Here is the setting description:

> Allows a user to override the severity levels for individual diagnostics. Use the rule name as a key and one of \"error\", \"warning\", \"information\", \"none\", `true` (alias for \"error\") or `false` (alias for \"none\") as value. The default value shown for each diagnostic is the default when \"python.analysis.typeCheckingMode\" is set to \"off\". See [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults) for defaults for each type checking mode (\"off\", \"basic\" and \"strict\").

If this doesn't solve your problem, can you please explain in more detail what you're asking for?

**Comment by goyalyashpal** [comment]
> See [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults) for defaults for each type checking mode ("off", "basic" and "strict").





> does the diagnosticSeverityOverrides setting do what you want?



hi! 
* it's halfway there; 
* as using this alone, i'll have to define the `severity level` value for most of these settings
* as shown in following permalink/screenshot
* which ain't very good solution

<details>
<summary><a href="https://github.com/microsoft/pyright/blob/dc3e56bf51cdd3d89146ed9116f4650de67bb086/docs/configuration.md?plain=1#L338-L365">docs/configuration.md?plain=1#L338-L365</a> Click me to show image</summary>

<br/>
<img src="https://github.com/microsoft/pylance-release/assets/19423063/c20d439f-a9b5-4ffd-8446-5b8433615982" width=575px />

</details>

<br/>

> explain in more detail what you're asking for?

is there some way to group the `diagnostic rule` keys (say a json arraylist or json object etc.) using which i can set value for all these at once??

based on the given defaults, 
* i was able to come up with following categorisation. 
* ofcourse, the name is just ad-hoc here, but it can be refined.
* if assumed `true` == `"error"` and `false` == `"warning"`, then these are 5 to 7 different arraylists in total
* this would make such configuration suuper simple to _something_ like:

```jsonc
"python.analysis.diagnosticSeverityOverrides": {
    ["strictError"]: "warning",
},
```

<details open>
<summary><h4>Categorisation of <tt>rules</tt> by <tt>checking mode</tt>-<tt>Severity level</tt></h4></summary>

<br/>

```
any-true: (50)
analyzeUnannotatedFunctions
strictParameterNoneValue
enableTypeIgnoreComments

any-"warning": (-)
reportMissingModuleSource

off-"warning": (45)
reportMissingImports
reportUndefinedVariable

basic-"error": (40)
reportGeneralTypeIssues
reportOptionalSubscript
reportOptionalMemberAccess
reportOptionalCall
reportOptionalIterable
reportOptionalContextManager
reportOptionalOperand
reportTypedDictNotRequiredAccess
reportPrivateImportUsage
reportUnboundVariable
reportUnusedCoroutine

standard-"error": (35)
reportFunctionMemberAccess
reportIncompatibleMethodOverride
reportIncompatibleVariableOverride
reportOverlappingOverload

basic/standard-"warning": (30)
reportAssertAlwaysTrue
reportInvalidStringEscapeSequence
reportInvalidTypeVarUse
reportMissingTypeStubs
reportSelfClsParameterName
reportUnsupportedDunderAll
reportUnusedExpression
reportWildcardImportFromLibrary

strict-true: (20)
disableBytesTypePromotions
strictListInference
strictDictionaryInference
strictSetInference

strict-"error": (20)
reportConstantRedefinition
reportDeprecated
reportDuplicateImport
reportIncompleteStub
reportInconsistentConstructor
reportInvalidStubStatement
reportMatchNotExhaustive
reportMissingParameterType
reportMissingTypeArgument
reportPrivateUsage
reportTypeCommentUsage
reportUnknownArgumentType
reportUnknownLambdaType
reportUnknownMemberType
reportUnknownParameterType
reportUnknownVariableType
reportUnnecessaryCast
reportUnnecessaryComparison
reportUnnecessaryContains
reportUnnecessaryIsInstance
reportUnusedClass
reportUnusedImport
reportUnusedFunction
reportUnusedVariable
reportUntypedBaseClass
reportUntypedClassDecorator
reportUntypedFunctionDecorator
reportUntypedNamedTuple

"none": (0)
reportCallInDefaultInitializer
reportImplicitOverride
reportImplicitStringConcatenation
reportImportCycles
reportMissingSuperCall
reportPropertyTypeMismatch
reportShadowedImports
reportUninitializedInstanceVariable
reportUnnecessaryTypeIgnoreComment
reportUnusedCallResult

false: (0)
deprecateTypingAliases
enableExperimentalFeatures
```

</details>

**Comment by debonte** [comment]
Before talking about solutions, can you explain what you're trying to accomplish? Why do you want to manipulate the severity of these rules in these severity level groups?

**Comment by goyalyashpal** [comment]
> what you're trying to accomplish?

* i want to be able to know what parts of type specification i am missing
* ... so as to expand my knowledge 
* ... as well as make an informed decision of how much type annotation _i_ can provide
* but i don't want to be forced to cater to _all rules_.

currently:
* with everything labelled "error" in strict mode, i loose the granularity (& shown half cents of errors)
* or with other modes, - those rules are shown "none", i loose the knowledge of what did i omit

this _knowledge for informed decision_ + _granularity_ is what i am trying to accomplish.

it would come a lot handy when you are dealing with large amount of untyped (i.e. not annotated) python code and are given task to make it _reasonably_ typed.

**Comment by erictraut** [comment]
Currently, pylance supports three type checking modes:
* off: No type checking rules are enabled. Only basic issues like syntax errors are reported.
* basic: Simple type checking rules are enabled. These rules enforce basic type compatibility rules but do not include checks that have a higher likelihood of producing false positive errors. This mode is recommended for people who may not have historically used type annotations or static type checking and are generally unwilling to make changes to their code to accommodate static type checking.
* strict: Many more type checking rules are enabled. These rules enforce the full static typing specific and also report conditions that are likely to indicate bugs or unintended behaviors in the code. You will generally need to make changes to your code to use this mode successfully. This mode also generally requires fully-typed libraries or type stubs.

Pyright (the type checker upon which pylance is built) recently added another type checking mode that falls between "basic" and "strict".
* standard: Includes all of the checks that are required to conform to the Python static typing spec but does not include some of the other checks in "strict" mode.

The latest production release of pylance doesn't yet have support for "standard" mode, but the next release will.

In any of these type checking modes, you can override the default settings for individual rules. These can be overridden on a per-project basis or even a per-file basis. For more details, refer to the pyright documentation for [configuration](https://microsoft.github.io/pyright/#/configuration) and [comments](https://microsoft.github.io/pyright/#/comments).

Based on what you're saying about your own needs, I recommend that you stick to "basic" type checking mode and then gradually enable a few additional diagnostic rules that you think might be useful. Refer to [this table](https://microsoft.github.io/pyright/#/configuration?id=diagnostic-rule-defaults) for a full list of supported diagnostic rules.
