### ISSUE TITLE
Pyright reports import warning "X could not be resolved from source" for pygobject modules while stubs installed

### ISSUE THREAD

**Issue by its-darsh** [microsoft/pylance-release#5204]
## Environment data

-   Language Server version: `v2023.11.10`
-   OS and version: Arch Linux, with kernel `6.5.9-arch2-1`
-   Python version: `3.11.5`

## Code Snippet

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
```

## Repro Steps

1. Remove anything have something to do with [fakegir](https://github.com/strycore/fakegir) generated files from code (if any)
2. Install the stubs package (pygobject-stubs) or use [gengir](https://github.com/santiagocezar/gengir) to generate the stubs

## Expected behavior

Code suggestions work without any warnings

## Actual behavior

Code suggestions work while pyright reports an import error

## Logs

```
2023-12-04 03:05:09.670 [info] (65446) [BG(1)] getSemanticTokens full at [file] (12ms)
2023-12-04 03:05:09.909 [info] (65446) [BG(1)] indexing: [file] [found 1] (0ms)

```

## Notes

1. Using [fakegir](https://github.com/strycore/fakegir) works fine but fakegir doesn't have right type annotations or right formatted docs
2. According to #196 adding `# type: ignore` or `# pyright: ignore[reportMissingModuleSource]`  to import lines _fixes_ the issue, this is a solution but this isn't an ideal for me since i have a big amount of files to edit like this
3. adding the option `"python.analysis.diagnosticSeverityOverrides": {"reportMissingModuleSource": "none"}` will also not help because there is multiple users working on the same project, also this seems to be an issue with pylance

## Image

![image](https://github.com/microsoft/pylance-release/assets/129121284/01b63c2e-e795-4e0f-9b9a-4ec02d18e46e)

**Comment by cas--** [comment]
I'm glad someone has reported this issue as I have really be puzzling over Pylance reporting `reportMissingModuleSource` warnings even though `pygobject-stubs` is installed in virtural env.

Thankfully installing fakegir did suppress the warnings but not ideal solution...

**Comment by its-darsh** [comment]
> I'm glad someone has reported this issue as I have really be puzzling over Pylance reporting `reportMissingModuleSource` warnings even though `pygobject-stubs` is installed in virtural env.
> 
> Thankfully installing fakegir did suppress the warnings but not ideal solution...

thanks, though, i wonder why there's no response from their side til this day

**Comment by debonte** [comment]
`reportMissingModuleSource` diagnostics are shown "when a type stub is found, but the module source file was not found, indicating that the code may fail at runtime when using this execution environment." (quoted from https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource).

So if you have the stubs installed, but not the actual package, this is expected and by design.

> adding the option "python.analysis.diagnosticSeverityOverrides": {"reportMissingModuleSource": "none"} will also not help because there is multiple users working on the same project

You could add it to the workspace settings (i.e. `.vscode/settings.json` off the root of your workspace) and check that file into source control.

**Comment by erictraut** [comment]
You can also add it to a `pyrightconfig.json` or `pyproject.toml` file as described [here](https://microsoft.github.io/pyright/#/configuration).
