### ISSUE TITLE
Verification of `Protocol` methods not working when using explicit sub-classing

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#5205]
## Environment data

-   Language Server version: Pylance language server 2023.11.10
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11, Anaconda

## Code Snippet

The snippet below works correctly (screen shot below)
The error message tells that the type of argument of the first method is not compatible with the Protocol

### Example that works OK

```python
from typing import Protocol


class System(Protocol):
    def send_x_int(self, x: int) -> str:
        ...

    def send_y_float(self, y: float) -> str:
        ...


def foo(sys: System):
    sys.send_x_int(5)


class MySystem:
    def send_x_int(self, x: str) -> str:
        return str(x)

    def send_y_float(self, y: float) -> str:
        return str(y)


foo(MySystem()) # ERROR!

```
![image](https://github.com/microsoft/pylance-release/assets/57204023/5d570909-fcbe-4fcf-ad69-0f155ad908fb)

Message:
```
Argument of type "MySystem" cannot be assigned to parameter "sys" of type "System" in function "foo"
  "MySystem" is incompatible with protocol "System"
    "send_x_int" is an incompatible type
      Type "(x: str) -> str" cannot be assigned to type "(x: int) -> str"
        Parameter 1: type "int" cannot be assigned to type "str"
          "int" is incompatible with "str"
```

### Example with possible issues

On the other hand, when explicit sub-classing the Protocol the error message is gone.
This is done on the next snippet

```python
from typing import Protocol


class System(Protocol):
    def send_x_int(self, x: int) -> str:
        ...

    def send_y_float(self, y: float) -> str:
        ...


def foo(sys: System):
    sys.send_x_int(5)


class MySystem(System): # <- subclass!
    def send_x_int(self, x: str) -> str:
        return str(x)

    def send_y_float(self, y: float) -> str:
        return str(y)


foo(MySystem()) # No error anymore

```

## Expected behavior

Expect the same error message in both snippets above.
It should check the signature of the implement method and verify that it is incompatible with the protocol (` "int" is incompatible with "str"`). 
That does not happen when sub-classing the protocol.

## Actual behavior

The error message does not appear.

**Comment by erictraut** [comment]
You need to enable the `reportIncompatibleMethodOverride` diagnostic rule if you want this error to be generated. This rule is not enabled by default in the "basic" type checking mode. You can either enable it manually or use "strict" mode, where it is enabled.

An upcoming version of pyright (the type checker upon which pylance is built) will also include a "standard" type checking mode that includes `reportIncompatibleMethodOverride` by default. It will remain off by default in "basic" mode.
