### ISSUE TITLE
how many

### ISSUE THREAD

**Issue by Lakmalsampath** [microsoft/pylance-release#5208]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue but there isn't enough information for us to resolve your problem. If you have more information, please reopen.
