### ISSUE TITLE
Feature request: Support 'go to def' and interacting with inlay hint components

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#5210]
Inlay hints are now interactive for JS/TS in VS Code Insiders: 

![image](https://github.com/microsoft/pylance-release/assets/45497113/68ebc3d1-053a-4682-aa09-f2aa8777dcc2)

Related issues/PRs on the TS side:
- https://github.com/microsoft/TypeScript/issues/47693
- https://github.com/microsoft/TypeScript/pull/54734
- https://github.com/microsoft/TypeScript/pull/55141
- https://github.com/microsoft/TypeScript/pull/55918
- LSP spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHintLabelPart

**Comment by heejaechang** [comment]
LSP spec - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHintLabelPart

**Comment by rchiodo** [comment]
Shouldn't we put this in triage as nobody is currently assigned?

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.8.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20248101-12-August-2024-PreRelease)
