### ISSUE TITLE
Add import quick action cannot find `SupportsNext`

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5215]
Using this code, the `SupportsNext` is not found
```python
from enum import StrEnum
import json
import os
import re
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing_extensions import Union, Tuple, Dict, Callable

def set_target(kind: str, parser: Callable[[str], str] = (lambda x: x), positional=False):
    def do(arg: str, it: SupportsNext): # SupportsNext should show an error
        options.target_kind = kind
        target = parser(arg if positional else next(it))

        if isinstance(target, bytes):
            # target may be the code, so, try some additional encodings...
            try:
                target = target.decode(sys.getfilesystemencoding())
            except UnicodeDecodeError:
                try:
                    target = target.decode("utf-8")
                except UnicodeDecodeError:
                    import locale

                    target = target.decode(locale.getpreferredencoding(False))
        options.target = target

    return do
```

Quick action offers nothing:

![image](https://github.com/microsoft/pylance-release/assets/19672699/7ebde375-efba-4d17-bcbd-09922955eff3)

But `SupportsNext` is found in the typeshed:

![image](https://github.com/microsoft/pylance-release/assets/19672699/6b1b55ad-2d36-46da-9868-d1bd325679c2)

Shouldn't pylance be able to find it?

**Comment by rchiodo** [comment]
If I turn off exact matches, I get this:
![image](https://github.com/microsoft/pylance-release/assets/19672699/8a2be49a-6ab9-414f-821c-5e1678a99af4)

But none of the ones in the stdlib

**Comment by Avasam** [comment]
Could it be because private modules are excluded from suggestions?

**Comment by rchiodo** [comment]
> Could it be because private modules are excluded from suggestions?

Yeah that's it. It's in `_typeshed`, not `typeshed`.

**Comment by rchiodo** [comment]
It's better to use `Iterable` here anyway. That is public.

```python
def set_target(kind: str, parser: Callable[[str], str] = (lambda x: x), positional=False):
    def do(arg: str, it: Iterable[str]): 
        options.target_kind = kind
```

Probably why `SupportsNext` isn't public.

**Comment by Avasam** [comment]
`_typeshed` isn't public because nothing in there exists at runtime. So if used outside of stubs, `_typeshed` imports must be wrapped in a `TYPE_CHECKING` check.
