### ISSUE TITLE
Inconsistent use of '...' in UI labels

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#5218]
Type: <b>Bug</b>

Two quick things I notied with how `...` is used in ui labels:

- In `move to file`, `...` should not be used for the section label (`Destination files ...`)

- In a few places in the UX, the `...` is has a space before it: `Label ...`. I believe the convention is to omit the space: `Label...`

![Image](https://github.com/microsoft/vscode-python/assets/12821956/dccc2f09-0368-421d-af91-0394158ae25c)

Extension version: 2023.23.13391009
VS Code version: Code - Insiders 1.85.0-insider (Universal) (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T11:18:22.866Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (1.94GB free)|
|Process Argv|--crash-reporter-id 0fffb5da-9cd7-46fd-9e7f-a1564e8c5fda|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Also `Destination files` should be lowercase to match our other separator labels: https://github.com/microsoft/vscode/pull/200184

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.12.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202312101-20-December-2023-PreRelease)
