### ISSUE TITLE
Goto def doesn't work in VS code.dev

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5222]
```python

from typing import TypedDict


class Enemies(TypedDict):
    Goblin: int
    Hobgoblin: int

the_dict: Enemies = {
    "Goblin": 1,
    "Hobgoblin": 2
}
```

Open this file in vscode.dev
Goto def from the `the_dict: Enemies` on the `Enemies`.

Expected:
It jumps up to the the class.

Actual:
It tries to open a `memfs` file.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2023.11.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202311104-7-December-2023-PreRelease)
