### ISSUE TITLE
The help pop up does not show up for method chains

### ISSUE THREAD

**Issue by joelostblom** [microsoft/pylance-release#5223]
I was adviced to migrate this issue here from https://github.com/microsoft/vscode-jupyter/issues/10004

## Environment data

-   VS Code version: 1.67
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1011282140
-   Python Extension version (available under the Extensions sidebar): v2022.6.0
-   OS (Windows | Mac | Linux distro) and version: PopOS 21.10
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | local

## Expected behaviour

The help for the method would show up correctly

## Actual behaviour and step to reproduce

If I type the name of a top level object, the help bubble shows up fine:
![image](https://user-images.githubusercontent.com/4560057/168144471-e8f288ae-087b-4f1b-8ea1-d586b734255a.png)

If I chain a function to this object I get either just a single line in the help bubble, or the same message as for the parent object 
![image](https://user-images.githubusercontent.com/4560057/168144777-42716204-4c78-4c3d-97ad-4de94cb53c5b.png)

## Logs

The output pane is empty

**Comment by debonte** [comment]
I'm not seeing this behavior. I'm using:
- VS Code: 1.88.0-insider
- Python extension: v2023.8.0
- Jupyter extension: v2024.3.2024030101 
- Pylance extension: v2024.2.105

The VS Code and extension versions that you mentioned above are very old. Please upgrade to latest and we can reactivate this issue if it's still not fixed for you.

![image](https://github.com/microsoft/pylance-release/assets/12820898/3d3661c8-31fb-4cd5-be6c-18b8b151317b)

**Comment by joelostblom** [comment]
Thanks @debonte , I just tried again with v1.86 and I see the popup like in your screenshot so that is great! I noticed that I no longer see a comprehensive popup for the first part of the chain, e.g. `pd.DataFrame(` just shows `() -> None` instead of the full dosctring that shows when I hover with the mouse over that class. Do you see the same thing?

**Comment by debonte** [comment]
> Do you see the same thing?

Yes. Looks like this regressed in Pyright 1.1.335. Could you file an issue at https://github.com/microsoft/pyright/issues?

**Comment by joelostblom** [comment]
Thanks for confirming, I filed https://github.com/microsoft/pyright/issues/7405
