### ISSUE TITLE
Pylance is incorrectly reporting that an attribute, inherited from a parent protocol, is missing

### ISSUE THREAD

**Issue by jreich218** [microsoft/pylance-release#5238]
<h3> Environment data </h3>

-   Language Server version: 2023.11.10
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): Python 3.11.7
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Code Snippet </h3>

```python
from typing import Protocol


class ShapeProtocol(Protocol):
    color: str


class CircleProtocol(ShapeProtocol):
    radius: float

```

<h3> Repro Steps </h3>

The above code should be sufficient for generating the following Pylance response to `CircleProtocol`:

'Class derives from one or more protocol classes but does not implement all required members
  Member "color" is declared in protocol class "ShapeProtocol" Pylance([reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues))'

<h3> Expected behavior </h3>

The above Pylance response should not have been present at all because color is inherited from ShapeProtocol.

<h3> Actual behavior </h3>

The following Pylance response to `CircleProtocol`:

'Class derives from one or more protocol classes but does not implement all required members
  Member "color" is declared in protocol class "ShapeProtocol" Pylance([reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues))'

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is behaving correctly here. You've defined a protocol class that indicates that any compatible classes must implement an instance variable `color`. You've then created a non-protocol subclass that explicitly derives from the protocol class, but it fails to implement the required instance variable.

You can fix your code in one of two ways:
1. Implement the `color` instance variable in the `CircleProtocolClass`:
```python
class CircleProtocol(ShapeProtocol):
    color = ""
    radius: float
```

2. Indicate that `CircleProtocol` is also intended to be a protocol class.
```python
class CircleProtocol(ShapeProtocol, Protocol):
    radius: float
```

I suspect that 2 is what you intended here. If you don't include the `Protocol` base class here, a static type checker will assume that this is a non-protocol class. For details, refer to [PEP 544](https://peps.python.org/pep-0544).
