### ISSUE TITLE
"python.analysis.inlayHints.functionReturnTypes" not recognized in python 2022.16.1 

### ISSUE THREAD

**Issue by ezeid** [microsoft/pylance-release#5243]
Environment:
VS Code Version: v4.5.2 (code-server)
OS Version: Cloud SageMaker using (python) v2022.16.1

Steps to Reproduce:
Preferences Open Settings (.JSON)
Add into settings.json: python.analysis.inlayHints.functionReturnTypes": true
3- the entry show: "unknown configuration setting" and typehint does not take effect

![vscode_issue](https://github.com/microsoft/vscode-python/assets/71358531/72cf8c38-82d3-43a6-bf75-2a4884279bfd)

**Comment by ezeid** [comment]
@bschnurr  Let me know if you have questions on this item. I appreciated updates asap.

**Comment by ezeid** [comment]
> Those settings actually come from the Pylance extension. Do you have that extension installed?
Yes as you can see in the image below:
![image](https://github.com/microsoft/pylance-release/assets/71358531/62ab5557-2c27-46af-a52a-5296c1acddaa)

**Comment by debonte** [comment]
@ezeid, the list is showing the Python extension. The Pylance extension is a separate extension. Looks like you don't have it installed. Here's mine:

![image](https://github.com/microsoft/pylance-release/assets/12820898/6102b58f-c597-4689-a51f-b97a9360f2fc)

**Comment by bschnurr** [comment]
Closing. Please let us know if you have an more issues.
