### ISSUE TITLE
Client Pylance: connection to server is erroring.

### ISSUE THREAD

**Issue by wdroom** [microsoft/pylance-release#5245]
I experienced the problem that Python Language Server cannot be started, thus checking function in the python code is not possible any more. after checking former articles and my testing, finally, I find out this problem seems to be related to the workspace limitation to contain the qty of project folders, do you have specific figures, how many project folders can be configured in a workspace file?
## Environment:
vsCode version: 1.85.0
Python version: v2023.22.0
Pylance version: v2023.11.10
use workspace to contain multiple project folder
## Picture of error messages:
Client Pylance: connection to server is erroring. wirte EPIPE
Connection to server got closed. Server will not be restarted.
Client Pylance: connection to server is erroring. Channel closed
![Uploading 2023-12-12_10h51_44.jpg…]()

**Comment by Immortals-33** [comment]
I got this bug too on my remote explorer. 

If I don't set the python interpreter on my remote explorer, the Pylance didn't work and showed a strange behavior: 
![image](https://github.com/microsoft/pylance-release/assets/85551178/9f176a50-2a93-427b-8877-529281ee4c44)

But if I set the interpreter, the above error occurs: 
![1702369316799](https://github.com/microsoft/pylance-release/assets/85551178/c46dcbf8-4445-42fa-bf9d-f4f808ae72c6)

Has anyone encountered this issue? I've tried uninstalling and reinstalling the Python and Pylance, but it didn't work.

**Comment by wdroom** [comment]
uninstall and reinstall python and pylance did not help, the problem was solved today for my own requirement, I found that it will work well when directly openning a folder or open a workspace with limited folders inside; but when more folders added in workspace, this error will appear, thus I think there should be some limitation for the quantity of folders in workspace configuration file, it is better to know how many can be afforded.

**Comment by wdroom** [comment]
> > Uploading 2023-12-12_10h51_44.jpg…
> 
> > Can somebody guide how to attach a picture into this post?
> 
> It looks like you were in the process of uploading the image to GitHub when you saved the issue. IMO the simplest way is to drag the image file into the issue text editor.

this did not work for me, I tried, but still under uploading.

**Comment by heejaechang** [comment]
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

if you can't get those logs, we will probably need some sample project we can use to repro.

**Comment by heejaechang** [comment]
please reopen if it still an issue.
