### ISSUE TITLE
Python Packages Not Recognized

### ISSUE THREAD

**Issue by fny** [microsoft/pylance-release#5247]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I expect imported packages to be clickable and have relevant type information besides any. However, the package is clearly unrecognized despite being installed. This is specific to the Blender python package (bpy)

## Steps to reproduce:

Install Python vscode extension.

Install Blender's Python package `pip install bpy`

Import it or any of its subpackages (e.g. mathutls, bpy_types, bmesh)

Ensure proper environment is selected. Visit built-in vscode terminal, run python, import packages. See that all packages are installed properly.

None of the packages will be recognized in vscode.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Pyenv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Blank
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.22.0
VS Code version: Code 1.85.0 (Universal) (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:18:04.614Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id f6f1381b-3f7f-40d2-9d6d-ed4a479031e7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. 

This is because bpy is a native python module. It doesn't have any python code for us to parse. These libraries require type stubs in order to work.

See the documentation about type stubs here: https://microsoft.github.io/pyright/#/type-stubs?id=importance-of-type-stub-files, specifically bullet point #2.

See this issue that somebody else already brought about blender:
https://github.com/microsoft/pylance-release/issues/4580

The good news is that a 3rd party has provided those type stubs:
https://pypi.org/project/blender-stubs/

If you install those stubs, Pylance should provide completions for most blender types (it does depend upon the quality of the stubs)

**Comment by rchiodo** [comment]
This is what it looks like after installing `blender-stubs`

![image](https://github.com/microsoft/pylance-release/assets/19672699/f52252f2-de50-43b5-8adb-c6536374c874)
