### ISSUE TITLE
syntax highlight broken for partialmethods

### ISSUE THREAD

**Issue by T-256** [microsoft/pylance-release#5250]
![image](https://github.com/microsoft/pylance-release/assets/132141463/90fc7bea-0b78-4a1a-a766-7f90924a8b96)
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
from curl_cffi import requests

async def main():
    async with requests.AsyncSession() as s:
        r = await s.get(URL)

```

## Repro Steps
pip install curl-cffi
Use above snippet.
I can confirm IntelliSense works.

## Expected behavior

highlight `get` to green

## Actual behavior

not highlight `get` to green

## Logs

```
XXX
```

**Comment by bschnurr** [comment]
thanks for logging an issue.  I dont there is a token issue.. I'm seeing `get` as a variable.  I did see an issue with the highlight not updating after pip installing `curl-cffi` though

![image](https://github.com/microsoft/pylance-release/assets/1946977/621486d5-8761-4828-8025-de28bd9d9505)

![image](https://github.com/microsoft/pylance-release/assets/1946977/131dce72-996b-4279-93c6-b56397ea6333)

![image](https://github.com/microsoft/pylance-release/assets/1946977/536090de-8043-4ab0-bab3-60395a681e40)



Note there is a tool to inspect tokens
![image](https://github.com/microsoft/pylance-release/assets/1946977/041b31cf-ec8e-4dbf-8d02-a06722d3e310)

**Comment by bschnurr** [comment]
maybe request custom support for partialmethod in pyright
https://github.com/microsoft/pyright/issues/2787

**Comment by erictraut** [comment]
This is related to https://github.com/microsoft/pyright/issues/2787. Pyright (the type checker upon which pylance is built) currently has no special-case handling of `functools.partialmethod`. It does have special-case handling for `functools.partial`. The logic for `partialmethod` should be similar, but there are challenges because of the way `partialmethod` is defined in the typeshed stubs. Notably, the `partialmethod` class doesn't include a `__call__` method. That means this change is complicated because it would involve not only a change in pyright but also a coordinated change in typeshed.

If this is something you're interested in, please upvote [this issue](https://github.com/microsoft/pyright/issues/2787). Even though it's closed, it's something I'd consider re-opening if there's sufficient interest.

**Comment by T-256** [comment]
> Notably, the `partialmethod` class doesn't include a `__call__` method.

Correct, make senses.




> That means this change is complicated because it would involve not only a change in pyright but also a coordinated change in typeshed.

Couldn't consider `functools.partialmethod` as special case?

Thanks, I upvoted that issue.
My main issue is beating to get parameter guide and parameter suggestion here:
![image](https://github.com/microsoft/pylance-release/assets/132141463/583545a9-23a7-428a-a436-1716d26bbf9b)

Now I should go to definition and scroll to `request` for checking parameters I'm using are correct or not.

**Comment by debonte** [comment]
If you want to see this issue fixed, please upvote https://github.com/microsoft/pyright/issues/2787. Closing this issue for now.

**Comment by randolf-scholz** [comment]
> Notably, the `partialmethod` class doesn't include a `__call__` method. That means this change is complicated because it would involve not only a change in pyright but also a coordinated change in typeshed.

Wouldn't this be kind of a lie?

```python
>>> from functools import partial, partialmethod
>>> partial(len).__call__
<method-wrapper '__call__' of functools.partial object at 0x7fa555381da0>
>>> partialmethod(len).__call__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'partialmethod' object has no attribute '__call__'. Did you mean: '__class__'?
```

Instead, shouldn't this be handled via Descriptor protocol? [typeshed annotates](https://github.com/python/typeshed/blob/96697a835b220daf5053f5520c9ce2588d34d28a/stdlib/functools.pyi#L140-L152)

```python
    def __get__(self, obj: Any, cls: type[Any] | None = None) -> Callable[..., _T]: ...
```
