### ISSUE TITLE
Possible false positive for pydantic v2 model with default value in Annotated field

### ISSUE THREAD

**Issue by declaresub** [microsoft/pylance-release#5252]
## Environment data

-   Language Server version: 2023.11.10 (pyright 088ebaa5)
-   OS and version: MacOS 14.1.2
-   Python version 3.12.0

Consider the following code, borrowed with modification from #4792 :

```
from pydantic import BaseModel, Field
from typing import Annotated

class Image(BaseModel):
    #url: str | None = Field(default=None, title='The URL of the image')
    url: Annotated[str | None, Field(default=None, title='The URL of the image')]
    name: str

img = Image(name='example')
```

pyright flags the last line with 'Argument missing for parameter "url"'.  If I replace the definition of url with the one not using Annotated, pyright does not mark the url parameter for missing argument.

PEP 681 does not mention the use of Annotated types, so I don't know whether or not this is in fact a bug.

**Comment by erictraut** [comment]
The stdlib dataclass — and therefore PEP 681's `dataclass_transform` — do not support the use of a field in an `Annotated` statement. In general, type checkers do not (and should not) interpret `Annotated` type arguments other than the first one. This is pydantic-specific behavior.

If you want your code to work with static type checking, you should use the form that is commented out in your code above.

**Comment by declaresub** [comment]
Aha.  Thanks for clarifying.
