### ISSUE TITLE
 Pylance will not give an error report when the type hint and the actual type of the value don't match

### ISSUE THREAD

**Issue by ydmykr** [microsoft/pylance-release#5266]
Here's the example:

```
class Prop[T]:
  def __init__(self,name:str,value:T) -> None:
    self.name: str=name
    self.value: T=value
    self._type= type(value)

prop=Prop[float](name='prop',value=True)
```

Prop should hold a value of type float. But I'm passing in a boolean value True when creating an instance of Prop. This is a type mismatch.

Can Pylance give an error report to remind it?

I've tried to set **Type Checking Mode** to `basic` or `strict`, both of them didn't work.

**Comment by erictraut** [comment]
Pylance is working correctly here. This isn't a bug.

In the Python type system, a `bool` is a subclass of `float`, so a type checker will not report an error for your code sample.

```python
x: float = True  # Not a type violation
```
