### ISSUE TITLE
Seeking Guidance on Type Annotation for Inherited Generic Classes in Pylance

### ISSUE THREAD

**Issue by Janus-Shiau** [microsoft/pylance-release#5267]
## Environment data

-   Language Server version: v2023.12.1
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5

## Code Snippet

```python
from typing import TypeVar, Generic, Type

T = TypeVar("T")

class A(Generic[T]):
    @classmethod
    def build(cls: Type[T]) -> T:
        return cls()  # Returns an instance of cls, which will be A or its subclasses

class B(A):
    pass

class C(B):
    pass

object_a = A.build()
object_b = B.build()
object_c = C.build()
```

## Repro Steps

I am experiencing an issue with Pylance in Visual Studio Code where the type hinting does not seem to work correctly for inherited generic classes. Specifically, when I define a class hierarchy as shown in the code snippet, the subclasses of A (i.e., B and C) do not seem to inherit the type hints as expected.

Just copy and paste this code to any python file, and you can see the `object_b` and `object_c` is annotated as `Any` 

![image](https://github.com/microsoft/pylance-release/assets/22385182/a88f64b7-7120-4649-b0ac-ee8110d4e209)

## Expected behavior

I expect the type hints to be correctly inferred for the subclasses of A, so that methods like build() return instances of the correct subclass.

## Actual behavior

The type hints are not being correctly inferred for subclasses B and C, resulting in potential misunderstandings or errors in type checking.

To the best of my knowledge for solving this problem is using multiple inheritance like:

```python
from typing import TypeVar, Generic, Type

T = TypeVar("T", bound="A")

class A(Generic[T]):
    @classmethod
    def build(cls: Type[T]) -> T:
        return cls()

class B(A["B"]):
    pass

class C(B, A["C"]):
    pass

object_a = A.build()
object_b = B.build()
object_c = C.build()
```

I still believe there should be a simpler method for handling this situation. Notably, when I omit type annotations, Visual Studio Code seems to work correctly. Therefore, I'm curious if there is a more straightforward approach to achieve the desired behavior with type annotations.

![image](https://github.com/microsoft/pylance-release/assets/22385182/3ab58d9c-b856-47b3-9d3c-060f2ad99124)

If this issue is not actually a bug and is instead a result of my misunderstanding, I apologize in advance for any confusion caused. I'm seeking guidance on whether there's a better way to handle type annotations in such scenarios, particularly in the context of using Pylance with Visual Studio Code.

**Comment by erictraut** [comment]
In your first example, you've defined `A` as a generic class. That means anywhere you use `A`, you should provide a type argument. If you don't, type checkers will assume that the type argument is `Any`. That means `class B(A): pass` is the equivalent of `class B(A[Any]): pass` which is probably not what you intended. If you enable the `reportMissingTypeArgument` diagnostic check in pylance, it will generate an error if you omit a type argument.

I'm not 100% sure I understand what you're trying to do with this class hierarchy, but my guess is that you intended the following:

```python
from typing import TypeVar

T = TypeVar("T", bound="A")

class A:
    @classmethod
    def build(cls: type[T]) -> T:
        return cls()
```

Note that `A` is not defined as a generic class. However, `build` is a generic method, and the type variable `T` is scoped to this method.

To clean this up further, you can leverage the `Self` type that was [introduced in Python 3.11](https://peps.python.org/pep-0673/).

```python
from typing import Self

class A:
    @classmethod
    def build(cls) -> Self:
        return cls()
```

**Comment by Janus-Shiau** [comment]
I agree with your point. While I am familiar with using Self, I also need a solution that is compatible with Python versions prior to 3.11. The first method I mentioned does work with versions before 3.11.

Thanks a lot!
