### ISSUE TITLE
Diagnostics broken for files created with `code new_file.py`

### ISSUE THREAD

**Issue by nguyendviet** [microsoft/pylance-release#527]
## Environment data

Pylance: v2020.10.2
-   OS and version: MacOS 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3

## Expected behaviour

Recognise docstrings either `"""` or `'''`

## Actual behaviour

Error:
```
String literal is unterminated
```

```python
"""
Some text
Input:

Output
[[A,B,1],
[B,C,4],
[C,E,1],
[D,E,5]]
"""

class Solution:
    def __init__(self):
        pass
    def get_result(self):
        pass
```
<img width="236" alt="Screenshot 2020-10-27 at 09 52 19" src="https://user-images.githubusercontent.com/30057363/97310880-22720680-183a-11eb-9a0d-57038508b08c.png">

<img width="352" alt="Screenshot 2020-10-27 at 09 44 17" src="https://user-images.githubusercontent.com/30057363/97310656-d58e3000-1839-11eb-8753-ba261b7ad537.png">
<img width="309" alt="Screenshot 2020-10-27 at 09 44 28" src="https://user-images.githubusercontent.com/30057363/97310657-d58e3000-1839-11eb-8fc8-80f7e05d4412.png">
<img width="329" alt="Screenshot 2020-10-27 at 09 45 16" src="https://user-images.githubusercontent.com/30057363/97310658-d58e3000-1839-11eb-85d2-3b5d51233b60.png">

If remove the array in the docstring:

<img width="231" alt="Screenshot 2020-10-27 at 09 55 47" src="https://user-images.githubusercontent.com/30057363/97311518-d2477400-183a-11eb-917e-bc7e4a7339d7.png">
<img width="333" alt="Screenshot 2020-10-27 at 09 55 56" src="https://user-images.githubusercontent.com/30057363/97311521-d2477400-183a-11eb-9e65-b2230179af54.png">

There's no indentation.

If I type out the class `Solution` manually, Pylance stops complaining but that means I cannot use my VSCode snippets for other snippets.

Python snippets:

```json
    "Default solution": {
        "prefix": "mysolution",
        "body": [
            "class Solution:",
            "    def __init__(self):",
            "        pass",
            "    def get_result(self):",
            "        pass",
            ],
        "description": "My solution default setup"
```

After pasting the output array back in the docstring, the error in the docstring goes away:

<img width="232" alt="Screenshot 2020-10-27 at 09 59 13" src="https://user-images.githubusercontent.com/30057363/97311937-4da92580-183b-11eb-8cdd-a566e1ce4bcc.png">

**Comment by erictraut** [comment]
I'm not able to repro the problem from the code snippets that you've posted above.

I suspect there is a bad character token in that snippet. Perhaps a non-breaking line feed or something similar. By copying and pasting the text, this bad token is getting stripped out.

Are you able to run the Python code successfully? Or does the Python interpreter also indicate that there's a problem with this code?

**Comment by nguyendviet** [comment]
Thank you @erictraut for your reply. I've tried switching back to `pylint` without changing anything and my code works normally so I suspect the problem is caused by `pylance` doesn't recognise the `docstring`.

I've also checked the snippet and couldn't find any bad token. VSCode does a good job at checking errors in snippets so I don't think the snippet is the issue. I include a screenshot of my snippet here.

<img width="407" alt="Screenshot 2020-10-27 at 11 32 51" src="https://user-images.githubusercontent.com/30057363/97324600-64a24480-1848-11eb-9430-dccf00c83beb.png">

**Comment by jakebailey** [comment]
Non-ASCII characters aren't an error; VS Code doesn't have a problem with using them. But the Python language (and therefore the parsers) may not accept certain characters.

I've seen this happen before when copying out of say, Word, or when there's an IME enabled and the wrong type of whitespace or quotations are being inserted.

Can you place exactly the code that has the problem somewhere, like a git repo?

**Comment by nguyendviet** [comment]
Thank you @jakebailey for your answer. I suspect that's the case. I copied the text to put in the docstring from this [link](https://leetcode.com/discuss/interview-question/900852/). It's text from LeetCode. The funny thing is it doesn't make `pylint` show that "warning", only `pylance`. I'm not sure it's a good or bad thing.

However, I typed in the snippet myself and `pylance` doesn't seem to accept the snippet printed out by VSCode as it shows "warning" and marks my `.py` red.

I've tried to start a new file without the text and `pylance` accepts the snippet. However, even after removing all the docstring in the old file, `pylance` still shows the warning for my snippet and marks he old file red.

I've also tried a different combinations of text. In the photo below, I just typed the text myself into the docstring so no copy-paste at all:

<img width="181" alt="Screenshot 2020-10-27 at 14 22 20" src="https://user-images.githubusercontent.com/30057363/97345017-f0739b00-185f-11eb-97f9-e1218f163311.png">
<img width="462" alt="Screenshot 2020-10-27 at 14 22 28" src="https://user-images.githubusercontent.com/30057363/97345020-f0739b00-185f-11eb-99a0-1e43e4ad199d.png">


`pylance`'s behaviours seem inconsistent.

**Comment by jakebailey** [comment]
A few things to try:

- If you save the file, then reload the editor so that it opens the file again, does it happen?
- If you roll back to 2020.10.1, does the bug reproduce? In the VS Code extension menu, there's an option to install old versions.

I'm wondering if there's something wrong with the new incremental text support.

**Comment by nguyendviet** [comment]
@jakebailey 

1. I saved the file, then reloaded the editor then the old file doesn't show the warning but when I created new `.py` files, the same thing happened again. `pylance` is even confused by my snippet name:

<img width="496" alt="Screenshot 2020-10-27 at 17 07 56" src="https://user-images.githubusercontent.com/30057363/97362789-e6f62d00-1877-11eb-8388-b99b6fe069cb.png">

`pylance` for some reasons, shows `myclass` (which isn't my snippet prefix) isn't defined. `myclass` is not written anywhere in my files.

2. I rolled back to 2020.10.1 and so far I haven't seen the warning. I've tried:
- Create new file, type in docstrings.
- Use docstrings from snippets.
- Use code from snippets
So far `2020.10.1` works for me.

**Comment by jakebailey** [comment]
OK, then the next thing to look at is the LSP trace to figure out what edits are happening.

Can you set `"python.trace.server": "verbose"` with 2020.10.2, reload, do the repro, then copy the contents of the language server output window to a gist or log file attachment?

Just to double check, does this only happen when you use a snippet to insert the text?

**Comment by erictraut** [comment]
@nguyendviet , what encoding is used for these files? If you look in the lower right part of the VS Code window, you should see the encoding ("UTF-8", etc.).

![Screen Shot 2020-10-27 at 2 23 14 PM](https://user-images.githubusercontent.com/7040122/97363583-097c4c00-1860-11eb-9da4-0b1fbbe7aafc.png)

@jakebailey, I wonder if this is related to the incremental (delta) text update support that you implemented in 2020.10.2?

**Comment by jakebailey** [comment]
Yes, that is my assumption (https://github.com/microsoft/pylance-release/issues/527#issuecomment-717529300).

**Comment by jakebailey** [comment]
I used the document given in the LSP client, but it appears some use the one used in VS Code itself instead (https://github.com/microsoft/vscode-textbuffer). Perhaps it's better in some way, at the very least consistency...

**Comment by nguyendviet** [comment]
@erictraut : It's "UTF-8".
@jakebailey & @erictraut Thank you for your prompt responses. Please let me know if I can provide more details.

**Comment by jakebailey** [comment]
See https://github.com/microsoft/pylance-release/issues/527#issuecomment-717548402, the LSP logs would be helpful.

**Comment by nguyendviet** [comment]
> See [#527 (comment)](https://github.com/microsoft/pylance-release/issues/527#issuecomment-717548402), the LSP logs would be helpful.

@jakebailey Sorry I missed that one. I'm actually setting it up. I'll let you know asap.

**Comment by nguyendviet** [comment]
@jakebailey 

> Can you set `"python.trace.server": "verbose"` with 2020.10.2, reload, do the repro, then copy the contents of the language server output window to a gist or log file attachment?

LSP logs:
```
$  cd /Users/viet/webdev/algorithms ; /usr/bin/env /usr/local/opt/python/bin/python3.7 /Users/viet/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/launcher 50160 -- /Users/viet/webdev/algorithms/test/test_pylance.py 
this is a test
```

Code:
```python
"""
This is a test
This is a test
This is a test
This is a test
This is a test
This is a test
This is a test
"""

class Solution:
    def __init__(self):
        pass
    def get_result(self):
        pass

print("this is a test")

```

> Just to double check, does this only happen when you use a snippet to insert the text?

No, it happens when I type the docstrings myself. In the photo, I typed the docstrings:

<img width="271" alt="Screenshot 2020-10-27 at 20 17 59" src="https://user-images.githubusercontent.com/30057363/97375702-df438200-1891-11eb-972d-ce8b9e740bb8.png">
<img width="483" alt="Screenshot 2020-10-27 at 20 18 53" src="https://user-images.githubusercontent.com/30057363/97375703-dfdc1880-1891-11eb-8d23-53fcf67b5f92.png">
<img width="362" alt="Screenshot 2020-10-27 at 20 19 05" src="https://user-images.githubusercontent.com/30057363/97375705-dfdc1880-1891-11eb-9a1c-ad1fbfe56b78.png">
<img width="901" alt="Screenshot 2020-10-27 at 20 19 17" src="https://user-images.githubusercontent.com/30057363/97375706-dfdc1880-1891-11eb-81db-443233399123.png">
<img width="526" alt="Screenshot 2020-10-27 at 20 20 04" src="https://user-images.githubusercontent.com/30057363/97375707-e074af00-1891-11eb-9449-eaf200c045d3.png">
<img width="607" alt="Screenshot 2020-10-27 at 20 20 14" src="https://user-images.githubusercontent.com/30057363/97375708-e074af00-1891-11eb-9ef8-4aa8915654ae.png">

**Comment by nguyendviet** [comment]
I did a few more tests:

- The warnings stop showing after reloading VSCode.
- The warnings show up in newly created files even when I type in docstrings with either `"""` or `'''` (photos).

<img width="587" alt="Screenshot 2020-10-27 at 20 31 10" src="https://user-images.githubusercontent.com/30057363/97376556-0b600280-1894-11eb-9fcb-760d8fb230b0.png">
<img width="758" alt="Screenshot 2020-10-27 at 20 31 25" src="https://user-images.githubusercontent.com/30057363/97376557-0bf89900-1894-11eb-9b3a-a6b7a1ab716f.png">
<img width="761" alt="Screenshot 2020-10-27 at 20 31 32" src="https://user-images.githubusercontent.com/30057363/97376697-6e519980-1894-11eb-9440-52da7c748d05.png">


- The warnings go away if I remove the docstrings and type the text back with or without snippets.

<img width="597" alt="Screenshot 2020-10-27 at 20 33 34" src="https://user-images.githubusercontent.com/30057363/97376578-19ae1e80-1894-11eb-9125-39f5ba9255ff.png">
<img width="764" alt="Screenshot 2020-10-27 at 20 33 40" src="https://user-images.githubusercontent.com/30057363/97376579-19ae1e80-1894-11eb-9977-c2090ceb7c1b.png">

**Comment by jakebailey** [comment]
Those aren't the LSP logs, that appears to be the output of the "Python" output window. You want the output of the "Python Language Server" window with trace mode enabled. It should be a huge amount of text (so don't paste it into the issue; use gist or a file attachment).

**Comment by nguyendviet** [comment]
@jakebailey Sorry about that. I did LSP logs a while ago but with `js`.  Can you help me with this?

I've been searching online for how to enable trace mode for python and to add `python.trace.server` but haven't been able to find the answer anywhere.

Here's my `launch.json` and I get `Property trace is not allowed.`:
```json
{
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "protocol": "inspector",
            "trace": true,
},
```
<img width="348" alt="Screenshot 2020-10-27 at 21 51 39" src="https://user-images.githubusercontent.com/30057363/97381378-59c6ce80-189f-11eb-979d-fe8ceff40390.png">

I've added `"python.trace.server": "verbose",` to my `settings.json` but it seems like it's deprecated.

<img width="250" alt="Screenshot 2020-10-27 at 21 51 20" src="https://user-images.githubusercontent.com/30057363/97381435-76630680-189f-11eb-96be-e7f2fc4efefe.png">

**Comment by jakebailey** [comment]
You want it in the settings, not the laucnh config. Ignore the warning. Check the "Python Language Server" output and there should be quite a lot of JSON being printed. Then you can reload to get a full trace.

**Comment by nguyendviet** [comment]
@jakebailey Got it. Thank you. Here's [the gist](<script src="https://gist.github.com/nguyendviet/d9e0c3f529905bf1303ef47f1e5da492.js"></script>) of the log after running a `.py` file with the warnings.

**Comment by jakebailey** [comment]
Very strange. This is the sequence of edits:

1. `""` (0, 0) - (0, 0)
2. `"` (0, 1) - (0, 2), replacing the last quote, probably an artifact of typing over VSC's auto-quote pairs
3. `"` (0, 2) - (0, 2)
4. `\n` (0, 3) - (0, 3)
5. `T`
6. `h` ... (and so on)

This all should work, we'll have to try and replicate this; the incremental text lib should have handled this.

**Comment by jakebailey** [comment]
Also, the file is opened as `untitled:/Users/viet/webdev/algorithms/test/test_pylance.py` first, then later is reopened as `file:///Users/viet/webdev/algorithms/test/test_pylance.py`. This untitled file behavior must be new; an untitled file shouldn't have a name...

**Comment by nguyendviet** [comment]
@jakebailey Here's what I did:
- Open VSCode, create a new file, type in docstring and type some random text, save it.
- After I'm done with the file `test_pylance.py`, `test_pylance_2.py`, etc. I remove them.
- Then I create new files with **the same name** again because the issue seems to appear only in newly created files. Maybe that's why there's an `untitled` file reopened as `test_pylance.py`.

I hope this helps.

**Comment by nguyendviet** [comment]
@jakebailey : I haven't seen any updated so I tried the following and it seems like it solved the problem (somehow):
- Updated to latest Pylance: problem persisted.
- Uninstalled everything on VSCode by Microsoft: Pylance, Python, IntelliCode, C++, Java, etc...
- Reinstalled

**Comment by jakebailey** [comment]
No update, sorry. I haven't had time to figure out what's going on here.

**Comment by nguyendviet** [comment]
> No update, sorry. I haven't had time to figure out what's going on here.

No worries. It looks like no one else has this bug. Since VSCode keeps asking me to install Pylance and update to the latest one for IntelliCode and I also use Python library by MS, I found a workaround: whenever I create a new `.py` file and have this bug, I just reload the whole window and it stops showing the red underlines.

**Comment by nguyendviet** [comment]
Hi @judej . Thanks for asking. This issue has been fixed.
