### ISSUE TITLE
Jupyter notebook has no syntax highlighting

### ISSUE THREAD

**Issue by ndbp97** [microsoft/pylance-release#5273]
Type: <b>Bug</b>

![image](https://github.com/microsoft/pylance-release/assets/151021178/e5ea7cbc-790c-4d26-b2a6-d440e630dd0c)

Extension version: 2023.12.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (8 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.91GB free)|
|Process Argv|--crash-reporter-id 1ba90d8f-1770-41e5-a4b9-2d517c8f2500|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
vscrp:30673768
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184c:30925681

```

</details>

**Comment by debonte** [comment]
I'm unable to reproduce this. If you switch back to `2023.11.10` does the issue go away?

Even with Pylance disabled (`"python.languageServer": "None"`) you should get syntax highlighting. Here's what I see in that case:

![image](https://github.com/microsoft/pylance-release/assets/12820898/11df8602-6aa2-417d-9f27-e0b31c212169)

But you're getting no coloring at all? Are you using a custom theme?

**Comment by ndbp97** [comment]
Yes, for some reason it only happens on one computer. But even reinstalling vscode doesn’t seem to help. Downgrading does not help either. Is there any way to debug this?

From: Erik De Bonte ***@***.***>
Date: Monday, 18 December 2023 at 23:19
To: microsoft/pylance-release ***@***.***>
Cc: Dickreuter, Nicolas ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/pylance-release] Jupyter notebook has no syntax highlithging (Issue #5273)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I'm unable to reproduce this. If you switch back to 2023.11.10 does the issue go away?

Even with Pylance disabled ("python.languageServer": "None") you should get syntax highlighting. Here's what I see in that case:

image.png (view on web)<https://github.com/microsoft/pylance-release/assets/12820898/11df8602-6aa2-417d-9f27-e0b31c212169>

But you're getting no coloring at all? Are you using a custom theme?

**Comment by debonte** [comment]
Does this repro if you create a new notebook in a new workspace? Do you see the same problem in `.py` files? Can you share your `settings.json`?
