### ISSUE TITLE
A question about type narrowing

### ISSUE THREAD

**Issue by uf-fipper** [microsoft/pylance-release#5274]
pylance version: `2023.12.1`

Look at the following code:

```python
from typing import TypeAlias, TypeVar

IntOrStr: TypeAlias = int | str
IntOrStrT = TypeVar("IntOrStrT", bound=IntOrStr)

def func(a: IntOrStrT) -> IntOrStrT:
    if isinstance(a, int):
        ...
        a.as_integer_ratio  # Cannot access member "as_integer_ratio" for type "str*"
    else:
        ...
    return a
```

![image](https://github.com/microsoft/pylance-release/assets/55644019/c0fb92e2-d5df-446a-a2b0-372ea11be7ff)

There is an error at line `a.as_integer_ratio`: `Cannot access member "as_integer_ratio" for type "str*"`. Is this normal? There is no error in version `2023.11.10`.

**Comment by heejaechang** [comment]
fixed in 2023.12.100 preview.
