### ISSUE TITLE
Extract method not working when invoking it on a member inside a class 

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#5277]
<h3> Environment data </h3>

-   Language Server version: 2023.12.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class foo:
    x = 1
```

<h3> Repro Steps </h3>

1. Create a Python file with the content above
1. Select `x = 1`
1. Trigger "Extract method"

It results in the following:
![image](https://github.com/microsoft/pylance-release/assets/45497113/24b43886-69fd-4f3a-b5bc-47f6b72b6101)

<h3> Expected behavior </h3>

Maybe a failure that this can't be done at the class level?

<h3> Logs </h3>

```
XXX
```

**Comment by luabud** [comment]
cc @heejaechang

**Comment by luabud** [comment]
There's also another example that maybe the result should be a failure message:

```
x = 1
```

If you select ` x = 1` and do "extract variable", we do the following:

```
new_var = x = 1
new_var
```

**Comment by heejaechang** [comment]
for this case - https://github.com/microsoft/pylance-release/issues/5277#issuecomment-1861531993
> x = 1

I think problem is `extract variable` is considering `x = 1` as `expression` and not `statement`. `extract variable` should only be offered for `expression`.

**Comment by luabud** [comment]
should we create a new issue for that case since https://github.com/microsoft/pyrx/pull/4476 will fix the first one in the opening comment?

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.12.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202312103-10-January-2024-PreRelease)
