### ISSUE TITLE
Refactor adds empty or duplicate lines to the entire file

### ISSUE THREAD

**Issue by dennisknothetelus** [microsoft/pylance-release#5285]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Imagine this simple my.py file
```
# Assign a value to myvar and print it
myvar = "some string"
print(myvar)
# End of file
```

When I press "F2" to refactor the name of myvar to myvar2 and press enter, I end up with this
```
# Assign a value to myvar and print it

myvar2 = "some string"

print(myvar2)
# End of file
# End of file
```

The original file had 4 lines. However, after the refactor, the file has 7 lines. Lines 2, 4 and 6 were added by the refactor action unexpectedly and in error.

## Steps to reproduce:

1. Write some Python code with variables, e.g. myvar (see above)
2. Place cursor onto a variable name Press "F2" to refactor 
3. Rename the variable (e.g. add a "2"), e.g. myvar2
4. Press Enter

I tried this in two configurations: One, where I had all my usual exensions running. And a second time, where I only had the Python extension running. Both time with the same result.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>
N/A
</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Jedi"

```

</p>
</details>

Extension version: 2023.22.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.58GB free)|
|Process Argv|--crash-reporter-id 1f5bb1fc-b359-404d-9513-066954dcda54|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrpc:30673769
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. You're using the 'jedi' language server and not Pylance. Issues with jedi would be logged here:
https://github.com/pappasam/jedi-language-server.

This works as expected with Pylance:
![rename](https://github.com/microsoft/pylance-release/assets/19672699/56d332da-b5b1-4304-94d1-f38d86901b7e)
