### ISSUE TITLE
Auto import completions are display even though they're disabled

### ISSUE THREAD

**Issue by cidersec** [microsoft/pylance-release#5290]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: do not offer auto-import completions when the option is not enabled
Actual: auto-import completions are the top recommended options

## Steps to reproduce:

1. Un-check "Offer auto-import completions"

![image](https://github.com/microsoft/pylance-release/assets/108358451/5deed31b-48ea-4e87-82f8-8ef58aaa19fa)

2. Type `sp` in a python file

![image](https://github.com/microsoft/pylance-release/assets/108358451/27439a6b-48aa-40fb-9c50-96cbc720c851)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.18
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

testing
• pytestEnabled: true

```

</p>
</details>

Extension version: 2023.12.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.85GB free)|
|Process Argv|--crash-reporter-id d307ec99-355a-400e-ba4d-0cec23c6aabc|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
962ge761:30917236
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184c:30925681

```

</details>

**Comment by heejaechang** [comment]
we shouldn't offer when it is off. I just tried it and it works as expected. there are multiple level of settings (folder, workspace, user, machine and etc). make sure the option is off fully, not off in one place but on in another place.

**Comment by cidersec** [comment]
Thank you for checking it.

* I checked all 3 settings, and it is off (user, workspace, folder)
* I uninstalled and reinstalled
* I tried installing the prerelease version

But those completions still come up. A couple questions
* I have several extensions installed, does screenshot above look like the auto import options created by pylance? are we sure that it's not another common extension (like the MS Python extension)
* is it possible that the settings file could get corrupted? is there a way I can check or reset this?
* anything else I can check to debug this, or logs I can look at?

**Comment by luabud** [comment]
@cidersec Can you try disabling the Pylance extension and reloading the window? Then we can know if this is coming from Pylance or not. 
It'd also be helpful if you could share any other settings you may have starting with `python.analysis`.  

Our logs can be found in the Python Language Server output channel. This is what shows up when auto imports are enabled and you accept the suggestion:
 
![image](https://github.com/microsoft/pylance-release/assets/45497113/dc8450c4-3eb8-458c-b09c-5da81c4cbe84)

**Comment by cidersec** [comment]
I disabled it and verified that it was coming from Pylance, but that prompted me to uninstall and reinstall for good measure and it stopped displaying those options. I should have thought to try that before, but thanks so much for the suggestion, you made my week :)
