### ISSUE TITLE
Pylance does not recognise built-in module function

### ISSUE THREAD

**Issue by viscount-monty** [microsoft/pylance-release#5293]
## Environment data
- Windows 10
- VScode 1.85.1
- Python 3.12.1
- Pylance v2023.12.1

## Code Snippet

This is the code snippet in which I discovered the issue, but can be created with a two-line file containing the import and the function call.
```python
# <other imports>
import platform
# <other imports and code>
about_dict = {
    "os.name": os.name,
    "os.path": os.path,
    "os.getcwd()": os.getcwd(),
    "os.getcwdb()": os.getcwdb(),
    'os.getenv("HOME")': os.getenv("HOME"),
    "os.getlogin()": os.getlogin(),
    "os.getpid()": os.getpid(),
    "platform.platform()": platform.platform(),
    "platform.system()": platform.system()
}
```
![image](https://github.com/microsoft/pylance-release/assets/52033240/ec347d71-b73e-45c5-9b7d-458d3e283598)

## Repro Steps

1. Open new python file with following contents:
![image](https://github.com/microsoft/pylance-release/assets/52033240/5af72ec8-fbe2-4fd2-83aa-e7d2260c8e2f)

## Expected behavior
No red line/file title etc from pylance

## Actual behavior
Red line and file title from Pylance as if `plaftorm.system()` is not a valid function, despite if functioning perfectly, outputting `Windows`.

## Logs

Got the following error when trying to add `"python.analysis.logLevel": "Trace"` to `settings.json`. 
```
This setting cannot be applied in this workspace. It will be applied when you open the containing workspace folder directly.
```
I don't understand what it means - what is the "containing workspace folder" and how does one open it "directly"?

**Comment by debonte** [comment]
I'm not seeing any errors with that code on my machine.

What is the diagnostic/error associated with that red squiggly underline? You can check by mousing over `system` or checking the Problems pane (Ctrl+Shift+M).

**Comment by viscount-monty** [comment]
Error is as follows:
![image](https://github.com/microsoft/pylance-release/assets/52033240/6577c51a-3d63-467a-acd7-929068384e75)

**Comment by erictraut** [comment]
If you right-click on `platform` and select "Go To Declaration", where does it take you? It should open a file called `platform.pyi`. This is a type stub that ships with Pylance and defines the types for the stdlib `platform` module. If you scroll down, you should see `def system() -> str: ...`.

I'm guessing that you have some other module named `platform` in your project or in your Python environment that's overriding the stdlib version. If so, "Go To Declaration" will take you to a different file than the one I mentioned above. If my theory is correct, you'll need to find and remove (uninstall) this other `platform` module or package.

**Comment by viscount-monty** [comment]
Looks like you're right, thanks! Seems like the Micropython module is causing the problem. 
![image](https://github.com/microsoft/pylance-release/assets/52033240/e1c8e5fa-c653-4696-b64b-5c70ba0d2c5b)
![image](https://github.com/microsoft/pylance-release/assets/52033240/176eb15e-afe5-476b-9533-9b05583b7174)

Is there any way to switch between CPython and Micropython considering I use both in the repository I'm working on?
