### ISSUE TITLE
Painfully slow autocomplete suggestions if you type fast

### ISSUE THREAD

**Issue by amalrajan** [microsoft/pylance-release#5297]
## Environment data

-   Language Server version: 2023.12.1
-   OS and version: Ubuntu 22.04 via WSL2 on Windows 11 23H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12 (Miniconda)

## Repro Steps

When I type fast (>100wpm), I can notice a slight delay between pressing the key on the keyboard and the characters appearing and the autocomplete suggestion popup appearing. Barely noticeable if you do 60wpm or so.

This issue disappears when I disable Pylance extension.

Also, this never was an issue a few months ago (before September 2023). I'm gonna switch to Pycharm temporarily as this issue is really annoying, even though overall, I really prefer the autcomplete on this plugin

**Comment by bschnurr** [comment]
Thank you for logging an issue. Do you have a public code repository or code sample to test with?

**Comment by heejaechang** [comment]
thank you for the reporting! but we will need some sample code otherwise, it will be hard for us to figure out what code path is causing an issue.

**Comment by amalrajan** [comment]
I couldn't see any difference when I watched a 10x slomo screen capture of pycharm and vscode (I simulated typing the same block of code on both editors at 120wpm). However, I can still feel a tiny bit of input lag on vscode between pressing a key on the keyboard and the characters appearing. It feels instantaneous on pycharm. 

Second, disabling pylance seems to improve the perceived latency.

I'm wondering if this is somehow related to 'Zero-latency typing' https://github.com/microsoft/vscode/issues/27378 ?

**Comment by rchiodo** [comment]
Without a repro it's impossible for us to pinpoint what might be taking longer. @Heejaechang has a fix in the works for an overload problem: https://github.com/microsoft/pylance-release/issues/5268? 

I'm going to close this without any specific repro though.
