### ISSUE TITLE
INtellisense not working

### ISSUE THREAD

**Issue by aditya-qure** [microsoft/pylance-release#5300]
Type: <b>Bug</b>

1. Install python extension 
2. Intellisense not working

Extension version: 2023.12.1
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T22:27:05.695Z)
OS version: Linux x64 6.2.0-39-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 4099)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|46.74GB (34.50GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pythonregdiag2cf:30926736
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by bschnurr** [comment]
Thanks for logging an issue and providing the video.. Invesitgating

**Comment by bschnurr** [comment]
I think this might be related to updated stubs, and now the _new_ function has overloads which breaks our search logic
```python
from django.db import models


class Contact(models.Model):
    first_name = models.CharField()
```

**Comment by aditya-qure** [comment]
It's with every module. 
![Screenshot from 2023-12-22 14-00-29](https://github.com/microsoft/pylance-release/assets/111493497/9786b43e-7442-44ee-bba9-2e5b05546219)

**Comment by Redowan-Ahmed** [comment]
Facing the same issue, Only showing args and kwargs in the parameter instead of the actual parameters. If I disable the pylance then it's working and also working with other Functions and classes, Just not working with Django models Fields. 

Few model fields are working

Such as Filefield and Image Field

**Comment by bschnurr** [comment]
I believe the change is in pyright, `CharField` should be fixed in our next pre-release

**Comment by bschnurr** [comment]
@aditya-qure  please supply some Pylance logs.. and a code example.
see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by aditya-qure** [comment]
Getting no `Python Language Server` in the dropdown menu 
![Screenshot from 2023-12-27 13-20-05](https://github.com/microsoft/pylance-release/assets/111493497/adc8a138-e1cf-43b9-8071-f75a65b2dca5)

**Comment by aditya-qure** [comment]
The issue seems to be indexing of large files.

**Comment by aditya-qure** [comment]
The issue seems to be indexing of large files.
`Enumeration of workspace source files is taking longer than 10 seconds.`

I created a `pyrightconfig.json` file and excluded large files. Go to definition is working fine now.

**Comment by bschnurr** [comment]
Glad to hear. closing then for now.

**Comment by rchiodo** [comment]
> This is still not fixed.

@hogsmead we recommend you open a new issue. This issue is rather vague and doesn't provide any information on what the problem might be.
