### ISSUE TITLE
How do I extend third party type annotations?

### ISSUE THREAD

**Issue by rachtsingh** [microsoft/pylance-release#5303]
I've looked at related issues and I don't think I found anything specific to this issue, but my apologies if it's a duplicate.

We extend Pandas dataframes using the [DataFrame accessor API](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.register_dataframe_accessor.html#pandas.api.extensions.register_dataframe_accessor). This monkey patches in a new method/object into the definition of `pd.DataFrame`, which is obviously externally defined. In our codebase we use this extensively, and each call is an error to Pyright, I think.

Relatedly, sometimes the type definitions for methods in pandas are incorrect (e.g. `pd.concat` supports taking `None` as a member of the input, but the type signature doesn't allow this), and we'd like to patch it with the correct definition while we're figuring out how/whether to upstream changes.

The closest solution I've found is this post: https://stackoverflow.com/questions/66501738/pandas-dataframe-accessor-type-hints but it's very unsatisfactory since we want to keep using the `pd.DataFrame` annotation for both clarity and ease-of-use.

Is there a way to import and extend third-party type annotations? I'm assuming I'm just missing the blessed path for this, but would it be possible to e.g. create a new `stubPath/pandas/core/frame.pyi` with contents like this?

```
class DataFrame:
    # import somehow from the default annotation
    dataset: Extension
```

**Comment by Viicos** [comment]
Pylance uses Pyright under the hood, and you can configure a path to custom type stubs (see [docs](https://microsoft.github.io/pyright/#/configuration?id=main-configuration-options), `stubPath` option -- by default, Pyright will look for the `typings` folder). However, I don't know if there is a way to only patch specific stub files. If it is not the case, you will have to make a full copy of the pandas stubs and add your custom edits there (not ideal, as you'll have to manually update your local stubs for every new release).

**Comment by judej** [comment]
@vilcos's suggestion is probably the best option here.  I would also recommend, when extending pandas stubs, to clone the pandas stubs repository rather than using the stubs shipped with Pylance. This ensures a better match with the version of pandas you are using.
