### ISSUE TITLE
Pylance does not recognize 'import cpuinfo' 

### ISSUE THREAD

**Issue by ullix** [microsoft/pylance-release#5306]
It reports:

"Import "cpuinfo" could not be resolved Pylance(reportMissingImports(https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)"

![image](https://github.com/microsoft/pylance-release/assets/9335726/76436ba6-09ea-45d2-a9f6-3ee466894bce)

though Python does import it and software using it runs correctly. https://pypi.org/project/py-cpuinfo/

**My system:**
Linux Mint 21
Python 3.10.12

Visual Studio Code:
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-91-generic

![image](https://github.com/microsoft/pylance-release/assets/9335726/cb7cc0cf-ef42-48b9-9d9a-1037cc70660d)

**Comment by bschnurr** [comment]
are you sure you have the correct environment selected?  https://code.visualstudio.com/docs/python/environments#_working-with-python-interpreters

**Comment by bschnurr** [comment]
or is this an issue... where it shows the missing error, then you pip install the library and it doesn't refresh?

**Comment by ullix** [comment]
Well, I am using multiple Virtual Environments and now tried to reproduce my error, but failed. It is ok now.
I will remember your questions when it happens again. Thanks.
