### ISSUE TITLE
Module cannot be used as a type.

### ISSUE THREAD

**Issue by 0x1618** [microsoft/pylance-release#5313]
<h3> Environment data </h3>

-   Language Server version: 2023.12.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda):  3.11
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

```python
from PIL import Image
from typing import IO, Union

class Images(Files):
    def __init__(self, image: Union[IO, Image]) -> None:
        self.image = image
```
![image](https://github.com/microsoft/pylance-release/assets/80158535/a1eafc5c-2676-4f23-9649-4b8fc92d6c20)

The "Image" is highlighted. I think that shouldn't happen.

**Comment by Viicos** [comment]
I think what you meant is `from PIL.Image import Image` (`Image` is a class defined in the `Image` module, might be confusing)

**Comment by bschnurr** [comment]
Closing I agree I think you just need to update your imports
