### ISSUE TITLE
Those paths wrote in .pth files should be including to search paths

### ISSUE THREAD

**Issue by sanzenwin** [microsoft/pylance-release#5317]

**Comment by rchiodo** [comment]
Thanks for the issue but this should already be supported. You can see where we read the files here:
https://github.com/microsoft/pyright/blob/bd137351ca462d2b4a2d6544c6534d0ac3841d78/packages/pyright-internal/src/analyzer/pythonPathUtils.ts#L195

There are some caveats though. See the documentation here:
https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs

Namely the `.pth` files have to contain just file paths and not import statements.

**Comment by rchiodo** [comment]
Do you have an example where file paths in pth files are not being used?

**Comment by sanzenwin** [comment]
I'm using PDM, and I can go to the function definition by pressing F12 , but I can't search the function body by pressing Ctrl+Shift+F. Does this have been supported ? or i missed something?

**Comment by rchiodo** [comment]
CTRL+SHIFT+F uses your VS code workspace folders (Pylance isn't actually involved here). If you want some folder to be searched you have to add to the list of open folders:
https://code.visualstudio.com/docs/editor/multi-root-workspaces#_adding-folders

**Comment by rchiodo** [comment]
This could be considered a feature request. Support searching for symbols in 3rd party libraries? There isn't really a way to do that now.

**Comment by debonte** [comment]
I believe https://github.com/microsoft/pylance-release/discussions/3187 is tracking that.
