### ISSUE TITLE
Does Pylance support Django `something.subobject_set` notation?

### ISSUE THREAD

**Issue by aidiss** [microsoft/pylance-release#532]
I get this warning.

```
subobject_set: Unknown
Cannot access member "subobject_set" for type "something"
  Member "subobject_set" is unknownPylance (reportGeneralTypeIssues)
```
Should pylance recognize that this is a django pattern?

**Comment by jakebailey** [comment]
Can you provide any more info like a full example? Pylance doesn't recognize any django patterns specifically, only patterns defined by the Python spec and what can be described by the stubs in the [django-stubs](https://github.com/TypedDjango/django-stubs) repo.

**Comment by martinlehoux** [comment]
I think he's talking about things like https://github.com/PyCQA/pylint-django try to do.
But yes surely this would take place in django-stubs repo.

For instance :
```python
class A(models.Model):
    b = models.ForeignKey("app.B")

class B(models.Model):
    pass

b = B.objects.get(...)
# this is valid in django but as it was created dynamically, Pylance can't recognize it
b.a_set.all()
```

**Comment by martinlehoux** [comment]
This issue seems to explain that it already works https://github.com/typeddjango/django-stubs/issues/82

But I still get the issue in VSCode

**Comment by jakebailey** [comment]
This seems like something they're achieving not via the python typing spec, but via their mypy plugin (which necessarily doesn't work with us because we aren't mypy). The whole "how should plugins work across type checkers" thing hasn't really been resolved, and we know that there may be holes when using the stubs but it's much better to use them and them be not entirely perfect than to do nothing and attempt to analyze the complicated code in Django proper.

**Comment by jakebailey** [comment]
In this case, there's no way for us to understand the behavior of that ForeignKey constructor, that we should be trying to find `app.B` and then do something with it; we'd need a version of this where the type `B` is explicitly referenced (and not by some string path in a regular function). But, that may not be how Django works.

Maybe there's a way to instead write something like:

```python
# Forward ref to B class below
b: ForeignKey["B"] = models.ForeignKey("app.B")
```

Or similar based on their types to avoid needing the plugin. I haven't read their implementation to know the right way (or if it's possible) to use a generic type for this.

**Comment by savannahostrowski** [comment]
This issue has been opened for 30+ days with the waiting for info label. I'm going to close this issue but if the solution provided above doesn't work for you, please respond here and we can reopen.

**Comment by judej** [comment]
Closing this in this repo since the work is not here in Pylance.
