### ISSUE TITLE
Python code suggests list information, horizontal separator foreground color can not be custom modified

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/pylance-release#5321]
Python code suggests list information, horizontal separator foreground color can not be custom modified
![2024-01-03_python_code](https://github.com/microsoft/vscode/assets/54253524/b0aaf99e-10e9-4854-945e-db04710388fd)

Hopefully the next release will fix it! Thank you very much!👍

Windows 10
VSCode 1.84.2
Python v2023.22.1

Extension version: 2023.22.1
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by heejaechang** [comment]
it is not something we can customize. even if we enable `html` in `markdown` ignoring some security issue (or by adding some mitigation), `<style>` is not `html tag` `vscode` or `lsp` support for us to `override`

I will cose it but if you want, you can open one in `vscode core`
