### ISSUE TITLE
Auto Generate pandas docify config for docstring injection

### ISSUE THREAD

**Issue by bschnurr** [microsoft/pylance-release#5334]
improves pandas docstrings
https://github.com/microsoft/pyrx/issues/4469

some functions use a `@doc` decorator... we have a manual updated docify config file with a list of these functions.

Improvement is to add a script to scrape pandas for function names with the decorator instead.

**Comment by bschnurr** [comment]
https://github.com/microsoft/pyrx/commit/2f01ced43a4d3b5b209f78e803a05aeca7eba434

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2023.12.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202312103-10-January-2024-PreRelease)
