### ISSUE TITLE
"No symbols found" in outline window on startup

### ISSUE THREAD

**Issue by simonborje** [microsoft/pylance-release#534]
Steps to reproduce:
- Use pylance
- Open a Python file in an editor
- Restart VSCode
- Switch to the restored python file editor if it is not already active
- Look at "outline" section of the EXPLORER sidebar

Result:
The outline view reports "No symbols found in document <filename>"

Expected result:
The outline view should include names of functions/variables/...

Closing and reopening the file or running "Python: Restart Language Server" restores the outline functionality.

**Comment by jakebailey** [comment]
When this occurs, do other features work, such as diagnostics or completions? If you edit the document, does the outline refresh?

**Comment by huguesv** [comment]
I've been able to reproduce it.

Looking at the LSP messages when this occurs, VS Code is not sending the `textDocument/documentSymbol` request. Editing the file triggers the request and the outline appears.

**Comment by huguesv** [comment]
[no-outline-msgs.txt](https://github.com/microsoft/pylance-release/files/5454642/no-outline-msgs.txt)

**Comment by MicaelJarniac** [comment]
I'm also experiencing this issue. When I open the editor and select a Python file, it says "No symbols found in document '{name}'", but after editing the file, the outline loads correctly.

<details>
<summary>Info</summary>

- Windows 10
  - Version 1909 (OS Build 18363.1440)
  - WSL 2
- Ubuntu 20.04.2 LTS
- Visual Studio Code
  - Version: 1.54.3 (user setup)
  - Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
  - Date: 2021-03-15T10:55:45.459Z
  - Electron: 11.3.0
  - Chrome: 87.0.4280.141
  - Node.js: 12.18.3
  - V8: 8.7.220.31-electron.0
  - OS: Windows_NT x64 10.0.18363
- Pylance
  - Id: ms-python.vscode-pylance
  - Version: 2021.3.2
</details>

**Comment by jakebailey** [comment]
It's likely this is related to https://github.com/microsoft/vscode-python/issues/15727 and will be fixed there.

**Comment by jakebailey** [comment]
The original issue predates the bug I introduced in the core extension, so it's very likely the original issue isn't fixed (but things that look like it are).

**Comment by MicaelJarniac** [comment]
Seems to have been fixed by https://github.com/microsoft/vscode-python/issues/15727. I've tested it here and it's now working correctly.

**Comment by jakebailey** [comment]
Thanks. I'm going to close this as I _think_ it's fixed, but I'd appreciate it if @simonborje could recheck (so we can reopen as appropriate).
