### ISSUE TITLE
an unexpected error on overload and Literal[True, False]

### ISSUE THREAD

**Issue by uf-fipper** [microsoft/pylance-release#5341]
## Environment data

-   Language Server version: 2023.12.1
-   OS and version: windows11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4

## Code Snippet

in this case, `pylance` think `a` is `int | str`:

```python
from typing import Literal, overload

def get() -> Literal[1, 0]:
    return 1

@overload
def func(a: Literal[1]) -> int:
    ...

@overload
def func(a: Literal[0]) -> str:
    ...

def func(a: Literal[1, 0]) -> int | str:
    ...

x: Literal[1, 0] = get()

a = func(x)
```

![image](https://github.com/microsoft/pylance-release/assets/55644019/642da72a-ce78-4e21-b24f-13058e5da983)

but in this case, `pylance` report an error:

```python
from typing import Literal, overload

def get() -> Literal[True, False]:
    return True

@overload
def func(a: Literal[True]) -> int:
    ...

@overload
def func(a: Literal[False]) -> str:
    ...

def func(a: Literal[True, False]) -> int | str:
    ...

x: Literal[True, False] = get()

a = func(x)
```
![image](https://github.com/microsoft/pylance-release/assets/55644019/633fadb1-a7b1-4e1c-9b1c-1cdb2ac6b227)
![image](https://github.com/microsoft/pylance-release/assets/55644019/a44c77ac-45ec-44b5-b15d-e9003ab3dfdb)

`pylance` has different behaviors towards these two types of code.

**Comment by erictraut** [comment]
This is intended behavior in pyright, the type checker upon which pylance is built.

The type `Literal[True, False]` is exactly the same as `bool`, and for a variety of reasons, pyright simplifies `Literal[False, True]` to `bool`. When calling an overload, pyright will expand unions, if necessary, to match multiple overloads, but it does not expand `bool`.

**Comment by uf-fipper** [comment]
Should I write another overload like this?

```python
from typing import Literal, overload

def get() -> bool:
    return True

@overload
def func(a: Literal[True]) -> int:
    ...

@overload
def func(a: Literal[False]) -> str:
    ...

@overload  # add this overload
def func(a: bool) -> int | str:
    ...

def func(a: bool) -> int | str:
    ...

x: bool = get()

a = func(x)
```

**Comment by erictraut** [comment]
> Should I write another overload like this?

Yes, that's the solution I'd recommend.

**Comment by uf-fipper** [comment]
ok, thanks for your reply.
