### ISSUE TITLE
Extract variable shouldn't be offered when selection contains statement.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5343]
```python
a: str = "hello"
```

select `a: str = "hello"`

expected: no `extract  variable` offered
actual: it is offered, and end result is wrong.

when there is type annotation on assignment, it is a statement that can't be extracted to right value of new assignment statement.

code action shouldn't be offered.

**Comment by StellaHuang95** [comment]
This is a dupe of #5339? We should disable extract variables on assignments.

**Comment by heejaechang** [comment]
this is dupe of https://github.com/microsoft/pylance-release/issues/5400

for now, I specifically allow `assignment`, but if we want, we could only allow nested `assignment`  (ex, a = `b = 1`) but not full (`a = b = 1`)
