### ISSUE TITLE
Spaces are inserted for indents when tab is selected as default

### ISSUE THREAD

**Issue by Maxxxel** [microsoft/pylance-release#5346]
Config as follows

**user and workspace settings via Extension Settings:**
--indent-string='\t'

**settings.json**
"pylint.args": [
    "--indent-string='\\t'"
],

**.pylintrc**
[FORMAT]
indent-string=\t

VSCode is set to use Tabs as Intendation, but when i jumpt to a new line it just adds one space.
See the following GIF: https://gyazo.com/be209ffbe97adcd02cba8367a56cf88c

The weird thing is, when i write a new function it adds 4 spaces for the intendation....

**Comment by debonte** [comment]
Can you provide your configuration from `settings.json`, both user and workspace (if it exists)? If you're not sure how to find those files, you can use the following commands in the command palette (Ctrl+Shift+P):

![image](https://github.com/microsoft/pylance-release/assets/12820898/24b8dee6-dbce-4108-84c7-02358fd109fb)

Can you also provide the contents of your "Python Language Server" log from the Output pane (Ctrl+Shift+U).

**Comment by Maxxxel** [comment]
User Settings: 
![60ff0b6b6c59e6d747fb8ee42064518b](https://github.com/microsoft/pylance-release/assets/10586721/513649ae-3023-484b-bec1-3d0c5f6bab36)

Workspace Settings:
![af22d479ee0948553cebcd3ef58e63b7](https://github.com/microsoft/pylance-release/assets/10586721/d4f520c8-61a4-4997-95b9-cfcf862be51d)

Output after i hit Enter and it made no Tab intendation:
`2024-01-11 11:28:06.520 [info] c:\...\python.exe -m pylint --reports=n --output-format=json --max-line-length=425 --disable=C0114 --disable=C0115 --disable=C0116 --indent-string='	' --clear-cache-post-run=y --from-stdin c:\...\main.py
2024-01-11 11:28:06.520 [info] CWD Linter: c:\FF15Prediction`

Here you can see that its actually a Tab:
![f5d43936b38712ddbab0914dc8022b54](https://github.com/microsoft/pylance-release/assets/10586721/e2098fd7-89df-4cb7-8f64-d51faf3f44d6)

I have the feeling that it has problems with code that was reformatted to use Tabs and before was using spaces. Cause when i go into files from an external Lib which is already using tabs it perfectly works.

**Comment by Maxxxel** [comment]
i can reproduce the behaviour.

1. Open a file that has space intendation
2. press enter -> it makes correct intendation using spaces
3. click convert intendation to tabs
4. press enter -> it makes a wrong single space intendation

**Comment by debonte** [comment]
I'm still unable to reproduce this.

Maybe one of your other extensions is interfering? Based on your settings it looks like you have an extension called "Python Indent" installed, which seems suspicious. Can you try disabling all of your extensions other than Python and Pylance, and see if this issue still happens?

Btw, please post files as text rather than images so it's easier for us to reuse your content when trying to reproduce issues.

User settings:
```json
{
    "workbench.colorTheme": "Default High Contrast", 
    "editor.inlineSuggest.enabled": true, 
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false, 
        "editor.formatOnType": true, 
        "editor.wordBasedSuggestions": "off"
    },
    "editor.renderControlCharacters": false, 
    "lua.debug.settings.luaVersion": "jit",
    "files.associations": {
    },
    "aws.telemetry": false, 
    "yaml.schemas": {
    },
    "redhat.telemetry.enabled": false, 
    "atlascode.jira.jqlList": [
    ],
    "git.autofetch": true, 
    "git.openRepositoryInParentFolders": "never",
    "blender.executables": [
    ],
    "blender.allowModifyExternalPython": true, 
    "python.analysis.autoImportCompletions": true,
    "python.analysis.completeFunctionParens": true,
    "python.analysis.packageIndexDepths": [
    ],
    "files.autoSave": "onWindowChange",
    "editor.detectIndentation": false, 
    "pylint.args": [
        "--max-line-length=425",
        "--disable=C0114",
        "--disable=C0115",
        "--disable=C0116",
        "--indent-string='\\t'"
    ],
    "pylint.lintOnChange": true, 
}
```

Workspace settings:
```json
{
    "python.analysis.diagnosticSeverityOverrides": {
    },
    "python.analysis.typeCheckingMode": "basic",
    "pythonIndent.trimLinesWithOnlyWhitespace": true,
    "python.terminal.activateEnvInCurrentTerminal": true,
    "pylint.args": [
        "--max-line-length=425",
        "--disable=C0114" ,
        "--disable=C0115" ,
        "--disable=C0116" ,
        "--indent-string='\t'"
    ],
    "[python]": {
        "editor.insertSpaces": false, 
        "editor.tabSize": 4, 
        "editor.detectIndentation": false 
    },
}
```

**Comment by Maxxxel** [comment]
After removing the mentioned extension it works as it should!

And the extension calls itself a solution for the problem it causes, lol.
