### ISSUE TITLE
No IntelliSense in Jupyter notebook.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/pylance-release#5347]
## Environment data

-   Build of Visual Studio Code - Insiders: 1.86.0-insider  
-   Build of python-insider: v2023.25.10101826 
-   Build of pylance-insider: v2023.12.103 

## Repro Steps

1. Create a new directory somewhere on disk.
2. Open that new directory via File > Open Folder... 
3. Create a new Jupyter notebook 
4. Type ```import``` .

## Expected behavior

As you type, your completion list should open and prompt for your input accordingly.

## Actual behavior

Nothing came up.

<img width="503" alt="image" src="https://github.com/microsoft/pylance-release/assets/82852072/bb94b492-8747-4511-82a0-04ed71ce3cc3">

No errors are displayed.

<img width="147" alt="image" src="https://github.com/microsoft/pylance-release/assets/82852072/f172b16e-adf6-4e2f-9c78-a1750d667637">

**Comment by hidaris** [comment]
Based on the screenshot, it seems that you didn't select the Jupyter kernel.

**Comment by ttSpace** [comment]
I can repro it in today's build. After restart the VSCODE, IntelliSense works well. 

![error](https://github.com/microsoft/pylance-release/assets/82852072/3c4c0aef-b7a8-415c-a2b2-c7ba02e2ec99)

## Build info

<details>
<p>

```
Build of Visual Studio Code - Insiders: 1.86.0-insider 
Build of python-insider: v2023.25.10111009
Build of pylance-insider: v2023.12.103

```

</p>
</details>

**Comment by judej** [comment]
This does not repro on 2024.7.1.
