### ISSUE TITLE
Incorrect type after check of a nested object

### ISSUE THREAD

**Issue by Vlod-github** [microsoft/pylance-release#5348]
## Environment data

-   Language Server version: v2023.12.1
-   OS and version: WIn 10 and Fedora 36
-   Python version: 3.11.2 and 3.10.11

## Code Snippet
```python
from typing import TypedDict, Optional


class APIObjectInfo(TypedDict):
    ...


class APIObject(TypedDict):
    info: Optional[APIObjectInfo]


def main(objects: dict[int, APIObject], id_: int):
    if id_ in objects and objects[id_]['info'] is not None:
        value = objects[id_]['info']
    else:
        ...
```

## Expected behavior

The `value` variable is expected to be of type `APIObjectInfo`. Also incorrect type definition in case of `Union` and `isinstance()`.

## Actual behavior

In fact, the type of the variable is shown as `APIObjectInfo | None`. Typechecker ignores explicit type checking in the situation when we check a nested structure and then there are two options - the variable is valid or invalid.

**Comment by erictraut** [comment]
This is intended behavior, not a bug. Pyright (the type checker upon which pylance is built) does not apply type narrowing for subscripted expressions where the subscript is a variable, as in this case. This is also true for other type checkers like mypy. For details about pyright's type narrowing behavior, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=type-narrowing).

The recommended approach here is to use a temporary variable and an assignment expression (walrus operator).

```python
def main(objects: dict[int, APIObject], id_: int):
    if id_ in objects and (temp := objects[id_]["info"]) is not None:
        value = temp
    else:
        ...
```

**Comment by Vlod-github** [comment]
Thank you @erictraut for your quick and quality response
