### ISSUE TITLE
Type narrowing when one of two fields may be None

### ISSUE THREAD

**Issue by Peter9192** [microsoft/pylance-release#5350]
The following example:

```py
def a_or_b(a: int | None = None, b: int | None = None):
    assert a or b
    if not b:
        return a + 5
```

complains about: Operator "+" not supported for "None" Pylance ([reportOptionalOperand](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportOptionalOperand)). However, from the context it is clear that `a` cannot be `None`. Is there a way to get successful type narrowing in this case?

FYI, my real use case is a bit more complex, using pydantic validators to ensure the input is valid. Something like this, as discussed [here](https://github.com/pydantic/pydantic/issues/506#issuecomment-1704003183).

```py
from pydantic import BaseModel, model_validator

class AorB(BaseModel):
    a: int | None
    b: int | None

    @model_validator(mode='after')
    def check_a_or_b(self):
        if not self.a and not self.b:
            raise ValueError('Either a or b (or both) is required')
        return self
    
    def make_pylance_unhappy(self):
        if self.a is None:
            return self.b + 5
 ```

**Comment by erictraut** [comment]
The behavior of pyright (the type checker upon which pylance is built) is as designed here, so this isn't a bug.

Type narrowing is applied to individual symbols (in this case, `a` and `b`). Types are not tracked conditionally between symbols (e.g. "the type of `b` is `int` if `a` is `None` but `int | None` if `a` is not `None`"). The `assert` statement in this case is not able to narrow the type of either `a` or `b` in this case. You'll see the same error if you run other static type checkers (e.g. mypy) on this code.

If you want to learn more about type narrowing, refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced).

You can change your simple example as follows:

```python
def a_or_b(a: int | None = None, b: int | None = None):
    if not b:
        assert a
        return a + 5
```

In your "real" example, you can fix it by doing the following:

```python
    def make_pylance_unhappy(self):
        if self.a is None:
            assert self.b is not None
            return self.b + 5
```

**Comment by Peter9192** [comment]
Thanks for the swift response, I suspected as much. Just noting that I clicked "question" when creating this issue, so I never intended to report it as a bug.

**Comment by debonte** [comment]
> Just noting that I clicked "question" when creating this issue, so I never intended to report it as a bug.

@rchiodo, this makes me wonder if we should have a "Question" option when creating new issues or perhaps just steer questions towards the discussions area. Or maybe we need a "question" label.

**Comment by rchiodo** [comment]
> @rchiodo, this makes me wonder if we should have a "Question" option when creating new issues or perhaps just steer questions towards the discussions area. Or maybe we need a "question" label.

There's actually a `question` option already:

![image](https://github.com/microsoft/pylance-release/assets/19672699/c1197547-253f-4762-baff-c8a3418f4a4f)


I wonder if we can just redirect that to the discussions tab?

**Comment by debonte** [comment]
Sorry, what I meant was, maybe we should remove it.
