### ISSUE TITLE
Multi-root workspace with diff Python interpreters selected: Intellisense issue

### ISSUE THREAD

**Issue by jirpok** [microsoft/pylance-release#5355]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

In a multi-root workspace, I have two directories. I've selected the appropriate Python interpreter for each of them (I use pipenv). 

When I have files open from both directories, the Python extension provides installed package intellisense only for one of them (the one that comes first in the Explorer tab, not sure whether that's relevant or not). 

If I close all files from that first directory, the behavior persists. I have to restart VS Code. Then, when I only have files open from the second directory, intellisense works. The moment I open a file from the first dir, it stops working again.

Expected behavior is to have intellisense respect each file's virtual env.

## Steps to reproduce:

1. Have a multi-root workspace with at least two dirs, a and b.
2. Create different virtual environment using Pipenv for each of them.
3. Choose correct Python interpreters from their virtual environments for each of them.
4. Install different packages to both envs. 
5. Open files from both dirs at once. 
6. Try to import a package in a file from dir b, intellisense does not work in my case.
7. Close all files from dir a.
8. Restart VS Code.
9. Intellisense in file from b works until you open a file from dir a.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): PipEnv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
No warnings or errors.
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

testing
• pytestEnabled: true
• unittestArgs: "<placeholder>"
• unittestEnabled: true

terminal
• activateEnvironment: false

experiments
• enabled: false

```

</p>
</details>

Extension version: 2023.22.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.6.6-76060606-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 3301)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|15.35GB (9.73GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Is this similar to what you have?

![image](https://github.com/microsoft/pylance-release/assets/19672699/c103c7c3-395d-4294-bdd2-46cda07df0ce)

You wouldn't be able to reference root1 from root2 because it's not in the search path. Pylance is treating these two folders as if they're independent of each other. 

This setting here is one way to make this work:

```jsonc
"python.analysis.extraPaths": [".."]
```

But I'm not sure you're talking about referencing your user files. This is a little ambiguous for me:

> Try to import a package in a file from dir b, intellisense does not work in my case.

Import what package? A package in the virtual environment? A package in the 'A' folder?

Can you show a screenshot of your import error? Or describe it in more detail.

**Comment by jirpok** [comment]
Hey Rich,

thanks for following up on this. 

I've recreated the workspace as per your example and I can't reproduce the issue :/ 

There has to be sth wrong with my setup, it could've been a glitch, I don't know. I abandoned the workspace after experiencing it and have been working in separate windows since.

Please accept my apologies, I really appreciate your feedback. 

I'll investigate further and let you know/reopen the issue if appropriate.

Best,

Jiri
