### ISSUE TITLE
Rename Symbol makes mistakes with for loop variables

### ISSUE THREAD

**Issue by studyingegret** [microsoft/pylance-release#5359]
Type: <b>Bug</b>

**Steps to reproduce**
1. Type the following Python (`db` is fictional and left undefined):

   ```python
   NTHREADS = 10
   NRECORDS = 1000
   RECORD_PER_THREAD, _REMAINDER = divmod(NRECORDS, NTHREADS)

   def worker(id):
       for id in range(RECORD_PER_THREAD*id,
                       min(RECORD_PER_THREAD*(id+1), NRECORDS)):
           db.User(id, str(id)).store()
   ```
2. Right-click on the `id` in `def worker(id):`, and click "Rename Symbol" to rename as `thread_id`. Observe results.
3. Revert the code to Step 1. Then right-click on the `id` in `for id`, and click "Rename Symbol" to rename as `user_id`. Observe results.
4. Revert the code to Step 1. Then right-click on the `id` in `db.User(id, ...)`, and click "Rename Symbol" to rename as `user_id`. Observe results.

**Expected results**

In Step 2, the function becomes

```python
def worker(thread_id):
    for id in range(RECORD_PER_THREAD*thread_id,
                    min(RECORD_PER_THREAD*(thread_id+1), NRECORDS)):
        db.User(id, str(id)).store()
```

In Steps 3 and 4, the function becomes

```python
def worker(id):
    for user_id in range(RECORD_PER_THREAD*id,
                    min(RECORD_PER_THREAD*(id+1), NRECORDS)):
        db.User(user_id, str(user_id)).store()
```

*Note:* The ragged indent of the third line is expected unless auto-formatting takes place; same for below

**Actual behavior**

In Step 2, the function becomes

```python
def user_id(thread_id):
    for thread_id in range(RECORD_PER_THREAD*thread_id,
                    min(RECORD_PER_THREAD*(thread_id+1), NRECORDS)):
        db.User(thread_id, str(thread_id)).store()
```

In Steps 3 and 4, the function becomes

```python
def user_id(user_id):
    for user_id in range(RECORD_PER_THREAD*user_id,
                    min(RECORD_PER_THREAD*(user_id+1), NRECORDS)):
        db.User(user_id, str(user_id)).store()
```

*Note:* The bug still exists when no variables are undefined, for example, after replacing `db.User(id, str(id)).store()` with `print(id, str(id))`.

Extension version: 2023.5.30
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.90GB (1.06GB free)|
|Process Argv|--crash-reporter-id 0ca47609-b826-438d-be24-b5589e9edec2|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by erictraut** [comment]
You listed the "extension version" as "2023.5.30". Is that the version of the Pylance extension or the Python extension? In either case, that's a very old version. Could you please update to the latest release and see if that fixes the issue? I'm not able to repro the problem as reported with the latest release of Pylance.

**Comment by studyingegret** [comment]
It's the version of the Pylance extension. VS Code on my computer does not prompt me to update Pylance now, but admittedly my VS Code version is quite old (1.76.2, 10 months ago) and does not provide me an option to install Pylance > 2023.5.30. If it works for you I guess I'll need to update VS Code to check again.

**Comment by studyingegret** [comment]
@erictraut I can still reproduce the bug on my side, with VS Code 1.85.1, Pylance 2023.12.1, Python extension 2023.22.1. Can you tell me your version information? Also, should I try the pre-release version?

**Comment by debonte** [comment]
This repros for me on both Pylance 2023.12.1 (release), Pylance 2023.12.103 (prerelease), and Pyright 1.1.347.

So, to be clear, your expectation is that the `id` in `for id` is declaring a new variable within the `for` loop's scope rather than assigning to the `worker` function's `id` parameter?

That doesn't seem to be the behavior at runtime. The following code prints 0 1 1, not 0 1 2:

```python
def worker(id):
    for id in range(0, id):
        print(id)

    print(id)

worker(2)
```

**Comment by debonte** [comment]
Btw, comprehensions on the other hand do have a separate scope for their loop variables. The following does print 0 1 2:

```python
def worker_comprehension(id):
    [print(id) for id in range(0, id)]

    print(id)

worker_comprehension(2)
```

**Comment by erictraut** [comment]
Ah, I misunderstood the bug report. The "actual behavior" observed in this case is correct. That's because `id` refers to the same symbol everywhere it occurs within the `worker` function. All instances of `id` are semantically identical and therefore should receive the updated name. Unlike some other programming languages, Python does not introduce a new scope for `for` statements. As @debonte points out, comprehensions _do_ introduce a new scope in Python.
