### ISSUE TITLE
Periodically getting "cannot activate pylance" in dev container

### ISSUE THREAD

**Issue by red8888** [microsoft/pylance-release#5366]
Type: <b>Bug</b>

This is not totally broken, I get this _occasionally_ when launching my dev container. I see issues online complaining about this not working at all, but I only see this on occasion.

When I get "cannot activate pylance" I reload the window and every time it works after that.

What could cause this? Is there some race condtion wrt the container launching process? In what order does pylance try to connect and where should I look to find the issue?

This has always been an issue for me on every machine I've used vscode on so I'm wondering if its just a long running bug syncronizing the container launch with extensions.

I haven't been able to capture logs when it happens though.

I also get this error sometimes, reloading always fixes it:

> Cannot activate the 'Pylance' extension because it depends on the 'Python' extension, which is not loaded. Would you like to reload the window to load the extension?

Extension version: 2023.12.1
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux x64 6.5.11-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (0.65GB free)|
|Process Argv|--crash-reporter-id 96d26004-b6a2-41a4-a0ba-b026e700ad63|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 @ desktop-linux|
|OS|Linux x64 6.5.11-linuxkit|
|CPUs|unknown (12 x 0)|
|Memory (System)|7.66GB (3.76GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30933248
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by luabud** [comment]
Just found this upstream issue at the VS Code repo, so closing this as a dupe: https://github.com/microsoft/vscode/issues/196794
