### ISSUE TITLE
Remove return type from __init__ override member completion

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5367]
### Discussed in https://github.com/microsoft/pylance-release/discussions/2593

<div type='discussions-op-text'>

<sup>Originally posted by **savannahostrowski** May 10, 2021</sup>
If I'm in a typeCheckingMode of "off", I don't want to see a return type for function snippets.

![image](https://user-images.githubusercontent.com/8949415/117730846-e84acf80-b1a1-11eb-9239-e79fe3d5db0e.png)
</div>

**Comment by luabud** [comment]
we just converted this back to an issue to add it to our roadmap

**Comment by JacobCallahan** [comment]
Very happy to see this get resolved!

**Comment by mattskel** [comment]
Did this ever get resolved? Experiencing similar for `__call__`. Especially bad when overriding a method from an inherited class. on Pylance `v2024.4.1`

**Comment by debonte** [comment]
> Did this ever get resolved?

@mattskel, not yet. Based on up-votes we converted it from an enhancement discussion back into an issue, but we haven't acted on it yet.

**Comment by heejaechang** [comment]
so, we don't want to add typing for override when typing mode is off? doing that is easy but LS experience will be degraded since we no longer know what arguments/return types are. either perf will degrade (since we now need to infer (calculate) it or can't figure out at all) or no more completion will be offered for arguments.

**Comment by mdragoss** [comment]
I would like to see these implemented.

**Comment by Perverance** [comment]
Hi. Is there any news regarding this issue? I can't find a way to deactivate this autocompletion anywhere. The only solution I've found is not to use the extension...

**Comment by heejaechang** [comment]
currently, in `a/b` testing.

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.11.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202411100-6-November-2024-PreRelease)
