### ISSUE TITLE
"Type annotation not supported for this type of expression" when dynamically adding a property.

### ISSUE THREAD

**Issue by ptrxyz** [microsoft/pylance-release#537]
## Environment data

-   Language Server version: Pylance language server 2020.10.2 (pyright d6db7c90)
-   OS and version: Arch Linux, Kernel 5.9.1
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.8.6

## Expected behaviour

Assume the following minimal example:
```python
class Foo():
    a = 99


Foo.prop: int = property(lambda self: self.a + 1)
```
I'd expect pylance to detect that `Foo.prop` is a of type `int`. ...

## Actual behaviour
... however, pylance throws an error: `"Type annotation not supported for this type of expression" `

## Logs
--

## Code Snippet / Additional information

see above.

**Comment by erictraut** [comment]
Attributes and their types must be declared as part of the class. If you attempt to access an attribute that is not declared within the class, that is exactly the sort of programming error that a static type checker is designed to flag.

In your example above, you would need to declare the `prop` as part of the class.

```python
class Foo():
    a = 99

    @property
    def prop(self):
        return self.a + 1
```

If there is some reason why a static declaration won't work, then you can effectively disable the static type checker by doing the following:

```python
cast(Any, Foo).prop = property(lambda self: self.a + 1)
```

I wouldn't recommend this approach because it leaves you completely exposed to bugs that would otherwise be caught by the type checker.

**Comment by jakebailey** [comment]
I don't think this is legal in the grammar, as the grammar says what appears before the colon must be a `NAME`, the identifier token which wouldn't have dots in it, versus `dotted_name` which does.

https://docs.python.org/3/reference/grammar.html

**Comment by A-UNDERSCORE-D** [comment]
Legal or not it _does_ work for assignment (as in the parser accepts it), however the annotations are not available at runtime and therefore arent processed. I _would_ like some support for this because I have legacy code that does this kind of silliness, but would also understand if you're not gonna support it.

**Comment by erictraut** [comment]
This is supported in the grammar, but it is not semantically legal. It wouldn't make sense to allow this from the perspective of a static type checker.

**Comment by jakebailey** [comment]
I'm going to close this for now; if this continues to be an issue we can revisit it, but this doesn't seem like a pattern we really want to support.

**Comment by JosephTLyons** [comment]
What about for function objects?  This sort of assignment to a function object is flagged with the same error, only I don't really know of the proper alternative.  The original question here was about classes, so the proper alternative is to define it in the class, but there's not really a way to do that with functions.

I know there are some popular Python libraries that do random on-the-fly creations of variables that are attached to function objects.

**Comment by erictraut** [comment]
@JosephTLyons, I don't think I understand what you're trying to do. It sounds like it's not directly related to this issue.

If you think there's a bug or want to submit an enhancement request, please open a new issue. If you just want advice about how to annotate a piece of code so it works well with the type checker, feel free to use the discussion section and post a question. In either case, it would be helpful if you could provide a minimal, self-contained example.

**Comment by JosephTLyons** [comment]
I don't know if its a bug or not, it just seems similar to what was originally written here, only done with functions instead of class instances:

```python
def do_something():
    pass

do_something.new_variable: int = 1   # "Type annotation not supported for this type of expression"
```

**Comment by erictraut** [comment]
This isn't (and shouldn't be) allowed by a type checker. It's equivalent to adding new attributes to a class that doesn't declare them.

```python
class A:
    ...

A().new_variable = 1  # Error: `new_variable` doesn't exist on object of type A
```

In general, there isn't good support in the Python type system for defining function objects that have additional (non-standard) attributes. This practice is pretty rare. It's more typical to use a object that stores both a function (either a callback stored as an instance variable or a method declared as part of the class) and associated attributes. You can optionally define a `__call__` method on the class so you can invoke the object in a call expression.

```python
class SomethingDoer1:
    new_variable: int
    def __call__(self):
        # Implement do_something logic here
        pass
```

or

```python
class SomethingDoer2:
    new_variable: int
    do_something: Callable[[], None]
    def __call__(self):
        return self.do_something()
```

Do either of these work for you?

Another approach (that is less type friendly and less robust) is to use a cast.

```python
cast(Any, do_something).new_variable = 1
```

**Comment by JosephTLyons** [comment]
I do realize it is a less common thing.  It came up while I was writing a decorator that did something similar to `_lru_cache_wrapper`, where I need to add an additional field onto a function so the user can access new information.  It definitely makes more sense to tie the variable and the function together via a class, but I'm not sure how that works with a decorator that is supposed to return a wrapper function.  It is possible there's a way, so I'll look into it.  If not, `# type: ignore` suppresses the error.
