### ISSUE TITLE
I am starter for Python, and it seems being in labyrinth.

### ISSUE THREAD

**Issue by yuesugi0001** [microsoft/pylance-release#5373]
<h3> Environment data </h3>

-   Language Server version: 2023.12.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by luabud** [comment]
Hi @yuesugi0001, can you share problems you're having with Python in VS Code? We have some tutorials that may be helpful.
- [Getting Started with Python in VS Code](https://code.visualstudio.com/docs/python/python-tutorial): this is a good one if you want a more complete and lengthy explanation on the basics of the Python support in VS Code
- [Python in VS Code quickstart](https://code.visualstudio.com/docs/python/python-quick-start): this is a summarized version of our tutorial, with quicker steps outlined to get you up and going with Python in VS Code.
