### ISSUE TITLE
Pylance Not effective

### ISSUE THREAD

**Issue by cnahmgx** [microsoft/pylance-release#5374]
I chose Conda's interpreter(Linux machines) on VSCode, but the Pylance still hasn't taken effect

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?
