### ISSUE TITLE
Indexing time with 2023.12.104 is about 3x slower

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5382]
1. Open a  folder 
2. Install a number of packages into the venv
3. Wait for the 'indexing finished' log output

It will be about 3x slower than with version 2023.12.1

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2024.1.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20241100-24-January-2024-PreRelease)
