### ISSUE TITLE
No docstrings shown for stdlib symbols

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5383]
-   Language Server version: 2023.12.104 (regression from 2023.12.103)
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.1

## Code Snippet

```python
dict()
```

## Repro Steps

1. Hover over `dict`

## Expected behavior

Hover output contains `dict` docstring:

![image](https://github.com/microsoft/pylance-release/assets/12820898/2d0af8d9-48fd-48b5-9a2b-9958d76bae81)

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/12820898/72c1cb71-f635-4d63-9acc-673eff7daeeb)

**Comment by bschnurr** [comment]
done

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2024.1.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20241100-24-January-2024-PreRelease)
