### ISSUE TITLE
Pylance fails to derive the type defined in class attributes

### ISSUE THREAD

**Issue by jackjyq** [microsoft/pylance-release#5390]
## Environment data

-   Language Server version: ms-python.vscode-pylance-2023.12.1
-   OS and version: Windows 11 23H2
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10 CPython

## Code Snippet

```python
from abc import ABC
from dataclasses import dataclass


@dataclass(kw_only=True)
class BaseRecordType:
    """database record type"""

    key: int


class BaseDatabase(ABC):
    """database class"""

    record_type = BaseRecordType

    def read(self, key: int) -> record_type:
        """read the record from database and return record_type"""
        data = {"key": key}  # simulate reading from the database

        return self.record_type(**data)


@dataclass
class DerivedRecordType(BaseRecordType):
    """let say we have another database which has extra field

    fist, we need to define the derived data type"""

    extra: str = "default extra field"


class DerivedDatabase(BaseDatabase):
    """then, we override the class attribute to change the record type"""

    record_type = DerivedRecordType


def read_derived_database(key: int) -> DerivedDatabase:
    database = DerivedDatabase()
    database.read(key)

    #     Expression of type "record_type" cannot be assigned to return type "DerivedDatabase"
    #   "record_type" is incompatible with "DerivedDatabase"PylancereportGeneralTypeIssues
    return database.read(key)


print(read_derived_database(1))
```

## Repro Steps

1. Paste the above code into VSCode with Pylance installed
2. Pylance raises `PylancereportGeneralTypeIssues` for the line `return database.read(key)`
3. However, if we run the code, it works as expected
   
## Expected behavior

Pylance should not raise any issue

## Actual behavior

Pylance raises `Expression of type "record_type" cannot be assigned to return type "DerivedDatabase" "record_type" is incompatible with "DerivedDatabase"PylancereportGeneralTypeIssues`

## Logs

```
XXX
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working correctly here. The `read` method in `BaseDatabase` is declared as returning the type `record_type`. This is a type alias for the type `BaseRecordType`.

If your intent is for `read` to return a different type for each subclass, then the base class should be defined as generic, like this:

```python
from typing import Generic, TypeVar

TRecord = TypeVar("TRecord", bound=BaseRecordType)

class BaseDatabase(ABC, Generic[TRecord]):
    record_type: type[TRecord]

    def read(self, key: int) -> TRecord:
        data = {"key": key}

        return self.record_type(**data)
```

Or if you're using Python 3.12, you can use the new syntax for generics:

```python
class BaseDatabase[TRecord: BaseRecordType](ABC):
    record_type: type[TRecord]

    def read(self, key: int) -> TRecord:
        data = {"key": key}

        return self.record_type(**data)
```
