### ISSUE TITLE
convert to relative path doesn't work with `network folder`

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5401]
1. clone https://github.com/microsoft/pylance-release/tree/main/testing/single
2. create a network folder `NetworkFolder` to the `single` folder
3. open `//NetworkFolder/single` in `vscode`
4. run `convert to relative path` code action on https://github.com/microsoft/pylance-release/blob/main/testing/single/src/codeaction.py#L74

expected:
convert to relative path work.

actual:
generate invalid path.

...

it works with `2023.12.1`

**Comment by rchiodo** [comment]
Weird. I get the network root in the included path:

# place curosr on `userModule` and confirm lightbulb shows up
# and trigger quick fix and confirm `Convert to relative path` is listed
# execute the code action and confirm it works as expected
from .//COMPUTERNAME/.single.src.lib.userModule import ConvertImportPath

**Comment by debonte** [comment]
This has the same underlying cause as #5399. Resolving as a dupe.
