### ISSUE TITLE
Unknown import symbol only when using "stubs"

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/pylance-release#5411]
When making a copy of a file in order to create a "stub" file, the imported symbols that worked ok in regultar `.py` files raises a "Unknown import symbol" error after create the `.pyi` file.

## Environment data

-   Language Server version: 2023.12.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.11.5 Anaconda

## Repro Steps

1. Create tree files: `foo.py`, `bar.py` and `spam.py` in the same folder.

    Contents of `foo.py`:
    ```python
    class Test:
        ...
    ```
    Contents of `bar.py`:
    ```python
    from foo import Test
    ```
    Contents of `spam.py`:
    ```python
    from bar import Test
    ```

2. Check that there are no problems with the imported symbols in all files.
3. Make a copy of `bar.py` and name it `bar.pyi` (i.e. create a stub file)
4. Now the line inside `spam.py` ("`from bar import Test`") shows the following error:
    ```
    "Test" is unknown import symbol
    ```

## Expected behavior

I expected the same behaviour in both cases of using `bar.py` or `bar.pyi` when the 2 files have the same content, which are type definitions.

Please, clarify if it is not correctly expected.

## Actual behavior

There is an error raised after create the stub file.

**Comment by erictraut** [comment]
The behavior you've described is correct, not a bug.

A stub file is meant to be a "stand-in" for a module when that module is untyped or written in a language other than Python. When you import a module, a type checker will attempt to resolve the import first using a type stub if it is present. In your example, you've created a type stub named "bar.pyi", but you haven't populated it with any type information. That means any file that imports from "bar" will see no symbols exported from that module.

If you want to create a proper type stub for "bar", you should provide type information within the stub file. For example, if "bar.py" is intended to export the symbol `Test`, which it in turn imports from the "foo" module, you should add the following line to `bar.pyi`:

```python
from foo import Test as Test
```

Note the redundant import form. This is required by the Python typing standard if the intent is for the type stub to re-export a symbol imported form another module. By default, symbols imported by a type stub are considered private to that stub and are not re-exported.

The behavior of type stubs is documented in the official [Python typing spec](https://typing.readthedocs.io/en/latest/spec/distributing.html#stub-files). Pyright (the type checker upon which pylance is built) follows this standard.

**Comment by Diogo-Rossi** [comment]
@erictraut thank you for the clarification.

So... to manually create stub files for existent modules, I need also to resolve the imports, not just add type annotations.
