### ISSUE TITLE
Visual Studio Code IntelliSense issue with Python 

### ISSUE THREAD

**Issue by mohiruhu** [microsoft/pylance-release#5422]
Hi There: 
Code Snippet

![image](https://github.com/microsoft/vscode-python/assets/58624180/ff476c53-207b-4eab-abba-6fd17c9ba148)

When I install python interpreter this IntelliSense does not work.

**Comment by heejaechang** [comment]
we probably need code snippet to repro the issue and the expected behavior and actual behavior so we know what we are looking for.
