### ISSUE TITLE
Extract method and variable not working on Untitled notebooks in WSL 

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#5424]
<h3> Environment data </h3>

-   Language Server version: 2024.1.102
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12, Anaconda
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic
![image](https://github.com/microsoft/pylance-release/assets/45497113/4d445d75-d5e7-444e-8d2d-e17c040740b9)

![image](https://github.com/microsoft/pylance-release/assets/45497113/d50c68a5-0197-45cd-a681-ded4b65ae825)

<h3> Code Snippet </h3>

An untitled notebook with the following sample:

```python
x = 10
y = 20
print(x+y)
```

<h3> Repro Steps </h3>

1. Create a new untitled notebook with the code sample above
2. Select all the code in the cell and trigger the "extract method" code action

<h3> Expected behavior </h3>

It should extract the method in that same cell like it does when using the latest stable version of the 3 extensions:
![pylanceworkingjan3024](https://github.com/microsoft/pylance-release/assets/45497113/ba0635f3-dcc5-4241-9ed4-25c1256a5c77)

<h3> Actual behavior </h3>

It extracts the method in a separate untitled Python file
![pylancebugjan3024notebooks](https://github.com/microsoft/pylance-release/assets/45497113/ff525863-a7cd-4fc3-bac1-6f62744bea4d)

<h3> Logs </h3>

[pylancelogsnotebookswsljan3024.txt](https://github.com/microsoft/pylance-release/files/14104688/pylancelogsnotebookswsljan3024.txt)

**Comment by luabud** [comment]
Also reproducing it on Windows:

![pylancebugjan3024notebookswindows](https://github.com/microsoft/pylance-release/assets/45497113/c6a258f8-90ea-495f-9f8d-7518eb7fe25b)

**Comment by luabud** [comment]
Interestingly enough, if I enable sync server it fails silently:
> 2024-01-30 13:54:50.948 [info] [Trace - 1:54:50 PM] Received response 'workspace/executeCommand - (50)' in 17ms. Request failed: Request workspace/executeCommand failed with message: applyEditSync failed with error 0 (-32603).
2024-01-30 13:54:50.949 [info] [Error - 1:54:50 PM] Request workspace/executeCommand failed.
2024-01-30 13:54:50.949 [info]   Message: Request workspace/executeCommand failed with message: applyEditSync failed with error 0
  Code: -32603

**Comment by rchiodo** [comment]
sync server failure should be this bug:
https://github.com/microsoft/pylance-release/issues/5404

**Comment by rchiodo** [comment]
Oh I think I know the problem. The `.py` in the notebook name. It's not being removed from the cell uri.

`untitled://Untitled-1.ipynb.py?jupyter-notebook#W0sdW50aXRsZWQ=`

It's likely the mapped cell uri is not being used in the extract method.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2024.1.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20241103-31-January-2024-PreRelease)
