### ISSUE TITLE
"Auto-Import" imports from wrong path when import format is "relative"

### ISSUE THREAD

**Issue by maflAT** [microsoft/pylance-release#5427]
## Environment data

-   Language Server version: v2024.1.102
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.1

## Code Snippet
While typing:
![grafik](https://github.com/microsoft/pylance-release/assets/13979550/f7f209cc-f447-4e4c-bd2f-07dd5bbd73a7)

After pressing Tab:
![grafik](https://github.com/microsoft/pylance-release/assets/13979550/40838aaa-6380-4035-a5d0-677e7b147f38)

## Repro Steps

1. Have a workspace with custom type stubs in a local folder that override an installed package.
   In my case I have PySide6 intalled in the default site-packages and locally I have a `./typings/PySide6/QtCore.pyi` defined.
2. Have `"python.analysis.importFormat"` set to `"relative"`.
3. Create a new python file and type the name of a symbol defined in those stubs.
4. Auto-Import the symbol either by pressing Tab or via quick fix

## Expected behavior

Pylance generates an import statement which points to the installed package. In this case:
```python
from PySide6.QtCore import QObject
```

## Actual behavior

The generated import statement points to the local stub directory instead:
```python
from ..typings.PySide6.QtCore import QObject
```
Pylance/Pyright will also correctly recognize the problem and display a warning.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.2.103, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20242103-22-February-2024-PreRelease)
