### ISSUE TITLE
Cell URI to notebook URI conversion fails if path only contains filename

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5435]
## Environment data

-   Language Server version: 2024.1.103
-   OS and version: Windows 11

## Repro Steps

1. Put a breakpoint in `PylanceAsyncServer.getWorkspaceForFile` where we call `getNotebookUriFromCell`
2. Create an untitled notebook
3. Breakpoint gets hit
4. Step over `getNotebookUriFromCell` call and check resulting URI
5. Step over `getNotebookData` call and check result.

## Expected behavior

`getNotebookUriFromCell` returns the notebook's URI. `getNotebookData` returns the notebook data.

## Actual behavior

`getNotebookUriFromCell` returns an incorrect URI with the filename included twice:
`untitled:Untitled-1.ipynb.py/Untitled-1.ipynb` 

`getNotebookData` returns `undefined`.

I'm unsure what user impact this has in VS Code. It was causing problems in other clients.

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2024.1.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20241104-1-February-2024-PreRelease)
