### ISSUE TITLE
`PyLance` recommend `list` instead `List` (upper case) 

### ISSUE THREAD

**Issue by yiliu30** [microsoft/pylance-release#5442]
I am using the `PyLance` extension in VS Code. It recommends `list` instead of `List` as below. 
According to [PEP 484](https://peps.python.org/pep-0484/), it should be `List`?

![image](https://github.com/microsoft/pylance-release/assets/106061964/4598b5d7-15cf-499d-82a5-e73c701778b7)

**Comment by erictraut** [comment]
[PEP 585](https://peps.python.org/pep-0585/) supersedes PEP 484 in this regard. As of Python 3.9, you no longer need to use the capitalized versions of `List`, `Tuple`, etc. These older forms are still supported but are no longer the preferred approach.

**Comment by yiliu30** [comment]
Thanks for pointing it out. 
Since I usually use Python 3.8, is it possible to configure `PyLance` to recommend `List` rather than `list`?

**Comment by erictraut** [comment]
I won't speak for the Pylance team, but Python 3.8 is pretty ancient at this point, so building features to support it may not be a good use of their time. Python 3.8 falls out of official support later this year. You might want to upgrade sooner rather than later.

**Comment by yiliu30** [comment]
Nice catch, thank you for your suggestion.
