### ISSUE TITLE
Too many tabs inserted on newline in function signature

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/pylance-release#5445]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

When I insert a newline in a function signature, even though I have it selected to insert only 4 tabs, it inserts 8. It does this for every parameter.

<img width="1840" alt="Screenshot 2024-02-05 at 11 33 28" src="https://github.com/microsoft/vscode-python/assets/27844407/ffdd5b17-185e-4405-aa9d-2a4c66287c03">

## Steps to reproduce:

1. Enable the Python extension.
2. Try to create a function signature with each parameter on a new line.

https://github.com/microsoft/vscode-python/assets/27844407/2cd46ac8-8fbb-4998-a35a-02d2c770ecd1

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.5
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2024.0.0
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:11.430Z)
OS version: Darwin arm64 23.2.0
Modes:
Remote OS version: Linux x64 5.15.0-89-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 8106252b-2e2a-45d6-a119-685169d4080a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lambda|
|OS|Linux x64 5.15.0-89-generic|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor (64 x 2200)|
|Memory (System)|251.54GB (213.85GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019bcf:30953938
3ef8e399:30949928

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue but this is actually on purpose. We are actually following PEP8's recommendations for spacing. You can see the discussion here:

https://github.com/microsoft/pylance-release/discussions/4534

There is a workaround, set this to false and indentation should follow the defaults from VS code:

```json
    "[python]": {
        "editor.formatOnType": false,
    }
```
