### ISSUE TITLE
# type: ignore at the top of a notebook

### ISSUE THREAD

**Issue by memeplex** [microsoft/pylance-release#5452]
Is there any way to get `# type: ignore` to work for an entire notebook and not just a cell?

Or another similar way to achieve that?

Thanks

**Comment by rchiodo** [comment]
This would do it:

```jsonc

    "python.analysis.ignore": ["**/*.ipynb*"]
```

That ignore all diagnostics in all notebooks. The `*` on the end is necessary because internally a `.py` is appended to a notebook cell.

**Comment by memeplex** [comment]
Thanks. Is this equivalent? Only disables reporting but otherwise keeps analysis going for autocomplete, navigation and other stuff?

**Comment by rchiodo** [comment]
Yes, it should be equivalent. All the other features still work, it just disables reporting of errors.

**Comment by memeplex** [comment]
I'm having some problems with the proposed solution.

Suppose I have a project in ~/Documents/Project.

In my user settings there is the line `"python.analysis.ignore": ["**/*.ipynb*"]`.

With ~/Documents/Project open in VSCode I open ~/Desktop/Scratchpad.ipynb.

But then type checking is enabled in Scratchpad.ipynb.

It seems that for files outside the project ignore rules are not applied, even though it's a user level config.

**Comment by rchiodo** [comment]
Yeah that's because the workspace is included in the regex we generate from the ignore path. It's prepended onto the ignore path. Seems like a bug to me, not sure why we have to stick the workspace onto it. But might be by design, need to do more digging. The code is pretty explicit about using the workspace root as the beginning of the regex:

https://github.com/microsoft/pyright/blob/5d78e9eebad30e500b424d8df57e77ae4efaff24/packages/pyright-internal/src/common/pathUtils.ts#L497-L498

I think you can workaround the problem by specifying multiple patterns though. If the ignore spec is rooted itself, it shouldn't prepend the workspace root.

**Comment by memeplex** [comment]
> I think you can workaround the problem by specifying multiple patterns though. If the ignore spec is rooted itself, it shouldn't prepend the workspace root.

I tried that but it doesn't seem to work, or perhaps I'm misunderstanding you. E.g.

```
"python.analysis.ignore": ["**/*.ipynb*", "/Users/carlos/Desktop/Scratch.ipynb"],
```

has no effect.

Weirdly enough, I noticed that in a multi-root workspace even the general `"**/*.ipynb*"` has effect, but for a single folder project there seem to be no workaround.

I can file a ticket for this issue for this if you see it fit.

**Comment by rchiodo** [comment]
The setting would be more like this:

```
"python.analysis.ignore": ["**/*.ipynb*", "/Users/carlos/Desktop/*.ipynb*"],
```

It needs the '*' at the end because the actual internal file name will have a `.py` appended.

For example, this works for me:

```
    "python.analysis.ignore": ["**/*.ipynb*", "C:\\Users\\rchiodo\\**\\*.ipynb*"],
```

**Comment by memeplex** [comment]
You're right! I forgot about the `*` at the end thing, sorry. `/**/*.ipynb*` seems to be enough, I'm going to give it a try. Thanks!

**Comment by memeplex** [comment]
Sorry for revisiting this once again. I realized that this solution is too drastic. It's not the same as `typeCheckingMode = off` because all analysis is skipped, not only type checking. What I would like to achieve is to have type checking off in notebooks, since they are usually exploratory and type analysis becomes a hindrance with so many false positives, but still have some convenient linting as with `typeCheckingMode = off`. When there is a mix of python and notebook files in a project, it seems like I only can turn type checking off for both of them, or to skip analysis altogether for notebooks.

**Comment by rchiodo** [comment]
Another solution is to put your notebooks into a separate folder and add that folder to a separate workspace. You can then have a  per workspace settings and set typecheckmode=off in just that folder.

**Comment by memeplex** [comment]
Yes, a multi-root workspace, I was thinking something like that, so if there's no other workaround I'm going to do as you said, I hope there is no problem with nested folders. Thanks again!
