### ISSUE TITLE
BoolProperty suddenly being marked as incorrect

### ISSUE THREAD

**Issue by hkunz** [microsoft/pylance-release#5455]
Type: <b>Bug</b>

Initially I thought this was a VSCode bug as [logged here](https://github.com/microsoft/vscode/issues/204797) but I was told this is a Pylance bug. I'm not sure if this is reproducible for others but in my VSCode which used to work with Pylance extension now suddenly is bugged. Create test.py file and just paste this code. Same problem even after updating to latest version VSCode 1.86.1
```
import bpy

class StupidClass(bpy.types.PropertyGroup):
    export_format: bpy.props.BoolProperty(
        name="asdf",
        description="asdf",
        default=False,
    )
```
And now all of a sudden VSCode underlines everything starting at name="asdf" as being incorrect "Call expression not allowed in type expression". This used to work and all of a sudden VSCode is bugged.

![image](https://github.com/microsoft/vscode/assets/2459196/0c008368-7f8e-4c1d-9b40-cf2599c730e9)

![image](https://github.com/microsoft/vscode/assets/2459196/a8034fc7-6061-49ed-bac3-8a4091d0cfc1)

I tried uninstalling and reinstalling Pylance extension for VSCode again but same problem. This is the version:

![image](https://github.com/microsoft/pylance-release/assets/2459196/caf796d6-2ac0-4869-84e8-0e292da74113)

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3503)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.48GB (24.87GB free)|
|Process Argv|--crash-reporter-id b01f801d-27b3-48c9-bd22-8ee05483775e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vcpkg-cmake-tools|Jac|2.0.9
blender-development|Jac|0.0.19
c-compiler-pretifier|jhe|1.0.0
vscode-clangd|llv|0.1.26
debugpy|ms-|2024.0.0
python|ms-|2024.0.1
vscode-pylance|ms-|2024.2.1
remote-wsl|ms-|0.81.9
cmake-tools|ms-|1.16.32
cpptools|ms-|1.18.5
makefile-tools|ms-|0.8.22
cppcheck-plugin|Nat|0.0.3
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928
e3gdj431:30958358

```

</details>

**Comment by debonte** [comment]
Pylance is behaving correctly here. The return value of a function cannot be used as a type annotation. Pyright, the type checker that Pylance is built on top of, has recently been working to adhere more closely to the typing spec. If this is a recent change in behavior, my guess is it is related to that work.

There's more detail on valid type expressions for type annotations here: https://github.com/python/typing/blob/main/docs/spec/annotations.rst#valid-type-expression-forms.

**Comment by hkunz** [comment]
But why is blender accepting this code and it works when I run it?

**Comment by hkunz** [comment]
> Pylance is behaving correctly here. The return value of a function cannot be used as a type annotation. Pyright, the type checker that Pylance is built on top of, has recently been working to adhere more closely to the typing spec. If this is a recent change in behavior, my guess is it is related to that work.
> 
> There's more detail on valid type expressions for type annotations here: https://github.com/python/typing/blob/main/docs/spec/annotations.rst#valid-type-expression-forms.

But why is blender 4.0 accepting this code as valid and it works when I run it?

**Comment by erictraut** [comment]
The values of type annotations are ignored at runtime. They are used for static type checking only, and there are rules about what expression forms are allowed within type annotations. You're using an expression form here that is expressly disallowed by the Python static type specification.

If you're not interested in using static type checking, you can simply delete the type annotation (the `:` and the expression that follows it).

If your intent is to assign a value to class-scoped variable `asdf`, then you should replace the `:` with `=`.

**Comment by hkunz** [comment]
Thank you very much for this insight! Currently the [documentation of Blender 4.0](https://docs.blender.org/api/current/bpy.props.html#operator-example) is using incorrect syntax in their examples. May I ask your opinion on that? Do they already know about this change and are they actively working to fix this or should I log a ticket for Blender to request to change the code to adhere more to this new standard? Is this now technically a bug on Blender's side or a feature change request? I'm not sure...

**Comment by MrClock8163** [comment]
@hkunz The Blender API has been using this syntax for more than 4 years now. It might be "incorrect" in the general sense for typing in Python, but in the context of the Blender API, annotations are only used for this singular purpose. Add-on codes are not otherwise annotated.
The main maintainers may or may not be aware of this inconsistency between the Blender API and the Python specs, but changing the API would break backwads compatibility with all existing add-ons, so my guess is that it'll stay for now. All we can do is suppressing this warning in VSCode.
