### ISSUE TITLE
Call expression not allowed in type expression' error with simple Pydantic models

### ISSUE THREAD

**Issue by dilippanicker** [microsoft/pylance-release#5457]
## Environment data
-   Language Server version: Pylance language server 2024.2.1 (pyright version 1.1.348, commit cfb1de0c)
-   OS and version: Ubuntu 22.04.3 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.12

## Code Snippet
```python
from pydantic import BaseModel, conint

   class TestModel(BaseModel):
       id: conint(ge=1)
   
```

## Expected behavior
No errors

## Actual behavior
Call expression not allowed in type expression' error

**Additional Notes**

* This issue surfaced after updating to the latest Pylance version.
* Downgrading to one version older, resolved the error.

**Comment by erictraut** [comment]
The behavior of pyright (the type checker upon which pylance is built) is correct here. Type annotations can contain only certain expression forms. Call expressions are expressly forbidden. 

I'm not sure what you are trying to do in the above code, but you'll need to change it if you want your code to type check without errors.

The recent change is part of an ongoing effort to eliminate ambiguities in [the official Python typing specification](https://typing.readthedocs.io/en/latest/spec/index.html) and to make pyright (and other type checkers like mypy) [conformant](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html) with this spec.

**Comment by MrClock8163** [comment]
This is really unfortunate, because it is something that users might not be able to influence. For example, the [Blender](https://www.blender.org/) Python API makes use of type annotations extensively for UI related property definitions. We must use call-like expressions in these annotations, because that's the only way to specify certain characteristics of properties. I guess we'll have to suppress this warning in these cases.

Example:
```py
easting: bpy.props.FloatProperty(
    name = "Easting",
    unit = 'LENGTH',
    default = 200000,
    soft_max = 1000000
)
```

**Comment by erictraut** [comment]
Type annotations are intended for static type checkers, and static type checkers will not understand dynamic values like this. What use case do you have in mind if it's not for static type checking? Are you using this for some sort of runtime type checking?

If your intent is to supply non-type metadata in the annotation, you could use the `Annotated` special form introduced in [PEP 593](https://peps.python.org/pep-0593/). For example:

```python
   class TestModel(BaseModel):
       id: Annotated[int, conint(ge=1)]
```

When using `Annotated`, you specify the static type annotation as the first argument and additional metadata in subsequent arguments. Call expressions are allowed for this additional metadata.

**Comment by MrClock8163** [comment]
The Blender API instantiates it's internal data types for UI related properties based on the provided type hints, and we (the add-on developers) can't really circumvent this.
I'm fairly sure that maintainers are aware of this issue, but at this point, it's probably a matter of backwards compatibility with add-ons created over the years.
Then again, I'm not arguing over it's correctness, I just wanted to provide some context for situations when this error might be unwanted, and unavoidable.

**Comment by dilippanicker** [comment]
Our project uses Pydantic models without Annotations extensively. Switched back to Pylance v2023.12.1 for now - which doesn't complain.

**Comment by dilippanicker** [comment]
In our case a # type: ignore at the class level could have helped.

**Comment by alexzhornyak** [comment]
@debonte, could you reopen issue, because we have more than 100k lines of code  in our Blender addons and it is really impossible to refactor and type everywhere comments. Or create a settings which will disable this report

**Comment by MrClock8163** [comment]
@alexzhornyak I "solved" it by adding this to my vscode settings
```json
"python.analysis.diagnosticSeverityOverrides": {
    "reportInvalidTypeForm": "none"
},
```

**Comment by debonte** [comment]
@alexzhornyak, @MrClock8163's solution is the way to disable this diagnostic globally or for a workspace. Pylance will not change its behavior here. We're a standards-based type checker, and what Blender is doing violates the typing spec.

**Comment by alexzhornyak** [comment]
I see the only solution, use your previous version and never update

![image](https://github.com/microsoft/pylance-release/assets/18611095/1f4b70d7-90a8-48ab-85c7-3e1246497dd6)

@debonte, Blender python community is now one of the most strongest. I don't ask you to change the behaviour, just extension option to disable such types of warnings. Previous Rylance versions were great. Why to changes things that worked for years!?

**Comment by erictraut** [comment]
> Why to change things that worked for years!?

This is part of an ongoing effort to improve [pyright's conformance](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html) with the Python [static type specification](https://typing.readthedocs.io/en/latest/spec/index.html) and make it more consistent with other Python static type checkers. Pyright is the type checker that pylance is built upon.

> option to disable such types of warnings

You can disable these warnings by setting the severity of `reportInvalidTypeForms` to "none". This can be done in a number of ways:
1. For your entire project using the `python.analysis.diagnosticSeverityOverrides` setting:
```json
"python.analysis.diagnosticSeverityOverrides": {
    "reportInvalidTypeForm": "none"
  }
```
2. For your entire project using the pyrightconfig.json or pyproject.toml setting. For details, refer to [this documentation](https://microsoft.github.io/pyright/#/configuration).
3. On a per-file basis by adding a comment at the top: `# pyright: reportInvalidTypeForm=false`.
4. On a per-line basis by adding a comment: `# pyright: ignore[reportInvalidTypeForm]` or `# type: ignore`.

**Comment by bennymeg** [comment]
Regarding Blender API, as @erictraut explained above, I've found this to work:
```python
class SettingsGroup(PropertyGroup):
    override: Annotated[BoolProperty, BoolProperty(
         name="Override something",
         description="...",
         default=False
    )]
```
Assuming Blender would not change their API, what would be the most appropriate solution, disable the warnings or using type annotation? 
Moreover, does this mean that i.e. the way that Blender uses BoolProperty is incorrect?

**Comment by MrClock8163** [comment]
While the traditional Blender way might not be conformant to the typing specs, in my personal opinion, it's better to follow it, and suppress the warnings (unless of course you absolutely need all functionalities of static type checking).
This solution with `Annotated` might make your code "correct", but it also makes it harder to read, and results in more text, while Blender add-on codes in general should not have type annotations (aside from the necessary `bpy.props` cases). The Blender API [Python Style Guide](https://developer.blender.org/docs/handbook/guidelines/python/#conventions-for-core-scripts) specifically outlines this for core scripts, and it's generally followed in all public add-ons.

**Comment by dilippanicker** [comment]
A suggestion:  Let the default be confirming to previous versions by # pyright: reportInvalidTypeForm=false as default and add # pyright: reportInvalidTypeForm=true to the config or per file.

**Comment by alexzhornyak** [comment]
The problem is that previously this was working from "the box". We have 3 Mac testing stations, 5 versions of Linux, 2 Window stations. Also we use for reference a lot of other 3d party repositories. And now I should everywhere disable it. So it's better to disable it by default as it was before

**Comment by b0o** [comment]
I tried @bennymeg's suggestion of using `Annotated` but it didn't seem to work inside of Blender. I was getting errors as if the property was not defined, such as `AttributeError: 'OT_my_op' object has no attribute 'my_prop'`.

My current workaround, in order to get proper type information while still being compatible with Blender, is this:

```py
def in_blender():
    # This check is somewhat arbitrary. As long as it returns true when running in Blender, it's fine
    return type(bpy.app.version) == tuple

class MYADDON_OT_MyOperator(bpy.types.Operator):
    """My Operator"""

    bl_idname = "myaddon.my_operator"
    bl_label = "My Operator"
    bl_options = {"REGISTER", "UNDO"}

    if in_blender():
        my_string_prop: bpy.props.StringProperty()  # type: ignore
        my_int_prop: bpy.props.IntProperty()  # type: ignore
    else:
        my_string_prop: str
        my_int_prop: int
```

![2024-04-23_23-18-14_region](https://github.com/microsoft/pylance-release/assets/21299126/cc3c06d7-27bd-421c-a8a4-298c2b2ad152)

**Comment by sailsweep** [comment]
it works

> I see the only solution, use your previous version and never update
> 
> ![image](https://github.com/microsoft/pylance-release/assets/18611095/1f4b70d7-90a8-48ab-85c7-3e1246497dd6)
> 
> [@debonte](https://github.com/debonte), Blender python community is now one of the most strongest. I don't ask you to change the behaviour, just extension option to disable such types of warnings. Previous Pylance versions were great. Why to change things that worked for years!?

**Comment by erictraut** [comment]
Pylance is built on pyright, a [standards-compliant type checker](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html). The Python community is diverse, and there are thousands of important libraries, tools, and sub-communities. The way we make these work together is through standardization.

If you would like to suggest changes to the Python typing standard, you're welcome to do so. The process is documented [here](https://github.com/python/typing-council#decisions). Alternatively, if you depend on a library that is not currently conformant with Python standards, you could lobby the maintainers of that library to update it so it conforms with the specifications — and therefore works with the rest of the Python ecosystem.

**Comment by the-citto** [comment]
stumbled here for the same, but with `pyright`

```python
import pydantic

    class Example(pydantic.BaseModel):
        my_int: pydantic.conint(gt=1)
```
flagging
```
Call expression not allowed in type expression Pyright (reportInvalidTypeForm)
```
`pydantic.conint` returns a type, but [they indeed discourage using it](https://github.com/pydantic/pydantic/blob/c7a3d5ca5267646cf95a3b4cb8d3b50ebec46609/pydantic/types.py#L148-L184)

**Comment by Ark-kun** [comment]
>Pylance is built on pyright, a [standards-compliant type checker](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html).

The Python feature in question is called "function annotations".
Here is the Python standard that has introduced the feature: https://peps.python.org/pep-3107/

You can find some official usage examples that are not constrained to the limited world-view expressed in this thread.

```python
def compile(source: "something compilable",
            filename: "where the compilable thing comes from",
            mode: "is this a single statement or a suite?"):
    ...
```

```
def foo(a: 'x', b: 5 + 6, c: list) -> max(2, 9):
    ...
```

In the course of discussing annotations, a number of use-cases have been raised. Some of these are presented here, grouped by what kind of information they convey. Also included are examples of existing products and packages that could make use of annotations.

Providing typing information
* Type checking ([[3]](https://peps.python.org/pep-3107/#typecheck), [[4]](https://peps.python.org/pep-3107/#maxime))
* Let IDEs show what types a function expects and returns ([[16]](https://peps.python.org/pep-3107/#idle))
* Function overloading / generic functions ([[21]](https://peps.python.org/pep-3107/#scaling))
* Foreign-language bridges ([[17]](https://peps.python.org/pep-3107/#jython), [[18]](https://peps.python.org/pep-3107/#ironpython))
* Adaptation ([[20]](https://peps.python.org/pep-3107/#adaptationpost), [[19]](https://peps.python.org/pep-3107/#pyprotocols))
* Predicate logic functions
* Database query mapping
* RPC parameter marshaling ([[22]](https://peps.python.org/pep-3107/#rpyc))
* Documentation for parameters and return values ([[23]](https://peps.python.org/pep-3107/#pydoc))

Note how "type checking" is only one of the many intended usages of annotations.

It's pretty unfortunate when the dominant IDEs reject programs written according the the official standard.

**Comment by Ark-kun** [comment]
Anyways, Pyright fails on pretty standard type annotations from Python's `typing` module.

For example this perfectly valid Python type annotation triggers the same "Call expression not allowed in type expression" error
```python
def my_func() -> typing.TypedDict("Point2D", x=int, y=int, label=str): ...
```

**Comment by AndreasBergmeier6176** [comment]
> Anyways, Pyright fails on pretty standard type annotations from Python's `typing` module.
> 
> For example this perfectly valid Python type annotation triggers the same "Call expression not allowed in type expression" error
> 
> def my_func() -> typing.TypedDict("Point2D", x=int, y=int, label=str): ...

Example at [mypy](https://mypy.readthedocs.io/en/stable/typed_dict.html) is:
```python
from typing import TypedDict

Movie = TypedDict('Movie', {'name': str, 'year': int})

movie: Movie = {'name': 'Blade Runner', 'year': 1982}
```

Question is whether an alias is mandatory for `TypedDict` usage.

**Comment by erictraut** [comment]
The Python typing spec documents [the grammar](https://typing.python.org/en/latest/spec/annotations.html) that is allowed in type expressions. This grammar intentionally does not include call expressions.

> Question is whether an alias is mandatory for `TypedDict` usage.

This is not considered a [type alias](https://typing.python.org/en/latest/spec/aliases.html). This is an [alternative (functional) syntax](https://typing.python.org/en/latest/spec/typeddict.html#typeddict-functional-syntax) for a TypedDict class definition.

**Comment by AndreasBergmeier6176** [comment]
> The Python typing spec documents [the grammar](https://typing.python.org/en/latest/spec/annotations.html) that is allowed in type expressions. This grammar intentionally does not include call expressions.
> 
> > Question is whether an alias is mandatory for `TypedDict` usage.
> 
> This is not considered a [type alias](https://typing.python.org/en/latest/spec/aliases.html). This is an [alternative (functional) syntax](https://typing.python.org/en/latest/spec/typeddict.html#typeddict-functional-syntax) for a TypedDict class definition.

With all that said are both of these `my_func` then considered legal?

```python
from typing import TypedDict

Movie = TypedDict('Movie', {'name': str, 'year': int})

def my_func() -> TypedDict('Movie', {'name': str, 'year': int})
  pass

def my_func() -> Movie
  pass
```

**Comment by tapetersen** [comment]
@AndreasBergmeier6176 To simply answer the question they are as far as I can understand both illegal under the current typing specification as calling `TypedDict` directly is not the same as subclassing it via a `class` statement and indeed only the latter declares a type in the typing sense even if the runtime behavior is indeed the same.

I don't fully agree but can see reasons to disallow it as while we in this case know the function is a type constructor and all the arguments are resolvable literals and types that doesn't have to be true for general calls.

In the case of the separately declared `Movie` type above you could also argue that since it's technically just a global module variable and not declared as final it's public api and therefore potentially mutated which is weird for the annotation.

I do sympathize though and wish there was a reasonable way to actually make the intent of the return value of a function being treatable as a static type clear with some combination of `Final` `TypeAlias` or a cast to `Type` .

For the cases we've needed it we've been forced to declare classes as well as the functions using `if TYPE_CHECKING:` blocks.

Edit: I actually realize that the functional version of `TypedDict` is treated as a class definition (I assume as a special case). That probably still doesn't make it a type expression (as a normal class declaration simply can't due to the grammar) and therefore it can't be used as a return type directly.

**Comment by AndreasBergmeier6176** [comment]
> To simply answer the question they are as far as I can understand both illegal under the current typing specification

And how come these are then directly in the Python docs (https://typing.python.org/en/latest/spec/typeddict.html#typeddict-functional-syntax)?

**Comment by tokitoki22** [comment]
> I see the only solution, use your previous version and never update
> 
> ![image](https://github.com/microsoft/pylance-release/assets/18611095/1f4b70d7-90a8-48ab-85c7-3e1246497dd6)
> 
> [@debonte](https://github.com/debonte), Blender python community is now one of the most strongest. I don't ask you to change the behaviour, just extension option to disable such types of warnings. Previous Pylance versions were great. Why to change things that worked for years!?

Actually this answer semes best solution which not prevent my working.
eventhough I add ignore setting correlty (for work-space and  user,) recent version seems ignore those setting, and keep complain about ":" or "=" . 

after all I change verison as you mentioned. (I really do not know why some one not hope to keep this setting option but change the way)
