### ISSUE TITLE
Using 'Self' gives unexpected behavior

### ISSUE THREAD

**Issue by AbelHutten** [microsoft/pylance-release#5460]
-   Language Server version: 2024.2.1
-   OS and version: Windows 10 Enterprise
-   Python version: 3.10.11

Using 'Self' gives unexpected behavior:

```
from typing_extensions import Self 

class Parent:
    def __init__(self, some_var: Self):
        self.some_var = some_var

class Child(Parent):
    def __init__(self, some_other_var: Parent):
        super().__init__(some_other_var)
```

This gives the following error:
```
Argument of type "Parent" cannot be assigned to parameter "some_var" of type "Self@Child" in function "__init__"
  Type "Parent" cannot be assigned to type "Self@Child"
```

I am able to make it work by removing the Self type hint and substituting 'Parent' instead, but I feel that that should not be necessary in this case.

**Comment by erictraut** [comment]
Pyright (the type checker that pylance is built upon) is doing the right thing here according to the Python typing spec. Your code contains a type violation, and pyright is reporting this violation.

You're passing a value of type `Parent` to a parameter that expects a value of type `Self`. You can fix this by either changing the base class to accept a value of type `Parent` or changing the child to accept a value of type `Self`.

Keep in mind that `Self` acts like a type variable with an upper bound of the current class. Your code is equivalent to the following.

```python
S = TypeVar("S", bound="Parent")

class Parent:
    def __init__(self: S, some_var: S):
        self.some_var = some_var

class Child(Parent):
    def __init__(self: S, some_other_var: Parent):
        super().__init__(some_other_var)
```

This might make it more obvious why this is a type violation.
