### ISSUE TITLE
Add `Change spelling to` code action similar to what typescript provide

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5467]
when there is unbound identifier, see whether it is potentially misspelling by checking with existing symbols.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.2.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20242101-15-February-2024-PreRelease)
