### ISSUE TITLE
Auto import wont show options that haven't already been imported in the past

### ISSUE THREAD

**Issue by basro** [microsoft/pylance-release#547]
## Environment data

-   Language Server version: Pylance language server 2020.10.3 (pyright b881f28d)
-   OS and version: Debian 10 buster (running as vscode dev container in windows 10)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9

## Expected behaviour

Auto import should offer objects and modules from the standard libraries, my own project and installed libraries.

## Actual behaviour

Auto import doesn't list anything until it has seen it imported.
After it sees it once it remembers it until I reopen the editor.

## Logs

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> pyenv root
> conda --version
> python3.7 ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-11-01 13:01:35: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://dev-container+633a5c73747566665c70726f6a656374735c636c656d656e74696e655c6c6561726e696e675c6d6574612d666f726d735c6d657461666f726d732d736572766572/home/vscode/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/vscode/.config/Code/User/settings.json')
	at _handleError (/home/vscode/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensionHostProcess.js:750:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/vscode/.vscode-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:9:168994)
	at async p.doesFileNeedToBeFixed (/home/vscode/.vscode-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:963651)
	at async /home/vscode/.vscode-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962778
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/vscode/.vscode-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962724)
	at async p.updateTestSettings (/home/vscode/.vscode-server/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:962351)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Python interpreter path: /usr/local/bin/python
Starting Pylance language server.
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> conda --version
```

## Code Snippet / Additional information

![pylance-bug gif](https://user-images.githubusercontent.com/1387293/97803249-a0158800-1c27-11eb-9d16-25f023e53884.gif)

**Comment by jakebailey** [comment]
At the moment, this is expected, but this was previously fixed by the indexer. The indexer was temporarily disabled while we optimized its performance but is likey to come back on by default in a future release.

Can you set `"python.analysis.indexing": true` and see if this fixes things for you? We'd like early feedback to ensure it works as expected and doesn't impact performance too much.

**Comment by basro** [comment]
Indeed auto import seems to work as I'd expect with this setting set to true. 
Can't say anything about it's performance yet, I guess I'll open an issue about it if I were to encounter a problem.

Thanks!

**Comment by basro** [comment]
After a bit more use I noticed that with `"python.analysis.indexing": true` the modules from my project and the standard library will appear in auto import suggestions, but external libraries like django will not.

Is there a way to make it also index installed libraries?

**Comment by jakebailey** [comment]
The intent is that it indexes installed libraries, though for perf reasons it elides some things. @heejaechang may be able to comment.

The perf would only be bad at startup while the indexer is running; should be only a few seconds (but it's hard to make claims about everyone's machines and environments).

**Comment by heejaechang** [comment]
@basro can you be more specific on what symbols from django isn't showing up? for third party libraries, we restricted indexing to only first level modules for now. knowing exactly what symbols you were looking for, it will help us to improve indexing.

thank you

**Comment by basro** [comment]
From what I can see, first level module symbols are being offered for autocomplete as you say but only for the stubs that come included with pylance. For example, django.VERSION is shown, but rest_framework.VERSION is not.

What I'd like is for all symbols from django and rest_framework submodules to be indexed.

Perhaps a setting for which libraries should be fully indexed could alliviate the performance problems. something like: "python.analysis.indexedLibraries": ["django", "rest_framework"]

**Comment by heejaechang** [comment]
@savannahostrowski @judej your opinion on adding options for users to specify libraries they want to fully index?

**Comment by heejaechang** [comment]
@basro rest_framework is not showing up because they don't export any symbols through __ all __ (heuristic we use to not index every symbols in the package). we will see what we can improve this as well.

**Comment by alex-dudnyk** [comment]
Hi @heejaechang. Is there exists some setting to change max index level? It would be very useful.

**Comment by erictraut** [comment]
There is no setting currently. I'd be reluctant to add such a setting because the tradeoffs involved in increasing the max index level would be difficult to understand for anyone not intimately familiar with the internals of pylance/pyright.

For properly-typed libraries (those that include a "py.typed" marker and provide types in the form of inlined annotations or packaged stubs), the indexer is able to do a much better job — and do it much more efficiently. A heuristic-based "max index level" no longer applies in this case. We are encouraging library maintainers to properly type their libraries because this will significantly improve the Python coding experience for everyone. If you are the consumer of a library that is not properly typed, I encourage you to provide feedback to the maintainers of that library. Your feedback will help in the prioritization of these improvements.

**Comment by levrik** [comment]
@erictraut Does `"python.analysis.indexing": true` still exist? I've tried setting it but I still don't get auto import suggestions from my local project.

**Comment by jakebailey** [comment]
@levrik See #1055 and our most recent changelog. Feedback is appreciated there.

**Comment by levrik** [comment]
@jakebailey Thanks a lot for pointing me to that issue. I'll subscribe to it.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
