### ISSUE TITLE
Custom Types not been recognize when imported from a module

### ISSUE THREAD

**Issue by DVillegasA** [microsoft/pylance-release#5471]
## Environment data

-   Language Server version: v2024.2.1
-   OS and version: Windows 10 x64
-   Python version: 3.11.7

## Code Snippet

```python
from motor.motor_asyncio import AsyncIOMotorDatabase, AsyncIOMotorCollection

class Manager:
    def __init__(self, db: AsyncIOMotorDatabase):
        self.daily_collection: AsyncIOMotorCollection = db.get_collection(f"operations")
```

## Repro Steps

1. For this particular example we need to install pymongo 4.6.1 and motor 3.3.2

## Expected behavior

After importing the specific types from the module `motor.motor_asyncio` and using it to annotate a particular variable (in this case `db`) we expect to get the corresponding autocompletion and suggestions for the methods inside of that type, which was the case until version v2023.12.1

![imagen](https://github.com/microsoft/pylance-release/assets/10423930/186ca374-53e6-4244-a5cd-bda9031e0279)

## Actual behavior

What's happening now is that the types are not been recognize as such, and are been treated as variables, which in turn throws a warning of type _reportInvalidTypeForm_ when trying to use them to annotate a variable:

![imagen](https://github.com/microsoft/pylance-release/assets/10423930/ef869661-dafd-4cec-b826-1360d6f096bf)

But what's odd is that, if instead of importing just the types, we import the entire module and use the types from there to annotate the variable, we can get back the expected behaviour:

![imagen](https://github.com/microsoft/pylance-release/assets/10423930/7691be17-90b8-40de-baae-e13d6c68d416)

## Logs

[not_working.txt](https://github.com/microsoft/pylance-release/files/14281317/not_working.txt)

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working correctly here. The `motor` library defines the symbol `AsyncIOMotorDatabase` as follows:

```python
AsyncIOMotorDatabase = create_asyncio_class(core.AgnosticDatabase)
```

In other words, it's dynamically allocating a class and assigning it to a variable named `AsyncIOMotorDatabase`. Variables like this cannot be used in type annotations according to the Python typing spec, so pyright is correct to flag this as an error.

It looks like the library is dynamically constructing these class types from other class types, so you could use the original base classes for type annotations in this case.

```python
from motor.core import AgnosticCollection, AgnosticDatabase

class Manager:
    def __init__(self, db: AgnosticDatabase):
        self.daily_collection: AgnosticCollection = db.get_collection(f"operations")
```
