### ISSUE TITLE
AsyncItemPaged[PathProperties] does not show correctly

### ISSUE THREAD

**Issue by hermanho** [microsoft/pylance-release#5477]
## Environment data

-   Language Server version: 2024.2.101 (pyright version 1.1.350, commit e9f1cc51)
-   OS and version: Win11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.8

## Code Snippet

Ref:
https://github.com/Azure/azure-sdk-for-python/blob/e3c6bf9facaa79dbaaed95faab6644e90cd7fcaa/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py#L488

```Python
from azure.storage.filedatalake.aio import DataLakeServiceClient

service_client = DataLakeServiceClient(
    account_url="xxx",
    credential="xxx",
)
file_system_client = service_client.get_file_system_client(
    file_system="xxx"
)
paths = file_system_client.get_paths(path="xxxx")
async for path in paths:
    name = path.name

```

## Repro Steps

1. pip install azure-storage-file-datalake
2. Use above code snippet
3. Mouseover on get_paths

![mstsc_1708100388_7Z2V4RdQu6](https://github.com/microsoft/pylance-release/assets/2337380/7f7ab85b-bb82-4679-a479-a483d354523e)

## Expected behavior

The result type of get_paths should be AsyncItemPaged[PathProperties] .

## Actual behavior

The result type of get_paths is AsyncItemPaged and the type of variable 'path' in next line is interpreted as Any.

**Comment by debonte** [comment]
I believe this is a bug in the [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python).

At the point where [the `AsyncItemPaged` object is returned](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py#L538) from `get_paths`, no type argument is provided and it can't be inferred.

This is the same behavior that you will see if you create a `list` without specifying a type argument:

```python
x = list()
reveal_type(x) # Type of "x" is "list[Unknown]"
```

`get_paths` should be returning `AsyncItemPaged[PathProperties]` instead. I'd recommend [filing an issue on them](https://github.com/Azure/azure-sdk-for-python/issues).
