### ISSUE TITLE
`searchImport` fails with circular reference some times.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5481]
new `searchImport` (under experiement) is failing sometime for symbols from opened user files.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.2.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20242102-20-February-2024-PreRelease)
