### ISSUE TITLE
Bug with module showing not resolved but works fine

### ISSUE THREAD

**Issue by heriga** [microsoft/pylance-release#5482]
## Environment data

-   Language Server version: XXX
-   OS and version: MAC os 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11 ANACONDAa

## Code Snippet

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

I get 2 problems in the problems tab in vscode, saying that Import "tensorflow.keras.models" could not be resolved. Same for tensorflow.keras.layers
The modules are being imported and work when i run the code, the vscode is the same env as my terminal env 
To not show any error, currently getting 'Import "tensorflow.keras.modles/layers" could not be resolved

XXX

## Actual behavior

Shows an error in problems  part in vscode even though i can run the code and use the imported modules perfectly fine
XXX

## Logs

```
XXX
```

**Comment by heriga** [comment]
yes the correct virtual env is used

**Comment by debonte** [comment]
This is a duplicate of https://github.com/microsoft/pylance-release/issues/3753. `tensorflow` dynamically loads (and re-exports) `keras`, so static type analyzers cannot resolve this import. You could use the following instead if you want to eliminate this error:

```python
from keras.models import Sequential
from keras.layers import LSTM, Dense
```

**Comment by heriga** [comment]
thank you sir it works now

**Comment by mczhao1977** [comment]
still not work for me
Keras 3.3.3 + TF 2.16.1
![image](https://github.com/microsoft/pylance-release/assets/20310300/ce476f2f-1aa1-4d7f-a7a2-e926710f0e37)

**Comment by rchiodo** [comment]
@mczhao1977, I'd recommend opening a new issue. The log as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue 

should tell us exactly where we searched for keras.models and keras.layers.

**Comment by mczhao1977** [comment]
Hi rchiodo, my problem is very similar to this issue.  I don't know Pylance's exact search directory for keras.models and keras.layers. But keras can be correctly parsed and the path is : ~/miniconda3/lib/python3.11/site-packages/keras/__init__.py
In this file: 
# Import everything from /api/ into keras.
from keras.api import *  # noqa: F403
from keras.api import __version__  # Import * ignores names start with "_".

Should I use "from keras.api.layers import LSTM, Dense" instead "from keras.layers import LSTM, Dense"?  
Thanks

**Comment by rchiodo** [comment]
@mczhao1977 you're right. It looks like the same problem as tensorflow. Keras recently changed their `__init__.py` to do a * import and that seems to make us unable to find it. Seems like a bug on our part though.

**Comment by rchiodo** [comment]
I opened a new issue:
https://github.com/microsoft/pylance-release/issues/5940

**Comment by eddieiyamah** [comment]
For anyone still having issues with importing the dependencies, especially if you're using vscode, "tensorflow.python.keras..." seems to work. I'm still not sure why. All with new versions of the libraries of course.

**Comment by whatfor2000** [comment]
This work for me
`from keras import Sequential`
