### ISSUE TITLE
Import suggestions ignores imports made on package level

### ISSUE THREAD

**Issue by anderssonjohan** [microsoft/pylance-release#5485]
Import suggestions never lists package level declarations, only module level.

Problem: I want users of my package to import symbols from package level and not module level. VSCode suggests importing symbols from `package.module` instead of `package`. 

## Environment data

-   Language Server version: 2024.2.2 (pyright version 1.1.348, commit cfb1de0c)
-   OS and version: macOS 12.7.3
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.1

FWIW, I'm NOT using the exact match setting when testing this:

```json
  "python.analysis.addImport.exactMatchOnly": true
```

## Code Snippet

The following code is not being shown in the list of import suggestions:

`pylance_imports_test/__init__.py`
```python
from pylance_imports_test.my_module import MyClass
```

Module defined as:

`pylance_imports_test/my_module.py`
```python
class MyClass:
    pass
```

## Repro Steps

1. Define a class in a module that is defined on the package level using a `from module import ...` import
2. Write some code using the exported class
3. Engage the import suggester
4. VSCode does not include the package level export as a suggestion

## Expected behavior

![Screenshot 2024-02-19 at 12 40 10](https://github.com/microsoft/pylance-release/assets/435885/6f7c3ccf-0910-4d33-a73e-e3897c87fa92)

Note: This behavior was produced by modifying the `__init__.py` from using a `from .... import ....` to use variables:

```python
import pylance_imports_test.my_module

MyClass = pylance_imports_test.my_module.MyClass
```

## Actual behavior

![Screenshot 2024-02-19 at 12 36 46](https://github.com/microsoft/pylance-release/assets/435885/1956b7c3-96a1-41db-9840-de001e7bfd33)

## Logs

The logs prints `[found 0]`, unless the workaround of declaring an explicit variable is used. Then it prints `[found 1]`:

```
2024-02-19 12:48:54.288 [info] [Info  - 12:48:54] (15502) SourceFile: Received fs event 'change' for path 'pylance_imports_test/__init__.py'
2024-02-19 12:48:54.312 [info] (15502) [BG(1)] indexing: file:///pylance_imports_test/__init__.py [found 1] (0ms)
2024-02-19 12:48:54.313 [info] (15502) Indexing Done: file:///pylance_imports_test/__init__.py
```

**Comment by heejaechang** [comment]
that's behavior for user files, when it is installed as third party packages (installed in site-packages), you will get the behavior you want.

**Comment by anderssonjohan** [comment]
> that's behavior for user files, when it is installed as third party packages (installed in site-packages), you will get the behavior you want.

@heejaechang Ok, thanks for the quick reply and explanation. For things in the venvs site-packages I never get any suggestions (only the message "No code actions available")

**Comment by heejaechang** [comment]
That's because, by default, pylance will try not to spend too much time on indexing. Indexing full packages installed is expensive, and not everyone wants or uses those expensive features. In other words, they don't want to spend 10 minutes waiting for VSCode to finish indexing their workspace/repo.

So, we have this option python.analysis.packageIndexDepths that allows users to let us spend 10 minutes to index. For example, if you add this:

```
{
  "name": "lime_webhooks",
  "depth": 5,
  "includeAllSymbols": true
}
```

I believe you will get what you want. For more detail on the option, see the description.

**Comment by heejaechang** [comment]
we also have this issue - https://github.com/microsoft/pylance-release/issues/5434 - to address root issue (providing mode (`full`) that are allowed to consume a lot of resources to provide better user experiences)
