### ISSUE TITLE
Intellisense not updating for workspace with multiple folders

### ISSUE THREAD

**Issue by peterchenadded** [microsoft/pylance-release#5486]
## Environment data

-   Language Server version: v2024.2.2
-   OS and version: MacOS 14.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9

## Code Snippet

```python
from app.one.one import AppOneTest
from app.two.two import AppTwoTest
```

## Repro Steps

1. Open app_one.code-workspace in vscode (a workspace with two folders)
2. Open the test.py file
3. Hover over the class to get the below docstring messages
```
from app.one.one import AppOneTest # Should show "AppOneTest."
from app.two.two import AppTwoTest # Should show "AppTwoTest."
```
4. Go to AppOneTest file (in app/one/one.py file) and update the docstring to something else
5. Go to AppTwoTest file (in app/two/two.py file) and update the docstring to something else
6. Go back to the test.py file
7. Hover over the class to get the docstring

## Expected behavior

Docstring for both to be updated.

## Actual behavior

Docstring not updated for app.two.two.AppTwoTest, but updated for app.one.one.AppOneTest

## Logs

Did not see any errors.

## Reproducer link with all the source code and workspace file.

See https://github.com/peterchenadded/pylance_issue/tree/main

**Comment by peterchenadded** [comment]
Note after some trial and error, was able to find a work around by using below:

```
#pyproject.toml
...
[tool.pyright]
include = [ "app", "../app_two/app" ]
```

and in app_one.code-workspace

```
# app_one.code-workspace
...
"settings": {
            "python.analysis.extraPaths": [
                  "../app_one", "../app_two" ]
        }
```

This seems to make the intellisense work when updating both files.

**Comment by judej** [comment]
Thanks for the update. Will close the issue, feel free to repoen if needed
