### ISSUE TITLE
Explorer OUTLINE view will look messy if are too many imports in file(seen on python)

### ISSUE THREAD

**Issue by florinCer** [microsoft/pylance-release#5490]
OUTLINE imports in Explorer tab, if are too many, will look messy. Will be a lot of scrolling if you want to reach to functions.
Pls group them behind a "Imports" or "\__imports\__" (for python specific) label entry category for easy grouping.

VS Code version: Code 1.86.2 (https://github.com/microsoft/vscode/commit/903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045

Example:

![feature_req_vscode__](https://github.com/microsoft/vscode-python/assets/22615419/88508ac5-67b3-4f15-ad7e-5d81e917f3d4)

Group behind Imports(or other name....) all Outline imports seen in Explorer Outline.

**Comment by florinCer** [comment]
I use Jedi. You have right on pylance imports not appear.

Yahoo Mail: Căutare, organizare, reușită 
 
  Pe vin., mar. 8, 2024 la 0:01, Erik De ***@***.***> a scris:   


I don't see imports in the Outline when using Pylance. Are you perhaps using Jedi instead? Check the python.languageServer setting.

This is what I see with Pylance:
image.png (view on web)

And this is what I see with Jedi:
image.png (view on web)

**Comment by debonte** [comment]
> I use Jedi. You have right on pylance imports not appear.

Ok. Please file an issue on Jedi at https://github.com/davidhalter/jedi/issues.
