### ISSUE TITLE
The beginning of the Pylance log file is deleted

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/pylance-release#5494]
I have the log level set to "Trace" to try to figure out some problems and the beginning of the Pylance log file is getting removed.  It seems like this may be some sort of "feature" to prevent the log file from getting too big and perhaps it is.  If this is a "feature", I would have expected to see a fairly obvious way to disable this in the GUI and I would have expected a Google search to quickly yield good results on how to turn it off.

As things are, Pylance doesn't even fully make it through initialization before the log is deleted.  In order to get the beginning portion of the log, it seems I need to close vscode at just the right time as it is loading.

**Comment by rchiodo** [comment]
That setting is actually in VS code. Pylance has no control over it. I believe it's here:

![image](https://github.com/microsoft/pylance-release/assets/19672699/f4b7467f-7ebc-4d01-ae71-76458dc95764)

**Comment by daltairwalter** [comment]
Perhaps this is a vscode setting, but it doesn't seem to be the one you are indicating.  After the beginning group of lines was deleted, my log had 10008 lines left in one case and  14337 lines left in another, so it doesn't seem to be line count related either.

At any rate, if it is an "option", it is not nearly adequately discoverable for something that does this much damage.

**Comment by rchiodo** [comment]
There is another problem, VS code seems to rehydrate the log with the last run's output. I haven't been very successful in getting it to not do that. 

I believe it's called persisted terminal sessions:

![image](https://github.com/microsoft/pylance-release/assets/19672699/e0b567b4-4811-4234-826a-066216e60b67)

You can tell if there's multiples in the output if you get this line more than once:

```
2024-02-21 10:18:28.131 [info] [Info  - 10:18:28 AM] (12192) Pylance language server 2024.2.102 (pyright version 1.1.351, commit 87171fbf) starting
```

**Comment by daltairwalter** [comment]
I only see "Pylance language server" in the log once if I close vscode soon after the language server starts - otherwise this part of the log is deleted and I don't see it at all.

**Comment by rchiodo** [comment]
Did you try setting the integrated scrollback level really high? Like 20000 or something? It doesn't seem to have any effect for me either, but that's what the help says it's supposed to do:
https://code.visualstudio.com/docs/terminal/basics#_navigating-the-buffer
