### ISSUE TITLE
Allow for setting `deprecateTypingAliases` configuration

### ISSUE THREAD

**Issue by nimashoghi** [microsoft/pylance-release#5499]
Pyright has a configuration option for deprecating aliases being imported from the `typing` module (e.g., `typing.Callable` -> `collections.abc.Callable`). However, setting the value for this setting in `python.analysis.diagnosticSeverityOverrides` doesn't do anything. It would be great if we could use this config in Pylance.

**Comment by erictraut** [comment]
`diagnosticSeverityOverrides` applies only to diagnostic rules, not to other configuration options. The `deprecateTypingAliases` configuration option is not a diagnostic rule. It allows only "true" or "false" values.

**Comment by nimashoghi** [comment]
> `diagnosticSeverityOverrides` applies only to diagnostic rules, not to other configuration options. The `deprecateTypingAliases` configuration option is not a diagnostic rule.

This makes sense. My confusion stemmed from the fact that `deprecateTypingAlias` [is listed under diagnostic rules in the Pyright docs](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults).

> It allows only "true" or "false" values.

For what it's worth, before posting this request, I had tried all different combinations of values for this configuration under `python.analysis.diagnosticSeverityOverrides`, including `"true"`/`"false"`/`true`/`false`/`"error"`/... Nothing works.

If `python.analysis.diagnosticSeverityOverrides` isn't the right configuration, then what configuration should I use to enable this diagnostic rule?

**Comment by erictraut** [comment]
> My confusion stemmed from the fact that deprecateTypingAlias [is listed under diagnostic rules in the Pyright docs](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults).

That's a good point. I will make a note of this and try to make it clearer.

> what configuration should I use to enable this diagnostic rule?

Pylance doesn't currently expose those configuration settings through the LSP interface. You'd need to set it in a pyrightconfig.json or pyproject.toml config file.

**Comment by nimashoghi** [comment]
> You'd need to set it in a pyrightconfig.json or pyproject.toml config file.

I wasn't aware of this configuration. This addresses my problem. Thank you very much!
