### ISSUE TITLE
Support imports that are not used directly. For example hvPlot

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#55]
#### My Pain

I am a user of [hvPlot](https://hvplot.holoviz.org/). It can add a `. hvplot` method with the same api as the pandas `.plot` to a wide arrray of datatypes like pandas dataframes, Rapids cuDF, Dask, XArray, Streamz, .... You get a [Holoviews}(http://holoviews.org/) object back which can be rendered to an interactive bokeh plot.

An example use case in VS Code is shown below

![image](https://user-images.githubusercontent.com/42288570/86524677-d3b0f300-be7d-11ea-84bd-8a7d500ad3e6.png)

The problem here is that Pylance reports that `hvplot.pandas is not accessed`. It might be True that it is not accessed. But it is used and a false indication that something is wrong.

#### Solution

Fix this :-)

Thanks for a great tool.

**Comment by erictraut** [comment]
This behavior is as intended.

Pylance is correctly reporting that this import is not accessed. This can be an indication of a bug, so it makes sense to report it as a warning. There's no way for Pylance to know that an import has side effects that you are relying upon, so there's no way to "fix" this.

If this warning bothers you, you can silence it through one of the following methods:
1. Add the following comment at the top of your source file: `# pyright: reportUnusedImport=false`.
2. Add the following comment to the end of that line: `# type: ignore`
