### ISSUE TITLE
No Import Suggestion for 'djangorestframework'

### ISSUE THREAD

**Issue by msenol86** [microsoft/pylance-release#5502]
Last updates broke the import suggestion feature. PyLance does not suggest SAFE_METHODS import even the rest_framework package is in virtual env and detected by PyLance.

![Screenshot 2024-02-22 at 10 38 18](https://github.com/microsoft/pylance-release/assets/2547551/cd93c02d-f410-4829-8ad5-9eb21467c468)
![Screenshot 2024-02-22 at 10 50 25](https://github.com/microsoft/pylance-release/assets/2547551/e07b33fe-9094-480c-b326-9ef280e2a0c6)

**Comment by debonte** [comment]
To clarify, I believe @msenol86 is saying that `SAFE_METHODS` (and maybe all `rest_framework` symbols?) are not provided as auto-import suggestions. This is what I see after `pip install djangorestframework` which gave me v3.14.0.

![image](https://github.com/microsoft/pylance-release/assets/12820898/d4bcf611-feb4-4342-ad44-a3b523eb9827)

**Comment by rchiodo** [comment]
Could it be a package index depth problem?

**Comment by rchiodo** [comment]
No I can repro even with packageIndexDepth set to 99:

```jsonc
    "python.analysis.packageIndexDepths": [
        {
            "name": "rest_framework",
            "depth": 99
        }
    ]
```
![image](https://github.com/microsoft/pylance-release/assets/19672699/177fa126-0f33-4119-8301-3054aa2ff93f)

**Comment by rchiodo** [comment]
I'm not getting any auto imports for anything in the rest_framework.

**Comment by rchiodo** [comment]
I don't believe this is a regression though. I went all the way back to 2023.9.30 and I still get the same results.

**Comment by rchiodo** [comment]
Ah it is related to indexing. SAFE_METHODS is not exported from the `__all__` for the `__init__.py` so we don't index it by default. You have to do something like this to get it work:

```jsonc
    "python.analysis.packageIndexDepths": [
        {
            "name": "django",
            "depth": 99
        },
        {
            "name": "flask",
            "depth": 2
        },
        {
            "name": "fastapi",
            "depth": 2
        },
        {
            "name": "rest_framework",
            "depth": 99,
            "includeAllSymbols": true
        }
```

![image](https://github.com/microsoft/pylance-release/assets/19672699/cdd6d4e4-1e66-44dd-91a1-2393ffaaf2ee)

Thanks to @HeejaeChang for pointing that out.

**Comment by rchiodo** [comment]
I think this sort of thing could be handled if we get this issue correct:
https://github.com/microsoft/pylance-release/issues/5434

**Comment by rchiodo** [comment]
Although you could argue the rest framework could be exporting their public api from their `__all__` export in the `__init__.pyi` but that's not a requirement for packages. 

Maybe we could flag this situation somehow? The public API of so and so has limited information?
