### ISSUE TITLE
Dont show `convert to relative path` for files in local `typings` or `stubs` path.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5505]
repro steps.

1. open a folder `test`
2. create a folder called `typings` inside of `test`, 
3. create a file in `typings`, `lib.pyi`
4. in `lib.pyi` create class `class MyType: ...`
5. create a `test.py` in the `test` folder
6. write `from lib import MyType`
7. set cursor on `lib`

Expected:
no code action to convert `lib` to `relative path`

Actual:
it offers `convert to relative path`, but if selected, nothing happen since we treat any modules under local `typings` or `stubs` as third party libraries not `user files` for `relative path` purpose.

**Comment by heejaechang** [comment]
related to https://github.com/microsoft/pylance-release/issues/5427

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.3.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/2024.3.100/CHANGELOG.md#20243100-13-march-2024-prerelease)
