### ISSUE TITLE
Pylance code completion is not effective for third-party libraries with poetry 

### ISSUE THREAD

**Issue by LQMaximus** [microsoft/pylance-release#5507]
Hi!

I use Poetry and put my virtualenv locally within the project directory.Pylance code completion is not effective for third-party libraries. 

I have already set following code
`"python.autoComplete.extraPaths":["D:\\BaiduSyncdisk\\Codefield\\dataScience_py\\.venv\\Lib\\site-packages", "D:\\Software\\Python\\3_10_8\\Lib"]`

`"python.analysis.extraPaths":["D:\\BaiduSyncdisk\\Codefield\\dataScience_py\\.venv\\Lib\\site-packages","D:\\Software\\Python\\3_10_8\\Lib"]`
```[tasklist]
### Tasks
```

**Comment by heejaechang** [comment]
Hi. Thank you for reporting the issue. have you followed the quick start steps shown in python extension readme?

https://marketplace.visualstudio.com/items?itemName=ms-python.python

especially, `Set up your environment` part?

if you did and still having problem, can you provide us some repro steps so we can take a look?

or at least some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

currently, there is not much actionable data for us to dig in to find out what happened.

**Comment by heejaechang** [comment]
closing since there is no response
