### ISSUE TITLE
VS Code freeze, 200% processor usage

### ISSUE THREAD

**Issue by ClementWalter** [microsoft/pylance-release#5509]
Type: <b>Bug</b>

it seems like it appears when using the jupyter extension and/or the debug terminal

Extension version: 2024.2.2
VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:17:50.719Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 7, 30|
|Memory (System)|64.00GB (31.84GB free)|
|Process Argv|. --crash-reporter-id 8fb28320-a685-4761-a70f-8fd3d2132a10|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
d34g3935:30971562
7j2b6412:30969109
e3gdj431:30958358

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue but we'll need more information to determine what the problem might be. 

What process is consuming the CPU?

And what were you doing when VS code froze? We don't have any code running in VS code, but it might be possible we returned so much data for some call that it froze VS code.

**Comment by rchiodo** [comment]
The log as talked about here would also help diagnose what the problem might be:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by rchiodo** [comment]
Closing issue with no response. If you can respond with the asked for information, please reopen this issue.

Thanks.
