### ISSUE TITLE
Can I remove the intext underline warnings and rather have a redline or a lamp in the line where errors are?

### ISSUE THREAD

**Issue by Vakke** [microsoft/pylance-release#552]
As the title says!

Can I somehow remove the intext warnings: especially the red underline and rather have red lines on the edge of editor to provide me information that I have error in the code in this line or lamp etc like PyCharm does have?

**Comment by judej** [comment]
@Vakke, thanks for the question. 

The enhancement you are asking for is a change in the behavior of VS-Code. So, that will be the right place to request that. Second, there could be multiple warnings or errors in a line and by showing the diagnostics inline, we are able to highlight the exact error - something we couldn't do if the code action is in the margin.

Thanks again!
