### ISSUE TITLE
`object*` appearing after `in` assertions in generic `dataclass`

### ISSUE THREAD

**Issue by barbagus** [microsoft/pylance-release#5559]
I am not familiar with the `object*` type indication that appears after a every `assert foo in bar` in the following code after refactoring this class to be generic.

```python
@dataclass
class _Decider[T]:
    choices: list[T]
    options: dict[T, bool] = {}

    def decide(self):
        decision: T | None = None

        for choice in self.choices:
            assert choice in self.options
            # `choice` is now `T@_Decider | object*`
            if self.options[choice]:
                assert decision is None
                decision = choice

        # `choice` is now `T@_Decider | object* | None`
        return decision

    def reject(self, option: T):
        assert option not in self.options or not self.options[option]
        # `option` is now `T@_Decider | object*`
        self.options[option] = False

    def consider(self, option: T):
        assert option not in self.options or self.options[option]
        # `option` is now `T@_Decider | object*`
        self.options[option] = True

        for choice in self.choices:
            if choice != option:
                assert choice not in self.options or not self.options[choice]
                # `choice` is now `T@_Decider | object*`
                self.options[choice] = False
    ...
```

Obviously this messes up my methods signatures and returned value typing.

Question is: am I doing something wrong ? what am I doing wrong ?

Note: I'll `cast()` for now... but I don't like it

## VScode info
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

## Python extension
v2024.2.1

## Pylance extension
v2024.2.2

## Python
3.12.0

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working correctly here, so this isn't a bug. You can read about with the "*" means after a type by going to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=conditional-types-and-type-variables).

If you have any follow-on questions, feel free to start a thread in the pyright [discussions forum](https://github.com/microsoft/pyright/discussions).
