### ISSUE TITLE
Regression in 2023.10.41 quick-fix pyright-specific comments

### ISSUE THREAD

**Issue by garthk** [microsoft/pylance-release#5565]
microsoft/pylance-release#4494 is not as fixed as its status would suggest. Perhaps it lacks test coverage and regressed between then and 2024.2.105, but I suspect it didn't work (well) then either and wasn't picked back up despite a timely warning from the original reporter <https://github.com/microsoft/pylance-release/issues/4494#issuecomment-1773361908>.

The fix was announced in [2023.10.41 (20 October 2023) PreRelease](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20231041-19-October-2023-PreRelease):

> Notable changes:
> 
> - Bug fix: microsoft/pylance-release#4494

Yeah, nah, I'm afraid not. See this fresh profile fail to use the feature (3 frames, 5s each):

![animation](https://github.com/microsoft/pylance-release/assets/15906/6650a92d-74f2-45fc-98f2-dafa23ad3c95)

## Environment data

- Python extension  `v2024.3.10611008 (pre-release)`
- Pylance extension `v2024.2.105 (pre-release)`
- Pylance language server: `2024.2.105 (pyright version 1.1.351, commit 87171fbf)`
-  OS and version: macOS `14.3.1 (23D60)`
-  Python version: `3.11.8`
-  … and distribution if applicable: `brew install python3`

## Code Snippet

```python
class Assignment:
	content_object: Any | None

	def get_absolute_url(self) -> str:
		"""Get the canonical URL for this assignment."""
		model: Model = self.content_object
		return resolve_url(to=model)


class Model:
	def get_absolute_url(self) -> str:
		return 'https://github.com/microsoft/pylance-release/issues/4494'


def resolve_url(to: Model) -> str:
	return ''
```

## Repro Steps

- Move cursor into `self.content_object`
- Use `editor.action.showHover` (`⌘K` `⌘I` by default on macOS)
- Use `editor.action.quickFix` (`⌘.`)
- Observe you didn't get an error-specific suppression
- Observe you didn't get a Pyright-specific suppression

For more detail and an importable profile so you know our settings match, clone [garthk/0847190…](https://gist.github.com/garthk/0847190b3d10d5d443a890b722fac0a1) (gist).

## Expected behavior

I expect this quick fix to be offered, and a matching comment added:

> Add '# pyright: ignore[reportAssignmentType]' to suppress warning

## Actual behavior

> Add '# type: ignore' to suppress warning

## Logs

See [python-analysis.log](https://gist.github.com/garthk/0847190b3d10d5d443a890b722fac0a1#file-python-analysis-log) in the gist.

**Comment by debonte** [comment]
If you add the following to your `pyproject.toml`, you will see the `# pyright: ignore[foo]` code action. We currently show either `# type: ignore` or `# pyright: ignore` depending on the value of the `enableTypeIgnoreComments` setting.

```toml
[tool.pyright]
enableTypeIgnoreComments = false
```

However, there is a problem. When `reportGeneralTypeIssues` got split into multiple smaller diagostic rules, this code action wasn't updated to use the rule name, so the comment is always `# pyright: ignore[reportGeneralTypeIssues]` which is obviously problematic.

I'll work on a fix for that.
