### ISSUE TITLE
Auto-completion doesn't offer `def __post_init__()` for data classes

### ISSUE THREAD

**Issue by valorien** [microsoft/pylance-release#5568]
`__post_init__()` is a dunder method available in data classes.
While trying to implement it, I've noticed that the code-completion feature is unaware of it.

<h3> Code Snippet </h3>

```python
from dataclasses import dataclass


@dataclass
class MyClass:

    def __p...  # <- Code-completion offers the __repr__ method instead of __post_init__
```

<h3> Environment data </h3>

-   Language Server version: 2024.2.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

**Comment by erictraut** [comment]
Auto-completion works only for method overrides. The parent class in this case doesn't implement a `__post_init__` method, so there will be no auto-completion for this method.

**Comment by valorien** [comment]
I understand, but I think that's actually something that should be addressed, considering it's working flawlessly in PyCharm:

![image](https://github.com/microsoft/pylance-release/assets/3483790/b92c87c0-21c1-4b70-9057-9902e985a944)

Thanks again and have a great day.
