### ISSUE TITLE
why one function is cite,but can't not find the define of the function?

### ISSUE THREAD

**Issue by CCCxzb** [microsoft/pylance-release#5571]
As the title,I can fine the define of matplotlib which is in the path site-packages.But when I try to go to the define of PyQT5, it is failed.But the PyQT5 is work and I can find the file and directory in the path site-packages.

**Comment by rchiodo** [comment]
Can you include the log as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

It should list out what paths we used to search for PyQT5.

You might also follow the steps outlined here to see if they solve your problem:
https://code.visualstudio.com/docs/python/editing#_importresolvefailure
