### ISSUE TITLE
Unstable and breaks with updates

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5577]
> Mücahit Şenol
> 2/22/2024
> very unstable. every update breaks something. compare to js/ts support, python support is a joke

Sorry you having issue with Pylance, Would like to resolve this issue.
Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md?rgh-link-date=2024-03-04T21%3A41%3A09Z#filing-an-issue)?

**Comment by bschnurr** [comment]
Please provide a code sample or repo steps to the issue you are seeing
