### ISSUE TITLE
Update breaks Pylance

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5579]
> Li-chih Wu
> 2/27/2024
> Updated enough times and always broken.
> Now staying at v2023.12.1

Li-chih,
Sorry you having issue with Pylance, Would like to resolve this issue.
Would you please add the information in the report as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md?rgh-link-date=2024-03-04T21%3A41%3A09Z#filing-an-issue)?

**Comment by cklim2024** [comment]
[PostAnalytics_光林_7176186288868360192.xlsx](https://github.com/microsoft/pylance-release/files/14670849/PostAnalytics_._7176186288868360192.xlsx)
