### ISSUE TITLE
Provide profiling command to generate `cpuprofile` (chrome perf profile file) for all worker threads

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5590]
Recently, Pylance has been receiving user feedback regarding performance. However, performance is one of the areas where regular logging is usually insufficient. It often requires a live reproduction to identify the issues, which is frequently difficult to obtain for various reasons.

Users could use VSCode (Chromium)'s built-in profiler through the `DevTools Performance` tab to provide us with the profiler data instead of a live reproduction. However, it is usually challenging to explain to users how to obtain this data for us since it involves multiple steps.

Therefore, it would be beneficial to provide commands that automatically generate these profile data for users and save them in a location where users can easily provide us with the profiling data.

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.3.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/2024.3.100/CHANGELOG.md#20243100-13-march-2024-prerelease)
