### ISSUE TITLE
Require Regret Matching in Code-Auto-Complete

### ISSUE THREAD

**Issue by HsunGong** [microsoft/pylance-release#56]
![image](https://user-images.githubusercontent.com/32933986/86524954-44263700-beb3-11ea-85b8-65b2a01f0654.png)

![image](https://user-images.githubusercontent.com/32933986/86524958-4daf9f00-beb3-11ea-9a9f-cac22c29346f.png)

Let `import os; os.path.splitext()` as an example.

We'd like to use some phase like `ext` to specify `splitext` rather than print `split` first. However, **pylance** does not support this.

**Comment by savannahostrowski** [comment]
Hey @HsunGong 

Thanks for the suggestion. We are currently investigating this request and will update with details soon.

**Comment by jakebailey** [comment]
This was fixed recently as a part of #608. It's now a fuzzy match and should handle these cases.
