### ISSUE TITLE
Unexpected `Never` type being reported, with accompanying reportGeneralTypeIssues error

### ISSUE THREAD

**Issue by ElijahSink** [microsoft/pylance-release#560]
## Environment data

-   Language Server version: v2020.10.3
-   OS and version: Win10 running in WSL
-   Python version: 3.8.6

## Code Snippet
```python
class MyClass():
    pass

def foo(bar: MyClass or Iterable[MyClass]):
    pass

def baz():
    foo([MyClass(), MyClass()])
```
## Expected behavior
`Never` type should not be reported, and no error should be raised.
## Actual behavior
![image](https://user-images.githubusercontent.com/42477963/98053482-3dc2b000-1dfe-11eb-89ab-b78815e90e27.png)

Pylance is somehow suggesting that `Iterable[MyClass]` is actually `Iterable[Never]`, which doesn't seem to make sense.

This behavior appears to be particular to user-defined classes, and not built-in types. If you replace `MyClass` with `str` or similar, there is no issue.

## Logs

```
Will be provided if needed
```

**Comment by jakebailey** [comment]
Is the code actually `MyClass or Iterable[MyClass]`, or did you mean `Union[MyClass, Iterable[MyClass]]`?

**Comment by ElijahSink** [comment]
The code is actually `MyClass or Iterable[MyClass]`, which pylance routinely interprets as the latter expression. We use the `or` syntax widely in our project, and usually have no issues. I assumed it was a commonplace shorthand for Union. With more primitive types, Pylance has no issue with it:
![image](https://user-images.githubusercontent.com/42477963/98054649-2507c980-1e01-11eb-80ef-e4d950d61056.png)

**Comment by erictraut** [comment]
The `or` operator is not a valid replacement for `Union`. The expression `int or str` evaluates to `int`, which is not what you intend.

**Comment by ElijahSink** [comment]
Thanks for the clarification there. Is there a reason why it's generally supported?

**Comment by erictraut** [comment]
This is all defined by the Python standards. See PEP 484 for details.

**Comment by jakebailey** [comment]
If we're supporting `or` as a substitute for `Union` (or that upcoming `|` syntax), I think that's a fluke.

**Comment by erictraut** [comment]
Since `int` is always truthy, the expression `int or str` should result in the value `int`. Likewise, the expression `int and str` should result in the value `str`. I've updated the logic for `or` and `and` to handle the case where the left-hand operand is always truthy. It is not normal to use the boolean `or` and `and` operators with class operands, which is why this issue hasn't come up previously.

In any case, you shouldn't use `or` for type annotations because it will not produce the results you intend.
