### ISSUE TITLE
Different highlight colors for the same type when using the Tokyo Night Storm theme in VS Code

### ISSUE THREAD

**Issue by LifeAdventurer** [microsoft/pylance-release#5604]
## Environment data

-   Language Server version: v2024.2.3
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.4

## Code Snippet

```python
for index, (code, language) in enumerate(LANGUAGES.items()):
    column_width[index % columns] = max(
        column_width[index % columns], len(f"{code}: {language}  ")
    )
    
lang_lines = []
line = ""
for index, (code, language) in enumerate(LANGUAGES.items()):
    if index % columns == 0:
        lang_lines.append(line)
        line = ""

    lang_lines = []
    line = ""
    code_lang_str = f"{code}: {language}"
    line += code_lang_str + ' ' * (
         column_width[index % columns] - len(code_lang_str)
    )
```

## Repro Steps

1. set `"editor.semanticHighlighting.enabled": true,` in `settings.json`
2. and select theme `Tokyo Night Storm`

## Expected behavior

`index, (code, language)` should be the same color in the photo below

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/108756201/2115712e-eb82-4a98-bd53-73f52f34e9f9)
info of the tokens using `Developer: Inspect Editor Tokens and Scopes`
![image](https://github.com/microsoft/pylance-release/assets/108756201/ada8d1c3-8021-4b49-b9dd-d2c3d5934ac2)
![image](https://github.com/microsoft/pylance-release/assets/108756201/efd75bdc-560d-4659-b010-cb0724be53f9)

**Comment by debonte** [comment]
As with #5570, this is by design. Pylance is behaving correctly here.

The theme has chosen to display the declaration (`#bb9af7`) and subsequent usages (`#c0caf5`) of variables in different colors.

```json
"semanticTokenColors": {
    ...
    "variable.declaration": {
        "foreground": "#bb9af7"
    },
    "variable": {
        "foreground": "#c0caf5"
    }
},
```

In Python, loop variables are accessible after the loop exits. So the `index` in the second loop is the same variable as the `index` in the first loop.

**Comment by LifeAdventurer** [comment]
> In Python, loop variables are accessible after the loop exits. So the index in the second loop is the same variable as the `index` in the first.

I understand now. Thanks!
