### ISSUE TITLE
False-positive `unboundvariable` with TYPE_CHECKING

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#5609]
**Python extension:** v2024.2.1
**Pylance extension:** v2024.2.3
**VScode:** 1.85

The issue is self-evident in the screenshot below. Neither mypy, not fkale8, not pylint complain.

![image](https://github.com/microsoft/pylance-release/assets/623756/f672ff96-68a8-439f-a5b2-5e3f93dc408a)

**Comment by erictraut** [comment]
Please post a minimal, self-contained piece of code in text format.

**Comment by debonte** [comment]
> The issue is self-evident in the screenshot below
> Neither mypy, not fkale8, not pylint complain.

@Kein, are you sure you were getting a diagnostic from Pylance? The screenshot above shows a pylint diagnostic.

**Comment by Kein** [comment]
> are you sure you were getting a diagnostic from Pylance? T

🤦
