### ISSUE TITLE
Add semantic token modifier to built-in functions

### ISSUE THREAD

**Issue by raptor494** [microsoft/pylance-release#561]
### Feature request:
add a modifier to the `function` tokens that correspond to Python's built-in functions (print, dir, vars, open, etc.).
I'd like to assign the new semantic token type to `support.function.builtin.python`.

### Situation
Before I installed this extension, I had a theme that automatically colored the Python built-in functions differently than regular functions. With semantic highlighting enabled, the built-in functions look no different than user-defined functions, and there currently isn't a way to disable semantic highlighting on a per-token basis.

### Suggestion
I would like it so that the tokens for the built-in functions (print, dir, vars, open, etc.) get an extra modifier added to them, such as the standard 'defaultLibrary' modifier, so I can adjust my settings to make them colored differently.

**Comment by huguesv** [comment]
Thank you for the suggestion. This has been implemented and will be available in the next release. The new token modifier is named 'builtin'.

**Comment by raptor494** [comment]
Thank you so much, this is an amazing extension and I'm very happy to see all the improvements being made!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020111-11-november-2020
