### ISSUE TITLE
Memory and CPU issues

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5610]
> From: Brendon Baumgartner
> Don't install this if you value your battery or CPU.

**Comment by judej** [comment]
Brendan, sorry to hear about the memory and cpu issues you are seeing. Would you please add some details of what you are seeing? 

The information that would be useful is described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

thank you.

**Comment by MartinSkold** [comment]
Maybe related to my issue here?
https://github.com/microsoft/pylance-release/issues/5632
