### ISSUE TITLE
Semantic Token Type / Tooltip Info changes depending on order of Assignments

### ISSUE THREAD

**Issue by maflAT** [microsoft/pylance-release#5612]
<h3> Environment data </h3>

-   Language Server version: 2024.2.106
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: standard

<h3> Code Snippet </h3>

```python
#                            # Semantic Token Type (Modifier) | Tooltip

def def_first(): ...         # function (declaration)
def_first = lambda: None     # function ()

lambda_first = lambda: None  # variable (declaration)
def lambda_first(): ...      # variable ()
```

<h3> Expected behavior </h3>

Both `def_first` and `lambda_first` are treated identically with regard to semantic highlighting and their type that is displayed in the tooltip.

<h3> Actual behavior </h3>

![grafik](https://github.com/microsoft/pylance-release/assets/13979550/d6fe5e97-7d51-4952-b2d1-8f106a1b46d4)

`def_first` is considered a function, whereas `lambda_first` is considered a variable.
In the outline view and the auto-complete popup, both are displayed as functions.

Probably related: https://github.com/microsoft/pyright/issues/7440

**Comment by rchiodo** [comment]
Thanks for the issue. Since Eric fixed the constant problem, that may fix the semantic highlighting issue when we next update our Pyright bits. I'll wait and try this then.

**Comment by rchiodo** [comment]
Going to won't fix this. It works as expected if the two entries are not rewritten, which seems like the more common case. I don't think we'd spend the time to fix this when they're reassigned.
