### ISSUE TITLE
No auto-completion provided when using overloaded `__new__` definitions

### ISSUE THREAD

**Issue by Viicos** [microsoft/pylance-release#5616]
## Environment data

-   Language Server version: 2024.2.3
-   OS and version: Ubuntu 22
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10

## Issue

The following works fine with auto-completion:
 
```python
class A:
    def __new__(cls, a: int) -> Self: ...
```

![image](https://github.com/microsoft/pylance-release/assets/65306057/cbc4cfb1-8b27-45e3-ac2b-37bf4ef8ea01)

But no suggestion is provided when using overloads:

```python
class A:
    @overload
    def __new__(cls, a: int) -> Self: ...

    @overload
    def __new__(cls, a: str) -> Self: ...
```

![image](https://github.com/microsoft/pylance-release/assets/65306057/33f69917-e09a-416f-a541-b904ef390754)

---

Opening this as a Pylance issue as it works with other pyright LSP implementations (e.g. sublime-lsp).

**Comment by heejaechang** [comment]
looks like a bug. normal method include `__init__` overload work as expected.

**Comment by Viicos** [comment]
I'll add that hovering on `A()` actually shows the overloads:
![image](https://github.com/microsoft/pylance-release/assets/65306057/c6c37cba-356d-4c25-b1ef-b57b63f2253d)

**Comment by Viicos** [comment]
No longer an issue in the latest version(s).
