### ISSUE TITLE
Intellisense breaks with this extension in docker.

### ISSUE THREAD

**Issue by StevenLech** [microsoft/pylance-release#5618]
Type: <b>Bug</b>

As the title indicates, when I have this extension enabled in my docker container, I lose my intellisense autofill. I am using python 3.12.

Extension version: 2024.2.1
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin x64 22.6.0
Modes:
Connection to 'dev-container+7b22686f737450617468223a222f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e74657220323032342f656563733338382f50726f6a656374732f656563733338382d7033222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e74657220323032342f656563733338382f50726f6a656374732f656563733338382d70332f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e746572253230323032342f656563733338382f50726f6a656374732f656563733338382d70332f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e74657220323032342f656563733338382f50726f6a656374732f656563733338382d70332f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|10, 14, 11|
|Memory (System)|8.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id 75c8236c-1a3e-4dbf-b9d0-89095faeff2a|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e74657220323032342f656563733338382f50726f6a656374732f656563733338382d7033222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e74657220323032342f656563733338382f50726f6a656374732f656563733338382d70332f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e746572253230323032342f656563733338382f50726f6a656374732f656563733338382d70332f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f73746576656e2f4465736b746f702f5363686f6f6c2f323032332d323032342f57696e74657220323032342f656563733338382f50726f6a656374732f656563733338382d70332f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30981707
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30958158
dsvsc020:30976470
666c4381:30973075

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Can you provide a log as described here?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

It might be the dev container doesn't have enough memory allocated to it - similar to this issue:
https://github.com/microsoft/pylance-release/issues/5230#issuecomment-1867730738

**Comment by rchiodo** [comment]
Closing issue with no response. If you can respond with the asked for information, please reopen this issue.

Thanks.
