### ISSUE TITLE
import unsuccessful

### ISSUE THREAD

**Issue by dikshapatil0406** [microsoft/pylance-release#5622]
<h3> Environment data </h3>

-   Language Server version: 2024.2.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by heejaechang** [comment]
@dikshapatil0406 
Can you provide us some logs as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)? and some repro steps?

**Comment by dikshapatil0406** [comment]
Yes, I can.
Import "xlsxwriter" could not be resolvedPylancereportMissingImports
<https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports>

**Comment by rchiodo** [comment]
That may be expected. We'd need more information. Like:

- What interpreter do you have selected in the VS code ui?
- Is `xlsxwriter` in your list of packages that are installed in that interpreter?
- The contents of the log as described [here](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)
