### ISSUE TITLE
`Add #type ignore` code action not offered for some type-related diagnostics

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5628]
## Environment data
-   Language Server version: 2024.2.106

## Code Snippet
```python
from os import getcwd

__all__ = { 1: getcwd } # reportUnsupportedDunderAll

def func() -> int:
     return "str" # reportReturnType
```

## Repro Steps

1. Put the cursor on the `reportReturnType` diagnostic on the last line.
2. Note that the `Add #type ignore` code action is provided:
![image](https://github.com/microsoft/pylance-release/assets/12820898/56814ecf-b273-4c0d-9e06-d5d44dd75977)
3. Put the cursor on the `reportUnsupportedDunderAll` diagnostic on the `__all__` line.

## Expected behavior

`Add #type ignore` code action is also available there.

## Actual behavior

It is not:
![image](https://github.com/microsoft/pylance-release/assets/12820898/c3bf3c2a-0987-418a-a90c-f2473082e7da)

Looks like the problem is that we assumed all type-ignorable diagnostics would include the word "Type". I'm guessing that based on the test in [this commit](https://github.com/microsoft/pyrx/pull/4527/commits/ab671644df343b8e7974f8e770e7e9792072b6d5#diff-4623ff2c2297984913108a49c9e0f18059cb0afe3ea80379cfc17746092a884d), which was added along with the "List of Type related diagnostic rules that can be suppressed with a type ignore comment" in `addTypeIgnore.ts`:

```typescript
test('test for newTypes', async () => {
    const pyrightTypeRuleKeys = Object.keys(DiagnosticRule).filter((key) => key.includes('Type'));

    pyrightTypeRuleKeys.forEach((key) => {
        assert(
            AddTypeIgnore.typeRuleKeys.includes(key as DiagnosticRule),
            `Missing ${key} in AddTypeIgnore.typeRuleKeys`
        );
    });
});
```

I was thinking about this because Eric [just added a new `reportUnhashable` diagnostic](https://github.com/microsoft/pyright/pull/7464/files) and I wanted to be sure that it got added to that list. But maybe we don't need the list at all? What are the class of diagnostics that can be suppressed with `#type: ignore` and `#pyright: ignore`? Is it all non-syntax errors?

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.3.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20243101-21-March-2024-PreRelease)
