### ISSUE TITLE
Unreachable conclusion reached even if Python->Analysis->Type Checking Mode is "off"

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#5640]
## Environment data

-   Language Server version: 2024.3.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10, Anaconda

## Code Snippet

```python
from typing import Any

import pandas as pd

s = pd.Series([3.4, 2.3])
r: Any = 3.2
s.round(r)

r1 = 3.4
s.round(r1)


def generate_series() -> Any:
    return pd.Series([1, 2, 3])


foo = {k: generate_series() for k in range(10)}
reveal_type(foo)
df = pd.concat(foo, axis=1)

print("unreachable?")

```

## Repro Steps

1. In Settings, Turn "Python->Analysis->Type Checking Mode " to "basic"
2. Then the call to `round()` is shown as incorrect, and code at the bottom is shown as unreachable.  Both of these conclusions are correct.
3. In Settings, Turn "Python->Analysis->Type Checking Mode" to "off"
4. The call to `round()` is not marked (which is correct - type checking is off), but the code at the bottom is still shown as unreachable.

## Expected behavior

If type checking is off, then the unreachable analysis should not occur.  The only way that analysis can occur in this case is because the pandas stubs were analyzed with respect to the code.

## Actual behavior

Last line shows unreachable if type checking is off.

Related to #5630 and #5631 - I think this is the real problem, not the `pandas-stubs` (for which I maintain)

**Comment by Dr-Irv** [comment]
Here's an example that illustrates the problem is not with `pandas-stubs`:

```python
from random import SystemRandom

sr = SystemRandom()

foo = sr.getstate()

print("hey")
```

With type checking off, the line `print("hey")` is shown as unreachable.  But the only way to make that conclusion is by looking at the typeshed stubs.

**Comment by Dr-Irv** [comment]
It actually may be better to introduce an option in `pylance` to turn off the unreachability analysis, because it doesn't allow untyped code to use stubs that are using `NoReturn` or `Never` to prevent untyped arguments.

**Comment by Dr-Irv** [comment]
> Type evaluations inform completion suggestions and other language server features. Reachability analysis is needed to produce correct type evaluations. For those reasons, it doesn't make sense to disable reachability analysis regardless of the mode.

If you are not doing type checking by turning the feature off, then why would you need to do "correct type evaluations"?

> 
> The problem here is that you're arguably using `NoReturn` incorrectly in the stubs. The `NoReturn` return type means that the function will never return control back to the caller. It doesn't mean that the arguments the function receives are incorrect and should be flagged as an error.

But in this case, in pandas, it means that if those arguments are passed, then the function will not return control back to the caller.  So why is that not a correct interpretation of the use of `NoReturn` ?  I should also note that command line `pyright` and `mypy` do not report an error on the original code - this is all happening because of the reachability analysis.

I did discover that you have `pyright.disableTaggedHints` as an option, but I don't see how to get VSCode to recognize that in its settings.

**Comment by erictraut** [comment]
> If you are not doing type checking by turning the feature off, then why would you need to do "correct type evaluations"?

We are still doing full type evaluations. We simply don't report all the errors we find in the process.

> But in this case, in pandas, it means that if those arguments are passed, then the function will not return control back to the caller.

Then it's the correct interpretation, and it's appropriate for a language server to show this.

> I should also note that command line pyright and mypy do not report an error on the original code - this is all happening because of the reachability analysis.

Unreachability is not an error. There are many legitimate reasons why code cannot be reachable. It's useful to show users in their editor that code is not reachable, and this is done through a subtle grayed-out text appearance. There's no need to report this condition in the command-line because it's not an errant condition or something that needs "fixing".

> I did discover that you have pyright.disableTaggedHints as an option, but I don't see how to get VSCode to recognize that in its settings.

This was added because some (non-VS Code) editors incorrectly interpret the tagged hints and display them as regular diagnostics. This is (understandably) really annoying for users of those editors. This option gives them the ability to work around this limitation in their editor. It's not applicable to VS Code because it correctly handles these tagged hints.

**Comment by Dr-Irv** [comment]
> It's useful to show users in their editor that code is not reachable, and this is done through a subtle grayed-out text appearance.

Yes, but in this case, because people had code that was untyped where pyright inferred the argument to be `Iterable[Any]`, they got the unreachable message, which is true if you don't know the type, but incorrect (in terms of saying its unreachable) if you have untyped code.  They then blame `pandas-stubs` for being incorrect, and the stubs are correct _if_ the calling code was correctly typed.

Also, the reachability analysis is inconsistent.  Consider this example (which will not execute):
```python
from datetime import date, datetime
from typing import Any

onedate = date(2024, 3, 14)
onedt = datetime(2024, 3, 14, 10, 15)

result = onedate - onedt
reveal_type(result)

print("unreachable")
```

In this case the type of `result` is `NoReturn`, but VS Code does not highlight the unreachable print statement!  And the type checker isn't picking up that subtracting a `datetime` from `date` is invalid (as indicated by the `NoReturn` in the stub).

If instead of using `result = onedate - onedt`, you had `result = onedate.__sub__(onedt)`, then it does see the code as being unreachable.

**Comment by erictraut** [comment]
@Dr-Irv, this isn't something that we're going to change in pyright. I'm not interested in arguing this point further.

I recommend that you re-examine your use of `NoReturn` overloads in pandas stubs. You are using `NoReturn` in overloads in a way that was never intended, and this is (not surprisingly) leading to undesirable behavior. If your intent is to specify that a particular combination of arguments should be treated as an error, we need another mechanism for this.

**Comment by Dr-Irv** [comment]
> @Dr-Irv, this isn't something that we're going to change in pyright. I'm not interested in arguing this point further.

I don't think this is something you have to change in `pyright`.  It's about how `pyright` is integrated into `pylance`.
> 
> I recommend that you re-examine your use of `NoReturn` overloads in pandas stubs. You are using `NoReturn` in overloads in a way that was never intended, and this is (not surprisingly) leading to undesirable behavior. If your intent is to specify that a particular combination of arguments should be treated as an error, we need another mechanism for this.

You're inconsistent here.  Above you wrote (quoting me):

> > But in this case, in pandas, it means that if those arguments are passed, then the function will not return control back to the caller.
> 
> Then it's the correct interpretation, and it's appropriate for a language server to show this.

I agree that the interpretation is correct, meaning our use of `NoReturn` is appropriate.  

I question whether it's appropriate to show that the code is unreachable on untyped code.  And if you want to leave that in there, then you have to decide if there should be some control that allows a user to turn off the reachability analysis, since there are cases where I think it is inappropriate to show that the code is unreachable.

@debonte - I don't think you should close this yet.
