### ISSUE TITLE
Pylance WSL can't access file with hashed filename generated from `_generated_diagnostic_collection_name`

### ISSUE THREAD

**Issue by mathisgauthey** [microsoft/pylance-release#5641]
## Environment data

-   Language Server version: v2024.3.1
-   OS and version: 
```
Version WSL : 2.0.14.0
Version du noyau : 5.15.133.1-1
Version WSLg : 1.0.59
Version MSRDC : 1.2.4677
Version direct3D : 1.611.1-81528511
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Version de Windows : 10.0.22631.3296
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12

## Code Snippet

![image](https://github.com/microsoft/pylance-release/assets/46576952/a76bf6b2-6dad-4c84-9036-19bb4405e839)
![image](https://github.com/microsoft/pylance-release/assets/46576952/d1318dc4-ad23-415e-b461-8610270af7cc)

## Repro Steps

Use a python repo inside WSL, it'll generate some issues in `PROBLEMS` tab from a hashed filename in the `.` folder

## Expected behavior

I should be able to see actual files and click on them to see and correct error.

## Actual behavior

Error generated on the `PROBLEMS` tab are from unfindable files somewhere I can't find.

**Comment by rchiodo** [comment]
Thanks for the issue. Do you have a repository that you can share that reproduces the problem?

Additionally if you could gather these logs it would help diagnose the issue. 
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

My guess is that there is something in the file path that is getting lost when we return the diagnostic.

**Comment by mathisgauthey** [comment]
Sure.

Here's my [work setup](https://github.com/mathisgauthey/odoo-dev-env-WSL), simply use this script in a folder inside WSL : 

```bash
#!/bin/bash

# Install Ubuntu dependencies
sudo apt install python3-dev python3-venv build-essential gcc libsasl2-dev libldap2-dev libssl-dev libpq-dev

# Clone the odoo source code
git clone https://github.com/odoo/odoo.git

# Create a python virtual environment
python3 -m venv odoo_venv

# Install Odoo dependencies inside the python virtual environment
source odoo_venv/bin/activate
pip install -r odoo/requirements.txt
```

Make sure to select the right python interpreter from the virtual environment `Python 3.10.12 venv/bin/python` from the bottom menu.

![image](https://github.com/microsoft/pylance-release/assets/46576952/7d3da8c1-d065-4844-9665-7fd705c9bbb2)

And then go inside a Python file.

I'm on another computer here and can't reproduce, this is weird. I'll make sure to send you some logs from my computer tomorrow but will need to do some privacy editing of the logs I reckon.

**Comment by rchiodo** [comment]
Were you debugging when you hit this problem? The unknown files might be from callstacks that don't have source. It would make sense that they can't be opened on disk because they don't exist.

**Comment by rchiodo** [comment]
Or potentially something else that is opening 'virtual files'. VS code allows the creation of virtual files. Some other extension might be generating those weird guid named files.

**Comment by rchiodo** [comment]
I can't seem to repro anything like this, so I'm guessing it's some sort of virtual file. There wouldn't be a file on disk for that so it would be behaving as designed.

**Comment by mathisgauthey** [comment]
It seems to be related to files generated while using `debugpy` when debugging python files. I'll try to look a bit more. Any idea what's this `generated...` file from the `source` column inside `PROBLEMS` table ?

**Comment by mathisgauthey** [comment]
> I did a search on https://cs.github.com. This is the first hit and the likely culprit: https://github.com/microsoft/vscode/blob/1454837231cec5ac0f9e8e80124a961cb36373c1/src/vs/workbench/api/common/extHostDiagnostics.ts#L283

Wow, I didn't know about such a Github global search feature. So it would definitely be linked to WSL, and maybe the debugger. I don't know what else I could do to help, or if there's anything we could do at all to ignore these type of file in Pylance, but I'd be glad to land a hand !
