### ISSUE TITLE
Users should be able to tell which `pandas-stubs` we have bundled

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5643]
As suggested by @Dr-Irv [here](https://github.com/microsoft/pylance-release/issues/5630#issuecomment-1998667409), it would be good if users could easily identify which `pandas-stubs` commit is bundled in their Pylance install.

We should probably do this for all bundled stubs.

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.3.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20243102-27-March-2024-PreRelease)

**Comment by disrupted** [comment]
how do you inspect the bundled version in the new release?

**Comment by StellaHuang95** [comment]
If you go to `...\.vscode\extensions\ms-python.vscode-pylance-2024.3.102\dist\bundled\stubs\pandas\_version.pyi`, you should be able to see the stub version and commit hash that's bundled in pylance.

**Comment by disrupted** [comment]
gotcha, for a minute I thought there was an official way to see it in the UI or ask the language server

**Comment by Dr-Irv** [comment]
> If you go to `...\.vscode\extensions\ms-python.vscode-pylance-2024.3.102\dist\bundled\stubs\pandas\_version.pyi`, you should be able to see the stub version and commit hash that's bundled in pylance.

Easier way:
Place this in your code:
```python
import pandas as pd
from pandas import _version
```
Right click on `_version`, and select "Go to Declaration".  Then it will open the file and you'll see the stubs version and commit hash.
