### ISSUE TITLE
Adding additional space after pressing Enter

### ISSUE THREAD

**Issue by mcornwell16** [microsoft/pylance-release#5644]
Type: <b>Bug</b>

Hitting "Enter" results in a new line + and extra space. I have not noticed this behavior before. 

Extension version: 2024.3.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'wsl+debian' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.74GB (44.36GB free)|
|Process Argv|--crash-reporter-id 8b221068-c226-4480-afe5-cf579551ce04|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+debian' could not be established
</details>

**Comment by debonte** [comment]
This is expected in many cases. Can you provide a code sample along with an indication of where the cursor was when you pressed Enter and the indentation behavior that you saw?

**Comment by mcornwell16** [comment]
Really odd - I can't replicate the issue this morning. Was wholly consistent last night too. 

I'll update if it starts happening again today. 

Appreciate the fast reply!

**Comment by debonte** [comment]
No problem. Closing for now.
