### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5649]
FROM:Stefan Savov Vasilev
> Freezes vscode taking up all available virtual memory

Stephan, sorry you are seeing this issue. We have had a reports of memory consumption and are actively looking at it. Could you help us by sending us the Pylance logs when you are seeing this problem? The  [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue) has the instructions for collecting the logs.

thanks

**Comment by bschnurr** [comment]
@Vasilev  do you have a github repo or code sample you could provide?

**Comment by bschnurr** [comment]
Our next release april 4, 20224 will contain some memory usage fixes
