### ISSUE TITLE
Function return type hidden / unnecessary scrolling

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#565]
## Environment data

-   Language Server version: 2020.11.0
-   Python Extension: v2020.10.332292344
-   OS and version: macOS
-   Python version: 3.9

## Expected behaviour

Display the complete return type.

## Actual behaviour

If the return type happens to span across multiple lines, the text box height will only be determined by the function definition. Sometimes this leads to the return type being hidden / only completely visible after scrolling.

Hover works as expected.

## Code Snippet / Additional information

![Screen Shot 2020-11-04 at 23 57 42 1](https://user-images.githubusercontent.com/30130371/98176793-8f039a00-1ef9-11eb-8cb6-501095d158c5.png)

![Screen Shot 2020-11-04 at 23 50 26](https://user-images.githubusercontent.com/30130371/98176298-88c0ee00-1ef8-11eb-8917-7705e4f3f4e4.png)

I've include the Python Extension version above, since I'm not sure what is responsible.

**Comment by jakebailey** [comment]
This is an unfortunate known bug with VS Code tooltips when there's only one line and it gets wrapped. I'm not sure if it's reported upstream, though.

However, I believe that VS Code will soon support resizing the tooltips in the UI, which may make it possible to just make them bigger when needed.

**Comment by cdce8p** [comment]
It seems to be fixed with VS Code `1.51.0`. Closing it
