### ISSUE TITLE
multiple `#type: ignore` shown for 1 line if that line contains multiple errors

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5657]
paste this in `a.py` and set `typechecking mode: basic`

```

register

```

and put cursor at `register`, `register` will have multiple diagnostics and pylance will show `#type: ignore` code actions per diagnostics.

it should show only 1 code actions for all diagnostics on same line.

**Comment by debonte** [comment]
This issue has been fixed in prerelease version 2024.4.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20244104-25-April-2024-PreRelease)
