### ISSUE TITLE
Extract Method unexpectedly adds type parameter for local type

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5661]
## Environment data

-   Language Server version: 2024.3.100

## Code Snippet
```python
class MyClass:
    pass 
    

foo: MyClass
```

## Repro Steps
1. Select line `foo: MyClass`
2. Press light bulb and choose "Extract method"

## Expected behavior

```python
def new_func():
    foo: MyClass

new_func()
```

## Actual behavior

```python
def new_func(MyClass):
    foo: MyClass

new_func(MyClass)
```

I ran into this when extracting a larger, more interesting chunk of code, but this seems to be the minimal repro example.

**Comment by rchiodo** [comment]
Closing as nobody else has noticed.
