### ISSUE TITLE
attrs frozen instances aren't detected as hashable

### ISSUE THREAD

**Issue by fathom-parth** [microsoft/pylance-release#5666]
## Environment data

-   Language Server version: 2024.3.1 (pyright version 1.1.351, commit 87171fbf
-   OS and version: MacOS Sonoma 14.4
-   Python version: python 3.7.16

## Code Snippet

Python requirements:
* attrs version 22.2.0

```python
from typing import FrozenSet
from attrs import frozen

@frozen
class Foo:
    x: int

global_frozenset: FrozenSet[Foo] = frozenset(
    {
        Foo(1),
    }
)
```

## Repro Steps

1. Copy paste the above snippet into vs code
2. See issue

## Expected behavior

No error

## Actual behavior

Error:
![image](https://github.com/microsoft/pylance-release/assets/59978261/26ff6439-0ab7-4809-b343-56d52d11cb33)

## Logs

This kept crashing my vs code but let me know if you really need this and I can work harder to get this to you!

**Comment by erictraut** [comment]
Newer versions of `attrs` fix this problem. I just confirmed that the issue no longer repros with the latest version (attrs 23.2.0).

**Comment by fathom-parth** [comment]
ah gotcha, I'll cycle to update it if we can

**Comment by fathom-parth** [comment]
Just to close the loop, updating attrs in our requirements fixed the issue!
