### ISSUE TITLE
NO means NO - stop prompting to make pylance the default language server

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/pylance-release#568]
![59810abc21000025a7fc9b6b](https://user-images.githubusercontent.com/2473545/98250554-56de7480-1f56-11eb-90c7-e570e2d734e9.jpg)

## Expected behaviour
![Snipaste_2020-11-05_10-53-17](https://user-images.githubusercontent.com/2473545/98250754-9e650080-1f56-11eb-9f4c-cfe37f9be6ea.png)

I know that microsoft has a history of disrepcting user choices, and agressively pushing microsoft defaults into users even when users said "no", but this is getting extremely annoying on my text editor. 

Once a user confirms that it does not want to make Pylance the default language server, you should never prompt it again. 
Not even if pylance is updated. 
Not even if I open a new folder.
Not even if I open a new file. 

Once I said "no, thanks" it's pretty clear that I don't want to make pylance the default language server. 

## Actual behaviour

Randomly, when user opens a new folder, or python file, or updates the extension, Pylance will annoy the user prompting to make it the default language server.

**Comment by jakebailey** [comment]
This prompt will appear if Pylance is installed but not set as the language server. If you aren't intending on using it, can you uninstall the extension? Or are you looking to only use it for some workspaces and not others?

**Comment by phgmacedo** [comment]
@jakebailey I installed it because intellicode and python for vscode will spam me to death with notifications If I don't. 
Even if I intended to only enable it for "some" workspaces, the prompt would still be wrong because it would change the global language server, not only the settings for the local workspace.

**Comment by phgmacedo** [comment]
@jakebailey I also have "python.languageServer": "Jedi" on my settings, which makes it pretty clear that I don't want the closed source pylance enabled. 
If you're not trying to make it annoying like other microsoft programs that ignore user default preferences, then why not respect the prompt?

**Comment by jakebailey** [comment]
We'll switch our prompt to ensure that clicking "no" never shows it again.

If I'm understanding this correctly, the reason for installing Pylance is just to make the IntelliCode extension not pop up as well; their prompt unfortunately does not have a "no" setting, but we can go see about getting that added as that's a better solution to this than installing an extension you don't plan to use.

**Comment by phgmacedo** [comment]
@jakebailey Yes, it would be helpful to fix it in intellicode as well! Thanks!

**Comment by beauxq** [comment]
I haven't tried yet, but I'm interested in being able to use it for some workspaces and not others.

Is this possible? How is it configured?

**Comment by jakebailey** [comment]
You can set `python.languageServer` within your folder/workspaces's `settings.json`, and it will be applied for that editor session.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.11.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020111-11-november-2020
