### ISSUE TITLE
Pylance deduces incorrect type. Is there a way to override this?

### ISSUE THREAD

**Issue by dhylands** [microsoft/pylance-release#5680]
## Environment data

-   Language Server version: v2024.3.1
-   OS and version: Ubuntu 22-04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.12

## Code Snippet

```python
def my_func():

    class Node:
        def __init__(self):
            self.D = None

    def func(node):
        node.D = 17

    root = Node()
    func(root)
    return root.D
```

## Repro Steps

Open source file containing above snippet.

## Expected behavior

Pylance should show that the return type of my_func is an int

In my case, I'm using third party software, so I would also be happy if there was a way I could tell pylance what the actual return type of the function is, rather than None.

## Actual behavior

Pylance shows return type of my_func as being None

## Logs

```
Unable to include the log as it was too big (max 65536 allowed(
```

**Comment by erictraut** [comment]
The behavior here is intended and correct. The type of attribute `D` is not declared, so its type is inferred based on all assignments to it within the class. Static analyzers do not (and generally cannot) perform cross-function analysis, so although `func` has the side effect of setting `D` to an `int`, this is not something a static code analysis tool will determine.

For more details about how type declarations and type inference works in the Python static type system, refer to the pyright [documentation](https://microsoft.github.io/pyright/#/type-concepts).
