### ISSUE TITLE
Features break when editing certain files

### ISSUE THREAD

**Issue by jocropsey** [microsoft/pylance-release#5690]
## Environment data

-   Language Server version: v2024.3.2
-   OS and version: Windows_NT x64 10.0.14393 (also occurs on RHEL 8 machine)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.2

**Result of "Help: Start Extension Bisect"**: Pylance extension
**Problem Summary:** Editing certain files in any way breaks Pylance features for that file

## Expected behavior

I expect to be able to edit my files and have syntax highlighting, hover hints, refactoring, etc. function as intended.

## Actual behavior

When editing certain files, syntax highlighting and hints break. They behave as though the file has not been edited since VS Code was last loaded, despite this not being the case. Problem is demonstrated in the pictures below:

*Figure 1: File Without Edits*
![image](https://github.com/microsoft/pylance-release/assets/33427348/8b6f82d2-f186-40ca-a72e-358df588ddfd)

I then decide to add in the new function, `test_func`. As you can see in the picture below, all highlighting and hints following this change break. Hovering over anything in an edited line behaves as it did before changes were made.

*Figure 2: File With Edits*
![image](https://github.com/microsoft/pylance-release/assets/33427348/e65c3db0-ef28-40d3-a376-fb637d58f669)

## Logs

[Python Language Server.log](https://github.com/microsoft/pylance-release/files/14758153/Python.Language.Server.log)

***

## Things I have tried

**Action**: Restarting VS Code / Calling reload command
**Result**: Pylance "fixes" itself and functions as expected until you edit anything, then the problem returns

**Action**: Disable all extensions
**Result**: No problem because, obviously, the bug has to do with Pylance's features.

**Action**: Disable all extensions, *except* Pylance and its dependencies
**Result**: Problem persists

**Action**: Rename the problem file
**Result**: File can be freely edited with Pylance features working. The moment the filename is returned to its original, all the problems return if the file has been edited in any way since program restart.

**Action**: Duplicate workspace (File > Duplicate Workspace)
**Result**: File can be freely edited with Pylance features working

***

This issue does not seem to have any rhyme or reason in what causes it. I have multiple files throughout my projects and most of them have no issues, but then certain files will suddenly start doing this. Once they "get the bug", it's there forever unless I create an entirely new workspace. Over time, that workspace develops its own new set of "problem files".

My problem seems a bit similar to this one opened for VS Code [here](https://github.com/microsoft/vscode/issues/152032), but with some key differences:

* My issue persists with all extensions disabled, excluding Pylance
* Removing the changes *does* "fix" the problem
* Their problem is with Java, so obviously cannot be Pylance related

Any help would be greatly appreciated!

**Comment by rchiodo** [comment]
Thanks for the issue. It looks like there's something else modifying the file after you edit it. We get this in the log at the very end:

```
2024-03-26 07:59:17.616 [info] [Info  - 7:59:17 AM] (12428) SourceFile: Received fs event 'change' for path 'e:\projects\code\PROJECT\PROJECTcore\PROJECTcore\support\userprompts.py'
2024-03-26 07:59:17.617 [info] [Info  - 7:59:17 AM] (12428) SourceFile: Received fs event 'change' for path 'e:\projects\code\PROJECT\PROJECTcore\PROJECTcore\support\userprompts.py'
```


Is there another process modifying this file? Like maybe a format on save?

What happens if you delete all of the code in the file and then say add something like:

```
import sys
sys.
```

Do completions work after the `sys.`? I'm trying to see if we think the file isn't getting any change notifications.

**Comment by jocropsey** [comment]
Okay, it does seem like format on save might be causing this issue. Typically I have this setting enabled, but after disabling it and restarting VS Code the problem seems to have gone away (for now anyway)

**Comment by rchiodo** [comment]
We should still work in that case though. Hmm. I wonder if one of your formatters is saving the file outside of using VS code APIs. Although you said you repro'd it with just Pylance enabled? So just VS code would be doing the edits then. 

I'm trying the same thing myself and not hitting a problem, but it might be timing dependent. 

Can you upload your settings.json (well the old settings)?

**Comment by rchiodo** [comment]
The change event may be a red herring. I get them too but the colorization works fine for me. 

Can you share your project? Without a repro, I don't think logging is going to be enough to figure out what's happening.

**Comment by rchiodo** [comment]
@malcolmsailor if you still want to share your project, you can e-mail it to me directly. My e-mail address is the same as my github id at microsoft.com.

**Comment by malcolmsailor** [comment]
> @malcolmsailor if you still want to share your project, you can e-mail it to me directly. My e-mail address is the same as my github id at microsoft.com.

OK, sending an email!

**Comment by rchiodo** [comment]
Thanks for the e-mail. Unfortunately I can't reproduce even with your example project. Although maybe it's a timing related issue as I couldn't use the extra paths you had set (they pointed to a google drive). 

It might be that the language server is just busy? So busy that it doesn't have a chance to respond to anything. This should be detectable by checking if there's any output in the `Python Language Server` log after you type in a file. It should cause analysis to run on the file being typed in.
