### ISSUE TITLE
code highlighting issues

### ISSUE THREAD

**Issue by benblo** [microsoft/pylance-release#570]
## Environment data
-   Language Server version: 2020.11.0 (pyright 9d8e431b)
(activated as the default language server in Python extension settings)
-   OS and version: Windows 10 Pro, Version	10.0.19041 Build 19041
-   Python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

## Expected behaviour

- @property and property(lambda) members should be treated the same (same color/icon/member type)
- known tokens shouldn't appear white (or, unknown tokens should appear in a different color, eg grey)
- (I realize I can probably configure those colors myself, but the default values should be more sensible IMO.)

## Actual behaviour

![image](https://user-images.githubusercontent.com/574187/98269097-a55b3580-1f8d-11eb-820f-de2012e85b20.png)

From the above screenshot:
- Notice how `my_property_from_decorator` appears white, while both `my_property_from_field` and `my_method` appear yellow.
  - One is considered a "property", the other a "variable" (the icons are also different):
![image](https://user-images.githubusercontent.com/574187/98272329-44356100-1f91-11eb-8893-c3a662c953aa.png)
![image](https://user-images.githubusercontent.com/574187/98272377-4f888c80-1f91-11eb-8790-05d3a871af45.png)
![image](https://user-images.githubusercontent.com/574187/98272559-85c60c00-1f91-11eb-9fd2-609ce67b4493.png)
- Also notice how in `my_property_from_field`'s body, `.bar` appears white, ie the self from the lambda is untyped (`my_property_from_decorator` doesn't have that issue, ie self typed and `.foo` appears blue)
![image](https://user-images.githubusercontent.com/574187/98272868-e35a5880-1f91-11eb-942a-17ee410127a0.png)
- Generally, I think white should be reserved for unknown tokens (eg `test.doesnt_exist`); any type of token that is known should be colored, eg modules (notice how `sys` also appears white).

## Code Snippet / Additional information
Here's the code from the above screenshot:

```python
class Test(object):
	def __init__(self):
		self.foo = "foo"
		self.bar = "bar"

	def my_method(self):
		pass

	@property
	def my_property_from_decorator(self):
		return self.foo

	my_property_from_field = property(lambda self: self.bar)


test = Test()

test.my_method()
test.my_property_from_decorator
test.my_property_from_field

test.doesnt_exist

import sys
sys.version
```

**Comment by benblo** [comment]
Side-note: I ended up modifying my own color settings: the semantic options are relatively straightforward (and the scopes inspector is awesome!), but the syntactic ones (TextMate rules) not so much (though very thorough).
It'd be great if we had an "unknown" semantic rule as a kind of kitchen-sink for all semantically unidentified tokens.

**Comment by jakebailey** [comment]
This appears to have been fixed at some point:

![image](https://user-images.githubusercontent.com/5341706/106978342-ed1a6600-6710-11eb-976c-ac0bd4e40af5.png)

**Comment by benblo** [comment]
Well yes and no: both types of properties are now colored similarly, but otherwise all I said before still holds:
- `my_property_from_field` appears as "variable" in the tooltip (whereas `my_property_from_decorator` appears as "property")
- their icons are different in the autocomplete menu
- `self` is untyped in `my_property_from_field`'s lambda
- `test.doesnt_exist`: it'd be great if we had an "unknown" semantic rule as a kitchen-sink for all semantically unidentified tokens

I'm not posting new screenshots since the tooltips etc are the same as before, except for the property colors (now variable-blue instead of method-yellow).

**Comment by jakebailey** [comment]
The first two are probably a bug and should be a new issue; it sounds like we aren't handling the `foo = property(...)` form, but I'm not sure to what extent we support it given that it's dynamic.

As for `self`, that's a scoping rule problem; I'm surprised that works but...:

```python
class Test(object):
    def __init__(self):
        self.foo = "foo"
        self.bar = "bar"

    def my_method(self):
        pass

    @property
    def my_property_from_decorator(self):
        return self.foo

    def get_bar(self):
        return self.bar

    my_property_from_field = property(lambda self: self.bar)

    weird_method = lambda self: self.bar


test = Test()

print(test.my_method())
print(test.my_property_from_decorator)
print(test.my_property_from_field)
print(test.weird_method())
```

Prints:

```
None
foo
bar
bar
```

So apparently you can make a method out of a lambda where the first parameter is self... 😬

**Comment by benblo** [comment]
Alright, I've split them up in several issues: 
- https://github.com/microsoft/pylance-release/issues/1230 : @property and property(lambda) members are not treated the same (bug)
- https://github.com/microsoft/pylance-release/issues/1231 : lambda properties should identify the self parameter as an instance of their containing class (not sure if bug or request 😄)
- https://github.com/microsoft/pylance-release/issues/1232 : "unknown/undefined" semantic token type (request)

Thanks Jake!
