### ISSUE TITLE
typo in `reportDeprecated` message

### ISSUE THREAD

**Issue by qexat** [microsoft/pylance-release#5705]
## Environment data

-   Language Server version: 2024.3.2 (pyright version 1.1.351, commit 87171fbf)
-   OS and version: n/a
-   Python version (& distribution if applicable, e.g. Anaconda): n/a

## Code Snippet

```python
import typing_extensions


@typing_extensions.deprecated("This function is depracted")
def foo(x: int) -> str:
    return chr(x + 0x20)


foo(3)  # The function "foo" is deprecated   This function is depracted
```

The second line says "depracted" instead of "deprecated"

**Comment by debonte** [comment]
> @typing_extensions.deprecated("This function is depracted")

That's the string that you provided to the decorator.

**Comment by qexat** [comment]
> > @typing_extensions.deprecated("This function is depracted")
> 
> That's the string that you provided to the decorator.

Welp I should sleep more apologies
