### ISSUE TITLE
Move symbol to new file isn't opening the new file

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#5709]
<h3> Environment data </h3>

-   Language Server version: 2024.3.102
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): Poetry, Python 3.12
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class TypeToMove:
    pass
```

<h3> Repro Steps </h3>

1.Hover on TypeToMove, click the light bulb and select "Move to new file" 

<h3> Expected behavior </h3>

The symbol moves to a new file with the symbol name, and the file opens in the editor 

<h3> Actual behavior </h3>

The file is successfully created but it doesn't open in the editor, so it seems as if it failed when it didn't

<h3> Logs </h3>

[pylance28032024logs.txt](https://github.com/microsoft/pylance-release/files/14797615/pylance28032024logs.txt)

**Comment by debonte** [comment]
From our perspective this is by design. See https://github.com/microsoft/pylance-release/issues/5217.

If you believe this is the wrong behavior, it would be an issue for vscode.

**Comment by luabud** [comment]
I thought that was the case only when auto save was enabled? in case it's disabled it'd still make sense to open the editor? 🤔

**Comment by debonte** [comment]
> I thought that was the case only when auto save was enabled? in case it's disabled it'd still make sense to open the editor? 🤔

Yes, that's correct. Do you have `files.refactoring.autoSave` set to `false`? It's `true` by default.

**Comment by luabud** [comment]
Ah, I see. I was confusing it with the `files.autoSave` setting. Thank you :)
