### ISSUE TITLE
How can I tell pylance that this short circuit expression is ok?

### ISSUE THREAD

**Issue by beauxq** [microsoft/pylance-release#571]
```python3
    merged: Dict[float, bool] = {}
    # merged is filled with stuff

    final = []
    lf = False
    last = None
    for k, v in merged.items():
        if v == lf:
            # note: the 1st time this block is executed, v must be False
            # because lf is initialized to False and hasn't had any chance to change
            lf = not lf
            # so at this point, either v is False, or last is float
            if (v == True) and (k - last >= 7):
                final.append((last, k))
            last = k  # last is changed from None to float, and has no chance to go back to None
```

pylance thinks I'm trying to subtract `None` from `float`, but I'm not because short circuit prevents evaluation of that.

How can I tell pylance that this short circuit expression is ok?

**Comment by erictraut** [comment]
A type checker doesn't reason about relationships between different symbols (e.g. `k` must be of type `int` since `v` evaluated to `True`).

The easiest way I see to address this particular case is to initialize `last` with the value `0` rather than `None`. That way, its type will be inferred as `int` rather than `int | None`.

**Comment by beauxq** [comment]
That doesn't work if I was planning to use the `None` value later to find out whether any `v` was `False`.
But I can figure something out if I need to. That's not my concern here.

My question was about how to tell pylance that the expression is ok.

I guess you could consider this as a feature request for something like TypeScript's `@ts-ignore`.

**Comment by jakebailey** [comment]
There is, you could use `# type: ignore`, but that wouldn't change the way that the analyzer looks at this code in terms of the code flow (and not being able to prove this specific condition).

You could also do:

```python
from typing import cast

if (v == True) and (k - cast(float, last) >= 7): ...
```

**Comment by savannahostrowski** [comment]
@beauxq Did the above suggestion work for you?

**Comment by savannahostrowski** [comment]
This issue has been opened for > 30 days with a waiting for information label so I'm going to close this. If this is still an issue, feel free to ping us and we can reopen.
