### ISSUE TITLE
Command telegram.ext.filters.ALL = import Updater, CommandHandler, MessageHandler, CallbackContext with error

### ISSUE THREAD

**Issue by AlanBzerra** [microsoft/pylance-release#5713]
Hello my friends, I'm trying to make an autoresponder system in Python, but my error code would really appreciate your help, thank you! ![print](https://github.com/microsoft/pylance-release/assets/165552213/5862929e-c5cc-4b9a-b930-cc20d81222c4)

**Comment by StellaHuang95** [comment]
Are you trying to assign the import statement to the attribute `All` of the `filters` module? This is not valid syntax in Python because you cannot assign the result of an import statement directly to an attribute like this.
