### ISSUE TITLE
Mismatch between hover and return type inlayhint for Callables

### ISSUE THREAD

**Issue by bschnurr** [microsoft/pylance-release#5727]
## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

Not sure if its better to show the Callable condensed version in hover or not

## Code Snippet

```python
def real_set_args(func):
    def wrapper(*args, **kwargs):
        pass
    return wrapper
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

![image](https://github.com/microsoft/pylance-release/assets/1946977/55e0d587-5df0-4efb-b223-eba40c43ef2a)

## Logs

```
XXX
```

**Comment by erictraut** [comment]
You might find [this recent thread](https://discuss.python.org/t/subtyping-rules-for-in-callable-types/50136/18) in the typing forums interesting.

**Comment by heejaechang** [comment]
showing `(...) -> ..` form in any tooltip is by design. we show valid python syntax form in inlay hint since user can double click to insert the text to user code.
