### ISSUE TITLE
attributes added in __new__ are not tracked

### ISSUE THREAD

**Issue by benblo** [microsoft/pylance-release#573]
## Environment data
-   Language Server version: 2020.11.0 (pyright 9d8e431b)
(activated as the default language server in Python extension settings)
-   OS and version: Windows 10 Pro, Version	10.0.19041 Build 19041
-   Python version: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

## Expected behaviour
- the type of `self` variable in `__new__` should be inferred correctly/automatically
- attributes added in `__new__` should be tracked like they are in `__init__` (or any instance method)

## Actual behaviour
![image](https://user-images.githubusercontent.com/574187/98344225-3c1e0580-2013-11eb-8014-5099ed19ae08.png)

From the above screenshot:
- Notice how `new_attr` appears blue in Bla, but white in Bli.
  - Bla uses self as its first variable, which apparently fools the analyzer into considering it an instance method or something, causing it to properly register the attribute.
  - However, if I enable the `basic` `typeCheckingMode`, Pylance reports that `__new__ override should take a "cls" parameter`
  - Bli uses cls as its first variable, so no report, but then the attribute is considered unknown.
- Also notice that I had to explicitly specify the type of self; if I don't, self is considered untyped (in either case):
![image](https://user-images.githubusercontent.com/574187/98344314-5d7ef180-2013-11eb-8e5e-c516dcdf3b48.png)

## Code Snippet / Additional information
Here's the code from the above screenshot:

```python
class Bla:
	def __new__(self, *args, **kwargs):
		cls = self  # hack to fool the analyzer
		self : Bla = super(Bla, cls).__new__(cls, *args, **kwargs)
		self.new_attr = 1

	def __init__(self):
		self.init_attr = 1

	def some_method(self):
		self.method_attr = 1

	def test(self):
		self.new_attr
		self.init_attr
		self.method_attr


class Bli:
	def __new__(cls, *args, **kwargs):
		self : Bli = super(Bli, cls).__new__(cls, *args, **kwargs)
		self.new_attr = 1

	def __init__(self):
		self.init_attr = 1

	def some_method(self):
		self.method_attr = 1

	def test(self):
		self.new_attr
		self.init_attr
		self.method_attr
```

**Comment by erictraut** [comment]
You are correct. This isn't a supported use case.

The `__new__` method is supposed to allocate a new instance, and the `__init__` method is supposed to initialize it. You're abusing the `__new__` method to initialize a new instance.

Recommended workarounds:
1. Initialize instance variables within the `__init__` method, consistent with the intent behind Python class instantiation and initialization.
2. Declare a class variable and type within the class declaration, like this:

```python
class Bla:
    new_attr: int
```

**Comment by benblo** [comment]
I understand what you're saying re abusing `__new__` vs `__init__`, I guess it depends whether you regard `__new__` as a class or instance method.
I sometimes use `__new__` to isolate some internal functionality in a base class, so derived classes don't have to call `super()` in their own `__init__`... this may or may not be a great practice, but that's my usecase.

---
This prompted me to try another test:
![image](https://user-images.githubusercontent.com/574187/98680480-c3e07880-2361-11eb-8b0b-bcdac2295379.png)
If I add a class variable as you suggest, it appears yellow (scopes inspector says "member"), but if I add it to cls, it also appears blue ("variable").

I still think all this feels inconsistent (though not high priority I'll admit), so if someone's ever fixing that I'd argue _for_ tracking attributes in `__new__`/static methods, just my 2 cents...

---
```python
class Blu:
	def __new__(cls, *args, **kwargs):
		self = super(Blu, cls).__new__(cls, *args, **kwargs)
		cls.new_attr_cls = 1
		self.new_attr_ins = 1

	static_attr = 1

	def test(self):
		self.new_attr_cls
		self.new_attr_ins
		self.static_attr
```

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
