### ISSUE TITLE
go to definition not working

### ISSUE THREAD

**Issue by cs-mshah** [microsoft/pylance-release#5732]
Type: <b>Bug</b>

Go to definition (alt + click) doesn't work for packages installed using:
```shell
pip install -e /path/to/local/package_folder
```

## Steps to reproduce:

Install any packages for example the following:
```
cd /path/to/folder
git clone https://github.com/yxlao/camtools.git
conda activate your_environment
pip install -e /path/to/folder/camtools
```

now clicking on `import camtools ` doesn't go to the `camtools` directory and show the implementation.

Extension version: 2024.4.0
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:14:59.643Z)
OS version: Linux x64 6.5.0-26-generic snap
Modes:
Remote OS version: Linux x64 5.4.0-174-generic
Remote OS version: Linux x64 5.4.0-174-generic

-   Python version (& distribution if applicable, e.g. Anaconda): 
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Unknown
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|Black Formatter|ms-python.black-formatter|2024.2.0|
|Git Graph|mhutchie.git-graph|1.30.0|
|GitHub Copilot|GitHub.copilot|1.178.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.13.1|
|gitignore|codezombiech.gitignore|0.9.0|
|Hide Gitignored|npxms.hide-gitignored|1.1.0|
|JavaScript Debugger|ms-vscode.js-debug|1.87.0|
|Jupyter|ms-toolsai.jupyter|2024.2.0|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.8|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.17|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.5|
|Pylance|ms-python.vscode-pylance|2024.4.1|
|Python|ms-python.python|2024.4.0|
|Python Debugger|ms-python.debugpy|2024.4.0|
|Python Environment Manager|donjayamanne.python-environment-manager|1.2.4|
|Ruff|charliermarsh.ruff|2024.16.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.8|
|Tensorboard|ms-toolsai.tensorboard|2023.10.1002992421|
|YAML|redhat.vscode-yaml|1.14.0|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2853)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 1, 0|
|Memory (System)|15.45GB (6.99GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: VAL-DGX|
|OS|Linux x64 5.4.0-174-generic|
|CPUs|AMD EPYC 7742 64-Core Processor (128 x 1794)|
|Memory (System)|503.54GB (490.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: VAL-DGX|
|OS|Linux x64 5.4.0-174-generic|
|CPUs|AMD EPYC 7742 64-Core Processor (128 x 1777)|
|Memory (System)|503.54GB (490.56GB free)|
|VM|0%|
</details>

**Comment by debonte** [comment]
See https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs

**Comment by cs-mshah** [comment]
I don't think I understand what is to be done. Could you kindly guide me on what to do in terms of VS Code context.

**Comment by debonte** [comment]
@cs-mshah, sorry for my short answer before. I was hoping that our editable install docs would steer you in the right direction, but I can see that they may be too focused on the technical details and not enough on how to solve the common problems. I think I need to do another pass on those.

Anyhow, after doing `pip install -e /path/to/folder/camtools`, if you take a look at the resulting `.pth` file (it's at `src\.venv\Lib\site-packages\__editable__.camtools-0.1.4.pth` in my venv), it contains:

```python
import __editable___camtools_0_1_4_finder; __editable___camtools_0_1_4_finder.install()
```

This installs an import hook that allows the Python import system to find the `camtools` modules at runtime. But Pylance is a static analysis tool (emphasis on static). We don't execute Python code as part of our analysis work, so this style of editable install won't work with Pylance.

If you want the editable install to work with Pylance, you'll need to use compat mode:

```text
pip install -e . --config-settings editable_mode=compat
```

Then the resulting `__editable__.camtools-0.1.4.pth` file will just contain the path to your install, which Pylance can easily handle. In my case the file looks like this:

```text
C:\issues\5732\camtools
```
