### ISSUE TITLE
Type Guard (Narrowing) under Condition Statement Gives error

### ISSUE THREAD

**Issue by dukenmarga** [microsoft/pylance-release#5738]
## Environment data

-   Language Server version: v2024.4.1
-   OS and version: openSuse 15.6
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.12.2

## Code Snippet

When using type guard in a statement outside if condition, I get this error said that the variable can be a None, even if the type has been checked, but the condition is written down outside if line. Is there a way to make this correct that I'm not aware of? I use Pylance extension of VSCode.

```python
def main():
    _ = mult_string_direct_checking("abc", None)
    _ = mult_string_direct_checking(None, "abc")

    _ = mult_string_indirect_checking("abc", None)
    _ = mult_string_indirect_checking(None, "abc")


def mult_string_direct_checking(var1: str | None, var2: str | None) -> str:
    if var1 is None or var2 is None:
        return ""

    # No error here
    return var1 * 2


def mult_string_indirect_checking(var1: str | None, var2: str | None) -> str:
    valid = var1 is None or var2 is None
    if valid:
        return ""

    # This return will get error: Operator "*" not supported for None
    return var1 * 2


```

![image](https://github.com/microsoft/pylance-release/assets/743869/8de64606-a6bc-44ee-89fa-ef8ebf038c8b)

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working as intended here. Please refer to [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced?id=aliased-conditional-expression) for details.
