### ISSUE TITLE
python.analysis.extraPaths stopped working

### ISSUE THREAD

**Issue by rayzinnz** [microsoft/pylance-release#5740]
Type: <b>Bug</b>

# Behaviour

On upgrade to vscode 1.88.0, imports to python files in paths specified in python.analysis.extraPaths no longer resolve.
The all give the warning "Import "xxx" could not be resolved PylancereportMissingImports".
This worked fine on vscode version 1.87.x and all earlier versions.
I have the same issue on both Windows and Linux, on both environments the imports started giving warnings after upgrading to vscode 1.88.0.

## Steps to reproduce:

I've setup a brand new virtual machine, freshly installed vscode, and reproduced the issue like so:

1. Have a python file in a non-standard path
![2024-04-06_07-16-54](https://github.com/microsoft/vscode-python/assets/20865729/4ecd9902-7068-4926-8845-08caa5b8c475)

2. add the path to python.analysis.extraPaths 
![2024-04-06_07-17-31](https://github.com/microsoft/vscode-python/assets/20865729/1fd45dc9-ca6b-43d9-afeb-a9fdfd9762ce)

3. add an import to that path in a python file.
![2024-04-06_07-19-06](https://github.com/microsoft/vscode-python/assets/20865729/05d50cfb-7767-42ce-ab0f-f2675649f8f7)

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.4.0
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:25:57.039Z)
OS version: Linux x64 6.5.0-26-generic
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|Better C++ Syntax|jeff-hykin.better-cpp-syntax|1.17.2|
|Bookmarks|alefragnani.Bookmarks|13.5.0|
|C/C++|ms-vscode.cpptools|1.19.9|
|C/C++ Extension Pack|ms-vscode.cpptools-extension-pack|1.3.0|
|C/C++ Themes|ms-vscode.cpptools-themes|2.0.0|
|CMake|twxs.cmake|0.0.17|
|CMake Tools|ms-vscode.cmake-tools|1.17.17|
|Code Runner|formulahendry.code-runner|0.12.2|
|Debugger for Java|vscjava.vscode-java-debug|0.57.0|
|Dev Containers|ms-vscode-remote.remote-containers|0.354.0|
|Doxygen Documentation Generator|cschlosser.doxdocgen|1.4.0|
|ESLint|dbaeumer.vscode-eslint|2.4.4|
|Extension Pack for Java|vscjava.vscode-java-pack|0.26.0|
|IntelliCode|VisualStudioExptTeam.vscodeintellicode|1.3.1|
|IntelliCode API Usage Examples|VisualStudioExptTeam.intellicode-api-usage-examples|0.2.8|
|isort|ms-python.isort|2023.10.1|
|JavaScript Debugger|ms-vscode.js-debug|1.88.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.2|
|JS CodeFormer: Javascript Refactoring & Code Automation|cmstead.js-codeformer|2.6.1|
|Jupyter|ms-toolsai.jupyter|2024.3.0|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.17|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Just let me click this freaking paths|GrandChris.just-let-me-click-this-freaking-paths|1.0.3|
|Kivy|BattleBas.kivy-vscode|0.5.5|
|Kotlin|fwcd.kotlin|0.2.34|
|Kotlin Language|mathiasfrohlich.Kotlin|1.7.1|
|Language Support for Java(TM) by Red Hat|redhat.java|1.29.0|
|Linux Desktop File support|nico-castell.linux-desktop-file|0.0.21|
|Live Preview|ms-vscode.live-server|0.4.13|
|Maven for Java|vscjava.vscode-maven|0.44.0|
|Project Manager for Java|vscjava.vscode-java-dependency|0.23.6|
|Pylance|ms-python.vscode-pylance|2024.4.1|
|Python|ms-python.python|2024.4.0|
|Python Debugger|ms-python.debugpy|2024.4.0|
|Rainbow CSV|mechatroner.rainbow-csv|3.11.0|
|Remote - SSH|ms-vscode-remote.remote-ssh|0.110.1|
|Remote Explorer|ms-vscode.remote-explorer|0.4.3|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.8|
|Test Runner for Java|vscjava.vscode-java-test|0.41.0|
|WSL|ms-vscode-remote.remote-wsl|0.88.0|
|XML|redhat.vscode-xml|0.26.1|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1920X 12-Core Processor (24 x 2125)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.18GB (23.82GB free)|
|Process Argv|--unity-launch /home/ray/MEGA/Rays/Programming/weka/tabular_playground/2024-04/playground_2024-04.py --crash-reporter-id f601e509-4314-4063-818f-84a218fd76e9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572

```

</details>

**Comment by debonte** [comment]
This morning there was a comment on an old Pyright bug about `extraPaths` behavior regressing. Might be related --  https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674

**Comment by heejaechang** [comment]
I can't repro the issue. can you provide us log (https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs) so we can see how we configured the pylance server?

**Comment by rayzinnz** [comment]
[Pylance language server Trace Logs.log](https://github.com/microsoft/pylance-release/files/14924609/Pylance.language.server.Trace.Logs.log)

Please see trace logs attached.

**Comment by debonte** [comment]
```text
2024-04-10 10:57:08.132 [info] [Info  - 10:57:08 AM] (3756) Search paths for 
2024-04-10 10:57:08.152 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\typeshed-fallback\stdlib
2024-04-10 10:57:08.153 [info] [Info  - 10:57:08 AM] (3756)   
2024-04-10 10:57:08.156 [info] [Info  - 10:57:08 AM] (3756)   
2024-04-10 10:57:08.156 [info] [Info  - 10:57:08 AM] (3756)   
2024-04-10 10:57:08.157 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\typeshed-fallback\stubs\...
2024-04-10 10:57:08.157 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\bundled\stubs
2024-04-10 10:57:08.157 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\AppData\Local\Programs\Python\Python312\DLLs
2024-04-10 10:57:08.157 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\AppData\Local\Programs\Python\Python312\Lib
2024-04-10 10:57:08.158 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\AppData\Local\Programs\Python\Python312
2024-04-10 10:57:08.158 [info] [Info  - 10:57:08 AM] (3756)   c:\Users\ray\AppData\Local\Programs\Python\Python312\Lib\site-packages
```

Some of the paths (extraPaths I assume) are blank in the log, as is the workspace path after "Search paths for".

This is the same symptom seen in the logs of https://github.com/microsoft/pylance-release/issues/5720. And I'm guessing is what @FindDefinition was referring to in https://github.com/microsoft/pyright/issues/7016#issuecomment-2042476674.

**Comment by heejaechang** [comment]
ah. this is for default workspace. let me try repro.

**Comment by rangedsp** [comment]
Hey @heejaechang, I see that this has been rolled into pyright 1.1.361, but today's release of pylance 2024.5.1 only included changes up to pyright 1.1.360. 

Could you please bump that in a prerelease build?

**Comment by rchiodo** [comment]
> I see that this has been rolled into pyright 1.1.361

I don't believe that's true. Heejae's commit is in 1.1.360. Are you still reproducing the problem?

**Comment by rangedsp** [comment]
@rchiodo you are right, I misread the version number. Yes I am still having this issue, rolling back to v2024.3.2 is the only way for pylance to pick up my extraPaths (site-package installed by pyenv). 

I'll create a new issue with more details.

**Comment by rayzinnz** [comment]
@rangedsp At least for me this is working on vscode, I am using "Pylance" pre-release versions, and this started working from pylance version v2024.4.104. My current version is v2024.5.1.
