### ISSUE TITLE
report undefined error on builtin functions

### ISSUE THREAD

**Issue by Aya-Yang** [microsoft/pylance-release#5746]
<h3> Environment data </h3>

-   Language Server version: 2024.4.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 2.7.16
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

![image](https://github.com/microsoft/pylance-release/assets/12084255/37a72ade-178c-453d-bfa7-02302defd548)

**Comment by laggardkernel** [comment]
From my experience, it seems it only happens on Python 2 project. Downgrading Pylance extension to v2024.3.2 resolves the warnings.

What LSP should I use for a Python 2 project? Any idea?

**Comment by debonte** [comment]
Please provide a complete, but minimal, code sample that reproduces this behavior.
