### ISSUE TITLE
the more cells in jupyter notebook, the more file to analyze in pylance

### ISSUE THREAD

**Issue by swg168** [microsoft/pylance-release#5748]
## Environment data

-   Language Server version: v2024.4.100 (pre-release)
-   OS and version: Windows11
-   Python version (& distribution if applicable, e.g. Anaconda): miniconda python 3.12

## Code Snippet

```python
print("Hello, World!")
```

## Repro Steps

1. open a new jupyter notebook in vscode
2. just run print("Hello, World!") in every cell
3.the more cells in jupyter notebook, the more files to analyze in pylance
4. the jupyter will be slow

## Expected behavior

I don't understand why I just run the same simple code in every cell, the files of pylance to analyze will be increased. I expect it will be 1, because I just run the "print".

## Actual behavior

In fact , the number of files is close to the number of cells.

## Logs

```
XXX
```

**Comment by StellaHuang95** [comment]
Not sure what you mean by "more files to analyze". Can you share your log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)? Thanks!

**Comment by swg168** [comment]
With the increase of cells, even if I just run very simple code in the cell, such as the “Print” , the number of files to be analyzed in the lower left corner will continue to increase, and the analysis of time is getting longer and longer. .As a result, my running code in Jupyter became very slow, and even Pylance would fail.


![20240412_170700_244_copy](https://github.com/microsoft/pylance-release/assets/109449633/66b3e319-4aad-4917-99ef-80cb4e161d9b)



`2024-04-12 17:15:06.404 [info] [Info  - 5:15:06 PM] (7660) [BG(10)] Long operation: checking: file:///d%3A/Desktop/Within_Strategy_Shifts/within_strategy_shift/wang/final_hmm_paper.ipynb.py#X40sZmlsZQ%3D%3D (3033ms)
2024-04-12 17:15:06.429 [info] [Info  - 5:15:06 PM] (7660) [BG(10)] Long operation: analyzing: file:///d%3A/Desktop/Within_Strategy_Shifts/within_strategy_shift/wang/final_hmm_paper.ipynb.py#X40sZmlsZQ%3D%3D (3033ms)
2024-04-12 17:15:08.826 [info] [Info  - 5:15:08 PM] (7660) [BG(10)] Long operation: analyzing: file:///d%3A/Desktop/Within_Strategy_Shifts/within_strategy_shift/wang/final_hmm_paper.ipynb.py#pylancePrefixCell (10581ms)
2024-04-12 17:15:29.523 [info] [Info  - 5:15:29 PM] (7660) [BG(10)] Long operation: analyzing: file:///d%3A/Desktop/Within_Strategy_Shifts/within_strategy_shift/wang/final_hmm_paper.ipynb.py#pylancePrefixCell (3972ms)
2024-04-12 17:15:36.934 [info] [Info  - 5:15:36 PM] (7660) [BG(10)] Long operation: analyzing: file:///d%3A/Desktop/Within_Strategy_Shifts/within_strategy_shift/wang/final_hmm_paper.ipynb.py#pylancePrefixCell (4093ms)`

**Comment by StellaHuang95** [comment]
I see, the behavior you're seeing is related to https://github.com/microsoft/pylance-release/issues/5173. The `File to Analyze` count is actually the `Cells to Analyze` count. Simple print statements shouldn't cause pylance to fail though. Is your code in a public repo or can you provide the code sample that caused the issue?

**Comment by ale-dg** [comment]
Hi @StellaHuang95 

As I have run into similar issues with the stable release, please find below the log by just opening a large notebook. Pylance even crashed right away (this has not happened with the pre-release though, nor with the versions installed in the Insiders)

Below the log and the book I used.

Best

[Pylance.log](https://github.com/microsoft/pylance-release/files/15003476/Pylance.log)

[penguins_classification.ipynb.zip](https://github.com/microsoft/pylance-release/files/15003477/penguins_classification.ipynb.zip)

**Comment by ale-dg** [comment]
Hi,

Just for not leaving any stone unturned, I have tried to do it with these settings and a different notebook:

```json
{
  "python.analysis.logLevel": "Trace",
  "python.analysis.indexing": false,
  "python.analysis.typeCheckingMode": "off",
  "python.analysis.enablePytestSupport": false,
  "python.analysis.inlayHints.pytestParameters": false,
  "python.analysis.inlayHints.callArgumentNames": "off",
  "python.analysis.inlayHints.functionReturnTypes": false,
  "python.analysis.inlayHints.variableTypes": false,
  "python.analysis.autoImportCompletions": false,
  "python.analysis.useLibraryCodeForTypes": false,
  "python.analysis.diagnosticMode": "openFilesOnly",
}
```
And Pylance still crashed... see the log below.

Best

[test_notebook_pylance.log](https://github.com/microsoft/pylance-release/files/15003653/test_notebook_pylance.log)

**Comment by rchiodo** [comment]
@ale-dg your issue should be this one:
https://github.com/microsoft/pylance-release/issues/5440

Your notebook is just pulling in so much we run out of memory. As a workaround, you could apply the suggested fix as described in the bug (or update to our latest prerelease as we've made some adjustments to the amount of memory we allocate).

I don't believe your issue is the same as the original poster in this isuse, where 'files to analyze' is incorrectly identified.

**Comment by ale-dg** [comment]
@rchiodo thanks for the quick answer. I'll use the prerelease then within insiders, although I must mention that I also saw a similar window as the screenshot above saying "125 files to be analysed", hence I thought it might be similar.

**Comment by rchiodo** [comment]
Sorry I removed waiting for user response, but Stella is actually waiting for @swg168 to provide a repro for the crash mentioned, not for the files to analyze count being off.

**Comment by heejaechang** [comment]
>  "125 files to be analysed"

internally, each cell is treated as a file, that implementation detail might be leaking out in status bar. we might want to change the wording to `cells/files` or just treat cells from same notebook to 1 file and just say 1 files to be analyzed.

**Comment by bhvieira** [comment]
Why does Pylance have to reanalyze cells that were not changed? Is it too eager to ignore the cache of previously analyzed cells?

**Comment by heejaechang** [comment]
unlike regular python files, cells implicitly depend on each other. for example, if you have `def foo():...` on `cell 2`, `cell 3` can use `foo` without explicit `from xxx import foo`. what that means is that, if you change `cell 2` such as `change foo to foo1`, we will need to re-analyze `cell 3` and after to find out impact of the change (such as `foo` no longer exists). Since it has similar impact as all those cells having `from xxx import *` of previous cells. regular file will have similar behavior if all those files has `from xxx import *` each other. 

one could argue that then, we only need to re-analyze cells after one that has changed, but that is not true since there are some stuff that will be impacted by changes in depending cells such as if one has `import os` in `cell1` and use the `os` in `cell10`, but removed it later, then we need to fade out `import os` in `cell1`

**Comment by heejaechang** [comment]
if you think you are having perf problem, I think best way for us to take a look is you sharing this to us (https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-cpuprofiles)
