### ISSUE TITLE
pandas read_csv() parse_dates parameter has incorrect type

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#576]
## Environment data

-   Language Server version: 2020.11.0
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.8 (Anaconda)

## Expected behaviour

No bug

## Actual behaviour

```
df = pd.read_csv("foo.csv", parse_dates=["Start", "Finish"])
```
reports 
```
No overloads for "pd.read_csv("foo.csv", parse_dates=["Start", "Finish"])" match parameters
  Argument types: (Literal['foo.csv'], List[str])
```

The issue here is that the `parse_dates` argument can be a number of things, including a list of column names.

## Code Snippet / Additional information

Partial fix to `pandas/io/parsers.pyi` 

```
 diff parsers.pyi.ORIG parsers.pyi
37c37
<     parse_dates: bool = ...,
---
>     parse_dates: Union[bool, List[int], List[str]] = ...,
374c374
<     parse_dates: bool = ...,
---
>     parse_dates: Union[bool, List[int], List[str]] = ...,
427c427
<     parse_dates: bool = ...,
---
>     parse_dates: Union[bool, List[int], List[str]] = ...,
764c764
<     parse_dates: bool = ...,
---
>     parse_dates: Union[bool, List[int], List[str]] = ...,
```

NOTE:  This is not all the possible argument types for `parse_dates`, but the above solves this problem.

**Comment by jakebailey** [comment]
Thanks again for the patch.

This issue has been fixed in version 2020.11.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020111-11-november-2020
