### ISSUE TITLE
fails to activate on startup half the time

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#5766]
From marketplace reviews:
> Lev Knoblock
9 hours ago
Thanks, Microsoft, for providing yet another crappy product :)
Runs horribly, fails to activate on startup half the time, and just overall a poor experience.

**Comment by rchiodo** [comment]
Lev if you could give any more information we'd love to fix the problem. A log as described here would help:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
