### ISSUE TITLE
Pylance fails to find source files on vscode.dev

### ISSUE THREAD

**Issue by chiaolinghong** [microsoft/pylance-release#5768]
## Environment data

-   Language Server version: v2024.4.1
-   OS and version: Windows 10 / Chrome browser
-   Python version (& distribution if applicable, e.g. Anaconda): v2024.4.1

## Repro Steps

1. Open vdcode.dev on browser
2. Click "Open Folder" in the Explorer tab
3. Open a folder with python files
4. Click yes to trust the user and access files.
5. Open up Output (Python Language Server)

## Expected behavior

Pylance should be able to read the source files and allow **import** usage

## Actual behavior

The Explorer shows the correct files, however the Pylance log cannot find the source directory.
https://github.com/microsoft/pylance-release/issues/2850#issuecomment-1137899418 also spotted this problem and suggested a solution for synchronous file system access in needed. Any information on plans to have this fixed?

## Logs

```
(Client) Pylance async client (2024.4.1) started with python extension (2024.4.1)
[Info  - 10:10:35 AM] Running pylance browser async server with options {
    "distUrl": "https://ms-python.vscode-unpkg.net/ms-python/vscode-pylance/2024.4.1/extension/dist",
    "cancellationMethod": "sharedArray",
    "enableSync": false,
    "prefetchRegexes": [
        ".*/stdlib/.*"
    ]
}
[Info  - 10:10:36 AM] Pylance language server 2024.4.1 (pyright version 1.1.356, commit 6652c4a8) starting
[Info  - 10:10:36 AM] Server root directory: file:///
[Info  - 10:10:36 AM] Starting service instance "python-test"
[Error - 10:10:36 AM] File or directory "/python-test" does not exist.
[Info  - 10:10:36 AM] No source files found.
```

**Comment by chiaolinghong** [comment]
This comment explains the issue. https://github.com/microsoft/pylance-release/issues/4926#issuecomment-1760589422
Enabling `"python.analysis.enableSyncServer"` to `true` allows import to work as expected.

**Comment by rchiodo** [comment]
This is actually by design. Pylance in vscode.dev is currently limited. The 'enableSyncServer' is something we're experimenting with that might support more functionality in the future.
