### ISSUE TITLE
django: Wrong return type on `django.contrib.auth.get_user_model` (tracking)

### ISSUE THREAD

**Issue by yankyhoffman** [microsoft/pylance-release#577]
In Django the [recommended](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#django.contrib.auth.get_user_model) way to work with users is to call `django.contrib.auth.get_user_model` to get the model set to manage users.

To add a new user to the database one would create a new instance of the class returned by `get_user_model` and then set the password using the classes method `set_password`.

The current return type is a generic `models.Model` while the `set_password` is a method defined in `AbstractBaseUser` which is the model recommended to be inherited when extending the base user functionality.

![image](https://user-images.githubusercontent.com/41123800/98397211-ff5f0800-202c-11eb-9965-4b9c5e9b962c.png)

I opened a [PR](https://github.com/typeddjango/django-stubs/pull/523) in the django-stubs repo, and I opened this issue here to track it as it affects Pylance as well.

**Comment by judej** [comment]
This enhancement request has been open for a while. Closing old issue because of lack of upvotes.
