### ISSUE TITLE
Autoadding a space with tab indentation

### ISSUE THREAD

**Issue by rayzinnz** [microsoft/pylance-release#5772]
Type: <b>Bug</b>

# Behaviour

With a python file set to tab indentation,
When pressing enter to make a knew line after a comment,
The indentation tab is automatically deleted and replaced with a space. Being invisible, the extra space causes indentation incosistencies in some cases e.g. adding or pasting code later on.

## Steps to reproduce:

1. Make a new python file, set Indentation type to Tab in vscode
2. Type this into the file:
```python
if 1==1:
	a=1
	#a comment
```
4. At the end of the "#a comment" press Enter to go to the next line. The line will auto indent with a tab, which is immediately removed and replaced with a space. Pressing Ctrl+z will remove the space and put the tab back.

![image](https://github.com/microsoft/vscode-python/assets/20865729/e67331d7-178d-4522-96b3-7e1775e458bd)

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.4.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:34:12.840Z)
OS version: Linux x64 6.5.0-27-generic
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.6
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|Better C++ Syntax|jeff-hykin.better-cpp-syntax|1.17.2|
|Bookmarks|alefragnani.Bookmarks|13.5.0|
|C/C++|ms-vscode.cpptools|1.19.9|
|C/C++ Extension Pack|ms-vscode.cpptools-extension-pack|1.3.0|
|C/C++ Themes|ms-vscode.cpptools-themes|2.0.0|
|CMake|twxs.cmake|0.0.17|
|CMake Tools|ms-vscode.cmake-tools|1.17.17|
|Code Runner|formulahendry.code-runner|0.12.2|
|Debugger for Java|vscjava.vscode-java-debug|0.57.0|
|Dev Containers|ms-vscode-remote.remote-containers|0.354.0|
|Doxygen Documentation Generator|cschlosser.doxdocgen|1.4.0|
|ESLint|dbaeumer.vscode-eslint|2.4.4|
|Extension Pack for Java|vscjava.vscode-java-pack|0.26.0|
|IntelliCode|VisualStudioExptTeam.vscodeintellicode|1.3.1|
|IntelliCode API Usage Examples|VisualStudioExptTeam.intellicode-api-usage-examples|0.2.8|
|isort|ms-python.isort|2023.10.1|
|JavaScript Debugger|ms-vscode.js-debug|1.88.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.2|
|JS CodeFormer: Javascript Refactoring & Code Automation|cmstead.js-codeformer|2.6.1|
|Jupyter|ms-toolsai.jupyter|2024.3.1|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.17|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Just let me click this freaking paths|GrandChris.just-let-me-click-this-freaking-paths|1.0.3|
|Kivy|BattleBas.kivy-vscode|0.5.5|
|Kotlin|fwcd.kotlin|0.2.34|
|Kotlin Language|mathiasfrohlich.Kotlin|1.7.1|
|Language Support for Java(TM) by Red Hat|redhat.java|1.29.0|
|Linux Desktop File support|nico-castell.linux-desktop-file|0.0.21|
|Live Preview|ms-vscode.live-server|0.4.13|
|Maven for Java|vscjava.vscode-maven|0.44.0|
|Project Manager for Java|vscjava.vscode-java-dependency|0.23.6|
|Pylance|ms-python.vscode-pylance|2024.4.1|
|Python|ms-python.python|2024.4.1|
|Python Debugger|ms-python.debugpy|2024.4.0|
|Rainbow CSV|mechatroner.rainbow-csv|3.11.0|
|Remote - SSH|ms-vscode-remote.remote-ssh|0.110.1|
|Remote Explorer|ms-vscode.remote-explorer|0.4.3|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.8|
|Test Runner for Java|vscjava.vscode-java-test|0.41.0|
|WSL|ms-vscode-remote.remote-wsl|0.88.0|
|XML|redhat.vscode-xml|0.26.1|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1920X 12-Core Processor (24 x 2053)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.18GB (24.21GB free)|
|Process Argv|--unity-launch --crash-reporter-id f601e509-4314-4063-818f-84a218fd76e9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
0ee40948:31013168

```

</details>

**Comment by rchiodo** [comment]
I believe this issue is fixed in our latest prerelease - 2024.4.101. I can no longer reproduce the issue there.
