### ISSUE TITLE
Unexpected "Code is unreachable"

### ISSUE THREAD

**Issue by s-inu** [microsoft/pylance-release#5776]
## Environment data

- Language Server version: v2024.4.1
- OS and version: Win10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.8

## Code Snippet

```python
def problem_json(id: str | int, title: str = None) -> str:
    assert is_int(id), f"{id}: is not an int"
    id = int(id)

    if title is not None:
        assert title.strip() != "", "empty title"
        title = filename_safe(title)
        return f"problem_{id}_{title}.json"

    return f"problem_{id:03}.json"

print(problem_json(1)) # problem_001.json
```

## Expected behavior

The last line `return f"problem_{id:03}.json"` should be reachable

## Actual behavior

Code is unreachable Pylance

![image](https://github.com/microsoft/pylance-release/assets/63855812/6b7e8154-3f90-4b81-bd70-52112660b751)

**Comment by rchiodo** [comment]
You haven't correctly set the type for the title. The way you have it the typechecker always thinks it's a string (and never None).

This fixes the issue:

```python
def problem_json(id: str | int, title: str | None = None) -> str:
    assert is_int(id), f"{id}: is not an int"
    id = int(id)

    if title is not None:
        assert title.strip() != "", "empty title"
        title = filename_safe(title)
        return f"problem_{id}_{title}.json"

    return f"problem_{id:03}.json"

print(problem_json(1)) # problem_001.json
```
