### ISSUE TITLE
sys.version_info reachability

### ISSUE THREAD

**Issue by fny** [microsoft/pylance-release#5780]
When using `sys.version_info` to do a version check, I receive a notice that the code which follows is unreachable.

```python
def ensure_python_3_11_plus() -> None:
    """
    Are we running python 3.11+?
    """
    if not sys.version_info >= (3, 11):
        raise Exit("Python 3.11+ is required.") # <--- Unreachable even in (3, 11) is changed to (3, 99)
```
<img width="386" alt="image" src="https://github.com/microsoft/pylance-release/assets/346068/15b45126-2231-42f1-84cf-4f68796abfec">

Ideally, there shouldn't be such a message

## Environment data

-   Language Server version:  Pylance async client (2023.12.1) started with python extension (2024.4.1)
-   OS and version: macOS 14.1.1
-   Python version: 3.11.8

## Code Snippet

```python
def ensure_python_3_11_plus() -> None:
    """
    Are we running python 3.11+?
    """
    if not sys.version_info >= (3, 11):
        raise Exit("Python 3.11+ is required.")
```
<img width="386" alt="image" src="https://github.com/microsoft/pylance-release/assets/346068/15b45126-2231-42f1-84cf-4f68796abfec">

**Comment by rchiodo** [comment]
This is working as designed for me.

This shows unreachable (I'm using Python 3.11.9):

```python
import sys

def ensure_python_3_11_plus() -> None:
    """
    Are we running python 3.11+?
    """
    if not sys.version_info >= (3, 11):
        raise Exit("Python 3.11+ is required.")
```

This does not show unreachable:

```python
import sys

def ensure_python_3_11_plus() -> None:
    """
    Are we running python 3.11+?
    """
    if not sys.version_info >= (3, 99):
        raise Exit("Python 3.11+ is required.")
```

You might want to update your Pylance version. 2023.12.11 is kind of old. But even if I use that version it works for me.
