### ISSUE TITLE
Pylance No parameter named "name" for existing parameter of instance of HttpSession of Locust

### ISSUE THREAD

**Issue by Akopov4** [microsoft/pylance-release#5786]
<h3> Environment data </h3>

-   Language Server version: 2024.4.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): python3.8.19, pip 24.0
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python

import time
from locust import HttpUser, task, between


class HelloWorldUser(HttpUser):
    wait_time = between 
    @task
    def hello_world(self):
        self.client.get("/hello")
        self.client.get("/world")
    
    @task(3)
    def view_items(self):
        for item_id in range(10):
            self.client.get(f"/item&id={item_id}", name="/item")
            time.sleep(1)
    
    def on_start(self) -> None:
        self.client.post("/login", json={"username":"foo", "password":"bar"})

```

<h3> Repro Steps </h3>
put code from example to editor
<h3> Expected behavior </h3>

self.client is an instance of class HttpSession
from .venv/lib/python3.8/site-packages/locust/clients.py   module

according to docstring: 

> :param name: (optional) An argument that can be specified to use as label in Locust's statistics instead of the URL path.
>                  This can be used to group different URL's that are requested into a single entry in Locust's statistics.

<h3> Actual behavior </h3>

No error should be

<h3> Logs </h3>

```


XXX
```
[vscode_log.txt](https://github.com/microsoft/pylance-release/files/15055316/vscode_log.txt)
[requirements.txt](https://github.com/microsoft/pylance-release/files/15055317/requirements.txt)

**Comment by debonte** [comment]
Pylance is behaving correctly here. Despite the documentation in `locust`, if you Go to Declaration on `get` you'll see that the stub (from the `requests` packag) does not include `name` parameter. 

There's already an issue tracking this in the `locust` issue tracker: https://github.com/locustio/locust/issues/2563. Please follow that for updates.
