### ISSUE TITLE
"code unreachable" triggered by optional import

### ISSUE THREAD

**Issue by emanspeaks** [microsoft/pylance-release#579]
Consider the following code snippet from a file called foo.py:

```python
try:
    import some_optional_dependency
except ImportError:
    def foo(*args, **kwargs):
        raise NotImplementedError
else:
    def foo(*args, **kwargs) -> bool:
        return True
```

In another file that imports foo, all the lines following a call to foo are grayed out and marked "code unreachable."  By peeking the definition, it takes me to the definition inside the except block instead of the expected actual definition.  This implies to me that pylance thinks that exception will be raised, though my environment indeed has the `some_optional_dependency` installed.

If pylance were to rely on the existence of the package on my machine, this would create seemingly inconsistent behavior between two separate users who may or may not have the same environment.  I suppose this is why the design decision has been made to treat this case as if the ImportError always raises for consistency.  However, the implication of this decision is that now it thinks my code in another file is unreachable when there is code in the second file that should guarantee that this package is present by the time the call is reached that pylance believes would fail.

What is the correct way to handle this situation so that my code is not erroneously marked unreachable while protecting for consistent behavior for users in different environments?  Is there a setting or flag that could be used to toggle the behavior so I could evaluate both code paths with pylance?

**Comment by erictraut** [comment]
This issue isn't because `foo` is declared within an except block. It's because 1) foo has no declared return type, and 2) the inferred type of foo is NoReturn because all code paths raise an exception.

You can work around the issue by adding a return type annotation `-> bool` to the `foo` function declaration. That way, pylance won't need to infer the return type based on the body of the function.

**Comment by jakebailey** [comment]
There hasn't been an update here in about a month; if the above suggestion doesn't help we can reopen this.
