### ISSUE TITLE
Can pylance hint the add-to-builtiins vars and libs ?

### ISSUE THREAD

**Issue by Alex-Beng** [microsoft/pylance-release#5792]
I have checked the pylance's issues. the https://github.com/microsoft/pylance-release/issues/2010 suggested to use protocols for runtime-imported librarys.

In my case, I have a lists of library, and they are imported in runtime too. Also, they are import as renamed, like:

```python
global2modules = [
    ("CONST", "xxx.const"),
    ("UTIL", "xxx.util"),
]

for global_name, module_name in global2modules:
    module = imoprtlib.import_module(module_name)
    __builtins__[global_name] = module
```

As well as the vars:
```python
SETTINGS = "xxx"

for name, value in vars().items():
    __builtins__[name] = value
```

There are so many libs, which make it write protocols a hard work. Also idk how to due with the vars.
Is it possible to customize the __builtins__, in order to make the pylance work in edition ?

**Comment by erictraut** [comment]
Dynamically patching the builtins namespace is generally a very bad idea. It's much better to use the normal import system to import symbols into individual module namespaces.

If you can't do that for some reason, here's [a technique](https://microsoft.github.io/pyright/#/builtins) that may meet your needs.

**Comment by Alex-Beng** [comment]
Thanks a lot! BTW someone just told me this way, i just wonder close the issue

**Comment by Alex-Beng** [comment]
The solution is to use pylance config  named `Stub Path` and create a `__builtins__.pyi`, which in my case is created by a simple codegen script.
![image](https://github.com/microsoft/pylance-release/assets/30763045/f4d9c0ae-dc5a-4b1e-a502-665a74c43cfc)
