### ISSUE TITLE
notebook cells sometimes get cycle.

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5798]
we are getting this report time to time

![image](https://github.com/microsoft/pylance-release/assets/1333179/c16cb770-e0a8-4992-9a58-56a69c616f71)

looks like there is a code path where cell gets circular dependency

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246101-20-June-2024-PreRelease)
