### ISSUE TITLE
Pylance (reportMissingImports) for import that's inside .so file

### ISSUE THREAD

**Issue by cheeyongteh** [microsoft/pylance-release#580]
Hi,

I have an .so file (C++). Inside the .so file there are exports like the following

00000000007c0220 T com::lchclearnet::swapclear::smart::SMARTDataProviderFactory::SMARTDataProviderFactory(java::lang::String const&)

so in the python script I will do

import lch_smart #this will load the .so file, Pylance find the import for this

then I will able to do the following

from com.lchclearnet.swapclear.smart import SMARTDataProviderFactory #Pylance fail to find the import for this

Does Pylance supports 'import' from a .so file?

Thanks,

Stephen

**Comment by jakebailey** [comment]
We should be able to resolve that the module exists (so long as it's placed where python would find it), though we won't know its contents as the only way to know is to actually execute the code. A stub would be the best way to get more enhanced information in that case.

Are you finding that it isn't working, or is this just a question as to the support?

**Comment by cheeyongteh** [comment]
Hi, Pylance is able to find the module but not able to find the class inside the .so. Like you mentioned I think I will need a stub for the .so. Thanks

**Comment by jakebailey** [comment]
Right; unfortunately trying to load random compiled modules that exist within the workspace is a bit of a bad idea (as we don't really want to run your code to inspect it; who knows what it does). For libraries we may do better here, but for compiled modules within the workspace the behavior you're seeing is expected (doesn't complain about the import, but doesn't know what's in it either).
