### ISSUE TITLE
Doesn't recognize dictionary update() method when selecting a nested dictionary 

### ISSUE THREAD

**Issue by edif** [microsoft/pylance-release#581]
![Screenshot 2020-11-07 023448](https://user-images.githubusercontent.com/6934810/98429953-d9277f80-20a1-11eb-87f2-c58a23cc4161.png)

**Comment by erictraut** [comment]
You are providing no type information, so the types are unknown. A static type checker cannot know that `th` is a nested dictionary if you don't provide this information.

Here's what it might look like if you added type annotations:

```python
def regfinal(th: Dict[str, Dict[str, bool]], e: str, score: bool = True):
    th[e].update({"score": score})
    return th[e]
```

**Comment by edif** [comment]
You right! 😅
I was trying to see if the **Wizard** 🔮 could guess what I wanted before I telling him!!! 
My bad🙈🙉🙊
