### ISSUE TITLE
quick fix can't detect reportlab package

### ISSUE THREAD

**Issue by HsinM** [microsoft/pylance-release#5817]
## Environment data

-   Language Server version: Pylance async client (2024.4.1)
-   OS and version: WIndows 10 1909 18363.752
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.8 & conda 4.11.0
-   Reportlab package version: 4.2.0

## Code Snippet

```python
# functions sample
Frame
tqdm
```

## Repro Steps

1. install reportlab and tqdm (for sample) packages: `pip install reportlab tqdm`.
2. open empty code file.
3. try use functions in reportlab package.

## Expected behavior

Quick-fix can detect function and give a tip to import it, like tqdm.
![image](https://github.com/microsoft/pylance-release/assets/16590829/594a0c6c-5a43-47d2-89ec-8f8cf86ec8dc)

## Actual behavior

Quick-fix not show corrent tip about reportlab package.
![image](https://github.com/microsoft/pylance-release/assets/16590829/0826b7b5-3c7a-4f81-a1ce-057cba4d44e4)

But manual import ths package is fully functional...

**Comment by debonte** [comment]
By default, Pylance only indexes top-level modules (depth = 1). You can increase the indexing depth for particular packages via the `python.analysis.packageIndexDepths` config setting.

If you add the following setting you'll see `reportlab.platypus.frames.Frame` appear in the completion suggestions:

```json
    "python.analysis.packageIndexDepths": [
        {
            "name": "reportlab",
            "depth": 3
        }
    ]
```

**Comment by HsinM** [comment]
@debonte It works fine after applying `packageIndexDepths` setting, Thanks a lot!

![image](https://github.com/microsoft/pylance-release/assets/16590829/821bcb09-b05e-4ad3-bb5f-783e3d9265f8)
