### ISSUE TITLE
code unreachable -- but it's not

### ISSUE THREAD

**Issue by mMerlin** [microsoft/pylance-release#5818]
Pylance does not crash, but why would it think that the code is unreachable? The previous return statement is in a conditional bock. There are no complaints for other very similar code blocks in the project.

Environment information

Pylance v2024.4.1
vscode
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:34:12.840Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.7-100.fc38.x86_64
% uname -srvmo
Linux 6.8.7-100.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:34:28 UTC 2024 x86_64 GNU/Linux
% cat /etc/os-release | grep "PRETTY"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
pipenv virtual environment
Python 3.8.19

Here a small simplified extract that pylance still does complain about.
```python
# test_pylance_issue.py

"""test unreachable code complaint from pylance"""

def connect(secrets: list = None, timeout_s:int=10) -> int:
    """minimal extract"""
    if secrets is not None:
        return 1



    if timeout_s < 0:
        raise ValueError('There are no AP credentials defined for connections.')
    return 0
```

![Screenshot from 2024-04-27 22-36-09](https://github.com/microsoft/pylance-release/assets/918823/d646788e-a26f-46b3-aee2-e4133b5a7f3f)

**Comment by erictraut** [comment]
This is because you have an error in your type annotation. You've indicated that `secrets` must be a `list`, but it looks like you intend for it to also accept `None`. If so, you should use the annotation `list | None`.

**Comment by mMerlin** [comment]
Well that was easy … if not intuitive based on the error message.

What I did to fix it in the original code, was change the annotation to Optional[SecretsT], where SecretsT is defined as a List[«another data type»]

**Comment by erictraut** [comment]
@mMerlin, pylance will provide error messages for cases like this, but you need to enable type checking mode (i.e. set `python.analysis.typeCheckingMode` to "basic"). Or if you don't want to see all type-related errors, you can enable just the `reportArgumentType` diagnostic rule. 

Here's what it looks like with this enabled. Note the red squiggle when you attempt to assign a default value of `None` to the `secrets` parameter.

![image](https://github.com/microsoft/pylance-release/assets/7040122/23840834-59b7-49d0-a802-c0a909221d80)
