### ISSUE TITLE
Quick fixes for type conversions

### ISSUE THREAD

**Issue by rhewy** [microsoft/pylance-release#582]
Have quick fixes for the basic type conversions e.g. float(), int(), str()

**Pylance** 2020.11.0 with strict for Type Checking Mode

In the image below, be able to wrap all the arguments in float()

![image](https://user-images.githubusercontent.com/4993063/98447059-dabf6a80-20d6-11eb-94e2-f9468e73e916.png)

**Python code to test is below:**
```python
def dist(x1:float, y1:float, x2:float, y2:float) -> float:
    return 1.0

x1 = '1'
y1 = '1'
x2 = '1'
y2 = '1'

theDist = dist(x1, y1, x2, y2)
```

**Desired result:**
```python
theDist = dist(float(x1), float(y1), float(x2), float(y2))
```

**Comment by judej** [comment]
This request has been open for a while. Closing old issue because of lack of upvotes.
