### ISSUE TITLE
Show Type Hierarchy shows no results for types declared in notebooks

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5832]
## Environment data
-   Language Server version: 2024.4.105
-   OS and version: Windows 11
-   Python version: 3.12.1

## Code Snippet
```python
class Base:
    pass

class Derived(Base):
    pass
```

## Repro Steps

1. Create a new notebook.
2. Paste the code above in the first cell
3. Right-click on `Base` and select "Show Type Hierarchy"

## Expected behavior
Derived is listed as a subtype.

![image](https://github.com/microsoft/pylance-release/assets/12820898/0347ae9a-cd1a-4745-a5b4-9fa75280d6e7)

## Actual behavior
No subtypes shown. This is because we're not decoding the URI within the `TypeHierarchySubtypesParams` and we attempt to use that within `TypeHierarchyProvider`.

![image](https://github.com/microsoft/pylance-release/assets/12820898/7692b01f-5f9d-45fa-bfa9-fa7d8b7b2758)

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.5.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20245102-23-May-2024-PreRelease)
