### ISSUE TITLE
VS Code flags "always" as an invalid value for `python.analysis.perfReporting`

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5834]
## Environment data

-   Language Server version: 2024.4.105

## Repro steps

1. Open `settings.json`.
2. Set `"python.analysis.perfReporting": "always"`

## Expected behavior
`"always"` is considered a valid value.

## Actual behavior
![image](https://github.com/microsoft/pyrx/assets/12820898/d3285493-0afd-4c8c-8db2-7506c61d6da0)

Maybe `python.analysis.perfReporting` should be an enum with values like `"never"`, `"once"`, and `"always"`, rather than a boolean?

**Comment by heejaechang** [comment]
it is by design. the whole option is for testing. it will go away once feature rollout is done. and especially `always` is for testing since otherwise, there is no way to test it.
