### ISSUE TITLE
Expand Callable Protocols in type tooltips of variables explicitly typed using a Callable Protocol class's name

### ISSUE THREAD

**Issue by munael** [microsoft/pylance-release#584]
See: https://mypy.readthedocs.io/en/latest/protocols.html#callback-protocols

Example:
```py
from typing import Callable, TypeVar
from typing_extensions import Protocol

T = TypeVar('T')

class Copy(Protocol):
    def __call__(self, __origin: T) -> T: ...

copy_a: Callable[[T], T]
copy_b: Copy

copy_a = copy_b  # OK
copy_b = copy_a  # Also OK
```

`Callable` based typings get expanded to function types in tooltips, while `Protocol#__call__` based typings continue using the name of the class in tooltips. It would be useful to have a flag for the behavior with maybe a hybrid option that shows both the type "alias" and the underlying function type.

**Comment by judej** [comment]
This enhancement request has been open for a while. Closing old issue because of lack of upvotes.
