### ISSUE TITLE
Save file lag

### ISSUE THREAD

**Issue by gs-emp** [microsoft/pylance-release#5842]
Type: <b>Bug</b>

Multi workspace with multiple pyenv one for each project. Switch between projects and pylance hangs when saving

Extension version: 2024.4.1
VS Code version: Code - Insiders 1.89.0-insider (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:05:29.995Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|14, 13, 11|
|Memory (System)|32.00GB (9.75GB free)|
|Process Argv|--crash-reporter-id 5bc09f10-9ca8-49d3-b8fe-a5ee972ecaa8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
ccp2r6:30958154
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
g316j359:31013175
pythoncenvpt:31022790
a69g1124:31018687
j0bi8933:31021562
dvdeprecation:31036532
pythonprt:31036556
dwnewjupytercf:31035177

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Can you provide the information as described here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

I'm going to guess you have code actions on save set in your settings?

**Comment by rchiodo** [comment]
See this issue for a discussion of what happens if code actions are set for save:
https://github.com/microsoft/pylance-release/issues/4263
