### ISSUE TITLE
pylance JavaScript heap out of memory I set NODE_OPTIONS and exlude

### ISSUE THREAD

**Issue by aedavids** [microsoft/pylance-release#5849]
I am a vscode newbie. I work on a large python project using a remote connection. I tried setting NODE_OPTIONS to a large value in my .bashrc on the remote server

```
export NODE_OPTIONS="--max-old-space-size=8192" # 8gb
export NODE_OPTIONS="--max-old-space-size=10204" #10gb
```

## Environment data

-   Language Server version: Python v2024.6.0
-   OS and version: Linux mustard 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
-   miniconda Python 3.11.4

```
2024-05-05 10:04:15.263 [info] (Client) Pylance async client (2024.4.1) started with python extension (2024.6.0)
2024-05-05 10:04:15.959 [info] [Info  - 10:04:15 AM] (522622) Pylance language server 2024.4.1 (pyright version 1.1.356, commit 6652c4a8) starting
2024-05-05 10:04:15.960 [info] [Info  - 10:04:15 AM] (522622) Server root directory: file:///private/home/aedavids/.vscode-server/extensions/ms-python.vscode-pylance-2024.4.1/dist
2024-05-05 10:04:15.960 [info] [Info  - 10:04:15 AM] (522622) Starting service instance "extraCellularRNA"
2024-05-05 10:04:16.041 [info] [Info  - 10:04:16 AM] (522622) Setting pythonPath for service "extraCellularRNA": "/private/home/aedavids/miniconda3/envs/extraCellularRNA/bin/python"
2024-05-05 10:04:16.041 [info] [Info  - 10:04:16 AM] (522622) Setting environmentName for service "extraCellularRNA": "3.11.4 (extraCellularRNA conda)"
2024-05-05 10:04:16.107 [info] [Info  - 10:04:16 AM] (522622) Assuming Python version 3.11.4.final.0

```

```
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

2024-05-05 10:11:07.085 [info]  1: 0xb85bc0 node::Abort() [/private/home/aedavids/.vscode-server/cli/servers/Stable-b58957e67ee1e712cebf466b995adf4c5307b2bd/server/node]
 2: 0xa94834  [/private/home/aedavids/.vscode-server/cli/servers/Stable-b58957e67ee1e712cebf466b995adf4c5307b2bd/server/node]

2024-05-05 10:11:07.085 [info]  3: 0xd66d10 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/private/home/aedavids/.vscode-server/cli/servers/Stable-b58957e67ee1e712cebf466b995adf4c5307b2bd/server/node]
```
## Code Snippet

I added the terminal parameters. Our system admin requires us to add the other parameters to reduce memory usage on the server. I looked at https://github.com/microsoft/pyright/blob/main/docs/configuration.md maybe exclude is not set up correctly?

Also does vscode save the index file?

Kind regards

Andy

```
$ cat .vscode/settings.json
{
    "terminal.integrated.env.linux": {
        "PYTHONPATH":"/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python:/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/python/src"

    },
    "terminal.integrated.env.osx": {
        "PYTHONPATH":"/Users/andrewdavidson/googleUCSC/kimLab/extraCellularRNA/deconvolutionAnalysis/python:/Users/andrewdavidson/googleUCSC/kimLab/extraCellularRNA/src:/Users/andrewdavidson/googleUCSC/kimLab/extraCellularRNA/intraExtraRNA_POC/python/src"
    },

    "python.terminal.executeInFileDir": true,

    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/env": true,
        "**/venv": true
      },
      "files.watcherExclude": {
         "**/.git/objects/**": true,
         "**/.git/subtree-cache/**": true,
         "**/node_modules/*/**": true,
        "**/.cache/**": true,
        "**/.conda/**": true,
        "**/.local/**": true,
        "**/.nextflow/**": true,
        "**/env/**": true,
        "**/venv/**": true,
        "**/work/**": true,
        "**/private/groups/**": true
      }
}
```

```python
XXX
```

## Repro Steps

1. XXX

## Expected behavior

XXX

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by KardRi** [comment]
You can only use 4GB if you use the node server shipped in vscode. 

Or you may specify your own Node.js executable
[#pylance-is-crashing](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#pylance-is-crashing)

**Comment by heejaechang** [comment]
if you want to use more memory then based on your env, you either need to use your own `node execuatable` (local vscode), or set `env var like you did` for `remote vscode`

you can't mix 2. if you are using `local vscode`, `env var for remote` won't work.

**Comment by aedavids** [comment]
Hi HeeJae

I work on mac os and linux. Node.js has different paths. Is there a way I can specify the path for each environment separately?

Kind regards,

Andy

From: Heejae Chang ***@***.***>
Date: Monday, May 6, 2024 at 10:59 AM
To: microsoft/pylance-release ***@***.***>
Cc: andrew e. davidson ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/pylance-release] pylance JavaScript heap out of memory I set NODE_OPTIONS and exlude (Issue #5849)

if you want to use more memory then based on your env, you either need to use your own node execuatable (local vscode), or set env var like you did for remote vscode

you can't mix 2. if you are using local vscode, env var for remote won't work.

**Comment by aedavids** [comment]
Hi Heejae

Sometimes I do all my work on my mac using the local file system. Other times I start vscode on my mac and use remote. For example here is how I configure my PYTHONPATH in .vscode/setting.json


{

    "terminal.integrated.env.linux": {

        "PYTHONPATH":"/private/home/aedavids/extraCellularRNA/deconvolutionAnalysis/python:/private/home/aedavids/extraCellularRNA/src:/private/home/aedavids/extraCellularRNA/intraExtraRNA_POC/python/src"



    },

    "terminal.integrated.env.osx": {

        "PYTHONPATH":"/Users/andrewdavidson/googleUCSC/kimLab/extraCellularRNA/deconvolutionAnalysis/python:/Users/andrewdavidson/googleUCSC/kimLab/extraCellularRNA/src:/Users/andrewdavidson/googleUCSC/kimLab/extraCellularRNA/intraExtraRNA_POC/python/src"

    },



    "python.terminal.executeInFileDir": true,


Kind regards,

Andy



p.s. setting "python.analysis.nodeExecutable": "/usr/bin/node"
on the linux remote did not work. I can start node from terminal how ever it throws errors in vscode



From: Heejae Chang ***@***.***>
Date: Monday, May 6, 2024 at 11:39 AM
To: microsoft/pylance-release ***@***.***>
Cc: andrew e. davidson ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/pylance-release] pylance JavaScript heap out of memory I set NODE_OPTIONS and exlude (Issue #5849)

I work on mac os and linux. Node.js has different paths. Is there a way I can specify the path for each environment separately?

can you be more specific? are you saying you are using remote? and client is on mac and server is on linux? or are you saying you have 1 repo that you work on 2 different machines?

**Comment by heejaechang** [comment]
> I do all my work on my mac using the local file system

for this case, you can do https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#provide-your-own-nodejs-executable-to-run-pylance-with

> Other times I start vscode on my mac and use remote

for remote case, you can do https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#increase-memory-limit-for-vs-code-remote-only

**Comment by JostTim** [comment]
Adding : 
```json
    "terminal.integrated.env.windows": {
        "NODE_OPTIONS": "--max-old-space-size=10204"
    },
    "terminal.integrated.env.linux": {
        "NODE_OPTIONS": "--max-old-space-size=10204"
    },
    "terminal.integrated.env.osx": {
        "NODE_OPTIONS": "--max-old-space-size=10204"
    }
```
Or any other suitable value for the ram ( `10204` : `10 GB` ) worked fine for me (local vscode, no remote connection), to fix the constant crashes with many files opened and large python projects. Thanks.

**Comment by heejaechang** [comment]
interesting...
