### ISSUE TITLE
Not ignoring 'DELETE' keyword even it is enclosed with single or double quotes

### ISSUE THREAD

**Issue by edwardmabuyo** [microsoft/pylance-release#5855]
## Environment data

-   Language Server version: v2024.5.1
-   OS and version: macOS Ventura, Apple M2 Pro, 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.17

## Code Snippet

```python
@api_view(['POST','GET','PUT','DELETE'])
@authentication_classes((JSONWebTokenAuthentication,))
@permission_classes((IsAuthenticated,))
@is_subscribe_project('project_id')
def comments(request,project_id,version_id):
    ... code goes here
```
![Screenshot 2024-05-07 at 8 28 35 AM](https://github.com/microsoft/pylance-release/assets/5960649/a72727ea-d897-4a53-82d7-8eaf62810ab3)

It stops recognizing below functions like @authentication_classes and below
## Repro Steps

1. XXX

## Expected behavior

Ignore 'DELETE' keyword as it is enclosed with quotes
It should look like this if I remove the 'DELETE' keyword

![Screenshot 2024-05-07 at 8 34 54 AM](https://github.com/microsoft/pylance-release/assets/5960649/20933e3b-ae0c-4d3e-87f2-d89a9c425955)

## Actual behavior

XXX

## Logs

```
XXX
```

**Comment by heejaechang** [comment]
it doesn't repro for me.

![image](https://github.com/microsoft/pylance-release/assets/1333179/89bd2243-b8ee-469f-9cb7-914995db7c0b)

we probably need full source code to dig in since color could be affected by text before code you shared.

**Comment by debonte** [comment]
Can you try disabling all of your extensions except Python and Pylance? I am also not able to repro this, but since `DELETE` isn't a keyword (`del` is), I can't understand why Pylance would be confused here.

**Comment by edwardmabuyo** [comment]
It was fixed by uninstall/install of pylance and python although Ive tried this before filing the ticket. Closing this ticket.
