### ISSUE TITLE
String syntax highlighting

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#586]
## Environment data

-   Language Server version: 2020.11.0
-   OS and version: macOS
-   Python version: 3.9

## Actual behaviour

`{}` are highlighted for string assignments even if the `f-prefix` is missing. This isn't a big deal. However if highlighting is only enabled for f-strings, you could recognize a missing prefix more easily.

![Screen Shot 2020-11-09 at 00 53 37](https://user-images.githubusercontent.com/30130371/98487890-02711880-2226-11eb-9a9b-c9bd6cad71f2.png)

## Code Snippet / Additional information

```python
var = "My string {}"
```

**Comment by jakebailey** [comment]
VS Code is highlighting it because it believes it to be a "regular" format string, i.e.:

```
var = "My string {}".format(1234)
```

It's true that it's not an f-string as it's missing the f prefix, but this pattern is pretty common as it was one of the two ways to format strings before 3.8.

**Comment by jakebailey** [comment]
It's possible that this could be removed from VS Code's Python TextMate grammar once proper f-strings are the more popular thing, but I'm guessing that's not likely to happen anytime soon.

**Comment by cdce8p** [comment]
Makes sense. In that case it would probably only make sense to change the highlighting if you can check for `"_".format`. Although IDK if that's possible.

**Comment by cdce8p** [comment]
After thinking some more about this, I don't believe anymore that it's worth it. Their is a good use case which I haven't considered until now:

```py
TEMPLATE = """
This is my long template
Add a placeholder: {}
"""

print(TEMPLATE.format("Hello World"))
```

This example will not be replaced by f-strings. I'm closing the issue.
