### ISSUE TITLE
Pylance does not report @abstractmethod not being implemented

### ISSUE THREAD

**Issue by ShravanSunder** [microsoft/pylance-release#5887]
## Environment data

pylance version: v2024.5.1
python: 3.12

## Code Snippet

```python
from abc import abstractmethod
from datetime import datetime
from typing import Optional

from pydantic import Field
from src.agent_store.common.models.column_base_model import ColumnBaseModel



class ColumnBaseModel:
  @abstractmethod
  @classmethod
  def column_schema(cls) -> str:
    pass



class DateCreated(ColumnBaseModel):
  date_created: Optional[datetime] = Field()

  @classmethod
  def column_schema(cls) -> str:
    return "date_created TIMESTAMP"


class DateModified(ColumnBaseModel):
  date_modified: datetime = Field(default_factory=datetime.now)


class DateLastUsed(ColumnBaseModel):
  date_last_used: datetime = Field(default_factory=datetime.now)

## should trigger not implemented abstract class
data = DateModified()

#######


```

It doesn't work with classmethods or instancemethods. 

## Repro Steps

The above code in pylance strict mode should generate an error for an abstract method not being implemented.  Below is the pyproject.toml
vscode also has `strict` enabled

```
[tool.pyright]
include = ["apps/**/*", "packages/**/*"]
typeCheckingMode="strict"
ignore=["**/.venv/**", ".venv"]

useLibraryCodeForTypes=false
autoSearchPaths=true

reportMissingTypeStubs=false
reportUnknownVariableType=false
reportUnknownMemberType=false
reportUnknownArgumentType=false

reportUnusedVariable="warning"
reportUnusedImport="warning"
reportIncompatibleMethodOverride="error"

# extra strictness
reportImplicitOverride = "warning"
reportCallInDefaultInitializer = "warning"
reportMissingSuperCall="information"
reportImportCycles="information"
reportPropertyTypeMismatch="warning"
reportShadowedImports="information"
reportUnnecessaryTypeIgnoreComment="information"

```
1. XXX

## Expected behavior

XXX

## Actual behavior
No checks happen

XXX

## Logs

```
XXX
```

related issues:  https://github.com/microsoft/pyright/issues/644

**Comment by debonte** [comment]
You're not seeing a diagnostic there because `ColumnBaseModel` doesn't inherit from `abc.ABC`. If you add `ABC` as a base class, the diagnostic will appear as expected:

```python
class ColumnBaseModel(ABC):
  @abstractmethod
  @classmethod
  def column_schema(cls) -> str:
    pass
```

![image](https://github.com/microsoft/pylance-release/assets/12820898/a2c01a96-a371-45ed-858b-60333d7c4263)

**Comment by ShravanSunder** [comment]
@debonte 

I still do not see that error even with that change

![2024-05-16 0541 Cursor timestamp_columns py — askluna](https://github.com/microsoft/pylance-release/assets/5294949/ba3dd761-ee69-4199-bd65-0cf99fbcdc4c)


```python
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Optional, override

from pydantic import Field


class GraphColumnBase(ABC):
  @abstractmethod
  @classmethod
  def graph_node_columns(cls) -> str:
    pass


class DateCreated(GraphColumnBase):
  date_created: Optional[datetime] = Field()

  @override
  @classmethod
  def graph_node_columns(cls) -> str:
    return "date_created TIMESTAMP"


class DateModified(GraphColumnBase):
  date_modified: datetime = Field(default_factory=datetime.now)

  @override
  @classmethod
  def graph_node_columns(cls) -> str:
    return "date_modified TIMESTAMP"


class DateLastUsed(GraphColumnBase):
  date_last_used: datetime = Field(default_factory=datetime.now)

  @override
  @classmethod
  def graph_node_columns(cls) -> str:
    return "date_last_used TIMESTAMP"


## should trigger not implemented abstract class
data = DateModified()
```

**Comment by rchiodo** [comment]
I believe in your latest example, it is implementing the abstract method:

```python
class GraphColumnBase(ABC):
  @abstractmethod
  @classmethod
  def graph_node_columns(cls) -> str:
    pass

class DateModified(GraphColumnBase):
  date_modified: datetime = Field(default_factory=datetime.now)

  @override
  @classmethod
  def graph_node_columns(cls) -> str:
    return "date_modified TIMESTAMP"
```

**Comment by ShravanSunder** [comment]
@debonte thanks!  @rchiodo thanks!  i was having a doh moment!

**Comment by spacether** [comment]
One is not always creating instances of classes. If a class is only providing classmethods, then one will never instantiate it and your warning system, which depends upon instantiation, will never trigger. Please consider adding warnings for unimplemented classmethods.

**Comment by erictraut** [comment]
> Please consider adding warnings for unimplemented classmethods.

@spacether, if you want to be notified of unimplemented methods within a class definition (regardless of whether those methods are static, class, or instance methods), you need to mark your class as `@final` to indicate that it will not be further subclassed.

```python
from abc import ABC, abstractmethod
from typing import final

class IFoo(ABC):
    @abstractmethod
    @classmethod
    def method(cls) -> int:
        raise NotImplementedError()

@final
class Foo(IFoo): # Error: IFoo.method is not implemented
    pass
```

**Comment by spacether** [comment]
Thank you!

**Comment by Filipe-Araujo0** [comment]
I still think that it does not sound right for the final decorator to warn about the not implemented methods, but only appear as a completion suggestion if the staticmethod decorator is present, while other not implemented and not static/class methods do.
