### ISSUE TITLE
It would be much better DX if missing abstract methods show up in class definition

### ISSUE THREAD

**Issue by ShravanSunder** [microsoft/pylance-release#5889]
Currently if you have a child class you have to construct it to get feedback that something is not implemented.  It would be much better DX and more useful if this feedback happened in the definition of the child class

![2024-05-16 0545 Cursor project py — askluna](https://github.com/microsoft/pylance-release/assets/5294949/8d349031-8580-4869-a669-00f0ded2a8a4)

Related to: https://github.com/microsoft/pylance-release/issues/5887

**Comment by heejaechang** [comment]
```python
from abc import ABC, abstractmethod

class Abstract(ABC):
    @abstractmethod
    def method(self): pass

class MiddleAbstract(A):
    def newMethod(self): pass

class ActualImpl(MiddleAbstract):
    def method(self):
        ...
```

won't that cause issue for `MiddleAbstract`? 

python doesn't have keyword like `abstract` to indicate this class that inherit from other abstract class is still supposed to be left as `abstract` class or not.

**Comment by ShravanSunder** [comment]
ah i see, that makes sense.  :(. i'll close this issue
