### ISSUE TITLE
Warnings for unbound variables?

### ISSUE THREAD

**Issue by ericrbg-harmonic** [microsoft/pylance-release#5901]
Consider this code:

```python
if input():
    x = 1

print(x)
```

Pylance knows that this variable may be unbound:

<img width="501" alt="image" src="https://github.com/microsoft/pylance-release/assets/160534985/c38eeca9-82e5-4269-bc8d-b01ce3602ee3">

However, it doesn't warn me. Is there any way to configure it to warn me if it detects anything that could possibly be unbound anywhere?

**Comment by ericrbg-harmonic** [comment]
amazing, many thanks! it'd be nice if this was more clearly documented, I couldn't find it by searching by unbound (possibly it's my lack of searching ability...)

**Comment by heejaechang** [comment]
documentation regarding diagnostic rules is all documented here - https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnboundVariable

confusion might come from us being `pylance` but diagnostics documentation is from `pyright`

* pylance is built on top of pyright as an analysis engine.
