### ISSUE TITLE
Cell magics disable parsing of python code

### ISSUE THREAD

**Issue by ibobak** [microsoft/pylance-release#5902]
Type: <b>Bug</b>

It tells me that the variable is not defined, although it is defined:
![image](https://github.com/microsoft/pylance-release/assets/8807043/b3fb1cb8-869b-4446-9332-babe1a174fc5)

Extension version: 2024.5.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 1199)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|251.76GB (223.06GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31049070
fchga941:31046352
pythonprt:31047983
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by rchiodo** [comment]
I can repro it myself with this:

![image](https://github.com/microsoft/pylance-release/assets/19672699/096f007a-8ec7-4fc2-a77b-ec9af297a502)


See this discussion:
https://github.com/microsoft/pylance-release/discussions/3851

**Comment by ibobak** [comment]
is it possible to make some logic which parses the magic and finds out that everything under it is python?

**Comment by ibobak** [comment]
I am sorry for so many bugs reported here.  I am just doing migration from PyCharm, and therefore finding a lot of issues.

**Comment by rchiodo** [comment]
> is it possible to make some logic which parses the magic and finds out that everything under it is python?

If you read the discussion, we talk about using a trick where we figure out what the expected language of the magic is and the forward the parsing to the language server that handles that language. For %%time, we'd forward the contents of the cell to ourselves. For say %%sql, we'd send it to a SQL language server.

**Comment by ibobak** [comment]
Is this what you are planning to do in some future release?

**Comment by heejaechang** [comment]
@ibobak if you upvote it (I mean if more people upvote it), it will help us to prioritize it.

**Comment by rchiodo** [comment]
Closing in favor of the discussion item.
