### ISSUE TITLE
Pylance makes type hints in Python unusable for me

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5906]
From Marketplace review:
> Andy Yermakov
Makes type hints in Python unusable for me. When turned off, type hints work again

**Comment by yermandy** [comment]
Hello. This is what I meant:

With Pylance enabled I see no hints anymore in the following use case:

<img width="250" alt="Screenshot 2024-05-22 at 19 51 48" src="https://github.com/microsoft/pylance-release/assets/39454881/0682e2f8-5c78-40fe-81b9-f19242c56714">

When disabled:

<img width="856" alt="Screenshot 2024-05-22 at 19 52 16" src="https://github.com/microsoft/pylance-release/assets/39454881/8a3f5e63-1081-437f-b7e2-1f8b3c4494e0">

**Comment by heejaechang** [comment]
```python
class Foo:
    a: int

def build(some_class):
    instance: some_class

    return instance

instance = build(Foo)

instance.
```

I am not sure what you meant by 
> instance: some_class

did you mean
> instance = some_class() or instance = some_class

otherwise, `instance: some_class`, `instance` is uninitialized. so it has no value.

if you change it to either `instance = some_class()` - instance of `some_class` type, or `instance = some_class` - instance is type alias for `some_class`, and `instance.` will either show `a` as instance member or class member.

anyway, both should work. just `instance: some_class` doesn't work since it is invalid code. (if you run the code, python will throw)

**Comment by heejaechang** [comment]
and why it works with `pylance` disabled, probably `jedi` has more relaxed heuristic to show something even if code is wrong.

**Comment by rchiodo** [comment]
Pylance will show an error here if you turn on 'basic' typecheckingmode:

![image](https://github.com/microsoft/pylance-release/assets/19672699/d6358b65-d5d2-4e9a-bb54-49bca57b0bbe)

**Comment by erictraut** [comment]
I'll also note that `some_class` here is a variable, and variables are not allowed in type annotations. The Python typing spec is very clear on this point. If you want to use type annotations ("hints") in your code, you need to use them in a valid manner. If you don't, tools like pylance that conform to the Python typing standard won't understand what you're trying to do.

**Comment by yermandy** [comment]
It seems that I was not clear enough. The point was rather that by using `instance: some_class`, I say to IDE that the thing that is returned from this function will have a type that is passed as an argument to the function. Example (this code does not suppose to work, it just shows how IDE helps):

```
class Foo:
    a: int


class Bar:
    b: int


def build(some_class):
    instance: some_class = ...  # some method that will instantiate the class based on some_class
                                # method has no typing information so I provide the type hint as
                                # instance: some_class

    return instance


foo_instance = build(Foo)
bar_instance = build(Bar)

foo_instance.
bar_instance.
```

Then, I have hints:

<img width="554" alt="Screenshot 2024-05-22 at 21 05 13" src="https://github.com/microsoft/pylance-release/assets/39454881/d674d001-c634-4565-ad49-b1192bcffe97">

<img width="556" alt="Screenshot 2024-05-22 at 21 05 18" src="https://github.com/microsoft/pylance-release/assets/39454881/688d0ac8-2e2e-41ad-ad0e-0beab7b11305">

**Comment by yermandy** [comment]
Maybe I am just mocking python with my wish to get tips when I wish to instantiate an instance using some builder function with a class name only

**Comment by yermandy** [comment]
But ideally, screenshots show what I am trying to achieve. I haven't found any other reasonable way to help IDE to provide me with tips

**Comment by heejaechang** [comment]
do something like this?

```python
from typing import Type, TypeVar

T = TypeVar("T")
class Foo:
    a: int

class Bar:
    b: int

def build(some_class: Type[T]) -> T:
    instance: T = some_class()

    return instance

foo_instance = build(Foo)
bar_instance = build(Bar)

foo_instance.
bar_instance.
```

**Comment by erictraut** [comment]
I don't think you have the right mental model of type hints, which explains why it's not working as you expect. You may find it useful to read [this documentation](https://microsoft.github.io/pyright/#/type-concepts). The Python [typing spec](https://typing.readthedocs.io/en/latest/spec/annotations.html) may also provide some clarity.

As @heejaechang mentioned, the code in your screen shot will not work at runtime. It's therefore unclear what your objective is. Do you intend to instantiate the class you pass to `build`? If so, then the code should look like this:

```python
class Foo:
    a: int

def build(some_class):
    return some_class()

instance = build(Foo)
```

Now when you type `instance.`, you'll see that pylance offers `a` as a suggestion.

**Comment by yermandy** [comment]
> Do you intend to instantiate the class you pass to `build`?

Yes, exactly. But I would like to build the instance based on the provided class and get type hints

**Comment by yermandy** [comment]
> do something like this?
> 
> ```python
> from typing import Type, TypeVar
> 
> T = TypeVar("T")
> class Foo:
>     a: int
> 
> class Bar:
>     b: int
> 
> def build(some_class: Type[T]) -> T:
>     instance: T = some_class()
> 
>     return instance
> 
> foo_instance = build(Foo)
> bar_instance = build(Bar)
> 
> foo_instance.
> bar_instance.
> ```

Ohh, well, thank you very much, sir! This is exactly what I was looking for ❤️

**Comment by yermandy** [comment]
That solves my problem, thank you guys, very grateful

**Comment by yermandy** [comment]
The main problem was how to tell IDE that the returned instance should be of some generic type without necessarily having to call a constructor. And I did not know if it will work with `T = TypeVar("T")`
