### ISSUE TITLE
Syntax highlighting issue for a valid conditional logic when type hints provided

### ISSUE THREAD

**Issue by technic960183** [microsoft/pylance-release#5908]
<h3> Issue Description </h3>

There appears to be a syntax highlighting issue in Pylance when defining a class with a constructor that includes specific conditional logic for parameter validation. The problem occurs when the constructor checks that if two optional parameters **with a type hint** (`width: tuple` or `dec_bound: float`) are not provided at the same time. If both parameters are specified, a `ValueError` is raised.
Despite this logic being correct and the code executing properly (as confirmed by our testing), the syntax highlighting incorrectly suggests that the code following this check is not executable. This misrepresentation can be misleading, implying a syntax or logical error where there is none.

I have observed that if the type hints (`: float` or `: tuple`) are removed from the parameters in the constructor definition, the syntax highlighting issue disappears. For example, changing the constructor signature `from def __init__(self, center, margin, width: tuple = None, dec_bound: float = None):` to `def __init__(self, center, margin, width = None, dec_bound = None):` results in correct syntax highlighting. This suggests that **the issue might be related to how Pylance handles type hints in this specific context**.

<h3> Environment data </h3>

-   Language Server version: 2024.5.1
-   OS and version: win32 x64
-   Python version: 3.10.11
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
class GridChunkConfig:

    def __init__(self, center, margin, width: tuple = None, dec_bound: float = None):
        '''
            Some comments
        '''
        self.margin = margin
        if dec_bound is not None and width is not None:
            raise ValueError("You must specify either the width or the dec_bound, not both")
        self.config = {}
        self.config['center_ra'] = center[0]
```
![image](https://github.com/microsoft/pylance-release/assets/48866415/447245e7-2203-4782-9f49-e37ff23d604d)

<h3> Repro Steps </h3>

1. Define a class with an __init__ method that takes parameters as shown.
2. Add logic inside the __init__ method to check the parameters and raise a ValueError if certain conditions are met.
3. Observe the syntax highlighting in the editor.

<h3> Expected behavior </h3>

The syntax highlighting should correctly highlight all lines of code, indicating that the logic and syntax are valid.

<h3> Actual behavior </h3>

The syntax highlighting fails after a certain line (line 10) despite the code being logically correct and executable when the arguments are provided correctly.

<h3> Logs </h3>

(1000+ lines. I can provide if really needed.)
```
2024-05-23 20:17:58.109 [info] (Client) Pylance async client (2024.5.1) started with python extension (2024.6.0)
2024-05-23 20:17:59.611 [info] [Info  - 8:17:59 PM] (8992) Pylance language server 2024.5.1 (pyright version 1.1.360, commit 4bc8428d) starting
2024-05-23 20:17:59.611 [info] [Info  - 8:17:59 PM] (8992) Server root directory: file:///c%3A/Users/user/.vscode/extensions/ms-python.vscode-pylance-2024.5.1/dist
2024-05-23 20:17:59.620 [info] [Info  - 8:17:59 PM] (8992) Starting service instance "pycorrelator"
2024-05-23 20:17:59.630 [info] [Info  - 8:17:59 PM] (8992) Auto-Indent enabled
```

**Comment by rchiodo** [comment]
Thanks for the issue.

The colorization difference is because the type checker thinks the code after the raise is unreachable.

If you set `python.analysis.typeCheckingMode` to `basic`, Pylance will show you an error as to why that's the case.

![image](https://github.com/microsoft/pylance-release/assets/19672699/08e926ef-2ff6-4e1f-85c7-b0c486833c95)

You're specifying something is None when the type says it's impossible.

You can fix this problem my allowing `None` as a type for your two input arguments:

```python
class GridChunkConfig:

    def __init__(self, center, margin, width: tuple | None = None, dec_bound: float | None = None):
        '''
            Some comments
        '''
        self.margin = margin
        if dec_bound is not None and width is not None:
            raise ValueError("You must specify either the width or the dec_bound, not both")
        self.config = {}
        self.config['center_ra'] = center[0]
```

**Comment by technic960183** [comment]
Thank you for providing the solution.

I have a further question:
Is the type checking in Pylance designed to follow a C/C++ coding logic? Understanding the design from a C/C++ perspective makes sense, but from Python's dynamic typing logic, this behavior seems like a bug.
Is this the rationale behind this design decision?

**Comment by erictraut** [comment]
Pylance is built on top of [pyright](https://github.com/Microsoft/pyright), a static type checker for Python. Pyright is [compliant with](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html) the [Python typing standard](https://typing.readthedocs.io/en/latest/#specification), which defines behaviors of static type annotations and the type analysis rules applied by static type checkers. 

The behavior you're seeing is not a bug. Pyright is working in compliance with the typing spec. As @rchiodo said, your code sample includes a bug. The type annotations for the `width` and `dec_bound` parameters declare that these two variables are not allowed to contain `None`. Given this constraint, static analysis proves that part of your code is unreachable. If you fix the type annotations in your code, the static analysis will match the runtime behavior.
