### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by MTsireud** [microsoft/pylance-release#5928]
<h3> Environment data </h3>

-   Language Server version: 2024.5.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by heejaechang** [comment]
@MTsireud thank you for creating the issue. can you provide some more data?
