### ISSUE TITLE
What is the version of pylance corresponding to vscode version 1.80.2?

### ISSUE THREAD

**Issue by zengziru** [microsoft/pylance-release#5936]
```[tasklist]
### Tasks
```

**Comment by zengziru** [comment]
I download the vis file of pylance version 2024.5.102 and version 2024.4.106, but I can not download the extensions from it by the vix file. It says it is not compatible with vs code 1.80.2

**Comment by debonte** [comment]
2024.2.1 is the latest Pylance version that is compatible with VS Code 1.80.2. Starting with 2024.2.100 we required VS Code 1.82.0 or later.

Why aren't you able to upgrade VS Code?
