### ISSUE TITLE
cyclic symbolic detection is broken

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#5937]
create symbolic link that cycle.

`a -> b -> c -> a`

and open the folder that contains `a`

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.5.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20245104-4-June-2024-PreRelease)
