### ISSUE TITLE
I end up configuring this more than actually optimizing my code like pycharm provides

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#5939]
From Marketplace review:
> Kevin Reevers
No where near the level of depth to take this seriously. Great idea, but end up configuring this more than actually optimizing my code like pycharm provides.

**Comment by rchiodo** [comment]
Kevin, can you elaborate some more? What configuring are you doing? Is it not working?

**Comment by theklr** [comment]
Sure there's a collection of issues pending. Until then I cant recommend my team to use it. 
#3701
#3704
#3187
