### ISSUE TITLE
No overloads for dict() match parameter for nested lists (List[List[str]])

### ISSUE THREAD

**Issue by RiseT** [microsoft/pylance-release#594]
## Environment data

-   Language Server version: 2020.11.0
-   OS and version: Linux Mint 20 Cinnamon
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9 conda-forge

## Expected behaviour

No error gets displayed by Pylance

## Actual behaviour

Although Python itself has no problems with the code, Pylance underlines the line marked in the code example below in red with the message "No overloads for dict(employee_titles) match parameters"

## Logs

```
Will provide if necessary
```

## Code Snippet / Additional information

```python
employee_titles = [
    ["Mary", "Senior Manager"],
    ["Brian", "Vice President"],
    ["Julie", "Assistant Vice President"],
]

a = dict(employee_titles) # This line gets incorrectly marked as an error by Pylance
print(a)
```

**Comment by erictraut** [comment]
According to the stdlib typeshed stubs, it's not legal to pass a list of lists to the `dict` constructor. If you think this is an error, feel free to submit a bug or a PR to the typeshed repo. Pylance picks up the latest copy of the typeshed stubs regularly.

The stdlib typeshed stub indicates that a list of two-entry tuples is supported, so the following is not flagged as an error:

```python
employee_titles = [
    ("Mary", "Senior Manager"),
    ("Brian", "Vice President"),
    ("Julie", "Assistant Vice President"),
]

a = dict(employee_titles)  # This line gets incorrectly marked as an error by Pylance
print(a)
```

**Comment by RiseT** [comment]
Thanks for the info, I've filed an issue to the typshed repo.

**Comment by RiseT** [comment]
@erictraut Just FYI, I had filed an issue to the typeshed repo, but they [basically said](https://github.com/python/typeshed/issues/4762#issuecomment-726073229) that while it's indeed legal to pass a list of lists to the dict constructor, there's currently no way to express this in typshed.

Don't know if this of any importance to Pylance, just pointing this out.
