### ISSUE TITLE
Cannot import keras.models in Pylance even though it's reexported in the `__init__.py`

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5940]
still not work for me
Keras 3.3.3 + TF 2.16.1
![image](https://github.com/microsoft/pylance-release/assets/20310300/ce476f2f-1aa1-4d7f-a7a2-e926710f0e37)

_Originally posted by @mczhao1977 in https://github.com/microsoft/pylance-release/issues/5482#issuecomment-2136644384_

**Comment by rchiodo** [comment]
I believe this should work?

If you look at the keras `__init__.py`, it does this:

```
from keras.api import *  # noqa: F403
```

Wouldn't that make all the symbols in keras.api appear in the root package?

**Comment by heejaechang** [comment]
`from keras.api import *`

makes `models` to be imported as `symbol` but not `module`

so, this works `from keras import models`, but this `import keras.models` won't work.

it must be written as `import keras.api.models` unfortunately.

the problematic line is the below in `keras`

```
# Add everything in /api/ to the module search path.
__path__.append(os.path.join(os.path.dirname(__file__), "api"))  # noqa: F405
```

we can't support this in the static analyzer.

**Comment by rchiodo** [comment]
We need to enter a bug on keras then to ask them to bring back something we can parse.

**Comment by rchiodo** [comment]
Closing in favor of https://github.com/keras-team/keras/issues/19779
