### ISSUE TITLE
Docstring templating

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5944]
In order for people to have consistent output in their docstrings, pylance could offer an automatic template for a docstring whenever the user types ''' or """ in different situations

- Module template at the top of a module
- Class template at the top of a class
- Function template at the first line of a function

This would gently push people to use restructured text for their doc strings.

Of course it would be behind a setting.

**Comment by rchiodo** [comment]
Assigning to Kacie for now. Talk about the idea in triage

**Comment by dangotbanned** [comment]
I'd appreciate native support that could replace https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring as it is very popular, but last updated over 2 years ago and has some issues

**Comment by Pixel-Minions** [comment]
Love the idea, but we need support for the google style too, and yeah using a ruff config could be ideal.

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.11.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202411100-6-November-2024-PreRelease)
