### ISSUE TITLE
Unsupported generic types (`"List" is not defined`) when using comment syntax

### ISSUE THREAD

**Issue by lnicola** [microsoft/pylance-release#595]
## Environment data

-   Language Server version: `2020.11.0 (pyright 9d8e431b)`
-   OS and version: `CentOS 7`
-   Python version (& distribution if applicable, e.g. Anaconda): `Python 2.7.5`

## Actual behaviour

I'm trying to use the comment syntax for types as a workaround with Python 2.7. It seems to be supported in simple cases, but not for generic types.

## Expected behaviour

I know that Python 2 is unsupported and there are probably better solutions like `mypy`, but would it be possible to support this for simple types like lists, sets and dictionaries?

## Code Snippet / Additional information

```python
def foo():
    # type: () -> List[int]

    return [1, 2, 3]
```

![image](https://user-images.githubusercontent.com/308347/98813444-d1af0000-242c-11eb-9fa5-d91632adda49.png)

![image](https://user-images.githubusercontent.com/308347/98813983-b5f82980-242d-11eb-9b29-2269b7e2ade9.png)

**Comment by erictraut** [comment]
`List` is a symbol defined in the `typing` module, so you need to include the statement `from typing import List`. Without this import, the symbol `List` has no meaning.

**Comment by lnicola** [comment]
I understand, but somehow the type checker already knows about `List`, since it's able to infer the type of `[1, 2, 3]` as shown above. Since the type annotations in comments are presumably most useful for pre-`typings` versions of Python, supporting there would make the feature much more useful.

**Comment by jakebailey** [comment]
As a workaround, does adding something like:

```python
try:
    from typing import List
except:
    pass
```

Work? I'm not sure that we'd want to try and figure out which types are which inside of comment annotations.

**Comment by lnicola** [comment]
Oh, that's an awesome workaround. Thanks.

I'll close this, since it's better than what I proposed and will probably be enough for a lot of code.
