### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by W8Yi** [microsoft/pylance-release#5954]
<h3> Environment data </h3>

-   Language Server version: 2024.5.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by heejaechang** [comment]
@W8Yi Hi, thank you for the issue. can you provide us some more detail? including log? 
[the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs)?

**Comment by debonte** [comment]
Closing this issue because it needs more information and has not had recent activity. If the issue still persists, please reopen with the information requested. Thanks.
