### ISSUE TITLE
Why not to just take the type of variable?  Why are you guessing it?

### ISSUE THREAD

**Issue by ibobak** [microsoft/pylance-release#5958]
Type: <b>Bug</b>

Below will be the source code to reproduce.  Here is the problem:
![image](https://github.com/microsoft/pylance-release/assets/8807043/1f4c30e3-7ec3-4704-80d9-b3ecb7b36fe6)

So, the problem is this:
![image](https://github.com/microsoft/pylance-release/assets/8807043/a2c0e36a-58af-4d49-b1a9-fcc5ae369907)

The question is this:  why Pylance cannot rely upon the factual value of the variable?  This is a juptyter notebook:  the code has already run and we already know what is the type.  Why not to use that type?   Why are you trying to analyze the function's code and find out what might be the type?

Here is the code to reproduce (split on cells like on the screenshot):
```
import pandas as pd

def test_func(a_some_parameter: int, a_return_row_count=True):
    if a_return_row_count:
        return pd.DataFrame(), 10
    return pd.DataFrame()

x = test_func(1, False)

type(x)

x.iloc[0]
```

Extension version: 2024.5.1
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:16:23.416Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz (88 x 1197)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 6, 6|
|Memory (System)|251.76GB (178.67GB free)|
|Process Argv|--crash-reporter-id 27d42247-63fb-4d9e-9cb0-87d9974843dc|
|Screen Reader|no|
|VM|50%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31064718
chatpanelt:31048053
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Sorry but Pylance doesn't know anything about the code being executed, it is purely a static analyzer. And statically, your code is returning a tuple in some cases. This line here:

```
if a_return_row_count:
        return pd.DataFrame(), 10
```

There are some things you can do. 

Force x to a data frame using a cast:

```python
x = cast(pd.DataFrame, test_func(1, False))
```

Have multiple overloads where the type of the parameters determine the type of the result:

```python
@overload
def test_func(a_some_parameter: int, a_return_row_count: Literal[True]) -> tuple[pd.DataFrame, Literal[10]]: ...

@overload
def test_func(a_some_parameter: int, a_return_row_count: Literal[False]) -> pd.DataFrame: ...

def test_func(a_some_parameter: int, a_return_row_count: bool):
    if a_return_row_count:
        return pd.DataFrame(), 10
    return pd.DataFrame()

x = test_func(1, False)

reveal_type(x)
```

**Comment by ibobak** [comment]
OK, I understood what to do in my case, thank you.   Total refactoring of my own library (with those issues) was planned long ago.

But let us forget about my library and let us look at the others:   there are many cases when a variable can have one declared type but actual type will be quite different.    Jupyter notebook is the place where there should work a mix of pylance and some kind of  "actual analyzer":    if a variable is initialized to something,  we already know the type and we can use that type.  But if the variable is NOT initialized - we should use pylance to try to  guess this type. 

How difficult is to implement?

**Comment by rchiodo** [comment]
> How difficult is to implement?

Sorry but it's not currently on our list of things to do. Pyright, the basis for most of Pylance is a static typechecker, it's declared as a [static type checker](https://github.com/Microsoft/pyright?tab=readme-ov-file#static-type-checker-for-python).

That being said, there are some other scenarios we want to support that require more dynamic information. Like Django Model relationships. Or pytest fixture intellisense. It might be we generate this information externally from Pyright and then feed it _static_ information from that generated data.

For example, when a jupyter kernel runs a cell, we might query the kernel for all of the types of the variables in the cell and then rewrite the cell (before we send it to Pyright) so that the appropriate type annotations are injected into the python code.

It's just an idea at the moment though.
