### ISSUE TITLE
pylance_error for importing function from another file

### ISSUE THREAD

**Issue by devnarayanp02** [microsoft/pylance-release#596]
I am Using Pylance in Visual Studio Code,
When i import fuction from another file it work normally.
But i receive a problem {
	Import "(file-name)" could not be resolved, Pylance (reportMissingImports)[1,8]
Everything is works good when i run code, but everytime i see error in Problems.
Please Solve it !

**Comment by judej** [comment]
@devnarayanp02, thanks for the report. Could you please send a code sample and the folder structure?

**Comment by devnarayanp02** [comment]
Code working normally in Terminal,no issue When i Run !
![Screenshot (3)](https://user-images.githubusercontent.com/52664716/98901584-05942f00-24da-11eb-8f89-e339ba41c084.png)

**Comment by devnarayanp02** [comment]
I am a Beginner and learning Python, 
when i make that two python file in desktop then didn't showing this problem
But when move these files to another folder where my all python files available then i face this problem
![Screenshot (5)](https://user-images.githubusercontent.com/52664716/98902067-fcf02880-24da-11eb-81f2-c909b7bed614.png)
.

**Comment by moulip** [comment]
I have exactly the same issue. To expand a bit, if I have a project with a single directory and all my python files in it there is no issue. If I create a structure with a top-directory and one subdirectory where I put all my files in, VSCode and Pylance can't resolve the modules anymore, though the code is running fine. If I open this subdirectory alone then Pylance finds the other files.

**Comment by moulip** [comment]
I have managed to fix this issue. This is related with the way Pylance is trying to resolve imports.
In your case, in your project root folder create a .vscode directory. Then in this directory create a settings.json file.
Open this file and add this:

    "python.analysis.extraPaths":["./subfolder1", "./subfolder2"]

This way you will be able to import your hello module into your hello2 file.

**Comment by jakebailey** [comment]
Correct, that's the way to do it at the moment if your import roots are not your workspace root: https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

It's not simple to figure out where imports are rooted for every project or folder.

**Comment by devnarayanp02** [comment]
Thanks for help, I don't know why but my problem is solved. Now I can move that two files to any directory,
Now color is not changing to green when import function from another file.
Now an extra folder 'pycache' created after importing function.

I have Updated VS Code then show a pop-up for installing Jupyter Notebook Extension and pylint module, I have installed both.
![Screenshot (6)](https://user-images.githubusercontent.com/52664716/99136820-4ceefc80-264d-11eb-8d85-29f304d585ad.png)
