### ISSUE TITLE
A type statement can be used only within a module or class scope

### ISSUE THREAD

**Issue by arjenzorgdoc** [microsoft/pylance-release#5964]
<h3> Environment data </h3>

-   Language Server version: 2024.5.103
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
def foo():
    type X = str
    a: X = "abc"
    return a
```

<h3> Expected behavior </h3>

A type statement can be used.

<h3> Actual behavior </h3>

I see this in the 'problems' tab:

`A type statement can be used only within a module or class scope`

```json
[{
	"resource": "/tmp/test.py",
	"owner": "_generated_diagnostic_collection_name_#4",
	"code": {
		"value": "reportGeneralTypeIssues",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportGeneralTypeIssues"
		}
	},
	"severity": 8,
	"message": "A type statement can be used only within a module or class scope",
	"source": "Pylance",
	"startLineNumber": 2,
	"startColumn": 10,
	"endLineNumber": 2,
	"endColumn": 11
}]
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is doing the correct thing here. The `type` keyword can be used only within a `class` body or within a module (global) scope. It is not allowed within a function scope. This is also true for the `TypeAlias` type qualifier that came before the `type` statement. You can fix your code by moving the type alias declaration outside of the function scope.

**Comment by arjenzorgdoc** [comment]
> It is not allowed within a function scope.

I looked everywhere for documentation about that. Can you point me to the specs?

**Comment by erictraut** [comment]
> Can you point me to the specs?

It is not (yet) part of the of the official [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html). There has been a big effort over the past six months to clean up and clarify the official typing spec, and we've made significant headway, but we still have a long way to go. This particular item (where `type` and `TypeAlias` can be used) is on a long list of items that still needs to be formally added to the spec. 

The decision to restrict `TypeAlias` and `type` to class and global scopes was made some time back in one of the public Python typing forums. Other type checker maintainers weighed in at the time, and we came to a common decision. I'm struggling to find the exact thread right now (we've switched forums several times over the years, which makes it more difficult to search for these historical discussions). If you're interested in participating in such discussions about the Python typing spec, the [Python typing forum](https://discuss.python.org/c/typing/32) is the current forum that the typing community uses. For example, if you want to make an argument in favor of permitting `type` statements within a function scope, you could post to that forum and make your case.

**Comment by oreilles** [comment]
I've been searching for this again, and it still seem like there isn't any restriction from using `type` or `TypeAlias` in a function scope still to this day.
