### ISSUE TITLE
Specifying node.exe in an unknown location is not warned by Pylance

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#5966]
## Environment data

-   Language Server version: 2024.5.103

## Repro Steps

1. Follow the directions in [this issue](https://github.com/microsoft/pylance-release/issues/5440) to create the folder, create the virtual environment, and install the `aws_cdk` and `pytest` in your virtual environment.
2. Set `"python.analysis.nodeExecutable": "C:\\Program Files\\nodejs\\node.exe"` in user's `settings.json`
3. Reload the window or restart VSCode

## Expected behavior
I can tell that Pylance is using user specified node.js by viewing the process explorer. 
![image](https://github.com/microsoft/pylance-release/assets/100439259/b3fceded-67fc-4e2a-a20c-faf218a3c7a3)

So I am expecting to get a question from pylance like so:
![image](https://github.com/microsoft/pylance-release/assets/100439259/d49f8c9b-4685-43ec-9a33-b3be577e320b)

## Actual behavior

Nothing pops up

**Comment by rchiodo** [comment]
Program files is not writeable by all users on the machine. You have to be an admin. That's actually one of the specifically allowed folders.

See the code here:
https://github.com/microsoft/pyrx/blob/06561e7c26583c308988acd09ef3996623faff3d/packages/vscode-pylance/src/common/utils.node.ts#L8

You'd need to pick somewhere that anybody could write to.

Example:

```
C:\Program Files>echo test > foo.txt
Access is denied.

C:\Program Files>
```

**Comment by StellaHuang95** [comment]
okay thanks, I was able to verify using `C:\\nodejs\\node.exe`
