### ISSUE TITLE
'reportMissingModuleSource' warning for requests.packages.*

### ISSUE THREAD

**Issue by trallnag** [microsoft/pylance-release#597]
## Bug

Pylance shows a `reportMissingModuleSource` on an valid import statement. And in addition the autocomplete and hinting works, it is just the warning that is wrong. Interestingly all other import statements that import stuff from the same library (`requests`) work fine.

![image](https://user-images.githubusercontent.com/24834206/98849306-4dbc3e80-2453-11eb-84ce-a7270d0fe17f.png)

## Environment data

* Language Server version: 2020.11.0
* OS and version: Linux, Fedora 32
* Python version 3.9 with Pyenv + virtualenv

The only installed package in the environment is `requests`. I ensured that the venv is activated:

![image](https://user-images.githubusercontent.com/24834206/98849818-17cb8a00-2454-11eb-9e56-31660c57e5d8.png)

Here is the pip list output:

```
Package    Version
---------- ---------
certifi    2020.11.8
chardet    3.0.4
idna       2.10
pip        20.2.3
requests   2.24.0
setuptools 49.2.1
urllib3    1.25.11
```

## How to recreate

You must have some kind of virtual environment tool, for example venv. I will use Pyenv and virutalenv in the example:

In shell:

```
pyenv virtualenv 3.9.0 test_pylance_bug
pyenv activate test_pylance_bug
pip install requests
code .
```

Ensure tht correct env is activated.

Create a file on VS Code with following content

```
from requests.packages.urllib3.util import Retry
from requests.adapters import HTTPAdapter

x = Retry()
a = HTTPAdapter()
```

**Comment by madewild** [comment]
I can confirm the same issue in this environment:

- Pylance version: 2021.1.3
- OS and version: Arch Linux (Kernel: Linux 5.10.11-arch1-1)
- Python version: 3.9.1 with virtualenv (but no Pyenv)

The command `from requests.packages.urllib3.util import Retry` is actually a shortcut for `from requests.packages.urllib3.util.retry import Retry` but both return a `reportMissingModuleSource` warning.

**Comment by heejaechang** [comment]
@trallnag Hi, thank you for the reporting.

this is happening since those modules are created dynamically.

requests\packages.py looks like this

```python
import sys

# This code exists for backwards compatibility reasons.
# I don't like it either. Just look the other way. :)

for package in ('urllib3', 'idna', 'chardet'):
    locals()[package] = __import__(package)
    # This traversal is apparently necessary such that the identities are
    # preserved (requests.packages.urllib3.* is urllib3.*)
    for mod in list(sys.modules):
        if mod == package or mod.startswith(package + '.'):
            sys.modules['requests.packages.' + mod] = sys.modules[mod]

# Kinda cool, though, right?

```

but pyi in typeshed define these statically as expected. that's why you are seeing the warning (since typechecker can't verify py files exist for those modules in pyi)

now, how to solve this. unfortunately, it is not easy for us to solve any dynamic behaviors until we have some kinds of plug in mechanism to inject some dynamic behaviors per libraries.

that being said, if you are using default typecheckingmode (which is off), you can import urllib3 directly instead

```python
from urllib3.util import Retry
```

since all actual library does is re-exporting urllib3 at runtime, it should work fine at runtime, and you should get auto-complete and etc at design/editing time.

unfortunately, if you use other typecheckingmode, you might get type errors since symbol from typeshed pyi and urllib3 will be considered as different types.

**Comment by alsitn** [comment]
To expand what said before, this works and won't throw another warning for urllib3.disable_warnings(InsecureRequestWarning) not being a declared variable(?)

`import requests
from requests.packages import urllib3
from urllib3.exceptions import InsecureRequestWarning
urllib3.disable_warnings(InsecureRequestWarning)`

**Comment by Alex2218** [comment]
add the **venv** folder to your VS Code workspace.

**Comment by heejaechang** [comment]
@alsitn I am not sure what you mean.

**Comment by binh-vu** [comment]
I encounter this issue when developing a python [extension modules](https://docs.python.org/3/extending/extending.html) (using Rust). As it is an extension created in another language, the source code is not available and hence I have that warning.

I don't think the warning in this case (extension + already provided pyi) can help much as there is no way to fix (no source code). Can we have a work around for this specific scenario?

**Comment by erictraut** [comment]
If the extension is written in another language, the import should resolve to a binary library file (e.g. a ".so" file on Mac or Linux or a ".pyd" file on Windows). The warning is an indication that pylance would not resolve the import to either a python source (.py) file or a binary library file. Do you see such library files present?

**Comment by pcplusmac** [comment]
I am having this issue, too. 
there is no complain in python cell, but when i do: 
   'import requests'
the error message of "import 'requests' could not be resolved from source pylance(missingModuleSource)"

**Comment by omidshojaee** [comment]
I have this issue with random modules.

Modules I've had this warning so far:

```django.core.management.utils```
```django.db```

Pylance v2022.8.21.

And yes the virtual environment is **active**.

**Comment by hitrust** [comment]
same issue
Pylance v2023.3.20

**Comment by heejaechang** [comment]
@hitrust can you open a new issue with a log as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

this issue is old one and won't be tracked.

**Comment by justineakehurst** [comment]
FWIW, I was able to get around this issue by using `stubgen` from Mypy:
```
stubgen --output ./typings -m requests.packages.urllib3.util.retry
```
And having vscode pylance look for the `typings` directory to override default typeshed .pyi references.
