### ISSUE TITLE
Support sphinx doc strings

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#5975]
### Discussed in https://github.com/microsoft/pylance-release/discussions/4416

<div type='discussions-op-text'>

<sup>Originally posted by **rchiodo** May 24, 2023</sup>
              @jakebailey I've created a new issue for an actual bug related to missing newlines for "key" and "keyword" parameter descriptions. These are valid syntax and break the current implementation of the docstring hover for sphinx format: https://github.com/microsoft/pylance-release/issues/2002

---

For the sake of not making new duplicate tickets, I would like to continue the discussion that is exactly related to "The Sphinx docstring hover may be more pretty". The Sphinx website shows an example rendering of how their syntax is meant to be used: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists

This is the expected rendering, which would bring it to parity with the same feature in PyCharm and match Sphinx's documentation.
![image](https://user-images.githubusercontent.com/88157114/139322820-d09c440f-7353-4f8f-badc-e1e337169d62.png)

_Originally posted by @jeremyvital4 in https://github.com/microsoft/pylance-release/issues/1113#issuecomment-954139426_
            </div>

**Comment by rchiodo** [comment]
Well this is silly, had to create another issue for an issue that was turned into a discussion. Anyway, this should be handled by the doc string work to support restructured text.

**Comment by rchiodo** [comment]
The output won't be exactly as asked for, but it should look something like so:

![image](https://github.com/microsoft/pylance-release/assets/19672699/603c9002-ee51-46a6-aae7-9d51e738199f)

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246100-13-June-2024-PreRelease)

**Comment by rchiodo** [comment]
The fix for this issue is behind an experimental feature flag:

```json
"python.analysis.supportRestructuredText": true
```

If you want to try our our new restructuredText support, enable this flag. It's behind a flag at the moment until we can make sure it handles all the possible Sphinx/GoogleDoc/Epytext scenarios that customers need. Please log additional issues if the flag is not meeting your needs.

Thanks :)

**Comment by tamnguyenswe** [comment]
My long awaited feature is finally here. Would be super nice if the tooltip supports (cross) referncing with :ref: tags.

**Comment by rchiodo** [comment]
Actually cross referencing was added an issue. Please up vote it:

https://github.com/microsoft/pylance-release/issues/6042
