### ISSUE TITLE
Use of multiplication operator `*` within expression split over multiple lines causes wrong highlighting

### ISSUE THREAD

**Issue by my1e5** [microsoft/pylance-release#5980]
## Environment data

-   Language Server version: Pylance v2024.6.1 / Python v2024.8.0 / VSCode 1.90.9
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.3

## Code Snippet

If a line of code within a method is too long it gets auto-formatted to be split across multiple lines. This is normal and generally fine. But I've found that if the expression contains multiplications using the `*` operator AND there is a specific presence of docstrings on either side of the code then the code highlighting breaks. This is the most minimal example I've been able to produce:

```python
class Foo:
    def foo_method(self):
        """The foo method.

        Further details. If you take away this text the error goes away.
        """
        really_long_variable_name = 1
        y = (
            really_long_variable_name
            * really_long_variable_name
            * really_long_variable_name
        )

    def bar_method(self):
        """The bar method."""
```
![image](https://github.com/microsoft/pylance-release/assets/10064103/90c985b1-b450-49c3-9d1b-ec9b19d6c2f3)

Notice how `* really_long_variable_name` is coloured light green.

## Additional notes
But if I change `bar_method` to not have a docstring. The error goes away.
```py
    def bar_method(self):
        pass
 ```
![image](https://github.com/microsoft/pylance-release/assets/10064103/c4b7bb44-96b9-40f0-989a-bae5066849ac)

Also if I remove the 'Further details' part of the `foo_method` docstring (this could also be an Args or Returns section of the docstring by the way)
![image](https://github.com/microsoft/pylance-release/assets/10064103/8c365e37-c8c9-4136-9875-004c623c19ce)

Also this just affects the use of `*`. If I change to `+` it goes away.
![image](https://github.com/microsoft/pylance-release/assets/10064103/c3d66954-7876-4750-b495-583a65d39bb3)

**Comment by debonte** [comment]
@my1e5, I'm unable to reproduce this behavior. Can you try disabling all of your extensions other than Python and Pylance and see if the behavior persists? If it does, please provide your user and workspace settings. They may provide a clue.

**Comment by my1e5** [comment]
@debonte, thanks for your advice. I found the culprit. It was the [Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments) extension which was causing this bug. After disabling that everything is fine.
