### ISSUE TITLE
Highlighting fails in jupyter notebook when switching betwen project interpreters

### ISSUE THREAD

**Issue by alita-moore** [microsoft/pylance-release#5986]
I'm cross posting a bug report that I made for the jupyter extension in the case that this problem is related to pylance. The post should contain all the necessary information to reproduce the problem: https://github.com/microsoft/pylance-release/issues/5995

**Comment by debonte** [comment]
@alita-moore, I'm unable to reproduce this issue. A video of you reproducing it might help. Also please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue).

**Comment by alita-moore** [comment]
Here are the logs of a time when I _think_ I reproduced it.
[logs.txt](https://github.com/user-attachments/files/15789229/logs.txt)

I'd be happy to collect more if you want.

**Comment by alita-moore** [comment]
Then I created a video of me reproducing it, which I shared on the other issue, but here's a quick link for convenience: https://www.loom.com/share/d7cb8b8ec70942998904e5d6f4e9c6f6?sid=4ea8ca7d-972f-4274-97e3-cb1fecdb176c

**Comment by debonte** [comment]
Duplicate of #5995
