### ISSUE TITLE
Inline type hinting doesn't work (global scope)

### ISSUE THREAD

**Issue by Groni3000** [microsoft/pylance-release#5993]
<h3> Environment data </h3>

-   Language Server version: 2024.6.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.5 (pip venv)
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
from typing import Optional, cast

global_x: Optional[int] = None  # of type `None` ??
# global_x = cast(Optional[int], global_x)
# With this ↑ cast, `global_x` is now of type `int | None`
# and code below works absolutely fine.

# Note: even with
# global_x: Optional[int]
# global_x = None
# It is None.

if global_x is None:
    global_x  # `None` as expected
else:
    global_x  # `Never` as NOT expected

```

<h3> Repro Steps </h3>

1. Just copy-paste code snippet.

<h3> Expected behavior </h3>

Expected to have correct type hinting due to my explicit declaration. The problem stays even in strict mode. It's kinda impossible to understand if it's a `duplicated` or `by_design` issue due to high number of open/closed issues, so, sorry if it is. But I tried to search the problem and saw that you support inline type hinting in global | class scopes. Maybe it's outdated?

<h3> Actual behavior </h3>

Variable has type of assigned value.

**Comment by Groni3000** [comment]
Issue I found that you support inline type hinting in module | class scope: #5964
That's why I'm curious why it's not working.

**Comment by debonte** [comment]
Pylance is working correctly here. Although you've annotated `global_x` as `Optional[int]`, you only ever assign `None` to it, so there's no way for `global_x` to have any value other than `None` in your `if`/`else` block.

See the documentation here: https://microsoft.github.io/pyright/#/mypy-comparison?id=assignment-based-type-narrowing

**Comment by Groni3000** [comment]
> Pylance is working correctly here. Although you've annotated `global_x` as `Optional[int]`, you only ever assign `None` to it, so there's no way for `global_x` to have any value other than `None` in your `if`/`else` block.
> 
> See the documentation here: https://microsoft.github.io/pyright/#/mypy-comparison?id=assignment-based-type-narrowing

Thank you for documentation link, should (and will) keep it in my favourites. Based on this: [class-and-instance-variable-inference](https://microsoft.github.io/pyright/#/mypy-comparison?id=class-and-instance-variable-inference)

We can construct this simple code snippet:
```python
from typing import reveal_type


class M:
    def __init__(self) -> None:
        self.m = None

    def method(self):
        self.m = 1


m_instance = M()
reveal_type(m_instance.m)  # Type of "m_instance.m" is "int | None"
```

That is 100% correct, no issues with that.

But on top of that we can construct my actual simplified version of code. Should send it, not my previous code snippet. I was trying to narrow the probles as much as I can. My bad.

```python
from typing import Optional, reveal_type, cast


class B: ...


class A:
    # x: Optional[B]
    # with self.x = None in __init__(...) doesn't work either.

    def __init__(self):
        self.x: Optional[B] = None

    def some_work(self):
        # Here is a complicated logic and
        # There may be assignment and may NOT.
        # But, for simplicity, lets just assign.
        self.x = B()


global_B: Optional[B] = None  # ok, `None` only
# global_B = cast(Optional[B], None)  # that would work fine.

a = A()
# --- this code block OVERRIDES type
a.x = global_B
reveal_type(a.x)  # Type of "a.x" is "None". Just overrided type hint...
# --- end
# I expected type: Union[type(global_B), type(a.x)] = Union[None, Union[B, None]] = Union[B, None]
# But instead we got simply None...

# Even after we call method that assigns self.x to B.
a.some_work()  # here is `self.x := B()` so I expected a.x to be `Optional[B]`, but, maybe it's impossible/hard to infere...
reveal_type(a.x)  # Type of "a.x" is "None".

# The rest of code doesn't metter, cuz we already have wrong type, but I will show it.
global_B = a.x  # `None` only...

if global_B is None:
    reveal_type(global_B)  # `None` - correct.
else:
    reveal_type(global_B)  # `Never`... But actual code logic highly relies on this.
```

So, I expected `Union` logic applied to types as described in comment, not override logic.

**Comment by debonte** [comment]
> ```python
> # Even after we call method that assigns self.x to B.
> a.some_work()  # here is `self.x := B()` so I expected a.x to be `Optional[B]`, but, maybe it's impossible/hard to infere...
> reveal_type(a.x)  # Type of "a.x" is "None".
> ```

Pylance doesn't model the side-effects of function calls. So this is expected.

> ```python
> a = A()
> # --- this code block OVERRIDES type
> a.x = global_B
> reveal_type(a.x)  # Type of "a.x" is "None". Just overrided type hint...
> ```

It sounds like you're confusing the annotated type of `a.x` (`Optional[B]`) with the type that Pylance currently believes `a.x` is set to (`None`). Consider the following:

```python
a = A()
reveal_type(a.x) # Type of "a.x" is "B | None"
a.x = None
reveal_type(a.x) # Type of "a.x" is "None"
a.x = 1 # reportAttributeAccessIssue: Cannot assign to attribute "x" for class "A". Type "Literal[1]" is incompatible with type "B | None"
```

So, even though Pylance says that `a.x` is currently `None` (for example), it still understands that it can legally be set to either `B` or `None`.

**Comment by erictraut** [comment]
You may also find [this documentation](https://microsoft.github.io/pyright/#/type-concepts) and [this documentation](https://microsoft.github.io/pyright/#/type-concepts-advanced) helpful.

**Comment by Groni3000** [comment]
Thank you @debonte , @erictraut !
