### ISSUE TITLE
dataclass_transform: Fields without default values cannot appear after fields with default values

### ISSUE THREAD

**Issue by powellnorma** [microsoft/pylance-release#5999]
## Environment data

-   Language Server version: 2024.6.1 (pyright version 1.1.364, commit 0618acc5)
-   Python version: 3.11

## Code Snippet

```python
from dataclasses import dataclass, field
from typing import dataclass_transform

@dataclass_transform()
def my_dataclass(c):
    return dataclass(c)

@my_dataclass
class MyClass:
    a: int
    b: int = field(compare=False)
    c: int
```

## Expected behavior

It should not say `Fields without default values cannot appear after fields with default values` for the field c. When using `@dataclass` instead of `@my_dataclass`, it works as expected.

**Comment by erictraut** [comment]
Pyright is working correctly here, so this isn't a bug.

When you use `dataclass_transform`, you must specify which functions and classes should be treated as fields specifiers. You have not specified this argument, so `dataclasses.field` is not considered a field specifier.

If you change your code to the following, it works:

```python
@dataclass_transform(field_specifiers=(field,))
def my_dataclass(c):
    return dataclass(c)
```
