### ISSUE TITLE
Pylance doesn't seem to respect python.autoComplete.extraPaths

### ISSUE THREAD

**Issue by jarshwah** [microsoft/pylance-release#6]
## Environment data

- Language Server version: 2020.6.1
- OS and version: OSX 10.15.5
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6 (pyenv)

## Expected behaviour

Project imports are recognised when they exist in paths defined by `python.autoComplete.extraPaths`

Example:

```
"python.autoComplete.extraPaths": [
            "kogan3/apps/",
            "kogan3/"
        ],
```

Should recognise an import of `from myapp.models import MyModel` when it is contained within `kogan3/apps/myapp/`

## Actual behaviour

Red squiggles and the imports aren't recognised

## Logs

```
Time taken to get recommendations: 5 ms, Memory increase: 480 KB.
[BG] analyzing: /Users/josh/dev/K3/kogan3/apps/klarna/models.py ...
[BG]   parsing: /Users/josh/dev/K3/kogan3/apps/klarna/models.py (9ms)
[BG]   binding: /Users/josh/dev/K3/kogan3/apps/klarna/models.py (2ms)
[BG]   checking: /Users/josh/dev/K3/kogan3/apps/klarna/models.py (102ms)
```

## Code Snippet / Additional information

![klarna-imports](https://user-images.githubusercontent.com/541083/86201221-4ed68880-bba2-11ea-8d20-f78349d56f9d.png)

**Comment by jarshwah** [comment]
Ah, as my team mate has discovered, a new setting resolves this:

```
"python.analysis.extraPaths": [
            "kogan3/apps/",
            "kogan3/"
        ],
```

**Comment by jakebailey** [comment]
Yes, we moved this to a new setting as the old one was inconsistently named (for historical reasons). We plan to keep everything under the `python.analysis.*` grouping from now on.
