### ISSUE TITLE
python intelliSence by Pylance not rendered AS IS

### ISSUE THREAD

**Issue by sirlis** [microsoft/pylance-release#601]
# Environment

VSCode Version: 1.51.1
OS Version: windows 10
Python Version: 3.7.9 64-bit

# Steps to Reproduce:

- install pylance
- define a class, or import a 3rd party package (e.g. pytorch) and then use a class
- hover your mouse on the class name
- the provided comment doc strings is not rendered AS IS

I'm using VSCode to write python, and using Pylance to provide intelliSence. I think that comment doc strings should be rendered **AS IS**. No markup interpretation. If the author makes an effort to format the string it look good.

# Detailed description

user defined class:

![1](https://user-images.githubusercontent.com/12960298/98910338-fd4deb00-24fd-11eb-9f70-8738837b16fc.png)

pytorch class:

![2](https://user-images.githubusercontent.com/12960298/98910349-017a0880-24fe-11eb-8663-a0b5812f7f4a.png)

I tried the `-` (minus) method and it worked more reasonable than plain text. But I also faced with `_` problems in **variable names** as is shown below. Since I can add `---` in my user defined classes, I cannot edit comments in 3rd party packages like PyTorch, whose comments are shown in the images above and are rendered as plain text by Pylance.

![3](https://user-images.githubusercontent.com/12960298/98910356-050d8f80-24fe-11eb-9574-fe1fc85a9bf2.png)

**Comment by jakebailey** [comment]
Not converting to markdown wouldn't be a good idea (as it prevents us from using markdown at all in the tooltips). VS Code's plaintext support is broken until 1.52, but maybe then we could add a toggle to say "use plaintext only".

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.2.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202120-3-february-2021
