### ISSUE TITLE
Signature help isn't formatted beautifully when class docstring is reused for `__init__`

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#6012]
## Environment data
-   Language Server version: 2024.6.100
-   OS and version: Windows 11
-   Python version: 3.12.1

## Code Snippet
```python
class Foo:
    """Does the thing.

    Attributes:
        bar (int): A short description
        buzz (str): A longer description that needs to be broken up over multiple lines,
            because there is additional context that I want to provide, and I don't
            want to go past the 88 line length limit for whatever reason.
    """
    bar: int
    buzz: str

    def __init__(self, bar, buzz):
        self.bar = bar
        self.buzz = buzz
```

## Repro Steps
1. Paste code above.
2. Initiate signature help for `__init__` by typing `Foo(`

## Expected behavior

Current parameter's docstring is shown in markdown and there's a line separating the parameter docstring from the full docstring.

![image](https://github.com/microsoft/pylance-release/assets/12820898/d3ba42be-7ab9-4a58-b9c1-ddd56bb4d028)

## Actual behavior

Current parameter's docstring is shown in plaintext. No line separating it from the full docstring.

![image](https://github.com/microsoft/pylance-release/assets/12820898/eb7ad715-4acf-4786-a8dc-3dfac15b0681)

Apparently this is because we're using the class docstring for `__init__` and the class docstring has an "Attributes" section instead of "Parameters". If you change it to "Parameters" it works as expected.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246101-20-June-2024-PreRelease)
