### ISSUE TITLE
Unbound methods are erroneously marked as incompatible with Callable where first argument is of type owner class

### ISSUE THREAD

**Issue by Alexandre-SCHOEPP** [microsoft/pylance-release#6016]
## Environment data

-   Language Server version: 2024.6.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.12.3 compiled on machine
-  Pylance Type checking is in mode 'standard'

## Code Snippet

```python
from typing import Callable


class Hello:
    def f(self, a: int) -> float:
        return 0.

    a: dict[str, Callable[['Hello', int], float]] = {
        'my_f': f
    }  # Entire dictionary marked as invalid
hello = Hello()
print(Hello.a['my_f'](hello, 3))  # 0.0
```

## Reproduction Steps

1. Add a method to a class
2. Use it, while still inside the class, as a function that expects the first argument to be an instance of the class
3. Watch pylance tell you that this is not a valid value for the given type

## Expected behavior

Pylance validates the association, like it would if 'a' was defined outside of the class definition.

Testing the same snippet with `mypy --strict test.py` succeeds with no issue found in 1 source file.

When `a` is defined outside of the class, it works. Same thing when it is defined inside of another method. I believe to be that this is because both of those require the usage of `Hello.f`, not `f`.

However, putting `Hello.f` would be syntaxically invalid python code for `a` to be a class variable, which is what I want.

## Actual behavior

Pylance flags the expression with the following error message:
```
Expression of type "dict[str, (self: Self@Hello, a: int) -> float]" is incompatible with declared type "dict[str, (Hello, int) -> float]"Pylance[reportAssignmentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAssignmentType)
```

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is correct in generating a type error here. 

In your code sample, the type of parameter `self` has an implicit type of `typing.Self`, not `Hello`. If you replace the type annotation `Callable[["Hello", int], float]` with `Callable[[Self, int], float]`, your code will type check without errors. For more details about the `typing.Self` special form, refer to [this section of the typing spec](https://typing.readthedocs.io/en/latest/spec/generics.html#self).

```python
from typing import Callable, Self

class Hello:
    def f(self, a: int) -> float:
        return 0.0

    a: dict[str, Callable[[Self, int], float]] = {"my_f": f}
```

If your intent is to allow only `Hello` objects for `self` (that is, you don't want to enable subclasses for the `Hello` class), you can explicitly annotate the `self` parameter in `f` as `"Hello"`.

```python
class Hello:
    def f(self: "Hello", a: int) -> float:
        return 0.0

    a: dict[str, Callable[["Hello", int], float]] = {"my_f": f}
```

**Comment by Alexandre-SCHOEPP** [comment]
> Pyright (the type checker upon which pylance is built) is correct in generating a type error here.
> 
> In your code sample, the type of parameter `self` has an implicit type of `typing.Self`, not `Hello`. If you replace the type annotation `Callable[["Hello", int], float]` with `Callable[[Self, int], float]`, your code will type check without errors. For more details about the `typing.Self` special form, refer to [this section of the typing spec](https://typing.readthedocs.io/en/latest/spec/generics.html#self).

My code must be compatible with 3.8+ versions, but `Self` was only introduced in 3.11. As such, the correct typing option is impossible for me to fulfill.

I will annotate f with the "Hello" flag, but that is unsatisfying to me, since in my real use-case subclassing would have meaning, and it might happen in a future update.

**Comment by erictraut** [comment]
If you want to use `Self` in older versions of Python, you can use the `typing_extensions` library, which provides back-ports of newer typing features.

Another option is to use `Any` here.

**Comment by Alexandre-SCHOEPP** [comment]
Typing extensions seems like the best solution, thanks !
