### ISSUE TITLE
pandas: read_csv supports any os.PathLike but FilePathOrBuffer doesn't reflect that

### ISSUE THREAD

**Issue by willfrey** [microsoft/pylance-release#602]
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: macOS Catalina 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0

## Expected behaviour

I expect Pylance to allow `os.PathLike` objects as the first argument to `pandas.read_csv(...)`.

## Actual behaviour

Right now, the first argument of the stub for `pandas.read_csv(...)` is `FilePathOrBuffer`, which is defined as

```py3
from pathlib import Path
from typing import AnyStr IO, Union

FilePathOrBuffer = Union[str, Path, IO[AnyStr]]
```

`read_csv(...)` handles `os.PathLike` just fine, [according to the pandas documentation for the function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html).

So would it be possible for you to change `Path` for `PathLike` or `PathLike[str]` in the stubs that you ship?

Thank you!

**Comment by willfrey** [comment]
This was fixed over in the pandas repo. Closing it.

**Comment by jakebailey** [comment]
I'm not sure that fixes it for us, given we have our own set of pandas types.

**Comment by gramster** [comment]
I assume @willfrey means that Pandas expanded their definition of FilePathOrBuffer; will take a look.

**Comment by jakebailey** [comment]
Seems like this was fixed in the first January release and we didn't document it (oops). Closing.
