### ISSUE TITLE
Bug: Code is unreachable

### ISSUE THREAD

**Issue by mfeyx** [microsoft/pylance-release#6028]
Hi there,

Sometimes Pylance states that my "Code is unreachable" even though the code works as expected. For instance, if I use an `if`-statement without an `else`. If I add the else statement the code is "reachable" and not greyed out. (Please find the examples below).

In my understanding the additional `else` is not neccessary and "bad" practice, if you will. 

### python
Python version 3.10.9.final.0 (and others)

### vs code
Version: 1.90.1 (system setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

### pylance
v2024.6.1
(Client) Pylance async client (2024.6.1) started with python extension (2024.8.1)
Pylance language server 2024.6.1 (pyright version 1.1.364, commit 0618acc5) starting

Published
2020-06-30, 22:05:55
Last released
2024-06-14, 02:25:45
Last updated
2024-06-07, 09:08:27
Identifier
ms-python.vscode-pylance

### "Code is unreachable"
![image](https://github.com/microsoft/pylance-release/assets/29640970/2bc848bb-ed13-41cb-bdfd-052a46f6b10b)

```python
import json


def load_json(obj: str) -> list | dict:
    if isinstance(obj, str):
        obj = json.loads(obj)
        return load_json(obj)
    return obj
```

### Code is reachable

![image](https://github.com/microsoft/pylance-release/assets/29640970/cb18c7e8-84f3-435f-a4f1-879e8aa5c5d6)

```python
import json


def load_json(obj: str) -> list | dict:
    if isinstance(obj, str):
        obj = json.loads(obj)
        return load_json(obj)
    else:
        return obj
```

## Repro Steps

- create a new python file
- paste the code

**Comment by erictraut** [comment]
Reachability checks are based on type analysis. The `obj` parameter is declared to be `str`. If we assume that this type declaration is not violated, the conditional expression `isinstance(obj, str)` will always be true. 

Based on the behavior of the code, it looks like the function also accepts values of type `list` and `dict`. If my assumption is correct, then you should adjust the type annotation for the `obj` parameter to be `obj: str | list | dict`. This will eliminate the apparently-unreachable code.

```python
def load_json(obj: str | list | dict) -> list | dict:
    if isinstance(obj, str):
        obj = json.loads(obj)
        return load_json(obj)

    return obj
```

**Comment by bschnurr** [comment]
@mfeyx see this issue. might help with typing. https://github.com/python/typing/issues/182#issuecomment-1320974824

**Comment by erictraut** [comment]
@mfeyx, I took a closer look at this issue because of the inconsistency you pointed out in your bug report between the code that uses an `else` and the code that does not. These should be equivalent, so you should see "unreachable code" in both cases. This inconsistency was due to a bug in the reachability code in pyright. It will be fixed in the next release of pyright and in a future release of pylance.

**Comment by StellaHuang95** [comment]
Thanks Eric. I will keep this issue open until Pylance releases the fix.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246101-20-June-2024-PreRelease)

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246102-25-June-2024-PreRelease)

**Comment by randori-ddejohn** [comment]
I'm seeing similar behavior where Pylance considers code unreachable because of an exhaustive `if-elif` on a `Literal` type, but the input values of this function are not actually validated. Pylance shouldn't be considering this unreachable since it's still possible to send something into this function that would raise the error.

To reproduce:

```python
from typing import Callable, Literal

InputType = Literal["a", "b", "c"]

def get_callable(input_type: InputType) -> Callable[[str], str]:
    if input_type == "a":
        return lambda x: input_type + x
    if input_type == "b":
        return lambda x: input_type + x
    if input_type == "c":
        return lambda x: input_type + x
    raise ValueError("unsupported input type")  # Pylance reports code is unreachable, but this is incorrect
```

Pylance should not be reporting code as unreachable just based on type analysis since types in Python are not validated at runtime.

**Comment by rchiodo** [comment]
The unreachable error is based solely on type analysis. That's what Eric is referring to [above](https://github.com/microsoft/pylance-release/issues/6028#issuecomment-2175118298).

For more information about this discrepancy, see these issues:
https://github.com/microsoft/pylance-release/issues/5776
https://github.com/microsoft/pylance-release/issues/6106

**Comment by randori-ddejohn** [comment]
> The unreachable error is based solely on type analysis. That's what Eric is referring to [above](https://github.com/microsoft/pylance-release/issues/6028#issuecomment-2175118298).

Yes, that's what I'm responding to. I'm saying it shouldn't be.
