### ISSUE TITLE
Please add the support for function jumping feature when using importlib

### ISSUE THREAD

**Issue by sishau** [microsoft/pylance-release#6031]
when importing libraries using regular import statement, I am able to jump to the function definition by pressing ctrl+left click. However, this functionality is missing when using importlib for importing libraries. It would be greatly beneficial if this feature could be added to improve the overall usability of the project.
![image](https://github.com/microsoft/pylance-release/assets/33338075/52862b40-e47e-471a-89b9-fd5ec95ea0ae)
![image](https://github.com/microsoft/pylance-release/assets/33338075/eab53121-d2da-4891-8b7e-8b9a96164796)

**Comment by debonte** [comment]
Your `importlib` approach is too dynamic for a static type checker to handle. You could use `if TYPE_CHECKING` to tell Pylance which imports you want it to consider at type checking time.

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    if my_args.project == 'projectA':
        from lib.projectA import libx
    elif my_args.project == 'projectB':
        from lib.projectB import libx
    else:
        raise ValueError("Invalid project name")
else:
    libx = importlib.import_module('lib.' + my_args.project + '.libx')

libx.libx().run()
```

**Comment by sishau** [comment]
@debonte No, it's not a problem for me that there are two options when jumping, I can choose them manually. My question is, if I use `importlib.import_module('lib.' + my_args.project + '.libx') `; would it be possible to give the same options as `from... import...` at the jump, instead of saying "No definition of run was found"?

**Comment by heejaechang** [comment]
we are static analyzer, we can't figure out what `my_args.project` will return, so what `'lib.' + my_args.project + '.libx'` expression would result to.

it requires actually running code. `notebook (jupyter extension)` with cell actually ran might be able to provide that information but not `pylance`
