### ISSUE TITLE
Multiple notifications "executing command" but no details on what is being run

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/pylance-release#6048]
![image](https://github.com/microsoft/vscode-python/assets/3840081/348abcb9-55fc-4bb2-a066-20c2343d551c)

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.102, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246102-25-June-2024-PreRelease)
