### ISSUE TITLE
Autocomplete does not suggest custom methods in Enum instancec (items)

### ISSUE THREAD

**Issue by Denis-Alexeev** [microsoft/pylance-release#6058]
## Environment data

-   Language Server version: Pylance language server 2024.6.1 (pyright version 1.1.364, commit 0618acc5) 
-   OS and version: MacOS Sonoma 14.5
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.2 (brew)

## Code Snippet

```python
from enum import Enum

class A(Enum):
    B = "B"

    def visibility(self):
        print("visibility")


A.B.v
```

## Repro Steps

1. Create the code according to code snippet above
2. Type `A.B.v`

## Expected behavior

vscode suggests the method `visibility`

## Actual behavior

vscode does not suggest the method `visibility`

## Logs

<img width="449" alt="image" src="https://github.com/microsoft/pylance-release/assets/52697534/ab9e08cf-dca6-4997-ac81-b97cc72377ee">

## Similar issue
https://github.com/microsoft/pylance-release/issues/4928

**Comment by Denis-Alexeev** [comment]
Oh, I see that the linked issue was re-opened. May be it is worth to close this one. Sorry for bothering guys.

**Comment by heejaechang** [comment]
due of https://github.com/microsoft/pylance-release/issues/4928
