### ISSUE TITLE
Intrusive Intellisense in Interactive Window

### ISSUE THREAD

**Issue by anthonykim1** [microsoft/pylance-release#6065]
It is great that Pylance provides in terms of providing Intellisense and Syntax highlighting for interactive window users. (Now experimental new VS Code specific Python REPL as well which uses interactive window as a backbone excluding some of the features like cell indexing)

Users from user studies testing out the new REPL and the interactive window(provided by Jupyter extension) has came across this glitch in the text input box of the interactive editor where same function definition/hints are provided multiple times without taking regards to the actual small size of the text input box in the interactive editor as a whole. 
/cc @cwebster-99 

Is this a regression? 
<img width="869" alt="Screenshot 2024-06-26 at 10 55 26 AM" src="https://github.com/microsoft/pylance-release/assets/62267334/0f1dbed7-93ac-4b6a-b62c-d1291d469104">

**Comment by rchiodo** [comment]
I believe this is by design. There are a bunch of overloads for the `parse` function and it's showing all of them. VS code itself would be responsible for making the UI smaller (or adding a scroll bar).
