### ISSUE TITLE
Pylance unable to import typing.T

### ISSUE THREAD

**Issue by Ankush-lastmile** [microsoft/pylance-release#6068]
<h3> Environment data </h3>

-   Language Server version: 2024.6.1
-   OS and version: darwin arm64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
from typing import T
```

<h3> Expected behavior </h3>

Pylance Imports object properly

<h3> Actual behavior </h3>

```
"T" is unknown import symbolPylance[reportAttributeAccessIssue](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAttributeAccessIssue)
Type of "T" is unknownPylance[reportUnknownVariableType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownVariableType)
(import) T: Unknown
```

**Comment by erictraut** [comment]
There is no symbol `T` exported from the typing module.

If you want to create a type variable in your code, you should do so using the following:

```python
T = TypeVar("T")
```

Or if you're using Python 3.12 or newer, you can use the new generics syntax introduced in [PEP 695](https://peps.python.org/pep-0695/). This doesn't require importing any symbols from the typing module.
