### ISSUE TITLE
VSCODE-pylance module imports not working after updating miniconda to latest version 24.5.0

### ISSUE THREAD

**Issue by minamulhaq** [microsoft/pylance-release#6073]
## Environment data
Pylance: v2024.6.1
OS: MacOS Sonoma 14.5 
miniconda version: 24.5.0

## Code Snippet
![image](https://github.com/microsoft/pylance-release/assets/25722761/81c63a72-c48e-44fc-a4e7-e898e1fe13d9)
## Repro Steps

1. Open vscode in some folder.
2. Create main.py
3. in same folder create another file content_reader.py and add some class/objects
4. The auto suggestions doesn't find the module 
5. 
![image](https://github.com/microsoft/pylance-release/assets/25722761/9333a49d-cdc9-4fbe-9a69-cc0822ef731f)

6. from main.py, call objects from content_reader.py
7. Pylance shows that modules are not imported so it shows red lines
8. in vscode, press key combitionation for quick fix, it doesn't find the import of modules in same folder. 
9. ![image](https://github.com/microsoft/pylance-release/assets/25722761/6c037df1-7ef2-468a-bed1-854b1b0a8129)
10. Manually import the module and errors in pylance are gone !!! 
11. ![image](https://github.com/microsoft/pylance-release/assets/25722761/5aad0b48-845b-4c8a-80ec-e71887343f12)

## Expected behavior

vscode should find the module in quick suggestions and should also import it. 

## Actual behavior

Modules in same folder are not found. 
## Logs

[log.log](https://github.com/user-attachments/files/16037512/log.log)

**Comment by rchiodo** [comment]
Thanks for the issue. It's because you have indexing turned off. 

Set this setting and it should work again:

```
"python.analysis.indexing": true
```

![image](https://github.com/microsoft/pylance-release/assets/19672699/c2aae648-fade-4e85-98c6-62fed9ce6e55)

**Comment by minamulhaq** [comment]
![image](https://github.com/microsoft/pylance-release/assets/25722761/76a1e5c4-8470-41bf-a9ac-592f12133e08)


Indexing is on. Everything was working fine before I udpated miniconda to latest version.

**Comment by rchiodo** [comment]
Your log says indexing is off. Oh wait, that's for the default workspace. I don't see the settings for the 'logger' workspace. Sorry I didn't check the workspace name in the log when looking at the settings.

Not sure how miniconda can have any effect on indexing of the workspace. 

If you start from scratch (new workspace) does it repro there too?

**Comment by heejaechang** [comment]
the log keep saying this

```
2024-06-29 00:53:52.261 [info] [Error - 00:53:52] (51649) File or directory "/Users/muhammadinamulhaq/Developer/learningNPractice/Python/logger/~/pyEnv" does not exist.
2024-06-29 00:53:52.290 [info] [Info  - 00:53:52] (51649) No source files found.
```

so, any file you opened, `pylance` doesn't see it as a file that belongs to the `workspace`, but a random opened file. and we don't support `add/auto import` for such files.

I think the reason it is happening is due to this setting you have

```
"python.analysis.include": [
    "~/pyEnv/**"
  ],
```

`include/exclude/ignore` only works relative to `workpace (folder)` you opened in `vscode`.  you can't open a folder and include `files` at a random location like you did above.

if your intention is importing files from those, what you want is `python.analysis.extraPath`, not `python.analysis.include`. `~/PyEnv` will work for `extraPath` since that's the purpose of the setting.

**Comment by minamulhaq** [comment]
Seems like Issue is resolved by removing
 
```
"python.analysis.include": [
    "~/pyEnv/**"
  ],

```
![image](https://github.com/microsoft/pylance-release/assets/25722761/9107737d-130a-41cc-8170-760558bebc0c)

![image](https://github.com/microsoft/pylance-release/assets/25722761/dbcdf33d-a1cb-4f57-8911-4aadfe5490ed)

**Comment by minamulhaq** [comment]
I will keep testing to verify the performance. Thanks for the support.
