### ISSUE TITLE
False unreachable code message

### ISSUE THREAD

**Issue by keames1** [microsoft/pylance-release#6074]
Type: <b>Bug</b>

The source file enclosed in the {* and *} below is a work in progress assembler for a homebrew instruction set architecture called rCode; specifically the D1-I5 version. The linter insists a bunch of code is unreachable despite it being above the if __name__ == "__main__" boilerplate. By all reason everything should be evaluated by the interpretor but it's marking the code as unreachable.
{*
'''
    An assembler for my D1-I3 8-bit processor designed to
    run in emulation or be implemented in Minecraft
    Redstone.

    A brief explanation of the register file seems in
    order before diving into the instruction set.
    
0-3:The s registers: s0, s1, s2 and s3 are the top of the
    stack. They can generally be used like normal GPRs,
    but when stack pushes or pops happen, or sp changes
    for any reason, they get dumped into memory and
    repopulated with whatever sp is pointing to. S0 = [sp],
    s1 = [sp + 1], etc.

4:  Ban is used in sx concatination addressing mode. Ban
    is the high byte; an sx register is the low byte.

5:  por is used to store port numbers when doing IO. The
    rest of the time, it can be used as a scratch register.
    Importantly, moves of 16-bit to 8-bit or vice-versa
    read or write 2 consecutively enumerated 8-bit
    registers. por is the one after s3, so its the low
    byte of s3.

6,7:SP and PC are the stack pointer and program counter.
    Pretty straightforward.

    Also, we're big-endian in this house, dammit! There
    will be no argument! Take that little-endian heresy
    elsewhere!

Addressing Modes:

    sx Concatination (Enumeration: 0-3):
        Memory is addressed by using the ban as the high byte
        of an address to which an s register is the low byte.

    Immediate (Enumeration: 4):
        The byte following an instruction is read to the
        destination register.

    Absolute (Enumeration: 5):
        The two bytes immediately following the instruction
        are read as an address and used to load/store a byte
        to/from memory.

    zero page indirect (Enumeration: 6):
        The effective address is a pair of bytes stored at a
        location in the zero page indicated by the byte following
        the instruction

    Zero page (Enumeration: 7):
        Addresses to first 256 bytes of RAM like on a 6502
        with a single immediate byte.

'''

# Below is a 16 * 16 grid of visible characters. The
# horizontal axis represents the high nybble
# (most significant) 4 bits of the instruction byte and
# the vertical is the low nybble. 0x00 is the top left
# corner. Below that, is a key indicating which instruction
# each character represents with a brief description of
# its function.

"""
#  0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
0  N  M  M  M  M  M  M  M  L  L  L  L  L  L  L  L
1  M  H  M  M  M  M  M  M  L  L  L  L  L  L  L  L
2  M  M  =  M  M  M  M  M  L  L  L  L  L  L  L  L
3  M  M  M  i  M  M  M  M  L  L  L  L  L  L  L  L
4  M  M  M  M  d  M  M  M  I  +  +  +  D  -  -  -
5  M  M  M  M  M  r  (  )  +  I  +  +  -  D  -  -
6  M  M  M  M  M  /  R  M  +  +  I  +  -  -  D  -
7  M  M  M  M  M  \  M  C  +  +  +  I  -  -  -  D
8  S  S  S  S  *  S  S  S  <  &  &  &  !  O  O  O
9  S  S  S  S  *  S  S  S  &  <  &  &  O  !  O  O
A  S  S  S  S  *  S  S  S  &  &  <  &  O  O  !  O
B  S  S  S  S  *  S  S  S  &  &  &  <  O  O  O  !
C  E  ?  ?  ?  X  X  X  X  V  V  V  V  W  W  #  #
D  ?  E  ?  ?  X  X  X  X  ^  ^  ^  ^  %  %  @  $
E  ?  ?  E  ?  X  X  X  X  ~  ~  ~  ~  0  0  0  0
F  ?  ?  ?  E  X  X  X  X  J  J  J  J  J  J  J  J

Child instructions: These are instructions containing 0
or 1 parameters inserted into the codespace regions of
instructions that require multiple parameters to conserve
codespace by eliminating useless instructions; like moves
of a register into itself, or comparisons of a register
with itself. For example, 0x00 is nominally a

mov   s0  s0

but that would do nothing, so it's treated like a
do nothing; a nop instruction.

T  P          D                                                    A L U E
a  n          e                                                    s a s x
b  e          s                                                    s n a a
l  u          c                                                    e g g m
e  m          r                                                    m u e p
   o          i                                                    b a   l
S  n          p                                                    l g   e
y  i          t                                                    y e  (s)
m  c          i                                                        
b             o                                                        
o             n                                                         
l                                                                     

N - nop     ; No operation.                                     | nop
H - hlt     ; Halt execution.                                   | hlt
= - syscall ; A software interrupt instruction. This is         | syscall
            ; futureproofing for possible operating system      |
            ; development and other related fanciness.          |
i - inc sp  ; An instruction specifically for incrementing      | inc sp
            ; the stack pointer.                                |
d - dec sp  ; An instruction specifically for decrementing      | dec sp
            ; the stack pointer.                                |
r - rfi     ; Return from interrupt.                            | rfi
( - clc     ; Clear the carry flag.                             | clc
) - sec     ; Set the carry flag.                               | sec
/ - ext0    ; Execute the following byte(s) as an               | mul s0, s1 ; The extension prefix byte
            ; extension 0 instruction rather than as part       |            ; would be generated by the
            ; of the base instruction set.                      |            ; assembler
\ - ext1    ; Execute the following byte(s) as an               | fpadd zp[0]%64, zp[8]%64
            ; extension 1 instruction rather than as part       |            ; Same as ext0, assembler will
            ; of the base instruction set.                      |            ; translate this with the prefix.
R - ret     ; Return from call. Just a garden variety           | ret
            ; return instruction.                               |
C - cal     ; Call a function at an absolute address            | cal foo
I - inc     ; Increment one of the s registers.                 | inc s3
D - dec     ; Decrement one of the s registers.                 | dec s2
* - dup     ; Duplicate one of the s registers to the top       | dup s0
            ; of the stack. The s registers are actually        |
            ; mapped to sp, sp + 1... so this is useful         |
            ; for passing locals by value.                      |
< - jss     ; Jump if sign set. Please note that all            | jmp s, loop
            ; conditional jumps support the same                |
            ; addressing modes: immediate, direct, sp offset    |
            ; and zero page. Their enumerations in this         |
            ; case, however are 0-3, not 4-7.                   |
! - jcs     ; Jump if carry set.                                | jmp c, switchStmtDefault
E - jos     ; Jump if overflow set.                             | jmp o, ERROR_CODE
                                                                |
Parent instructions: These are instructions requiring one       |
or more parameters. Their positioning in the codespace is       |
decided such that those parameters are attainable by bit        |
banging; though they vary in length they're always              |
enumerated from 0 and they always begin at the least            |
significant bit of each nybble.                                 |
                                                                |
M - mov     ; Copy a register into another register. If the     | mov s2, sp
            ; registers differ in length, the next              |
            ; consecutively enumerated register will be used    |  
            ; as a least significant byte For instance,         |
            ; mov   sp  s0                                      |
            ; will put s0 in the most significant byte of sp and|
            ; s1 in the least significant byte.                 |
            ; mov   s0  sp                                      |
            ; will write the most significant byte of sp        |
            ; to s0 and the least significant byte to s1.       |
            ; rCode is big-endian, can you tell? I hear         |
            ; you little-endian heritics groaning and I'll      |
            ; have none of it!                                  |
L - lod     ; Load from memory. This pneumonic is               | mov s2 abs[message]
            ; supported, but the                                | mov s0 zp[messageLen]
            ; mov   reg [addressing mode]                       |
            ; syntax is preferred. Low 2 bits of the low        |
            ; nybble indicate an sx register, low 3 of the      |
            ; high nybble indicate an addressing mode.          |
+ - adc     ; Add any two of the s registers and store the      | clc
            ; sum in the first. The carry is always added       | adc s0, s2
            ; and must be explicitly cleared during the         | adc s1, s3 ; What a 16-bit add would look
            ; addition of the first pair of addend bytes.       |            ; like. ;-)
- - subb    ; First argument is the minuend, second is the      | sec
            ; subtrahend. Works on any s register and           | subb s0, s2
            ; stores the difference in the minuend.             | subb s1, s3
            ; The carry is always borrowed and must always      |
            ; be set before doing the subtraction on the        |
            ; least significant bytes of the operands.          |
S - sto     ; Store to memory. This pneumonic is                | mov zpi[usefulPointer], s2
            ; supported, but the                                | mov ban[s3], s1
            ; mov   [addressing mode]   reg                     |
            ; syntax is preferred. Low 2 bits of the low        |
            ; nybble indicate an sx register, low 3 of the      |
            ; high nybble indicate an addressing mode.          |
& - and     ; Bitwise and of any 2 s registers. This            | and s2, s0
            ; stores the result in the first operand; as        |
            ; in any bitwise operation.                         |
O - or      ; Bitwise or of any 2 s registers.                  | or  s0, s3
? - cmp     ; Subtracts the second operand from the first       | cmp s3, s2
            ; and sets the flags accordingly. Doesn't           |
            ; store the result.                                 |
X - xor     ; Bitwise exclusive or.                             | xor s3, s2
V - bsr     ; Bit shift right of any s register.                | bsr s0
^ - bsl     ; Bit shift left of any s register.                 | bsl s2
~ - not     ; Bitwise not of any s register.                    | not s3
J - jmp     ; Jump unconditionally to address obtained by       | jmp break
            ; any of the 8 supported addressing modes.          |
W - in      ; Read from the port whose port number is in        | in s0
            ; the port register (por) into s0 or s1.            | mov s1, imm[DISK_PORT]
% - out     ; Write the port whose port number is in por the    | mov por, s1
            ; contents of s0 or s1.                             | out s0
# - spa     ; SP ADD: Sign extend s0 or s1 to 16 bit and        | spa s1
            ; add to sp.                                        |
@ - dum     ; Dump: Pops 4 values off the stack (the s          | dum zp[0x80]
            ; registers) and stores them at a zero page         |
            ; address.                                          |
$ - fil     ; Fill: Pushes 4 items from a zero page address     | fil zp[0x32]
            ; onto the stack, populating all the s registers    |
            ; with new values.                                  |
0 - jzs     ; Jump zero set.                                    | jmp z, exitRoutine
"""

"""
Continuing the pattern of this being equal parts design doc and implementation,
it's time to start fleshing out the details of the assembly language design.
Due to the limits of a 256 point codespace, each instruction has at most 2
operands and the processor is a load/store architecture. In hope of simplifying
parsing and making the code more readable, all addressing modes other than
absolute are explicitly marked by their addressing mode name followed by
specific information like a zero-page address or a register in square brackets.

For example:

    A label, an integer literal or a constant will be recognized as an absolute
    address in instructions requiring one as one of its operands. However,
    abs[someInteger] will also be recognized by the assembler for consistencys
    sake.

    ban[s register] will be used for sx concat addressing mode.

    zpi[<Thing that evaluates to an 8-bit integer>] is the syntactic representation
    of a zero-page indirect.

    zp[i8] will be used for zero page access.

    <thing that evaluates to i8>.i will signify immediate addressing mode. If it's in
    the range -128 to 256, the assembler will recognize it as fitting in 8 bits.

"""
from enum import *
import sys
import argparse
# Helper functions:
def substituteExtension (filePath: str, extension: str) -> str:
    intermediateSplit: list = filePath.split(".")
    incompletePath: str = ""
    for i in intermediateSplit[:-2]:
        incompletePath += i + "."
    
    return incompletePath + extension

# Assembly related functions and classes:

@unique
class LexState (Enum):
    NEW_TOKEN = auto()
    NUMERIC = auto()
    ALPHANUMERIC = auto()
    KEYWORD = auto()
    DIRECTIVE = auto()
    STRING = auto()
    FORMAT_STRING = auto()
    CHAR = auto()
    MACRO = auto()

class Token:
    pass

class Lexer:
    def __init__ (self, srcString):
        self._srcString = srcString
        self._tokens = self.genTokens()
    
    def genTokens (self):
        state: LexState = LexState.NEW_TOKEN
        nextState: LexState = LexState.NEW_TOKEN
        srcIdx: int = 0
        accumulatedStr: str = ""
        self._tokens: list[Token] = []
    
    while True:
        pass

class AbstractSyntaxTree:
    pass

def genCode (tree) -> bytearray:
    pass

def assemble (srcString: str) -> tuple[Lexer, AbstractSyntaxTree, bytearray]:
    binary: bytearray = b""

    lex: Lexer = Lexer(srcString)
    tree: AbstractSyntaxTree = AbstractSyntaxTree(lex)
    binary = genCode(tree)

    return binary

def main ():
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        sys.argv, description = "An assembler which targets the rCode D1-I5 processor architecture,\n\
 converting its assembly language into hexadecimal or binary (hlod or\n\
 lod) files for loading into memory and execution."
    )
    parser.add_argument("sourceFile", help="The file to be assembled.")
    parser.add_argument("-o", "--outputFile", type = str, default=None, help="The output to be written. If not supplied, it defaults to sourceFile with the .s extension replaced with '.lod' or '.hlod' as appropriate depending on whether '-x' is included.")
    parser.add_argument("-x", "--hexadecimal", action="store_true", help="Store the load file in a hexadecimal format rather than binary.")
    parser.add_argument("-l", "--listing", action="store_true", help="Print a listing of the assembled program to console after assembly.")
    parser.add_argument("-pl", "--writeListing", default=None, help="Write a listing of the assembled program to a file.")
    
    class _:
        sourceFile: str
        outputFile: str
        hexadecimal: bool
        listing: bool
        writeListing: bool

    args: _ = parser.parse_args(namespace=_())

    # This logic is designed to determine a default name for the assembler output if
    # args.outputFile isn't supplied by the user. It also informs the user if they use
    # .hlod extension on their output file, inconsistent with an included with a -x
    # argument, printing an error message and exiting.
    if args.hexadecimal and args.outputFile:
        if len(args.outputFile) > 4:
            if args.outputFile[-4:] == ".lod":
                print(f"Error: -x was included yet the destination '{args.outputFile}' ends in a binary '.lod', not hexadecimal '.hlod' extension.")
                exit()
    
    if args.outputFile:
        if len(args.outputFile) > 5:
            if args.outputFile[-5:] == ".hlod":
                args.hexadecimal = True
    
    if not args.hexadecimal and not args.outputFile:
        args.outputFile = substituteExtension(args.sourceFile, "lod")

    elif args.hexadecimal and not args.outputFile:
        args.outputFile = substituteExtension(args.sourceFile, "hlod")

    srcString: str
    try:
        with open(args.sourceFile, "r") as f:
            srcString = f.read()
    
    except FileNotFoundError:
        print(f"Error: The file '{args.sourceFile}' does not exist.")
        exit()
    
    ## That's enough UI stuff done, It's time for assembly time!!!
    binary: bytearray = assemble(srcString)

if __name__ == "__main__":
    main()
*}

Extension version: 2024.6.1
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.23GB free)|
|Process Argv|--crash-reporter-id 37cd7278-7b18-442d-83bc-07e9ccda0db8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870

```

</details>

**Comment by rchiodo** [comment]
Thanks for the issue, but can you clearly state where the issue is? We really only need to see the python code with the 'unreachable' problem. 

Most of the time false 'unreachable' code is caused by incorrect or incomplete type annotations.

See this example:
https://github.com/microsoft/pylance-release/issues/5776
