### ISSUE TITLE
`reportShadowedImports` diagnostic missing in `codeaction.py` test file

### ISSUE THREAD

**Issue by debonte** [microsoft/pylance-release#6087]
## Environment data
-   Language Server version: 2024.6.100
-   OS and version: Windows 11 and Ubuntu 22.04.3 LTS
-   Python version: 3.12.1

## Repro Steps

1. Open VS code on pylance-release\testing\single
2. Install the requirements.txt
3. Open the `codeaction.py` file and observe the `import mailbox` line near the bottom.

I tried creating a simpler project and this did **not** repro for me:
1. Open new folder in VS Code.
2. Create empty `mailbox.py`
3. Create `test.py` containing `import mailbox`

## Expected behavior

`reportShadowedImports` diagnostic reported on `mailbox`

![image](https://github.com/microsoft/pylance-release/assets/12820898/10facfa2-ca5e-43c2-a849-298657e16e99)

## Actual behavior

No diagnostic. Works as expected in 2024.6.1. Regressed in 2024.6.100.

![image](https://github.com/microsoft/pylance-release/assets/12820898/301cec15-dd62-4ce4-a634-ada19ed556b5)

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.6.104, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20246104-3-July-2024-PreRelease)
