### ISSUE TITLE
vscode.dev Python extension spit out multiple console errors - Pylance 404.

### ISSUE THREAD

**Issue by chiaolinghong3d** [microsoft/pylance-release#6089]
## Environment data

-   Language Server version: 2024.6.1
-   OS and version: Chrome (Version 126.0.6478.127)
-   Python version (& distribution if applicable, e.g. Anaconda): v2024.8.1

## Repro Steps

1. Open up `vscode.dev` in Chrome.
2. Install **Python** extension -> Select "Install anyway"
3. Open a python file.
4. Open up console, sees multiple console errors:
<img src="https://github.com/microsoft/vscode/assets/39775868/9375d2ce-723a-4220-93b9-c07603fef8db" width="750" />

5. **Pylance 404 error** when trying to fetch **Pylance package.nls.en-us.json** at https://ms-python.vscode-unpkg.net/ms-python/vscode-pylance/2024.6.1/extension/package.nls.en-us.json

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by rchiodo** [comment]
Thanks for the issue. That's expected. If that happens it falls back to the default nls.json which happens to already be `en-us`.
