### ISSUE TITLE
Unresolved import warnings

### ISSUE THREAD

**Issue by earlybird3010** [microsoft/pylance-release#6098]
## Environment data

-   Language Server version: v2024.6.1
-   OS and version: Microsoft Windows 11 Home 10.0.22631 Build 22631
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.4 

## Code Snippet

import sys
import os

lecture11_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../Lecture11'))

sys.path.insert(0, lecture11_path)

from linked_list import *

print(link(1, link(2, empty)))

## Repro Steps

1. Create 2 subfolders in my CS61A folder: Lecture11/ and Lecture16/
2. Create linked_list.py in Lecture11/
3. Create implement_sequence.py in Lecture16/ which contains the code snippet above
4. Add .vscode/settings.json to CS61A folder, which contains 
{
    "python.analysis.extraPaths": ["./Lecture11"]
}

## Expected behavior

Pylance doesn't show any error with import statement

## Actual behavior

Pylance shows: Import "linked_list" could not be resolved, but the code works fine. I tried using some of the functionalities from linked_list module and it works.

## Logs

```
XXX
```

**Comment by erictraut** [comment]
Your code is dynamically modifying the import resolution paths. Static analysis tools like pylance, mypy, linters, etc. do not understand such dynamic modifications. Keep in mind that static analysis tools don't actually execute your code.

If you want your code to work with static type checking, you should either avoid dynamic modification of import resolution paths or you can tell the tool that you are modifying the paths by adding the additional path(s) to the `extraPaths` setting.

**Comment by earlybird3010** [comment]
Ah, I understand where the mistake is. I didn't open the folder CS61A, so even after I added a .vscode/settings.json file with the additional path added to the extraPaths setting in that folder, the Python server doesn't treat it as the main root of user module imports. Thanks for your help!
