### ISSUE TITLE
Introspection of top-level type variables

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#61]
Disclaimer: I'm not sure if it should be a feature request or a bug report.

## Environment data
-   VS Code version: 1.46.1
-   Extension version (available under the Extensions sidebar): v2020.6.91350
-   OS and version: macOS 10.14.6 (18G103)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6.10 (conda create -n ... python=3.6.10)
-   Type of virtual environment used: conda
-   Value of the `python.languageServer` setting: the problem is with both Jedi/Microsoft

## Description
```python
class ThirdPartyClass:
    """Docstring."""
    def __init__(self, x):
        self.x = x
    
class MyMixin:
    pass


B = type('B', (ThirdPartyClass, MyMixin), {})
```

Now, if start typing `B(` no documentation show up, neither (1) for `__init__` nor (2) for B itself.
Changing the last line to this:
```python
B = type('B', (ThirdPartyClass, MyMixin), {'__doc__': Path.__doc__})
```
doesn't help.

P.S. Regular inheritance performs slightly better: `__init__`'s signature shows up, but without docstrings (which is a problem, since `__init__`'s arguments are usually described in class docstrings).

**Comment by erictraut** [comment]
Why would you use a direct call to the `type` constructor to create a class rather than using the `class` statement? I assume this is used only for dynamic types — those that can't be described statically?

Pylance/Pyright is a static type analyzer, and as such it uses information that can be statically determined. It doesn't run the code, so it can't "introspect" runtime objects for properties.

**Comment by Yura52** [comment]
My goal is to add a mixin to third-party entities (as shown in the example) without compromising documentation and autocompletion features. Using `type` simply makes code more compact when creating 10 subclasses, so it is not mandatory. Anyway, as I described in "P.S.", conventional mechanism (i.e. the `class` keyword) doesn't achieve the goal either. What is the proper way to solve my problem?

**Comment by erictraut** [comment]
Unfortunately, I don't see a good solution that meets all of your constraints.

You could use normal inheritance and copy the class docstring (the actual string literal) into your derived class, but I'm guessing that you don't want to do that for maintenance reasons.

Maybe there's something you could do with a class decorator to dynamically inject the functionality of your mix-in class into the original class when it's instantiated?

**Comment by Yura52** [comment]
I see. Thanks for the answer and the suggestion!
