### ISSUE TITLE
No code suggestion appears. Error: Language server extension command failed.  Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found

### ISSUE THREAD

**Issue by kuolemaaa** [microsoft/pylance-release#6104]
Never managed to make it work since 1 year. And nothing changed.

code 1.90.0-1
pylance 2024.6.1
intellicode 1.3.1
python 3.12.4-1

---

```
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.
```

---

Output: Python
```
2024-07-07 12:59:58.057 [info] Default formatter is set to null for workspace /home/user/ws/project
2024-07-07 12:59:58.064 [info] Python interpreter path: ./.venv/bin/python
2024-07-07 12:59:58.089 [info] > pyenv which python
2024-07-07 12:59:58.089 [info] cwd: .
2024-07-07 12:59:58.411 [info] Starting Pylance language server.
2024-07-07 12:59:58.419 [info] Send text to terminal: source /home/user/ws/project/.venv/bin/activate
2024-07-07 13:00:05.372 [info] Discover tests for workspace name: project - uri: /home/user/ws/project
```

---

output: VS Intellicode
```
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Acquiring model 'intellisense-members-lstm-pylance' for python
vs-intellicode-python was passed a model: {}.
Found bundled model for python
Activating Python extension
Language server extension command failed. Exception: Error: command 'python.intellicode.loadLanguageServerExtension' not found
    at v.n (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1637:23867)
    at v.executeCommand (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1637:23796)
Error while activating Python: {}
```

**Comment by rchiodo** [comment]
This should be a bug in intellicode: https://github.com/MicrosoftDocs/intellicode/issues/509.

Looking at intellicode's source, my only guess is that you don't have `python.languageServer` set to 'Default'. 

![image](https://github.com/microsoft/pylance-release/assets/19672699/1e0df9a2-5a6b-40d0-8d50-338cf162e760)

Their code might have a bug in the order in which they load the extensions. If `python.languageServer` is `Default`, they will end up loading Pylance before they attempt to call `python.intellicode.loadLanguageServerExtension` so then the command should work. If it's not set to `Default`, I don't think it's guaranteed Pylance will load soon enough.

**Comment by kuolemaaa** [comment]
> This should be a bug in intellicode: [MicrosoftDocs/intellicode#509](https://github.com/MicrosoftDocs/intellicode/issues/509).
> 
> Looking at intellicode's source, my only guess is that you don't have `python.languageServer` set to 'Default'.
> 
> ![image](https://private-user-images.githubusercontent.com/19672699/346650572-1e0df9a2-5a6b-40d0-8d50-338cf162e760.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NTkxMzksIm5iZiI6MTcyMDQ1ODgzOSwicGF0aCI6Ii8xOTY3MjY5OS8zNDY2NTA1NzItMWUwZGY5YTItNWE2Yi00MGQwLThkNTAtMzM4Y2YxNjJlNzYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE3MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YWY4Y2UwZjFlM2U2NDhlYWY2ZmI2ZDJhMTVmY2NlMGU0NWJmYWY2MGE4ZDg3YjEwNzk5YzQxNjhhZjJkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8gxrLor1geQpXxQKK7MG7-rj-GKiUNxJ1W-DmqkO7OQ)
> 
> Their code might have a bug in the order in which they load the extensions. If `python.languageServer` is `Default`, they will end up loading Pylance before they attempt to call `python.intellicode.loadLanguageServerExtension` so then the command should work. If it's not set to `Default`, I don't think it's guaranteed Pylance will load soon enough.

Set in 'Default': still same issue but thanks for trying
