### ISSUE TITLE
Split (or hide) multiple overloads in tooltips for functions

### ISSUE THREAD

**Issue by christopherdwelton** [microsoft/pylance-release#612]
Intellisense tooltips for autocomplete selection have a newline between each overload, which helps immensely with legibility. (It could even be argued a bit of extra space between the overloads wouldn't go amiss.)

![autocomplete](https://user-images.githubusercontent.com/74527014/99219575-d0196b00-2791-11eb-85b1-6584e13bedfc.png)

Hovering over the same symbols after they are in the code, however, brings up a huge monolithic wall of text that is almost less useful than the old "Jedi" or "Microsoft" language server tooltips, just due to the shear amount of clutter.

![overload](https://user-images.githubusercontent.com/74527014/99219670-035bfa00-2792-11eb-8bf8-3bef051ae33f.png)

I believe this would look much better with newlines separating the overloads as is already the case in the autocomplete version.

**Comment by bejota** [comment]
I agree this is unusable. I prefer the original code doc.

**Comment by jakebailey** [comment]
They should definitely match (but we know that these tooltips can get unwieldy due to overloads / large signatures in general).

**Comment by taldcroft** [comment]
Adding to this, many of the code docs have become unusable in Pylance to the point where I'm switching back to Jedi for the time being despite many great features of Pylance.

### Jedi (gives information I need)

![image](https://user-images.githubusercontent.com/348089/99811618-67284f00-2b13-11eb-8181-0c5961d3b32a.png)

### Pylance (not useful for me)

I am also unable to scroll within that tooltip window to get to the actual docstring.

![image](https://user-images.githubusercontent.com/348089/99811573-58419c80-2b13-11eb-84f3-fd4099543e2e.png)

**Comment by timqsh** [comment]
I'm having the same issue. Docstrings for functions in `itertools` module and builtins like `map` and `zip` are lost when I switch language server to Pylance.

**Comment by jakebailey** [comment]
The next release splits the big `Overload` line into individual lines, matching the completion tooltip. Also, in cases where the tooltip is long (wider than VS Code's default width for each tooltip), an extra newline will be added to help distinguish it.

This is an incremental improvement; we may consider more significant changes like hiding all but the currently-matching overload on hover or completion (similar to TS and C#), but that will require a bit more consideration.

**Comment by jakebailey** [comment]
The case in https://github.com/microsoft/pylance-release/issues/612#issuecomment-731206793 is unrelated; that's more about docstring mapping, where itertools is actually compiled code within the python interpreter itself where we can't access it, so will be handled in the same way as #465 (which I'll retitle to be broader).

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202131-10-march-2021
