### ISSUE TITLE
warning on some imported package

### ISSUE THREAD

**Issue by HadiMoosavi** [microsoft/pylance-release#6126]
## Environment data

-   Language Server version: v2024.7.1
-   OS and version: Windows 10 Enterprise
-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0 64 bit

## Code Snippet

```python
from openseespy.opensees import *
wipe()
```

## Repro Steps

1. XXX

## Expected behavior

wipe() is part of the package and the code runs well but I still get the warning that the method is not defined.
strangely, when I use:

import openseespy.opensees as ops
ops.wipe()

the warning goes away.

## Actual behavior

There should be no warning

## Logs

```
XXX
```

**Comment by debonte** [comment]
With your initial code...

```python
from openseespy.opensees import *
wipe()
```

...the diagnostic that I see is `"wipe" is not defined`.

If I make the change you suggested...

```python
import openseespy.opensees as ops
ops.wipe()
```

...I still see a diagnostic, which is effectively the same thing -- `"wipe" is not a known attribute of module "openseespy.opensees"`

There are a few issues that are preventing Pylance from handling `openseespy` well:
1. `openseepy/opensees/__init__.py`, which you can get to by "go to def" on `opensees`, imports the platform-specific module within a `sys.platform.startswith` check which we do not support. We only support simple equality checks on `sys.platform` as specified by [PEP 484](https://peps.python.org/pep-0484/#version-and-platform-checking).
2. Even if that worked, the platform-specific packages are implemented in native code (not Python), so Pylance doesn't understand what symbols are exposed by those packages. You may want to ask the `openseespy` maintainers if [type stubs](https://microsoft.github.io/pyright/#/type-stubs?id=importance-of-type-stub-files) are available.
