### ISSUE TITLE
False positive: "is possibly unboundPylance (reportUnboundVariable)"

### ISSUE THREAD

**Issue by DanielAtKrypton** [microsoft/pylance-release#614]
## Environment data

-   Language Server version: v2020.11.1
-   OS and version: Microsoft Windows 10 Pro Version 10.0.19041 Build 19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7

## Expected behaviour

No pylance error should be reported in the snippet below. Because the code will either produce `candles` artifact or return `True` when retrials were elapsed.

## Actual behaviour
![Imgur](https://i.imgur.com/AnJ9KpP.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
for i in range(1 + self.number_of_retrials):
    try:
        candles = self.exchange.fetch_ohlcv(self.pair, self.timeframe_str, since, self.limit, self.params)
        break
    except:
        if (i == self.number_of_retrials):
            logging.warn("Aborted fetching ohlcv!")
            return True
        # Sleep for a while then retry
        time.sleep(self.retry_sleep_time)
        logging.debug("Retrying for the {} time".format(i+1))

self.queue.put(candles)
```

**Comment by erictraut** [comment]
A `for` loop is not guaranteed to execute. The iterable value can return zero items. In this particular case, it appears that the code is safe, but a static type checker has no way of knowing that the for loop will execute at least once. A recommended practice is to initialize variables before the loop if you intend to use them after the loop.

**Comment by DanielAtKrypton** [comment]
Thank you @erictraut !
