### ISSUE TITLE
Asyncio.TaskGroup doc string causes parsing error

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#6143]
I came to report another issue with RST support.
It seems like it might not be related.
Let me know if you would like me to create a distinct issue for it.

With RST support true:
![image](https://github.com/user-attachments/assets/9e312d06-5aa4-404a-9ba6-a4397aa1af0b)

With RST support false:
![image](https://github.com/user-attachments/assets/ee6d86c5-9223-4706-be44-8760586dcf60)

Code:
```python
import asyncio

asyncio.TaskGroup()
```

> Thank you so much. Unselecting that check box did indeed solve the problem described in the above ticket. I left a screenshot here for anyone else that comes across this thread.

You can also just put the full path of the param in the search to only get 1 result.
![image](https://github.com/user-attachments/assets/b6d018dc-b2be-4388-a26c-44776841e22b)

_Originally posted by @mheguy in https://github.com/microsoft/pylance-release/issues/6127#issuecomment-2227554101_

**Comment by heejaechang** [comment]
This issue has been fixed in prerelease version 2024.7.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20247101-22-July-2024-PreRelease)
