### ISSUE TITLE
Pylance suggests bad completions

### ISSUE THREAD

**Issue by cdeil** [microsoft/pylance-release#6145]
Type: <b>Bug</b>

0. Create some Python env with plotly installed
1. Open a new file `app.py`
2. Type `import plotly.express as px`
3. Pylace suggests bad completions on "as" and "px"

With PyLance `v2024.7.1`

See Screenshots:

<img width="1045" alt="Screenshot 2024-07-15 at 20 16 09" src="https://github.com/user-attachments/assets/e5a6c1da-442c-42d3-824e-22f67ca3c982">
<img width="1017" alt="Screenshot 2024-07-15 at 20 15 59" src="https://github.com/user-attachments/assets/9fed05fc-1b4b-4ba7-a2c3-ecc2b9550235">
<img width="1003" alt="Screenshot 2024-07-15 at 20 15 46" src="https://github.com/user-attachments/assets/d8218821-16ef-4453-ae70-f3e2724e7888">

---

Extension version: 2024.7.1
VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by debonte** [comment]
I can repro what you show in your first screenshot, but I don't think that's a bug -- it's just how our parser chose to recover from the incorrect syntax. Pylance provided an error on the `from` (expected symbol) and then started parsing from the `from` as a new import statement.

I'm not able to repro what you're showing the second and third screenshots. Could these completion suggestions be from another extension? Can you try disabling all of your extensions other than Python and Pylance and see if this still happens?

**Comment by cdeil** [comment]
When I disable the Django v1.15.0 extension the bug disappears.

Can you try to reproduce with https://marketplace.visualstudio.com/items?itemName=batisteo.vscode-django ?

**Comment by cdeil** [comment]
cc @batisteo

Is this an issue in Pylance or the Django extension or some interaction?

**Comment by debonte** [comment]
This repros with the Django extension installed and Pylance disabled, so it's a Django extension bug.

**Comment by cdeil** [comment]
OK, thanks. I filed the issue with them here: https://github.com/vscode-django/vscode-django/issues/181
