### ISSUE TITLE
Type narrowing is broken for `if-elif`

### ISSUE THREAD

**Issue by benglewis** [microsoft/pylance-release#6148]
## Environment data

-   Pylance version: 2024.7.1
-   OS and version: macOS 14.5 (but it also reproduces on Windows)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.4 (from `https://conda.anaconda.org/conda-forge/osx-arm64/python-3.12.4-h30c5eda_0_cpython.conda` )

## Code Snippet

```python
def fn(a: str | None, b: list[int] | None):
    if a is None and b is None:
        raise ValueError("a and b cannot be both non-None")
    elif a is not None:
        print(a)
        b = [1]
    
    b.pop()
```

## Repro Steps

Copy-paste code and use `pylance`

## Expected behavior

`b` should be detected as a `list[int]` type. This is because, either `a` and `b` were `None`, in which case, an exception was raised or `a` is not None and thus, `b` was defined as a `list[int]` or `b` (by-definition from the first if), must be not-`None` and thus a `list[int]`.

## Actual behavior

`b` is still considered `list[int] | None` and thus, the `pop` call is considered invalid.

**Comment by benglewis** [comment]
I'm not sure if it is important information, but the same problem also occurs with `match` cases too.

```python
def fn(a: str | None, b: list[int] | None):
    match a, b:
        case None, None:
            raise ValueError("a and b cannot be both non-None")
        case str(), None:
            print(a)
            b = [1]

    b.pop()
```

**Comment by nineteendo** [comment]
This works as intended. Relations between types are not considered, but you can use an `assert` to tell this to the type checker:

```python
from typing import reveal_type

def fn(a: str | None, b: list[int] | None):
    if a is None and b is None:
        raise ValueError("a and b cannot be both non-None")

    reveal_type(b)  # Type of "b" is "list[int] | None"
    if a is not None:
        print(a)
        b = [1]

    assert b is not None
    b.pop()
```

mypy does the same: https://mypy-play.net/?mypy=latest&python=3.12&gist=12be0a69a580d4a3e9e97719cf8d4eda

**Comment by benglewis** [comment]
OK, that is a little frustrating. Is there some kind of technical explanation as to why? I just checked TypeScript too and I see that it behaves the same way, so it would be great to get a better understanding of why

**Comment by nineteendo** [comment]
This would force all variables to be narrowed at the same time:

```python
reveal_type(a, b) # (str, list[int]) | (None, list[int]) | (str, None) | (None, None)
if a is None and b is None:
    raise ValueError("a and b cannot be both non-None")

reveal_type(a, b) # (str, list[int]) | (None, list[int]) | (str, None)
if a is not None:
    print(a)
    b = [1]

reveal_type(a, b) # (str, list[int]) | (None, list[int])
b.pop()
```

There's an exponential growth of the number of combinations. This is complicated both for us and for type checkers.
There also wouldn't be an obvious way to reveal the type of a single variable anymore.

(Also, you should close this as "not planned")
