### ISSUE TITLE
Chained file crash

### ISSUE THREAD

**Issue by rchiodo** [microsoft/pylance-release#6169]
@otavio-silva's problem is this:
Error: Debug Failure. False expression: Chained file path undefined doesn't match cellFilePaths file:///home/azakun/Documents/Code/Python/notebooks/Stable%20Diffusion%20XL/StableDiffisionXL.ipynb.py#X14sdnNjb2RlLXJlbW90ZQ%3D%3D
    at _0x2ee97f (/home/azakun/.vscode-server/extensions/ms-python.vscode-pylance-2024.7.1/dist/server.bundle.js:1:888452)
    at /home/azakun/.vscode-server/extensions/ms-python.vscode-pylance-2024.7.1/dist/server.bundle.js:1:817188

Not likely the same issue as the original poster. I'll link a new bug.

_Originally posted by @rchiodo in https://github.com/microsoft/pylance-release/issues/6154#issuecomment-2243338275_

**Comment by rchiodo** [comment]
@otavio-silva, can you post a copy of your notebook?

**Comment by otavio-silva** [comment]
> @otavio-silva, can you post a copy of your notebook?


Here: [StableDiffisionXL.zip](https://github.com/user-attachments/files/16337129/StableDiffisionXL.zip)

**Comment by heejaechang** [comment]
@otavio-silva can I get some repro steps if possible? also, can I get `Trace` log as in [the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs)? 

your previous log is `info` level log, so it doesn't contain any detail except the assert.

**Comment by otavio-silva** [comment]
@heejaechang after some investigation, I found out that this is related to the `NO notebook document for 'file//*.ipynb'` error and disabling the Continue extension seems to have solved it for now.

**Comment by KacieKK** [comment]
related to this? https://github.com/continuedev/continue/issues/1463

**Comment by otavio-silva** [comment]
> related to this? [continuedev/continue#1463](https://github.com/continuedev/continue/issues/1463)

Yup, that one. After removing it, can't reproduce any related errors.

**Comment by heejaechang** [comment]
I think this could be also partly due of this - https://github.com/microsoft/pylance-release/issues/6178
