### ISSUE TITLE
Catch "not is" errors

### ISSUE THREAD

**Issue by dcnieho** [microsoft/pylance-release#6176]
I find myself often writing `not is` instead of the correct `is not` in Python, such as `self._cache not is None` instead of `self._cache is not None`. This is not highlighted as an error, but i get a syntax error when importing the module containing this.

It would be very helpful for me if `is not` gets an error squiggle

**Comment by dcnieho** [comment]
Thanks for the quick look! Making the minimal repo revealed the problem: it happens only when working in files that are not part of the folder/project opened in VSCode, but a pip-installed dependency.

Specifically, i am working on a project that involves multiple packages, and for development i have done an editable install of a tools package in my main package, and i see the problem (no highlighting) when editing a file that belongs to the tools package from inside the VSCode instance that has the folder of the main package open.

I am not sure if this is intended or a bug. Syntax highlighting, auto completion and type inference for the file in the tools package do work (and are very welcome), error reporting (more generally i notice) does not. Also, for instance, undefined variables do not get a squiggle.

**Comment by debonte** [comment]
> for development i have done an editable install of a tools package in my main package, and i see the problem (no highlighting) when editing a file that belongs to the tools package from inside the VSCode instance that has the folder of the main package open.

I'm unable to repro this with my own editable install. I tried both normally (`pip install -e <dir>`) and using `--config-settings editable_mode=compat` as suggested in [our PEP 660 documentation](https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs).

Can you provide access to a repo that reproduces this issue along with instructions on how to repro it?

**Comment by dcnieho** [comment]
You can repro (hopefully with the following steps:
```
git clone https://github.com/dcnieho/glassesTools
git clone https://github.com/dcnieho/gazeMapper
cd .\gazeMapper\
python -m venv .venv
.\.venv\Scripts\activate
pip install --no-deps -e ..\glassesTools\
pip install --no-deps -e .
```
- Then open the gazeMapper folder in VSCode
- Open a file, e.g. /src/gazeMapper/plane.py
- If the correct venv (.venv) is activated, the glassesTools imports on line 9 of plane.py should be resolved.
- right-click on plane in `from glassesTools import plane` and go to definition. That opens a file in the editable-installed glassesTools dependency. Introduce a syntax error in this file. I see that it is not picked up, no red squiggle. Similary, no yellow squiggles at all for unresolved imports or missing variables being used or whatever.

This is VSCode 1.91.1, Python 3.10.9

**Comment by debonte** [comment]
From our perspective, editable install paths are part of the Python search path. All modules found through the Python search path are considered "third party imports" and [we don't report diagnostics for third party imports](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/sourceFile.ts#L967).
