### ISSUE TITLE
Mistakenly treating typing.Dict as typing.TypedDict

### ISSUE THREAD

**Issue by ARF1** [microsoft/pylance-release#618]
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.9

## Actual behaviour

Assuming the following code:

```
import typing as ty


def foo() -> ty.Dict[str, float]:
    return {'abc': 1.0}


foo_dict = foo()
foo_dict['def'] = 'new value'
```

Pylance complains:

```
Argument of type "Literal['new value']" cannot be assigned to parameter "v" of type "float" in function "__setitem__"
  "Literal['new value']" is incompatible with "float"
```

This error would be correct for `typing.TypedDict` but not for `typing.Dict`. The latter does accept elements of new types.

**Comment by erictraut** [comment]
The behavior is correct. A variable of type `Dict[str, float]` accepts keys of type `str` and values of type `float`. This code is attempting to assign a value of type `str`, which is a type violation. If you want to allow values of both `str` and `float`, you would need to change the code to:

```python
def foo() -> ty.Dict[str, Union[float, str]]:
    return {'abc': 1.0}
```
