### ISSUE TITLE
False "Code is unreachable" warning when using `not isinstance()`

### ISSUE THREAD

**Issue by valorien** [microsoft/pylance-release#6182]
When using `not isinstance()` to check if a variable is of the required type/s, Pylance **incorrectly** reports the indented code block as unreachable. 
 
<h3> Environment data </h3>

-   Language Server version: 2024.7.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
def my_func(var: int | str) -> None:
    if not isinstance(var, (int, str)):
        print('not ok')  # <-- Pylance: Code is unreachable
    else:
        print('ok')
```

**Comment by rchiodo** [comment]
Thanks for the issue. This is by design. The type for var is (int | str), it cannot be anything else as far as Pylance is concerned. If you call my_func with something else (and you enable typeCheckingMode=basic), Pylance should give you an error.

![image](https://github.com/user-attachments/assets/e5c2e761-bdcc-4883-bb23-2f0ba052e9b2)


See this issue for more information:
https://github.com/microsoft/pylance-release/issues/6131

**Comment by debonte** [comment]
There's been a lot of recent discussion about this behavior from the perspective of package authors. See https://github.com/microsoft/pylance-release/issues/5647 for example.

Are you a package author? Our prerelease build from today (2024.7.102) includes a new config setting that allows you to disable the tagged hints which cause the `if` block's code to be dimmed in your scenario. You can set `python.analysis.disableTaggedHints` to `true` if you'd like to disable this feature.

**Comment by valorien** [comment]
Thank you both for the prompt replies. I'm not a package author and I actually do find the hints useable.
Reading #5647, I have to agree with @sztomi regarding this behaviour: marking the indented code as unreachable when it is clearly not the case in any way, shape, or form, is a terrible "by design" choice IMO. It is both logically incorrect and simply misleading.

The fact that Pylance "thinks" this is the case solely based on Pyright's logic, indicates to me that these two tools are way over-coupled with each other to the point where Pylance's ability to work correctly is severely hindered. This isn't the first Pylance bug I encountered where it turned out an obviously incorrect behaviour was due to how Pyright operates and "nothing could be done".

I appreciate Pylance's team hard work and dedication and recognize that users complaining about tools they got for free is the epitome of ungratefulness. However, please take this to heart: if Pylance's approach to solving such a trivial issue is hiding the incorrect warning instead of actually addressing the underlying faulty logic that causes it, VS code will cease to be a useful Python development tool and will soon fall behind PyCharm/Zed/Lapce and others.

Thanks again for your time.

**Comment by rchiodo** [comment]
> This isn't the first Pylance bug I encountered where it turned out an obviously incorrect behaviour was due to how Pyright operates and "nothing could be done".

What would be the wanted behavior? A warning on the type specification for `var`? That `int | str` isn't actually the possible types?

**Comment by rchiodo** [comment]
I wonder if maybe the warning we give should mention 

"Given that the type of 'var' is declared 'int | str', this code path is unreachable. You may want to further specify the type of 'var'"

**Comment by debonte** [comment]
@valorien, the scenario in #5647 was a public API which external users could call with incorrect types. In that case a package author would, understandably, want to validate the types of the function's parameters and raise errors for invalid types. And it's strange from the package author's perspective that that intentional validation code is flagged as unreachable.

But it sounds like that's not the case for you? This is a function that is only called from within your code base? If that's the case, why do you want to add extra code to detect invalid parameter types? As Rich pointed out above, assuming you have `python.analysis.typeCheckingMode` set to something other than `"off"`, any calls you make to `my_func` with an argument that is neither an `int` nor a `str` will be flagged with a `reportArgumentType` diagnostic.

**Comment by valorien** [comment]
@rchiodo I know I'm stating the obvious here, but type annotations are meaningless when it comes to Python's logic.
The fact that `var` is of type `int | str` does in no way make the conditional code in my example "unreachable".

What would be the wanted behaviour? Don't warn this block is unreachable when that's clearly not the case.
I can use type annotations to inform users of my code that `var` is of type `some_type`, and yet still decide I want to make sure (or raise a TypeError exception) when an unsupported type of variable is passed.
That is a completely valid and acceptable behaviour in Python and it **does not make the code unreachable**. A simple run immediately proves that, which only makes Pylance's "warning" even more questionable.

**Comment by rchiodo** [comment]
So what you're saying detecting this unreachability is useless because it's obviously for the exceptional case when the user passes in the wrong value. You did this on purpose, it's not a coding mistake and in fact you don't want to specify the arguments to allow for this code to be reachable because that gives the wrong impression to callers.

**Comment by valorien** [comment]
@debonte, thank you for elaborating on #5647.
It actually is the same case in my logic, though I'm building an internal tool where reading/configuration errors my occur, which is why type checks are needed. Again, the point is that this code is completely valid and is **not** unreachable.

The issue here is not whether Pylance's type checking will prevent me from calling a function with an incorrect type of argument, it is that while developing the function itself, Pylance is misleading me as a developer by telling me a block of code is unreachable.

There are cases where code blocks should be marked as unreachable. This is clearly not one of them and never will be since that code is **easily** reachable.

**Comment by valorien** [comment]
> So what you're saying detecting this unreachability is useless because it's obviously for the exceptional case when the user passes in the wrong value. You did this on purpose, it's not a coding mistake and in fact you don't want to specify the arguments to allow for this code to be reachable because that gives the wrong impression to callers.

@rchiodo No, what I'm saying is that calling this code "unreachable" is simply incorrect and misleading. It is perfectly reachable, and this behaviour might also confuse developers further as they would assume actual cases of unreachable code can be ignored just like this one should. Pylance is bending the term "unreachable" here to mean something completely unrelated. It's worse than useless since it's simply not true.

I don't know on what basis you've decided users passing in wrong values is an exceptional case, but even if that was the case, marking this code block as unreachable would still be wrong. The fact that I did this on purpose for my testing doesn't mean it can't happen - and even then that code block would still not be considered "unreachable".

Please also take into account that not all users use VS code or an IDE, many have never heard or care about type annotations, and it's completely reasonable and valid for me as someone who writes a function to raise a TypeError with a friendly message when an unsupported type is passed.

**Comment by heejaechang** [comment]
problem is this is runtime type check

```
    if not isinstance(var, (int, str)):
        print('not ok')  # <-- Pylance: Code is unreachable
```

and the warning is design time (static analysis) type check.

and it sounds like you want us to understand runtime type not design time type. and that's not possible for us. we don't run code to know what the runtime type is. we only know the static time type which is `int` | `str`.

I don't believe any of static analysis tool will know what the runtime type will be. if you want that, you would need something like notebook that actually run the code.

`"python.analysis.disableTaggedHints": false` might be what you want.

**Comment by erictraut** [comment]
Most of pylance's features (including semantic highlighting, completion suggestions, signature help, refactoring, etc.) are based on static type analysis. Static type analysis is intrinsically tied to reachability analysis. If a block is considered unreachable by a static type checker, it will have no effect on downstream types. If it is reachable, the static type analyzer must take into consideration any changes it makes to local state.

When pyright detects that code is unreachable by static analysis, it never generates an error condition (i.e. the condition never appears in VS Code's "problems" panel, and red squiggles never appear). Rather, pyright uses tagged hints to instruct the editor to display the text using a subtle grayed-out color. As a developer, you can then decide whether this is something you expect or not. Sometimes unreachable code is indicative of a bug, but sometimes it's not.

It sounds like you would prefer _not_ to be notified of code that is statically determined to be unreachable. If that's the case, the `python.analysis.disableTaggedHints` will provide you with a way to disable these tagged hints, and you will not see any of the grayed-out blocks of code in your editor.

You are correct that there may be differences between runtime behavior and behaviors determined through static analysis. This is especially true in a language as dynamic as Python. A static analyzer needs to make certain assumptions. One of those assumptions is that if the developer has taken the time to add type annotations in their code, these annotations correctly describe the intended behavior at runtime. In your case, it sounds like you're using type annotations in a "looser" (as in, "less strict") manner.

**Comment by heejaechang** [comment]
from what you are saying, It seems you only consider `syntactically unreachable code` as `unreachable code` and doesn't consider `type-wise unreachable code` as `unreachable code` since in python, you can't force function parameters to be certain type. 

so, is your asking us to split `unreachable` to be `syntactically unreachable` and `type-wise unreachable` ?

**Comment by valorien** [comment]
This is going deep beyond my understanding of the subject matter, so allow me to bow out.
But before I go, here's the same code snippet when it is written in **PyCharm**:

![charm_1](https://github.com/user-attachments/assets/72a3817f-3e55-4cc3-bd72-64c279c7a9de)

As you can see, PyCharm does not warn the user that this perfectly reachable code is "unreachable".
Also note that it is only `not isinstance()` that causes **Pylance** to issue this warning, while `isinstance()` by itself does not.

Thank you all for your time and I appreciate the feedback provided.

**Comment by debonte** [comment]
> Also note that it is only `not isinstance()` that causes **Pylance** to issue this warning, while `isinstance()` by itself does not.

I'm not seeing that behavior in 2024.7.1 or our most recent prerelease build. Can you provide a code sample to explain what you mean?

```python
def my_func(var: int | str) -> None:
    if not isinstance(var, (int, str)):
        print('not ok')  # <-- Pylance: Code is unreachable
    else:
        print('ok')


def my_func_reversed(var: int | str) -> None:
    if isinstance(var, (int, str)):
        print('ok')
    else:
        print('not ok')  # <-- Pylance: Code is unreachable
```

![image](https://github.com/user-attachments/assets/ec26df9c-7937-4b77-88d7-d10fb5bc9217)

**Comment by heejaechang** [comment]
@valorien I just tried `pycharm`. and I don't think they provide `unreachability` check based on `type` like `pylance`. it only provides unreachability based on `syntax`

ex)
```
def foo():
    print(10)
    return
    print(10) <= pycharm only works for something like this.
```

but not for this.

```
class A:
    pass


def foo():
    a: A = A()
    if isinstance(a, A):
        print(1)
    else:
        print(2)
```

**Comment by valorien** [comment]
@debonte, the code you provided is exactly my point. Only the `not isinstance()` or `else` (when logically flipped and `else == not isinstance()`) are marked as unreachable. Why would any type check be "reachable" in this case? utterly confusing.

@heejaechang, thank you very much for checking. PyCharm may not provide unreachability warnings based on types, but it also doesn't issue **completely false** unreachability warnings like the one issued by Pylance that started this discussion.
You haven't indicated where the warning in your 2'nd code sample is so I'm not sure what to look for.

**Comment by heejaechang** [comment]
there is no warning in `pycharm` for the 2nd code since it seems not check `reachability` based on `type`
..

not sure what you meant by 

>  Only the not isinstance() or else (when logically flipped and else == not isinstance()) are marked as unreachable. Why would any type check be "reachable" in this case? utterly confusing.

the code example flips condition and it shows expected behavior.

**Comment by valorien** [comment]
I see your point regarding PyCharm in this use case, and you're correct. I also understand your point regarding the flipped logic and why it's treated differently.

However, my point stands: marking `if not isinstance(obj, types...)` sanity checks as "unreachable", when they are **absolutely perfectly reachable** and necessary when users provide incorrect arguments to a called function, is a bug and not a feature.
PyCharm may not detect reachability based on type, but it also doesn't falsely flag reachable and perfectly functional code as unreachable, like Pylance does.

**Comment by heejaechang** [comment]
we recently added an option to disable `type based` reachability check. it will be released soon, (not in this prerelease though). it will be off by default if `type checking mode` is `off` and will be on by default if `type checking mode` is `enabled`.

when it is off, we will only show unreachable code if we can determine it without involving type such as 

```
   return
   print(a) <= here
```
