### ISSUE TITLE
Quick fix code action fails

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#6183]
## Environment data
-   Pylance version: v2024.7.102 (pre-release)
-   OS and version: linux and windows
-   3.12

## Repro Steps
in an empty files, type `os` and use the code action to add `import os.`

## Expected behavior

`import os` should be added to the top of the file

## Actual behavior
The `import os` is not added to the top of the file

## Logs
2024-07-24 23:20:04.705 [info] [Error - 11:20:04 PM] Request workspace/executeCommand failed.
2024-07-24 23:20:04.705 [info]   Message: Request workspace/executeCommand failed with message: applyEditSync failed with error 0

**Comment by rchiodo** [comment]
Do you have sync server enabled? This is a known issue.

**Comment by rchiodo** [comment]
This issue here:
https://github.com/microsoft/pylance-release/issues/5404
