### ISSUE TITLE
Typechecking error on type-conditional variable redefinition 

### ISSUE THREAD

**Issue by ARF1** [microsoft/pylance-release#619]
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.9

## Actual behaviour

```
import numpy as np

def foo(a: ty.List[float], b: ty.List[float):
    if not isinstance(a, np.ndarray):
        a = np.array(a)
    if not isinstance(b, np.ndarray):
        b = np.array(b)
    res = np.less_equal(b-a, 0.5)
    return res
```

Pylance complains:
```
Operator "-" not supported for types "List[float]" and "List[float]"
  Operator "-" not supported for types "List[float]" and "List[float]"
```

Despite `a` and `b` clearly having type `numpy.ndarray`.

**Comment by jakebailey** [comment]
You can't reassign `a` with a completely different type as what it's declared as in the parameter. The type checker doesn't allow it.

I'd think that if you wanted to accept either a list or an ndarray, the parameter should be a union of those two, not just `List` (which ndarray does not inherit from).

**Comment by erictraut** [comment]
This is the correct behavior. You have declared that symbol a is of type `List[float]`. You cannot redeclare it to something else later. If the `np` module had more complete type information and you enabled type checking, you would see errors when attempting to reassign `a` and `b` to a value that doesn't match their declared types.

Here's one way you could code this in a type-appropriate way.

```python
def foo(a: Union[List[float], np.ndarray], b: Union[List[float], np.ndarray]):
    np_a = a if isinstance(a, np.ndarray) else np.array(a)
    np_b = b if isinstance(b, np.ndarray) else np.array(b)
    res = np.less_equal(np_b - np_a, 0.5)
    return res
```

**Comment by ARF1** [comment]
Many thanks for the explanations.
