### ISSUE TITLE
Bulleted lists with sub bullets don't display the sub-bullets correctly indented

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#6195]
## Environment data

-   Pylance version: v2024.7.102 (pre-release)
-   OS and version: windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.4 tried conda and venv

## Code Snippet

```python
def bulleted_list():
    """
    Bulleted list
    -------------
    * Item1
        
        * SubItem
    
    * Item2
        
        * SubItem
    """
```

## Repro Steps
Hover over the function name to get the docstring

## Expected behavior

bullets and sub bullets

## Actual behavior

![image](https://github.com/user-attachments/assets/4bb80a0c-23ae-43a7-9beb-97f478b545eb)

**Comment by rchiodo** [comment]
Did you enable the new docstring support?

it works for me with that enabled.



![Image](https://github.com/user-attachments/assets/8bc04ee3-fcf5-47b8-89e3-0fe9bac24061)

Without it enabled:



![Image](https://github.com/user-attachments/assets/70bdfd92-2001-4625-948d-8c61996d66d0)
