### ISSUE TITLE
Docstrings initially render incorrectly

### ISSUE THREAD

**Issue by judej** [microsoft/pylance-release#6196]
## Environment data

-   Pylance version: v2024.7.102 (pre-release)
-   OS and version: Windows	
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.4 tried anaconda env and venv

## Code Snippet
```python
def epytext_imread():
    """
imread(filename[, flags]) -> retval
.   @brief Loads an image from a file.
.   @anchor imread
.   
.   The function imread loads an image from the specified file and returns it. If the image cannot be
.   read (because of missing file, improper permissions, unsupported or invalid format), the function
.
.   Currently, the following file formats are supported:
.   
.   -   Windows bitmaps - \\*.bmp, \\*.dib (always supported)
.   -   JPEG files - \\*.jpeg, \\*.jpg, \\*.jpe (see the *Note* section)
    """

```

## Repro Steps
1. Hover over the function name for the docstring. 
2. The first time the docstring renders, it renders incorrectly. Is fixed in subsequent renderings.

## Expected behavior
![image](https://github.com/user-attachments/assets/7ae4af5e-05f0-464d-a3ef-862d2d8d7f5e)

## Actual behavior
![image](https://github.com/user-attachments/assets/f223e594-2e84-4661-99aa-f8cbb92eb4b1)

## Logs

```
XXX
```

**Comment by rchiodo** [comment]
This might be by design. You have to wait for Pylance to load the reparser WASM file. It might just take longer on your machine.

Well assuming you have restructured text support enabled.

**Comment by judej** [comment]
It seemed to mis-render and render alternatingly. But can't repro now.
