### ISSUE TITLE
Linter incorrectly marks code as unreachable with typed defaulted argument

### ISSUE THREAD

**Issue by BaileyGalacci** [microsoft/pylance-release#6217]
Type: <b>Bug</b>

# Behaviour

Code is greyed out and marked unreachable when it should in fact be reachable. Expected the code to not be greyed out.

## Steps to reproduce:

1. Create a function with a defaulted and typed argument. 

2. Create an if statement checking if that argument is set to None.
```
def func(myInt: int = None):
    if myInt is None:
        print("Input set to None, or not provided.")
```

4. The print line is greyed out. Now remove the type specifier from the function signature, and the code will be marked accessible. 
`def func(myInt = None)`

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Nothing shows up between steps 2 and 3.
```

</p>
</details>

Extension version: 2024.7.1
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 4.18.0-553.8.1.el8_10.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600K (20 x 5007)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.16GB (17.23GB free)|
|Process Argv|. --crash-reporter-id c9e90ff9-ec61-4df0-b2fe-7a473620efce|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactorc:31101458
ccplti:31103428
pythonrstrctxtcf:31103194

```

</details>

**Comment by heejaechang** [comment]
dup of https://github.com/microsoft/pylance-release/issues/6182
