### ISSUE TITLE
Language server suggests auto-importing stdlib functions from local project files instead

### ISSUE THREAD

**Issue by rChaoz** [microsoft/pylance-release#6221]
**Describe the bug**
The language server suggest importing functions from files that import them rather than the declaration module. This makes sense for re-exports (e.g. `from ... import x as x`), but not otherwise.

**Code or Screenshots**

1. Create a simple python module + file with an import:
   ```python
   from os import abort
   ```

2. In a new file try to get the autoimport for `abort`:

   <img width="590" alt="image" src="https://github.com/user-attachments/assets/ccf51d7f-b60b-4385-8727-77864af6d2b7">

At this point, the language server will suggest two imports of `abort` - one from `typing` (correct) and **one from the file created earlier (incorrect)**. This gets worse the more you import that specific function in your project, suggesting imports from each file that uses it.

**Information**

Using PyRight `1.1.374` with the built-in language server (i.e. from `.venv`) in PyCharm.

**Comment by heejaechang** [comment]
what version of `pylance` are you using? this should be what `pylance + vscode` shows you for the same situation

![image](https://github.com/user-attachments/assets/0d8c26a2-d148-463b-9515-a5dd077d1f88)

editor decides how to show data to UI. so this bug should go to `PyCharm` if it decides to show the UI as you said in the description.
