### ISSUE TITLE
saving `autoImportCompletion` through UI (status bar), when `workspace` is not opened, error out.

### ISSUE THREAD

**Issue by ARMANTWOX** [microsoft/pylance-release#6228]
Type: <b>Bug</b>

i have been using tkinter for gui for my software and import tkinter or from tkinter dosent work i looked at the pylance and saw auto import completions is false so i tried to turn it on it gave me a error:

Failed to update setting 'python.analysis.autoImportCompletions'.
CodeExpectedError: Unable to write to Workspace Settings because no workspace is opened.
Please open a workspace first and try again.

my terminal also gave a error:

Traceback (most recent call last):
  File "c:\Users\ASUS\Desktop\tkinter.py", line 1, in <module>
    from tkinter import *
  File "c:\Users\ASUS\Desktop\tkinter.py", line 2, in <module>
    from tkinter import ttk
ImportError: cannot import name 'ttk' from partially initialized module 'tkinter' (most likely due to a circular import) (c:\Users\ASUS\Desktop\tkinter.py)

Extension version: 2024.7.1
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19042
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G4400 @ 3.30GHz (2 x 3312)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.38GB free)|
|Process Argv|C:\\Users\\ASUS\\Desktop\\tkinter.py --crash-reporter-id e51223ef-d9a2-4a41-98e2-c703911459c0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplc:31103425
pythonrstrctxt:31103193

```

</details>

![Screenshot 2024-08-05 195738](https://github.com/user-attachments/assets/01c615ec-c7a6-4826-afe7-1d9c6b0c1c55)
![Screenshot 2024-08-05 200027](https://github.com/user-attachments/assets/a5443fc7-6f21-468b-935e-238858b59efe)
![Screenshot 2024-08-05 195828](https://github.com/user-attachments/assets/19987833-8809-4918-9d60-c4c71f5e888c)

**Comment by heejaechang** [comment]
I guess you opened the file standalone without folder or workspace opened. you probably need to manually set the setting in user `settings.json`

![image](https://github.com/user-attachments/assets/ecf2ca8e-615b-48dd-9213-d68becf2aa07)

at the `settings.json`, enable auto import by setting `"python.analysis.autoImportCompletions": true`

that said it looks like we should fix the error issue with no folder opened.
