### ISSUE TITLE
Pylance insiders

### ISSUE THREAD

**Issue by jakebailey** [microsoft/pylance-release#623]
Pylance now features an insiders program, which offers early access to new features and improvements.

To enable insiders, set `"pylance.insidersChannel": "daily"`. This will enable a daily check for new builds. At startup or when the insiders setting is changed, Pylance will automatically update and prompt you to reload.

To leave the insiders program, remove the setting, or explicitly set `"pylance.insidersChannel": "off"`. You may be prompted to downgrade your extension to the latest stable version.

When reporting issues, ensure that you are providing a version number. Insiders builds can be distinguished by versions containing `-pre`.

Thank you for your feedback and support!

**Comment by byehack** [comment]
Add tag `usesOnlineServices` to `pylance.insidersChannel` setting.

**Comment by jakebailey** [comment]
We'll do so for the next release, but we also read `python.insidersChannel`, which is in the core Python extension (and they have a lot more settings that involve "online services").

**Comment by saaketp** [comment]
Is there any place to see the change log for insiders versions?

The [Changelog page](https://marketplace.visualstudio.com/items/ms-python.vscode-pylance/changelog) on market place and the [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md) in this repository only show the stable versions.
