### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Yahya78h** [microsoft/pylance-release#6241]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2024.8.1`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.91.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Barou/AppData/Local/Temp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rchiodo** [comment]
@Yahya78h  thanks for the issue. Can you attach the mentioned file? Otherwise this is unactionable for us.

**Comment by bschnurr** [comment]
please see https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue 

if you have a public repo or code sample that would really help. 

closing for now.
