### ISSUE TITLE
Pylance ins`t accessing fixture from main conftest

### ISSUE THREAD

**Issue by Lukkimon** [microsoft/pylance-release#6249]
Am i doing something wrong?

I have conftest.py in main directory with fixture "fixture_one".
I created folder "tests" and one sub folder named "rest" with its own conftest.py containing "fixture_two".
When i try to use hints it only shows "fixture_two". 
But using "pytest-fixtures" extension it shows both

![изображение](https://github.com/user-attachments/assets/ebd6dc5c-8b0f-4670-94ef-b18ba3727919)

**Comment by Lukkimon** [comment]
I moved main conftest.py inside tests directory. Now It shows

![изображение](https://github.com/user-attachments/assets/98f29bf4-1d8c-4fba-8c3a-377894a0b6db)

Buts it shouldn`t matter is it? Test runs both ways

**Comment by debonte** [comment]
Thanks for the repro steps. I figured out the problem and am working on a fix.

**Comment by bschnurr** [comment]
This issue has been fixed in prerelease version 2024.8.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20248100-11-August-2024-PreRelease)

**Comment by Lukkimon** [comment]
I updated but nothing changed for me

**Comment by debonte** [comment]
Sorry, this issue was incorrectly closed. It has been fixed, but it missed 2024.8.100 and will show up in our next prerelease build.

**Comment by KacieKK** [comment]
This issue has been fixed in prerelease version 2024.8.101, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20248101-12-August-2024-PreRelease)
