### ISSUE TITLE
Use Github Releases to publish Changelog

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#625]
Doing so would allow interested users to select `Releases only` and be notified when a new one is available.

**Comment by jakebailey** [comment]
For the release today and onward, we should be publishing a release here as well with a copy of the notable changes (and a link back to the full log).

**Comment by jakebailey** [comment]
First one done here: https://github.com/microsoft/pylance-release/releases/tag/2020.12.0

🙂
