### ISSUE TITLE
pylance unable to recognize property render by another class

### ISSUE THREAD

**Issue by Hocnonsense** [microsoft/pylance-release#6251]
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.10.13 from anaconda

## Code Snippet

```python
from typing import Callable, Literal, TypeVar


class Pair:
    T = Literal["ref", "query"]
    FT = TypeVar("FT")
    CLS = TypeVar("CLS", type, type)

    def __init__(self, f: Callable[[CLS, T, T], FT]):
        self.f = f

    def __call__(self, cls: CLS):
        self.cls = cls
        return self

    def switch(self, this: T):
        if this == self.T.__args__[0]:
            return self.T.__args__[1]
        if this == self.T.__args__[1]:
            return self.T.__args__[0]
        raise ValueError("not in switch")

    def __getitem__(self, this: T):
        return self.f(self.cls, this, self.switch(this))


class Test:
    @property
    @Pair
    def l(self, this: "Pair.T", other: "Pair.T"):
        return other[::-1]


t = Test()
l = t.l["ref"]
```

## Repro Steps

1. move mouse over the last `l = t.l["ref"]`, the left, variable l

## Expected behavior

`l` should be recognize as type 'str'

## Actual behavior

cannot determin type of `l`, however, property `l` of class `Test` was recognize as `str`, however, it is actually a `Pair` object

## Logs

None

**Comment by erictraut** [comment]
You have a few bugs in your code. If you enable type checking (i.e. set `typeCheckingMode` to "basic" or "standard"), pylance will help you find these bugs.

The first issue is that the type variable `CLS` is defined incorrectly. It should not be a value-constrained type variable. Simply delete the "type, type" value constraints. The second issue is it appears that you intend `Pair` to be a generic class, but the way you've defined it, it's a non-generic class with generic methods. To make it a generic class, you need to move the TypeVar definitions outside of the class and have the class derive from `Generic`.

```python
FT = TypeVar("FT")
CLS = TypeVar("CLS")

class Pair(Generic[FT, CLS]): ...
```

Or if you're using Python 3.12, you can make use of the new generics syntax:

```python
class Pair[FT, CLS]: ...
```

With those two bug fixes, your code will work as you expect.

Code sample in [pyright playground](https://pyright-play.net/?strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDCAhgDYlEBGJApgDRQAySM1IpAsAFBdcDG5AZwFQACkSQgA2gDEAKvQIMAygF0AXFyhaosqAF5GzVqUkAiENWCn6pgI4BXVnFMqenbVAAmlqAH1fqMz%2BABQC1CTA9MBqhKTkVNSSkopK9PI6KvRyKgCUGu4e2mERAHTA%2BlDAbh7e5f68cSHFkVD8AjEpeZqFWs0lbRVt3T0WMPYgKFDN1dq1UwDuzLwAFqHhLTDLSO06XQU9SOWb2-oGfbIl-kQgaAL%2BkgAM6sM92qPjk%2BeXvte39wCMrn2hUOsC2wj0Z3WJQuVxud18kkB%2BVehXeEym0NhP3h9yeLw8bG21CgADVSI4AKIgcAgYKmFBgfCoBZLZamHIzLRzfxoagwIwQJrrejHHayPao9GfaHANalNqi8H0PoCRYwFbBMU5TncPX8IhCHTUAQwFHaAACCHACFY8BeFrEEhecxI8o24JipidIBh1igTOWrC9Pr9kte0oDm1YkjUagAtIC3Fx8AZZCaYMFdSQKjASiQzBYrECgA)

**Comment by Hocnonsense** [comment]
Thanks for your kind advice! it helps me a lot!

While mypy still not support PEP 695, I have to use `Generic`. The behavior is almost the same, but I've found that in vscode, [adding `CLS` in `class Pair(Generic[FT, CLS]): ...`](https://pyright-play.net/?strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoDCAhgDYlEBGJApgDRQDi1K1ISAxvQDJIyun0AKomoA1IiHoAxVKQCwAKEWKpgqAF4owhGIkAKAESqDASkUEuAZQ1aR4kIYuXTypQvbkAzp6gAFIkgOTCxs7ADaqvROALomAFyKUElaNjx8IKRhBiDUwAb0BgCOAK6scAbRicnMxRBxUDIopDbZuflQRaUg5a7JUAAmuVAA%2BsOovKN6ntQkwPTA9cRklDRhYU5CQtHSgrEJCn1907MAdB6ei1ZVh1DHwCfANsC9yYOPo%2BykJJN39OeXlni10OdzOJB8mnOwL6ORgxRAKFuM2ebj6b1uAHdeOwABZTZH0GA4pAXLRAg43TCPIkkjSaUE1CBhAAM0X2lMOsPhiIZKFqYQAjJUKTckNTiRD6ciTozBWzoZSuQikadZayFUkMiTqFBxCRSgBREDgBwGFBgfCoTHYnEuVGvIajNDUGC8agQH4E2AS%2BqCExQAC0AD4GoJ2YqXdyVfdgPjTudCRL6KDPFiYLi9DTPCYzG5FB4iN4tNRPDBw0kAAIIcA6PBwYEV-yBYHokhxubekn1AxNkAnQTtC041jd3v90zlzmR5VD1hhOJxANC1z4TSCEswPS5og2GAnEhZHJ5YVAA) will disable pylance to report the correct type.

![image](https://github.com/user-attachments/assets/cda5eaf0-9b04-47d0-a27f-498788397aca)

![image](https://github.com/user-attachments/assets/29ca38e2-fc37-4323-9a04-336c4511201f)

**Comment by erictraut** [comment]
Mypy 1.11 does support PEP 695 as an experimental feature.

I presume you're using mypy in your CI pipeline? If you switch from mypy to pyright (which is the type checker that pylance is built upon), you'll see consistent type checking results between your editor and your CI. Plus, pyright has more up-to-date features and [conforms more closely](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html) to the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html).

**Comment by Hocnonsense** [comment]
That's great! I'd like to try it when I need type check for a whole project. (I'm enjoying Pylance extention in vscode now, it seems that pyright is included by Pylance, and the Pyright extension is redundant? If so, I'm already using pyright (inside pylance) to check my codes.)

Thanks!
