### ISSUE TITLE
Fixit imports from private file instead of re-export

### ISSUE THREAD

**Issue by superlopuh** [microsoft/pylance-release#6252]
## Environment data

-   Pylance version: v2023.10.40
-   OS and version: macOS 14.5
-   Python version: Python 3.11.6 brew

## Code Snippet

This is more of a question about the Python LSP server in VSCode but I'm not sure where the best place to post it is.

I have a directory in a project that I would like to pretend is a file, and to hide the inner folder structure. It has a number of files that are pure implementation detail. How do I export symbols in such a way that VSCode automatically imports them from the public re-export?

``` python
proj/public/_private.py

class _A: pass
```

``` python
proj/public/__init__.py

from ._private import _A as A  # noqa: TID251

# I was hoping this would redirect the LSP but it seems to have 0 effect
__all__ = [
    "A",
]
```

``` python
proj/file.py

# from proj.public import A              <-- this is what I would like the fixit to produce
# from proj.public._private import _A    <-- this is what it currently produces

# Non-imported A
print(A)
```

## Repro Steps

Hover over the `A` in `print(A)`, and apply the fixit.

## Expected behavior

To import the symbol from the re-export.

## Actual behavior

Imports private symbol from private file.

**Comment by StellaHuang95** [comment]
I am not able to repro what you mentioned above about `quick fix` adding the `from proj.public._private import _A ` import statement when hovering over `A`. Could you review your repro steps and see if any steps might have been missed? Additonally, import aliases are not included in auto import for workspace files for now, see discussion here: https://github.com/microsoft/pylance-release/issues/5654#issuecomment-2035617973 and the corresponding enhancement request here: https://github.com/microsoft/pylance-release/issues/5434

**Comment by superlopuh** [comment]
My apologies, you're right that my code doesn't reproduce, I took it from a real codebase and I'm not sure what causes the behaviour in the larger project. The issues you linked are exactly what I was hoping to find, and I'm glad that they're being worked on and that I can monitor them for progress. I'll close this issue for now.
