### ISSUE TITLE
unreachable code appears on isinstance typehinting 

### ISSUE THREAD

**Issue by YoniChechik** [microsoft/pylance-release#6256]
Type: <b>Bug</b>

# Behaviour

paste this code to vscode .py and behold that some part appears unreachable even though it's only typehints

```python
def _plot_shapely(
    geometry: Polygon | MultiPolygon | list[Polygon | MultiPolygon], polygon_color="blue", title="Geometry Plot"
):
    # Check if the input is a Polygon or MultiPolygon
    if isinstance(geometry, Polygon):
        geometries = [geometry]
    elif isinstance(geometry, MultiPolygon):
        geometries = geometry.geoms
    elif isinstance(geometry, list):
        geometries = []
        for geom in geometry:
            if isinstance(geom, Polygon):
                geometries.append(geom)
            elif isinstance(geom, MultiPolygon):
                geometries.extend(geom.geoms)
            else:
                raise TypeError("All elements in the list must be shapely Polygon or MultiPolygon")
    else:
        raise TypeError("Input must be a shapely Polygon or MultiPolygon") # THIS WILL APPEAR AS UNREACHABLE CODE
```

This should not be the case since this code is definitly reachable...

Extension version: 2024.12.2
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.5.0-44-generic

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.9
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|Code Spell Checker|streetsidesoftware.code-spell-checker|3.0.1|
|GitHub Pull Requests|GitHub.vscode-pull-request-github|0.94.0|
|GitLens — Git supercharged|eamodio.gitlens|15.2.3|
|JavaScript Debugger|ms-vscode.js-debug|1.92.0|
|Pylance|ms-python.vscode-pylance|2024.8.1|
|Python|ms-python.python|2024.12.2|
|Python Debugger|ms-python.debugpy|2024.10.0|
|Ruff|charliermarsh.ruff|2024.36.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.9|
|Todo Tree|Gruntfuggly.todo-tree|0.0.226|
|View Image for Python Debugging|elazarcoh.simply-view-image-for-python-debugging|4.0.0|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (25.58GB free)|
|Process Argv|--folder-uri vscode-remote://attached-container%2B7b22636f6e7461696e65724e616d65223a222f796f6e692d6465765f73696d706c69636974792d31227d@ssh-remote%2Bmercury/root/simplicity --crash-reporter-id 4f2d0330-6b3c-4bf6-91d9-f8f5387d72e8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container yoni-dev_simplicity (yoni-dev_simplicity-1) @ mercury|
|OS|Linux x64 6.5.0-44-generic|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 800)|
|Memory (System)|125.53GB (120.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-c:31111712

```

</details>

**Comment by debonte** [comment]
There's been a lot of discussion in the Pylance and Pyright issue trackers lately about whether type analysis should impact unreachability hints, so a new setting has been added to control this behavior. If you don't want Pylance to mark code as unreachable when it is only unreachable based on type analysis, starting in 2024.8.100 you can set the following in your VS Code settings:

```json
"python.analysis.typeEvaluation.enableReachabilityAnalysis": false
```

Or in your `pyrightconfig.json` (or `pyproject.toml`):

```json
{
    "enableReachabilityAnalysis": false
}
```
