### ISSUE TITLE
pylance evaluates code in realtime so linux code in unreachable on windows

### ISSUE THREAD

**Issue by fenchu** [microsoft/pylance-release#626]
## Environment data

-   Language Server version: v2020.11.2
-   OS and version: windosw10 2009
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.9.0 win64

## Expected behaviour

I have a test that should exit if we are on windows, but since I develop on windows it seems like pylance takes this
literally and says the rest of the code is unreachable :-)

It is really impressive, but is there a way to turn this off so I can make my linux code in a windows environment

## Actual behaviour
![pylance unreachable](https://user-images.githubusercontent.com/11349883/99674440-5675cb80-2a76-11eb-80bf-f02195389961.jpg)

But if i invalidates the test, pylance can reach it
![pylance reachable](https://user-images.githubusercontent.com/11349883/99675749-e2d4be00-2a77-11eb-8fa9-26b7b58c5e96.jpg)

## Logs

```
I tried enabling logging but nothing shows
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment]
You can configure which OS environment the code is intended to run within. By default, it defaults to the OS you are using for development. To override this default, create a "pyrightconfig.json" file in your root directory and specify a "pythonPlatform". For cross-platform code, set this to an empty string. You can find more details and a sample config file [here](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#sample-config-file).

**Comment by fenchu** [comment]
Excellent, This should be a setting in settings.json and and shortcut in vsc
