### ISSUE TITLE
Pylance settings parsing silently fails if path not exists

### ISSUE THREAD

**Issue by paulober** [microsoft/pylance-release#6266]
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: macOS 15.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.5

## Code Snippet

The following settings include a path that does not exist before a path that does exist.

```json
{
    "python.linting.enabled": true,
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.typeshedPaths": [
        "~/. stubs/notExists",
        "~/. stubs/exists"
    ],
    "python.analysis.extraPaths": [
        "~/.stubs/notExists",
        "~/.stubs/exists"
    ]
}
```

The problem here is that if pylance encounters the `notExists` path, it will just silently fail without any user feedback and it stops processing other paths in the array. This is also the reason why the first settings stops the full setup of the user to stop working while the second version does also fail but continues to work as expected:

```json
{
    "python.linting.enabled": true,
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.typeshedPaths": [
        "~/. stubs/exists",
        "~/. stubs/notExists"
    ],
    "python.analysis.extraPaths": [
        "~/.stubs/exists",
        "~/.stubs/notExists"
    ]
}
```

## Repro Steps

1. setup a new folder with the described settings.
2. (Your `exists` path must override some of the functions like `dump` from the json.pyi module or any other module that is included in the Python installation)
3. Create a main.py and test the difference in between the two versions of settings

## Expected behavior

One of the suggested solutions below.

## Actual behavior

Nothing happens from a user perspective though the typing system will silently fallback to the modules from the Python installation. So if your custom paths include stubs that override the system modules like `json`. The user may continue develop a script with wrong typings which potentially results with lots of error messages if they try to execute the script on a system that expects the custom module typings.

## Logs

```console
2024-08-15 18:58:44.854 [info] [Error - 6:58:44 PM] (80806) typeshedPath /Users/myuser/. stubs/notExists is not a valid directory.
```

### Suggested solutions:

- Please add user feedback like with a notification if a path cannot be found.
- If the parser fails to locate a path that does not exist, continue parsing the other entries if present and notify the user via a log entry. (preferred)

**Comment by cwebster-99** [comment]
Apologies for the delayed response and thank you for the report! Given our current limited resources, it's unlikely we will be able to fix this issue in the near future. [We're closing it so we can focus on higher priority issues](https://github.com/microsoft/pylance-release/wiki/Issue-Management). However, if this is a critical issue for you let us know and we can reevaluate. Thanks!
