### ISSUE TITLE
CMD + LMB defaults to system stubs if module is overridden

### ISSUE THREAD

**Issue by paulober** [microsoft/pylance-release#6268]
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: macOS 15.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.5

## Code Snippet

**json.pyi:**
```python
def dumps(obj, separators=None) -> str:
    """
    Return *obj* represented as a JSON string.

    The arguments have the same meaning as in `dump`.
    """
    ...
```

**.vscode/settings.json**
```json
{
    "python.linting.enabled": true,
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.typeshedPaths": [
         "~/.stubs/mystubs"
    ],
    "python.analysis.extraPaths": [
        "~/.stubs/mystubs"
    ]
}
```

## Repro Steps

1. Create a new folder with a .vscode and settings.json.
2. Create a typings folder with a file inside that overrides a default/included module like `json`. So `typings/json.pyi` overrides the default json. This file must contain functions that also exist in the default module but with a different function signature of optional arguments and add a doc-string to the function declaration that differs from the normal one. (you can find an example above)
3. Now create a main.py an include you custom module (like `import json`).
4. Type `module_name.` and wait for auto suggestions.
5. Press enter and call the function with the correct parameters.
6. CMD / STRG + Left mous button on the function name

## Expected behavior

- The extension shows your doc-string and functions
- The extension opens the correct `override_module.pyi` you created.

## Actual behavior

- It shows you doc-string and functions and uses them for syntax high-lighting of errors if you try to use an optional parameter that only exists on the system module definition.
- But if you left click on the function it takes you to the original system module definition instead of your custom implementation which doc-string and function signature is also displayed.

## Logs

```
Nada
```

**Comment by rchiodo** [comment]
Thanks for the issue but this is by design. CMD+Left Click goes to the definition of the function, not the declaration. Stubs are declarations.

The difference is more pronounced on the context menu:

![Image](https://github.com/user-attachments/assets/29518216-2b0f-4b17-82ad-1dfd2fee6d30)

**Comment by paulober** [comment]
> Thanks for the issue but this is by design. CMD+Left Click goes to the definition of the function, not the declaration. Stubs are declarations.

Thanks for the explanation. Is it possible per setting to enable go to declaration for CMD + LMB?

**Comment by rchiodo** [comment]
> Is it possible per setting to enable go to declaration for CMD + LMB?

I don't believe mouse clicks are rewriteable, but you could make a keyboard shortcut for it. Or rewrite F12 to goto declaration instead.

Right now F12 is goto definition:



![Image](https://github.com/user-attachments/assets/24c8cf23-12cc-4d7b-9965-584ba9ddbc26)

**Comment by paulober** [comment]
Ok, thanks.

**Comment by debonte** [comment]
> I don't believe mouse clicks are rewriteable,

@paulober, you could up-vote this issue: https://github.com/Microsoft/vscode/issues/3130
