### ISSUE TITLE
Inference on variables according to information provided by Paramspec

### ISSUE THREAD

**Issue by Xukai-Liu** [microsoft/pylance-release#6273]
```
from typing import TypeVar, Callable
from typing_extensions import ParamSpec
T = TypeVar('T')
P = ParamSpec('P')

def build(cls: Callable[P, T], *args: P.args, **kwargs: P.kwargs)-> T:
    return cls(*args, **kwargs)

class Poop:
    def __init__(self, amount: int, strength: float)->None:
        return

def pooper(amount: int, strength: float)->Poop:
    return Poop(amount, strength)

build(pooper, )
```

As my example provides, the type checker should have the information needed to produce the specific arguments from the Callable once it is provided. But from my experiments it doesn't seem this functionality exists. Please let me know if this could be implemented in Pylance as I do not have a detail level understanding of this repository. If it is possible I'd be glad to implement it as I understand this may not be of high priority.

**Comment by debonte** [comment]
FYI, this was originally filed as https://github.com/microsoft/pyright/issues/8770.

**Comment by Xukai-Liu** [comment]
> FYI, this was originally filed as [microsoft/pyright#8770](https://github.com/microsoft/pyright/issues/8770).

Thanks for mentioning this! I was redirected by the guys at pyright to this repo, I simply copied the original post as I thought it was ok. Should I have mentioned this fact? Apologize in advance as I have very little experience participating in the open source community.

**Comment by debonte** [comment]
Not a big deal. I was just mentioning it for context.

**Comment by StellaHuang95** [comment]
Thank you for your suggestion. It appears that a similar enhancement has already requested by other users, see [this discussion](https://github.com/microsoft/pylance-release/discussions/2634). 

Please note that Pylance is a closed-source project, and we have limited resources to implement new features. We prioritize enhancements based on user demand, so if you'd like to see this feature supported, we encourage you to upvote the linked discussion. Thanks!
