### ISSUE TITLE
Is there any way to disable specific error messages?

### ISSUE THREAD

**Issue by WindSoilder** [microsoft/pylance-release#6274]
Given the following code:
```python
def a() -> dict[int, list[int]]:
    return {3: [1, 2]}
```
pyright says that: 
1. Pyright: Subscript for class "dict" will generate runtime exception; enclose type annotation in quotes
2. Pyright: Subscript for class "list" will generate runtime exception; enclose type annotation in quotes

But acutally I don't need my code supporting old python version, I'm using python 3.11 which supports the syntax.

I have configure virtual env to use python3.11, but the error still exists.  Is there any way to disable the message?  Thanks!

**Comment by erictraut** [comment]
If you are using Python 3.11 (or any version of Python after 3.8), you should not see these errors unless you've explicitly configured pyright's `pythonVersion` setting to an older version of Python. 

If you look in the Output logs for pylance, you should see a line that says something like "Assuming Python version 3.11.0.final.3" or something like that. If you don't see that, then check your pyproject.toml or pyrightconfig.json file to see if you've specified a "pyrightVersion".

**Comment by WindSoilder** [comment]
Thanks!  I never set `pythonVersion` in any of my config files.
But I can set it manually in `pyrightconfig.json`.
