### ISSUE TITLE
Type inference for argparse

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#628]
The standard module `argparse` is a very popular approach to handling command line arguments. The problem is that autocompletion does not work for the result of `argparse.ArgumentParser.parse_args()` since it is a generic namespace. I am not aware of workarounds that do not require code duplication. It would be very useful if VSCode could infer types, at least in simple cases, when there is just one parser without (external)(sub)parsers imported from somewhere else. As far as I understand, any implementation will be a "hack" to some extent. However, due to the popularity of `argparse`, it may be worth it.

**Comment by erictraut** [comment]
Pylance doesn't use any form of type inference in cases where type declarations are provided. The methods on this case are declared in the stdlib type stub `argparse.pyi`. The method in question is defined using the following overloads:

```python
    @overload
    def parse_args(self, args: Optional[Sequence[Text]] = ...) -> Namespace: ...
    @overload
    def parse_args(self, args: Optional[Sequence[Text]], namespace: None) -> Namespace: ...  # type: ignore
    @overload
    def parse_args(self, args: Optional[Sequence[Text]], namespace: _N) -> _N: ...
    @overload
    def parse_args(self, *, namespace: None) -> Namespace: ...  # type: ignore
    @overload
    def parse_args(self, *, namespace: _N) -> _N: ...
```

These overloads do allow for custom namespaces that are preserved through the use of a TypeVar `_N`.

Do you have a specific code sample that exhibits the problem you're seeing?

If you think that the type declaration for this method is incorrect or incomplete, please file a bug report or a PR in the [typeshed repo](https://github.com/python/typeshed). That's where we (and all other Python type checkers) get these standard type stubs.

**Comment by Yura52** [comment]
If I understand correctly, you suggest something like this:

```python
@dataclass
class Args:
    x: int
...
parser.add_argument('--x', type=int)
parser.parse_args(['--x', '123'], Args())
```

The problem is that now I have two places where types are given: the `Args` definition and the `add_argument` call. The feature request implies that types are inferred exclusively from `add_argument` calls via some ad hoc machinery. However, I don't know to what extent such a machinery will be problematic for the Pylance code base :)

**Comment by erictraut** [comment]
Pylance doesn't have in-built knowledge of specific classes or methods. It bases its behaviors on type information found in type stubs.

**Comment by Yura52** [comment]
I see, thank you for the answer. If the issue is completely irrelevant to Pylance's roadmap, I don't mind closing it.
