### ISSUE TITLE
"numpy" is not accessed pylance

### ISSUE THREAD

**Issue by jagan007G** [microsoft/pylance-release#6282]
import numpy
import scipy.io.wavfile
from scipy.fftpack import dct

sample_rate, signal = scipy.io.wavfile.read('harvard.wav')  # File assumed to be in the same directory
signal = signal[0:int(3.5 * sample_rate)]  # Keep the first 3.5 seconds

I executed above code in python virtual environment. then numpy is not work. its show the error of 
( WavFileWarning: Chunk (non-data) not understood, skipping it.
  sample_rate, signal = scipy.io.wavfile.read('harvard.wav')  # File assumed to be in the same directory ) 

And, In the code section, the numpy modulus are in transparent word. I point that it shows numpy is not accessed in pylance

**Comment by rchiodo** [comment]
Thanks for the issue but this is by design. That code is not directly using numpy. That's what the error message means. It would run the same with or without the `import numpy` statement.
