### ISSUE TITLE
Language server does not update when selecting Python environment

### ISSUE THREAD

**Issue by imadjarov-quantinuum** [microsoft/pylance-release#6285]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I select a Python environment in a Jupyter notebook from the environment picker, the language server does not update (i.e. syntax highlighting, etc.). It only updates when I close and re-open the notebook. 

I am using Jupyter notebooks with Remote - SSH on a remote Linux machine. My language server is Pylance v2024.8.1.

### VS Code Version

1.92.2

### Jupyter Extension Version

v2024.7.0

### Coding Language and Runtime Version

Python v3.8.13

### Language Extension Version (if applicable)

v2024.12.3

### Running Jupyter locally or remotely?

Remote

**Comment by rchiodo** [comment]
Thanks for the issue. This should be a dupe of https://github.com/microsoft/vscode/issues/199800
