### ISSUE TITLE
Auto-imports for namespace packages

### ISSUE THREAD

**Issue by FaydSpeare** [microsoft/pylance-release#6290]
Are auto-imports not supported for namespace packages? Auto-imports work fine for all packages installed in my virtual environment except for the one which is inside a namespace. 

Additionally, if I modify the namespace package in my virtual environment, so as to remove the namespace, making it a standard looking package, the auto-imports become available for that package.

**Comment by FaydSpeare** [comment]
You can reproduce this by installing the opentelemetry-api (which uses an `opentelemetry` namespace).

As an example, the following import is resolved correctly:
`from opentelemetry.attributes import BoundedAttributes`

however, when you type `BoundedAttrib...` into the editor,  there is no auto-import available.

**Comment by heejaechang** [comment]
have you tried `packageIndexDepth` option? https://github.com/microsoft/pylance-release/blob/e0f7c1e70d8760454a661dd4875d236faa888419/README.md?plain=1#L129

**Comment by heejaechang** [comment]
adding this to `packageIndexDepths` made it work for me

```
{
      "name": "opentelemetry",
      "depth": 2,
      "includeAllSymbols": true
    }
```

**Comment by FaydSpeare** [comment]
Great, thanks!

I'm wondering if this should be the default setting. I don't see why auto-imports shouldn't work for namespace packages out of the box.

**Comment by heejaechang** [comment]
it is not specific to `namespace` package but just default behavior. that said, treating namespace package specially seems good idea but also that would make explaining option harder since now the depth is not from the root of package but root of package under namespace package.

let me tag @luabud to see her opinion.

**Comment by JohanKarlbergg** [comment]
Hey @heejaechang @luabud, have you discussed handling namespace packages in a special way yet?

**Comment by heejaechang** [comment]
opened https://github.com/microsoft/pylance-release/issues/7248 to track it.

**Comment by mmzeynalli** [comment]
Hey! I still have this problem, despite giving depth manually:

<img width="640" height="267" alt="Image" src="https://github.com/user-attachments/assets/3f0a7e32-52da-4556-a36f-f27ebbdd9871" />


This image is from integrify-epoint-python, which is on top of integrify-core-python, both "integrify" namespace. This is my config:

```
    "python.analysis.indexing": true,
    "python.analysis.autoImportCompletions": true,
    "python.analysis.packageIndexDepths": [
        {
            "name": "src",
            "depth": 1
        },
        {
            "name": "integrify",
            "depth": 2,
            "includeAllSymbols": true
        },
        {
            "name": "integrify-core",
            "depth": 2,
            "includeAllSymbols": true
        },
    ],
```

There is still no autocomplete. For source code directly, you can check:

https://github.com/Integrify-SDK/integrify-epoint-python
https://github.com/Integrify-SDK/integrify-core-python
