### ISSUE TITLE
Automatic rename refactoring does not apply to notebooks

### ISSUE THREAD

**Issue by ibestvina** [microsoft/pylance-release#6298]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Renaming objects inside .py files, or the files themselves, which triggers the automatic refactoring, does not affect any code inside notebooks where these are referenced. I am not sure if this is a Pylance or Jupyter problem.

### VS Code Version

1.92.2 (Universal)

### Jupyter Extension Version

v2024.7.0

### Coding Language and Runtime Version

Python 3.10

### Language Extension Version (if applicable)

v2024.12.3

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the issue. This is actually a known issue and has to do with how VS code returns references. See these issues for more information:
https://github.com/microsoft/pylance-release/issues/5175
https://github.com/microsoft/pylance-release/issues/6022
https://github.com/microsoft/vscode/issues/211829

**Comment by rchiodo** [comment]
This issue actually describes in more detail what the problem is:
https://github.com/microsoft/vscode/issues/177391

We just haven't gotten to implementing the recommended open all notebook documents during find all references.
