### ISSUE TITLE
Show better hints for namedtuple __init__()

### ISSUE THREAD

**Issue by ARF1** [microsoft/pylance-release#630]
## Environment data

-   Language Server version: 2020.11.1
-   OS and version: Windows 10 
-   Python version (& distribution if applicable, e.g. Anaconda): Miniconda Python 3.9

## Actual behaviour

Pylance is missing argument information:
![image](https://user-images.githubusercontent.com/5834577/99722326-cc972400-2ab0-11eb-8dd5-98f5102cb5cf.png)

Note that pylance seems to already have the required information as attested by this error message:
![image](https://user-images.githubusercontent.com/5834577/99722535-13851980-2ab1-11eb-99c2-46bc4dd559f5.png)

## Expected behaviour

Behaviour analogous to:
![image](https://user-images.githubusercontent.com/5834577/99722367-de78c700-2ab0-11eb-9942-c6626d12bfdc.png)

**Comment by erictraut** [comment]
Thanks for the suggestion.

The `__new__` and `__init__` methods for `namedtuple` and `NamedTuple` are synthesized by pyright. The `__new__` method contains all of the fields, but `__init__` contains only generic `*args` and `**kwargs`. The signature help is using the `__init__` method, so it's showing the less useful of the two in this case.

There are a couple of potential ways we could fix this. I'll need to think more about which one is better.

**Comment by erictraut** [comment]
This will be fixed in the next release.

**Comment by ARF1** [comment]
Great thank you.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.12.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020120-2-december-2020
