### ISSUE TITLE
crash 5 time 

### ISSUE THREAD

**Issue by UNOCLOCK** [microsoft/pylance-release#6313]
Type: <b>Bug</b>

with this extension on, i receive this warning :crashed 5 times in the last 3 minutes

Python Jedi client: couldn't create connection to server.
来源: Python
Go to output
The Python Jedi server crashed 5 times in the last 3 minutes.The server will not be restarted. See the output for moreinformation.
来源: Python
Go to output
Pending response rejected since connection got disposed

Extension version: 2024.8.2
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.19GB free)|
|Process Argv|--crash-reporter-id 80e63daa-9109-4b03-8d2f-f129da83eec0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562:31125793

```

</details>

**Comment by StellaHuang95** [comment]
Are you using the Jedi language server or Pylance language server? If it's Pylance, could you provide the logs as described here?
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by UNOCLOCK** [comment]
1. open a main.py file；
2. Pylance enable: no environment and i cant run files；
3. disable the Pylance, three errors happend, but i can see environment available and i can run the code files.
<img width="758" alt="20240903150132" src="https://github.com/user-attachments/assets/c9687926-bf34-4568-bbbb-3e58411e3092">


can you show me where to use this code? -------"python.analysis.logLevel": "Trace"
this is my setting.json:
```
{
    "workbench.colorTheme": "Default Dark Modern",
    "remote.SSH.remotePlatform": {
        "3": "linux",
        "3": "linux",
        "4": "linux",
        "3": "linux",
        "192.158.0.1": "linux"
    },
    "github.copilot.enable": {
        "*": true,
        "plaintext": false,
        "markdown": false,
        "scminput": false
    },
    "github.copilot.editor.enableAutoCompletions": true,
    "python.defaultInterpreterPath": "C:\\P\\A\\envs\\torch\\python.exe",
    "files.autoSave": "afterDelay",
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false
    },
    "diffEditor.hideUnchangedRegions.enabled": true
    
}

```

**Comment by UNOCLOCK** [comment]
![image](https://github.com/user-attachments/assets/d8627a42-40dc-4ff4-96bb-0f7adcffd3e3)

**Comment by StellaHuang95** [comment]
Could you put it inside of the `{}`, just below the `"diffEditor.hideUnchangedRegions.enabled": true`? That should work.

**Comment by KitRana** [comment]
having the same issue with pylance

**Comment by heejaechang** [comment]
this says you are using `Jedi`

![Image](https://github.com/user-attachments/assets/759f4f41-d482-4b39-b7a9-97f90f8bc419)

check your setting `python.languageServer` to see whether you have set it to `jedi`. if you are using `jedi`, bug should go to `jedi`. we are `pylance` not `jedi`
