### ISSUE TITLE
Pylance does not get Resource type definitions from pyvisa

### ISSUE THREAD

**Issue by lycannon** [microsoft/pylance-release#6315]
## Environment data
-   Pylance version: v2024.8.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.5

## Code Snippet
# pyVISA version 1.14.1
```python
import pyvisa
rm = pyvisa.ResourceManager()
res = rm.open_resource("USB0::0x0957::0x2807::MY62003108::0::INSTR")
res.query("*IDN?")
```

## Expected behavior
No Error

## Actual behavior

Cannot access attribute "query" for class "Resource"
Attribute "query" is unknown

## Logs
N/A

## Additional Information
This error occurs for any function calls into Resource class (res.write, res.query, etc.)

The code does work- there are no issues communicating with the VISA instruments.

**Comment by debonte** [comment]
Based on the type annotations provided by `pyVISA`, Pylance is behaving correctly here. `ResourceManager.open_resource` is annotated as returning `Resource`, and `Resource` does not have a `query` method.

My best guess is that at runtime you are getting a `MessageBasedResource` object (derived from `Resource`) as this does have a `query` method. If that's the case, one potential solution would be using `isinstance` to check if the returned `Resource` is a `MessageBasedResource`:

```python
if (isinstance(res, pyvisa.resources.messagebased.MessageBasedResource)):
    res.query("*IDN?")
```
