### ISSUE TITLE
No inspection of modules / functions from installed packages

### ISSUE THREAD

**Issue by taldcroft** [microsoft/pylance-release#632]
## Environment data

-   Language Server version: Pylance 2020.11.2
-   OS and version: MacOSX 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3 conda

## Expected behaviour

When I hover over a function from an installed (not built-in) package, I expect to see the documentation in a tooltip. The screenshot below shows the expected behavior which I get using the Jedi Language Server.

![image](https://user-images.githubusercontent.com/348089/99808284-a1432200-2b0e-11eb-8175-d9eba151588a.png)

## Actual behaviour

Using the Pylance language server this is what I get, namely no documentation.

![image](https://user-images.githubusercontent.com/348089/99808950-9f2d9300-2b0f-11eb-89f7-099be2381397.png)

I *do see* function / module docstrings for all Python built-in (standard library) packages.

As a corollary, when using Pylance I do not get any autocompletion hints in the import statement.  For instance on that line if I type `from scipy.interpolate import interp` then I do not see `interp1d` as an option. Using Jedi, I get the expected result that `interp1d` is an available function for import.

**Comment by huguesv** [comment]
I've tried to reproduce this on 2020.11.2:

After typing `from scipy.interpolate import` + space, I did not get completions. I had to force trigger completions with CTRL+SPACE to get them to appear.

But when I did, `interp1d` was in the list, and I see the docstring. Hovering on it after it's typed also gives me docstring, and go to definition takes me to the source in interpolate.py.

![image](https://user-images.githubusercontent.com/1696845/99834205-0fd8ad80-2b18-11eb-8efe-a53328b513ea.png)

I wonder if the difference could be in the version of scipy, or the use of conda. I tested using venv.

**Comment by taldcroft** [comment]
It's worth noting that relative imports or absolute imports of the package I'm editing *are found* by Pylance.  I.e. I'm working on a package called `proseco`, so if `proseco/tests/test_stuff.py` does `from proseco.acq import myfunc` then all is well. But if `proseco` is installed to the conda environment then no luck with that same line.

**Comment by taldcroft** [comment]
I also do not reproduce this problem on Windows with a conda environment, but on Mac the problem occurs for both conda and venv.

**Comment by huguesv** [comment]
Does that last comment apply to scipy? Which version of scipy is installed on your Mac, is it the same as in my screenshot?

We'll probably need the logs for this, please see https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#filing-an-issue for how to enable them.

**Comment by taldcroft** [comment]
My version of scipy is 1.5.0 (should be close enough to 1.5.4 for this). However, it is not about scipy or the package.

Here are some quasi-reproducible minimal steps for the problem.

**Make a virtualenv**

```
/usr/bin/python3 -m venv venv-play
source venv-play/bin/activate
```

**Make a minimal package in another directory:**
```
(venv-play) ➜  cat setup.py
from setuptools import setup

setup(name='play',
      version='0.1',
      packages=['play'],
      zip_safe=False)

(venv-play) ➜  cat play/__init__.py
def myfunc(a, b=1):
    """This is my function

    :param a: a
    :param b: b
    """
    print(a, b)

(venv-play) ➜  pip install .
```

**Then from a different directory edit a file:**
```
(venv-play) ➜  cat pylance.py 
from play import myfunc

(venv-play) ➜  code .
```
When I open `pylance.py` and then hover over `myfunc`, this is what comes up in the logger.  Again there is no docstring associated with `myfunc`, but `play` is shown as a module and the linter recognizes that it is an installed package.
```
Background analysis message: analyze
[BG(1)] analyzing: /Users/aldcroft/tmp/vscode-venv/pylance.py ...
[BG(1)]   checking: /Users/aldcroft/tmp/vscode-venv/pylance.py (1ms)
[BG(1)] analyzing: /Users/aldcroft/tmp/vscode-venv/pylance.py (1ms)
Background analysis message: resumeAnalysis
[FG] parsing: /Users/aldcroft/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi [fs read 1ms] (12ms)
[FG] binding: /Users/aldcroft/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi (2ms)
[FG] parsing: /Users/aldcroft/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi [fs read 0ms] (3ms)
[FG] binding: /Users/aldcroft/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi (1ms)
[FG] parsing: /Users/aldcroft/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist/typeshed-fallback/stdlib/3/typing.pyi [fs read 0ms] (21ms)
[FG] binding: /Users/aldcroft/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist/typeshed-fallback/stdlib/3/typing.pyi (8ms)
```

**Comment by taldcroft** [comment]
Just a ping on this issue which is still happening in the latest release. Have any developers tried reproducing this on a Mac? As a reminder, I do not see the same issue on Windows.

**Comment by enkeyz** [comment]
I have a similar issue: https://github.com/microsoft/pylance-release/issues/932

**Comment by taldcroft** [comment]
For me I just discovered the problem:
```
"python.analysis.useLibraryCodeForTypes": false,
```
The hover-over documentation says that this is related to discovering types when stubs are not available, but it appears to also prevent getting docstrings. I can reliably make the original problem come and go by including or excluding this setting.

Maybe there is a new issue required to make the docstring for that setting more helpful to users, but I'm closing my issue.

**Comment by jakebailey** [comment]
Ah, I see. That does make sense, as we will have to analyze the real library if stubs are present in order to do the resolution to find the corresponding symbol to get docstrings. I am a bit surprised that this setting impedes this process, however. Perhaps it's the case that it works at the first level, but some libraries re-export and we lose the info that we're trying to analyze for purposes of mapping.
