### ISSUE TITLE
Rename shadowed file code action doesn't show up

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#6328]
## Environment data

-   Pylance version: 2024.8.104

## Repro Steps

1. Clone `pylance-release`
2. Open `pylance-release\testing\single` folder in VS Code
3. Open `codeaction.py`, place cursor on `mailbox`

## Expected behavior

Lightbulb shows up and trigger quick fix and `Rename "...mailbox" to "...mailbox_x"` entry is listed

## Actual behavior

`Rename "...mailbox" to "...mailbox_x"` code action isn't showing up

**Comment by StellaHuang95** [comment]
That's because the `reportShadowedImports` is not set in `pyrightconfig.json` so it uses the default value `off`.

**Comment by rchiodo** [comment]
Default is on in pylance. That's the default for that setting. But since pyrightconfig.json is present all defaults come from that.

**Comment by StellaHuang95** [comment]
Why is this diagnostic rule special-cased in Pylance?

**Comment by rchiodo** [comment]
Because Eric didn't want that behavior for the command line in Pyright. So we override it in Pylance.
