### ISSUE TITLE
Broke imports when switching existing language server to Pylance

### ISSUE THREAD

**Issue by snowberry-clearwing** [microsoft/pylance-release#633]
## Environment data

-   Language Server version: v2020.11.2
-   OS and version: Windows 10 Version 1909 OS build 18363.1198, running extension under WSL Ubuntu 20.04.1 LTS (Focal Fossa)
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5

## Expected behaviour

It either just works or there are clearer setup instructions on how to migrate to Pylance.

## Actual behaviour

Imports broke, test discovery for pytest broke. When I uninstalled the plugin my VS Code settings defaulted to 'Jedi' when it was previously Microsoft which then broke Intellisense.

When I added Pylance to a simple Hello World! project it worked fine, it just did not want to play nicely with an existing project.

**Comment by huguesv** [comment]
Please try setting `python.analysis.extraPaths`. That is one of the settings that is different in Pylance.

From https://github.com/microsoft/pylance-release#settings-and-customization

`python.analysis.extraPaths`

Used to specify extra search paths for import resolution. This replaces the old `python.autoComplete.extraPaths` setting.
Default value: empty array

**Comment by snowberry-clearwing** [comment]
Ah yes, I saw that setting but as I had never set the what it says to be the _old_ setting it was not clear this was a necessary step. Anyhow, thank you - adding that setting seemed to resolve the problem.
