### ISSUE TITLE
Warnings are not shown for non-overridable settings when a config file is present in a multi-root workspace scenario

### ISSUE THREAD

**Issue by StellaHuang95** [microsoft/pylance-release#6338]
## Environment data

-   Pylance version: 2024.8.104

## Repro Steps

1. Clone `pylance-release`
2. Open the multi-root workspace `testing/test.code-workspace` in VS Code
3. Open `single\.vscode\settings.json`

## Expected behavior

Squiggles should appear on non-overridable settings, along with a "xxx cannot be set" warning.

## Actual behavior

No warnings or squiggles

**Comment by rchiodo** [comment]
Might have something to do with this code here:
https://github.com/microsoft/pyrx/blob/f96e1447cd84cd54934e0c4499183f7cf1ccf39f/packages/vscode-pylance/src/providers/settingsJsonWatcher.ts#L70

Maybe it's not finding the workspace folder that matches the settings.json

**Comment by StellaHuang95** [comment]
This issue has been fixed in prerelease version 2024.9.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#20249100-12-September-2024-PreRelease)
