### ISSUE TITLE
pandas: rename_axis has incorrect parameters

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#634]
## Environment data

-   Language Server version: 2020.11.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda 3.7.8

## Expected behaviour

No error

## Actual behaviour

```python
import pandas as pd

df = pd.DataFrame.from_records(
    [[1, 2, 3, 4], [5, 6, 7, 8]], columns=["a", "b", "c", "d"]
).set_index(["a", "b"])
print(df)

df2 = df.rename_axis(index={"a": "x"})
print(df2)
```

reports
```
No overloads for "df.rename_axis(index={ "a": "x" })" match parameters
  Argument types: (Dict[str, str])
```

Issue here is that `rename_axis()` without the `inplace` argument returns a `DataFrame` and that the `index` argument can be a dict or function, as in `rename()`

## Possible fix
```
diff frame.pyi.orig frame.pyi
3310c3310
<         index: Optional[IndexType] = ...,
---
>         index:  Optional[Union[Dict[Union[_str, int], _str], Callable]] = ...,
3315c3315
<         inplace: Literal[False]
---
>         inplace: Literal[False] = ...
```

NOTE:  You probably have to change the other arguments in other overloads for `rename_axis()`.  Also look at the `columns` argument as well, as it uses the same type of argument.  I just fixed this one because it fixed a problem in my code.

**Comment by gramster** [comment]
Just want to let you know we now have the type stubs in a repo at https://github.com/microsoft/python-type-stubs and will take pull requests :-)

**Comment by Dr-Irv** [comment]
> Just want to let you know we now have the type stubs in a repo at https://github.com/microsoft/python-type-stubs and will take pull requests :-)

That's great news.  For the ones where I have suggested fixes in the issue, will you apply them or do I need to create PRs ?

**Comment by jakebailey** [comment]
It'll likely be quicker to submit them there. At least for this issue, I was looking into how to apply it but I wasn't confident enough in my interpretation of your changes to stick it in for last Wednesday's release (hence why this is still open).

**Comment by gramster** [comment]
Or if you're in no rush, I will get to them before the end of the year (my bandwidth for these is less than Jake's).

**Comment by jakebailey** [comment]
Seems like this was fixed in the first January release and we didn't document it (oops). Closing.
