### ISSUE TITLE
No autocompletion for single-file mode starting from Pyright version 1.1.378

### ISSUE THREAD

**Issue by anthony-S93** [microsoft/pylance-release#6348]
**Describe the bug**
Autocomplete no longer works with single-file mode starting from pyright version `1.1.378`

**Steps to reproduce**
1. Create an empty python file `test.py`
2. Open the file with text editor.
3. Start `pyright` in single file mode.
4. Write any python code.
5. Observe the lack of autocomplete.

I've included full LSP debug logs for single-file mode and normal mode:
1. [single-file-mode.log](https://gist.github.com/anthony-S93/654b76bb86e5def5b64b8943fb0fec5b)
2. [normal-mode.log](https://gist.github.com/anthony-S93/a10e6e06ab6243399fbb94a21b323665)

Both of these logs are generated after launching pyright in two different modes on an empty python file `test.py`. In both instances, pyright was launched by the Neovim LSP Client.

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
```

Downgrading pyright to version `1.1.377` fixes the issue.

**Comment by rchiodo** [comment]
Hover doesn't work either for a single file.

**Comment by rchiodo** [comment]
Problem doesn't repro in Pylance though.

**Comment by heejaechang** [comment]
let me take a look

**Comment by rchiodo** [comment]
It looks like the default workspace is recreated for some reason. So it loses the sourceFileInfo in the original default workspace and subsequent requests don't find any source files.

**Comment by rchiodo** [comment]
It's a difference in `_getDefaultWorkspaceKey` and `_getWorkspaceKey` in the WorkspaceFactory. It doesn't return the same value for both. Probably from the python path removal stuff.

**Comment by heejaechang** [comment]
I am sending PR to pyright directly.

**Comment by rchiodo** [comment]
I could, I was in the middle of debugging it to make sure it wasn't affecting Pylance. But if you have a PR ready, feel free to submit.
