### ISSUE TITLE
Type error when assigning empty lists 

### ISSUE THREAD

**Issue by dbrattli** [microsoft/pylance-release#635]
Pylance gives error when assigning empty lists to more compound types.

## Environment data

-   Pylance language server 2020.11.2 (pyright 750a296b)
-   OS and version: Mac OS 11.01
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9 (brew)

## Expected behaviour

It should be possible to assign empty lists to variables with type hints without casting.

<img width="589" alt="Screenshot 2020-11-21 at 08 21 19" src="https://user-images.githubusercontent.com/849479/99870342-ac5f8600-2bd2-11eb-907a-78640f3dc89d.png">

## Actual behaviour

Pylance gives type error.

<img width="1056" alt="Screenshot 2020-11-21 at 08 21 32" src="https://user-images.githubusercontent.com/849479/99870353-b5505780-2bd2-11eb-8b28-aa1ae5f9e5d3.png">

## Logs

Cannot see anything unusual in the log:

[Info  - 11:46:09 PM] Pylance language server 2020.11.2 (pyright 750a296b) starting
[Info  - 11:46:09 PM] Server root directory: /Users/dbrattli/.vscode/extensions/ms-python.vscode-pylance-2020.11.2/dist
[Error - 11:46:09 PM] stubPath /Users/dbrattli/Developer/Github/aioreactive/typings is not a valid directory.
[Info  - 8:14:12 AM] No configuration file found.
[Info  - 8:14:12 AM] Setting pythonPath for service "aioreactive": "/usr/local/opt/python@3.9/bin/python3"
Search paths found for configured python interpreter:
  /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9
  /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
  /Users/dbrattli/Library/Python/3.9/lib/python/site-packages
  /usr/local/lib/python3.9/site-packages
  /Users/dbrattli/Developer/Github/aioreactive
  /Users/dbrattli/Developer/Github/Expression
  /Users/dbrattli/Developer/Github/RxPY
  /usr/local/Cellar/protobuf/3.13.0_1/libexec/lib/python3.9/site-packages
[Error - 8:14:12 AM] stubPath /Users/dbrattli/Developer/Github/aioreactive/typings is not a valid directory.
[Info  - 8:14:12 AM] Assuming Python version 3.9
[Info  - 8:14:12 AM] Assuming Python platform Darwin
[Info  - 8:14:12 AM] Searching for source files
[Info  - 8:14:12 AM] Found 53 source files
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: analyze
...
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py ...
[BG(1)]   parsing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (3ms)
[BG(1)]   binding: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (1ms)
[BG(1)]   checking: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (6ms)
[BG(1)] analyzing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (10ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
Background analysis message: setFileOpened
Background analysis message: markFilesDirty
Background analysis message: analyze
[BG(1)] analyzing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py ...
[BG(1)]   parsing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (1ms)
[BG(1)]   binding: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (0ms)
[BG(1)]   checking: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (7ms)
[BG(1)] analyzing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (8ms)
Background analysis message: resumeAnalysis
Background analysis message: getSemanticTokens
[FG] parsing: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (1ms)
[FG] binding: /Users/dbrattli/Developer/Github/aioreactive/aioreactive/testing/test.py (0ms)
Background analysis message: markFilesDirty
Background analysis message: analyze
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange

**Comment by dbrattli** [comment]
This seems to be a problem with `Tuple` types. Lists by themselves works fine:

<img width="411" alt="Screenshot 2020-11-21 at 08 58 09" src="https://user-images.githubusercontent.com/849479/99871029-bf288980-2bd7-11eb-9b16-53ac405f739b.png">

**Comment by erictraut** [comment]
Thanks for the bug report. You are correct that this occurs only for tuples, and only with generic type arguments. It's a long-standing bug that was masked by another bug that I recently fixed. 

It will be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.12.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020120-2-december-2020
