### ISSUE TITLE
auto import not working

### ISSUE THREAD

**Issue by olegkorshunov** [microsoft/pylance-release#6350]
## Environment data

-   Pylance version: v2024.8.1
-   OS and version: WSL
-   Python version (& distribution if applicable, e.g. Anaconda):  poetry 3.11.8

![image](https://github.com/user-attachments/assets/b2a98b34-4233-4095-9397-4c585686b3f1)
![image](https://github.com/user-attachments/assets/6af4dd6f-ecdb-4b05-b0ab-47fd5dbad9a5)

`settings.json`
```json
{
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "terminal.integrated.persistentSessionReviveProcess": "never",
    "terminal.integrated.enablePersistentSessions": false,
    "files.eol": "\n",
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false,
        "editor.formatOnType": true,
        "editor.wordBasedSuggestions": "off",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "ms-python.black-formatter",
        "editor.codeActionsOnSave": {
            "source.organizeImports": "explicit"
        }
    },
    "python.analysis.packageIndexDepths": [
        {
            "name": "sqlalchemy",
            "depth": 3,
            "includeAllSymbols": true,
        },
    ],
    "python.analysis.indexing": true,
    "python.analysis.autoImportCompletions": true,
    "python.analysis.autoSearchPaths": true,
    "python.analysis.importFormat": "absolute",
    "python.analysis.inlayHints.variableTypes": false,
    "python.analysis.inlayHints.functionReturnTypes": false,
    "python.testing.autoTestDiscoverOnSaveEnabled": true,
    "workbench.colorTheme": "Default High Contrast",
    "search.exclude": {
        ".idea": true,
        // ".venv": true,
        "poetry.lock": true
    },
    "editor.rulers": [
        120
    ],
    // formatter
    "pylint.args": [
        "--max-line-length=120",
        "--disable=C0114, C0115, C0116, W0105, C0200, E1101, E1121, C0103, W0621, W1203",
    ],
    "mypy-type-checker.args": [
        "--allow_redefinition"
    ],
    "black-formatter.importStrategy": "fromEnvironment",
    "black-formatter.args": [
        "--line-length=120"
    ],
    "notebook.formatOnCellExecution": true,
    // "flake8.importStrategy": "fromEnvironment",
    // "flake8.args": [
    //     "--config-toml=pyproject.toml"
    // ],
    "python.terminal.activateEnvInCurrentTerminal": true,
    "remote.autoForwardPortsSource": "hybrid",
    "workbench.editor.editorActionsLocation": "titleBar",
    "isort.importStrategy": "fromEnvironment",
    "isort.args": [
        "--profile",
        "black"
    ],
    "editor.defaultFormatter": "ms-python.black-formatter",
    "update.mode": "none",
    "extensions.autoUpdate": false,
    "editor.minimap.enabled": false,
    "explorer.compactFolders": false,
    "python.analysis.diagnosticMode": "workspace",
    "python.analysis.inlayHints.pytestParameters": true,
    "notebook.output.textLineLimit": 100,
    "files.autoSave": "onFocusChange",
    "debugpy.debugJustMyCode": false,
    "editor.formatOnSave": true,
    "notebook.formatOnSave.enabled": true,
    "[markdown]": {
        "diffEditor.ignoreTrimWhitespace": true
    },
    "jupyter.askForKernelRestart": false,
    "jupyter.debugJustMyCode": false,
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.stickyScroll.enabled": false,
    "files.insertFinalNewline": true,
}

```

**Comment by heejaechang** [comment]
what symbol are you looking for?

**Comment by rchiodo** [comment]
The variable in the other module - `uuid_pk`. It's not working because of this code here:

https://github.com/microsoft/pyright/blob/49235d38ba73200c014b1ae5b2617f1d67321352/packages/pyright-internal/src/languageService/autoImporter.ts#L467

Which looks like we only include 'CONSTANTS' as imports for variables.

**Comment by heejaechang** [comment]
this is by design then. auto import only suggests variables in `__all__` unless it is from stub file.

**Comment by rchiodo** [comment]
But why do we not include other variables? I couldn't find anything that indicates these are considered 'private'. Private is only for variables with `_` or `__`.

**Comment by heejaechang** [comment]
we already tried to include locals and back off since it includes too much stuff. python doesn't have accessibility mechanism and nobody uses `_` for variables to indicates it is private at the top level. see any of our repro steps usual put in the issue. none of them are supposed to be public but none of them uses `_`.

our escape patch is `__all__` for regular python file. if the variable is intended to be used in other module, it should be explicitly added to `__all__` otherwise, we won't expose it to `add/auto import`

**Comment by heejaechang** [comment]
one thing we have we didn't have before is new `search import` code action and `add import` ordering with MRU, so, one thing we could do is exposing `variables` in `search code` action and `add import` with lowest priority?

I believe `auto import` should be left as it is.

**Comment by heejaechang** [comment]
@olegkorshunov that said, where is this `uuid_pk` defined? it would help for us to understand the usage case?

**Comment by olegkorshunov** [comment]
> @olegkorshunov that said, where is this `uuid_pk` defined? it would help for us to understand the usage case?
here my project structure
`app/db/custom_types.py: uuid_pk`

I trying it to auto import in `wallet.py`
```
- app
    - __init__.py
    - db
       - __init__.py
       - custom_types.py.py
       - wallet.py
       ...
     ...
...
```

the
