### ISSUE TITLE
Editable installs created by uv ar enot recognized

### ISSUE THREAD

**Issue by letrec** [microsoft/pylance-release#6353]
When I have a packages installed by uv as an editable install, Pylance reports import from it as missing:

> Import "package.module" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

## Environment data

-   Pylance version: v2024.8.2
-   OS and version: Ubuntu 22.04.4 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12 from https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
-   uv version: 0.4.5

## Steps to reproduce
1. Create a venv using uv - `uv venv --python 3.10`
2. Activate the venv - `source .venv/bin/activate`
3. Install the package into the venv - `uv pip install -e ~/src/package` 
4. Open the project in VS Code with Pylance and observe that imports from the package are reported as missing

It doesn't seem to be the issue of how uv produces editable installs, because the package installed this way is completely functional in python.

I also reported this issue to uv [dist-info entry in site-packages for editable install](https://github.com/astral-sh/uv/issues/6793), but not sure where the actual problem is.

**Comment by rchiodo** [comment]
Editable installs aren't supported without compat mode in Pylance. Editable installs tend to rely on dynamic imports and since Pylance is a static type checker, we can't find the import paths.

See this for more information:
https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs

**Comment by heejaechang** [comment]
as a workaround, we can use either `extraPath` or `PYTHONPATH` to make pylance to see those `editable installs`. all the legacy editable install does is adding `PYTHONPATH` behind the back.

**Comment by charliermarsh** [comment]
I suspect you can use `uv pip install --config-setting editable_mode=compat` to get these working here.

**Comment by anentropic** [comment]
> I suspect you can use `uv pip install --config-setting editable_mode=compat` to get these working here.

@charliermarsh this indeed fixed the Pylance resolution for me (I had same issue https://github.com/microsoft/pylance-release/issues/7650)

but it just directly operates on the venv, so it's an extra manual step to remember to do

is there any way that I can specify this install method for the package in `pyproject.toml`?

currently I have:
```toml
[tool.uv.sources]
lib-a = { path = "../libs/lib-a", editable = true }
```

that by itself made an editable package that worked but Pylance couldn't resolve (and `uv pip install --config-setting editable_mode=compat ../libs/lib-a` on top of that fixed it)

the main use case for editable installs is local development, so it's awkward that the IDE doesn't support them

**Comment by anentropic** [comment]
from https://github.com/microsoft/pylance-release/issues/7650#issuecomment-3414593535

Never mind, found the docs now https://microsoft.github.io/pyright/#/import-resolution?id=editable-installs

It suggests I can do:
```toml
[tool.uv]
config-settings = { editable_mode = "compat" }
```

and indeed this works after recreating the venv and restarting VS Code
