### ISSUE TITLE
Ternary operator doesn't narrow the `else` case when using `TypeGuard`

### ISSUE THREAD

**Issue by Cleric-K** [microsoft/pylance-release#6354]
<h3> Environment data </h3>

-   Language Server version: 2024.8.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: basic

<h3> Code Snippet </h3>

```python
class C:
    s: str

def is_C(c) -> TypeGuard[C]:
    return isinstance(c, C)

def f(c: C | str):
    a1 = c.s if isinstance(c, C) else c
    # a1: str
    a2 = c.s if is_C(c) else c
    # a2: C | str
```

<h3> Repro Steps </h3>

1. Just paste the snippet in VS Code

<h3> Expected behavior </h3>

The resolved types of `a1` and `a2` should be both `str`

<h3> Actual behavior </h3>

In the first case the `else` case is properly narrowed to `str`. In the second it remains `C | str`
```python
a1: str
a2: C | str
```

<h3> Logs </h3>

N/A

**Comment by erictraut** [comment]
`TypeGuard` does not provide narrowing in the negative ("else") case. For details, refer to [this section](https://typing.readthedocs.io/en/latest/spec/narrowing.html#typeguard) of the Python typing spec. 

If you switch to the newer `TypeIs` special form, you will see narrowing in both the positive and negative cases. For more information about `TypeIs`, refer to [this documentation](https://typing.readthedocs.io/en/latest/spec/narrowing.html#typeis).
