### ISSUE TITLE
typing.Concatenate no longer works with dataclasses when used with more than one parameter

### ISSUE THREAD

**Issue by J-L0** [microsoft/pylance-release#6372]
<h3> Environment data </h3>

-   Language Server version: 2024.8.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.12.1
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: standard

<h3> Code Snippet </h3>

```python
# %% Imports
from dataclasses import dataclass
from typing import Any, Callable, Concatenate, ParamSpec, TypeVar, reveal_type

# %% Type Vars
T = TypeVar("T")
P = ParamSpec("P")

# %% Classes
class MyRegularClass:
    def __init__(self, a: int, b: int, c: int) -> None:
        self.a = a
        self.b = b
        self.c = c

@dataclass
class MyDataClass:
    a: int
    b: int
    c: int

# %% Functions
def do_something_a(input: Callable[Concatenate[int, P], Any]):
    return

def do_something_b(input: Callable[Concatenate[int, int, P], Any]):
    return

def return_unchanged(input: Callable[P, T]):
    return input

# %% Type Checking
do_something_a(MyRegularClass)  # This works
do_something_a(MyDataClass)     # This works

do_something_b(MyRegularClass)  # This works
do_something_b(MyDataClass)     # This used to work too

reveal_type(
    return_unchanged(MyRegularClass)
)  # Outputs: Type of "return_unchanged(MyRegularClass)" is "(a: int, b: int, c: int) -> MyRegularClass
do_something_b(return_unchanged(MyDataClass))  # This also works
```

<h3> Repro Steps </h3>

1. Install Pylance  2024.8.1 or later
2. Look at the code snipped above

<h3> Expected behavior </h3>
The function `do_something_b` should accept both `MyRegularClass` and `MyDataClass` since they can be seen as callables which take two integers for their first two parameters. This is the behavior seen in version 2024.7.1 (pyright version 1.1.369, commit 1168be71) and earlier.

<h3> Actual behavior </h3>

Pylance provides the following complaint when trying to pass `MyDataClass` to `do_something_b`:

```
Argument of type "type[MyDataClass]" cannot be assigned to parameter "input" of type "(int, int, **P@do_something_b) -> Any" in function "do_something_b"
  Type "((a: int, b: int, c: int) -> MyDataClass) | ((...) -> MyDataClass)" is incompatible with type "(int, int, **P@do_something_b) -> Any"
    Type "(...) -> MyDataClass" is incompatible with type "(int, int, **P@do_something_b) -> Any"PylancereportArgumentType
```
Pylance seems to hallucinate the type of `MyDataClass` as `(a: int, b: int, c: int) -> MyDataClass) | (...) -> MyDataClass)` but the `(...) -> MyDataClass)` part seems to be a mistake to me.
Running the pyright CLI version 1.1.378 directly on the file does not produce any complaints so this seems to be an issue with Pylance.

As seen by the `return_unchanged` function, Pylance can be reminded that this should work. But I would very much appreciate it if the previous compatibility could be restored although this approach may be a bit esoteric.
<h3> Logs </h3>

[output.log](https://github.com/user-attachments/files/16944985/output.log)

**Comment by erictraut** [comment]
Thanks for the bug report. This is the same root cause as https://github.com/microsoft/pyright/issues/8840, which has been fixed in the main branch of the pyright project. The problem is not with `Concatenate` but in how the constructor is converted into a callable signature. Apologies for the regression. This will be addressed in the next release of pyright and in a future release of pylance.

**Comment by J-L0** [comment]
That is good to hear, thanks! Then I'm looking forward to the next version.
