### ISSUE TITLE
IntelliCode support for Python not functioning

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/pylance-release#6397]
Type: <b>Bug</b>

Sorry, something went wrong activating IntelliCode support for Python. Please check the 'Python' and 'VS IntelliCode' output windows for details.  

Please fix it, I happen to be a upcoming data analyst who needs Python to function properly.

Extension version: 2024.14.1
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.24GB free)|
|Process Argv|--crash-reporter-id 3ab84b27-3b66-48e1-b94b-f4055dc42152|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31134655
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
pme_test_t:31118333
fje88620:31121564

```

</details>

**Comment by rchiodo** [comment]
@AGoh2019 we need more information to figure out what your problem might be. Are you using the interactive window?

**Comment by AGoh2019** [comment]
Pylance team,
I believe so.  Can't Microsoft fix its own extension.  Least expected that Pylance is giving trouble.
Regards,
--- Andrew Goh
 

    On Thursday, 19 September 2024 at 12:44:31 am SGT, Rich Chiodo ***@***.***> wrote:  
 
 


@AGoh2019 we need more information to figure out what your problem might be. Are you using the interactive window?

**Comment by rchiodo** [comment]
If you're using the interactive window then this is already fixed in our latest Pylance release version. Otherwise, we'd need more information. Specifically the information here:
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue
