### ISSUE TITLE
Python IntelliSense not working

### ISSUE THREAD

**Issue by rjpost20** [microsoft/pylance-release#6400]
Type: <b>Bug</b>

I have VS Code version 1.90.2 running on Windows 10. Recently I noticed that most if not all of my IntelliSense features are not working in my Python files.
- Nothing happens when I hover over types (functions, variables, etc.) in Python files
- Ctrl + Click on a type does nothing
- Ctrl + Right Click results in the same menu as Ctrl + Left Click

I cannot jump to a type definition, view type definitions, etc. because of this.
I have tried/checked:
- Restarting VS Code
- Disabling all extensions and re-enabling
- Making sure Python + Pylance are installed
- Making sure workspace is trusted
- Making sure hovering is enabled
- Making sure IntelliSense is enabled

Extension version: 2024.14.1
VS Code version: Code 1.90.2
OS version: Windows_NT x64 10.0.19045

UPDATE: It appears that the issue may be that latest version of Pylance (v2024.8.2) is not compatible with VS Code 1.90.2

**Comment by debonte** [comment]
@rjpost20, it's possible that Pylance crashed. Can you please switch to our latest prerelease build and see if the issue goes away? There was a recent crash related to interactive windows. Perhaps you were hitting that.

If prerelease doesn't fix the issue, can you provide your "Python Language Server" log from the Output pane?

**Comment by JoostHazelzet** [comment]
I experience this issue too since I upgraded Python extensions and VSCode. IntelliSense did work after upgrade but it stopped recently. I could not found out what triggers this, nor could I restore the IntelliSense. I use VSCode on MacOS (version 1.93.1) and work via remote tunnel on Ubuntu (code version 1.93.1). The python.languageServer is set to Default.

This is screenshot of what I see now: 
![Screenshot 2024-09-26 at 08 18 11](https://github.com/user-attachments/assets/52dba7d7-617c-4ea3-9412-b1909ffbf809)
If IntelliSense works then the imported packages show green.

**Comment by rchiodo** [comment]
@JoostHazelzet can you provide your 'Python Language Server' output?

**Comment by rchiodo** [comment]
What does your 'Python' output show? And what's your version of Pylance. 2404.14.2 is not a Pylance version number. That's likely the Python extension.

**Comment by JoostHazelzet** [comment]
My mistake, Pylance extension is on version v2024.9.2. Here is the Python output:

[python.log](https://github.com/user-attachments/files/17152618/python.log)

**Comment by rchiodo** [comment]
Are you sure your Pylance extension is enabled? And that the 'Language server' option for Python is 'Default' or 'Pylance'?

There should be a line like this in the 'Python' log:

```
2024-09-26 09:02:02.900 [info] Starting Pylance language server.
```

**Comment by JoostHazelzet** [comment]
I noticed the error messages in the python log referring to a former Mamba environment. I decided for a reinstallation of VSCode and recreation of this Mamba environment which solved the issue for me. Pylance is working like a charm again. Thank you for your support.

**Comment by debonte** [comment]
Ok if you see the issue again, feel free to reactivate this issue.

**Comment by fayizfareed** [comment]
I encountered a similar issue. I simply disabled the pylance extension and restarted the extension. Subsequently, it functioned flawlessly without the pylance extension.

**Comment by mrckzgl** [comment]
Same problem here. I installed and enabled pylance, but none of the features are working (hovering ctrl+click to get to the definition of a function). How to check if pylance is actually running?

EDIT: The "Python Language Server" log in the output pane is empty.

**Comment by rchiodo** [comment]
@mrckzgl your issue is likely a dupe of this one:
https://github.com/microsoft/vscode-python/issues/25301
