### ISSUE TITLE
warn if uncollected data is acessed

### ISSUE THREAD

**Issue by solomoncyj** [microsoft/pylance-release#6401]
for some commands, eg `filter(func, list)` , returns a uncollected list which needs to be collected with `list()` . i am requesting to have a warning that will tell the user if they are acessing a uncollected variable

**Comment by solomoncyj** [comment]
` print('result') # does not get caught and reurns a mem adress`

**Comment by debonte** [comment]
> ` print('result') # does not get caught and reurns a mem adress`

Do you mean `print(result)`? That works fine at runtime. On my machine it printed "<filter object at 0x000001FCBCF8D000>".
