### ISSUE TITLE
Problems importing a class and error with intellisense

### ISSUE THREAD

**Issue by IamDomenik** [microsoft/pylance-release#641]
In advance notice that I am working in python.

Context:
I create 2 classes in a file to work with them as modules and import them to another file (so far everything is correct)

The problem appears that when I want to import it shows me that I have a problem: ------> _Import "classes" (that's the name of the file I want to import) could not be resolved / Pylance
![imagen_2020-11-22_233118](https://user-images.githubusercontent.com/74888462/99927197-d2903d80-2d1a-11eb-9465-43c79331d846.png)

Apart from the fact that in the new file where I am implementing the code, the intellisense does not want to work for me when calling the methods in the new file.
![image](https://user-images.githubusercontent.com/74888462/99927383-91e4f400-2d1b-11eb-8a19-2cc0cb0f0046.png)

Although it shows me the error, the code still runs without any problem.
but for me the main problem is intellisense since when working with very extensive code I need it and more when importing classes.
And this is a problem that has lowered my productivity and in some cases has prevented me from continuing to work.

**Comment by huguesv** [comment]
Please see the troubleshooting doc: https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings

You can choose the import roots with `extraPaths`, open the subfolder, or use a multi-root workspace to split out the roots.

**Comment by judej** [comment]
Closing issue. Please reopen if necessary.
