### ISSUE TITLE
Hover doesnt show docs for module.func() but shows for func()

### ISSUE THREAD

**Issue by guptadivyansh** [microsoft/pylance-release#6413]
Type: <b>Bug</b>

# Behaviour

In the below example, hovering over the first curve_fit function will show the full scipy documentation but the second one will not. I would expect it to work in either case?

## Steps to reproduce:
```
from scipy.optimize import curve_fit
curve_fit()

scipy.optimize.curve_fit()
```

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

</p>
</details>

Extension version: 2024.14.1
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin x64 23.6.0
Modes:
Remote OS version: Linux x64 6.2.0-39-generic

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|autopep8|ms-python.autopep8|2024.0.0|
|Black Formatter|ms-python.black-formatter|2024.2.0|
|Data Wrangler|ms-toolsai.datawrangler|1.8.1|
|GitHub Copilot|GitHub.copilot|1.230.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.20.1|
|JavaScript Debugger|ms-vscode.js-debug|1.93.0|
|Jupyter|ms-toolsai.jupyter|2024.8.1|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.19|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|MATLAB|MathWorks.language-matlab|1.2.5|
|Pylance|ms-python.vscode-pylance|2024.9.1|
|Python|ms-python.python|2024.14.1|
|Python Debugger|ms-python.debugpy|2024.10.0|
|Rainbow CSV|mechatroner.rainbow-csv|3.12.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.9|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 6|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id a83a8754-874e-4a0e-850b-e803d902b19e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|lnmajo032istaacat|
|OS|Linux x64 6.2.0-39-generic|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700K (24 x 4786)|
|Memory (System)|188.41GB (172.45GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563
iacca1:31138162

```

</details>

**Comment by debonte** [comment]
> hovering over the first curve_fit function will show the full scipy documentation but the second one will not. I would expect it to work in either case?

Pylance is behaving correctly here. `scipy.optimize.curve_fit` is an unknown symbol because you haven't imported `scipy.optimize`.

This would fail at runtime as well. I don't know what parameters to pass to `curve_fit`, so I changed your code to the following and ran it:

```python
from scipy.optimize import curve_fit

print(curve_fit)

print(scipy.optimize.curve_fit)
```

The first `print` succeeds, but the second one fails with `NameError: name 'scipy' is not defined`.

If you add `import scipy.optimize`, you'll get the behavior you expected:

```python
from scipy.optimize import curve_fit
import scipy.optimize

curve_fit()

scipy.optimize.curve_fit()
```

![image](https://github.com/user-attachments/assets/7a9c154c-9524-4d46-810d-4bc299454fca)

**Comment by guptadivyansh** [comment]
Thanks for the explanation!

So basically I was expecting pylance to be aware of a deeper level than it possibly can statically?

**Comment by debonte** [comment]
> So basically I was expecting pylance to be aware of a deeper level than it possibly can statically?
> ...
> And if I want to change this behavior, python.analysis.packageIndexDepths is the setting to play with?

The code as written was invalid -- `scipy` is an unknown symbol, therefore `scipy.optimize.curve_fit` is unknown. Even at runtime. There is no setting that would have made Pylance understand it and show the docstring for `curve_fit`. Nor would that be desirable in my mind -- running this code would result in an exception, and Pylance's current behavior is warning you that something is wrong.

Btw, on my machine I see a diagnostic on the "scipy" of `scipy.optimize.curve_fit` which says, `"scipy" is not defined" which perhaps would have helped you figure this out on your own. I'm not sure why you're not seeing that on your side. If you're curious, you could share your settings.

![image](https://github.com/user-attachments/assets/86741c5b-9b22-412d-9e9d-2d00d2231634)

We also have an "auto import" feature that will insert any necessary import statement when a completion suggestion is used, and an "add import" code action that can be used to add an import after the fact.

`python.analysis.packageIndexDepths` changes how deeply we index into certain packages. Increasing the depth will increase indexing time, but also increase the number of symbols available in auto-import completion suggestions and "add import" code actions, but it will not change how we interpret your code.

I'm not having any luck getting auto-import to work with `curve_fit` though. Even with the following setting, it's not appearing. There may be a bug here. I'll keep playing with it.

```json
    "python.analysis.packageIndexDepths": [
        {
            "name": "scipy",
            "depth": 2
        }
    ],
```

There's been discussion about adding imports on save (similar to Go?), but we don't support that -- https://github.com/microsoft/pylance-release/discussions/6033

**Comment by debonte** [comment]
> I'm not having any luck getting auto-import to work with curve_fit though.

Oh, this is because `scipy/optimize/__init__.py` sets the value of `__all__` dynamically:
```python
__all__ = [s for s in dir() if not s.startswith('_')]
```

Pylance only recognizes a few, specific, static approaches to setting `__all__` as described [here](https://microsoft.github.io/pyright/#/typed-libraries?id=library-interface).

Auto-import does work for other `scipy` modules. For example, with `python.analysis.packageIndexDepths` set as shown in my previous comment, I can type "set_back" and see the following:

![image](https://github.com/user-attachments/assets/bd03d0a0-e40c-44eb-b53c-ef5a4fa682bf)

If I accept the highlighted completion suggestion, it inserts the following two lines into my source file:

```python
from scipy.fft import set_backend


set_backend
```
