### ISSUE TITLE
"Never" is not iterable

### ISSUE THREAD

**Issue by GammaGames** [microsoft/pylance-release#6415]
I'm writing a fixture for pytest that returns an object with an optional kwarg. It's reporting a problem even though I've checked if the variable isn't `None` and made sure it's a `list`.

## Environment data

-   Pylance version: v2024.9.1
-   OS and version: Ubuntu 22.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12

## Code Snippet

```python
def fixture():
    _arg = None
    class FixtureClass:
        def do_thing(self, arg=None):
            nonlocal _arg
            if arg is not None:
                _arg = arg

    _class = FixtureClass()
    if _arg is not None:
        if isinstance(_arg, list):
            for s in _arg:
                _class.do_thing(s)
        else:
            _class.do_thing(_arg)
```

## Repro Steps

1. Create a new python file and paste the code in

## Expected behavior

No problems

## Actual behavior

![image](https://github.com/user-attachments/assets/72a71f13-8919-4cd6-bd99-219919864381)

**Comment by debonte** [comment]
Pylance is behaving properly here. `_arg` is always `None` within `fixture()`. Therefore, `_arg is not None` will always be false. That's why `_arg` is narrowed to `Never` within that `if` block -- there's no type that `_arg` could possibly have in that context.

**Comment by GammaGames** [comment]
Makes sense, thank you! I should declare it with `_arg : str | list | None = None` instead
