### ISSUE TITLE
Allow users to blacklist certain folders

### ISSUE THREAD

**Issue by Ierezell** [microsoft/pylance-release#642]
Hi, I've been using pylance and it's a really great tool thank you ! 

I really like the "Analyse workspace things" which give lot of insight.

However, I was working with a library call weight and biases (to track ml runs) and it's checkpointing my code in a folder. 

Unfortunately, pylance check that folder and I get 1000+ errors....
I read #422 but I guess it was different enough to raise a new issue. 

The best thing possible would be to have the possibility to blacklist this folder. 

If there is a hack available please let me now.

Thanks in advance.

**Comment by erictraut** [comment]
Pylance is built on top of Pyright, Microsoft's open-source type checker. Most of Pyright's configuration options are available directly through VS Code settings, but a few of the more esoteric/advanced configuration options are not. There is an option to "exclude" specific directories in Pyright. To do so, create a "pyrightconfig.json" file at the root of your workspace and add an "exclude" section. Specify the relative path to the folder you would like to exclude. For more details and a sample config file, see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#sample-config-file).

**Comment by Ierezell** [comment]
Thanks a lot for the detailed answer which solved the problem. 

Sorry for taking your time on the stupid question. 

Have a great day :)
