### ISSUE TITLE
a problem appears in remting to a linux (vs code advice me submit a issue) 

### ISSUE THREAD

**Issue by DHOPQ** [microsoft/pylance-release#6425]
<h3> Environment data </h3>

-   Language Server version: 2024.9.2
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by DHOPQ** [comment]
how can I provide detailed information such as log .etc?

**Comment by DHOPQ** [comment]
the main problem is that the speed at which Pylance parses code is very slow (about 3000 to 4000ms each time).

**Comment by debonte** [comment]
Our log appears as "Python Language Server" in the Output pane.

There's more detail about collecting data to investigate issues, including cpuprofiles which might be useful in this case, [here](https://github.com/microsoft/pylance-release/wiki/Collecting-data-for-an-investigation.).
