### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Haymann** [microsoft/pylance-release#643]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2020.11.2`
- OS Version: `Linux x64 5.8.0-29-generic`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by MikhailArkhipov** [comment]
Please provide the file listed above (/tmp/ms-python.vscode-pylance-unresponsive.cpuprofile.txt) and, if possible, list libraries you use in your code (public ones). Thanks.

**Comment by savannahostrowski** [comment]
While this ticket isn't 30 days old, the version this issue was reported on is many versions out of date. Please update to 2020.12.2 and let us know if this high CPU usage is still a problem.

**Comment by Haymann** [comment]
Updated it to the latest version and it works fine. Thanks for your support!
