### ISSUE TITLE
Pylance client: couldn't create connection to server

### ISSUE THREAD

**Issue by avalonliberty** [microsoft/pylance-release#6444]
## Environment data

-   Pylance version: v2024.12.3
-   OS and version: Ubuntu 20.04.6 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.15

## Expected behavior

The pylance server is able to be connected and provide corresponding coloring and comment on the code

## Actual behavior

When I open the VSCode, the " Pylance client: couldn't create connection to server." error message will pop out.
This chuck of message follows with it. Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

I can't even tell what this means

**Comment by rchiodo** [comment]
Are you using VS Codium? Pylance is outputting a message saying it's not licensed to work on anything by VS Code. That's the error you get if you're trying to use Pylance on VS Codium or any other open source version of VS code.
