### ISSUE TITLE
ClassVar with specified value raises "Fields without default values cannot appear after fields with default values"

### ISSUE THREAD

**Issue by kevinleahy-switchdin** [microsoft/pylance-release#6449]
## Environment data

-   Pylance version: v2024.9.2
-   OS and version: ubuntu (WSL2)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12

## Code Snippet

```python
from dataclasses import dataclass

@dataclass
class MyClass:
    float_number: ClassVar[float] = 0.3
    int_number: int

MyClass(int_number=4)

# result: MyClass(int_number=4)
```
screenshot:
![image](https://github.com/user-attachments/assets/88442690-548e-4596-b6d1-18e3be57bafb)

Should this be an issue? It seems like since `float_number` is a class variable the concept of a "default value" doesn't apply? It's also conceptually not treated as a field at run-time: https://peps.python.org/pep-0557/#class-variables.

**Comment by erictraut** [comment]
It appears from your snippet that you're not importing `ClassVar`. If you aadd `from typing import ClassVar` to the top of your file, it should work as you expect. By default, you should see a separate error telling you that `ClassVar` is undefined, but perhaps you've disabled the `reportUndefinedVariable` check.
