### ISSUE TITLE
better understanding of isinstance(x, Sequence/Mapping/etc.) pattern

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#645]
## Environment data

-   Language Server version: v2020.11.2
-   OS and version: macOS 10.14.6
-   Python version 3.6.10 (miniconda)

## Description
I am implementing a recursive function that traverses input up to "leafs". Below a minimized version is given.

```python
import typing


def f(x):
    if isinstance(x, typing.Sequence):
        return type(x)(f(item) for item in x)  # PROBLEM HERE
    else:
        return 2 * x
```

What I mean by the problem line is "if x is either tuple or list". However, Pylance underlines the line and says: "Expected no arguments to "Sequence" constructor Pylance (reportGeneralTypeIssues)". I realize that there is not so much information for Pylance to understand my idea, however, I don't know if Pylance should be so sure that I am doing something wrong here.

**Comment by erictraut** [comment]
This error won't appear if you set typeCheckingMode to "off" (which is the default). I presume that you've enabled basic type checking mode. The reason we don't enable type checking by default is that there are cases where false positives can occur in this mode, and you will need to add more information to resolve them. This is one such case.

In this case, Pylance is using the `isinstance` call to narrow the type to the specified class. It's telling you that it's not safe to call all Sequence types with a constructor that accept an iterable. This would generate runtime exceptions if you passed the wrong type to `f`.

The most straightforward workaround is to provide a proper type annotation for parameter `x`. Something like...

```python
def f(x: Union[tuple, list, float]):
   ...
```

**Comment by Yura52** [comment]
Yes, I forgot to mention that I enabled typeCheckingMode. Thanks for the quick reply!
