### ISSUE TITLE
No error on duplicate imports

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#6452]
1. Turn on analysis 
2. Create a file:

```py
from os.path import join
from os import path
from os.path import join
from os import abort as join
```

**Bug**
There are no errors reported about `join` being imported multiple times

Maybe not a runtime error but seems like a programing mistake we should catch. Also when you run `organize imports`, it shifts the import order which changes the behavior of the code :/

**Comment by erictraut** [comment]
This is legal Python code, and it doesn't violate any static typing rules.

If you'd like to enforce a rule like "no duplicate import symbols", that's something that would be more in the domain of a linter. Popular linters for Python code include pylint and ruff. Pyright (the static analysis tool upon which pylance is built) is a type checker, so it focuses on type analysis and type violations.

**Comment by mjbvz** [comment]
Ok with pushing this to a linter but running organize imports breaks the code by changing which import is resolved in the body of my program

**Comment by erictraut** [comment]
With static type checking turned on, you should see errors if your code is broken by changing the order of imports.
