### ISSUE TITLE
Go To Definition ... NOT to stub

### ISSUE THREAD

**Issue by ahopkins** [microsoft/pylance-release#647]
Sorry if this is a duplicate. I tried looking for something about this.

When clicking "Go to definition" where there is a `.pyi`, I do not want to see the stub file. I want to be brought to the actual source code.

**Comment by huguesv** [comment]
Duplicate of https://github.com/microsoft/pylance-release/issues/65

**Comment by ahopkins** [comment]
TY. 🙏
