### ISSUE TITLE
Include types for rdkit

### ISSUE THREAD

**Issue by hadim** [microsoft/pylance-release#651]
It's a C++ library with a Python wrapper build with Boost: https://github.com/rdkit/rdkit

**Comment by hadim** [comment]
xref with https://github.com/microsoft/pyright/issues/1202

**Comment by gmseabra** [comment]
Hi, I wonder how this issue is going... It would be very useful for the chemistry community.

**Comment by judej** [comment]
This enhancement request has been open for a while. Closing old issue because of lack of upvotes. Hopefully, creating a typestub has fixed the issue for you.
