### ISSUE TITLE
Support `StrEnum` string autocomplete similar to `Literal`

### ISSUE THREAD

**Issue by pd-bryce** [microsoft/pylance-release#6518]
Suppose I have the following:

```python
from enum import StrEnum
from typing import Literal

class StrEnumExample(StrEnum):
    ABC = "abc"
    DEF = "def"

LiteralExample = Literal["abc", "def"]
```

I receive auto-completes off the literal:

<img width="594" alt="Screenshot 2024-10-03 at 6 00 07 PM" src="https://github.com/user-attachments/assets/729fb572-34cc-4272-bed6-2ce5681836b6">

And I receive auto-completes off the enum properties:

<img width="594" alt="Screenshot 2024-10-03 at 6 00 26 PM" src="https://github.com/user-attachments/assets/d37704e1-d9ca-4868-80f2-f629e0fb8e68">

But I don't receive auto-completes off strings when the type is the `StrEnum`:

<img width="594" alt="Screenshot 2024-10-03 at 6 00 55 PM" src="https://github.com/user-attachments/assets/ba02cd9a-dbb6-4eda-bf54-24f42ccd589f">

This would be a nice-to-have feature for supporting both an enum and a string as an input with great auto-complete support in both cases.

Not blocking anything as I could union these:

<img width="594" alt="Screenshot 2024-10-03 at 6 03 12 PM" src="https://github.com/user-attachments/assets/ff4170c5-aaee-4fb6-8bb8-fdbcf61da006">

But thought I'd request so I don't need to maintain the list in two places. Thanks!

**Comment by debonte** [comment]
Wouldn't `x: StrEnumType = "abc"` be invalid?

I tried this:
```python
x: StrEnumExample = StrEnumExample.ABC
print(x.name, x.value)

x = "abc"
print(x.name, x.value)
```

The first `print` succeeds, but the second raises an exception:
```text
Exception has occurred: AttributeError
'str' object has no attribute 'name'
  File "C:\issues\pylance\6518\test.py", line 14, in <module>
    print(x.name, x.value)
          ^^^^^^
AttributeError: 'str' object has no attribute 'name'
```

Pylance reports a diagnostic for the `str` assignment also:
![image](https://github.com/user-attachments/assets/b7513116-2f38-49fa-85d8-afd10dc3151a)

**Comment by pd-bryce** [comment]
Ah yeah, fair point.

The convenience of comparing a `StrEnum` to a `str` covers my use case, but that's not comprehensive of all use cases, and other use cases would have a valid reason _not_ to support this.

Thanks for the look and response!
