### ISSUE TITLE
Changing types for input arguments

### ISSUE THREAD

**Issue by Yura52** [microsoft/pylance-release#652]
## Environment data
- Language Server version: v2020.11.2
- OS and version: macOS 10.14.6
- Python version 3.6.10 (miniconda)

**typeCheckingMode == "basic"**

## Description
In `foo` everything is fine, but in `bar` all the three lines are underlined and the message is the same:
```
Expression of type "str" cannot be assigned to declared type "int"
"str" is incompatible with "int" Pylance (reportGeneralTypeIssues)
```

```python
import typing


def foo():
    x = 0
    x = str(x)


def bar(x: int):
    x = str(x)
    x = typing.cast(str, str(x))
    x = typing.cast(str, x)
```

**Comment by erictraut** [comment]
This is working as expected. You have declared that the symbol `x` within this function can be assigned only values of type `int`, but then you are attempting to assign a `str` to it. It is the job of the type checker to identify type inconsistencies like this. Since you have enabled basic type checking, these errors are expected and correct.

You should create a new local variable in this case:

```python
def bar(x: int):
    y = str(x)
```

**Comment by Yura52** [comment]
Well, if I change `x = 0` to `x: int = 0` in `foo`, then I get the same error. Then the question is why Pylance does not complain about `foo` in its first formulation AND infers the type of `x` as `str` (not `Union[int, str]`)?

**Comment by erictraut** [comment]
There is no inference used when you declare a type for a symbol. Inference is used only in cases where a symbol (like a variable or parameter) has no declared type. By adding the type annotation `: int` to `x`, you are declaring the type of `x`.

If you omit the type declaration, then pylance will attempt to infer its type using the available information. In this case, its type will be `Union[Unknown, str]`. The `Unknown` is a special form of `Any`, and it comes from the fact that the input parameter type cannot be inferred. The `str` comes from the assignment. Pylance is also applying type narrowing to narrow the type to just `str` after the assignment.

For more details about type declarations and type inference, see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-inference.md).

For more details about type narrowing, see [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-narrowing).
