### ISSUE TITLE
No autocomplete for `Literal` with descriptor `__set__` method

### ISSUE THREAD

**Issue by armoha** [microsoft/pylance-release#6523]
Might be related to https://github.com/microsoft/pylance-release/issues/5299

<h3> Environment data </h3>

-   Language Server version: 2024.9.104
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.11.9 64 bit
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
from __future__ import annotations

from typing import overload, Self, Literal


class FooDescriptor:
    @overload
    def __get__(self, instance: None, owner: type[Foo]) -> Self:
        ...

    @overload
    def __get__(self, instance: Foo, owner: type[Foo]) -> str:
        ...

    def __get__(self, instance, owner):
        if instance is None:
            return self
        return "foo"

    def __set__(self, instance: Foo, value: Literal["abc", "def"]) -> None:
        pass


class Foo:
    foo = FooDescriptor()


foo = Foo()
foo.foo = "_no_literal_suggestion_"

```

<h3> Repro Steps </h3>

Type `foo.foo = ""` and no auto-completes off the literal.

<h3> Expected behavior </h3>

Literal `"abc"`, `"def"` are suggested in the autocomplete popup, just like how property works:

![image](https://github.com/user-attachments/assets/b38d4b2e-c095-4361-aabe-489651a5a552)

<h3> Actual behavior </h3>

No autocomplete popup appears.

![image](https://github.com/user-attachments/assets/9bebc20b-b534-4ba2-8678-dbc8ce01faf6)

<h3> Logs </h3>

https://gist.github.com/armoha/444e446feed23b09a19371e83dd6d3c9

**Comment by debonte** [comment]
If I annotate `Foo.foo` as `ClassVar[FooDescriptor]` I get the expected behavior.

![image](https://github.com/user-attachments/assets/91be17e5-988e-4a13-b580-cb9f3832ade4)

**Comment by armoha** [comment]
Annotating `ClassVar[FooDescriptor]` solved it, thank you!
