### ISSUE TITLE
Type checking stating None maybe present in Iterable despite filter() -ing output

### ISSUE THREAD

**Issue by vishalnandagopal** [microsoft/pylance-release#6526]
## Environment data

-   Pylance version: v2024.9.2
-   OS and version: Windows 11
-   Python version: 3.12.6

I have type checking enabled.
`"python.analysis.typeCheckingMode": "basic"` in VSCode settings.json

## Code Snippet

```python
def dummy(a: str) -> str | None:
    return a

result = ["a", "b", None]
m = map(lambda x: dummy(x), result)
_ : filter[str] = filter(bool, m)
```

```python
def dummy(a: str) -> str | None:
    return a

result = ["a", "b", None]
m = map(lambda x: dummy(x), result)
_: list[str] = list(filter(bool, m))
```

## Repro Steps

1. Create python file, paste the code.

## Expected behavior

It should not show an error stating None might come into the filter. Since I have filtering using the function bool, the elements with value `None` will be filtered out and no longer present

Same issue is reproduced even if type of variable `_` is `list[str]`

## Actual behavior

Error shown
```
Type "filter[str | None]" is not assignable to declared type "filter[str]"
  "filter[str | None]" is not assignable to "filter[str]"
    Type parameter "_T@filter" is invariant, but "str | None" is not the same as "str"Pylance[reportAssignmentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportAssignmentType)
```

**Comment by erictraut** [comment]
Pyright (the type checker that pylance is built upon) is working correctly here. Type evaluation for calls to stdlib functions like `filter` are dictated by the type information provided in the community-maintained typeshed stubs. You can find the definition for the `filter` class [here](https://github.com/python/typeshed/blob/99095f5437dc4ce045a33dab55d1c1eeac1ea04d/stdlib/builtins.pyi#L1404).

The `filter` constructor has four overloads. The one that applies in your code example is the fourth one.
```python
class filter(Iterator[_T]):
    ...
    def __new__(cls, function: Callable[[_T], Any], iterable: Iterable[_T], /) -> Self: ...
```

In your first code sample, the type of `m` is `map[str | None]`. This is a subtype of `Iterable[str | None]`. That means the type variable `_T` takes on the value of `str | None`, and the result of the constructor call is a value of type `filter[str | None]`. This type isn't compatible with `filter[str]`, hence the type error.

All of this behavior is defined by the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/index.html), which pyright [adheres to](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html).

If you want to eliminate the type checker error, you have a couple of options.

1. Define your own filter function with a [TypeIs](https://typing.readthedocs.io/en/latest/spec/narrowing.html#typeis) return type:

```python
def str_none_filter(x: str | None) -> TypeIs[str]:
    return bool(x)

_: filter[str] = filter(str_none_filter, m)
```

This is a bit more verbose, but it gives a static type checker the information it needs to validate type correctness in this case.

2. In this particular case, specifying `bool` as the filter function is not needed. Instead, you can specify `None` when calling `filter`, in which case it will perform a truthy check. This uses the first overload, which gives you the results you're looking for.

```python
_: filter[str] = filter(None, m)
```

**Comment by vishalnandagopal** [comment]
Thank you for the detailed information. It makes sense why the error is being thrown now. I thought pyright tries to understand the function/filter/map output ~like mypy, which wasn't throwing an error when I used it for this function.~

mypy doesn't seem to be throwing an error even when I intentionally put wrong types here, so I guess it is just ignoring the function here.

> you can specify None when calling filter, in which case it will perform a truthy check

Thanks for this info. While it would not work for me in my actual use case here, this is new to me and I can use in the future..
