### ISSUE TITLE
StopIteration has wrong __init__ doc

### ISSUE THREAD

**Issue by jeffreyyjp** [microsoft/pylance-release#653]
## Environment data

-   Language Server version: v2020.11.2
-   OS and version: 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2

## Expected behaviour

Show each specific info for Exception

## Actual behaviour

![image](https://user-images.githubusercontent.com/17985592/100405812-5a6da300-309f-11eb-8b39-01abc403f6f8.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
There's some inconsistency here. When just the type is present:

![image](https://user-images.githubusercontent.com/5341706/100675737-6023ec80-331c-11eb-9395-ef8b0eaaa86e.png)

But when it's called, the `__init__` function's doc is used:

![image](https://user-images.githubusercontent.com/5341706/100675763-6ca84500-331c-11eb-8793-f716f53ac031.png)

But, I can see in the generated file for the builtin docstrings that it should be working:

![image](https://user-images.githubusercontent.com/5341706/100675861-9e211080-331c-11eb-951c-555f0f853f16.png)

So, very likely a bug in the docstring fetching code for init methods.

**Comment by erictraut** [comment]
The problem here is that these subclassed exceptions don't have an `__init__` method override, so we're finding the `__init__` in the base class `Exception`, and we're picking up the docstring from that class.

**Comment by jakebailey** [comment]
Ah, yeah. That's what I thought. I'm thinking that there would need to be an alternate traversal that checks the shadow files for docs rather than the regular type lookup that doesn't consider it.

**Comment by CodeCrazy-ywt** [comment]
@erictraut @jakebailey I came up with an idea -- simply find the class's __doc__ attribute. Will that help?

**Comment by CodeCrazy-ywt** [comment]
Excuse me, but when will this problem be solved? It's been quite a long time since this issue was opened. JediLSP is doing the correct behavior. So when will Pylance？

**Comment by jakebailey** [comment]
The next version should fix this particular case (inheriting `object`'s docs), though the whole source mapping when typeshed and our scraped output mismatch is another problem.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202191-8-september-2021
