### ISSUE TITLE
Type checking fails for Huggingface datasets

### ISSUE THREAD

**Issue by saiden89** [microsoft/pylance-release#6534]
## Environment data
-   Pylance version: v2024.9.2
-   OS and version: MacOS Sequoia 15.0
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12, via anaconda
- Huggingface datasets version: 3.0.1
## Code Snippet
```python
from datasets import Dataset

dataset = Dataset.from_parquet(path_or_paths="file")
dataset.map(lambda x: {"new": x["old"]}, batched=True)
```

## Expected behavior
`map` is a [valid](https://huggingface.co/docs/datasets/v3.0.1/en/package_reference/main_classes#datasets.Dataset.map), no error should be thrown.

## Actual behavior
Pylance throws the error
`Cannot access attribute "map" for class "Dict[str, IterableDataset]" Attribute "map" is unknown`

**Comment by debonte** [comment]
The return type of `Dataset.from_parquet` is not annotated. When `python.analysis.useLibraryCodeForTypes` is set to `true`, our type checker looks at the library code to determine what types may be returned. Despite the fact that the `from_parquet` docstring says it will only return a `Dataset`, the type checker determines that the return type is `Dict[str, IterableDataset] | IterableDataset | Dataset | DatasetDict`. You can come to the same conclusion by digging into the function that `from_parquet` calls to calculate its return value, the functions that function calls, and so on.

For `map` to be a valid call on the `dataset` variable, it would need to be valid for all of the possible return types of `from_parquet`, but it is not a valid call on the `Dict[str, IterableDataset]` as pointed out by the diagnostic.

If you believe that the docstring is correct, consider [filing an issue](https://github.com/huggingface/datasets/issues) on the `datasets` package to ask that the authors provide a return type annotation.

In the meantime, you can solve this in your code by doing an `isinstance` check:
```python
dataset = Dataset.from_parquet(path_or_paths="file")
if isinstance(dataset, Dataset):
    dataset.map(lambda x: {"new": x["old"]}, batched=True)
```

or by casting:
```python
dataset = cast(Dataset, Dataset.from_parquet(path_or_paths="file"))
dataset.map(lambda x: {"new": x["old"]}, batched=True)
```
