### ISSUE TITLE
pylance doesn't show errors on settings.json when pyrightconfig.json exists

### ISSUE THREAD

**Issue by heejaechang** [microsoft/pylance-release#6546]
## Environment data

-   Pylance version: 2024.10.101

1. Create `pyrightconfig.json` at the root of `pyrx`
2. Open `settings.json` in `.vscode`
3. See something like `python.analysis.include` in `settings.json`

Expected: `python.analysis.include` has error squiggle
Actual: Nothing.

....

We probably need to test a scenario where a repo uses multiple languages.

**Comment by rchiodo** [comment]
Could this be because pylance hasn't loaded? Don't you need to open a python file?

**Comment by StellaHuang95** [comment]
I can't repro. I do see the warnings after opening a python file, closing.
