### ISSUE TITLE
type<long> not defined in Python2

### ISSUE THREAD

**Issue by Arrow-Li** [microsoft/pylance-release#655]
## Environment data

-   Language Server version: Pylance language server 2020.11.2 (pyright 750a296b)
-   OS and version: CentOS 7 with VS Code remote
-   Python version (& distribution if applicable, e.g. Anaconda): 2.7.15

## Expected behaviour

Class long is exist in py2

## Actual behaviour

`"long" is not defined`
![typelong](https://user-images.githubusercontent.com/17962902/100430725-1f389780-30d2-11eb-9e1d-7e829befcbde.jpg)

## Logs

```
{
	"resource": "xxx.py",
	"owner": "_generated_diagnostic_collection_name_#2",
	"severity": 4,
	"message": "\"long\" is not defined",
	"source": "Pylance (reportUndefinedVariable)",
	"startLineNumber": 91,
	"startColumn": 75,
	"endLineNumber": 91,
	"endColumn": 79
}
```

## Code Snippet / Additional information

None

**Comment by erictraut** [comment]
Pylance doesn't support Python 2. You can use the older Jedi language server if you still have the need to use Python 2.

**Comment by Arrow-Li** [comment]
> 
> 
> Pylance doesn't support Python 2. You can use the older Jedi language server if you still have the need to use Python 2.

I have both Python2&3 project, how can I setting language server for each project?

**Comment by Arrow-Li** [comment]
Any plan to support Python2 in the future?

**Comment by erictraut** [comment]
You can specify per-workspace settings to select language server.

Pylance is designed for use with Python 3, and we have no plans to add support for Python 2.

**Comment by jakebailey** [comment]
Yes, we don't plan to support Python 2. #156, #177, #7
