### ISSUE TITLE
Warn when official vscode not detected

### ISSUE THREAD

**Issue by SollyBunny** [microsoft/pylance-release#6558]
I had the exact same issue as #5375.

Can the extention warn when it refuses to run via a popup or any logs in outputs rather than failing silently

**Comment by KacieKK** [comment]
Hey @SollyBunny, Thanks for posting. Can you please provide a log as described under "Filing an issue" in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by SollyBunny** [comment]
Everything on the linked issue is exactly the same as mine

I'm in arch Linux 
Using vscodium with Microsoft marketplace

The logs are the same for both provided by linked issue
There's no completion of any kind

**Comment by debonte** [comment]
>Can the extention warn when it refuses to run via a popup or any logs in outputs rather than failing silently

We're already logging a message explaining this in the Pylance log ("Python Language Server") as shown in the referenced issue. Are you not seeing this in your log?

> 2024-01-22 14:40:49.163 [info] (Client) You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

**Comment by SollyBunny** [comment]
> We're already logging a message explaining this in the Pylance log ("Python Language Server") as shown in the referenced issue. Are you not seeing this in your log?
> ...

I thought that was just some random legal nonsense and didn't bother reading it... so my bad.
