### ISSUE TITLE
"Argument missing" error given for class init even though there's a matching __new__ overload

### ISSUE THREAD

**Issue by matangover** [microsoft/pylance-release#6563]
## Environment data

-   Pylance version: v2024.10.1
-   OS and version: macOS 14.6.1
-   Python version: 3.10.0

## Code Snippet

`pip install pedalboard==0.9.16`

```python
from pedalboard.io import AudioFile
AudioFile("input.wav")
```

## Expected behavior

No error

## Actual behavior

Argument missing error:
![Image](https://github.com/user-attachments/assets/ada9bb0f-10ce-4512-a4b8-5c3d4d5aa0a3)

Here's the definition of the overload that I expected should be matched:
![Image](https://github.com/user-attachments/assets/acbf2638-f7ae-45b2-a1f0-6d156dba6b89)

**Comment by erictraut** [comment]
This is a bug in the type stub for `pedalboard`. It is overwriting the definition of `typing.overload` with a local version.

```python
typing.overload = patch_overload
```

It looks like these stubs are auto-generated. They contain a bunch of things that shouldn't appear in well-written stubs. I recommend filing an issue (or better yet, a PR) with that project.

**Comment by matangover** [comment]
Oh ok thanks. What are the other errors in the stub? They are generated with pybind.
