### ISSUE TITLE
possibly unbound variable with the same if statment before bound and before used

### ISSUE THREAD

**Issue by AradAlon** [microsoft/pylance-release#657]
## Environment data

-   Language Server version: 2020.11.2 (pyright 750a296b)
-   OS and version: Ubuntu 18.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6

## Expected behaviour

Pylance should recognize the same if statement was used to bound `b` and used before using `b`'s value

## Actual behaviour

Pylance think `b` is possibly unbound although he will always be bound under those circumstances

## Code Snippet / Additional information

```python
a = {"a": 3}
tmp = a.get('a')
if tmp:
    b = tmp
... #some code that is not related to b or tmp
for i in range(10):
    if tmp and (b < i):
        print("yayy")
```

**Comment by erictraut** [comment]
I don't think it's practical for a type checker to retain conditional types for a variable that are based on the types of other variables. That's what would need to be done here, and it would add enormous complexity and cost to the type checker. I don't know of any other type checker in any language that supports this.

The right way to handle this is to always initialize `b`.

```python
a = {"a": 3}
tmp = a.get('a')
b = tmp
... #some code that is not related to b or tmp
for i in range(10):
    if b is not None and (b < i):
        print("yayy")
```

**Comment by AradAlon** [comment]
This is the only way of solving this?
I thought  a more straight forward solution could be used, like comparing hashes of the if statement.
We don't care about `tmp`'s type (since it could be a more complex if statement), only that it is the key to `b` (or other hashable value).
So if `b` is bounded under some condition (the key), Pylance just check that the same key will appear before future uses of `b`.
The variable could shake himself from the key, or get a new one, when it will be assigned again

**Comment by erictraut** [comment]
No, it's much more complicated than that. For one thing, `tmp` can been reassigned at various points in the code flow (e.g. between the initial test and the subsequent test), so it's not sufficient to simply check that the expression is the same in both locations. In this example, `tmp` is reassigned in two different locations that are "between" the first test and the place where `b` is used. 

```python
if tmp:
   b = tmp

tmp = <something else>

for i in range(10):
   if tmp and (b < 1):
      print("yayy")

   tmp = <something else>
```

When the type checker determines the type for a symbol at a particular point where that symbol is used, it performs code flow analysis walking backward up the code flow graph to discover all of the ways the symbol is assigned a value. This information is then propagated back down the code flow graph, applying type narrowing as appropriate. In the case of `b` in the subexpression `(b < i)`, it finds that `b` is assigned on some code paths and not others, so it is still potentially unbound at the point it is used. To do what you're suggesting would require that the type analyzer remember all of the conditions under which each type was assigned and invalidate those conditions in cases where they are no longer valid (e.g. `tmp` is reassigned). While theoretically possible, it would explode the amount of information and the computation required for type checking — to the point of being impractical.

**Comment by AradAlon** [comment]
Ok I understand the complexity now, Thank you for the detailed explanation 👍
