### ISSUE TITLE
Defining generic following PEP-695 new syntax causes incorrect static type analysis.

### ISSUE THREAD

**Issue by raceychan** [microsoft/pylance-release#6579]
```python
import typing as ty

class IErrorResponse(ty.Protocol):
    content: "ErrorDetail"
    headers: dict[str, str]
    status_code: int


type ExceptionHandler[Exc] = ty.Callable[[Request, Exc], IErrorResponse]

class HandlerRegistry[Exc: Exception]:
    """
    Add error handler to fastapi according to their signature
    """
    __upper_bound__ = Exc
    _handlers: dict[type[Exc] | int, ExceptionHandler[Exc]]


    def register(self, handler: ExceptionHandler[Exc]) -> ExceptionHandler[Exc]:
         ....

class GeneralAPPError(Exception): ...
class GeneralWebError(Exception): ...
class AuthenticationError(GeneralWebError): ...


assert HandlerRegistry.__upper_bound__ is Exception #True 
```

According to [PEP-695](https://peps.python.org/pep-0695/#upper-bound-specification) by @erictraut 

> 

```python
# Defining a generic class prior to this PEP looks something like this.

from typing import Generic, TypeVar

_T_co = TypeVar("_T_co", covariant=True, bound=str)

class ClassA(Generic[_T_co]):
    def method1(self) -> _T_co:
        ...
With the new syntax, it looks like this.

class ClassA[T: str]:
    def method1(self) -> T:
        ...
```

Exc defined in HandlerRegistry class should be a convariant, but here pylance thinks Exc is an invariant
![Image](https://github.com/user-attachments/assets/ffa164b1-4f95-40db-a3fe-52ef2badce27)

![Image](https://github.com/user-attachments/assets/3383fad0-4f75-4367-9b59-21ac839909e4)

which leads to following errors:

Here, we define handler_registry like this
```python
handler_registry: ty.Final[HandlerRegistry[GeneralWebError]] = HandlerRegistry()
``` 
pylance says that "GeneralWebError" is incompatible with "AuthenticationError"
where AuthenticationError is a subclass of GeneralWebError, and GeneralWebError is a subclass of Exception
![Image](https://github.com/user-attachments/assets/eed5cba2-d8f8-4d46-942e-67fc3ad7d1c9)
![Image](https://github.com/user-attachments/assets/83a47448-e4d6-4efa-a74f-17649b365671)

**Comment by raceychan** [comment]
smaller reproduction.

```python
class ClassA[T: str]:

    type ExceptionHandler = ty.Callable[[int, T], ty.Any]

    def register(self, handler: ExceptionHandler) -> ExceptionHandler: ...


class substr(str):
    pass


a: ClassA[str] = ClassA()


@a.register
def test(request: int, exc: substr):
    ...

```

![Image](https://github.com/user-attachments/assets/9b1424cb-2a1f-4e92-8de3-6097dde7eff2)
![Image](https://github.com/user-attachments/assets/5c762263-2920-49aa-9654-0b393875fe8e)

**Comment by raceychan** [comment]
update:
I change it back to the old syntax using typing.TypeVar, but the issue still exists, so using pep-695 defined new syntax might not be the root cause.

**Comment by erictraut** [comment]
Pyright is working correctly here. The type parameter `T` in `ClassA` is invariant because it is used in both a function input and return type. That means `a.register` (where `a` is of type `ClassA[str]`) must be passed an argument that is a callable that accepts a `str` as its second parameter. In your example, `test` is a callable, but it accepts a `substr` as its second parameter. While `substr` is a subtype of `str`, it's not an exact match. Invariance requires that the types be the same.

If you have questions about type parameters and invariance, feel free to post to the [pyright discussions forum](https://github.com/microsoft/pyright/discussions) or the [Python typing forum](https://discuss.python.org/c/typing/32).

**Comment by raceychan** [comment]
> Pyright is working correctly here. The type parameter `T` in `ClassA` is invariant because it is used in both a function input and return type. That means `a.register` (where `a` is of type `ClassA[str]`) must be passed an argument that is a callable that accepts a `str` as its second parameter. In your example, `test` is a callable, but it accepts a `substr` as its second parameter. While `substr` is a subtype of `str`, it's not an exact match. Invariance requires that the types be the same.
> 
> If you have questions about type parameters and invariance, feel free to post to the [pyright discussions forum](https://github.com/microsoft/pyright/discussions) or the [Python typing forum](https://discuss.python.org/c/typing/32).

thanks, eric. sorry to bother you again, I think I do need to know more about these details such as when generic being used in both a function input and return type then it becomes invariant. so that i don't need to raise incorrect issue

**Comment by raceychan** [comment]
@debonte woud you mind re-open the issue or transfer it to discussion?

**Comment by erictraut** [comment]
@raceychan, if you have general questions about the Python type system, the [Python typing forum](https://discuss.python.org/c/typing/32) is a good place to post those questions.

If you have questions specifically about pyright's type checking features, the [pyright discussion forum](https://github.com/microsoft/pyright/discussions) is a good place to post.

**Comment by raceychan** [comment]
> [@raceychan](https://github.com/raceychan), if you have general questions about the Python type system, the [Python typing forum](https://discuss.python.org/c/typing/32) is a good place to post those questions.
> 
> If you have questions specifically about pyright's type checking features, the [pyright discussion forum](https://github.com/microsoft/pyright/discussions) is a good place to post.

Thanks, would do.
