### ISSUE TITLE
Performance issue reported from VSCode/Pylance

### ISSUE THREAD

**Issue by dax-westerman** [microsoft/pylance-release#6580]
<h3> Environment data </h3>

-   Language Server version: 2024.10.101
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by debonte** [comment]
Thanks for the report. Unfortunately, this is not enough information for us to investigate this issue. 

If this continues to be a problem, would you please reopen the issue and add the information described in [the troubleshooting guide](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)?

**Comment by dax-westerman** [comment]
No problem, this was a pop-up asking me if I wished to report the performance issue, so I clicked "yes".  If there is additional detail I can provide, happy to do so.  I am unaware of what caused the issue, however, as it just showed up.  That said, I might suggest improving the default issue generation, please.  If I am to take the time to help improve the product by sharing details, it will be helpful to know how to do so, other than closing the issue on an item for which I could not have additional context.

**Comment by debonte** [comment]
Can you share the project you were editing when you encountered this? Also, the "Python Language Service" log (from the time when you saw this) would be helpful.

The agree that using a different issue template for perf issues would make sense.

**Comment by dax-westerman** [comment]
Sure, be happy to.  Attached is log (redacted to obscure compute paths).  Sorry, can't post code.  In reviewing the places where the long-running operation was occurring, the code's pretty light in those places.  That said, I think the issue might be related to Remote-SSH.  The remote doesn't have an entry for this time frame, attached is local.   

[local Python Language Server.log](https://github.com/user-attachments/files/17452421/local.Python.Language.Server.log)

**Comment by debonte** [comment]
Without being able to repro the issue, we won't be able to fix it. Would you be willing to share the code privately? We would only use it to repro the issue and then delete it. Alternatively, if you can narrow down the repro (ex. by commenting out code until it goes away), perhaps you can generate a separate project that repros the problem without exposing anything proprietary.
