### ISSUE TITLE
performance issue with pylance

### ISSUE THREAD

**Issue by viniciusmilk** [microsoft/pylance-release#6585]
<h3> Environment data </h3>

-   Language Server version: 2024.10.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
XXX
```

<h3> Repro Steps </h3>

1. XXX

<h3> Expected behavior </h3>

XXX

<h3> Actual behavior </h3>

XXX

<h3> Logs </h3>

```
XXX
```

**Comment by KacieKK** [comment]
Thanks for the issue, but we don't have enough information to resolve your problem. Can you please provide a log as described under "Filing an issue" in the troubleshooting guide? If you have more information, please reopen.
