### ISSUE TITLE
include pandas, matplotlib and other bundled stubs 

### ISSUE THREAD

**Issue by tekumara** [microsoft/pylance-release#659]
Pylance bundles stubs for:
* django
* jmespath
* matplotlib
* pandas
* PIL
* onnxruntime

Pyright doesn't.

Would be nice to have a consistent user experience when using Pylance in VSCode and Pyright on the CLI and in CI/CD.

If this isn't possible, would it be possible to provide these stubs (in particular pandas and matplotlib) as a separately installable pypi distribution?

**Comment by jakebailey** [comment]
I'm going to mark this as a duplicate of #277. We already intend to publish the stubs somewhere, though I'm not so sure about a PyPI package immediately.

`onnxruntime` is not a Python module; we don't ship stubs for that.
