### ISSUE TITLE
Statements must be separated by newlines or semicolon

### ISSUE THREAD

**Issue by xkotj** [microsoft/pylance-release#66]
## Environment data
-   Language Server version: 2020.6.1
-   OS and version: Win 10, 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 2.7.18rc1, virtualenv

## Expected behaviour

No Problem message

## Actual behaviour

Statements must be separated by newlines or semicolons

## Code
```python
x = 10
try:
    print str(x)
except Exception as ex:
    print str(x)
```

**Comment by erictraut** [comment]
The print keyword is not supported in Python 3, so this code will not run in a Python 3 interpreter. 

Pylance does not support Python 2. If you still have Python 2 code that you need to support, you can use the Jedi language server instead.

**Comment by xkotj** [comment]
So python 2.7 is not supported? I was migrating from Microsoft Python Language Server and I did not see it’s not supported.
I am closing this issue. Thanks

**Comment by YupegLV** [comment]
How do I turn off this prompt？

**Comment by YupegLV** [comment]
How do I turn off this prompt in diagnosticSeverityOverrides？

**Comment by jakebailey** [comment]
There is no way to disable a syntax error; if you believe there's a bug in the parser, please file a new issue. But, this issue was for Python 2 compatibility, and we have no plans to support Python 2, so if your error stems from the `print` keyword, that's issue which we aren't going to change.
