### ISSUE TITLE
pandas: loc indexer not return the correct type of object

### ISSUE THREAD

**Issue by RuixiangLiu01** [microsoft/pylance-release#660]
Hi, developer. I meet  a problem when using 'loc' to select some columns, it seems 'loc' doesn't return the a DataFrame for me
![image](https://user-images.githubusercontent.com/37862626/100577159-93fe1280-331a-11eb-9f7d-ebe9a1b3edf5.png)
![image](https://user-images.githubusercontent.com/37862626/100577215-ae37f080-331a-11eb-9622-38f9ca2b65e0.png)

any advise would be appreciated, thanks

**Comment by RuixiangLiu01** [comment]
update:
I checked the stub files
![image](https://user-images.githubusercontent.com/37862626/100581008-ea228400-3321-11eb-8f17-2318c58e010b.png)
I think my code should be refered as a DataFrame not a Seires accroding to the code in stub file

**Comment by judej** [comment]
@RuixiangLiu01, could you please add a code snippet for this so that we could repro?

**Comment by RuixiangLiu01** [comment]
> @RuixiangLiu01, could you please add a code snippet for this so that we could repro?

Thanks for reply. Here is a simple example:
`df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [2, 3, 4, 5]})
df1 = df.loc[:,'A']`
![image](https://user-images.githubusercontent.com/37862626/100689525-9797a500-33bf-11eb-9e65-c8737ef19b3b.png)
![image](https://user-images.githubusercontent.com/37862626/100689580-b1d18300-33bf-11eb-9bdb-e4bb9479402e.png)

I am not sure is it helpful for u

**Comment by gramster** [comment]
In that example you gave, Pylance infers that df is a DataFrame and df1 is a Series, and that is correct. Can you give an example where waht Pylance shows you is not correct?

**Comment by gramster** [comment]
This is a non-trivial fix; right now things only work as well as they do because of a bug :-( There's a bunch of complexity around this kind of indexing that I need to think through.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.5.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202150-5-may-2021
