### ISSUE TITLE
Move to symbol code action is not available

### ISSUE THREAD

**Issue by luabud** [microsoft/pylance-release#6604]
<h3> Environment data </h3>

-   Language Server version: 2024.10.102
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): poetry with Python 3.12.7
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
x = 10

```

<h3> Repro Steps </h3>

1. Open a folder and create a Python file with "x = 10" 

<h3> Expected behavior </h3>

Invoking code actions on `x` should show "move symbol" code action

<h3> Actual behavior </h3>

![Image](https://github.com/user-attachments/assets/d6066141-4474-4b65-9e9c-428ecfe997ce)

<h3> Logs </h3>

[pylancelogs20241025.txt](https://github.com/user-attachments/files/17528054/pylancelogs20241025.txt)

**Comment by heejaechang** [comment]
from the log, it shows

```
2024-10-25 15:31:33.889 [info] (29596) Searching for source files
2024-10-25 15:31:33.892 [info] [Info  - 3:31:33 PM] (29596) No source files found.
```

so, we probably need your settings. it looks like the file you opened is not recognized as user file.

**Comment by luabud** [comment]
ah, I was using a different profile that had `light` language server mode  🤦‍♀️ thanks!
