### ISSUE TITLE
Add code lens for code navigation of references and implementation of functions/classes

### ISSUE THREAD

**Issue by snowberry-clearwing** [microsoft/pylance-release#661]
Currently the only code lens support seems to be for the status of tests. I would like to see code lens added to code in general that assist with code navigation by showing references and implementation of functions/classes (similar to how this works in Visual Studio and other languages in VS Code e.g. TypeScript). For example: https://docs.microsoft.com/en-us/visualstudio/ide/find-code-changes-and-other-history-with-codelens?view=vs-2019

**Comment by judej** [comment]
This enhancement request has been open for a while. Closing old issue because of lack of upvotes.
