### ISSUE TITLE
Should be mandatory to always return "None" when doesn't return anything?

### ISSUE THREAD

**Issue by JonathanLoscalzo** [microsoft/pylance-release#6622]
I prefer not to explicitly type obvious return types, such as for functions or methods that don't return anything. In these cases, I believe the inference should automatically use `-> None` instead of `-> Any`. However, the issue is that I’m not receiving any inference because of this error:
`Analysis of function "setUp" is skipped because it is unannotatedPylance`

<h3> Environment data </h3>

-   Language Server version: 2024.10.1
-   OS and version: darwin arm64
-   Python version: 3.10.11 
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: standard

<h3> Code Snippet </h3>

```python
class TestExample(TestCase):
    def setUp(self):
        return super().setUp()

    def test_fake_method(self):
        2 + 2
```

<h3> Repro Steps <h3>

- save the file, and wait to inference
- see the inference for those methods

<h3> Expected behavior </h3>

```python
class TestExample(TestCase):
    def setUp(self) -> None:
        return super().setUp()

    def test_fake_method(self) -> None:
        2 + 2
```

<h3> Actual behavior </h3>

```python
class TestExample(TestCase):
    def setUp(self) -> Any:
        return super().setUp()

    def test_fake_method(self) -> Any:
        2 + 2
```

## Logs

```
not sure here
```

**Comment by rchiodo** [comment]
Sorry but I'm not sure what you mean by inference. I get no such error. 

This is what I see:

![Image](https://github.com/user-attachments/assets/c67f38f7-3f1d-42e7-b7d5-985193fe47c8)

Perhaps you have some other setting that's changing the result. Can you include your full settings (either settings.json or pyrightconfig.json).

**Comment by rchiodo** [comment]
Oh, you must have this set:

```
    "python.analysis.typeEvaluation.analyzeUnannotatedFunctions": false,
```

That's what this setting does. Turns off analysis of unannotated functions. So, we can't tell what they return and it just default to Unknown.

If you want them to be analyzed, you have to set that to true.

**Comment by JonathanLoscalzo** [comment]
- It was disabled
- I don't have pyrightconfig.json
- settings.json
```json
 {
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "dbt.queryLimit": 500,
    "python.testing.autoTestDiscoverOnSaveEnabled": true,
    "autoDocstring.docstringFormat": "google-notypes",
    "[python]": {
        "diffEditor.ignoreTrimWhitespace": false,
        "editor.defaultFormatter": "ms-python.black-formatter"
    },
    "editor.formatOnSave": true,
    "black-formatter.path": [
        ".venv/bin/black"
    ],
    "python.testing.pytestArgs": [
        "ops/tests/unit_tests",
        "ops/auto_triage/tests",
    ],
    "python.analysis.diagnosticMode": "openFilesOnly",
    "python.analysis.typeEvaluation.analyzeUnannotatedFunctions": false
}
```

![Image](https://github.com/user-attachments/assets/dc904258-e31e-401e-9b33-aaf717542b82)
