### ISSUE TITLE
No autocomplete for pybullet

### ISSUE THREAD

**Issue by rubendsa** [microsoft/pylance-release#663]
## Environment data

Pylance language server 2020.11.2 (pyright 750a296b)
OSX 10.13.6
pyenv Python 3.7.3
Pybullet is installed with `pip install pybullet==3.0.7`

## Expected behaviour

Expected behavior autocompletes available functions (identical to this: https://github.com/microsoft/python-language-server/issues/482). Importing pybullet in an ipython instance autocompletes just as expected:

![image](https://user-images.githubusercontent.com/48568081/100687966-24961c00-3336-11eb-9a72-451a9bb0d8e6.png)

## Actual behaviour

Autocomplete works for other libraries (ex: numpy), but not pybullet. 
![image](https://user-images.githubusercontent.com/48568081/100687893-fdd7e580-3335-11eb-92bd-a91811e0a369.png)

Autocomplete working with numpy:
![image](https://user-images.githubusercontent.com/48568081/100688332-f6fda280-3336-11eb-9910-9f6d4906869d.png)

## Logs

![image](https://user-images.githubusercontent.com/48568081/100688247-c0278c80-3336-11eb-9570-5bef2da2c116.png)

**Comment by judej** [comment]
@rubendsa, thanks for the report. The reason you don't see the completions is because pybullet is a compiled module without type stubs. Pylance cannot analyze compiled modules and cannot give you completions if there are no type stubs. My recommendation is to request the library authors to create type stubs for pybullet. thanks!

**Comment by rubendsa** [comment]
Thanks @judej ! Digging a bit deeper, how is it that pycharm is able to analyze pybullet despite the lack of type stubs? Below is an example screenshot.
![image](https://user-images.githubusercontent.com/48568081/102518824-9d8bb800-4046-11eb-956d-072bb25b88be.png)

**Comment by rubendsa** [comment]
Looks like maybe pycharm is auto generating stubs based on method doc strings? 
![image](https://user-images.githubusercontent.com/48568081/102520389-83eb7000-4048-11eb-8f97-4e06829a648b.png)

**Comment by jakebailey** [comment]
Some analyzers will execute modules to examine their contents; this isn't something we currently do, hence the difference.

**Comment by rubendsa** [comment]
I see, thanks @jakebailey !

**Comment by rohit-kumar-j** [comment]
@rubendsa , you can add the pycharm generated stub file ([extracted_here](https://github.com/rohit-kumar-j/temporary_pybullet_stub_file)) in top-level directory for vs code as a work around. [Also See: bullet#3193](https://github.com/bulletphysics/bullet3/discussions/3913)
