### ISSUE TITLE
docstring altered by decorator is now fully displayed

### ISSUE THREAD

**Issue by copdips** [microsoft/pylance-release#6653]
Hello,

When working with Pyspark module, there're many functions with `@since(version_number)` decorator, which will just append the `version_number` to the wrapped function' docstring.

When using repl's   `help(func)` or `func.__doc__`, it displays well the altered docstring, but in VSCode, when hovering over the function name, it only show the orignal one.

The pyspark.since decorater is deinfed [here](https://github.com/apache/spark/blob/5d757993f4cfcd859eb11640d210a560d6136465/python/pyspark/__init__.py#L81-L97):

```python
def since(version: Union[str, float]) -> Callable[[_F], _F]:
    """
    A decorator that annotates a function to append the version of Spark the function was added.
    """
    import re

    indent_p = re.compile(r"\n( +)")

    def deco(f: _F) -> _F:
        assert f.__doc__ is not None

        indents = indent_p.findall(f.__doc__)
        indent = " " * (min(len(m) for m in indents) if indents else 0)
        f.__doc__ = f.__doc__.rstrip() + "\n\n%s.. versionadded:: %s" % (indent, version)
        return f

    return deco
```

And is used [here](https://github.com/apache/spark/blob/5d757993f4cfcd859eb11640d210a560d6136465/python/pyspark/ml/base.py#L355-L359) for example:

```python
# file pyspark/ml/base.py

class Predictor:
    ...
    @since("3.0.0")
    def setLabelCol(self: P, value: str) -> P:
        """
        Sets the value of :py:attr:`labelCol`.
        """
        return self._set(labelCol=value)
```

In REPL, it displays well the added `versionadded:: 3.0.0`:

```python
In [1]: from pyspark.ml.base import Predictor

In [2]: Predictor.setLabelCol.__doc__
Out[2]: '\n        Sets the value of :py:attr:`labelCol`.\n\n        .. versionadded:: 3.0.0'
```

But in VSCode, the version number is not displayed:

![Image](https://github.com/user-attachments/assets/059e4cdc-3723-4019-996e-e2c599c041ce)

**Comment by rchiodo** [comment]
Thanks for the issue but this isn't possible in Pylance. Pylance is a [static](https://typing.readthedocs.io/en/latest/index.html) typechecker. It doesn't run the code in the `since` decorator, so it can't tell that the docstring has been modified dynamically. There's no way to tell that every function decorator with since has extra information in the doc string.
