### ISSUE TITLE
Fallback to system python if virtualenv absolute path contains `cache`

### ISSUE THREAD

**Issue by fecet** [microsoft/pylance-release#6663]
## Environment data

-   Pylance version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Code Snippet

```python
XXX
```

## Repro Steps

1. using conda/mamba create a environemnt on `$HOME/.cache/envs/env`

## Expected behavior

Pylance use the environment `$HOME/.cache/envs/env`

## Actual behavior

Pylance use the system python

## Logs

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue. See this for more information:

https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment

You likely need to select your environment inside of VS code.
