### ISSUE TITLE
Unable to detect lazy loaded module attributes (PEP-562)

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/pylance-release#6670]
When using `__getattr__` at module level in order to perform lazy initializations of some attributes, pylance false reports these as not being able to import. At the same time, mypy does not seem to have any problem with this.

It should be noted that use of `__getattr__` at module level is documented and approved via https://peps.python.org/pep-0562/ and working since python 3.7

## Environment data

-   Pylance version: v2024.11.100 (pre-release)
-   OS and version: MacOS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12

## Code Snippet

To reproduce the issue, one needs to attempt to `import foo from some_module`, with that module having a code similar to:

```python
#  some_module.py
from typing import Any


def __getattr__(name: str) -> Any:
    match name:
        case "foo":
            return 123
    msg = f"module {__name__!r} has no attribute {name!r}"
    raise AttributeError(msg)


__all__ = ("foo",)
```

## Repro Steps

1. XXX

Perform the import succesfully.

XXX

![](https://sbarnea.com/ss/Screen-Shot-2024-11-15-12-21-42.12.png)

XXX

## Logs

```
XXX
```

**Comment by rchiodo** [comment]
Thanks for the issue but this isn't a supported pattern for a [static type checker](https://typing.readthedocs.io/en/latest/). I presume in your real code you're doing something like this:

```python
import importlib

def __getattr__(name):
    if name == "output"
        return importlib.import_module(".somepath.output")
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
```

The workaround for this situation is to have a type stub as described in this issue:
https://github.com/microsoft/pyright/issues/3989
