### ISSUE TITLE
Annotations with Classes Decorated by Class Decorators Without Parentheses Do Not Hint the Actual Class

### ISSUE THREAD

**Issue by mantasu** [microsoft/pylance-release#6679]
## Environment data

-   Pylance version: `v2024.11.2`
-   OS and version: `WSL2 Ubuntu 22.04.4 LTS`
-   Python version (& distribution if applicable, e.g. Anaconda): `3.12.7`

## Code Snippet

Consider the following snippet:

```python
class decorator[T]:
    def __init__(self, cls: type[T]):
        self.cls = cls

    def __call__(self) -> T:
        return self.cls


@decorator
class MyClass: ...
```

Correct behavior:
```python
a = MyClass()
a # shows "(variable) a: MyClass" when hovered
```

Incorrect behavior 1:
```python
a = None # can be any other type and anywhere else
a: MyClass
a # shows "(variable) a: Any" when hovered
```

Incorrect behavior 2:
```python
def f(a: MyClass):
    a # shows "(parameter) a: Any" when hovered
```

## Example

![Image](https://github.com/user-attachments/assets/0be63952-01d9-4144-8f82-acd72587dc5a)

**Comment by erictraut** [comment]
Pyright (the type checker upon which pylance is built) is working as intended here.

When you apply this class decorator to the undecorated `MyClass`, the resulting `MyClass` symbol is assigned an object of type `decorator[MyClass]`. This symbol is invalid for a type annotation, as per the [Python typing spec](https://typing.readthedocs.io/en/latest/spec/annotations.html). That means the statement `a: MyClass` results in a type checking error. You can see this if you set `typeCheckingMode` to "basic" or "standard".

If you would like to provide more details about your use case, I may be able to help suggest ways to modify your code such that it works within the bounds of the Python typing spec.

**Comment by mantasu** [comment]
Thank you for helping me out!

I'm still not sure why `a = MyClass()` executes correctly but `a: MyClass` does not. I'd try assigning a return type to `__new__` but that does not seem to be taken into account.

As for my use case, it's a bit involved but I need a way to make the type-checker show the correct class imposed by the annotation. I can only modify the decorator and the decorator must be a class decorator and used without parentheses (the case with parentheses works just fine but I need to account for both so this is just a sub-problem). If there is any way to do that, please let me know!

**Comment by erictraut** [comment]
This isn't a question of what "executes correctly". This is a question of whether you're using a type annotation expression that a static type checker will accept. Keep in mind that static type analysis tools like pyright and mypy do not "execute" your code. They analyze the types based on static information provided to them. This static information is in the form of type annotations, which must follow certain rules as spelled out in the Python type specification. One of those rules is that a type annotation must refer to a class, not an instance of a class. For example, `a: list[int]` and `b: int` are legal type annotations, but `a: [0]` and `b: 0` are not. In your case, you're attempting to use an instance of a `decorator` class in a type annotation expression.

Here's an approach that might help address your use case:

```python
from typing import Callable, overload

class decorator[T]:
    @overload
    def __new__(cls) -> Callable[[type[T]], type[T]]: ...

    @overload
    def __new__(cls, _cls: type[T]) -> type[T]: ...

    def __new__(cls, _cls: type[T] | None = None) -> Callable[[type[T]], type[T]] | type[T]:
        if _cls is not None:
            return _cls
        return lambda x: x

@decorator
class MyClass: ...

def func(a: MyClass):
    a.
```

**Comment by mantasu** [comment]
Thanks for the explanation - that clarifies things a lot! I didn't realize annotations for `__new__` methods are taken into account, thank you for providing this solution, it works perfectly.

Perhaps just another question on whether `Self` could indicate the bounding based on the decorated class symbol, rather than standalone? For example, based on [PEP-0673](https://peps.python.org/pep-0673/#use-in-method-signatures), given this setup:

```python
SelfMyClass = TypeVar("SelfMyClass", bound="MyClass")

class CojointClass:
    def method(self): pass

def cojoin[T: type](cls: T) -> T | type[CojointClass]: ...
```

the following two snippets should be equivalent:

```python
@cojoin
class MyClass:
    def __init__(self: SelfMyClass):
        self.method
```

```python
@cojoin
class MyClass:
    def __init__(self: Self):
        self.method
```

However, the type-checker does not indicate the possible availability of `.method` attribute in the second case:

| Case 1 | Case 2 |
| ------ | ------- |
| ![Image](https://github.com/user-attachments/assets/d270b71d-17da-44f1-8b83-f91a10a5040b) | ![Image](https://github.com/user-attachments/assets/69af04dc-f8e6-4f44-af5c-c5ab32b2829c) |

**Comment by erictraut** [comment]
> the following two snippets should be equivalent:

No, these are not equivalent. When you use a `Self`, it has an upper bound of the pre-decorated `MyClass` whereas `SelfMyClass` has an upper bound of the post-decorated `MyClass`. The pre-decorated `MyClass` does not have a method named `method`.

**Comment by mantasu** [comment]
I see yeah, `Self` bounds only to the actual class in which it appears. That resolves all my issues, thanks again for your help!
