### ISSUE TITLE
Intellisense should offer super()-calls when overwriting inherited methods

### ISSUE THREAD

**Issue by hmeine** [microsoft/pylance-release#668]
In a subclass, I can type "def so" and get an autocompletion popup offering "def some_method" with the complete signature from a parent class I inherit from. I would like these stubs to contain a super call (e.g., `super(SubClass, self).some_method(argument1, argument2)`.

If the method should better be empty by design (not knowing whether a super call makes sense), it would be nice to be able to type "super" and get the full super call offered as IntelliSense completion.

**Comment by jakebailey** [comment]
This will be fixed in the next Pylance release (though not the old form, as we don't support Python 2).

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.12.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020120-2-december-2020

**Comment by Diogo-Rossi** [comment]
This is a good feature, but can this remains as an option?
Sometimes we may don't add the `super` call (when implementing interfaces/abstract classes, for instance)
