### ISSUE TITLE
Show return types on function hover?

### ISSUE THREAD

**Issue by TylerYep** [microsoft/pylance-release#669]
In my type-annotated Python code, hovering over a function name shows the function definition and parameter types, but does not give the return type. Can the return type of the function be added to this window as well?

Thanks!

<img width="574" alt="Screen Shot 2020-10-19 at 3 47 07 PM" src="https://user-images.githubusercontent.com/18021435/96519669-5b025680-1222-11eb-9f12-826ed8fef3a1.png">

**Comment by jakebailey** [comment]
This is transferred, but I know we show return types in Pylance if you'd like to recheck.

**Comment by TylerYep** [comment]
Will Pylance eventually become the default Python language server in VS Code?

**Comment by jakebailey** [comment]
We're still in preview at the moment, working things through, so I can't really put a date on that.

Does the return type show as you'd like it to with Pylance? (Checking in case I can close this issue 🙂 )

**Comment by TylerYep** [comment]
Yep, it works great. Thanks!
