### ISSUE TITLE
Intellisense suggestions cannot ignore case issues

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#67]
# 1
The same function, if I start with a capital letter I can't get intelisense suggestion.
I think is good to  add a ferature like pycharm about code completion :
![image](https://user-images.githubusercontent.com/33288114/86769271-79807f80-c081-11ea-80b5-5988c2ce25f6.png)

# 2
Please add support for pyqt5 module, I can't get intelisense  suggestions.

**Comment by savannahostrowski** [comment]
Hey @CatNofishing 

Thanks for the suggestion. We are currently investigating this request and will update with details soon.

**Comment by CatNofishing** [comment]
@savannahostrowski   Thank you for your reply 😁

**Comment by CatNofishing** [comment]
This issue stiil exist

**Comment by jakebailey** [comment]
Unless I'm mistaken, this has been working since 2020.12.0, which introduced fuzzy matching for completion items.
