### ISSUE TITLE
Searching for a class in libraries

### ISSUE THREAD

**Issue by ibobak** [microsoft/pylance-release#6701]
Type: <b>Feature Request</b>

# Behaviour

In my config file of the project I have this:
```
"python.autoComplete.extraPaths": [
        "./venv/lib/python3.10/site-packages"
    ],
```
However, searching for a class in libraries doesn't work.

This is PyCharm:
![Image](https://github.com/user-attachments/assets/8e0d86b3-3b2d-49aa-949d-7df13056bfd3)

And this is VS Code.  It would be a killer feature if you could make it:
![Image](https://github.com/user-attachments/assets/c0cc296f-21ed-4db7-ada5-055492a44119)
![Image](https://github.com/user-attachments/assets/3cd0f3f6-d9de-441d-b03c-882d90007316)

## Steps to reproduce:

1. Install a library, e.g. pytorch_lightning
2. Press Ctrl+N  (search for symbol) and try to find a class in this library, e.g. #LearningRateMonitor

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.20.0
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 6.8.0-49-generic
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>
<summary>User Settings</summary>
<p>

```

condaPath: "<placeholder>"

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|Austin VS Code|p403n1x87.austin-vscode|0.17.3|
|autoDocstring - Python Docstring Generator|njpwerner.autodocstring|0.6.1|
|Ayu Monokai|lakshits11.ayu-monokai|0.0.3|
|Black Formatter|ms-python.black-formatter|2024.4.0|
|C/C++|ms-vscode.cpptools|1.22.11|
|Codeium: AI Coding Autocomplete and Chat for Python, Javascript, Typescript, Java, Go, and more|Codeium.codeium|1.24.8|
|CPython Extension Pack|franneck94.vscode-cpython-extension-pack|0.1.0|
|Cython|tcwalther.cython|0.1.0|
|Data Wrangler|ms-toolsai.datawrangler|1.12.1|
|Databricks|databricks.databricks|2.4.8|
|Databricks Driver for SQLTools|databricks.sqltools-databricks-driver|0.4.2|
|Dev Containers|ms-vscode-remote.remote-containers|0.388.0|
|Django|batisteo.vscode-django|1.15.0|
|Docker|ms-azuretools.vscode-docker|1.29.3|
|Git Extension Pack|donjayamanne.git-extension-pack|0.1.3|
|Git History|donjayamanne.githistory|0.6.20|
|gitignore|codezombiech.gitignore|0.9.0|
|GitLens — Git supercharged|eamodio.gitlens|16.0.2|
|Grey Light+ Pro|elanzalaco.grey-light-plus-pro|0.0.1|
|Inline SQL|qufiwefefwoyn.inline-sql-syntax|2.16.0|
|IntelliCode|VisualStudioExptTeam.vscodeintellicode|1.3.2|
|IntelliCode API Usage Examples|VisualStudioExptTeam.intellicode-api-usage-examples|0.2.9|
|JavaScript Debugger|ms-vscode.js-debug|1.95.3|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.3|
|Jinja|wholroyd.jinja|0.0.8|
|Jupyter|ms-toolsai.jupyter|2024.10.0|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.21|
|Jupyter PowerToys|ms-toolsai.vscode-jupyter-powertoys|0.1.1|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Language-Cython|guyskk.language-cython|0.0.8|
|Monokai Pro|monokai.theme-monokai-pro-vscode|2.0.2|
|Open in GitHub, Bitbucket, Gitlab, VisualStudio.com !|ziyasal.vscode-open-in-github|1.3.6|
|Project Manager|alefragnani.project-manager|12.8.0|
|Pylance|ms-python.vscode-pylance|2024.11.2|
|Pylint|ms-python.pylint|2024.0.0|
|Python|ms-python.python|2024.20.0|
|Python C++ Debugger|benjamin-simmonds.pythoncpp-debug|0.3.0|
|Python Debugger|ms-python.debugpy|2024.12.0|
|Python Environment Manager|donjayamanne.python-environment-manager|1.2.4|
|Python Extension Pack|donjayamanne.python-extension-pack|1.7.0|
|Python Indent|KevinRose.vsc-python-indent|1.18.0|
|Remote - SSH|ms-vscode-remote.remote-ssh|0.115.1|
|Remote - SSH: Editing Configuration Files|ms-vscode-remote.remote-ssh-edit|0.87.0|
|Remote Explorer|ms-vscode.remote-explorer|0.4.3|
|Ruff|charliermarsh.ruff|2024.54.0|
|SQLTools|mtxr.sqltools|0.28.3|
|Studio Icons|jtlowe.vscode-icon-theme|1.6.6|
|SVG|jock.svg|1.5.4|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.10|
|Tensorboard|ms-toolsai.tensorboard|2023.10.1002992421|
|YAML|redhat.vscode-yaml|1.15.0|
|Zoomer|anthonyattard.zoomer|0.3.1|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 155H (22 x 1993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 3, 3|
|Memory (System)|62.32GB (42.39GB free)|
|Process Argv|--crash-reporter-id dbc99d2c-fa75-4b80-8e72-7c457ce4fdf5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by StellaHuang95** [comment]
Thanks for reaching out. There's a similar discussion about searching function definitions across third-party libraries as an enhancement request. Please upvote https://github.com/microsoft/pylance-release/discussions/3187 if you'd like to see it being supported. We prioritize tasks based on various factors, including upvote counts, so your feedback helps us better understand user needs. Thank you for your understanding!
