### ISSUE TITLE
Generated docstrings return type could be narrowed

### ISSUE THREAD

**Issue by KacieKK** [microsoft/pylance-release#6704]
![Image](https://github.com/user-attachments/assets/8ad3b457-0bed-4876-b9f6-4760b2a9e25e)

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.12.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202412100-16-December-2024-PreRelease)
