### ISSUE TITLE
Autocomplete paths in strings in editor

### ISSUE THREAD

**Issue by randallpittman** [microsoft/pylance-release#671]
It would be super handy when writing scripts to offer autocompletion of paths in strings, like IPython does.

E.g. typing:

`file_path = "/data/NewYork_` <kbd>Tab</kbd> (or <kbd>Ctrl</kbd>+<kbd>Space</kbd> or whatever)

...would offer autocompletions of paths starting with `/data/NewYork_`

**Comment by judej** [comment]
Thanks again for the issue. This enhancement request has been open for a while. Closing old issue because of lack of upvotes.
