### ISSUE TITLE
aiohttp.web.run_app partially unknown

### ISSUE THREAD

**Issue by AlanBogarin** [microsoft/pylance-release#6730]
I have been using Pylance for a long time in VSCode. I almost never had problems in the static analysis method, but now I found one, I'm not sure if it was due to some configuration change or some other reason
I deleted all the extensions, leaving only the basics for Python, but it still didn't solve the problem

Here, Pylance does not recognize SSLContext and marks it as Unknown, and when I use the function, it shows me `reportUnknownMemberType`

![Image](https://github.com/user-attachments/assets/988427cb-3e22-4d10-b496-edabb7ee3b06)

OS: windows 11
Pylance: v2024.11.3
VSCode: 1.95.3 (user setup)
Python: 3.13.0
Aiohttp: 3.11.9

**Comment by erictraut** [comment]
I presume that you've enabled strict type checking. By default, the `reportUnknownMemberType` is not enabled by default. Are you sure you want to enable this? Strict-mode checks like this require that all of your imported libraries have complete and accurate types — a difficult requirement to meet. If you didn't intend to enable "strict" type checking mode, I recommend switching the `typeCheckingMode` back to "standard" or "basic".

If you think you have found a static analysis bug, please provide a minimal, self-contained code sample that demonstrates the issue. Debugging static analysis problems from partial code screenshots isn't really possible.

**Comment by AlanBogarin** [comment]
```python
from aiohttp.web import Application, run_app  # <-- reportUnknownVariableType

app =  Application()

run_app(app)
```
I have no idea what to show you, since this is not a syntax problem, nor is it a problem with aiohttp since its type annotations are very good

![Image](https://github.com/user-attachments/assets/75f29f3e-bc4b-41c3-adc0-3d35fcae1236)

Regarding strict mode, it's fine, I've been using it for a long time, I'm already very familiar with annotations, type checks, typing, _typesheed, and others.

I consider that this error that it shows is a false positive, because
1. The aiohttp annotations are correct
`aiohttp.web.py`
    ```python
    290 | try:
    291 |     from ssl import SSLContext
    292 | except ImportError:  # pragma: no cover
    293 |     SSLContext = Any  # type: ignore[misc,assignment]
    ...
    463 | def run_app(
    ...
    472 |     ssl_context: Optional[SSLContext] = None,
    ...
    483 | ) -> None:
    ```
2. I don't use stubs distributions with this package
![Image](https://github.com/user-attachments/assets/84476199-a131-4f5f-86ef-deb09907bc71)

but I wouldn't know what causes it

**Comment by erictraut** [comment]
The code in the `aiohttp` library is defining the symbol `SSLContext` in two conflicting ways. First, it's importing the symbol from another library (`ssl`). Second, it's assigning it the value `Any`. It appears that the authors are attempting to define a type alias in the `except` block, but type aliases cannot have more than one assignment and cannot be conditionally assigned. A static type checker cannot determine which of these two code paths are taken at runtime. The `SSLContext` is therefore treated as a variable. The Python typing spec indicates that variables cannot be used in type expressions. If pyright detects a variable within a type expression, it is treated as `Unknown`.

So pyright is working as intended here, and I don't consider this a false positive.

The authors of the `aiohttp` can fix this by making the definition of `SSLContext` unambiguous for static type checkers. For example, they can do this through the use of a `TYPE_CHECKING` conditional:

```python
if TYPE_CHECKING:
    # Static behavior assumes ssl is present
    from ssl import SSLContext
else:
    # Dynamic behavior depends on whether ssl is present
    try:
        from ssl import SSLContext
    except ImportError:  # pragma: no cover
        SSLContext = Any  # type: ignore[misc,assignment]
```

Alternatively, they could replace the `SSLContext = Any` statement with `pass` and then use a quoted type annotation form for `SSLContext` so the annotation expression isn't evaluated at runtime.

**Comment by AlanBogarin** [comment]
If you put it that way, I think a pull is needed for aiohttp. Thank you so much
