### ISSUE TITLE
get_pytest_options.py leaving git processes around

### ISSUE THREAD

**Issue by camillol** [microsoft/pylance-release#6749]
Type: <b>Bug</b>

# Behaviour

Pylance seems to spawn git processes that stay around even after quitting VSCode. They seem to hold the git lock in my repo for a while, resulting in `git status` appearing stuck.

## Steps to reproduce:

1. I opened the structlog repo and was making some changes. Only two files were open in this window. I noticed that my git seemed stuck, and I looked at the running git processes.

# Diagnostic data

Example of one of these git processes:
camillo          89047   0.0  0.0 34064596   2036   ??  S     9:53PM   0:00.05 /Applications/Xcode.app/Contents/Developer/usr/bin/git describe --dirty --always --long --abbrev=40
Its parent was 83988:
camillo          83988   0.0  0.0 35442332  14116   ??  S     9:52PM   0:11.18 /Users/camillo/.virtualenvs/work/bin/python -I /Users/camillo/.vscode-insiders/extensions/ms-python.vscode-pylance-2024.12.1/dist/bundled/files/get_pytest_options.py

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.20.0
VS Code version: Code - Insiders 1.96.0-insider (3781e5f084838b16d9bb16998cd476f232b2ff5f, 2024-12-05T20:57:43.615Z)
OS version: Darwin arm64 24.1.0
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.8
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnvWrapper
-   Value of the `python.languageServer` setting: Default

<details>
<summary>User Settings</summary>
<p>

```

languageServer: "Pylance"

```
</p>
</details>

<details>
<summary>Installed Extensions</summary>

|Extension Name|Extension Id|Version|
|---|---|---|
|Black Formatter|ms-python.black-formatter|2024.5.13171011|
|Cython VSCode|ktnrg45.vscode-cython|1.0.3|
|Even Better TOML|tamasfe.even-better-toml|0.19.2|
|GitHub Copilot|GitHub.copilot|1.248.0|
|GitHub Copilot Chat|GitHub.copilot-chat|0.23.2024120501|
|GitHub Pull Requests|GitHub.vscode-pull-request-github|0.100.3|
|GitLens — Git supercharged|eamodio.gitlens|16.0.4|
|Go|golang.go|0.42.1|
|isort|ms-python.isort|2023.13.13171013|
|JavaScript Debugger|ms-vscode.js-debug|1.96.0|
|JavaScript Debugger Companion Extension|ms-vscode.js-debug-companion|1.1.3|
|Jupyter|ms-toolsai.jupyter|2024.10.0|
|Jupyter Cell Tags|ms-toolsai.vscode-jupyter-cell-tags|0.1.9|
|Jupyter Keymap|ms-toolsai.jupyter-keymap|1.1.2|
|Jupyter Notebook Renderers|ms-toolsai.jupyter-renderers|1.0.21|
|Jupyter Slide Show|ms-toolsai.vscode-jupyter-slideshow|0.1.6|
|Makefile Tools|ms-vscode.makefile-tools|0.11.13|
|Marp for VS Code|marp-team.marp-vscode|2.8.0|
|Prettier - Code formatter|esbenp.prettier-vscode|11.0.0|
|Pylance|ms-python.vscode-pylance|2024.12.1|
|Python|ms-python.python|2024.20.0|
|Python Debugger|ms-python.debugpy|2024.13.2024112901|
|Python Path|mgesbert.python-path|0.0.14|
|Remote - SSH|ms-vscode-remote.remote-ssh|0.115.1|
|Remote - SSH: Editing Configuration Files|ms-vscode-remote.remote-ssh-edit|0.87.0|
|Remote Explorer|ms-vscode.remote-explorer|0.4.3|
|Ruff|charliermarsh.ruff|2024.56.0|
|Table Visualizer for JavaScript Profiles|ms-vscode.vscode-js-profile-table|1.0.10|
</details>
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|160, 58, 31|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 7b87a5b2-68e7-4d42-ad22-32e3bce2e5e7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrpc:30624061
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
5b1c1929:31184661

```

</details>

**Comment by rchiodo** [comment]
Pylance doesn't spawn git processes (we do spawn a python process though). You must have your extensions folder under a git tree and something is watching the folder.

**Comment by camillol** [comment]
@rchiodo no, it's not under a git tree:

```
➜  ~ [arm][openai] cd /Users/camillo/.vscode-insiders/extensions/ms-python.vscode-pylance-2024.12.1/dist/bundled/files/                     
➜  files [arm][openai] git status
fatal: not a git repository (or any of the parent directories): .git
```

And if something were watching it, the process wouldn't be a child of get_pytest_options.py, right?

I couldn't quickly find `get_pytest_options.py` on GitHub, but my copy is just this:

```
import sys
from _pytest.config import get_config

c = get_config()
c.parse(sys.argv)
print(f"Python classes: {c.getini('python_classes')}")
print(f"Python files: {c.getini('python_files')}")
print(f"Python functions: {c.getini('python_functions')}")
```

Isn't it possible that `get_config` is starting that git process? Perhaps indirectly, e.g. by starting an interactive shell which then uses git to check for the current directory's git status?

**Comment by rchiodo** [comment]
Can you run that code yourself and see if it spawns the other process?
