### ISSUE TITLE
Make pass through settings descriptions to adopt inline code

### ISSUE THREAD

**Issue by mjbvz** [microsoft/pylance-release#6757]
I noticed that a number of the Python setting descriptions could be improved by using markdown inline code instead of plain text. For example `python.analysis.ignore`

![Image](https://github.com/user-attachments/assets/b1385de8-1588-4048-9a6d-fa140ba82183)

The `*`, `**`, `?`, and `${workspaceFolder...}` parts would all be easier to read/understand if we used inline code for them instead of plain text

I noticed this problem in enough setting descriptions that I think it's worth doing a quick pass through all the Python settings during a debt week to make sure all of them are using Markdown when it would improve readability.

In general, inline code should be used for:

- Actual code 
- Setting values, such as enum values for the setting
- File paths/names
- Character values, such as `{` when used in a setting like `python.analysis.autoFormatStrings`
- Keyboard key names 

Other things to adopt as part of this:

- Split up long setting descriptions into a list / multiple lines when it would be useful. `python.analysis.ignore` could benefit from this

 - Make sure that any setting names in descriptions use the setting link syntax to create clickable links. For example ```  `#python.analysis.typeCheckingMode#` ```. This setting name is currently rendered as plain text in `python.analysis.diagnosticSeverityOverrides`

**Comment by rchiodo** [comment]
@mjbvz how do I do this?
> Split up long setting descriptions into a list / multiple lines when it would be useful. python.analysis.ignore could benefit from this

Adding newlines or `</br>` seems to have no effect.

**Comment by rchiodo** [comment]
Oh double newline works. `\n\n`.

**Comment by rchiodo** [comment]
This issue has been fixed in prerelease version 2024.12.100, which we've just released. You can find the changelog here: [CHANGELOG.md](https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202412100-16-December-2024-PreRelease)
