### ISSUE TITLE
VS Code Cannot Detect Variables/Functions in other files.

### ISSUE THREAD

**Issue by lek18** [microsoft/pylance-release#6759]
Type: <b>Feature Request</b>

# Behaviour

Create a file.py with a new variable foo. Add foo to a new python file2.py, vscode cannot locate foo for automatic imports. 
XXX

## Steps to reproduce:

1. Create a file.py with a new variable foo. 
2. Add foo to a new python file2.py, vscode cannot locate (cmd+.) foo for automatic imports. 

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.23.2024121003
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by rchiodo** [comment]
Thanks for the issue but this is by design at the moment. Variables aren't considered public exports so they're not listed in auto-imports.
