### ISSUE TITLE
variables created via %%bigquery aren't recognised by pylance

### ISSUE THREAD

**Issue by myyc** [microsoft/pylance-release#6763]
-   Pylance version: v2024.12.1
-   OS and version: arch linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.2

## Code Snippet

from microsoft/vscode-jupyter#15751 

not sure it's an issue with pylance or the `%%bigquery` magic but variables defined with it are definitely picked up by vscode (see screenshot) but pylance doesn't recognise them.

![Image](https://github.com/user-attachments/assets/c760160f-bde0-46f3-92a7-1039b88fdb90)

**Comment by rchiodo** [comment]
Thanks for the issue but this by design. Pylance is a static analyzer, it can't understand what dynamic code does, so it has no idea what the `%%bigquery` call is doing.

**Comment by rchiodo** [comment]
Here's a similar issue:
https://github.com/microsoft/pylance-release/issues/6031

**Comment by bschnurr** [comment]
I'm not sure what type you expect `bigtest` to be, but something like this might work
```python

from typing import TYPE_CHECKING
from pandas import DataFrame

if TYPE_CHECKING:
    bigtest: DataFrame
else:
    %%bigquery bigtest
```

**Comment by myyc** [comment]
the `%%bigquery` magic saves the cell content into its argument (a dataframe, correct). i would argue that #6031 is a quite different issue as this isn't a dynamic import, it's just a regular variable assignment but using jupyter magics (terrible syntax but not uncommon). pylance does interact with magics already, which is why `%%bigquery` itself (not valid python syntax, loaded via `%load_ext`) doesn't throw an error.
