### ISSUE TITLE
Does not properly display sphix hint, as before

### ISSUE THREAD

**Issue by oiltanker** [microsoft/pylance-release#6772]
<h3> Environment data </h3>

-   Language Server version: 2024.12.1
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda):  3.12.0
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: off

<h3> Code Snippet </h3>

```python
def collect(pkgs: Iterable[str]) -> list[str] | None:
    """Collects PACMAN package dependencies without duplicate providers

    :param Iterable[str] pkgs: package names to be used for collecting
    :return list[str] | None: package names needed to satisfy all dependencies if successful, None otherwise
    """
    pass

def splitDepDef(dep: str) -> tuple[str, str | None, str | None]:
    """Spilt dependency string into definition as (name, op, ver) tuple, if any is defined

    :param str dep: dependency string
    :return tuple[str, str | None, str | None]: split dependency definition (name, op, ver)
    """
    pass

def create(
    define: str | Iterable[str] | Callable[[Target, dict], bool],
    deps: Iterable[str | tuple[str] | Target] | str | Target | None,
    build: Callable[[Target, dict], bool] | None,
    clean: Callable[[Target, dict], bool] | None = None,
    abort: Callable[[Target, dict], bool] | None = None,
    env: dict[str, str] | None = None,
    alias: bool = False
) -> Target:
    """Creates a target from parameters

    :param str | Iterable[str] | Callable[[Target, dict], bool] define: target name/path(s) or function (must set "target" property)
    :param Iterable[str | tuple[str] | Target] | str | Target | None deps: target dependencies
    :param Callable[[Target, dict], bool] | None build: build function
    :param Callable[[Target, dict], bool] | None clean: clean function (default None)
    :param Callable[[Target, dict], bool] | None abort: abort function (default None)
    :param dict[str, str] env: environment variables (default None)
    :param bool alias: designates target as alias, i.e. no physical target (default False)
    :return Target: target created and initialized from parameters
    """
    pass
```

<h3> Repro Steps </h3>

1. Create file structure with complex sphinx tags, e.g. provided in code snippet
2. See itellisence hints

<h3> Expected behavior </h3>

Properly displayed sphinx hind in intellisence

<h3> Actual behavior </h3>

Intellisence displays docstring as simple text

<h3> Logs </h3>

[link](https://mega.nz/file/ncQCCA5Y#JRp_rUjQq__9GVonfff34RWpZnbbeREBkmBADYyA2PE)

**Comment by rchiodo** [comment]
This setting should reenable it:

![Image](https://github.com/user-attachments/assets/0c1e3c19-c801-4eb5-9793-8f3b855b46f2)


I think we likely need to make this default to true.

**Comment by rchiodo** [comment]
@luabud did the experiment for this setting run out? We were still testing it I believe. It seems some people have it set back to disabled with our latest bits.

**Comment by oiltanker** [comment]
sorry for the trouble, i just did all my docstrings to sphinx format and then formatting suddenly disappeared (for me)

**Comment by rchiodo** [comment]
@oiltanker did that setting fix the problem?
