### ISSUE TITLE
Pylance hijacks `editor.formatOnType` logic

### ISSUE THREAD

**Issue by leep-frog** [microsoft/pylance-release#6773]
## Environment data

-   Pylance version:  v2024.12.1 
-   OS and version: Windows 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.2

## Code Snippet (see [this original issue](https://github.com/microsoft/vscode/issues/235948))

See [this example extension](https://github.com/leep-frog/example-ext) which adds a python formatter.  When enabled in isolation, this extensions works totally fine and as expected (formats on each enter press).  However, when the Pylance extension is also enabled, then the `editor.formatOnType` logic no longer works reliably (often works 0-3 times and then no more after that, presumably it stops working after the Pylance extensions is fully activated, but not confirmed that).

See the below video:

https://github.com/user-attachments/assets/3e774cd9-b0da-4a80-95c9-df3614ac5adc

```python
XXX
```

## Repro Steps

1. Run the [example extension](https://github.com/leep-frog/example-ext) debugger.
2. Verify that pressing `Enter` always formats the file (just adds an arbitrary string to the top) when Pylance is disabled.
3. Verify it does not work reliably when Pylance is enabled.

## Expected behavior

Document is formatted with example extension on each enter press

## Actual behavior

Document is formatted only for first 0-3 enter presses (presumably stops once Pylance is fully activated)

**Comment by KacieKK** [comment]
Thanks for reporting, could you try disabling these two settings? 
```
"[python]": {
    "editor.formatOnType": false,
    "editor.autoIndent": "none"
}
```

**Comment by leep-frog** [comment]
Hmm. I was having the issue when running the extension locally, but after publishing it appears to be working fine. I'll close the ticket and reopen if it reappears with the published extension.
