### ISSUE TITLE
Variable is not defined error for f-string debug statement

### ISSUE THREAD

**Issue by squaresmile** [microsoft/pylance-release#686]
## Environment data

-   Language Server version: Pylance v2020.12.0
-   OS and version: Windows 10 20H2 19042.662
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.0

## Expected behaviour

Pylance can see the variable in f-string debug statement.

## Actual behaviour

`<variable_name[:-1]> is not defined` error is raised by Pylance

## Code Snippet / Additional information

```python
test_var = 123
print(f"{test_var=}")
```
Error: `"test_va" is not defined Pylance(reportUndefinedVariable)`

![image](https://user-images.githubusercontent.com/13234442/101118575-5b2e9980-35b7-11eb-8373-f3bdbda7ae77.png)

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release. In the meantime, you can work around the issue by inserting a space before the "=" token in the f-string expression.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.12.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#2020121-9-december-2020
