### ISSUE TITLE
Missing members in shyft.time_series

### ISSUE THREAD

**Issue by kjellaso** [microsoft/pylance-release#687]
## Environment data

-   Language Server version: 2020.12.0
-   OS and version: Ubuntu 19.04
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.9
-   Package: Shyft

## Expected behaviour

Autocomplete functions and variables listed in __all__ variable in a __init__.py file

## Actual behaviour

As in Jedi, list these autocompletions when starting to type. These functions/variables are listed in the shyft.time_series.__init__.py file under __all__ variable

## Code Snippet / Additional information
pip install shyft

Then in a python shell:
import shyft.time_series as sa
sa.UtcP

**Comment by jakebailey** [comment]
I did the above steps, and I see that `UtcP` isn't found, but I'm not seeing where `UtcP` comes from either.

Likely, it's from this line:

```python
from shyft.time_series._time_series import *
```

`_time_series` is compiled code, and we don't execute compiled code to inspect it. Jedi does (but this is not necessarily safe).

This will need a stub.

**Comment by jakebailey** [comment]
I'll also note that `UtcP ` is not in `__all__` either, at least not from what I am reading.

**Comment by judej** [comment]
This will require a stub from the library author.
