### ISSUE TITLE
No documents says "pylance support pyrightconfig.json" completely

### ISSUE THREAD

**Issue by Haibao425** [microsoft/pylance-release#688]
I was a user of pyright, and now I have converted to use pylance, but still keep pyrightconfig.json file, seems pylance supports pyrightconfig.json, you know, "pylance" and "pyright" are different name..... I am confused about this, pylance is to replace pyright, but no document says that pyrightconfig.json is still supported and when the deadline that will not support pyrightconfig.json is......

So I am not sure if I should create pyrightconfig.json file for my new python project.

Anyone who can provide a officially documents to tell me if pyrightconfig.json will be supported in future, or are there any settings in pylance which can replace what pyrightconfig.json can do completely?

**Comment by jakebailey** [comment]
We have no intent to stop supporting pyrightconfig.json; Pylance is built on pyright, which is still an ongoing public project and CLI tool for type checking.

**Comment by judej** [comment]
Closing old issue. If this is still a problem, please reopen with the information requested. thanks
