### ISSUE TITLE
Unreachable path when using SQLA order_by desc/asc

### ISSUE THREAD

**Issue by sachaventura** [microsoft/pylance-release#69]
## Environment data

-   Language Server version: 2020.6.1
-   OS and version: OSX 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.5 64-bit

## Expected behaviour

Any code following SQLAlchemy queries that use `order_by(Foo.bar.desc())` or `order_by(Foo.bar.asc())` should not be be marked with `Code is unreachable` 

## Actual behaviour

Code following SQLAlchemy queries that use `order_by(Foo.bar.desc())` or `order_by(Foo.bar.asc())` is marked with `Code is unreachable` and is greyed out.
I'm suspecting the issue is not confined to just this use case.

## Logs

```
XXX
```

## Code Snippet / Additional information

![Screenshot 2020-07-08 at 10 00 42 am](https://user-images.githubusercontent.com/2261178/86857470-ee939980-c101-11ea-97fd-0f811ed033e9.png)

```python
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session

Base = declarative_base()

class Person(Base):
    __tablename__ = 'person'
    id = Column(Integer, primary_key=True)
    name = Column(String(250), nullable=False)

engine = create_engine('sqlite:///sqlalchemy_example.db')
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
session: Session = DBSession()

p = session.query(Person).get(5)
p2 = session.query(Person).order_by(Person.name).first()
p2 = session.query(Person).order_by(Person.name.asc()).first()
p3 = ... # unreachable
```

**Comment by erictraut** [comment]
I presume that you're not using a type stub for sqlalchemy, so Pylance is attempting to infer types from the library implementation. When Pylance analyzes the `asc` method, it finds the following code:
```
    def asc(self):
        return self.operate(asc_op)
```
It then analyzes the `operate` method, and it finds:
```
    def operate(self, op, *other, **kwargs):
        raise NotImplementedError(str(op))
```
Note that the `operate` method is not annotated with a return type and is not marked as `@abstractmethod` (as it probably should be). So Pylance assumes that this method always raises an exception when called.

The recommended fixes for this problem are:
1. Find or create a type stub for sqlalchemy that defines its public interface so Pylance doesn't need to try to infer the interface from the library implementation.
2. Report a bug (or submit a PR) to sqlalchemy to properly mark these methods as `@abstractmethod` or annotate the method with a proper return type.

**Comment by sachaventura** [comment]
Thanks, Eric.
That was fast 😛
