### ISSUE TITLE
__build_class__ not recognized as builtin

### ISSUE THREAD

**Issue by tweakimp** [microsoft/pylance-release#693]
## Environment data

-   Language Server version: v2020.12.0
-   OS and version: Windows 10 64bit
-   Python version: 3.8.2

## Expected behaviour

`__build_class__` is recognized as a builtin.

## Actual behaviour

`__build_class__` is marked as `"__build_class__" is not defined Pylance (reportUndefinedVariable)`

## Code Snippet / Additional information

```python
print(__build_class__)
```

**Comment by erictraut** [comment]
The `__build_class__` symbol doesn't appear in the `builtins.pyi` type stub file that pylance consumes from the [typeshed repo](https://github.com/python/typeshed). If you think that this is an error, please file a bug or a PR in typeshed. 

I don't see references to `__build_class__` in any PEPs or the main Python documentation. It appears that it's a semi-documented symbol that never became fully public or official. The most authoritative reference I could find was [this post from Guido](https://mail.python.org/pipermail/python-3000/2007-March/006338.html).

@gvanrossum could probably shed more light on it.

**Comment by gvanrossum** [comment]
It's internal to the CPython implementation, and not intended to ever be used by user code. I'm sorry if you have to deal with user code that uses this -- it's not valid, and depending on this symbol is covered by the general blanket condition in the language reference that all undocumented dunder names are reserved for the implementation.

**Comment by tweakimp** [comment]
It is not actually used in user code, I just played around with all the builtins.

@gvanrossum Thank you for your work on Python. It saved my life.
