### ISSUE TITLE
Python 2.7 syntax not recognised

### ISSUE THREAD

**Issue by schlamar** [microsoft/pylance-release#7]
## Environment data

- Language Server version:  Pylance language server 2020.6.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7.17

## Expected behaviour

Python 2.7 syntax (e.g. `except Exception, e:`) is not marked as error if Python 2.7 interpreter is configured.

## Actual behaviour

Python 2.7 syntax is marked as errors.

## Code Snippet / Additional information

```python
        try:
            raise ValueError
        except Exception, e:
            print e
```

**Comment by erictraut** [comment]
Pylance does not support Python 2 by design. The JEDI language server is available, and it supports Python 2.x.

**Comment by schlamar** [comment]
So I would expect that this is documented.

**Comment by gramster** [comment]
Agreed; we should make it clear in Marketplace description.

**Comment by SteveGoodenough** [comment]
I would expect that from Jan 1st 2020 the reverse should be true. Only specifically mention Python 2 when it *is* supported.

**Comment by savannahostrowski** [comment]
Documentation was added to our README to indicate that Pylance supports Python 3 codebases.
