### ISSUE TITLE
[Q] Limit scope of type analysis to project files?

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#702]
I've noticed that Pylance/Pyright already ignores \*.pyi stubs and only do semantic colorization for them. I was wondering if there was a centralized way to limit this kind of type analysis only to the current project/workspace files. Case in point: I'm using these stubs
https://github.com/nutti/fake-bpy-module
which, due to their low quality, aree provided as source-files (\*.py) with no type annotations, just for autocompletion. Now, every time I navigate to the target site to get a bit more info Pylance tries to analyze it as well, which results in a very slow performance. It may take it minutes and generate up to few thousands warnings. It seems utterly pointless to waste CPU cycles on it and honestly, on anything outside of the project files.
One way I could tackle it is to use keyword comments  to try and disable disable analysis:, something like
> \# pyright: off

The issue is that I already have `generalTypeChecking` disabled due to unreliable results. And I also have defined custom severity states to the rest of the directives, which means even if I have `generalTypeChecking` disabled at the top of the file, it will still check for other cases like argument and parameters types, unused or unbound variables. 

Technically, I could solve this by writing a script that iterates over every possible py-file there and appends at the top every possible diagnostics directive to false, but I think you can see how exceptionally bad this solution is.

Is there currently some way to limit actual, direct type analysis and hinting/error report only to **opened project files**?

**Comment by Kein** [comment]
I don't know why it labeled it as triage, I made sure I chose a "question" type of an issue.

**Comment by judej** [comment]
@kein, you should look at the Pyright config docs https://github.com/microsoft/pyright/blob/master/docs/configuration.md#main-pyright-config-options. And look at the `ignore` setting. 

Please let me know if this fixes the problem.

**Comment by jakebailey** [comment]
> Is there currently some way to limit actual, direct type analysis and hinting/error report only to opened project files?

Note that this is already what we do, we only analyze files that have been opened. When you jump to that file, it's opened, and is analyzed. Closing it hides the diagnostics again.

Analyzing referenced files is unavoidable; analysis is lazy and will load files as needed. Opening a file just finishes off the analysis and reveals the diagnostics.

**Comment by Kein** [comment]
> Analyzing referenced files is unavoidable; analysis is lazy and will load files as needed. Opening a file just finishes off the analysis and reveals the diagnostics.

Yes but it is either synchronous or somewhat sequential, i.e. if I open MASSIVE file with few k lines the server will starts analyzing it, displaying "3 files to analyze". Obviously, I'm not gonna wait, so once I get info I need, I switch back to my working document, do changes, save, and... we are stuck. Until it finished chugging through that big file I opened for like 5 seconds - it wont process the current I'm working on as well.
I understand that eventually, as time goes, it will be improved but excepting it to process massive scr or type file in a blink of an eye is very unlikely.

>Please let me know if this fixes the problem.
Sadly no, after trying a few times I could not find a working combination that would "exclude all but working project"

**Comment by jakebailey** [comment]
The nature of the analysis is that it is sequential, yes. We'd always like to improve the performance, but we largely need concrete projects to test to find potential blowups in the current code.

A few thousand lines is not that large, I really wouldn't expect it to chug.

**Comment by erictraut** [comment]
If you have an example of where it takes >50 milliseconds to fully analyze a source file, we'd like to look at it. Is there a particular file within a particular package that you could recommend we look at?

**Comment by Kein** [comment]
> If you have an example of where it takes >50 milliseconds to fully analyze a source file, we'd like to look at it. Is there a particular file within a particular package that you could recommend we look at?
https://github.com/nutti/fake-bpy-module

If you guys could adjust pyright config logic or add an option (to avoid breaking old logic) so you can ovlap `ignore[*]` with `include[./*]` i.e. it ignores everything but ANYTHING as deep as it goes in current project directory is processed - that'd be sweet.

**Comment by erictraut** [comment]
We'd rather understand and fix the underlying problem rather than adding configuration options to mask it.

**Comment by Kein** [comment]
But my problem isn't exactly the fact that Pylance is slow on big files, but rather the fact I cant limit scope or full diagnostics and warnings/errors output only to the project, which I think still would be useful function overall.

**Comment by max-sixty** [comment]
Could pylance pass the VSCode settings through to pyright?

ref https://github.com/microsoft/pyright/issues/1334#issuecomment-753398432

**Comment by erictraut** [comment]
We've considered creating new VS Code settings in the "python.analysis.xxx" namespace that mirror the "include" and "exclude" configuration settings from the pyrightconfig.json file, but since this is a pretty esoteric and advanced feature, we've been reluctant to expose settings for all VS Code users. If you have the need to exclude portions of your workspace, you can use the pyrightconfig.json configuration file, which is honored by pylance since it's built on top of pyright. Please refer to the pyright documentation for details about the [pyrightconfig.json file](https://github.com/microsoft/pyright/blob/master/docs/configuration.md).

**Comment by max-sixty** [comment]
> We've considered creating new VS Code settings in the "python.analysis.xxx" namespace that mirror the "include" and "exclude" configuration settings from the pyrightconfig.json file, but since this is a pretty esoteric and advanced feature, we've been reluctant to expose settings for all VS Code users

Right — hence the suggestion to inherit the  `files.exclude` setting in VSCode by default — rather than requiring a new pylance-specific setting...

**Comment by erictraut** [comment]
I don't think we'd want to conflate `files.exclude` (which is an editor setting) with the exclusion settings for pylance/pyright. Those have different meanings, so conflating the two would be problematic. Plus, there's strong precedent for keeping them separate: the TypeScript compiler and language server have their own exclusion configuration mechanism and do not honor the `files.exclude` editor setting.

**Comment by max-sixty** [comment]
IIUC the Typescript language server uses `tsconfig.json`, which is a language config file. The corollary of that  — using python / setuptools tooling — would also be great, though not sure if there's an easy way to implement it. Hence the suggestion to use files tracked by version control (which is what `setuptools_scm` does).

My main point is that a _language server specific_ config file is going to be difficult to discover. e.g. I only found that there was a problem after turning on pylance & pyright logging levels, and there's already plenty of information available that the 2000 files in `.asv` don't need to be tracked, either from the vscode settings, or setuptools, or git.

Thanks, happy new year!

**Comment by jakebailey** [comment]
Going back to the original issue, it seems a bit like what's actually wanted here is to not look at libraries for types at all; is there any reason to not disable `useLibraryCodeForTypes` and then convert the fake module to `pyi` files? Then no other could would be analyzed except what is typed (fast).

On the whole, generating diagnostics is not the bottleneck and restricting it would only be visual. We have to analyze the code, do so lazily (analyze the bare minimum of what is needed to answer a given question), except in the workspace itself where we are looking at semantic tokens, generating diagnostics for every node, etc. If that is slow, we'd need an example so we can go and try and optimize things.

`files.exclude` is definitely not the right thing.

**Comment by Kein** [comment]
> Going back to the original issue, it seems a bit like what's actually wanted here is to not look at libraries for types at all

No, the type information is needed, otherwise what the point? What's not needed is to avoid processing and applying any supplementary functional to the documents OUTSIDE of the project: no semantic coloring, no linting and type checking INSIDE the external document. For example, if I have custom type stubs and I use in-place navigation to the source Pylance provides and VS opens for me that stud/source document - it should not be processes as a valid projet document for all active aforementioned functional. But it STILL should be processes in the background for type info because otherwise I wont have that type info in the active and actual PROJECT document.

**Comment by erictraut** [comment]
Pylance uses lazy evaluation for all type information. In other words, it evaluates only the files that are referenced and only the portions of the parse tree that need to be analyzed to resolve a type definition. This is all done on demand, and the results are cached in memory to avoid duplication of work.

The full file is analyzed only if and when it is opened in the editor, and that can be done very quickly. So I think it's working like you are suggesting it should.

**Comment by jakebailey** [comment]
I am referring to the setting "useLibraryCodeForTypes", which goes into libraries and runs the normal type inference on them as though they are user code. I am not saying that libraries cannot have types, but if a package is for stubs, then it its stubs would be read. I am just saying that if you are stubbing out something like blender, then it's describing a module that would exist in the real code (which is exactly what stubs are for, no?).

**Comment by Kein** [comment]
> So I think it's working like you are suggesting it should.

No it doesn't. Am I failing to explain what do I mean? I've tried twice. Is it because english is not my native language? Am I using incorrect defintions, are my sentences do not refelct my flow of thoughts? I dont really know what else can I do.

**Comment by jakebailey** [comment]
Pylance defaults to "open files only", so the only code that is analyzed is the files you have open, as well as any code needed to fully type check them. Diagnostics are not emitted for any file that isn't open in this mode. The actual diagnostic emitting is done as a part of the type checking, which is exactly what the analysis is doing anyway to offer any of its feature. Offering an option to disable this would not affect performance, and your idea of a script that appends that wouldn't change the performance characteristics of Pylance.

We already start by only analyzing the files you open, and then the minimum number of files and code needed while analyzing those open files (we may only parse and bind files, and never actually evaluate their types!). When `useLibraryCodeForTypes` is disabled, we don't go and analyze libraries that don't have stubs, which saves more time.

To my eye, this is already effectively the minimum amount of work needed to have things work as expected.

It seems like you are offering a solution of limiting the scope to project files as a way to improve the performance in editing your project, correct? I'm still interested in the contents of the project and what sort of performance you're getting at the moment. If we are slow, we'd like to understand why, as the intent is that we already do the least amount of work in every instance by design.

> For example, if I have custom type stubs and I use in-place navigation to the source Pylance provides and VS opens for me that stud/source document - it should not be processes as a valid projet document for all active aforementioned functional. But it STILL should be processes in the background for type info because otherwise I wont have that type info in the active and actual PROJECT document.

By this, are you just trying to say that you want no editor features whatsoever in any library code? We intend for features to work in all files (as that's what most people expect; jump to code and you can keep jumping, highlighting working, etc). Are you seeing performance hits when this happens? Do you have any logs that show the slowdown? Our trace mode will emit timings that we can look at for potential performance bugs.

**Comment by Kein** [comment]
> It seems like you are offering a solution of limiting the scope to project files as a way to improve the performance in editing your project, correct? I'm still interested in the contents of the project and what sort of performance you're getting at the moment.

If I wanted to make a performance issue report I'd do it. The request in opening post is a completely different proposal, it does not have to be performance related necessary.

**Comment by jakebailey** [comment]
Your original post said:

> Now, every time I navigate to the target site to get a bit more info Pylance tries to analyze it as well, which results in a very slow performance. It may take it minutes and generate up to few thousands warnings. It seems utterly pointless to waste CPU cycles on it and honestly, on anything outside of the project files.

Which is what I was focusing on; disabling diagnostics generation is unlike to impact the performance except for a few small wins. If it's more of a visual issue of not wanting to see type errors in non-workspace files, that's a different beast (which I think may be workable with `pyrightconfig.json` as it is now via some combination of include/exclude/ignore?).

**Comment by erictraut** [comment]
I've read and re-read all of your posts, and I'm still unclear on what _problem_ you're experiencing.

Rather than explaining a desired _solution_, could you please take another try at explaining the _problem_ you're experiencing? That way, we may be better able to suggest solutions.

**Comment by max-sixty** [comment]
To interject with an answer to "what's the actual problem": https://github.com/microsoft/pyright/issues/1334#issue-777358476

Essentially, if there's a path that contains a large number of python files in the project directory — e.g. a `.asv` path — then Pylance will keep filling and emptying its cache such that there is rarely an available result.

This happens even though those python files aren't accessed by code that runs in the project; in this case they're used by the asv benchmarking suite. It may not be trivial for Pylance to evaluate whether or not they're accessible, though.

One possible resolution is to warn the user if the cache keeps getting wiped — it's unlikely that it's an intended, and it was difficult for me to debug — I turned on a bunch of logging and then guessed that was the issue, and confirmed it by wiping that path.

**Comment by jakebailey** [comment]
@max-sixy I'm having a hard time understanding how what you've described relates to what @Kein has described. It sounds more like you want to be able to exclude folders from the analysis entirely, which I believe is already achievable through a pyrightconfig file. But, those files should not be analyzed at all if they are not referenced either, as the default is "open files only", and if they are getting pulled in then they are referenced from other open files which may need their info. If you're using workspace mode where the entire workspace is checked for errors, then you're going to hit things like this without excluding files that should not be checked for diagnostics, which I believe is what was described in that pyright issue.

**Comment by jakebailey** [comment]
Re-examining this, I think that some of the previously mentioned items could be covered by ignore/exclude in a pyrightconfig (or as a VS Code setting as requested in #1150), but I don't think anyone actually confirmed that it had the expected behavior, so I can't really do anything until that's tested.

I think enough's been said about how we choose to limit our analysis; we are lazy, but opening a file means that the editor is looking for diagnostics/semantic tokens/etc, and we serve those requests.

Now, I tested out `fake-bpy-module` and it does appear that the `bpy.types` module is very very large (nearly 100k lines) and we spend a significant amount of time parsing and (mainly) checking it. This will require further investigation.

**Comment by max-sixty** [comment]
Thanks @jakebailey. I can write out the steps to reproduce my case if that would be helpful (it's basically cloning xarray and running asv). 

> I think enough's been said about how we choose to limit our analysis; we are lazy, but opening a file means that the editor is looking for diagnostics/semantic tokens/etc, and we serve those requests.

This sounds ideal. It's not the behavior I was seeing though — I'm not sure how the packages inside the asv path was getting picked up. It's similar to a nested virtualenv — potentially something running `import pandas` was being interpreted as referencing the pandas packages under `.asv`?

**Comment by jakebailey** [comment]
Would you mind making a new issue with the set of steps? I think your case is sufficiently different than the original post and I'd like to split the two apart.

**Comment by max-sixty** [comment]
I just opened an issue to give a full repro, but I can't get any logs like those in https://github.com/microsoft/pyright/issues/1334. So maybe it's fixed! Or I was doing something screwy back then.

I'll leave the `asv` conda directories there and see if it becomes slow again; otherwise we can consider the case fixed. Cheers @jakebailey

**Comment by Kein** [comment]
I disagree, very precise control as to what actually fully process on language server would be useful and unless I'm missing some implementation detail that make the addition of this feature to be way harder and complex than it seems (in which case it would make sense, as a balance between feature's worth and implementation effort) I'm not sure I understand the effort to make convincing argument requested exception filter is not worth it or useful.

Since nobody else expressed interest and you've already came to some consensus between each other I don't see much point arguing further. Thankfully, I dont work with Python as much so I dont have to suffer with weirdly slow big projects often :P
I suspect though, this or similar to this suggestion will pop up later down the road anyway.
