### ISSUE TITLE
Testing pylance from command line

### ISSUE THREAD

**Issue by Dr-Irv** [microsoft/pylance-release#704]
When I'm trying to fix the pandas typestubs, the only way I've been able to do it is by editing the stubs in the release in my extensions directory, going to settings and turning off and on  the pylance type checking to force the edited stubs to get reloaded in VSCode.

Is there a way to tell pylance (via command line or another method) to reload fresh type stubs and check one python file for errors? (Similar to `mypy` )

**Comment by jakebailey** [comment]
The bundled stubs are lower in precedence than typings. You should be able to put stubs into a folder named typings and have changes picked up there automatically. The stubs in the extension are assumed to be read-only and are not watched for changes.

**Comment by jakebailey** [comment]
I don't expect us to have any CLI for pylance; it's exclusively a VS Code extension (which can be run in multiple processes and such).

The CLI would be pyright, which you can run with the same setup and stick the typings you're working on into a folder. The only difference is in the default settings.

**Comment by Dr-Irv** [comment]
> The bundled stubs are lower in precedence than typings. You should be able to put stubs into a folder named typings and have changes picked up there automatically. The stubs in the extension are assumed to be read-only and are not watched for changes.

So if I have my own copy of the https://github.com/microsoft/python-type-stubs repo, and instead of using `typings`, I use the absolute path of the directory containing that repo in my settings for "Stub Path", will pylance use the stubs in the repo instead of the bundled stubs?

And if I make a change to that local repo containing the stubs, will pylance automatically see that my copy of the stubs have changed and use that as soon as I edit it (within VS Code)?

**Comment by jakebailey** [comment]
Yes, that all should work.

**Comment by jakebailey** [comment]
Unless I'm mistaken, this should be closed; it's possible we could better watch our own stub files, but we aren't intending for them to be modified in-place and for editing, the `typing` folder or other projects open work better.
