### ISSUE TITLE
Type annotations context semantically highlighted incorrectly?

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#708]
## Environment data
Pylance 2012.12.1
Python 3.8.5
Win7x64

## Expected behaviour
Not sure but definitely not the actual one as of now?

## Code Snippet / Additional information
Blender has new recommendations for type annotations:
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons#Class_Property_Registration

Although I find them weird since they don't actually conform PEP-526 directly, the result with semantic linter I get is this:
![image](https://user-images.githubusercontent.com/623756/101698005-dc8b9d80-3a89-11eb-9658-af0b7402bc73.png)

**Comment by jakebailey** [comment]
Unless I'm mistaken, function calls like this shouldn't be legal in type annotations. Type annotations are meant to be static only, and future releases of Python won't evaluate them at all anymore. I don't believe we really try and handle this.

In any case, what do you find to be incorrect about this highlighting? I don't know how your theme has chosen to show its semantic colors as they all are different.

**Comment by Kein** [comment]
The `bpy.props` highlighted as type (italic and burple) until the method usage.

**Comment by jakebailey** [comment]
Can you use VS Code's token inspector and share what scopes/modifiers we're applying? You can find it in the command palette, and then you can click on a token to reveal how it's being processed:

![image](https://user-images.githubusercontent.com/5341706/101698993-4aef4200-3a2f-11eb-9190-784602fe9716.png)

**Comment by Kein** [comment]
![Uploading image.png…]()

**Comment by Kein** [comment]
![image](https://user-images.githubusercontent.com/623756/101699219-d72f5280-3a8b-11eb-9c65-c03c8488d472.png)

**Comment by jakebailey** [comment]
That seems correct to me... we're saying that it's a module, but then adding a modifier to say that it's inside of a type hint. The latter was added as a feature last month to help themers to tweak the colorization inside of annotations specifically.

It says that your user settings are overriding it; perhaps they can be modified to more specifically recolor things. I'd have expected those overrides to also override the class, but that hasn't occurred.

**Comment by Kein** [comment]
I have no issues with my typeHint rules to overrides every other single semanticly-processed type - that is the whole idea, to see it is a type/typehint at a glance. The issue is that it seemed wrong to me it colored the declaration that way in aforementioned case but then I remembered almost any literal can be specified there so.. ehhh

**Comment by CatNofishing** [comment]
@jakebailey  please consider this issue, highlighted incorrectly #708

**Comment by jakebailey** [comment]
I'm not sure there's anything wrong on our end here; we are marking the whole annotation with the typeHint modifier, and it'd really depend on the rules in your config (which we can take a look at). For me, it seems like it's saying that it should be italic and bold and that's what is happening, unless you're saying that it's the class portions that are wrong (in which case I'd be interested in the token there).
