### ISSUE TITLE
Manually built packages don't get semantic highlighting

### ISSUE THREAD

**Issue by DocterDum** [microsoft/pylance-release#710]
## Environment data

-   Language Server version: 2020.12.1
-   OS and version: Win 10 19042.630
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9

## Expected behaviour

I've been using OpenCV's pip package, however to enable CUDA acceleration I was required to build OpenCV myself. After manually building and installing, Pylance no longer performs semantic highlighting on functions.

I've tested with it installed to both the system and user directories:
C:\Program Files\Python39\Lib\site-packages\cv2
C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\cv2

## Code Snippet / Additional information

import cv2 as cv
import numpy as np

cv.imshow(args)
np.array(args)

'array' shows as yellow
'imshow' displays as white

## Logs

[Info  - 3:59:04 pm] Pylance language server 2020.12.1 (pyright 4ef6f2b2) starting
[Info  - 3:59:04 pm] Server root directory: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist
[Info  - 3:59:04 pm] No configuration file found.
[Info  - 3:59:04 pm] Setting pythonPath for service "ImageRecognition": "C:\Program Files\Python39\python.exe"
Search paths found for configured python interpreter:
  C:\Program Files\Python39\DLLs
  C:\Program Files\Python39\lib
  C:\Program Files\Python39
  C:\Users\*****\AppData\Roaming\Python\Python39\site-packages
  C:\Program Files\Python39\lib\site-packages
[Error - 3:59:04 pm] stubPath d:\ImageRecognitionProject\ImageRecognition\typings is not a valid directory.
[Info  - 3:59:04 pm] Assuming Python version 3.9
[Info  - 3:59:04 pm] Assuming Python platform Windows
[Info  - 3:59:04 pm] Searching for source files
[Info  - 3:59:04 pm] Found 10 source files
[FG] parsing: d:\ImageRecognitionProject\ImageRecognition\vidFR.py (47ms)
[FG] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\builtins.pyi [fs read 2ms] (86ms)
[FG] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\builtins.pyi (32ms)
[FG] binding: d:\ImageRecognitionProject\ImageRecognition\vidFR.py (3ms)
[Info  - 3:59:05 pm] Background analysis(1) root directory: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist
[Info  - 3:59:05 pm] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: getSemanticTokens
[BG(1)] parsing: d:\ImageRecognitionProject\ImageRecognition\vidFR.py (47ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\builtins.pyi [fs read 2ms] (90ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\builtins.pyi (34ms)
[BG(1)] binding: d:\ImageRecognitionProject\ImageRecognition\vidFR.py (2ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\os\__init__.pyi [fs read 1ms] (29ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\os\__init__.pyi (5ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\2and3\math.pyi [fs read 2ms] (5ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\2and3\math.pyi (1ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi [fs read 1ms] (9ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\2and3\_typeshed\__init__.pyi (1ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\third_party\2and3\typing_extensions.pyi [fs read 0ms] (3ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\third_party\2and3\typing_extensions.pyi (0ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\typing.pyi [fs read 0ms] (25ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\typing.pyi (11ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\abc.pyi [fs read 0ms] (0ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\3\abc.pyi (0ms)
[BG(1)] parsing: d:\ImageRecognitionProject\ImageRecognition\funky.py [fs read 0ms] (10ms)
[BG(1)] binding: d:\ImageRecognitionProject\ImageRecognition\funky.py (1ms)
[BG(1)] parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py [fs read 1ms] (61ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py ...
[BG(1)]   parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\__init__.py [fs read 0ms] (44ms)
[BG(1)]   binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\__init__.py ...
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\numeric.py [fs read 0ms] (71ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\numeric.py ...
[BG(1)]       parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\umath.py [fs read 0ms] (5ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\umath.py ...
[BG(1)]         parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\bundled\native-stubs\numpy\core\_multiarray_umath.pyi [fs read 2ms] (113ms)
[BG(1)]         binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\bundled\native-stubs\numpy\core\_multiarray_umath.pyi (22ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\umath.py (136ms)
[BG(1)]       parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\numerictypes.py [fs read 1ms] (18ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\numerictypes.py (3ms)
[BG(1)]       parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py [fs read 1ms] (30ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py (6ms)
[BG(1)]       parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\arrayprint.py [fs read 1ms] (29ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\arrayprint.py (12ms)
[BG(1)]       parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\_asarray.py [fs read 1ms] (4ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\_asarray.py (2ms)
[BG(1)]       parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\_ufunc_config.py [fs read 0ms] (5ms)
[BG(1)]       binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\_ufunc_config.py (1ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\numeric.py (258ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\records.py [fs read 0ms] (10ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\records.py (4ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\memmap.py [fs read 0ms] (7ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\memmap.py (1ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\function_base.py [fs read 1ms] (13ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\function_base.py (1ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\machar.py [fs read 0ms] (11ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\machar.py (2ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\getlimits.py [fs read 0ms] (9ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\getlimits.py (3ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\shape_base.py [fs read 1ms] (12ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\shape_base.py (3ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\einsumfunc.py [fs read 0ms] (19ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\einsumfunc.py (6ms)
[BG(1)]   binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\__init__.py (433ms)
[BG(1)]   parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\__init__.py [fs read 0ms] (8ms)
[BG(1)]   binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\__init__.py ...
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\type_check.py [fs read 1ms] (3ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\type_check.py (2ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\index_tricks.py [fs read 0ms] (18ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\index_tricks.py (2ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\function_base.py [fs read 1ms] (53ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\function_base.py (12ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\nanfunctions.py [fs read 0ms] (13ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\nanfunctions.py (3ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\shape_base.py [fs read 1ms] (14ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\shape_base.py (5ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\stride_tricks.py [fs read 0ms] (1ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\stride_tricks.py (1ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\twodim_base.py [fs read 0ms] (6ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\twodim_base.py (2ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\ufunclike.py [fs read 0ms] (2ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\ufunclike.py (0ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\histograms.py [fs read 0ms] (5ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\histograms.py (9ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\polynomial.py [fs read 1ms] (26ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\polynomial.py (5ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\utils.py [fs read 0ms] (20ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\utils.py (6ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\arraysetops.py [fs read 0ms] (7ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\arraysetops.py (3ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\npyio.py [fs read 1ms] (41ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\npyio.py (16ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\financial.py [fs read 0ms] (16ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\financial.py (4ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\arraypad.py [fs read 1ms] (5ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\arraypad.py (3ms)
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_version.py [fs read 1ms] (3ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_version.py (1ms)
[BG(1)]   binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\lib\__init__.py (309ms)
[BG(1)]   parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\matrixlib\__init__.py [fs read 0ms] (0ms)
[BG(1)]   binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\matrixlib\__init__.py ...
[BG(1)]     parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\matrixlib\defmatrix.py [fs read 0ms] (5ms)
[BG(1)]     binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\matrixlib\defmatrix.py (2ms)
[BG(1)]   binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\matrixlib\__init__.py (7ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\__init__.py (804ms)
[BG(1)] parsing: C:\Program Files\Python39\lib\site-packages\cv2\__init__.py [fs read 0ms] (2ms)
[BG(1)] binding: C:\Program Files\Python39\lib\site-packages\cv2\__init__.py (1ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\2and3\time.pyi [fs read 0ms] (1ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\stdlib\2and3\time.pyi (1ms)
[BG(1)] parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\face_recognition\__init__.py [fs read 0ms] (1ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\face_recognition\__init__.py (0ms)
[BG(1)] parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\face_recognition\api.py [fs read 0ms] (18ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\face_recognition\api.py (2ms)
[BG(1)] parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\dlib\__init__.py [fs read 0ms] (3ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\dlib\__init__.py (0ms)
[BG(1)] parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\face_recognition_models\__init__.py [fs read 0ms] (6ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\face_recognition_models\__init__.py (0ms)
[BG(1)] parsing: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\third_party\3\pkg_resources\__init__.pyi [fs read 0ms] (10ms)
[BG(1)] binding: c:\Users\*****\.vscode\extensions\ms-python.vscode-pylance-2020.12.1\dist\typeshed-fallback\third_party\3\pkg_resources\__init__.pyi (3ms)
[BG(1)] parsing: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\multiarray.py [fs read 0ms] (7ms)
[BG(1)] binding: C:\Users\*****\AppData\Roaming\Python\Python39\site-packages\numpy\core\multiarray.py (5ms)
Background analysis message: analyze
[BG(1)] analyzing: d:\ImageRecognitionProject\ImageRecognition\vidFR.py ...
[BG(1)]   checking: d:\ImageRecognitionProject\ImageRecognition\vidFR.py (9ms)
[BG(1)] analyzing: d:\ImageRecognitionProject\ImageRecognition\vidFR.py (9ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange

**Comment by jakebailey** [comment]
![image](https://user-images.githubusercontent.com/5341706/106979090-70888700-6712-11eb-8ff4-03a5df6b5f02.png)
