### ISSUE TITLE
Missing docstrings for builtins (pyright) 

### ISSUE THREAD

**Issue by YodaEmbedding** [microsoft/pylance-release#712]
Docstrings for third-party libraries and custom functions work. Would it be possible to reallow builtin functions (e.g. `print`) to also display docstrings?

This issue from the pylance repository contains more details: https://github.com/microsoft/pylance-release/issues/49

> I am using the extension with Python 3.8.3. On hover for any function, the tooltip shows only the type information (of parameters, return value etc.).
> I'd prefer it showing the documentation of the function (wherever available) as well, so that it is clear what the function is being used for. This can be seen [demonstrated in the Pylance announcement blog post](https://devblogs.microsoft.com/python/wp-content/uploads/sites/12/2020/06/type_information.gif) for the pandas library.
> ## Environment data
> 
>     * Language Server version: 2020.6.1
> 
>     * OS and version: Windows 10 Version 20H2 (OS Build 19042.330)
> 
>     * Python version: 3.8.3 64-bit
> 
> 
> ## Expected behaviour
> 
> Before installing pylance
> ![image](https://user-images.githubusercontent.com/24961562/86480931-a163a080-bd6c-11ea-99e9-540a4ccfd8d3.png)
> ## Actual behaviour
> 
> After installing pylance
> ![image](https://user-images.githubusercontent.com/24961562/86480946-aaed0880-bd6c-11ea-97de-23006c3b6003.png)

**Comment by bschnurr** [comment]
Please update your pylance version to the latest 2020.12.1
you should see doc strings for `print`

**Comment by savannahostrowski** [comment]
To be clear, is the request to have this work in pyright?

**Comment by YodaEmbedding** [comment]
> To be clear, is the request to have this work in pyright?

Yes, that is correct.

It's useful for developers using pyright as a replacement for the (deprecated?) Microsoft Python Language Server in editors such neovim.

**Comment by HawickMason** [comment]
Still got problems on builtin docstring under pylance version 2021.1.1 while under a venv......
![image](https://user-images.githubusercontent.com/15688994/104558613-0e41e680-567e-11eb-94f7-0f5c49814629.png)
When I click on the builtin funcitons, it goes to 
![image](https://user-images.githubusercontent.com/15688994/104558678-231e7a00-567e-11eb-9d1f-ea9481aad7ac.png)
Any clue?

**Comment by jakebailey** [comment]
@HawickMason This issue is about the decision to shift the builtin docstring code from Pylance into pyright, not for general issues with builtin docstrings. If you're using Pylance and have an issue with it's current builtin docstring support, it's unrelated and we'd appreciate a new issue with our bug template filled out.

**Comment by savannahostrowski** [comment]
This request has been open for a long while without upvotes and as such, we cannot prioritize this work so I'm going to close this.
