### ISSUE TITLE
Generic type vs type implementation of built-ins (typing.Dict vs dict)

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#715]
So I've noticed that even in `strict` mode Pylance does not seems to mind me throwing around `dict[t,t]` in type annotations, however `mypy` raises quite a fuss and recommends using generic `typing.` variation of it - `Dict`.
Any particular reason Pylance does not have it een at the highest level of diagnostics?
Some extra insight: https://github.com/python/mypy/issues/7907#issuecomment-557101078

**Comment by erictraut** [comment]
Are you using Python 3.9 or Python 3.10a? This syntax is now support in the newer versions of Python, as per PEP 585. Pylance emits an error only if you're using Python 3.8 or older.

**Comment by Kein** [comment]
Actually I'm using 3.8.5 and Pylance does not emit any errors for me

**Comment by savannahostrowski** [comment]
Would you be able to provide a code example and some trace logs so we can get info about the interpreter being used?

**Comment by Kein** [comment]
Sorry, I took few days off and still dont understand what code snippet you expect me to provide?
I mean:
![image](https://user-images.githubusercontent.com/623756/102056226-1bf51980-3dfd-11eb-80f2-f144129e66f4.png)
```python
var: dict[str, Any] = dict(test='literal1'm test2=123)
```
?

There is nothing out of ordinary in the log:
```
Search paths found for configured python interpreter:
  C:\Programs\Python\DLLs
  C:\Programs\Python\lib
  C:\Programs\Python
  C:\Users\Kein\AppData\Roaming\Python\Python38\site-packages
  C:\Programs\Python\lib\site-packages
[Info  - 11:10:20 am] Assuming Python version 3.8
[Info  - 11:10:20 am] Assuming Python platform Windows
[Info  - 11:10:20 am] Searching for source files
[Info  - 11:10:20 am] Found 3 source files
```

**Comment by erictraut** [comment]
When we ask for code snippets, we're looking for self-contained and minimal code snippets that exhibit the bug. I presume that your full snippet is as follows?

```python
from typing import Any
var: dict[str, Any] = dict(test="literal1", test2=123)
```

This generates an error for me when a Python 3.8 interpreter is selected, and that error goes away when I select a Python 3.9 interpreter.

Is it possible that you are using `from __future__ import annotations`? That will also suppress this error even with older versions of Python.

**Comment by Kein** [comment]
> Is it possible that you are using `from __future__ import annotations`?

Nope, just basic `import typing`, Python 3.8.5 detected correctly. Only other linters emit warnings.

**Comment by erictraut** [comment]
Here's what I see with Python 3.8 selected:

![Screen Shot 2020-12-14 at 8 49 32 AM](https://user-images.githubusercontent.com/7040122/102110001-83a16980-3de9-11eb-8de6-e3c0f1146dac.png)

And with Python 3.9 selected:

![Screen Shot 2020-12-14 at 8 49 42 AM](https://user-images.githubusercontent.com/7040122/102109928-71bfc680-3de9-11eb-9718-c0b1558254af.png)

**Comment by Kein** [comment]
Yep, nothing here, mypy does generate the error but not Pylance.

**Comment by jakebailey** [comment]
Hmm, I don't get an error for this either, and I have selected Python 3.8:

![image](https://user-images.githubusercontent.com/5341706/105762984-06016b00-5f0a-11eb-899d-13849403d36d.png)

![image](https://user-images.githubusercontent.com/5341706/105763025-13b6f080-5f0a-11eb-85d4-ad7f58d2bd3a.png)

**Comment by erictraut** [comment]
Do you have typeCheckingMode set to "off"? That error is suppressed in that case. If you set typeCheckingMode to "on" and choose Python 3.8 or older, you should see the error. I just confirmed that I do.

![Screen Shot 2021-01-25 at 12 45 54 PM](https://user-images.githubusercontent.com/7040122/105764029-4a413b00-5f0b-11eb-9762-2b36eb252b79.png)

![Screen Shot 2021-01-25 at 12 46 01 PM](https://user-images.githubusercontent.com/7040122/105764042-4f05ef00-5f0b-11eb-99d0-d79d4f1f8a25.png)

**Comment by jakebailey** [comment]
Nope, I am in strict mode. See if I just try and use `dict`:

![image](https://user-images.githubusercontent.com/5341706/105764431-cb98cd80-5f0b-11eb-867c-a35fee2ad0d4.png)

**Comment by erictraut** [comment]
Are you editing a ".py" or ".pyi" file? I can't tell from your screen shots. If you're editing a ".pyi" file, then the behavior is expected.

**Comment by jakebailey** [comment]
py.

![image](https://user-images.githubusercontent.com/5341706/105765178-e0299580-5f0c-11eb-9e4f-67012dae36e4.png)

**Comment by erictraut** [comment]
Can you try overriding the python version in pyrightconfig.json? That's what I'm doing in my repro. (I'm also using the debug pyright extension. I haven't confirmed with pylance, but it's the same code.)

**Comment by jakebailey** [comment]
If I explicitly set 3.8 in that config, then I do see the error. In fact, even having the `pyrightconfig.json` file at all makes the error appear. Removing the file, the error goes away again.

**Comment by jakebailey** [comment]
We did a little bit of testing with this, and found that at first startup, the Python extension is answering just "python" as the interpreter (not the correct one), but if you change the config, Pylance re-queries the Python extension and gets back the activated one (at which point it knows the version number). So it's not the existence of any config, but some timing issue where the Python extension is returning one answer but not notifying when it knows the answer has changed.

**Comment by jakebailey** [comment]
I haven't been able to experience this in a while; I last commented in January and haven't seen it since. I'm going to call this fixed, unless someone manages to reproduce it.

In my case, I think there's been enough refactoring of the interpreter system in the Python extension that the race is probably gone.
