### ISSUE TITLE
matplotlib: analysis failed when use some package

### ISSUE THREAD

**Issue by CarlDegio** [microsoft/pylance-release#716]
I met some problems when use pylance analysis.
![recognition failed](https://user-images.githubusercontent.com/52379582/101801485-5c2c7180-3b49-11eb-8c73-b635d19a7ff1.png)
Recognition failed in this fig.
!['set_data' should be a method of variable patch](https://user-images.githubusercontent.com/52379582/101801499-60f12580-3b49-11eb-881a-e13b5e387167.png)
![read failed](https://user-images.githubusercontent.com/52379582/101801507-63ec1600-3b49-11eb-8dd6-e3b3dd897745.png)
Couldn't search this method in variable 'patch'

However, it has no effect on running code. That is, running normally but analysis wrong.
I just use this for a short time, so I'm not sure about whether it's a common problem.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202130-3-march-2021
