### ISSUE TITLE
Semantic map ignores member.access for NamedTuples

### ISSUE THREAD

**Issue by Kein** [microsoft/pylance-release#723]
## Environment data
Pylance 2012.12.1
Python 3.8.5
Win7x64

## Expected behaviour
Access to the members of NamedTuple treated as `member.access.python`

## Actual behaviour
Members of NamedTuple lumped together into generic `variable` scope:
![image](https://user-images.githubusercontent.com/623756/101982018-f42d7680-3c81-11eb-8fd6-daf84e493251.png)

## Code Snippet / Additional information
See above

**Comment by jakebailey** [comment]
This got fixed in a previous release, but we missed closing this issue:

![image](https://user-images.githubusercontent.com/5341706/105900647-2f38fe80-5fd1-11eb-9b7a-44374e2958e3.png)
