### ISSUE TITLE
Import “Path.to.own.script” could not be resolvedPylance (reportMissingImports) in VS Code using python 3.9x on Lubuntu 20.04

### ISSUE THREAD

**Issue by AndreasLuckert** [microsoft/pylance-release#724]
## Environment data

-   Language Server version: Pylance v2020.12.2
-   OS and version: Lubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.0 (default, Nov 22 2020, 23:12:14) 
[GCC 5.5.0] on linux, managed with pip, pyenv and pyenv-virtualenvwrapper installed via homebrew

## Expected behaviour

`Pylance` doesn't show a _warning_ when importing a custom module at the beginning of my current `python`-script:
`import General.Misc.general_tools as tools`

## Actual behaviour

My `python 3.9x` - script (using `VS Code` on `Lubuntu 20.04 LTS`) starts with the following import of custom "tools":

    import sys
    sys.path.append(
        '/home/andylu/Dokumente/Allgemeines_material/Sonstiges/Programming/Python/Scripts/'
    )
    
    import General.Misc.general_tools as tools

Now, `Pylance` states `Import "General.Misc.general_tools" could not be resolvedPylance (reportMissingImports)` even though when executing the module is being imported perfectly fine.

Thus, to ensure making `Pylance` understand that this is an existing module-path, in addition to the `sys.path.append(..)` - approach, I added the following to the `settings.json` - file:

    {
    	...
    	// Possible values: "Jedi", "Pylance", "Microsoft", "None".
    	"python.languageServer": "Pylance",
    	// NOTE on changing from microsoft to pylance language server: python.autoComplete.extraPaths --> python.analysis.extraPaths
    	// Docs: https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#unresolved-import-warnings
    	"python.analysis.extraPaths": [
    		"/home/andylu/Dokumente/Allgemeines_material/Sonstiges/Programming/Python/Scripts"
    	],
    	...
    }

Yet, I still get the `reportMissingImports`-message even though it's correctly being imported.

A workaround I found [here][1] works well (appending `# type: ignore` to the import-statement):

    import General.Misc.general_tools as tools  # type: ignore

Nevertheless, it's just a workaround which is why I'm looking to solve the root of this issue.

  [1]: https://www.reddit.com/r/VisualStudioCode/comments/i3mpct/how_to_tell_pylance_to_ignore_particular_linefile/g5bkx9u?utm_source=share&utm_medium=web2x&context=3
  [2]: https://stackoverflow.com/a/15282950/12298276
  [3]: https://virtualenvwrapper.readthedocs.io/en/latest/
  [4]: https://github.com/pyenv/pyenv

## Code Snippet / Additional information

I asked this question several days ago on [StackOverflow](https://stackoverflow.com/questions/65252074/import-path-to-own-script-could-not-be-resolvedpylance-reportmissingimports), but was recommended to file an issue here.

**Notes on additional measures I tried:**

I added `export PYTHONPATH="$PYTHONPATH:/home/andylu/Dokumente/Allgemeines_material/Sonstiges/Programming/Python/Scripts"` to my `~/.bashrc` - file, which enables me now to import the module directly in a `python`-shell from terminal without the previous `sys`-path manipulation. This however applies only to the global system python environment, but not to any virtual environment.
In order to change the sys-path there, I followed [these instructions][2], while my particular virtual environment "scrapy_course" is open, like so:

    (scrapy_course) andylu@andylu-Lubuntu-PC:~/$ add2virtualenv /home/andylu/Dokumente/Allgemeines_material/Sonstiges/Programming/Python/Scripts

This command applies for [virtualenvwrapper][3], which mananges virtual environments in conjunction with [pyenv][4] neatly.
Now, I can run my aforementioned script within the current environment even without the `sys.path.append(...)` prior to import the module, YET `pylance` still doesn't recognize the paths correctly and shows me the same warning as before.

**Comment by jakebailey** [comment]
Can you provide the logs that the issue template listed? https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#filing-an-issue

It should be printing the search paths Pylance is using to resolve imports.

Note that we don't currently support PYTHONPATH (#275, WIP), so modifying that won't help. extraPaths should be getting you what you need.

**Comment by AndreasLuckert** [comment]
> Can you provide the logs that the issue template listed? https://github.com/microsoft/pylance-release/blob/master/TROUBLESHOOTING.md#filing-an-issue
> 
> It should be printing the search paths Pylance is using to resolve imports.

Do you refer to 

> Enable trace logging by adding `"python.analysis.logLevel": "Trace"` to your `settings.json` configuration file. Adding this will cause a large amount of info to be printed to the Python output panel.
?

This is what I did, but I have no idea where the logs are being sent and saved. Can you provide me some more info on that, please? Do I have to run the `python` script, start a debug session, or just let the file be analyzed by `pylance`?

**Comment by AndreasLuckert** [comment]
Now, for some reason, it stopped throwing the warnings. I don't know how it got resolved, but I'm going to close this issue for now. Thanks for your help.
