### ISSUE TITLE
Type info of decorated class is not helpful with specific attribute class

### ISSUE THREAD

**Issue by kang-sw** [microsoft/pylance-release#728]
When `gin.configurable` decorates any class, pylance's suggestions shows pretty useless information. It works well when the class is decorated with `attr.attrs`, or any other attribute method. 

![image](https://user-images.githubusercontent.com/32210953/102029927-dbdd6900-3df3-11eb-9b38-bac55676a014.png)

![image](https://user-images.githubusercontent.com/32210953/102029977-18a96000-3df4-11eb-9b98-576f49f03d31.png)

![image](https://user-images.githubusercontent.com/32210953/102029942-eef03900-3df3-11eb-8e29-404acca04863.png)

![image](https://user-images.githubusercontent.com/32210953/102030028-61f9af80-3df4-11eb-9e75-8d4561462f26.png)

This makes it hard to work with tf-agents that most of classes are decorated with `gin` attribute....

Is there any workaround to resolve this?

**Comment by jakebailey** [comment]
This is likely due to the `gin.configurable` decorator not being well-typed, and the analysis assuming it wipes away all of the info. This happens pretty commonly when a decorator uses `functools.wraps`, whose type isn't super helpful.

Where can we find the code for `gin`? I've looked on PyPI, but the results didn't seem like they matched what this library appears to be doing.

**Comment by kang-sw** [comment]
I found this when I was using `tf-agent` library to practice some reinforcement algorithms.

I think you can get `gin` package by command `pip install gin`, in Windows.

![image](https://user-images.githubusercontent.com/32210953/102164008-8033de00-3ece-11eb-9c45-f17bbaf60161.png)

and here's url of the repository [gin](https://github.com/google/gin-config)

**Comment by jakebailey** [comment]
Yeah, they haven't annotated it at all: https://github.com/google/gin-config/blob/0841fef568722a21e4f3745a0697da608ba4376e/gin/config.py#L1163

Though I'm a bit confused, as I believe we had a heuristic where we would assume that the decorator did nothing to the signature if the decorator was untyped. @erictraut Am I misremembering that?

**Comment by erictraut** [comment]
That's definitely the way it used to work. I'm wondering if maybe I broke that heuristic when I added support for [PEP 614](https://www.python.org/dev/peps/pep-0614/). I don't think we have a specific unit test for this heuristic, and we probably should.

**Comment by erictraut** [comment]
This will be addressed in the next release. See https://github.com/microsoft/pyright/issues/1292 for details.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.1.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202110-6-january-2021
