### ISSUE TITLE
Scipy module intelisense stucks in loading and miss doc about minimize function

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#729]
version: 1.51.1 (user setup)
commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
pylance:v2020.12.3-pre.1

![image](https://user-images.githubusercontent.com/33288114/102037206-958e0700-3dff-11eb-8618-92c09d0ca33f.png)

**Comment by judej** [comment]
Thanks for the report, could you please fill out the template so we can see the logs and the version?

Also, what do you see when you hover over `minimize()`? Do you get a tooltip?

thanks

**Comment by bschnurr** [comment]
![image](https://user-images.githubusercontent.com/1946977/102121971-ab98c900-3df9-11eb-948e-6704b03ac3b5.png)

**Comment by bschnurr** [comment]
On my machine it takes 25 seconds for hover to finish loading. Then once it is cached the doc strings appear.

**Comment by CatNofishing** [comment]
> On my machine it takes 25 seconds for hover to finish loading. Then once it is cached the doc strings appear.

Yeap,it take a long time to load doc when you hover the word about scipy.optimize.minimize

**Comment by bschnurr** [comment]
I'm seeing a difference between parsing in foreground thread vs background thread when just opening _minimize.py. 

[pylance_minimize_fgthread.txt](https://github.com/microsoft/pylance-release/files/5698844/pylance_minimize_fgthread.txt)
[pylance_minimize_bgthread.txt](https://github.com/microsoft/pylance-release/files/5698845/pylance_minimize_bgthread.txt)

I also compared with pyright but pyright has "python.analysis.useLibraryCodeForTypes": false, by default which also speeds things up.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.1.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202110-6-january-2021
