### ISSUE TITLE
matplotlib: Pylance does'nt show autocomplete of modules in matplotlib

### ISSUE THREAD

**Issue by Trid-collab** [microsoft/pylance-release#73]
Issue Type: <b>Bug</b>

import matplotlib.pyplot as plt
plt.style.use("seaborn-darkgrid") <----- when we plt. --- the style option does not show up in the autocomplete option. 

import pandas as pd
pd.set_option <----- the set_option does not show up when type pd. in autocomplete

Extension version: 2020.6.1
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.96GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gramster** [comment]
Thanks; we are missing the option APIs; will add them in next release.

**Comment by jakebailey** [comment]
As for pyplot, the documentation does not list `pyplot.style`: https://matplotlib.org/api/pyplot_api.html

This might be exported by way of it importing something else and a variable existing, but I'm not sure that it's actually a part of pyplot's declared API (which is why I didn't add it to the stub). I think we'll have to check other projects to see if this is a common usage.

**Comment by CatNofishing** [comment]
It is good to add api about pandas and matplotlib ，This can enhance the programming experience of data science.

**Comment by Trid-collab** [comment]
An update- found now that the below option works in the Jupyter Notebook Option when I first run the notebook in VS Code , but does not show in when writing .py file 

> import matplotlib.pyplot as plt
> plt.style.use("seaborn-darkgrid") <----- when we plt. --- the style option does not show up in the autocomplete option.

**Comment by jakebailey** [comment]
Correct; the notebook is working with the live code, but these stubs haven't been updated/fixed yet to include these methods.

I'm still not super convinced that this undocumented value should be exposed, in any case, but the stubs need to be updated in general.

**Comment by ain-soph** [comment]
Add one thing. `matplotlib.cm.get_cmap` is not well declared in stubs `cm.pyi`. Actually it seems to be a quite short file and I guess a lot of things are missing?

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202130-3-march-2021
