### ISSUE TITLE
Rendering of docstrings inside VSCode is incorrect.

### ISSUE THREAD

**Issue by Liripo** [microsoft/pylance-release#730]
1. docstrings are rendered incorrectly in opencv
![image](https://user-images.githubusercontent.com/54770415/102072889-71511b00-3e3d-11eb-9504-d14f3cf58b07.png)
2. but in numpy is correct.
![image](https://user-images.githubusercontent.com/54770415/102072920-7ca44680-3e3d-11eb-88d2-1c37fc6f4ebe.png)

How should I solve this problem.

**Comment by jakebailey** [comment]
We missed closing this, but this was fixed in the previous release. cv2's format is supported.
