### ISSUE TITLE
Go to Definition doesn't work with function from tensorflow.compat.v1

### ISSUE THREAD

**Issue by xdhmoore** [microsoft/pylance-release#734]
## Environment data

I am running this on Docker (backed by WSL2 on Windows) , using VS Code:

- Docker Image: `tensorflow/tensorflow:1.15.2-p3`
- Remote - Containers extension:` v0.154.0`
- Pylance extension: `v2020.12.2`, running inside the docker container
- Python extension: `v2020.11.371526539`, running inside the docker container

To clarify, with the help of the Remote - Containers extension, my editing is taking place inside the docker container, and the Pylance and Python extensions are running inside the container as well.

## Issue

If I create the following file it runs without error. But if I hover my mouse over `RunConfig`, the Intellisense doesn't give me the signature information. Also "Go to Definition" and Ctrl+Click don't work:
```python
import tensorflow.compat.v1 as tf
tf.estimator.RunConfig()
```

Interactively, if I import the above and run `help(tf)`, that help page lists a different fully qualified namespace. If I use that instead:
```python
import tensorflow_core._api.v1.compat.v1 as tf
tf.estimator.RunConfig()
```
then the mouse-hovering, the "Go to Definition" and the Ctrl+Click all work.

## Language Server Logs

[Both the not-working and working logs](https://gist.github.com/xdhmoore/f0db16b592c4e33c010c8625fcf5758c)
If you search the logs for `dist-packages`, you can see that only in the 2nd log is the language server parsing a file at a location matching the import.

## Thoughts
I suspect that tensorflow is doing something fancy with their module definitions... Also, for what it's worth, there is more (less concise) information on my StackOverflow post [here](https://stackoverflow.com/questions/65271399/vs-code-pylance-pylint-cannot-resolve-import/65312471).

**Comment by aflyhorse** [comment]
From the ```__init__.py``` of tensorflow, it says:
```
# Since TensorFlow Python code now resides in tensorflow_core but TensorFlow
# ecosystem code (e.g. estimator, but also even tensorflow) imports tensorflow
# we need to do forwarding between the two. To do so, we use a lazy loader to
# load and forward the top level modules.
```
and then it use a "LazyLoader" to load tensorflow._api, tensorflow.python, etc. one by one.

I suspect this is a dynamic process and pylance cannot statically analyze it until runtime. Although I really hope the autocomplete is usable in tensorflow.

**Comment by xdhmoore** [comment]
The `tensorflow.compat.v1` namespace I think is specifically for accessing old TensorFlow 1 APIs while using TensorFlow 2, so it wouldn't surprise me if it does something similar.

**Comment by xdhmoore** [comment]
I found this TF1->TF2 [symbol mapping spreadsheet](https://docs.google.com/spreadsheets/d/1FLFJLzg7WNP6JHODX5q8BDgptKafq_slHpnHVbJIteQ/edit#gid=0) on the tensorflow/community github FAQ. Not sure if it is relevant or helpful. I think in 1.15.2, which is what I am using, some of the names in column B (tf_upgrade_v2) already exist.

**Comment by bschnurr** [comment]
this appears to work, using the latest `tensorflow==2.6.0`

![image](https://user-images.githubusercontent.com/1946977/133344241-5b3739fa-d0f8-4f5e-b6c5-50259680e15d.png)
