### ISSUE TITLE
How to emphasize annotated types over inferred types?

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#738]
I have had some trouble with using library `tqdm`. As mentioned in #233, using a for-loop using `tqdm` would have the loop variable be typed as "Unknown". I tried to explicitly mark a `tqdm.tqdm` instance with an `Iterable` type to see if it would make a difference, but failed.

```python
from typing import Iterable
from tqdm import tqdm as TQDM  # `tqdm.tqdm` is a class so rename it with a UPPERCASE name.


tqdm: Iterable[int] = TQDM(range(10))
# Variable `tqdm` is still typed as `tqdm`(class `tqdm.tqdm`)
# and is not considered an `Iterable[int]`.

for i in tqdm:
# I'd like to see `i` have a type of `int`, but it is marked as "Unknown".

    print(i)
```

Also, there have been similar problems with `pandas`.

```python
import pandas as pd


df = pd.DataFrame([[0, 1, 2], [3, 4, 5]])
# `pandas.DataFrame` is not a generic class.

s: pd.Series[int] = df.loc[:, 0]
# `pandas.Series` is a generic class, but `s` is typed `Series[Dtype]` here
# whereas `Dtype` is an unspecified generic type coming from the stubs.
```

It seems that whenever the type of a variable could be inferred, the annotated type would get ignored. I think I can understand the reason behind this behavior. But I still wonder if there is a way to have annotated types take effect instead of the inferred ones, especially when they are not conforming to each others?

**Comment by erictraut** [comment]
The `tqdm` package doesn't contain type annotations. Pylance will do its best to infer its types, but there are limits to type inference. If this package is one that you rely upon, please encourage the maintainers to add inline type annotations or include type stubs within the package.

The `tqdm` class does provide a `__iter__` method that returns a generator, but the first type argument of the generator (the yield type) is unknown. If it were properly typed, it would return the type `Generator[int, Any, Any]`.

When you provide a type annotation for a variable, you are declaring its type. However, when you assign a value to that variable, that that type can be further "narrowed" (i.e. made more specific). That's what's happening in your example. You're declaring that the variable `tqdm` is of type `Iterable[int]`, but then you're immediately assigning it a value that has the type of a `TQDM` object. This type is compatible with — and narrower than — `Iterable[int]`. For more information about type narrowing, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#type-narrowing).

The most straightforward way I can see to work around the issue in your case is to specify a type for the variable `i`, like this:
```python
i: int
for i in tqdm:
    print(i)
```

Another way (one I wouldn't recommend) is to use a `cast` call:

```python
tqdm = cast(Iterable[int], TQDM(range(10)))
```

The problem with your second example is not related in any way to the first. In this case, the package (pandas) does have type annotations. The expression `df.loc` has a type `_LocIndexerFrame`. According to the pandas type stubs, this class's `__getitem__` method does not allow callers to pass a tuple that includes a slice and an int entry. If you think your code is correct, this this would appear to be a bug in the pandas type stubs. You should file a separate bug on that issue in the [python-type-stubs repo](https://github.com/microsoft/python-type-stubs).

**Comment by Azureblade3808** [comment]
Thank you for the explanation and suggestion.

For `tqdm`, I'm now sticking to the first work-around you gave, and will make some more research in the `cast` trick.

For `pandas`, I'm quite sure that my sample code works, though I don't know if it is optimal. I will check if I need to file a bug for it.
