### ISSUE TITLE
Incorrect behavior with Union type alias

### ISSUE THREAD

**Issue by ElijahSink** [microsoft/pylance-release#743]
## Environment data

-   Language Server version: 2020.12.2 (pyright 6feebac9)
-   OS and version: Arch Linux 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0

## Code Snippet

```python
from typing import Union, List

ID = Union[str, int]


def foo(ids: List[ID]) -> None:
    pass


strings = ["123", "234", "345"]
ints = [123, 234, 345]

foo(strings)
""" ^^
Argument of type "list[str]" cannot be assigned to parameter "ids" of type "List[ID]" in function "foo"
  TypeVar "_T" is invariant
    Type "str" cannot be assigned to type "ID"
      "str" is incompatible with "int" (PylancereportGeneralTypeIssues)
"""
foo(ints)
""" ^^
Argument of type "list[int]" cannot be assigned to parameter "ids" of type "List[ID]" in function "foo"
  TypeVar "_T" is invariant
    Type "int" cannot be assigned to type "ID"
      "int" is incompatible with "str" (PylancereportGeneralTypeIssues)
"""
```

## Expected behaviour

No errors should be reported. The types `str` and `int` are within the definition of `ID` and so should be allowed.

## Actual behaviour

Errors are reported. Each type is considered incompatible with the other option in the union.

## Logs

```
Can be provided if needed.
```

**Comment by Azureblade3808** [comment]
Let's just assume that `strings` and `ints` are indeed lists of `str` of `int` respectively:

```
strings: list[str] = ["123", "234", "345"]
ints = [123, 234, 345]
```

If we write some logic in `foo` that make changes to the input list, the code could be:

```python
def foo(ids: List[ID]) -> None:
    # As `ids` is `List[ID]`, it can accept both `str` and `int` as its element.
    ids.append("456")
    ids.append(456)
```

Then, you will see:

```python
foo(strings)
assert strings == ["123", "234", "345", "456", 456]  # Astonishing type mismatch.

foo(ints)
assert ints == [123, 234, 345, "456", 456]  # Astonishing type mismatch.
```

The real problem is that `List`s are mutable. If `foo` only reads `ids`, `ids` can be typed as `Sequence`(an immutable protocol).

```python
from typing import Union, Sequence

ID = Union[str, int]


def foo(ids: Sequence[ID]):
    pass


strings = ["123", "234", "345"]
ints = [123, 234, 345]

# No error.
foo(strings)
foo(ints)
```

**Comment by ElijahSink** [comment]
That's interesting. Why would it be assumed that a mixed-type list is a problem? I was under the impression that 
`List[Union[str, int]]` means "each element of the list may either be a string or an int" rather than "all elements of the list must either be a string, or all must be an int." 
The latter interpretation is correct?

In reality, an array of mixed types (within the specified bounds) is perfectly acceptable to my code. That's what I mean to convey. If not `List[Union[str, int]]` what should I use?

**Comment by erictraut** [comment]
The behavior of Pylance is correct even though it might not be intuitive. For more details, [refer to this section of the documentation](https://github.com/microsoft/pyright/blob/master/docs/type-concepts.md#generic-types).

**Comment by ElijahSink** [comment]
Thanks for the clarification! The issue arises because `strings` and `ints` have narrower types than the argument `ids` is annotated as. This makes sense.

Annotating `strings` or `ints` to be `List[ID]` is another way of solving the problem.

**Comment by erictraut** [comment]
The problem is that lists are mutable. If you pass a `List[str]` to a function that's expecting a `List[Union[str, int]]`, it could append an `int` to the list, which would violate the type `List[str]`.

**Comment by ElijahSink** [comment]
Yes. Is there a more appropriate place to ask these questions than filing bug reports?

**Comment by erictraut** [comment]
GitHub recently enabled a new feature called "Discussions". I recently enabled this feature in the [pyright repo](https://github.com/microsoft/pyright). @judej, you might want to consider enabling this for the pylance-release repo as well. It provides a good forum for questions like this.

**Comment by binh-vu** [comment]
I encounter this problem today, while I solved my issue by changing type from List to Sequence.

But I wonder in general, when I just create a variable (say `a`) contains the list of string `List[str]` (for example, in csv reader function) and pass it as initial value of a class, which type is `List[Union[str, int]]`, then I won't use the variable `a` anymore (its reference is dropped after the function exists). Is it correct that we can always safely cast `List[str]` to `List[Union[str, int]]` if we can detect that the reference is dropped after passing? 

Example:

```python
def read_from_text_file(file):
    with open(file, "r") as f:
        lst = f.read().split(",")
    return List(lst)  # error

@dataclass
class List:
    items: List[Union[int, float]]
```
