### ISSUE TITLE
Running pylance from node in WSL2

### ISSUE THREAD

**Issue by chshr** [microsoft/pylance-release#745]
I am trying to figure out how to make pylance my lsp-mode server in Emacs, which is running in Ubuntu 20.04 under WSL2. To do that, I figure I should start the server either in WSL or in Win 10 itself. I wanted to run it from node, akin to pyright server, but npm does not seem to have pylance package.
How can I start pylance server without opening VS Code? I am aware that pylance uses pyright under the hood, but I want the additional functionality of pylance in my lsp server.

**Comment by erictraut** [comment]
Pylance works only with VS Code.

You can use Pyright with other editors.
