### ISSUE TITLE
import other python files in the same directory as the compiled file

### ISSUE THREAD

**Issue by Hakoyu** [microsoft/pylance-release#749]
I have multiple python projects under my workspace.
They are in different subfolders.
I want to call files from the same directory in a subfolder.
But Pylance will only be defined to the workspace directory.
I can use **"python.analysis.extraPaths"** to add absolute paths, but it's a pain in the ass.
I would like to be able to customize the location of the directory.
For example, use **"${fileDirname}"** or **"${workspaceFolder}"**, etc.

**Comment by jakebailey** [comment]
extraPaths supports relative paths to the workspace. You can put in a path `./some/path`, and the path will be rooted at the workspace. Does it not work for you?

**Comment by Hakoyu** [comment]
> extraPaths supports relative paths to the workspace. You can put in a path `./some/path`, and the path will be rooted at the workspace. Does it not work for you?

I have multiple subfolders in my workspace folder, if I use this method I need to add many relative directories of folders.
The python compiler will automatically link to other files in the same directory as the compiled file, the project will compile normally, but using Pylance will prompt an error, and the auto-completion of other files will not work.

**Comment by jakebailey** [comment]
Are you saying that you're trying to do an absolute import of the compiled code, or a relative one? If you import relatively, then there isn't a need for the import root. If you're doing absolute imports, you may be hitting #253 which impacts imports that scripts may do due to scripts having their own special import path behavior.

**Comment by jakebailey** [comment]
This issue has been open with the "waiting for info" label for over a month, so I'm going to close it. If you can answer the questions above and it's not #253, I'm happy to reopen it.
