### ISSUE TITLE
py.typed file breaks autocompletion for inline annotated libraries

### ISSUE THREAD

**Issue by nathanrpage97** [microsoft/pylance-release#752]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version:  macOS 10.15.6 
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7, 3.8

## Expected behaviour

Fully auto-completion of installed package.

## Actual behaviour

Installing a package with py.typed breaks auto-completion for libraries that are inline annotated (no .pyi files).

## Logs

```
XXX
```

## Code Snippet / Additional information

Note in this example from the wheels

```python
import example

example.  
```

This shows auto completion when py.typed doesn't exist, but shows nothing when it does exist. It seems like it is looking for the .pyi file?

[example-0.1.0-py3-none-any.whl.zip](https://github.com/microsoft/pylance-release/files/5712718/example-0.1.0-py3-none-any.whl.zip)
[example-0.1.0+no.typed-py3-none-any.whl.zip](https://github.com/microsoft/pylance-release/files/5712719/example-0.1.0%2Bno.typed-py3-none-any.whl.zip)

**Comment by erictraut** [comment]
Please refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md#library-interface).
