### ISSUE TITLE
Native Notebook: misplaced squiggly lines

### ISSUE THREAD

**Issue by gvanrossum** [microsoft/pylance-release#761]
## Environment data

```
Version: 1.53.0-insider (system setup)
Commit: c927a8015b9e26bd454d6e293bb0384aa1975d06
Date: 2020-12-18T05:27:48.567Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042
```
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.416706931
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Jupyter server running: (No idea)

## Expected behaviour

Squiggly lines show up for incorrect code (for some interpretation of "incorrect").

## Actual behaviour

After some time of use, I noticed squiggly lines showing up randomly. I have observed this a number of times.

## Steps to reproduce:

Sorry, I don't know. But here's a GIF. Note the erratic squiggle under "impo" and "math" (but not "rt") and in the second cell a bunch more.

![image](https://user-images.githubusercontent.com/2894642/102706038-3c7d0380-4243-11eb-8eac-bd6ce8e6cfbe.png)

**Comment by jakebailey** [comment]
The Jupyter extension had its update today; is there any chance you could test again to see if this still happens? There were a number of fixes there that could have impacted this.

**Comment by gvanrossum** [comment]
I'll test later, thanks for the note!

**Comment by gvanrossum** [comment]
I'm sorry, I lots track of the files I used to repro this. I trust that it's been fixed. Sorry for being a lame user. :-(
