### ISSUE TITLE
Add a command that fills out the issue template

### ISSUE THREAD

**Issue by gvanrossum** [microsoft/pylance-release#762]
When  I open a new bug I am asked for a bunch of version info that requires going back and forth copying and pasting versions of OS, vscode, extensions, pylance, etc. Why not add a little command to vscode that collects all these versions and prints them in the Markdown form the issue tracker requires? And then advertise that in the new issue template.

**Comment by bschnurr** [comment]
Here is something similar C# does using the clipboard to help users report issues.

https://github.com/OmniSharp/omnisharp-vscode/pull/2845
https://github.com/OmniSharp/omnisharp-vscode/pull/2503

**Comment by jakebailey** [comment]
Much better would be to encode the text into the new issue URL; this is what Go does for the `go bug` and `gopls bug` commands.

**Comment by gvanrossum** [comment]
Whatever, just save me from hunting down half a dozen of different pieces of info by clicking around in the UI and copying them to GitHub one at a time. :-)

**Comment by jakebailey** [comment]
Of course, just throwing that there before I forget. 🙂

**Comment by gvanrossum** [comment]
Huh, I just found a "Report issue" menu item under Help in VS Code Insiders. That solves my problem. Sorry!

**Comment by jakebailey** [comment]
That may help for most, but I'm actually going to leave this open at the moment (if you don't mind) as we're working on a version which will auto-populate our template here with all of our required info as well as switch things over to the right logs, etc.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.1.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202111-13-january-2021
