### ISSUE TITLE
Type inference override

### ISSUE THREAD

**Issue by nemec** [microsoft/pylance-release#765]
I'm not sure if this is a bug or a feature request, but in order to support auto-completion for argparse (see #628) in other language servers (the default vscode one, Microsoft I think?) I like to create a marker class defining the acceptable properties and then manually annotate the type signature of the `parse_args` method with the class, so it's used when auto-completing. Pylance, however, ignores my manual annotation and continues to assume the type is the return type from `parse_args` (which is `Namespace`).

Note: I don't expect Pylance to special-case code for argparse. I simply want it to use my `Args` class as the type for all inference decisions, even if I make a mistake and my `Args` class gets out of sync with how I've actually configured my argparse parser.

This is a minimal reproduction:

```python
import argparse

class Args:
    command: bool = None

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--command', action='store_true')
    args: Args = parser.parse_args()
```

The inferred type is `Namespace`, but it would be nice if it said `Args` (however, the default language server also shows `Namespace` despite the annotation, so this is less important than auto-complete support):
![Screenshot from 2020-12-22 03-32-06](https://user-images.githubusercontent.com/136378/102873225-75190a80-4406-11eb-9094-5aa92f24f2b2.png)

This is the auto-complete output from the Pylance language server. There is no suggestion for `command`.
![Screenshot from 2020-12-22 03-32-23](https://user-images.githubusercontent.com/136378/102873233-7813fb00-4406-11eb-8431-4a4038f64dcb.png)

This is the auto-complete output from the default language server, which includes `command` as a suggestion:
![Screenshot from 2020-12-22 03-35-06](https://user-images.githubusercontent.com/136378/102873477-cde8a300-4406-11eb-865f-6141c54abede.png)

**Comment by erictraut** [comment]
There's no type inference applied when evaluating the type of the expression `parser.parse_args()`. Inference is used only in cases where a type declaration (i.e. an explicit annotation) is not present, and the type checker needs to infer the type based on other contextual information. In this case, the types are explicitly declared in the `argparse.pyi` stub file.

The problem here is that you are not specifying a namespace argument to `parse_args()`. With the following small change, it will work as you are expecting:

```python
args = parser.parse_args(namespace=Args())
```

**Comment by nemec** [comment]
I see, thank you. That does set the tooltip properly.

Maybe this is beyond the scope, but do you know if it's possible to do this with multiple subparsers (e.g. `git add` becomes `AddArgs()`, `git commit` becomes `CommitArgs()`). This was easy enough to do after the fact by manually "casting" with an annotation, but with the `parse_args` solution I won't know the true type until after the arguments are parsed.

**Comment by erictraut** [comment]
Sorry, but the only thing I know about `parse_args` is from the research I did to answer this question. You'd have to ask someone who is more familiar with this interface.

**Comment by nemec** [comment]
I appreciate the help anyway! I guess it's not possible to override the type that Pylance thinks a variable is, then.
