### ISSUE TITLE
pylance adding problems to my project

### ISSUE THREAD

**Issue by r3vert** [microsoft/pylance-release#766]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: Macos Big Sur version 11.1
-   Python version: Python 3.9.0 64-bit (venv)

## Expected behaviour

I should not see any problems about files from the extension

## Actual behaviour

I am getting 50 or more problems from /Users/*******/.vscode-insiders/extensions/ms-python.vscode-pylance-2020.12.2/dist/bundled/stubs/matplotlib/__init__.pyi
(the asterisks are my username which i do not want to share 
## Logs
No logs
```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
Are you getting problems for these even when the file is unopened? What are your settings? Are you using a type checking mode other than the default? What are the problems themselves?

**Comment by r3vert** [comment]
I tried changing the location of the project and it seemed to fix the issue.
I actually don't get this problem. should I close the issue?

**Comment by jakebailey** [comment]
If you can't reproduce it anymore, then close it, yes. I'm wondering if maybe you opened up your home directory such that we were treating the bundled files as "in the workspace" or something.

**Comment by r3vert** [comment]
This issue is closed because I cannot reproduce it any more. if you have the same issue reopen thisissue
