### ISSUE TITLE
Incorrect problem report when analyzing a recursive function

### ISSUE THREAD

**Issue by hoechenberger** [microsoft/pylance-release#768]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: macOS Big Sur 11.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6 from `conda-forge`

## Expected behaviour

No problem should be reported.

## Actual behaviour

Pylance reports an issue:
```
Function with declared type of "dict[Unknown, Unknown]" must return value
  Type "None" cannot be assigned to type "dict[Unknown, Unknown]"
```

## Code Snippet / Additional information

```python
def foo(count: int = 5) -> dict:
    if count > 0:
        count -= 1
        foo(count)
    else:
        return(dict(foo='bar'))
```

**Comment by erictraut** [comment]
The error message is correct for the sample you provided above. There is a code path where `None` is returned, so the proper return type annotation should be `Optional[dict]` (or more properly `Optional[Dict[str, str]]`).

Did you perhaps intend to include a return statement in the `if` clause as well?

**Comment by hoechenberger** [comment]
Hello @erictraut,

> Did you perhaps intend to include a return statement in the `if` clause as well?

**ouch**, now this is truly embarrassing. Yes, yes indeed I forgot the `return`. Thanks for pointing this out. Have a nice day, and Happy Holidays!
