### ISSUE TITLE
Import "requests" could not be resolved from source

### ISSUE THREAD

**Issue by MrEscape54** [microsoft/pylance-release#77]
## Environment data

-   Language Server version: Pylance language server 2020.6.1
-   OS and version: MS Windows 10 Pro - 10.0.18362 Build 18362

-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.8.2

## Expected behaviour

(django running on a venv) imports from third-party modules should be resolved from source

## Actual behaviour

(django running on a venv) It seems that third-party modules can not be resolved from source

## Logs

```
{
	"resource": "/c:/Users/............/views.py",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 4,
	"message": "Import \"requests\" could not be resolved from source",
	"source": "Pylance (reportMissingModuleSource)",
	"startLineNumber": 12,
	"startColumn": 8,
	"endLineNumber": 12,
	"endColumn": 16
}
```

## Code Snippet / Additional information

pipfile (generated by pipenv)
```python
[packages]
requests = "*"
```

views.py

```python
import requests
```

**Comment by jakebailey** [comment]
Is `requests` definitely installed in the environment that's been selected? Just being in the config isn't enough.

Can you enable trace logging and provide that log instead? That is a diagnostic log, but I'm interested in the search paths being used.

**Comment by MrEscape54** [comment]
You hit the jackpot.!! I was using a different environment...sorry

Thank you very much for your help!!

**Comment by jakebailey** [comment]
Thanks for confirming. I'm glad the diagnostics pointed out the issue, at least. 😄
