### ISSUE TITLE
start setting header with pylance instead of python

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/pylance-release#771]
Only one setting starting with pylance and others are nested in python, and it is very hard to find them when modify .josn setting file. Please consider distinguishing them.

![image](https://user-images.githubusercontent.com/33796896/103098307-4bafd880-45d8-11eb-9a6a-44e9f7d5efe5.png)

**Comment by savannahostrowski** [comment]
Thanks for this feedback. Given that we are now bundled with the Python extension, we will not be updating the setting name space at this time.
