### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by scienceLabwork** [microsoft/pylance-release#772]
Issue Type: <b>Bug</b>

Pylance is not poping up when I write a code in python.

Extension version: 2020.12.3-pre.1
VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|23, 17, 14|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id 7adae825-f008-4e21-a9fb-4c982a80d485|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
vstry914:30236575
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459:30237187

```

</details>

**Comment by bschnurr** [comment]
Can you post what you see in the "Python Language Server" output window?

**Comment by scienceLabwork** [comment]
![Screenshot 2020-12-25 at 11 38 21 AM](https://user-images.githubusercontent.com/51542683/103122317-b2e78e80-46a5-11eb-809b-eaffc31cb162.png)
Pylance Only.

**Comment by scienceLabwork** [comment]
Thanks For support! Issue Solved after trying too many solutions.
