### ISSUE TITLE
Variable Explorer

### ISSUE THREAD

**Issue by aster94** [microsoft/pylance-release#775]
Hello,

Many python users are used to Spyder, which provide an awesome variable explorer out of the box.
![image](https://user-images.githubusercontent.com/21184718/103151149-cd8c3700-477b-11eb-8c25-22cb44ca7ee0.png)

The VSCode's python team did a great work back in April 2019 with the variable explorer for Jupyter notebook ([link](https://devblogs.microsoft.com/python/python-in-visual-studio-code-april-2019-release/))

~~Would it be possible to use a variable explorer, as easily as it is used in Spyder, also in a normal `.py` file?~~

~~Right now the user is forced to convert between python script file and jupiter notebook~~

**Comment by judej** [comment]
@aster94, thanks for the suggestion. Will add this to our feature requests.

**Comment by jakebailey** [comment]
I just wanted to revisit this; @aster94, are you expecting this to be coming from live data in a debugging session, or populated with statically available information? Pylance does not integrate with running code, so this may not be something we can do (but would be a feature added to the Python extension, say in the debugger, or something).

**Comment by aster94** [comment]
Statically available information after the running of the whole file would be a good starting point (and in a later release after the run of a selection of code or cell)
Also IMHO the data viewer should be improved to be more compelling compared to the Spyder's one

But please, consider other suggestions from different user's case

**Comment by jakebailey** [comment]
The data viewer meaning the existing one in the Jupyter extension? I'm wondering if this should be moved to their repo so you can give feedback there; Pylance isn't involved with runtime data.

**Comment by savannahostrowski** [comment]
Without more information, it's difficult for us to prioritize or reason about the feature request. Closing this for now. If you can provide more info, I'll reopen.
