### ISSUE TITLE
pandas: Incorrect parameter type for `pandas.Index.get_level_values()`

### ISSUE THREAD

**Issue by DannyNemer** [microsoft/pylance-release#780]
## Environment
-   Language Server: v2020.12.2
-   OS: macOS v10.15.6
-   Python: v3.7.9
-   Pandas: v1.1.5 (latest)

## Expected behavior

Recognize that the parameter `level` for [`pandas.Index.get_level_values(level)`](http://pandas.pydata.org/docs/reference/api/pandas.Index.get_level_values.html#pandas.Index.get_level_values) can be of type `str` or `int`.

## Actual behavior

Pylance incorrectly reports that the parameter `level` for `pandas.Index.get_level_values(level)` must be a string:

<img width=500 src=https://user-images.githubusercontent.com/170023/103179824-b2d1c500-4844-11eb-88d4-b41b08cdb07f.png>

## Code Snippet

Should not return errors:
```python
import pandas as pd

pd.Index(['ds']).get_level_values(0)
```

---

Please let me know how I can improve this bug report because many more will follow (all for typeshed issues). Is this the best repo for such bug reports? (I am following the precedent of Pandas type issues in the release notes.)

**Comment by jakebailey** [comment]
https://github.com/microsoft/python-type-stubs is the new canonical source for these stubs, for reference.

**Comment by DannyNemer** [comment]
> [microsoft/python-type-stubs](https://github.com/microsoft/python-type-stubs) is the new canonical source for these stubs, for reference.

@jakebailey Thank you! Would it be more efficient for me to create these issues in that repo? Or, does that repo not receive the same degree of visibility? I'm happy to do whichever is easiest for you. 🙂

**Comment by jakebailey** [comment]
That's a great question, because on one hand we want to close issues here so people know we shipped the stubs in Pylance, but on the other, it'd be nice for them to be in the repo they are fixed in... I don't know if we have a solid answer yet, that repo is very new (and then we all went on break for the holidays).

**Comment by jakebailey** [comment]
No harm in having these here at the moment, transferring is easy.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202132-17-march-2021
