### ISSUE TITLE
Autocompletion as fast and powerful as Kite

### ISSUE THREAD

**Issue by martinetmayank** [microsoft/pylance-release#783]
I have used kite for couple of months and that was way fast (it takes memory too) and the completion was too strong (it autocompletes multiple lines as once).

I wish of using this feature in PyLance (which indeed requires low memory usage).

**Comment by judej** [comment]
Thanks for the suggestion @martinetmayank. We are planning several enhancements for in the future. Please let me know if there are other questions or suggestions, please let me know.

**Comment by savannahostrowski** [comment]
What are the specific features that you are interested in @martinetmayank?

**Comment by martinetmayank** [comment]
Let say I want to import a library 
`from matplotlib import pyplot  as plt`

If I use Pylance, it autocompletes a word while importing, not the whole sentence. I've to press `tab` write couple of letter then `tab` and it goes on.

While in KITE, I only have to write `from matplotlib import`  and hit TAB, it autocompletes it to `from matplotlib import pyplot  as plt`
Obviously it displays other options which can be selected by using arrow keys, but it keep in memory the most used methods and their ways of importing it.

**Comment by savannahostrowski** [comment]
@martinetmayank Thanks for the info. This functionality is something that we'd expect IntelliCode to handle. You can file a feature request over on their issue tracker https://github.com/MicrosoftDocs/intellicode/issues.
