### ISSUE TITLE
False positive report of an "unbound variable"?

### ISSUE THREAD

**Issue by paxcodes** [microsoft/pylance-release#786]
## Environment data

-   Language Server version: v2020.12.2
-   OS and version: 10.14.6
-   Python version: Python 3.8.2

## Expected behaviour

Given the following code, pylance shouldn't report `some_var` as an "unbound" variable.

```python
some_var = None

def func():
    if not some_var: 
        some_var = "some_value"
    return some_var
```
## Actual behaviour

Getting message from pylance `"some_var" is unbound`

## Code Snippet / Additional information

![Screen Shot 2020-12-28 at 2 41 35 PM](https://user-images.githubusercontent.com/13646646/103247185-dd8e4d00-491a-11eb-928c-d50aee7477d0.png)

**Comment by paxcodes** [comment]
Given I can replicate this in repl.it, I really think there's simply a knowledge gap on my part re: what's going on. Closing this.

**Comment by erictraut** [comment]
Perhaps you meant to include the statement `global some_var` within your function? That will allow it to access the variable of that name defined within the global scope. Without this statement, the Python interpreter (and Pylance) will assume that you're referring to a local variable, and it hasn't been assigned a value before it is accessed.

**Comment by paxcodes** [comment]
@erictraut Thank you for taking the time to point me in the right direction. That is exactly what I'm missing.
