### ISSUE TITLE
Auto-complete and suggestions not working as expected

### ISSUE THREAD

**Issue by shubhamdevgan** [microsoft/pylance-release#787]
Recently started using Pylance pretty happy with features, but Auto-complete and suggestions don't work as excepted , when using 'Jedi' as language server I get proper suggestions about Django models fields i.e fields present in model but when using 'Pylance' as language server I don't get suggestions.

Suggestions I get using Jedi:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28834720/103276288-23671600-49ec-11eb-9ae7-a09667cc0d63.gif)

Suggestions I get using Pylance:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/28834720/103276433-86f14380-49ec-11eb-8c62-6dab287415bf.gif)

**Comment by Alonoparag** [comment]
I encounter the same issue, Jedi working fine, pylance sends no suggestions at al

**Comment by pcgeek86** [comment]
I'm having the same problem. Pylance doesn't work, but Jedi returns suggestions just fine.

**Comment by ryancausey** [comment]
I'm having this same issue with my Django projects since VSCode started defaulting to Pylance. Original comment here: https://github.com/microsoft/vscode-python/issues/16188#issuecomment-840817828

**Comment by judej** [comment]
Thanks for the request. Jedi is able to provide completions since it can interrogate the code.  Pylance does not support that and there are unfortunately, to plans to support executing third party code.
