### ISSUE TITLE
Unimplemented abstract method is not reported.

### ISSUE THREAD

**Issue by giyyapan** [microsoft/pylance-release#788]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: OSX 10.13.3
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8

## Expected behaviour&Actual behaviour

This code snippet should resulting an error about MixinA not implemented method a, but it doesn't.

## Code Snippet / Additional information

```python
import abc

class InterfaceA(abc.ABC):
  @abc.abstractmethod
  def a(self) -> None: print('InterfaceA.a')

class MixinA(InterfaceA):
  pass

ab = MixinA()
ab.a()
```

I also tried using Pyright alone, Pyright would report this error correctly:
![image](https://user-images.githubusercontent.com/3479453/103291720-5aa6e880-4a27-11eb-8939-4f7dd8afd10d.png)

Thank youl.

**Comment by erictraut** [comment]
By default, the `python.analysis.typeCheckingMode` is set to "off" in Pylance. In Pyright it defaults to "basic". If you enable basic type checking in Pylance, you will get the desired behavior.

**Comment by giyyapan** [comment]
Thanks for for explaination.
I bilieve I did set the `python.analysis.typeCheckingMode` to "basic" when I report this issue, but I can confirm it's fixed with latest version of Pylance now, so I'm closing this issue now.

**Comment by s-banach** [comment]
Why do you need to instantiate `MixinA()` to see the type warning?
The only reason I'm trying to use `@abstractmethod` is because I thought it would allow me to check the source code where the classes are defined.

**Comment by erictraut** [comment]
> Why do you need to instantiate MixinA() to see the type warning?

`MixinA` could be subclassed, and the subclass could provide the implementations for any remaining abstract methods, so it wouldn't be appropriate to emit an error. If you add a `@final` class decorator to `MixinA`, that tells the type checker and the runtime that the class cannot be further subclassed. In this case, pylance will emit an error telling you that some of the abstract methods are missing an implementation.
