### ISSUE TITLE
Code unreachable for base class type annotation that raises NotImplementedError

### ISSUE THREAD

**Issue by seminumber** [microsoft/pylance-release#790]
## Environment data

Language Server Version :2020.12.2 (pyright 6feebac9)
OS: Ubuntu 18.02 / Windows 10
Python version: 3.8 

## Expected behavior

If the following conditions are met (see code snippet below) :
   1. a variable is annotated as a class
   2. its member methods raises NotImplementedError
   3. another variable is assigned to the return value for the method

Then the code below that line become unreachable.

If there is any class that explicitly (not via factory or reflection) derived and implemented it, the code become reachable again.

## Actual behavior

The code should become reachable, as quite a few third party library offer a base class.

eg. original case that made me discover this was ```gym.Env``` class (in OpenAI Gym) and the variable assignment to
``` x: np.ndarray = env.reset()```

## Logs

The below are logs from Python language server

```
[Info  - 6:50:19 PM] Pylance language server 2020.12.2 (pyright 6feebac9) starting

(skipping a few lines)

Background analysis message: setFileOpened
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
[FG] parsing: /[deleted]/scratch.py (1ms)
[FG] binding: /[deleted]/scratch.py (0ms)
Background analysis message: getSemanticTokens
[BG(1)] parsing: /[deleted]/scratch.py (1ms)
[BG(1)] binding: /[deleted]/scratch.py (1ms)
Background analysis message: getSemanticTokens
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
Background analysis message: analyze
[BG(1)] analyzing: /[deleted]/scratch.py ...
[BG(1)]   checking: /[deleted]/scratch.py (1ms)
[BG(1)] analyzing: /[deleted]/scratch.py (1ms)
Background analysis message: resumeAnalysis
Background analysis message: getDiagnosticsForRange
Background analysis message: getDiagnosticsForRange
```

## Code Snippet / Additional information

```
class Foo:
    def foo(self):
        raise NotImplementedError

def foo_test(a: Foo):
    x: int = a.foo()
    a.foo()  # pylance: code unreachable

# Uncommenting below, the code is reachable again
# class Bar(Foo):
#     def foo(self):
#         return 42

# foo_test(Bar())
```

Edit: corrected misspelling, removed account names

For those who want to bypass the issue, the below snippet may help (in case you cannot edit Foo).

```
import typing

class _(Foo):
    def foo(self) -> typing.Any:
        return None
```

**Comment by erictraut** [comment]
If the class is abstract (i.e. it relies on subclasses to override certain methods), it should derive from ABC, and the methods in question should be decorated with `@abstractmethod`.

See https://github.com/microsoft/pylance-release/issues/31 for more details.

**Comment by seminumber** [comment]
> If the class is abstract (i.e. it relies on subclasses to override certain methods), it should derive from ABC, and the methods in question should be decorated with `@abstractmethod`.

I would disagree. It would be nice if it could, but the code has perfectly fine runtime behavior obeying python's rule (meaning without using reflection) -- and the base class code was not my code after all, and it does not make sense if one has to edit third party packages. Unless it is marked as `@typing.final`, any class method is assumed to be overriden, which is a common behavior in other languages as well (e.g. sealed class in .NET, final in Java). The above code passes pyright's type check, and this makes me think it is due to the wrong assumption of code execution path in pylance. The issue only happens when you assign a variable the returned value, which makes it inconsistent as well.

Still then, is it considered as a feature request? (and yes, it was a duplicate. Sorry I couldn't find it)

**Comment by erictraut** [comment]
I'm not sure what feature you're asking for.

It is legitimate for methods to raise exceptions, and code that calls these methods sometimes rely on the fact that the code after the call is unreachable. A static analyzer shouldn't assume that a subclass is going to later override the method and provide different behavior unless it is given some hint that it is designed to be overridden. Such an assumption would create false positive errors in other cases, which is arguably worse than the small annoyance you're experiencing with grayed-out text in your code.

There are limits to what a static analyzer can do with untyped library code, especially when that code is not following basic standards of programming like marking abstract methods as abstract. If this is a library that you use often, I recommend that you contact the maintainer and ask them to add minimal type annotations and/or properly mark classes and methods as abstract where appropriate.

**Comment by seminumber** [comment]
I'm also not completely sure about how to concretely formulate the feature. Some naive ideas are thinking of raising `NotImplementedError` serve as a hint for later the method are being updated (by either attribute assignment or derivation). The exception has longer tradition than `@abstractclass` as they may be in Python 2 as well (or maybe not) -- so maybe the name for the feature are maybe "support for `NotImplementedError`". Another way is the internals of the method calls should not be used for evaluating the code path (and in that case, the feature may be "Type inference should be separated from runtime inference". But there should be side effects that I haven't come up with and I'll be thinking over what would it be a better idea.

Code unreachable in other languages, at least what I have experienced, doesn't look over other method -- quite often due to the simplicity but also because it is considered a runtime-behavior after all. Suppose we are in a single method. If there's a statement after return, yes it's unreachable. If there's a statement below exception and no catch, the code below are unreachable. 

But if there's a method call that may raise an exception, is the code below that call should be marked unreachable when the certain conditions are met? I'd rather say no, it's a runtime behavior and not the responsibility of the static analyzer. For instance, if the static analyzer meets `open('##!$.^_any invalid filename')` so that the statement should always fail, it doesn't make sense for an analyzer to capture these. Maybe some have pattern recognition and provides suggestion for the function `open`, but at least it's not used for evaluating code path. Likewise, if there's a method call that always raises an exception for sure, I'd say maybe you can, but would not be bothered by the fact that the tool doesn't look into our method.

In a compiled language, raising an exception for a method means the programmer wants it to leave for the runtime, and suppress compiler errors. Situation in python is not much different in my view. Because types are usually not annotated, pylance should look into the internal implementation and grasp the idea of the method signature that was intended. And when successful, the python method has the type check that general compiled langauges enjoy. And that's what I expect for pyright/pylance (and maybe a few surprise of new features). For the code above, I would go like "the method signature are Callable[[Foo], Any], and the implementation is to raise NotImplementedError". Evaluation of code paths is a different story.

Besides, static code analyzers are rule-based check tool. If the behavior is expected, then the same behavior should be expected as well for non-assignment case. In the code sample, without assigning `x=a.foo()`  but simply calling `a.foo()` twice doesn't make the latter unreachable. If the former was not a bug, the latter should be.

So I wonder, is it a bug that you put lower priority and will not fix, or is it an intended behavior that follows the spec whose side effects will be relieved by a new feature (like detecting `NotImplementedError`). In case of former, I'll leave the issue open. If the latter, I'll close the issue and maybe some time come up with an idea and put a feature request then.

**Comment by erictraut** [comment]
If the code is in a library that you use often, I recommend that you encourage the library maintainer to 1) add type annotations, and 2) add the use of ABC & abstractmethod, or 3) (preferably) both. The only way that Python libraries will improve in quality is if users demand such improvements.

**Comment by seminumber** [comment]
And that's why I encourage pylance to be better because I want to use pylance for my major code analysis tool -- although great in general, issues have been encountered (like this).  Typing is still an optional feature in python, and it doesn't seem a valid argument that my tool doesn't support 'xxx' so please use 'yy' instead. And it could be more than just graying out later. You can see many examples how an assumption of unreachable code (such as UB in C++) makes unintentional consequences.

I do have a bypass and perhaps better way is using a custom type stubs. Anyway, it doesn't seem you think pylance should fix it so I assume the latter in my previous question. Thanks for the discussion. Closing.
