### ISSUE TITLE
Publish extension to Open VSX

### ISSUE THREAD

**Issue by easthighNerd** [microsoft/pylance-release#791]
It would be fantastic if this extension was published to <a href="https://open-vsx.org/">Open VSX</a> so that people <i>(including myself)</i> using <a href="https://vscodium.com/">VSCodium</a> or <a href="https://github.com/flathub/com.visualstudio.code-oss">Code - OSS</a> would be able to easily install and use this extension.

**Comment by Tatsh** [comment]
Already tried this in Code-OSS. Pylance source checks to make sure it is run on VS Code specifically. This is due to the license not allowing use of Pylance in anything that is not the official VS Code build.

**Comment by jakebailey** [comment]
#746
