### ISSUE TITLE
pandas: Missing function annotation for pandas.DataFrame.convert_dtypes

### ISSUE THREAD

**Issue by devon-ge** [microsoft/pylance-release#792]
Pylance does not include annotation for [pandas.DataFrame.convert_dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.convert_dtypes.html). Instead, there is a `convertDTypes` function in frame.pyi.
I haven't tested whether `convertDTypes` is equivalent to convert_dtypes.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202132-17-march-2021
