### ISSUE TITLE
False "code is unreachable"

### ISSUE THREAD

**Issue by hilayc9** [microsoft/pylance-release#794]
When you write a python code like the following:
```
if sys.platform == 'win32':
    #some code here
else:
    # some other code
```
It marks the code as "unreachable" depends on whether you are writing in Linux or Windows.
I believe the warning shouldn't appear on that case.

**Comment by erictraut** [comment]
Please refer to https://github.com/microsoft/pylance-release/issues/470

**Comment by hilayc9** [comment]
Sorry, I tried looking for "sys.platform" and I didn't search for "os.name".

**Comment by hilayc9** [comment]
@erictraut I tried it and I don't find it as a good solution.
I can understand from your comment on #470 that this is intended but consider it as a feature request.
When I used `{"pythonPlatform": "All"}` it just swaps the unreachable part between the 'if' and 'else' statements.

Please make another option for "Any" so the sys.os / sys.platform won't show a warning, it is very confusing since the code works as I expect it and I just need to ignore this warning.

Would be appreciated.
Thank you

**Comment by erictraut** [comment]
You won't see a warning for unreachable code. You will simply see that some code is "grayed out". If you're seeing a warning, then something else is wrong, and we should investigate that.

**Comment by erictraut** [comment]
I've changed "pythonPlatform" to accept a value of "All". When it receives this configuration value (or any other string value that it doesn't understand), it will assume that all platforms are supported. So that should eliminate the "grayed out" code in this case. If you are seeing an actual warning, please let me know because that shouldn't happen.

**Comment by hilayc9** [comment]
@erictraut by warning I mean grayed out, there isn't an actual warning of course.
I'm experiencing something different than your description.
This is what I get when I use "All"
![image](https://user-images.githubusercontent.com/25383191/103553502-3418ff80-4eb6-11eb-817d-c83491004b75.png)

This is the json configuration file
```
{
	"pythonPlatform": "All"
}
```

**Comment by erictraut** [comment]
Yeah, I just checked in the [change for "All"](https://github.com/microsoft/pyright/commit/602aefa1d5edcec353ad2f7628d27e22cbfa0a24). You won't see the updated behavior until the next release of pylance.

**Comment by hilayc9** [comment]
Ok got it. Thank you very much!

**Comment by jakebailey** [comment]
The above change is in 2021.1.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202110-6-january-2021
