### ISSUE TITLE
Improve auto import for common abbreviations

### ISSUE THREAD

**Issue by MarcSkovMadsen** [microsoft/pylance-release#8]
Hi

First of all thanks for the great work on Pylance. Works really well so far for me (10 minutes of testing :-))

I work in data science in we have common abbreviations for `pandas`, `numpy`, `panel` etc. I would like the auto importing to work for that.

pandas -> pd
numpy -> np
panel -> pn
holoviews -> hv

# Solution

Either automatically recognice common abbreviations. Or alternatively auto import for example pandas and then suggest an abbreviation.

**Comment by heejaechang** [comment]
just FYI, abbr is not supported in auto-import, but code action supports those.

![abbr](https://user-images.githubusercontent.com/1333179/86221862-4fd3cf80-bb3a-11ea-904c-54006d1afb8d.gif)

**Comment by heejaechang** [comment]
for now, we didn't include abbr in "auto import" but included them only in code action. we are worrying about the completion list being too bloated. but will leave the issue open for now to get some more feedback. for now, use code action for common abbreviations.

**Comment by cdce8p** [comment]
I was thinking about this issue recently. Like many others, I tend to have some abbreviations I use quite frequently for imports. Could adding a new setting fix it? A suggestion:
```json
[{
    "suggestion": "pd",
    "import": "import pandas as pd",
    "enabled": true,
}, {
    "suggestion": "dt",
    "import": "from datetime import datetime as dt",
    "enabled": true,
}]
```

This syntax would allow anyone to customize their auto-import suggestions, while keeping the completion list clean for everybody else. Additionally a user could use this to disable really common mistakes.
This would also address #210

**Comment by jakebailey** [comment]
Created #735 for that suggestion, but the original issue here to support these common abbreviations has been done for a bit.
