### ISSUE TITLE
Code Helper Renderer uses 100% of CPU once Pylance is enabled 

### ISSUE THREAD

**Issue by wineapp** [microsoft/pylance-release#80]
Issue Type: **Performance Issue**

When Pylance is enabled, the process Code Helper (Renderer) takes up 100% of the CPU

## Environment data

[Info  - 6:10:50 AM] Pylance language server 2020.6.1 starting
[Info  - 6:10:50 AM] Server root directory: /Users/mano.k/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 6:10:50 AM] Background analysis root directory: /Users/mano.k/.vscode/extensions/ms-python.vscode-pylance-2020.6.1/server
[Info  - 6:10:50 AM] Background analysis started

-   Language Server version: 2020.6.1
-   VSCode: 1.46.1
-- Electron: 7.3.1
-- Chrome: 78.0.3904.130
-- Node.js: 12.8.1
-- V8: 7.8.279.23-electron.0
-- OS: Darwin x64 19.5.0

-   OS and version: MacOS 10.15.5
-   Python version: 3.8.2 
-   Python packages installed:
-- wheel
-- aiohttp==3.6.2
-- requests==2.23.0
-- websockets==8.1
-- python_graphql_client==0.2.0
-- fuzzywuzzy==0.18.0
-- python-levenshtein==0.12.0

## System Info:

Item | Value
-- | --
CPUs | MacBook Pro (13-inch, 3.3 GHz Dual-Core Intel Core i7)
GPU | Intel Iris Graphics 550 1536 MB
Memory (System) | 16 GB 2133 MHz LPDDR3
Screen Reader | no
VM | no

**Comment by judej** [comment]
@wineapp, sorry to hear about the issue. Is this issue consistent? Is it at startup? If so, how for how long does it peg the CPU? And is there a repo we can and use to reproduce this problem?

**Comment by erictraut** [comment]
We fixed an issue in the latest release that could explain what you're seeing. Please try the latest version and let us know if this still repros. Thanks!

**Comment by wineapp** [comment]
@erictraut Yes, this issue no longer exists with the latest build. Thanks!
