### ISSUE TITLE
"Presentation" is unknown import symbol 

### ISSUE THREAD

**Issue by nkmrhdm** [microsoft/pylance-release#800]
## Environment data

-   Language Server version: 2020.12.2
-   OS and version: macOS Big Sur 11.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 (Anaconda 1.7.2)

## Behaviour

I use the module `Presentation` from the library `python-pptx` and getting following error while importing, also autocomplete is not working. 

`from pptx import Presentation`
`"Presentation" is unknown import symbolPylancereportGeneralTypeIssues`

**Comment by judej** [comment]
@nkmrhdm, I tried this and was able to import the `Presentation` module. Could you make sure your virtual env is set up and activated?

If you are still having issues, could you please add your logs and also the level of typechecking you are using? IOW the value of `python.analysis.typeCheckingMode` in your settings file?

**Comment by jakebailey** [comment]
@nkmrhdm It's been a month or so since we asked the above and marked the issue as needing more info. As far as I am aware, @judej wasn't able to reproduce it when installing the pptx package and doing the same.

More info, trace logs, etc, would be helpful, and we can reopen this issue as needed.

**Comment by gsmedley** [comment]
Hi,

I see the same thing:
<img width="719" alt="Screen Shot 2021-12-31 at 4 52 52 PM" src="https://user-images.githubusercontent.com/30830/147838737-114cb2c4-8cd7-445b-ae1e-4677b5ab308e.png">

That's with _typeCheckingMode: basic_.

**Comment by erictraut** [comment]
Which version of python-pptx do you have installed? I'm not able to repro this with the latest published version (0.6.21).

**Comment by gsmedley** [comment]
Python 3.8.12
python-pptx 0.6.21
