### ISSUE TITLE
PyLance import of inner packages works incorrectly

### ISSUE THREAD

**Issue by wvolkov** [microsoft/pylance-release#801]
## Environment data

-   Language Server version: Pylance language server 2020.12.2
-   OS and version: Windows_NT x64 10.0.19041
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.9
-   WSL: Ubuntu 20.04
-   VS Code: 1.52.1

## Expected behaviour

1. pip install asyncpg
2. import asyncpg
3. pylance will show class PosrtgesError after hitting psycopg.Post at editor

## Actual behaviour

3. pylance intellisence doesn't seem to find that class:
![inner import](https://user-images.githubusercontent.com/49549154/103521954-affd5280-4e8a-11eb-95fd-cb1e1081db59.png)

while it still can show that via inner class exceptions:

![inner import via inner module](https://user-images.githubusercontent.com/49549154/103522014-c99e9a00-4e8a-11eb-92e3-85fedbbcf972.png)

## Code Snippet / Additional information

```python
import asyncpg
asyncpg.PostgresError
```

If we look at inner structure at asyncpg module ([available at github here](https://github.com/MagicStack/asyncpg/blob/master/asyncpg/exceptions/_base.py)) 
there is a mention of that class via __all__ reference but with tuple, not list:

```python
# ... at 13 line
__all__ = ('PostgresError', 'FatalPostgresError', 'UnknownPostgresError',
           'InterfaceError', 'InterfaceWarning', 'PostgresLogMessage',
           'InternalClientError', 'OutdatedSchemaCacheError', 'ProtocolError',
           'UnsupportedClientFeatureError')
# ...
```
maybe that is the way of it is not working properly.

**Comment by jakebailey** [comment]
Curious, I think a tuple should work. If you go and edit the file to be a list, does it work?

@erictraut Do you know off the top of your head if we are strict about it only being a list?

**Comment by erictraut** [comment]
We support lists and tuples. You can find a list of all supported idioms [here](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md#library-interface).

**Comment by jakebailey** [comment]
Thanks for the clarification. We'll have to look closer at this one, then.

**Comment by wvolkov** [comment]
I found out that the same issue has happened with ```numpy``` library as well:

```python
import numpy as np

x = np.datetime64()  # it doesn't appears at pylance previews
```
![image](https://user-images.githubusercontent.com/49549154/105138174-97856d00-5b05-11eb-88d2-96ff189c31b8.png)

While in debug mode, it still accessible:

![image](https://user-images.githubusercontent.com/49549154/105138446-f0ed9c00-5b05-11eb-9d81-859e2f3c5202.png)

**Comment by jakebailey** [comment]
This is definitely unrelated; likely #150.

**Comment by bschnurr** [comment]
if you look at `asyncpg.__init__.py`   you'll see they are dynamically building `__all__`

```
__all__ = (
    ('connect', 'create_pool', 'Pool', 'Record', 'Connection')
    + exceptions.__all__  # NOQA
)

```

**Comment by jakebailey** [comment]
Hm, this should be one of the patterns we support.

**Comment by bschnurr** [comment]
ahh. `PostgresError` isn't in that list

**Comment by jakebailey** [comment]
But, `__all__` is for `import *`, so it's omission there may or may not imply it should be externally visible.

**Comment by erictraut** [comment]
No, this isn't a pattern we support. This example is using using a nested tuple expression within a tuple expression.

**Comment by erictraut** [comment]
Here's the specific set of patterns that we support: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface

So this would work:
```python
__all__ = ['connect', 'create_pool', 'Pool', 'Record', 'Connection']
__all__.extend(exceptions.__all__)
```

**Comment by jakebailey** [comment]
Maybe I'm missing something but it's just parenthesis at the top level; it's functionally equivalent to `('foo', 'bar') + something.__all__`.

**Comment by erictraut** [comment]
At the point where we handle `__all__`, we have no type information. We're looking for very specific parse tree patterns. It's very strict. It's not feasible for us to handle deviations. That's why we explicitly defined (and standardized) the list of patterns that we support.

**Comment by jakebailey** [comment]
Sure. I was just surprised that this was one we didn't handle.

**Comment by bschnurr** [comment]
This seems like a bug after I edit  `asyncpg/exceptions/__init__.py`

doens't work
```
__all__ = _base.__all__
```

works
```
__all__ = []
__all__.extend(_base.__all__)
```



where _base.__all__  is 
```
__all__ = ['PostgresError', 'FatalPostgresError', 'UnknownPostgresError',
           'InterfaceError', 'InterfaceWarning', 'PostgresLogMessage',
           'InternalClientError', 'OutdatedSchemaCacheError', 'ProtocolError',
           'UnsupportedClientFeatureError']
```

**Comment by erictraut** [comment]
`__all__ = _base.__all__` is not a pattern we support. The _very specific_ list of supported patterns is here: https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface. If you stick to the list of standardized supported patterns, it will work fine.

**Comment by bschnurr** [comment]
yup. thank you. i'm submitting a change to asyncpg
