### ISSUE TITLE
Incomplete Uninstall

### ISSUE THREAD

**Issue by WilliamJudge94** [microsoft/pylance-release#802]
## Environment data

-   Language Server version: v2020.12.2
-   OS and version: Big Sur 11.0.1
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.6

## Expected behaviour

When I uninstall PyLance, VS Code recognizes this and reverts back to its original state for its python language server. 

## Actual behaviour

Upon uninstall, PyLance forgets to reset the python.languageServer variable found inside the setting.json file back to "Jedi". It stays as "PyLance", removing all language server functionality in VS Code. Must be manually reset.

**Comment by jakebailey** [comment]
I don't think there's anything we can do about this, unfortunately.

There's no way to distinguish when a user has uninstalled an extension from when they've disabled it, or switched to a workspace that has the extension disabled. Even if it could be detected, we wouldn't be able to put that into the Pylance extension, as by definition if we're uninstalled, then our code isn't running (and therefore can't change a setting).

There are also numerous places someone may set this config, and we don't want to change settings without user input (consider a user uninstalling Pylance, then opening up a workspace where Pylance was the default). At best, the tooltip in the Python extension could be modified to offer to change the config back to the default.
