### ISSUE TITLE
Syntax highlighting broken

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/pylance-release#804]
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): 2020.12.2 (15 December 2020)
-   OS and version: macOS 11
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Value of the `python.languageServer` setting: pylance

The syntax highlighting for Python appears to be badly broken, based on the screen shot below:

![image](https://user-images.githubusercontent.com/81476/103375583-30454180-4aa0-11eb-8b3d-85281e90b16e.png)

There is no syntax issue, as the code itself and that above it run without error within VSCode.

**Comment by judej** [comment]
@fonnesbeck, do you see the incorrect colorization when you open the editor or after you begun editing the file?

**Comment by fonnesbeck** [comment]
I was seeing this after editing, though I have not noticed it in the past few days.

**Comment by judej** [comment]
Could you please send the logs as well? 
Thanks

**Comment by jakebailey** [comment]
@fonnesbeck Have you seen this issue recently? We were still interested in some logs to see what may be going on here, but can reopen this if needed (it's been over a month since we asked and labeled this issue as needing info).

**Comment by fonnesbeck** [comment]
I still do see it occasionally. Next time it happens I will collect the logs.
