### ISSUE TITLE
`<>` in docstrings gets rendered as `&lt;&gt;` on hovering over calls

### ISSUE THREAD

**Issue by jalajdev** [microsoft/pylance-release#816]
## Environment data

-   VS Code version:
```
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```
-   Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Value of the `python.languageServer` setting: Pylance

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

The docstrings should be rendered correctly.

## Actual behaviour

The `<` and `>` characters when placed inside code blocks in docstrings get rendered as `&lt;` and `&gt;` respectively when moue is hovered over definition of the function (or class) or a call to the function.

## Steps to reproduce:

Consider this code:
![Screenshot from 2021-01-07 16-58-07](https://user-images.githubusercontent.com/67556827/103888094-2491f480-510a-11eb-846d-dd0b3b1e1a8a.png)

When I hover over the definition, it shows the docstring as:
![Screenshot from 2021-01-07 16-59-38](https://user-images.githubusercontent.com/67556827/103888099-265bb800-510a-11eb-9e94-cc4bfa279486.png)

I don't think it was supposed to be this way and it must be something with this extension because this doesn't happen with other languages.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202131-10-march-2021
