### ISSUE TITLE
Default severity levels in PyLance

### ISSUE THREAD

**Issue by staffann** [microsoft/pylance-release#817]
Pylance has an option Diagnostic Severity Overrides, where I can set the severity level for each report type, e.g. reportUnusedImport etc. But what are the default levels for each report type?

Without using the above option, there was no entry in the Problems tab for an unused import, so I guess the default level was None. Is that the case for all report types? Can I make sure that all reports are shown without having to add one setting item for every possible report type from Pylance?

**Comment by erictraut** [comment]
Pylance is built on an open-source type checker called Pyright. They share the same diagnostic rules and default severity levels, which are documented [here](https://github.com/microsoft/pyright/blob/master/docs/configuration.md#diagnostic-rule-defaults). Pylance and Pyright differ in that the typeCheckingMode default for Pylance is "off", and Pyright defaults to "basic".

**Comment by jakebailey** [comment]
Yeah, that page is useful; we should link to it from our docs too.

One thing that I think we have to fix is that the diagnostic overrides in Pylance are copied from pyright and don't reflect Pylance's actual defaults. I'm not sure if VS Code does something weird by pre-populating the map, or if it's just for the UI (which would be best).

**Comment by erictraut** [comment]
VS Code doesn't prepopulate defaults. It's just for the UI.

**Comment by mattwelke** [comment]
> Pylance and Pyright differ in that the typeCheckingMode default for Pylance is "off", and Pyright defaults to "basic".

Learning Python and using VS Code to develop for it today. I ran into this just now. I added some type hinting to my code and wondered why VS Code didn't seem to do anything with it. Is it documented anywhere why this is the default type checking mode? As a newbie without context, this seems like a strange decision.

**Comment by jakebailey** [comment]
The majority of Python users in VS Code are not interested in type checking diagnostics (only things like completions/hovers, which do _use_ type checking), so the default for Pylance is to hide all but the guaranteed errors. (Somewhat like how editing JS will not give you type errors, unless you tell the editor to do so.)

This matches the previous behavior of MPLS and pylint, which don't provide type errors by default either.

Maybe one day, if typing becomes more widely accepted, the default can change, but this for now is the default with the least friction for most users.

**Comment by mattwelke** [comment]
> for now is the default with the least friction for most users.

Ah this makes sense. Its target audience is people who've been using Python for a while. I'm completely new to Python, prefer VS Code since I've used it before for JS, TS, and Go, and generally prefer working with static typed languages. So that was why I expected this extension to work this way. Since I'm not the target audience, I need to edit the default settings to configure it the way I want to work.

Perhaps a warning should be added very close to the top of the extension readme that static type checking is disabled?

Also:

> the default for Pylance is to hide all but the guaranteed errors

This wasn't my experience a few minutes ago. The code:

```python
def capitalize_string(input: str):
    return input.capitalize()

processed_str = capitalize_string(42)

print(processed_str)
```

Looks like an "guaranteed error" to me. Indeed, when I ran it, I got this output:

```
Traceback (most recent call last):
  File "/home/matt/python-pyenv-poetry-vscode-test/app.py", line 4, in <module>
    processed_str = capitalize_string(42)
  File "/home/matt/python-pyenv-poetry-vscode-test/app.py", line 2, in capitalize_string
    return input.capitalize()
AttributeError: 'int' object has no attribute 'capitalize'
```

And VS Code's problems tab didn't warn me at all, until I at least used the "basic" type checking setting.

**Comment by jakebailey** [comment]
"Guaranteed" was probably too reductive; the errors I mean are syntax errors, unresolved imports, and unbound/undefined variable accesses. Those are more about the structure of the code and the state of the workspace and are things that MPLS/pylint/etc also warn about by default.

**Comment by rchiodo** [comment]
What was the decided course of action for this issue? Defaults do already show up:

![image](https://user-images.githubusercontent.com/19672699/195959681-14eab627-8c39-4a5b-9659-6c7425a2ae71.png)

**Comment by judej** [comment]
The README in pylance-release needs to be updated to point to Pyright: https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings

**Comment by erictraut** [comment]
Is there anything left to do for this issue? I think it's complete.

**Comment by rchiodo** [comment]
Yes I believe it can be closed.  I just checked. Readme is pointing to the appropriate section
