### ISSUE TITLE
Do I need to install a linter package if I'm using Pylance?

### ISSUE THREAD

**Issue by mattwelke** [microsoft/pylance-release#818]
Before creating this issue, I searched the opened and closed issues for mentions of "lint" to see if any answered my question, and I searched the extension page (https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) for mentions of "lint" too. I wasn't able to find an answer to my question.

I'm trying to understand what I need to set up to get linting when using VS Code to develop Python. When I install Pylance, I get problems reported in the problems tab if I make a mistake that linting would catch, like bad indentation:

![image](https://user-images.githubusercontent.com/7719209/104055379-afcbc280-51bc-11eb-8583-b52b87c1d826.png)

However, despite linting seeming to work out of the box, I get a popup from VS Code every time I load my project warning me that I should install a linter package. It suggests "pylint":

![image](https://user-images.githubusercontent.com/7719209/104055434-cbcf6400-51bc-11eb-804f-f5fbd3d7f3ef.png)

If I follow the suggestion by clicking on "Install", it successfully installs it. It detects my selected virtual environment and installs it via Poetry, since I'm using Poetry:

```
source /home/matt/.cache/pypoetry/virtualenvs/python-pyenv-poetry-vscode-test-SKKyz3XO-py3.9/bin/activate
~/python-pyenv-poetry-vscode-test > source /home/matt/.cache/pypoetry/virtualenvs/python-pyenv-poetry-vscode-test-SKKyz3XO-py3.9/bin/activate
(python-pyenv-poetry-vscode-test-SKKyz3XO-py3.9) ~/python-pyenv-poetry-vscode-test > poetry add --dev pylint
Using version ^2.6.0 for pylint

Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file

Package operations: 7 installs, 0 updates, 0 removals

  • Installing lazy-object-proxy (1.4.3)
  • Installing wrapt (1.12.1)
  • Installing astroid (2.4.2)
  • Installing isort (5.7.0)
  • Installing mccabe (0.6.1)
  • Installing toml (0.10.2)
  • Installing pylint (2.6.0)
```

But then, the next time the developer window is reloaded in VS Code, I get duplicate problems reported for the issue. One problem is reported by Pylance and one is reported by pylint. Both appear to be reporting the same problem:

![image](https://user-images.githubusercontent.com/7719209/104055616-118c2c80-51bd-11eb-8b16-10dc864ebe09.png)

I can work around the issue by solving the problem, at which point both problem reports go away, but I find the duplicate problem reports distracting while I work on my code. What is the recommended way of configuring linting when using the Pylance extension to develop Python with VS Code?

**Comment by jakebailey** [comment]
The Python extension suggests pylint by default (without a language server running) as a way to get syntax errors on save, otherwise there is no info. I'm not entirely certain why it's asking for it to be installed when you have Pylance, though. There isn't much of a reason to run it along side Pylance unless you are going to configure it to enable some of its other more style-related lints.

If you want it to be disabled, you should be able to set something like:

```
"python.linting.pylintEnabled": false
```

Or maybe the bigger hammer of:

```
"python.linting.enabled": false
```

Pylance is still a bit of a preview, so I think we're likely to tweak this behavior more in the Python extension as we clean things up there.

**Comment by mattwelke** [comment]
Interesting. I did try to delete the Python extension when I realized I had both the Python and Pylance extensions installed at the same time. But, when I tried to delete it, it warned me that I couldn't because the Pylance extension depended on it:

![image](https://user-images.githubusercontent.com/7719209/104056237-2c12d580-51be-11eb-97b8-893a58feac3b.png)

Adding `"python.linting.pylintEnabled": false` to my settings did not stop the popup from appearing when my project was loaded. I was able to click on "do not show again" though to work around that. That might be a problem though if it applies that "do not show again" setting to my entire VS Code environment, no matter which Python project I ever open. I checked my settings for something I could remove to disable hiding that popup, but couldn't find anything, so I can't test whether `"python.linting.pylintEnabled": false` has the desired affect of hiding that popup.

This seems like a tricky thing that's worth considering as the extension develops. I can see my team wanting to use linting tools as part of a CI/CD process, and they'd want those tools specified explicitly (for example, in dev dependencies in `pyproject.toml`), so I can see myself using a combination of installed linting packages and VS Code features, depending on whether I'm deploying or developing. Pylance will definitely need settings to enable and disable features to help it play nicely with packages developers may install to provide some features.

**Comment by jakebailey** [comment]
You can't remove the Python extension, no, it provides the core functionality to make Python work (and in fact is the one that starts the Pylance process).

> Pylance will definitely need settings to enable and disable features to help it play nicely with packages developers may install to provide some features.

Can you elaborate on this? Pylance isn't in control of these linters, the Python extension is, and if these settings I'm suggesting aren't working, then that's probably an issue with it. Pylance itself has configuration, and a project-level config via [pyrightconfig.json](https://github.com/microsoft/pyright/blob/master/docs/configuration.md) (and pyright is what you'd actually want to use in CI, as it is a CLI tool).

**Comment by mattwelke** [comment]
Ah. I think I misunderstood a few things.

> it provides the core functionality to make Python work (and in fact is the one that starts the Pylance process).

I didn't realize the Python extension was in charge. I was under the impression Pylance was a new extension that would eventually replace it. According to what you're saying, it's more like an extra extension one can install to augment the Python extension.

> pyright is what you'd actually want to use in CI, as it is a CLI tool

- I misunderstood how CI/CD would be done for Python projects. I haven't productionized a Python project yet. I was instructed to use `pyproject.toml` and Poetry by my team, and I assumed `pyproject.toml` would be the source of truth for what linting tools would be used and how they'd be invoked, like how for Node.js projects, `package.json` would be the source of truth for linting tools used, recording their versions and how to invoke them with `npm run ...`). I'm sure I'll learn more about how this fits together once I try productionizing a Python project.

> > Pylance will definitely need settings to enable and disable features to help it play nicely with packages developers may install to provide some features.
>
> Can you elaborate on this?

Given my misunderstanding about CI/CD tools in Python, this may not be an issue. My concern was that if tools like linters are added to a project explicitly by adding them as a dependency (to `requirements.txt` or `pyproject.toml`), that editors like VS Code would take them into account even if tools like Pylance already provides the functionality, like the duplicate linting I witnessed that I described above.

You already stated though that the desired behavior of the `python.linting.enabled` setting is that VS Code won't use dev dependency packages like pylint to do linting, which would let Pylance kick in and do it instead. So if it's working as intended, then I have nothing to worry about. I could have my CI/CD process use tools described explicitly in files like `pyproject.toml`, since having CI/CD processed reproducible (with versions of tools pinned) is a good thing, without having VS Code pick those tools up. That way, I don't get the duplicate problem reports in VS Code.

**Comment by mattwelke** [comment]
By the way, my thought process throughout all of this that linting is supposed to a first class feature of Pylance - that you're supposed to use Pylance *instead of* a linter Python package like pylint installed.

If that's not true, and this is just coincidentally something both the basic language server features and a linting tool pick up (hence the duplicate problem reports), then that would make things clearer to me what role Pylance has.

**Comment by jakebailey** [comment]
For pyproject.toml, see microsoft/pyright#694; the discussion about would be better there.

> You already stated though that the desired behavior of the python.linting.enabled setting is that VS Code won't use dev dependency packages like pylint to do linting, which would let Pylance kick in and do it instead.

That linting setting doesn't affect Pylance, no, just the Python extension's own external-tool-running code, where it runs pylint, or flake8, mypy, etc. The default for the Python extension is supposed to be pylint, but if an LS is enabled, nothing, hence my confusion as to why both were running without explicitly enabling pylint.

> By the way, my thought process throughout all of this that linting is supposed to a first class feature of Pylance - that you're supposed to use Pylance instead of a linter Python package like pylint installed.

The definition of "linting" is really difficult to pin down; it means something different to everyone. For the longest time, it was linters which provided effectly any and all info about python code, until language servers could do it live without saving, a taller task. I'd argue that you can use Pylance in place of linters for most reasons, but linters often have many other rules that people like (line length, banning some APIs, etc) so I don't expect them to go away.

To provide a comparison, this would be like how people use TS and ESLint; both can give you syntax errors, but if you're using both, you'd use TS for type errors, but ESLint for other style things. Some JS users don't use TS, and would just run ESLint or similar. There's overlap, and it's not cut and dry who does what 100% of the time.

**Comment by mattwelke** [comment]
That really clears it up for me. Thank you. I like the example of JS and TS. I always use TS, so I've never used ESLint or Prettier etc. I never felt the need to. I was always happy with the JS and TS language servers in VS Code (and I never had good practices like only checking in linted code put in place).

So you want me to create a minimal reproduction and issue for my problem where VS Code suggested installing pylint despite me using Pylance? That's the only thing that seems to be actually not behaving right given your explanations.

**Comment by jakebailey** [comment]
That could be helpful, though this wouldn't be the tracker for it.

(That bug would confuse me, given microsoft/vscode-python#13315 would imply the opposite is true...)

**Comment by mattwelke** [comment]
Closing this issue because I think it's too early to create issues related to linters and Pylance. I'd rather wait and see how Pylance develops.
