### ISSUE TITLE
how to disable Auto-completion of __init__(self, )  when i click enter?

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#819]
# vscode
version: 1.52.1 (user setup)
commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

#issue
Auto-completion of __init__(self, ) should not automatically include a "return" statement  . This issue is similiar to [#1082](https://github.com/microsoft/python-language-server/issues/1082).

**Comment by jakebailey** [comment]
There isn't a way to disable it, however is it correct to say that your seeing this when just completing a class without a base class? There is a bug at the moment where we insert an unnecessary init call for classes without parents.

**Comment by CatNofishing** [comment]
I  just do not want this Auto-completion , I want to custom my __init__  even if my class has a base class

**Comment by CatNofishing** [comment]
any  solution to disable this. The  same isuuse appear in  PyQt Module ，for example ， when you type eventFliter and clock enter, it will  automatically include a "return" statement  and  signature
![Uploading image.png…]()

**Comment by jakebailey** [comment]
That is this issue. If we change this behavior or add a setting, we would give an update here.

**Comment by judej** [comment]
We have review this and decided the current behavior if what is the intended behavior.
