### ISSUE TITLE
Conditional Import of TypedDict Not Working

### ISSUE THREAD

**Issue by andrewkittredge** [microsoft/pylance-release#828]
This might be a side effect of https://github.com/python/mypy/issues/1297.

## Environment data
 

-   Language Server version: 2021.1.0
-   OS and version: Windows
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2

## Expected behaviour

TypedDict works

## Actual behaviour

Argument to class must be a base class

## Code Snippet / Additional information

```python
try:
    from typing import TypedDict
except ImportError:
    from typing_extensions import TypedDict


class Foo(TypedDict):
    bar: str
```

![image](https://user-images.githubusercontent.com/430274/104381650-ccd4fe00-54fa-11eb-9fe9-743bb3706be9.png)

**Comment by erictraut** [comment]
This is related to https://github.com/microsoft/pyright/issues/1358

**Comment by andrewkittredge** [comment]
if TYPE_CHECKING:
    # https://github.com/microsoft/pyright/issues/1358
    from typing import TypedDict
else:
    try:
        from typing import TypedDict
    except ImportError:
        from typing_extensions import TypedDict

solves my problem.
