### ISSUE TITLE
Intellisense not working in different cells 

### ISSUE THREAD

**Issue by LilHang** [microsoft/pylance-release#829]
## Environment data

-   Language Server version: v2021.1.0
-   OS and version: win10 20H2
-   Python version (& distribution if applicable, e.g. Anaconda): Anaconda

## Expected behaviour

1. create new jupyter notebook in vscode
2. write code in cell no.1, eg: "temp = 1" or import a library
3. shift + enter，run cell no.1
4. in cell no.2，type”te....“or"numpy.", intellisense, autocompletion shows up 
## Actual behaviour
in cell no.1 intellisense works fine, but in cell no.2 and cells below, it failed.
in .py file, intellisense works totally fine .

## Additional information

i'm using vscode-insiders, python extension version :v2020.12.424452561
and i find semantic highlighting sometimes is slow，is there any setting i need to change ？

**Comment by jakebailey** [comment]
Unless I'm mistaken, this is the same as microsoft/vscode-jupyter#4389 and is fixed in the next version of the Jupyter extension.
