### ISSUE TITLE
"No definition found for "method_name" with Pylance

### ISSUE THREAD

**Issue by ebonat** [microsoft/pylance-release#833]
hi,

i did install "Pylance" extension in my vs code and make it available in my settings as:

"python.languageServer": "Pylance",

i have a class file with static methods and when i right-click in any of them in the client file i got the message: No definition found for. This occurs with any module file too. When comment "Pylance" every thing works normally. i can right-click on any method and jump to the definition in the class or module file.

thanl you for your help,

-ernest

**Comment by jakebailey** [comment]
Can you please provide a code example that shows the problem? I tested with this example, and things appeared to work as expected:

```python
class Base:
    @staticmethod
    def some_static(cls):
        pass


Base.some_static()
```

**Comment by ebonat** [comment]
yes, this works if the class is in the same file or same folder. if i append the class file to the calling program as:

import sys
sys.path.append("class_file _path")

this will not work. is this should be?

thank you for your help,

-ernest

**Comment by jakebailey** [comment]
`sys.path` and other runtime tricks aren't supported as they can't be statically analyzed, but this should not affect references unless you are also getting import resolution diagnostics when importing the other class. (https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#unresolved-import-warnings)

**Comment by ebonat** [comment]
i'll try that!

thank you for your help.
