### ISSUE TITLE
:q

### ISSUE THREAD

**Issue by waewoo** [microsoft/pylance-release#846]
<h3> Environment data </h3>

-   Language Server version: 2021.1.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
This appears to have been opened by mistake via the report issue command; the title is keystrokes for exiting vim...
