### ISSUE TITLE
Shows GeneralTypeIssues when using pathlib library

### ISSUE THREAD

**Issue by TreeKat71** [microsoft/pylance-release#848]
## Environment data

-   Language Server version: 2021.1.1
-   OS and version: OSX 10.14.6
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.9

## Expected behaviour

No error

## Actual behaviour

Pylance[reportGeneralTypeIssues]: Operator "/" not supported for types "Path" and "object | str | datetime"

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
from pathlib import Path

def save_model(self, storage: Path):
    storage / name
```

**Comment by erictraut** [comment]
Your sample code doesn't show how `name` is assigned a value or a type. Is it annotated with the type `Union[object, str, datetime]`? Is its type inferred from some other expression?

According to the `pathlib.pyi` type stub, `Path` derives from `PurePath` which supports the following method:
```python
    def __truediv__(self: _P, key: Union[str, _PathLike]) -> _P: ...
```

That means the `/` operator is supported, but the right-hand operand must be of the type `str` or a `PathLike[str]`. It cannot be an `object` or `datetime`. That explains the error you're seeing here.

**Comment by jakebailey** [comment]
It's been a month since this issue was opened and we left a reply waiting for info; if the above doesn't make sense and your issue persists, we can take a look, but it seems like your `name` variable is just of the wrong type.
