### ISSUE TITLE
AutoComplete not working with Class Variables - Pylance

### ISSUE THREAD

**Issue by akshitgupta29** [microsoft/pylance-release#85]
Tried the same with Pylance as well. Same issueL

https://github.com/microsoft/vscode-python/issues/12840

## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by erictraut** [comment]
Could you please provide a code snippet that exhibits the problem? I can't repro it from the screen shot you provided in the linked bug report.

**Comment by akshitgupta29** [comment]
@erictraut 

PFB:
![image](https://user-images.githubusercontent.com/12370891/87121715-02c1cd00-c2a1-11ea-8f42-0edfb3f851f2.png)

#Class IPL
class IPL:
    playerTeam = []
    edges = [[], []]
    playersList = []
    teamsList = [] 

    self.playersList (playersList is not auto-completed)

**Comment by erictraut** [comment]
`self` isn't a valid symbol within a class declaration. Did you intend to create an instance method within that class?

<img width="803" alt="Screen Shot 2020-07-09 at 11 12 03 PM" src="https://user-images.githubusercontent.com/7040122/87122385-a24b7500-c239-11ea-8262-174903c33c1b.png">

**Comment by akshitgupta29** [comment]
It is same in that method as well:

![image](https://user-images.githubusercontent.com/12370891/87125421-1e7ca180-c2a8-11ea-8801-10423fc3aea0.png)

**Comment by erictraut** [comment]
Which version of Pylance are you running? There was a bug in an earlier version that could explain what you're seeing, but this bug was fixed in the latest version. You can find the version by clicking on the Pylance extension and looking in the upper right, as circled in red here.

<img width="1051" alt="Screen Shot 2020-07-09 at 11 55 37 PM" src="https://user-images.githubusercontent.com/7040122/87125696-c8741380-c23f-11ea-8a93-ffd5f834ea11.png">

**Comment by akshitgupta29** [comment]
Thanks @erictraut. I have updated the version and now it is working as expected.

**Comment by akshitgupta29** [comment]
Hi @erictraut, Also, I cannot see much documentation for the default python functions, that we used to get in the MS-Python server. Can you please check for the same as well.

**Comment by erictraut** [comment]
Documentation for default python functions is a completely different issue. The current behavior is expected (i.e. it's not a bug). The type stubs that provide the type information for the Python stdlib functionality contain no documentation. Please feel free to open another issue on this topic.

**Comment by akshitgupta29** [comment]
Thanks @erictraut. Opened another bug issue with the team. PFB for reference. Closing this issue.

https://github.com/microsoft/pylance-release/issues/96

**Comment by SilverWx** [comment]
Same problem with last version for me

**Comment by jakebailey** [comment]
@SilverWx, this issue is pretty old and closed; if you have an issue we'd appreciate a new issue with an example that doesn't work.
