### ISSUE TITLE
pandas: false positive with a multi-index

### ISSUE THREAD

**Issue by thierry-bm** [microsoft/pylance-release#850]
## Environment data

-   Language Server version: 2021.1.1
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3

## Expected behaviour

No false positive.

## Actual behaviour

False positive on the following piece of code : 
```python
midx = pd.MultiIndex.from_product([["A0", "A1"], ["B0", "B1", "B2", "B3"]])
t = pd.DataFrame(np.arange(16).reshape((2, len(midx))), index=['a','b'], columns=midx)
t[('A0','B0')]
```
The last line is reported as an error : `No overloads for "t[('A0', 'B0')]" match parameters
  Calling function "__getitem__"
  Argument types: (tuple[Literal['A0'], Literal['B0']])`

I think Pylance doesn't understand correctly that tuples can be used in a multiindex settings? 

I can provide logs if needed. Thanks for this great extension!

**Comment by gramster** [comment]
I added an additional overload for getitem to the DataFrame class:

```
    @overload
    def __getitem__(self, idx: Tuple[Any]) -> Series[Dtype]: ...
```

Unfortunately it does not seem to have fixed the problem

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.2, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202132-17-march-2021

**Comment by thierry-bm** [comment]
Awesome. Concerning Pandas I still notice typing bugs almost daily (although it's probably the same ones that keep coming back), is it something that is worth reporting in this repo? I was under the impression that the pandas team was also working on improved "official" typing stubs. Does this kind of fix suppose to act as a temporary solution ?

**Comment by jakebailey** [comment]
Yes, still report them. We push these changes back to the https://github.com/microsoft/python-type-stubs repo which they will likely pull from (and we deprecate), but that process is slow going.
