### ISSUE TITLE
Auto complete for file/path name and `pandas` column name with bracket access

### ISSUE THREAD

**Issue by noppGithub** [microsoft/pylance-release#851]
1. In Juypter notebook, when you are trying to read a file with command `df = pd.read_csv('./myfile.csv')`
for the file name, you can just type `'./m` then press TAB to get a list of your file that you can pick from.

2. In Jupyter notebook, when you are typing the name of a column, e.g. you are accessing `df['date_start']`, while you are typing `df['d` then you press TAB, it's will show the option or autocomplete for you,

I think it's would be nice if we have this feature in VSCODE

**Comment by jakebailey** [comment]
Both of these rely on runtime data, things we don't have access to as a static analyzer. Jupyter itself has this data in memory and should already be suggesting it. Are you not seeing these completions when using the Jupyter extension in a notebook?

**Comment by noppGithub** [comment]
> Both of these rely on runtime data, things we don't have access to as a static analyzer. Jupyter itself has this data in memory and should already be suggesting it. Are you not seeing these completions when using the Jupyter extension in a notebook?

I can't see these completions when using Jupyter in VSCODE.
I'm not sure if I use VSCODE correctly, below are my steps for this issue.

- Create a new folder
- Create Python virtual environment in this folder
- Open VSCODE
- Select Python interpreter.
- Install `pandas` to the environment
- Create a CSV file
- Create a `.ipynb` file, click on it
- Get prompt to install `ipykernel`
- Press install
- Create some codes(as shown in the images below)
- Try to get autocompletion while pd.read_csv
- Try to get autocompletion while typing

Reference images.
<a href="https://imgur.com/o3rY6Hx"><img src="https://i.imgur.com/o3rY6Hx.png" title="source: imgur.com" /></a>
I expected to see filename autocompletion here.
<a href="https://imgur.com/v1O8fo9"><img src="https://i.imgur.com/v1O8fo9.png" title="source: imgur.com" /></a>
I expected to see column name autocompletion here.
<a href="https://imgur.com/WuN54ea"><img src="https://i.imgur.com/WuN54ea.png" title="source: imgur.com" /></a>

**Comment by jakebailey** [comment]
Can you try manually triggering a completion by hitting Ctrl+Space inside of one of those strings? And is this the new or old notebook system in the Jupyter extension?

**Comment by gramster** [comment]
The pandas part is a dup? https://github.com/microsoft/pylance-release/issues/102

**Comment by jakebailey** [comment]
Yes, it is.

As for the file-path one, I can't find it, but I believe that's a feature request we said we weren't going to do either (as it escapes the bounds of what's reasonable in a python analyzer). For notebooks, they already handle this because jupyter has this built-in and already accesses loads of runtime data.
