### ISSUE TITLE
Auto completion doesn't work as expected

### ISSUE THREAD

**Issue by syvshc** [microsoft/pylance-release#855]
I found `Pylance` when writing python, it is very pretty. However Auto-completion doesn't work as expected, Take an example of `numpy`, here's `Jedi` performs 
![Jedi.gif](https://i.loli.net/2021/01/20/Jj8fEkQK4g5bWv1.gif)

`Jedi` tells me there is a function called `sin()`, but `Pylance` doesn't.

![Pylance.gif](https://i.loli.net/2021/01/20/QnqYz7aSK24mb6U.gif)

I have below extensions related to `python`: `Pylance`, `pylint`, `python`.

And I found a similar issue  https://github.com/microsoft/pylance-release/issues/787#issue-775813882

**Comment by jakebailey** [comment]
This should be fixed in the next release with numpy 1.20 installed: 

![image](https://user-images.githubusercontent.com/5341706/114482633-bdc62080-9bbb-11eb-9c53-78bb8437b986.png)

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.4.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202141-14-april-2021
