### ISSUE TITLE
Do not report unused imports in `__init__.py`

### ISSUE THREAD

**Issue by adamal** [microsoft/pylance-release#856]
It seems to be a common approach in Python to use `__init__.py` files to reorganize how the user of a module imports from it.

E.g. from a recent swagger-gen project I would see a lot of lines like:
```
from swagger_client.models.thing import Thing
```

I believe the purpose of these is for users of the module to be able to import `Thing` like
```
from swagger_client.models import Thing
```
in stead of 
```
from swagger_client.models.thing import Thing
```

This is a pattern I have seen many times, so perhaps `__init__.py` should be treated like a special case and ignore unused imports (and thus not offer to remove them).

**Comment by erictraut** [comment]
If your intent is to re-export a symbol that is imported, then you should use the redundant form of the import as specified in PEP 484:
```python
from swagger_client.models import Thing as Thing
```

This tells type checkers and other tools that `Thing` is not meant to be a private internal usage within the file but instead is meant to be a public re-export of the symbol. When the redundant import form is used, pylance will no longer report the import as unused.

For more details, refer to [this documentation](https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md).

**Comment by adamal** [comment]
Thanks, Eric. That makes sense. I'll close this.

**Comment by KalleDK** [comment]
I tried using the re-export method, but it still gives the error

```python
from .country import get_country as get_country
```

```python
from fqdn.country import get_country as get_country
```

both still marks the last word with an error of reportUnusedImport, if I create __all__ and add it there, then it all works though.

**Comment by jakebailey** [comment]
Is your project marked as `py.typed`? I'm trying to remember if this exception only applies to py.typed libraries or not.

**Comment by erictraut** [comment]
We should probably mark redundant forms of import as "used" regardless of whether it's within a py.typed library. I'll take care of this.

**Comment by erictraut** [comment]
I've changed the code to treat all redundant forms of "from .. import" statements as re-exports. In all such cases, the imported symbol is marked as accessed.
