### ISSUE TITLE
Variables defined in an if marked possibly unbound even if later access is guarded by the same check

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [microsoft/pylance-release#860]
## Environment data

-   Language Server version: 2021.1.1 (pyright 6a970b45)
-   OS and version: Ubuntu 20.10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6

## Expected behaviour

Pylance sees that the two checks are the same and infers that the given variable is bound

## Actual behaviour

Pylance assumes that the variable is unbound

## Logs

Not sure any will be relevant. Happy to provide if needed

## Code Snippet / Additional information

```python
if 1 << 10 > 0:
    test = False


if 1 << 10 > 0:
    print(test)
   #      ^^^^ Possibly unbound warning
```

**Comment by erictraut** [comment]
This is expected behavior. It is not practical for a static type checker to understand (and generally dangerous for it to assume) that an expression executed earlier in a method will give the same result if it is executed later in a function. You should initialize your variables in all code paths instead.

```python
test = True
if 1 << 10 > 0:
    test = False
```

or

```python
test = not (1 << 10 > 0)
```

**Comment by jakebailey** [comment]
The next release contains some more narrowing improvements when it comes to indexing tuples with literals, but I don't see us changing this behavior without a lot of users having this problem to motivate a larger change; it's not straightforward to do checks like this and as Eric said, can be dangerous (and impacts perf).
