### ISSUE TITLE
Syntax highlighting breaks on Python3 return type hinting

### ISSUE THREAD

**Issue by Azsu** [microsoft/pylance-release#862]
<h3> Environment data </h3>

-   Language Server version: 2021.1.2
-   OS and version: darwin x64
-   Python version (and distribution if applicable, e.g. Anaconda): 3.8
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

Proper color coding based on syntax

<h3> Actual behaviour </h3>

Following a return type hint on a function definition, the syntax coloring is broken.

def f(x : bool):
    '''Summary that has good syntax color
    ''''
    this_syntax_color_is_good = x
    return x

def f(x : bool) -> bool:
    '''Summary that has broken color
    ''''
    this_text_is_also_wrong = x
    return x

...more broken syntax highlighting

<img width="597" alt="Screen Shot 2021-01-21 at 2 03 22 PM" src="https://user-images.githubusercontent.com/1273425/105418203-90d42400-5bf1-11eb-9131-8fd228a08da0.png">
<img width="559" alt="Screen Shot 2021-01-21 at 2 03 42 PM" src="https://user-images.githubusercontent.com/1273425/105418212-93cf1480-5bf1-11eb-93ed-aa7230784009.png">

**Comment by jakebailey** [comment]
Could be #732?

**Comment by erictraut** [comment]
I'm not able to repro this or #732. @jakebailey or @bschnurr, are you able to?

**Comment by Azsu** [comment]
V2021.1.2, have you tried including a block docstring?

**Comment by Azsu** [comment]
Settings:

<img width="445" alt="Screen Shot 2021-01-22 at 12 12 58 PM" src="https://user-images.githubusercontent.com/1273425/105540640-60e95700-5cab-11eb-92b4-9bce5d8b3821.png">
<img width="572" alt="Screen Shot 2021-01-22 at 12 13 05 PM" src="https://user-images.githubusercontent.com/1273425/105540651-634bb100-5cab-11eb-8f38-85dbc896ec71.png">

**Comment by Azsu** [comment]
ms-python.python-2021.1.502429796

Logs:
[renderer1.1.log](https://github.com/microsoft/pylance-release/files/5858425/renderer1.1.log)
[renderer1.2.log](https://github.com/microsoft/pylance-release/files/5858426/renderer1.2.log)
[renderer1.3.log](https://github.com/microsoft/pylance-release/files/5858427/renderer1.3.log)
[renderer1.log](https://github.com/microsoft/pylance-release/files/5858429/renderer1.log)

**Comment by niamiot** [comment]
Hi, same here 
![image](https://user-images.githubusercontent.com/1019656/108703158-88ca1580-750a-11eb-9594-311f8114d793.png)

I was able to fix it by removing  the _Python for VSCode extension_

**Comment by Azsu** [comment]
> Hi, same here
> ![image](https://user-images.githubusercontent.com/1019656/108703158-88ca1580-750a-11eb-9594-311f8114d793.png)
> 
> I was able to fix it by removing the _Python for VSCode extension_

I can confirm this is related to conflicting plugins, I would say just close this but it might be a good idea to identify and flag conflicting plugins in code

**Comment by jakebailey** [comment]
That doesn't make sense; removing the Python extension means Pylance will not run at all; the Python extension is what actually activates Pylance, and Pylance requires it to be installed (VS Code will not let you have Pylance and not the Python extension).

Are you saying that you're just going back to pure VS Code defaults (no highlighting at all)? Are you certain Pylance is actually running?

**Comment by AlexanderDudnyk** [comment]
I have the same problem.
 ### Environment data
    Language Server version: 2021.2.4
    VS Code version: 1.53.2
    OS and version: Linux 5.8.0-43-generic Ubuntu 20.10 x86_64 
    Python version (and distribution if applicable, e.g. Anaconda): 3.8.6
    Type of virtual environment used:  pipenv, virtualenv, without virtual environment
    python.languageServer: Pylance
    python.analysis.indexing: true
    python.analysis.typeCheckingMode: basic
    python.analysis.completeFunctionParens: true
    
[vs_intellicode.log](https://github.com/microsoft/pylance-release/files/6054254/vs_intellicode.log)
[python_lang_server.log](https://github.com/microsoft/pylance-release/files/6054255/python_lang_server.log)
[python.log](https://github.com/microsoft/pylance-release/files/6054259/python.log)

![Снимок экрана от 2021-02-27 13-04-45](https://user-images.githubusercontent.com/4014286/109385657-1b4d2900-78fe-11eb-9901-325266ef481c.png)

**Comment by jakebailey** [comment]
Oops, we meant to close this in favor of #732, which appears to be the same issue. That issue's in our backlog for investigation.

**Comment by jakebailey** [comment]
Seems like the extension in question was this one: https://marketplace.visualstudio.com/items?itemName=tht13.python

(Not "Python", the one we make.)

**Comment by h12sw06** [comment]
I'm using a temporary solution.
It's a way to create a meaningless def _(): pass. 
```
def function():
  def _():
       pass

  return 'Hello World!'
```
