### ISSUE TITLE
reportUndefinedVariable False warning for subclass when using isinstance

### ISSUE THREAD

**Issue by anikdatos** [microsoft/pylance-release#866]
## Environment data

-   Language Server version: 2021.1.2
-   OS and version: Windows 10
-   Python version: 3.8.0, (conda) 

## Expected behaviour

No warning should be highlighted for the code

## Actual behaviour

"Tree" is not defined

## Code Snippet / Additional information
```
class superTree:
   # super tree methods
    class Tree:
        def __init__(self,value=None):
            self.value = value
            self.children = []
        def add_child(self,node):
            assert isinstance(node,Tree) <--- "Tree" not defined 
            self.children.append(node)
            node.parent = self
```

Also note that it gives no Warning for this case
```
class Tree:
    def __init__(self,value=None):
        self.value = value
        self.children = []
    def add_child(self,node):
        assert isinstance(node,Tree)
        self.children.append(node)
        node.parent = self
```

**Comment by erictraut** [comment]
I'm not able to repro the error you've reported. Could you verify that the first sample above produces an error or warning?

Here's what I see when I paste your code into the editor with the latest version of Pylance.
![Screen Shot 2021-01-22 at 12 07 43 AM](https://user-images.githubusercontent.com/7040122/105464121-e33f3000-5c45-11eb-99db-661164e0e7b3.png)

**Comment by anikdatos** [comment]
![8CE9D96E-38A5-44D9-A509-0CE0EEEB51FD](https://user-images.githubusercontent.com/52519645/105467575-e5dc6c80-5cbb-11eb-8555-111d2e87bfbc.png)

Please refer.

**Comment by erictraut** [comment]
Ah, I had pasted both of your samples into the same editor window. I'm now able to repro the warning if I include only your first sample.

Here's your sample with a few additional lines of code that instantiates the inner class.

```python
class superTree:
    # super tree methods
    class Tree:
        def __init__(self, value=None):
            self.value = value
            self.children = []
        def add_child(self, node):
            assert isinstance(node, Tree)
            self.children.append(node)
            node.parent = self

x = superTree.Tree()
x.add_child(x)
```

When I run this, the Python interpreter generates the following output:
```
Traceback (most recent call last):
  File "x.py", line 15, in <module>
    x.add_child(x)
  File "x.py", line 9, in add_child
    assert isinstance(node, Tree)
NameError: name 'Tree' is not defined
```

So, as you can see, Pylance is doing the right thing here. The warning is correct.

**Comment by anikdatos** [comment]
Well, I suppose this is a python bug then!

Thank You
