### ISSUE TITLE
The whole Pylance seems to be not working

### ISSUE THREAD

**Issue by didimelli** [microsoft/pylance-release#87]
## Environment data

-   Language Server version: 2020.7.0
-   OS and version: Windows 10, version 2004, build 19041.330.
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3

## Expected behaviour

I'm using WSL 2 on Ubuntu 20.04 and i am using VScode with the Remote - WSL extension.
![image](https://user-images.githubusercontent.com/53627721/87145412-8e3f5c00-c2a9-11ea-9415-fff80683d3af.png)
Everything works, the interpreter is correctly set up, git is correctly working and so on.

I have both the Python and the Pylance extensions installed on WSL
![image](https://user-images.githubusercontent.com/53627721/87145712-01e16900-c2aa-11ea-9c7d-7649b891c8a4.png)

I would expect to see some actions like highlighting of errors, unimported modules, ...

## Actual behaviour

I cannot see anything. 
Some examples:
![image](https://user-images.githubusercontent.com/53627721/87145858-51c03000-c2aa-11ea-8f81-dbb4d2d7d6cf.png)
(clearly, the variable after the `return` does not exist)

![image](https://user-images.githubusercontent.com/53627721/87145991-8d5afa00-c2aa-11ea-86bd-71ff8ac21d44.png)

## Additional information

The Pylance output does not show anything.
![image](https://user-images.githubusercontent.com/53627721/87146039-a499e780-c2aa-11ea-9d14-7e10c7ab0276.png)

What am i doing wrong?

**Comment by didimelli** [comment]
The developer tools give some infos about some errors.
![image](https://user-images.githubusercontent.com/53627721/87148004-e2e4d600-c2ad-11ea-9bb3-3006bc15ee3f.png)
![image](https://user-images.githubusercontent.com/53627721/87148028-ed9f6b00-c2ad-11ea-9c95-54d517af565b.png)

**Comment by didimelli** [comment]
Actually i could solve the first issues about python3.7.
The last two still remains (the `Unable to read file ....settings.json` and the `attempted to download with skipDownload true`).

**Comment by didimelli** [comment]
Downgrading to `2020.6.1` fixes the problem.

**Comment by jakebailey** [comment]
Most of those red messages related to the core extension's config fixing code. Another bug, but I don't think it's related.

The last one indicates that it's failing to start the LS, though, which would meant that the log about starting the LS shouldn't have happened at all. Are these screenshots taken from multiple runs of VS Code, or the all the same session/reload?

**Comment by didimelli** [comment]
They are all coming from the same session/reload!

**Comment by jakebailey** [comment]
Okay, so all of the red errors are red herrings, and aren't impacting anything. They're known issues but aren't impeding the language server from starting.

Can you enable trace logging and copy the output?

```json
"python.analysis.logLevel": "Trace"
```

**Comment by jakebailey** [comment]
I can reproduce this, at least. Rolling this into #86 as I believe it to be the same thing. It appears to be only diagnostics which have the issue.
