### ISSUE TITLE
variable defined in outer function of closure is reported as unbound in inner function

### ISSUE THREAD

**Issue by cropr** [microsoft/pylance-release#872]
## Environment data

-   Language Server version: 2021.1.2
-   OS and version: Ubuntu 20.10
-   Python version: 3.8.6

## Expected behaviour

No error (like mypy)

## Actual behaviour

Pylance reports "i" is unbound in the if statement

## Code Snippet / Additional information

```python
def outer():
    i = 0
    def inner():
        if i == 0:
            i += 1
            return 'first_time'
        else: 
            return 'not_first_time'
    ...
```

**Comment by erictraut** [comment]
Pylance is doing the right thing here. It's pointing out that your code contains a bug that will generate a runtime exception.

```python
def outer():
    i = 0

    def inner():
        if i == 0:
            i += 1
            return "first_time"
        else:
            return "not_first_time"

    inner()

outer()
```

If I add the extra function calls and run this in the python interpreter, I receive the following exception: `UnboundLocalError: local variable 'i' referenced before assignment`. 

I think what you intended was for `inner` to use the nonlocal `i`, but you're missing a `nonlocal i` statement. If you add that, the code will no longer crash, and pylance won't generate an "unbound variable" error.

**Comment by jakebailey** [comment]
This issue has been open with the "waiting for info" tag for over a month, so I'm going to close it. If the above doesn't apply and you still have this issue, we can reopen.
