### ISSUE TITLE
reportMissingImports

### ISSUE THREAD

**Issue by addankiashok1** [microsoft/pylance-release#875]
<h3> Environment data </h3>

-   Language Server version: 2021.1.2
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by erictraut** [comment]
You haven't provided enough details for this bug report to be actionable. Please fill in the details of the template and provide a minimal piece of code that exhibits the problem you are seeing.

**Comment by jakebailey** [comment]
It's been a month since this was opened with no info; closing. If you have info to provide we can reopen.
