### ISSUE TITLE
Use inherited docstring from super or abstract base class for implementation methods with no docstring 

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/pylance-release#877]
[Sphinx](https://github.com/sphinx-doc/sphinx/issues/3140) and other documentation generators output the docstring associated with the super class method if the sub class implementation doesn't have a docstring.

See other discussion in general on [StackOverflow](https://stackoverflow.com/questions/2025562/inherit-docstrings-in-python-class-inheritance) and [again](https://softwareengineering.stackexchange.com/questions/353004/how-should-i-handle-docstrings-of-subclass-methods).

It would be great to have this as a feature, so when hovering or completing a sub class method, the user can see the docstring from the superclass.

Thanks!

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.3.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202130-3-march-2021
