### ISSUE TITLE
Hovering the mouse over keywords does not display intelisense suggestions in jupyter notebook

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#88]
# vscode 
version: 1.46.1 (user setup)
commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
pylance version : 2020.7.0

# describe
Typehint is invalid, and smart suggestions cannot be obtained through mouse hovering in jupyter

**Comment by CatNofishing** [comment]
sorry, after I reset the vscode, it started to work normally.😂

**Comment by huguesv** [comment]
Excellent!
