### ISSUE TITLE
Import couldn't be resolved

### ISSUE THREAD

**Issue by DotBow** [microsoft/pylance-release#885]
## Environment data

-   Language Server version: v2021.1.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.6 (pipenv)

## Expected behaviour

XXX

## Actual behaviour

For some reason Pylance can't resolve imports (Python ms-python.python do not have such issue), might be related to using pipenv.

![изображение](https://user-images.githubusercontent.com/32243930/105992680-78af4980-60b6-11eb-937f-9d6ba33ebbab.png)

![изображение](https://user-images.githubusercontent.com/32243930/105992805-967cae80-60b6-11eb-9e75-85ddb86545b6.png)

## Logs

```
XXX
```

## Code Snippet / Additional information

Link to repository https://github.com/DotBow/Blender-Launcher

**Comment by DotBow** [comment]
Ok, it can be fixed using extra paths:

![изображение](https://user-images.githubusercontent.com/32243930/105993916-fb84d400-60b7-11eb-965d-7b34f7e3a8c5.png)

But this is a bit strange that VS knows about virtual environment and cant automatically use paths. Same for local paths.
Do I need to change it every time by hand?

**Comment by jakebailey** [comment]
You should not need to do that; can you please provide trace logs, which will include info about the search paths being given by the interpreter? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by DotBow** [comment]
> 
> 
> You should not need to do that; can you please provide trace logs, which will include info about the search paths being given by the interpreter? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

Hi! Here is the logs:

[Python Language Server Output.log](https://github.com/microsoft/pylance-release/files/5882528/Python.Language.Server.Output.log)
[Python Output.log](https://github.com/microsoft/pylance-release/files/5882529/Python.Output.log)

I'm not quite sure which part you need exactly, sorry.

**Comment by jakebailey** [comment]
The logs are implying that you have the global interpreter selected and not the one that contains site-packages folder you had to manually add. In the python output, it says:

```
Python interpreter path: ~\AppData\Local\Programs\Python\Python38\python.exe
```

And in the Pylance logs, it says:

```
[Info  - 22:21:34] Setting pythonPath for service "Blender-Launcher": "C:\Users\user\AppData\Local\Programs\Python\Python38\python.exe"
Search paths found for configured python interpreter:
  C:\Users\user\AppData\Local\Programs\Python\Python38\DLLs
  C:\Users\user\AppData\Local\Programs\Python\Python38\lib
  C:\Users\user\AppData\Local\Programs\Python\Python38
  C:\Users\user\AppData\Roaming\Python\Python38\site-packages
  C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages
```

Which agree that it's the global interpreter. Can you try selecting the environment that contains the module?

**Comment by DotBow** [comment]
You are right, the environment wasn't selected! 
But it was perfectly running using 'pipenv run start' and Python (ms-python.python) extension was working fine resolving modules without explicitly selected environment.
What about local imports then? Do I need to use extra paths for them? They also worked fine with Python (ms-python.python) extension.

**Comment by jakebailey** [comment]
I guess I'm not sure what you mean by "working fine resolving modules without explicitly selected environment"; do you mean that the code ran in the terminal, or that some imports worked?

Local imports shouldn't need anything special, unless you are relying on imports being rooted from subdirectories of your workspace (in which case you may need extraPaths). Judging by the breadcrumb in the screenshots, you may want to set extraPaths to `["./sources"]` to say that modules can be imported from there (if you have not already set PYTHONPATH or something). We automatically detect `./src` as a possible place to import from, but not `./sources` (which is rare).

**Comment by DotBow** [comment]
I mean that imports works both for local paths and modules from environment.
My regular scenario is the following with Python extension:
- clone repository
- install environment via pipenv install
- that's it... At this point everything is ready to use

I'm not quite sure if this extensions somehow releated to each other, maybe I'm wrong...

**Comment by jakebailey** [comment]
I'm trying to figure out if you're saying that the imports do/don't get squiggled in the editor window, or if you are talking about something else. The Python extension can run three different analysis services (+pylint) that would potentially show or not show errors, so I want to know if previously you had been using something else and have only now switched to Pylance. Jedi, for example, very loosely resolves imports and will be able to resolve your custom project layout (even if it gets imports wrong sometimes), whereas MPLS and Pylance are more strict and require you to list custom import roots if it's not the auto-detected `src` directory (which is the most common non-standard layout).

The above is mainly about the local imports; I wouldn't expect any analysis to get your third-party imports to work without the Python extension having selected the correct environment, and I'm not familiar enough in how they operate to know if something changed there, or if settings got cleared or something.

**Comment by mvanderlee** [comment]
OS: Windows 10
VSCode: 1.52.1

I have the same issue, projects that used to work fine are now unable to resolve absolute imports from the project itself. 
However, for me it broke with v2021.1.3.

Tested with multiple Pylance versions:
v2021.1.0  - Works fine
v2021.1.1  - Works fine
v2021.1.2  - Works fine
v2021.1.3  - Broken

It's only broken when using virtualenv, using system python works fine.

**Comment by erictraut** [comment]
In the latest version, we made a small change to the import resolution logic to match the behavior of the Python interpreter when modules of the same name are found both locally and in site-packages. In particular, when the local package is a namespace package, the Python interpreter prefers regular packages (those with an `__init__.py` file) over namespace packages.

For example, if you have a package installed in your virtualenv called "foo" and a folder in your local workspace called "foo" and your code contains `import foo.bar`, if the local folder "foo" doesn't contain an `__init__.py` file, it's considered a namespace package, and the package "foo" within the virtualenv's site-packages directory will take precedent. Does that explain the behavior you're seeing?

**Comment by mvanderlee** [comment]
@erictraut That sounds like the cause.
We merge multiple project under the same root module and merge them with this:

```python
"""Ensure the namespace gets merged"""
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

This allows us to have `companyX.project1`, `companyX.project2` And on install, they all work together seamlessly. The interpreter allows this. It seems that Pylance no longer handles this.

**Comment by erictraut** [comment]
Static analyzers can't deal with dynamic (runtime) manipulation of import paths. The import paths need to be described statically.

There are probably ways for you to get this to work, but it may require some creativity. As you're probably aware, import resolution in Python is very complex. Pylance tries to do its best to match the import resolution rules of the interpreter (within the limits of what's possible statically). Let us know if you run out of ideas, and we can try to help you out.

**Comment by DotBow** [comment]
> 
> 
> Static analyzers can't deal with dynamic (runtime) manipulation of import paths. The import paths need to be described statically.
> 
> There are probably ways for you to get this to work, but it may require some creativity. As you're probably aware, import resolution in Python is very complex. Pylance tries to do its best to match the import resolution rules of the interpreter (within the limits of what's possible statically). Let us know if you run out of ideas, and we can try to help you out.

Thanks for explanation and help! It seems everything is working perfect now! It was my mistake and non-acquaintance 😓
