### ISSUE TITLE
Is it possible to report that a variable is never read after its value being re-assigned?

### ISSUE THREAD

**Issue by Azureblade3808** [microsoft/pylance-release#889]
## Environment data

-   Language Server version: Pylance 2021.1.3
-   OS and version: Irrelevant
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.5 (Anaconda)

## Expected behavior

```python
def foo():
    a = 1
    a = a + 1  # Error reported that the new value of `a` is never read.
```

## Actual behavior

No error reported.

**Comment by erictraut** [comment]
Pylance will report cases where a variable's value is not accessed on any code path. In the example you provided, the variable `a` is accessed once in the expression `a = a + 1`, so it is not marked as unaccessed. If you change this statement to `b = a + 1`, the variable `b` is unaccessed, so it is displayed as "grayed out" by Pylance, and if you enable the `reportUnusedVariable` diagnostic check, it will generate an error as well.

**Comment by Azureblade3808** [comment]
Thanks for explanation.

I had the image that some other IDE does such kind of check, which turned out to be wrong after some verification (tried Spyder for Python and Eclipse for Java, and both have the same behavior with Pylance).

Closing this issue.
