### ISSUE TITLE
Prioritize starred IntelliSense suggestion

### ISSUE THREAD

**Issue by gokturksm** [microsoft/pylance-release#89]
When I try to use one of the methods of pd (pandas), there is few starred suggestions there.
![image](https://user-images.githubusercontent.com/2174487/87166751-ad071800-c2d4-11ea-8b2c-f8ae1b2e4a75.png)

This is cool, so why not utilize this one further on? When I type "d", then there are no starred suggestions. 
![image](https://user-images.githubusercontent.com/2174487/87166814-c4de9c00-c2d4-11ea-9873-3abbf5bfd621.png)

I suggest that the behavior in the first picture should be carried out in the second picture as well. Starred ones should be at top and their order should not be changed as well.

I don't know the name for starred suggestions, so there is that.

**Comment by Bluppsn** [comment]
Intellicode is context aware, it's supposed to change. Depending on the context it suggests different functions.

**Comment by MikhailArkhipov** [comment]
This looks like a bug rather than enhancement. Most probably IC does not get chance to augment the list. This works in "Microsoft" LS

![image](https://user-images.githubusercontent.com/12820357/87178308-c9ce2c00-c291-11ea-9919-dc24a22cef86.png)

**Comment by jakebailey** [comment]
This should be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.9.3, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202193-22-september-2021
