### ISSUE TITLE
Incorrect intelligence prompt

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#890]
I updated Pylance to the latest version and the bug appeared
![image](https://user-images.githubusercontent.com/33288114/106105825-94325700-617f-11eb-9510-af4b989cdc46.png)

**Comment by judej** [comment]
@CatNofishing, we are unable to reproduce this. Would you please fill out the template. Please refer to https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue for instructions.

**Comment by CatNofishing** [comment]
It  work fine now, thanks, maybe some little bug appear
