### ISSUE TITLE
"Arguments missing" for optional arguments in dataclass

### ISSUE THREAD

**Issue by talarari** [microsoft/pylance-release#893]
## Environment data
-   Language Server version: Pylance language server 2021.1.3
-   OS and version: Mac os catalina
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.8

## Expected behaviour

Creating an instance of a dataclass without arguments for optional fields will show no error

## Actual behaviour

creating an instacnce of a dataclass without arguments for optional fields shows and error "arguments missing"

![image](https://user-images.githubusercontent.com/4973087/106163054-6ce48580-6191-11eb-86f3-ef39efecf67c.png)
![image](https://user-images.githubusercontent.com/4973087/106163071-71a93980-6191-11eb-8aaa-daaac3b2550b.png)

**Comment by notatallshaw** [comment]
Have you tried running this code?

When I run this:
```python
from dataclasses import dataclass
from typing import Optional

@dataclass
class User:
    name: str
    age: Optional[int]

user = User(name="Jon")
```

I get this output:
```
  File "data_class_test.py", line 9, in <module>    
    user = User(name="Jon")
TypeError: __init__() missing 1 required positional argument: 'age'
```

`Optional` from typing means the value can by the given type (int in this case) or it can be the None type.  

For a field to be actually optional in a dataclass you must give it a default value, in this case probably `None`:
```
@dataclass
class User:
    name: str
    age: Optional[int] = None
```

Which Pylance correctly handles (actually if this was a bug I assume it would be with Pyright not Pylance).

**Comment by erictraut** [comment]
The notation `Optional[int]` means that the value must be of type `None` or `int`. It does not mean that it can be omitted from the dataclass. There is currently no way to specify that individual elements are not required. There is an ongoing discussion in the typing-sig about adding such a facility in Python 3.10, but no decision has been finalized yet. 

Pylance is doing the right thing here based on PEP 557.

**Comment by erictraut** [comment]
If you're interested in following the discussion in the typing-sig, here's a [link](https://mail.python.org/archives/list/typing-sig@python.org/thread/PYHMQEL7KKV7CJOPLY5BR6PTR4O5K7VU/).

**Comment by talarari** [comment]
thanks for the info, using a default value makes sense.
