### ISSUE TITLE
VS Code Version Compatibility

### ISSUE THREAD

**Issue by navneethc** [microsoft/pylance-release#9]
Windows 10 1909
VS Code 1.45.1
Python extension: 2020.6.91350

Pylance will not install because of the following issue.

![image](https://user-images.githubusercontent.com/4192839/86215040-b4724700-bb99-11ea-8a07-faf1b8aa7b3a.png)

I'm afraid I can't update to a higher version, as this is my work laptop, but I have a Microsoft and few non-Microsoft extensions already installed. Is there a minimum required version of VS Code? I wasn't able to locate that information in the documentation.

**Comment by erictraut** [comment]
Pylance requires VS Code version 1.46.0 or above.

**Comment by navneethc** [comment]
Thank you.
