### ISSUE TITLE
pd.Timestamp is missing from the suggestions

### ISSUE THREAD

**Issue by gokturksm** [microsoft/pylance-release#90]
## Environment data

-   Language Server version: Latest
-   OS and version: W10 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.x

## Expected behaviour

pd.Timestamp should be in the suggestion list just like pd.Dataframe. see #13

## Actual behaviour

![image](https://user-images.githubusercontent.com/2174487/87167191-48988880-c2d5-11ea-9176-7b613e437888.png)
![image](https://user-images.githubusercontent.com/2174487/87167288-682fb100-c2d5-11ea-923a-f740ad7ded08.png)

## Code Snippet / Additional information

```python
pd.time
pd.T
```

**Comment by netokey** [comment]
The problem exists in the latest version 2020.7.1.

**Comment by gramster** [comment]
This should be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.8.1, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202081-13-august-2020
