### ISSUE TITLE
 could not be resolved Pylance report MissingImports

### ISSUE THREAD

**Issue by mingtiandemeng** [microsoft/pylance-release#900]
After upgrading, I found that I couldn't reference it
![e](https://user-images.githubusercontent.com/26112103/106423363-45483280-649b-11eb-819b-1e927f757c48.png)

**Comment by jmlidbetter** [comment]
I am also seeing `Import "..." could not be resolved` errors for modules in the current python package with the latest upgrade (2021.1.3). Downgrading to 2021.1.2 fixes the issue.

**Comment by jakebailey** [comment]
Is this a duplicate of #892? Are you also using pkgutil namespace packages?

**Comment by jakebailey** [comment]
Note that this isn't really enough info to go on; we need concrete cases to know what to look for. Imports not resolving could be numerous things.

**Comment by jmlidbetter** [comment]
Yes, appologies, this is a duplicate of #892 on my side, we are using pkgutil namespace packages.

**Comment by jakebailey** [comment]
Thanks for confirming.
