### ISSUE TITLE
incorrect type hinting of nested generic class

### ISSUE THREAD

**Issue by benblo** [microsoft/pylance-release#901]
## Environment data

-   Language Server version: 2021.1.3
-   OS and version: Windows 10 Pro
-   Python version: 3.8.5

## Issue

Consider the following:
```python
from typing import TypeVar, Generic, Type

T = TypeVar("T")

class Node(Generic[T]):
	class Item(Generic[T]):
		def __getitem__(self, index) -> T:
			pass

	def __init__(self, node_type : Type[T]) -> None:
		pass

	def __get__(self, obj, cls) -> Item[T]:
		pass


class Test:
	node = Node(int)

test = Test()
v = test.node[0]
```
### Expected behaviour

The type hint reported for `v` should be `int`.

### Actual behaviour

The type reported for `v` is T@Node, ie unknown:
![image](https://user-images.githubusercontent.com/574187/106477996-0d47ec00-64a9-11eb-9f98-701650c96ca2.png)

**This is a regression: the above sample code used to work circa September 2020.**

## Workaround

Now if I specify different TypeVars for Node and Item:
```python
from typing import TypeVar, Generic, Type

T1 = TypeVar("T1")
T2 = TypeVar("T2")

class Node(Generic[T1]):
	class Item(Generic[T2]):
		def __getitem__(self, index) -> T2:
			pass

	def __init__(self, node_type : Type[T1]) -> None:
		pass

	def __get__(self, obj, cls) -> Item[T1]:
		pass


class Test:
	node = Node(int)

test = Test()
v = test.node[0]
```
... the type reported for `v` is now (correctly) `int`.
![image](https://user-images.githubusercontent.com/574187/106479155-4a60ae00-64aa-11eb-92ca-840dc602e635.png)

There seems to be a confusion as to which scope the `T` comes from, as specifying different TypeVars resolves it; there should be no confusion at all :).

## Side-node

I would actually expect the following to work:
```python
from typing import TypeVar, Generic, Type

T = TypeVar("T")

class Node(Generic[T]):
	class Item:
		def __getitem__(self, index) -> T:
			pass

	def __init__(self, node_type : Type[T]) -> None:
		pass

	def __get__(self, obj, cls) -> Item[T]:
		pass


class Test:
	node = Node(int)

test = Test()
v = test.node[0]
```
... ie since `Item` is a nested class of `Node`, it shouldn't need to be generic at all to get access to the `T` of its containing class, and the `T` of `Item.__getitem__` should naturally be the `T` of `Node`.
For reference, the equivalent works in C#.

**Comment by erictraut** [comment]
The current behavior is correct. [PEP 484](https://www.python.org/dev/peps/pep-0484/#id21) specifically disallows the use of the same type variable within a nested class (i.e. a class declared within another class). Earlier versions of pylance/pyright allowed this, but that was a bug. Your first sample now correctly generates errors. I confirmed that mypy also reports the error.

The correct way to write this code is what you have done in your "workaround" sample.

**Comment by benblo** [comment]
Ah, well ok then, good to know!
I suppose my third example is also not allowed by the PEP?
Thanks Eric!
