### ISSUE TITLE
Python Extension taking very long time to show Autocomplete and IntelliSense commands

### ISSUE THREAD

**Issue by mohammedayub44** [microsoft/pylance-release#902]
Hi,

Facing really long time delays in IntelliSense using Pylance when connected to remote EC2 machine.

- Extension Name: `python`
- Extension Version: `2021.1.502429796`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.52.1`

It shows loading for about 10secs on any object I hover the mouse over and doesn't show me any autocomplete options fast. 
I'm currently connected to a remote EC2 machine which is my development server running t2.xlarge instance (about 16GB RAM)

The Running Extensions commands gives me the below output , Also how can I go about reducing the time shown on these `Activations`
![image](https://user-images.githubusercontent.com/7122670/106373867-c42e5580-634b-11eb-88e7-9db87a6c67c8.png)

 
Thanks !

**Comment by judej** [comment]
@mohammedayub44, thanks for the report. Could you please add more info on the problem? Is there a code sample that can repro the problem? What modules are you importing? Could you please add the trace logs as well? Please see this for adding logs - https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue

**Comment by mohammedayub44** [comment]
@judej  Thanks. I don't have any logs, Sorry.  However, below is additional info.

The remote machine is a Ubuntu 16.04 Deep Learning AMI which has virtual environments. I'm currently connect to `tenorflow2_p36` environment which uses TensorfFlow 2.X. I have cloned the below repository, setup the dev environment and trying to make edits to `mlflow/tensorflow.py` file.

Repository - https://github.com/mlflow/mlflow 

This is very similar to the one described here - #57  issue still persists.

**Comment by jakebailey** [comment]
It's unlikely that #57 is related. Since you mention tensorflow, it may be related to a recent change in decorator behavior that improves type inference, but does appear to hurt performance with tensorflow. If you downgrade to 2021.1.0, do you see your performance improve?

**Comment by mohammedayub44** [comment]
@jakebailey Thanks.
Updating the pylance to latest version `2021.2.0`. Stopping and restarting my remote EC2 machine helped. 
Activations now are very quick as below:
![image](https://user-images.githubusercontent.com/7122670/106853018-037bdf80-6687-11eb-8aea-25d83ff731ea.png)

Closing for now. Will open if I see any issues.
