### ISSUE TITLE
pylance

### ISSUE THREAD

**Issue by selim382** [microsoft/pylance-release#903]
<h3> Environment data </h3>

-   Language Server version: 2021.1.3
-   OS and version: win32 x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

XXX

<h3> Actual behaviour </h3>

XXX

<h3> Logs </h3>

Python Language Server Log
```
XXX 'Please paste the output from your clipboard'
```

<h3> Code Snippet / Additional information </h3>

```python
XXX
```

**Comment by jakebailey** [comment]
You seem to have submitted the auto-generated template before filling it out; did you intended to include info, or was submitting this a mistake?

**Comment by selim382** [comment]
{
	
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pyright/blob/master/docs/configuration.md",
			"path": "/microsoft/pyright/blob/master/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com"
		}
	},
	"severity": 4,
	"message": "Import \"playsound\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 3,
	"startColumn": 6,
	"endLineNumber": 3,
	"endColumn": 15
}

**Comment by jakebailey** [comment]
This is a copy of a diagnostic, yes. Do you have a copy of the code that doesn't work? Is the interpreter which contains `playsound` correctly selected at the bottom left? Do other imports work?

https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md contains some troubleshooting and issue reporting steps that should help.

**Comment by jakebailey** [comment]
This issue has been open with the "waiting for info" label for over a month, so I'm going to close it. If you can answer some of the above questions, I'm happy to reopen.
