### ISSUE TITLE
Wrong interpreter found

### ISSUE THREAD

**Issue by nobody-famous** [microsoft/pylance-release#904]
How does Pylance find the python interpreter to use?

I activated a virtual environment, started VSCode inside that environment, and Pylance could not find modules I had installed with pip. I turned on trace logging and it has this at the end,

> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Pylance language server.
Python interpreter path: /usr/bin/python3
> conda --version

However, when I run that python command from within a VSCode terminal, it gives,

$ python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
/home/rich/work/viasat/env/mando-labs/bin/python

Why does the trace show the interpreter as /usr/bin/python3? I've checked my settings files and don't have any paths set for Python. I'm not sure what I have set wrong that's causing it to ignore the virtual env.

**Comment by jakebailey** [comment]
Pylance does not choose; the core extension does and we accept the interpreter path given to us by the main Python extension (selected at the bottom left).

Which trace logs are you looking at, the Python window, or the "Python Language Server" output? That output above is from the Python extension itself, but Pylance when it asks for the interpreter may not get what's printed there.

Can you enable trace mode and look at the Python Language Server output? https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue has the setting and where to look listed.

**Comment by nobody-famous** [comment]
Awesome, thank you! I didn't notice the selector along the bottom, it had the wrong one selected.

**Comment by fischgeek** [comment]
Based on the above comments, I shouldn't be seeing this issue anymore, but I do. Anyone want to weigh in or should I open a new issue?

![image](https://user-images.githubusercontent.com/4293840/197575240-6c8122ae-7c3b-4fb8-b1e7-78070d984422.png)
