### ISSUE TITLE
Cannot install Pylance 2021.1.3 in a Docker container with "Remote - Containers" plugin

### ISSUE THREAD

**Issue by sqybi** [microsoft/pylance-release#906]
## Environment data

-   Language Server version: 2021.1.3 (not installed)
-   OS and version: Ubuntu 18.04 on host, and Ubuntu 16.04 in Docker container
-   Python version (& distribution if applicable, e.g. Anaconda): 3.5.2

## Expected behaviour

Install the Pylance language server in the container with "Remote - Containers" plugin.

## Actual behaviour

The Pylance language server was installed on the host successfully, but it couldn't be installed in the container.

## Logs

(There are no logs because the plugin is even not installed.)

### What happened

Here is a screenshot of when I tried to install Pylance to my container:

![image](https://user-images.githubusercontent.com/966312/106576943-b14c9880-6578-11eb-9497-fb6c7029046d.png)

After I clicked "Install in Container sqybi/sqybi:tspkg (/tspkg)" (which is my container's image name and name) and waited for a very long while, nothing happened actually.

#### Evidence 1: 

"Go to definition" is disabled when I opened a Python source file and select an identifier in my project with the "Remote - Containers" plugin. As a comparison, I opened the same project and the same file on my host, and the "Go to definition" feature works well.

#### Evidence 2:

The Pylance settings, e.g., `python.analysis.diagnosticMode`, doesn't exist when I connected to a container. Again as a comparison, it exists when I'm not connected to the container. See the figures below.

![image](https://user-images.githubusercontent.com/966312/106578427-75b2ce00-657a-11eb-8c88-f5121ff93547.png)

![image](https://user-images.githubusercontent.com/966312/106578500-882d0780-657a-11eb-9595-235bda193cce.png)

#### Test Environment

All the comparisons are on the same machine with the same VSCode instance. What's more, I have completely restarted VSCode before the test.

**Comment by 13301338176** [comment]
still not work

**Comment by alexpavlidespyrra** [comment]
Im having this same issue.

**Comment by judej** [comment]
@alexpavlidespyrra could you please add the logs? As well as any console output: (Help -> Toggle Developer Tools -> console)

[Getting additional info instructions](https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue)

**Comment by qijiale** [comment]
> still not work

Has the problem been solved？

**Comment by Auxority** [comment]
Nope, this is still an issue.

**Comment by thicolares** [comment]
I use an MBB with Apple Silicon and I've tried to follow [these steps](https://github.com/microsoft/vscode/issues/173327#issuecomment-1416805325). In the end, it worked after I unchecked the Rosetta emulation on Docker Desktop (Features in development > Use Rosetta for x86/amd64 emulation on Apple Silicon) and added `platform: linux/amd64` to the required services in `docker-compose.yaml` file. There're other ways to fix this platform issue, like using the proper image or using this directive in the `Dockerfile` itself.

**Comment by luabud** [comment]
There's an open issue on extension installation issues on devcontainers running on Apple Silicon so I'm going to close this on favour of that: https://github.com/microsoft/vscode-remote-release/issues/8541  

For any other problems with installing Pylance when using any one of the Remote Extensions, I kindly ask folks to file an issue providing logs on the[ vscode-remote-release ](https://github.com/microsoft/vscode-remote-release/issues) repository, so their team can investigate. Thanks!
