### ISSUE TITLE
Suggestion and module documentation info not showing on jupyter notebook

### ISSUE THREAD

**Issue by Mlaouar** [microsoft/pylance-release#909]
## Environment data

-   Language Server version:  Pylance language server 2021.1.3
-   OS and version: Windows 10 v10.0.18363
-   Python version : 3.8.5 64-bit

## Expected behaviour

Show suggestion documentation on a jupyter notebook/ python file

![2](https://user-images.githubusercontent.com/23510172/106742129-e6122b80-661c-11eb-857a-706220928d2f.png)

## Actual behaviour

It works great on python script but not when running a jupyter notebook

![1](https://user-images.githubusercontent.com/23510172/106742282-21145f00-661d-11eb-887b-7d86fb525038.png)

**Comment by jakebailey** [comment]
Is this the old notebooks system, or the new one that uses VS Code's built-in cell system? As far as I know, the old one (where they recreated cells in a webview) does not support some features, while the new one does as the editor is powering everything.

**Comment by jakebailey** [comment]
Just to confirm, do you see an arrow at all to the right on that completion item if you hover it? Does hitting Ctrl+Space expand it out?

**Comment by Mlaouar** [comment]
Thank you for your help, no i can't see an arrow to answer your question, only works when it's a .py file in VS Code. 

I checked and there is a new Jupyter native api (it's what you meant by new version of Jupyter system ?)that is only available on vs code insiders, so i installed insiders and code documentation works perfectly, it seems that we can modify the Jupyter extension project to use the native api on VS Code.

![Untitled](https://user-images.githubusercontent.com/23510172/106794585-59d22980-6659-11eb-9104-8a4397fc844d.png)

**Comment by jakebailey** [comment]
Yes, then this makes sense. There's not really much we can do about this from our end, as it's entirely a UI issue. I'll close this for now (and eventually this will be the default notebook system in Jupyter).

**Comment by Mlaouar** [comment]
Yes it solved the problem for me understanding it's source, i hope it'll be Jupyter default operating Api in the next version of VS Code also, it feels faster and looks better.
