### ISSUE TITLE
pandas MultiIndex levels is unsubscriptable?

### ISSUE THREAD

**Issue by gokturksm** [microsoft/pylance-release#91]
## Environment data

-   Language Server version: Pylance language server 2020.7.0
-   OS and version: W10 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.x

## Expected behaviour

Accessing pandas MultiIndex.levels[...].size should not be shown as a problem.

## Actual behaviour

![image](https://user-images.githubusercontent.com/2174487/87167606-e8561680-c2d5-11ea-874c-478320b6d5b5.png)

## Code Snippet / Additional information

```python
import pandas as pd

multi_index__ = pd.MultiIndex.from_product([list('abc'), list('123')])

multi_index__.levels[0].size
```

**Comment by jakebailey** [comment]
The tooltip indicates that this message is coming from pylint, which is a different diagnostic provider than Pylance. I would check your pylint settings or report an issue on pylint's tracker if you believe this message to be an error. We can't handle that message in Pylance (as we don't run pylint or control its settings).

@erictraut Unrelated, but I think it might be a bug that `multi_index__` is being treated as a type alias, but perhaps not.

**Comment by gokturksm** [comment]
Sorry, didn't see it was from Pylint. Thanks for the explanation.
