### ISSUE TITLE
Opencv intellisence fails

### ISSUE THREAD

**Issue by jahaniam** [microsoft/pylance-release#912]
I am writing a dockerfile and I have `RUN pip install opencv-python`

Pip will install the opencv as sudo in the `/usr/local/lib/python3.6/site-packages/cv2`
I cannot get the autocomplete feature.

![test](https://user-images.githubusercontent.com/13435607/106827318-deb34800-6645-11eb-9e2a-1b88d9f3f0ac.gif)

Here is my tracing output:

```
[Info  - 12:02:54 AM] Pylance language server 2021.1.3 (pyright 61c53da4) starting
[Info  - 12:02:54 AM] Server root directory: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist
[Info  - 12:02:54 AM] No configuration file found.
[Info  - 12:02:54 AM] Setting pythonPath for service "vscode": "/usr/bin/python3"
Search paths found for configured python interpreter:
  /usr/lib/python3.6
  /usr/lib/python3.6/lib-dynload
  /home/vscode/.local/lib/python3.6/site-packages
  /usr/local/lib/python3.6/dist-packages
  /usr/lib/python3/dist-packages
[Error - 12:02:54 AM] stubPath /home/vscode/typings is not a valid directory.
[Info  - 12:02:54 AM] Assuming Python version 3.6
[Info  - 12:02:54 AM] Assuming Python platform Linux
[Info  - 12:02:54 AM] Searching for source files
[Info  - 12:02:54 AM] Found 4249 source files
[Info  - 12:02:54 AM] Background analysis(1) root directory: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist
[Info  - 12:02:54 AM] Background analysis(1) started
Background analysis message: setConfigOptions
Background analysis message: setTrackedFiles
Background analysis message: markAllFilesDirty
Background analysis message: setFileOpened
Background analysis message: getSemanticTokens
[BG(1)] parsing: /home/vscode/x.py (15ms)
[BG(1)] parsing: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/stdlib/3/builtins.pyi [fs read 2ms] (128ms)
[BG(1)] binding: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/stdlib/3/builtins.pyi (48ms)
[BG(1)] binding: /home/vscode/x.py (0ms)
[BG(1)] parsing: /usr/local/lib/python3.6/dist-packages/cv2/__init__.py [fs read 0ms] (8ms)
[BG(1)] binding: /usr/local/lib/python3.6/dist-packages/cv2/__init__.py ...
[BG(1)]   parsing: /usr/local/lib/python3.6/dist-packages/cv2/data/__init__.py [fs read 0ms] (0ms)
[BG(1)]   binding: /usr/local/lib/python3.6/dist-packages/cv2/data/__init__.py (0ms)
[BG(1)] binding: /usr/local/lib/python3.6/dist-packages/cv2/__init__.py (3ms)
[BG(1)] parsing: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi [fs read 1ms] (13ms)
[BG(1)] binding: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/stdlib/2and3/_typeshed/__init__.pyi (2ms)
[BG(1)] parsing: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi [fs read 0ms] (6ms)
[BG(1)] binding: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/third_party/2and3/typing_extensions.pyi (2ms)
[BG(1)] parsing: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/stdlib/3/typing.pyi [fs read 2ms] (38ms)
[BG(1)] binding: /home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2021.1.3/dist/typeshed-fallback/stdlib/3/typing.pyi (12ms)
Background analysis message: getSemanticTokens
Background analysis message: analyze
[BG(1)] analyzing: /home/vscode/x.py ...
[BG(1)]   checking: /home/vscode/x.py (2ms)
[BG(1)] analyzing: /home/vscode/x.py (2ms)
Background analysis message: resumeAnalysis
```

**Solution:**

Opencv IntelliSense fails if it is installed in `/usr/local/lib/pythonX/site-packages`. I have to install it using `pip install --user` which is not common in many Dockerfiles.
It works fine if it is installed under `$HOME/.local/lib/pythonX/site-packages`

**How to reproduce the issue:**

1. make sure to deactivate conda and other environments.
2. sudo pip3 install opencv-python
3. make sure it is installed under  `/usr/local/lib/pythonX/site-packages` : `python -c "import cv2;print(cv2.__file__)"`
4. open vscode and see IntelliSense fails

fix:
```
sudo pip uninstall opencv-python
pip install opencv-python --user
```

PS. I know we should never use sudo pip but sometimes this is unavoidable especially in containers and other provided images. There is something wrong with opencv package being in this directory for intellisense.

Related issue:
https://github.com/microsoft/pylance-release/issues/138

**Comment by chitalian** [comment]
I am running into the same issue. Except doing 
```
sudo pip uninstall opencv-python
pip install opencv-python --user
```

Doesn't solve my issue. 

I don't know how to get tracing info. If someone can show me, I can share

**Comment by jahaniam** [comment]
Check where your opencv is installed. 
for tracing see the related issue. Someone from pylance team shared a link

**Comment by jakebailey** [comment]
https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue has some instructions for trace logging.

**Comment by chitalian** [comment]
I am on macOS. I see a folder called `cv2` here
`/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages`
I also see a folder call `cv2` here
`/Users/<user>/Library/Python/3.8/lib/python/site-packages`

**Comment by jakebailey** [comment]
I'm most interested in trace logs if you can provide them, thanks.

**Comment by chitalian** [comment]
I am thinking my sys.path is a bit messed up. anyway here is the log
[log.txt](https://github.com/microsoft/pylance-release/files/5929632/log.txt)

**Comment by jakebailey** [comment]
That's the "Python" output window; I'm looking for the "Python Language Server" output window when you have logLevel set to Trace.

This is mainly to look for log lines that show that we aren't loading our bundled native stubs.

**Comment by chitalian** [comment]
I am getting it from here? It says `Python Language Server` on the top right?


<img width="2502" alt="image" src="https://user-images.githubusercontent.com/26822232/106979927-1c7ea200-6714-11eb-83d6-ede219e03c1f.png">

**Comment by jakebailey** [comment]
My mistake, thanks.

**Comment by jahaniam** [comment]
what is your output for this?

```
import cv2
print(cv2.__file__)
```

Something is wrong with your python

**Comment by jakebailey** [comment]
Yes, we're failing to even run python to get the normal info we need (sys.path, the python version, etc). That protobuf pth file appears to be causing issues. If we can't call python, we probably won't be able to resolve much of anything. I don't know if your issue is related to the OP.

**Comment by chitalian** [comment]
thanks all - I figured it out. I had a python2 package in my PYTHONPATH. And when I was testing I only reloaded the window. But you have to close the entire process to reset env for vscode.

**Comment by bschnurr** [comment]
closing this issue since I was related to opencv being installed in a different location than the interpreter.

**Comment by bschnurr** [comment]
The next release of Pylance will have a partial stub for opencv, and this should help fix issues where we couldn't match the native stub to the installed user version of opencv.
