### ISSUE TITLE
Pylance says that the return type is non iterable

### ISSUE THREAD

**Issue by enkeyz** [microsoft/pylance-release#914]
## Environment data

-   Language Server version: latest insider
-   OS and version: latest Manjaro Linux
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.1 64bit

## Expected behaviour

No error message from Pylance

## Actual behaviour

Getting error message is that the return type is not iterable(type checking set to basic). The code snippet is running without any error messages tho.
You can find home_timeline() docs here: https://docs.tweepy.org/en/v3.5.0/api.html#API.home_timeline It returns a list.

## Logs

```
XXX
```

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/17646853/106903251-14196d80-66fa-11eb-94d8-25ddce1dfded.png)
![image](https://user-images.githubusercontent.com/17646853/106905398-8ab76a80-66fc-11eb-93ce-5fd6b9667dfe.png)

```python
XXX
```

**Comment by erictraut** [comment]
It looks like you have enabled type checking (i.e. set `python.analysis.typeCheckingMode` to "basic"). If you want to use type checking, you will generally need packages that contain type information — or separate type stubs that provide the additional type information. If Pylance doesn't find any type information, it will do its best to infer types based on the library code, but that often results in incomplete or inaccurate types.  That's what's happening here. The package you're using ("tweepy") doesn't provide any type information. Presumably you haven't installed a type stub for the package. 

Your options include:
1. Disable type checking.
2. Find or create a type stub for the package. Perhaps contact the maintainers of the package and request that they provide inline type annotations for the package.
3. Disable the "python.analysis.useLibraryCodeForTypes" so Pylance doesn't attempt to infer types from the code.

**Comment by jakebailey** [comment]
This issue has been open with the "waiting for info" label for over a month, so I'm going to close it. If the above options don't work for you, we can reopen this.
