### ISSUE TITLE
Code Helper (renderer) uses 100% cpu forever

### ISSUE THREAD

**Issue by christopherhesse** [microsoft/pylance-release#92]
## Environment data

-   Language Server version: [Info  - 10:22:02 AM] Pylance language server 2020.6.1 starting
-   OS and version: Mac OS X 10.15.5
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.7 through anaconda

## Expected behaviour

VSCode does not use a single core at 100% forever.

## Actual behaviour

VSCode uses a single core at 100% forever

## Logs

I can't paste all the log output because it main contain internal company stuff, but here are the last few lines:

```
##########Linting Output - flake8##########
> ~/miniconda3/envs/openai/bin/python ~/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/pyvsc-run-isolated.py flake8 --ignore=E,W --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s <path to internal file1.py>
cwd: ~/code/openai
> ~/miniconda3/envs/openai/bin/python ~/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/pyvsc-run-isolated.py flake8 --ignore=E,W --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s <path to internal file1.py>
cwd: ~/code/openai
##########Linting Output - flake8##########
> ~/miniconda3/envs/openai/bin/python ~/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/pyvsc-run-isolated.py flake8 --ignore=E,W --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s <path to internal file2.py>
cwd: ~/code/openai
> ~/miniconda3/envs/openai/bin/python ~/.vscode/extensions/ms-python.python-2020.6.91350/pythonFiles/pyvsc-run-isolated.py flake8 --ignore=E,W --format=%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s <path to internal file2.py>
cwd: ~/code/openai
##########Linting Output - flake8##########
```

## Code Snippet / Additional information

![image](https://user-images.githubusercontent.com/440336/87198731-b467fa80-c2af-11ea-8288-eb15abe8f5a3.png)

**Comment by christopherhesse** [comment]
In my case, I have a large internal codebase open, so there could be some problematic files in there.

**Comment by jakebailey** [comment]
> Pylance language server 2020.6.1 

The current version is 2020.7.0, which has some significant CPU improvements. #80

Can you update and try that version?

**Comment by christopherhesse** [comment]
This is looking a lot better, thanks!
