### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by davidbrsp** [microsoft/pylance-release#921]
- Issue Type: `Performance`
- Extension Name: `vscode-pylance`
- Extension Version: `2021.2.0`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.53.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/6f/ydwhg02j2l33cnk1f27jzftc0000gp/T/ms-python.vscode-pylance-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jakebailey** [comment]
Do you have the logs that this VS Code template provides? I don't think we can do anything about this without the profile info that says we're causing CPU load.

**Comment by davidbrsp** [comment]
> Do you have the logs that this VS Code template provides? I don't think we can do anything about this without the profile info that says we're causing CPU load.

Here's the Info:

[ms-python.vscode-pylance-unresponsive.cpuprofile.txt](https://github.com/microsoft/pylance-release/files/5934932/ms-python.vscode-pylance-unresponsive.cpuprofile.txt)

**Comment by jakebailey** [comment]
As far as I can tell, the bulk of the time this profile reports is spent accessing the file system (loading node modules, reading other files). If I read the profile itself, your `.vscode` folder (including extensions, settings, etc) appear to be stored in a Google Drive volume. Are you sure this isn't massively slowing down VS Code as a whole when it needs to load things? I wouldn't recommend putting a high-traffic folder like `.vscode` into a synced folder...

**Comment by davidbrsp** [comment]
> As far as I can tell, the bulk of the time this profile reports is spent accessing the file system (loading node modules, reading other files). If I read the profile itself, your `.vscode` folder (including extensions, settings, etc) appear to be stored in a Google Drive volume. Are you sure this isn't massively slowing down VS Code as a whole when it needs to load things? I wouldn't recommend putting a high-traffic folder like `.vscode` into a synced folder...

Put .vscode directory on default home user folder and everything works like charm! Thank you very much
