### ISSUE TITLE
Import "tablib" could not be resolved Pylance(reportMissingImports)

### ISSUE THREAD

**Issue by Shashank-sankey** [microsoft/pylance-release#922]
**Describe the bug**
while importing "from tablib import Dataset" vscode is showing the warning Import "tablib" could not be resolved Pylance(reportMissingImports)

**To Reproduce**
import the package as "from tablib import Dataset" you will get this warning

**Expected behavior**

**Screenshots or Code**
![image](https://user-images.githubusercontent.com/67677169/106999384-189e5e80-67ac-11eb-97c5-4816e7312bc0.png)

**VS Code extension or command-line**
pylance

**Comment by jakebailey** [comment]
Do you have the environment where `tablib` is installed selected at the bottom left?

**Comment by ianpatrickbuss** [comment]
I am having some issues with this as well.

```
$ pip3 install Faker
Requirement already satisfied: Faker in /home/ian/.local/lib/python3.8/site-packages (6.4.1)
Requirement already satisfied: text-unidecode==1.3 in /home/ian/.local/lib/python3.8/site-packages (from Faker) (1.3)
Requirement already satisfied: python-dateutil>=2.4 in /usr/lib/python3/dist-packages (from Faker) (2.7.3)
```
Though it is unable to detect the installed dependency or use auto-complete.
![python](https://user-images.githubusercontent.com/31316609/108754111-88824800-7513-11eb-9885-c49b3d7e0d59.png)

Is Pylance looking for the dependency in a specific directory or does it need to be remapped to a separate dependency?

**Comment by jakebailey** [comment]
I'm not sure your issue is strictly related, it just has the same diagnostic. Can you open a new issue and fill out the issue template with trace logs?

**Comment by jakebailey** [comment]
This issue has been open for over a month without a response to my environment question; we can reopen this if you're still seeing the issue. Logs and your environment info would be helpful.
