### ISSUE TITLE
Ошибка импорта файлов находящихся в одной и той же папке

### ISSUE THREAD

**Issue by chicago666666** [microsoft/pylance-release#924]
Issue Type: <b>Bug</b>

"view" is not accessedPylance
Import "view" could not be resolved Pylance report MissingImports
Import "config" could not be resolved Pylance report MissingImports
Import "posts.blueprint" could not be resolvedPylancereportMissingImports

Файл точно есть =) и всё работает как книжка пишет, но всё время пишет "ощибка, ощибка, ощибка,..." Бесит - честно)

Extension version: 2021.2.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-3420M APU with Radeon(tm) HD Graphics (4 x 1497)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.47GB (1.02GB free)|
|Process Argv|--crash-reporter-id 87014751-308c-4a9e-a92f-50c25eafd942|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by judej** [comment]
@chicago666666, thanks for the report. Could you please send us a code snippet for the repro as well as send more information using the guideline set in https://github.com/microsoft/pylance-release/blob/main/TROUBLESHOOTING.md#filing-an-issue 

thanks

**Comment by jakebailey** [comment]
This issue has been open with the "waiting for info" label for over a month, so I'm going to close it.

**Comment by DaSh-More** [comment]
## How to reproduce the error
1) Create filse main.py and funcs.pyw in one folder
2) Write the code to the file funcs.pyw:
``` python
def test_func():
    print('hello')
```

2) Write the code to the file main.py:
``` python
from funcs import test_func

test_func()
```

Pylance print:
Import "test9" could not be resolved

---
## Full error info

``` json
[{
	"resource": "/d:/Programs/Python3/test_progs/temp/main.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"funcs\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 6,
	"endLineNumber": 1,
	"endColumn": 11
}]
```
