### ISSUE TITLE
pylance cannot correctly recognize array objects in numpy module.

### ISSUE THREAD

**Issue by CatNofishing** [microsoft/pylance-release#93]
## Environment data
version: 1.46.1 (user setup)
commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

 Language Server version: pylance 2020.7.0
 Python version (& distribution if applicable, e.g. Anaconda): 2020.6.91350

## describe
pylance cannot correctly recognize array objects in numpy module. I cannot get any attribute hints for array object. 
Even, I can't get the correct api hint for array function.

![image](https://user-images.githubusercontent.com/33288114/87211556-a1573800-c34c-11ea-96c5-ca36b2f5c726.png)
![image](https://user-images.githubusercontent.com/33288114/87211672-23dff780-c34d-11ea-8d00-aef4bbc7d1c8.png)

**Comment by moritzwilksch** [comment]
Same for me, on Mac.

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by jakebailey** [comment]
Numpy contains a lot of compiled code; we currently don't have a scraper that will create type stubs for compiled modules.

I believe that numpy will be shipping type stubs (as the numpy-stubs repo was merged upstream), so I would expect this to get better in the next numpy release.

**Comment by moritzwilksch** [comment]
Ahh, interesting. For me, that leaves pylance in a kind of latent state where I’d love to use it for its speed and suggestion quality but without support for NumPy or Keras I’ll have to stay with the MS Python Language Server for a while. Anyway, thanks for the heads-up!

**Comment by jakebailey** [comment]
Closing in favor of #150. Note that the next release of numpy is likely to include stubs which should greatly improve its usability.

**Comment by EdPS** [comment]
@jakebailey this not only happens with numpy. The same issue happens to me with numpy and also the Image class in the Pillow module as of today. This surely happens with many other modules. The fix for me was to move back to the Jedi Language Server. If Jedi can manage it, Pylance should also be able to. I don't think numpy or all modules taht could share the same problem are to blame.
