### ISSUE TITLE
slow speed of renaming a variable/symbol

### ISSUE THREAD

**Issue by lrwagner** [microsoft/pylance-release#938]
Not sure if this is an issue but renaming a function, class or arguments takes a lot longer than renaming a simple variable (about 30s vs almost instantly) which hurts the overall experience with pylance. The project is not really big, about ~1000 lines of code split among a few files. Is there something I can do to improve the performance?

**Comment by lrwagner** [comment]
probably duplicate of #882

**Comment by erictraut** [comment]
Renaming a symbol that is local to a single module will always be faster than renaming a symbol that is global to a project. The latter requires pylance to open, read, parse, and bind all of the files in the project. It caches this information the first time it's done, but it will be slow on the first rename or "find all references" operation.

If you enable analysis of all files in the project (i.e. set "python.analysis.diagnosticMode" to "workspace"), all files in the workspace will be analyzed when you open the workspace, so the first rename or "find all references" will be fast.
