### ISSUE TITLE
Type error report for a code snippet from the Python docs on typing.overload

### ISSUE THREAD

**Issue by Telofy** [microsoft/pylance-release#943]
I have some code along the lines of the example from the [documentation section of the `typing.overload` decorator](https://docs.python.org/3/library/typing.html#typing.overload). Here a slightly modified version that I would expect to be syntactically and type-wise correct.

```python
from typing import overload

@overload
def process(response: None) -> None:
    ...

@overload
def process(response: int) -> tuple[int, str]:
    ...

@overload
def process(response: bytes) -> str:
    ...

def process(response):
    if isinstance(response, int):
        return (response, "Narf")
    if isinstance(response, bytes):
        return str(response)
```

I get this type error:

![image](https://user-images.githubusercontent.com/223663/107693995-1f970680-6caf-11eb-9438-ec2529aef591.png)

How do I use `overload` in a way that avoids this issue?

Thank you!

**Comment by erictraut** [comment]
`overload` is applied when a function is invoked. It is not used for the function definition itself.

For the function definition, you'll need to specify type annotations that are unions of all accepted and return types, like the following:

```python
def process(response: Optional[Union[int, bytes]]) -> Optional[Union[tuple[int, str], str]]:
    if isinstance(response, int):
        return (response, "Narf")
    if isinstance(response, bytes):
        return str(response)
```

**Comment by Telofy** [comment]
Thanks! But oh, that’s sad. I’ll need to read up on what `overload` is even good for then for static type-checking.

But is there any way to capture the notion (from the overload version) that such combinations as `bytes -> None`, `int -> str`, etc. are invalid?

**Comment by erictraut** [comment]
Overloads are meant to describe the externally-visible behavior of a function that accepts different input types. It's up to the implementation to handle these different inputs appropriately (e.g. by performing isinstance checks, like your example above). It's also up to the implementation to return values whose types conform to the return types in the overloads.

If I understand your question correctly, you're wondering if a type checker will enforce that the implementation honors all of the overload signatures. The answer is no. I'm not aware of any type checkers or compilers in any programming language that do this.

**Comment by jakebailey** [comment]
TS does verify that an overload's signature is compatible with the final implementation:

![image](https://user-images.githubusercontent.com/5341706/107700104-dd98a100-6c6b-11eb-88e2-1593851d07ac.png)

Versus:

![image](https://user-images.githubusercontent.com/5341706/107700156-f2753480-6c6b-11eb-87db-114e652df470.png)

**Comment by jakebailey** [comment]
But of course internally, it's up to the implementer to do the right thing. I don't believe that it's trying to match parameters based on narrowing to "figure out" which signature is being implemented to restrict return types.

**Comment by Telofy** [comment]
@erictraut 

Yeah, I think I just misunderstood what `overload` is meant for. (I imagined it similar to the multiple function implementations that you have in Haskell to pattern-match the input types.)

But apart from my general curiousity about how type annotations work, I also have the practical issue that in my program, the equivalent of `int -> None` would be a bug, and that I’d like to catch it statically. I found out about `overload` and thought it was meant for that case. But I suppose it does something else.

I’ve solved it like this for now (my actual implementation is a bit less ugly and roundabout):

```python
from typing import Optional, Union

def _process_none(response: None) -> None:
    ...

def _process_int(response: int) -> tuple[int, str]:
    return (response, "Narf")

def _process_bytes(response: bytes) -> str:
    return str(response)

def process(response: Optional[Union[bytes, int]]):
    if isinstance(response, int):
        return _process_int(response)
    if isinstance(response, bytes):
        return _process_bytes(response)
    return _process_none(response)
```

@jakebailey 

Oh, thanks for the TS example!

**Comment by erictraut** [comment]
>TS does verify that an overload's signature is compatible with the final implementation:

This isn't quite correct. TypeScript verifies that an overload's signature is compatible with the implementations _signature_, not the implementation itself. (I wasn't aware that TypeScript did even that, so thanks for pointing it out, Jake.)

**Comment by jakebailey** [comment]
Sorry, I left out the word "signature". Probably should have written "final implementation's" to be clearer; I did mean the signature.

I wonder if we could do something like that... Sounds like a few expensive assignment checks, though. Probably no worse than the override checks.

**Comment by jakebailey** [comment]
Is there any work left to do here, or has the question been answered well enough?

It'd be interesting to have the check that overloads match the signature of the final function, but that doesn't really change the type we infer things as when they are unannotated.

**Comment by Telofy** [comment]
Yep, all good, and I’m happy to have solved it another way. Thank you for your help!
