### ISSUE TITLE
Feature Request: Check for duplicate class

### ISSUE THREAD

**Issue by hudcap** [microsoft/pylance-release#945]
In similar vein to #865, it would be great if `pylance` could report a duplicate class being defined.

MWE:

```
class foo:
    def bar(self):
        return 0

class foo:
    def bar(self):
        return 1
```

**Comment by erictraut** [comment]
Pylance already supports this functionality. You need to enable the type checker though. In other words, set `python.analysis.typeCheckingMode` to "basic".

**Comment by hudcap** [comment]
Thank you!
Is there a list somewhere of what checks are included in "basic" and "strict"? I searched, but I can't find more than what I could infer from the names of the settings.

**Comment by hudcap** [comment]
For reference, I found it here: https://github.com/microsoft/pyright/blob/master/docs/configuration.md#diagnostic-rule-defaults
