### ISSUE TITLE
Pylance: import from same directory could not be resolved

### ISSUE THREAD

**Issue by adamwass** [microsoft/pylance-release#948]
![image](https://user-images.githubusercontent.com/36089488/107843639-f5bb0e00-6d9a-11eb-867a-087c609e5e36.png)

Despite the script `Mesh.py` being in the same directory as `Simulation.py`, Pylance cannot resolve the import. I have tried adding the folder in which both scripts reside using `extraPaths` in the `settings.json` file like so:
```
{
    "python.analysis.extraPaths": [
        "/home/adamwass/Documents/ASO/"
    ]
}
```

However, this had no effect. Interestingly enough, if I use `from .Mesh import *`, Pylance can then resolve it. However, the code will not run then because of the error: `ImportError: attempted relative import with no known parent package`. So basically, I have to choose between Pylance linting and the code actually running right now.

**System Information:**
Linux Virtual Machine
Ubuntu 20.04
Python 3.8.5
VScode v1.53.2
Python Extension for VScode v2021.1.502429796
Pylance v2021.2.2

**Comment by adamwass** [comment]
It turns out this issue was entirely on my end. My workspace folder was set to the default `.tmp` folder for VScode instead of the folder in which the scripts reside. Changing the workspace root to the parent folder for `Simulation.py` solved the problem.

**Comment by sylwekb** [comment]
@adamwass worked for me, thank you!

**Comment by Bikeman868** [comment]
I have this exact same problem but I can't find any settings for Workspace root in VS Code v1.57.0
Where were these settings in VS Code v1.53.2?
Thanks

**Comment by adamwass** [comment]
> I have this exact same problem but I can't find any settings for Workspace root in VS Code v1.57.0
> Where were these settings in VS Code v1.53.2?
> Thanks

It's not in settings. Go to File > Open Folder and navigate to your working directory.
