### ISSUE TITLE
Pylance 2020.7.1 not working 

### ISSUE THREAD

**Issue by Trid-collab** [microsoft/pylance-release#95]
Issue Type: <b>Bug</b>

My Pylance ver just got upgraded to 2020.7.1. Since the upgrade, Pylance has stopped working. VS Code has become slow and times unreponsive.  I have de installed and tried the earlier ver 2020.7.0 which seems to work.

Extension version: 2020.7.1
VS Code version: Code 1.47.0 (d5e9aa0227e057a60c82568bf31c04730dc15dcd, 2020-07-09T08:02:06.629Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.68GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jakebailey** [comment]
2020.7.0 had a significant regression which prevented a number of features from working including all diagnostics. I wouldn't recommend using it (even over 2020.6.1).

Can you provide any other information? Our bug template should have asked for logs, screenshots, etc, which would help us in identifying the problem.

**Comment by Trid-collab** [comment]
Withdrawing this issue. It seems to working fine. It might have something to do my i5 laptop. It seems working fine. I have have also tested it on my i7 machine. Both seem to working now.
