### ISSUE TITLE
__builtins__ reported as undefined

### ISSUE THREAD

**Issue by janosh** [microsoft/pylance-release#954]
## Environment data

-   Language Server version: v2021.2.2
-   OS and version: macOS 11.2.0
-   Python version: 3.8.5

## Expected behavior

`__builtins__` is recognized as built-in.

## Actual behavior

```
"__builtins__" is not defined (Pylance reportUndefinedVariable)
```

![Screen Shot 2021-02-16 at 12 17 03](https://user-images.githubusercontent.com/30958850/108055935-ed8bf880-7050-11eb-88b4-471165f71568.png)

## Code Snippet / Additional information

```python
hasattr(__builtins__, "__IPYTHON__")
```

**Comment by erictraut** [comment]
I think `__builtins__` is an internal implementation detail, not something anyone should be relying on. See here: https://docs.python.org/3/library/builtins.html. As such, I think it's appropriate for Pylance to flag it as not defined. You can, of course, suppress the diagnostic if you want.

**Comment by janosh** [comment]
Oh right, my bad.
