### ISSUE TITLE
Add docstrings for builtins

### ISSUE THREAD

**Issue by akshitgupta29** [microsoft/pylance-release#96]
Please add the functionalities of being able to view the documentation for the default python functions. Was able to see in the "Microsoft" LS, but is missing in the Pylance.

![image](https://user-images.githubusercontent.com/12370891/87230333-094d6300-c3cd-11ea-8811-c9254abc2fc2.png)

## Environment data

-   Language Server version: XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX

## Expected behaviour

XXX

## Actual behaviour

XXX

## Logs

```
XXX
```

## Code Snippet / Additional information

```python
XXX
```

**Comment by jakebailey** [comment]
Docstrings for builtin functions are something we're planning on solving, yes. For these files, the documentation is not in any `.py` file we can read, so they're a bit more difficult to extract on the fly (compared to "normal" code where we can consult the real implementation in addition to stubs).

**Comment by akshitgupta29** [comment]
Thaks...same was available in the MS Python Language Server.

**Comment by LordKa0S** [comment]
Similar #49

**Comment by jakebailey** [comment]
Thanks, they're the same underlying issue. I'll close this on in favor of #49.
