### ISSUE TITLE
Type Hint Implies Mandatory Type Assignment

### ISSUE THREAD

**Issue by berkdemir** [microsoft/pylance-release#960]
For type hints, the warning by Pylance does not seem to fit the definition by [PEP 484](https://www.python.org/dev/peps/pep-0484/). According to PEP 484:

> It should also be emphasized that Python will remain a dynamically typed language, and the authors have no desire to ever make type hints mandatory, even by convention.

## Expected behaviour

Pylance should warn about the typehints in the function, but should not force the user.

## Actual behaviour

Pylance says that "cannot be assigned"
![image](https://user-images.githubusercontent.com/40423004/108316060-66b05a80-71cd-11eb-889c-1ad517e30d19.png)

## Recommendation

Parameter "z" is requested as "int" by function "trial" while current assignment is "float".

## Code to Reproduce

```python
def trial(x: float, y: str, z: int) -> str:
    return str(x * z) + y


print(trial(2, "aa", 3.2))
```

**Comment by erictraut** [comment]
By default, static type checking is disabled in pylance. I presume that you have enabled it by setting "python.analysis.typeCheckingMode" to "basic". When type checking is enabled, type violations are reported as indicated in PEP 484. If you aren't interested in seeing these errors, you can set "python.analysis.typeCheckingMode" to "off".

The idea behind type annotations is to document type constraints for inputs to functions and to notify you if you violate those constraints. Don't think of them as "type hints". That's exactly what this error message is telling you. The input parameter `z` is annotated to accept only `int` arguments, but you're violating that by passing it a `float` argument. That indicates that there's a bug in either the caller or the callee.

**Comment by berkdemir** [comment]
I completely agree with what you said. It's just the wording should be adjusted to comply with PEP. Do you think "cannot be assigned" is true? It can be. But it shouldn't be.

**Comment by erictraut** [comment]
No, it cannot be assigned without violating type constraints.

**Comment by berkdemir** [comment]
It's not a constraint, it's a hint and it is not mandatory. 

> authors have no desire to ever make type hints mandatory, even by convention.

**Comment by erictraut** [comment]
When a static type checker is enabled, type annotations are treated as type constraints. That's the whole purpose of static type checking.

The statement "authors have no desire to ever make type hints mandatory, even by convention" means that annotations can be omitted if you are not interested in static type checking. The code will still run in the interpreter, and there are no runtime type checks performed.

**Comment by berkdemir** [comment]
Again, pylance's statement that "cannot be assigned" is not true based on these definitions. However, it is my last post, if you do not agree, we can close it.

**Comment by erictraut** [comment]
When you enable the type checker in pylance, it enforces a set of type consistency rules that are spelled out in PEP 484. If one of those rules is violated, it's the job of a type checker to tell you about the rule that was violated so you can correct it. In this particular case, the result of an expression cannot be assigned to another variable or parameter if the type of that expression is incompatible with the type declared for the target variable or parameter. By the type consistency rules, it cannot be assigned. I don't know how the error message could more clearly communicate the rule violation.

Let's take another example that might make things more clear for you. Imagine that you enabled a code style checker (like pylint) that enforces a line length of 80 characters. If your code includes a line that is 90 characters long, it would be reasonable for pylint to report an error with the message "Line length cannot exceed 80 characters". Clearly the program will still run, but you asked the tool to enforce this additional rule. Would you consider it inappropriate or misleading for pylint to say "Line length cannot exceed 80 characters"?

**Comment by berkdemir** [comment]
It is probably due to my English that I cannot express myself clearly.
I have no argument against this statement:
> it's the job of a type checker to tell you about the rule that was violated so you can correct it

However, as you said:
> Clearly the program will still run,

So, my only recommendation is the changing the wording "cannot". Because **it can** as you said.
**_Currently, pylance says_:** cannot be assigned to parameter
**_My recommendation is something like:_** Parameter "z" is requested as "int" by function "trial" while current assignment is "float".
It's all about informing the developer **correctly.** Current warning is not correct. It can assign it, but pylance should warn against it.

**Comment by erictraut** [comment]
You _cannot_ assign it without violating the type checking rules you have asked the tool to enforce. Just as if you had requested pylint to enforce the 80-character rule and it told you "Line length cannot exceed 80 characters".

**Comment by berkdemir** [comment]
OK, closing the issue.
