### ISSUE TITLE
Analysis Diagnostic Severity Overrides Should be in Alphabetical Order

### ISSUE THREAD

**Issue by berkdemir** [microsoft/pylance-release#961]
## Expected behaviour

Alphabetical order in analysis diagnosic severity overrides in settings.

## Actual behaviour

It is not clear to me what the order was, probably it depends on the timeline of development. Since no search is available, it would be great to order those. (It is great to have these overrides in a GUI!)
![image](https://user-images.githubusercontent.com/40423004/108317389-408bba00-71cf-11eb-812c-c4753bb28f8f.png)

**Comment by erictraut** [comment]
The ordering is intentional. They are sorted and grouped by related functionality. For more details, see [this documentation](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md).

**Comment by berkdemir** [comment]
If it's intentional, OK. It was just bad user experience for me to find the one I was looking for.
