### ISSUE TITLE
False positives with __annotations__

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#965]
<h3> Environment data </h3>

-   Language Server version: 2021.2.3
-   OS and version: darwin x64
-   Python: 3.9.1
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

The module variable `__annotations__` should be recognized correctly.

<h3> Actual behaviour </h3>

See screenshot below

<h3> Logs </h3>

--

<h3> Code Snippet / Additional information </h3>

<img width="760" alt="Screen Shot 2021-02-18 at 19 49 26" src="https://user-images.githubusercontent.com/30130371/108406229-6aba9780-7222-11eb-9248-33905cef5abd.png">

```py
var: int = 42

print(__annotations__)
```

The python output in **3.9.1** is:
```
{'var': <class 'int'>}
```

**Comment by jakebailey** [comment]
Where is this defined in the Python docs or PEP? I know we already support a few of these that are documented: https://github.com/microsoft/pyright/blob/f2ff105380c71d17b729934da867e258a1ed6228/packages/pyright-internal/src/analyzer/binder.ts#L225-L235

**Comment by jakebailey** [comment]
Since you updated the title to mention `__builtins__`, see #954.

**Comment by cdce8p** [comment]
> Where is this defined in the Python docs or PEP? I know we already support a few of these that are documented: https://github.com/microsoft/pyright/blob/f2ff105380c71d17b729934da867e258a1ed6228/packages/pyright-internal/src/analyzer/binder.ts#L225-L235

I noticed it while investigating #964 and looking at the output of `locals()` since I wanted to see if any of them worked.
I only found PEP [3107](https://www.python.org/dev/peps/pep-3107/) that mentions it in the context of function annotations. Could be an implementation detail for modules although it seems to work just as expected.

> Since you updated the title to mention __builtins__, see #954.

Removed the reference. Should have checked beforehand.

**Comment by jakebailey** [comment]
I see. I don't think we'd want to special case more of these if they aren't properly documented as being available on every module. I did find that PEP, but it only mentioned functions (as you said).

**Comment by cdce8p** [comment]
> I see. I don't think we'd want to special case more of these if they aren't properly documented as being available on every module. I did find that PEP, but it only mentioned functions (as you said).

I'm fine with that
