### ISSUE TITLE
Auto-import confuses package and class with same name and different case

### ISSUE THREAD

**Issue by syagev** [microsoft/pylance-release#97]
## Environment data

-   Language Server version: 2020.7.1
-   OS and version: 10 (18363)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.6

## Expected behaviour

Using PyLance "Quick Fix" feature on the following code should suggest to add `from abc import ABC`:

```python
class myclass(ABC):
    pass
```

## Actual behaviour

Suggested imports all reference package `abc`, if it is clicked, **the written code is changed!** (IMO an "auto-import" quick-fix should never modify the code from which it was activated, it's very confusing).

## Code Snippet / Additional information

![pylance_bad_auto_import](https://user-images.githubusercontent.com/5247438/87242659-7564b100-c437-11ea-92f6-c75099c298c5.gif)

**Comment by jakebailey** [comment]
For clarity, the Pylance is fuzzy in these quick fixes, showing instances where the case may not match in case you have misspelled a module or similar. It's doing the right thing in that it's offering you things and replacing them on selection; if you click on a quick fix it's going to fix the code.

The core issue is that the quick fix `import abc` is not the right fix for this code, `from abc import ABC` is, but we don't yet have support for fixes that involve variables inside of unimporteed modules (only module names themselves).

**Comment by heejaechang** [comment]
should work in next version.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2020.9.0, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/master/CHANGELOG.md#202090-3-september-2020
