### ISSUE TITLE
Issue with auto import/code action for Numpy

### ISSUE THREAD

**Issue by MattisTrygstad** [microsoft/pylance-release#970]
## Environment data

-   Language Server version: v2021.2.4-pre.1
-   OS and version: MacOS Mojave 10.14.5
-   Python version (& distribution if applicable, e.g. Anaconda): pyenv 3.8.6

## Expected behaviour

If I write `numpy.` or `np.` and open code action suggestions, `import numpy` or `import numpy as np` should be listed. This works fine for other libraries such as `matplotlib` and abbreviation `plt`.

## Actual behaviour

Numpy import is not suggested even though it is installed and accessible by the current Python interpreter. When I import numpy manually it is recognized.

## Logs

N/A

## Code Snippet / Additional information

![](https://raw.githubusercontent.com/MattisTrygstad/img/main/issue.gif)

**Comment by MattisTrygstad** [comment]
This is my current User settings related to Python. I encounter the same issue without `"python.analysis.indexing": true`.
```
  "python.linting.enabled": true,
  "files.autoSave": "off",
  "python.languageServer": "Pylance",
  "editor.formatOnPaste": true,
  "python.formatting.provider": "autopep8",
  "python.formatting.autopep8Args": ["--ignore=E501"],
  "python.showStartPage": false,
  "[python]": {
    "editor.defaultFormatter": "ms-python.python"
  },
  "files.exclude": {
    "**/__pycache__": true
  },
  "python.autoComplete.extraPaths": ["${workspaceFolder}/src"],
  "python.analysis.extraPaths": ["${workspaceFolder}/src"],
  "python.pythonPath": "/Users/mattis/.pyenv/shims/python",
  "pylance.insidersChannel": "daily",
  "python.analysis.typeCheckingMode": "off",
  "python.analysis.autoImportCompletions": true,
  "editor.accessibilitySupport": "off",
  "python.analysis.indexing": true
```

**Comment by MattisTrygstad** [comment]
I would also like to add that auto import of numpy worked fine previously, this has only been an issue for the last couple of weeks. Let me know if you need any further info.

**Comment by erictraut** [comment]
Which version of numpy are you using? The latest version (1.20) contains inlined type information. If you're able to upgrade to that version, please give it a try and let us know if that addresses your issue.

**Comment by MattisTrygstad** [comment]
Thank you for the reply. I'm currently using numpy 1.20.1. So far I've tried reinstalling VS Code, the Python and Pylance extension, as well as created a new python installation and environment using pyenv virtualenv without any luck.

**Comment by judej** [comment]
Thanks for the report, will investigate this. 

In the meantime, would you ensure that numpy is installed? 

thanks!

**Comment by jakebailey** [comment]
Mainly, do an `import numpy` to see if it's resolved; we don't offer it if we can't resolve it, so if there's a problem there the issue may show as "quick fix doesn't work".

**Comment by MattisTrygstad** [comment]
I can confirm that the interpreter recognises numpy when its imported manually. All functionality works and there is no squiggly line under the import statement. I have been working with numpy daily with the slight inconvenience that the library has to be imported manually. The auto import/code action works with every other library except numpy. I just tried with a new virtualenv with a new numpy installation with the same result. Please let me know if there is anything else i can try.

**Comment by savannahostrowski** [comment]
Hey there - we've tested this out and this is working on the latest version of Pylance. Please update to 2021.3.0!
