### ISSUE TITLE
Suggestion of __init_subclass__ should not require classmethod decorator

### ISSUE THREAD

**Issue by cdce8p** [microsoft/pylance-release#972]
<h3> Environment data </h3>

-   Language Server version: 2021.2.3
-   OS and version: darwin x64
-   Python version: 3.9.2
-   python.analysis.indexing: true
-   python.analysis.typeCheckingMode: strict

<h3> Expected behaviour </h3>

Suggestion results when writing methods should include `__init_subclass__`. The `@classmethod` decorator is implicitly applied and thus not required. See example int [PEP 487](https://www.python.org/dev/peps/pep-0487/#proposal) and the [explanation](https://www.python.org/dev/peps/pep-0487/#requiring-an-explicit-decorator-on-init-subclass).

<h3> Actual behaviour </h3>

`__init_subclass__` is only suggested if the `@classmethod` decorator is used.

<h3> Code Snippet / Additional information </h3>

```python
class Parent:
    def __init  # show suggestions here
```

<img width="585" alt="Screen Shot 2021-02-20 at 23 45 42" src="https://user-images.githubusercontent.com/30130371/108610430-c11c0780-73d5-11eb-954e-677de2caecf7.png">

<img width="570" alt="Screen Shot 2021-02-20 at 23 45 23" src="https://user-images.githubusercontent.com/30130371/108610437-cd07c980-73d5-11eb-990d-7d69a1d0b139.png">

**Comment by erictraut** [comment]
Thanks for reporting the problem. This symbol is unfortunately inconsistent with all other class methods in that it doesn't require a `@classmethod` decorator. I've added special-case handling in the completion handler to accommodate this exception. This will be fixed in the next release.

**Comment by jakebailey** [comment]
This issue has been fixed in version 2021.2.4, which we've just released. You can find the changelog here: https://github.com/microsoft/pylance-release/blob/main/CHANGELOG.md#202124-24-february-2021
