### ISSUE TITLE
"Go To Definition" is limited compared to PyCharm

### ISSUE THREAD

**Issue by gsutra** [microsoft/pylance-release#975]
In PyCharm, it seems that "Go To Definition" is searching for any function/method/class candidate with the same name, even if the imports are missing, even if the types are not correct or undefined/unknown. In the screenshot below, imports are missing, and code analysis should not be able to find the definition of `myMethod`. Still PyCharm finds two `myMethod` methods in the root directory, and proposes them as candidate.
It would be helpful if pylance could also propose candidates based only on name matching, rather than code analysis/inspection.

### PyCharm

![pycharm](https://user-images.githubusercontent.com/14281560/108697539-4b15be80-7503-11eb-865e-4205410b4048.png)

### VS Code

![vscode](https://user-images.githubusercontent.com/14281560/108697558-4ea94580-7503-11eb-82db-ef56bc757c5c.png)

**Comment by jakebailey** [comment]
Where are `Cat` and `Dog` defined? If they don't exist, we will infer the return type of that `createAnimal` function as `Unknown` and then not know anything. PyCharm's analysis method is quite different than a typical type checker, and it's somehow deciding (without evidence) that `Cat` and `Dog` are classes, and that `myMethod` exists on them.

Actually make the code valid, and we have the same behavior:

![image](https://user-images.githubusercontent.com/5341706/108752880-e2c1df80-74f8-11eb-9910-55a5818ebe18.png)

**Comment by erictraut** [comment]
The main value of "Go to Definition" is to show the precise definition used for the selected symbol. Showing all definitions in the project that happen to share the same name would greatly reduce the value of this feature. The behavior you describe would also be inconsistent with the intended use of "Go To Definition" in the language server protocol.

**Comment by jakebailey** [comment]
Yeah, I don't think this is a good idea... This is a constrained case where there really is only one option. what if there are many? Should it search all libraries for potential candidates too? And so on...

**Comment by erictraut** [comment]
Incidentally, there's already a way to search for a symbol by name within the project. Choose "Go To Symbol in Workspace" (command-T on Mac OS), then start typing the first few characters of the symbol you want to look up.

**Comment by jakebailey** [comment]
I don't see us doing this. Note that we already provide diagnostics with quick fixes that would automatically fix this code (hover on the squiggles for `Cat` and `Dog` with indexing enabled and you'll get auto-imports).

**Comment by gsutra** [comment]
> This is a constrained case where there really is only one option. what if there are many?

I totally agree with you two @erictraut and @jakebailey : the behaviour proposed by PyCharm is not relevant when the exact/precise definition is already found. But it is relevant when nothing is found : user can still find something, and in many cases the candidates make sense, because there are not so much `foo` name in a real project, thus not so much false candidates.

> Choose "Go To Symbol in Workspace" 

I did not know this feature, and it does the job well, thank you :+1: 

> quick fixes that would automatically fix this code

The point is not to fix the code. Python allows duck typing, and thus you can write valid code where it is not possible to predict the type of objects. You might guess the type, but without certainty. In such cases, name based candidates are relevant for the developer.
