### ISSUE TITLE
When Selecting python interpreter, list venvs from `venvs` option specified in pyrightconfig.json 

### ISSUE THREAD

**Issue by MHDante** [microsoft/pylance-release#995]
Not urgent! But pyright already asks you to keep venvs in a folder, so it would be useful to use that same setting to facilitate interpreter switching.

**Comment by jakebailey** [comment]
It's the Python extension that offers that UI; we just ask them for which one the user selected. If you think this should be a heuristic for them to select options, you may want to consider asking them, but I think they already should be detecting them in their interpreter detection (which is currently being reworked).

**Comment by MHDante** [comment]
sounds good, I'll post there!
